### ISSUE TITLE
matplotlib.pyplot.figlegend not working with Patches

### ISSUE THREAD

**Issue by cristi-neagu** [matplotlib/matplotlib#10005]
Hello,

I'm trying to create a custom legend using `pyplot.figlegend`. I need to use `figlegend` because i want a single legend on a plot with multiple subplots. I also need to create custom patches to represent different plot colors. But `figlegend` keeps returning an error.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

data = np.random.rand(1000)
colors = ['C0', 'C1', 'C2']
labels = ['l1', 'l2', 'l3']
patches = [mpatches.Patch(color=color, label=label) for color, label in zip(colors, labels)]

plt.plot(data)
plt.figlegend(handles=patches, loc='upper right')
plt.show()
```

```
lib\site-packages\matplotlib\figure.py:1506: UserWarning: No labeled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labeled objects found. "
```
I have also tried the following, with exactly the same result:

```python
plt.figlegend(handles=patches, labels=labels, loc='upper right')
```

  * Operating system: Windows 7
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.6.1 

Matplotlib installed via pip. I get this result both in Jupyter and in the console.

Thanks.

**Comment by cristi-neagu** [comment]
Issue solved in version 2.1.1.

**Comment by tacaswell** [comment]
Can you try with 2.1.1 (just released).  I can not reproduce this:

![so](https://user-images.githubusercontent.com/199813/34062882-dfbbf6d6-e1bc-11e7-96c4-317ae9f9df42.png)

**Comment by tacaswell** [comment]
Ah, great!  I had a stale tab open, sorry for the noise!
