### ISSUE TITLE
TST: `mlab.cohere` needs a test

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#10012]
### Missing test:

`mlab.cohere` has no test.    That led to a pretty nasty bug getting through.  Test logic is not simple.  I could put together an easy one at the end, or @QuLogic  could do it properly.

cross-ref #10003 #10004 

ping @duncanmmacleod

**Comment by QuLogic** [comment]
You're confusing me with someone who actually understands mlab. 😛  I only removed a million repetitive classes that differed only in options (like fft size) by using parametrization.

**Comment by jklymak** [comment]
I understand mlab, but don't understand test paremeterization.  Together we could be unstopable.
