### ISSUE TITLE
Documentation mistake in the pyplot introductory tutorial

### ISSUE THREAD

**Issue by leonprou** [matplotlib/matplotlib#10037]
### Bug report

In the [introductory tutorial]( https://matplotlib.org/2.0.2/users/pyplot_tutorial.html#working-with-multiple-figures-and-axes), you can read " The subplot() command specifies numrows, numcols, **fignum** where **fignum** ranges from 1 to numrows*numcols".
I'm interpreting fignum as figure number, which is a wrong cause the third argument is **plot_number**, it's easily seen in the docs of [subplot](https://matplotlib.org/2.0.2/api/pyplot_api.html#matplotlib.pyplot.subplot)

To fix, just need replace [here](https://github.com/matplotlib/matplotlib/blob/master/tutorials/introductory/pyplot.py) fignum to plot_number.

**Comment by leonprou** [comment]
@dsblank thanks for the tags. It's really small, so I can make a PR if you're interested.

**Comment by tacaswell** [comment]
@leonprou Please do!  We :heart: documentation PRs!

**Comment by surana-mudit** [comment]
Hey @leonprou , I am a new contributor to this repo, I would like to make a PR for this issue as it is my first issue

**Comment by leonprou** [comment]
@surana-mudit ok, go for it 👍

**Comment by dstansby** [comment]
Fixed by #10055
