### ISSUE TITLE
mouse event

### ISSUE THREAD

**Issue by amryounis** [matplotlib/matplotlib#10038]
### Bug report

**Bug summary**
trying to draw new data point in accordance to mouse event. thing is graph does not get updated with the new point till I click on an icon on the toolbar. otherwise, I have to activate the zoom or pan icons

**Code for reproduction**

```python
# Paste your code here
#
# code is based on book: mastering matplotlib
```
import random
import sys
import time
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image

class Callbacks:
    def __init__(self):
        (figure, axes) = plt.subplots()
        axes.set_aspect(1)
        axes.set_ylim(bottom=-1, top=1)
        axes.set_xlim(left=-1, right=1)
        axes.grid(True)
        figure.canvas.mpl_connect('button_press_event', self.press)
        figure.canvas.mpl_connect('button_release_event', self.release)
        figure.canvas.mpl_connect('motion_notify_event', self.moved)

    def start(self):
        plt.show()

    def moved(self, event):
        pass #print('x = {}, y = {}'.format(event.xdata, event.ydata))

    def press(self, event):
        print('Press: x = {}, y = {}'.format(event.xdata, event.ydata))
        self.start_time = time.time()

    def release(self, event):
        print('Release: x = {}, y = {}'.format(event.xdata, event.ydata))
        self.end_time = time.time()
        self.draw_click(event)

    def draw_click(self, event):
        size = 4 * (self.end_time - self.start_time) ** 2
        c1 = plt.Circle([event.xdata, event.ydata], 0.002,)
        c2 = plt.Circle([event.xdata, event.ydata], 0.02 * size, alpha=0.2)
        c3 = plt.plot(event.xdata, event.ydata, 'ro')
        event.canvas.figure.gca().add_artist(c1)
        event.canvas.figure.gca().add_artist(c2)
        event.canvas.figure.gca().draw_artist(c2)
        event.canvas.figure.show()

cbs = Callbacks()
cbs.start()

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
I think you want to be using `event.canvas.draw_idle()` (or `event.canvas.draw()`) rather than `event.canvas.figure.show()`.

**Comment by amryounis** [comment]
Hi tacaswell, it is working now with your proposed functions... many thanks indeed

**Comment by jklymak** [comment]
@amryounis.  Glad it works. Is there a documentation issue here?

**Comment by amryounis** [comment]
hi, i am not sure but documentation, in general, is a major weakness here.

**Comment by jklymak** [comment]
Was there an example you followed that was incorrect?

**Comment by tacaswell** [comment]
@amryounis  does the text at https://github.com/matplotlib/matplotlib/pull/4779 help at all?

**Comment by amryounis** [comment]
@tacaswell I have not read #4779 till you mentioned it but no, it did not help

**Comment by timhoffm** [comment]
Closing as non-actionable.
