### ISSUE TITLE
Opening a matplotlib window from Python 3.6.3 does not work with qt5agg backend on Windows 7

### ISSUE THREAD

**Issue by Rolf-Hempel** [matplotlib/matplotlib#10047]
### Bug report

**I'm trying to port [my application code](https://github.com/Rolf-Hempel/MoonPanoramaMaker) from Python 2.7/QT4/Matplotlib 1.4.2 to Python 3.6.3/QT5/Matplotlib 2.1.1. The Python code creates a matplotlib window with a complex figure. In the new environment only an empty window appears, and the CPU load rises sharply.**

**I could boil down the problem to this very simple example code:**

```python
import matplotlib.pyplot as plt

class TileVisualization:

    def __init__(self):
        # Switch on interactive mode to make the window changeable.
        plt.ion()
        self.fig = plt.figure(figsize=(8.5, 8.5))
        self.ax = self.fig.add_subplot(111, facecolor='black')
        plt.tight_layout()
        self.fig.canvas.draw()


    def close_tile_visualization(self):
        plt.close()


if __name__ == "__main__":
    import time

    tv = TileVisualization()

    time.sleep(20)

    tv.close_tile_visualization()
```

**Only the frame of the matplotlib window appears, the figure is blank.**

![screenshot_error](https://user-images.githubusercontent.com/19596791/34174816-907a99ec-e4fa-11e7-95d4-bdd156d8d15c.PNG)

**If I run the same code with the PyCharm debugger and stop at a breakpoint before the line**
```
self.fig.canvas.draw()
```
**the matplotlib figure shows correctly (see below), but the processor load is very high and the matplotlib window can only be moved jerkily with the mouse.**

![screenshot_debugger](https://user-images.githubusercontent.com/19596791/34174986-21c7c9ce-e4fb-11e7-8fbe-b853553ac277.PNG)

**The code works properly with Matplotlib 1.4.2 and python 2.7. I tried the code on two different computers. The result was the same.**

**Matplotlib version**

  * Operating system: Windows 7 professional 64 bit
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.6.3
  * Jupyter version (if applicable): - 
  * Other libraries: None

**I installed the software using Miniconda (Python 3 version from the conda.io website), created an environment and only added: "conda install matplotlib pyqt5".**

**Comment by jklymak** [comment]
Can you remove the `plt.tight_layout()` and still get the same problem?   Not sure, but you may need to call fig.tight_layout, but really, I wouldn’t call tight_layout at all w. Interactive code.  If you want to get the spacing, do it outside the interactive code, and then hardcode the subplot parameters in the interactive plot.

**Comment by Rolf-Hempel** [comment]
No, it has nothing to do with `plt.tight_layout()`. If I comment out the statement the behaviour does not change. Only the window is not cropped to the size of the subplot.

**Comment by jklymak** [comment]
I’m not very good w interactive plots, and I don’t have a computer in front of me.  But don’t you need a `show()` in here somewhere?

**Comment by WeatherGod** [comment]
not with plt.ion()

**Comment by tacaswell** [comment]
See text at https://github.com/matplotlib/matplotlib/pull/4779 

Do you expect the figure to be interactive while it is open?  The issue is likely that we have made the GUI frame integration lazier and there may have been some changes with how PyQT handle's its event loop integration. 

Try replacing `time.sleep(20)` with `plt.pause(20)`.

**Comment by efiring** [comment]
Take out the plt.ion(), take out the draw(), and change time.sleep to plt.pause.  Then I think it will work.  It does on OSX, anyway.

The problem, at least in part, is that something has to run the Qt5 mainloop.  Normally we delegate that to ipython, or do it explicitly as in an embedding example.  As a quick and dirty way, though, we have the plt.pause() function.  In your original version, I think the plot was not being drawn because  a draw_idle was being triggered, and then sleep was blocking things before any drawing could occur. One thing I don't understand is the CPU usage in that case, which I can reproduce on OSX.  That does seem to be a bug in matplotlib; although the mainloop was not running, the code was still stuck in some internal loop.  This is probably related to an attempt to make ion work even outside of ipython.

**Comment by tacaswell** [comment]
I can reproduce the high-cpu only with `plt.pause(20)` and `plt.ion()`.

Something is not latching right and each time it draws it is marking the figure as stale again which is in turn triggering another draw.

**Comment by Rolf-Hempel** [comment]
Thanks for your quick replies!

I need to keep the plt.ion(). In my full code I have to interact with the plt window. Also, replacing time.sleep with plt.pause does not help me much. Please remember that this is just a small mockup code. In the real code the sleep is replaced with all kinds of other activities, including GUI actions in other windows using QT5. All that worked perfectly with Python 2.7, QT4 and Matplotlib 1.4.2. CPU usage was very low all the time.

By the way: When I replace the sleep with plt.pause, the high CPU load stays the same, as well as the jerky window shifting. So, the only improvement is that the figure content is visible without running the code in debugging mode.

**Comment by tacaswell** [comment]
You do not need to have `plt.ion()` to have the figure be responsive.  If you are doing other things with Qt then you have the Qt event loop running.  All you need to do is call `canvas.draw_idle()` when ever you want the figure to update.  The event loop will take care of scheduling the re-draw.

Alternatively you could put a function on a timer that checks if any figures are stale and if so calls `draw_idle` for you.

We need to track down that latching bug, but either of those approaches will work now.

**Comment by Rolf-Hempel** [comment]
Thank you very much for your quick help!
This evening I will try out what you suggested and let you know how it works.

**Comment by Rolf-Hempel** [comment]
If I take the `plt.ion()` out, the figure does not show up any more. If I then insert a `plt.show()`, at the end of `__init__`, the plot becomes visible, but the program blocks until I close the matplotlib window. Therefore, it is not so simple to have both Qt gui and matplotlib activities going on in parallel. I guess this is why I had used the `plt.ion()` in my original code in the first place.

As a remedy I could start matplotlib in a separate thread. But that's too much for tonight. I still hope you will find the bug, so my original code would work again as with Matplotlib 1.4.2.

**Comment by tacaswell** [comment]
Under the hood the Matplotlib figure _is_ (in the sense of `isinstance`) Qt objects.  The `fig.canvas` is a QWidget and `fig.canvas.manager` has QMainWindow that the canvas is embedded in.  Do `fig.canvas.manager.show()` like you would any other part of your Qt GUI.

If you are already building significant Qt GUIs, have a look at https://matplotlib.org/devdocs/gallery/user_interfaces/embedding_in_qt_sgskip.html#sphx-glr-gallery-user-interfaces-embedding-in-qt-sgskip-py which gives you the flexibility to embed plots however you want.

**Comment by Rolf-Hempel** [comment]
Thank you very much for your helpful suggestions. I successfully integrated my complete matplotlib window in a Qt5-based testprogram. As long as I don't use `time.sleep()` everything works fine. I do not need `plt.ion()` any more. I will now start porting the full application to Qt5 and Python 3 and see what happens.

**Comment by jklymak** [comment]
@Rolf-Hempel  could you share the working example?

**Comment by Rolf-Hempel** [comment]
Of course I'm happy to share the working test program. But I'm afraid it's not as self-explaining as the short snippet I listed above. So, here's a short explanation:
- The example consists of four python files: `tile_visualization.py`, `tile_constructor.py`, `qtgui.py` and `miscellaneous.py`. The program is started by runnig the `__main__` routine in the first file.

- The "real" application ([MoonPanoramaMaker](https://github.com/Rolf-Hempel/MoonPanoramaMaker)) is about creating a panorama phtography of the moon. The matplotlib window shows the distribution of tiles for the panorama. In the test, it is created from a small test Qt5 gui by pressing the button "Open Matplotlib Window".

- The class `TileVisualization` in module `tile_visualization` provides a number of methods to manipulate the appearance of the tiles, and to select tiles for other functions of the MoonPanoramaMaker program. When the matplotlib window opens, a number of functions are tested automatically.

- Additionally, you can test the selection of a number of contiguous tiles: With the left mouse button you draw a rectangle which contains a number of tiles, and release the mouse button. Then you press the button `Select Tiles` in the Qt5 gui. The numbers of the tiles which are completely contained in the selection rectangle are printed on standard output.

All this now works on my computer, and the CPU load is very low all the time. I didn't port the complete Application to Python 3 and Qt5 yet, so the final test is still open.

The following zip folder contains the four Python files required to run the test.

[Qt5_Matplotlib_Example.zip](https://github.com/matplotlib/matplotlib/files/1581956/Qt5_Matplotlib_Example.zip)

**Comment by jklymak** [comment]
OK, sorry!  I meant the working version of the simple script...

**Comment by Rolf-Hempel** [comment]
Sorry, I stopped working with the simple script and instead implemented the suggested changes in the more realistic test program. The logic of the initial QT window and the creation of the matplotlib window from there (end of file "tile_visualization.py"), however, would be very similar for the simple script also.

**Comment by QuLogic** [comment]
I believe this was completed [here](https://github.com/matplotlib/matplotlib/issues/10047#issuecomment-353389113) and didn't really need to be re-opened.
