### ISSUE TITLE
Only one legend entry is rendered for items with the same label and color

### ISSUE THREAD

**Issue by ArcturusB** [matplotlib/matplotlib#10056]
### Only one legend entry is rendered for items with the same label and color

In Matplotlib 2.1.1, items that have the same label and color result in a single legend entry. This happens even if some other properties of the items are different (eg. marker or linewidth).

This behaviour is surprising because the style of the first item is used for the handle, regardless of the style of the following items. 

I would expect either the behaviour from Matplotlib 2.1.0, or the labels being merged only if the label and **all** style properties are equal.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
plt.plot([0, 1], [0, 1], label='foo', color='k', marker='o', linewidth=1)
plt.plot([0, 1], [1, 2], label='foo', color='k', marker='.', linewidth=2)
plt.plot([0, 1], [2, 3], label='bar', color='k', marker='s', linewidth=3)
plt.legend()
plt.savefig('foobar.png')
```

**Actual outcome (Matplotlib 2.1.1)**

![foobar_211](https://user-images.githubusercontent.com/9514702/34212958-326c036e-e59e-11e7-8cb6-2b55e7afd6d1.png)

**Expected outcome (Matplotlib 2.1.0)**

![foobar_210](https://user-images.githubusercontent.com/9514702/34213037-6315912e-e59e-11e7-8132-b4c8095e3227.png)

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 2.1.1
  * Matplotlib backend: agg
  * Python version: 3.6.3
  * Matplotlib installed from Arch Linux repository `community/python-matplotlib`.

**Comment by tacaswell** [comment]
attn @jklymak Looks like more issues with the de-duplication logic.

**Comment by jklymak** [comment]
OK, I see what has happened finally.  Sorry to be so slow.   

The de-duplication logic was *only* in `Figure.legend` *not* in `Axes.legend` (or `pyplot.legend()`).  

The old `Figure.legend` de-duplication had this bug and the bug reported in #10030.   

What I did in #9324 was make the parsing logic the same.  So the de-duplciation logic ended up in `Axes.legend` and that means people who weren't triggering the bug now *are* triggering the bug.

I propose we get rid of the de-duplciation logic for both versions of legend.  That is a breaking API change for `Figure.legend()` but I think it is a pretty clear edge case.  I think its better to do that than to keep the de-duplication logic for `Axes.legend()` which was also a breaking change that we (I) didn't note at the time.

**Comment by jklymak** [comment]
Closed #10064.  Thanks for the bug report!

**Comment by HappyMeeple** [comment]
I experience the same bug, or so I think with Matplotlib 3.4.3.

However, it should be fixed, right?

**Comment by jklymak** [comment]
@HappyMeeple the original report example works fine for me, so if you have a similar error, please open a new issue with a self-contained minimal example.   Thanks!
