### ISSUE TITLE
Deprecate svgfont support, possibly replacing with woff?

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10063]
### Bug report

**Bug summary**

The svg backend currently exposes the svg.fonttype = svgfont option, which embeds fonts into the svg file using the "svg fonts" feature which appears to be essentially unsupported anywhere and removed from the svg standard (https://caniuse.com/#feat=svg-fonts https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts).  The code path was also not working at all on Py3 (#10046).

I would thus suggest deprecating support for svg fonts.

A possibility to still allow embedding the font file into the svg file would be to use the apparently more popular WOFF(2) format, see https://developer.mozilla.org/en-US/docs/Web/Guide/WOFF https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face for the format, http://www.sameratiani.com/2011/10/16/embed-inline-webfonts-in-css.html for embedding the font into the svg file itself, and https://caniuse.com/#search=woff for support.  A quick test suggests that this is supported but chrome/firefox, but not by inkscape, but at least inkscape emits a warning and replaces the embedded font by another one, whereas it appears to freeze with the current implementation of svg fonts.

**Comment by tacaswell** [comment]
> removed from the svg standard

That is indeed a compelling argument.

**Comment by ksunden** [comment]
Closed by #10086, just never was properly linked, it was fully removed later (didn't track down exactly when)

**Comment by QuLogic** [comment]
It was fully removed in #12245.

**Comment by anntzer** [comment]
I think we can keep this open to track the possibility of implementing woff(2) support?  Feel free to reclose if you disagree.

**Comment by timhoffm** [comment]
Then, change the title or rather make a new ticket so that one can see the state immediately?

**Comment by anntzer** [comment]
Sure, see #25791.
