### ISSUE TITLE
Dragged legend moves upon resizing figure window

### ISSUE THREAD

**Issue by inxp** [matplotlib/matplotlib#10060]
Dragged legend moves upon resizing figure window from matplotlib version 2.1.0.

**Code for reproduction**

```
import matplotlib.pyplot as plt

X = range(100)
Y = [value ** 2 for value in X]

plt.plot(X, Y,label='Y')
leg=plt.legend()
leg.draggable(True)
plt.grid(True)
plt.show()
```
**Matplotlib 2.1.1/2.1.0 output**

![2 1 0](https://user-images.githubusercontent.com/6796654/34217804-7c5bba3a-e5d2-11e7-91d2-6dcbd8addb25.jpg)

**Matplotlib 2.0.2 output**

![2 0 2](https://user-images.githubusercontent.com/6796654/34217841-972f7da6-e5d2-11e7-8c13-753657f445f5.jpg)

In 2.1.0 legend tries to retain it's location with respect to monitor (if we resize in one axis). 
Is this expected? How do I bring back the old behavior?

  * Operating system: Windows 10 64 bit
  * Matplotlib version: 2.1.0/2.0.2
  * Matplotlib backend: NA
  * Python version: 2.7.10
  * Jupyter version (if applicable): NA
  * Other libraries: NA
  * Installed using whl files

**Comment by Raab70** [comment]
What if you try: `leg.draggable(True, update='bbox')`

**Comment by tacaswell** [comment]
Interesting.  I can not think of what changed between 2.0 and 2.1 to have caused that (we changed the default location to 'best' in 2.0 though).

**Comment by Raab70** [comment]
I was having a hard time reproducing, the dragging was not working well for me. I would drag and it would not show the change until I clicked a few times and then the movement on window resize didn't seem to follow either scheme above. (master/OSX/agg backend)

I too looked and didn't see any changes between 2.0 and 2.1 that looked like they should affect this.

**Comment by inxp** [comment]
Sorry for late reply...

> What if you try: `leg.draggable(True,update='bbox')`

Using `update='bbox' `with matplotlib ver. 2.0.2 makes the behavior same as 2.1.0 (legend moves upon resizing figure window). Using` update='bbox'` or `'loc'` in matplotlib ver. 2.1.0 doesn't have any impact on the behavior.

> we changed the default location to 'best' in 2.0 though.

The behavior exists even if we change legend location from best to let's say 'upper right'

> I was having a hard time reproducing, the dragging was not working well for me. I would drag and it would not show the change until I clicked a few times and then the movement on window resize didn't seem to follow either scheme above. (master/OSX/agg backend)

Dragging works fine for me. I've used TkAgg and Qt4Agg backends.

**Comment by u55** [comment]
I just discovered this problem when dragging a legend and then manually saving the figure if `'savefig.dpi'` is not equal to `'figure.dpi'`.

**Comment by afvincent** [comment]
@u55 Your remark may be related to #10458

**Comment by jklymak** [comment]
So this is a duplicate and closed?  Feel free to re-open if I'm mistaken...

**Comment by inxp** [comment]
Fixed for me also.
Thanks
