### ISSUE TITLE
memory leak with histograms 

### ISSUE THREAD

**Issue by amymcgovern** [matplotlib/matplotlib#10123]
### Bug report

When repeatedly calling hist on an axis, memory eventually runs out.  The figures are being closed in between each call but there is a memory leak.  When it is changed to a fix number of bins, it works fine.

This causes the memory leak.
```
  ax.hist(hist_data, bins='auto', histtype='bar', stacked=True, color=my_colors)
```

This fixes the bug:
```
  ax.hist(hist_data, bins=100, histtype='bar', stacked=True, color=my_colors)
```

**Actual outcome**

```
# If applicable, paste the console output here

python(41037,0x7fffa6bc4340) malloc: *** mach_vm_map(size=183134513703677952) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/amy/repos/myrorss/storm_classification/visualize_data.py", line 377, in <module>
    plot_histograms_of_data(training_input, training_output, AZSHEAR_COLUMNS, "graphs/shear")
  File "/Users/amy/repos/myrorss/storm_classification/visualize_data.py", line 289, in plot_histograms_of_data
    color=storm_colors, label=set(output_data))
  File "/Users/amy/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/Users/amy/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6161, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/Users/amy/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 564, in histogram
    n = np.zeros(bins, ntype)
MemoryError
```

**Expected outcome**

When it works fine, it happily plots a lot of figures, one by one.

**Matplotlib version**

  * Operating system: repeated on both Linux and Mac OS X
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.13
  * Jupyter version (if applicable):
  * Other libraries: 

Anaconda default channel

**Comment by jklymak** [comment]
- can you supply self-contained code to trigger the issue?
  - not clear this isn't a numpy issue: the error is coming from numpy.  What version of numpy are you using, and does calling `numpy.histogram` repeatedly cause the same memory leak?

**Comment by amymcgovern** [comment]
Yes, I can supply the code.  I will note that I learned that only my data will trigger it, not randomly generated data.  I suspect it is an interaction with Nans in there.  The code and data files needed to run it are attached.

[bug_report.zip](https://github.com/matplotlib/matplotlib/files/1592314/bug_report.zip)

**Comment by fredrik-1** [comment]
I don't think that numpy histogram and thus matplotlib hist is supposed to work with nans or masked arrays. See for example https://github.com/matplotlib/matplotlib/issues/8105/

**Comment by amymcgovern** [comment]
Plausibly but having a memory error is definitely a bug...

**Comment by jklymak** [comment]
But I’m not convinced it is a Matplotlib bug. 

It would still be preferable if you can reproduce in a self contained way.

**Comment by fredrik-1** [comment]
> Plausibly but having a memory error is definitely a bug...

I kind of agree with that but you sometimes get "strange" error messages when using plt.hist or np.histograms with nans because the code is not trying to handle nans at all (at least not np.histogram and plt.hist not enough if I remember correctly). I agree that a memory error is worse than some other "incorrect" errors but the problem is probably that you tried to use the function in the wrong way.  

I would suggest that nans and masked arrays should be handled in the plt.hist function in some way because it often makes sense to have nans in data that should be plotted as a histogram (or at least make an understandable exception).  I see now that it is written in the documentation that hist doesn't work for masked arrays. 

It can of course be handled by the user by using x[~np.isnan(x)] instead of x in plt.hist but it might not be the first thing you think about when you get a strange range error. 

I cant get hist to work with nans unless I use a range and that throws a warning but seems to work as expected. Your code in the first post doesn't work for me with data with nans.

**Comment by amymcgovern** [comment]
1) There are no nans in this data.  I wish you wouldn't jump to that conclusion so easily.  I have already cleaned the nans out using pandas.

2) I did provide self contained code.  It reliably crashes.

3) I have created a nice self contained set of code that will reliably trigger the memory error.

```
import numpy as np
import math
import matplotlib as mpl
import cPickle
import pandas as pd
mpl.use('agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.gridspec import GridSpec



def plot_histograms_of_data(input_data, output_data, variable_names, filepath, variable_index=-1):
    """Make Histograms of the data for each of the variables in variables_names

    :param input_data: input_data
    :param output_data: labels of the input_data
    :param variable_names: names of the columns of input_data
    :param filepath: string for location of output files. "[variable_name].png" will be appended for each variable
    :param variable_index: optional index of a single variable to plot. If not specified, all variables will be plotted
    (which will take a long time)
    """

    labels_to_colors = {'unknown': (0, 0, 0), 'disorganized': 'green', 'marginal supercell': 'blue',
                        'qlcs': 'purple', 'linear hybrid': 'orange', 'supercell': 'red', 'outlier': 'black'}

    storm_colors = [labels_to_colors[label] for label in set(output_data)]

    for v, var in enumerate(variable_names):

        if variable_index != -1 and v != variable_index:
            continue  # Only plot the variables specified (or all if variable_index == -1)

        print "Binning %s" % var
        # Separate the data (for this variable) by storm type into columns corresponding to labels
        hist_data = [input_data[output_data == label, v] for label in set(output_data)]

        num_figs = len(set(output_data)) + 1  # Plus 1 for combined plot
        num_figs_per_side = int(math.ceil(math.sqrt(num_figs)))
        fig = plt.figure(figsize=(4 * num_figs_per_side, 3 * num_figs_per_side))
        # Make a log plot for each individual storm type
        for l, label in enumerate(set(output_data)):
            ax = fig.add_subplot(num_figs_per_side, num_figs_per_side, l+1)  # Count from 1, not 0
            plt.cla()

            ax.hist(hist_data[l], bins=100, histtype='bar', log=True, color=storm_colors[l], label=label)
            plt.title("Log plot for %s" % label)
            ax.set_xlabel(var)
            ax.set_ylabel("Log( Count )")

        # Plot everything combined (not in a log plot)
        ax = fig.add_subplot(num_figs_per_side, num_figs_per_side, num_figs)
        ax.hist(hist_data, bins='auto', histtype='bar', stacked=True,
                color=storm_colors, label=set(output_data))
        plt.legend()
        plt.title("Combined plot")
        ax.set_xlabel(var)
        ax.set_ylabel("Count")

        plt.suptitle("Distribution for %s" % var, y=1.03)

        plt.tight_layout()
        savefile = filepath + "%s.png" % var
        print "Saving file to %s" % savefile
        plt.savefig(savefile, dpi=300, bbox_inches="tight")
        plt.close()


if __name__ == "__main__":

    training_input = np.random.rand(6545, 2)
    training_input[1000, 0] = 1000000000000000
    training_input[2000, 0] = 1000000000000000
    training_input[3000, 0] = 1000000000000000
    training_input[4000, 0] = 1000000000000000

    labels = ('disorganized', 'marginal supercell', 'qlcs', 'linear hybrid', 'supercell', )
    training_output = np.random.choice(labels, 6545, p=[0.340, 0.015, 0.229, 0.006, 0.41])
    training_output = np.sort(training_output)

    COLUMNS = ['a', 'b']

    plot_histograms_of_data(training_input, training_output, COLUMNS, "")
```

**Comment by jklymak** [comment]
Thanks for the self-contained example, though its not minimal:  Here is one you can post on the numpy page (or not put a way-out-of-range number in your array.  This isn't a matplotlib bug. 

```python
import numpy as np

training_input = np.random.rand(6545)
training_input[1000] = 1000000000000000

m, bins = np.histogram(training_input, 'auto')
```

**Comment by amymcgovern** [comment]
Thanks

**Comment by fredrik-1** [comment]
Sorry, but I thought nans were involved when you wrote "I suspect it is an interaction with Nans in there." 

I didn't want to download a large zip file.

**Comment by amymcgovern** [comment]
Fair :-P

It's already been confirmed over on the numpy page.

**Comment by tacaswell** [comment]
@amymcgovern Thanks for sticking with this issue. 

xref to numpy bug report : https://github.com/numpy/numpy/issues/10297
