### ISSUE TITLE
Review documentation of Axes plotting methods

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10148]
As a follow up of #7205, some docstrings of the basic Axes plotting methods could need a bit care. In particular:

- Conversion to numpydoc format.
- Improvements on the descriptions.

I intend to go through the methods and update their docs. This is a summary issue to keep track of my progress: 

### Basic

- [x] `Axes.plot`
- [x] `Axes.errorbar`
- [x] `Axes.scatter`
- [x] `Axes.plot_date`
- [x] `Axes.step`
- [x] `Axes.loglog`
- [x] `Axes.semilogx`
- [x] `Axes.semilogy`
- [x] `Axes.fill_between`
- [x] `Axes.fill_betweenx`
- [x] `Axes.bar`
- [x] `Axes.barh`
- [x] `Axes.stem`
- [x] `Axes.eventplot`
- [x] `Axes.pie`
- [x] `Axes.stackplot`
- [x] `Axes.broken_barh`
- [x] `Axes.vlines`
- [x] `Axes.hlines`
- [x] `Axes.fill`

### Spans

- [x] `Axes.axhline`
- [x] `Axes.axhspan`
- [x] `Axes.axvline`
- [x] `Axes.axvspan`

### Spectral

- [x] `Axes.acorr`
- [x] `Axes.angle_spectrum`
- [x] `Axes.cohere`
- [x] `Axes.csd`
- [x] `Axes.magnitude_spectrum`
- [x] `Axes.phase_spectrum`
- [x] `Axes.psd`
- [x] `Axes.specgram`
- [x] `Axes.xcorr`

### Statistics

- [x] `Axes.boxplot`
- [x] `Axes.violinplot`
- [x] `Axes.violin`
- [x] `Axes.bxp`

### Binned 

- [x] `Axes.hexbin`
- [x] `Axes.hist`
- [x] `Axes.hist2d`

### Contours

- [x] `Axes.clabel`
- [x] `Axes.contour`
- [x] `Axes.contourf`

### Array

- [x] `Axes.imshow`
- [x] `Axes.matshow`
- [x] `Axes.pcolor`
- [x] `Axes.pcolorfast`
- [x] `Axes.pcolormesh`
- [x] `Axes.spy`

### Unstructured triangles

- [x] `Axes.tripcolor`
- [x] `Axes.triplot`
- [x] `Axes.tricontour`
- [x] `Axes.tricontourf`

### Text and Annotations

- [x] `Axes.annotate`
- [x] `Axes.text`
- [x] `Axes.table`
- [x] `Axes.arrow`

### Fields

- [x] `Axes.barbs`
- [x] `Axes.quiver`
- [x] `Axes.quiverkey`
- [x] `Axes.streamplot`

## Axes limits and direction

- [x] `Axes.invert_xaxis`
- [x] `Axes.xaxis_inverted`
- [x] `Axes.invert_yaxis`
- [x] `Axes.yaxis_inverted`
- [x] `Axes.set_xlim`
- [x] `Axes.get_xlim`
- [x] `Axes.set_ylim`
- [x] `Axes.get_ylim`
- [x] `Axes.update_datalim`
- [x] `Axes.update_datalim_bounds`
- [x] `Axes.set_xbound`
- [x] `Axes.get_xbound`
- [x] `Axes.set_ybound`
- [x] `Axes.get_ybound`

## Axes scales

- [x] `Axes.get_xscale`
- [x] `Axes.set_xscale`
- [x] `Axes.get_yscale`
- [x] `Axes.set_yscale`

<s>Note: I currently update the docstrings in my private branch https://github.com/timhoffm/matplotlib/tree/axes-plotting-docstrings and will provide a pull request once I'm done. I think this is better than opening a separate pull request for every change. Please let me know, in case you'd rather prefer many smaller PRs.</s>

The fixes will be supplied in a series of PRs referencing this issue.

**Comment by jklymak** [comment]
I think the only disadvantage to a big PR is you may have to privately rebase a bunch, and other folks might make conflicting changes if it takes you a while.

**Comment by anntzer** [comment]
I would probably make PR with small batches of related methods, but one-at-a-time is fine too.
A giant PR is also fine as long as you don't mind an unbounded (in time...) review process.

**Comment by timhoffm** [comment]
Thanks for the answers. I'll switch to smaller batches then.

**Comment by ImportanceOfBeingErnest** [comment]
I think it would be really great if the documentation of a function could link to some (or all?) examples from the gallery that use this function.  
I don't know at which point this would be specified, if it's in the docstring or some sphinx config file?
Also linking from the examples to the docs is only present in some cases.

**Comment by jklymak** [comment]
There is some of that on a few of the pages: https://matplotlib.org/api/_as_gen/matplotlib.patches.Wedge.html#matplotlib.patches.Wedge

I have no idea from looking at the source how that happens, however.

**Comment by jklymak** [comment]
BTW, I like the doc interpolation, but not when someone has named the doscstring something unsearchable like `Patch`.  Does anyone know where the `Patch` docstring lives that is interpolated via `%(Patch)s`?

**Comment by jklymak** [comment]
... or is it just auto-generating from the `set_` and `get_`?

**Comment by ImportanceOfBeingErnest** [comment]
Yeah, that's exactly what I mean.  
In the [page source](https://matplotlib.org/_sources/api/_as_gen/matplotlib.patches.Wedge.rst.txt) it says

     .. include:: matplotlib.patches.Wedge.examples

but the question is indeed who is reponsible for putting that line there?

The `%(Patch)s` seems to come from https://github.com/matplotlib/matplotlib/blob/d54e2e3628824704d0182e4793a92f0bea2e9000/lib/matplotlib/patches.py#L551-L558

Which then points to https://github.com/matplotlib/matplotlib/blob/d54e2e3628824704d0182e4793a92f0bea2e9000/lib/matplotlib/artist.py#L1466
 and that seems to indeed give the setters from the classes. But I don't think it will help with creating the examples, or will it?

**Comment by jklymak** [comment]
Opening new issue

**Comment by timhoffm** [comment]
I'm explicitly excluding work on gallery links from this effort. It's already big enough as it is now. The gallery links have their own ticket #10974.

**Comment by timhoffm** [comment]
I hereby declare this work complete. 🎉
