### ISSUE TITLE
Low resolution (dpi problem) with Qt5 backend on new iMac Pro Retina

### ISSUE THREAD

**Issue by mweber-ovt** [matplotlib/matplotlib#10160]
### Bug report

**Bug summary**

When embedding a figure in Qt5 on a new iMac Pro Retina 5k, figures are plotted in low resolution if the figure is created using pyplot.  This does not occur on a regular iMac, or on a MacBook Pro with Retina display.

**Code for reproduction**

```python
import sys

from numpy import arange, sin, pi

import matplotlib
matplotlib.use("Qt5Agg")

from matplotlib.backends.backend_qt5agg import (
	FigureCanvasQTAgg as FigureCanvas)
from matplotlib.figure import Figure
import matplotlib.pyplot as plt

from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow, QVBoxLayout

class App(QMainWindow):
	def __init__(self):
		super(QWidget, self).__init__()

		# set up the window
		self.setWindowTitle('Qt Window')

		# create the central widget
		self.cw = QWidget()

		# create first figure and a canvas
		self.fig1 = Figure(dpi = 100, figsize=(3,3))
		self.ax1 = self.fig1.add_subplot(111)
		self.canvas1 = FigureCanvas(self.fig1)
		self.canvas1.setParent(self.cw)
		print('Figure 1 dpi:', self.fig1.dpi)

		# create second figure using pyplot
		# when inspecting dpi, it can already be seen something is different
		self.fig2 = plt.figure(dpi = 100, figsize=(3,3))
		self.ax2 = self.fig2.add_subplot(111)
		self.canvas2 = FigureCanvas(self.fig2)
		self.canvas2.setParent(self.cw)
		print('Figure 2 dpi:', self.fig2.dpi)

		# create a layout and add the two canvases
		self.layout = QVBoxLayout()
		self.layout.addWidget(self.canvas1)
		self.layout.addWidget(self.canvas2)

		# assign the layout to the central widget
		self.cw.setLayout(self.layout)
		# set the central widget
		self.setCentralWidget(self.cw)

		# plot some data
		t = arange(0.0, 3.0, 0.01)
		s = sin(2 * pi * t)
		self.ax1.plot(t, s)
		self.ax2.plot(t, s)

		# show the window
		self.show()

app = QApplication(sys.argv)
main_window = App()
sys.exit(app.exec_())
```

**Actual outcome**

<img width="708" alt="screenshot 2018-01-04 04 56 51" src="https://user-images.githubusercontent.com/8430369/34564516-c92fe176-f10b-11e7-9516-b14b11e779fd.png">

```
# If applicable, paste the console output here
Figure 1 dpi: 200
Figure 2 dpi: 400
```

**Expected outcome**

Both figures should be the same size and resolution.  And they are on other systems, except the new iMac Pro.  This would allow me to continue using the convenience of pyplot.

**Matplotlib version**

  * Operating system:  macOS High Sierra 10.13.2 
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):  Qt5Agg
  * Python version: 3.6.4 (Anaconda)
  * Jupyter version (if applicable):
  * Other libraries: pyqt5

Anaconda 5.0.1 & update Matplotlib

**Comment by jklymak** [comment]
This has the same error on my late 2013 MacBook Pro.  I don't think this is a hardware-related problem.  Too bad; I was going to offer to trade.  

I'm not clear on how to embed figures in QT5, but it seems the hidpi got applied twice somehow. Setting the second figure to 50 dpi works fine...

**Comment by raphaelproux** [comment]
Strangely I had the same problem on a Macbook Pro 2016 with the same configuration and Matplotlib 2.0.2. Updating to 2.1.1 solved the issue so it may be a lead to find where this problem comes from?

**Comment by dstansby** [comment]
Can anyone test on Matplotlib 2.2.3 or 3.0.0 to see if this is still a problem? I think quite a bit of work went into high dpi screens on MacOS recently.

**Comment by mweber-ovt** [comment]
I am on the Anaconda distribution.  Apparently, Anaconda cannot update Matplotlib 2.2.2 although Anaconda Navigator indicates an upgrade is available.  So, unfortunately, I haven’t been able to confirm the issue is resolved.

On Sep 25, 2018, at 12:44, David Stansby <notifications@github.com<mailto:notifications@github.com>> wrote:


Can anyone test on Matplotlib 2.2.3 or 3.0.0 to see if this is still a problem? I think quite a bit of work went into high dpi screens on MacOS recently.

**Comment by tacaswell** [comment]
I am concerned that the underlying issue is that when `plt` takes care of creating the widgets it creates a canvas, which does some initial setup (which includes the slightly brittle details of how to handle the implicit DPI doubling (which is the subtle internal details of how we implement hi-DPI support to play nice with the way the GUI frameworks support it).  You are then re-assigining the canvas to a second canvas which I suspect is re-triggering the dpi doubling latch.

Using pyplot with full embedding is not encouraged (as now there are 2 canvas that think they own that figure and are (maybe?) still alive and you are getting into the pyplot global state).  We should track down and fix the double doubling, but I strongly suggest not doing the thing that behaves badly!

**Comment by jklymak** [comment]
As @tacaswell notes above:

```python
self.fig1 = Figure(dpi = 100, figsize=(3,3))
		self.ax1 = self.fig1.add_subplot(111)
		self.canvas1 = FigureCanvas(self.fig1)
		self.canvas1.setParent(self.cw)
		print('Figure 1 dpi:', self.fig1.dpi)

		# create second figure using pyplot
		# when inspecting dpi, it can already be seen something is different
		self.fig2 = Figure(dpi = 100, figsize=(3,3))
		self.ax2 = self.fig2.add_subplot(111)
		self.canvas2 = FigureCanvas(self.fig2)
		self.canvas2.setParent(self.cw)
		print('Figure 2 dpi:', self.fig2.dpi)
```

works as expected. Sorry, I should have noticed you were doing this before.  Not sure if this really needs to stay open.

**Comment by mweber-ovt** [comment]
Using pyplot is much easier than not using it.  @tacaswell, if pyplot does indeed create a canvas, how do I get it to plot  inside a Qt widget?

**Comment by timhoffm** [comment]
See [Embedding in Qt](https://matplotlib.org/gallery/user_interfaces/embedding_in_qt_sgskip.html)

**Comment by mweber-ovt** [comment]
This works of course but the question is, what about figures created and plotted with pyplot?


On Oct 8, 2018, at 00:56, Tim Hoffmann <notifications@github.com<mailto:notifications@github.com>> wrote:


See Embedding in Qt<https://matplotlib.org/gallery/user_interfaces/embedding_in_qt_sgskip.html>

**Comment by WeatherGod** [comment]
FIgures created using pyplot are assumed to be managed by pyplot. They
cannot be embedded into another Qt widget because they are already in a Qt
window managed by pyplot. If you want more information than what is
provided at the link, please read my book, "Interactive Applications using
Matplotlib", which describes the many different ways you can work with
matplotlib figures (either by embedding Qt widgets into them, or embedding
them into Qt widgets -- chapter 5).

**Comment by tacaswell** [comment]
Moved to 3.2 as this is exercising a bug in the DPI doubling logic, but only by doing something that is usually not done (re-setting the canvas of a figure).

**Comment by dstansby** [comment]
Just tried this (on a retina MacBook Pro), and it seems to be fine for me - I get both DPIs reported as 100. @mweber-ovt is this still an issue for you?

**Comment by mweber-bg** [comment]
@dstansby Thanks…it’s no longer a problem on any of my systems!
