### ISSUE TITLE
Docstring interpolation does not work correctly for indented insertions

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10161]
### Bug report

After switching to the numpydoc format, it's a common situation that one wants to add a docstring interpolation to the a parameter entry, e.g.

~~~
@docstring.dedent_interpd
def axhline(self, y=0, xmin=0, xmax=1, **kwargs):
    """
    Add a horizontal line across the axis.

    [...]

    Other Parameters
    ----------------
    **kwargs :
        Valid kwargs are :class:`~matplotlib.lines.Line2D` properties,
        with the exception of 'transform':

        %(Line2D)s
"""
~~~

The resulting docstring is:

~~~
Other Parameters
----------------
**kwargs :
    Valid kwargs are :class:`~matplotlib.lines.Line2D` properties,
    with the exception of 'transform':

      agg_filter: a filter function, which takes a (m, n, 3) float array and a dpi value, and returns a (m, n, 3) array 
  alpha: float (0.0 transparent through 1.0 opaque) 
  animated: bool 
  [...]
~~~

Note that the first line `agg_filter` is correctly indented. However, the following inserted lines are missing the indent before the `%(Line2D)s` in the original string.

This is a general problem if the inserted string is multi-line (basically always) and the format string should be indented as in the parameter list.

Any clever ideas to get this working?

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/issues/9414 for related discussion.

(FWIW I think it is not too hard to write a custom interpolator that checks the leading indentation and does the "right" thing)

**Comment by anntzer** [comment]
As it turns out it is really easy to make interpolation respect indentation when using new-style ({}) formatting, see https://github.com/anntzer/structured-docstrings#interpolated-docstrings for an example implementation.

Don't have much time to relitigate the discussion in #9414 right now but I think a more robust interpolator may be a good first step...

**Comment by timhoffm** [comment]
As proposed in #10274, we should consider expanding to a definition list, so that the parameters are rendered as if they were regularly written, i.e.

~~~
Other Parameters
----------------
%(Line2D)s
~~~

would become

~~~
Other Parameters
----------------
agg_filter
    a filter function ...
alpha
    float (0.0 transparent to 1.0 opaque)
...
~~~

I'm not quite decided, if this is a good idea.

On the one hand, it's nice to use the standard format. On the other hand, it may be clearer, to say that this whole group of parameters is just inherited from Line2D. This may help more experienced users, who already know the Line2D properties and don't have to scan the whole list to know what is available. Also it explains the existence of some maybe unexpected params like figure. Another technical aspect: I don't think we can link the parameter names themselves. We would need to use something else to link to the respective Line2D property for further information.

In sum, I tend to leave this as a table below the parameter `**kwargs`.

**Comment by anntzer** [comment]
You may be interested in https://github.com/anntzer/matplotlib/commit/0f72aa45745ee8f96c381f7ad07c09f3f8a9966d which was a start at converting to the new interpolation system I proposed above.
