### ISSUE TITLE
Use of parentheses when referencing methods in docs

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10185]
### Current situation

Currently, we're not using any trailing parentheses when referencing methods or functions. 

[Example](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar) for ``barh()``:

~~~
orientation : {'vertical',  'horizontal'}, optional
    *This is for internal use only.* Please use `barh` for 
     horizontal bar plots.
~~~

![grafik](https://user-images.githubusercontent.com/2836374/34644773-5d5b4088-f33d-11e7-97bd-d8172ccc5b7d.png)

### Proposed change

I propose to add trailing empty parentheses in such situations:

![grafik](https://user-images.githubusercontent.com/2836374/34644708-f90d9226-f33b-11e7-935b-a723f0911ee2.png)

*Reason:* The parentheses indicate that the reference is a function and visually distinguish it from just a plain word / link. To a certain extend, this is a matter of taste. One the downside, one could argue that the parentheses clutter the text and reduce readability. In my view, the added semantics outweighs this.

### How to add parentheses
Basically, there are two options:

- Sphinx can automatically parentheses using [add_function_parentheses](http://www.sphinx-doc.org/en/1.6.5/config.html#confval-add_function_parentheses).
  **Advantage:** Will be added consistenly throughout the code base.
- Add parenthesis explicitly in the docstrings.
  **Advantage:** Will also be visible in plaintext versions of the docs (e.g. in the terminal). Can be added on a case-by-case bases.

One can also do both.

Personally, I'd do both and add the explicit ones over time when encountering them in the docs.

### Decision

So we should decide:

1. Do we want to add parentheses? *Yes*
2. If so, how do we add them? *add_function_parentheses and explicit*

What do you think?

Anyway, the result should be included in the [documentation guide](https://github.com/matplotlib/matplotlib/blob/master/doc/devel/documenting_mpl.rst)

**Comment by anntzer** [comment]
I'm -1 on the change (and on add_function_parentheses), because many things can be callable in python (e.g., would you want to add parentheses around class names too?); conversely, functions can be used in a non-call context (ie. as callbacks) (although that's arguably rare-ish for matplotlib functions).

**Comment by tacaswell** [comment]
I am not sure that the `()` help with semantics that much.  Hopefully the context around the link should provide enough clues if it is a function / method / attribute.

People who are passing callables in non-call contexts are going to understand not to call it first so I would not worry about confusing them.

I am -0 on this.  I think we should add `()` explicitly where it adds to clarity (which may be too vague and result in it being random).

Thanks for the clear write up on this @timhoffm !

**Comment by timhoffm** [comment]
## Note:
When using ``:meth:`bar` `` or ``:func:`bar` `` instead of `` `bar` `` Sphinx has always been adding parentheses to the code. See e.g. the dostring of [plot_date()](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot_date.html).

**The parentheses have been there for a long time and just started vanishing when we switched to using the default role.**

**Comment by anntzer** [comment]
So basically this is due to the any role not respecting add_function_parentheses (which is on by default) on any roles that resolve to functions.
May be worth opening an issue on Sphinx's side about that...

**Comment by timhoffm** [comment]
Yes, that is correct. (Note: We're using the `obj` role, not the `any` role. But that doesn't make a difference in this context).

Reported upstream https://github.com/sphinx-doc/sphinx/issues/4409

**Comment by anntzer** [comment]
Let's just track this on sphinx's side.
