### ISSUE TITLE
legend is not present in the generated image if I use 'tight' for bbox_inches

### ISSUE THREAD

**Issue by jdhao** [matplotlib/matplotlib#10194]
## summary of the problem
I tried to put legend outside of the axes. If I use `fig.legend()` method to produce legend and use `bbox_inches='tight'` in `savefig()` method. The legend is not present in the produced image (using the argument `bbox_extra_artists` also does not work). If I use `ax.legend()` instead, the legend is present in the saved image.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl

x = np.arange(-5, 5, 0.1)
y1 = np.sin(x)
y2 = np.cos(x)

y3 = np.sin(2*x)
y4 = np.cos(2*x)

fig, (ax1, ax2) = plt.subplots(ncols=1, nrows=2, figsize=(10, 6))

ax1.plot(x, y1, label='sin')
ax1.plot(x, y2, label='cos')

ax2.plot(x, y3, label='sin')
ax2.plot(x, y4, label='cos')

handles, labels = ax1.get_legend_handles_labels()
# following code does not work
legend = fig.legend(handles, labels, loc='lower left', ncol=2, frameon=False,
              bbox_to_anchor=(0.12, 0.88))
plt.savefig('test.jpg', bbox_extra_artists=[legend,], bbox_inches='tight')

# following code works
# legend = ax1.legend(handles, labels, ncol=2, frameon=False,
#                     loc='lower left', bbox_to_anchor=(-0.01, 1.2))
# plt.savefig('test.jpg', bbox_inches='tight')
plt.show()
```
## outcome
The saved images are different if I use different legend method.
### using `fig.legend` method
![image](https://user-images.githubusercontent.com/16662357/34658251-8e382b0e-f468-11e7-912b-2b2eba51598f.png)

### using `ax.legend` method
![image](https://user-images.githubusercontent.com/16662357/34658289-c5cb6d24-f468-11e7-93d2-b5c149c51095.png)

**Matplotlib version**
  * Operating system: Windows 8.1 and Linux (CentOS 7) (This problem is maybe platform independent)
  * Matplotlib version:  2.0.2(Linux), 2.0.0 (Windows)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.5.2 (Windows), 3.6.2 (Linux)

The matplotlib and python are all distributed with Anaconda.

## quesiton
Is this a bug or something I do not know. Maybe there is difference between `fig.legend` and `ax.legend` method?

**Comment by tacaswell** [comment]
Suspect that this is a bug in the tight bbox code which is not taking the figure legend into account.

**Comment by jdhao** [comment]
Thanks, right now, I will just stick to the `ax.legend` method.

**Comment by anntzer** [comment]
Probably the fix will be similar to https://github.com/matplotlib/matplotlib/pull/9164...

**Comment by dstansby** [comment]
Odd, the bbox caclulation **is** including the legend, but the legend just isn't being drawn. This is obvious to see if one does `bbox_to_anchor=(0.12, 1.5)`:
![test](https://user-images.githubusercontent.com/6197628/56468993-a8361a00-642b-11e9-8b42-95cec5f6a29a.jpg)

**Comment by tacaswell** [comment]
I think the bug is that the legend is, under the hood, drawn with an `OffsetBox` subclass which does not properly take into account the changed bounding box so draws its self outside of the active area.

If you change it to `bbox_to_anchor=(0.5, .5)` then you do see the legend both on the screen and in the jpg, but they are in different places in relation to the axes.

**Comment by Vast-Stars** [comment]
The same problem trapped me for hours.

**Comment by SMV818VMS** [comment]
Same problem

**Comment by tacaswell** [comment]
This needs someone to dig into the two classes and sort out why they are behaving differently.  It is very likely that something is being cached that should not be (which is why the the legend moves around).

**Comment by jklymak** [comment]
Right, so the issue is that somehow the offset for the box is being calculated relative to the current figures origin rather than the original figures origin.  Still not quite sure why, but you can 
easily see this by setting `bbox_inches=mtransforms.Bbox.from_extents([1, 0, 3, 3]` or some such and see it move up or to the right.

**Comment by jklymak** [comment]
bbox_inches works by re-defining `transFigure` to put the origin up and to the right to be tight with the axes decorations.   However, so far as I can see, `legend` and offsetBbox do not participate in the transform logic.  So the offset in `legend` is relative the the bottom left of the current figure, and not transformed.  

I have a fix, but I *thinkt* the proper fix is to fix `offsetBox` to actually have a transform.  But I find the architecture of `offsetBox` extremely hard to understand, so I'm not even sure if that is possible.

**Comment by QuLogic** [comment]
I spent too long last night trying to figure this out. This seems to only occur with `bbox_to_anchor`, because then the offset is determined by:
https://github.com/matplotlib/matplotlib/blob/9ccdb1ddcd6250fac950ddcab97c41f59f68dd72/lib/matplotlib/legend.py#L577
which uses `width` and `height` from `VPacket.get_extent_offsets`, and somewhere in there I guess is where the problem starts happening, but it was too roundabout to figure out just yet.

**Comment by jklymak** [comment]
As noted in #17511, what happens is that `legend` does 
```
       if transform is None:
            transform = BboxTransformTo(self.parent.bbox)
```

`bbox_tight.py` never  changes the parent bbox, but rather directly changes `transFigure`.  So the legend never hears that it should move relative to the bottom left, and stays in the same spot.  

The fix in #17511 is to explicitly set the default `bbox_transform=fig.transFigure` for `figure.legend`.  There is really no reason for it to be generic (as a default).

**Comment by amir-rahnama** [comment]
This problem is showing up again in version 3.1.2 and Python 3.7 and 3.8 btw.

**Comment by jklymak** [comment]
@amir-rahnama please open a new reproducible issue.  The code above works fine for me.
