### ISSUE TITLE
error in construction of inverted log transforms

### ISSUE THREAD

**Issue by fkloosterman** [matplotlib/matplotlib#10202]
### Bug report

The `__init__` method for scale.LogTransformBase takes a required positional argument `nonpos`, but it's derived classes are constructed without that required argument in the `inverted` method.

**Code for reproduction**

```python
import matplotlib.scale as scale
tform = scale.InvertedLog10Transform() #OK
tform = tform.inverted() #not OK
```

**Actual outcome**

```
TypeError: __init__() missing 1 required positional argument: 'nonpos'
```

**Expected outcome**

proper construction of transform object.

**Matplotlib version**

  * Operating system: ubuntu 16.04
  * Matplotlib version: 2.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by magedhennawy** [comment]
should this be closed??
