### ISSUE TITLE
TST: gdb has been removed from Travis

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#10216]
### Bug report

Travis builds were failing.  See below.  Easy kludge was to remove the gdb calls before the pytest call as in #10217.  Passes test, but C++ will no longer get a stacktrace if there are errors.  

This is a placeholder to remind us that gdb should really still be called and the issue investigated.  

OTOH, feel free to close if we don't think the gdb traces are actually crucial.

#### Passes

https://travis-ci.org/matplotlib/matplotlib/jobs/325962082

```
if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
  pytest $PYTEST_ARGS $RUN_PEP8
else
  gdb -return-child-result -batch -ex r -ex bt --args python $PYTHON_ARGS -m pytest $PYTEST_ARGS $RUN_PEP8
fi
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
============================= test session starts ==============================
```

#### Fails

https://travis-ci.org/matplotlib/matplotlib/jobs/327083036

```
if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
  pytest $PYTEST_ARGS $RUN_PEP8
else
  gdb -return-child-result -batch -ex r -ex bt --args python $PYTHON_ARGS -m pytest $PYTEST_ARGS $RUN_PEP8
fi
warning: Error disabling address space randomization: Operation not permitted
============================= test session starts ==============================
```

@QuLogic  also notes that the kernel is different between both tests (though they updated their kernel due to Specter/Meltdown, so maybe all the kernels are new).

Not sure what the solution is.  See

  - https://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted
  - https://rubicks.github.io/post/docker-run-privileged-gdb/

**Comment by jklymak** [comment]
The OS-X runs of course work, so that does point to the `gdb` call being the culprit.

**Comment by QuLogic** [comment]
Based on debug in #10217, it is definitely something in `gdb`. However, disabling address space randomization does not fix it (though the message goes away). I'm wondering if it's perhaps we're making it run a backtrace when the child process has simply exited normally (though this wasn't a problem before.) I'm just not sure how to trigger that conditionally.

**Comment by QuLogic** [comment]
I believe it might be possible in Python 3 to rely on just (pytest-)faulthandler, though I'm not sure how detailed it gets.

**Comment by jklymak** [comment]
@QuLogic does that need action from us to get to work or do you mean it should already work?  Whats the roadmap for this - should we ask Travis what's going on?

**Comment by anntzer** [comment]
I would just set the PYTHONFAULTHANDLER environment variable (https://docs.python.org/3/library/faulthandler.html) in the test env and call it a day until we hit a case where a more detailed traceback proves necessary.
