### ISSUE TITLE
Axes3D.view_init elevation issue between 270 and 360 degrees

### ISSUE THREAD

**Issue by amichaut** [matplotlib/matplotlib#10241]
### Bug report

**Bug summary**

I want to make rotate a 3D plot using the `view_init `method. If the `azim` argument is used it makes a smooth rotation around the z-axis. However, if the `elev` argument is used the plot is flipped after the angle 270 degrees. This problem seems to come from the fact that the range [0:-90] does not give the same output as the range [270:360] while it should. Here are two outputs that should be the same for -15 and 345, but there are not.

![345](https://user-images.githubusercontent.com/11176618/34902501-af08c20a-f7ea-11e7-9326-42e4e0f8eb27.png)
![-15](https://user-images.githubusercontent.com/11176618/34902502-af18b994-f7ea-11e7-8d0f-971215223621.png)

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
from pylab import *

elevation=345 #or -15
angle=None

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
X, Y, Z = axes3d.get_test_data(0.05)
s = ax.plot_surface(X, Y, Z, cmap=cm.jet)
ax.view_init(elev = elevation, azim=angle)
plt.axis('off')
```

**Matplotlib version**
  * Operating system: Debian
  * Matplotlib version: 2.1
  * Matplotlib backend:TkAgg
  * Python version: 2.7

Installed from pip

**Comment by WeatherGod** [comment]
Hmmm, looks like this is on purpose?

```
        if abs(relev) > np.pi/2:
            # upside down
            V = np.array((0, 0, -1))
        else:
            V = np.array((0, 0, 1))
```

Haven't a clue why, though.

**Comment by WeatherGod** [comment]
git blame isn't much help. It has been this way since the inception back in
2009.

**Comment by scottshambaugh** [comment]
This was fixed with https://github.com/matplotlib/matplotlib/pull/21426 and can be closed.
