### ISSUE TITLE
I have determined a color for each data point pragmatically and I have 11 set of x(time) and y(subjects) and I want to make plots for these values(x values) and these colors will be used for the data points on the plots.

### ISSUE THREAD

**Issue by rebeen** [matplotlib/matplotlib#10251]
colors ['violet', 'yellow', 'yellow', 'yellow', 'yellow', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'moccasin']
X  [0, 4, 6, 18, 33, 54, 64, 79, 93, 109, 109, 113]
Y  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
colors ['violet', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'red', 'red', 'red', 'red', 'red', 'moccasin']
X  [0, 8, 10, 10, 11, 13, 23, 40, 44, 65, 80, 81, 89]
Y  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

colors ['violet', 'yellow', 'yellow', 'yellow', 'red', 'red', 'red', 'red', 'red', 'red', 'moccasin']
X  [0, 5, 21, 36, 38, 51, 67, 82, 96, 97, 99]
Y  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
right now I have this plot which is not the one that I want 
![111](https://user-images.githubusercontent.com/1238516/34930805-a8370dc8-f9cb-11e7-9079-f0e2578d03bd.png)
but I want to make this
![513](https://user-images.githubusercontent.com/1238516/34932364-d10991c4-f9d2-11e7-8543-b55dd0b0d1fa.png)

I determined specific colors for a group of data points if you look at the first plot the one that I have created you can see that each subject has a color for all its data points but it should has different color for its data points based on the color that has determined

**Comment by jklymak** [comment]
This isn’t a bug report.

**Comment by story645** [comment]
Please post this to the users mailing list or stackoverflow.
