### ISSUE TITLE
ENH tripcolor with explicit RGB colors

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#10265]
I would like to plot an unstructured triangular mesh and specify my own RGB values per node. I'd use this to create something like

![rgbtricub](https://user-images.githubusercontent.com/181628/35099444-522ed822-fc58-11e7-9203-c2a789bca506.png)

(where the domain is not a triangle but a more complicated shape). At first I though [tripcolor](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.tripcolor.html#matplotlib.axes.Axes.tripcolor) was for me, but it seems that you only specify values for `C` that then get mapped to an RGB triplet via a color map. When specifying an RGB array, one gets the error message
```python
ValueError: Collections can only map rank 1 arrays
```

**Comment by nschloe** [comment]
I just found that the behavior can be emulated by associating integer values with the points and then creating a color map that associated RGBs with the respective integers,
```python
z = numpy.arange(n)
cmap = matplotlib.colors.LinearSegmentedColormap.from_list('mymap', rgb, N=len(rgb))
```
Perhaps that's easy enough.

**Comment by jklymak** [comment]
I don't think any of the `pcolors` accept RGB's.  I'm going to close because you found a work around, and I'm not convinced that there is a huge demand for this.  If you think this is really a desirable enhancement, happy to re-open and walk through a spec for the API.
