### ISSUE TITLE
Documentation of fontdict

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10293]
While working on the docs, I've found a `fontdict` parameter on multiple pyplot functions such as `xlabel`, `text`, `title` etc.

I've not found a concise documentation which values are supported here.

- https://matplotlib.org/gallery/text_labels_and_annotations/text_fontdict.html lists:
   family, color, weight, size
- https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_title.html lists:
  fontsize, fontweight, verticalalignment, horizontalalignment

### Questions:

1. What are the allowed values?
2. What's the exact purpose of this parameter? AFAICS it's simply passing it's contents to a `Text` object, which can already be achieved by kwargs.

**Comment by anntzer** [comment]
Answer to 1) is pretty clearly "any kwarg to Text" and to 2) is probably "because no one complained about the redundant API" (seems to have come in very early, in e34a333).
(funny thing is that many of these kwargs are then themselves forwarded to fontproperties (see also #10249))
I would support making this more principled...

**Comment by timhoffm** [comment]
Thanks for the reply. So this is 'historic'.

Is there a benefit from using `fontdict` compared to `kwargs`?

If not, should this be deprecated for removal in 3.0?
If so, what do we do about it?
- Just document how it works?
- Limit and document the set of accepted parameters?
- Somehow merge it with fontproperties (not looked into this)?

**Comment by jklymak** [comment]
Are all the extra kwargs passed through?  Umm, OK, I'm dumb, but how do I mix a kwarg dictionary with bare kwargs? i.e. `set_title('boo', location='left', kargdict)`    Its pretty convenient to have a dict to pass to all your future text calls.

**Comment by anntzer** [comment]
`set_title('boo', location='left', **kargdict)` will unpack your kwargs there

**Comment by jklymak** [comment]
Certainly we'd want to have lots of examples of this, because I don't think a lot of users know this syntax.

**Comment by efiring** [comment]
It looks like `text._process_text_args` is used only in `figure.Figure.Text`, and all it does there is to return the `fontdict` if it exists, or an empty dictionary if not; so that function can be removed.

I'm not sure that removing the fontdict kwarg itself is a good idea, however.  In various text calls one might want a common font-related properties in a single dictionary, and other kwargs in another dictionary.  Only one of them can be supplied via `**kwargs` (unless this has changed recently).  Having a single common fontdict kwarg also provides some organization to the signature and the corresponding documentation.

I'm not unalterably opposed to deprecating fontdict over several--not just one--release cycles, but I need some convincing.

**Comment by anntzer** [comment]
I think we should also consider the opposite route of requiring text kwargs to be passed in their own dict (as mentioned by @efiring the organization it provides it worthwhile).  Of course this goes back to the general issue of mpl's use of kwargs throughout to set properties through the entire call stack.

**Comment by jklymak** [comment]
I've often found myself confused how to specify font properties and have to look it up.  And then some properties can be set by keyword and others (I think) need to be provided in `fontdict`.  So I'm actually pretty 👍 on simplifying/unifying the API.  

An would be to have a `fontdict()` function that had all the font properties as kwargs so the possible kwargs at least command-completed in various tools.

**Comment by anntzer** [comment]
See #10249 for a writeup/todo on font properties...

**Comment by timhoffm** [comment]
@anntzer I don't think "requiring text kwargs to be passed in their own dict" is a good idea. It would significantly clutter simple use cases, in particular in pyplot

    text('foo', fontdict={'color': red})
    # vs.
    text('foo', color='red')

For the moment, I will just document the current state, that `fontdict` is an additional way of specifying Text parameters by passing a dict as a single argument. This is needed anyway, since `fontdict` will still be around for a while even if we decide to deprecate it or modify its behavior.

**Comment by dopplershift** [comment]
To muddy the waters a bit, @efiring, that behavior about unpacking multiple dicts for kwargs has indeed changed in Python 3, which coincidentally we're about to be able to start using:
```python
def foo(**kwargs):
    print(list(kwargs))

d1 = dict(a=1, b=2)
d2 = dict(c=3, d=4)

foo(**d1, **d2)
```
yields
```
['a', 'b', 'c', 'd']
```

I'm not sure if that affects any arguments.

**Comment by timhoffm** [comment]
Indeed, multiple dicts reduce the benefit of an explicit `fontdict`. Essentially the only use case of the explicit version is the ability to pass two parameter dicts, such as:

~~~
fontdict = {'color': 'red', 'size': 16}
leftaligned = {'multialignment': 'left', 'rotation': 45}
rightaligned = {'multialignment': 'right', 'rotation': -45}
text('foo', fontdict=fontdict, **leftaligned)
text('bar', fontdict=fontdict, **rightaligned)
# ... more text()
~~~

This can then be written as:
~~~
text('foo', **fontdict, **leftaligned)
text('bar', **fontdict, **rightaligned)
~~~

Under these circumstances I vote for deprecating and removing the explicit fontdict parameter.

**Comment by anntzer** [comment]
At least discouraging the use of fontdict seems reasonable here.
