### ISSUE TITLE
patch facecolor does not respect alpha value

### ISSUE THREAD

**Issue by keflavich** [matplotlib/matplotlib#1030]
If you set the facecolor of a patch with an alpha value, e.g.

```
facecolor=(1,0,0,0.5)
```

the alpha value is ignored; only the patch's `_alpha` property is used.  This makes it impossible to have a patch with an opaque edge and a (partially) transparent fill.  

I've only tested this on the TkAgg backend.

**Comment by tommycarstensen** [comment]
I still have this issue with python3 and matplotlib 1.5 when following this example and changing the alpha:
http://stackoverflow.com/a/16563397/778533

**Comment by tacaswell** [comment]
Can you provide a minimal example? It is hard to tell exactly what you are doing from your comment and the link.

**Comment by tommycarstensen** [comment]
Of course. I should have done that from the beginning.

1) Download and unzip:

http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip

2) Run this code with python3 and check Angola, Afghanistan, Algeria and Albania afterwards (they are darker):

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

import matplotlib as mpl
mpl.rcParams['font.size'] = 10.
mpl.rcParams['font.family'] = 'Verdana'
mpl.rcParams['axes.labelsize'] = 8.
mpl.rcParams['xtick.labelsize'] = 6.
mpl.rcParams['ytick.labelsize'] = 6.

fig = plt.figure(figsize=(11.7,8.3))
plt.subplots_adjust(left=0.05,right=0.95,top=0.90,bottom=0.05,wspace=0.15,hspace=0.05)
ax = plt.subplot(111)
x1 = -180.0
x2 = 180.
y1 = -60.
y2 = 85.

m = Basemap(resolution='i',projection='merc', llcrnrlat=y1,urcrnrlat=y2,llcrnrlon=x1,urcrnrlon=x2,lat_ts=(x1+x2)/2)
m.drawcountries(linewidth=0.5)
m.drawcoastlines(linewidth=0.5)

from matplotlib.collections import LineCollection
import shapefile

print('read')
sf = shapefile.Reader('ne_10m_admin_0_sovereignty.shp')
print('shapes')
shapes = sf.shapes()
print('records')
records = sf.records()
d_facecolors = {
    'Africa': ('#e41a1c',),
    'Asia': ('#377eb8',),
    'Europe': ('#4daf4a',),
    'South America': ('#984ea3',),
    'North America': ('#ffff33',),
    'Antarctica': 'white',
    'Seven seas (open ocean)': 'white',
    'Oceania': ('#ff7f00',),
    }
fields = sf.fields
for i, field in enumerate(fields):
    print(i, field)
index = fields.index(['ADM0_A3_WB', 'N', 6, 2])

import matplotlib



set_countries = set()
for record in records:
    set_countries.add(record[3])

for country in list(reversed(sorted(set_countries))):
    for record, shape in zip(records, shapes):
        continent = record[index]
        if record[3] != country:
            continue
        facecolors = [d_facecolors[record[index]]]
        lons, lats = zip(*shape.points)
        ## transpose the data and convert from lat/lon to meters
        data = np.array(m(lons, lats)).T

        ## initiate patches
        ptchs = [[]]
        i_ptchs = -1
        ## get points
        pts = np.array(shape.points)
        pts = data
        ## get parts
        prt = shape.parts
        ## extend length...???
        par = list(prt) + [pts.shape[0]]
        for pij in range(len(prt)):
            path = matplotlib.patches.Polygon(pts[par[pij]:par[pij+1]])

            ## Color Greenland like North America
            if country == 'Denmark' and lons[par[pij]] < 0:
                facecolors.append(d_facecolors['North America'])
                ptchs.append([])

            ## Color French Guiana as South America
            if country == 'France':
                if lons[par[pij]] < 0:
                    if len(facecolors) == 1:
                        facecolors.append(d_facecolors['South America'])
                        ptchs.append([])
                    i_ptchs = -1
                else:
                    i_ptchs = 0

            ptchs[i_ptchs].append(path)
    #        ptchs.append(matplotlib.patches.PathPatch(path))
            if country == 'France':
                print('France', len(ptchs), lons[par[pij]])
        for facecolor, ptch in zip(facecolors, ptchs):
            ax.add_collection(
                matplotlib.collections.PatchCollection(
                    ptch,
                    facecolor=facecolor,
                    edgecolor='k',
                    linewidths=.01,
                    alpha = 0.5,
                    clip_on = True,
                    match_original = True,
                    ),
    ##            set_visible = True,
                )
        continue

        if len(shape.parts) == 1:
            segs = [data,]
        else:
            segs = []
            for i in range(1,len(shape.parts)):
                index1 = shape.parts[i-1]
                index2 = shape.parts[i]
                if record[3] == 'Argentina':
                    print(i, index1, index2, len(shape.parts))
                segs.append(data[index1:index2])
                if record[3] == 'Argentina':
                    print(
                        i,
                        data[index1:index2][0],
                        data[index1:index2][-1],
                        data[index1:index2][0] == data[index1:index2][-1])

            segs.append(data[index2:])
            if record[3] == 'Argentina':
                print(index2, data[index2:][0], data[index2:][-1], data[index2:][0]==data[index2:][-1])
    #    print(record[3], segs[0][0], segs[-1][-1], segs[0][0]==segs[-1][-1])

        lines = LineCollection(segs,antialiaseds=(1,))
        lines.set_facecolors(facecolor)
        lines.set_edgecolors('k')
        lines.set_linewidth(0.1)
    #    ax.add_collection(lines)

plt.savefig('tutorial10.png', dpi=300)

**Comment by tacaswell** [comment]
Does reproducing this depend on basemap?

**Comment by AndrewDDavis** [comment]
I've run afoul of this issue when trying to set the facecolor alpha of boxplot patches. As a workaround, one can set `patch.set_alpha(None)`, and then the alpha of `patch.set_facecolor(RGBA)` will be respected.

**Comment by timhoffm** [comment]
@AndrewDDavis does reproducing this depend on basemap? Could you post a minimal example on the bug?

**Comment by AndrewDDavis** [comment]
The issue arose for me when setting the patch colors in boxplots created by pandas `df.plot.box()`, which sets the alpha of the box patches to 1. Matplotlib's `boxplot()` did not have an issue for me. For example:

```python
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

x = [np.random.randn(10) for _ in range(2)]

# matplotlib
fig, ax = plt.subplots()
bp = ax.boxplot(x, patch_artist=True)

box = bp['boxes'][0]
box.get_alpha()         # no result
box.set_facecolor([1., 0, 0, 0.5])
box.get_facecolor()     # (1.0, 0.0, 0.0, 0.5)

box.set_alpha(1)
box.get_facecolor()     # (1.0, 0.0, 0.0, 1) 

# pandas
df = pd.DataFrame(data=x).transpose()

fig2, ax2 = plt.subplots()
bp2 = df.plot.box(ax=ax2, patch_artist=True, return_type='dict')

box2 = bp2['boxes'][0]
box2.get_alpha()         # 1
box2.set_facecolor([1., 0, 0, 0.5])
box2.get_facecolor()     # (1.0, 0.0, 0.0, 1)

box2.set_alpha(None)
box2.get_facecolor()    # (1.0, 0.0, 0.0, 0.5)
```

If you know that the patch's alpha value is set, and that it will supersede the facecolor value, this behavior is consistent. If you don't realize this, it's surprising when you set a facecolor and the alpha isn't respected.
