### ISSUE TITLE
No link to shared axes for Axis.set_units

### ISSUE THREAD

**Issue by duncanmmacleod** [matplotlib/matplotlib#10304]
### Bug report

**Bug summary**

The `Axis.set_units` method does not emit to linked axes in the same way that `Axes.set_xlim` does (by default).

**Code for reproduction**

```python
from matplotlib import pyplot
from astropy import units
from astropy.visualization import quantity_support

data = units.Quantity([1, 2, 3, 4, 5], 'm')

with quantity_support():
    fig = pyplot.figure()
    ax1 = fig.add_subplot(2, 1, 1)
    ax2 = fig.add_subplot(2, 1, 2, sharey=ax1)
    ax1.plot(data)
    ax2.plot(data)
    print('After first plot:')
    print(ax1.yaxis.get_units())
    print(ax2.yaxis.get_units())
    ax1.yaxis.set_units(units.cm)
    print('After manual set_units():')
    print(ax1.yaxis.get_units())
    print(ax2.yaxis.get_units())
```

**Actual outcome**

```
After first plot:
m
m
After manual set_units():
m
cm
```

**Expected outcome**

If `set_units` was linked to all shared axes, I would expect the call out to `ax1.yaxis.set_units` to also operate on `ax2`.

This is probably best exposed via new `set_xunits` and `set_yunits` methods for the `Axes` object, that include an `emit=True` keyword to use `self._shared_x_axes.get_siblings` in the same way as `Axes.set_{x,y}lim`.

**Matplotlib version**

  * Operating system: macOS 10.13.2
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'agg'
  * Python version: 2.7.14
  * Jupyter version (if applicable):
  * Other libraries: astropy 2.0.2

all installed with macports.

**Comment by jklymak** [comment]
Units support are a bit inconsistent.  Does `astropy` regularly use them for plotting? It'd be good if a dev who uses them regularly could help w/ them in Matplotlib.  We have some old examples JPL wrote, which if I recall correctly don't quite work if you extend them at all.  

See #9713

**Comment by duncanmmacleod** [comment]
@jklymak, astropy provides a `ConversionInterface` that integrates its own `units` package with the matplotlib infrastructure, but I have no idea if its widely used (I have only just started playing with it). I am happy to try and extend the unit infrastructure as I go along, which might not amount to much.

**Comment by jklymak** [comment]
It seems the Matplotlib should consider using a minimal units system for testing.  We have one in `examples/units/basic_units.py`, but it doesn't do sensible things if you start mixing units from what I can tell. What happens if you do 

```python

ax.xaxis.set_units(cm)
ax.plot(x * cm, x)
ax.xaxis.set_units(m)
plt.show()
```

I'd expect to see things plotted in meters, but the conversion happens when `plot` is called, so it never knows about the `m` units.  What happens if we subsequently do
```
ax.plot(datetime(2018,1,1))
```
on that axis?  

This'll all take a bit of thought to do correctly, and maybe when JPL originally did this, they put the thought in, but subsequently its no longer as cohesive.
