### ISSUE TITLE
How to use triplot to make a multi-color line of the triangular

### ISSUE THREAD

**Issue by liubailong-IFS** [matplotlib/matplotlib#10300]
Dear 
I use  matplotlib to deal with finite element results and the grid is triangular , I know the cord(x,y)of the points of the triangular and another parameter(Pressure of the points). So I just want the color change between each two points of the triangle along the line not the areas. Hope  you can help me, Thanks  a lot.

![image](https://user-images.githubusercontent.com/33473208/35260761-7aa18cfe-0050-11e8-8dfe-88c595188a04.png)

**Comment by jklymak** [comment]
This is for issues/bugs, not general user help - try stackexchange or the mailing list...

**Comment by thanojo** [comment]
Hello there,
Sorry to bring this up again, but has there been a solution to this yet? i can't find anything on stackexchange...

**Comment by jklymak** [comment]
No, this is still not for user help.  Please discuss at discourse.matplotlib.org or ask for help at stackoverflow
