### ISSUE TITLE
Matplotlib Sample Outdated?

### ISSUE THREAD

**Issue by wxprofessor** [matplotlib/matplotlib#10318]
### Bug report

**Bug summary**

The Matplotlib Sample: "Plot Precip With Filled Contours"
https://matplotlib.org/basemap/users/examples.html

code source: https://matplotlib.org/basemap/users/figures/plotprecip.py

seems to be dated... I say "seems" because this is my first week of python! :)  

**Code for reproduction**
The variables as specified in your code do not seem to exist:
latcorners = nc.variables['lat'][:]
loncorners = -nc.variables['lon'][:]
lon_0 = -nc.variables['true_lon'].getValue()
lat_0 = nc.variables['true_lat'].getValue()

I'm guessing because that data is from 2006 and something has changed since then :)

I have been failing with new data located here:
http://water.weather.gov/precip/downloads/2018/01/24/nws_precip_1day_20180124_conus.nc

surely there is a way for matplotlib to cull the information needed from the file? if not I figure I'll do the long math.. 

use your code located here
code source: https://matplotlib.org/basemap/users/figures/plotprecip.py

but also notice that not only are the lat lon variables present, your variable:
prcpvar = nc.variables['amountofprecip']

will need to be adjusted to prcpvar = nc.variables['observation']

and the units are now inches instead of mm.

happy python....ing? :)

cheers,

--patrick
```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Can you report on the basemap repo?  Note you may not get much satisfaction as basemap is being phased out.

**Comment by QuLogic** [comment]
The basemap repo is [here](https://github.com/matplotlib/basemap).
