### ISSUE TITLE
imshow documentation has confusing matrix dimensions

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10323]
[This Stackoverflow question](https://stackoverflow.com/questions/48453346/arguments-for-imshow-in-matplotlib-are-ambiguous) brings the confusing matrix dimensions used in the [`imshow` documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html?highlight=matplotlib%20pyplot%20imshow#matplotlib.pyplot.imshow) to our attention. 

![image](https://user-images.githubusercontent.com/23121882/35418515-e0bc43f6-0232-11e8-8797-f2ed98149f80.png)

According to the docstring one may use arrays of shapes `(n, m)` etc. which are then named `MxN`. 

However, according to [wikipedia](https://en.wikipedia.org/wiki/Matrix_(mathematics)) 
> A matrix with m rows and n columns is called an m × n matrix or m-by-n matrix.

This is also the convention used by numpy, e.g. the [arrays.ndarray.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html) speaks about

> A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:
> `x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)`

The documentation should therefore either speak of 

* shape `(n, m)`, or `n x m` array (`nxm` looks strange)
* shape `(N, M)` or `NxM` array
* shape `(m, n)` or `m x n` array 
* shape `(M, N)` or `M x N` array 

Now, which is better? All capitalized or not, `n` or `m` being rows?

**Comment by timhoffm** [comment]
Also mentioned in #10225 .

**Comment by anntzer** [comment]
Should clearly be m first and n second.  I prefer (m, n) but am not going to fight over capitalization and commas vs crosses.

**Comment by ImportanceOfBeingErnest** [comment]
Oh great, @timhoffm If you are already aware of this, this can be just closed as duplicate I guess.

**Comment by timhoffm** [comment]
I propose to find a consensus on the format here before closing. I‘m afraid the other thread has too many aspects to reasonably discuss them there. It‘s more a collection.

**Comment by ImportanceOfBeingErnest** [comment]
This issue is sufficiently addressed by the new docs in #10982. 
Hence I'm closing this.
