### ISSUE TITLE
Missing keys in matplotlibrc.template to move x-axis labels to top

### ISSUE THREAD

**Issue by piecrustinator** [matplotlib/matplotlib#10343]
### Bug report

**Bug summary**

In the matplotlibrc.template, there is an option to set 'xtick.top : True' but there is no option to set the xtick labels on top as well, nor to set the xaxis title on top. Same goes for setting 'ytick.right : True'

**Expected outcome**

Add keys to the matplotlibrc.template so that it becomes possible to move the x-axis to the top of the graph. For instance, something along the lines of:
xtick.labeltop : True / False
xtick.labelbottom : True / False
ytick.labelleft : True / False
ytick.labelright: True / False
xaxis.labeltop : True / False
xaxis.labelbottom : True / False
yaxis.labelleft : True / False
yaxis.labelright: True / False

**Comment by QuLogic** [comment]
Fixed by #10306.
