### ISSUE TITLE
syntax error without a space

### ISSUE THREAD

**Issue by zhubuz** [matplotlib/matplotlib#10341]
I found a bug during I was trying to print a activation function using this lib. There is a syntax error reported, after I put a space there, error fixed. 

The error code is:
```python
>>> w1 = 0.5
>>> w2 = 1.0
>>> w3 = 2.0
>>> l1 = 'w = 0.5'
>>> l2 = 'w = 1.0'
>>> l3 = 'w = 2.0'
>>> for w, l in [(w1, l1), (w2, l2), (w3, l3)]:
...     f = 1 / (1 + np.exp(-x*w))
...     plt.plot(x, f, label=l)
... plt.xlabel("x")
  File "<stdin>", line 4
    plt.xlabel("x")
      ^
SyntaxError: invalid syntax
>>> plt.ylabel("h_w(x)")
<matplotlib.text.Text object at 0x7f65e95274e0>
>>> plt.legend(loc=2)
>>> plt.show()
```

Actual outcome is:
![figure_1](https://user-images.githubusercontent.com/14157833/35495782-919f90de-04fd-11e8-94da-0e1b9cf809f9.png)

after I add a space upon "plt.xlabel("x")":

```python
>>> w1 = 0.5
>>> w2 = 1.0
>>> w3 = 2.0
>>> l1 = 'w = 0.5'
>>> l2 = 'w = 1.0'
>>> l3 = 'w = 2.0'
>>> for w, l in [(w1, l1), (w2, l2), (w3, l3)]:
...     f = 1 / (1 + np.exp(-x*w))
...     plt.plot(x, f, label=l)
... 
[<matplotlib.lines.Line2D object at 0x7f65ee24db38>]
[<matplotlib.lines.Line2D object at 0x7f65ee24dda0>]
[<matplotlib.lines.Line2D object at 0x7f65ee24db70>]
>>> plt.xlabel("x")
<matplotlib.text.Text object at 0x7f65e9513b70>
>>> plt.ylabel("h_w(x)")
<matplotlib.text.Text object at 0x7f65ee8fa400>
>>> plt.legend(loc=2)
<matplotlib.legend.Legend object at 0x7f65ee79d2e8>
>>> plt.show()
```

and the outcome is:
![figure_1-1](https://user-images.githubusercontent.com/14157833/35495793-a53affa2-04fd-11e8-9095-bedc32a538a5.png)

**Matplotlib version**

  * Operating system: ubuntu 16.04 lts
  * Matplotlib version: 1.5.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2
  * Jupyter version (if applicable):
  * Other libraries: 
installed from linux command line: sudo apt-get install python3-matplotlib

**Comment by QuLogic** [comment]
It is the way the interpreter console works; `...` means it is expecting a (indented) block. You need to enter a blank line to exit that mode.

This doesn't have anything to do with Matplotlib.
