### ISSUE TITLE
Python version specific matplotlibrc

### ISSUE THREAD

**Issue by rmccampbell** [matplotlib/matplotlib#10376]
### Bug report

**Bug summary**

There should be a way to use different config files for different python versions, or at least specify different backends for different versions. I have PyQt5 installed for python3, so I prefer to set my backend to Qt5Agg. But occasionally I want to run something in python2 for testing or compatibility purposes. I don't want to waste time and space installing PyQt5 on python2, so I want the backend to stay TkAgg. A workaround is to change the config files in the matplotlib installation, but these will be overwritten on the next install.

**Comment by QuLogic** [comment]
You could use the `MPLBACKEND` environment variable to do that, e.g., if you're using bash, then `alias pympl2='MPLBACKEND=TkAgg python2'` could work.

**Comment by rmccampbell** [comment]
I'm on windows (I could accomplish the same with a bash script) but I would much rather avoid using aliases if possible. By the time I remember I forgot to use the alias I might as well just call mpl.use('TkAgg').

**Comment by tacaswell** [comment]
This would fit with in @anntzer 's advocacy to have the configuration just be a python script.

With our current system this would be a pretty big jump in complexity.

**Comment by anntzer** [comment]
1. #9795 would also solve (in another manner) the OP's problem.
2. You can put a matplotlibrc in the site-packages folder (which is different for each Python version) although it's a bit of a hack (see docs).
3. As mentioned by Tom, pure Python mplrcs would also make this trivial.

**Comment by timhoffm** [comment]
The original use-case has become obsolete due to dropping of Python 2 support. Please reopen if this is still a desirable feature.
