### ISSUE TITLE
Make kiwisolver an optional dependency?

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#10386]
#9082 introduced a nice new geometry manager, but now installing Matplotlib requires installing kiwisolver. Would it be possible to make this an optional dependency that is only needed for doing constrained layout stuff (especially since the layout stuff is experimental at the moment)?

**Comment by jklymak** [comment]
Is `kiwisolver` being a difficult install?

**Comment by dstansby** [comment]
On my machine at least it doesn't seem to come pre-compiled so builds it from a source distribution, which takes ~30 secs. It's not a massive issue, but keeping the install simple with minimum dependencies would be nice.

**Comment by jklymak** [comment]
@tacaswell and @QuLogic discussed on gitter, and should be the final arbitrers.  I have no idea how onerous this dependency is in the general install world, but it would be a shame from a usability point of view if it wasn't installed by default.   e.g. its a lot easier to tell a user to try `constrained_layout=True` then to get them to `pip intstall kiwisolver`, etc etc after they have already installed matplotlib.

**Comment by anntzer** [comment]
Looks like @matthew-brett is trying to get OSX wheels built for that? (https://github.com/nucleic/kiwi/issues/44)
FWIW it is really easy to build a manylinux wheel (once you have a standard manylinux docker setup).

**Comment by story645** [comment]
@jklymak it's also required for the tests...which are there own odd install set.

**Comment by matthew-brett** [comment]
@anntzer - yes I'm using multibuild which builds both OSX and manyinux wheels, as well as Windows wheels:

https://github.com/MacPython/kiwisolver-wheels

The sticking point is the issue you've pointed to.

**Comment by anntzer** [comment]
what's wrong with running pytest from their source folder? (yes, you may prefer being sure not to be accidentally importing something from the source tree, but it's a C-only package with no python component so indeed you won't be importing anything from the source tree (other than the tests))

**Comment by story645** [comment]
I am running pytest from the source folder!

**Comment by anntzer** [comment]
I meant the kiwi tests (the issue mentioned by @matthew-brett in the kiwi repo).

**Comment by matthew-brett** [comment]
@anntzer - yes, that's not a bad idea in our case (where we do have the source repo to hand) - I'll give it a go.

**Comment by QuLogic** [comment]
kiwisolver is in Fedora now.

**Comment by jklymak** [comment]
Thanks a lot @QuLogic

**Comment by matthew-brett** [comment]
The Kiwisolver maintainer @MatthieuDartiailh has kindly put up wheels now:

https://pypi.org/project/kiwisolver/#files

@MatthieuDartiailh - I guess you're planning to keep updating these for new releases?  I'm asking because it may well affect whether Matplotlib takes Kiwisolver as a dependency.

**Comment by MatthieuDartiailh** [comment]
Yes I will keep updating those. Even though I have no short term plans for updates to this library. However should any bugs be found, I will try to address those and release in consequence.

**Comment by dstansby** [comment]
I'm happy leaving this as a dependency in that case - thanks a lot @MatthieuDartiailh for making the wheels!

**Comment by MatthieuDartiailh** [comment]
You should rather thank @matthew-brett for setting up the whole infrastructure. Even the upload of the wheels is automated.

**Comment by matthew-brett** [comment]
I believe there are wheels, for Python 3.5 : https://www.piwheels.hostedpi.com/simple/kiwisolver/
