### ISSUE TITLE
maybe bugs in ax.annotate when get bbox coordinates(matplot-2.1.0)?

### ISSUE THREAD

**Issue by snowflake01986** [matplotlib/matplotlib#10384]
### Bug report

**As others have found, ax.annotate.get_windows_extent will get an odd bbox (including the connection line), but my question is when I continue to transform so as get coordinates of the bbox, the coordinates don't seems to be reasonable**

**snippet code**

```python
import matplotlib.pyplot as plt
import matplotlib
#matplotlib.use("TkAgg")
fig, ax = plt.subplots()

annot = ax.annotate("test", xy=(0,0), xytext=(0.5,0.5), arrowprops=dict(
             arrowstyle = "-",
             connectionstyle = "angle3,angleA=0,angleB=90",
             shrinkA = 0.05), ha='center')



print(annot.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transData.inverted()))
print(annot.get_window_extent(fig.canvas.get_renderer()).transformed(fig.transFigure.inverted()))
print(annot.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transData.inverted()))

annotbbox = annot.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transData.inverted())
ax.plot([annotbbox.xmin, annotbbox.xmin, annotbbox.xmax, annotbbox.xmax, annotbbox.xmin], 
        [annotbbox.ymin, annotbbox.ymax, annotbbox.ymax, annotbbox.ymin, annotbbox.ymin], 'r-')
print(annotbbox.width)
print(annotbbox.height)
print(annotbbox)
ax.axis([-0.2, 1, -0.2,1])
ax.grid()

txt = ax.text(0.7, 0.7, "text")
print(txt.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transAxes.inverted()))
print(txt.get_window_extent(fig.canvas.get_renderer()).transformed(fig.transFigure.inverted()))
print(txt.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transData.inverted()))
txt = txt.get_window_extent(fig.canvas.get_renderer()).transformed(ax.transData.inverted())
print(txt.width)
print(txt.height)
print(txt)
plt.show()
```

**Actual outcome**

```
![snippet](https://user-images.githubusercontent.com/6914064/35840302-5712f166-0b30-11e8-82b4-2c716c464658.png)



Bbox(x0=-0.1871219758064516, y0=-0.14962121212121215, x1=-0.13344254032258063, y1=-0.11174242424242425)
Bbox(x0=-0.02001953125, y0=-0.005208333333333333, x1=0.02158203125, y1=0.02395833333333333)
Bbox(x0=-0.1871219758064516, y0=-0.14962121212121215, x1=-0.13344254032258063, y1=-0.11174242424242425)
0.0536794354839
0.0378787878788
Bbox(x0=-0.1871219758064516, y0=-0.14962121212121215, x1=-0.13344254032258063, y1=-0.11174242424242425)
Bbox(x0=0.75, y0=0.7418831168831169, x1=0.8059475806451613, y1=0.7797619047619049)
Bbox(x0=0.70625, y0=0.68125, x1=0.749609375, y1=0.7104166666666667)
Bbox(x0=0.7, y0=0.6902597402597404, x1=0.7671370967741933, y1=0.7357142857142858)
0.0671370967742
0.0454545454545
Bbox(x0=0.7, y0=0.6902597402597404, x1=0.7671370967741933, y1=0.7357142857142858)
```

**Expected outcome**
my aim was to get the text bbox coordinate on the figure. Without doubt, it didn't work. However, the output should be something to do with the xy(0,0)/xytext(0.5, 0.5) coordinates?

**Matplotlib version**

  * Operating system: ubuntu
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.5.2+
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
I don't think there is a problem with matplotlib here. 

In order to get the bbox coordinates of an artist drawn on a figure, this artist would need to actually be drawn. Especially for artists like ticklabels and annotations, the position is not even calculated before draw time. 

Hence you would get the coordinates that you are probably expecting (not sure what you actually expect, as you did not tell really) by first drawing the figure.

`fig.canvas.draw()`

After that `get_window_extent` should give you a bounding box from which the coordinates in the final plot could be extracted (unless you change anything afterwards which would again change the artist's position).

**Comment by jklymak** [comment]
Is this a bug, documentation issue, or user-support.  For the latter please refer to stackexchange or the email group.  For the first two, can you narrow down what you perceive of as the bug, or whats not clear?

**Comment by snowflake01986** [comment]
@ImportanceOfBeingErnest @jklymak , Thank you both of you. fig.canvas.draw() is exactly what I need. I tried to calculate the position of bbox of an annotation, but the result seemed to be random before making the artist drawn.
