### ISSUE TITLE
Download as PDF or Tex does not work with images created inline using %matplotlib notebook

### ISSUE THREAD

**Issue by the-moog** [matplotlib/matplotlib#10380]
### Bug report

(Originaly raised as [https://github.com/jupyter/notebook/issues/3295](https://github.com/jupyter/notebook/issues/3295)  Though there is some lack of clarity about which parts of Jypyter are managed where - perhaps this itself is a bug?)

Issue:
Download as PDF or Tex does not work with images created inline using %matplotlib notebook

If you create images (graphs etc) using the %matplotlib notebook magic then images created inline are not rendered in Tex or PDF output.

Instead the images is replaced with 
<IPython.core.display.Javascript object>
<IPython.core.display.HTML object>

The suggested workround of replacing **%matplotlib notebook** with **%matplotlib inline** before using 'Download as' is not convienient as it does not work in all cases. 
For example (given below) the figure.set_size_inches methods produces different results.

Also, any dynamic runtime changes to the plots (zoom, pan, etc) are not possible when using inline.

Example code to reproduce the issue
```
import matplotlib.pyplot as plt
import numpy as np

#%matplotlib inline
%matplotlib notebook

fig = plt.figure()
fig.set_size_inches(9.5,6, forward=True)
plt.plot(np.arange(0,10,0.1))
plt.plot(np.arange(10,0,-0.1))
```
File -> Download As -> PDF (Via LaTeX)

This issue is also discussed here:
[https://stackoverflow.com/questions/35305607/jupyter-notebook-matplotlib-figures-missing-in-exported-pdf](https://stackoverflow.com/questions/35305607/jupyter-notebook-matplotlib-figures-missing-in-exported-pdf)

**Actual outcome**
A PDF document containing code but no pictures

**Expected outcome**
A PDF document containing code and pictures

**Matplotlib version**
  * Operating system: Windows 7
  * Matplotlib version: 5.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 2.7.14
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: n/a

Python was installed as msi from Python website
Everything else installed through pip

**Comment by tacaswell** [comment]
attn @mpacer what is the canonical location for nbagg + saving notebooks not play well together?

If you do `plt.close('all')` before saving does that help?

**Comment by efiring** [comment]
I tested with `plt.close('all')`, and it does not change the result.

**Comment by mpacer** [comment]
I think the issue is that there _is_ no canonical location since the issue could arise in either library. 

My intuition is that here for some reason it’s seeing a _repr_latex_ that isn’t doing what we would expect and is dumping the text repr of the object. I think in this case it may be a matplotlib bug. I think the right way to handle this would be to include a _repr_png_ _repr_jpeg_ or _repr_latex_ with a link to the base64 encoded static image. Since the nbagg keeps a channel open to handle updates, you might want to assign these values when the channel is closed. 

The issue is that when exporting to LaTeX we can’t really deal with either html or JavaScript and converting to PDF happens via LaTeX.

**Comment by ghayth82** [comment]
I am facing the same issue, any solution?

**Comment by tacaswell** [comment]
@ghayth82 not directly, but the right place to follow the follow-on to this issue is https://github.com/matplotlib/jupyter-matplotlib/issues/16

**Comment by jklymak** [comment]
I don’t think those are the same.  That issue refers to the new widgets backend.  This issue is using nbagg.

**Comment by tacaswell** [comment]
But in both cases the underlying cause is the widget protocol not being _quite_ rich enough or not specified enough for our needs (or we are just using it wrong).

Long term we want to deprecate notebook in favor of ipympl so if we are going to fix it one place we  should fix it over there.
