### ISSUE TITLE
More documentation `mlab` deprecation.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#10382]
### Bug report

#9151 was merged, but there was some concern that 

  - more of the deprecations in `mlab.py` should have alternates given.  
  - A table of deprecated functions and their alternates should be part of the documentation

**Comment by ImportanceOfBeingErnest** [comment]
Also, there are a lot of examples using functions from `mlab`, as e.g. [image_masked](https://matplotlib.org/examples/pylab_examples/image_masked.html). Those examples should be updated with the alternatives.

**Comment by QuLogic** [comment]
That example does not use `mlab` on [master](https://matplotlib.org/devdocs/gallery/images_contours_and_fields/image_masked.html).
