### ISSUE TITLE
[Question]: Plot the exact number of hexagons using hexbin

### ISSUE THREAD

**Issue by rohitgavval** [matplotlib/matplotlib#10396]
I am trying to use `matplotlib.pyplot.hexbin` to plot a rectangular grid of hexagons. I am facing two difficulties:
1. The grid is not of the desired dimensions. For example, when I try to generate a 6x6 grid of hexagons, I get a grid with one extra row and one extra column (There is one extra hexagon in each row):
![image](https://user-images.githubusercontent.com/29671299/35971537-5809022a-0cf4-11e8-8e21-03fce9f8c824.png)

Instead, I would like to see something like this:
![image](https://user-images.githubusercontent.com/29671299/35971631-c56e25ca-0cf4-11e8-9a64-9656149dbc4e.png)

Is there a way I could achieve this using hexbin?

2. Sometimes the grid gets cropped, even when the `figsize` is increased.
![image](https://user-images.githubusercontent.com/29671299/35971821-75c98fae-0cf5-11e8-9988-94aab141dfb6.png)

I am using the code from this page:
https://pythontic.com/visualization/charts/hexagonalbinning

How can I get around this?

**Comment by ImportanceOfBeingErnest** [comment]
Concerning the second problem, one might opt to use `autoscale` or `margins(0)` to fit the plot tight into the axes. 

```
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)
xData = np.random.random_integers(1, 10, 100)
yData = np.arange(0, 100, 1)

fig, (ax,ax2) = plt.subplots(ncols=2, figsize=(5,2.5))

ax.hexbin(xData, yData, gridsize=6, edgecolor=None)

ax2.hexbin(xData, yData, gridsize=6, edgecolor=None)
ax2.margins(0) 
#ax2.autoscale()


ax.set_title("default")
ax2.set_title("use autoscale() or margins(0)")
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/35974248-93746500-0cd8-11e8-945a-3d44a7dccc7f.png)

Not sure if this should be made the default.  So I guess the question here can be whether `hexbin` should call `autoscale` or `margins(0)`, or whether a solution similar to how bar charts are forced to stick to zero should be incorporated into the hexbin plot.  

Converning the first part, this is not really clear. What should happen to points that then lie outside the shown hexbins? E.g. in the picture below, should the red data points be ignored?

![image](https://user-images.githubusercontent.com/23121882/35974667-48443ad6-0cda-11e8-8bdb-2cfa9444ea76.png)

Second, what property should determine how the bins would be arranged? E.g. for a 2 x 3 grid, there would be the two options below.

![image](https://user-images.githubusercontent.com/23121882/35974984-74ee025a-0cdb-11e8-9762-797514ef987f.png)

**Comment by rohitgavval** [comment]
Regarding the second problem, I would like to see exactly the opposite of what margins(0) does. That is, I would like to see all the corners of the hexgrid in the plot. How can I make hexbin do that?

**Comment by ImportanceOfBeingErnest** [comment]
Second question: Use `ax.margins(1./n)` where `n` is the number of bins, e.g. `ax.margins(1./6)` for the 6 bins from the example. Make sure to call this *before* the hexbin plot, i.e. the axes needs to know that it will need this margin before knowing that it will show a hexbin plot. 

First question: I would translate this to the wish to have something like `pcolorhex`, in similarity to `pcolormesh` or `tripcolor`, to be able to plot data on hexagonal grids.

**Comment by dstansby** [comment]
Since this is a question that appears to have been answered, I'm going to close it. Feel free to re-open if there are any problems.

**Comment by franzoni** [comment]
Thanks a lot for the info!
By the way, at least on my setup makes no difference

**Comment by franzoni** [comment]
```
import numpy as np
import matplotlib.pyplot as plt

# Fixing random state for reproducibility
np.random.seed(19680801)

n = 10000
xmin = 0
xmax = 12
xbins= 6
ymin = 0
ymax = 12
ybins= 6
x = np.random.randint(low=xmin,high=xmax, size=n)
y = np.random.randint(low=ymin,high=ymax, size=n)
c = x+y

fig, axes = plt.subplots(ncols=2, sharey=True, figsize=(14, 9))
fig.subplots_adjust(hspace=0.5, left=0.07, right=0.93)

ax=axes[0]
hb = ax.hexbin(x, y, gridsize=(xbins,ybins), cmap='inferno')
#https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hexbin.html
#hb = ax.hexbin(x, y, C=c, gridsize=(xbins,ybins), cmap='inferno')
ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))
ax.set_title("With a linear color scale")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('Just some counts')
# https://github.com/matplotlib/matplotlib/issues/10396#issuecomment-364109974

ax=axes[1]
hb = ax.hexbin(x, y, gridsize=(xbins,ybins), cmap='inferno')
ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))
ax.set_title("With a linear color scale")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('Just some counts')
# https://github.com/matplotlib/matplotlib/issues/10396#issuecomment-364109974
ax.autoscale()
# setting margins has not effect
#ax.margins(0) 

plt.show()
```

**Comment by franzoni** [comment]
![download](https://user-images.githubusercontent.com/4729828/70612029-7108b900-1c06-11ea-8f8d-5886146b7f02.png)
