### ISSUE TITLE
Cairo backend marker/line style

### ISSUE THREAD

**Issue by seberg** [matplotlib/matplotlib#1039]
Small thing... using matplotlib.use('cairo.pdf') and plt.plot([1,2,4,3], '--o'), etc. the black lines surrounding the markers are actually drawn using the same line style. ie. 'o:' would have black dots surrounding the circle. The newest version I tried this with was 1.1.1 shipped with ubuntu.

**Comment by tacaswell** [comment]
This is related to cairo being a stack based graphic context and the underlying cairo context can get changed without it being reflected in the python layer.

**Comment by tacaswell** [comment]
This needs a fix similar to: https://github.com/matplotlib/matplotlib/pull/4542

I suspect that `restore` should just reset a bunch of internal state.

**Comment by QuLogic** [comment]
Is this still broken? I can't seem to reproduce with 1.5.3 and the cairo backend (there is no cairo.pdf backend.)

**Comment by tacaswell** [comment]
Closing as @QuLogic can not reproduce.

@seberg Please ping to have this re-opened if this is still an issue.
