### ISSUE TITLE
ax.get_legend().get_title().get_visible() does not work

### ISSUE THREAD

**Issue by boeddeker** [matplotlib/matplotlib#10391]
I use a wrapper around matplotlib and set there automatic the legend. 
When the legend do not contain a title, everything works fine.
When I set after the first plot the legend title and call `ax.legend()` after the second plot, this overwrites the title and I have to use `ax.legend(title=title)`. With `ax.get_legend().get_title().get_text()` I get the current legend title.

The Problem is that the default title value (None) is converted to text, so `ax.get_legend().get_title().get_text()` returns the str None and not the object None.
So calling `ax.legend(title=ax.get_legend().get_title().get_text())` does not work. When there was initially no title.

So I thought I set the legend title only when `ax.get_legend().get_title().get_visible()` is True, but this does not work because the call returns always True.

Currently, I have to call `ax.get_legend()._legend_title_box.get_visible()`, but `_legend_title_box` is a private property.

The relevant matplotlib code is here:
https://github.com/matplotlib/matplotlib/blob/bf2127b21690b79b4fb200984446498f17fff85e/lib/matplotlib/legend.py#L1100

An example, when someone what to test what I wrote:
```python
import matplotlib.pylab as plt

x1, y1 = [1, 2, 3], [3, 4, 5]
x2, y2 = [1, 2, 3], [3, 4, 6]

def plot(x, y, label, title=None, ax=None):
    if ax is None:
        _, ax = plt.subplots(1, 1)
    ax.plot(x, y, label=label)
    if title:
        ax.legend(title=title)
    else:
        ax.legend(title=ax.get_legend().get_title().get_text() if ax.get_legend() and ax.get_legend()._legend_title_box.get_visible() else None)
        # ax.legend()  # does not keep the title
    return ax
    
ax = None
ax = plot(x1, y1, '1', title='title', ax=ax)
ax = plot(x2, y2, '2', ax=ax)  # no legend title, when ax.legend()  is used

ax = None
ax = plot(x1, y1, '1', title='title1', ax=ax)
ax = plot(x2, y2, '2', title='title2', ax=ax)  # title2 win, is ok

ax = plot(x1, y1, '1', ax=ax)
# Figure out if there is a legend title
print(ax.get_legend().get_title().get_visible())  # wrong output (True), legend title is not visible
print(ax.get_legend()._legend_title_box.get_visible())  # correct output (False), legend title is not visible

```

```
$ pip show matplotlib
Name: matplotlib
Version: 2.1.0
Summary: Python plotting package
Home-page: http://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: BSD
Location: /opt/anaconda/lib/python3.6/site-packages
Requires: numpy, six, python-dateutil, pytz, cycler, pyparsing
```

Depending on your opinion the Bug is one of the following points:
 - `ax.legend()` should keep the title
 - `ax.get_legend().get_title()` or `ax.get_legend().get_title().get_text()` is None
 - `ax.get_legend().get_title().get_visible()` returns False when the legend title is not visible

**Comment by jklymak** [comment]
OK, confirmed.  

Confirmed,

The confusion is that `get_title` returns the actual text of the title, and the visibility of that text is always true.  The only visibility that gets set to False is `_title_box`, which has no public method. 

Worse, the (hidden) title gets set to the string `"None"` which is silly.

**Comment by boeddeker** [comment]
Thanks for the fix, that simplifies my code.

How about keeping the title of the legend?

The code would then be something like (I do not know, why `_parse_legend_args` has axs and not ax):
```python
        # Check if the old legend (if exist) has a title
        ax = ...  # self or axs[0]
        if ax.legend_:
            kwargs.setdefault(
                'title',
                ax.legend_.get_title().get_text()
            )
```
Here the positions, where it could be fixed:
https://github.com/matplotlib/matplotlib/blob/005a6036b83c91e3142ab574849fdd0bc89023bc/lib/matplotlib/axes/_axes.py#L555
https://github.com/matplotlib/matplotlib/blob/005a6036b83c91e3142ab574849fdd0bc89023bc/lib/matplotlib/legend.py#L1402

**Comment by Vickershhh** [comment]
So this bug has been fixed already?

**Comment by boeddeker** [comment]
It depends. 
Should ax.legend() reset the legend title?
If yes, than this bug is fixed, because I can achieve what I want without using a private attribute.

If not, something like my last commit needs to be implemented.

In my mind it feels more expectable when ax.legend do not reset the legend title.

**Comment by jklymak** [comment]
Yes, if you call ax.legend() it resets the legend, including the title.  Not quite sure how making legend properties persistent across calls to legend would work.

**Comment by boeddeker** [comment]
Inside of ax.legend is the old legend known, so it is possible to get the old title and provide it as fallback in kwargs with setdefault. And when your PR is merged there is no check required if the old text is "None".

**Comment by jklymak** [comment]
It’s possible to do either.  But the question is if you hav to explicitly set the title or explicitly clear it.  I’d argue you should explicitly have to set it, and clearing is implicit.  But I don’t often use legend titles, and wouldn’t object to needing explicit clearing...

**Comment by boeddeker** [comment]
Following your argumentation, I would say explicitly clear it would be better because when you rarely use it, it is few "overhead" to clear the title. But when you use it, it is annoying to write the code to keep the title.
A further point, when you set the legend title you normally want to have a title in the legend and it is in my mind rarely the case that you clean it (Or maybe this never happen?).

In my example where I hit this problem, I have a function that plots many lines and write the parameter values into the legend and the parameter keys into the legend title. After that plot I added one further line also with a label. But since the label require a call of `ax.legend()`, I had to get the title and set the title again.

This is the code, that say keep the title:
```python
ax.legend(title=ax.get_legend().get_title().get_text() if ax.get_legend() and ax.get_legend().get_title().get_visible() else None)
```
and this for reset
```python
ax.legend(title=None)
```
For me is the reset example easy to remember and feels natrual, but for the keep example I have to look into old code to remember what I have to use.

**Comment by jklymak** [comment]
Or you could just have a local variable and keep track of the title yourself.

**Comment by boeddeker** [comment]
Keeping the legend title as a local variable is in my example to much work, above code to keep the legend is easier.
I use an abstraction layer between my code in the ipython notebook and matplotlib, so the call to `ax.legend` is not in the notebook and also the code that sets the legend title is not in the notebook.
So I keeping it as a local variable means, I have to return the value (bad style) or extract it from the legend (similar to keeping the legend title).

Here an example plot where I hit this problem (Note: `pd_plot.line` is a private function).
After that plot I wanted to add some further lines to the graphs with a label that reset the legend title.
```python
import numpy as np
import pandas as pd

# produce a Dataframe for all combinations with random y value
data = {'x1': [1, 2], 'x2': [2, 3], 'hue1': [4, 5], 'hue2': [6, 7], 'hue2': [8, 9], 'subplot1': [10, 11], 'subplot2': [12, 13], 'y': [1]}
k, v = zip(*sorted(data.items()))
from itertools import product
example_df = pd.DataFrame(
    [dict(zip(k, values)) for values in product(*v)]
)
example_df['y'] = example_df['y'] + np.random.normal(size=len(df_tmp['y']))

pd_plot.line(
        data=example_df,
        x=['x1', 'x2'],
        y='y',
        hue=['hue1', 'hue2'],
        subplots=['subplot1', 'subplot2']
    )
```
![download 11](https://user-images.githubusercontent.com/13744128/36156773-5d3c52be-10d8-11e8-9faf-9eb9f4776508.png)

Since your opinion is that an implicit reset is the desired behavior, this issue can be closed and I change my matplotlib wrappers to handle this correctly how I need it.

**Comment by jklymak** [comment]
It’s just my opinion.  You are welcome to submit a PR and get traction for it.  I’m not saying my opinion carries any particular weight.

**Comment by boeddeker** [comment]
When there is at least one other person interested in a changed behavior, I will prepare a PR when #10392 is merged, else a PR is to much work because my code already has a fix.

**Comment by NCSUphytotron** [comment]
I am interested!  I'm surprised no one else has noticed that in addition to 
ax.get_legend().get_title().get_visible() always returning True
ax.get_legend().get_visible() also always returns True

**Comment by NCSUphytotron** [comment]
Exactly.  I just want to show and hide the legend on demand but keep all its properties the same.

I've been working all morning to shorten my code (which is usually around 1300 lines) for a sscce.  Is 264 lines acceptable to post here?

**Comment by ImportanceOfBeingErnest** [comment]
I don't think anyone will read that code. Usually a problem is depictable with some 20 lines.

**Comment by NCSUphytotron** [comment]
Ok I got it down to 60ish lines...         Temp_Axes.legend().get_visible()   ALWAYS RETURNS TRUE!
```
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
import time
from Tkinter import *

#--------------Create TK window, frames, variables, callback functions, and widgets---------                    
root = Tk()

def toggleLegend():  
    vis = Temp_Axes.legend().get_visible()   #THIS ALWAYS RETURNS TRUE!
    print vis 
    Temp_Axes.legend().set_visible(not vis)  #EVEN AFTER IT HAS BEEN SET FALSE HERE
    
#TK Frames
clock_f=Frame(root)
clock_f.grid(row=0,column=1,sticky=E+S+W)
graphframe=Frame(root, width=400, height=300) 
graphframe.grid(row=2,rowspan=2, column=0,columnspan=3,sticky=N+W+E+S)
#TK variables
tk_time=StringVar()
#TK widgets
Label(clock_f,textvariable=tk_time,font=("Calibri",28,"bold"),bg="#CC0000",fg="White").pack(side=LEFT)
Button(clock_f,text="toggle legend",command=toggleLegend, width=25,height=3).pack(side=LEFT)
#infinite loop for updating tkinter variables and draw() command which have to be in the main thread
def Tkinter_update():      
    delay=1
    while True:
        delay+=1
        tk_time.set(time.strftime("%H:%M:%S"))
        # plus many many more tk variables....
        if (delay > 12):    # every nth cycle...
            Graph_Figure.canvas.draw_idle()
            Graph_Figure.canvas.flush_events()
            delay = 0
        root.update()
        time.sleep(.2)

#---------------------Configure and define graph properties--------------------------------
Graph_Figure = Figure(figsize=(9.4,5.3),frameon=False)    
Graph_Figure.subplots_adjust(left=.09, right=.9, top=.93, bottom=.1)
TKcanvasAgg=FigureCanvasTkAgg(Graph_Figure, master=graphframe)   
TKcanvasAgg.get_tk_widget().pack()

Light_Axes = Graph_Figure.add_subplot(211, label='Light',facecolor='gray')
CO2_Axes = Graph_Figure.add_subplot(211,label='CO2',frameon=False,sharex=Light_Axes)   
RelHumid_Axes = Graph_Figure.add_subplot(211,label='RelHumid',frameon=False,sharex=Light_Axes)
AbsHumid_Axes = Graph_Figure.add_subplot(211,label='AbsHumid',frameon=False,sharex=Light_Axes)  
Temp_Axes = Graph_Figure.add_subplot(212,label='Temperature',facecolor='gray')

GP0, = Light_Axes.plot([],[],'-',color='w',linewidth=3)
GP5, = Temp_Axes.plot([],[],'o',color='black',ms=1,zorder=8,label='light temp')
GP1, = Temp_Axes.plot([],[],'o',color='magenta',ms=1,zorder=18,label='control air')
GP3, = Temp_Axes.plot([],[],'o',color='cyan',ms=1,zorder=14,label='CW supply') 
GP4, = Temp_Axes.plot([],[],'om',color='navy',ms=1,zorder=16,label='CW return')
GP2, = Temp_Axes.plot([],[],'o',color="#CC0000",ms=1,zorder=30,label='chamber temp')
GP6, = RelHumid_Axes.plot([],[],'_b',ms=3,zorder=12,scalex=False)                    
GP7, = AbsHumid_Axes.plot([],[],'_b',ms=3,zorder=10,scalex=False)                    
GP8, = CO2_Axes.plot([],[],'o',color='green',ms=3,zorder=6,scalex=False)
Temp_Axes.legend(loc='upper left',framealpha=0.2,markerscale=5)

#start threads (not shown) and tkinter update function
Tkinter_update()

```
There is probably going to be several things that you don't understand why I'm doing that would make more sense if you could see the rest of my code.

**Comment by jklymak** [comment]
You want to call `TempAxes.get_legend()` or save as a variable.  Calling `TempAxes.legend()` remakes the legend each time so of course its visible.

**Comment by ImportanceOfBeingErnest** [comment]
As I said above:

> You usually would not call `legend` more than once.

In your code you call it twice per button click. 
Here is a minimal example of how your code should look like. This is more to show you how a minimal example should look like than solving your issue.

```
import matplotlib.pyplot as plt

fig, ax= plt.subplots()
ax.plot([1,2,3], label="bla bla")
ax.legend()

def toggleLegend(evt):  
    vis = ax.get_legend().get_visible()
    print vis
    ax.get_legend().set_visible(not vis)
    fig.canvas.draw_idle()

fig.canvas.mpl_connect("button_press_event", toggleLegend)

plt.show()
```

**Comment by NCSUphytotron** [comment]
Oh wow, thanks my dudes!  I didn't notice the subtle difference of the "get_" in the first half of my command.  What a moron I am.  I guess you have to get the get_ of the get_.

Yeah my next project is to mess around with that mpl_connect() business to toggle individual lines on and off.
