### ISSUE TITLE
wxagg is broken as of master

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10418]
### Bug report

See https://github.com/matplotlib/matplotlib/pull/10210#issuecomment-364758376 and following comments for possible fix.

Would have been nice if test_backends_interactive caught this...

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by DietmarSchwertberger** [comment]
With the merge of PR #10395 this seems to be fixed.
