### ISSUE TITLE
Confusing log message from GridSpec

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#10424]
With master, running `plt.subplots()` is generating the log message from the following code in gridspec.py, `GridSpec.__init__`:
```python
        if (self.figure is None) or not self.figure.get_constrained_layout():
            _log.info("GridSpec must be called with the fig keyword if "
                    "constrained_layout is used")
            self._layoutbox = None
```
Every call to `subplots` in existing code is supplying the figure without constrained_layout, so this message makes no sense.

**Comment by QuLogic** [comment]
Should be removed in #10407?

**Comment by efiring** [comment]
Thank you.  Things are changing faster than I can keep up...

**Comment by jklymak** [comment]
Sorry.  I thought that was interesting info.  I didn’t realize so many people changed the default log level
