### ISSUE TITLE
find points which lies strictly inside the polygon

### ISSUE THREAD

**Issue by igniteeng000** [matplotlib/matplotlib#10430]
**Feature**

**Code for reproduction**

```python
# Paste your code here
if points does not lies on path:
      print(points)
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
You may have misunderstood the matplotlib issue tracker. What exact issue do you want to report about here? It may help to stick to the template when creating an issue. 

Note that if you have a question on how to *use* matplotlib, this is not necessarily the right place to ask. There is a matplotlib mailing list for such things, or consider asking a question on stackoverflow.com.

**Comment by igniteeng000** [comment]
Sorry, but can you briefly explain how it can be done?

**Comment by ImportanceOfBeingErnest** [comment]
Which part of my previous comment was not clear?

**Comment by igniteeng000** [comment]
I am asking about how we can exclude the points which lies on polygon path

**Comment by tacaswell** [comment]
@igniteeng000 Thanks for taking the time to reach out, but we prefer to handle this sort of question through other venues.  Either the user mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users you will have to join to post un-moderated) or stackoverflow.
