### ISSUE TITLE
broken link in lib/matplotlib/dates.py comment

### ISSUE THREAD

**Issue by pseyfert** [matplotlib/matplotlib#10453]
### Bug report

Not really a bug in terms of misbehaving code. I was just trying to understand lib/matplotlib/dates.py and and found a link in a comment that lead nowhere.

https://github.com/matplotlib/matplotlib/commit/268ca34d75362198f2ed94ea595bdf1fbf4e0f12#diff-e6ad13bbdbf1912ae565e5ed7f274144R515

https://bugs.python.org/issue177742

The code just says

```python
if dt.year >= 1900:
    # Note: in python 3.3 this is okay for years >= 1000,
    # refer to http://bugs.python.org/issue177742
    return cbook.unicode_safe(dt.strftime(fmt))
```

**Expected outcome**

The link leads to an existing bug which can then be read.

**Matplotlib version**

Cloned the current master, e.g. 86514a28111417d713672abf1717fd7ec5802bcd, but also in matplotlib 2.0.0

**Comment by jenshnielsen** [comment]
I would guess that the correct issue is https://bugs.python.org/issue1777412

**Comment by pseyfert** [comment]
Thanks, that looks correct indeed.

(I realised now I could've found that https://github.com/matplotlib/matplotlib/pull/3242#issuecomment-62784225 in the discussion of the merge request that added the comment).

Should I make a tiny PR that adds the missing digit?

**Comment by tacaswell** [comment]
@pseyfert Yes please!
