### ISSUE TITLE
Interactive plots stay small when process busy on HiDPI displays

### ISSUE THREAD

**Issue by ahoereth** [matplotlib/matplotlib#10456]
### Bug report

**Bug summary**

When using `%matplotlib notebook` in Jupyter Notebooks on a HiDPI screen (tested on multiple MacBooks of different generations), the plot stays half-sized until the cell is finished with all its computations. 

**Code for reproduction**

```python
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import time

def draw(ax):
    """Scatter some new data into an axis."""
    ax.cla()
    ax.scatter(*np.random.rand(2, 1000))
    ax.get_figure().canvas.draw()

_, ax = plt.subplots(1, 1)

for _ in range(10):
    # Draw some new data
    draw(ax)
    # Do some intermediate computations
    time.sleep(.1)

# Plot wont upscale till this sleep is over
time.sleep(10)
```

**Actual outcome**

Plots stay small until last `sleep` finishes.

**Expected outcome**

Plots should rescale to screen's DPI right after initial drawing.

**Matplotlib version**

  * Operating system: Ubuntu 16.04 / macOS 10.13
  * Matplotlib version: `2.1.2`
  * Matplotlib backend: `nbAgg`
  * Python version: `3.6.4`
  * Jupyter version: `4.4.0`

**Other Information**

#5383 is probably relevant for when attempting to fix this problem.

**Comment by tacaswell** [comment]
There is something not quite right with the way we handle the negotiation about what the screen DPI is and  do not fix it until the second draw.  The way that draw gets triggered as the js side sends a message back asking for a re-draw, but we do not process that request until your code stops blocking.

The first issue can probably be fixed, but the second probably can not (see https://github.com/matplotlib/matplotlib/pull/4779 for longer discussion) be (at least in general and not without work on the jupyter side as well.

Would you be interested in working on fixing this?

Also have a look at https://github.com/matplotlib/jupyter-matplotlib which is built on top of ipywidgets and may behave better.
