### ISSUE TITLE
matplotlib install fails under windows 7 with python_d

### ISSUE THREAD

**Issue by b-v** [matplotlib/matplotlib#10477]
### Bug report

**Bug summary**
Hi,

If I try to install matplotlib on Windows 7 via `python_d -m pip install matplotlib` it fails with 
`Command "python setup.py egg_info" failed with error code 1 ...` and `... \site-packages\pip\basecommand.py:229: ResourceWarning: unclosed file <_io.BufferedReader name=3>`

It might be related to issue #9176, in the sense that this ResourceWarning is reported as well (in one of the comments). It fails with both python 3.6.4 and python 3.7.0b1. If I use `python.exe` instead of `python_d.exe` it does work with python 3.6.4.

**Matplotlib version**

  * Operating system: Windows 7 Enterprise
  * Matplotlib version: 2.1.2
  * Python version: 3.6.4, 3.7.0b1

Python has been installed by using the executable installer from www.python.org/downloads/windows. Then I run the aforementioned `pip` command.

Thanks

**Comment by QuLogic** [comment]
Please post the entire message.

**Comment by dstansby** [comment]
@b-v did you get a chance to try this again?

**Comment by anntzer** [comment]
Closing per lack of information.  Feel free to request a reopen with more info.
