### ISSUE TITLE
cmp() is an undefined name in Python 3

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#10501]
These three files each contain at least one call to the Python 2-only builtin function __cmp()__ that was removed in Python 3.  Without a change (removing the surrounding `__cmp__()` method altogether?), a NameError or TypeError: unorderable types could be raised at runtime.

* http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp
* http://python-future.org/compatible_idioms.html#cmp

flake8 testing of https://github.com/matplotlib/matplotlib on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/matplotlib/testing/jpl_units/Duration.py:95:14: F821 undefined name 'cmp'
      return cmp( self._seconds, rhs._seconds )
             ^
./lib/matplotlib/testing/jpl_units/Epoch.py:144:17: F821 undefined name 'cmp'
         return cmp( t._jd, rhs._jd )
                ^
./lib/matplotlib/testing/jpl_units/Epoch.py:146:14: F821 undefined name 'cmp'
      return cmp( t._seconds, rhs._seconds )
             ^
./lib/matplotlib/testing/jpl_units/UnitDbl.py:142:14: F821 undefined name 'cmp'
      return cmp( self._value, rhs._value )
             ^
```

**Comment by tacaswell** [comment]
Attn @TD22057
