### ISSUE TITLE
'FigureManager' is an undefined name in backend_wx.py

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#10502]
flake8 testing of https://github.com/matplotlib/matplotlib on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/matplotlib/backends/backend_wx.py:1485:18: F821 undefined name 'FigureManager'
        figmgr = FigureManager(canvas, 1, self)
                 ^
./lib/matplotlib/backends/backend_wx.py:1548:18: F821 undefined name 'FigureManager'
        figmgr = FigureManager(canvas, 1, frame)
                 ^
```

**Comment by tacaswell** [comment]
These are injected via the https://github.com/matplotlib/matplotlib/blob/5d30d6a38fd13f42deeb90e985719516ed14e76a/lib/matplotlib/backends/backend_wx.py#L1969 class decorator at the bottom.
