### ISSUE TITLE
show() is an undefined name in backend_webagg.py

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#10500]
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_webagg.py#L54

flake8 testing of https://github.com/matplotlib/matplotlib on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/matplotlib/backends/backend_webagg.py:54:9: F821 undefined name 'show'
        show()
        ^
```

**Comment by anntzer** [comment]
Basically same as https://github.com/matplotlib/matplotlib/issues/10502#issuecomment-366372404.  Closing this side, we can discuss on the other issue whether there is a better way to handle this without restoring the large amount of code duplication previously present.
