### ISSUE TITLE
Use long color names for rc defaultParams

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10550]
### Change Request

`rcsetup.defaultParams` uses the single-letter shorthands for color definitions. This leads to definitions like these:

~~~
    'text.color':          ['k', validate_color],     # black
    'axes.facecolor':        ['w', validate_color],  # background color; white
~~~

I propose to exchange them for the long color names 'black' and 'white' for better readability.

Is there something to be aware of when changing the string without changing the semantics or can I simply replace them?

**Comment by efiring** [comment]
They are not exactly equivalent, but I think you should be able to replace them.  The difference is that the single-letter colors can be used for the abbreviated style arguments as in `plot(x, y, 'ro')`, so if the rcParams value were ever being used in a string substitution to generate such an argument, the long name would break it.  I would call that "revealing an existing bug" in whatever code was foolishly relying on a single-letter color specification.
