### ISSUE TITLE
Special conversions of xrange()

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#10556]
Documenting these requests so they do not get lost...

#10525 attempted to convert all calls to __six.moves.xrange()__ into calls to __range()__ as part of the removal of Python 2 support.  There were [several suggestions](https://github.com/matplotlib/matplotlib/pull/10525#pullrequestreview-97434039) to make alternative conversions:

- [ ] These functions should just be deleted as they have been deprecated since 2.1: [one](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/__init__.py#L950) and [two](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/__init__.py#L11770)
- [ ] Probably better written using [__np.stack()__](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html) or a variant of it: [one](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L564-L566) and [two](https://github.com/matplotlib/matplotlib/blob/master/lib/mpl_toolkits/axes_grid1/colorbar.py#L532-L534)
- [ ] Probably should be [__itertools.count()__](https://docs.python.org/3/library/itertools.html#itertools.count): [one](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/sphinxext/plot_directive.py#L600)

After these changes are made, the lines containing __from six.moves import xrange__ should also be removed.

**Comment by tacaswell** [comment]
:+1: Thanks for doing this @cclauss

**Comment by mc10** [comment]
The first point should be fixed once #10608 is merged.

**Comment by anntzer** [comment]
All points have been handled.
