### ISSUE TITLE
contour and contourf treat levels differently

### ISSUE THREAD

**Issue by boeleman** [matplotlib/matplotlib#10572]
### Bug report

**Bug summary**

When setting levels that span a wider range of values than the data set, contourf correctly picks the right  colors to fill the areas between the contour lines. contour does not use the same colors.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

levels = np.arange(-100, 100, 10)

x = np.loadtxt(open('x.txt','rb'),delimiter=',')
y = np.loadtxt(open('y.txt','rb'),delimiter=',')
z = np.loadtxt(open('z.txt','rb'),delimiter=',')

#CS = plt.contour(x, y, z, levels)
CS = plt.contourf(x, y, z, levels)

CB = plt.colorbar(CS)

plt.show()
```

The data is attached.

**Actual outcome**

When plotting with contour instead of contourf the colors range is scaled according to the maximum and minimum of the used data.

**Expected outcome**

I would expect contour to respect the range set in levels.

**Matplotlib version**

  * Operating system: Debian unstable
  * Matplotlib version: 2.1.1-2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 
  * Jupyter version (if applicable):
  * Other libraries: 

[z.txt](https://github.com/matplotlib/matplotlib/files/1750666/z.txt)
[y.txt](https://github.com/matplotlib/matplotlib/files/1750667/y.txt)
[x.txt](https://github.com/matplotlib/matplotlib/files/1750668/x.txt)

Installed from Debian package

**Comment by boeleman** [comment]
A work around can be found here:

https://stackoverflow.com/questions/18599625/matplotlib-standard-colormap-usage

**Comment by dstansby** [comment]
Could you post an example that uses generated data instead of data in files? Maybe using `np.random.rand`?

**Comment by boeleman** [comment]
This is an example with generated data. This script plots two figures. One with a range of 100:-100 and one 40:-40. They should both be 100:-100.

```python
import numpy as np
import matplotlib.pyplot as plt

levels = np.arange(-100, 100, 10)

# Data to plot.
x, y = np.meshgrid(np.arange(10), np.arange(10))
z = 50*np.sin(0.5 * x) * np.cos(0.52 * y)

plt.figure(1)
CS = plt.contourf(x, y, z, levels)
CB = plt.colorbar(CS)

plt.figure(2)
CS = plt.contour(x, y, z, levels)
CB = plt.colorbar(CS)

plt.show()
```

**Comment by timhoffm** [comment]
Note: If you want to have levels in the range -100:100, you have to to use either `levels = np.arange(-100, 110, 10)` or `levels = np.linspace(-100, 100, 21)`.

I can reproduce the issue. `QuadContourSet` handles levels for the filled and the line contour case differently, as can seen from `CS.levels`. It's the full range for filled (contourf), but only the range for the plotted lines for contour.

Not sure which behavior is intended, but they should be the same.
