### ISSUE TITLE
legend in wrong place with wrong labels

### ISSUE THREAD

**Issue by akkana** [matplotlib/matplotlib#10576]
### Bug report

The sample code below has two subplots. For the ax1 subplot, the legend is drawn in the wrong place -- upper right when the code specifies upper left -- and the labels are "u", "p" and "p" instead of the labels provided.

I'm using the python-matplotlib and python-matplotlib3 packages on Debian testing (version 2.1.1-2 in both cases), not matplotlib from git; I hope it's okay to report a bug on that version. I asked on (hash)matplotlib on freenode and someone there saw the same thing I'm seeing and suggested that I report it.

I'll try attaching a screenshot of the output after submitting the bug; when I try that now, I get "something went really wrong and we can't process that file" and the submit button greys out.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib import gridspec
import numpy as np

def plot_planet():
    jd = np.array([0.0, 0.915438, 1.830875, 2.746313, 3.661751, 4.577189, 5.492626, 6.408064, 7.323502, 8.238939, 9.154377])
    tra = np.array([18.754013, 18.821358, 18.888625, 18.955808, 19.022901, 19.089897, 19.15679, 19.223575, 19.290245, 19.356796, 19.423221])
    tde = np.array([-23.029638, -22.953653, -22.871279, -22.782548, -22.687498, -22.586167, -22.478597, -22.364832, -22.244918, -22.118904, -21.986842])
    ura = np.array([18.7608, 18.825919, 18.890963, 18.955928, 19.020808, 19.085599, 19.150295, 19.214892, 19.279385, 19.343769, 19.40804])
    ude = np.array([-23.022275, -22.948273, -22.868299, -22.782384, -22.690559, -22.592859, -22.489321, -22.379982, -22.264883, -22.144067, -22.017578])
    mra = np.array([18.699487, 18.759638, 18.819789, 18.87994, 18.940091, 19.000242, 19.060393, 19.120544, 19.180694, 19.240845, 19.300996])
    mde = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
    obliq_ra = [-3.67878, -3.97686, -4.27044, -4.55928, -4.84302, -5.12142, -5.39412, -5.66088, -5.92146, -6.17544, -6.42264]
    eccen_ra = [ 0.40722, 0.27366, 0.14028, 0.0072, -0.12558, -0.25788, -0.3897, -0.52098, -0.6516, -0.78162, -0.91086]
    true_ra = [-3.27156, -3.7032, -4.13016, -4.55208, -4.9686, -5.3793, -5.78382, -6.18186, -6.57306, -6.95706, -7.3335 ]

    fig = plt.figure(figsize=(12, 8))   # width, height in inches

    gs = gridspec.GridSpec(1, 2, width_ratios=[2.5, 1])

    # Plot equations of time:
    ax1 = fig.add_subplot(gs[0])
    ax1.plot(obliq_ra, label="obliquity",    color="lightblue")
    ax1.plot(eccen_ra, label="eccentricity", color="pink")
    ax1.plot(true_ra,  label="Eqn of Time",  color="black")
    ax1.set_title("Equation of Time")
    ax1.legend("upper left")

    # Plot the analemma:
    ax2 = fig.add_subplot(gs[-1])
    ax2.plot(obliq_ra, tde, label="obliquity", color="lightblue")
    ax2.plot(eccen_ra, tde, label="eccentricity", color="pink")
    ax2.plot(true_ra,  tde, label="analemma", color="black")
    ax2.set_title("Analemma")
    ax2.legend(loc="upper right")

    plt.show()

if __name__ == '__main__':
    plot_planet()
```

**Matplotlib version**

  * Operating system: Debian testing, Debian stable
  * Matplotlib version: tried 2.1.1-2 and 2.0.0+dfsg1-2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: Tried with 2.7.13, 2.7.14+, 3.5.3 and 3.6.4
  * Jupyter version (if applicable):
  * Other libraries: numpy

All libraries are from apt-get.

**Comment by akkana** [comment]
Nope, no luck attaching the screenshot -- it's still saying "something went really wrong".
I've uploaded it at http://shallowsky.com/tmp/mpl-legend.jpg

**Comment by afvincent** [comment]
What is the result with
```
ax1.legend(loc="upper left")
```
?

**Comment by afvincent** [comment]
Closing as the suggestion made above solved the problem :) (as reported on the mailing-list by @akkana).
