### ISSUE TITLE
Creating colorbar for manual axes broken

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#10582]
This only occurs with 2.2rc1 (and the current tip of that branch). The following code:

```python
import matplotlib.pyplot as plt
import numpy as np

gx = np.linspace(-5, 5, 10)
img = np.hypot(gx, gx[:, None])

fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
mesh = ax.pcolormesh(gx, gx, img)
plt.colorbar(mesh)

plt.show()
```

produces:

```pytb
Traceback (most recent call last):
  File "test-error.py", line 10, in <module>
    plt.colorbar(mesh)
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/pyplot.py", line 2225, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/figure.py", line 2062, in colorbar
    cax, kw = cbar.make_axes(ax, **kw)
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/colorbar.py", line 1135, in make_axes
    gs = parents[0].get_subplotspec().get_gridspec()
AttributeError: 'Axes' object has no attribute 'get_subplotspec'
```

The line in question:
https://github.com/matplotlib/matplotlib/blob/9b48fd82a6e66df6fce9c99e56e9e75def5afe9a/lib/matplotlib/colorbar.py#L1134-L1136

Seems to have crept in with the constrained layout manager--I'm not sure what the proper fix is.

**Comment by dopplershift** [comment]
I should note that I originally discovered this because it broke a CartoPy plot of mine, so any fix needs to be cognizant of that.

**Comment by jklymak** [comment]
Cool should be an easy fix - just need a check for the gridlock first.    I’ll try to fix tomorrow.  Sorry about that.

**Comment by dopplershift** [comment]
No worries, we hit it on an allowed fail Travis build. Just wanted to make sure we didn't release with it.
