### ISSUE TITLE
I have problems with display Arabic words in the plots, the words became backward, how can I solve it

### ISSUE THREAD

**Issue by baabsa** [matplotlib/matplotlib#10583]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
Essentially the same issue as https://github.com/matplotlib/matplotlib/issues/8765.
Closing as duplicate, not because it is not important (it is), but the solution will essentially be the same as for the previous issue.
