### ISSUE TITLE
Figures plotting in local display

### ISSUE THREAD

**Issue by nadnerbity** [matplotlib/matplotlib#10580]
### Bug report

When I ssh -Y into a machine (Computer A) running OS X 10.11 figures are appearing on the display of Computer A, not on my machine (Computer B).  I have tried multiple backends: QT4, QT5, Tk, Macosx.  If I do not have a VNC connection to Computer A I am told that I cannot access the display (see  below).

I can ssh to a red hat box (Computer C) and matplotlib opens figures on my machine (Computer B).  Matplotlib functions fine on Computer B (no ssh).  I don't think the problem is Computer B.  I am suspicious that the topic discussed in the [Stack Exchange Q](https://apple.stackexchange.com/questions/23382/how-do-i-run-a-gui-app-via-ssh) is relevant: OS X doesn't support what I want to do.

Is it possible to have figures from Computer A display on Computer B, if Computer A runs OS X?

**Code for reproduction**

```python
>>> import matplotlib
>>> matplotlib.use('tkagg')
>>> import matplotlib.pyplot as plt
>>> plt.figure(1)
```

**Actual outcome**

```
Feb 23 16:53:47  python[75277] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Feb 23 16:53:47  python[75277] <Error>: This user is not allowed access to the window system right now.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:47  python[75277] <Warning>: Invalid Connection ID 0
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:47  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<matplotlib.figure.Figure object at 0x1048bc1d0>
>>> Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
2018-02-23 16:53:48.009 Python[75277:6361567] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2018-02-23 16:53:48.009 Python[75277:6361567] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2018-02-23 16:53:48.009 Python[75277:6361567] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2018-02-23 16:53:48.010 Python[75277:6361567] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:53:48  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:54:03  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:54:03  python[75277] <Warning>: Invalid Connection ID 0
Feb 23 16:54:03  python[75277] <Error>: CGSCopySpaces: No connection with id 0x       0
Feb 23 16:54:03  python[75277] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Feb 23 16:54:03  python[75277] <Warning>: Invalid Connection ID 0
Feb 23 16:54:03  python[75277] <Error>: CGSCopySpaces: No connection with id 0x       0
```

**Expected outcome**
A figure on Computer B.

**Matplotlib version**

  * Operating system: OS X 10.11.??
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
  * Jupyter version (if applicable): I dunno, I don't use it.
  * Other libraries: 

This appears to be the system version of python.  I did try using macports and homebrew installations and had the same problem.

**Comment by jklymak** [comment]
This is a better question for stackexchange or mailing list.  I’ll close but feel free to reopen if you think this is a matpltolib bug.

**Comment by nadnerbity** [comment]
I suppose it isn't a matplotlib problem because if I try to open a PyQt4 window I get the same error:
```
from PyQt4 import QtGui
app = QtGui.QApplication(sys.argv)
Feb 23 17:19:26  python[75997] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Feb 23 17:19:26  python[75997] <Error>: This user is not allowed access to the window system right now.
```

**Comment by nadnerbity** [comment]
In case someone finds this closed issue, I solved my problem.  [I posted the answer to stackoverflow.](https://stackoverflow.com/questions/48937709/plotting-figures-using-matplotlib-over-ssh-using-x11-and-os-x/48966209#48966209)
