### ISSUE TITLE
Random image failures with test_curvelinear4

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#10602]
We are getting frequent but inconsistent failures on Travis:
```
FAIL lib/mpl_toolkits/tests/test_axisartist_floating_axes.py::test_curvelinear4[png]
```
e.g., https://travis-ci.org/matplotlib/matplotlib/jobs/346056502

**Comment by QuLogic** [comment]
Also seems to affect AppVeyor, e.g., #10426 [failed](https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.6750) but then [worked on rebuild](https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.6753).

**Comment by efiring** [comment]
The Travis output indicates that we should be able to download the result images as a tarball, but I haven't been able to access the given URL.  Is there some trick to it?

**Comment by efiring** [comment]
In 2 examples, one from Travis and the other from Appveyor, the mismatch is 0.011, but the tolerance is 0.01.  My guess is that there has always been something slightly non-deterministic in this test, and whatever it is, it has simply gotten slightly worse.  In the spirit of triage, I think we should just bump the tolerance to 0.02 and move on.  Tracking down the root cause is probably not the best use of anyone's time right now.

**Comment by QuLogic** [comment]
Yes, when I transferred those examples from the source files into real tests, they were always a bit flaky, and I was always hopeful that things like #10403 will help with it (e.g., I've just noticed that `set_axes_locator` in the toolkit version does not set `Axes.stale`.)
