### ISSUE TITLE
issue with matplotlib.add_subplot documentation

### ISSUE THREAD

**Issue by mjschurman** [matplotlib/matplotlib#10611]
I believe there is an error (or at least confusing wording) in the **documentation** for the 

`matplotlib.figure.Figure.add_subplot` method

found here:
https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html

under the *args description it states:

`Either a 3-digit integer or three separate integers describing the position of the subplot. If the three integers are I, J, and K, the subplot is the Ith plot on a grid with J rows and K columns.`

I believe that a more clear description would read something like:

`Either a 3-digit integer or three separate integers describing the position of the subplot. If the three integers are J, K, and I the subplot is the Ith plot on a grid with J rows and K columns.`

**Comment by jklymak** [comment]
Thanks!  This has been fixed recently: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure 
I'll close, but comment if you still finde the new version confusing and I'll happily re-open.
