### ISSUE TITLE
I have already installed matplotlib function using the command : sudo apt-get install python3-matplotlib.

### ISSUE THREAD

**Issue by saruz** [matplotlib/matplotlib#10637]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by saruz** [comment]
But matplotlib.pylab  importing shows error!!! what to do?

**Comment by jklymak** [comment]
Best to take this to the mailing list or stack exchange.

**Comment by saruz** [comment]
would you help with the python code to visualise a 5 dof arm simulation in
python along with a pid controller?

**Comment by timhoffm** [comment]
No, this place is for discussing the development of matplotlib, not for user support. As suggested above, please use the mailinglist or stackexchange.
