### ISSUE TITLE
Adding NCL colortables to default matplotlib colormaps

### ISSUE THREAD

**Issue by serazing** [matplotlib/matplotlib#10630]
I really like [NCL colortables](https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml) which provides nice data visualization on maps. I have all the tables stored in a JSON file, easily convertible into a python dictionary and matplotlib

I was thinking to add them to the matplotlib default colormaps. Let me know if it would be possible to do so and I could send a pull request to add these colormaps.

**Comment by story645** [comment]
Some of those are already in the default maps and a bunch of others are in [cmocean](https://github.com/matplotlib/cmocean), so would you be open to providing them as a standalone library similar to cmocean?

**Comment by serazing** [comment]
Okay, that is a good alternative. I have created a standalone library similar to cmocean. You can see the library [here](https://github.com/serazing/cmclimate). I still need to write a documentation to describe all the colorbars available and how to use them.
The library use is actually similar to `cmocean`:
```
import cmclimate
cmclimate.cm.colorbar_name
```

**Comment by story645** [comment]
Awesome!

**Comment by tacaswell** [comment]
I'm going to close this as I think the best path forward is to do as @story645 suggests and I trust @serazing to remember to do that when their docs are ready :smile: .

Thanks for your work on this @serazing !
