### ISSUE TITLE
autoscaling only one side of an axis

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10644]
Currently, an axis can be either autoscaled or not.  There is no way to autoscale just one side of it.

Example case that caused some head scratching:

```
from matplotlib import pyplot as plt

fig, axs = plt.subplots(1, 2, sharey=True)
data = [[0, 1], [0, 2]]

for ax, row in zip(axs, data):
    ax.plot(row)
    ax.set(ylim=(0, None))
    # Actually setting a bunch of things, `ax.set(ylim=..., title=..., etc.)`

plt.show()
```

Note that the call to ylim completely disables y-autoscaling on all shared axes (because Matplotlib now thinks that there is a user-specified ylimits on the axes), so the call to plot() on the second axes does not trigger autoscaling at all.

(Yes, in this case the call to set_ylim can be moved to after the loop as a workaround.)

Not sure if it's worth making it possible to autoscale just one of the two sides, whether the autoscale_view should check whether the previous call to set_ylim had a None on one of the two sides, etc.

**Comment by jklymak** [comment]
Well, I didn't knw you could set ylim to 0, None, so learned something new.
```python

from matplotlib import pyplot as plt

fig, ax = plt.subplots()
data = [[0, 1], [0, 2]]

for row in data:
    ax.plot(row)
    ax.set(ylim=(0, None))
```
does exactly the same thing in just one axis. I think once you `ax.set_ylim` you are done w/ autoscaling (at least for the y axis) and further plot calls won't autoscale.  Anything else seems hard to handle.

**Comment by anntzer** [comment]
> I think once you ax.set_ylim you are done w/ autoscaling (at least for the y axis)

The hope is that that would mark autoscale being off only for one of the two sides.  Not saying it's easy...

**Comment by jklymak** [comment]
But you are sharing the y-axis, so once you turn the scaling off for one axis, you've turned it off for the other.  Its like they share the same axes (see my example above).

**Comment by anntzer** [comment]
I just want to turn off autoscaling *for the lower bound only* of all (shared) y axes.

**Comment by jklymak** [comment]
I guess you could do that.  Depends on if you think `None` means keep autoscaling the upper bound, or to use the max of the data when `set_ylim` is called.  The latter is whats done (sharing or not), and it doesn't strike me as worse than the former (and is considerably easier to code).

**Comment by anntzer** [comment]
None (clearly?) means 'keep that bound what it was, regardless of whether it was set from autoscaling or explicitly' (...IMO...).

**Comment by jklymak** [comment]
OK, fair enough.  But "what it was" in your case was 1.0 for axs[0].  You want to to be autoscale_ymax or some other flag.  Again, I agree you could do that, but I'm not sure what the real advantage is.

**Comment by jklymak** [comment]
Flip your example.  What will the ylims be then if change the behaviour as you suggest?

**Comment by anntzer** [comment]
Basically yes, I want separate autoscale_ymin and autoscale_ymax.
In the example I gave, ymin would be 0... what else?

**Comment by jklymak** [comment]
OK, I guess thats fair.  

```
ax.set_ylim(bottom=0)
```
also turns off autoscaling.

**Comment by jklymak** [comment]
Does 
```
ax.set_ylim((0, None), auto=True)
```
not do what you want?

**Comment by anntzer** [comment]
aha...
*technically* not really because the next call to plot will also change the bottom ylim, but in practice yes that's what I want :-)
