### ISSUE TITLE
Most warnings calls do not set the stacklevel

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10643]
### Bug report

**Bug summary**

Calls to `warnings.warn` should usually set `stacklevel=2` (or higher) so that the source line that gets displayed in the warnings message is the line triggering the code, not the line in mpl that has the warnings call (which is basically redundant with the warnings message itself).  Right now most of the calls do not include the stacklevel argument.

**Comment by tacaswell** [comment]
I am :+1: on adding `stacklevel` to all of our warnings

**Comment by ImportanceOfBeingErnest** [comment]
Interesting. Can the documentation state this as a general advise then? E.g. in [logging-level](https://matplotlib.org/devel/contributing.html#which-logging-level-to-use) or where else would that fit?

**Comment by tacaswell** [comment]
re-opening an the issue that closed this only addressed a few warnings.

**Comment by cldssty** [comment]
I'd like to try to find and address more warnings if that's okay?

**Comment by anntzer** [comment]
go for it!

**Comment by cldssty** [comment]
Have found some more calls and set stacklevels to 2. There are more though.

**Comment by hershen** [comment]
This is fixed in #12006. Can this be closed?

**Comment by jklymak** [comment]
Thanks a lot @hershen!

**Comment by hershen** [comment]
You're welcome!
