### ISSUE TITLE
matplotlib with joblib with requests hangs

### ISSUE THREAD

**Issue by alyaxey** [matplotlib/matplotlib#10647]
### Bug report
**Bug summary**
When running simple code which uses matplotlib with joblib with requests the program hangs forever on macOS.

**Code for reproduction**

```python
import requests
from joblib import Parallel, delayed
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot

Parallel(2, verbose=100)([delayed(requests.get)('http://google.com')])
```

**Actual outcome**

The program hangs with no output.

**Expected outcome**

The program finishes work in about a second.

**Matplotlib version**

  * Operating system: macOS high sierra
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: anaconda 3.6
  * Other libraries: joblib==0.11, requests==2.18.4

**Comment by jenshnielsen** [comment]
Are you using a forkserver? as documented in https://pythonhosted.org/joblib/parallel.html#bad-interaction-of-multiprocessing-and-third-party-libraries

**Comment by jenshnielsen** [comment]
The following works for me if I set it to use forkserver with `export JOBLIB_START_METHOD='forkserver'`

```
import requests
from joblib import Parallel, delayed
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot


if __name__ == '__main__':
    Parallel(2, verbose=100)([delayed(requests.get)('http://google.com')])
```

**Comment by alyaxey** [comment]
Thanks! Now it works. I didn't know about such an option. It turns out that if we replace import matplotlib with NLTK the bug will also be present.

**Comment by jenshnielsen** [comment]
Great it works. Its most likely caused by matplotlib importing numpy which I guess NLTK does too
