### ISSUE TITLE
constrainedlayout is very slow for large number of subplots

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10655]
Not sure anything can be done about this, but just leaving a note in case @jklymak (or someone else) in interested in working on the performance: with figure.constrained_layout.use set (mpl2.2.0rc1), on my machine,
- subplots(4, 4) takes 4s,
- subplots(5, 5) takes 28s,
- subplots(6, 6) takes 48s.

**Comment by jklymak** [comment]
Yeah, I get 4, 12 and 30 s for the same thing.

Cheap, fast, or good: choose two!

Seriously, the slow down is in `_constrained_layout.do_constrained_layout`.  It does a NlogN loop on the axes (i.e. all possible pairs are compared), and I'm not sure how I can get away from that.   Its *not* in the constraint solver, it is in my code, so I'll try and think how it could go faster.

**Comment by jklymak** [comment]
Ok, down to 1.8, 3.3s, 6.3s.  Thanks for pointing out this is so pokey...

**Comment by jklymak** [comment]
Closed by #10658
