### ISSUE TITLE
Creating a 6 DoF plot of a quadcopter. 

### ISSUE THREAD

**Issue by aldrinchua8** [matplotlib/matplotlib#10673]
Good Day, 
I am currently using the matplotlib to plot the movement of the quadcopter. The available data that i get are the x, y, z and the rotational angles roll, pitch and yaw. I am able to plot the position of the quadcopter since it only need the x, y, z coordinates but I am having a hard time plotting the angles of the quad. Please Help. The desired outcome is similar to the picture shown. 

![sample](https://user-images.githubusercontent.com/32363552/36945312-f8048b3c-1fe6-11e8-950c-0cd77a6cafa6.PNG)

**Comment by timhoffm** [comment]
GitHub issues are for bug reports and discussing the development of matplotlib, not for user support.

Please use the mailing list or stackoverflow for your question.
