### ISSUE TITLE
Add documentation for set_rlim

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#10704]
The polar axes method `set_rlim` currently has no documentation, and a unhelpful `*args, **kwargs` signature. It would be good to add some documentation, and if possible make the signature a bit more clear. (xref #10654)

**Comment by AdamsonMA** [comment]
Is this issue still open? If so, I am interested in fixing the issue to get more involved with the project.

**Comment by jklymak** [comment]
@AdamsonMA  That'd be great!

**Comment by AdamsonMA** [comment]
I'll have the documentation for the set_rlim and other methods in the polar graph done tomorrow.  However, I saw that the set_rlim function only has the ability to call two other methods within the class, and does not make any computations itself. Perhaps the method could allow the possibility of calling all of the setter methods, just be deleted for redundancy, or left in the code?
