### ISSUE TITLE
Doc issue: ConnectorPatch -> ConnectionPatch

### ISSUE THREAD

**Issue by tloredo** [matplotlib/matplotlib#10727]
On the tutorials page for annotations:

https://matplotlib.org/tutorials/text/annotations.html?highlight=connectionpatch

the entry for ConnectionPatch is mistitled **Connector**Patch, and **Connector**Patch is used in the text 3 times, and in the TOC (but not the example).  Looks like the fix should be made here:

https://github.com/matplotlib/matplotlib/blob/master/tutorials/text/annotations.py

The same problem exists here:

https://matplotlib.org/users/annotations_guide.html#using-connectorpatch

But I can't find where this is in the current code base; from the page's header, it may be out-of-date.

**Comment by afvincent** [comment]
Good catch :)!

FWIW, the last link refers to a very old version of Matplotlib indeed. My guess is that it got merged with the new version of the tutorial during the documentation overhaul that took place with the release of Matplotlib 2.0.

**Comment by Xavier-J-Ortiz** [comment]
@afvincent Hi! I'd like to take this if it's still available!

This would be my first contrib to the project and am excited to help out a library that I've used in the past!

It's been a while for me in terms of python and I would need to get acclimated to python 3, but I don't think that will be a huge hurdle. 

I'll read up on any documentation that can be helpful on setting up the dev environment, and if I can't get situated or if I see this is too big of a chunk to chew, I'll give a shout on here!

Thanks!

**Comment by QuLogic** [comment]
Fixed by #10731.
