### ISSUE TITLE
inverse transform break chaining

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10741]
### Bug report

**Bug summary**

Transform chaining seems to not be possible in some cases. As an example 
```
tr = ax.transAxes - ax.transData + ax.transData
```
gives a different result than
```
tr = ax.transAxes 
```
although those are linear transformations, which can easily be inverted, so one would expect
```
A + B^-1 + B == A
```
The following example shows that this is not the case.

**Code for reproduction**

The code should create a red and a green line from [0,0] to [1,1] in axes cooridinates. Yet the red line is somehow fixed to its initial prosition and forgets about its transform.

```
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

# apply transform A + B^-1 + B 
# this should equal A
tr = ax.transAxes - ax.transData
trinv = ax.transData
line = plt.Line2D([0,1],[0,1],transform=tr+trinv, color="crimson")
ax.add_line(line)

# apply transform A
line2 = plt.Line2D([0,1],[0,1],transform=ax.transAxes, color="limegreen")
ax.add_line(line2)

ax.set_ylim(.1,1.1)

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/23121882/37214723-270b2396-23b6-11e8-8ee2-4e174c0077b5.png)

**Expected outcome**

A plot with red and green line overlapping.

Now it may well be that I'm completely misunderstanding the transform chaining in which case it would probably be good to update the documentation.

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version:  2.2
  * Matplotlib backend: Qt4Agg as well as TkAgg
  * Python version: 2.7.10

**Comment by ImportanceOfBeingErnest** [comment]
Also the comments in the source suggest that the above chaining should be possible. 

https://github.com/matplotlib/matplotlib/blob/c85b029954e92daf943e54b596d0d7197ea44c67/lib/matplotlib/transforms.py#L1381-L1394

**Comment by ImportanceOfBeingErnest** [comment]
I think I solved this issue as far as to get the correct transform chain, such that the above example works. So let
```
A := ax.transAxes
B := ax.transData
```
We want to perform 

```
tr = A + B^-1 
trinv = B
transform = tr + trinv
```

This does not work as expected, as seen above. If we now define
```
C := ax.transScale
D := ax.transLimits
```

we can replace B according to 
https://github.com/matplotlib/matplotlib/blob/4391fe9184b50ba178e80bf356d9d478494cf1ef/lib/matplotlib/axes/_base.py#L668

```
B = C + (D + A)
```

Hence

```
A = (A + B^-1) + B
  = (A + (C + (D + A))^-1) + B
  = (A + (D + A)^-1 + C^-1) + B
  = A + (A^-1 + D^-1 + C^-1) + B
  = (D^-1 + C^-1) + B
```
  
So we might expect that 

```
tr = ax.transLimits.inverted() + ax.transScale.inverted()
```

would work. But it still doesn't. 

However, since

https://github.com/matplotlib/matplotlib/blob/4391fe9184b50ba178e80bf356d9d478494cf1ef/lib/matplotlib/axes/_base.py#L662-L663

we might use 

```
ax.transLimits.inverted() == mtransforms.BboxTransformTo(mtransforms.TransformedBbox(ax.viewLim, ax.transScale))
```

This suddenly works,

```
tr =  mtransforms.BboxTransformTo(
        mtransforms.TransformedBbox(ax.viewLim, ax.transScale))  + \
      ax.transScale.inverted()
trinv = ax.transData 
line = plt.Line2D([0,1],[0,1],transform=tr+trinv, color="crimson")
ax.add_line(line)
```

produces

![image](https://user-images.githubusercontent.com/23121882/37258102-c880042c-2572-11e8-8ced-32a3ba6e7fec.png)

Note however that 

```
tr =  mtransforms.BboxTransformTo(
        mtransforms.TransformedBbox(ax.viewLim, ax.transScale))  - ax.transScale
```

does not work. Seemingly `D^-1 + C^-1` is not actually the same as `D^-1 - C`. 

So in total, the actual problem in terms of code is solved, but I'm left with the mysteries:

1. Why is `A + B^-1` not giving the same result as `D^-1 + C^-1`?
2. Why is `mtransforms.BboxTransformFrom().inverted()` not giving the same result as `mtransforms.BboxTransformTo()`
3.  Why is `D^-1 + C^-1` is not actually the same as `D^-1 - C` (i.e. why is substraction not the same as inversion?)

So apparently all of this is not actually a problem in the real world, since matplotlib works fine as we all know. Still it's somehow strange that some of the transform features are not working as expected. 

Note that if you think this is not an issue at all, feel free to close this; but it would be great if someone could shed some light on this. In this case I would also volunteer to update the Transformation tutorial, since there apparently some loopholes to be closed therein.

**Comment by QuLogic** [comment]
The problem (originally, I did not look at the other cases) is that `.inverted` copies the matrix; hence it is not linked with the original transform. So when you change the limits, the forward transform changes, but the inverse does not. If you call `ax._set_ylim` before adding the lines, then the two overlap. (But if you zoom in or out they don't.)

**Comment by ImportanceOfBeingErnest** [comment]
Yep, that'll be it. The solution from above only works because `ax.transScale.inverted() == ax.transScale == Identity` in this case. 

So let's make this a wishlist proposal to either make the inverted transforms aware of changes or to at least provide updated inverted transforms for the usual cases like `ax.transAxesInverted` or `ax.transDataInverted` such that transforming back and forth between the different systems is easily possible. 

(I'm aware that this would involve a lot of work, especially distinguishing the cases for which no general inverse exists, so no pressure here. ;-))

**Comment by tacaswell** [comment]
I'm going to re-open this at it is a funny edge case in our transform stack (apparently one we do not use internally).
