### ISSUE TITLE
WebAgg losing image/axes after 'save' in Chrome

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#10764]
### Bug report

**WebAgg 'save' disrupts plotting for Chrome**

After pressing `save` button, plot is gone.  When I zoom, a plot re-appears, but axis lines are gone (well, one can see 'trace' but they seem just one pixel outside the clip area).

**Code for reproduction**

```python
from matplotlib.pylab import *
plot([0,1])
show()
```
press `save` button

**Actual outcome**

(see above)

When I use the resize function of the plot in the interface, the full plot and axes re-appear.

I just tested this on Firefox, which does not seem to have that same problem.

**Expected outcome**

The `save` button should not kill the plot.

But maybe it is only related to current Chrome version.

**Matplotlib version**

  * Operating system: Fedora 17 (64 bit)
  * Matplotlib version: 2.2.0
  * Matplotlib backend: WebAgg
  * Python version: 3.6.4
  * IPython version: 6.2.1
  * Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
  * Firefox 58.0.2 (64-bit)
  * Other libraries: 

python built from source, packages from pip3 (current).

**Comment by QuLogic** [comment]
This seems fine in the current version; please comment/re-open if still reproducible.
