### ISSUE TITLE
ENH: Possibility to decide tick and label position in mplot3d

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#10767]
*Originally discussed on [Gitter](https://gitter.im/matplotlib/matplotlib?at=5aa724e953c1dbb743d55209) with @WeatherGod .*

Currently, there is no easy (i.e. public built-in) way to set the position of the ticks and labels of an axis in mplot3d, while  with 2d plots, one can for example achieve this with:
```python
ax.xaxis.set_ticks_position("top")
ax.xaxis.set_label_position("top")
```

It would be nice to be able to have a similar feature for mplot3d. The current situation is that the label of an axis is placed through a heuristic that selects a reasonable axis based on the orientation of the plot. One will call that behavior "auto" in what follows. The proposal is to introduce a possibility for fixed placement of ticks and labels. A naming scheme that could work (at least in my genuine view) is:
  - x-axis: {"auto", "front", "back", "both"};
  - y-axis: {"auto", "front", "back", "both"};
  - z-axis: {"auto", "left", "right", "both"}.

As far as I can tell, this seems quite robust to any rotation that I could achieve when playing with a 3d plot. Defaulting to "auto" would preserve the current behavior, while introducing the other names could address the need expressed by some users to change it, for example in this [SO thread](https://stackoverflow.com/questions/15042129/changing-position-of-vertical-z-axis-of-3d-plot-matplotlib) (or even recently on the mailing-list) where the OP gets the behavior that they wants by accessing and setting a private attribute:
```python
# [yada yada yada]

tmp_planes = zaxis._PLANES

if 'left' in self.sides_to_draw :
    # draw zaxis on the left side
    zaxis._PLANES = (tmp_planes[2], tmp_planes[3],
                     tmp_planes[0], tmp_planes[1],
                     tmp_planes[4], tmp_planes[5])
elif 'right' in self.sides_to_draw :
    # draw zaxis on the right side
    zaxis._PLANES = (tmp_planes[3], tmp_planes[2], 
                     tmp_planes[1], tmp_planes[0], 
                     tmp_planes[4], tmp_planes[5])

# [yada yada yada]
```

**Edit:** adapted a code snippet from the SO thread to avoid relying on an external URL too much

**Comment by QuLogic** [comment]
This might be something that @scottshambaugh might have thoughts on.

**Comment by scottshambaugh** [comment]
I like this as a feature, and think it's still relevant. I'd rather not have different front/back vs left/right vs top/bottom naming conventions for each axis, but `'upper', 'lower', 'auto', 'both', 'none'` as a set of options would be great. I *think* this would not be too hard to implement.
