### ISSUE TITLE
subplots with qt5agg backend flashes frame on windows desktop

### ISSUE THREAD

**Issue by usproptrader** [matplotlib/matplotlib#10770]
The code works fine as it saves the final chart correctly.
The only problem seems around subplots that the initial 
frame gets flashed on the desktop.(windows 10)
python 3.5

**Code for reproduction**

```python
        plt.style.use('dark_background')
        plt.switch_backend("qt5agg")
        ax,ff = plt.subplots(1,1,figsize=(3,3))
        candlestick_ohlc(ff,dfin[['dt','open','high','low','close']].values , width=.0004, colorup='g', colordown='r')
        ff.xaxis_date()
        ff.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
        ff.xaxis.label.set_size(10)
        ax.autofmt_xdate()
        loc=ff.xaxis.get_major_locator()
        loc.maxticks[mdates.DAILY] = 2000
        fnt=5
        plt.xticks(fontsize=fnt)
        plt.yticks(fontsize=fnt)
        plt.title(sym,size=fnt+2)
        plt.grid()
        plt.tight_layout()
        plt.savefig(fnc)
        plt.pause(.01)
        plt.close(ax)

```

just needs a noshow option in subplots or remove the flash all together

**Matplotlib version**
version 1.5.3
with qt5agg
python 3.5
pycharm ide

installed with pycharm cant get 2.2.2
version to work with finance and candlestick_ohlc

**Comment by jklymak** [comment]
PyCharm has an issue w/ 2.2.0, but will be fixed soon.  

I don't think we are doing bug fixes for 1.5.3

No idea what `candlestick_ohlc` is.  Please provide a matplotlib-only sefl-contained minimal working example.  

Not sure what the actual error is, but you have `plt.pause(0.1)` followed by `plt.close(ax)`. You've transposed ax and ff in the subplots call, so `plt.close(ax)` closes the figure.  That seems correct to me.  I'm closing because I think this is user error, not an actual matplotlib bug.  Stackexchage and the mailing list are an appropriate place for these issues.

**Comment by usproptrader** [comment]
I have had this on stackoverflow for a while and no one knows.
i will try to get the new 2.2.2 version working and see if the problem exists
if it does then i will post it in the mailing list with example data to show
the problem. thanks

**Comment by jklymak** [comment]
Still not at all clear what the error is.  That the "inital frame gets flashed to the desktop" sounds like appropriate behaviour to me.  Did you want it just saved to disk? If so, don't use the qt5agg backend - use just plain `Agg`.

**Comment by usproptrader** [comment]
![mn1b9](https://user-images.githubusercontent.com/7141475/37359613-766db8fc-26c4-11e8-8a0b-7c93e89459a8.png)
I am generating 10 charts every minute and at the plt.subplots() call this image pops up on the desktop
which interferes with other program displays on the desktop.
 I am also using Tkinter and the standard backend crashes with that.
qt5agg works ok so all i have to do is find out how to stop this
frame from displaying for every chart that is saved.thanks

**Comment by jklymak** [comment]
`qt5Agg` is an interactive backend.  You will get a chart poppong up.  If you don't want a chart popping up, use `Agg`, which is non-interactive.  https://matplotlib.org/faq/usage_faq.html#what-is-a-backend

**Comment by usproptrader** [comment]
That solved the problem
works perfectly now.
 thanks
