### ISSUE TITLE
TkAgg reports bad option 'foobar' for icon with `logging` set to INFO level

### ISSUE THREAD

**Issue by robbmcleod** [matplotlib/matplotlib#10785]
**Bug summary**

TkAgg reports bad option 'foobar' for icon with `logging` set to INFO level.  The code in question is located here:

https://github.com/matplotlib/matplotlib/blob/d420e66c776becfcf489a0181acf5b777da9f9ea/lib/matplotlib/backends/_backend_tk.py

although I do not see where this `foobar` argument is coming from.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import logging 
logging.basicConfig(level=logging.INFO, datefmt='%m-%d %H:%M')
import numpy as np
plt.switch_backend('TkAgg')
plt.figure()
plt.plot( np.arange(24), np.linspace(-np.pi,np.pi,24), '+-')
plt.show(block=True)
```

**Actual outcome**

```
INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: bad option "foobar": must be aspect, attributes, client, colormapwindows, command, deiconify, focusmodel, forget, frame, geometry, grid, group, iconbitmap, iconify, iconmask, iconname, iconphoto, iconposition, iconwindow, manage, maxsize, minsize, overrideredirect, positionfrom, protocol, resizable, sizefrom, stackorder, state, title, transient, or withdraw
```

**Expected outcome**

Nothing.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.3 Anaconda
  * Jupyter version (if applicable): N/A
  * Other libraries: TkInter version 8.6

Installed via `pip install` yesterday.

**Comment by anntzer** [comment]
Already closed by https://github.com/matplotlib/matplotlib/pull/10681.
