### ISSUE TITLE
Make pie charts circular by default

### ISSUE THREAD

**Issue by nicoguaro** [matplotlib/matplotlib#10789]
### Bug report

**Bug summary**

The default configuration for pie charts should give circular pies. That is in the definition according to Wikipedia:

> A pie chart (or a circle chart) is a circular statistical graphic which is divided into slices to illustrate numerical proportion. 

See for example: https://kosara.net/papers/2016/Kosara-EuroVis-2016.pdf

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.pie([10, 90])
plt.show()
```

![pie_ellipse](https://user-images.githubusercontent.com/1097787/37429625-e6631984-279d-11e8-8ff1-e029d6a3229c.png)

**Actual outcome**

**Expected outcome**

The expected outcome is the following

![pie_circle](https://user-images.githubusercontent.com/1097787/37429677-11f21438-279e-11e8-9b7e-0e930fd176dc.png)

This is obtained by the following snippet

````python
import matplotlib.pyplot as plt

plt.pie([10, 90])
plt.axis("image")
plt.show()
````

**Matplotlib version**

  * Operating system: Linux Mint
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.4
  * Distribution: Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19)

**Comment by Imanflow** [comment]
I saw this tagged as a good first issue and I started looking at it. Not only using `plt.axis("image")` works, also with `equal` and ` scaled`. 

I checked the code in `pyplot.py` and `_axes.py` and I fail to see clearly what should be modified in order to make it by default, but with a bit of guidance I would take the issue.

**Comment by ImportanceOfBeingErnest** [comment]
I should think this is as easy as adding 

    self.set_aspect("equal")

in the `pie` method of `Axes` in `_axes.py` (around [line 2792](https://github.com/matplotlib/matplotlib/blob/5e52ce11ab59176a467dd2c68db8c5e1fbc20a24/lib/matplotlib/axes/_axes.py#L2792) of the current master).

But it should probably get a "what's new"-entry.

**Comment by Imanflow** [comment]
the what's new entry could be something like:

Circular pie charts by default
----------------------------------------------

Added equal aspect to the axes in `plt.pie` by default to ensure a circular image. 

What do you think?

**Comment by tacaswell** [comment]
This seems like a very odd oversite, is this a regression from earlier versions of Matplotlib?

**Comment by ImportanceOfBeingErnest** [comment]
@tacaswell I don't think so, the examples in versions [1.3](https://matplotlib.org/1.3.0/examples/pie_and_polar_charts/pie_demo_features.html), [1.4](https://matplotlib.org/1.4.0/examples/pie_and_polar_charts/pie_demo_features.html), [1.5](https://matplotlib.org/1.5.0/examples/pie_and_polar_charts/pie_demo_features.html), [2.0](https://matplotlib.org/2.0.0/examples/pie_and_polar_charts/pie_demo_features.html) all have some line with `plt.axis("equal")` or `ax1.axis('equal')` in them. (Which is of course not a sufficient criterium :see_no_evil:)


As a what's new entry I could imagine the following:

> We acknowledge that the majority of people do not like egg-shaped pies. Therefore, an axes to which a `pie` chart is plotted will be set to have equal aspect ratio by default. This ensures that the pie appears circular independent on the axes size or units. To revert to the previous behaviour you may set the axes' aspect to automatic, `ax.set_aspect("auto")` or `plt.axis("auto")`.

**Comment by Imanflow** [comment]
apparently @jerrylui803 was working on it without commenting here... he opened a pullrequest yesterday.

https://github.com/matplotlib/matplotlib/pull/10887
