### ISSUE TITLE
ImportError, library not loaded for libc++abi.1.dylib

### ISSUE THREAD

**Issue by sjLambda** [matplotlib/matplotlib#10786]
### Bug report

**Bug summary**

ImportError, library not loaded for libc++abi.1.dylib

The above error is on a plain IPython session.

**Code for reproduction**

```python
# Paste your code here
# 
#
import matplotlib.pyplot as plt
```

**Actual outcome**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-a0d2faabd9e9> in <module>()
----> 1 import matplotlib.pyplot as plt

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     29 from cycler import cycler
     30 import matplotlib
---> 31 import matplotlib.colorbar
     32 from matplotlib import style
     33 from matplotlib import _pylab_helpers, interactive

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/artist.py in <module>()
     14 import matplotlib
     15 from . import cbook, docstring, rcParams
---> 16 from .path import Path
     17 from .transforms import (Bbox, IdentityTransform, Transform, TransformedBbox,
     18                          TransformedPatchPath, TransformedPath)

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/path.py in <module>()
     24 import numpy as np
     25 
---> 26 from . import _path, rcParams
     27 from .cbook import _to_unmasked_float_array, simple_linear_interpolation
     28 

ImportError: dlopen(/Users/x/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libc++abi.1.dylib
  Referenced from: /Users/x/anaconda3/envs/tensorflow/lib/libc++.1.dylib
  Reason: image not found

**Expected outcome**
a blank prompt

**Matplotlib version**

  * Operating system: Mac OS, El Capitan, version 10.11.6, Darwin Kernel Version 15.6.0 /RELEASE_X86_64 x86_64
  * Matplotlib version: 2.2.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6.4
  * Other libraries: 

conda update --all

**Comment by jklymak** [comment]
This is an install issue - you probably have a library clash in your environment somewhere.  Follow up w/ conda if you can't sort it out, but I don't think Matplotlib is to blame here.
