### ISSUE TITLE
Add lines.markerfacecoloralt/mfcalt to rcParams

### ISSUE THREAD

**Issue by kalagau** [matplotlib/matplotlib#10790]
### Bug report

**Bug summary**

lines has an option to set markerfacecoloralt/mfcalt but that option isn't available via `rcParams['lines.markerfacecoloralt']`
**Code for reproduction**

```python

import matplotlib as mpl
mpl.rcparams['lines.markerfacecolor']

```

**Actual outcome**

```
 KeyError: 'lines.markerfacecoloralt'

```

**Expected outcome**
The default value of markerfacecoloralt should be returned

**Matplotlib version**

  * Operating system:Ubuntu 17.1
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK3Agg
  * Python version:3.6

**Comment by jklymak** [comment]
I don't think we garauntee that every kwarg will get an rcParam.  I don't even know what `markerfacecoloralt` is supposed to refer to, and the documentation is not much help.  I'd have to be convinced this needs to be in the rcParam list, perhaps by someone better dcoumenting what it does and why.

**Comment by timhoffm** [comment]
There are two-color fill styles:
https://matplotlib.org/gallery/lines_bars_and_markers/marker_fillstyle_reference.html

**Comment by jklymak** [comment]
Cool.  I'd never have gotten there from the docstrings for those params, so labelling as a documentation issue.  Regardless, I don't know that this needs an rcParam.

**Comment by kalagau** [comment]
I was under the impression that adding this would improve consistency.  Since there are already rcparams for mfc.

**Comment by timhoffm** [comment]
Probably not particularly important, but I don't see why we should leave this out. So +0.5 for adding this.

By the way, am I correct that styles are based on rcParams? If so, +1 for adding. This should be configurable in a style.

**Comment by jklymak** [comment]
I guess you could make that argument.  The counter would be that you already have to specify the fillstyle, so specifying the color is hardly onerous.  

However, I'd take the slightly longer rcParam list if the same PR also explains properly what these do in the docstring of the parameters.  Its completely opque unless you look at the example above.

**Comment by QuLogic** [comment]
I'm rather confused about what needs to be documented here, as it doesn't seem to be what the title is referencing.

**Comment by timhoffm** [comment]
This was mislabeled. It's a request to add a new rcParam.
