### ISSUE TITLE
manually backport #10806

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#10814]
Preserve support for all versions of python expected to be released before 2020

**Comment by dstansby** [comment]
Sticking a link here for future reference: #10806

**Comment by QuLogic** [comment]
Fixed by #11333. Note that adding the Fixes magic to the description of a PR not targetting `master` does not close the issue.

**Comment by tacaswell** [comment]
It will close it when that commit is accessible _from_ master.

I am not sure if we want to continue to do the merges up from 2.2.x to mastor or if we want to do it with 'strategy ours' so git has a a merge commit, but we keep none of the changes.

**Comment by QuLogic** [comment]
No, the magic was only in the PR description; it needs to be in the commit message to trigger the on-master closing.
