### ISSUE TITLE
Axis autoscaling ignores margins

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10820]
### Bug report

Autoscaling should produce equal margins on both sides of the plotted data. However it does not do so in certain cases. 

**Code for reproduction**

```
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = 5,3

plt.scatter([.4],[.5])
plt.scatter([.6],[.6])

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/23121882/37559472-3c6fd598-2a27-11e8-83c3-d0b4946f7e8a.png)

**Expected outcome**

We would expect to have the same margin on all sides, e.g. the blue dot should be as far away from the lower left corner than the orange dot from the upper right corner.

![image](https://user-images.githubusercontent.com/23121882/37559479-772f7e04-2a27-11e8-94ef-d8394a30dd1d.png)

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 2.2
  * Matplotlib backend: Qt4Agg, Qt4Cairo, TkAgg, TkCairo
  * Python version: 2.7.10

**Comment by jklymak** [comment]
You say certain cases.  Any hints about what the difference is between what works and what doesn’t?

**Comment by ImportanceOfBeingErnest** [comment]
Not sure. But if you put both points in the same scatter, it works as expected.

**Comment by anntzer** [comment]
Pretty certain this is yet another manifestation of #7413.

**Comment by efiring** [comment]
Yes, it is #7413. I'm going to close this as a duplicate.  (#9979 is another duplicate, and I wouldn't be surprised if there are several more among our open issues.)
