### ISSUE TITLE
Tk error when pressing 'q' key on interactive 'key_press_event' window.

### ISSUE THREAD

**Issue by lkilcher** [matplotlib/matplotlib#10848]
I'm getting a `_tkinter.TclError: this isn't a Tk application` when I press the `'q'` key in an interactive window `key_press_event`. 

**Code for reproduction**

Note that the code below is copied from the [event handling demo](https://matplotlib.org/users/event_handling.html#event-attributes), where I've replaced `'button_press_event'` with `'key_press_event'`, and I've added `event.key` to the print statement.

```python
import matplotlib.pyplot as plt
plt.ion()

class LineBuilder:
    def __init__(self, line):
        self.line = line
        self.xs = list(line.get_xdata())
        self.ys = list(line.get_ydata())
        self.cid = line.figure.canvas.mpl_connect('key_press_event', self)

    def __call__(self, event):
        print('click', event, event.key)
        if event.inaxes!=self.line.axes: return
        self.xs.append(event.xdata)
        self.ys.append(event.ydata)
        self.line.set_data(self.xs, self.ys)
        self.line.figure.canvas.draw()

fig = plt.figure()
ax = fig.add_subplot(111)
ax.set_title('click to build line segments')
line, = ax.plot([0], [0])  # empty line
linebuilder = LineBuilder(line)

plt.show()
```

**Actual outcome**

In this case, with the mouse over the window, I press `' '` three times, then `'r'` once, then `'q'`. The window closes immediately, and the error below is generated.

```
click <matplotlib.backend_bases.KeyEvent object at 0x11e4f5b38>  
click <matplotlib.backend_bases.KeyEvent object at 0x11e4f52e8>  
click <matplotlib.backend_bases.KeyEvent object at 0x118611780>  
click <matplotlib.backend_bases.KeyEvent object at 0x11e4f5cf8> r
click <matplotlib.backend_bases.KeyEvent object at 0x11e5018d0> q
Traceback (most recent call last):
  File "/Users/lkilcher/anaconda3/envs/hot-spots3/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 26, in blit
    dataptr, colormode, bboxptr)
_tkinter.TclError: this isn't a Tk application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lkilcher/anaconda3/envs/hot-spots3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/Users/lkilcher/anaconda3/envs/hot-spots3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/Users/lkilcher/work/mhk/HSM_Team/Hot Spots/analysis/test/test02.py", line 19, in __call__
    self.line.figure.canvas.draw()
  File "/Users/lkilcher/anaconda3/envs/hot-spots3/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 13, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/Users/lkilcher/anaconda3/envs/hot-spots3/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 34, in blit
    dataptr, colormode, bboxptr)
_tkinter.TclError: this isn't a Tk application
```

**Matplotlib version**
  * Operating system: OSX Sierra 10.12.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend: TkAgg (I can't get macosx working)
  * Python version: 3.5.4 (IPython 4.0.0 and 6.2.1 both generate the error)

Installed MPL via conda (default channel), I get this error both inside and outside a venv.

**Comment by ImportanceOfBeingErnest** [comment]
What happens is that when you press `"q"`, the application window closes (as `"q"` is the default key for closing). This happens faster than the callback is handled. Hence when the callback wants to redraw the figure at `self.line.figure.canvas.draw()`, there isn't any canvas to draw anymore. 

What exactly would you like to happen when pressing `"q"`?

**Comment by lkilcher** [comment]
I'd like to know how to override that behavior, so that I can use the `'q'` key in my interactive application (i.e., to do something different than closing). Is this the case for all backends, or just TkAgg? This `'q'` behavior [isn't documented](https://matplotlib.org/users/navigation_toolbar.html), as far as I can tell.

I noticed that #830 requested `'q'` close the window, and that discussion seemed to indicate that `"ctrl + w" / "cmd + w"` would be the standard 'close' keys.

**Comment by ImportanceOfBeingErnest** [comment]
You may find out by printing `print(plt.rcParams["keymap.quit"]`). I think the default does contain `"q"`. In any case you may also overwrite this parameter not to contain `"q"`.

```
plt.rcParams["keymap.quit"] = ["ctrl+w", "cmd+w"]
```

**Comment by lkilcher** [comment]
Excellent, thank you!
