### ISSUE TITLE
Some minor ticker are missing

### ISSUE THREAD

**Issue by sodynamic** [matplotlib/matplotlib#10859]
### Bug report

**Bug summary**

I am using AutoMinorLocator to plot the minor ticker, but some of the minor tickers are not shown in the figure.
**Code for reproduction**

```python
# -*- coding: utf-8 -*-

import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter, AutoMinorLocator)
        
wk_dir = os.path.split(os.path.realpath(__file__))[0]+"\\"

x_data = np.array([12.40396234,12.3122339,11.57786594,10.71503164,8.46129598
,6.21834307,4.02916017,1.92859094,-0.05075462,-1.88340493
,-3.55526797,-5.06412207,-6.43910928,-7.70860496,-8.78513967
,-9.70712813,-10.51293907,-11.24094117,-11.41661924])

y_data = np.array([2.25195418,2.05308704,1.5156142,1.19544585,0.57207549
,-0.08868661,-0.90895525,-1.9344171,-3.17761866,-4.62844935
,-6.26217958,-8.04780366,-9.98873291,-12.10602853,-14.22089749
,-16.33382289,-18.44528725,-20.5557731,-20.64836265])

def main():

    fig = plt.figure(figsize=(12,12))
            
    ax1 = plt.subplot()    
    ax1.plot(x_data,y_data)


    majorLocator = MultipleLocator(5)
    minorLocator = AutoMinorLocator()
    
    ax1.xaxis.set_major_locator(majorLocator)
    ax1.xaxis.set_minor_locator(minorLocator)
    
    ax1.yaxis.set_major_locator(majorLocator)
    ax1.yaxis.set_minor_locator(minorLocator)

    
    ax1.grid(which="major")
    ax1.grid(which="minor",linestyle = ":")
    ax1.margins(0.2)
    ax1.axis('equal')

    #plt.show()
    fig.savefig(wk_dir+"GridMissing.jpg")  


if __name__ == '__main__':
    main()
```

**Expected outcome**

The above code should generate a plot which has full minor tickers on axis x, and there should not miss the grid lines for the relevant minor tickers. From the attached picture, it is clear that the minor tickers and grid lines on the right side of the plot are missing.
![gridmissing](https://user-images.githubusercontent.com/22489383/37728873-62bdc3e8-2d76-11e8-97de-85cfe357d861.jpg)
A similar problem is also reported on the stackoverflow as
[https://stackoverflow.com/questions/24385006/missing-some-minor-gridlines-in-matplotlib-after-deleting-part-of-data-range](url). However, the solution is not good for me.

**Matplotlib version**

  * Operating system:
Windows 7 64-bit SP1
  * Matplotlib version: 
2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
module://ipykernel.pylab.backend_inline
  * Python version:
IPython 6.2.1
  * Other libraries: 
numpy 1.14.2

The matplotlib is installed from conda by default.

**Comment by afvincent** [comment]
IIRC, due to implementation details, each axis locator has to use its **own instance** of a locator:
```python
ax1.xaxis.set_major_locator(MultipleLocator(5))
ax1.xaxis.set_minor_locator(AutoMinorLocator())
   
ax1.yaxis.set_major_locator(MultipleLocator(5))
ax1.yaxis.set_minor_locator(AutoMinorLocator())
```
seems to works fine.

**Comment by afvincent** [comment]
Anyway, if I am correct, that is not the first time that we get this kind of issue ticket ;): I guess that it means that something could be clearer in the documentation about that requirement.

**Comment by sodynamic** [comment]
@afvincent , you are totally right! Thank you!

**Comment by afvincent** [comment]
FWIW, this requirement is mentioned at least in this [tutorial](https://matplotlib.org/gallery/ticks_and_spines/major_minor_demo.html#major-minor-demo):
```
Note, you should not use the same locator between different Axis because the locator stores references to the Axis data and view limits
```
But it may not be very easy to find it.

**Comment by afvincent** [comment]
Maybe one should include a similar statement to the one from the tutorial in the docstrings of `Axes.XAxis.set_major_locator`, _etc_.?

**Comment by sodynamic** [comment]
I think it would be better if the example code set the tickers for both x and y axes. I am sure every one will notice that each axis should have its own locator. Because the code
`majorLocator = MultipleLocator(5)`
does not seem to be an member function operation, it may not be very easy to understand the requirement for the first time.

**Comment by anntzer** [comment]
Or just make the axis of tickers be unrewritable, and error out when one tries to reuse them...

**Comment by afvincent** [comment]
@anntzer Something like
```python
class TickHelper(object):
    axis = None

    def set_axis(self, axis):
        if self.axis is not None:
            self.axis = axis
            return
        raise ValueError("The axis of a ticker instance should not be rewritten.")

    # yada yada yada
```
? Or even something stricter by making `TickHelper.axis` an almost read-only property?

**Comment by anntzer** [comment]
Better to make axis a readonly property (and deprecate set_axis yada yada, actually it's the same philosphy as with Artist.axes), but that's the idea yes.
