### ISSUE TITLE
Problem with subplot / matplotlib.dates interaction

### ISSUE THREAD

**Issue by DamienIrving** [matplotlib/matplotlib#1086]
I've been plotting timeseries data using the matplotlib.dates module and have come across an issue when using it in conjunction with the subplot command.

For figures with greater than one subplot in a particular column, the time (or x) axis ticks and their labels are only printed on the final subplot that is plotted, and are missing on all other subplots in that column (see example code below). The only exception is when the time axis is identical for each plot in the column (you can test this by editing my example code at ###) - then all time axis ticks and their labels are displayed correctly.

Is this a bug in the subplot source code, or am I missing something?

from pylab import *
from matplotlib.dates import YEARLY, DateFormatter, rrulewrapper, RRuleLocator, drange
import datetime
# tick every 5th easter

rule = rrulewrapper(YEARLY, byeaster=1, interval=5)
loc = RRuleLocator(rule)
formatter = DateFormatter('%m/%d/%y')
# data for subplot 1

date1 = datetime.date( 1952, 1, 1 )
date2 = datetime.date( 2004, 4, 12 )
delta = datetime.timedelta(days=100)

dates = drange(date1, date2, delta)
s = rand(len(dates)) # make up some random y values
# plot subplot 1

ax1 = subplot(211)
plot_date(dates, s)
ax1.xaxis.set_major_locator(loc)
ax1.xaxis.set_major_formatter(formatter)
labels = ax1.get_xticklabels()
setp(labels, rotation=30, fontsize=10)
# data for subplot 2

date1 = datetime.date( 2052, 1, 1 )  ###( 1952, 1, 1 )
date2 = datetime.date( 2104, 4, 12 ) ###( 2004, 4, 12 )

dates = drange(date1, date2, delta)
s = rand(len(dates)) # make up some random y values
# plot subplot 2

ax2 = subplot(212)
plot_date(dates, s)
ax2.xaxis.set_major_locator(loc)
ax2.xaxis.set_major_formatter(formatter)
labels = ax2.get_xticklabels()
setp(labels, rotation=30, fontsize=10)

show()

**Comment by seguri** [comment]
@efiring Hi, would you be so kind to explain to me why reindexing a dataframe breaks `grid=True` and the axis formatter?
I'm collecting data from sensors, every minute, but I do not always get data, so I reindex to insert missing minutes. When I do that, the figure breaks.

Without:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2405157/161295988-713d9122-e0ff-45b1-808b-7e8498a5a91e.png">

With
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2405157/161296722-95ba17e1-9f37-40f7-b2e4-d50d178e2452.png">

Code:
```python
now = datetime.utcnow()
min_freq_idx = pd.date_range(min(df.index), now, freq="min")
df = df.reindex(min_freq_idx, fill_value=0)
axs = df.plot(subplots=True, yticks=[0, 1], rot=23, grid=True, figsize=(12,6), legend=False)
for ax in axs:
    ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
    ax.xaxis.set_major_formatter(formatter = mdates.DateFormatter("%m-%d %H"))
```

Thanks!

**Comment by tacaswell** [comment]
@seguri Please open an issues on Pandas.  They maintain a set of locators that are index aware.

**Comment by seguri** [comment]
@tacaswell I will. Could I get rid of Pandas in the meantime and migrate this maybe to pure numpy data, so that I can plot it correctly?

**Comment by tacaswell** [comment]
That should work.
