### ISSUE TITLE
Documentation for new contributors not matching with actual issues labels

### ISSUE THREAD

**Issue by Imanflow** [matplotlib/matplotlib#10880]
In this part of the docs https://matplotlib.org/devel/contributing.html#issues-for-new-contributors refers to the label `new-contributor-friendly`, which has never been used, and `Easy-fix`, which has not been used since 22nd July 2017. 

I think they should be substituted by `good first issue` which seems to be the one fitting the cause and currently in use.

**Comment by mimikaTU** [comment]
could i work on it?

**Comment by jklymak** [comment]
If someone references an issue witha pull request, then please check the PR to see if the PR addresses the issue.  In this case, the PR above closes this Issue...
