### ISSUE TITLE
pyplot: Program halts after gui save of first plot

### ISSUE THREAD

**Issue by kwcooper** [matplotlib/matplotlib#10888]
### Bug report

**Bug summary**
Occasionally, when plotting multiple successive plots, if the GUI button is used to save a plot, the program halts, the second plot is never shown, and all other code does not run. 

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [10, 20, 30, 40, 50]

plt.plot(x,y)
plt.show()

# *save with gui*

plt.plot(y,x)
plt.show()

print('finished')
```

**Actual outcome**

```
# If applicable, paste the console output here
# *Program halts, no output* 
#
```

**Expected outcome**
When closing the first, saved plot, the next will be displayed. 

**Matplotlib version**

  * Operating system: MAC OSX
  * Matplotlib version: '2.0.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.1
  * Jupyter version (if applicable):
  * Other libraries: n/a

pip

**Comment by dstansby** [comment]
Could you try updating your version of Matplotlib to at least `2.2`, and seeing if it is still a problem?

**Comment by kwcooper** [comment]
Yes, it still occurs for me after update

**Comment by tacaswell** [comment]
Can you try with tkagg instead of macosx as the backend?

**Comment by dstansby** [comment]
I'm having trouble reproducing this on the `macosx` backend. Does it happen all the time or just some of the time? And are you saving to a png file or some other format?

**Comment by GazpachoZen** [comment]
FWIW, I might be encountering something similar. I'm not at all sure what the root issue is, but some code that's been working fine for several weeks is now exhibiting this issue.  I will try to carve off a piece of code that can demonstrate it. I am presently using matplotlib==2.2.2 with Python 2.7.14 on a Windows 10 system.

**Comment by ImportanceOfBeingErnest** [comment]
> On a subsequent flow through the exact same lines
@GazpachoZen Can you detail what that means to make it reproducible for others as well? What interpreter are you using? Which steps are needed to get the same result? In the code shown there is nothing that would invoke any plot to be shown.

**Comment by GazpachoZen** [comment]
That's correct... Without even having a plot be shown the system will choke up.  You can add a show() into the mix, but it's not needed to demonstrate the problem.

I'll try to gen up some a full *.py file that demonstrates all this, but for the moment I have to get back to work.  :-(

**Comment by efiring** [comment]
Please reopen when you have the full test file ready.
