### ISSUE TITLE
Matplotlib Crashses and Exits Python on plt.show() Using Qt5Agg Backend

### ISSUE THREAD

**Issue by Auerilas** [matplotlib/matplotlib#10883]
Hi all,
I'm running Linux Mint 18.3, Anaconda Python 3.5.5, and matplotlib 2.2.2. Everything has been running great up until today. I tried to generate some graphs and once I typed plt.show(), Python just.. quit. It's quite similar to [issue 4590](https://github.com/matplotlib/matplotlib/issues/4590).

**Code for reproduction**

```python
In [1]: import matplotlib

In [2]: matplotlib.__version__
Out[2]: '2.2.2'

In [3]: matplotlib.get_backend()
Out[3]: 'Qt5Agg'

In [5]: import sys

In [6]: sys.version
Out[6]: '3.5.5 | packaged by conda-forge | (default, Feb 13 2018, 05:02:37) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]'

In [7]: from matplotlib import pyplot as plt
plt.plot([1,2,3]);
plt.show();

```
Nothing happens, Python just exits. This is a new problem, and I suspect it has something to do with Qt5, because when I switch backends, I can get it to work.

```
import matplotlib
matplotlib.use("TkAgg")
from matplotlib import pyplot as plt

plt.plot([1,2,3]);
plt.show();
```

Everything has been installed via conda-forge. I'm not sure where to go for the error logs to see what's happening. Any advice?

**Comment by ImportanceOfBeingErnest** [comment]
It seems you are running this inside of `IPython`? By "Python just exits" you mean that IPython exists back to terminal without any error?

Would this also occur if run as script or from terminal?

**Comment by Auerilas** [comment]
It did also occur when run from a script and from the Terminal. I don't think IPython was the culprit.

Unfortunately, I never found out what was. I thought I had a system issue, so I did a dist-upgrade, which broke my system. It just stopped booting up. So I wound up wiping the HDD and doing a clean install of Linux Mint 18.3, a new install of Anaconda/Python/matplotlib, etc. and everything is back to normal.
