### ISSUE TITLE
memory error using savefig with ylim to create pdf of box plots

### ISSUE THREAD

**Issue by bu22dee** [matplotlib/matplotlib#10889]
### Bug report

**Bug summary**

This is my first post. I am working with python for 3 weeks and i am completly new to this topic

savefig while using ylim for box plots gives sometimes a memory error. saveing as png or svg, or not using ylim workes fine.

my guess: despite of limiting the plot with ylim savefig just "zoom" in which can create very long distances even they are not part of the plot anymore which just hit some pdf limitations. in this case there is a data point at 1e39. when i use ylim(-2,2) there is a huge distence which is not part of the plot maybe this causes the memory error.

ram was fine the whole time. 

i hope this helps.

code in comments

**Actual outcome**

```
PS D:\Users\user\Documents\s_line_messdaten\vorlage> py .\vorlage.py
1_box_plot: quantity1
2_box_plot: quantity2
Traceback (most recent call last):
  File ".\vorlage.py", line 173, in <module>
    box_plot(data)
  File ".\vorlage.py", line 146, in box_plot
    plt.savefig("./boxplot/"+simplename[quantity]+'.pdf', dpi=2)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backends\backend_pdf.py", line 2592, in print_pd
f
    self.figure.draw(renderer)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_i
mages
    a.draw(renderer)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\axes\_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_i
mages
    a.draw(renderer)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\lines.py", line 840, in draw
    rgbaFace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backends\backend_pdf.py", line 1799, in draw_mar
kers
    path, trans, rgbFace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backend_bases.py", line 328, in draw_markers
    rgbFace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backends\backend_pdf.py", line 1719, in draw_pat
h
    gc.get_sketch_params())
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backends\backend_pdf.py", line 1521, in writePat
h
    sketch=sketch)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\matplotlib\backends\backend_pdf.py", line 1511, in pathOper
ations
    True))]
MemoryError: Memory error
```

**Expected outcome**

 pdf files for all plots

**Matplotlib version**

  * Operating system: Win 7
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6
  * Jupyter version (if applicable): ---
  * Other libraries: numpy (but should not be relevant)

 
i am at work i think it was installed via pip

**Comment by ImportanceOfBeingErnest** [comment]
Can you please provide a minimal runnable example. See http://sscce.org.

**Comment by bu22dee** [comment]
like this? 

try to change datatype to svg or png. without ylim there are no problems, too. it looks like that this problem only shows with very large negative numbers.

```
import matplotlib.pyplot as plt


data = [[2,3,1,2,3,10e50], [2.3, 1, -2, -10e34]]

#without y_lim
def box_plot(data, datatype):
    plt.figure("zoom")
    plt.boxplot(data, labels = ["data1", "data2"], sym="o", meanline=True, notch=False)
    plt.savefig('nofail.'+datatype)
    plt.clf()

box_plot(data, 'pdf')

#with y_lim
def box_plot_ylim(data, ylim, datatype):
    plt.figure("zoom")
    plt.boxplot(data, labels = ["data1", "data2"], sym="o", meanline=True, notch=False)
    plt.ylim(ylim)
    plt.savefig('fail.'+datatype)
    plt.clf()

box_plot_ylim(data, (-5, 5), 'pdf')
```

**Comment by ImportanceOfBeingErnest** [comment]
I can reproduce the memory error with python 2.7, matplotlib 2.2.2, TkAgg as well as Qt4Agg. I can also reproduce with python 3.6, master, Qt5Agg. Both on Windows8.1.

What's funny is that it works fine for the last data value being set to `-1e34` or `-100e34`, yet it fails for `-10e34`.

**Comment by phobson** [comment]
I cannot reproduce this with Python 3.6, MPL v2.2.2 on (Windows subsystem for) Linux

**Comment by phobson** [comment]
I also cannot reproduce this on vanilla Windows with Python 3.6 and MPL v2.1.2 & v2.2.2 on my admittedly pretty high-end work machine.

I can report however that the test case with the zoomed limits does seem to take much longer to render than it should.

**Comment by jklymak** [comment]
I General we don’t garauntee to filter every bad value out of the input.  In this case I can only assume the very large numbers are meant to represent bad data.  Suggest masking your arrays before passing to boxplot or any other Matplotlib function is the right way to specify data as bad otherwise you are bound to hit floating point problems somewhere along the line.

**Comment by ImportanceOfBeingErnest** [comment]
@jklymak `-1e34` is a perfectly valid value. It should by no means being filtered out, since that would change the boxplot statistics. And using such a value should not result in a memory error.

**Comment by phobson** [comment]
on thing to check: inspect the artists that represent the whiskers and see how many points are in that path

**Comment by jklymak** [comment]
@ImportanceOfBeingErnest Yes, `-1e34` is perfectly valid flaoting point number, but you can't do valid floating point arithmetic with it unless the other numbers are very large as well.  

Do this:

```python
a = np.array([1e10], dtype=np.float64)
b = np.array([5.], dtype=np.float64)
c = a-b
d = c-a
print(d)
```
you get `[ -5.]` as the output.

Now do 

```python
a = np.array([1e17], dtype=np.float64)
b = np.array([5.], dtype=np.float64)
c = a-b
d = c-a
print(d)
```

`[ 0.]`

So yes, `-1e34` is a perfectly valid floating point number, but you can't do floating point arithmetic properly unless the other values are on the order of `1e19` and expect to get anything sensible out.  

I don't know thats the problem here, but I do know that mixing `-5` and `-1e34` is asking for trouble, and users shouldn't expect miracles.  We can try to work around such issues, or folks can just be cognizant of how floating point arithmetic works and precondition their data in the way that makes sense for their data set.

**Comment by ImportanceOfBeingErnest** [comment]
I don't quite get the point. Surely any maths on those numbers is accurate within the limits of floating point accuracy. Compared to 1e34 it does not actually matter if some result is +5 or -5. But this issue is not about the wrong mean shown on the plot or similar.

**Comment by jklymak** [comment]
Because the error is only triggered when zooming in to -5 to +5...

**Comment by ImportanceOfBeingErnest** [comment]
Ok, agreed, I mean it's just a memory error from a plot with 2 boxes and 10 lines. Can't be that serious after all.

**Comment by tacaswell** [comment]
This is _super_ weird.  The exception is coming from https://github.com/matplotlib/matplotlib/blob/a9a495e76f457bcf14c860fccd2644bb5f4fb113/src/_path.h#L1184-L1232 but if you drop into the debugger to look at the input there are only 26 vertexes handed to c from python and `percision` looks like it is 6 (hard-coded).

**Comment by bu22dee** [comment]
btw i have got that error after i changed the order of the boxes. maybe the error is dependent on the positon of the very large negative number (while zoomed in).

**Comment by tacaswell** [comment]
I did not dig deep enough, https://github.com/matplotlib/matplotlib/blob/a9a495e76f457bcf14c860fccd2644bb5f4fb113/src/_path.h#L1047-L1182  That whole set of functions can result in 1 being returned which gets turned into a `MemoryError` by https://github.com/matplotlib/matplotlib/blob/a9a495e76f457bcf14c860fccd2644bb5f4fb113/src/_path_wrapper.cpp#L739-L747

**Comment by QuLogic** [comment]
The problem is that `buffersize_int` is not updated when the buffer is realloc'd to match the new `buffersize`, so it's doubled for _every_ extra character over the original buffer size. I'm not sure why we even have `buffersize_int` in the first place.
