### ISSUE TITLE
ENH: clear() method for widgets.RadioButtons

### ISSUE THREAD

**Issue by raamana** [matplotlib/matplotlib#10922]
### Enhancement proposed

Right now, RadioButtons can be created without activating any of the individual buttons, but they can not be cleared once created. It can be achieved in a dirty way, by hacking properties of the associated artists. However, I feel they need to come with a `clear()` method which deactivates previously selected one - it simply has to do two things: update the button colour and set value_selected to None. If this is acceptable, I'll be happy to send in a PR.

**Comment by WeatherGod** [comment]
I think this is a reasonable feature request. Would it make sense to also
add such a convenience feature to the check boxes widget?

**Comment by raamana** [comment]
that's true - I can do that as well.

**Comment by ImportanceOfBeingErnest** [comment]
Checkboxes can at least be all unchecked individually. So there would be no definitive need for such feature as in the case of radio buttons. But since this would probably be equally easy to add, why not.

**Comment by WeatherGod** [comment]
We are sticklers with regards to backwards compatibility. Yes, the name
choice wasn't great. What would be fine is to accept an optional boolean
argument that would be the state to set the checkbox to.

**Comment by ImportanceOfBeingErnest** [comment]
But feel free to update the docstring of the method to make this behaviour more apparent.

**Comment by raamana** [comment]
Hey guys, take a look at #10924

**Comment by QuLogic** [comment]
To take care of this, I've rebased the linked orphaned PR and will do a bit of cleanup as well.
