### ISSUE TITLE
shorten a colorbar by half when the colorbar is created using axes_grid1

### ISSUE THREAD

**Issue by llodds** [matplotlib/matplotlib#10923]
### Bug report

**Bug summary**

I am trying to shorten a colorbar by half. Does anyone know how to do this? Any suggestions? I tried cax.get_position() and then cax.set_position(), but this method did not work.

Besides, it seems that axes created by axes_grid1 has the same bbox positions as the original axes. Is this a bug?

PS. I have to use axes_grid1 to create colorbar axes, because I need to use tight_layout() afterwards, and tight_layout() only applies to axes created by axes_grid1 but not ones created by add_axes().

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np
plt.figure()
ax = plt.gca()
im = ax.imshow(np.arange(100).reshape((10,10)))
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
bbox1 = ax.get_position()
print(bbox1)
bbox1 = cax.get_position()
print(bbox1)
plt.colorbar(im, cax=cax)
plt.show()
```

**Comment by ImportanceOfBeingErnest** [comment]
The bboxes are not set until the figure is drawn, so they point to the same dimensions initially.

Is this a feature request to add such a function to the `axes_grid1` ? Why are the `axes_grid1` functions not sufficient? 

Note that in general such questions are better placed at Stackoverflow where a larger number of people see them and they do not clutter the issue tracker. Or if there is an issue, it might make sense to state it more clearly.

**Comment by llodds** [comment]
I see. I checked bbox after plt.show() and now they have reasonable values. 

My original plan is to overlay two pictures (one with a smaller value of alpha=) and each picture will be shown with a colorbar. My current situation is I can overlay two pictures however two colorbars will overlap as well. So I am trying to find a way to shorten both colorbars by half. I am not sure how to use axes_grid1 to achieve this.

**Comment by ImportanceOfBeingErnest** [comment]
I just saw that you also posted this on SO: https://stackoverflow.com/questions/49576588/matplotlib-shorten-a-colorbar-by-half-when-the-colorbar-is-created-using-axes-g

I will help you over there as there does not seem to be any issue with the library involved here.
