### ISSUE TITLE
Savefig's frameon is ignored

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10939]
The `savefig` documentation says about the `frameon` argument 
>frameon : bool  
>If True, the figure patch will be colored, if False, the figure background will be transparent. If not provided, the rcParam ‘savefig.frameon’ will be used.

This does not seem to be the case

    fig, ax = plt.subplots(figsize = (3,3), dpi=72)
    ax.set_facecolor("navajowhite")
    fig.savefig("fname", framon=True) # or False

gives (grey is the background to see the effect):

![image](https://user-images.githubusercontent.com/23121882/38175820-e74f2ae2-35e2-11e8-823a-867cf1258dab.png)

We would expect to see a difference if `frameon=False`, namely to not have the white frame present in the plot. 

The only option to get the frame off is apparently to use a transparent color for the `facecolor` argument
```
fig.savefig("fname", facecolor=(1,1,1,0))
```

![image](https://user-images.githubusercontent.com/23121882/38175847-9f60b010-35e3-11e8-8fc8-8cab4ecf0cb7.png)

This however still keeps the background patch. It is hence what we would expect the `transparent` argument in `savefig` to do.

>transparent : bool  
>If True, the axes patches will all be transparent; the figure patch will also be transparent unless facecolor and/or edgecolor are specified via kwargs. This is useful, for example, for displaying a plot on top of a colored background on a web page.

So this has essentially the effect one would expect from `frameon`, except that it applies to the figure patch **and** the axes patches. 

![image](https://user-images.githubusercontent.com/23121882/38176116-5cea6f54-35e9-11e8-967c-ba5c6948279a.png)

It also is overwritten in case a `facecolor` is specified.

![image](https://user-images.githubusercontent.com/23121882/38176128-b49c017c-35e9-11e8-8602-74d00cf3fd57.png)

While this is according to the documentation, it's highly confusing. 

Here is a jupyter notebook in case people want to reproduce all the figures: [TransparencyIssue.zip](https://github.com/matplotlib/matplotlib/files/1866618/TransparencyIssue.zip)

To summarize:
* `frameon` is ignored. 
* There is hence no way to completely get rid of the background frame (only to make it transparent).
* The `transparent` is conditional on the `facecolor` being set. (This leads to very counterintuitive behaviour, e.g. `savefig(..., transparent=True, facecolor=None)` results in a **non-transparent** background with a transparent axes.

Proposal for a fix:

* `frameon` keeps or removes the background patch.
* `transparent` turns the background patch and all axes transparent, independently of the facecolor.
* `facecolor` with a transparent color like `(1,1,1,0)` can be used in the rather uncommon case where a transparent background patch is needed (and hence `frameon=False` would not help) but the axes should not be made transparent.
* (optional) Check if it makes sense to let `transparent=True` remove a colorbar patch's facecolor [[*](https://stackoverflow.com/questions/53190203/matplotlib-pyplot-pcolor-savefig-colorbar-transparency)]

**Comment by anntzer** [comment]
See also https://github.com/matplotlib/matplotlib/issues/9921 https://github.com/matplotlib/matplotlib/pull/10023

**Comment by ImportanceOfBeingErnest** [comment]
#10023 does not address the `frameon` being ignored, does it?

**Comment by anntzer** [comment]
It doesn't, but the general idea there is that I'd like to move as many of these kwargs as possible out of savefig, and just have the user manipulate whatever figure/axes properties they want, as needed.

**Comment by QuLogic** [comment]
This was deprecated in the above PR and subsequently removed in #16165.
