### ISSUE TITLE
OSX backend raises deprecation warning for enter_notify_event

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#10948]
**Bug summary**

Opening a figure using the MacOSX backend raises a deprecation warning (see below).

**Code for reproduction**

```python
import matplotlib
matplotlib.use('macosx')
import matplotlib.pyplot as plt
plt.plot([1, 2], [1, 2])
plt.show()
```

**Actual outcome**

```bash
/Users/dstansby/github/matplotlib/lib/matplotlib/backend_bases.py:1993: MatplotlibDeprecationWarning: enter_notify_event expects a location but your backend did not pass one.
  cbook.warn_deprecated('3.0', 'enter_notify_event expects a '
```

**Expected outcome**

**Matplotlib version**

  * Matplotlib version: master branch
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.4

**Comment by tacaswell** [comment]
The fix is to add xy information to https://github.com/matplotlib/matplotlib/blob/3664c83425f86cbe4a2a5133514cee2366b2bfd1/src/_macosx.m#L2243-L2260

**Comment by jklymak** [comment]
Yep, its pretty straigth forward, but #11846 or something else to fix the MacOS backend needs to go in first...
