### ISSUE TITLE
Matplotlib in vfx tools.

### ISSUE THREAD

**Issue by SeongjinKim2** [matplotlib/matplotlib#10959]
Hi, 
Currently, i am try to several time to use matplotlib in vfx tool. (maya, nuke, houdini)

 i was success to import matplotlib at standalone program, but i was failed to import matplotlib at maya.

error is : matplotlib\__init__.py line 127: cannot import name cbook 

How can i import matplotlib at vfx tools?

**Comment by jklymak** [comment]
This is a mailing list or stackexchange question.  Github is for issues and bugs.
