### ISSUE TITLE
in 2.1.1 the x/y limits don't update when updating axes content

### ISSUE THREAD

**Issue by benbowen** [matplotlib/matplotlib#10957]
I am unable to cycle plots interactively with Matplotlib 2.1.1.  In version 1.5.1., as you can see below after pressing a key several times, the x and y axes automatically adjust.  In 2.1.1, the axes limits never adjust and stay what they would be for the first line plotted (the blue one).

I wrote a simple example to reproduce the problem. As you can tell from the code, I'm running it in a notebook.

For solutions, I've tried numerous, cla, clear, various autoscaling commands, etc to no avail.

```
%matplotlib notebook
import matplotlib
print('matplotlib version = %s'%matplotlib.__version__)
import matplotlib.pyplot as plt
import numpy as np

class mpl_fig_cycle(object):
    def __init__(self):
        self.fig,self.ax = plt.subplots()
        self.fig.canvas.mpl_connect('key_press_event', self.press)
        self.set_plot_data()
       
    def set_plot_data(self):
        self.ax.plot(np.random.rand(12) + np.random.rand(1)*2,
            np.random.rand(12) + np.random.rand(1)*2)
       
    def press(self,event):
        self.set_plot_data()

mpl_fig_cycle()
```

Output using 1.5.1:

> ![image](https://user-images.githubusercontent.com/810953/38335652-e9a11e26-3813-11e8-8ce9-d88f97c8090d.png)

Output using 2.1.1:

> ![image](https://user-images.githubusercontent.com/810953/38335736-3f2a5d94-3814-11e8-95e2-c087096f3263.png)

**Comment by ImportanceOfBeingErnest** [comment]
I can run this and it updates as desired with matplotlib 2.2.2, IPython 5.3.0, jupyter notebook server 4.4.1. 
What I find supprising is that apparently it is not necessary to draw the canvas after the update. At least in the interactive backends the code would not run well, because

* The canvas is not redrawn
* The instance of the class will be garbage collected

A running version there would need to use:

    class mpl_fig_cycle(object):
        # ....

        def set_plot_data(self):
            self.ax.plot(...)
            self.fig.canvas.draw_idle()

    mc = mpl_fig_cycle()

Not sure if that helps here; to me Jupyter notebooks are a big mystery in many aspects.

**Comment by benbowen** [comment]
Success! 
> ![image](https://user-images.githubusercontent.com/810953/38338129-093da7dc-381d-11e8-889d-4da801bc1636.png)

I switched to a different conda channel.  I wonder if that is somehow what's messing it up.

This is all that changed:

```bash
(base) [bpb@cori07 ~ 03:23 PM] /global/common/software/m2650/nersc_python_install (master) > conda config --add channels conda-forge

(base) [bpb@cori07 ~ 03:24 PM] /global/common/software/m2650/nersc_python_install (master) > conda install matplotlib=2.2.2

Solving environment: done

## Package Plan ##

  environment location: /global/common/software/m2650/python-cori

  added / updated specs: 
    - matplotlib=2.2.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-2.2.2           |           py27_1         9.0 MB  conda-forge
    kiwisolver-1.0.1           |           py27_1         932 KB  conda-forge
    ca-certificates-2018.1.18  |                0         140 KB  conda-forge
    certifi-2018.1.18          |           py27_0         143 KB  conda-forge
    openssl-1.0.2n             |                0         3.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.7 MB

The following NEW packages will be INSTALLED:

    kiwisolver:      1.0.1-py27_1            conda-forge

The following packages will be UPDATED:

    certifi:         2018.1.18-py27_intel_0  intel       [intel] --> 2018.1.18-py27_0 conda-forge
    matplotlib:      2.1.1-np114py27_intel_2 intel       [intel] --> 2.2.2-py27_1     conda-forge
    openssl:         1.0.2n-intel_0          intel       [intel] --> 1.0.2n-0         conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2018.03.07-0                        --> 2018.1.18-0      conda-forge

Proceed ([y]/n)? y
```
