### ISSUE TITLE
Garbled animations using imagemagick pipe output

### ISSUE THREAD

**Issue by nmiles2718** [matplotlib/matplotlib#10977]
I have been working on some code to create a gif using images stored in FITS format with matplotlib ([animated_fits](https://github.com/nmiles2718/animated_fits)). It has been working fine without a hitch and I have even been able to incorporate pngs with `pillow`. I use the pipe-based writer, `imagemagick`, to save the animations as a gif but this requires the following changes to be made to the `savefig.bbox` parameter:
```python
mpl.rcParams['savefig.bbox'] = 'standard'
```

For some reason, I am unable to make changes to this parameter in v2.2.2. 

```python
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 16:25:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib as mpl

In [2]: print(mpl.rcParams['savefig.format'], type(mpl.rcParams['savefig.format']))
png <class 'str'>

In [3]: mpl.rcParams['savefig.format']='jpg'

In [4]: print(mpl.rcParams['savefig.format'], type(mpl.rcParams['savefig.format']))
jpg <class 'str'>

In [5]: print(mpl.rcParams['savefig.bbox'], type(mpl.rcParams['savefig.bbox']))
None <class 'NoneType'>

In [6]: mpl.rcParams['savefig.bbox']='standard'

In [7]: print(mpl.rcParams['savefig.bbox'], type(mpl.rcParams['savefig.bbox']))
None <class 'NoneType'>

In [8]: 'savefig.bbox' in mpl.rcParams.keys()
Out[8]: True
```

What is even weirder is that if I open the matplotlibrc file (`mpl.matplotlib_fname()`) I find that the value for `savefig.bbox` is correctly set!
```
#savefig.dpi         : figure   ## figure dots per inch or 'figure'
#savefig.facecolor   : w        ## figure facecolor when saving
#savefig.edgecolor   : w        ## figure edgecolor when saving
#savefig.format      : png      ## png, ps, pdf, svg
#savefig.bbox        : standard ## 'tight' or 'standard'.
```

So it would appear that something is actively setting the value of `savefig.bbox` to `None`. Anyone have any idea what's going on here or what I am doing wrong? Any and all help is appreciated!

**Expected outcome**

```python
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 16:25:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib as mpl

In [2]: print(mpl.rcParams['savefig.bbox'], type(mpl.rcParams['savefig.bbox'])).
None <class 'NoneType'>

In [3]: mpl.rcParams['savefig.bbox']='standard'

In [4]: print(mpl.rcParams['savefig.bbox'], type(mpl.rcParams['savefig.bbox']))
standard <class 'str'>

```

**Version Info**
  * Operating system: Mac OSX El Capitan (v10.11.6)
  * Matplotlib version: v2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Mac OSX
  * Python version: v3.5.5

All of the packages were installed using [Astroconda Channel](http://astroconda.readthedocs.io/en/latest/)

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/blob/ad53f46ff6e27984d55e99ecbc84f696409475f8/lib/matplotlib/rcsetup.py#L627-L638

**Comment by nmiles2718** [comment]
I guess I should've been more clear. It is not working as expected, the saved gif comes out garbled:
![short_dark_hp](https://user-images.githubusercontent.com/20194427/38445006-a55eb1a8-39bf-11e8-8e40-739b4ae21b11.gif)

I ran into this behavior before and the problem was solved by setting the `savefig.bbox` parameter to `standard` instead of `tight`.

**Comment by jklymak** [comment]
`"standar"` and `None` are the same thing.  

You must be setting it to `tight` in your code somewhere.

**Comment by nmiles2718** [comment]
I explicitly set the value to `standard` after importing. See [](https://github.com/nmiles2718/animated_fits/blob/2cd23afccb90246414125a041cc505c75c462dbc/lib/mkAnimation.py#L24)

**Comment by jklymak** [comment]
... and the fact that it's `None` later means that worked.  So presumably the garbling is being caused by something else.

**Comment by QuLogic** [comment]
How are you generating this gif? Are the second and remaining frames actually like that? Those weird lines look like something is not reading the files correctly, and not something that matplotlib is doing.

**Comment by tacaswell** [comment]
@QuLogic It is using our animation save code

```python

            if self.save and'gif' in self.save:
                ani.save(filename=self.save, writer='imagemagick',
                         fps=self.fps, bitrate=300)
            elif self.save and 'mp4' in self.save:
                ani.save(filename=self.save, writer='ffmpeg',
                         dpi=180, fps=self.fps,bitrate=300)
```

I have seen wrapping if dimensions get messed up, but the horzonal expansion is just weird.  It looks like there is some disagreement someplace about how many bits are in RGBA...

**Comment by nmiles2718** [comment]
## Update
Really not sure what is going on here, but the problem was solved by setting the `writer` argument to `imagemagick_file` rather than `imagemagick`. There is something happening to the `stdout` *after* the first frame has been drawn that is causing each subsequent image to appear distorted and stretched. Anyways, here is the output with `writer` set to `imagemagick_file`:

![shortdrk_hp](https://user-images.githubusercontent.com/20194427/38458538-3cf795ea-3a6d-11e8-8157-cce56ae32651.gif)


Looking back through my commit history for [animated_fits](https://github.com/nmiles2718/animated_fits), I have been using `imagemagick` since the beginning and I have made numerous `gifs` without any problem. I will keep looking into this issue because I would much rather be able to use the `pipe` based approach rather than saving numerous temporary `pngs`, combining them to make the gif and then deleting them. The temporary file approach can be very frustrating when working with larger datasets because of the added runtime from writing each individual frame to file. 

Any thoughts or suggestions for areas to look into @tacaswell or @QuLogic? You two are probably a lot more knowledgeable on this subject than me, so any advice is greatly appreciated!

**Comment by QuLogic** [comment]
We currently pass rgba data directly to imagemagick. You might be able to force the frame format to png which _might_ get it to work (if imagemagick is somehow forgetting the format layout.) I think something like this?
```python
writer = animation.ImageMagickWriter(fps=self.fps, bitrate=300)
writer.frame_format = 'png'
ani.save(filename=self.save, writer=writer)
```

**Comment by jklymak** [comment]
Milestoning 3.0, but if a regression feel free to re-milestone.

**Comment by anntzer** [comment]
I cannot reproduce the issue running your example code at https://github.com/nmiles2718/animated_fits with your example data, even after editing mkAnimation.py back to using imagemagick instead of imagemagick_file (e.g. `python ../lib/mkAnimation.py -path './' -save test.gif` from the examples directory).

**Comment by tacaswell** [comment]
I wonder if this is mac pipes fighting back?

**Comment by tacaswell** [comment]
I think close this as stale is reasonable as we could not reproduce this in 2018.  If there are new issues of this sort please open a new issue with a reproduction example with current versions of everything.
