### ISSUE TITLE
Current versions cannot reproduce rotate_axes_3d_demo.py

### ISSUE THREAD

**Issue by snownontrace** [matplotlib/matplotlib#10980]
### Bug report

**Bug summary**

Python 2.7.14
Mac OS X El Capitan, v10.11.6
Matplotlib v2.2.2 (same for v2.0.0)

I was trying to reproduce the rotating 3D plot from this example:
https://matplotlib.org/examples/mplot3d/rotate_axes3d_demo.html
(also copied below)

However, the plot displayed the initial view, got stuck, and then finished without any errors.  I later found that if I use another computer with an old matplotlib version (v1.5.3), the code runs correctly.  I used pip to install different versions of matplotlib.

**Code for reproduction**
```python
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# load some test data for demonstration and plot a wireframe
X, Y, Z = axes3d.get_test_data(0.1)
ax.plot_wireframe(X, Y, Z, rstride=5, cstride=5)

# rotate the axes and update
for angle in range(0, 360):
    ax.view_init(30, angle)
    plt.draw()
    plt.pause(.001)
```

**Comment by dstansby** [comment]
I reckon this is an OSX backend bug; what result do you get from this:
```python
import matplotlib
print(matplotlib.get_backend())
```

**Comment by snownontrace** [comment]
With both versions 1.5.3 and 2.2.2 I got "MacOSX"
It appears that I need to install PyQt5 for using Qt5Agg -- will try it later.  Thanks!
