### ISSUE TITLE
How  to initiate the format of a line in matplotlib? 

### ISSUE THREAD

**Issue by lyw615** [matplotlib/matplotlib#10985]
How  to initiate the format of a line in matplotlib? For example,the declaration of  a point :
my_point, = plt.plot([], [], 'bx', alpha=.5).But  it comes wrong,when i  use the format like :my_line, = plt.plot([,], [,], color='brown', linestyle='-')  or   my_line, = plt.plot([[],[]], [[],[]], color='brown', linestyle='-').
Because i want to plot a line between two points  with data  storaged in list

### Bug report

**Bug summary**

The right  format to define a point:my_point, = plt.plot([], [], 'bx', alpha=.5)
But it comes to wrong when i copy the codes to define a line like:my_line, = plt.plot([,], [,], color='brown', linestyle='-')
I  want to get the right format
**Code for reproduction**

```python
# Paste your code here
#my_point, = plt.plot([], [], 'bx', alpha=.5)
#my_line, = plt.plot([,], [,], color='brown', linestyle='-')
```

  * Python version:3.64

**Comment by jklymak** [comment]
Is this a bug report?  If not, then please use the mailing list or stack exchange.
