### ISSUE TITLE
Subplot figure have big blank space In Spyder3

### ISSUE THREAD

**Issue by york2018up** [matplotlib/matplotlib#11012]
### Bug report

**
I use subplot command in Python3.6, Spyder 3 environment, 
I already used plt.tight_layout(),
but the output figure is very strange, and a lot of blank space in the bottom.

I used the same code in Pycharm and Jupyter, the figure can be output perfectly.
The problem only happened in Spyder 3.
Is there someone know why this happened?
Thanks!
**

****

```python
plt.figure(8,figsize = (12,6))
for i in range(9):
    plt.subplot(9,3,i+1)
    plt.scatter(np.arange(0,modeshape[:,0].size),modeshape[:,i])
plt.tight_layout()
plt.show()
```

**Actual outcome**
![default](https://user-images.githubusercontent.com/36834077/38535917-35975c62-3cc1-11e8-876b-58504fdc4b1c.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:  Newest
  * Matplotlib version: Newest
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
You have asked for 27 subplots and only plotted in the first 9.  Hence 2/3 of the space is not being used.

This is not a bug, and should really be posted at StackOverflow or the mailing list.
