### ISSUE TITLE
Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image

### ISSUE THREAD

**Issue by Glutch** [matplotlib/matplotlib#11016]
### Bug report

**Bug summary**

1. install python 2.7
2. pip install pandas & numpy & fbprophet
3. install visual c++
4. error
5. install latest python 3.6.5
6. still error
Error: INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image

**Code for reproduction**

```python
import pandas as pd
import numpy as np
from fbprophet import Prophet

df = pd.read_csv('data.csv')
df['y'] = np.log(df['y'])
df.head()

m = Prophet()
m.fit(df);

future = m.make_future_dataframe(periods=365)
future.tail()

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

m.plot(forecast);

m.plot_components(forecast);
```

**Actual outcome**

```
INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image
```

**Matplotlib version**
  * Operating system: Windows 10 Pro
  * Matplotlib version: 2.2.2
  * Matplotlib backend: TkAgg
  * Python version: 3.6.5
  * Other libraries: pandas, fbprophet

first i tried to install everything with pip, then i uninstalled with pip and tried to install with pip3. Same problem. This is a very fresh install with a new computer. I haven't coded in python before on this computer or installed any other modules

Thanks!

**Comment by jenshnielsen** [comment]
Is this actually an error? Do you get a plot. From the output you provided it looks like its just a logging message (at level info so not serious in any way)

**Comment by ImportanceOfBeingErnest** [comment]
Can you please help people understand in how far this is a problem with matplotlib and not with fbprophet?

**Comment by Glutch** [comment]
I do not get a plot, nothing happens really.
The code is directly copied from https://facebook.github.io/prophet/docs/quick_start.html#python-api

I'm not sure where the problem lies, i'm just guessing matplotlib. I'm very new to python :)

This is the entire log
```
PS C:\Users\me\Documents\dev\prophet> python app.py
INFO:fbprophet.forecaster:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pystan\misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):
Initial log joint probability = -19.4685
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evalsINFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image
```

**Comment by jenshnielsen** [comment]
What happens if you run a simple example using only matplotlib

```python
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()
```

**Comment by Glutch** [comment]
That worked as expected

**Comment by ImportanceOfBeingErnest** [comment]
At the moment this does not look like there is anything wrong within matplotlib. 


You may open an issue on the project that you are using (fbprophet).  Developpers of that project would need to find out if that is a problem with their code or with how they use matplotlib, and whether this is to be expected or a regression with matplotlib. In the latter case they may then reach out on the matplotlib issue tracker with the *actual* problem.

**Comment by Glutch** [comment]
Okey, thank you :)

**Comment by hassheh** [comment]
@Glutch I have the same problem. Are you able to find the reason?

**Comment by bluenote10** [comment]
I'm also getting these weird log messages, but in a slightly different setting:

- no fbprophet involved, basically plain matplotlib usage. I'm not doing anything related to "icons" in my code.
- I do get the plots as expected, so it looks like a logging issue.

I still have to find a minimal reproducing example, the actual code where it happens is quite complex.

**Comment by tacaswell** [comment]
@bluenote10 If you find a minimal example can you please open a new issue?

**Comment by jcomeauictx** [comment]
It's from /usr/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py:
```
        # Put a mpl icon on the window rather than the default tk icon.
        # Tkinter doesn't allow colour icons on linux systems, but tk>=8.5 has
        # a iconphoto command which we call directly. Source:
        # http://mail.python.org/pipermail/tkinter-discuss/2006-November/000954.html
        icon_fname = os.path.join(
            rcParams['datapath'], 'images', 'matplotlib.ppm')
        icon_img = Tk.PhotoImage(file=icon_fname)
        try:
            window.tk.call('wm', 'iconphoto', window._w, icon_img)
        except Exception as exc:
            # log the failure (due e.g. to Tk version), but carry on
            _log.info('Could not load matplotlib icon: %s', exc)
```
Trying to find out what *does* work, just because.

But it's likely not the cause of a failed plot. It just sets the window icon.

**Comment by jcomeauictx** [comment]
I don't get the error from the python commandline:
```python
Python 2.7.18 (default, Sep 19 2023, 07:10:59) 
[GCC 10.2.1 20210110] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> from six.moves import tkinter as tk
>>> window=tk.Tk()
>>> icon_img = tk.PhotoImage(file='/usr/share/matplotlib2/mpl-data/images/matplotlib.ppm')
>>> window.tk.call('wm', 'iconphoto', window._w, icon_img)
''
```
So I'm not sure why the matplotlib backend has a problem. However, the above didn't actually change the icon.
