### ISSUE TITLE
quotes_historical_yahoo_ohlc didn't get data

### ISSUE THREAD

**Issue by Vigor111** [matplotlib/matplotlib#11024]
This is my code

> import matplotlib.pyplot as plt
> 
> from matplotlib.dates import DateFormatter, WeekdayLocator, DayLocator, MONDAY,YEARLY
> from matplotlib.finance import quotes_historical_yahoo_ohlc, candlestick_ohlc
> 
> plt.rcParams['font.sans-serif'] = ['SimHei']
> plt.rcParams['axes.unicode_minus'] = False
> 
> ticker = '600028'
> ticker += '.ss'
> 
> date1 = (2015, 8, 1)
> date2 = (2016, 1, 1)
> 
> 
> mondays = WeekdayLocator(MONDAY)
> alldays = DayLocator()
> #weekFormatter = DateFormatter('%b %d')
> mondayFormatter = DateFormatter('%m-%d-%Y')
> dayFormatter = DateFormatter('%d')
> 
> quotes = quotes_historical_yahoo_ohlc(ticker, date1, date2)
> if len(quotes) == 0:
>     raise SystemExit
> 
> fig, ax = plt.subplots()
> fig.subplots_adjust(bottom=0.2)
> 
> ax.xaxis.set_major_locator(mondays)
> ax.xaxis.set_minor_locator(alldays)
> ax.xaxis.set_major_formatter(mondayFormatter)
> #ax.xaxis.set_minor_formatter(dayFormatter)
> 
> #plot_day_summary(ax, quotes, ticksize=3)
> candlestick_ohlc(ax, quotes, width=0.6, colorup='r', colordown='g')
> 
> ax.xaxis_date()
> ax.autoscale_view()
> plt.setp(plt.gca().get_xticklabels(), rotation=45, horizontalalignment='right')
> 
> ax.grid(True)
> plt.title('600028')
> plt.show()

I got this error

> Traceback (most recent call last):
>   File "yahoo.py", line 22, in <module>
>     quotes = quotes_historical_yahoo_ohlc(ticker, date1, date2)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/finance.py", line 455, in quotes_historical_yahoo_ohlc
>     ochl=False)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/finance.py", line 503, in _quotes_historical_yahoo
>     fh = fetch_historical_yahoo(ticker, date1, date2, cachename)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/finance.py", line 362, in fetch_historical_yahoo
>     with contextlib.closing(urlopen(url)) as urlfh:
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1228, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
>

**Comment by efiring** [comment]
This is one of the reasons we have moved the finance module to its own package:
https://github.com/matplotlib/mpl_finance
and deprecated it within the matplotlib package.  We simply have not been able to maintain it.  See
https://github.com/matplotlib/mpl_finance/issues/11.
