### ISSUE TITLE
shared axes and ticklabels.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11036]
### Bug report

```
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

fig = plt.figure()
gs = gridspec.GridSpec(2, 1)
ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1], sharex=ax1)
ax1.set_xticklabels('')
plt.show()
```

makes the ticklabels on `ax2` disappear as well. 

Similarly:

```python
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.gridspec as gridspec

fig = plt.figure()
gs = gridspec.GridSpec(2, 1)
ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1], sharex=ax1)
ax1.xaxis.set_major_formatter(mticker.NullFormatter())
plt.show()
```

appears to share the formatter.  

This means that we can't manually duplicate the behaviour of `fig, ax = plt.subplots(sharex=True)`.  The reason I need to do it manually is something more complicated:

```python

fig = plt.figure(constrained_layout=True)
gs = gridspec.GridSpec(2, 1)
gs_top = gridspec.GridSpecFromSubplotSpec(1, 2, gs[0])
gs_bot = gridspec.GridSpecFromSubplotSpec(1, 2, gs[1])
ax_top=[]
ax_bot=[]
for i in range(2):
    if i > 0:
        ax_top += [fig.add_subplot(gs_top[i], sharex=ax_top[0], sharey=ax_top[0])]
    else:
        ax_top += [fig.add_subplot(gs_top[i])]

    ax_bot += [fig.add_subplot(gs_bot[i], sharex=ax_top[0], sharey=ax_top[0])]
    pctop = ax_top[i].pcolormesh(np.random.randn(20, 20))
    ax_top[i].set_xticklabels('')
    pcbot = ax_bot[i].pcolormesh(np.random.randn(20, 20), cmap='RdBu_r')
    #if i == 1:
    #    ax_top[i].set_yticklabels('')
    #    ax_bot[i].set_yticklabels('')
    
fig.colorbar(pctop, ax=ax_top)
fig.colorbar(pcbot, ax=ax_bot)
```

**Comment by afvincent** [comment]
Huh, so this behavior would actually be a bug and not a feature ^^ ? (Good to know, because FWIW I have also been bitten by it quite a few times.)

**Comment by jklymak** [comment]
One person's bug is another's feature.  I'm not sure where this behaviour came from - I can see the rationale, but I don't think its correct.

**Comment by ImportanceOfBeingErnest** [comment]
The whole idea of sharing axes is that they use the same formatter and locator. 

Relevant here might be the text in the [shared_axis_demo](https://matplotlib.org/examples/pylab_examples/shared_axis_demo.html):

>If you want to turn off the ticklabels for a given axes (e.g., on
subplot(211) or subplot(212), you cannot do the standard trick

       setp(ax2, xticklabels=[])
>because this changes the tick Formatter, which is shared among all
axes.  But you can alter the visibility of the labels, which is a
property

       setp( ax2.get_xticklabels(), visible=False)
