### ISSUE TITLE
wrong x-position of marker with drawstyle='steps-xxx'

### ISSUE THREAD

**Issue by pierre-haessig** [matplotlib/matplotlib#11031]
### Bug report

Hello, as discussed on [matplotlib-devel](https://mail.python.org/pipermail/matplotlib-devel/2018-April/001041.html), there is a unexpected change in Matplotlib 2.2 when plotting lines and markers (e.g. style 'D-') combined with drawstyle='steps-post'` (`steps-pre' and 'steps-mid' as well).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 6, 7)
y = np.sin(x)
plt.plot(x, y, 'D-', drawstyle='steps-post')
```

**Actual outcome**

In Matplotlib 2.2.2, markers are drawn at each "line break". 

![image](https://user-images.githubusercontent.com/1010404/38661424-1af8d130-3e31-11e8-8e25-82636bc60023.png)

Running the same script with `drawstyle='steps-mid'` yields markers at half-integer positions (except for those at the end)

**Expected outcome**

In all previous Matplotlib versions, the marker was placed at the exact x-position of the input data (which is the left of each segment for `drawstyle='steps-post'`). I didn't do the bissection to know when the changed happen, but I suspect it's quite new (2.1 → 2.2 ?).

**Matplotlib version**
  * Matplotlib version: 2.2.2
  * Python version: 3.6

**Comment by anntzer** [comment]
Something like
```
diff --git a/lib/matplotlib/lines.py b/lib/matplotlib/lines.py
index cc8c61754..738a2396f 100644
--- a/lib/matplotlib/lines.py
+++ b/lib/matplotlib/lines.py
@@ -745,6 +745,8 @@ class Line2D(Artist):
             subslice = slice(max(i0 - 1, 0), i1 + 1)
             self.ind_offset = subslice.start
             self._transform_path(subslice)
+        else:
+            subslice = None
 
         transf_path = self._get_transformed_path()
 
@@ -804,7 +806,15 @@ class Line2D(Artist):
             gc.set_antialiased(self._antialiased)
 
             marker = self._marker
-            tpath, affine = transf_path.get_transformed_points_and_affine()
+
+            # Markers *must* be drawn ignoring the drawstyle.
+            with cbook._setattr_cm(
+                    self, _drawstyle="default", _transformed_path=None):
+                self.recache()
+                if subslice:
+                    self._transform_path(subslice)
+                tpath, affine = (self._get_transformed_path()
+                                 .get_transformed_points_and_affine())
             if len(tpath.vertices):
                 # subsample the markers if markevery is not None
                 markevery = self.get_markevery()
```
fixes the issue, but that's pretty horrible from a performance point of view.  Don't have the time to turn this into a proper PR right now.

**Comment by pierre-haessig** [comment]
great, thanks!
