### ISSUE TITLE
Checking if a figure is empty (no data visible)

### ISSUE THREAD

**Issue by raamana** [matplotlib/matplotlib#11040]
I am in a situation where I need to programmatically check a certain drawing function generated a figure, that has data drawn and visible, so when I export it with `fig.savefig()`, it will have something. It seems there is no `fig.is_empty()` method? I am not taking about figure being visible (`fig.get_visible()`), or atleast 1 child artist being present in the figure (which can be checked with `len(fig.get_children())>0`), but "atleast some data" being visible.. Is there a quick way to check it, or a method below would be of use to include in `matplotlib.Figure` class?

```python
def is_empty(self):
    """Return True if there is no visible artist in the figure"""

    return not any([child.get_visible() for child in self.get_children()])
```

PS: I know it is possible to have atleast one artist visible in a figure, but no actual data drawn, but we won't go there.

**Comment by raamana** [comment]
Here is a better implementation

```python
def is_empty(self):
    """Return True if there is no visible artist in the figure"""

    children = self.get_children()
    if len(children) < 1:
        return True
    
    for child in self.get_children():
        if child.get_visible():
            return False

    return True
```

**Comment by raamana** [comment]
I guess I may need to exclude the background patch, and we need a way to distinguish between "what is added by the user" and what comes with the figure when its created (like the background patch).. 

Also, defining "what is data" might be subjective too.

**Comment by anntzer** [comment]
This seems too subjective/use-case-specific to be provided as a method on the figure class (I'm proposing to close the issue).  But your approach seems about right for your use-case.

**Comment by jklymak** [comment]
I agree with @anntzer Surely the user can keep track of whether they have added artists to a figure or not.  By default, Matplotlib adds all sorts of artists to a cleared figure.

**Comment by anntzer** [comment]
Closing per agreement of two devs.

**Comment by raamana** [comment]
@jklymak, "surely the user can keep track of whether they have added artists to a figure"  is asking too much of the user, esp. the novice ones. Just to play devil's advocate a bit here, there is no for `fig.get_children()` also, as "surely the user can keep track of whether they have added artists to a figure", don't you think?

Also, let me reiterate a finer point you may have missed in my post, it is NOT about what artists were added, but about **what is currently visible on figure**  and _what will appear in the image file_ when it is saved to disk e.g. with savefig().. I need something like this to ensure a complicated visualization/drawing operation actually resulted in visible changes. 

I see this as an analogue to checking if a **mutable** datastructure (e.g. list or ndarray ) is empty.

cc @timhoffm

**Comment by jklymak** [comment]
Again, if its a user, they will know if they want to save the figure or not.  If its a sophisticated developer who needs to make the decision for the naive user, then, as you've noted, its just a few lines to make the same decision.  Not worth the API cruft to add an extra method, in my opinion.

**Comment by ImportanceOfBeingErnest** [comment]
The only definition of "empty" for a figure that I could make sense of is that the figure does not contain any artist. This can easily be queried via `not fig.get_children()`. (This however will hardly ever be the case.)
 
Everything else just depends on definition of "empty". One user may want to know if the figure would only contain white pixels if saved. Another one wants to know if there are any artists in the figure, the next wants to know if the artists are visible (in the sense of visually perceivable), or if the artists are visible (in the sense of having their `visible` property set to True). One might further distinguish between artists that are data and artists that constitute the graph. For data, one may want to know if there is actually no data or whether it's simply outside the shown data range.... I think this can go on forever.  

The point is, this demand is so specialized, there is nothing that matplotlib itself can really provide, apart from the tools that let the user write the query for his special use case.  
As far as I can tell, those tools are available.
