### ISSUE TITLE
set_position() for an axis from ImageGrid has no effect

### ISSUE THREAD

**Issue by raamana** [matplotlib/matplotlib#11053]
### Bug report

`set_position()` for an axis obtained from `mpl_toolkits.axes_grid1.ImageGrid` has no effect, whereas it works for an axis obtained from `plt.subplots()`.. Any idea why?

It seems `ImageGrid` returns a `LocatableAxes` - how is that different from regular `Axes`?

This toolkit needs serious lift on docs - I could contribute, but I have no idea what's going on :)

**snippet**

```python
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.axes_grid1 import ImageGrid

fig = plt.figure(1)
ig = ImageGrid(fig, nrows_ncols=(2, 2),
               rect=(0.02, 0.02, 0.98, 0.98),
               axes_pad=0.005, aspect=True,
               share_all=True, direction='row')
plt.show()

zoomed_pos = (0.3, 0.3, 0.8, 0.8)
ig[0].set_position(zoomed_pos) # this statement is supposed "zoom" the axis, but does not
# it does not work for other values of zoomed_pos either
```

Thanks for your help.
**Matplotlib version**

  * Operating system: Mac (also Linux)
  * Matplotlib version: 2.2.0
  * Matplotlib backend: TkAgg
  * Python version: 3.6

**Comment by ImportanceOfBeingErnest** [comment]
I do not see why `set_position` should zoom the axes. Can you be more clear on what the expected outcome is? (If it works for subplots, as you say, could you provide the working code with `subplots` to understand the difference?)

**Comment by raamana** [comment]
By "zoom", I mean enlarging the axis extents.

Working code with `plt.subplots()`

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(2, 2)
plt.show(block=False)

zoomed_pos = (0.3, 0.3, 0.5, 0.5)
ax[0][0].set(position=zoomed_pos, zorder=1)

plt.pause(0.01)
fig.canvas.draw_idle()
inp = input('hello')

```

--

code **NOT** working with `ImageGrid `

```python
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.axes_grid1 import ImageGrid

fig = plt.figure(1)
ig = ImageGrid(fig, nrows_ncols=(2, 2),
               rect=(0.02, 0.02, 0.98, 0.98),
               axes_pad=0.005, aspect=False,
               share_all=True, direction='row')
plt.show(block=False)

zoomed_pos = (0.3, 0.3, 0.5, 0.5)
ig[0].set(position=zoomed_pos, zorder=1)

plt.pause(0.01)
fig.canvas.draw_idle()
inp = input('hello')

```

**Comment by ImportanceOfBeingErnest** [comment]
Taking an axes out of an ImageGrid and positionning it at a different location is probably not going to work. This is because the axes is still bound to the grid and updates its position accordingly. 

Better remove that axes (`ig[0].remove()`) or turn its axes off (`ig[0].axis("off")` and then create a new axes at the position where you want it to be.

**Comment by raamana** [comment]
What I want is what ImageGrid offers - tight grid alignment. In addition, I need to be able to change the **existing** axis extents (without creating a new one) in a fast way.. deletting/recreating is unnecessary and slow..

also, methods of classes derived from ImageGrid or Grid must throw a warning if user asks them to take an action they are unable to - something like "Axis positions are interlinked in the ImageGrid, and can not be modified individually.."

also is it possible to extract position calculations (for the cells of) of ImageGrid? that's all I need it I think.

**Comment by jklymak** [comment]
get_postion will get you the figure relative position of the axes

You could consider using subplots_adjust if you want an alternative.  And/Or remove the decorators  (perhaps using sharex and sharey) and use tight_layout or constrained_layout.  

Not sure I understand the speed issue.  Adding and removing an axes will be infinitesimal compared to anything that happens at draw time.
