### ISSUE TITLE
keyboard shortcuts don't get registered using the experimental toolmanager with qt

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#11050]
### Bug report

**Bug summary**

All's in the title.

**Code for reproduction**

```python
from matplotlib import use; use("qt5agg")
from pylab import *
rcParams["toolbar"] = "toolmanager"
plot()
show()
```

**Actual outcome**

press e.g. "s", nothing happens

**Expected outcome**

relevant tool (in this case, "save figure") is triggered

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: 2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.6
  * Jupyter version (if applicable): N/A
  * Other libraries:

**Comment by timhoffm** [comment]
Works here for the current master and Qt 5.6.

**Comment by anntzer** [comment]
Ah, it's more subtle than this.
With the classic toolbar, when the figure first pops up, I *don't* need to click on the window first to get keypresses registered.
With toolmanager, I need to first click on the window (even though it supposedly already has focus) for keypresses to get registered.
Can you repro that?

**Comment by timhoffm** [comment]
> Can you repro that?
Yes. More precisely, you have to click on the figure. Clicking on Toolbar/statusbar/tilte does not have any effect.

I don't know anything about the internals of the toolmanager and it's interaction with the backend. So, just a wild guess: Qt does have different [contexts for shortcuts](http://doc.qt.io/qt-5/qt.html#ShortcutContext-enum). Could it be a `Qt::WidgetShortcut` context on the canvas, which is maybe not focused initially?

**Comment by fariza** [comment]
I guess it's my fault. I did the implementation hoping somebody with more QT experience will fix things.
In GTK there is a `canvas.grab_focus()` call that fixes that, is there something similar in QT?

**Comment by anntzer** [comment]
Probably something with setFocus and setFocusPolicy, see how FigureManagerQT does it.

**Comment by fariza** [comment]
@anntzer I pushed https://github.com/matplotlib/matplotlib/pull/18365 that fixes the problem, it was quite simple at the end
