### ISSUE TITLE
PyQt backend: libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by rth** [matplotlib/matplotlib#11058]
**Bug summary**

I am getting some segfaults and general instability when using latest matplotlib with PyQt5 (cf versions below) from the default conda channel  on Debian Linux. I have managed to reproduce part of it below with Docker which produces the `libgcc_s.so.1 must be installed for pthread_cancel to work` error.

**Code for reproduction**

Given the following *Dockerfile*,
```dockerfile
FROM continuumio/miniconda:4.4.10

RUN apt-get install -y xvfb

RUN conda create -n test-env qt==5.9.4 matplotlib==2.2.2 pyqt==5.9.2 python==3.6.5 
```
if we build this image as,
```sh
docker build -t test-pyqt .
```

the following imports raise an error,
```sh
$ docker run --rm test-pyqt:latest \
      /opt/conda/envs/test-env/bin/python -c "import PyQt5.Qt; import matplotlib.pyplot"
libgcc_s.so.1 must be installed for pthread_cancel to work
```
where `libgcc_s.so.1` is present on the system,
```bash
$ docker run --rm test-pyqt:latest file /lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libgcc_s.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=51ad5fd294cd6c813bed40717347a53434b80b7a, stripped
```
Imports in the other order work fine,
```bash
docker run --rm test-pyqt:latest \
      /opt/conda/envs/test-env/bin/python -c "import matplotlib.pyplot; import PyQt5.Qt"
```

This error has some [other occurences unrelated to matplotlib](https://github.com/search?q=libgcc_s.so.1+must+be+installed+for+pthread_cancel+to+work&type=Issues) and generally appears to be due to mixing 64bit and 32bit libraries .  I have checked it's not an issue here with the code provided in [automl/auto-sklearn#403 (comment)](https://github.com/automl/auto-sklearn/issues/403#issuecomment-356559922) . 

There is also an old CPython bug [https://bugs.python.org/issue18748](https://bugs.python.org/issue18748) not sure it's relevant.

I cannot reproduce this on my main Linux system (Gentoo distribution) with conda and the same version of dependencies though.
 
**Matplotlib version**

  * Operating system: Debian 9.4 x86_64 GNU/Linux
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):  Qt5Agg
  * Python version: 3.6.5
  * Other libraries: qt 5.9.4 pyqt 5.9.2

**Comment by tacaswell** [comment]
This should be reported to the anaconda folks as this is a packaging bug,  I am not sure there is anything we can do in Matplotlib to fix this.  That file may not be in the loader search path.

My wild guess is that those Qt binaries are not correctly made relocatable and importing just `PyQt5.Qt` is going to fail (so this is independent of Matplotlib).  If you import Matplotlib it works because the rpath on our c++ libraries are set by conda which pulls in the right version of libgcc so when Qt looks for it it uses the one it already has.

**Comment by tacaswell** [comment]
attn @msarahan

**Comment by msarahan** [comment]
CC @mingwandroid

**Comment by rth** [comment]
Thanks for your response @tacaswell !

> My wild guess is that those Qt binaries are not correctly made relocatable and importing just PyQt5.Qt is going to fail (so this is independent of Matplotlib).

For the record it doesn't. It really a combination of both, interestingly.

> If you import Matplotlib it works because the rpath on our c++ libraries are set by conda which pulls in the right version of libgcc so when Qt looks for it it uses the one it already has.

Thanks, that's the kind of insight I was looking for. I know it's a packaging issue, but I wasn't sure where to open it since I also get the same thing on the conda-forge channel using the docker image above,
```
conda create -c conda-forge -n test-env qt==5.6.2 matplotlib==2.2.2 pyqt==5.6.0 python==3.6.5
```
for different versions of pyqt, qt and a different build setup.  Will open an issue at anaconda & conda-forge ...

**Comment by mingwandroid** [comment]
Investigating ...

**Comment by mingwandroid** [comment]
I cannot reproduce this I'm afraid.

**Comment by mingwandroid** [comment]
Please run `LD_DEBUG=libs python -c "import PyQt5.Qt; import matplotlib.pyplot" 2>&1 | grep libgcc_s.so.1` and paste the output.

We provide our own `libgcc_s.so.1` so you should see:

```
       510:	find library=libgcc_s.so.1 [0]; searching
       510:	  trying file=/opt/conda/envs/qt594mpl222/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
       510:	calling init: /opt/conda/envs/qt594mpl222/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
       510:	calling fini: /opt/conda/envs/qt594mpl222/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1 [0]
(qt594mpl222) root@f9a6894e885b:/# ls -l /opt/conda/envs/qt594mpl222/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
-rw-rw-r-- 14 root root 706232 Mar  8 18:41 /opt/conda/envs/qt594mpl222/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
```

I renamed the env name since I mount my linux conda install from macOS and persist it across various linux distros so I can test lots of them quickly and easily.

**Comment by mingwandroid** [comment]
> and generally appears to be due to mixing 64bit and 32bit libraries

I can guarantee we do not do this.

**Comment by rth** [comment]
Thanks for looking into it @mingwandroid !

> Please run `LD_DEBUG=libs ..`

From inside the container,
```bash
$ LD_DEBUG=libs python -c "import PyQt5.Qt; import matplotlib.pyplot" 2>&1 | grep libgcc_s.so.1
        21:     find library=libgcc_s.so.1 [0]; searching
        21:       trying file=/opt/conda/envs/test-env/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
        21:     calling init: /opt/conda/envs/test-env/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
        24:     find library=libgcc_s.so.1 [0]; searching
        24:       trying file=/opt/conda/envs/test-env/bin/../lib/././libgcc_s.so.1
        24:     calling init: /opt/conda/envs/test-env/bin/../lib/././libgcc_s.so.1
        24:     calling fini: /opt/conda/envs/test-env/bin/../lib/././libgcc_s.so.1 [0]
libgcc_s.so.1 must be installed for pthread_cancel to work
```
The output seems to be different when running it from the docker CLI for some reason (but the error is the same),
```bash
$ docker run --rm -e LD_DEBUG=libs test-pyqt:latest /opt/conda/envs/test-env/bin/python -c "import PyQt5.Qt; import matplotlib.pyplot" 2>&1 | grep libgcc_s.so.1
         7:     find library=libgcc_s.so.1 [0]; searching
         7:       trying file=/opt/conda/envs/test-env/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
         7:     calling init: /opt/conda/envs/test-env/lib/python3.6/site-packages/PyQt5/../../../libgcc_s.so.1
libgcc_s.so.1 must be installed for pthread_cancel to work
```

It is strange ; it does find the right `libgcc_s.so` apparently..

> I cannot reproduce this I'm afraid.

Here is a reproducible [example in Travis CI](https://travis-ci.org/rth/ci-sandbox/builds/367549971) based on the setup in [this Github repo](https://github.com/rth/ci-sandbox/tree/pyqt59mpl222).

**Comment by rth** [comment]
FWIW, I can reproduce it on a Debian 9.4 VM, so it's not Docker related.

**Comment by mingwandroid** [comment]
Ok thanks that helps

**Comment by mingwandroid** [comment]
> FWIW, I can reproduce it on a Debian 9.4 VM

I *cannot* reproduce it on a Debian 9.4 Docker container. What am I missing?

**Comment by rth** [comment]
Let's move this discussion to https://github.com/ContinuumIO/anaconda-issues/issues/9190 as it's probably not very relevant to matplotlib developers..
