### ISSUE TITLE
Matplotlib.units fails if used in a file called new.py

### ISSUE THREAD

**Issue by conallprendergast** [matplotlib/matplotlib#11068]
### Bug report

**Bug summary**

When running the code "import matplotlib.units as units" in a file called "new.py", the "cbook.py" file causes an error when it does an "import new"

**Code for reproduction**
```python
import matplotlib.units as units
```

**Actual outcome**
```
[root@localhost ~]# cat new.py
import matplotlib.units as units
[root@localhost ~]# python new.py
Traceback (most recent call last):
  File "new.py", line 1, in <module>
    import matplotlib.units as units
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 151, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/usr/lib64/python2.7/site-packages/matplotlib/rcsetup.py", line 20, in <module>
    from matplotlib.colors import is_color_like
  File "/usr/lib64/python2.7/site-packages/matplotlib/colors.py", line 54, in <module>
    import matplotlib.cbook as cbook
  File "/usr/lib64/python2.7/site-packages/matplotlib/cbook.py", line 32, in <module>
    import new
  File "/root/new.py", line 1, in <module>
    import matplotlib.units as units
  File "/usr/lib64/python2.7/site-packages/matplotlib/units.py", line 47, in <module>
    from matplotlib.cbook import iterable, is_numlike, is_string_like
ImportError: cannot import name iterable
[root@localhost ~]# ls new.pyc
new.pyc
```

**Expected outcome**

I would expect that the import succeeds as it does when working in a file not named "new.py", The below console log shows my expected outcome

```
[root@localhost ~]# python new2.py
[root@localhost ~]# cat new2.py
import matplotlib.units as units
```

**Matplotlib version**

  * Operating system: CentOS Linux release 7.4.1708 (Core)
  * Matplotlib version: 1.2.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTKAgg
  * Python version: 2.7.5
  * Jupyter version (if applicable):
  * Other libraries: 

Installed matplotlib from pip

**Comment by QuLogic** [comment]
Because it imports `new`:
> File "/usr/lib64/python2.7/site-packages/matplotlib/cbook.py", line 32, in <module>
> import new

and the one in the current directory is used instead.

> Matplotlib version: 1.2.0

This is very old, and that's been removed a long long time ago. You will need to upgrade.
