### ISSUE TITLE
Add a "density" kwarg to hist2d

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#11070]
Recently `ax.hist` got a density keyword argument to conform to numpy kwargs - it would be good if `ax.hist2d` could have it's `normed` argument replaced with a `density` argument for API consistency.

**Comment by dstansby** [comment]
If anyone wants to have a go at this, https://github.com/matplotlib/matplotlib/pull/8993 and https://github.com/matplotlib/matplotlib/pull/9889 show what was done to `ax.hist` to make this change.

**Comment by vermashresth** [comment]
Hi @dstansby, I would like to do this. This PR is for both replacing and depreciating, right?

**Comment by vermashresth** [comment]
@dstansby @jklymak  I noticed that `np.histogram` function of numpy has newer kwargs with depreciated `normed` argument but `np.histogram2d` ([here](https://github.com/numpy/numpy/blob/master/numpy/lib/twodim_base.py#L533:L565)) still works on `normed` and not `density`. How do we replace the arguments for `ax.hist2d` then?

**Comment by jklymak** [comment]
I’d argue for consistency with numpy.  If they don’t used notmed I guess we shouldn’t.

**Comment by dstansby** [comment]
Agree with @jklymak (maybe I should convince numpy should change for API consistency 😉 )

**Comment by anntzer** [comment]
numpy 1.15 introduced a 'density' kwarg to hist2d (https://github.com/numpy/numpy/pull/11529).  Even if we don't require numpy 1.15, we can always just introduce the 'density' kwarg and pass it as 'normed' to numpy.

**Comment by thoo** [comment]
Hi All,
I just submitted the pull request for this issue [here](https://github.com/matplotlib/matplotlib/pull/12436). This is my first request and please let me know if something is missing.

**Comment by anntzer** [comment]
Closed by #13128.
