### ISSUE TITLE
Installing from source on windows, documentation

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#11072]
I finally managed to install matplotlib from source in developing mode thanks to the new build documentation
https://matplotlib.org/users/installing.html
https://matplotlib.org/devdocs/users/installing.html

but it can be improved and I have some questions. I don't really know much about 
`python setyp.py develop` vs `pip install -e`, wheels, `python -mpip install -ve .`, `python setup.py bdist_wheel` etc (but more now than before) and I find it quite hard to find relevant information.

I use conda and "wheel builds using conda packages" worked when I understood that the `build_alllocals.cmd ` resulted in a `.whl` file that I should install with `pip install dist/filename.whl`.  The problem was that the `-e` flag didn't work so my local files where not used when I used matplotlib.

I tried to change `bdist_wheel` in the `build_alllocal.cmd` to `develop` and it worked in one step to get an develop installation.

So are there any reason why the suggested steps are 
```
python setup.py bdist_wheel
pip install dist/filename.whl
```
and not just `python setup.py` or `python setup.py -e`?

A few more words in the documentation about details and difference between an installation in develop mode and a standard installation would probably make it much easier for people like me, that don't really know the details about all python setup tools, to install matplotlib from source.

**Comment by QuLogic** [comment]
At this point, `build_alllocal.cmd` does not exist any more. There are no longer any extra dependencies other than the compiler and Python, and a simple `pip install .` works for installing from source. The instructions no longer mention `bdist_wheel` or `setup.py`, just `pip`, so I don't think there's anything more to change here.
