### ISSUE TITLE
Zoom doesn't work with twinx() using SubplotHost 

### ISSUE THREAD

**Issue by coldbyte** [matplotlib/matplotlib#11087]
### Bug report

**Bug summary**

Zoom doesn't work on secundary ax using SubplotHost. It only zooms the primary ax.

**Code for reproduction**

```python
from mpl_toolkits.axes_grid1.parasite_axes import SubplotHost 
**

fig = plt.figure(figsize=(15, 5))  
primary_ax = []
ysecondary_ax = []        

for i, sec in enumerate(someloop):          
            
  data1 = df.loc[** somedata]
  data2 = df.loc[** somedata]
  data3 = df.loc[** somedata]  
  
  ax = SubplotHost(fig, Rows,Cols,int(sec)) # Grid lines ok but zoom doesn't work on secundary axis
  #ax = plt.subplot(Rows,Cols,int(sec)) # works with zoom but grid lines above data
  
  fig.add_subplot(ax) 
  
  primary_ax.append(ax)
  ysecondary_ax.append(ax.twinx())         
  
  if i > 0:
      ysecondary_ax[i].get_shared_y_axes().join(ysecondary_ax[0], ysecondary_ax[i])
      primary_ax[i].get_shared_y_axes().join(primary_ax[0], primary_ax[i])              
      
  # Plot
  primary_ax[i].bar(data3.index, data3)         
  ysecondary_ax[i].plot(data1.index, data1)
  ysecondary_ax[i].plot(data2.index, data2)
  
  
  ysecondary_ax[i].grid(ls="-", lw=1, zorder=-1, color='k')
  ysecondary_ax[i].set_axisbelow(True)
  
plt.show()  
```

**Actual outcome**

Only zooms the primary ax on all subplots but not the secundary ax. 

**Expected outcome**

To zoom both primary ax and secundary ax on all subplots.

**Matplotlib version**

  * Operating system: Win7
  * Matplotlib version:  2.2.2
  * Matplotlib backend :TkAgg
  * Python version: Python 3.6.2

**Comment by jklymak** [comment]
It'd help if your code was self-contained....

But there is no real good reason for the x-axis to co-zoom with the y-axis the way this is written up.  Usually a twin axis has different data on the other axis, so you there is no unique way to sync up the zooms.

Finally, `axes_grid1` is rather poorly maintained, so this may not get too much attention.  If the same behaviour is problematic using the basic `twinx` then let us know.
