### ISSUE TITLE
Pie demo crashes backport v2.2.2-doc

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11103]
### Bug report

From #11083 and its back port #11089;  see backport #11102 for the new error.

```
Warning, treated as error:
/home/circleci/project/examples/pie_and_polar_charts/pie_demo2.py failed to execute correctly: Traceback (most recent call last):
  File "/home/circleci/project/examples/pie_and_polar_charts/pie_demo2.py", line 32, in <module>
    shadow=True, radius=0.5)
  File "/home/circleci/project/lib/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/circleci/project/lib/matplotlib/axes/_axes.py", line 2930, in pie
    **textprops)
TypeError: text() got multiple values for keyword argument 'size'
```

I'd try and fix, but I'm still not comfortable pushing on the back branches.  This snuck in while the doc builds weren't working...  ping @timhoffm and @dstansby

**Comment by ImportanceOfBeingErnest** [comment]
A smaller issue is that the new pie_demo2 is not using equal aspect in the assumption that this is done interally, which is not the case for version 2.2. A backported version of this should still set equal aspect manually in the example.

**Comment by dstansby** [comment]
I reverted that change, so now I think this is fixed.
