### ISSUE TITLE
Documentation, Spinx

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#11117]
I am building the documentation on windows and have encountered a few problems. I have solved most and I am going to write a pull request about those but I have a problem with the example file  `\matplotlib\examples\userdemo\pgf_preamble_sgskip.py`

I get the following error 
```
Encoding error:
'charmap' codec can't decode byte 0x8f in position 749: character maps to <undefined>
```
The file is not even supposed to be run and I also get the same error with `-Dplot_gallery=0`. 

I guess that it has something to do with the unicode characters when some of the files are rendered (the html?). I get the same errors on 2 different computers.

Whats wrong? Is it possible to solve?

**Comment by ImportanceOfBeingErnest** [comment]
This is an error in sphinx-gallery: https://github.com/sphinx-gallery/sphinx-gallery/pull/311  
It is solved in the current development version, but not in the latest release v0.1.13. So you may wait until v0.1.14 is released or use the master of sphinx-gallery.

**Comment by tacaswell** [comment]
See longer discussion at https://gitter.im/matplotlib/matplotlib?at=5ad5fed17c3a01610defc309 as well.

I'm going to close this as there is not much we can do on the Matplotlib side.  

Sorry that you are having these troubles but I am greatly encouraged that people are building the docs on windows!
