### ISSUE TITLE
Linux Distro MPL Writes Empty Plot for Fig with Unfilled markers saved as EPS

### ISSUE THREAD

**Issue by a-gilbert** [matplotlib/matplotlib#11118]
### Bug report

**Bug summary**
Attempting to save a plot to disk as an eps file fails without throwing an error (in Jupyter Notebook) on linux distributions of MPL for plots with no marker face color.

Running code straight from command line generates error.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.random.rand(10)
y = np.random.rand(10)

plt.close('all')
plt.plot(x, y, 'o', markerfacecolor='None')
plt.savefig('test.eps')
```

**Actual outcome**

Generates figure with axes but no markers only on linux distros.  Runs without error in a jupyter notebook. Running as a script from command line prints the following:
```QApplication: invalid style override passed, ignoring it.```

**Expected outcome**

A figure with axes and markers with no facecolor

**Matplotlib version**

  * Operating system: Linux Mint w/Conda; Friend Tested From only Arch-Linux Packages
  * Matplotlib version: 2.2.2 
                         build: py35h0e671d2_1 
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.5
  * Jupyter version (if applicable): 1.0.0

Installed matplotlib and python purely from conda for my test case. A colleague reported the
same bug for python and packages installed from Arch repos for both python 2.7 and 3

**Comment by anntzer** [comment]
What does
```
from PyQt5.QtWidgets import *; app = QApplication([]); app.exec_()
```
give?

**Comment by a-gilbert** [comment]
```QApplication: invalid style override passed, ignoring it.``` 
Then it hangs and gives no further output.

**Comment by anntzer** [comment]
Then it's a Qt configuration issue, not a Matplotlib issue.
Perhaps setting the backend to tkagg (or even agg, if you don't care about actually popping up a window) will help.  (Call matplotlib.use("tkagg") *before* importing pyplot, or set the MPLBACKEND environment variable to 'tkagg'.)

**Comment by jklymak** [comment]
... or `%matplitlib notebook` for inline images...
