### ISSUE TITLE
No module named 'matplotlib.externals' only inside IPython3 console

### ISSUE THREAD

**Issue by Etienne5131** [matplotlib/matplotlib#11112]
Hi everyone,

I need to use 3d plotting like [in this demo](https://matplotlib.org/examples/mplot3d/contour3d_demo3.html).

Yet, when I enter 

`from mpl_toolkits.mplot3d import axes3d`

I have the following response:

```Traceback (most recent call last):

  File "<ipython-input-1-91c2be293cef>", line 1, in <module>
    from mpl_toolkits.mplot3d import axes3d

  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 4, in <module>
    from matplotlib.externals import six

ImportError: No module named 'matplotlib.externals'
```

However, it only occures inside IPython console (I use spyder3, same problem on bash IPython3).
I tried it on python3 console and it worked.

I updated matplotlib, re-installed it, tried [it](https://github.com/matplotlib/matplotlib/issues/8332), but didn't work ...

Help !!!

**Comment by dstansby** [comment]
What version of Matplotlib are you using? And how did you install it?

**Comment by Etienne5131** [comment]
matplotlib==2.2.2

I installed it by using `sudo pip3 install matplotlib`

**Comment by matthew-brett** [comment]
What do you get for this following, inside IPython:

```
import matplotlib
print(matplotlib.__version__)
print(matplotlib.__file__)
```

**Comment by Etienne5131** [comment]
```
import matplotlib
print(matplotlib.__version__)

Out : 2.2.2

print(matplotlib.__file__)

Out : /usr/local/lib/python3.5/dist-packages/matplotlib/__init__.py
```

**Comment by jenshnielsen** [comment]
@Etienne5131 As you can see from your original traceback combined with your latest comment you have 2 different installations. The toolkits are comming from `/usr/lib/python3/dist-packages/mpl_toolkits` but pip installs matplotlib to `/usr/local/lib/python3.5/dist-packages/matplotlib`

Mostlikely you have a system wide installlation using your system package manager (e.g apt-get) as well as the pip one

**Comment by Etienne5131** [comment]
Ok, it's working now. But could you explain me why ?

Before, I had matplotlib installed with pip3 and nothing installed via synaptics.
It worked with python3 but not with ipython.

Now, it is not installed with pip3 but with synaptics.
It works for both.

Does the system-wide matplotlib is partially non-used inside IPython ?

I had something I did not tell before : I used help('matplotlib') inside python3 and IPython3 to check if both reffered to the same __ini.py__ file and it did. If both command programs are linked to the same package 'file', how did it worked differently ?

**Comment by jenshnielsen** [comment]
Python loads modules according to `sys.path` Your path may be different within IPython and a regular python shell. Try 

```
In [1]: import sys

In [2]: print(sys.path)
```

But originally you must have had at least a partial install via your os level package manager. Your traceback shows that the code is loaded from within `/usr/lib/python3/dist-packages/` pip will never install there. It seems like your system wide install perhaps only contained the `mpl_toolkits` and 
not the base `matplotlib` folder

**Comment by Etienne5131** [comment]
Well, I now have an error inside syder : 

```
Traceback (most recent call last):

  File "<ipython-input-5-ce1e38dd6333>", line 1, in <module>
    plt.subplots()

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 1177, in subplots
    fig = figure(**fig_kw)

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)

  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5agg.py", line 43, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)

  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    return FigureManagerQT(canvas, num)

  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5.py", line 465, in __init__
    self.toolbar.message.connect(self._show_message)

TypeError: connect() failed between NavigationToolbar2QT.message[str] and _show_message()
```

when I try `plt.subplots()`
