### ISSUE TITLE
Can't import name _backports when importing Axes3D from mplot3d

### ISSUE THREAD

**Issue by dvalters** [matplotlib/matplotlib#11122]
I've cloned the latest master of matplotlib. I built matplotlib with the command

```
python -mpip install -ve .
```
I followed the instructions for setting up the test environment in the Developers Guide. But when I run `pytest` the mplot3d test fails trying to import `_backports`.

**Code for reproduction**

Run `pytest` in the matplotlib directory.

The following code also produces the same Traceback:
```
python -c "from mpl_toolkits.mplot3d import Axes3D"
```

**Actual outcome**

```
ERROR collecting lib/mpl_toolkits/tests/test_mplot3d.py 

ImportError while importing test module '/home/dav/devel/matplotlib/lib/mpl_toolkits/tests/test_mplot3d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/mpl_toolkits/tests/test_mplot3d.py:3: in <module>
    from mpl_toolkits.mplot3d import Axes3D, axes3d, proj3d, art3d
../../anaconda3/envs/matplotlib-devel/lib/python3.5/site-packages/mpl_toolkits/mplot3d/__init__.py:6: in <module>
    from .axes3d import Axes3D
../../anaconda3/envs/matplotlib-devel/lib/python3.5/site-packages/mpl_toolkits/mplot3d/axes3d.py:32: in <module>
    from matplotlib.cbook import _backports
E   ImportError: cannot import name '_backports'

```

**Matplotlib version**

  * Operating system: Fedora 27 Linux 4.13.16-302.fc27.x86_64 
  * Matplotlib version: 2.0.0.post7995+g0984694
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.5

**Comment by ImportanceOfBeingErnest** [comment]
Something seems strange with the version number here. If cloning the latest master, it should be something like `2.2.2.post8??+?????`.

**Comment by dvalters** [comment]
@ImportanceOfBeingErnest I am not sure how I managed to end up with an older version from master, but I've started afresh and it's behaving as expected now.

Thanks!

**Comment by dvalters** [comment]
Aha, I think I found what I did wrong now: After building `python -mpip install -ve .`  I ran
```
python setup.py build
```
following the instructions here https://matplotlib.org/devel/contributing.html:

>  If you change the C-extension source (which might happen if you change branches) you will need to run: `python setup.py build`

and this changes the version number from 
`2.2.2.post8??+?????` to `2.0.0+7995+?????`

**Comment by ImportanceOfBeingErnest** [comment]
I don't know why that would happen, sorry. Feel free to reopen if you think this is something matplotlib can be accountable for.

**Comment by jklymak** [comment]
I think that’s wrong.  You just need to run pip again if you change c extensions.  Reopening as a doc bug.

**Comment by tacaswell** [comment]
Are you sure you are running pytest from the enviroment you think you are?  The traceback is coming from "../../anaconda3/envs/matplotlib-devel/lib/python3.5/site-packages/" which should not be the case if you source installed Matplotlib.  Do you have overlapping conda and pip installations of Matplotlib?

Issues like this + pytest's sometimes over-eager test discovery is why I prefer to run the tests as `python tests.py` in the top level directory.

**Comment by dvalters** [comment]
Yes, it looks like the original issue (Traceback etc.) was caused by somehow setting up my conda environment incorrectly. I will try the `python tests.py` in future.

**Comment by efiring** [comment]
From the discussion I conclude this can be closed.  Reopen if necessary.

**Comment by mayukhberkeley** [comment]
I faced the same issue `ImportError: cannot import name '_backports'`
when trying `import matplotlib.pyplot as plt`
I installed matplotlib 3.3.4 via pip

I figured that I also had python3-matplotlib installed that had placed matplotlib version 2.1.1 in the dist-packages

I removed it using the following and it all worked
`apt-get remove -y python3-matplotlib`
