### ISSUE TITLE
Highlight past winners fo JDH plotting contest in docs

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11129]
per suggestion by @dstansby  https://gitter.im/matplotlib/matplotlib?at=5ae09e5815c9b031143542cc

From @ngoldbaum: 
  - 2016: https://scipy2016.scipy.org/ehome/146062/332971/ 
  - 2015: https://scipy2016.scipy.org/ehome/115969/276538/

**Comment by QuLogic** [comment]
Both of those links are dead for me. Is this still something we want to do? Maybe this should go to `mpl-brochure-site`? I don't seem to have permissions to transfer though.

**Comment by jklymak** [comment]
Its a little strange to have a visualization contest, but not advertise the winners on our site, but I don't feel strongly about this.

**Comment by story645** [comment]
It's technically sponsored by Scipy (& submissions can be from any Python viz library not just mpl) so I think it's better suited for the brochure site.

**Comment by ksunden** [comment]
Hasn't been run the past couple years, but here is a link with past winners all listed, so if we do add it, probably the best link to use:

https://jhepc.github.io/gallery.html
