### ISSUE TITLE
ax.scatter after boxplot does not scatter-plot the right values

### ISSUE THREAD

**Issue by cocoaaa** [matplotlib/matplotlib#11133]
I have the following function to boxplot each column of a pandas DataFrame. It also tries to plot .95 and .05 quantile values on each boxplot. 

```python
def boxplot_time_series(df, title=""):
    f,ax = plt.subplots()
    f.suptitle(title)
    ax.set_ylabel('response')
    ax.set_xlabel('sensor id')
    if df.shape[1] > 48:
        df = df.iloc[:, :48]

    df_quantile95 = df.quantile(0.95)
    df_quantile5 = df.quantile(0.05)
    
    df.boxplot(ax=ax)    
    ax.scatter(range(48), df_quantile95, c='r', s=100, marker='+')
    ax.scatter(range(48), df_quantile5, c='r', s=100, marker='+')
```
![image](https://user-images.githubusercontent.com/8037983/39328550-91629c82-4950-11e8-85e4-8bfbc516fd48.png)

However, the quantile values are not plotted on the correct values.  For instance, the quantile95 for the second column is 49.56, while the red marker appears at a much lower value.  Indeed, it doesn't make sense that a 95% quantile value is below the median.  Also, even though `df_quantile95` has a length of 48, it doesn't plot red markers at the last boxplot.

**Matplotlib version**

  * Operating system: Mac0S High Sierra 10.13.3
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.5
  * Jupyter version (if applicable): 1.0.0

Thanks!

**Comment by timhoffm** [comment]
From [boxplot()](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.boxplot.html?highlight=boxplot#matplotlib-axes-axes-boxplot)

> positions : array-like, optional
>    Sets the positions of the boxes. The ticks and limits are automatically set to match the positions. Defaults to range(1, N+1) where N is the number of boxes to be drawn.

The numbers at the bottom are labels of your DataFrame index, not coordinates.

**Solution:**
Use either `range(1, 49)` - possibly `range(1, df.shape[1] + 1)` or alternatively `boxplot(ax=ax, positions=range(48))`

**Comment by timhoffm** [comment]
At devs: the default `range(1, N+1)` is really a bit unfortunate since all other defaults e.g. `plot(y)` use `range(N)`. I really would like to change this. On the other hand, I'm *very* hesitant beacause it would break a lot of existing plots.

**Comment by ImportanceOfBeingErnest** [comment]
I think this normally isn't that much of an issue because the labels would show the coordinates. The issue only occurs with pandas which uses a fixed formatter and fixes the limits such that the plot does not autoscale any more (which would otherwise make the shift pretty obvious). In that sense one could argue that this is in pandas' garden.

**Comment by jklymak** [comment]
I’m going to close for the reasons above.  The zero-index issue can be revisited if anyone feels passionately about it.
