### ISSUE TITLE
"make clean" doesn't remove all the build doc files

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#11139]
**Bug summary**

Building the html docs, then running `make clean` does not remove all the built files, and only removes stuff in the `build` directory. It should also clean the following directories:

```
$ git clean -xfd
Removing api/_as_gen/
Removing build/
Removing gallery/
Removing savefig/
Removing sphinxext/__pycache__/
Removing tutorials/
```

I have no idea how to fix this since the makefile was changed, does anyone else know how?

**Comment by anntzer** [comment]
https://github.com/sphinx-gallery/sphinx-gallery/pull/364 would fix most of that and I'd rather wait until that gets merged and require the next s-g version (which is needed on Windows anyways).
`__pycache__` would stay around, but I don't think that's much of a problem?

The way to fix the makefile, in any case, is to add a custom target, as per https://github.com/sphinx-gallery/sphinx-gallery/pull/364/files#diff-88b99bb28683bd5b7e3a204826ead112.

**Comment by timhoffm** [comment]
*Note*: For now, we're working around the issue by using a custom clean target in the Makefile.
sphinx-gallery/sphinx-gallery#364 would still be preferable in the long run.
