### ISSUE TITLE
Adding legend entries for contour

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#11134]
I'm trying to add legend entries for contour plots, but Matplotlib doesn't seem to like the following code:

```python
import matplotlib.pyplot as plt
import numpy as np

xs = np.linspace(-1, 1, 100)
ys = np.linspace(-1, 1, 100)

X, Y = np.meshgrid(xs, ys)
Z1 = X**2 + Y **2
Z2 = (X - 0.5)**2 + (Y - 0.5)**2

fig, ax = plt.subplots()
ax.contour(X, Y, Z1, colors='k', label='Contour 1')
ax.contour(X, Y, Z2, colors='C0', label='Contour 2')
ax.legend()

plt.show()
```

The warning is
```
No handles with labels found to put in legend.
```

I'm guessing this is because the calls to contour don't automatically add label handles somewhere? It would be nice if legend entries could easily be added for contour plots using the above code.

**Comment by ImportanceOfBeingErnest** [comment]
One can obtain the handles and labels via `ContourSet.legend_elements()`.

```
cntr1 = ax.contour(X, Y, Z1, colors='k')
cntr2 = ax.contour(X, Y, Z2, colors='C0')
h1,_ = cntr1.legend_elements()
h2,_ = cntr2.legend_elements()
ax.legend([h1[0], h2[0]], ['Contour 1', 'Contour 2'])
```
![image](https://user-images.githubusercontent.com/23121882/39364013-a8ab812e-4a2c-11e8-8788-591f69b0e85a.png)

or 

```
cntr1 = ax.contour(X, Y, Z1, )
cntr2 = ax.contour(X, Y, Z2, linestyles="--")
h1,l1 = cntr1.legend_elements("Z1")
h2,l2 = cntr2.legend_elements("Z2")
ax.legend(h1+h2, l1+l2)
```
![image](https://user-images.githubusercontent.com/23121882/39364231-908f97aa-4a2d-11e8-8ac7-b30c09cd196b.png)

Do you think that the use case from the issue is common? How often do people create a contour plot of the same color? 

What would the rationale for the single legend item from the set of countours be? Always take the first one?

**Comment by ImportanceOfBeingErnest** [comment]
Na, that makes things complicated. Suppose you have one color but different linestyles or one linestyle and different colors or different colors and different linestyles, or the same linestyle and the same color... and then the same with linewidths etc.  
I think either the presence of a valid `label` triggers a legend entry or not, it shouldn't depend on anything else. But the question is indeed, how would that legend handle look like?

**Comment by dstansby** [comment]
Hmm, that is indeed right (I haven't thought about this much!). I'll leave this issue open for discussion on potentially easier ways to add legend entries to contour.

**Comment by dstansby** [comment]
Going to close this, as I agree with @ImportanceOfBeingErnest's points above. Thanks for the replies!

**Comment by mladendalto** [comment]
The above answer form @ImportanceOfBeingErnest :
...
h1,_ = cntr1.legend_elements()
h2,_ = cntr2.legend_elements()
ax.legend([h1[0], h2[0]], ['Contour 1', 'Contour 2'])

did not help me, but [this ](https://stackoverflow.com/questions/10490302/how-do-you-create-a-legend-for-a-contour-plot-in-matplotlib) did:
...
labels = ['line1', 'line2','line3','line4',
           'line5', 'line6']
for i in range(len(labels)):
    CS.collections[i].set_label(labels[i])

**Comment by CharizardAcademy** [comment]
> The above answer form @ImportanceOfBeingErnest : ... h1,_ = cntr1.legend_elements() h2,_ = cntr2.legend_elements() ax.legend([h1[0], h2[0]], ['Contour 1', 'Contour 2'])
> 
> did not help me, but [this ](https://stackoverflow.com/questions/10490302/how-do-you-create-a-legend-for-a-contour-plot-in-matplotlib) did: ... labels = ['line1', 'line2','line3','line4', 'line5', 'line6'] for i in range(len(labels)): CS.collections[i].set_label(labels[i])

Thanks, works for me as well :D
