### ISSUE TITLE
Only the first figure window has mpl icon, all other figures have default tk icon.

### ISSUE THREAD

**Issue by lte2000** [matplotlib/matplotlib#11138]
### Bug report

**Bug summary**
When plot more than one figure window, only the first figure window has the default mpl icon (come from matplotlib.ppm), and all other figure windows' icon is set to the default tk icon.

**Code for reproduction**

code 1:
```python
import logging
import matplotlib.pyplot as plt
logging.basicConfig(format="%(name)s %(levelname)s: %(message)s", level=logging.INFO)
plt.figure(1)
plt.plot([1,2,3])
plt.show()
```

code 2:
```python
import logging
import matplotlib.pyplot as plt
logging.basicConfig(format="%(name)s %(levelname)s: %(message)s", level=logging.INFO)
plt.figure(1)
plt.plot([1,2,3])
plt.figure(2)
plt.plot([4,5,6])
plt.show()
```

code 3:
```python
import logging
import matplotlib.pyplot as plt
logging.basicConfig(format="%(name)s %(levelname)s: %(message)s", level=logging.INFO)
plt.figure(1)
plt.plot([1,2,3])
plt.figure(2)
plt.plot([4,5,6])
plt.figure(3)
plt.plot([7,8,9])
plt.show()
```

**Actual outcome**
code 1 runs normally.

code 2 will log:
```
matplotlib.backends._backend_tk INFO: Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image
```
And the icon of figure 1 and figure 2 is different.

code 3 will log:
```
matplotlib.backends._backend_tk INFO: Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image
matplotlib.backends._backend_tk INFO: Could not load matplotlib icon: can't use "pyimage19" as iconphoto: not a photo image
```
The icon of figure 1 is different than figure 2 and 3.
Screenshot attached:
Icon of window:
![figure_title](https://user-images.githubusercontent.com/35422407/39393621-04eec34c-4afa-11e8-85a0-6f4aa58f8c4c.png)

And the icon in taskbar:
![taskbar](https://user-images.githubusercontent.com/35422407/39393623-0ad91244-4afa-11e8-8536-49138602fb4e.png)

If debug, the log information is coming from the exception:
```
file: matplotlib/backends/_backend_tk.py
class _BackendTk()
method new_figure_manager_given_figure()
        # Put a mpl icon on the window rather than the default tk icon.
        # Tkinter doesn't allow colour icons on linux systems, but tk>=8.5 has
        # a iconphoto command which we call directly. Source:
        # http://mail.python.org/pipermail/tkinter-discuss/2006-November/000954.html
        icon_fname = os.path.join(
            rcParams['datapath'], 'images', 'matplotlib.ppm')
        icon_img = Tk.PhotoImage(file=icon_fname)
        try:
            window.tk.call('wm', 'iconphoto', window._w, icon_img)
        except Exception as exc:
            # log the failure (due e.g. to Tk version), but carry on
            _log.info('Could not load matplotlib icon: %s', exc)
```

**Expected outcome**
All figure's icon are same by default.

**Matplotlib version**
  * Operating system: Windows 7 pro.
  * Matplotlib version:  2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.5

**Comment by YonatanSimson** [comment]
I have the same problem in Ubuntu 14.04

Matplotlib version: 2.2.2
Matplotlib backend (print(matplotlib.get_backend())): TkAgg
Python version: 3.6.3

This is the error I get
```
04-29 13:48 matplotlib.backends._backend_tk INFO     Could not load matplotlib icon: can't use "pyimage79" as iconphoto: not a photo image
```

**Comment by tacaswell** [comment]
That is deeply odd...

Also, I am :+1: that the change to using the standard library logging framework is paying off!

I can also reproduce this.  Going through the steps in at the CLI raises the same exception.  The issue is not failing to find the underlying icon, its somehow the second time we make the `iconphoto` call it does not work.   I also tried stashing the `icon_img` at the module level (to use the `PhotoImage` that worked again) and it still fails on subsequent calls.

This looks like a bug in how we are using Tk.

**Comment by anntzer** [comment]
```
diff --git a/lib/matplotlib/backends/_backend_tk.py b/lib/matplotlib/backends/_backend_tk.py
index 85d42eb43..c3ba1189d 100644
--- a/lib/matplotlib/backends/_backend_tk.py
+++ b/lib/matplotlib/backends/_backend_tk.py
@@ -999,9 +999,9 @@ class _BackendTk(_Backend):
         # http://mail.python.org/pipermail/tkinter-discuss/2006-November/000954.html
         icon_fname = os.path.join(
             rcParams['datapath'], 'images', 'matplotlib.ppm')
-        icon_img = Tk.PhotoImage(file=icon_fname)
+        icon_img = Tk.PhotoImage(file=icon_fname, master=window)
         try:
-            window.tk.call('wm', 'iconphoto', window._w, icon_img)
+            window.iconphoto(False, icon_img)
         except Exception as exc:
             # log the failure (due e.g. to Tk version), but carry on
             _log.info('Could not load matplotlib icon: %s', exc)
```
fixes the issue (the second line is not necessary, but saves an access to a tkinter private variable so why not...)

The problem is that otherwise the image is always registered to the *first* window created, and thus not apparent to the second window.

Feel free to make a PR from this.
