### ISSUE TITLE
FR: add a supxlabel and supylabel as the suptitle function which are already exist

### ISSUE THREAD

**Issue by orena1** [matplotlib/matplotlib#11147]
I did not manage to find if supxlabel/supylabel exist, but I think it should be a direct extension to suptitle (for subplots) and might be worth implementing.

Thanks.

**Comment by ImportanceOfBeingErnest** [comment]
To translate this: What the user wants is a figure level function that creates a label for a set of subplots, similar to how `fig.suptitle("dada")` creates a title for the complete figure. 

![image](https://user-images.githubusercontent.com/23121882/39430231-925ee128-4c8d-11e8-8a95-9c9e22b4b6dc.png)


There is a [user script for Matlab](https://www.mathworks.com/matlabcentral/fileexchange/7772-suplabel) which provides such function under the name of `suplabel`. 

<hr>

A [respective SO question](https://stackoverflow.com/questions/16150819/common-xlabel-ylabel-for-matplotlib-subplots) seems to be pretty popular. 
However, I think the only true advantage such function would have compared to a manually placed `text` is if it was possible to include it in the geometry management for subplots.

**Comment by jklymak** [comment]
This is doable in the constrained_layout manager, not in tight_layout.

**Comment by jklymak** [comment]
Cross-ref #13072 as a similar issue

**Comment by WeatherGod** [comment]
I am intrigued. Question: should the supxlabel and supylabel text have a
different font size, much like suptitle? Also, should there be rcparams for
this, similar to what suptitle has? Right now, there is a figure.titlesize
which is used for suptitle. I would guess the equivalent would be
figure.labelsize and such?

**Comment by jklymak** [comment]
Yes, I think so.  BTW, I'd like this attached to gridspec rather than figure, so that there can be two "subfigures" in a paretn figure.  

There will be centering complaints (see #13072) that I don't think are trivial.

**Comment by bilalhsyed** [comment]
I'd like to take a go at this in the next couple weeks. Will ask more questions here as I get started.
