### ISSUE TITLE
Error in documentation of pyplot.errorbar()

### ISSUE THREAD

**Issue by lassehalve** [matplotlib/matplotlib#11156]
### Bug report

**Bug summary**

The documentation of pyplot.errorbar() specifies, that if one gives asymmetrical errors xerr/yerr, the positive one should be given first. In realization, the errors to the lower end have to be given first

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.errorbar([0, 1], [1, 2], xerr=[[1, 2], [5, 10]], yerr=[[1, 2], [5, 10]])
plt.show()
#
```

**Actual outcome**

the smaller errorbars appear to the left of the plot points

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

The documentation way suggests the smaller errorbars should appear to the right

**Matplotlib version**

  * Operating system: RHEL6
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 2.7.10
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by dstansby** [comment]
Which line of the docs do you think needs changing? Is it this one:

    shape(2,N): Separate + and - values for each data point.

**Comment by lassehalve** [comment]
Yes, exactly

**Comment by lassehalve** [comment]
just changing it to 

shape(2,N): Separate - and + values for each data point.

would suffice, I think

**Comment by ImportanceOfBeingErnest** [comment]
Oh wow. I wouldn't have thought that the order of plus/minus actually conveys any information. Would it hurt to say:

"The first row contains the lower errors, the second row contains the upper errors." 

such that this is clearified once and for all?

**Comment by ImportanceOfBeingErnest** [comment]
"Yeah, that sounds fine." as in "Yes, I'll do it that way" or "Yes, I would like to see it being done this way by someone else"?

**Comment by lassehalve** [comment]
Sorry, I did not see that question :)

I have never edited the documentation up til now, so I would like if somebody else could do that =)

**Comment by JacobEFO** [comment]
I would like to handle this issue @ImportanceOfBeingErnest 

It seems like a great way to contribute to Matplotlib.

**Comment by ImportanceOfBeingErnest** [comment]
@JacobEFO This is already on it's way (even twice). 

But you may look at other [Good first issue](https://github.com/matplotlib/matplotlib/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue")s if you like.

**Comment by JacobEFO** [comment]
@ImportanceOfBeingErnest Ah typical.

I will look into it, and see where I can pitch in ;) Thank you.

**Comment by Clear-up** [comment]
OMG it's already Sept. but the documentation is still not corrected. I meet this problem as well and it took me several hours to find the problem!!!!!

**Comment by jklymak** [comment]
The PR that closed this issue is in the current documentation.  If you think the documentation needs further update, please open a new issue with specifics.  Thanks!
