### ISSUE TITLE
home/back/forward buttons do nothing in 3d mode

### ISSUE THREAD

**Issue by samuela** [matplotlib/matplotlib#11178]
### Bug report

**Bug summary**

The home, backward, and forward buttons in the UI do nothing when the plot is three dimensional. Also the zoom button does not work at all. It simply rotates the plot.

**Code for reproduction**

From the examples,
```python
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
from matplotlib import cm

fig = plt.figure()
ax = fig.gca(projection='3d')
X, Y, Z = axes3d.get_test_data(0.05)

cset = ax.contourf(X, Y, Z, cmap=cm.coolwarm)
ax.clabel(cset, fontsize=9, inline=1)

plt.show()
```

**Actual outcome**

Buttons don't work.

**Expected outcome**

Buttons would work.

**Matplotlib version**

  * Operating system: macOS 10.13.4
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

Python and matplotlib installed via pip in a virtualenv.

**Comment by dstansby** [comment]
I can reproduce this.

**Comment by samuela** [comment]
cc @nfoti
