### ISSUE TITLE
[feature request] multiple 3d plots with tied viewing angles

### ISSUE THREAD

**Issue by samuela** [matplotlib/matplotlib#11181]
I have a figure with a number of 3d subplots that are all showing basically the same things. I'd really love to have a way to rotate any one of these plots in the UI and have all of the others adjust their viewing angles to match, ideally in real-time.

**Comment by ImportanceOfBeingErnest** [comment]
You may always connect those subplots through events. A possible solution is given in this Stackoverflow question: [Using Matplotlib 3D axes, how to drag two axes at once?](https://stackoverflow.com/questions/41167196/using-matplotlib-3d-axes-how-to-drag-two-axes-at-once)

<details>
 <summary>Code here for completeness</summary>

```
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import matplotlib.pyplot as plt
import numpy as np

n_angles = 36
n_radii = 8

radii = np.linspace(0.125, 1.0, n_radii)
angles = np.linspace(0, 2*np.pi, n_angles, endpoint=False)
angles = np.repeat(angles[..., np.newaxis], n_radii, axis=1)

x = np.append(0, (radii*np.cos(angles)).flatten())
y = np.append(0, (radii*np.sin(angles)).flatten())
z = np.sin(-x*y)

fig = plt.figure( figsize=(13,6))
fig.subplots_adjust(left=0, right=1, top=1, bottom=0, wspace=0)
ax = fig.add_subplot(1, 2, 1, projection='3d')
ax2 = fig.add_subplot(1, 2, 2, projection='3d')

ax.plot_trisurf(x, y, z, cmap=cm.jet, linewidth=0.2)
ax2.plot_trisurf(x, y, z, cmap=cm.viridis, linewidth=0.5)

def on_move(event):
    if event.inaxes == ax:
        if ax.button_pressed in ax._rotate_btn:
            ax2.view_init(elev=ax.elev, azim=ax.azim)
        elif ax.button_pressed in ax._zoom_btn:
            ax2.set_xlim3d(ax.get_xlim3d())
            ax2.set_ylim3d(ax.get_ylim3d())
            ax2.set_zlim3d(ax.get_zlim3d())
    elif event.inaxes == ax2:
        if ax2.button_pressed in ax2._rotate_btn:
            ax.view_init(elev=ax2.elev, azim=ax2.azim)
        elif ax2.button_pressed in ax2._zoom_btn:
            ax.set_xlim3d(ax2.get_xlim3d())
            ax.set_ylim3d(ax2.get_ylim3d())
            ax.set_zlim3d(ax2.get_zlim3d())
    else:
        return
    fig.canvas.draw_idle()

c1 = fig.canvas.mpl_connect('motion_notify_event', on_move)

plt.show()
```

</details>

I guess one could easily extent this functionality to any amount of axes, but I currently wouldn't know where in the code to put that.

**Comment by anntzer** [comment]
fwiw I feel like a recipe is good enough...

**Comment by ImportanceOfBeingErnest** [comment]
The problem with this recipe above is that it uses the "private" `_rotate_btn` and `_zoom_btn`. I'm personally not very stringent about using such attributes, but I guess if proposing this as some "official strategy" (e.g. as example on the matplotlib site) people wouldn't like it.

**Comment by dstansby** [comment]
I think this would be a nice new feature - kind of like `sharex` and `sharey`, but for 3D plots.

**Comment by ImportanceOfBeingErnest** [comment]
Yep, just mind that rotation is a priori independent on sharing. You might synchronize the viewing angle, but not share the axes or vice versa. This is easily accounted for when manually creating the callback, but for some automated option it will require two independent groupers or similar. 
Not saying this shouldn't be implemented, but I suppose there are much more important features in the  [mplot3d](https://github.com/matplotlib/matplotlib/labels/mplot3d) category to fix/implement first.

**Comment by samuela** [comment]
cc @nfoti
