### ISSUE TITLE
RectangleSelector examples don't run in notebooks

### ISSUE THREAD

**Issue by sorenrasmussen** [matplotlib/matplotlib#11201]
The RectangleSelector examples in the documentation ([here](https://matplotlib.org/gallery/widgets/rectangle_selector.html) and [here](https://matplotlib.org/api/widgets_api.html#matplotlib.widgets.RectangleSelector)) don't work properly in Jupyter notebooks.

To fix, change the last line from:
`show()` or `plt.show()`
to
`show(block=True)` or `plt.show(block=True)`

Thanks!

**Comment by jklymak** [comment]
You don’t usually need to call show in notebooks.  The examples are meant to work standalone.  While it’s a bit confusing to notebook users it’s not particularly a bug.  Is there some way we can make the difference between notebooks and other backends more straightforward?

**Comment by sorenrasmussen** [comment]
Not calling `show` does not make it work.
Since the gallery-example contains a "download jupyter notebook" button, it would make sense if the notebook actually works :)

**Comment by sorenrasmussen** [comment]
Maybe this is not just a documentation issue, but a bug?
Events, connected using `fig.canvas.mpl_connect(...)` work fine in notebooks without a blocking `show()`..

**Comment by jklymak** [comment]
Which backend are you using?   Does nbagg work ok?  Ie %matplotlib notebook

**Comment by sorenrasmussen** [comment]
I have tried with Qt, TK and nbagg.

As I am diggin into this things are starting to get hairy.
These are results using the example from the API doc:

### nbagg:
With `nbagg` it never works.

### tk
With `%matplotlib tk` and `plt.show(block=True)`, the code cell will run the first time and block until the figure is closed. The second time I run the cell and close the figure, the cell will keep blocking forever.

### qt
With `%matplotlib qt` and `plt.show(block=True)`, the code cell will run the first time and block until the figure is closed. The second time I run the cell and close the figure, the cell will not block.

**Comment by ImportanceOfBeingErnest** [comment]
Maybe there is the need to be more specific here. Which jupyter version, which IPython version, which matplotlib version are in use? What exactly does not work? I cannot reproduce this and everything works fine when using `%matplotlib notebook`.

I do agree that it is pretty useless to have the notebook with `%matplotlib inline` for an interactive example. I fear there is little one can do, as those are automatically generated (unless one want to change them all to `notebook`).

**Comment by sorenrasmussen** [comment]
### Software:
- matplotlib: 2.2.2
- IPython: 6.2.1
- Jupyter 4.4.0

### What works:
I can draw rectangles in the figure.

### What doesn't work:
When `plt.show()` does not block, the `onselect` function does not run.
`plt.show(block=True)` does not consistently cause blocking behaviour.

**Comment by tacaswell** [comment]
The print is likely coming out in the terminal where you started the notebook server....

**Comment by tacaswell** [comment]
I also strongly recommend against using notebooks + GUI backends, there are too many event loops running.

**Comment by sorenrasmussen** [comment]
**Ernest:**
In a notebook, a blocking function means means that the cell does not finish executing. show(block=True) should keep the cell "running" until the figure is closed.

You are right. The callback does run, but does not print. I guess this is not possible. Sorry for the confusion on my part.

This leaves only the problem of inconsistent behaviour of show(block=True) and a documentation issue :)

**Comment by ImportanceOfBeingErnest** [comment]
> In a notebook, a blocking function means means that the cell does not finish executing. show(block=True) should keep the cell "running" until the figure is closed.

Do you mean that if you click on "Run All", cells further down would not be executed? I cannot reproduce this: independent on `plt.show()` or `plt.show(block=True)` all cells will be executed in my case. 
@sorenrasmussen Is this different for you?

I think the question here is really:
* Would there be a difference between `plt.show()` and `plt.show(block=True)` from within matplotlib? And if so how does it look like and where does it come from?
* Finally, is there anything the matplotlib documentation can do not to trap people into running the notebooks from the example section, which have simply not been designed for or ever been tested on jupyter?

**Comment by sorenrasmussen** [comment]
@ImportanceOfBeingErnest Correct, cells further down should not be executed if a function (and thereby also the cell where it was run) is blocking. Just like any other Python code.

@tacaswell Unfortunately, the rectangleselector is quite slow and a bit buggy with nbagg, at least on my setup. For example, if I mark rectangles quickly in succession, the "old" rectangles sometimes stay partly visible

**Comment by sorenrasmussen** [comment]
`plt.show()` never blocks. This is as expected.
`plt.show(block=True)` blocks _sometimes_, depending on the backend and whether the cell has been run before or not (see above). I would expect it to block every time, for any backend (maybe except `inline`).

**Comment by ImportanceOfBeingErnest** [comment]
I am still sceptical. Looking at the source code of the nbagg backend there should not be any difference between `plt.show()` and `plt.show(block=True)`, because the argument `block` is never actually used. This is consistent with what I observe running the code in a jupyter notebook.  
So if someone observes a difference, it should be well described, best without the use of qualifiers like "expected" or "works fine" but rather in a clear descritive way, and best without using the verb "to block" itself.  
A table like 
![image](https://user-images.githubusercontent.com/23121882/39814636-663c8a96-5395-11e8-960e-6f134173ced2.png)

could then help to sort this out.

**Comment by sorenrasmussen** [comment]
@ImportanceOfBeingErnest 

- %matplotlib notebook
  - 1st:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell execution finishes
  - n'th:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell execution finishes

- %matplotlib tk
  - 1st:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell keeps running until figure close.
  - n'th:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell keeps running indefinitely.
    
- %matplotlib qt
  - 1st:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell keeps running until figure close.
  - n'th:
    - `plt.show()`: cell execution finishes.
    - `plt.show(block=True)`: cell execution finishes.

**Comment by ImportanceOfBeingErnest** [comment]
So to summarize, 
* **Jupyter `notebook`** backend: This is **feature request** to have a blocking behaviour in the notebook. This might in general be hard to achieve due to the connections to the server.
* In addition there might be a **bug** in the **qt and tk backends** when being run from within jupyter. I cannot reproduce this either, but that probably has different reasons out of the scope of this question.
