### ISSUE TITLE
can't plot from remote machine connected via ssh -X from macOS

### ISSUE THREAD

**Issue by fvisconti** [matplotlib/matplotlib#11220]
### Bug report

**Bug summary**
Any plot trial ends up with this error message: `This plugin does not support propagateSizeHints()` and then hangs.
Same procedure when connecting from a local Linux machine runs just fine.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.hlines(3, 0, 3)
plt.show()
```
**Actual outcome**
after the first `plt` invocation, it logs:

```
QFontDatabase: Cannot find font directory /astri03/data1/visconti/miniconda/envs/astri/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /astri03/data1/visconti/miniconda/envs/astri/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /astri03/data1/visconti/miniconda/envs/astri/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /astri03/data1/visconti/miniconda/envs/astri/lib/fonts - is Qt installed correctly?
```
Yes, four times.

Then, after `plt.show()`:
`This plugin does not support propagateSizeHints()` 
and then hangs.

**Expected outcome**
Simple plot.

**Matplotlib version**

  * Operating system: local: macOS; remote: Linux Ubuntu (both 14.04 and 16.04)
  * Matplotlib version:  2.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.0 from Continuum Analytics
  * Jupyter version (if applicable): 
  * Other libraries: 

Matplotlib installed with conda, default channel.

It happens both running through `ipython` than vanilla `python`.

**Comment by jklymak** [comment]
I don't think either of those errors originate w/ matplotlib.  Can you make a basic Qt GUI run over ssh -X?  (i.e. take matplotlib out of the loop?) If not, I think the error is in Qt.  But I'm not an expert on this...

**Comment by phobson** [comment]
As a mostly Windows user who rarely SSHs into remotes, I wouldn't expect the remote machine to be able to launch a GUI on my local machine. Am I missing something?

**Comment by jklymak** [comment]
`ssh -X` lets the remote launch x-windows on your local machine *if* the x-server is running.  I assume @fvisconti can open a local xterm over ssh -X, though I've often found such things to be flakey on macOS....

**Comment by tacaswell** [comment]
The server wouldn't happen to be using wayland would it?

Does the TkAgg backend work for you?

Strongly suspect that this is a Qt issue, can you open any other Qt app?  Does:

```python
import PyQt5.QtWidgets
app = PyQt5.QtWidgets.QApplication([b'test'])
mw = PyQt5.QtWidgets.QMainWindow()
mw.show()
get_ipython().run_line_magic('history', '')
app.exec_()
```

work?

**Comment by fvisconti** [comment]
Sorry for that, it was a server configuration issue.
