### ISSUE TITLE
RAM does not get cleaned correctly using Qt5 backend

### ISSUE THREAD

**Issue by nilsholle** [matplotlib/matplotlib#11226]
### Bug report

**Bug summary**

When closing a Qt window with an embedded matplotlib figure (Qt5Agg backend), the memory is not released, even trying closing, hiding and deleting the canvas explicitly and setting its parent to None.

**Code for reproduction**

Main window:
```python
import sys

from PyQt5.QtWidgets import *

from mplwindow import MplWindow


class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.btn = QPushButton("Press me")
        self.setCentralWidget(self.btn)
        self.btn.clicked.connect(self.__openWindow)

    def __openWindow(self):
        MplWindow(self).show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())

```

Window with embedded figure that opens when pressing the button in MainWindow:
```python
import gc

import matplotlib
matplotlib.use("Qt5Agg")
import matplotlib.backends.backend_qt5agg as mplAgg
import numpy as np
from matplotlib.figure import Figure
from PyQt5.QtWidgets import *


class MplWindow(QMainWindow):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.fig = Figure()
        ax = self.fig.add_subplot(111)
        ax.plot(np.arange(20000), np.random.random(20000))
        self.canvas = mplAgg.FigureCanvasQTAgg(self.fig)
        self.setCentralWidget(self.canvas)

    def close(self):
        self.setParent(None)
        self.canvas.close()
        self.canvas.hide()
        self.canvas.setParent(None)
        del self.canvas
        del self.fig
        gc.collect()
        super().close()

```

**Actual outcome**

Memory usage increases every time a new subwindow with a figure embedded is opened and does not decrease when closing it.
![bildschirmfoto von 2018-05-10 21-01-52](https://user-images.githubusercontent.com/9198471/39888923-9fbc28a6-5496-11e8-81f6-04fa2fdc9279.png)

**Expected outcome**

Memory usage should decrease when closing the window.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5
  * Jupyter version (if applicable):
  * Other libraries: 

Installed using pip.

**Comment by ImportanceOfBeingErnest** [comment]
That's not a matplotlib problem. You never call `close`. Maybe you want to add something like

    def closeEvent(self, event):
        self.close()

**Comment by nilsholle** [comment]
You are right, but the problem still persists.

I added
```python
def closeEvent(self, event):
    self.close()
    event.accept()
```
and checked if self.close() is actually run.

**Comment by ImportanceOfBeingErnest** [comment]
I cannot reproduce this. When actually calling close, the memory is freed. (I'm running this with python 3.6 on windows 8.1 and matplotlib 2.2.2)

**Comment by nilsholle** [comment]
Sorry, for this minimal example your comment actually fixed it.
In a more complex project the problem is still there, I will try to find its root there.
Thanks anyways!
