### ISSUE TITLE
about the contourf command

### ISSUE THREAD

**Issue by stardomlee** [matplotlib/matplotlib#11261]
I have one column of data such as (n,1) array. I want to draw 2D contourf image (converting (l*m) array) using this data, so I reshaped this data using nump.reshape command, and it worked well.

However, if I have three columns of data such as (n,3) array. all the three columns data have the same position in the contourf image (also converting (l*m) array), I have no good idea how to reshape the array to visualize the data? 

In my current case, my data is (241016, 3) array, and i need to mesh as (640*375) grids in the contourf image. If I only use one column, it is OK. In this case, I will get three pictures using this data. Because all the three columns data have same coordinates, so I want to realize the three pictures in one image. 

### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#import numpy as np
import matplotlib.pyplot as plt


###### loading data ######
data0 = np.loadtxt('dnss_all_00021')
data_i1 = np.array(data0[:,0])
data_i2 = np.array(data0[:,1])
data_i3 = np.array(data0[:,2])
array_i1 = np.reshape(data_i1, (376, 641))
array_i2 = np.reshape(data_i2, (376, 641))
array_i3 = np.reshape(data_i3, (376, 641))
delta = 1
x = np.arange(0.0, 641, delta)
y = np.arange(0.0, 376, delta) 
X, Y = np.meshgrid(x, y)

##### Graph plotting #######
plt.figure(figsize = (10, 4))
plt.subplots_adjust(wspace = 0.3, hspace = 0.6)
plt.subplot(1,3,1)
plt.contourf(X, Y, array_i1)
plt.colorbar()
plt.title('1')
plt.subplot(1,3,2)
plt.contourf(X, Y, array_i2)
plt.colorbar()
plt.title('2')
plt.subplot(1,3,3)
plt.contourf(X, Y, array_i3)
plt.colorbar()
plt.title('3')

plt.show()
#
```

[dnss_all_00021.txt](https://github.com/matplotlib/matplotlib/files/2011396/dnss_all_00021.txt)

![figure_1](https://user-images.githubusercontent.com/23466046/40153184-70f26576-59c3-11e8-870f-e325f6ea9ec8.png)
These pictures are plotted by drawing every columns' data respectively. I want to make them in one picture because every column data have same positions.

Thank you very much,
Joeylee

**Comment by jklymak** [comment]
GitHub is for bug reports.  Please use mailing list or stackexchange if you want user support.   Thanks!
