### ISSUE TITLE
'str' object has no attribute '_rgba_under' when trying to set_under a colormap 

### ISSUE THREAD

**Issue by pskeshu** [matplotlib/matplotlib#11264]
### Bug report

When trying to set_under a colormap, matplotlib throws an AttributeError.

**Code for reproduction**

```python

Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib. pyplot as plt
>>> from matplotlib.colors import Colormap
>>> Colormap.set_under("Greens_r", color='k')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/matplotlib/colors.py", line 555, in set_under
    self._rgba_under = colorConverter.to_rgba(color, alpha)
AttributeError: 'str' object has no attribute '_rgba_under'
>>> print(matplotlib.__version__)
2.2.0
```

But the same code works with `Colormap.set_under(plt.cm.Greens_r, color='k')`

For the sake of consistency, I think it would be good if the function worked even if the string is passed.

**Comment by ImportanceOfBeingErnest** [comment]
It's not really clear what the code shown is supposed to be doing. To get rid of the error, you would need to provide the colormap as first argument of `set_under`, 

```
import matplotlib
import matplotlib.cm
from matplotlib.colors import Colormap
Colormap.set_under(matplotlib.cm.Greens_r, color='k')
```

but I'm sceptical that this is in any way useful.  
Usually you would work with instances and call the instance methods instead of a class method:

```
import matplotlib
from matplotlib.colors import Colormap

cmap = Colormap("Greens_r")
cmap.set_under(color='k')
```

Or the more often used way

```
import matplotlib
import matplotlib.cm

cmap = matplotlib.cm.get_cmap("Greens_r")
cmap.set_under(color='k')
```

**Comment by ImportanceOfBeingErnest** [comment]
Oh, I didn't see the edit when answering. So what you're asking for is essentially to do a typechecking on *`self`* inside of a class' method. There are many reasons not to do this, which are all based on how python is designed and are outside the matplotlib domain. I'm sure there are some tutorials about classes, methods and the use of `self` available online, which might help you to get an insight on the topic.

**Comment by anntzer** [comment]
You will likely get more in-depth answers on stackoverflow or the mailing list.
