### ISSUE TITLE
Triangle plot with Python using data file

### ISSUE THREAD

**Issue by esadri21** [matplotlib/matplotlib#11269]
I have a data file containing 4 columns and n rows. I would like to plot them similar to [this](https://www.researchgate.net/profile/A_Jessner/publication/263352189/figure/fig1/AS:296372118016011@1447672027453/Triangle-plot-of-distributions-of-fitted-parameters-diagonal-and-2-d-correlations.png) .  if you plot my data file columns two by two the figure is elliptical similar to these links, but I want to plot them professionally. I wonder how can I do that in Python

**Comment by jklymak** [comment]
GitHub is for bugs not user support.  Try stackexchange or the mailing list.  Thanks!
