### ISSUE TITLE
Broken test for pcolormesh with masked array as input

### ISSUE THREAD

**Issue by Zac-HD** [matplotlib/matplotlib#11270]
https://github.com/matplotlib/matplotlib/blob/31d2c2ff9b652a03d58c77529326e21a2cdb31ae/lib/matplotlib/tests/test_axes.py#L1132-L1155

Note that `Zm` is unused; and thus there is no test for `pcolormesh` with a masked array as input.

**Comment by QuLogic** [comment]
Duplicate of #8802.
