### ISSUE TITLE
Strange interaction constrained layout and "save" button notebook backend...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11285]
### Bug report

While in a jupyter notebook if I do:

```python
import matplotlib.pyplot as plt
%matplotlib notebook 
fig, ax = plt.subplots(constrained_layout=True)
```
the figure renders properly, but if I then try and drag the figure off the screen, or hit the "save" button (or hit "s") the figure doesn't render or drag.  Somehow `constrained_layout` is interfering w/ the "saving" of the png.  Everything else works fine (i.e. I can do `fig.savefig` etc), but somehow the interactivity of the figure is broken.

**Comment by ImportanceOfBeingErnest** [comment]
I cannot reproduce this. This works fine for me in various tested environments including python2, python3, mpl 2.2.2 and master (from a week ago).
