### ISSUE TITLE
imshow of multiple images produces old pixel values printed in status bar

### ISSUE THREAD

**Issue by calumblair** [matplotlib/matplotlib#11284]
### Bug report

**Bug summary**
When viewing an image with an interactive backend, if multiple images are displayed sequentially in a figure window, the status bar text showing image intensity at a coordinate will be wrong and will refer to a previous image.

**Code for reproduction**
This should be run from an Ipython / Jupyter / Spyder console

```python
import matplotlib
matplotlib.use('qt5agg')
import matplotlib.pyplot as plt
print(matplotlib.get_backend())
import numpy as np
X0 = np.zeros([100,100])
X1 = np.ones([100,100])
plt.imshow(X0)
#mouseover the image. The status bar will show "x = <coord> y = <coord> [0]"
plt.imshow(X1)
#mouseover the image. The status bar will show "x = <coord> y = <coord> [1]"
plt.imshow(X0)
#mouseover the image. The status bar will show "x = <coord> y = <coord> [1]"
#you  may have to repeat the last 2 plt.imshow calls to get this behaviour to appear
```

**Actual outcome**

When you mouseover the figure window after displaying multiple figures, when looking at the X/Y coordinates and values in the status bar, the values for each array element are incorrect and refer to a previous image. If X0 is displayed, I expect to see "x = <coord> y = <coord> [0]" but x = <coord> y = <coord> [1]"  is displayed.

**Expected outcome**
When you mouseover the figure window, the X/Y coordinates and values in the status bar should be correct and match the image being displayed. If X0 is displayed, I expect to see "x = <coord> y = <coord> [0]" 

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg 
  * Python version: 3.6.5
  * Jupyter version (if applicable): 1.0.0
  * Other libraries:  numpy 1.14.2

Matplotlib, numpy and python installed from conda (default channel)

This behaviour is observed with qt5agg and tkagg backends but may apply to other interactive backends too.

**Comment by tacaswell** [comment]
I also noticed this yesterday but did not get to writing up a issue!

The issue is that 1) the artists that partcipate in the mouse_over logic are a set 2) all of the images you add have the same zorder so the 'top' artist is unclear (but at draw time falls back to the order they were added in).

The simplest work-around is to ether remove the old image or do

```
im = ax.imshow(X0)
im.set_data(X1)
im.set_data(X2)
```

to re-use the artist or to assign distinct z-orders.

The more complicated fix would be to change from using a set to a list to store the artists that would like to partcipate in mouse-over so we can keep track of the order they were added in.

**Comment by anntzer** [comment]
That doesn't actually seem particularly difficult to fix (manually managing a list, or abusing OrderedDict to serve as an OrderedSet (using None as values)), *except* for the backcompat on Axes.mouseover_set.  I think the simplest is to deprecate manual manipulation of the mouseover_set (turning it into a private attribute) and just let people set the mouseover attribute of artists (essentially treating mouseover_set as an internal optimization of "what are the artists which have mouseover = True")
(Note by the way that direct manipulation of mouseover_set can result in an inconsistent state between whether an artist believes that its mouseover is set and whether the Axes has it in its mouseover_set; that can be problematic in the (certainly rare) case of removing and re-adding artists from the axes while manipulating mouseovers).

**Comment by tacaswell** [comment]
Thanks @anntzer !
