### ISSUE TITLE
Image in github repo does not match matplotlib.org (breaks image tutorial)

### ISSUE THREAD

**Issue by nbeaver** [matplotlib/matplotlib#11296]
The [image tutorial on matplotlib.org](https://matplotlib.org/users/image_tutorial.html) uses this sample image:

https://matplotlib.org/_images/stinkbug.png

and notes that it is a "24-bit RGB PNG image (8 bits for each of R, G, B)". However, further inspection reveals that it is *not* a 24-bit RGB, but rather an 8-bit grayscale image.

    $ curl -s 'https://matplotlib.org/_images/stinkbug.png' | file -
    /dev/stdin: PNG image data, 500 x 375, 8-bit grayscale, non-interlaced

However, the source image in the github repository *is* an RGB image:

    $ curl -s 'https://raw.githubusercontent.com/matplotlib/matplotlib/master/doc/_static/stinkbug.png' | file -
    /dev/stdin: PNG image data, 500 x 375, 8-bit/color RGB, non-interlaced

I noticed this because when I tried to follow the tutorial on my own machine, I kept on getting this error in line 7:

    In [7]: lum_img = img[:,:,0]
    IndexError: too many indices for array

This is because `imread` stores a grayscale image as an ndarray with only two dimensions, not three, as documented here:

> For grayscale images, the return array is MxN. For RGB images, the return value is MxNx3. For RGBA images the return value is MxNx4.

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imread.html

So `img.shape` ends up as `(375, 500)` when it should be `(375, 500, 3)`.

Let me know if I should file this here instead:

https://github.com/matplotlib/matplotlib.github.com/issues

**Comment by ImportanceOfBeingErnest** [comment]
@nbeaver Here is the correct place for such issues. :+1:  
A quick note: The page you refer to is an older version. The current version is available at http://matplotlib.org/tutorials/introductory/images.html  
This however shows the same issue indeed and I guess this is due to some mechanism in sphinx when including images.

**Comment by timhoffm** [comment]
This seems to be an issue only in the release docs. The current development snapshot is fine.

~~~
curl -s 'https://matplotlib.org/devdocs/_images/stinkbug.png' | file -
/dev/stdin: PNG image data, 500 x 375, 8-bit/color RGB, non-interlaced
~~~

So it's not a sphinx issue per se.

**Comment by ImportanceOfBeingErnest** [comment]
There is an option [`html_scaled_image_link`](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_scaled_image_link) which if set to false might result in this behaviour (as far as I understood). Maybe different builds use this differently?

**Comment by timhoffm** [comment]
We also have two versions: in `_static` and in `_images`. Not sure why.

Only the one at `https://matplotlib.org/_images/stinkbug.png` is grayscale.

**Comment by anntzer** [comment]
As a side note, the setup of the tutorial is a bit brittle: because the relative path to the image file is hardcoded, the tutorial file cannot, in fact, be run from the source tree (or a download) (it's probably not intended to be run directly anyways, but that sort of goes against the spirit of sphinx-gallery, I think?).

**Comment by QuLogic** [comment]
The release is not out yet, but there's no need to keep this open.
