### ISSUE TITLE
ConnectionStyle Angle3 hangs with specific parameters

### ISSUE THREAD

**Issue by toobaz** [matplotlib/matplotlib#11294]
### Bug report

**Bug summary**

I'm getting weird results from using ``ConnectionStyle.Angle3``. If I run 

```python
from matplotlib.patches import ConnectionStyle, FancyArrowPatch

conn_style_1 = ConnectionStyle.Angle3(angleA=0, angleB=180)
p1 = FancyArrowPatch((.2, .2), (.5, .5),
                             connectionstyle=conn_style_1)
plt.gca().add_patch(p1)
```

... the interpreter emits no sign of life except going to 100% of CPU usage until I kill it.

By the way, if I run

```python
from matplotlib.patches import ConnectionStyle, FancyArrowPatch

conn_style_1 = ConnectionStyle.Angle3(angleA=0, angleB=179)
p1 = FancyArrowPatch((.2, .2), (.5, .5),
                             connectionstyle=conn_style_1)
plt.gca().add_patch(p1)
```

I do get a line, but quite different from what I expected.

( xref #9518 , but I don't get any error)

**Actual outcome**

The second snippet results in

![weird_arrow](https://user-images.githubusercontent.com/1224492/40436022-4a107db4-5eb2-11e8-925a-55691d96f11a.png)

**Expected outcome**

Both snippets should give a similar result, with the curve reaching the second point from left, not from right.

**Matplotlib version**
  * Operating system: Linux
  * Matplotlib version: both git master and 2.0.0 from Debian
  * Matplotlib backend: both ``'module://ipykernel.pylab.backend_inline'`` and ``Qt5Agg``
  * Python version: 3.5.3
  * Jupyter version: 5.4.0

**Comment by ImportanceOfBeingErnest** [comment]
The question is a bit what do you expect from a second order Bezier curve with the control point at infinity? 

> [`ConnectionStyle.Angle3`](https://matplotlib.org/api/_as_gen/matplotlib.patches.ConnectionStyle.html#matplotlib.patches.ConnectionStyle.Angle3)  
Creates a simple quadratic bezier curve between two points. The middle control points is placed at the intersecting point of two lines which crosses the start (or end) point and has a angle of angleA (or angleB). 

The case `angleA=0, angleB=179` looks as expected.

So in that sense it might be useful to produce an error instead of letting the code try to workout the coordinates of infinity.

**Comment by toobaz** [comment]
> The case angleA=0, angleB=179 looks as expected. You cannot get a second order Bezier curve which changes the sign of its curvature. If that is desired, one would need to introduce a new ConnectionStyle based on third order Bezier curves.

Yep, sorry, I had completely misunderstood.

(The wording in the docs didn't help me... unless I'm still misunderstanding, I suggest to rephrase as "Creates a simple quadratic bezier curve between two points. The middle control point is placed at the intersection of two lines which cross the start and end point, and have a slope of angleA and angleB, respectively.")

**Comment by jklymak** [comment]
I think throwing an error or warning and adjusting to 179.9 or something non-infinite would be appropriate, but I've not looked at the code to see how easy such a check would be.  Improving the docs is always welcome as well!

**Comment by ImportanceOfBeingErnest** [comment]
I will take a closer look after the weekend; I think this should be easy to check.

**Comment by ImportanceOfBeingErnest** [comment]
See #11323 for a fix. This would now raise an error if the angles are equal or differ by exactly 180 degrees. 
I also changed the docstring as proposed above.

Is there still some interest in adding a new ConnectionStyle with two angles as input using a cubic Bezier instead of a quadratic one?

**Comment by toobaz** [comment]
> Is there still some interest in adding a new ConnectionStyle with two angles as input using a cubic Bezier instead of a quadratic one?

Can't speak in general, but personally, I was able to achieve what I was trying to achieve with a ``Path``, which ended up serving me better than a even a cubic Bezier ``FancyPatch`` would.

**Comment by ImportanceOfBeingErnest** [comment]
Ok, in that case, let's leave it as it is.
