### ISSUE TITLE
Get the z coord in event

### ISSUE THREAD

**Issue by mko010** [matplotlib/matplotlib#11309]
### Bug report

**Bug summary**

Matplotlib doesn´t allow get the z coord as event.zdata
**Code for reproduction**

    import matplotlib
    matplotlib.use('TkAgg')
    from tkinter import filedialog
    from tkinter import *
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
    from nibabel.loadsave import read_img_data
    from nibabel.loadsave import load as load_nii
    from viewers import OrthoSlicer3D
    from matplotlib.figure import Figure
    import numpy as np
    
    import sys
    if sys.version_info[0] < 3:
        import Tkinter as Tk
    else:
        import tkinter as Tk
    
    root = Tk.Tk()
    root.wm_title("Orthoslicer3D for brain segmentation")
    
    f = Figure()
    
    sagital = f.add_subplot(221)
    sagital.set_position([0,0,0.5,0.5])
    sagital.set_axis_off()
    
    coronal = f.add_subplot(222)
    coronal.set_axis_off()
    coronal.set_position([0,0.5,0.5,0.5])
    
    axial = f.add_subplot(223)
    axial.set_position([0.5,0.5,0.5,0.5])
    axial.set_axis_off()
    
    axes = (sagital, coronal, axial)
    
    
    # a tk.DrawingArea
    canvas = FigureCanvasTkAgg(f, master=root)
    canvas.get_tk_widget().pack(side=Tk.RIGHT, fill=Tk.BOTH, expand=1)
    
    toolbar = NavigationToolbar2TkAgg(canvas, root)
    toolbar.update()
    canvas._tkcanvas.pack(side=Tk.RIGHT, fill=Tk.BOTH, expand=0)
    
    def _load():
        data = filedialog.askopenfilename(initialdir = "/", title = "Select file", filetypes = (("nii files","*.nii"),("gz files", "*.gz"),("all files","*.*")))
        data_load = load_nii(data)
        data_read = read_img_data(data_load)
        data_read = np.asanyarray(data_read)
        OrthoSlicer3D(data_read, axes=axes).show()
    
    
    coords = []
    
    
    def _onclick(event):
        coords.append((event.xdata, event.ydata, event.zdata))
        return coords
    
    canvas.mpl_connect('button_press_event', _onclick)
    
    buttonLoad = Tk.Button(master=root, text='Load', command=_load)
    buttonLoad.pack(side=Tk.LEFT, expand = 1)
    
    Tk.mainloop()

**Actual outcome**

TypeError: <lambda>() missing 1 required positional argument: 'z'

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.5
  * Jupyter version (if applicable):
  * Other libraries: 

I have installed matplotlib from pip and python from source.

**Comment by WeatherGod** [comment]
Could you include the full traceback, please?

**Comment by mko010** [comment]
Traceback (most recent call last):
  File "C:\Users\migue\Documents\IM\TFG\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "C:\Users\migue\Documents\IM\TFG\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "C:\Users\migue\Documents\IM\TFG\venv\lib\site-packages\matplotlib\backend_bases.py", line 2888, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
TypeError: <lambda>() missing 1 required positional argument: 'z'

**Comment by WeatherGod** [comment]
Ok, the traceback shows that the problem isn't with _onclick(), it is
mouse_move. Also, the code for reproduction is incomplete. The FIgure class
is never imported and it seems like you are dealing with axes3d objects,
but you never specify them. I think the problem lies somewhere in how you
are constructing your figure and event handling, but I can't tell without a
true minimal working example demonstrating the problem.

**Comment by mko010** [comment]
there the complete code

**Comment by mko010** [comment]
Well, I need the x, y and z data, from navigation toolbar for draw that points into the image, then How can I do that?

**Comment by ImportanceOfBeingErnest** [comment]
One possible option is shown in [this Stackoverflow question](https://stackoverflow.com/questions/50283031/matplotlib-ax-format-coord-in-3d-trisurf-plot-return-x-y-z-instead-of-az). A cleaner solution would of course simply replicate the code from [`format_coords`](https://github.com/matplotlib/matplotlib/blob/8168210211c598f32f683084460b104a3fe2255c/lib/mpl_toolkits/mplot3d/axes3d.py#L1157).

**Comment by mko010** [comment]
But that solution use a fig.gca, and I need use subplots, because otherwise Orthoslicer doesn't work

**Comment by ImportanceOfBeingErnest** [comment]
You can replace `fig.gca()` by any `axes` object you like.

**Comment by ImportanceOfBeingErnest** [comment]
That `[91]` seems to be from a 2D plot, like `imshow`. A 3D matplotlib plot would show `z=91`. But, yes, that is exactly how the linked [stackoverflow question](https://stackoverflow.com/questions/50283031/matplotlib-ax-format-coord-in-3d-trisurf-plot-return-x-y-z-instead-of-az) does it.

**Comment by mko010** [comment]
`AttributeError: 'AxesSubplot' object has no attribute 'button_pressed'`

**Comment by ImportanceOfBeingErnest** [comment]
Note that the matplotlib issue tracker is not a personal help desk. If you think that there is a bug in matplotlib, a minimal runnable example is required. 
Also note that one cannot give support for some third party package like Orthoslicer here.

**Comment by mko010** [comment]
I know and I'm sorry

**Comment by WeatherGod** [comment]
The mailing list might be a better place to continue this discussion.
