### ISSUE TITLE
Ways to improve the documentation search results

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#11315]
The search summary contains excerpts of the .rst sources. ReST code elements tend to clutter the summary, making it hard to find useful information within. 

![grafik](https://user-images.githubusercontent.com/2836374/40577376-ecf645d2-6104-11e8-976b-094530844e84.png)

Sphinx itself wants to target this in the long run, but I think that will not be anytime soon. There are two ways to work around this.

## sphinx-pretty-serachresults plugin

The plugin [sphinx-pretty-serachresults](https://pypi.org/project/sphinxprettysearchresults/) additionally builds a text version of the docs and uses this in the search results.

- (++) Optimal results.
- (+) Simple to integrate.
- (-) additional dependency. But it's only need for building the docs, so I think it's ok.
- (-) increases the size of the built docs by 87MB due to the additional text files.
- (--) does an additional complete sphinx run to build the text version (essentially doubles documentation build time). Is it maybe possible to do this conditionally only for release builds? (One would have to know in `conf.py` and then can conditionally include the plugin.)

## Filter result texts

Another approach is filtering the bad stuff out from the displayed string in javascript. I had a prove-of-concept at https://github.com/sphinx-doc/sphinx/pull/4857.

- (+) Better readable results, but may still contain some ReST elements (see the above PR for an example). This also depends on how much effort one puts into the filter.
- (+) No overhead at documentation build time. Search times are not significantly increased by filtering (< +1%).
- (-) Need a way to inject the javascript filter. Unfortunately the idea of including this directly into Sphinx was rejected. There is no way to inject the code in the currently released Sphinx versions. However, I think it would be possible to add such an interface via a quite straight-forward PR to Sphinx. There are already hooks available for customizing stemming, splitting and scoring. So we'd just have to expand that interface for another method.

I have working versions of both ways. They are feasible, but have the stated advantages/disadvantages.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/10573/files for "if a final version".
Would prefer the solution to come from sphinx itself; from a quick look at their tracker it doesn't seem like they're unwilling to consider PRs.

**Comment by timhoffm** [comment]
Yes, they are willing to accept PRs, but I assume that implementing this in sphinx properly is not trivial.

There is:

- https://github.com/sphinx-doc/sphinx/pull/4857#issuecomment-387419166 suggests that `shpinx-build` should build HTML and Text together. Not sure if this is meant (a) sequential (and this no different from  `sphinx-pretty-serachresults` in terms of performance penality) or if this is (b) parallel (which may not be so easy).
- https://github.com/sphinx-doc/sphinx/issues/1618#issuecomment-324424096 proposes to get the contents from HTML. No idea how complicated that would be as I'm not a javascript genius.
