### ISSUE TITLE
Really deprecate Patches.xy?

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#11322]
Part of #11299 deprecates the property `Patches.xy`.

I assume this was based on the existing docstring

> Set/get the vertices of the polygon.  This property is
provided for backward compatibility with matplotlib 0.91.x
only.  New code should use
:meth:`~matplotlib.patches.Polygon.get_xy` and
:meth:`~matplotlib.patches.Polygon.set_xy` instead.

That docstring is 10 years old, and I'm not sure if we really want to deprecate the property. In many places I would actually favor properties over getters/setters.

**Comment by anntzer** [comment]
I'm fine with restoring it.  But please remove the docstring then :)

**Comment by ImportanceOfBeingErnest** [comment]
This is surely one of the many cases where independent of what the docs say, people are just using it. Hence when removing such property/attribute that people do use, there should be some reason to do so. 

Is there any such reason? If not, I would personally also favour keeping it.

**Comment by tacaswell** [comment]
:+1: on un-deprecating and changing the doc-string as required.
