### ISSUE TITLE
'ipython --pylab' crashes on exit when using Qt5Agg backend

### ISSUE THREAD

**Issue by AgilentGCMS** [matplotlib/matplotlib#11346]
### Bug report

**Bug summary**

I recently installed matplotlib on Ubuntu 18.04. Since python-pyqt5 is in the repository, I thought I'd try out the Qt5Agg backend for matplotlib. However, when I do that and open a figure, ipython crashes on exit. Actually, the python process hangs and has to be killed with SIGKILL. This does not happen if in the same installation I use the Qt4Agg backend.

**Code for reproduction**

```
$ ipython --pylab
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
Type "copyright", "credits" or "license" for more information.

IPython 5.7.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: Qt5Agg

In [1]: figure()
Out[1]: <Figure size 864x648 with 0 Axes>

In [2]: exit()
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python2.7 path = /usr/bin pid = 2182
KCrash: Arguments: /usr/bin/python2.7 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/32969/kdeinit5__0

[1]+  Stopped                 ipython --pylab
```

**Actual outcome**

The only way to stop python after that is with 
```
$ killall -9 ipython
[1]+  Killed                  ipython --pylab
```
However, using the Qt4Agg backend does not cause this problem.

**Expected outcome**

exit() should be able to terminate the ipython process normally.

**Matplotlib version**

  * Operating system: Ubuntu 18.04 LTS
  * Matplotlib version: 2.2.2
  * Matplotlib backend: Qt5Agg
  * Python version: 2.7.15rc1
  * Jupyter version (if applicable): N/A

I installed matplotlib from source.

**Comment by timhoffm** [comment]
Note to narrow this down: Works with Python 3.6.4 on Ubuntu 17.10.

**Comment by timhoffm** [comment]
Closing as non reproducible in current Matplotlib 3.2.2. Please reopen if this is still an issue.
