### ISSUE TITLE
Animating circles sometimes skews them to ellipses

### ISSUE THREAD

**Issue by vandenheuvel** [matplotlib/matplotlib#11359]
### Bug report

**Bug summary**

Animating circles sometimes skews them to ellipses. Saving an image shows redrawings without clearing screen.

**Code for reproduction**

```python
from itertools import product

from matplotlib import pyplot
from matplotlib.animation import FuncAnimation
from numpy.ma import arange


class DrawClass:
    def __init__(self, axis):
        self.axis = axis
        self.fig = None

    def init(self):
        self.axis.set_xlim(0 - 0.5, 3 + 0.5)
        self.axis.set_ylim(0 - 0.5, 3 + 0.5)
        pyplot.axis("equal")

        background = list()
        for (x, y) in product(range(3), range(3)):
            color = 'w' if (x + y) % 2 == 1 else (0.8, 0.8, 0.8)
            s = pyplot.Rectangle((x - 0.5, y - 0.5), 1, 1, fc=color)
            pyplot.gca().add_patch(s)

        return background

    def __call__(self, frame):
        fraction = frame / 10
        c = pyplot.Circle((fraction, 1), radius=0.5, fc='r')
        pyplot.gca().add_patch(c)

        return c,


if __name__ == "__main__":
    figure, axis = pyplot.subplots()

    drawer = DrawClass(axis)
    animation = FuncAnimation(figure,
                              drawer,
                              frames=arange(10),
                              init_func=drawer.init,
                              interval=round(100),
                              blit=True)

    pyplot.show()

```

**Actual outcome**
When using the save function:
![figure_1-1](https://user-images.githubusercontent.com/20440137/40835997-7b8d036e-6595-11e8-9f88-480797f77888.png)
When screenshotting:
![screenshot from 2018-06-01 12-16-52](https://user-images.githubusercontent.com/20440137/40836086-c862a14e-6595-11e8-83e2-d27a1280a6e5.png)
This is also what I'm actually seeing.

**Expected outcome**
A normal, clean circle like this:
![figure_1](https://user-images.githubusercontent.com/20440137/40836104-d8208272-6595-11e8-854d-605a8ee824b4.png)

**Matplotlib version**

  * Operating system: Arch Linux 4.16.12-1, gnome with wayland
  * Matplotlib version: 2.2.2-2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.5-3

Installed using Arch's package manager pacman.

**Comment by ImportanceOfBeingErnest** [comment]
Those are two different issues. 

* Use `blit=False` to see how the saved version would look like. You see many circles here, because you add many circles to the axes. If that is not desired, only add a single circle and update its position instead.

* The circle appearing as an ellipse is due to the patches added inside the init function after setting the axis limits. 

A correct version of the code would look like

```
from itertools import product

from matplotlib import pyplot
from matplotlib.animation import FuncAnimation
from numpy.ma import arange


class DrawClass:
    def __init__(self, axes):
        self.axes = axes
        self.fig = None

    def init(self):
        background = list()
        for (x, y) in product(range(3), range(3)):
            color = 'w' if (x + y) % 2 == 1 else (0.8, 0.8, 0.8)
            s = pyplot.Rectangle((x - 0.5, y - 0.5), 1, 1, fc=color)
            self.axes.add_patch(s)
        
        self.c = pyplot.Circle((0, 1), radius=0.5, fc='r')
        self.axes.add_patch(self.c)
        self.axes.set_xlim(0 - 0.5, 3 + 0.5)
        self.axes.set_ylim(0 - 0.5, 3 + 0.5)
        self.axes.axis("equal")
        return background

    def __call__(self, frame):
        self.c.center = frame / 10., 1
        return self.c,


if __name__ == "__main__":
    fig, ax = pyplot.subplots()
    
    drawer = DrawClass(ax)
    drawer.init()
    animation = FuncAnimation(fig,
                              drawer,
                              frames=arange(10),
                              interval=round(100),
                              blit=True)

    pyplot.show()
```

**Comment by vandenheuvel** [comment]
That appears to work. Thank you!

**Comment by vandenheuvel** [comment]
@ImportanceOfBeingErnest While I still don't understand the precisely reason for the skews, I found a fix: creating the figure and setting the aspect ratio as a property of a subplot.

**Comment by tacaswell** [comment]
By default the ratio of (1 unit of xdata is screen space) : (1 unit of ydata in screen space) is not constrained so your circle in data-space may become a ellipse.  Setting the aspect to 'equal' constrains that ratio to be 1 so your circle displays as a circle.
