### ISSUE TITLE
DOC: Really add an arrow tutorial

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#11350]
In #11219 and #11223 @dstansby headed out to provide an arrow tutorial. Since the scope of this was rather limited, it ended up as an example [examples/shapes_and_collections/arrow_guide.py](https://matplotlib.org/devdocs/gallery/shapes_and_collections/arrow_guide.htm) - which is great. 

However as mentionned in this PR #11223 there are a lot of other things to consider about arrows. In the end it would be good to have something like a complete "Arrow tutorial". I'm collecting the comments in this thread for them not to get lost, once someone has more time to write this up.

There currently are already the [annotation_demo](https://matplotlib.org/gallery/text_labels_and_annotations/annotation_demo.html) example and the [annotations](https://matplotlib.org/users/annotations.html) tutorial. So I wonder in how far they are overlapping or not. Independent of that, there should be links in between them.

In addition, the following things should be considered when writing :

* what is the relation between `ax.arrow`, `ax.annotate`, `ax.quiver`, `mpatches.FancyArrowPatch`? 
* Any user looking at the `patches` doc would directly ask: "What is the difference between `Arrow`, `FancyArrow`, `FancyArrowPatch` and `YAArrow`?" A tutorial might want to answer this.
* The problem when drawing arrows is mostly to understand all the different parameters. Common questions could be 
  * How to make the head larger?
  * What are the units of `head_length`, `head_width`, `tail_width`, `mutation_scale`,  etc.?
  * Why is my arrow shorter than the distance between the two points I specified?
  * Why can't I use an `FancyArrowPatch` in a collection? What's the alternative? (should be checked when deprecating other arrows)
  *  How do I draw an arrow with a dotted tail?
  * When should I use a `ConnectionPatch` instead of a `FancyArrowPatch`?
* Is the [arrow_demo](https://matplotlib.org/3.0.0/gallery/text_labels_and_annotations/arrow_demo.html) useful? Can it be replaced by something simpler? Definitely explain `plt.arrow`'s `length_includes_head` and possibly `head_starts_at_zero` -> #12768
* Apperently it's not possible to get an arrow with a bolder connection path in the middle and two arrow heads on both sides? ([This SO question](https://stackoverflow.com/questions/57642971/how-to-create-filled-in-default-style-double-ended-arrows-with-matplotlib?noredirect=1#57642971)) Need to check.

**Comment by Adrien-Luxey** [comment]
I'm currently struggling with `FancyArrowPatch`'s `path` parameter, which essentially disables a lot of heavy-lifting done by this class when called with `posA` & `posB`. My concrete problem is that `shrinkA` & `shrinkB` parameters are not interpreted using `path`; however I can't reproduce their behavior using NetworkX (the arrow head ends up under the vertex the arrow is pointing to).
