### ISSUE TITLE
Unable to retrieve marker from legend handle

### ISSUE THREAD

**Issue by kdcurry** [matplotlib/matplotlib#11357]
### Bug report

**Bug summary**

I created a plot then manually created a legend to match the plot. When retrieving the handles from the legend object, get_marker() returns and empty string even when that is not the correct marker.

**Code for reproduction**

```python
# Paste your code here
#
```
<img width="578" alt="screen shot 2018-05-31 at 2 58 10 pm" src="https://user-images.githubusercontent.com/4032126/40808012-1937f596-64e3-11e8-86e5-192bd2dd203e.png">
<img width="333" alt="screen shot 2018-05-31 at 2 58 21 pm" src="https://user-images.githubusercontent.com/4032126/40808016-1ad192c2-64e3-11e8-9a0a-f3527f73e7c1.png">

**Expected outcome**

Expected output is 'v' rather than ''

**Matplotlib version**

  * Operating system: mac OS X El Capitan
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version:  3.6.4 
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

conda

**Comment by afvincent** [comment]
A copy-pastable version of the example reported by @kdcurry (thanks for the ticket :) )
```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

fig, ax = plt.subplots()

s = ax.scatter([0, 1], [0, 1], marker="v")
handles = [Line2D([0], [0], marker="v", ls="")]
leg = ax.legend(handles, ["a"])

print("'" + handles[0].get_marker() + "'")  # -> 'v'
print("'" + leg.legendHandles[0].get_marker() + "'")  # -> ''

fig.show()
```

**Comment by ImportanceOfBeingErnest** [comment]
I suppose the reason the line is separated from the markers inside the `HandlerLine2D` is that you have the option to create more than one marker via the `numpoints`  argument. I.e. `ax.legend()` produces
![image](https://user-images.githubusercontent.com/23121882/40815008-e338bf46-6543-11e8-8455-43386d69a610.png)
while `ax.legend(numpoints=3)` produces 
![image](https://user-images.githubusercontent.com/23121882/40815024-f8f029a0-6543-11e8-85d0-92fb5fd3c792.png)

**Comment by afvincent** [comment]
I may have a not-very-nice “fix”. Let's see if I manage to put everything into a PR.

**Comment by kdcurry** [comment]
Ok, so there is currently no way of retrieving a marker type from a legend handle if the legend handle is of type PathCollection? I was able to retrieve the marker when legend handles were of type Line2D.

On a similar note, I am noticing when I retrieve the linestyle from a legend handle of type Line2D, the linestyle is always returning type '--'.

`import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import geopandas as gpd
import shapely


fig, ax = plt.subplots()
line = gpd.GeoSeries(shapely.geometry.linestring.LineString(((0,0),(1,1))))
line.plot(ax = ax, label = 'line', linestyle = ':')
ax.legend()`

**Comment by ImportanceOfBeingErnest** [comment]
One way of getting the marker from a legend is [this one](https://github.com/matplotlib/matplotlib/pull/11358#issuecomment-393997899), 

    ax.get_legend()._legend_handle_box.get_children()[0].get_children()[0].get_children()[0].get_children()[1].get_marker()

but it's of course not the intended way to let users dig their way through the legend packers.

Concerning geopandas, do we need to check if the proposed fix #11358 breaks something for them?

**Comment by kdcurry** [comment]
I don't think the fix broke something with geopandas, I think this is a separate but similar issue? But I may be wrong.

Thanks for looking into this!

**Comment by kdcurry** [comment]
@afvincent @ImportanceOfBeingErnest 
I am working to develop a course at the University of Colorado, Boulder. My goal is to set up an entirely automated grading system for Matplotlib plots. We love the flexibility and ease that Matplotlib offers and want to continue spreading this knowledge to students!

The reason I want to retrieve markers, linestyles, and other attributes from legend handles is to test legend accuracy. I would like to accept both  Matplotlib generated legends and custom legends as long as the data correlates with the legend accurately. I am currently taking attributes from the legend handles and testing that these attributes match the expected data on the plot (which is how I ran into the issues stated above). Is there a better method that is already imbedded in the Matplotlib library to achieve this goal? If not, do you believe it is better to dig into legend packers as @ImportanceOfBeingErnest  has shown above rather than legend handles? My concern is that different methods of producing similar looking plots will produce different levels of “children.”

I really appreciate any feedback or guidance you may have! Thank you! @lwasser

**Comment by lwasser** [comment]
Thanks all! We are working with some of the jupyter team to build a platform that allows for scalable courses. We offer many courses online at no cost (see earthdatascience.org) but also want teach more students online. Our goal is to build modular tools to autograde plots (and other homework assignment elements) that others may also benefit from - following up on and supporting some of the work underway at Berkley. We'd really truly appreciate any guidance you have with respect to building tools to test matplotlib plots @kdcurry mentioned above.

**Comment by ImportanceOfBeingErnest** [comment]
Well, you may get a similar looking legend by all kinds of different means, and yes, the `get_children` method above will surely fail in case the legend has columns or inverted the order of text vs. handle etc.

My personal opinion: Don't compress students' work into automated grading scemes. University is meant  to guide people into solving their problems. You can only know if a certain plot fulfills the requirement by looking at it, not by examining it's code structure.

**Comment by lwasser** [comment]
gotcha! we were just hoping to be able to offer more free and open courses that could support more students who can't afford to pay for university credits. We can't guide them all however, unfortunately but some feedback can have  a strong impact. It sounds like that may not be possible however given all of the potential ways to create a legend and a plot! Perhaps we need to test the data object rather than the plot. Thanks @ImportanceOfBeingErnest   we appreciate your input!

**Comment by ImportanceOfBeingErnest** [comment]
This gets totally off-topic now. Very quick idea on how I would do it: Provide students a list of expectations (in German we'd call that "expectation horizon") and let them mark their work themselves, or let them mark their collegues' work.

**Comment by kdcurry** [comment]
Thanks for all your help @ImportanceOfBeingErnest !

**Comment by lwasser** [comment]
thanks @tacaswell looks like this may have been addressed. i will look into the merge and our package to see if it's now easier to grab markers! i am so appreciative of all of the effort that goes into matplotlib. thank you maintainers!
