### ISSUE TITLE
Warning: Cannot change to a different GUI toolkit: notebook. Using qt instead.

### ISSUE THREAD

**Issue by parejkoj** [matplotlib/matplotlib#11365]
### Bug report

When I try to use the jupyter notebook `%matplotlib notebook` magic command on Linux (as the first command executed in the notebook), I get this warning:

```
Warning: Cannot change to a different GUI toolkit: notebook. Using qt instead.
```

Plots then appear a separate qt window, outside the browser. The `%matplotlib inline` command does work.

This occurs in freshly-opened jupyter notebooks, with a fresh kernel.

  * Operating system: Ubuntu 16.04/18.04
  * Matplotlib version: 2.1.1
  * Python version: 3.6.3
  * jupyter (1.0.0)
  * jupyter-client (5.2.3)
  * jupyter-console (5.2.0)
  * jupyter-core (4.4.0)
  * notebook (5.5.0)

LSST miniconda:
https://github.com/lsst/lsstsw/blob/master/etc/conda3_packages-linux-64.txt

I've since upgraded matplotlib and jupyter to attempt to remedy this, but upgrading didn't change the error.

**Comment by jklymak** [comment]
Do you have something set in your matplotlibrc?

**Comment by tacaswell** [comment]
How are you starting the notebook server?

**Comment by parejkoj** [comment]
> Do you have something set in your matplotlibrc?

I don't have a personal matplotlibrc. Is there a system one I should check for?

> How are you starting the notebook server?

`jupyter notebook` from a terminal.

**Comment by hmaarrfk** [comment]
Is there a reason why we can't change backends on the fly? It is super useful at times.

**Comment by hmaarrfk** [comment]
@jklymak Wow thanks for letting me know about that! Pretty awesome!

**Comment by jklymak** [comment]
#12608 is the PR...

**Comment by tacaswell** [comment]
> Is there a reason why we can't change backends on the fly? It is super useful at times.

You can end up with conflicting event loops, changing the backend changes some module level state in `pyplot`, different GUIs need different input hooks to be interactive at the prompt, and there is state in `Gcf`.  If any of it gets out of sync with the rest things get very broken very fast in ways that are very hard to reproduce / communicate via github issue.  Even though we think it works now (including checks that you won't go to a known-broken state), it is better not to....

**Comment by hmaarrfk** [comment]
Hmm interesting. Yeah, even programming is tough.

I guess I'm ok with working in a jupyter notebook. then maybe outputting to QT for a bit, closing all my figures, and outputting again to the notebook.

**Comment by jklymak** [comment]
#12608 should not allow two GUI backends to be used if one of them has already been started.  So its not totally "on-the-fly"

**Comment by tacaswell** [comment]
I discourage using the native GUI backends inside of notebooks / jlab.  That relies on the fact that your server is running locally so the windows pop-up in the right place.  The biggest selling point (for me) of Jupyter is that you can run the kernels somewhere else (which gets you 0 install, access to big compute, and locality with data storage (I am very much wearing my "I work at a user facility" hat)).  Better to not get bad habits that won't transfer well.....

**Comment by hmaarrfk** [comment]
@tacaswell I guess I often crash my browser when viewing and interacting with images. Native backends are often unavoidable :/. 4K screens, large images, are challenging to deal with :/

**Comment by astromancer** [comment]
I had this warning come up recently after adding the line 
`c.InteractiveShellApp.gui = 'qt5'` 
in my `ipython_config.py` file.  Commenting out this line removed the warning.

**Comment by pspiagicw** [comment]
Is this issue resolved in the new versions ?

**Comment by tacaswell** [comment]
This should be lazier now and there is an open PR (https://github.com/matplotlib/matplotlib/pull/22005) to make it even lazier.
