### ISSUE TITLE
setting default figsize with pyplot.rc in same (jupyter/ipython) cell of matplotlib import does not work

### ISSUE THREAD

**Issue by soxofaan** [matplotlib/matplotlib#11393]
### Bug report

**Bug summary**

I try setting the default figsize with `matplotlib.pyplot.rc` in the same jupyter/ipython cell I did the import of matplotlib, but that does not work. If it's in separate cells it does work

**Code for reproduction**

In same cell:
<img width="435" alt="screen shot 2018-06-07 at 12 34 49" src="https://user-images.githubusercontent.com/44946/41094840-e6ddfbfa-6a4f-11e8-9f7c-b2ba353870a7.png">

- Note that `plt.rcParams['figure.figsize']` returns `[6.0, 4.0]` instead of expected `[12.0, 6.0]`.
- Note it did work for the line width
- Same result if I switch the `plt.rc` calls

In different cell:
<img width="454" alt="screen shot 2018-06-07 at 12 35 10" src="https://user-images.githubusercontent.com/44946/41094893-1a8321f6-6a50-11e8-9e0d-c5c7ab5ed5dd.png">
Here it works as expected

**Matplotlib version**

  * Operating system: OS X Darwin 17.5.0 i386
  * Matplotlib version: 2.0.2
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 2.7.15.final.0 (anaconda distribution, default channels)
  * Jupyter version: Jupyter notebook 5.5.0, IPython 5.7.0

**Comment by ImportanceOfBeingErnest** [comment]
Seems to be the same issue as 
* https://github.com/ipython/ipython/issues/11098
* https://github.com/jupyter/notebook/issues/3385

 and I suspect that IPython or Jupyter is really the place to look for the cause of this; I doubt that matplotlib can do anything about it at all.

**Comment by jklymak** [comment]
I’ll close in lieu of those issues but please feel free to ask to reopen if you think error in our court.  I also think not too hard to workaround.

**Comment by soxofaan** [comment]
@ImportanceOfBeingErnest Thanks for the references. 

@jklymak  Yes, probably better to close, I'll move to these ipython/jupiter issues

**Comment by itku8531** [comment]
I use Spyder and run into the same issue. The problem showed up often (the size didn't change). I run the code 10 times and got it to work ONE time even I didn't change anything ... really frustrated. BUT I found instead using 

`plt.subplot(7,3,j+1)`
`plt.rcParams['figure.figsize'] = [4, 3]`  <<< to change individual imagine size, I used

`plt.subplot(7,3,j+1)`
`plt.gcf().set_size_inches(12, 21, forward=True)`   <<< to change the overall output plot size. 

I was able to get what I want by this way (can see the compared plots below). Hope this can help someone.
Bad plot:
![CSM_Pairs_RF02_example_1](https://user-images.githubusercontent.com/71041437/106989072-8c018b00-672e-11eb-9e43-554ae0f7c9e1.jpg)
Good plot:
![CSM_Pairs_RF02_example_2](https://user-images.githubusercontent.com/71041437/106989080-915ed580-672e-11eb-824c-43d05379af23.jpg)
