### ISSUE TITLE
Incorrect x-axis when plotting an array

### ISSUE THREAD

**Issue by rocapp** [matplotlib/matplotlib#11414]
Matplotlib 2.2.2
Ubuntu 16.04
Python 3.6.1

Notice the array minimum and maximum.
![codempl](https://user-images.githubusercontent.com/9521583/41213963-8a6cdd4a-6d16-11e8-8131-31080693cddc.png)

The resulting plot is then:
![plotmpl](https://user-images.githubusercontent.com/9521583/41213977-a9001e7a-6d16-11e8-8ac5-7c1316beca75.png)

The x ticks should correspond to the array min and max, but they don't.

**Comment by QuLogic** [comment]
They do; there's an offset subtracted from all ticks. That's what the `+1e3` in the bottom right corner is.

**Comment by rocapp** [comment]
Oh, whew. That's actually a huge relief. I thought that was supposed to be a multiplicative scaling... 
Thanks!
