### ISSUE TITLE
Adding Binder links to the Matplotlib gallery

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#11415]
Hey all - we recently added a nifty new feature to `sphinx-gallery` that automatically generates Binder links for each sphinx gallery example. See the sphinx gallery docs as an example:

https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/sin_func/plot_sin.html#sphx-glr-auto-examples-sin-func-plot-sin-py

I think it'd be cool if we had this for Matplotlib (e.g. each example would have a "launch binder" button at the bottom that could open an interactive version of the example for users).

However, there are a few caveats here:

1. Matplotlib docs get a *ton* of users, and this might have unexpected results on `mybinder.org` if a gigantic influx of people happens. At the least, we'd likely hit the per-repo limit of 100 concurrent Binder sessions.
2. Binder is still in beta (e.g. it won't have 100% uptime, though is pretty close to this, and may occasionally drop off if we have an outage)

That said, it'd be pretty cool if each of our users was one click away from interacting w/ the matplotlib examples on each page.

What do folks think about this? If we're +1 giving it a shot, I can put together a PR activating the Binder links on the matplotlib docs.

**Comment by ImportanceOfBeingErnest** [comment]
What happens if the limit is reached? Who maintains [mybinder.org](https://mybinder.org); would the use of this feature be within their envisionned use cases? 

From the matplotlib side one could make this an experimental feature, like

![image](https://user-images.githubusercontent.com/23121882/41243913-cea003e2-6da3-11e8-8658-a8233423efd7.png)

and see what happens?

**Comment by choldgraf** [comment]
When the limit is reached binder will display a message saying that the limit is reached for the repository. There's a chance that a gigantic influx of traffic would overwhelm the binder servers and the site would go down, though I think this is small. In that case, we'd remove the binder links from the matplotlib docs.

Re: Binder's envisioned use case, I can confirm that interactive documentation is one of the envisioned use-cases, yes :-)

When is the next release planned? One thing we could do is implement this PR at the beginning of a cycle, and then it's only exist in the `/latest` URL as a test run

**Comment by ImportanceOfBeingErnest** [comment]
In general there is of course a problem with those notebooks generated via sphinx-gallery: There is no control over whether a notebook is to be created/linked to by a certain example. This is important because many examples do not run in `%matplotlib inline` mode. 

So ideally one would have a directive flagg to set whether an example should (not) contain a notebook and even better, whether that example should use `%matplotlib notebook` instead of `inline`.  
This then quickly leads to even more general problems with sphinx-gallery which has no way to hide code/comments/directives from the output. 

In that sense one might also question in how far one should provide non-runnable notebooks to users.

**Comment by jklymak** [comment]
Binder doesn't appear to work with `%matplotlib notebook`.  What examples don't work in `inline`?  We should proabbly start noting that in the example somewhere.  A flag would be cool, if there is an easy way to impliment.  Not sure what metadata we can enter into the examples as they are...

**Comment by ImportanceOfBeingErnest** [comment]
> What examples don't work in inline? 

Well obviously all examples from the sections "Animation", "Widgets" and "Embedding" and I suppose others as well which use `.draggable()` or similar stuff.

> Not sure what metadata we can enter into the examples as they are.

Currently none. Everything written in those files appears in the output, like e.g. `# sphinx_gallery_thumbnail_number = 18` in the constrained_layout guide.

<hr> 

What's important really is the question: What would weight more, 
* user excitement, being able to run most of the examples (not all as stated above) sometimes (if traffic is low enough) online; 
* or user frustration, not being able to run a certain example at a certain point in time.

I'm personally undecided here, but those points may help people come to a conclusion.

**Comment by choldgraf** [comment]
Some quick thoughts:

1. Binder should work fine with `%matplotlib notebook`. Which example didn't work for you @jklymak ?
2. We could try and merge something into sphinx-gallery that calls "%matplotlib notebook" instead of "inline" with a flag, though this may be unnecessary complexity
3. My 2 cents is that some interactivity is better than no interactivity

**Comment by jklymak** [comment]
`JavaScript output is disabled in JupyterLab`

**Comment by choldgraf** [comment]
ah - I think that just means that an extension hasn't been enabled for JupyterLab on that Binder build. It works with the Noteboook UI

**Comment by jklymak** [comment]
I just followed the links.  No sure what the Notebook UI is.  

FWIW, I'm not 100% against this, but I think most users would be better served by downloading the code and running locally versus running in a remote instance.  At some point they are going to want to run matplotlib locally, unless we are trying to send people to binder as a one-stop shop for data analysis.  I'm not seeing the benefit of making this run remotely.

**Comment by timhoffm** [comment]
While generally it would be nice to be able to tinker with the examples online, I'm sceptical that we should hook to binder in it's current state.

A feature that's not yet reliably working is creating frustration for the user. That would have to be sorted out before.

- Wait till binder is out of beta for stability of service.
- Do we have example download statistics? That would be a hint on the expected traffic on binder (though the interactive examples would probably be used more often by some factor).
- Check with the mybinder operators if the traffic is ok.
- 100 sessions seems quite little, given that probably many people will keep the example open in their browser even when not working on it directly. Is there a timeout?. If the session limit is reached most of the time, the feature is basically unusable.
- Apart from the technical limitations, we'd also have to make sure that the examples really work. Probably start with a white-list. (That would also help controlling the initial amount of traffic.)

**Comment by ImportanceOfBeingErnest** [comment]
I do see the point of letting people run examples on the fly. This has something to do with being inviting and inclusive. People visiting matplotlib.org can directly try out how great this works by running some example and changing the color to "red" - "Oh wow, this is easy, I need that for my project." 

... and that is exactly the problem when it comes to this feature only working sometimes or not at all when choosing a non-compatible example. Then it's more "Oh, this doesn't work, I can't even change the color to "red"; let's take some other library instead."

Maybe a whitelist like @timhoffm just mentions is a good start; One could advertise a couple of examples to try out on the main page and make sure those are running fine.

**Comment by choldgraf** [comment]
a few thoughts:

* Right now within sphinx gallery I don't think it's possible to include a white list for Binder links, but this might be something worth adding.
* My intuition is that the *vast* majority of people will never run examples locally on their computer (e.g. most people just `pip install matplotlib` and never know where the examples are located on their machine). I think a lot more people would click on interactive links on the web.
* It'll probably be a loooong time before Binder is ever "officially" out of Beta (we're doing sort of a gmail-style "beta forever" model for Binder)
* re: user session destroying, yep we delete user sessions after periods of inactivity (fairly aggressively, the goal of Binder is to have short interactive sessions in general)
* re: examples really working, anything that's not tagged `sgskip` should work fine in the Binder environment, provided that the repo is set up with the same environment that sphinx-gallery+CircleCI uses when it runs the examples

(full disclosure here - I'm on the sphinx gallery team as well as the Binder team, so we could probably make some additions to one or another project if it'd be valuable here)

**Comment by jklymak** [comment]
> My intuition is that the vast majority of people will never run examples locally on their computer (e.g. most people just pip install matplotlib and never know where the examples are located on their machine). I think a lot more people would click on interactive links on the web.

Users must run some code locally, at some point in their careers.  Presumably some of it is cut and paste from the examples, and/or downloaded from the examples pages.  I'm not seeing how going to binder to run the example is better than doing it locally if I want to play with the examples, unless I don't already have a python/matplotlib environment installed.  But even if I didn't, I'm not getting the long-term use case for a newbie to start using binder.  Why should we, as a package, be guiding people there?

**Comment by tacaswell** [comment]
I am :+1: on this in principle.  Reducing the friction of 'let me play with this' to clicking a link is definitely a good thing!

Is ipympl installed in the binder images?  If so `%matplotlib widget` should work and give you interactive figures under jupyter lab.

We do run all of the examples as part of building the docs so we know that they are at least valid python and produce reasonable output.  The best way to get feedback on which versions of the notebooks work is to open them up and get user feedback on what is broken!

**Comment by ImportanceOfBeingErnest** [comment]
There is a word for this in German: "Berührungsangst überwinden" which would mean "cure haphephobia" but is used in the sense of what literally translates to "overcome touch fears" :sweat_smile:

> re: examples really working, anything that's not tagged sgskip should work fine in the Binder environment, provided that the repo is set up with the same environment that sphinx-gallery+CircleCI uses when it runs the examples

and 

> The best way to get feedback on which versions of the notebooks work is to open them up and get user feedback on what is broken!

I don't think that's the problem. There should not be any broken examples. All examples are valid python code. But if some example with interactive features like `.draggable()` is run with `%matplotlib inline` it will simply not work as intended.  
We should pretty much know which examples will or will not run in jupyter with inline backend. The problem is rather that for unexperienced users there is no difference between the example not working because it's broken or the example not working because it cannot work within the jupyterlab environment or with the inline backend.

So suppose users give feedback on what is broken, but then what? Currently there is no way of black or whitelisting examples or imposing a backend which should be used in the respective jupyter notebook file. This would be a step to make from the sphinx-gallery side first.

**Comment by choldgraf** [comment]
one option here: it'd be pretty straightforward to modify sphinx gallery to not add Binder links to any examples that are marked `sgskip`. AKA, if sphinx-gallery doesn't run them as a part of the build, then they don't get a link generated for them. That way you'd know that anything that successfully builds with the docs can be successfully run in Binder w/ the same environment.

That said, it's worth thinking about how much of an impact this will have on users. Just as an FYI:

* Of the 527 files in the `examples` folder, 37 are marked `sgskip`.
* Of those, about 80% are in `event_handling`,  `misc`, and `user_interfaces`
* The % traffic to the website that goes to these three subdomains is `event_handling` (.72%), `misc` (2.52%) , and `user_interfaces` (.93%).
* So in total, we're talking about roughly 4.25% of the traffic in examples (which is itself about 17% of the site as a whole)
* So in total, potentially breaking Binder buttons would exist on pages that make up .7% of traffic to the matplotlib documentation. And in this case, the "breaking" behavior would only happen if they also clicked a Binder button.

Not making a value judgment on that one way or another, just giving some # s

**Comment by ImportanceOfBeingErnest** [comment]
I was talking more about examples like 
* [simple_anim.py](https://matplotlib.org/gallery/animation/simple_anim.html) (in fact, all examples from the [animation section](https://matplotlib.org/gallery/index.html#animation)), or 
* [path_editor.py](https://matplotlib.org/gallery/event_handling/path_editor.html) (in fact, all examples from the [event handling section](https://matplotlib.org/gallery/index.html#event-handling)) or
* [slider_demo.py](https://matplotlib.org/gallery/widgets/slider_demo.html) (all from [Widgets](https://matplotlib.org/gallery/index.html#widgets))

They are not `_sgskip`ped. And they produce nice output images. But if you download the example as ipynb file and try to run it in your notebook, it won't work. This is a problem already present currently, but I suppose it becomes more obvious once a button says "Try me out!".

The numbers are surely useful. Where did you get those? Are crawlers and search engines filtered out of those? Do you have numbers on how often the `ipynb` files have been downloaded?

Do you think there is any way of creating a binder link for a handful of examples manually to put on the homepage? I'm asking since this could be a compromise and would allow to see how it goes before implementing it in full.

**Comment by choldgraf** [comment]
it'd be pretty straightforward to create binder links for a subset of examples on the main page, yeah. 

re: the numbers, I pulled those from the google analytics page, just digging through the "content drilldown" section

**Comment by choldgraf** [comment]
Here's a quick thought. re: Binder links, if we want to avoid the complexity of inserting Binder links into *all* of the examples because we aren't sure they'd work, we could instead just point out a few "highlighted tutorials" or something like this to put on the home page. 

For example, if we wanted to add just a couple examples to the home page, we could do the following:

1. Choose some examples we'd like to highlight
2. Figure out what dependencies they need (e.g. this would probably just be "matplotlib" and maybe something like "scipy".
3. Add those dependencies to an `environment.yml` or `requirements.txt` file in https://github.com/matplotlib/matplotlib.github.com.
4. Add links to the main page that point to the examples in Binder. E.g., here's a link that'd build the boxplot color example:
  
   https://mybinder.org/v2/gh/matplotlib/matplotlib.github.com/master?filepath=_downloads%2Fboxplot_color.ipynb

   In this case, the example only depends on matplotlib and numpy

5. So the only thing we'd need to add would be the `requirements.txt` file to that repo, and links to the notebooks we want people to be able to interact with.

Also relevant, I just opened up https://github.com/sphinx-gallery/sphinx-gallery/pull/401 which (if merged) will let us choose whatever text we want for the first cell. So we could either change that to `%matplotlib notebook`. Or we could change it to something like:

```
%matplotlib inline
# NOTE FOR ANIMATION EXAMPLES: Comment the above line and uncomment
# the following line to use animations.
#%matplotlib notebook
```

**Comment by berceanu** [comment]
There is also https://github.com/jupyter/jupyter-sphinx

**Comment by tacaswell** [comment]
This is also related to #22634

**Comment by agriyakhetarpal** [comment]
Hi all – apologies for commenting on an issue that's been around for almost seven years, but I've posted an [update](https://github.com/matplotlib/matplotlib/pull/22634#issuecomment-2588014453) on #22634 that was linked above. That PR aims to add an interactive REPL for Matplotlib's docs homepage running via Pyodide/JupyterLite and WebAssembly, and this issue deserves to receive the surrounding context as well: the combination of Sphinx-Gallery through its [JupyterLite integration](https://sphinx-gallery.github.io/stable/configuration.html#jupyterlite), and its underlying Sphinx extension ([`jupyterlite-sphinx`](https://github.com/jupyterlite/jupyterlite-sphinx/)) are pretty stable at this point and should overall allow replacing Binder with notebooks that can run Matplotlib with in-browser computation, avoiding server costs.

To address https://github.com/matplotlib/matplotlib/issues/11415#issuecomment-396374463, it is possible to download the notebooks with Sphinx-Gallery. Also, it is theoretically possible to disable a few examples for JupyterLite through Sphinx-Gallery's integrations based on an `sgskip` label (though, maybe disabling only under JupyterLite and not elsewhere needs to be a feature request or something?).

After all, one can expect that it would be useful for both docstring-based API examples that showcase functionality and for the galleries, even if it's on an experimental basis and users are warned that certain notebooks might not work. It is to be noted that `scikit-learn` has had this integration already for their docs' notebooks and they have been maintaining it so far, to the point of Pyodide/WASM as an officially supported platform: https://github.com/scikit-learn/scikit-learn/issues/23727

All in all, if this item is still in the ambit, I would be happy to put together a PR. :)

Here are some links to contemporary interactive documentation efforts in the ecosystem for Scientific Python projects:

- https://github.com/numpy/numpy/pull/26745
- https://github.com/scipy/scipy/pull/20019
- https://github.com/PyWavelets/pywt/pull/728
- and so on
