### ISSUE TITLE
matplotlib selector widget is not visible with blitting and wxpython

### ISSUE THREAD

**Issue by tavin** [matplotlib/matplotlib#11425]
### Bug report

The following code example uses the RectangleSelector widget, so that we should see a continuously updated rectangular patch over the plot. However, nothing can be seen, unless we set `useblit=False`.

**Code for reproduction**

```python
#!/usr/bin/env python3

import matplotlib
from matplotlib.widgets import RectangleSelector

if __name__ == '__main__':
    matplotlib.use('wxagg')
    import matplotlib.pyplot as plt
    figure = plt.figure()
    rect = RectangleSelector(figure.gca(), (lambda e1, e2: print(e1, e2)), useblit=True)
    plt.show()
```

**Matplotlib version**
  * Operating system: ubuntu 17.10
  * Matplotlib version: 2.2.2
  * Matplotlib backend: wxagg
  * Python version: 3.6.3
  * Other libraries: wxpython 4.0.1

Everything was installed from virtualenv + pip.

**Comment by lkjell** [comment]
Could you check with latest wxpython 4.0.2 and matplotlib git version? It appears to work here.

**Comment by anntzer** [comment]
Works for me with wx 4.0.1 and matplotlib 2.2.2 or git HEAD.

**Comment by tavin** [comment]
I've tried with wxpython 4.0.3 and both matplotlib 2.2.3 and matplotlib git head. I'm still seeing the bug. Perhaps it has something to do with ubuntu.

**Comment by anntzer** [comment]
Perhaps https://github.com/matplotlib/matplotlib/issues/10417, attn @DietmarSchwertberger?

**Comment by DietmarSchwertberger** [comment]
@tavin: are you using X or Wayland? Please check with: `$ echo $XDG_SESSION_TYPE`
```
$ echo $XDG_SESSION_TYPE
wayland
```

**Comment by tavin** [comment]
wayland yes @DietmarSchwertberger

**Comment by DietmarSchwertberger** [comment]
OK, I will have a look and start a Wayland compatible implementation. I can start earliest next week, though.

@tavin : as a workaround, you may select X from the login screen: https://askubuntu.com/questions/961304/how-do-you-switch-from-wayland-back-to-xorg-in-ubuntu-17-10

**Comment by DietmarSchwertberger** [comment]
@tavin : I have just submitted a PR #11944 to fix the Wayland issued. Maybe you can check whether this fixes your problems.
