### ISSUE TITLE
Pressing the "1" key kills the zoom/pan tool

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#11432]
### Bug report

**Bug summary**

Pressing the <kbd>1</kbd> key on the keybord kills the pan/zoom tool.
But only when subplots are used and in case those subplots contain any artist/title etc.

**Code for reproduction**

Steps for reproduction:

1. Run the following code with Qt*Agg or TkAgg backend.
 ```
import matplotlib.pyplot as plt

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2)

# ax2 and ax3 contain some additional elements
ax2.set_title('Ax2')
ax3.plot([1,3,3])

plt.show()
```

2. Interact with the zoom and pan tool on all subplots to verify they are working fine.
3. Press <kbd>1</kbd> on your keybord while your mouse is over one of the axes.
4. Try to interact with the zoom / pan tools in that axes again.

**Actual outcome**

On the two subplots, which do not have anything added (`ax1`, `ax4`) zooming and panning still works fine. On the two subplots which either contain a plot element (`ax3`) or a title (`ax2`), zooming and panning is broken, i.e. nothing happens if you activate the zoom or the pan tool and drag the mouse over those subplots.

**Expected outcome**

Obviously one would not want <kbd>1</kbd> to kill any tools.  
Or at least if there is a reason for it, to read about it in the [interactive navigation](https://matplotlib.org/users/navigation_toolbar.html#navigation-keyboard-shortcuts) docs.

**Further remarks**

Interestingly this is limited to the case of multiple subplots. If there is only a single subplot present, pressing <kbd>1</kbd> is harmless.

This issue was first observed in [this SO question](https://stackoverflow.com/questions/50822404/zoom-stops-working-after-connecting-button-press-event-but-only-in-subplot) for a slightly more involved use case.

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: tested with 2.0.2, 2.2.2 as well as master
  * Matplotlib backend: Qt4Agg /Qt5Agg /TkAgg
  * Python version: 2.7 / 3.6

**Comment by tacaswell** [comment]
The reason in the code is:

https://github.com/matplotlib/matplotlib/blob/928d6d5e1a860f617cb19011884a599b09029c9c/lib/matplotlib/backend_bases.py#L2454-L2468

but I don't know the reason for that code!  Looks like it goes back to 2006.

I think we should disable that code block by default with a flag in preparation for eventually deleting it.

**Comment by ImportanceOfBeingErnest** [comment]
Ah, seeing that code this all makes sense. The intention here is to enable or disable navigation interaction in the axes number `n` if the number n in pressed on the keyboard. E.g. enable / disable interaction in the first axes if <kbd>1</kbd> is pressed. But somehow this doesn't really work. 

So two options:
* Implement this feature consistently and document it clearly
* Remove this feature.

**Comment by anntzer** [comment]
I think this should just be removed.  Note that (AFAIK) the handlers only fire when the mouse is over the axes, so it's unlikely you're triggering them by default anyways (and if someone really wants to implement their own even handlers instead of relying on builtin pan/zoom, they would likely just disconnect the default tools).

**Comment by timhoffm** [comment]
+1 for removing this feature.

**Comment by anntzer** [comment]
This was deprecated in 3.3 in #16529.
