### ISSUE TITLE
plt.subplot eats my subplots

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#11435]
### Bug report

**Bug summary**

`plt.subplot` eats my subplots. But it doesn't completely digest them, since they are still there, just not shown.

Creating a subplot grid with `plt.subplots` and in addition adding a `plt.subplot` removes those subplots from the grid, which are under the newly created subplot.  
Creating the additional subplot via `fig.add_subplot` does not remove them.

**Code for reproduction**

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(2,3,
                       subplot_kw={"label" : "A"}, 
                       gridspec_kw={'width_ratios':[1,1,3]})
ax[0,2].plot([1,2,3])

axi = plt.subplot(133, label="B")
axi.plot([7,6,5], color="red")
axi.axis("off")

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/23121882/41364277-8a575c6e-6f36-11e8-9b82-328490d97667.png)

**Expected outcome**

The expected outcome would be the same as with `fig.add_subplot`:

```
axi = fig.add_subplot(133, label="B")
axi.plot([7,6,5], color="red")
axi.axis("off")
```

![image](https://user-images.githubusercontent.com/23121882/41364363-b83f0c44-6f36-11e8-8672-04a78ea7938f.png)

**Matplotlib version**

  * Operating system: Win 8.1
  * Matplotlib version: master
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6

**Comment by fredrik-1** [comment]
I am currently looking at and editing those docstrings and that behavior is correct according to the docstrings and code. `plt.subplot` delete overlapping subplots and `fig.add_subplot` doesn't.  

I don't know why it is a difference in behavior.

**Comment by ImportanceOfBeingErnest** [comment]
So you think this is desired? That feels a lot as if suddenly `plt.title` would create a title below the axes while `ax.set_title` creates it above or so.

**Comment by fredrik-1** [comment]
I don't understand why the feature exist but it is well documented [https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.subplot.html#matplotlib.pyplot.subplot](url)

**Comment by ImportanceOfBeingErnest** [comment]
I see. My bad. I guess this can be closed, although I think this pretty annoying and should probably be changed at some point.

**Comment by jklymak** [comment]
Matlab does this...

**Comment by anntzer** [comment]
We can't blame everything on MATLAB, see https://github.com/matplotlib/matplotlib/pull/7377#issuecomment-260049527 and surrounding discussion (I haven't tried for subplot though).

**Comment by jklymak** [comment]
Again, I wouldn't use `plt.subplots` and `plt.subplot` in the same figure and expect anything sensible to happen.
