### ISSUE TITLE
imsave always saves alpha channel

### ISSUE THREAD

**Issue by tonyxty** [matplotlib/matplotlib#11436]
### Bug report

**Bug summary**

`mpimg.imsave` always saves alpha channel, regardless of the shape of input array.

Related stackoverflow question: https://stackoverflow.com/questions/40613330/how-to-force-python-to-write-3-channel-png-image

**Code for reproduction**

```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.image as mpimg
import numpy as np


A = np.zeros((32, 32, 3))
print(A.shape)
mpimg.imsave("A.png", A)

A_read = mpimg.imread("A.png")
print(A_read.shape)
```

**Actual outcome**

```
(32, 32, 3)
(32, 32, 4)
```

**Expected outcome**
```
(32, 32, 3)
(32, 32, 3)
```
**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: matplotlib-2.2.2 (from pip)
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: Python 3.6.5
  * Jupyter version (if applicable): N/A
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
In the SO question you link to there is an answer and a comment which show alternatives to using matplotlib's `imshow` and `imsave` methods. 

If this is for convenience, you may also just select the channels you want via `mpimg.imread("A.png")[:,:,:3]`. Maybe you can comment on why matplotlib methods need to not save any alpha channel.

**Comment by tonyxty** [comment]
@ImportanceOfBeingErnest, thanks for your comment.
> For such cases, other libraries are much stronger and provide the respective methods.

matplotlib's native png library seems to be the only one that directly supports floating-point numpy arrays, and I'm worried about the errors introduced in converting int arrays to and back from floats. (I tried loading images with Pillow and divide the results by 255.0, it produces slightly different values than matplotlib)

> Maybe you can comment on why matplotlib methods need to not save any alpha channel.

Maybe my wording is not very clear.  I was hoping that matplotlib can choose the format according to the shape of the array, which means `imread`ing a previously `imsave`d image will give back exactly the same numpy array, as long as it represents a valid image.  In fact this feature seems to be already present in C++ source code: https://github.com/matplotlib/matplotlib/blob/86a3c946a65ae5876fb5e2f532a81c3f60b7db69/src/_png.cpp#L191-L200
But the python code for `imsave` did not make use of it.

**Comment by ImportanceOfBeingErnest** [comment]
I would actually rather trust Pillow in this case than matplotlib.  
What imsave does is that it creates a matplotlib figure, calls `imshow` on it and saves the result as png. This is a detour that you wouldn't usually do when working with images and any solution that directly uses the numpy array to convert to colors might be more efficient and precise.

**Comment by tonyxty** [comment]
Sounds reasonable, I will use Pillow instead.  Closing.
