### ISSUE TITLE
Get rid of get_test_data in axes3d examples

### ISSUE THREAD

**Issue by JakobJakobson** [matplotlib/matplotlib#11440]
### Bug report ###

**Bug summary**
Some axes3d examples load test data instead of generating their data within their script. For newcomers it would be much more convenient if the examples would also generate the data, especially as all the examples only use ```axes3D.get_test_data(0.1)``` and ```axes3D.get_test_data(0.5)```.

The examples can be found via <https://matplotlib.org/search.html?q=get_test_data&check_keywords=yes&area=default> and are
- [ ] 3D plots as subplots 
- [ ] 3D wireframe plot
- [ ] 3D wireframe plots in one direction
- [ ] Demonstrates plotting contour (level) curves in 3D
- [ ] Demonstrates plotting contour (level) curves in 3D using the extend3d option
- [ ] Filled contours
- [ ] Projecting contour profiles onto a graph
- [ ] Projecting filled contour onto a graph
- [ ] Rotating a 3D plot

As the ```get_test_data``` function in ```matplotlib/axes3d.py``` with the following code
```python
def get_test_data(delta=0.05):
    '''
    Return a tuple X, Y, Z with a test data set.
    '''
    x = y = np.arange(-3.0, 3.0, delta)
    X, Y = np.meshgrid(x, y)

    Z1 = np.exp(-(X**2 + Y**2) / 2) / (2 * np.pi)
    Z2 = (np.exp(-(((X - 1) / 1.5)**2 + ((Y - 1) / 0.5)**2) / 2) /
          (2 * np.pi * 0.5 * 1.5))
    Z = Z2 - Z1

    X = X * 10
    Y = Y * 10
    Z = Z * 500
return X, Y, Z
```

is not very big it also would not bloat the examples very much. With your approval I would prepare the pull request for that issue.

Regards

**Comment by timhoffm** [comment]
I’m +/-0 on this. What’s the real benefit? I don’t see how this is “much more convenient”.

**Comment by JakobJakobson** [comment]
As a newcomer I wouldn't know how to prepare the 3d-data and had to check another example that shows how the 3d data is constructed.
This would become obsolete.

**Comment by timhoffm** [comment]
Hm. If you want to plot something, you'd probably have the data already. Apart from that, I don't think that showing people how to generate arbitrary data using numpy is a goal of the matplotlib docs.

**Comment by JakobJakobson** [comment]
Okay, then I close the issue now.

**Comment by timhoffm** [comment]
Anyway, thanks for sharing your thoughts on how to improve matplotlib. Hope to see you back some time.

**Comment by da-rs** [comment]
> how to generate arbitrary data 
arbitrary: It's not arbitrary, there is an expected input data structure which is not necessarily obvious.
how: Rather than how, it will be showing what -- what is expected for of input. So that the users can research ways of producing it (e.g. meshgrid)
