### ISSUE TITLE
markerfacecolor="None" becomes black when using the alpha channel

### ISSUE THREAD

**Issue by hsandmeyer** [matplotlib/matplotlib#11458]
**Bug summary**

When plotting non-filled markers with` markerfacecolor="None"` along with `alpha=non-zero` the marker face color becomes black for the png format. Same happens when using plt.show().

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.errorbar([1], [1], markerfacecolor = "None",
        marker = 'o', alpha = 0.9, markersize=100)

plt.savefig('test.png')
plt.savefig('test.pdf')
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/26244423/41591333-b9a7f424-73b9-11e8-8a0f-19e1a0901418.png)

**Expected outcome**
[test.pdf](https://github.com/matplotlib/matplotlib/files/2114790/test.pdf)

**Matplotlib version**

matplotlib 2.2.2-2 on arch-linux

**Comment by anntzer** [comment]
Fixed in master by #11105.
