### ISSUE TITLE
bbox intersection algorithm docs

### ISSUE THREAD

**Issue by Phlya** [matplotlib/matplotlib#11450]
Hi, the link to the description of algorithm for bbox intersection in the docs doesn't actually lead to the explanation: http://www.tekpool.com/node/2687 - it's from here https://matplotlib.org/devel/transformations.html

**Comment by jklymak** [comment]
Took me a while to see what you meant!  

https://matplotlib.org/devel/transformations.html#matplotlib.transforms.BboxBase.intersection

Anyone know if there is a doi we can point to instead?  Otherwise we should just remove the link...

**Comment by jklymak** [comment]
Sucks that old versions still show up in the root of `devel`....

**Comment by Phlya** [comment]
Right, sorry, forgot to make a permalink to the necessary place.

I see, thanks! I am still curious what the algorithm is, though, and why it shows up in devel?..

**Comment by jklymak** [comment]
The docs got reorganized.  That directory is not part of the current doc tree, but still lurks around under `devel` (so we don't break links ?)...

**Comment by Phlya** [comment]
Mh, well, it comes up first if you search on google, maybe there should be some redirect to the current version?
