### ISSUE TITLE
Layout managers have problems with titles containing MathText

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#11468]
Layout managers seem to have problems with titles containing MathText.

One would expect to have a title which neither overlaps with the axes nor with the figure boundary in all cases depicted below.

### multi line title

![tight_layout2](https://user-images.githubusercontent.com/23121882/41689562-781e55a0-74f1-11e8-98d6-901db12dcb66.png)

as expected

### multi line title with MathText

![tight_layout1](https://user-images.githubusercontent.com/23121882/41689568-7e1c5c2c-74f1-11e8-9f9d-1304e8405004.png)

The title is a bit squeezed towards the top figure boundary, but does not go beyond it, nor does it overlap the axes. This is somehow still acceptable.

### single line title with MathText

![tight_layout0](https://user-images.githubusercontent.com/23121882/41689577-880b13ae-74f1-11e8-91e4-62a4d6662ba4.png)

Here the title overlaps with the axes. This is in thus far strange because in the case above with multiple lines, this overlap does not occur.

### multi line title

![constrained_layout2](https://user-images.githubusercontent.com/23121882/41689709-40927e58-74f2-11e8-9871-382312caa272.png)

as expected

### multi line title with MathText

![constrained_layout1](https://user-images.githubusercontent.com/23121882/41689723-50ff221e-74f2-11e8-9205-6ecde44d4556.png)

The title exits the figure. This is not desiredeable.

### single line title with MathText

![constrained_layout0](https://user-images.githubusercontent.com/23121882/41689717-4c12ef24-74f2-11e8-8dae-628f60b268d0.png)

Here the title overlaps with the axes. 

## code 

```
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['savefig.facecolor']='#e9f7fd'

def create_bug(title="", constrained_layout=True, i=0):
    plt.figure(constrained_layout=constrained_layout)
    plt.plot([0,1,2],[0,1,1])
    plt.title(title)
    
    if not constrained_layout:
        plt.tight_layout()
        tx = "tight_layout"
    else:
        tx = "constrained_layout"
    plt.text(0.4,.95, tx, va="center")
    plt.savefig(tx+str(i)+".png")
    
titles = ['line $\sum_{i} x_i$',
          'multi-\nline $\sum_{i} x_i$',
          'multi-\nline']
for layout in [True, False]:
    for i, title in enumerate(titles):
        create_bug(title, layout, i)
```

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 2.2.2, current master
  * Matplotlib backend : Qt5Agg
  * Python version: 2.7, 3.6

**Comment by jklymak** [comment]
Thats because we have no way of knowing the text size other than by the fontsize.  If we stick a huge symbol like `$\sum_{i}$` in there, we don't know that its so much larger.  I'm not sure what particularly can be done about this w/o a lot of work in the `get_tightbbox` code for the text.

**Comment by ImportanceOfBeingErnest** [comment]
Sure? If only fontsize matters, how do you find out the difference between "iiiiiiiiiii" and "mmmmmmmmmm", which clearly is accounted for, e.g. in the case of ylabels.
<details>
 <summary>See e.g. this image.</summary>

![image](https://user-images.githubusercontent.com/23121882/41749025-9debf558-75b4-11e8-9e81-d746ff409d88.png)

</details>

<hr>

Here are the boxes for the text obtained via `get_window_extent()` for the respective cases:


**tight_layout**

![tight_layout2zz](https://user-images.githubusercontent.com/23121882/41751182-7b7017aa-75c0-11e8-92b2-6da14e088f22.png) &nbsp; &nbsp; &nbsp; ![tight_layout1zz](https://user-images.githubusercontent.com/23121882/41751190-7d97d360-75c0-11e8-91e3-9d539bb78297.png) &nbsp; &nbsp; &nbsp; ![tight_layout0zz](https://user-images.githubusercontent.com/23121882/41751191-7fb3bb0a-75c0-11e8-885c-8fe1729790a9.png)

**constrained_layout**

![constrained_layout2zz](https://user-images.githubusercontent.com/23121882/41751264-b8a45744-75c0-11e8-8b5f-754382e10584.png)&nbsp; &nbsp; &nbsp; ![constrained_layout1zz](https://user-images.githubusercontent.com/23121882/41751267-bac91f46-75c0-11e8-89ff-f3e0ac6a1a81.png)&nbsp; &nbsp; &nbsp; ![constrained_layout0zz](https://user-images.githubusercontent.com/23121882/41751268-bc2b5200-75c0-11e8-8127-e7120b313b11.png)

Seeing this it might be understandable that the multiline with mathtext (middle column) is cut on top. But what is really strange is that in the case of the single line (right column), the bounding box is actually correct, but still overlaps with the axes. 

So in total those might be two different issues:
* The bounding box (window extent is wrong) for such multiline mathtext.
* The bounding box is ignored by the be layout managers.

**Comment by jklymak** [comment]
OK, the last column the problem is that neither layout manager cares if the title overlaps the axes.  Thats the fault of where the title is being placed.  If you call w/ no layout manager the i still overlaps.  The way the layout managers work is by adjusting the size of the axes assuming a border that takes up the other decorators; here the layout managers are doing the right thing from their point of view.  If we wanted something that does a better job of positioning axes that could be done separately.  

The middle column is definitely just a problem with the bbox from multiline w/ text.  Multi lines are hard: https://github.com/matplotlib/matplotlib/pull/9775

**Comment by jklymak** [comment]
Hmmm, though #9498 should have taken care of the right hand column case.  I'll need to see whats going on there.

**Comment by jklymak** [comment]
Ah...  #9498 only does its thing if the xaxis is on top.   An easy fix is to also move the title if it overlaps the actual axes.   My only concern there is performance because I think the axes tightbbox calf can be expensive.

**Comment by jklymak** [comment]
OK, not finding a nice consistent way to do this.  OTOH, note that there is a pad argument now for `set_title`, so the user can simply specify a larger pad (in points) to get the title far enough away from the axes.  https://github.com/matplotlib/matplotlib/pull/9816  https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_title.html

**Comment by jklymak** [comment]
@ImportanceOfBeingErnest please see #11499 and #11502.  I think together they solve the issue here...

**Comment by ImportanceOfBeingErnest** [comment]
Yep, it seems so. Once they are merged, this can be closed.
