### ISSUE TITLE
Strange behaviour with ligatures and combination of pgf and lualatex

### ISSUE THREAD

**Issue by JakobJakobson** [matplotlib/matplotlib#11488]
### Bug report

**Bug summary**

Saving my pdf graphics via the pgf module results in having or not-having ligatures with different fonts.

**Code for reproduction**
On the one hand I got my code with rcfonts set to "True" meaning the dejavu sans fonts. 
```python
import matplotlib as mpl
mpl.use("pgf")
pgf_with_lualatex = {
    "pgf.rcfonts": True,
    "pgf.preamble": [r"\usepackage{unicode-math}"],
    "pgf.texsystem": "lualatex",   
}
mpl.rcParams.update(pgf_with_lualatex)
import matplotlib.pyplot as plt

plt.title("figure")

plt.savefig("ligature_dejavu.pdf")

```
Here the ligature fi of figure works fine. See [ligature_dejavu.pdf](https://github.com/matplotlib/matplotlib/files/2128802/ligature_dejavu.pdf).

On the other hand I  got my code with rcfonts set to "False" meaning the latin modern fonts.
```python
import matplotlib as mpl
mpl.use("pgf")
pgf_with_lualatex = {
    "pgf.rcfonts": False,
    "pgf.preamble": [r"\usepackage{unicode-math}"],
    "pgf.texsystem": "lualatex",   
}
mpl.rcParams.update(pgf_with_lualatex)
import matplotlib.pyplot as plt

plt.title("figure")

plt.savefig("ligature_LMmodern.pdf")

```
Here the ligature fi of figure does not work. See [ligature_LMmodern.pdf](https://github.com/matplotlib/matplotlib/files/2128805/ligature_LMmodern.pdf)

I'm just wondering if this is due to lualatex or is it a matplotlib bug?

**Matplotlib version**
  * Operating system:  CentOS 
  * Matplotlib version: 2.2.2
  * Python version: 3.6.3
  * I installed it via pip and I'm running it in a virtual environment.

**Comment by anntzer** [comment]
Unless I'm mistaken, this is simply because there is no "fi" ligature in latin modern sans (which can easily be tested by compiling a test case independent of matplotlib with lualatex or pdflatex), whereas there is one in dejavu sans.
Feel free to request a reopen if you can produce such a ligature.
