### ISSUE TITLE
Some issues about doc of plt.hist

### ISSUE THREAD

**Issue by gauss-clb** [matplotlib/matplotlib#11490]
See [doc](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html?highlight=hist#matplotlib.pyplot.hist)

1. For parameter `density`,  is the `If stacked is also True, the sum of the histograms is normalized to 1.` wrong?  I have tried  `stacked=True`, but no effect.

```python
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
x = np.random.randint(-5, 5, 100)
plt.subplot(121)
plt.hist(x, density=True)
plt.subplot(122)
plt.hist(x, density=True, stacked=True)
plt.show()
```
There is no difference whether `stacked` is `True` or `False`.

![d1](https://user-images.githubusercontent.com/11674304/41810474-a5b399ac-7731-11e8-81ca-454e20291c14.png)

2. For parameter `cumulative `, `If cumulative evaluates to less than 0 (e.g., -1), the direction of accumulation is reversed. In this case, if normed and/or density is also True, then the histogram is normalized such that the first bin equals 1.`, I have tried it, but the last bin equals 1, not the first bin.

```python
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
weights = np.arange(100) - 50
x = np.random.randint(-5, 5, 100)
plt.subplot(111)
plt.hist(x, density=True, weights=weights, cumulative=True)
plt.show()
```
![d2](https://user-images.githubusercontent.com/11674304/41810493-18830490-7732-11e8-8fe0-0ce77b09dc55.png)

**Comment by ImportanceOfBeingErnest** [comment]
I think it would help if you provided a minimal runnable example from which one can see in how far this is an issue.

**Comment by gauss-clb** [comment]
Yeah, I have updated code and result.

**Comment by ImportanceOfBeingErnest** [comment]
Concerning the first point, `stacked` can only be used if you have several datasets, use in this case e.g. 

    x = np.random.randint(-5, 5, size=(100,2))

Unless you are unhappy with the result of that as well, maybe one can limit this issue to the `cumulative` part?

**Comment by gauss-clb** [comment]
@ImportanceOfBeingErnest Even if I use `x = np.random.randint(-5, 5, size=(100,2))`, it is not correct either. The width of bar is `0.9`, `a1[0]` and `a1[1]` are `10/9`, which means the area under each histogram is `1.0`, but `a2[0]` is `5/9` and `a2[1]` is `10/9`, can you tell me why?

```python
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
x = np.random.randint(-5, 5, size=(100,2))
plt.subplot(121)
a1,b1,*_ = plt.hist(x, density=True)
plt.subplot(122)
a2,b2,*_ = plt.hist(x, density=True, stacked=True)

print(a1[0].sum())
print(a1[1].sum())

print(a2[0].sum())
print(a2[1].sum())

plt.show()
```

**Comment by ImportanceOfBeingErnest** [comment]
```
s1 = (a2[0]*np.diff(b2)).sum()
s2 = ((a2[1]-a2[0])*np.diff(b2)).sum()
print(s1+s2) # this prints 1.
```

**Comment by gauss-clb** [comment]
I think you are right for the first case `density`, but for the second case `cumulative`, `the first bin` need to be replaced with `the last bin` in doc, do you think so?

**Comment by ImportanceOfBeingErnest** [comment]
Concerning `cumulative`, the sentence 

> If `cumulative` evaluates to less than 0 (e.g., -1), the direction of accumulation is reversed.

is to be understood literally, meaning that if the `cumulative` argument is set to `-1`, the accumulation performed in the inverse direction.

    plt.hist(x, density=True, weights=weights, cumulative=-1)




![image](https://user-images.githubusercontent.com/23121882/42156662-f2322a76-7deb-11e8-9a99-993462775d45.png)

In total, as far as I can see, the documentation is correct for both cases. But if you want to make a suggestion, @gauss-clb, on how to word it better, such improvements are generally well received.
