### ISSUE TITLE
bi-directional perceptually flat colormaps in matplotlib?

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#11508]
A few folks have asked me how they can plot a perceptually flat colormap (like viridis) for bi-directional data (AKA, data that you'd use `coolwarm` or `RdBu` for). I searched around but didn't find anything like this in matplotlib. I know it's been discussed before, does anyone know if those discussions went anywhere?

**Comment by choldgraf** [comment]
Ah I found https://github.com/matplotlib/matplotlib/pull/6254 which implements a circular colormap. Has something similar been done for a diverging colormap?

**Comment by dstansby** [comment]
This would be a really great thing to add, and I don't think it already exists.

**Comment by choldgraf** [comment]
are you gonna be at scipy @dstansby ? or @tacaswell ? maybe we can make it into a quick hack :-)

**Comment by afvincent** [comment]
@choldgraf It looks like [cmocean](https://matplotlib.org/cmocean/) may have a few of them, namely "balance", "delta", and "curl".

**Comment by dstansby** [comment]
@choldgraf I won't be at scipy, but I'm in Berkeley now for 3 weeks, happy to spend an afternoon hacking this together/doing other Matplotlib things if you'll be around at all.

**Comment by choldgraf** [comment]
@dstansby cool! I'll be back from Scipy starting Friday. Whereabouts are you working? You could probably use the BIDS space if you need a place to hang.

**Comment by ImportanceOfBeingErnest** [comment]
Possibly related: #6033

**Comment by choldgraf** [comment]
ooh nice find

**Comment by jklymak** [comment]
I'll close in favour of #6033
