### ISSUE TITLE
Math expression doesn't show properply  in wrapped text

### ISSUE THREAD

**Issue by bigvzhang** [matplotlib/matplotlib#11511]
### Bug report

**Bug summary**

**Code for reproduction**

```
#!/usr/bin/python3
import matplotlib.pyplot as plt
t1="""
Sets are usually denoted by capitals. 
The objects belonging to a set are called its elements or members. 
We write  $x \in A $ if x is a member of A, and $ x \notin A $ if it is not.
"""

t2="""
If all members of A are also in B, we call A a subset of B (and B a superset of A),
and write $A \subseteq B $ or $B \supseteq A $.
"""

t3="""
It is an axiom that the sets A and B are equal (A=B) if they have the same members, i.e.,
$A \subseteq B and B \subseteq A $, 
"""

plt.text(0, 0.1, t1, wrap = True)

plt.text(0, 0.4, t2, wrap = True)

plt.text(0, 0.7, t3, wrap = True)
plt.show()

```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Will show math functions in the plot. But some times they also
**Matplotlib version**

  * Operating system: Cygwin In Windows7
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): QT5Agg
  * Python version:3.6.4
 

use pip

**Comment by dstansby** [comment]
I've just fixed the formatting on the report so it displays properly; this is what I get running the code:
![figure_1](https://user-images.githubusercontent.com/6197628/41900790-630b9d46-7927-11e8-81c3-dcb7dacb0b81.png)
@bigvzhang is this what you expected? I'm not sure which bit is wrong.

**Comment by bigvzhang** [comment]
I really want to see the  math expressions shown properly! The first two are my wants, but not the third one. And if the plot is resized, probably the first two won’t be shown properly.

**Comment by anntzer** [comment]
This is because you need to be using raw-strings (see https://matplotlib.org/tutorials/text/mathtext.html#writing-mathematical-expressions, https://stackoverflow.com/a/13338569/378080).
