### ISSUE TITLE
LogLocator ignores numticks without axis

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#11518]
### Bug report

**Bug summary**

It does not seem possible to use LogLocator to generate a specific number of log-spaced tick locations without a live axis.

**Code for reproduction**

```python
import matplotlib as mpl
ticker = mpl.ticker.LogLocator(numticks=2)
ticker.tick_values(1, 10)
```
array([   0.1,    1. ,   10. ,  100. ])

**Expected outcome**

array([   1. ,   10. ,  ])

**Matplotlib version**
  * Matplotlib version: 2.2.2
  * Python version: 3.6

**Comment by mwaskom** [comment]
For context about my expectations, here's how this works on an axis:

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots(figsize=(6, 4))
ax.plot(np.logspace(1, 4, 10))
ax.set_yscale("log")
ax.yaxis.set_major_locator(mpl.ticker.LogLocator(numticks=2))
```
![image](https://user-images.githubusercontent.com/315810/41984283-4c7d6546-79fe-11e8-81a0-d070bdcc8439.png)

**Comment by WeatherGod** [comment]
The live axis is clipped to the bounds, so you only *see* 2 major ticks.
IIRC, we modified this behavior a bit several releases ago because we were
running into situations where ticks weren't appearing due to floating-point
issues. So we generated extra ticks and let the clipping handle the rest. I
think @efiring would know for sure, though.

**Comment by mwaskom** [comment]
Ah, I think that's right:

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots(figsize=(6, 4))
ax.plot(np.logspace(1, 4, 10))
ax.set_yscale("log")
ax.yaxis.set_major_locator(mpl.ticker.LogLocator(numticks=2))
ax.get_yticks()
```
```
array([  1.00000000e-02,   1.00000000e+00,   1.00000000e+02,
         1.00000000e+04,   1.00000000e+06,   1.00000000e+08])
```

So I think the match between the appearance and the `numticks` parameter here was serendipitous.

It's still very confusing, however, how little (if any) influence `numticks` seems to have on the number of positions that the locator generates...
