### ISSUE TITLE
using 'sharex' once in 'subplots' function can affect subsequent calles to 'subplots'

### ISSUE THREAD

**Issue by seth-a** [matplotlib/matplotlib#11515]
### Bug report

**Bug summary**
Using 'sharex' keyword argument once in the subplot function causes all subsequent axes returned by subplots to have a shared x-axis when the subplot_kw argument is also included.

**Code for reproduction**

```python
import matplotlib
from pylab import *


defaults_subplots = dict()

x1, y1 = range(30), randn(30)
x2, y2 = range(30, 60), randn(30)

close('all')

## Case 1 : single subplot (can be multiple as well)
##  this behaves correctly
f2, ax2 =  subplots(1,1, sharex=True, subplot_kw=defaults_subplots)
title('figure 1')
ax2.plot(x2, -y2)

## Case 2 : multiple subplots (single subplot causes bug to not appear)
f1, (ax1, _) = subplots(2,1, sharex=True, subplot_kw=defaults_subplots)
title('figure 2')
ax1.plot(x1, y1)

## Case 3 : same code as case 1, however axis is shared with subplots in case 2
f2, ax3 =  subplots(1,1, subplot_kw=defaults_subplots)
title('figure 3')
ax3.plot(x2, -y2)

show()
```

**Actual outcome**

Figure 1 has an independent x axis, while subplots in figures 2 and 3 share an x axis. 

**Expected outcome**
The x axis should be independent for each figure.  The subplots in figure 2 should have a shared axis.
 
**Fix**
The bug is the result of modifying the `subplot_kw` dictionary, following patch resolves the issue:

```
@@ -1171,6 +1171,9 @@
                          (sharey, share_values))
     if subplot_kw is None:
         subplot_kw = {}
+    else:
+        subplot_kw = subplot_kw.copy()
+
     if gridspec_kw is None:
         gridspec_kw = {}
 ```

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 1.5.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2
Matplotlib installed through ubuntu package manager.

**Comment by jklymak** [comment]
A lot of sharing code has changed since 1.5.  Can anyone reproduce on a newer matplotlib?

**Comment by tacaswell** [comment]
@seth-a Can you put in a PR with that change?  We should not be mutating user input (at least not with out very big warnings and for very good reasons)!

**Comment by dstansby** [comment]
I can't reproduce, but agree with @tacaswell that the fix should still probably go in.

**Comment by tacaswell** [comment]
The exact work here:

 - verify that this bug still exists on master
 - make sure we copy before mutating any dictionaries that the user passes in.

**Comment by ImportanceOfBeingErnest** [comment]
I cannot reproduce this with matplotlib 2.2, neither can I reproduce it with current master. The code inside of `subplots` has really changed a lot since version 1.5 and it is now immune against such mutated injections. 

What remains is the "problem" that matplotlib internally indeed modifies a user-provided object - in this case the dictionary that gets passed in.
