### ISSUE TITLE
Axes3D scatter plot for Numpy arrays in F-order does not give correct z-values

### ISSUE THREAD

**Issue by NichtJens** [matplotlib/matplotlib#11525]
### Bug report

**Bug summary**

Axes3D scatter plots work fine for Numpy arrays in C-order, but fail to produce the correct z-value for F-order. It seems the z-value of the last coordinate set is used for all coordinates.

**Code for reproduction**

```python
import numpy as np

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import pyplot as plt


# create two 3D plots

fig = plt.figure()
axC = fig.add_subplot(121, projection='3d')
axF = fig.add_subplot(122, projection='3d')


# rotate both images together, only here for making it easier to see the problem... can be ignored

def on_move(event):
    if event.inaxes == axC:
        axF.view_init(elev=axC.elev, azim=axC.azim)
    elif event.inaxes == axF:
        axC.view_init(elev=axF.elev, azim=axF.azim)
    else:
        return
    fig.canvas.draw_idle()

fig.canvas.mpl_connect('motion_notify_event', on_move)


# the interesting part

A = np.array((
    ( 1,  2,  3),
    ( 1, -2,  3),
    (-1,  2, -3),
    (-1, -2, -3)
))

C = A.copy("C")
F = A.copy("F")

for i in range(10):
    C += i
    F += i
    axC.scatter(*C.T) # looks correct
    axF.scatter(*F.T) # z-values never change

axC.set_title("C")
axF.set_title("F")
plt.show()
```

**Actual outcome**

For F-ordered arrays, the z-value of the last coordinate set is used for all coordinates.

**Expected outcome**

Scatter plots should be independent from the array's order. Thus, both plots from the example should be identical.

**Matplotlib version**

  * Operating system: Linux Mint 17.2 / Ubuntu 14.04
  * Matplotlib version: 1.3.1-1ubuntu5
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.5-5ubuntu3
  * Other libraries: Numpy: 1:1.8.2-0ubuntu0.1

Installed the OS's default version via apt.

**Comment by anntzer** [comment]
Appears that
```
diff --git a/lib/mpl_toolkits/mplot3d/art3d.py b/lib/mpl_toolkits/mplot3d/art3d.py
index 7a669e46d..ee5f71d61 100644
--- a/lib/mpl_toolkits/mplot3d/art3d.py
+++ b/lib/mpl_toolkits/mplot3d/art3d.py
@@ -450,7 +450,7 @@ class Path3DCollection(PathCollection):
         else:
             xs = []
             ys = []
-        self._offsets3d = juggle_axes(xs, ys, np.atleast_1d(zs), zdir)
+        self._offsets3d = juggle_axes(xs, ys, np.atleast_1d(zs).copy(), zdir)
         self._facecolor3d = self.get_facecolor()
         self._edgecolor3d = self.get_edgecolor()
         self.stale = True
```
fixes the issue, although why there is a modification in place in one case and not the other remains unclear to me.

**Comment by anntzer** [comment]
Figured it out: in scatter3d,
```
        xs, ys, zs = np.broadcast_arrays(
            *[np.ravel(np.ma.filled(t, np.nan)) for t in [xs, ys, zs]])
```
ensures that zs gets copied if it was not C-contiguous before.  In the original example, when the input was in F-order, each z was already contiguous in C-order, so no copy would be made.

Would be nice to decide whether array copying (not letting further in-place changes to the inputs affect the artists) should generally occur in the axes methods or in the artist constructors (preferably not in both, to avoid excessive copies).  I think doing it in the axes methods (and documenting that artists may not make copies -- allowing for efficient data sharing if needed) makes sense?

**Comment by timhoffm** [comment]
Sounds reasonable.
