### ISSUE TITLE
matplotlib not working radar plot v2.2.2 python 3.6 Anaconda W10

### ISSUE THREAD

**Issue by TJTapajyoti** [matplotlib/matplotlib#11541]
![image](https://user-images.githubusercontent.com/24482959/42121930-16d693e4-7c07-11e8-9be3-089db924239f.png)

The centers are shifted due to this statement (Line 189)

ax.set_varlabels(spoke_labels)

**Comment by jklymak** [comment]
What code was used to make this plot?  https://matplotlib.org/gallery/api/radar_chart.html?highlight=radar Should work.

**Comment by TJTapajyoti** [comment]
It would be good if these websites are updated to reflect the versions of matplotlib more explicitly. I found it on my own eventually,

**Comment by jklymak** [comment]
Sorry this was frustrating.  It was noted in the other thread that you posted in about this problem that the issue was the web search (and a perhaps unexpected change in the meaning of theta).  If you want to continue the conversation there that would be great...

**Comment by TJTapajyoti** [comment]
Thanks. Please close this issue.
