### ISSUE TITLE
import time

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#11546]
Here's an import profile created with Python 3.7's `importtime` and displayed with [tuna](https://github.com/nschloe/tuna):
```
python3.7 -X importtime -c "import matplotlib" 2> matplotlib.log
tuna matplotlib.log
```
Looks like lazy-loading urllib.request would pay off. Likewise for pyparsing.

![matplotlib](https://user-images.githubusercontent.com/181628/42136272-9a6d8922-7d58-11e8-856c-f474603688f3.png)

**Comment by timhoffm** [comment]
There are actually two urllib.request uses:
- The one in `matplotlib._open_file_or_url()` i mention above.
- The one in `matplotlib.image` from @anntzer 

Just removing or inlineing one does not give a performance benefit.

**Comment by anntzer** [comment]
I did try inlining both.

**Comment by anntzer** [comment]
I played a bit with -Ximporttime and noticed that in certain cases, a module taking longer to import was actually due to the gc kicking in; thus, one should call gc.disable() before doing these benchmarks.

**Comment by jklymak** [comment]
I don't see an action on this, and it looks ephemeral, so I'm closing....
