### ISSUE TITLE
Implement support for hiding ticks labels from a stylesheet and/or "rcParams".

### ISSUE THREAD

**Issue by KelSolaar** [matplotlib/matplotlib#11543]
### Feature request

**Feature summary**

I would like to be able to hide ticks labels directly from a stylesheet and/or `rcParams` which does not seem to be currently possible. One can hide ticks as follows:

**Code for reproduction**

```python
with plt.style.context({'xtick.bottom': False, 'ytick.left': False}):
    plt.plot(1, 1)
    plt.show()
```
but it is not possible to hide the ticks labels thus attributes like so would be a welcome addition:

- `'xtick.top.labels'`
- `'xtick.bottom.labels'`
- `'ytick.left.labels'`
- `'ytick.right.labels'`

**Matplotlib version**

  * Operating system: macOs 10.12.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: Python 2.7.14

**Comment by QuLogic** [comment]
Is that not `xtick.labelbottom`, `xtick.labeltop`, `ytick.labelleft`, and `ytick.labelright`?

**Comment by KelSolaar** [comment]
Hi @QuLogic,

I will try straight away although I don't see those in the big classic stylesheet: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/stylelib/classic.mplstyle

Is there a way to find the full documented list of rcParams?

**Comment by KelSolaar** [comment]
Confirming it works, thanks!

**Comment by QuLogic** [comment]
The classic style is there to replicate pre-2.0 style; it shouldn't be taken as a complete listing of rcParams. You can look at the template which should be more comprehensive: https://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template

Closing, as there is nothing to do here.

**Comment by KelSolaar** [comment]
Awesome thanks!

**Comment by jklymak** [comment]
... or https://github.com/matplotlib/matplotlib/blob/a53a04cda6112703b0cd5a1add89a3368df87b0d/lib/matplotlib/rcsetup.py#L967
