### ISSUE TITLE
Undefined names: 'obj_type' and 'cbook'

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#11550]
@anntzer  I thought we had testing in place to catch these kind of errors before PR review.

flake8 testing of https://github.com/matplotlib/matplotlib on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/matplotlib/__init__.py:917:31: F821 undefined name 'obj_type'
                version, key, obj_type, alternative=alt_key)
                              ^
./lib/matplotlib/gridspec.py:279:13: F821 undefined name 'cbook'
            cbook.warn_deprecated("2.2", "fig", obj_type="keyword argument",
            ^
./lib/matplotlib/gridspec.py:369:13: F821 undefined name 'cbook'
            cbook.warn_deprecated("2.2", "fig", obj_type="keyword argument",
            ^
3     F821 undefined name 'obj_type'
3
```

**Comment by anntzer** [comment]
Well, I'm waiting for https://github.com/matplotlib/matplotlib/pull/11477#issuecomment-399709807 to be resolved...
