### ISSUE TITLE
Hoping add a drawing function 'patch'  in matplotlib

### ISSUE THREAD

**Issue by spaceJmmy** [matplotlib/matplotlib#11557]
### Bug report

**Bug summary**

**Code for reproduction**

```
Dear author,
        I encountered a problem in the drawing process. That is, matplotlib can not 
implement the drawing  function of patch which is  available in MATLAB. So sincerely 
hope adding this function.

                                                                        Thanks a lot
```

**Actual outcome**

**Expected outcome**
```MATLAB
like the MATLAB code:

x = (0:100)/20*pi;
y = sin(x);
patch([x nan],[y nan],[y nan],'edgecolor','interp')

```

**Matplotlib version**

  * Operating system: 
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
It seems you are asking for a new feature here. What exactly is this supposed to do? In how far is the existing Line3DCollection (like e.g. [here](https://stackoverflow.com/questions/38079366/matplotlib-line3dcollection-multicolored-line-edges-are-jagged)) not sufficient?

**Comment by dopplershift** [comment]
Here's the [docs](https://www.mathworks.com/help/matlab/ref/patch.html) for MATLAB's `patch` function. I'm not exactly sure how it differs from our `pcolormesh`, but I haven't looked in detail much.

**Comment by jklymak** [comment]
Patch in matlab is the same as patches.Polygon and ax.add_patch.

**Comment by ImportanceOfBeingErnest** [comment]
I interpreted this to ask for a multicolored line, as seen here: https://www.mathworks.com/help/matlab/ref/patch.html#bur94a4-1

but I'm not sure if it is meant to be in 2D or 3D. 

In any case, as it stands, this is sufficiently unclear to cause any further action. @spaceJmmy If you want people to consider putting effort into something you should describe much more in detail what the desired functionality is in how far it would exceed matplotlib's current capabilities.

**Comment by jklymak** [comment]
Does Polygon/Patch do color interpolation?  Doubt it.  

Of course we can create coloured lines.... https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html

**Comment by timhoffm** [comment]
I don't think we have color interpolation along lines.

Here is a complete basic example how to achieve this by coloring interpolated segments. Note that this will not have the best performance, but may serve as a basic workaround for your wish for the time being.

~~~
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection


def colored_line(x, y, c):
    N = 501
    
    xx = np.linspace(x.min(), x.max(), N)
    yy = np.interp(xx, x, y)
    cc = np.interp(xx, x, c)
    
    ax = plt.gca()
    
    points = np.array([xx, yy]).T.reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)
    norm = plt.Normalize(yy.min(), yy.max())
    lc = LineCollection(segments, cmap='viridis', norm=norm)
    lc.set_array(cc)
    line = ax.add_collection(lc)
    
    dots = ax.scatter(x, y, c=y)
    return line, dots


x = np.linspace(1, 10, 15)
y = np.sin(x)
line, _ = colored_line(x, y, y)
plt.colorbar(line)
~~~

![grafik](https://user-images.githubusercontent.com/2836374/42247539-88dd0262-7f21-11e8-8a7d-095d7e6a3d44.png)

**Comment by spaceJmmy** [comment]
@ImportanceOfBeingErnest @dopplershift @jklymak @timhoffm @tacaswell  Thank you all a lot.

In fact, my problem is this, I want to use matplotlib to draw such a picture which drawn from three column vector data, longitude, latitude and flux,

![wanted_result.png](https://raw.githubusercontent.com/spaceJmmy/assets/master/Issue/NOAA5-1502-p7.png)
I tested the code @jklymak @timhoffm  gave, and got the following result pictures,
![test_1.png](https://raw.githubusercontent.com/spaceJmmy/assets/master/Issue/test_1.png)
![test_2.png](https://raw.githubusercontent.com/spaceJmmy/assets/master/Issue/test_2.png)
as you can see, the effect of the result pictures is not ideal, and does not achieve the effect of the first picture, so I hope that your masters can give me some suggestions or solutions. Thank you very much.

**Comment by jklymak** [comment]
I'm going to close, because I don't think there is a bug here. The github group is typically for bug reports and feature requests, and not for user support.  

If you have a question about how to use or configure matplotlib subscribe to the mailing list at: https://mail.python.org/mailman/listinfo/matplotlib-users

Or post a question on https://stackoverflow.com with a `matplotlib` tag.

Thanks again, and we hope you enjoy using matplitlib!
