### ISSUE TITLE
fill_between() misbehaves with unsorted x 

### ISSUE THREAD

**Issue by jrcooper91** [matplotlib/matplotlib#11560]
With the following lines, it doesn't fill in smoothly across the data points - it should make a horn-shaped confidence interval shaded region. I later figured out that this is because the x values are not sorted, either ascending or descending. This doesn't make much sense considering it would be weird to have to sort all of your arrays by x every time you'd like to plot, an nothing else within matplotlib requires this. What's even more odd is that I haven't been able to find this issue brought up either here or anywhere else and it wasn't the easiest to solve. I tried it on another computer and it produced the same result. Using 2.1.4 on OS X 10.10.5, installed via pip. 

`import matplotlib.pyplot as plt`
`x = [1.3593999999999999, 0.20000000000000001, 0.71409999999999996, 0.20000000000000001, 0.76590000000000003, 0.39939999999999998, 0.57030000000000003, 1.0488999999999999, 1.4826999999999999, 0.59440000000000004, 2.8220999999999998, 0.88249999999999995, 3.7656999999999998, 1.1563000000000001, 2.7907999999999999, 1.4410000000000001, 2.9563000000000001, 0.86939999999999995, 3.1839, 0.75829999999999997, 0.85819999999999996, 0.37790000000000001, 1.1896, 1.7965, 0.91549999999999998, 2.21]`
`lcb1 = [1.3067688952908503, 1.339874778521488, 1.331785026924782, 1.339874778521488, 1.3305359570981614, 1.3375340821721677, 1.3347724872284397, 1.321712734320043, 1.2987108276061894, 1.3343175636304379, 1.0504308156182025, 1.3273410291070968, 0.68983888885479838, 1.3172830315683193, 1.0604446149538005, 1.3015974909007677, 1.0055773532242014, 1.3277283035833536, 0.92338804684138087, 1.330725423872702, 1.3280534887915891, 1.3378286868148876, 1.3157634665580598, 1.2704774459609012, 1.3263315018503126, 1.2090045253160648]`
`ucb1 = [2.0158299031159892, 2.5109679867954444, 2.2848243216347939, 2.5109679867954444, 2.2624723586117139, 2.4224583752252604, 2.3473547865007678, 2.1423555756665649, 1.9677102227240464, 2.3368293067845274, 1.6057349567412056, 2.2125421817712132, 1.5364053661884427, 2.0978518628187164, 1.6099820131622795, 1.9838228464918717, 1.5894444305554802, 2.2181235082665989, 1.5679349902859483, 2.2657455916375158, 2.2229012490799205, 2.4319595660703506, 2.0841993352827402, 1.8529705520867856, 2.1985163020001961, 1.7260452664893216]`
`plt.fill_between(x,lcb1,ucb1,)`
`plt.show()`

![bad](https://user-images.githubusercontent.com/31331976/42221894-4a0ae6b8-7e99-11e8-841e-08859a7a3abb.png)

**Comment by jklymak** [comment]
The order of x matters for all sorts of plotting routines, “plot” being the most obvious.  Fill between is one of those routines.  If there is something in the docs that would have made this more clear feel free to comment but closing as I don’t think there is a bug.

**Comment by jrcooper91** [comment]
Thanks for your reply. It's not really a bug just more along the lines of highly inconvenient. I've used a lot of plot routines, and not single one of them requires x to be sorted, and I'm using this exact data set which is not sorted. This is the only routine that can't seem to handle it.

**Comment by jklymak** [comment]
`plt.fill_between(x, lcb1)` will look very different than `plt.plot(x[isort], lcb1[isort])`.   `fill_between` works basically the same way.

**Comment by jrcooper91** [comment]
I'm sorry, but you're really not making sense. plt.plot(x, lcbl) produces a plot exactly how it should look _without_ any sorting of the arrays. My point is that fill_between should work in the same manner, and it doesn't.

**Comment by jklymak** [comment]
Well, maybe I've misunderstood what you want to happen.  Maybe a smaller example (three or four data points) would make it more clear...

**Comment by jrcooper91** [comment]
No worries. I'll post my solution here so that if someone comes across it, I just sorted the arrays. 

`import matplotlib.pyplot as plt
x = [1.3593999999999999, 0.20000000000000001, 0.71409999999999996, 0.20000000000000001, 0.76590000000000003, 0.39939999999999998, 0.57030000000000003, 1.0488999999999999, 1.4826999999999999, 0.59440000000000004, 2.8220999999999998, 0.88249999999999995, 3.7656999999999998, 1.1563000000000001, 2.7907999999999999, 1.4410000000000001, 2.9563000000000001, 0.86939999999999995, 3.1839, 0.75829999999999997, 0.85819999999999996, 0.37790000000000001, 1.1896, 1.7965, 0.91549999999999998, 2.21]
lcb1 = [1.3067688952908503, 1.339874778521488, 1.331785026924782, 1.339874778521488, 1.3305359570981614, 1.3375340821721677, 1.3347724872284397, 1.321712734320043, 1.2987108276061894, 1.3343175636304379, 1.0504308156182025, 1.3273410291070968, 0.68983888885479838, 1.3172830315683193, 1.0604446149538005, 1.3015974909007677, 1.0055773532242014, 1.3277283035833536, 0.92338804684138087, 1.330725423872702, 1.3280534887915891, 1.3378286868148876, 1.3157634665580598, 1.2704774459609012, 1.3263315018503126, 1.2090045253160648]
ucb1 = [2.0158299031159892, 2.5109679867954444, 2.2848243216347939, 2.5109679867954444, 2.2624723586117139, 2.4224583752252604, 2.3473547865007678, 2.1423555756665649, 1.9677102227240464, 2.3368293067845274, 1.6057349567412056, 2.2125421817712132, 1.5364053661884427, 2.0978518628187164, 1.6099820131622795, 1.9838228464918717, 1.5894444305554802, 2.2181235082665989, 1.5679349902859483, 2.2657455916375158, 2.2229012490799205, 2.4319595660703506, 2.0841993352827402, 1.8529705520867856, 2.1985163020001961, 1.7260452664893216]
x = np.array(x)
lcb1 = np.array(lcb1)
ucb1 = np.array(ucb1)
aind = np.argsort(x)
x1=x[aind]
lcb11=lcb1[aind]
ucb11=ucb1[aind]
plt.fill_between(x1,lcb11,ucb11)
plt.show()`

![good](https://user-images.githubusercontent.com/31331976/42225133-6f673738-7ea1-11e8-9feb-26d1fb4af37a.png)

**Comment by jklymak** [comment]
My point before was that if you'd done `plot(x, ucb1)` that gives you a completely differently line than `plot(x[aind], ucb1[aind])`

**Comment by timhoffm** [comment]
The order does play a role for plot. You may not notice this when using just markers for plotting. However, when you use a line, it connects from the first point to the second to the third, no matter what their *x* values are.

~~~
plt.plot(x, lcb1, 'bo', label='unsorted points')
plt.plot(x, lcb1, 'r', label='unsorted line')
~~~
![image](https://user-images.githubusercontent.com/2836374/42231048-c7a2982c-7eea-11e8-9fff-b072197defa4.png)
