### ISSUE TITLE
Setting axis ticks in log scale produces duplicate tick labels.

### ISSUE THREAD

**Issue by szsdk** [matplotlib/matplotlib#11575]
### Bug report

**Bug summary**

Setting axis ticks in a small log scale produces duplicate tick labels.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
s = 10
ax.axis([s, 100, 10, 100])
ax.loglog([20, 30], [30, 40])
from matplotlib.ticker import ScalarFormatter
for axis in [ax.xaxis, ax.yaxis]:
    axis.set_major_formatter(ScalarFormatter())

ax.set_xticks([20, 55])
ax.set_yticks([20, 55])
plt.show()
```

**Actual outcome**
![figure_1](https://user-images.githubusercontent.com/6657200/42314213-26c86c36-8077-11e8-853e-47a387d7d72a.png)

**change code a little bit**
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
s = 9
ax.axis([s, 100, 10, 100])
ax.loglog([20, 30], [30, 40])
from matplotlib.ticker import ScalarFormatter
for axis in [ax.xaxis, ax.yaxis]:
    axis.set_major_formatter(ScalarFormatter())
ax.set_xticks([20, 55])
ax.set_yticks([20, 55])
plt.show()
```

**Expected outcome**
![figure_2](https://user-images.githubusercontent.com/6657200/42314434-91b84156-8077-11e8-8409-aac5a95962c4.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.2.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6

**Comment by ImportanceOfBeingErnest** [comment]
I think there is already an issue about this somewhere around (which I can't find currently).  
For some (maybe desired?) reason, minor ticks are labelled as well, depending on the axis bounds. 

A workaround is to turn them off.

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
s = 10
ax.axis([s, 100, 10, 100])
ax.loglog([20, 30], [30, 40])
from matplotlib.ticker import ScalarFormatter, NullFormatter
for axis in [ax.xaxis, ax.yaxis]:
    axis.set_major_formatter(ScalarFormatter())
    axis.set_minor_formatter(NullFormatter())

ax.set_xticks([20, 55])
ax.set_yticks([20, 55])
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/42344490-c7a6360e-809c-11e8-8591-5dad464c117e.png)

**Comment by tacaswell** [comment]
See https://matplotlib.org/users/dflt_style_changes.html#logformatter-labeling-of-minor-ticks

The underlying issue is we made the defaults better, but did so in a way that broke people's existing work-arounds.

**Comment by timhoffm** [comment]
Related: #13112, #13126.
