### ISSUE TITLE
wx segfault

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#11582]
The following script (opening two figures, and triggering a figure quit via the keyboard shortcut on a timer 1 second after the second figure is drawn) segfaults when used with the wx{,agg} backend.  It works as expected (closing the second figure after 1s) e.g. other backends.

```
from pylab import *

plt.figure()

fig = plt.figure()
timer = fig.canvas.new_timer(1000)
timer.add_callback(fig.canvas.key_press_event, "q")
fig.canvas.mpl_connect("draw_event", lambda event: timer.start())
plt.show()
```

Interestingly, commenting out the first `plt.figure()` (which seemingly plays no role...) removes the segfault.

Noted while working on the tests for #11581.
Matplotlib master on Py3.6/Arch Linux.

**Comment by tacaswell** [comment]
Linked with #11578 ?

**Comment by tacaswell** [comment]
I can reproduce with with 2.2.2 both from pypi and from arch packages (and a range of 4.0.x wxpython versions) so this is not a recent regression on our part.

My guess at what is going on is that as part of closing the second figure we are cleaning up some part of Wx global state that the first figure is still using.  If you don't include the other open figure the state isn't shared and everything exits happily.

I suspect that this is a nastier version of the 'wx segfaults at exit' bug we have had in the past.

**Comment by anntzer** [comment]
Remove the RC tag or not? (I vote for it)
