### ISSUE TITLE
ticklabels font using latex

### ISSUE THREAD

**Issue by photoniker** [matplotlib/matplotlib#11586]
I can not change the fontstyle of the ticklabels to "sans-serif" when using latex. 

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rc
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
rc('text', usetex=True)

def xticklabels_example():
    fig = plt.figure() 
    x = np.arange(20)
    y1 = np.cos(x)
    y2 = (x**2)
    y3 = (x**3)
    yn = (y1,y2,y3)
    COLORS = ('b','g','k')
    for i,y in enumerate(yn):
        ax = fig.add_subplot(len(yn),1,i+1)
        ax.plot(x, y, ls='solid', color=COLORS[i]) 
        if i != len(yn) - 1:
            # all but last 
            ax.set_xticklabels( () )
        else:
            for tick in ax.xaxis.get_major_ticks():
                tick.label.set_fontsize(14) 
                # specify integer or one of preset strings, e.g.
                #tick.label.set_fontsize('x-small') 
                tick.label.set_rotation('vertical')
    fig.suptitle('Matplotlib xticklabels Example')
    plt.show()

if __name__ == '__main__':
    xticklabels_example()
```

**Matplotlib version**
  * Operating system: python 3.6 (itom 3.1.0, www.itom.rocks)
  * Matplotlib version: 2.2.2
  * Python version: 3.6

![pltbug2](https://user-images.githubusercontent.com/17592823/42379259-6ff2d8ac-812a-11e8-83e3-1c2df6c7d6f9.PNG)

**Comment by pharshalp** [comment]
this answer by @mdboom might help... 
https://stackoverflow.com/a/16345065

**Comment by jklymak** [comment]
That makes sense to me.  OTOH, we maybe could do a better job of documenting this.  I don't think its trivial for a user to know that they need to setup TeX by hand this way.

**Comment by pharshalp** [comment]
I am trying to come up with a good documentation entry for this. Found 3 other issues that have the same root cause (i.e. not knowing that changing text font in TeX doesn't automatically change the math font) -- #8436, #6041, #3999.

**Comment by jklymak** [comment]
I think an entry that says “font selection using tex” or some such would be helpful.  Show changing the basic font and the math font.  

Long term I really wonder if the Tex rendering should not consult the non-Tex font selection mechanisms at all, and users should set the preamble by hand to get what they want.  That would reduce confusion in my mind.

**Comment by pharshalp** [comment]
Will work on it in a day or two... looks like I might have to remove some
portions of the existing documentation (seems to be inconsistent with the
stackoverflow answer... will confirm soon). I looked at the “git blame” for
that and it seems to be 10 yrs old!

**Comment by ImportanceOfBeingErnest** [comment]
As commented here, one can turn the use of tex off for the `ScalarFormatter` such that the set font is used for the labels as well.

     ax.xaxis.get_major_formatter()._usetex = False
     ax.yaxis.get_major_formatter()._usetex = False

![image](https://user-images.githubusercontent.com/23121882/43034731-4b3758d0-8ce2-11e8-82be-8cef13fc3259.png)

**Comment by ImportanceOfBeingErnest** [comment]
The ticklabels do use tex, because `text.usetex=True` is set. But they are not rendered in math mode (i.e. the `$` are removed). Hence they use the same font used by the rest of the document, but still through the tex system in use.

**Comment by pharshalp** [comment]
ahh right... that makes sense. But, this won't solve the issue if you have a mathematical formula in the title (or annotations).

**usetex_maths_DejaVu-Sans.png**
![usetex_maths_dejavu-sans](https://user-images.githubusercontent.com/15175620/43032078-88abf718-8c7c-11e8-904e-61813b065753.png)

**usetex_maths_cmbright.png**
![usetex_maths_cmbright](https://user-images.githubusercontent.com/15175620/43032080-89f2c25a-8c7c-11e8-8c26-016b1a2ccc32.png)

**Comment by ImportanceOfBeingErnest** [comment]
In this issue, there is no math mode text used. Hence this would solve this issue.

**Comment by anntzer** [comment]
In theory we could emit something along the lines of `\everymath\expandafter{\the\everymath\sf}` in the TeX preamble in such cases, which would have the effect of defaulting TeX math to sans-serif.
However, note that the *default* font.family is already `sans-serif` (that's why plain text (not math) defaults to a sans-serif font in Matplotlib), so this would effectively affect nearly anyone who is using usetex, even though most users likely associate usetex with the default Computer Modern Roman font (both from classical TeX behavior and from longstanding Matplotlib behavior).  So I guess the question is, is it worth making a breaking change here?
