### ISSUE TITLE
Anaconda qt 5.9.6 conflicts

### ISSUE THREAD

**Issue by Lomelgande** [matplotlib/matplotlib#11639]
### Bug report

When running 

    conda install qt=5.9.6

I am met with the following

    UnsatisfiableError: The following specifications were found to be in conflict:
      - matplotlib -> freetype=2.5
      - matplotlib -> pyqt=4 -> qt==4.8.5
      - qt=5.9.6

I am confused as to both of these conflicts as I have qt 5.9.5 installed and running conda info on qt 5.9.5 shows that it has a freetype dependency of

    freetype >=2.8,<2.9.0a0

It seems like if I have qt 5.9.5 installed I should be able to install qt 5.9.6.

**Comment by jklymak** [comment]
I think this is more appropriately followed up with conda, not matplotlib.  We don't maintain the conda requirements list.
