### ISSUE TITLE
constrained_layout and colorbar for a subset of axes

### ISSUE THREAD

**Issue by dcherian** [matplotlib/matplotlib#11641]
### Bug report

**Bug summary**

constrained_layout seems to place colorbars at the "extreme right" of the image. (not sure how to phrase this; see below)

**Code for reproduction**

```python
f, ax = plt.subplots(2,2, constrained_layout=True)

data = np.random.randn(10, 10)
    
for aa in ax.flat:
    mappable = aa.pcolormesh(data)
    
f.colorbar(mappable, ax=ax[:, 0])
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2448579/42615612-3335ec1e-8568-11e8-9424-dcd4002ed92b.png)

**Expected outcome**

I would like the constrained_layout version of this --- which results when setting `constrained_layout=False` in the `plt.subplots` call above

![image](https://user-images.githubusercontent.com/2448579/42615630-4d06edd2-8568-11e8-9486-ac79f07982c7.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version:  2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.6.5
  * Jupyter version (if applicable): 5.5.0
  * Other libraries:

**Comment by dcherian** [comment]
Thanks, @QuLogic I meant to report that too but forgot.

The behaviour for `[ax[0, 0], ax[1, 1]]` seems reasonable to me; "insert a colorbar with vertical extent bounded by the top and bottom of both axes; and to the right of the rightmost axes"

**Comment by jklymak** [comment]
Colorbar either steals space from an axes or a GridSpec.  If you specify multiple axes in the same GridSpec it steals from the whole GridSpec. 

To get what you want, you need to make a nested GridSpec.

**Comment by jklymak** [comment]
I agree that its inconsistent between `constrained_layout=True` and `constrained_layout=False`.  Its possible I can add this functionality to the `constrained_layout` algorithm, but I'm not sure.

In the meantime, the way to do what you want is indeed a bit longer.  It also loses the idea that the subplots have the same size.  OTOH, if you are adding a colorbar to one column, but not the second, my guess would be they contain different data types.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

fig = plt.figure(constrained_layout=True)
gs0 = gridspec.GridSpec(1, 2, figure=fig )

gsl = gridspec.GridSpecFromSubplotSpec(2, 1, gs0[0])
gsr = gridspec.GridSpecFromSubplotSpec(2, 1, gs0[1])

data = np.random.randn(10, 10)

axs = []
for i in range(2):
    ax = fig.add_subplot(gsl[i])
    mappable = ax.pcolormesh(data)
    axs += [ax]
fig.colorbar(mappable, ax=axs)

for i in range(2):
    ax = fig.add_subplot(gsr[i])
    mappable = ax.pcolormesh(data)

plt.show()
```
![figure_1](https://user-images.githubusercontent.com/1562854/42638365-4a664318-85a2-11e8-8d15-7b5d9818ace2.png)

**Comment by jklymak** [comment]
I think I can make this consistent, but milestoning 3.1 because there is a workaround and its a bit of an obscure use case.

**Comment by dcherian** [comment]
> OTOH, if you are adding a colorbar to one column, but not the second, my guess would be they contain different data types.

Yes, different data types but on the same x,y grid. Practically, the two axes on the right could have a shared colorbar or one colorbar each and that would make the axes the same size which would be fine. My example was over-simplified. The below is what I'm aiming for with the big colorbar for the 2 panels on the left.

```
import matplotlib.pyplot as plt
import numpy as np

f, ax = plt.subplots(2,2, constrained_layout=True)

data = np.random.randn(10, 10)
    
for aa in ax.flat:
    mappable = aa.pcolormesh(data)
    
f.colorbar(mappable, ax=ax[:, 0])
f.colorbar(mappable, ax=ax[0, 1])
f.colorbar(mappable, ax=ax[1, 1])
```

![image](https://user-images.githubusercontent.com/2448579/42650760-7ea621ca-85ca-11e8-93dd-6a2faf6402e3.png)

**Comment by jklymak** [comment]
![figure_1](https://user-images.githubusercontent.com/1562854/42651725-141b4d30-85c5-11e8-9647-e7d07cff06f7.png)

PR, coming, but I need to write some tests and update the guide.

BTW< thanks for giving `constrained_layout` a try!  Please report any other issues so I can keep polishing it...

**Comment by dcherian** [comment]
@jklymak This looks great! Thanks for all your hard work. It has certainly made life a whole lot easier.
