### ISSUE TITLE
Sequential boxplot call edits xticklabels and xlim attributes

### ISSUE THREAD

**Issue by qmarcou** [matplotlib/matplotlib#11655]
### Bug report

**Bug summary**
I have tried to make sequential calls to boxplot to create a line plot with a boxplot (instead of error bar as my data is clearly not normally distributed) at each x position. I was surprise to see that only the last boxplot is visible at the end. It seems that each call to boxplot edits the xlabel and change the xlim attribute of the concerned axis. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1,1)
ax.set_xlim(0,3) #Set xlim before to show that the xlim is changed
ax.boxplot([1,2,3,4,5,6],positions=[1])
ax.boxplot([1,2,3,4,5,6],positions=[2])
plt.show()
```

**Actual outcome**
 xlim have been changed and only boxplot at position 2 is visible:
![image](https://user-images.githubusercontent.com/18257721/42721124-b48bb4b0-8702-11e8-8360-adf81edcd2dd.png)

Upon moving the `ax.set_xlim(0,3)` line after the second boxplot creation:
```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1,1)
ax.boxplot([1,2,3,4,5,6],positions=[1])
ax.boxplot([1,2,3,4,5,6],positions=[2])
ax.set_xlim(0,3) #Set xlim after to show that xticklabel has been messed with
plt.show()
ax.get_xticklabels() #Check the number of ticklabel objects present
```
 one obtains:
Console output: `<a list of 1 Text xticklabel objects>`
Plot :
![image](https://user-images.githubusercontent.com/18257721/42721119-6f8d53c8-8702-11e8-9089-45caaad9b189.png)

 The label '1' of the first boxplot is missing, showing that the xticklabel has been messed with upon creation of the second boxplot:

**Expected outcome**
The expected outcome is the one produced by the following code:
```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1,1)
ax.boxplot([[1,2,3,4,5,6],[1,2,3,4,5,6]],positions=[1,2])
ax.set_xlim(0,3) #Set xlim before to show that the xlim is changed
plt.show()
ax.get_xticklabels() #Check the number of ticklabel objects present
```
Console output: `<a list of 2 Text xticklabel objects>`
Obtained plot:
![image](https://user-images.githubusercontent.com/18257721/42721111-42fa2f0c-8702-11e8-826c-0a929434e5ad.png)

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 2.2.2 (initially noticed on 1.5.3)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg or module://ipykernel.pylab.backend_inline
  * Python version: 2.7.15

**Comment by qmarcou** [comment]
As a side note, this issue is not present in the similar plotstyle violinplots:
```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1,1)
ax.set_xlim(0,3) #Set xlim after to show that xticklabel has been messed with
ax.violinplot([1,2,3,4,5,6],positions=[1])
ax.violinplot([1,2,3,4,5,6],positions=[2])
plt.show()
ax.get_xticklabels()
```
Console output: `<a list of 7 Text xticklabel objects>`
Plot:
![image](https://user-images.githubusercontent.com/18257721/42724310-d62a80c0-873d-11e8-93d9-0def058e0f2f.png)

**Comment by jklymak** [comment]
Did you try `manage_xticks=False`?    It looks like `box plot` takes over the tick management wo it can label each box on the axes.  It can't do that, *and* know about other `boxplots`.  So I think the choices are either turn off the tick management or pack your data into a 2-D array instead of just a vector.

**Comment by qmarcou** [comment]
Woups my bad I did not see the kwarg option... Thanks!
However, wouldn't it make more sense to default this option to `False`? I mean this makes the API quite inconsistent (and counter intuitive) with violinplots (which is very similar in essence) for instance and the rest of the matplotlib plotting functions

**Comment by jklymak** [comment]
Someone made that decision when the kwarg was introduced.  I don't think its such a big deal that we'd break old code to change it.

**Comment by tacaswell** [comment]
IIRC, the behavior of boxplot was always to take over the ticks and the kwarg gave you an escape hatch to _not_ have it change.  We did not make it False by default for exactly the back-compatibility issues that @jklymak mentions.

In many cases, when you are passing in a bunch of data, managing the xticks is what you want (as it 'does the right thing' and ensures that the ticks are on the boxes and I think you can pass in a list of strings to label them with).

@qmarcou You may be interested in `Axes.bxp` which will draw the box plots, but expect pre-reduced data.
