### ISSUE TITLE
Error using LaTex font in matplotlib

### ISSUE THREAD

**Issue by LuigiFilippoChiara** [matplotlib/matplotlib#11668]
### Bug report

**Bug summary**

Hi everybody,
I would like to print some figures with Matplotlib using a Latex font. I’m trying to run the test code demo_tex.py which I found at http://matplotlib.org/users/usetex.html, but i get a huge error ending in " FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex' ". This is the first time I have an error using Matplotlib, it has always worked perfectly.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

# Example data
t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(4 * np.pi * t) + 2

plt.rc('text', usetex=True)
plt.plot(t, s)

plt.show()
```

**Actual outcome**

```
runfile('/Users/Filippo/AnacondaProjects/Python/Advanced_Solids_Mechanics/demo_tex.py', wdir='/Users/Filippo/AnacondaProjects/Python/Advanced_Solids_Mechanics')
Traceback (most recent call last):

  File "/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)

  File "/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 241, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 125, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2212, in print_figure
    **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 513, in print_png
    FigureCanvasAgg.draw(self)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1192, in draw
    renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1130, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 922, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 309, in _get_layout
    ismath=ismath)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 232, in get_text_width_height_descent
    s, fontsize, renderer=self)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 501, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 365, in make_dvi
    texfile], tex)

  File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 335, in _run_checked_subprocess
    stderr=subprocess.STDOUT)

  File "/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout

  File "/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:

  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

<Figure size 432x288 with 1 Axes>
```

**Expected outcome**

A figure with a cosine should appear. xlabel and ylabel should have Latex font.

**Detailed description**

I looked a lot in the internet but no solution worked for me so far.
My matplotlib configuration and cache directories are both located in '/Users/Filippo/.matplotlib’, where I also tried to remove the file tex.cache (without any success).
I obtained Matplotlib from Anaconda, I didn’t add any customizations to my matplotlibrc (in fact, I don’t know how to use matplotlilrc).
Matplotlib installing location: '/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py’

I installed Latex using the latest version of MacTex and TexMaker. I verified that dvipng was installed too. I used home-brew to install the latest version of ghostscript (9.23). Ghostscript is now installed in the following location:
/usr/local/Cellar/ghostscript/9.23

These are the locations of latex, dvipng, python and ghostscript:
![screen shot 2018-07-15 at 16 34 07](https://user-images.githubusercontent.com/41269743/42737083-288c2a34-8870-11e8-9e4f-30e18fcf95d7.png)

I’m not really sure if latex, dvipng and ghostscript  are really working on my PATH. They work whenever I call them from the command line, as in the following examples:

![screen shot 2018-07-15 at 16 39 13](https://user-images.githubusercontent.com/41269743/42737088-3e1b4b64-8870-11e8-810b-3c83e76fb445.png)

![screen shot 2018-07-15 at 16 39 21](https://user-images.githubusercontent.com/41269743/42737089-432a173e-8870-11e8-898f-cc6ff8b395d6.png)

![screen shot 2018-07-15 at 16 39 18](https://user-images.githubusercontent.com/41269743/42737091-4ae457e6-8870-11e8-805e-3981ebe14eab.png)

I don’t know if this was useful but I tried to link them to my PATH modifying my .bash_profile in the following way (I have the same error using Matplotlib even If don’t link them in this way)(Anaconda wrote automatically the first two lines when I installed it):

![screen shot 2018-07-15 at 16 41 45](https://user-images.githubusercontent.com/41269743/42737094-54ed15a2-8870-11e8-8b64-70809ce8ead3.png)

I tried to do everything that I could, but I still unable to run Matplotlib and have a Latex font.
What can I do?
If you need more information just tell me.
Thank you very much for your help!

Filippo

**Matplotlib version**

  * Operating system: macOS High Sierra version 10.13.5
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Spyder version: 3.2.8

I got my matplotlib from Anaconda3.

**Comment by marco1m** [comment]
I have the same error. Did you resolve it?

**Comment by anntzer** [comment]
What happens if you do, from a Python prompt, `import subprocess; subprocess.check_call("latex")`?

**Comment by ewquon** [comment]
I'm having the same problem. The output is:

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-31-1d523de1ec75> in <module>
> ----> 1 import subprocess; subprocess.check_call("latex")
> 
> ~/anaconda3/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
>     334     check_call(["ls", "-l"])
>     335     """
> --> 336     retcode = call(*popenargs, **kwargs)
>     337     if retcode:
>     338         cmd = kwargs.get("args")
> 
> ~/anaconda3/lib/python3.7/subprocess.py in call(timeout, *popenargs, **kwargs)
>     315     retcode = call(["ls", "-l"])
>     316     """
> --> 317     with Popen(*popenargs, **kwargs) as p:
>     318         try:
>     319             return p.wait(timeout=timeout)
> 
> ~/anaconda3/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
>     767                                 c2pread, c2pwrite,
>     768                                 errread, errwrite,
> --> 769                                 restore_signals, start_new_session)
>     770         except:
>     771             # Cleanup if the child failed starting.
> 
> ~/anaconda3/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
>    1514                         if errno_num == errno.ENOENT:
>    1515                             err_msg += ': ' + repr(err_filename)
> -> 1516                     raise child_exception_type(errno_num, err_msg, err_filename)
>    1517                 raise child_exception_type(err_msg)
>    1518 
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

**Comment by ewquon** [comment]
Perhaps this will give someone some insight... I get the error in a jupyter notebook, but the error goes away if I include the `%matplotlib inline` directive.

**Comment by er9** [comment]
> What happens if you do, from a Python prompt, `import subprocess; subprocess.check_call("latex")`?
I also obtained the error above.  But if I called "latex.exe" I was able to interact with MikTex.

I'm on the linux subsystem for windows, and what I did is install another tex library using
`sudo apt-get install texlive dvipng texlive-latex-extra texlive-fonts-recommended`
It's not a great solution but it worked...

**Comment by ewquon** [comment]
Okay, I think my environment was screwed up... I reinstalled some packages (I can no longer remember which ones) and the problem went away and I am no longer able to reproduce the error within Python/IPython/Jupyter.

**Comment by junbinhuang** [comment]
In my case, this issue can be resolved if the yourFile.py is launched from Terminal: (Of course, first cd to the file dir.)
`idle3 yourFile.py`
Instead, if idle is launched by double-clicking the yourFile.py file, the same FileNotFoundError occurs.
Using VS Code with Python support can also resolve this issue.
Hence, the cause of this issue is probably due to that the PATH is not sent to Matplotlib when idle is launched directly.

**Comment by xhain** [comment]
Did anyone ever solve this?

```
(base) max@MaxMBP17:~/Documents/Jobs/Flowkey/PyNoteDetection$ which latex
/Library/TeX/texbin/latex
(base) max@MaxMBP17:~/Documents/Jobs/Flowkey/PyNoteDetection$ which dvipng
/Library/TeX/texbin/dvipng
(base) max@MaxMBP17:~/Documents/Jobs/Flowkey/PyNoteDetection$ which python
/anaconda3/bin/python
```

Error:

> Traceback (most recent call last):
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
>     self.draw()
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
>     self.figure.draw(self.renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
>     renderer, self, artists, self.suppressComposite)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
>     mimage._draw_list_compositing_images(renderer, self, artists)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1187, in draw
>     renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1125, in _get_tick_bboxes
>     extent = tick.label1.get_window_extent(renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 930, in get_window_extent
>     bbox, info, descent = self._get_layout(self._renderer)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 313, in _get_layout
>     ismath=ismath)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 209, in get_text_width_height_descent
>     s, fontsize, renderer=self)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 464, in get_text_width_height_descent
>     dvifile = self.make_dvi(tex, fontsize)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 328, in make_dvi
>     texfile], tex)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 298, in _run_checked_subprocess
>     stderr=subprocess.STDOUT)
>   File "/anaconda3/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/anaconda3/lib/python3.6/subprocess.py", line 423, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/anaconda3/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/anaconda3/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

Running `plt.rc('text', usetex=True)` for some publication ready plots in spyder on OSX

**Comment by anntzer** [comment]
As a general rule, you need to be able to run latex from python to use usetex mode.  So if `import subprocess; subprocess.check_call(["latex"])` fails with a FileNotFoundError, the problem is with the interaction between your python install and your tex install, not on Matplotlib's side.

**Comment by TangeniThePyGuru** [comment]
> > What happens if you do, from a Python prompt, `import subprocess; subprocess.check_call("latex")`?
> 
> I also obtained the error above. But if I called "latex.exe" I was able to interact with MikTex.
> 
> I'm on the linux subsystem for windows, and what I did is install another tex library using
> `sudo apt-get install texlive dvipng texlive-latex-extra texlive-fonts-recommended`
> It's not a great solution but it worked...

Initially, I was actually trying to run latex from Jupyter notebook or terminal, meanwhile I was doing it wrong. It should be run from the actual UBUNTU terminal.

Thanks this installation is part of what i missed, it worked for me.
