### ISSUE TITLE
doc - Simplify backend description in tutorials/introductory/usage.html for beginners

### ISSUE THREAD

**Issue by kschleicher** [matplotlib/matplotlib#11665]
### Bug report

read https://matplotlib.org/tutorials/introductory/usage.html#backends in your browser

**Matplotlib version**
<!- matplotlib.__version__ 2.1.1 ->
 
tutorials/introductory/usage.html targets beginners.  Provide a simple table or decision tree to help select backend based criterion like:
-OS
-if code is a script, ipython session, or jupyter notebook

Clean up there backend discussion and move it to a more advanced document.

**Comment by tacaswell** [comment]
Thanks @kschleicher It was great to work with you at the scipy sprints.

**Comment by kschleicher** [comment]
Thomas,

Thanks for all the help.  Maybe I can find time to help on documentation.

Karl



________________________________

**Comment by timhoffm** [comment]
The above link is now redirected to https://matplotlib.org/stable/users/explain/quick_start.html, which does not touch backends at all. Backend documentation is now separated into https://matplotlib.org/stable/users/explain/figure/backends.html.

Therefore, the issue is resolved.

**Comment by QuLogic** [comment]
> Therefore, the issue is resolved.

Did you mean to close, then?
