### ISSUE TITLE
Matplotlib markers streched

### ISSUE THREAD

**Issue by gopi1616** [matplotlib/matplotlib#11675]
![wespp_frequency_comparison](https://user-images.githubusercontent.com/11431678/42780344-8bf0b962-8908-11e8-948c-50770590599f.png)

### Bug report

When I do scatter plot with matplotlib using python2.7 there was no issue but while trying the same code with python3.6 I got following error:

plt.figure(figsize=(8,8))
  File "/usr/local/python/3.6.3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/usr/local/python/3.6.3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/python/3.6.3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/local/python/3.6.3/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

I used import matplotlib; matplotlib.use('Agg') in my script per suggestion from 
https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

It worked but I got image like this with streched markers.

Matplotlib scatter markers streched

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
If you leave the sections "Code for reproduction" and "Matplotlib version" empty, there is little one can do about your issue. But it does not actually look like it's a problem with matplotlib itself, but rather with the code in use. You may find asking a question about your problem (including a minimal runnable example) on stackoverflow more helpful than attempting to report your problem as issue here, which it most probably isn't anyways.

**Comment by jklymak** [comment]
Closing becaue no matplotlib bug isolated...  Feel free to modify with a  Short, self-containted, correct, example (http://sscce.org) and request a reopen.  Thanks!

**Comment by WeatherGod** [comment]
I am really curious how this happened.
