### ISSUE TITLE
The rcParams setting for figure.figsize does not change when run from another notebook

### ISSUE THREAD

**Issue by gregtam** [matplotlib/matplotlib#11693]
### Bug report

**Bug summary**

If you have a Jupyter notebook that establishes matplotlib rcParams and call the notebook from another (using `%run` ), the `figure.figsize` setting will only update when the `%run` command is executed twice. 

**Code for reproduction**

`matplotlib_settings.ipynb` - This notebook establishes the plot settings
```
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (10, 8)
print(plt.rcParams['figure.figsize'])
```

`matplotlib_import.ipynb` - This notebook runs the `matplotlib_settings.ipynb` notebook.

*First Cell:*

```
# First cell
%run matplotlib_settings.ipynb

print('Strangely enough, it changes in the cell that it was run in.')
print(plt.rcParams['figure.figsize'])
```
Output:
```
[10.0, 8.0]
Strangely enough, it changes in the cell that it was run in.
[10.0, 8.0]
```

*Second Cell:*
When run in a second cell, the settings have not changed.
```
# Second cell
print('But not in any other cells.')
print(plt.rcParams['figure.figsize'])
```
Output:
```
But not in any other cells.
[6.0, 4.0]
```

For most of the `rcParams` settings (as far as I can tell), they will function properly and be changed, but it does not seem to work for `figure.figsize`.

**Matplotlib version**
  * Operating system: Mac OS X version 10.12.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.6.5 (but also applied to Python 2.7.14)
  * Jupyter version (if applicable): 1.0.0

This was installed using Anaconda Python 3

**Comment by jklymak** [comment]
This is probably a jupyter issue...  Feel free to ask to reopen if you think we can help...
