### ISSUE TITLE
Setting alpha on legend handle changes patch color

### ISSUE THREAD

**Issue by bpteague** [matplotlib/matplotlib#11702]
### Bug report

**Bug summary**

I occasionally want the alpha value of the patch in a histogram's legend to be different than the alpha value used to plot the legend.  However, when I call `set_alpha` on a legend handle, the color of the patch in the legend changes.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.hist([1, 2, 3], alpha = 0.25, label = 'data', color = 'red')
legend = plt.legend()
for lh in legend.legendHandles:
    lh.set_alpha(1.0)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2431900/42916377-e3e2c770-8ad2-11e8-9a9d-77f0db02e7a2.png)

**Work-around**

I can get the result I desire if I call `set_edgecolor()` and `set_facecolor()`:

```python
plt.hist([1, 2, 3], alpha = 0.25, label = 'data', color = 'red')
legend = plt.legend()
for lh in legend.legendHandles:
    lh.set_facecolor(lh.get_facecolor())
    lh.set_edgecolor(lh.get_edgecolor())
    lh.set_alpha(1.0)
```

**Expected outcome**

![image](https://user-images.githubusercontent.com/2431900/42916427-26b11bd8-8ad3-11e8-8a68-d6fc1a08efeb.png)

**Matplotlib version**
- Matplotlib v2.2.2
- Installed from Anaconda (default channel)
- Backend: module://ipykernel.pylab.backend_inline
- Jupyter version: 5.5.0

**Comment by bpteague** [comment]
Seems related to the following lines in `matplotlib.patches.set_alpha`:
```python
        self._set_facecolor(self._original_facecolor)
        self._set_edgecolor(self._original_edgecolor)
```
because both `self._original_facecolor` and `self._original_edgecolor` are set to `None`.

**Comment by jklymak** [comment]
Huh, I thought we squashed that bug.  Anyway, the fix is to have the `_original_face/edgecolors` set in `set_color`  few lines after.  Want to make a PR?

**Comment by bpteague** [comment]
It looks like `set_color()` calls `set_edgecolor()` and `set_facecolor()`, which already update `_original_edgecolor` and `_original_facecolor` respectively.  

Perhaps `set_color()` isn't getting called as the legend is being set up?  I tried digging through the legend code, but I don't understand `matplotlib`'s internals terribly well and got rather lost.

**Comment by jklymak** [comment]
Ooops.  Yes, you are right.  Chasing through legend isn't pretty...

**Comment by jklymak** [comment]
See #11703 - looks like it fixes the problem to me... Thanks for the great report.

**Comment by bpteague** [comment]
Brilliant.  #11703 fixes this for me too.  Thanks for digging into this for me (-:

**Comment by jklymak** [comment]
Ha we only get to close it when the PR gets merged :wink:

**Comment by bpteague** [comment]
I just got so excited!  An hour from report to fix is pretty remarkable.  Thanks again.

**Comment by jklymak** [comment]
Well, I was annoyed, because I fixed that bug 6 months ago (for markers instead of bars)...

**Comment by boyob** [comment]
![1](https://user-images.githubusercontent.com/24429461/55476652-c0dfbb00-5649-11e9-8d6a-ec18b83b256d.png)
How to change the color of font in legend?

**Comment by timhoffm** [comment]
@boyob This is the bug tracker. For help, please use gitter, the mailinglist or stackoverflow. https://matplotlib.org/#need-help
