### ISSUE TITLE
memory leak in pylab.specgram

### ISSUE THREAD

**Issue by liaoyd16** [matplotlib/matplotlib#11719]
### Bug report

**Bug summary**

When called repeatedly, pylab.specgram(x) would quickly run out of memory by producing functions, dicts and lists uncollected by python garbage collection. (In comparison, scipy.signal.spectrogram does not produce such uncollected objects.)

**Code for reproduction**

```python
import pylab
import wave
import scipy.signal as signal
import objgraph

wav_file = "sample.wav"

def get_wav_info(wav):
    frames = wav.readframes(-1)
    sound_info = pylab.fromstring(frames, 'int16')
    frame_rate = wav.getframerate()
    wav.close()
    return sound_info, frame_rate

def test_pylab_specgram():
    print("test pylab.specgram")
    for i in range(100):
        print("\t", objgraph.most_common_types(limit=2))
        f = wave.open(wav_file)
        sound_info, frame_rate = get_wav_info(f)
        spec = pylab.specgram(sound_info, Fs=frame_rate)
        print("\t", objgraph.most_common_types(limit=2), "\n")

def test_scipy_spectrogram():
    print("test scipy.spectrogram")
    for i in range(100):
        print("\t", objgraph.most_common_types(limit=2))
        f = wave.open(wav_file)
        sound_info, frame_rate = get_wav_info(f)
        spec = signal.spectrogram(sound_info, fs=frame_rate)
        print("\t", objgraph.most_common_types(limit=2), "\n")

test_scipy_spectrogram()
test_pylab_specgram()
```

**Outcome**

pylab.specgram(x):
before running: [('function', 16050), ('dict', 6778)]
after running: [('function', 16160), ('dict', 8845)]
scipy.signal.spectrogram(x):
before running: [('function', 16050), ('dict', 6777)]
after running: [('function', 16050), ('dict', 6781)] 

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 2.2.2
  * Matplotlib backend: MacOSX
  * Python version: 3.6.5
  * Other libraries: wave

matplotlib installed via pip3

**Comment by liaoyd16** [comment]
[issue.zip](https://github.com/matplotlib/matplotlib/files/2215935/issue.zip)

**Comment by ImportanceOfBeingErnest** [comment]
Are you comparing a function that produces a matplotlib figure (`pyplot.specgram`) with one that does not produce any matplotlib figure (`scipy.signal.spectrogram`)?

If so, to be fair you need to close the figure (`pylab.close()`) before doing the comparisson. Or, inversely, you need to actually plot the output of `scipy.signal.spectrogram` to a figure, e.g. using `pcolormesh`.

(Btw. [best don't use `pylab`](https://matplotlib.org/devdocs/api/api_overview.html#the-pylab-api-disapproved), better use `pyplot`)

**Comment by jklymak** [comment]
I'm going to close because I think this is just the memory needed for the plots...

**Comment by QuLogic** [comment]
If you use `pyplot` instead of `pylab`, there is no leak, at least as measured here. I did not look any further into it, as I don't think `pylab` is worth it any more.

**Comment by jklymak** [comment]
Did you close the figures?   If not, it’s not a memory leak.  Figures take up memory.

**Comment by liaoyd16** [comment]
with close() called, memory is still not cleaned.
```python

import matplotlib.pyplot as plt
import numpy as np


import pylab

import scipy
from scipy import io
import scipy.io.wavfile
import scipy.signal as signal


import cv2

import objgraph


NFFT = 2048


objgraph.show_most_common_types(limit=2)

Fs, x = scipy.io.wavfile.read('demo.wav')

objgraph.show_most_common_types(limit=2)

Sxx, _, _, _ = plt.specgram(x, Fs=Fs, NFFT=NFFT, noverlap=1900)
objgraph.show_most_common_types(limit=2)

plt.close()

objgraph.show_most_common_types(limit=2)

**Comment by liaoyd16** [comment]
Wondering how @QuLogic 's code looks like?

**Comment by liaoyd16** [comment]
It's great! with plt.close('all'), gc.collect() added it works!
