### ISSUE TITLE
Rendering of the api documentation

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#11727]
I have looked into the rendering of the matplotlib modules in the documentations. The goal should be to have:
- easy to read documentation.
- easy to get an overview of classes and functions. 
- easy to find related examples and tutorials.
- limit manual work. 

I would say that some modules, like the the `axes` module, is well documented (but quite a lot of manual work where probably needed) but some other like the [collections](https://matplotlib.org/2.2.2/api/collections_api.html#module-matplotlib.collections) module is not. It is really difficult to get any sort of overview when everything is in one file without any links. 

I have tried some different solutions:
- [automodapi](https://11885-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/transformations.html#module-matplotlib.transforms)
   - Mostly automatic but some classes and functions that are imported needs to be taken away manually.
   - All classes on a single page but there are links to the methods.
   - Attributes are included (I am not sure if there are a option to not include them)
   - No automatic links to examples
- automodsumm
   - should work as automodsummary but it doesn't at the moment but maybe later. 
   - The templates below should result in the same result with automodsumm
- [autosummary with templates, one file](https://11885-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/colors_api.html#module-matplotlib.colors)
    - The result is similar to automodapi
    - Same manual work is needed on the first page with an autosummary
       - most of the time easy with a simple script or using dir.
    - Links to examples are included.
       - sometimes the same examples appear several times...  (with the actual implementation)
    - Links make it possibly to get an overview
    - One file make it easier to skim through many docstrings fast
    - Probably good for relative small classes
- [autosummary with templates, many files](https://11885-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/figure_api.html)
     - Some manual work needed on the first page
     - Good overview
     - Might result in many clicks when looking through a class
     - links to examples included
     - The documentation probably takes much longer to build

The code can be found in #11595

Some questions:
- What is best?
   - Many pages?
   - A single page for a class?
- Should attributes be included in the documentation?
- Should inherited members always be included? 
   - I guess so but this result in same methods being documentated many times and might clutter the 
     more important methods for some classes.
- Automatic vs manual work?
- Should the signature be included in the autosummary lists?

Some discussion in #11572

**Comment by ImportanceOfBeingErnest** [comment]
The above is a nice summary, it would be useful to include which of those solutions require an additional dependency.

As commented elsewhere already, in my opinion, any solution which does not require to manually list the classes and methods is preferrable. 

I also think it should be possible to include examples with automodapi or automodsumm; essentially it should be possible to tell it to use a custom template instead of the default one somehow (finding out how exactly would be useful here).

**Comment by fredrik-1** [comment]
I looked into templates with `automodsumm` and wrote a solution that worked on my computer.  The problem seemed to be one line that I don't understand why it is needed but sphinx use it in autosummary and that the rendering code where not run recursively (the file class_name.rst in _as_gen where not run through sphinx so the next level pages where not rendered). 

I guess that my template `autoclass_onefile.rst` might work with `automodsumm`. I can test it.

I wrote a pull request but I haven't heard anything yet. The code was also tested on many different sphinx and python versions and it failed on many of them...

**Comment by timhoffm** [comment]
Thanks for the summary. That's a helpful overview.

#### Dependencies

`automodapi` and `automodsumm` are part of the [sphinx-automodapi](https://github.com/astropy/sphinx-automodapi/) package, i.e. this is an additional dependency. I'm ok with adding this dependency. It's only needed when building the docs, so it should not affect a regular user.

#### Granularity of pages

It would be helpful if we can define the granularity for different parts of the documentation seprately: 
- one module per page (e.g. [matplotlib.scale](https://matplotlib.org/devdocs/api/scale_api.html))
- one class per page (e.g. from above [matplotlib.transforms](https://11885-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/transformations.html#module-matplotlib.transforms))
- one method per page (e.g. [Axes](https://matplotlib.org/devdocs/api/axes_api.html))

*Is that something that can be achieved with the above options?*

*Is it possible to mix these options? E.g. could we use `automodapi` for most modules and switch to `automodule` with a custom template if we need more control?*

#### Remark on structure

Generally, I would like to separate the API documentation from more explanatory parts. E.g. https://github.com/matplotlib/matplotlib/blob/master/doc/api/animation_api.rst is a mixture of explanatory text and API docs. IMO, the API doc .rst files should usually not contain any extra text. A few introductory sentences may come from the module docstring. But everything else should be in a separate file - either as part of a tutorial or in separate functionality-centered part of the documentation (.rst file).

**Comment by tacaswell** [comment]
I am OK with this having been closed.  I think in the intervening years we have made some improvements to the API docs.  If we wanted to look at moving to another auto-generation tool, we should probably start fresh as I think the tool landscape has also changed in the last 5 years.
