### ISSUE TITLE
New mode between non-interactive and interactive?

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#11725]
I think that it would be useful to have a third interactive mode. It already kind of exist when `%matplotlib` attach the `_needmain` attribute to `plt.show` but it is kind of hacky because of the need for a try block and there is no information about the property in `pyplot`. 

I want the `plt.show()` behavior when `%matplotlib` has been used without the need to use IPython or `%matplotlib` because I don't think that it make sense to let `plt.show()` block by default in an interactive python session.

In detail I propose the following:
- non-interactive mode
  -plt.show() block by default
- in between mode
  - as non-interactive mode with the difference that plt.show() don't block by default.
- interactive mode as it is today. 

This would result in a consistent behavior between vanilla python and IPython with and without %matplotlib. 

This can of course also just be a property on `plt.show`. 

I believe this would be useful when running the same scripts in different ways so that you don't need to change the `plt.show` `block` parameter. The problematic case is if you want to run python interactively but matplotlib non-interactive. Then is it necessary to use `plt.show(False)` to get expected behavior and change this if you want to run the same script in non-interactive python.

It might even be possibly to get this behavior by default if matplotlib knows if the python session is interactive or not.

**Comment by WeatherGod** [comment]
we already have this, if I understand you correctly. Call `plt.ion()`.

**Comment by fredrik-1** [comment]
No, that is not what I mean. `plt.ion()` put you in interactive mode (automatic plotting after each command) `plt.show` is not needed and don't block if it is used anyway. 

I am thinking about a possibility of being in matplotlib non-interactive mode when `plt.show` is needed but don't block by default.

It is possible to get into that mode now by using:
```
#in IPython
%matplotlib
plt.ioff()
# in all python
plt.ioff() #if on before
plt.show._needmain=False
```
But the last one are not public and impossibly to know if you don't look into the source code for `%matplotlib` or `backend_bases`

**Comment by fredrik-1** [comment]
I have read parts of #4779 but I have to admit that I think the issues about interactivity is confusing and interactive plotting on my windows computer with standard python 3.6 don't even work due to a known bug.

What I am suggesting is to make a public api to the `plt.show._needmain` property that %matplotlib sets so that the behavior with and without using %matplotlib can be the same. 

One questions that pop up now is if it still is safer to use IPython for interactive plotting or if interactive plotting is also supposed to work with standard python? Issues from 4-5 years ago suggest that interactive plotting at that time where only supposed to work with IPython. 

I don't want the windows to pop up but I want the possibility to work in an interactive python environment and decide when I want the figures to update by using `plt.show()` instead of `plt.show(False)`.

**Comment by tacaswell** [comment]
The windows bug will be fixed in the next cpython patch release (https://github.com/python/cpython/pull/7978).

Given that bug in cpython, I would suggest using IPython for interactive plotting.  They explicitly make sure that the input hooks are installed so that the interlacing of the GUI loop and the prompt loop is done correctly.   With the cpython prompt you are at the mercy of the GUI framework correctly installing the input hook (which _most_ do).

I do not disagree that interactivity is confusing!  I still am not sure I understand the functionality you are asking for.  Is this a GUI version of the `inline` backend (visible snap shot, but 'dead')?

**Comment by fredrik-1** [comment]
I am suggesting something like [this](https://github.com/matplotlib/matplotlib/compare/master...fredrik-1:interactive). This works as I want in IPython and python 3.5 on windows. 

But I am actually happy with using interactive mode in IPython or spyder but I believe that this new mode can be useful, having interactive GUI windows that don't block the python prompt by default but don't update automatically after each plot command.

**Comment by jklymak** [comment]
I'm going to close for lack of response, but feel free to recomment if there is a clear proposal...
