### ISSUE TITLE
pgf backend doesn't make background transparent

### ISSUE THREAD

**Issue by klicperajo** [matplotlib/matplotlib#11738]
### Bug report

**Bug summary**

When using the pgf backend the background cannot be set to transparent.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.use('pgf')

import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(range(10))
fig.savefig(f"test.png", transparent=True)

```

**Actual outcome**

A figure with white background.

**Expected outcome**

A figure with transparent background. This works when using a different backend (i.e. commenting out `mpl.use('pgf')`).

**Matplotlib version**
  * Operating system: Windows 10 x64
  * Matplotlib version: 2.1.1 (installed with pip)
  * Matplotlib backend: pgf
  * Python version: 3.6.4

**Comment by dstansby** [comment]
It looks like you're using an old version of Matplotlib; the most recent version is `2.2.2`. Please could you upgrade to Matplotlib `2.2.2` and let us know if there is still a problem?

**Comment by anntzer** [comment]
I can repro the OP's the issue with 3.0.2.

**Comment by klicperajo** [comment]
I can still reproduce this with matplotlib 3.2.0 (Anaconda, Python 3.7.3, Ubuntu 16.04).

**Comment by AlexMiessen** [comment]
This bug still persists with python 3.7.7, Matplotlib 3.3.2 on macOs Big Sur 11.1.

**Comment by anntzer** [comment]
Looks like the magic invocations are
```patch
diff --git i/lib/matplotlib/backends/backend_pgf.py w/lib/matplotlib/backends/backend_pgf.py
index 110b47c35..0e2f75151 100644
--- i/lib/matplotlib/backends/backend_pgf.py
+++ w/lib/matplotlib/backends/backend_pgf.py
@@ -166,7 +166,7 @@ def make_pdf_to_png_converter():
     """Return a function that converts a pdf file to a png file."""
     if shutil.which("pdftocairo"):
         def cairo_convert(pdffile, pngfile, dpi):
-            cmd = ["pdftocairo", "-singlefile", "-png", "-r", "%d" % dpi,
+            cmd = ["pdftocairo", "-singlefile", "-transp", "-png", "-r", "%d" % dpi,
                    pdffile, os.path.splitext(pngfile)[0]]
             subprocess.check_output(cmd, stderr=subprocess.STDOUT)
         return cairo_convert
@@ -180,7 +180,7 @@ def make_pdf_to_png_converter():
                    '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dNOPROMPT',
                    '-dUseCIEColor', '-dTextAlphaBits=4',
                    '-dGraphicsAlphaBits=4', '-dDOINTERPOLATE',
-                   '-sDEVICE=png16m', '-sOutputFile=%s' % pngfile,
+                   '-sDEVICE=pngalpha', '-sOutputFile=%s' % pngfile,
                    '-r%d' % dpi, pdffile]
             subprocess.check_output(cmd, stderr=subprocess.STDOUT)
         return gs_convert
```
Come claim your free PR :)

**Comment by klicperajo** [comment]
Have you tested this properly? If so, why don't you just put it into a PR yourself? Wouldn't want to steal someone else's credit. :)

**Comment by anntzer** [comment]
Because I believe I already have all the credit I need in Matplotlib contributions for now, as you can check at https://github.com/matplotlib/matplotlib/graphs/contributors.
The point of posting the patch is so that people who actually need the feature (i.e., not me) can try and play with it, possibly find further issues and fix them themselves, and possibly write the tests that may make the PR more likely to be merged.  Certainly I am more than willing to donate the credit for this specific patch to the community.

**Comment by klicperajo** [comment]
Okay, point taken. I'll see if I can get around to it on the weekend. :)
