### ISSUE TITLE
Figure not rendered on the first run

### ISSUE THREAD

**Issue by SofianeB** [matplotlib/matplotlib#11745]
### Bug report

**Bug summary**

```python
matplotlib.pyplot.show()
```

**Actual outcome**

```
It shows <Figure size 1500x1500 with 2 Axes>
```

**Expected outcome**
Figure.

**Matplotlib version**

  * Operating system: CentOS 7
  * Matplotlib version:  2.2.2 (installed via yum install python-matplotlib)
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.6.0
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
This can't be the only code you ran.  Please make your example complete.

**Comment by SofianeB** [comment]
@jklymak 

```
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap, cm
import numpy as np

lat = data['dimension'][0]['values'][:]
lon = data['dimension'][1]['values'][:]
var = data['measure'][0]['values'][:]
var = np.reshape(var, (len(lat), len(lon)))

fig = plt.figure(figsize=(15, 15), dpi=100)
ax  = fig.add_axes([0.1,0.1,0.8,0.8])

map = Basemap(projection='cyl',llcrnrlat= -90,urcrnrlat= 90, llcrnrlon=0,urcrnrlon=360, resolution='c')

map.drawcoastlines()
map.drawparallels(np.arange( -90, 90,30),labels=[1,0,0,0])
map.drawmeridians(np.arange(-180,180,30),labels=[0,0,0,1])

x, y = map(*np.meshgrid(lon,lat))

clevs = np.arange(0,371,10)

cnplot = map.contourf(x,y,var,clevs,cmap=plt.cm.jet)
cbar = map.colorbar(cnplot,location='right')

plt.title('')
plt.show()
```

**Comment by jklymak** [comment]
Sorry should have said a minimal self contained example.  It’s not clear what the bug is you are reporting

**Comment by SofianeB** [comment]
Is simple.  If I run this code so I get this as output:

```<Figure size 1500x1500 with 2 Axes>```

If I run twice, then the figure is displayed.

**Comment by ImportanceOfBeingErnest** [comment]
This is the expected behaviour. You need to select a backend to actually show your figure. If you happen to always want to use the inline backend, it may make sense to [configure IPython/Jupyter to use that as default](https://stackoverflow.com/questions/21176731/automatically-run-matplotlib-inline-in-ipython-notebook).

**Comment by jklymak** [comment]
Yes, you need to specify the backend before you plot.  i.e. %matplotlib nbagg etc.

**Comment by SofianeB** [comment]
@ImportanceOfBeingErnest Thank you. 
I will see how can I add it to notebook configuration (I am using docker).
