### ISSUE TITLE
test_axes.py::test_csd_freqs failing with numpy 1.15.0 on macOS

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#11766]
There's a really small change in the generated image, leaving this here to track investigations into why.

**Comment by matthew-brett** [comment]
We recently changed to using OpenBLAS for the Mac wheels - maybe that's the explanation?

**Comment by dstansby** [comment]
Here's what I get locally:
![csd_freqs](https://user-images.githubusercontent.com/6197628/43157846-011d6872-8f33-11e8-8693-1fa834c0d01b.png)

And here's the expected image:
![csd_freqs](https://user-images.githubusercontent.com/6197628/43157864-0836315c-8f33-11e8-9017-cd190ac43a23.png)

There's no noticeable change in the diff, so as @jklymak suggested I think it's safe just to add a small tolerance to this test.

**Comment by jklymak** [comment]
Personally I think we should deprecate `csd`, `psd` and friends...  We shouldn't have our own version of the computation of spectral statistics, and the plots are trivial after the the spectra are calculated.

**Comment by jklymak** [comment]
I'd still deprecate `axes.psd`, `axes.csd`, `axes.magnitude_spectrum`, `axes.angle_spectrum`, `axes.phase_spectrum`, `axes.cohere`, and `axes.specgram`.   I think a plan discussed at some point was to move them into a toolbox to give folks a straight-to-plot method of getting these statistical plots.  I think that'd make deprecation pretty straight forward as all the mlab and axes methods could just be moved to there and called from the deprecated methods.  Then the maintainer of `mpl_spectral` could decide how to eventually get rid of the stuff brought over from `mlab`. 

End-users would call

```python
import matplotlib.mpl_spectral as mpls

fig, ax = plt.subplots()
mpls.psd(ax, x, nfft=1024)
```

**Comment by tacaswell** [comment]
Probably the right way to do this is to talk to the maintainers of the scipy spectral functions and develop a version of these that uses scipy and put them in their own package.
