### ISSUE TITLE
which={"major", "minor", "both"} vs minor={True, False}

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#11773]
Just mentioning it here, not that it's particularly urgent: for specification of major vs minor ticks, there is currently a mix between methods that take a `which` ("major"/"minor"/"both" (if applicable)) kwarg and those that take a `minor` (bool) kwarg.  And then there are those that try to please everyone, like `get_ticklabels`:
```
        minor : bool
           If True return the minor ticklabels,
           else return the major ticklabels

        which : None, ('minor', 'major', 'both')
           Overrides `minor`.

           Selects which ticklabels to return
```
... ugh.

I'd suggest homogenizing to use `which` (as that can also handle "both"), even in the cases where "both" is not valid (in which case we just accept "major"/"minor").

Or we can wait for the ticking refactor proposed in #5665...

**Comment by jklymak** [comment]
I find “which” obscure.   What about a “major” and a “minor” bool kwarg?

**Comment by timhoffm** [comment]
I wouldn't want to make separate "major" and "minor args. It feels more natural to specify which ticks you want in a single arguement. No strong arguments but:
- you have to care for the unreasonable `minor=False, major=False` case.
- what to do in cases where "both" is not allowed? Do we still have both arguments? If yes, that's quite verbose and you have to make sure, that only one at a time is True. If not, and say `minor : bool` toggles the behavior, that would be an asymmetry to the case where "both" was allowed and we would have introduced "major" and "minor" there.

The naming "which" is not really good as a standalone name. However, in the context of a function signature `get_ticklabels(which='minor')` it's still quite readable. I don't really have a much better name. "type" and "kind" would be equally general, "labeltype" would be marginally better at the cost of being longer and a change in the API. Overall, I'd stick to "which".

**Comment by jklymak** [comment]
Not sure that `minor=False, major=False` is unreasonable.

I'm not following your second point.  If `both` is not allowed, either don't have both kwargs, ignore the one thats not applicable, or error if both are set True, as I guess we do if `both` is set.

**Comment by anntzer** [comment]
I think I'm warming up to (major: bool, minor: bool).  The problem of `which` is that sometimes it's not clear whether you're referring to major vs minor or to x vs y, e.g. in `ax.grid(which="both")`.  OK, that's not really true because the axis is always specified with the `axis` keyword, but still...

OTOH the axis keyword does take values "x", "y", and "both"; we don't have e.g. `grid(x=True, y=False)`...

**Comment by anntzer** [comment]
It would be good to at least list the APIs where this happens before deciding what to do with it.

**Comment by oscargus** [comment]
Quick grepping:

### which
```
matplotlib/axis.py:    def set_tick_params(self, which='major', reset=False, **kwargs):
matplotlib/axis.py:    def get_tick_params(self, which='major'):
matplotlib/axis.py:    def get_ticklabels(self, minor=False, which=None):
```

### minor
```
matplotlib/axes/_secondary_axes.py:    def set_ticks(self, ticks, labels=None, *, minor=False, **kwargs):
matplotlib/axis.py:    def get_ticklabels(self, minor=False, which=None):
matplotlib/axis.py:    def get_ticklines(self, minor=False):
matplotlib/axis.py:    def get_ticklocs(self, *, minor=False):
matplotlib/axis.py:    def get_ticks_direction(self, minor=False):
matplotlib/axis.py:    def set_ticklabels(self, labels, *, minor=False, fontdict=None, **kwargs):
matplotlib/axis.py:    def _set_tick_locations(self, ticks, *, minor=False):
matplotlib/axis.py:    def set_ticks(self, ticks, labels=None, *, minor=False, **kwargs):
matplotlib/colorbar.py:    def set_ticks(self, ticks, *, labels=None, minor=False, **kwargs):
matplotlib/colorbar.py:    def get_ticks(self, minor=False):
matplotlib/colorbar.py:    def set_ticklabels(self, ticklabels, *, minor=False, **kwargs):
mpl_toolkits/axisartist/grid_helper_curvelinear.py:    def get_tick_iterator(self, nth_coord, axis_side, minor=False):
```

### major
(Had to skip the "def "-part to get some hits.)
```
matplotlib/axis.py:        major=True,
matplotlib/axis.py:                tick = instance._get_tick(major=True)
matplotlib/axis.py:                tick = instance._get_tick(major=False)
matplotlib/axis.py:    majorTicks = _LazyTickList(major=True)
matplotlib/axis.py:    minorTicks = _LazyTickList(major=False)
matplotlib/axis.py:        return self._tick_class(self.axes, 0, major=major, **tick_kw)
matplotlib/axis.py:            tick = self._get_tick(major=True)
matplotlib/axis.py:            tick = self._get_tick(major=False)
matplotlib/tests/test_skew.py:        return SkewXTick(self.axes, None, major=major)
```

Not perfect, but gives some indication at least... (There are several other APIs where `which` is used though, such as axis-selection.)

**Comment by timhoffm** [comment]
The first `major=True` is actually from `Tick.__init__()`. So we have all three cases in public API 🤦.

**Comment by timhoffm** [comment]
As a heads up, I have some options on this. Will write that down later today.

**Comment by timhoffm** [comment]
While the mixture is not great, I believe there is no reasonable way to improve. We need to live with the current state. See https://github.com/matplotlib/matplotlib/issues/11773#issuecomment-1544458782 for details.
