### ISSUE TITLE
constrained_layout doesn't deal well with disabled clipping

### ISSUE THREAD

**Issue by dcherian** [matplotlib/matplotlib#11783]
cc @jklymak 

### Bug report

**Bug summary**

Unexpected output when `constrained_layout=True` and clipping is disabled.

**Code for reproduction**
```python
def make_plot(ax):
    h0 = ax[0].plot([1,2], [3,4])
    h1 = ax[1].plot([1,2], [3, 8])
    ax[1].set_ylim([3, 5])
    h1[0].set_clip_on(False)

f, ax = plt.subplots(2, 1, constrained_layout=False)
make_plot(ax)
ax[0].set_title('constrained_layout=False')

f, ax = plt.subplots(2, 1, constrained_layout=True)
make_plot(ax)
ax[0].set_title('constrained_layout=True')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2448579/43340769-3ed6afbe-9192-11e8-9610-fb72293e35bf.png)

**Expected outcome**

expected outcome is behaviour seen with `constrained_layout=False`

![image](https://user-images.githubusercontent.com/2448579/43340747-2add2a6a-9192-11e8-8afd-9c22adcc5f9c.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.2.2.post1813.dev0+gcb47f2dbc
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.0

**Comment by jklymak** [comment]
Hi @dcherian Thats actually expected :wink:  constrained_layout makes room for all artists attached to the axes, so its working great.  

For what you want just take the unclipped line out of the layout:

```python
def make_plot(ax):
    h0 = ax[0].plot([1,2], [3,4])
    h1 = ax[1].plot([1,2], [3, 8])
    ax[1].set_ylim([3, 5])
    h1[0].set_clip_on(False)
    h1[0].set_in_layout(False)


f, ax = plt.subplots(2, 1, constrained_layout=False)
make_plot(ax)
ax[0].set_title('constrained_layout=False')

f, ax = plt.subplots(2, 1, constrained_layout=True)
make_plot(ax)
ax[0].set_title('constrained_layout=True')
```

![cl](https://user-images.githubusercontent.com/1562854/43342196-b7ebc34a-9196-11e8-9200-0b481aa4265f.png)

Todo:
  [] add `set_in_layout()` to the Artist list of methods - I missed that in the original PR
  [] discuss if `set_clip_on(False)` should also remove the artist from the layout?

**Comment by dcherian** [comment]
Wow, that was a simple fix.

> if set_clip_on(False) should also remove the artist from the layout?
I think so. I can't see why the first image in my post should be the desired outcome.

It would also be useful to add this to the constrained layout guide.

**Comment by jklymak** [comment]
Yeah its in the CL guide about legends, but not about general artists.  On my todo list, thanks!

**Comment by asteppke** [comment]
I think I stumbled over similar behavior without touching any clipping functions. In the example below one has to explicitly remove the text from the layout although it is outside of the axis limits. Is this desired behavior? It feels strange that `ax.plot` does not cause this issue but `ax.text` does.

````python
fig, axes = plt.subplots(ncols=2, figsize=(6,3), constrained_layout=True)

for ax in axes:
    t = ax.text(0.2, 40E6, 'text')
    # the default: t.set_in_layout(True)
    # required for constrained layout to work here: 
    t.set_in_layout(False)
    
axes[0].set_ylim((0, 100E6))
axes[1].set_ylim((0, 1E5))

````

**Comment by tacaswell** [comment]
By default text is not clipped where as lines are, hence the difference.

I'm comfortable leaving this issues closed.
