### ISSUE TITLE
Feature request  w.generate_event for matplotlib widgets

### ISSUE THREAD

**Issue by drmcnelson** [matplotlib/matplotlib#11782]
### Feature request

**Feature request**

The Tkinter widget method w.generate_event(), provides a way to simulate a mouse click for a tkinter widget.

What is needed, is a similar way to simulate a mouse click, and other events, for a matplotlib widget.

**Comment by jklymak** [comment]
@drmcnelson if you work through @anntzer code could you add an example to the examples gallery?

**Comment by drmcnelson** [comment]
So, I see _process(name, ax, coords, *args)    That looks pretty good.  Presumably, coords are offset from the corner of the axes. And so, if ax is the axes for a single matplotlib button widget, then coords can be [0,0] ?

**Comment by drmcnelson** [comment]
This really should be added to the API

**Comment by WeatherGod** [comment]
`process()` is already a part of the API. `_process()` is part of the
private API. Documentation may be a bit lacking, but it is part of the API
already. Please don't use `_process()`.

**Comment by drmcnelson** [comment]
Yes, process() is in the API, but that is not what we are looking for.   In **_process()**, the event is delivered where it needs to go based on the **axes** argument and it takes care of translating the coordinates to be consistent with that semantic.

There is nothing like that in the API, and that is the call that we need.
