### ISSUE TITLE
Newer versions of ImageMagickWriter not found on windows

### ISSUE THREAD

**Issue by t-makaro** [matplotlib/matplotlib#11792]
### Bug report

**Bug summary**

When I try to save an animation using imagemagick to write to a gif, the saving works perfectly, but the message ```MovieWriter imagemagick unavailable.``` is printed to the console.

**Code for reproduction**

```python
from matplotlib.animation import FuncAnimation
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 1, 20)

def f(x, i):
    return x*np.sin(i/10)

line, = plt.plot(x, f(x, 0))
plt.xlim([0,1])
plt.ylim([-1,1])
fig = plt.gcf()
def animate(i):
    line.set_data(x, f(x,i))

anim = FuncAnimation(fig, animate, frames=60, interval=50)
anim.save('fig.gif', writer='imagemagick')
plt.show()
```

**Actual outcome**

```
MovieWriter imagemagick unavailable.
```
Yet, the gif is still produced.

**Expected outcome**

The gif is produced without lying to me about the unavailability of imagemagick.

**Matplotlib version**

  * Operating system: Windows 10 Version 1803
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5 (installed with conda)
  * Other libraries: imagemagick 7.0.8.7 (installed with chocolatey)

I suspect this has to do with that way that I've installed imagemagick, since chocolatey shims "magick" into the PATH, and matplotlib looks through the registry.

**Comment by anntzer** [comment]
Perhaps setting the animation.convert_path rcParam (https://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template#L612) will help?

**Comment by t-makaro** [comment]
I tried adding:
```python
mpl.rcParams['animation.convert_path'] = 'magick'
```
to the top of my code. That changed nothing. Error occurs. Gif still produced.

Adding
```
animation.convert_path:  magick
```
to my ```.matplotlib/matplotlibrc``` file did cause the error message to disappear.


The weird thing about this is that without making any adjustments to ```matplotlibrc``` the gif IS produced despite the error message. If the writer works then it shouldn't require me to change my ```matplotlibrc``` file to stop it from displaying a meaningless error.

**Comment by ImportanceOfBeingErnest** [comment]
First, this is a warning, not an error. So this warns that the requested writer is unavailable. But apparently there is still a different one there. This is inside of this fall-back mechanism:

https://github.com/matplotlib/matplotlib/blob/300e4c9afbc9dc00800f36184814634694171e3f/lib/matplotlib/animation.py#L1122-L1132

So what I suspect is happening here is that indeed imagemagick is not found, hence you get a warning. But since you may have pillow installed, and that is the first available writer, it'll choose this one to create the output. From the outside it's hard to distinguish whether a gif is created via imagemagick or pillow.

Now the interesting part is why there is a difference between setting the imagemagick path in the rcParams or the rc file - I have no idea why that would be.

**Comment by tacaswell** [comment]
There is an issue with imagemagik on windows that there is a built in window utility called 'convert' which clashes with imagemagick's, see https://github.com/matplotlib/matplotlib/blob/0e95b73c7ee32601502c6b8291839c849444ab49/lib/matplotlib/animation.py#L726-L742

I suspect that we are not making sure this is getting called in all of the required places...

That warning should be made clearer (that it is a warning), @t-makaro any interest in helping with that?

**Comment by t-makaro** [comment]
@ImportanceOfBeingErnest I think it is falling back to PillowWriter. Currently, PillowWriter makes a gif that doesn't loop. When I get the warning, the produced gif doesn't loop. I checked my windows registry. These are the keys that I get:
![image](https://user-images.githubusercontent.com/18018386/43754757-3c1dfe3a-99c1-11e8-995c-5950423c3043.png)

I'm not sure if those match with what is expected. I'd have to take a closer look. I'd be interested in getting matplotlib to somehow find my install of imagemagick itself. Regardless, the warning should at least specify what writer matplotlib has fallen back to.

**Comment by dopplershift** [comment]
So I'd only expect things to work out the box if `C:\Program Files\ImageMagick-7.0.8-Q16\convert.exe` exists.

As far as `mpl.rcParams['animation.convert_path'] = 'magick'` not working, did that line run *before* importing `matplotlib.animation`.

**Comment by t-makaro** [comment]
@dopplershift Yes, resetting the available writers or running changing the rcParam before importing ```matplotlib.animation``` fixed that issue.

I've been doing some research as to why I don't have a ```convert.exe``` in the imagemagick program files. It turns out that in imagemagick 7 (first released over 2 years ago), the convert command was replaced with magick (for all systems I believe). [source](http://imagemagick.org/script/porting.php#cli). Convert is a symbolic link to magick.

On windows, when running the installer it gives the option to "install legacy utilities" which includes ```convert.exe```, but it's disabled by default. When I installed using chocolately, it used default options (which I would have done anyway before know all this). 


For windows at least, we could probably get away with changing [this line](https://github.com/matplotlib/matplotlib/blob/0e95b73c7ee32601502c6b8291839c849444ab49/lib/matplotlib/animation.py#L738) to:
```python
binpath += r'\magick.exe'
```
We'd have to list the change in a changelog saying that only imagemagick >= 7 is supported out of the box on windows, but I think moving to the new version is a good idea.

I'm more or less happy at this point. Regardless of any change or not. If people think we should do something about this change to imagemagick (version 6 vs 7), great. I'd be willing to submit the above change to the ```binpath += …```  line. If not, I won't complain if the issue is closed.

**Comment by ImportanceOfBeingErnest** [comment]
It wasn't clear to me that imagemagick would only install `convert.exe` in some cases (I do have it in my install and I can't remember doing anything nonstandard when installing). What happens in other operating systems like linux?

In any case I don't think one can simply replace the `convert.exe` by `magick.exe` without annoying a lot of people. However, one could of course use the `Version` registry key to find out which of those shall be used.

**Comment by fredrik-1** [comment]
I encountered this problem a year ago and believe that the solution given above are correct and good. (if I remember correctly, I haven't tested this now).
 
`convert` does not always exist an windows but the same functionality is then in the function `magick`. So changing the rc parameter to `animation.convert_path: magick,` should work without any problems in that case.

Some documentation and maybe a better warning is probably enough. 

One other possibility is to check if any of the two alternatives exist and use that one. I guess that should be easy to do.

**Comment by fredrik-1** [comment]
The animation script above doesn't work for me on master but it works on v2.2.2 ... can someone confirm?

**Comment by fredrik-1** [comment]
I am looking at the animation module and are working at some changes in documentation and maybe some other changes. 

Shouldn't the functionality to test another writer if the one you try to use is not installed be deleted? 
The first writer in the list would in most cases don't even work. 

One possibility is to check for a writer that does the same thing, imagemagick/pillow and ffmpeg/avconv but are there any real reason to do that?

Any reason why PIL is imported instead of Pillow?  PIL has not been updated in 7-8 years if I understand correctly but I guess that it is included in Pillow.

**Comment by ImportanceOfBeingErnest** [comment]
When you have pillow installed, `import PIL` will import pillow.

**Comment by t-makaro** [comment]
The only reason that I can think of to have for falling back to a different writer is to run code on different systems, but that could be easily handled by the user. The fallback behaviour is weird and could produce unexpected results for people. I think that if a writer is unavailable then it should error, and print the available writers. 

I fairly confident that PIL is pillow. It's just built that way so people can install pillow in place of the original PIL, and not even need to change imports.

**Comment by tacaswell** [comment]
@t-makaro You have hit on what I think is the biggest tension when working on Matplotlib.  On one hand we want to be a library that is nice for "developers" to work with where we make as few assumptions as possible and in the face of ambiguity fail fast and on the other hand we are a end-user facing api where would should do our best to "just work" and if we are pretty sure what the user wanted, to do it (even isn't _quite_ what they said to do).

**Comment by t-makaro** [comment]
Ya, that's fair. At least we have a better warning now that tells people what matplotlib is doing if it wasn't quite the writer user asked for. Especially since some writers can be particularly annoying to get working.

**Comment by HansBambel** [comment]
I just stumbled across this and fixed it with @t-makaro's hint to install Imagemagick with legacy support.
