### ISSUE TITLE
Pie chart inconsistent return tuple size depending on keywords argument.

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#11807]
### Bug report

```
plt.pie(..., autopct='%1.1f') # returns a 3-tuple
plt.pie(..., autopct=None) # returns a 2-tuple
```

This is due to
```
if autopct is None:
    return slices, texts
else:
    return slices, texts, autotexts
```

This should likely be:

```
if autopct is None:
    return slices, texts, []  # thrid empty argument.
else:
    return slices, texts, autotexts
```

To have consistency of API.

Arguably this is a change of API. The default of `autopct` being `None` this was likely introduced on purpose to not break existing code, a migration path forward should probably be designed.

**Comment by timhoffm** [comment]
I'd argue that it's ok in this case to have a different number of arguments depending on `autopct`. I tend to not break API compatibility for this.

**Comment by timhoffm** [comment]
@tacaswell would you want to change the API here? If not, we should close this.

**Comment by tacaswell** [comment]
We talked about this on the call.  There is no (maintainable) way we know how to do this without breaking someone (as if anyone is currently unpacking they are using one or the other) in a way we can warn them about.  This is unfortunately an API oddness that we are going to have to continue to live with.

There is probably a multi-cycle deprecation path where we warn if you would get two back, give a kwarg to opt into the 3 return and then eventually deprecate that flag.  However the effort for that does not seem worth the payoff and medium term we may want to move to returning a `Pie` typed object.
