### ISSUE TITLE
how do i make a live barplot

### ISSUE THREAD

**Issue by jandevries1421353151** [matplotlib/matplotlib#11803]
Hello,

i use drawnow to get live charts and matplotlib for charting (latest version). When i draw chart 2,3,4 with barplot its just a normal barplot, put now i want bars to be added live on the right where it left. so i got chart 1 working live with drawnow and just normal numbers as input but how should i do it with barplots? i put data for the charts in a list like Bardata = [] and i call the function with ax1 = fig etc with drawnow(function)

when i have new bar created i want it to show up in the chart on the far right without reloading the whole chart, any ideas on how i should do that?

thanks,

Jan

**Comment by jklymak** [comment]
Thanks for your interest in Matplotlib!  github is for bug reports, not user support.  Please post in the mailing list or stackoverflow.
