### ISSUE TITLE
matplotlib 3D text orientation zdir  

### ISSUE THREAD

**Issue by fabiengueret** [matplotlib/matplotlib#11804]
### Bug report

When trying to tag point in a 3D scatter plot, the figure.text (same with text3D) the tag is rendered either descending on the left of the mid plan or rising on the right.

**Code for reproduction**

```python

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
#from matplotlib import cm
#from mpl_toolkits.mplot3d import Axes3D
#from pylab import *

x= [-1,-0.5, 0.5, 0.5] 
y= [1, 0.5, 0.25, 0.1]
z= [1, 0.75, 0.5,0.25]
tags = ['tag1','tag2','tag3','tag4']

az = -45
el = 45
fig = plt.figure(figsize=(20,10))
ax = fig.add_subplot(111, projection='3d')
ax.view_init(azim=az, elev= el)
ax.scatter(x, y ,z, s=20)
for x1, y1, z1,tag in zip(x,y,z,tags):
    label = tag
    ax.text3D(x1, y1, z1, label, zdir='z') 
```              

**Actual outcome**
![image](https://user-images.githubusercontent.com/35690374/43473442-0c992e38-94e8-11e8-9910-a8f530e4822c.png)

**Expected outcome**

All text tags rising as zdir 

**Matplotlib version**
  * Operating system: Windows 10 Pro
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

python 3.6
spyder 3.2.8
anaconda 1.8.7 2016

**Comment by ImportanceOfBeingErnest** [comment]
You might accidentally have deleted the 3 backticks (```) needed to close the code environment, such that the graphics is not shown correctly.  


One should note here that which text is shown in which direction also depends on the azimuthal angle.
  E.g. setting `az=-10` in the above code reverses `tag3` and `tag4` but not the other two.

![image](https://user-images.githubusercontent.com/23121882/43474530-7962fa16-94f3-11e8-9365-1a502affa0e5.png)

**Comment by WeatherGod** [comment]
If I understand your issue right, what we are seeing isn't exactly a bug.
The tags are oriented according to the direction of the z vector as
projected in the 2D transformation that is employed. So, the z vector is
slightly tilted as you move away from the center.

If you don't want that to happen, mplot3d now has the option to specify an
'orthographic' projection:
https://matplotlib.org/users/prev_whats_new/whats_new_2.1.0.html#orthographic-projection-for-mplot3d

**Comment by WeatherGod** [comment]
.... and I think I misunderstood your report.

Yes, the tags are automatically oriented based on which side of the center they are on. This was done in order to automatically have the axes label show up oriented "the right way". I can see how this may be undesirable in some circumstances.

**Comment by duhaime** [comment]
@ImportanceOfBeingErnest @WeatherGod has there been any improvement on this front? I too would like to specify the text director with x, y, z float components between -1 and 1 (or 0 and 1) but currently setting `zdir` does not appear to change the text direction:

```
from mpl_toolkits.mplot3d import Axes3D
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

# point data - x, y, z
a = [0.0, 0.0, 0.0]
b = [1.0, 1.0, 1.0]

df = np.array([a, b])

fig = plt.figure()
ax = fig.gca(projection='3d')

# point data: pattern for drawing points is:
# ax.scatter(x_vals, y_vals, z_vals)
ax.scatter(df[:,0], df[:,1], df[:,2], s=100, c=['blue', 'orange'], alpha=1.0)

# line data: pattern for drawing lines is:
# ax.plot([x_start, x_end], [y_start, y_end], zs=[z_start, z_end])
ax.plot( [a[0], b[0]], [a[0], a[0]], zs=[a[0], a[0]], c='red' )    # x-line
ax.plot( [b[0], b[0]], [a[0], b[0]], zs=[a[0], a[0]], c='purple' ) # y-line
ax.plot( [b[0], b[0]], [b[0], b[0]], zs=[a[0], b[0]], c='green' )  # z-line
ax.plot( [a[0], b[0]], [a[0], b[0]], zs=[a[0], b[0]], c='gray', linestyle=':' )  # direct line

# add equation labels
ax.text(0.4, 0.3, 0, '(a.x - b.x)', fontsize=20, horizontalalignment='center', zdir=(0.5,0,0))

# add axis labels
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
```

![screen shot 2018-09-10 at 11 21 51 am](https://user-images.githubusercontent.com/4801116/45306903-bc0bbc00-b4eb-11e8-82a6-31c0cc3784dc.png)

Changing the zdir argument to `zdir=(0.1,0,0)` results in exactly the same plot. Is there a way to fine tune this currently?

**Comment by athantas95** [comment]
By playing with the `y` coordinate I got the desired orientation for values of `y<=-0.055` and `z=-1`. That is to set `zdir` to `(0,-0.055,-1)`.
Not perfect but a fine for me workaround.
