### ISSUE TITLE
Figure gets collapsed after nth iteration using constrained_layout

### ISSUE THREAD

**Issue by abbazs** [matplotlib/matplotlib#11810]
### Bug report

**Bug summary**

Repeatedly saving a figure created using `constrained_layout=True` and using `GridSpec`, grids in the figure collapses after nth time. From 0 to 90 figure is generated as expected. From 91 grids inside the figure collapses. Sample images shown here.
![0](https://user-images.githubusercontent.com/758268/43677275-df9d3c70-981c-11e8-9799-5be091b3e504.png) ![90](https://user-images.githubusercontent.com/758268/43677280-f22e6ea4-981c-11e8-957f-474a3bb7f8ae.png) ![91](https://user-images.githubusercontent.com/758268/43677282-f57f7a76-981c-11e8-91fb-6778921617d4.png)

**Code for reproduction**
```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.colors as mcolors
import matplotlib._layoutbox as layoutbox

plt.style.use('ggplot')

def gridspec_bug(file):
    fig = plt.figure(figsize=(2,5), constrained_layout=True)
    gs = gridspec.GridSpec(5, 1, figure=fig, height_ratios=[1/20, 6/20, 6/20, 4/20, 3/20])
    ax1 = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])
    ax3 = fig.add_subplot(gs[2])
    ax4 = fig.add_subplot(gs[3], sharex=ax3)
    ax5 = fig.add_subplot(gs[4], sharex=ax3)
    fig.text(0.5, 0.5, file, fontsize=25, color='black', ha='center', va='center')
    fig.savefig(file, format='png')
    plt.close(fig)

if __name__ == '__main__':
	for i in range(0, 110):
		file_name = f'{i}.png'
		gridspec_bug(file_name)
		print(f'Done {i}')
```

**Matplotlib version**
  * Operating system: `Windows 10`
  * Matplotlib version: `2.2.2`
  * Matplotlib backend (`print(matplotlib.get_backend())`): `agg`
  * Python version: `3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]`
  * Jupyter version (if applicable): NA
  * Other libraries: NA

**Comment by jklymak** [comment]
Thanks, this was definitely an overflow bug, but it got fixed in #11330 and is fine on master...

![boo309](https://user-images.githubusercontent.com/1562854/43678306-08ab8916-97c6-11e8-8168-e894823f6be4.png)
