### ISSUE TITLE
Animation Examples 

### ISSUE THREAD

**Issue by anthonytec2** [matplotlib/matplotlib#11823]
When going to the gallery of the different plots under the animation section, various of these plots are blank. See this [link](https://matplotlib.org/gallery/animation/basic_example.html). Possibly an issue with documentation generation.

**Comment by ImportanceOfBeingErnest** [comment]
This is expected. The purpose of those examples is to show how an animation is produced. Yet, the way the matplotlib documentation is generated, it is currently not possible to show animated output. The images shown are the static version of the animations, i.e. the state of the figure before the animation actually starts. 

One possible solution would be to not use the automatic sphinx-gallery output for those examples, but rather generate some animated gifs manually and link them statically inside the example file. 

One might also opt for not showing any output (that would be easier compared to the above, but maybe equally confusing?). 

The question is a bit whether either of the above is really worth the effort.

**Comment by QuLogic** [comment]
There is some hope to do something like this in sphinx-gallery: https://github.com/sphinx-gallery/sphinx-gallery/issues/150

**Comment by ImportanceOfBeingErnest** [comment]
@anthonytec2 seems like you are building the docs from an environment that has an older matplotlib version in it. E.g. if you had a system-wide python with matplotlib 2.1 installed and some folder with matplotlib 2.2, then running `make html` to build the docs from that folder would probably result in such error.

<hr>

In general I do think it's worth waiting for sphinx-gallery to sort out [their new scraper system](https://github.com/sphinx-gallery/sphinx-gallery/pull/313).
