### ISSUE TITLE
Compressed Triangulation Masking in CubicTriInterpolator

### ISSUE THREAD

**Issue by tallakahath** [matplotlib/matplotlib#11820]
### Bug report

**Bug summary**

If `tri_analyzer`'s `_get_compressed_triangulation` method masks out triangles, a `ValueError` due to `shape mismatch` occurs because of:

```self._z[node_renum[~node_mask]] = self._z```

since the LHS and the RHS are *not* same-sized if triangles get masked away. This is because `node_renum` being masked by `~node_mask` reduces the indices being passed to `self._z` to the subset of unmasked points along `self._z`, which can be smaller than all of `self._z`. The following code works and *I think* does what is intended:

```self._z[node_renum] = z```

Note that the very next line in the source is `self._z = self._z[~node_mask]` which takes care of applying the mask. 

**Code for reproduction**

Ah, this is where things get tricky. I have a really hackneyed way of reproducing the "error" but the example is super contrived and not a great test case. It fails for the Right Reasons, though, which I hope is useful. In the real world I'm plotting heat capacity maps for a phase diagram, so I have a 2D irregular mesh of x-values (compositions) and y-values (temperatures) that I'm unraveling to feed to Triangulation. 

```python
from numpy import zeros, arange, repeat
from numpy.random import rand
from matplotlib.tri import Triangulation, TriAnalyzer, UniformTriRefiner
x = zeros(1000) 
for i in range(10):
    x[500+i] = rand()
y = repeat(arange(100), 10)
tri = Triangulation(x, y)
refiner = UniformTriRefiner(tri)
refiner.refine_field(rand(1000), subdiv=2)
```

**Actual outcome**

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-3bc829626eee> in <module>()
      8 tri = Triangulation(x, y)
      9 refiner = UniformTriRefiner(tri)
---> 10 refiner.refine_field(rand(1000), subdiv=2)

/usr/local/lib/python2.7/site-packages/matplotlib/tri/trirefine.pyc in refine_field(self, z, triinterpolator, subdiv)
    168         if triinterpolator is None:
    169             interp = matplotlib.tri.CubicTriInterpolator(
--> 170                 self._triangulation, z)
    171         else:
    172             if not isinstance(triinterpolator,

/usr/local/lib/python2.7/site-packages/matplotlib/tri/triinterpolate.pyc in __init__(self, triangulation, z, kind, trifinder, dz)
    414         # Taking into account the node renumbering in self._z:
    415         node_mask = (node_renum == -1)
--> 416         self._z[node_renum[~node_mask]] = self._z
    417         self._z = self._z[~node_mask]
    418

ValueError: shape mismatch: value array of shape (1000,) could not be broadcast to indexing result of shape (109,)
```

**Expected outcome**

Some refined triangles. 

**Matplotlib version**
  * Operating system: Ubuntu 16.04.3 LTS, OSX 10.11.6 (tested on both)
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt4Agg and MacOSX
  * Python version: 2.7
  * Other libraries: Tested on numpy 1.15.0 and 1.14.3

Installed using pip. Numpy installed from source (on ubuntu box) and using homebrew (on OSX box)

**Comment by tacaswell** [comment]
attn @ianthomas23

**Comment by ianthomas23** [comment]
@tacaswell: Actually this is @GBillotey's code, not mine.

**Comment by tacaswell** [comment]
Sorry to bother you, I had you associated with all of the contour + triangulation code.

**Comment by GBillotey** [comment]
Thanks @tallakahath for the report. This is a bit embarrassing, as some tests are obviously missing...
I believe the patch proposed will fail to handle correctly the `-1` values of `node_renum` (denoting masked nodes) and will be mixing the `z` values. I would suggest rather something like :

```
# Taking into account the node renumbering in self._z:
node_kept = (node_renum != -1)
size_kept = np.sum(node_kept)
z_renum = np.empty(size_kept, dtype=self._z.dtype)
z_renum[node_renum[node_kept]] = self._z[node_kept]
self._z = z_renum
```

However I will not be able to submit proper PR in the coming weeks, before September. Of course feel free to propose one.

**Comment by mdepitta** [comment]
It appears that this bug is still going on and not solved. I cannot run on my data sets a refinement problem as specified in the [tricontour demo](https://matplotlib.org/gallery/images_contours_and_fields/tricontour_smooth_delaunay.html#sphx-glr-gallery-images-contours-and-fields-tricontour-smooth-delaunay-py), using `matplotlib.__version__=3.2.0. As soon as I attempt to invoke the `refine.refine_field(z,subdiv=3)` I get the 

> ValueError: shape mismatch: value array of shape (1800,) could not be broadcast to indexing result of shape (1628,)

My `z` data is the same shape of original `x` and `y` data fed to the `Triangulation` instance. But the `UniformRefiner` gives me this error... Any solution?

**Comment by mdepitta** [comment]
My bad, sorry. It was a problem of `triinterpolator` choice in the `refine_field` method.
