### ISSUE TITLE
Problems with the tests with python 3.5

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#11825]
I have written some tests that works on my computer and an travis with everything except python 3.5, #11796. (the tests at least, flake8 on python 3.6 failed on my last implementation)

What is going on? The error is due to multiprocessing and it is a known problem in same cases but I don't understand how my tests are related to the problematic cases and what I can do to make the tests pass on python 3.5.

Is `PYTHONHASHSEED=0` set on travis?

**Comment by tacaswell** [comment]
Closing this to keep the discussion in #11796  (better to not split the conversation in half!).
