### ISSUE TITLE
Colors of contours generated with contour()/contourf() should match colors of the 3D surface plotted using plot_surface()

### ISSUE THREAD

**Issue by snooper77** [matplotlib/matplotlib#11830]
### Bug report

**Bug summary**

The colors used in plotting a 3D surface using `plot_surface()` and the corresponding contours generated using `contour()` or `contourf()` should match, but they don't.

Here's a minimal example demonstrating the issue

```
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
from matplotlib import cm

fig = plt.figure()
ax = fig.gca(projection='3d')
X, Y, Z = axes3d.get_test_data(0.05)
cmap = cm.coolwarm
ax.plot_surface(X, Y, Z, cmap=cmap, alpha=0.7)
ax.contour(X, Y, Z, zdir='z', offset=-100, cmap=cmap)
ax.contour(X, Y, Z, zdir='x', offset=-40, cmap=cmap)
ax.contour(X, Y, Z, zdir='y', offset=40, cmap=cmap)

# contour projections of the 'blue valley'
green = [0, 0.8, 0]
vx, vy, vz = 0, -3, -72
minx, miny, minz = -40, 40, -100
ax.quiver(vx, vy, vz, 0, 0, minz-vz, color=green)
ax.quiver(vx, vy, vz, minx-vx, 0, 0, color=green)
ax.quiver(vx, vy, vz, 0, miny-vy, 0, color=green)

ax.set_xlabel('X')
ax.set_xlim(-40, 40)
ax.set_ylabel('Y')
ax.set_ylim(-40, 40)
ax.set_zlabel('Z')
ax.set_zlim(-100, 100)

plt.show()
```

![contour](https://user-images.githubusercontent.com/1882043/43891095-cfdeedc4-9bc8-11e8-907e-8db29af17bc5.png)

**Actual outcome**
Take a look at the green arrows that show the contour projections of the blue valley :
1. Projecting onto the X-Y plane works fine as the projected valley is still blue
1. Projecting onto the Y-Z or the X-Z plane **fails as the projected valley changes color to light gray**

Note that the same problem exists for `contourf()`.

**Expected outcome**
The valleys in all contours should remain blue (and, analogously, the peak should remain dark red).

**Matplotlib version**
  * Operating system: Windows 7 Enterprise
  * Matplotlib version: 2.2.2
  * Matplotlib backend: nbAgg
  * Python version: 3.5.4 |Anaconda, Inc.| (default, Nov  8 2017, 14:34:30) [MSC v.1900 64 bit (AMD64)]
  * Jupyter version (if applicable): 4.4.4

**Comment by ImportanceOfBeingErnest** [comment]
The contour levels are chosen along the line of projection. If we take e.g. the projection along x,   
`ax.contour(X, Y, Z, zdir='x', offset=-40, cmap=cmap)`, the first contour line is the cut of the data in the Y-Z plane at x=-30. The second is the one at x=-20 and so forth. Those lines are colorized incrementally with the colors from the colormap, first line is dark blue, than lighter blue, and dark red for the last line. So I would say the plot that is shown (which is pretty much the plot [from the docs](matplotlib.org/gallery/mplot3d/contourf3d_2.html)) is correct.

**Comment by tacaswell** [comment]
I agree with @ImportanceOfBeingErnest 's analysis. It is a bit confusing, but correct.

Each of the projected contours sets is colored independently and one projected "down" matches because the color map used on the surface and for the bottom contour is the Z values.  On the other planes the color (and curves) are based on either X or Y and colored / traced as such.

I think if you want to have the projection on the x/y planes to be colored by Z you can get the affect by using a LineCollection and doing the slicing directly rather than run run through contour.


[1] https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html
