### ISSUE TITLE
image compare animations for testing

### ISSUE THREAD

**Issue by t-makaro** [matplotlib/matplotlib#11839]
I'm currently trying to create pytests for animations over in [animatplot](https://github.com/t-makaro/animatplot/issues/8). Now, I know that people here have talked about writing image comparison tests for animations, so I thought I would open an issue here to track progress, and to share what I am doing. 

Now my needs for animatplot are fairly different, but essentially I'm going to wrap around ```matplotlib.testing.compare.compare_images```, and use a custom file writer (which you can see [here](https://github.com/t-makaro/animatplot/blob/154e90263ab05595d02746cce807da13a71274c4/animatplot/testing/comparison.py)) to output a set of images. This file writer was inspired by @tacaswell's [stackoverflow answer](https://stackoverflow.com/questions/41230286/matplotlib-animation-write-to-png-files-without-third-party-module/51778313#51778313).

Once I get stuff working over there, I will be willing to help create these types of tests here.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/pytest-mpl might also be interested in this feature.

**Comment by t-makaro** [comment]
I'm very close to having everything working, but I'm having to remove the text to get things to compare properly on circleci. Which is fine for the most part, but for one of my tests I can't remove the text. I am getting a:
```
Could not set locale to English/United States. Some date-related tests may fail
    "Could not set locale to English/United States. "
```
message, but I don't think that is the issue.

I'm not sure what's causing the test to render so differently.
![image](https://64-87026896-gh.circle-artifacts.com/0/home/circleci/project/tests/output_images/Animation/controls0-failed-diff.png)

I am using ```matplotlib.testing.setup()``` which should set the font....

**Comment by tacaswell** [comment]
Might be a freetype issue, see https://matplotlib.org/devel/contributing.html#building-matplotlib-for-image-comparison-tests

**Comment by t-makaro** [comment]
Alright, I have something that works for me over at animatplot. You can see my implementation [here](https://github.com/t-makaro/animatplot/blob/master/animatplot/testing/tools.py). It's as simple as using a decorator on a function that returns an animation. Internally, it will use the ```BunchOFiles``` writer to save the animation, and then loop over the images for comparison. Unfortunately, it does require specifying how many frames to expect. 

This would require some additional work to suit matplotlib's needs.
