### ISSUE TITLE
Feature Request: Controlling top, bottom, left, and right tick parameters independently of one another

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#11837]
`matplotlib.axes.Axes.tick_params` allows one to control the direction which the ticks along the x and y axes point.  Currently this can either be set to `in` or `out` which is very useful, but sometimes I want to create a plot that has ticks along the bottom pointing out and ticks along the top pointing in and I was unable to find an easy solution to accomplish this as `tick_params` for top and bottom are both tied to the x-axis.  I am currently able to accomplish what I want by using and `ax.twiny()`:
```
fig, ax = plt.subplots()

majorLocator = AutoLocator()
minorLocator = AutoMinorLocator()

ax_top = ax.twiny()
ax_top.tick_params(which='both', direction='in')
ax_top.set_xlim(ax.get_xlim())

ax.xaxis.set_minor_locator(minorLocator)
ax.xaxis.set_major_locator(majorLocator)

ax_top.xaxis.set_minor_locator(minorLocator)
ax_top.xaxis.set_major_locator(majorLocator)

ax_top.get_shared_x_axes().join(ax_top, ax)
ax_top.set_xticklabels([])
```
![unknown](https://user-images.githubusercontent.com/6963786/43929085-449f5580-9be8-11e8-8de3-795ba6e38764.png)
but this seems like a messy solution

**Comment by afvincent** [comment]
I agree that a more concise and user-friendly way to achieve this would be a nice feature to have from a user perspective. In some fields (at least the few ones that I know), these kinds of tick directions are rather common. For the record, a “recent” Gitter discussion related to the same topic occurred [here](https://gitter.im/matplotlib/matplotlib?at=5b2c37887da8cd7c8c61f202).

**Comment by ImportanceOfBeingErnest** [comment]
If I see it correctly this should be simplified by the `secondary_xaxis` proposed in #11589, it should then look like (the API there is not yet finalized, so this is a rough estimate):

```
fig, ax = plt.subplots()
ax.minorticks_on()

ax_top = ax.secondary_xaxis('top', 1)
ax_top.minorticks_on()
ax_top.tick_params(which='x', direction='in', labeltop=False)
```

Even simpler solution would require something like proposed [here](https://github.com/matplotlib/matplotlib/issues/5665#issuecomment-376940355).

**Comment by jklymak** [comment]
As #11859 (note new PR number) stands now, this is:

```python

import numpy as np
import matplotlib.pyplot as plt

convert = 1

fig, ax = plt.subplots()

ax.minorticks_on()

axsecond = ax.secondary_xaxis('top', conversion=convert)
axsecond.minorticks_on()
axsecond.tick_params(axis='x', which='both', direction='in', labeltop=False)
```

![figure_4](https://user-images.githubusercontent.com/1562854/44169523-8826ad80-a089-11e8-9ab6-d0a779c5ca9e.png)
