### ISSUE TITLE
macosx backend won't load 

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11846]
### Bug report

#11600 (34794819d8) appears to have broken the macosx backend.  

```
% git checkout 34794819d8
% cd lib
% git clean -xdf
% cd ..
% pip install -e .
% pythonw testMac.py

Traceback (most recent call last):
  File "testMac.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 2410, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 246, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

```python 
import matplotlib
matplotlib.use('macosx')
```

No error on the previous commit (f4ae5d1ccb).  #11600 had a bunch of changes in the `_src/macosx.h`....

**Comment by anntzer** [comment]
In `_macosx.m verify_framework`, there is a block that reads
```
    NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
    NSRunningApplication* app = [NSRunningApplication currentApplication];
    NSApplicationActivationPolicy activationPolicy = [app activationPolicy];
    [pool release];
    switch (activationPolicy) {
        case NSApplicationActivationPolicyRegular:
        case NSApplicationActivationPolicyAccessory:
            return true;
        case NSApplicationActivationPolicyProhibited:
            break;
    }
```
This block is present both in 2.2.3 and in 3.0.0rc1.

Can you printf the value of `activationPolicy` in both versions when you try to import the module?

**Comment by jklymak** [comment]
printing as a %d, `activationPolicy` is -1 in `v3.0.0rc1` and doesn't trigger the break or return below.  

In `v2.2.3` it returns 0, and returns `true` out of the `ActivationPolicyAccessory` case.  

Sorry, I have no idea what `[app activationPolicy]` does, or I could try and fix, but right now its broken on 3.0, and works 2.2.3...

**Comment by jklymak** [comment]
I think you moved `NSApp = [NSApplication sharedApplication];` into `lazy_init` but `verify_framework()` needs the app to have started?

**Comment by anntzer** [comment]
Just jotting down some notes:
- `[foo bar]` is basically objC for `foo.bar()`.
- Looks like the issue was known since when the code came in: https://github.com/matplotlib/matplotlib/pull/4452#issuecomment-105176711.
- We can't afford to start an app unless we're going to commit to the osx backed because otherwise trying to use another backend can cause a segfault when the other GUI toolkit tries itself to start an app (that was caught by the unit test that went in #11600 and is what motivated the refactor in _macosx.m to start with)

**Comment by jklymak** [comment]
That all sounds correct.  I think the check should go into lazy_init, but lazy_init needs to return something in failure and the higher functions need to bail on failure so the python interpreter can throw the error.   I wasn’t familiar enough with the c++ to get that to happen.

**Comment by anntzer** [comment]
Also, does it work if you switch back to using the osx<10.6 #ifdef?

**Comment by dstansby** [comment]
Feel free to ping me in pull requests if anyone wants someone with a mac to test stuff.
