### ISSUE TITLE
Feature request: metric units

### ISSUE THREAD

**Issue by RollsW** [matplotlib/matplotlib#11849]
OK I have a feature request. At the moment matplotlib calculates the size of graphs in inches. I would be very surprised if anybody outside the USA (or anybody in the scientific community) regularly uses non-SI measurement units by choice. Please could we have the option to describe graph sizes in cm or mm as well? 

It's not a massive deal (we can obviously just divide everything by 2.54) but it would certainly make code using matplotlib cleaner if we didn't end up doing this every time we use it.

Thanks for reading!

Will

**Comment by anntzer** [comment]
Already being discussed at #5104, #9226 and a few other places.
