### ISSUE TITLE
quiver incorrectly inverts y axis

### ISSUE THREAD

**Issue by phyzx1** [matplotlib/matplotlib#11857]
### Bug report

The quiver function does not correctly invert the arrows when using .invert_yaxis(). The Y axis is inverted, but the arrows are not correctly inverted.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

X = np.arange(-10, 10, 1)
Y = np.arange(-10, 10, 1)
U, V = np.meshgrid(X, Y)

# Generate quiver plot
fig, (ax0, ax1, ax2) = plt.subplots(1, 3)
q = ax0.quiver(X, Y, U, V)
ax0.quiverkey(q, X=0.01, Y=1.1, U=10,
             label='quiver(X, Y, U, V)', labelpos='E')

plt.show()

# Use invert_yaxis(). Note that arrows are NOT flipped correctly
q = ax1.quiver(X, Y, U, V)
ax1.quiverkey(q, X=0.01, Y=1.1, U=10,
             label='quiver(X, Y, U, V), invert_yaxis()',labelpos='E')
ax1.invert_yaxis()
plt.show()

# Negate the V component to display the inverted plot correctly
q = ax2.quiver(X, Y, U, -V)
ax2.quiverkey(q, X=0.01, Y=1.1, U=10,
             label='quiver(X, Y, U, -V), invert_yaxis()', labelpos='E')
ax2.invert_yaxis()
plt.show()
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
![image](https://user-images.githubusercontent.com/34775310/44162455-5c59f680-a08e-11e8-8d0d-65567e6ba0bb.png)

```

**Expected outcome**

See image above, or run the snippet of code to see the problem and workaround. 

**Matplotlib version**
  * Operating system:  Windows 10
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:  3.6.3 (Spyder 3.3.0)
  * Jupyter version (if applicable):
  * Other libraries: 

Installed matplotlib via anaconda 3.0

**Comment by phyzx1** [comment]
Well, I dug up the source code, and Lo! and Behold! There is additional documentation that states that
" Note: inverting a data axis will correspondingly invert the arrows only with ``angles='xy'``.

I guess this is not a bug after all.  Apparently I did not look carefully through all of the possible keywords. 
It was not obvious to me that the "angles" keyword was relevant to my issue.

**Comment by christian-rauch** [comment]
@phyzx1 Thanks for the hint.

The documentation for `quiver`'s parameter `angles` actually states:
> Note: inverting a data axis will correspondingly invert the arrows only with angles='xy'.

This is easy to miss when looking for axes related issues.
