### ISSUE TITLE
Tick label shows a small float instead of 0 for 1 subplot only

### ISSUE THREAD

**Issue by arbolis** [matplotlib/matplotlib#11853]
**Bug summary**
I use a MultipleLocator for a plot consisting of 2 subplots that do not share the same y axis. I expect the tick labels to show 0, 2, 4, 6, etc., which is what happens for the 1st subplot, but not for the 2nd subplot. For that subplot, 0 is not displayed but something like -3.85...e-15 is displayed instead (messing up my axis labels).

**Code for reproduction**
I'm too lazy for a full MWE. Here are some relevant lines:

```python
fig, axes = plt.subplots(2, 1, figsize=get_figsize(100.0 / 2.5, wf=1.0, hf=1.0), sharex = True, sharey = False)
# Possibly relevant lines:
scale_y = 1e-3
ticks_y = ticker.FuncFormatter(lambda y, pos: '{0:g}'.format(y/scale_y))
axes[0].yaxis.set_major_formatter(ticks_y)
axes[1].yaxis.set_major_formatter(ticks_y)

# Now what I believe is the real thing.
loc_major_y2 = ticker.MultipleLocator(base=2.0e-6)
axes[1].yaxis.set_major_locator(loc_major_y2)
axes[0].yaxis.set_major_locator(loc_major_y2)
```

**Actual outcome**

Everything is fine except the 0 tick label of axes[1] (the 2nd subplot), which shows a small negative float instead of 0.

**Expected outcome**
I expected 0 to be displayed instead of that small float. It is correctly displayed in the 1st plot.

**Matplotlib version**

  * Operating system: GNU/Arch Linux.
  * Matplotlib version: 2.2.3.
  * Python version: 3.7

Installed Matplotlib using pacman.

**Comment by jklymak** [comment]
It’s really hard to tell what the issue is w/o knowing what your xlims are.  I dont think we can help you without a MWE, and I think if you make one you’ll fix the problem.

**Comment by arbolis** [comment]
Changed the line ticks_y = ticker.FuncFormatter(lambda y, pos: '{0:g}'.format(y/scale_y)) to
ticks_y = ticker.FuncFormatter(lambda y, pos: '{0:g}'.format(int(y/scale_y))) did it, so it seems it wasn't a bug.
