### ISSUE TITLE
Adding "pie of pie" and "bar of pie" functionality

### ISSUE THREAD

**Issue by pjk645** [matplotlib/matplotlib#11858]
Excel has a functionality where a wedge of a pie chart can be "exploded" out into another pie or bar chart to explain the distribution within the wedge's subgroup. I couldn't find any support for this so I hacked a solution as I don't like being out charted by Excel. Maybe you guys could use this to make a more elegant version as I'm mostly a coder and not a developer.  The code and output is below. I'm running Python 3.6.5 (Anaconda 5.2 dist) and matplotlib 2.2.2 on a Windows 7 64 bit machine.

```
import matplotlib.pyplot as plt
from matplotlib.patches import ConnectionPatch
import numpy as np
import math

# style choice
plt.style.use('fivethirtyeight')

# make figure and assign axis objects
fig = plt.figure(figsize=(15,7.5))
ax1 = fig.add_subplot(121)
ax2 = fig.add_subplot(122)

# pie chart parameters
ratios = [.27, .56, .17]
labels = ['Approve', 'Disapprove', 'Undecided']
explode=[0.1,0,0]
# rotate so that first wedge is split by the x-axis
angle = -180*ratios[0]
ax1.pie(ratios, autopct='%1.1f%%', startangle=angle,
        labels=labels,explode=explode )

# bar chart parameters

xpos = 0
bottom = 0
ratios = [.33, .54, .07, .06]
width = .2
colors = [[.1,.3,.5], [.1,.3,.3], [.1,.3,.7], [.1,.3,.9] ]

for j in range(len(ratios)):
    height = ratios[j]
    ax2.bar(xpos, height, width, bottom=bottom, color=colors[j])
    ypos = bottom + ax2.patches[j].get_height()/2
    bottom += height
    ax2.text(xpos,ypos, "%d%%" % (ax2.patches[j].get_height()*100), ha='center')

plt.title('Age of approvers')
plt.legend(('50-65', 'Over 65', '35-49', 'Under 35'))
plt.axis('off')
plt.xlim(-2.5*width, 2.5*width)


# use ConnectionPatch to draw lines between the two plots
# get the wedge data for the first group
theta1, theta2 = ax1.patches[0].theta1, ax1.patches[0].theta2
center, r = ax1.patches[0].center, ax1.patches[0].r
bar_height = sum([item.get_height() for item in ax2.patches])
x = r*np.cos(math.pi/180*theta2)+center[0]
y = np.sin(math.pi/180*theta2)+center[1]
con = ConnectionPatch(xyA=(-width/2,bar_height), xyB=(x,y), coordsA="data", coordsB="data",
                      axesA=ax2, axesB=ax1)
con.set_color([0,0,0])
con.set_linewidth(4)
ax2.add_artist(con)

x = r*np.cos(math.pi/180*theta1)+center[0]
y = np.sin(math.pi/180*theta1)+center[1]
con = ConnectionPatch(xyA=(-width/2,0), xyB=(x,y), coordsA="data", coordsB="data",
                      axesA=ax2, axesB=ax1)
con.set_color([0,0,0])
ax2.add_artist(con)
con.set_linewidth(4)

plt.show()
```

Output:
![bar_of_pie_example](https://user-images.githubusercontent.com/28957002/44166830-641f9800-a09a-11e8-8687-2dc3046ef32c.png)

**Comment by anntzer** [comment]
Seems suitable (possibly) as a gallery entry.

**Comment by pjk645** [comment]
I'm happy to clean it up if you think that is a good direction in which to go.

**Comment by WeatherGod** [comment]
Yeah, I think having this as a gallery example would be better than adding
complex functionality into pie().

**Comment by ImportanceOfBeingErnest** [comment]
:+1: @pjk645 Would you be comfortable with creating a pull request for this?  
You would need to add a file to [/examples/pie_and_polar_charts](https://github.com/matplotlib/matplotlib/tree/master/examples/pie_and_polar_charts) with this code in it and a couple of explaining words. You could use the other files in that folder as a pattern/template.

I think the code is mostly fine, except one could replace the pyplot functions with the respective axes methods (e.g. `ax2.set_title()` instead of `plt.title`) such that it is more obvious which axes is worked on. Also the figure size should not exceed 9 inch in width for examples.

**Comment by pjk645** [comment]
I haven't done it before, but I'll give it a go

**Comment by jklymak** [comment]
https://matplotlib.org/devel/contributing.html  Let us know if anything is not clear.  Generally editing an example is straight forward, but beware of flake8 style issues....

**Comment by pjk645** [comment]
Okay, I made a pull request:  #11865 

As I said, I code but I am an experienced developer so sorry if I'm not following the usual standards.

**Comment by pjk645** [comment]
Example of bar of pie plot added.
