### ISSUE TITLE
Figure does not close until script finishes execution

### ISSUE THREAD

**Issue by adamjstewart** [matplotlib/matplotlib#11861]
### Bug report

**Bug summary**

I have a script that loads some data, plots it, and then trains a machine learning model. When I manually try to close the figure window, the script continues, but the figure remains open until the script finishes execution.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import time

x = np.arange(5)
y = np.arange(5)

plt.plot(x, y)
plt.show()

time.sleep(30)
```

**Actual outcome**

When I try to close the figure window, it remains open until the entire script finishes execution.

**Expected outcome**

When I close the figure window, the figure should disappear immediately.

**Matplotlib version**

  * Operating system: macOS 10.13.6 (High Sierra)
  * Matplotlib version: 2.2.3 (conda)
  * Matplotlib backend: MacOSX
  * Python version: 3.6.5 (conda)

**Comment by tacaswell** [comment]
I suspect there is a weird race condition between the window being closed, the event loop being stopped, and the GUI re-drawing the window out of existence.

See https://github.com/matplotlib/matplotlib/pull/4779 for many details about the GUI event loop integration.

I suspect putting `plt.pause(.1)` in will make it 'work'.

**Comment by adamjstewart** [comment]
Unfortunately, `plt.pause(.1)` did not work. Tried before and after the `plt.show()` line.

**Comment by adamjstewart** [comment]
Update: I switched to the Qt5Agg backend and this bug no longer occurs. So this is definitely a bug in the MacOSX backend. It seems like the MacOSX backend is very buggy and lacking in terms of features. Also see #11879 for other bugs I've encountered.
