### ISSUE TITLE
Why there is limit to plot vertical lines?

### ISSUE THREAD

**Issue by hoyeunglee** [matplotlib/matplotlib#11878]
![image](https://user-images.githubusercontent.com/5094741/44295921-bdc7d280-a2e5-11e8-8b7c-9a23c5ce3b34.png)

![image](https://user-images.githubusercontent.com/5094741/44295936-dfc15500-a2e5-11e8-9fe7-83d751f9f0d7.png)

**Comment by QuLogic** [comment]
Line 2 is:
```python
    if result[xc] == 1 and xc == 0:
```
This is not a bug in Matplotlib. Please use [StackOverflow](https://stackoverflow.com/) or the [mailing list](https://mail.python.org/pipermail/matplotlib-users/) for general usage questions.
