### ISSUE TITLE
Unable to change filename when saving from figure window

### ISSUE THREAD

**Issue by adamjstewart** [matplotlib/matplotlib#11879]
### Bug report

**Bug summary**

When I try to save a figure by clicking the save button in the figure window, it doesn't allow me to change the filename. Even if I explicitly click the Finder-like window that pops up, all text is sent to the Terminal.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.plot()
plt.show()
```

**Actual outcome**

I am unable to change the filename, and all text is sent to the Terminal. This may be related to the fact that I'm seeing the following error message in the Terminal:
```
objc[36742]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8965cc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x112aa1cd8). One of the two will be used. Which one is undefined.
```
Perhaps the error message is forcing the focus to be on the Terminal? It would be interesting to see if anyone can reproduce this without any error message.

**Expected outcome**

I should be able to change the filename.

**Matplotlib version**

  * Operating system: macOS 10.13.6 (High Sierra)
  * Matplotlib version: 2.2.3 (conda)
  * Matplotlib backend: MacOSX
  * Python version: 3.6.5 (conda)

**Comment by adamjstewart** [comment]
Update: I switched to the Qt5Agg backend and this bug no longer occurs. So this is definitely a bug in the MacOSX backend.

Side note: I noticed that the Qt5Agg backend is significantly more powerful than the MacOSX backend. The MacOSX backend figure window does not have the "Edit axis, curve and image parameters" button that the Qt5Agg backend has. Is there some fundamental limitation of the MacOSX backend that prevents this, or does it just need a developer to work on? Also, where can I find a side-by-side comparison of each backend in terms of functionality and speed?

**Comment by WeatherGod** [comment]
I swear, I remember this bug from a long time ago. Could this be a
framework/non-framework build issue again?

**Comment by jklymak** [comment]
Yes that is exactly what this is.  @adamjstewart if you do pip install python.app and then run pythonw instead of python this should work.  OTOH I thought the macOS backend was not supposed to work at all if you didn’t do this.

**Comment by adamjstewart** [comment]
`pythonw` did the trick! The default backend for conda-installed matplotlib is MacOSX. I wonder if this could be changed.

**Comment by tacaswell** [comment]
I am not sure we can fix this if it is related to if the GUI event loop is spinning correctly or not which depends on the details of the python build...

**Comment by jklymak** [comment]
@anntzer - sorry to be dense - what do you want tested?

**Comment by anntzer** [comment]
Looks like the original bug arises from running the OSX backend on a non-framework build(?), which should not happen anymore after the backend-switching+framework-detection work(?)

**Comment by dstansby** [comment]
I can't get the OSX backend to get past the expected error message now; closing this, but anyone feel free to re-open if I've missed something.
