### ISSUE TITLE
imread() produces a misleading error: "read past end of file"

### ISSUE THREAD

**Issue by AlekseyMalyshev** [matplotlib/matplotlib#11886]
### Bug report

**Bug summary**

When imread() encounters an image file with zero length, it produces an exception "read past end of file"

**Code for reproduction**

```python
# Paste your code here
#
#
plt.imread("image.png")
```

**Actual outcome**

Exception "read past end of file"

**Expected outcome**

There should be a more meaningful behavior if we try to open a zero length file. Maybe return an empty result.

**Matplotlib version**

  * Operating system:  Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1019-aws x86_64) (on AWS)
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.6.5
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: TensorFlow 1.10.0 Keras 2.2.2

I used pip3 to install everything.

**Comment by anntzer** [comment]
No, an empty file is not a valid file in the PNG, JPEG, or any other image format we support.

**Comment by mat2py** [comment]
> There should be a more meaningful behavior if we try to open a zero length file.
> imread() produces a misleading error

> No, an empty file is not a valid file in the PNG, JPEG, or any other image format we support.

This is still an open issue. not supporting it is irrelevant in the discussion of whether it is a misleading error message. It is however relevant in whether it should return an empty result or an error which says "empty files are not supported". Which would be a lot less misleading. Googling this error comes directly to this bug ticket

**Comment by timhoffm** [comment]
Since matplotlib 3.3.0, we have switched to pillow for png reading, and this now gives the error message
```
SyntaxError: not a PNG file
```
which should be good enough. Any further requests concerning the message should be targeted to pillow.

**Comment by mp-v2** [comment]
Ah perfect, case closed!
