### ISSUE TITLE
datetime.datetime.strptime(root[i+3][2][0].text, "%H:%M:%S:%f")  

### ISSUE THREAD

**Issue by timeanddoctor** [matplotlib/matplotlib#11885]
A analysis script ([https://github.com/pariterre/KinoveaAnalyse] created by pariterre, while there is a error such as: 

datetime.datetime.strptime(root[i+3][2][0].text, "%H:%M:%S:%f")
OSError: [Errno 22] Invalid argument

>  data = {}
>     data_to_stack = np.ndarray((3, 1))  # Declare data stacker that keeps being updated (Time, X, Y)
>     for repere in reperes_anato:
>         repere_found = False
>         data_tp = np.ndarray((3, 0))  # Append all data
>         # Find the data for each reperes
>         for i in range(len(root)):
>             # If we haven't reach the repere so far
>             if not repere_found:
>                 if root[i][0][0].text is not None and len(root[i]) > 1 and root[i][1][0].text == repere:
>                     repere_found = True
>             # If we finished the repere
>             elif len(root) <= i+3 or root[i+3][0][0].text is None:
>                 break
>             # Otherwise add data
>             else:
>                 data_to_stack[0, 0] = datetime.datetime.timestamp(
>                     datetime.datetime.strptime(root[i+3][2][0].text, "%H:%M:%S:%f")
>                 )
>                 data_to_stack[1, 0] = root[i+3][0][0].text
>                 data_to_stack[2, 0] = root[i+3][1][0].text
>                 data_tp = np.hstack((data_tp, data_to_stack))

the source data from example document.
Anyone could help me to deal with it, Thanks!

**Comment by jklymak** [comment]
This doesn't look to be a bug in matplotlib.  Please consider using stackoverflow for user support.
