### ISSUE TITLE
Histogram of list of datetimes

### ISSUE THREAD

**Issue by Zinjaai** [matplotlib/matplotlib#11899]
### Bug report

**Bug summary**
When creating a histogram of a list of datetimes, the input seems to be interpreted as a sequency of arrays.

**Code for reproduction**

```python
from datetime import datetime
from matplotlib import pyplot as plt
plt.hist([datetime(2018,1,1),  datetime(2018, 2, 1),  datetime(2018,3, 1)])

# We get the expected result,  when we cast the list to a numpy array (but only if we specify the dtype?!)
# import numpy
# plt.hist(numpy.array([datetime(2018,1,1),  datetime(2018, 2, 1),  datetime(2018,3, 1)], dtype='datetime64[h]'))

```

**Actual outcome**

Output of **n** is a list of arrays, indicating that the input dates are interpreted as a sequence of arrays.
```
# If applicable, paste the console output here
([array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),   #  <---  expected array instead of list of arrays
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])],
 array([736695. , 736700.9, 736706.8, 736712.7, 736718.6, 736724.5,
        736730.4, 736736.3, 736742.2, 736748.1, 736754. ]),
 <a list of 3 Lists of Patches objects>)
```
Output of matplotlib version 2.2.0, 2.2.2 and 2.2.3 

**Expected outcome**

```
# If applicable, paste the console output here
(array([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.]),
 array([736695. , 736700.9, 736706.8, 736712.7, 736718.6, 736724.5,
        736730.4, 736736.3, 736742.2, 736748.1, 736754. ]),
 <a list of 10 Patch objects>)
```
This worked in matplotlib version 2.1.2

**Matplotlib version**

  * Operating system: Fedora 27
  * Matplotlib version:  2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version:  3.6.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Your example is nt quite complete, so maybe I'm doing something wrong, but for 

```python

from matplotlib import pyplot as plt
import datetime

n, x = plt.hist([datetime.datetime(2018,1,1),  datetime.datetime(2018, 2, 1),
                 datetime.datetime(2018,3, 1)])
```

on 2.1.2 I get 
```
Traceback (most recent call last):
  File "testHist.py", line 5, in <module>
    datetime.datetime(2018,3, 1)])
ValueError: too many values to unpack (expected 2)
```

So I don't think it worked on 2.1.2 either.

**Comment by Zinjaai** [comment]
@jklymak  have i been able to clarify your questions?  Greetings!

**Comment by jklymak** [comment]
This bisects to c02a84d95c2497215b73ae14967969d422bec229 "Correctly convert units for a stacked histogram" @dstansby

**Comment by Zinjaai** [comment]
>   I guess this used to work before, but whether or not it really should have is debatable.

To be able to create a histogram from a list of datetimes seems pretty beneficial to me.

```
from datetime import datetime
from matplotlib import pyplot as plt
plt.figure(figsize=(12, 6))
dates = [datetime(2010, 6, 15)] * 2 + \
        [datetime(2011, 6, 15)] * 3 + \
        [datetime(2012, 6, 15)] * 7 + \
        [datetime(2013, 6, 15)] * 4 + \
        [datetime(2015, 6, 15)] * 1
plt.hist(dates, bins=5, rwidth=0.8)
plt.xlabel('Year')
plt.ylabel('Number of events')
```

Old matplotlib version
![old](https://user-images.githubusercontent.com/42547503/44578057-e98a0300-a792-11e8-8312-d98fe351348e.png)

Newer version
![new](https://user-images.githubusercontent.com/42547503/44578062-ebec5d00-a792-11e8-911d-37049bcc0774.png)

In contrast to dates, i haven't that often tried to create histograms of strings, .... :confused:

**Comment by haydenflinner** [comment]
This just caused plotting a 70MB file to explode to over 50GB of memory for me, quite surprising that I can't plot a histogram of datetimes.

**Comment by jklymak** [comment]
This should be fixed on master...

**Comment by haydenflinner** [comment]
Awesome! I'm on a pretty old version, so I'll leave the explicit conversion for now
