### ISSUE TITLE
DOC: Colormap tutorial needs info on manipulating colormaps

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11903]
### Bug report

I don't see where in the documentation we help users know how to create or manipulate colormaps.  Seems it should go here or in its own tutorial under `colors`:
 https://matplotlib.org/tutorials/colors/colormaps.html#sphx-glr-tutorials-colors-colormaps-py

Crossref #7716

**Comment by afvincent** [comment]
There may be something [here](https://matplotlib.org/gallery/images_contours_and_fields/custom_cmap.html).

**Comment by jklymak** [comment]
Great!  Thanks, that should be in there too.  OTOH it doesn't discuss `ListedColormap` which is a great way to make concatenated colormaps, so I think that needs documenation as well.  But thanks, I made an issue because I wanted to make sure folks pointed me to stuff I was missing!

**Comment by afvincent** [comment]
I am not saying that the current doc is enough for every use case: TBH I never really understood it ^^.

**Comment by jklymak** [comment]
... I understand it, but not well enough to not have to look it up everytime I need to make a colormap.  Which is good, because it means I spend very little time making tweaked colormaps 😛

**Comment by anntzer** [comment]
Looking at #7716 again, truncation is basically just e.g.
```
cmap = colors.ListedColormap(plt.cm.viridis(np.linspace(.3, .7, 256)))
```
and concatenation
```
cmap = colors.ListedColormap(np.vstack([
    plt.cm.viridis(np.linspace(0, .5, 50)),
    plt.cm.jet(np.linspace(.5, 1, 50)),
]))
```
with much more lines spent doing input checking/massaging than anything else, so I now agree that we may just want to better document this.
(This doesn't take care of over/under/bad, but neither does #7716...)

**Comment by jklymak** [comment]
WRT https://matplotlib.org/gallery/images_contours_and_fields/custom_cmap.html, I took a crack at improving the explanation in #11905.  If its actually better, I'd suggest we rewrite `custom_cmap` and also add a short `ListedColormap` example.
