### ISSUE TITLE
Improve linestyle documentation

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#11908]
We currently have

https://matplotlib.org/gallery/lines_bars_and_markers/line_styles_reference.html
https://matplotlib.org/gallery/lines_bars_and_markers/linestyles.html

which are partly redundant. Also one of them uses the (offset, on-off-dash-seq) but does not explain it.

This should be merged in to a single comprehensible file with a bit more explanation.

See also:
https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle
(which itself is not in great shape)

**Comment by tacaswell** [comment]
Is this fully addressed by #11909?

**Comment by ImportanceOfBeingErnest** [comment]
In https://github.com/matplotlib/matplotlib/issues/11797 I compared the different ways to set linestyle and there seem to be a couple of inconsistencies and missing options. So getting clear about which option/syntax can be used where would also help (re)writing the examples.

**Comment by thoo** [comment]
I am a new comer and would like to work on this. Would [this](https://matplotlib.org/devdocs/devel/documenting_mpl.html#documenting-matplotlib) be a good place to start? Thanks.

**Comment by timhoffm** [comment]
Yes, particularly "Writing examples and tutorials".
