### ISSUE TITLE
MatplotlibDeprecationWarning: The poly_between function was deprecated in version 2.2. xs, ys = poly_between(angles, 0, val) 

### ISSUE THREAD

**Issue by scls19fr** [matplotlib/matplotlib#11911]
Hello,

I'm using `poly_between` function 

see https://github.com/python-windrose/windrose/issues/81

but it displays a depreciation warning.

    MatplotlibDeprecationWarning: The poly_between function was deprecated in version 2.2. xs, ys = poly_between(angles, 0, val)

Does an alternative function exist?

Kind regards

**Comment by anntzer** [comment]
No.  You can either copy the function to windrose, or, in this particular case, you can just fix the implementation with
```
diff --git i/windrose/windrose.py w/windrose/windrose.py
index 1db3d17..9afd551 100644
--- i/windrose/windrose.py
+++ w/windrose/windrose.py
@@ -454,9 +454,9 @@ class WindroseAxes(PolarAxes):
             val = vals[i, :] + offset
             offset += vals[i, :]
             zorder = ZBASE + nbins - i
-            xs, ys = poly_between(angles, 0, val)
-            patch = self.fill(xs, ys, facecolor=colors[i],
-                              edgecolor=colors[i], zorder=zorder, **kwargs)
+            patch = self.fill(np.append(angles, 0), np.append(val, 0),
+                              facecolor=colors[i], edgecolor=colors[i],
+                              zorder=zorder, **kwargs)
             self.patches_list.extend(patch)
 
     def bar(self, direction, var, **kwargs):
```
which is going to be more efficient anyways...

**Comment by scls19fr** [comment]
Thanks @anntzer for this fix

**Comment by chayanroyc** [comment]
I get the same error with using windrose. 💯 
ImportError: cannot import name 'poly_between' from 'pylab' (C:\Users\acer\AppData\Local\Programs\Python\Python37\lib\site-packages\pylab.py)
What should I do? I don't understand how to implement the fix given here.

**Comment by WeatherGod** [comment]
This most likely means that the windrose package needs updating. I am
assuming you aren't directly calling `poly_between`, right?

**Comment by scls19fr** [comment]
https://github.com/python-windrose/windrose/pull/114 have been merged.

Could you try latest master version?

**Comment by chayanroyc** [comment]
I downloaded windrose from PyCharm. It shows the error when I run it.

**Comment by scls19fr** [comment]
https://github.com/python-windrose/windrose#install-latest-development-version

**Comment by chayanroyc** [comment]
How do I download this into my Pycharm IDE? By using pip?

**Comment by scls19fr** [comment]
New version have been upload on Pypi
