### ISSUE TITLE
plt.contour levels parameter don't work as intended if receive a single int

### ISSUE THREAD

**Issue by eisterman** [matplotlib/matplotlib#11913]
### Bug report

**Bug summary**

The official documentation (https://matplotlib.org/api/_as_gen/matplotlib.pyplot.contour.html) says that the parameter `levels` of the `pyplot.contour` function is an integer will be calculated and shown a number of contours equal to the number passed as a parameter.
The reality of the facts, however, is that the outline associated with the past value is plotted.

**Code for reproduction**

I used the contour demo example from https://matplotlib.org/gallery/images_contours_and_fields/contour_demo.html#contour-demo adding the `levels` parameter as int.

```python
import matplotlib
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
# the original demo had 2 here, but so most of the values would have been less than 5
Z = (Z1 - Z2) * 6

plt.contour(X, Y, Z, levels=5)
plt.show()
```

**Actual outcome**

![Output_bug_1](https://i.imgur.com/BKuH99m.png)

**Expected outcome**

According to official documentation I should expect 5 outlines and not the boundary associated with the value 5.
![Right_outcome_1](https://i.imgur.com/wEOm7SP.png)

The expected output was obtained by modifying the penultimate line in:
```python
plt.contour(X, Y, Z, levels=np.linspace(np.min(Z),np.max(Z),7))
```

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.0
  * Other libraries: `numpy`

All libraries have been installed via the official ArchLinux repository

**Comment by jklymak** [comment]
Yeah, this is a bit funky.  It works fine if you do: `plt.contour(X, Y, Z, 5)`.  So if you specify `levels` as a kwarg, it assumes you have entered the actual levels you want contoured.  Its debatable if this is desirable or not - I'd vote for it being undesirable, and `levels=5` should behave as you expected it should (i.e. the same as if 5 was passed in as a positional argument), but maybe the original authors had a reason for this behaviour. 

I would say that `levels=[5]` should only make one contour.

**Comment by jklymak** [comment]
Milestoning 3.1, since this behaviour has been present since at least 2.0.2

**Comment by tacaswell** [comment]
I think @efiring changed some of this for 3.0 already.

**Comment by efiring** [comment]
I see where the problem is.
