### ISSUE TITLE
Limiting ticks on colorbar axes falsify tick labels.

### ISSUE THREAD

**Issue by juseg** [matplotlib/matplotlib#11937]
### Bug report

Using ``locator_params(nbins=)`` on colorbar axes yield incorrect tick labels.

If one has not checked data values this can quietly produce wrong figures. If this is an uncorrect usage of ``locator_params``, is it possible to warn the user against that (docs, warming)?

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

# simple contour plot with labels and colorbar
cs = plt.contourf(np.arange(24).reshape(6, 4))
cs.clabel(colors='k', fmt='%.0f')
cb = plt.colorbar(cs, label='cbar with wrong values')

# reduce number of colorbar ticks
# (this is the problematic line)
cb.ax.locator_params(axis='y', nbins=6)

plt.show()
```

**Actual outcome**

![caxbins](https://user-images.githubusercontent.com/1186928/44624862-0cecb380-a935-11e8-8ca0-0fcf8b995080.png)

**Expected outcome**

The colorbar tick labels should span 0 to 24 (see contour labels).

**Matplotlib version**

OS: Linux
python: 2.7.15.final.0
numpy: 1.15.0 (pip)
matplotlib: 2.2.3 (pip)

Many thanks for all the good work!

**Comment by timhoffm** [comment]
Not 100% sure what is going on

~~~
import numpy as np
import matplotlib.pyplot as plt

# simple contour plot with labels and colorbar
cs = plt.contourf(np.arange(24).reshape(6, 4))
cs.clabel(colors='k', fmt='%.0f')
cb = plt.colorbar(cs, label='cbar with wrong values')

# reduce number of colorbar ticks
axlocator = cb.ax.yaxis.get_major_locator()
locator, formatter = cb._get_ticker_locator_formatter()
print(axlocator)
print(locator)
locator.set_params(nbins=6)
cb.update_ticks()
plt.show()
~~~
![grafik](https://user-images.githubusercontent.com/2836374/44625987-d2731e80-a914-11e8-9c2b-e36fc7666888.png)

There seems to be two different locators. Note that `cb.ax.yaxis.get_major_locator()` is a different object than `cb._get_ticker_locator_formatter()`. If I use the latter and additionally `cb.update_ticks()`, it works as expected. Unfortunately this is a private API. Also the original example would be the natural way to address this problem. It should be made working or at least break with a reasonable message.

**Comment by efiring** [comment]
At least part of the problem--maybe all of it--is that `Axis.set_ticks()` always makes a *new* `FixedLocator` instead of just changing the `locs` array if there is already a `FixedLocator` in place.

**Comment by efiring** [comment]
It's more complicated than that...

**Comment by jklymak** [comment]
Just to clarify a bit.  This is a problem with the locator for contours.  The above code works with pcolor for instance.  

Someone would have to dig into what the interaction is between the contour locator and locator_params, but my assumption would be that you just shouldn’t do this.

**Comment by nedlrichards** [comment]
Just ran into this issue myself, but using pcolormesh.

```
mport numpy as np
import matplotlib.pyplot as plt

td = np.random.randn(300, 300)
p_dBh = 20 * np.log10(np.abs(td))

fig, ax = plt.subplots()
cm = ax.pcolormesh(p_dBh,
                   vmin=-20, vmax=10,
                   rasterized=True)
cb = fig.colorbar(cm)
cb.ax.locator_params(nbins=5)
```

![out_a](https://user-images.githubusercontent.com/11950875/65071360-7e821000-d943-11e9-80fe-758ced23fa3d.png)

With the locator_param commented out.

![out_b](https://user-images.githubusercontent.com/11950875/65071406-9063b300-d943-11e9-88ae-b42b1ae83de5.png)

I am also having trouble with recommended fix
```
cb._get_ticker_locator_formatter()
------------------------------------------------------------------
AttributeError                   Traceback (most recent call last)
<ipython-input-6-201c29ef113a> in <module>()
----> 1 cb._get_ticker_locator_formatter()

AttributeError: 'Colorbar' object has no attribute '_get_ticker_locator_formatter'
```

**Comment by juseg** [comment]
I stumbled again upon this issue while using a stand-alone `ColorbarBase`. The problem appears with `BoundaryNorm`, but not with `Normalize`.

```
import matplotlib as mpl
import matplotlib.pyplot as plt

# initialize axes
ax0 = plt.axes([0.1, 0.1, 0.1, 0.8])
ax1 = plt.axes([0.4, 0.1, 0.1, 0.8])
ax2 = plt.axes([0.7, 0.1, 0.1, 0.8])

# add colorbars
normalize = mpl.colors.Normalize(0, 10)
boundarynorm = mpl.colors.BoundaryNorm(boundaries=range(11), ncolors=256)
cb0 = mpl.colorbar.ColorbarBase(ax=ax0, norm=boundarynorm)
cb1 = mpl.colorbar.ColorbarBase(ax=ax1, norm=boundarynorm)
cb2 = mpl.colorbar.ColorbarBase(ax=ax2, norm=normalize)

# limit ticks
ax1.locator_params(nbins=3)
ax2.locator_params(nbins=3)

# add labels
cb0.set_label('BoundaryNorm')
cb1.set_label('BoundaryNorm, nbins=3')
cb2.set_label('Normalize, nbins=3')
```

![colorbarbug](https://user-images.githubusercontent.com/1186928/69275133-14ecdf00-0bdc-11ea-83a4-1eb6327e9ca0.png)

**Comment by efiring** [comment]
@nedlrichards In your example with pcolormesh you were using an earlier version of matplotlib, before @jklymak's modifications that make the colorbar Axes behave more normally in cases where the norm is essentially continuous.  With the current version, your example works. The problem remains for filled contours and BoundaryNorm because they work with discrete intervals, not a continuum, so they require special handling.

Possible solutions:
- disable locator_params for colorbar Axes
- monkey-patch the Axes.locator_params.

More generally, we have the problem that a colorbar Axes simply is not a normal Axes.  Even if we fix this problem with locator_params, there will be other anomalies.  For example, if someone uses the alternative public API `cbar.ax.yaxis.set_params()`, they will run into the same problem.

Another option would be to add a `ColorbarBase.locator_params()` method that does the right thing.  This would be consistent with the established practice exemplified by the `set_label()` method, in which colorbar manipulation and customization is done via Colorbar methods, not generic Axes methods.   This option doesn't remove the foot-cannon, but it provides a way of alerting people to it and giving them an alternative.

**Comment by anntzer** [comment]
Actually I don't think this has anything to do with colorbars, it's just brittleness of FixedFormatter:
```python
from pylab import *

fig, ax = plt.subplots()
ax.set_xlim([0, 10])
ax.set_xticks(range(10))  # Sets up FixedLocator.
ax.set_xticklabels(list("abcdefghij"))  # Sets up FixedFormatter.
ax.set_yticks([])
ax.locator_params(nbins=3)
plt.show()
```
gives
![test](https://user-images.githubusercontent.com/1322974/80347436-953efc80-886c-11ea-8bd6-28926117631e.png)
i.e. FixedFormatter naively labels the first three ticks as "a" "b" "c" even though it was intended that they be labeled by position as "a" "d" "g".

**Comment by efiring** [comment]
Agreed, the problem is with FixedFormatter, but it is turning up in colorbar.
Do you have a solution in mind?  The FixedFormatter limitation seems inherent, because it is designed to do exactly the mindless thing it is doing. Fixing it--doing something smarter--requires a change in API.

**Comment by anntzer** [comment]
We could just make `set_ticklabels` (both on colorbars and on plain axes) not set the axes' formatter to a FixedFormatter, but to the right FuncFormatter.

**Comment by efiring** [comment]
In the general case, I think the FuncFormatter would need to use a dictionary lookup, with the key being the value to be formatted.  But generating that dictionary would require `set_ticklabels` to be called with those values, not just the labels.  That could be done by adding a keyword argument, which would trigger the generation and use of a FuncFormatter.
Is that what you have in mind?

**Comment by anntzer** [comment]
Basically
```
diff --git i/lib/matplotlib/axis.py w/lib/matplotlib/axis.py
index 359999c73..e7d4117a8 100644
--- i/lib/matplotlib/axis.py
+++ w/lib/matplotlib/axis.py
@@ -1626,11 +1626,18 @@ class Axis(martist.Artist):
         """
         ticklabels = [t.get_text() if hasattr(t, 'get_text') else t
                       for t in ticklabels]
+        locator = (self.get_minor_locator() if minor
+                   else self.get_major_locator())
+        if isinstance(locator, mticker.FixedLocator):
+            formatter = mticker.FuncFormatter(
+                lambda x, pos: ticklabels[[*locator.locs].index(x)])
+        else:
+            formatter = mticker.FixedFormatter(ticklabels)
         if minor:
-            self.set_minor_formatter(mticker.FixedFormatter(ticklabels))
+            self.set_minor_formatter(formatter)
             ticks = self.get_minor_ticks()
         else:
-            self.set_major_formatter(mticker.FixedFormatter(ticklabels))
+            self.set_major_formatter(formatter)
             ticks = self.get_major_ticks()
         ret = []
         for tick_label, tick in zip(ticklabels, ticks):
diff --git i/lib/matplotlib/ticker.py w/lib/matplotlib/ticker.py
index 0ed9d489c..96016a99f 100644
--- i/lib/matplotlib/ticker.py
+++ w/lib/matplotlib/ticker.py
@@ -381,8 +381,10 @@ class FuncFormatter(Formatter):
     position ``pos``), and return a string containing the corresponding
     tick label.
     """
+
     def __init__(self, func):
         self.func = func
+        self.offset_string = ""
 
     def __call__(self, x, pos=None):
         """
@@ -392,6 +394,12 @@ class FuncFormatter(Formatter):
         """
         return self.func(x, pos)
 
+    def get_offset(self):
+        return self.offset_string
+
+    def set_offset_string(self, ofs):
+        self.offset_string = ofs
+
 
 class FormatStrFormatter(Formatter):
     """
```
(half of the patch being due to FuncFormatter not supporting set_offset_string...).

One may need better error handling in case the FuncFormatter gets called on a position which is not in the FixedLocator.locs, but that "shouldn't" happen normally.

**Comment by efiring** [comment]
Good.  Ping me when your PR is ready for review.
I think we are still left with a wart: the solution relies on `set_ticklabels` being called after `set_ticks`, which is a natural order but is not enforced.  Maybe the FixedFormatter fallback should trigger a warning?  Or are there cases where that fallback is what the user really needs?

**Comment by anntzer** [comment]
We actually more or less enforce that now with the warning in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axis.py#L1531.

To be honest I'm just posting the patch with the hope that someone will pick it up and turn it into a real PR ;-), right now I don't really care enough about this specific use case to write the tests, the docs, and argue whether changing the formatter type that set_ticklabels sets is an API break or not...

**Comment by efiring** [comment]
OK, no problem.  Your patch is a good head start.  I didn't want to start on it if you already had it mostly done.

**Comment by zaheerkzz** [comment]
> I stumbled again upon this issue while using a stand-alone `ColorbarBase`. The problem appears with `BoundaryNorm`, but not with `Normalize`.
> 
> ```
> import matplotlib as mpl
> import matplotlib.pyplot as plt
> 
> # initialize axes
> ax0 = plt.axes([0.1, 0.1, 0.1, 0.8])
> ax1 = plt.axes([0.4, 0.1, 0.1, 0.8])
> ax2 = plt.axes([0.7, 0.1, 0.1, 0.8])
> 
> # add colorbars
> normalize = mpl.colors.Normalize(0, 10)
> boundarynorm = mpl.colors.BoundaryNorm(boundaries=range(11), ncolors=256)
> cb0 = mpl.colorbar.ColorbarBase(ax=ax0, norm=boundarynorm)
> cb1 = mpl.colorbar.ColorbarBase(ax=ax1, norm=boundarynorm)
> cb2 = mpl.colorbar.ColorbarBase(ax=ax2, norm=normalize)
> 
> # limit ticks
> ax1.locator_params(nbins=3)
> ax2.locator_params(nbins=3)
> 
> # add labels
> cb0.set_label('BoundaryNorm')
> cb1.set_label('BoundaryNorm, nbins=3')
> cb2.set_label('Normalize, nbins=3')
> ```
> 
> ![colorbarbug](https://user-images.githubusercontent.com/1186928/69275133-14ecdf00-0bdc-11ea-83a4-1eb6327e9ca0.png)

this solved my problem.
