### ISSUE TITLE
Contours are not removed correctly when using clabel with inline=True

### ISSUE THREAD

**Issue by mrich** [matplotlib/matplotlib#11945]
### Bug report

**Bug summary**

Several of the contours created using pyplot.contour are not correctly removed when labelling the contours using plt.clabel invoked with inline=True.  In other words, I'm seeing the same behavior reported in [9988](https://github.com/matplotlib/matplotlib/issues/9988).

**Code for reproduction**

```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

def accuracy(sens, spec, prev):
    return sens * prev + spec * (1 - prev)

prev = .01

spec = np.linspace(0,1,50)
sens = np.linspace(0,1,50)
X,Y = np.meshgrid(spec, sens)
Z = accuracy(Y,X,prev)

plt.figure(figsize = (5,5), dpi=100)

# set limits & labels for axes
plt.xlim(1,0)
plt.ylim(0, 1)

contours = plt.contour(X, Y, Z, 11, colors='black')
plt.clabel(contours, inline = True, fontsize=10)
plt.xlabel("Specificity", fontsize = 12)
plt.ylabel("Sensitivity", fontsize = 12)

plt.title(u'Accuracy (prevalence = %0.2f)' %prev, fontsize = 15)

plt.contour(X,Y,Z, colors = 'black')

plt.savefig('Accuracy_prev_01.png', dpi=100)
```

**Actual outcome**

![accuracy_prev_01](https://user-images.githubusercontent.com/1474517/44642716-58797e80-a982-11e8-9dbb-d5cd6113c016.png)

**Expected outcome**

**Matplotlib version**

  * Operating system: Mac OSX - Darwin-17.7.0-x86_64-i386-64bit
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.6.6 :: Anaconda custom (64-bit)
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: numpy version 1.15.0

I installed everything via the Anaconda distribution.  I also updated things since then with:

> conda update conda
> conda update --all

**Comment by QuLogic** [comment]
You are calling `plt.contour` twice; `plt.clabel` doesn't know anything about the second call.

**Comment by mrich** [comment]
Doh!  That does explain everything.  Thanks so much for the rapid reply and resolution.
