### ISSUE TITLE
UnicodeDecodeError on importing pyplot in python2

### ISSUE THREAD

**Issue by AndreySV** [matplotlib/matplotlib#11955]
### Bug report

**Bug summary**

UnicodeDecodeError on importing pyplot If some module in call stack is located in directory with non-ascii character in path. The problem is that traceback.format_stack() returns list of 'str' objects in python2. This problem happens only on python2.

**Code for reproduction**
Create two modules in a directory with a non-ascii character in the path.

```python
#!/usr/bin/env python
# first_module.py
import second_module
```

```python
# second_module.py
import matplotlib.pyplot
```
Run first module.
```
$ python2 first_module.py
```

**Actual outcome**

Following traceback happens
```
Traceback (most recent call last):
  File "./a.py", line 3, in <module>
    import second_module
  File "/home/developer/WorkData/PLC/beremiz/tmp/xыв/beremiz/second_module.py", line 3, in <module>
    import matplotlib.pyplot
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 18, in <genexpr>
    if not line.startswith('  File "<frozen importlib._bootstrap'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 50: ordinal not in range(128)
```

**Matplotlib version**
  * Operating system: Debian Buster
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'WX"
  * Python version: 2.7.15

**Comment by AndreySV** [comment]
Suggested in [comment](https://github.com/matplotlib/matplotlib/issues/9196#issuecomment-416549629) change:

```
_backend_loading_tb = b"".join(
    line for line in traceback.format_stack()
    # Filter out line noise from importlib line.
    if not line.startswith(b'  File "<frozen importlib._bootstrap'))
```
seems to fix the problem. In python2 crash doesn't happen anymore and the code looks to work with python 3.6 either.

**Comment by tacaswell** [comment]
@AndreySV Can you try the fix in #11957 ?  It is slightly different, but should have the same effect.

**Comment by AndreySV** [comment]
all good like originally suggested changed.

**Comment by Zac-HD** [comment]
@tacaswell looks like merging #11957 didn't automatically close this?
