### ISSUE TITLE
Single shot timer not working correctly with MacOSX backend

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#11985]
### Bug report

**Bug summary**

A timer created when using the MacOSX backend and in 'single-shot' mode causes the callback to be called straight away instead of after the specified interval.

**Code for reproduction**

```python
from matplotlib import pyplot as plt

def timercb(e):
    print("timer")

fig, ax = plt.subplots()
timer = fig.canvas.new_timer(interval=5000)
timer.single_shot = True
timer.add_callback(timercb, ax)
timer.start()
plt.show()
```

**Actual outcome**

The script prints out ``timer`` straight away

**Expected outcome**

The script would print out ``timer`` after 5 seconds

**Matplotlib version**

  * Operating system: MacOS X 10.13.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.4

I am using conda to manage my Python ecosystem

**Comment by dstansby** [comment]
I can reproduce this on master.

**Comment by dopplershift** [comment]
Has nothing to do with single shot, I get this behavior without it. The first timer event just happens too soon. I'm investigating...
