### ISSUE TITLE
Feature request: add an option to hide header/title bar in NbAgg/WebAgg

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#11986]
I am making use of the NbAgg backend to implement data viewers for the [Glue](http://glueviz.org/) application in Jupyter notebook. However, one thing that I've found is that the title/header bar is unnecessary in a lot of (my use) cases and there is also a lot of wasted space between the title/header bar and the plot itself:

<img width="781" alt="screen shot 2018-08-30 at 14 59 12" src="https://user-images.githubusercontent.com/314716/44873128-5acf2780-ac65-11e8-9036-98dd40f95dbb.png">

This is even more the case when opening multiple plots in a single notebook.

Would it be possible have a way, e.g. through an rcParameter for ``webagg``, to turn off the header/title bar and get a tighter layout? (or is there already a way to do this?). In my mind it would look nicer to simply have:

<img width="710" alt="screen shot 2018-08-30 at 14 59 12" src="https://user-images.githubusercontent.com/314716/44873354-fa8cb580-ac65-11e8-84eb-496aefcc2527.png">

And for my use case I'm fine with losing access to the 'power' button to freeze the plot.

**Comment by tacaswell** [comment]
Would be good to cross post on jupyter-matplotlib.

**Comment by ImportanceOfBeingErnest** [comment]
You may get rid of the title bar via css:

```
%%html
<style> .output_wrapper .ui-dialog-titlebar { display: none; } </style>
```

![image](https://user-images.githubusercontent.com/23121882/44887048-833d3d00-acca-11e8-8b74-806ee7126639.png)

Of course one can still discuss if there should be an option to toggle the bar within matplotlib.

**Comment by astrofrog** [comment]
@ImportanceOfBeingErnest - thanks, good to know! In my case I would still need to do that without requiring users to modify the CSS. I think the cleanest way to do this may be to have an rcParam called e.g. ``webagg.titlebar`` that could be set to ``False``?

**Comment by oscargus** [comment]
Related: #6896

**Comment by raphaelquast** [comment]
Just putting this here for future reference since the issue title also mentions `webagg`.

When using pure `webagg` (not in Jupyter Notebooks), adding the following lines to the css does the job:

```html
<style type="text/css">
    div.ui-dialog-titlebar {
        display:none;
      }
</style>
```
