### ISSUE TITLE
Controlling whitespace margins from x-label to figure edge for pgf

### ISSUE THREAD

**Issue by JacobEFO** [matplotlib/matplotlib#11987]
Hello you guys. I am currently making all my plots with Matplotlib (which is awesome). These plots are exported as pgf using the rcparams update and inserted into LaTeX with \input{pgffile.pgf}, the results are in general awesome, even though I have som issues with figure to caption whitespace.

### Bug report
I get excessive whitespace between my actual figure and the whitespace.

See for instance this picture: https://imgur.com/a/98bqKVh

**Code for reproduction**

```python
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
width = 3.74
height = 3.2

pgf_with_latex = {
    "pgf.texsystem": "pdflatex",         # use Xelatex which is TTF font aware
    "text.usetex": True,                # use LaTeX to write all text
    "font.family": "serif",             # use serif rather than sans-serif
    "font.serif": "Times New Roman",             # use 'Ubuntu' as the standard font
    "font.sans-serif": [],
    "font.monospace": "Ubuntu Mono",    # use Ubuntu mono if we have mono
    "axes.labelsize": 12,               # LaTeX default is 10pt font.
    "font.size": 12,
    "legend.fontsize": 12,               # Make the legend/label fonts a little smaller
    "xtick.labelsize": 12,
    "ytick.labelsize": 12,
    "pgf.rcfonts": False,               # Use pgf.preamble, ignore standard Matplotlib RC
    "text.latex.unicode": True,
    "pgf.preamble": [
     r"\usepackage{amsmath}",
     ]
}

mpl.rcParams.update(pgf_with_latex)
lw = 1.3
from matplotlib import rcParams
rcParams.update({'figure.autolayout': True})

t = np.arange(1,10,0.1)
f1 = plt.figure(figsize = (width,height))
plt.plot(t, t*t)
plt.ylabel('Value')
plt.xlabel('Time')
plt.savefig('dummy.pgf')
plt.show
```

The output is here (same picture as above): https://imgur.com/a/98bqKVh

I suppose the outcome is as expected, I would like to know how I can remove the excess whitespace from the xlabel to the figure edge eliminating a lot of caption whitespace in LaTeX.

This issue can be solved in LaTeX itself using \vspace{}, but I would like to see if there is a solution for the actual plots itself.

**Matplotlib version**

  * Operating system: Mac OS X
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.4
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: 

Matplotlib was installed using conda with the default channel (I believe).

Best regards
Jacob

**Comment by JacobEFO** [comment]
Hi jklymak

Thanks for the quick reply, I didn't see it, so I apologize for my slow reply.
It seems it is matplotlib that does "some" excessive whitespace. See for instance what happens in the PDF: https://drive.google.com/open?id=1mzSneZHEm3_owJHqPjnVqpOaPscAA3Kn

(I didn't know how else to attach a pdf file here).

Also it's only the matplotlib generated files that experience excessive whitespace. Neither the tikzfigures or regular \includegraphics{} figures experience excessive whitespace.

**Comment by jklymak** [comment]
Did you try

```
plt.savefig('dummy.pgf', bbox_inches='tight')
```

**Comment by JacobEFO** [comment]
Yes, but with this however.

`
from matplotlib import rcParams
rcParams.update({'figure.autolayout': True})
`

Either results in the following

`/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py:2022: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "`

**Comment by jklymak** [comment]
With the example above or something more complicated?   You can also try constrained_layout.

**Comment by JacobEFO** [comment]
With the case above. Isn't constrained_layout exclusively for subplots?

Seems like it gives me errors when I actually try to use it.
