### ISSUE TITLE
mpl3.0.0rc2 - missing function: matplotlib.cbook.is_string_like

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#12008]
### Bug report

**Some previous features have been removed in 3.0.0rc2**

**Code for reproduction**

```python
from matplotlib.cbook import is_string_like
```

**Actual outcome**

```
ImportError: cannot import name 'is_string_like' from 'matplotlib.cbook'
```

**Expected outcome**

Expected ... function is loaded, as of Version 2.2.3

**Matplotlib version**

  * Operating system: Fedora 28
  * Matplotlib version: 3.0.0rc2 
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: 3.7.0
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

```shell
pip install --upgrade --pre matplotlib
```

**Comment by QuLogic** [comment]
Yes, `is_string_like` was [deprecated in 2.1](https://matplotlib.org/api/cbook_api.html#matplotlib.cbook.is_string_like) and many [deprecated functions have been removed](https://matplotlib.org/devdocs/api/api_changes.html#removal-of-deprecated-apis). This result is expected.
