### ISSUE TITLE
matplotlib.pyplot.imread occasionally takes longer time

### ISSUE THREAD

**Issue by betterze** [matplotlib/matplotlib#12002]
### Bug report

**Bug summary**

Even for exactly the same code, imread takes very different time. 

**Code for reproduction**

```python
    mtime=0
    for i in range(num_of_imgs):
        img_id=img_ids[i]
        class_id=class_ids[i]
        
        start=time.time()
        img= plt.imread(file_path+'train/'+img_id)
        end=time.time()
        
        if end-start>mtime:
            mtime=end-start
            print(img_id,end-start)
            
            start=time.time()
            img= plt.imread(file_path+'train/'+img_id)
            end=time.time()
            print(end-start)
```

**Actual outcome**

```
000011e9b72d9066d9a64c326bfef62e.jpeg 0.10991501808166504
0.0005021095275878906
06c6cd0763de47268dc19c17feb0a34c.jpeg 0.2879338264465332
0.0005652904510498047
071fe84267306ab20a10aff5b07161a1.jpeg 1.1599855422973633
0.0005271434783935547
0722c470336beac76c82672fa9c24448.jpeg 1.412771463394165
0.0005052089691162109
07342c52470114f7b2651457d96f705c.jpeg 1.460874080657959
0.0004673004150390625
0734d926f168e4f9b0c6ff293447d73f.jpeg 2.249683141708374
0.0005409717559814453
```

**Expected outcome**
The run time for imread the same image (the same code) should be very similar. But as you can see from the result, they are very different.

**Matplotlib version** 

  * Operating system: linux 
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
The variation between the first and second read of the same file is likely due to your OS already having the bytes of the file cached in memory. 

Similarly I suspect the variation in the initial read time is due to the I/O performance of your disk system.  If you use `open(..., mode='b').read()` you will see the same issues.

**Comment by betterze** [comment]
Get it. Thank you for your help.
