### ISSUE TITLE
bar chart axis formatting issue when dates are used

### ISSUE THREAD

**Issue by bmironov** [matplotlib/matplotlib#12014]
### Bug report

**Bug summary**

I use pandas to plot DateFrame and it works properly for line-type charts. When I change type chart in my call for "bar" X axis formatter behaves differently

**Code for reproduction**

Below are cells and their output as I see it in Jupyter 5.6.0 interface

```python
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib

pd.show_versions()
```

```python
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

```python
data = pd.DataFrame({"timestamp": pd.period_range('2018-08-22', freq='D', periods=8),
                     "value": [0.078419,0.078617,0.074033,0.073842,0.070815,0.068357,0.069577,0.068752]}) \
    .set_index('timestamp')

data['value'].plot.bar(color='dodgerblue', rot=90)
plt.show();
```

![image](https://user-images.githubusercontent.com/171609/45065041-1ab4de00-b085-11e8-9834-4aad7823fd0d.png)

```python
data['value'].plot.line(color='dodgerblue', rot=0)
plt.show();
```

![image](https://user-images.githubusercontent.com/171609/45065057-299b9080-b085-11e8-8aa9-34aee4964196.png)

```python
print(matplotlib.get_backend())
```

```python
module://ipykernel.pylab.backend_inline
```
**Expected outcome**

Please take a look at provided charts. I expect to see same format of axis X as minimum. Formatter from "line"-type chart is preferred one.

**Matplotlib version**
  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)]
  * Jupyter version (if applicable): 5.6.0
  * Other libraries: 

I used pip to install everything in my environment

I also opened pandas Github issue for this behaviour: https://github.com/pandas-dev/pandas/issues/22594

**Comment by jklymak** [comment]
Thats what bar plots do for you -label each bar.  Maybe you want `hist` or `step`?

**Comment by bmironov** [comment]
@jklymak Thank you for quick reply.

Sorry if I misunderstand the concept here. As in Excel, I can easily flip data presentation from line chart to bar chart. My understanding is that line and bar charts are same kind of "animals". "hist" is different because it processes my data to show distribution instead of simple series, like "line" does. "step" is not available via pandas, at least now.

If my assumption about similarities of bar and line charts is correct, then why do they behave differently in formatting tick values? Essentially they both show exact same labels with different formatting and no extra processing is done (like "hist") to have different formatter.

Thanks

**Comment by timhoffm** [comment]
Bar and line-charts are different concerning axes labelling. By definition the bars are equidistant and there is a label below each bar (or group of bars). However, the axis is ordinal and does not have a direction or scale. You could as well use labels A, B, C, ... or A, C, B, ..

In contrast, the axis in a line plot does have a direction and scale. The labels are attached to that scale. In general, they do not align with data points.

You can construct a dataset with equidistant data points in which labels to bars and labels on a line plot can coincide. However, matplotlib uses totally different mechanisms to construct the respective axis. Therefore, the axes will still not be the same by default. You would have to enforce this manually by configuring explicitly how you would like the axis to look like.

**Comment by bmironov** [comment]
@timhoffm Thank you for this explanation. This means that "line" and "bar" are very different in nature in regards to X axis labelling. It would be great to have some sort of bar presentation that is equal to line in this regard as part of the library. It is common to present data as bar and line combination in our industry. For example, bars show actual values and line on top shows overall trend.

Feel free to close this issue or add to as wish list.

Best regards,
Boris

**Comment by ImportanceOfBeingErnest** [comment]
In **pandas**, bar plots are categorical in nature. Also, pandas provides different Formatters for different valued plots. To make a line plot with datetime index compatible with matplotlib datetime handling you may use the `x_compat=True` argument.  
In general, because this is not something matplotlib has control over, issues with that should be discussed at the pandas issue tracker. 

Concerning **matplotlib**, the situation is a bit clearer. Both, line plots and bar plots, are numeric plots by default (unless you use strings as input). This means you should not run into a situation where a matplotlib bar plot (`plt.bar` or `ax.bar`) and a matplotlib line plot (`plt.plot` or `ax.plot`) give you anything different concerning units, ticks or labels. So from the matplotlib perspective the feature you are looking for is already the default.

```
import pandas as pd
import matplotlib.pyplot as plt

fig, (ax, ax2) = plt.subplots(nrows=2, sharex=True, sharey=True)
data = pd.DataFrame({"timestamp": pd.date_range('2018-08-22', freq='D', periods=8),
                     "value": [0.078419,0.078617,0.074033,0.073842,0.070815,0.068357,0.069577,0.068752]}) \
    .set_index('timestamp')

ax.plot(data.index, data.value)
ax.tick_params(axis="x", labelbottom=True, rotation=45)

ax2.bar(data.index, data.value)
ax2.tick_params(axis="x", labelbottom=True, rotation=45)

plt.setp(ax.get_xticklabels()+ax2.get_xticklabels(), ha="right")
fig.tight_layout()
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/45094339-4682a300-b11b-11e8-91c2-d46625a5f244.png)
