### ISSUE TITLE
NavigationToolbar2QT zoom cursor uses up memory without release

### ISSUE THREAD

**Issue by Bibushka** [matplotlib/matplotlib#12041]
When using the "zoom" button from a Navigation toolbar, when clicking and not releasing the mouse button and just playing with it on the figure, the memory usage (monitored in Windows Task Manager) shoots up by hundreds of MB, even GB, and doesn't come back down.  gc.collect() doesnt clear memory.

What is using this memory and how can it be freed? 

```
from PySide2 import QtCore, QtWidgets
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT
from matplotlib.figure import Figure
import sys

class Ui_main_window(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_main_window, self).__init__()
        self.setObjectName("main_window")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.chart_canvas = MyCanvas(self.centralwidget, width=6, height=3, dpi=100)
        self.gridLayout.addWidget(self.chart_canvas, 3, 0, 2, 6)
        self.toolbar = NavigationToolbar2QT(self.chart_canvas, self.centralwidget)
        self.toolbar.update()
        self.gridLayout.addWidget(self.toolbar, 2, 0, 1, 4)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 21))
        self.menubar.setObjectName("menubar")
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.show()

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Main Window"))


class MyCanvas(FigureCanvas):
    def __init__(self, parent=None, width=6, height=3, dpi=100):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = self.fig.add_subplot(111, frame_on=True)
        FigureCanvas.__init__(self, self.fig)
        self.setParent(parent)
        self.axes.cla()
        self.axes.plot([3, 1, 6, 3, 7, 8], [7, 3, 7, 3, 2, 1])
        self.draw()


app = QtWidgets.QApplication(sys.argv)
GUI_main_window = QtWidgets.QMainWindow()
main_window = Ui_main_window()
app.exec_()
```

I'm running it in Pycharm 2018 on Windows7, matplotlib vs 2.2.3

**Comment by jklymak** [comment]
Does this happen with a vanilla matpltolib window or only when embedded in an app?

**Comment by Bibushka** [comment]
I've tested it using this code but it doesn't spike the memory
https://matplotlib.org/gallery/pyplots/pyplot_two_subplots.html#sphx-glr-gallery-pyplots-pyplot-two-subplots-py

**Comment by tacaswell** [comment]
We have a work-around of a bug in pyside where we leak the image buffers we use to draw the widget see https://github.com/matplotlib/matplotlib/blob/1a40221e2651b465bdacce24e071d36951214ee0/lib/matplotlib/backends/backend_qt5agg.py#L65-L68

I wonder if the same bug happen is pyside2

Can your reproduce this if you use pyqt5 instead?

**Comment by Bibushka** [comment]
I've switched to PyQt5 and it doesn't seem to behave like this.

**Comment by Bibushka** [comment]
And i've tried the work-around and it doesn't fix the problem

**Comment by QuLogic** [comment]
This appears to specifically be about Qt4, which is now deprecated. I don't think we want to spend much time tracking this down.
