### ISSUE TITLE
LaTex x-small font stretching

### ISSUE THREAD

**Issue by MaxSchambach** [matplotlib/matplotlib#12056]
### Description

Using the LaTex text rendering, label fonts with sizes ``x-small`` are being stretched.

#### Details

Changing the font size to ``small`` results in correct font rendering, but I noticed that the ``small`` and ``x-small`` fonts use up the same amount of vertical space, so it seems like the font is just vertically stretched in the ``x-small`` case.
See the images below.

Output using font size ``x-small`` and PDF backend:
![plot_pdf_matplotlib_xsmall](https://user-images.githubusercontent.com/28300359/45219038-e706cd80-b2a9-11e8-9f6d-fdebc40efc98.jpeg)

Output using font size ``small`` and PDF backend:
![plot_pdf_matplotlib_small](https://user-images.githubusercontent.com/28300359/45219046-eb32eb00-b2a9-11e8-8448-35e51747ee1c.jpeg)

## Expected Output
Output using font size ``x-small`` and PGF backend rendered with pdflatex:
![plot_pgf_latex_xsmall](https://user-images.githubusercontent.com/28300359/45219050-ecfcae80-b2a9-11e8-8d7a-1aa08b9fe04c.jpeg)

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version:  2.2.2
  * Matplotlib backend: TkAgg / PDF / PGF
  * Python version: 3.6.6 (Anaconda Python)
  * Jupyter version: JupyterLab 0.34

**Comment by pharshalp** [comment]
can you post the code you used to generate these? Since you are mixing the native Matplotlib fontsize declarations with LaTex, it might not lead to correct results.

**Comment by MaxSchambach** [comment]
Thank you for the hint! Sorry, I didn't have time to create a simple MWE. I've tried setting the font sizes explicitly in pt, and that solved the problem. I thought internally, ``small`` ``x-small`` etc. would translate to LaTex's ``\small{}`` and ``\footnotesize{}`` font sizes which would be a nice feature. As for now, you would have to set all desired font sizes in pt manually.

**Comment by pharshalp** [comment]
If you look at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py it shows the following scaling values...

```python
font_scalings = {
    'xx-small' : 0.579,
    'x-small'  : 0.694,
    'small'    : 0.833,
    'medium'   : 1.0,
    'large'    : 1.200,
    'x-large'  : 1.440,
    'xx-large' : 1.728,
    'larger'   : 1.2,
    'smaller'  : 0.833,
    None       : 1.0}
```
My guess is, the LaTex font you are using only allows certain quantized font sizes. This might result in the same quantized fontsize corresponding to both 'small', 'x-small' scalings (I am not 100% sure if this is the correct  explanation).

**Comment by MaxSchambach** [comment]
I think you are right. So I guess, the only way for now to accomplish consistent font sizes to use within a LaTex document is to specify all the font sizes in pt directly. This is a little cumbersome but probably not a problem of Matplotlib but rather a task for an extra package.

**Comment by pharshalp** [comment]
> So I guess, the only way for now to accomplish consistent font sizes to use within a LaTex document is to specify all the font sizes in pt directly.

or you could use relative sizes i.e. \small{}, \large{} etc

**Comment by MaxSchambach** [comment]
But how would I specify that in Matplotlib? I have tried setting the fontsizes in the .rc file to ``\footnotesize{}`` etc. but the syntax does not work and I don't see anything in the font manger that points towards such an option.

**Comment by pharshalp** [comment]
```python
import numpy as np
import matplotlib.pyplot as plt

t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(4 * np.pi * t) + 2

plt.rc('text', usetex=True)
plt.rc('text.latex', preamble=r'\usepackage{fourier}, \usepackage[T1]{fontenc}')
plt.plot(t, s)

plt.xlabel(r'{\Huge{Huge}}, Normal, {\tiny{tiny}}')
plt.ylabel(r'{\Huge{Huge}}, Normal, {\tiny{tiny}}')
plt.tight_layout()
plt.savefig('tex_demo.png')
```
![tex_demo](https://user-images.githubusercontent.com/15175620/45322426-33eedc00-b516-11e8-9f30-8d718c07e540.png)

**Comment by jklymak** [comment]
Fixed to documentation or code most welcome. It does seem that xsmall and xxsmall should give different font sizes.

**Comment by pharshalp** [comment]
I will take this up over the weekend and try to document this (in addition to #11586 related to the use of TeX. I did start a PR #11718 but couldn't follow through).

**Comment by voidstarstar** [comment]
I think this is actually caused by the "optical sizes" of a font (sometimes found in OpenType variable fonts).  When you zoom in on certain small pt sized fonts, they will look distorted, but from the normal intended zoom level it is more appealing to the human eye.  This is tricky to track down due to the subtlety, but once you know what to look for, it's easy to find resources explaining it (e.g. [link](https://tex.stackexchange.com/a/328237), [link](https://tex.stackexchange.com/q/18721), [link](https://fonts.google.com/knowledge/glossary/optical_size_axis), [link](https://www.typedesignclass.com/resources/optical-sizes-explained)).

Sorry for bumping a 5+ year old issue.  I figured this would be helpful for people that stumble across this issue in the future (like myself), to know that it's a feature and _not_ a bug in matplotlib or LaTeX.
