### ISSUE TITLE
Keyword *interpolation* behaving improperly while saving to SVG with **savefig()**

### ISSUE THREAD

**Issue by dabana** [matplotlib/matplotlib#12065]
### Bug report

**Bug summary**

When saving an interpolated rbga image to SVG format, the output depends whether the keyword *interpolation* as been omitted or it has been put to *none* (*interpolation="none"*). This should not be the case. It should produce an UN-interpolated image in both case. We do not see this behavior with the other formats, PNG for instance.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

fig, (axl, axr) = plt.subplots(1, 2)
# full green image
img = np.zeros((5, 5, 4))
img[...,1] = np.ones((5, 5))
# transparent above main diagonal
img[...,3] = np.tril(np.ones((5, 5), dtype=np.uint8))

axl.set_title('with keyword\ninterpolation="none"')
axr.set_title('WITHOUT keyword\ninterpolation')
axl.imshow(img, interpolation="none")
axr.imshow(img)

plt.savefig('interp_alpha_svg.svg')
plt.savefig('interp_alpha_png.png')
```

**Actual outcome**

Github does not support SVG so here is my description. The left image, with *interpolation="none"*, looks interpolated (smoothed edges), but the right image, WITHOUT the *interpolation* keyword, has sharp edges.

**Expected outcome**

This is the output you get when *format* is PNG.

![interp_alpha_png](https://user-images.githubusercontent.com/29574757/45240817-fab93080-b2b7-11e8-9da4-8e86138eff45.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04 Bash on Windows10
  * Matplotlib version: 3.0.0rc1.post186+g5e01393
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.5.2
  * Jupyter version (if applicable):
  * Other libraries: 
matplotlib installed from source

**Comment by anntzer** [comment]
I think this is basically an instance of https://github.com/matplotlib/matplotlib/issues/10112: the uniniterpolated image is stored as a big 5x5 image and svg renderers interpolate it by default; the non-interpolated image is upsampled (in nearest mode) to a much larger number of pixels.

**Comment by dabana** [comment]
Okai so if I understand correctly, if we want to fix this issue we need to make sure that a large UPsampled image gets sent to the SVG renderer with *interpolation="none"* as well as WITHOUT the *interpolation* keyword (which is already the case).

**Comment by anntzer** [comment]
No, we want to tell the svg renderer not to perform resampling itself, as explained in #10112.

**Comment by anntzer** [comment]
Good point, that I don't know...

**Comment by dabana** [comment]
IF "specifying *interpolation=none*" and "omitting *interpolation*" behaving differently IS the intended behavior

THEN, oh well... close this issue...

OTHERWISE, we should make sure that an UNsampled images gets sent to the SVG renderer with interpolation="none" (which is already the case) as well as WITHOUT the interpolation keyword. That way the SVG render takes care of doing whatever he wants.

**Comment by dabana** [comment]
I vote for B

**Comment by ImportanceOfBeingErnest** [comment]
Just that we know what the issue is, here is the output of the code when the svg is opened in inkscape 0.91:

![image](https://user-images.githubusercontent.com/23121882/45245730-f1eb4d80-b2fd-11e8-88c3-67be09af10f7.png)

(Maybe worth noting that inkscape 0.49 shows no difference between the two subplots)

**Comment by ImportanceOfBeingErnest** [comment]
Equally worth noting that there is a difference between `None` and `"none"`

![image](https://user-images.githubusercontent.com/23121882/45245954-01b76180-b2ff-11e8-9f14-d91c208183ef.png)

**Comment by dabana** [comment]
From the **imshow()** documentation:

>**interpolation** : string, optional, default: None
>Acceptable values are 'none', 'nearest', 'bilinear', 'bicubic', 'spline16', 'spline36', 'hanning', 'hamming', 'hermite', 'kaiser', 'quadric', 'catrom', 'gaussian', 'bessel', 'mitchell', 'sinc', 'lanczos'

>If `interpolation` is None, default to rc `image.interpolation`. See also the `filternorm` and `filterrad` parameters. If interpolation is 'none', then no interpolation is performed on the Agg, ps and pdf backends. Other backends will fall back to 'nearest'.

So it IS the intended behavior. In the doc, should we specify:
1) that the SVG backend will not perform any interpolation either
2) that rc `image.interpolation` is the same as 'nearest'
3) that SVG renders (such as browsers) might perform interpolation on SVG images.

**Comment by timhoffm** [comment]
The docstring has already changed a bit in the current master: 
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.imshow.htm

Issue 2 is already handled. 1 an 3 remain open. You are welcome to provide a PR to clarify the SVG handling.
