### ISSUE TITLE
'matplotlib' has no attribute 'cm' when deploying an app

### ISSUE THREAD

**Issue by renanxcortes** [matplotlib/matplotlib#12075]
I'm trying to deploy an app developed using Dash which use some matplotlib functions. When I run locally the application, it runs smoothly and everything is okay, however, when I deploy it using the same code (I'm deploying using heroku) the matplotlib version that is installed (which is the current 2.2.3) no longer find the attrbute 'cm' to create a colormap.

```python
import matplotlib
cmap = matplotlib.cm.get_cmap('Reds')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/22593188/45276820-61397c80-b479-11e8-9253-033c0466e3c5.png)

**Matplotlib version**

I'm using Windows 10, with matplotlib 2.2.3 locally and in the deploy and, locally, my Python version is 3.6.6.

Thank you!

Kind regards,
Renan

**Comment by jklymak** [comment]
This doesn’t look like a matplotlib bug to me.  This’d be better discussed in the mailing list or stackoverflow unless there is a particular bug you can isolate.  Thanks!

**Comment by tacaswell** [comment]
I suspect you just need to do `import matplotlib.cm`

**Comment by yifan123** [comment]
> I suspect you just need to do `import matplotlib.cm`

Amazing! it did work!
