### ISSUE TITLE
PySide2 memory leak during canvas paintEvent

### ISSUE THREAD

**Issue by simon-kraeusel** [matplotlib/matplotlib#12089]
### Bug report

A memory leak occurs during every frame draw when PySide2 is used with Python3. This issue was already fixed for PySide in the method `matplotlib.backends.backend_qt5agg.FigureCanvasQtAgg.paintEvent`
However, an additional check for `QT_API == 'PySide2'` is needed.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
plt.plot([1,2],[1,2])
plt.show()
```

**Actual outcome**

When a redraw of the figurecanvas is forced, the program memory increases steadily. For example during resizing the popup window.

**Expected outcome**

Constant memory during ui execution. 

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7

all packages are pip installed

**Comment by simon-kraeusel** [comment]
The fix to this issue is:

``` Python
if QT_API in ('PySide', 'PySide2') and six.PY3:
    ctypes.c_long.from_address(id(buf)).value = 1
```
to be inserted into 
`matplotlib.backends.backend_qt5agg.FigureCanvasQtAgg.paintEvent`

I am new to github so don't know how to create a branch/commit/pull request sensibly. I will look into it and try to commit this fix.

**Comment by dabana** [comment]
@simon-kraeusel checkout the [matplotlib developper guide](https://matplotlib.org/devel/contributing.html) for a step by step guide how to contribute.

**Comment by simon-kraeusel** [comment]
@dabana Thank you. I sort of managed to get the fix into a merge request. However, I will have a closer look at the developer-guide in order to do it properly next time. Cheers.
