### ISSUE TITLE
Broken doc build with sphinx 1.8

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#12108]
The doc CI is broken with sphinx 1.8.

Matplotlib currently defines its own :math: role (based on mathtext rendering + png embedding), but this triggers a warning (fatal on CI for us) with sphinx 1.8 because sphinx now provides its own :math: role by default.

I removed that definition in #11928, but that doesn't actually help, because ours is slightly different: the mathtext tutorial uses the construct
```
.. role:: math-stix(math)
   :fontset: stix
```
to later be able to use `math-stix` meaning "render with that fontset, and this causes an error with sphinx 1.8's own math role).
    
I think the long-term solution is to move the mathtext tutorial to use *plots* to display the relevant samples, or to move matplotlib's own :math: role to something like :mplmath:, but in the mean time I can live with a warning about duplicate roles in sphinx's startup.

In the meantime we should just pin sphinx<1.8 and restore our own math role.  At least fixing doc-requirements.txt would be nice for 3.0.

**Comment by tacaswell** [comment]
Fixed by #12109 / https://github.com/matplotlib/matplotlib/pull/12110
