### ISSUE TITLE
document where to get nightly wheels

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#12100]
We need to document that nightly.matplotlib.org exists and has nightly builds of many packages from the scipy ecosystem.

**Comment by tacaswell** [comment]
and how to install them

**Comment by tacaswell** [comment]
not sure, but they can probably be changed to.

**Comment by anntzer** [comment]
Hmm, any reason why there are no post-3.0 nightlies there?

**Comment by tacaswell** [comment]
Duplicate of https://github.com/matplotlib/matplotlib/issues/9994
