### ISSUE TITLE
plotting contours from a three column array

### ISSUE THREAD

**Issue by mahtaparsa** [matplotlib/matplotlib#12103]
Hi,
I have a three column array, contains two parameters which are the x and y axes, and the Chi-square of these two parameters. I should make a meshgrid of these two parameters and then plot 1-sigma, 2-sigma, and 3-sigma contours, considering the Chi-square values. How can I do it in matplotlib?

**Comment by jklymak** [comment]
This is not a bug report.  Please use the mailing list or stackexchange for user help
