### ISSUE TITLE
pypi wheels for 2.2.3 claim to require numpy 1.7, but really require numpy 1.10

### ISSUE THREAD

**Issue by eferreira** [matplotlib/matplotlib#12119]
### Bug report

**Bug summary**

It seems like the wheels on pypi for matplotlib 2.2.3 were built against numpy 1.10, even though they are telling pip that they only need 1.7. And I believe the intention was for matplotlib 2.2.3 to still support numpy 1.7 (correct me if I'm wrong).

**Code for reproduction**

On a fresh python installation:
```
$ pip install numpy==1.9.1  # installs numpy-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl from pypi
$ pip install matplotlib==2.2.3  # installs matplotlib-2.2.3-cp27-cp27mu-manylinux1_x86_64.whl from pypi
$ python -c "import matplotlib.pyplot"
```

**Actual outcome**

(filepaths clipped)
```
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "{venv path}/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "{venv path}/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "{venv path}/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "{venv path}/lib/python2.7/site-packages/matplotlib/path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: numpy.core.multiarray failed to import
```

**Expected outcome**

Doing a pip install of matplotlib 2.2.3 in a virtual env that has numpy 1.9.1 should work.

**Matplotlib version**

See the wheel names mentioned above. I also reproduced this with the narrow unicode wheel ("m" instead of "mu") and I reproduced it on a Mac (I don't have the exact wheel that it used on hand at the moment).

Python and pip were installed with conda, using this command:
```
$ conda create -n mpl python=2.7 pip=9
```

**Comment by tacaswell** [comment]
This is likely due to crossed wires on multibuild.  Master has jumped to 1.10 (which is the oldest version of numpy that support py35), but the 2.2.x wheels should still be built against 1.7.1.

attn @matthew-brett

**Comment by matthew-brett** [comment]
Sorry - do you mean - these dependencies should be changed in matplotlib-wheels?

**Comment by eferreira** [comment]
For my part I'm hoping that the 2.2.3 wheels can be rebuilt against numpy 1.7.1 so that using pip to install matplotlib 2.2.3 along with numpy < 1.10 works smoothly.

**Comment by tacaswell** [comment]
See https://github.com/MacPython/matplotlib-wheels/pull/5

I think that is enough to fix the wheels, but I am more concerned about the process of replacing the wheel on pypi....

**Comment by tacaswell** [comment]
I am going to close this with no action as the next release (coming in the next few days) will be built with the correct version of numpy.
