### ISSUE TITLE
Scientific notation expressed in two terms

### ISSUE THREAD

**Issue by GrishaVar** [matplotlib/matplotlib#12111]
### Bug report

**Bug summary**

When plotting a line graph of points which are very close to one another, the scientific notation of the tick label is expressed in two terms.

**Code for reproduction**

```python
from decimal import Decimal
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
y = [Decimal('0.99999'), Decimal('1')]
ax.plot(y)
ax.ticklabel_format(axis='y', style='sci', scilimits=(-5, 5))
fig.show()
```

**Actual outcome**

Tick label value is 1e-5+9.9999e-1

**Expected outcome**

Tick label value is 1e-5 or something similar

**Matplotlib version**
  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.2.2
  * Matplotlib backend: TkAgg
  * Python version: 3.6.4
  * Decimal version: 1.70

python installed via pyenv, matplotlib via pip

**Comment by jklymak** [comment]
Can you try w/o Decimal?

**Comment by GrishaVar** [comment]
Issue persists with floats.

**Comment by jklymak** [comment]
I think you are just looking at the offset.  You can turn that off.  You can probably also change its formatting 
https://stackoverflow.com/questions/9303728/matplotlib-yaxis-range-display-using-absolute-values-rather-than-offset-values

**Comment by GrishaVar** [comment]
This fixed the issue. Thank you.
