### ISSUE TITLE
Plot in JS Animation has larger margin than "normal" PNG plot

### ISSUE THREAD

**Issue by mgeier** [matplotlib/matplotlib#12115]
### Bug report

**Bug summary**

A few hours ago #12098 was merged, which left-aligns JS Animation plots and thereby fixes #11795.

This brought to light another little inconsistency between JS Animations and "normal" plots.
The PNG data in the JS Animation seems to have a larger white margin than normal plots.
Therefore, if I plot a normal plot and then a similar JS Animation, the plot in the JS Animation shows up a bit further right (because of the PNG margin).

**Code for reproduction**

I'm using the examples from https://splines.readthedocs.io/en/latest/bezier.html

**Actual outcome**

![grafik](https://user-images.githubusercontent.com/705404/45547484-3bb5c580-b821-11e8-9d56-1c992456a350.png)

**Expected outcome**

Ideally, the PNG data in the JS Animation should have the same white margin as "normal" PNG plots.

**Matplotlib version**
  * Operating system: Debian Linux
  * Matplotlib version: `master` (848d9fc56561c0b79440ffd7d40f4f2f2e98ded1 a.k.a. `3.0.0rc1.post275+g848d9fc56`)
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 3.6.6
  * Jupyter version: JupyterLab 0.35.0a0

**Comment by WeatherGod** [comment]
I suspect the issue is that notebooks by default trims excess whitespace
from static matplotlib figures. You don't want to do that in general for
animations because the amount of excess whitespace can change from frame to
frame.

**Comment by mgeier** [comment]
@WeatherGod Indeed, I just checked with `savefig('myplot.png')` and it has the same white margin as the plots in the JS Animation. I wasn't aware that Jupyter manipulates the plots that it gets from Matplotlib.

Any ideas how I could make this consistent?

Manually remove the margins from Matplotlib plots?
Tell Jupyter to keep the margins?

**Comment by mgeier** [comment]
Thanks @ImportanceOfBeingErnest, the suggested config setting for the `InlineBackend` works perfectly!

I still have to look into the `ipympl` backend some day ...
