### ISSUE TITLE
PDF renderer draws strange artifacts on '%' character in 1.1.1

### ISSUE THREAD

**Issue by eeaston** [matplotlib/matplotlib#1211]
Hi there, 
The following code: 

``` python
from matplotlib import use
use("pdf")
import matplotlib.pyplot as plt
plt.title("Is there a bug?%%")
plt.savefig("test.pdf")
plt.close
```

..produces a PDF with strange arrow artiacts overlaying the '%' characters.

This i a regression since 1.1.0. 

Matplotlib version: 1.1.1
Backend: PDF
Arch: x86_64
Python: 2.6.2

Thanks,
Edward

**Comment by shauvik** [comment]
mpl.rcParams['pdf.fonttype']=42 fixed it for me

From: http://stackoverflow.com/questions/14295647/why-do-vector-based-image-files-contain-damaged-characters
