### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.pyplot'

### ISSUE THREAD

**Issue by derelearnro** [matplotlib/matplotlib#12123]
I try to import matplotlib and it work well, but when I  `import matplotlib.pyplot as plt` it make error. My os is running in ubuntu17.10

`conda list`
# packages in environment at /home/user/miniconda3/envs/deeplearning:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.0                      117  
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_4    conda-forge
matplotlib                2.0.0               np112py36_3    conda-forge
mkl                       2019.0                      117  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.12.1           py36he24570b_1  
numpy-base                1.15.0           py36h3dfced4_0  
openssl                   1.0.2p               h470a237_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pip                       18.0                     py36_1    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
python                    3.6.2                         0  
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           2  
setuptools                40.2.0                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.18                        0  
tornado                   5.1              py36h470a237_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

Here other information about conda:

 conda info

     active environment : deeplearning
    active env location : /home/user/miniconda3/envs/deeplearning
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.5 Linux/4.13.0-46-generic ubuntu/17.10 glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Thanks for your interest in matpltolib.  This looks like an is talkathon problem. Please seek help at stackoverflow or on the mailing list.   Thanks!

**Comment by derelearnro** [comment]
I already solved it by install uninstall matplotlab: `pip uninstall matplotlab ` then install jupyter  `pip install jupyter` and reinstall matplotlib:  `pip install matplotlab` and it works well to me now. Thank you.

**Comment by ashishmishraiitb** [comment]
Getting this error when trying to install "pip install matplotlab".

ERROR: Could not find a version that satisfies the requirement matplotlab (from versions: none)
ERROR: No matching distribution found for matplotlab.

Any suggestions?

**Comment by ImportanceOfBeingErnest** [comment]
Please note that this project, as well as the package itself is called `matplotlib`, not `matplotlab`.

**Comment by geraldooi** [comment]
after uninstall matplotlib and install matplotlib again get `cannot import name 'rcParams' from 'matplotlib' (unknown location)`

**Comment by tacaswell** [comment]
@geraldooi Can you please post at https://discourse.matplotlib.org/c/community/install/13 including what system you are on and how you are trying to install Matplotlib.

**Comment by geraldooi** [comment]
I solve these error by

**Comment by geraldooi** [comment]
I solved these error by running `conda uninstall matplotlib` and `conda install -c conda-forge matplotlib` commands in cmd.
