### ISSUE TITLE
Documentation of TextArea's fontprops keyword argument is misleading

### ISSUE THREAD

**Issue by galenlynch** [matplotlib/matplotlib#12121]
The [documentaiton](https://matplotlib.org/api/offsetbox_api.html#matplotlib.offsetbox.TextArea) for `TextArea` strongly suggests that the keyword argument `fontprops` should be a `FontProperties` object. However, inspecting the [source code](https://matplotlib.org/_modules/matplotlib/offsetbox.html#TextArea) suggests that `fontprops` should instead be a dictionary of keyword arguments that will be passed to the `Text` object inside `TextArea`.

I propose rewording the documentation to make it clear that `fontprops` should be a dictionary of keyword arguments.

**Comment by ImportanceOfBeingErnest** [comment]
There are two options:

1. Update the documentation with what the code does. (easy)
2. Update the code such that it'll indeed also allow for `FontProperties` objects as input. Then update the documentation.

@galenlynch Any interest in making that change an submitting a pull request?

**Comment by galenlynch** [comment]
Sure, glad to make a PR with option 1.
