### ISSUE TITLE
Streamplot does not work for 29x29 grid

### ISSUE THREAD

**Issue by manandoshi** [matplotlib/matplotlib#12133]
Here's the related SO question: https://stackoverflow.com/questions/52352129/matplotlib-streamplot-error-for-a-specific-number-of-gridpoints

and a python notebook demonstrating the possible bug:  https://colab.research.google.com/drive/1Z5oylZaRww9xeUrlRWOnQWbwSlTRIE6c

**Comment by manandoshi** [comment]
I reproduced the error on 2.2.0 and 2.1.2

**Comment by dstansby** [comment]
Yep, I can reproduce on `2.2.3` which is the most recent release.

**Comment by dstansby** [comment]
This was fixed by #11455; I'll see if we can get it backported to the branch that will be released as the 2.2.x series.

**Comment by QuLogic** [comment]
That was not eventually backported, but is fixed in v3.0.0.
