### ISSUE TITLE
fix pdf docs

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#12146]
The latexpdf docs are not building cleanly again due to names with non-latin characters and a music note in the docs:

- Андрей Парамонов
- David Trémouilles
- \$♫\$

`make latexpdf` is enough to trigger this.

We either need to sort out how to convince pdflatex to play nice with unicode or to switch sphinx to using xetex (or one of the other modern ones?)

**Comment by tacaswell** [comment]
We may also want to revert af102661c which made the html less pretty, but makes the latex build.

**Comment by anntzer** [comment]
Something like
```
latex_engine = 'lualatex'  # or xelatex

latex_elements = {
    'babel': r'\usepackage{babel}',
    'fontpkg': r'\setmainfont{DejaVu Serif}',
}
```
in conf.py works on a minimal sphinx example.

For some reason I need to force the use of babel, I get an error with polyglossia (the default on lualatex/xelatex), dunno why, you may not need it.
If you don't set the font to DejaVu (for example), then you get the default (lmodern) which doesn't have coverage for cyrillic and music notes, so the docs do build but the missing characters are just gone.
As for the choice between lualatex and xelatex, in my experience xelatex is faster (not a negligible point for building mpl's docs I guess) but I think(?) lualatex is the more "official", actively developed successor to pdflatex.

**Comment by tacaswell** [comment]
:+1: just figured out half of this.

I am just going to push this fix to the docs branch.

**Comment by anntzer** [comment]
Closed by https://github.com/matplotlib/matplotlib/commit/5758fc8c7f1ca4f6eadf9744e597fc09c3700031
