### ISSUE TITLE
Problems of using sharex options with lines plots and colormesh with colorbar

### ISSUE THREAD

**Issue by billtau** [matplotlib/matplotlib#12161]
### Bug report

**Bug summary**
I am trying to make a plot with sharex options.  There are two subplots, one is just a line plot, and the other is made with pcolormesh, with a colorbar.  The use of the colorbar, however, totally messed up the position of the plot from pcolormesh. 

**Code for reproduction**

```python
# Paste your code here
#
#
import matplotlib.pyplot as plt
import numpy as np

plt.close('all')
fig,axes=plt.subplots(2,1,sharex=True)
ax = axes[0]
x = np.linspace(0, 100, 100)
ax.plot(x)

data = np.random.random((50, 100))
ax = axes[1]
plt2=ax.pcolormesh(data)
plt.colorbar(plt2)
plt.show()

```

**Actual outcome**
![with_cb](https://user-images.githubusercontent.com/14089622/45735396-579eda00-bc1a-11e8-910e-e99aa0346084.png)

**Expected outcome**
Something like the following, but with a colorbar on the right of the corresponding image. 
![without_cb](https://user-images.githubusercontent.com/14089622/45735478-916fe080-bc1a-11e8-8038-114c7dc6d307.png)

**Matplotlib version**
  * Operating system:  MacOSX
  * Matplotlib version:  2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

matplotlib was installed via Macport

**Comment by jklymak** [comment]
Constrained_layout=True also takes care of this without any hoops so long as you don’t mind the other layout things it does.

**Comment by jklymak** [comment]
Closing as this isn’t really a big but rather something that needs to be worked around.
