### ISSUE TITLE
https://matplotlib.org/users/beginner.html is outdated

### ISSUE THREAD

**Issue by marcelm** [matplotlib/matplotlib#12162]
There seems to be an outdated tutorial page online at https://matplotlib.org/users/beginner.html . It has the old “Matplotlib 2.0.0rc2 is available – Install the release candidate now!“ banner.

I guess it’s not reachable from the main page, but it comes up in Google results.

**Comment by QuLogic** [comment]
Duplicate of #9556 (and others.)
