### ISSUE TITLE
pip install v3.0.0 'failed with exit status 1181'

### ISSUE THREAD

**Issue by Yobmod** [matplotlib/matplotlib#12168]
### Bug report

**Bug summary**

Trying to pip install on windows 7, python 3.6.3: 

"LINK: fatal error LNK1181: cannot open input file 'png.lib'
error: command 'C:\program Files(x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' 
failed with exit status 1181

**Code for reproduction**

pip install matplotlib  # fails

pip install matplotlib==2.2.3  # works

**Comment by tacaswell** [comment]
@Yobmod Can you please try again?

**Comment by Yobmod** [comment]
Just retried, and it is now working for me. Thanks!

**Comment by tacaswell** [comment]
Great!

sorry about that, definitely my fault :sheep:
