### ISSUE TITLE
Violin plot inconsistency between list and numpy

### ISSUE THREAD

**Issue by RaphP** [matplotlib/matplotlib#12178]
### Bug report

When feeding the same data to violin plot in list or in numpy array, the result is not the same. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

data = [ [1, 2, 3] , [4, 5, 6] ]
data_np = np.array(data)

f, (ax1, ax2) = plt.subplots(2)

ax1.violinplot(data)
ax1.set_title('list')

ax2.set_title('numpy array')
ax2.violinplot(data_np) #Same data but in numpy

plt.show()

```

**Actual outcome**

![problem](https://user-images.githubusercontent.com/10462086/45803215-4bb62500-bcb9-11e8-86ab-36d9b28f5764.png)

**Expected outcome**
Both should be the same isn't it ?

Actually the [doc](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.violinplot.html#matplotlib.pyplot.violinplot) specify - in terms I didn't understood at first - that it will
"Make a violin plot for each column of dataset or each vector in sequence dataset. " 

It is more clear when looking at the [hist doc](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html), where one can read at the end

"Note that the ndarray form is transposed relative to the list form."

The difference between the two outcomes, I think, is the way of thinking at data : vectors in matrix or lists in list (which correspond to columns in array of row in array). 
I discussed with some collegues who are working with Matlab, and they do think the vector as base unit of the 2D matrix. For me the base unit is a row of a 2D array.  

In the function plot when plotting [ [1,2,3], [4,5,6]  ], we have 3 curves, so I thing it is the matrix/vector way of thinking that is predominant in matplotlib. 
So should we change the violinplot and histogram behavior for list to work the same as array ?

After writing this I do belive that the best solution is to just mention that specificity more clearly in the doc of violinplot, not changing the code. I can do this, but I would like some feedback from differents points of view before.

Best,
RP

**Comment by anntzer** [comment]
See also https://github.com/matplotlib/matplotlib/issues/8092 for the same issue with boxplots.  (I agree that the behavior is... awkward.)

**Comment by jklymak** [comment]
I personally think this difference shouldn’t have happened.  I think we should change hist and violinplot to be consistent with plot which if I recall correctly is each data set is in a row and the time increases as you move across columns.  

However I suspect this change came in a long time ago so I’m not sure how easy it would be to change without breaking a lot of downstream code.   Certainly it should be explained better in the docstring.

**Comment by ImportanceOfBeingErnest** [comment]
This feels a bit like a deja-vu, but the main point is that you usually have data in columns. However, if you use datasets of different length they cannot be stored in a matrix, hence the option to use a list of (possibly unequal-length) datasets. 
 Concerning `plot`, it only ever plots columns, even if supplied as list of lists. That makes sense, because for plot you cannot have unequal-length datasets.

**Comment by jklymak** [comment]
Oops got it backwards in my post above.  

Ok it’s fair enough to say a list will each contain a distinct data set.  That’s really different than saying one is transposed from the other.  I appreciate that if you make a matrix from the list of lists it will be transposed, but that description misses the point.  A change to all the docstring s that use these dual conventions the way you nicely explain it above would be very helpful.  The current docstrings are far too inscrutable.

**Comment by nunocalaim** [comment]
See here also https://stackoverflow.com/questions/52987492/matplotlib-violin-plot-weird-input-requirement
