### ISSUE TITLE
Deprecate and remove pyplot.plotfile?

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#12180]
Currently the record array methods in the `mlab` module are deprecated, but `pyplot.plotfile()` still requires them and has not been deprecated. Does anyone have any objections to deprecating `pyplot.plotfile()`, and supplying users with alternative options for reading in files (e.g. numpy, pandas)?

**Comment by ImportanceOfBeingErnest** [comment]
I guess this makes sense. The key would be really to provide alternatives. I think people like the simplicity of reading the data and plotting it in one line seen from often used constructs like

     pandas.read_csv("fname").plot()

I've never seen someone using `pyplot.plotfile` though. I don't know where in the docs that would fit, but showing matplotlib options like

    plt.plot(*np.loadtxt("fname", unpack=True, usecols=(1,2)))

or 

    plt.plot("x", "y", data=pandas.read_csv("fname"))

might be helpful.

**Comment by WeatherGod** [comment]
The record array methods in mlab predates the numpy days. Why not just
update plotfile() to use the numpy functions?

**Comment by timhoffm** [comment]
+0.5 on deprecating `plotfile()`. It does too much. Parsing a file and plotting are separate concerns. While it may be convenient for a user, it's not reasonable from an API point of view. 

`pandas.read_csv("fname").plot()` does it right by chaining the different functionalities. The other two pyplot-based code snippets are reasonable as well. We could just add an example for "Plotting data from a file" to promote the alternatives.

The focus of matplotlib is plotting, not parsing data out of a file. The latter is a complicated topic itself and we should not bother too much about it ourselves.

That said, I don't mind if someone has strong  feelings about `plotfile()` and wants to take on the burden to port it to numpy.

**Comment by dstansby** [comment]
For now I have just made `csv2rec` a private method (well, added an underscore to its name), which is then used in `plotfile()`. If anyone else wants to replace it then feel free to open a new PR.

**Comment by rudrathegreat** [comment]
Another alternative to `matplotlib.pyplot.plotfile` is `matplotlib.pyplot.savefig` which allows you to save a figure (graph) into a folder. Simply - 

```Python

plt.savefig('Images/image.png')

```

## Requirements

> Python 3.7
>
> Matplotlib 2.2.3
>
>SciPy (if you want to save the data as an audio file)
>
> NumPy (recommendation, if you want speed)

I hope that helped!

**Comment by WeatherGod** [comment]
@rudrathegreat, uhm. I don't follow. `savefig()` is not an alternative to `plotfile()`. And I don't know why you included a requirements list there.

**Comment by jklymak** [comment]
@rudrathegreat Thanks so much for your interest in Matplotlib.  

When calibrating the kind of comments to post here, please note whether commenters are on the development team or not, as indicated by a "Member" badge in the heading of their posts.  Most folks who are on the development team are aware of somethig as basic as `fig.savefig`.

**Comment by rudrathegreat** [comment]
@jklymak and @WeatherGod . Thanks for letting me know. I thought the issue was realted to saving the graph. I love Matplotlib!

**Comment by anntzer** [comment]
Done in #13740.
