### ISSUE TITLE
axvline incorrectly tries to handle unitized ymin, ymax

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#12198]
After
```
line = plt.axvline(
    x=.5, ymin=matplotlib.dates.num2date(1), ymax=matplotlib.dates.num2date(1.05))
line.set_clip_on(False)
```
and panning the axes around, one sees that matplotlib (3.0) converted ymin and ymax to the scalar values 1 and 1.05, which is not correct: ymin and ymax are values relative to the axes bounds and thus intrinsically unitless; passing unitized data to ymin or ymax should result in an error.

The same point likely applies to axhline, axvspan, axhspan.

**Comment by jklymak** [comment]
This is still a bug...

**Comment by Worthy7** [comment]
![image](https://user-images.githubusercontent.com/4762399/62458715-9600a180-b7b8-11e9-99c9-9e3061506489.png)

**Comment by QuLogic** [comment]
I don't understand what panning has to do with this?

**Comment by anntzer** [comment]
it's just to show that 1 and 1.05 have been interpreted as dates, not unitless axes-coordinates values.

**Comment by QuLogic** [comment]
But they haven't, they were converted back to a numerical value of 1/1.05 (which is probably still wrong). Panning around, the line always stays above the Axes.

**Comment by anntzer** [comment]
Oops sorry, I guess I misremebered the example's behavior...  Well, backconversion to unitless values is also wrong :)
