### ISSUE TITLE
Show fails on figures created with the object-oriented system

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#1219]
The following code fails with a:

``` python
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'manager'
```

On all all gui backends that I have tested.  This seems to be because non of the canvases in any backends 
have a manager attribute which is requested in the show method of the figure at line 348 in figure.py. 

``` python
import matplotlib
matplotlib.use('gtkagg')
import matplotlib.backends as mbackends  # lazy import
from matplotlib.figure import Figure
fig = Figure()
ax = fig.add_subplot(1,1,1)
ax.plot(range(10))
fig.show()
```

**Comment by sleepyhollo** [comment]
I get the same error.

Using:
* Windows 10; 64 bit
* Python 3.7.3 (64 bit)
* Matplotlib 3.1.0
* Tkinter 8.6


Steps to replicate:
1. the sample code for embedding Matplotlib in Tkinter as described [here](https://matplotlib.org/3.1.0/gallery/user_interfaces/embedding_in_tk_sgskip.html), 
2. Moving or zoom the figure
3. After that, move the mouse on the figure
4. The console floods with `AttributeError: 'FigureCanvasTkAgg' object has no attribute 'manager'`.

**Comment by MichaMEG** [comment]
I get the same error.

Using: Debian 10 and 11 + normal python, python3-matplotlib, ... from Debian 10 and 11
I have now unfortunately not understood how to solve the problem!?
Could someone here explain to a poor troll what I need to change. Thank you very much ;)

**Comment by jklymak** [comment]
Please open a new issue that has a self-contained _minimal_ example (if the problem persists after you create the example).
