### ISSUE TITLE
"if 1:" blocks in examples

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#12191]
### Bug report

Some examples contain code in an `if 1:` block.

e.g. https://matplotlib.org/devdocs/gallery/axisartist/demo_axisline_style.html
or https://matplotlib.org/devdocs/gallery/event_handling/pick_event_demo.html

IMO this does not make sense and is rather confusing for the reader.

The condition should simply be removed for trivial cases, or replaced by functions if appropriate.

**Comment by abhinuvpitale** [comment]
I can do this, should I take it up? 
It should be replaced with '''__name__ == '__main__'''', right?

**Comment by timhoffm** [comment]
You are welcome to do this! :+1: 

Concerning, `__name__ == '__main__'` I don't think we have a strict policy here. As a rule of thumb, I would not add that if the example is more snippet-like.

E.g. for https://matplotlib.org/devdocs/gallery/axisartist/demo_axisline_style.html I would just remove the conditional and dedent.

OTOH, more program like examples such as https://matplotlib.org/devdocs/gallery/misc/demo_agg_filter.html?highlight=agg%20filter definitively call for `__name__ == '__main__'`.

**Comment by abhinuvpitale** [comment]
added the commits @timhoffm, please review!

**Comment by QuLogic** [comment]
Fixed by #12222.

**Comment by abhinuvpitale** [comment]
Let me add them, might take some time!

**Comment by QuLogic** [comment]
Now complete with #12260.
