### ISSUE TITLE
issues clearing rubberband on nbagg at non-default browser zoom

### ISSUE THREAD

**Issue by DTicien** [matplotlib/matplotlib#12201]
### Bug report

**Bug summary**

When trying to zoom in or out while in %matplotlib notebook mode, part of the "zoom rectangle" remains at the bottom and the right part of the axis.
The result is an axis crowded with remains of this rectangle and not readable anymore.

**Code for reproduction**

import matplotlib.pyplot as plt
%matplotlib notebook

plt.figure()
plt.plot(0,0)
plt.show()

**Actual outcome**

![capture du 2018-09-21 15-46-47](https://user-images.githubusercontent.com/36225851/45885211-20653000-bdb6-11e8-8385-be636f828605.png)

**Expected outcome**
Same but without the rectangle "glitch"

**Matplotlib version**

  * Operating system: Debian Stretch 
  * Matplotlib version: - matplotlib=2.2.3=py37hb69df0a_0
  * Matplotlib backend : nbAgg
  * Python version: 3.7.0
  * Jupyter version :
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.3=py37_0
  - jupyter_console=5.2.0=py37_1
  - jupyter_core=4.4.0=py37_0

Install with Conda - Default channels used

**Comment by tacaswell** [comment]
does re-sizing the plot force enough of a re-draw to fix it?

**Comment by DTicien** [comment]
Yes it does erase the rectangle when re-sizing.

**Comment by tacaswell** [comment]
Do you have the 'zoom' on your browser set to not 100%?

It looks like there is some confusion in the code as to how big your figure is.

The way nbagg works is we ship a png to the browser and wrap it in enough js to get the title bar and capture mouse/keyboard events.  We then pipe those events back to the python side, update the plot, and ship a png (diff) back to the browser to update what you see.  However, for performance reasons we use the js to draw the rubberband for the zoom box (we do this in all the backends, it help keep latency down).  What looks like is going wrong is that when the rubberband is released only some parts of the image are re-drawn from the png (browsers are very lazy about not updating pixels they don't have to).

**Comment by DTicien** [comment]
Issue fixed!
It was indeed the browser that was set to 90% and not 100%, that's the ratio we roughly observe on the screenshot.
Thanks for you help, that wasn't an obvious one...

**Comment by tacaswell** [comment]
I'm going to re-open this (and changed the title). Although we figured out a workaround for you, this is something that should be supported!

attn @SylvainCorlay I suspect that ipympl will have the same bug.

**Comment by SylvainCorlay** [comment]
@tacaswell thanks for the ping!

**Comment by Who8MyLunch** [comment]
I can't believe I found this!  I've had this exact issue for over year now and could not figure out what the problem was.  It was especially tricky since I had the same problem at work as at home with completely different setups.  home = Linux, chrome, and pip; whereas work = Windows 10, Firefox, and conda.  My co-workers thought I must be cursed.

It turns out the only common factor was my preference for a browser zoom setting of 90%.
