### ISSUE TITLE
Python will suddenly not plot anymore

### ISSUE THREAD

**Issue by heihaa** [matplotlib/matplotlib#12217]
Hi! I am experience a very strange behavior. As a student I've been using Spyder for my Python coding assignments. But some days ago I wanted to try out the Python environment in Visual Studio. So, I installed python environment in VS. But after that, none of even my simplest codes will produce any plots anymore. Even if I try the exact same code as I for sure know been showing a plot before. Initally I had a error message saying something like "mkl_aa_fw_init_workdivision...." + some more info and directory reference. So after some googling I deleted a mkl file in the directory witch was mentioned in the error message. After that there is no error message, but still no plot. If I try a simple test code like this:

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0,5,11)
y = x**2
plt.plot(x,y)

The only thing happening is Ipython console says "Kernel died, restarting". Also in Visual Studio, there is no plot coming up.I have no idea about the cause and how to fix it, even after hours of search and trial. Really frustrating to use time on this instead of my assignments. The only difference befor, when it was working, and after, is that I tried the Visual Studio environment. I highly appreciate help on this issue!
  * Matplotlib backend (`print(matplotlib.get_backend())`): :..
  * Python version: 2.7

**Comment by jklymak** [comment]
This is best followed up on the mailing list or stackoverflow.  It doesn’t sound like a matplotlib bug.  Thanks!

**Comment by ImportanceOfBeingErnest** [comment]
IDEs are sometimes shockingly complicated. However for student's assignments using a simple editor should be enough. Else Spyder is a good IDE, which is not too complicated, plus it's open source such that you will usually quickly find solutions to problems of usage. 
We cannot solve your particular problem here, but the general advice would be: (1) start simple (2) if something's not working, revert to the previously working solution. In this case it would mean to uninstall VisualStudio and potentially python as a whole.

If during your studies with matplotlib you find problems with the library itself or with its documentation, you may use this GitHub issue tracker to file a report about the problem. Good luck.

**Comment by heihaa** [comment]
I have now uninstalled both Anaconda and Visual Studio. Downloaded Anaconda again and installed. No fix, same issue still. The Complete error message is "mkl_blas_dgem2vu the startingpoint for the procedure was not in the library for dynamic connections c:\ProgramData\Anaconda2\Library\bin\mkl_intel_thread.dll". My problen is really, who shall I turn to for help?? I have absolutely no idea what sort of problem this is, and whom to turn to.

**Comment by WeatherGod** [comment]
mkl is an accelaration library, primarially used by numpy, but I doubt this
is a numpy issue. This seems more like an environment issue with
VisualStudio+Anaconda.

**Comment by ImportanceOfBeingErnest** [comment]
Related: 
https://github.com/ContinuumIO/anaconda-issues/issues/8327
https://github.com/ContinuumIO/anaconda-issues/issues/8561
https://stackoverflow.com/questions/51532576/entry-point-not-found-numpy-python

It's the kind of problem where you need to use google a lot and advance step by step trying different things. Eventually asking a question at Stackoverflow isn't a bad idea as it will be seen by a lot of people.

**Comment by heihaa** [comment]
Thank you so much for your help! The 8561 issue solved the problem for me. It was a recently installed music instrument interface program, Amplitube, on my PC that caused this. Just uninstall Amplitube and then all was fine again. Again, thank you, you saved my week!
