### ISSUE TITLE
In histogram, bars whose count is larger than 2**31 sometimes become negative

### ISSUE THREAD

**Issue by chuangy1** [matplotlib/matplotlib#12225]
### Bug report

**Bug summary**
When plot the histogram, some bars whose count is larger than 2**31 sometimes become negative under some unknown conditions.

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

![bug](https://user-images.githubusercontent.com/32028513/45923786-a4442700-bf32-11e8-8a63-d856363c078c.png)

**Expected outcome**
![normal](https://user-images.githubusercontent.com/32028513/45923788-b920ba80-bf32-11e8-869d-62f35c09a619.png)

**Matplotlib version**

  * Operating system: Windows 10 17134.286
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
Please provide a minimal example to reproduce the issue.

**Comment by tacaswell** [comment]
This looks like integer overflow, can your reproduce this with just `np.histogram`.

**Comment by chuangy1** [comment]
> Please provide a minimal example to reproduce the issue.

from matplotlib import pyplot as plt

l = [(359, 218641918), (360, 346814771), (361, 221783064), (362, 228103721), (363, 226773168), (364, 340432095),
     (365, 892706639), (366, 350615631), (367, 402126509), (368, 315962305), (369, 397399137), (370, 419634877)
     ]
l1, l2 = zip(*l)
l1 = [i + 0.1 for i in l1]
min_l1, max_l1 = min(l1) // 5 * 5, max(l1) // 5 * 5 + 5
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
bins = int((max_l1 - min_l1) / 5 + 0.1)
ax.hist(l1, weights=l2, range=(min_l1, max_l1), bins=bins)
plt.show()
plt.close()

**Comment by ImportanceOfBeingErnest** [comment]
`np.histogram` returns `[  218641918  1363906819 -2147483648   419634877]`, so it's definitely coming from `numpy`.

Using `weights=np.array(l2).astype(float)` solves the issue. 

Not sure in how far such integer overflows should be handled, or left for the user to avoid; but in any case it's probably for numpy to decide. I don't think matplotlib should deviate from what numpy does in such cases.
