### ISSUE TITLE
Init calls subclass method pattern

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#12220]
We have [a lot of places](https://lgtm.com/projects/g/matplotlib/matplotlib/alerts/?mode=list&rule=py%2Finit-calls-subclass) with the [init-calls-subclass pattern](https://lgtm.com/rules/10030085/). 

This cause problems if the subclass method relies on subclass attributes that have not yet been set up.

I actually ran into the issue in #12215.

- Has anyone encountered this before?
- Do we have a strategy how to avoid this issue?

**Comment by tacaswell** [comment]
I agree with @anntzer, many of the cases where we have this are using setters (you have the same problem with properties) that cause non-trivial internal state change.  We both want to override those things in sub-classes and to set up defaults in `__init__` (and to not have the state setting logic in 2x places) so I think we just have to absorb this complexity.

The advise to use composition is well meaning, but I don't think practical for us....

**Comment by timhoffm** [comment]
For setters/properties, it would be work to define the subclass attributes before calling the super init. 

Would that be a reasonable pattern?

**Comment by timhoffm** [comment]
Let's not follow up on this for now.
