### ISSUE TITLE
3d axes are collapsed by tight_layout

### ISSUE THREAD

**Issue by adeak** [matplotlib/matplotlib#12239]
Calling `fig.tight_layout()` on a figure with a 3d `Axes` inside will collapse the axes into a vertical line.

Minimal example:
```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

for tighten in False,True:
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot([1,2], [1,2], [1,2])
    if tighten:
        fig.tight_layout()

plt.show()
```
The following figures are produced with python 3.7, matplotlib 3.0.0 (also master):
![figure without tight_layout: all's fine](https://user-images.githubusercontent.com/17914410/45932469-be0a5c00-bf7c-11e8-9988-1bf55e10ced5.png?s=50)
![figure with tight_layout: axes is a single vertical line](https://user-images.githubusercontent.com/17914410/45932470-c19de300-bf7c-11e8-8368-52e12d0c48cc.png)

There's also a warning that says
`/home/user/matplotlib-env/lib/python3.7/site-packages/matplotlib/tight_layout.py:177: UserWarning: The left and right margins cannot be made large enough to accommodate all axes decorations.`
but that's hardly surprising since there's no room for any decorations whatsoever.

May or may not be related to the recent-ish issues fixed by https://github.com/matplotlib/matplotlib/pull/11739 and https://github.com/matplotlib/matplotlib/pull/11627.

**Comment by jklymak** [comment]
The right spines on this axis has a very large value of `x1` and is still marked as visible.  tight_layout now tries to use all artists, and this sporadic artist causes tight_layout to try to make room.  

Not sure where that axis position gets set.  Hopefully someone familiar with the 3d code can help.  I'd suggest it just get marked as not visible.

**Comment by jklymak** [comment]
I think #12241 fixes this without too many side effects.

**Comment by NHades** [comment]
This same issue is also present in 2D plots with fig.tight_layout().  My program uses matplotlib as back-end in PyQt4. 
I had to revert to 2.2.3 whihc fixed issue.

**Comment by jklymak** [comment]
@NHades  It's possible to create a plot that this is an issue, but note that most plots don't have a problem.  Can you open a new issue with a minimal example that triggers the axes collapse?   Also, please take a look at https://matplotlib.org/api/api_changes.html#matplotlib-axes-axes-get-tightbbox-now-includes-all-artists
