### ISSUE TITLE
set_xticks() needs argument for 'fontsize'

### ISSUE THREAD

**Issue by ulfaslak** [matplotlib/matplotlib#12318]
### Bug report

**Bug summary**

Unlike `plt.xticks` or `plt.yticks`, `ax.set_xticks` and `ax.set_yticks` has no argument `fontsize`. 
To change the fontsize of ticklabels in a subplot, the shortest workaround (to my knowledge) is:
```Python
for tick in ax.xaxis.get_majorticklabels():  # example for xaxis
    tick.set_fontsize(12) 
```
This feels too convoluted. It should not be more complicated than `ax.set_xticks(fontsize=12)`

**Code for reproduction**

```python
fig, ax = plt.subplots(1, 2, figsize=(10, 4))

ax[0].plot(range(10), [x**2 for x in range(10)])  # First subplot
ax[0].set_xticks(fontsize=10)                     # where I want fontsize 10 on xticks 

ax[1].plot(range(10), [x**3 for x in range(10)])  # Second subplot
ax[1].set_xticks(fontsize=12)                     # where I want fontsize 12 on xticks

plt.show()
```

**Actual outcome**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-561-19741a4fe5dc> in <module>()
      2 
      3 ax[0].plot(range(10), [x**2 for x in range(10)])  # First subplot
----> 4 ax[0].set_xticks(fontsize=10)                     # where I want fontsize 10 on xticks
      5 
      6 ax[1].plot(range(10), [x**3 for x in range(10)])  # Second subplot

TypeError: set_xticks() got an unexpected keyword argument 'fontsize'
```

**Expected outcome**

<img width="412" alt="screen shot 2018-09-28 at 10 31 45" src="https://user-images.githubusercontent.com/6390218/46197314-bd215380-c309-11e8-9986-e343985a371b.png">

**Matplotlib version**

  * Operating system: Mac OS 10.13.6
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 2.7
  * Jupyter version (if applicable): 4.4.0
  * Other libraries:

**Comment by timhoffm** [comment]
As written above, `set_xticks` sets only the positions and thus does not handle labelsize. Use `set_xticklabels` or `tick_params`.

**Comment by 1010337861** [comment]
赶紧加上fontsize 寻思啥呢 大兄弟

**Comment by kwyip** [comment]
a hack would be to add an argument of `labels` before `fontsize`.

`ax.set_xticks([1,4,5], labels=['1','4','5'], fontsize=100)`

Matplotlib version: 3.9.0
