### ISSUE TITLE
colorbar(boundaries=...) doesn't work so well with nonlinear norms

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#12312]
### Bug report

**Bug summary**

**Code for reproduction**

```python
from pylab import *
imshow(np.random.rand(100, 100), norm=mpl.colors.LogNorm())
colorbar(boundaries=[1e-4, 1e-3, 1e-2, 1])
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1322974/46166672-12bb1900-c294-11e8-977f-930538f82072.png)

**Expected outcome**

Either properly positioned boundaries, or (better) disallow passing boundaries in such cases.

Note that the docstrings in colorbar.py say
```
    The following will probably be useful only in the context of
    indexed colors (that is, when the mappable has norm=NoNorm()),
    or other unusual circumstances.

    ============   ===================================================
    Property       Description
    ============   ===================================================
    *boundaries*   None or a sequence
    *values*       None or a sequence which must be of length 1 less
                   than the sequence of *boundaries*. For each region
                   delimited by adjacent entries in *boundaries*, the
                   color mapped to the corresponding value in values
                   will be used.
    ============   ===================================================
```
but that still ends up part of the public API, which makes my intended fix for https://github.com/matplotlib/matplotlib/issues/7320 more difficult...

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
You get "properly" positionned ticks when in addition specfiying `spacing="proportional"`.

```
import matplotlib.pyplot as plt
import matplotlib.colors
import numpy as np

plt.imshow(np.random.rand(100, 100), norm=matplotlib.colors.LogNorm())
plt.colorbar(boundaries=[1e-4, 1e-3, 1e-2, 1], spacing="proportional")

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/46167316-c244bb00-c295-11e8-87e3-48f370bf620f.png)

**Comment by anntzer** [comment]
Thanks for pointing this out.  I don't think this should be an option, though... (it sound be the default and only behavior... no?)

**Comment by jklymak** [comment]
When overhauling colorbar I didn’t really look at boundary colorbars.  Maybe they need a similar overhaul

**Comment by jklymak** [comment]
Oops.  Didn’t see the above.  I’d be in favour of proportional=true as a default.

**Comment by ImportanceOfBeingErnest** [comment]
I would have though the "usual" (if you can speak of "usual" for something that declared "unusual") use case would be something like

```
import matplotlib.pyplot as plt
import matplotlib.colors
import numpy as np; np.random.seed(42)

data = np.random.choice([0,5,250], size=(12,12))
cmap = matplotlib.colors.ListedColormap(["crimson","gold","indigo"])
bounds = [0,1,10,1000]
norm = matplotlib.colors.BoundaryNorm(bounds, len(bounds)-1)

fig, axes = plt.subplots(ncols=2)

for ax, spacing in zip(axes, ["uniform", "proportional"]):

    ax.set_title("spacing="+spacing)
    im = ax.imshow(data, norm=norm, cmap=cmap)
    fig.colorbar(im, ax=ax, boundaries=bounds, values =[0,5,250], spacing=spacing, 
                 orientation="horizontal")

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/46178467-43f91080-c2b7-11e8-84e5-bc7fe09f201b.png)

Here the use of `"proportional"` is clearly undesired.

The consequence of such change is then the usual "My plot looks different, what can I do?". Hence my vote here would be: Don't break the API.

**Comment by anntzer** [comment]
As the docstring quote above says:
```
    The following will probably be useful only in the context of
    indexed colors (that is, when the mappable has norm=NoNorm()),
    or other unusual circumstances.
```
I guess we can add BoundaryNorm to the list of reasonable use cases.  But it would be nice if NoNorm and BoundaryNorm could somehow signal that they need this behavior to the colorbar machinery, rather than the user having to specify it.
