### ISSUE TITLE
AttributeError: module 'matplotlib.pyplot' has no attribute 'hold'

### ISSUE THREAD

**Issue by geatpy-dev** [matplotlib/matplotlib#12337]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# 
# matplotlib.pyplot.hold(True)
#
```

**Actual outcome**

```
# 
  Traceback (most recent call last):

  File "<ipython-input-5-e6c3cacc0f5d>", line 1, in <module>
    matplotlib.pyplot.hold(True)

  AttributeError: module 'matplotlib.pyplot' has no attribute 'hold'
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries: 

After updating matplotlib3.0.0, it occurs "AttributeError: module 'matplotlib.pyplot' has no attribute 'hold'"  **error** when I write "matplotlib.pyplot.hold(True)". It may be a big BUG of matplotlib!

**Comment by QuLogic** [comment]
The hold functionality was deprecated in 2.1, and [intentionally removed in 3.0](https://matplotlib.org/api/api_changes.html#hold-machinery).

**Comment by FarFromBoston** [comment]
Then how am i supposed to do this?
http://www.spectralpython.net/algorithms.html


![image](https://user-images.githubusercontent.com/25518651/59989997-d1ba2e80-9684-11e9-8a19-9f7c587da0e5.png)

**Comment by QuLogic** [comment]
First of all, don't use `pylab`; it is very outdated and not recommended. Second, just plot as usual; the default is `hold` being on.
