### ISSUE TITLE
Figures not rendering in docker

### ISSUE THREAD

**Issue by mattroos** [matplotlib/matplotlib#12341]
**Issue summary**
When using matplotlib in docker, the figures are never rendered. This issue may be related to #8929 and #11745. Other x11 apps work okay, e.g., xeyes.

**Code for reproduction**

```python
>>> import matplotlib
>>> matplotlib.use('agg')
>>> import matplotlib.pyplot as plt
>>> plt.ion()
>>> plt.plot(5,5)
[<matplotlib.lines.Line2D object at 0x7fd75bc64d50>]
```

**Actual outcome**
No figure is rendered.

**Matplotlib version**

  * Operating system: Ubuntu 14.04
  * Matplotlib version: 2.0.0
  * Matplotlib backend: agg
  * Python version: 2.7.6

python and matplot lib installed by pip.

**Comment by jklymak** [comment]
`matplotlib.use('agg')` means you are rendering to a non-GUI backend.  
https://matplotlib.org/tutorials/introductory/usage.html#backends

**Comment by mattroos** [comment]
Thanks!  It doesn't seem clear from that guide what the 'agg' backend really is, but in any case, the guide still helped me resolve the problem. Even without the matplotlib.use('agg'), it was defaulting to agg.  Creating a matplotlibrc file and setting the backend to TkAgg fixed the problem. Much appreciated!

**Comment by bryanperez43** [comment]
@mattroos how were you able to render the graph when running the docker image

**Comment by mattroos** [comment]
1. Start a [bash session](http://phase2.github.io/devtools/common-tasks/ssh-into-a-container/) in your running docker container.
2. Copy a sample template of the matplotlibrc file into ~/.configure/matplotlib/, found at the download link at this [site](https://matplotlib.org/users/customizing.html).
4. You might need to set the path evironment variable for bash. On the command line, execute:
```export MATPLOTLIBRC=~/.configure/matplotlib```
Or add that line to you ~/.bashrc file.
3. Edit the matplotlibrc file, editing the backend parameter as such: ``` backend : tkagg```

**Comment by FrankZh27** [comment]
Typo correction: the path should be ~/.config/matplotlib/matplotlibrc

**Comment by mayursawant** [comment]
In my backend it's already " tkagg " Still facing same problem   can you suggest any other way? 
@mattroos

**Comment by mattroos** [comment]
@mayursawant, sorry, no. I've been away from the relevant project for quite some time.

**Comment by mayursawant** [comment]
@mattroos  Can you send me the matplotlibrc file. I am unable to find it  . 
If possible please send it to

sawantmayur66@gmail.com

**Comment by mattroos** [comment]
@mayursawant, there are plenty of examples/templates available on the internet. Like this one.
https://gist.github.com/jsoma/9d7c2adf05f15685db9ac9e095722b51

**Comment by tacaswell** [comment]
Also see https://matplotlib.org/tutorials/introductory/customizing.html#a-sample-matplotlibrc-file

If you need more help @mayursawant please post on https://discourse.matplotlib.org
