### ISSUE TITLE
Error for bbox_inches='tight' in savefig with make_axes_locatable

### ISSUE THREAD

**Issue by jiaozhh** [matplotlib/matplotlib#12355]
### Bug report

**Bug summary**

When setting bbox_inches='tight' in savefig function, the colorbar is plotted in the wrong way. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.basemap import Basemap

outfile = r'E:\wrong.tif'

# read in data on lat/lon grid.
hgt = np.loadtxt(r'E:\tmp\basemap\500hgtdata.gz')
lons = np.loadtxt(r'E:\tmp\basemap\500hgtlons.gz')
lats = np.loadtxt(r'E:\tmp\basemap\500hgtlats.gz')
lons, lats = np.meshgrid(lons, lats)

mnh = Basemap(lon_0=-105, boundinglat=20.,
              resolution='c', area_thresh=10000., projection='nplaea')
xnh, ynh = mnh(lons, lats)
CS = mnh.contour(xnh, ynh, hgt, 15, linewidths=0.5, colors='k')
CS = mnh.contourf(xnh, ynh, hgt, 15, cmap=plt.cm.Spectral)

mnh.drawcoastlines(linewidth=0.5)
delat = 30.
circles = np.arange(0., 90., delat).tolist() + \
          np.arange(-delat, -90, -delat).tolist()
mnh.drawparallels(circles, labels=[1, 0, 0, 0])
delon = 45.
meridians = np.arange(0, 360, delon)
mnh.drawmeridians(meridians, labels=[1, 0, 0, 1])
plt.title('NH 500 hPa Height (cm.Spectral)')

# colorbar on bottom.
mnh.colorbar(pad='5%')
plt.savefig(outfile, dpi=300, bbox_inches='tight')  # wrong
# plt.savefig(outfile, dpi=300) # right
plt.show()
```

**Actual outcome**

The wrong one:
![default](https://user-images.githubusercontent.com/6754276/46267605-74b3a100-c568-11e8-8f52-72a38318b7ee.png)

```
# If applicable, paste the console output here
# None
#
```

**Expected outcome**

The correct figure:
![default](https://user-images.githubusercontent.com/6754276/46267594-68c7df00-c568-11e8-9d65-8a379ba1540e.png)

**Matplotlib version**

  * Operating system: Windows 10 x64
  * Matplotlib version:  3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: 3.6.6
  * Jupyter version (if applicable): None
  * basemap version: 1.2.0
  * PyCharm version: 2018.2.4 

I install matplotlib and basemap from https://www.lfd.uci.edu/~gohlke/pythonlibs.

**Comment by jklymak** [comment]
This should probably be reported in the base map subgroup.  Can you make this self contained?  

Things changed for drawing colorbars in MPL 3.0 and it’s possible we broke something for basemap, but it’s hard to know what.

**Comment by jiaozhh** [comment]
OK, I will report it in the basemap subgroup.

**Comment by jklymak** [comment]
OK I can reproduce in Matplotlib:

```python

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

fig, ax = plt.subplots()

pcm = ax.pcolormesh(np.random.random((32, 32)))
divider = make_axes_locatable(ax)
cax = divider.append_axes('bottom', size='5%', pad='2%')
cb = fig.colorbar(pcm,orientation='horizontal',cax=cax)
plt.savefig('boo.png', dpi=300, bbox_inches='tight')  # wrong
plt.show()
```
  - Note that its something wrong w/ the `bbox_inches='tight'` interaction - `plt.show()` and `plt.tight_layout()` work as expected.  
 - it doesn't matter if the colorbar is on the right or bottom of the page...

**Comment by jklymak** [comment]
Crossref https://github.com/matplotlib/basemap/issues/426

**Comment by jklymak** [comment]
Bisect says it was my PR: https://github.com/matplotlib/matplotlib/pull/9855

**Comment by jklymak** [comment]
This is quite a wild goose chase: #10682 also made this not work even if I roll back #9855 changes.
