### ISSUE TITLE
pdf image generated by matplotlib with semi transparent lines missing in Word on Windows.

### ISSUE THREAD

**Issue by Yefee** [matplotlib/matplotlib#12364]
### Bug report

**Bug summary**

The basic problem is I generated some pdf images with some semi-transparent patches (i.e. alpha=0.5) by Matplotlib on a Mac, then inserted it into Microsoft Word (still on Mac). The image in Word is identical as in pdf. However, when I open the Word file on a Windows machine, the semi-transparent patches are missing.

I searched a lot online, didn't find any relevant issues. Maybe it is due to the backend? or Due to Word?

**Matplotlib version**

  * Operating system: Mac OS 12.13
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6
  * Jupyter version (if applicable):None
  * Other libraries: None

I use conda-forge to install Matplotlib.

**Comment by jklymak** [comment]
Sorry, but I don't think we can help you with PDF conversion problems in Microsoft Word going between Mac and Windows.  Suggest looking at the original PDF on both machines and/or converting to a non-vector image format.
