### ISSUE TITLE
Create Arbitrary scale transforms

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12361]
So I was wondering if one could not provide the `_ArbitraryTransform` and the `ArbitraryScale` as a public object within `matplotlib.transforms` and `matplotlib.scale` respectively, possibly with an enhanced API for `.set_scale` to also allow for a single scale to be defined as a functional relation.

_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/11859#issuecomment-419597979_

**Comment by QuLogic** [comment]
I was going to ask the same thing, so since I think it probably was, I'll close this.
