### ISSUE TITLE
In 3.0.0 backend cannot be set if 'get_backend()' is run first

### ISSUE THREAD

**Issue by moonshoes87** [matplotlib/matplotlib#12362]
### Bug report

**Bug summary**

In my code, I need to check whether the matplotlib backend has already been set.  If it has not been set, I need to then set it to 'WXAgg'.  In matplotlib 2.*, I was able to do this, but in matplotlib 3.0.0 it fails.

**Code for reproduction**

```python
import matplotlib
if not matplotlib.get_backend() == 'WXAgg':
    matplotlib.use('WXAgg')
print('backend:', matplotlib.get_backend())
```

**Actual outcome**

With matplotlib 3.0.0:
```
/Users/nebula/Python/PmagPy/programs/test.py:7: UserWarning: matplotlib.pyplot as already been /Users/nebula/Python/PmagPy/programs/test.py:7: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  matplotlib.use('WXAgg')
backend: MacOSX
```

**Expected outcome**

With matplotlib 2.2.3:
```
backend: WXAgg
```

**Matplotlib version**

  * Operating system: OSX High Sierra 10.13.6
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6.6 (Anaconda, default channel)
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
I can't reproduce.  Are you doing this from inside an interactive shell?  Just running the above as a script I get the expected outcome on both master and v3.0.0

**Comment by moonshoes87** [comment]
The same result occurs when I run the code within the Python interpreter or as a script.

One difference is that if I run it as an executable:   `./test.py`  the backend is MacOSX, whereas if I run it as a python program: `python test.py`, the backend is Qt5Agg.  But in either case, I get the same user warning.

Here is the full matplotlib version info:

    matplotlib                3.0.0            py36h54f8f79_0

**Comment by ImportanceOfBeingErnest** [comment]
I can reproduce this with matplotlib 3.0.0

![image](https://user-images.githubusercontent.com/23121882/46319851-eaa52000-c5db-11e8-805d-4387e2b6c13c.png)

It's pretty strange that the warning complains about pyplot being imported without it being imported anywhere.

If using master, the problem does not occur.

![image](https://user-images.githubusercontent.com/23121882/46319920-42438b80-c5dc-11e8-8a16-f8085341d52c.png)

Here the `mpl300` environment has been completely created via conda, i.e. `conda create -n mpl300 matplotlib=3.0`. In both cases, `matplotlib.get_backend()` is `'Qt5Agg'`.

**Comment by anntzer** [comment]
Perhaps conda still ships a matplotlibrc with a backend: set?  dunno.

**Comment by ImportanceOfBeingErnest** [comment]
Ok let appart conda, how can it be that if you `import matplotlib` you get a warning about `pyplot` being imported? That should never happen, should it? 

So what's the purpose of this line?

https://github.com/matplotlib/matplotlib/blob/d5a4eda9cff9d6f9d8061f1f22598e0434d2d6eb/lib/matplotlib/__init__.py#L876-L880

**Comment by Kaushalya** [comment]
This line throws me the following error if I import matplotlib inside PyCharm.
`AttributeError: module 'matplotlib.pyplot' has no attribute 'switch_backend'`
Works fine on the interpreter.

**Comment by ImportanceOfBeingErnest** [comment]
Given that the issue does not occur when matplotlib is installed via `pip` suggests at least that conda might know better what's happening.

**Comment by jklymak** [comment]
@tacaswell  `get_backend()` just says "Return the name of the current backend" and I think its reasonable for users to not expect that to *do* anything, like import pyplot and set the backend.  

I don't see how this is conda's fault.  I have no idea what matplotlibrc they ship, but I should be able to run the above code w/ no matplotlibrc.

**Comment by anntzer** [comment]
The correct fix IMO is what I proposed in https://github.com/matplotlib/matplotlib/pull/11600#issuecomment-411819618, which is to make use() succeed even if the backend has already been "set", as long as the event loop did not start yet.
This is what some early versions of the backend switching PRs did, but that got scrapped due to disagreement over the API.

**Comment by anntzer** [comment]
> Do we have good handle on when each of the event loops gets started / checking it is started? I think we need to be cautious or more than just if the loop is running, but if input_hook has been set up.

We have get_running_interactive_backend() which is supposed to check just that.

**Comment by tacaswell** [comment]
I don't think we defer the imports long enough, if you have the rcparams set to Qt5, then even though the event loop will not have started yet you will not be able to switch to Qt4.

In principle I agree it sounds good, but I am worried about it only working sometimes.

**Comment by anntzer** [comment]
In that specific case you'll get an ImportError, which is just fine with me.
Remember that the current behavior of use() is that if pyplot is already imported, then we won't switch, except if force=True, in which case, well, we'll give it a try but it may or may not work.  (And on top of that we may or may not get a warning depending on the value of warn.)
The proposed behavior is that neither force nor warn will exist anymore, and either the switch will silently succeed, or raise an ImportError.  If you are *really* worried about breaking some setups we can always keep force with a default of True, with the meaning "silently suppress ImportError"...
