### ISSUE TITLE
Examples in docs should be redirected to latest version number

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12374]
_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/12244#issuecomment-426337602_

There's no redirection right now.  I think we should redirect matplotlib.org/gallery/... to matplotlib.org/$version/gallery/... (which is what cpython does) so that people don't bookmark links that will be broken in the future, but that's a wholly separate issue...

**Comment by ImportanceOfBeingErnest** [comment]
The problem with that is what you can currently observe already when searching on google: It'll find old pages for you, because those are the ones most links direct to. (e.g. google "[matplotlib+imshow+example](www.google.de/search?q=matplotlib+imshow+example)"). Relevant: https://github.com/matplotlib/matplotlib/issues/10016  and https://github.com/matplotlib/matplotlib/issues/10854

**Comment by floggle** [comment]
I would suggest using robots.txt (which currently doesn't exist).

If you put all your docs in directories named after the version /docs/3.0.2/ and then only allow robots to crawl the /current/ edition (which is just an invisible pointer to /3.0.2/ for instance), that would go a long way to reducing end-user discovery of old docs. The old versions would remain perpetually available for links.

**Comment by timhoffm** [comment]
Does somebody know if it's possible to integrate the version picker from readthedocs into other sites?
![grafik](https://user-images.githubusercontent.com/2836374/51424587-2f2aea80-1bd0-11e9-9e11-86f02e134e74.png)

IMHO that would really help with version confusion.

**Comment by dopplershift** [comment]
So on other projects, the RTD theme has an option `canonical_url` that can be used to set a path to the version we want crawled--it adds links with the `rel="canonical"` attribute that apparently tells the crawlers what we want. I set it in `conf.py` as, e.g.: 

```python
{'canonical_url': 'https://matplotlib.org/latest/'}
```

though that would require us to have something like https://matplotlib.org/ work as a root for the latest for all doc pages--I'm not sure if that's the case. I'm also not sure if the `canonical_url` is a standard option or if it could easily be grafted onto our theme.

**Comment by jklymak** [comment]
I think #13592 was incorrect, and canonical should point to our top level.  I think we should also have a sitemap.xml that puts a lower weight on the old versions versus the current one.  Do we have anyone who knows enough about how to do this automatically?  Maybe using this extension: https://github.com/jdillard/sphinx-sitemap

**Comment by jklymak** [comment]
Re-milestoning because our search results are really all over the place.

**Comment by jklymak** [comment]
See also https://stackoverflow.com/questions/63542354/readthedocs-robots-txt-and-sitemap-xml

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib.github.com/pull/47 for most of this....

**Comment by jklymak** [comment]
See matplotlib/matplotlib.github.com#48 for an alternative to matplotlib/matplotlib.github.com#47 

@floggle Do you have SEO experience?  Is matplotlib/matplotlib.github.com#48 what you were suggesting?  Note the sitemap.xml down-weights the old versions, versus hiding them.  We could also hide the old versions and only allow `/stable/`...

**Comment by jklymak** [comment]
Now see matplotlib/matplotlib.github.com#49
