### ISSUE TITLE
Bug with font finding, and here is my fix as well.

### ISSUE THREAD

**Issue by PGTBoos** [matplotlib/matplotlib#12406]
### Bug report
font_manager crashes with font not found errors, 
**Bug summary**
there is an Issue allready for this, but after i fixed it i couldnt find that issue back as when i fixed it my errors where gone .

Some error about font not found
**Code for reproduction**
from matplotlib.font_manager import win32InstalledFonts
print(win32InstalledFonts())

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: matplotlib:2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: Python:3.6.2
  * Jupyter version (if applicable): (latest)
  * Other libraries:
 
Conda default

Here is my fix:

    def win32InstalledFonts(directory=None, fontext='ttf'):
    """
    Search for fonts in the specified font directory, or use the
    system directories if none given.  A list of TrueType font
    filenames are returned by default, or AFM fonts if *fontext* ==
    'afm'.
    """
    import winreg
    if directory is None:
        directory = win32FontDirectory()
    fontext = get_fontext_synonyms(fontext)
    items = set()
    for fontdir in MSFontDirectories:
        try:
            with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, fontdir) as local:
                for j in range(winreg.QueryInfoKey(local)[1]):
                    key, direc, tp = winreg.EnumValue(local, j)
                    if not isinstance(direc, str):
                        continue
                    # Work around for https://bugs.python.org/issue25778, which
                    # is fixed in Py>=3.6.1.
                    direc = direc.split("\0", 1)[0]
                    try:
                        path = Path(directory, direc).resolve()    #errors on file not found
                        items.add(str(path))
                    except:
                        #print ("found invalid font direc : {}",direc)
                        continue
        except (OSError, MemoryError):
            continue
    return list(items) 

Essentially problems are caused because the registry does not really reflect all the fonts, that was the reasons Path(directory,direc).resolve() crashed, so placed it inside another try excerpt and it now works.
The point here is registry does not reflect the file system, people can remove software in wild ways. 
i left a commented option to show the missing files in the excerpt.
Its fixed now so i hope other people with the same issues can be happy and go coding now :), 
its my first python opensource contribution

**Comment by anntzer** [comment]
Calling `Path("non/existent/path").resolve()` doesn't crash for me; can you show an example of failing case that this fixes?

**Comment by PGTBoos** [comment]
notice that in case of the first try: in above code, that the code also didnt provide fonts cause a non existing fontdir wa passed trough (didnt exist in regsitry at all) and that would erase the entire item list.
By doing sub level try catch just before it is checked this is resolved.

**Comment by PGTBoos** [comment]
some how a wrong registry path is givven suposendly having fonts, well not on my win 10 system the regkey didnt exist.

**Comment by anntzer** [comment]
Ah, I see, this changed in Py3.6:

> If the path doesn’t exist and strict is True, FileNotFoundError is raised. If strict is False, the path is resolved as far as possible and any remainder is appended without checking whether it exists. If an infinite loop is encountered along the resolution path, RuntimeError is raised.

> New in version 3.6: The strict argument.

in 3.5 this was

>̣ If the path doesn’t exist, FileNotFoundError is raised. If an infinite loop is encountered along the resolution path, RuntimeError is raised.

So the fix seems fine but the except clause should specifically just catch FileNotFoundError and RuntimeError.

**Comment by PGTBoos** [comment]
i'm not coding that long in python just a few days days or so
but i think the code is ok like this, essentially it tries to check a font, on whatever cause it fails will result in not adding it to the list. 

English is not my first language, so i hope my bug cause explanation was clear.
And i dont know who puts the fix on git, i dont plan for joining this matplotlib project, could you do that ?
I saw quite a few stackoverflow questions related to this, (also from earlier years).

**Comment by anntzer** [comment]
Sure, I'll do it.

**Comment by PGTBoos** [comment]
maybe a small side note, that it seamed strange to me that only lowercase  font extensions where added in the old code. It doesnt violate windows if WINDINGS2.TTF was used besides windings.ttf

**Comment by anntzer** [comment]
That was already reported and fixed elsewhere.
