### ISSUE TITLE
replace ttconv for ps/pdf

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12418]
_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/5414#issuecomment-371353438_

Actually there's (at least) still one thing that this PR does which #9763 doesn't, which is to replace ttconv (the font subsetter for pdf/ps output).  That's actually a task fairly independent from wrapping freetype (which is what #9763 focuses on).

**Comment by QuLogic** [comment]
It needs updating, but this is done in #20866.

**Comment by QuLogic** [comment]
The PR is still open, and has been rebased, so this could be closed by it.
