### ISSUE TITLE
ColorbarNorm Tutorial needs some work....

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12424]
_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/12419#issuecomment-427610481_

In [the current version](https://matplotlib.org/gallery/userdemo/colormap_normalizations.html#colormap-normalizations) that example has somehow become useless, as it suddenly uses data that is symmetric about 0 anyways. It also lost the warning. There is also an error in the BoundaryNorm section. I suppose that was edited in a hurry and would need to be refurbished anyways.

**Comment by ImportanceOfBeingErnest** [comment]
Actually, there is a [tutorial](https://matplotlib.org/tutorials/colors/colormapnorms.html) and an [example](https://matplotlib.org/gallery/userdemo/colormap_normalizations.html#colormap-normalizations) which are *almost* identical. This issue mostly applies to both of them.

**Comment by jklymak** [comment]
#12419 will update those examples.  The last statement should have been `Z1 - 0.4 * Z2`

**Comment by story645** [comment]
Was this closed by #12419?

**Comment by timhoffm** [comment]
- The data is not symmetric anymore in https://matplotlib.org/devdocs/tutorials/colors/colormapnorms.html#twoslopenorm-different-mapping-on-either-side-of-a-center. I assume that was the original main point.
- Don't understand what the "lost warning" is.
- Don't see the "error in the BoundaryNorm section".

From the issues mentioned in the original post, it seems more or less solved. @jklymak please confirm. If that's the case we can close this.

I've moved the discussion on tutorial/example similarity to a separate issue #15866.
