### ISSUE TITLE
matplotlib-mac

### ISSUE THREAD

**Issue by musdfakoc** [matplotlib/matplotlib#12437]
### Bug report

**Bug summary**

The matplotlib does not work properly in python with climt. Normally the graphics should be like changing with time yet first it did not show the graphs and when it finally opens it is only the initial time's graphics.
**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: MacOSX Mojave
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7.0
  * Jupyter version (if applicable):5.6.0 (notebook), 0.34.9 (jupyterlab)
  * Other libraries: climt

**Comment by ImportanceOfBeingErnest** [comment]
This is a bit vague. If you can enable people reproduce the issue, e.g. by providing a runnable code, it would be possible to look into this. But as it stands, it doesn't look like a matplotlib issue.  
I would hence close this. However if there is any evidence for a bug in matpotlib feel free to provide more insight into the problem and reopen this issue.
