### ISSUE TITLE
Scatter doesn't accept a list of strings as color spec.  

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12438]
_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/12431#issuecomment-427697109_

I wonder if this is the correct fix. The documentation also states

> `c` : color, sequence, or sequence of color, optional, default: 'b'
The marker color. Possible values:
>
>* A single color format string.
>* **A sequence of color specifications of length n.**

So for 

    plt.scatter([0,1],[2,3],c=("0.5", "0.7"))

one would expect two points with different shades of grey. But this is converted to an array of values and shown with the viridis colormap.  
Not sure if the documentation is wrong here or the code.

**Comment by anntzer** [comment]
Given that `plt.scatter([0,1],[2,3],c=("r", "b"))` works as expected and that "0.5", "0.7" are well-documented as strings meaning levels of gray, I'd argue it's a code bug, not a documentation one.

**Comment by jklymak** [comment]
#12431 looks after this as well...
