### ISSUE TITLE
Travis error is MacOS image tolerance of 0.005 for `test_constrained_layout.py::test_colorbar_location`

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12433]
_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/pull/12431/comment#issuecomment-427675481_

Travis error is MacOS image tolerance of 0.005 changing for `test_constrained_layout.py::test_colorbar_location`.  Not sure what changed on macOS to cause this, but it doesn't affect this PR.

**Comment by jklymak** [comment]
This seems to have fixed itself 🤷‍♂️

**Comment by QuLogic** [comment]
I mean, it was the full test suite, so whether it was slower wasn't particularly noticeable. I also re-ran just the one test 100 times over and it never failed, so...

Should we just mark it as flaky then?
