### ISSUE TITLE
Issues with gridspec/tight_layout in matplotlib version 2.2.3

### ISSUE THREAD

**Issue by BenMGeo** [matplotlib/matplotlib#12444]
### Bug report

**Bug summary**

We use [iris](https://github.com/SciTools/iris) that requires [cartopy](https://github.com/SciTools/cartopy) and matplotlib for plotting maps.

A display error occurred, when using matplotlib 2.2.3 compared to 2.2.2 or 2.2.0.

We use matplotlib.gridspec to have 3 subplots (main map (iris.quickplot.pcolormesh), summary line plot (iris.quickplot.plot) and a matplotlib colorbar (matplotlib.pyplot.colorbar)) and use matplotlib.pyplot.tight_layout() thereafter.

With 2.2.0 or 2.2.2, we had no overlaps of plots and labels. With 2.2.3, the plots come in front of the neighbouring plots' labels.

(python 2.7.15, conda-forge environment)

**Code for reproduction**

(Even a code snippet would be large. I will produce one, if really required.)

**Actual outcome and Expected outcome**
![image](https://user-images.githubusercontent.com/14977178/46612690-946f3a00-cb11-11e8-8117-dec848978aaa.png)

**Comment by ImportanceOfBeingErnest** [comment]
It is important to be able to reproduce the undesired behaviour in order to see if there is a problem and eventually to be able to fix it. It is unlikely that some developper installs iris in two different environments with the respective matplotlib versions and keeps playing around with it until the undesired behaviour pops up. It would hence be helpful to see a minimal, runnable code that produces this, and, if possible it shouldn't use iris or cartopy. Or if this issue only occurs with those, opening the issue at the issue trackers of those projects would make more sense, I suppose.

**Comment by jklymak** [comment]
... or bisecting the change using git bisect to tell us what commit broke the layout.

**Comment by BenMGeo** [comment]
Sorry to bother you.

I thought it would be a matplotlib issue due to finding this, when switching matplotlib versions. 

Apparently, my minimal script not using iris/cartopy cannot reproduce these glitches. 

My bad. I'll aproach the respective github pages.

**Comment by jklymak** [comment]
It still seems that we changed something in 2.2.3, so please do let us know what you find.

**Comment by BenMGeo** [comment]
I tried to reproduce the errors above and found that I could not! 

Instead of using my old environment with 2.2.3, I set up a minimum environment and everything works fine. So a fresh install makes 2.2.3 compatible. Looks like some .pyc files (?) were the reason for the issue. 

It's really hard to find the reason here.

**Comment by BenMGeo** [comment]
We have the same issue now for somebody using matplotlib 3.0

**Comment by dibsonmuad** [comment]
Issue is still present in matplotlib 3.0.3. Works on 2.2.2 (Those are the two versions we use). So it looks like something broke between 2.2.2 and 2.2.3.

**Comment by ImportanceOfBeingErnest** [comment]
Looks like we still need a reproducible example to be able to take any action here.
