### ISSUE TITLE
Formatting numerical legend

### ISSUE THREAD

**Issue by stevencollinscn** [matplotlib/matplotlib#12454]
I'm looking for a way to format the numerical legend (e.g. using integers) in matplotlib and haven't received any answer on [StackOverflow](https://stackoverflow.com/questions/52503899/format-number-in-legend-label-in-matplotlib). Thus, I wonder if there is a way to do so right now. If not, I wonder if this could be a possible feature to add in the future release.

**Comment by QuLogic** [comment]
The labelling for the items that goes in the legend is done by wherever you get `gdf` from (Pandas? GeoPandas?). If you tag your SO post with those topics, you might get more interest, but this is not a request that can be fulfilled by Matplotlib, since it does not do any of that work.

**Comment by stevencollinscn** [comment]
@QuLogic The map is made by `geopandas`, but in my second case where I got the plot with `Seaborn` and set the legend with `ax.legend()`. Is it controlled by `matplotlib`?

**Comment by QuLogic** [comment]
That would be done by seaborn, presumably. Matplotlib does not do any formatting of labels for the legend; it uses whatever is given to it by the whatever calls the plotting functions. You can attempt to pass [labels to `ax.legend` yourself (see 2 and 3)](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.legend.html), but you would have to generate them yourselves all over.

**Comment by stevencollinscn** [comment]
@QuLogic the doc seems to explain how to label legends instead of the subgroups under a legend, but thanks for the clarification.
