### ISSUE TITLE
Documentation of AnchoredText's prop keyword argument is misleading

### ISSUE THREAD

**Issue by galenlynch** [matplotlib/matplotlib#12467]
This bug is nearly identical to #12121, but affects `AnchoredText` instead of `TextArea`.

The [documentation](https://matplotlib.org/api/offsetbox_api.html#matplotlib.offsetbox.AnchoredText) for `AnchoredText` strongly suggests that the keyword argument `prop` should be a `FontProperties` object. However, inspecting the [source code](https://matplotlib.org/_modules/matplotlib/offsetbox.html#AnchoredText) suggests that `prop` should instead be a dictionary of keyword arguments that will be passed to the `TextArea` object inside of `AnchoredText`.

I propose rewording the documentation to make it clear that `prop` should be a dictionary of keyword arguments to construct the `TextArea` instance.

Perhaps it would be worthwhile to look over the documentation of other classes in `offsetbox` for similar issues, since this is the second time I've come across the same issue.

**Comment by ImportanceOfBeingErnest** [comment]
Sure, judging from #12434 you already know how that would be fixed. So if you have the time, just go ahead (no need to open a new issue for each item you find).

**Comment by galenlynch** [comment]
Maybe I should make another issue for this, but it would be nice if `TextArea` and `AnchoredText` had a consistent API, maybe by renaming the `prop` argument of `AnchoredText` to be `fontprops` as is used by `TextArea`, which has the added benefit of being more descriptive. 

It seems like it would be fairly easy to also support the old keyword, to prevent breaking people's code.

What's the attitude around here to such API changes? All things considered, it's a very minor complaint.
