### ISSUE TITLE
cbar.add_lines should allow manually adding lines, not just contour sets

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12462]
_Originally posted by @dstansby in https://github.com/matplotlib/matplotlib/pull/12461#issuecomment-428247970_

Huh, and here I am manually adding lines to the cbar axes with `axhline`! You learn a new bit of the API every day...

_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/pull/12461#issuecomment-428249505

We could extend the API of cb.add_lines to check if the first argument is a list of levels instead of a ContourSet, but that entails a bunch of extra kwargs to pass down.

**Comment by dstansby** [comment]
Actually, for manually adding lines to just the colourbar I think using `axhline` on the colourbar axes is a reasonable way of doing it - an example in the gallery would be nice though showing how to get the colourbar axes and then add a hline.

**Comment by wsoofi** [comment]
I'm happy to do this.

**Comment by timhoffm** [comment]
I think this is solved by #13506. Please report back if that's not sufficient.

**Comment by QuLogic** [comment]
I thought this issue is about adding an example to demonstrate how to do it. #13494 did that, but was complicated by other issues which were fixed by #13506, but the _example_ is still not merged. So do we still want an example (now somewhat simpler)?
