### ISSUE TITLE
"close_event" for nbagg/notebook backend

### ISSUE THREAD

**Issue by rasai** [matplotlib/matplotlib#12480]
Hello,

This is sort of a bug report/cry for help. 

I have a notebook cell with the "%matplotlib notebook" magic that continually updates (with a while loop) an interactive plot. What I am hoping to do is to break out of the loop when the close button on the top right is pressed. In other words, I am trying to do something like:
```python
while some_condition:
  # ... plot commands ...
  if figure_is_closed():
    break
  else:
    fig.canvas.draw()
```
I am trying to find how to do the "figure_is_closed()" part.

I tried implementing setting some global Boolean using the 'close_event' described in https://matplotlib.org/gallery/event_handling/close_event.html
But this event doesn't seem to work with the nbagg/notebook backend. 
To make sure it wasn't because of some error in my code, I downloaded the example notebook from the above site, changed the first line to "%matplotlib notebook" then closed the figure with the power button. 
But the "closed figure" print statement did not show up.
I'm not sure if this is intended behavior, my misunderstanding of the example, or a bug.

I also searched online and went through the docs/sources but I wasn't able to figure out other approaches on how to do this. 

Any help would be appreciated.

**Matplotlib version**

  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbagg/notebook
  * Python version: 3.5
  * Jupyter version (if applicable): 0.7

**Comment by jklymak** [comment]
This would be better discussed on StackOverflow or the mailing list, perhaps including the jupyter/ipython folks.  If there is a bona fide matplotlib bug isolated, please do let us know.  Thanks!

**Comment by ImportanceOfBeingErnest** [comment]
> "But the "closed figure" print statement did not show up."

You cannot `print` anything in jupyter from within an event loop. So if the sole witness for whether or not an event has been triggered is a print statement, the callback might as well just been called.  
I would argue that the close_event should indeed also work in notebooks. So if it doesn't, this might be a bug. A quick test however did not give any indication that it wouldn't. I suppose the notebook version of 0.7 that is reported is much too old to reliably work. 

![image](https://user-images.githubusercontent.com/23121882/46768389-47918c00-cce8-11e8-92b8-22bafc1da8ea.png)

...although it seems strange that it's called twice.

**Comment by rasai** [comment]
Sorry for the slow response. I wanted to do a little more testing before I respond.
The Jupyter version is actually 4.4.0 (I had accidentally listed JupyterHub version) and in the jupyter notebook example on the matplotlib website:
https://matplotlib.org/gallery/event_handling/close_event.html
there is a print statement inside the event loop, so I had followed that. 

Here is an adapted example notebook that I made based on your status trick:
```
%matplotlib notebook
import matplotlib.pyplot as plt
import time

status = []
def handle_close(evt):
    status.append('done')

fig = plt.figure()
fig.canvas.mpl_connect('close_event', handle_close)
plt.text(0.35, 0.5, 'Close Me!', dict(size=30))
count=0
while len(status)<1 and count < 10:
    fig.canvas.draw()
    print("waiting... {0}".format(status))
    time.sleep(1)
    count+=1
```
But even if I press the close button, it will always print 'waiting... []' 10 times. It looks like the callback function is somehow buffered, and only called at the end. To test this, I ended cloning matplotlib and inserting a test `raise Exception` inside 
matplotlib/lib/matplotlib/backends/backend_nbagg.py at line 214: (Yes, this is terrible but I wanted something fast)
```
    def on_message(self, message):
        # The 'supports_binary' message is relevant to the
        # websocket itself.  The other messages get passed along
        # to matplotlib as-is.

        # Every message has a "type" and a "figure_id".
        message = json.loads(message['content']['data'])
        if message['type'] == 'closing':
            raise RuntimeError('Testing closing')
            self.on_close()
            self.manager.clearup_closed()
        elif message['type'] == 'supports_binary':
            self.supports_binary = message['value']
        else:
            self.manager.handle_json(message)
```
And the error is thrown to the jupyter log at the end of the 10 iterations. Looks like it is buffered for some reason. I'll look around more and ask on SO to see if there is away to force flush this buffer.

Thank you for your help!

**Comment by ImportanceOfBeingErnest** [comment]
The while loop is run outside the event loop. During that time no events can be processed (You can also not interact with the figure, like zooming etc.). You can manually call `FigureCanvas.flush_events()` to emulate your own "event loop" if that is of use for you.  
However, I would recommend to first start the event loop and do whatever you need to do inside of it. Matplotlib provides nice tools like `FuncAnimation` or `FigureCanvas.new_timer` that can be used for such purposes.

**Comment by rasai** [comment]
Ah, I see. I'll take a closer look at the tools you mentioned. Thank you so much!
