### ISSUE TITLE
run my code failed after i Import pylab failed, python version is 3.6.6

### ISSUE THREAD

**Issue by shangxww** [matplotlib/matplotlib#12499]
### Bug report

**Bug summary**
Installed [ylab in python 3.6.6 and then import it 

**Code for reproduction**
import pylab as pl
  File "C:\ProgramData\Anaconda2n\envs\py36\lib\site-packages\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "C:\ProgramData\Anaconda2n\envs\py36\lib\site-packages\matplotlib\__init__.py", line 351
    print(s, file=self.fileo)
                 ^
SyntaxError: invalid syntax

```python

import pylab as pl
import pymc as mc

G_obs = [1.]
N = len(G_obs)

R = mc.Categorical('R', [.2,.8], value=[1,0])

p_S = mc.Lambda('p_S', lambda R=R: pl.where(R, .01, .4),
                doc='Pr[S|R]')
S = mc.Categorical('S', p_S, value=pl.ones(N))

p_G = mc.Lambda('p_G', lambda S=S, R=R:
                pl.where(S, pl.where(R, .99, .9), pl.where(R, .8, 0.)),
                doc='Pr[G|S,R]')
G = mc.Categorical('G', p_G, value=G_obs, observed=True)

M=mc.MCMC(set([R,S,G]))
M.use_step_method(mc.Metropolis, R, proposal_sd=1., proposal_distribution='Normal')
M.sample(1e4)

**Matplotlib version**
matplotlib-3.0.0.dist-info

**Comment by tacaswell** [comment]
How did you install matplotlib?  I suspect something has gone wrong with your environments. 

If you add

```python
import sys
print(sys.version)
```

before you import pylab what do you get?

**Comment by shangxww** [comment]
My environment is windows7
@functools.wraps(func)
    def wrapper():
        nonlocal called, ret
In this line , error show 'end of statement expected

when i run my code, below error will be throw out
    nonlocal called, ret
                  ^
SyntaxError: invalid syntax

**Comment by shangxww** [comment]
> 
> 
> How did you install matplotlib? I suspect something has gone wrong with your environments.
> 
> If you add
> 
> ```python
> import sys
> print(sys.version)
> ```
> 
> before you import pylab what do you get?

Thanks you for your suggestion, above islsue has resolved.

**Comment by dstansby** [comment]
Great, feel free to re-open if it is still an issue!
