### ISSUE TITLE
Adding twin axes into polar coordinate system

### ISSUE THREAD

**Issue by 519165198** [matplotlib/matplotlib#12506]
### Bug report
Adding twin x Axes into polar coordinate system seems does not work
**Bug summary**

**Code for reproduction**

```python
import numpy as np
from matplotlib.ticker import FormatStrFormatter
import matplotlib.pyplot as plt


labels = np.array(['E', '', 'N', '', 'W', '', 'S', ''])
dataLength = 8
data = np.array([3.23, 3.23, 9.68, 3.23, 12.90, 32.26, 6.45, 29.03])
angles = np.linspace(0, 2*np.pi, dataLength, endpoint=False)

width = np.pi/8*np.array([1]*8)

ax = plt.subplot(111, projection='polar')
ax2 = ax.twinx()

bars = ax.bar(angles, data, alpha=0.4, label=labels, width=width, bottom=0.0, color="red")

data = np.array([10.3, 2.23, 15.68, 13.23, 12.90, 12.26, 8.45, 29.03])
data = np.concatenate((data, [data[0]]))
angles = np.concatenate((angles, [angles[0]]))

plots = ax.plot(angles, data, alpha=0.7, linestyle="--", linewidth=1, color="blue")
plt.fill(angles, data, facecolor='blue', alpha=0.25)

gridLines, gridLabel = ax.set_thetagrids(angles * 180/np.pi, labels, fontproperties="DejaVu Sans")

ax.yaxis.set_major_formatter(FormatStrFormatter('%d%%'))

plt.yticks(fontsize=8)
plt.xticks(fontsize=15)

[label.set_fontweight('bold') for label in ax.get_xticklabels()]
[label.set_color('blue') for label in ax.get_yticklabels()]

plt.show()
```

**Actual outcome**

```

```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
It would help if "Actual outcome" and "Expected outcome" weren't left empty. At least to me it is not clear what a `twinx` axes for a polar plot (i.e. a second theta axis) should look like or what its functionality might be. 
With a bit of imagination I could think of a `twiny` in the sense of a second r-axis though. Is that what you mean?

**Comment by 519165198** [comment]
![1fecb3ec-6f94-4f7a-b272-373a6198eda6](https://user-images.githubusercontent.com/38233072/46884013-40a08000-ce86-11e8-9e24-b619a71c7cec.png)
![4d07c7df-0c29-4db0-bdc4-4ab48e28516a](https://user-images.githubusercontent.com/38233072/46884014-40a08000-ce86-11e8-8944-700e7beaab8d.png)

**Comment by 519165198** [comment]
> I'm affraid that's currently not possible. I added the "Wishlist" tag. It might be that someone is willing to provide such feature.

Thanks for your reply!
