### ISSUE TITLE
LogNorm ticklabels on colorbar

### ISSUE THREAD

**Issue by Phlya** [matplotlib/matplotlib#12503]
### Bug report

**Bug summary**

I think position of ticklabels on colorbars with `LogNorm` is sometimes weird, and I believe it wasn't like this in earlier versions, but I haven't checked that now. Namely, in the example below, I would expect the lowest ticklabel be at 5x10-1, not 6x10-1 as it is now.

**Code for reproduction**

```python
plt.imshow(np.random.random(15**2).reshape((15, 15))+0.5, norm=LogNorm(vmax=2, vmin=0.5), cmap='coolwarm')
plt.colorbar()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2895034/46867350-97716f80-ce1c-11e8-9c2c-793a8a2b1b43.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): inline
  * Python version: 3.5.2
  * Jupyter version (if applicable): Jupyter Lab 0.33.6

**Comment by ImportanceOfBeingErnest** [comment]
At least in matplotlib 2.0.2, the resulting image is the same as shown above.   
In matplotlib 1.5.3 the resulting image is 

![image](https://user-images.githubusercontent.com/23121882/46869300-93991980-ce2b-11e8-9e38-38a2a2d4e563.png)

In current master, the result is

![image](https://user-images.githubusercontent.com/23121882/46869361-c6431200-ce2b-11e8-8003-63b817baed55.png)

where something strange is happending with the formatting, probably the same issue as https://github.com/matplotlib/matplotlib/issues/12488.

That being said, I think having the lower end ticked and labeled if it falls on a "useful" number may be more appealing; but expectations might be different here for different cases, such that finding a good default. You can decide to have all minor ticks labelled (which would result in crowded axes here) or none (which would not show any label except the10^1), or, you can have "nice" labels (the default). This is hardcoded to be [1,2,3,4,6,10]*10^exp

https://github.com/matplotlib/matplotlib/blob/aa1e5cfce851b02dfd0806d07d6ec703a0d4cbfb/lib/matplotlib/ticker.py#L963

On a by-case basis you may of course use your own locations

```
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm
from matplotlib.ticker import LogFormatterSciNotation

plt.imshow(np.random.random(15**2).reshape((15, 15))+0.5, 
           norm=LogNorm(vmax=2, vmin=0.5), cmap='coolwarm')


class MF(LogFormatterSciNotation):
    def set_locs(self, locs=None):
        self._sublabels = set([1,2,5,10])

cb = plt.colorbar(format=MF())

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/46874491-8e42cb80-ce39-11e8-8596-94eab980cd9a.png)

**Comment by ImportanceOfBeingErnest** [comment]
Yep, so the problem can of course be reformulated as to whether there should be an option to customize automatic ticking in

```
plt.xscale("log")
plt.xlim(0.5, 2)
```

![image](https://user-images.githubusercontent.com/23121882/46875591-5a1cda00-ce3c-11e8-9573-4fa9eef98e3d.png)

**Comment by anntzer** [comment]
I think @Phlya may not see the formatting (superscript vs inline math) issue because of some setting in his rcParams? @Phlya can you provide them?

**Comment by Phlya** [comment]
Here is my matplotlibrc, I think everything is commented out...
[matplotlibrc.zip](https://github.com/matplotlib/matplotlib/files/2473557/matplotlibrc.zip)
And I also have `sns.set_style("ticks")` in case it might be important.

**Comment by ImportanceOfBeingErnest** [comment]
No, the "formatting (superscript vs inline math) issue" does not appear in version 2.2.2 (which @Phlya is using). Neither in matplotlib 3.0.0. It only appears in the master branch.

**Comment by anntzer** [comment]
I also see it with mpl3.0.0.

**Comment by jklymak** [comment]
> Having an interface for those of the style `LogFormatter(..., sublabels=None)` would be an option to add. In case `sublabels` are provided, `minor_thresholds` would be ignored, and `self._sublabels = sublabels` being set.

This seems a reasonable feature request to me.  I actually am not sure I like the defaults....

**Comment by Phlya** [comment]
I keep stumbling upon this issue - I often use LogNorm with values around 1 in the range as used above.

I was just now trying to reproduce the custom subclass from https://github.com/matplotlib/matplotlib/issues/12503#issuecomment-429339689 to fix this, but it doesn't seem to work:

```
class MF(LogFormatter):
    def set_locs(self, locs=None):
        self._sublabels = set([1,2,3,4,5,6,7,8,9,10]) # All levels just as an example
im = plt.imshow(np.linspace(0.5, 2, 100).reshape((10, 10)), norm=LogNorm(0.5, 2))
cb = plt.colorbar(format=MF())
```
![image](https://user-images.githubusercontent.com/2895034/68023414-f3649b80-fc9e-11e9-8386-33bd840e8f15.png)

I am using mpl 3.1.1

Any ideas? Is there another way to fix this?

The problem is that I always want to show the bottom tick, but even adding with `cb.set_ticks([0.5]` doesn't do anything.

**Comment by Phlya** [comment]
Even more strange, perhaps, is that with vmin=0.25, vmax=4 the colorbar has no tick labels apart from 1.
![image](https://user-images.githubusercontent.com/2895034/68023677-cd8bc680-fc9f-11e9-994e-719907721887.png)

**Comment by jklymak** [comment]
PRs certainly welcome for this - someone would have to dig into the guts of the LogFormatter for minor ticks.  That would be great, but it is unusual to use log scales on such a small range of data, hence it hasn't received much attention.  Note the simpler minimal example is 

```
import matplotlib.pyplot as plt

plt.xscale("log")
plt.xlim(0.25, 5)
plt.show()
```

**Comment by ImportanceOfBeingErnest** [comment]
The workaround from above would now need to look like

```
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm
from matplotlib.ticker import LogFormatterSciNotation

plt.imshow(np.random.random(15**2).reshape((15, 15))+0.5, 
           norm=LogNorm(vmax=2, vmin=0.5), cmap='coolwarm')

class MF(LogFormatterSciNotation):
    def set_locs(self, locs=None):
        self._sublabels = set([1,2,5,10])

cb = plt.colorbar(format=MF())
cb.ax.yaxis.set_minor_formatter(MF())

plt.show()
```

but it's still a workaround and uses some private attribute, so a more sustainable solution is clearly desireable.

**Comment by anntzer** [comment]
Would be nice to figure out why https://github.com/matplotlib/matplotlib/pull/12865 doesn't help here.
