### ISSUE TITLE
pyplot.step broken in 3.0.0?

### ISSUE THREAD

**Issue by jgillis** [matplotlib/matplotlib#12515]
### Bug report

**Bug summary**

There appears to be a mix-up of arguments for `pyplot.step`.
`x` and `y` arguments get promoted to keyword arguments, but `Axes.step` wants them as positional arguments.

**Code for reproduction**

```python
from pylab import *;step([1,2],[3,4],'g')
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jgillis/miniconda3/envs/temp_env/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2850, in step
    return gca().step(x=x, y=y, *args, where=where, data=data, **kwargs)
  File "..../lib/python3.6/site-packages/matplotlib/__init__.py", line 1786, in inner
    return func(ax, *args, **kwargs)
TypeError: step() got multiple values for argument 'x'
```

**Expected outcome**

A plot.

**Matplotlib version**
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): any of them
  * Python version: 3.6.5 (Installed with miniconda)

**Comment by anntzer** [comment]
That's already fixed by #12293, which will be in the next bugfix release.
Thanks for the report!
