### ISSUE TITLE
Empty axes on draw after blitted animation finishes

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#12528]
### Bug report

**Bug summary**

When using blitting in an animation the figure window can be resized and the plot can be zoomed without problem **while** the animation is running.  
However after the animation finishes (`repeat=False`), the content is not redrawn to the canvas and the axes become empty on zooming/panning/resizing.

This issue was raised on Stackoverflow: https://stackoverflow.com/questions/52806527/how-can-i-keep-the-last-frame-when-i-use-matplotlib-animation-function-with-blit

**Code for reproduction**

Code taken from [the simple animation example](https://matplotlib.org/gallery/animation/simple_anim.html) and adapted to use `repeat=False` and equipped with a callback to print the line visibility.

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, ax = plt.subplots()

x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))

def init():  # only required for blitting to give a clean slate.
    line.set_ydata([np.nan] * len(x))
    return line,

def animate(i):
    line.set_ydata(np.sin(x + i / 100.))  # update the data.
    return line,

ani = animation.FuncAnimation(
    fig, animate, init_func=init, frames=100, interval=20, blit=True, repeat=False)

def ondraw(evt):
    print(line.get_visible())

fig.canvas.mpl_connect("draw_event", ondraw)

plt.show()
```

To reproduce, wait till the animation finishes, then resize the window or zoom or pan in the axes.

**Actual outcome**

An empty axes after zooming, panning, resizing.
Even though the connected `ondraw` callback prints `True` for the visibility of the line througout.

**Expected outcome**

The line should be visible.

**Matplotlib version**

  * Operating system: Win8
  * Matplotlib version: 2.0.2, 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6

**Comment by tacaswell** [comment]
Punting to 3.2. 

I took a quick look at this and I think the solution is to, on ending the loop call `art.set_animated(False)` on all of the blitted artists, but it was not immediately clear to me where the right place to put that logic was.

**Comment by oh54** [comment]
Does this have hope of making it into 3.2.0?

**Comment by ar13pit** [comment]
Hi @tacaswell, on ending the loop call `art.set_animated(False)` does retain the data if pan or zoom is used, however the axes completely clear out when the window is resized. Do you have any suggestion to solve this issue?

**Comment by ar13pit** [comment]
After trying out quite a few approaches, I solved this issue the following way:

1. Instead of using multiple functions with `animation.FuncAnimation`, I wrote a class inheriting from `animation.FuncAnimation`
2. Defined all the required functions (func, frames, init_func) as member functions
3. In the generator function, after the loop ends I added the following 2 lines:
    ```python
    self.art.set_animated(False)
    self.fig.canvas.mpl_disconnect(self._resize_id)
    ```
    Doing so stopped the blitting and disconnected the `resize_event` handler inherited from the parent class `animation.Animation`.

It would be great if something like this can be integrated into one of the classes.

**Comment by tacaswell** [comment]
@ar13pit Can you push that code someplace?  I don't quite understand (did you redefine all of the methods?  If so why did you inherit from `FunctionAnimation`?).

From this description, my guess as to what the fix should be is to put the disconnect / `set_animated_false` code in the method where we decide to _not_ repeat.

A PR to implement that would be very welcome!

**Comment by ar13pit** [comment]
Sure! I'll implement a PR soon. 

The solution is quite simple. The only reason I inherited from `FuncAnimation` was to have access to the variable `self._resize_id` defined in its parent class, which is the connection id of the `resize_event` handler. 

I'll put it up in a method in a clean way, so its more clear.
