### ISSUE TITLE
Incorrect rendering of math symbols

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#12532]
### Bug report

Reopened #12183 (part 2) as a separte issue to keep track of it:

> 2. The [Writing mathematical expressions](https://matplotlib.org/tutorials/text/mathtext.html) tutorial aquires all kinds of red symbols which dont belong there.
> 
> ![image](https://user-images.githubusercontent.com/23121882/45818896-4cfc4780-bce3-11e8-8f8f-be86ea129443.png)  or   ![image](https://user-images.githubusercontent.com/23121882/45818914-5d142700-bce3-11e8-8150-12c13ca89274.png)

#### Comment by @anntzer:

I think I know how to fix the red mathtext symbols (you "just" need to patch the suitable docutils dicts and/or send a patch to docutils) but it's not going to be a priority for me, pinning to 1.7.9 in the meantime is fine.

#### Alternative temporary workaround:

Pin Sphinx to <1.8.0.

**Comment by anntzer** [comment]
self-assigning, but anyone else can go for it if they want.

**Comment by colinmetcalf** [comment]
I'd like to take a swing at this if it hasn't been resolved yet!
