### ISSUE TITLE
matplotlib 3.0 animation blitting bug with Qt5Agg backend

### ISSUE THREAD

**Issue by djpine** [matplotlib/matplotlib#12536]
### Bug report

**Bug summary**

On animations that use blitting, a horizontal bar appears at the bottom and a vertical bar on the right of function animation plots when using the Qt5Agg backend but not when using the TkAgg backend.

The attached screenshot shows the problem for the "The Bayes update” example from the matplotlib animation examples: https://matplotlib.org/gallery/animation/bayes_update.html#sphx-glr-gallery-animation-bayes-update-py

Any version before 3.0.0

**Matplotlib version**

  * Operating system: macOS: 10.13.6
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.0
  * Jupyter version (if applicable):
  * Other libraries: 

 conda
 anaconda

<img width="724" alt="bayes_update_frame" src="https://user-images.githubusercontent.com/3291641/47028554-e3e4e400-d169-11e8-870a-2ed4102173fd.png">

**Comment by ImportanceOfBeingErnest** [comment]
What does "Any version before 3.0.0" mean? Is this an issue which occurs in matplotlib 3.0.0 or is it an issue which occurs in any version before that?

**Comment by jklymak** [comment]
I can't reproduce this in 2.2.3, 3.0.0 or master.  Maybe your Qt5 install is broken?

**Comment by anntzer** [comment]
I'm going to close this based on the lack of confirmation or activity.  Feel free to ping for reopen if this is still valid.

**Comment by djpine** [comment]
The issue hasn't gone away.  Did you try doing this on a Mac under OSX.
Here are my parameters.  I get the same (bad) result on 3 different
installations (all anaconda).  I have no reason to believe anything is
wrong with my Qt5Agg installation.  It works for all other purposes.  By
the way, if I save the animation using ffmpeg, the mp4 file it produces
does not have this problem---it's fine.


   - Operating system: macOS: 10.14.4
   - Matplotlib version: 3.0.3
   - Matplotlib backend (print(matplotlib.get_backend())): Qt5Agg
   - Python version: 3.7.3

**Comment by Jerry-Ma** [comment]
I can confirm that this error presents on macOS. My env:

   - Operating system: macOS: 10.14.5
   - Matplotlib version: 3.1.0
   - Matplotlib backend: Qt5Agg
   - Python version: 3.7.3

Screenshot:

<img width="784" alt="Screen Shot 2019-07-18 at 12 43 37" src="https://user-images.githubusercontent.com/2752708/61475861-bb3c8580-a959-11e9-93c3-200b57a4a3bd.png">

**Comment by lateral-gug** [comment]
I have the same problem on Windows.

**Comment by timhoffm** [comment]
@lateral-gug 
- Which version of Matplotlib are you using?
- Are you using screen scaling (e.g. 125% or 150%)?

**Comment by lateral-gug** [comment]
@timhoffm 
I'm currently using version 3.1.1, Python 3.7.4. I'm not using sceen scaling. The problem occurs when using the Qt5Agg backend, so for the animations I use TkAgg.

**Comment by timhoffm** [comment]
I cannot reproduce this with 3.3.2. @lateral-gug can you please try with this version?
