### ISSUE TITLE
The plot function of the matplotlib 2 and 3 versions is much slower than 1.5.3

### ISSUE THREAD

**Issue by materia9** [matplotlib/matplotlib#12542]
### Bug report

**Bug summary**

The plot function of the matplotlib 2 and 3 versions is much slower than the plot function of matplotlib 1.5.3 if one plots many lines (and other objects) in an Axes.

**Code for reproduction**

I have tested it on an Ubuntu server (CLI only), version 16.04 with python 3.5.2 (through virtualenv), matplotlib 1.5.3 with backend agg set by matplotlibrc. 

```python
setup="""import matplotlib.pyplot as plt
a=[1,2]"""
test="plt.plot(a,a,'-')"
import timeit
timeit.timeit(test,setup,number=1000)
# output: 0.6324263589922339
timeit.timeit(test,setup,number=1000)
# output: 0.6100882450118661
timeit.timeit(test,setup,number=1000)
# output: 0.6113728249911219
```
=> around 0.6-0.7 sec, it is stable for a few dozen times.

On the same machine & operating system, python 3.5.2 (through virtualenv), matplotlib 2.2.2 with backend agg. 

```python
setup="""import matplotlib.pyplot as plt
a=[1,2]"""
test="plt.plot(a,a,'-')"
import timeit
timeit.timeit(test,setup,number=1000)
# output: 0.9981246230890974
timeit.timeit(test,setup,number=1000)
# output: 1.3041282850317657
timeit.timeit(test,setup,number=1000)
# output: 1.6257964670658112
timeit.timeit(test,setup,number=1000)
# output: 1.9830634299432859
```
=> getting slower and slower...

Note that matplotlib 2.0.0, 2.0.1, 2.1.0, 2.1.2, 2.2.2, or 3.0.0 has the same slowdown behavior. If I set svg as backend, the result is the same as agg (I confirmed backend="svg" only for matplotlib 2.0.0 on the Ubuntu server). 

This behavior is also confirmed on a Windows distribution: WinPython-64bit-3.4.4.6Qt5 with matplotlib 2.0.0 and default backend TkAgg, but not for WinPython-64bit-3.4.4.5Qt5 with matplotlib version 1.5.3 and TkAgg, though the situation is much more complex. In addition, WinPython-64bit-3.5.1.1 and matplotlib 2.1.0 (packaged by Christoph Gohlke) causes the same slowdown behavior. 

Another windows distribution anaconda 3 version 4.4.0(64bit) also has a similar behavior. For the anaconda 3 environment, all the packages are default of the 4.4.0 distribution (python 3.6 and matplotlib 2.0.2 with backend qt5agg), and it runs on windows7-x64. 

If I close the figure by pyplot.close(), the slowed plot() is returned to the initial state. 

**Expected outcome**

The expected outcome is "no slowdown for the plot function of matplotlib 3" as the matplotlib version 1.5.3.

**Matplotlib version**
  * Operating system: Ubuntu 1604 (CLI only)
  * Matplotlib version: matplotlib 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.5.2
  * Jupyter version (if applicable): 
  * Other libraries: 

**Other note**

I have used a script to write huge maps with overlayed many lines drawn by plot(). When I'm with matplotlib 1.5.3, it takes several minutes to output a bunch of png files, but no fatal problem is there. However, with 2.0.0-3.0.0 it takes several hours or more, and I cannot use the script at all. 

I believe this slowdown behavior can occur for most of the matplotlib environments. I think this is not an OS/system dependent bug/specification.

**Comment by jklymak** [comment]
I agree your script slows down for me.  

OTOH, initializing a figure in your setup doesn't exhibit this slow down.  I'm not sure why this happens, but I'm not sure what your use case is.  

In general, I'd suggest not trying to use the state-based interface for the best performance... 

```python
setup="""import matplotlib.pyplot as plt
a=[1,2]
fig = plt.figure()
"""
test="plt.plot(a, a, '-')"
import timeit
timeit.timeit(test,setup,number=1000)
timeit.timeit(test,setup,number=1000)
timeit.timeit(test,setup,number=1000)
timeit.timeit(test,setup,number=1000)
timeit.timeit(test,setup,number=1000)
timeit.timeit(test,setup,number=1000)
```

**Comment by QuLogic** [comment]
> OTOH, initializing a figure in your setup doesn't exhibit this slow down. I'm not sure why this happens, but I'm not sure what your use case is.

But I think that's the point, since:

> If I close the figure by pyplot.close(), the slowed plot() is returned to the initial state.

On the other hand, drawing 4000 lines vs 1000 lines seems like it _should_ be slower to me, but is it _too much_ slower per line? I'm not sure, possibly, but I think a more interesting test is this:
```python
>>> setup="""import matplotlib.pyplot as plt
... a=[1,2]
... plt.close('all')
... """
>>> 
>>> test="plt.plot(a,a,'-')"
>>> import timeit
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=1)
>>> timeit.timeit(test,setup,number=10)
>>> timeit.timeit(test,setup,number=100)
>>> timeit.timeit(test,setup,number=1000)
>>> timeit.timeit(test,setup,number=10000)
>>> timeit.timeit(test,setup,number=100000)
>>> timeit.timeit(test,setup,number=200000)
```
which does not seem to scale so well in recent versions. Still waiting for 100000 with 3.0.0...

**Comment by QuLogic** [comment]
Oh, actually, 100000 count finished, so:
![figure_1-3](https://user-images.githubusercontent.com/302469/47070644-ae6ae580-d1bf-11e8-8deb-e6c74aac785a.png)
Looking at time per line (just time / number):
![figure_1-4](https://user-images.githubusercontent.com/302469/47071029-7dd77b80-d1c0-11e8-9d7b-90d1abb34149.png)
Ignoring 1 and 10 which are pretty noisy, 10000 lines is an order of magnitude slower, but at 100000 lines, it's two orders of magnitude slower per line. I don't know what's going on there.

**Comment by QuLogic** [comment]
More straightforward test, I think?
```python
import timeit

setup = """
import matplotlib.pyplot as plt
plt.close('all')
a = [1, 2]
"""
test = "plt.plot(a,a,'-')"

# Prime stuff
timeit.timeit(test, setup, number=10)

t1 = timeit.timeit(test, setup, number=1000)
t2 = timeit.timeit(test, setup, number=10000)
print(t1, t2, t2 / t1)
```
with results:
```
version	time1000		time10000		ratio
1.5.3	1.665212828986114	8.014447881025262	4.812867005057222
2.0.0	2.089658019016497	44.532892381976126	21.311091086059935
2.0.1	2.085433025000384	44.81260865801596	21.488395033931962
2.0.2	2.05447192498832	42.90871796300053	20.88552169591924
2.1.0	2.251952402002644	40.38666930099134	17.934068795182256
2.1.1	1.9482705270056613	38.53039746900322	19.776718343227937
2.1.2	2.0048703539941926	40.01708639998105	19.959937220008875
2.2.0	2.104869660019176	40.214108515006956	19.105272539602566
2.2.1	1.962975592003204	39.36644780100323	20.05447645980663
2.2.2	1.9735110830224585	39.55972639701213	20.04535304480068
2.2.3	1.9041270589805208	38.6958993919834	20.322120422311198
3.0.0	2.072705873986706	39.154758671997115	18.890648771446596
```
The base time went up slightly, but the main point is that the ratio is much higher now for some reason.

**Comment by QuLogic** [comment]
Ran an automated bisect with ratio=13 as good/bad threshold and it points to 9617dfef1f377760645b7986d3081cca34aa0805 as the first bad commit
```
commit 9617dfef1f377760645b7986d3081cca34aa0805
Author: Thomas A Caswell <tcaswell@gmail.com>
Date:   Tue Dec 8 13:09:10 2015 -0500

    Merge pull request #5583 from mdboom/padding
    
    API: Use data limits plus a little padding by default

:040000 040000 b905ec739efee2f8b0c4ebb14b46760497c30e6d a7b4c85793d0d175bee8582c91c7c625dc4d909e M	lib
:100644 100644 b4e602b846c5c1b360fede4fc3c2b16fd095b57d 604b1036d911e9522d67d35489dad897b94f4a85 M	matplotlibrc.template
```
which I guess might make sense as automated margins would require iterating through all artists.

**Comment by dstansby** [comment]
If anyone wants a fun project, this looks like a good excuse to dig up https://github.com/matplotlib/matplotlib/issues/2188 / https://github.com/airspeed-velocity/asv - there are some older results at https://matplotlib.org/mpl-bench/

**Comment by QuLogic** [comment]
I'm still waiting for them to accept the PR to enable it on NumPy's bench system...

**Comment by QuLogic** [comment]
A pretty generous speed up can be had by disabling autoscale and sticky edges before plotting, and then re-enabling them after:
```python
import matplotlib.pyplot as plt

a = [1, 2]

fig, ax = plt.subplots()
for _ in range(10000):
    ax.plot(a, a, '-')
```
```bash
$ time python ../mpl-tests/issue12542a.py 
real	0m39.860s
user	0m38.035s
sys	0m0.186s
```
vs.
```python
import matplotlib.pyplot as plt

a = [1, 2]

fig, ax = plt.subplots()
ax.autoscale(False)
ax.use_sticky_edges = False
for _ in range(10000):
    ax.plot(a, a, '-')
ax.use_sticky_edges = True
ax.autoscale(True)
```
```bash
$ time python ../mpl-tests/issue12542a.py 
real	0m7.476s
user	0m5.423s
sys	0m0.168s
```

**Comment by anntzer** [comment]
See #12546 for a small improvement.

**Comment by QuLogic** [comment]
#12547 is a related change insomuch as it helps if you've already disable autoscale, but it's orthogonal to @anntzer's change.

**Comment by jklymak** [comment]
Ooops, I see what the difference is now.  Sorry for the noise.

I think a todo here, asside from makig the autolim algorithm faster, is to have a Performance Tweaks page where we list potential performance blocks that will slow things down for folks who want to have thousands of artists, or a very responsive GUI.  Off the top of my head:

  - autolimits
  - "best" legend location
  - the layout managers

No doubt there are more.

**Comment by ImportanceOfBeingErnest** [comment]
Adding to the list (especially with respect to the actual topic here)

* Using **collections** instead of individual artists. I.e. a `LineCollection` instead of many `plot`s, a `PathCollection` or `PolyCollection` or even `Path.make_compound_path_from_polys` instead of a `bar` with many bars (like [here](https://stackoverflow.com/questions/52785611/how-can-i-specify-a-list-of-colors-for-rectangles-using-patches-pathpatch/52788179#52788179)), etc.

**Comment by anntzer** [comment]
One can squeeze out another ~30% percent or so by replacing the property access (artist.sticky_edges, sticky.x, sticky.y) by direct attribute/tuple access (artist._sticky_edges, sticky[0], sticky[1] (sticky is a namedtuple)), which I guess is a reasonable patch (with a comment explaining the performance implications) but really just a band-aid over a problematic design.

**Comment by materia9** [comment]
Thank you everyone. I now realize that the root cause of the problem at least for my case. Now I'm trying to use the options: `autoscale(False)` and `use_sticky_edges = False`. I'm a lazy programmer and thus I found this behavior (maybe a good programmer can solve the speed limitation completely and never realizes the problem). I think a performance tweak page will be a very good start point even for me.

**Comment by jklymak** [comment]
So is ti possible to delay `autoscale_view` to draw time?  Seems a straightforward solution.  

If that is not possible, could we accumulate `x_stickies` and `y_stickies` in `add_artist` and remove them in `artist.remove`?  Unless I'm misunderstanding, the problem is that making these lists from scratch every time a new artist is added is inefficient.

**Comment by tacaswell** [comment]
If we cache the sticky-ness, we need to track if it is updated on the artists.
