### ISSUE TITLE
more info on how to write backends?

### ISSUE THREAD

**Issue by BMaxV** [matplotlib/matplotlib#12553]
### Bug report / Request for more detailed information about backends

**Bug / summary**

I would like to write a backend. The information in backend_template.py is nice, but leaves me with lots of open questions. I'm prepared to do the leg work of research myself, but if someone has already done it and I haven't found it, I would appreciate a pointer in the right direction.

I can read the other backends for reference, but I would have to read a few to make sure whatever I learn isn't specific to the backend but something matplotlib needs.

**Expected outcome**

Ideally, a detailed descriptions of what matplotlib gives to the backend and what assumptions are made about backends. Tips, tricks for developing matplotlib in particular are welcome as well. Especially quicker testing than changing something, reinstalling, running the test, would be nice.

**other**

I want to write it for the panda3d rendering/game engine. So ideally I want the plots to end up either as some kind of texture to dress 3d objects with or somehow draw 2d on my screen or both. Maybe that's relevant.

**Comment by anntzer** [comment]
@BMaxV Any other specific questions not handled by #12554?  If not I'll close this.

**Comment by BMaxV** [comment]
No further questions at the moment.
