### ISSUE TITLE
Clean up unused imports

### ISSUE THREAD

**Issue by tkivisik** [matplotlib/matplotlib#12562]
### Bug report

There are 41 unused imports according to:
https://lgtm.com/projects/g/matplotlib/matplotlib/alerts/?mode=list

They should be removed.

**Matplotlib version** - latest from the master branch.

**Comment by tkivisik** [comment]
I will remove them.

**Comment by tkivisik** [comment]
Thank you for the warnings. In that case retract from claiming this for myself and I leave this up for someone with more intimate knowledge of the project.

When some eager person would like to take this on, which approach would make you confident that no necessary imports are removed?

**Comment by timhoffm** [comment]
I've removed some obviously unused imports.

As a rule of thumb:

- don't change imports in `pylab`
- it's mostly ok to remove module imports
- removing imported methods or classes require careful consideration (in particular in widely used namespaces like `matplotlib` or `pyplot`). For other namespaces it depends if this could be considered part of the public API.

**Comment by tkivisik** [comment]
Thanks for explaining the guidelines and removing unused imports.

**Comment by WeatherGod** [comment]
you'd be surprised by how many people can be impacted by the removal of a
third-party import. I remember seeing a bunch of bug reports when I changed
how basemap was importing pyproj. I kinda wish that there was some sort of
way to force all new packages to adopt `__all__` usage. Even I forget to
set it sometimes in my own projects. It is one of those things that doesn't
pay off right away, but is a huge "I wish I did that 10 years ago" kind of
thing.

**Comment by timhoffm** [comment]
`__all__` is just a very mild limitation. Basically, it

- excludes non-listed elements from a wildcard import
- defines the intention of a public interface (but essentially only visible to the reader of the source code)

As a result, most people won't notice the effect of `__all__` anyway (you shouldn't do wildcard imports anyway and a library user does usually not check the source code).

In particular `__all__` does neither prevent an explicit import nor does it exclude elements from `dir()` and thus completion.

For an explanation see e.g. http://xion.io/post/code/python-all-wild-imports.html
