### ISSUE TITLE
macOS builds are broken

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#12578]
The [most recent CRON build](https://travis-ci.org/matplotlib/matplotlib/jobs/444165618) from 11 hours ago has started failing on macOS. Can someone on macOS investigate this?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
```
I'm not sure if maybe https://github.com/Homebrew/homebrew-core/pull/33207 is related.

**Comment by QuLogic** [comment]
Travis uses homebrew, not conda.

However, it seems to have fixed itself. I don't see anything on homebrew's GitHub, but somebody must have done something.

**Comment by QuLogic** [comment]
This is broken again...

**Comment by jklymak** [comment]
Now its failing because it cannot download gcc (in a timely manner?).  Its a bit brutal that we have to download gcc everytime we run CI. Is that what it did before?

**Comment by dstansby** [comment]
I'm very confused as to why homebrew is downloading and installing numpy instead of pip?

**Comment by dstansby** [comment]
If we want to keep using brew numpy, my guess would be the problem is these lines in the build
```
==> Installing numpy dependency: openblas
==> Downloading https://homebrew.bintray.com/bottles/openblas-0.3.3.high_sierra.bottle.tar.gz
==> Pouring openblas-0.3.3.high_sierra.bottle.tar.gz
==> Caveats
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.
For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"
For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"
```
So I guess numpy is might not be finding openblas which is now required (https://github.com/Homebrew/homebrew-core/pull/33207)
