### ISSUE TITLE
Support for hierarchical labeling of bar-plots

### ISSUE THREAD

**Issue by louist87** [matplotlib/matplotlib#1257]
With the increasing popularity of the Pandas data-analysis library, more and more users can be expected to want to plot hierarchically organized data.

Below is an example of a Pandas dataframe:

```
Group Local Global Attn  mean
ASub  LD    GD     Attn    -0
                   Dist    -0
            GS     Attn    -0
                   Dist    -0
      LS    GD     Attn    -0
                   Dist    -0
            GS     Attn    -0
                   Dist    -0
DSub  LD    GD     Attn    -0
                   Dist     0
            GS     Attn    -0
                   Dist    -0
      LS    GD     Attn    -0
                   Dist    -0
            GS     Attn    -0
                   Dist    -0
```

(Note that the above `mean` column values are **not** zero, but very small floats)

And here is the resulting matplotlib.pyplot bar graph:
![Graphical representation of above data.  Note that the values are not zero, but extremely small floats](http://i.stack.imgur.com/z8qiG.png)

It would be nice, and I imagine relatively simple, to add support for hierarchical labeling of the x-axis.  For clarity, I mean that I should be able to create a tree-like structure of labels that shows how the left half of the bars belong to the `ASub` group, the left half of which belongs to the `LD` group of the `Local` parameter, etc...

Thoughts?

**Comment by anntzer** [comment]
I agree with @story645 that #6321 is a dupe, but I'll close this one as the other has what I believe is a clearer example graph.
