### ISSUE TITLE
Incorrect hist error message with bad color size

### ISSUE THREAD

**Issue by z0glen** [matplotlib/matplotlib#12580]
### Bug report

**Bug summary**

When the hist() function is provided data and color parameters that are of different sizes, the resulting error message is incorrect. The lengths of the two parameters are switched. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt

data = [[0, 1, 2], [3, 4, 5]]
colors = ['red']

plt.hist(data, color=colors)
```

**Actual outcome**

```
ValueError: color kwarg must have one color per data set. 1 data sets and 2 colors were provided
```

**Expected outcome**

```
ValueError: color kwarg must have one color per data set. 2 data sets and 1 colors were provided
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.0
  * Matplotlib backend: TkAgg
  * Python version: 3.6.5

**Comment by timhoffm** [comment]
Thanks for the report.
