### ISSUE TITLE
Matplotlib pypi distribution lacks packages for Python 2.7

### ISSUE THREAD

**Issue by capslockwizard** [matplotlib/matplotlib#12590]
### Bug report

**Bug summary**

Installation of a python module (https://github.com/capslockwizard/drsip) with pip fails because it attempts to installed matplotlib 3.0.0 which does not support Python 2.7.

This installation was performed on ReadTheDocs as part of building the documentation.

**Code for reproduction**

python setup.py install --force

**Expected outcome**

Downloads and installs matplotlib 2.2.3.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: -
  * Matplotlib backend (`print(matplotlib.get_backend())`): -
  * Python version: 2.7
  * Jupyter version (if applicable): -
  * Other libraries: -

**Comment by dstansby** [comment]
Could you post the exact command you are using to install Matplotlib, and the ouput of the command? There are py27 wheels for windows available (https://pypi.org/project/matplotlib/2.2.3/#files), so I'm not sure what's happening here.

**Comment by capslockwizard** [comment]
I have been trying to build documentation on read the docs for my python module (https://github.com/capslockwizard/drsip). During the build process it attempts to install my module (a Python 2 module) and Matplotlib as one of the dependencies but the installation fails because it is attempting to install Matplotlib 3.0.0.

My module does not actually use Matplotlib but one or more of my module's dependencies like MDAnalysis, SciPy or Pandas probably requires Matplotlib.

I was able to solve the problem by providing a pip requirements text file. I am not sure why it worked.

I have attached the logs of the successful build and failed build:
[successful_build.log](https://github.com/matplotlib/matplotlib/files/2504144/successful_build.log)
[failed_build.log](https://github.com/matplotlib/matplotlib/files/2504145/failed_build.log)

**Comment by QuLogic** [comment]
ReadTheDocs is not building on Windows, but Linux, though we have 2.2.3 wheels for that as well.

I don't understand how you solved it as both those logs are building the same version of your code.

**Comment by capslockwizard** [comment]
Sorry, my initial bug report is inaccurate. You are right, it shouldn't be on Windows.

The main difference between the successful and failed builds is this command: 
`python /home/docs/checkouts/readthedocs.org/user_builds/drsip/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/drsip/.cache/pip -r requires.txt`

The successful build installed the requirements first before performing:
`python setup.py install --force`

The requirements are also available in the setup.py file. So I have no idea why that would make a difference?

**Comment by capslockwizard** [comment]
I guess it is a more of a problem with pip rather than Matplotlib, so I will close the issue

**Comment by QuLogic** [comment]
Using `python setup.py install` is deprecated. I don't know how readthedocs steps are defined, but if you set it to do `pip install .` I suspect it will work fine.
