### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'artist'

### ISSUE THREAD

**Issue by staqiuddin** [matplotlib/matplotlib#12626]
### Bug report

**Bug summary**

I am unable to use Matplotlib due to an error when importing `matplotlib` or `matplotlib.pyplot`.

**Code for reproduction**

```python
import matplotlib.pyplot
```

**Actual outcome**

```
Traceback (most recent call last):

  File "<ipython-input-15-864e826dab68>", line 1, in <module>
    import matplotlib.pyplot

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 28, in <module>
    import matplotlib.artist as martist

AttributeError: module 'matplotlib' has no attribute 'artist'
```

**Expected outcome**

The import should work. It used to work before I updated some packages today. One of the updated packages is `qtpy` (1.5.1 -> 1.5.2). I am not sure if this is related or not.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.0
  * Matplotlib backend: Executing `print(matplotlib.get_backend())` fails.
  * Python version: 3.6.7

I installed `matplotlib` from Anaconda Python Distribution through the default channel.

**Code for getting Matplotlib backend**

```python
import matplotlib
print(matplotlib.get_backend())
```

**Full traceback**

```
Traceback (most recent call last):

  File "<ipython-input-18-0484cd13f94d>", line 1, in <module>
    import matplotlib

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar

  File "C:\Users\user\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 28, in <module>
    import matplotlib.artist as martist

AttributeError: module 'matplotlib' has no attribute 'artist'
```

Thank you.

**Comment by has2k1** [comment]
I have the same [error](https://travis-ci.org/has2k1/plotnine/jobs/445641074#L1069) on travis for plotnine. It started yesterday (25/10/19).

**Comment by StrikerRUS** [comment]
Confirm that. The problem has started yesterday for macOS Python 3.6. Later it has appeared on Windows Python 3.6. Seems that other OSs and Python versions are bug-free, so far.

**Comment by ImportanceOfBeingErnest** [comment]
I suppose this is fixed by https://github.com/matplotlib/matplotlib/pull/12604 ?

**Comment by tacaswell** [comment]
Yup, same issue.  CPython fixed a bug that we were relying on and we were not watching the rc's closely enough.  

Should have a release out in the next 24 hours to fix this!

**Comment by staqiuddin** [comment]
Thank you @tacaswell for your efforts and prompt reply. Kindly I would like to ask that once the aforementioned release is out, will I be able to update the package through conda?

Thank you.

**Comment by tacaswell** [comment]
That depends on down-stream packaging efforts (by Anaconda and conda-forge).  I suspect that it will be prompt in this case.

**Comment by SPScientist** [comment]
I am also facing the same issue today.
Please guide me.

**Comment by ImportanceOfBeingErnest** [comment]
@SPScientist This issue is fixed by #12604. Are you using matplotlib 3.0.1 and still see the issue?

**Comment by SPScientist** [comment]
@ImportanceOfBeingErnest , thank you for your feedback.
I could not able to import the mathplotlib ( even pandas ) also. 
Somehow installation on my machine got corrupted after installing some other python packages.
Finally it is working after uninstalling the existing setup and re-installing.

**Comment by agilebean** [comment]
For Jupyter Notebook users, this problem goes away if you update matplotlib to 3.0.1 *and restart the jupyter kernel.

**Comment by jg2345** [comment]
I have the same problem on a brand new install of pandas from Anaconda.  What should I do to fix it?

**Comment by samrudh** [comment]
> I have the same problem on a brand new install of pandas from Anaconda. What should I do to fix it?

Try :
conda uninstall matplotlib
and then :
conda install matplotlib

It solved the issue for me

**Comment by TdevSoft** [comment]
Upgrading matplotlib to 3.0.2 solved the issue.

**Comment by DFreeMind** [comment]
restart conda environment solved my issue

**Comment by cycnc35** [comment]
uninstall matplotlib and reinstall it and then restart anaconda environment

**Comment by SPScientist** [comment]
For me , it worked after re-installing the Matplotlib.

**Comment by Cheruiyotd** [comment]
It appears that if you are running several processes of python and you have imported matplotlib with different names(using import as) or you have imported modules that import matplotlib with different names you will encounter those errors

**Comment by NamraRehman** [comment]
`AttributeError: module 'matplotlib' has no attribute 'rcParams'`

facing this issue with version 3.3.4 

Solved the problem by downgrading the version to = 3.2.2

**Comment by haydraa** [comment]
i have the same problem 
version :1.6 vs code 
python version: 3.9 
what should i do

**Comment by WeatherGod** [comment]
All of these reports usually indicate a bad installation of matplotlib, or
a file named "matplotlib.py" was imported from somewhere instead of the
actual package.
