### ISSUE TITLE
Write canonical example of how to use Matplotlib inside a webserver

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#12628]
As shown by #11094 #12612 matplotlib is used inside of webservers to dynamically serve plots.  The example should show:

 1) importance of picking a non-GUI backend (both by setting the backend and explicitly by not using pyplot).  Given that these servers are multi-threaded, not using pyplot at all may be the best option to avoid any coupling between workers via pyplot and memory leaks due to pyplot holding references to figures forever.  Should probably show use of `new_figure_manager`
 2) saving to a bytesIO buffer to avoid disk
 2) png, svg, and pdf
 3) be applicable to both django and flask (not sure off the top of my head what the differences are), bonus points for cherrypy, aiohttp, tornado, and pyramid

**Comment by anntzer** [comment]
Rather than bothering with any explicit backend *at all*, I would strongly suggest merging #12450 and have the canonical approach be
```
from matplotlib.figure import Figure
fig = Figure()
<do the plotting>
fig.savefig(...)
```

**Comment by mgeier** [comment]
Possible duplicate: #4124.

**Comment by tacaswell** [comment]
Indeed!  I'm going to close the older one.

**Comment by anntzer** [comment]
Do you want to make a decision about #12450, by the way? :) (as noted above)

**Comment by anntzer** [comment]
@tacaswell I think something like
```
import base64
from io import BytesIO

from flask import Flask
from matplotlib.figure import Figure


app = Flask(__name__)


@app.route("/")
def hello():
    # Generate the figure **without using pyplot**.
    fig = Figure()
    ax = fig.subplots()
    ax.plot([1, 2])
    # Save it to a temporary buffer.
    buf = BytesIO()
    fig.savefig(buf, format="png")
    # Embed the result in the html output.
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return f"<img src='data:image/png;base64,{data}'/>"
```
is what you're looking for?

**Comment by story645** [comment]
My version was (stolen from a cookbook)
```python
 fig = matplotlib.figure.Figure()
 canvas = FigureCanvas(fig)
//plot to figure code
canvas.print_figure(responseBuffer)
```
where the outfile is the responsebuffer, like 
```python
response = pyramid.response.Response(content_type='image/png')
```

**Comment by anntzer** [comment]
- `canvas = FigureCanvas(fig)` is not necessary anymore since #12450 (that's the whole point of that PR).
- I prefer suggesting the use of `savefig` (and yes you can also pass the Response buffer to it), as it's a regular method that you'd also use in other contents, rather than `print_figure`, which is a bit an implementation detail.

**Comment by tacaswell** [comment]
Yes, something as simple as that is what I had in mind.

Agree on preferring `savefig` over `print_figure`.

**Comment by pjmnoble** [comment]
Hi problem goes away really nicely using the AGG backend
I just import matlplotlib at the top of my code and follow this with matplotlib.use('AGG') before importing any other matplotlib components (matplotlib.pyplot in this case)

No need for the matplotlib GUI backend in the web server.

Running on a Mac(High Sierra) with a Django server
