### ISSUE TITLE
Broken 'Developer Discussions' link

### ISSUE THREAD

**Issue by hershen** [matplotlib/matplotlib#12654]
### Bug report

Broken 'Developer Discussions' link at the bottom of README.rst.

I receive a 404 page not found error when I try to follow it.

**Comment by QuLogic** [comment]
It's not broken; it's private, because GitHub doesn't seem to have any other setting. But nothing actually happens there anyway.

**Comment by hershen** [comment]
I see, thanks. It's interesting that there's no indication that's the reason.
Is it worth mentioning it on README.rst?
