### ISSUE TITLE
In version 3.0.0 make_axes_locatable + colorbar does not produce expected result

### ISSUE THREAD

**Issue by dchandan** [matplotlib/matplotlib#12661]
### Bug report

**Bug summary**

In Matplotlib 3.0.0 using `make_axes_locatable` and `append_axes` functions to make a separate axis for colorbar does not function as it is supposed to.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
from mpl_toolkits.axes_grid1.colorbar import colorbar

fig, (ax1, ax2) = plt.subplots(1, 2)
fig.subplots_adjust(wspace=0.5)

im1 = ax1.imshow([[1, 2], [3, 4]])
ax1_divider = make_axes_locatable(ax1)
cax1 = ax1_divider.append_axes("right", size="7%", pad="2%")
cb1 = colorbar(im1, cax=cax1)

im2 = ax2.imshow([[1, 2], [3, 4]])
ax2_divider = make_axes_locatable(ax2)
cax2 = ax2_divider.append_axes("top", size="7%", pad="2%")
cb2 = colorbar(im2, cax=cax2, orientation="horizontal")
cax2.xaxis.set_ticks_position("top")

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/5779123/47624508-daf1fc00-daf3-11e8-96ea-a5bd95af3d93.png)

**Expected outcome**

From [matplotlib gallery](https://matplotlib.org/gallery/axes_grid1/demo_colorbar_with_axes_divider.html)

![image](https://user-images.githubusercontent.com/5779123/47624521-0248c900-daf4-11e8-91ad-cfdf24874df0.png)

**Matplotlib version**

  * Operating system: Mac OS Mojave
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

All packages installed from default conda channel.

**Comment by jklymak** [comment]
This is fixed 3.0.1.  Sorry for the bug.
