### ISSUE TITLE
plt.scatter crashes because overwrites the colors to an empty list

### ISSUE THREAD

**Issue by massich** [matplotlib/matplotlib#12664]
### Bug report

**Bug summary**
When doing scatter plot of `nan` values it crashes because the list of colors gets overwriten to an empty list by this line:

https://github.com/matplotlib/matplotlib/blob/c921e2ead5a9b8ea3dabf74c9aee3958eecfc01e/lib/mpl_toolkits/mplot3d/axes3d.py#L2317

**Code for reproduction**
We hit this bug in https://github.com/mne-tools/mne-python/pull/5676, but here is a MWE. Most probably this is a duplicated of #12641. In which case, this can be used as a test.

```py
import matplotlib.pyplot as plt
import numpy as np

n_points = 4
xs = ys = zs = np.full(n_points, np.nan)
colors = list(np.full(2, 'k'))
plt.scatter(xs, ys, zs, c=colors)
plt.show()
```

**Expected outcome**

(As in matplotlib 2.2.2) we would expect an empty plot with no error
```sh
In [25]: matplotlib.__version__
Out[25]: '2.2.2'

In [26]: %paste
import matplotlib.pyplot as plt
import numpy as np

n_points = 4
xs = ys = zs = np.full(n_points, np.nan)
colors = list(np.full(2, 'k'))
plt.scatter(xs, ys, zs, c=colors)
plt.show()
## -- End pasted text --

In [27]: 
```

**Actual outcome**
It breaks because cannot iterate over `c`

```sh
In [9]: matplotlib.__version__
Out[9]: '3.0.1'

In [10]: %paste
import matplotlib.pyplot as plt
import numpy as np

n_points = 4
xs = ys = zs = np.full(n_points, np.nan)
colors = list(np.full(2, 'k'))
plt.scatter(xs, ys, zs, c=colors)
plt.show()
## -- End pasted text --
Traceback (most recent call last):
  File "<ipython-input-10-f59e87d45c38>", line 7, in <module>
    plt.scatter(xs, ys, zs, c=colors)
  File "/home/sik/miniconda3/envs/mne/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2864, in scatter
    is not None else {}), **kwargs)
  File "/home/sik/miniconda3/envs/mne/lib/python3.6/site-packages/matplotlib/__init__.py", line 1805, in inner
    return func(ax, *args, **kwargs)
  File "/home/sik/miniconda3/envs/mne/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4234, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 2 elements, which is not acceptable for use with 'x' with size 4, 'y' with size 4.
```

**Comment by ImportanceOfBeingErnest** [comment]
Bisects to https://github.com/matplotlib/matplotlib/pull/11383; also relevant https://github.com/matplotlib/matplotlib/issues/11373.

The [scatter documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.scatter.html) is rather clear 
> `x, y` : array_like, shape (n, )
> `c` : color, sequence, or sequence of color, optional, default: 'b'
   The marker color. Possible values:
  [...]
   A sequence of color specifications of length n.

So I think it was never intended that `x` and `c` are of different length. (And that is independent if them containing nans, or not.) I think the fact that it worked in some previous version was just an implementation detail. Or is there an argument that the colors should be cycled through?

**Comment by massich** [comment]
I mess up the MWE. It was supposed to be this one:
```py
In [2]: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: 
   ...: n_points = 4
   ...: xs = ys = zs = np.full(n_points, np.nan)
   ...: colors = list(np.full(n_points, 'k'))
   ...: plt.scatter(xs, ys, zs, c=colors)
   ...: plt.show()
```
In that case, they are all the same and the tests passh. Which means that my MWE was wrong. I'll repoen if needed.

**Comment by massich** [comment]
Sorry it was needing to be 3D.

```py
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

n_points = 4
xs = ys = zs = np.full(n_points, np.nan)
colors = list(np.full(n_points, 'k'))
ax.scatter(xs, ys, zs, c=colors)
plt.show()
```

**Comment by massich** [comment]
@ImportanceOfBeingErnest Sorry I mess up the snipped, I think that the error is related to #11373. Feel free to close if the issue is irrelevant. Sorry for the noise.

**Comment by ImportanceOfBeingErnest** [comment]
The new 3D code with equal length lists bisects to https://github.com/matplotlib/matplotlib/pull/12431, which is the same PR that introduced the problem in https://github.com/matplotlib/matplotlib/issues/12641. So I guess we can close this.

**Comment by massich** [comment]
Thx.
