### ISSUE TITLE
Wrong discrete colorbar ticks in ImageGrid

### ISSUE THREAD

**Issue by zxdawn** [matplotlib/matplotlib#12662]
### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid
import numpy as np
import matplotlib

lon,lat = np.meshgrid(np.arange(-180, 180, 10), np.arange(-85, 90, 10))
data = np.sort(np.random.rand(18, 36),axis=1)

# Settings
bounds = [0,0.01,0.04,0.07,0.1,0.13,0.16,0.2,0.25,0.35,0.45,0.6,0.9]
colors = ['#390231','#7F1CAB','#0047FD','#0072FE','#019EFF','#00C4FF','#01EDFF',\
        '#00FFFB','#00FFC8','#29F905','#FBDD03','#FA0F00']

# Grid
fig = plt.figure()
grid = ImageGrid(fig, 111,
                nrows_ncols=(2, 1),
                axes_pad=(0.35, 0.35),
                label_mode="1",
                share_all=True,
                cbar_location="right",
                cbar_mode="each",
                cbar_size="5%",
                cbar_pad="6%",
                )

# Jet
p = grid[0].pcolormesh(lon,lat,data, vmin=0, vmax=0.9, cmap='jet')
cb = grid.cbar_axes[0].colorbar(p)

# Discrete
cmap = matplotlib.colors.ListedColormap(colors)
norm = matplotlib.colors.BoundaryNorm(bounds, cmap.N)
p = grid[1].pcolormesh(lon,lat,data, cmap=cmap, norm=norm)
cb = grid.cbar_axes[1].colorbar(p, ticks=bounds)

grid[0].set_title('jet')
grid[1].set_title('Defined')
plt.show()

# Subplots
f, (ax1, ax2) = plt.subplots(2, 1,sharex=True)

# Jet
p = ax1.pcolormesh(lon,lat,data, vmin=0, vmax=0.9, cmap='jet')
f.colorbar(p,ax=ax1)
ax1.set_title('jet')

# Discrete
p = ax2.pcolormesh(lon,lat,data, cmap=cmap, norm=norm)
f.colorbar(p,ax=ax2,ticks=bounds)
ax2.set_title('defined')

plt.show()
```

**Actual outcome**

![grid](https://user-images.githubusercontent.com/30388627/47624558-f93e1300-db58-11e8-832c-8d17ce85629b.png)

![subplots](https://user-images.githubusercontent.com/30388627/47624571-0e1aa680-db59-11e8-949d-20bcf8d7264a.png)

Location of colorbar ticks is wrong in ImageGrid, but correct in subplots.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.4
  * Other libraries: numpy(1.14.2) 

installed from conda

**Comment by ImportanceOfBeingErnest** [comment]
A workaround would be to set the labels manually.

```
bounds = [0,0.01,0.04,0.07,0.1,0.13,0.16,0.2,0.25,0.35,0.45,0.6,0.9]
ticks=np.linspace(bounds[0],bounds[-1], len(bounds))
cb = grid.cbar_axes[1].colorbar(p, ticks=ticks)
cb.ax.set_yticklabels(bounds)
```

![image](https://user-images.githubusercontent.com/23121882/47643327-65c20d80-db6b-11e8-8a53-055eb3a9d435.png)

I think `matplotlib.colorbar` has significantly diverged from `mpl_toolkits.axes_grid1.colorbar`. This behaviour goes back to before 1.5.3.

**Comment by oscargus** [comment]
In the current `main`, the following result is obtained for the first plot, so it seems to have been fixed along the way.
![image](https://user-images.githubusercontent.com/8114497/168786456-a05cfa7c-e325-4bd2-9b0d-9f020f1a90b9.png)

It would just be to add a test so that it is not reintroduced again.

**Comment by QuLogic** [comment]
As noted by @oscargus, all this needs is converting the reproducer into a test.

**Comment by jklymak** [comment]
I think this is fixed because image grid uses a normal colorbar now and I think this is tested for normal colorbars?
