### ISSUE TITLE
DOC: CL tutorial now saves png each time...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12677]
_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/12394#issuecomment-434404280_

It seems one drawback of this is that now every time you build the docs it'll create two png images in the tutorials folder, which will then end up in any commit (if one doesn't pay attention).

**Comment by jklymak** [comment]
... or if someone else wants to put the `savefig` statements into an if-False loop, that'd be fine.

**Comment by ImportanceOfBeingErnest** [comment]
I think my preferred solution would be either

* to turn the respective code blocks into rst blocks, such that they are not executed. 
* or to let the code execute, and link to the generated files, instead of those in `_static` (those can then be removed, such that there is no increase in doc size)
