### ISSUE TITLE
make_axes_locatable breaks with matplotlib 3.0

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#12671]
### Bug report

**Bug summary**
Matplotlib version 3 does not support adding axes from mpl tool kits like it did in version 1 and 2. 

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import matplotlib as mpl
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np

# Version
mpl.__version__
# '3.0.0'

# Data
t = np.linspace(0,2*np.pi)

fig, ax = plt.subplots()
ax.scatter(t,np.sin(t))

# Add extra ax doesn't work
divider = make_axes_locatable(ax)
ax_bottom = divider.append_axes("bottom", size="10%")
ax_bottom.scatter(t,np.cos(t), color="red")
```

**Actual outcome**
From version: `3.0.0`

![image](https://user-images.githubusercontent.com/9061708/47677804-5e0b6480-db7d-11e8-87bc-91665eb79665.png)

**Expected outcome**
From version: `2.2.3`

![image](https://user-images.githubusercontent.com/9061708/47677896-97dc6b00-db7d-11e8-82d2-b21d30a68f55.png)

**Matplotlib version**
  * Operating system:
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217

  * Matplotlib version: 
'3.0.0'
  * Matplotlib backend (`print(matplotlib.get_backend())`):
module://ipykernel.pylab.backend_inline
  * Python version:
3.6.6
  * Jupyter version (if applicable):
4.4.0
  * Other libraries: 

conda default channel

**Comment by jklymak** [comment]
This is fixed in 3.0.1.  Thanks...

**Comment by jolespin** [comment]
Awesome!  Now I can use the features from version 3.  Wasn't sure if people generally use the make_axes_locatable enough to catch the error so I posted it without a thorough search.

**Comment by jklymak** [comment]
`axes_grid1` is somewhat poorly covered in our tests, so changes that break it get missed sometimes.  

Actually, for your case above, I'd strongly suggest just using subplots, perhaps with `gridspec_kw={'height_ratios':[0.9, 0.1]}`, but maybe your case is more complicated...

**Comment by jolespin** [comment]
I've never tried gridspec options before but I usually use this for getting dendrograms with data tracks underneath like below.  For the most part the number of data tracks are known and in this case maybe gridspec would be a better option.  I will look into this. 

![image](https://user-images.githubusercontent.com/9061708/47682009-50a7a780-db88-11e8-903d-1fe14d959932.png)

**Comment by jklymak** [comment]
I imagine either would work fine.  But `subplots` *should* be better supported.

Right now the best reason to use `axes_grid1` is for axes with a set asepct ratio...
