### ISSUE TITLE
matplotlib ui in thread still blocked

### ISSUE THREAD

**Issue by ericyan71** [matplotlib/matplotlib#12680]
hello, I want use matplotlib to show some data in a loop for very long time, but I found matplotlib was blocked and loss reponse.

so I think if it is could be used in thread. here is my test code:

```python
    import time
    import threading
    import numpy as np
    from queue import Queue
    import matplotlib.pyplot as plt
    
    class Worker(threading.Thread):
        def __init__(self, q):
            threading.Thread.__init__(self)
            self.q = q
    
        def run(self):
            fig = plt.figure('bg', clear=True)
            ax = fig.subplots()
            while True:
                img = self.q.get()
                if img is None:
                    break
                ax.imshow(img)
                plt.show(block=False)
                print("x")
                plt.pause(0.01)     # blocked here
                print("y")
                while self.q.empty():
                    plt.pause(0.01)
                      
    
    def main():
        plt.ion()
        q = Queue()
        worker = Worker(q)
        worker.start()
    
        for f in range(10):
            img = np.random.randint(0, 255, size=(300,300,3)).astype(np.uint8)
            q.put(img)
            time.sleep(0.3)
    
        q.put(None)
        worker.join()
    
    
    if __name__ == '__main__':
        main()
```
I test it in pycharm, it run python code with an option:
![ericyan_matplotlib_git](https://user-images.githubusercontent.com/22901866/47763522-12cb9000-dcfc-11e8-8a21-521157414ff6.png)

when I uncheck "run with python console", it works well, but if check "run with python console", the matplotlib ui was dead and loss response.

I found it was blocked at `plt.pause(0.01)`, between `print("x")` and `print("y")`. I want to know how to solve this problem. thanks, or there are a best method to show data in a loop, thanks.

- Operating System: Windows 10 (64 bit)
- Matplotlib Version: 2.2.2  Qt5Agg
- Python Version: 3.6.5 (64 bit)
- pycharm

**Comment by QuLogic** [comment]
Most windowing toolkits expect to be run in the main thread. You will need to restructure so that any plotting does not occur in your worker thread.

If you need help with this, please try posting on [StackOverflow](https://stackoverflow.com/questions/tagged/matplotlib) or the [matplotlib users](https://mail.python.org/mailman/listinfo/matplotlib-users) mailing list, as this is not a bug.

**Comment by ericyan71** [comment]
I have solved the problem by using process instead of thread. thanks.
