### ISSUE TITLE
Plotting text on 3d axes before tight_layout() breaks tight_layout()

### ISSUE THREAD

**Issue by sjvrijn** [matplotlib/matplotlib#12687]
### Bug report

**Bug summary**

`plt.tight_layout()` does not work on 3d plots when adding text *before* the `tight_layout()` call, but does work when adding text after. Problem does not occur for 2d plot.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

def test1():
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    plt.title('tight_layout() first: correct layout')

    plt.tight_layout()
    ax.text(.5, .5, .5, s='some string')

    plt.show()


def test2():
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    plt.title('ax.text() first: wrong layout + UserWarning')

    ax.text(.5, .5, .5, s='some string')
    plt.tight_layout()

    plt.show()


test1()
test2()
```

**Actual outcome**

![test1](https://user-images.githubusercontent.com/8833517/47823693-b4d59180-dd69-11e8-8222-0fe4d15e8728.png)
![test2](https://user-images.githubusercontent.com/8833517/47823694-b4d59180-dd69-11e8-895a-0f954a5ed2c9.png)

```
D:\Python36\lib\site-packages\matplotlib\tight_layout.py:176: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  warnings.warn('Tight layout not applied. The left and right margins '
```

**Expected outcome**

Same behavior for both cases.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.0.1
  * Matplotlib backend (module://backend_interagg):
  * Python version: 3.6

**Comment by QuLogic** [comment]
CC @jklymak

Also, what is interagg?

**Comment by jklymak** [comment]
I would guess, w/o looking, that `a=text(); a.get_tightbbox()` doesn't return anything sensible for 3-D axes?

**Comment by timhoffm** [comment]
Indeed: `Bbox(x0=1130.7891891891893, y0=733.3340540540539, x1=1189.7891891891893, y1=743.3340540540539)` doesn't look reasonable to me.

~~~
def test2():
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    plt.title('ax.text() first: wrong layout + UserWarning')

    t = ax.text(.5, .5, .5, s='some string')
    print(t.get_tightbbox(c.get_renderer()))
    plt.tight_layout()

    plt.show()

test2()
~~~

A possible workaround is to reimplement `get_tightbbox` in `Text3D` and simply return `None`. This is the way `Axis3D` currently works: https://github.com/matplotlib/matplotlib/blob/ec6a45ad6489319b245d6777c975cf96f9be2ec8/lib/mpl_toolkits/mplot3d/axis3d.py#L460
