### ISSUE TITLE
Annotations get cropped out of figures saved with bbox_inches='tight'

### ISSUE THREAD

**Issue by jooh** [matplotlib/matplotlib#12699]
### Bug report

**Bug summary**

Annotations get cropped when saving figures with bbox_inches='tight'.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
# from https://matplotlib.org/gallery/text_labels_and_annotations/demo_annotation_box.html
exec(open('demo_annotation_box.py').read())
plt.savefig('test.png', bbox_inches='tight')
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1559987/47849299-f5b0c300-ddc8-11e8-9e02-bf1191219703.png)

**Expected outcome**
A crop that respects the bounding boxes of the annotations to the right.

**Matplotlib version**

  * Operating system: CentOS Linux release 7.5.1804 (Core)
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6
  * Jupyter version (if applicable): NA - but the same issue also appears in notebooks on jupyter 4.4.0 with the inline backend
  * Other libraries: conda 4.5.11 with the following environment spec:

```
conda list
# packages in environment at /home/jc01/anaconda3/envs/mpltest:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.56.2               h464dc38_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.0                      118  
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
matplotlib                3.0.1                h8a2030e_1    conda-forge
matplotlib-base           3.0.1            py36hc039c98_1    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.15.3           py36h1d66e8a_0  
numpy-base                1.15.3           py36h81de0dd_0  
openssl                   1.0.2p               h470a237_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       18.1                  py36_1000    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
python                    3.6.6                h5001a0f_3    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.5.0                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.2               hb1c47c0_0    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by jklymak** [comment]
This one goes back to v2.2.2   Not sure why these artists are not part of the layout...

**Comment by jklymak** [comment]
Neither `_AnnotationBase` nor `AnnotationBbox` have `get_tightbbox` nor `get_window_extent` defined, so the default is None, and `bbox_inches='tight'` ignores the artist.  

Its totally possible to add these methods to these classes, but its a bit of a project to do correctly.  

*However*, is there a good reason to use `AnnotationBbox` instead of `Annotation`?  ping @ImportanceOfBeingErnest  who seems to grok all the OffsetBbox use cases. I find the flexibility offered by these methods completely overwhelemed by the complexity of specifying them.

**Comment by ImportanceOfBeingErnest** [comment]
> However, is there a good reason to use AnnotationBbox instead of Annotation?

Well, if you want to annotate with text, `Annotation` is just as good as `AnnotationBbox(TextBox(...), ...)`. The purpose of `AnnotationBbox` is of course to create annotations with content other than text, like shapes, images, in fact arbitrary artists. I still find the text annotation in the example useful to show the easiest possible use case of that class.

Concerning the actual problem here, one may specify the `bbox_extra_artists` manually, 

```
plt.savefig('test.png', bbox_inches='tight', 
                 bbox_extra_artists=[a.offsetbox for a in [ab1, ab2, ab3, ab4]])

```
supposing all `AnnotationBbox`es have previously been named `ab1`, `ab2`, etc. 

I suppose  if implementing a `get_window_extent` one would also need to take into account the `.offsetbox`, `.arrow_patch` and the `.patch`. Should be feasible.

**Comment by jooh** [comment]
Thanks. bbox_extra_artists seems like a good workaround for now, although this won't work for inline plots in notebooks (here I just turn off the tight bbox with `%config InlineBackend.print_figure_kwargs={'bbox_inches':None}` and position the axes manually in the figure).

As for why I need image annotations - it's actually another workaround to support using images as tick labels, inspired by [this SO answer](https://stackoverflow.com/a/52426377/3375155). I use code like

```
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
arr_img = images[0,:,:,4]
imagebox = OffsetImage(arr_img, zoom=0.1, cmap='gray')
imagebox.image.axes = ax_im
ab = AnnotationBbox(imagebox, xy=(0,5),
                    xybox=(-40, 0),
                    xycoords=("axes fraction", "data"),
                    boxcoords="offset points",
                    box_alignment=(1, .5),
                    bboxprops={"edgecolor" : "w", "facecolor": "w"},
                    arrowprops=dict(linewidth=.5 * ax_im.yaxis.get_majorticklines()[0].properties()['linewidth'],
                                    arrowstyle='-'),
                    pad=0.,
                    annotation_clip=False)
artist = ax_im.add_artist(ab)
```
To generate something like

![test](https://user-images.githubusercontent.com/1559987/47911104-869ca280-de8c-11e8-9fd1-73bb402d9c95.png)


Note that by setting arrowstyle='-' the annotation arrow becomes a makeshift tick line (although the line doesn't quite reach the axis, annoyingly). If there is a less hacky way to achieve images as tick labels that would be even better. As far as I can tell tick labels are always text in matplotlib.

**Comment by jklymak** [comment]
Thats a pretty specialized plot - as you are doing, I'd expect to do a bit of manual placement in order to do something like that.... (Have you considered using the Notebook backend instead of inline?)

Of course, if someone wants to make `AnnotationBbox` more robust, I think that'd be great!

**Comment by jklymak** [comment]
Closing because its workings intended, but feel free to discuss further.  Thanks,
