### ISSUE TITLE
matplotlib.plot.show always blocks the execution of python script

### ISSUE THREAD

**Issue by pahome** [matplotlib/matplotlib#12692]
### Bug report

matplotlib.plot.show always blocks the execution of python script

**Code for reproduction**

I try plt.show(block=False) , it failed and appear in a small moment then close itself.

Code:
```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.show(block=False)
    print("---Plot graph finish---")
```

I try plt.draw() or interactive mode , it failed, too. Check the code below.

Code:
```

import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.draw()
    plt.show()
    print("---Plot graph finish---")
```
Above will block until I close it.

Code:

```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.ion()
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.draw()
    plt.show()
    print("---Plot graph finish---")
```
Above will appear nothing, or it appear and disappear very fast.

**Expected outcome**

I can keep the graph and still execute following code without closing the graph

**Matplotlib version**

```
user@ya:~/$ sudo pip freeze | grep matplotlib
matplotlib==2.2.3
user@ya:~/$ sudo pip -V
pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```
```
I only execute script in Ubuntu ex: user@ya: python xxx.py
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:    16.04
Codename:   xenial
```

**How to install matplotlib?**
pip install

**Comment by ImportanceOfBeingErnest** [comment]
First code: You need to put a blocking `show` after your print statement.

```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.show(block=False)
    print("---Plot graph finish---")
    plt.show()
```

Second code: `plt.show()` needs to come *after* the print statement, similar to the first code

```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.draw()
    print("---Plot graph finish---")
    plt.show()
```

Third code: You would want to turn interactive mode off again to keep the figure alive.

```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    plt.ion()
    plt.figure(figsize=(10, 10))
    plt.plot(range(5), lw=2, label='Real')
    plt.title('Prediction')
    plt.legend(loc="best")
    plt.draw()
    plt.show()
    print("---Plot graph finish---")
    plt.ioff()
    plt.show()
```

More options are listed in the answers to [this SO question](https://stackoverflow.com/questions/458209/is-there-a-way-to-detach-matplotlib-plots-so-that-the-computation-can-continue). 
If you need to run significant amount of code while having the figure open, you may run it inside the event loop or use threading. 

I will close this as there does not seem any actual problem with matplotlib involved. Feel free to reopen if you disagree, in which case a clearer problem description would be helpful.

**Comment by pahome** [comment]
@tacaswell  thanks for replying.
Is there any way to keep graph even if python script finished?

**Comment by ImportanceOfBeingErnest** [comment]
You cannot keep a computer program open after it has terminated. 
The solution is hence always to keep the script running.

**Comment by tacaswell** [comment]
> Is there any way to keep graph even if python script finished?

That is what `block=True` does.  

You can also run your script as `python -i my_script.py` which drops you into an interactive interpreter after your code is done.

**Comment by comperem** [comment]
> @tacaswell thanks for replying.
> Is there any way to keep graph even if python script finished?

Hello, I've wanted the same thing and [put together a simple example here](https://stackoverflow.com/a/56982302/7621907). My preferred development cycle is to run a python script at a bash command prompt, edit the script, re-run and so on.

@ImportanceOfBeingErnest is correct but the answer provided is not the only solution.

It is possible to run the python script, use multiprocessing to launch a separate process with the `matplotlib` plot, exit the originating python script and leave the `matplotlib` process still running. It's not typical because most occurrences where a second process is launched assumes you still want control or communication with that process. For plotting during debugging, I rarely (ever, really) need programmatic command or communcation with that plot process. You want the figure to remain interactive, so it must have it's own process that remains after the parent script is finished, so keep the plotting process alive but only as long as you want that plot. Close the plot window and you're done.

I've been using it for a few days and it fits in nicely with my code-plot-code-plot-code... development cycle.

**Comment by jklymak** [comment]
Many image viewers will update the image if it changes on file.  So I usually just leave the image file open in my image viewer and then resave  the image if I need to make a change.

**Comment by hitbuyi** [comment]
> Many image viewers will update the image if it changes on file. So I usually just leave the image file open in my image viewer and then resave the image if I need to make a change.
can you show a example of that? 

plot the figure and keep figure alive ,like what MATLAB does, many people need this feature

**Comment by jklymak** [comment]
If you want to keep the figure alive you need to keep the python interpreter alive. Ipython is the usual solution for this.

**Comment by tacaswell** [comment]
@hitbuyi Please see https://matplotlib.org/stable/users/explain/interactive.html

If you want to re-run a script repeatedly in the shell I suggest `%run -i path/to/file.py`

**Comment by comperem** [comment]
the interactive event loop documentation is not clear.

what does this means?

"if you configure the event loop integration"

where is an example where a plot is created, in interactive mode, that doesn't freeze, shows data correctly, and remains responsive despite python command prompt being free to accept new inputs

**Comment by comperem** [comment]
> @hitbuyi Please see https://matplotlib.org/stable/users/explain/interactive.html
> 
> If you want to re-run a script repeatedly in the shell I suggest `%run -i path/to/file.py`

hello @tacaswell,

I appreciate your inputs, but the interactive event loop documentation is not clear. there are a number of options and permutations. for example, what does this mean?

"if you configure the event loop integration"

an example would help. is there an example where a plot is created, in interactive mode, with the plot window that doesn't freeze, shows data correctly, and remains responsive to pan and zoom and also where the python command prompt is free to accept new inputs?

**Comment by rcomer** [comment]
I just do

```bash
$ ipython --matplotlib
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.
Installed tk event loop hook.
Using matplotlib backend: TkAgg

In [1]: %run basic_plot.py

In [2]: 

```
where in this case `basic_plot.py` contains

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([1, 2])
```

The plot is displayed, and I can interact with it.  I have the ipython command prompt as shown by `In [2]:` above.  Everything in the script's namespace is available to continue interacting with it.

I think that `ipython --matplotlib` is the same as using the `%matplotlib` magic after starting `ipython`.  I prefer it because I can make a bash alias rather than having to always remember to activate interactive mode after starting `ipython`.
