### ISSUE TITLE
semilogy with NaN prevents display of Title (cairo backend)

### ISSUE THREAD

**Issue by nbecker** [matplotlib/matplotlib#12701]
### Bug report
In the following code, when semilogy is fed data with NaN, the title does not appear.

**Bug summary**

**Code for reproduction**

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

x = np.array ([0, 1, 2, 3])
y = np.array ([10, np.nan, 8, np.nan])
fig, ax = plt.subplots(constrained_layout=True)#, sharex=True)
ax.semilogy (x, y, 'x-')
ax.set_title('test')
plt.show()

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: linux fedora 29
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://mplcairo.qt
  * Python version: 3.7.1
  * Jupyter version (if applicable):
  * Other libraries: 

 pip

**Comment by anntzer** [comment]
Took me a while to figure it out but it should be fixed in mplcairo master.  If you can build it yourself from the repo you can try it now, otherwise I'll upload new "nightly" wheels "soon".

**Comment by anntzer** [comment]
New wheels are up.  Closing, but feel free to ping me with additional issues.

**Comment by nbecker** [comment]
Thanks!  Can I pip install the update? (how?)

**Comment by nbecker** [comment]
Better now, but still has a problem.  If NaN is not removed, now some of the lines are not plotted (just the markers).  I'll have to make another test case to show it.

**Comment by anntzer** [comment]
I'll wait for your example then.

**Comment by anntzer** [comment]
@nbecker Still a problem? (https://github.com/matplotlib/matplotlib/issues/12701#issuecomment-435470376)
