### ISSUE TITLE
Wishlist: functionally linked twin axes

### ISSUE THREAD

**Issue by FilipDominec** [matplotlib/matplotlib#12734]
While there is an elegant option of ```twinx```/```twiny``` for plotting two curves with two independent x or y axes into a single plot, in science one sometimes faces a different task: plotting one curve on a dual axis  defined by a function. 

As an example this can be an optical spectrum with bottom x-axis showing the wavelength λ in nanometers and top x-axis photon energy _E_ in electronvolts. Note the functional dependence of these axes is nonlinear _E_=hc/λ. For publication, one also needs both axes to have nice, round and correctly positioned  numbers, so passing this functional dependence directly into an object like ```xaxisformatter``` is out of question.

I have implemented a solution that generates correct secondary x- or y-axes, also with the possibility of logarithmic option: 

**https://gist.github.com/FilipDominec/9101258e8ba979c715a28bc527a43961**

Since I consider this situation relatively common in scientific plotting, I suggest the 30-line long trick could be added to matplotlib for easier use by others. A real-life image featuring two pairs of functionally dependent axes follows:

![e7308db2-8977-11e6-8727-da0a48d46152](https://user-images.githubusercontent.com/511950/47963325-f2b50d00-e02a-11e8-8f0e-1ddafbe0e69f.png)

**Comment by ImportanceOfBeingErnest** [comment]
Yes, such feature is indeed useful. I think we came to the conclusion that using twin axes for it is not actually the best approach, since they are meant to contain different data altogether; while here, you have the same data, and just want a different scale for it. 

It was hence proposed in https://github.com/matplotlib/matplotlib/pull/11859 to add a `secondary_axes` function in order to be able to produce such plots. I suppose the plan is still to get this in in version 3.1.

@FilipDominec Since you have a clear usecase in mind here, it would sure be helpful if you could look through #11859 and see if this solves your case and if the example that comes with it is clear enough.

**Comment by FilipDominec** [comment]
@ImportanceOfBeingErnest It basically appears the same with the difference that my solution automatically uses the ```brentq``` solver to invert the passed function, so no extra burden is put on the end user. Feel free to pick from my 30-liner solution as much as you find useful.

**Comment by ImportanceOfBeingErnest** [comment]
The idea in https://github.com/matplotlib/matplotlib/pull/11859 is to really provide a different *scale*, not just place the ticks at different positions and label them accordingly. This requires to have a callable inverted function available. I think calling `brentq` repeatedly could become quite expensive. In addition scipy is currently not a dependency of matplotlib. Of course one could discuss whether scipy should become a dependency if there is a true benefit to be expected. I currently do not see this benefit here, but maybe I'm missing something important?

**Comment by FilipDominec** [comment]
I guess there is just negligible overhead of numerically finding root of a function 5-20 times per one plot, but   fully agree scipy should not be an dependency of matplotlib. On the other hand, I find it rather important to isolate the user from the internal mathematics of plotting. Maybe some 10-liner Newton or Brent root finding algorithm could be hard-coded in the plotting routine.
