### ISSUE TITLE
Incorrect license info in setup.py

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#12766]
setup.py currently contains the lines
```
classifiers = [
    <...>
    'License :: OSI Approved :: Python Software Foundation License',
    <...>
    ]
```
and
```
        license="BSD",
```
which are in contradiction with one another.  (Considering the actual contents of the LICENSE file, I think the second instance should be changed to `license="PSF"`.)
See also https://packaging.python.org/specifications/core-metadata/#license for the metadata spec.

**Comment by tacaswell** [comment]
Yeah, I have been reading licensing things for the last 30 minutes....
