### ISSUE TITLE
Cairo backend discards alpha channel for collections

### ISSUE THREAD

**Issue by joh** [matplotlib/matplotlib#12773]
### Bug report

The cairo backend ignores the alpha value of artists when rendering Collections such as PatchCollection.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('Cairo')
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
import numpy as np

circles = [plt.Circle((i,i), 1.0) for i in np.arange(10)]
col = PatchCollection(circles, alpha=0.5)
ax = plt.gca()
ax.add_collection(col)
ax.autoscale_view()
plt.savefig('test_cairo_alpha.png')
```

**Actual outcome**

![test_cairo_alpha_actual](https://user-images.githubusercontent.com/116013/48202782-17302280-e366-11e8-82bd-ad1e559a6d84.png)

**Expected outcome**
Expected output when using the default `Qt5Agg` backend:

![test_cairo_alpha_expected](https://user-images.githubusercontent.com/116013/48202787-1d260380-e366-11e8-952f-037c18ea4521.png)

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: master @ 4dbbd22095e32b77053aab403c442934f18ade71
  * Matplotlib backend (`print(matplotlib.get_backend())`): cairo
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
Thanks for #12774.
As a curiosity: why are you using the cairo backend?  Are you aware of my rewrite of that backend in https://github.com/anntzer/mplcairo?

**Comment by joh** [comment]
I'm using the cairo backend via FigureCanvasGTK3Cairo to embed some plots in Gtk3. I was not aware of your rewrite of that backend, will check it out :) are there plans to merge your port to matplotlib master?

**Comment by anntzer** [comment]
Not in the short term, as there are serious technical hurdles to doing that (mostly, the static linking of a recent c++ standard library).
