### ISSUE TITLE
Avoid decimals in Histogram Plot Python

### ISSUE THREAD

**Issue by ardiaz11** [matplotlib/matplotlib#12784]
Good Day,

I want to make a histogram plot in python, my dataframe has int64 values, but when i tried to make the plot this shows decimal values like this
(array([318410.,      0.,      0., 299533.,      0.,      0., 318040.,
             0.,      0., 321024.]),
 array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ]),
 <a list of 10 Patch objects>)

If i print the column to graph this only has int values, but when i graph the data this shows decimal values, and i dont want shows decimal values

dataStations.stations.value_counts()
4    321024
1    318410
3    318040
2    299533
Name: stations, dtype: int64

plt.hist(dataStations["stations"])
(array([318410.,      0.,      0., 299533.,      0.,      0., 318040.,
             0.,      0., 321024.]),
 array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ]),
 <a list of 10 Patch objects>)

**Comment by pharshalp** [comment]
Update: 
Quoting https://github.com/matplotlib/matplotlib/issues/2293#issuecomment-22502200
> The problem stems from an undocumented "feature" in numpy.histogram. It returns the histogram as ints if you don't normalize or use weights, but floats if you do. I took the route of just forcing everything to be a float so that matplotlib doesn't carry over this undocumented numpy "feature". This was also the most straightforward way to avoid problems with int division.

Since matplotlib 3.0 only supports Python 3, we no longer need to worry about int division issues. I took the liberty of postponing the int to float casting (only if stacked or density is set to True). With this approach, the returned hist values will remain ints if the data has dtype int and no weighting/stacking/density is used. Please see #12802

**Comment by jklymak** [comment]
@pharshalp I think the issue the user is having is not in the dtype of `n`, but in the value of the x-bins.  i.e. they want the bins to be centred on 1, 2, 3, 4.

@ardiaz11 did you try specifying the `bins` argument?  

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html

**Comment by pharshalp** [comment]
@jklymak 
may be I am interpreting the user's question incorrectly but I do think they are referring to the dtype of `n`.  If the user wants to have bins to be centred on 1, 2, 3, 4 then bin edges will need to be floating point numbers i.e. `bins=[0.5,1.5,2.5,3.5, 4.5]` so we can not expect `bins` to be of dtype `int`.

From the documentation ...
The  `bins` argument when given as a sequence refers to the bin edges...
> If bins is a sequence, gives bin edges, including left edge of first bin and right edge of last bin. In this case, bins is returned unmodified.

the returned variable `bins` also refers to bin edges
> bins : array
The edges of the bins. Length nbins + 1 (nbins left edges and right edge of last bin). Always a single array even when multiple data sets are passed in.

**Comment by ardiaz11** [comment]
Thank you for your answers.

I have updated the matplot library from the version 2.2.2 to 3.0.1 but the result is the same.
Before i used bins to specify the colum numbers but also the library is showing floating values.

From a date column i am separating the year,month, minutes, after using sort_index() the values don´t shows decimals, like this.
datos.Hour.value_counts().sort_index()
0     15467
1         1
3         2
4       159
5      1170
6     32088
7     41265
8     34747
9     41634
10    17950
11    40322
12    40720
13    40645
14    34616
15    17212
16    28183
17    25522
18    26957
19    12354
20    25648
21    29266
22    28783
23    27307
Name: Hour, dtype: int64

After i am graphing the Hour colum but the array shows decimal points, even if i use bins and density.
plt.hist(datos['Month'])
(array([0.11224487, 0.05066968, 0.07012231, 0.06937015, 0.09188156,
        0.09327912, 0.12428751, 0.10672094, 0.08338458, 0.10713018]),
 array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ]),
 <a list of 10 Patch objects>)

**Comment by pharshalp** [comment]
@ardiaz11 Could you please clarify what values you were expecting to be integers and not floating point numbers (`n` i.e. values of the histogram bins or `bins` i.e. the edges of the bins)?

 ```python
n, bins, pathes = plt.hist(datos['Month'])
```

**Comment by ardiaz11** [comment]
Hi Harshal,
I want in my chart integers values, the dataset only has integer values but when i use hist, the graphic shows float numbers, i sorted my dataset only to be sure the dataset only has integer numbers.

datos.Hour.value_counts().sort_index()
0 15467
1 1
3 2
4 159
5 1170
6 32088
7 41265
8 34747
9 41634
10 17950
11 40322
12 40720
13 40645
14 34616
15 17212
16 28183
17 25522
18 26957
19 12354
20 25648
21 29266
22 28783
23 27307
Name: Hour, dtype: int64

**Comment by jklymak** [comment]
`n` is either the number of counts in a bin, or some normalization of the number of counts.  You can argue that it should be integers for counts, and floats for the normalized counts, but it should have nothing to do with the dtype of the data being binned.

**Comment by ardiaz11** [comment]
Thank you Jody, now is a great graph. 
Thank you to all for your time.
