### ISSUE TITLE
Slider val attribute inconsistent data type

### ISSUE THREAD

**Issue by idraper** [matplotlib/matplotlib#12793]
### Bug report

**Bug summary**

The val attribute in the slider class is not consistent. If you select the slider it return type <numpy.float64>, but if you change it in the code it will be of type `<int>` or `<float>`, etc.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

fig, ax = plt.subplots()
slider = Slider(fig.add_axes([0.6, 0.03, 0.3, 0.03]), 'Test Slider', 0, 100, valfmt='%1i', valstep=1, color='w')

def slider_changed(i):
	print (type(slider.val))

slider.on_changed(slider_changed)

slider.set_val(10)
slider.set_val(10.5)

plt.show()
```
**Actual Output**
<class 'int'>
<class 'float'>
<class 'numpy.float64'>  # this appears when you select (click on) the slider

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.0.1
  * Matplotlib backend: TkAgg
  * Python version: Python 3.6.4
  * Jupyter version (if applicable): n/a
  * Other libraries: none in example

I installed using pip.

I understand why how val may need to change internally, but I think there should be a function `get_val` (similar to `set_val`) where you can specify the return type.

**Comment by anntzer** [comment]
I don't have a strong opinion about adding `get_val` (I guess it'd go well with `set_val`, and this way we avoid directly accessing the `.val` attribute (for which writing doesn't update the position...), but just to know, why do you care about the exact type?

**Comment by idraper** [comment]
I am using a slider to show a graph in time. I have a separate plot that also reflects changes in the slider. However, when the user is not selecting the slider, both plots continue to change. I am using the slider as a reference to keep the plots synced. I also do several operations on this value in other places in my code.

It is isn't a big issue, since I just convert it to an int object and the problem is solved, but I figured I'd let you guys know.

**Comment by dstansby** [comment]
I'm going to close this as won't fix. I think the output is reasonable above: it's returning the type of the variable you set the slider with. If this is still an issue, please leave a comment and I can re-open.
