### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jzyxbb** [matplotlib/matplotlib#12797]
### Bug report

The coordinate of result is wrong.The input is 
1 2
1 2
1.2
This code is for computing Larange.
Whatever the input is,the output is strange!
Thank you for everyone's help!
**Code for reproduction**
.

```python
import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
starttime = datetime.datetime.now()
xk=list(input('(x)').split())
fx=list(input('(fx)').split())
a=float(input('x'))
def Larange(x):
    LX = 0.0
    for i in range(len(fx)):
        t = float(fx[i])
        for j in range(len(fx)):
            if i != j:
                t *= (float(x)-float(xk[j]))/(float(xk[i])-float(xk[j]))
        LX += t
    return LX
Larange(a)
print('result:',Larange(a))
plt.scatter(a,Larange(a),c='blue',marker='s',s=100)
plt.text(a,Larange(a),s='result:('+str(a)+','+str(Larange(a))+')')
plt.plot(xk,fx)
j=0
while j<len(xk):
    plt.text(xk[j],fx[j],s='('+str(xk[j])+','+str(fx[j])+')')
    j+=1
plt.show()
endtime = datetime.datetime.now()
print('running time:',(endtime - starttime).seconds)
```

**Actual outcome**

![qq 20181112235936](https://user-images.githubusercontent.com/41759189/48359315-a5463900-e6d7-11e8-87c1-b20cc811b8e5.png)

**Expected outcome**
![qq 20181113000004](https://user-images.githubusercontent.com/41759189/48359330-ab3c1a00-e6d7-11e8-9271-2eaedf3711cd.png)

**Matplotlib version**

  * Operating system:win 10
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3.6
  * Jupyter version (if applicable):
  * Other libraries: pandas numpy

**Comment by tacaswell** [comment]
I think you are plotting your values as strings so they are being treated as categoricals.  The simplest fix is to convert your values to floats at the top (sorry for being brief, have to run).

**Comment by QuLogic** [comment]
> ```
> xk=list(input('(x)').split())
> fx=list(input('(fx)').split())
> a=float(input('x'))
> ```

Without knowing what this input is, we can't really reproduce this.

**Comment by jzyxbb** [comment]
> > ```
> > xk=list(input('(x)').split())
> > fx=list(input('(fx)').split())
> > ```
> 
> As @tacaswell guessed earlier, these two variables are lists of strings. They are being plotted as categories, not as numbers. You could input _any_ two space-separated values and the plot would look the same.
> 
> The only casting to float is on `x` and _within_ `Larange`, but if you want Matplotlib's plot to look like numbers, you'll need to cast the input the `plot`, `scatter`, and `text` as well (or do it once at the beginning.)

Yes,Thx,I use another  function to convert list to float ,the output is as same as I want!

**Comment by tacaswell** [comment]
Great!  I am going to close this, if you have more questions I suggest contacting the mailing list (matplotlib-user@python.org).

**Comment by jzyxbb** [comment]
OK，thx

蒋子艺
Ziyi Jiang，Student
电子工程学院（School of Electronic Engineering）
电子信息工程（Electronic information Engineering）
Xidian university

________________________________
