### ISSUE TITLE
pcolormesh in log polar coordinates

### ISSUE THREAD

**Issue by yoichi-kazama** [matplotlib/matplotlib#12803]
### Bug report

**Bug summary**

radius range setting does not work for pcolormesh() in log polar coodinates.

**Code for reproduction**

```python
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

r = np.geomspace(1, 100, num=10)
th = np.linspace(0, 360, num=50)
th = np.radians(th)
v = np.random.rand(len(r), len(th))

ax = plt.subplot(1, 1, 1, projection='polar')
ax.set_rlim(1, 100)
ax.set_rscale('log')
plt.pcolormesh(th, r, v)
```

**Actual outcome**

![pcolormesh_polar](https://user-images.githubusercontent.com/44988698/48429415-11906d80-e7a8-11e8-9972-3565c1663ece.png)

**Expected outcome**

I think the pixels should spread to the outer edge of the circle, and no warnings should be shown.

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.6
  * Jupyter version (if applicable): Jupyterlab 0.34.1
  * Other libraries: 

Python, jupyterlab numpy and matplotlib were installed with conda.

**Comment by dstansby** [comment]
I suspect this is the same bug as https://github.com/matplotlib/matplotlib/issues/24383 - I think it will be easier to fix https://github.com/matplotlib/matplotlib/issues/24383 first (there's an even simpler example of radial log scale that doesn't work there), then come back to this issue and see if it's fixed as a side effect.
