### ISSUE TITLE
Issue with minor tick spacing in colorbar with custom Normalize class

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#12808]
### Bug report

**Bug summary**

Minor ticks don't appear in the right place in colorbars when a custom Normalize class is used.

**Code for reproduction**

The following example requires [astropy](http://www.astropy.org). If needed I can try and provide an example that doesn't use this.

```python
import numpy as np
import matplotlib.pyplot as plt
from astropy.visualization import LogStretch, ImageNormalize, PercentileInterval

data = np.arange(256).reshape((16, 16))

norm = ImageNormalize(data, interval=PercentileInterval(99), stretch=LogStretch())

plt.rcParams['xtick.minor.visible'] = True

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
im = ax.imshow(data, norm=norm)
cb = fig.colorbar(im)
fig.savefig('test.png')
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/314716/48497051-4bef1e80-e82b-11e8-919d-a6bdcff03004.png)

**Expected outcome**

The minor ticks should respect the spacing of the current stretch.

I noticed that using LogNorm, the ticks used to be spaced incorrectly in Matplotlib 2.2 but this was fixed in Matplotlib 3.0. However, the minor ticks are still broken for custom normalizations as shown above.

**Matplotlib version**

  * Operating system: MacOS X 10.13.6
  * Matplotlib version: 3.0.1
  * Matplotlib backend: Agg
  * Python version: 3.7.1

**Comment by jklymak** [comment]
Did this ever work?  Making axes work for random normalizations is non-trivial, and probably requires some under-the-hood manipulation of scales....

**Comment by astrofrog** [comment]
Just to be clear, it does work for major ticks, just not minor ticks.

It probably never worked for minor ticks, so it's not a regression, but it does seem like a bug compared to the expected behavior.

Just out of curiosity, since this does work for the major ticks, I'm curious why it would be difficult to extend this to minor ticks? (that is, the machinery is already in place for major ticks?).

If there is a reason this would be challenging, I wonder whether one solution would be to extend the code here:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L490

to allow Normalize sub-classes to provide their own custom locators?

**Comment by astrofrog** [comment]
It does seem like there is a minor tick auto-locator:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L1222

But for some reason this isn't working here (I tried calling ``minorticks_on``)

**Comment by jklymak** [comment]
OK, so this is basically an issue with the fact that there are no arbitrary norms/scales allowed for axes at present.  A few have been made to work (LogNorm, SymLogNorm, etc), but the general solution hasn't been done. 

In this case I assume the best outcome would be a stretched axes, with the major tick marks appearing to be constant in space, and minor ticks between, like a Log norm is presently handled.  Thats not possible and would require adding to the axis API.

I'm going to close this in lieu of #12665 which boils down to the same issue, but its an excellent use case of the same functionality discussed there.  I think we can/should try and add this, as also discussed in #11859 

Thanks!
