### ISSUE TITLE
cannot import name rcParams

### ISSUE THREAD

**Issue by simon-r** [matplotlib/matplotlib#1280]
I've tried this demo from your website:
http://matplotlib.org/api/widgets_api.html?highlight=matplotlib.widgets#matplotlib.widgets.RectangleSelector

But at the moment of runnig your program I've this error:

 File "rec.py", line 1, in <module>
    from matplotlib.widgets import  RectangleSelector
  File "/usr/lib/python3.2/site-packages/matplotlib/**init**.py", line 105, in <module>
    import os, re, shutil, subprocess, sys, warnings
  File "/usr/lib/python3.2/subprocess.py", line 378, in <module>
    import select
  File "/home/simone/spz/select.py", line 1, in <module>
    from pylab import *
  File "/usr/lib/python3.2/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/lib/python3.2/site-packages/matplotlib/pylab.py", line 222, in <module>
    from matplotlib import mpl  # pulls in most modules
  File "/usr/lib/python3.2/site-packages/matplotlib/mpl.py", line 1, in <module>
    from matplotlib import artist
  File "/usr/lib/python3.2/site-packages/matplotlib/artist.py", line 6, in <module>
    from matplotlib import docstring, rcParams
ImportError: cannot import name rcParams

I'm using the GIT version with python 3 under ArchLinux.
But I've observed the same problem with matplotlb 1.1.1 on python 2

**Comment by WeatherGod** [comment]
Ah, you seem to have some sort of name collision going on. you have a
module called `dis.py`, which is taking precedence over the standard
library module of the same name. Now, this shouldn't be happening in
python3.5. Could you double-check which version of python you are running?

**Comment by pluviosilla** [comment]
I'm getting the same error under very similar circumstances (importing matplotlib pyplot with a failure in the attempt to load colorbar, then martist, then rcParams), but I do not have dis.py or any other python (.py) files in my working directory. However, I think (but am not sure) that the problem started after I installed statsmodels. I'm running a jupyter notebook within a conda environment with python 3.6 and matplotlib-3.0.2-py36_1002.

**Comment by WeatherGod** [comment]
without seeing your traceback, we can't determine if there is some other
file that is getting caught up in the import tree.

**Comment by pluviosilla** [comment]
Thanks for taking time to respond. Here's the  traceback:

After the import
`from matplotlib import pyplot as plt `
I get
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-52-99ba79ecbbfb> in <module>
----> 1 from matplotlib import pyplot as plt

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\pyplot.py in <module>
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 import matplotlib.image
     34 from matplotlib import rcsetup, style

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\colorbar.py in <module>
     26 
     27 import matplotlib as mpl
---> 28 import matplotlib.artist as martist
     29 import matplotlib.cbook as cbook
     30 import matplotlib.collections as collections

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\artist.py in <module>
      8 
      9 import matplotlib
---> 10 from . import cbook, docstring, rcParams
     11 from .path import Path
     12 from .transforms import (Bbox, IdentityTransform, Transform, TransformedBbox,

ImportError: cannot import name 'rcParams'

```

**Comment by WeatherGod** [comment]
That is really strange. Those items should be coming from
site-packages/matplotlib/__init__.py. Can you check that that file is valid
in your install?

**Comment by pluviosilla** [comment]
How can I verify that it is valid? You can view the file [here](https://drive.google.com/open?id=1gyfp6rF6UKm1jeqjcJ0MxAPIddobwz0d).

**Comment by jklymak** [comment]
@pluviosilla Can you do

```python
import logging
logging.basicConfig(level=logging.DEBUG)
import matplotlib.pyplot as plt
```

Its just that your install is messed up somehow - running the debugging will help us see how.

**Comment by pluviosilla** [comment]
Nothing changes, unfortunately:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-53-ebf44ebd011b> in <module>
      1 import logging
      2 logging.basicConfig(level=logging.DEBUG)
----> 3 import matplotlib.pyplot as plt

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\pyplot.py in <module>
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 import matplotlib.image
     34 from matplotlib import rcsetup, style

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\colorbar.py in <module>
     26 
     27 import matplotlib as mpl
---> 28 import matplotlib.artist as martist
     29 import matplotlib.cbook as cbook
     30 import matplotlib.collections as collections

C:\Anaconda3\envs\py36-keras\lib\site-packages\matplotlib\artist.py in <module>
      8 
      9 import matplotlib
---> 10 from . import cbook, docstring, rcParams
     11 from .path import Path
     12 from .transforms import (Bbox, IdentityTransform, Transform, TransformedBbox,

ImportError: cannot import name 'rcParams'
```

**Comment by pluviosilla** [comment]
And changing the debugging level has no effect on the amount of spew.

**Comment by jklymak** [comment]
That means that you do not have a recent matplotlib installed in `C:\Anaconda3\envs\py36-keras`  Try updating.

**Comment by pluviosilla** [comment]
These problems occur in a newly created conda environment where I installed matplotlib in the usual way:
`conda install matplotlib -n py36-keras`
After experiencing all these difficulties I tried uninstalling and reinstalling as well as:
`conda install matplotlib -c conda-forge -n py36-keras`

Versions: python 3.6 and matplotlib-3.0.2-py36_1002.

**Comment by jklymak** [comment]
Does conda really install in `C:\Anaconda3` on Windows?  What does `conda info` give you?

You can also try:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
import matplotlib
print('Version', matplotlib.__version__)
import matplotlib.pyplot as plt
```

**Comment by pluviosilla** [comment]
Here's what I get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-4ac91ebc2005> in <module>
      2 logging.basicConfig(level=logging.DEBUG)
      3 import matplotlib
----> 4 print('Version', matplotlib.__version__)
      5 import matplotlib.pyplot as plt

AttributeError: module 'matplotlib' has no attribute '__version__'
```

As for my conda installation info, here's what I get:

```
C:\WINDOWS\system32>conda info

     active environment : None
       user config file : C:\Users\John\.condarc
 populated config files : C:\Users\John\.condarc
          conda version : 4.6.2
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\John\.conda\pkgs
                          C:\Users\John\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\John\.conda\envs
                          C:\Users\John\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False

```

**Comment by jklymak** [comment]
The fact you can't even print the `__version__` means your install is broken. 

I'd clean up your conda install - in particular, I don't think you want the `C:\Anaconda3` path in there, but I'm not an expert on how conda works on Windows machines.

**Comment by pluviosilla** [comment]
I don't think the "Anaconda3" is the problem. Been using that for ages and never had this kind of problem before. 

I have a number of conda environments. Maybe too many.

**Comment by WeatherGod** [comment]
Actually, could you print out `matplotlib.__file__`?

**Comment by jklymak** [comment]
@pluviosilla If you are still having trouble, probably worth opening a new issue.  But please make sure its not a conda problem first, which this really seems to be.  We can't really debug install issues.

**Comment by MorganWeiss** [comment]
I still have the same issue, is there any solution. I tried uninstalling and installing matplotlib but I still get the same error message: ImportError: cannot import name 'rcParams' from 'matplotlib' (unknown location)

**Comment by kvamsi7** [comment]
> I still have the same issue, is there any solution. I tried uninstalling and installing matplotlib but I still get the same error message: ImportError: cannot import name 'rcParams' from 'matplotlib' (unknown location)

Have you tried `conda install -f matplotlib`

**Comment by dentalfloss1** [comment]
I have this issue and I don't have anaconda at all
