### ISSUE TITLE
ArtistAnimation only draws the final legend

### ISSUE THREAD

**Issue by jwkvam** [matplotlib/matplotlib#12833]
### Bug report

**Bug summary**

`ArtistAnimation` only draws the final legend.

**Code for reproduction**

```python
fig, ax = plt.subplots()
a = ax.plot(range(5))
la = ax.legend(a, 'a')
b = ax.plot(range(1, 6))
lb = ax.legend(b, 'b')
arts = [[a[0], la], [b[0], lb]]
anim = ArtistAnimation(fig, arts)
```

**Actual outcome**

![legend](https://user-images.githubusercontent.com/86304/48686295-0d7d9a80-eb70-11e8-8951-026ebdf2fa15.gif)

**Expected outcome**

I expected the legend to appear in both frames.

If I change the order of the legends:

```
arts = [[a[0], lb], [b[0], la]]
```

Then the final legend is drawn on the first frame.

![legend2](https://user-images.githubusercontent.com/86304/48686680-1f603d00-eb72-11e8-9a46-8713abb1ff57.gif)

**Matplotlib version**
  * Operating system: MacOS Mojave
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.7.0
  * Jupyter version (if applicable): JupyterLab 0.35.4
  * Other libraries: 

I installed matplotlib with conda through conda-forge.

**Comment by QuLogic** [comment]
The problem is that there can be only one Axes legend (`Axes.legend_`), so the second time you add one, it just replaces the first. There _can_ be two Figure legends (though you have to specify a few more placement options), so you can do it like this:
```python
fig, ax = plt.subplots()
a = ax.plot(range(5))
la = fig.legend(a, 'a', loc='upper left',
                bbox_transform=ax.transAxes, bbox_to_anchor=(0, 1))
b = ax.plot(range(1, 6))
lb = fig.legend(b, 'b', loc='upper left',
                bbox_transform=ax.transAxes, bbox_to_anchor=(0, 1))
arts = [[a[0], la], [b[0], lb]]
anim = ArtistAnimation(fig, arts)
```

**Comment by jwkvam** [comment]
That's awesome! Thanks for the solution, works great!
