### ISSUE TITLE
\right) becomes ! when used together with sumation in latex strings

### ISSUE THREAD

**Issue by juergspaak** [matplotlib/matplotlib#12834]
the string
r"$\left( \sum_{i=1}^n \right)$"
is not formated properly by matplotlib axis labeling (or plt.text either).
The last symbol should be a big ")", however is a "!". The problem seems to be caused by \sum_{i=1}^n, as it does not occur in other combinations. (see script below).

here's code for reproduction
import matplotlib.pyplot as plt

plt.plot(range(5))
plt.xlabel(r"$\left( \sum_{i=1}^n \right)$", fontsize = 16)
plt.ylabel(r"$\left( 100 \right)\left(\sum_{i=1}^n\right]$", fontsize = 16)

Here's the output of the above code.
[bugreport.pdf](https://github.com/matplotlib/matplotlib/files/2594179/bugreport.pdf)

The y-axis is formated correctly, not however the x-axis (! should be a ). 

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 1.5.3
  * Matplotlib backend : module://ipykernel.pylab.backend_inline
  * Python version: '3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'

matplotlib was installed via conda

**Comment by QuLogic** [comment]
I cannot reproduce this with Matplotlib 2.2.3; can you try updating?

**Comment by juergspaak** [comment]
updated and works fine, thanks

**Comment by QuLogic** [comment]
This is actually a duplicate of #5210 and was only "fixed" by the change of default font.
