### ISSUE TITLE
matplotlib.rc_file resets to default template before updating rcparams

### ISSUE THREAD

**Issue by JackCaster** [matplotlib/matplotlib#12836]
### Bug report

**Bug summary**
`matplotlib.rc_file` reverts to the default template before updating rcparams.

**Code for reproduction**
```python
import matplotlib as mpl
import matplotlib.pyplot as plt

plt.style.use("seaborn-darkgrid")
mpl.rc_file('mpl_style.txt')
plt.plot(1)
```
where `mpl_style.txt` contains
```
font.size : 28
```
**Actual outcome**
![image](https://user-images.githubusercontent.com/18400141/48715801-217bd780-ec16-11e8-88ee-e3e39986e4d0.png)

**Expected outcome**
If instead we swap the order of the commands (first we update the rcfile and then we apply the style) then it works.
```python
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rc_file('mpl_style.txt')
plt.style.use("seaborn-darkgrid")

plt.plot(1)
```
![image](https://user-images.githubusercontent.com/18400141/48715819-2e003000-ec16-11e8-8a77-69b71af8edd3.png)

The workaround, right now, is to use `matplotlib.rcParams.update(matplotlib.rc_params_from_file('mpl_style.txt', use_default_template=False))`. I guess an option like `use_default_template=False` should be included in `matplotlib.rc_file` as well.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: matplotlib 3.0.2 (conda)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6

**Comment by timhoffm** [comment]
Even though the docstring "Update rc params from file." is not very clear about this matter. Using the term "update" may be interpreted that parameters not defined in the file are kept.

The function has always based the loaded file on the default rcparams. I propose not to change the behavior, but clarify the docstring. We may additionally introduce a kwarg `use_default_template=True`.
