### ISSUE TITLE
How to change the background color of an insert figure?

### ISSUE THREAD

**Issue by dustyHz** [matplotlib/matplotlib#12857]
When I create an insert axes in the main plot, I would like to change its axis background.
But when I apply `ax.figure.set_facecolor('b')`, it changes the background of the main plot.
So the question may be how could we set the figure handle to a new axes insert the main plot?

In details, to change the color of the background of a figure, we will use:
```
import matplotlib.pyplot as plt
fig = plt.figure()
fig.set_facecolor('b')
```
and then we get a figure like:
![image](https://user-images.githubusercontent.com/45228525/48841041-8d824b00-ed90-11e8-8f18-1fc04167328c.png)

It's different from the code `ax.set_facecolor('b')` which will set the face color of axes:
![image](https://user-images.githubusercontent.com/45228525/48841130-d2a67d00-ed90-11e8-9fb5-3da5ec9aa03f.png)

Now, when we creat an insert axes in the main plot:
```
import matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_axes([0,0,1,1])
ax2 = plt.axes([0.2, 0.6, 0.4, 0.3])
```
![image](https://user-images.githubusercontent.com/45228525/48841295-4fd1f200-ed91-11e8-8c64-d738acfefa9d.png)

We want to change the background color of the new insert axes.
If we use the order `ax2.figure.set_facecolor('r')`, it actually change the background color of the main plot:
![image](https://user-images.githubusercontent.com/45228525/48841401-a3444000-ed91-11e8-9d35-2ed5269f03dc.png)

So how could we solve this problem?

**Comment by QuLogic** [comment]
`ax.figure` gives you the `Figure` (namely, `fig` again). If you want to change the colour of the `Axes`, then use `ax.set_facecolor`.

Your terminology is a bit confusing though, so if you mean something else, please clarify.

**Comment by dustyHz** [comment]
> `ax.figure` gives you the `Figure` (namely, `fig` again). If you want to change the colour of the `Axes`, then use `ax.set_facecolor`.
> 
> Your terminology is a bit confusing though, so if you mean something else, please clarify.



> `ax.figure` gives you the `Figure` (namely, `fig` again). If you want to change the colour of the `Axes`, then use `ax.set_facecolor`.
> 
> Your terminology is a bit confusing though, so if you mean something else, please clarify.

Thank you for your reply. I have re-edit the question to make it more clear.

**Comment by jklymak** [comment]
Ax2.set_facecolor not what you are after?

**Comment by QuLogic** [comment]
> We want to change the background color of the new insert axes.

The "background" of the inset `Axes` is the space between the spines. There is no concept in Matplotlib of a background of the `Axes` + the ticks. When you set the colour of `ax.figure`, that's changing the `Figure` colour, not the `Axes` "background", and it appears behind the tick labels because they are transparent. But this colour would be there even if there were no `Axes` at all!

As @jklymak says, you would need to get the bounding box of the `Axes` _and_ the ticks using `get_tightbbox`, and then add a `Rectangle` patch under the inset.

**Comment by QuLogic** [comment]
Try using `Axes.inset_axes` instead.

**Comment by dustyHz** [comment]
> Try using `Axes.inset_axes` instead.

Yeah, it works. Thanks|!

**Comment by story645** [comment]
Closing as it seems the issue has been resolved, please reopen if that's not the case.

**Comment by JohannesBuchner** [comment]
I could not get this solution to work when the inset is over or outside the main axis, because I cannot paint a rectangle there.
