### ISSUE TITLE
evince misrenders some pdf bar plots

### ISSUE THREAD

**Issue by laborleben** [matplotlib/matplotlib#12864]
This is a regression in matplotlib 2.x.x. The bug does not exist in matplotlib 1.5.x.

### Bug report

**Bug summary**

When using some special numbers matplotlib.bar() is missing y-ticks and corresponding y-tick labels.

**Code for reproduction**

```python
arr = np.array([3765, 3792], dtype=np.int32)
plt.bar([0, 1], arr)
plt.yscale('log')
```

**Actual outcome**

<img width="518" alt="bildschirmfoto 2018-11-22 um 15 45 51" src="https://user-images.githubusercontent.com/8696773/48909507-bdebe700-ee6d-11e8-9147-36feb8605f61.png">

**Expected outcome**

<img width="502" alt="bildschirmfoto 2018-11-22 um 16 03 02" src="https://user-images.githubusercontent.com/8696773/48910446-466b8700-ee70-11e8-9821-3aba89e4df45.png">

**Matplotlib version**
  * Operating system: macOS/Ubuntu
  * Matplotlib version: 2.2.3 (conda install matplotlib)
  * Matplotlib backend: MacOSX/Qt5Agg
  * Python version: Anaconda 2.7

### Bonus

Plotting issues with Evince 3.18.2 in Ubuntu 16.04. The bars are upside down depending on the zoom level.

Zoom level: 140%
![screenshot_2018-11-22_16-11-16](https://user-images.githubusercontent.com/8696773/48911028-e70e7680-ee71-11e8-97f8-eed017217c06.jpg)

Zoom level: 170%
![screenshot_2018-11-22_16-11-41](https://user-images.githubusercontent.com/8696773/48911039-f1307500-ee71-11e8-9602-8ce339abf235.jpg)

**Comment by anntzer** [comment]
The ticking issue is already open as #8768 (especially https://github.com/matplotlib/matplotlib/issues/8768#issuecomment-308965501), but the pdf/evince issue is new.  I can't repro using okular (also using poppler as rendering backend) or mupdf or zathura(mupdf) or acroread, so I think it's a bug in evince, but heh.
(Also pdfs generated by mplcairo do not appear to expose this issue.)

**Comment by laborleben** [comment]
Yes, that's true, I couldn't reproduce the PDF displaying issue anywhere else beside Evince.

**Comment by laborleben** [comment]
Thanks for linking #8768. I was wondering no else found this bug before me :-)

**Comment by anntzer** [comment]
Relabeled the issue to focus on the evince problem as the ticker problem is already tracked elsewhere.

**Comment by laborleben** [comment]
Maybe for very small ranges change locator:

```python
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np

arr = np.array([0.0333, 0.03], dtype=np.float32)
plt.clf()
plt.bar(range(len(arr)), arr)
plt.yscale('log')
base_exponents = np.unique(np.floor(np.log10(plt.ylim())))
msb_digits = np.floor(plt.ylim() / (10**np.floor(np.log10(plt.ylim())))).astype(np.int)
if (base_exponents.size == 1 or np.abs(np.diff(base_exponents))[0] < 1) and np.count_nonzero(np.bincount(msb_digits)) < 3:
    ax = plt.gca()
    ax.yaxis.set_major_locator(locator=ticker.NullLocator())
    ax.yaxis.set_minor_locator(locator=ticker.AutoLocator())
```

This at least puts some numbers on the y-axis.

**Comment by laborleben** [comment]
```python
plt.tight_layout()
```
or
```python
plt.savefig("test.pdf", bbox_inches="tight")
```
fixes the displaying of the tick labels.

**Comment by anntzer** [comment]
Closing as I think the remaining issue belongs to evince (https://gitlab.gnome.org/GNOME/evince/issues/1056) and I don't think there's anything else to do on Matplotlib's side.
