### ISSUE TITLE
Feature request: show bars in plt.hist

### ISSUE THREAD

**Issue by rosgori** [matplotlib/matplotlib#12874]
### Feature request

**Summary**

With the new style of plotting (after version 1.5), you cannot distinguish the bars on `plt.hist`.  Take for example the old way:

```python
import matplotlib.pyplot as plt
import random

l_n = []
for _ in range(2000):
    l_n.append(random.betavariate(5, 25))

with plt.style.context('classic'):
    plt.hist(l_n, bins=20)
    plt.show()
```

Unfortunately, I cannot upload images. Nevertheless, you can see the bars. Now, this:

```python
plt.hist(l_n, bins=20)
plt.show()
```

You only see the silhouette of the histogram, not the bars. An easy way to solve this:

```python
plt.hist(l_n, bins=20, edgecolor='w')
plt.show()
```

`edgecolor='w'` would be the default option (I would prefer white because it looks good with all the styles). What do you think?

 By the way, if you want to compare with other software, I think all of them show bars. And a quick search [shows](https://www.google.com/search?q=histogram&num=50&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjVi47amOzeAhUHuVkKHYdhA8wQ_AUIDigB&biw=1366&bih=672)...

**Matplotlib version**

  * Operating system: Ubuntu 16.04.5 LTS
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6
  * Jupyter version (if applicable): 7.1.1
  * Other libraries: 
 * How I installed matplotlib: conda

**Comment by jklymak** [comment]
`plt.hist(l_n, bins=20, edgecolor='w')` works fine, so are you asking that this be the default?  I'd not particularly support that.  On the other hand maybe a `hist.edgecolor` rcparam could be considered (I didn't see one, though you can `patch.force_edgecolor`.

**Comment by anntzer** [comment]
Discussed https://github.com/matplotlib/matplotlib/pull/12493 as well.

**Comment by timhoffm** [comment]
I agree that bars in histograms should be visually separate. The current default behavior is not good.

A hard coded default `edgecolor='w'` can break styles.

Rcparams `patch.edgecolor` and `patch.force_edgecolor` are too global in their scope.

Therefore a `hist.edgecolor` rcparam is the reasonable way to go.
