### ISSUE TITLE
Clipping not working

### ISSUE THREAD

**Issue by henningpohl** [matplotlib/matplotlib#12900]
### Bug report

I'm trying to clip plotting to only a certain region. But I find that using the clip_box parameter doesn't seem to do anything.

**Code for reproduction**

```python
import numpy as np
from matplotlib.transforms import Bbox
import matplotlib.pyplot as plt

x = np.random.uniform(-1, 1, 200)
y = np.random.uniform(-1, 1, 200)

plt.figure()

plt.scatter(x, y, clip_on=True, clip_box=Bbox.from_extents(0, 0, 1, 1))

plt.xlim(-1, 1)
plt.ylim(-1, 1)

plt.show()
```

**Actual outcome**

![figure_1](https://user-images.githubusercontent.com/1923681/49098812-10634400-f270-11e8-9afb-13b9c2c43f0c.png)

**Expected outcome**

Only points inside one quadrant should be shown

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 2.2.3 (installed via conda)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.5

**Comment by henningpohl** [comment]
Something like `Bbox.from_extents(0, 0, 0.5, 0.5)` doesn't do anything either.

**Comment by henningpohl** [comment]
I can do some clipping if I configure it _after_ the `scatter` call:
```
sc = plt.scatter(x, y)
sc.set_clip_on(True)
sc.set_clip_box(Bbox.from_extents(0, 0, 1, 1))
```
However, now everything is clipped. This does seem to be a coordinate system thing, though. If I change the clip to `sc.set_clip_box(Bbox.from_extents(0, 0, 200, 200))` all but the points in the lower-left corner are clipped. But I have no idea what units are used there.

**Comment by ImportanceOfBeingErnest** [comment]
Neither `clip_box`, nor `clip_path` seem to be working when using as argument to a plotting function. This definitely needs some further investigation. 

An option to obtain a clipped artist in data coordinates is to use the `clip_path`. In this case

```
import numpy as np
import matplotlib.pyplot as plt

x = np.random.uniform(-1, 1, 200)
y = np.random.uniform(-1, 1, 200)

fig, ax = plt.subplots()

sc = ax.scatter(x, y, clip_on=True)

rect = plt.Rectangle((0,0), 1,1, transform=ax.transData)
sc.set_clip_path(rect)

ax.set(xlim=(-1, 1), ylim=(-1, 1))
plt.show()
```

Or if wanting to use a bounding box, one needs to transform it to screen coordinates as well.

```
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.transforms import Bbox, TransformedBbox

x = np.random.uniform(-1, 1, 200)
y = np.random.uniform(-1, 1, 200)

fig, ax = plt.subplots()

sc = ax.scatter(x, y, clip_on=True)

box = TransformedBbox(Bbox.from_extents(0,0,1,1), ax.transData)
sc.set_clip_box(box)

ax.set(xlim=(-1, 1), ylim=(-1, 1))
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/49103173-f67b2e80-f27a-11e8-814c-f0e785df5d7c.png)

Note however that setting the clip_box/path overwrites the clipping by the axes. So with other limits set one would get something like this

![image](https://user-images.githubusercontent.com/23121882/49103664-45759380-f27c-11e8-94cc-87bb2a84d71a.png)

Not sure if that is expected.

**Comment by henningpohl** [comment]
That would do the trick. Thanks! I guess it would be nice if the transformation were an explicit parameter that could be specified. So something like:
```
ax.scatter(x, y, clip_on=True, clip_box=Bbox.from_extents(0, 0, 1, 1), clip_transform=ax.transData)
```

**Comment by ImportanceOfBeingErnest** [comment]
Isn't the problem that, as mentionned earlier,

> Neither clip_box, nor clip_path seem to be working when using [it] as argument to a plotting function.

?

**Comment by anntzer** [comment]
Unless I'm mistaken, it looks like indeed, either clip_box should work as a kwarg, or that kwarg should not exist; at least it should not silently do nothing.

**Comment by jklymak** [comment]
Oops, sorry, misread the above.

**Comment by dopplershift** [comment]
Might be related to #8270, where `add_artist` is unconditionally calling `set_clip_path`.
