### ISSUE TITLE
Slightly missaligned horizontal line

### ISSUE THREAD

**Issue by jakobjakobson18** [matplotlib/matplotlib#12942]
### Bug report

**Bug summary**

In interactive windows and in png images horizontal lines are aligned by its lower edge and not by the center of the line. In pdf images however it looks fine.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 2*np.pi, 100)
fig, ax = plt.subplots()
ax.plot(x, 0.01*np.sin(x))
ax.axhline(0, 1, 0)
plt.savefig("Pdf_HorizontalLine.pdf")
plt.savefig("Png_HorizontalLine.png")
plt.show()
```

**Actual outcome**

[Pdf_HorizontalLine.pdf](https://github.com/matplotlib/matplotlib/files/2652654/Pdf_HorizontalLine.pdf)
![png_horizontalline](https://user-images.githubusercontent.com/43045863/49577939-e46b5100-f948-11e8-9829-0db44fa746c5.png)

**Expected outcome**
The horizontal line is also in the png file aligned by the center of the line and not by the lower edge.

**Matplotlib version**

  * Operating system: CentOS 7.7.1810 (Core)
  * Matplotlib version: 3.0.2 (via pip)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6
  * Jupyter version (if applicable): not used
  * Other libraries:

**Comment by jakobjakobson18** [comment]
If you don't consider this a bug, I'll close it.

**Comment by jklymak** [comment]
Well it’s being discussed in #12934 so let’s close here, but feel free to chime in there.
