### ISSUE TITLE
matplotlib cannot plot after tensorflow training in anaconda3 - kernal die

### ISSUE THREAD

**Issue by Garfield-kh** [matplotlib/matplotlib#12953]
### Bug report

**Bug summary**
I am new to python, I met a problem that after tensorflow training in anaconda. the plot function will make my kernal die.
I tried simle plot, which is working.
but either [https://github.com/MorvanZhou/Tensorflow-Tutorial/blob/master/tutorial-contents/302_simple_classification.py](url) or [https://www.tensorflow.org/tutorials/keras/basic_regression](url); The anaconda kernal will die in both Jupyter notebook and spyder.
I tried reinstall the system. or change the version to previous matplot. It still fail.

The whole process I did is: 
1. a new mac os system. 
2. download anaconda. 
3. create a environmen. python 3.6 or 3.7. 
4. install the package <tensorflow> <keras> <matplotlib>. 
5. in the environment I cteated, install jupyter and spyder. 
6. copy the example code and run. 
7. kernal die at the moment when I do plot.

I also tried this code, which is working.
`
import numpy as np
import matplotlib.pyplot as plt

x = np.random.randn(100)
plt.plot(x)
plt.show()
`

Did anyone met same problem as mine?

Thank you.

**Matplotlib version**

  * Operating system: Macbook pro OS, Anaconda3-5.3.1
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7
  * Jupyter version (if applicable): 5.7.2
  * Other libraries: tensorflow 1.12.0

**Comment by jklymak** [comment]
The fact that Matplotlib works makes it hard to see if this is matplotlib’s problem, or one of the other packages you are using in the examples.  Do you get a stack trace or any other console output?  Can you simplify the examples to the point where you can reproduce the error with as little extra code as possible?    We’d like to help, but there is not much to go on here.

**Comment by Garfield-kh** [comment]
Thank you for your reply.
I was thinking it might be the problem of python 3.7; which is the default version after I install anaconda3 on Macbook.
But the problem wasn't solved when I try environment with python 3.6.
Eventually the problem was solved by deleting the whole anaconda3 folder, and copy an older version from friend.

Thank you! Through I haven't find out where the problem is. XD
