### ISSUE TITLE
3.0.2: docstring of matplotlib.tri.Triangulation:40:toctree references unknown document 'api/matplotlib.tri.Triangulation.edges'

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#12963]
Hello,
when building 3.0.2 documentation, with sphinx 1.7.9, i got this error:

```
Warning, treated as error:
matplotlib/tri/triangulation.py:docstring of matplotlib.tri.Triangulation:40:toctree references unknown document 'api/matplotlib.tri.Triangulation.edges'
```

(well, technically it's a warning, but you set `-W` to sphinx, so all warning are treated as errors).

for now i'm going to remove the `-W`, but it'd be good if you could have a look at actually fix the underlying issue

thanks!

**Comment by sandrotosi** [comment]
full list of warnings:

during "reading sources" phase:
```
matplotlib/tri/triangulation.py:docstring of matplotlib.tri.Triangulation:40: WARNING: toctree references unknown document 'api/matplotlib.tri.Triangulation.edges'
matplotlib/tri/triangulation.py:docstring of matplotlib.tri.Triangulation:40: WARNING: toctree references unknown document 'api/matplotlib.tri.Triangulation.neighbors'
```

during "writing outputs" phase:
```
doc/api/index.rst:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.edges'
doc/api/index.rst:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.neighbors'
matplotlib/tri/triangulation.py:docstring of matplotlib.tri.Triangulation:46:<autosummary>:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.edges'
matplotlib/tri/triangulation.py:docstring of matplotlib.tri.Triangulation:46:<autosummary>:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.neighbors'
doc/contents.rst:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.edges'
doc/contents.rst:: WARNING: toctree contains reference to nonexisting document 'api/matplotlib.tri.Triangulation.neighbors'
```

**Comment by QuLogic** [comment]
The [doc backport branch](https://circleci.com/workflow-run/d584b75c-b348-47e9-b10e-19125e9923e0) as well as the [patch branch](https://circleci.com/workflow-run/b937a668-71cd-4cea-8401-007db0bf606a) built fine with Sphinx 1.8.2, so I think this must be fixed?

**Comment by sandrotosi** [comment]
we still dont have sphinx 1.8 in our development environment (it's been packaged so hopefully "soon"), but since the doc deps state `sphinx>=1.3,!=1.5.0,!=1.6.4,!=1.7.3,!=1.8.0` and it seems sphinx 1.8 is required to build the documentation correctly nowdays, maybe it's time to update those requirements? thanks

**Comment by dstansby** [comment]
Looks like our doc deps are updated, and this works fine with Sphinx >= 1.8.1, so I'll close this, feel free to comment/re-open if it's still an issue.
