### ISSUE TITLE
cannot import name cbook on matplotlib (2.2.3)

### ISSUE THREAD

**Issue by algila** [matplotlib/matplotlib#12978]
I should not use matplotlib. 
At the code line `import matplotlib.pyplot as plt`  I get the following error when I run my code from terminal or from Jupyter. But if I run my code in PyCharm community 2018.3 no issues at all 

### Bug report
ImportError: cannot import name cbook

**Code for reproduction**

```python
# import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
#
#
```

**Actual outcome**

```
#
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-4b1d03186b9b> in <module>()
      1 import numpy as np
      2 import pandas as pd
----> 3 import matplotlib.pyplot as plt
      4 import seaborn as sns
      5 import lightgbm as lgb

/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py in <module>()
    124 # cbook must import matplotlib only within function
    125 # definitions, so it is safe to import from it here.
--> 126 from . import cbook
    127 from matplotlib.cbook import (
    128     _backports, mplDeprecation, dedent, get_label, sanitize_sequence)

ImportError: cannot import name cbook
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: ubuntu 18.04 LTS
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 2.7
  * Jupyter version (if applicable): 1.0
  * Jupyter-cliet 5.2.3
  * Jupyter-console 5.2.0
  * Jupyter-core 4.4.0
  * Other libraries: 
absl-py (0.2.2)
asn1crypto (0.24.0)
astor (0.7.1)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0.post1)
bleach (1.5.0)
ccsm (0.9.13.1)
certifi (2018.8.24)
chardet (3.0.4)
cloudpickle (0.5.3)
compizconfig-python (0.9.13.1)
configparser (3.5.0)
contextlib2 (0.5.5)
cryptography (2.1.4)
cycler (0.10.0)
Cython (0.28.5)
dask (0.18.1)
decorator (4.3.0)
dnspython (1.15.0)
entrypoints (0.2.3)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.2.0)
gast (0.2.0)
grpcio (1.13.0)
h5py (2.8.0)
html5lib (0.9999999)
idna (2.6)
imgaug (0.2.6)
ipaddress (1.0.17)
ipykernel (4.8.2)
ipython (5.8.0)
ipython-genutils (0.2.0)
ipywidgets (7.4.0)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
Keras (2.2.4)
Keras-Applications (1.0.6)
Keras-Preprocessing (1.0.5)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.0.1)
lightgbm (2.2.2)
lxml (4.2.4)
Markdown (2.6.11)
MarkupSafe (1.0)
matplotlib (2.2.3)
mistune (0.8.3)
mock (2.0.0)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (2.1)
notebook (5.6.0)
numpy (1.15.4)
olefile (0.45.1)
pandas (0.23.4)
pandocfilters (1.4.2)
pathlib (1.0.1)
pathlib2 (2.3.2)
pbr (4.1.0)
pexpect (4.6.0)
pickleshare (0.7.4)
Pillow (5.1.0)
pip (9.0.3)
prometheus-client (0.3.1)
prompt-toolkit (1.0.15)
protobuf (3.6.0)
ptyprocess (0.6.0)
pycairo (1.16.2)
pycrypto (2.6.1)
Pygments (2.2.0)
pygobject (3.26.1)
pyparsing (2.3.0)
python-dateutil (2.7.5)
pytz (2018.7)
PyWavelets (0.5.2)
pyxdg (0.25)
PyYAML (3.13)
pyzmq (17.1.2)
qtconsole (4.3.1)
requests (2.19.1)
scandir (1.9.0)
scikit-image (0.14.0)
scikit-learn (0.20.0)
scipy (1.1.0)
seaborn (0.9.0)
SecretStorage (2.3.1)
Send2Trash (1.5.0)
setuptools (40.6.2)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
subprocess32 (3.5.3)
termcolor (1.1.0)
terminado (0.8.1)
testpath (0.3.1)
toolz (0.9.0)
tornado (5.1)
tqdm (4.28.1)
traitlets (4.3.2)
urllib3 (1.23)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.31.1)
widgetsnbextension (3.4.0)
xgboost (0.81)

**Comment by algila** [comment]
Hi,
in PyCharm where it is working the print output is  `/usr/bin/python2.7`
in Jupyter and in terminal where it is NOT working the print output is` /usr/bin/python`

**Comment by mueslo** [comment]
Are you sure you are running Python 2.7? The only reason cbook would not be there is if you have matplotlib 2.x and 3.x installed side by side for Python 3.

**Comment by tacaswell** [comment]
It looks like you are hitting different python interpreters and the installation is broken in `/usr/bin/python` but not `/usr/bin/python2.7`

**Comment by timhoffm** [comment]
I don‘t think we can help here further.

**Comment by zhemaituk** [comment]
More for awareness. It seems this `cannot import name cbook` issue is quite common, check the number of upvotes:
https://stackoverflow.com/questions/46651581/importerror-cannot-import-name-cbook-when-using-pycharms-profiler


Same happened for me on a fresh installation (RHEL env):
```
...
  File "/opt/myapp/news_ml/python/LFs/keywords/lda_keyword_generator.py", line 13, in <module>
    from matplotlib import pyplot as plt
  File "/opt/myapp/python-site/lib/python2.7/site-packages/matplotlib/__init__.py", line 126, in <module>
    from . import cbook
ImportError: cannot import name cbook
```

Downgrade to 2.0.2 worked like a charm.

**Comment by tacaswell** [comment]
@zhemaituk How did you install?

In the linked SO issue it looks like they have crossed conda and pip installations.

**Comment by zhemaituk** [comment]
@tacaswell 
Installed on clean RHEL 7.5 (with its out-of-the-box Python 2.7.5).
Under service account user (not root):
`pip install --user matplotlib==2.2.4`

On SO it's rather the answer, which is helpful to a few people. I found that thread by symptoms/error message, and the solution helped, even though a reason was different I believe.

**Comment by tacaswell** [comment]
It looks like there is some interaction between the underlying enviroment and `--user`.  Downgrading to 2.0.2 may fix the problem because either matches the underlying matplotlib version or shadows it better.

If you look in `/opt/myapp/python-site/lib/python2.7/site-packages/matplotlib` is there a cbook?

In general, I do not expect `--user` to work (due to both overlays and if you do start to use environments you can complied extensions from a different version of cpython).

**Comment by urstrulykkr** [comment]
I have gone through all the docs. Nothing is helping out with the issue. I think while installing and uninstalling the matplotlib might have corrupted the core modules or directories in 
`/usr/local/lib/python2.7/dist-packages/`

**Comment by tacaswell** [comment]
@urstrulykkr if you are doing `sudo pip ...` you run a right risk of corrupting your system as your system package manager and pip will conflict with each other.
