### ISSUE TITLE
set_position doesn't work on Axes added using inset_axes in matplotlib 3.0.2

### ISSUE THREAD

**Issue by Laukei** [matplotlib/matplotlib#12985]
### Bug report

**Bug summary**

Axes added using Axes.inset_axes() in matplotlib 3.0.2 don't respond visually to Axes.set_position().

**Code for reproduction**

```python
import matplotlib.pyplot as plt

# an example using regular axes
fig, ax = plt.subplots()
ax2 = fig.add_axes([.7,.7,.2,.2])
ax2.set_position([.1,.1,.2,.2])
print(ax2.get_position())
plt.show()
# plt.show() shows axes that match the ax2.get_position() output

# an example using Axes.inset_axes
fig, ax = plt.subplots()
ax2 = ax.inset_axes([.7,.7,.2,.2])
ax2.set_position([.1,.1,.2,.2])
print(ax2.get_position())
plt.show()
# plt.show() shows axes at the position set when ax.inset_axes was called, but ax2.get_position() shows the values from set_position 
```

**Actual outcome**

```python
Bbox(x0=0.1, y0=0.1, x1=0.30000000000000004, y1=0.30000000000000004)
Bbox(x0=0.1, y0=0.1, x1=0.30000000000000004, y1=0.30000000000000004)
```

![image](https://user-images.githubusercontent.com/4028662/49946889-cb821300-fee7-11e8-8b55-6831727436d7.png)

**Expected outcome**

I believe the outcome should match the regular Axes use case:

![image](https://user-images.githubusercontent.com/4028662/49947111-56fba400-fee8-11e8-80a4-81135c493eac.png)

**Matplotlib version**

  * Operating system: Windows 10 x64
  * Matplotlib version: 3.0.2
  * Matplotlib backend: TkAgg
  * Python version: 3.7.0
  * Other libraries: 
altgraph==0.16.1
bleach==3.0.2
certifi==2018.11.29
chardet==3.0.4
Click==7.0
cx-Freeze==5.1.1
cycler==0.10.0
docutils==0.14
future==0.17.1
idna==2.7
kiwisolver==1.0.1
macholib==1.11
matplotlib==3.0.2
numpy==1.15.1+mkl
pefile==2018.8.8
Pillow==5.3.0
pkginfo==1.4.2
Pygments==2.3.0
PyInstaller==3.4
pyjanssen==0.1
pyparsing==2.3.0
PyQt5==5.11.3
PyQt5-sip==4.19.13
pyqt5-tools==5.11.2.1.3
python-dateutil==2.7.5
python-dotenv==0.9.1
pytz==2018.7
pywin32-ctypes==0.2.0
readme-renderer==24.0
requests==2.20.1
requests-toolbelt==0.8.0
scipy==1.1.0
six==1.11.0
tqdm==4.28.1
twine==1.12.1
urllib3==1.24.1
virtualenv==16.1.0
webencodings==0.5.1
websockets==7.0

**Comment by jklymak** [comment]
Away from computer for a few days, but inset_axes uses locatable_axes to allow different transforms and allow the axes to move if the range of the axes change.  So repositioning it is going to be a little more work than just set_position

**Comment by Laukei** [comment]
Hey @jklymak , thanks for the pointer!

My quick, hacky fix so far is to overwrite the axes_locator with a new one.  Using this fix, ax2.get_position() returns the incorrect value, but the graph is drawn correctly. I feel like calling set_position should automatically update the axes_locator. Would simply overwriting it like this be undesirable?

```python
import matplotlib.pyplot as plt
from matplotlib.axes._axes import _make_inset_locator
fig, ax = plt.subplots()
ax2 = ax.inset_axes([.7,.7,.2,.2])
ax2.set_axes_locator(_make_inset_locator([.1,.1,.2,.2],fig.transFigure,ax))
print(ax2.get_position())
plt.show()
```

**Comment by jklymak** [comment]
I’m not sure what the best API for what you want should be.  What is the application where you want to be able to specify the inset axes position multiple times?  Certainly it seems possible to change set_position, but that’d require subclassing axes, which has considerable overhead...

**Comment by Laukei** [comment]
To me, a call to `set_position` should set the position of the `Axes`. If there's a two-tier positioning system whereby specifying an `axes_locator` can override the position, then `set_position` and `get position` should reflect this - perhaps by raising an error?

Is it too significant a change to make the `axes_locator` into class `AxesLocator` and give it `set_position` and `get_position` functions, as well as its usual behaviour of locating axes? I don't know how widely `axes_locator`s are used across matplotlib though. Maybe this change would be absolutely horrific.

**Comment by Laukei** [comment]
I think that if a user creates axes with `inset_axes`, maintaining position correctly using the inset_locator would be expected behaviour - this is definitely the case for me.

The specific case I have is writing control software for a hardware X-Y positioner with a higher-resolution but smaller-range X-Y positioner mounted on it. I am using the `ax` to represent the larger positioners' full extents (50mm x 50mm), and `ax2` to represent the smaller range positioners' full extents (5mm x 5mm). Having `ax2` remain correctly aligned in `ax` is important for this use case, because the positioners themselves are mounted inside a completely sealed vacuum vessel with no windows, so it's important for the user to know where the two X-Y frames are relative to each other. `ax` will have a map of the surface of the device under test displayed on it, and `ax2` will show the map made in-situ. I imagine only a small number of people will ever want to use `matplotlib` for something like this, but hey, here I am...

Is it possible that giving `Axes` a function called something like `update_axes_locator` or something similar, that provides an external interface to `_make_inset_locator` could be a solution? It could be automatically called by `set_position` if `axes_locator is not None`?

**Comment by QuLogic** [comment]
That seems reasonable to me.
