### ISSUE TITLE
cannot import name _preprocess_data

### ISSUE THREAD

**Issue by engr-Eghbali** [matplotlib/matplotlib#12981]
Hi guys I have problem with importing packages,some of them figured out but this one is still remaining:

```pytb
/usr/lib64/python2.7/site-packages/matplotlib/colors.py:345: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not cbook.is_string_like(arg) and cbook.iterable(arg):
/usr/lib64/python2.7/site-packages/matplotlib/colors.py:737: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  not cbook.is_string_like(colors[0]):
Traceback (most recent call last):
  File "sm.py", line 39, in <module>
    import matplotlib.pyplot as plt  # to plot
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 26, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib64/python2.7/site-packages/matplotlib/figure.py", line 36, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 17, in <module>
    from matplotlib import _preprocess_data
ImportError: cannot import name _preprocess_data
```

  * Operating system:centos7x64
  * Matplotlib version: 2.2.3
  * Python version:2.7.5
  * Jupyter version :4.4.0
 installed matplotlib and ipython  from pip.

**Comment by WeatherGod** [comment]
If you are having difficulty importing packages, especially submodules like
this, then chances are your environment is somehow corrupt overall.

I also find it odd that you are getting those warnings upon import...

**Comment by tacaswell** [comment]
How exactly did you install things?

You said you used pip, but the imports are coming from system owned paths.  My guess is you had the centos python-matplotlib package installed and then `sudo pip install matplotlib` on top of that?

**Comment by engr-Eghbali** [comment]
@tacaswell Thanks for your replay, 
in fact,I'm using centos with developer packages which is containing py and some other things by default.
and yes...I had not `pip` and installed it by `yum` and then `matplotlib` by `pip`.
Do you suggest I remove/reinstall  all py and its dependencies ?

**Comment by timhoffm** [comment]
Appears to be caused by mixing conda and pip.

**Comment by simonhou** [comment]
Hi @engr-Eghbali , 
I also met this problem. Have you already fixed this problem?

**Comment by engr-Eghbali** [comment]
> Hi @engr-Eghbali ,
> I also met this problem. Have you already fixed this problem?

Hi, No I didn't ... finally used online interpreters.
I never told that I mixed conda and pip, they closed this issue on their own!

**Comment by tacaswell** [comment]
This is definitely an installation issue.  I suggest removing everything and re-installing either via the system package manager or by creating a user-space enviroment and using pip.  You should almost never do `sudo pip install ...`.
