### ISSUE TITLE
Windows conda build directions broken (installs unsupported python 3.5)

### ISSUE THREAD

**Issue by jimbo1qaz** [matplotlib/matplotlib#13000]
### Bug report

**Bug summary**

https://matplotlib.org/users/installing.html#building-on-windows is broken:
- Uses `#` instead of `rem` for comments.
- Tells users to install Python 3.5, despite Matplotlib git only supports building on Python 3.6+.
  - Bug: `conda create -n "matplotlib_build" python=3.5`
- I'm not sure if `activate` is deprecated in favor of `conda activate`.

**Actual outcome**

```
># if you want a qt backend, you also have to install pyqt (be aware that pyqt doesn't mix well if
'#' is not recognized as an internal or external command,
operable program or batch file.

>python setup.py bdist_wheel

Beginning with Matplotlib 3.1, Python 3.6 or above is required.

This may be due to an out of date pip.

Make sure you have pip >= 9.0.1.
```

**Matplotlib version**

  * Operating system: Windows 10 x64
  * Matplotlib version: Master dba2d7b7003b034435664c28fcf00fd7c00391bd
  * Python version: 3.5 (this is the bug)

**Comment by dstansby** [comment]
Maybe we should backport the fix to the current version of the docs?
