### ISSUE TITLE
Inconsistent range handling for set_xticks

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#13007]
### Bug report

Replaces #12994.

**Bug summary**

**Code for reproduction**
~~~
import matplotlib.pyplot as plt

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(9, 3))
for ax in [ax1, ax2, ax3]:
    ax.plot([1, 2])
 
ax2.set_xticks([1, 2])
ax3.set_xticks([2])
~~~

**Actual outcome**

![image](https://user-images.githubusercontent.com/2836374/50099054-7c0c5180-021d-11e9-93e0-782f65280a96.png)

ax1 is the original data.

ax2 extends the range to include 2 as expeced.

ax3 does not change the range. I would have expected that it looks like ax2 but with only the tick at 2.

The difference between ax2 and ax3 is just a label in the existing range. That should not have an influence on adjusting the range to outside labels.

**Comment by dstansby** [comment]
Does setting a tick value mean that tick should be included in autoscale calculations? To my mind the result above seems reasonable, since the axis is scaled to the data, but only a tick outside the limits has a label so no other ticks are shown.

**Comment by timhoffm** [comment]
The point is, ax2 and ax3 should have the same range - not saying which one. Either the range should only depend on the data (in which case ax2 would be wrong, or the range should include the labels, in which case ax3 must go up to 2.

**Comment by MaozGelbart** [comment]
Can't repro using matplotlib 3.6.3:
![image](https://user-images.githubusercontent.com/13831112/217511029-69a1981a-6834-4bd1-8535-6a2cb3d24fa3.png)

**Comment by tacaswell** [comment]
Thank you for triaging this @MaozGelbart !

Closing as fixed, I do not think it is worth tracking down exactly what version we fixed this in.
