### ISSUE TITLE
Memory leak when rendering MathText to get its bounding box

### ISSUE THREAD

**Issue by vlad-oles** [matplotlib/matplotlib#13019]
### Bug report

**Bug summary**

Calling in a loop get_window_extent() for Text objects that contain MathText's "\bf" command increases used memory, despite the Text objects being removed. The memory use grows even after the first 50 Text objects are created, which is the cache size for Text objects.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import random


fig = plt.figure()
renderer = fig.canvas.get_renderer()
sample_text = "$\\bf{{{}}}$".format(random.randint(0, 9999999999))
i = 0
while True:
    # This wouldn't make memory usage grow:
    # text = sample_text

    # This wouldn't either:
    # text = "{}".format(random.randint(0, 9999999999))

    # But this does:
    text = "$\\bf{{{}}}$".format(random.randint(0, 9999999999))
    # ...when combined with get_window_extent():
    plotted_text = fig.text(0, 0, text)
    plotted_text.get_window_extent(renderer)
    plotted_text.remove()

    # Check if memory grows after 50 iterations.
    i += 1
    if i % 50 == 0:
        print(i)
```

**Matplotlib version**
  * Operating system: Ubuntu 18.04.1 LTS
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'TkAgg', 'Agg'
  * Python version: 3.6.5

**Actual outcome**
Memory usage grows indefinitely.

**Expected outcome**
No growth of used memory after the first 50 Text objects created.

Matplotlib installed from pip.

**Comment by QuLogic** [comment]
There's a [cache](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/text.py#L115) on `Text` mapping text+properties to locations. Are you sure the memory growth is indefinite and not capped after 50 objects or so?

**Comment by vlad-oles** [comment]
It seems like the memory growth indeed stops after 50 pages are printed. I never waited enough to figure it out.

**Comment by vlad-oles** [comment]
Reopening as using "\bf" command in MathText creates memory leak that persists even after 5000 created MathText objects.

First post edited to incorporate the '\bf' command.
