### ISSUE TITLE
Seemingly irrelevant exception about sequence multplication happening when linestyle used

### ISSUE THREAD

**Issue by fxfactorial** [matplotlib/matplotlib#13031]
on matplotlib 2.2.3, python 3.7.1, latest OS X.

Trying to have dotted grid lines for a simple graph showing a vector. 

```python

def with_vector_grid():
    fix, ax = plt.subplots()
    ax.arrow(0.0, 0.0, 0.5, 0.5, head_width=0.05, head_length=0.1, fc="k", ec="k")
    ax.set_xlim([-0.2, 2])
    ax.set_ylim([-0.2, 2])
    plt.grid(True, linewidth="0.5")
    plt.show()


with_vector_grid()
```

will explode if `plt.grid(True, linewidth="0.5")` changed to `plt.grid(True, linewidth="0.5", linestyle=':')`. 

Relevant traceback:

```
    return XTick(self.axes, 0, '', major=major, **tick_kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 178, in __init__
    self.gridline = self._get_gridline()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 503, in _get_gridline
    **self._grid_kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/lines.py", line 391, in __init__
    self.set_linestyle(linestyle)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/lines.py", line 1125, in set_linestyle
    self._us_dashOffset, self._us_dashSeq, self._linewidth)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/lines.py", line 68, in _scale_dashes
    scaled_offset = offset * lw
TypeError: can't multiply sequence by non-int of type 'float'
```

This error message is very confusing to me.

**Comment by jklymak** [comment]
This isn't present in master, so would be a 2.2.4 bug fix only, if we deem it important enough to fix.

**Comment by WeatherGod** [comment]
attn: @efiring as this looks like it is in the dash scaling code. I wonder how this got "fixed"?

**Comment by efiring** [comment]
This is not a bug but a lack of input validation.  The problem is that the linewidth has been supplied as a string when it should be a number.  I suspect that in 2.3 the linewidth input is being coerced via a `linewidth = float(linewidth)` or something like that.

**Comment by jklymak** [comment]
Oops, duh!   Thanks @efiring.  I’m going to close as not really a bug, but feel free to re-open or discuss further...

**Comment by fxfactorial** [comment]
Exceptions that don’t give relevant information on what is wrong is indeed a bug

**Comment by jklymak** [comment]
PRs welcome!
