### ISSUE TITLE
'NoneType' has no attribute '_alive' when using plt in a context manager

### ISSUE THREAD

**Issue by jatentaki** [matplotlib/matplotlib#13033]
### Bug report

**Bug summary**

I am creating a GUI for annotating a dataset. I have a class which owns and controls a `Figure` and also has `__enter__` and `__exit__` implemented, such that in case of an exception thrown, it is guaranteed to save the work before exiting. It works and is usable but when closing the window it throws some exception originating from `weakref.py`. Below is an example stripped to the maximum I could.

**Reproducing code**
```python
 import numpy as np
 import matplotlib.pyplot as plt
 
 class AnnotationGui:
     def __init__(self):
         self.img = np.zeros((50, 50))
         self.fig, self.ax = plt.subplots()
         self.display = self.ax.imshow(self.img)
         self.fig.canvas.mpl_disconnect(
             self.fig.canvas.manager.key_press_handler_id
         )
         self.fig.canvas.mpl_connect('key_press_event', self.on_key)
         plt.show()
 
     def on_key(self, event):
         pass
 
     def __enter__(self):
         return self
 
     def __exit__(self, *exc):
         pass
 
 with AnnotationGui() as gui:
     pass
```

**Actual outcome**

A window opens as expected, but when closing I get a traceback
```
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f8e42d31378>
Traceback (most recent call last):
  File "/home/jatentaki/miniconda3/lib/python3.7/weakref.py", line 55, in _cb
AttributeError: 'NoneType' object has no attribute '_alive'
```

**Expected outcome**

A window opens as above and then closes without raising any errors.

**Matplotlib version**

  * Operating system: Xubuntu 18.04 LTS
  * Matplotlib version: 3.0.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.1
  * Other libraries: Numpy 1.15.4

Python and mpl from miniconda3, default channel

**Comment by anntzer** [comment]
I can't reproduce the error with py3.7+mpl3.0.2+qt5agg.

**Comment by anntzer** [comment]
I can't reproduce the error with py3.7+mpl3.0.2+qt5agg.

**Comment by dstansby** [comment]
Seems fine for me too, are you still having problems @jatentaki ?

**Comment by tacaswell** [comment]
I sometimes see this in local test runs.

**Comment by anntzer** [comment]
Does adding `if sys.is_finalizing(): return` at the very top of `matplotlib.cbook.CallbackRegistry._remove_proxy` fix the issue?
