### ISSUE TITLE
Matplotlib Not showing plots in excel file

### ISSUE THREAD

**Issue by kristenl2784** [matplotlib/matplotlib#13045]
Hello,

I am totally new at programming, and have looked at other posts about Matplotlib not showing plots, but nothing seems to be working for me. I have a script that was written by a contractor (no longer with us), and an executable for the script. The script works as it should and plots show in my excel file. But now I need to tweak a few areas inside the script, so I downloaded Python 3.6.0 because the contractor was using this version. The main difference is that I'm on windows 10 and the contractor used Linux.

I downloaded what I thought were all the packages needed using the "pip" command inside power shell. I tweaked the areas in the script that I needed to tweak, and ran pyinstaller --onefile .\file name.spec using power shell.

The script compiled and at the end it says "Building EXE from EXE-00.toc completed successfully".

But when I run the new executable the excel file doesn't show plots like it once did.

I'm assuming it has something to do with matplotlib because I see this during the compile

 
![matplotlib](https://user-images.githubusercontent.com/46056120/50400915-cc713b00-0758-11e9-8e15-654b049dc08f.JPG)

 
I've also downloaded VS with windows SDK

Matplotlib version 3.0.2
Python 3.6.0
Pyinstaller 3.4
Pip 18.1  
Numpy 1.15.4
Pandas 0.23.4
Scipy 1.2.0

Script uses these imports:

![script import](https://user-images.githubusercontent.com/46056120/50400983-689b4200-0759-11e9-82bb-0b028ed0125a.JPG)

Any help would be great.

 

Thanks
Kristen

**Comment by WeatherGod** [comment]
I wouldn't worry about those warnings unless the contractor's code
specifically used one of the cairo-based backends. Matplotlib supports
utilizing many different backends, which allows it to be used in many
different contexts. Looking at the import list, it would seem that TkAgg
would have been the intended backend (assuming that matplotlib is even used
-- it isn't imported). Is this a single .py source file, or are there more?

Does the original executable still work? Is there a matplotlibrc file
lurking about in the directory trees? Do you see any warnings when you try
to display the plot from the new executable in powershell?

**Comment by kristenl2784** [comment]
Hello,

The original script and executable work fine, unless I try to compile it then the plots don't show.  

Here is what happens when I compile. 

![1](https://user-images.githubusercontent.com/46056120/50403190-95a42080-076a-11e9-9f97-8f25c2fce853.JPG)
![2](https://user-images.githubusercontent.com/46056120/50403191-98067a80-076a-11e9-94d6-e4f1a7db168a.JPG)

As far as Matplotlib, the script doesn't have this in it at all.  I installed it because the contractor left notes to install matplotlib, scipy, numpy, and any other missing packages.  I did a search for "Matplotlib"  inside the script and nothing was found.

**Comment by WeatherGod** [comment]
if matplotlib is not imported directly at all, then it becomes very
unlikely that matplotlib is used at all. It is possible that a package like
pandas could use matplotlib under-the-hood, but ultimately, one needs to
somehow invoke `plt.show()` or `fig.show()`. The only way to implicitly
invoke those commands for matplotlib is if the interactive mode was turned
on inside a matplotlibrc file.

Can you show a screenshot of a figure that the old executable makes. We can
tell you what library likely generated it.

**Comment by kristenl2784** [comment]
Heres a plot made by the executable 

![4](https://user-images.githubusercontent.com/46056120/50404226-72ca3a00-0773-11e9-8e73-a6a6d83788cf.JPG)

**Comment by WeatherGod** [comment]
This is a figure that appears when you open the excel spreadsheet in excel?
If so, then what is most likely happening is that openpyxl is being used to
insert a figure into the excel spreadsheet and is then rendered by excel.
However, openpyxl has gone through a bunch of changes over the years and it
is quite possible that the code might have gotten broken over time.

Matplotlib is used for creating figures and displaying them either as
images or within interactive GUI widgits. One particular thing about this
figure that makes me think it isn't a matplotlib figure is that by default,
matplotlib legend boxes are fairly tight. You would not get this much
padding in a normal legend box from matplotlib. You also wouldn't get the
line and the label that close together. There are a bunch of other aspects
of the figure that, while it is possible to do them in matplotlib, it isn't
default and I doubt someone would go through the effort to make them that
way.

**Comment by kristenl2784** [comment]
Hello,

Yes, this is the plot made by the script and placed in excel (I used the snip tool and snipped the image right out of excel.

**Comment by WeatherGod** [comment]
Let's be specific with our terminology. Is it a plot object that is
rendered by excel when excel opens it (so, if you change the data points,
the plot updates?) Or is it an image object that is embedded in excel
(possibly as an OLE object perhaps?). If it is the latter, then we are back
to square one. If it is the former, then the problem is almost certainly
with openpyxl.

**Comment by kristenl2784** [comment]
I'll try to explain what happens:
The executable asks for:
1. The folder where the data files are stored
2. The location of the template to use
3. A box to check on if I want error plots to be created. 

The template has 5 tabs inside of it. The first tab is the data tab, the script will locate the data files and copy it into the template (data).  The remaining 4 tabs are for the plots.  The plots are created from the data tab. 

![plot](https://user-images.githubusercontent.com/46056120/50482387-3e918c00-09b4-11e9-899c-e1620c6d6c8d.JPG)


If I don't check the option to create error plots, then all that is populated is the data tab which is all I'm getting right now when I run the executable. But plots should be created since I always check the option to create error plots.  

What's strange is that the template has 4 blank plots tabs, and the 1 empty data tab.  But when I run the executable all that is populated is the data tab, and the 4 plots tabs are removed, and not even showing anymore. 

![data](https://user-images.githubusercontent.com/46056120/50482389-42bda980-09b4-11e9-92e4-7df5af62bb2a.JPG)

If I take a template that is populated with data and all the plots are showing, I can change the data inside the data tab to manipulate the way the plots look after the script has finished. So, I'm assuming we're back at square one.

**Comment by jklymak** [comment]
This really has nothing to do w matplotlib.  Best wishes getting get this sorted out, but I’m going to close.

**Comment by kristenl2784** [comment]
Okay, where do I continue to post for support?

**Comment by jklymak** [comment]
This is a bug tracker for matplotlib, not a general python/excel help forum.  You could try stackoverflow, or perhaps more ideally consult with the person who originally wrote your script.

**Comment by kristenl2784** [comment]
If I could consult with the person that wrote it, I wouldn't be on here asking for help.

**Comment by phobson** [comment]
@kristenl2784 I'm available for contract work
