### ISSUE TITLE
Docker alpine - matplotlib.pyplot failed to import (numpy multiarray)

### ISSUE THREAD

**Issue by cnasikas** [matplotlib/matplotlib#13059]
### Bug report

I try to import matplotlib but an error is occured. I use pipenv to install dependencies and docker for deployment. What is driving me crazy is that when I build and run the docker image on a mac with macOS mojave 10.14.2 everything is working fine. When I move the same image to another maching and specifically to Ubuntu 16.04.5 LTS server it fails.

I search a lot but couldn't find a solution

**Bug summary**

**Code for reproduction**

**Dockerfile:**

```
FROM python:3-alpine
RUN apk --no-cache --update-cache add build-base wget freetype-dev libpng-dev openblas-dev

RUN pip3 install pipenv

RUN set -ex && mkdir /app
WORKDIR /app

COPY Pipfile .
COPY Pipfile.lock .

RUN set -ex && pipenv install

COPY . .

ENTRYPOINT ["/bin/sh"]

```

**Pipfile:**

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
matplotlib = "==3.0.2"
numpy = "==1.15.4"

[requires]
python_version = "3.7"

```

**Build image & start docker container:**
```
docker build -t my_image .
docker run -it my_image
```

**Inside docker container:**

```
pipenv run python
import matplotlib.pyplot as plt
```

I try also inside docker container

```
pip install matplotlib
python
>>> import matplotlib.pyplot
```

wihtout using `pipenv` but again I face the same problem.

**Actual outcome**

```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/matplotlib/colorbar.py", line 28, in <module>
    import matplotlib.artist as martist
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/matplotlib/artist.py", line 11, in <module>
    from .path import Path
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/matplotlib/path.py", line 17, in <module>
    from . import _path, rcParams
ImportError: numpy.core.multiarray failed to import
```

**Expected outcome**

The module should be imported

**Matplotlib version**

  * Operating system: Docker: Alpine, Host: Ubuntu 16.04.5 LTS, MacOS 10.14.2
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Same error when trying to get backend
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: numpy 1.15.4

Related: #12119

**Comment by cnasikas** [comment]
I tried also this solution (no pipenv) with the same results

https://gist.github.com/orenitamar/f29fb15db3b0d13178c1c4dd611adce2

**Comment by tacaswell** [comment]
> What is driving me crazy is that when I build and run the docker image on a mac with macOS mojave 10.14.2 everything is working fine. When I move the same image to another maching and specifically to Ubuntu 16.04.5 LTS server it fails.

This makes me suspicious that this is actually a docker problem (particuarly given that switching the base image fixes the problem).  I am going to close this issue as not something we can solve at the Matplotlib issue.  I would also try to sort out the docker related issues before going to numpy.

Thank you for the report and best of luck!
