### ISSUE TITLE
Missing self in image_slices_viewer

### ISSUE THREAD

**Issue by pierrethibault** [matplotlib/matplotlib#13051]
Little bug that shows up only when using the class in a different context:

https://github.com/matplotlib/matplotlib/blob/4aa27080672d178c03c0c37a65751b3a04c840bd/examples/event_handling/image_slices_viewer.py#L35

should be `self.ax.set_ylabel(...`. It feels silly to submit a PR for 5 characters, but can do it if that's the procedure.

**Comment by timhoffm** [comment]
Good catch! Thanks!

Every code change must go in via a PR, even if it's just 5 characters. You are welcome to provide a PR. If you feel that's too much bothering, I will make the PR later on myself.

**Comment by pierrethibault** [comment]
Done with PR #13052

**Comment by timhoffm** [comment]
Just a hint: The typical workflow is to leave the issue open until the PR gets merged. You can add "Fixes #13051" or "Closes #13051" to the PR text. Github looks for these phrases and automatically closes the respective issue when the PR gets merged.
