### ISSUE TITLE
matplotlib hangs on interactive plotting with math in labels

### ISSUE THREAD

**Issue by agallenne** [matplotlib/matplotlib#13066]
I have the same problem as in the closed issue: https://github.com/matplotlib/matplotlib/issues/11152.
Basically, plots work ok, until I have several time this messages: QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier
, and then after some time ipython stops responding (even ctrl+c or z don't work). A solution to have the terminal back is to click on the matplotlib plot and then click on Quit from the main menu. However, although python is back, I cannot plots do not display anymore. 

  * Operating system: OSX
  * Matplotlib version: 3.0.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.6
  * IPython version: 7.2.0

**Comment by tacaswell** [comment]
How did you install python, matplotlib, qt, and pyqt?

**Comment by agallenne** [comment]
The latest version of anaconda

**Comment by jklymak** [comment]
Just to reference https://github.com/ipython/ipython/issues/10201

Did you try the %matplotlib magic command from ipython?

**Comment by agallenne** [comment]
yes I tried

**Comment by agallenne** [comment]
I would be happy to provide you with more information to help debugging, but I do not have much. It appears after running my code 3-4 times, then the message "QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier" appears, but python has still not frozen, then a few more times rerunning the code and it freezes. If I remove the plotting function from the code I no longer have this problem. I will try to attach this function.

**Comment by jklymak** [comment]
And you are running this in ipython?  just `run test.py`?

**Comment by agallenne** [comment]
Indeed, from a terminal I do:
$ ipython --pylab
>> import test
>> test.plotData() 

I do the last one a few times and the message appears, then a few more times and ipython got stuck

**Comment by jklymak** [comment]
Yes, I can reproduce this on my mac using ipython 7.0.1.  Thanks for the reproducible example.  

Oddly, a much simpler plot doesn't have the same issues for me...

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

def plotData():

    winSize = (5.5,4.5)
    fig, axs = plt.subplots(1,1, figsize=winSize)
    axs.plot(np.arange(10))

plotData()
plt.show()
```

**Comment by jklymak** [comment]
OK, so 

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.set_ylabel('$V_{orb}\,(km/s)$', fontsize=12)
plt.show()
```
Fails, and 

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.set_ylabel('V_{orb}\,(km/s)', fontsize=12)
plt.show()
```

does not fail (as long as I was willing to try it, which wasn't for ever).  So I guess we have some weird issue getting the latex version of the axes labels.  I'm not clear how that code works, but it doesn't shock me that it can get confused after a while.  In my case I only need to run the above four times in an interactive ipython script to get the lock up.

**Comment by agallenne** [comment]
Even using the backend manually it still fails for me

**Comment by jklymak** [comment]
> Even using the backend manually it still fails for me

Can you say exactly what you are doing that fails.  That would definitely be our problem in that case...

**Comment by agallenne** [comment]
I tried using only python from the terminal (without --pylab), then change the beginning of my code with your lines:

import matplotlib
matplotlib.use('qt5agg')
import matplotlib.pyplot as plt

**Comment by agallenne** [comment]
sorry, it was ipython (autocorrect :-| )

**Comment by jklymak** [comment]
Really?  If I run your code, I never get the figure window popping up because you don't call `plt.show()`.  How are you getting a window to raise if you never show it?

**Comment by jklymak** [comment]
Ah, OK: 

```python
import matplotlib
matplotlib.use('qt5agg')
import matplotlib.pyplot as plt

plt.ion()
fig, ax = plt.subplots()
ax.set_ylabel('$V_{orb}\,(km/s)$', fontsize=12)
plt.show()
```

will give the lockup...

**Comment by agallenne** [comment]
Actually for some reasons, I have never had to use plt.show() (maybe something in the matplotlib.rc file). Even using/removing plt.ion() and plt.show() it still fails

**Comment by agallenne** [comment]
Ok, I tried your two functions, the first one gives such things in loop and does not fail (I had to stop it though):
.....
b9196c <built-in function monotonic> entering inputhook
b9196c 412901.310172447 about to create socket notifier
b9196c 412901.310206452 about to create connect notifier
b9196c 412901.310256461 about to enable connect notifier
b9196c 412901.310296483 did not need to run qt loop
.....

and the second one gives the same message as before (QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier), and python stops responding.

**Comment by tacaswell** [comment]
so with lots of printing it never failed?  How often did it say "did not reed to run qt loop" vs "about to launch main loop" ?

**Comment by agallenne** [comment]
So, I let it run 1mn approx before stopping the loop. There are 3126 lines printed, and there are 521 occurrences of "did not need to run qt loop". As these are blocks of 6 printed lines each time, it means that only this sentence is printed. There is 0 occurence of "about to launch main loop"

**Comment by Carreau** [comment]
Thanks for the ping. I haven't touched the eventloop in a while, and add looking at this to my todo list. I might have have time to do that soon though.

**Comment by tacaswell** [comment]
> There is 0 occurence of "about to launch main loop"

That is deeply worrying.  Is the figure responsive during that minute?  If so, what is running the event loop?  If you are not typing for that minute why is the context always reporting that it is ready with input?  @agallenne could you post 10-15 of the 6-line blocks?  I am curious about the timing on them...

@Carreau Is there someone else we should ping instead?

**Comment by agallenne** [comment]
The figure does not appear at all actually. I just start ipython and import the function, and the event loop is running indefinitely. If I press "enter" during the loop it is not responding anymore. I attached a text file with the output of my terminal.
[test.txt](https://github.com/matplotlib/matplotlib/files/2730932/test.txt)

**Comment by liruhan** [comment]
If there is no display device for output, can  I plot on file?

**Comment by efiring** [comment]
Quick update: I'm getting related failures on my system--several failure modes--with no mathtext.  Sometimes there is a delay in the plot becoming active, sometimes when it becomes active the terminal no longer responds.  Ipython 7.1.1, and 6.5.0 (different conda environments).  Sometimes with `QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier` messages on the terminal, sometimes not. 
I'm not going to try to pursue this mess at the moment; just registering that there remains a perplexing problem related to qt5agg and ipython on recent mpl, at least with my current conda environments.

**Comment by tacaswell** [comment]
What versions of Qt do people who are having problems have?

**Comment by efiring** [comment]
`qt                        5.6.2                h9e3eb04_4    conda-forge`
in both of the environments I am using.

**Comment by efiring** [comment]
Some of the behavior I am seeing seems to be timing-dependent, and it involves something going wrong with the inputhook.  I'm wondering whether it might be related to ipython moving away from readline and simple tab completion printing to the machinery that generates the annoying quasi-gui tab completion table.

**Comment by tacaswell** [comment]
See https://github.com/ipython/ipython/issues/10364/ and https://github.com/ipython/ipython/pull/10373 for how to get back to non-PT ipython via https://github.com/ipython/rlipython

**Comment by tacaswell** [comment]
@efiring can you try the first version of the input hook in https://github.com/matplotlib/matplotlib/issues/13066#issuecomment-451048182 at some point?

Could you also try adding

```
notifier.setEnabled(False)
```

to the bottom of the inputhook?

**Comment by efiring** [comment]
I have done that (including adding the line to the bottom) on my py36 environment, and the result is that starting ipython and typing %matplotlib results in a full-speed stream of output blocks like
```
9ce13f <built-in function monotonic> entering inputhook
9ce13f 149527.889747306 about to create socket notifier
9ce13f 149527.889788281 about to create connect notifier
9ce13f 149527.889853261 about to enable connect notifier
9ce13f 149527.889901615 did not need to run qt loop
9ce13f 149527.889920123 exiting inputhook
```
until I kill the process.

**Comment by efiring** [comment]
Simply importing matplotlib.pyplot as plt has the same effect.  Ctrl-C doesn't stop it, so I have to kill it from another window.

**Comment by tacaswell** [comment]
That is consistent at least....

if you just add the `setEnabled(False)` does that make it better?  I have some concern that the telemetry is messing with what we are measuring with the prints....

**Comment by efiring** [comment]
I already have the `setEnabled(False)`.  Do you mean I should remove all the print calls?

**Comment by efiring** [comment]
Looks like that works!

**Comment by kmtac** [comment]
Even with this fix, there still seems to be some trouble with the qt event loop, at least on my computer.   After calling the "%gui qt" magic, ipython eventually slows down dramatically.  "Eventually" varies, from a minute or so to half an hour.  Dramatically means time.sleep(0.1) takes 10.1 seconds.  The 10.1 

I'm using the developer version of ipython (cloned yesterday), but with qt.py from the fix reported here.

Minimal example:
% ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt                                                                                                                           
In [2]: import time                                                                                                                       
In [3]: x=0.1; tic=time.time();time.sleep(x);toc=time.time();print(f"Expected {x} sec, got {toc-tic:.2f} seconds.")                       
Expected 0.1 sec, got 0.10 seconds.
In [4]: x=0.1; tic=time.time();time.sleep(x);toc=time.time();print(f"Expected {x} sec, got {toc-tic:.2f} seconds.")                       
Expected 0.1 sec, got 10.10 seconds.
                      
This problem has been around for at least a year, but less than two years.  I first noticed it when using pymeasure (which uses time.sleep).

I'm using the anaconda python distribution, see version info below. 
conda version : 4.6.14
conda-build version : 3.17.8
python version : 3.7.3.final.0

I put my comments here because it seems to be the same problem.  Let me know if you'd like me to file a separate bug report or to do other tests.

**Comment by kmtac** [comment]
My apologies here ... I had meant to comment on the [ipython issue](https://github.com/ipython/ipython/pull/11740).

**Comment by greglucas** [comment]
I'm not following where this one is at in terms of what has been integrated and what needs to be tested still, but it seems more like an ipython issue specifically? (unless `%gui qt` is spinning up matplotlib's qt event loop?)

Specifically, this reproducible example, where I was able to confirm that letting ipython go for a few minutes and coming back does produce the 10.1 second output.
https://github.com/matplotlib/matplotlib/issues/13066#issuecomment-495662548
