### ISSUE TITLE
Startup lag due to font cache (font_manager) and PyInstaller

### ISSUE THREAD

**Issue by jimbo1qaz** [matplotlib/matplotlib#13071]
### Bug report

**Bug summary**

On first import, `matplotlib.font_manager` spends nearly 10 seconds building a font cache (`fontlist-v300.json`).

When compiling with PyInstaller (with one-file mode *disabled*), the font cache is located at `%localappdata%\Temp\tmp6i35kb4u` which is cleared every time the app is closed, leading to startup lag EVERY time.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
```

**Actual outcome**

Slow app startup.

**Expected outcome**

Fast app startup.

**Matplotlib version**
  * Operating system: Windows 10 x64
  * Matplotlib version: 3.0.2
  * Matplotlib backend Agg
  * Python version: 3.7.2 locally, 3.6.7 PyInstaller

Installed via Poetry (related to Pip).

**Comment by jimbo1qaz** [comment]
This is somewhat of an interaction between pyinstaller and matplotlib, not a strict "bug" in either program.

I'm trying to work around this by setting `sys.modules['matplotlib.font_manager'] = MagicMock()`, but it fails on Python 3.6 with `AttributeError: module 'matplotlib' has no attribute 'font_manager'`.

--------
```python
_fmcache = os.path.join(
    mpl.get_cachedir(), 'fontlist-v{}.json'.format(FontManager.__version__))
...
@_logged_cached('CACHEDIR=%s')
def get_cachedir():
    """
    Return the location of the cache directory.

    The procedure used to find the directory is the same as for
    _get_config_dir, except using `$XDG_CACHE_HOME`/`~/.cache` instead.
    """
    return _get_config_or_cache_dir(_get_xdg_cache_dir())
```

In my local-machine pyinstaller build, `print(matplotlib.get_cachedir())` == `C:\Users\jimbo1qaz\AppData\Local\Temp\tmp90q8qi6j`.

>AttributeError: module 'matplotlib' has no attribute 'get_home()'

-----

I get the feeling this was intentional on pyinstaller's part, by setting MPLCONFIGDIR to a temporary path.

https://github.com/pyinstaller/pyinstaller/blob/c06d853c0c4df7480d3fa921851354d4ee11de56/PyInstaller/loader/rthooks/pyi_rth_mplconfig.py#L35-L37
Pyinstaller "need[s] to force matplotlib to recreate config directory every time you run your app."

https://github.com/pyinstaller/pyinstaller/issues/617

Maybe I should move this issue to pyinstaller's bug tracker.

-----

ouch this code changed a lot between 3.0.2 (site-packages) and master (git clone).

**Comment by anntzer** [comment]
The patch on pyinstaller's side (due to the font cache hardcoding the path to matplotlib) will become unnecessary once https://github.com/matplotlib/matplotlib/pull/12472 is merged; after that PyInstaller should just stop setting MPLCONFIGDIR.
(As a side note it would be better if the issues got reported to us so that we can fix them...)

**Comment by anntzer** [comment]
Now that #12472 is merged can you try with mpl master + pyinstaller-with-the-MPLCONFIGDIR-patch-patched-out?

**Comment by jimbo1qaz** [comment]
Right now I'm using matplotlib 3.0.2 + pyinstaller + manually unset MPLCONFIGDIR before importing matplotlib. It might be faster, but I haven't confirmed, the speed hit was intermittent before. Do you want me to test master on Windows?

**Comment by anntzer** [comment]
Well, manually unsetting MPLCONFIGDIR will work too.
The Windows build if not using conda (which I guess is your case) is a bit in a state of flux right now, so it may not be worth it for you to spend too much time on that...

**Comment by anntzer** [comment]
Closing, as the remaining issue is on PyInstaller's side.
