### ISSUE TITLE
Slow in plotting markov decision process graph with pycharm and python 3.6

### ISSUE THREAD

**Issue by srinibujjay** [matplotlib/matplotlib#13087]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#import fiabilipy
import time
from fiabilipy import Component, Markovprocess
A0, A1 , A2 ,A3,A4 = [Component('A{}'.format(i), 1e-4, 1.1e-3 ,1.1e-3 ) for i in range(5)]
M0, M1 , M2, M3,M4 = [Component('M{}'.format(i), 1e-3, 1.2e-2, 1.2e-3 ) for i in range(5)]
compA=(A0,A1,A2,A3,A4)
compM=(M0,M1,M2,M3,M4)
components = (compA+compM)
initstates = {0: 0.9, 1:0.1}
process = Markovprocess(components, initstates)
def normal(x):
 return all(x)
def available1(x):
    for i in compA:
        return (x[0]or x[i] or x[i+1])
def available2(x):
    for i in compM:
        return (x[0] or x[i] or x[i+1])
def available(x):
    return available1 and available2
def damaged(x):
 return available(x) and not(normal(x))
def faulty(x):
 return not available(x)
print(process.value(150, available))
print(process.value(100,damaged))
import matplotlib
matplotlib.use('TkAgg')
import pylab
states = {u'normal': normal,
          u'available': available,
          u'damaged': damaged,
          u'faulty': faulty,
         }
timerange = range(0, 6000, 10)
for (name, func) in states.items():
     proba = [process.value(t, func) for t in timerange]
     pylab.plot(timerange, proba, label=name)
pylab.legend()
pylab.show()


#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Can you reproduce the problem without whatever fiabilipy is?  Otherwise it’s impossible for us to debug and one suspects the issue is elsewhere. It would also be better to not have pycharm in the mix.

**Comment by tacaswell** [comment]
I suspect the issue is that as you are plotting in the loop you are never giving the GUI any chance to update the window.  See https://github.com/matplotlib/matplotlib/pull/4779 for a long explanation, but I suspect adding `fig.canvas.flush_events()` inside of the loop will fix your problem.

**Comment by srinibujjay** [comment]
The same loop and graph is working fine for lesser tuple values , when it goes more than 6 tuple values there the issue starts for me, i will try with fig.canvas.flush_events() and come back

**Comment by srinibujjay** [comment]
meanwhile fiabilipy is library for reliability analysis with python whichis not so active i guess for huge data inputs and that may be the reason for my issues

**Comment by srinibujjay** [comment]
Got it , the value assigned in component is not fitting in the range(0,6000,100) or its much more than that , can anyone suggest how to get the range as default in this case

**Comment by srinibujjay** [comment]
>           Can you reproduce the problem without whatever fiabilipy is?  Otherwise it’s impossible for us to debug and one suspects the issue is elsewhere. It would also be better to not have pycharm in the mix.
Got it , the value assigned in component is not fitting in the range(0,6000,100) or its much more than that , can anyone suggest how to get the range as default in this case

**Comment by jklymak** [comment]
I don’t think we can help debug fiabilipy.   Please do let us know if there is a matplotlib issue but I’m going to close for now.
