### ISSUE TITLE
fig.show() doesn't block

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#13101]
### Bug report

Calling `fig.show()` on a figure doesn't block. Commenting out the `input()` line below does block, and the figure shows fine. Also using `plt.show()` instead works fine.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('qt5agg')
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
fig.show()
# input()
```

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.7.1

**Comment by WeatherGod** [comment]
fig.show() can't block because if it did, then when it comes time to show
multiple figures, then the first figure would block the others.

**Comment by dstansby** [comment]
Doh, that makes sense - is there not a way to do some stuff, open a figure that stays open, then do some other stuff and open another figure whilst keeping the first one open?

**Comment by dstansby** [comment]
No, just in a shell

**Comment by jklymak** [comment]
`plt.ion()` works in a vanilla python shell as well.  Am I not understanding your problem?  

```
In [9]: plt.ion()

In [10]: plt.plot(range(10))
Out[10]: [<matplotlib.lines.Line2D at 0x11d6326a0>]

In [11]: plt.plot(range(10))
Out[11]: [<matplotlib.lines.Line2D at 0x11d67c748>]

In [12]: plt.figure()
Out[12]: <Figure size 1280x960 with 0 Axes>

In [13]: plt.plot(range(20))
Out[13]: [<matplotlib.lines.Line2D at 0x1234c5080>]
```

**Comment by dstansby** [comment]
I'm clearly just very confused, `plt.ion()` worked fine... Thanks all!

**Comment by timhoffm** [comment]
This should probably be mentioned in the documentation. 

Not sure I understand all this correctly. Is there any use-case for and end-user to call  `fig.show`?

**Comment by timhoffm** [comment]
Is that the use case of embedding matplotlib in your own GUI application?

Users from the command line/ipython/jupyter notebooks do not have to bother with `fig.show()`, right?

**Comment by ImportanceOfBeingErnest** [comment]
It seems, `fig.show()` is useful in IPython. While `plt.ion()` + `plt.show()` result in an unresponsive window, `fig.show()` works fine for me. I'm not a regular IPython user myself, but I used (i.e. py27, matplotlib < 2.2) to use it like

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt

In [2]: fig, ax = plt.subplots()

In [3]: ax.plot([1,2])
Out[3]: [<matplotlib.lines.Line2D at 0x7c19976a20>]

In [4]: fig.show()

In [5]: ax.plot([1,3])
Out[5]: [<matplotlib.lines.Line2D at 0x7c1c5aa320>]

In [6]: fig.show()
```

Here in cell 4, the window opens up and shows a responsive(!) figure. Without closing the window I could continue to plot stuff and call `fig.show()` again to have the figure updated.   

Nowadays (py36, matplotlib 3), the second `fig.show()` doesn't seem to work any more. I would instead need to use `fig.canvas.draw()` in cell 6 from above.

**Comment by timhoffm** [comment]
I get a responsive window with

~~~
In [1]: import matplotlib.pyplot as plt

In [2]: plt.ion()

In [3]: fig, ax = plt.subplots()
~~~
Figure window is immediately displayed and the command line is not blocked (no `show()` needed).
I can then add elements to the plot
~~~
In [4]: ax.plot([1,2])
~~~
which immediately updates the plot.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, your code works for me too. The problem is when you close the GUI window, and then want to get it back. `plt.show()` doesn't work in that case.

**Comment by jklymak** [comment]
...? But `fig.show()` does?  I'd have thought closing the window would destroy the figure.

**Comment by ImportanceOfBeingErnest** [comment]
Surprisinigly perhaps, yes. In the case you closed it you'd also need to draw it though (`fig.canvas.draw()`).

**Comment by tacaswell** [comment]
> I'd have thought closing the window would destroy the figure.

The visibility / non-visibility of the window is decoupled from it's existence in most GUI frameworks.  This is really helpful for things like showing / hiding complex panes etc.  In our case the continued existence also depends on a hard-ref to the underlying python object (but for pyplot, we register a callback on 'close' to remove it from pyplot's cache, which is why re-showing with `plt.show()` does not work, but `fig.show` does).

**Comment by Guimoute** [comment]
I just stumbled upon a situation where `fig.show()` not blocking can be an issue. 

```python
fig, ax = plt.subplots()
manager = plt.get_current_fig_manager()
manager.window.showMaximized()
fig.show()

... # Plotting objects in data coordinates: works fine.

... # Plotting objects in figure coordinates: fails because the objects fall in the pre-fullscreen positions.```

The current work-around is to add a code section with `#%%` so that Spyder can execute everything that is not based on figure coordinates first, then run the rest.

**Comment by prabhuiitdhn** [comment]
fig.show() does not block the window for showing plot multiple times. so, Quick fixes using self.fig.waitforbuttonpress() it waits user to press the button for next plot visualisation.

```
      self.fig.show()
      plt.pause(0.1)
      self.fig.waitforbuttonpress()
```
