### ISSUE TITLE
No MatplotlibDeprecationWarning for default rcParams

### ISSUE THREAD

**Issue by koki-sato** [matplotlib/matplotlib#13118]
### Bug report

**Bug summary**

I get MatplotlibDeprecationWarning when putting the default rcParams copied by `matplotlib.rcParams.copy()` into `matplotlib.rcParams.update()`.

**Code for reproduction**

```python
>>> import matplotlib
>>> matplotlib.__version__
'3.0.2'
>>> rc_params = matplotlib.rcParams.copy()
>>> matplotlib.rcParams.update(rc_params)
/Users/xxxx/.local/share/virtualenvs/xxxx/lib/python3.6/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/xxxx/.local/share/virtualenvs/xxxx/lib/python3.6/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning:
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)
```

It is because `matplotlib.rcParams.copy()` returns dictionary of rcParams and it includes deprecated rcParams like `examples.directory` and `text.latex.unicode`. However, `examples.directory` and `text.latex.unicode` are included in the default rcParams of matplotlib.

**Expected outcome**

Do not show MatplotlibDeprecationWarning for default rcParams.

**Matplotlib version**

  * Operating system: macOS Sierra 10.12.6
  * Matplotlib version: 3.0.2
  * Matplotlib backend: Agg
  * Python version: 3.6.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
Until the parameters are actually removed, they are valid and `rcParams.copy()` must copy them if they are in the config. At least in the present master branch they are not included anymore. Can you please check your local config file (path can be obtained using `matplotlib.matplotlib_fname()`) to see if these parameters are set there?

**Comment by koki-sato** [comment]
@timhoffm Thanks for your comment!

There is an empty `matplotlibrc` in the project root.

```python
>>> import matplotlib
>>> print(open(matplotlib.matplotlib_fname()).read())
>>> rc_params = matplotlib.rcParams.copy()

>>> rc_params['examples.directory']
''
>>> rc_params['text.latex.unicode']
True
```

I think [`examples.directory`](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L1451) and [`text.latex.unicode`](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L1133) are included in [defaultParams](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L997-L1483) and [it is used on setup](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L1045-L1050).

**Comment by timhoffm** [comment]
You are right. However, I don't have a clear view how to prevent this.

We cannot remove the parameter unconditionally because someone might be relying that it's there.
One option would be to add a `skip_deprecated` parameter to `copy()`. However, that seems a bit of an overkill and would also not help in other use-cases like iterating over rcParams.

**Comment by koki-sato** [comment]
I also don't have any solutions… 
However, I thought it was inappropriate to display the warning when applying parameters which were included in the default rcParams :(

The most troubling thing on this is that these warnings are displayed when I use [`seaborn`](https://github.com/mwaskom/seaborn) and `seaborn.reset_orig()`. Now, I think this can be controlled in seaborn. So I will create an issue in the seaborn repository.

**Comment by QuLogic** [comment]
I thought we had some machinery to avoid this (or at least a discussion somewhere already).

**Comment by koki-sato** [comment]
I see. Thank you for your responses!

I hit upon two solutions, but I don't think they are good.

1. Deprecated rcParams should be removed from default value.
This will solve the problem, but it will be a big change.

2. Preparing a function which returns a instance of matplotlib.RcParams
`matplotlib.rcParams.update(matplotlib.rcParamsDefault)` don't show warnings. This is because `matplotlib.rcParamsDefault` is not a dictonary but a instance of `matplotlib.RcParams`. So, It is also a way to prepare the following method.

```python
class RcParams(MutableMapping, dict):
    [...]
    def wrapped_copy(self):
	   with warnings.catch_warnings():
	       warnings.simplefilter("ignore", MatplotlibDeprecationWarning)
	       return RcParams(self.copy())
```
