### ISSUE TITLE
No matplotlib C++ High Level API

### ISSUE THREAD

**Issue by lamarrr** [matplotlib/matplotlib#13120]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
Matplotlib is a python library. Why are you expecting a C++ API?

**Comment by timhoffm** [comment]
Thanks for your interest in Matplotlib, but I'm afraid this is not how it works.

At it's core Matplotlib is a python library. Some extensions are written in C, but essential code parts are in python. It's neither technically possible nor intended within the scope of the project to make that available to programming languages other than python.

You'll have to find some C++ targeted plotting library.

**Comment by lamarrr** [comment]
Thank you sir

**Comment by tacaswell** [comment]
Or embed a python interpreter in your c++ application.  Agree with @timhoffm , we are not going to support a c++ API and consider c/c++ extensions we have to be private (so we may change the API on them in a non-back compatible way at any time).
