### ISSUE TITLE
macports package py36-matplotlib depends on obsolete macports package

### ISSUE THREAD

**Issue by nealeyoung** [matplotlib/matplotlib#13130]
### Bug report

Trying to install py36-matplotlib from the current macports (macports version 2.5.4) fails, as py36-matplotlib depends on an obsolete package py36-pyobj-cocoa.

Here are macports instructions that demonstrate the problem

```
% sudo port selfupdate  # updates to MacPorts base version 2.5.4

% sudo port info py36-matplotlib
....
Library Dependencies: ... py36-pyobjc-cocoa ...
...

% sudo port info py36-pyobjc-cocoa
....
Description:          This port is obsolete.
...

% sudo port install py36-matplotlib +cairo 
--->  Computing dependencies for py36-matplotlib
The following dependencies will be installed:  py36-pyobjc-cocoa
Continue? [Y/n]: 
--->  Configuring py36-pyobjc-cocoa
Error: py36-pyobjc-cocoa is obsolete; please uninstall it.
Error: Failed to configure py36-pyobjc-cocoa: obsolete port
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_python_py-pyobjc-cocoa/py36-pyobjc-cocoa/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port py36-matplotlib failed

```
**Matplotlib version**
  * Operating system: Mac OSX 10.14.1
  * Matplotlib version: py36-matplotlib @3.0.2 
  * Python version: Python 3.6.8  installed in /opt/local/bin/python

I believe all relevant packages were installed via macports.

**Comment by QuLogic** [comment]
You will need to report this to macports; we do not have any affiliation with the packages built there.

**Comment by nealeyoung** [comment]
Resubmitted to macports:
[https://trac.macports.org/ticket/57873#ticket](https://trac.macports.org/ticket/57873#ticket)
