### ISSUE TITLE
font family ['serif'] not found. Falling back to DejaVu Sans

### ISSUE THREAD

**Issue by david-waterworth** [matplotlib/matplotlib#13139]
### Bug report

**Bug summary**

I'm intermittently getting the warning `font family ['serif'] not found. Falling back to DejaVu Sans` when plotting with `rc('text', usetex=True)` enabled. If I delete `~\.cache\matplotlib` the warning stops and the charts are rendered with the correct font. But a day or so later it starts again

**Code for reproduction**

Cannot reliably reproduce as intermittent, can reliably fix by deleting `~\.cache\matplotlib`

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.1 x64
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: 

installed from pip

**Comment by anntzer** [comment]
Can you please provide your ~/.cache/matplotlib/fontlist-v300.json before and after deleting ~/.cache/matplotlib (and reimporting matplotlib to regenerate the json)?  Thanks.

**Comment by anntzer** [comment]
"import matplotlib.font_manager" should regenerate it.

**Comment by david-waterworth** [comment]
I had to do it outside jupyter - seems to be ignoring %load_ext autoreload

**Comment by david-waterworth** [comment]
I've attached the fontlist-v300.json files before and after deleting ~/.cache/matplotlib

[fontlist-v300-after.zip](https://github.com/matplotlib/matplotlib/files/2747368/fontlist-v300-after.zip)
[fontlist-v300-before.zip](https://github.com/matplotlib/matplotlib/files/2747369/fontlist-v300-before.zip)

**Comment by david-waterworth** [comment]
I've been playing with a minimal notebook - if I restart kernel and clear outputs, the first time I run the cells below I get the warnings, the 2nd time there's no warning and the 2nd font found is different.

i.e. first run through after restarting kernel:
```
import matplotlib.pyplot as plt
from matplotlib import rc
rc('font',**{'family':'serif','serif':['Computer Modern Roman']})
rc('text', usetex=True)

import matplotlib.font_manager
import os
fm = matplotlib.font_manager.json_load(os.path.expanduser("~/.cache/matplotlib/fontlist-v300.json"))

fm.findfont("serif", rebuild_if_missing=False)
```
> /home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
>   (prop.get_family(), self.defaultFamily[fontext]))
> '/home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf'
```
fm.findfont("serif", fontext="afm", rebuild_if_missing=False)
```
> /home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/font_manager.py:1241: UserWarning: findfont: Font family ['serif'] not found. Falling back to Helvetica.
  (prop.get_family(), self.defaultFamily[fontext]))
> '/home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica.afm'

2nd (and subsequent) run:
```
import matplotlib.pyplot as plt
from matplotlib import rc
rc('font',**{'family':'serif','serif':['Computer Modern Roman']})
rc('text', usetex=True)

import matplotlib.font_manager
import os
fm = matplotlib.font_manager.json_load(os.path.expanduser("~/.cache/matplotlib/fontlist-v300.json"))

fm.findfont("serif", rebuild_if_missing=False)
```
>   (prop.get_family(), self.defaultFamily[fontext]))
> '/home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf'
```
fm.findfont("serif", fontext="afm", rebuild_if_missing=False)
```
> '/home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/afm/phvr8a.afm'

**Comment by anntzer** [comment]
In theory the cache should be reusable across venvs (as long as they all have mpl>=3 (not sure of the exact lower bound)).

When you say no warning on the 2nd+ run, do you mean after restarting the kernel in between? Otherwise that's normal, that's due to the fact that Python keeps track of already emitted warnings and does not emit duplicate warnings (by default).

I still don't understand why deleting and regenerating the cache helps (can you provide your matplotlibrc?  possibly relevant).
However I see at least one "bug" (say, inaccuracy) in the text layouting code now: even when usetex is True, we try to get the font extent using ismath=False, and that's apparently what triggers the warning (because then you need the font, e.g. Computer Modern Roman in your case, to actually be findable by non-tex machinery :/)

**Comment by david-waterworth** [comment]
The 2nd+ run has no restart of the kernel - note though it appears to have found the correct (non-fallback) font on the second run?

I think the deletion of the cache is a red herring. It’s just that the warning is only triggered once and the 2nd time round it finds the requested font (I think)?

**Comment by anntzer** [comment]
Perhaps it should, but it's not clear it is... (both of these fonts are Helvetica)

**Comment by david-waterworth** [comment]
I missed your request to provide my [matplotlibrc.zip](https://github.com/matplotlib/matplotlib/files/2753696/matplotlibrc.zip)

`matplotlib.matplotlib_fname()`
'/home/david/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/matplotlib/mpl-da

I've not customised it, there's nothing in `$HOME/.config/matplotlib`

**Comment by tacaswell** [comment]
possible related to https://github.com/matplotlib/matplotlib/issues/13137

**Comment by anntzer** [comment]
To the best of my guess this should be closed by #13170, @david-waterworth can you try matplotlib master?

**Comment by david-waterworth** [comment]
@anntzer I'm still seeing the warning on master

i.e. (now I get the warning each time, and the reported font path is the same)

```
import matplotlib
import os
matplotlib.font_manager._rebuild()
fm = matplotlib.font_manager.json_load(os.path.expanduser("~/.cache/matplotlib/fontlist-v310.json"))
fm.findfont("serif", rebuild_if_missing=False)
```
> findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
> '/home/david/matplotlib/lib/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf'
```
fm.findfont("serif", fontext="afm", rebuild_if_missing=False)
```
> findfont: Font family ['serif'] not found. Falling back to Helvetica.
> '/home/david/matplotlib/lib/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica.afm'

**Comment by anntzer** [comment]
That's expected; but what about the actual original use case?

**Comment by david-waterworth** [comment]
Behaviour has now changed to writing to logger

> 2019-01-15 09:19:04,932 - matplotlib.font_manager - INFO - findfont: Found a missing font file.  Rebuilding cache.
> 2019-01-15 09:19:05,077 - matplotlib.font_manager - INFO - Could not open font file /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf

**Comment by david-waterworth** [comment]
Thanks @anntzer, master appears to have fixed the original issue (it does now throw an exception with the latex preamble I was using, but I understand that's not supported anyway and I don't need it at this stage)

**Comment by anntzer** [comment]
This is good to close then?

**Comment by david-waterworth** [comment]
I think so. Thanks!

**Comment by vishalmhjn** [comment]
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans

Matplotlib version: 3.1.2

**Comment by nora-illanes** [comment]
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.

I have this issue as well. Python 3.8. Environment wit matplotlib 3.2.1. I am using visual studio code (1.44), launched from anaconda. 
The part of the code with rcParams settings is:
```
`# some lines for the latex font
plt.rcParams['font.size'] = 30
plt.rcParams['font.family'] = "sans-serif"
font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 30
        ,'sans-serif':'Helvetica'}

rc('font', **font)  # pass in the font dict as kwargs
#rc('font', **{'family':'serif','serif':['Palatino']})
rc('latex')
#rc('text', usetex=True)
rc('text')`

usetex is commented out, because a whole new set of errors appear.
What can I do? Removing the cache doesnt help. 
```


[fontlist-v310.zip](https://github.com/matplotlib/matplotlib/files/4571280/fontlist-v310.zip)
[matplotlibrc.zip](https://github.com/matplotlib/matplotlib/files/4571314/matplotlibrc.zip)

**Comment by tfabbri** [comment]
I confirm the same issue. 

Matplotlib version 3.2.1 in a Python 3.7 conda environment executed through Jupyter Lab. 
Removing the cache does not help as well as the installation of all the required packages from latex.

**Comment by Struan-Murray** [comment]
Can confirm above in Matplotlib 3.2.1 but running Python 3.8.2 through terminal.

**Comment by Struan-Murray** [comment]
Running Matplotlib 3.2.1 and Python 3.8.2 I have the same issue but it seems to be triggered by having a legend in the figure. Here is the MWE:
```from matplotlib import rc
import matplotlib.pyplot as plt

rc('font', **{'family':'serif','serif':'Computer Modern'})
rc('text', usetex=True)

plt.figure()
plt.plot(0,0,label='Input')
plt.title('Commenting out legend removes warning')

plt.legend()

plt.show()
```
Commenting out the ```plt.legend``` seems to fix the error.

**Comment by gwangjinkim** [comment]
I also get same problem - Python 3.7.3 from a conda env ubuntu 18.04 LTS.

**Comment by sesise0307** [comment]
https://github.com/matplotlib/matplotlib/issues/17585#issuecomment-653060005
> Can you removing everything in ~/.cache/matplotlib?

This helped me.

**Comment by mbakker7** [comment]
Getting the same error consistently. Python 3.8.2. Matplotlib 3.2.2. Jupyter  Notebook 6.1.1
No error:
```
plt.plot([1, 2, 3], [3, 4, 5], label='test')
plt.xlabel('x-axis') 
#plt.legend()
```
Adding the legend throws an error. 
```
plt.plot([1, 2, 3], [3, 4, 5], label='test')
plt.xlabel('x-axis') 
plt.legend()
```
Error:
```
findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.
```

**Comment by tim-hilt** [comment]
Having the same exact error on Python 3.7.9, Matplotlib 3.3.2 installed via `conda install -c conda-forge matplotlib`. It works without the legend, as mentioned above.

**Comment by anntzer** [comment]
this will be fixed by https://github.com/matplotlib/matplotlib/pull/17521 in 3.4.

**Comment by tim-hilt** [comment]
Thanks for the update! Looking forward to it

**Comment by thangckt** [comment]
I get this with matplotlib 3.4.1

findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.

anyone can help?

**Comment by jklymak** [comment]
@thangckt please open a new issue with reproducible steps.  Thanks...

**Comment by GoingMyWay** [comment]
@thangckt  I think Matplotlib does not provide all fonts. You need to download the font file and install it so that Matplotlib can use it.

**Comment by charelF** [comment]
I had the same problem on macOS with matplotlib 4.3.4, I could solve it with deleting

```~/.matplotlib/fontlist-v330.json```

and then restarting jupyter notebook

**Comment by hkayann** [comment]
`findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.`

This issue still persists. Jupyter run from PyCharm. Lib version is 3.5.1.

**Comment by oscargus** [comment]
Try `matplotlib.font_manager._rebuild()`

**Comment by hkayann** [comment]
@oscargus I get this `AttributeError: module 'matplotlib.font_manager' has no attribute '_rebuild'`

**Comment by DBerke** [comment]
I'm suddenly getting this error on macOS 10.12.6, first with matplotlib 3.4.2 and just now 3.5.1 after upgrading. Removing `~/.matplotlib/fontlist-v330.json` had no effect. Running `matplotlib.font_manager._rebuild()` gave the same error as hkayann above. It was working fine a few months ago when making plots, and I can't think of any major system changes that might have changed anything.

**Comment by anntzer** [comment]
Please provide your fontlist-v330.json?

**Comment by DBerke** [comment]
Here's my [fontlist-v330.json](https://gist.github.com/DBerke/24c3e5f46778f02597583a424ee1e733) file, and this is with usetex on.

**Comment by anntzer** [comment]
I guess we'll need a complete repro example.  There's no font named "stix" or "cm10" in your fontlist.json, and trying to use such fonts in font.serif with usetex results in
> No LaTeX-compatible font found for the serif fontfamily in rcParams. Using default.

if one additionally has `plt.set_loglevel("info")`.

**Comment by DBerke** [comment]
Thanks for taking a look. I was able to fix the problem by simply commenting out the line `font.serif          : stix, cm10` in my matplotlibrc file, which gave me serif fonts in my plot again (since `font.family           : serif` is still uncommented, presumably). I'm not sure why that worked, but I'm content to leave it here now that it's working again, since it looks like a local configuration issue. Thanks for the help.

**Comment by anntzer** [comment]
A full repro example would still be useful, if only so that this doesn't occur again (or perhaps we can make the configuration problem more obvious, etc.).

**Comment by DBerke** [comment]
Ok, I'll try to get one this weekend, I'm pressed for time this week.

**Comment by anntzer** [comment]
No hurries.

**Comment by sakshamg94** [comment]
Same issue. I tried both the solutions proposed here:
- `matplotlib.font_manager._rebuild()`
- removing everything in `~/.cache/matplotlib/` and then restarting Jupyter notebook.
Neither work for me

**Comment by hkayann** [comment]
@sakshamg94 can you try the steps I provided on [SO.](https://stackoverflow.com/a/71356144/14543452)

**Comment by iDTer** [comment]
> @sakshamg94 can you try the steps I provided on [SO.](https://stackoverflow.com/a/71356144/14543452)

didn't help...

**Comment by iDTer** [comment]
Why this bug remains unsolved to this day....

**Comment by lancelot1969** [comment]
Having the same issue but in my case: 
`findfont: Font family ['Heiti TC'] not found. Falling back to DejaVu Sans.`

**Comment by hoochanlon** [comment]
Maybe.

```python
import platform
import os

system = platform.system()

if system == 'Darwin':  # macOS
  font_path = '/System/Library/Fonts/STHeiti Light.ttc'
elif system == 'Windows':
  font_path = 'C:/Windows/Fonts/simhei.ttf'
else:  #  unix
  font_path = 'simhei.ttf'

custom_font = fm.FontProperties(fname=font_path)
```

**Comment by jaweriaamjad** [comment]
I am having a similar issue. I have been trying to set fonts as follows:

`matplotlib.rcParams['font.family'] = "sans-serif"
	matplotlib.rcParams['font.sans-serif'] = "Arial"`

I have also tried with `matplotli.pyplot` but keep getting the following message:

`findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial`

I have looked at the fonts cache and apparently there are not Arial fonts. I have tried removing the cache and regenerating it but the error persists.

[fontlist-v300.zip](https://github.com/matplotlib/matplotlib/files/13279837/fontlist-v300.zip)

**Comment by oscargus** [comment]
@jaweriaamjad it seems like you do not have Arial installed, so that seems like the most likely problem. (Arial is a Microsoft font and it looks from the paths like you are not using Windows? Helvetica is a good replacement, as in Arial is a "copy" of Helvetica.)

**Comment by ZPVIP** [comment]
I have problem to display chinese, I solved the problem by following these steps:
- Download  `SimHei.ttf` font file from internet and save it to python directory, for me, it's `/Users/<username>/venv_3_9/lib/python3.9/site-packages/matplotlib/mpl-data/fonts/ttf`
- Delete `~\.cache\matplotlib` and `~/.matplotlib/*.json`
- Find and delete all metadata of Font file, such as `xattr -l SimHei.ttf`, `xattr -d com.apple.quarantine SimHei.ttf`
- Set font in python script: `import matplotlib.pyplot as plt`, `plt.rcParams['font.sans-serif'] = ['SimHei']`

If it doesn't work , try to reload python environment: `cd /Users/<username>/venv_3_9/bin && deactivate && source ./activate`

**Comment by QuLogic** [comment]
> Download `SimHei.ttf` font file from internet and save it to python directory, for me, it's `/Users/<username>/venv_3_9/lib/python3.9/site-packages/matplotlib/mpl-data/fonts/ttf`

There is no need to put fonts in a system/package directory like this. Matplotlib will read fonts from standard system paths.

**Comment by locorico25** [comment]
Humble attempt here. I am using Ubuntu WSL on Windows and had the same issues anytime I tried to plot anything with matplotlib. I noticed that by doing the following imports the warnings finally disappear:
`import matplotlib as mpl`
`import matplotlib.pyplot as plt`

For me the solution was to add `import matplotlib as mpl`. Hope this can solve the issue!
