### ISSUE TITLE
Matplotlib bug with colors

### ISSUE THREAD

**Issue by knightcube** [matplotlib/matplotlib#13135]
### Bug report

**Bug summary**
I am running this piece of code in Jupyter:
```
import matplotlib.pyplot as plt
import numpy as np
x = np.random.rand(40)
print(x,'\n')
y = np.random.rand(40)
z = np.random.rand(40)
colors = np.random.rand(40)*100
print("colors:",colors)
# plt.style.use('seaborn-white')
plt.scatter(x,y,s=z*1000,c=colors)
plt.show()
```

When this code is run in jupyter with the line - 
`plt.style.use('seaborn-white')`
the graph is shown in black and white.
Commenting it out and running the code again shows the graph in black and white again. 
Restart the kernel and run the code again keeping the  line - "plt.style.use('seaborn-white')" commented out. A colorful graph is shown as must be the case. 
However if you put the line back in the code and run it again, it shows black and white graph. 
Now again if you comment it out and run the code again without restarting the kernel it shows black and white again. This should not be the case. It should show colored graph.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
x = np.random.rand(40)
print(x,'\n')
y = np.random.rand(40)
z = np.random.rand(40)
colors = np.random.rand(40)*100
print("colors:",colors)
# plt.style.use('seaborn-white')
plt.scatter(x,y,s=z*1000,c=colors)
plt.show()
```

**Actual outcome**
Output should be colored according to the code. Seems like the plt.style.use('seaborn-white') when run it sets black and white by default and until and unless we don't restart the kernel it does not show a colored graph.

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries:

**Comment by QuLogic** [comment]
This is expected behaviour; changing the style is permanent. If you want to change the style temporarily, you can use a style context as in [the style sheet tutorial](https://matplotlib.org/tutorials/introductory/customizing.html#temporary-styling).

**Comment by knightcube** [comment]
Oh I see. Thanks for clearing the confusion :)
