### ISSUE TITLE
Animation blitting with small interval : black zones

### ISSUE THREAD

**Issue by Lahorde** [matplotlib/matplotlib#13143]
### Bug report

**Bug summary**

If plot interval delay is too short. Some black zone around plot are displayed.
Increasing animation interval solves this issue. Before starting animation I have to be sure figure has been drawn().

![bug_blit](https://user-images.githubusercontent.com/5982137/50953763-abc51700-14b4-11e9-8242-432a7e5ff824.PNG)

[I posted about this issue on stackoverflow](https://stackoverflow.com/questions/54116398/matplotlib-animation-blitting-black-zone?noredirect=1#comment95070996_54116398)

**Code for reproduction**

```
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

def update_fig(num, data, plot, ax) :
    text = None
    if num % 2 == 0 :
        text = ax.text(0.5, 0.5, str(num), horizontalalignment='center', verticalalignment='center', transform=ax.transAxes,size=15)
    plot.set_array(data[:, :, num %1500].ravel())
    if text : 
        return pp_color, text,
    else :
        return pp_color,

fig, ax = plt.subplots()
data = np.random.rand(60, 50, 1500)
pp_color = plt.pcolormesh(data[:,:, 0], cmap = 'Reds', vmin=np.amin(data), vmax=np.amax(data))
cbar = plt.colorbar()
t1 = cbar.ax.set_title('t1')
plt.axis('equal')
ax.text(0.5, -0.1, 'footnote text', horizontalalignment='center', transform=ax.transAxes,)
t2 = ax.set_title("t2")
line_ani = animation.FuncAnimation(fig, update_fig,
                                   interval=0.1, blit=True, fargs=(data, pp_color, ax))
plt.show()
```

**Matplotlib version**
  * Operating system: windows 10
  * Matplotlib version:  matplotlib.__version__
Out[99]: '2.2.3'
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 3.7.0

**Comment by deichdeich** [comment]
I am also experiencing this bug, but when I increase the interval, the black bars remain.

I'm on mpl v. 3.0.3 on macOS 10.12

**Comment by lumasullo** [comment]
I am experiencing the same bug, it's not solved by increasing the interval

**Comment by fhartenbach** [comment]
I produced this bug as well. I had to increase the interval to 50(ms) to "get rid" of it. However this is not an acceptable solution for me.
