### ISSUE TITLE
widgets.RadioButtons: select by closest in position

### ISSUE THREAD

**Issue by mromanie** [matplotlib/matplotlib#13145]
Mine is actually a suggestion, not a bug report. I would find it useful if in the RadioButton widget the selected  button were the one spatially closest to the mouse click (within the button circle), rather than the first match found scrolling down the list.

**Matplotlib version**

  * Operating system: Mac OS 10.11.6
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.7 
  * Jupyter version (if applicable):
  * Other libraries: 

conda

**Comment by timhoffm** [comment]
Sorry, I cannot follow your suggestion. Can you please rephrase it, or add a screenshot for illustration.

AFAIK, a mouse click selects a button if you either click on the button circle or on the associated label.

**Comment by mromanie** [comment]
Many thanks for your answer and apologies for not being clearer! What I mean is best illustrated with the attached example, adapted from my actual code (test.py, which I run with Python 3.6.7 and matplotlib 3.0.2, both installed from conda). 

For example, clicking on the circle of button '20' selects button '19', instead (clicking on the label works as expected).

This is linked to the resizing of the buttons (function adjustRadio), which I do to make them look better (they would otherwise be way too thin, given the elongated aspect ration of the axes). What happens is that, after resizing, both button '19' and '20' fulfil the "proximity clause" in the RadioButtons class:

`np.linalg.norm(pclicked - p.center) < p.radius`

and the first button to do so is picked and activated, which is the wrong one ('19' vs '20').

This may be solved by modifying the button activation criterion to pick the closest button to the mouse click among those that meet the "proximity clause" (modified widgetsMRO.py also attached).


[widgetTest.zip](https://github.com/matplotlib/matplotlib/files/2748603/widgetTest.zip)

**Comment by timhoffm** [comment]
Thanks for the clarification. It seems you have already dived into the issue and your proposed fix sounds reasonable. Would you be willing to create a pull request?

**Comment by QuLogic** [comment]
Closed by #13268.
