### ISSUE TITLE
DOC: matplotlib.pyplot.arrow

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#13156]
> The x/y-coordinate of the arrow base.

Shouldn't that say something like this?:

> The x and y coordinates of the arrow base.

There is no division going on here.

**Comment by timhoffm** [comment]
A slash can be used in the sense of „or“ 
https://en.m.wikipedia.org/wiki/Slash_(punctuation)#XOR.

So technically, this is valid. Feel free to submit a PR, if you think this may be misleading to readers.

**Comment by DumbMachine** [comment]
Which file is this issue present in?

**Comment by DumbMachine** [comment]
If this still requires to be fixed, could you mention which file this is present in?

**Comment by timhoffm** [comment]
Not sure this really needs fixing, but OTOH rewriting doesn‘t hurt either.  The relevant code is the arrow docstring in matplotlib/axes/_axes.py

**Comment by QuLogic** [comment]
Fixed by #13165.
