### ISSUE TITLE
plt.contourf for magnetic field mapping

### ISSUE THREAD

**Issue by NTUwilliam** [matplotlib/matplotlib#13160]
Hi all !

What I'm trying to do is to map the magnetic field on my own dataset. The **magnetic field map** that I wanna get is something like this ( built by Matlab on the same dataset, unmeasured part removed in the middle part of this graph): 
![map](https://user-images.githubusercontent.com/43923666/51032522-533c6980-15db-11e9-8188-4343e320dd4d.jpg)

However, when I want to use the **matplotlib.pyplot.contourf** to get a similar map, I failed. The graph below is what I get:
![python_map](https://user-images.githubusercontent.com/43923666/51032623-b4643d00-15db-11e9-80a3-35d4c3d7c4c5.png)

The `python` code I'm using for mapping is: 

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

z = pd.read_excel('/home/williamwoo/Desktop/Associated_data3_A_block.xlsx', sheet_name='Sheet1')

x = z ['pos_x']
y = z ['pos_y']

u = z ['mag_x']
v = z ['mag_y']
w = z ['mag_z']

X, Y =np.meshgrid(x, y)

U, V =np.meshgrid(u, v)                                                 
Z = np.sqrt(U**2+V**2)          

m = plt.contourf(X, Y, Z, cmap=plt.cm.jet)
cbar=plt.colorbar(m,orientation='vertical')                             
cbar.set_label('Magnetic Field Strength ($\mu$T)', rotation=270)

plt.title('Magnetic Field Map')
plt.xlabel('$Direction  X$ (m)')
plt.ylabel('$Direction  Y$ (m)')

plt.show()
```

My dataset has 10 columns: 
- first 3 columns are the position x/y/z; 
- 4-7 columns are the quaternions;
- last three columns (8-10) are the collected magnetic field data x/y/z.

My dataset is here:
[Associated_data3_A_block.xlsx](https://github.com/matplotlib/matplotlib/files/2749529/Associated_data3_A_block.xlsx)

I think something's wrong with the **parameter Z**. Because for the function `plt.contourf`, the parameter **Z** must be a **2D array**. 
But since my magnetic field data is a 3D vector [x, y, z], I have no idea how to correctly change the 3D vector into a 2D array. So I'm sure the `Z = np.sqrt(U**2+V**2)` I used in the python code is wrong.

Shall I use some function like `reshape`?
Does anyone have any hint or advice for this?

Thanks in advance!!

**Comment by timhoffm** [comment]
This is the issue tracker for Matplotlib which is for bug reports. However, your problem looks more like a data handling/usage problem. Please use one of the following way to get help:

- [gitter channel](https://gitter.im/matplotlib/matplotlib)
- [matplotlib users mailinglist](https://mail.python.org/mailman/listinfo/matplotlib-users)
- [stackoverflow](http://stackoverflow.com/questions/tagged/matplotlib)

Some hints (without full discussion):

- Your data is just a line of points. I don't see how one can generate the map you've shown in your first image. There's no information lateral to the line and if you've generated the above image from the same data, the structure is heavily dominated from the rendering algorithm you've used.
- IMHO, the best you can do is, some sort of scatter plot.
  ~~~
  plt.figure(figsize=(6, 9))
  plt.gca().set_aspect('equal')
  plt.scatter(x, y, c=np.sqrt(u**2 + v**2), cmap='jet')
  plt.colorbar()
  ~~~
  
  ![grafik](https://user-images.githubusercontent.com/2836374/51076148-2c426e00-1695-11e9-9555-6e5171527755.png)

- Note also that `contourf` is for drawing contour lines for data on a rectangular grid, which you do not have.

**Comment by QuLogic** [comment]
The problem with scatter is that it overprints and so looks a little weird. I think this [multicoloured line example](https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html) might be a bit nicer (just set a wide width).

**Comment by NTUwilliam** [comment]
@timhoffm Thanks for your advice and hints !
Yes, the map shown in the first image was built by Gaussian Process in Matlab to predict the magnetic field value of the unmeasured area so that's why the generated map is wider than the actual path.
I've implemented `scatter plot` and it works quite well.


@QuLogic Thanks for your advice. I'm trying that.

**Comment by dstansby** [comment]
Since this seems to be fixed, I'm going to close this.

**Comment by NTUwilliam** [comment]
@timhoffm @QuLogic @dstansby 
Sorry for bothering again. I've posted the issue on stackoverflow but no one answered so I came back to here. 

Actually I've plotted magnetic field of the 4 robot paths covering almost the whole testing area, by using the **`plt.scatter`**, as shown below:
![B-block-1234combined-need-improvement](https://user-images.githubusercontent.com/43923666/54874738-38cd0a80-4e2c-11e9-88ca-e9c6f84a9ef4.png)

However, what I'm trying to get is a **smoothed magnetic field map** of the whole area by **interpolating** the existing data I have. The smoothed map, for example, is something like this:
![Fig 1](https://user-images.githubusercontent.com/43923666/54874775-d7f20200-4e2c-11e9-912c-2f2841e74d7d.jpg)


I've tried to use `scipy.interpolate.griddata` and `imshow`, but the debugging process keep warning me that the `X, Y = np.meshgrid(x, y)` has **MemoryError** or the `m = interpolate.griddata(points, values, (x, y), method='cubic')` has **invalid number of dimensions** in `(x, y)`. 
 
My code is below:

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import interpolate


z = pd.read_excel('/home/williamwoo/Desktop/Mag_Map/03-17-B-Mag-1234combined.xlsx', sheet_name='Sheet1')

x = z ['pos_x']
y = z ['pos_y']

u = z ['mag_x']
v = z ['mag_y']
w = z ['mag_z']

X, Y = np.meshgrid(x, y)
points = (68166, 2)
values = np.sqrt(u**2+v**2+w**2)

plt.figure(figsize=(20, 10))
plt.gca().set_aspect('equal')

m = interpolate.griddata(points, values, (X, Y), method='cubic')
plt.imshow(m, extent=(0,58,0,20), origin='lower')

n = plt.colorbar(m, shrink=0.6)                               
n.set_label('Magnetic Field Strength ($\mu$T)', rotation=270, size=15, labelpad=15)


plt.title('Magnetic Field Map', size=20)
plt.xlabel('$Direction  X$ (m)', size=15)
plt.ylabel('$Direction  Y$ (m)', size=15)

plt.show()
```

My dataset has 5 columns, 68166 rows of data in total: 
- first 3 columns are the collected magnetic field data x/y/z; 
- 4-5 columns are the 2D position X/Y.
It can be downloaded in [here](https://www.dropbox.com/s/5sjczsjta9t8jt7/03-17-B-Mag-1234combined.xlsx?dl=0)


So am I using the wrong interpolation function and complicate the process? Do you have any idea how to get the **smoothed magnetic field map** of the whole testing area?
Any hint or advice is appreciated.

Thanks a lot!

**Comment by timhoffm** [comment]
I think, using `scipy.interpolate.griddata` and `imshow` is right. No matter what interpolation you use, it cannot know that you want only certain areas to be interpolated. You should convert your corridor map to the same grid and mask out the parts of the interpolation result that you do not want.

**Comment by NTUwilliam** [comment]
@timhoffm Noted with thanks.

@dstansby Could you please **re-open** this issue? I still can't get it solved.

**Comment by dstansby** [comment]
I think it might be worth asking this question on the scipy mailing list (https://scipy.org/scipylib/mailing-lists.html), since the question is not really about Matplotlib but how `scipy.interpolate.griddata` interpolates the data.
