### ISSUE TITLE
Figures in windows not tabs

### ISSUE THREAD

**Issue by hutattedonmyarm** [matplotlib/matplotlib#13164]
I want to create multiple figure with Matplotlib in python, using the macosx backend. Currently, my code looks something like this:

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2, 100)

f1 = plt.figure(1)
plt.plot(x,x**2)

f2 = plt.figure(2)
plt.plot(x,x**2)
plt.show()
```

This creates a single window, with two tabs. One for figure 1, and one for figure 2. I suggest an option to open them in separate windows.

Note that the tabs likely come from the automatic tab-support built into the OS since macOS 10.12
**Matplotlib version**

  * Operating system: macOS 10.14.3
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.1
  * Jupyter version (if applicable): -
  * Other libraries: -
  * Installed via: pip
  * Python installation via pyenv

**Comment by ImportanceOfBeingErnest** [comment]
It seems this an OS "feature". Is [this](https://discussions.apple.com/thread/7852724) of any help?

**Comment by tacaswell** [comment]
@hutattedonmyarm I think we are :+1:  adding that feature to atleast the OSX backend (as it is clearly mac-specific) if you are interested in implementing it.

For the other backends, it would need to be done in a way that does not affect non-OSX users.

**Comment by hutattedonmyarm** [comment]
I played with the source a bit. I managed to change the behavior, but it should be optional. I'm assuming this would be set using rcParams, or maybe as a backend function? I'm very new to using Matplotlib, so not sure what the best way is

**Comment by tacaswell** [comment]
We do have precedence for GUI specific rcparams (`osx.figure_mode` ?), I do not think we have precedence for backend specific static methods.

It may also be that this is best done as a documentation PR showing how to change the application settings.

**Comment by hutattedonmyarm** [comment]
Alright, will use rcparams then. I'll have to find how to read the params, and then update the docs
