### ISSUE TITLE
cycler mixing (cross product) results in repeated adjacent properties

### ISSUE THREAD

**Issue by bjmuld** [matplotlib/matplotlib#13174]
### Bug report

**Bug summary**

Composing two property cyclers yields a cycler which stays on one property value for multiple calls

```python
from matplotlib.pyplot import cycler

prop_orders = {
    'color': ['k', 'r', 'g', 'b', 'c', 'm', 'y'],
    'marker': ['.', 'o', 'v', 's', '*'],
    'linestyle': ['-', '--', '-.', ':'],
    'hatch': ('-', '+', 'x', '\\', '*', 'o', 'O', '.'),
}

a=cycler('color', prop_orders['color'])
b=cycler('marker', prop_orders['marker'])

c = (a*b)()

print(next(c))
print(next(c))
```

**Actual outcome**

```
{'color': 'k', 'marker': '.'}
{'color': 'k', 'marker': 'o'}
```

**Expected outcome**
I would expect both attributes to be actively cycling, i.e.
```
{'color': 'k', 'marker': '.'}
{'color': 'r', 'marker': 'o'}
```

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:  3.6.8 (Anaconda)
  * Jupyter version (if applicable):  n/a
  * Other libraries: 

(mini)conda installation

**Comment by bjmuld** [comment]
moving to matplotlib/cyclers

**Comment by tacaswell** [comment]
xref https://github.com/matplotlib/cycler/issues/50
