### ISSUE TITLE
qt4backend zoom-to-rect box is drawn incorrectly on OSX

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#1318]
Only on OSX:

```python
import matplotlib
matplotlib.use("qt4agg")
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()
```
Now click zoom-to-rect; instead of a solid rectangle outline, I get a dotted L-shape.

This is with mpl v1.2.x, 7f5b00526b92, pyqt 4.9.4 from homebrew, OS X 10.8.

**Comment by tacaswell** [comment]
@efiring Did the qt5 related refactor and/or general system upgrades magically fix this?

**Comment by efiring** [comment]
I don't see it now with 1.4.3 or 1.5.x using anaconda, on the same machine as before, but with OSX 10.9 rather than 10.8.  So something fixed it.
