### ISSUE TITLE
Locators off by one day

### ISSUE THREAD

**Issue by matmcnic** [matplotlib/matplotlib#13185]
### Bug report

**Bug summary**

When using any of the Locators the date calculation (x axis labels) are off by one day sometimes. This occurs when the x data is a list of contiguous dates. If the dates are not contiguous the problem does not occur.

-Using data from a list of contiguous dates:
--problem occurs
--ax.get_xticks() shows that Epoch from Jan 01, 1970 is used

-Using data from a list with non-contiguous dates:
--problem does not occur
--ax.get_xticks() shows that Epoch from Jan 01, 0000 is used

This seems to be a problem in how a date is calculated given an Epoch number of days when the Epoch Jan 01, 1970 is used.  Perhaps because some systems use 0 and some use 1 as the first day Jan 01, 1970?

**Code for reproduction**

```python
import pandas as pd 
import datetime
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter, DayLocator
import matplotlib.ticker as ticker
import matplotlib.dates as mdates
#%matplotlib inline

#comment out any day to show the example with non-contiguous dates
d = {
    '2017-10-01': 20,
    '2017-10-02': 20,
    '2017-10-03': 15,
    '2017-10-04': 1,
    '2017-10-05': 118,
    '2017-10-06': 16,
}

df = pd.DataFrame(list(d.items()), columns=['DATE', 'TMIN'])
df['DATE'] = df['DATE'].astype('datetime64[ns]')

fig, ax = plt.subplots(figsize=(8, 4))

df.plot(x='DATE', y='TMIN', kind='line', ax=ax)

ax.xaxis.set_major_locator(mdates.DayLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter("\n%b%d"));

#Turn off minor ticks
ax.xaxis.set_minor_formatter(mdates.DateFormatter(""));

ax.grid(True, which='both')

print(ax.get_xticks())
```

**Actual outcome**

![bugreport](https://user-images.githubusercontent.com/15078200/51133587-6893dc80-1803-11e9-8f38-728efb24fc26.png)

For contiguous data the x axis labels are off by one day.
Also notice the print(ax.get_xticks()) -- you can see that for contiguous data it uses Epoch 1970 and for non-contiguous it uses Epoch 0000

Examples from print(ax.get_xticks()) (notice different Epochs used)
Contiguous data: [17440. 17441. 17442. 17443. 17444. 17445.]
Non-contiguous data: [736603. 736604. 736605. 736606. 736607. 736608.]

**Matplotlib version**

  * Operating system: Windows 8.1 x64
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD6
4)]
  * Jupyter version (if applicable): Notebook server is: 5.7.4 (problem occurs both in console and in Jupyter)
  * Other libraries: pandas  0.23.4

All installs are from Anaconda follwed by conda update --all

**Comment by jklymak** [comment]
A couple of things.  
First the epoch issue is a pandas difference.    If you use numpy datetime64 or datetime, this isn't a problem.  Pandas has their own locators, formatters *and* unit converters.  So at its root I think this is a pandas issue.  Did you bring it up there?  

That being said, if you set the locator *before* you plot the data the code you are using works as I think you expect.

**Comment by matmcnic** [comment]
Formatter is OK as I do use matplotlib.dates formatter:
```
from matplotlib.dates import DateFormatter
ax.xaxis.set_major_locator(mdates.DayLocator())
```

> ...you need to specify the x_compat=True parameter.

Changing my code as you said above to fixed the issue!
```
ax = df.plot(..., x_compat=True)
```

**Comment by matmcnic** [comment]
Based on comments above, this is not a bug.

**Comment by matmcnic** [comment]
Based on comments above, this is not a bug.
