### ISSUE TITLE
Typo in add_subplot() docstring

### ISSUE THREAD

**Issue by pylang** [matplotlib/matplotlib#13191]
### Bug report

**Bug summary**

I believe there is a typo in the `add_subplot()` docstring.  When tab completing in jupyter, I get the following:

**Code for reproduction**

```python
>>> fig = plt.figure()
>>> fig.add_subplot(1, 1, 1 <TAB>)
```

**Actual outcome**

```python
"""
Signature: fig.add_subplot(*args, **kwargs)
Docstring:
Add a subplot.

Parameters
----------
*args
    Either a 3-digit integer or three separate integers
    describing the position of the subplot. If the three
    integers are I, J, and K, the subplot is the Ith plot on a
    grid with J rows and K columns.
...
"""
```

**Expected outcome**

Assuming intergers `(add_subplot(I, J, K))`, I believe it should say:

>    ... If the three
>    integers are I, J, and K, the subplot is the **Kth** plot on a
>    grid with **I** rows and **J** columns.

**Matplotlib version**

  * Operating system: Windows 7
  * Matplotlib version: '2.1.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`): inline
  * Python version: Python 3.6
  * Jupyter version (if applicable): '5.3.0'+
  * Other libraries:

**Comment by jklymak** [comment]
Thanks for the report.  This doc string has undergone substantial revision since 2.1.2 and is now correct, so I’m going to close this.
