### ISSUE TITLE
demo_parasite_axes2 doesn't work as expected

### ISSUE THREAD

**Issue by floggle** [matplotlib/matplotlib#13193]
This demo:
https://matplotlib.org/examples/axes_grid/demo_parasite_axes2.html

If I copy/paste all the code from that, the output is a graph doesn't have the "Temperature" axis - neither the axis label, nor the tick labels are there.

**Comment by QuLogic** [comment]
Are you using the latest version of Matplotlib?

**Comment by ImportanceOfBeingErnest** [comment]
You are referring to the example from the documentation of matplotlib 2.0.2. Unless you are using that version you might rather refer to the example of the version in use. For the latest 3.0.2, that example would be found [here](https://matplotlib.org/gallery/axisartist/demo_parasite_axes2.html). 

In general, also consider not using the axes grid for the sole purpose of parasite axes (other applications may still make it desireable, though), but rather [Multiple Yaxis With Spines](https://matplotlib.org/gallery/ticks_and_spines/multiple_yaxis_with_spines.html).

**Comment by floggle** [comment]
I'm new to Matplotlib. I simply did "pip install matplotlib" on my python 3.6, and then tried the example.

There's nothing on that page that clearly states it only works with certain versions.

**Comment by jklymak** [comment]
Agreed - its super annoying that old pages don't disappear from the main site's tree.  But no one has come up/implimented a way to fix that.

**Comment by dstansby** [comment]
Can someone manually delete all the pages in `/examples`? (cc @tacaswell)

**Comment by jklymak** [comment]
The problem is that 404s all the exiting internet links out there.

**Comment by floggle** [comment]
Stick a big warning at the top of the page "This example is deprecated and for version X. Current examples are found at example.com/current."

**Comment by jklymak** [comment]
Modern matplotlib docs have a new header that has the version in it.  

I think it wouldn't be a huge lift to add a banner to the old versions, at least those pre 3.0....

**Comment by floggle** [comment]
I'd also suggest setting robots.txt to not crawl them. If they're all in the same directory, that's an easy one-line fix.
Of course, you don't even seem to have a robots.txt, so it's about a 3 line fix instead - https://matplotlib.org/robots.txt

```
Disallow: *
/example
```

**Comment by floggle** [comment]
And while fixing outdated pages, this just came up as a high result for one of my searches:
https://matplotlib.org/users/style_sheets.html

Oooh, there's a new version, `2.0.0rc2`! :-o .... :-/

**Comment by jklymak** [comment]
I think we would actually accept help with this. OTOH, I'm not quite clear how we make low-level chnges to the docs  https://github.com/matplotlib/matplotlib.github.com

**Comment by QuLogic** [comment]
☹️ Oh, it's the outdated docs. This is (unfortunately) duplicated in various issues (e.g., #10016, #12374, etc.), so I don't think there's any need to leave this one open.
