### ISSUE TITLE
macosx backend lacks support for cursor-type widgets

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#1319]
In examples/widgets, the cursor, lasso_selector, multicursor, rectangle_selector, and span_selector all fail with macosx backend because of unimplemented features including, but perhaps not limited to, FigureCanvasMac.copy_from_bbox().

As a first step in keeping track of macosx anomalies, it would be nice to have all known limitations described in the module docstring.

It would probably also make sense to add the copy_from_bbox method, having it raise an UnimplementedError with a useful message to let the user know that this is a known limitation.

A note in the overall mpl docs would also be helpful.

**Comment by mdboom** [comment]
Fixed by #6178
