### ISSUE TITLE
MPL 3 + Colorbar + PowerNorm bug

### ISSUE THREAD

**Issue by LevN0** [matplotlib/matplotlib#13228]
### Bug report

**Bug summary**

In MPL v3, when using Colorbar with a linear norm, then changing norm to PowerNorm, breaks the Colorbar under some circumstances. Worked fine in MPL v1 and v2.

**Code for reproduction**

Minimum necessary test case:

```python

fig, ax = plt.subplots()

data = np.clip(randn(250, 250)*10, 0, 10)

cax = ax.imshow(data)
cbar = fig.colorbar(cax)

cax.norm = mpl.colors.PowerNorm(gamma=2, vmin=0, vmax=10)
cbar.set_norm(cax.norm)
cbar.update_normal(cax)

plt.show()
```

On matplotlib 3.0.2 the (bug?) result is:

![mpl_3](https://user-images.githubusercontent.com/15056721/51431082-03b8f780-1bf2-11e9-940f-0427eb09bba2.png)

On matplotlib 2.2.3 the (expected) result is:

![mpl_2](https://user-images.githubusercontent.com/15056721/51431080-f7cd3580-1bf1-11e9-8127-a5739d330221.png)

Result when adding LogNorm to ``ColorbarBase._use_auto_colorbar_locator`` (see discussion below) on matplotlib 3.0.2

![mpl_3_fixed](https://user-images.githubusercontent.com/15056721/51431077-f1d75480-1bf1-11e9-8883-3a0c4151c7e5.png)

**Discussion**

Few points:

1) If the image's norm is set prior to ``fig.colorbar``, then the expected result is achieved on 3.0.2 as well. 
2) If vmin/vmax are not set, the result seems correct and matches between 3.0.2 and 2.2.3
3) ``cbar.update_bruteforce`` instead of update_normal does not fix the issue

I looked into the colorbar code, and can see the following: 

   In ``ColorbarBase.update_ticks()``, if the auto-colorbar is first used (i.e. first branch), then setting PowerNorm calls the second branch (i.e. what it calls the fixed locator branch) once ``Colorbar.update_normal`` runs. That exact sequence triggers the issue.

 If things are forced to the first branch of ``ColorbarBase.update_ticks()`` (e.g. via adding to PowerNorm to ``ColorbarBase._use_auto_colorbar_locator()`` ), then a similar result to what one gets from MPL 3.0.2 LogNorm is achieved. If things are forced to the second branch, then the result from MPL 2.2.3 is achieved. However, when first one branch is hit and then PowerNorm hits the second branch, this triggers the issue. 

Relevant code from ColorbarBase,

``` python

    def _use_auto_colorbar_locator(self):

        return (self.boundaries is None
                and self.values is None
                and ((type(self.norm) == colors.Normalize)
                    or (type(self.norm) == colors.LogNorm)))

    def update_ticks():

        # ... 

        if self._use_auto_colorbar_locator():
            _log.debug('Using auto colorbar locator on colorbar')
            _log.debug('locator: %r', locator)
            long_axis.set_major_locator(locator)
            long_axis.set_major_formatter(formatter)
        else:
            _log.debug('Using fixed locator on colorbar')
            ticks, ticklabels, offset_string = self._ticker(locator, formatter)
            long_axis.set_ticks(ticks)
            long_axis.set_ticklabels(ticklabels)
            long_axis.get_major_formatter().set_offset_string(offset_string)
```

**Expected outcome**

Either: 
  1. functionality of MPL 2.2.3 
  2. functionality of adding PowerNorm to ``ColorbarBase._use_auto_colorbar_locator``.

**Comment by jklymak** [comment]
Not fully parsing this. But if PowerNorm is added to the list in _use_auto_color_locator does everything work?  

Note colorbar handling was changed 3.0 for as many cases as possible but it’s possible that it doesn’t fit this pattern of calling things.

**Comment by QuLogic** [comment]
This looks something like #12682.

**Comment by jklymak** [comment]
1. I don't think you should (need) to call `cbar.set_norm(cax.norm)`.  If you change the mappable, we should be able to deal with the new norm on the mappable.
2. `update_normal` and `update_bruteforce` are definitely messed up.  

My test code uses `LogNorm`, just to make it clear that the issue is not `PowerNorm`.

```python
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

N = 100
X, Y = np.mgrid[0:3:complex(0, N), 0:2:complex(0, N)]
Z1 = (1 + np.sin(Y * 10.)) * X**(2.)

print(np.min(Z1))
data = Z1

fig, ax = plt.subplots(2, 2, constrained_layout=True)
ax = ax.flat

cax = ax[0].pcolormesh(data, cmap='RdBu_r', rasterized=True)
# , norm=mpl.colors.PowerNorm(gamma=2, vmin=0, vmax=50))
cbar = fig.colorbar(cax, ax = ax[0])

cax = ax[1].pcolormesh(data, cmap='RdBu_r', norm=mpl.colors.LogNorm(vmin=0.001, vmax=18), rasterized=True)
cbar = fig.colorbar(cax, ax=ax[1])

cax = ax[2].pcolormesh(data, cmap='RdBu_r', rasterized=True)
cbar = fig.colorbar(cax, ax=ax[2])
cax.set_norm(mpl.colors.LogNorm(vmin=0.001, vmax=18))
cbar.update_bruteforce(cax)

cax = ax[3].pcolormesh(data, cmap='RdBu_r', rasterized=True)
cbar = fig.colorbar(cax, ax=ax[3])
cax.set_norm(mpl.colors.LogNorm(vmin=0.001, vmax=18))
cbar.update_normal(cax)

plt.show()
```

![figure_1dsada](https://user-images.githubusercontent.com/1562854/51433547-a7f66a80-1c01-11e9-8266-2f533bc5e234.png)

**Comment by LevN0** [comment]
@jklymak - Yes, the specific issue I reported with PowerNorm does appear to work if added to _use_auto_color_locator, though I did limited experimentation. See 3rd image in above report for what that particular result looks like if that change was made. I am not exactly sure why hitting the second branch after running the first produces such a strange outcome though, I could not dig down that far. Some solution to the issue would be great, because this has worked since at least ~v1.0. 

Regarding LogNorm, I am not actually seeing much change in your test code/plots compared to behavior in 2.2.3. Some things are clearly inconsistent, but at least all of them can be fixed with a couple lines of code. The issue at the top is different between 2.2.3 and 3.0.2, and the only way I can see to fix them is to revert the action of  ``long_axis.set_major_locator(locator)`` and ``long_axis.set_major_formatter(formatter)``, and this is new behavior.  Actually there was an additional thing introduced in that LogNorm sets log axis for colorbar as of MPL v3, but update_normal does not revert to linear if the norm is changed - this is kind of unfortunate, though at least update_bruteforce does work in that case. The PowerNorm issue is not only new, but also not resolved with either update_normal or update_bruteforce.

@QuLogic - Agreed on similarity.

**Comment by jklymak** [comment]
OK, Thanks.  sure we can make this work - I just had no idea folks would set the norm post-facto so that never got tested.  Clearly our testing is inadequate for this feature.  But if the above is a good enough test, then I think we can figure out how to make `update_normal` work.

Maybe someone should comment on what the*idea* behaviour should be here.  To me:
```
cax = ax[2].pcolormesh(data, cmap='RdBu_r', rasterized=True)
cbar = fig.colorbar(cax, ax=ax[2])
cax.set_norm(mpl.colors.LogNorm(vmin=0.001, vmax=18))
```
should just work, and we shouldn't have to call anything like `update_normal` or `update_bruteforce`. 

ping @efiring because I think he will know the history here...

**Comment by LevN0** [comment]
> sure we can make this work 

Sounds good to me! 

>I just had no idea folks would set the norm post-facto so that never got tested. 

To explain a bit of reasoning here, the application in question allows user to change the norm. So it comes up as linear by default, but lets them change norm and min/max of norm. Similar to functionality of e.g. SAO DS9.

**Comment by jklymak** [comment]
Are you able to download PRs and test from the dev version?  I think I have a fix, but it'd be good to know it works for you

**Comment by jklymak** [comment]
OK, I'd propose that changing the norm resets the locator and formatter to whatever the default is for that norm, so if you want to specify ticks, you'd need to do so again after changing the norm.   So the following

```python 
fig, ax = plt.subplots()
cax = ax.pcolormesh(data, cmap='RdBu_r', rasterized=True)
cbar = fig.colorbar(cax, ax=ax)

print('original', cbar.locator)
cbar.set_ticks([0, 10, 20])
print('first set ticks', cbar.locator)
cax.set_norm(mpl.colors.PowerNorm(gamma=2, vmin=0.001, vmax=18))
print('after norm changed', cbar.locator)
cbar.set_ticks(np.arange(0, 20, 2))
print('after ticks set second time', cbar.locator)
plt.show()
```

gives 
```
original <matplotlib.colorbar._ColorbarAutoLocator object at 0x127311be0>
first set ticks <matplotlib.ticker.FixedLocator object at 0x127351320>
after norm changed <matplotlib.colorbar._ColorbarAutoLocator object at 0x127311d68>
after ticks set second time <matplotlib.ticker.FixedLocator object at 0x1272f1080>
```

**Comment by LevN0** [comment]
I noticed that,

```python

    def update_ticks():

        # ... 

        if self._use_auto_colorbar_locator():
            _log.debug('Using auto colorbar locator on colorbar')
            _log.debug('locator: %r', locator)
            long_axis.set_major_locator(locator)
            long_axis.set_major_formatter(formatter)
        else:
            _log.debug('Using fixed locator on colorbar')
            locator.set_axis(None)                                                                       # new line
            formatter.set_axis(None)                                                                   # new line
            ticks, ticklabels, offset_string = self._ticker(locator, formatter)
            long_axis.set_ticks(ticks)
            long_axis.set_ticklabels(ticklabels)
            long_axis.get_major_formatter().set_offset_string(offset_string)
```

Adding the two new lines, that reset the axis prior to ``self._ticker`` seems to cure the originally reported issue. Internally ``self._ticker`` calls create_dummy_axis on both locator and formatter, so perhaps it is not supposed to have any other axis prior to that? I do not have sufficient understanding to know what ill effects it might have though.

**Comment by jklymak** [comment]
@LevN0 Can you check vs #13234 and post any code that doesn't work there?  I'm not sure how you are getting into the `else:` part of that loop.

**Comment by LevN0** [comment]
@jklymak Apologies, did not realize there had been a further change in the PR since it was first referenced.

Indeed, the linear -> PowerNorm -> linear works here. Thank you!

A couple possibly related questions. Not sure if another issue would be more appropriate for the first. Here is a test case,

```python

fig, ax = plt.subplots()

data = randn(250, 250)*1000

cax = ax.imshow(data)
cbar = fig.colorbar(cax)

cax.norm = mpl.colors.LogNorm(vmin=1, vmax=1000)
cbar.set_norm(cax.norm)
cbar.update_normal(cax)

cax.norm = mpl.colors.Normalize(vmin=-1000, vmax=1000)
cbar.set_norm(cax.norm)
cbar.update_normal(cax)
```
The result maintains a log axis, and spits out a bunch of warnings.

I believe the issue is that LogNorm sets axis to log, and nothing in update_normal or elsewhere adjusts it back on norm change. Perhaps there should be an else in ``ColorbarBase.config_axis``?

The other part is that the new scheme for LogNorm to use log-axis seems to effectively prohibit arbitrary ticks, since they do not show up unless they fall on a major tick mark. Is there any way around this? An option to maintain linear axes for LogNorm as had been the case in v1 and v2 might have been nice, but this maybe asking too much. I am able to force the axes to linear manually by getting it from Colorbar.ax and using ax.set_xscale, at least for the moment, which then lets me set custom ticks that show up anywhere.

**Comment by jklymak** [comment]
OK, you shouldn't set the mappables norm by hand, but should use `set_norm` instead.  I agree we shouldn't expose `cax.norm`, but that will be hard to deprecate.  

But agreed this had some issues, so see update.

**Comment by LevN0** [comment]
All the previously reported issues seem gone. A change seems to have broken (it is ignored) the ``format`` attribute of Colorbar, which worked in MPL 3.0.2. E.g., see:

```python

fig, ax = plt.subplots()

data = randn(250, 250)

cax = ax.imshow(data)
cbar = fig.colorbar(cax, format='%4.2e')
```

I am (very positively) surprised by the high level of effort you are giving to this issue, thanks!

**Comment by jklymak** [comment]
Well, I broke it, so I have to fix it.  

We are running into the issue that the user can set and access `cbar.locator/formatter` directly, but that we want it to magically reset itself when the norm changes.  I think we can still make this all work, but its turning out to not be trivial.

**Comment by efiring** [comment]
Would it help to turn some attributes into properties?

**Comment by jklymak** [comment]
I guess the real question is if we want user set locators and formatters to survive a norm change or not.  This PR says not.  If we want yes, but still do something intelligent if it’s never been set then we prob need properties.

**Comment by jklymak** [comment]
OK, #13234 has addressed all the issues I think we've identified so far, and added tests for them all... 

Ended up not needing properties.  

@LevN0 - care to see how it is working now?

**Comment by LevN0** [comment]
All the previously reported issues seem fixed. I could not find any issues with this version, though I am sure my tests are super incomplete. 

A question: why is ``Colorbar.minorticks_off`` disabled for log-axis? I understand minor ticks being turned on by default for LogNorm, but why is the user disallowed from turning them off? If the user adjusts the major ticks via set_ticks and does not have them at powers of 10, make the colorbar more confusing in my opinion.

**Comment by jklymak** [comment]
OK< great.  I'll mark it as not WIP

The minor ticks thing is a nuisance as well, but can you open a new Issue for that?  I think it can be dealt with in another PR.  The current PR is long enough as it is..

**Comment by LevN0** [comment]
Will do, thanks for the work on this one!

**Comment by jklymak** [comment]
Re-milestonig 3.1.  This is a bug, but the fix is too intrusive to be for a big-release (and 3.1 is on its way soonish anyway).
