### ISSUE TITLE
Sankey basic gallery example is not rendered properly.

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#13237]
### Bug report

The results of the sankey plot on the gallery seems broken: https://matplotlib.org/devdocs/gallery/specialty_plots/sankey_basics.html#sphx-glr-gallery-specialty-plots-sankey-basics-py

Running the code on my computer produces a different result: why it is rendered like this on the gallery needs to be investigated.

**Edit**: it is not the only plot behave this:
https://matplotlib.org/devdocs/gallery/specialty_plots/sankey_rankine.html#sphx-glr-gallery-specialty-plots-sankey-rankine-py

**Comment by anntzer** [comment]
It's already covered by https://github.com/matplotlib/matplotlib/pull/13218 (which will I'm rebasing now).

**Comment by dstansby** [comment]
Fixed by #13218
