### ISSUE TITLE
Request to add a new offset crosshairs feature

### ISSUE THREAD

**Issue by kakirastern** [matplotlib/matplotlib#13242]
Request for a new feature: Would it be possible to add a new offset crosshairs feature to the Matplotlib package, which would allow users to use a simple command to add this feature to their plot?

**Comment by jklymak** [comment]
What is an offset crosshairs?  You might want to try mplcursors....

**Comment by jklymak** [comment]
https://matplotlib.org/gallery/misc/cursor_demo_sgskip.html

**Comment by kakirastern** [comment]
Thanks, @jklymak, I will look into it further and see if the data cursor as prescribed in the link you have provided does what I want Matplotlib to. I think I want something related though may not be the same... because I want to actually draw an offset crosshair on a figure instead of an actual cursor. But I can see how using a cursor can aid the process. So it might be a means to an end. Will definitely follow up on this.

**Comment by tacaswell** [comment]
You can accomplish that with `ax.axvline` and `ax.axhline`, I am not sure that a method that adds both is worth expanding the API for.  It only saves one line of code, and if you find yourself doing this all time time carrying a helper function like (untested):

```python
def crosshair(ax, x=None, y=None, **kwargs):
    ret = {}
    if x is not None:
        ret['x'] = ax.axhline(x, **kwargs)
    if y is not None:
        ret['y'] = ax.axvline(y, **kwargs)
    return ret
```

may be helpful to you.

**Comment by kakirastern** [comment]
Thanks @tacaswell, it was just that I am new to Open Astronomy and am looking for something I can try out as preparation for GSoC 2019. Yup, you are right, it saves only one line of code...

**Comment by tacaswell** [comment]
@kakirastern Don't be discouraged!  This is a good idea, but one of the persistent tensions in Matplotlib is the right 'level' of the API.  If we include every convenience function that is useful to people in every field that uses Matplotlib the API would be even more un-manageablely large, but we need to also provide enough high-level functions that it is easy to use.

**Comment by kakirastern** [comment]
Thanks for the encouragement, @tacaswell. Now I understand the situation better so I can contribute in a more appropriate way in the near future. I appreciate your comments.

**Comment by timhoffm** [comment]
Thanks for sharing your ideas on how to improve Matplotlib. Even if it does not lead to an actual change in every case, user feedback is an important contribution to the project.
