### ISSUE TITLE
Installing mpl_toolkits in developer mode

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#13241]
### Bug report

The [Contributing guide](https://matplotlib.org/devdocs/devel/contributing.html) explains to install matplotlib in developer mode

~~~
python -mpip install -v .
~~~

However, it does not explain how to handle `mpl_toolkits` and by default I'm still using the preinstalled version then:

~~~
In [1]: import matplotlib                                                               

In [2]: matplotlib.__file__                                                             
Out[2]: '/home/tim/dev/matplotlib/lib/matplotlib/__init__.py'

In [3]: import mpl_toolkits.mplot3d                                                     

In [4]: mpl_toolkits.mplot3d.__file__                                                   
Out[4]: '/home/tim/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py'
~~~

This is inconsistent and results in problems when using toolkit stuff in development or when building docs based on the development version.

This issue has two parts for me:
1. I would like to fix my own development environment.
2. We should have documentation how to handle `mpl_toolkits` for development.

Once somebody explains 1. to me, I'm willing to include this in the docs.

**Comment by anntzer** [comment]
You may want to make sure everything is uninstalled first (in particular, there should not be a matplotlib-nspkg.pth in your site-packages), but other than that, `pip install -e .` does work for me.

**Comment by QuLogic** [comment]
I agree with @anntzer; there is no other special thing to do and it works correctly as is.

As I know you know how to find this bug, I'm going to close it to reduce clutter.
