### ISSUE TITLE
imsave outputs JPEG with wrong dimension

### ISSUE THREAD

**Issue by tboch** [matplotlib/matplotlib#13253]
### Bug report

**Bug summary**

When saving a 2d array in JPEG format, imsave generates an image of wrong dimension. This only happens for some specific array sizes, and only in JPEG (PNG outputs are fine for instance)

**Code for reproduction**

```python
import matplotlib.image as mimg
import numpy as np
import PIL

x = np.zeros((1856, 1728))
mimg.imsave('foo.jpg', x, format='jpg')
jpg_im = PIL.Image.open('foo.jpg')
jpg_im.size
```

**Actual outcome**

```
(1728, 1855)
```

**Expected outcome**

```
(1728, 1856)
```
**Matplotlib version**
  * Operating system: Debian 9
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.3
  * Other libraries: PIL 5.0.0

matplotlib installed from pip

**Comment by tacaswell** [comment]
png and not png go through entirely different code paths: https://github.com/matplotlib/matplotlib/blob/feac1eca0e40e84a9f699906e5c6f90d3ddf9e6b/lib/matplotlib/image.py#L1439-L1452

It looks like there is some rounding error in the figure resize process (the canonical size of the figure is in inches (as makes sense from a publishing PoV), to get the target size in pixels, we set the size in inches to `pixel_num / dpi` and then when we save the figure use `size_in_in * dpi` pixels).  Some where in that process we are rounding incorrectly.

I suspect we should replace that function with something like

```python
def imave(data, ....):
    im = cmap(norm(data))
    # yes, I know this is not the real API
    PIL.imsave(im, ...)
```

as much of the work that is done by `AxesImage` and `figimage` is to handle up/down sampling the raw user input to a different pixel grid to fit in into your figure.  In this use-case you very much want _none_ of that to happen!

**Comment by tboch** [comment]
Quick workaround for me was to change the dpi value as this does not interfere with the actual size of the generated JPEG.
