### ISSUE TITLE
backport to 2.x fixes for sphinx 1.8?

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#13258]
Hello,
in Debian we just got this bug report, http://bugs.debian.org/918896:

```
matplotlib2 fails to build with Sphinx 1.8, currently available in
experimental:

  # build the doc
  [...] /usr/bin/make -C doc html
  make[1]: Entering directory '/<<PKGBUILDDIR>>/doc'
  Running Sphinx v1.8.3

  Warning, treated as error:
  while setting up extension matplotlib.sphinxext.mathmpl: directive u'math' is already registered, it will be overridden
  make[1]: *** [Makefile:20: html] Error 2

This was fixed in matplotlib 3.x in this commit, please backport it:

https://github.com/matplotlib/matplotlib/commit/f87e9f46daf42ad7

That commit switches from generating PNG images for math formulas to MathJax
library, which renders the math formulas on client side. To package it for
Debian, please add this line to conf.py:

  mathjax_path = 'file:///usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

and make your documentation package depend on libjs-mathjax.

Also upstream has noticed that some math renders incorrectly with MathJax,
there is a follow-up commit which fixes it:

https://github.com/matplotlib/matplotlib/commit/a101de79650e077a
```

i see an issue was already reported and fixed at https://github.com/matplotlib/matplotlib/issues/12108 but it looks like the fixes where never backported to 2.x - would it be possible to do that?

thanks!

**Comment by NelleV** [comment]
Sure thing!

**Comment by NelleV** [comment]
I believe it already has been. This patch is fully in our branch already.

**Comment by dstansby** [comment]
I'm going to close this since it looks like it's fixed - feel free to comment or re-open if I'm wrong!

**Comment by LocutusOfBorg** [comment]
Hello, can we please have a backport against 2.2.x branch?

**Comment by tacaswell** [comment]
It looks like this got pulled back to 3.0.x and 3.0.0-doc, but not the 2.2.x branches.

I think we need to backport both https://github.com/matplotlib/matplotlib/pull/12149 and https://github.com/matplotlib/matplotlib/pull/11928

**Comment by tacaswell** [comment]
Tried to do this naively, did not work, do not have time to dig deeper now.

**Comment by tacaswell** [comment]
Closed by #13420

**Comment by LocutusOfBorg** [comment]
thanks! I will test it in a few minutes

**Comment by sandrotosi** [comment]
@LocutusOfBorg i'm already working on it, please leave the package maintainer job to the package maintainer

**Comment by LocutusOfBorg** [comment]
@sandrotosi I'll leave happily to you the Debian part :)
I want to take care of the Ubuntu part, and Ubuntu is going to freeze really soon and matplotlib2 never reached any stable Ubuntu release.

**Comment by LocutusOfBorg** [comment]
(btw without manual intervention the package won't probably be ever autosyncd, because it has been removed from Ubuntu due to sphinx 1.8)

**Comment by sandrotosi** [comment]
the PR patch (applied directly on top of 2.2.3) works, thanks!

**Comment by tacaswell** [comment]
There should be a 2.2.4 in the next few days as well.
