### ISSUE TITLE
"double-pendulum" example's speed not correct / varying

### ISSUE THREAD

**Issue by mikefarmer01** [matplotlib/matplotlib#13267]
### Bug report

**Bug summary**

"matplotlib/examples/animation/double_pendulum_sgskip.py": The animation seems to be speed up by either factor 2 or factor 4 (mostly factor 4, the behaviour isn't consistent though). So per second, about 2 or 4 displayed "seconds" are passing in the animation window with the animation processing significantly faster as expected. 

**Code for reproduction**

The example was not changed.

**Matplotlib version**

  * Operating system: Linux version 4.20.3-arch1-1-ARCH (builduser@heftig-25602) (gcc version 8.2.1 20181127 (GCC)) #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019

  * Matplotlib version: 3.0.2
  * Matplotlib backend: TkAgg
  * Python version: 3.7.2
  * Other libraries: Numpy: 1.16.0
                             Scipy: 1.2.0

I installed Python from the Arch repositories. I installed matplotlib via pip.

**Comment by timhoffm** [comment]
Thanks for the report. The intended time interval and the interval at which frames were displayed did not match. See #13271.
