### ISSUE TITLE
why my python3.7 is no response in jupyter notebook, when I use %matplotlib in line

### ISSUE THREAD

**Issue by Interesting6** [matplotlib/matplotlib#13266]
### Bug report

**Bug summary**

**Code for reproduction**

When I use plot in jupyter notebook and make figure showed in notebook, the dock of python show no response. But in others application(like terminal or pycharm etc.), it works normally.
```python
import matplotlib.pyplot as plt
%matplotlib inline
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/22903497/51582228-286ce200-1f06-11e9-8cb5-46fd282d1302.png)
This is my mac's program dock, the first row's Chinese means "The application is not responding".

**Expected outcome**

**Matplotlib version**

  * Operating system:  macos high sierra 10.13.6
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version:  3.7.0 ( with brew install )
  * Jupyter version (if applicable):  jupyter is 1.0.0; notebook is 5.7.0
  * Other libraries:

**Comment by QuLogic** [comment]
> Matplotlib version: 3.3.0

Please check again; that version does not exist.

**Comment by dstansby** [comment]
It looks like you're using an old version of Matplotlib; the most recent version is `3.0.3`. Please could you upgrade to Matplotlib `3.0.3` and let us know if there is still a problem?

**Comment by QuLogic** [comment]
Closing as there has been no response in two months.
