### ISSUE TITLE
IndexError in _update_title_position and get_ticks_position

### ISSUE THREAD

**Issue by rth** [matplotlib/matplotlib#13277]
**Bug summary**

I have a Qt based GUI application that uses matploltib for plotting. When rendering a figure (some pcolormesh subplots), with v3.0.2 I occasionally get the below traceback  with an `IndexError`. It is not deterministic and it only happens around 50 % of times.

It also only started happening in 3.0.x, this exception doesn't happen in v2.2.3 as far as I can tell. 

**Code for reproduction**

There is no code for reproduction unfortunately. I am not able to spend time to isolate this into a minimal example, but I opened this in the hope that someone might find this useful. For instance, https://github.com/IanGlass/Jira-Helper/issues/16 has exactly the same traceback (and also happened shortly after 3.0.x release).

In case it relevant, there is one sublot created without ticks (using `ax.axis("off")`)

After a very superficial look, it looks like `XAxis.majorTicks` might be sometimes empty, in which case `XAxis.majorTicks[0]` is invalid.

Another data point is that both in my case and the one linked above threading is used. In my case, interaction with the UI does happen from the main thread (I believe/hope), but that still might be relevant (particularly given that this is not deterministic).

Though this exception is not blocking (i.e. the program still continues to run) -- I have not figured out yet if that's due to that fact that exception is captured by PyQt or if that `draw_idle` was called from a separate thread.

**Actual outcome**

```py
Traceback (most recent call last):
  File "lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2588, in draw
    self._update_title_position(renderer)
  File "lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2542, in _update_title_position
    or ax.xaxis.get_ticks_position() == 'top'):
  File "lib/python3.7/site-packages/matplotlib/axis.py", line 2066, in get_ticks_position
    majt = self.majorTicks[0]
IndexError: list index out of range
```

**Expected outcome**

No error

**Matplotlib version**

  * Operating system: Gentoo Linux
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 3.7.2 (default, Dec 29 2018, 06:19:36) [GCC 7.3.0] :: Anaconda, Inc. on linux
  * Jupyter version (if applicable): not relevant
  * Other packages: I use the xarray plotting API that calls matplotlib

Installed from the default conda channel,
```
$ conda list | grep matplotlib
matplotlib                3.0.2            py37h5429711_0
```

**Comment by jklymak** [comment]
Update title position was indeed changed to make sure it doesn’t overlap with the axes.  But if this is really a bug, it seems to have found one in get_ticks_position.

**Comment by rth** [comment]
Thanks for the feedback! Yes, https://github.com/matplotlib/matplotlib/commit/90c30a0a677d0d924159b23407e9693df575996c looks like a probable reason.

>  I think matplotlib makes basically no guarantees about thread-safety

Agreed, and generally I am trying to avoid interacting with matplolib from another thread, but in this case do you think something like https://github.com/matplotlib/matplotlib/compare/master...rth:workaround-for-lazyticks-with-threading?expand=1 would be a reasonable workaround? That fixes my error.

There are other places in the code where `len(self.majorTicks)` is checked before accessing `self.majorTicks[0]` and I imagine it wouldn't hurt in general?

**Comment by anntzer** [comment]
Returning "unknown" seems wrong and likely an API break?  If we really want to fix that I guess a lock should just be added at a judicious (TBD...) place.

**Comment by jklymak** [comment]
"unknown" is returned elsewhere in the code if the position can't b determined.

**Comment by anntzer** [comment]
Closing as wontfix as this is basically a thread-safety issue and we now deem them invalid (#13298).  Feel free to reping if you disagree.
