### ISSUE TITLE
Can not longer import Matplotlib

### ISSUE THREAD

**Issue by maxpgn** [matplotlib/matplotlib#13270]
### Bug report

**Bug summary**

Hi everyone, I've just made an update in my Anaconda Navigator today. I didn't really pay attention to the content of the update, just clicked 'Ok' when asked to update, sorry about that. Since then, I get an error message when importing Matplotlib. I tried it from Jupyter, from iPython and from the console, always get the same message. Even after a computer reboot. I am clearly a noob, so I don't feel like digging without your help ;)

Thank you.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

ImportError: cannot import name 'get_backend' from 'matplotlib' (/home/maxpgn/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py)

**Matplotlib version**

  * Operating system: Debian Stretch
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Get the error message instead
  * Python version: 3.7.2
  * Anaconda Navigator : 1.9.6 
  * Jupyter version (if applicable): 
  * Other libraries: 

I installed all my packages and libraries using the Anaconda Navigator.

**Comment by story645** [comment]
Have you tried reinstalling matplotlib in navigator?

**Comment by story645** [comment]
No apologies needed, glad your solution was fixed!
