### ISSUE TITLE
Matplotlib + multiprocessing: WARNING: QApplication was not created in the main() thread.

### ISSUE THREAD

**Issue by lodo1995** [matplotlib/matplotlib#13296]
### Bug report

**Bug summary**
When using Matplotlib with the `multiprocessing` module, `QApplication` and `QObject` warnings appear on the console, related to the fact that the plots are not issued from the main thread.

My guess is that the callback gets executed on a separate thread, and the Matplotlib backend does not like this.

**Code for reproduction**
```python
from multiprocessing import Pool
import matplotlib.pyplot as plt

def computeData():
    return [0, 1, 2, 3], [0, 2, 1, 3]

def onResult(payload):
    time, data = payload
    plt.plot(time, data)
    plt.savefig('plot.png')

if __name__ == '__main__':

    with Pool() as pool:
        pool.apply_async(computeData, callback = onResult)
        pool.close()
        pool.join()
```

**Actual outcome**
The code produces the correct plot, but the following warnings appear in the console:
```
WARNING: QApplication was not created in the main() thread.
QObject::~QObject: Timers cannot be stopped from another thread
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.0.1
  * Matplotlib backend: `Qt5Agg`
  * Python version: 3.7.0

Everything was installed with Conda, using only the official channels.

**Comment by dopplershift** [comment]
And to be clear, this is not a warning from matplotlib, but from the Qt library itself.

**Comment by lodo1995** [comment]
Thank you for the answers.

I believe in general warnings are there for a reason, to try to avoid dangerous/undefined behaviours in the code that uses a library. So I would argue that, if Qt has issues with non-main threads, then the Qt backends should be disallowed, or at least require an explicit user choice, to be used in non-main threads.

Anyway, the code works fine and switching to a non-GUI backend to remove the warnings is straightforward (once you know about this). So I'm closing this issue. Thank you again for your quick replies.
