### ISSUE TITLE
docs unclear on status of constraint layout

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#13311]
https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html

Says:
![image](https://user-images.githubusercontent.com/449558/51870884-db807580-2322-11e9-857f-c13f62ed3505.png)

I imagine that's still the case in 3.0.2? Updating the note might make sense, then?

**Comment by jklymak** [comment]
Its been merged for a bit over a year now, so I guess we could consider making it non-experimental (if thats what you are suggesting).

**Comment by amueller** [comment]
I suggest either marking it non-experimental or marking it as still experimental. This is the docs for 3.0.2 and it only tells me what the status was in 2.2, not what the status is now.

**Comment by dstansby** [comment]
I'm happy for it to go non-experimental.

**Comment by dstansby** [comment]
(putting this as `3.0.3` as the docs should at least be fixed for `3.0.3`)
