### ISSUE TITLE
Export figure parameters

### ISSUE THREAD

**Issue by mcastorina** [matplotlib/matplotlib#13325]
**Matplotlib version**

  * Operating system: Arch Linux 4.19.12
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 3.7.1
  * Jupyter version (if applicable): n/a
  * Other libraries: none

Both matplotlib and python are installed from the Arch repositories.

There are two menus on the interactive graph windows: "Configure subplots" and "Edit axis, curve, and image parameters". It would be nice to have an export option for the latter in the same way "Configure subplots" has one.

**Comment by tacaswell** [comment]
The configuration options for the artists is very tied to what artists are in the figure.  How would you export that in a way that could be re-applied?

**Comment by mcastorina** [comment]
Perhaps it could output structured data in json or yaml for example.

```
{
    "artist_1": {
        "attribute_1": "value",
        "attribute_2": "value"
    }
    "artist_2": {
        "attribute": "value"
    }
    ...
}
```

Or in the following format:
```
artist_1.attribute_1=value
artist_1.attribute_2=value
artist_2.attribute=value
```

I'm not familiar with matplotlib artists, so I'm not sure if this is feasible.

**Comment by jklymak** [comment]
Hard to imagine such a thing would be faster than just replotting the data because it would have to save the data inside itself.  

I’ve done lots of data analysis over the years and I would say that it is a bad idea to rely on GUIs to make a plot look good.  Spending the time to figure out how to do it from the script will be more reproducible and save you a lot of time in the long run.

**Comment by timhoffm** [comment]
I don‘t think this is a viable/reasonable addition given the current way of working of the library. Generating the relevant code (e.g. interactive Jupyter session) and reusing that is the way to go. I propose to close this.

**Comment by marcowork** [comment]
I disagree on closing this issue. Makes no sense to distinct between variables to expose.
in the GUI you can actually export the values
```
top=0.959,
bottom=0.323,
left=0.042,
right=0.991,
hspace=0.2,
wspace=0.2
```

however setting these values should be available too.
I fully agree with @mcastorina on this feature request.

**Comment by jklymak** [comment]
I'm not following you, you can set all those values: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots_adjust.html
