### ISSUE TITLE
feature request: common x/y-label for subplot grid

### ISSUE THREAD

**Issue by HDembinski** [matplotlib/matplotlib#13326]
In scientific applications, I often generate a grid of subplots using shared axis, e.g. with `pyplot.subplots(2, 2, sharex=True, sharey=True)`. However, putting an central axis label on the common x- and y-axes is difficult to do currently.

Several solutions are discussed on SO, which all have caveats:
https://stackoverflow.com/questions/16150819/common-xlabel-ylabel-for-matplotlib-subplots/23638795
https://stackoverflow.com/questions/6963035/pyplot-axes-labels-for-subplots

* Use `Figure.text(...)` to create the labels. You need to manually place the labels and rotate the y-axis label manually. It does not work with `pyplot.tight_layout()`.
* Generate a common `ax = fig.add_subplot(111)`, then  turn off all ticks and spines except for the axis labels and set the axis labels on this subplot.  This is a non-intuitive hack, but has some advantages: you don't need to position the labels manually, and they will use the label font settings from the matplotlibrc. However, this trick also doesn't work properly with `pyplot.tight_layout()`.

I have no proposal at this time for a nice interface to handle this case more elegantly, but I think there is a clear need in the user community for setting common labels on axis of subplot-grids, as demonstrated by the highly ranked questions on SO.

**Comment by anntzer** [comment]
I think(?) @jklymak wrote something to do that recently?  Just pinging him there.

**Comment by jpivarski** [comment]
As an example of how this could work, this is a first-class citizen in Vega-Lite, not built manually:

https://vega.github.io/vega-lite/examples/trellis_bar.html

You get it by assigning one of the data features to a "trellis" facet, just as you would assign a data feature to the x or y axis.

**Comment by jklymak** [comment]
This is the same request as #11147, so I'll close this here, but please add to the discussion there.  This is easily doable in constrained_layout (see `suptitle`), and likely doable just by hand...
