### ISSUE TITLE
Log Colorbar minorticks_off reverted if ticks set...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#13339]
Posted by @LevN0

Apologies if not the right place. This PR has the following side effect:

```python

fig, ax = plt.subplots()

data = np.clip(randn(250, 250)*1000, 0, 1000)

cax = ax.imshow(data, norm=mpl.colors.LogNorm(vmin=1, vmax=1000))
cbar = fig.colorbar(cax, format='%d')

cbar.minorticks_off()
cbar.set_ticks([5, 10, 100])

plt.show()
```

Prior to this PR, minor ticks would remain off after ``set_ticks`` when they had been turned off. After this PR, they come back on.

_Originally posted by @LevN0 in https://github.com/matplotlib/matplotlib/pull/12909#issuecomment-459566413_

**Comment by LevN0** [comment]
Actually do not think connected to that PR, not sure why I thought it was. 

The cause is straight forward when looking at the code (``set_ticks`` calls ``update_ticks``, which sets minor ticks on for LogNorm). Post 13234, if it were accepted in current form, the turning on of minor ticks for LogNorm could be moved to new ``_reset_locator_formatter_scale``, though not sure if that introduces any new issues.

**Comment by jklymak** [comment]
Can you give it a try and run the tests, and submit a PR if that is a reasonable solution?  Seems you found something that works, so feel free to give it a try...

OTOH, did you test if the same thing happens for log-axes on a normal axes instead of a colorbar?  The point of the colorbar changes recently were to make the colorbar behave more like a normal axis, so, anything we can do to further that end is welcome.

**Comment by jklymak** [comment]
I think the problem is in master w/o #13234 right?  Or would your proposed change stomp on #13234?

**Comment by LevN0** [comment]
Problem is in master w/o #13234. However the proposed fix needs behavior/function introduced by  #13234.

**Comment by jklymak** [comment]
Right   - may as well wait for #13234 to go in, though you can make a PR against that branch and then rebas when its merged, its a bit fragile to do that.

**Comment by jklymak** [comment]
@LevN0 #13234 is merged, so if you want to talk a crack at fixing this, that'd be great.   If you can't get to it, ping me and I can probably do it.  Thanks!
