### ISSUE TITLE
ud in altair

### ISSUE THREAD

**Issue by harryomharry** [matplotlib/matplotlib#13361]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
This is the bug tracker for Matplotlib, not Altair. Also, you didn't write anything... I'll assume this was an accident.
