### ISSUE TITLE
Use file object instead of file paths

### ISSUE THREAD

**Issue by vanillajonathan** [matplotlib/matplotlib#13378]
### Bug report
`matplotlib.backends.backend_agg` have the methods `print_jpeg`, `print_jpg`, `print_png`, etc which takes a "str or PathLike or file-like object".

This allows code such as `canvas.print_png('plot.png')` which would write to the file system. Even in contexts/environments where the [`open`](https://docs.python.org/3/library/functions.html#open) function is not available and file system access is not intended.

It also does not allow try/except statements.

**Code for reproduction**

```python
figure = Figure()
canvas = FigureCanvas(figure)
canvas.print_png('plot.png')
```

**Proposal**
Remove string as an argument. 

```python
figure = Figure()
canvas = FigureCanvas(figure)
f = open(path, 'w')
f.write(canvas.print_png())
f.close()
```

Maybe accept a file object instead.
```python
figure = Figure()
canvas = FigureCanvas(figure)
with open(path, 'w') as f:
    canvas.print_png(f)
f.close()
```

**Comment by QuLogic** [comment]
> It also does not allow try/except statements.

I do not understand what you mean by this; there are no `try`/`except` in your examples.

> **Code for reproduction**

Please provide a _complete_ example, including imports.

**Comment by vanillajonathan** [comment]
You can do:
```python
figure = Figure()
canvas = FigureCanvas(figure)
try:
    f = open(path, 'w')
    f.write(canvas.print_png())
    f.close()
except OSError:
    print('Could not save plot file.')
```
But afaik you can not to do.
```python
figure = Figure()
canvas = FigureCanvas(figure)
try:
    canvas.print_png('plot.png')
except OSError:
    print('Could not save plot file.')
```

**Comment by anntzer** [comment]
Why not?  What exception does the second case raise on your system?

**Comment by vanillajonathan** [comment]
I don't know. I haven't tried it. I just looked at the matplotlib documentation and there is no mentioning of any exceptions being raised.

**Comment by anntzer** [comment]
Please clarify what you mean by "in contexts/environments where the open function is not available and file system access is not intended."  Note that you can always write to a BytesIO() object and do whatever you want with the resulting buffer.

**Comment by vanillajonathan** [comment]
I have an application that takes Python code as user input and then parses into an abstract syntax tree. Then it executes the code if there is no reference to the `open` function in the abstract syntax tree.

**Comment by anntzer** [comment]
That looks like a limitation of your application?
Note that there is plenty of C-level code that will also access the filesystem, so the AST does not include all the relevant information there.

**Comment by vanillajonathan** [comment]
Yes, my application is intentionally designed to limit file system access in order to provide access to matplotlib in an isolated safe environment.
It blocks imports and certain functions calls such as `open`. So then matplotlib poses a problem when it circumvents the restrictions introduces by directly handling files instead of relying on a passed in file object parameter.

**Comment by anntzer** [comment]
But Matplotlib needs to access the filesystem anyways e.g. to read font files, so if there's no filesystem, there's no Matplotlib.

**Comment by jklymak** [comment]
> It blocks imports and certain functions calls such as `open`. So then matplotlib poses a problem when it circumvents the restrictions introduces by directly handling files instead of relying on a passed in file object parameter.

I'm not really understanding.  We *do* allow you to pass a file object to `print_png`, so if thats all you are asking, its already being done.   If you asking us to *disallow* passing a string pathname, that would break thousands of users code, so thats *extremely* unlikely to happen.  If you are concerned we don't raise an error explictly if the open is disallowed, presumably open raises an error and the user should catch that.

**Comment by tacaswell** [comment]
We _need_ read access, but not write access.

I think the request here is to _remove_ the ability to pass strings in as filenames which is a complete non-starter for upstream Matplotlib.

If you want shipped a patched version of Matplotlib with your application that is probably the best way to get what you want (or a custom version of cython which has file writing stripped out).  I suggest having a look at https://www.python.org/dev/peps/pep-0551/

I am also deeply concerned about the premise,  will you correctly identify `getattr(locals()['__builtins__'], 'open')` as forbidden?

**Comment by vanillajonathan** [comment]
> I'm not really understanding. We _do_ allow you to pass a file object to `print_png`, so if thats all you are asking, its already being done.
Oh cool, yeah that's what I wanted, so great!

> If you asking us to _disallow_ passing a string pathname, that would break thousands of users code, so thats _extremely_ unlikely to happen.
Yes, that is also what I want.

**Comment by vanillajonathan** [comment]
@tacaswell 
> I think the request here is to _remove_ the ability to pass strings in as filenames which is a complete non-starter for upstream Matplotlib.

Yes, I would like that.
Maybe just deprecate the methods for now?
Maybe remove them in a future major release? Like version 4.

> I am also deeply concerned about the premise, will you correctly identify `getattr(locals()['__builtins__'], 'open')` as forbidden?

I was an almost empty dictionary to `exec` containing just a reference to matplotlib. So `locals()` and `globals()` are pretty empty and does not contain `__builtins__`.

```python
ns_local = {'matplotlib': matplotlib}
ns_global = {}
exec(code, ns_global, ns_local)
```

**Comment by anntzer** [comment]
Make that `matplotlib.tests.test_basic.builtins.open` for example...

**Comment by vanillajonathan** [comment]
Could the methods that take a path string as parameter be marked as deprecated?
Could they be considered for removal in a future major release? Like version 4.

**Comment by anntzer** [comment]
No, we will not consider them for removal.

**Comment by tacaswell** [comment]
I am going to quote https://www.python.org/dev/peps/pep-0551/#rejected-advice

> Do not attempt to implement a sandbox within the Python runtime. There is a long history of attempts to allow arbitrary code limited use of Python features (such as [14]), but no general success. The best options are to run unrestricted Python within a sandboxed environment with at least hypervisor-level isolation, or to prevent unauthorised code from starting at all.

We will not deprecate or remove filename input as strings to support a project that is discouraged by the cpython core developers.

**Comment by vanillajonathan** [comment]
Good point. Fair rationale.
But maybe it ought to be considered it in the name of a clean Pythonic API.
