### ISSUE TITLE
Rework main documentation page

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#13382]
I find the main documentation page not quite welcoming and helpful for users. Therefore, I propose to rework it.

Comments on the current sections:

- Introductory text: Conceptually ok, but too wordy and maybe too much detail at some points.
- Installation: No Information other than a link. Could be included in some top-Level menu. Not also that many people, will just use the preinstalled version in their OS or anaconda or just pip install. Detailed installation instructions are more like an advanced topic nowerdays.
- Documentation: Is it really necessary to confront the user with various versions of the docs in such a prominent place? Some sort of version dropdown menu on the side would be better.
- Need help: Rather confusing than helpful with that many options and links. Also very wordy, e.g. the sentence on the search tool could be left out completely. We have the search box in a prominent place and people know how to use these things 😄 

Things I’m missing:

- better structure: There’s no kind of TOC. You have to scroll down to see which topics are actually on the page.
- a clear reference “Getting started” for new users (well, I think the appropriate content for this is also missing, but that’s another topic.

IMO https://seaborn.pydata.org is an example of a good main page. - Not that we have to do exactly the same, but it shows how one can do it in a clean, informative and compact way.

**Comment by dstansby** [comment]
+10 for this, I definitely find the front page a bit too much of a block of text to navigate.

**Comment by timhoffm** [comment]
We have a committee working on this 😀.

**Comment by tacaswell** [comment]
attn @dorafc (so you get notifications)

**Comment by timhoffm** [comment]
This was created before setting up the dedicated committee and call. I've just updated the issue to announce that something is going on. I don't expect any updates to this issue. We have other/better channels to communicate.

**Comment by timhoffm** [comment]
Mostly fixed (apart from a better getting started).

Of course there's still room for improvement, but this issue does not contain information in that direction. Closing as fixed.

**Comment by dstansby** [comment]
Had a glance down the home page for the first time in a while (usually I dive straight into the API docs), and it was so much better than I remember! Thanks a lot to everyone who worked to improve it.

**Comment by jklymak** [comment]
My largest gripe right now is that you would never know from the top-level navigation that most of the documentation lives at Documentaion-API-Overview-Modules and even then its hard to parse that most drawing methods live on `Axes`.
