### ISSUE TITLE
plt.plot() terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by RMeli** [matplotlib/matplotlib#13414]
### Bug report

**Bug summary**

`plt.plot()` fails with error
```
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Code for reproduction**

```python
from matplotlib import pyplot as plt

plt.plot()
```

**Actual outcome**
```
2019-02-11 22:09:09.936 python[17037:389239] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fab105e6460
2019-02-11 22:09:09.937 python[17037:389239] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fab105e6460'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff43503ded __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6f5cf720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff43581195 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff434a5a60 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff434a5408 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000000122c6531d TkpInit + 413
	6   libtk8.6.dylib                      0x0000000122bbd17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x00000001229e5a0f _tkinter_create + 1183
	8   python                              0x000000010eb5a8b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x000000010ec9ab47 call_function + 247
	10  python                              0x000000010ec98684 _PyEval_EvalFrameDefault + 45284
	11  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	12  python                              0x000000010eb59577 _PyFunction_FastCallDict + 231
	13  python                              0x000000010ebdd0b1 slot_tp_init + 193
	14  python                              0x000000010ebe7091 type_call + 241
	15  python                              0x000000010eb5a283 _PyObject_FastCallKeywords + 179
	16  python                              0x000000010ec9abe4 call_function + 404
	17  python                              0x000000010ec98778 _PyEval_EvalFrameDefault + 45528
	18  python                              0x000000010eb5a078 function_code_fastcall + 120
	19  python                              0x000000010ec9aafe call_function + 174
	20  python                              0x000000010ec98684 _PyEval_EvalFrameDefault + 45284
	21  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	22  python                              0x000000010eb59577 _PyFunction_FastCallDict + 231
	23  python                              0x000000010eb5d4a2 method_call + 130
	24  python                              0x000000010eb5aef2 PyObject_Call + 130
	25  python                              0x000000010ec988cf _PyEval_EvalFrameDefault + 45871
	26  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	27  python                              0x000000010eb5a783 _PyFunction_FastCallKeywords + 195
	28  python                              0x000000010ec9aafe call_function + 174
	29  python                              0x000000010ec986bf _PyEval_EvalFrameDefault + 45343
	30  python                              0x000000010eb5a078 function_code_fastcall + 120
	31  python                              0x000000010ec9aafe call_function + 174
	32  python                              0x000000010ec986bf _PyEval_EvalFrameDefault + 45343
	33  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	34  python                              0x000000010eb5a783 _PyFunction_FastCallKeywords + 195
	35  python                              0x000000010ec9aafe call_function + 174
	36  python                              0x000000010ec986bf _PyEval_EvalFrameDefault + 45343
	37  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	38  python                              0x000000010eb5a783 _PyFunction_FastCallKeywords + 195
	39  python                              0x000000010ec9aafe call_function + 174
	40  python                              0x000000010ec98684 _PyEval_EvalFrameDefault + 45284
	41  python                              0x000000010ec8c2d2 _PyEval_EvalCodeWithName + 418
	42  python                              0x000000010ecf0c40 PyRun_FileExFlags + 256
	43  python                              0x000000010ecf00b7 PyRun_SimpleFileExFlags + 391
	44  python                              0x000000010ed1c7ec pymain_main + 9564
	45  python                              0x000000010eb2ca9d main + 125
	46  libdyld.dylib                       0x00007fff7069ded9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Matplotlib version**

  * Operating system: macOS 10.14.3 (Mojave)
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.1

`miniconda` installed using the [bash script](https://docs.conda.io/en/latest/miniconda.html) (version 4.6.3).

Python environment created with `conda`:
```
conda create -n py37 python=3.7
conda activate py37
```

`matrplotlib` installed using conda
```
conda install matplotlib
```

The same error is obtained in the `base` environment (`matrplotlib` installed in the same way). Everything installed from a fresh `miniconda` installation, using the default channel.

I've seen a bunch of open/closed similar issues, but none seem to solve the problem.

**Comment by jklymak** [comment]
Please check qt5agg, and if that works, please make sure you have the most recent tk installed.  Its possible there is a conda issue that should be submitted...

Do you have something in your .matplotlibrc that is setting tkagg as the backend?  Otherwise, the mac should default to the mac backend I think.

**Comment by RMeli** [comment]
If I try to use `Qt5Agg`
```
import matplotlib

matplotlib.use("Qt5Agg")
print(matplotlib.get_backend())

from matplotlib import pyplot as plt

plt.plot()
```
I get the following error:
```
Qt5Agg
Traceback (most recent call last):
  File "plot.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2374, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 13, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 49, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/Users/rmeli/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 165, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

However, quite surprisingly, if I explicitly tell `matplotlib` to use `TKAgg`, everything seem to work fine:
```
import matplotlib

matplotlib.use("TKAgg")
print(matplotlib.get_backend())

from matplotlib import pyplot as plt

plt.plot()
```

How is this possible? Can I make a permanent fix (for all my `conda` environments) so that I don't have to add
```
import matplotlib
matplotlib.use("TKAgg")
```
to all my scripts (which I also use on different platforms)? I couln't find any `.matplotlibrc` file.

**Comment by jklymak** [comment]
You should have a `.matplotlibrc` file in `~/.matplotlib/matplotlibrc`.

**Comment by RMeli** [comment]
There is none:
```
╭─rmeli@admin-MacBook-Pro ~/.matplotlib
╰─$ ll
total 152
-rw-r--r--  1 rmeli  staff    73K 11 Feb 21:56 fontlist-v300.json
drwxr-xr-x  2 rmeli  staff    64B 11 Feb 21:56 tex.cache
```

This might be the problem?

**Comment by jklymak** [comment]
Maybe not. I thought conda installed the default one, but maybe it doesn’t?   You can create one and set the backend to tkagg there. 

That doesn’t mean the error you are getting is ok.  But it’s hard to diagnose


The qt5 issue is probably because you don’t have qt5 installed?

**Comment by RMeli** [comment]
Creating the following `.matplotlib/matplotlibrc` file seem to solve the problem:
```
backend : TKAgg
```

This appears to work with every `conda` environment I have. Shouldn't `conda` install one by default? Is this a `conda` bug?

Yeah, I think the issue with `Qt5` is that I don't have it installed.

**Comment by jklymak** [comment]
My guess is that the new backend logic we introduced is triggering the macosx backend in a buggy way.  I hope these things are fixed for 3.1 but it’s pretty hard to diagnose when it’s kind of an install issue.  

Glad you found a workaround and sorry this is kind of broken.

**Comment by RMeli** [comment]
I see. It's probably related to the new version, because never experienced this problem before.

Thank you for the help in finding a workaround! I'll leave it to you to decide if the issue can be closed or not.

**Comment by TheBrettski** [comment]
Thanks @RMeli and others, this was driving me crazy for a couple of hours. This worked for me:
`import matplotlib
matplotlib.use("TKAgg")
from matplotlib import pyplot as plt

plt.plot()
`
Sorry, first comment. Not sure how to reference the code above in my comment.

**Comment by RMeli** [comment]
> Creating the following `.matplotlib/matplotlibrc` file seem to solve the problem:
> 
> ```
> backend : TKAgg
> ```

I know the feeling! ; ). 

In my opinion the above option (using the `matplotlibrc` configuration file in the `~/.matplotlib` folder) is cleaner: you don't have to add `matplotlib.use("TKAgg")` to all your scripts, and all your old code (or code written by others) will work as expected without having to add `matplotlib.use("TKAgg")`.

**Comment by TomHeaven** [comment]
In my case, use the `macosX` backend solved the crash problem.
```python
import matplotlib
matplotlib.use("macOSX")
```
And use `TkAgg` backend does not solve the problem.

**Comment by chaowu2009** [comment]
under MacOS, you should include:
matplotlib.use("macOSX")

and then use "pythonw" instead "python" to run your xxx.py file at the command line.

**Comment by aaronrr** [comment]
@chaowu2009 Thank you, that is the only thing that worked for me. But I am unclear on why, from python docs: 

> 4.1.2. Running scripts with a GUI
> With older versions of Python, there is one Mac OS X quirk that you need to be aware of: programs that talk to the Aqua window manager (in other words, anything that has a GUI) need to be run in a special way. Use pythonw instead of python to start such scripts.
> 
> With Python 3.6, you can use either python or pythonw.

I'm running python 3.7.0 so I'm not sure how this is related, must me some legacy GUI issue.

**Comment by jklymak** [comment]
With matplotlib 3.1 you should no longer need to use `pythonw`.

**Comment by aaronrr** [comment]
@jklymak Good call, I was using 3.0.3. Updating seem to have fixed it, and `matplotlib.use("macOSX")` is no longer necessary.

**Comment by cubeFUN** [comment]
conda install python.app
use `pythonw` instead of `python` solves mine

**Comment by margaritageleta** [comment]
Same error using matplotlib==3.5.1 on Mac OS Big Sur. Tried `matplotlib.use("macOSX")` and `matplotlib.use("TKAgg")`, does not solve the issue.
