### ISSUE TITLE
Add label support to fill_between

### ISSUE THREAD

**Issue by ycopin** [matplotlib/matplotlib#1341]
Unfortunately, the `fill_between` command does not support labelling. A work-around is discussed in http://matplotlib.1069221.n5.nabble.com/legend-label-for-fill-between-or-similar-td26401.html, but a native implementation would be better.

**Comment by shoyer** [comment]
This was fixed by #3303, right? If so I believe we can mark this as closed.

**Comment by tacaswell** [comment]
Yes, thank you for catching that.
