### ISSUE TITLE
Importing matplotlib after PySide2 is imported causes crash occasionally

### ISSUE THREAD

**Issue by BLKSerene** [matplotlib/matplotlib#13429]
### Bug report

**Bug summary**

Importing matplotlib after PySide2 is imported causes crash occasionally. When the order of imports is reversed, the occasional crash goes away. I'm not sure whether this is PySide2's problem or Matplotlib's. I've also reported this bug on [Qt Bug Tracker](https://bugreports.qt.io/browse/PYSIDE-937).

**Code for reproduction**

```
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

print('pyside')

import matplotlib.pyplot

print('matplotlib')
```

**Actual outcome**

No specific error message, I only got this:
```
Process finished with exit code -1073741819 (0xC0000005)
```

**Matplotlib version**
  * Operating system: Windows 10 64-bit
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.2 64-bit
  * Other libraries: PySide2/shiboken2: 5.12.1

Matplotlib, PySide2/shiboken2 were all installed via pip.

**Comment by piontk** [comment]
I had the same issue right now, trying to do the following: 

```
from PySide2 import QtWidgets, QtCore, QtGui
import numpy as np
import matplotlib.pyplot as plt

men_means, men_std = (20, 35, 30, 35, 27), (2, 3, 4, 1, 2)
women_means, women_std = (25, 32, 34, 20, 25), (3, 5, 2, 3, 3)

ind = np.arange(len(men_means))  # the x locations for the groups
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(ind - width/2, men_means, width, yerr=men_std,
                color='SkyBlue', label='Men')
rects2 = ax.bar(ind + width/2, women_means, width, yerr=women_std,
                color='IndianRed', label='Women')

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.set_xticks(ind)
ax.set_xticklabels(('G1', 'G2', 'G3', 'G4', 'G5'))
ax.legend()


def autolabel(rects, xpos='center'):
    """
    Attach a text label above each bar in *rects*, displaying its height.

    *xpos* indicates which side to place the text w.r.t. the center of
    the bar. It can be one of the following {'center', 'right', 'left'}.
    """

    xpos = xpos.lower()  # normalize the case of the parameter
    ha = {'center': 'center', 'right': 'left', 'left': 'right'}
    offset = {'center': 0.5, 'right': 0.57, 'left': 0.43}  # x_txt = x + w*off

    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()*offset[xpos], 1.01*height,
                '{}'.format(height), ha=ha[xpos], va='bottom')


autolabel(rects1, "left")
autolabel(rects2, "right")

plt.show()
```
When I remove the PySide2 import it works nicelly, but I need to use it on PySide2.

**Comment by BLKSerene** [comment]
This bug will be fixed in PySide2 5.12.2. See: https://bugreports.qt.io/browse/PYSIDE-937

**Comment by piontk** [comment]
@BLKSerene  but how can I fix it on my computer? The cash still happens here...

**Comment by tacaswell** [comment]
@piontk It looks like pinning to pyside2 5.12.0 or waiting for 5.12.2.

If I followed the links correctly, https://codereview.qt-project.org/#/c/254757/4/sources/shiboken2/libshiboken/signature.cpp is the fix which looks like there was a reference counting bug in shiboken.

**Comment by BLKSerene** [comment]
@piontk You can downgrade PySide2 (and shiboken2) to 5.12.0 for now, and upgrade to the latest version later when 5.12.2 is released.

**Comment by piontk** [comment]
@tacaswell and @BLKSerene , tank you for your answers, it works fine now!

**Comment by astrofrog** [comment]
It looks like PySide2 5.12.2 [has been released](https://pypi.org/project/PySide2/5.12.2), so it'd be worth checking if it works with that version?
