### ISSUE TITLE
ImportError when PySide2 backend is not found is fatal, but not propagated

### ISSUE THREAD

**Issue by bartoli** [matplotlib/matplotlib#13433]
I import matplotlib using 

```
try:
  import matplotlib.pyplot as plt
except ImportError:
```

So that a script can continue without running the optional stuff that uses matplotlib 

This seemd to work fine with agg backend. But with PySide2, if PySide2 is not properly installed in my python env, 
An ImportError when trying to load PySide modules stops my script before being propagated upwards to my catch

```
File "bla\TestUtils.py", line 45, in <module>
    import matplotlib.pyplot as plt
  File "foo\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "foo\matplotlib\backends\__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "foo\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "foo\matplotlib\backends\backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "foo\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "foo\matplotlib\backends\qt_editor\formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "foo\lib_winnt\matplotlib\backends\qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

Could the exception be caught and propagated upwards that call stack so we can detect it in a non fatal way?

**Comment by jklymak** [comment]
It bothers me that you have two different prefixes in there.  

I have no idea why your interpreter is not catching the ImportError, and I'm really not clear what matplotlib can do about it. I don't think we block the propagation in any strange way...

**Comment by bartoli** [comment]
My bad, i was confused because my code prints the traceback, but the exception was actually properly caught. This can be closed.

**Comment by jklymak** [comment]
OK Thanks!
