### ISSUE TITLE
boxplot/violinplot orientation-setting API

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#13435]
### Bug report

**Bug summary**

Currently, boxplot(), bxp(), violin(), and violinplot() take a `vert: bool` argument to switch between vertical and horizontal; this is inconsistent with colorbar(), hist(), eventplot(), and Slider(), which take an `orientation: {"vertical", "horizontal"}` argument.

For consistency, I'd suggest adding support for `orientation` (both because I think colorbar() and hist(), in particular, are probably the most used among all these, and because I like the API better :-)), and later deprecate `vert`.  Thoughts?

attn @phobson who has been involved in boxplots, IIRC.

**Comment by phobson** [comment]
I think this is a good idea.

Should be easy enough to capture `vert`, emit and deprecation warning, and then set `orientation` accordingly.

**Comment by anntzer** [comment]
(and while we're at it, the manage_xticks arg should be renamed to manage_ticks, as it covers both orientations)

**Comment by phobson** [comment]
just throwing this out there: what would you say to `manage_labels`?

**Comment by anntzer** [comment]
well technically it's managing ticks, tick labels, *and axis limits* so I think manage_labels is worse than manage_ticks, and perhaps manage_axis is better?
I also wonder whether it really needs to manage axis limits -- can't the standard margins system do that just as well?  (needs to be investigated)

**Comment by phobson** [comment]
good points all around.

just noticed a wrinkle: `boxplot.vert` is an rcParam

**Comment by anntzer** [comment]
We know how to handle deprecation/renaming of rcParams too.

**Comment by anntzer** [comment]
At least adding orientation should hopefully be uncontroversial.

**Comment by saranti** [comment]
Would you want separate PRs for `boxplot` and `violinplot` to keep it simple? The review process for the `boxplot` section will probably take a bit longer because it involves the deprecation of an rcParam which Ive never done before.

**Comment by timhoffm** [comment]
Should we simply deprecate the `boxplot.vert` rcParams without replacement? This is more of a plot-type setting rather than style. It’s not useful as a global config or style parameter. The only use case would be a local context (e.g. via a context manager) if somebody wants to make multiple horizontal plots. But for that rare case using the parameter explicitly may be good enough and is more clear for the reader.

**Comment by phobson** [comment]
> Should we simply deprecate the `boxplot.vert` rcParams without replacement? [snip] I believe, we also don’t have that config for bar() or hist()

I think that's a good idea and the justification is solid, IMO
