### ISSUE TITLE
NonUniformImage does not respond to ax.set_scale('log')

### ISSUE THREAD

**Issue by jacobsvensmark** [matplotlib/matplotlib#13442]
### Bug report

**Bug summary**

An image displayed with NonUniformImage does not respond to scaling the axis with `ax.set_xscale('log')`, other than changing the axis, not the image itself.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt 
from matplotlib.image import NonUniformImage

# Linear x array for cell centers:
x = np.linspace(1, 10, 10) 

# Highly nonlinear x array:
x2 = x**3

# Linear y-array
y = np.linspace(1, 10, 10) 
z = np.sqrt(x[np.newaxis, :]**2 + y[:, np.newaxis]**2)


fig, axs = plt.subplots(nrows=2, ncols=2)
fig.subplots_adjust(bottom=0.07, hspace=0.3)

# Uniform Grid, linear x-axis
ax = axs[0, 0]
im = ax.imshow(z, extent=(1, 10, 1, 10), aspect='auto',origin='lower')
ax.set_title("Uniform Grid, linear x-axis")

# Uniform Grid, log x-axis (image changes)
ax = axs[0, 1]
im = ax.imshow(z, extent=(1, 10, 1, 10),aspect='auto',origin='lower')
ax.set_xscale('log')
ax.set_title('Uniform Grid, log x-axis')

# Correct ticklabel formatting
from matplotlib.ticker import StrMethodFormatter, NullFormatter
ax.xaxis.set_major_formatter(StrMethodFormatter('{x:.0f}'))
ax.xaxis.set_minor_formatter(NullFormatter())

# NonUniform Grid, linear x-axis
ax = axs[1, 0]
im = NonUniformImage(ax, interpolation='nearest', extent=(1, 1000, 1, 10))
im.set_data(x2, y, z)
ax.images.append(im)
ax.set_xlim(1, 1000)
ax.set_ylim(1, 10) 
ax.set_title('NonUniform Grid, lin x-axis')

# NonUniform Grid, logarithmic x-axis (this doesn't work as intended)
ax = axs[1, 1]
im = NonUniformImage(ax, interpolation='nearest', extent=(1, 1000, 1, 10))
im.set_data(x2, y, z)
ax.images.append(im)
ax.set_xlim(1, 1000)
ax.set_ylim(1, 10) 
ax.set_xscale('log')
ax.set_title('NonUniform Grid, log x-axis')

plt.show()
```

**Actual outcome**

![figure_1](https://user-images.githubusercontent.com/37659419/52872670-66e46e00-314d-11e9-8012-53957c0625b7.png)

**Expected outcome**

The bottom panels are made using NonUniformImage. I expected a change similar to the top two panels (made with imshow) when setting `ax.set_xscale('log')`, however as can be seen in the bottom two panels, the image does not change from the left to the right hand side, only the axis.

The issue is briefly discussed [in this link](https://stackoverflow.com/questions/54713236/nonuniformimage-with-nonlinear-axes-in-matplotlib-in-python), and suggested by stackoverflow user Aaron to originate from the following:

> Basically the problem is that the image is rendered using square coords which are not transformed by the axis transformation, then the bounding box is linearly scaled to axes coords so the data lines up (if the axes coords are also linear). In this case the lack of a second transform misaligns the data. This could be considered a bug that mpl.image._ImageBase does not query the axes transforms for the purpose of aligning all the data, only the bounding box...

**Matplotlib version**
  * Operating system: OS X 10.14 
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 3.7.1

Python installed via default conda channel

**Comment by jklymak** [comment]
What are you trying to do with `NonUniformImage` that can't be done with `imshow` or `pcolormesh`?    So far as I can see `NonUniformImage` is almost completely un-documented.

**Comment by ImportanceOfBeingErnest** [comment]
Defining an image with n x m pixels on an n x m non-uniform grid calls for problems: Either there is one row and column missing, or something else is going wrong. Because you will necessarily need one edge coordinate more than you have pixel values per dimension. Not sure what NonUniformImage is actually doing in this case, but maybe it should rather error out?

**Comment by jacobsvensmark** [comment]
`imshow` assumes a uniform grid of constant spacing in the `x` and `y` directions, which I do not have. I have data analogous to the data in the bottom row, where you can see that the width of pixels along the `x`-axis varies i.e. the grid is non uniform.

I was not aware of `pcolormesh`, it does, essentially the thing I need, but I need to specify the corners of each pixel, rather than the midpoint of the pixel. So for an image of size `Nx,Ny` I would need an array of `x`-values of size `Nx+1` and for `y` of size  `Ny+1`. With `NonUniformImage` I don't need the extra grid value, I provide the points at which I have data and it assumes some way of finding pixel borders, which is a behaviour I would like.

Anyways, the point is that `NonUniformImage` could/should, as far as I can see, meaningfully adjust to the axes when they are set to logarithmic scaling, analogous to other image plotting routines. In the example above I show that it ignores the axes.

**Comment by jklymak** [comment]
#9629 does what you want with `pcolormesh`; right now you can pass N, M vectors, but then the data gets trimmed, which is suboptimal in my opinion.  

Skeptical that anyone will get `NonUniformImage` to work with log axes.  Your better bet for now would be to provide `pcolormesh` with the appropriate x,y vectors that are N+1, M+1 long.

**Comment by jacobsvensmark** [comment]
Allright, thanks for the reference.

**Comment by jklymak** [comment]
You're welcome to keep this open - maybe someone else thinks `NonUniformImage` should be kept around and fixed.

**Comment by jacobsvensmark** [comment]
Done! Thanks again.

**Comment by efiring** [comment]
This bug is shared by the `PcolorImage` used by `pcolorfast` under some circumstances.  It would be nice to fix it for both of these, since they provide a substantial performance boost compared to `pcolormesh`.  Or at a minimum, an exception should be raised when they are used with other than linear scales.  Unfortunately, when I looked at this some time ago my impression was that the fix would be non-trivial, and I didn't pursue it.

**Comment by anntzer** [comment]
I think the patch to fix this is along the lines of
```patch
diff --git i/lib/matplotlib/image.py w/lib/matplotlib/image.py
index a7642a2cb2..ec585e329c 100644
--- i/lib/matplotlib/image.py
+++ w/lib/matplotlib/image.py
@@ -1066,8 +1066,10 @@ class NonUniformImage(AxesImage):
         l, b, r, t = self.axes.bbox.extents
         width = int(((round(r) + 0.5) - (round(l) - 0.5)) * magnification)
         height = int(((round(t) + 0.5) - (round(b) - 0.5)) * magnification)
-        x_pix = np.linspace(vl.x0, vl.x1, width)
-        y_pix = np.linspace(vl.y0, vl.y1, height)
+        x_pix, _ = self.axes.get_xaxis_transform().inverted().transform(
+            np.column_stack([np.linspace(l, r, width), np.zeros(width)])).T
+        _, y_pix = self.axes.get_yaxis_transform().inverted().transform(
+            np.column_stack([np.zeros(height), np.linspace(b, t, height)])).T
         if self._interpolation == "nearest":
             x_mid = (self._Ax[:-1] + self._Ax[1:]) / 2
             y_mid = (self._Ay[:-1] + self._Ay[1:]) / 2
```
(i.e. just get the data coordinates corresponding to pixel values).  There may just be some off-by-1 or off-by-0.5 things...
