### ISSUE TITLE
boxplot doesn't normalize properties before applying them

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#13448]
### Bug report

**Bug summary**

Per title and example below.

**Code for reproduction**

```python
boxplot(np.random.rand(100), medianprops={"c": "red"})
```

**Actual outcome**

```
/usr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:1725: UserWarning: Saw kwargs ['c', 'color'] which are all aliases for 'color'.  Kept value from 'color'
  seen=seen, canon=canonical, used=seen[-1]))
```
and the median line doesn't use "red", but the default provided by the rcparams.

**Expected outcome**

no warning and a red median line.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: 3.0.2/master
  * Matplotlib backend (`print(matplotlib.get_backend())`): any
  * Python version: 3.7
  * Jupyter version (if applicable): no
  * Other libraries: no

**Comment by jklymak** [comment]
So this was fixed, right?

**Comment by anntzer** [comment]
Not yet, #13449 is just to avoid having to fix this in two places.
