### ISSUE TITLE
Issues with jquery download caching

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#13450]
Looks like I missed two points when reviewing @tacaswell's parts of #11246: https://github.com/matplotlib/matplotlib/pull/11246#pullrequestreview-204527495 and https://github.com/matplotlib/matplotlib/pull/11246#pullrequestreview-204536283.

**Comment by tacaswell** [comment]
milestoned an 3.0.3 as 4de6dfb is on the PR into 2.2.x and the backport bot only needs to pull this back to 3.0.x.

**Comment by tacaswell** [comment]
and in duplicating comments, I think the caching as the sha is ok (as users should put the files in the tree where they should be rather than rely on putting things in the right place in the cache) and the issue with freetype has PRs / commits to fix it.

**Comment by anntzer** [comment]
But for the case of FreeType that doesn't really work anymore (I think?)?  Previously you could just have the tarball in the cache and we wouldn't try to load it, now you need to have the tarball renamed to the sha for that.

**Comment by anntzer** [comment]
The FreeType issue just above remains valid (well, at least unless @tacaswell explicitly dismisses it, which is fine with me too).

**Comment by tacaswell** [comment]
Ah, I miss understood some of the bail logic, another PR coming.
