### ISSUE TITLE
FuncAnimation:  interactive zoom/pan with blitting does not work

### ISSUE THREAD

**Issue by onatt** [matplotlib/matplotlib#13478]
### Bug report
**Bug summary**
In an animation using blitting that contains some static graphics elements, the static parts of the figure are not updated after an interactive zoom/pan event. However, they are correctly updated after an resize event.

**Code for reproduction**

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.animation

t = np.linspace(0, 10, 100)
y = np.sin(t)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)

line, = ax.plot(t, y)
point, = ax.plot(0, 0, 'o')


def update(i):
    point.set_data([t[i], y[i]])
    return point,


ani = mpl.animation.FuncAnimation(fig, update, frames=t.size, blit=True)
plt.tight_layout()
plt.show()
```

**Actual outcome**
After an interactive zoom/pan operation the axes is redrawn, but the line plot stays on it's original position on screen. It seems that for some reason, a zoom/pan does not trigger a new initialization of the blitting.

Before pan: Point moves along the sinusoidal line
![a](https://user-images.githubusercontent.com/47846440/53152407-c14e5600-35b5-11e9-9401-5e616a0d5d66.png)
After pan: The sinusoidal line is not shifted correctly
![b](https://user-images.githubusercontent.com/47846440/53152436-d4f9bc80-35b5-11e9-97b8-fbc3e9f5fabe.png)

**Expected outcome**
![c](https://user-images.githubusercontent.com/47846440/53152835-ed1e0b80-35b6-11e9-9dad-841266675c9c.png)

**Matplotlib version**

  * Operating system: Linux 4.20.10 (same problem with Windows 10)
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg (TkAgg shows the same problem)
  * Python version: 3.0.2
  * Jupyter version (if applicable): n/a

**Proposed fix**
The following modification of matplotlib/animation.py fixes the problem:

```python
class Animation(object):
    ...
    def _setup_blit(self):
        # Setting up the blit requires: a cache of the background for the
        # axes
        self._blit_cache = dict()
        self._drawn_artists = []

        def remove_from_cache(ax):
            try:
                del self._blit_cache[ax]
            except KeyError:
                pass

        for ax in self._fig.axes:
            ax.callbacks.connect('xlim_changed', remove_from_cache)
            ax.callbacks.connect('ylim_changed', remove_from_cache)

        self._resize_id = self._fig.canvas.mpl_connect('resize_event', self._handle_resize)
        self._post_draw(None, self._blit)
```

**Comment by story645** [comment]
Thanks for the report & the fix!

Do you have the bandwidth to package up your fix as a pull request?

**Comment by onatt** [comment]
The bandwidth is generally not a problem. However, it is a bit difficult for the next couple of days.

What do I have to do?
1.) git clone https://github.com/matplotlib/matplotlib.git
2.) Make the proposed modifications to animation.py
3.) git commit
4.) What comes next?

**Comment by story645** [comment]
Almost:
1. fork
2. git clone
3. git checkout -b animation branch
4. make changes
5. git commit
6. git push to your fork
7. open a PR against matplotlib from your fork

it's described here: https://matplotlib.org/devel/contributing.html#contributing-code
