### ISSUE TITLE
ax.yaxis.label.properties()['position'] always returns (0, 0.5)

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#13486]
### Bug report

**Bug summary**

`ax.yaxis.label.properties()['position']` always returns (0, 0.5) in a script, but a different value when called interactively

**Code for reproduction**

```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# Fixing random state for reproducibility
np.random.seed(19680801)

mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

fig, ax = plt.subplots()

n, bins, patches = ax.hist(x, 50, normed=1, facecolor='g', alpha=0.75)
ax.set_xlabel('Smarts $x$')
ax.set_ylabel('Probability $y$')
ax.set_title('Histogram of $\mathit{IQ}$')
ax.text(60, .025, r'$\mu=100,\ \sigma=15$')
ax.grid(True)

print("ax.yaxis.label.properties()['position'] = {}".format(ax.yaxis.label.properties()['position']))
fig.show()
print("ax.yaxis.label.properties()['position'] = {}".format(ax.yaxis.label.properties()['position']))
```

**Actual outcome**
`python -i code.py` returns:
```
ax.yaxis.label.properties()['position'] = (0, 0.5)
ax.yaxis.label.properties()['position'] = (0, 0.5)
```
When then entering `ax.yaxis.label.properties()['position']` in the console, I get `(25.097222222222214, 0.5)`.

**Expected outcome**
```
(25.097222222222214, 0.5)
(25.097222222222214, 0.5)
```
(I'm not sure about the first line though)

**Matplotlib version**

  * Operating system: Ubuntu 16.04.5 LTS 64-bit
  * Matplotlib version: 3.0.2 (conda, build: py36_1002, channel: conda-forge)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8 (conda, build: h0371630_0)

**Comment by QuLogic** [comment]
This is not really a bug, but there are couple issues here:
* Any drawing position is unlikely to be correct until at least the first draw.
* `Figure.show()` only does something when the pyplot machinery is running, i.e., while `plt.show()` is running, or if you've called `plt.ion()` while interactive.

However, you _don't_ need to show the figure (interactively or not) to get a draw in; you can force it by using `fig.canvas.draw()`, and using that in place of `fig.show()` gives:
```
ax.yaxis.label.properties()['position'] = (0, 0.5)
ax.yaxis.label.properties()['position'] = (25.222222222222214, 0.5)
```

**Comment by baloe** [comment]
That's goot to know but it does not yet resolve the issue I really have:

After setting up a plot I intend to edit the yticklabels without changing anything else:
```python
ax.set_yticklabels([ r'\$\num{{{:g}}}\$'.format(item) for item in ax.get_yticks().tolist() ])
```
The problem is that this has the ylabel moved to the left too.
I could not figure out how to prevent matplotlib from updating positions so I figured I would get the position of the ylabel before modifying the yticks, and then impose this postion.
Unfortunately, I don't get this to work:
```python
fig.canvas.draw()
ylabelposition = ax.yaxis.label.get_position()
ax.set_yticklabels([ r'\$\num{{{:g}}}\$'.format(item) for item in ax.get_yticks().tolist() ])
ax.yaxis.label.set_position(ylabelposition)
```

**Comment by jklymak** [comment]
I'm going to close this because @QuLogic  gave the answer for your first issue.  If you have a second issue, feel free to submit a bug report, or ask at stackoverflow.
