### ISSUE TITLE
labelpad is not the spacing between the axis and the label

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#13487]
### Bug report

**Bug summary**

The matplotlib documentation for `matplotlib.axes.Axes.set_ylabel` reads
"labelpad : Spacing in points between the label and the y-axis."
(https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_ylabel.html#matplotlib.axes.Axes.set_ylabel)
but in fact it is *not* the spacing between the label and the y-axis.
It really is the spacing between the label and the ticklabels.

**Code for reproduction**

```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

np.random.seed(19680801)
mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

fig, ax = plt.subplots()

n, bins, patches = ax.hist(x, 50, normed=1, facecolor='g', alpha=0.75)
ax.set_ylabel('Probability $y$', labelpad=0)
fig.show()
```

**Actual outcome**

Much space between y-axis and ylabel.

**Expected outcome**

No space between y-axis and ylabel.

**Matplotlib version**
  * Operating system: Ubuntu 16.04.5 LTS 64-bit
  * Matplotlib version: 3.0.2 (conda, build: py36_1002, channel: conda-forge)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8 (conda, build: h0371630_0)

**Comment by ImportanceOfBeingErnest** [comment]
Indeed the documentation should be more specific about what the `labelpad` is relative to.

**Comment by timhoffm** [comment]
`labelpad` is a distance in points from the axes bounding box including ticks and tick labels.

**Comment by high-in-entropy** [comment]
Hi! I am completely new to OpenSource contribution. Is there a way I can contribute to this issue?

**Comment by ImportanceOfBeingErnest** [comment]
@high-in-entropy Yes you can read https://matplotlib.org/devel/contributing.html#contributing on how to contribute. In this specific case the docstring of the `set_ylabel` and `set_xlabel` methods should be updated.

**Comment by high-in-entropy** [comment]
Thank you! This is my pull request for the issue.
#13546

**Comment by DZusername** [comment]
How do you keep long xlabels from being cutoff on only the right side subplots?
