### ISSUE TITLE
make_axes_locatable and append_axes does not work with polar projections

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#13481]
### Bug report

**Bug summary**

I'm trying to figure out how to append axes to my polar projection.  There's no option for "outer" or anything that would resemble polar projections with the `append_axes` arguments.

**Code for reproduction**

```python
    import numpy as np
    import matplotlib.pyplot as plt
    from mpl_toolkits.axes_grid1 import make_axes_locatable
    
    plt.style.use("seaborn-white")
    def synthesize(polar=False):
        fig = plt.figure()
        ax = fig.add_subplot(111, polar=polar)
        t = np.linspace(0,2*np.pi)
        r_sin = np.sin(t)
        r_cos = np.cos(t)
        for r in [r_sin, r_cos]:
            ax.scatter(t, r, c=r, s=t*100, edgecolor="white", cmap=plt.cm.magma_r)
            ax.scatter(t, -r, c=r, s=t*100, edgecolor="white", cmap=plt.cm.magma_r)
        ax.set_title("polar={}".format(polar),fontsize=15)
        ax.set_xticklabels([])
        return fig, ax, t
        
    # Rectilinear
    fig, ax, t = synthesize(polar=False)
    divider = make_axes_locatable(ax)
    ax_below = divider.append_axes("bottom", size="32.8%", pad=0.1)
    ax_below.scatter(t, np.tan(t), c="black", edgecolor="white")
    
    # Polar
    fig, ax, t = synthesize(polar=True)
    divider = make_axes_locatable(ax)
    ax_below = divider.append_axes("bottom", size="32.8%", pad=0.1)
    ax_below.scatter(t, np.tan(t), c="black", edgecolor="white")



```

**Actual outcome**
It adds a small ax plot beneath the polar plot

[![enter image description here][1]][1]

```
NA
```

**Expected outcome**

I was hoping that the polar ax would be appended on the outer ring of the original polar plot

**Matplotlib version**

  * Operating system:
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1510

  * Matplotlib version: 
3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
module://ipykernel.pylab.backend_inline
  * Python version:
3.6.6
  * Jupyter version (if applicable):
4.4.0
  * Other libraries: 

I used conda to install

How can I do this? 

**Is there a way to `append_axes` on a `polar` matplotlib projection `ax` using `make_axes_locatable`?** 

For the end product I am trying to get another ax to wrap around the original polar ax.

  [1]: https://i.stack.imgur.com/ZwBLB.png

**Comment by ImportanceOfBeingErnest** [comment]
> Is there a way to `append_axes` on a `polar` matplotlib projection `ax` using `make_axes_locatable`?

Well yes, you've done that in your code.

> I am trying to get another ax to wrap around the original polar ax.

For that purpose the `Divider` is of no use. It's purely working on a rectangular grid.

Some example which might help for building such wrapped polar axes from scratch could be
[Demo Floating Axes](https://matplotlib.org/gallery/axisartist/demo_floating_axes.html) or
[Radar chart (aka spider or star chart)](https://matplotlib.org/gallery/specialty_plots/radar_chart.html)

Also consider if plotting a small and a large polar plot on top of each other and possibly using a clip path, or a white circle or similar wouldn't give you the desired plot while keeping complexity low.

**Comment by jolespin** [comment]
Thank you for your suggestions.  I will try this out.
