### ISSUE TITLE
Disable mathtext and LaTeX

### ISSUE THREAD

**Issue by danielleontiev** [matplotlib/matplotlib#13490]
### Bug report

**Bug summary**

I use matplotlib to make plots for LaTeX documents so I generate graphics as `.pgf` as a final step and use `plt.show()` in creation process to tweak my plot. Today I faced a problem I would like to use symbol from `amsmath` in label. I finally figured out how to do it when I run my plot as follows: `plt.show()`. To achieve it I've added:

    plt.rc('text',usetex=True)
    plt.rc('text.latex', preamble=r'\usepackage{amsmath}')

My plot is shown correctly in matplotlib window. But when I try to save it: `plt.savefig('plot.pgf', format='pgf')` it crashes with LaTeX error:

    ! Undefined control sequence.
    <argument> ...tfont \(\displaystyle W(\boldsymbol 
                                                      {p}, +\infty )\)
    <*> ...\displaystyle W(\boldsymbol{p}, +\infty)\)}

I am confused. Why it runs LaTeX compiler? It should simply translate the plot to `.pgf` file "blindly" as `gnuplot` does. I can't use `amsmath` and I am not able to use my own defined commands in LaTeX.

**Code for reproduction**

```python
# Paste your code here
#
#
import matplotlib.pyplot as plt
import numpy as np

plt.rc('font',family='serif')
plt.rc('text',usetex=True)

plt.rc('text.latex', preamble=r'\usepackage{amsmath}')

x = np.linspace(-10, 10, 1000)
y = np.sin(x)

plt.plot(x, y)
plt.xlabel(r'$p_\parallel / m$')
plt.ylabel(r'$W(\boldsymbol{p}, +\infty)$')


# plt.show()
plt.savefig('test.pgf', format='pgf')

```

**Matplotlib version**

  * Operating system: Ubuntu 16.04.5
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.8

I installed matplotlib as follows:
    
    python3.6 -m pip install --user matplotlib

**Comment by pharshalp** [comment]
As described here [https://matplotlib.org/users/pgf.html](url), you have to select the pgf backend and update the `pgf.preamble`.

```python
import matplotlib as mpl
mpl.use("pgf")
import matplotlib.pyplot as plt
import numpy as np

plt.rc('font', family='serif')
plt.rc('text', usetex=True)
plt.rc('pgf', preamble=[r"\usepackage{amsmath}"])

x = np.linspace(-10, 10, 1000)
y = np.sin(x)

plt.plot(x, y)
plt.xlabel(r'$p_\parallel / m$')
plt.ylabel(r'$W(\boldsymbol{p}, +\infty)$')

plt.savefig('test.pgf', format='pgf')
```

**Comment by danielleontiev** [comment]
@pharshalp thank a lot for your code. But it is still unclear why matplotlib runs LaTeX compiler and is it possible to disable it because I have my own defined commands in document and it is not handy to add them to matplotlib preamble

**Comment by anntzer** [comment]
(IIRC) it is to figure out the size of the text objects, so that they can be placed with the correct paddings.

**Comment by danielleontiev** [comment]
Ok, thank you for explanation. Now I think using LaTeX worth it even if it
makes you to define custom preamble

сб, 23 февр. 2019 г., 18:16 Antony Lee <notifications@github.com>:

**Comment by QuLogic** [comment]
Closing, as there doesn't appear to be a bug here, and the issue appears to have been figured out.
