### ISSUE TITLE
Long legend and tight_layout result in resizing error

### ISSUE THREAD

**Issue by Dunkhan** [matplotlib/matplotlib#13522]
### Bug report

**Bug summary**

If the legend is too long to fit in the space allocated to the figure, tight_layout will scale the other subplots proportionally smaller. Because the legend is all text however, the legend can not be scaled. This results in the other subplots being made unreasonably small for no reason, and the legend is still cut off. The specific use case I have is unusual so this may be a low priority issue, but I felt it was worth mentioning.

Aplogies that the example is not fully 'minimal'. I just cut down my actual use case.

**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.lines as lines
import random
from cycler import cycler

caption = "My Chart"
spectrum_limits = [0,10]
balance_limits = [-8,8,0,10]
balance_x_caption = "X Axis"
balance_y_caption = "Y AXis"
spectrum_y_caption = "Y Axis"
labels = ["a","b","c","d","e"]
legend_captions = "abcdefghijklmnopsdjkfhsdkjfsdkfggudyguyu"

balance_data = [[random.randint(-7,7) for x in range(10)],[random.randint(1,9) for y in range(10)]]
structure_data = [[random.randint(1,10) for w in range(10)] for z in range(20)]#Adjust the last range to 10 or 30 to see the difference

colors = ['#418CF0FF','#FCB441FF','#E0400AFF','#056492FF','#BFBFBFFF','#1A3B69FF','#FFE382FF','#129CDDFF','#CA6B4BFF','#005CDBFF','#F3D288FF','#506381FF','#F1B9A8FF','#E0830AFF','#7893BEFF']
cycler = cycler('color', colors)()

#Create plot
fig = plt.gcf()
fig.set_size_inches(10, 3)
ax = fig.subplots(1,3, gridspec_kw = {'width_ratios':[5, 1, 5]})

#Axis setup
ax[0].set_xlabel(balance_x_caption)
ax[0].set_ylabel(balance_y_caption)
ax[2].set_ylabel(spectrum_y_caption)
ax[0].set_xlim(balance_limits[0], balance_limits[1])
ax[0].set_ylim(balance_limits[2], balance_limits[3])

#Plot Balance
for coords in zip(balance_data[0], balance_data[1]):
	ax[0].scatter(coords[0], coords[1], marker="o", facecolors=next(cycler)['color'], edgecolors='black', zorder=3)
	
#Plot Spectrum
legend_lines = []
ax[2].set_ylim(spectrum_limits[0],spectrum_limits[1])
for i in range(len(structure_data)):
	line = structure_data[i]
	startIndex = 0
	line_color = next(cycler)['color']
	marker_color = line_color
	xold = np.linspace(0, len(line)-1, len(line))
	ax[2].plot(xold,line, color=line_color)
	legend_lines.append(lines.Line2D([0,0], [0,0], color=line_color, markeredgecolor=marker_color, markerfacecolor=marker_color, marker="o"))

#Legend
legend = ax[1].legend(legend_lines, legend_captions, loc=0, frameon=False, title=caption)

#Clear styles for middle figure (legend)
for position, spine in ax[1].spines.items():
	spine.set_visible(False)
ax[1].get_xaxis().set_ticks([])
ax[1].get_yaxis().set_ticks([])

plt.tight_layout()

plt.show()
```

**Actual outcome**
If tight_layout is on, the left and right subplots are incorrectly resized. If the length of the legend is reduced to 10 elements this does not happen. If the length of the legend is increased to 30 elements, the tight_layout fails

**Expected outcome**
The legend should not cause resizing of other elements if it is too large for the figure. The legend can not be resized because tight layout does not modify font sizes, so there is no reason for the legend to be taken into account. The legend must be cut off in this case as there is no way to make it fit.

**Matplotlib version**
  * Operating system:Windows 10 x64
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3.7 x32
  * Jupyter version (if applicable):
  * Other libraries: 

scipy
flask
some others, I dont think any of these are required for reproduction

Installed with pip

**Comment by Dunkhan** [comment]
I just found out it is possible to work around the issue with `prop={'size': height/mmToInch}` in the legend. This results in random resizing of the fonts and looks really ugly.
The workaround I will be using is calculating the number of elements that will fit in the legend and then not adding more after this limit.

**Comment by Dunkhan** [comment]
Similar issue: in the case above if the legend label strings are too long, the legend gets forced over to the left, overlapping the scatter plot. In this case i would prefer them to be cut off as well.

**Comment by jklymak** [comment]
Set legend.in_layout(False) and it should no longer be included in the tight layout calculation.

**Comment by jklymak** [comment]
Closing, but feel free to comment or re-open if you think there is more we can do here...

**Comment by Dunkhan** [comment]
Yeah that works. Thanks.
