### ISSUE TITLE
Boxplotting Masked Arrays

### ISSUE THREAD

**Issue by danrod13** [matplotlib/matplotlib#13533]
### Bug report
When I try to boxplot several np.arrays of masked values, ax.boxplot includes the masked values. This throws off the analysis of the data and gives me an almost unusable boxplot. 

**Bug summary**
I masked several -9999 values (equipment error values) in order to look at the variances in the rest of our good data (range between 0~500). I masked the -9999 values using a np.ma.masked_less to give an array of good data with several masked values in the array. Once I called these data into the boxplot, it included the masked -9999 values. I patched this bug by switching out the masked_less call with an inequality statement that replaced the -9999 values with erroneous values (i.e. swapped out -9999 with a random number instead of removing it from the data set).

Boxplot function including masked values in a np.array where it should be ignoring said masked values.

**Code for reproduction**

```python
# Paste your code here
#
#
import numpy as np
import matplotlib.pyplot as plt

a = np.ma.array([229.5,374.0,536.5,-9999,-9999,-9999,-9999,-9999,182.0,42.5,49.0])
b = np.ma.array([363.0,118.5,159.0,-9999,311.0,516.0,380.0,338.5,223.0,211.5,128.5])
c = np.ma.array([205.5,277.5,141.5,278.0,302.0,251.0,299.0,250.0,315.5,92.1,211.9])

a = np.ma.masked_less( a, -9000 )
b = np.ma.masked_less( b, -9000 )
c = np.ma.masked_less( c, -9000 )

data_to_plot = [ a , b, c ]
labels = [ 'a', 'c', 'c' ]

fig = plt.figure( 3, figsize = ( 8, 10 ) )
ax = fig.add_subplot( 111, frameon = False )
bp = ax.boxplot( data_to_plot, patch_artist = True, widths = .85, 
                labels = labels, vert = True)
plt.setp( bp[ 'boxes' ], color = 'black', alpha = .8, linewidth = 3 )
plt.setp( bp[ 'whiskers' ], color = 'black', linewidth = 3 )
plt.setp( bp[ 'fliers' ], markeredgecolor = 'black', alpha = 1, markersize = 30, marker = '.' )
plt.setp( bp[ 'medians' ], color = 'orange', linewidth = 3 )
plt.setp( bp[ 'means' ], color = 'black' )
plt.setp( bp[ 'caps' ], color = 'black', linewidth = 4 )

colors = ['r', 'b', 'g', ]
for b in ( bp ):
    for patch, color in zip( bp[ 'boxes' ], colors ):
        patch.set_facecolor( color )
plt.show()
```

**Actual outcome**

![bp_masked_array](https://user-images.githubusercontent.com/48063090/53507494-0676fa00-3a86-11e9-87c2-5c9878243670.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Expected a boxplot with masked values ignored so only shows unmasked values above -9000

**Matplotlib version**

  * Operating system: macOS High Sierra 10.13.6
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: Spyder 3.1.2

Unsure how installed. Think it was through pip

**Comment by jklymak** [comment]
its possible that boxplot is not mask-aware.  However, I don't see any reason why it can't be made aware.

Did you mean version 3.0.2?

**Comment by jklymak** [comment]
@phobson, are you the boxplot guru?  If not, feel free to un-assign yourself!

**Comment by danrod13** [comment]
@jklymak matplotlib.__version__ says it's "2.0.2" which could be part of the issue.

**Comment by jklymak** [comment]
This is still reproducible in master, so I don't think its a version thing.  Thanks for checking!

**Comment by phobson** [comment]
@jklymak thanks for the heads up. i'll take a look

**Comment by phobson** [comment]
The crux of the matter is here:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/__init__.py#L1280

Paraphrased:
```python
for x in data:
    x = np.asarray(x)
```

So we're explicitly throwing away the mask. 

For an immediate work around:
```python
data_to_plot = list(map(lambda X: [x for x in X if x >= -9000], [a, b, c]))
```
May or may not with your real data

**Comment by danrod13** [comment]
![masked_array_bp](https://user-images.githubusercontent.com/48063090/53514125-f87ca580-3a94-11e9-950d-662978e930ce.png)
Thanks @phobson ! The code is running well. Here's the new figure

**Comment by jklymak** [comment]
I thought we had a standard way to regularize input like this; certainly `np.asarray` is not quite safe enough.

**Comment by phobson** [comment]
perhaps this:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/__init__.py#L996

**Comment by jklymak** [comment]
That could work...

**Comment by dasrirez** [comment]
We've noticed all data on numpy masks is deleted after https://github.com/matplotlib/matplotlib/blob/8137b4c5459c9362e704853914fbbd74ea6e3199/lib/matplotlib/cbook/__init__.py#L1243 

Specifically here in _reshape_2D https://github.com/matplotlib/matplotlib/blob/8137b4c5459c9362e704853914fbbd74ea6e3199/lib/matplotlib/cbook/__init__.py#L1418

Thinking of two approaches for this fix using `delete_masked_points` (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/__init__.py#L996) 
1. Have a function to filter out masked values in `X` using `delete_masked_points` before passing `X` to `_reshape_2D`
2. Run the filter function within  `_reshape_2D` (avoids some duplicate code in other places where `_reshape_2D` is called but changes the behaviour of this function)

We're going ahead with solution 1 unless a green light is given for 2, either way it seems to fix this particular issue.

**Comment by phobson** [comment]
@dasrirez 

Who is "we" in this case? Does this comment mean that you're going to submit a PR?

**Comment by dasrirez** [comment]
@phobson yep, me and a group of other students are working on understanding and contributing to this project. Just wanted check in here on the best approach for our PR (please let me know if this is the right place for these sorts of discussions). Sorry for the ambiguity!

**Comment by phobson** [comment]
@dasrirez Thanks for clearing that up. 

This is the right place for that discussion. When you have a PR ready, ping me on it and I'll happily review it.

**Comment by tacaswell** [comment]
This is still a bug in 3.7.

The analysis above still seems correct.  Anyone picking this up should review #13651 .  On a quick skim it is not clear to me if starting from those commits or starting from scratch is better.
