### ISSUE TITLE
Docs for matplotlib.pyplot.specgram() reference an unsupported mode setting

### ISSUE THREAD

**Issue by bcongdon** [matplotlib/matplotlib#13540]
### Bug report

**Bug summary**

The docs for `matplotlib.pyplot.specgram`'s `mode` argument reference the 'complex' mode setting, which is not a valid option:

`'complex' returns the complex-valued frequency spectrum.` (from [here](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.specgram.html))

However, if you try to set `mode='complex'`, you receive a `ValueError` due to this line of code: https://github.com/matplotlib/matplotlib/blob/74640bb3998a51abfb2251a4bc39cea6c215b889/lib/matplotlib/axes/_axes.py#L7653-L7654

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
plt.specgram(np.ones(1000), Fs=100, mode='complex')
```

**Expected outcome**

The docs should not reference the `complex` mode type if it is not planned supported.

**Matplotlib version**
N/A

**Comment by jklymak** [comment]
Care to open a PR - someone simply forgot to remove that phrase...

**Comment by bcongdon** [comment]
For sure! 😄 Just wanted to make sure that my understanding was correct.
