### ISSUE TITLE
Missing 3.0.3 wheels break CI and pip installs

### ISSUE THREAD

**Issue by rgommers** [matplotlib/matplotlib#13554]
Hi, you released Matplotlib 3.0.3 a couple of hours ago, and the set of wheels is incomplete. There are no wheels for Windows for example. However there is a `.tar.tz` - this is quite bad, it will break installation and CI for everyone who tries `pip install matplotlib` and is not set up to build from source. Example: https://github.com/scipy/scipy/pull/9423

If the rest of the wheels are coming within hours, I suggest to leave things as is and document in your release procedure not to do this. If there's an issue and other wheels will take longer, I suggest to remove the 3.0.3 source release for now (existing wheels can stay).

**Comment by jklymak** [comment]
Probably just an oversight that is almost fixed... https://github.com/matplotlib/matplotlib/issues/13553#issuecomment-468546794

**Comment by rgommers** [comment]
thanks @jklymak

**Comment by rgommers** [comment]
yep, they just popped up, closing
