### ISSUE TITLE
Allow absolute numbers as input for GridSpec 

### ISSUE THREAD

**Issue by SamSchott** [matplotlib/matplotlib#13566]
Would it be possible to allow absolute numbers as input for `GridSpec` or as `gridspec_kw` keyword arguments? This can be useful in any number of scenarios where one does not want the spacings and margins of plots or subplots to scale proportionally with the figure size but to remain fixed.

For instance, when embedding a matplotlib canvas in a UI, this would allow the alignment of axis positions with other UI elements.

**Comment by jklymak** [comment]
I'm not sure that Matplotlib has an easy way to place axes in absolute (inches) units so that the size of the axes don't change if the figure is resized. I think it can be done with `axes_locator`, but that is pretty advanced usage.

However, I'm not following the need.  If you are embedding the matplotlib canvas in a GUI, just make the embedded canvas a fixed size in the GUI, and the axes elements won't move around.  If Matplotlib were designed to only have fixed-size axes the whole code base would be a lot shorter!

**Comment by SamSchott** [comment]
Ok, I will look into axes locators. From the online documentation, it seems to me that they can be used to retain fixed padding between axes, as well as fixed axes sizes, but not to provide a padding between the axis and the figure edge. But the documentation is not very detailed.

As for use cases: I am trying keep a fixed distance between an axes and the figure edges, i.e., the axes will still resize when resizing the canvas and window, but its distance from the edges will remain fixed instead of expanding or shrinking proportionally. I acknowledge that this is rather niche, but other plotting packages (e.g. pyqtgraph) do this by default. 

This may be relevant to other use cases as well: `tight_layout` does try to maximize the axes space, but has to be called again after resizing a figure to again fill the available area. When giving a fixed padding to the edges, this distance would only need to be adjusted once (to accommodate tick labels, axis labels, etc) and will be retained. Does that make sense?

**Comment by jklymak** [comment]
> As for use cases: I am trying keep a fixed distance between an axes and the figure edges, i.e., the axes will still resize when resizing the canvas and window, but its distance from the edges will remain fixed instead of expanding or shrinking proportionally. I acknowledge that this is rather niche, but other plotting packages (e.g. pyqtgraph) do this by default.

Sure, thats exactly what `constrained_layout` is supposed to do.  If you want to adjust the padding, you can, and the units are in inches.   The issue might be that the axes position changes if the ylabel changes (for instance) , but you can take elements out of the layout by doing `ax.get_xlabel().set_in_layout(False)` , and then the padding will be to the tick labels.  If you want to remove the tick labels from the adjustment that may bee harder, but the smart thing is to change the tick formatter to have a fixed width.  

https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html

Not sure if thats exactly what you want, but its close...

**Comment by SamSchott** [comment]
Amazing, yes, this is what I was looking for. Thank you helping out!
