### ISSUE TITLE
Progress of animation.save (for long animations)

### ISSUE THREAD

**Issue by SBCV** [matplotlib/matplotlib#13561]
Storing long animations with `animation.save()` takes unfortunately a considerable amount of time. Currently, there is (afaik) no possibility to see the progress of the process and it is unclear if the program is running for minutes or hours. 
In my opinion it would be very valuable, if there would be some option to enable user feedback / logging information. For example: `anim.save(output_path, writer, log_progress=True)`

The desired logging information can be added with with a small amount of additional lines:

Original code:
```
for data in zip(*[a.new_saved_frame_seq() for a in all_anim]):
    for anim, d in zip(all_anim, data):
        # TODO: See if turning off blit is really necessary
        anim._draw_next_frame(d, blit=False)
    writer.grab_frame(**savefig_kwargs)
```
With logging:
```
frame_number = 0
number_frames = sum([a.save_count for a in all_anim])
for data in zip(*[a.new_saved_frame_seq() for a in all_anim]):
    for anim, d in zip(all_anim, data):
        # TODO: See if turning off blit is really necessary
        anim._draw_next_frame(d, blit=False)
        if log_progress and frame_number % 100 == 0:
            _log.info('frame ' + str(frame_number) + ' of ' + str(number_frames))
            frame_number +=1
    writer.grab_frame(**savefig_kwargs)
```

If this is valuable for others, I can create a pull request. 
Please let me know, If this such logging is already possible with some other built-in option.

**Comment by jklymak** [comment]
This seems reasonable to me.

**Comment by SBCV** [comment]
I' created a PR (https://github.com/matplotlib/matplotlib/pull/13564), would be nice if you could take a look at it.

**Comment by timhoffm** [comment]
Wouldn't it be reasonable to offer a generic callback, so that e.g. GUIs could do their own progress display?

**Comment by dopplershift** [comment]
I like the idea of a generic callback. I could see *maybe* offering the logging as the default callback, but not convinced having a default is a great idea.

**Comment by QuLogic** [comment]
Not yet fixed.

**Comment by logancyang** [comment]
I'm trying to use this callback when generating a big gif.

```py
anim.save(
            "test.gif",
            writer="imagemagick",
            fps=30,
            progress_callback=lambda i, n: print(i),
        )
```

The problem is it gets stuck at the end when `i` reaches `n` but the saving isn't actually complete. It seems after i reaches n, the writer is working hard to convert the frames into gif. That time is significant compared to the part covered by this progress callback. How do I include the writer into the progress?

**Comment by timhoffm** [comment]
Answered at #19270.
