### ISSUE TITLE
Axes3D voxels is rendered incorrectly with plot_surface, plot_wireframe, or plot

### ISSUE THREAD

**Issue by Obi-Wan** [matplotlib/matplotlib#13580]
### Bug report

**Bug summary**

When using the voxels rendering for Axes3D, surfaces and lines are not stacked correctly in the visual perspective of the axes.

**Code for reproduction**

Adding the following lines to the example from matplotlib's example https://matplotlib.org/gallery/mplot3d/voxels.html produces the glitch:

```x = np.linspace(0, 8, 9)
(xx, yy) = np.meshgrid(x, x, indexing='ij')
zz = np.ones_like(xx) * 4
ax.plot_surface(xx, yy, zz)
```
or
`ax.plot_wireframe(xx, yy, zz)`

before the line
`plt.show()`

**Actual outcome**

![voxels_surface](https://user-images.githubusercontent.com/106832/53702363-6236df80-3e06-11e9-92f9-a19a0fd5cceb.png)

**Expected outcome**

The plane should be rendered below the green voxels and some of the red voxels.
When rotating, some of the voxels become visible. 
![voxels_surface_2](https://user-images.githubusercontent.com/106832/53702387-a3c78a80-3e06-11e9-985c-4c432aa3fe1a.png)

**Matplotlib version**
Using matplotlib from a miniconda distribution:
  * Operating system: linux64
  * Matplotlib version: 3.0.2
  * Matplotlib backend : Qt5Agg
  * Python version: 3.6

Thank you in advance!

Cheers,
Nicola

**Comment by ImportanceOfBeingErnest** [comment]
This is essentially what the [My 3D plot doesn't look right at certain viewing angles](https://matplotlib.org/api/toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles) paragraph of the mplot3d FAQ tells us about.

**Comment by Obi-Wan** [comment]
Thank you for pointing this out! I did my research before submitting the bug, but apparently I missed it, or didn't look for the right thing :)

Anyway, do I read this correctly: 
> This problem will likely not be solved until OpenGL support is added to all of the backends (patches are greatly welcomed). 
in the sense that some of the backends might give the correct output?? Or simply it means that it won't be fixed until the "reduction of 3D data down to 2D + z-order scalar" won't be removed?

**Comment by ImportanceOfBeingErnest** [comment]
Solving this is indeed only possible when having a true 3D renderer. This would require a major rework of the complete mplot3d module and/or a true 3D backend.  
An intermediate solution, where each face of a collection is treated independently across different artists within the "2D + z-order" framework would be possible though. Still no-one has implemented anything alike as of now.

**Comment by Obi-Wan** [comment]
Ok, thank you very much for the explanation!
What should I then do with this issue? Close it, or leave it open indefinitely until this gets fixed?

**Comment by timhoffm** [comment]
Closing as "won't or can't fix" because there are no concrete plans to rewrite with a true 3D renderer.
