### ISSUE TITLE
Not working with python 3.7.2

### ISSUE THREAD

**Issue by Joellidin** [matplotlib/matplotlib#13598]
### Bug report

When trying to plot simple plots it does not work. Using ``matplotlib.use('TkAgg')`` before gives me a window but does not display the graph.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

**Actual outcome**

```
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to 
function correctly if Python is not installed as a framework. See the Python documentation for more 
information on installing Python as a framework on Mac OS X. Please either reinstall Python as a 
framework, or try one of the other backends. If you are using (Ana)Conda please install python.app 
and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the 
Matplotlib FAQ for more information.
```
<img width="752" alt="screenshot 2019-03-05 at 23 19 45" src="https://user-images.githubusercontent.com/19657866/53841806-01daa600-3f9e-11e9-9993-1567dc1f5c3b.png">

**Expected outcome**
When using ``python2`` it works perfectly:
<img width="752" alt="screenshot 2019-03-05 at 23 26 55" src="https://user-images.githubusercontent.com/19657866/53841870-39495280-3f9e-11e9-9d0d-7de5959af2ab.png">

**Matplotlib version**

  * Operating system: macOS Mojave. Version 10.14.3
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):MacOSX or TkAgg
  * Python version: 3.7.2

I installed Matplotlib with virtualenv using pip.

**Comment by Joellidin** [comment]
### Update
I located the problem to be with the virtual environment. Any idea how to get this to work in a virtual environment?

**Comment by dstansby** [comment]
Have you had a read of https://matplotlib.org/faq/osx_framework.html / does the stuff on that page solve your problem?

**Comment by Joellidin** [comment]
My bad. Thank you!

**Comment by jklymak** [comment]
@Joellidin no problem - this does seem to have been some sort of install problem, but it is still curious that you got the behaviour you did.  If there are more problems, please do let us know, but try to reproduce the steps carefully...
