### ISSUE TITLE
text in colorbar does not work correctly with tight layout

### ISSUE THREAD

**Issue by cyclehome** [matplotlib/matplotlib#13600]
### Bug report

**Bug summary**

Setting text on a colorbar via colorbar.ax.text() fails (or even crashes) in many cases when using tight layout.

**Code for reproduction**

Consider this minimal example:
```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

factor = 0.01
arr = factor * np.arange(100).reshape((10, 10))

fig, ax = plt.subplots(1, 1, figsize=(5,4), dpi=100)
fig.suptitle('my title')

im = ax.imshow(arr)

divider = make_axes_locatable(ax)
cax = divider.append_axes("right", "5%", pad="10%")

cb = fig.colorbar(im, cax=cax)
cb.ax.text(0.5, 0.5, 'my colorbar', ha='center', va='center', rotation=90)

fig.tight_layout(rect=[0, 0, 1, 0.95])

plt.savefig("layouttest.png")
```
This produces the expected outcome:
![layouttest](https://user-images.githubusercontent.com/48286302/53886840-3c395700-4021-11e9-9da3-09ce1f8f810d.png)
The colorbar size is aligned with the plot (as describes here: https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html), and the colorbar description is centered in the middle of the colorbar.

Now, change _factor_ from 0.01 to 0.001 ...

**Actual outcome**

we get this:
```
C:\Program Files\Python37\lib\site-packages\matplotlib\tight_layout.py:181: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  warnings.warn('Tight layout not applied. '
Traceback (most recent call last):
  File "C:\dev\workspaces\Python_playground\layout3.py", line 20, in <module>
    fig.tight_layout(rect=[0, 0, 1, 0.95])
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\figure.py", line 2374, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\tight_layout.py", line 379, in get_tight_layout_figure
    left += kwargs["left"]
TypeError: 'NoneType' object is not subscriptable
```

and when _factor_ is 0.1 instead:

![layouttest](https://user-images.githubusercontent.com/48286302/53887412-81aa5400-4022-11e9-842a-9a0d8f3f496a.png)

See how the description for the colorbar is not placed correctly. The position changes with different _factor_ s, e.g. try 0.02 for some other position.

So, apparently there are two bugs here:

1. the obvious one is in **tight_layout.py** line 361:
_auto_adjust_subplotpars()_ may return None as a result, but the result (_kwargs_) is then accessed with _kwargs["left"]_ on line 379 ... (see output above).

2. tight layout calculation for colorbar text
Apparently there is a bug in the layout calculation, which leads to wrong positioning of the colorbar text. The outcome may be so wrong that tight-layout is "rejected" altogether, which then leads to the crash above.
And it obviously depends on the values of the matrix that is being plotted ...

**Expected outcome**

I'd expect stable positioning of the colorbar text, regardless of the matrix values. This worked well in Matplotlib 2.x (and Python 2).

A few more notes, just in case you might ask: why don't you do ... instead of ... :

- why _cb.ax.text()_ and not _cb.set_label()_?
because _text()_ allows relative positioning, so I have the text centered exactly in the middle of the colorbar. _set_label()_ instead will place the text beside the colorbar, which takes too much space if I need several colorbars. I could adjust positioning with _labelpad_, but that is in pixels and needs to be adjusted by hand for every single plot, which is not suitable for automated batch plot generation ...

- why _plt.subplots()_ instead of _plt.figure()_?
because in my real application I need several subplots ...

- why _tight_layout_ with a _rect_?
because otherwise the figure title may overlap with the plot

- why _imshow()_ instead of _matshow()_?
it fails with both functions

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.2
  * Jupyter version (if applicable):
  * Other libraries: numpy

**Comment by dstansby** [comment]
Could you paste a minimal snippet of code that reproduces the problem?

**Comment by cyclehome** [comment]
yes sorry, hit the wrong button just after entering the title. Report should be complete now.

**Comment by jklymak** [comment]
Colorbars changed in 3.0 to actually have real units instead of normalized ones so if you want to place text half way through the colorbar you need to place at y=1/2 (vmax-vmin).  Thi has nothing to do w tight layout.  

The tight layout error seems strange and someone should look at that.

**Comment by jklymak** [comment]
Note you can also specify a transform to place the text in axes coordinates.   Transform=ax.transAxes (I think)

**Comment by ImportanceOfBeingErnest** [comment]
May I suggest to use axes coordinates for placing the text? This would make its position independent of any "factor".
```
cb.ax.text(0.5, 0.5, 'my colorbar', ha='center', va='center', rotation=90,
           transform=cb.ax.transAxes)
```

**Comment by cyclehome** [comment]
ok, this solves the problem. Thanks guys!
Still the bug in tight_layout.py (access of None return value) should be looked at ...

**Comment by jklymak** [comment]
> why tight_layout with a rect? because otherwise the figure title may overlap with the plot

You can use `constrained_layout` instead of tight_lyout to get around that limitation of `suptitle`.
