### ISSUE TITLE
legend's framealpha kwarg does not apply when writing to an eps file

### ISSUE THREAD

**Issue by canerozer** [matplotlib/matplotlib#13604]
**Bug summary**
Hello,

I plot an arbitrary signal and I use the legend with framealpha kwarg. Then, I try to save the plot in both eps and png formats however framealpha is not being used when the savefig command renders the plot in eps format despite it is for png.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


t = np.arange(20)
x = np.hstack((-1.5*np.ones(10), np.zeros(10)))

fig, ax = plt.subplots()

ax.plot(t, x, 'blue')

blue = mpatches.Patch(color='blue', label="A Random Signal")
ax.legend(handles=[blue], loc=3, framealpha=0.5)

fig.savefig("test.png")
fig.savefig("test.eps", format="eps")
```

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.5.2
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: jupyterlab==0.35.4

**Comment by jklymak** [comment]
As @anntzer notes in #13605, the ps backend doesn't handle alpha at all (it has not concept of it).

**Comment by timhoffm** [comment]
Closing as "documented to not work" per #13605.
