### ISSUE TITLE
How to show a graph as a slideshow by reading the file in Pyqt5

### ISSUE THREAD

**Issue by binsha1** [matplotlib/matplotlib#13613]
### Bug report

**Bug summary**

I wish to plot the graph part by part as to appear this as a slideshow. First I want to plot a set of data then after a time interval I wish to plot another set of data automatically as a slideshow.

**Code for reproduction**

```python
# Paste your code here
#
#
```class MatplotlibWidget(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)
        loadUi("graphgenerate.ui", self)
        self.setWindowTitle("PyQt5 & Matplotlib Example GUI")
        self.playbutton.clicked.connect(self.drawGraph)
        self.addToolBar(NavigationToolbar(self.MplWidget.canvas, self))


    def drawGraph(self):
        f1 = open('TESTIP2.txt', 'r')
        print(f1)
        data = np.genfromtxt(f1)
        m = np.size(data, 0)
        n = np.size(data, 1)
        x = data[:, 0].reshape(m, 1)
        y = data[:, 1].reshape(m, 1)
        iters = m // 4
        xs=[]
        ys=[]
        for i in range(iters):
            xs.append(x[i])
            ys.append(y[i])
        self.MplWidget.canvas.axes.clear()
        self.MplWidget.canvas.axes.plot(xs,ys)
        self.MplWidget.canvas.axes.legend(('cosinus', 'sinus'), loc='upper right')
        self.MplWidget.canvas.axes.set_title('Signal' )
        self.MplWidget.canvas.draw()

**Actual outcome**

Wish to appear my graph as a slideshow

**Matplotlib version**

  * Windows:
  * Matplotlib 3.0: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python 3.5:
  * Pycharm:
  * Other libraries: 


pip install matplotlib

**Comment by timhoffm** [comment]
Please note that this is the bug tracker. Usage questions are better placed at the gitter channel, matplolib-users mailinglist or stackoverflow, see https://matplotlib.org/devdocs/#need-help.

Also, it's not quite clear what the actual problem is. Does the window not show, does the window show but the plot doesn't render?

**Comment by binsha1** [comment]
> Please note that this is the bug tracker. Usage questions are better placed at the gitter channel, matplolib-users mailinglist or stackoverflow, see https://matplotlib.org/devdocs/#need-help.
> 
> Also, it's not quite clear what the actual problem is. Does the window not show, does the window show but the plot doesn't render?

I want the graph to be plotted as a slideshow after reading the file. But I don't know how to do it in PyQt5, but it works in matplotlib without pyqt5. I am trying to implement a GUI app for graph plotting which shows graph as a slideshow so that the data can be visualized clearly.
