### ISSUE TITLE
constrained_layout and tight_layout vertical auto sizing breaks on window resize when ylabel text is long; axis collapse

### ISSUE THREAD

**Issue by Dodelo** [matplotlib/matplotlib#13653]
### Bug report

When the ylabel text is very long, and a figure is created with constrained_layout=True, or fig.set_constrained_layout(True), or set_tight_layout(True) then the axis will collapse once you try to resize the window. It will **NOT** collapse when you use tight_layout().

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig=plt.figure(constrained_layout=True);
#fig=plt.figure(); 
#fig.set_constrained_layout(True); # this has the same effect 
#fig.set_tight_layout(True); # this also has the same effect
plt.plot((0,1,2,3), (2,1,2,0));
plt.xlabel("xlabel");
plt.grid();
yl=plt.ylabel("This is a very long ylabel which may have to be wrapped depending on the figure height");
plt.show();
```

**Actual outcome**
Initial Output:
![image](https://user-images.githubusercontent.com/40698393/54141767-958cf600-4426-11e9-9dd6-8a996e063bfb.png)

Upon increasing the window size:
![image](https://user-images.githubusercontent.com/40698393/54141798-a63d6c00-4426-11e9-9b61-58b11ca51672.png)

Increasing further:
![image](https://user-images.githubusercontent.com/40698393/54142049-2a8fef00-4427-11e9-8b58-edc3a6808ce7.png)

**Expected outcome**
I would expect the axis to fill the available space regardless of the length of the ylabel

**Matplotlib version**

  * Operating system: macOS 10.14.3
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MACOSX
  * Python version: 3.5.4
  * Jupyter version (if applicable): not required
  * Other libraries: none required

**Comment by jklymak** [comment]
This is the same issue as #13650, so I'll close here if that is OK.

**Comment by Dodelo** [comment]
Hi, no that is not okay, that is not the same issue! The problem axis collapsing on resizing events does not occur when you use tight_layout() only. These are two separate bugs as far as I can gather.

**Comment by Dodelo** [comment]
Also, please try to reproduce the two issues, you'll see that they are different from each other.

**Comment by jklymak** [comment]
They are the same issue.  In both cases you are trying to use a constraint solver, but giving it an impossible constraint.  The two constraint solvers are different, so the response *is* different to the impossible constraint, but the reason is the same.

**Comment by Dodelo** [comment]
Please look in the bug description, I specifically point out that the resizing behavior is different depending on how you apply the layout. The other bug report I opened deals with the size of the vertical margins, but it does not involve resizing at all. Therefore both reports should be opened.
