### ISSUE TITLE
tight_layout() leaves white margins when ylabel is long

### ISSUE THREAD

**Issue by Dodelo** [matplotlib/matplotlib#13650]
### Bug report

When you make a plot with a very long ylabel and then use tight_layout(), the actual graphing area is very small because tight_layout() has made the top and bottom margins very large. I'm not sure what purpose this serves, because it just adds white space instead of showing the data. I have reproduced the bug in Spyder and when running from the Terminal. 
Edit to add: this occurs without wrap=True as well.
Edit to add 2: issue occurs in matplotlib 2.2.2. I'll update and confirm the issue persists.

```python
import matplotlib.pyplot as plt
fig=plt.figure();
plt.plot((0,1,2,3), (2,1,2,0));
plt.ylabel("This is a very long ylabel which may have to be wrapped depending on the figure height", wrap=True);
plt.xlabel("xlabel");
plt.grid();
plt.tight_layout();
plt.show();
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/40698393/54128972-89e10580-440d-11e9-97c2-b07b42a5686a.png)
![image](https://user-images.githubusercontent.com/40698393/54128977-8d748c80-440d-11e9-97a8-08dab2ea2cc6.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/40698393/54129117-daf0f980-440d-11e9-96b9-872ecd73e09a.png)

tight_layout should align the labels and axis borders neatly to fill the available figure canvas; it can be achieved manually by creating a short ylabel first, then running tight_layout(), and then creating the real label

This can be achieved by running the following code:

```python
import matplotlib.pyplot as plt
fig=plt.figure();
plt.plot((0,1,2,3), (2,1,2,0));
plt.xlabel("xlabel");
plt.grid();
plt.ylabel("ylabel\n");
plt.tight_layout();
plt.ylabel("This is a very long ylabel which may have to be wrapped depending on the figure height", wrap=True);
plt.show();
```

**Matplotlib version**

  * Operating system: macOS 10.14.3
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg when run from Spyder; MacOSX when run from Terminal
  * Python version: 3.5.4
  * Jupyter version (if applicable): 4.4.0 but not necessary
  * Other libraries: none necessary

 anaconda installation

default

**Comment by jklymak** [comment]
The reason is that if you have multiple subplots you don’t want that really long ylabel overlapping the other subplots.  

In recent matplotlib you can remove the ylable from the layout manually by using set_in_layout(True).

**Comment by jklymak** [comment]
Oopps ok I missed that you’d put wrap=True in there.  I’m not sure what wrap=True is supposed to be doing but it’s certainly problematic to have something that is supposed to wrap to a certain size but then the size depends on the size of that object after wrapping.  To be honest I didn’t know we had wrap=True.  But I’m not surprised it doesn’t play well with geometry management.   For fun did you try constrained_layout=True?

**Comment by Dodelo** [comment]
> The reason is that if you have multiple subplots you don’t want that really long ylabel overlapping the other subplots.
> 
> In recent matplotlib you can remove the ylable from the layout manually by using set_in_layout(False)

Hi, thank you for taking the time to investigate the issue I found. Unfortunately, I don't quite understand you yet:

- I don't have multiple subplots, just one
- Even with multiple subplots, you'd want the actual axis to take up as much of the area available to each subplot cell
-I'll try the "set_in_layout(False)" but I need to update MPL first; I just checked and I'm running 2.2.2 (the version anaconda ships with)

> Oopps ok I missed that you’d put wrap=True in there. I’m not sure what wrap=True is supposed to be doing but it’s certainly problematic to have something that is supposed to wrap to a certain size but then the size depends on the size of that object after wrapping. To be honest I didn’t know we had wrap=True. But I’m not surprised it doesn’t play well with geometry management. For fun did you try constrained_layout=True?

the wrap=True doesn't change this behavior, the issue occurs without it as well

if I create my figure with fig=plt.figure(constrained_layout=True) then unspeakable things happen when the window is resized. I'll update MPL before confirming these issues.

**Comment by Dodelo** [comment]
I just checked, the issues persist in 3.0.3. I'll need to create separate bug reports for issues that occur when you use set_tight_layout(), fig=plt.figure(constrained_layout=True) or set_constrained_layout() in conjunction with long y axis labels. I'll link these here once I've finished them.

**Comment by jklymak** [comment]
1.  wrap=True is a text property that kind of relies on the text being inside the axes for it to work properly.  I'm not surprised it causes problems, and I would very much recommend against using it for labels.  If you know where you want a carriage return, you can/should do `set_ylabel('First part\nSecondPart')` and you will get a nice carriage return. Matplotlib is a crummy text layout engine, and wrapping text is non-trivial.  

2. For `wrap=False`, the way the layout managers work (both tight_layout and constrained_layout) is they shrink the size of the axes until the axes in the figure no longer overlap and they are less-wide than the figure.  If you give either layout managers such a long ylabel that it spills off the page, it will try to shrink the axes size to zero in a vain attempt to get everything to fit. 

The moral of the story is that we can't do magic with really long pieces of text in labels.  If you want long text, I'd suggest just using Text, and keep the labels succinct.

**Comment by Dodelo** [comment]
Hm I don't quite get it. Regardless of whether I have subplots or not, I have a certain amount of vertical space available for my axis. The axis should fill this space as much as possible (sans some sensible padding of course). Wrapping the text shouldn't be too hard I you know how much space you have to fit it in. I don't get why you'd shrink the axis if the ylabel belonging to that axis is "higher" than the axis?

> The moral of the story is that we can't do magic with really long pieces of text in labels. If you want long text, I'd suggest just using Text, and keep the labels succinct.

Yeah I'll just use annotations. Hopefully somebody will enable MPL to work with long ylabels.

**Comment by jklymak** [comment]
Please read https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html and https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py for why the axes size is shrunken to accomodate labels, and if it still doesn't make sense feel free to disucuss further...

**Comment by Dodelo** [comment]
I've added for related issues which occur when resizing a window when a ylabel is long: https://github.com/matplotlib/matplotlib/issues/13653

**Comment by mdruiter** [comment]
Wrapping is irrelevant here.
Point is that the y axis is unnecessarily collapsed when the ylabel happens to be longer than the axes. For example in subplots, in small figures, with large label fonts, etc.
I don't see a way to exclude just the ylabel from layouting (which could work around it).

**Comment by jklymak** [comment]
All Artists have an in_layout method

**Comment by mdruiter** [comment]
> All Artists have an in_layout method

Please suggest a specific fix then, as this doesn't help:
`plt.ylabel('some veeeery long label').set_in_layout(False)`

**Comment by jklymak** [comment]
What is a reproducible example that fails in?

**Comment by mdruiter** [comment]
What about [the original one](https://github.com/matplotlib/matplotlib/issues/13650#issue-419484307) at the top?
`
import matplotlib.pyplot as plt
fig=plt.figure()
plt.plot((0,1,2,3), (2,1,2,0))
plt.ylabel("This is a very long ylabel which may have to be wrapped depending on the figure height").set_in_layout(False)
plt.xlabel("xlabel")
plt.grid()
plt.tight_layout()
plt.show()
`

**Comment by jklymak** [comment]
I see.  You are correct, you cannot exclude the ylabel from the layout, otherwise the new position of the axes would cover the ylabel (i.e. the axes would be as big as it would be if the ylabel was not there)

The issue here is

1. The label is too long, and the layout managers try to make enough space around the axes so that it will fit.  This is desirable in the case where there are two subplots above one another, and you don't want the two ylabels overlapping each other.  Of course its undesirable when the label is longer than the figure is high, but in my opinion at that point the user needs to intervene anyways.
2. wrap doesn't work.  But if I understand correctly, wrap needs a fixed-sized box to work with, and we don't have a fixed size for the ylabel.  

I can vaguely imagine various complicated solutions to these issues.  If anyone had a specific suggestion for how to fix this, even with pseudocode, that would be welcome.  

The workarounds are to manually wrap, or to not use the layout managers.

**Comment by ImportanceOfBeingErnest** [comment]
An obvious workaround would also be to first use a random label, call `tight_layout`, then put in the desired label:

```
import matplotlib.pyplot as plt
fig=plt.figure()
plt.plot((0,1,2,3), (2,1,2,0))
plt.ylabel("Blabla\nblubb")
plt.xlabel("xlabel")
plt.grid()
plt.tight_layout()
plt.ylabel("This is a very long ylabel which may have to be wrapped depending on the figure height", wrap=True)
plt.show()
```

If it was possible to use the in_layout property *per direction*, this could also be useful here, i.e. include the label in the horizontal direction, but exclude in vertical direction.

**Comment by jklymak** [comment]
Right, thats a great workaround for leaving things out of the layout.  For constrained_layout you can also turn it off after a draw.

**Comment by mdruiter** [comment]
Sure, but that defeats the purpose of `constrained_layout` doing things automatically... It's very hard to automate a workaround for a general case.

I like the suggestion of `in_layout` *per* *direction*: that's exactly the issue here! I understand it's quite some work to implement though. :-/

**Comment by rcomer** [comment]
With v3.7.1 the code from the OP now gives me

![temp](https://github.com/matplotlib/matplotlib/assets/10599679/eb3112f6-c69a-4c56-8a68-39eddc8a6844)

so I guess this has been fixed at some point.
