### ISSUE TITLE
Support \boldsymbol. (Feature request.)

### ISSUE THREAD

**Issue by smithsp** [matplotlib/matplotlib#1366]
While I understand that it is possible to use 

```
text.usetex = True
```

along with the appropriate declarations for text.latex.preamble to be able to use \boldsymbol, it would be nice to be able to keep 

```
text.usetex = False
```

with something like

```
title(r'$\boldsymbol\psi_N$=0.95')
```

to achieve bold symbols.

Even better would be to detect whether the current font is bold, and automatically substitute in a \boldsymbol command.

(As always, I'm appreciative of the work that matplotlib developers have contributed, but I also know that the squeaky wheel gets the grease.)

**Comment by petehuang** [comment]
Seems like there are really two issues here: one for the original `\boldsymbol` request and one for a broader font documentation request

The latter certainly stands, but where do we stand on `\boldsymbol`? Is this a can't fix (i.e., what's our gut sense on whether or not a suitable font exists?)?

**Comment by mojca** [comment]
The XITS fonts (derived work from STIX that did not deliver for years and years and years) contains both a regular and a bold variant.

The Polish TeX user group GUST is working on a number of free Unicode math fonts and some of them come or will come in a bold variant. Even the non-bold fonts contain a number of bold symbols inside the "bold" Unicode slots.

**Comment by QuLogic** [comment]
We no longer use Vera + CM fonts, but DejaVu fonts in all cases (by default.) These fonts contain bold-italic symbols here:
![screenshot from 2017-01-01 19-40-17](https://cloud.githubusercontent.com/assets/302469/21583687/31a0ad72-d05a-11e6-8e7f-bf496abb80ca.png)
so there is no need for extra fonts.

**Comment by mojca** [comment]
There is also http://www.gust.org.pl/projects/e-foundry/tex-gyre-dejavu-math. If bold symbols from the Unicode math repertoire is going to be used, it should be pretty straightforward to switch to a different Unicode Math OTF font.

**Comment by mojca** [comment]
The request is still valid/wanted.

**Comment by egnerney** [comment]
\perp won't go bold for me using this and when I use Latex then nothing will go bold and the font looks worse/inconsistent with other plots. Please help.
