### ISSUE TITLE
plt.ion() recently changed behaviour

### ISSUE THREAD

**Issue by iago-lito** [matplotlib/matplotlib#13661]
### Bug report

Interactive plot windows do not open anymore after `plt.ion()`, as described [here](https://stackoverflow.com/questions/55138174/plt-ion-recently-changed-behaviour?noredirect=1#comment97020724_55138174) on SO.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.scatter(1, 1)
plt.show() # Blocks and opens a graphical window as usual.

plt.ion()
plt.scatter(1, 1) # Does *not* open a graphical window anymore as I expect.
plt.scatter(2, 2) # Does *not* update the graphical window anymore as I expect (there is still no window at all)

plt.ioff()
plt.show() # The window opens at last, but it's blocking.
```

**Matplotlib version**

  * Operating system: Linux 5.0.0-arch1-1-ARCH on x86_64
  * Matplotlib version: 3.0.3-1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.2
  * Jupyter version (if applicable):
  * Other libraries:

matplotlib installed with `sudo pacman -S python-matplotlib`

**Comment by oscargus** [comment]
I think that his has been solved. At least on my CentOS maching running current main, it is automatically opened.

Will close in a while unless someone has a counter-example.

**Comment by timhoffm** [comment]
@oscargus in particular for longer-existing issues you can be a bit bolder and close if you think the issue is solved:

> I'm closing because this works on current main (CentOS). Please report back if the problem still exists.

People can still post to closed issues.
