### ISSUE TITLE
How to customize quantiles in boxplot

### ISSUE THREAD

**Issue by liupandatacs** [matplotlib/matplotlib#13675]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Please submit a full bug report if you have found a bug. OTOH this looks like a [stackoverflow](https://stackoverflow.com/questions/tagged/matplotlib) question...
