### ISSUE TITLE
Boxplot xlim not correctly calculated

### ISSUE THREAD

**Issue by danjjl** [matplotlib/matplotlib#13713]
### Bug report

**Bug summary**

In figure with multiple `boxplot` calls and manual `positions`. The `xlim` is not set correctly.

**Code for reproduction**

```python
plt.figure()
plt.boxplot(np.random.rand(100,3), positions=[2, 4, 6])
plt.boxplot(np.random.rand(100,3), positions=[1, 3, 5])
plt.show()
```

**Actual outcome**

![boxplot](https://user-images.githubusercontent.com/747240/54598787-941c8880-4a39-11e9-9949-454a546700a7.png)

**Expected outcome**

I would have expected the `xlim` to be set to `[0.5, 6.5]`.
![Expected outcome](https://user-images.githubusercontent.com/747240/54598933-df369b80-4a39-11e9-891c-588642300a35.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04.6
  * Matplotlib version: 3.0.2
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 3.7.1
  * Jupyter version: 4.4.0

Matplotlib was installed from conda using the main channel.

**Comment by danjjl** [comment]
Equivalent `plot` figure does produce the expected outcome.

```python
plt.figure()
plt.plot([50, 150], [0, 10])
plt.plot([0, 100], [-10, 10])
plt.show()
```

![plot](https://user-images.githubusercontent.com/747240/54599309-a0edac00-4a3a-11e9-9436-060c87f8e2a3.png)

**Comment by danjjl** [comment]
This commit looks related to the issue: https://github.com/tacaswell/matplotlib/commit/8c9f4d4c937bb31440c35ff52954fd4cdce1a136

**Comment by anntzer** [comment]
Likely https://github.com/matplotlib/matplotlib/pull/13444 should close this.
