### ISSUE TITLE
Feature request: similar attribute suggestions

### ISSUE THREAD

**Issue by NicolasHug** [matplotlib/matplotlib#13714]
Years into using matplotlib I still find myself constantly misusing functions from `pyplot` and methods from `Axes` objects, e.g. `plt.xlabel` vs `ax.set_xlabel`.

How difficult would it be to suggest similar-looking attribute names when one accesses a non-existing attribute? Something like what `git` does:

```
 » git statuss   
git: 'statuss' is not a git command. See 'git --help'.

The most similar command is
	status
```

If that'd be a welcome addition I'd be happy to give it a try.

Somehow related, is there any reason that `boilerplate.py` doesn't generate `plt.set_xlabel`? Why just `plt.xlabel`?

**Comment by jklymak** [comment]
Is there a way for a library to even capture an AttributeError and try to change it?  Otherwise that seems like an interpreter function not the library’s?

**Comment by NicolasHug** [comment]
I was thinking about using `__getattr__()`, something like (warning, bad code):


```python
def get_similar_attributes(obj, attr):                                         
    # return attributes found in object that are similar to attr                  
    # (needs actual logic)                                                        
    return 'some_arbitrary_string'                                                
                                                                                  
                                                                                  
class C:                                                                          
                                                                                  
    def __getattr__(self, attr):                                                  
        try:                                                                      
            return self.__dict__[attr]                                            
        except Exception as e:                                                    
            similar_attributes = get_similar_attributes(self, attr)               
            raise ValueError(                                                     
                'C has no {} attribute, did you mean {}?'.format(                 
                    attr, similar_attributes)                                     
            )                                                                     
                                                                                  
o = C()                                                                           
o.some_methodd()
```

```
Traceback (most recent call last):
  File "lol.py", line 20, in <module>
    o.some_methodd()
  File "lol.py", line 16, in __getattr__
    attr, similar_attributes)
ValueError: C has no some_methodd attribute, did you mean some_arbitrary_string?
------------------------------------------------------------
```

**Comment by jklymak** [comment]
For every class?  Are there other libraries that do this?

**Comment by NicolasHug** [comment]
>For every class?

For `Axes` and `pyplot` (which is a module so it might be trickier). Maybe Figure too? That would already be helpful I think.

>Are there other libraries that do this?

Not that I know of

**Comment by timhoffm** [comment]
Writing code (interactively or in an editor) is quite different from executing a program on the command line. Nowadays, a lot of write-time checks are available for the former, so that a check at execution time is the inferior solution and IMO not worth of adding the complexity to the code.

Much of this can be prevented by using tab-completion in ipython/jupyter/your IDE of choice. I grew a habit of tabbing a lot. If it doesn‘t complete, there‘s likely an error. Also, IDEs can be quite helpful in highlighting missing attributes. Not every is perfect, but for pyplot/Axes it should do.

**Comment by anntzer** [comment]
There are plenty of modules online for that, e.g. a quick googling yields https://github.com/SylvainDe/DidYouMean-Python, https://github.com/dutc/didyoumean.  It doesn't make sense to implement this specifically for Matplotlib.

**Comment by NicolasHug** [comment]
I didn't know these existed, thanks for the links.

I'm still curious about why some of the functions between Axes and pyplot match while some don't match, but feel free to close the issue.

Thanks

**Comment by timhoffm** [comment]
The difference is mostly that the `pyplot` API is inspired by MATLAB and `Axes` is a classical object-oriented API. For actions, mostly plotting-functions, the names are the same e.g. `plot()`. For configuring properties such as labels MATLAB uses bare functions, hence `plt.xlabel()`. The classical OOP paradigm is getters/setters, i.e. `ax.get_xlabel()`/`ax.set_xlabel()`.

Maybe this comparison table helps:

|                                  | pyplot           | Axes                 |
| -------------------------------- | ---------------- | -------------------- |
| Actions                          | plt.plot()       | ax.plot()            |
| Setting properties (e.g. xlabel) | plt.xlabel(text) | ax.set_xlabel(text)  |
| Getting properties (e.g. xlabel) | plt.xlabel()     | ax.get_xlabel()      |
