### ISSUE TITLE
xlim on datetime axes not datetimes, but float

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#13727]
When `get_xlim()`ing an axis with `datetime` data, the limits will still be reported and floats:
```python
from datetime import datetime
import matplotlib.pyplot as plt

values = [50, 50.02]
time = [datetime(2016, 10, 10, 18, 00), datetime(2016, 10, 10, 18, 15)]
plt.plot(time, values)
ax = plt.gca()
ax.set_xlim(
  datetime(2016, 10, 10, 17, 00),
  datetime(2016, 10, 10, 19, 00)
)
print(ax.get_xlim())
```
```
(736247.7083333334, 736247.7916666666)
```
Whoops!

This is with mpl 3.0.3 on Python 3.7.2.

**Comment by jklymak** [comment]
That’s how dares work.  If you need to get datetime  back look up num2date. You could argue that we should do that conversion but we have to handle different date inputs and they all get turned into floats early on.

**Comment by nschloe** [comment]
Alright then, I can work with `num2date`.
