### ISSUE TITLE
Qt5Agg backend causes warning with new PyQt5 versions (Linux\Ubuntu)

### ISSUE THREAD

**Issue by davcrom** [matplotlib/matplotlib#13722]
### Bug report

**Bug summary**

With the backend set to Qt5Agg, importing pyplot causes an annoying warning with new versions of PyQt5 (>=5.8) and causes my IPython kernel to crash with older versions.

**Code for reproduction**

```
ipython --quick
from matplotlib import pyplot
```
or
```
python
from matplotlib import pyplot
pyplot.plot()
```

**Actual outcome**

```
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
```

IPython has the --quick flag to disable any default import of MPL. The problem persists when I comment out the backend specification in my matplotlibrc file, but goes away when I remove the file completely.

**Matplotlib version**

  * Operating system: Ubuntu 16.04.5 LTS xenial
  * Matplotlib version: 3.0.3 (but the problem also exists with e.g. v2.0.0)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.5.2
  * IPython version: 7.3.0 

All python libraries installed with pip.

**Comment by timhoffm** [comment]
I cannot reproduce this using Qt 5.9.2. Can you please post your matplotlibrc file?

**Comment by davcrom** [comment]
@timhoffm matplotlibrc uploaded as .txt (original format is not supported), thanks.
[matplotlibrc.txt](https://github.com/matplotlib/matplotlib/files/3008007/matplotlibrc.txt)

**Comment by timhoffm** [comment]
Sorry, still not reproducible. Do you have the `QT_STYLE_OVERRIDE` environment variable set on your system? If so, try to
- unset it
- set it to empty
- set it to `fusion`

**Comment by davcrom** [comment]
It was set to 'gtk', setting it to either empty or 'fusion' fixed the problem. Thanks!

**Comment by davcrom** [comment]
Sorry, but how can this variable be set permanently?
Other threads in various places can't provide a clear answer for this.

```grep -R "QT_STYLE_OVERRIDE"```
only returns results from by bash history.

Thanks in advance.

**Comment by WeatherGod** [comment]
You could add the line `export QT_STYLE_OVERRIDE=fusion` to your ~/.bashrc
file.
