### ISSUE TITLE
imshow with LogNorm and colorbar borks under extreme dynamic range image

### ISSUE THREAD

**Issue by jahomax** [matplotlib/matplotlib#13729]
### Bug report

**Bug summary**

imshow of an image `x` for which `numpy.log2(x[x != 0])).ptp() > 1024` fails if you use `matplotlib.colors.LogNorm()` and `colorbar`. In other words if your dynamic range is greater than 2 ** 1024, not including zeros, it fails.

**Code for reproduction**

```python
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np

x = np.ones((2,1))
for xi in (5.563e-309, 5.562e-309):
    x[1]=xi
    plt.imshow(x,norm=LogNorm(),aspect='auto')
    plt.colorbar()
    plt.title('log2(x.T)={}'.format(np.log2(x.T)))
    plt.tight_layout()
    plt.show()
```

**Actual outcome**

![Screenshot from 2019-03-21 16 02 20](https://user-images.githubusercontent.com/45937110/54768614-6e3ce280-4bf7-11e9-9cd8-d6b5621abc18.png)
... Big vertical space ...
![Screenshot from 2019-03-21 16 02 38](https://user-images.githubusercontent.com/45937110/54768636-79900e00-4bf7-11e9-80b6-1462f74a59ac.png)

**Expected outcome**
I think it ought to clip the range, perhaps by finding the middle region of logarithmic range, and set the vmin and vmax at that range's edge. 

**Matplotlib version**

  * Operating system: openSUSE Leap 15.0
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.7
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: numpy 1.16.2

Python built from source; operating in a venv virtual environment; installing things via pip.

**Comment by jklymak** [comment]
`RuntimeWarning: overflow encountered in double_scalars` is a pretty explicit warning that you are asking the computer to do things it can't do using floating point arithmetic.  Its challenging, to say the least, for a library to check every possible overflow condition, so at some point its up to the user to see those warnings and adjust their data accordingly.   

Your heuristic with what to do w/ the overflow data is fine, but someone else will inevitably want a different one, so I think this is really better handled by the user.

**Comment by jahomax** [comment]
That makes sense, I can accept that. Will close.
