### ISSUE TITLE
get_data() from axvline wrong?

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#13733]
When drawing a line with `axvline`

![line](https://user-images.githubusercontent.com/181628/54820795-99c7d780-4ca0-11e9-95e8-63983f447bc8.png)

it draws through the whole plot. When fetching the y-coordinates via `get_data()` from the corresponding `Line2D` object, however, it says `[0, 1]` (instead of `[0, 107]` in this case).
```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

s = np.random.normal(0, 1, 1000)

plt.hist(s, 30)
plt.axvline(1.96)
# plt.show()

ax = plt.gca()
for c in ax.get_children():
    if isinstance(c, matplotlib.lines.Line2D):
        print(c.get_data())
```
```
([1.96, 1.96], [0, 1])
```
Any hint on what's going wrong?

(From https://github.com/nschloe/matplotlib2tikz/issues/195.)

**Comment by jklymak** [comment]
The y coordinate is in axex units not data units

**Comment by nschloe** [comment]
What are `axex` units, and how can find out about the unit from the `Line2D` object?

**Comment by jklymak** [comment]
Look at the transform.  Axes units are 0 to 1 with 0,5 being half way up the axes

**Comment by nschloe** [comment]
Thanks @jklymak, I'll play around with that.

**Comment by nschloe** [comment]
For the record, I got this now with two transformations:
```python
def _transform_to_data_coordinates(obj, xdata, ydata):
    if obj.get_transform() != obj.axes.transData:
        points = numpy.array([xdata, ydata]).T
        transform = matplotlib.transforms.composite_transform_factory(
            obj.get_transform(), obj.axes.transData.inverted()
        )
        return transform.transform(points).T
    return xdata, ydata
```
This method transforms `xdata`, `ydata` to data coordinates no matter what.
