### ISSUE TITLE
The example of axes.bar() is wrong, need to modify

### ISSUE THREAD

**Issue by hudingyin** [matplotlib/matplotlib#13749]
### Bug report

**Bug summary**

The example of axes.bar() is wrong
https://matplotlib.org/gallery/lines_bars_and_markers/categorical_variables.html

**Code for reproduction**

(Just copy from the above  url)
```
import matplotlib.pyplot as plt

data = {'apples': 10, 'oranges': 15, 'lemons': 5, 'limes': 20}
names = list(data.keys())
values = list(data.values())

fig, axs = plt.subplots(1, 3, figsize=(9, 3), sharey=True)
axs[0].bar(names, values)
axs[1].scatter(names, values)
axs[2].plot(names, values)
fig.suptitle('Categorical Plotting')
```

### Output
```
Traceback (most recent call last):

  File "<ipython-input-165-e4c3e30cc8ef>", line 1, in <module>
    runfile('D:/Workspace/Python/Computational Neuroscience/python tutorials.py', wdir='D:/Workspace/Python/Computational Neuroscience')

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "D:/Workspace/Python/Computational Neuroscience/python tutorials.py", line 8, in <module>
    axs[0].bar(names, values)

  File "C:\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1811, in inner
    return func(ax, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 2129, in bar
    label='_nolegend_'

  File "C:\Anaconda3\lib\site-packages\matplotlib\patches.py", line 641, in __init__
    self._x = float(xy[0])

ValueError: could not convert string to float: 'oranges'
```

### Fixed example
I fixed the example:

```
import numpy as np
import matplotlib.pyplot as plt

data = {'apples': 10, 'oranges': 15, 'lemons': 5, 'limes': 20}
names = list(data.keys())
values = list(data.values())

ind = np.arange(len(names))
fig, axs = plt.subplots(1, 3, figsize=(9, 3), sharey=True)
axs[0].bar(ind, values)
axs[0].set_xticks(ind)
axs[0].set_xticklabels(names)
axs[1].scatter(ind, values)
axs[1].set_xticks(ind)
axs[1].set_xticklabels(names)
axs[2].plot(ind, values)
axs[2].set_xticks(ind)
axs[2].set_xticklabels(names)

fig.suptitle('Categorical Plotting')
```

**Matplotlib version** 

  * Operating system: WIN 10
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline
  * Python version: 3.5
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by timhoffm** [comment]
Please recheck the matplotlib version you are using. I cannot reproduce the above bug with v3.0.3. Also the traceback line numbers do not match with the code of v3.0.3.

**Comment by ImportanceOfBeingErnest** [comment]
The images in the documentation are created by actually running the respective matplotlib version. For newer versions the version number is part of the title. You can also check the version number from the URL (the last published version does not occur in the URL though.) 

![image](https://user-images.githubusercontent.com/23121882/54884653-ee6f7c00-4e73-11e9-83af-4e240a6aac83.png)

This means that if you see a plot in the examples, it is almost impossible for the respective code not to run cleanly with the respective matplotlib version. (Things are different for interactive examples, which are not actually run though.)

In this case however we can deduce that the version that produces the error, is either not matplotlib 3.0.3 or that the install is broken. 

You find your matplotlib version via

```
import matplotlib
print(matplotlib.__version__)
```

Categorical plotting has been introduced in matplotlib 2.1; the example is hence expected to fail for any previous version. You would also see that this example does not even exist in the documentation for versions prior to 2.1.

**Comment by hudingyin** [comment]
> Please recheck the matplotlib version you are using. I cannot reproduce the above bug with v3.0.3. Also the traceback line numbers do not match with the code of v3.0.3.

Thanks for you.
My matplotlib version is 1.5.1.

**Comment by jklymak** [comment]
Thanks for getting back to us.
