### ISSUE TITLE
How to replace round with only barbs when ploting barbs for low wind speed area ?

### ISSUE THREAD

**Issue by viczhn** [matplotlib/matplotlib#13746]
Matplotlib's barbs will plot rounds for the low wind speed area, and it looks a little bit ugly to me. So is there a way to replace those rounds with barbs or something else ? Thanks! 

![$HI$NNPK A76A`OFYU`VUU2](https://user-images.githubusercontent.com/9367497/54867053-fc12fc00-4db6-11e9-8823-2db378f9fe47.png)

**Comment by kasanitej** [comment]
Those rounds are not calm? if not calm, provide the data & code to produce your results.

**Comment by dstansby** [comment]
Can you provide a short, self contained example that illustrates the problem? That way it's much easier to see what's going on.

**Comment by dopplershift** [comment]
Code to reproduce the problem would be helpful. Something weird seems to be going on, because those dots are supposed to be circles that are appropriately sized with the barbs (as is standard). See the center of this image:
![barb_demo](https://matplotlib.org/_images/sphx_glr_barb_demo_001.png)

**Comment by timhoffm** [comment]
Closing due to lack of feedback. Please reopen and provide a self contained example if this is still of interest.
