### ISSUE TITLE
saved PDF size is incorrect

### ISSUE THREAD

**Issue by okdzhimiev** [matplotlib/matplotlib#13763]
### Bug report

**Bug summary**

When saving a PDF file with:
`plt.rcParams["figure.figsize"] = [60,120]`
or
`fig.set_size_inches(60, 120)`

The result PDF size is: 59.7x119.4 in

**Code for reproduction**

[escher_pattern.py](https://git.elphel.com/Elphel/imagej-elphel/blob/master/src/main/resources/escher_pattern.py)

**Matplotlib version**

  * Operating system: Kubuntu 18.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.7
  * Jupyter version (if applicable): N/A
  * Other libraries: tkinter.TkVersion = 8.6

Matplotlib was installed using pip:
`pip3 install matplotlib --upgrade`

Thanks

**Comment by ImportanceOfBeingErnest** [comment]
In the linked code you use `bbox_inches="tight"` when saving. This will (and is meant to) crop the figure. 
Do you experience any problems when removing this option?

**Comment by okdzhimiev** [comment]
It works correctly. Now I just need figure out how to remove the border.
Thanks for the quick response.

**Comment by tacaswell** [comment]
I am going to close this as Matplotlib is behaving as expected for the linked code.

@okdzhimiev Have a look at the `tight_layout` and `constrained_layout` kwargs on `plt.subplots()`

**Comment by okdzhimiev** [comment]
Thanks. 
Found the solution - just added `pad=0` to `fig.tight_layout()`:
`fig.tight_layout(pad=0)`
