### ISSUE TITLE
Error running the animation/random_walk.py example

### ISSUE THREAD

**Issue by daguito81** [matplotlib/matplotlib#13778]
### Bug report

**Bug summary**

When running the random_walk.py example, python throws an error

**Code for reproduction**
This appears by running random_walk.py as is

**Actual outcome**

AttributeError stating that the generated ax has no plot attribute
```
Traceback (most recent call last):
  File "random_walk.py", line 52, in <module>
    lines = [ax.plot(dat[0, 0:1], dat[1, 0:1], dat[2, 0:1])[0] for dat in data]
  File "random_walk.py", line 52, in <listcomp>
    lines = [ax.plot(dat[0, 0:1], dat[1, 0:1], dat[2, 0:1])[0] for dat in data]
AttributeError: 'NoneType' object has no attribute 'plot'
```

**Matplotlib version**

  * Operating system: Windows 10 Pro Version 1803
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

**Comment by daguito81** [comment]
I posted the bug for documentation purposes but I'd like to take a crack at it as I think I solved it already

**Comment by anntzer** [comment]
The example must be run with matplotlib master, not 2.2.3 (with 2.2.3, you need to run an older version of the example).

**Comment by daguito81** [comment]
Thank you for your comment. I tested it with master and indeed it works. Sorry about that

**Comment by anntzer** [comment]
No worries.  Good to close?

**Comment by daguito81** [comment]
I thought I closed it myself already.

Regards,
Dago
