### ISSUE TITLE
Imshow gives values out of the extent

### ISSUE THREAD

**Issue by Max16hr** [matplotlib/matplotlib#13785]
**Bug summary**

With imshow() you get an image with values outside the extent being set.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

axes = plt.subplot()
axes.set_aspect(1)
axes.format_coord = "x={:1.2f}, y={:1.2f}".format

pltRange = range(-1, 12)
axes.set_xlim(min(pltRange), max(pltRange))
axes.set_ylim(min(pltRange), max(pltRange))
axes.set_xticks(pltRange)
axes.set_yticks(pltRange)
plt.grid(True)

array = np.random.random((10, 10))
image = axes.imshow(array, extent=[0, 10, 0, 10], origin='lower')
image.format_cursor_data = " |  Value: {:8f}".format

plt.show()

```

**Actual outcome**

![image](https://user-images.githubusercontent.com/47167280/55176475-7b227e80-5181-11e9-9c1a-7c7f77e0eb6c.png)

On the bottom right you can see the coordinates of the mouse cursor and the value of the array you are moving over. This works fine on the coloured tiles. But I also expect to get no value when I move my mouse over the white plates.

On the top and on the right side, this does happen. But not on the bottom and on the left. If you move your mouse to the position, lets say (-0.5, 2.5), you will still get a value. That makes no sense to me.

**Expected outcome**

No values on all white tiles.

**Matplotlib version**

  * Operating system: Windows 10 Home, 1809
  * Matplotlib version: 3.0.3
  * Matplotlib backend: TkAgg
  * Python version: 3.7.2
  * Other libraries: Numpy 2.16.2

**Comment by ImportanceOfBeingErnest** [comment]
This seems to be fixed in current master. It bisects to #10356, which would (unintentionally) have fixed this.

**Comment by dstansby** [comment]
Since this looks fixed in master I'm going to close this, feel free to comment or re-open if it's still an issue when version 3.1 comes out.
