### ISSUE TITLE
Extremely slow drawing of text with Agg backend

### ISSUE THREAD

**Issue by guidocioni** [matplotlib/matplotlib#13784]
### Bug report

**Bug summary**
Creating a figure using `pyplot.annotate` or `pyplot.text` with the `Agg` backend is extremely slow and hangs when adding additional path effects.

**Code for reproduction**
Assume `var` is an array of floats (length about 200) and `ax` is an axes instance. To put labels on a background I have to do this (`lons` and `lats` are arrays with the same dimension of `var` containing the desired position of the label)

```python
ax.annotate( ('%d'%txt), (lons[i], lats[i]), color = 'white', weight='bold', fontsize=8,
                     path_effects=[patheffects.withStroke(linewidth=1, foreground="black")])
```

**Actual outcome**
 
Annotating about 200 labels over an image takes the following amount of time:

- `cairo` backend, text without `path_effects` -> 2 seconds to produce the PNG image
- `cairo` backend, text with  `path_effects`  -> 2.5 seconds 
- `Agg` backend, text without  `path_effects`  -> 1 minute 21 seconds 
- `Agg` backend, text with  `path_effects`  -> "infinite" amount of time, script hangs

Note that I have to use either `cairo` or `Agg` since this is running on a headless server and I need to produce PNG pictures without having a remote display set. I always used `Agg` in the past with this script and never had problems. At some point I must have updated to a version of matplotlib which introduced this bug but never realized until now. Note that with other scripts I can successfully use the `Agg` backend. 
 
**Expected outcome**

Runtime should be comparable in `Agg` and `cairo` backends. Script should not hang using `path_effects`. This was not the observed behavior with previous versions of matplotlib. The problem with `cairo` backend is that one has to install it beforehand on the server and the quality of produced graphic is slightly worse than `agg`.

**Matplotlib version**

  * Operating system: macOS Mojave
  * Matplotlib version:  3.0.2, tried also on some 2.* versions
  * Matplotlib backend: either `agg` or `cairo`, as specified in the description.
  * Python version: 3.7.1

Matplotlib was installed with `conda` from the `conda-forge` channel.

**Comment by jklymak** [comment]
Can you make this example minimal and self contained?

**Comment by guidocioni** [comment]
Ok so I was able to narrow down this problem to my workstation... I've tried on another machine that I have with similar setup and I don't get this problem. So it must be related to my configuration. That's pretty weird since on both machines I installed matplotlib/python using conda and the version of python/matplotlib is the same.

Do you have any suggestion on how to narrow down the problem with the matplotlib/backend installation?

Otherwise since it can only be reproduced on my system I think you can close the issue for now as it shouldn't be a general bug of matplotlib.

**Comment by guidocioni** [comment]
So I figured it out. Somehow I had an old outdated .matplotlibrc in my home folder and this was forcing matplotlib to use another backend, even though I specified `Agg`. I deleted the file and now everything is working again. I think you can close the issue. If anyone has the same problem I'd suggest you to do a clean install and remove the old .matplotlibrc.

**Comment by WeatherGod** [comment]
Which backend was it forcing matplotlib to?

**Comment by guidocioni** [comment]
Tk5Agg. I think this was one of my previous attempts to fix the window not showing up on MacOS but then I forgot to remove it with the new updates...
