### ISSUE TITLE
BUG: incorrect error bar colors when NaN values are present

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#13799]
### Bug report

**Bug summary**

When using variable colors for error bars, the colors are incorrect/shifted if NaN values are present.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x = [1, np.nan, 3, 4, 5]
colors = ['red', 'green', 'blue', 'purple', 'orange']

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.scatter(x, x, c=colors, s=100)
ax.errorbar(x, x, xerr=0.2, yerr=0.2, ecolor=colors, fmt='none')
fig.savefig('errorbar_colors.png')
```

**Actual outcome**

![errorbar_colors](https://user-images.githubusercontent.com/314716/55234603-6dbdd080-5223-11e9-8fe1-532fd20a1127.png)

**Expected outcome**

![errorbar_colors](https://user-images.githubusercontent.com/314716/55234635-7ca48300-5223-11e9-8e10-eb95b03416b4.png)

**Matplotlib version**

  * Operating system: MacOS X 10.14.2
  * Matplotlib version: 3.0.3 (from pip)
  * Matplotlib backend: Agg
  * Python version: 3.7.1

**Comment by timhoffm** [comment]
Closed by #17624.
