### ISSUE TITLE
Move 'modules' link to LH side of website?

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#13796]
Currently the link to "modules" is on the far RH side of the website:
<img width="1202" alt="Screenshot 2019-03-29 at 11 23 02" src="https://user-images.githubusercontent.com/6197628/55229498-16186880-5215-11e9-83b0-83c5e3556bf9.png">

Often I find myself clicking "API", expecting to have a list of modules, and it takes me a while to figure out that what I actually want is the modules link, but it's a bit hidden on the RH side. Would there be any objections to moving it next to the "API" link on the LH side?

**Comment by anntzer** [comment]
Agreed the current layout is not optimal.
We could also merge https://matplotlib.org/api/api_overview.html and https://matplotlib.org/api/api_overview.html (the latter going at the bottom of the former).

**Comment by ImportanceOfBeingErnest** [comment]
Definitely a useful suggestion. I usually click "docs" and then search for "modules" in that list. That is inconvenient as well.

(@anntzer The two links above are the same?)

Moreover, the "FAQ" could also get its own entry on the top level?

**Comment by anntzer** [comment]
sorry, edited incorrect link

**Comment by dstansby** [comment]
Good idea, I would be +lots for just putting the content of "modules" at the bottom of "API".

**Comment by timhoffm** [comment]
I see this as part of the greater problem that the documentation is not very well structured. Related:

- Rework main documentation page #13382
- Also beyond the main page, the structure needs improvement. Maybe via Google Season of Docs? What's the status on that?

You can do small improvements as you go, e.g. moving the link. But I think we need a concept of the doc structure at some point to clean things really up. For example I don't think merging api/api_overview and api/index will do the trick. We need something else there.

**Comment by dstansby** [comment]
I think this is redundant now - the current `devdocs` doesn't have this issue.
