### ISSUE TITLE
'tuple' object is not callable, plt.xticks()

### ISSUE THREAD

**Issue by wang-jinghui** [matplotlib/matplotlib#13803]
### 'tuple' object is not callable

**Bug summary**
        I have written this before, and there is no such problem.
      data is a  datafrme object, ind  np.array, labels  list。
```python
series = data.app_class_1.value_counts()
ind = np.arange(len(series))
labels = series.index.tolist()
plt.figure(figsize=(13, 5))
plt.bar(ind, series)
plt.xticks(ind, labels, fontproperties=msyh)
```
![type_error](https://user-images.githubusercontent.com/22521393/55273470-f5c8d680-5306-11e9-9bd7-408845e22a37.png)

**Previous normal output**
![norm_output](https://user-images.githubusercontent.com/22521393/55273525-aafb8e80-5307-11e9-871b-09be0d7f4eba.png)

**Matplotlib version**

  * Operating system:   ubuntu 16.04
  * Matplotlib version:   3.0.2
  * Matplotlib backend : module://ipykernel.pylab.backend_inline
  * Python version:  3.7.2
  * Jupyter version : 1.0.0
  * Other libraries:

**Comment by QuLogic** [comment]
I'm fairly certain this is because you have at some point written `plt.xticks=(ind, labels)` by accident.

**Comment by wang-jinghui** [comment]
> I'm fairly certain this is because you have at some point written `plt.xticks=(ind, labels)` by accident.

I'm pretty sure I didn't write that way. I haven't changed anything today, but it works.
![cnn](https://user-images.githubusercontent.com/22521393/55283695-720cf980-539b-11e9-8a0e-f8bc365719ec.png)

Look at this, `plt.xticks=(ind, labels)`, No Type Error, 'tuple' object is not callable.
![cnn](https://user-images.githubusercontent.com/22521393/55283777-cc5a8a00-539c-11e9-8e95-acc3fa1dc161.png)

**Comment by ImportanceOfBeingErnest** [comment]
Does this mean the issue has solved itself by restarting the kernel and this issue can be closed?

**Comment by jklymak** [comment]
Please always give self-contained bug reports if at all possible.   That will either cause the problem to be apparent, or make it a lot easier for us to debug.  Thanks!

**Comment by wang-jinghui** [comment]
> 这是否意味着问题通过重新启动内核解决了，这个问题可以关闭？

I think so.

> 如果可能的话，请始终提供自包含的错误报告。这将导致问题显而易见，或者使我们更容易调试。谢谢！

only these

**Comment by wang-jinghui** [comment]
> 如果可能的话，请始终提供自包含的错误报告。这将导致问题显而易见，或者使我们更容易调试。谢谢！

only these， type error, tuple object is not callable, but restarting the kernal, it works.

**Comment by tacaswell** [comment]
@wang-jinghui Setting `plt.xticks = (...)` will work, but that replaces the `xticks` function on the `pyplot` module with a tuple so any subsequent calls to `plt.xticks(...)` will fail with the exception you got.

Restarting the kernel fixes the problem because it re-loads the pyplot module and `xticks` is a function again.   Look it `type(plt.xticks)` before and after resetting it.

**Comment by wang-jinghui** [comment]
@tacaswell  Thank you for your answer, you solved my confusion.

**Comment by wang-jinghui** [comment]
@QuLogic Thank you  for your answer.

**Comment by SyedFaizanAlii** [comment]
this error can easily handle by restarting the kernel in VS code Studio

**Comment by timhoffm** [comment]
For reference [PEP-726](https://peps.python.org/pep-0726/) was a rejected attempt to introduce a module-level `__setattr__`  that could have been used to prevent overwriting module functions. The PEP lists changing the module type as a possible workaround. But I don't think we want to go this way. So there is currently no way to prevent users from accidentally using `plt.xticks = ...`.
