### ISSUE TITLE
mathtext.fontset is not respected by context managers

### ISSUE THREAD

**Issue by moble** [matplotlib/matplotlib#13812]
### Bug report

**Bug summary**

Applying the rc setting `mathtext.fontset: stix` via a dictionary or rc file in `rc_context`, or as a style with `plt.style.context`, does not seem to work.  The math fonts are not stix-like; they look like the default dejavusans.  Applying this setting without a context manager (either directly or through `matplotlibrc`) *does* work as expected.

I've seen some comments in these issues that this sort of thing crops up because the font is chosen when the axes are first created.  But I don't see how to create the axes any later — in particular, after the context statement.  I've tried more explicit methods like asking for subplots within the context manager, but nothing changes.  Are the axes created at the beginning of the `rc_context` call?

**Code for reproduction**

```python
import matplotlib as mpl
import matplotlib.pyplot as plt

with mpl.rc_context(rc={'mathtext.fontset': 'stix'}):
    plt.plot([0, 1], [2, 3])
    plt.xlabel(r'$x$')  # Note the dollar signs
    plt.ylabel(r'$y$')

plt.savefig('context_fail.png', dpi=200)
```

**Actual outcome**

![context_fail](https://user-images.githubusercontent.com/1470769/55284254-b0c19600-5340-11e9-8f06-1f730c29fee4.png)

Note the fonts that the labels x and y are in, which look like dejavusans.

**Expected outcome**

I expect this to work just like if I replaced the context manager with
```python
mpl.rcParams['mathtext.fontset'] = 'stix'
```
That gives this result:

![rc_win](https://user-images.githubusercontent.com/1470769/55284304-f2067580-5341-11e9-8260-cf17faa80ff2.png)

Note the fonts that the labels x and y are in, which look like stix.

**Matplotlib version**
  * Operating system: macOS 10.13.6 (17G5019)
  * Matplotlib version: 3.0.2
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 3.6

Installed from conda-forge.

**Comment by QuLogic** [comment]
> I've seen some comments in these issues that this sort of thing crops up because the font is chosen when the axes are first created.

It's the reverse of this; the fonts are chosen when the figure is drawn. If you move the `savefig` in the context, it works.
