### ISSUE TITLE
PDF Export: Markeredgecolor transparency defined by markerfacecolor

### ISSUE THREAD

**Issue by JoschD** [matplotlib/matplotlib#13847]
### Bug report

**Bug summary**
The alpha value of the markerfacecolor is also used for markeredgecolor, 
after exporting to `.pdf` and using **PDF XChange Editor** and **LibreOffice Draw** for viewing (see below).

**Why is that a big problem?**
When using `fillstyle='none'` markers disappear completely.

**Work as expected:**
 - Evince
 - Okular
 - Zathura
 - Adobe Acrobat DC
 - Chrome
 - Edge
 - Firefox
 - Master PDF Editor (v4)
 - Xournal
 - Inkscape

**Workaround:**
Open in inkscape and just save it.

**Related?**
[alpha value lost on marker edges #4580](https://github.com/matplotlib/matplotlib/issues/4580)
[markerfacecolor/markeredgecolor alpha issue #1504](https://github.com/matplotlib/matplotlib/issues/1504)
[No markers in EPS if fillstyle='none' #10921 ](https://github.com/matplotlib/matplotlib/issues/10921/) _originally posted there_

**Code for reproduction**

```python
from matplotlib.colors import to_rgba
from matplotlib import pyplot as plt
import numpy as np

x = np.arange(0, 100, 10)
fig, ax = plt.subplots(1, 1)
ax.plot(x, x**2, marker="o", fillstyle='full', 
                 markerfacecolor=to_rgba("r", .4), markeredgecolor="k")
fig.savefig("testplot.pdf")
```

What it should look like (e.g. in evince):
![image](https://user-images.githubusercontent.com/26184899/55421704-24021c80-557a-11e9-8d90-d4e694b6a529.png)

What it looks like in PDF XChange Editor and LibreOffice Draw:
![image](https://user-images.githubusercontent.com/26184899/55421722-2d8b8480-557a-11e9-9964-f609a293ca03.png)

**Matplotlib version**
  * Operating system: Ubuntu 18.04 (created and viewed), Windows 7 (viewed)
  * Matplotlib version: 
       * From PyPI:
          - 2.2.2 
          - 3.0.0
          - 3.0.3
      * From source:
           - [3.1.x](https://github.com/matplotlib/matplotlib/commit/985116f0fef5768c002ece94460dd911232f20c2)
"full-revisionid": "985116f0fef5768c002ece94460dd911232f20c2",
 "version": "3.0.2+1951.g985116f0f"

          - [Master](https://github.com/matplotlib/matplotlib/commit/8714c32afd838e04b271ce07f7fde3695768ed99)
 "full-revisionid": "8714c32afd838e04b271ce07f7fde3695768ed99",
 "version": "3.0.2+2102.g8714c32af"

  * Matplotlib backend: Qt5Agg
  * Python version: 2.7, 3.7.2

**Comment by jklymak** [comment]
This works fine for Mac Preview and Acrobat Reader as well.  

So this is working for 12 other PDF viewers including the main standard ones, and *not* working for two obscure ones?  I'm not at all convinced this is a Matplotlib bug, unless someone can point to the error matplotlib is making....

**Comment by anntzer** [comment]
Please open bug reports on the bugtrackers for the viewers that display this incorrectly.  I think at this point these viewers' implementers need to convince us that their implementation is correct for us to take action.

**Comment by dixr** [comment]
Just noticed this also happens on the Adobe Acrobat app on android (version 23.1.1.25723), a PDF reader that many people are using I guess.

So maybe there is indeed a problem in how matplotlib exports the PDF? The fact that opening and saving it in inkscape solves the problem would also point to matplotlib?

**Comment by tacaswell** [comment]
Even so, I think we still need evidence that we are generating pdf files that are out of spec rather than this being a bug in viewers.

Given the complexity of the pdf spec there are multiple inputs that will generate the same visual output, that inkscape does not round trip is not that surprising.

If someone wants to dig into this sorting out what the difference between what we are outputting and the inkscape version would be interesting (if they are at all comparable).
