### ISSUE TITLE
matplotlib.sphinxext.plot_directive generates incorrect links when using dirhtml builder

### ISSUE THREAD

**Issue by glenfletcher** [matplotlib/matplotlib#13858]
When using the `dirhtml` builder in sphinx with the `.. plot::` directive, the generated links are relative to the source file tree not the output, i.e. the source file name become a directory containing index.html, however the relative path generated is based on the location of the source file
https://github.com/matplotlib/matplotlib/blob/ae73a46cc46045d7edac52ef3e8876515802f10d/lib/matplotlib/sphinxext/plot_directive.py#L740

I fixed this locally using the the following hack, however I don't think this is the appropriate solution there should be some way to make the directive use the output path not the input path, which would remove the need for a hack solution. Hence I'm posting this as a issue rather than a patch.

```python
    if setup.app.builder.name == 'dirhtml':
        subdir = os.path.basename(os.path.splitext(rst_file)[0])
        dest_dir_link = os.path.join(relpath(setup.confdir, os.path.join(rst_dir, subdir)),
                                     source_rel_dir).replace(os.path.sep, '/')
    else:
        dest_dir_link = os.path.join(relpath(setup.confdir, rst_dir),
                                     source_rel_dir).replace(os.path.sep, '/')
```

**Comment by anntzer** [comment]
Related to #12456, perhaps(?).

**Comment by MikhailRyazanov** [comment]
PR #24205 seems to solve this issue in a more robust way. If anybody is still interested, please test it.

**Comment by QuLogic** [comment]
I confirmed that this works now by copying the test `tinypages/some_plots.rst` into a subdirectory and building before and after the above PR. The download links are now working, and not using broken relative paths.
