### ISSUE TITLE
Zero-width figure crashes libpng

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#13857]
### Bug report

**Bug summary**

Zero-width figure crashes libpng.
This happens when using ``%matplotlib inline`` or saving to png.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.subplots(1, 1, figsize=(3, 0))
plt.savefig("test.png")
```

**Actual outcome**
```
RuntimeError: libpng signaled error
```

**Matplotlib version**

  * Operating system: ubuntu / conda
  * Matplotlib version: 3.0.2, conda 3.0.2-py37h5429711_0 same at 3.0.3-py37h5429711_0
  * libpng 1.6.35-hbc83047_0, same with 1.6.36-hbc83047_

Apparently I broke "conda list" on my machine so getting all the versions seems a bit tricky.

**Comment by WeatherGod** [comment]
My vote is to raise BlackHoleSingularityError.

**Comment by WeatherGod** [comment]
In all seriousness, though, this should be easy enough to detect and raise
in the Figure class. I can't imagine how a figsize with a 0-length
dimension would ever be anything but an error.

**Comment by amueller** [comment]
yeah totally fine with an error. doing zero height works btw ?!
I guess the expected behavior that I didn't specify is "either create an empty figure or raise an informative error".
