### ISSUE TITLE
How to change the color of legend font?

### ISSUE THREAD

**Issue by boyob** [matplotlib/matplotlib#13864]
how to change the color of the circled black font?
![1](https://user-images.githubusercontent.com/24429461/55477000-9e01d680-564a-11e9-9b18-952be9ddf256.png)

**Comment by pharshalp** [comment]
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(3, 2))
ax.hist([1, 2, 3], label='data1')
leg = ax.legend()
for leg_text in leg.get_texts():
    leg_text.set_color('red')
fig.savefig('temp.png')
```
![temp](https://user-images.githubusercontent.com/15175620/55483258-39b42800-55f4-11e9-8cbd-09c081fc8f72.png)

**Comment by WeatherGod** [comment]
This is a bug tracker, not a help forum. Please use gitter, stackoverflow, or the mailing list (all documented on matplotlib.org) for questions like these. I'll be closing this issue as it isn't a bug.
