### ISSUE TITLE
Vulnerability - lib/.../backends/web_backend/js/mpl.js

### ISSUE THREAD

**Issue by psherloc** [matplotlib/matplotlib#13899]
### Bug report

**Bug summary**

Ran 3.0.3 against SonarQube, resulting in a A3 - Sensitive Data Exposure class B

```python
mpl.get_websocket_type = function() {

    if (typeof(WebSocket) !== 'undefined') {

        return WebSocket;

    } else if (typeof(MozWebSocket) !== 'undefined') {

        return MozWebSocket;

    } else {

        alert('Your browser does not have WebSocket support. ' +

              'Please try Chrome, Safari or Firefox ≥ 6. ' +

              'Firefox 4 and 5 are also supported but you ' +

              'have to enable WebSockets in about:config.');
```

**Actual outcome**

```
# If applicable, paste the console output here
#
Remove this usage of alert(...).
MITRE, CWE-489 - Leftover Debug Code 
OWASP Top 10 2017 Category A3 - Sensitive Data Exposure
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: 

downloaded raw Zip file, unpacked source code package, ran SonrQube against the folder.

**Comment by QuLogic** [comment]
OK? What vulnerability do you think there is here?

**Comment by psherloc** [comment]
Hi..  Just referring to what SonarQube is reporting:
![image](https://user-images.githubusercontent.com/33331978/55678772-84aaa400-5942-11e9-8890-ab51124c0140.png)
![image](https://user-images.githubusercontent.com/33331978/55678778-a0ae4580-5942-11e9-8ce2-a983d0057cc1.png)

**Comment by QuLogic** [comment]
Yes, and? Please use some judgment in the future and don't just open bug reports because a scanner thinks there's a vulnerability.

It's clear from the contents of the message that this is intended and there is no leak of debug information.
