### ISSUE TITLE
Blurry app icon on macOS

### ISSUE THREAD

**Issue by janosh** [matplotlib/matplotlib#13891]
Matplotlib v3.0.3 (backend `TkAgg`)  installed with `conda` has a blurry app icon on macOS (10.14.4).

![matplotlib-icon](https://user-images.githubusercontent.com/30958850/55647505-bc480d80-57d5-11e9-89b6-70a5c938bc1d.png)

**Comment by timhoffm** [comment]
With #13169 we'll be able to generate icons in all sizes. Note that Tk iconphoto supports multiple sizes.
