### ISSUE TITLE
pyplot line chart shows many data points that are not available in the source data

### ISSUE THREAD

**Issue by vino1493** [matplotlib/matplotlib#13905]
I tried creating a line chart using the data from a Dataframe. I load the Dataframe using a CSV file.
While using `df.plot(kind='line')`, I had issues with `xticks`. So, I'm using `matplotlib.pyplot` for getting the line chart.
While doing so I found something strange that the line chart has some data points which are not available in the source Dataframe.

adding the source file in **txt** format [test.txt](https://github.com/matplotlib/matplotlib/files/3054307/test.txt)

Using `df.plot`:

```
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame.from_csv(r'C:\Users\test.csv')
df.plot(x='GNRL_Scenario', kind='line')
plt.show()
```

![image](https://user-images.githubusercontent.com/40484319/55724787-c4988680-5a29-11e9-9e60-f66d5e5747ee.png)

Using `matplotlib.pyplot`:

```
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame.from_csv(r'C:\Users\test.csv')
fig = plt.figure(figsize=(7,6))
ax = fig.add_subplot(111)
ax.plot(df['GNRL_Scenario'],df['Value'])
plt.show()
```

![image](https://user-images.githubusercontent.com/40484319/55724730-a894e500-5a29-11e9-970b-b3d60488209c.png)

**Comment by tmdavison** [comment]
You have two values of `V2017AC` in your `GNRL_Scenario` column, hence the repeated value

**Comment by vino1493** [comment]
I spent so much time creating the post! But missed a small detail. I thought all the values were unique. Thank you very much @tmdavison

**Comment by Mohamed-Zeghlache** [comment]
@tmdavison but it's the same table (values) used in both solutions. why did he get different results
why didn't the line jump back in the first plot

**Comment by ImportanceOfBeingErnest** [comment]
@Mohamed-Zeghlache There is a fundamental difference on how matplotlib and pandas interprete strings. 



![image](https://user-images.githubusercontent.com/23121882/55732314-120df700-5a1c-11e9-9b7b-25a4fe571cfa.png)

```
import pandas as pd
import matplotlib.pyplot as plt

x = ["a", "a", "a", "a"]
y = [1,2,3,4]

fig, (ax, ax2) = plt.subplots(ncols=2)
ax.plot(x,y, marker="o")
pd.DataFrame({"x" : x, "y" : y}).plot(x="x", y="y", marker="o", ax=ax2)

ax.set_title("matplotlib `plot`")
ax2.set_title("pandas `plot`")
plt.show()
```

Besides, there is also an old bug (https://github.com/pandas-dev/pandas/issues/7612 and as a consequence, https://github.com/pandas-dev/pandas/issues/22334) in pandas, that makes plotting of strings unpredictable.

**Comment by Mohamed-Zeghlache** [comment]
thanks @ImportanceOfBeingErnest , i really appreciate the effort.
