### ISSUE TITLE
Error: color kwarg must have one color per dataset

### ISSUE THREAD

**Issue by Mattsda** [matplotlib/matplotlib#13906]
### Bug report

**Bug summary**

I'm unable to plot histograms due to the fact that the color kwarg must have one color per dataset? I'm not sure what this means. 

**Code for reproduction**

![PythonError2](https://user-images.githubusercontent.com/44985594/55745163-99e80700-5a04-11e9-8f21-92b4acd87b97.PNG)

**Actual outcome**

![PythonError](https://user-images.githubusercontent.com/44985594/55745076-6c02c280-5a04-11e9-925a-f89e52768712.PNG)

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
Please state the matplotlib version you are using. Also, please try to provide a fully self-contained example, so that we can debug the error.

**Comment by QuLogic** [comment]
Closing for lack of response. It is impossible to explain what may or may not be wrong without any idea of what data is being used. Please re-open if further information is provided.
