### ISSUE TITLE
matplotlib config font in matplotlibrc doesn't work

### ISSUE THREAD

**Issue by eromoe** [matplotlib/matplotlib#13904]
### Bug report

Because matplotlib can't plot Chinese at default. 
I want to set matplotlib use `YaHei Consolas Hybrid` font permanently .

Directly write in code is working as I know:

    import matplotlib
    import matplotlib.pyplot as plt
    
    matplotlib.rcParams['font.family'] = 'YaHei Consolas Hybrid'
    
    plt.figure()
    plt.title("哈哈")
    plt.show()

title is correct ![image](https://user-images.githubusercontent.com/3938751/55697332-9304c880-59f3-11e9-81ee-06633591ad80.png)

I used to set font by :

1. Find matplotlib config path :` python -c 'import matplotlib; print(matplotlib.matplotlib_fname())'`

2. add font to that file:

        font.family : YaHei Consolas Hybrid
        font.serif : YaHei Consolas Hybrid
        font.sans-serif : YaHei Consolas Hybrid

    I also tried:

        font.family : "YaHei Consolas Hybrid"
        font.serif : "YaHei Consolas Hybrid"
        font.sans-serif : "YaHei Consolas Hybrid"

3. check by :

        import matplotlib.pyplot as plt   
        plt.figure()
        plt.title("哈哈")
        plt.show()

But it doesn't work , title show like this  ![image](https://user-images.githubusercontent.com/3938751/55697297-5df87600-59f3-11e9-9db6-975921db6c9d.png)

At least this worked in ubuntu as I remenber .

Check the fontlist `C:\Users\XXXX\.matplotlib\fontlist-v300.json`  , does find this font :

    {
      "fname": "C:\\WINDOWS\\Fonts\\YaHei Consolas Hybrid 1.12 For Powerline.ttf",
      "name": "YaHei Consolas Hybrid",
      "style": "normal",
      "variant": "normal",
      "weight": 400,
      "stretch": "normal",
      "size": "scalable",
      "__class__": "FontEntry"
    },

So I have completely no clue why it doesn't work.

**Matplotlib version**

  * Operating system: win 10 
  * Matplotlib version:  3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

install by pip .

**Comment by QuLogic** [comment]
> But it doesn't work .

Please define "doesn't work". What are you expecting and what happens?

**Comment by eromoe** [comment]
Title showed as  ![image](https://user-images.githubusercontent.com/3938751/55697306-6e105580-59f3-11e9-90f0-6b0d10e8e04b.png)

**Comment by eromoe** [comment]
I recall one thing, I didn't set the background . 
OHH, I find the evil . 

I tested code in ipython and I set plot style in  `~/.ipython/profile_default/startup/startup.ipy` by jupyter theme in some day :

```
from jupyterthemes import jtplot
jtplot.style()
```
