### ISSUE TITLE
Seaborn disables constrained_layout

### ISSUE THREAD

**Issue by jkrumbiegel** [matplotlib/matplotlib#13907]
I'm testing out the new constrained_layout and really like it so far. I'm using seaborn a lot for fast subplot grids, and I thought I could profit from the new layout manager. I tried to use seaborn functions to plot into a figure using constrained_layout, but a lot of them use tight_layout internally, which then disables constrained_layout. Over at seaborn, the opinion was that because constrained_layout is new and experimental, nothing will be changed to incorporate it (even though it would solve some of their problems I think). Is there no way to benefit from both?

The example I tried it with:

```python
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.DataFrame(
    dict(
        x=np.tile(np.linspace(0, 10, 100), 4),
        y=np.sin(np.tile(np.linspace(0, 4*np.pi, 100), 4)) * np.repeat(np.arange(1, 5), 100),
        group=np.repeat(np.arange(1, 5), 100),
        hue=np.tile(np.linspace(0, 4*np.pi, 100), 4)
    )
)

grid = sns.FacetGrid(df, col='group', hue='hue', col_wrap=2)
grid.fig.set_constrained_layout(True)
grid.map(plt.scatter, 'x', 'y')
```

this gives:

```python
anaconda3/lib/python3.6/site-packages/matplotlib/figure.py:2144: UserWarning: This figure was using constrained_layout==True, but that is incompatible with subplots_adjust and or tight_layout: setting constrained_layout==False. 
  warnings.warn("This figure was using constrained_layout==True, "
```

**Comment by oscargus** [comment]
This seems to have been solved at some stage until the current `main` which gives no warning and:
![image](https://user-images.githubusercontent.com/8114497/172009676-9f87de79-c2a7-484b-9f93-1b3f1d145034.png)

Feel feel to reopen if you still have this issue.
