### ISSUE TITLE
plt.bar() creates different results when repeated

### ISSUE THREAD

**Issue by tlkaufmann** [matplotlib/matplotlib#13909]
### Bug report

**Bug summary**

When plotting a bar graph of some data from `np.histogram` on several different axis the outcome always slightly differs from each other.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

data = np.random.uniform(0, 100, size = 100)
hist, bins = np.histogram(data, bins=100)

fig, ax = plt.subplots(ncols = 3)

for a in ax:
    a.bar(bins[:-1], hist)
```

**Actual outcome**
![pyplot_bar](https://user-images.githubusercontent.com/17513791/55800493-23b2d580-5ad4-11e9-8e41-8fe7b0feee69.png)

**Expected outcome**

The same barplot three times.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.1
  * Jupyter version (if applicable): IPython 7.2.0

Matplotlib installed via standard conda channel.

**Comment by MrMonk3y** [comment]
same issue

**Comment by jklymak** [comment]
Re-opening.  I think there should be the option to properly anti-alias here ala #13724.  However, this canvas-level anti-aliasing will have to happen at a lower level...

**Comment by MrMonk3y** [comment]
There should at least be one of those red warnings when the image is smaller than the resolution needed to plot the bars correclty.

**Comment by anntzer** [comment]
I guess this is basically the same issue as the one being discussed at https://github.com/matplotlib/matplotlib/issues/13236#issuecomment-494976772?
