### ISSUE TITLE
Time series plots for non-daily data behave strangely

### ISSUE THREAD

**Issue by docbiz** [matplotlib/matplotlib#13910]
I was playing with some synthetic data in [this zipped csv file](https://github.com/matplotlib/matplotlib/files/3060451/df_plot.csv.zip). It is time series data for four (toy) financial strategies A through D. The rows are records for each day, but weekends are excluded.

`matplotlib` seems to be struggling with this data, at least in some circumstances. (Forewarning: I am very new to `pandas` and `matplotlib`, so I'm sorry if the below is inelegant or mistaken.)

In Python:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_plot = pd.read_csv("df_plot.csv", index_col="date")

### pandas.DataFrame.pyplot: fast and correct (but mangled axes,
### not matplotlib proper, etc.)
plot = df_plot.plot()
fig = plot.get_figure()
fig.savefig("pandas.DataFrame.pyplot.png")

### matplotlib.pyplot.plot on the raw data: slow beyond belief
plt.figure(figsize=(10,6))
for strategy in ["A", "B", "C", "D"]:
    plt.plot(df_plot.index, df_plot[strategy], linestyle="-")
plt.legend()
plt.savefig("matplotlib.plot.raw.png")

### matplotlib.pyplot.plot with the raw data being padded with NAs to
### be pseudo-daily: fast, but it produces broken lines
daily_time = np.arange(np.datetime64(df_plot.index.min()),
                       np.datetime64(df_plot.index.max()),
                       np.timedelta64(1, 'D'))
df_tmp = pd.DataFrame(index=pd.Index(daily_time))
df_mpl = df_tmp.join(df_plot)

plt.figure(figsize=(10,6))
for strategy in ["A", "B", "C", "D"]:
    plt.plot(df_mpl.index, df_mpl[strategy], linestyle="-")
plt.legend()
plt.savefig("matplotlib.plot.adjoined_daily.png")
```

In R:

```R
library(tidyverse)

tbl <- read_csv("df_plot.csv")

### ggplot2: fast and correct... ;)
tbl %>%
  gather(key = 'strategy', values = -date) %>%
  group_by(strategy) %>%
  ggplot() +
    geom_line(aes(x = date, y = value, colour = strategy)) +
    ggsave("ggplot.png", width = 10, height = 6)
```

Do you know to resolve this issue? Am I missing something?

**Comment by jklymak** [comment]
Have you tried asking this on Stackoverflow?  This seems to be a usage question not a bug report.

**Comment by docbiz** [comment]
I've not tried asking this on StackOverflow. I'll clarify my point by simplifying the example.

[This zip](https://github.com/matplotlib/matplotlib/files/3060978/df_modified.csv.zip) contains a single time series. The data is daily, but it excludes weekends. The naïve plotting...
```Python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_modified = pd.read_csv("df_modified.csv", index_col="date")
plt.plot(df_modified.index, df_modified['value'], linestyle="-")
plt.savefig("matplotlib.plot.raw.png")
```
...is so slow to finish that it's pointless to let it complete. The exact same plotting computation with `df_modified` replaced by `df_daily`, where...
```Python
daily_time = np.arange(np.datetime64(df_modified.index.min()),
                       np.datetime64(df_modified.index.max()),
                       np.timedelta64(1, 'D'))
df_tmp = pd.DataFrame(index=pd.Index(daily_time))
df_daily = df_tmp.join(df_modified)
```
...is reasonably fast (though the line is broken).

That is to say: plotting a time series that has missing days is _multiple orders of magnitude slower_ than plotting a time series that has the exact same data, but is padded with NAs so that the index is no longer missing any days.

Do you think that this is a usage question? If so, could you clarify what you mean by that?

**Comment by tacaswell** [comment]
Is the datatype of your colum strings by any chance?

**Comment by docbiz** [comment]
No:
```Python
In [10]: df_modified.dtypes
Out[10]:
value    float64
dtype: object
```

**Comment by docbiz** [comment]
(I appreciate that 'value' is an unclear column name in that—sorry!)

**Comment by tacaswell** [comment]
How about the index?

Can you post the code to generate the synthetic data rather than a link to a datafile?

**Comment by docbiz** [comment]
🤦‍♂️ 

The date column wasn't being automatically parsed as a date column. Manually parsing it as such resolved the issue. Thanks, and sorry for wasting everyone's time.
