### ISSUE TITLE
Hello, I'm receiveing the following error on Anaconda Windows: ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running. Could you please help me to solve that? 

### ISSUE THREAD

**Issue by AlvaroVelloso** [matplotlib/matplotlib#13922]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by AlvaroVelloso** [comment]
import ludwig

file_train = r"C:\ludwig\train.csv"
file_test =  r"C:\ludwig\test.csv"
# train a model
#model_definition = {input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}
#Date, Number, Open, Close, Low, High, LowNext"

#ludwig train --data_csv path/to/file.csv --model_definition "{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}"

#model_definition = "{input_features: [{name: Low, type: numerical}], output_features: [{name: LowNext, type: numerical}]}"

#model_definition = "{input_features: [{name: Low, type: numerical, encoder: rnn}], output_features: [{name: LowNext, type: numerical}], training: {epochs: 50}}"
#model = ludwig.LudwigModel(model_definition)

model = ludwig.LudwigModel(
    model_definition={
        "input_features": [{"name": "low", "type": "numerical", "encoder": "rnn"}],
        "output_features": [{"name": "lownext", "type": "numerical"}],
        "training": {"epochs": 20}
    }
)


train_stats = model.train(file_train)

# or load a model
#model = LudwigModel.load(path)

# obtain predictions
predictions = model.predict(file_test)

model.close()

**Comment by ImportanceOfBeingErnest** [comment]
This doesn't look like a bug with matplotlib. For general help with matplotlib see https://matplotlib.org/#need-help

Presumably the problem comes from [this line](https://github.com/uber/ludwig/blob/76ba9708db4cfb4b2646daba8a53dfebb7fabdc7/ludwig/utils/visualization_utils.py#L28) in `ludwig`. If that should be the case, you would need to make sure to not run the code in an environment which has alread loaded a qt backend.

**Comment by nicolas-gervais** [comment]
What solved the problem for me was to **restart** my kernel, import the following **first**:

`import matplotlib
matplotlib.use('TKAgg')`

**Then**, 

`import matplotlib.pyplot as plt`
