### ISSUE TITLE
Colors plotted with 3D scatter are inconsistent when their values are really close

### ISSUE THREAD

**Issue by matthieuheitz** [matplotlib/matplotlib#13928]
### Bug report

**Bug summary**

Colors plotted with 3D scatter are inconsistent when the values are really close.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# matplotlib.use('Qt5Agg')  # save_png=False: bug in window,  save_png=True: bug in png, NO bug in window
# matplotlib.use('Qt4agg')  # Same as Qt5Agg
# matplotlib.use('TkAgg')   # save_png=False: NO bug in window,  save_png=True: bug in png, NO bug in window
# matplotlib.use('WebAgg')  # Same as Qt5Agg


# save_png = True
save_png = False

n = 4
dim = 3
t = np.linspace(0, 1, n)
X = np.meshgrid(*((t,)*dim))    # Means meshgrid(t,t) if dim=2 and meshgrid(t,t,t) if dim=3

np.random.seed(0)

s = 1e-16
# 3D :
# 2e-15 : no bug (gray, red or blue circles with contours of the same darkened color)
# 1e-15 : bug (gray circles with red or blue contours)
# 1e-16 : bug ((gray circles with blue contours of different shades)

# 2D:
# <= 1e-14 : gray, blue and red circles
# >= 1e-15 : gray circles

# -> This probably has to do with the fact that for 3D, I think 2 circles are drawn in order to have the darker border effect.
# When the bug is there, the second smaller circle drawn is gray instead of being the color of the first bigger circle.

A = (np.random.rand(*((n,)*dim))-0.5) * s

B = np.exp(A)   # All values are close to 1 but sometimes not 1, e.g. 0.9999999999999989

print(B)
print(B == 1)

if dim==2:
    # 2D
    fig = plt.figure(figsize=(9, 6))
    p = plt.scatter(*X, s=50, c=B, cmap='coolwarm') # * expands the list X into arguments X[0],X[1],X[2]
    plt.colorbar(p)
    plt.title('s=%g' % s)
    if save_png: plt.savefig("plot_%dd_s%0.2g.png"%(dim,s))
    plt.show()

if dim == 3:
    # 3D
    from mpl_toolkits.mplot3d import Axes3D
    fig = plt.figure(figsize=(9, 6))
    ax = fig.add_subplot(111, projection='3d')
    p = ax.scatter(*X, s=100, c=B.flatten(), cmap='coolwarm')
    plt.colorbar(p)
    plt.title('s=%g'%s)
    if save_png: plt.savefig("plot_%dd_s%0.2g.png"%(dim,s))
    plt.show()

# When save_png = False :
# In the 3D interactive plot, as soon as we change the view with the mouse, the bug disappears.
# All points get blue or red, and no longer gray in the middle.

# When save_png = True :
# In the 3D interactive plot, the bug is not there.
# BUT, in the png saved, the bug is there.

# -> This probably have to do with the fact that saving to png refreshes the plot in the same way as changing the view,
# so the bug disappears.
```

**Actual outcome**

We print`B` and `B == 1` and see that most values are not exactly 1 but very close to it.

```
>>> print(B)
[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]

>>> print(B == 1)
[[[ True False  True  True]
  [False False False False]
  [False False False  True]
  [ True False False False]]

 [[False False False False]
  [False False  True False]
  [False False False False]
  [ True False False False]]

 [[ True  True False False]
  [False False False False]
  [False False False False]
  [False False False False]]

 [[False False  True False]
  [False False False False]
  [False False  True False]
  [False False False False]]]
```

This is what the 3D plot looks like for different values of `s`:

![plot_3d_s2e-15](https://user-images.githubusercontent.com/2835332/55948929-ccd30a80-5c51-11e9-9361-9db50e59fa40.png)
![plot_3d_s1e-15](https://user-images.githubusercontent.com/2835332/55948927-cc3a7400-5c51-11e9-84f0-9109407e0a7f.png)
![plot_3d_s1e-16](https://user-images.githubusercontent.com/2835332/55948928-cc3a7400-5c51-11e9-8a7b-db30c71d3ea5.png)

For `2e-15`, it's the expected result but not if `s< 2e-15`.

**Expected outcome**

We should either have all points completely gray, like with the 2D scatter plot (see below), or blue and red points like for `s=2e-15`.

2D scatter plots for 2 values of `s`:
![plot_2d_s1e-14](https://user-images.githubusercontent.com/2835332/55949201-5c78b900-5c52-11e9-8a0c-5804f30d2597.png)
![plot_2d_s1e-15](https://user-images.githubusercontent.com/2835332/55949203-5d114f80-5c52-11e9-847c-cc0fbfe510d2.png)

Moreover, as mentionned in the code :

The behavior is quite dependent on the backend used.

For backend Qt5Agg:
- When save_png = False :
In the 3D interactive window, as soon as we change the view with the mouse, the bug disappears. All points get blue or red, and no longer gray in the middle.

- When save_png = True :
In the 3D interactive window, the bug is not there.
BUT, in the png saved, the bug is there.

-> This probably have to do with the fact that saving to png refreshes the plot in the same way as changing the view, so the bug disappears.

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg`
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries: 

I installed matplotlib with conda : 

```
>>> import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:43:46) 
[GCC 7.3.0] on linux
```

**Comment by ImportanceOfBeingErnest** [comment]
Something looks strange here indeed, though maybe this is expected with numbers at the edge of floating point precision?

In any case a workaround for now would be to set the color limits manually, 

    ax.scatter(..., depthshade=False, vmin=0.9999, vmax=1.0001)

**Comment by matthieuheitz** [comment]
Yes, the fact that numbers are at the edge of floating point precision is probably a cause of the problem, but the bug should be fixable since a slight camera move fixes it, and using another backend fixes it.
Thank you for the workaround, I don't really need one because this happened to me in a very rare case, but it might be useful for others.

**Comment by jklymak** [comment]
It’s really hard for us to fix every possible issue that can arise at the boundary of machine precision.

**Comment by matthieuheitz** [comment]
Yes, of course, I understand that :). I submitted the issue more to signal it and for later reference than to ask for it to be fixed. It's not urgent at all for me.

**Comment by WeatherGod** [comment]
I am still concerned about the differences in backends, though. I am
wondering if the qt backend isn't triggering the draws correctly (or
perhaps they are doing it correctly, but we aren't setting the stale flags
correctly and the other backends are inadvertantly doing draws twice?

**Comment by jklymak** [comment]
Its not just that different backends have different floating point operations?  I agree this is a problem if its happening for robust data values, but if they are all functionally zeros and just going through slightly different math during rendering....

**Comment by WeatherGod** [comment]
doubtful. We provide the backends with the colors. They don't do the
colormapping.

**Comment by jklymak** [comment]
... the colours are floating point four-tuples

**Comment by WeatherGod** [comment]
uhm, then that might be the bug? A colormap is specified, so wouldn't the
data passed to "c" be interpreted as data to get colormapped? If you wanted
them to be 4-tuples, then you should call `plot`. Also, watch out for the
depth-shading that occurs by default for scatter (but not for plot).

**Comment by ksunden** [comment]
The example given now only does gray dots as is suggested to be the "correct" vizualization, though I will also point out that numpy gives only exactly 1 as well, so that may be part of it, regardless, I'm going to close this as even with s=1e-15, I get only gray dots, and I do not see any "all blue", so can no longer reproduce the erroring behavior.
