### ISSUE TITLE
cant use plt at all!!

### ISSUE THREAD

**Issue by xwjBupt** [matplotlib/matplotlib#13927]
### Bug report

**Bug summary**
when i use plt.subplot or plt.show it raise an error:

/home/xwj/anaconda3/bin/python3.6: relocation error: /home/xwj/anaconda3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

**Code for reproduction**

```python
# Paste your code here
plt.subplot(121)
plt.imshow(img)
plt.subplot(122)
plt.imshow(den)
plt.show()
```

**Actual outcome**

/home/xwj/anaconda3/bin/python3.6: relocation error: /home/xwj/anaconda3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**
show my desire image? is there something wrong with my anaconda environment?i can use it yesterday ,somehow i can not today?

**Matplotlib version**

  * Operating system:ubuntu 14.04
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):Q5Agg
  * Python version:anaconda 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
This looks like an problem of your PyQt5 installation. I don't think it has anything to do with matplotlib.

**Comment by xwjBupt** [comment]
@timhoffm thanks for your reply,i tried reinstall matplotlib,and it works fine~
