### ISSUE TITLE
− with save fig in .pgf

### ISSUE THREAD

**Issue by 10Avril** [matplotlib/matplotlib#13921]
### Bug report

**Bug summary**

When I use the command plt.savefig in order to create a pgf file (to include it in a LaTeX document), the symbol for the negative numbers writtent in the file is − (U+2212), while LaTeX waits this symbol - (U+002D)

**Code for reproduction**
`fig.savefig("file.pgf", bbox_inches='tight')`

**Matplotlib version**
  * Operating system : Windows 10
  * Matplotlib version : 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`) : TkAgg
  * Python version : 3.7.0

**Comment by jklymak** [comment]
Can you provide more code to reproduce this?

**Comment by 10Avril** [comment]
For example :

```import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = 2*x + 1

fig = plt.figure()
plt.plot(x,y)
plt.show()
fig.savefig("figure.pgf", bbox_inches='tight')
```

In the produced pgf file, for example on line 83 :
`\pgftext[x=0.715781in,y=0.234413in,,top]{\color{textcolor}\sffamily\fontsize{10.000000}{12.000000}\selectfont **−**10.0}%`
I notice that the problem of the character **−** occurs only in the lines that displays digits on the figure.

**Comment by anntzer** [comment]
This comes from https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/ticker.py#L567 (the axes.unicode_minus rcparam defaults to True).  You can set it to False, but I think the more robust solution is actually to make latex able to handle the unicode minus, which can be done by adding
```tex
\usepackage[utf8]{inputenc}
\DeclareUnicodeCharacter{2212}{-}
```
to the tex preamble.

**Comment by 10Avril** [comment]
It works now !
Thank you !
