### ISSUE TITLE
axes.errorbar raises ValueError when using cycler for fillstyle

### ISSUE THREAD

**Issue by raymondEhlers** [matplotlib/matplotlib#13934]
### Bug report

**Bug summary**

`ax.errorbar` raises a `ValueError` when `yerr` is specified and a cycler for `fillstyle` is specified. It works as expected if `yerr` is not specified or if `fillstyle` is passed explicitly instead of using the cycler. From what I understand, I think this should be possible.

**Code for reproduction**

```python
from cycler import cycler
import matplotlib.pyplot as plt

fillstyle_cycler = cycler("fillstyle", ["none", "full"])
fig, ax = plt.subplots()
ax.set_prop_cycle(fillstyle_cycler)
# Will work if `yerr` is not specified.
ax.errorbar([1,2,3], [4,5,6], yerr = [1,1,1], marker = "o")
```

**Actual outcome**

```
Traceback (most recent call last):
  File "exploration_scripts/test_errorbar_cycler.py", line 15, in <module>
    ax.errorbar([1,2,3], [4,5,6], yerr = [1,1,1])
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3262, in errorbar
    barcols.append(self.vlines(xo, lo, uo, **eb_lines_style))
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1143, in vlines
    lines.update(kwargs)
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/artist.py", line 916, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/artist.py", line 916, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/code/.jet_h/lib/python3.7/site-packages/matplotlib/artist.py", line 912, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property fillstyle
```

**Expected outcome**

Should work the same as when I specify

```python
ax.errorbar([1,2,3], [4,5,6], yerr = [1,1,1], marker = "o", fillstyle = "none")
```

**Matplotlib version**

  * Operating system: macOS 10.14.3
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: Python 3.7.2
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

I don't have a broad sense of the matplotlib code (so this may be off base), but perhaps it needs to be added to the list of properties [here](https://github.com/matplotlib/matplotlib/blob/dd18211687623c5fa57658990277440814d422f0/lib/matplotlib/axes/_axes.py#L3274)?

Thanks!

**Comment by WeatherGod** [comment]
yeah, this bug is actually the tip of a bigger iceberg. There is a deeper
problem where if you have, for example, an attribute like 'hatch' in your
default cycler, then calling plot after calling bar would break because
plot doesn't know hatch. The issue in this case is that a separate "plot"
call is made, if I remember correctly, which is grabbing things from the
default cycler when it shouldn't be.

**Comment by ksunden** [comment]
This no longer errors, but not going to take the time to bisect exactly when it stopped doing so
