### ISSUE TITLE
Plot data with large x axis in notebook

### ISSUE THREAD

**Issue by Juniorlimaivd** [matplotlib/matplotlib#13931]
Hello,

I have a series dataset  that has about 5000 instances, and I want do a plot like this:

![image](https://user-images.githubusercontent.com/9555750/55973246-871b3f80-5c5b-11e9-9cd8-58461af1397b.png)

However, if I try to plot with this code:

```python
%matplotlib inline
N = data['some_series'].count()
plt.plot(data['some_series'], linewidth=0.7, antialiased=True)
plt.plot(data['some_series2'], linewidth=0.7, antialiased=True)
plt.xticks(range(N),rotation=45) 
plt.grid()
```

I get this:

![image](https://user-images.githubusercontent.com/9555750/55973498-17598480-5c5c-11e9-8701-dd3b89296fd8.png)

If I try to run this code in %matplotlib notebook, it not show anything. 

I was able to get some decent plot if I decrease de dataset samples to around 500 and used the following code:

```python
%matplotlib notebook
import matplotlib 
import matplotlib.pyplot as plt

N = data['some_series'].count()
plt.plot(data['some_series'], linewidth=0.7, antialiased=True)
plt.plot(data['some_series2'], linewidth=0.7, antialiased=True)

plt.xticks(range(N),rotation=45) 
plt.grid()

plt.gca().margins(x=0)
plt.gcf().canvas.draw()
tl = plt.gca().get_xticklabels()
maxsize = max([t.get_window_extent().width for t in tl])
m = 0.05 # inch margin
s = maxsize/plt.gcf().dpi*N+2*m
margin = m/plt.gcf().get_size_inches()[0]

plt.gcf().subplots_adjust(left=margin, right=1.-margin)
plt.gcf().set_size_inches(s, plt.gcf().get_size_inches()[1])
plt.ylabel('Series1 and 2')
plt.subplots_adjust(left=0.01, right=1.0, top=0.9, bottom=0, hspace=0)
```

And I get an output like this:

![image](https://user-images.githubusercontent.com/9555750/55974007-20972100-5c5d-11e9-87c0-bea8685b7bd4.png)

Though, it not always works and it is very bad to interact with. I was wondering if matplotlib have a better way to plot large series in jupyter notebook and if not, it is in the plans to work around this functionailty?
 
Thank you in advance :)

**Comment by jklymak** [comment]
Its impossible to tell without your data, but you probably need to convert strings to floats.  https://stackoverflow.com/questions/47155569/difference-in-plotting-with-different-matplotlib-versions

**Comment by Juniorlimaivd** [comment]
The data is all numerical. Here are part of the data.describe()

![image](https://user-images.githubusercontent.com/9555750/55974621-74563a00-5c5e-11e9-987b-36bfffff66ca.png)

Here are some lines of my dataset:

https://pastebin.com/A3eDhh2K

**Comment by jklymak** [comment]
OK, sorry:  This is your problem: `plt.xticks(range(N),rotation=45) `  Why do you want 5000 ticks?

**Comment by jklymak** [comment]
OK, sorry:  This is your problem: `plt.xticks(range(N),rotation=45) `  Why do you want 5000 ticks?

**Comment by jklymak** [comment]
OK, sorry:  This is your problem: `plt.xticks(range(N),rotation=45) `  Why do you want 5000 ticks?

**Comment by Juniorlimaivd** [comment]
It's was for the data do not shrink as it happens in the first plot of the issue. 

For the second plot, I remove the ticks and it became much faster, but for the dataset with 5000 it still not plotting anything (the output of the cell is blank)

**Comment by Juniorlimaivd** [comment]
Also, I have this big blank space when I output using the second code without `plt.xticks(range(N),rotation=45)`, like this:

![image](https://user-images.githubusercontent.com/9555750/55975678-e039a200-5c60-11e9-9d1a-72f8c7aa9d2c.png)

**Comment by jklymak** [comment]
There is a maximum canvas size, and you are probably exceeding it by doing

`s = maxsize/plt.gcf().dpi*N+2*m`

When `N=5000`.   

I would just plot the time series, let ticking be auto, and then “zoom” using the zoom tool, and “pan” using the pan tool.  If you want to start zoomed in, you can set the `ax.set_xlim([0, 300])` and then use the pan tool.  

Anyway, this is not really a bug report.  We strongly encourage usage question go to stackoverflow where there is a large and enthusiastic group of folks willing to help.

**Comment by Juniorlimaivd** [comment]
This blank space also comes from it?

**Comment by jklymak** [comment]
No idea about the blank space.   Please make a [Short, Self Contained, Correct, Example](http://sscce.org) and if the problem is still there we can investigate. Please try to make the figure canvas a reasonable size.  If your canvas is 50000x500 pixels I'd not be surprised for odd things to happen.  There is really no need to do that.

**Comment by Juniorlimaivd** [comment]
Thank you for your help. I was able to get the desired behavior. With `ax.set_xlim([0, 300])` and `%matplotlib notebook`. Closing this issue.
