### ISSUE TITLE
`ax.get_xaxis().get_minorticklabels()` always returns list of empty strings

### ISSUE THREAD

**Issue by tdegeus** [matplotlib/matplotlib#13968]
### Bug report

**Bug summary**

`ax.get_xaxis().get_minorticklabels()` always returns list of empty strings.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.set_xscale('log')
ax.set_yscale('log')

ax.set_xlim([2e-2, 2e-1])
ax.set_ylim([2e+1, 2e+3])

ax.plot([0.02, 0.1, 0.2], [20, 1000, 2000])

ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
ax.get_xaxis().set_minor_formatter(matplotlib.ticker.ScalarFormatter())

fig.canvas.draw()

print([item.get_text() for item in ax.get_xaxis().get_minorticklabels()])

plt.show()
```

**Actual outcome**

```bash
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
```

![test](https://user-images.githubusercontent.com/7030445/56143792-76433480-5fa1-11e9-8f30-334e83ca2bba.png)

**Expected outcome**

```bash
['0.00', '0.00', '0.00', '0.01', '0.01', '0.01', '0.01', '0.01', '0.02', '0.03', '0.04', '0.05', '0.06', '0.07', '0.08', '0.09', '0.20', '0.30', '0.40', '0.50', '0.60', '0.70', '0.80', '0.90', '2.00', '3.00', '4.00', '5.00', '6.00', '7.00', '8.00', '9.00', '20.00', '30.00', '40.00', '50.00', '60.00', '70.00', '80.00', '90.00']
```

**Matplotlib version**

  * Operating system: macOS Mojave 10.14.4
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): `MacOSX`
  * Python version: 3.7.3

Python installed using homebrew, matplotlib using pip.

**Comment by ImportanceOfBeingErnest** [comment]
Do you get the same with `TkAgg` backend? I.e. `import matplotlib; matplotlib.use("TkAgg")`

**Comment by tdegeus** [comment]
I get a `NSException` when using `matplotlib.use("TkAgg")`?!?!

**Comment by ImportanceOfBeingErnest** [comment]
Ok, that's unfortunate, but is unrelated (you may not have tk inter installed). Would `"Qt5Agg"` work instead? I'm trying to find out if this is backend dependent, because I cannot reproduce (and don't have a Mac).

**Comment by tdegeus** [comment]
@ImportanceOfBeingErnest No such luck. I can say that a colleague on a mac can reproduce this problem (in his case installation through macports)

**Comment by jklymak** [comment]
That is very strange.  Indeed toggling `matplotlib.use('MacOSX')` and `matplotlib.use('Qt5Agg')` give the bug and the expected result respectively.  

If you do:

```python
print([item.get_text() for item in ax.get_xaxis().get_minorticklabels()])
plt.show()
print([item.get_text() for item in ax.get_xaxis().get_minorticklabels()])
```
 and close the window you get the right answer...
```
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['0.00', '0.00', '0.00', '0.01', '0.01', '0.01', '0.01', '0.01', '0.02', '0.03', '0.04', '0.05', '0.06', '0.07', '0.08', '0.09', '0.20', '0.30', '0.40', '0.50', '0.60', '0.70', '0.80', '0.90', '2.00', '3.00', '4.00', '5.00', '6.00', '7.00', '8.00', '9.00', '20.00', '30.00', '40.00', '50.00', '60.00', '70.00', '80.00', '90.00']
```

**Comment by tdegeus** [comment]
I can reproduce that after `plt.show` the output is what it should be.
