### ISSUE TITLE
[DOC] Undocumented behavior in streamplot

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#13974]
The docstring of `ax.streamplot` (“only”) states
```
x, y : 1d arrays
    an evenly spaced grid.
```
but looking at the actual code in the master branch (through the interface on GitHub website), it seems that a bit more of processing is involved (through the class `matplotlib.streamplot.Grid`) in order to also allow at least one special case of 2d-arrays for X and Y.

Expected behavior: such special casing being made explicite in the docstring.

**Comment by UnaiSan** [comment]
It seems that `Grid` objects only work with 2D arrays created as in `np.meshgrid(x,y, indexing="xy")`, and not as in `np.meshgrid(x,y, indexing="ij")`. Is there a specific reason for this? I, personally, have always preferred the second way to deal with 2D (or ND) arrays.

**Comment by jklymak** [comment]
Because that is how _all_ our input arrays are provided.
