### ISSUE TITLE
hexbin lightning plot

### ISSUE THREAD

**Issue by masabhathini** [matplotlib/matplotlib#13985]
HI,
I am trying to plot lightning data into hexbin plot.
I followed this web link.`https://basemaptutorial.readthedocs.io/en/latest/plotting_data.html`
But, I am not getting the plot with hexbin.
I am using python2.7; matplotlib2.0.2
my code as follows....
https://stackoverflow.com/questions/55708536/lat-lon-lightning-point-data-to-3km-x-3km-grid-count-spatial-plot

**Comment by masabhathini** [comment]
Now, I have upgraded to python3.7.3 and created a new conda envi for basemap, pandas.
I still have the same issue.
Plot does not have hexbins.

**Comment by ImportanceOfBeingErnest** [comment]
I suspect you forgot to transform the data to the coordinate system used by basemap. This would leave the hexbin plot somewhere outside the shown map.

**Comment by masabhathini** [comment]
Thanks @Elan Ernest
Your guess is correct. 
![image](https://user-images.githubusercontent.com/25902165/56427803-bfb1bd80-62da-11e9-969d-4c5187c87a34.png)

**Comment by masabhathini** [comment]
Hi @ImportanceOfBeingErnest ,

Can we save this data in a ascii format ?
I want to find the difference between previous hour - current hour lightning over a each hexbin.
i.e., I want to plot the difference in previous hour and current hour.

regards,
M. Sateesh
