### ISSUE TITLE
[FR] Setting PDF backend in matplotlibrc/style

### ISSUE THREAD

**Issue by ArchangeGabriel** [matplotlib/matplotlib#13994]
Now that #12674 landed, my [helper script](https://github.com/matplotlib/matplotlib/issues/4371#issuecomment-278934272) has considerably shrinked and is now reduced to:
```
import matplotlib as mpl
from matplotlib.backends.backend_pgf import FigureCanvasPgf
mpl.backend_bases.register_backend('pdf', FigureCanvasPgf)
import matplotlib.pyplot as plt
plt.style.use('pdf')
```

Could there be a way that using such a `pdf` style could do this backend registration? IIRC the biggest hurdle was that the backend must be registered before importing pyplot, but maybe things have (or could be) changed so that we could register the `pgf` backend for PDF output in matplotlibrc/style configuration files. The end goal for me is getting right of this helper and just have
```
import matplotlib.pyplot as plt
plt.style.use('pdf')
```
at the beginning of my notebooks. ;)

Thanks for consideration.

**Comment by anntzer** [comment]
I don't think(?) this needs to be called before pyplot is imported, and register_backend also takes the backend as a string, so just `mpl.backend_bases.register_backend("pdf", "matplotlib.backends.backend_pgf")` is likely enough... and then (assuming I'm correct) I'd say that's as good as `plt.style.use("pdf")` :-)

**Comment by ArchangeGabriel** [comment]
`plt.style.use("pdf")` would stay anyway, since this `pdf` style is where I define all my other settings related to PDF output (like latex/pgf preambles). Using your code, that would gain one line on my above case as such:
```
import matplotlib as mpl
mpl.backend_bases.register_backend("pdf", "matplotlib.backends.backend_pgf")
import matplotlib.pyplot as plt
plt.style.use("pdf")
```
So still a bit better, but actually like this is does not work:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-48d17890291d> in <module>
----> 1 mpl.backend_bases.register_backend('pdf', 'matplotlib.backends.backend_pgf')

AttributeError: module 'matplotlib' has no attribute 'backend_bases'
```
It works however if I move the pyplot import above the “backend” line. Not a big issue then, but thought I would mention it regardless.

So to rephrase it, what I would love is something like this in rcParams:
```
pdf.backend: "matplotlib.backends.backend_pgf"
```
and thus the now four lines code could then be reduced to the two lines at the end of my first post.

**Comment by anntzer** [comment]
That's just a matter of having matplotlib import backend_bases when the toplevel module is imported (or you can just do `import matplotlib.backend_bases; matplotlib.backend_bases.register_backend(...)`), which seems innocuous enough (and a change I would be fine with).
Strictly personally, I don't think every two-liner needs to have its equivalent in the matplotlibrc.

**Comment by tacaswell** [comment]
To comment a bit more, we have explicitly forbid `backend` as something that is controlled by the style module: https://github.com/matplotlib/matplotlib/blob/a1f9e0fc03b5c4ec7eadef9723ea48168d0e992f/lib/matplotlib/style/core.py#L41-L46 and I do not think we would change that.

**Comment by ArchangeGabriel** [comment]
Just for the record, while reviewing things I realized I’ve never commented here that #15536 mostly solved the issue.

Maybe the doc at https://matplotlib.org/stable/users/explain/text/pgf.html should be updated, replacing “The last method” by “The lasts methods” since this one also allows keeping interactive drawing. Opening a PR for this.
