### ISSUE TITLE
Tests files installed by default?

### ISSUE THREAD

**Issue by ArchangeGabriel** [matplotlib/matplotlib#13993]
I’ve just tried to compile from the 3.1.0rc1 tag for ArchLinux to see if everything runs OK, but I’ve noticed that the large bunch of tests files (`usr/lib/python3.7/site-packages/matplotlib/tests/`, `usr/lib/python3.7/site-packages/matplotlib/sphinxext/tests/` and `usr/lib/python3.7/site-packages/mpl_toolkits/tests/`) got installed while we don’t have any specific `setup.cfg`, so that tests should not be installed as is the default (and has been for the past years/releases).

I can provide more information if required, just tell me what (and eventually where to look for them).

**Comment by tacaswell** [comment]
Thanks for testing for looking at the rc!

It looks like this was intentially changed in   fc73b77cf840551930d15ee2ea10cadbabdc65a6 / https://github.com/matplotlib/matplotlib/pull/12317 .  We pinged @felixonmars for Arch but got no response.

**Comment by felixonmars** [comment]
Sorry for being inactive on that issue. Since Arch don't split packages I tend to provide mostly the default set. I didn't notice the tests installation change.

**Comment by ArchangeGabriel** [comment]
@tacaswell What I’m saying is that matplotlib install now defaults to `tests = True`, while still saying the opposite. It might be a side-effect of the linked changes, but likely not the intended behaviour. I’ll look at those files and see if I find something weird.

**Comment by ArchangeGabriel** [comment]
OK, indeed: https://github.com/matplotlib/matplotlib/pull/12317/files#diff-c28358ce9623af21f7b6e068f69085b7R662

I don’t think this was intended, am I right?

**Comment by tacaswell** [comment]
I think that was an intended change, but we failed to update the documentation / template.  Is that going to be a problem for Arch?

@anntzer can you confirm the intent?

Also, thank you to both @ArchangeGabriel and @felixonmars for your work on Arch packaging :tada:  (it is what I use on my personal machines).

**Comment by ArchangeGabriel** [comment]
No, it won’t be an issue at all, we build two copies anyway (one with the tests to check everything but fonts work, one without the tests for distribution). So currently the two copies end up being identical, but if it gets confirmed that this was intended, then we will switch from enabling tests in one copy to disabling them in the other. ;)

**Comment by anntzer** [comment]
Always installing tests was not an intended change of that PR (in fact as @tacaswell may remember I have a PR in the works for splitting the test install even more), looks like it got in accidentally... making a PR to revert that.

**Comment by timhoffm** [comment]
Reverted in #14008

**Comment by tacaswell** [comment]
> in fact as @tacaswell may remember I have a PR in the works for splitting the test install even more

No, my memory is a bit sieve like....

Thanks for following up on thin @anntzer !
