### ISSUE TITLE
_axes.py import statement overriding another import?

### ISSUE THREAD

**Issue by kasanitej** [matplotlib/matplotlib#13996]
The following may not be a bug, it is just an observation.
So I am going through the source code of the _axes.py file. During the import statements, I have seen the following two statements.

```
import matplotlib.category as _  # <-registers a category unit converter
import matplotlib.dates as _  # <-registers a date unit converter
```
Isn't it that matplotlib.dates namespace is overriding the matplotlib.category?

Thanks.

**Comment by jklymak** [comment]
The import executes some code in those modules but the actual modules are not explicitly needed.

**Comment by tacaswell** [comment]
Good catch @kasanitej ! 

 @jklymak has the correct explanation of what is going on here. Going to close this as I do not think this is a bug or feature we need to track (but I would merge a PR that adds a `del _` after those imports to make it clear they are not used).
