### ISSUE TITLE
Link to vischeck.com needs to be changed

### ISSUE THREAD

**Issue by vaibhavkarve** [matplotlib/matplotlib#14000]
### Bug report

**The documentation page on Colormaps has a link to vischeck.com but vischeck.com is no more available. The link is broken and should be changed.**

Link to documentation page: [https://matplotlib.org/users/colormaps.html](https://matplotlib.org/users/colormaps.html)

Unfortunately I do not know of any alternate websites that it can be replaced with. However, making colorblind-friendly images is very important from an accessibility point of view and this broken link should definitely be replaced.

**Comment by tacaswell** [comment]
Indeed, the DNS entry seems to be gone: https://dnschecker.org/#A/vischeck.com

I also don't know of a good replacement :disappointed:

**Comment by tacaswell** [comment]
Looks like it has been down for ~9 months (from 2018-08).
