### ISSUE TITLE
numpydoc 0.9 breaks doc build

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#14003]
`numpydoc` 0.9 has been released, which breaks the documentation build. See e.g. https://circleci.com/gh/matplotlib/matplotlib/20463 .

The problem is the `_preprocess_data` decorator trying to append a `.. note:` section to the end of the docstring doesn't play well with some of the numpydoc sections.

**Comment by tacaswell** [comment]
We should probably pin it back for now while we sort out a real fix..
