### ISSUE TITLE
How to change the color of border in Matplotlib 3d Ploting?

### ISSUE THREAD

**Issue by ConAntares** [matplotlib/matplotlib#14022]
With reading the Matplotlib Manual, I have mastered a lot of methods to personalize my graphic style. But I don't find how to change the color of borders.

my code:
```
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import axes3d
from matplotlib import rcParams

# Global Setting
plt.rcParams['font.family'] = 'CMU Serif'
#plt.rcParams['font.size'] = '14'               # Font Size
plt.rcParams['mathtext.fontset'] = 'cm'         # cm: Computer Mathematics
plt.rcParams['mathtext.rm'] = 'CMU Serif'       # Require CMU Serif font file
plt.rcParams['grid.color'] = '#F0F0F0'
plt.rcParams['grid.linestyle'] = 'solid'
plt.rcParams['text.usetex'] = True              # Require TeX environment
formatter = mpl.ticker.ScalarFormatter(useMathText=True)
formatter.set_scientific(True) 
formatter.set_powerlimits((-1,1))

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

X, Y, Z = axes3d.get_test_data(0.05)

ax.plot_wireframe(X, Y, Z, rstride=10, cstride=10)

ax.xaxis.pane.fill = False
ax.yaxis.pane.fill = False
ax.zaxis.pane.fill = False
ax.set_proj_type('ortho')                   # 'ortho': Orthographic; 'persp': Perspective(default)
#ax.set_axis_off()
ax.set_axis_on()
ax.grid(True)

fig.savefig("3D Line Py.pdf", dpi=1080)
plt.show()
```

This is my picture:
![a](https://i.stack.imgur.com/MLyGC.jpg)

But I want this kind of border like this:
![b](https://i.stack.imgur.com/X2ws8.png)

**Comment by jklymak** [comment]
This is a bug tracker; we very much prefer user questions go to stackoverflow where there are more folks able to provide help.  Of course if you find a bug or need a new feature, this is the place to post.

**Comment by dstansby** [comment]
@ConAntares you might be able to adopt this example to your use case: https://matplotlib.org/gallery/ticks_and_spines/spines.html#sphx-glr-gallery-ticks-and-spines-spines-py

If not, maybe it would be good for us to add an example of modifying spines on 3D axes.

**Comment by ConAntares** [comment]
I have found a method to solve this issue.

:)

```Python

ax.xaxis.pane.set_edgecolor('#D0D0D0')
ax.yaxis.pane.set_edgecolor('#D0D0D0')
ax.zaxis.pane.set_edgecolor('#D0D0D0')
ax.xaxis.pane.set_alpha(1)
ax.yaxis.pane.set_alpha(1)
ax.zaxis.pane.set_alpha(1)

```

**Comment by ConAntares** [comment]
But I hope that Matplotlib could custom the 3d borders styles.

I perfer the 3D border style of MathGL

![MathGL](http://mathgl.sourceforge.net/png/cont3.png)

**Comment by jklymak** [comment]
Closing as quite old, and I don't think there is an action here.  Follow up on https://discourse.matplotlib.org if there is further discussion...
