### ISSUE TITLE
Change style selection/generation algorithm

### ISSUE THREAD

**Issue by KOLANICH** [matplotlib/matplotlib#14025]
When one plots lots of curves on the same canvas without specifying their styles, each 10 curves the style become repeat itself. We need to throw away this algo.

Instead they should be generated.

1. select base styles. Black solid, black dashed, black dotted. Black curves are preferred first because they are suitable for printing on a laser printer.
2. draw with them first.
3. if the number exceeds, compute styles for the rest uniformly distributing colors  using HSV model, dashedness and dotedness.

**Comment by jklymak** [comment]
The default color styles just changed recently, I don't think there will be a lot of uptake on changing them again.  You can of course (and should!) define your own color and linestyle cycles: https://matplotlib.org/gallery/color/color_cycler.html#sphx-glr-gallery-color-color-cycler-py   There has been talk of making a way to organize these so they can be shared somehow, but that hasn't happened.

**Comment by timhoffm** [comment]
Apart from whether another change of the default style is bearable, I have some fundamental concerns on the proposal.

1. Preferably all black is a design decision for the specific scope of printing in b/w. While I have no data on that, I question if this is still the most dominant use-case. Color printers are more common nowadays and many graphs will only be used on screen. Since color can convey additional information and makes the graphs more visually appealing (personal opinion). I'm against of defaulting to all-black.
2. Automatically computing styles is hard to get visually distinct and good-looking at the same time. I don't dare to put the default style in algorithmic hands. I think our fixed style cycle (repeated if necessary) is the right way to go.

In total, I'm :-1: on the proposed changes.

That said, you can always set your own style as required. You can easily make a function that creates a sufficiently large style cycle with the style sequence of your choosing.

**Comment by KOLANICH** [comment]
>Preferably all black is a design decision for the specific scope of printing in b/w. While I have no data on that, I question if this is still the most dominant use-case. Since color can convey additional information and makes the graphs more visually appealing (personal opinion). I'm against of defaulting to all-black.

Only few first curves are proposed to be black. It is quite useless to print an image with more than 5 intersecting curves - printers usually have poorer resolution and color quality than screens, and on screens one can magnify plots interactively.

>Color printers are more common nowadays and many graphs will only be used on screen.

B&W laser ones are still having the best price per page. And even picture of inkjet ones looks poor.

>Automatically computing styles is hard to get visually distinct and good-looking at the same time.

In fact it is impossible, even if using hardcoded styles, like it is currently used.

>repeated if necessary) is the right way to go.

It makes different curves indistinguishable, I feel like any sensible automated solution will be better than this algo.

> You can of course (and should!) define your own color and linestyle cycles: https://matplotlib.org/gallery/color/color_cycler.html#sphx-glr-gallery-color-color-cycler-py

Thank you for the hint.

**Comment by tacaswell** [comment]
> Here knowing the count of lines is required beforehand.

We in general have no way of knowing ahead of time how many lines are going to be drawn (for example, at my day-job we use Matplotlib for live data visualization as part of data acquisition users need to see the plot as data comes in and at any point in the future we will add more lines (as they start the next experiment). 

That said, I think there are algorithms for picking "the color furthest from all of the colors I have already picked".

I would find in very odd for some of the lines to be black and others in color for a reason that was not to highlight the difference between the two classes.

I am also :-1: on changing the default behavior to this, however I think an example of 

```python
def plot_many_lines(ax, *data):
    ...
```

that implements such an algorithm would be interesting as an example or as a stand-alone library (see https://github.com/NSLS-II/scientific-python-cookiecutter for a cookie-cutter to boot-strap this quickly).

**Comment by KOLANICH** [comment]
>We in general have no way of knowing ahead of time how many lines are going to be drawn (for example, at my day-job we use Matplotlib for live data visualization as part of data acquisition users need to see the plot as data comes in and at any point in the future we will add more lines (as they start the next experiment).

Doesn't mpl plot everything on `show` call, not on `plot` call? I mean on `show` call count of curves is known, so colors can be generated.

**Comment by jklymak** [comment]
The user has to be able to set the color at `plot` time if they wish, and to querry the colors after the line has been added to the figure. So no, we do not wait until draw time to decide things like color.  As discussed above, if you want to change the colors at draw time based on how much data you have, you can easily write a method to do so.  i.e. `fix_colors(ax)`.s

**Comment by jklymak** [comment]
I'm going to close this as won't fix in the main library, but thanks for the ideas!  If you come up with something you think works well, please drop a line to the users mailing list and share.

**Comment by KOLANICH** [comment]
>The user has to be able to set the color at plot time if they wish, and to querry the colors after the line has been added to the figure. So no, we do not wait until draw time to decide things like color. 

Thank you for the info.
