### ISSUE TITLE
pip install matplotlib fails while building kiwisolver on mac

### ISSUE THREAD

**Issue by goerz** [matplotlib/matplotlib#14031]
Since today, when I try to install `matplotlib` on macOS via `pip`, the installation fails while trying to build `kiwisolver`. Can we ensure that all dependencies of `matplotlib` provide wheels?

<details>
<summary>log</summary>
<pre>
    ...
    Building wheels for collected packages: kiwisolver
    Building wheel for kiwisolver (setup.py) ... error
    Complete output from command /Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-install-t9u3qteo/kiwisolver/setup.py';f=getattr(tokenize, 'o$
    en', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-wheel-gp3bw9o8 --python-tag cp36:
    running bdist_wheel
    running build
    running build_ext
    building 'kiwisolver' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/py
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include -arch x86_64 -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include -ar$
    h x86_64 -I. -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include/python3.6m -c py/kiwisolver.cpp -o build/temp.macosx-10.7-x86_64-3.6/py/kiwisolver.o
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from py/kiwisolver.cpp:9:
    In file included from ./kiwi/kiwi.h:9:
    ./kiwi/constraint.h:9:10: fatal error: 'map' file not found
    #include <map>
            ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
    Failed building wheel for kiwisolver
    Running setup.py clean for kiwisolver
    Failed to build kiwisolver
    Installing collected packages: mpmath, sympy, click, pyparsing, six, cycler, python-dateutil, kiwisolver, matplotlib, coverage, py, atomicwrites, attrs, pluggy, more-itertools, pytest, pytest-cov, sphinxcontrib-jsmath, docutils, MarkupSafe, jinja2, snowballstemmer, sphin$
    contrib-htmlhelp, imagesize, chardet, urllib3, idna, requests, pytz, babel, sphinxcontrib-serializinghtml, sphinxcontrib-applehelp, packaging, sphinxcontrib-devhelp, alabaster, sphinxcontrib-qthelp, Pygments, sphinx, better-apidoc, sphinx-autodoc-typehints, isort, appdir$
    , toml, black, decorator, ipython-genutils, traitlets, pyrsistent, jsonschema, jupyter-core, nbformat, webencodings, bleach, mistune, testpath, defusedxml, entrypoints, pandocfilters, nbconvert, tornado, ptyprocess, terminado, pyzmq, Send2Trash, jupyter-client, appnope, $
    cwidth, prompt-toolkit, pickleshare, pexpect, parso, jedi, backcall, ipython, ipykernel, prometheus-client, notebook, jupyter-console, widgetsnbextension, ipywidgets, qtconsole, jupyter, argh, PyYAML, pathtools, watchdog, port-for, livereload, sphinx-autobuild, sphinx-rt$
    -theme, smmap2, gitdb2, gitpython, apipkg, execnet, pytest-forked, pytest-xdist, watermark, virtualenv, nodeenv, zipp, importlib-metadata, identify, cfgv, importlib-resources, aspy.yaml, pre-commit, pep8, nbval, pycodestyle, pyflakes, mccabe, flake8, readme-renderer, req$
    ests-toolbelt, pkginfo, tqdm, twine, nbsphinx, qdyn
    Running setup.py install for kiwisolver ... error
        Complete output from command /Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-install-t9u3qteo/kiwisolver/setup.py';f=getattr(tokenize, $
    open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-record-dv16j2ct/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_ext
        building 'kiwisolver' extension
        creating build
        creating build/temp.macosx-10.7-x86_64-3.6
        creating build/temp.macosx-10.7-x86_64-3.6/py
        gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include -arch x86_64 -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include -$
    rch x86_64 -I. -I/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/include/python3.6m -c py/kiwisolver.cpp -o build/temp.macosx-10.7-x86_64-3.6/py/kiwisolver.o
        warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
        In file included from py/kiwisolver.cpp:9:
        In file included from ./kiwi/kiwi.h:9:
        ./kiwi/constraint.h:9:10: fatal error: 'map' file not found
        #include <map>
                ^~~~~
        1 warning and 1 error generated.
        error: command 'gcc' failed with exit status 1

        ----------------------------------------
    Command "/Users/goerz/Documents/Programming/github/qdynpylib/.venv/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-install-t9u3qteo/kiwisolver/setup.py';f=getattr(tokenize, 'open', open)(__file__);$
    ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-record-dv16j2ct/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in
    /private/var/folders/ll/rgszt4s525s2xtv8rr60lqz40000gn/T/pip-install-t9u3qteo/kiwisolver/
    make: *** [.venv/py36/bin/py.test] Error 1
</pre>
</details>

**Comment by jklymak** [comment]
First, to work around this you should be able to do:

```
export LDFLAGS=--stdlib=libc++
export CFLAGS=--stdlib=libc++
```

Second, agreed that it'd be great if there were wheels:  @MatthieuDartiailh and @matthew-brett  made wheels for the last kiwi release, but that didn't get done yet for yesterdays release (I assume).  I'll open a ticket there...

**Comment by MatthieuDartiailh** [comment]
The wheels have been uploaded. There was only a couple of hour of gap between the source and wheel upload.

**Comment by jklymak** [comment]
The wheel seems to be there: 

https://files.pythonhosted.org/packages/df/93/8bc9b52a8846be2b9572aa0a7c881930939b06e4abe1162da6a0430b794f/kiwisolver-1.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

so I'll close this, but feel free to comment if its not working for some reason.
