### ISSUE TITLE
Purpose of Scatter plot with pie-chart markers example 

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#14055]
I would like to improve this example:

https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/scatter_piecharts.html

But I'm actually unclear, what the key message is:

- Should additional information be encoded in the pies? If so, one should have different pies at different points. This would require individual markers `xy*` per point.
- Or is this only a way to illustrate how to create fancy multicolored markers? In that case, I'd probably not adapt the size and resort to `plot()` instead of `scatter()` to keep it more simple.

**Comment by ImportanceOfBeingErnest** [comment]
I've definitely seen people asking how to use their own data for those pie charts and then finding it utterly complicated to produce one single marker per wedge. It would probably help to start with some 3 rows by 3 column (1 column per pie) dataset and use functions to simplify the creation of those markers.

Peronally, I think when attempting such pie chart scatter, I would always either opt for creating a pie inside an inset axes 

    mpl_toolkits.axes_grid1.inset_locator.inset_axes(..., 
                    bbox_to_anchor=(x-radius, y-radius, radius*2, radius*2),
                    bbox_transform=ax.transData, loc="center")

or creating the wedges from scratch inside a `DrawingArea`. 

One thing that makes the example unnecessarily complicated is the fact that markers are always normalized https://github.com/matplotlib/matplotlib/blob/e285ddeddc82521d2626a32cfa7587f52c6953db/lib/matplotlib/markers.py#L338-L340

so an option to turn this behaviour off might also simplify the example a lot.

**Comment by oscargus** [comment]
The pie-chart marker example does no longer exist. Should this be closed or renamed? 

(It seems like being able to create a scatter with custom pie charts may still be quite useful?)

**Comment by timhoffm** [comment]
The pie chart symbol example was removed in #22276. As it was, it was not very useful, because all points had the same pie distribution.
