### ISSUE TITLE
How to use matplotlib in pyqt5?

### ISSUE THREAD

**Issue by xlgforever** [matplotlib/matplotlib#14073]
i want to use matplotlib to plot the real-time changing data, i have tried to use a  custom subclass of `from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg`, and i define a update_plot function in the subclass to plot the axes like this:
- axes.cla()
- axes.plot(new_x, new_y)
- axes.autoscale_view(True,True,True)
- self.draw()-----the self means the instance of  the subclass, i think

and then in the GUI:
```
 def update(self):
        time_now = time.time()
        value_now = random.random() # for example
        self.data.append(pd.DataFrame({'time':[time_now],'values':[value_now]}), ignore_index=True)
        self.widget.update_plot(self.data.loc[:, 'time'].values.flatten(), self.data.loc[:, 'values'].values.flatten())
```
the widget is the promoted Widget by the subclass using Qt designer.

finally i use a QTimer in the GUI to update the plot every 1sec. but it does not work. i just get a blank plot:
![image](https://user-images.githubusercontent.com/40095259/56883062-22a01300-6a98-11e9-94f5-79041775a86b.png)

Although, i use the pyqtgraph to do the same thing and success, the pyqtgraph is not enough  to plot something.

**Comment by timhoffm** [comment]
Have you checked https://matplotlib.org/devdocs/gallery/user_interfaces/embedding_in_qt_sgskip.html?

**Comment by timhoffm** [comment]
Since there is no feedback, I assume this is solved.
