### ISSUE TITLE
cannot install dependencies

### ISSUE THREAD

**Issue by VoxelPrismatic** [matplotlib/matplotlib#14116]
### Bug report

**Bug summary**

Cannot install dependencies using provided code [debian/ubuntu]
It keeps on throwing `You must put some 'source' URIs in your sources.list`
**Code for reproduction**

```sudo apt-get install python3-matplotlib
sudo apt-get build-dep python-matplotlib
```

**Actual outcome**

```
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
```

**Expected outcome**

I expect it to install the dependencies, I cannot remember the version number but it worked about a month ago
**Matplotlib version**

  * Operating system: Kubuntu 18.10
  * Matplotlib version: Latest (installed 5/1/19 M/D/Y)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Latest (installed 5/1/19 M/D/Y)
  * Python version: 3.7.3
  * Jupyter version (if applicable): [none]
  * Other libraries: All latest - Numpy, Numexpr, Discord.py, Discord.py[voice]

**Comment by VoxelPrismatic** [comment]
It seems that `sources.list` some how got deleted, but I cannot find it in the repo history

**Comment by ksunden** [comment]
https://wiki.debian.org/SourcesList

`sources.list` is for apt, not matplotlib (you will likely get the same error message if you do `apt build-dep <some other package>`

**Comment by timhoffm** [comment]
Seems to be an issue with apt rather than matplotlib itself.
