### ISSUE TITLE
PyPI wheels should not set default backend

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#14121]
I just noticed that the wheels on PyPI still set a default backend in their matplotlibrc (to tkagg on linux/windows and to macosx on macos).  I think this should change, and we should instead omit the default backend and trigger fallback.

Currently, a linux/windows user who installs matplotlib from pypi and does not bother writing a matplotlibrc always gets tkagg, whereas backend fallback is triggered if (and only if) they explicitly write a matplotlibrc *and* explicitly ignore the `backend: ...` entry in it.  This seems **backwards**: I'd say backend fallback is here to help the "unconfigured" case, more than the "you have a config but ignored a key" case.  This also invalidates the relevant 3.0 whatsnew entry (https://matplotlib.org/users/whats_new.html#improved-default-backend-selection) in the default case of a PyPI install.

(Also, setting the default backend to macosx on macos is not really helpful -- backend fallback will already choose to use that backend if that works, and, if it doesn't (assuming nonframework builds are still an issue, which I'm not certain about), will perform the required fallback.)

If downstream redistributors want to set a default backend (#11844) that's their problem, but I think setting it on the PyPI wheels defeats some of the purpose of having backend fallback to start with...

**Matplotlib version**

  * Operating system: any
  * Matplotlib version: 3.0+
  * Matplotlib backend (`print(matplotlib.get_backend())`): that's the question
  * Python version: any

**Comment by amueller** [comment]
Also see @tacaswell's comment here: https://github.com/ContinuumIO/anaconda-issues/issues/10219#issuecomment-457220949

**Comment by tacaswell** [comment]
I believe I have changed this behavior for 3.1 (see https://github.com/MacPython/matplotlib-wheels/commit/39cf18eccd6c50bafc8891a8c0724dd374e75d46 and https://github.com/MacPython/matplotlib-wheels/commit/73a9f41f9050d3f9f452ea04cf1b939dadaf1ca5 )

This should be the case for the rc2 wheels that were just uploaded this morning.  I'm going to close this, please ping to re-open if the rc2 wheels do not have this behavior.

**Comment by amueller** [comment]
awesome, thanks!
