### ISSUE TITLE
Unexpected behavior in matplotlib.colors.to_rgba_array when passing unknown color name string

### ISSUE THREAD

**Issue by dwysocki** [matplotlib/matplotlib#14122]
### Bug report

**Bug summary**

Passing invalid color names as strings to `matplotlib.colors.to_rgba_array` sometimes produces surprising output, rather than crashing.  When a string is provided, but not recognized by `to_rgba`, the function attempts to iterate over each character in the string, and parse that as a named color.  In the off-chance each character is a valid color name, the function does not crash as it should, and instead returns one RGBA array for each character.

**Code for reproduction**

```python
import matplotlib as mpl
print("Works as expected")
print(mpl.colors.to_rgba_array("C9"))
print("Should crash, as there is no C10, but doesn't")
print(mpl.colors.to_rgba_array("C10"))
print("Successfully crashes")
print(mpl.colors.to_rgba_array("not-a-color"))
```

**Actual outcome**

```
Works as expected
[[0.09019608 0.74509804 0.81176471 1.        ]]
Should crash, as there is no C10, but doesn't
[[0.   0.75 0.75 1.  ]
 [1.   1.   1.   1.  ]
 [0.   0.   0.   1.  ]]
Successfully crashes
--------------------------------------------------------------------
KeyError                           Traceback (most recent call last)
/usr/lib/python3.7/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    165     try:
--> 166         rgba = _colors_full_map.cache[c, alpha]
    167     except (KeyError, TypeError):  # Not in cache, or unhashable.

KeyError: ('n', None)

During handling of the above exception, another exception occurred:

ValueError                         Traceback (most recent call last)
<ipython-input-21-338bfadd6f4f> in <module>
----> 1 print(mpl.colors.to_rgba_array("not-a-color"))

/usr/lib/python3.7/site-packages/matplotlib/colors.py in to_rgba_array(c, alpha)
    265     result = np.empty((len(c), 4), float)
    266     for i, cc in enumerate(c):
--> 267         result[i] = to_rgba(cc, alpha)
    268     return result
    269 

/usr/lib/python3.7/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    166         rgba = _colors_full_map.cache[c, alpha]
    167     except (KeyError, TypeError):  # Not in cache, or unhashable.
--> 168         rgba = _to_rgba_no_colorcycle(c, alpha)
    169         try:
    170             _colors_full_map.cache[c, alpha] = rgba

/usr/lib/python3.7/site-packages/matplotlib/colors.py in _to_rgba_no_colorcycle(c, alpha)
    210         except ValueError:
    211             pass
--> 212         raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
    213     # tuple color.
    214     c = np.array(c)

ValueError: Invalid RGBA argument: 'n'
```

**Expected outcome**

The code snippet should have crashed on
```python
print(mpl.colors.to_rgba_array("C10"))
```
but instead it returned RGBA values for "C" (cyan), "1" (black), and "0" (white).  This could easily surprise a user, as they may be naming colors like "C0", "C1", ..., and then forget that there is no "C10".

I think it would make sense, when `to_rgba_array` gets all the way to its last attempt to convert the values:
```python
    # Convert one at a time.
    result = np.empty((len(c), 4), float)
    for i, cc in enumerate(c):
        result[i] = to_rgba(cc, alpha)
    return result
```
it should raise an exception if `isinstance(c, six.string_types)` is `True`.

However, it is possible, however unlikely, that there are a few users out there making use of this functionality, so it may need to stay in.  In that case, I think at least a warning message would still be desirable, as there are likely more users who will hit this functionality by accident (e.g., with the "C10" example I used).

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

Installed matplotlib from pip.

**Comment by ImportanceOfBeingErnest** [comment]
In matplotlib 3.1, the cycler will continue cycling for `"C10"`, i.e.

    mpl.colors.to_rgba_array("C0") == mpl.colors.to_rgba_array("C10")

for the default case of a color cycle of 10 elements.

In view of this, is there any other case that gives undesired output?

**Comment by dwysocki** [comment]
Interesting, that certainly would solve the issue with the numbered colors.

However, I could still see this being an issue for a misspelling of a named color. I think it's a less likely scenario, but could still reasonably arise.

One example I was able to come up with: a user means to type "gray", but the "a" did not get pressed fully, making the input "gry" which can be interpreted as green, red, and yellow.  In other words, you'd have
```python
mpl.colors.to_rgba_array("gry") == mpl.colors.to_rgba_array(["g", "r", "y"])
```

I see this as less likely than the "C10" case, as it only arises with specific typos on specific color names, rather than a common logical error of assuming there are more than 10 "Cx" colors, so maybe it's acceptable.  It still might be worth producing a warning message, though.

**Comment by tacaswell** [comment]
This is one of issues with APIs that take flexible input.  If `to_rgba_array` gets a string it is ambiguous if the user means "this is one color, please give be back a (1, 4) array" or "this is a sequence of single character colors and I want back a (len(inp), 4) array".   To break the ambiguity we give precedence to the first case and then try the second.

I think raising in the "string as an iterable of single character colors" would not be a good idea because we are very flexible about taking "inputs" as iterables else where in the library.  I am also against warning in that case because while in some cases we are down that codepath via a typo in other cases we are down that code path intentionally.  In the later case we should not be warning (because we are doing what the user wants).  However, because we can not tell those two cases apart we should not warn.

**Comment by anntzer** [comment]
I think it would make sense to treat strings as "not iterables" ("not an iterable of 1-character codes") for this purpose.  After all, we don't treat e.g. `plot([1, 2, 3], "abc")` as `plot([1, 2, 3], ["a", "b", "c"])` (categorical) (and that's true for functions less pathological than `plot` as well, e.g. `bar`).
It would be reasonable that "iterable" means in matplotlib's context `np.ndim(x) > 0` (i.e. `np.asarray(x)` is not a size-() array), rather than the stdlib definition.

**Comment by tacaswell** [comment]
@anntzer fair, so the proposal is warn-on and deprecate "str-as-iterable-of-1-char-colors'?

**Comment by anntzer** [comment]
yes

**Comment by tacaswell** [comment]
:+1:
