### ISSUE TITLE
Why was the EMF format removed ？

### ISSUE THREAD

**Issue by zzdzzdzzdzzd** [matplotlib/matplotlib#14133]
We know that previous versions had EMF format, but why remove it now? When writing a paper,  figures with EMF format are often needed. There will always be problems in putting the figure with other format into the paper, such as low resolution of figure or too large storage of figure.

**Comment by jklymak** [comment]
Matlab stores EMF, wasn't aware matplotlib ever did.

**Comment by timhoffm** [comment]
EMF support was based on pyemf, which is not available on PyPI, so you cannot pip-install that dependency. Also, it seems it did not really work (https://github.com/matplotlib/matplotlib/issues/1961#issuecomment-17191599).

Therefore it was removed in matplotlib 1.4. See #1961.
