### ISSUE TITLE
Default backend not availabe on windows with pip-installed matplotlib 3.0.3

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#14142]
There seems to be a relatively common error with not having the tk backend after installing matplotlib on windows:
https://github.com/amueller/word_cloud/issues/483

This SO question seems quite popular:
https://stackoverflow.com/questions/36327134/matplotlib-error-no-module-named-tkinter

Maybe there should be fallback if tk is not available.

**Comment by anntzer** [comment]
see also #14121.

**Comment by amueller** [comment]
Feel free to close as duplicate. I think the link to the SO question is helpful since it shows how common a problem this is.
