### ISSUE TITLE
plt.close() does not close the plot window with TkAgg backend on MacOS

### ISSUE THREAD

**Issue by hlgirard** [matplotlib/matplotlib#14161]
### Bug report

**Bug summary**

plt.close() does not close the plot window with TkAgg backend on MacOS

**Code for reproduction**

```python
import matplotlib.pyplot as plt 
plt.ion()
plt.plot([1.6, 2.7]) # This shows the plot in a window
plt.title("Test Title") # This works showing the link between code and plot works
plt.clf() # This works too, clearing the figure
plt.close() # This makes the plot window unresponsive but does not close it.
```

**Actual outcome**

The window becomes unresponsive (rainbow wheel when hovering) but does not close until the ipython prompt is exited. Switching to the Qt4Agg backend results in the expected behavior.

**Expected outcome**

The plotting window should close.

**Matplotlib version**
  * Operating system: OS X 10.14.4 Mojave
  * Matplotlib version: 3.0.3
  * Matplotlib backend: TkAgg
  * Python version: 3.7

**Comment by efiring** [comment]
1) What version of ipython?
2) Are you invoking ipython with the `--gui` option?
3) Are you using `%matplotlib tk`?
4) Do you have tkagg backend set via an rcParam, or are you using `matplotlib.use('tkagg')`?

**Comment by efiring** [comment]
I can verify similar behavior with mpl v2.2.2, ipython 6.5, Mojave:
```
$ ipython
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %matplotlib tk

In [2]: import matplotlib

In [3]: import matplotlib.pyplot as plt

In [4]: plt.plot([1,2,3])
[<matplotlib.lines.Line2D at 0x11c4d0278>]

In [5]: plt.close()
```
and the window is dead with the spinning ball until ipython is exited.

**Comment by efiring** [comment]
It gets worse with master and up-to-date ipython:
```
(mpl1) ~/work/programs/py/mpl/tests $ ipython
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib

In [2]: matplotlib.__version__
'3.1.0.post1017+g4b50ce6cc'

In [3]: %matplotlib tk

In [4]: import matplotlib.pyplot as plt

In [5]: plt.plot([1,2,3])
[<matplotlib.lines.Line2D at 0x11a6a8cf8>]

In [6]: plt.close()
```
The window opens, but the plot never appears.  Resizing the window turns it from white to black.  As before, the `close` has no effect; the window remains with the spinning ball until ipython is exited.

**Comment by efiring** [comment]
The above steps work correctly with `%matplotlib osx` and `%matplotlib qt`.

**Comment by efiring** [comment]
The tk backend seems completely broken on osx.  Executing a script:
```
import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()
```
gives the same behavior: a blank plot that turns from white to black when resized.
Interrupting it with Ctrl-C gives a traceback:
```
(mpl1) ~/work/programs/py/mpl/tests $ python tktest.py
^C
Traceback (most recent call last):
  File "tktest.py", line 7, in <module>
    plt.show()
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/pyplot.py", line 271, in show
    return _show(*args, **kw)
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/cbook/deprecation.py", line 405, in wrapper
    return func(*args, **kwargs)
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backend_bases.py", line 3337, in show
    cls.mainloop()
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 907, in mainloop
    managers[0].window.mainloop()
  File "/Users/efiring/miniconda3/envs/mpl1/lib/python3.7/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
```

**Comment by hlgirard** [comment]
My code was executed as a script since it is part of a larger utility I am writing. I reached the same conclusion that switching to Qt or osx backends solves the problem. It appears to be directly linked to the Tkinter backend.

**Comment by greglucas** [comment]
I can't reproduce any of the above scripts on newer versions of Matplotlib, the tkagg backend appears to close the window properly for me. Feel free to reopen if you are still running into this issue.
