### ISSUE TITLE
setup downloads sometimes fails CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by zerothi** [matplotlib/matplotlib#14169]
### Bug report

Sometimes (depending on how Python has been installed) one might see a 
```bash
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```
error.

**Fix**

The easy fix is to ensure `certifi` certificates path is added to the `urlopen` method.

I.e. in your `setupext.py` you may need:
```python
import certifi
    with urlopen(
            Request(url, headers={"User-Agent": ""}), cafile=certifi.where()) as req:
        file_contents = BytesIO(req.read())
```

Probably there needs to be some try-execpt-(import certifi-fix) to handle this.

**Matplotlib version**

This happens when `setup.py` tries to download files, e.g. the recent change to jquery download. So basically I have only seen this in 2.2.4 and 3.0.3.

Agreed, this may be because my installation is not the same as system installations, but it may happen elsewhere I guess.

**Comment by tacaswell** [comment]
I was thinking

```python
try:
    import certifi
    ca_path = certifi.where()
except ImporError:
    ca_path = None
````

to avoid having the two copies of the `Request` line, but either way should work (assuming `ca_path` being `None` is ok with `Request`).

**Comment by zerothi** [comment]
Yeah, that is a good idea! But I don't know if `ca_path` would cause other problems (sometimes?)

**Comment by tacaswell** [comment]
Re-milestoned this to oldest version of Matplotlib this is going to be supported in the near future.

**Comment by QuLogic** [comment]
`certifi` was added in #18225.
