### ISSUE TITLE
Could you add different styles of border and axes in 3D graphics?

### ISSUE THREAD

**Issue by Photonico** [matplotlib/matplotlib#14163]
Matplotlib is my most commonly used visualization solution. But I have a little dissatisfaction with the style of border and axes plotting. I prefer the style of Gnuplot and MathGL.
Could you develop it?

Gnuplot Sample:
![Gnuplot Sample](http://gnuplot.sourceforge.net/demo_5.3/fenceplot.1.png)

MathGL Sample:
![MathGL Sample](http://mathgl.sourceforge.net/png/cont3.png)

Another question is that could you tell me when will Matplotlib get the support of OpenGL?

Sincerely,

**Comment by story645** [comment]
Those look lovely. Is there functionality missing from matplotlib or documentation missing from the [making a custom style](https://matplotlib.org/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py) tutorial that's preventing you from creating those styles?

**Comment by tomneep** [comment]
Perhaps a slightly different issue to this (let me know if a separate issue is needed) but the setting a style with a 3d figure doesn't really work very well. For example

```python
import matplotlib.pyplot as plt 
import numpy as np

plt.style.use('ggplot')
fig, axes = plt.subplots(subplot_kw=dict(projection='3d'))
for mu, sigma, marker in [(-.5, 0.75, 'o'), (0.75, 1., 's')]:
        x, y = np.random.normal(loc=mu, scale=sigma, size=(2, 30))
        z = np.random.random(size=30)
        axes.plot(x, y, z, ls='none', marker=marker)
fig.suptitle("ggplot", fontsize=16)
```
gives
![ggplot_bad](https://user-images.githubusercontent.com/17545360/88916106-65353a00-d25d-11ea-926d-5870fd5e13c9.png)

a simple fix here is to set the `figure.patch` `facecolor` to be the same as the `axes.patch` `facecolor` with 

```python
fig.patch.set_facecolor(axes.patch.get_facecolor())
```
to get 
![ggplot_good](https://user-images.githubusercontent.com/17545360/88916249-a7f71200-d25d-11ea-938c-6a895f225e21.png)
but then this doesn't really match the ggplot style for 2d. Setting the panes to have the right facecolor might be more appropriate
```python
ax_color = axes.patch.get_facecolor()
axes.patch.set_facecolor(fig.patch.get_facecolor())
for a in axes.xaxis, axes.yaxis, axes.zaxis:
    a.pane.set_facecolor(ax_color)
```
![ggplot_better](https://user-images.githubusercontent.com/17545360/88916760-8cd8d200-d25e-11ea-9463-17e97aeab474.png)

The downside here is that all the "default" 3d panes have slightly different colors, presumably to make them slightly distinctive and that is lost here, but if this approach was considered the best solution then perhaps some small color variations could be added back in.

Sorry for the long post, the bottom line is that the style sheets don't really work for 3d plots.

**Comment by oscargus** [comment]
Just a note that it is now possible to set the 3D pane color using style files.
