### ISSUE TITLE
Spurious warning calling fig.show() in jupyter inline backend

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#14171]
### Bug report

**Bug summary**

Using `fig.show()` in a notebook raises what seems like an un-needed warning. After calling `plt.show()` once, all subsequent calls to `fig.show()` don't raise the warning.

**Code for reproduction**

```python
%matplotlib inline
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.show()
```

**Actual outcome**

Plot is shown fine, but the following warning is raised:

```
/Users/dstansby/miniconda3/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  % get_backend())

```

**Expected outcome**

The figure is shown fine, so the warning seems unnecessary.

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version: `master` branch
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3
  * Jupyter version (if applicable): 4.4.0

**Comment by nitrofortin** [comment]
Creating a placeholder for this backend to avoid the NoGUIException or simply continue using `fig.show(warn=False)`. I am new here so let me know if it makes any sense.

**Comment by milind-prajapat** [comment]
Exact same issue on windows as well

**Comment by tacaswell** [comment]
I think the correct fix for this is for IPython to implement a no-op `manager.show()`.

**Comment by oscargus** [comment]
I've opened an issue in ipython for this, so closing assuming that the comment from @tacaswell is indeed correct.
