### ISSUE TITLE
Unnecessary QApplication reference count increase in backend_qt5.py

### ISSUE THREAD

**Issue by vasole** [matplotlib/matplotlib#14178]
### Bug report

**Bug summary**

Random crashes when ending applications using matplotlib with PyQt5 that do not happen with PySide2.

The random crashes disappear is a weakref to the already existing QApplication is hold instead of increasing the QApplication reference count.

**Code for reproduction**

Closing the shown window by the code below may results on crashes under PyQt5 that do not happen under PySide2.

```python
from PyQt5.QtWidgets import QApplication, QWidget
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class MyWidget(QWidget):
    def __init__(self, parent=None):
        QWidget.__init__(self, parent)
        self.fig = Figure()
        self.canvas = FigureCanvas(self.fig)

app = QApplication([])
w = MyWidget()
w.show()
app.exec_()
app = None
```

**Actual outcome**

When closing the window one can get a Python crash.

![image](https://user-images.githubusercontent.com/5636251/57458305-67366600-7271-11e9-9ef8-cea06055fafb.png)

**Expected outcome**

No crash.

**Matplotlib version**

  * Operating system: Windows 7
  * Matplotlib version:  3.0.3 (from PyPI) and 3.1.0rc2 (from Gohlke)
  * Matplotlib backend (`print(matplotlib.get_backend())`): PyQt5
  * Python version: 3.7 from python.org
  * Other libraries: PyQt5-5.12.2 from PyPI

**Comment by tacaswell** [comment]
Is this a new problem?  We have held onto the hard reference if we found an existing QApplication from d400dc5feeea2fbf1705e52cc5da2fd4ce743daf (2010, mpl 1.1.0)

**Comment by tacaswell** [comment]
I spoke with @vasole about this in person and he can no longer reproduce this.

If it is not possible for there to be multiple hard-refs to the qapp and still have the process shut down cleanly, then this should be raised as an issue with pyqt.
