### ISSUE TITLE
Figure object behavior in Jupyter and Python console

### ISSUE THREAD

**Issue by zhangt58** [matplotlib/matplotlib#14183]
For the `Figure` object, e.g. `fig` created from `plt.figure()`, of which the `show()` method could be used to show the plot, in the Python/IPython console, after `fig.show()` and close the pop-up plot window, the `fig` object will not be able to `show()` again,  while in Jupyter-Notebook, `fig.show()` does not pop up anything, instead, direct executing `fig` will show the plot, and this can be executed as many times as needed.

So the first question is: Can I do `fig.show()` more than one times in Python console?

Another question is: Can I make a copy of `fig`? The intention is to try to plot on the same figure with different axes, see the code snippets below in Jupyter:

```Python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
x = np.linspace(-4, 4, 100)
y = np.sin(x)

ax.plot(x, y)

# execute 'fig' can show current plot with sin curve, I will make this as my drawing canvas
fig
# After this point, the `fig` object  permenantly updated, and I would hope I can do the following
fig1 = fig.copy()
ax1 = ax.copy()
# add another curve, e.g. ax1.plot(x1, y1)
# then I get updated figure, show it by executing `fig1`
# and do the same procedure to draw another plot on fig,
# by `fig2 = fig.copy(), ax2 = ax.copy(), ax2.plot...`
```
It looks like I cannot use `deepcopy` from `copy` module to copy `Figure` nor `Axes` objects.

Please let me know If my understanding is wrong, or there is already some approaches that I can work with to achieve what I want. Thanks!

**Matplotlib version**

  * Operating system: Linux Mint 19.1
  * Matplotlib version: 2.1.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline (jupyter),  TkAgg (Python console)
  * Python version: 3.6.8
  * Jupyter version (if applicable): 5.2.2

**Comment by nitrofortin** [comment]
You might want to look into pickle to copy the objects (by saving and loading them back).

It was suggested here at least: https://stackoverflow.com/questions/45810557/pyplot-copy-an-axes-content-and-show-it-in-a-new-figure
