### ISSUE TITLE
Overlapping title+suptitle with constrained_layout and low h_pad

### ISSUE THREAD

**Issue by ArchangeGabriel** [matplotlib/matplotlib#14184]
### Bug report

**Bug summary**

When using both `title` and `suptitle` with `constrained_layout`, titles overlap.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.rcParams = plt.rcParamsDefault
plt.rcParams['figure.constrained_layout.use'] = True
plt.title('Test with b')
plt.suptitle('Test with p')
```

Other possibility is the exact demonstration that is used to work by @jklymak [here](https://github.com/matplotlib/matplotlib/issues/5355#issuecomment-441287273), hence the “Regression?” tag in the title. I don’t have time to bisect currently though…

**Actual outcome**

[test.pdf](https://github.com/matplotlib/matplotlib/files/3167592/test.pdf)

**Expected outcome**

Titles are spaced correctly.

**Matplotlib version**
  * Operating system: ArchLinux
  * Matplotlib version: 3.1rc2
  * Matplotlib backend (`print(matplotlib.get_backend())`): multiple
  * Python version: 3.7.3

Python and matplotlib are distro packages.

**Comment by jklymak** [comment]
I can't reproduce on master or 3.1.0rc2.    Are you *sure* you were using 3.1rc2?

[TEst.pdf](https://github.com/matplotlib/matplotlib/files/3167742/TEst.pdf)

**Comment by ArchangeGabriel** [comment]
Yes, but seeing the ticks and the white space on your figure I’ve realized that the line I was using to reset `rcParams` does not work. So I’ve moved away my matplotlibrc and the above test does indeed work with the default config, but it fails again if you add this:
```
plt.rcParams['figure.constrained_layout.h_pad'] = 0.01
```
So not sure whether this is expected, but I would have expected that the titles should not overlap even if `h_pad` is set to zero.

**Comment by jklymak** [comment]
OK, closing as a duplicate of #13672, if thats OK.   

Basically the algorithm works fine, but we need to account for the difference of the descending characters when we place the subtitle, and we are not.  Probably straightforward to fix....

**Comment by ArchangeGabriel** [comment]
OK, I trust you on both being the same underlying issue. ;)
