### ISSUE TITLE
Varying results depending on server operating system

### ISSUE THREAD

**Issue by HannhaHsu** [matplotlib/matplotlib#14182]
### Bug report

**Bug summary**

The images saved on Linux and Windows are different on some pixel values, even though they are visually almost the same. The matplotlib was set to backend, due to display not available on the running server.

**Python Code for reproduction**
```
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
plt.switch_backend('agg')
from matplotlib.lines import Line2D 

data = pd.read_csv(os.path.join(self.input_path, "for_wafermap_plotting.csv"))
data['Radius'] = np.power((np.power((data['field_center_x'] + data['intra_field_x']),2) + np.power((data['field_center_y'] + data['intra_field_y']),2)), 0.5)
plot_scatterplot(data, X_column = 'Radius', Y_col_list = ['predicted_size'],
                         output_path=os.path.join(self.output_path, "scatter_plot1.png"))

def plot_scatterplot(dataframe, X_column, Y_col_list, xlim_range = [0,0], ylim_range = [0,0], customize_xlim = False, customize_ylim = False, legends=[], marker_size = 104, marker_style = 0, marker_color = 0, is_grid = True, is_legend = True, legend_loc='upper left', x_label = 'X [mm]', y_label = 'Y [mm]', title = 'Table', output_path=None):
    # Define figure size
    fig,ax = plt.subplots(figsize=(20,16)) 
    # Add grid to the figure if specified as True       
    if is_grid:
        plt.grid(color='grey', linestyle=':')
    marker_list = Line2D.filled_markers
    colors_list = ['b','r','g','c','m','y','k']
    axes = []
    if len(Y_col_list) == 1:
        plot = ax.scatter(dataframe[X_column], dataframe[Y_col_list[0]], s = marker_size, marker = marker_list[marker_style], c = 'b')
        axes.append(plot)
    elif len(Y_col_list) > 1:
        for Y_column in Y_col_list:
            plot = ax.scatter(dataframe[X_column], dataframe[Y_column], s = marker_size, marker = marker_list[marker_style], c = colors_list[marker_color])
            marker_color += 1
            marker_style += 1
            axes.append(plot)
    # Add legend, x label, y label, title
    if (len(legends) > 0) and is_legend:
        ax.legend(axes, legends, loc = legend_loc, fontsize = 44, bbox_to_anchor=(0., -0.15),
                  mode="expand", borderaxespad=0.)
    plt.tick_params(labelsize = 44)
    plt.xlabel(x_label, fontsize = 52)
    plt.ylabel(y_label, fontsize = 52)
    plt.title(title, fontsize = 52)
    if customize_xlim == True:
        plt.xlim(xlim_range[0], xlim_range[1])
    if customize_ylim == True:
        plt.ylim(ylim_range[0], ylim_range[1])
    # Save figure
    if output_path is not None:
        ax.figure.savefig(output_path, bbox_inches='tight')
    plt.close()
```

**Actual outcome**

![scatter_plot1_linux](https://user-images.githubusercontent.com/19208969/57475563-67bb0680-7249-11e9-8e1f-9fd6d962f923.png)
![scatter_plot2_windows](https://user-images.githubusercontent.com/19208969/57475565-68ec3380-7249-11e9-824e-1d19382f6b2c.png)

By loading and comparing using:
```
import pandas as pd
import matplotlib.pyplot as plt
img = plt.imread(r"C:\Users\..\Desktop\refs\wafermap_plot1_linux.png")
img2 = plt.imread(r"C:\Users\..\Desktop\refs\wafermap_plot1_windows.png")
diff = pd.DataFrame(img2[:,:,1]-img[:,:,1])
for i in range(diff.shape[1]):
    print (i, diff.loc[diff[i] != 0].shape[0])
---> some non-0 values are observed
```
**Expected outcome**

Exactly same files at pixel level
img == img2

**Matplotlib version**

  * Operating system: Microsoft Windows 10 Enterprise, Linux
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`): plt.switch_backend('agg')
  * Python version: 2.6.9
  * Jupyter version (if applicable): 1.4.3
  * Other libraries: 
argparse | 1.3.0 
lxml | 3.4.4 
matplotlib | 1.4.3 
nose | 1.3.7 
numpy | 1.9.2 
pandas | 0.16.2
patsy | 0.4.0 
pip | 7.1.0
pyparsing | 2.0.3
pyqt | 4.10.4
python | 2.6.9
python-dateutil | 2.4.2
pytz | 2015.4 
scikit-learn | 0.16.1
scipy | 0.16.0 
setuptools | 18.0.1 
six | 1.9.0 
statsmodels | 0.6.1
vc | 9 
vs2008_runtime | 9.00.30729.1 

1. Download Anaconda 2.7 version. Source: https://www.anaconda.com/download/
2. conda create -n python2.6 python=2.6.9 numpy scipy matplotlib pandas scikit-learn statsmodels lxml argparse
3. conda activate python2.6 
4. conda install pytz==2015.4
5. conda install pyqt==4.10.4

**Comment by jklymak** [comment]
Different versions of font libraries can give you small differences in the fonts.  Then using `bbox_inches=tight` can make the difference even more stark because it may resize the tow figures differently.

**Comment by HannhaHsu** [comment]
@jklymak Thanks for responding promptly. Can you please explain why the font libraries versions are different in this case, as the same matplotlib packages are installed on both OS?

**Comment by tacaswell** [comment]
Can you check the version of freetype on the two machines?  This is a build / install time decision so it is possible that conda picked slightly different versions on linux vs windows.

Rendering fonts is a surprisingly hard problem that we fully out-source to freetype.  Between minor versions they slightly change the exact rendering of the glyphs when rasterized (as that is what 'bug fixes' look like to them!).  If you need pixel identical pngs between OS make sure you pin both matplotlib and freetype.

This exact problem actually causes us difficulty in our test suite (which is currently pinned to a pretty old version of freetype).

**Comment by HannhaHsu** [comment]
@tacaswell 
I have checked the freetype versions:
Windows: 2.9.1
Linux: 17.4.11
Which one would you recommend to continue to use to make the results from linux and windows consistent?

**Comment by tacaswell** [comment]
`Linux: 17.4.11` is not a freetype version (they are currently 2.10) so something seems off there.  

It does not particularly matter what version you use, so long as it is the same (our test suite is pixel identical across OS on a fixed version of freetype).

**Comment by anntzer** [comment]
that looks like a freetype libtool version, the conversion table is at https://github.com/aseprite/freetype2/blob/master/docs/VERSIONS.TXT#L53 so that would be 2.5.5 (quite old).

**Comment by HannhaHsu** [comment]
Got it. Thanks to all! @tacaswell @anntzer @jklymak

**Comment by HannhaHsu** [comment]
@anntzer and all,

I wonder wouldn't it be ideal if we ask Anaconda to include freetype in the package, to maintain the consistency?

**Comment by jklymak** [comment]
You mean freeze the freetype version? It seems we can trust users who need images to be consistent to freeze their own installs.

**Comment by HannhaHsu** [comment]
What I meant is that if there are dependencies to other packages, anaconda could include the depended packages as well. As a anaconda user, I think that is the purpose of having Anaconda.

**Comment by jklymak** [comment]
I think the conda recipe is maintained elsewhere.  But surely it includes free type.
