### ISSUE TITLE
axhline/axvline don't use prop_cycle

### ISSUE THREAD

**Issue by u55** [matplotlib/matplotlib#14222]
Hi matplotlib developers,
`axhline` and `axvline` do not use the prop_cycle, and it seems to me that they should. Was this intentional?

```python
import numpy as np
import matplotlib.pyplot as plt
from cycler import cycler

fig, ax = plt.subplots()
ax.set_prop_cycle(cycler(color=['r', 'g', 'y', 'm'], ls=['--']*4))
ax.plot(np.arange(9))
ax.axhline(4) # uses default styles instead of cycler
ax.axvline(4) # uses default styles instead of cycler
ax.plot(-np.arange(9))
plt.show()
```

Tested with matplotlib 3.0.3 and python 3.7.3 (Anaconda) on Windows 10.

**Comment by jklymak** [comment]
Usually these are not meant to represent data, but rather some interesting value.  Hence, I don't think they should participate in the cycle....

**Comment by u55** [comment]
@jklymak Thanks for the answer. I don't see the distinction between a single _value_ and _data_ (an array of values), but it sounds like your typical use-case is more like a configurable grid line or annotation, in which case I would expect the default color to be gray or black instead of 'tab:blue', so as to distinguish it from _data_ lines plotted with the default color cycle. 

But if the consensus is that the current behavior is desired, I will close the issue.

**Comment by jklymak** [comment]
Yeah, that's exactly how I think of it.  I'd be for the default being black, but....

FWIW, I think you can manually use the cycle colors...

**Comment by u55** [comment]
> FWIW, I think you can manually use the cycle colors...

Do you mean something more sophisticated than `ax.axhline(4, color='g', ls='--')` ?

**Comment by tacaswell** [comment]
@u55 You can do things like

```python
for j, stys in enumerate(my_cycler):
    ax.axhline(j, **stys)
```

I think @jklymak 's analysis is correct and a common usage is easily configurable "extra" grid lines.

The default color ends up falling through to `rcParams['lines.color']` which is by default `'C0'` which is not great for exactly the reasons you state @u55 . 

However changing the default color of `axvline` would be an API change and unfortunately we missed this when we did 2.0.  If we had noticed this when we were going through that process I suspect we would have changed `axvline` and `axhline` to match the grid color by default.

At this point, I am concerned about changing default colors ad-hoc as once we start to go down that route it opens up a rather scary can of worms....

**Comment by u55** [comment]
@tacaswell Yeah, I also wouldn't expect you to change the default color now, at least not until the next major version bump (4.0).
