### ISSUE TITLE
latex \substack does't work

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [matplotlib/matplotlib#14247]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: win10
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: python37
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by dstansby** [comment]
Could you post a minimal example of the code needed to produce the error, and the error message you get?

**Comment by anntzer** [comment]
Let's just assume this is a request for the latex \substack command (https://tex.stackexchange.com/questions/153490/atop-vs-substack-for-multiple-lines-under-a-sum).

**Comment by anntzer** [comment]
attn @devRD, perhaps.
