### ISSUE TITLE
Can't use CJKV?

### ISSUE THREAD

**Issue by diohabara** [matplotlib/matplotlib#14269]
### Bug report

**Bug summary**

I cannot write Japanese comments on matplotlib's graphs.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
data_a = [1, 2, 3, 4, 5]
data_b = [1, 4, 9, 16, 25]
plt.title('V_DS-I_D特性')
plt.scatter(data_a, data_b)
plt.show()
```

**Actual outcome**

https://imgur.com/HUTjUPQ

The part written in Japanese appears as weird rectangles.

**Matplotlib version**

  * Latest Google Collaboratory

**Comment by anntzer** [comment]
That is because the default font (DejaVu Sans) does not have CJKV [chinese japanese korean vietnamese] glyphs.  Matplotlib 3.1+ (https://github.com/matplotlib/matplotlib/pull/12759) prints a warning: `Requested glyph (\N{CJK UNIFIED IDEOGRAPH-7279}) missing from current font.`
