### ISSUE TITLE
symlog looses some points since 3.1.0 (example given)

### ISSUE THREAD

**Issue by tbarbette** [matplotlib/matplotlib#14265]
### Bug report

**Bug summary**

Since I updated to 3.1.0, symlog looses some points, at least when drawing a scatter plot

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
 
x = [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01, 1.2000e+01, 1.3000e+01, 1.4000e+01, 1.5000e+01, 1.6000e+01, 1.7000e+01, 1.8000e+01, 1.9000e+01, 2.0000e+01, 2.1000e+01, 2.2000e+01, 2.3000e+01, 2.4000e+01, 2.5000e+01, 2.6000e+01, 2.7000e+01, 2.8000e+01, 2.9000e+01, 3.0000e+01, 3.1000e+01, 3.2000e+01, 3.3000e+01, 3.5000e+01, 3.7000e+01, 3.8000e+01, 3.9000e+01, 4.0000e+01, 4.2000e+01, 4.3000e+01, 4.5000e+01, 4.6000e+01, 4.8000e+01, 5.0000e+01, 5.2000e+01, 5.5000e+01, 5.7000e+01, 6.0000e+01, 6.1000e+01, 6.3000e+01, 6.7000e+01, 6.8000e+01, 7.1000e+01, 7.6000e+01, 7.7000e+01, 8.0000e+01, 8.6000e+01, 8.7000e+01, 8.8000e+01, 9.1000e+01, 9.8000e+01, 9.9000e+01, 1.0000e+02, 1.0400e+02, 1.1400e+02, 1.1600e+02, 1.2100e+02, 1.3300e+02, 1.3400e+02, 1.3500e+02, 1.4200e+02, 1.5600e+02, 1.5700e+02, 1.5900e+02, 1.6700e+02, 1.8600e+02, 1.8700e+02, 1.8800e+02, 1.9000e+02, 2.0000e+02, 2.2600e+02, 2.3000e+02, 2.3100e+02, 2.4600e+02, 2.9200e+02, 2.9500e+02, 2.9900e+02, 3.0000e+02, 3.2000e+02, 4.4200e+02, 4.4500e+02, 4.5200e+02, 4.5700e+02, 4.8500e+02, 1.0645e+04, 1.1602e+04, 1.3856e+04, 1.6537e+04, 1.7642e+04, 2.2227e+04]

y = [0.57583333, 0.73833333, 0.81666667, 0.86016667, 0.88616667, 0.90266667, 0.91416667, 0.92333333, 0.93033333, 0.93633333, 0.94133333, 0.946, 0.94966667, 0.95333333, 0.95633333, 0.95866667, 0.96133333, 0.9635, 0.9655, 0.96683333, 0.96866667, 0.97016667, 0.97166667, 0.97266667, 0.97383333, 0.97483333, 0.9758, 0.97633333, 0.9775, 0.97783333, 0.979, 0.9795, 0.97983333, 0.98083333, 0.9818, 0.982, 0.982, 0.983, 0.983, 0.984, 0.984, 0.985, 0.985, 0.986, 0.986, 0.987, 0.987, 0.988, 0.988, 0.988, 0.989, 0.989, 0.989, 0.99, 0.99, 0.99, 0.991, 0.991, 0.991, 0.991, 0.992, 0.992, 0.992, 0.992, 0.993, 0.993, 0.993, 0.994, 0.994, 0.994, 0.994, 0.995, 0.995, 0.995, 0.995, 0.996, 0.996, 0.996, 0.996, 0.996, 0.997, 0.997, 0.997, 0.997, 0.998, 0.998, 0.998, 0.998, 0.998, 0.999, 0.999, 0.999, 0.999, 0.999, 1., 1., 1., 1., 1., 1. ]

plt.xscale("symlog")
plt.scatter(x, y)
plt.show()
```

**Actual outcome**
Using 3.1.0
![310](https://user-images.githubusercontent.com/248961/57986525-64f4b880-7a76-11e9-941f-4dea5da9f722.png)

**Expected outcome**
Using 3.0.3
![303](https://user-images.githubusercontent.com/248961/57986520-57d7c980-7a76-11e9-9b2d-0e23e2adcd65.png)

Especially look at the Y axis, we lost the 0.5 value and 0.7 too. Worst, I think (not clear here in this picture) that the points are shifted from the actual X values

**Matplotlib version**
  * Operating system: Ubuntu 18.04 LTS
  * Matplotlib version:  3.1.0
  * Matplotlib backend : TkAgg
  * Python version: 3.6.7
Installed with pip3

**Comment by timhoffm** [comment]
The point seems indeed to be missing:
~~~
plt.xscale("symlog")
plt.scatter(x, y)
plt.xlim(left=0.9)
plt.ylim(bottom=0.5)
plt.show()
~~~

![grafik](https://user-images.githubusercontent.com/2836374/57986761-5c51b180-7a79-11e9-9dc4-4cd2edcbdee4.png)

**Comment by efiring** [comment]
The bug is specific to scatter; using plot, the two left-hand points are included.
With scatter, the points are plotted if one starts with the `scatter` call before the `xscale`, and then they disappear upon calling `xscale("symlog") even though the view limits remain large enough to include them.

**Comment by dstansby** [comment]
I can boil the example down to the following, where no data is shown in the plot at all:

```python
import matplotlib.pyplot as plt

x = [1.0000e+00, 2.0000e+00]
y = [0.57583333, 0.73833333]

plt.xscale("symlog")
plt.scatter(x, y)
plt.show()
```

**Comment by dstansby** [comment]
And the change that stopped this working bisects cleanly to https://github.com/matplotlib/matplotlib/commit/e959692e42f08c6e157632cf208a6fd19d4228b1 by @efiring ; my guess is that some points are now being masked that shouldn't be.

**Comment by efiring** [comment]
The missing points are those in the linear range of the symlog transformation. (The default linear range is -2 to 2.)  As I noted in a review comment reply in #14281, this points to a strange interaction between symlog and scatter that is revealed, not caused, by e959692.

**Comment by efiring** [comment]
I think I see the problem in SymmetricalLogTransform.

**Comment by tbarbette** [comment]
Thanks for the quick support guys!
