### ISSUE TITLE
SpanSelector does not work when used in method

### ISSUE THREAD

**Issue by ChristianF88** [matplotlib/matplotlib#14276]
Hi there,

I don't know how to get the SpanSelector working when the plot is created within a class definition. The plot is created but loses it's interactive capabilities. To illustrate this issue I simply put a standard example into a class definition. Has anybody any ideas?

Thanks in advance!!

**Working example:**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector

# Fixing random state for reproducibility
np.random.seed(19680801)

fig, (ax1, ax2) = plt.subplots(2, figsize=(8, 6))
ax1.set(facecolor='#FFFFCC')

x = np.arange(0.0, 5.0, 0.01)
y = np.sin(2*np.pi*x) + 0.5*np.random.randn(len(x))

ax1.plot(x, y, '-')
ax1.set_ylim(-2, 2)
ax1.set_title('Press left mouse button and drag to test')

ax2.set(facecolor='#FFFFCC')
line2, = ax2.plot(x, y, '-')


def onselect(xmin, xmax):
    indmin, indmax = np.searchsorted(x, (xmin, xmax))
    indmax = min(len(x) - 1, indmax)

    thisx = x[indmin:indmax]
    thisy = y[indmin:indmax]
    line2.set_data(thisx, thisy)
    ax2.set_xlim(thisx[0], thisx[-1])
    ax2.set_ylim(thisy.min(), thisy.max())
    fig.canvas.draw()

# Set useblit=True on most backends for enhanced performance.
span = SpanSelector(ax1, onselect, 'horizontal', useblit=True,
                    rectprops=dict(alpha=0.5, facecolor='red'))


plt.show()
```

**My code:**

```python

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector


# Fixing random state for reproducibility
np.random.seed(19680801)
class SpanTest():
    def plot(self):
        fig, (ax1, ax2) = plt.subplots(2, figsize=(8, 6))
        ax1.set(facecolor='#FFFFCC')

        x = np.arange(0.0, 5.0, 0.01)
        y = np.sin(2*np.pi*x) + 0.5*np.random.randn(len(x))

        ax1.plot(x, y, '-')
        ax1.set_ylim(-2, 2)
        ax1.set_title('Press left mouse button and drag to test')

        ax2.set(facecolor='#FFFFCC')
        line2, = ax2.plot(x, y, '-')


        def onselect(xmin, xmax):
            indmin, indmax = np.searchsorted(x, (xmin, xmax))
            indmax = min(len(x) - 1, indmax)

            thisx = x[indmin:indmax]
            thisy = y[indmin:indmax]
            line2.set_data(thisx, thisy)
            ax2.set_xlim(thisx[0], thisx[-1])
            ax2.set_ylim(thisy.min(), thisy.max())
            fig.canvas.draw()

        # Set useblit=True on most backends for enhanced performance.
        span = SpanSelector(ax1, onselect, 'horizontal', useblit=True,
                            rectprops=dict(alpha=0.5, facecolor='red'))


        plt.show()
        
st = SpanTest()
st.plot()
```

**Matplotlib version**

  * Operating system: **Ubuntu 18.04**
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): **TkAgg**
  * Python version: **3.6**
  * Jupyter version (if applicable):
  * Other libraries: **numpy-version -> 1.16.3**

I installed matplotlib via pip. I'm not using conda.

Thank you very much!
Have a great one!
Christian

**Comment by ImportanceOfBeingErnest** [comment]
The code when run as script works fine. You might be running it in some kind of interactive environment (e.g. IPython) where interactive mode is turned on. This will lead to `plt.show()` to be non-blocking, and hence the class' `plot()` function to return. At that point, no reference is kept to  `span`, which is subsequently garbage collected. 

The [`SpanSelector`](https://matplotlib.org/api/widgets_api.html#matplotlib.widgets.SpanSelector) documentation puts this as follows:

> To guarantee that the selector remains responsive, keep a reference to it.

In your case, the easiest to do so is to make it an instance variable: `self.span = SpanSelector(..)`

**Comment by ChristianF88** [comment]
Thanks a lot, especially for the quick answer. Your absolutely right. 

Have a great day!
