### ISSUE TITLE
Docs: Axes.inset_rectangle is referred to but does not exist

### ISSUE THREAD

**Issue by clbarnes** [matplotlib/matplotlib#14275]
The [documentation page](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.indicate_inset_zoom.html) for `Axes.indicate_inset_zoom` explains the method's kwargs by referring to another method, `Axes.inset_rectangle`. However, this method does not exist in matplotlib 3.0.x or 3.1.x, and no documentation page can be found by the page search.

**Comment by clbarnes** [comment]
Additionally, in the docs for `Axes.indicate_inset_zoom` the return value `connector_lines` claims to be a 4-tuple, but is actually a list.

**Comment by timhoffm** [comment]
Closed by #14278.
