### ISSUE TITLE
RendererSVG CSS 'white-space' property conflicts with default HTML CSS

### ISSUE THREAD

**Issue by aodin** [matplotlib/matplotlib#14283]
### Bug report

**Bug summary**

The CSS 'white-space' property was added to the SVG renderer by https://github.com/matplotlib/matplotlib/pull/13674. This property's value, however, conflicts with the default CSS [`white-space` value](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

**Code for reproduction**

Create a basic plot and render it to SVG:

```python
from matplotlib import pyplot

pyplot.plot([1, 2, 3, 4])
pyplot.savefig(
    'example.svg',
    format='svg'
)
```

Embed the saved SVG into an HTML file and view. Here is a gist with a full example https://gist.github.com/aodin/4292cfeabe9107d0fd7d15c79062bb22

**Actual outcome**

As you can see from the screenshot below, the `white-space` property set by the SVG renderer affects the whole HTML page, overriding the default `white-space` value.

<img width="350" alt="matplotlib-whitespace-svg" src="https://user-images.githubusercontent.com/566614/58055939-a2138600-7b1c-11e9-9f26-dc7f3b471c36.png">

**Expected outcome**

The SVG renderer should not set a CSS property that conflicts with default values.

<img width="350" alt="matplotlib-whitespace-svg-expected" src="https://user-images.githubusercontent.com/566614/58055940-a2138600-7b1c-11e9-9d72-4263a8e8dbae.png">

The above image was made by changing the CSS property name to `svg white-space`. I do not know any way to make the CSS properties set within the SVG to be non-global. Additionally, I do not see an easy way to change the default CSS properties set by https://github.com/matplotlib/matplotlib/blob/d4ce99a88e68c2dde9635685aa0ebb0a5df3af0e/lib/matplotlib/backends/backend_svg.py#L318

While it is possible to override the new value on the HTML page with `* {white-space: normal !important;}`, this is a regressive override likely to cause additional CSS issues.

In the future, I ask that developers please consider the use case of embedding rendered SVG before altering CSS defaults.

**Matplotlib version**

  * Operating system: macOS 10.14.4 (18E226)
  * Matplotlib version: matplotlib==3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.7.3

Python was installed via the latest macOS installer. A virtualenv was created without site-packages and used to install matplotlib via `pip install matplotlib`

**Comment by tacaswell** [comment]
Huh, the style sheet must propagate out (see https://www.w3.org/TR/SVG2/styling.html#StyleSheetsInHTMLDocuments), that is rather surprising to me...

Is there a way we can use selectors to just apply this to text we create?

**Comment by aodin** [comment]
I would recommend inlining the styles on the `svg` element, since all inlined styles are inherited by children, but do not affect the outer document. Example:
```svg
<svg version="1.1" style="stroke-linecap:round;stroke-linejoin:round;white-space:pre" ...>
```
This change, however, will affect those who currently override styles, as [inline styles have highest precedence](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). Only by using the !important` exception could these styles be changed by the outer document.

**Comment by ImportanceOfBeingErnest** [comment]
Would the following work?

```
<svg class="mplsvg">
    <style type="text/css">
        svg.mplsvg {stroke-linecap:butt;stroke-linejoin:round;white-space:pre;}
    </style>
</svg>
```

**Comment by gyohng** [comment]
Jupyter interface gets massively messed up by `white-space:pre` being default for the entire page when used with:
```
%config InlineBackend.figure_formats = ['svg']
```

**Comment by anntzer** [comment]
I don't know enough about css to fix that, but I'm fine with reverting https://github.com/matplotlib/matplotlib/pull/13674 and rebreaking https://github.com/matplotlib/matplotlib/issues/13200 as a stopgap.

**Comment by tacaswell** [comment]
I am :+1: on @anntzer 's plan as something we can get done in the next week for 3.1.1.

**Comment by timhoffm** [comment]
Not a CSS expert, but AFAICS @ImportanceOfBeingErnest's proposal of assigning a class https://github.com/matplotlib/matplotlib/issues/14283#issuecomment-494201577 would work.

- `class` is a valid SVG attribute https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
- This approach effectively restricts the application of CSS

An alternative would be to use `id` and a uuid for it so that also mutliple plots would be isolated. Not sure if that's needed/wanted.
