### ISSUE TITLE
Consider adding a warning to yscale('symlog') when no linthreshy is set

### ISSUE THREAD

**Issue by staadecker** [matplotlib/matplotlib#14297]
I spent several hours trying to figure out why `plt.yscale('symlog')` didn't work.

It would have helped if an error were raised when no `linthreshy` parameter was specified. Just an idea.

**Comment by efiring** [comment]
I don't understand.  The linthresh defaults to 2 and the linscale defaults to 1 when you set either yscale or xscale to 'symlog'.

**Comment by staadecker** [comment]
Ahhh. My data was all between -1 and 1 so when I used `symlog` it gave the impression that nothing worked.

As for a fix, I don't know anymore. What would happen if the default `linethresh` is say `10 ** (-10)`. Would this have side effects?

**Comment by efiring** [comment]
Yes, it would mean that for a data range from -1e5 to 1e5, for example, there would be something like 30 decades.
No default will suit every use case.  I don't expect we will be changing these defaults.

**Comment by staadecker** [comment]
Ok that makes sense. Any ideas on how to make this more intuitive for a beginner (so they don't end up like me). Maybe a warning if all of your graph fits in the default linethresh range since at that point `symlog` has no effect?

**Comment by efiring** [comment]
In my view, symlog is an odd (perhaps "advanced") scale to start with, and it is up to the user to read the documentation.  It looks like the plt.yscale and plt.xscale docs could use a tiny bit of editing to include the default value for the thresholds.  Perhaps additional advice could be added elsewhere in the docs as well.  I would not support adding any sort of warning machinery to the code, however.

**Comment by staadecker** [comment]
Ok that makes sense! I'm closing the issue.
