### ISSUE TITLE
Graph Zooms-Out Due to Cursor Widget axes on a plot with autoscale_view() enabled

### ISSUE THREAD

**Issue by dwij2812** [matplotlib/matplotlib#14307]
### Bug report

**Bug summary**

When Using autoscale_view() for a dynamically Updating plot and using the Cursor Widget with it the graph zooms out abruptly, is there anyway to prevent this as this is being done once the cursor is used on the plot and its ha(Horizontal Axis) and va(Vertical Axis) causing the graph to scale to fit the cursor lines.

**Code for reproduction**

**Matplotlib version**

  * Operating system: Windows 7 (64 Bit)
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):(tkAgg)
  * Python version:3.7.3
  * Jupyter version (if applicable):No
  * Other libraries: numpy

**Comment by dstansby** [comment]
Please could you provide a small self contained example of code that is needed to reproduce this problem?

**Comment by dwij2812** [comment]
This is the example i am trying to work with for my application:
```python
import serial
import time
import csv
import matplotlib
matplotlib.use("tkAgg")
import matplotlib.pyplot as plt
from matplotlib.widgets import Cursor
import numpy as np

ser = serial.Serial('/dev/ttyACM0')
ser.flushInput()

plot_window = 20
y_var = np.array(np.zeros([plot_window]))

plt.ion()
fig, ax = plt.subplots()
line, = ax.plot(y_var)
cursor = Cursor(ax, useblit=True, color='red', linewidth=2)

while True:
    try:
        ser_bytes = ser.readline()
        try:
            decoded_bytes = float(ser_bytes[0:len(ser_bytes)-2].decode("utf-8"))
            print(decoded_bytes)
        except:
            continue
        with open("test_data.csv","a") as f:
            writer = csv.writer(f,delimiter=",")
            writer.writerow([time.time(),decoded_bytes])
        y_var = np.append(y_var,decoded_bytes)
        y_var = y_var[1:plot_window+1]
        line.set_ydata(y_var)
        ax.relim()
        ax.autoscale_view()
        fig.canvas.draw()
        fig.canvas.flush_events()
    except:
        print("Keyboard Interrupt")
        break
```

Explanation:
So, Here i am trying to get some data over a serial port and plot it on the graph by updating it in realtime using the infinite while loop. Hence due to auto scale function when the cursor panes are displayed on the graph the graph automatically starts zooming out to fit the pane axis which are of infinite length in the view of the graph pane.

**Comment by jklymak** [comment]
I'm going to close as pretty old.  Bt if you can make a self-contained (non-serial line) reproducible example, we can reopen.
