### ISSUE TITLE
'ha' and 'va' of axes.set_xlabel() seem useless

### ISSUE THREAD

**Issue by Aquapisces** [matplotlib/matplotlib#14300]
### Bug report

**Bug summary**

When I want to put  xlabel  on the right of x-axis, and ylabel on the top of y-axis, I found it  impossible.

**Code for reproduction**

If I write `ax.set_xlabel('Time')` ，the xlabel is located the center of x-axis.
If I write `ax.set_xlabel('Time',ha='left')`，the xlabel moved a little bit to the right, and is still in the center area of x-axis.
What if I write  `ax.set_xlabel('Time',ha='right')`? The xlabel moved a little bit to the left.

```python
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure("FFF")
ax=fig.add_subplot(111)
ax.set_xlabel('xlabel',ha='left')
x = np.arange(0, 2*np.pi, 0.01)
line=ax.plot(x, np.sin(x))
plt.show()
#
#
```

**Matplotlib version**

  * Operating system:win10-64bit
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):Qt5Agg
  * Python version:3.6.3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
This is because the alignment is inherited from text. As with all texts the alignment aligns the text relative to a given point, which is the center of the axes for axes labels.

**Comment by QuLogic** [comment]
You can set the position of the anchor point using [`Axis.set_label_coords`](https://matplotlib.org/api/_as_gen/matplotlib.axis.Axis.set_label_coords.html):
```
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure("FFF")
ax = fig.add_subplot(111)
ax.xaxis.set_label_coords(0, -0.07)
ax.set_xlabel('xlabel', ha='left')
x = np.arange(0, 2*np.pi, 0.01)
line = ax.plot(x, np.sin(x))
plt.show()
```

**Comment by tacaswell** [comment]
I am going close this as I don't think there is anything we can do on the Matplotlib side.

We do have one example of using `set_label_coords` (https://matplotlib.org/gallery/pyplots/align_ylabels.html?highlight=set_label_coords) but it is a bit obsure for the use-case here.  I would be happy to merge an example more illustrative of this case, but do not think we should need to keep this issue open to track it.

Thank you for reporting this @Aquapisces .  If you have more questions please follow up on the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users).

**Comment by jklymak** [comment]
I don’t k is that it would be crazy to let set_xlabel take a position argument.

**Comment by timhoffm** [comment]
The position argument would probably be called `loc` in resemblence of `set_title()' and `legend()`.
