### ISSUE TITLE
Unable to import matplotlib on Windows 10 v1903

### ISSUE THREAD

**Issue by jonascj** [matplotlib/matplotlib#14303]
### Bug report
```import matplotlib``` fails with `ImportError: DLL load failed` as shown here: https://i.imgur.com/e3UyE1h.png 

In the end it turns out to be module kiwisolver which does not import properly.

This is on a fresh installation of Windows 10 (see version below), fresh install of Python 3.7.3, tried several times over. 

**Matplotlib version**
  * Operating system: Windows 10 version 1903 (May 2019) 64bit
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Not able to import
  * Python version: 3.7.3 (32bit)
  * Other libraries: pip 19.0.3, kiwisolver 1.1.0.

Python installed from Windows-installer from python.org. Matplot lib installed via `pip install matplotlib`.

**Comment by jonascj** [comment]
Fixed by installing Microsoft Visual C++ 2015 redistributable. Some dependencies for precompiled binaries must have been missing.

And again, maybe this is more a kiwisolver issue than a matplotlib issue.

**Comment by jklymak** [comment]
Reopening though maybe the correct fix is on kiwis end.

**Comment by tacaswell** [comment]
Closing this as #14316 has been merged.

**Comment by snjay5** [comment]
Hi,

I dont have admin rights on my PC hence I am not able to install Microsoft Visual C++ 2015 redistributable.
Which leads to the failing of matplotlib installation. Is there any other way around?
