### ISSUE TITLE
No Autocomplete for `matplotlib.pyplot.figure`

### ISSUE THREAD

**Issue by clsmt** [matplotlib/matplotlib#14312]
### Bug report

**Bug summary**

No autocomplete for `matplotlib.pyplot.figure` in python 3.

**Code for reproduction**

```python
from matplotlib import pyplot as plt

fig = plt.figure()
fig.
```

**Actual outcome**

No autocomplete pop up as you type.

**Expected outcome**

Autocomplete

**Matplotlib version**

  * Operating system: win
  * Matplotlib version:  3.0.3
  * Python version: 3.6

**More info**
Related: https://youtrack.jetbrains.com/issue/PY-35981
Possibly because
Python 2.7:
```
    Returns
    -------
    figure : Figure
```
vs

Python 3.7:
```
    Returns
    -------
    figure : `~matplotlib.figure.Figure`
```
Not sure if this is a problem in pycharm only, or with other ide as well.

**Comment by clsmt** [comment]
... is it just me? no one else has the same issue?

**Comment by WeatherGod** [comment]
I think you need to raise this issue with the pycharms people. How IDEs do their auto-completion is not our concern (for the most part). The documentation follows a standard format.

**Comment by WeatherGod** [comment]
now, if the pycharms people can point out a particular problem with our documentation, then that can certainly be raised as a bug here, but for the moment, I don't see a bug in how we document Figure objects.

**Comment by jklymak** [comment]
Completion works in `python` so agree this is definitely a pycharm issue and should be taken up with them.

**Comment by clsmt** [comment]
> Completion works in `python` so agree this is definitely a pycharm issue and should be taken up with them.

You mean Ipython? 

> now, if the pycharms people can point out a particular problem with our documentation, then that can certainly be raised as a bug here, but for the moment, I don't see a bug in how we document Figure objects.

THanks for the clarification, is there an IDE that provides autocompletion for matplotlib in python3? I don't have to use pycharm. Thanks!

**Comment by timhoffm** [comment]
> Completion works in `python` so agree this is definitely a pycharm issue and should be taken up with them.

Just as a side remark: REPLs like python/ipython evaluate the line `plt.figure()`. So `fig` is an actual `Figure` instance there, that can be queried for it's method. In contrast, IDEs have to infer that the result of `plt.figure()` is as `Figure` by static code and/or docstring analysis. These are two completely separate pairs of shoes.

**Comment by clsmt** [comment]
> Just as a side remark: REPLs like python/ipython evaluate the line `plt.figure()`. So `fig` is an actual `Figure` instance there, that can be queried for it's method. In contrast, IDEs have to infer that the result of `plt.figure()` is as `Figure` by static code and/or docstring analysis. These are two completely separate pairs of shoes.

Thanks, I should have specified that I meant the autocomplete in the integrated text editor, not in the ipython command line.

**Comment by sweese** [comment]
Autocomplete doesn't work for figure objects in Jupyter Notebook also.

**Comment by tacaswell** [comment]
This is using sphinx's markup for specifying which class will be returned https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/domains.html#role-py:obj  This should be reported to what ever project is parsing the docstrings insufficiently.

**Comment by stavna** [comment]
> ... is it just me? no one else has the same issue?

Got the same problem here with matplotlib 3.1.3 on pycharm pro 2019

I downgraded matplotlib to 2.2.5 and the problem was fixed.

I'm looking now for the latest stable version pycharm's autocomplete will work

**Comment by timhoffm** [comment]
Follow up discussion in #17190.
