### ISSUE TITLE
Improvement: Better error message if kiwisolver fails to import

### ISSUE THREAD

**Issue by jonascj** [matplotlib/matplotlib#14315]
I had the frustrating experience of trying to install matplotlib on a fresh/clean installation of Windows 10 the other day, for hours on end the `import matplotlib` failed with `ImportError: DLL load failed`. 

It turned out to be kiwisolver, which was missing Microsoft Visual C++ Redistributable 2015/2017. 

In `_check_versions()` in `lib/matplotlib/__init__.py` could catch the exception and show a hint like: `You likely miss Microsoft Visual C++ Redistributable 2015/2017`.

**Comment by jonascj** [comment]
Submitted a PR to implement this: https://github.com/matplotlib/matplotlib/pull/14316

**Comment by anntzer** [comment]
Closed by #14316.
