### ISSUE TITLE
wrong alpha and mistaken colored area

### ISSUE THREAD

**Issue by euhruska** [matplotlib/matplotlib#14314]
**Bug summary**
Couple of points are in wrong alpha and small area around them is mistakenly colored.
**Actual outcome**
I plot points in light blue color and 99% it works, but a couple of the points are full blue color. This is unexpected since every single point I draw has alpha=0.5, as seen in the code.
There is no error message, but I'm plotting 5 million points, so maybe that's causing it.
Shapely claimed it's caused by matplotlib. https://github.com/Toblerity/Shapely/issues/719

![transparent_fail](https://user-images.githubusercontent.com/9983894/58352181-78b26d00-7e30-11e9-9e48-ee43bc842b40.PNG)

**Expected outcome** 
When I'm not using shapely, but otherwise similar setting without alpha that area looks like below. One can identify the wrong-colored points as the point which are encircled by other points. Shapely also colored in that white area, so that's another error.
![no_transparent_correct](https://user-images.githubusercontent.com/9983894/58352379-fa09ff80-7e30-11e9-8651-e0201ac247c8.PNG)

## code
```
n_here=all_Y1.shape[0]
size = 0.02
polygons1=[]
for i in range(n_here):
  polygon1=Point(all_Y1[i, 0], all_Y1[i, 1]).buffer(size)
  polygon1=shapely.affinity.scale(polygon1,1,ratioxy, origin=(all_Y1[i, 0], all_Y1[i, 1]))
  polygons1.append(polygon1)#_here)]

polygons1 = cascaded_union(polygons1)
for polygon1 in polygons1:
    #polygon1 = shapely.affinity.scale(polygon1,1,ratioxy)
    polygon1 = matplotlib.patches.Polygon(np.array(polygon1.exterior), facecolor="blue", lw=0, alpha=0.5)
    res[1].add_patch(polygon1)
```

**Matplotlib version**
  * Operating system: Red Hat Enterprise Linux Workstation release 7.6
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.7.3
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 
shapely 1.6.4
installed with conda

**Comment by jklymak** [comment]
Can you reproduce w/o shapely and with something we can run?  Otherwise going to be pretty hard to debug!

**Comment by euhruska** [comment]
I got it reproducible with shapely. I draw a  shapely points in a circle shape and one point in the middle, then I get the error. It's filled in and the center if full blue, even though it should be not filled in and cneter point light blue. If the circle is open there is no error.
```
import numpy as np
import matplotlib
matplotlib.use('Agg')
from matplotlib.pyplot import *
import matplotlib.pyplot as plt
from shapely.geometry import Point
from shapely.ops import cascaded_union
def reproduce(part=2, n=1000, size=0.01):
    polygons1=[Point(0.5+0.4*np.cos(i), 0.5+0.4*np.sin(i)).buffer(size) for i in list(np.arange(0,part*np.pi,0.01))]
    polygons1=polygons1+[Point(0.5,0.5).buffer(size)]
    polygons1 = cascaded_union(polygons1)
    fig = plt.figure(figsize=(10,10))
    
    ax = fig.add_subplot(111)
    for polygon1 in polygons1:
        #polygon1 = shapely.affinity.scale(polygon1,0.3,2)
        polygon1 = matplotlib.patches.Polygon(np.array(polygon1.exterior), facecolor="blue", lw=0, alpha=alpha)  
        ax.add_patch(polygon1)
    if part==2:
      plt.savefig('/scratch1/eh22/fail.png')
    else:
      plt.savefig('/scratch1/eh22/ok.png')

reproduce(part=1) #correct
reproduce(part=2)# wrong
```

correct plot:
![ok](https://user-images.githubusercontent.com/9983894/58357005-d3eb5c00-7e3e-11e9-95b7-a8b38102ba2d.png)
wrong plot:
![fail](https://user-images.githubusercontent.com/9983894/58357014-dd74c400-7e3e-11e9-92dc-d95102f095a5.png)

**Comment by euhruska** [comment]
ok, looks like an issue on my side. I draw only the polygon exterior, not the interior, so it fills in the whole circle.

**Comment by jklymak** [comment]
Maybe you can make a simple example just using `matplotlib.patches.Polygon` and then see what is causing the error?

**Comment by euhruska** [comment]
Had to use both the exterior and the interior boundary as input for the polygon, solved
