### ISSUE TITLE
Deprecate unused testing cleanup mechanisms

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#14329]
The class `matplotlib.testing.decorators.CleanupTestCase` and the decorator `matplotlib.testing.decorators.cleanup` are not used in the code base. We have an automatic cleanup via an auto-used fixture instead.

Can we deprecate them or are they considered part of the user-facing API for testing?

**Comment by anntzer** [comment]
matplotlib.testing is written in a (somewhat) testing-framework-agnostic way.  I don't think pytest really risks going away anytime soon, but I think it would be nice to keep some equivalent functionality that's independent of pytest (in fact I have a PR in the works to make more of the testing tooling independent of pytest, while makings things shorter :)).

**Comment by jklymak** [comment]
@anntzer  has plans for this so lets keep around.
