### ISSUE TITLE
`TypeError: float() argument must be a string or a number`, not 'Period'

### ISSUE THREAD

**Issue by cartman12** [matplotlib/matplotlib#14359]
### Bug report

**Bug summary**

Error when plotting date series after using pd.to_datetime()

`TypeError: float() argument must be a string or a number`, not 'Period'

**Code for reproduction**
After converting time series in pandas using `pd.to_datetime(df['column'], format = '%Y%m%d%H') `

train.plot(x='ds', y='y', color='blue', label='Train', figsize=(16,4))

```python
# df = pd.to_datetime(df['ds'], format = '%Y%m%d%H') 
# df = df.set_index('ds')
# train = [2015:2018]
# train = train.reset_index()
# train.plot(x='ds', y='y', color='blue', label='Train', figsize=(16,4))

```

**Actual outcome**

Error

```
# If applicable, paste the console output here
# `TypeError: float() argument must be a string or a number`, not 'Period'
#
```

**Expected outcome**
A plot

 3.0.1

**Matplotlib version**

Colab

Yes

**Comment by jklymak** [comment]
Can you make this self contained, and preferably w/o pandas.  If you really need to use pandas, also please make sure that this is not a pandas issue.  Thanks!

**Comment by cartman12** [comment]
I think i jumped to fast on this, issue was in Prophet plot.py code, they used `pandas.plotting.deregister_matplotlib_converters()`

**Comment by ruiyuh-work** [comment]
I got the same issues.  I don't think it is related to the Prophet. It happened after setting DATE as the index.
