### ISSUE TITLE
required interactive framework error on Backend attribute on matplotlib V3.0.3

### ISSUE THREAD

**Issue by aktaseren** [matplotlib/matplotlib#14364]
Hi guys,

As I am running below codes, I am getting " AttributeError: type object 'Backend' has no attribute 'required_interactive_framework' ". 

import statsmodels.api as sm
test = pd.DataFrame({"prediction": pred, "observed": y_validation.flatten()})
lowess = sm.nonparametric.lowess
z = lowess(pred.flatten(), y_validation.flatten())
test.plot(figsize = [14,8],
          x ="prediction", y = "observed", kind = "scatter", color = 'darkred')
plt.title("KNN: Prediction Vs Test Data", fontsize = 18, color = "darkgreen")
plt.xlabel("Predicted Power Output", fontsize = 18) 
plt.ylabel("Observed Power Output", fontsize = 18)
plt.plot(z[:,0], z[:,1], color = "blue", lw= 3)
plt.show()

Do you have any suggestion that can solve my issue?

Cheers,

**Comment by tacaswell** [comment]
Can you please fill out

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries: 


My knee-jerk guess is that your enviroment is corrupted and you have over-lapping installations of different versions of mpl.

**Comment by aktaseren** [comment]
Thanks a lot, @tacaswell. Your knee-jerk guess solved the issue I have on MLP. I uninstalled and installed. After restarting the conda, the trouble was gone.
