### ISSUE TITLE
button doesn't work with a live plot 

### ISSUE THREAD

**Issue by rachedZAKHAMA** [matplotlib/matplotlib#14367]
Hi,

I was trying to make a live plot with tkinter where I can see the data updating live in a for loop. I used a tkinter window to plot the matplotlib figure and I added a button. The problem is that I can't make the button work during the for loop.

My example is :

```python
##############################

# imports

import numpy as np
from time import sleep
import matplotlib
matplotlib.use("TkAgg")
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
from matplotlib.figure import Figure
from matplotlib.pyplot import pause
import tkinter as tk

fenetre = tk.Tk()
# update function , called whenever the user hit the button : changes the plot line color
def update():
    n=np.random.randint(4)
    colors=['b','g','r','c']
    l.set_color(colors[n])
    canvas.show()
# tkinter button, changes the line color
bouton = tk.Button(fenetre, text="change color", command=update)
bouton.pack()
# create random data
x=np.array([i for i in range(10)])
y=np.random.randn(10)
# create matplotlib figure and plot
fig=Figure(figsize=(5,5))  
ax=fig.add_subplot(111)
l,=ax.plot(x,y)
# put the figure in the tkinter window
canvas=FigureCanvasTkAgg(fig,fenetre)
canvas.show()
canvas.get_tk_widget().pack(side=tk.TOP,fill=tk.BOTH, expand=True)
# add the toolbar
toolbar= NavigationToolbar2TkAgg(canvas,fenetre)
toolbar.update()
canvas._tkcanvas.pack(side=tk.TOP,fill=tk.BOTH, expand=True)

# update random data every  2 seconds
for i in range(15):
    sleep(2)
    y=np.random.randn(10)
    l.set_ydata(y)
    canvas.show()


tk.mainloop()

######################
```
**Expected outcome**

I am trying to see a plot of random data changing on the screen every 2 seconds and change its color whenever I hit the button. It doesn't work since apparently Python  doesn't execute the button  command before finishing the loop.

Do you have any suggestions?
**versions**
I'm running the code on a jupyter notebook with: 
  * Operating system: windows
  * Matplotlib version: '2.1.2'
  * Matplotlib backend: I'm using  'TkAgg'
  * Python version: 3.6.4 
  * Jupyter version: 5.4.0 installed via Anaconda 
  
Best regards,
Rached.

**Comment by tacaswell** [comment]
I edited the OP to add code markup.

**Comment by tacaswell** [comment]
@rachedZAKHAMA See https://github.com/matplotlib/matplotlib/pull/4779 for a long discussion of event loops.

In very short, tk buttons won't respond if the tk main loop is not running to process them.  Before you start the tk main loop you are running the loop with the `sleep` in it which effectively blocks the process.

You can either run the main loop for a period of time (trace through why `plt.pause` is doing) in your loop or make use of Tk timers for the periodic update.   Given that it looks like you are working on a stand-alone application with embedded Matplotlib, the second option is probably better in the long run.



---

https://github.com/matplotlib/matplotlib/blob/f1975a7efddef12c78c2221c0986ed08614d810d/lib/matplotlib/pyplot.py#L291-L314

**Comment by rachedZAKHAMA** [comment]
For the Tk timers, I don't think it is a good idea in my case because I must keep the loop for a later version of my code. 
I replaced sleep(2) by pause(2)
I still can't click the button when the loop is running  :/

**Comment by jklymak** [comment]
Closing as quite old, and I don't think there is an action here.  Follow up on https://discourse.matplotlib.org if there is further discussion...
