### ISSUE TITLE
xlim  none

### ISSUE THREAD

**Issue by HuangQinJian** [matplotlib/matplotlib#14365]
```
fig = plt.figure()
plt.xlabel('Epoch')
plt.ylabel("Accuaracy")
plt.plot([0.1111, 0.21111], label='train', color='r', linestyle='-', alpha=0.5)
plt.plot([0.1111, 0.21111], label='valid', color='b', linestyle='-', alpha=0.5)
plt.legend(loc="upper right")
plt.xlim(1, 2)
plt.ylim(0, 1)
fig.savefig('Accuaracy_fine-tune_resnet.jpg')
```

But the output is empty:

![image](https://user-images.githubusercontent.com/20330704/58560311-70ef3000-8257-11e9-9cd8-8164b720639b.png)

if I delete, it is ok :
```
plt.xlim(1, 2)
plt.ylim(0, 1)
```

version  3.0.2

**Comment by jklymak** [comment]
You don’t have any data between x =1 and 2.

**Comment by HuangQinJian** [comment]
> You don’t have any data between x =1 and 2.

I modify it to

```
fig = plt.figure()
plt.xlabel('Epoch')
plt.ylabel("Accuaracy")
plt.plot([1.1111, 0.21111], label='train', color='r', linestyle='-', alpha=0.5)
plt.plot([1.1111, 0.21111], label='valid', color='b', linestyle='-', alpha=0.5)
plt.legend(loc="upper right")
plt.xlim(1, 2)
plt.ylim(0, 1)
fig.savefig('Accuaracy_fine-tune_resnet.jpg')
```

It aslo empty

**Comment by WeatherGod** [comment]
You are doing a line plot with a single data point and no markers. That's
why you aren't seeing anything.

**Comment by ImportanceOfBeingErnest** [comment]
Notice the difference between

* `plt.plot(x,y)`, which would plot a single point at coordinates (x,y)
* `plt.plot([y1,y2])`, which would plot a line between the two points `(0, y1)` and `(1,y2)`. In order for this line to be seen the x limits need to (partially) include the range [0,1], and the y limits need to include [y1,y2].

So use `plt.xlim(-1,2); plt.ylim(0,1)` to see the line. Then change those to your liking.
