### ISSUE TITLE
Add link to style examples in matplotlib.style documentation

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#14362]
The documentation for `matplotlib.style` isn't very helpful for those wanting to use a style sheet, but there are some helpful examples in the example gallery. It would be good to add a link to these examples at the top of the `matplotlib.style` doc page.

- `matplotlib.style` page: https://matplotlib.org/devdocs/api/style_api.html?highlight=style#module-matplotlib.style
- Style examples: https://matplotlib.org/devdocs/gallery/index.html#style-sheets

**Comment by m-happy** [comment]
Hello @dstansby  Can I work on this issue if this is not resolved.

**Comment by dstansby** [comment]
Yes, you definitely can - let me know if you have any questions.

**Comment by Kusal-Pasupuleti** [comment]
Hello @dstansby Can I work on this issue if this is not resolved?

**Comment by m-happy** [comment]
Hey Kunal, can you choose some other issue I have been working on this.
