### ISSUE TITLE
Bug in "jet" colormap?

### ISSUE THREAD

**Issue by mizuno-gsinet** [matplotlib/matplotlib#14361]
### Bug report

**Bug summary**

https://github.com/matplotlib/matplotlib/blob/e2b581abb0159a0c6f7879e8392a8b00662ec7e1/lib/matplotlib/_cm.py#L245-L250

"jet" colormap maps values in [0.11, 0.125] to the same color, rgb(0, 0, 1). Shouldn't it be an injective map?

**Comment by QuLogic** [comment]
The Matlab colormap defaults to 64 bins, 1 / 64 = 0.015625 and 0.125 - 0.11 = 0.015, so this is likely the limits of that quantization.

**Comment by mizuno-gsinet** [comment]
@QuLogic Is it the same one as MATLAB's? I can't confirm as I don't have access to it.

**Comment by WeatherGod** [comment]
technically speaking, it is the same one as IDL's jet colormap. In
discussions with John Hunter about the origins of the jet colormap in
matplotlib, he noted that he didn't add it, but another user did, and I
checked with that user and he said that he didn't have access to Matlab at
that time, but was using IDL.

**Comment by jklymak** [comment]
I'm going to close as I don't think there is a bug here, but please continue the discussion....
