### ISSUE TITLE
gcc error when building matplotlib dev from source

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#14370]
### Bug report

**Bug summary**

Failed to build dev version of `matplotlib` from source. Example log: https://travis-ci.org/astropy/astropy/jobs/538721543

```
set build/lib.linux-x86_64-3.7/matplotlib/_version.py to '3.1.0+955.ge2b581abb'
    running build_ext
    building 'matplotlib.ft2font' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -std=c99 -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/home/travis/miniconda/envs/test/lib/python3.7/site-packages/numpy/core/include -I/home/travis/miniconda/envs/test/include/python3.7m -c src/checkdep_freetype2.c -o build/temp.linux-x86_64-3.7/src/checkdep_freetype2.o -I/usr/include/freetype2
    src/checkdep_freetype2.c:1:45: error: missing binary operator before token "("
     #if defined __has_include && ! __has_include(<ft2build.h>)
                                                 ^
    src/checkdep_freetype2.c:15:11: note: #pragma message: Compiling with FreeType version 2.5.2.
       #pragma message("Compiling with FreeType version " \
               ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/travis/miniconda/envs/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-cbwrywg3/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hmjgqamm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-cbwrywg3/matplotlib/
```

We did not see this error when CI ran 20 hours ago; https://travis-ci.org/astropy/astropy/jobs/538455547 failed with something else that was unrelated to `matplotlib`. But definitely was happening 4 hours ago (https://travis-ci.org/astropy/astropy/jobs/538718110).

**Code for reproduction**

Here is how our CI pick up dev version of `matplotlib`:

https://github.com/astropy/ci-helpers/blob/d9cd38228f30cf939bb47ef5e07175421f87ac33/travis/setup_dependencies_common.sh#L605-L617

**Actual outcome**

See logs posted in summary above.

**Expected outcome**

Successful build of `matplotlib` dev.

**Matplotlib version**

  * Operating system: Ubuntu 4.8.4-2ubuntu1~14.04.3
  * Matplotlib version: 3.1.0+955.ge2b581abb
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg (https://github.com/astropy/astropy/blob/62f1ac1726e57facf922eab9fa3ee36b03aa8a2d/astropy/conftest.py#L37)
  * Python version: 3.6 and 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries: https://github.com/astropy/astropy/blob/62f1ac1726e57facf922eab9fa3ee36b03aa8a2d/.travis.yml#L38

**Comment by pllim** [comment]
Maybe related to #13067 ?

**Comment by anntzer** [comment]
Likely.  Does changing _checkdep_freetype2.h to
```
#if defined __has_include
  #if __has_include(<ft2build.h>)
    #error "FreeType version 2.3 or higher is required. \
You may set the MPLLOCALFREETYPE environment variable to 1 to let \
Matplotlib download it."
  #endif
#endif

#include <ft2build.h>
#include FT_FREETYPE_H

#define XSTR(x) STR(x)
#define STR(x) #x

#pragma message("Compiling with FreeType version " \
  XSTR(FREETYPE_MAJOR) "." XSTR(FREETYPE_MINOR) "." XSTR(FREETYPE_PATCH) ".")
#if FREETYPE_MAJOR << 16 + FREETYPE_MINOR << 8 + FREETYPE_PATCH < 0x020300
  #error "FreeType version 2.3 or higher is required. \
You may set the MPLLOCALFREETYPE environment variable to 1 to let \
Matplotlib download it."
#endif
```
(basically, hiding the actual __has_include call under a first #if), and modifying _checkdep_libpng.h in the same manner, fix the problem?
(Given the example at https://en.cppreference.com/w/cpp/feature_test, I *think* this should work.)

**Comment by ajeyaajeya** [comment]
I find the same error on NVIDIA Jetson TX2 

> src/checkdep_freetype2.c:3:6: error: #error "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
     #error "FreeType version 2.3 or higher is required. \
      ^~~~~
src/checkdep_freetype2.c:10:10: error: #include expects "FILENAME" or <FILENAME>
 #include FT_FREETYPE_H
          ^~~~~~~~~~~~~
src/checkdep_freetype2.c:15:9: note: #pragma message: Compiling with FreeType version FREETYPE_MAJOR.FREETYPE_MINOR.FREETYPE_PATCH.
 #pragma message("Compiling with FreeType version " \
         ^~~~~~~
src/checkdep_freetype2.c:18:4: error: #error "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
   #error "FreeType version 2.3 or higher is required. \
    ^~~~~
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by Melikadastranj** [comment]
I get another warning, and i coudnt install this package: 
 fatal error C1189: #error:  "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
How can i handle it

**Comment by RingoTT** [comment]
> I get another warning, and i coudnt install this package:
> fatal error C1189: #error: "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
> How can i handle it

I am getting the same warning and couldnt install matplotlib
Can i get some help on how to change the environmental variable?

**Comment by Melikadastranj** [comment]
> > I get another warning, and i coudnt install this package:
> > fatal error C1189: #error: "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
> > How can i handle it
> 
> I am getting the same warning and couldnt install matplotlib
> Can i get some help on how to change the environmental variable?

Hi there 
I installed some other packages as a prerequisite, also I upgrade my pip.

**Comment by tacaswell** [comment]
@Melikadastranj @RingoTT Please direct questions about installation to https://discourse.matplotlib.org/c/community/install/13

Please include:
 - what version of python you are using and how you got it
 - what version of gcc you are using (and how you got it)
 - how you are trying to install Matplotlib

**Comment by kenneth3000** [comment]
my version of python is python 3.8.2
 as for my version of gcc i don't know what that means

I am trying to install Matplotlib from my Pycharm as shown below using the + sign here
![Matplot method](https://user-images.githubusercontent.com/62405390/77321743-ee1df100-6d12-11ea-8978-1cb65d6e755a.jpg)

i got this error
![Matplotlib error](https://user-images.githubusercontent.com/62405390/77321822-0e4db000-6d13-11ea-85ff-c7896dc6ae75.jpg)

please help out

**Comment by tacaswell** [comment]
@kenneth3000 Can you please open a topic on https://discourse.matplotlib.org/c/community/install/13 with this information including a text version of the full error message from your second image.

**Comment by kenneth3000** [comment]
Thanks, i will do
