### ISSUE TITLE
Add Sponsor button to the repository?

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#14386]
It's now possible to add a `funding.yml` file, that adds a sponsor button to the top of repositories. Should we do this? See https://github.com/sunpy/.github/blob/master/FUNDING.yml for an example.

**Comment by tacaswell** [comment]
Given our financial sponsorship via NF, I will check with them about how we should handle it.  I assume the rest of the sponsored projects will have the same question....

**Comment by dstansby** [comment]
Looks like someone fixed this, thanks to whoever it was.

**Comment by tacaswell** [comment]
It was me via https://github.com/matplotlib/matplotlib/commit/087baf604c53464e739337808547443e45f5fbe8
