### ISSUE TITLE
Index error when use TkAgg in embedded python

### ISSUE THREAD

**Issue by mmmm1998** [matplotlib/matplotlib#14382]
### Bug report
Using TkAgg backend, when the matplotlib code are running in embedded python cause `IndexError` (the backtrace below).
I should mention, that the code, used below, works, when runned via interpreter

Actually, the error appears in `/usr/lib/python3.7/tkinter/__init__.py`,  so if you feel, that this is TKinter bug, tell me and I will move the bug to TKinter bug tracker.

**Code for reproduction**

Crash code (C++).
```cpp
#include <Python.h>

int main()
{
    Py_Initialize();
    const char* command =
        "import matplotlib\n"
        "matplotlib.use('TkAgg')\n"
        "print(matplotlib.get_backend())\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "foo = np.random.rand(10)\n"
        "plt.plot(foo)\n"
        "plt.show()\n";

    PyRun_SimpleString(command);
    Py_Finalize();
    return 0;
}
```

Working equals code (Python 3)
```python3
import matplotlib
matplotlib.use('TkAgg')
print(matplotlib.get_backend())
import numpy as np
import matplotlib.pyplot as plt
foo = np.random.rand(10)
plt.plot(foo)
plt.show()
```

**Actual outcome**

```
TkAgg
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2787, in plot
    return gca().plot(
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 920, in gca
    return gcf().gca(**kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 597, in gcf
    return figure()
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3252, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 946, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2018, in __init__
    baseName = os.path.basename(sys.argv[0])
IndexError: list index out of range
```

**Expected outcome**

```
TkAgg
<matplotlib result image appears>
```

**Matplotlib version**

  * Operating system:
    - Type: Virtual Machine (VirtualBox)
    - Operating System: Manjaro Linux 
    - KDE Plasma Version: 5.15.5
    - KDE Frameworks Version: 5.58.0
    - Qt Version: 5.12.3
    - Kernel Version: 4.19.45-1-MANJARO
    - OS Type: 64-bit
    - Processors: 6 × AMD FX(tm)-8150 Eight-Core Processor
    - Memory: 3,9 ГиБ
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: Python 3.7.3 (default, Mar 26 2019, 21:43:19)

**Comment by timhoffm** [comment]
I found https://docs.python.org/2.0/api/embedding.html
> Py_Initialize() does not set the ``script argument list'' (sys.argv). If this variable is needed by Python code that will be executed later, it must be set explicitly with a call to PySys_SetArgv(argc, argv) subsequent to the call to Py_Initialize(). 

Even though I don't see a corresponding statement in the python 3.7 docs.

Clearly, tkinter expects `sys.argv` to be present and non-empty.

Not an expert on this, but we have something similar here:
https://github.com/matplotlib/matplotlib/blob/4cf397084eab4b8aaeabb5e86095d8e5dd573aa7/lib/matplotlib/__init__.py#L204

As a workaround, you can try adding `sys.argv = ['']` at the top of your script.

**Comment by mmmm1998** [comment]
Yes, you right, I had reread the documentation and `PySys_SetArgv` still needed for Python3, so I close this as resolved.
