### ISSUE TITLE
Strange crash on pyplot into embedded Python

### ISSUE THREAD

**Issue by mmmm1998** [matplotlib/matplotlib#14381]
### Bug report

There is Cantor program - frontend for some mathematical languages including Python 3. Cantor Python backend very simple, there are two programs: Cantor itself and python3server, which run code from Cantor (them communicate via dbus), using embeded python.
Recently, one of Manjaro user create [bug report](https://bugs.kde.org/show_bug.cgi?id=407362) about crashing on simple matplotlib code (see details in the link).

According stacktrace, the crash happends deep inside Python interpreter in PyQt5, when python3server run `plt.show(foo)` command. But this bug are reproduced only on Manjaro. But even on Manjaro I couldn't reproduce it in simple python program and simple PyEmbedded program, so I have no idea, why the bug happends and who could fix it.

Maybe this is matplotlib bug, maybe not, I am not sure. I suspect, that `Qt5Agg` backend, used by default, could interract with python3server, which use Qt5 too.

**Matplotlib version**

  * Operating system:
    - Type: Virtual Machine (VirtualBox)
    - Operating System: Manjaro Linux 
    - KDE Plasma Version: 5.15.5
    - KDE Frameworks Version: 5.58.0
    - Qt Version: 5.12.3
    - Kernel Version: 4.19.45-1-MANJARO
    - OS Type: 64-bit
    - Processors: 6 × AMD FX(tm)-8150 Eight-Core Processor
    - Memory: 3,9 ГиБ
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: Python 3.7.3 (default, Mar 26 2019, 21:43:19)

**Comment by anntzer** [comment]
That seems most likely to be a bug with cantor itself.  Does displaying just a boring QMainWindow (something like `from PyQt5.QtWidgets import *; app = QApplication([]); win = QMainWindow(); win.show(); app.exec_()`) work?

**Comment by mmmm1998** [comment]
@anntzer, thanks for answer.
Your suggestion have been very helpfull, I have found that Cantor crashes on import statement, and after some reasearching, now I am sure, that the problem is conflicts between `PyQt5` embedded Qt libraries (v5.12) and system Qt libraries (v5.9 on my system, for example), which are used in Cantor. So, obvisiously, this is not `matplotlib` problem and now I am closing this bug ticket and creating new on PyQt bug tracker referring on this ticket. I think, you could mark this as upstream problem (because matplotlib use pyqt), if you want.
