### ISSUE TITLE
\iint written twice in docs

### ISSUE THREAD

**Issue by raybellwaves** [matplotlib/matplotlib#14392]
The double integral symbol (\iint) occurs twice in the docs

https://matplotlib.org/users/mathtext.html

I will be happy to delete the duplicate from the file if you can point me to which file I should edit. Thanks.

![Screenshot from 2019-05-30 22-33-35](https://user-images.githubusercontent.com/17162724/58677794-63a37580-832b-11e9-956d-70816a74c87c.png)

**Comment by tacaswell** [comment]
That is a stale page, the current version is at https://matplotlib.org/tutorials/text/mathtext.html and the source is at https://github.com/matplotlib/matplotlib/blob/master/tutorials/text/mathtext.py.

A pull request would be most welcome!

**Comment by xcz011** [comment]
@tacaswell I would like to contribute on this, and this will be my first PR here. Please feel to give any feeback on my PR [https://github.com/matplotlib/matplotlib/pull/14406](url)
