### ISSUE TITLE
ENH: Add HiDPI physical to logical pixel ratio property

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#14405]
When writing figure resizing code to set subplot sizes, HiDPI screens can mess things up if the physical to logical pixel ratio is not accounted for. On the Qt5 backend, there is `fig.canvas. _dpi_ratio` and on MacOSX there is `fig.canvas._device_scale` that expose the physical to logical pixel ratio. This leads to code like this:
```python
    dpi_ratio = 1.
    for key in ('_dpi_ratio', '_device_scale'):
        dpi_ratio = getattr(params["fig"].canvas, key, dpi_ratio)
```
I propose adding a `dpi_ratio` or similar property to `fig.canvas` or perhaps directly `fig`. For most backends it would just be `1.` but Qt5Agg and MacOSX canvases could give their actual values.

Thoughts? I can take a stab at this if it seems worthwhile. Pointers as to the preferred name and whether it should live at the `fig` or `fig.canvas` level welcome.

**Comment by ImportanceOfBeingErnest** [comment]
dpi is an annoying problem. There is lots of discussion in  https://github.com/matplotlib/matplotlib/issues/11227 and https://github.com/matplotlib/matplotlib/pull/11232. So any idea how to get out of that trap are very welcome.
