### ISSUE TITLE
Odd behavior when using `collections.set_color`

### ISSUE THREAD

**Issue by seth-a** [matplotlib/matplotlib#14404]
### Bug report

**Bug summary**

Calling "set_offset" on an object returned by "scatter" causes points to disappear if linewidth=0 was passed as an argument to scatter (although, as far as I can tell, this argument isn't meant to affect scatter).  However, when a breakpoint is placed in the relevant code this does not occur. 
**Code for reproduction**

```python
import pdb
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

matplotlib.interactive(True)

M = 1000
x,y = np.random.randn(2, M)

# create figure with two identical axes
fig = plt.figure()
ax1 = plt.subplot(211)
ax2 = plt.subplot(212)

cmap = matplotlib.cm.get_cmap('viridis')

def test_func(ax, tobreak):
    l = ax.scatter([], [], c=[], linewidth=0)

    if tobreak:
        pdb.set_trace()
    l.set_offsets(np.c_[x, y])
    l.set_color(cmap(np.linspace(0, 1, len(x))))

    # Not necessary, but rules out failure to redraw
    ax.figure.canvas.draw()

    # Set limits to show data
    ax.set_xlim(-3, 3)
    ax.set_ylim(-3, 3)


test_func(ax1, True)
test_func(ax2, False)
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```
![matplotlib_scatter_updates](https://user-images.githubusercontent.com/12515766/58731749-a746bf80-83bd-11e9-9296-29d476056276.png)

**Expected outcome**
At the very least, that placing a breakpoint wouldn't affect the outcome of the code.   Both subplots should update correctly, or neither should.

 Ideally, this should raise an error when linewidth=0 is passed into the initializer, if it is unsupported.  Or, hande updates correctly if that argument is valid.

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: '1.5.1'
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2

**Comment by timhoffm** [comment]
The actual problem is that the points are not filled. If you do `ax.scatter([], [], c=[], linewidth=1)` in your example, you'll get

![image](https://user-images.githubusercontent.com/2836374/59148135-22832380-8a05-11e9-8fe3-57c22e6ca67a.png)

So setting `linewidth=0` makes them invisible.

**Comment by seth-a** [comment]
No, that explains why the points disappear in the second subplot.  However, the bug is that matplotlib's behavior is not consistent.  Your example figure shows a single subplot, if you'd run the example code I gave there would be two subplots.

As stated in the original bug report omitting the linewidth argument gives the desired behavior.  The problem is that the presence of a breakpoint changes that behavior.  In the upper plot (without the breakpoint) the points are not filled.  Running the same code I gave above with `linewidth=1` results in 

![Figure_1](https://user-images.githubusercontent.com/12515766/59150920-cd411500-89f8-11e9-9dc4-6c46aff9978f.png)

So that's better in that the points are visible in both plots. However, in one plot they are solid and the other they are not.  The _only_ difference between the code generating these plots is the presence of a breakpoint.  That should not affect how points are drawn.  I've looked into this a little more, and omitting the argument `c=[]` when first calling scatter causes the correct behavior (shown below, where the subplots are identical).  
![Figure_2](https://user-images.githubusercontent.com/12515766/59151087-696c1b80-89fb-11e9-9e24-90e6a23631ca.png)

This is the correct behavior- two identical calls to maptlotlib _should give identical results_.
So, it seems that the bug originates in  the `c` argument causing scatter to guess at whether edges or faces should be colored in subsequent updates ([this bug](https://github.com/matplotlib/matplotlib/issues/6844/) discusses some of how this is done).  When drawing interactively and taking a break between calls matplotlib guesses wrong.

**Comment by seth-a** [comment]
OK, so the difference in behavior is definitely related to `matplotlib` interactively updating the plot in between creating the `collections` object using `scatter` and updating the offsets and color.  I've replaced the breakpoint with a canvas update (using `ax.figure.canvas.draw()`) and the same inconsistency in behavior continues.

**Comment by timhoffm** [comment]
I can confirm this behavior on master:

*The fill color is not updated if a not-None `c` is passed initally to scatter and no redraw is done.*

@seth-a For the moment, you can redraw as a workaround.

Here is a stripped down example:

~~~
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

x, y = np.random.random((2, 100))

fig, axs = plt.subplots(2, 3, sharex=True, sharey=True)
cmap = matplotlib.cm.get_cmap('viridis')

def test_func(ax, redraw):
    xy = c if c else []
    l = ax.scatter(xy, xy, c=c, linewidth=1)

    if redraw:
        ax.figure.canvas.draw()
    l.set_offsets(np.c_[x, y])
    l.set_color(cmap(np.linspace(0, 1, len(x))))

    # Not necessary, but rules out failure to redraw
    ax.figure.canvas.draw()

for i, c in enumerate([None, [], [0, 1]]):
    test_func(axs[0, i], redraw=False)
    test_func(axs[1, i], redraw=True)
    axs[0, i].set_title('initial c=%s' % c)
    axs[0, 0].set_ylabel('without redraw')
    axs[1, 0].set_ylabel('with redraw')

plt.show()
~~~

![image](https://user-images.githubusercontent.com/2836374/59157490-cde6b380-8aab-11e9-8976-978b06461ae9.png)
