### ISSUE TITLE
am still finding it hard on how to update my matplotlibrc.template in linux. Find errors while running my python program your solutions can absolutely be of a help to me and some other people that might ran inside kinda problem am facing now. Thanks

### ISSUE THREAD

**Issue by Bionic31** [matplotlib/matplotlib#14416]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
@Bionic31 please reformat the issue to have a short readable caption and put the description in the content block.

**Comment by timhoffm** [comment]
Closing due to lack of feedback.
