### ISSUE TITLE
annotate arrow not shown with style 'ggplot' in Jupyter

### ISSUE THREAD

**Issue by aerijman** [matplotlib/matplotlib#14427]
### Bug report

**Bug summary**
Annotate doesn't show the arrow with style 'ggplot' 

**Code for reproduction**
#### In Jupiter lab:
```python
import matplotlib as mpl
%pylab inline

mpl.style.use('ggplot')
plt.annotate('foo', xy=(0, 1), xytext=(0.1,1), arrowprops=dict(arrowstyle="->"))
```

**Matplotlib version**

  * Operating system: MacOS Mojave 10.14.5
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable): 4.4.0
 * Miniconda3, default channel

**Comment by ImportanceOfBeingErnest** [comment]
Do you see the arrow when using the default style (`mpl.style.use('default')`). If so, the grey color of ggplot style may just be too bright?

**Comment by aerijman** [comment]
Yes I do see it using default. How can I resolve that?

**Comment by ImportanceOfBeingErnest** [comment]
Of course you can give the arrow any color you like, e.g. for a red arrow

    plt.annotate('foo', xy=(0, 1), xytext=(0.1,1), arrowprops=dict(arrowstyle="->", color="red"))

Is that what you mean?

**Comment by aerijman** [comment]
Yes, I did it and looks good. 

May I close the issue or you should do it?

Thanks a lot!!
