### ISSUE TITLE
tight_layout() messes up bbox_to_anchor in legend().

### ISSUE THREAD

**Issue by sorenwacker** [matplotlib/matplotlib#14432]
### Bug report

I want to plot something with the legend outside the figure. I am using 
    
     legend(bbox_to_anchor=(1.2, 1))

To position the legend and then I have to do 

     tight_layout()

To make sure the plot is complete when saved to a file.

Unfortunately, tight_layout() pushes the legend into the figure no matter what values I put in the legend function. 

It would be nice to have more convenient ways to postion the legend beside or even above or below the figure.

**Comment by jklymak** [comment]
This will be provided by https://github.com/matplotlib/matplotlib/pull/13072

**Comment by rcomer** [comment]
This was done in #19743 I think.
