### ISSUE TITLE
ipdb forcing interactive mode/ not plotting in new updates

### ISSUE THREAD

**Issue by cgrudz** [matplotlib/matplotlib#14444]
### Bug report

Hey Y'all,

I just made a full conda update all a few days ago so I'm not sure which packages have updated, and where the bug might be originating since the update.  The issue that I encountered was in using ipython debugger in a plotting script.  When running this previously (without any ipdb traces set) the plotting script would run to the point of a show command and work fine.  Now when ipdb is imported (at all, traces or no), the script runs but fails to show the figure and exits.  This issue is eliminated when I comment the ipdb import command.

**Bug summary**

I think ipdb is forcing interactive mode in matplotlib and then this ignores the final plot command when running a plot from a script with ipdb imported.  Running this script from command line results in the script concluding without a plot showing.

**Code for reproduction**

Below is the non-working script, run from command line with python test.py

```python
from matplotlib import pyplot as plt
import ipdb

fig = plt.figure(figsize=(12,8))
ax1 = fig.add_axes([.1, .1, .8, .8])

ax1.plot(range(10), range(10))

plt.show()

```
If the import of ipdb is commented, this works fine from command line with python test.py

```python
from matplotlib import pyplot as plt
#import ipdb

fig = plt.figure(figsize=(12,8))
ax1 = fig.add_axes([.1, .1, .8, .8])

ax1.plot(range(10), range(10))

plt.show()
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```
The  outcome is that the script runs without a plot showing and exits.

**Expected outcome**

This should show a figure of a straight line, which is successful whenever import ipdb is commented out.

**Matplotlib version**

  * Operating system: Ubuntu 18.04 64 bit
  * Matplotlib version: matplotlib                3.1.0            py36h5429711_0  
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
  * Jupyter version (if applicable):
  * Other libraries:  ipdb                      0.11                     pypi_0    pypi

Python and all packages are managed from a miniconda installation with manual installation and update of packages.

**Comment by timhoffm** [comment]
This is caused by ipdb initializting IPython, which sets `pyplot.show._needmain` (cf. backend_bases l.3328). I'm not enough into this magic to know what's the right way forward.

**Comment by anntzer** [comment]
I guess we need to figure out whether we're in an IPython interactive session or not, which we can do by walking the frame stack and looking for something that looks like an IPython interactive frame...  Perhaps @Carreau has a better idea of how to distinguish between ipdb being imported and a real IPython interactive session being run? :)

**Comment by anntzer** [comment]
(FWIW I cannot repro this anymore using the latest versions of everything, either.)
