### ISSUE TITLE
command-line flag to disable agg warning

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#14457]
I'm running all my tests with
```
MPLBACKEND=Agg pytest
```
to make sure no figures are popping up and it all works in headless environments. I'm getting many warnings like
```
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```
That's correct, but that's also intentional. Is there a command-line flag that I can use to disable those warnings?

**Comment by QuLogic** [comment]
You can pass a [standard warning filter](https://docs.python.org/3/library/warnings.html#describing-warning-filters) to pytest.

**Comment by nschloe** [comment]
According to [this](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS), I can only enable/disable _all_ warnings at once. Do I miss anything?

**Comment by QuLogic** [comment]
You can specify individual warnings as in the link I gave.

**Comment by nschloe** [comment]
I get it now. This
```
MPLBACKEND=Agg pytest -W ignore::UserWarning
```
does the trick. Thanks!
