### ISSUE TITLE
add third angle to view_init()

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#14453]
### Bug report

**Bug summary**

[mpl_toolkits.mplot3d.axes3d.Axes3D.view_init](https://matplotlib.org/mpl_toolkits/mplot3d/api.html#mpl_toolkits.mplot3d.axes3d.Axes3D.view_init)
provides a means to set the elevation and the azimuth, but the z-axis is always aligned with the vertical camera axis.
A third angle would be required to permit any view.

The issue was reported on [stackoverflow](https://stackoverflow.com/questions/34812843/interchange-location-of-y-and-z-axis-in-3d-matplotlib-plot) 3.5 years ago.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = Axes3D(fig)

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()
```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/12622691/58944759-c01af080-8782-11e9-9c1a-1465e18cdd05.png)

Now, however hard you try to rotate the plot interactively or what angles you set in `ax.view_init()`, you will never be able to get the z-axis in a horizontalish position that is required to produce the plot below:  

**Expected outcome**

By rotating interactively or via `ax.view_init()` one should be able to obtain this view below. Unfortunately, this is not possible.
![Figure_2](https://user-images.githubusercontent.com/12622691/58944932-17b95c00-8783-11e9-85a0-aab508d19706.png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version:  3.1.0, py37h5429711_0 
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.3 (conda)

**Comment by SReich-EMI** [comment]
my searching of how this could work ends here. I would kindly ask the community to implement this third angle to complete the 3D plotting in this case.

**Comment by scottshambaugh** [comment]
This looks like a relevant PR to keep in mind when reworking this: https://github.com/matplotlib/matplotlib/pull/10762

**Comment by timhoffm** [comment]
There are two aspects to consider:

- With the restricted two angles, the final view direction does not depend on the execution order of the two rotations.
  With three angles, you have to find a reasonable execution order and document that.
- When interactively navigating in the view window we currently map the two screeen directions horizontal/vertical to azimuth/elevation. AFAICS there is no simple way of controlling the third dimension interactively (though one might look at 3d programs how they solve this)

**Comment by baloe** [comment]
This is brilliant, thank you so much @scottshambaugh !

**Comment by baloe** [comment]
I updated my answer in the SO thread: https://stackoverflow.com/a/56457693/7042795

**Comment by SReich-EMI** [comment]
Thanks a lot for your work! I will surely test it in the next days!
