### ISSUE TITLE
GridSpec.update() and SubplotParams.update() have a different API

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#14469]
### Bug report

GridSpec.update() and SubplotParams.update() have a different behavior for passing *None*.

[GridSpec.update()](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.gridspec.GridSpec.html#matplotlib.gridspec.GridSpec.update)

> Values set to None use the rcParams value.

[SubplotParams.update()](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.figure.SubplotParams.html#matplotlib.figure.SubplotParams.update)

> Update the dimensions of the passed parameters. None means unchanged.

This is an inconsistent API choice. Unfortunately, every adaption would be a straight breaking change. I'm not sure if that's worth it. Should we do something here?

**Comment by ImportanceOfBeingErnest** [comment]
I think the gridspec docstring is simply wrong. At least 

```
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

gs = GridSpec(2,3, left=0.5)

fig = plt.figure()
ax = fig.add_subplot(gs[0,0])

gs.update(top=0.5)

plt.show()
```

shows a figure with both, left and top applied correctly.

**Comment by timhoffm** [comment]
That's not the correct test for GridSpec.update:

~~~
    def update(self, **kwargs):
        """
        Update the current values.

        Values set to None use the rcParams value.
        """
~~~

To be precise, one would have to add: Parameters that not passed stay unchanged.

So you would have to test expicitly setting `left=None`, and that works as documented (and differently to `SubplotParams.update()`).

~~~
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

gs = GridSpec(2,3, left=0.5)

fig = plt.figure()
ax = fig.add_subplot(gs[0,0])

gs.update(left=None)
plt.show()
~~~

**Comment by timhoffm** [comment]
Closing is justified. I do not see this as important enough to follow up for now.
