### ISSUE TITLE
Log scale messed up in histograms when sharing axes

### ISSUE THREAD

**Issue by tamasgal** [matplotlib/matplotlib#14527]
Hi there, this is somewhat related to https://github.com/matplotlib/matplotlib/issues/4450

### Bug report

**Bug summary**

If I plot multiple histograms with log-scale in a single plot, the limits are messed up.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

dummy_data = [np.random.randn(10000), []]
fig, axes = plt.subplots(len(dummy_data), sharex=True, sharey=True)

for ax, data in zip(axes.flatten(), dummy_data):
    ax.hist(data, bins=100)
    ax.set_yscale('log', nonposy='clip')
```

which produces the following correct output:

![two_histograms](https://user-images.githubusercontent.com/1730350/59257800-f2bb6200-8c36-11e9-9816-ae4a228a6e45.png)

However, if I add a new empty dataset, the scale is messed up, which I don't understand:

```python
import matplotlib.pyplot as plt
import numpy as np

dummy_data = [np.random.randn(10000), [], []]
fig, axes = plt.subplots(len(dummy_data), sharex=True, sharey=True)

for ax, data in zip(axes.flatten(), dummy_data):
    ax.hist(data, bins=100)
    ax.set_yscale('log', nonposy='clip')
```

![three_histograms](https://user-images.githubusercontent.com/1730350/59257857-12528a80-8c37-11e9-82d4-b97056832be1.png)

I tried also `nonposy='clip'` and a few other settings but could not succeed. Any ideas how to circumvent it?

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3
  * Jupyter version (if applicable): 5.7.8
  * Other libraries:

**Comment by dstansby** [comment]
What a weird bug... I can confirm this is a problem on the current `master` branch too.

**Comment by tamasgal** [comment]
Yep, thanks for cheking. As a workaround I set the `sharey=False`.

**Comment by phobson** [comment]
as a perhaps more agreeable workaround, you can use the `bottom` kwarg in your call to `hist`:

```python
import matplotlib.pyplot as plt
import numpy as np

dummy_data = [np.random.randn(10000), [], []]
fig, axes = plt.subplots(len(dummy_data), sharex=True, sharey=True)

for ax, data in zip(axes.flatten(), dummy_data):
    ax.hist(data, bins=100, bottom=0.001)
    ax.set_yscale('log', nonposy='clip')
```

![image](https://user-images.githubusercontent.com/1163939/59288784-6b1b2680-8c29-11e9-9a8b-6ecedcd09f11.png)

**Comment by tamasgal** [comment]
Thanks, that's also a nice option!

**Comment by anntzer** [comment]
Looks like something like
```
diff --git i/lib/matplotlib/ticker.py w/lib/matplotlib/ticker.py
index 5039b0230..64597ab09 100644
--- i/lib/matplotlib/ticker.py
+++ w/lib/matplotlib/ticker.py
@@ -2329,7 +2329,16 @@ class LogLocator(Locator):
                 "log-scaled.")
             vmin, vmax = 1, 10
         else:
-            minpos = self.axis.get_minpos()
+            ax = self.axis.axes
+            shared_axises = [
+                other_axis
+                for other_ax in [*ax._shared_x_axes.get_siblings(ax),
+                                 *ax._shared_y_axes.get_siblings(ax)]
+                for other_axis in other_ax._get_axis_list()
+                if other_axis.get_major_locator() is self]
+            minpos = min(
+                self.axis.get_minpos(),
+                *(other_axis.get_minpos() for other_axis in shared_axises))
             if not np.isfinite(minpos):
                 minpos = 1e-300  # This should never take effect.
             if vmin <= 0:
```
fixes it.

The sort of horrible expression in the middle is to get whatever axises are sharing the locator, and get the smallest minpos across all sharing axises rather than just the main one.

The clean solution is probably to just completely get rid of minpos, which is yet another gross hack :( but that's more surgery.
