### ISSUE TITLE
Does font_manager have trouble reading underscores in (.ttf) font filenames?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [matplotlib/matplotlib#14536]
The make utility has trouble understanding hyphens, so I usually convert them to underscores in the files I'm working with. I took two fonts called "Black" and "Light" from the [Montserrat family](https://github.com/JulietaUla/Montserrat/tree/master/fonts/ttf), and discovered that if I change the hyphens in their names to underscores, Matplotlib treats "Light" as if it were "Black".

```
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

fonts  = [
    # These two font files are identical
    "fonts/Montserrat_Black.ttf"
  , "fonts/Montserrat-Black.ttf"
  
    # These two font files are identical, and distinct from the previous two
  , "fonts/Montserrat_Light.ttf"
  , "fonts/Montserrat-Light.ttf"
  ]

for (i,f) in zip( [1,2,3,4], fonts ):
  plt.subplot(4, 1, i)
  plt.text( 0, 0.5
          , "A phrase to test the font"
          , fontproperties =
            fm.FontProperties(fname=f) )

plt.show()
```

I expected the first two lines to look the same (dark), and the second two lines to look the same (light), but in fact the first three all look the same (dark), and only the last one looks different (light).

I'm evaluating this code from a Jupyter notebook, so I precede it by first evaluating the line `%matplotlib inline`. It's all using Anaconda version 3.6.8.

**Comment by anntzer** [comment]
I can't repro this as of matplotlib 3.1 (qt5agg) or even 2.2.4:
![test](https://user-images.githubusercontent.com/1322974/59393304-433bd800-8d7b-11e9-8fd3-b1c5c75ed8ef.png)

**Comment by timhoffm** [comment]
@JeffreyBenjaminBrown Which OS are you using?

**Comment by JeffreyBenjaminBrown** [comment]
I'm using Kubuntu 18.04.

I rebooted the computer, and restarted Jupyter (from the same Docker container that was running before rebooting), and now I can't reproduce the issue either.

**Comment by anntzer** [comment]
Let's assume that this is not a problem unless we get a repro, then.
