### ISSUE TITLE
Plots not showing in Jupyter Notebook

### ISSUE THREAD

**Issue by Invisible786** [matplotlib/matplotlib#14534]
When I try to run plt.show() code for plotting a graph, then only the image size appears but not the plot.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
slices_hours = [4, 8]
activities = ['Sleep', 'Work']
colors = ['r', 'g']
plt.pie(slices_hours, labels=activities, colors=colors, startangle=90, autopct='%.1f%%')
plt.show()
```

**Actual outcome**

```
<Figure size 640x480 with 1 Axes>
```
**Actual Code with Output**

![image](https://user-images.githubusercontent.com/27002169/59314971-441a2e80-8cd5-11e9-8ee7-7ffe7754f4e6.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/27002169/59315020-7e83cb80-8cd5-11e9-8156-30328446b58e.png)

**Matplotlib version**

  * Operating system: Windows 10 Home, Version: 1809, OS Build: 17763.529 
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
    `module://ipykernel.pylab.backend_inline`
  * Python version: 3.7.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: `pip list`
Package           Version
----------------- -------
attrs             19.1.0
backcall          0.1.0
bleach            3.1.0
colorama          0.4.1
cycler            0.10.0
decorator         4.4.0
defusedxml        0.6.0
entrypoints       0.3
ipykernel         5.1.1
ipython           7.5.0
ipython-genutils  0.2.0
jedi              0.13.3
Jinja2            2.10.1
jsonschema        3.0.1
jupyter-client    5.2.4
jupyter-core      4.4.0
jupyterthemes     0.20.0
kiwisolver        1.1.0
lesscpy           0.13.0
MarkupSafe        1.1.1
matplotlib        3.1.0
mistune           0.8.4
nbconvert         5.5.0
nbformat          4.4.0
notebook          5.7.8
numpy             1.16.4
pandocfilters     1.4.2
parso             0.4.0
pickleshare       0.7.5
pip               19.1.1
ply               3.11
prometheus-client 0.7.0
prompt-toolkit    2.0.9
Pygments          2.4.2
pyparsing         2.4.0
pyrsistent        0.15.2
python-dateutil   2.8.0
pywinpty          0.5.5
pyzmq             18.0.1
Send2Trash        1.5.0
setuptools        40.8.0
six               1.12.0
terminado         0.8.2
testpath          0.4.2
tornado           6.0.2
traitlets         4.3.2
wcwidth           0.1.7
webencodings      0.5.1

**Comment by ImportanceOfBeingErnest** [comment]
Many people report on the "inline" backend selected by default, but that is not my experience. Possibly some distributions add additional code that selects/activates the backend.  To be on the safe side one can do it manually, e.g. putting one of the following in the first line of the notebook

* `%matplotlib inline`  - Figures are shown as static png images (optionally svg if configured)
* `%matplotlib notebook` or `%matplotlib nbagg` - Interactive Figures inside the notebook
* `%matplotlib widgets` - - Interactive Figures inside the notebook (requires [jupyter-matplotlib](https://github.com/matplotlib/jupyter-matplotlib) to be installed)
* `%matplotlib tk` or `%matplotlib qt` etc. - GUI windows show the figure externally to the notebook with the given interactive backend

**Comment by Invisible786** [comment]
@ImportanceOfBeingErnest  Thanks it works for now.

**Comment by Lotfey** [comment]
this link would work for you as it did for me, good luck
https://github.com/matplotlib/ipympl
