### ISSUE TITLE
Changing mplstyle: axes.titlelocation causes Bad Key error

### ISSUE THREAD

**Issue by susielu** [matplotlib/matplotlib#14547]
### Bug report

**Changing mplstyle: axes.titlelocation causes Bad Key error**

I see `axes.titlelocation` in the latest [template](https://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template#L291)
but when I change the default from `center` to `left` I get this bad key error: 
```
Bad key "axes.titlelocation" on line 291 in
./nflx_theme.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
```

**Matplotlib version**

  * Operating system: Mac
  * Matplotlib version: 3.1.0
  * Python version:3.6.5

I believe I installed using pip

**Comment by timhoffm** [comment]
This was added in #13802 and is targeted at v3.2.0. It's not yet present in v3.1.0 https://github.com/matplotlib/matplotlib/tree/a8f4a742803b5238911b9c3f698f2417c3ac441a. If you look at the template from the master branch, you better run it with the master branch code :smile:.

**Comment by susielu** [comment]
Thanks @timhoffm I gotcha that makes sense. I found it confusing that in the error message it explicitly says to compare with that file, thanks for the quick response and clarification.

**Comment by anntzer** [comment]
I think it would make sense to move the template file to mpl-data (perhaps mpl-data/stylelib) and make the error message point to that (or at the very least, *don't* make the error message point to the github repo, as that's legitimately confusing).

**Comment by anntzer** [comment]
closed by https://github.com/matplotlib/matplotlib/pull/14548.
