### ISSUE TITLE
Update show() entry in howto tutorial.

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#14553]
The entry on using `show()` in https://matplotlib.org/faq/howto_faq.html#use-show is written in a confusing manner, as it alternates between describing the pre-1.0 behavior and the current one.  I'm not sure if it should be entirely scrapped, or whether the differences in the OSX backend mentioned remain present and the whole thing should be rewritten.  Compare also with https://matplotlib.org/tutorials/introductory/usage.html#what-is-interactive-mode; it may be worth harmonizing the two discussions to a single place.

**Comment by Huzaib** [comment]
I want to do it if it's still open?

**Comment by timhoffm** [comment]
Go for it.

**Comment by Huzaib** [comment]
So should the description about the 1.0 version be removed or a comparison between the versions be provided?
Also, I am a beginner at this and I don't knowhow to find this corresponding file
Thank You

**Comment by dopplershift** [comment]
So you should just worry about documenting current behavior. The current version of that page is in (relative to the base of a git checkout of the matplotlib repository): `doc/faq/howto_faq.rst`.

The other page mentioned originally is in `tutorials/introductory/usage.py`

**Comment by Huzaib** [comment]
Sir my PR run failed
I just made changes in the usage.py file you mentioned
I don't understand what happened

**Comment by dmatos2012** [comment]
Closing as https://matplotlib.org/stable/faq/howto_faq.html has since been changed, so no longer relevant. Closed on #18198 also.
