### ISSUE TITLE
Non functional API links break docs builds downstream

### ISSUE THREAD

**Issue by bsipocz** [matplotlib/matplotlib#14551]
https://github.com/matplotlib/matplotlib/pull/12716 has added new "See Also" sections to docstrings with some of them containing non functional API links. When the `Axes` class is subclassed downsteam and thus method documentation is inherited, these links are causing failing docs builds.

Examples: https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.get_tightbbox.html#matplotlib.axes.Axes.get_tightbbox

Sphinx and numpydoc recently became significantly stricter, it may be a reason why it doesn't yet cause issues for your doc testing using pinned version of Sphinx.

**Comment by alexrudy** [comment]
I tried to fix this in #14764

**Comment by QuLogic** [comment]
This should be fixed by the above PR.
