### ISSUE TITLE
colorbar label prints "None" when label=None

### ISSUE THREAD

**Issue by KevinBouchaud** [matplotlib/matplotlib#14563]
### Bug report

**Bug summary**

When giving the variable None to the label argument of matplotlib.pyplot.colorbar(), i.e label=None, the label still appears, with the text "None", as if being given label="None".

**Code for reproduction**

```python
import numpy as np 
import matplotlib.pyplot as plt 

fig, ax = plt.subplots() 
img = ax.imshow(np.random.random((10,10))) 
fig.colorbar(mappable=img, ax=ax, label=None)   
fig.show()
```

**Actual outcome**

![colormap_label](https://user-images.githubusercontent.com/28622529/59619338-9a023280-912a-11e9-9028-45a1bb16b554.png)

**Expected outcome**

The label should not appear. The bug is still present in matplotlib 3.1.

**Matplotlib version**

  * Operating system: Ubuntu 18.04.2 LTS x86_64
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.2
  * Jupyter version (if applicable):
  * Other libraries: 

I installed matplotlib via conda through the default channel.

**Comment by dstansby** [comment]
I suspect this is intended behaviour; if `str(label)` works, then it will be used as a label, if you want a blank label then the default option is to pass an empty string.

**Comment by timhoffm** [comment]
@dstansby I beg to differ. Usually, when we accept `None` it means "use the default", sometimes also "show nothing" (even though we often have the string version `'none'` for that). I would say it's never intended to convert `None` to a string and show it when the parameter is something to print out.

I argue that this here is just lack of reasonable argument checking. There tagging as "confirmed bug".

Compare for example
~~~
In [4]: plt.xlabel(None)                                                                                                     
Out[4]: Text(0.5, 23.52222222222222, '')
~~~

**Comment by anntzer** [comment]
looks like a replay of https://github.com/matplotlib/matplotlib/pull/10392 :)
