### ISSUE TITLE
New output format - Single Image Random Dot Stereogram

### ISSUE THREAD

**Issue by Mazecreator** [matplotlib/matplotlib#14578]
I have coded a Single Image Random Dot Stereogram C++ function for TensorFlow to produce 3D SIRDS images on a 2D plan.

Single Image Random Dot Stereogram (SIRDS)

SIRDS is a means to present 3D data in a 2D image. It allows for scientific data display of a waterfall type of plot with no hidden lines due to perspective. Data is encoded to show data in the Z direction as depth.

This project is based upon: https://www.cs.waikato.ac.nz/~ihw/papers/94-HWT-SI-IHW-SIRDS-paper.pdf

You can see an example of what I mean on my GitHub page:
https://github.com/Mazecreator/TensorFlow-SIRDS/blob/master/single_image_random_dot_stereograms/SIRDS%20Demo.ipynb

It dawned on me that this tool would be much more available to the scientific community it it were included in more generic visualization tools such as MatPlotLib.  If there is interest from the community, I am more than willing to provide the code to help generate this output format.  I really have no idea where to start to get this into MatPlotLib and would like to work with someone to help integrate the code if desired.

Thanks for your consideration.

**Comment by timhoffm** [comment]
Thanks for considering Matplotlib!

We are trying to keep core Matplotlib reasonably sized, and I have the feeling that this is too specialized.  Your functionality is better placed in a separate package. If you want to, that could be hosted under the matplotlib umbrella here on github too. Let us know if you need any help with that.

**Comment by tacaswell** [comment]
I agree with @timhoffm this seems too specialized for Matplotilb, but would be perfect for a stand-alone package.  Particularly if this requires tensorflow, that is not a dependency that I would be willing to pick up in core Matplotlib.

I would also be concerned about running the output of SIRDS through our imaging display framework due to the amount we resample.

If you are not familiar with python packaging https://github.com/NSLS-II/scientific-python-cookiecutter is a good place to get started.

Thanks for considering us and best of luck!

ps I just spent 30 minutes staring at the outputs and, unlike my historical experience, could actually see the illusion!

**Comment by Mazecreator** [comment]
@timhoffm A separate package might work.  I could use some pointers to get started... The size isn't that big for the code, maybe a 2K or so.  I am looking for a way to make this available to the scientific community and let them know it is available.  It is useful for viewing "Water-Fall" type of plots.  This was the intent for TensorFlow. 

@tacaswell this project doesn't depend on TensorFlow, but just happen to be the package I was working with at the time.  Ultimately, you pass this a 2D array with "height data" encoded at each point and it creates a 2D image of random dots for display which encodes that height data.  Your comment about the image routine Re-Sampling could be a problem as the output image size needs to be known and the "random" dots are selected to appropriately encode the height data.  Any resampling or removal of dots (they can change in size, but not presence) will likely corrupt the visual output.

Sounds like a separate packs hosted with Matplotlib might be the best way to go.
