### ISSUE TITLE
LAS Point Cloud is not visualized

### ISSUE THREAD

**Issue by zwnk** [matplotlib/matplotlib#14572]
I'm trying to visualize a small point cloud. The point cloud is in UTM WGS84.
The x, y and z coordinates are calculated and than arranged in a numpy array. When running the program it terminates without showing the actual plot and without any error.

**Code for reproduction**
```python
import numpy as np
import laspy
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

# reading lasfile
input_las = laspy.file.File("test.las", mode="r")
point_records = input_las.points.copy()

# getting scale and offset factors
las_scaleX = input_las.header.scale[0]
las_offsetX = input_las.header.offset[0]
las_ScaleY = input_las.header.scale[1]
las_offsetY = input_las.header.offset[1]
las_scaleZ = input_las.header.scale[2]
las_offsetZ = input_las.header.offset[2]

# calculating UTM coordinates and storing every point
p_X = np.array((point_records['point']['X'] * las_scaleX) + las_offsetX)
p_Y = np.array((point_records['point']['Y'] * las_scaleY) + las_offsetY)
p_Z = np.array((point_records['point']['Z'] * las_scaleZ) + las_offsetZ)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax = fig.add_subplot(111, projection='3d')

ax.scatter(p_X, p_Y, p_Z, c='r', marker='o')
plt.show
```

p_X:
```
[679517.94154783 679515.63354783 679521.35854783 ... 679526.42254783
 679526.90754783 679527.95654783]
```

p_Y:
```
[5800743.35322174 5800752.74222174 5800753.04822174 ... 5800741.16722174
 5800741.36322174 5800741.26222174]
```

p_Z:
```
[646.459 660.879 657.244 ... 668.224 669.552 648.596]
```

**Actual outcome**
The acutal outcome is that nothing happens, the program terminates without an error.

```
no output
```

**Expected outcome**
plotted point cloud

**Matplotlib version**

  * Operating system: win 10
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6
  * Other libraries: pylas

It is a conda environment on windows.

**Comment by timhoffm** [comment]
Your code contains `plt.show`, which just states the function but does not habe any effect. You need to call it `plt.show()`.

**Comment by zwnk** [comment]
sorry and thanks!
