### ISSUE TITLE
Builtin function for multicolor/colormapped line

### ISSUE THREAD

**Issue by KOLANICH** [matplotlib/matplotlib#14584]
Currently in order to make a multicolor curve one has to not to use `plot` but do its work manually himself: https://matplotlib.org/3.1.0/gallery/lines_bars_and_markers/multicolored_line.html

It is bad. I guess `plot` should accept `c` argument the same way `scatter` accepts it.

**Comment by efiring** [comment]
It would take much more than just a 'c' argument; one needs the colormap, the norm, and the values being mapped.  Note also that the 'x' and 'y' coordinates of N points along the line require N-1 values for the colors of the line segments between the consecutive points.
I'm sure we don't want to overload the 'plot' function with all this.  It might make sense to have a new function that would encapsulate the functionality shown in the example you cite.

**Comment by KOLANICH** [comment]
>*m sure we don't want to overload the 'plot' function with all this. It might make sense to have a new function that would encapsulate the functionality shown in the example you cite.

It is fine if that function is called from `plot` internally.

**Comment by ImportanceOfBeingErnest** [comment]
Functions in the matplotlib API should have a defined return object. `plot` returns a list of `Line2D` objects.  
One could of course let it take a `c` argument (and all the other arguments needed) and let it return a list of differently colored lines. But that is highly inefficient; and we probably don't want to introduce such inefficient code. 
Letting `plot` return a `LineCollection` would be a bad API; I think in general we try to avoid functions where the return type depends on some combination of input parameters. 
Hence the only option is really to create a new method that creates and returns a `LineCollection`.

**Comment by anntzer** [comment]
This was already discussed in https://github.com/matplotlib/matplotlib/issues/6040; I would suggest folding the two discussions together.

**Comment by efiring** [comment]
I'm closing this in favor of #6040. I don't think the discussion here to date adds anything new.
