### ISSUE TITLE
forward port jquery removal from ipympl

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#14596]
https://github.com/matplotlib/jupyter-matplotlib/pull/85  removes jquery from ipympl.  Much of that js is shared / derived from the webagg and nbagg backends currently shipped in Matplotlib.

Going forward we should pull that patch forward (probably not for old version so it won't help us with #14587 and friends) and deprecate the nbagg backend (as it does not work with jlab) but keep the webagg backend.

**Comment by jklymak** [comment]
I'm not a fan of deprecating `nbagg` until https://github.com/matplotlib/jupyter-matplotlib/issues/16 is closed.

**Comment by QuLogic** [comment]
Do we want to support IE 8, 9, or 10?

**Comment by timhoffm** [comment]
Jupyter notebook and Jupyterlab both don't support IE:
https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#browser-compatibility
https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers

Therefore I don't think it's necessary that we support IE.
