### ISSUE TITLE
NavigationToolbar2Tk save_figure function bug

### ISSUE THREAD

**Issue by k1moradi** [matplotlib/matplotlib#14602]
There is no guarantee that canvas having a manager attribute, which was exactly what happened in my case.

fname = tkinter.filedialog.asksaveasfilename(
            **master=self.canvas.manager.window,**
            title='Save the figure',
            filetypes=tk_filetypes,
            defaultextension=defaultextension,
            initialdir=initialdir,
            initialfile=initialfile,
            )

I suggest the following change to fix the problem.

fname = tkinter.filedialog.asksaveasfilename(
            **master=self.canvas._master,**
            title='Save the figure',
            filetypes=tk_filetypes,
            defaultextension=defaultextension,
            initialdir=initialdir,
            initialfile=initialfile,
            )

**Comment by anntzer** [comment]
Thanks for the report, this was fixed in https://github.com/matplotlib/matplotlib/pull/14568.

**Comment by V-Geek** [comment]
Thanks Keivan, it solved my problem.
