### ISSUE TITLE
Scatterplot: should vmin/vmax be ignored when a norm is specified?

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#14603]
### Bug report

**Bug summary**

The `scatter` documentation says:

> *vmin* and *vmax* are ignored if you pass a *norm* instance.

However, it seems that this is not the case. Is the documentation correct of the behaviour?

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

cmap = matplotlib.cm.viridis_r
norm = matplotlib.colors.BoundaryNorm([1,3,6,8], cmap.N, clip=True)

values = np.arange(10)

# only specifying a norm
plt.scatter(values, values, c=values, norm=norm)

# also specifying vmin/vmax. Should those be ignored?
plt.scatter(values, values, c=values, norm=norm, vmin=6, vmax=10)
```

**Actual outcome**

```
# only specifying a norm
plt.scatter(values, values, c=values, norm=norm)
```

![index](https://user-images.githubusercontent.com/1020496/59982970-2d9b9d80-961a-11e9-9303-4d6ccf29ec4b.png)

```
# also specifying vmin/vmax. Should those be ignored?
plt.scatter(values, values, c=values, norm=norm, vmin=6, vmax=10)
```

![index2](https://user-images.githubusercontent.com/1020496/59982972-2ffdf780-961a-11e9-9dd4-b0a92b74e0d5.png)

So the vmin/vmax have clearly "altered" the BoundaryNorm applied on the data.

According to the documentation, this should not happen. 
Specifically for a BoundaryNorm (with specified bounds), it seems strange let the plotting change those bounds.

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): notebook inline backend
  * Python version: 3.7
  * Installed from conda-forge

**Comment by story645** [comment]
Not that this should change anything, but what happens when clip is false?
