### ISSUE TITLE
importing matplotlib.animation causes pyinstaller windows executable to fail

### ISSUE THREAD

**Issue by shlomok613** [matplotlib/matplotlib#14607]
### Bug report

**Bug summary**

compiled simple animation demo with pyinstaller
pyinstaller -w -F --dist=. test.py
it generates failed to execute test.py dialog box

**Code for reproduction**
import matplotlib.animation

```python
import matplotlib.animation
```

**Actual outcome**
on running test.exe
![image](https://user-images.githubusercontent.com/52164257/60021133-1603f980-969a-11e9-91f2-97f331197827.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**
script should run with no output

**Matplotlib version**

  * Operating system:
Windiows 7
  * Matplotlib version: 
3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
TkAgg
  * Python version:
3.6.2
  * Jupyter version (if applicable):
  * Other libraries: 
pyinstaller version 3.4

installed through pip

**Comment by anntzer** [comment]
I can't repro: I can successfully build an exe for e.g. examples/animation/simple_anim.py using pyinstaller.

**Comment by anntzer** [comment]
Closing for lack of repro.  Feel free to request a reopen with more info.
