### ISSUE TITLE
Issue with using plt.axis('equal') with plt.polar(theta,r) plot

### ISSUE THREAD

**Issue by jtwolfson** [matplotlib/matplotlib#14608]
**Bug summary**

when using matplotlib.pyplot.axis('equal') with a polar plot, it tends to make things completely unreadable. This was discovered after original using a Cartesian plot and changing the one line of code from plt.plot to plt.polar and the plt.axis('equal') was left in. Right now, the clear solution is to not change the axis attributes using plt.axis('equal') when using a polar plot.
However, maybe the axis attributes that would create a messed up plot should be ignored if the plot is a polar plot. 

```python
import matplotlib.pyplot as plt
import numpy as np
data_angles=np.arange(0,2.05,.05)*np.pi
data_radii=np.sin(data_angles)
plt.polar(data_angles, data_radii)
plt.axis('equal')
```
**Matplotlib version**

  * Operating system: CENTOS 7
  * Matplotlib version: 3.1.0
  * Matplotlib backend: GTK3Agg
  * Python version: 3.6

**Comment by RebeccaWPerry** [comment]
I can replicate this. With plt.axis('equal'), the radial plot only shows one pie slice. Instead, the full circle should be shown.
- Matplotlib version: 3.1.0
- Python version: 3.6.7

**Comment by RebeccaWPerry** [comment]
Please bear with me. I'm using this an an opportunity to learn more about the inner workings of Matplotlib. I've figured out that plt.polar(data_angles, data_radii) uses set_aspect from _base.py with aspect= 'equal', so it's even more surprising to me that explicitly saying plt.axis('equal') messes things up.

'auto' and 'equal' both result in showing only a pie slice of the radial plot. Passing in a numerical value leaves the full circle in tact.

**Comment by anntzer** [comment]
The problem is because `axis('equal')` also sets adjustable to 'datalim' :(
