### ISSUE TITLE
Contour() fails when both cmap and colors are specified

### ISSUE THREAD

**Issue by MaozGelbart** [matplotlib/matplotlib#14618]
### Bug report

**Bug summary**

According to the ``cmap`` argument description in the ``contour()`` [documentation](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.contour.html), ``colors`` argument should take precedence over ``cmap`` when both are specified. However, specifying both results in a ``ValueError: Either colors or cmap must be None``.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2
fig, ax = plt.subplots()
CS = ax.contour(X, Y, Z, cmap="viridis", colors='red')

```

**Actual outcome**

```
Traceback (most recent call last):
  File "D:\contour_cmap_colors.py", line 12, in <module>
    CS = ax.contour(X, Y, Z, cmap="viridis", colors='red')
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\axes\_axes.py", line 6400, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\contour.py", line 849, in __init__
    raise ValueError('Either colors or cmap must be None')
ValueError: Either colors or cmap must be None
```

**Expected outcome**
Not to fail, and use the ``colors`` input.

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3

See related seaborn issue [here](https://github.com/mwaskom/seaborn/issues/1748).

**Comment by tacaswell** [comment]
Closed by #14757
