### ISSUE TITLE
Two different fonts in the axes in pgf images

### ISSUE THREAD

**Issue by jakobjakobson13** [matplotlib/matplotlib#14637]
### Bug report

**Bug summary**

A pgf image exported by matplotlib leads to two different fonts in the x- and y-axis in a [latex document](https://github.com/matplotlib/matplotlib/files/3330872/scrartcl_de.pdf)

**Code for reproduction**
First you have to create the figure with the following code or a similar one.
```python3
import matplotlib as mpl
mpl.rcParams["axes.formatter.use_mathtext"] = False
import matplotlib.pyplot as plt

plt.close()
plt.semilogy(3.5, 3.5e3, "o")
plt.savefig("test.pdf")
plt.savefig("test.pgf")
```

Then you put the `pgf` figure into a latex document:
```latex
\documentclass{scrartcl}
\usepackage{pgf}

\begin{document}
\input{test.pgf}
\end{document}
```

**Actual outcome**

Latex produces a pdf document with the y-axis in roman font (computer modern roman) and the x-axis in a sans-serif font (computer modern sans). I had expected both axes to have the same font.
The [pdf](https://github.com/matplotlib/matplotlib/files/3330874/test.pdf) produced by matplotlib in contrast has the sans-serif font for both axes.

**Expected outcome**

I would expected both axes to have a sans-serif font like in the pdf produced by matplotlib itself. However, I'm not sure if this is more latex related. 
I also found a similar question on [stackoverflow](https://stackoverflow.com/questions/52277797/is-there-a-non-math-version-of-matplotlib-ticker-logformatterscinotation).

**Matplotlib version**

  * Operating system: Ubuntu 18.04.2
  * Matplotlib version: 3.1.0
  * Matplotlib backend: TkAgg
  * Python version: 3.6.8
  * Jupyter version (if applicable): not important
  * Other libraries: pdfTex 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)

**Comment by timhoffm** [comment]
This happens when a `LogFormatterMathtext` or `LogFormatterSciNotation` are used.

**Comment by jakobjakobson13** [comment]
So (deducting from your label} there is no easy work around?

**Comment by timhoffm** [comment]
I don't think so. Ping @anntzer I think you're the `usetex` expert here.

**Comment by anntzer** [comment]
Sorry, a quick look does not yield anything.

**Comment by bonderado** [comment]
Hello, 
I am an enthusiastic user of matplotlib, thanks  fro its creation.
I stumbled on this bug looking for other things and I played a bit with the generated text.pgf, in particular with the line:

\pgftext[x=0.501581in,y=4.003238in,left,base]{\color{textcolor}\sffamily\fontsize{10.000000}{12.000000}\selectfont \(\displaystyle {10^{4}}\)}%

Apparently, as soon as math mode is entered with \( \), math mode fonts are used, which are not set to sans serif.
Changing the line to:

\pgftext[x=0.501581in,y=4.003238in,left,base]{\color{textcolor}\sffamily\fontsize{10.000000}{12.000000}\selectfont \(\mathsf{\displaystyle {10^{4}}}\)}%

turns the math text to sans, but I am not sure this is a practical solution in case the tick labels are formatted in some complex way (for some reason I cannot imagine at the moment).

A hint for a more general solution may be in the manual for package fontspec v2.7c whose section 4.4 states:

Note that fontspec will not change the font for general mathematics; only the upright
and bold shapes will be affected. To change the font used for the mathematical symbols, see
either the mathspec package or the unicode-math package.

I thought this  could be helpful.

Happy life to all.
