### ISSUE TITLE
Adding hatches changes face color

### ISSUE THREAD

**Issue by SMZ70** [matplotlib/matplotlib#14639]
### Bug report

**Bug summary**

Adding hatches results in a change in the face color of bars. The problem occurs when saved as PDF. Everything is ok with png.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.barh(2, 4, edgecolor='black', facecolor='green', alpha=0.3)
ax.barh(3, 4, edgecolor='black', facecolor='green', hatch='///', alpha=0.3)
fig.savefig('hbarplot.pdf')
fig.savefig('hbarplot.png')
```
**Actual outcome**

![image](https://user-images.githubusercontent.com/52261779/60219905-97af7f00-9874-11e9-8e1d-2130dc5300d0.png)

**Expected outcome**

The plot in the pdf file to be the same as the one in png file.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.3, conda, default
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg or module://ipykernel.pylab.backend_inline (problem occurs with both)
  * Python version: 3.7

**Comment by jklymak** [comment]
Can you try a range of PDF viewers?  This works fine on Apple Preview, and Adobe Acrobat.

**Comment by timhoffm** [comment]
Generated with 3.1: [hbarplot.pdf](https://github.com/matplotlib/matplotlib/files/3333483/hbarplot.pdf)

**Comment by SMZ70** [comment]
> Can you try a range of PDF viewers? This works fine on Apple Preview, and Adobe Acrobat.

You're right. The problem is with Foxit Reader. Thanks!

**Comment by SMZ70** [comment]
> Generated with 3.1: [hbarplot.pdf](https://github.com/matplotlib/matplotlib/files/3333483/hbarplot.pdf)
> 
> This file is displayed correctly in Okular and Adobe Reader.
> 
> @SMZ70 you can download this file and cross-check with your PDF viewer.

The file looks fine in Adobe Reader, but the problem exists with Foxit Reader. There must be something wrong with the viewer. Thanks!

**Comment by anntzer** [comment]
The pdf is also misdisplayed by chromium.
OTOH mplcairo generates a pdf that chromium reads fine.

**Comment by ImportanceOfBeingErnest** [comment]
There are continuously problems with matplotlib generated output on different pdf viewers. 
One thing [I found](https://github.com/matplotlib/matplotlib/issues/12367#issuecomment-427441611) to often work nicely is to save pdfs via svg and convert to pdf with inkscape.

```
def savepdfviasvg(fig, name, **kwargs):
    import subprocess
    fig.savefig(name+".svg", format="svg", **kwargs)
    incmd = ["inkscape", name+".svg", "--export-pdf={}.pdf".format(name),
             "--export-pdf-version=1.5"] #"--export-ignore-filters",
    subprocess.check_output(incmd)

    
savepdfviasvg(fig, "hatchtestconv")
```

**Comment by timhoffm** [comment]
It's unclear if the PDF we generate is broken but handled gracefully by some viewers, or if we comply with the spec and the viewers are buggy. But to find out, somebody with experience in the PDF specification would be required.
