### ISSUE TITLE
matplotlib plot window home and back-forth buttons not responsive

### ISSUE THREAD

**Issue by PleaseStateTheNatureOfYourInquiry** [matplotlib/matplotlib#14648]
Recently the 'home' and 'back' 'forward' buttons on the standard matplotlib plot window you get when doing a command such as 'plt.plot (something))' have become totally unresponsive on my system. The zoom, drag, and save buttons work fine. 

I have updated to Mac OS 10.14.5, but not sure it is related.

Does anyone else experience this problem? 
Does anyone have an idea of what could be going on?

Thanks in advance!
Maarten

**Comment by timhoffm** [comment]
Which version of matplotlib, which backend are you using?

~~~
import matplotlib
print(matplotlib.__version__)
print(matplotlib.get_backend())
~~~

**Comment by MaartenLCF** [comment]
> Which version of matplotlib, which backend are you using?
> 
> ```
> import matplotlib
> print(matplotlib.__version__)
> print(matplotlib.get_backend())
> ```

Hi Tim. Thanks for your reply. I have version 3.0.3 with backend TkAgg.

**Comment by greglucas** [comment]
I can't reproduce this on newer versions of Matplotlib, the home/back/forward toolbar all works as expected for me with tkagg. Feel free to reopen if you're still having issues with the toolbar buttons.
