### ISSUE TITLE
Axes title default color

### ISSUE THREAD

**Issue by OriolAbril** [matplotlib/matplotlib#14656]
Hi, I have just realized that `ax.set_title()` uses as default the color defined in `rcParams["text.color"]` instead of using the color from `rcParams["axes.labelcolor"]`. Why is that? 

In my case, I was trying to create an style for dark figure background and light axes background. Therefore, as the title is on top of the figure background like the axis labels and ticklabels, I expected them to have the same color. Below there are two examples, both have axes.labelcolor white but they have different text.color.

![image](https://user-images.githubusercontent.com/23738400/60391503-ff253300-9aef-11e9-8fcf-023bf7fdd52a.png)

![image](https://user-images.githubusercontent.com/23738400/60391501-f3d20780-9aef-11e9-9838-f624029fa6fa.png)

Maybe `'color': rcParams['axes.labelcolor']` could be added to the default fontdict like axes.titlesize and axes.titleweight? 

I added an `ax.set_title` to the style sheet reference script and only solarized theme will be modified by this. It could affect user made themes though, but I feel that it is more coherent like this.

**Comment by timhoffm** [comment]
On the danger of proliferation of config parameters (not sure if this is a real problem though), it would be reasonable to make and `axes.titlecolor`.

**Comment by OriolAbril** [comment]
Yes, this is also an option, but seeing as only 1 of the available styles has axes.labelcolor different than text.color, I am not sure if this is necessary.

**Comment by timhoffm** [comment]
Implemented by #14707.
