### ISSUE TITLE
Where is the right place to go if I want to contribute to the DOCUMENTATIONs?

### ISSUE THREAD

**Issue by bingyao** [matplotlib/matplotlib#14657]
Maybe this is a silly question. 

### Background

While I am reading and exploring the great docs from matplotlib's [website][1], sometimes I also want to make some minor contributions (fixing typo, improving RST styling, etc.). 

### But the question is

Where should I head to make those modifications? For example, although the [Developers' Guide][8] says that:
> All documentation is built from the `doc/` directory.

but for those [Tutorials docs][2], I couldn't find counterpart `.rst` files in the [`./doc`][3] folder. And also, how are the documentations organized?

### My current understanding

After some exploration I found following locations:

* A separate [matplotlib.github.com][4] repo
    It seems this is the place to hold the whole documentations of **`matplotlib`** (sources and built htmls). So should we make modifications in this separated repo for the docs?
* Another separate [devdocs][5] repo
    It looks like this is an auto built/generated repo used by travis, not for human to directly interactive with.
* The matplotlib repo's [`./doc`][3] folder
    What is the relationship of this folder to [matplotlib.github.com][4] repo?
* The matplotlib repo's [`./tutorial`][6] folder
    There are no `.rst` files in this folder, only `.py` files, in the same structure of the tutorial docs. But I also found out that these `.py` files are (partly) different from those `.py` files directly downloaded from the tutorial doc pages, e.g.:
    > [Download Python source code: usage.py][7]

[1]: https://matplotlib.org/contents.html
[2]: https://matplotlib.org/tutorials/index.html
[3]: https://github.com/matplotlib/matplotlib/tree/master/doc
[4]: https://github.com/matplotlib/matplotlib.github.com
[5]: https://github.com/matplotlib/devdocs
[6]: https://github.com/matplotlib/matplotlib/tree/master/tutorials
[7]: https://matplotlib.org/_downloads/a8c08470ce2a44c17f3d402409658d9c/usage.py
[8]: https://matplotlib.org/devel/index.html

**Comment by timhoffm** [comment]
Thanks for your interest in helping to improve matplotlib!

All the editable parts of the documentation are in this repo:

- examples and tutorials are located in the respective folders. They are written as .py files and converted to .rst using sphinx-gallery as part of the sphinx build.
- API documentation such as classes, functions etc. are taken from the docstrings in the code as part of the sphinx build.
- everything else (e.g. the developers guide) ist directly written in .rst files in the `doc` folder.

**Comment by bingyao** [comment]
Ah! I was missing the awareness of _sphinx-gallery_ conversion and https://matplotlib.org/devdocs/ 

Now the structure and the organization of the docs are more clear to me! Thanks!
