### ISSUE TITLE
cm.ScalarMappable should fail early when norm input is wrong

### ISSUE THREAD

**Issue by Tigraan** [matplotlib/matplotlib#14669]
**Summary**

`matplotlib.cm.ScalarMappable` does not validate its `norm` keyword argument. It should check that it is callable.

**The issue**

```python
import matplotlib.cm
test = matplotlib.cm.ScalarMappable(norm=1, cmap='jet')  # faulty, but runs fine
test.to_rgba([0., 0.5])  # fails with an unclear stack trace
```

The code above fails with the stack trace

> Traceback (most recent call last):
>   File "...\test.py", line 3, in <module>
>     test.to_rgba([0., 0.5])  # fails with an unclear stack trace
>   File "...\anaconda2\lib\site-packages\matplotlib\cm.py", line 274, in to_rgba
>     x = self.norm(x)
> TypeError: 'int' object is not callable

That is because `self.norm` is whatever was passed as the `norm` keyword argument to `matplotlib.cm.ScalarMappable.__init__`, but you need to look at the source code to know it.

It would make sense to validate that `norm` is callable during class instantiation: for instance `if callable(norm) == True: raise TypeError('norm' must be callable.)`. That would cause the error to appear on the faulty line of the user code, and the traceback to point at `matplotlib.cm.ScalarMappable.__init__` rather than `matplotlib.cm.ScalarMappable.to_rgba`.

 One could argue that not validating at class instantiation allows to give `norm` as a mutable object that is not callable at instantiation but is when actually used. I am not convinced that is a significant/good use case, compared to the value of failing earlier rather than later when the input is wrong.

**Version**
matplotlib 2.2.2
Python 2.7

**Comment by anntzer** [comment]
This would effectively be fixed by https://github.com/matplotlib/matplotlib/pull/13535.
