### ISSUE TITLE
[Feature request] Show quartiles (box) in violin plot

### ISSUE THREAD

**Issue by ParikhKadam** [matplotlib/matplotlib#14661]
**Bug summary**
It isn't actually a bug.. But comparing violin plots of seaborn with matplotlib, it seems that matplotlib plots lacks the quartile values and IQR when plotting violin plots. And this data is actually important when visualizing. So, it would be better if you include these things when plotting violin plots.

**Comment by ImportanceOfBeingErnest** [comment]
I guess the intended functionality would be to create a `violinplot` and then create a `boxplot` on top. Do you experience any problem when doing so?

**Comment by timhoffm** [comment]
I don‘t think so. This is just about adding lines for the respective quantiles. The lines should extend to the edge of the violin. See https://seaborn.pydata.org/examples/grouped_violinplots.html.

**Comment by ImportanceOfBeingErnest** [comment]
Interesting, so the default in seaborn is https://seaborn.pydata.org/examples/wide_form_violinplot.html; meaning, @ParikhKadam, can you clarify a bit what you envision?

**Comment by ParikhKadam** [comment]
@ImportanceOfBeingErnest @timhoffm Yes creating a box plot on a violin plot will work. But it would just be better if you can add an argument `showquartiles` like there are others such as `showextremes`. It will just reduce processing as the same thing will be recalculated when plotting box over violin.

Thank you.

**Comment by tacaswell** [comment]
I think this functionality already exists by passing `quantiles=[0.25, 0.75]` to violinplot?

**Comment by jklymak** [comment]
Closing per @tacaswell comment and discussion in #14661.
