### ISSUE TITLE
sharex is ignored for histogram bar width 

### ISSUE THREAD

**Issue by jmbarefoot** [matplotlib/matplotlib#14676]
**Bug summary**
Histogram bar width is does not take into account other subplots when sharex is enabled. This bug can be found on [master](https://github.com/matplotlib/matplotlib/blob/04d9d28b820af0b4df230a3c67314ed5b0af8fdd/lib/matplotlib/axes/_axes.py#L6668).

**Code for reproduction**

```python
import matplotlib.pyplot as plt

# Data set that will create 4 bars on histogram
t1 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]
# Data set that will create 2 bars on histogram
t2 = [1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3]

fig, axs = plt.subplots(2, 1, sharex='all', sharey='all')

# 8 bins to make sure there is a gap between each bar
axs[0].hist(t1, bins=8)
axs[1].hist(t2, bins=8)

plt.show()
```

**Actual outcome**
The bin size changes on a per-axis basis. In `t1` the data spans from 4 to 1 and is broken into 8 bins leading to each bin having a width of `(4 - 1) / 8 = 0.375`.  However in `t2` the data spans from 3 to 1 and is broken into 8 bins leading to each bin having a width of `(3 - 1) / 8 = 0.25`. 
The width of each bar is based on the perceived width of the graph. This perceived width does not take into account if sharex is enabled.

**Expected outcome**
Both graphs have the same number of bins and share the x axis so each bar on the histogram should have the same width.

**Matplotlib version**
  * Operating system: Windows
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 2.7.16 :: Anaconda, Inc.

**Comment by ImportanceOfBeingErnest** [comment]
If `bins=N` is a number, the bin width is `(data.max()-data.min())/N`. Always. This has nothing to to with sharing the axis limits tickers; but it's rather a consequence of the histogramming process. 

One can also view it from the inverse perspective. Suppose you can specify `bins=8` and get a different histogram out, depending on the axes you use for showing it. Such non-deterministic outputs of code are clearly undesired, so I think there is no interest in changing the current behaviour. 

Note that if you want to have the same binning used for several plots/datasets, you can always take the output of one and use if for the other

```
hist, bins, _ = ax.hist(....)
ax2.hist(..., bins=bins)
```

**Comment by jmbarefoot** [comment]
This bug happens regardless of if the number of bins is specified. If I were to use your suggestion (example below), then I could end up cutting off my data set and misrepresenting my data if I did not create the histograms in the correct order.

```python
import matplotlib.pyplot as plt

t1 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]
t2 = [1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3]

fig, axs = plt.subplots(2, 1, sharex='all', sharey='all')
_, bins, _ = axs[1].hist(t2)
axs[0].hist(t1, bins=bins)

plt.show()
```

In your example you said that the bin width is `(data.max()-data.min())/N`, and that makes sense. However the minimum and maximum should refer to the limits of the axis it is on.

Also if I set `bins=8`  and added a second graph under the pretense that they would be sharing the x axis, I would expect the first to change to share the x axis binning.

**If I took a histogram and removed a data point, should the binning change even when I set the axis limits? This seems even more undesirable.**

**Comment by jmbarefoot** [comment]
@ImportanceOfBeingErnest, Removing a single data point leads to vastly different results. I think you would agree this is much more non-deterministic. I would expect that removing the a single data point would result in the corresponding category in the histogram to decrease. If any other point besides the min or max were removed, this would be the case.

```python
import matplotlib.pyplot as plt

t1 = [1, 1, 2.3, 3, 3, 3, 3.9, 5, 6.3, 5, 9]
t2 = [1, 1, 2.3, 3, 3, 3, 3.9, 5, 6.3, 5]

fig, axs = plt.subplots(2, 1)

axs[0].set_xlim(1, 10)
axs[0].hist(t1, bins=5)

axs[1].set_xlim(1, 10)
axs[1].hist(t2, bins=5)

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/51932373/60550922-67396c00-9cde-11e9-9450-7125209923ef.png)

**Comment by timhoffm** [comment]
You are looking to fix the *bins* and the *range*. They cannot be automatically calculated taking into account multiple sets, but you can easily determine the rage yourself.

~~~
t1 = [1, 1, 2.3, 3, 3, 3, 3.9, 5, 6.3, 5, 9]
t2 = [1, 1, 2.3, 3, 3, 3, 3.9, 5, 6.3, 5]

fig, axs = plt.subplots(2, 1)

xmin = min(t1 + t2)
xmax = max(t1 + t2)

axs[0].set_xlim(1, 10)
axs[0].hist(t1, bins=5, range=(xmin, xmax))

axs[1].set_xlim(1, 10)
axs[1].hist(t2, bins=5, range=(xmin, xmax))

plt.show()
~~~

![grafik](https://user-images.githubusercontent.com/2836374/60551196-d3da5800-9d2a-11e9-9f4f-0541f17010ea.png)

**Comment by ImportanceOfBeingErnest** [comment]
> In your example you said that the bin width is (data.max()-data.min())/N, and that makes sense. However the minimum and maximum should refer to the limits of the axis it is on.

I disagree. A histogram is a mathematical/statistical construct. It is independent on how large the sheet of paper is you draw it on.

> If I took a histogram and removed a data point, ...

By that you change the statistics and hence, yes, you would expect a different histogram.

> ... I think you would agree this is much more non-deterministic.

No, because you can absolutely predict what will happen if you take that data point out.


If you're not happy with what `bins=N` (with `N` a number) does, which by the way is just following `numpy.histogram`, I would suggest to specify the bin edges directly via a list or array. That way you have full control over the binning yourself.

**Comment by jmbarefoot** [comment]
I don't completely agree that keeping the bar width independent despite a shared axis is correct, but you make a good point about the limitations of the function when run. It seems like `range=(xmin, xmax)` was the best design choice.
