### ISSUE TITLE
Heatmaps are being truncated when using with seaborn

### ISSUE THREAD

**Issue by mirage007** [matplotlib/matplotlib#14675]
### Bug report

**Bug summary**

The very top and bottom of the heatmaps are getting truncated to 1/2 height in version `3.1.1`. This does not happen for version `3.0.3`.

This is the code from a Jupyter Notebook
```python
import matplotlib
import pandas as pd
import numpy as np
import seaborn as sb
%pylab inline

print(matplotlib.__version__)
print(sb.__version__)

grid = pd.DataFrame(np.arange(9).reshape((3,3))/10)
fig, ax = subplots(1, 1, figsize=(5, 5))

sb.heatmap(grid, annot=True, fmt=".0f", ax=ax, cmap='RdBu',  vmin=0, vmax=1, cbar=True);
```
**Actual outcome**

```
Populating the interactive namespace from numpy and matplotlib
3.1.1
0.9.0
```

![download](https://user-images.githubusercontent.com/1696066/60530345-87f5c780-9cc6-11e9-9e31-a251283f3f7e.png)

**Matplotlib version**

  * Operating system: Ubuntu Linux
  * Matplotlib version: 3.1.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable): 4.4.0
  * Other libraries:

**Comment by jklymak** [comment]
It’s not clear what the issue is here.   Can you also give the expected outcome?  There have been changes to colorbar.  Perhaps seaborn was doing something low level and the changes didn’t interact well with their manipulations

**Comment by ImportanceOfBeingErnest** [comment]
This is a regression between 3.1.0 and 3.1.1. It bisects to https://github.com/matplotlib/matplotlib/pull/14579

Expected outcome would be 
![image](https://user-images.githubusercontent.com/23121882/60534085-55b58b80-9d01-11e9-8723-41afca57c07b.png)

**Comment by ImportanceOfBeingErnest** [comment]
Here is a pure matplotlib test case:

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

data = np.arange(9).reshape((3,3))/10

fig, ax = plt.subplots(1, 1, figsize=(3.5, 3.5))

ax.pcolormesh(data)
ax.set(xlim=(0, data.shape[1]), ylim=(0, data.shape[0]))

ax.invert_yaxis()
ax.set(xticks=np.arange(data.shape[1])+.5, 
       yticks=np.arange(data.shape[0])+.5)

ax.set_title(matplotlib.__version__)
plt.show()
```

**Actual outcome with 3.1.1**

![image](https://user-images.githubusercontent.com/23121882/60535153-c493e400-9d03-11e9-93fe-93d6b3916224.png)

**Expected outcome, as with 3.1.0**

![image](https://user-images.githubusercontent.com/23121882/60535256-fdcc5400-9d03-11e9-8af2-db75dcee0543.png)

**Comment by jklymak** [comment]
Ping @anntzer

**Comment by anntzer** [comment]
oops, see #14677.

**Comment by ImportanceOfBeingErnest** [comment]
There are by now 5 issues (including this) and 13 questions on stackoverflow within less than a month about this. Is there any plan to release 3.1.2 anytime soon?

**Comment by QuLogic** [comment]
@ivanov was in charge of releasing 3.1.1, but I'm not sure if he's doing 3.1.2. @tacaswell?

**Comment by talhakabakus** [comment]
Same here, hopefully, `3.1.2` will be released as soon as possible as I am not satisfied with the idea of reverting back to `3.1.0.` Any news regarding the release?

**Comment by jklymak** [comment]
It’s slated for sometime in September.  You can use master if you need this urgently and don’t want to roll back.

**Comment by talhakabakus** [comment]
> It’s slated for sometime in September. You can use master if you need this urgently and don’t want to roll back.

Thanks for the feedback.

**Comment by davidyakobovitch** [comment]
I have logged this issue with dozens of students with bootcamps and is consistent and still exists.  Is there an update on this? Is this update in the new rc? https://github.com/matplotlib/matplotlib/releases/tag/v3.2.0rc1

**Comment by jklymak** [comment]
Yes, its in the newly tagged release.
