### ISSUE TITLE
feature request: savefig as base64 for viewing in html

### ISSUE THREAD

**Issue by phineas-pta** [matplotlib/matplotlib#14699]
### Feature request

**Summary**

As seen in this [StackOverflow post](https://stackoverflow.com/questions/31492525/converting-matplotlib-png-to-base64-for-viewing-in-html-template), `savefig` method should be able to return base64 string to be inserted in HTML `img` element

**Actual workaround**

Save plot as file in hard disk then read, encode it in base64

```python
import matplotlib.pyplot as plt
from base64 import b64encode

plt.plot([0,1], [0,1])
plt.savefig('some_file.png')
plt.close()

plot_file = open('some_file.png', 'rb')
base64_string = b64encode(plot_file.read()).decode()
plot_file.close()

img_elem = '<img src="data:image/png;base64,{}"\>'.format(base64_string)
```

**Comment by jklymak** [comment]
I am not sure that the performance/API implications of this would justify it becoming part of `savefig`.  99% of people don't want this extra encoding step, and it will have a negative performance implication, so you'd want to be able to turn it off. At that point it may as well be its own method.

**Comment by tacaswell** [comment]
You can also pass a `BytesIO` object into to `savefig` (see https://matplotlib.org/faq/howto_faq.html#matplotlib-in-a-web-application-server and the SO post you reference) which avoids the disk I/O.

This is an interesting corollary to https://github.com/matplotlib/matplotlib/pull/6909 but I think allowing filename to be `None` and the returning `BytesIO` object is a better API to streamline this application.

Returning the base64 encoded sting of the image from `savefig` would also have rather negative impact on people working interactively as doing

```
>>> plt.plot(...)
[<matplotlib.lines.Line2D at 0x7fb5544d4160>]
>>> plt.savefig(...)
# WALL
# OF
# TEXT
```

as the interpreter prints out the returned string.

Additionally, even with in the web-server space, you may not want to always base64 encode the result.  It is my understanding that the string produced by the svg backend can be directly dropped into HTML.

So while I understand the motivation for this request, I think this is a specialization too far to put in core Matplotilb. 

Hopefully we will hear from you again @phineas-pta !

**Comment by phineas-pta** [comment]
thank you verymuch. it's very clear to me
