### ISSUE TITLE
Not support pyclustering and wxpython ???

### ISSUE THREAD

**Issue by liufsd** [matplotlib/matplotlib#14717]
full detail here:

https://github.com/annoviko/pyclustering/issues/524

**Comment by tacaswell** [comment]
What does `matplotlib.get_backend()` report?  My guess is that the pyplot import is selecting qt or tk as the GUI framework to use which is interfering with WX.

There is not enough information either here or in the pyclustering issue to really debug this, closing until we get more information.

**Comment by liufsd** [comment]
yes.  i have no any stacktrace about this. so i do not know how to fix this. just test code and report this issue.
