### ISSUE TITLE
drawstyle parameter of line needs example

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#14724]
`plot` takes a [drawstyle parameter](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html?highlight=drawstyle#matplotlib.lines.Line2D.set_drawstyle) that can be used to modify how the points are connected. 
```python
fig, ax = plt.subplots(figsize=(15,5))
_ = ax.plot(x, sin_x, drawstyle='steps')
_ = ax.set_aspect('equal')
```
![step](https://user-images.githubusercontent.com/1300499/60853228-125b9100-a1c9-11e9-9038-a4791a394446.png)

This isn't documented in the example gallery and it would be useful for someone to make an example in the same style as the [linestyle reference](https://matplotlib.org/gallery/lines_bars_and_markers/linestyles.html#sphx-glr-gallery-lines-bars-and-markers-linestyles-py)

**Comment by timhoffm** [comment]
This has a strong overlap with https://matplotlib.org/gallery/lines_bars_and_markers/step_demo.html and should be included there.

**Comment by sameshl** [comment]
@story645 I would like to take up this issue. As I understand you want documentation for drawstyle parameter in the same style as https://matplotlib.org/gallery/lines_bars_and_markers/linestyles.html#sphx-glr-gallery-lines-bars-and-markers-linestyles-py ?

**Comment by story645** [comment]
@sameshl basically, but really you should do what @timhoffm suggests & add on to the example he linked (and in a similar style).

**Comment by Avni-Sharma** [comment]
PTAL https://github.com/matplotlib/matplotlib/pull/15011
