### ISSUE TITLE
Line2D properties should state units

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#14720]
Right now `Line2D` `linewidth` parameter is a `float`.  That is nice to know, but it would be helpful to know that the float is points.  Same with `markersize`, and probably other kwargs.

**Comment by timhoffm** [comment]
Marking as good first issue. Please remove if you think it's too hard to find out without prior knowledge.

**Comment by jklymak** [comment]
Nah it should be trivial.  The set/get methods have the units, but that’s of little use to someone looking at the docs of “plot”.

**Comment by sameshl** [comment]
Hi @jklymak , I would like to work on this issue. Could you explain what you mean by "float is points"? And can you give me the reference of the documentation I would need to update.

**Comment by lukelbd** [comment]
@sameshl He means the physical units for the float number that sets line width and markersize is ["points"](https://en.wikipedia.org/wiki/Point_(typography)), i.e. 1/72 of an inch. This is also the unit used to determine font size btw.

**Comment by sameshl** [comment]
@jklymak , I looked into this issue and I think we need to update the https://github.com/matplotlib/matplotlib/blob/a25663ae601c7bd8282e73968b092e7cb3f9988f/lib/matplotlib/lines.py#L1091-L1098
for linewidth. Similarly, we need to do this for all setter functions of the kwargs.
But, I am not entirely sure how to do it, can you please help me out.

**Comment by sameshl** [comment]
@jklymak Could you review my PR and let me know if any more changes need to be done. :+1:
