### ISSUE TITLE
Segmentation fault using pdb.set_trace() after show()

### ISSUE THREAD

**Issue by mohawkjohn** [matplotlib/matplotlib#14742]
### Bug report

**Bug summary**

If I do `plt.show()`, close the plot, and then a `pdb.set_trace()` is executed, a segmentation fault occurs.

**Code for reproduction**

```python
#!/usr/bin/python3

import matplotlib.pyplot as plt
import pdb

fig = plt.figure()
plt.show()

pdb.set_trace()
```

**Actual outcome**

```
[3]    1156 segmentation fault (core dumped)  python3 plot_fail.py
```

**Expected outcome**

This should give me a pdb shell instead of a segmentation fault.

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

Python is installed via apt. I installed matplotlib using pip.

**Comment by anntzer** [comment]
I can't repro this locally.  Do you also get a segfault at exit if you just run a pyqt app like the following?
```
from PyQt5.QtWidgets import *
import pdb

app = QApplication([])
win = QMainWindow()
win.show()
app.exec_()

pdb.set_trace()
```
What happens if you use other backends, e.g. tkagg?

**Comment by mohawkjohn** [comment]
Ahh, yup, the pyqt app gives a segfault also. So it sounds like the problem is with PyQt5?

**Comment by anntzer** [comment]
1. yes, so I think we can close this issue?
2. yes, matplotlib now checks at runtime whether pyqt5, pygobject, etc. are available and picks the first working backend among qt5agg (which is mildly more polished), gtk3agg, ... tkagg.
