### ISSUE TITLE
Saving Figures as a PDF,  creates a black box around the plotting area

### ISSUE THREAD

**Issue by wsor330** [matplotlib/matplotlib#14753]
### Bug report

- Saving Figures as a pdf generates a black box, around the plotting area i.e. figure 1 below. The black box artifact is not present when the figure is saved as a ```.png``` file. I initially thought this was due to Metpy, so i have started an issue there, https://github.com/Unidata/MetPy/issues/1048, but it turns out that METPY might not be the reason for this bug and might be due to matplotlib.
```
# Imports
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
from metpy.interpolate import interpolate_to_grid as interpolate
import numpy as np

# Function for plotting
def slope_map(data):
    
    m = Basemap(llcrnrlon = 166, llcrnrlat = -47.4,urcrnrlon = 178.6, urcrnrlat = -33.5,
                resolution='i',projection='aea',lat_1=-47.5,lon_0=173,lat_0=-41)
    m.drawcoastlines(zorder = 20)
    
    cvals= data[:,0]

    cmap=plt.cm.bwr 

    #extract coords from dataframe and turn into a list as the map function gives an error if not.
    lons = (data[:,1]).tolist()
    lats = (data[:,2]).tolist()
    
    lons, lats = m(lons,lats) #convert to map projections
    
    # Interpolation
    gx, gy, img = interpolate(lons, lats, cvals, interp_type='cressman', hres=5000,search_radius = 25000,minimum_neighbors=1)
    
    #Plot
    m.pcolormesh(gx, gy, img, cmap=cmap,shading = 'gouraud',zorder = 10)

    return None

# Reproducible Data
lons = np.random.uniform(167, 177, size=(100, 1))
lats = np.random.uniform(-46, -34, size=(100, 1))
slopes = np.random.uniform(-10, 10, size=(100, 1))
data = np.column_stack([slopes,lons, lats])

# Use plotting function above
slope_map(data)

# Save figures
plt.savefig('foo.png') # Save as a photo, NO black box
plt.savefig('foo.pdf') # Save as a pdf, black box is apparent
```

Actual Output:
1st Figure is when the plot is saved as a pdf. - Black box artifact generated
[foo.pdf](https://github.com/matplotlib/matplotlib/files/3404375/foo.pdf)

2nd Figure is when the plot is saved as a .png file or what the SPYDER figure window shows - No black box artifact generated
![foo](https://user-images.githubusercontent.com/43772253/61422614-87b12980-a960-11e9-9001-00080e503284.png)

Console Output:
No errors given

**Expected outcome**
No black box around the plot after saving the figure as a pdf, should be similar to .png file. 

**Matplotlib version**

  * Operating system: WINDOWS 10
  * Matplotlib version: matplotlib=3.0.3=py37_0
  * Matplotlib backend (`print(matplotlib.get_backend())`):Qt5Agg
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: 
basemap=1.2.0=py37ha41f07c_2
basemap-data-hires=1.2.0=0
metpy=0.10.0=py37_1001
numpy=1.16.2=py37h8078771_1

Conda

Channels provided in anaconda.org

**Comment by jklymak** [comment]
This has far too many things going on for us to sensibly tell what the issue is.  Can you step by step remove things until you get to a minimal example that shows the problem?  For instance you are using PDF pages.  Is that necessary for the error?  Next.  there is no way for us to reproduce this.  Please reproduce with a synthetic data set.  Finally please try to minimize the imports to external packages

**Comment by wsor330** [comment]
Hi, thanks for the help, it does seem that the problem only occurs when saving figures as a pdf, i have tried to save it as a .png file and it is fine. I have tried to minimize the imports but can't seem to completely remove the 'basemap' module, as i keep getting errors, when ignoring the use of it.

**Comment by timhoffm** [comment]
The bug report is not narrowed down enough to be actionable from the Matplotlib side. If this is still an issue, please report back and we will discuss a way forward.
