### ISSUE TITLE
Improve dev installation documentation

### ISSUE THREAD

**Issue by shanosborne** [matplotlib/matplotlib#14755]
The current instructions for installing the dev version of matplotlib (specifically in the dev docs section here: https://matplotlib.org/devel/documenting_mpl.html) do not explicitly state that you need to uninstall the conda/pip version of matplotlib first (and maybe several times), before installing the dev version. Not uninstalling first can lead to really unhelpful and confusing errors, so it would be good to include that information in the documentation

**Comment by rcomer** [comment]
Sorry you didn’t get a response for so long @shanosborne!

I’m pretty sure these days when you install from source, pip automatically uninstalls any existing Matplotlib version.  Please comment or re-open if you think I have that wrong.
