### ISSUE TITLE
should cm be renamed to colormaps?

### ISSUE THREAD

**Issue by ivanov** [matplotlib/matplotlib#1476]
It's a bit confusing to have a proper module have such a short, non-descriptive name.

Looking at code that uses it, if one were to see `from matplotlib import cm` - they'd be left wondering what those two letters could possibly stand for. Then further down, they'd see it being used with a keyword argument that would shed some light, such as `cmap = cm.RdBu`, and they would maybe go through the steps of "oh, it's a map... probably a color map"...maybe...

If the import code was written as `from matplotlib import colormaps as cm`, it'd be more clear. We would retain the dangling `plt.cm` and have a dummy `matplotlib.cm` module which would just import everything from `matplotlib.colormaps`.

as a bonus, I think `plt.colormaps` should be retained, but the code and documentation for it should live inside this new colormaps module.

**Comment by petehuang** [comment]
This is still useful. In the meantime, the docs just need to make sure that any mention of colormap is accompanied by a note saying that the colormap module is indeed named `cm`. I think this is done fine so far, but something to be aware of.

**Comment by efiring** [comment]
Too late.  Not worth the disturbance.  Decided in the devel meeting on 2020-04-27.
