### ISSUE TITLE
SandboxViolation on EasyInstall

### ISSUE THREAD

**Issue by mikkokotila** [matplotlib/matplotlib#14782]
I got the following error message from a Travis [build](https://travis-ci.org/autonomio/dedomena/jobs/558778125) referencing back to matplotlib. Any idea what this is / what do with this?

```
Installed /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/Dedomena-0.0.6-py3.5.egg
Processing dependencies for Dedomena==0.0.6
Searching for twintel
Reading https://pypi.org/simple/twintel/
Downloading https://files.pythonhosted.org/packages/3a/f1/de2d538a8ffb55362f1a8710dc921035b32c53ee7a20cda789d19c95fe64/twintel-1.3.tar.gz#sha256=09f88f956c8cf618a34801a811bdac10c6cc5943862ceb3708bbf2f298a16b54
Best match: twintel 1.3
Processing twintel-1.3.tar.gz
Writing /tmp/easy_install-3t1yzx2q/twintel-1.3/setup.cfg
Running twintel-1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3t1yzx2q/twintel-1.3/egg-dist-tmp-au2twq58
error: SandboxViolation: mkdir('/home/travis/.config/matplotlib', 511) {}
The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.
This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
The command "python setup.py install" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by dstansby** [comment]
It looks like the problem comes when installing the `twintel` package, and not `Matplotlib` here. Exactly what command did you run to get the above output?

**Comment by QuLogic** [comment]
This is a bug in

**Comment by mikkokotila** [comment]
Thanks. It's strange that the error message referred to matplotlib:

`error: SandboxViolation: mkdir('/home/travis/.config/matplotlib', 511) {}`

**Comment by tacaswell** [comment]
This does seem to actually be us (and `twintel` is trying to install a dependency of which Matplotlib is a dependency) https://github.com/matplotlib/matplotlib/blob/e34c6efe4aa2bee4979c07434197b29c3c8e30bb/lib/matplotlib/__init__.py#L564-L567 on master https://github.com/matplotlib/matplotlib/blob/81e9ace61c7e0e48423cb96fbc1ca46101a61e4c/lib/matplotlib/__init__.py#L649-L660 on 2.2.x but it looks like we have always been doing this so it is not clear to me why this is just coming up now.

@mikkokotila Can you reproduce this locally or get anymore debugging information out of your CI?

**Comment by QuLogic** [comment]
This is not a new error. It's existed since [twintel was added to dedomena](https://travis-ci.org/autonomio/dedomena/builds/503548496). Setuptools is just better at sandboxing now.

**Comment by anntzer** [comment]
I agree with @QuLogic's analysis.  https://github.com/mikkokotila/twintel/pull/2 also likely fixed the issue.
