### ISSUE TITLE
Show user how to use Agg buffer in example

### ISSUE THREAD

**Issue by darkdragon-001** [matplotlib/matplotlib#14796]
Tell the user to use `Agg` via

    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

https://github.com/matplotlib/matplotlib/blob/507bd38add3b199ffc9148177e0781d9b3406793/examples/misc/agg_buffer_to_array.py#L8

---

An alternative is to explicitly create an Agg canvas via

    from matplotlib.backends.backend_agg import FigureCanvasAgg
    canvas = FigureCanvasAgg(fig)

as shown in this example

https://github.com/matplotlib/matplotlib/blob/507bd38add3b199ffc9148177e0781d9b3406793/examples/user_interfaces/canvasagg.py#L30

**Comment by tacaswell** [comment]
@darkdragon-001 Does the change in #14797 address your concern?

**Comment by darkdragon-001** [comment]
@tacaswell Thanks for your fast response.

Unfortunately, it doesn't work:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5791127bf4b1> in <module>()
      9 ax.plot([1, 2, 3])
     10 ax.set_title('a simple figure')
---> 11 fig.canvas.draw()
     12 
     13 # grab the pixel buffer and dump it into a numpy array

AttributeError: 'NoneType' object has no attribute 'draw'
```
