### ISSUE TITLE
control font weight more precisely from 0 to 1000

### ISSUE THREAD

**Issue by StevenLi-DS** [matplotlib/matplotlib#14801]
The font weight does not increase gradually from 0 to 1000, but only have three different stages that can be inspected visually.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.style.use('seaborn-white')

fig, ax = plt.subplots(figsize=(5, 20))

for i in range(51):
    fontweight = i * 20
    ax.text(0.1, i/30, f'fontweight: {fontweight}',
            weight=fontweight, fontsize=30,
            transform=ax.transAxes)

ax.set_axis_off()
```
![fontweight](https://user-images.githubusercontent.com/33796896/61304336-fe122800-a7b6-11e9-9c42-cd4f83fd748e.png)

**Expected outcome**

The users can control the font weight more precisely by using int from 0 to 1000

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.1
  * Matplotlib backend: 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.7.3

**Comment by anntzer** [comment]
Except for some fonts ("variable weight fonts", which are relatively rare and anyways totally unsupported by matplotlib at this point), it is not possible to interpolate the font between two weights.  See https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight (against which matplotlib's font system is modeled):
> In earlier versions of the font-weight specification, the property accepts only keyword values and the numeric values 100, 200, 300, 400, 500, 600, 700, 800, and 900; **non-variable fonts can only really make use of these set values**, although fine-grained values (e.g. 451) will be translated to one of these values for non-variable fonts using the Fallback weights system.

(emphasis mine)

Moreover if a font doesn't provide a certain weight value (e.g. 200), then we can't invent it either.
