### ISSUE TITLE
default tick formatter could switch to scientific notation earlier

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#14800]
### Bug report

**Bug summary**

The default tick formatter switches to scientific notation only for very small values, but there is a range of slightly bigger values where scientific notation would be better too.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.rcdefaults()
axs = plt.figure().subplots(2)
axs[0].set(xlim=(1e-7, 21e-7))
axs[1].set(xlim=(1e-8, 21e-8))
plt.show()
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1322974/61278107-da011780-a7b3-11e9-9ee0-0b1d95afbed5.png)

**Expected outcome**

Either the top axes should also use scientific notation (note that this also happens e.g. 1e-6 and 1e-5), or we need something smarter to determine the number of ticks.
IIRC the default ticker places ticks assuming that labels will have a width of no more than ~3 character heights(?), so allowing for 4-5 digits before switching to scientific notation may make sense.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: head, at least as far back as 3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 37
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
That’s my recollection.  Ticks are spaced 3*fontsize apart.

**Comment by timhoffm** [comment]
That's controlled by the rcParam `axes.formatter.limits = -7, 7`.

Note that the `%g` notation already writes 1e-5. On that basis, I'd be fine with switching to `-5, 5`. Probably, nobody wants to read more than four digits anyway. 0.0003 is just fine, but you really start counting with 0.00003.
