### ISSUE TITLE
add a plot showing all built-in font family to the doc

### ISSUE THREAD

**Issue by StevenLi-DS** [matplotlib/matplotlib#14803]
Please consider adding a plot that shows all the available built-in font family like the following:

![download](https://user-images.githubusercontent.com/33796896/61308193-b80c9280-a7bd-11e9-8a8a-85b04c1b092d.png)

I can find some of them from the following [plot](https://matplotlib.org/3.1.0/gallery/text_labels_and_annotations/fonts_demo.html), but I believe it's not comprehensive.

![sphx_glr_fonts_demo_001](https://user-images.githubusercontent.com/33796896/61307776-f2296480-a7bc-11e9-8b90-a005d0cd2642.png)

we have something similar for the color [here](https://matplotlib.org/3.1.0/gallery/color/named_colors.html) that shows all the named color, so a list of font-family would be very helpful.

**Comment by anntzer** [comment]
This depends on what's installed on your computer, so we can't really have a comprehensive list on the online docs.

**Comment by StevenLi-DS** [comment]
Hopefully someone could make it more readable.
```python
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager
plt.style.use('seaborn-white')

all_fonts = list(set([font.name for font in fontManager.ttflist]))

fig, ax = plt.subplots()

for index, font in enumerate(all_fonts):
    if index < 100:
        ax.text(0, index/10, f'{font}', family=font,
                fontsize=20, transform=ax.transAxes)
    else:
        ax.text(1.5, (index-100)/10, f'{font}', family=font,
                fontsize=20, transform=ax.transAxes)

ax.set_axis_off()

fig.savefig('fonts', dpi=600, facecolor='white', bbox_inches='tight')
```

![fonts](https://user-images.githubusercontent.com/33796896/61310837-138d4f00-a7c3-11e9-9693-74762a8c837f.png)

**Comment by timhoffm** [comment]
Thanks for considering how to improve matplotlib! However, as @anntzer wrote the actual available fonts are determined by your system not by matplotlib. Therefore, such a list is not suited for the online docs.

Additionally, when I tried to run this on Ubuntu 19.04, there are 401 fonts available, which do not even fit on a png.

> ValueError: Image size of 8740x66768 pixels is too large. It must be less than 2^16 in each direction.

Therefore, I'm closing as not feasible.

**Comment by StevenLi-DS** [comment]
Thanks for the explanations guys @anntzer @timhoffm
