### ISSUE TITLE
How to save hexbin binned data in a text file.

### ISSUE THREAD

**Issue by masabhathini** [matplotlib/matplotlib#14811]
### General Query

**summary**

Hi,

How can I save the hexbin data in a ascii format ?
https://github.com/matplotlib/matplotlib/issues/13985
I want to find the difference between previous hour - current hour lightning over a each hexbin.
i.e., I want to plot the change in previous hour and current hour.

regards,
M. Sateesh

**Comment by timhoffm** [comment]
The data is contained in the returned `PolyCollection`.

- Use `pc.get_offsets()` to obtain a Nx2 array of the hexagon centers.
- Use `pc.get_array()` to obtain a length-N array of the values associated with the hexagons.

**Comment by timhoffm** [comment]
Docs on this have been improved in #14839.
