### ISSUE TITLE
Unify set_3d_properties()

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#1482]
Different 3d artist objects have slightly different call signatures for set_3d_properties (mostly with regards to kwargs).  This should be consistent across all artist objects for mplot3d.

**Comment by petehuang** [comment]
@WeatherGod following up - can one of these be closed?

**Comment by WeatherGod** [comment]
Not really a duplicate, but I can see how it could be seen that way. The problem is that the mplot3d API is quite muddy. There isn't a clear delineation of responsibilities among methods. Part of this is due to a lack of a consistent API in the core matplotlib for setting artist data, which #1483 touches on, and probably should be modified to be generic (there might already be an issue made for that).
