### ISSUE TITLE
3d artist objects need clear and unified way to get/set 3d coordinate data

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#1483]
Because get_offsets() need to remain 2-D based for draw(), a separate function is needed to get and set the 3d coordinate data.  Currently, one would set the 2d offsets, and then use set_3d_properties() to set the 3rd dimension data, which is awkward.

Perhaps this is an opportunity to create a function in the base artist class strictly for raw coordinate data?  get/set_offsets() would then be intended more for display/transform purposes but would often be the same as the new methods.  Also, this would help clear up confusion where some artists have get/set_array(), get/set_data() and get/set_offsets() all for coordinate data.  A unified method would be valuable for documentation purposes.

**Comment by WeatherGod** [comment]
This would be a great low-hanging fruit task for SciPy 2015 sprints

**Comment by pelson** [comment]
I agree that the *doing* of this is simple, but I don't think it is an easy thing todo unless we can be very specific about what is required (unless one of us were doing it, rather than a newcomer to the project).

**Comment by OceanWolf** [comment]
Hmm, by the description above, do I understand that we want to separate out the screen stuff from the axes stuff because we shouldn't assume them as identical...?

I would imagine we should make this generic for all coordinate systems, not just 3d, what do we do with polar axes coordinates, and ``basemap``?

**Comment by jklymak** [comment]
I'm ging to close this as being very old, and probably not pertinent, or if it is, no one has picked up on it...  Feel free to request a re-open...

**Comment by scottshambaugh** [comment]
Related to https://github.com/matplotlib/matplotlib/issues/784
