### ISSUE TITLE
DOC: Webpage not formated correctly on gallery docs

### ISSUE THREAD

**Issue by sameshl** [matplotlib/matplotlib#14831]
**Bug summary**
The webpage rendered for `https://matplotlib.org/3.1.1/gallery/index.html#subplots-axes-and-figures` does not have properly aligned text under  `Zooming in and out ...`. The title of the example is too big to fit that. I could work on it but I am not entirely sure if I is just on my pc

**Actual outcome**
![zooming](https://user-images.githubusercontent.com/43701530/61384115-8e429100-a8cd-11e9-9933-98af9b545d0a.png)

**Comment by jklymak** [comment]
That is certainly a poor title

**Comment by timhoffm** [comment]
Layout-wise, that would have to be addressed in sphinx-gallery. OTOH, I don't think one wants to grow the tiles indefinitely.

Parctically, we should better come up with a shorter title.
