### ISSUE TITLE
import matplotlib.pyplot as plt forces out from python interactive mode

### ISSUE THREAD

**Issue by bit-scientist** [matplotlib/matplotlib#14841]
**Bug summary**

I have a conda env with matplotlib version=2.2.2, and after activating the env (tfgpu36) I usually type python to enter into the interactive mode. There I typed 
`import matplotlib.pyplot as plt`, it exited out from interactive mode
>

**Code for reproduction**

```python
(tfgpu36) D:\self_learning>python
Python 3.6.8 |Anaconda custom (64-bit)| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt

(tfgpu36) D:\self_learning>
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8
  * Other libraries:  pillow 5.4.1, opencv 3.4.3
`conda list` output for matplotlib:
`matplotlib                2.2.2            py36had4c4a9_2    anaconda`

As for running a sample file in the env itself:
I have a **code.py** in my _D:\self_learning_ and **1.jpeg** image
code.py content:
```
from skimage.color import rgb2gray
import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy import ndimage

image = plt.imread('1.jpeg')
print(image.shape)
plt.imshow(image)
```
if I do `python code.py` in  _D:\self_learning_, this as well produces nothing.
I hope I included everything. 
Thanks.

**Comment by timhoffm** [comment]
Sorry that there was no response. Not worth following up after years. If this is an issue with current matplotlib, please open a new ticket.

**Comment by rcomer** [comment]
@timhoffm did you intend to close this one?
