### ISSUE TITLE
duecredit integration for citation

### ISSUE THREAD

**Issue by clbarnes** [matplotlib/matplotlib#14856]
duecredit ( https://github.com/duecredit/duecredit ) is a package which helps people cite the software they're using. Maintainers put a small stub file in their package which usually does nothing (adding practically no overhead): however, when imported through duecredit, it allows the caller to automatically pick up the maintainer's preferred citation information. For any script/package a user may have written, citations associated with all imported packages, classes, and functions can be automatically gathered and exported. 

Matplotlib is used heavily in scientific workflows and I strongly suspect that it is under-cited. duecredit presents a solution which the python scientific ecosystem could benefit from investing in (IMO).

Zenodo makes it a little bit tricky because obviously the release has to be shipped before it gets a DOI, and by then it's too late to include that DOI in the package you've just shipped, but certainly the 2007 paper, any published algorithms used within matplotlib, and the "latest" version could all be cited.

**Comment by anntzer** [comment]
We already provide a `__bibtex__` attribute at the toplevel 
https://github.com/matplotlib/matplotlib/blob/6870ac00097508411c10d67b96f9863d597d04aa/lib/matplotlib/__init__.py#L154
perhaps duecredit could just read that? (makecite, a project that appears at least superficially similar to duecredit, already scrapes those: https://github.com/adrn/makecite/blob/fa3b4a61a2fed3af936038cb0980cb4267919f69/CHANGES.rst)

Having to add a dependency just for this purpose seems a bit heavy-handed.

**Comment by clbarnes** [comment]
It doesn't add a dependency - it adds a single stub file. Duecredit would not be required to run matplotlib; however, if a matplotlib user was using duecredit, they would be able to cite it properly.

**Comment by anntzer** [comment]
Ah, I see, it's basically vendoring a tiny version of itself.  Still, I think it could just read `__bibtex__`?  Extra points if it parses a doi field from the bibtex data :p

**Comment by anntzer** [comment]
Closing as currently handled by https://github.com/duecredit/duecredit/pull/153, and I still think duecredit could just read `matplotlib.__bibtex__`.
