### ISSUE TITLE
Pandas 0.25 breaks tests

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#14859]
@jklymak Thanks! And yes, it's the pandas 0.25.0 that causes the failure, 0.24.2 was fine.

Can we change the `test_bar_pandas(pd)` to following to avoid this failure?

```python
def test_bar_pandas(pd):
    # Smoke test for pandas
    pd.plotting.register_matplotlib_converters()
    fig, ax = plt.subplots()

    df = pd.DataFrame(
        {'year': [2018, 2018, 2018],
         'month': [1, 1, 1],
         'day': [1, 2, 3],
         'value': [1, 2, 3]})
    df['date'] = pd.to_datetime(df[['year', 'month', 'day']])

    monthly = df[['date', 'value']].groupby(['date']).sum()
    dates = monthly.index
    forecast = monthly['value']
    baseline = monthly['value']
    ax.bar(dates, forecast, width=10, align='center')
    ax.plot(dates, baseline, color='orange', lw=4)
    pd.plotting.deregister_matplotlib_converters()
```

i.e. register at beginning and deregister at the end.

_Originally posted by @bingyao in https://github.com/matplotlib/matplotlib/pull/14739#issuecomment-513235994_

**Comment by jklymak** [comment]
@bingyao I think thats good as a stopgap measure.  Can you do in a separate PR however so we can keep it straight?  *Don't* close this issue though, because we should get to the root of the problem!  Thanks for figuring this out!

**Comment by bingyao** [comment]
@jklymak  Okay, I will open a separate PR right away.

**Comment by dstansby** [comment]
Quick update as I look into this; it seems that `pd.plotting.deregister_matplotlib_converters()` changed somehow in `0.25`, and also de-registers our built in datetime converters, so I think this might be an upstream bug.

**Comment by timhoffm** [comment]
Fixed in newer pandas versions. https://github.com/pandas-dev/pandas/pull/27481
