### ISSUE TITLE
Weird behavior when `imshow()`ing a subclass of `ndarray` with dimensionaility constrained.

### ISSUE THREAD

**Issue by Varato** [matplotlib/matplotlib#14877]
## My code

I want to implement a subclass of numpy` ndarray` as follows.

```Python
# image.py
import numpy as np
import matplotlib.pyplot as plt


class Image(np.ndarray):
    def __new__(cls, input_array: np.ndarray):
        if input_array.ndim != 2:
            raise ValueError(f"An Image must be constructed from 2D array, but {input_array.ndim:d}D received")
        obj = np.array(input_array, copy=False).view(cls)
        return obj  # returns an Image's instance

    def __array_finalize__(self, viewed):
        # This method is called when (just before?) numpy constructs a new array.
        # viewed here is the object where the new array has been constructed from
        # viewed is None if it's been constructed from no where.
        if viewed is not None:
            if viewed.ndim != 2:
                raise ValueError(f"A {viewed.ndim:d}D array is being viewed as an Image. Expect 2D.")

    # other methods
```
My goal is to have, as [numpy_doc#`__array_finalize__`][numpy_doc#`__array_finalize__`] implies, a 2D-only array-like type with some other methods. And I want instances of my `Image` can directly be `imshow()`ed. But it goes wrong: 

```
$ python -i image.py
>>> im = Image(np.random.rand(5,5))
>>> plt.imshow(im)
>>> plt.show()
Traceback (most recent call last):
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 83, in _draw
    self.figure.draw(renderer)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 593, in draw
    renderer, renderer.get_image_magnification())
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 841, in make_image
    unsampled=unsampled)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 407, in _make_image
    vmid = self.norm.vmin + dv / 2
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py", line 4063, in __add__
    return add(self, other)
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py", line 1013, in __call__
    (da, db) = (getdata(a), getdata(b))
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py", line 714, in getdata
    data = a._data
  File "/Users/xinchen/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py", line 3575, in _get_data
    return ndarray.view(self, self._baseclass)
  File "image.py", line 18, in __array_finalize__
    raise ValueError(f"A {viewed.ndim:d}D array is being viewed as an Image. Expect 2D.")
ValueError: An 0D array is being viewed as an Image. Expect 2D.
```

## Traceback

Turns out the `Image` instance `im` is firstly cast into a `MaskedArray` and then passed into the `Normalize.autoscale_None()`. And inside `autoscale_None()` `vmin`, `vmax` are computed. See the following snippet and gh-links.

```Python
# matplotlib/image.py

class _ImageBase(martist.Artist, cm.ScalarMappable):
    # ...
    def setdata(self, A):
        
        self._A = cbook.safe_masked_invalid(A, copy=True) # here A is converted to <numpy.ma.core.MaskedArray>. *A.baseclass* is Image
        # ...
        
    # ...
    def _make_image(self, A, in_bbox, out_bbox, clip_bbox, magnification=1.0,
                    unsampled=False, round_to_pixel_border=True):
        # ...
        self.norm.autoscale_None(A)  # this makes self.norm.vmin also a <numpy.ma.core.MaskedArray>
        dv = (np.float64(self.norm.vmax) -
              np.float64(self.norm.vmin))
        vmid = self.norm.vmin + dv / 2  # THE ADDING HERE IS THE PROBLEM
        # ...
    # ...
```
https://github.com/matplotlib/matplotlib/blob/520b5f65dd61735c5d13b34fa638b97600140cc4/lib/matplotlib/image.py#L431-L433

https://github.com/matplotlib/matplotlib/blob/520b5f65dd61735c5d13b34fa638b97600140cc4/lib/matplotlib/colors.py#L1032-L1038

## The problem is:

1. After cast, the `MaskedArray` -- `A` in `autoscale_None()` -- has its `baseclass` as `Image`.
2. Somehow, `A.min()` returns a 0D `MaskedArray` rather than a scalar, which makes `self.norm.vmin` in `_imageBase._make_image()` a `MaskedArray` with `baseclass` `Image` as well.
3. When the adding occurs at `vmid = self.norm.vmin + dv / 2`, numpy conducts a view-cast from the `MaskedArray` to its `baseclass` (which is `Image` here). See the following snippets 

    ```Python
    # numpy/ma/core.py
    
    # ...
    def getdata(a, subok=True):
        try:
            data = a._data
        except AttributeError:
            data = np.array(a, copy=False, subok=subok)
        if not subok:
            return data.view(ndarray)
        return data
    # ...
    class _MaskedBinaryOperation(_MaskedUFunc):
        # ...
        def __call__(self, a, b, *args, **kwargs):
            # Get the data, as ndarray
            (da, db) = (getdata(a), getdata(b))
            # ...
    # ...
    add = _MaskedBinaryOperation(umath.add)
    # ...
    class MaskedArray(ndarray):
        # ...
        def _get_data(self):
            """Return the current data, as a view of the original
            underlying data.

            """
            return ndarray.view(self, self._baseclass)  # here self._baseclass is my Image class. So its view-casted to Image
        # ...
        _data = property(fget=_get_data)
        data = property(fget=_get_data)
        # ...
        def __add__(self, other):
            return add(other, self)
    ```
    
    See [this][numpy/core.py at 691e6dbe1fd70c7638daf3ab38e877419babeed2 · numpy/numpy · GitHub] for source code.
4. But `self.norm.vmin` is a 0D `MaskedArray`, which makes the view-casting raise the exception in `__array_finalize__` of `Image`.

## A possible fix
I thinks (at least) in `autoscale_None()`, `self.vmin` is supposed to be a scalar. So explicitly convert `A.min()`, `A.max()` to scalars may be enough.
Though very unlikely some one would code like this, it might be helpful for future Googlers.

**Matplotlib version**

  * Operating system: macOS Mojave 10.14.5
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.5

[numpy_doc#`__array_finalize__`]: https://numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array_finalize__
[numpy/core.py at 691e6dbe1fd70c7638daf3ab38e877419babeed2 · numpy/numpy · GitHub]: https://github.com/numpy/numpy/blob/691e6dbe1fd70c7638daf3ab38e877419babeed2/numpy/ma/core.py#L3582-L3597

**Comment by tacaswell** [comment]
Wouldn't it be simpler to handle this in your class to accept 2D or 0D?

```

**Comment by tacaswell** [comment]
I'm going to close this as I believe the correct fix is to add the `__array_wrap__` method to OPs ndarray sub-class.

**Comment by Varato** [comment]
Thanks a lot for the help!

**Comment by tacaswell** [comment]
@Varato Your welcome!

I know you did not come here for a lecture on software design, but I strongly suggest you re-consider this path.  Having a bunch of functions that operate on 2D arrays is a better design than having a bunch of methods on your 2D array.  Functions that operate on 2D arrays well seamlessly inter-operate with all of the functions from skimage and from scipy.ndimage in a way that feels 'first-party' from the user point of view.  Additionally, if `__array_function__` succeeds in it's goals, then function that take arrays will work with dask arrays / cupy arrays / etc where as your methods well be tied to your `np.ndarray` subclass.
