### ISSUE TITLE
Categoricals not showing up in the preview window

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#14881]
As reported by  @wuweihust on gitter,  string categorical tick labels don't show up in the preview window of an interactive plot:
```python
%matplotlib notebook
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot(['hi', 'bye', 'why'], [3,1,2])
```
<img width="514" alt="error" src="https://user-images.githubusercontent.com/1300499/61806958-a69f3800-ae06-11e9-8483-4d36bec7bb1b.PNG">

On gitter, @jklymak recommend implementing the `format_data_short` method for the [StrCategoryFormatter](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/category.py#L130). 

The implementation should probably be something like the [default](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/ticker.py#L261):

```python  
    def format_data(self, value):
        return self.__call__(value)

    def format_data_short(self, value):
        return self.format_data(value)
```

Which, as an aside, why aren't these called given `StrCategoryFormatter` inherits from `Formatter`?

**Comment by jklymak** [comment]
It probably does, but the float x=1.342 doesn't map to "1" properly?

**Comment by story645** [comment]
But it should be hitting `self.__call__` which is:
```python
def __call__(self, x, pos=None):
    return '' if pos is None else self.format_ticks([x])[0]
```
and `self.format_ticks` does the lookup:
```python
 def format_ticks(self, values):
        r_mapping = {v: self._text(k) for k, v in self._units.items()}
        return [r_mapping.get(round(val), '') for val in values]
```
unless it's hitting `__call__` in `Formatter`?

**Comment by QuLogic** [comment]
But `pos` would be `None`, so it would return `''`.

**Comment by story645** [comment]
Hmm, so then it probably is hitting 'format_data' and 'format_data_short', but the fix needs to be on '__call__' to not return ' '

**Comment by Longrich1992** [comment]
Your welcome

**Comment by lepuchi** [comment]
Hello, is anyone working on this? I would like to pick it up otherwise.

**Comment by timhoffm** [comment]
@lepuchi You’re welcome. Go for it!
