### ISSUE TITLE
Future support for 4D plots

### ISSUE THREAD

**Issue by ruidazeng** [matplotlib/matplotlib#14882]
Is 4D plotting potentially possible for matplotlib? 

I am currently graphing hundreds of quadruples (4-tuples) using matplotlib using
```python
from matplotlib import pyplot as plt
from mpl_toolkits import mplot3d
plt.axes(projection='3d')
```
I am thinking that perhaps there could a similar module like `mplot3d` that might allow us to plot 4D graphs in the future.

**Comment by WeatherGod** [comment]
you can use the animation module with mplot3d, if that's what you mean by
4D?

**Comment by story645** [comment]
Can you please provide a sample image of what you mean by 4D?

**Comment by ruidazeng** [comment]
I was looking for 4-dimensional objects whose locations locations in 4D space can be given as vectors or n-tuples, i.e. as ordered lists of numbers such as (t,x,y,z). 

Two of the examples I can think of are Clifford-torus and tesseract, respectively. I have attached a sample image of a tesseract below.

![Tesseract](https://upload.wikimedia.org/wikipedia/commons/5/55/8-cell-simple.gif?w=500)

**Comment by jklymak** [comment]
That’s just animated 3D plot so I’ll close this.  You may also want to look at mayavi for three d plotting.  Thanks!
