### ISSUE TITLE
kerning seems generally wrong

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#14887]
### Bug report

**Bug summary**

Matplotlib seems to fail to apply kerning correctly.

**Code for reproduction**

```python
figtext(.5, .5, "AV", size=36); figtext(.5, .4, "Te", size=36)
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1322974/61868122-02d28c80-aed9-11e9-9139-63c4b26c9a43.png)
and similarly for pdf/ps/svg output.

**Expected outcome**

with mplcairo, one gets:
![cairo](https://user-images.githubusercontent.com/1322974/61868151-0ebe4e80-aed9-11e9-8b3b-758f2ccbd382.png)

Note that it's not that matplotlib doesn't apply kerning at all -- there is definitely code a bit everywhere to apply it, but it looks like we're getting wrong values.  See also https://matplotlib.org/gallery/misc/font_indexing.html which shows that get_kerning apparently returns 0 when it shouldn't.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg/mplcairo
  * Python version: 37
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
I think I've figured this out, but I don't expect this to be good for our test images...

**Comment by anntzer** [comment]
I guess we could fix https://github.com/matplotlib/matplotlib/issues/9681 (kill hinting_factor) at the same time, if we do go that route :p

**Comment by QuLogic** [comment]
Hmm, well that one breaks an order of magnitude more tests, so perhaps not as easy as this one. maybe even possible to fix it with some rc param that allows not changing any test.

**Comment by anntzer** [comment]
Fair enough.
