### ISSUE TITLE
Make table cell text multiple rows

### ISSUE THREAD

**Issue by PradeepGaneshbabu** [matplotlib/matplotlib#14885]
Sorry, this might have already been asked

![image](https://user-images.githubusercontent.com/47116729/61833336-d4957400-ae28-11e9-85e5-26e8f4094f8f.png)

Can someone tell me how I can move these cell texts to multiple rows?

**Comment by swfiua** [comment]
Change the commas between items to newlines?
If x is your text:
x = x.replace(',', '\n')
but current table code will keep all cells the same height, so that might not look so good.

There's an improved table in my blume project:

https://github.com/swfiua/blume/blob/master/blume/table.py
