### ISSUE TITLE
New yticks behavior in 3.1.1 vs 3.1.0

### ISSUE THREAD

**Issue by caldwellshane** [matplotlib/matplotlib#14897]
### Bug report
I'm using `imshow`, and between 3.1.0 and 3.1.1 the behavior of the extents of the plot has changed when using `Axes.set_yticks`. In 3.1.0, and in 3.1.1 when not calling `set_yticks`, the plot includes the outer 0.5 bin in the top and bottom rows. This is the desired behavior. But in 3.1.1 when using `set_yticks`, the outer 0.5 bin in the top and bottom rows is not included in the plot. 

**Code for reproduction**
```python
import matplotlib
import matplotlib.pyplot as plt

xy = [[1, 3], [2, 4]]
fig, ax = matplotlib.pyplot.subplots(1)
ax.imshow(xy)
ax.set_xticks([0, 1])
ax.set_xticklabels(["0", "1"])
ax.set_yticks([0, 1])
ax.set_yticklabels(["0", "1"])
fig.savefig(f"matplotlib-v{matplotlib.__version__}.png")
```
The behavior changes in 3.1.1 if `ax.set_yticks([0, 1])` is commented out.

Desired behavior
![image](https://user-images.githubusercontent.com/6991781/61991111-66a3a500-b000-11e9-9ad2-04613b8a1a81.png)

Behavior in 3.1.1 with `set_yticks`
![image](https://user-images.githubusercontent.com/6991781/61991098-4aa00380-b000-11e9-84b4-303fde60972c.png)

**Matplotlib version**
  * Operating system: Mac OS 10.14.5
  * Matplotlib version: 3.1.1
  * Matplotlib backend: agg
  * Python version: 3.7.3
  * Jupyter version (if applicable): N/A
  * Other libraries: Fresh conda install of just matplotlib, using conda-forge

**Comment by anntzer** [comment]
Thanks for the report, this was already reported in https://github.com/matplotlib/matplotlib/issues/14675 and fixed in https://github.com/matplotlib/matplotlib/pull/14677 (please confirm master works for you).

**Comment by caldwellshane** [comment]
Thanks! Yes, master is (`__version__ = 3.1.0.post1561+g8d3e817d3`) is working.
