### ISSUE TITLE
'MPLBACKEND=webagg' is overwritten by agg when $DISPLAY is not set on Linux

### ISSUE THREAD

**Issue by GreenCourt** [matplotlib/matplotlib#14903]
## Bug report

* The environment variable `MPLBACKEND=webagg` is overwritten by 'agg' when $DISPLAY is not set on Linux.
* The behavior of  `backend:webagg` written in matplotlibrc was as same as `MPLBACKEND=webagg` (I tried).
* I want to avoid hard-coding the backend to .py file, because I use the same code on other environment.

**Code for reproduction**

```
# matplotlibrc
webagg.open_in_browser : False
webagg.address : 0.0.0.0
```

```python
# test.py
import matplotlib.pyplot as plt
print(plt.get_backend())
```

**Actual outcome**

When I type the shell command `MPLBACKEND=WebAgg DISPLAY= python test.py`,

```
agg
```

the backend is overwritten by agg.

When I type the shell command `MPLBACKEND=WebAgg DISPLAY=:0 python test.py` (although X11 is not installed),

```
WebAgg
```

I can use webagg.

**Expected outcome**

When I type the shell command `MPLBACKEND=WebAgg DISPLAY= python test.py`,

```
WebAgg
```

* I want to use webagg even when X11 is not installed.
* I want to use the environment variable MPLBACKEND to avoid hard-coding the backend.

**Question**

Does matplotlib overwrite the backend by 'agg', when `$DISPLAY` is empty?
I understand that the fallback behavior is useful.
However, is there any reason that webagg must be fallbacked to agg?

Or, is there a correct way (not setting the `$DISPLAY`) to avoid the fallback behavior?

**Matplotlib version**
  * Operating system: Debian 10
  * Matplotlib version:  3.1.0
  * Python version: 3.7.3 (anaconda)

**Comment by tacaswell** [comment]
That is definitely a bug in the fallback logic to make sure we don't try to use a GUI backend on a headless server.  I suspect we have miss-categorized `webagg` as a GUI backend.

**Comment by GreenCourt** [comment]
Thanks for your reply!
Also, if `webagg.open_in_browser` is automatically set to `False` when `$DISPLAY` is not set,
I think it is very convenient.

**Comment by anntzer** [comment]
The short term fix is to add webagg to https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L44.  The long term fix is... we need to figure out what rcParams["backend_fallback"] really means.

**Comment by anntzer** [comment]
this was requested many times when the fallback was not present (you can search the issue tracker), so heh.

**Comment by GreenCourt** [comment]
Thanks for your work!
