### ISSUE TITLE
PDF logo glitchy, has extra features

### ISSUE THREAD

**Issue by joelfrederico** [matplotlib/matplotlib#14939]
## Bug report

The PDF logo doesn't look quite right, viewed in Adobe Acrobat, Preview, and Google Chrome (on macOS). If you look closely at the center, there are some extra features there that don't show up in, for instance, the svg.

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/images/matplotlib.pdf

Maybe somebody should track down why the render of the PDF glitched? At least replace it with one that isn't glitchy?

![image](https://user-images.githubusercontent.com/458871/62189030-de384380-b322-11e9-9259-28bbf118c7f2.png)

**Comment by joelfrederico** [comment]
For what it's worth, when I use the the script and save to PDF, I get the features as well.

**Comment by anntzer** [comment]
This basically comes from https://github.com/matplotlib/matplotlib/issues/9830.  FWIW one can check with mplcairo master that setting the miter_limit (globally, via `mplcairo.set_option(miter_limit=5)`) fixes the issue.

**Comment by joelfrederico** [comment]
Ah gotcha. Close the issue as a duplicate then?

**Comment by anntzer** [comment]
Sure, added a note in #9830 so that we remember that the logo needs to be regen'd.
