### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by pylang** [matplotlib/matplotlib#14959]
### Bug report

**Bug summary**

I believe there is a typo in the title of a [subplots demo page][0].

**Actual outcome**

"Creating multiple subplots using `plt.subplot`"

**Expected outcome**

"... using `plt.subplots`"

The examples on the page refer to `plt.subplots()` not `plt.subplot()`

**Matplotlib version**

  * Matplotlib version: 3.1.1

  [0]: https://matplotlib.org/3.1.1/gallery/subplots_axes_and_figures/subplots_demo.html#creating-multiple-subplots-using-plt-subplot

**Comment by sameshl** [comment]
This has already been fixed in the master branch. The docs will be updated in the next matplotlib release.

@timhoffm We can close this issue.

**Comment by QuLogic** [comment]
Fixed by #14688.
