### ISSUE TITLE
Padding with spaces does not work with PGF

### ISSUE THREAD

**Issue by physkets** [matplotlib/matplotlib#14970]
### Bug report

**Bug summary**

Since TeX does not recognize spaces, padding a number does not produce the expected result, because appropriate curly brackets are not used.

**Code for reproduction**

```python
NUM = 42
# Use the following string as annotation or label in a plot:
TEXT = f'N = {NUM:>5d}'
```

**Actual outcome**

```tex
\pgftext[...]{ ... \selectfont N =    42}%
```

**Expected outcome**

```tex
\pgftext[...]{ ... \selectfont N = {   42}}%
```

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.1.1
  * Matplotlib backend: pgf
  * Python version: 3.7.3
  * Other libraries: texlive: 2019.51075

Using the `python-matplotlib` package in the Archlinux repository.

**Comment by ImportanceOfBeingErnest** [comment]
Using `TEXT = f'N={{{NUM:>5d}}}'` one would get the pgf output `\selectfont N={   42}`. However, would that help? Spaces are in generally ignored by latex, so the output would be the same, right?

**Comment by physkets** [comment]
No, its not the same; in the latter case, it does add some space (although not as much as required).

**Comment by timhoffm** [comment]
I don't think the number of spaces in the inner bracket would change anything. Shouldn't the output be
~~~
\pgftext[...]{ ... \selectfont N = \ \ \ 42}%
~~~

Still, if you're not using a monotype font, the output is likely not to be as desired. In particular alignment over multiple lines is not guaranteed.
