### ISSUE TITLE
Is there a way to set_zticks in a customized way ?

### ISSUE THREAD

**Issue by bhuvanshukla** [matplotlib/matplotlib#14980]
### Bug report

**Bug summary**
I'm unable to find anywhere that we can set the `ztick` like `xtick` and `ytick` or is there a way ?

**Code for reproduction**
```
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111)
x= np.linspace(-math.pi,math.pi,30)
y= np.linspace(-math.pi,math.pi,30)
xx,yy = np.meshgrid(x,y)

X_grid, Y_grid = np.meshgrid(x,y)
print("X_grid shape: ",X_grid.shape)
zz =-2*(np.cos(xx) + np.cos(yy))

#ax = plt.axes(projection='3d')
ax = Axes3D(fig)
ax.plot_surface(xx,yy,zz)

plt.xticks([x[0],x[int(len(s)/2)], x[-1]], [r'$-\pi$',  r'$0$', r'$-\pi$' ])
plt.yticks([y[0],y[int(len(s)/2)], y[-1]], [r'$-\pi$',  r'$0$', r'$-\pi$' ])
plt.xlabel("kx")
plt.ylabel("ky")
```
**Actual outcome**
Please see [this](https://imgur.com/2gKygjK).

**Expected outcome**
In output `z-axis` should have the values like `x` and `y` axis ( `[-math.pi,0,math.pi]` ).

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: '2.2.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: Python 3.6.5

Working on `Spyder`.

**Comment by timhoffm** [comment]
There is no support for 3D plots through the pyplot interface. You need to work with the Axes object.

~~~
plt.xticks(locs, labels)
~~~
is equivalent to
~~~
ax.set_xticks(locs)
ax.set_xticklabels(labels)
~~~

and there are `ax.set_zticks()` and `ax.set_zticklabels()` methods as well.

**Comment by bhuvanshukla** [comment]
Where is the documentation for that, i'm unable to find it [here](https://matplotlib.org/3.1.1/api/axes_api.html). Please can you provide the link ?

**Comment by WeatherGod** [comment]
https://matplotlib.org/api/toolkits/mplot3d.html

The 3d capabilities are implemented in a separate module because it isn't
as fully featured as typical 2d plotting.

**Comment by ImportanceOfBeingErnest** [comment]
Presumably the problem is that while [`.set_zticks`](https://matplotlib.org/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_zticks) and [`.set_zticklabels`](https://matplotlib.org/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_zticklabels) are documented for the `Axes3D`, this is not the case for the `x` and `y` variants, because they are inherited from the 2D axes?

**Comment by bhuvanshukla** [comment]
I will try this and update here possibly in around 13 hours from now.

**Comment by bhuvanshukla** [comment]
The line `ax.set_zticks([z[0],z[int(len(z)/2)], z[-1]], [r'$-\pi$',  r'$0$', r'$-\pi$' ])` is still having no effect on the output. Note: I have used the statement `ax = Axes3D(fig)`.

**Comment by timhoffm** [comment]
As written here https://github.com/matplotlib/matplotlib/issues/14980#issuecomment-518156902 you must use

~~~
ax.set_zticks([z[0],z[int(len(z)/2)], z[-1]])
ax.set_xticklabels([r'$-\pi$', r'$0$', r'$-\pi$' ])
~~~

**Comment by bhuvanshukla** [comment]
Thank you. really sorry for not trying that.

**Comment by Sahuta** [comment]
Hi, related to this issue, is there any method like plt.rcParams['xtick.direction"] about z ticks?

**Comment by WeatherGod** [comment]
No, I don't think that is implemented at all. The 3d tickmark code is very
different from the 2d version, so they don't share a lot of features
currently.
