### ISSUE TITLE
Overlapping text when using subplots

### ISSUE THREAD

**Issue by annacnev** [matplotlib/matplotlib#14984]
### Bug report

**Bug summary**

When using subplots, is there a fix to stop the title of the second subfigure from overlapping with the x-axis label of the first? The plots are related so I would like to keep them as the same figure. 

**Code for reproduction**

```
import numpy as np
from matplotlib.pyplot import figure, subplot, plot
import matplotlib.pyplot as plt


figure(32)
subplot(211)
plot(np.linspace(0, 5, 20), np.random.randint(100, size=20))
plt.title('Right Ventricle volume  ')
plt.xlabel('Frame relative time (seconds')
plt.ylabel('volume(ml)')
subplot(212)
plot(np.linspace(0, 5, 20), np.random.randint(100, size=20))
plt.title('Right Ventricle fow')
plt.xlabel('Frame relative time (seconds')
plt.ylabel('Pressure(ml/sec)')

plt.show()
```

**Actual Code**
```
figure(32)
subplot(211)
plot(xrange_plot, self.var7[yrange_plot:self.Pt], color=self.x[self.col_fac - 1, :])
plt.title('Right Ventricle volume  ')
plt.xlabel('Frame relative time (seconds')
plt.ylabel('volume(ml)')
subplot(212)
plot(xrange_plot, self.var19[yrange_plot:self.Pt], color=self.x[self.col_fac - 1, :])
plt.title('Right Ventricle fow')
plt.xlabel('Frame relative time (seconds')
plt.ylabel('Pressure(ml/sec)')
```
**Actual outcome**

![Figure_32](https://user-images.githubusercontent.com/40902441/62488234-c7b24200-b791-11e9-8d4c-1b7e9c70c043.png)

```
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
Try [constrained layout](https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py), [tight layout](https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py), or [`subplots_adjust`](https://matplotlib.org/gallery/subplots_axes_and_figures/subplots_adjust.html#sphx-glr-gallery-subplots-axes-and-figures-subplots-adjust-py).

**Comment by dstansby** [comment]
Yep, I think the solutions provided by @QuLogic should work, so I'm going to close this; feel free to comment if you still have a question/issue.

**Comment by JiaxiangBU** [comment]
> Try [constrained layout](https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py), [tight layout](https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py), or [`subplots_adjust`](https://matplotlib.org/gallery/subplots_axes_and_figures/subplots_adjust.html#sphx-glr-gallery-subplots-axes-and-figures-subplots-adjust-py).

I try it but the sub plot is overlapping still. Here is a partial solution https://github.com/slundberg/shap/issues/153#issuecomment-974783127 .

**Comment by jklymak** [comment]
> > Try [constrained layout](https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py), [tight layout](https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py), or [`subplots_adjust`](https://matplotlib.org/gallery/subplots_axes_and_figures/subplots_adjust.html#sphx-glr-gallery-subplots-axes-and-figures-subplots-adjust-py).
> 
> 
> 
> I try it but the sub plot is overlapping still. Here is a partial solution https://github.com/slundberg/shap/issues/153#issuecomment-974783127 .

Please open a new issue if none of those worked for you with a self contained example.
