### ISSUE TITLE
Barplot call crashes when called with yscale="log" and bins with h=0

### ISSUE THREAD

**Issue by kopytjuk** [matplotlib/matplotlib#14981]
Contrary to that, when called with `yscale="linear"` and bins with height=0 works everything as expected.

https://github.com/matplotlib/matplotlib/blob/f2116d82dfd6b82fe178230766d95ea9ac2b0c8c/lib/matplotlib/axes/_axes.py#L2442

**Comment by anntzer** [comment]
A minimal repro is `yscale("log"); bar([0], [0])` which gives
```
ValueError: min() arg is an empty sequence
```
https://github.com/matplotlib/matplotlib/pull/14581 fixes this.
