### ISSUE TITLE
Styles may be broken?

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#15004]
### Bug report

**Bug summary**

Between 3.1.0 and 3.1.1 the style sheet gallery broke. It now shows all styled figures with grey background.

* **3.1.0**: https://matplotlib.org/3.1.0/gallery/style_sheets/style_sheets_reference.html
* **3.1.1**: https://matplotlib.org/3.1.1/gallery/style_sheets/style_sheets_reference.html

Since the only recent changes to the example itself seem pretty unrelated, this might be an indication that something more serious broke in between.

![image](https://user-images.githubusercontent.com/23121882/62658590-693fbc00-b969-11e9-8e91-68519857152d.png)

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/compare/v3.1.0...v3.1.1 is the diff between those two versions, nothing jump out at me.

Running that example locally (`python style_sheets_reference.py`) works correctly, but building the docs locally fails in the same way (gray on the 2nd one on).

**Comment by tacaswell** [comment]
If I install v3.1.0 locally and then build the `v3.1.1-doc` branch it is still all gray and if I build v3.1.0  with `v3.1.0-doc` I also get the gray background which makes me think that sphinx gallery moved under us....

**Comment by ImportanceOfBeingErnest** [comment]
I built the docs with current matplotlib master, sphinx 1.8.5, sphinx_gallery 0.3.1 and the output is correct (all styles applies as they should). This is somehow good news, as there doesn't seem to be a bigger problem in matplotlib. 

It seems sphinx_gallery is now at 0.5.0 already. Is it possible for you to recover which sphinx_gallery versions you used for the builts respectively?

**Comment by ImportanceOfBeingErnest** [comment]
Found it. This is a bug in sphinx_gallery, which was fortunately fixed already 2 days ago in https://github.com/sphinx-gallery/sphinx-gallery/pull/527 
So we need to wait for the next version to appear.

**Comment by tacaswell** [comment]
Great!  Good catch on this and thank you for running it to ground @ImportanceOfBeingErnest .

I am going to leave this open for now and close it when I re-build the 3.1.1 docs and re-push to the docs (hopefully tonight :crossed_fingers: ).

**Comment by tacaswell** [comment]
I just pushed the updated docs, should be live in the next 10-15 minutes.
