### ISSUE TITLE
matplotlib.pyplot.xcorr performs unexpectedly (outputs values larger than 1) when passed boolean arrays in certain contexts

### ISSUE THREAD

**Issue by MarvinT** [matplotlib/matplotlib#15021]
### Bug report
matplotlib.pyplot.xcorr performs unexpectedly (outputs values larger than 1) when passed boolean arrays in certain contexts... I tried to recreate a minimal example generating random data but was unable to create it, however, here is a full example using a kaggle dataset in colab notebook.
**Bug summary**

https://colab.research.google.com/drive/1dVXkXuxMAuzGPDWtHi2AAZ_ygPTbZEpY

**Actual outcome**

![image](https://user-images.githubusercontent.com/1386198/62817413-2bc36600-bb04-11e9-87b3-468204b158d7.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/1386198/62817423-4c8bbb80-bb04-11e9-881a-e0fa4c3caed4.png)

**Matplotlib version**

  * Operating system: Colab Notebook
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3
  * Jupyter version (if applicable):
  * Other libraries: 

See colab notebook

**Comment by jklymak** [comment]
Cast your boolean array to float?  There have been changes in how numpy handles boolean arrays that may be causing grief.  Pretty hard to tell more w/o that minimal self-contained example.  :wink:

**Comment by MarvinT** [comment]
Yep, that's how I made the second plot. The colab notebook is a pretty small self contained example and allows anytime to replicate it in the exact same environment.

**Comment by ImportanceOfBeingErnest** [comment]
Quoting a recent [comment](https://github.com/matplotlib/matplotlib/issues/14992#issuecomment-519147356)
> [..] in general, you will get much better responses from projects if you provide an easily understandable and testable example (see http://www.sscce.org/ for a longer discussion as to why). The information we ask for in the issue template to guide you so we can help you as easily as possible.

In particular, if possible, the example should be *inside the issue*, only use numpy and matplotlib and not require to log into kaggle or similar services.

**Comment by jklymak** [comment]
OK, but if its a cast-to-float issue I don't think we are going to change anything to stay current with numpy's conventions.  I guess you could argue we should catch the "bad" input, but we can't check everything.  Agreed that it probably used to work when booleans were automatically cast to 1/0.  

I'm going to close as "won't fix", but if you strongly feel there is something un-obtrusive we should do about it we can re-open  I will also say that `xcorr` is probably something that we will not encourage compared to just calling numpy's `xcorr`.

**Comment by tacaswell** [comment]
The underlying problem is that the normalization https://github.com/matplotlib/matplotlib/blob/05c9fb52e0e5224694f38f311fce7b25b0a5e79d/lib/matplotlib/axes/_axes.py#L2018-L2019 results in dividing by 1 when the input arrays are bools.

The "play" button in co-lab does not work, the example appears to require a kaggle account / key, depends on large number of un-related packages (geopy, pandas, statsmodel), and is several screens long.

Trying 

```python
In [16]: plt.xcorr(np.array([True, False] * 30), np.array([True, False, True] * 20))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-21d5ec450f94> in <module>
----> 1 plt.xcorr(np.array([True, False] * 30), np.array([True, False, True] * 20))

~/.virtualenvs/bleeding/lib/python3.9/site-packages/matplotlib/pyplot.py in xcorr(x, y, normed, detrend, usevlines, maxlags, data, **kwargs)
   3047         x, y, normed=True, detrend=mlab.detrend_none, usevlines=True,
   3048         maxlags=10, *, data=None, **kwargs):
-> 3049     return gca().xcorr(
   3050         x, y, normed=normed, detrend=detrend, usevlines=usevlines,
   3051         maxlags=maxlags, **({"data": data} if data is not None else

~/.virtualenvs/bleeding/lib/python3.9/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1546     def inner(ax, *args, data=None, **kwargs):
   1547         if data is None:
-> 1548             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1549 
   1550         bound = new_sig.bind(ax, *args, **kwargs)

~/.virtualenvs/bleeding/lib/python3.9/site-packages/matplotlib/axes/_axes.py in xcorr(self, x, y, normed, detrend, usevlines, maxlags, **kwargs)
   2017 
   2018         if normed:
-> 2019             correls /= np.sqrt(np.dot(x, x) * np.dot(y, y))
   2020 
   2021         if maxlags is None:

TypeError: ufunc 'true_divide' output (typecode 'e') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind''

```

fails in numpy which is probably the correct place to fail.

@MarvinT Can you track down what version of numpy this behavior changed in?

**Comment by timhoffm** [comment]
@tacaswell You removed the "Won'T or can't fix" label. Does that mean, this should be reopened?

**Comment by tacaswell** [comment]
I removed the label because I don't think it is a bug on our side and I don't want to label it "upstream fix required" because newer versions of numpy error out on where I think the problematic code is.
