### ISSUE TITLE
Bug in matplotlib.pyplot.grid settings

### ISSUE THREAD

**Issue by jfdo** [matplotlib/matplotlib#15036]
Bug report

**matplotlib grid settings**

<matplotlib.pyplot.grid(axis='both')>

**Code for reproduction**

<plt.grid(b=True, which='both', color='b', axis='x', linestyle='--', linewidth= 2)
   plt.grid(b=True, which='both', color='b', axis='y',linestyle='--', linewidth= 0.5)>

```python
plt.grid(b=True, which='both', color='b', axis='x', linestyle='--', linewidth= 2)
plt.grid(b=True, which='both', color='b', axis='y',linestyle='--', linewidth= 0.5)
#
#
```

**Actual outcome**

<There is a bug in the matplotlib grid setting. When selected the the "axis = x" settings the changes are on the "y" axis. And when selected the "axis = y", the changes happen on the "x" axis>

**Matplotlib version**
< matplotlib.__version__ = '2.0.0'>
  * Operating system: Windows Professional 64 bit
  * Matplotlib backend (`print(matplotlib.get_backend()) =  Qt5Agg`):
  * Python version: Python 3.6.0
  *Spyder version : 3.1.2

<!--Please tell us how you installed matplotlib and python e.g., Through Anaconda>

**Comment by jklymak** [comment]
Pretty sure that was fixed.  Is it possible to upgrade to a more recent version?

**Comment by jfdo** [comment]
By the way I found there was incompatibility between the older matplotlib and new version. Some of my scripts that worked with the older version of matplotlib didn't work with the new version. As such I had to uninstall the whole anaconda  and then installed the older version with Python 3.6.0 and spyder older version of matplotlib. So it looks like if I install the new version of matplotlib I will have to change all of my older scripts. Is there any solution for this?
Thanks

**Comment by timhoffm** [comment]
This works correctly with Matplotlib 2.1.0:

![image](https://user-images.githubusercontent.com/2836374/66153337-9fbd4e80-e61b-11e9-86ff-5f37093dcf27.png)

Re: Version incompatibility. We are sometimes introducing backwards-incompatible changes, mostly to fix awkward behavior and to make the API more concise. In general we're quite defensive and only do so if there is a real benefit. Additionally, there is a two-version deprecation period that notifies users of future changes. But in the long run, you won't be able to avoid some changes if you want to keep up with the latest versions.
