### ISSUE TITLE
plt.style.use() doesn't work on the first pass

### ISSUE THREAD

**Issue by andrzejnovak** [matplotlib/matplotlib#15056]
Using style to update rcParams has a strange bug, running the code as shown below the changed parameter isn't updated. Strangely enough after executing all cells again it works as expected.
![image](https://user-images.githubusercontent.com/13226500/62982958-6aeb0300-bdf3-11e9-82d5-91da944f6811.png)

**Matplotlib version**

  * Operating system: WSL
  * Matplotlib version: master
  * Matplotlib backend (`module://ipykernel.pylab.backend_inline`):
  * Python version: 3.7
  * Jupyter version (if applicable): 1.0.0
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
It's more that it's not working in the first cell, or the cell where `pyplot` is first imported. 

This is a known thing, reported e.g. in https://github.com/matplotlib/matplotlib/issues/9217 already, but ultimately it's an IPython/ipykernel problem, tracked in https://github.com/ipython/ipykernel/issues/267
