### ISSUE TITLE
Feature request: stem3

### ISSUE THREAD

**Issue by fkromer** [matplotlib/matplotlib#15066]
Would be great to have an equivalent to [Matlab's stem3](https://de.mathworks.com/help/matlab/ref/stem3.html) in `matplotlib`. [A temporary workaround is e.g. to use Line3D](https://stackoverflow.com/questions/8453726/is-there-a-matplotlib-counterpart-of-matlab-stem3).

**Comment by harshanavkis** [comment]
Is anybody working on this? I would like to take this up. A few questions:
1) Would the api need to be same as the matlab api?
2) Where should I begin?

**Comment by WeatherGod** [comment]
Nope, go ahead and try to implement it. No, the api should match our stem()
API, just with a `z` and `zdir` argument, most likely. You'll see what I
mean when you look at implementations for `plot()` and `scatter()` in
`lib/mpl_toolkits/mplot3d/axes3d.py`.

**Comment by smolgeat** [comment]
Is anyone still working on this?

**Comment by anntzer** [comment]
Not as far as I can see.

**Comment by fkromer** [comment]
No. I'm using "sufficient enough" workaround for visualization `stem3` like right now.

**Comment by tcho0501** [comment]
@jackcwu and I are working on this

**Comment by timhoffm** [comment]
@tcho0501 thanks for your interest, but there is already #18310.

**Comment by adeak** [comment]
https://github.com/matplotlib/matplotlib/pull/18310 was merged 2 weeks ago., Can be closed now?

**Comment by timhoffm** [comment]
Yes, thanks for the notification.
