### ISSUE TITLE
RuntimeWarning: Glyph 8722 missing from current font.   font.set_text(s, 0.0, flags=flags)

### ISSUE THREAD

**Issue by chaotianjiao** [matplotlib/matplotlib#15062]
Hello ,It's very nice to use it ! Someday when I run my code I got a Warning:
RuntimeWarning: Glyph XXX missing from current font.
font.set_text(s, 0.0, flags=flags)
XXX is some numbers, such as 8722 、25329  etc.
Although it doesn't influence the result, I really want to slove this warning. What can I do?
Thanks and best wishes!

**Comment by timhoffm** [comment]
What exactly is the text `s` in your case?

**Comment by chaotianjiao** [comment]
@timhoffm sorry for late response，  **s** is chinese, like ' 三月', and I have add this code in my project:
plt.rcParams['font.family'] = ['sans-serif']
plt.rcParams['font.sans-serif'] = ['SimHei']
Maybe the code's problem?

**Comment by chaotianjiao** [comment]
@tacaswell Thanks, It helps a lot!

**Comment by bkdwei** [comment]
use 'WenQuanYi Micro Hei' can show chinese correctly.

**Comment by jxustlsp** [comment]
> 您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
> RuntimeWarning：当前字体缺少字形XXX。
> font.set_text（s，0.0，flags = flags）
> XXX是一些数字，例如8722，25329等。
> 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
> 谢谢，祝你好运！

楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？

**Comment by zhaofeng-shu33** [comment]
I encounter the same issue using matplotlib 3.1.2, python 3.7.3 on macos 10.14.
How to choose the correct font names?
Following the official instruction does not help.
I try `STSong` etc. but it does not work.

**Comment by zhaofeng-shu33** [comment]
`Songti SC` works.

**Comment by MurikiSaiSrinivas** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/58871008/70849863-1f805880-1eaa-11ea-8afa-1257f9f47f17.png)
I get this thing when I tried to use this code
![Screenshot (31)](https://user-images.githubusercontent.com/58871008/70849873-4048ae00-1eaa-11ea-8068-8a934c23582d.png)

**Comment by MurikiSaiSrinivas** [comment]
please help me

**Comment by bkdwei** [comment]
在linux系统的终端使用以下命令，查找可用的中文字体，在绘图时用任意一种已安装的字体即可。mac应该也有这个命令吧。
fc-list :lang=zh family.

**Comment by taiyisanxian** [comment]
> > 您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
> > RuntimeWarning：当前字体缺少字形XXX。
> > font.set_text（s，0.0，flags = flags）
> > XXX是一些数字，例如8722，25329等。
> > 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
> > 谢谢，祝你好运！
> 
> 楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？

我试了下绘图前设置：plt.rcParams["font.family"]="STSong" ，显示中文正常了

**Comment by tacaswell** [comment]
@MurikiSaiSrinivas Make sure the values you are using for you x are datetimes or floats, not strings.  We treat strings as catagorical data.  Can you please move this discussion to https://discourse.matplotlib.org/ ?

**Comment by radial-hks** [comment]
在使用的holoviews+matplotlib 作为显示扩展时，出现同样的问题, 使用 fc-list :lang=zh family查找对应的字体，使用 plt.rcParams['font.family'] = ['宋体\-繁,宋體\-繁,Songti TC']进行修改，依然无法解决 该问题，本机环境为mac,请问有什么解决方案吗

**Comment by tacaswell** [comment]
@radial-hks You may have to regenerate the font cache.

Do

```
import matplotlib
print(matplotlib.get_cachedir())
```

and remove any `fontlist-*.json` files in that directory and try again.

Can you produce the problem without holoviews?

**Comment by marchboy** [comment]
> > 您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
> > RuntimeWarning：当前字体缺少字形XXX。
> > font.set_text（s，0.0，flags = flags）
> > XXX是一些数字，例如8722，25329等。
> > 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
> > 谢谢，祝你好运！
> 
> 楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？

import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
#有中文出现的情况，需要u'内容'

Reference: https://segmentfault.com/a/1190000005144275

**Comment by radial-hks** [comment]
非常感谢 这个问题已经得到了良好的解决，再次感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "marchboy"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 下午4:22
收件人: "matplotlib/matplotlib"<matplotlib@noreply.github.com&gt;; 
抄送: "radial"<1720069673@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [matplotlib/matplotlib] RuntimeWarning: Glyph 8722 missing from current font.   font.set_text(s, 0.0, flags=flags) (#15062)





   
您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
 RuntimeWarning：当前字体缺少字形XXX。
 font.set_text（s，0.0，flags = flags）
 XXX是一些数字，例如8722，25329等。
 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
 谢谢，祝你好运！
  
楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？
  
import matplotlib.pyplot as plt
 plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
 plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
 #有中文出现的情况，需要u'内容'
 
Reference: https://segmentfault.com/a/1190000005144275

**Comment by radial-hks** [comment]
1、查看系统安装字体
`fc-list :lang=zh`
2、 替换代码中的字体
[](https://imgkr.cn-bj.ufileos.com/3291e73b-7795-4976-9b84-7a1c73fde67f.png)

**Comment by KimUzoo** [comment]
font_location = "NanumBarunGothic.otf"
    font_name = font_manager.FontProperties(fname=font_location).get_name()
    matplotlib.rc('font', family=font_name)


I wrote this code and I keep getting this error. I think I've tried all the methods on Google. What should i do

**Comment by zhaofeng-shu33** [comment]
@chaotianjiao Can you reopen this issue?

**Comment by KimUzoo** [comment]
set(sorted((f name of f in mpl.font_manager.fontManager.ttflist)))

I found a list of possible fonts with this code. Among them, Malgun Gothic was printed. I tried another font, but it didn't work. I am not sure why. Thank.

**Comment by meocean** [comment]
> > > 您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
> > > RuntimeWarning：当前字体缺少字形XXX。
> > > font.set_text（s，0.0，flags = flags）
> > > XXX是一些数字，例如8722，25329等。
> > > 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
> > > 谢谢，祝你好运！
> > 
> > 
> > 楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？
> 
> import matplotlib.pyplot as plt
> plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
> plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
> #有中文出现的情况，需要u'内容'
> 
> Reference: https://segmentfault.com/a/1190000005144275

Solve the problem perfectly，thanks!

**Comment by rehman-453** [comment]
same issue when i use urdu font.

**Comment by chengjon** [comment]
> > > > 您好，使用它非常好！有一天，当我运行我的代码时，我得到了一个警告：
> > > > RuntimeWarning：当前字体缺少字形XXX。
> > > > font.set_text（s，0.0，flags = flags）
> > > > XXX是一些数字，例如8722，25329等。
> > > > 尽管它不影响结果，但我真的很想取消此警告。我能做什么？
> > > > 谢谢，祝你好运！
> > > 
> > > 
> > > 楼主解决了吗？我也碰到了一样的问题。能说一下解决办法吗？
> > 
> > 
> > import matplotlib.pyplot as plt
> > plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
> > plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
> > #有中文出现的情况，需要u'内容'
> > Reference: https://segmentfault.com/a/1190000005144275
> 
> Solve the problem perfectly，thanks!

from matplotlib import pyplot as plt 
plt.rcParams['font.sans-serif'] = ['KaiTi']
plt.rcParams['font.serif'] = ['KaiTi']
plt.rcParams['axes.unicode_minus'] = False
加入这几句，解决一切问题
