### ISSUE TITLE
check_figures_equal decorator reuses figures if called multiple times inside a single test.

### ISSUE THREAD

**Issue by andrewzwicky** [matplotlib/matplotlib#15079]
### Bug report

**Bug summary**

When running a test suite with multiple tests using check_figures_equal, figures are re-used, causing plot elements to become "stacked", causing tests to unexpectedly fail.

**Code for reproduction**

```python
from matplotlib.testing.decorators import check_figures_equal
from matplotlib import pyplot as plt

@check_figures_equal(extensions=["png"])
def test_red_line_first(test_figure, reference_figure):
    red_circle = plt.Circle((0, 0), 0.2, color='r', clip_on=False)
    reference_figure.add_artist(red_circle)
    reference_figure.subplots().plot([0,1,2], [3,4,5], color='red')    


@check_figures_equal(extensions=["png"])
def test_blue_line_second(test_figure, reference_figure):
    blue_circle = plt.Circle((1, 1), 0.2, color='b', clip_on=False)
    reference_figure.add_artist(blue_circle)
    reference_figure.subplots().plot([0,1,2], [4,4,4], color='blue')


@check_figures_equal(extensions=["png"])
def test_green_line_third(test_figure, reference_figure):
    green_circle = plt.Circle((1, 0), 0.2, color='g', clip_on=False)
    reference_figure.add_artist(green_circle)
    reference_figure.subplots().plot([0,1,2], [5,4,3], color='green')
```

running as:
`pytest .\mpl_figure_equal_test.py`

**Actual outcome**
Reference Screenshots:
![test_red_line_first-expected](https://user-images.githubusercontent.com/5263073/63228487-3e4f3680-c1b9-11e9-8452-e8b6a84f6b9f.png)
![test_blue_line_second-expected](https://user-images.githubusercontent.com/5263073/63228488-4018fa00-c1b9-11e9-8ac0-1b27d2f3baa2.png)
![test_green_line_third-expected](https://user-images.githubusercontent.com/5263073/63228490-414a2700-c1b9-11e9-8181-f40ed360201b.png)

**Expected outcome**
Reference Screenshots:
![test_red_line_first-expected](https://user-images.githubusercontent.com/5263073/63228494-6048b900-c1b9-11e9-95a5-f1d3e2e362b5.png)
![test_blue_line_second-expected](https://user-images.githubusercontent.com/5263073/63228495-68a0f400-c1b9-11e9-8a23-0953f2184c27.png)
![test_green_line_third-expected](https://user-images.githubusercontent.com/5263073/63228496-69d22100-c1b9-11e9-82fa-cb8768b0bf2c.png)

**Matplotlib version**

  * Operating system: `Windows 10`
  * Matplotlib version: `matplotlib            3.1.0`
  * Matplotlib backend (`print(matplotlib.get_backend())`): `TkAgg`
  * Python version: `3.7.3`
  * Jupyter version (if applicable):
  * Other libraries:  `pytest                4.5.0`

everything installed via pip

https://github.com/matplotlib/matplotlib/blob/e86c9cd7105e107589220286d55cd9ffc3bfeb64/lib/matplotlib/testing/decorators.py#L394-L395

I'm guessing these lines are at fault, and might need some kind of other information to distinguish them?

**Comment by anntzer** [comment]
Probably one should just wrap the whole thing in a `try... finally: plt.close("all")`?  In our own test suite this is done by an autouse fixture but I guess adding the close() to check_figures_equal makes it more usable by third-party packages.

**Comment by QuLogic** [comment]
All our tests autouse a fixture from `matplotlib.testing.conftest` that closes all figure at the end of a test. If you're not running these as Matplotlib tests, you'll need to replicate that behaviour.

**Comment by andrewzwicky** [comment]
Both of those make sense.  Is `check_figures_equal` intended for use in third-party projects?  It seems quite useful, so it might make sense to either update the documentation re: extra testing steps for closing figures or include that functionality to close just those two figures.  Do maintainers have a preference?  It seems like a relatively small thing I can contribute.

I just tested a small fix with `try`/`finally` and it worked as intended.  I think having to add extra figure closing stuff in my own test suite would make me scratch my head a bit, so I'd prefer the `plt.close` included in the wrapper, but I understand if that's not desirable for some other reason.

**Comment by anntzer** [comment]
I'm personally fine with a pr adding the call to close.
