### ISSUE TITLE
python setup.py build (in parallel)

### ISSUE THREAD

**Issue by ivanov** [matplotlib/matplotlib#1507]
One bottleneck for development is a lack of ability for parallel compilation - which is something that's true for all extension code (I think this is due to a limitation in distutils / setuptools / etc). I know I'm not alone in having tried to do this before, but I just came across this [SO post suggesting a way to monkeypatch distutils into submission for this purpose](http://stackoverflow.com/questions/11013851/speeding-up-build-process-with-distutils), so perhaps someone's feeling optimistic and wants to give this another stab?

**Comment by pelson** [comment]
Just to follow up with this *ancient* thread, the following works a treat for me on a mac:

```
 CC="ccache gcc" CXX="ccache" pip install -e .
```
