### ISSUE TITLE
tight_layout crops long titles

### ISSUE THREAD

**Issue by oliversheridanmethven** [matplotlib/matplotlib#15084]
# A title with a big LaTeX item

I have a plot where in the title I have a big equation produced using LaTeX, and hence have split this over two lines. However, when I go to save this using `plt.savefig(..., bbox_inches='tight')` some of this gets cropped off in the output (pdf). However, this does not seem to be the case when I use `plt.gcf().tight_layout()` prior to saving.

>I am in the habit of using `bbox_inches` and was not expecting this behaviour. 

## The title I expect

![image](https://user-images.githubusercontent.com/13259221/63286588-48a02c00-c2b0-11e9-8a88-792601f4574e.png)

### Using `tight_layout` only. 

If I use 

```
plt.gcf().tight_layout()
plt.savefig('figures/mwe.pdf', format='pdf', transparent=True)
```

I get (ignore the line from the screen grab)

![image](https://user-images.githubusercontent.com/13259221/63286716-8ef58b00-c2b0-11e9-85d4-10dfd751b203.png)

### Using `bbox_inches='tight'`

However, if I use

```
plt.savefig('figures/mwe.pdf', format='pdf', bbox_inches='tight', transparent=True)
```

I get that the top is cropped off (undesired)

![image](https://user-images.githubusercontent.com/13259221/63286898-f9a6c680-c2b0-11e9-8fc9-0f1bc647de7e.png)

# The code

In my example the first line is cropped off entirely, and I have played about with the fonts a bit to try and highlight the issue. 

```
import matplotlib as mpl
mpl.rcParams.update({"font.size": 30})
import matplotlib.pylab as plt

plt.clf()
plt.title('Limiting behaviour of \n' + r'$x(1-y)^{2m+1}\left(\frac{1 - y^{(p+1)(K-1)}}{1 - y^{p+1}}\right)$', y=1.1)
plt.savefig('mwe.pdf', format='pdf', bbox_inches='tight', transparent=True)
plt.gcf().tight_layout()
plt.savefig('mwe2.pdf', format='pdf', transparent=True)

```
The code uses MPL version 2.2.3 and python version 2.7.12.

(I've gone through the suggested "related problems" but can't seem to find anything to resolve this or explain why one solution is working and the other isn't).

**Comment by QuLogic** [comment]
Do you need all this extra preamble to reproduce?

**Comment by oliversheridanmethven** [comment]
> Do you need all this extra preamble to reproduce?

I've reduced it down (I had thought it was due partially to some bits being rendered with LaTeX, but I have replicated the issue with only increasing the fontsize). The original query has been modified accordingly. However, _**this now appears to be cropping out some of the horizontal margin**_:

# Using `tight_layout`
![image](https://user-images.githubusercontent.com/13259221/63295595-f584a400-c2c4-11e9-8945-63c1a569acc7.png)

# Using `bbox_inches`
However, using `bbox_inches` doesn't seem to show this issue:

![image](https://user-images.githubusercontent.com/13259221/63295671-2c5aba00-c2c5-11e9-9815-9f0840d94081.png)

**Comment by jklymak** [comment]
Can you test in 3.x? Some of this has been fixed though not necessarily this exact problem.

**Comment by anntzer** [comment]
bbox_inches="tight" seems fixed as of master; tight_layout seems still wrong.

**Comment by oliversheridanmethven** [comment]
> bbox_inches="tight" seems fixed as of master; tight_layout seems still wrong.

I have just tested this using Python 3.7.4 and MPL 3.1.1+1906.g5e3bede, and `bbox_inches` works fine, whereas `tight_layout` is cropping stuff off the side. It seems now to highlight a bug in `tight_layout`.

**Comment by anntzer** [comment]
Let's keep this open for the tight_layout bug.

**Comment by jklymak** [comment]
BTW, this really doesn't have anything to do w/ mathtext..

```python
fig, ax = plt.subplots(constrained_layout=False)
ax.set_title('Limiting behaviour of \n' + 'Booooger Booooger Booo')
#fig.canvas.draw()
#fig.tight_layout()
plt.show(block=False)

fig, ax = plt.subplots(constrained_layout=False)
ax.set_title('Limiting behaviour of \n' + 'Booooger Booooger Booo')
#fig.canvas.draw()
fig.tight_layout()
plt.show(block=False)

fig, ax = plt.subplots(constrained_layout=False)
ax.set_title('Limiting behaviour of \n' + 'Booooger Booooger Booo')
#fig.canvas.draw()
fig.tight_layout()
fig.tight_layout()
plt.show(block=True)
```

**Comment by tacaswell** [comment]
I can not reproduce this any more, except in the cases where the font is very large and wider than figure.  `tight_layout` (or `constrained_layout`) can only resize and adjust the location of the Axes in the Figure.  If there is a title that is bigger than the `Figure` then they are stuck and the title will be clipped.  On the other hand `fig.savefig(..., bbox_inches='tight')` effectively resizes the output so is able to not appear clipped.

I am going to close this as part fixed and part unfixable.
