### ISSUE TITLE
Inconsistent kwarg naming between step() and fill_between()

### ISSUE THREAD

**Issue by andrzejnovak** [matplotlib/matplotlib#15085]
Calling step style is using a different kwarg name in `step()` and `fill_between() i.e.
```
ax.step(x, y, where='post')
```
and
```
ax.fill_between(x, y, step='post')
```

Maybe use `step` in both or pick a better kwarg name usable in both and not conflicting with `where` in fill_between which turns bin filling on/off

**Comment by timhoffm** [comment]
This should also be consistent with
~~~
ax.plot(x, y, drawstyle='step-post')
~~~

Maybe we should just
~~~
ax.fill_between(x, y, drawstyle='step-post')
~~~

`ax.step` is just a thin wrapper around `plot`, setting the drawstyle. It must have a straight-forward parameter name. I'd leave `where`.

**Comment by timhoffm** [comment]
Let‘s not go through the hassle of an API change. `step()` is a bit awkward anyway and we nowadays have `stairs()`, which is preferable in many cases.
