### ISSUE TITLE
Coerce MxNx1 images into MxN images for imshow

### ISSUE THREAD

**Issue by kmader** [matplotlib/matplotlib#15089]
Not a bug report and possibly a repeat or bad idea, but using pytorch, keras, theano, tensorflow you often end up with images with shape (x, y, 1). It would be nice, if matplotlib imshow would just assume images of that size are grayscale rather than showing an error message.

```
import matplotlib.pyplot as plt
import numpy as np
gray_image = np.ones((3, 3, 1))
plt.imshow(gray_image)
```

# Result

```
TypeError: Invalid shape (3, 3, 1) for image data
```
https://github.com/matplotlib/matplotlib/blob/0290a7e2382598cf3c54150abcf4e55a0b455941/lib/matplotlib/image.py#L674-L677

# Expected Result

The same as if I did
```
plt.imshow(gray_image[:, :, 0])
````

**Comment by jklymak** [comment]
Imshow already takes mxn matrix and maps the values into a colormap.  If you want that colormap to be grey you can easily do that with the cmap kwarg and can scale with vmin and vmax.  I think it’s pretty confusing to say that a mxnx1 array behaves differently.

**Comment by kmader** [comment]
@jklymak thanks for responding. I think I didn't make it clear. My suggestion would be to have the mxnx1 input interpreted the same way as mxn rather than throwing an error message.

**Comment by jklymak** [comment]
OK, but that's not the same as assuming it is grayscale

**Comment by tillahoffmann** [comment]
@kmader, we have ended up using `plt.imshow(np.squeeze(x))`, where `x` is the output from the network. My hunch is that adding a silent "squeeze" to the interface of `imshow` could cause confusion in other settings.

**Comment by kmader** [comment]
@tillahoffmann it would only be a silent squeeze if the 3rd dimension were 1 so it shouldn't change any other behavior, or was there something else you were thinking of?
it just works for MxNx1 images instead of throwing an error. The idea would also be useful for students/beginners who are often confused by such messages and why keras images cannot be shown as they are.

**Comment by EricBuist** [comment]
I agree. I ran into this recently and I'm just stuck, cannot render images in grayscale. Probably another function, imshow_grayscale? But would be too specific I imagine. All of this "squeeze" stuff is really confusing and I cannot find ways around this. Documentation is not clear and just enumerating bunches of special cases.

**Comment by jklymak** [comment]
This was closed because we now squeeze mxnx1 images.  If you are still having this issue you have an old matplotlib or you should please open a new issue
