### ISSUE TITLE
DOC: colLoc missed typed as rowLoc in matplotlib.axes.Axes.table 

### ISSUE THREAD

**Issue by StevenLi-DS** [matplotlib/matplotlib#15097]
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.table.html

![image](https://user-images.githubusercontent.com/33796896/63468240-5d59fc80-c435-11e9-8d92-192d71b2c45b.png)

**Comment by timhoffm** [comment]
Thanks for the report. This has already been fixed on the master branch:

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.table.html
