### ISSUE TITLE
How to  plot on a image specific position, with grid ?

### ISSUE THREAD

**Issue by selvakarna** [matplotlib/matplotlib#15094]
How to  plot on a image specific position, with grid ? from below attachment ?

plot inside rectangular red box ? with x y scaling ?

![sk](https://user-images.githubusercontent.com/25522855/63424236-9beab980-c42b-11e9-933c-a0cad4df6717.jpg)

**Comment by ImportanceOfBeingErnest** [comment]
There is a good chance to get help with your matplotlib plotting problems if you use one of the options listed in https://matplotlib.org/#need-help and in addition make sure to explain your problem clearly, using whole sentences.

**Comment by selvakarna** [comment]
Hi ImportanceOfBeingErnest, 

            How to plot inside rectangle box with scaling?

**Comment by selvakarna** [comment]
Hi @ImportanceOfBeingErnest ,

     Check this attachment , i want to plot like this ?
![sk (copy)](https://user-images.githubusercontent.com/25522855/63428947-69928980-c436-11e9-8cf1-3bc384e0cfab.jpg)

**Comment by jklymak** [comment]
@selvakarna thanks for your interest in Matploltlib!  However, this is an issue tracker and not a user help forum, which is better served in the forums @ImportanceOfBeingErnest  links to above.  Even on stackoverflow you will likely need to show that you've tried *something* before folks will be interested to pitch in and help.    I'm going to close, but if there is something lacking in our documentation, please feel free to let us know.
