### ISSUE TITLE
matplotlib.collections inheritance diagram small/blurry

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#15109]
See https://matplotlib.org/devdocs/api/collections_api.html - the inheritance diagram at the top of the page renders small and blurry for me:

<img width="957" alt="Screenshot 2019-08-23 at 13 23 07" src="https://user-images.githubusercontent.com/6197628/63592322-3cb2b380-c5a9-11e9-8161-1ad2e54c614f.png">

Not sure what the correct fix is, but maybe there are configuration options for drawing these inheritance diagrams, or maybe some CSS changes could improve things.

**Comment by dstansby** [comment]
I think the thing to do is change the configuration somehow, as documented here: https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html#confval-inheritance_graph_attrs

**Comment by joybhallaa** [comment]
Can I take this issue?

**Comment by dstansby** [comment]
Yes, please do!
