### ISSUE TITLE
Updating 3d scatterplot data.

### ISSUE THREAD

**Issue by scottcanoe** [matplotlib/matplotlib#15118]
When animating a 3d scatter plot, I ran into a problem. One should be able to update z-data using Path3DCollection.set_3d_properties, but I got "builtins.ValueError: too many values to unpack (expected 2)". Turns out this was caused by 

```python
if len(offsets) > 0:
    xs, ys = offsets.T 
```
in mplot3d/art3d.py, line 453. I got everything working by removing the transpose operation.

**Comment by ImportanceOfBeingErnest** [comment]
Would you mind showing a minimal verifiable example of the issue? Else, it's really hard to guess what could be wrong.

**Comment by WeatherGod** [comment]
If stuff started working by removing the transpose operation, then chances
are, the data you are supplying is in the wrong shape. But I can't be sure
unless I see your code.

**Comment by timhoffm** [comment]
Closing due to lack of feedback.
