### ISSUE TITLE
Make plt.style.use accept path-like objects in addition to string

### ISSUE THREAD

**Issue by ivarstange** [matplotlib/matplotlib#15138]
`plt.style.use(style)` accepts a `str`, `dict`, or `list`. The `str `can be either the name of a style or a path/URL to a style file. I propose that this also accept a pathlike object (`pathlib.Path`) so that it is unneccesary to cast it like `plt.style.use(str(my_path))`, but accept it like this `plt.style.use(my_path)`.

There may be other places in the code that accepts file paths as strings.

**Comment by omsitapara23** [comment]
Hi @QuLogic,

If no one is working on this problem than I would like to give it a shot. Also can you please guide me from where should I start?

Thank You!
Om.

**Comment by timhoffm** [comment]
You will need to change the code in the function `use()`  at `matplotlib/style/core.py`.

**Comment by omsitapara23** [comment]
Hi @timhoffm,

Thanks for the guidance and I have started working on this enhancement. Can you please tell me where to go if I need any help?

Thank you!
Om.

**Comment by timhoffm** [comment]
You can ask on the [gitter channel](https://gitter.im/matplotlib/matplotlib) or post questions alongside your PR.
