### ISSUE TITLE
TkAgg backend showing empty figure

### ISSUE THREAD

**Issue by paudetseis** [matplotlib/matplotlib#15133]
### Bug report

**Bug summary**

TkAgg backend plots an empty figure with matplotlib=3.1.1 (python=3.7.3) installed within conda environment on MacOS=10.14.6. 

**Code for reproduction**

The following lines return an empty (blank) figure in python shell
```python
import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt

f = plt.figure()
ax = f.add_subplot(1,1,1)
ax.plot(range(10))

f.show()
```

**Actual outcome**

Code runs without complaints or error messages but produces an empty figure with no frame or axes

**Expected outcome**

Simple line plot.

**Matplotlib version**

  * Operating system: MacOS=10.14.6
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: python=3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

I have conda=4.7.11 installed and I created en environment:
```bash
conda create -n test_mpl python=3.7
conda activate test_mpl
```
Then I installed Matplotlib using conda using the default channel:
```bash
conda install matplotlib
```
which was installed correctly:
```python
import matplotlib
print(matplotlib.__version__)
```
```
3.1.1
```

**Comment by ImportanceOfBeingErnest** [comment]
Is there any difference if you use `plt.show()` instead of `f.show()`?  
Is there any difference if you use another backend?
