### ISSUE TITLE
pyplot.annotate() API deprecation

### ISSUE THREAD

**Issue by amaeckelberghe** [matplotlib/matplotlib#15142]
### Bug report

**Bug summary**

I wanted to update my code that annotates a plot by changed the deprecated keyword argument `s` to `text` as described in the documentation of matplotlib v3.1.1. However it fails to recognise `text` as an argument and requests `s` instead.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt


print(matplotlib.__version__)
print(matplotlib.get_backend())
matplotlib.pyplot.plot()
matplotlib.pyplot.annotate('without keyword', xy=(0.5, 0.75))
matplotlib.pyplot.annotate(s='keyword "s"', xy=(0.5, 0.5))
matplotlib.pyplot.annotate(text='keyword "test"', xy=(0.5, 0.25))
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/36659848/63761353-4f86fa00-c8c1-11e9-804c-12bd48d354ab.png)

```
3.1.1
TkAgg
Traceback (most recent call last):
  File "<input>", line 9, in <module>
TypeError: annotate() missing 1 required positional argument: 's'
```

**Expected outcome**

I would expect that the keyword we should use in version 3.1.1 would be 'text' since in the documentation (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.annotate.html) it says:

Parameters: | text : str *The text of the annotation. s is a deprecated synonym for this parameter.*
-- | --

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.4

I installed matplotlib through pip

**Comment by timhoffm** [comment]
This issue is discussed in #15049.

**Comment by ImportanceOfBeingErnest** [comment]
Marking as release critical, because the documentation cannot state a parameter `text`, if that parameter does not exist.

**Comment by timhoffm** [comment]
The way forward (two possible solutions) is https://github.com/matplotlib/matplotlib/pull/15049#issuecomment-521138564.

**Comment by tacaswell** [comment]
Pushed to 3.3 as this issue does not break any existing code, but is an inconsistency that we should fix.

We should push out deprecating the `s` kwarg for at least one extra minor release after we clean this up.

**Comment by timhoffm** [comment]
Fixed via the final removal of the deprecation #16491.

Luckily there was no further feedback on the inconsistency in 3.1, so we don't have to be too afraid that this will still be present in 3.2 and only be resolved in 3.3.

**Comment by SeaDude** [comment]
What is the fix for us end users? Following this tutorial [here](https://towardsdatascience.com/a-beginners-guide-to-create-a-cloropleth-map-in-python-using-geopandas-and-matplotlib-9cc4175ab630)...

I receive the error...
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-165dd014e247> in <module>
      4 
      5 for idx, row in merged.iterrows():
----> 6     plt.annotate(s=row['province'], xy=row['coords'], horizontalalignment='center')

TypeError: annotate() missing 1 required positional argument: 'text'
```
When attempting to run...
```
# Add Labels
merged['coords'] = merged['geometry'].apply(lambda x: x.representative_point().coords[:])
merged['coords'] = [coords[0] for coords in merged['coords']]

for idx, row in merged.iterrows():
    plt.annotate(s=row['province'], xy=row['coords'], horizontalalignment='center')
```
Thank you!

**Comment by ksunden** [comment]
@SeaDude See #15049, which is now merged, and ensures that the proper renaming is propegated (not yet released, but coming)

Alternatively, you can just take out the `s=`, as that is the first positional argument anyway

**Comment by tacaswell** [comment]
What version of Matplotlib are you using?

You can also change `plt.annotate` to `ax.annotate`.  The random switching between the OO and sate machine APIs in that tutorial is very weird.
