### ISSUE TITLE
System crashes upon calling plt.show()

### ISSUE THREAD

**Issue by joriswitstok** [matplotlib/matplotlib#15157]
### Bug report

**Bug summary**

When trying to show a figure under the `TkAgg` backend, my system crashes when calling `plt.show()` (some quick googling led me to a seemingly similar [issue #10833](https://github.com/matplotlib/matplotlib/issues/10883)).

**Code for reproduction**

I use the following script:

```python
import sys
print("Python", sys.version)

import matplotlib
matplotlib.use("TkAgg") # use interactive Agg backend
print("Matplotlib", matplotlib.__version__, "(backend: " + matplotlib.get_backend() + ')')
import matplotlib.pyplot as plt

plt.plot([0], [0])

plt.show()
```

**Actual outcome**

When running this, my system crashes and immediately prompts the log-in screen. When logging back in, all the programs that were running restart, as if the system completely restarted.

**Expected outcome**

When leaving out the line specifying to use the `TkAgg` backend, the code shows the empty plot as expected, as well as the output:

```python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Matplotlib 3.1.0 (backend: MacOSX)
```

Alternatively, leaving out the `plt.show()` command means the code does not cause any trouble, either.

**Matplotlib version**

  * Operating system: Mac OSX 10.14.6
  * Matplotlib version: 3.1.0
  * Matplotlib backend: MacOSX/TkAgg
  * Python version: 3.7.4

I installed the latest version of the conda distribution and run this in the base environment.

**Comment by jklymak** [comment]
Closing as a duplicate.  This is an upstream tkagg issue and matplotlib can’t fix it.

**Comment by ImportanceOfBeingErnest** [comment]
Might be helpful to link to the duplicate target here for future reference?
