### ISSUE TITLE
%Matplotlib notebook not working on Google Colab

### ISSUE THREAD

**Issue by leowu4ever** [matplotlib/matplotlib#15161]
**Summary**
Cant switch backend to notebook to enable interactive mode on Google Colab

```python
%matplotlib notebook
import matplotlib.pyplot as plt
import matplotlib
matplotlib.get_backend()
%matplotlib --list
plt.plot([12,3,4])
```

**Actual outcome**
'nbAgg'

Available matplotlib backends: ['tk', 'gtk', 'gtk3', 'wx', 'qt4', 'qt5', 'qt', 'osx', 'nbagg', 'notebook', 'agg', 'inline', 'ipympl', 'widget']

[<matplotlib.lines.Line2D at 0x7f22f2272b70>]
No actual plot displayed

**Expected outcome**
An interactive plot displayed

**Matplotlib version**

  * Operating system:macOS Catalina 10.15Beta
  * Matplotlib version: '3.0.3'
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version:Python 3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
You will need to reach out to google colab to see if they have a plan to support interactive backends in the future. I would think they might opt for `ipywidgets` instead of `nbagg` in that case.

**Comment by jklymak** [comment]
I’m going to close this as I don’t think there is anything matplotlib can do about whatever google collab does.  If there is, feel free to open a new request!

**Comment by tacaswell** [comment]
The likely reason `nbagg` is not available is that it works by injecting a bunch of js into the frontend from the backend.  For (very good) security reasons, this sort of thing is forbidden in jupyterlab and I would assume is also forbidden in colab.

**Comment by chourasiaankur1** [comment]
if you are using %matplotlib notebook
do use:-
%matplotlib inline

**Comment by mennucc** [comment]
As a matter of fact, it seems to be possble injecting js into colab. 
See https://stackoverflow.com/a/55435199
and for your convenience
https://colab.research.google.com/drive/1tXS-kwZUWgkJqYXKxglg67yGQmenSl8d

**Comment by tacaswell** [comment]
This issue should be taken up via the colab support channels.
