### ISSUE TITLE
More tests `ConciseDateFormatter` needed

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#15182]
> Would we need to draw the conclusion that `ConciseDateFormatter` is not sufficiently tested, or is this code path too non-standard?

_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/15181#issuecomment-527936743_

Indeed the `format` and `zero_format` options should get tests, including checks if they are wrong-sized, etc.  ~Promise to do this ASAP~....  or happy to help a newer contributor through writing these tests.

**Comment by sameshl** [comment]
@jklymak I would love to take this up

**Comment by jklymak** [comment]
That would be great!  Let us know iff you need guidance.

**Comment by abhinuvpitale** [comment]
@sameshl are you on this, or else I could get started on this.

**Comment by sameshl** [comment]
@abhinuvpitale You can get started on this.

**Comment by abhinuvpitale** [comment]
@jklymak I need to add the tests in the `test_dates.py` right?
A little guidance on the test content would be helpful.

**Comment by jklymak** [comment]
That’s right `test_dates.py`.  The content would be checking that the formatter makes the correct format if you change `format` and `zero_format`

**Comment by stevenjlm** [comment]
Since this thread seems kind of dead, I wrote 2 tests and have code for it (it's on a branch on my forked copy of `matplotlib`); however, when I run tests locally, a lot of them fail because `dateutil` throws a deprecation warning. Since this is not `matplotlib`, should I ignore it? Or should I do something?

**Comment by jklymak** [comment]
I guess that depends on why `dateutil` is throwing a deprecation warning?

**Comment by stevenjlm** [comment]
Full trace:
[trace.txt](https://github.com/matplotlib/matplotlib/files/4056776/trace.txt)
The relevant line is,
DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.

**Comment by jklymak** [comment]
Thanks. That’s dateutils issue so fee free to ignore it.  Or report it to them if you can make a non matplotlib mi nimble example.
