### ISSUE TITLE
Improve axis labels in pgf backend

### ISSUE THREAD

**Issue by runburg** [matplotlib/matplotlib#15192]
### Bug report

**Bug summary**
Rotated axis labels do not align well using the pgf backend.

**Code for reproduction**
When setting axis labels: `ax.set_xticklabels(names, rotation=90)` where `names` is a list of strings. I get this result using Matplotlib's builtin TeX engine:

<img width="677" alt="Screen Shot 2019-09-04 at 3 39 50 PM" src="https://user-images.githubusercontent.com/45680856/64305338-d4f65400-cf2a-11e9-8d66-e01ece7e2875.png">

**Actual outcome**
If I switch to the pgf backend, things get wonky: 

<img width="655" alt="Screen Shot 2019-09-04 at 3 39 29 PM" src="https://user-images.githubusercontent.com/45680856/64305369-fa835d80-cf2a-11e9-900e-268cc4561992.png">

I get this result even if I pad all of the axis label strings to be the same length. I tried padding with `' '` and `'~'` but it seems like pgf doesn't process these space characters.

**Expected outcome**
It would be great if the handling of axis labels was smoother with the pgf backend. Ideally, alignment would be right-justified along the axis to be consistent with matplotlib's default formatting.

**Matplotlib version**

  * Operating system: macOS 10.14.6
  * Matplotlib version: 3.1.1
  * Matplotlib backend: pgf
  * Python version: 3.7.4

**Comment by anntzer** [comment]
Please provide a minimal example to repro the issue.  At least with
```
from pylab import *
matplotlib.rcParams["text.usetex"] = True
matplotlib.use("pgf")
xticks(range(5), ["foo", "bar", "quux", "longer"], rotation=90)
savefig("/tmp/test.pdf")
```
the alignment looks fine to me (as of master).

**Comment by runburg** [comment]
The problem comes when saving as a .pgf file. Here is an adapted MWE

```
from pylab import *
matplotlib.rcParams["text.usetex"] = True
matplotlib.use("pgf")
xticks(range(6), ["foo", "longer", "bar","short", "quux", "very long"], rotation=90)
savefig("test.pgf")
```

Using a LaTeX script to compile this document:

```
\documentclass{article}
\usepackage{pgf}

\begin{document}
\begin{figure}
  \input{test.pgf}
\end{figure}
\end{document}
```
I get this. You can see the errant behavior on the axis labels.
<img width="775" alt="Screen Shot 2019-09-05 at 10 02 46 AM" src="https://user-images.githubusercontent.com/45680856/64376649-7aa9d180-cfc4-11e9-85db-b6965d1ce79b.png">

**Comment by anntzer** [comment]
This is because you need to use the same fonts as thosed used by Matplotlib (and documented at the top of test.pgf), as they are actually used for measuring the text size for positioning.  Indeed, adding
```
\usepackage{fontspec}
\setmainfont{DejaVuSerif.ttf}[Path=.../matplotlib/mpl-data/fonts/ttf/]
\setsansfont{DejaVuSans.ttf}[Path=.../matplotlib/mpl-data/fonts/ttf/]
\setmonofont{DejaVuSansMono.ttf}[Path=.../matplotlib/mpl-data/fonts/ttf/]
```
fixes the alignment.

**Comment by runburg** [comment]
Alright so this does work the mwe. 

For my actual use case, I'm trying to import this into a Latex document so I'd like to use Computer Modern Roman. Setting rcparams:
```
mpl.rc('font', **{'family': 'serif', 'serif': ['cmr10']})
mpl.rc('text', usetex=True)
```
is effective for this for anyone that stumbles on this page!

Thanks for the help!
