### ISSUE TITLE
FigureCanvas constructor crashes if interactive mode is switched on

### ISSUE THREAD

**Issue by catastropeia** [matplotlib/matplotlib#15205]
### Bug report

**Bug summary**
Creating a FigureCanvas object crashes, if `plt.ion()` is called beforehand.

**Code for reproduction**

The following MWE crashes - but works fine if the line `plt.ion()` is removed.
```python
#!/usr/bin/env python
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg 

plt.ion()
fig, ax = plt.subplots()
canvas = FigureCanvasQTAgg(fig)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "mmwe.py", line 8, in <module>
    canvas = FigureCanvasQTAgg(fig)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 21, in __init__
    super().__init__(figure=figure)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    self._update_figure_dpi()
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 261, in _update_figure_dpi
    self.figure._set_dpi(dpi, forward=False)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 477, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 913, in set_size_inches
    self.stale = True
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 230, in stale
    self.stale_callback(self, val)
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 589, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 495, in draw_idle
    if not (self._draw_pending or self._is_drawing):
AttributeError: 'FigureCanvasQTAgg' object has no attribute '_draw_pending'
```

**Expected outcome**
No error.

**Matplotlib version**
  * Operating system: Arch Linux
  * Matplotlib version: 3.1.1 (installed via pip)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.4
  * PyQt5 version: 5.13.0 (installed via pip)

**Comment by tacaswell** [comment]
I see why this is happening:

 - you are using the stock python prompt (not IPython)
 - you have created your figure with pyplot with interactive mode enabled
 - this causes a callback to be installed on the figure such that when it is changed and needs a re-draw, a draw is scheduled for the future.
 - this requires checking some state on the canvas to determine if it _is_ drawing or of a draw has already been scheduled
 - this state is set up late in the `__init__` process
 - the canvas that was created as part of `plt.figure` runs through this code path _before_ the callback gets installed


You will not have this problem in IPython because the stale callback works differently (we use a hook when the prompt returns to _find_ the stale figures rather than via a callback).

The two fixes I see are to either move the state initialization earlier in the process (but then there may be some weird race conditions with setting the DPI / DPI ratio correctly) or to make where we check the state more forgiving.  I think the second is probably the better option as it avoids the risk of race conditions.

**Comment by tacaswell** [comment]
@catastropeia I opened a PR to fix the crash, but you probably should not be doing that.  If you have 2 canvas that are both looking at the same underlying Figure you may get weird behavior (ex, they both try to change the size of the Figure and conflict with each other).

**Comment by ImportanceOfBeingErnest** [comment]
There are some usecases for this; like you may want to take an existing pyplot figure and show it with scrollbars in a QT window, or show all open pyplot figures in tabs of one single QT window, instead of each figure by its own. So if there is a way to support moving a figure from one canvas to another that would be fantastic.

**Comment by tacaswell** [comment]
At that point it is probably best to not use `pyplot` at all and just embed Matplotlib in your Qt application (see https://matplotlib.org/gallery/user_interfaces/embedding_in_qt_sgskip.html?highlight=embedding) or make sure you have fully destroyed the other canvas before you use the new one.

It is a bit dirty, but you can monkey-patch `plt.figure` to do some other embedding.  If we pave one of the cow-paths, I think that is a better one ("provide a factory that produces a figure embeded into what ever GUI you want").

**Comment by ImportanceOfBeingErnest** [comment]
Sure, I mean if you know from the beginning that you need that, it makes sense. But often you may have existing figures and decide on the fly what to do with them. 

To give an example (where we don't create the figure ourselves):

```
import matplotlib
matplotlib.use('Qt5Agg')
from PyQt5 import QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar


class ScrollableWindow(QtWidgets.QMainWindow):
    def __init__(self, fig):
        self.qapp = QtWidgets.QApplication([])

        QtWidgets.QMainWindow.__init__(self)
        self.widget = QtWidgets.QWidget()
        self.setCentralWidget(self.widget)
        self.widget.setLayout(QtWidgets.QVBoxLayout())
        self.widget.layout().setContentsMargins(0,0,0,0)
        self.widget.layout().setSpacing(0)

        self.fig = fig
        self.canvas = FigureCanvas(self.fig)
        self.canvas.draw()
        self.scroll = QtWidgets.QScrollArea(self.widget)
        self.scroll.setWidget(self.canvas)

        self.nav = NavigationToolbar(self.canvas, self.widget)
        self.widget.layout().addWidget(self.nav)
        self.widget.layout().addWidget(self.scroll)

        self.show()
        exit(self.qapp.exec_()) 


import seaborn as sns
iris = sns.load_dataset("iris")
g = sns.pairplot(iris, hue="species")
# pass the figure to the custom window
a = ScrollableWindow(g.fig)
```

Surprisingly, this works fine. But may create problems for more complicated cases(?).

**Comment by tacaswell** [comment]
If you also show the original window and resize that it goes very sideway:

```python
import matplotlib

matplotlib.use("Qt5Agg")

import seaborn as sns
from PyQt5 import QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

qapp = QtWidgets.QApplication.instance() or QtWidgets.QApplication([])


class ScrollableWindow(QtWidgets.QMainWindow):
    def __init__(self, fig):

        QtWidgets.QMainWindow.__init__(self)
        self.widget = QtWidgets.QWidget()
        self.setCentralWidget(self.widget)
        self.widget.setLayout(QtWidgets.QVBoxLayout())
        self.widget.layout().setContentsMargins(0, 0, 0, 0)
        self.widget.layout().setSpacing(0)

        self.fig = fig
        self.canvas = FigureCanvas(self.fig)
        self.canvas.draw()
        self.scroll = QtWidgets.QScrollArea(self.widget)
        self.scroll.setWidget(self.canvas)

        self.nav = NavigationToolbar(self.canvas, self.widget)
        self.widget.layout().addWidget(self.nav)
        self.widget.layout().addWidget(self.scroll)

        self.show()


iris = sns.load_dataset("iris")
g = sns.pairplot(iris, hue="species")
g.fig.show()
# pass the figure to the custom window
a = ScrollableWindow(g.fig)

exit(qapp.exec_())

```

**Comment by ImportanceOfBeingErnest** [comment]
Yep, you cannot show the original window of course. `plt.close(g.fig)` should probably live somewhere. But you get the idea: Take a pyplot figure and show it in some custom GUI.
