### ISSUE TITLE
Closing figures is done by number

### ISSUE THREAD

**Issue by vnmabus** [matplotlib/matplotlib#15203]
### Closing figures is done by number

**Currently, closing a figure is done using the `num` attribute in the manager. This can cause problems if there are figures not managed by pyplot, as the number could be the same as a
pyplot-managed figure.**

As there are efforts to reduce the dependency on pyplot, such as #14024, this should be changed for those to work well. Alternatively, a way to create a manager which selects an appropiate number could work.

**Code for reproduction**

```python
import matplotlib.pyplot as plt 

# Figure managed by pyplot 
fig1 = plt.figure() 
 
# Figure not managed by pyplot, but using the same backend 
fig2 = fig = plt.new_figure_manager(1).canvas.figure 

fig1.show() 
fig2.show()
```

**Actual outcome**

Closing one figure closes both.

**Expected outcome**

Closing one figure leaves the other open.

**Matplotlib version**
  * Operating system: All
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: All

**Comment by tacaswell** [comment]
The linkage is only one way, if you close the un-managed figure it closes the managed figure, but not the other way around.

>   Alternatively, a way to create a manager which selects an appropriate number could work.

How do you do that without managing all of the figures?

As a work around, you can do:

```
fig2.canvas.manager.num = str(uuid.uuid4)
```

which will de-couple everything.

----

Somewhat annoyingly, the only place that looks like it actually requires an integer is formatting the initial widow title.

**Comment by anntzer** [comment]
> Somewhat annoyingly, the only place that looks like it actually requires an integer is formatting the initial widow title.

Actually there's also `Figure.__setstate__` which assumes it can assign a number to an unpickled figure with `max(plt.get_fignums()) + 1`.

**Comment by tacaswell** [comment]
global state + pickling!

**Comment by jklymak** [comment]
I'm not up on how this all works, but it seems that pyplot should be keeping track of figure handles, not figure numbers or title strings?
