### ISSUE TITLE
Orphan "customizing" documentation

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#15213]
Googling "matplotlib rcParams" brings up the following page: https://matplotlib.org/users/customizing.html

I think this page may be an orphan. I can't figure out how to navigate to it from the https://matplotlib.org/ homepage. And does not seem integrated into the sphinx toc flow. For example if I press "next" in the navbar, and then "previous", I don't get back to it.

It also is apparently outdated. For example, it is missing the `legend.title_fontsize` parameter that was added in 3.0. And you'll note that it doesn't have "Version 3.1.1" in the title section the way that other pages in the current docs do.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, there are many such old files in the `/users` folder. Related https://github.com/matplotlib/matplotlib.github.com/pull/39

**Comment by mwaskom** [comment]
Is there a canonical file with this information, though? I cannot find one in the user guide

**Comment by ImportanceOfBeingErnest** [comment]
Oh, yes, sorry. This guide is now part of the tutorials:

https://matplotlib.org/tutorials/introductory/customizing.html
