### ISSUE TITLE
Having legend to the right of subplots different in PY2 and PY3

### ISSUE THREAD

**Issue by hamzamerzic** [matplotlib/matplotlib#15215]
I have a subplot and would like to show the legend only at the right of the rightmost subplots. I have the specified subplot size, but I get different behaviour in PY2 and PY3 when I apply tight layout.

For example, the same code in PY2 produces the nice plot above, but get's messed up in PY3: https://imgur.com/a/Xtt47Uy

I was able to achieve a similar result when doing `plt.subplots_adjust(wspace=0.03)` in PY3, but this breaks when I remove scale sharing in y since the y tick labels end up protruding the plots, e.g. something like this happens: https://imgur.com/a/99kfedy

Is there a way to achieve the same behaviour wrt the legend in PY3? Or could I somehow find the width of the y tick labels and do the subplot adjust per column (which seems super tedious)? The matplotlib that I'm using is '3.0.3'.

Thanks in advance!

P.S. I've also noticed that ticks appear by default in PY2 but not in PY3.

**Comment by jklymak** [comment]
Can you make a minimal self contained example that shows the behaviour?  You can also upload images directly to github

**Comment by tacaswell** [comment]
Can you please also include the versions of Matplotlib you are using?

**Comment by hamzamerzic** [comment]
Thanks for the answer. Here's a colab with an example of the old behavior in Python 2 with my 1.5.2 version and in Python 3 [[link](https://colab.research.google.com/drive/1w21pHc16-tpT1ky9FHw7Yj6V4kGpGsi7)]. 

I realised while writing this that if I use the default Matplotlib version in PY2 Colab which is 2.5.2 I get the same result as in PY3, so I guess it is not actually bug, but I would still be super thankful for any tips on how to get the same output as in the 1.5.2 version (the first plot in the colab).

The difference it seems to me is that the legend in 1.5.2 doesn't seem to be counted in the figure size, while in the newer versions it does and is part of whatever optimisation is being done by tight layout.

Thanks in advance!

**Comment by ImportanceOfBeingErnest** [comment]
I think in most cases it is a desireable feature to have the legend included in the layout_management. In the case you do not want that, though, you may exclude it via [`set_in_layout`](https://matplotlib.org/api/_as_gen/matplotlib.artist.Artist.set_in_layout.html)

```
legend = ax.legend(...)
legend.set_in_layout(False)
```

**Comment by hamzamerzic** [comment]
Ah thank you very much, just tested it and it works! One thing though, this now crops the legend when displaying in Colab. Any tips on have to "expand" the displayed part of the figure? Thanks!

**Comment by jklymak** [comment]
Well that is why we include the legend by default in the layout.  So that it doesn’t get cropped by bbox_inches=tight.  Are you saying such cropping did not happen in py2?   Please still make a fully self contained complete example.

**Comment by ImportanceOfBeingErnest** [comment]
In 1.5 the legend was included in the `bbox_inches="tight"`, but not in tight layout apparently. So that would mean you need to reinclude it after calling `tight_layout()`

```
legend = ax.legend(...)
legend.set_in_layout(False)
fig.tight_layout()
legend.set_in_layout(True)
fig.savefig(..., bbox_inches="tight")
```

**Comment by hamzamerzic** [comment]
Interesting. Ok, thank you! Will try it out now. I've updated the Colab to demonstrated the change. At the top you can see that it doesn't crop and at the bottom with the change it does.

**Comment by hamzamerzic** [comment]
Sweet, works as you described. Thank you very much for the quick help everyone!
