### ISSUE TITLE
hist plot broken for close values

### ISSUE THREAD

**Issue by SoniaSamipillai** [matplotlib/matplotlib#15238]
### Bug report

**Bug summary**

hist plot behaves unexpectedly, while plotting two close values

**Code for reproduction**

```python
a = [[3.94915814],[3.94915814]]
plt.hist(a)
b = [[3.9491581381352656],[3.9491581381352665]]
fig,ax = plt.subplots(figsize=(4,3))
plt.hist(b)
```

**Actual outcome**
two bars in wrong places in one plot and in the second case, no bars at all.

<img width="816" alt="Screen Shot 2019-09-09 at 9 04 51 AM" src="https://user-images.githubusercontent.com/46730455/64547250-113a0380-d2e1-11e9-93d0-0009fda98988.png">

**Expected outcome**

Single bar with vertical size 2

**Matplotlib version**

  * Operating system:Mac
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable): Google Colab
  * Other libraries:

**Comment by jklymak** [comment]
You can specify the bins.  And you can't expect numbers with more than 15 significant digits to be recognized as different if they are 64-bit doubles: https://en.wikipedia.org/wiki/IEEE_754

**Comment by tacaswell** [comment]
What does `nump.histogram` do with these inputs?

**Comment by ImportanceOfBeingErnest** [comment]
`numpy.histogram` calculates the histogram of the flattened array. So I'm not sure if that's comparable.

**Comment by jklymak** [comment]
```
N, binx = numpy.histogram(b)
In [23]: N
Out[23]: array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [24]: binx
Out[24]:
array([3.94915814, 3.94915814, 3.94915814, 3.94915814, 3.94915814,
       3.94915814, 3.94915814, 3.94915814, 3.94915814, 3.94915814,
       3.94915814])
In [27]: numpy.diff(binx)
Out[27]:
array([0.0000000e+00, 0.0000000e+00, 4.4408921e-16, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.4408921e-16,
       0.0000000e+00, 0.0000000e+00])
```

**Comment by lobpcg** [comment]
> 
> 
> You can specify the bins. And you can't expect numbers with more than 15 significant digits to be recognized as different if they are 64-bit doubles: https://en.wikipedia.org/wiki/IEEE_754

> You can specify the bins. And you can't expect numbers with more than 15 significant digits to be recognized as different if they are 64-bit doubles: https://en.wikipedia.org/wiki/IEEE_754

Of course, but the plot should be then a single bar with vertical size 2, rather than the produced empty plot, no?

**Comment by afvincent** [comment]
Well at least, the choice of the x-range seems a bit akward when the precision of the inputs increases:
```python
import matplotlib.pyplot as plt  
  
data_a = [[0.9999999999999], [1.0000000000001]]  
data_b = [[0.99999999999999], [1.00000000000001]]  
data_c = [[0.999999999999999], [1.000000000000001]] 
data_d = [[0.9999999999999999], [1.0000000000000001]]  
fig, axs = plt.subplots(nrows=2, ncols=2, num="hist_issue", 
                        clear=True, constrained_layout=True)  
for data, label, ax in zip([data_a, data_b, data_c, data_d], 
                           ["13 digits", "14 digits", "15 digits", "16 digits"], 
                           axs.flat):  
    ax.hist(data)  
    ax.set_title(label)  
  
plt.show() 
```
[hist_issue_with_high_precision.pdf](https://github.com/matplotlib/matplotlib/files/3592063/hist_issue_with_high_precision.pdf)

**Comment by tacaswell** [comment]
When guessing the bin size, the default (effectively passed through from numpy) is `np.linspace(min(data), max(data), 11)` which if your min and max are within a few of the mantissa of each other is going to result in singular bins (as @jklymak showed).  At that point which "bin" the counts land in is going to end up in details of how numpy implements the binning (remember the bins are half open except for the far right bin which is fully closed).   It looks like some of the counts are going to bins that have 0 width.

I suspect that this should be sorted out at the numpy level.

**Comment by jklymak** [comment]
We can try and get numpy to change their behavior here, but I’m against matplotlib special-casing this.

**Comment by jklymak** [comment]
I don't think we have an action here, so I'm going to close this.  TLDR: don't do things near floating point precision and expect them to work smoothly.
