### ISSUE TITLE
DOC: Automatic default rcParam expansion creates misleading sentences

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#15232]
Looking at the changes in #15230, the fact that `=` produces valid code (as argued in #15115) seems to be a point _against_ using it. Many sentences appear to use constructs like:
```
Use :rc:`something` to do something.
```
or
```
You can do something by setting :rc:`something`.
```

These will become:
```
Use rcParams[something] = "default" to do something.
```
or
```
You can do something by setting rcParams[something] = "default".
```

This implies that you should set the rcParam to its default value, but those sentence often just mean set it to _anything_.

_Originally posted by @QuLogic in https://github.com/matplotlib/matplotlib/pull/15115#issuecomment-529270587_

**Comment by jklymak** [comment]
👍 Ideally math should be part of a proper sentence.

**Comment by timhoffm** [comment]
I propose to use the more verbose

> rcParams[name] (default: Val)

to make it unambiguous.
