### ISSUE TITLE
Can't specify integer `font.weight` in custom style sheet any more

### ISSUE THREAD

**Issue by fpavogt** [matplotlib/matplotlib#15240]
### Bug report

In matplotlib v3.1.1, the `font_manager.FontManager.score_weight` function [was made more robust](https://matplotlib.org/3.1.1/api/api_changes.html#fontmanager-scores), and now issues an exception if a integer value is passed as a string (e.g. '500'). 

This, however, causes havoc with my custom style sheet, in which I define `font.weight: 500`, which then appears to be converted to `'500'` by the time it reaches the `score_weight` function.

**Expected outcome**

Specifying `font.weight: 500` used to work in earlier versions. The [doc still suggests (indirectly) that this should work](https://matplotlib.org/tutorials/introductory/customizing.html?highlight=rcparams%20weight#a-sample-matplotlibrc-file).

**Question**
What is the proper way to specify integer font weights in style sheets ? Should they be banned (and the doc clarified) in favor of name-based strings (e.g. `normal`) ? Or the `score_weight` function modified to handle them?  

**Matplotlib version**
  * Operating system: OS X 10.13.6
  * Matplotlib version: 3.1.1
  * Python version: 3.7.3

**Comment by afvincent** [comment]
https://github.com/matplotlib/matplotlib/blob/30ee9390920ba7f58b89f6e9101dacab808cfc59/lib/matplotlib/rcsetup.py#L1098
indeed seems to convert an int argument an str.

**Comment by anntzer** [comment]
it should indeed be replaced by something like
```python
def validate_int_or_string(s):
    if isinstance(s, str):
        try: return int(s)
        except ValueError: return s
    elif isinstance(s, numbers.Number):  # also numpy ints
        return s
    else: fail
```

**Comment by PatrickFeiring** [comment]
Same as #15170
