### ISSUE TITLE
Colorbar tick placement issues with ImageGrid and LogNorm

### ISSUE THREAD

**Issue by samaloney** [matplotlib/matplotlib#15247]
### Bug report

**Bug summary**

The colorbar tick marks are all compressed ontop of each other for the image which has a LogNorm normalisation applied.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1.axes_grid import ImageGrid

x,y = np.ogrid[-4:4:31j,-4:4:31j]
z = 120000*np.exp(-x**2-y**2)

fig = plt.figure()
grid = ImageGrid(fig, 111,  # similar to subplot(141)
                     nrows_ncols=(2, 1),
                     axes_pad=0.05,
                     label_mode='L',
                     cbar_location='right',
                     cbar_mode='each'
                     )

im0 = grid.axes_all[0].imshow(z)
im1 = grid.axes_all[1].imshow(z, norm = LogNorm(z.min(), z.max()))

cb0 = grid.cbar_axes[0].colorbar(im0)
cb1 = grid.cbar_axes[1].colorbar(im1)

plt.show()
```

**Actual outcome**

![imagegrid_cbar_issue](https://user-images.githubusercontent.com/24570854/64686831-3f564980-d481-11e9-9a77-94c8b517849b.png)

**Expected outcome**

The colorbar tick marks would be place correctly as in the the non-lognorm image.

**Matplotlib version**

  * Operating system: macOS 10.14.6
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.0
  * Jupyter version (if applicable):
  * Other libraries: 

pip installed

**Comment by anntzer** [comment]
interestingly enough, this happens even after switching to the "normal" colorbar implementation (https://github.com/matplotlib/matplotlib/pull/13397), even though this doesn't happen for non-imagegrid axes...

**Comment by samaloney** [comment]
It seems like it could be related to #12155 as when ImageGrid is called with the above parameters it creates a default colorbar on each row which then has to be updated. I tried to adapt the solutions in #12155 but no luck yet. I also came across #13397 but haven't had the time to install locally to test, I guess now I don't

**Comment by samaloney** [comment]
Actually this kinda works `cb1 = grid.cbar_axes[1].colorbar(im1, ticks=[0.001,10, 1000])` so seems like there is an extra axis somewhere ...

**Comment by ImportanceOfBeingErnest** [comment]
The code also errors out when run interactively with the qt backend and moving the mouse over the axes.

```
AttributeError: 'Colorbar' object has no attribute 'formatter'
Traceback (most recent call last):
  File "d:\***\lib\matplotlib\cbook\__init__.py", line 196, in process
    func(*args, **kwargs)
  File "d:\***\lib\matplotlib\backend_bases.py", line 2805, in mouse_move
    data_str = a.format_cursor_data(data)
  File "d:\***\lib\matplotlib\image.py", line 972, in format_cursor_data
    + "]")
AttributeError: 'Colorbar' object has no attribute 'formatter'
```

**Comment by zwep** [comment]
Have you tried to set `vmin` when performing `plt.imshow`?

You can see an example of this here

https://stackoverflow.com/questions/56439837/colorbar-scaling-in-imagegrid

**Comment by samaloney** [comment]
Yea it doesn't help unfortunately

**Comment by zwep** [comment]
Have you tried something without Imagegrid? Because I think the problem lies there...

**Comment by zwep** [comment]
Here, I tried something without `Imagegrid`. Works better to say the least


```
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1.axes_grid import ImageGrid

x,y = np.ogrid[-4:4:31j,-4:4:31j]
z = 120000*np.exp(-x**2-y**2)


fig, ax = plt.subplots(2,1)
map_ax0 = ax[0].imshow(z)
map_ax1 = ax[1].imshow(z,  norm=LogNorm(z.min(), z.max()))
plt.colorbar(mappable=map_ax0, ax=ax[0])
plt.colorbar(mappable=map_ax1, ax=ax[1])
plt.tight_layout()
```

Here is an example

![github_alt_imgrid](https://user-images.githubusercontent.com/26649804/65044122-9f0a9400-d95c-11e9-825d-9ea596067886.png)
