### ISSUE TITLE
Check if canvas is clean or dirty

### ISSUE THREAD

**Issue by vanillajonathan** [matplotlib/matplotlib#15256]
I would like a attribute or a method to check if a canvas (or figure) is clean or dirty, i.e. if anything has been drawn on it.

**Comment by vanillajonathan** [comment]
Yes, a `empty` property or method would be fine too. It would be easy to use.

I just want to determine if anything is drawn on the canvas/figure so I can do things like only saving if it makes sense.

**Comment by anntzer** [comment]
this idea was already discussed and rejected in https://github.com/matplotlib/matplotlib/issues/11040.

**Comment by tacaswell** [comment]
It will be stale until it is drawn.

Why do you want this check?

**Comment by vanillajonathan** [comment]
My application displays a text informing the user that nothing has been drawn so the user doesn't wonder why the canvas is blank.

But it could also be used to disable the save figure button, or to only save an image if the canvas is not blank.

**Comment by timhoffm** [comment]
Would this as `Figure.is_empty()` work?

~~~
def is_empty(self):
    """Return whether the figure no Artists (other than the default background `.Rectangle`)."""
    contained_artists = self.findobj(include_self=False)
    if len(contained_artists) < 1:
        return True
    elif len(contained_artists) == 1 and isinstance(contained_artists[0], Rectangle):
        return True
    else:
        return False
~~~

**Comment by vanillajonathan** [comment]
Probably, but I don't know since I don't know matplotlib. But I think such an addition would be a useful addition to the API because it would be easily discoverable. I was not able to figure out how to do that myself by just glancing at the API documentation.

**Comment by timhoffm** [comment]
The question is also direct at the other devs (@anntzer @tacaswell). It seems reasonable to me, but there were some caveats.

**Comment by anntzer** [comment]
I personally don't like the idea, for the same reasons as explained by @ImportanceOfBeingErnest in the other thread, and would rather we document better how the user can check whatever definition they want of emptiness.

**Comment by jklymak** [comment]
The reason we do not document this is probably because it’s a strange thing to lose track of.

**Comment by timhoffm** [comment]
For reference the argument is https://github.com/matplotlib/matplotlib/issues/11040#issuecomment-380986726.

I do not quite agree. It would be legitimate to define a meaning of `is_empty` and document it as such. IMHO that should be "The figure does not contain any artists except its background rectangle." But I'm not strongly feeling about this. So, don't want to go into a discussion if there are contrary opinions among core devs.

**Comment by tacaswell** [comment]
This feels like it is trying to push application specific bookkeeping logic back up into Matplotlib without a clear understanding of the kinds of bookkeeping that are needed.  As discussed before "empty" can be ambiguous.

There does seem to be a bug in stale handling...

**Comment by vanillajonathan** [comment]
Alternatively perhaps just the documentation could be improved?

**Comment by timhoffm** [comment]
Documentation improvements are always good. Which information would you need, where would you expect to find such information?

**Comment by vanillajonathan** [comment]
I would expect to find information on the page dealing with `Figure` and/or `Canvas` about how to check if anything has been drawn. The code in the post above by @ImportanceOfBeingErnest is what helped me accomplish what I was after.
