### ISSUE TITLE
Large memory growth with log scaling and linear ticking

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#15251]
I found that I can make my machine spike in memory usage with just this:
```python
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

fig, ax = plt.subplots()
ax.set_yscale('log')
ax.yaxis.set_major_locator(MultipleLocator(100))
plt.savefig('test.png')
```
When I say huge, I mean I see memory usage go up and I kill it before I end up with an unresponsive system.

Removing either of the log scaling or the `MultipleLocator` causes the huge memory spike to disappear.

**Comment by dopplershift** [comment]
This occurs with master and 3.1.1.

**Comment by jklymak** [comment]
Looks like I broke this with 740dda5050e13  No idea how

**Comment by jklymak** [comment]
OK, so before the limits were -inf and inf, and then the autoscaling tried to handle that incorrectly.  We tried in the PR above to fall back to the view limits, which are 0 and 1.  But then the transform is log, so it makes the left view limit 1e-300 (ahem, which happens at a line of code commented "this should never take effect).  Then the code tries to auto-add a margin and changes [1e-300, 1] to [1e-315, 1e15].  Obviously adding ticks every 100 between 1e-315 and 1e15 will take a while as you will have 1e13 ticks.  

I dunno what the right solution here is.  A log axis with no data will have undefined bounds, but clearly we fall back to something that will have trouble for some locators.
