### ISSUE TITLE
Axes labels and legend move off FigureCanvas plot when Qt window gets smaller

### ISSUE THREAD

**Issue by EricKJagde** [matplotlib/matplotlib#15265]
### Bug report

**Bug summary**

I have to use matplotlib.axes.Axes.set_position to dynamically set the position of the axes so that the y-axis label, the x-axis label, and the legend stay on the screen as the qt window/widget gets smaller.  I have to calculate values for the pos parameter for this function (pos=[left_corner, bottom_corner, width, height] w/ values normalized).

**Actual outcome**

The y-axis labels, the x-axis labels, and the legend move off of the plot (parts of them) as the window/widget holding the axes gets smaller.

**Expected outcome**

I want the matplotlib.figure.Figure to resize when the Qt window resizes so that the y-axis labels, x-axis labels, and legend stay on the FigureCanvas.  I want the plot axes to get smaller so that everything is still visible and on the page.  This is why I am using the set_position function.  It would be nice if this was built in.

**Matplotlib version**
  * Operating system: Linux x86_64
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Did you try constrained layout?

**Comment by EricKJagde** [comment]
Yeah, I tried plt.subplots(constrained_layout=True) and plt.rcParams['figure.constrained_layout.use'] = True as indicated [here](https://matplotlib.org/3.1.1/tutorials/intermediate/constrainedlayout_guide.html).

I got errors saying that constrained_layout is an invalid keyword argument or rc parameter.

That site indicates that the constrained_layout feature is experimental.  That is where I got the suggestion to use the set_position function.

**Comment by EricKJagde** [comment]
I guess that this issue is solved with later versions of matplotlib where the constrained_layout feature exists.  Could that be possible?

**Comment by jklymak** [comment]
Yes. I think it came in 2.2.  Whether it fixes your exact problem is another issue.  

Constrained layout has a couple of rough edges but either folks aren’t hitting them or just not reporting them.  So i think it’s possible that it will become non experimental soon.

**Comment by EricKJagde** [comment]
That sounds good.  Looks like we need to update to a newer version then.  Thanks for the help.

[It did come in 2.2](https://matplotlib.org/3.1.1/users/prev_whats_new/whats_new_2.2.html).

**Comment by jklymak** [comment]
Well what you want to do may be possible without cl.  But that’s the kind of thing it was designed to do.
