### ISSUE TITLE
Tight layout issue in latest version

### ISSUE THREAD

**Issue by HyperionC21** [matplotlib/matplotlib#15311]
### Bug report
Issue when plotting a confusion matrix
**Bug summary**

Code that used to work doesn't fit properly with tight layout.
Used to work with 3.1.0 on same platform.

**Code for reproduction**
https://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html

**Actual outcome**

https://imgur.com/a/eXHBAUY

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version:  3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.4
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
This bug has been reported a few times and will be fixed when 3.2 is released.  For now downgrade to 3.1.  Thanks!
