### ISSUE TITLE
How to create a new backend for embedding plot in eclipse?

### ISSUE THREAD

**Issue by AlexLuya** [matplotlib/matplotlib#15310]
Hello,I want to develop a plugin which can embed plot into eclipse(not popup a new windows).Currently,I got these suggestions
 
1  Create a new backend -- say a "PyDev" backend;
2  Having some server receiving data from this 'PyDev' backend;
3  Plotting the received data by using java visualization lib like;
    Nebula: https://www.eclipse.org/nebula/widgets/visualization/visualization.php

Question
1,Is this new backend needed?Why can't I use existed backend?
2,If yes,any doc to help develop new backend?

**Comment by ImportanceOfBeingErnest** [comment]
xref: https://stackoverflow.com/questions/58023969/any-suggestions-for-developing-a-plugin-to-embed-matplotlib-result-into-eclipse

In theory no dedicated backend is needed. Instead one could imagine to use the existing webagg backend and connect an eclipse browser plugin to its server.

**Comment by AlexLuya** [comment]
@ImportanceOfBeingErnest Thanks,do you know any doc to tell how backend works underhood, and I have checked here:
https://matplotlib.org/3.1.1/devel/index.html
Not found the related introduction.

**Comment by jklymak** [comment]
@AlexLuya Thats pretty advanced, and not likely to get a short intro (though if after you are done you'd like to contribute one, that would be awesome!)   You'll probably have to find a backend like what you envision and follow the code.

**Comment by jklymak** [comment]
I don't think there is an action here.  Follow up on https://discourse.matplotlib.org if there is further discussion...
