### ISSUE TITLE
imshow log scale 

### ISSUE THREAD

**Issue by themrzmaster** [matplotlib/matplotlib#15337]
### Bug report

**Bug summary**

plot image background scales incorrectly when on log scale, if its linear works great

**Code for reproduction**

```python
plt.scatter(df['razao atrito'],df['resistencia'],zorder=2)
plt.xscale("log",nonposx="mask")
plt.yscale("log",nonposy="mask")
img=plt.imread("Capture.jpg")
plt.imshow(img,aspect='auto',zorder=1,extent=[0.1,10,1,1000])
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/852747/65549226-7bfb5980-def3-11e9-9dc9-985006730c99.png)

**Expected outcome**
![WhatsApp Image 2019-09-24 at 17 30 35](https://user-images.githubusercontent.com/852747/65549293-9df4dc00-def3-11e9-804c-c359dbef2f75.jpeg)

**Comment by QuLogic** [comment]
That outcome is correct. The image is shown in data space and your data space is non-linear.

You probably want to specify `transform=ax.transAxes` and a 0-1 extent so that it is shown in the Axes coordinates, which are linear.
