### ISSUE TITLE
Artist Tutorial missing link to Image docs

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15334]
In the [artist tutorial](https://matplotlib.org/tutorials/intermediate/artists.html#sphx-glr-tutorials-intermediate-artists-py), there's a paragraph about graphic primitives that links out to the docs for all the primitives except image, which is still formatted as if it has a link:

![image](https://user-images.githubusercontent.com/1300499/65527428-9e27b400-dec0-11e9-8f3e-b25fa4240d40.png)

I'm not sure if it's a formatting error or it's supposed to link out to AxesImage, but the inconsistency is a bit jarring.

**Comment by punndcoder28** [comment]
Hey. Can I take up this issue? Can you give more details as to what that needs to be done for this issue?

Thanks.

**Comment by sameshl** [comment]
@story645 I made a PR to fix this but I am unable to understand what might cause this issue. As I see the link with formatting issue https://github.com/matplotlib/matplotlib/blob/6870ac00097508411c10d67b96f9863d597d04aa/tutorials/intermediate/artists.py#L60 looks syntactically same to the one which is getting formatted correctly in the same file here https://github.com/matplotlib/matplotlib/blob/6870ac00097508411c10d67b96f9863d597d04aa/tutorials/intermediate/artists.py#L29. If you have any idea on how to fix it let me know.

**Comment by ImportanceOfBeingErnest** [comment]
This issue is already fixed in master, so there isn't really anything to do here. Hence closing.
