### ISSUE TITLE
pyplot quiver: x and y indexes in U and V arrays switched?

### ISSUE THREAD

**Issue by FCI-adam** [matplotlib/matplotlib#15343]
#14503 
# Bug report

**Bug summary**

pyplot.quiver seems to flip the x and y index values with each other for the U and V 2-D array inputs (arguments 3 and 4).  Flipping each index (x->y and y->x) gives me the expected results, but I don't want to go back and debug a workaround if this is an issue and gets fixed in the future.

**Code for reproduction**

```
import numpy
import sympy
from sympy.utilities.lambdify import lambdify
from matplotlib import pyplot

### sympy formula defs ###
U = .1
x, y, z = sympy.symbols('x y z')
u = U * x
ufunc = lambdify((x), u)
v = -U * y
vfunc = lambdify((y), v)
#####################

### create x,y,z space ###
x = numpy.linspace(-1, 1, 81)
y = numpy.linspace(-1, 1, 81)
z = numpy.linspace(-1, 1, 81)
####################

### and 2 - 3D arrays to represent u and v components of vector field for each x,y,z ###
u = numpy.zeros((81, 81, 81))
v = numpy.zeros((81, 81, 81))
for i in range(0,80):
  for j in range(0,80):
    for k in range(0,80):
      u[i, j, k] = ufunc(x[i])
      v[i, j, k] = vfunc(y[j])
pyplot.quiver(x[0::4], y[0::4], u[0::4,0::4,0], v[0::4,0::4,0], angles='xy', pivot='tail', units='xy')
pyplot.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/55854973/65720793-b4777080-e076-11e9-8d09-69f4e3d96ce3.png)

Switching:

      u[i, j, k] = ufunc(x[i])
      v[i, j, k] = vfunc(y[j])

To:

      u[j, i, k] = ufunc(x[i])
      v[j, i, k] = vfunc(y[j])

gave me the desired result.

**Expected outcome**
![image](https://user-images.githubusercontent.com/55854973/65720896-eee10d80-e076-11e9-8f5e-28894ffe142e.png)

I'm new to matplotlib and haven't used previous versions, so I don't know if this is something new or if I'm just doing it wrong (not sure why the x and y components should be switched if that's the case...)

u is a function of x, so verifying the u array can be done by entering stuff like u[20, 30, 0], followed by u[10,30,0] (keep y and z constant); the value should be different.  The same goes for v, only this is a function of y (so enter stuff like y[30, 20, 0] followed by y[30, 10, 0]).  As seen in the Actual outcome image, u and v vary when they shouldn't be (magnitude of the x or y component of the arrows change when they should stay constant).

If it's any additional help, I'm looking at example 1.2 on page 8 (labeled page 4) in:
https://digitalworks.union.edu/cgi/viewcontent.cgi?article=2228&context=theses

  * Operating system: Windows 10
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.3
  * Jupyter version (if applicable): NA
  * Other libraries: 

python installed from windows install package
matplotlib installed from pip (version 19.2.3 running through powershell with admin privs)
conda not used

**Comment by ImportanceOfBeingErnest** [comment]
It is very common to interprete the first dimension of a 2D array as the y component and the second as x component. If you imagine the array  to be a list of rows, this is consistent with how the array looks:

```
[[1,2,3],
 [4,5,6]]
```
x commonly denotes the horizontal direction so values of a row are subsequent values along the x dimension.

**Comment by jklymak** [comment]
Thanks @FCI-adam but this is working as expected and is the convention we use for all our matrix display.  Please also note our new discourse.matplotlib.org is a good place to ask more general questions like this if you aren't sure if something is a bug.
