### ISSUE TITLE
pyplot plot raises IndexError when x or y are pandas Index objects

### ISSUE THREAD

**Issue by hoffm386** [matplotlib/matplotlib#15342]
### Bug report

**Bug summary**

Pandas Index objects used to be a supported "array-like" type for plotting in Matplotlib 3.0.2.  Now in Matplotlib 3.1.1 it produces an IndexError.

**Code for reproduction**

```python
import pandas as pd
from matplotlib import pyplot as plt
x = pd.Index([0,1,2])
y = pd.Series([2,3,4])
plt.plot(x, y)
```

**Actual outcome**

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-5a4667d5ecd4> in <module>
      1 x = pd.Index([0,1,2])
      2 y = pd.Series([2,3,4])
----> 3 plt.plot(x, y)

~/.conda/envs/prework-labs/lib/python3.7/site-packages/matplotlib/pyplot.py in plot(scalex, scaley, data, *args, **kwargs)
   2793     return gca().plot(
   2794         *args, scalex=scalex, scaley=scaley, **({"data": data} if data
-> 2795         is not None else {}), **kwargs)
   2796 
   2797 

~/.conda/envs/prework-labs/lib/python3.7/site-packages/matplotlib/axes/_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1664         """
   1665         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D._alias_map)
-> 1666         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1667         for line in lines:
   1668             self.add_line(line)

~/.conda/envs/prework-labs/lib/python3.7/site-packages/matplotlib/axes/_base.py in __call__(self, *args, **kwargs)
    223                 this += args[0],
    224                 args = args[1:]
--> 225             yield from self._plot_args(this, kwargs)
    226 
    227     def get_next_color(self):

~/.conda/envs/prework-labs/lib/python3.7/site-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs)
    397             func = self._makefill
    398 
--> 399         ncx, ncy = x.shape[1], y.shape[1]
    400         if ncx > 1 and ncy > 1 and ncx != ncy:
    401             cbook.warn_deprecated(

IndexError: tuple index out of range
```

**Expected outcome**

A plot of `x` vs. `y`
![<matplotlib.lines.Line2D plot graphing the x values against the y values](https://user-images.githubusercontent.com/2507951/65717024-35be0b80-e055-11e9-9902-5e8dbf96e8a0.png)

This is what used to work in Matplotlib 3.0.2.

**Matplotlib version**

  * Operating system: macOS Mojave
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: pandas 0.25.0

Installed Matplotlib with `conda` from the `conda-forge` channel

**Other notes**

If `y` is an Index instead of `x`, the same error is produced.  If the Index has a different `dtype` than integer, the same error is produced.

If I convert the Index object to some other array-like type (pandas Series, numpy array, base Python list), it works just fine.  So, something like:

```python
import pandas as pd
from matplotlib import pyplot as plt
x = pd.Index([0,1,2])
y = pd.Series([2,3,4])
plt.plot(list(x), y)
```

**Comment by ImportanceOfBeingErnest** [comment]
I just tried this code in matplotlib 3.1.0, as well as in current master and it works fine in both cases. 
My personal recommendation would be to revert to 3.1.0 until 3.2.0 is released.

**Comment by ImportanceOfBeingErnest** [comment]
This seems to be due to pandas 0.25 in use. Can you try with pandas 0.24.x or 0.25.1 ?

**Comment by timhoffm** [comment]
See also https://github.com/pandas-dev/pandas/issues/27775

**Comment by MossadIAP** [comment]
Hey, this issue is still there, any solution?

**Comment by MossadIAP** [comment]
pandas version 1.4.1 on spyder

**Comment by tacaswell** [comment]
@MossadIAP Please open a new issue with code to reproduce + mpl + pandas version numbers.

Pandas can be a bit of a moving target, when in doubt convert to numpy arrays before passing in to Matplotlib.

**Comment by MossadIAP** [comment]
I'm trying plt.suplots, so there's this line where the bug takes place " axs[0, 1].plot(datetimeindex, data)" I change datetime array to any other array of the same size it runs perfectly, tried converting using np.array(), doesn't make any difference. It didn't use to give me this error 2 days ago, this is due to spyder updating probably and me having to update all packages. Not sure where it all went wrong with this one.

**Comment by tacaswell** [comment]
@MossadIAP Please open a new issue with a reproducible example and the details of what versions you have installed.   It is confusing to discuss new bugs in the comments of a fixed bug and it is very hard to help you without a minimal reproducible (that we can copy-paste-test) to debug.
