### ISSUE TITLE
Warnings about bad config (when using default config)

### ISSUE THREAD

**Issue by vwood** [matplotlib/matplotlib#15345]
### Bug report

**Bug summary**

Seeing ugly extra output on using matplotlib 3.1.1, with default configuration.

**Code for reproduction**

```python

import matplotlib.pylab as pl
pl.figure()
```

**Actual outcome**

```
"KConfigIni: In file /etc/matplotlibrc, line 41: " Invalid entry (missing '=')
"KConfigIni: In file /etc/matplotlibrc, line 41: " Invalid entry (missing '=')
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
```

**Expected outcome**

```
```

**Matplotlib version**

  * Operating system: Ubuntu 18.10, Linux 4.18.0-25-generic #26-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8
  * Other libraries: n/a

The above despite the config specifying TkAgg (which incidentally is the line it complains about)

installed matplotlib with pip install, python from apt install.

**Comment by jklymak** [comment]
Any chance that line is improperly written?  Can you let us know what it says?

**Comment by vwood** [comment]
That line reads:

```
backend      : TkAgg
```

**Comment by timhoffm** [comment]
Interestingly the error comes from `KConfigIni`, which with some right could expect an equal sign if this was an ini-style format.

The question is, why is KConfig involved at all? AFAIK we have our own rc file parser in  `_rc_params_in_file`.

**Comment by QuLogic** [comment]
That's correct, we don't use `KConfigIni`  directly. Try running with `-W error` and see if the traceback sheds any light on where it's coming from.

**Comment by vwood** [comment]
I only get the same warning:

```
$ python3 -W error example.py 
"KConfigIni: In file /etc/matplotlibrc, line 41: " Invalid entry (missing '=')
"KConfigIni: In file /etc/matplotlibrc, line 41: " Invalid entry (missing '=')
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
$ 

```

**Comment by vwood** [comment]
Also, ltrace seems to suggest the culprit is "libKF5Style.so.5"

```libKF5Style.so.5->_ZN13KSharedConfig10openConfigERK7QString6QFlagsIN7KConfig8OpenFlagEEN14QStandardPaths16StandardLocationE(0x7ffd8946de70, 0x7ffd8946de68, 3, 16"KConfigIni: In file /etc/matplotlibrc, line 41: " Invalid entry (missing '=')
) = 0x7ffd8946de70
```

**Comment by anntzer** [comment]
@sandrotosi Perhaps you can help on this?  IIRC putting the matplotlibrc in /etc/matplotlibrc is a debian-packaging-specific thing to start with.

**Comment by anntzer** [comment]
In my view this is a bug on Debian/Ubuntu's side -- they are the ones who put the matplotlibrc file in /etc rather than in its normal location (under site-packages/matplotlib/mpl-data) -- so this should be reported on the Debian/Ubuntu bug tracker.

**Comment by sandrotosi** [comment]
Debian never packaged 3.1.1 (i'm doing so now, for 3.1.2) so the user probably tried to upgrade it outside of the debian/ubuntu package management system.

**Comment by anntzer** [comment]
Thanks for the heads up, let's leave this as is then.
