### ISSUE TITLE
PySide2 + Matplotlib: Non-blocking show not working

### ISSUE THREAD

**Issue by GPhilo** [matplotlib/matplotlib#15359]
### Bug report

When using matplotlib in interactive mode or with `show(block=False)`, with pyside2 as qt5 backend, the visualization is broken.
In interactive mode, on calls to any figure-opening function (e.g., `subplot()` or directly `plt.plot()`) the figure is created, but it's black. Calling `show()` or `draw()` doesn't help, calling `pause(0.001)` draws the plot but the interactive controls are not working.
In non-interactive mode, everything works as long as `show()` is called with `block=True`, otherwise it has the same behaviour as the interactive mode.
This seems to be specific to pyside2, as the same setup with pyqt5 works as expected.

**Note**: I have Qt5 installed system-wide (using the Linux runfile from the Qt5 homepage), not sure if it's used in the conda environment though.

```
conda create -n test_matplotlib python=3
conda activate test_matplotlib
pip install pyside2 matplotlib
```
in python:

```python
import matplotlib.pyplot as plt
plt.ion()
plt.plot(range(10), range(10)) # shows a black window not responding to input
plt.pause(0.001) # draws the figure, but still no response to input
```

**Actual outcome**
![Screenshot from 2019-10-02 10-47-22](https://user-images.githubusercontent.com/4441724/66030669-1fef9100-e502-11e9-8b52-b65276f2adef.png)

**Expected outcome**

The figure shows and is interactive.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg (via PySide2 v 5.13.1)
  * Python version: 3.7.4
  * Jupyter version (if applicable):
  * Other libraries: Qt5 5.13.1

**Comment by tacaswell** [comment]
Does this work for you as expected in IPython?

My suspicion is that pyqt by default installs in input hook on import but pyside2 does not.  Matplotlib's policy has been that we do not get involved in setting up the input hooks, as that is the responsibility of the prompt, to avoid getting into situations where things are broken because too many packages are trying to be helpful and breaking each other!

After a bit of research, it appears that pyside2 does not even provide a input hook implementation, this should go to them as a feature request.  For now I think your options are to use pyqt (which provides an input hook for you), use IPython (which has both a prompttoolkit input hook) or vendor the readline based input from IPython (see https://github.com/ipython/ipython/blob/master/IPython/lib/inputhookqt4.py it is called qt4, but it works with all qt bindings) into your code.

See https://github.com/matplotlib/matplotlib/pull/4779 for many details about input hooks and how GUI event loops get integrated with the prompt.

**Comment by anntzer** [comment]
fwiw I cannot repro this locally (on Arch Linux).

**Comment by larsoner** [comment]
FYI I have this problem on Ubuntu 22.10 using both PySide2 and PySide6 installed via `pip`, but not PyQt5 or PyQt6

**Comment by tacaswell** [comment]
See https://matplotlib.org/stable/users/explain/interactive_guide.html for lots of details, but the short version is for the UI to be "live", you need something to spin the GUI event loop.  In blocking mode what is blocking the prompt is the event loop so it works, in non-blocking mode you need something to be running the event loop while the prompt waits for you to work.  

Python has a `PyOS_InputHook` that is used by readline at the prompt.  PyQt installs an inputhook on import, pyside does not.  I am failing to find a way to manually install the hook for pyside (I can not find `PyOS_InputHook` in any of the pyside source....) as it appears they still do not provide one.

If you use IPython by default they use prompt toolkit and provide an input hook for Qt.

I do not think there is anything that we can do on the mpl side to fix this so I am inclined to close this.

**Comment by larsoner** [comment]
Agreed with all of that, just wanted to document that this is more or less a known bug with PySide6 compared to PyQt6!

**Comment by cbrnr** [comment]
Is there a relevant bug report? I agree this is a limitation, but we should report it just in case the PySide are not aware or they think it should be implemented e.g. on MPL side. I tried searching here: https://bugreports.qt.io/issues/?jql=text%20~%20%22matplotlib%20ion%22

I'm happy to create an issue if there is none, but I'm afraid I don't understand enough of the technicalities involved. If they want more details, would it be OK to include you @tacaswell?

**Comment by tacaswell** [comment]
If you create an issues with pyside, the headline should be about `PyOS_InputHook` not anything about Matplotlib.

Yes, but I think linking here is probably enough.

**Comment by cbrnr** [comment]
https://bugreports.qt.io/browse/PYSIDE-2192

**Comment by hoechenberger** [comment]
Hello, this is unfortunately still an issue today, and nothing seems to be moving on the PySide of things (pun intended). I'm wondering if there's anything we can do to resolve or work around this issue, or to motivate the PySide devs to fix the problem? Lots of users must be facing this issue, no?

**Comment by larsoner** [comment]
Just wanted to report back that an upstream fix has been merged in PySide and should come out with PySide 6.7.3 and later, and will probably be backported to [6.7.2 on conda-forge](https://github.com/conda-forge/pyside2-feedstock/pull/230)
