### ISSUE TITLE
ScalarFormatter.set_powerlimits documentation seems inconsistent

### ISSUE THREAD

**Issue by cmbant** [matplotlib/matplotlib#15376]
### Bug report

Documentation says:
> set_powerlimits(self, lims)[source]
> Sets size thresholds for scientific notation.
> (min_exp, max_exp)
> A tuple containing the powers of 10 that determine the switchover threshold. Numbers below 10\*\*min_exp and above 10\*\*max_exp will be displayed in scientific notation.

However

```
    sFormatter = matplotlib.ticker.ScalarFormatter(useOffset=False, useMathText=True)
    sFormatter.set_powerlimits((-2, 2))
    plt.plot([120,130,140],[0.03,0.05,0.08])
    plt.gca().xaxis.set_major_formatter(sFormatter)
    plt.gca().yaxis.set_major_formatter(sFormatter)
```

does use scientific notation on the y axis but not the x axis. The the correct description of the actual behaviour seems to be 

> A tuple containing the powers of 10 that determine the switchover threshold. Numbers with absolute values below 10**(min_exp+1) and above 10**(max_exp+1) will be displayed in scientific notation.

Or it is a bug (would make more sense if the original description were correct).

**Comment by ImportanceOfBeingErnest** [comment]
A confusing bit is that you are using the same formatter for both axes. If using a dedicated formatter per axis it would give 

```
import matplotlib.ticker
import matplotlib.pyplot as plt

sFormatter1 = matplotlib.ticker.ScalarFormatter(useOffset=False, useMathText=True)
sFormatter1.set_powerlimits((-2, 2))

sFormatter2 = matplotlib.ticker.ScalarFormatter(useOffset=False, useMathText=True)
sFormatter2.set_powerlimits((-2, 2))

plt.plot([120,130,140],[0.03,0.05,0.08])
plt.gca().xaxis.set_major_formatter(sFormatter1)
plt.gca().yaxis.set_major_formatter(sFormatter2)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/66169512-effad780-e640-11e9-930d-4bdfa05a8f17.png)

Still, the sentence in the documentation remains incorrect (or at least not detailed enough), as seen from the y axis.

**Comment by anntzer** [comment]
As a general rule a single formatter instance cannot be used across multiple axises --- though https://github.com/matplotlib/matplotlib/pull/13482 fixes that :)

**Comment by timhoffm** [comment]
Reusing formatters is off-topic.

The actual issue is a documentation issue. IMHO it's not a bug, but one has to think about the limits in the right way, see #17590.
