### ISSUE TITLE
Default support unicode in plots !

### ISSUE THREAD

**Issue by yinshurman** [matplotlib/matplotlib#15384]
### Feature request

**it is quite frustrating to deal with the unicode problem !
I tried many solutions from the web ,none of it worked for me on Mac OS,
and most of them looks very long and complicated .

**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
Unfortunately, it's not clear what is meant by *"the unicode problem"* here. In general matplotlib does allow to use unicode in figures. 

Please note that the template for bug reports is meant to be filled out completely. This will allow us to understand the problem and potentially either direct you towards a solution or identify which part of matplotlib would need to be fixed.

I will close this for now; but please feel free to update the issue with the necessary information - in particular a minimal runnable code example that shows the issue and we can reopen this.

**Comment by tacaswell** [comment]
I suspect that this is actually a font selection problem, https://matplotlib.org/tutorials/text/text_props.html?highlight=han#text-with-non-latin-glyphs may be useful.

https://matplotlib.org/users/dflt_style_changes.html#normal-text
