### ISSUE TITLE
set_facecolor doesn't work for PatchCollection if set_array is called first

### ISSUE THREAD

**Issue by Joshuaalbert** [matplotlib/matplotlib#15397]
### Bug report

**Bug summary**

Calling `set_color` on `PatchCollection` will not set face colours if `set_array` was called before. Edge colours will be set.

**Code for reproduction**

```python
from matplotlib.patches import Circle
from matplotlib.collections import PatchCollection
import pylab as plt

coll = PatchCollection([Circle((0.25,0.5), 0.3), Circle((0.75, 0.5), 0.3)])
c = [(1,0,0,0.5),
    (1,1,0,0.5)]
coll.set_facecolor(c)
ax = plt.subplot()
ax.add_collection(coll)
plt.show()

# Try set_array first then 
coll = PatchCollection([Circle((0.25,0.5), 0.3), Circle((0.75, 0.5), 0.3)], cmap=plt.cm.bone)
coll.set_array(np.array([0.5, 0.5])) # comment to give expected behaviour
c = [(1,0,0,0.5),
    (1,1,0,0.5)]
coll.set_facecolor(c)
ax = plt.subplot()
ax.add_collection(coll)
plt.show()
```

**Actual outcome**

![Screenshot from 2019-10-09 11-15-23](https://user-images.githubusercontent.com/14807032/66468254-23e15d00-ea86-11e9-8b56-2603d016cbb3.png)

**Expected outcome**

![Screenshot from 2019-10-09 11-17-27](https://user-images.githubusercontent.com/14807032/66468437-6d31ac80-ea86-11e9-8d3c-ba67987a5fff.png)

**Matplotlib version**
  * Operating system: linux
  * Matplotlib version: 3.0.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.6.2

Python was installed from conda default channel, then all other packages are from pip.

**Comment by ImportanceOfBeingErnest** [comment]
The coloring via colormapping and via facecolor are mutually exclusive. If you want to use `set_facecolor` you need to make sure to remove the array for colormapping first. 

    coll.set_array(None)

**Comment by Joshuaalbert** [comment]
Okay, then I guess it's not an issue, but a caveat.
