### ISSUE TITLE
Imshow does not show true colors

### ISSUE THREAD

**Issue by jecs89** [matplotlib/matplotlib#15395]
The problem is related to the internal scaling of imshow.
For example:
mat1 = [ 0, 10, 15, 20 ]
mat2 = [ 0, 100, 150, 200 ]
If I use the imshow function with cmap ='gray' to show mat1 and mat2, they are going to have the same visualization because there is an internal scaling but the visualization is not showing the true colors. How can I turn off this internal scaling or what solutions do you propose?

**Comment by jklymak** [comment]
Thanks for your interest in matplotlib.  This sort of user-help is best discussed at stackoverflow or https://discourse.matplotlib.org, but in this case you want to specify `vmin` and `vmax` to `imshow`: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib-axes-axes-imshow  I'm going to close, as this isn't a bug.
