### ISSUE TITLE
Inaccurate ellipse drawing

### ISSUE THREAD

**Issue by darjusp** [matplotlib/matplotlib#15402]
### Bug report

**Bug summary**
Ellipse drawing looks inaccurate, matplotlib draws it smaller than supposed to be 

**Code for reproduction**

```python
# Draws ellipse and few points for validation
# Points calculated mathematically to show that one should be inside and one close to the edge
ells = Ellipse((20, 60), 2, 5, 0,  edgecolor='black', facecolor='none')
plt.figure(figsize=(10,10))
a = plt.subplot(111, aspect='equal')
a.add_patch(ells)
plt.scatter([18.5,17.8], [60,60], alpha=0.5)
plt.xlim(np.min(20)*0.88,np.max(20)*1.07)
plt.ylim(np.min(60)*0.95,np.max(60)*1.05)
print((18.5-20)**2/4 + (60-60)**2/25)
print((17.8-20)**2/4 + (60-60)**2/25)
plt.show()
#
```

**Actual outcome**

![screen](https://user-images.githubusercontent.com/10597360/66585830-3ba50800-eb90-11e9-802f-1fcd20eca0ff.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

There should be the real edges of the plot https://www.desmos.com/calculator/kvwwht3kex
Mathematics of the point looks correct according to the graph in desmos
**Matplotlib version**

  * Operating system: Mac OSx 10.11
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.2
  * Jupyter version (if applicable): 5.6.0
  * Other libraries: 

 pip install matplotlib

**Comment by jklymak** [comment]
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.patches.Ellipse.html

**Comment by darjusp** [comment]
Yes that solved the thing, thanks for pointing it out
