### ISSUE TITLE
ImportError: cannot import name 'rcParams' from 'matplotlib' (unknown location)

### ISSUE THREAD

**Issue by Escanor2019** [matplotlib/matplotlib#15407]
i am get this error:

`ImportError: cannot import name 'rcParams' from 'matplotlib' (unknown location)`

**full code error**: http://prntscr.com/pi5hui

i try uninstall matplotlib in pip and install in anaconda powershell, and also run jupyter notebook in anaconda powershell

pip and anaconda, 64 bits all softwares.

python37-64bits
Anaconda3-2019.07-Windows-x86_64.exe
pip -V: pip 19.2.3 from C:\ProgramData\Miniconda3\lib\site-packages\pip (python 3.7)

**Comment by tacaswell** [comment]
This is likely due to conflicting installations.

I suggest you create a post at https://discourse.matplotlib.org/c/community/install for more help on this.  Please copy-paste the traceback rather than posting a link to a screenshot.
