### ISSUE TITLE
Rectangle's xy parameter is wrongly explained

### ISSUE THREAD

**Issue by iwmq** [matplotlib/matplotlib#15401]
matplotlib.patches.Rectangle's first parameter, xy, is the combination of left and top coordinates, but the documentation and source code comment explain it as the bottom and left rectangle coordinates.

**Comment by ImportanceOfBeingErnest** [comment]
The direction of the vertical axis goes from bottom to top. Hence the `xy` parameter denotes the bottom left corner of the rectangle.  
If this is unclear, maybe showing an example would help us understand where the misunderstanding comes from.

**Comment by iwmq** [comment]
@jklymak Thank you first.
It turns out that this confusion results from the difference between data plotting (plt.plot and the like) and image display (plt.imshow). Bellow is what I observed.

For plt.imshow(), my code is:
`import numpy as np
import matplotlib.pyplot as plt
from mxnet import image

img = image.imread("./data/dog.jpg").asnumpy()
fig, axes = plt.subplots(1, 1)
axes.imshow(img)
axes.add_patch(plt.Rectangle(xy=(200, 120), width=250, height=190,
                             fill=False, edgecolor='red', linewidth=3))
plt.savefig("./data/dog_boxed.jpg")`

And I got:
![dog_boxed](https://user-images.githubusercontent.com/19398624/66616172-4c8e6180-ec02-11e9-9ed8-33f93fdc40e2.jpg)

For plt.plot():
`x = np.linspace(0.0, 600.0, 1000)
y = 0.65 * x + 10.0

fig, axes = plt.subplots(1, 1)
axes.plot(x, y)
axes.add_patch(plt.Rectangle(xy=(100, 200), width=250, height=120,
                             fill=False, edgecolor='red', linewidth=3))
plt.savefig("./data/linear_boxed.png")`
And I got:
![linear_boxed](https://user-images.githubusercontent.com/19398624/66616230-7e072d00-ec02-11e9-8d8e-3fd30befad4d.png)

The two coordinate systems are different. For plt.plot(), matplotlib.patches.Rectangle's xy parameter is exactly right. However, for plt.imshow(), the vertical aixs is inverted.
So may some comments be added to the API reference to address this confusion?

Thanks again.

**Comment by timhoffm** [comment]
Please check the *origin* and *extent* parameters in the `imshow()` docs:
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.imshow.html#matplotlib.pyplot.imshow

and this extended explanation:
https://matplotlib.org/tutorials/intermediate/imshow_extent.html#sphx-glr-tutorials-intermediate-imshow-extent-py

If you have ideas how to improve the docs, we are more than happy to include them.

**Comment by jklymak** [comment]
We could not use the phrase “bottom left” and instead say “minimum coordinate”.

**Comment by iwmq** [comment]
Thanks everyone. As @jklymak said, alternative phrase is better, like "minimum coordinate" or "starting coordinate" which may eliminate the confusion.

**Comment by jklymak** [comment]
@iwmq any interest in trying to fix it yourself by opening a Pull Request?  Its a bit daunting, but relatively straight-forward after a bit of set up: https://matplotlib.org/devel/index.html

**Comment by iwmq** [comment]
Thank you for your advice @jklymak . I would like to open a pull request. Since it is my first PR, it will take some time. Good day everyone.
