### ISSUE TITLE
plt.hist not properly plotting the specified color for histogram

### ISSUE THREAD

**Issue by jsl1994** [matplotlib/matplotlib#15415]
### Bug report

When plotting a discrete variable using plt.hist, the intended color is not properly displaying. Either I get a histogram where the top half of a bar is green and the bottom half is blue, or the bar is entirely blue (despite explicitly specifying the color to be green). The bug seems to occur when I add certain extra arguments to the plt.hist function (particularly density and weights)

**Code for reproduction**

```python
import numpy as np
import matplotlib
print "Matplotlib version: ", matplotlib.__version__
import platform
print "Python version: ", platform.python_version()
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

NumSamples = 10000

def orig():
    return np.random.binomial(10,0.75)

origSamples = [orig() for x in range(NumSamples)]

plt.subplot(2,2,1)
weights = np.ones_like(origSamples)/float(len(origSamples))
#n, bins, patches = plt.hist(color="g",x=origSamples, bins=20,alpha=0.7,label="Original")	#works fine (correctly colored)
#n, bins, patches = plt.hist(color="g",x=origSamples, bins=20,alpha=0.7,density=True,label="Original")	#BUG (half green half blue)
#n, bins, patches = plt.hist(color="g",x=origSamples, bins=20, alpha=0.7,weights=weights,density=True,label="Original")	#BUG (still half green half blue)
n, bins, patches = plt.hist(color="g",x=origSamples, bins=20, alpha=0.7,weights=weights,label="Original")	#turns to blue even though color='g'
#n, bins, patches = plt.hist(color="g",x=origSamples, bins=20,density=True)	#bug (half green half blue)

plt.xlabel('Outcomes')
plt.ylabel('Probability Mass')
plt.title('Binomial Distribution')

freq = n/np.sum(n)
plt.bar(bins[:-1], freq, align="edge", width=np.diff(bins))
plt.grid(axis='y', alpha=0.75)

plt.show()

```

**Actual outcome**
![all_blue](https://user-images.githubusercontent.com/34314292/66725798-ba9d7900-edfa-11e9-80ac-3ad93c753db1.png)
![HalfColored](https://user-images.githubusercontent.com/34314292/66725802-c0935a00-edfa-11e9-9c9e-33afbb882002.png)

These are the outputs obtained when running with some of the other commented out lines (I included both errors in the same snippet)

**Expected outcome**
Both plots should be entirely green

**Matplotlib version**

  * Operating system: Ubuntu 16.04.6 LTS "Xenial"
  * Matplotlib version: 2.2.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.12
  * Jupyter version (if applicable): Not applicable
  * Other libraries: Numpy: 1.16.2

I installed matplotlib with pip

**Comment by ImportanceOfBeingErnest** [comment]
You create a blue bar plot via `plt.bar(..)`. Remove it if you don't want it to be there.

**Comment by jklymak** [comment]
Can you clarify this?  It’s pretty hard to tell what if your code works and what doesn’t.  Right now you call plt.hist and plt.bar in the same axes; maybe one is over plotting the other?

**Comment by jklymak** [comment]
I’m going to close this but feel free to clarify and we can reopen if there really is a bug.
