### ISSUE TITLE
Incorrect color in case of unique value

### ISSUE THREAD

**Issue by kerooksblog** [matplotlib/matplotlib#15419]
### Bug report

**Bug summary**

I'm plotting some shapefiles on which I'm working with geopandas and it looks like that the colour used in the plot, in case of an unique value, is not showed correctly in the legend. 

[Here](https://github.com/matplotlib/matplotlib/files/3725844/test.zip) the zipped shp created for the test

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import geopandas as geo

test = geo.read_file("./test.shp") 

fig = plt.figure()
fig.set_size_inches(25, 20)

ax1=plt.subplot(331) # in w2 some values are '0', some '0.3'
test.plot(ax=ax1,column='w2',legend=True, cmap='tab20b')
plt.title('w2')

ax2=plt.subplot(332) # in wl values are only '0'
test.plot(ax=ax2,column='wl',legend=True, cmap='tab20b')
plt.title('wl')

ax3=plt.subplot(333) # in wl values are only '0.8'
test.plot(ax=ax3,column='w3',legend=True, cmap='tab20b')
plt.title('w3')

plt.show()
```

**Actual outcome**

![test_actual](https://user-images.githubusercontent.com/17175539/66777087-521ccd80-eec8-11e9-939b-af29ff6bc958.png)

**Expected outcome**

![test_expected](https://user-images.githubusercontent.com/17175539/66777100-5a750880-eec8-11e9-97f8-ea7fbdeb52a9.png)

**Matplotlib version**

  * Operating system: Linux, Fedora 30
  * Matplotlib version: 3.1.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: Python 3.7.4
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: geopandas 0.5.1

**Comment by ImportanceOfBeingErnest** [comment]
It's hard for us to judge in how far this is expected or not. However, generally, geopandas issues should of course be handled according to the options listed [on the geopandas site](https://geopandas.readthedocs.io/en/latest/#get-in-touch) - item *Get in touch*.

**Comment by kerooksblog** [comment]
@ImportanceOfBeingErnest I see, I've thought on a matlibplot issue since it was related with the data plot and legend in the particular case of having an unique value, while I didn't find out issue in the statistical analysis of the data. Sorry for the confusion.

**Comment by ImportanceOfBeingErnest** [comment]
If you were using matplotlib, you would need to set `vmin`/`vmax`. This might be the same for the geopandas plotting method, or maybe one would expect that method to analyse the whole frame to find vmin/vmax automatically - that would need to be discussed with geopandas developpers.

**Comment by tacaswell** [comment]
Thanks for reporting this @kerooksblog (the github UI tells me that this is your first issue opened on github so I am going to assume you are new to the community (sorry if I am assuming wrong)).  If you find problems with open source software it is definitely correct to report bugs!

However, as @ImportanceOfBeingErnest said, the code in `test.plot` comes from geopandas (which uses Matplotlib as a dependency).  It is possible this is exposing a bug in Matplotlib, but that depends on what geopandas is doing hence the bug should be reported to them.

Good luck!

As a side note, code to generate simulated data is better than a zip file of simulated data.

**Comment by kerooksblog** [comment]
Thanks @ImportanceOfBeingErnest and @tacaswell for your kind explanation and sorry again! I'll report this to geopandas developers right now.
