### ISSUE TITLE
twiny with sharedx + twiny is very slow

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#15412]
### Issues with sharedx

**Bug summary**

1)  `twiny` (`tiwinx` I did not test, but I assume would be similar) is rather slow, even for small datasets it slows down interactive use noticeably byond reason.

2) It would be great to also have built-in sharing of twin axes as well.  It seems a reasonable use case, e.g., I often want to look at two data sets with same twinx and be able to zoom in concurrently to same location in both subplots.

**Code for reproduction**

1)
The following works reasonably fast

```python
import matplotlib.pylab as plt

def demo():
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    ax2 = fig.add_subplot(212, sharex = ax1)

    # some data
    ax1.plot([1,2,3],[1,3,2])
    ax2.plot([1,2,3],[3,1,2])

    # get rid of overlapping axes labels
    fig.tight_layout()
```

but the following runs noticeably less smooth

```python
import matplotlib.pylab as plt

def demo():
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    ax1b = ax1.twiny()

    # some data
    ax1.plot([1,2,3],[1,3,2])
    ax1b.plot([1,2,3],[1,4,3], color='r')

    # get rid of overlapping axes labels
    fig.tight_layout()
```
2) I found an online post suggesting how to add shared `twinx`/`twiny`

[How to share secondary y-axis between subplots in matplotlib](https://stackoverflow.com/questions/12919230/how-to-share-secondary-y-axis-between-subplots-in-matplotlib)

With some modifications I can get this to work

```python
import matplotlib.pylab as plt

def demo():
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    ax1b = ax1.twiny()
    ax2 = fig.add_subplot(212, sharex = ax1)
    ax2b = ax2.twiny()

    # set mutually axes sharing
    ax1.get_shared_x_axes().join(ax1, ax2b)
    ax2.get_shared_x_axes().join(ax1, ax1b)

    # some data
    ax1.plot([1,2,3],[1,3,2])
    ax1b.plot([1,2,3],[1,4,3], color='r')
    ax2.plot([1,2,3],[3,1,2])
    ax2b.plot([1,2,3],[1,5,4], color='r')

    # get rid of overlapping axes labels
    fig.tight_layout()
```

but it is now extremely slow.

**Feature request**
It would probably better to have a keyword to axes creation to also share twin axes, such as `sharedtwiny=ax1b`.   One would then need to return the second axes of that plot as well.

So the desired code would look like this
```python3
# desired code (not working now)
import matplotlib.pylab as plt

def demo():
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    ax1b = ax1.twiny()
    ax2, ax2b = fig.add_subplot(212, sharex = ax1, sharedtwiny=ax1b)
    
    # some data
    ax1.plot([1,2,3],[1,3,2])
    ax1b.plot([1,2,3],[1,4,3], color='r')
    ax2.plot([1,2,3],[3,1,2])
    ax2b.plot([1,2,3],[1,5,4], color='r')

    # get rid of overlapping axes labels
    fig.tight_layout()
```

Maybe there would be tricks to help with speed that way?

I think it did not use to be all that slow in the past.

**'Bug'**
Without the sharing, if you zoom in one window, the shared axis will be adjusted but not the town axis in the other plot, and vice verse, whereas when you some in the plot with the twin axis, both are adjusted.  I think that this would not usually be the desired outcome.

You can try this:

```python
import matplotlib.pylab as plt

def demo():
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    ax1b = ax1.twiny()
    ax2 = fig.add_subplot(212, sharex = ax1)
    ax2b = ax2.twiny()

    # some data
    ax1.plot([1,2,3],[1,3,2])
    ax1b.plot([1,2,3],[1,4,3], color='r')
    ax2.plot([1,2,3],[3,1,2])
    ax2b.plot([1,2,3],[1,5,4], color='r')

    # get rid of overlapping axes labels
    fig.tight_layout()
```

**Matplotlib version**

  * Operating system: Fedora 30
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.0rc1
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Matplotlib installed using pip on locally-built python.

**Comment by QuLogic** [comment]
I'm not sure what you mean by slow. Is this still a problem with the latest version? Can you post a video or something?

**Comment by timhoffm** [comment]
I'm closing for lack of feedback. We'll reopen if somebody can give additional context.

**Comment by 2sn** [comment]
Well, I am now using 

* Operating system: Fedora 34
* Matplotlib version: 3.4.1
* Matplotlib backend (print(matplotlib.get_backend())): Qt5Agg
* Python version: 3.9.4

and it is still quite slow in interactive compare to a regular line plot with no share axes.  

(just closing the issue did not make it go away; I would have hoped severe performance issues are of interest to the Matplotlib developers)

**Comment by jklymak** [comment]
Performance is very important.  But we need something actionable, reproducible, and easy to follow.  You might also check your rcParams and if there is something in there that may be causing you grief.  As @QuLogic suggested you would also be helping us significantly if you included a movie or animated gif.

**Comment by 2sn** [comment]
@jklymak In my case I use this for a more complicated plot, rendering interactive mode almost unusable.

As it happens for interactive zooming into the figure, I would not know how will to capture this in an animation unless you render/capture in 60 fps, but can't be done within matplotlib.

In any case, just try the example, zoom in/out using the 'pan' tool, and you will most likely immediately see the difference compared to a simple `plot([0,3,2])` example where things go really smoothly - hence I think `rcParams` would unlikely be the reason, to me it seems to be narrowed down to the twin + shared axes.

**Comment by jklymak** [comment]
I did 

```python
import matplotlib.pylab as plt
import numpy as np

fig = plt.figure()
ax1 = fig.add_subplot(211)
ax1b = ax1.twiny()
ax2 = fig.add_subplot(212, sharex = ax1)
ax2b = ax2.twiny()

# set mutually axes sharing
ax1.get_shared_x_axes().join(ax1, ax2b)
ax2.get_shared_x_axes().join(ax1, ax1b)

# some data
ax1.plot(np.random.randn(10000))
ax1b.plot(np.random.randn(10000), color='r')
ax2.plot(np.random.randn(10000))
ax2b.plot(np.random.randn(10000), color='r')

ax2.set_xlim(3000, 4000)

plt.show()
```

with Qt5Agg, v3.4.1, on my 2014 3.5 GHz iMac Quad-Core Intel Core i5.  Panned around, it didn't seem any faster, with or without, the sharing, and not noticeably slower than if I turn sharing off.  OTOH, I'm not using a scroll wheel or something and expecting things to scroll by so fast I can't see them:

## sharing on

https://user-images.githubusercontent.com/1562854/116835870-2ed47480-ab79-11eb-8ed6-c39743bdf5c7.mov

## sharing off

if anything this was laggier:

https://user-images.githubusercontent.com/1562854/116836003-cfc32f80-ab79-11eb-9420-260f32b5ccf1.mov

**Comment by jklymak** [comment]
> I would not know how will to capture this in an animation unless you render/capture in 60 fps, but can't be done within matplotlib.

I'm also not sure what you mean here.  Most operating systems have screen capture software included (ie. for Fedora: https://fedoraproject.org/wiki/ScreenCasting?)

**Comment by jklymak** [comment]
I'll close for lack of reproducibility.
