### ISSUE TITLE
overlap many bars in ax.bar is very slow!!!

### ISSUE THREAD

**Issue by sbelharbi** [matplotlib/matplotlib#15411]
hi,
any idea why this code is getting slower and slower when overlapping many bars?
`ax.plot()` is fine. it keeps the same fast plot. but `ax.bar` gets slower.
any idea how to speed it up? i have more than `1000` bars to draw. need to go fast.
thanks

### Bug report

**Bug summary**

**Code for reproduction**

```python
import datetime as dt

import matplotlib.pyplot as plt
import numpy as np

fg = plt.figure()
ax = fg.add_subplot(111)
nbr = 1000
d = 20
alpha = 0.2
x = np.random.rand(nbr, d)
for i in range(1000):
    tx = dt.datetime.now()
    ax.bar(x=np.arange(d), height=x[i, :],
           align="center",  width=0.98, alpha=alpha, color="blue")
    print("{}/{} in {}".format(i, nbr, dt.datetime.now() - tx))
```

**Actual outcome**

```
0/1000 in 0:00:00.013769
1/1000 in 0:00:00.013218
2/1000 in 0:00:00.013270
3/1000 in 0:00:00.013327
4/1000 in 0:00:00.013285
.....
718/1000 in 0:00:00.808473
719/1000 in 0:00:00.793444
720/1000 in 0:00:00.793674
721/1000 in 0:00:00.779146
.... it is getting slower and slower ...
892/1000 in 0:00:01.220902
893/1000 in 0:00:01.214336
894/1000 in 0:00:01.221586
895/1000 in 0:00:01.246888
....
996/1000 in 0:00:01.521590
997/1000 in 0:00:01.523176
998/1000 in 0:00:01.529786
999/1000 in 0:00:01.532116
```

**Expected outcome**
The plotting goes fast and does not slow because of the overlapping.

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://backend_interagg`
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Thanks for the report.  This seems more suited to discourse.matplotlib.org.

**Comment by sbelharbi** [comment]
either i am  doing something wrong, or it is a limitation/bug.
but, here is an extremely fast and seems overlapping-independent alternative that does the same thing, but no bars. it can  fill the area between two curves. it is `matplotlib.axes.Axes.fill_between` ([doc](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.fill_between.html#matplotlib.axes.Axes.fill_between)).

there is slight increase of time...

```python
import datetime as dt

import matplotlib.pyplot as plt
import numpy as np

fg = plt.figure()
ax = fg.add_subplot(111)
nbr = 1000
d = 20
alpha = 0.2
x = np.random.rand(nbr, d)
tcks = np.arange(d)
for i in range(1000):
    tx = dt.datetime.now()
    ax.fill_between(tcks, x[i, :].min(), x[i, :], facecolor='blue', alpha=alpha)
    print("{}/{} in {}".format(i, nbr, dt.datetime.now() - tx))
```

output:
```bash
0/1000 in 0:00:00.001045
1/1000 in 0:00:00.000812
2/1000 in 0:00:00.000814
3/1000 in 0:00:00.001199
4/1000 in 0:00:00.000805
5/1000 in 0:00:00.000808
....
995/1000 in 0:00:00.001145
996/1000 in 0:00:00.001187
997/1000 in 0:00:00.001229
998/1000 in 0:00:00.001128
999/1000 in 0:00:00.001112
```

**Comment by sbelharbi** [comment]
@jklymak  sorry i did not see your comment.

**Comment by jklymak** [comment]
Not to say this doesn’t have an issue in it, but let’s discuss more before opening a focussed ticket
