### ISSUE TITLE
Plotting with C API, call to plt::show has failed

### ISSUE THREAD

**Issue by 02yogesh16** [matplotlib/matplotlib#15421]
I am trying use python for plotting data generated in c++ using a C API, I am using this package for that: https://github.com/lava/matplotlib-cpp

I have removed all other issues but now I am stuck with one last issue which is; I am getting an exception saying that call to show has failed while doing plt::show(). 

c++ code is working perfectly without plotting:

plt::plot(time, nav_pos, "o");
plt::show();

Lool at the attached file for the error.
![error3](https://user-images.githubusercontent.com/11498835/66809985-01e74f00-ef4c-11e9-9106-6b66821a872d.PNG)

**Comment by anntzer** [comment]
You should report this on matplotlib-cpp's issue tracker -- it is an independent project and afaik none of the matplotlib core devs is involved in it.
