### ISSUE TITLE
Wrong __version__numpy__

### ISSUE THREAD

**Issue by torquil** [matplotlib/matplotlib#1542]
When I install matplotlib using "python build setup.py" and "python install --prefix=...", one of the first lines of output in both cases is:

numpy: 1.6.2

I also have numpy 1.4 (system-wide, I am not root) and numpy 1.6.2 (home folder) installed but it is the 1.6.2 version that is used by python since I have adjusted PYTHONPATH:

$ python

> > > import numpy
> > > numpy.**version**
> > > '1.6.2'

This is the numpy version that I want to use. However, after installing matplotlib 1.2.0, I get

$ python

> > > import matplotlib
> > > matplotlib.**version**
> > > '1.2.0'
> > > matplotlib.**version__numpy**
> > > '1.4.0'

Why is matplotlib not using my numpy 1.6.2, when python itself is using it, and matplotlib detected numpy 1.6.2 during the build and install?

**Comment by michaelaye** [comment]
That confused me as well today.
