### ISSUE TITLE
the python script in Catalina dock icon display wrong

### ISSUE THREAD

**Issue by DukeHouse** [matplotlib/matplotlib#15446]
the new icon is a blur icon,it is not clear anymore

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/pull/14930 for work on fixing this.

**Comment by DukeHouse** [comment]
thanks for your advice!All fine!

**Comment by dstansby** [comment]
I'm going to close this in favour of https://github.com/matplotlib/matplotlib/issues/14850
