### ISSUE TITLE
Hexbin: ticks of logarithmic colorbar can not be removed with set_ticks([])

### ISSUE THREAD

**Issue by a-seyler** [matplotlib/matplotlib#15459]
### Bug report

**Bug summary**

In a hexbin plot with logarithmic bins the ticks of the colorbar are not removed with cb.set_ticks([]) and remain visible. The tick labels, however, vanish. 

**Code for reproduction**

This example code originates from the hexbin demo (https://matplotlib.org/2.0.2/examples/pylab_examples/hexbin_demo.html), slightly altered by adding the  cb.set_ticks([]) lines:

```python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors

np.random.seed(0)
n = 100000
x = np.random.standard_normal(n)
y = 2.0 + 3.0 * x + 4.0 * np.random.standard_normal(n)
xmin = x.min()
xmax = x.max()
ymin = y.min()
ymax = y.max()

fig, axs = plt.subplots(ncols=2, sharey=True, figsize=(7, 4))
fig.subplots_adjust(hspace=0.5, left=0.07, right=0.93)
ax = axs[0]
hb = ax.hexbin(x, y, gridsize=50, cmap='inferno')
ax.axis([xmin, xmax, ymin, ymax])
ax.set_title("Hexagon binning")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('counts')
cb.set_ticks([])

ax = axs[1]
hb = ax.hexbin(x, y, gridsize=50, bins='log', cmap='inferno')

ax.axis([xmin, xmax, ymin, ymax])
ax.set_title("With a log color scale")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('log10(N)')
cb.set_ticks([])

plt.show()

```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/13469413/67210243-09f63180-f419-11e9-8f6b-8d42c8f56ce5.png)

**Expected outcome**

The colorbar ticks in the right subplot panel (logarithmic hexbin) should vanish just like the ones in the left panel. 

**Matplotlib version**

  * Operating system:  Ubuntu 18.04.3 LTS
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3
  * Jupyter version (if applicable): IPython 7.8.0 Console in Spyder IDE
  * Other libraries: 

Matplotlib installed via conda (default channel).

**Comment by jklymak** [comment]
You need to remove the minor ticks as well.

**Comment by a-seyler** [comment]
> You need to remove the minor ticks as well.

With cb.minorticks_off() ? This works, thank you! 

For me, the question remains why this is implemented in this particular way. Is there any use case, where someone wants to remove just the major ticks from a (logarithmic) colorbar and keep the minor ticks?

**Comment by jklymak** [comment]
`set_ticks` is not really meant to remove all the ticks, its usually meant to set the ticks to some desired value.  Its relatively rare that someone doesn't want any ticks on their colorbar.

**Comment by timhoffm** [comment]
`cb.ax.tick_params(which='both', right=False, labelright=False)` would be a consistent way to achieve this.
