### ISSUE TITLE
about animation of quiver vector arrows (mathematical vectors)

### ISSUE THREAD

**Issue by pablo3p** [matplotlib/matplotlib#15469]
Hi there,

I am trying to find out if it is possible to add vectors based off of quiver in matplotlib and animate this via matplotlib animation.
I was able to use quiver to create static graphs of vector addtion.

I am trying to duplicate the animation style here from this link:
https://www.physics.mun.ca/~jjerrett/vector/vector.html

But i saw on stackoverflow that at one point it was not possible to position vectors
then they said it can, see this link:
https://stackoverflow.com/questions/17758942/is-it-possible-to-update-matplotlib-quiver-position-coordinates-in-an-animation?rq=1

---------------------------------------------------------
So to explain details of my program, it asks user to input 2 vectors.
Then the 2 vectors, the tails, are placed at the origin.
Then need to move one of the vector tails to the tip of the other vector in order to do vector addition.
And then draw arrow from origin to the final point.
-------------------------------------------------------------
Hope you can let me know.

P.

**Comment by jklymak** [comment]
Thanks for you interest in matplotlib.  This seems better suited to discussion over at discourse.matplotlib.org.  I’m going to close as this is not really an issue, but if you isolate an issue feel free to open a new request.  Thanks!

**Comment by pablo3p** [comment]
Hi there, i was not aware of this discussion section  'discourse.matplotlib.org'. I will post this question there.
Thanks for your reply, really appreciate it.
P.
