### ISSUE TITLE
pyplot.step function that continues beyond last point

### ISSUE THREAD

**Issue by mbakker7** [matplotlib/matplotlib#15475]
### Bug report

The pyplot.step function documentation states for the option `where=post`:

'post': The y value is continued constantly to the right from every x position, i.e. the interval [x[i], x[i+1]) has the value y[i].

What I understood from that (and what I want) is that the last value of y is continued constantly after the last value of x (like `axhline`, but then starting at the last value of y and extending to the right). Can that be implemented as an option?

**Code for reproduction**

     plt.step([0, 1, 2, 3], [0, 4, 2, 3], where='post')
     plt.xlim(0, 5)

**Actual outcome**

Step function ends at x=3, y=3, but I want to contiue to x=5, y=3 (the limit of the axis)

**Comment by timhoffm** [comment]
This is a wording issue. Horizontal segments are only drawn between the points.
That is also the only reasonable way to implement it. In general (unevenly distributed x values), there is now canonical way for the length of a segment beyond the last data point.

**Comment by mbakker7** [comment]
I agree that the wording can be improved a bit. But the gist of my question is whether the option I suggest is a possibility to implement. Maybe an additional keyword `extend` that can be `left`, `right` or `both`?

**Comment by timhoffm** [comment]
As said above, there is no good general way to determine how far that should stretch out.
I propose to pad the input data instead for such a use case.

**Comment by janosh** [comment]
> As said above, there is no good general way to determine how far that should stretch out.

Isn't there? Wouldn't extending to the edges of the plot be the expected default here?

**Comment by jklymak** [comment]
The artist doesn't know where the edge of the plot is.

**Comment by timhoffm** [comment]
> Wouldn't extending to the edges of the plot be the expected default here?

No, this is an assumption on the data. One common case for `step` would be a histogram-like plot, in which case the extent should be the same as "the other step lengths".
