### ISSUE TITLE
Secondary axis not available

### ISSUE THREAD

**Issue by johncwok** [matplotlib/matplotlib#15492]
I am trying to reproduce the tutorial on how to add a secondary axis to a plot, which can be found here : https://matplotlib.org/3.1.0/gallery/subplots_axes_and_figures/secondary_axis.html

unfortunately when I try it, the following line 
```Python
secax = ax1.secondary_xaxis('top', functions=(forward, inverse))
```
Throws the error : 
```Python
AttributeError: 'AxesSubplot' object has no attribute 'secondary_xaxis'
```
Is this a known issue ? I couldn't find anything online.

**Comment by ImportanceOfBeingErnest** [comment]
Check your matplotlib version (`print(matplotlib.__version__)`). Presumably you are using 3.0 or lower, which does not yet have this new feature?

**Comment by johncwok** [comment]
you are right, my version is 3.0.3 ! in the mean time i found a workaround
