### ISSUE TITLE
retrieve marker info from scatter obj

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#15496]
I have a `scatter` object like
```python
import numpy as np
import matplotlib.pyplot as plt

n = 10
x = np.random.rand(n)
y = np.random.rand(n)

obj = plt.scatter(x, y, s=100, c='black', marker='+')
```
and I'd now like to retrieve information about the marker from that object (cf. https://github.com/nschloe/tikzplotlib/issues/324).

Line2D objects have [`get_marker*`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.get_marker), scatter PathCollections don't.

Any hints?

**Comment by ImportanceOfBeingErnest** [comment]
I think a similar request was already posted in https://github.com/matplotlib/matplotlib/issues/4672

**Comment by nschloe** [comment]
Absolutely, let's close as duplicate.
