### ISSUE TITLE
bar3d: plotted bars overlap incorrectly

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#155]
[Original report at SourceForge, opened Thu Dec 31 13:32:15 2009](https://sourceforge.net/tracker/?func=detail&aid=2924256&group_id=80706&atid=560720)

For bar3d(), overlapping for the bars can be wrong from certain views. Attached is an example of the problem using hist3d_demo.py
### SourceForge History
- On Thu Jun  3 15:28:02 2010, by efiring: assigned_to: 100
- On Thu Dec 31 13:32:15 2009, by nhmc: File Added: 357273: hist3d_bug.png

**Comment by timhoffm** [comment]
See also #13580.
