### ISSUE TITLE
FixedFormatter somewhat broken

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#15501]
### Bug report

I don't understand neither why the minor nor the major ticks are like they are in this example:

https://matplotlib.org/devdocs/gallery/ticks_and_spines/tick-formatters.html

- For major ticks, I would have expected no label on the first tick, '1' on the second and so on.
  But the '1' is already on the first tick.
- I have absolutely no idea where the minor ticks come from.

**Comment by QuLogic** [comment]
This is essentially #7122.
