### ISSUE TITLE
Relevant methods are only documented in base classes and thus not easily discoverable

### ISSUE THREAD

**Issue by PDiracDelta** [matplotlib/matplotlib#15514]
Out of date documentation in subplot2grid explanation in 'Notes':
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.subplot2grid.html
It says:

> The following call
> ```
> subplot2grid(shape, loc, rowspan=1, colspan=1)
> ```
> is identical to
> ```
> gridspec=GridSpec(shape[0], shape[1])
> subplotspec=gridspec.new_subplotspec(loc, rowspan, colspan)
> subplot(subplotspec)
> ```

However, `gridspec` has no attribute `new_subplotspec`. See https://matplotlib.org/3.0.3/api/gridspec_api.html.

**Comment by jklymak** [comment]
Its a bit burried, but its there.  https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.gridspec.GridSpecBase.html#matplotlib.gridspec.GridSpecBase

Leaving open as I don't think we should have user-level docs in something like `GridSpecBase`.

**Comment by timhoffm** [comment]
Semi-related to https://github.com/matplotlib/matplotlib/issues/15503#issuecomment-546083557 in that documentation may be only available in the base class. And not easily accessible from the derived class.

Unfortunately, there's currently no simple solution.

**Comment by oscargus** [comment]
This is now changed to read as:
```
fig = gcf()
gs = fig.add_gridspec(nrows, ncols)
ax = fig.add_subplot(gs[row:row+rowspan, col:col+colspan])
```
and at least those two methods are easy to find.

Closing this as completed (although I have not figured out when).
