### ISSUE TITLE
Collections could check x- and y- transforms separately to decide whether to autoscale each direction

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#15518]
### Bug report

Consider the following example
```python

from pylab import *
plt.rcdefaults()
fig, ax = plt.subplots()
ax.plot([1, 3], [5, 7])
ax.vlines(x=[1, 2, 3], ymin=0, ymax=1, transform=ax.get_xaxis_transform())
plt.show()
```
where I want to use vlines in a manner similar to axvline, i.e. lines spanning the full axes height (but more efficiently than with repeated calls to axvline, as vlines will create a single LineCollection.

![test](https://user-images.githubusercontent.com/1322974/67589233-3fbc5280-f758-11e9-9472-538beacdb9d6.png)

The autoscaling in the y axis incorrectly goes all the way down to include (0, 1) (coming from the call to vlines), even though these values are in axes coordinates rather than data coordinates.

In effect, I *think* this is equivalent to the suggestion at https://github.com/matplotlib/matplotlib/pull/13642#discussion_r264878170.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master or 3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): any
  * Python version: 37
  * Jupyter version (if applicable): no
  * Other libraries:

**Comment by ksunden** [comment]
Fixed by #25324
