### ISSUE TITLE
antialiased image check seems wrong when used on zoomed image

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#15517]
### Bug report

**Bug summary**

The new antialiased image code appears to not handle zoomed images correctly.

attn @jklymak 

**Code for reproduction**

```python
from pylab import *
plt.rcdefaults()
fig, axs = plt.subplots(1, 2)
axs[0].imshow(np.random.rand(10, 10))  # now defaults to interpolation="antialiased"
axs[1].imshow(np.random.rand(1000, 1000))
axs[1].set(xlim=(-.5, 9.5), ylim=(-.5, 9.5))
plt.show()
```

**Actual outcome**

Run with mpl master (or anything after #13724 was merged).

![test](https://user-images.githubusercontent.com/1322974/67588555-af314280-f756-11e9-9dfd-96cd77dc1a0e.png)

**Expected outcome**

The right image should also be rendered using "nearest" interpolation.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 37
  * Jupyter version (if applicable): no
  * Other libraries:

**Comment by jklymak** [comment]
Fair enough, its because we use the actual data shape, not the visible data shape:
```python
shape = list(data.shape)
```
I'm not quite sure how we can toggle between the two...  I *thought* we had zooming working, but maybe I'm wrong...

**Comment by anntzer** [comment]
Indeed, I somehow remember that we did check zooming, but heh...

**Comment by jklymak** [comment]
The y transform isn't being applied properly.  I'm just doing 
```python
shape = list(data.shape)
dispx, dispy = transform.transform([shape[1], shape[0]])
```
but I'm pretty sure shape[0] is not being transformed correctly to `dispy`

**Comment by jklymak** [comment]
Ooops, I think I fixed it, but need to add this as a test.
