### ISSUE TITLE
Partial residual plots with Pearson correlation coefficient and P-value

### ISSUE THREAD

**Issue by Larry-Lai** [matplotlib/matplotlib#15526]
Hello Matplotlib/Python users

I'm attempting to plot the residual regression plots with Pearson correlation coefficient and P-value in Python.

I've read an article regarding the simple correlation and linear regression: https://towardsdatascience.com/simple-and-multiple-linear-regression-with-python-c9ab422ec29c

What would be the best way to do it in Python?

- Y=Continuous var
- X=Continuous var
- Nuisance covariate=Z (Continuous var)

Thanks for considering my request.

**Matplotlib version**

  * Operating system: Ubutnu 16.0.4
  * Matplotlib version: 3.1.1
  * Python version: 3.7/Anaconda 2019.10 for Linux Installer
 

Best regard
Larry Lai

**Comment by jklymak** [comment]
This sort of user question is best pursued at discourse.matpltolib.org or stackoverflow, not the issue tracker.  Thanks for your understanding!

**Comment by Larry-Lai** [comment]
Thanks for pointing that out.
