### ISSUE TITLE
Cannot install matplotlib 3.1.1

### ISSUE THREAD

**Issue by zomatree** [matplotlib/matplotlib#15520]
### Bug report

Cant install matplotlib 3.1.1

**Actual outcome**

Error: https://mystb.in/ziwarewibo.coffeescript

**Expected outcome**

for it to work

**Matplotlib version**
  * Operating system: windows 10
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.8
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
Matplotlib cannot find freetype (ft2build.h).  You can make Matplotlib download its own copy of freetype by doing `set MPLLOCALFREETYPE=1` at the command line first.

**Comment by tacaswell** [comment]
We don't have wheels up for py38 yet.

@zomatree If you need more help with installing from the sdist on windows please create a topic at https://discourse.matplotlib.org/c/community/install

**Comment by Harmon758** [comment]
There are now wheels for Python 3.8 on PyPI with v3.1.2.
