### ISSUE TITLE
Can't disable plot label for pandas series

### ISSUE THREAD

**Issue by notmatthancock** [matplotlib/matplotlib#15575]
### Bug report

**Bug summary**

When plotting a `pandas.Series`, matplotlib uses the name of the series as the default label for the plot. It is possible to over-ride this default with a different label value, but it is not possible to disable the label by providing `label=None` since it falls back to the series name.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import pandas as pd


x = pd.Series([1, 2], name='The name!')

plt.plot(x, label=None)
plt.legend()
plt.show()
```

**Actual outcome**

Plot has legend with item `The name!` despite passing `label=None`.

**Expected outcome**

Plot has legend with no labels.

**Matplotlib version**

  * Operating system: Ubuntu 18
  * Matplotlib version: 2.2.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt4Agg
  * Python version: 3.6.5

**Comment by notmatthancock** [comment]
Whoops. Apparently this *can* be disabled by passing `label=''` rather than `label=None`. This can be closed if this is the expected way to disable the label in this situation.

**Comment by notmatthancock** [comment]
> Running the original post's code in master does not give a legend, but rather Warning: No handles with labels found to put in legend. I can reproduce the legend creation with matplotlib 2.2.3 though. Maybe this is an "issue" that fixed itself over time?

Perhaps a better example would be the following slight modification:

```python
import matplotlib.pyplot as plt
import pandas as pd


x = pd.Series([1, 2], name='The name!')
y = [1, 2, 3]

plt.plot(x, label=None)
plt.plot(y, label='nice y values')
plt.legend()
plt.show()
```

Here, you'd expect there to be a legend with a single item, `'nice y values'`. But, the actual outcome is that it also shows the first label, despite passing `label=None`.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, so in matplotlib 2.2.3 (and presumably 2.2.4, which you are running), there are two legend items.   
In matplotlib 3.1, as well as in the current development version, there is only a single legend entry.  
So in that sense, this is already "fixed".  
Therefore, one could leave this as is, or, if someone feels strong about it, run a bisect and backport the fix to 2.2.5.

**Comment by notmatthancock** [comment]
> In matplotlib 3.1, as well as in the current development version, there is only a single legend entry.
So in that sense, this is already "fixed".

Thanks; missed that detail.

**Comment by jklymak** [comment]
Given that there is a workaround and 2.2.x is almost at end of life Can we reclose this?

**Comment by ImportanceOfBeingErnest** [comment]
I would say yes. The only other potential issue was that `.set_label(None)` works. But that is similar to other parameters, like `.set_marker(None)` - so if that is considered a problem, it would be part of a different/larger issue.
