### ISSUE TITLE
feature request: set grid behind everything by default

### ISSUE THREAD

**Issue by dominiklenne** [matplotlib/matplotlib#15581]
action:
create plot with border and grid, grid in different color than border.
format grid and border via style sheet.
python 3.7 with IDLE 3.5.1

expected result: 
border is plottet above grid

actual result:
grid is plotted above border, the border line is interrupted with the grid color and linewidth

**Comment by jklymak** [comment]
Can you provide a MWE of the issue you are having?  If I do 
```python
import matplotlib.pyplot as plt

plt.grid('on', color='r')
plt.show()
```

I get the following, which looks fine to me: 

![grid](https://user-images.githubusercontent.com/1562854/67970115-b679a580-fbc7-11e9-8ef1-105ebac9ca24.png)

**Comment by dominiklenne** [comment]
Thx for inquiring!
I attached the py file (plot happens at the end), the plots.mpls style sheet (see grid specifications) and the resulting svg file. If you enlarge this a bit, you see, that the upper and lower border is overwritten by the thin red grid line. Also the horizontal grid lines peek a little bit into the left and right border lines.
see
https://drive.google.com/open?id=1MBlrRPnzgJuZrYVvLT0eY6YnfOy05-gC

**Comment by jklymak** [comment]
Do you get the same thing with other backends?   Maybe this is an issue with svg?

**Comment by jklymak** [comment]
What version of matplotlib?  I cannot reproduce in png, svg, or pdf using:

```python
import matplotlib.pyplot as plt

plt.rcParams['axes.linewidth'] = 2
plt.rcParams['xtick.major.size'] = 4
plt.rcParams['xtick.minor.size'] = 2
plt.rcParams['xtick.major.width'] =  2
plt.rcParams['ytick.major.size'] = 4
plt.rcParams['ytick.minor.size'] = 2
plt.rcParams['ytick.major.width'] =  2
plt.rcParams['grid.color'] = 'red'
plt.rcParams['grid.alpha'] = 1

plt.grid('on', color='r')
plt.savefig('boo.svg')
plt.savefig('boo.pdf')
plt.savefig('boo.png')
```

**Comment by dominiklenne** [comment]
Jody, I must really apologize, I was using an old version.
With some trouble I managed to install the latest miniconda plus couple of packages, and the grid is now neatly behind everything.

**Comment by jklymak** [comment]
No problem, but be sure to specify matplotlib version for future bug reports...
