### ISSUE TITLE
feature request: allow zorder in style sheets

### ISSUE THREAD

**Issue by dominiklenne** [matplotlib/matplotlib#15580]
As far as I have tested, in style sheets any line like

axes.zorder : 1   or
grid.zorder: 2

throws a bad key error.
It would very convenient to make this work.

**Comment by anntzer** [comment]
Can this be closed now that https://github.com/matplotlib/matplotlib/issues/15581 was closed?

**Comment by dominiklenne** [comment]
I'll close it. Think this zorder thingy would be a nice to have, though, but works for me as it is now - thx!!!
