### ISSUE TITLE
Graceful handling of a numpy matrix

### ISSUE THREAD

**Issue by gustavla** [matplotlib/matplotlib#1558]
If you give `quiver` numpy matrices, it will crash. It raises a `ValueError` for a `reshape`, which can be hard to realize was caused by the matrices (potentially to great frustration for the user).

The source of the problem boils down to `ravel()` for `np.matrix` creating a row matrix of shape `(1, N)`, instead of an ndarray with shape `(N,)`.

I naively tried fixing it (pull request: #1546) by throwing in a call to `np.asarray`, but it was rightly closed because it would break support for masked arrays. It was also pointed out that it was likely to be a problem beyond just `quiver`.

As I see it, the issue is either resolved by adding support for `numpy.matrix`, or better information to the users of the source of the error.

**Comment by anntzer** [comment]
The correct way to fix this is probably to figure out each call site of `np.asanyarray` (there's like ~25 of them) to see whether they should be replaced by calls to `np.asarray`.  The trick here is that you probably still want masked arrays to pass through, so perhaps you really need a helper function that behaves like `asarray`, except that masked arrays are passed through.

This helper function should probably(?) then be used in most places where either `asarray` or `asanyarray` is used.

**Comment by dopplershift** [comment]
Instead of only whitelisting masked arrays, it should blacklist matrix. Otherwise, you needlessly preclude other `ndarray` subclasses.

**Comment by efiring** [comment]
On 2016/10/11 9:17 AM, Ryan May wrote:
> Instead of only whitelisting masked arrays, it should blacklist matrix.
> Otherwise, you needlessly preclude other |ndarray| subclasses.

Right.  The matrix subclass is an anomaly that causes more problems than 
it is worth; it alters some of the most fundamental ndarray behavior. 
In most discussions I have seen, the consensus advice is to discourage 
its use.

**Comment by anntzer** [comment]
Agreed, just blacklisting matrix and matrix subclasses seems better.
