### ISSUE TITLE
Blitting and DPI scaling on Windows 10

### ISSUE THREAD

**Issue by onatt** [matplotlib/matplotlib#15587]
### Bug report
Animations with blitting do not display correctly on a computer running Windows 10 in combination with a dpi scaling factor 150% or more.

**Code for reproduction**

Please find below a very simple animation based on FuncAnimation. In order to reproduce the bug, one has to select a scaling factor of 150 % or more in the windows display settings dialog. The problem is correlated with blitting. The same code works correctly for any dpi scaling factor when FuncAnimation is called with the argument `blit=False`.

I already tried different values for the size of the figure (`figsize=...`) and different values for the figure dpi (`dpi=...`) and did not find any correlation with the strange behavior. I was able to reproduce the bug on different computers. So it is likely not correlated with any bug in the graphics driver. 

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.animation


fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.grid()
x = np.linspace(0, 20, 500)
plot, = ax.plot(x, np.sin(x))


def update(n):
    plot.set_ydata(np.cos(x - 0.5 * n))
    return plot,

             
ani = mpl.animation.FuncAnimation(fig, update, blit=True)
plt.show()
```

**Actual outcome**
The following screenshot is acquired with a value of 150% for the dpi scaling. The Axes is cut at the lower and right border.
![150percent](https://user-images.githubusercontent.com/47846440/68040997-d7c5b900-fccf-11e9-8662-43e9ee2ab683.png)

**Expected outcome**

The following screenshot is acquired with a value of 100% for the dpi scaling.
![100percent](https://user-images.githubusercontent.com/47846440/68041016-e2804e00-fccf-11e9-9010-9eaea6bc4331.png)

**Matplotlib version**

  * Operating system: Windows10 (64bit) v. 1903
  * Matplotlib version: 3.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: Python 3.7.4 (Anaconda)

Matplotlib was installed using Anaconda3-2019.10-Windows-x86_64.exe. The problem persists on a completely new installation.

**Comment by timhoffm** [comment]
Does this also happen with other backends, say TkAgg?

**Comment by onatt** [comment]
This does not happen with the TkAgg backend. I also tried Qt4Agg and it shows the same behavior as Qt5Agg.

**Comment by jklymak** [comment]
... right the question is if we are querying the DPI properly from QT, or if QT is not returning it properly.

**Comment by ImportanceOfBeingErnest** [comment]
I ran the code on windows 8.1 with current master and Qt5Agg backend (qt 5.9.7, pyqt 5.9.2) and the result is as expected. 

![image](https://user-images.githubusercontent.com/23121882/68050671-f040ce00-fce5-11e9-8a05-0a020fd99249.png)

However with matplotlib 3.1.1, the result is 

![image](https://user-images.githubusercontent.com/23121882/68050711-0cdd0600-fce6-11e9-91d3-76ab42422db7.png)

So maybe this is fixed already.

**Comment by timhoffm** [comment]
Works for me on 3.1.0 (Win10, 150%, qt 5.9.7, pyqt 5.9.2). This seems to be fixed.

**Comment by ImportanceOfBeingErnest** [comment]
Since that bug has apparently been introduced in 3.1.1, the fact that it works on 3.1.0 isn't really relevant, is it? The question is whether it's fixed on master - which seems to be the case; but I cannot tell for sure because the environments I tested in are sufficiently different.

**Comment by timhoffm** [comment]
Yes works on master as well.
