### ISSUE TITLE
[Feature Request] plt.scatter(<list of numbers>) should work like plt.plot, where the <list> is inferred to indicate y-values

### ISSUE THREAD

**Issue by hmswaffles** [matplotlib/matplotlib#15599]
When making a scatter plot, I often find myself making an x-axis, a la:
`plt.scatter(range(len(data_list)),data_list)`

But on the other hand, `plt.plot(data_list)` does not require an x-axis to necessarily be passed. Instead of having `plt.scatter()` fail if only passed one argument, can we make it so that it assumes that the x-axis starts at zero and increases by 1 for each datapoint in the y-axis list?

**Comment by greglucas** [comment]
What about utilizing the `plot` call instead of `scatter` for this purpose?
```
plt.plot([5, 6, 7], lw=0., marker='o')
```

**Comment by timhoffm** [comment]
I don't think `scatter()` should be usable with a single argument. Already the name suggests that you distribute (x, y) points on the plane.

As @greglucas suggested use `plot` if you want to plot 1D-data vs. their impicit index using markers. In particular.
~~~
plt.plot(data_list, linestyle='none', marker='o')
~~~
or short
~~~
plt.plot(data_list, 'o')
~~~
See the [documentation of plot](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html#matplotlib.pyplot.plot) for further details.

**Comment by jklymak** [comment]
Another reason is that we can’t infer the positional arguments.

**Comment by timhoffm** [comment]
Closing, because `plot()` is the way to go here. Anyway, thanks for contributing your ideas.
