### ISSUE TITLE
The density flag in pyplot.hist() does not work correctly

### ISSUE THREAD

**Issue by kdlin** [matplotlib/matplotlib#15603]
### Bug report

**Bug summary**
The density flag is supposed to have density for the Y-axix for the histogram plot, pyplot.hist(). However, the output does not always work correctly. The following is an example.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

np.random.seed(0)
x = np.random.random(100)
plt.hist(x, density=True)
plt.show()
```

**Actual outcome**

```
# 
# Please see the generated histogram below
#
```
![image](https://user-images.githubusercontent.com/25801835/68241326-51f18880-ffc3-11e9-9615-9b69fb065f95.png)

**Expected outcome**
The Y-axis should display density.

**Matplotlib version**

  * Operating system: inux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline
  * Python version:3.6.8
  * Jupyter version (if applicable):5.2.2
  * Other libraries:

**Comment by jklymak** [comment]
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html
```
density : If True, the first element of the return tuple will be the counts normalized to form a probability density, i.e., the area (or integral) under the histogram will sum to 1. This is achieved by dividing the count by the number of observations times the bin width and not dividing by the total number of observations. 
```

Thats what the above plot does.  I'm going to close, but if you think thats an error, feel free to continue discussion...

**Comment by kdlin** [comment]
Isn't this a strange way for plotting histogram? When density = False, the histogram plot would have counts on the Y-axis. But when density = True, the Y-axis does not mean anything useful. 

I think a better implementation would plot the PDF as the histogram when density = True.

**Comment by jklymak** [comment]
We are just following numpy's convention here:  https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html 

You can of course calculate the histogram yourself using `np.histogram` and normalize it as applicable and plot using `step` or `bar`

**Comment by jklymak** [comment]
See also #15605

**Comment by aritraMandal02** [comment]
It is still an issue. The ticker values shown in the y-axis should not be greater than 1. This means the frequency in that bin is greater than the total frequency which simply doesn't make any sense. I have faced this issue today.
![Screenshot (109)](https://github.com/matplotlib/matplotlib/assets/87606712/db1e209b-4d6c-46fd-84c6-d60ce7ac0b7d)
