### ISSUE TITLE
Grid disappear after pcolormesh apply

### ISSUE THREAD

**Issue by AntSimi** [matplotlib/matplotlib#15600]
### Bug report

**Bug summary**

Grid disappear after pcolormesh apply
![toto](https://user-images.githubusercontent.com/36040805/68127437-2d8ba280-ff16-11e9-804d-482d12f4b6a3.png)

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np
ax = plt.subplot(111)
ax.grid(True)
ax.pcolormesh(np.arange(7), np.arange(7), np.random.randn(6,6))
ax.set_xlim(-1,7)
plt.show()
```

**Expected outcome**

Grid must be visible, but if you apply a pcolormesh after to set grid to True, grid disapear?

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version: 3.1.1
  * Matplotlib backend : Qt4Agg
  * Python version: 3.7.4

I install library with conda with no options:
conda install matplotlib

**Comment by ImportanceOfBeingErnest** [comment]
The grid seems to be turned off deliberately

https://github.com/matplotlib/matplotlib/blob/014aa5b97b71806a02cf9ea9162a0d50a85f2d50/lib/matplotlib/axes/_axes.py#L6173

I don't know if there is any specific reason for that?

**Comment by jklymak** [comment]
Weird.  It’s been like that for 14 years though, so may be hard to change?

**Comment by anntzer** [comment]
Looks like pcolor() does the same, and has basically always done so.
It's probably actually not too hard to change that: one can check before the call to `grid(False)` whether the grid is on (which would only happen if explicitly set earlier in the code and then the user relying on pcolor(mesh)() unsetting it...) and if so emit a deprecationwarning asking to unset the grid first.

**Comment by timhoffm** [comment]
Could it be that this serves the purpose of overriding `rcParams[axes.grid.*]` settings for these plots? By default, a style might have grid lines, but they don't make sense for false-color plots.

Anyway should `imshow()` have the same behavior?

**Comment by Tillsten** [comment]
As a suggestion, maybe add another `rcParams['axes.auto_disable']` ?

**Comment by anntzer** [comment]
> Could it be that this serves the purpose of overriding rcParams[axes.grid.*] settings for these plots? By default, a style might have grid lines, but they don't make sense for false-color plots.

Actually I occasionally do want grids on my images.

> As a suggestion, maybe add another rcParams['axes.auto_disable'] ?

In that case I would suggest just disabling the grid yourself with `grid(False)` (or modifying the style to unset `rcParams["axes.grid.*"]`); I don't think every possible arrangement needs to be doable via rcParams.

**Comment by jklymak** [comment]
I don’t think any individual artists should set axes properties.  If it weren’t for back compatibility concerns I’d vote to change this

**Comment by timhoffm** [comment]
> If we're going to make the user add a kwarg to each call I don't see how that's better than requesting that the user calls grid(False) first.

For backward compatibility, the default would of course stay to deactivate the grid.

**Comment by anntzer** [comment]
My point is that this can actually be changed with a proper deprecation transition (check whether the grid was set, and if so, warn that pcolormesh won't unset it for you anymore in the future).

**Comment by timhoffm** [comment]
> I don’t think any individual artists should set axes properties.

It's the `pcolormesh()` method, not the artist. There's other precedence, e.g. `imshow` sets the aspect. I believe that some plotting functions may modify the axes by default to adapt it to the intention of the plot type.
