### ISSUE TITLE
Support histograms normalized to a value != 1

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#15605]
It would be useful if hist() could normalize histograms to values other than 1 (typical use case: plot two histograms representing two subpopulations, one of which represents 1/3 of the total population and the other 2/3).  Right now this is rather painful to do, requiring either to completly forgo hist() and instead use np.histogram() and do the plotting oneself, or to modify the coordinates for the individual artists returned by hist() (which is tricky to do in a generic manner because this technically depends on histtype/orientation...).

This could easily be folded into the `density` kwarg, taking advantage of the fact that `True == 1`: we could just have `density = x (: float)` normalize to `x` (except x = False/0 which still means no normalization).  (Note that having this specified by `density` rather than a separate `normalize_to` (e.g.) avoids having to decide what happens if `density` is False but `normalize_to` is set.

This was briefly discussed in #1567 though that issue was mostly requesting other features and closed after discussing them.

**Comment by timhoffm** [comment]
+1 for the concept. +/-0 for reusing `density`.

From an API point of view, `normalization` would be a better term than `density`. `density` makes sense as a bool, but `density=0.5` is semantically misleading. Options are:
- "misuse" `density`
- use two keywords and deal with conflicts
- deprecate `density` and introduce `normalization`.
All of these have their disadvantages, and I don't have a particular preference.

**Comment by anntzer** [comment]
> deprecate density and introduce normalization.

We already just went through a deprecation cycle to rename `normed` to `density` so I think a second such cycle would be a bit too much.

**Comment by kdlin** [comment]
To my knowledge, there are two ways to plot histograms for the Y-axis: count and PDF. The current pyplot.hist() does not implement the PDF option correctly, as I reported in #15603. The returned values may be okay. But the chart does not show PDF correctly.

A work-around is to use weights parameter to normalize it to 1 or another value. But this is limiting the use of "density" flag.

**Comment by anntzer** [comment]
It is reporting pdfs properly.  Note that it is plotting a *density* so it's the integral (height times width) that's 1, not the sum of the height of the bars.

**Comment by kdlin** [comment]
That is not the case, as I reported in #15603. Please refer to the example in that ticket.

**Comment by anntzer** [comment]
The area of the blue zone in https://github.com/matplotlib/matplotlib/issues/15603#issue-518000088 *is equal to 1*.

**Comment by ImportanceOfBeingErnest** [comment]
Given the repeated confusion that this specific thing causes every now and then, my vote would be to stay as close as possible to the `numpy.histogram` implementation. Should numpy decide to add arguments for non-unity density, matplotlib could take them over.

**Comment by anntzer** [comment]
It's very easy to take the output of numpy.histogram and multiply it by whatever factor you want.  It's, as argued above, not so easy to do so on the histogram artists generated by matplotlib.

**Comment by liltaylor** [comment]
I think the point here is that if you don't have the full range of your sample as your range (or the range covered by the bins) the flag density=True does not give you an estimate of the density, but, rather, an estimate of the _conditional density_ given you are inside the specified range. This has a lot of "wow effect" on me. Maybe it would be enough to write this in the documentation, to clarify things.

**Comment by jklymak** [comment]
The docstring writes what `density=True` means to the `hist` method in math.  I don't think we can be more explicit than that.  https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.hist.html

I'm actually going to close this, because between `numpy.histogram`, `axes.stair` and `axes.bar` folks can normalize as they require, and possibly animate if they want. `axes.hist` is just a convenience around these methods for the simplest cases; more complex cases should be handled at a lower level.  @anntzer, please feel free to reopen if you disagree with this state of things.

**Comment by anntzer** [comment]
The addition of `stairs` changed the story a bit and makes it much easier to just draw custom things; I agree with closing.
