### ISSUE TITLE
Colormaps should have a `_repr_html_` that is an image of the colormap

### ISSUE THREAD

**Issue by jsignell** [matplotlib/matplotlib#15616]
`colorcet` has a swatch function in the plotting module that creates an image of the colormap.

<img width="1048" alt="Screen Shot 2019-11-06 at 3 00 22 PM" src="https://user-images.githubusercontent.com/4806877/68333441-85f1aa00-00a6-11ea-99b0-d9ef9726c916.png">

I think that the colormaps should have a `_repr_html_` that does something similar.

**Comment by jklymak** [comment]
Would be cool.  How does it get used?

**Comment by story645** [comment]
In jupyter notebook you could type `cm.jet` and it'd print out a swatch

**Comment by jsignell** [comment]
Whoops I guess I should have mentioned that part :)

**Comment by timhoffm** [comment]
That's a fancy feature and if somebody wants to implement that, go for it.

However, I suspect that it's more fancy than actually useful. The only purpose I see for drawing a standalone colormap is getting an impression of the colors. I would primarily do that for selecting a suitable colormap. But in such a scenario I would not necessarily know the name, and I would like to compare different maps. Both can be addressed better by the [colormap reference](https://matplotlib.org/devdocs/gallery/color/colormap_reference.html).

But maybe I'm overlooking a real-world use-case.

**Comment by jsignell** [comment]
Well I definitely tend to think about such things from the perspective of a higher level package that would consume the `_repr_html_` (such as [panel](https://panel.pyviz.org)). If you think about it from that perspective you can imaging someone easily displaying a bunch or colormaps by having them render themselves using their `_repr_html_`. Definitely fancy though :)

**Comment by dopplershift** [comment]
It’s always nice for users to be able to do things *without* referring to an external resource, and in this case *not* have to refer to our colormap reference example. Otherwise, the jupyterlab/notebook environment wouldn’t have that handy “shift-tab bring up a tooltip” functionality.

I also think it’s nice for users who are offline and don’t have quick access to the colormap reference.

**Comment by bdice** [comment]
I would like to work on this for the SciPy 2020 sprint. 😃

**Comment by Carreau** [comment]
you likely want a `_repr_png_`, so that non-html frontend can display it.
