### ISSUE TITLE
Deprecation warning about formlayout

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#15638]
### Bug report

**Bug summary**

This is not really a bug, but when I install a package (nexpy/nexpy) in Miniconda that uses Matplotlib, I get a deprecation warning about the use of the old qt_editor.formlayout module, which says that it will be removed in v3.3. The problem is that the replacement module cannot be listed as a dependency in conda because it is not available in either the default conda channel or Conda-forge. How will Matplotlib handle this dependency when 3.3 is released?

**Code for reproduction**

```
$ conda config --add channels conda-forge
$ conda install nexpy
$ conda install qtconsole
$ nexpy &
```

**Actual outcome**

This gives the following warning. 

```
/home/rosborn/miniconda3/lib/python3.7/site-packages/nexpy/gui/widgets.py:21: MatplotlibDeprecationWarning: 
The matplotlib.backends.qt_editor.formlayout module was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use the formlayout module available on PyPI instead.
  from matplotlib.backends.qt_editor.formlayout import (ColorLayout,
```

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7

**Comment by ImportanceOfBeingErnest** [comment]
This came in via https://github.com/matplotlib/matplotlib/pull/12889. It says:

> matplotlib.backends.qt_editor.formlayout module
This module is a vendored, modified version of the official formlayout module available on PyPI. Install that module separately if you need it.

What this means is that nexpy should probably take up formlayout as a dependency itself. Or use a vendored version of it as well.  
Note that if you think you need more time for this adaption, one can of course postpone the removal.

**Comment by rayosborn** [comment]
That isn't the issue. I already import the new formlayout module when it's available, but revert to the qt_editor version when it's not. The issue is that I *cannot* make the new formlayout module a dependency because it will cause conda installations to fail, since it is not available on conda at all. It's only on PyPI.

**Comment by rayosborn** [comment]
If Matplotlib is going to require formlayout in future versions, someone will have to get it installed on conda-forge.

**Comment by ImportanceOfBeingErnest** [comment]
The original formlayout and the vendored version of it have already diverged. This was the motivation for making the vendored version private and deprecate public usage.  
If conda cannot be convinced to provide formlayout you can still vendor it yourself, either in the form of the original version or in form of the current vendored version from within matplotlib.

**Comment by rayosborn** [comment]
I'm afraid I am having a lot of difficulty in understanding what you are talking about. Can you use a different word than "vendor" because I have no idea what that means in this context?

As I understand it, in earlier versions of Matplotlib, a version of formlayout was included within the qt_editor module. Then, it was released on PyPI as a separate package. In more recent versions of Matplotlib, this new separate version is now used in their Qt GUI to generate a figure options form and there is a threat to discontinue the qt_editor version completely in future versions. 

This means that, in the future, it will be impossible to guarantee that the Qt backend of Matplotlib will work, even after resolving all listed dependencies, because formlayout cannot be listed as a dependency if it's not available on conda. The user will just see some mysterious exception and be told to install formlayout. If they have no control over their particular Python distribution, they will be powerless to fix it.

It is not my job to add formlayout to conda-forge. It seems to me that if Matplotlib wants to use the functionality in the latest version of formlayout, the developers should either ensure that the package is available on conda-forge before removing the qt_editor version or back-port the code into Matplotlib.

**Comment by ImportanceOfBeingErnest** [comment]
Apparently my comments lacked some detail, sorry for that.  
Matplotlib itself uses its own version of formlayout ("vendored"), which is not the same as the one you can install on pypi ("original"). 
Matplotlib will continue to use its own version. There is no risk of matplotlib breaking or users seeing errors. The thing that changed is that this version is considered internal in the future. This will give matplotlib the freedom to change that piece of code and adapt it to its needs without notice.

For users, who have previously used this piece of code, e.g. by importing ` matplotlib.backends.qt_editor.formlayout`, this has the following consequence: They would either need to
* Install formlayout from pypi (https://pypi.org/project/formlayout/) and `import formlayout` instead; or,
* Put a custom version of the code into their own code base ("vendoring").

**Comment by rayosborn** [comment]
So all I have to do is replace ``import matplotlib.backends.qt_editor.formlayout`` by ``import matplotlib.backends.qt_editor._formlayout``. I wish I had known that earlier, because I spent some time modifying the ``formlayout`` calls in NeXpy to match the new package, since I assumed that the warnings meant the internal version was being removed. I am used to monitoring internal changes to the Matplotlib code because I already use a customized version of the Matplotlib toolbar and figure option dialogs, so I'm not worried if it's public or private.

**Comment by ImportanceOfBeingErnest** [comment]
Once it's private it can as well be removed, i.e. replaced by something completely different. That's the whole point of it being private. So continuing to use `matplotlib.backends.qt_editor._formlayout` is definitely not recommended.

**Comment by rayosborn** [comment]
Thanks for the advice. I can probably absorb what I need into my own modules.

**Comment by anntzer** [comment]
You can use (and declare dependencies on) pip packages in a conda environment (I regularly do so myself), see e.g. https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
In any case I think this can be closed?
