### ISSUE TITLE
None as tick label converted to empty string

### ISSUE THREAD

**Issue by wesbarnett** [matplotlib/matplotlib#15630]
### Bug report

I was surprised that when `None` is a tick label it gets converted to an empty string instead of `NaN` or simply `None`. Maybe this is a weird cornercase, but I actually have a case where one category is `None` and another category is `""` so when they are used as labels, they show up as the same thing.

**Code for reproduction**

```python
labels = ["A", "B", "C", "", None]
values = [1.0, 2.0, 3.0, 4.0, 5.0]
plt.barh(np.arange(len(values)), values, tick_label=labels)
```

In contrast and as a counterexample from another package, when used as index values, `pandas` actually converts `None` to `NaN`. For example, run:

```python
pd.DataFrame(values, index=labels)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/5508833/68419155-b0576c00-0167-11ea-8405-572ab253f92c.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/5508833/68419130-a33a7d00-0167-11ea-8592-e0da97686d06.png)

Alternatively, if I plot using pandas

```
pd.DataFrame(values, index=labels).plot.barh()
```

I get the following plot:

![image](https://user-images.githubusercontent.com/5508833/68421573-85234b80-016c-11ea-873c-58d748fc00a3.png)

**Matplotlib version**

  * Operating system: macOS Mojave (10.14.5)
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.4
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

I installed matplotlib via pip in a virtual environment.

**Comment by timhoffm** [comment]
`None` resulting in no label is the intended way of working in Matplotlib. Casting `None` to a string would be a bit of an assumption. I can't speak for pandas, but `None` -> `NaN` conversion seems like a type coercion (may happen if you force a list containing non-numeric data into a numeric column).

If you want the string "None", you should pass it in as such `[str(l) for l in labels]`, or `map(str, labels)`.

**Comment by anntzer** [comment]
fwiw I think the situation with labels is pretty awkward: we convert everything to strings, *except* None (and that change is quite recent (depending on the specific place) -- #10392, #14660).  If someone wants to write robust, generic code, they can't rely on that autoconversion unless they know for sure the label can't be None (basically, it's the OP's issue).
I would support deprecating passing parameters other than str or None.  (cf. `plot(["1", "2"])` which used to mean `plot([1, 2])` before the implementation of categoricals -- well I don't know whether that really supports doing the change given the havoc that the change caused, but I see these as being the same kind of change)

**Comment by jklymak** [comment]
I'm not sure there is still an action item here, so closing, but feel free to re-open.
