### ISSUE TITLE
URL is not shown when webagg failed to open the browser.

### ISSUE THREAD

**Issue by GreenCourt** [matplotlib/matplotlib#15650]
Thanks for developping!  
Currently, the URL is shown only when `rcParams['webagg.open_in_browser']` is False.

```python
# from matplotlib/lib/matplotlib/backends/backend_webagg.py
@staticmethod
    def show():
        WebAggApplication.initialize()

        url = "http://{address}:{port}{prefix}".format(
            address=WebAggApplication.address,
            port=WebAggApplication.port,
            prefix=WebAggApplication.url_prefix)

        if rcParams['webagg.open_in_browser']:
            import webbrowser
            webbrowser.open(url)
        else:
            print("To view figure, visit {0}".format(url))

        WebAggApplication.start()
```

* Is it possible to print the URL when `webbrowser.open` failed?
* Or, simply set `webagg.open_in_browser` to False when `$DISPLAY` is empty on Linux?

**Matplotlib version**
  * Operating system: Debian 10
  * Matplotlib version:  3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): webagg
  * Python version: 3.7.4

**Comment by anntzer** [comment]
The second option won't work because webbrowser.open can succeed even with an unset DISPLAY if a text-mode browser (elinks, w3m, etc.) is available.
Printing if `webbrowser.open` returns False (that's how it signals failure) seems fine, do you want to open a PR for that?
