### ISSUE TITLE
pyplot.imsave() erases data in RGB channels if alpha is 0 when saving to PNG with Matplotlib 1.5.2 / Python 2.7

### ISSUE THREAD

**Issue by romwell** [matplotlib/matplotlib#15677]
### Bug report

**Bug summary**

Note: this bug is not reproducible in Matplotlib 3.0, so I am filing it here so that people who had a similar problem know what to do.

Problem: pyplot.imsave() erases data in RGB channels if alpha is 0, and replaces it with white color.

When calling pyplot.imsave(), the pixels with alpha equal to 0 ([r, g,b, 0]) get written as white pixels with alpha 0 ([255, 255, 255, 0]).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg 

# Generate a test image: orange canvas, with alpha set to 1
im = [[[0.95, 0.6, 0.1, 1] for c in range(200)] for r in range(200)]

# Apply mask: make top left corner transparent, but don't touch the RGB data.
for r in range(100):
  for c in range(100):
    im[r][c][3] = 0

# Save the image. The RGB data in top left corner is wiped out.
plt.imsave('orange.png', np.array(im))

# Let's load the image back and see the data destroyed:
saved_rgba = mpimg.imread('orange.png') 

# We remove the alpha channel to expose the bug.

def remove_alpha(im):
  return  [[ (r, g, b) for (r, g, b, a) in row ] for row in im]

saved_rgb = remove_alpha(saved_rgba)
correct_rgb = remove_alpha(im)

# Plot side-by-side to see data loss
# The top left corner is white, because of the bug - but it should not be.
fig, axes = plt.subplots(1, 2)
axes[0].imshow(saved_rgb)
axes[1].imshow(correct_rgb)

print('Saved value ' + str(saved_rgba[0][0]) + ';  actual value ' +  str(im[0][0])  )
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/11616602/68635215-afe30c00-04ac-11ea-9963-c78c3bc82a77.png)

```
Saved value [1. 1. 1. 0.];  actual value [0.95, 0.6, 0.1, 0]
```

**Expected outcome**
Any pixel with value [r,g,b,0] should get saved as [r, g, b, 0].
I.e. saved and actual values should match:

```
Saved value [0.95, 0.6, 0.1, 0];  actual value [0.95, 0.6, 0.1, 0]
```

The two squares in the output of the above code should both be completely orange.

![image](https://user-images.githubusercontent.com/11616602/68635234-be312800-04ac-11ea-9362-f569681bae2d.png)

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 1.5.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://IPython.kernel.zmq.pylab.backend_inline
  * Python version: 2.7.15

Using Matplotlib from within Colab / Python 2 runtime.

**Comment by QuLogic** [comment]
> Note: this bug is not reproducible in Matplotlib 3.0, so I am filing it here so that people who had a similar problem know what to do.

So there's no reason to keep this open, then?
