### ISSUE TITLE
Errorbar doesn't show correct result in log scale

### ISSUE THREAD

**Issue by weiguangcui** [matplotlib/matplotlib#15681]
### Bug report

The errorbar does not show correct error values when changing into log scale.

Please see the errorbar for the data points in this [correct](https://drive.google.com/file/d/1nq4BJY7DSShu7sH6YiCdc-bVC6ER4D2X/view?usp=sharing) figure and the one in [wrong](https://drive.google.com/file/d/194oZKddM_p1xVZPbnCE5PoNbNdfNhdC8/view?usp=sharing) figure.

The wrong errorbar value is from this line calculation;
`ax1.errorbar(10**Terrazas17[:,0],10**Terrazas17[:,2], yerr=T17err, zorder=0, fmt="none", marker="none",elinewidth=1)`
While the corret value is calculted in a stupid way:
`for i in range(Terrazas17[:,1].size):
    plot([10**Terrazas17[i,0],10**Terrazas17[i,0]],[T17err[0,i],T17err[1,i]],lw=1,c='k')
`

**Matplotlib version**
3.1.1

**Comment by jklymak** [comment]
Can you make a self-contained example that we can test using synthetic data?

**Comment by jklymak** [comment]
I'm going to close for lack of response, but feel free to respond and we can easily re-open!  Thanks...
