### ISSUE TITLE
stacked bar with colors based on values and not same color for same column

### ISSUE THREAD

**Issue by sagarsitap596** [matplotlib/matplotlib#15689]
<img width="378" alt="Screenshot 2019-11-13 at 12 50 10 PM" src="https://user-images.githubusercontent.com/16373773/68741649-323a1000-0614-11ea-99d0-ee427b67833d.png">

Its not a bug. I just want to know if this kind of graph can be drawn using matplotlib

**Comment by anntzer** [comment]
Yes, see https://matplotlib.org/gallery/misc/table_demo.html#sphx-glr-gallery-misc-table-demo-py.
Please keep the issue tracker for bug reports; you can ask questions on the mailing list or https://discourse.matplotlib.org/.

**Comment by sagarsitap596** [comment]
Thank you!
