### ISSUE TITLE
Center parameter of pie chart does not work?

### ISSUE THREAD

**Issue by aryanmediratta** [matplotlib/matplotlib#15728]
I have gone through the entire documentation of Matplotlib and all questions on Stackoverflow but i could not find one use case of the Center parameter in matplotlib.pyplot.pie. How can it be used?

**Comment by ImportanceOfBeingErnest** [comment]
`center` sets the center of the pie. An example would be

```
import matplotlib.pyplot as plt

plt.pie([4,2,3,1], center=(5,1))
plt.pie([2,3,1,4], center=(1,1))
plt.pie([1,4,2,3], center=(3,4))
plt.autoscale()

plt.show()
```

resulting in

![image](https://user-images.githubusercontent.com/23121882/69150290-b25eea80-0ad8-11ea-96c0-cac39af537d7.png)

The [documentation](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.pie.html) says
> center : list of float, optional, default: (0, 0)
 Center position of the chart. Takes value (0, 0) or is a sequence of 2 scalars.

which I think is clear enough. Do you have any suggestion for improving it?

**Comment by aryanmediratta** [comment]
Just wanted an example because i couldn't find any. Thank you so much!

**Comment by quarkov** [comment]
@ImportanceOfBeingErnest 

Hi! 

Thanks for sharing your example with a bunch of pies, it helped me too.
And I needed help because center parameter didn't work when I was trying to align _the only_  pie.
Just try
```
import matplotlib.pyplot as plt
plt.pie([4,2,3,1])
plt.show()
```
and then
```
plt.pie([4,2,3,1], center=(2, 0))
plt.show()
```
There will be no difference, the method seems to work correctly with at least two or more pies, not with the only one. I worked this around by creating an empty second pie in addition to the first one, but I'm not sure it supposed to be that way =)

**Comment by tacaswell** [comment]
@quarkov are you using the inline backend or other wise saving using `bbox_inches='tight'`?

**Comment by ImportanceOfBeingErnest** [comment]
The `center` always works correctly. The reason you don't see a difference on screen is that the `pie` method sets the limits of the axes around the center of the pie. 
Compare the two cases below, where we set the frame on and autoscale

```
import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(ncols=2)
ax1.pie([4,2,3,1], frame=True)
ax2.pie([4,2,3,1], center=(2,0), frame=True)

ax1.autoscale()
ax2.autoscale()
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/78905017-a8388b00-7a7d-11ea-80d4-b0e8179077b0.png)

Obviously you can change the limits of the axes yourself; so in the following we have one pie per axes, all axes have the same limits set, and the center parameter is changed:

```
import matplotlib.pyplot as plt

fig, (ax1, ax2, ax3) = plt.subplots(nrows=3)

ax1.pie([4,2,3,1], center=(0,0))
ax1.set_xlim(-1,5)

ax2.pie([4,2,3,1], center=(2,0))
ax2.set_xlim(-1,5)

ax3.pie([4,2,3,1], center=(4,0))
ax3.set_xlim(-1,5)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/78905443-49274600-7a7e-11ea-9614-e7132a169618.png)
