### ISSUE TITLE
Please add markeredgewidth keyword to matplotlib.scatter()

### ISSUE THREAD

**Issue by soerendip** [matplotlib/matplotlib#15731]
I can set the width of marker edges in `plt.plot()` with the `makeredgewidth` argument. Though this does not work for `plt.scatter()`. It would be nice if those kinds of keywords would be more consistent in the different functions.

**Comment by ImportanceOfBeingErnest** [comment]
Do you mean `linewidths`?

**Comment by timhoffm** [comment]
Closing due to lack of feedback.
