### ISSUE TITLE
Setting lines.marker = s in matplotlibrc also sets markers in boxplots

### ISSUE THREAD

**Issue by soerendip** [matplotlib/matplotlib#15730]
### Bug report

Setting this line
    lines.marker      : s    ## the default marker
in the matplotlibrc leads to an unexpected result:

```
%pylab inline
boxplot(range(100))

```

![fig](https://user-images.githubusercontent.com/3391614/69190942-b0982580-0ade-11ea-903e-8f59e3f5e70d.jpg)

**Comment by ImportanceOfBeingErnest** [comment]
I suppose nooone ever wants markers on boxplot outlines. Hence one might probably add
a line like 

    d["marker"] = ""

in 

https://github.com/matplotlib/matplotlib/blob/70fb1a6b90a8f308cbe27c1edfdf543f3761c222/lib/matplotlib/axes/_axes.py#L3928
