### ISSUE TITLE
%matplotlib qt5 in Jupyter notebook freezes Python event loop

### ISSUE THREAD

**Issue by sjlnk** [matplotlib/matplotlib#15746]
Qt5Agg backend randomly freezes the Python event loop when used inside Jupyter Notebook. Line `%matplotlib qt5` starts this random freezing behaviour. Freezing does not seem to happen when executing the code from ipython console.

I'm posting this here because I guess it's an issue with Matplotlib's QT5 event loop integration logic.

## Bug Reproduction

Run inside a Jupyter notebook:

```python
import asyncio
from datetime import datetime

# inclusion of this line causes pinger to stop eventually,
# typically after 5-10 loops
%matplotlib qt5  

async def pinger():
    while True:
        print(str(datetime.now()))
        await asyncio.sleep(0.1)

await pinger()
```

## Workaround

I have developed a hacky workaround for this issue but I'm not sure what side effects it may have, if any:
 
```python
import asyncio
from datetime import datetime
import matplotlib
from PyQt5.QtCore import QCoreApplication
matplotlib.use('qt5agg')

async def pinger():
    while True:
        print(str(datetime.now()))
        await asyncio.sleep(0.1)

async def qt_integration_loop():
    while True:
        QCoreApplication.processEvents()
        await asyncio.sleep(0.01)

asyncio.create_task(qt_integration_loop())
asyncio.create_task(pinger())

# do some plotting here, it should work and pinger should keep on running ...
```

## System Info:

OS: Manjaro Linux, kernel: 5.3.6-1-MANJARO
Python: 3.8.0 (manually compiled from source)
matplotlib: 3.2.0rc1
jupyter: 1.0.0
jupyter-client: 5.3.4
jupyter-core: 4.6.0
ipykernel: 5.1.3
ipython: 7.9.0
notebook: 6.0.1
pyqt5: 5.13.1

Python environment is created using virtualenv/virtualenvwrapper. The packages are installed using pip.

**Comment by tacaswell** [comment]
xref https://matplotlib.org/devdocs/users/explain/figure/interactive_guide.html for lots of details about event loop integration.

In the terminal the two event loops that need to be integrated are the input prompt and the GUI event loop which is pretty well established and working for both readline and prompt toolkit.  Depending on the platform these either work by running the event loop for a finite amount of time _or_ setting up a file descriptor to kill the GUI event loop when the user types anything.  Thus the charade of both the prompt and the GUI being active is maintained.

In the case of ipykernel, then the user input is all handled in the browser, but on the server side you need to integrate the asyncio event loop that is managing the network communications and the GUI toolkit.  I suspect, but have not checked the code to be sure, that messages from the front end will interrupt the GUI toolkit but other wise it does not time-share with asyncio.

The solution of using a kicker function to run in a task and let the GUI toolkit run sometimes is a not terrible solution (I have used it in other cases).
