### ISSUE TITLE
Add link to matplotlib docker container in install docs

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15744]
There's a matplotlib docker container owned by matplotlib at https://github.com/matplotlib/mpl-docker
A link to this should be added somewhere in the devdocs, probably as a section under https://matplotlib.org/devdocs/users/installing.html#installing-from-source

The goal of this docker container is to more easily set up a matplotlib development environment, especially for new contributors.

**Comment by Macavitycode** [comment]
Hey, May I take this up as my first contribution?

**Comment by Macavitycode** [comment]
May I take this up as my first contribution to Open source?

**Comment by devarshigoswami** [comment]
If the issue still persists, can I try ?

**Comment by story645** [comment]
Sorry no, I'm going to close this issue for now since there isn't agreement on the state of the docker image.
