### ISSUE TITLE
Hiding the edges of a axes.table cell overrides the cell facecolor

### ISSUE THREAD

**Issue by mrroboto1420** [matplotlib/matplotlib#15743]
### Bug report

**Bug summary**

When setting the `visible_edges` parameter of an `ax.table` cell to either `'vertical'` or `'horizontal'`, the cell facecolor becomes transparent. It happens if the colored cells are in the column labels and the body cells.  

**Code for reproduction**

```python

import matplotlib.pyplot as mpl

fig, ax = mpl.subplots()
fig.patch.set_visible(False)
ax.axis('off')
ax.axis('tight')
col_text = ['Col A', 'Col B', 'Col C', 'Col D', 'Col E', 'Col F']

table_text = [['Lorem Ipsum', '', 'foo', '', 'bar', 'loo'],
              ['Lorem Ipsum', 'foo', 'bar', '', 'loo', 'too'],
              ['', 'foo', 'bar', '', 'loo', 'too'],
              ['', 'foo', 'bar', '', 'loo', 'too'],
              ['', 'foo', 'bar', '', 'loo', 'too'],
              ['Lorem Ipsum', '', '', 'foo', '', 'bar'],
              ['Lorem Ipsum', 'foo', '', 'bar', '', 'loo'],
              ['', 'foo', '', 'bar', '', 'loo'],
              ['Lorem Ipsum', 'foo', '', 'bar', '', 'loo']]

t0 = ax.table(cellText=table_text, colLabels=col_text,
              loc='center', bbox=[-0.05, 0, 1.1, 1.0],
              rowLoc='center', colLoc='center', cellLoc='center')

for (row, col), cell in t0.get_celld().items():
    t0.auto_set_column_width(col)
    # Set cell colors:
    t0[(row, col)].set_facecolor('red')
    t0[(0, col)].set_facecolor('#5dbcd2')
    # Text placement in specific columns:
    t0[(row, 1)]._loc = 'left'
    t0[(row, 2)]._loc = 'right'
    t0[(row, 3)]._loc = 'right'
    t0[(row, 4)]._loc = 'right'
    # Hide horizonal borders in columns C, D, and E:
    if (col in (2, 3, 4)):
        cell.visible_edges = 'horizontal'
    # Hide vertical borders in rows 2 through 8, column A:
    if ((row in (2, 3, 4, 5, 7, 8) and col == 0)):
        cell.visible_edges = 'vertical'

mpl.show()
```

**Actual outcome**

[https://i.imgur.com/O9cBpGx.png](https://i.imgur.com/O9cBpGx.png)

**Expected outcome**

The cell colors should be preserved. In the example above, the column labels should be light blue and the table cells should all be red. Note that the cell color will return if the cell's `visible_edge` parameter is set back to `'closed'`  i.e. `cell.visible_edges = 'closed'`.

**Matplotlib version**

  * Operating system: Windows 10 Pro (using Anaconda custom (64-bit))
  * Matplotlib version:  3.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.9

All packages installed / managed with Anaconda.

**Comment by ImportanceOfBeingErnest** [comment]
It's not that the facecolor is changed, but rather the cell looses its filling.
If the `visible_edges` is not `"closed"`, the path of the rectangle is open. But open rectangles cannot be filled.

**Comment by mrroboto1420** [comment]
Is there a work around to preserve the cell color while erasing the borders?  I have been going over the documentation, but it seems like this is the only way to erase cell borders.

**Comment by ImportanceOfBeingErnest** [comment]
One can use a transparent color for the `edgecolor` of the cell. That would visually remove the complete cell border. 
Otherwise it would of course be possible to create a custom `CustomCell`, which has any kind of feature you like, but it would require a good bit of work. 

Note that there is a slightly improved version of matplotlib's table functionality in https://github.com/swfiua/blume; however, as far as I can see, it suffers the same problem as matplotlib's internal table in this respect.
