### ISSUE TITLE
get framealpha from legend object

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#15764]
I'm trying the retrieve the `framealpha` value from a legend object. The method `get_alpha()` always seems to return `None`.
```python
import matplotlib.pyplot as plt
import matplotlib as mpl

plt.plot(range(100), label="data")
plt.legend(loc="center", framealpha=0.31415)

# inspect the legend
fig = plt.gcf()
ax = fig.get_children()[1]
leg = ax.get_children()[10]
assert isinstance(leg, mpl.legend.Legend)
print(leg.get_alpha())
```
```
None
```

**Comment by anntzer** [comment]
That's because the alpha value only applies to the frame (so you can get it with `leg.get_frame().get_alpha()`) -- not to the handles and labels.
