### ISSUE TITLE
Link in the project description should use https

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#15768]
Link in the project description at https://github.com/matplotlib/matplotlib should use https.
And maybe remove the trailing slash.

![grafik](https://user-images.githubusercontent.com/2836374/69495491-d438e280-0ec7-11ea-9302-085787af2b3a.png)

@tacaswell I assue you're only one with the permission to change that.

**Comment by story645** [comment]
Anyone in the @matplotlib/admin group  (which actively is @tacaswell , @dopplershift , & @efiring ) can change it.

**Comment by dopplershift** [comment]
Changed. Thanks for pointing that out!
