### ISSUE TITLE
DOCS 2D Line label option `_nolegend_` is not documented

### ISSUE THREAD

**Issue by jpeacock29** [matplotlib/matplotlib#15770]
### Bug report
The special value for a 2D Line label `_nolegend_` is not documented.

**Comment by timhoffm** [comment]
I'm not sure if this is intended to be user-facing.

Also there's more logic involved than just `_nolegend_`:
~~~
l, = plt.plot([1, 3, 2])
print(l.get_label())
l, = plt.plot([1, 3, 2], label=None)
print(l.get_label())
l, = plt.plot([1, 3, 2], label='_nolegend_')
print(l.get_label())
l, = plt.plot([1, 3, 2], label='_private')
print(l.get_label())
l, = plt.plot([1, 3, 2], label='visible')
print(l.get_label())
plt.legend()
~~~
results in 
~~~
_line0
_line1
_nolegend_
_private
visible
~~~
and only `visible` is part of the legend.

**Comment by jpeacock29** [comment]
It seems like these magic parameters should definitely be documented. Could not any user incidentally input these values? Surely they're not common labels, but if some labels are special I would think it should be documented. These are also used as [an example](https://matplotlib.org/gallery/event_handling/pipong.html?highlight=_nolegend_) and floating around as solutions for adding a line but not listing it on the legend.

**Comment by ImportanceOfBeingErnest** [comment]
This was documented in 1.3.1 (https://matplotlib.org/1.3.1/users/legend_guide.html), where it says

> If label attribute is empty string or starts with “_”, those artists will be ignored.

![image](https://user-images.githubusercontent.com/23121882/69673807-778e2100-109b-11ea-9e61-e3a2e39a2395.png)

This got lost in #2442, specifically in https://github.com/matplotlib/matplotlib/commit/99f325dcd3f045f92c422d335e3d5be4a72b33f6#diff-52cdf77880da5ac3d7b2712d2d318772L47

I suspect that this was an unintentional mistake and should be readded.
