### ISSUE TITLE
3.2.0 may break some Cartopy tests

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#15806]
### Bug report

I've started trying to get Cartopy working with the latest Matplotlib releases. Currently a lot of things fail, but there are some new things in 3.2.0rc1 that we may want to fix before releasing. Unfortunately, all those existing failures make it difficult to determine what's new, but I believe the following *are* introduced by 3.2.0rc1.

**Code for reproduction**

```
$ conda create -p /tmp/cpmpl matplotlib-base cartopy filelock
$ conda activate /tmp/cpmpl
$ pip install matplotlib==3.2.0rc1
$ pytest --pyargs cartopy -k 'test_limits_contour or test_contour_plot_bounds or test_global_contourf_wrap_no_transform or test_pcolormesh_goode_wrap or test_pcolormesh_mercator_wrap'
```

**Actual outcome**
For `test_limits_contour`:
```
E           AssertionError: 
E           Arrays are not almost equal to 6 decimals
E           
E           x and y +inf location mismatch:
E            x: array([[ inf,  inf],
E                  [-inf, -inf]])
E            y: array([[ 70., -45.],
E                  [170.,  45.]])
```

For `test_contour_plot_bounds`:
```
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       Mismatch: 100%
E       Max absolute difference: 3230840.45
E       Max relative difference: 0.99999998
E        x: array([-0.05,  0.05, -0.05,  0.05])
E        y: array([-2763217.  ,  2681906.  ,  -263790.62,  3230840.5 ])
```

For `test_global_contourf_wrap_no_transform`:
The test image is cropped into a very small area.

For `test_pcolormesh_goode_wrap`, and `test_pcolormesh_mercator_wrap`:
The left edge of the image is visibly cropped.

**Expected outcome**

Tests pass.

**Matplotlib version**
  * Operating system: Fedora 30
  * Matplotlib version: 3.2.0rc1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg
  * Python version: 3.7
  * Other libraries: Cartopy 0.17.0

**Comment by QuLogic** [comment]
`test_limits_contour` bisect to:
```
commit b03370a04537fec9ed153850cf0d73cbc839bd78
Author: Jody Klymak <jklymak@gmail.com>
Date:   Fri Jul 19 13:50:57 2019 -0700

    FIX: get_datalim for collection (#13642)
    
    * FIX: change autolim exclude shapes not in data co-ordinates
    
    * Update doc/api/next_api_changes/2019-03-04-AL.rst
    
    Co-Authored-By: Elliott Sales de Andrade <quantum.analyst@gmail.com>
```

`test_contour_plot_bounds` bisects to:
```
commit aa87937c38be95a5efad0a0a8c30717ffd8931fb
Author: Paul Ivanov <pivanov5@bloomberg.net>
Date:   Wed Oct 2 13:07:01 2019 -0700

    Backport PR #15258: Don't fallback to view limits when autoscale()ing no data.
```

`test_global_contourf_wrap_no_transform` is changed slightly (zoomed in a bit) by b03370a04537fec9ed153850cf0d73cbc839bd78, and then broken entirely by aa87937c38be95a5efad0a0a8c30717ffd8931fb.

`test_pcolormesh_goode_wrap` and `test_pcolormesh_mercator_wrap` both fail starting with b03370a04537fec9ed153850cf0d73cbc839bd78

**Comment by QuLogic** [comment]
I just realized the conda-forge packages of Cartopy do not include the test images, so you will need to grab them from GitHub or install via source if you want to test `test_global_contourf_wrap_no_transform`,  `test_pcolormesh_goode_wrap`, and `test_pcolormesh_mercator_wrap`

**Comment by jklymak** [comment]
@QuLogic,  Happy to look at this, but I'm not 100% clear if the problem is just that an image test broke, which is expected if it used auto limits, or if the image looks really bad.

**Comment by QuLogic** [comment]
Well, the problem is that the test limits are now 0 (or maybe whatever `nonsingular` outputs), so there's nothing in the image. Some tests don't do that, and are just cropped a little bit, but I haven't figured out why that is.

In Cartopy, artists can have an arbitrary transform that is unrelated to the transform of the Axes (which is fundamental to how it works since data and map may come from different coordinate systems.) For `contourf`, Cartopy [grabs the collection's datalim and reapplies autoscaling based on it](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L1512-L1516). I _think_ the [new check for `transData`](https://github.com/matplotlib/matplotlib/commit/b03370a04537fec9ed153850cf0d73cbc839bd78#diff-506c6bd01694bddbd8999f2c6e920705R222) fails in this case, returning a null bbox, but I could be wrong.

Please excuse any errors I may have made; I have no internet and am trying to answer the specifics from memory.

**Comment by anntzer** [comment]
@QuLogic Looks like you may need the following as well, due to #13581:
```patch
diff --git a/lib/cartopy/tests/mpl/__init__.py b/lib/cartopy/tests/mpl/__init__.py
index 6ba66cc..bc9fe42 100644
--- a/lib/cartopy/tests/mpl/__init__.py
+++ b/lib/cartopy/tests/mpl/__init__.py
@@ -31,7 +31,6 @@ import matplotlib.pyplot as plt
 import matplotlib.patches as mpatches
 from matplotlib.testing import setup as mpl_setup
 import matplotlib.testing.compare as mcompare
-import matplotlib._pylab_helpers as pyplot_helpers
 
 
 MPL_VERSION = distutils.version.LooseVersion(mpl.__version__)
@@ -211,12 +210,12 @@ class ImageTesting(object):
             plt.switch_backend('agg')
             mpl_setup()
 
-            if pyplot_helpers.Gcf.figs:
+            if plt.get_fignums():
                 warnings.warn('Figures existed before running the %s %s test.'
                               ' All figures should be closed after they run. '
                               'They will be closed automatically now.' %
                               (mod_name, test_name))
-                pyplot_helpers.Gcf.destroy_all()
+                plt.close('all')
 
             if MPL_VERSION >= '2':
                 style_context = mpl.style.context
@@ -228,14 +227,12 @@ class ImageTesting(object):
             with style_context(self.style):
                 r = test_func(*args, **kwargs)
 
-                fig_managers = pyplot_helpers.Gcf._activeQue
-                figures = [manager.canvas.figure for manager in fig_managers]
-
+                figures = [plt.figure(num) for num in plt.get_fignums()]
                 try:
                     self.run_figure_comparisons(figures, test_name=mod_name)
                 finally:
                     for figure in figures:
-                        pyplot_helpers.Gcf.destroy_fig(figure)
+                        plt.close(figure)
                     plt.switch_backend(orig_backend)
             return r
```

**Comment by QuLogic** [comment]
Isn't that in 3.3.0, only? I'll look into that some time.
