### ISSUE TITLE
LogLocator subs affects ticks but not labels

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [matplotlib/matplotlib#15816]
When using `ticket.LogLocator`, I get ticks at the specified multiples of powers of 10, but the labels don’t correspond to the ticks.  (Note that in the attached plot, there’s no label at 5 times the power of ten, and undesired labels appear at 4 and 6 times the power of 10).

**Code for reproduction**

My code looks like this:

```
import matplotlib.pyplot as plt
from matplotlib import ticker

fig, ax = plt.subplots()
ax.plot([20,100])
ax.set_yscale('log')
loc= ticker.LogLocator(base=10.0, subs=(1, 2, 3, 5))
ax.yaxis.set_major_locator(loc)
ax.tick_params(axis='y', which='minor', left=False)

plt.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/1065412/70004410-01fed680-151b-11ea-9d1f-ae6287bb764d.png)

**Matplotlib version**

  * Operating system: Windows 7
  * Matplotlib version: 2.2.4
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6

**Comment by Phillip-M-Feldman** [comment]
A possibly related issue: The bottom two labels are overprinted.

**Comment by ImportanceOfBeingErnest** [comment]
Here is what works instead, 

```
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import ticker

fig, ax = plt.subplots()
ax.plot([20,100])
ax.set_yscale('log')
loc = ticker.LogLocator(base=10.0, subs=(1, 2, 3, 5))
fmt = ticker.LogFormatterSciNotation(base=10.0, labelOnlyBase=False, 
                                     minor_thresholds=(np.inf, np.inf))
ax.yaxis.set_major_locator(loc)
ax.yaxis.set_major_formatter(fmt)
ax.tick_params(axis='y', which='minor', left=False, labelleft=False)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/70005214-0baf2b00-1569-11ea-84d4-710c1c173f9b.png)


This is based on the [documentation of `LogFormatter`](https://matplotlib.org/3.1.1/api/ticker_api.html#matplotlib.ticker.LogFormatter), which mentions this special case. 

> In some cases [...] there is no distinction between major and minor ticks; the tick locations might be set [..] by a locator that puts ticks at integer powers of base and at intermediate locations. For this situation, disable the `minor_thresholds` logic by using `minor_thresholds=(np.inf, np.inf)`, so that all ticks will be labeled.

However, I do agree that it it not at all obvious why the formatter does not simply label all available ticks.

**Comment by Phillip-M-Feldman** [comment]
This is helpful.  Thank you!

**Comment by ruijpbastos** [comment]
It looks like there's an implemented solution, even though it could probably be simplified. So, can this issue be closed, or should there be some more discussion about this?

**Comment by jklymak** [comment]
There is some desire to overhaul the tick system someday and issues like this point out the pain points.

**Comment by ruijpbastos** [comment]
> There is some desire to overhaul the tick system someday and issues like this point out the pain points.

Should this have some label, or be added to some milestone, to make the status clear?
