### ISSUE TITLE
Stacked bar width greater than 1 ignored in 3.1.1...

### ISSUE THREAD

**Issue by mzadony** [matplotlib/matplotlib#15811]
Sometime between Matplotlib 3.0.3 and 3.1.1, the ability to set over-width bars was lost.  Specifically, I have a chart with dates on the bottom that aggregate data by month, showing a stacked bar chart with 3 possible values, but Matplotlib 3.1.1 ignores situations where width > 1.  (I didn't test to see if 3.1.0 or 3.1.1 had the regression).

Here's the code in question... "res1" is a DataFrame containing aggregated counts by month (e.g. counts for the month of 2/2018 has a date of '2018-02-01').

	fig, ax1 = plt.subplots()

	fmt = "{x:,.0f}"
	tick = mtick.StrMethodFormatter(fmt)

	ax1.yaxis.set_major_formatter(tick)
	ax1.set_xlabel("[Date Processed] by month")
	ax1.bar(res1.yrmo_xaxis.values, res1.ct_clm_A, color="tab:purple", width=20, label="AAA Claims")
	ax1.bar(res1.yrmo_xaxis.values, res1.ct_clm_B, color="tab:green", width=20, label="BBB Claims", bottom=res1.ct_clm_A)
	ax1.bar(res1.yrmo_xaxis.values, res1.ct_clm_C, color="tab:blue", width=20, label="CCC Claims"
			, bottom=np.array(res1.ct_clm_A)+np.array(res1.ct_clm_B))
	ax1.tick_params(axis="y", labelsize="small")
	ax1.set_title("[dbo].[xxxxx_claim] - AAA/BBB/CCC Claims by [Date Processed]")
	ax1.legend(loc="best", fontsize="x-small")

	fig.tight_layout()
	fig.autofmt_xdate()
	pdf.savefig()
	plt.close()

**Actual outcome**

This chart is saved as a multi-page PDF file (there's more charts on different pages).  In 3.1.1, pencil-thin bars are created, even when zooming the PDF to 3200%.  The chart is unreadable for its purpose.  It appears that any value for "width" larger than 1 is now ignored.

**Expected outcome**

In 3.0.3, the output was different - when set to "width=20", the bar width took up most of the available space for the month.  Reverting from 3.1.1 to 3.0.3 fixed the problem / removed the regression.

I presume that width handling with dates in the x-axis is to offer ~30 columns in a month, where "width=1" means 100% of the available column width (e.g. 1 day out of 30), and "width=20" would be 2000% of a day's column width (e.g. around 2/3 of the total space for the month).  The intent with "width=20" is to spill into other days' space within the month, _which is desired in this case_, since the only data point is always the 1st of the month.

Also, changing the dates to text (e.g. '2018-01') would not be practical, since some months might not have aggregated entries in the dataframe (e.g. no values in that month).  I'd want the chart to not have a bar in those months...

**Matplotlib version**

  * Operating system: Windows Server 2016
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'TkAgg'
  * Python version: 3.7.1
  * Jupyter version (if applicable): N/A
  * Other libraries: 

Python 3.7.1 is running from SQL Server 2017-CU16 via Machine Learning Server 9.4.7.  Matplotlib 3.1.1 (and 3.0.3) were installed via PIP.

**Comment by ImportanceOfBeingErnest** [comment]
Could you provide a self-contained code please, best without the use of pandas, but if necessary, defining the dataframe within the code itself.

**Comment by mzadony** [comment]
I have been able to find the offending code.  In 3.0.x (I think 3.0.2 and maybe 3.0.3), including dates in the x-axis **of a bar chart** resulted in a _"left = x - width / 2 [...] ufunc subtract cannot use operands with types dtype('<M8[ns]') and dtype('float64')"_ error.  (This is documented along with the solution: https://github.com/matplotlib/matplotlib/issues/11649#issuecomment-404694105 ).

The solution, which only needed to be done to bar charts, was to add ".values" to the x-axis entry, creating the correct chart.  However, with 3.1.1 or 3.1.2 (I didn't test 3.1.0), including ".values" causes the pencil-thin lines to occur.  Removing ".values" resolves the problem in 3.1.1 and 3.1.2, but I'm not sure if this would count as a regression in 3.1.x...  (I will admit to being a Python newbie)

Here is self-contained code that shows what I'm talking about...  Note that I intentionally did this as a PDF (change the save-as location) because a Jupyter Notebook inline chart doesn't show the thin-width lines at all, but PDF does.
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.backends.backend_pdf import PdfPages

d = {'x': pd.to_datetime(['2010-12-01', '2011-01-01', '2013-01-01']),
    'y1': [4, 9, 2],
    'y2': [5, 10, 3],
    'y3': [1, 2, 3]}

res1 = pd.DataFrame(data=d)

with PdfPages("d:/results/xxxxx.pdf") as pdf:
    fig, ax1 = plt.subplots()

    fmt = "{x:,.0f}"
    tick = mtick.StrMethodFormatter(fmt)

    ax1.yaxis.set_major_formatter(tick)
    ax1.set_xlabel("[Date Processed] by month")
    ax1.bar(res1.x.values, res1.y1, color="tab:purple", width=20, label="A Claims")
    ax1.bar(res1.x.values, res1.y2, color="tab:green", width=20, label="B Claims", bottom=res1.y1)
    ax1.bar(res1.x.values, res1.y3, color="tab:blue", width=20, label="C Claims", bottom=np.array(res1.y1)+np.array(res1.y2))
    ax1.tick_params(axis="y", labelsize="small")
    ax1.set_title("[dbo].[xxxxx_claim] - A/B/C Claims by [Date Processed]")
    ax1.legend(loc="best", fontsize="x-small")

    fig.tight_layout()
    fig.autofmt_xdate()

    pdf.savefig()
    plt.close()
```
On 3.1.1 and 3.1.2, this creates a PDF chart file that contains tiny-width lines -- even when using Acrobat Reader DC with zoom set as 6400%, shows the bar as 1 pixel wide.  Removing the ".values" from the 3 `ax1.bar(res1.x.values, ...)` lines above fixes the width issue. However, including ".values" is necessary in 3.0.x to avoid the error mentioned above.

For the above: pandas 0.25.3, NumPy 1.17.4.

**Comment by dstansby** [comment]
Would it be possible to post the image as you would expect it (ie. with Matplotlib 3.0.3) and the broken image? I think that would help us to understand what's going wrong here.

**Comment by timhoffm** [comment]
Closing due to lack of feedback. @mzadony please report back if this is still an issue on 3.2.2.
