### ISSUE TITLE
Should constrained_layout work as plt.figure() argument?

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#15821]
### Bug report

**Bug summary**

Might be a documentation issue. The [constrainedlayout_guide](https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html) says

> constrained_layout needs to be activated before any axes are added to a figure. Two ways of doing so are
> * using the respective argument to `subplots()` or `figure()`,
> * [...]

However, `fig = plt.figure(constrained_layout=True)` does not seem to have any effect.

**Code for reproduction**

```
import matplotlib.pyplot as plt

def example_plot(ax, fontsize=12):
    ax.plot([1, 2])
    ax.set_xlabel('x-label', fontsize=fontsize)
    ax.set_ylabel('y-label', fontsize=fontsize)
    ax.set_title('Title', fontsize=fontsize)

fig = plt.figure(constrained_layout=True)
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)

for ax in [ax1, ax2]:
    example_plot(ax, fontsize=24)
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/23121882/70066708-69855680-15ed-11ea-980e-c1ea91601c1d.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/23121882/70066780-8ae64280-15ed-11ea-9ea8-3c6b15a2b9da.png)

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7

**Comment by jklymak** [comment]
Constrained layout doesn't work with `add_subplot` in the numeric form, only the `gridspec` form.  i.e. 
```python
    fig = plt.figure(constrained_layout=True)
    gs = fig.add_gridspec(2, 1)
    ax1 = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])
```
works fine. 

Probably the docs should be clearer about that. TBH I didn't realize `add_subplot` worked with the numeric arguments.

**Comment by jklymak** [comment]
See #17347

**Comment by jklymak** [comment]
Moved to 3.4 because I don't think this is time critical.  OTOH if someone wanted to merge #17347 in time for 3.3 this would be a helpful addition
