### ISSUE TITLE
Cannot import name 'ft2font' from 'matplotlib'

### ISSUE THREAD

**Issue by chenrhcq** [matplotlib/matplotlib#15832]
### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib
```

**Actual outcome**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-0484cd13f94d> in <module>
----> 1 import matplotlib

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib-3.2.0rc1-py3.8-macosx-10.9-x86_64.egg/matplotlib/__init__.py in <module>
    204 
    205 
--> 206 _check_versions()
    207 
    208 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib-3.2.0rc1-py3.8-macosx-10.9-x86_64.egg/matplotlib/__init__.py in _check_versions()
    189     # Quickfix to ensure Microsoft Visual C++ redistributable
    190     # DLLs are loaded before importing kiwisolver
--> 191     from . import ft2font
    192 
    193     for modname, minver in [

ImportError: cannot import name 'ft2font' from 'matplotlib' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib-3.2.0rc1-py3.8-macosx-10.9-x86_64.egg/matplotlib/__init__.py)
```

**Expected outcome**

Should be no error

**Matplotlib version**

  * Operating system: MacOS 10.14.6
  * Matplotlib version: 3.2.0rc1
  * Python version: 3.8
  * Jupyter version (if applicable): 
  * Other libraries: 

I installed matplotlib with pip.

**Comment by tacaswell** [comment]
This is usually a sign that your installation is broken,  `ft2font` is one fo the c-extensions we build.

Can you please post an issue at https://discourse.matplotlib.org/c/community/install along with details about how you installed Matplotlib?

**Comment by jklymak** [comment]
How does pip build this though?

**Comment by tacaswell** [comment]
If you are installing from source, it gets built by distutils.  When the wheel gets bundled the binary objects get included (if you download the whl from pypi and look inside there is a `matplotlib/ft2font.cpython-38-darwin.so` file which is a c-extension module).  Installing from the wheel should copy that file to the correct place to be found by python.

I am a bit surprised that the path above has `.egg` in it.

We either need confirmation from someone with a mac that this is a problem with `pip install --pre matplotlib` or more details from the OP.

**Comment by ErikCVik** [comment]
I am also getting error. 

I installed matplotlib using pip to a target directory. 

Looking inside package folder I see "ft2font.cp38-win32" but python doesnt seem to be able to call it? 

Any suggestions on how to fix this?

**Comment by tacaswell** [comment]
@ErikCVik It is very difficult to debug installation issues without more information.

This conversation would be better had at https://discourse.matplotlib.org/c/community/install/13 . Can you please create new topic and include:

 - your operating system version
 - your version of python and how you installed it
 - how you tried to install Matplotlib
   - if you are not installing a pre-built wheel / conda package, what compiler versions you are using
 - what version of Matplolib you are trying to install

I'm going to close this issue because I don't think there is anything we can do on the Matplotlib side.
