### ISSUE TITLE
Lasso selector does not show in Jupyter notebook

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/matplotlib#15852]
### Bug report

**Bug summary**

When trying the [Lasso selector](https://matplotlib.org/3.1.1/gallery/widgets/lasso_selector_demo_sgskip.html) example in a Jupyter notebook, the lasso does not show.
It does however show correctly in the Qt window, if I try the same code example in a classic ipython terminal shell.

I also tried with a simpler example:
```py
import matplotlib.pyplot as plt
from matplotlib.widgets import LassoSelector

fig, ax = plt.subplots()

def onSelect(x):
    print(x)

lineprops = {'color': 'red', 'linewidth': 4, 'alpha': 0.8}
lsso = LassoSelector(ax=ax, onselect=onSelect, lineprops=lineprops)

plt.show()
```
but the same happens:

**Jupyter**:
![Screenshot at 2019-12-07 13-09-52](https://user-images.githubusercontent.com/39047984/70374477-e3218b00-18f2-11ea-978a-10629d985d44.png)

**Qt window**:
![Screenshot at 2019-12-07 09-16-26](https://user-images.githubusercontent.com/39047984/70374481-f46a9780-18f2-11ea-85d0-bbc60ebda200.png)

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg + nbAgg
  * Python version: 3.7.3
  * Jupyter version (if applicable): 1.0.0 notebook: 6.0.2
  * Other libraries: 

Matplotlib installed from `conda`

**Comment by ImportanceOfBeingErnest** [comment]
The nbagg backend does not implement blitting, but the LassoSelector widget uses it by default. 
Hence

    LassoSelector(..., useblit=False)

will work in the notebook.

**Comment by anntzer** [comment]
Normally widgets autodisable blitting when the canvas doesn't support it (they check for canvas.supports_blit).  Why is that not working in this case?

**Comment by ImportanceOfBeingErnest** [comment]
Due to https://github.com/matplotlib/matplotlib/blob/e240493a899ac05cb992cdb88f5487386586090e/lib/matplotlib/widgets.py#L2461-L2462

I suppose it should be 

    lineprops['animated'] = self.useblit

instead.

**Comment by anntzer** [comment]
lgtm
