### ISSUE TITLE
pdf-backend for savefig produces X markers that are drawn incorrectly in Adobe Illustrator

### ISSUE THREAD

**Issue by normanius** [matplotlib/matplotlib#15856]
### Bug report

Markers 'x' are drawn incorrectly in Adobe Illustrator if a plot is saved via `savefig` as a PDF (see screenshot 1 below). All [other markers](https://matplotlib.org/3.1.1/api/markers_api.html) look fine. The markers also look fine if the pdf is displayed with Apple's Preview (see screenshot 2).

Note: To judge the other markers in Adobe Illustrator, one first has to ungroup the PDF (Object -> Ungroup) in order to have the transparency set straight. (See issue #15051 for more info on this)

**Code for reproduction**

```python
fig = plt.figure()
markers = [ ".", ",", "o", "v", "^", "<", ">", "1", "2", "3", "4", "8", "s",
            "p", "P", "*", "h", "H", "+", "x", "X", "D", "d", "|", "_",
            0, 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11 ]
for i, m in enumerate(markers):
    plt.plot([i%8+0.5],[i//8+0.5], m,
             color=[0.0,0.3,1.0], alpha=0.6)
plt.xlim([0,9])
plt.ylim([0,5])
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.savefig("test.pdf",
            transparent=True,
            bbox_inches="tight")
```

**Actual outcome**

Screenshot 1: X-marker shown in Apple's Preview.app. (correct)
![image](https://user-images.githubusercontent.com/11406002/70376202-b7a89b80-1906-11ea-8954-bcb5d770bd00.png)

Screenshot 2: Same X-marker shown in Adobe Illustrator (wrong)
![image](https://user-images.githubusercontent.com/11406002/70376220-e1fa5900-1906-11ea-8416-84d7b90f1706.png)

Screenshot 3: All the markers in Adobe Illustrator (after ungrouping) - only the X-marker is displayed wrongly
![image](https://user-images.githubusercontent.com/11406002/70376311-e96e3200-1907-11ea-9dc5-305c91bcdc91.png)

**Expected outcome**

Screenshot 1 and Screenshot 2 should look the same.

**Matplotlib version**
  * Operating system: MacOS 10.14.5
  * Matplotlib version: 3.1.1
  * Matplotlib backend: MacOSX
  * Python version: 3.6.8

Matplotlib installed through pip.

**Comment by normanius** [comment]
Note: selecting the marker in Illustrator and then selecting Object -> Path -> Outline Stroke fixes the appearance.

**Comment by anntzer** [comment]
Do you know any other pdf viewer that showcases this? (not everyone has access to illustrator).
Do you get the same issue with https://github.com/matplotlib/mplcairo?

**Comment by normanius** [comment]
I can reproduce the problem only in Illustrator. Tested Inkscape, and a couple of other apps that come with a PDF viewer (TeXshop, Books, Opera, Safari, Skim...), though I don't know whether they just interface to Preview.app somewhere under the hood... 

`pip install mplcairo` fails for my machine, which is why wasn't able to check myself.

I doubt that this is an Illustrator bug. But since the problem occurs just there, I can post the problem on one of Adobe's forums and seek help there.

**Comment by anntzer** [comment]
Thanks for checking.

**Comment by tacaswell** [comment]
I am comfortable leaving this closed as a renderer bug until proven otherwise.
