### ISSUE TITLE
Better logo image for numfocus donation page

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#15879]
### Bug report

The matplotlib logo at the [numfocus dontation page](https://numfocus.org/donate-to-matplotlib) looks quite makeshift and not like the logo we use on the website nowadays.

The picture is 300px scaled to 360px. Therefore, I've recreated the logo in two sizes

- 300px https://imgur.com/kY3FqKq
- 360px https://imgur.com/dNX4i3g

Could somebody with contact to numfocus offer please them the new images?

The images were created using the logo example https://matplotlib.org/gallery/misc/logos2.html and parameters
~~~
make_logo(height_px=360, lw_bars=1, lw_grid=0.8, lw_border=1.2, 
          rgrid=[1, 3, 5, 7], with_text=False)
~~~
Resulting pngs were minified through https://tinypng.com/.

**Comment by tacaswell** [comment]
I have contacted NF about this.
