### ISSUE TITLE
Describe possible kwargs that may be input into a function

### ISSUE THREAD

**Issue by physkets** [matplotlib/matplotlib#15899]
### Bug report

**Bug summary**

A lot of Artists and functions take extra _kwargs_. It would be nice to have a documentation page describing all possibilities, and link to it from the documentation page of every function that can use it.

**Extra Info**

I recently found out that I could pass `rasterized=True` to `hist2d` only because someone told me. I wouldn't have known just from reading the docs.

**Matplotlib version**
  * Matplotlib version: 3.1.1
  * Python version: 3.8

**Comment by timhoffm** [comment]
These functions Axes plotting methods are missing kwargs descriptions:
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.bar.html
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.barh.html
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.hist2d.html
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.clabel.html
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.contour.html /  https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.contourf.html (check if they support kwargs additional to the ones documented)
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.xcorr.html / https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.acorr.html (a bit more complicated see source code)
- [ ] https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.pcolorfast.html supported kwargs depend on the type of grid.

**Comment by jeroaranda** [comment]
> ### Bug report
> **Bug summary**
> 
> A lot of Artists and functions take extra _kwargs_. It would be nice to have a documentation page describing all possibilities, and link to it from the documentation page of every function that can use it.
> 
> **Extra Info**
> 
> I recently found out that I could pass `rasterized=True` to `hist2d` only because someone told me. I wouldn't have known just from reading the docs.
> 
> **Matplotlib version**
> 
> * Matplotlib version: 3.1.1
> * Python version: 3.8

just found out the rasterized=True here!

contributing to this would be to fork the repository create some documentation and do a PR?

**Comment by tacaswell** [comment]
@jeroaranda What method are you looking at?  If you look at some of them (ex https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.bar.html ) there is a table at the bottom which lists rasterized.
