### ISSUE TITLE
Problem with inconsistent barplot: small bars missing 

### ISSUE THREAD

**Issue by jamesgoldfarb** [matplotlib/matplotlib#15902]
### Bug report

**Bug summary**

Having a problem with small bars disappearing…
The first plot has six bars for ‘75573’. The second and third plots have only one bar visible. The only difference being the deletion of the underscore in the xlabel and no rotation of the xlabel. Additionally, if I save the first plot with plt.save_fig() at high resolution, the bars are missing as in the 2nd and 3rd plots. Honestly, that’s my real problem…
Thanks in advance…

**Code for reproduction**

import pandas as pd

dict={‘2012’: {‘75571’: 2643.0, ‘75572’: 4459.0, ‘75573’: 30.0, ‘75574’: 31456.0},
‘2013’: {‘75571’: 2833.0, ‘75572’: 6192.0, ‘75573’: 13.0, ‘75574’: 31473.0},
‘2014’: {‘75571’: 4548.0, ‘75572’: 8290.0, ‘75573’: 41.0, ‘75574’: 33045.0},
‘2015’: {‘75571’: 7501.0, ‘75572’: 10031.0, ‘75573’: 40.0, ‘75574’: 35093.0},
‘2016’: {‘75571’: 9027.0, ‘75572’: 13310.0, ‘75573’: 409.0, ‘75574’: 41982.0},
‘2017’: {‘75571’: 11607.0, ‘75572’: 15535.0, ‘75573’: 75.0, ‘75574’: 48975.0}}

df=pd.DataFrame(dict)
df.index.name=‘AAAA_AAAA’ #NOTE UNDERSCORE
df.plot(kind=‘bar’,rot=70) #NOTE ROTATE

df=pd.DataFrame(dict)
df.index.name=‘AAAA AAAA’ #NO UNDERSCOE
ax=df.plot(kind=‘bar’,rot=70)

df=pd.DataFrame(dict)
df.index.name=‘AAAA_AAAA’ #NOTE UNDERSCORE
df.plot(kind=‘bar’) #NOTE NO ROTATE

**Actual outcome**

![Clipboard](https://user-images.githubusercontent.com/10813691/70535213-a50eac00-1b2a-11ea-987c-c329c310f1b7.jpg)
**Expected outcome**

**Matplotlib version**

  * Operating system: ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline
  * Python version: 3.7.5
  * Jupyter version (if applicable):
jupyter core     : 4.6.1
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

  * Other libraries:

**Comment by jklymak** [comment]
This is pretty clearly just a resolution issue.  I'm closing because I don't see how we can help with this.   Save with enough resolution or use a vector back end like PDF....

**Comment by tacaswell** [comment]
@jamesgoldfarb Why did you edit your issue out of existence?  It may not be a bug we can fix, but the content will be indexed by search engines and may help someone else who has the same problem in the future.

**Comment by jklymak** [comment]
Apologies if what I wrote on closing this sounded more abrupt than it could have.
