### ISSUE TITLE
Annotated heatmap label issue

### ISSUE THREAD

**Issue by paulvija** [matplotlib/matplotlib#15916]
### Bug report

I'm trying to annotate the rows and columns of an interpolated array. But the text labels seem to be not in the centre or misaligned. The extent is comprised of latitudes and longitudes. 
Is there a way to re-align the annotations towards the center pf each squares?

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(10,10)

xi = np.linspace(176.9167, 178.985, num=10)
yi = np.linspace(-16.1411, -18.284, num=10)

f, ax = plt.subplots(figsize=(10,10))

plt.imshow(data,extent = (np.min(xi),np.max(xi), np.min(yi),np.max(yi)))

for r,xx in enumerate(xi):
    for s,yy in enumerate(yi):
        plt.text(xx , yy , r,
                 horizontalalignment='center',
                 verticalalignment='center',fontsize=14, color='r'
                 )
plt.show()
```

**Actual outcome**
![annotate](https://user-images.githubusercontent.com/12703555/70700111-0dc67600-1d2f-11ea-8867-2a83b6dae057.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/12703555/70700382-862d3700-1d2f-11ea-811e-aed2a2a66aed.png)

**Matplotlib version**

  * Operating system: MacOS 10.15.1 
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline
  * Python version: 3.7.0

**Comment by ImportanceOfBeingErnest** [comment]
Recheck you logic for setting the extent. If you have 10 pixels to distribute between two values, those values are the edges of the first and last pixel; but you would have 11 edges in total. Alternatively, if you have 10 pixels and the pixel centers are known, the extent would need to be half a pixel wider in each direction.

**Comment by jklymak** [comment]
right, and then to centre the text, you need to put in the centre of the pixels.

**Comment by paulvija** [comment]
Thanks to both of you! I've solved it now. 11 edges scenario helped out. 
![image](https://user-images.githubusercontent.com/12703555/70754849-27060b80-1d9d-11ea-93fb-6ea327c55d4d.png)
