### ISSUE TITLE
Bossplayers

### ISSUE THREAD

**Issue by soriano9** [matplotlib/matplotlib#15917]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by story645** [comment]
Closing because there's no content in this bug report. Feel free to repopen once edited to include content.
