### ISSUE TITLE
Support for Python Type Hints (PEP 484)

### ISSUE THREAD

**Issue by CraigMiloRogers** [matplotlib/matplotlib#15926]
It would be helpful if matplotlib supported Python type hints (PEP 484, the typing module, etc.). I can attest that I, myself, have made mistakes using matplotlib that might have been more quickly resolved if type hints were available.

I realize that this is a significant change, requiring a significant effort. I may be able to contribute some time to this end.

**Comment by story645** [comment]
Thank you for your offer to help. This was discussed in #13798 and on the dev call* and the consensus was that @tacaswell is open to matplotlib/matplotilb-typeshed if people are interested in writing and supporting pyi files, but that typing (especially in upstream scientific packages) isn't standardized enough yet for Matplotlib to adopt inline use. 

*https://paper.dropbox.com/doc/In-Matplotlib-2019-meeting-agenda--AqWjIHu14j1631lSPjHsbDuRAg-aAmENlkgepgsMeDZtlsYu#:h2=No-3.8-syntax-before-2021-(dro

**Comment by anntzer** [comment]
I'm going to close this as non-actionable given that this was discussed not so long ago in #13798 and I don't think the state of typing in Python changed significantly since then.
