### ISSUE TITLE
Exception Thrown on Bar Graph with Datatime Index

### ISSUE THREAD

**Issue by CraigMiloRogers** [matplotlib/matplotlib#15924]
### Bug report

**Bug summary**

An exception occurs when doing a bar graph when the index is a datetime object with a timezone.
**Code for reproduction**

```python
        # This is not a complete snippet:
        ax.bar(sd.index, sd.values)
```

**Actual outcome**

```
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 2348, in bar
    self._process_unit_info(xdata=x, ydata=height, kwargs=kwargs)
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2125, in _process_unit_info
    kwargs = _process_single_axis(xdata, self.xaxis, 'xunits', kwargs)
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2108, in _process_single_axis
    axis.update_units(data)
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1495, in update_units
    self.set_units(default)
  File "/local/home/rogers/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1569, in set_units
    if u != self.units:
  File "/local/home/rogers/.local/lib/python3.6/site-packages/parse.py", line 527, in __eq__
    return self._name == other._name and self._offset == other._offset
AttributeError: 'NoneType' object has no attribute '_name'

```

**Expected outcome**
A bar graph should have been produced.

**Matplotlib version**

  * Operating system: OpenSUSE Tumbleweed Linux
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK3Cairo
  * Python version: 3.6.9
  * Jupyter version (if applicable):
  * Other libraries: 

Installed using pip3

**Buggy code**

In set_units(...) in axis.py, the statement " if u != self.units" fails when "self.units" is None and "u" is not None, and "u" is an instance of FixedTzOffset, causing FixedTzOffset.__eq__(...) in parse.py to fail.

Here is the relevant code in axes.py:
```
    def set_units(self, u):
        """
        Set the units for axis. 
        
        Parameters
        ----------
        u : units tag
        """
        pchanged = False
        if u is None:
            self.units = None
            pchanged = True
        else:
            if u != self.units:                                                                                                     
                self.units = u
                pchanged = True
        if pchanged:
            self._update_axisinfo()
            self.callbacks.process('units')
            self.callbacks.process('units finalize')
        self.stale = True

```
Here is the relevant code from parse.py:  FixedTzOffset.__eq__(...)

```
    def __eq__(self, other):
        return self._name == other._name and self._offset == other._offset
```

***Approach 1***
The following code fixes this bug with a change to axis.py.  It also has a change to prevent an unnecessary update when both 'u' and 'self.units' are None.

```
   def set_units(self, u):
        """
        Set the units for axis.
         
        Parameters
        ----------
        u : units tag
        """
        pchanged = False
        if u is None:
            if self.units is not None:
               self.units = None
               pchanged = True
        else:
            if self.units is None or u != self.units:
                self.units = u
                pchanged = True
        if pchanged:
            self._update_axisinfo()
            self.callbacks.process('units')
            self.callbacks.process('units finalize')
        self.stale = True
```

***Approach 2***
The following code fixes this bug with a change to parse.py:

```
    def __eq__(self, other):
        if other is None:
            return False
        return self._name == other._name and self._offset == other._offset
```

Both fixes (Approach 1 and Approach 2) may be implemented, if desired.

**Comment by anntzer** [comment]
That quite clearly seems to be a bug in parse.py, not in matplotlib (sure, you can special-case None in matplotlib, but this doesn't help with other units).

**Comment by CraigMiloRogers** [comment]
If you fix the bug in parse.py, you might want to also apply the optimization (to the u is None case) in axis.py.

**Comment by CraigMiloRogers** [comment]
I haven't checked to see if this fix is applicable to older stable releases of matplotlib.

**Comment by anntzer** [comment]
parse.py is not part of matplotlib.
Optimizing for None hardly makes sense (you could insert such checks for None literally before every equality check...).

**Comment by CraigMiloRogers** [comment]
No, the other branch of the if.  If both `u` and `self.units` are None, the existing code needlessly sets pchanged to True. Perhaps I should submit this as a separate bug report?

**Comment by anntzer** [comment]
Ah, yes.  Sorry for the quick close, you are correct.  We can track this here.

**Comment by CraigMiloRogers** [comment]
Why apply the Approach 1fix to matplotlib? I prefer to apply defensive programming when a bug is discovered that crosses packages, but I'll concede that this is a matter of taste.

**Comment by anntzer** [comment]
I could write arbitrary unit classes that do arbitrary things in their `__eq__`, failing in all kinds of random ways; matplotlib can't possibly handle all of them...

**Comment by CraigMiloRogers** [comment]
I am creating an issue in the parse project.

**Comment by CraigMiloRogers** [comment]
The issue I created in the parse project is: https://github.com/r1chardj0n3s/parse/issues/92

**Comment by CraigMiloRogers** [comment]
If I may take a little more of your time: I agree that it would be difficult to protect against all possible failures of external packages.  However, once someone runs into a specific instance of such a failure, I believe that it is good practice to provide defensive coding, at least some of the time.

If the maintainer of parse.py promptly issues a new release, fixing the bug there, then you can issue a compatability constraint for matplotlib (e.g., must be used with parse.py >= 1.12.2).

If the maintainer of parse.py does not promptly issue a new release, then it would be a kindness to the users of matplotlib to work around the issue.

Thanks.

**Comment by anntzer** [comment]
Again, I really do not believe this is realistic.  For any single line of matplotlib I can probably cook up an object with the right `__eq__` or `__add__` or whatever method that would make that line crash, and that crash could be avoided by adding a specific check at that line.

**Comment by jklymak** [comment]
I'm as always a few steps behind.  @CraigMiloRogers can you specify what `sd` is exactly here, and why `parse.py` is being used here at all?  A minimal working example helps.
