### ISSUE TITLE
highlight examples of new features in gallery

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15920]
Currently, the what's new content in the gallery is in the [pyplot](https://matplotlib.org/devdocs/gallery/index.html#pyplot) section of the gallery, I think because they somewhat (but inconsistently) use the pyplot api and are from the 0.9X version releases. 

For discoverability and to really highlight the new features, it might be good to factor these out into their own section in the gallery and then add plots from more recent [Whats New](https://matplotlib.org/devdocs/users/whats_new.html) for the newer releases:

- [ ] [Whats New 0.98.4 Legend](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_98_4_legend.html#sphx-glr-gallery-pyplots-whats-new-98-4-legend-py)
- [ ] [Whats New 0.98 Fill Between](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_98_4_fill_between.html#sphx-glr-gallery-pyplots-whats-new-98-4-fill-between-py)
- [ ] [Whats New 0.99 Axes Grid](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_99_axes_grid.html#sphx-glr-gallery-pyplots-whats-new-99-axes-grid-py)
- [ ] [What's New 0.99 MPL3D](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_99_mplot3d.html#sphx-glr-gallery-pyplots-whats-new-99-mplot3d-py)
- [ ] [Whats New 0.99 Spines](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_99_spines.html#sphx-glr-gallery-pyplots-whats-new-99-spines-py)
- [ ] [Whats New 1 MPL3D](https://matplotlib.org/devdocs/gallery/pyplots/whats_new_1_subplot3d.html#sphx-glr-gallery-pyplots-whats-new-1-subplot3d-py)

**Comment by timhoffm** [comment]
I fully agree we should not have "What's new" scattered throughout the gallery. Moving them to a separate section is a good step.

More generally, I'm not sure if we need a "What's new" section in the long run. Taking the matplotlib version as a category criterion seems not quite useful. Nobody cares if a feature was added in 0.98 or 1.2.1 when looking at the gallery. For future additions, I propose not to add "What's new" plots. Instead, add regular plots in the respective categories and link to them in the "What's new" document; or add an inline plot there if that's more suitable.

With the existing ones, we should finally also integrate them in the regular sections. Depending how important it is to keep the "What's new" aspect, we could edit the examples and old "What's new" files" accordingly. - Or we just discard that aspect because nobody cares about that in current docs (it would still be present in old versions of the docs).

**Comment by story645** [comment]
So the reason I like a standalone what's new section, especially if we can pull in more images from the newer what's news, is that it shows a record of new features to the library/that the library is dynamic & responsive to user requests.  I agree that maybe making a standalone what's new section in an already too crowded gallery long term isn't the right approach, but I think that maybe a bigger discussion on what is the point of the gallery/should we maybe have multiple smaller gallery pages that serve different purposes?

**Comment by timhoffm** [comment]
>  it shows a record of new features to the library/that the library is dynamic & responsive to user requests.

Isn't that what https://matplotlib.org/devdocs/users/whats_new.html is for

**Comment by story645** [comment]
Kind of, but the what's new pages are not a gallery (the visual is really important to me cause it's a visualization library) nor is it super discoverable right now (it's like 3 links under docs I think), but maybe the fix is something like using sphinx gallery in more places & putting a link + small blurb on the what's new in the right sidebar on the home page like a lot of other libraries do?

**Comment by timhoffm** [comment]
Kind of. I think there are multiple things to do here.

My main point is that a user is only interested in "What's new" of the last 1-2 releases. Everything else is established functionality in the library, and "new in version 0.x" is not a criterion I would look for in the gallery, instead the content (e.g. "Fill between") is the most relevant property and should be the main organization criterion.

**Comment by jklymak** [comment]
Maybe a “new” badge on examples added in the last two releases?

**Comment by story645** [comment]
I really like that @jklymak if it's doable! 

What's New discoverablity/layout can totally be addressed in a seperate issue

**Comment by timhoffm** [comment]
A "new" badge (or more general badges) would likely need to be a feature of sphinx-gallery because it generates the HTML code.

**Comment by smolgeat** [comment]
Hi, 
Since it doesn't seem like badges are a feature for sphinx-gallery would using an emoji like 🌟 at the beginning of the title of the recent examples achieve the same result?

**Comment by story645** [comment]
@smolgeat I think it's that that probably can't be automated and we'd have to have a legend to explain what that symbol means, but you're welcome to give it  shot.

**Comment by story645** [comment]
closing since the `what's new` section is gone in favor of #23506 - if those directives get added, can maybe use them for gallery badges

**Comment by QuLogic** [comment]
Was there a reason for re-opening?
