### ISSUE TITLE
multiple colorbars (with different ranges/ticks) for subplots in matplotlib

### ISSUE THREAD

**Issue by linlintamu** [matplotlib/matplotlib#15934]
I am using matplotlib to plot subplots with different colorbars. see code below for more detail.

The goal I want to achieve is the attached colorbars are with different ranges (ticks) for different subplots. This may be accomplished by setting different ci (see code below). For example, the left 2 columns subplots should come with a colorbar with range of 0-100,21 intervals; the right 2 columns subplots should be with a colorbar with range of 0-5, 21 intervals.

However, the first colorbar fails to have 0~100 labels.  I guess the left subplots are still correct regarding the patterns and colors, with only the 'labels' of the left colorbar wrong.

What should I do to fix this?

Thank you very much!

**Code for reproduction**

```python
fig, axs = plt.subplots(nrows=2, ncols=4, figsize=(10, 10)) #, constrained_layout=True)
fig.subplots_adjust(bottom=0.05, top=0.95, left=0.15, right=1.6,
                    wspace=0.1, hspace=0.15)

for i, ax in enumerate(axs.flat):
    cmap = plt.get_cmap('gist_earth_r')
    cmap.set_over('navy')
    cmap.set_under('white')
    if i < 2 or (i >= 4 and i<= 5):
        ci = np.linspace(0., 100., 21)
    else:
        ci = np.linspace(0.,5.,21)

    norm = matplotlib.colors.BoundaryNorm(ci, cmap.N)
    pcm = ax.pcolormesh( x, z, cs[i], cmap=cmap, norm=norm )
    ax.set_xticks([-90,-60,-30,0,30,60,90])
    ax.set_xticklabels(['90S','60S','30S','0','30N','60N','90N'])
    ax.set_yticks([1000,850,700,500,300,100])
    ax.set_ylabel('')
    ax.set_xlabel('')
    ax.invert_yaxis()
    ax.set_title(titles[i],loc='center',pad='5')#,fontdict=font)
    ax.xaxis.set_major_formatter(ticker.NullFormatter())
    ax.yaxis.set_major_formatter(ticker.NullFormatter())


fig.colorbar(pcm, ax=axs[:, :2], shrink=0.6, location='bottom',extend='both', pad=0.05)
fig.colorbar(pcm, ax=axs[:, 2:], location='bottom', shrink=0.6, extend='both', pad=0.05)
#fig.colorbar(pcm, ax=[axs[1, 1]], location='right')


plt.show()

```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
In that case you will need to use the instance of `pcm` for colorbar creation  that actually has the desired norm, i.e. you will want to either hold on to the `pcm` variables created, or create the colorbars within the loop. 
If further problems arise, I invite you to use the usual channels to seek help, i.e. stackoverflow, [discourse.matplotlib.org](https://discourse.matplotlib.org), or [the mailing list](https://mail.python.org/mailman/listinfo/matplotlib-users)
