### ISSUE TITLE
Accept url in fontManager.addfont

### ISSUE THREAD

**Issue by MaxGhenis** [matplotlib/matplotlib#15936]
### Bug report

**Bug summary**

In 3.2.0rc1, `fontManager.addfont` only accepts local paths. It'd be great to also accept urls, as to avoid requiring downloading a font file.

**Code for reproduction**

```python
!pip install -U --pre matplotlib
import matplotlib as mpl
mpl.__version__  # 3.2.0rc1
mpl.font_manager.fontManager.addfont('https://github.com/MaxGhenis/random/raw/master/Roboto-Regular.ttf')
mpl.rc('font', family='Roboto')
mpl.pyplot.plot([1, 2])
```

**Actual outcome**

>findfont: Font family ['Roboto'] not found. Falling back to DejaVu Sans.
![chart with dejavu sans instead of roboto](https://user-images.githubusercontent.com/6076111/70844108-21d2ac00-1df1-11ea-9724-6388848d2254.png)

**Expected outcome**
No warning. Chart with Roboto labels.

This occurs when I instead download the file:
```
!wget https://github.com/MaxGhenis/random/raw/master/Roboto-Regular.ttf
mpl.font_manager.fontManager.addfont('Roboto-Regular.ttf')
```

**Matplotlib version**
  * Operating system: Linux (Google Colab)
  * Matplotlib version: 3.2.0rc1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable): `jupyter core     : 4.5.0
jupyter-notebook : 5.2.2`
  * Other libraries:

**Comment by anntzer** [comment]
I would prefer not.  If we get into the business of downloading fonts, we also need to decide where to cache them, and for how long (or should we re-download the font every time?).  (and I guess more things that I don't want to care about -- https? ftp? ...)
Note that downloading the font is a one-liner even in python:
```
Path("dest_path.ttf").write_bytes(urllib.request.urlopen("https://...").read())
```
On the other hand addfont should probably raise if the font cannot be added (as in this case...).

**Comment by korakot** [comment]
We don't need to cache it. If people care enough about caching, they would have download it themselves.

The purpose of `addfont()` is to make it simpler to add a new font. So, supporting URL is very useful. People want the simplest solution possible. Please support it.

**Comment by anntzer** [comment]
Even if you don't care about caching, matplotlib needs to write that font somewhere to the filesystem.
If you learn how to open an url (which is again literally one line with the stdlib, and not a particularly obscure one), you will be able to use urls everywhere a file-like object is accepted, across all python libraries.  That seems better than going to each and every python library out there and ask them to add support for opening urls.

**Comment by MaxGhenis** [comment]
OK thanks for considering and the explanation. Feel free to close if this doesn't make sense.

**Comment by anntzer** [comment]
Thanks for the suggestion, at least this gave us #15937 so it's not all lost :)
