### ISSUE TITLE
Finance candlesticks

### ISSUE THREAD

**Issue by tbremard** [matplotlib/matplotlib#15931]
Hello,

you did support candlesticks,
 i do not see it anymore.

did you removed it definitely, or i do not find it ?

i also would like to print stock data via bar chart ( thin candles). possible ?

**Comment by timhoffm** [comment]
Candlestick plots were part of the finance module, which has been removed from core matplotlib in  2.2.0 ([see API changes](https://matplotlib.org/api/prev_api_changes/api_changes_2.2.0.html?highlight=change#modules-methods-and-functions)).

It's available as a separate module now and seems to get some new attention recently: https://github.com/matplotlib/mpl-finance.
