### ISSUE TITLE
Images are clipped incorrectly with custom clip path

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#15952]
### Bug report

**Bug summary**

This is related to #15946, but for images. When setting a custom clip path, the image is cropped slightly incorrectly.

**Code for reproduction**

(Note, in lieu of subclassing `Axes` and `Subplot`, I've just overwritten the `Axes.patch` using the [properties that it should have](https://github.com/matplotlib/matplotlib/blob/59acd5c4e2afc2ae9191ff2daf60bd959abd8c23/lib/matplotlib/axes/_base.py#L1073-L1081)).

```python
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as mpatches

data = [[1, 1], [0, 1]]

fig, ax = plt.subplots(1, 3, figsize=(6, 2), sharex=True, sharey=True)
ax[0].set_xlim(0, 2)
ax[0].set_ylim(0, 2)
ax[0].set_title('Default patch')

ax[2].patch = mpatches.PathPatch(
    Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
    facecolor=plt.rcParams['axes.facecolor'],
    edgecolor='None',
    linewidth=0,
    snap=False,
    transform=ax[2].transAxes)
ax[2].patch.set_figure(fig)
ax[2].set_title('Custom patch')

img = []
for a in ax:
    img.append(a.imshow(data, extent=(0, 2, 0, 2), vmin=-10))

img[1].set_clip_box(None)
img[1].set_clip_path(
    Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
    ax[1].transAxes)
ax[1].set_title('Custom clip path')

plt.show()
```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/302469/70952825-79615980-2035-11ea-8002-dfac7ba85a94.png)

If you check the antialiasing along the top spine, the first Axes is grey (f1f1f1), but the second and third are slightly yellow (f0e7a0). Note, this seems to be figure size and/or DPI dependent.

**Expected outcome**

All images should be cropped in the same way, and there should not be a difference in edges along the top of the Axes.

**Matplotlib version**
  * Operating system: Fedora 30
  * Matplotlib version: 9d00ca839e5faf10257095ad1e2bfb5296549d47
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg (probably just Agg though)
  * Python version: 3.6.3

**Comment by anntzer** [comment]
At the risk of sounding like a broken record... looks like this doesn't happen with mplcairo? can you confirm?

**Comment by QuLogic** [comment]
I believe you are correct.  Also, I think this affects all artists, not just images, but it really depends on how the artist interacts with the border.

**Comment by dopplershift** [comment]
@anntzer  *cough*humblebrag*cough* :wink:

**Comment by anntzer** [comment]
hehe...

**Comment by QuLogic** [comment]
As noted in #15970, it was not a full fix, but I couldn't figure out a way to reproduce in plain Matplotlib. Now, I _think_ I have something that still shows the issue. Basically, because the figure background defaults to white, you don't see it, but by changing the background to some other colour, you can see that the image is clipped a bit differently using a clip path over a clip box:
```python
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as mpatches
from matplotlib.testing import setup as mpl_setup


plt.rcParams['savefig.facecolor'] = 'b'

data = [[1, 1], [0, 1]]

fig, ax = plt.subplots(1, 4, figsize=(8, 2), sharex=True, sharey=True,
                       facecolor='b')
ax[0].set_xlim(0, 2)
ax[0].set_ylim(0, 2)
ax[0].set_title('Default patch')

for a in ax[2:]:
    a.patch = mpatches.PathPatch(
        Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
        facecolor=plt.rcParams['axes.facecolor'],
        edgecolor='None',
        linewidth=0,
        snap=False,
        transform=a.transAxes)
    a.patch.set_figure(fig)
    a.set_title('Custom patch')

img = []
for a in ax[:3]:
    img.append(a.imshow(data, extent=(0, 2, 0, 2), vmin=-10))
    for s in a.spines.values():
        s.set_bounds(0, 1.25)

img[1].set_clip_box(None)
img[1].set_clip_path(
    Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
    ax[1].transAxes)
ax[1].set_title('Custom clip path')

ax[3].set_title('No image, clip path')
ax[3].set_aspect('equal')
for s in ax[3].spines.values():
    s.set_bounds(0, 1.25)

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/302469/71317134-47436380-244a-11ea-9d8f-8dd2905a7f69.png)

The first `Axes` is normal and while the clip position is a bit inconsistent with the spines, they all fall within or under the spine (which being opaque black, covers that up). In the second `Axes`, where the clip path is set on the image directly, the top extends one pixel extra and the right is clipped a little early (maybe 0.5 pixel.) In the third `Axes`, the path is set as the background patch, and the image is clipped slightly differently on all four edges. I suspect this is because the _patch_ itself is clipped differently, which is why I put just a custom patch on the fourth `Axes` and no image. Comparing three and four, that seems to be the case for all sides except the right.

So while the patch changing position a bit might explain a few edge differences, it doesn't explain the second `Axes`, and I'm going to reopen this.

**Comment by greglucas** [comment]
I was just looking into some snapping related problems and decided to test your cases out here. It looks like the second axes  (of the most recent example) is now fixed? Here is the result I get with master:
![Figure_1](https://user-images.githubusercontent.com/12417828/88358643-fd4a9500-cd2c-11ea-9e10-501d9bf7b634.png)
There are still issues with aliasing in the third and fourth axes in that image though.

If you remove the `snap=False` from the patch, things look pretty good to me I think. Below is the image with snapping on by default.
![Figure_1_snapTrue](https://user-images.githubusercontent.com/12417828/88358689-32ef7e00-cd2d-11ea-88aa-c7905e6d27a6.png)

**Comment by QuLogic** [comment]
Indeed, it is snapping that seems to do this. I am mostly worried about the last case though, as it's the (likely, not tried this change on it yet) problem that manifests in Cartopy.
