### ISSUE TITLE
cannot import name 'ft2font' from 'matplotlib' / The baseline image directory does not exist. 

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#15951]
I would like to get matplotlib master and run the tests. Despite all the information found online, e.g., https://matplotlib.org/devel/index.html, I was not able to do so.

What I've tried:
```
git clone git@github.com:matplotlib/matplotlib.git
cd matplotlib
pip3 install . --user
pytest
```
This fails with
```
E   ImportError: cannot import name 'ft2font' from 'matplotlib' (/home/nschloe/software/matplotlib/source-nschloe/lib/matplotlib/__init__.py)
```
If instead of pytest I run
```
python3 -c "import matplotlib; matplotlib.test()"
```
I'm getting
```
E   OSError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.
```
I have no idea what's going wrong. Any hints?

**Comment by jklymak** [comment]
What I do is `conda install matplotlib; conda uninstall matplotlib; pip install -ve .`, making sure that `setup.cfg` is properly configured.  See https://discourse.matplotlib.org/t/step-by-step-to-installling-from-source-using-conda/20034/2

I'm going to close this with the friendly encouragement to get help for this on the discourse page:  https://discourse.matplotlib.org  If no one helps, please ping us on gitter: https://gitter.im/matplotlib/matplotlib
