### ISSUE TITLE
Unknown Border Appearing When Using pcolor/pcolormesh

### ISSUE THREAD

**Issue by TheCedarPrince** [matplotlib/matplotlib#16029]
### Bug report

**Bug summary**

The color pattern that appears when using imshow, shows along a `pcolor` grid for an unknown reason. Creates conflicting grid and coloring sequence. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(10, 10)
plt.pcolormesh(data, edgecolors="k", linewidth=2)
ax = plt.gca()
ax.set_aspect("equal")
plt.imshow(data)
plt.show()
```

**Actual outcome**

![error](https://user-images.githubusercontent.com/29561456/71497492-7f6dec00-2826-11ea-8ea9-2f9ba23bd72c.png)

**Expected outcome**

![success](https://user-images.githubusercontent.com/29561456/71497550-b512d500-2826-11ea-812f-79094603d058.png)

**Matplotlib version**
>
  * Operating system: Fedora 30 x86_64
  * Matplotlib version: 3.1.2
  * Matplotlib backend: TkAgg
  * Python version: 3.7.4
  * Other libraries: numpy==1.18.0

> Note: matplotlib==3.1.2 was installed via pip

**Comment by QuLogic** [comment]
There is no border; they're plotted on different boundaries. See the [`pcolormesh` documentation on the `X`/`Y` arguments](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.pcolormesh.html) vs. the [default extent for `imshow`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.imshow.html).

Though it seems `pcolormesh` does _not_ seem to mention anywhere that the default `X`/`Y` are `np.arange(len(dimension))`, and I think we should mention that.

**Comment by TheCedarPrince** [comment]
Hey @QuLogic - got it! After experimenting with the code and documentation more, I was able to get a working example of what I was expecting:

```python
import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(10, 10)

fig = plt.figure()
ax = fig.gca()
ax.pcolor(data, edgecolors='k', linewidths=2)

plt.show()
```

![success](https://user-images.githubusercontent.com/29561456/71539594-7a836800-290c-11ea-8b98-0b587d3dd281.png)

I can put a docs pull request in - would you be willing to review?

**Comment by dstansby** [comment]
@TheCedarPrince would be great to have a pull request, and I'd be happy to review it!

**Comment by TheCedarPrince** [comment]
Hey @dstansby - I have to admit, I am new to how to contribute to docs. How do I go about doing that here in MPL? If you can point me somewhere, I can go from there.
