### ISSUE TITLE
Remove some github labels

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#16030]
IMHO the following labels are not needed:

- `default changes` :  `API changes` / `API consistency` should be sufficient.
- <s>`has PR` - Is this needed? It can be seen in the comments of the PR.</s>
- <s>`Merge with single review?` I don't think we use this in our approval process.</s>
- `Not a blocker`: Every non-release-critical issue is that automatically.
- <s>`Path handling`:  Too specific `maintenance` / `API changes` should be sufficient.</s>
- `Py2-only`, `Py 2/3 compat`, `Py3k`: obsolete because we're Python 3 only.

**Comment by story645** [comment]
Merge with single review is I think part of the new PR process @anntzer proposed?
https://matplotlib.org/devdocs/devel/coding_guide.html#merging

**Comment by anntzer** [comment]
I've been using "has PR" to mark the issue list when skimming through it to see whether there's stuff that looks like low hanging fruits that could be easily fixed, without having to actually check the comments.
I think Path handling is about matplotlib paths, not pathlib paths.
Py2/3 labels should be kept until we completely close off the mpl2 branch (which is hopefully soon?)

**Comment by timhoffm** [comment]
Done.
