### ISSUE TITLE
Matplotlib is not showing image for Python3.5 and above. Solution to this problem is include the command plt.show() like this plt.imshow(im) plt.show()

### ISSUE THREAD

**Issue by senthilkumarIRTT** [matplotlib/matplotlib#16046]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
@senthilkumarIRTT Is this a bug report a request for help or something else?

Please use the heading only for a short summary and describe the issue in detail in the body.
