### ISSUE TITLE
Feature request: SplitMap Control for Plots in Jupyter

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/matplotlib#16064]
The ipyleaflet package has a very nice [SplitMap Control function](https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html) where you can turn a slider left and right to see different layers.
![split](https://user-images.githubusercontent.com/44469195/71644681-c0ee1380-2ccc-11ea-8099-25658ad09113.png)
My idea: 
The same for matplotlib.
Especially in fields like image processing it could be very nice to have a fast option to see the "previous/after" change.

One idea how to code could look like:
```python
%matplotlib inline
import matplotlib.pyplot as plt
fig1 = plt.figure()
plt.plot([1,2])
fig2 = plt.figure()
plt.plot([3,3])
## Here starts the new part:
control = SplitMapControl(left_layer=fig1, right_layer=fig2)
m.add_control(control)
```

**Comment by jklymak** [comment]
That sounds like a reasonable downstream package rather than a base feature?

**Comment by tacaswell** [comment]
I'm not sure how this could be done with `inline` which puts a static png (as a base64 encoded string) into the notebook.

If you have an interactive backend you can probably do this with the current cursor widget + 2 imshows + 2 clippings paths that are re-set as the cursor moves.
