### ISSUE TITLE
Issue with shading and layering in 3D-plots

### ISSUE THREAD

**Issue by khashabri** [matplotlib/matplotlib#16071]
### Bug report

The following code should show a cylinder that is on a plane. However, as obvious in the 3rd and the 4th image, the shading and layering of `matplotlib` are not applied correctly and the result looks strange. Using `zorder` didn't also solve that.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

# Help function to determine the cylinder plot data
def data_for_cylinder_along_z(center_x,center_y,center_z,radius,height_z):
    z = np.linspace(0, height_z, 50)
    theta = np.linspace(0, 2*np.pi, 50)
    theta_grid, z_grid=np.meshgrid(theta, z)
    x_grid = radius*np.cos(theta_grid) + center_x
    y_grid = radius*np.sin(theta_grid) + center_y
    z_grid = z_grid - height_z/2 + center_z
    return x_grid,y_grid,z_grid

# setting up a figure
fig = plt.figure(figsize=(10, 10))
ax = fig.gca(projection='3d')
ax.view_init(90, 0)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_xlim3d(-1, 1)
ax.set_ylim3d(-1, 1)
ax.set_zlim3d(-1, 1)

# plotting a plane
yy, zz = np.meshgrid([-0.5, 0.5], [-0.5, 0.5])
ax.plot_surface(0, yy, zz, color='yellow')

# plotting a cylinder
r = 0.1
Xc,Yc,Zc = data_for_cylinder_along_z(r, 0, 0, r, 1)
ax.plot_surface(Xc, Yc, Zc)

plt.show()
```

**Actual outcome**

![1](https://user-images.githubusercontent.com/50481847/71667816-f5161280-2d66-11ea-9616-9e702ae44261.png)
![2](https://user-images.githubusercontent.com/50481847/71667818-f7786c80-2d66-11ea-8402-2c5634b51d1d.png)
![3](https://user-images.githubusercontent.com/50481847/71667819-f9dac680-2d66-11ea-8f9f-df257d222723.png)
![4](https://user-images.githubusercontent.com/50481847/71667822-fba48a00-2d66-11ea-9f75-fda118473854.png)

**Expected outcome**
The plane should be **behind** the cylinder in all images and the cylinder must be shown.

**Matplotlib version**

  * Operating system: Ubuntu Linux 64-bit
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3

**Comment by anntzer** [comment]
This is essentially the same issue as https://github.com/matplotlib/matplotlib/issues/12620: we know about it, but basically can't fix it.
