### ISSUE TITLE
how to interact in a 3d polygraph?

### ISSUE THREAD

**Issue by Daemon1992** [matplotlib/matplotlib#16130]
And the way I did it in 2d, I found that sometimes in 3d it doesn't respond.And the event_handling in the example is all about 2d, may I ask whether 3d event processing can be supported like 2d.
can u give me some advice or examples. 

thank you.

version-3.1.1

**Comment by QuLogic** [comment]
This question is too vague; I do not understand what it is you are having trouble with. I suggest posting on the [Discourse](https://discourse.matplotlib.org/) and providing _much_ more information.

**Comment by jklymak** [comment]
Closing as not relevant to the issue tracker.  Please follow up on Discourse!
