### ISSUE TITLE
pp.hist parmeter 'density' does not scale data appropriately

### ISSUE THREAD

**Issue by jacobnrohan** [matplotlib/matplotlib#16147]
### Bug report

**Bug summary**

'density' argument in pp.hist() does not scale data appropriately

**Code for reproduction**

```python
print(matplotlib.__version__)
a = np.array([2.7871902, -0.16587533, 2.400487, -0.22041278, 3.5801802, -0.458245, 1.7463026, -0.29266447, 1.4848666,
-0.13430892, 3.2835798, -0.027157811, 0.55700374, -0.12730916, 0.3448488, -0.3222668, 0.22995274, -0.031041186,
0.1893434, -0.01208617, 2.104571, -0.009364999, 0.062176008, -0.045246653, 0.031220708,-0.04697927,0.02657558,
-0.031277005,0.01713127,-0.031898744,0.012391248,-0.008699492,0.007395051,-0.0067330534,0.005730991,-0.004206775,
0.0037450397,-0.000804145,0.0025498285,-0.0028463008,])
b = pp.hist(a, density=True)
print(b[0])
print(b[1])
```

**Actual outcome**

```
3.1.1
[0.43333723 1.54763297 0.06190532 0.         0.06190532 0.06190532
 0.06190532 0.06190532 0.06190532 0.12381064]
[-0.458245   -0.05440248  0.34944004  0.75328256  1.15712508  1.5609676
  1.96481012  2.36865264  2.77249516  3.17633768  3.5801802 ]
```

![Screenshot from 2020-01-07 15-09-30](https://user-images.githubusercontent.com/31712481/71929648-b6fe6180-315f-11ea-9ca7-a102e77c0941.png)

**Expected outcome**

all values on plot should be <1.0

**Matplotlib version**

  * Operating system: Debian GNU/Linux 9 (stretch) 64-bit
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.5 installed via anaconda3, default channels
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

**Comment by jklymak** [comment]
```
print(sum(b[0]*np.diff(b[1])))
1.0
```

https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html
which is purposely consistent with:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html

> If True, the first element of the return tuple will be the counts normalized to form a probability density, i.e., the area (or integral) under the histogram will sum to 1. 

Though looking at that, I suppose saying it will "sum to 1" would be clearer as "will integrate to 1"

**Comment by jklymak** [comment]
@jacobnrohan let us know if the change in #16149 makes more sense.

**Comment by jacobnrohan** [comment]
Yes the change is clear. From [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html), numpy.histogram, "it is not a probability mass function" when density=True.

Having a probability_mass_function=True argument would be helpful.
