### ISSUE TITLE
How do I get the point coordinates (xyz) on a 3d graph?

### ISSUE THREAD

**Issue by Daemon1992** [matplotlib/matplotlib#16156]
### Bug report

**Bug summary**
I've created a three-dimensional line graph, and I want to click on a point in the graph, and there's a response event.The matplotlib example doesn't seem to support 3d event response very well.
I can't get the right z coordinate of the selected point..

**Code for reproduction**
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle
import numpy as np
from numpy.random import rand
np.random.seed(19680801)

def eventHandleSet():
    print("eventHandle set")
    def onpick1(event):
        ind = event.ind
        print("clikced point index : ",xs[ind],ys[ind],zs[ind])
        if isinstance(event.artist, Line2D):
            thisline = event.artist
            xdata = thisline.get_xdata()
            ydata = thisline.get_ydata()
            ind = event.ind
            print('onpick1 line:', np.column_stack([xdata[ind], ydata[ind]]))
        elif isinstance(event.artist, Rectangle):
            patch = event.artist
            print('onpick1 patch:', patch.get_path())
    fig.canvas.mpl_connect('pick_event', onpick1)

    # def onclick(event):
    #     print('%s click: button=%d, x=%d, y=%d,z=%d, xdata=%f, ydata=%f, zdata=%f'%
    #              ('double' if event.dblclick else 'single', event.button,
    #                event.x, event.y, event.z, event.xdata, event.ydata, event.zdata))

    # cid = fig.canvas.mpl_connect('button_press_event', onclick)

def randrange(n, vmin, vmax):
    return (vmax - vmin)*np.random.rand(n) + vmin

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
n = 15

for m, zlow, zhigh in [('o', -50, -25), ('^', -30, -5)]:
    xs = randrange(n, 23, 32)
    ys = randrange(n, 0, 100)
    zs = randrange(n, zlow, zhigh)
    ax.scatter(xs, ys, zs, marker=m,picker=True)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

eventHandleSet()

plt.show()

**Actual outcome**

![图片](https://user-images.githubusercontent.com/17067217/71943453-b1eef000-31fb-11ea-8f65-025ba1816faf.png)
As you can see from the diagram, the z coordinate of the point in the red circle is wrong.It should be between -40 and -50, not -12. ("pick_event")

![图片](https://user-images.githubusercontent.com/17067217/71943607-288bed80-31fc-11ea-9e20-66764f5cfaa0.png)
You can see from the graph that you can't get the z coordinates by clicking on the event, only the x and y coordinates.  ("button_press_event")

**Matplotlib version**

  * Operating system: win7 64bit
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3.7.3
  * Jupyter version (if applicable):
  * Other libraries: qt5.9.8

**Comment by jgwilliams17** [comment]
Hi @Daemon1992, I'm having the same issue you had last year (coordinates being returned are not the 3D coordinates displayed on the graph). Did you manage to resolve this?

**Comment by acloudinmybluesky** [comment]
Hi @Daemon1992
Hi @jgwilliams17
I also have the same problem (the coordinates returned are mostly wrong). Did you manage to find a solution?

**Comment by Rickfdalton** [comment]
I came across the exact same issue, any remedies??

**Comment by stefanie-theodora** [comment]
I'm having the same problem, were you able to find a fix?

**Comment by jklymak** [comment]
It is not possible to uniquely get the coordinates in a 3d plot when they are projected onto a 2d screen.

**Comment by kdschlosser** [comment]
I am really close to getting the proper coordinates. It is off a little bit and how far off it is depends on the focal distance and the roll, pitch and yaw. Now I am not saying that it would be accurate to a fraction but it can be accurate to a whole integer. It does allow for repositioning of the elements in a scatter plot. I have found when doing the repositioning it is by far easier to handle by using trigger keys to lock to moving only along a specific axis. 

Here is the code for what I have so far. This uses the wxPython backend but the same kind of thing would apply for other backends as well I am sure.

If someone else could possibly lend a hand to sort out the small deviation that can occur depending on where the roll, pitch and yaw are that would be a big help. 

<details>

<summary>click me for the code</summary>

Read the top as it will give instruction on use.
I have modified the default mouse handling

"""
Press and hold `x`, `y` or `z` and then click on one of the points in the plot
and drag the point along the axis noted by the key that is being held down.

Left click and drag rotates the plot.
Right click and drag pans the plot.
Mouse wheel zooms the plot.

Code was added to remove the flicking that was seen when the plot is redrawn.
"""

import wx
import matplotlib


matplotlib.use('WXAgg')


from matplotlib.backends.backend_wxagg import (  # NOQA
    FigureCanvasWxAgg as FigureCanvas
)
from matplotlib.backends.backend_wxagg import (  # NOQA
    NavigationToolbar2WxAgg as NavigationToolbar
)
from mpl_toolkits.mplot3d.art3d import Line3D, Path3DCollection  # NOQA
from mpl_toolkits.mplot3d import axes3d  # NOQA
from matplotlib.backend_bases import ResizeEvent  # NOQA
from mpl_toolkits.mplot3d.axes3d import _Quaternion  # NOQA
import matplotlib.pyplot  # NOQA
import numpy as np  # NOQA


class Canvas(FigureCanvas):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.Bind(wx.EVT_ERASE_BACKGROUND, self._on_erase_background)

    # bypass erasing the background when the plot is redrawn.
    # This helps to eliminate the flicker that is seen when a redraw occurs.
    # the second piece needed to eliminate the flicker is seen below
    def _on_erase_background(self, _):
        pass

    # override the _on_paint method in the canvas
    # this is done so double buffer is used which eliminates the flicker
    # that is seen when the plot redraws
    def _on_paint(self, event):
        drawDC = wx.BufferedPaintDC(self)
        if not self._isDrawn:
            self.draw(drawDC=drawDC)
        else:
            self.gui_repaint(drawDC=drawDC)
        drawDC.Destroy()

    # override the _on_size method in the canvas
    def _on_size(self, event):
        self._update_device_pixel_ratio()
        sz = self.GetParent().GetSizer()
        if sz:
            si = sz.GetItem(self)
        else:
            si = None

        if sz and si and not si.Proportion and not si.Flag & wx.EXPAND:
            size = self.GetMinSize()
        else:
            size = self.GetClientSize()
            size.IncTo(self.GetMinSize())

        if getattr(self, "_width", None):
            if size == (self._width, self._height):
                return

        self._width, self._height = size
        self._isDrawn = False

        if self._width <= 1 or self._height <= 1:
            return

        dpival = self.figure.dpi

        if wx.Platform != '__WXMSW__':
            scale = self.GetDPIScaleFactor()
            dpival /= scale

        winch = self._width / dpival
        hinch = self._height / dpival
        self.figure.set_size_inches(winch, hinch, forward=False)

        self.Refresh(eraseBackground=False)
        ResizeEvent("resize_event", self)._process()  # NOQA
        self.draw_idle()


# monkey patch the _on_move method for Axes3D
# this is done to change the handling of the right mouse button.
# the right mouse button pans the plot instead of zooming.
# The mouse wheel is used to zoom instead (as it should be)
def _on_move(self, event):
    if not self.button_pressed or event.key:
        return

    if self.get_navigate_mode() is not None:
        return

    if self.M is None:
        return

    x, y = event.xdata, event.ydata

    if x is None or event.inaxes != self:
        return

    dx, dy = x - self._sx, y - self._sy
    w = self._pseudo_w
    h = self._pseudo_h

    if self.button_pressed in self._rotate_btn:
        if dx == 0 and dy == 0:
            return

        style = matplotlib.rcParams['axes3d.mouserotationstyle']
        if style == 'azel':
            roll = np.deg2rad(self.roll)

            delev = (-(dy / h) * 180 * np.cos(roll) +
                     (dx / w) * 180 * np.sin(roll))

            dazim = (-(dy / h) * 180 * np.sin(roll) -
                     (dx / w) * 180 * np.cos(roll))

            elev = self.elev + delev
            azim = self.azim + dazim
            roll = self.roll
        else:
            q = _Quaternion.from_cardan_angles(
                *np.deg2rad((self.elev, self.azim, self.roll)))

            if style == 'trackball':
                k = np.array([0, -dy / h, dx / w])
                nk = np.linalg.norm(k)
                th = nk / matplotlib.rcParams['axes3d.trackballsize']
                dq = _Quaternion(np.cos(th), k * np.sin(th) / nk)
            else:  # 'sphere', 'arcball'
                current_vec = self._arcball(self._sx / w, self._sy / h)
                new_vec = self._arcball(x / w, y / h)
                if style == 'sphere':
                    dq = _Quaternion.rotate_from_to(current_vec, new_vec)
                else:  # 'arcball'
                    dq = (_Quaternion(0, new_vec) *
                          _Quaternion(0, -current_vec))

            q = dq * q
            elev, azim, roll = np.rad2deg(q.as_cardan_angles())

        vertical_axis = self._axis_names[self._vertical_axis]

        self.view_init(elev=elev, azim=azim, roll=roll,
                       vertical_axis=vertical_axis, share=True)

        self.stale = True

    elif self.button_pressed in self._zoom_btn:
        px, py = self.transData.transform([self._sx, self._sy])
        self.start_pan(px, py, 2)
        self.drag_pan(2, None, event.x, event.y)
        self.end_pan()

    self._sx, self._sy = x, y
    self.get_figure(root=True).canvas.draw_idle()


setattr(axes3d.Axes3D, '_on_move', _on_move)


class Frame(wx.Frame):
    def __init__(self):
        self.key = None
        self.selected_object = None
        self.button_held = False
        self.had_motion = False
        self.object_tooltip = None

        self.wires = []
        self.artists_mapping = {}

        self.data = [
            [10, 20, -30, 'o'],
            [15, 15, 0, 'o'],
            [20, 15, -20, 'o'],
            [100, 50, 25, 'o'],
            [100, 50, -10, 'o'],
            [2, 0, 0, 'o'],
            [5, 20, -30, 'o']

        ]

        self.lines = [
            [[10, 15], [20, 15], [-30, 0], 3],
            [[15, 20], [15, 15], [0, -20], 3],
            [[100, 100], [50, 50], [25, -10], 1],
            [[2, 5], [0, 20], [0, -30], 2],
        ]

        super().__init__(None, size=(1000, 700))
        panel = wx.Panel(self)

        v_sizer = wx.BoxSizer(wx.VERTICAL)
        h_sizer = wx.BoxSizer(wx.HORIZONTAL)

        self.fig = matplotlib.pyplot.figure()

        ax = self.axes = self.fig.add_subplot(projection='3d')
        ax.autoscale(True)

        for line in self.data:
            obj = ax.scatter(*line[:-1], marker=line[-1], picker=True)
            self.artists_mapping[obj] = line

        for line in self.lines:
            wire = Line3D(*line[:-1], linewidth=line[-1], picker=True)
            ax.add_line(wire)
            self.wires.append(wire)

        # Set the axis labels
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_zlabel('z')

        self.canvas = Canvas(panel, wx.ID_ANY, self.fig)

        # MouseEvent
        self.canvas.mpl_connect("button_press_event", self.on_press)
        self.canvas.mpl_connect("motion_notify_event", self.on_motion)
        self.canvas.mpl_connect("button_release_event", self.on_release)
        self.canvas.mpl_connect("scroll_event", self.on_mouse_scroll)

        # LocationEvent
        self.canvas.mpl_connect("figure_enter_event", self.on_figure_enter)
        self.canvas.mpl_connect("figure_leave_event", self.on_figure_leave)
        self.canvas.mpl_connect("axes_enter_event", self.on_axes_enter)
        self.canvas.mpl_connect("axes_leave_event", self.on_axes_leave)

        # KeyEvent
        self.canvas.mpl_connect("key_press_event", self.on_key_press)
        self.canvas.mpl_connect("key_release_event", self.on_key_release)

        # CloseEvent
        self.canvas.mpl_connect("close_event", self.on_close)

        # DrawEvent
        self.canvas.mpl_connect("draw_event", self.on_draw)

        # PickEvent
        self.canvas.mpl_connect("pick_event", self.on_pick)

        # ResizeEvent
        self.canvas.mpl_connect("resize_event", self.on_resize)

        toolbar = NavigationToolbar(self.canvas)
        toolbar.Realize()

        h_sizer.Add(self.canvas, 1, wx.EXPAND | wx.ALL, 5)
        v_sizer.Add(h_sizer, 1, wx.EXPAND)
        v_sizer.Add(toolbar, 0, wx.LEFT | wx.EXPAND)

        panel.SetSizer(v_sizer)
        toolbar.update()

        wx.CallAfter(self.canvas.draw)

    def on_close(self, evt):
        pass

    def on_draw(self, evt):
        pass

    def on_key_press(self, evt):
        key = evt.key
        if isinstance(key, str):
            self.key = key.lower()

    def on_key_release(self, evt):
        key = evt.key
        if isinstance(key, str) and key.lower() == self.key:
            self.key = None

    def on_pick(self, evt):
        if isinstance(evt.artist, Path3DCollection):
            self.selected_object = evt.artist
            self.axes.button_pressed = None

            # old_pos = self.artists_mapping[self.selected_object]
            # x, y, z = self.location_coords(evt.mouseevent.xdata,
            #                                evt.mouseevent.ydata)
            # print(old_pos)
            # print(x, y, z)
            # print()

    def on_resize(self, evt):
        pass

    def on_mouse_scroll(self, evt):
        x, y = evt.xdata, evt.ydata

        if x is None or evt.inaxes != self.axes:
            return

        if not hasattr(self.axes, '_sx') or not hasattr(self.axes, '_sy'):
            self.axes._sx, self.axes._sy = x, y

        h = self.axes._pseudo_h  # NOQA

        scale = h / (h + (evt.step / 100))
        self.axes._scale_axis_limits(scale, scale, scale)  # NOQA

        self.axes.get_figure(root=True).canvas.draw_idle()

    def on_figure_enter(self, evt):
        pass

    def on_figure_leave(self, evt):
        pass

    def on_axes_enter(self, evt):
        pass

    def on_axes_leave(self, evt):
        pass

    def on_press(self, event):
        if event.button == 1:
            # left button
            if event.dblclick:
                # print(self.selected_object)
                pass
            elif self.selected_object is not None:
                self.button_held = True
                self.axes.button_pressed = None

        elif event.button == 2:
            # middle button
            pass
        elif event.button == 3:
            # right button
            # open context menu
            self.had_motion = False

        elif event.button == 8:
            # forward
            pass
        elif event.button == 9:
            # back
            pass

    def location_coords(self, xv, yv):
        p1, pane_idx = self.axes._calc_coord(xv, yv, None)  # NOQA
        xs = self.axes.format_xdata(p1[0])
        ys = self.axes.format_ydata(p1[1])
        zs = self.axes.format_zdata(p1[2])

        def get_int(val):
            if val.startswith('−'):
                return int(-float(val[1:]))
            else:
                return int(float(val))

        return get_int(xs), get_int(ys), get_int(zs)

    def on_motion(self, event):
        if event.button == 3:
            self.had_motion = True
            # Start the pan event with pixel coordinates

            x, y = event.xdata, event.ydata
            # In case the mouse is out of bounds.
            if x is None or event.inaxes != self:
                return

            self.axes.button_pressed = None

            if not hasattr(self.axes, '_sx') or not hasattr(self.axes, '_sy'):
                self.axes._sx, self.axes._sy = event.xdata, event.ydata

            px, py = self.axes.transData.transform([self.axes._sx, self.axes._sy])  # NOQA
            self.axes.start_pan(px, py, 2)
            # pan view (takes pixel coordinate input)
            self.axes.drag_pan(2, None, event.x, event.y)
            self.axes.end_pan()

            self.axes._sx, self.axes._sy = event.xdata, event.ydata
            # Always request a draw update at the end of interaction
            self.axes.get_figure(root=True).canvas.draw_idle()

        elif self.button_held and self.selected_object is not None:
            if self.key not in ('x', 'y', 'z'):
                return

            old_pos = self.artists_mapping[self.selected_object]
            try:
                x, y, z = self.location_coords(event.xdata, event.ydata)
            except TypeError:
                return

            if x == z:
                return

            old_x, old_y, old_z = old_pos[:-1]

            x_diff = x - old_x
            y_diff = y - old_y
            z_diff = z - old_z

            x_diff = min(1, (max(-1, x_diff)))
            y_diff = min(1, (max(-1, y_diff)))
            z_diff = min(1, (max(-1, z_diff)))

            # self.axes.autoscale(False)

            for wire in self.wires:
                xs, ys, zs = wire.get_data_3d()

                if xs[0] == old_x and ys[0] == old_y and zs[0] == old_z:
                    if self.key == 'x':
                        xs[0] += x_diff
                    elif self.key == 'y':
                        ys[0] += y_diff
                    elif self.key == 'z':
                        zs[0] += z_diff

                    wire.set_data_3d(xs, ys, zs)

                elif xs[1] == old_x and ys[1] == old_y and zs[1] == old_z:
                    if self.key == 'x':
                        xs[1] += x_diff
                    elif self.key == 'y':
                        ys[1] += y_diff
                    elif self.key == 'z':
                        zs[1] += z_diff

                    wire.set_data_3d(xs, ys, zs)

            if self.key == 'x':
                old_pos[0] += x_diff
                self.selected_object._offsets3d[0][0] += x_diff  # NOQA
            elif self.key == 'y':
                old_pos[1] += y_diff
                self.selected_object._offsets3d[1][0] += y_diff  # NOQA
            elif self.key == 'z':
                old_pos[2] += z_diff
                self.selected_object._offsets3d[2][0] += z_diff  # NOQA

            self.axes.get_figure(root=True).canvas.draw_idle()

            height = self.canvas.GetSize()[1]
            x = round(x, 2)
            y = round(y, 2)
            z = round(z, 2)
            label = f'x: {x} y: {y} z: {z}'

            size = self.canvas.GetTextExtent(label)
            if self.object_tooltip is None:
                self.object_tooltip = wx.StaticText(self.canvas, wx.ID_ANY,
                                                    label=label, size=size,
                                                    pos=(0, height - size[1]))
            else:
                self.object_tooltip.SetLabel(label)
                self.object_tooltip.SetPosition((0, height - size[1]))
                self.object_tooltip.SetSize(size)

    def on_release(self, event):
        if self.object_tooltip is not None:
            self.object_tooltip.Destroy()
            self.object_tooltip = None

        if event.button == 3 and not self.had_motion:
            menu = wx.Menu()

            wx.MenuItem()

            menu.Append(wx.ID_ANY, 'menu item 1')
            menu.Append(wx.ID_ANY, 'menu item 2')
            menu.Append(wx.ID_ANY, 'menu item 3')
            menu.AppendSeparator()
            menu.Append(wx.ID_ANY, 'menu item 4')
            menu.Append(wx.ID_ANY, 'menu item 5')
            menu.AppendSeparator()

            sub_menu = wx.Menu()
            sub_menu.Append(wx.ID_ANY, 'sub menu item 1')
            sub_menu.Append(wx.ID_ANY, 'sub menu item 2')
            sub_menu.Append(wx.ID_ANY, 'sub menu item 3')
            sub_menu.AppendSeparator()
            sub_menu.Append(wx.ID_ANY, 'sub menu item 4')
            sub_menu.Append(wx.ID_ANY, 'sub menu item 5')

            menu.AppendSubMenu(sub_menu, 'menu item 6')

            x = event.x
            y = event.y

            height = self.canvas.GetSize()[1]

            y = abs(y - height)

            self.canvas.PopupMenu(menu, x, y)
        else:
            self.selected_object = None
            self.button_held = False

        self.had_motion = False


class App(wx.App):
    def OnInit(self):
        frame = Frame()
        frame.Show()
        return True


if __name__ == "__main__":
    app = App()
    app.MainLoop()
</details>
