### ISSUE TITLE
How to add points to a 3d polyline graph dynamically?

### ISSUE THREAD

**Issue by Daemon1992** [matplotlib/matplotlib#16157]
### Bug report

**Bug summary**
How do you dynamically insert three-dimensional coordinates that are constantly being generated into the diagram?

**Matplotlib version**

  * Operating system:win7
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3.7.3
  * Jupyter version (if applicable):
  * Other libraries: qt5.9.8

**Comment by jklymak** [comment]
Can you ask this on discourse.matplotlib.org ? Its not really an issue, but if you find that the solution you come up with should have been documented better, please feel free to open a new issue. Thanks!
