### ISSUE TITLE
I click the mouse many times before I respond to the event under pyqt5

### ISSUE THREAD

**Issue by Daemon1992** [matplotlib/matplotlib#16158]
### Bug report

**Bug summary**

I use pyqt5 as my UI, and when I click on a 3d mouse click, it takes several clicks to respond to an event.I ran the matplotlib example, and the click-point response was fast.I don't know if pyqt is the cause of this problem.

**Code for reproduction**

```python
from testForm import Ui_Form
from PyQt5.QtWidgets import QApplication,QWidget,QGridLayout
import sys,time
import numpy as np

import matplotlib
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

class Figure_Canvas(FigureCanvas):
    def __init__(self,parent=None,width=3.9,height=2.7,dpi=100):
        self.fig=Figure(figsize=(width,height),dpi=100)
        super(Figure_Canvas,self).__init__(self.fig)
        self.ax=self.fig.add_subplot(111)

class ImgDisp(QWidget, Ui_Form):
    ptCount = 1
    def __init__(self):
        super(ImgDisp,self).__init__()
        self.setupUi(self)

    def Init_Widgets(self):
        print(matplotlib.get_backend())
        self.PrepareSamples()
        self.dram3dline()

    def PrepareSamples(self):
        self.SurfFigure = Figure_Canvas()
        self.SurfFigureLayout = QGridLayout(self.groupBox)
        self.SurfFigureLayout.addWidget(self.SurfFigure)
        self.axes3d = self.SurfFigure.fig.gca(projection='3d')

    def dram3dline(self):
        self.x = np.linspace(0, 100, 10)
        self.y = np.sin(self.x)
        self.z = np.cos(self.x)
        self.axes3d.plot(self.x, self.y, self.z, marker = 'o',color='green',picker=True)
        self.axes3d.set_xlabel('X', color='r', size=15)
        self.axes3d.set_ylabel('Y', color='r', size=15)
        self.axes3d.set_zlabel('Z', color='r', size=15)
        def onpick2(event):
            ind = event.ind
            print("point :",self.x[ind],self.y[ind],self.z[ind])

        self.SurfFigure.fig.canvas.mpl_connect('pick_event', onpick2)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = ImgDisp()
    ui.Init_Widgets()
    ui.show()
    sys.exit(app.exec_())

```

Ui_Form It only has one groubox.Groupbox as a canvas for matplotlib.

**Matplotlib version**

  * Operating system:win7
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3.7.3
  * Jupyter version (if applicable):
  * Other libraries: qt5.9.8

**Comment by timhoffm** [comment]
Can you please provide a self-contained example? We cannot test this. Either provide Ui_Form, or preferably, create a small window in code.

**Comment by Daemon1992** [comment]
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 534)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))

/////////////////////////////////////////////////////////////////
Multiple clicks to pick up the scatter.

**Comment by Daemon1992** [comment]
![图片](https://user-images.githubusercontent.com/17067217/72032239-b97cca80-32c9-11ea-9d64-3e8770857470.png)

Another problem, I implemented the zoom function, as shown in the figure, the polyline is beyond the canvas.The actual excess should not be shown

**Comment by timhoffm** [comment]
The picking problem is actually bug/missing feature of 3D plots.

`Line3D` does not reimplement the method `contains()`, it just reuses the 2D method, which obviously cannot work in 3D.

**Comment by anntzer** [comment]
Actually it seems to work for me?
In fact the inherited contains() will work, somewhat by accident in this case -- for the purposes of drawing, the line's "data" is set to the 2D projected coordinates, so the check will work...
