### ISSUE TITLE
ENH: Printing option and "crosshair" for the backends

### ISSUE THREAD

**Issue by jakobjakobson13** [matplotlib/matplotlib#16180]
Dear developers,

you are doing a great job with the matplotlib package, but I would like to propose two minor improvements:

- An optional "crosshair" for the graphic backend. Even though you get the information in the lower left corner, I would find a tool that shows a vertical line to the x-axis and a horizontal line to the y-axis according to the current cursor position quite useful. Possible applications would be that you have multiple stacked 1D-spectra and you want to check easily if their maxima/minima or something else falls on the same x-value without pointing each point out.
- An print button on the graphical backend. That would saves you the additional step of printing the file out of the file manager (which I can't do anyway) or opening it with some preview program and print it from the preview program.

If you don't agree to this suggestions, that's fine for me and you can close the bug report without any further discussion.

**Comment by jklymak** [comment]
For the first, see https://matplotlib.org/3.1.1/gallery/misc/cursor_demo_sgskip.html.  maybe mplcursors?  

For the second, printing to an actual printer across multiple platforms is a morass that I dont' think we need to wade into.

**Comment by timhoffm** [comment]
> Printing to an actual printer across multiple platforms is a morass that I dont' think we need to wade into.

I totally agree with that. Please write the content to a file format of your choice and use a suitable viewer of your choice to print the content.

**Comment by ImportanceOfBeingErnest** [comment]
Possible actionable item here: The [cursor demo](https://matplotlib.org/3.1.1/gallery/misc/cursor_demo_sgskip.html) should mention the option to use [`matplotlib.widgets.Cursor`](https://matplotlib.org/3.1.1/api/widgets_api.html?highlight=widgets#matplotlib.widgets.Cursor).

**Comment by timhoffm** [comment]
Cursor demo is rewritten in #15644. I will check how to integrate that.

**Comment by jakobjakobson13** [comment]
Thanks for addressing this bug report so quickly. I'm fine with your responses and if you want to close the bug report, go ahead.
