### ISSUE TITLE
BUG: unrecognised argument "ecolor" gets passed silently in plt.bar()

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#16186]
### Bug report

**Bug summary**

`plt.bar` silently accepts `ecolor` as a kwarg, but does nothing with it.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
x = y = list(range(10))

# correct
plt.bar(x, y, edgecolor="red")

# correct
plt.bar(x, y, ec="red")

# correct: unrecognised kwarg raises AttributeError
plt.bar(x, y, edge_color="red")

# incorrect: unrecognised kwarg "ecolor" is passed silently with no visible effect
plt.bar(x, y ecolor="red")
```

**Actual outcome**
(precision, I present here what happens when each `plt.bar` line is run separately)

![edgecolor_bug](https://user-images.githubusercontent.com/14075922/72204188-795a4b00-3475-11ea-902e-11a03b4d7bbe.png)
x2
then
```python
AttributeError: 'Rectangle' object has no property 'edge_color'
```
then
![noedgecolor_bug](https://user-images.githubusercontent.com/14075922/72204183-6e071f80-3475-11ea-84ab-b8bcfe02d483.png)

**Expected outcome**

Either raise `AttributeError` or accept the argument as an additional alias to `edgecolor`, whichever is most consistent with existing apis.

**Matplotlib version**

  * Operating system: MacOs (10.15.2)
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.5
  * Jupyter version (if applicable): JupyterLab 1.2.4
  * Other libraries: none

Installed python and mpl via conda's `default` channel.

**Comment by jklymak** [comment]
We don’t tend to guard all our kwargs.  I’m not sure this typo merits extra protection.

**Comment by neutrinoceros** [comment]
Thing is that it's not a _typo_ per say, some functions do use "ecolor" as a kwarg. I realise as I'm writing that it's _not_ meant mean "edgecolor" but rather "error color" (as in `plt.errorbar()`) but given the proximity in naming, it got me confused so I can imagine other users may too.

**Comment by timhoffm** [comment]
IMHO we should check all arguments at some level (errors should never pass silently).

**Comment by neutrinoceros** [comment]
my point exactly :)

**Comment by timhoffm** [comment]
Actually, `ecolor` is a valid argument. It specifies the color of error bars. It doesn't have an effect on your plot since errorbars are missing.

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.bar.html

I'm closing this as it's correctly implemented. We do not protect against use of valid kwargs that *currently* do not take effect due to other settings (e.g. we also wouldn't warn on setting facecolor if a patch was completely transparent).

**Comment by neutrinoceros** [comment]
Fair enough. Thanks !
