### ISSUE TITLE
hist demo appears to incorrectly mention `normed` and something odd about `density` as well.

### ISSUE THREAD

**Issue by joelmiller** [matplotlib/matplotlib#16185]
Looking at the webpage:

https://matplotlib.org/3.1.1/gallery/statistics/histogram_features.html

It claims that "this demo shows a few optional features:"

Among these is:

"The normed flag, which normalizes bin heights so that the integral of the histogram is 1. The resulting histogram is an approximation of the probability density function."

In fact, it is not shown (`density=1` is used instead).  

While I'm at it, `density` is listed as a boolean on 

https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html

So it's not clear to me why `density=True` isn't being used there.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, totally. Would you like to file a pull request with the respective changes? (The file that needs to be changed is https://github.com/matplotlib/matplotlib/blob/master/examples/statistics/histogram_features.py)
