### ISSUE TITLE
pdfTex slows down mpl.animation.FuncAnimation.save()

### ISSUE THREAD

**Issue by MrRobinhq** [matplotlib/matplotlib#16182]
### Bug report

**Bug summary**

When saving a (3d) animation which contains text elements typeset in Latex with matplotlib.animation.FuncAnimation.save(), the process gets slowed down significantly by pdfTex after a certain amount of processed frames. This seems to happen as soon as the number of animated frames exceeds a certain, inconsistent threshold. It doesn't seem to matter which ffmpeg movie writer (pipe or file based) is used.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from matplotlib.animation import FuncAnimation
import matplotlib as mpl
mpl.rcParams['text.usetex'] = True
plt.style.use('seaborn-whitegrid')

fig, ax = plt.subplots(1, 1, figsize = (10, 10), subplot_kw = {'projection':'3d'})
ax.set(xlabel = '$x$', ylabel = '$y$', zlabel = '$z$')

data = np.random.randn(10000, 3)
point_red = ax.plot([data[:, 0][0]], [data[:, 1][0]], [data[:, 2][0]], marker = 'o', \
                                  color = 'red', alpha = 0.9, animated = True)[0]
line_red = ax.plot(data[:, 0], data[:, 1], data[:, 2], color = 'red', lw = 0.8, alpha = 0.9)[0]
text = ax.text2D(0.1, 0.8, f'$t={0}$', transform = fig.transFigure)

def update_frame(frame):

    line_red.set_data_3d(data[:, 0][:frame], data[:, 1][:frame], data[:, 2][:frame])
    point_red.set_data_3d([data[:, 0][frame]], [data[:, 1][frame]], [data[:, 2][frame]])
    text.set_text('$t=$' + f' {frame}')

    return [fig]

def save_prog(curr_frame, total_frame):
    print(f'Saving frame {curr_frame}/{total_frame}.', '\n')

writer = mpl.animation.FFMpegWriter(fps = 50)
frames = np.arange(10000)

anim = FuncAnimation(fig, func = update_frame, frames = frames, blit = True)
anim.save('fname.avi', progress_callback = save_prog, dpi = 150, writer = writer)
```

**Actual outcome**

The saving process is fast (~20 frames/s) in the beginning, but after a certain amount of processed frames it slows down substantially to around 1 frame every 3 seconds. At the same time, a pdfTex thread is started and closed for every processed frame (observed via Task Manager). I discovered this while trying to save a more complex animation, where it started to slow down only after around 3500 saved frames (passing a lower number of frames to mpl.animation.FuncAnimation() resulted in the slow down never occurring). Interrupting the script at different points prior to this threshold had no effect on the resulting animation (other than cutting it off prematurely of course), it still displayed the animated text properly; the slow down also never happened on the same processed frame (sometimes it didn't occur at all); this inconsistent behaviour leads me to believe this is a bug (the pdfTex thread doesn't seem to be required in order to render the animation).

**Expected outcome**

Time to save animation only depends on animation complexity and number of frames.

**Matplotlib version**

  * Operating system: Windows 10 Home 1809
  * Matplotlib version: 3.1.2 (installed via pip3 19.3.1)
  * Matplotlib backend: TkAgg
  * Python version: 3.7.6
  * Ipykernel version: 5.1.3 (installed via pip3 19.3.1)
  * pdfTex version: 1.40.19  (installed via MiKTeX 2.9)

**Comment by tacaswell** [comment]
I'm sorry this fell through the cracks when initially reported.

When using `mpl.rcParams['text.usetex'] = True` we start a latex process for each `Text` object which can be slow (particularly on windows) at it involves spawning at two new (sub)processes.  To mitigate this, we cache the results so the second (or Nth) time you ask for the same text to be rendered we can skip the sub-processes and use the cached result.  The 3sec / frame may be the _actual_ speed of rendering these frames on your system, but if you hit the cache it will seem faster.

If you use `mpl.rcParams['text.usetex'] = False` we will internally render the math text and avoid the sub-process calls.

I am going to leave this closed because, as frustrating as it is, this is evidence of the tex cache working as expected.
