### ISSUE TITLE
Typo in doc of angle_spectrum

### ISSUE THREAD

**Issue by mocquin** [matplotlib/matplotlib#16190]
In matplotlib 3.0.3, I noticed the following confusing doc of angle_spectrum, in the window argument : 

<img width="528" alt="Capture d’écran 2020-01-12 à 12 19 31" src="https://user-images.githubusercontent.com/36188368/72218031-74a99b80-3536-11ea-8f2d-ad9e2c5d73a2.png">

Signature says "window=None", while docstring says "window=mlab.window_hanning".

Am I missing something ?

For notebook reproduction :
```python 
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1)
ax.angle_spectrum?
```

Cheers

**Comment by jklymak** [comment]
None defaults to mlab.hanning.  We use None to specify whether the user explicitly changed the kwarg or not.

**Comment by timhoffm** [comment]
This usage of None is quite common to prevent defining defaults in multiple places.

The call signature is not present anymore in more recent docs:
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.angle_spectrum.html
