### ISSUE TITLE
pcolormesh with shading=gouraud gives error when saved as eps

### ISSUE THREAD

**Issue by LucaLanzilao** [matplotlib/matplotlib#16217]
Bug summary
I have a pcolormesh that has shading='gouraud', and I am trying to save it to an .eps. If I save the image as .png everything works fine, but when I save it as .eps it gives error. A similar issue was already open and then closed in the past. 

Code for reproduction
import matplotlib.pyplot as plt
import numpy as np
plt.pcolormesh(np.random.randn(10,10), shading='gouraud')
plt.gcf().savefig('test.eps')

Matplotlib version
matplotlib 3.1.1
Python 3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

**Comment by LucaLanzilao** [comment]
I provide an example. The first figure (etaGainH.png) is the one I save from python with plt.savefig('etaGainH.png'). The second figure is the one I get when I use plt.savefig('etaGainH.eps'). 

![etaGainH](https://user-images.githubusercontent.com/45151790/72344357-50ce8d00-36d1-11ea-9161-f9ca238b1c22.png)
[etaGainH-eps-converted-to.pdf](https://github.com/matplotlib/matplotlib/files/4059081/etaGainH-eps-converted-to.pdf)

This is the code I'm using:
```python
fig, ax = plt.subplots(1,1,figsize=(5.3,4.3))
X,Y = np.meshgrid(hstar,invparam,indexing='ij')
cmap = mpl.cm.get_cmap('viridis') ;\
plt.pcolormesh(X,Y,etaGain*100,cmap=cmap,shading='gouraud');\
cbar = plt.colorbar()
cbar.set_label(r'$\mathcal{G}_{\eta}\;[\%]$',fontsize = 14)
plt.ylim([0.5,1.5])
plt.xlim([0.16,0.4])
plt.savefig('etaGainH.eps',format='eps',bbox_inches='tight',dpi=300)
```

Note that if I use shading='flat' instead of shading='gouraud', this is what I get

![etaGainHFlat](https://user-images.githubusercontent.com/45151790/72344782-61cbce00-36d2-11ea-8da8-ea34d811abdc.png)
[etaGainHFlat-eps-converted-to.pdf](https://github.com/matplotlib/matplotlib/files/4059114/etaGainHFlat-eps-converted-to.pdf)

Code 
```python
fig, ax = plt.subplots(1,1,figsize=(5.3,4.3))
X,Y = np.meshgrid(hstar,invparam,indexing='ij')
cmap = mpl.cm.get_cmap('viridis') ;\
plt.pcolormesh(X,Y,etaGain*100,cmap=cmap,shading='flat');\
cbar = plt.colorbar()
cbar.set_label(r'$\mathcal{G}_{\eta}\;[\%]$',fontsize = 14)
plt.ylim([0.5,1.5])
plt.xlim([0.16,0.4])
plt.savefig('etaGainH.eps',format='eps',bbox_inches='tight',dpi=300)
```

The problem seems to be related to this particular shading option. 
Hope that the issue is more clear.

**Comment by anntzer** [comment]
Locally this works for me, and https://github.com/matplotlib/matplotlib/pull/1993 suggests that it indeed should.

**Comment by LucaLanzilao** [comment]
Hi, thank you for your reply.
I did not explain well what the problem is in the first post. 
The code
```python
import matplotlib.pyplot as plt
import numpy as np
plt.pcolormesh(np.random.randn(10,10), shading='gouraud')
plt.gcf().savefig('test.eps')
```
works fine. However, when I save the image with .eps, some pixels change. You can see the difference in my second post. This problem does not exist when I use shading='flat' or when I save the image as .png.

**Comment by anntzer** [comment]
Your example is not reproducible: we don't have the hstar, invparam variables.

**Comment by LucaLanzilao** [comment]
I'm sorry, you are right.
Here it is a reproducible example. 

For images with shading='gouraud':
```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,1,25)
y = np.linspace(0,1,25)
X,Y = np.meshgrid(x,y,indexing='ij')
z = np.sin(X*2*np.pi) + np.cos(Y*2*np.pi)
cmap = plt.get_cmap('viridis')
plt.subplots(1,1,figsize=(5.3,4.3))
plt.pcolormesh(x, y, z, cmap=cmap, shading='gouraud')
cbar = plt.colorbar()
plt.title('Gouraud')
plt.savefig('TestGou.eps',bbox_inches='tight',dpi=300)
```
Output:
![TestGou](https://user-images.githubusercontent.com/45151790/72360264-fc86d580-36ef-11ea-82f5-27b58a56a43a.png)
[TestGou-eps-converted-to.pdf](https://github.com/matplotlib/matplotlib/files/4060128/TestGou-eps-converted-to.pdf)

For images with shading='flat':
```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,1,25)
y = np.linspace(0,1,25)
X,Y = np.meshgrid(x,y,indexing='ij')
z = np.sin(X*2*np.pi) + np.cos(Y*2*np.pi)
cmap = plt.get_cmap('viridis')
plt.subplots(1,1,figsize=(5.3,4.3))
plt.pcolormesh(x, y, z, cmap=cmap, shading='flat')
cbar = plt.colorbar()
plt.title('Flat')
plt.savefig('TestFlat.eps',bbox_inches='tight',dpi=300)
```
Output:
![TestFlat](https://user-images.githubusercontent.com/45151790/72360428-3ce65380-36f0-11ea-8970-296583481bab.png)
[TestFlat-eps-converted-to.pdf](https://github.com/matplotlib/matplotlib/files/4060141/TestFlat-eps-converted-to.pdf)

If you compare the image TestGou.png and  TestGou-eps-converted-to.pdf, they are different. On the other hand, TestFlat-eps-converted-to.pdf and TestFlat.png are identical. 
I would like to know where I'm doing something wrong. Thank you in advance for your help.

**Comment by anntzer** [comment]
Yes, I can confirm the difference now.
