### ISSUE TITLE
set_useOffset(False) is not working

### ISSUE THREAD

**Issue by vallsv** [matplotlib/matplotlib#16232]
Hi,

I try to disable the offset computed to label the axes in the plot.

It looks like the global or local set of `useOffset` is just ignored.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist.axislines import Subplot

# Disable it globally
matplotlib.rcParams["axes.formatter.useoffset"] = False

fig = plt.figure(figsize=(3, 3))

ax = Subplot(fig, 111)
fig.add_subplot(ax)

ax.axis["right"].set_visible(False)
ax.axis["top"].set_visible(False)

# Disable it locally
ax.get_yaxis().get_major_formatter().set_useOffset(False)

ax.set_ylim(10 ** 8, 10 ** 8 + 1)

print(ax.get_yaxis().get_major_formatter().useOffset)
# > False

plt.show()
```

**Actual outcome**

![Screenshot from 2020-01-15 17-21-52](https://user-images.githubusercontent.com/7579321/72451205-de86a700-37bb-11ea-832d-f155c7649c4c.png)

**Expected outcome**

We should not see the `1e8` and the axis should be labelled without the remove of the offset.

**Matplotlib version**

* matplotlib 3.1.1

**Comment by anntzer** [comment]
That's not the offset (which refers to an *added* offset, not a multiplicative factor).  You can turn off the factor with `set_scientific(False)`.

**Comment by vallsv** [comment]
Thanks a lot. 

It works, but it really sounds weird.

Cause I don't want to disable scientific notation for numbers in the axis, which could be used without problem. I don't want to have a splinting of the values in 2 which is exactly what is supposed to be done by `useOffset`.

Do you think there is a problem in the method naming? or the documentation?

**Comment by anntzer** [comment]
The name is unlikely to change, but you are welcome to propose improvements to the docs.

**Comment by timhoffm** [comment]
The above example does not use offset, but the scientific notation:

with `useOffset`
![grafik](https://user-images.githubusercontent.com/2836374/84152182-987cf900-aa64-11ea-894c-2bf8a1219eb7.png)

without `useOffset` (falling back to scientific)
![grafik](https://user-images.githubusercontent.com/2836374/84152121-869b5600-aa64-11ea-8afc-408d4672c238.png)

Only if you disable both offset and scientific notation will you get the complete numbers at the labels for the data provided in the example.
![grafik](https://user-images.githubusercontent.com/2836374/84152899-89e31180-aa65-11ea-915b-16d3094ea645.png)


The offset and the scientific label are quite similar, but offsets have a +/- sign while the scientific scaling factor has not.
