### ISSUE TITLE
ValueError: Image size of 1440x88500 pixels is too large. It must be less than 2^16 in each direction.

### ISSUE THREAD

**Issue by YubinXie** [matplotlib/matplotlib#16234]
I tried to generate a jpg report with many items and it is very long. Then I got an image size issue. Any idea that how to increase this limit?

### Bug report

**Bug summary**

ValueError: Image size of 1440x88500 pixels is too large. It must be less than 2^16 in each direction.

**Actual outcome**

Error.

**Expected outcome**

A larger image.

**Matplotlib version**

  * Operating system: Mac OS
  * Matplotlib version: 2.2。3
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline

  * Python version: 3.7
  * Jupyter version (if applicable): jupyter-notebook : 6.0.2
qtconsole        : not installed
ipython          : 7.10.2
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

**Comment by timhoffm** [comment]
The maximum size of JPG is 65.535 pixels in each direction. This is a file format limit and there is no way of increasing.

General hint: I don't know what you're trying to achieve but such large files image files are usually problematic. Consider splitting up in multiple files or using other technologies such as multi-page pdfs. Note also that JPG is optimized for pictures. It's compression will generate artifacts for sharp edges like lines and texts. It's thus almost never a good choice to save matplotlib to JPG.

**Comment by YubinXie** [comment]
Got it. I try to generate a report where i compare multiple images side by side. I choose the jpg file as it is smaller. Thank you for your explanation! I will try to think about other solution.

**Comment by Lucca-cherries** [comment]
> The maximum size of JPG is 65.535 pixels in each direction. This is a file format limit and there is no way of increasing.
> 
> General hint: I don't know what you're trying to achieve but such large files image files are usually problematic. Consider splitting up in multiple files or using other technologies such as multi-page pdfs. Note also that JPG is optimized for pictures. It's compression will generate artifacts for sharp edges like lines and texts. It's thus almost never a good choice to save matplotlib to JPG.

Why did I reproduce this error when I forgot to write the extension of the file name, for example, when I mistakenly wrote `plt.savefig('a/test')` instead of `plt.savefig('a/test.pdf')` as I wanted? Got the error: `ValueError: Image size of 184000x56000 pixels is too large. It must be less than 2^16 in each direction.`

**Comment by rcomer** [comment]
@Lucca-cherries please see the _fname_ description in the `savefig` documentation.  This describes the default file format.
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html#matplotlib.pyplot.savefig
