### ISSUE TITLE
Nightly release failing with numpy 1.15.x

### ISSUE THREAD

**Issue by effigies** [matplotlib/matplotlib#16230]
### Bug report

**Bug summary**

The nightly release up on https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ is causing import errors with numpy 1.15.x. The problem resolves by upgrading to 1.16 or higher.

First detected on Travis CI in https://github.com/nipy/nipype/pull/3152, but reproduced easily locally.

**Code for reproduction**

Using conda, install numpy 1.15.x and the latest [nightly build](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/matplotlib-3.2.0rc2+1180.ga8ed66d0f-cp37-cp37m-macosx_10_9_x86_64.whl):

```
conda create -n numpy115_mpl python=3.7 numpy=1.15
conda activate numpy115_mpl
pip install https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/matplotlib-3.2.0rc2+1180.ga8ed66d0f-cp37-cp37m-macosx_10_9_x86_64.whl\#sha256\=fa2c4f132fbd257a1ecab26ce61a6789584b63581cffbeec5c1a4d0f8e24cabe
```

Attempt to import:

```
python -c 'import matplotlib'
```

**Actual outcome**

```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Volumes/Data/anaconda3/envs/numpy115_mpl/lib/python3.7/site-packages/matplotlib/__init__.py", line 187, in <module>
    _check_versions()
  File "/System/Volumes/Data/anaconda3/envs/numpy115_mpl/lib/python3.7/site-packages/matplotlib/__init__.py", line 172, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
```

**Expected outcome**

**Matplotlib version**

  * Operating system: OSX
  * Matplotlib version: 3.2.0rc2+1180.ga8ed66d0f
  * Matplotlib backend (`print(matplotlib.get_backend())`): n/a
  * Python version: 3.7.6
  * Jupyter version (if applicable):
  * Other libraries: numpy 1.15

**Comment by tacaswell** [comment]
I don't think that numpy guarantees that things complied with newer versions of numpy (but do guarantee that things compiled with old numpy work with new numpy).  It looks like those wheels are built with numpy 1.18 (https://travis-ci.org/MacPython/matplotlib-wheels/jobs/637581926#L962). 

Do the nightly matplotlib wheels work with newer versions of numpy?  I am not convinced that we want to worry about pinning back the build dependencies on nightly wheel build.

**Comment by effigies** [comment]
Gotcha. If your release wheels are built with the oldest supported numpy, then I don't think there's a problem.

I've switched our `--pre` test to also use `--upgrade`, to ensure that we're testing all libraries with the newest version (what I was intending anyway...), so we're not going to hit this again unless the next matplotlib release also compiles with numpy 1.18.

**Comment by tacaswell** [comment]
Our release wheels should be built with the oldest supported version of numpy.  I'm going to close this as no-action, thank you for reporting!
