### ISSUE TITLE
axes.spy plotting function doesn't respect origin='lower' kwarg when marker is not None

### ISSUE THREAD

**Issue by proteins247** [matplotlib/matplotlib#16252]
### Bug report

**Bug summary**

`spy` always draws with the origin in the upper left corner if `marker` is not `None`, even if `origin='lower'` is provided as a keyword argument.

**Code for reproduction**

```python
points = np.zeros([10, 5])
points[5:] = 1
fig, ax = plt.subplots()
ax.spy(points, marker='.', origin='lower')

```

**Actual outcome**
![spy_point_marker](https://user-images.githubusercontent.com/9356872/72668056-a1efc100-39f0-11ea-8103-72c68f7005f4.png)

After this point, the origin appears to be fixed in the upper left corner. Any subsequent commands (`imshow`, `spy`) seem to ignore `origin='lower'`.

**Expected outcome**

Note that `ax.spy(points, origin='lower')` (omitting the `marker` argument) works properly:
![spy_default_marker](https://user-images.githubusercontent.com/9356872/72668033-6fde5f00-39f0-11ea-9e82-9fe283673166.png)

Though it's worth pointing out that the x-axis ticks and labels always end up in upper spine, not the lower one, regardless of `origin='upper'` or `origin='lower'`. The behavior of `imshow` is a bit different. If `origin='lower'`, the ticks and labels are moved to the bottom.

The documentation for spy notes that:
```
If *Z* is a `scipy.sparse.spmatrix` or *marker* or *markersize* are
*None*, a `~matplotlib.lines.Line2D` object will be returned with
the value of marker determining the marker type, and any
remaining kwargs passed to `~.Axes.plot`.
```
So that seems to explain why including `marker` changes the function's behavior.

**Matplotlib version**

  * Operating system: Centos 7
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.8
  * Jupyter version (if applicable):
  * Other libraries: 

Installed using anaconda.

**Comment by proteins247** [comment]
Looking into the actual `spy` function, I observe that...

1. ylim is set in this way:
```self.set_ylim(nr - 0.5, -0.5)``` 
(when going down the `marker is not None` branch)

2. `self.xaxis.tick_top()` is always called.

**Comment by wcneill** [comment]
Outsider here, has this issue been fixed? Or is the work-around still required. I'm not super fluent but it looks like the some change has been committed that will fix this... Does that mean I just need to update matplotlib?

**Comment by timhoffm** [comment]
This is fixed. If you think there is still an error please provide a minimal example indicating what is going wrong.
