### ISSUE TITLE
API changes are too hard to find in the rendered docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#16251]
Looks like (unless I've missed a shorter route) with the master docs, to access the API changes you need to click on "Documentation" (top menu), "API Overview", find the small, inconspicuous "See also the API Changes" link (and possibly then again the small "Old API changes" link).  (and I only figured that out because I grepped the source...)

It doesn't have to be toplevel, but this seems a bit too well hidden to me.

**Comment by QuLogic** [comment]
There is a faster route due to #16065 (which was before this issue, no?): scroll down to the News section and click "API changes".

**Comment by timhoffm** [comment]
That is true, but API changes should be present in the toc https://matplotlib.org/devdocs/contents.html, next to what‘s new. Or probably even better both merged to a „changelog“ page.

**Comment by anntzer** [comment]
Fixed by the website redesign.
