### ISSUE TITLE
DOC: Move version links to sidebar

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#16253]
I would like to move the version links on the main page to the sidebar. Similar to (exact format to be detemined).
![grafik](https://user-images.githubusercontent.com/2836374/72668480-abe0e680-3a27-11ea-8199-7f86b5353d93.png)

I propose to reuse the existing `versions.html` with adapted, so that older versions of the page still can show up-to-date version information.

This can be handled in separate steps for which I plan to make dedicated PRs:
- [x] Move the version snippet to the sidebar.
- [x] For 2.2.5 update the EOL announcement.-
- [x] For 3.x remove the EOL announcement.
- [x] Update the contents of versions.txt.

**Comment by timhoffm** [comment]
@tacaswell who controls `version.txt`?

**Comment by timhoffm** [comment]
A suitable source block for `versions.html` could be:
~~~
<p><strong>Latest release</strong><br>
3.2.0: <a href="https://matplotlib.org/3.2.0/index.html">docs</a> | <a href="https://matplotlib.org/3.2.0/users/whats_new.html">changelog</a></p>
<p><strong>Last release for Python 2</strong><br>
2.2.5: <a href="https://matplotlib.org/2.2.5/index.html">docs</a> | <a href="https://matplotlib.org/2.2.5/users/whats_new.html">changelog</a></p>
<p><strong>Development version</strong><br>
<a href="https://matplotlib.org/devdocs/index.html">docs</a></p>
~~~
I chose HTML formatting <strong> and <br> because I think this gives a more consistent view on older versions of the docs than trying to use CSS.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib.github.com/blob/master/versions.html <- that is the point of truth of that file,  I will move it over and publish.

**Comment by tacaswell** [comment]
pushed as https://github.com/matplotlib/matplotlib.github.com/commit/4cafb51a0106fd559de2904f17932e342ede9159

**Comment by timhoffm** [comment]
Thanks!
