### ISSUE TITLE
Apply NEP29 (time-limited support) to IPython

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#16263]
Currently, Matplotlib maintains some code to support some extremely old versions of IPython (supposedly down to 1.x) even though it is quite possible that such versions don't even work with Py3.6+.  There are also some tricky points wrt backend switching which were fixed a while ago in ipython (https://github.com/ipython/ipython/pull/9287) but for which we still maintain backcompat for older versions.  (Backend switching is the motivation for this proposal.)

Even though IPython is not a "dependency" of Matplotlib, there's obviously some rather tight coupling due to event loop integration, so I would suggest applying NEP29 (or rather our version of it, https://matplotlib.org/devdocs/devel/min_dep_policy.html#python-dependencies): "we should support at least (...) minor versions initially released in the 12 months prior to our planed release date or the oldest that supports our minimum python" (as there is no compiled code in IPython) -- right now this would mean ipython 7.3.0.  I'm not asking that we be super strict (we could e.g. also treat ipython like numpy, which means 24 months -- so IPython 6.3.0, right now), but unlimited support seems a bit too much.

Assuming we agree on this, we also need to decide what to do if Matplotlib detects that it is running in an too-old-IPython: error out? print a warning?

**Comment by tacaswell** [comment]
:+1: to removing work-around code for old versions of IPython.  50/50 on adding a warning for older versions of IPython.

**Comment by anntzer** [comment]
Do you suggest to not even bother checking if we're running a too-old ipython?

**Comment by dopplershift** [comment]
Treating IPython like numpy seems reasonable. I’m also 50/50 on even bothering to warn about old versions.

**Comment by tacaswell** [comment]
Pushing to 3.4 as it is not urgent.

We talked about this on the call, general agreement, but still want to think about if we should warn about old versions.

The code we use from IPython has been stable for an extremely long time so this maybe a moot point.

**Comment by QuLogic** [comment]
cc @ianthomas23; I think this ties in with the backend registry?

**Comment by ianthomas23** [comment]
> cc @ianthomas23; I think this ties in with the backend registry?

Yes it does. Looking forward we have removed the hidden tight coupling between the two projects, such as matplotlib dynamically altering ipython's `backend2gui` mapping, and replaced it with the `BackendRegistry` public API. So it should be *much* easier in future to keep them in step.

Can we claim to have done enough to close this issue now by informally adopting NEP29 for IPython backward compatibility and implementing tests to prove it in #28205? Or does there need to be a statement somewhere (code or docs) that this is a formal policy?

**Comment by anntzer** [comment]
I think what really matters is just that someone actually looked into the compatibility ranges, but a statement in the docs can't hurt... (I'm not insisting on it either.)

**Comment by tacaswell** [comment]
Opened a PR with explicitly adding it to the docs.
