### ISSUE TITLE
SymLogNorm colorbar incorrect on master

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#16280]
### Bug report

**Bug summary**

The colormap/tick locations within the colorbar are not being updated properly with a SymLogNorm on master. I think this is different than #16269 because it is actually creating the colorbar, just a wrong one.

Compare the previous correct version:
https://matplotlib.org/3.1.0/gallery/userdemo/colormap_normalizations_symlognorm.html

with a fresh checkout of master:

![test](https://user-images.githubusercontent.com/12417828/72822693-c38abb80-3c2f-11ea-89f9-a101191d7bb3.png)

Difference in the colorbar of the top axis.

**Comment by jklymak** [comment]
That example is pretty broken anyways.  

Colorbars changed to behave more like normal axes, though I thought they changed in 3.1.  Can you bisect this and see what commit made this change?

I'm ill-disposed to `SymLogNorm`, but maybe its an easy fix.

**Comment by dstansby** [comment]
@jklymak good job I'm well-disposed 😉 - I'll try to look into this as I think I have the same issue too!

**Comment by dstansby** [comment]
Bisects to dc51a68352fd5f1a209c55f2ffb7bdc6f7728159

**Comment by jklymak** [comment]
Hmm, well not surprising.  I guess the hand-made axes handling that used to be in colorbar did something special with `SymLogNorm`.    This comes back to the issue that @anntzer has that scales and norms are not terribly different.  I suspect the correct fix is for someone to gin up a SymLogScale if it doesn't already exist and get that to work and then let it be applied to colorbars.  Or special case SymLogNorm in colorbar, but thats a last resort IMHO.

**Comment by greglucas** [comment]
@dstansby, out of curiosity how did you bisect that so fast? When I do a git bisect and rebuild with `python -mpip install .` it takes quite a while to rebuild mpl each time. Is there an automated way that you've got to make bisecting faster?

**Comment by jklymak** [comment]
You don’t need to pip install each time if you don’t need to rebuild any of the c code.  (And you’ve used pip install -e)

**Comment by anntzer** [comment]
Some more tricks (everything here assumes you're in a -e install):
- Even if you need to rebuild c extensions you can just do `python setup.py build_ext --inplace` which will just rebuild the extensions and skip the rest.
- ccache (https://ccache.dev/) *really* helps too (because if you're bisecting even only once in a while, you'll be compiling the same files again and again).

**Comment by jklymak** [comment]
So it seems that `SymLogNorm` itself is also broken, so perhaps not such a bad thing that its colorbar doesn't work: https://github.com/matplotlib/matplotlib/issues/16376  But of course we should fix these things ASAP.

**Comment by tacaswell** [comment]
@greglucas Using `pip install -e .` is one way to make it faster (as you don't have to actually re-install if only the python changes) and the other is to use `ccache` so that the c-extensions build almost instantly.

**Comment by greglucas** [comment]
Thanks for the helpful hints on commands! A quick search through the docs doesn't indicate anything telling me about `ccache` and the wording is pretty vague around the `pip install -e .` command. I think this would actually be helpful for other new contributors getting started and bisecting, so I will try and look into adding it somewhere in the docs.
