### ISSUE TITLE
Problem with errorbar in log scale

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#163]
[Original report at SourceForge, opened Wed Sep  1 13:52:54 2010](https://sourceforge.net/tracker/?func=detail&aid=3057653&group_id=80706&atid=560720)

When using log scale, if the error is larger than flux, the error bar does not plot at all:

import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.errorbar([1.],[1.],yerr=[2.])
ax.set_yscale('log')
fig.savefig('test.png')

However, I think it would make more correct to plot the line for the errorbar, and to make it go down to -infinity.

**Comment by SebastianoF** [comment]
Uhm... No, the errorbar should not be asymmetric when passing in log scale.
Please consider 
http://faculty.washington.edu/stuve/uwess/log_error.pdf
