### ISSUE TITLE
Is it acceptable to change the axis_name attribute?

### ISSUE THREAD

**Issue by l-johnston** [matplotlib/matplotlib#16301]
XAxis and YAxis have the class attribute axis_name that propagates to instances. In my library, I would like to change this axis_name from the default 'x' and 'y' values to actual, relevant values. Here's an example:

```python
>>> import matplotlib.pyplot as plt
>>> ax = plt.figure().add_subplot()
>>> ax.plot([1,2,3])
>>> ax.xaxis.axis_name = "index"
```
In my library, this axis_name would then be used by my matplotlib.units.ConversionInterface to form the axis label.

Is it acceptable to change axis_name?

**Comment by ImportanceOfBeingErnest** [comment]
It is not advisable to change the attribute. It's not too clear what the ultimate purpose would be and why that attribute would be needed. In the limit, one can attach another attribute like `ax.xaxis.my_axis_name`.

**Comment by l-johnston** [comment]
I am contributing to the [Unyt](url) project where I have implemented the [matplotlib.units.ConversionInterface](url) that will set the axis label to the unit from the plotted data. We are considering adding a name attribute to unyt_array that will then propagate to the axis label so that the user sees a label like "Time (s)". I need a way to name the Axis instance with our unyt_array name, but we don't want to monkeypatch Axis.

**Comment by ImportanceOfBeingErnest** [comment]
The links don't lead anywhere, so I'm still a bit at loss about the actual problem. All I can say here is really, that `ax.xaxis.axis_name` is not meant to be changed if matplotlib's default behaviour is desired, e.g. it is used in https://github.com/matplotlib/matplotlib/blob/ce295ee35ed3b19c1a02b1e6aaaa8ad0813e0834/lib/matplotlib/scale.py#L111

to identify which locator to use.

**Comment by l-johnston** [comment]
I updated the links.

Our goal is to have the axis label come from our ``unyt_array`` name and unit. The workflow looks like:

```python
>>> import matplotlib.pyplot as plt
>>> import unyt
>>> unyt.matplotlib_support()
>>> x = unyt.unyt_array([0,1,2], units="s", name="Time")
>>> y = unyt.unyt_array([3,4,5], units="V", name="Voltage")
>>> plt.plot(x, y)
>>> plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/17813788/72998495-8d7e4080-3dc3-11ea-8d06-73dfc026e9bc.png)

This is an actual working example from my local dev branch. The problem is that there isn't a clean way to propagate the unyt_array.name attribute through to the axis label without monkeypatching the Axis instance.

**Comment by anntzer** [comment]
If you *really* don't want to monkeypatch the axis (even though I would argue that reusing axis_name for a purpose it wasn't intended for is philosophically the same as monkeypatching, if not worse...), you could for example maintain a (separate, global) mapping of {axis: label} (or a WeakKeyDictionary if you want to be careful about garbage collection).

**Comment by l-johnston** [comment]
At this point, I won't use axis_name; that's why I asked the question. The [Axis documentation](https://matplotlib.org/api/_as_gen/matplotlib.axis.YAxis.axis_name.html#matplotlib.axis.YAxis.axis_name) doesn't state that axis_name is read-only. Perhaps that is a documentation improvement?

**Comment by jklymak** [comment]
The way most packages implement this (i.e. pandas and xarray) is to attach a plot method to their data object and then they can pass default labels to whatever they want.  i.e. http://xarray.pydata.org/en/stable/plotting.html#simple-example

**Comment by tacaswell** [comment]
@l-johnston That proposed workflow can become problematic very fast, what if the user does:

```
>>> x = unyt.unyt_array([0,1,2], units="s", name="Time")
>>> y = unyt.unyt_array([3,4,5], units="V", name="Safe Voltage")
>>> y2 = unyt.unyt_array([3,4,5], units="V", name="Dangerous Voltage")
>>> plt.plot(x, y)
>>> plt.plot(x, y2)
```
