### ISSUE TITLE
How to plot graph on time interval using matplotlib

### ISSUE THREAD

**Issue by Suraj023** [matplotlib/matplotlib#16316]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by Suraj023** [comment]
Please suggest, I am a student and working on a restaurant management system in which I have to show that how many times table is booked and upto which time in a whole day and there are lots of tables in the restaurant 

conclusion: I have have to show time interval of all Tables in a day


kindly help me .......

**Comment by ImportanceOfBeingErnest** [comment]
Hello and thanks for your interest in matplotlib. This is the matplotlib issue tracker, where bugs and new features are tracked and discussed. Your question would better fit in [discourse.matplotlib.org](https://discourse.matplotlib.org), the matplotlib mailing list, or stackoverflow. In case of using one of those channels you might also want to provide more details about your actual problem. Good luck with your project.

**Comment by Suraj023** [comment]
Thank you Sir/Madam for responding but I am facing the same issue.I want to create a project in which a different persons spending time on a particular table. I want to create [this type of graph
](https://discourse.matplotlib.org/t/time-interval-with-respect-any-specific-data/20850?u=suraj_verma)
Thank you .
