### ISSUE TITLE
How does matplotlib show 16 bit images with cmap

### ISSUE THREAD

**Issue by kHarshit** [matplotlib/matplotlib#16315]
Hi,

With respect to [this question](https://stackoverflow.com/q/59873709/6210807) on stackoverflow, OpenCV fails to plot/save 16 bit images with colormap, while matplotlib does that. Does that mean that matplotlib supports colormaps for 16 bit images or it internally converts it to 8-bit image?

Thanks

**Comment by anntzer** [comment]
We internally convert to 32bit floats in the normalization pipeline, then apply the colormap palettes which are typically limited to 255 values, but you can create your own palettes with more values.

**Comment by kHarshit** [comment]
Okay, thanks.
