### ISSUE TITLE
BUG: VisibleDeprecationWarning in boxplot

### ISSUE THREAD

**Issue by bashtage** [matplotlib/matplotlib#16353]
### Bug report

**Bug summary**

`boxplot` is calling `asarray` on lists of arrays they do not have the same shape. In future NumPy ragged array construction will raise an error unless dtype='object' is explicitly passed.

This issue happens in 

https://github.com/matplotlib/matplotlib/blob/c0bf2ef8ab5ad5d1540e23b7936a02a23ebc477b/lib/matplotlib/cbook/__init__.py#L1382

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
x = [np.random.standard_normal(v) for v in np.random.randint(100,200,5)]
plt.boxplot(x)
```

You need NumPy 1.19dev0 to see this warning.

**Actual outcome**
```
numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

**Expected outcome**

No warning

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version:  3.2.0rc2+1221.g20805b805 
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.8.0
  * Jupyter version (if applicable):
  * Other libraries: numpy: 1.19.0.dev0+32aa66e 

This is on a statsmodels "pre" build that uses the latest nightlies on rackcdn.

**Comment by timhoffm** [comment]
https://github.com/numpy/numpy/pull/15083 would have allowed an easy fix. But it's closed with the comment that downstream libraries don't need it anymore :sad:. Using `dtype=object` is not a solution in our case, because we might also have regularly shaped arrays that we do not want to convert to `object`.

Probably we need to rewrite the whole `_reshape_2D` logic to not try to fit it into a single array in the first place.

**Comment by tacaswell** [comment]
attn @phobson

**Comment by phobson** [comment]
Hmmm. I wonder if a std-lib list of arrays would work for us. I might be able to think about this at some point this week. If someone else comes up with a solution, feel free to propose it here or in a PR that I'll happily review.
