### ISSUE TITLE
DOC: wrong self-refering link in Marker filling-styles example

### ISSUE THREAD

**Issue by pierre-haessig** [matplotlib/matplotlib#16354]
Hello,

I just noticed an extraneous link in the [Marker filling-styles](https://matplotlib.org/gallery/lines_bars_and_markers/marker_fillstyle_reference.html) example. It's a "see also" type of link which points to the example itself.

> Also refer to the **Marker filling-styles** and Marker Path examples.

I think it should be either removed, or more probably it should be a reference to the [Marker Reference](https://matplotlib.org/gallery/lines_bars_and_markers/marker_reference.html).

Best,
Pierre

**Comment by timhoffm** [comment]
The Marker filling-styles example has recently been integrated into the marker reference:
https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/marker_reference.html#marker-fill-styles

During that, the link was already removed. Anyway, thanks a lot for caring to report on documentation issues!
