### ISSUE TITLE
runtime error occurs

### ISSUE THREAD

**Issue by fathimakmurshida** [matplotlib/matplotlib#16367]
### Bug report

**Bug summary**

/home/user/zipflaw/env/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py:180: RuntimeWarning: Glyph 3376 missing from current font.
  font.set_text(s, 0, flags=flags)
how can i fix this? am using Malayalam language

**Comment by anntzer** [comment]
Indic scripts are currently not supported.  See discussion in https://github.com/matplotlib/matplotlib/issues/5941, https://github.com/matplotlib/matplotlib/issues/8765.
