### ISSUE TITLE
Call to input blocks slider input on osx with the default agg 'MacOSX'. It works fine on when TkAgg is used.

### ISSUE THREAD

**Issue by odinsbane** [matplotlib/matplotlib#16369]
### Bug report

**Bug summary**
I recently updated to matplotlib==3.1.1 and when I use the default backend on OS X, I cannot use non-blocking with the python function `input`.

```python
#!/usr/bin/env python3

from matplotlib import pyplot
from matplotlib.widgets import Slider
import numpy

figure = pyplot.figure(0)
plot = pyplot.imshow(numpy.random.random((64, 64)))
pyplot.subplots_adjust(left=0.1, bottom=0.25)
axrs = pyplot.axes([0.2, 0.05, 0.65, 0.05], facecolor="blue")
slider = Slider(axrs, "Slice", 0, 3, valinit=1, valstep=1)

def setSlice(slc):
    plot.set_data(numpy.random.random((64, 64)))
    figure.canvas.draw()
slider.on_changed(setSlice)

pyplot.show(block=False)
input("true")
```
If I run that code, the slider is no longer interactive at all. If I set the MPLBACKEND to be TkAgg, then it works as expected. If I use `pyplot.show(block=True)` then everything works as expected: the slider changes and the image updates. 

I have also tried using:

```python
pyplot.ion()
pyplot.show()
input("waiting")
```
I get the same behavior.

I am using the slider to select z slices, and I wait on user input to decide to move on to another dataset, so the .show() with block doesn't really help me. Currently my TkAgg work around is sufficient, but I reported this bug in case it is a bug you want to know about, or I am incorrectly showing a non-blocking window.

  * Operating system: MacOS Sierra 10.12.6
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`MacOSX`):
  * Python version: 3.6.9

I installed using the default anaconda channel. I just updated conda which is how I noticed the error.

**Comment by greglucas** [comment]
This is working as expected on main now and will be in the next release.
