### ISSUE TITLE
imshow image extends too far for large images

### ISSUE THREAD

**Issue by human9** [matplotlib/matplotlib#16378]
### Bug report

**Bug summary**

When plotting a large image with imshow, the image may sometimes extend beyond it's reported extent, leading to to the border being obscured. I think this is related to #1441.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(figsize=(6,3), ncols=2)

for ax, n in zip(axes.flatten(), [100,200]):
    mat = np.ones((n,n))
    mat[1:-1,1:-1] = 0
    # Turning clip off to see the issue better
    im = ax.imshow(mat, interpolation='none', clip_on=False)
    ax.set_title(f'{n}x{n}')
```

**Actual outcome**

![imshow_test](https://user-images.githubusercontent.com/18050721/73502330-8f29b300-4418-11ea-8bc1-6d7c6fef052d.png)

**Expected outcome**
Images should fit within their extent.

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.1
  * Jupyter version (if applicable):
  * Other libraries: 

All packages installed from distribution repositories using pacman.

**Comment by tacaswell** [comment]
#1441 is related to numerical instabilities when you are very zoomed in on a large image.  This is more closely related to https://github.com/matplotlib/matplotlib/issues/12934 

In this case I think the issues is related to the fact that we are down-sampling your image.  The smallest quanta we can color in the output is 1pixel.  If you have more data-pixels across your image than you have screen-pixels something has to give.  If you increase the DPI I expect this effect to become less pronounced, but at some level, there is no way to get around this aliasing (which can also lead to some pixels being "wider" than others depending on how the beating between the screen pixels and the data pixels is lined up).

**Comment by human9** [comment]
Ah, this is indeed alleviated by increasing the DPI, thanks! I suppose if I really want every pixel to be visible on zooming in, using `pcolormesh` and exporting in a vector format might be a better idea.

**Comment by tacaswell** [comment]
If you have a live figure, when you zoom in it will re-sample correctly, but if you want static output you can zoom in on you either need to use very high DPI (basically to match your screen dpi at the expected zoom level) or use a vector backend.  

Off the top of my head, I think that setting the interpolation to 'none' and saving to a vector backend will not do any re-sampling, but I may be wrong about that.

**Comment by jklymak** [comment]
I think we can safely close this.
