### ISSUE TITLE
enable figures to be excluded from calls to show()

### ISSUE THREAD

**Issue by keatonb** [matplotlib/matplotlib#16377]
### Feature request
Calling matplotlib.pyplot.show() displays all active figures.  There are times this is not desirable, such as when some figure is still being developed.  Of course, show() can be called for specific figures, but perhaps a user doesn't know that an undisplayed figure belongs to a class instance and these all get displayed when they call show() for their own plot. 

Example at https://stackoverflow.com/q/59995448/4302578

It would be great if there was some attribute of a figure like `figure.show_by_default`, `figure.implicit_show`, or `figure.exclude_from_show` that could be set to stop these from popping up when `plt.show()` is called without arguments.

**Comment by anntzer** [comment]
I think this is basically a variant on https://github.com/matplotlib/matplotlib/pull/14024.

**Comment by keatonb** [comment]
The behavior I want is achieved, in effect, after the figures I do *not* want to show have been shown once with a call to `show()` (i.e., I can still modify them and display them directly by accessing their canvasses, but they don't show up again with later calls to `show`).  Is there a way I can make matplotlib *think* that `show` has already been called for specific figures, without having to actually displaying them with `show`?

**Comment by ImportanceOfBeingErnest** [comment]
In principle this is what `plt.close(fig)` is for. The problem is just that figures that are closed, cannot be reopenend as of now.  
 https://github.com/matplotlib/matplotlib/pull/14024 (+ making sure every figure has a manager(?)) would make that possible though.

The ideal solution to the problem in the stackoverflow post would probably be not to use pyplot at all. But then it's hard to get the notebook to identify the canvas as something "showable".

**Comment by ImportanceOfBeingErnest** [comment]
Btw. you can attach the manager manually, so

```
%matplotlib widget
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_nbagg import FigureCanvasNbAgg, FigureManagerNbAgg

class interactiveplot(object):
    def __init__(self, x, y):

        self.fig = Figure(figsize=(2,2))
        self.canvas = FigureCanvasNbAgg(self.fig)
        self.canvas.manager = FigureManagerNbAgg(self.canvas, 2)
        self.ax = self.fig.subplots()
        self.plot, = self.ax.plot(x,y)
    def update(self,x,y):
        self.plot.set_data(x,y)
        self.fig.canvas.draw()
    def show(self):
        self.canvas.manager.show()
```
should work?

**Comment by keatonb** [comment]
Your example does work, but I also want to be able to display the plots via their canvasses (using ipympl) without calling `show()`, since in my actual problem the class I have returns a `Box` containing both ipywidgets and mpl canvasses.

**Comment by tacaswell** [comment]
I am comfortable leaving this closed, directly creating the `Figure` s (with which ever canvsa you want) will create `Figures` that are unknown to `pyplot` and hence will not be implicated by `plt.show()`.
