### ISSUE TITLE
rethink how we display DOI svg badges

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#16388]
If you go to https://matplotlib.org/citing.html only a (random) fraction of the svg's for the DOIs load.  Investigating using browser tools says we are getting 429 (TOO MANY REQUESTS) responses back from zenodo.

We probably should embed a copy of the svg in our docs (and write a helper script to do that).

**Comment by timhoffm** [comment]
Should we ask the zenodo people how to best handle this?

**Comment by QuLogic** [comment]
We could link the general one, and ask people to pick a version-specific one from there?

**Comment by timhoffm** [comment]
Should be good enough.
