### ISSUE TITLE
Should rcParams values be mutable?

### ISSUE THREAD

**Issue by OriolAbril** [matplotlib/matplotlib#16384]
### Bug report?

rcParams which accept iterables are stored as lists, which allows to update these lists without going through the validation function set for the rcParam.

**Code for reproduction and outcome**

```python
In [2]: plt.rcParams["lines.dashdot_pattern"]
Out[2]: [6.4, 1.6, 1.0, 1.6]

In [3]: plt.rcParams["lines.dashdot_pattern"].append("unvalidated_value")

In [4]: plt.rcParams["lines.dashdot_pattern"]
Out[4]: [6.4, 1.6, 1.0, 1.6, 'unvalidated_value']
```

As expected, trying to do `plt.rcParams["lines.dashdot_pattern"] = [6.4, 1.6, 1.0, 1.6, 'unvalidated_value']` results in `ValueError: Key lines.dashdot_pattern: Could not convert all entries to floats`. 

I am basically curious about this being intended or not as there may be use cases I am missing.

Note: I am talking about rcParams values, not about rcParams objects.

**Comment by jklymak** [comment]
Since people need to be able to set rcParams in their code, they have to be mutable.  

I'll close, because this isn't really a bug, but feel free to continue the discussion at http://discourse.matplotlib.org

**Comment by WeatherGod** [comment]
Important distinction to be made here: of course the rcParams dictionary
should be mutable. The question is should the values stored in the rcParams
be mutable. I think they shouldn't be.

**Comment by jklymak** [comment]
I'm not sure thats a practical distinction.  If the dictionary is mutable by the user without verification, then I don't see how it helps to make the entries inside any individual entry un-mutable? i.e. if `plt.rcParams["lines.dashdot_pattern"]=[6.4, 1.6, 1.0, 1.6, 'unvalidated_value']` is allowed in user code, then I don't see that its worth the effort to make `plt.rcParams["lines.dashdot_pattern"].append("unvalidated_value")` fail.   But please do re-open if this is something you want to seriously discuss.

**Comment by OriolAbril** [comment]
@jklymak the dictionary, **is not** mutable by user code without verification. As I said above, `plt.rcParams["lines.dashdot_pattern"]=[6.4, 1.6, 1.0, 1.6, 'unvalidated_value']` is **not allowed**, it raises a `ValueError`. Sorry if I was not clear enough in the initial issue

**Comment by jklymak** [comment]
Oh I see. Sorry, I misunderstood.  Still not convinced this is worth protecting, but we can re-open for discussion.

**Comment by timhoffm** [comment]
-0 on protecting as of now. Protecting would mean either:
- we internally store a custom read-only list and return that.
- we return a copy on access. This means that rcParams has to be rewritten as a completely different object.

Both of them should only be introduced with careful consideration.

**Comment by tacaswell** [comment]
Is there a reason we can't ensure that we use tuples instead of lists in what is returned by the validators in `rcsetup.py`?

**Comment by anntzer** [comment]
This would break people doing e.g. `rcParams["font.serif"].insert(0, "somefont")` or `rcParams["axes.formatter.limts"][1] = 3` which seems a bit gratuitious.
In general I'm not sure what we're exactly trying to do by overprotecting rcParams modification.  If you put in an invalid value you'll get an error when actually trying to use it anyways.  Sure, erroring out when setting the value is nicer, but it's not worth building a huge machinery just to achieve that.

**Comment by tacaswell** [comment]
I see both sides of this.  On one hand, if we claim rcparams is validated state, it should be validated state.  On the other hand, the complexity to ensure this is high (see enthought traits, ipython's traitlets, and atom (not the editor) for a sense of what that takes) and making the validation bullet proof is not at the top of my list of work we need to do.

The case @anntzer makes the convenience of mutable values is pretty compelling. Changing to tuples would likely break a lot of users.

While I would not oppose merging a PR that uses a list sub-class to apply validate-on-mutate, I am not in favor of it either.  That status quo has been like this for the history of the project and we have not had many complaints.

I propose we close this as no-action.  I think to answer the initial question, this is not fully intended, but I think it has become a de-facto part of the API and I am not sure that the benefit of fully validating all mutations is worth the effort / code complexity to do it.

**Comment by anntzer** [comment]
(FWIW I don't even think we should really bother validating rcParams; hopefully the error at the point of use should be clear enough.  But we do need to know what type of values we expect so that *parsing* matplotlibrc works, so we may as well just always validate for simplicity...)

**Comment by timhoffm** [comment]
Closing as no-action. Because

- trying to make this immutable is really complicated. Python is not desiged for this.
- there are acceptable use cases for manipulation
- the associated risk / user confusion is low
- we're all consenting adults here (as much as I don't like this attitude, I think it applies here)
