### ISSUE TITLE
New pypi pylab module shadows Matplotlib's

### ISSUE THREAD

**Issue by cliffckerr** [matplotlib/matplotlib#16422]
### Bug report

**Bug summary**

In December 2019, a new module was published to pypi that has the name `pylab` (there was no such module before):

https://github.com/LukeSkywalker92/pylab

If installed, this shadows the Matplotlib `pylab`, which is highly confusing.

**Code for reproduction**

In the terminal:
```
pip install matplotlib
pip install pylab # <-- wrong pylab
```

In the console:
```python
>>> import pylab # <-- wrong pylab
>>> dir(pylab)
```

**Actual outcome**

```
>>> dir(pylab)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Expected outcome**

```
>>> dir(pylab)
['ALLOW_THREADS', 'Annotation', 'Arrow', 'Artist', 'AutoLocator', 'Axes', 'AxisError', 'BUFSIZE', 'Button', ...
```

**Matplotlib version**
  * Operating system: Linux
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.5
  * Jupyter version (if applicable): N/A
  * Other libraries: `pylab` (that's the problem!)

`matplotlib` (and the erroneous `pylab`) installed via pip.

**Solution**

It would be nice to remove this "fake" `pylab` from pypi, but I'm not sure if that's possible! I assume the author (`LukeSkywalker92`) didn't realize that this package would create this shadowing problem.

**Comment by WeatherGod** [comment]
Seriously? I thought we got this sorted out with the pypi people the last
time someone published a pylab package.

**Comment by jklymak** [comment]
I dunno, do we need to hog the top-level namespace?   `import matplotlib.pylab as pylab` seems to work just fine.

**Comment by WeatherGod** [comment]
Just as a point of reference. pylab was the original name of matplotlib. We
have always had a pylab.py. Yes, it does seem to be a bit superfluous now,
but there are still tons of people who use it.

**Comment by cliffckerr** [comment]
@jklymak I see your point, but personally I find `pylab` it very convenient...I'm sure there are lots of people (myself included) who start practically every single script with `import pylab as pl` -- often these are just three-line scripts (or even in the console) to load some data and plot it. Having to type `import matplotlib.pylab as pl` every time would significantly increase the total number of keystrokes :)

**Comment by jklymak** [comment]
Sure but then don’t install the pylab package?

**Comment by jklymak** [comment]
My point is its a little unfair to expect everyone at pypi to remember we have this namespace.  If we want it reserved we should try and make our own package to put there.

**Comment by cliffckerr** [comment]
@jklymak I completely agree -- to me it seems like the obvious way to install `pylab` would be, well, `pip install pylab`, just like everything else!

**Comment by jklymak** [comment]
I guess - I don't know how pypi really works, but I'd assume it would just softlink to matplotlib.

Is anyone on the dev team the point person with pypi?  @tacaswell ?

**Comment by tacaswell** [comment]
There used to be a pylab package, but we asked the author to take it down and rename (see https://github.com/javipalanca/scibag/issues/1) however, we failed to the squat the name to prevent it from becoming a problem again (like we did with `pyplot` https://pypi.org/project/pyplot/1.5.0/) .  

I am going to follow the same game plan as before and start by asking the owner to rename and take it off pylab.  From a quick skim at the code this looks like a project for working with bench-top EE lab equipment which quite logically has the name `pylab` (rather than someone malicious name squatting to install malware via typo).

**Comment by tacaswell** [comment]
xref to mailing list post from 15 https://discourse.matplotlib.org/t/pypi-name-collisions/19342

**Comment by QuLogic** [comment]
All the releases on PyPI are gone, so there's no shadowing. Do you need to do anything more like uploading a placeholder?

**Comment by cliffckerr** [comment]
+1 for taking the same approach with `pylab` as was taken with `pyplot`, as @tacaswell mentioned!

**Comment by cliffckerr** [comment]
@tacaswell I tried to upload an empty package and transfer ownership to you but I couldn't:
```
The user 'sciris' isn't allowed to upload to project 'pylab'.
```
So I'll assume pypi has agreed to not let users claim this name, which I believe resolves this issue. Thank you!

**Comment by tacaswell** [comment]
I just verified that the pylab project still exists on pypi, but is invisible because it contains no release and I am still an owner.

**Comment by cliffckerr** [comment]
Ah great, I think I just missed that you'd already done this! Well, confirm that it's working as intended ;)
