### ISSUE TITLE
New function for xylim

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/matplotlib#16424]
I would really like to use an intuitve function, where one does not have to define xlim and ylim separately.
A nice name could be xylim.
```py
def xylim(xinterval,yinterval):
    plt.xlim(xinterval[0],xinterval[1])
    plt.ylim(yinterval[0],yinterval[1])

plt.xylim( [10,20]  ,  [9,90] )
```
This would make it possible to writer denser code, without loosing readability.
Further it would be quit intuitive to use.
It took a while for me to find [plt.axis](https://matplotlib.org/api/pyplot_summary.html) which does set both x and y limits in one line of code, however it is used with `[xmin xmax ymin ymax]`  (eg. `plt.axis([0, 6,0, 20])`), which is in my opinion less readable then e.g. `plt.xylim( [0,6]  ,  [0,20] )`
What do you think?

**Comment by jklymak** [comment]
There are already lots of ways to do the same thing in matplotlib, which leads to confusion, particularly if implementations drift apart.  I think your proposal is close enough to `plt.axis`, and `axis` has a long long history (going back >30 years in Matlab), I think this would have a tough time being added.

**Comment by anntzer** [comment]
There's already both `axis` and also `gca().set(xlim=(5, 7), ylim=(9, 10))` which also works and is certainly quite readable.
Closing, as I think the chances of this getting in are close to nil.

**Comment by tacaswell** [comment]
@kolibril13 Is there someplace we could better document `axis` and `set(xlim=(), ylim=())` to make them easier to find?

**Comment by kolibril13** [comment]
Thanks for your responses.
I think in the documentation, there could be 
```py
https://matplotlib.org/api/pyplot_summary.html
```

**Comment by kolibril13** [comment]
Thanks for your responses.
I think in the documentation it could become clearer that axis can manipulate limits
https://matplotlib.org/api/pyplot_summary.html
![123](https://user-images.githubusercontent.com/44469195/74002450-600ec680-496f-11ea-8fd6-73f2a56c9398.png)
E.g. make "Convenience method to get or set some axis properties." to "Method to get or set some axis properties (e.g. xlim, ylim and xy-relations). Then people can find it more easily when searching there. Further,  it would be really nice to be able to use also `plt.axis([0, 6],[0, 20])`  and not only `plt.axis([0, 6,0, 20])` this would not break the current functionality,  but gives the code more structure.

**Comment by tacaswell** [comment]
I suspect that we could do some argument number and length parsing to allow `plt.axis(x, y)` to work...

Could you open a PR with the documentation change and maybe take a look at extending the axis API in that way?

**Comment by kolibril13** [comment]
> I suspect that we could do some argument number and length parsing to allow plt.axis(x, y) to work...

Nice! 
I will do the documentation change in around two weeks, when I have time for that

**Comment by anntzer** [comment]
Let's not try to make `axis(x, y)` work.  There's plenty of perfectly readable and barely longer-to-type alternatives available, *and* `axis` is so confusingly (very) different from `axes` which does completely different things and takes completely different arguments that I would rather "soft-deprecate" `axis` (without any removal plan -- it's too widely used to be worth it, and only a problem from a pedagogical PoV, not so much from a maintenance one).
