### ISSUE TITLE
XY axis line thickness/ or width.

### ISSUE THREAD

**Issue by vishwasgowda** [matplotlib/matplotlib#16426]
Hi,
I am trying to customize my plot to make it look prettier. However, I am having trouble finding the right names or examples to customize my plots. For example, I just want my XY axis lines to be thicker. Second, I would like to truncate the y-axis number to 3 digits. I can't seem to find the right examples or I might be doing it wrong. I appreciate it if you could help me in this regard. 

The below code with the commented line should still give an empty plot. 

**Code for reproduction**
`plt.figure(figsize =(30, 15), dpi=300)
# plt.plot(test1.index, test1['REV'], linewidth =10)
# plt.plot(sales_3_test.index, sales_3_test['Prediction'], color ='r', linewidth =10)
# # plt.plot(line_up_2017.index, line_up_2017['LU_REV_2017'], color='green', linewidth =5)
# plt.plot(ln_2018_1.index, ln_2018_1['LU_REV_2018'], color ='magenta', linewidth =10)
plt.legend(['Revenue_2019', 'Prediction_2019', 'Ln_Rev_2018 to 2020'], loc='best',
           fontsize= 30, edgecolor='black' )
plt.tick_params(axis= 'x',labelsize=30, length =6, pad=6, width=3, color='black')
plt.tick_params(axis='y', labelsize=30,length =6, pad=6, width=4)
plt.xlabel('Shipping_Date', fontsize=40, color='Green', labelpad=10, fontweight='bold')
plt.ylabel('Total_Revenue', fontsize=40, color='blue', labelpad=10, fontweight='bold')
plt.title('Comparing prediction against line up revenue and actual revenue', fontsize=40, 
          fontweight = 'bold', color='blue')
fmt = '${x:,.0f}'
plt.gca().yaxis.set_major_formatter(StrMethodFormatter(fmt))
plt.show()`

**Actual outcome**

<
![image](https://user-images.githubusercontent.com/28074675/73970629-796e2f00-48eb-11ea-9d75-1866f667cf19.png)
>

**Expected outcome**
I would like to see thicker lines on the x-axis and y-axis, and also truncate the numbers to few digits.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.3
  * Matplotlib backend (module://ipykernel.pylab.backend_inline):
  * Python version:3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

pip install

**Comment by jklymak** [comment]
This sort of user help is better suited to discourse.matplotlib.org or stackoverflow.  This is for tracking bugs.  Thanks for your understanding!
