### ISSUE TITLE
matplotlib 3.0.3 Missing Dependencies 

### ISSUE THREAD

**Issue by ToxicAvengerX** [matplotlib/matplotlib#16449]
Bug report

-Bug summary

It seems that on Windows 10 OS  matplotlib 3.0.3 fails to install due to dependencies missing.

Code for reproduction

python3 pip install matplotlib==3.0.3

Actual outcome

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jacob\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jacob\\AppData\\Local\\Temp\\pip-install-x4kmzuzm\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\jacob\\AppData\\Local\\Temp\\pip-install-x4kmzuzm\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jacob\AppData\Local\Temp\pip-install-x4kmzuzm\matplotlib\pip-egg-info'
         cwd: C:\Users\jacob\AppData\Local\Temp\pip-install-x4kmzuzm\matplotlib\
    Complete output (47 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019,
                            19:21:23) [MSC v.1916 32 bit (Intel)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.18.1]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Expected outcome

Matplotlib is installed without incident.

PC Details (I thought mattered)

Operating system: Windows 10
Python version: 2.7, 3.7, 3.8

**Comment by QuLogic** [comment]
It looks like there are [no wheels for Python 3.8](https://pypi.org/project/matplotlib/3.0.3/#files); are you sure it doesn't work on 3.7 too? Matplotlib 3 doesn't support Python 2.

**Comment by ToxicAvengerX** [comment]
no, i mean thats whats installed on my PC.

**Comment by jklymak** [comment]
@ToxicAvengerX I think that if you do `pip install` and there is a "wheel" then you will get dependencies like `freetype`.  If you don't have freetype, matplotlib cannot work, so either use  python 3.7 for which there is a "wheel", or install freetype manually.

**Comment by tacaswell** [comment]
Is there something pinning you to mpl3.0.3?  We are not going to release any more bug-fix releases in the 3.0.x series or produce py38 wheels for old releases.

I think you options are to :
 - upgrade to a newer version of Matplotlib
 - down grade to python 3.7
 - install freetype + libpng and a compiler to build Matplotlib from source

**Comment by ToxicAvengerX** [comment]
Downgrading to python 3.7 worked. I needed 3.0.3 Due to it being a dependency for MineRL. [minerl.io](url)

**Comment by tacaswell** [comment]
do you know why they are pinned to an old version of Matplotlib?
