### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'figure'

### ISSUE THREAD

**Issue by YubinYuan** [matplotlib/matplotlib#16458]
Bug report

**Bug summary**

The problem in running jupyter cannot be solved after uninstalling and reloading maplotlib several times
**Code for reproduction**
import tensorflow as tf
import numpy as np
import matplotlib as plt
x_data = np.linspace(-0.5,0.5,200)[:,np.newaxis]
noise = np.random.normal(0,0.02,x_data.shape)
y_data = np.square(x_data) + noise
x = tf.placeholder(tf.float32,[None,1])
y = tf.placeholder(tf.float32,[None,1])
Weights_L1 = tf.Variable(tf.random_normal([1,10]))
biases_L1 = tf.Variable(tf.zeros([1,10]))
Wx_plus_b_L1 = tf.matmul(x,Weights_L1) + biases_L1
L1 = tf.nn.tanh(Wx_plus_b_L1)
Weights_L2 = tf.Variable(tf.random_normal([10,1]))
biases_L2 = tf.Variable(tf.zeros([1,1]))
Wx_plus_b_L2 = tf.matmul(L1,Weights_L2) + biases_L2
prediction = tf.nn.tanh(Wx_plus_b_L2)
loss = tf.reduce_mean(tf.square(y-prediction))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(2000):
        sess.run(train_step,feed_dict={x:x_data,y:y_data})
    prediction_value = sess.run(prediction,feed_dict={x:x_data})
    plt.figure()
    plt.scatter(x_data,y_data)
    plt.plot(x_data,prediction_value,'r-',lw=5)
    plt.show()

**Actual outcome**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-6350becb1739> in <module>
     33         sess.run(train_step,feed_dict={x:x_data,y:y_data})
     34     prediction_value = sess.run(prediction,feed_dict={x:x_data})
---> 35     plt.figure()
     36     plt.scatter(x_data,y_data)
     37     plt.plot(x_data,prediction_value,'r-',lw=5)

AttributeError: module 'matplotlib' has no attribute 'figure'
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Get an image with prediction information

**Matplotlib version**
<!--Please specify your platform and versions of the relevant libraries you are using:-->
  * Operating system:Windows 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:Python3.7.4
  * Jupyter version (if applicable):6.0.3
  * Other libraries: 

I installed matplotlib from Anaconda Python Distribution through the default channel.

Thank you！

**Comment by ImportanceOfBeingErnest** [comment]
That's more or less a typo. `plt` is the usual alias for `matplotlib.pyplot`. So stick to the documentation (e.g. [the usage guide](https://matplotlib.org/tutorials/introductory/usage.html)) and `import matplotlib.pyplot as plt`.

**Comment by YubinYuan** [comment]
> That's more or less a typo. `plt` is the usual alias for `matplotlib.pyplot`. So stick to the documentation (e.g. [the usage guide](https://matplotlib.org/tutorials/introductory/usage.html)) and `import matplotlib.pyplot as plt`.

Thank you very much for solving the problem

**Comment by dupyo** [comment]
That's my problem, too. I solved the problem, too. Thank you very much!

**Comment by tbrkic** [comment]
**_

- [ ] @- > `[# I'M USING THIS](https://jupyter.org/try-jupyter/lab/)`

_**
