### ISSUE TITLE
Allow wedges of polar plots to include theta = 0.

### ISSUE THREAD

**Issue by gewoondim1** [matplotlib/matplotlib#16462]
### Feature request

**Summary**

When creating wedges fro polar plots, it is not possible to create a wedge which include theta = 0.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from math import pi

fig = plt.figure()
ax = plt.axes(polar=True)

ax.scatter([i*pi/6 for i in range 12], [1]*12)
ax.set_thetalim(300, 60)

plt.show()
```

```python
from matplotlib import pyplot as plt
from math import pi

fig = plt.figure()
ax = plt.axes(polar=True)

ax.scatter([i*pi/6 for i in range 12], [1]*12)
ax.set_thetalim(60, 300)

plt.show()
```

**Actual outcome**

Both code snippets produce the same outcome, a plot ranging from 60 degrees to 300 degrees.

**Expected outcome**

When `theta_min < 360 and theta_max > 0` the produced wedge should range from `theta_min` to `theta_max`

**Comment by ImportanceOfBeingErnest** [comment]
I might misunderstand the expected outcome. Independent of that, one would need to use radiants, instead of degrees. Then, something like

    ax.set_thetalim(np.deg2rad(-60), np.deg2rad(60))

would include `0`.

**Comment by gewoondim1** [comment]
The set_thetalim function actually uses degrees (which can be very confusing). See also #4986

**Comment by ImportanceOfBeingErnest** [comment]
Well, it's pretty confusing, so it *can*  be in degrees in case you use the `thetamin/max` arguments.
So, 

    ax.set_thetalim(np.deg2rad(-60), np.deg2rad(60))  # in radiants

is the same as 

    ax.set_thetalim(thetamin=-60, thetamax=60)  # in degrees


The [documentation](https://matplotlib.org/api/projections_api.html#matplotlib.projections.polar.PolarAxes.set_thetalim) would clearly need to be updated.

**Comment by jklymak** [comment]
That seems simply wrong.

**Comment by gewoondim1** [comment]
`ax.set_thetalim(thetamin=-60, thetamax=60)` is what I was looking for.

**Comment by timhoffm** [comment]
Is this still an issue other than inconsistent and confusing units. I'd defer the degree vs. rad topic to https://github.com/matplotlib/matplotlib/issues/4986#issuecomment-584860063.

**Comment by ImportanceOfBeingErnest** [comment]
I'd say this is a documentation issue. So from the docstring it should become clear that

* `set_thetalim(thetamin=a, thetamax=b)` is in degrees, and `set_thetalim(a, b)` is in radiants.
* negative numbers can/should be used when crossing the zero point.

Possible signature changes, deprecations etc. are more long term and can be tracked in #4986.
