### ISSUE TITLE
Add link to blog to front page

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#16487]
Trying to get more content for the blog & figure linking it on the homepage would be a good place to do so (and totally forgot about it when that issue went in). 

It should go with the Twitter and Instagram links since it's another more showcase oriented site. The link is https://matplotlib.org/matplotblog/

**Comment by donchanee** [comment]
Hello @story645,
I would like to work on this issue.

Shall I write like this guide? [Link](https://matplotlib.org/matplotblog/posts/how-to-contribute/)

(p.s. This is my first time to contribute to open source! matplotlib is my favorite lib.)

**Comment by story645** [comment]
Hi, awesome! Your enthusiasm is awesome, but that guide would be overkill for this issue. The front page now has this section: 
![image](https://user-images.githubusercontent.com/1300499/74458876-5944ef80-4e58-11ea-9ac3-f64122f90da2.png)

and this subsection:
```Tweet us at Twitter! or see cool plots on Instagram!
```
`Python <http://www.python.org/>`_
should be amended to something like:
```Tweet us at `Twitter <twitter.com/matplotlib>`_! See cool plots on `Instagram<instagram.com/matplotart/>`_ ! Check out our ` blog <https://matplotlib.org/matplotblog/>`_
```
