### ISSUE TITLE
long string of format_coord in osx backend

### ISSUE THREAD

**Issue by yuezhihan** [matplotlib/matplotlib#16498]
### Bug report

**Bug summary**

I tried to customize the text of status bar using `format_coord`. When the text is long, the status bar of **MacOSX** backend wouldn't display properly (see image). It seems that the width of the text box does not automatically adjust with the size of the window.

<img width="1221" alt="WX20200214-000436@2x" src="https://user-images.githubusercontent.com/18026801/74454773-58937400-4ebf-11ea-847a-290e689ee97a.png">

**Code for reproduction**

```python
ax.format_coord = A_LONG_STRING_HERE
```

**Matplotlib version**
  * Operating system: macos 10.14.6
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.3

**Comment by QuLogic** [comment]
Indeed, the text box in the macOS backend does have a fixed width:
https://github.com/matplotlib/matplotlib/blob/a712590129628f1ecd56b7e5fe93d18debe261c1/src/_macosx.m#L1252-L1255
But it would take someone more familiar with macOS than I to know whether it can auto-resize.
