### ISSUE TITLE
text object not respecting string size 

### ISSUE THREAD

**Issue by jmoran2611** [matplotlib/matplotlib#16497]
### Bug report

**Bug summary**

If you have a formated string, lets say :
```python
 '{:>7.02f}'.format(100.00) 
```

The text created won't fully respect the formating of the string. The total size of the string changes:

```python
iimport matplotlib.pyplot as plt
import matplotlib.pyplot as plt
fig,ax=plt.subplots(1,1)
ax.text(0.5, 0.5, 'Time:'+'{:>10.02f}'.format(1)+'s',fontsize=15)
ax.text(0.5, 0.4, 'Time:'+'{:>10.02f}'.format(100)+'s',fontsize=15)
plt.show()
print("Expected behavior")
print('Time:'+'{:>7.02f}'.format(1)+'s')
print('Time:'+'{:>7.02f}'.format(100)+'s')
```

![image](https://user-images.githubusercontent.com/32171497/74446577-65d94000-4e78-11ea-8d2d-c9dfa6ea2da0.png)

```

**Expected outcome**

That Text keeps the string format

**Matplotlib version**

  * Operating system: CentOS Linux
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.7.4

**Comment by anntzer** [comment]
This is because the default font is not monospace (https://en.wikipedia.org/wiki/Monospaced_font); you need to select such a font.

**Comment by jmoran2611** [comment]
Thank you very much. Somehow I had never thought about this.
