### ISSUE TITLE
Example/tutorials warn due to new pcolormesh shading

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#16493]
The new warning introduced in #16258 is now being triggered by several examples, and the tutorials. At least for the latter, I assume we don't want to go through and just do a blanket `Z[:-1, :-1]`, but instead take a more nuanced approach. Though possibly not; I have not looked at the issues yet, but I don't want to forget about this.

**Comment by jklymak** [comment]
We probably want to change to `shading='auto'` for these.

**Comment by jklymak** [comment]
Did you track which ones have the warning?

**Comment by jklymak** [comment]
I found one.  Are there more?

**Comment by jklymak** [comment]
Re-opening in case there are more...

**Comment by QuLogic** [comment]
Here is the list:
* /matplotlib/examples/userdemo/colormap_normalizations_bounds.py:38
* /matplotlib/examples/userdemo/colormap_normalizations_bounds.py:41
* /matplotlib/examples/userdemo/colormap_normalizations_custom.py:44
* /matplotlib/examples/userdemo/colormap_normalizations_custom.py:47
* /matplotlib/examples/userdemo/colormap_normalizations_diverging.py:39
* /matplotlib/examples/userdemo/colormap_normalizations_lognorm.py:29
* /matplotlib/examples/userdemo/colormap_normalizations_lognorm.py:32
* /matplotlib/examples/userdemo/colormap_normalizations_power.py:26
* /matplotlib/examples/userdemo/colormap_normalizations_power.py:29
* /matplotlib/examples/userdemo/colormap_normalizations_symlognorm.py:33
* /matplotlib/examples/userdemo/colormap_normalizations_symlognorm.py:36
* /matplotlib/tutorials/colors/colormapnorms.py:65
* /matplotlib/tutorials/colors/colormapnorms.py:68
* /matplotlib/tutorials/colors/colormapnorms.py:102
* /matplotlib/tutorials/colors/colormapnorms.py:105
* /matplotlib/tutorials/colors/colormapnorms.py:134
* /matplotlib/tutorials/colors/colormapnorms.py:137
* /matplotlib/tutorials/colors/colormapnorms.py:176
* /matplotlib/tutorials/colors/colormapnorms.py:182
* /matplotlib/tutorials/colors/colormapnorms.py:185
* /matplotlib/tutorials/colors/colormapnorms.py:221
* /matplotlib/tutorials/colors/colormapnorms.py:252
* matplotlib/examples/images_contours_and_fields/pcolormesh_grids.py:66
* matplotlib/examples/images_contours_and_fields/pcolormesh_levels.py:67
* matplotlib/examples/specialty_plots/leftventricle_bulleye.py:82
* matplotlib/examples/specialty_plots/leftventricle_bulleye.py:96
* matplotlib/examples/specialty_plots/leftventricle_bulleye.py:110
* matplotlib/examples/specialty_plots/leftventricle_bulleye.py:122
* matplotlib/examples/subplots_axes_and_figures/axes_margins.py:65
* matplotlib/examples/userdemo/colormap_normalizations.py:32
* matplotlib/examples/userdemo/colormap_normalizations.py:35
* matplotlib/examples/userdemo/colormap_normalizations.py:49
* matplotlib/examples/userdemo/colormap_normalizations.py:52
* matplotlib/examples/userdemo/colormap_normalizations.py:73
* matplotlib/examples/userdemo/colormap_normalizations.py:76
* matplotlib/examples/userdemo/colormap_normalizations.py:111
* matplotlib/examples/userdemo/colormap_normalizations.py:114
* matplotlib/examples/userdemo/colormap_normalizations.py:129
* matplotlib/examples/userdemo/colormap_normalizations.py:135
* matplotlib/examples/userdemo/colormap_normalizations.py:138
* matplotlib/examples/userdemo/colormap_normalizations_bounds.py:32

I believe you fixed:
* matplotlib/examples/images_contours_and_fields/pcolor_demo.py:100
* matplotlib/examples/images_contours_and_fields/pcolor_demo.py:103
