### ISSUE TITLE
Setting a thetalim > 2pi gives odd results

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#16501]
### Bug report

**Bug summary**

Doing `set_thetalim(0, >2pi)` on a polar plot produces an odd result; see below. There are 400 and 500 degree ticks that probably shouldn't be there, and a floating 200 degree tick (but no 300 degree tick...). 

I would be pro erroring out if someone tries to set a limit that's not in the range `[0, 2pi]` - any thoughts?

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

ax = plt.subplot(111, projection='polar')
ax.set_thetalim(0, 3 * np.pi)

plt.show()
```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/6197628/74464472-78a94000-4e8b-11ea-8861-5462ef966589.png)

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
I *guess* the slightly more lenient solution would be to only require that tmax-tmin < 2pi, and error out otherwise?  If someone asks 400°-600° we can always subtract 360° and draw 40°-260° but label 400-600?

**Comment by prasadve** [comment]
Our team would like to start working on this bug if nobody has started it. Thanks

**Comment by timhoffm** [comment]
Go for it.

**Comment by timhoffm** [comment]
Closed by 16717.
