### ISSUE TITLE
`Axes.autoscale` has scale-inconsistent margins

### ISSUE THREAD

**Issue by scottgigante** [matplotlib/matplotlib#16539]
### Bug report

**Bug summary**

Autoscaling axis behaviour is inconsistent for data on very small scales

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
x = np.repeat(np.arange(10), 10)
y = np.tile(np.arange(10), 10)

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
axes[0].scatter(x, y)
axes[1].scatter(x*1e3, y*1e3)
axes[2].scatter(x*1e-3, y*1e-3)
axes[3].scatter(x*1e-6, y*1e-6)
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/8499679/74611934-92869500-50ce-11ea-9434-757cd5ae46ea.png)

**Expected outcome**

The plot should scale in the same way regardless of absolute values of data range. E.g.

![image](https://user-images.githubusercontent.com/8499679/74611949-bf3aac80-50ce-11ea-9011-a2b30971ad77.png)

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.8.1
  * Jupyter version (if applicable): jupyter-client==5.3.4 jupyter-console==6.0.0 jupyter-core==4.6.1

Installed with pacman on arch linux (installs from source.)

**Comment by ImportanceOfBeingErnest** [comment]
Thanks for the bug report. This is one of the points tracked inhttps://github.com/matplotlib/matplotlib/issues/7413. This part is fixed in current master by #13642. You can try the release candidate of matplotlib 3.2 to see it in action.

**Comment by scottgigante** [comment]
Thanks, and apologies for the noise!

**Comment by tacaswell** [comment]
@scottgigante Better a bit of noise than bugs going un-reported.
