### ISSUE TITLE
Problem with scatter size when set xlim/ylim

### ISSUE THREAD

**Issue by GYHHAHA** [matplotlib/matplotlib#16548]
```python
fig = plt.figure(figsize=(10,10))
gs = gridspec.GridSpec(1,1) 
ax0 = plt.subplot(gs[0])
ax0.scatter([0],[1],s=20000)
ax0.scatter([0],[3],s=20000)
ax0.set_xlim(-2,2)
ax0.set_ylim(-5,5)
```
This result of the above code shows two intersecting circles.
![bug1](https://user-images.githubusercontent.com/41546976/74694942-15256680-522d-11ea-84c5-c9fb9ff6d563.png)
But if I cancel the set_xlim/set_ylim step, these two circles are separated.
```python
fig = plt.figure(figsize=(10,10))
gs = gridspec.GridSpec(1,1) 
ax0 = plt.subplot(gs[0])
ax0.scatter([0],[1],s=20000)
ax0.scatter([0],[3],s=20000)
```
![bug2](https://user-images.githubusercontent.com/41546976/74694989-4dc54000-522d-11ea-8bb0-6154101fd48a.png)
So how to find a more explicit way to decide the size of scatters?
Thanks!

**Comment by GYHHAHA** [comment]
I find the problem can be solved in [this](https://stackoverflow.com/questions/48172928/scale-matplotlib-pyplot-axes-scatter-markersize-by-x-scale/48174228#48174228) way.
Still Thanks!

**Comment by story645** [comment]
Is there a reason you can't set `s` to a different value, like `s=10000`?

**Comment by timhoffm** [comment]
For future reference: Only marker positions are included in auto-scaling; marker sizes are not. For really large markers this can lead to observed clipping.

**Comment by GYHHAHA** [comment]
Whether exists a more convenient way to scatter with a given radius? (suppose it's a circle marker)

**Comment by GYHHAHA** [comment]
> Is there a reason you can't set `s` to a different value, like `s=10000`?

Actually a different value can be set.

**Comment by tacaswell** [comment]
@GYHHAHA Depending on what you are doing, you may be better off using https://matplotlib.org/api/_as_gen/matplotlib.patches.Circle.html  It is a bit fussier to use (you will have to create the artists and add them to the axes your self), but it will let you control the size of the circles in data space (rather than in pixel space).

**Comment by timhoffm** [comment]
An alternative workaround is to impose larger margins around the data: `plt.rcParams['axes.ymargin'] = 0.2` when you know, you have very large markers.

**Comment by GYHHAHA** [comment]
Indeed, it's more convenient to apply circle under this situation. Thanks. @tacaswell

**Comment by ImportanceOfBeingErnest** [comment]
In addition to the options shown in the [SO post](https://stackoverflow.com/questions/48172928/scale-matplotlib-pyplot-axes-scatter-markersize-by-x-scale/48174228#48174228) OP linked to, probably the fastest option would be to use a PathCollection.

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.collections as mcoll
import matplotlib.transforms as mtrans
import matplotlib.markers as mmarkers

c = mcoll.PathCollection(
                [mmarkers.MarkerStyle("o").get_path()],
                offsets=np.repeat(np.arange(10),2).reshape(10,2),
                edgecolors=["k"]*10,
                transOffset=mtrans.IdentityTransform(),
                offset_position="data")
plt.gca().add_collection(c)
plt.gca().set(xlim=(-2, 11), ylim=(-2,11))
plt.gca().set_aspect("equal")
plt.show()
```

I think in view of this, it's relevant to discuss the possibility to either not deprecate `offset_position="data"` or to provide a public replacement option.

**Comment by GYHHAHA** [comment]
Yes, it seems more natural. Thanks for your solution! @ImportanceOfBeingErnest
