### ISSUE TITLE
@sabyagunnersya I try both (n,1) and (n,). Both of them are not working! Is there any other solution? Thanks!

### ISSUE THREAD

**Issue by developerpawandeep** [matplotlib/matplotlib#16554]
@sabyagunnersya I try both (n,1) and (n,). Both of them are not working! Is there any other solution? Thanks!
ValueError: c of shape (303262, 1) not acceptable as a color sequence for x with size 303262, y with size 303262
ValueError: c of shape (303262,) not acceptable as a color sequence for x with size 303262, y with size 303262

_Originally posted by @weihuaguo in https://github.com/matplotlib/matplotlib/issues/9209#issuecomment-538565708_

**Comment by developerpawandeep** [comment]
ValueError: 'c' argument has 93 elements, which is not acceptable for use with 'x' with size 93, 'y' with size 93.

ValueError: RGBA values should be within 0-1 range

using same script for 2 diff scatter plots , but getting error on 1 and working fine on other

**Comment by dstansby** [comment]
Could you post a small code example that triggers the problem you're encountering? Could you also let us know which version of Maptlotlib you're using? Thanks!

**Comment by developerpawandeep** [comment]
> Could you post a small code example that triggers the problem you're encountering? Could you also let us know which version of Maptlotlib you're using? Thanks!

well i resolved the problem from my end ( problem was i was giving random of (255,255,255) as input but it only accepts (1,1,1) color random range in decimals.
