### ISSUE TITLE
fill draws a mirror image

### ISSUE THREAD

**Issue by lolaclinton** [matplotlib/matplotlib#16557]
### Bug report

**Bug summary**
When I plot a polygon into a canvas it draws its vertical mirror image too.

**Code for reproduction**

```python
# Paste your code here
#
#
```

def hull_matrix(x, img):
    fig, ax = plt.subplots()
    s=img.shape
    #Image from plot
    ax.axis('off')
    fig.tight_layout(pad=0)
    fig.set_dpi(1)
    fig.set_size_inches((s[1],s[0]))
    # To remove the huge white borders
    ax.margins(0)
    ax.set(xlim=(0, s[1]), ylim=(0, s[0]))
    plt.fill(x[:,1], x[:,0])
    fig.canvas.draw()
    image_from_plot = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
    image_from_plot = image_from_plot.reshape(fig.canvas.get_width_height()[::-1] + (3,))
    return image_from_plot

x = array([[830., 734.],
       [829., 491.],
       [831., 444.],
       [854.,  70.],
       [859.,  15.],
       [863.,   1.],
       [939.,   0.],
       [939., 790.],
       [937., 819.],
       [935., 836.],
       [931., 840.],
       [925., 840.]])

# img is just used for the dimensions, img size is
![flipped polygon](https://user-images.githubusercontent.com/7840266/74851654-88040f80-5309-11ea-997f-294faf75d1bf.png)
 (1333, 1088, 4)
m=hull_matrix(x, img)
plt.imshow(m)
plt.show()

where
**Actual outcome**

![flipped polygon](https://user-images.githubusercontent.com/7840266/74851825-c7326080-5309-11ea-9097-9b651806311e.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Only one polygon. Not the mirror image.

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries: 

conda
matplotlib                3.1.1            py36h54f8f79_0
module://ipykernel.pylab.backend_inline

**Comment by ImportanceOfBeingErnest** [comment]
Please consider that the axes direction changes between a normal plot and an `imshow` image - hence the mirroring. Also see https://matplotlib.org/tutorials/intermediate/imshow_extent.html

The reason there are two shapes in the figure is that you show the `plt.fill`, as well as the content of the figure at the time the fill is created inside the same figure. Remove the `ax.axis('off')` to observe what you're actually doing.

I cannot currently identify any bug or undesired behaviour here, so closing this. However, if there is anything more that would deserve our attention here, please ping to reopen.
