### ISSUE TITLE
'It is not currently possible to manually set the aspect ' NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

### ISSUE THREAD

**Issue by Marietto2008** [matplotlib/matplotlib#16568]
Hello.

I'm trying to directly convert real-person videos to the motion of animation models (i.e. Miku, Anmicius) following the instructions located here :

https://github.com/peterljq/OpenMMD

and this :

https://www.youtube.com/watch?v=hKx6jl9a5-I

The first thing that I did has been to use openpose 1.3.1 that's inside the repo,but it didn't work. When I do "bin\OpenPoseDemo.exe --video rp.mov --write_json json_rp --write_video rp2.avi --number_people_max 1" I see that the openpose output window remains black. So,I used the installation of openpose 1.5 and I changed :

....the code of /3D Pose Baseline to VMD/src/openpose_3dpose_sandbox_vmd_new.py, line 104, to for o in range(0,len(_tmp_data),5):, from 3 to 5. Because when it was 3 the OpenMMD errored (when executed the "3D Pose Baseline to VMD"/OpenposeTo3D.bat):

after some time of work,the final message has been something like this :

Traceback (most recent call last):
File "src/openpose_3dpose_sandbox_vmd.py", line 484, in
tf.app.run()
File "C:\Users\marietto2020\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "C:\Users\marietto2020\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299, in run
_run_main(main, args)
File "C:\Users\marietto2020\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250, in _run_main
sys.exit(main(argv))
File "src/openpose_3dpose_sandbox_vmd.py", line 412, in main
viz.show3Dpose(p3d, ax2, lcolor="#FF0000", rcolor="#0000FF", add_labels=True)
File "K:\Pers\cg\MMD\OpenMMD\3d-pose-baseline-vmd\src\viz.py", line 55, in show3Dpose
ax.set_aspect('equal')
File "C:\Users\marietto2020\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\axes_base.py", line 1281, in set_aspect
'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

The full story can be read here : https://github.com/peterljq/OpenMMD/pull/29

is there a fix for that ? thanks.

**Comment by ImportanceOfBeingErnest** [comment]
The project you are using needs to remove [this line](https://github.com/peterljq/OpenMMD/blob/a7a606f191dc2c13ee21a11b7063e2f98d86519a/3D%20Pose%20Baseline%20to%20VMD/src/viz.py#L110) from their code.  

Closing here, because this is outside of the responsibility of matplotlib, and I would think the error message is clear enough.

**Comment by Marietto2008** [comment]
it worked. thanks man.

**Comment by wy-luke** [comment]
thanks

**Comment by wy-luke** [comment]
> The project you are using needs to remove [this line](https://github.com/peterljq/OpenMMD/blob/a7a606f191dc2c13ee21a11b7063e2f98d86519a/3D%20Pose%20Baseline%20to%20VMD/src/viz.py#L110) from their code.
> 
> Closing here, because this is outside of the responsibility of matplotlib, and I would think the error message is clear enough.

thanks
