### ISSUE TITLE
Slider demo not working in Pycharm nor Jupyter

### ISSUE THREAD

**Issue by nyck33** [matplotlib/matplotlib#16570]
### Bug report

**Bug summary**

The slider and radio buttons are unresponsive, not even clickable.
**Code for reproduction**

The code is from this site:  https://matplotlib.org/3.1.1/gallery/widgets/slider_demo.html
```python
# Paste your code here
#
#
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/25189545/75228938-d11eee00-5765-11ea-99d1-f6bf51196f4c.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries: 

pip install matplotlib==3.1.1

**Comment by nyck33** [comment]
Neither is this one:  https://matplotlib.org/2.0.2/examples/widgets/slider_demo.html

**Comment by nyck33** [comment]
So I saw that it needs an interactive backend but `plt.ion()` doesn't work
So I tried `matplotlib.interactive()` but it's telling me I'm missing 1 required position argument 'b'.
This is really really confusing.

**Comment by nyck33** [comment]
Got it working with:

```
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button, RadioButtons
import matplotlib

matplotlib.use('TkAgg')
```

**Comment by kiwiheretic** [comment]
I presume this means it still doesn't work on Jupyter?

**Comment by jklymak** [comment]
The default Jupyter inline backend is not interactive. The notebook (nbagg) and Jupyter lab backends _are_ interactive and sliders should work.
