### ISSUE TITLE
azure pipelines doesn't seem to respect [ci skip]

### ISSUE THREAD

**Issue by pharshalp** [matplotlib/matplotlib#16574]
### Bug report

**Bug summary**
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml says [ci skip] in commit message should disable CI. This doesn't seem to work with the current matplotlib azure pipelines setup.

this will be useful to have (for WIP draft PRs) so as to not block CI resources.

**Comment by rcomer** [comment]
I have successfully used `[skip ci]` in recent PRs, e.g. #26045.  So I guess whatever the problem was has been fixed.
