### ISSUE TITLE
Segmentation fault when blitting onto closed figure (TkAgg)

### ISSUE THREAD

**Issue by dranjan** [matplotlib/matplotlib#16580]
### Bug report

**Bug summary**

With the "TkAgg" backend, calling `figure.canvas.blit` on a closed `Figure` instance crashes the Python interpreter with "segmentation fault."  An easy workaround is to check if the figure is closed using `plt.fignum_exists(figure.number)` before attempting the blit operation.

I tried a couple other backends and they didn't crash.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots()
axes.imshow(np.zeros((1000, 1000, 3), dtype=np.uint8))
fig.canvas.draw()
plt.close(fig.number)
fig.canvas.blit(axes.bbox)
```

**Actual outcome**
```
zsh: segmentation fault (core dumped)  python segfault2.py
```

**Expected outcome**

I'm not really sure, but segfaulting the interpreter isn't it.  I think an acceptable alternative would be raising a Python exception from within matplotlib.

**Matplotlib version**

  * Operating system: Ubuntu 18.04.4
  * Matplotlib version: 3.1.3
  * Matplotlib backend: TkAgg
  * Python version: 3.6.9

matplotlib was installed from pip in a virtualenv.

**Comment by anntzer** [comment]
Looks like we need to check whether the tk image handle has been deleted.  A cursory look at the API docs didn't reveal any official way to do so, but something like
```patch
diff --git i/lib/matplotlib/backends/_backend_tk.py w/lib/matplotlib/backends/_backend_tk.py
index 6556d104f..9c1d7d070 100644
--- i/lib/matplotlib/backends/_backend_tk.py
+++ w/lib/matplotlib/backends/_backend_tk.py
@@ -75,6 +75,10 @@ def blit(photoimage, aggimage, offsets, bbox=None):
     else:
         photoimage.blank()
         bboxptr = (0, width, 0, height)
+    try:
+        photoimage.tk.call(photoimage, "get", 0, 0)
+    except tk.TclError:
+        raise RuntimeError(f"{photoimage} has been deleted") from None
     _tkagg.blit(
         photoimage.tk.interpaddr(), str(photoimage), dataptr, offsets, bboxptr)
```
appears to work.
(Something that could go into tkagg.cpp without going through the Tk interpreter would likely be both faster and more robust, though.)

**Comment by QuLogic** [comment]
That might fail if `bbox = None`, right?

**Comment by anntzer** [comment]
Also, looks like the simpler check is just `photoimage.tk.call("info", "commands", photoimage)` (non-empty iff photoimage exists).
