### ISSUE TITLE
Hi, I'm new to python and trying to learn coding on my own. But getting error while trying to load the packages "Error loading package list:connect timed out". where I'. using python 3.7, pycharm as IDE. Could anyone please help me to fix the error 

### ISSUE THREAD

**Issue by Suresh573** [matplotlib/matplotlib#16582]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
It's not possible to identify any problem with matplotlib here. I'd recommend bringing your problem up at any general help forum, but make sure to write a clear and reproducible problem description, so people have a chance to understand it.
