### ISSUE TITLE
Greek alphabet '$\xi$' cannot be displayed 

### ISSUE THREAD

**Issue by richannan** [matplotlib/matplotlib#16598]
### Bug report

**Bug summary**

Some Greek alphabets (such as: alpha, beta, xi) cannot be displayed in the axis of figure. However, other alphabets (like: phi, lambda, omega etc) get printed.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
labels = ['xxxx', 'yyyy']

maximum_N = [3.5677, 3.5955]
minimum_N = [-3.4626, -3.4946]
mean_N = [0.0519, -0.0500]
std_N = [1.1707, 1.1804]

maximum_E = [9.7301, 9.7541]
minimum_E = [-9.8428, -9.8634]
mean_E = [-0.0510, -0.0544]
std_E = [3.2591, 3.2698]

x = np.arange(len(labels))  
width = 0.2  
fig, ax = plt.subplots(1,2)
maxi_N = ax[0].bar(x, maximum_N, width, label='Maximum')
mini_N = ax[0].bar(x, minimum_N, width, label='Minimum')
mini_N = ax[0].bar(x, mean_N, width, label='Mean')
mini_N = ax[0].bar(x, std_N, width, label='std')

ax[0].set_ylabel('$\eta$ (sec)')
ax[0].set_title(f'Statistics in $\eta$')
ax[0].set_xticks(x) 
ax[0].set_xticklabels(labels)
ax[0].legend()

maxi_E = ax[1].bar(x, maximum_E, width, label='Maximum')
mini_E = ax[1].bar(x, minimum_E, width, label='Minimum')
mini_E = ax[1].bar(x, mean_E, width, label='Mean')
mini_E = ax[1].bar(x, std_E, width, label='std')

#ax[1].set_ylabel('$\xi$ (sec)')         # returns error for alpha, beta, xi
#ax[1].set_title(f'Statistics in $\xi$') # returns error for alpha, beta, xi
ax[1].set_xticks(x)
ax[1].set_xticklabels(labels)
ax[1].legend()

fig.tight_layout()
plt.show()
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:  Windows
  * Matplotlib version: 3.0.3 (conda) & 3.1.1 (pip)
  * Matplotlib backend (`print(matplotlib.get_backend())`): ipykernel.pylab.backend_inline & TkAgg
  * Python version: 3.7
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: numpy

By commenting out the two problematic lines, the code is okay but not what I wanted.

I installed Matplotlib from both pip & conda.
![code_shot](https://user-images.githubusercontent.com/46886513/75568002-64983d80-5a4a-11ea-9768-fd56ca158bfb.jpg)

**Comment by ImportanceOfBeingErnest** [comment]
Consider the [MathText tutorial](https://matplotlib.org/tutorials/text/mathtext.html); it uses raw strings throughout, `r"$\alpha$"`. Equally it would be possible to escape the backslash with another one, `"$\\alpha$"`. 

The error *"unicode error unicodeescape codec can't decode bytes in position 2-3"* is googleable, so I think, there is nothing to do here, hence closing.

**Comment by tacaswell** [comment]
The `SyntaxError` is being raised by the Python parser/interpreter before we are even called so I don't think there is anything we can do about this even if we wanted to.

To help sign-post future google searches:

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> '$\xi&$'
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 1-2: truncated \xXX escape
>>> 

```

If you have further issues like this @richannan please ask on https://discourse.matplotlib.org
