### ISSUE TITLE
Different rendring between show() and savefig()

### ISSUE THREAD

**Issue by student-sx** [matplotlib/matplotlib#16628]
Savefig() gives me a different output than show() in the following example

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np



# matplotlib.rc('font', family='serif')
# matplotlib.rc('font', size=16)
# matplotlib.rc('legend', fontsize=16)
# matplotlib.rc('legend', numpoints=1)
# matplotlib.rc('legend', handlelength=1.5)
# matplotlib.rc('legend', frameon=False)
# matplotlib.rc('xtick.major', pad=7)
# matplotlib.rc('xtick.minor', pad=7)
# matplotlib.rc('text', usetex=True)
# matplotlib.rc('text.latex', 
#               preamble=[r'\usepackage[T1]{fontenc}',
#                         r'\usepackage{amsmath}',
#                         r'\usepackage{txfonts}',
#                         r'\usepackage{textcomp}'])
 



X = np.arange(-10, 10, 1)
Y = np.arange(-10, 10, 1)
U, V = np.meshgrid(X, Y)

R = np.sqrt(U**2 + V**2)

fig, ax = plt.subplots()
q = ax.quiver(X, Y, U/R, V/R,color='gray',scale_units='inches',scale=4)

ax.set_title('Math test: $\int_a^b f(x) \,\mathrm{d}x$')

plt.savefig('quiver_test.pdf',dpi=fig.dpi)
plt.show()

```

Result of show():

![Selection_029](https://user-images.githubusercontent.com/18629143/75678767-a31e3a00-5c8e-11ea-875b-b9d4906dd6a7.png)

Resulting pdf:

![Selection_028](https://user-images.githubusercontent.com/18629143/75678708-85e96b80-5c8e-11ea-837a-3f881864d711.png)

**Matplotlib version**

  * Operating system: Linux (ubuntu 19.04)
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.3

How can I force savefig to produce exactly the same output as show() (even with the font and latex settings added, which I commented out in my code above)

**Comment by ImportanceOfBeingErnest** [comment]
It looks like you changed the figure size of the shown figure, e.g. by maximizing the figure window to screen size or similar. If you don't do that, both figures will be the same.

**Comment by student-sx** [comment]
No I didn't rescale it.

**Comment by ImportanceOfBeingErnest** [comment]
If the figure wasn't changed, it would have dimensions 640 by 480 pixels. Given that it has 1604 by 899 pixels *something* needs to cause it to change. That could be a system setting to maximize the GUI window, or a doubleclick, which wasn't on purpose or anything similar.

**Comment by jklymak** [comment]
Also please make sure that your rcparameters are all cleared (i.e. move `~/.matplotlib/matplotlibrc` to `~/.matplotlib/matplotlibrc.Old`) and try again.  This seems unlikely to be a matplotlib bug.

**Comment by timhoffm** [comment]
By default the first plot including the window should look similar to this.

![grafik](https://user-images.githubusercontent.com/2836374/75801708-ddb1d080-5d7b-11ea-9839-99e9545def8a.png)

**Comment by student-sx** [comment]
Hm. I have saved the figure from the show command using a screenshot. If I do it via the save button below, it looks like
![Figure_1](https://user-images.githubusercontent.com/18629143/75813986-435c8780-5d91-11ea-9e2f-27a435acf48b.png)

Exactly like my screenshot. I also don't have any `.matplotlib` directory.

**Comment by ImportanceOfBeingErnest** [comment]
Could you show a screenshot of your complete screen? What's your screen's resolution? Do you have a special window manager installed in ubuntu? Do you use some "high-dpi" setting?

**Comment by student-sx** [comment]
I am using xmonad. Screen resolution depends if I use the laptop screen or an external monitor, but both times the same. Yes I think I have some high dpi settings for qt and gtk.

**Comment by timhoffm** [comment]
HiDPI may influence the rendering, but it should not affect the aspect ratio of the figure.

**Comment by jklymak** [comment]
Try installing qt and setting the backend to qt5Agg?  Just to see if this is backend dependent?

**Comment by tacaswell** [comment]
Can you put in a `print(fig.get_size_inches())` before and after `plt.show()`?  My guess is that when it is getting tiled by xmonad the size is getting changed (to make it much bigger).  The fonts are sized in absolute units so if you make the figure bigger and then scale the two to be the same size the font will look way smaller in the bigger image.

**Comment by jklymak** [comment]
I'll close for lack of response but feel free to get back to us if we can help....
