### ISSUE TITLE
Error in Agg backend's PNG renderer when `markeredgewidth > markersize`

### ISSUE THREAD

**Issue by brunobeltran** [matplotlib/matplotlib#16621]
### Bug report

**Bug summary**

Whenever the edge width of a marker is increased beyond the size of the marker, you would want the marker to 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
for i in range(0, 150, 20):
    fig, ax = plt.subplots()
    lines = ax.plot(0, 0, marker='p', markersize=60, markeredgewidth=i, 
                    markeredgecolor='k', clip_on=False)
    plt.xlim([-0.04, 0.04])
    plt.ylim([-0.04, 0.04])
    plt.savefig(f'/home/bbeltr1/Downloads/test_{i}.png')
fig._cachedRenderer
```

**Actual outcome**

While the outer extents of the pentagon's edge appear correct, you can see that the inner extents begin to recede away from the center as the edge width is set larger and larger, until eventually the original marker is fully visible again, along with some of the background.

Console output:
`<matplotlib.backends.backend_agg.RendererAgg at 0x7f5277bf0e80>`

Saved images:
![test_0](https://user-images.githubusercontent.com/1475390/75633133-397f2c80-5bb7-11ea-870c-72d336625caa.png)
![test_20](https://user-images.githubusercontent.com/1475390/75633134-3b48f000-5bb7-11ea-93f7-d6e1ff4b4523.png)
![test_40](https://user-images.githubusercontent.com/1475390/75633135-3d12b380-5bb7-11ea-8ae6-8e96145ac49d.png)
![test_60](https://user-images.githubusercontent.com/1475390/75633136-3edc7700-5bb7-11ea-8d9f-e544f7919c3f.png)
![test_80](https://user-images.githubusercontent.com/1475390/75633138-41d76780-5bb7-11ea-912f-67d4cda2c0ac.png)
![test_100](https://user-images.githubusercontent.com/1475390/75633140-43a12b00-5bb7-11ea-9b51-7a78eb2e2dc1.png)
![test_120](https://user-images.githubusercontent.com/1475390/75633143-4734b200-5bb7-11ea-9379-952432ecaf89.png)
![test_140](https://user-images.githubusercontent.com/1475390/75633144-4865df00-5bb7-11ea-9f81-ae6e1aa4a1d9.png)

**Expected outcome**

The expected outcome is a fully-shaded pentagon (due to the edge being huge). My PDF backend does this correctly, as seen below in a screenshot  of what `test_140.pdf` looks like if I save as `'test_{i}.pdf'` instead:

![test_140 pdf](https://user-images.githubusercontent.com/1475390/75633195-b5797480-5bb7-11ea-9c32-7eeb07e16a3d.png)

**Matplotlib version**

  * Operating system: Debian 9
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline` is what gets printed, and inline plots also show this error, but I can take Jupyter out of the loop by saving directly to file. Both cases are apparently using `RendererAgg` to make the PNG, as seen above.
  * Python version: 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

Matplotlib was installed and updated via the default conda channel.

**Comment by brunobeltran** [comment]
I'm sure whoever (if anyone) eventually tackles this will notice, but this looks like a typical "even/odd" vs "non-zero" fill style mix up (see e.g. https://www.slideshare.net/Mark_Kilgard/22pathrender, slide 21).

**Comment by tacaswell** [comment]
I wonder if mplcairo has this problem...

That is wild how did you find this?

**Comment by QuLogic** [comment]
This does not affect mplcairo:
![image](https://user-images.githubusercontent.com/302469/76195361-8027e480-61be-11ea-8a2a-6717a705f967.png)

**Comment by anntzer** [comment]
This also doesn't seem to affect mplcairo even if setting the fill rule (with cairo_set_fill_rule) to even-odd (the default is nonzero).

**Comment by brunobeltran** [comment]
> I wonder if mplcairo has this problem...
> 
> That is wild how did you find this?

Writing tests for #16607, of course wanted to make sure formulas work in fat/thin marker edge cases.
