### ISSUE TITLE
contourf with custom colormap

### ISSUE THREAD

**Issue by Skillmon** [matplotlib/matplotlib#16629]
### Bug report

Using a custom colormap created with `LinearSegmentedColormap.from_list`, `contourf` doesn't seem to use the correct colours for every value.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap


def color_grid(xx, classes):
    x = xx.ravel()
    Z = np.zeros(x.shape)
    dx = (x.max() - x.min())/classes
    for i in range(classes):
        Z[(i * dx <= x) & ((i + 1) * dx >= x)] = i
    return Z.reshape(xx.shape)


colors = ['b',
          'r',
          'm',
          'c',
          'g',
          'xkcd:orange',
          'xkcd:peach',
          'xkcd:bright pink',
          'xkcd:crimson']


xx, yy = np.meshgrid(np.arange(0, 10, 0.02), np.arange(0, 10, 0.02))
fig, sub = plt.subplots(len(colors)-1, 1)

for i, ax in enumerate(sub.flatten()):
    cm = LinearSegmentedColormap.from_list('foo', colors[0:i+2], i+2)
    Z = color_grid(xx, i+2)
    ax.contourf(xx, yy, Z, cmap=cm)
plt.show()
```

**Actual outcome**

![mwe](https://user-images.githubusercontent.com/8701017/75685610-1d54bb80-5c9b-11ea-9693-7d383164f117.png)

**Expected outcome**

I expected the colours to be correctly picked, meaning an increasing number of different colours in each subplot from top to bottom with each bar in a row roughly the same size (since that's what `Z` should look like).

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): PGF with PDF output, GTK3Agg
  * Python version: 3.8.1
  * Other libraries: numpy

Installed from Arch Linux repositories.

**Comment by Skillmon** [comment]
Oh, and even with `levels=i+2` the colours aren't set reliably.

**Comment by ImportanceOfBeingErnest** [comment]
There is a beating of two different discretisations, the manual one and the one from contour, right?

So if you create an image plot, i.e. replace `ax.contourf(xx, yy, Z, cmap=cm)` by `ax.imshow(Z, aspect="auto", cmap=cm)` it will show the expected colors

![image](https://user-images.githubusercontent.com/23121882/75762178-88090400-5d3a-11ea-8b93-d17dceb90877.png)

If using a contour plot, the contours will only be at the discretization levels if exactly those levels are chosen when calling it (else it wouldn't know about that explicit desire). 

    ax.contourf(xx, yy, Z, levels=np.linspace(0,Z.max(),i+2+1), cmap=cm)

![image](https://user-images.githubusercontent.com/23121882/75762572-31e89080-5d3b-11ea-9db0-5ff8d4c6b657.png)

Closing this, as there is no bug apparent here, but feel free to discuss further if I'm misunderstanding.

**Comment by Skillmon** [comment]
Well, I only used that data to simplify the MWE, in my actual use case I'm trying to visualise the results of an SVM. And I beg you pardon but if I have data with $n$ distinct $Z$ values and say there will be $n$ levels, the results of `contourf` should show $n$ differently coloured areas.

**Comment by ImportanceOfBeingErnest** [comment]
The colored areas are *in between* the levels. So to get n colors one needs n+1 levels. But if an integer, the `levels` argument will only determine an approximate number, provided by the output of a `MaxNLocator`. See issue https://github.com/matplotlib/matplotlib/issues/12729 and PR https://github.com/matplotlib/matplotlib/pull/16534 for the corresponding docstring fix.

**Comment by Skillmon** [comment]
Ok, specifying as a list does work, still I find the behaviour with `levels=<int>` weird when $Z$ has exactly $n$ distinct levels.

**Comment by timhoffm** [comment]
Just as a remark, a similar plot can be created in a single axes using a horizontal bar chart:
See https://matplotlib.org/gallery/lines_bars_and_markers/horizontal_barchart_distribution.html

**Comment by ImportanceOfBeingErnest** [comment]
The reason for this is that you rarely want some odd levels like 

![image](https://user-images.githubusercontent.com/23121882/75769059-c48e2d00-5d45-11ea-8b39-e2844649d634.png)

but rather some nice levels like

![image](https://user-images.githubusercontent.com/23121882/75769124-e25b9200-5d45-11ea-9007-429967f65686.png)

**Comment by Skillmon** [comment]
@timhoffm this is just an oversimplification for the sake of an MWE, I need `contourf` as it is used to show the class borders of an SVM.

**Comment by Skillmon** [comment]
@ImportanceOfBeingErnest Thank you very much for your patience with me and the explanations where I misunderstood the documentation. Everything seems clear to me now :)
