### ISSUE TITLE
Azure pipelines are broken on v3.2.x

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#16624]
As noted in #16612, Azure doesn't seem to post on non-`master` PRs.

If you go to Azure, and check the Runs (not Recent for some reason), then you can find the `v3.2.x` builds, and the latest one fails
https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=8691&view=results

In fact, it's been failing for a _long_ time.

**Comment by QuLogic** [comment]
Build log says we're building with FreeType 2.10.1, which explains the small image failures.

**Comment by QuLogic** [comment]
The linked PR fixed macOS, but not Windows: https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=9280&view=logs&j=7fb64067-7f42-5414-94b1-b7d4c3501c77&t=350b785d-724e-5d38-bb09-cca4c8ab57f2&l=410

**Comment by QuLogic** [comment]
Sigh, still not fixed https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=9283&view=results

I'll see if I can set this up on my fork to iterate quicker.

**Comment by QuLogic** [comment]
Setting up a fork is a bit of a pain, but I realized I can just push it here.

**Comment by tacaswell** [comment]
Closed by #16640
