### ISSUE TITLE
"Fillable" markers should be equal-area or equal-width for a given `markersize`

### ISSUE THREAD

**Issue by brunobeltran** [matplotlib/matplotlib#16623]
### Bug report

Currently, "markersize" means something quite heterogeneous for each different marker (see below). We could easily make it mean the same thing by scaling the "base" size of each marker's path so that it has unit area. This would have the upside of making plots with a constant `markersize` across different markers look perceptually uniform. And would fix a few ancient issues, like issue #1099.

An alternative would be to have markers be unit "width" (see below), which would fix all but the pentagon markers to at least be slightly more uniform. We could then use the actual areas of the unit marker sizes as a simple scaling factor in `Axes.scatter` to fix #1099. 

**Code for reproduction**

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
for marker in mpl.markers.MarkerStyle.markers:
    fig, ax = plt.subplots()
    plt.xlim([-0.04, 0.04])
    plt.ylim([-0.04, 0.04])
    lines = ax.scatter(0, 0, s=100**2, marker=marker, clip_on=False)
    plt.title(str(marker))

    origin_px = ax.transData.transform((0,0))
    top_right_px = origin_px + np.array([50, 50])
    top_right_data = ax.transData.inverted().transform(top_right_px)
    ax.plot([-1, 1], [top_right_data[1], top_right_data[1]])
    ax.plot([-1, 1], [-top_right_data[1], -top_right_data[1]])
    ax.plot([top_right_data[0], top_right_data[0]], [-1, 1])
    ax.plot([-top_right_data[0], -top_right_data[0]], [-1, 1])
```

**Actual outcome**

The `point` is *defined* to be a half-radius `circle`. I guess this is fine.
![marker-test-point](https://user-images.githubusercontent.com/1475390/75636142-119cc280-5bd1-11ea-83bf-c651acdeccbb.png)
The `pixel` of course has a fixed meaning, so need not be updated.
![marker-test-pixel](https://user-images.githubusercontent.com/1475390/75636161-3a24bc80-5bd1-11ea-88a8-075fc9286181.png)

For several markers, `markersize` means "width" or "height" (many omitted for clarity, but happy to edit this to include all here for reference):

![marker-test-caretup](https://user-images.githubusercontent.com/1475390/75636195-866ffc80-5bd1-11ea-995e-79413b50553d.png)

![marker-test-circle](https://user-images.githubusercontent.com/1475390/75636197-8a038380-5bd1-11ea-91c3-726bc4bc5702.png)
![marker-test-hexagon1](https://user-images.githubusercontent.com/1475390/75636237-cafb9800-5bd1-11ea-9a89-96eeeca19d40.png)

![marker-test-plus_filled](https://user-images.githubusercontent.com/1475390/75636250-e1a1ef00-5bd1-11ea-8035-7ddcb819b4c8.png)
![marker-test-square](https://user-images.githubusercontent.com/1475390/75636252-e5357600-5bd1-11ea-97bb-bf63effd21d6.png)

![marker-test-tickright](https://user-images.githubusercontent.com/1475390/75636269-ff6f5400-5bd1-11ea-8a58-07c7f1f978ef.png)

![marker-test-x_filled](https://user-images.githubusercontent.com/1475390/75636296-30e81f80-5bd2-11ea-890c-176c75347e7e.png)

For some markers, `markersize` means "width of square used to create me", which seems pretty unexpected after all the above examples otherwise:
![marker-test-diamond](https://user-images.githubusercontent.com/1475390/75636212-a8697f00-5bd1-11ea-9c91-f29ef7ec4c98.png)
![marker-test-thin_diamond](https://user-images.githubusercontent.com/1475390/75636259-f1b9ce80-5bd1-11ea-80d7-89b82133c8bc.png)

And for *only some* polygons (notice that there are many full-width triangles in the first list above), `markersize` means "radius of the circumscribing circle", which means it neither corresponds to the width/height NOR the area:
![marker-test-octagon](https://user-images.githubusercontent.com/1475390/75636243-d64ec380-5bd1-11ea-9096-1e061d7c2954.png)
![marker-test-pentagon](https://user-images.githubusercontent.com/1475390/75636244-d8188700-5bd1-11ea-9189-a082d13ddff6.png)
![marker-test-star](https://user-images.githubusercontent.com/1475390/75636256-ec5c8400-5bd1-11ea-8e95-468d3be72653.png)
![marker-test-tri_down](https://user-images.githubusercontent.com/1475390/75636285-2168d680-5bd2-11ea-80b9-e41105ff1e17.png)
![marker-test-tri_left](https://user-images.githubusercontent.com/1475390/75636286-23329a00-5bd2-11ea-8547-7e9119e66611.png)
![marker-test-tri_right](https://user-images.githubusercontent.com/1475390/75636290-24fc5d80-5bd2-11ea-848a-b95234e0ee3a.png)
![marker-test-tri_up](https://user-images.githubusercontent.com/1475390/75636291-262d8a80-5bd2-11ea-989c-736a03fce6f1.png)

**Expected outcome**

Two proposals for fixing this: 

1) make all `markersize=1` markers have unit area. This is easy to do by scaling their paths appropriately. The non-fillable markers could be left as-is or scaled to the size at which their "fillable" counterpart would have unit area. (e.g. '1' would be scaled so that the equilateral triangle it draws the skeleton of would have unit area, 'x' and '+' would be scaled so that the squares they draw the skeleton of would have unit area).

2) make all `markersize=1` markers have unit width/height (whichever is larger). This seems more in line with the current "zeitgeist" of marker design. It would only require changing a couple of markers:
    a) 'd' (thin diamond) and 'D' (diamond) would be scaled to be of unit height instead of "D" being made from a rotated unit square (so a factor of 1/sqrt(2)).
    b) '8' (octagon) and 'p'/'*' (pentagon/star) would be scaled up slightly to have unit width. Especially for octagon (see above) this would match MUCH better the current conventions for e.g. 'x'/'X'. 
    c) "triangle skeletons" (i.e. `'tri_left'` and friends) should be scaled to be the same width as the `'caret'` family, for consistency.
Every other marker could remain the same and this convention be matched.

I am happy to make either of these into a PR (code is written for option 2 already, tbh). However, if we go with option (2), I think we should definitely fix the `s` argument to scatter to actually be a measurement of the area of the marker in px^2, since each marker in that case will still have a different base area measurement (also code already written, tbh).

**Matplotlib version**

  * Operating system: Debian 9
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

**Comment by timhoffm** [comment]
See also #15703.

**Comment by brunobeltran** [comment]
Closing this, as I basically moved the discussion to #15703. Will happily reopen if e.g. you think that a PR of a "geometrically uniform" marker size (as opposed to a "perceptually uniform" marker size) might be accepted, in which case it might make more sense to refer to this issue directly.
