### ISSUE TITLE
Minor typo in API document of patches.ConnectionPatch

### ISSUE THREAD

**Issue by smartlixx** [matplotlib/matplotlib#16645]
### Bug report

**Bug summary**

https://matplotlib.org/3.1.3/api/_as_gen/matplotlib.patches.ConnectionPatch.html?highlight=connectionpatch

Table of coordsA and coordsB, at the line 'axes fraction', '0,1 is lower left of axes and 1,1 is upper right' should be '0,0 is lower left'.

**Comment by timhoffm** [comment]
@smartlixx Thanks for the report!
