### ISSUE TITLE
Can't access graph data

### ISSUE THREAD

**Issue by mattou78400** [matplotlib/matplotlib#16642]
```python
plt.subplot(311)
plot = sns.kdeplot(data = df['rel_str'], data2 = df['price'], color='b', shade=True, cbar=1, bw=0.001)
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [red, red])
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [green, green])


plt.subplot(312)
plot2 = sns.kdeplot(data = df['rel_str'], data2 = df['price'], color='r', shade=True, cbar=1, bw=0.01)
plot2.set_title(date)
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [red, red])
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [green, green])

plt.subplot(313)
plot3 = sns.kdeplot(data = df['rel_str'], data2 = df['price'], color='r', shade=True, cbar=1, bw=0.05)
plot3.set_title(date)
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [red, red])
plt.plot([0, max(df['rel_str'].loc[df['actual'] == 1])], [green, green])

plt.show()
plt.clf()
```

**Actual outcome**
3 plots with different bandwidth for each kde plot
https://imgur.com/uqetxaA

**Expected outcome**

I'm trying to access the data from the "blue plot" which is bandwidth = 0.001
As sns.kdeplot calculates everything by itself, I don't pass it the explicit graph data.
I need the (x, y, z) data of each blue dot.
But it seems that using seaborn for the "plot formulas" complicate things. I tried the solution explained here:
https://stackoverflow.com/questions/20130768/retrieve-xy-data-from-matplotlib-figure

But no luck.

Thanks for your help!

**Matplotlib version**

  * Operating system: windows
  * Matplotlib version: latest
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: seaborn

Pip install

**Comment by ImportanceOfBeingErnest** [comment]
Seaborn functions return the axes object they plot to. That's a design choice that can be discussed with seaborn developpers.  
There doesn't seem to be a problem with matplotlib here, so closing.
