### ISSUE TITLE
GSOC Banner/FrontPage

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#16663]
Add either the usual banner or something to the sidebar announcing that mpl is seeking a gsoc student this year. It should link to https://github.com/matplotlib/matplotlib/projects/12
![image](https://user-images.githubusercontent.com/1300499/75919844-46588600-5e2c-11ea-8dd1-6aad3b257451.png)

**Comment by timhoffm** [comment]
The upper banner could be removed/repurposed if we apply the last step of #16253 to the version info (`version.txt`).

**Comment by story645** [comment]
I'm fine with it?

**Comment by timhoffm** [comment]
I just need to find out who is responsible for `version.txt` as that is not part of the repo.

**Comment by story645** [comment]
I'm a bit confused about what you mean by versions.txt

**Comment by timhoffm** [comment]
Sorry, I meant `versions.html`. The content of the box is embedded from https://matplotlib.org/versions.html so that it can show up-to-date information even for older versions of the docs.

**Comment by story645** [comment]
applications are due the 31st so at this point I don't care how the banner gets posted

**Comment by timhoffm** [comment]
Then go with the usual banner. I suppose that's the fastest way forward. @tacaswell should know how to add it.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/16826  @dorafc and I will work on moving them (GSOC and JHEP) to the side bar this week.

**Comment by story645** [comment]
Since GSOC closes out tuesday, I'm going to close this issue as a "works for me"
