### ISSUE TITLE
Allow dates.DateConverter to convert string dates

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotlib#16666]
### Current behavior

At present, it is not possible to use strings for date locations when the x-axis has datetime values. Take the following simple example:

**Code for reproduction**

```python
x = [datetime(2000, 1, 1), datetime(2000, 2, 1), datetime(2000, 3, 1)]
y = [1, 2, 1]
fig, ax = plt.subplots(figsize=(2, 2))
ax.plot(x, y)
ax.xaxis.set_major_locator(dates.MonthLocator())
```
![a](https://user-images.githubusercontent.com/7226751/75928493-832c7900-5e3c-11ea-8f5f-1d1acfbdfc35.png)

### Error
Attempting to add some text using a string containing a date fails

```python
ax.text(x='2000-01-25', y=1.5, s='here')
ConversionError: Failed to convert value(s) to axis units: '2000-01-25'
```

To correctly add text, you must use a datetime or `dates.datestr2num`

```python
x1 = datetime(2000, 1, 25)
ax.text(x=x1, y=1.5, s='here')
```

### Quick fix

The body of the dates.DateConverter.convert method is just a single line - `return date2num(value)`

A simple check for a string like this would work.

```
if isinstance(value, str):
    return dates.datestr2num(value)
else:
    return dates.date2num(value)    
```

**Comment by jklymak** [comment]
You can also do `x=np.datetime64('2000-01-25')`.  But I guess we could add this so long as no one had the expectation that strings would ever trigger the use of a date axis.  

The only hesitation I have about this is that malformed datestr complaints will come to us, and matplotlib doesn't want to be responsible for a bunch of date-parsing logic.  Yeah, we provide `datestr2num`, but it clearly points the user to `dateutil`.

**Comment by tacaswell** [comment]
I'm 50/50 on this.

In this case there is no ambiguity that the date convertor is already in use.  However, if this was merged

```python
x = [datetime(2000, 1, 1), datetime(2000, 2, 1), datetime(2000, 3, 1)]
y = [1, 2, 1]
fig, [ax1, ax2] = plt.subplots(2, figsize=(2, 2))

# This would work
ax1.plot(x, y)
ax1.text(x='2000-01-25', y=1.5, s='here')

# This would not
ax2.text(x='2000-01-25', y=1.5, s='here')
ax2.plot(x, y)
```

which seems like it would be more confusing on net.

**Comment by tdpetrou** [comment]
Another idea would be to provide documentation on how to register a converter (I couldn't find any) by subclassing DateConverter.

Or add in more built-in classes that subclass DateConverter such as pandas.plotting._matplotlib.converter.DatetimeConverter

**Comment by jklymak** [comment]
I think the documentation is here, right?  Its pretty advanced, so not sure it merits more prominent placement, but if you wrote a subclass and wanted to put it on the examples pages, that might be good.  

https://matplotlib.org/3.1.3/api/units_api.html#module-matplotlib.units

**Comment by jklymak** [comment]
I think the consensus is to not do this and just expect datetime-like objects to work.
