### ISSUE TITLE
Support .otf fonts

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#1668]
Matplotlib's freetype wrapper only supports .ttf fonts.  As more and more fonts are only available in .otf format, we should update the wrapper to support them.

**Comment by anntzer** [comment]
Something like
```
from pylab import *
fp = matplotlib.font_manager.FontProperties(fname="/usr/share/fonts/OTF/LinLibertine_R.otf")
plt.text(.5, .5, "foo", fontproperties=fp)
show()
```
actually works perfectly fine since at least mpl1.4 (can't compile 1.3, apparently my numpy headers are too recent...).

There are many additional features with otf (font variations, complex layout, etc.) but I think they should each get their own issue depending on the need.
