### ISSUE TITLE
Toolbar tools don't show when selected - wxpython and macOS

### ISSUE THREAD

**Issue by jbhopkins** [matplotlib/matplotlib#16701]
### Bug report

**Bug summary**

When using the WxAgg backend on MacOS, if you select a tool in the toolbar you essentially can't tell that the tool is selected. There is only a very small change in the appearance. On other platforms (linux, windows) it is very obvious that the tool is selected.

**Code for reproduction**

```python
import wx
import matplotlib as mpl
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg

class PlotFrame(wx.Frame):
    def __init__(self, parent, title, *args, **kwargs):
        wx.Frame.__init__(self, parent, title=title, *args, **kwargs)

        self.fig = mpl.figure.Figure((5,4))
        self.subplot1 = self.fig.add_subplot(111)
        self.canvas = FigureCanvasWxAgg(self, wx.ID_ANY, self.fig)

        self.toolbar = NavigationToolbar2WxAgg(self.canvas)
        self.toolbar.Realize()

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.canvas, 1, wx.LEFT | wx.TOP | wx.GROW)
        sizer.Add(self.toolbar, 0, wx.GROW)

        self.SetSizer(sizer)
        self.Layout()
        self.Fit()
        self.CenterOnScreen()
        self.Show(True)

if __name__ == '__main__':
    app = wx.App(False)
    frame = PlotFrame(None, 'My Plot Frame')
    app.MainLoop()
```

**Actual outcome**

No tools selected:
![Screen Shot 2020-03-06 at 9 43 04 AM](https://user-images.githubusercontent.com/23534688/76103103-baaf3880-5f96-11ea-903d-179d0446d906.png)

Magnifying tool selected:
![Screen Shot 2020-03-06 at 9 43 15 AM](https://user-images.githubusercontent.com/23534688/76103130-c7cc2780-5f96-11ea-832b-c322728728d6.png)

**Expected outcome**
The expected outcome is that you should be able to easily tell which tool is selected. Depending on the screen used sometimes it is impossible, or sometimes just very hard, to tell if the tool is selected.

**Matplotlib version**
  * Operating system: MacOS 10.14.6
  * Matplotlib version: 3.1.3
  * Matplotlib backend: WxAgg
  * Python version: 3.7.5
  * Other libraries: wxpython 4.0.4

Everything installed through default conda channel.

**Comment by tacaswell** [comment]
Does it work in the same env if you use `pyplot` (and our embedding in wx) rather than doing it your self?

**Comment by jbhopkins** [comment]
I'm assuming you mean something like this:

```python
import matplotlib as mpl

mpl.use('WxAgg')

import matplotlib.pyplot as plt

plt.plot(range(10), range(10)[::-1])
plt.show()
```

That has the same result, in that you can't tell if a button is activated.

I should note, for clarity, that the toolbar button functions still work, it's just the visual letting you know if a button is selected that isn't right.

**Comment by tacaswell** [comment]
Yes, exactly that, thank you for checking.  I don't personally know wx very well and wanted to make sure that it wasn't something about how you were setting the toolbar up (admittedly unlikely).

I am now suspecting that it is a Wx / apple interaction issue.  If you make buttons outside of Matplotlib do they have the same issue?

**Comment by jbhopkins** [comment]
I've never used a toolbar in wx outside of matplotlib. So I just pulled up the toolbar demo in the wxpython demo. That one you can easily see the on/off toggle.

Button off:
![off](https://user-images.githubusercontent.com/23534688/76117710-ebe93200-5fb1-11ea-9582-43eec8552291.png)


Button on:
![on](https://user-images.githubusercontent.com/23534688/76117735-f6a3c700-5fb1-11ea-8d54-740da7b0ea87.png)

**Comment by tacaswell** [comment]
Is that "T" text or an image?  A hunch is that the images are square, the shadow is a rounded square rendered under it so it is getting hidden?

If I flip between the two images you posted of the Figure I _think_ I can see a very subtle difference, maybe there is a setting in Wx we should be changing?

**Comment by jbhopkins** [comment]
The "T" is an image.

I agree that there's a difference between the two images I originally posted. I've noticed that on the right monitor (a very good, high contrast one) you can tell the difference. On a bad monitor they can look identical. So there may be a setting somewhere. I tried changing the colors, but the toolbar didn't seem to respond to the usual wx.SetForegroundColour or wx.SetBackgroundColour so I'm not sure where to go from there.

**Comment by jbhopkins** [comment]
So a little more investigation of the wx demo. There are two ways to create a toolbar in wx. You can use the wx.ToolBar class or you can use the wx.Frame.CreateToolBar. The demo by default uses the second. matplotlib uses the first. If I set the flag in the demo so it creates the coolbar with wx.ToolBar I get an identical result to what we see in matplotlib (i.e. almost no visible change in the button when toggled).

So this appears to be a difference between the wx.Frame.CreateToolBar and the wx.ToolBar. And that about taps out the limit of my wx knowledge.  Maybe @RobinD42 can help?

**Comment by RobinD42** [comment]
IIRC the native toolbar on OSX is actually part of the widget used for the frame implementation. So when `CreateToolBar` is used it actually just turns on the frame's own toolbar features. When `wx.ToolBar` and `SetToolBar` are used then it creates a separate widget for the toolbar and positions it at the top of the frame's client area. So the only way to look truly native is to use the `CreateToolBar` approach.

As for the look of the togglable tool items, there was some problem with getting the native toolbar to support toggle items the same way as on the other platforms. So a workaround of simply creating a new bitmap from the current one, with a shaded background, was used to indicate the the tool was toggled. From the images above it appears that the shadow color is not different enough from that version of the toolbar to be easily visible.

There's some more info here: https://trac.wxwidgets.org/ticket/16645

**Comment by tacaswell** [comment]
Is there anything we can do the Matplotlib side of things?

**Comment by jbhopkins** [comment]
@RobinD42 seems to be suggesting that the problem is the shading the ToolBar widget is using to autogenerate the toggled bitmaps. It's not a fix, but a workaround would be to generate the toggled bitmaps manually and passing those to the toolbar, rather than letting wx do it automatically. If we did that we'd probably want to make it platform specific, since the toggle looks fine as is on linux and windows.

I'm hoping there might be a more elegant solution, such as modifying how the widget is automatically generating the bitmaps, but I don't know if there's a way to do that.

**Comment by RobinD42** [comment]
There isn't. That color changing code has no contributing APIs and the color used is basically hard-coded. 😦 

On the other hand, since Matplotlib is putting the buttons at the bottom of the frame instead of the top, then maybe a `wx.ToolBar` isn't the best choice anyway. There is a generic toolbar-like widget in `wx.lib.agw.buttonpanel` that would probably be a good fit. You have full control over the panel's colors and gradient, and can handle bitmaps like a toolbar's tools as well as labels and other controls.

**Comment by anntzer** [comment]
We could put it at the top instead, I'd guess this is basically an accident of history.  (e.g. the qt backend puts it at the top)

**Comment by jbhopkins** [comment]
I think the main issue with switching to the `wx.CreateToolBar` (which would be the toolbar at the top), is that it will break backwards compatibility. That toolbar doesn't need to be added to a sizer, and so can't be placed arbitrarily in a layout. While it doesn't seem to throw an error when added to a sizer, it doesn't obey the usual layout rules. So code like the example in my top level post won't work as it previously did. I don't know how important this is for matplotlib.

While I think that using the `wx.CreateToolBar` would work well for the pyplot window, I'd prefer to either generate custom bitmaps for the disabled version and use `wx.ToolBar` or switch to using the `wx.lib.agw.buttonpanel` as toolbar, if that works similarly.

**Comment by jbhopkins** [comment]
So I've got some time now and I'm starting to work on this. I'm noticing in the code that there seems to be two possible toolbars, one associated with an rcParams['toolbar'] value of 'toolbar2' and one the other with 'toolmanager'. My impression is that the 'toolmanager' version is depreciated. Do I need to worry about it, or can I just modify the Toolbar2 code?

**Comment by QuLogic** [comment]
Unfortunately, the status is that 'toolmanager' is newer, but in limbo, and has been for some time. I would focus on 'toolbar2' for now, but it may be necessary to work on the other once this is all figured out.

**Comment by dstansby** [comment]
On the currently `main` branch of Matplotlib this seems to work for me. Here is un-toggled: ![Screenshot 2023-01-02 at 16 41 10](https://user-images.githubusercontent.com/6197628/210258816-c9ddb767-0e14-4bbb-ae1d-0a8ba5b5a440.png) and here is toggled: ![Screenshot 2023-01-02 at 16 41 23](https://user-images.githubusercontent.com/6197628/210258836-3505b78d-ee05-4582-9908-6a50491baa16.png)

As such I'll close this - if it's still an issue for anyone, please leave a comment and I can re-open!
