### ISSUE TITLE
Deprecation warnings from stylelib

### ISSUE THREAD

**Issue by astromancer** [matplotlib/matplotlib#16700]
### Bug report

**Bug summary**

I'm getting a string of deprecation warnings whenever I import pyplot.  The warnings are coming from a file named `/matplotlib/mpl-data/stylelib/_classic_test.mplstyle` as you can see below.  I think this file gets created during the build since it has no counterpart in the repo [here](https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib/mpl-data/stylelib).  Also, the url in the warnings points to a non-existent page.

**Code for reproduction**

`from matplotlib import pyplot`

**Actual outcome**

```
Bad key "savefig.frameon" on line 421 in
/usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.2.0rc2+1631.g44b4e8e15/matplotlibrc.template
or from the matplotlib source distribution

Bad key "verbose.level" on line 472 in
/usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.2.0rc2+1631.g44b4e8e15/matplotlibrc.template
or from the matplotlib source distribution

Bad key "verbose.fileo" on line 473 in
/usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.2.0rc2+1631.g44b4e8e15/matplotlibrc.template
or from the matplotlib source distribution
In /usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /usr/local/lib/python3.6/dist-packages/matplotlib-3.2.0rc2+1631.g44b4e8e15-py3.6-linux-x86_64.egg/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
```

**Matplotlib version**

  * Operating system: ubuntu 18.04
  * Matplotlib version: 3.2.0rc2+1631
  * Python version: 3.6.9

Built from source with pip via `pip install .`

**Comment by hakostra** [comment]
I have the same problem with 3.2.1 installed from pip on python 3.6.9, slightly different output:

```
import matplotlib.pyplot as plt                                                                                                                       
In /home/hakostra/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/hakostra/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/hakostra/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
```
very annoying.

**Comment by hakostra** [comment]
Update:
```
pip3 uninstall matplotlib
rm -rf ~/.local/lib/python3.6/site-packages/matplotlib*
pip3 install matplotlib
```
solved the problem.

**Comment by tacaswell** [comment]
What is in your matplolibrc?

**Comment by hakostra** [comment]
I don't have any.

**Comment by tacaswell** [comment]
I don't have any guess off the top of my head what is going on.  @hakostra How are you installing Matplotlib and on what platform?

Can you intentionally drive it back to a broken state?

That style sheet is used in the tests (to avoid regenerating all of the images).

**Comment by hakostra** [comment]
I am using most recent linux mint (based ubuntu 18.04). I install Matplotlib via pip3. When I updated from a 3.0.x to 3.2, with pip3, i got the above mentioned errors.

I noticed that the file ~/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle was not included in the 3.2 package, it was probably laying there from some older package (3.0 or older). I therefore un-installed matplotlib (pip3 uninstall matplotlib), and the file was still there, so i completely wiped the installation folder (rm -r), and re-installed matplotlib over again (pip3 install matplotlib). The file are now gone and matplotlib works.

~/.local is excluded from my daily backup so I cannot reconstruct what I deleted.

**Comment by tacaswell** [comment]
are you implicitly using `--user`?

**Comment by hakostra** [comment]
Yes, this is with my pip the default if i run pip as a non-root user.

```
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by tacaswell** [comment]
ok so the bug is that uninstall is not clearing out all of the style files.

That is an exteremely old version of pip, if you do `pip install -U pip` and then try again do you have the same issues?

**Comment by mauvilsa** [comment]
I started getting these warning so I ended up reading this issue. Since some time ago I have noticed that pip somehow keeps old packages. So following the solution from @hakostra I first uninstalled matplotlib, but ran the uninstall multiple times until I was sure that all versions were uninstalled, since lately I do that. Specifically the following is what happened:
```
$ pip3 uninstall -y matplotlib                                  
Uninstalling matplotlib-3.2.1:                                                                                                      
  Successfully uninstalled matplotlib-3.2.1                                                                                         
$ pip3 uninstall -y matplotlib
Uninstalling matplotlib-3.0.3:
  Successfully uninstalled matplotlib-3.0.3
$ pip3 uninstall -y matplotlib
Cannot uninstall requirement matplotlib, not installed
```
Then I checked and there were no `~/.local/lib/python3.6/site-packages/matplotlib*` files. I installed matplotlib again the warnings no longer appeared. So I guess this is some weird pip issue.

**Comment by tacaswell** [comment]
I'm going to close this as resolved by fully uninstalling and re-installing.  I don't think there is anything we can do on the Matplotlib side to address this.

**Comment by astromancer** [comment]
In my case I had to remove the `build` directory in the main repo to get the warnings to disappear. 👌

**Comment by Multi-Kocky** [comment]
> In my case I had to remove the `build` directory in the main repo to get the warnings to disappear. 👌

I got the same problem, could you tell me where can I remove 'build' directory? Thanks

**Comment by tacaswell** [comment]
@Multi-Kocky If you installed from source the build process creates a build directory in the top level of your checkout, remove it like you would any other folder (or use `git clean -xfd`).  If you installed Matplotlib through pip / conda / system package manager / ... you will need to use that tool to uninstall it and re install it.

**Comment by RuihanGao** [comment]
> I started getting these warning so I ended up reading this issue. Since some time ago I have noticed that pip somehow keeps old packages. So following the solution from @hakostra I first uninstalled matplotlib, but ran the uninstall multiple times until I was sure that all versions were uninstalled, since lately I do that. Specifically the following is what happened:
> 
> ```
> $ pip3 uninstall -y matplotlib                                  
> Uninstalling matplotlib-3.2.1:                                                                                                      
>   Successfully uninstalled matplotlib-3.2.1                                                                                         
> $ pip3 uninstall -y matplotlib
> Uninstalling matplotlib-3.0.3:
>   Successfully uninstalled matplotlib-3.0.3
> $ pip3 uninstall -y matplotlib
> Cannot uninstall requirement matplotlib, not installed
> ```
> 
> Then I checked and there were no `~/.local/lib/python3.6/site-packages/matplotlib*` files. I installed matplotlib again the warnings no longer appeared. So I guess this is some weird pip issue.

Thanks for pointing it out! 
I get
```
matplotlib                3.1.2                    pypi_0    pypi
matplotlib-base           3.3.2            py38h91b0d89_0    conda-forge
```
after running `conda list | grep matplotlib` and
```
matplotlib
matplotlib-3.1.2.dist-info
matplotlib-3.1.2-py3.8-nspkg.pth
matplotlib-3.3.2.dist-info
matplotlib-3.3.2-py3.8-nspkg.pth
```
in `~/anaconda3/envs/myenv/lib/python3.8/site-packages`
Therefore, I run `pip3 uninstall matplotlib` twice to remove matplotlib 3.1.2 and 3.3.2 and run another `conda remove --force matplotlib`.
Finally, I install a new version by `pip3 install matplotlib` and the warnings disappear.

**Comment by rhondene** [comment]
> Update:
> 
> ```
> pip3 uninstall matplotlib
> rm -rf ~/.local/lib/python3.6/site-packages/matplotlib*
> pip3 install matplotlib
> ```
> 
> solved the problem.

>The above solved the problem on Windows 10, Python3.7, Matplotlib3.4
