### ISSUE TITLE
Float figure DPI

### ISSUE THREAD

**Issue by 1313e** [matplotlib/matplotlib#16718]
Small question: Isn't the DPI of a figure supposed to be an integer?
I am asking, as the value for `'figure.dpi'` as stored in `mpl.rcParams`, is a float and not an integer, which is caused by the following line:

https://github.com/matplotlib/matplotlib/blob/07a108fffb6b0cb1a836093c96adf08be50e82a9/lib/matplotlib/rcsetup.py#L1388

However, the docstring of `plt.figure` states clearly that it is an integer:

https://github.com/matplotlib/matplotlib/blob/07a108fffb6b0cb1a836093c96adf08be50e82a9/lib/matplotlib/pyplot.py#L473-L474

So, which one of them is correct?

**Comment by QuLogic** [comment]
Float is correct:
```
>>> import matplotlib.pyplot as plt
>>> plt.figure(figsize=(10, 10), dpi=3.5)
<Figure size 35x35 with 0 Axes>
```
