### ISSUE TITLE
LICENSE: can you clarify somewhere for what part the license are from?

### ISSUE THREAD

**Issue by nicola-lunghi** [matplotlib/matplotlib#16729]
Hi,
can you add in the documentation an explanation of the license for the software used and for example what option / module need what license?
the LICENSE folder is not very clear for me...

Thanks
Nick

**Comment by anntzer** [comment]
attn @tacaswell I guess a master license summary file pointing out what part of the lib goes with what license would be useful.

**Comment by nicola-lunghi** [comment]
I am developing a recipe for linux yocto.
In yocto every package should have specified the license -> and where the license is as the build system is checking for changes and can filter for specific licenses.
The setup.py specify PSF as license but then there's a license folder with a bunch of license files.

also is not easy to exclude a particular part for licensing reason?

**Comment by tacaswell** [comment]
It is not easy to exclude a particular part based on license.  All of the licenses are BSD compatible.  A majority of the license are for assets (like fonts and color maps) that we have included in the source.  

Which of the license files in unclear about what it applies to?

In addition we also bundle the source for qhull (https://github.com/matplotlib/matplotlib/blob/master/extern/libqhull/COPYING.txt), AGG (https://github.com/matplotlib/matplotlib/blob/master/extern/agg24-svn/src/copying) and ttconv (https://github.com/matplotlib/matplotlib/blob/b292a59d37de2f767e3071261a9df2c296d60096/extern/ttconv/pprdrv.h#L11-L21) but you can link to external versions of those at build time if you wish.

**Comment by anntzer** [comment]
Actually neither agg (for sure) nor ttconv (I think?) can be switched to upstream versions as we have patched both of them.  qhull can (on the not yet released mpl3.3).

**Comment by tacaswell** [comment]
have we patched Agg in API incompatible ways?  I thought we had just fixed bugs (and made it ABI incompatible).

**Comment by anntzer** [comment]
dunno :/

**Comment by tacaswell** [comment]
I suspect @QuLogic knows the answer to this due to trying to get our patches merged upstream a year or two ago....

**Comment by QuLogic** [comment]
Agg is much further ahead than upstream, since it hasn't really seen any development. It seems like there might be something happening on SF, but I have not looked at it.

Debian maintains an comprehensive list of [which files are under which license](https://salsa.debian.org/python-team/modules/matplotlib/-/blob/master/debian/copyright).
