### ISSUE TITLE
xlim is not auto scaled when using twinx

### ISSUE THREAD

**Issue by 01baftb** [matplotlib/matplotlib#16723]
I am reporting as possible bug.

When plotting a secondary y axis on the right, the xlim is not being properly auto scaled. As possible work around was proposed here, https://stackoverflow.com/a/27344398/4988010, however, it seems this was fixed here, https://github.com/matplotlib/matplotlib/commit/26ed35b78cd7542f6841835925be53419661e36e. However, I am not seeing the issue being resolved on matplotlib v3.2.0. 

```python
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
decay = lambda C, K, x: C *(1-np.exp(-1*K*x))
x = np.linspace(0,10,10)

# Create a secondary y axis on the right
twin_ax = ax.twinx()

for n in range(5):
    C = n**2 + 5
    K = 0.75
    # Plot the exponential decay on left y axis 
    ax.plot(x,decay(C,K,x), marker='o', linestyle='--', label=C)
    # Plot the limit of decay on right y axis 
    twin_ax.axhline(y=C, color='gray') 
    
ax.legend()
ax.set_xlabel('X')
ax.set_ylabel('Measured values')
twin_ax.set_ylabel('Theoritical limit')

# Align the both left and right y axis 
twin_ax.set_ylim(ax.get_ylim())

##################
# Issues or bugs
# Need to fix the X limits or else 
# the graph doens't display properly
##################

print('xlim before fix: {}'.format(ax.get_xlim()))
ax.relim()
print('xlim after relim(): {}'.format(ax.get_xlim()))
# A hack to fix the issue # https://stackoverflow.com/a/27344398/4988010
twin_ax.plot(0, 0, visible=False)
print('xlim after fixing: {}'.format(ax.get_xlim()))

plt.show()
```
![plot with issue](https://imgur.com/nouM1AN.png)
![plot with working hack](https://imgur.com/MqAPF38.png)

**Comment by jklymak** [comment]
This looks like the axes are fighting each other and `axhline` is hard coding the axes limits because folks argued it should have a role in setting the view limits.  

Possible solutions are to plot your lines on the original axes, or use `ax.secondary_axes` instead of `twin_axes`. Is there are reason you are using `twin_axes` here?

**Comment by ImportanceOfBeingErnest** [comment]
It's still a regression, right?

![image](https://user-images.githubusercontent.com/23121882/76366521-81762000-632a-11ea-8363-75fed2299fc5.png)

![image](https://user-images.githubusercontent.com/23121882/76366571-ae2a3780-632a-11ea-91d4-14632bd39a6e.png)

**Comment by jklymak** [comment]
Sure, bisects to 84448caaf89

**Comment by 01baftb** [comment]
> This looks like the axes are fighting each other and `axhline` is hard coding the axes limits because folks argued it should have a role in setting the view limits.
> 
> Possible solutions are to plot your lines on the original axes, or use `ax.secondary_axes` instead of `twin_axes`. Is there are reason you are using `twin_axes` here?

Thanks for pointing out `ax.secondary_axes`. This seems to be a [new feature](https://matplotlib.org/3.1.0/users/whats_new.html#secondary-x-y-axis-support) I just found out about. However, I am still unsure how I can use this to plot a secondary y axis on the right for the specific example I shared. For example, when I try to do the following, I an error, 

`AttributeError: 'SecondaryAxis' object has no attribute 'axhline'`. 

```python
twin_ax = ax.secondary_yaxis('right')
twin_ax.axhline(y=10, color='gray') 
```

With limited use examples/documentation, I am still unsure what is the different between `secondary_yaxis()` and` twinx()`.

**Comment by jklymak** [comment]
Sure, a bt off topic, but secondary axis is not to be drawn on, its just to show an alternate scale. All the plotting happens on the parent axes.

**Comment by oscargus** [comment]
I think this is fixed now.

![16723](https://user-images.githubusercontent.com/8114497/194844437-6ec8fb3f-189c-406e-86de-ab3511f39d70.png)

Should probably add a test though before closing.
