### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by alibenn** [matplotlib/matplotlib#16733]
### Bug report

pip install fails

Syntax error in setup.py

The error occurs when running a test in my CI/CD pipeline. The output is below (slightly edited). 

1  Running with gitlab-runner 12.7.1 (003fe500)
Using Docker executor with image gitlab-registry.cern.ch/ci-tools/ci-worker:cc7 ...
00:03
4 WARNING: Container based cache volumes creation is disabled. Will not create volume for "/cache"
5 Authenticating with credentials from job payload (GitLab Registry)
6 Pulling docker image gitlab-registry.cern.ch/ci-tools/ci-worker:cc7 ...
7 Using docker image sha256:262a48c12b0622aabbb9331ef5f7c46b47bd100ac340ec1b076c0e83246bb573 for gitlab-registry.cern.ch/ci-tools/ci-worker:cc7 ...
10 Initialized empty Git repository in ...
11 Created fresh repository.
12 From https://gitlab.cern.ch/...
13  * [new ref]         refs/pipelines/1479476 -> refs/pipelines/1479476
19  * [new branch]      master                 -> origin/master
20 Checking out 0478b59a as master...
21 Skipping Git submodules setup
22
Authenticating with credentials from job payload (GitLab Registry)
00:24
23 $ pip install numpy==1.10.4
24 Collecting numpy==1.10.4
25   Downloading https://files.pythonhosted.org/packages/4b/06/c7df438b7b89e16161e4cc2183b5d7f36d0e5ceb46aa0adc4df12a8e8268/numpy-1.10.4-cp27-cp27mu-manylinux1_x86_64.whl (15.0MB)
26 Installing collected packages: numpy
27 Successfully installed numpy-1.10.4
28 You are using pip version 8.1.2, however version 20.0.2 is available.
29 You should consider upgrading via the 'pip install --upgrade pip' command.
30 $ pip install boost_histogram
31 Collecting boost_histogram
32   Downloading https://files.pythonhosted.org/packages/7b/06/1f4eecfd93670c8cb636305c9e1f2abb5ee4b55ea72c414f61fad551f7fc/boost_histogram-0.6.2-cp27-cp27mu-manylinux1_x86_64.whl (1.7MB)
33 Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python2.7/site-packages (from boost_histogram)
34 Installing collected packages: boost-histogram
35 Successfully installed boost-histogram-0.6.2
36 You are using pip version 8.1.2, however version 20.0.2 is available.
37 You should consider upgrading via the 'pip install --upgrade pip' command.
38 $ pip install matplotlib
39 Collecting matplotlib
40   Downloading https://files.pythonhosted.org/packages/be/06/81367951cc50695830482eacefdc8289c68770db166a4d4283e7eac22dee/matplotlib-3.2.0.tar.gz (40.5MB)
41     Complete output from command python setup.py egg_info:
42     Traceback (most recent call last):
43       File "<string>", line 1, in <module>
44       File "/tmp/pip-build-BGcCzF/matplotlib/setup.py", line 138
45         raise IOError(f"Failed to download jquery-ui.  Please download "
46                                                                        ^
47     SyntaxError: invalid syntax
48     
49     ----------------------------------------
50 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BGcCzF/matplotlib/
51 You are using pip version 8.1.2, however version 20.0.2 is available.
52 You should consider upgrading via the 'pip install --upgrade pip' command.
53 ERROR: Job failed: exit code 1

**Actual outcome**

pip install failed
```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

pip installing matplotlib.

The same pipeline runs on my desktop so there seems to be something odd with this particular file.

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
>  33 Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python2.7/site-packages (from boost_histogram)

You are using Python 2.

> 36 You are using pip version 8.1.2, however version 20.0.2 is available.

And your `pip` is too old to notice that Matplotlib 3 doesn't support Python 2.

You need to upgrade one or both of these.

**Comment by timhoffm** [comment]
Alternatively, if you are bound to Python 2, you could pin `matplotlib=2.2.5`.

**Comment by alibenn** [comment]
Many thanks and sorry for the noise. I didn't mean to abuse the bug report for support. The error message just looked as if there was a garbled file in the release. 
Fixing the version as @timhoffm suggested solved the problem for me.

**Comment by tacaswell** [comment]
For people who land here in the future please direct any followups to: https://discourse.matplotlib.org/c/community/install/13

No worries @alibenn, we would rather see some false positives than people not report bugs!
