### ISSUE TITLE
Create colorbar based on user defined values

### ISSUE THREAD

**Issue by zhexingli** [matplotlib/matplotlib#16737]
Is there a way in matplotlib to allow users to manually create a continuous colorbar? Here's an example.

I'd like to plot a dataset x and y:
x = [1,2,3,4,5]
y = [1,2,3,4,5]
and I'd like to color code the lines in between the data points according to another list z (not necessarily in sequential order):
z = [4,3,2,1], with higher number being darker color

So essentially a line with user-defined color gradient that consists of multiple data points.

Scatter plot is not what I wanted. I need the lines connecting the data points and not showing the points themselves. In the actual plot, the way I color code the data is to normalize the color value between 0 and 1, loop through the line segments and use ax.plot() to plot out the line segments, and then use the alpha (the transparancy parameter) to set the darkness of the color (in this case 'red') for that segment. Now I'm trying to create a vertical continuous colorbar next to the plot based on my predefined values but couldn't find a way to do this. A lot of online answers seem to use preexisting colormaps in matplotlib, but here I'd like my own colorbar based on the transparancy of each data (ie, the values in the list z). Any ideas how should I do that?

Thanks in advance!

**Comment by timhoffm** [comment]
Does this example help you?

https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html

**Comment by zhexingli** [comment]
> Does this example help you?
> 
> https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html

This might, I'll take a look, thx.

**Comment by zhexingli** [comment]
> Does this example help you?
> 
> https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html

In fact, this is extremely helpful. Thank you so much!
