### ISSUE TITLE
Breaking change in 3.2: quiver.set_UVC does not support single numbers any more

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#16743]
### Bug report

**Bug summary**

In prior versions of matplotlib, it was possible to set all UVC values to the same by calling `quiver.set_UVC` with single numbers for U and V. This raises an error in matplotlib 3.2.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

q = plt.quiver(
    [0, 0, 1],
    [0, 1, 1],
    [0.5, 0.5, 0.5],
    [0, 0, 0],
)

q.set_UVC(0, 0.5)
plt.xlim(-1, 2)
plt.ylim(-1, 2)
plt.show()

```

**Actual outcome**

matplotlib 3.1 works as expected, matplotlib 3.2 raises:

```
    q.set_UVC(0, 0.5)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/matplotlib/quiver.py", line 604, in set_UVC
    raise ValueError(f'Argument {name} has a size {var.size}'
ValueError: Argument U has a size 1 which does not match 3, the number of arrow positions
```

**Expected outcome**

No breaking changes between minor revisions.

**Comment by tacaswell** [comment]
Sorry about that!
