### ISSUE TITLE
Legend && Draggable

### ISSUE THREAD

**Issue by kanhaiya-gupta** [matplotlib/matplotlib#16756]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
# Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from matplotlib import pyplot as plt
>>> import numpy as np
>>> 
>>> x = np.linspace(-2.*np.pi, 2.*np.pi, 1000)
>>> y = np.sin(x)
>>> plt.plot(x, y, '-', lw=2, label='Sine curve')
[<matplotlib.lines.Line2D object at 0x7f46ace082d0>]
>>> leg = plt.legend(loc='best', fontsize=20)
>>> leg.draggable(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Legend' object has no attribute 'draggable'
>>> plt.show()
>>> leg.draggable(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Legend' object has no attribute 'draggable'

#  Another Code 
Traceback (most recent call last):
  File "neww.py", line 18, in <module>
    myPlot.plot_all()
  File "/home/kanhaiya/anaconda3/lib/python3.7/site-packages/kafe/plot.py", line 455, in plot_all
    self.draw_legend()
  File "/home/kanhaiya/anaconda3/lib/python3.7/site-packages/kafe/plot.py", line 502, in draw_legend
    self.legend.draggable()
AttributeError: 'Legend' object has no attribute 'draggable'

#

```

**Actual outcome**

```
# If applicable, paste the console output here
#
# File "/home/kanhaiya/anaconda3/lib/python3.7/site-packages/kafe/plot.py", line 455, in plot_all
    self.draw_legend()
  File "/home/kanhaiya/anaconda3/lib/python3.7/site-packages/kafe/plot.py", line 502, in draw_legend
    self.legend.draggable()
AttributeError: 'Legend' object has no attribute 'draggable'

#
```

**Expected outcome**
Figure 

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
There is no `Legend.draggable`; there is [`Legend.set_draggable`](https://matplotlib.org/_modules/matplotlib/legend.html#Legend.set_draggable), though.

**Comment by ImportanceOfBeingErnest** [comment]
`Legend.draggable()` has been deprecated in matplotlib 3.0 and has been removed in 3.1. I think that was a bit quick - isn't there a rule to have at least 2 minor versions in between?

In any case, there is a fix in `kafe` already, see https://github.com/dsavoiu/kafe/commit/462a81853815b3d6dc299500ce872713ea386af8, but apparently no new release as of now. 
Options are:  
(1) Use matplotlib 3.0 or earlier with your existing kafe install
(2) Install the development version of kafe
(3) Manually apply the fix from https://github.com/dsavoiu/kafe/commit/462a81853815b3d6dc299500ce872713ea386af8 to your version.

**Comment by kanhaiya-gupta** [comment]
Thank you so much.

That solved my problem.

Thanking  you
Kanhaiya Gupta

**Comment by kanhaiya-gupta** [comment]
Solved

**Comment by kanhaiya-gupta** [comment]
/anaconda3/lib/python3.7/site-packages/kafe/plot.py:817: MatplotlibDeprecationWarning: Passing the block parameter of show() positionally is deprecated since Matplotlib 3.1; the parameter will become keyword-only in 3.3.
  plt.show(self.axes)

How do I edit for the contour plot for the code?
contour1 = myFit.plot_contour(0, 1, dchi2=[1., 2.3])

**Comment by ImportanceOfBeingErnest** [comment]
`plt.show(self.axes)` never made sense, even before the deprecation.  
This is a deprecation warning, meaning kafe developpers should take care of making their code correct before matplotlib 3.3 is released.

**Comment by kanhaiya-gupta** [comment]
The actual description is 

def show(self):
        '''
        Show graphics in one or more matplotlib interactive windows.

        Note
        ----
            This shows all figures/plots generated before it is called. Because
            of the way ``matplotlib`` handles some plotting parameters
            (``matplotlib.rcParams``) these cannot be set individually for each
            figure before it is displayed. This means that all figures will be
            shown with the same plot style: that of the `Plot` object from
            which show() is called.
        '''
        self._update_rcParams()
        plt.show(self.axes)

**Comment by ImportanceOfBeingErnest** [comment]
Yes, the line `plt.show(self.axes)` in their code is wrong (and has always been!). Please discuss this with the kafe maintainers - they need to correct it.
