### ISSUE TITLE
Different significant figures produced by format between print() and matplotlib

### ISSUE THREAD

**Issue by Gabriel-p** [matplotlib/matplotlib#16759]
### Bug report

**Bug summary**

As the title indicates

```python
import matplotlib.pyplot as plt
    
var = 0.015573443983402477
print("{:.2f}".format(var))
    
plt.scatter(.5, .5, label="var={:.2}".format(var))
plt.legend()
plt.show()
```

**Actual outcome**

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/TDN8Z.png

**Expected outcome**

As the `print()` statement correctly shows:

    0.02

**Matplotlib version**

  * Operating system: elementary OS 5.1.2
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.2
  * Jupyter version (if applicable):
  * Other libraries: 

I'm using the installation from the default `conda` channel.

**Comment by ImportanceOfBeingErnest** [comment]
This has nothing to do with matplotlib. Compare the output of

    print("{:.2f}".format(var))

and 

    print("var={:.2}".format(var))

**Comment by Gabriel-p** [comment]
That's even weirder. Thank for pointing it out.

**Comment by tacaswell** [comment]
See https://docs.python.org/3.8/library/string.html#format-specification-mini-language (have to scroll down a bit)

'.2f' -> "fixed point to 2 decimal places"
'.2' ~ '.2g' -> "2 significant figures"

**Comment by Gabriel-p** [comment]
I just realized I was using `{.2f}`  and `{.2}`. Thanks for the link @tacaswell
