### ISSUE TITLE
Contourf contours different for positive/negative data

### ISSUE THREAD

**Issue by milankl** [matplotlib/matplotlib#16792]
### Bug report

**Bug summary**

Contourf creates contours that are different for positive and negative data. Inverting the sign of the data and reverting the colormap at the same time does not yield the same result for contourf (although it should), however, it does so for pcolormesh.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

# CREATE DATA
lon = np.linspace(-180,180,90)
lat = np.linspace(-90,90,45)
d = np.random.randn(len(lat),len(lon))

# PLOTTING
fig,ax = plt.subplots(2,2, figsize=(15,8))

# colorbar levels
cminmax = [-4,4]
clevs = np.arange(cminmax[0],cminmax[1]+1,1)
clevsNeg = -clevs[::-1]

cs = ax[0,0].contourf(lon,lat,d, clevs,cmap='bwr')
fig.colorbar(cs, ax=ax[0,0])
ax[0,0].set_title('contourf with pos. data and normal cmap')

cs2 = ax[0,1].contourf(lon,lat,-d, clevsNeg,cmap='bwr_r')
fig.colorbar(cs2, ax=ax[0,1])
ax[0,1].set_title('contourf with neg. data and reversed cmap')

cs3 = ax[1,0].pcolormesh(lon,lat,d, vmin=cminmax[0],vmax=cminmax[1],cmap='bwr')
fig.colorbar(cs3, ax=ax[1,0])
ax[1,0].set_title('pcolormesh with pos. data and normal cmap')

cs4 = ax[1,1].pcolormesh(lon,lat,-d, vmin=cminmax[0],vmax=cminmax[1],cmap='bwr_r')
fig.colorbar(cs4, ax=ax[1,1])
ax[1,1].set_title('pcolormesh with neg. data and reversed cmap')

plt.show()
```

**Actual outcome**
![contourf_issue](https://user-images.githubusercontent.com/25530332/76784513-b0b5e280-67ab-11ea-84f9-4b4059e92ef9.png)

**Expected outcome**

Top left subplot should look the same as top right subplot, as can be seen for plotting the same data with pcolormesh (bottom left & right).

**Matplotlib version**
  * Operating system: macOS or Ubuntu 18
  * Matplotlib version: 3.1.1 or 3.2.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.9

**Comment by timhoffm** [comment]
Confirmed.

Interestingly, if I take a simpler data pattern it seems to show correctly:
~~~
X, Y = np.meshgrid(lon, lat)
d = X/90 + (Y/45)**2 - 2
~~~

![grafik](https://user-images.githubusercontent.com/2836374/76939760-457a2680-68f9-11ea-8006-020ef9760689.png)

It may be that there is a slight position offset, but I can't really tell. At least position offset is the direction I would recommend to investigate.

**Comment by milankl** [comment]
Thanks Tim. It's just harder to see in your example. Check the zero isoline how it just not touches the right boundary in the top left subplot vs how the same line crosses the right boundary in the top right subplot

**Comment by jklymak** [comment]
Imagine I have two data values on the x axis, say 0 and 2, and I discretize the x-axis into 4 divisions , i.e. 0, 0.666, 1.3333, and 2, and I ask for where the 1 value is.  If I come at it from below I get 0.6666, and if I come at it from above I get 1.3333.  Thats all thats happening here.  

From the docstring:
> contourf fills intervals that are closed at the top; that is, for boundaries z1 and z2, the filled region is:
>
> `z1 < Z <= z2`

If you make all these negatives, the inequality is satisfied in the other direction and the contours are slightly different.  

I don't think this is a bug, but just a consequence of discretization;  If you want to avoid, use more contour levels for more precision.

**Comment by timhoffm** [comment]
@jklymak is right. The issue is coloring of values that are exactly on the boundary. The the direction of the half-open interval reverses upon reversal of the cmap.

E.g. for 0:

![grafik](https://user-images.githubusercontent.com/2836374/77051171-2ba91400-69cb-11ea-943f-54a4d94beed1.png)

But for 1-e10:
![grafik](https://user-images.githubusercontent.com/2836374/77051496-aa05b600-69cb-11ea-96e0-49af8c04e66c.png)

We have to make a decision how these boundary values are colored. I think this is done in a consistent way and it's documented. I don't see any need for further action.

**Comment by milankl** [comment]
Great explanation, thanks everyone. That's why having lots of contour levels is actually important!

**Comment by milankl** [comment]
Sorry, I'm not convinced by this argument @timhoffm. From `z1 < Z <= z2` I would also conclude that

> to avoid, use more contour levels for more precision.

As @jklymak said, because the difference in colours between levels decreases for increasing number of contour levels. However, tweaking the code from further up with
```python
nlevs = 256
clevs = np.linspace(cminmax[0],cminmax[1],nlevs+1)
```
yields
![image](https://user-images.githubusercontent.com/25530332/77121731-c9382e00-6a33-11ea-8000-11f65cee82ad.png)
Where I see the colour of some points jumping many contour levels between the top right and the top left.

**Comment by timhoffm** [comment]
I see. But no idea where that's coming from :slightly_frowning_face:.

**Comment by jklymak** [comment]
Please set `vmin` and `vmax` in your calls to `contourf`.  You will see that the apparent large scale shade differences disappear, and that the remaining differences are small shifts in where the contour is.  

Also, for consistency, please include a seed to your random data.

The point is that yes, there will be one-data-pixel jitter in the location of the contours due to the inequality having to be deterministic on one side or the other.  


```python
import numpy as np
import matplotlib.pyplot as plt

# CREATE DATA
lon = np.linspace(-180,180,90)
lat = np.linspace(-90,90,45)
np.random.seed(19680808)
d = np.random.randn(len(lat),len(lon))
#d = np.cumsum(np.cumsum(d, axis=0), axis=1)
#d = d / np.max(np.abs(d))

# PLOTTING
fig,ax = plt.subplots(2,2, figsize=(15,8))

# colorbar levels
cminmax = [-4,4]
clevs = np.linspace(cminmax[0], cminmax[1], 10)
clevsNeg = -clevs[::-1]

cs = ax[0,0].contourf(lon,lat,d, clevs,cmap='bwr',
                      vmin=cminmax[0], vmax=cminmax[1])
fig.colorbar(cs, ax=ax[0,0])
ax[0,0].set_title('contourf with pos. data and normal cmap')

cs2 = ax[0,1].contourf(lon,lat,-d, clevsNeg,cmap='bwr_r',
                        vmin=cminmax[0], vmax=cminmax[1])
fig.colorbar(cs2, ax=ax[0,1])
ax[0,1].set_title('contourf with neg. data and reversed cmap')

cs3 = ax[1,0].pcolormesh(lon,lat,d, vmin=cminmax[0],vmax=cminmax[1],cmap='bwr')
fig.colorbar(cs3, ax=ax[1,0])
ax[1,0].set_title('pcolormesh with pos. data and normal cmap')

cs4 = ax[1,1].pcolormesh(lon,lat,-d, vmin=cminmax[0],vmax=cminmax[1],cmap='bwr_r')
fig.colorbar(cs4, ax=ax[1,1])
ax[1,1].set_title('pcolormesh with neg. data and reversed cmap')

plt.show()
```

![ContourfDemo](https://user-images.githubusercontent.com/1562854/77198727-c7f31980-6aa4-11ea-9c86-b1057034c1bb.png)

**Comment by jklymak** [comment]
I guess a final hint is to avoid an odd number of levels so some of your data can be white.

**Comment by milankl** [comment]
Could we not have `vmin = clevs[0]` and `vmax = clevs[-1]` not set by default then? I guess most users would solely rely on providing `clevs`.

**Comment by jklymak** [comment]
Then folks would be confused when the default didn't agree with the default in `pcolormesh` or `imshow`.

**Comment by milankl** [comment]
@jklymak I can't reproduce your hack with `vmin`, `vmax`. Specifying these arguments has no effect for me. It also seems from the [documentation](https://matplotlib.org/3.2.0/api/_as_gen/matplotlib.pyplot.contourf.html)

> **vmin, vmaxfloat**, optional
> 
>  If not None, either or both of these values will be supplied to the Normalize instance, overriding the default color scaling based on levels.

That something like `vmin = clevs[0]` and `vmax = clevs[-1]` is actually happening under the hood?

**Comment by jklymak** [comment]
`vmin` and `vmax` definitely work with `contourf`.   Not sure what you are saying is not working.

**Comment by milankl** [comment]
Not reproducible, as in when I run your code then I get
![index](https://user-images.githubusercontent.com/25530332/77329537-03484f00-6d16-11ea-858e-f11968856835.png)
and not the plot that you posted. If I set the number of contourf levels high, then the problem persists, and it also doesn't depend on whether this number is even or odd.

**Comment by jklymak** [comment]
OK, it does depend on the dpi....

dpi=50

![Contour50](https://user-images.githubusercontent.com/1562854/77331169-96b15e00-6cdd-11ea-807d-0a857bc85b45.png)

dpi=200

![Contour200](https://user-images.githubusercontent.com/1562854/77331217-a8930100-6cdd-11ea-949b-ff6fd10da8d9.png)

dpi=300

![Contour300](https://user-images.githubusercontent.com/1562854/77331368-ded08080-6cdd-11ea-9e92-19ee7e8d05fb.png)

PDF:

[contour.pdf](https://github.com/matplotlib/matplotlib/files/4370207/contour.pdf)

**Comment by milankl** [comment]
Yes, I can confirm that. For higher dpi, postive and negative plot seem to converge, independent of vmin/max. Saving in dpi=300 and then lowering resolution if needed seems to be a intermediate workaround. But what's the problem then?

**Comment by jklymak** [comment]
the problem is you have too few pixels to represent the data and hence you get aliasing.  The asymmetry of the aliasing is explained above.
