### ISSUE TITLE
Doc: figure for colormaps off

### ISSUE THREAD

**Issue by jrwrigh** [matplotlib/matplotlib#16801]
The first image on the latest documentation for ["Choosing Colormaps in Matplotlib"](https://matplotlib.org/3.1.3/tutorials/colors/colormaps.html?highlight=colormaps#lightness-of-matplotlib-colormaps) has the Y axis label in weird, non-centered position.

The culprit file appears to be somewhere in this area.
https://github.com/matplotlib/matplotlib/blob/e154a0d1a5e61527df6142dc7a0953d22fd2e2ab/tutorials/colors/colormaps.py#L227-L230

**Comment by tacaswell** [comment]
Thanks for reporting this!  Agree that is where the bug is.

**Comment by QuLogic** [comment]
That's because the 'y-label' is actually some figure text that's placed at a fixed location in each figure (which may have multiple y-labels). I'm not sure it really buys us anything to use that single label instead of one for each Axes.
