### ISSUE TITLE
I installed matplotlib using anaconda and when i try to import matplotlib i get check version error in jupyter notebook and pycharm .

### ISSUE THREAD

**Issue by PROJECT-HELLER** [matplotlib/matplotlib#16857]
I installed matplotlib using anaconda and when i tried to import  "import matplotlib.pyplot as plt" , i recive the following error.

/////////////////////////////////////////////////////////////////////////////////////////////////////////
ImportError                               Traceback (most recent call last)
<ipython-input-1-3e09cd8c1b79> in <module>
----> 1 import matplotlib.pyplot as plt
      2 import numpy as np
      3 
      4 x = [1, 2, 2.5, 3, 4]
      5 y = [1, 4, 7, 9, 15]

C:\Anaconda\envs\tensorflow\lib\site-packages\matplotlib\__init__.py in <module>
    203 
    204 
--> 205 _check_versions()
    206 
    207 

C:\Anaconda\envs\tensorflow\lib\site-packages\matplotlib\__init__.py in _check_versions()
    188     # Quickfix to ensure Microsoft Visual C++ redistributable
    189     # DLLs are loaded before importing kiwisolver
--> 190     from . import ft2font
    191 
    192     for modname, minver in [

ImportError: DLL load failed: %1 is not a valid Win32 application.

///////////////////////////////////////////////////////////////////////////////////////////////////////////

I tried reinstalling using pip but everytime i recive this error, both in jupyter notebook and pycharm ide. 
Please help me regarding this. I would be highly obliged to you.

**Comment by jklymak** [comment]
We encourage asking for install help at discourse.matplotlib.org.  FWIW. please make sure your Jupyter is being invoked from the same environment as you installed matplotlib (i.e. do `conda install jupyter` there.)  I'm going to close for discussion at the discourse.

**Comment by PROJECT-HELLER** [comment]
I did everything but this error comes every time. Please help me,
