### ISSUE TITLE
Hexbin mincnt parameter docstring should say "more than or equal to" not "more than"

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotlib#16865]
The current docstring for `hexbin` has this for `mincnt`:

```python
mincnt : int > 0, default: *None*
    If not *None*, only display cells with more than *mincnt*
    number of points in the cell.
```

But, it really displays cells that have more than or equal to `mincnt`.

The `int > 0` is also slightly confusing. It does accept 0 and negative numbers and can appear to relate to the 'more than' below when it does not.

**Comment by anntzer** [comment]
There's also the problem that when C is None, the condition is >= mincnt (as you write), but when C is not None, the condition is > mincnt (as documented).  Perhaps this should be made consistent first?  (I think >= mincnt makes more sense?)

**Comment by tdpetrou** [comment]
Agreed, consistency should be done first. >= makes more sense to me as well as it is a minimum count.

**Comment by anntzer** [comment]
Actually, looking at this again, I think I see why it's > for the case with a reducer: with the effective mincnt default of 0 (None is converted to 0), we don't want to get a warning with np.mean(empty_list), but just get nan straight away (at least np.mean([]) returns nan with a warning, but np.max() would be even worse as it raises an exception).

On the other hand, in the case without C, it makes sense to keep empty cells mapped, well, to zero.

Not sure if there's an easy way out there...

**Comment by anntzer** [comment]
https://github.com/matplotlib/matplotlib/pull/26113#issuecomment-1635816609 is likely still a problem for now.
