### ISSUE TITLE
use freetype from system

### ISSUE THREAD

**Issue by nicola-lunghi** [matplotlib/matplotlib#16878]
Hi,

I need to build matplotlib and I need to tell the build system to use the freetype version from the syste,

can anyone help me with this??

Thanks
Nicola Lunghi

**Comment by anntzer** [comment]
Please provide the relevant info: what version of matplotlib? what os? why do you want to use system freetype?

**Comment by nicola-lunghi** [comment]
Hi
I am trying to build matplotlib 3.2.1 on linux  yocto
I am cross compiling for arm
I already have freetype_2.10.1 available on my system.

How can I instruct matplotlib to use the library from the system and not build it?
-> can I have it use pkg-config?

**Comment by nicola-lunghi** [comment]
ok 
I have build without specifying anything and I get in python 3.8.1
```
>>> import matplotlib
>>> matplotlib.test()
Matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below. Expected freetype version 2.6.1. Found freetype version 2.10.1. Freetype build type is not local
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't close file
Aborted
```

**Comment by nicola-lunghi** [comment]
but if I set local_freetype=True I got

```
| running build_ext
| error: Failed to download FreeType. Please download one of ['https://downloads.sourceforge.net/project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz', 'https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz'] and extract it into build/freetype-2.6.1 at the top-level of the source repository.
```

**Comment by tacaswell** [comment]
A bulk of our test suite is image comparison tests that checks that the generated images match the baseline images exactly.  However many of the tests have text in the images, for the tests to pass you must use the same version of freetype we generated the baseline images with.

I suggest looking at how Fedora and Debian patch Matplotlib to be able to run the tests.

https://matplotlib.org/devel/contributing.html?highlight=freetype#building-matplotlib-for-image-comparison-tests

attn @QuLogic

**Comment by QuLogic** [comment]
Debian just [ignores test comparison failures](https://salsa.debian.org/python-team/modules/matplotlib/-/blob/master/debian/patches/0012-dont-generate-a-test-failure-if-images-are-not-close.patch). Fedora uses new images that I've verified are correct, or at least not totally wrong, from https://github.com/QuLogic/mpl-images.

**Comment by twmht** [comment]
got the same issue on ubuntu 18.04

**Comment by xonobo** [comment]
same issue on nvidia jetson tx1 with jetpack 4.4

**Comment by QuLogic** [comment]
The original report was asking how to build again system FreeType, and that's been fixed, so I don't think this needs to stay open.
