### ISSUE TITLE
Permission issue while adding Arm64 jobs in Travis-CI

### ISSUE THREAD

**Issue by odidev** [matplotlib/matplotlib#16879]
**While adding Arm64 jobs in travis.yml, getting permission issue while building wheel for pandas.**

**Code for reproduction**
Added following code in travis.yml
`- python: 3.8
         env:
            - EXTRAREQS='-r requirements/testing/travis_extra.txt'
  - python: 3.8
      arch: arm64
      env:
        - EXTRAREQS='-r requirements/testing/travis_extra.txt'`

**Actual outcome**
```
Building wheels for collected packages: coverage, tornado, pandas, pandocfilters, backcall, pyzmq, MarkupSafe, pyrsistent
  WARNING: Building wheel for coverage failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/b1'
  WARNING: Building wheel for tornado failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/88'
  WARNING: Building wheel for pandas failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/23'
  WARNING: Building wheel for pandocfilters failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/f6'
  WARNING: Building wheel for backcall failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/19'
  WARNING: Building wheel for pyzmq failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/48'
  WARNING: Building wheel for MarkupSafe failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/0c'
  WARNING: Building wheel for pyrsistent failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/be'
Failed to build coverage tornado pandas pandocfilters backcall pyzmq MarkupSafe pyrsistent
ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly
The command "# Install dependencies from PyPI.
  python -mpip install --upgrade $PRE -r requirements/testing/travis_all.txt $EXTRAREQS $PINNEDVERS
  " failed and exited with 1 during .
```
**Expected outcome**
`As it is getting passed for amd64 platform.`
**Matplotlib version**
`Latest`

**Comment by tacaswell** [comment]
This probably should be reported to travis, I would expect those folders to be writable.

Might be worth adding some debugging commands to sort out what the permissions on those directories are and see if you can use chmod/chown to fix them.

**Comment by odidev** [comment]
HI @tacaswell, permission issue while building wheel for pandas can be resolved by adding env as  "PIP_NO_CACHE_DIR=off" for arm64 jobs.
but since wheel is not available for aarch64 it takes aroung 45 min to build wheel for pandas. In travis-CI we can run any job upto 50 minutes maximum. hence build is getting exited in between 
 execution after 50 minutes. Please have a look at the log:
https://travis-ci.com/github/Ross1503/matplotlib/jobs/318742213

Is there any way that we can increase this maximum timeout limit  for one job in travis-CI for this package.

**Comment by tacaswell** [comment]
pandas is only an optional test dependency, the "fix" may be to just not install pandas for this job.

**Comment by oscargus** [comment]
Closing as Travis is no longer used.
