### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.backends.backend_svg'

### ISSUE THREAD

**Issue by JiaxiangBU** [matplotlib/matplotlib#16875]
### Bug report

**Bug summary**

I use `pandas_profiling` to take a data analysis result. `pandas_profiling` uses the `matplotlib.backends.backend_svg`, but python prints this module is not found. I don't know how to install it only, so I upgrade matplotlib. However, it does not work.

**Code for reproduction**

```python
# Paste your code here
# !pip install pandas-profiling
import pandas_profiling
import matplotlib.backends.backend_svg
```

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-92-e7b59767d44b> in <module>
      1 # !pip install pandas-profiling
      2 import pandas_profiling
----> 3 import matplotlib.backends.backend_svg

ModuleNotFoundError: No module named 'matplotlib.backends.backend_svg'
```

```python
matplotlib.__version__
'3.0.2'
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 7 x64
  * Matplotlib version: '3.0.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`):`module://ipykernel.pylab.backend_inline`
  * Python version:`Python 3.7.3`
  * Jupyter version (if applicable):`jupyter-notebook : 6.0.0`
  * Other libraries: `pandas_profiling.__version__ 2.5.0`

**Comment by tacaswell** [comment]
How did you install Matplotlib?

This looks like a packaging / installation problem.

**Comment by JiaxiangBU** [comment]
> How did you install Matplotlib?
> 
> This looks like a packaging / installation problem.

Yes, I also find other modules like `matplotlib.xxx` cannot be loaded. After reinstallation, it works. @tacaswell 

I will close this issue.

**Comment by JiaxiangBU** [comment]
The problem is Python choose `~\AppData\Roaming\Python\...` as the directory of the module. So I delete it and reimport Matplotlib and it works.

    ```bash
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-2-451dd3e21c6e> in <module>
          1 import numpy as np
          2 import pandas as pd
    ----> 3 import matplotlib.pyplot as plt
          4 plt.style.use('ggplot')
          5 import seaborn as sns
    
    ~\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py in <module>
         30 from cycler import cycler
         31 import matplotlib
    ---> 32 import matplotlib.colorbar
         33 import matplotlib.image
         34 from matplotlib import rcsetup, style
    
    ~\AppData\Roaming\Python\Python37\site-packages\matplotlib\colorbar.py in <module>
         26 
         27 import matplotlib as mpl
    ---> 28 import matplotlib.artist as martist
         29 import matplotlib.cbook as cbook
         30 import matplotlib.collections as collections
    
    ModuleNotFoundError: No module named 'matplotlib.artist'
    ```

**Comment by Sachin-R-Ladhad** [comment]
I am also facing same issue please can you explain in detail "delete it and reimport Matplotlib"

**Comment by tacaswell** [comment]
It is likely that you have broken your installation.  I suggest fully uninstalling Matplotlib (via what ever mechanisms you installed it with) and then re-installing.

**Comment by nidhis-code-studio** [comment]
after upgrading Matplotlib check this as well

Go to this location
~\AppData\Roaming\Python\Python37\site-packages\
and check the folder name ..
for some weird reason matplotlib is saved as ~atplotlib folder.
just rename ~atplotlib folder as matplotlib

**Comment by tacaswell** [comment]
@nidhis-code-studio What OS and what upgrade path produced that issue?  That is something we should track down and make sure gets reported to the correct project as a bug...

**Comment by nidhis-code-studio** [comment]
> @nidhis-code-studio What OS and what upgrade path produced that issue? That is something we should track down and make sure gets reported to the correct project as a bug...

I am using Windows 10 with conda 4.8.3

**Comment by tacaswell** [comment]
Can you report this to anaconda?
