### ISSUE TITLE
Change return type get_{x,y}ticklabels to plain list

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotlib#16885]
Its fairly often that I use `get_xticklabels` and other similar methods when exploring and visualizing data with matplotlib. I almost always use `list(ax.get_xticklabels())` or `ax.get_xticklabels()[0]` to view. When teaching, it's also much nicer to be able to see some of the labels without this workaround. One of the main purposes of the getter methods is to actually see a nice underlying representation of the object.

I see from the docstrings that the purpose of `silent_list` is to silence the repr, but perhaps this can change.  `get_xticks` returns an array. `get_lines` and `get_labels` return a silent list.

Is the silent list even necessary?

**Comment by anntzer** [comment]
I agree that especially for ticklabels, returning a plain list is fine -- it is "unlikely" that there are so many tick labels that this drowns out the terminal.

**Comment by tdpetrou** [comment]
I think I see the purpose of a silent list - to shorten the output of those plotting methods that return many items (like `bar` or `plot`). I almost never want to see that output. 

Do tick labels or lines ever get returned outside of the getter methods? If not, then the only reason they are accessed is to view their values.

Another option is to display for first and last 3 values.

**Comment by anntzer** [comment]
My point is not to switch to plain lists everywhere, but indeed only for ticklabels where plain lists do seem better than silent_list.

**Comment by ImportanceOfBeingErnest** [comment]
In the standard case `list(ax.get_xtickslabels())` would return something like

    [Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, '')]

I don't see how this is useful to see as output.

**Comment by tdpetrou** [comment]
Can you explain how thats the 'standard' case? The only time I view the repr for tick labels is when I purposefully access them with a getter method. Also, calling `set_xticklabels` returns a list and not a silent_list.

**Comment by ImportanceOfBeingErnest** [comment]
By standard case I mean:

```
import matplotlib.pyplot as plt
plt.plot([32,34,21])
print(list(plt.gca().get_xticklabels()))
```

**Comment by tacaswell** [comment]
The simplest path here is to consider changing the return type of `get_xticklabels()` to be a normal `list`.
