### ISSUE TITLE
if pie normalizes depends on input values

### ISSUE THREAD

**Issue by shankhoghosh** [matplotlib/matplotlib#16905]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
values = [0.17205503009458298,
 0.1122098022355976,
 0.0005159071367153912,
 0.4616509028374893,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

labels= ['Coal',
 'Oil',
 'Natural gas',
 'Hydro',
 'Geothermal',
 'Solar PV',
 'Wind',
 'Tide',
 'Nuclear',
 'Biofuels',
 'Waste',
 'Solar thermal']
colors= [(0.0, 0.0, 0.0, 0.7),
 (1.0, 0.0, 0.0, 0.7),
 (0.5019607843137255, 0.5019607843137255, 0.5019607843137255, 0.7),
 (0.0, 0.0, 0.5019607843137255, 0.7),
 (0.8235294117647058, 0.4117647058823529, 0.11764705882352941, 0.7),
 (1.0, 1.0, 0.0, 0.7),
 (0.0, 0.5019607843137255, 0.5019607843137255, 0.7),
 (0.0, 1.0, 1.0, 0.7),
 (0.5019607843137255, 0.0, 0.5019607843137255, 0.7),
 (0.0, 1.0, 0.0, 0.7),
 (0.5647058823529412, 0.9333333333333333, 0.5647058823529412, 0.7),
 (1.0, 0.8431372549019608, 0.0, 0.7)]

import matplotlib.pyplot as plt

fig,ax = plt.subplots()
ax.pie(x=values,labels=labels,labeldistance=None)
# End
```

**Actual outcome**

![plot](https://user-images.githubusercontent.com/32898536/77561591-edd54f80-6ee4-11ea-821a-e0d37b659fe5.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by shankhoghosh** [comment]
I think I found the problem. Right now if I just multiply the values by 10000. Then the plot is generated without the missing piece.

**Comment by QuLogic** [comment]
This is expected behaviour; please see the [docstring of `pie`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.pie.html):
> If `sum(x) < 1`, then the values of *x* give the fractional area directly and the array will not be normalized. The resulting pie will have an empty wedge of size `1 - sum(x)`.

Your values sum to 0.746.

**Comment by timhoffm** [comment]
The behavior is correctly documented.

Nevertheless, should we change it? ("In the face of ambiguity refuse the temptation to guess.")

It's a bit of magic, that `x` and `x*100` give the same plot for `x = np.array([0.2, 0.3, 0.4, 0.1])`, but not for `x = np.array([0.2, 0.3, 0.4])`.

An alternative would be to make this explicit by introducing a parameter `normalize`. When True, always make a full pie by normalizing `x` so that `sum(x) == 1`. When False, make a partial pie or error out if `sum(x) > 1`. Deprecation period: `normalize=None` gives the current behavior and if `sum(x) < 1` warn that you should explicitly pass `normalize=False`. After the deprecation period change the default to `normalize=True`.

**Comment by tacaswell** [comment]
I am :+1: on @timhoffm 's suggestion of adding a normalize kwarg.

**Comment by raphacosta27** [comment]
Hi guys, I think I'll take this issue. Is there someone already in it?

**Comment by tacaswell** [comment]
Nope, go for it @raphacosta27

**Comment by raphacosta27** [comment]
Hi there again, thanks for the quick answer.
There's already a normalization for the cases that `sum(x) > 1`, should I move this part together with the handler for the cases that `sum(x) < 1` or let it out just like it's already there?
Below, the part of the code I was talking about.
``` 
sx = x.sum()
if sx > 1:
   x = x / sx

#my code goes here 
```

**Comment by raphacosta27** [comment]
Also, should I add something to the doc/api/next_api_changes file?

**Comment by tacaswell** [comment]
This should definitely be documented in api_changes and maybe in whats_new.  The behavior to implement is what is described by @timhoffm [above](https://github.com/matplotlib/matplotlib/issues/16905#issuecomment-605668370):

> An alternative would be to make this explicit by introducing a parameter normalize. When True, always make a full pie by normalizing x so that sum(x) == 1. When False, make a partial pie or error out if sum(x) > 1. Deprecation period: normalize=None gives the current behavior and if sum(x) < 1 warn that you should explicitly pass normalize=False. After the deprecation period change the default to normalize=True.

This will also need tests that it warns when we expect it to and that in normalizes (or not) when we  expect.

**Comment by QuLogic** [comment]
Fixed by the above PR.
