### ISSUE TITLE
type1ec.sty needed for TeX output of plots. Not a standard texlive

### ISSUE THREAD

**Issue by LRydin** [matplotlib/matplotlib#16911]
### Bug report

**Bug summary**

`type1ec.sty` not found. I have never encountered this before v3.2.1. Standard texlive (`apt install texlive-latex-extra`) does not come with this (only `type1cm.sty`).

**Code for reproduction**

```python
import numpy as np
import matplotlib
matplotlib.rcParams['pgf.texsystem'] = 'pdflatex'
matplotlib.rcParams.update({'font.family': 'serif', 'font.size': 18,
    'axes.labelsize': 20,'axes.titlesize': 24, 'figure.titlesize' : 28})
matplotlib.rcParams['text.usetex'] = True
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1)
x = np.random.norm(0,1)
y = np.random.norm(0,2)
ax.plot(x,y, label='a label')
ax.legend(fontsize=15)
```

**Actual outcome**

Sorry for the short description, 
```
...
type1ec.sty not found.
...
```

**Expected outcome**

 Expected no problems with plotting. `fontsize=12` runs on some choices of label. Labels with a single character also produce no error...

**Fix**
on linux: `apt install cm-super`.

Is it now necessary  to have cm-supper for plotting TeX? 

**Matplotlib version**

  * Operating system: Linux (Ubuntu 19.10)
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline` (seems strange to me)
  * Python version: 3.7.6
  * Jupyter version (if applicable): 6.0.3
  * Other libraries:

**Comment by anntzer** [comment]
Yes, this has been made necessary so that unicode input works.

**Comment by LRydin** [comment]
Wonderful, thanks. If not included in the documentation, I would say it is helpful to do so :)

Cheers

**Comment by RiteshBhola** [comment]
Thank you
It solved my issue.

**Comment by zhu00ling** [comment]
i solved this bug on ubuntu by adding the cm-super. but the same bug appears on mac.

**Comment by sanurielf** [comment]
> i solved this bug on ubuntu by adding the cm-super. but the same bug appears on mac.

I solved using tlmgr in OSX:

`sudo tlmgr install cm-super`

**Comment by ale-munozarancibia** [comment]
In Fedora 35, I kept having the "not found" error for type1ec.sty and type1cm.sty although both were installed. I was able to solve it installing texlive-psutils with dnf.

**Comment by shikhar-saxena** [comment]
I keep getting the "not found" error too. And I couldn't fix it, despite installing `cm-super`?

**Comment by RiteshBhola** [comment]
Have you also installed dvi-png and ghostscript?

**Comment by shikhar-saxena** [comment]
Yeah I have installed both of them but it doesn't work for some reason.
________________________________

**Comment by shikhar-saxena** [comment]
Yeah I have installed both of them but it doesn't work for some reason.

**Comment by drscotthawley** [comment]
Same issue.   Trying to get it working on Colab (which runs Debian) 

Attempted fixes so far include...
```bash
!sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended 
!sudo tlmgr install cm-super  
!sudo apt install texlive-latex-base
!sudo tlmgr install type1cm
```
...but trying to create figure with latex support still produces. 
```
! LaTeX Error: File `type1ec.sty' not found.
```



I'm noticing that the `tlmgr` commands tend to produce the following message:

```
(running on Debian, switching to user mode!)
(see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)

tlmgr: Local TeX Live (2021) is older than remote repository (2023).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

I cannot find any `update-tlmgr-latest` on the Colab hard drive, even after installing the above packages. (And even after installing `locate`!)


Other suggestions?

**Comment by OleHolmNielsen** [comment]
We struggled with finding an appropriate RPM package for RockyLinux 9 (clone of RHEL 9), and found that this package needs to be installed:
# dnf install texlive-type1cm
