### ISSUE TITLE
SyntaxError while compiling bacis_units.py file

### ISSUE THREAD

**Issue by dakmorzg** [matplotlib/matplotlib#16914]
### Bug report

**Bug summary**

I've found a way to convert units on x and y axis: [units_sample](https://matplotlib.org/3.1.1/gallery/units/units_sample.html) where basic_units.py file is [linked](https://matplotlib.org/3.1.1/_downloads/3a73b4cd6e12aa53ff277b1b80d631c1/basic_units.py).
I've tried to run example, but PyCharm returns few invalid syntax errors in basic_units.py. I've found ["Matplotlib Release 1.4.3" documentation](https://matplotlib.org/1.4.3/Matplotlib.pdf), where are differences against downloaded file. 
I did some corrects according to pdf (removing 'f' flag in front of some strings), then it runs well (without error at least).
Below, in a "code for reproduction" section, is a list of lines with syntax error.

**Code for reproduction**

```python
subcls = type(f'TaggedValue_of_{value_class.__name__}',  # line 125
return f'BasicUnit({self.name})'  # line 198
return fr'${n//2}\pi$'  # line 316
return fr'${n}\pi/2$'  # line 318

```

**Actual outcome**

```
Traceback (most recent call last):
  File "/my-repo-path/testing.py", line 5, in <module>
    from basic_units import cm, inch
  File "/my-repo-path/basic_units.py", line 125
    subcls = type(f'TaggedValue_of_{value_class.__name__}',
                                                         ^
SyntaxError: invalid syntax
```

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: matplotlib==3.0.3 (installed using `pip3`)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2 (provided by distro)

**Comment by WeatherGod** [comment]
f-strings were introduced in python 3.6, if I remember correctly. That is
why you are getting the syntax error (you are using python 3.5).

**Comment by jklymak** [comment]
I'm going to close this.   If you still have questions, feel free to post at discourse.matplotlib.org
