### ISSUE TITLE
keyword share_all in ImageGrid class

### ISSUE THREAD

**Issue by chaochinyang** [matplotlib/matplotlib#16938]
### Bug report

**Bug summary**

The keyword share_all in ImageGrid class does not work as intended.

**Code for reproduction**

```python
from mpl_toolkits.axes_grid1 import ImageGrid
import matplotlib.pyplot as plt
from numpy.random import random

fig = plt.figure()
grid = ImageGrid(fig, 111, nrows_ncols=(2,2), share_all=False,
                 label_mode="all", axes_pad=0.5)

for ax in grid:
    ax.pcolormesh(random((100,100)))

grid[0].set_xlim(-1,1)
grid[3].set_ylim(-1,1)

plt.show()
```

**Actual outcome**

<img width="752" alt="Screen Shot 2020-03-27 at 1 29 51 PM" src="https://user-images.githubusercontent.com/11709830/77798013-516b9400-702f-11ea-9890-369864d67002.png">

**Expected outcome**

With `share_all=False`, the axes in each subplot should scale independently.  However, the axes are still shared by all subplots.

**Matplotlib version**
  * Operating system: MacOS 10.15.4
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.3
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

My matplotlib and python are provided by default anaconda3.

**Comment by anntzer** [comment]
Looks like this is overridden by share_x and share_y which are always set to True (this kind of non-orthogonal kwargs is really a pain and I think we should deprecate share_all in favor of share_x/share_y), but even forcing share_x/share_y to False, the result is not great:
![test](https://user-images.githubusercontent.com/1322974/77799703-a03c1c80-7075-11ea-9c8a-17011e0ee59e.png)

**Comment by chaochinyang** [comment]
I think it makes sense to use sharex/sharey to replace share_all, as long as they work as intended...

I see that in the development head that ImageGrid simply passes share_all to Grid.  I guess as long as ImageGrid has sharex/sharey as keyword and send them to Grid, the code should work correctly.

**Comment by chaochinyang** [comment]
Just want to prevent this bug report from becoming inactive, and hope one of the developers could pick this up.

**Comment by anntzer** [comment]
Actually looking at the code again I'm almost certain that ImageGrid is fundamentally unable to handle the case of not sharing xlims along a column or ylims along a row of axes (this comes from the use of AxesX/AxesY in _init_locators).  The best you can do is probably to use Grid (perhaps with aspect=True) instead:
```python
from mpl_toolkits.axes_grid1 import Grid
import matplotlib.pyplot as plt
from numpy.random import random

fig = plt.figure()
grid = Grid(fig, 111, nrows_ncols=(2,2),
            share_all=False, share_x=False, share_y=False,
            aspect=True,  # Optional, depends on the exact desired semantics.
            label_mode="all", axes_pad=0.5)

for ax in grid:
    ax.pcolormesh(random((100,100)))

grid[0].set_xlim(-1,1)
grid[3].set_ylim(-1,1)

plt.show()
```
Probably to be closed as "can't fix".
