### ISSUE TITLE
ConnectionPatch failure when drawing multiple connection lines

### ISSUE THREAD

**Issue by 787854818** [matplotlib/matplotlib#16956]
### Bug report

I encountered a small problem when using ConnectionPatch to connect nodes of two networks. Firstly, I draw two networks in different subplot respectively. Then I draw lines with ConnectionPatch to connect nodes from different networks. Most connecting lines are correct, but sometimes there is a problem with one line.

**Code**

```python
import matplotlib.pyplot as plt
from matplotlib.patches import ConnectionPatch
import networkx as nx


G1 = nx.petersen_graph()
G2 = nx.petersen_graph()
pos1 = nx.spring_layout(G1)
pos2 = nx.spring_layout(G2)


plt.figure(figsize=[8,4])
ax1 = plt.subplot(121)
nx.draw_networkx(G1,pos1)


ax2 = plt.subplot(122)
nx.draw_networkx(G2,pos2)


for i in range(len(pos1)):
    con = ConnectionPatch(xyA=set(pos1[i]), xyB=set(pos2[i]), coordsA=ax1.transData, coordsB=ax2.transData, arrowstyle="-", color = "green")
    ax2.add_artist(con)


plt.show()
```

In this picture, the connecting line of node pair 5 is incorrect. 

<img width="620" alt="incorrect" src="https://user-images.githubusercontent.com/40711748/77897610-7587d900-72ac-11ea-9eb6-c5297592415f.png">

**I draw the wrong connecting line separately and the result is correct**
```python
i = 5
point1 = (pos1[i][0], pos1[i][1])
point2 = (pos2[i][0], pos2[i][1])
con = ConnectionPatch(xyA=point1, xyB=point2, coordsA=ax1.transData, coordsB=ax2.transData, arrowstyle="-", color = "green")
ax2.add_artist(con)
```
<img width="622" alt="solo" src="https://user-images.githubusercontent.com/40711748/77897928-ed560380-72ac-11ea-8373-9711e610dcbe.png">

**Sometimes another node pair goes wrong, or no node pair goes wrong.**
<img width="615" alt="correct" src="https://user-images.githubusercontent.com/40711748/77896232-87687c80-72aa-11ea-819d-ca4550bd4280.png">

**Matplotlib version**

  * Operating system: win10
  * Matplotlib version: 3.1.3 (from pip)
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Other libraries: networkx 2.4

**Comment by ImportanceOfBeingErnest** [comment]
Don't use a `set`, i.e. replace `ConnectionPatch(xyA=set(pos1[i]), xyB=set(pos2[i]), ...` by  
`ConnectionPatch(xyA=pos1[i], xyB=pos2[i], ...`

**Comment by 787854818** [comment]
I see, thanks a lot!
