### ISSUE TITLE
How to solve an error of "ValueError: Key backend: Unrecognized backend string '"agg"'

### ISSUE THREAD

**Issue by YoohwanPark** [matplotlib/matplotlib#16952]
![matplotlib_error](https://user-images.githubusercontent.com/62859008/77863562-4b0f2f00-725e-11ea-94f1-7f1bf5987067.PNG)

 "ValueError: Key backend: Unrecognized backend string '"agg"': valid strings are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']"

**How to solve this error?? I can't import matplotlib! I've tried to re-install Anaconda several times and update the lasted version of matplotlib but I can find the solution.**

**Comment by WeatherGod** [comment]
Try without the quotes
