### ISSUE TITLE
A second animation overlaps first when displayed using `to_jshtml`

### ISSUE THREAD

**Issue by kpeeters** [matplotlib/matplotlib#16964]
Before I start putting together a full working example, a quick check if this is a known one or there is a workaround:

When I make two animations in a Jupyter notebook, and output them with `HTML(to_jshtml())`, the first and last frame of the first animation are overlapping the 2nd animation (all the time). Is there any way to completely clear any buffers/cache of the animation system, or some other way to avoid this?

**Comment by dopplershift** [comment]
I've not heard of this problem before, so code to reproduce would be greatly appreciated.

**Comment by tacaswell** [comment]
Are you reusing the same figure in both animations?

**Comment by kpeeters** [comment]
Ah, thanks, was re-using the same figure; using a new one for each animation works fine. Should have thought about that myself...
