### ISSUE TITLE
Thin line color distortion on large scale

### ISSUE THREAD

**Issue by VasylVaskivskyi** [matplotlib/matplotlib#16976]
### Bug report

Distortion of color in thin lines (1px), when viewed on a large scale. On small scale lines look as they should.

**Code for reproduction**
Image with labels on my google drive
https://drive.google.com/drive/u/0/folders/18ldsmKxdk8Ha8m-Hiyw-fWqQlW1SZXqJ
It is multipage tiff file.

```python
import matplotlib
import numpy as np
import colorsys
import tifffile as tif
import matplotlib.pyplot as plt

def random_label_cmap(n=2**16):

    h,l,s = np.random.uniform(0,1,n), 0.4 + np.random.uniform(0,0.6,n), 0.2 + np.random.uniform(0,0.8,n)
    cols = np.stack([colorsys.hls_to_rgb(_h,_l,_s) for _h,_l,_s in zip(h,l,s)],axis=0)
    cols[0] = 0
    return matplotlib.colors.ListedColormap(cols)


img_path = 'labels.tif'
labels = tif.imread(img_path)

lbl_cmap = random_label_cmap()

plt.axis('off')

plt.imshow(labels[3, :, :], cmap=lbl_cmap)

out_path = 'labels_color.tif'
plt.savefig(out_path, dpi=300, bbox_inches='tight', pad_inches=0, quality=100)

```

**Actual outcome**
Here is the same image but on different magnifications.

![actual](https://user-images.githubusercontent.com/35797200/78011297-4ff5e080-733b-11ea-888d-78c0ee1258a2.jpg)

![actual_1](https://user-images.githubusercontent.com/35797200/78011337-5c7a3900-733b-11ea-8bac-da6b48740d2a.jpg)

![actual_2](https://user-images.githubusercontent.com/35797200/78011359-6439dd80-733b-11ea-9ad2-80a25cbe0b02.jpg)

**Expected outcome**

![expected](https://user-images.githubusercontent.com/35797200/78011265-41a7c480-733b-11ea-82f4-a880afac3955.jpg)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.2.1
  * Matplotlib backend: TkAgg
  * Python version: 3.7.7
  * Other libraries: numpy 1.18.2, tifffile 2020.2.16

Installed with pip

**Comment by anntzer** [comment]
This arises from the switch to defaulting to `interpolation="antialiased"`.  You can set `interpolation="none"` to get rid of the artefacts; I guess this could be better documented?  attn @jklymak.

**Comment by jklymak** [comment]
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html  Folks have to expect some sort of artifact if their image has data that is subpixel.  I don't really see an action item here.
