### ISSUE TITLE
New improvements for the websites(GSOC)

### ISSUE THREAD

**Issue by marcelodelaquintana** [matplotlib/matplotlib#16984]
**Some problems were identified:**

- There is not easy way to change from documentations version ()
- New Features are not that easy discoverable and would be easy if you could actually see them in the website. 
- Some small problems detected like (accessibility, performance) that could be irmproved

**The idea is to improve the following fields**

- Improve the UX when displaying new features we would like to display the features like having a global version documentation dropdown in the toolbar. 
- Improve the search command adding more filters, paginating and improving the speed (elastic search or some related) 

- Improving accessibility making it more accessible to users. 

**Resources:**

- Ligthouse (https://developers.google.com/web/tools/lighthouse)
- https://discourse.matplotlib.org/t/matplotlib-website-feedback/20648

**Comment by story645** [comment]
Hi, Marcelo, we're sorry but the GSOC application window just closed so this can't be considered as a proposal this year. Can you add some concrete suggestions though that we could consider turning into actionable issues?

**Comment by timhoffm** [comment]
@story645 wouldn‘t these topics more suitable for GSOD anyway?

**Comment by story645** [comment]
@timhoffm yup!

**Comment by SidharthBansal** [comment]
Has the Google Season of Docs announced this year?

**Comment by story645** [comment]
Yes, but we haven't decided yet if we'll participate.

**Comment by SidharthBansal** [comment]
That's great news!

**Comment by SidharthBansal** [comment]
I am happy we have GSoD announced this year too. :-)

**Comment by tacaswell** [comment]
We have also previously gotten the feedback that doc related work is out of scope for GSOC.

**Comment by QuLogic** [comment]
> * There is not easy way to change from documentations version ()

The pydata-sphinx-theme has a version selector now.

> * New Features are not that easy discoverable and would be easy if you could actually see them in the website.

We have started tagging things with `.. versionadded`, and the release notes have an overview of all new features.

> * Some small problems detected like (accessibility, performance) that could be irmproved

This is not particularly specific.

I think we can close this as too broad, mostly complete, and/or non-actionable any more.
