### ISSUE TITLE
pyplot.rgrids don't do anything

### ISSUE THREAD

**Issue by Toussaic** [matplotlib/matplotlib#16982]
Hello,

The function pyplot.rgrids doesn't seem to do anything.
I tried in an ipython console with the Qt5 backend and in a notebook.

```
import matplotlib.pyplot as plt
%matplotlib qt5
# Or in a notebook
# %matplotlib notebook

# Data
import random
import math
theta = [2*i*math.pi/360 for i in range(0, 360)]
r = [2 + random.gauss(0, 0.3) for i in range(0,360)]

# Plotting
plt.subplots(1, 1, subplot_kw={'projection':'polar'})
plt.plot(theta, r)
plt.rgrids(radii=(0.5, 2), labels=("low", "mean"))
```

On the other hand, when using axes.set_rgrids, it works fine :
```
# Instead of plt.rgrids
plt.gca().set_rgrids(radii=(0.5, 2), labels=("low", "mean"))
```
I tried using pyplot.draw() after, or defining the rgrids before plotting but it doesn't change anything.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend : Qt5 or notebook
  * Python version: 3.8.1
  * Jupyter version : 6.0.3
  * Installed via conda

[package_list.txt](https://github.com/matplotlib/matplotlib/files/4410003/package_list.txt)

**Comment by ImportanceOfBeingErnest** [comment]
The key is that the `radii` is not a named argument for [`plt.rgrids`](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.rgrids.html), the signature is `pyplot.rgrids(*args, **kwargs)`. Hence

    plt.rgrids((0.5, 2), labels=("low", "mean"))

would work fine, while

    plt.rgrids(radii=(0.5, 2), labels=("low", "mean"))

doesn't.
For [`PolarAxes.set_rgrids`](https://matplotlib.org/3.1.0/api/projections_api.html#matplotlib.projections.polar.PolarAxes.set_rgrids) the signature has the named arguments in it, `set_rgrids(self, radii, labels=None, angle=None, fmt=None, **kwargs)` therefore it work fine. 

While this is correctly documented, this subtlety is at the very least confusing.

**Comment by Toussaic** [comment]
Yes, confusing indeed, but understanding. I missed the difference between the two functions.
Thanks!
