### ISSUE TITLE
Underscore character does not exist for cmr10 font

### ISSUE THREAD

**Issue by jrwrigh** [matplotlib/matplotlib#16995]
### Bug report

The bundled font `cmr10` (and it's associated family) do not contain the underscore character. Instead, the unicode character for the underscore (according to [this website](https://unicode-search.net/unicode-namesearch.pl?term=UNDERSCORE) anyways) is actually mappted to the overdot.

See [this StackOverflow](https://stackoverflow.com/questions/60974480/underscore-in-label-does-not-render/60975058#60975058) for details, but I'll repeat here.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
plt.rcParams.update({
            'font.family': 'serif',
            'font.serif': 'cmr10',
})

variable = range(5)
plt.plot(variable, variable, label='test_underscore')
plt.plot(variable, variable, label='escape\_underscore')
plt.plot(variable, variable, label=r'rawtest_underscore')
plt.plot(variable, variable, label=r'rawescape\_underscore')
_=plt.legend()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/20801821/78159073-4b92fb80-73ff-11ea-82d3-32ca7606226b.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/20801821/78158976-2c946980-73ff-11ea-9f80-c7d7011a091e.png)

**Matplotlib version**

  * Operating system: Manjaro 19.0.2
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6

**Other**
`cmr10` loaded into FontForge shows that:
A) the underscore character doesn't exist
B) the normal underscore character (`005f`) is replaced by the overdot
![image](https://user-images.githubusercontent.com/20801821/78159691-22bf3600-7400-11ea-99a4-cff311d23636.png)

**Comment by anntzer** [comment]
That's because there's, well, no underscore in the classic OT1 encoding (https://texfaq.org/FAQ-underscore).  Consider e.g. downloading and using lmroman10-regular.ttf.

**Comment by jrwrigh** [comment]
Huh. The more you know I guess. Thanks for the quick response!
