### ISSUE TITLE
matplotlib has problem with leap years

### ISSUE THREAD

**Issue by Kadelka** [matplotlib/matplotlib#17009]
The function plot() in matplotlib, version 3.2.1, has a problem with the date 2020-02-29 in this leap year. The plots are ugly if the day 2020-02-29 is in the range of the x-axis.
Here a simple program running with 
ipython --pylab
```
import datetime as dt
y = range(20)
datum = [dt.date(2020,3,1)+dt.timedelta(x) for x in range(20)] 
plot(datum,y)
```

looks fine but with
```datum = [dt.date(2020,2,29)+dt.timedelta(x) for x in range(20)] ```
the plot looks ugly

Similarly for 2020-02-28, and other date near 2020-02-29.
There is no problem for the year 2019.

A similar problem holds with pandas.DataFrame.plot()

**Comment by QuLogic** [comment]
>  the plot looks ugly

Ugliness is subjective. Are the ticks wrong? Is the margin incorrect? Is the line broken? Please define what you mean.

**Comment by Kadelka** [comment]
Without the leap day the ticks are equidistant. With the leap day an additional tick (for the leap day) is added, if the time series has not too many values. Consequence: The description overlap (I don't know the correct term).

**Comment by timhoffm** [comment]
@Kadelka Can you please post a screenshot? I think that would clarify the issue.

**Comment by Kadelka** [comment]
Figure1.pdf with problems (starting with date 2020-02-24) and Figure2.pdf without problems (starting with date 2020-03-01).
[Figure_1.pdf](https://github.com/matplotlib/matplotlib/files/4426212/Figure_1.pdf)
[Figure_2.pdf](https://github.com/matplotlib/matplotlib/files/4426213/Figure_2.pdf)

**Comment by Kadelka** [comment]
I have the same problems with anaconda3. Here the details of my ipython installation:
Python 3.7.7 (default, Mar 23 2020, 22:36:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: Qt5Agg

**Comment by Kadelka** [comment]
My standard installation opens with:
Python 3.8.2 (default, Feb 26 2020, 18:13:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: Qt5Agg

**Comment by ImportanceOfBeingErnest** [comment]
Note that this has nothing to do with leap years. It will occur everytime you plot across a month's end which has an odd number of days.

**Comment by Kadelka** [comment]
O.K. I understand. But is this a feature or a bug?

**Comment by ImportanceOfBeingErnest** [comment]
How would you like it to look instead? Should there be a 3-days gap?

Note that matplotlib has a great bunch of options for ticking and formatting labels. Possibly what you're looking for is 

```
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.units as munits

converter = mdates.ConciseDateConverter()
munits.registry[datetime.date] = converter
munits.registry[datetime.datetime] = converter

y = range(20)
datum = [datetime.date(2020,3,20)+datetime.timedelta(x) for x in range(20)] 

plt.plot(datum,y)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/78353733-da904700-75aa-11ea-9ac5-c3054c94d811.png)

**Comment by jklymak** [comment]
Note also that for matplotlib 3 we changed the AutoDateLocator to have `interval_multiples=True` by default.  That will *always* put a tick at 1.  Its possible this logic should be changed to *never* put a tick at 28 or 29, but it gets a bit complicated...

With that in mind, you can also try.

```python
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

y = range(20)
datum = [datetime.date(2020,2,20)+datetime.timedelta(x) for x in range(20)]

plt.plot(datum,y)
locator = mdates.AutoDateLocator(interval_multiples=False)

plt.gca().xaxis.set_major_locator(locator)
plt.show()
```

https://matplotlib.org/api/dates_api.html#matplotlib.dates.AutoDateLocator

As an aside, I find the grammar for getting/setting the major locator a major PITA to remember.
