### ISSUE TITLE
Broken "Text Rotation Relative To Line" example 

### ISSUE THREAD

**Issue by asongtoruin** [matplotlib/matplotlib#17005]
The "Text Rotation Relative To Line" [example](https://matplotlib.org/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html) appears to be broken in the current docs:

![Misaligned rotated text](https://user-images.githubusercontent.com/20771863/78273828-43be7e80-7507-11ea-8bca-29b465a9efbd.png)

Compared to older versions of the module:

![Correctly rotated text](https://user-images.githubusercontent.com/20771863/78273979-723c5980-7507-11ea-89d1-d80245c501da.png)

Checking back through older versions of the documentation, it looks as though this broke in [v3.2.0](https://matplotlib.org/3.2.0/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html) as it looks to have still been fine in [v3.1.3](https://matplotlib.org/3.1.3/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html)

**Comment by anntzer** [comment]
This can be fixed e.g. by adding a call to `fig.canvas.draw()` before computing trans_angle, but even the "old" behavior was pretty brittle -- for example, if you interactively change the figure size, the text goes out of alignment.  The correct solution (which is robust against figure resizes) is the one implemented in matplotlib.contour.ClabelText; right now a quick and dirty solution is to just write `th1.__class__ = mpl.contour.ClabelText` (ugh!) but I think it would be reasonable to move that feature (e.g. as a `rotation_transform=ax.transData` property) to the main Text class.

**Comment by QuLogic** [comment]
Fixed by #15532.
