### ISSUE TITLE
Request: provide a contextmanager for ioff or allow plt.figure(draw_on_create=False)

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#17013]
# Issue:
Often when I'm using the widget backend in jupyterlab and want to do something like define a small layout of ipywidgets and plots I find myself using this pattern:
```python
plt.ioff()
fig = plt.figure()
plt.ion()
....
widgets.VBox([slider1,slider2,fig.canvas])
```
`ioff` is necessary because without it the below snippet will result in two identical plots showing up with the slider between them
```python
%matplotlib widget
import ipywidgets as widgets
import numpy as np
import matplotlib.pyplot as plt
phase = widgets.FloatSlider(value=0, min=0, max=np.pi)
x = np.linspace(0, 2*np.pi)

fig = plt.figure()
ax = fig.gca()

line = ax.plot(x, np.cos(x))[0]
def update(change):
    line.set_data(x, np.cos(x + phase.value))
    fig.canvas.draw_idle()
phase.observe(update,names='value')
widgets.VBox([phase,fig.canvas])
```
![image](https://user-images.githubusercontent.com/10111092/78321481-163ef880-753a-11ea-99a5-b633e3dd2b9c.png)

I then always call `ion` again because I prefer it for most of what I do in a  notebook.

This is annoying because it requires two extra lines everytime I want to do this, and it doesn't seem necessary to constantly be calling `(un)install_repl_displayhook` in `ion` and `ioff`
I understand that I could use the object oriented interface to make my own figures using `Figur e` but this would be somewhat signifcant change from how I naturally use matplotlib in the notebook and would require learning more about a non-trivial interface.

# Potential solutions
## 1 - kwarg:
Add a kwarg to `plt.figure`. Something like `draw_on_create` or `draw` or `draw_immediately` e.g.:
```diff
diff --git a/lib/matplotlib/pyplot.py b/lib/matplotlib/pyplot.py
index a097296dc..0f8d54380 100644
--- a/lib/matplotlib/pyplot.py
+++ b/lib/matplotlib/pyplot.py
@@ -491,6 +491,7 @@ def figure(num=None,  # autoincrement if None, else integer from 1-N
            frameon=True,
            FigureClass=Figure,
            clear=False,
+           draw=True,
            **kwargs
            ):
     """
@@ -613,7 +614,8 @@ def figure(num=None,  # autoincrement if None, else integer from 1-N
         # to be called in plotting commands to make the figure call show
         # still work.  There is probably a better way to do this in the
         # FigureManager base class.
-        draw_if_interactive()
+        if draw:
+            draw_if_interactive()
 
         if _INSTALL_FIG_OBSERVER:
             fig.stale_callback = _auto_draw_if_interactive
```

## 2 - contextmanager: 
This one I can admittedly have in my own library, but would be nice to have provided by matplotlib.
There could be either be a context manager separate from `ion/ioff` that toggles `matplotlib.interactive`. Or `plt.ioff` could be transformed in a contextmanager that can still be called like so:
```python
class ioff:
    def __call__(self):
        matplotlib.interactive(False)
        uninstall_repl_displayhook()
        
    def __enter__(self):
        self.call()
        
    def __exit__(self):
        ion()
```
## 3 - remove specific figures from interactive mode:
Maybe certain figures could be prevented from being redrawn in interactive mode, something like:
```python
plt.figure(is_interactive=False)
```
which would then exclude that figure from being redrawn without an explicit call to `fig.canvas.draw`
This may already be possible using the Object Oriented interface but for me at least as noted I find digging that can be confusing.

**Comment by tacaswell** [comment]
I am not a fan of option 1, it is adding a toggle to a toggle which is a sign we should take a step back and reconsider ;)

I am a fan of option 2, I think it would be a generally useful thing independent of back end.

I recall that @anntzer was recently doing some work to "donate" figures to the state machine, I wonder if we need a way to also "orphan" a `Figure` from the state machine without destroying it (which is option 3, but implemented a bit differently).

**Comment by efiring** [comment]
I would like the context manager option for the case where I am making an html animation in a notebook, using the notebook backend.

**Comment by ianhi** [comment]
> adding a toggle to a toggle which is a sign we should take a step back and reconsider ;)

Good point 😂

A plus for the context manager approach is that it seems pretty easy to implement. I implemented the below diff and ran the tests and got the same results as the master branch, so I don't think that this breaks anything:
```diff
diff --git a/lib/matplotlib/pyplot.py b/lib/matplotlib/pyplot.py
index fcfb4b3f6..3b32a2261 100644
--- a/lib/matplotlib/pyplot.py
+++ b/lib/matplotlib/pyplot.py
@@ -333,16 +333,36 @@ def isinteractive():
     return matplotlib.is_interactive()
 
 
-def ioff():
-    """Turn the interactive mode off."""
-    matplotlib.interactive(False)
-    uninstall_repl_displayhook()
+class ion_class():
+    def __call__(self):
+        """Turn the interactive mode off."""
+        matplotlib.interactive(True)
+        install_repl_displayhook()
+ 
+    def __enter__(self):
+        self.call()
+
+    def __exit__(self):
+        matplotlib.interactive(False)
+        uninstall_repl_displayhook()
+
+class ioff_class():
+    def __call__(self):
+        """Turn the interactive mode on."""
+        matplotlib.interactive(False)
+        uninstall_repl_displayhook()
+
+    def __enter__(self):
+        self.call()
+
+    def __exit__(self):
+        matplotlib.interactive(True)
+        install_repl_displayhook()
+
+ioff = ioff_class()
+ion = ion_class()
 
 
-def ion():
-    """Turn the interactive mode on."""
-    matplotlib.interactive(True)
-    install_repl_displayhook()
```

**Comment by tacaswell** [comment]
Could you open a PR with that patch?

I am not sure if we want to spell it

```python

with plt.ion:
    ...

```

or

```python
with plt.ion():
    ...
```

:+1: to `plt.ion()` and `plt.ioff()` still working as expected (other wise this is a non-starter) and to adding as little extra API as needed.

We probably should cache the current state in `__enter__` and then set it back to that in `__exit__` as

```python
plt.ion()
with plt.ion():
    ...
# I expect to still be in interactive mode
assert plt.isinteractive()
```

**Comment by tacaswell** [comment]
I'm also curious what the 33 failing tests are.

**Comment by ianhi** [comment]
For `with plt.ion:` vs `with plt.ion()` I think the former is much simpler to implement.  Beyond that if we use `plt.ion()` then plt.ion() would need to generate and return an object, which seems like an api change as currently `plt.ion()` returns None. 

> We probably should cache the current state in __enter__ and then set it back to that in __exit__

Good call. Does checking `matplotlib.isinteractive` give information about the repl hook? Or does that need to be queried separately?

As for tests I'm a bit confused, I keep managing to get different results for environments (fresh conda envs) that I expect to be the same. I have also been using pytest-parallell and or pytest-xdist which may be playing a role in a few of the tests. I'll investigate this further.

Is there a canonical conda envinroment or other virtual environment for running the tests in?
