### ISSUE TITLE
`get_major_ticks` docs missing return type

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#17015]
[axis.Axis.get_major_ticks](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axis.Axis.get_major_ticks.html?highlight=ax%20get_major_ticks#matplotlib.axis.Axis.get_major_ticks) should be updated to list its return type, which is a list of [Tick objects](https://matplotlib.org/devdocs/api/axis_api.html#matplotlib.axis.Tick) and cross reference to the Tick object documentation. 

The motivation for this fix is examples like [dollar tick](https://matplotlib.org/gallery/pyplots/dollar_ticks.html#sphx-glr-gallery-pyplots-dollar-ticks-py) where it is unclear what methods are on the tick objects.

**Comment by vishalBindal** [comment]
Hello @story645, I'm interested to contribute here.
