### ISSUE TITLE
DOC: Tutorial/Sample plots should use same fig/axis creation method

### ISSUE THREAD

**Issue by demisjohn** [matplotlib/matplotlib#17023]
### Bug report

The "sample plots" in the tutorial sections should all use the same method of generating a new plotting axis, unless the tutorial is about different methods for achieving this.

On this page:
https://matplotlib.org/3.2.1/tutorials/introductory/sample_plots.html
_Most_ of the MPL examples now use `plt.subplots()`, EXCEPT for the following: 

- <s>"Surface3d" (`gca`), </s>
- "Multiple Subplots" (`subplot`), 
- <s>"streamplot" (`fig.add_subplots`), </s>
- "Polar Plots" (`subplot`), 
- <s>XKCD (`fig.add_axes`). </s>

**Expected outcome**

If it makes sense, I think all of these should be converted to use a single style of figure/axis creation.  Possibly also applicable to other tutorial pages and examples in the documentation pages.

@tacaswell suggested that `plt.subplots(...)` is the preferred way to do this, so the above could be unified in using that method.

([Here is the SE question prompting this bug report](https://stackoverflow.com/questions/27221009/fig-gca-vs-fig-add-subplot))

**Comment by timhoffm** [comment]
Mostly :+1:.

- "streamplot" uses a more complex layout with a gridspec, which cannot be created via `plt.subplots()`. It's debatable if one needs that complex layout, but a change would not be a one-liner there.
- XKCD uses special positioning of the Axes. This can alternatively achieved via `plt.subplots( subplot_kwdict=...)` or an extra `fig.subplots_adjust` call. IMHO that is more complicated than `fig.add_axes`.

@demisjohn Wanna make a pull request?

**Comment by asafmaman101** [comment]
Hi, I would like to take that one. Where can I find the website source code?

**Comment by timhoffm** [comment]
This part is generated from `tutorial/introductory/sample_plots.py`.

**Comment by asafmaman101** [comment]
Hi, thanks. I guess I'm missing something, the `tutorial/introductory/sample_plots.py` include mostly comments, does the website generet its content from the comments? Also, the comments only include links for the pages with the examples but I cannot find those page's source in the project.

Is it somewhere else?

**Comment by timhoffm** [comment]
The page is generated from the py files using Sphinx gallery https://sphinx-gallery.github.io/stable/syntax.html.

**Comment by asafmaman101** [comment]
Hi, I sent PR #17340 for this issue.
It didn't pass the codecov test, I'm trying to figure out why, I simply changed the files releated to the plots above, any help? Thanks.
