### ISSUE TITLE
ImportError: cannot import name 'rcParams' from 'pylab' 

### ISSUE THREAD

**Issue by shanethomas1029** [matplotlib/matplotlib#17041]
**Python 3.7
OS: Windows 10**

**Error** : 
Traceback (most recent call last):
  File "C:\Desktop\Signature Project\9 Signature-Verification-master\finalwork_axisbank.py", line 14, in <module>
    from pylab import rcParams
ImportError: cannot import name 'rcParams' from 'pylab' (C:\Users\shane\AppData\Local\Programs\Python\Python37\lib\site-packages\pylab\__init__.py)

**Import Statements that I have Given:**

from pylab import*
from os import listdir
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from skimage import measure            
from scipy.ndimage import convolve
from sklearn import linear_model, datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.neural_network import BernoulliRBM
from sklearn.pipeline import Pipeline
from sklearn.base import clone
import cv2
from pylab import rcParams
from scipy.misc import imread
import seaborn as sns; 

Any solution?]

**Comment by timhoffm** [comment]
Which version of matplotlib are you using?

**Comment by timhoffm** [comment]
Please check why you have `lib\site-packages\pylab\_init_.py`. This is not from matplotlib and probably shadows the import. The matplotlib pylab module should be at `lib\site-packages\pylab.py`.
