### ISSUE TITLE
Support 'markerfacecoloralt' in prop_cycle

### ISSUE THREAD

**Issue by Z4uit** [matplotlib/matplotlib#17055]
### Bug report

**Bug summary**

When using the cycler to style a series of plots, one cannot use markerfacecoloralt because it is not recognised as artist. Markerfacecolor and color are recognised.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
from cycler import cycler

x = np.linspace(0,1,10)
B = [0,1,2,3]
colors = ['k', 'tab:gray', 'tab:red', 'tab:blue']

# Desired workflow
fig1,ax1 = plt.subplots()
ax1.set_prop_cycle(cycler('c',colors)+
                   cycler('markerfacecolor',colors)+
                   cycler('markerfacecoloralt',colors[::-1]))
for b in B:
    ax1.plot(x,x+b,'-o',markersize=7,fillstyle='top')
```

**Actual outcome**

```
ValueError: Unknown artist properties: {'markerfacecoloralt'}
```

**Expected outcome**
![gitHub](https://user-images.githubusercontent.com/63285054/78651868-39aece00-78c1-11ea-9410-ede1d0a16640.png)

```python
# Workaround to get above plot
fig2,ax2 = plt.subplots()
ax2.set_prop_cycle(cycler('c',colors)+
                   cycler('markerfacecolor',colors))
for b,cAlt in zip(B,colors[::-1]):
    ax2.plot(x,x+b,'-o',markersize=7,markerfacecoloralt=cAlt,fillstyle='top')
```

**Matplotlib version**

  * Operating system: macOS Catalina 10.15.3
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.5

**Comment by timhoffm** [comment]
This is essentially duplicate of #10790.

**Comment by Z4uit** [comment]
Is prop_cycle taking its valid artists from rcParams? In that case, sorry, I did not know and it is a duplicate indeed.

**Comment by timhoffm** [comment]
Not directly valid artists. But cycler and rcParams share functionality for parameter validation and both are implemented in `rcsetup.py`. It would be natural to solve both issues together.

I've removed the duplicate because one still needs to be aware of both features to solve them together.
