### ISSUE TITLE
Segmentation fault with macosx backend

### ISSUE THREAD

**Issue by cbrnr** [matplotlib/matplotlib#17061]
The following short example produces a segmentation fault when using the default `macosx` backend (of course on macOS):

```python
from functools import partial
import matplotlib.pyplot as plt


def close_event(event, fig):
    plt.close(fig)


fig, ax = plt.subplots()
close_callback = partial(close_event, fig=fig)
fig.canvas.mpl_connect("close_event", close_callback)
plt.show(block=False)  # block=True works
```

To reproduce, run the script with `python example.py`. This produces the following segfault:

```
[1]    62624 segmentation fault  python example.py
```

Running the code in interactive mode works. Also, `block=True` does not produce the segfault.

This script also runs normally with the `PyQt5` backend, e.g. `MPLBACKEND=qt5agg python example.py`, so it seems like this is an issue with the `macosx` backend.
  * Operating system: macOS 10.15.4
  * Matplotlib version: 3.2.1
  * Matplotlib backend: macosx
  * Python version: 3.8.2

I can reproduce this problem with Homebrew Python as well as Anaconda.

**Comment by QuLogic** [comment]
Can you get a backtrace?

**Comment by tacaswell** [comment]
See https://docs.python.org/3/library/faulthandler.html for how to get a good backtrace.

My guess is that we are not being careful enough not reusing dead objects in the OSX backend.  My guess is that the double close is trying to tear down a already torn down objectivec object which leads to a null deference which leads to segfault?

I wonder if https://github.com/matplotlib/matplotlib/pull/16942 has already fixed this, can you try installing from master @cbrnr ?

**Comment by jklymak** [comment]
On master:

```
Fatal Python error: Segmentation fault

Current thread 0x000000010f54adc0 (most recent call first):
  File "/Users/jklymak/matplotlib/lib/matplotlib/_pylab_helpers.py", line 86 in destroy_all
[2]    87588 segmentation fault  python3 -q -X faulthandler testmacosx.py
```

**Comment by cbrnr** [comment]
@jklymak beat me to it, the traceback points to the same line for me (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_pylab_helpers.py#L86).

**Comment by anntzer** [comment]
Can't test this, but first thing I'd consider is adding a check whether `canvas` is NULL at https://github.com/matplotlib/matplotlib/blob/master/src/_macosx.m#L1730 -- possibly https://github.com/matplotlib/matplotlib/blob/master/src/_macosx.m#L349 has already been called at that point.

**Comment by cbrnr** [comment]
I changed this function to:

```objective-c
- (void)windowWillClose:(NSNotification*)notification
{
    PyGILState_STATE gstate;
    PyObject* result;

    gstate = PyGILState_Ensure();
    if(canvas != NULL)
    {
        result = PyObject_CallMethod(canvas, "close_event", "");
        if(result)
            Py_DECREF(result);
        else
            PyErr_Print();
    }
    PyGILState_Release(gstate);
}
```

I still get the segfault though.

**Comment by anntzer** [comment]
Well, guessed wrong, then :)

**Comment by cbrnr** [comment]
Not sure why there are these two very similar functions:

https://github.com/matplotlib/matplotlib/blob/a86d4fb84d5dfbd4ab53ba210976d22500186749/src/_macosx.m#L728-L734

https://github.com/matplotlib/matplotlib/blob/a86d4fb84d5dfbd4ab53ba210976d22500186749/src/_macosx.m#L750-L762

If I comment out the lines related to the `pool` in `FigureManager_destroy` (i.e. lines 756 and 758), the example works. However, I'm not sure if this doesn't leave deleted windows lying around because I'm absolutely not familiar with this codebase.

**Comment by tacaswell** [comment]
@cbrnr can you put in a (draft) PR with your changes?

**Comment by cbrnr** [comment]
Yes, will do.

**Comment by cbrnr** [comment]
@tacaswell see #17084.
