### ISSUE TITLE
documentation of animation contains non-working code example

### ISSUE THREAD

**Issue by grg2rsr** [matplotlib/matplotlib#17066]
As It reads here on the [official docs](https://matplotlib.org/3.1.1/api/animation_api.html) as an example on how to save an animation as a video file

```
moviewriter = MovieWriter(...)
moviewriter.setup(fig=fig, 'my_movie.ext', dpi=100)
for j in range(n):
    update_figure(n)
    moviewriter.grab_frame()
moviewriter.finish()
```
this code snippet contains two bugs, first there is `moviewriter.setup(fig=fig, 'my_movie.ext', dpi=100)` which should not contain `fig=` as it will throw a non-keyword argument after a keyword argument error, and then it should be `update_figure(j)` instead of `n` which also won't run of course ... 

just stumbled over this and thought I'd post it briefly. No idea if this is the correct way or place to report this.

**Comment by tacaswell** [comment]
Thanks for reporting this @grg2rsr .  That code snippet is meant to be illustrative of the life cycle of the writers, not something you can copy-paste, but it should not contain syntax errors!

Would you mind also opening a PR clarifying that and fixing the syntax?

**Comment by QuLogic** [comment]
Fixed by the linked PR.
