### ISSUE TITLE
How to engage more contributors to matplotlib

### ISSUE THREAD

**Issue by SidharthBansal** [matplotlib/matplotlib#17060]
@story645 asked my opinion on how to increase the long term contributors count at mpl at gitter. Thanks for the question.
These are few things which can help mpl:
1. *Welcomebot*: Usage of the welcome bot to encourage people on their first PR submission, first issue submission, first pr merge, etc. The welcome bot has extra friendly messages to encourage contributors to work at organisations. Emoticon usage can also be incorporated for more friendliness.
2. *Detailed and Quick Installation Guidelines*: Newcomers faced a lot of problem by scrolling between pages for installation. So, my suggestion would be the inclusion of one page of guideline including installation commands for software including sphinx, matplotlib, conda/venv etc installation. Preferable to give troubleshooting link there as well. I know there are problems with different OS etc. But that can be discussed
3. *More and self-contained first-timer issue*: Most of the first-timer issue miss code links, newcomers don't know how to search for specific features. So, including them will help contributors to commit. Issues should contain proposed solutions too. Currently most issues are already taken up and are fixed.
4. *Prefer friendliness over professionalism initially to attract contributors*: Imagine a person who is new to organisation and has no prior experience in the tools used at the organisation. It is exceeding difficult to contribute. Usage of technical jargons makes their life much more problematic. So, motivating folks help. :-)

Thanks

**Comment by story645** [comment]
Thanks for posting it in one place, but like said mentioned on gitter, I think this conversation would be better suited for https://discourse.matplotlib.org/c/community 

Also can you please give constructive suggestions that we can spin off into PRs? Do we need to update documentation, reviewer guidelines, the readme? We're happy to adopt these suggestions but help on how would be appreciated.

**Comment by SidharthBansal** [comment]
Moved to https://discourse.matplotlib.org/t/how-to-engage-more-contributors-to-matplotlib/21059
