### ISSUE TITLE
Installation error downloading jquery on python3 on Ubuntu

### ISSUE THREAD

**Issue by pySRURGS** [matplotlib/matplotlib#17075]
### Bug report

Syntax error when downloading/installing jquery-ui

I am trying to install some software that depends on Matplotlib. When I run the installation script, matplotlib installation throws this error.

**Code for reproduction**

```pip3 install matplotlib --user````

**Actual outcome**

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y0fnsonx/matplotlib/setup.py", line 139
        raise IOError(f"Failed to download jquery-ui.  Please download "
                                                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
```

**Matplotlib version**

Ubuntu 16.04 (Windows Subsystem for Linux)
Matplotlib 3.2.1
Python version 3.7 

Installing matplotlib using ```sudo apt-get install python3-matplotlib``` works fine though.

**Comment by QuLogic** [comment]
>  Python version 3.7

That cannot be true, because the syntax error is an f-string, which are available since 3.6. Please double-check that `pip3` is running the Python you think it's running.

**Comment by pySRURGS** [comment]
You are correct. My pip was actually pointing to python3.5.

**Comment by QuLogic** [comment]
We should remove this and error out better.

**Comment by yingdi11** [comment]
Running in anaconda environment in windows. I am new to python. Not sure what I did wrong.


(base) C:\Users\DiYing>python --version
Python 3.7.6

(base) C:\Users\DiYing>pip3 install C:\Users\DiYing\Downloads\imageai-2.1.5-py3-none-any.whl
Processing c:\users\diying\downloads\imageai-2.1.5-py3-none-any.whl
Collecting pillow (from imageai==2.1.5)
  Using cached https://files.pythonhosted.org/packages/d1/89/ab37df755c493ddf26ad047c29565b7640c0e1b78f1013ef47fe9d310bdf/Pillow-7.1.1-cp35-cp35m-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\diying\appdata\local\programs\python\python35\lib\site-packages (from imageai==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): scipy in c:\users\diying\appdata\local\programs\python\python35\lib\site-packages (from imageai==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): h5py in c:\users\diying\appdata\local\programs\python\python35\lib\site-packages (from imageai==2.1.5)
Collecting matplotlib (from imageai==2.1.5)
  Using cached https://files.pythonhosted.org/packages/4a/30/eb8e7dd8e3609f05c6920fa82f189302c832e5a0f6667aa96f952056bc0c/matplotlib-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DiYing\AppData\Local\Temp\pip-build-oxpnig03\matplotlib\setup.py", line 139
        raise IOError(f"Failed to download jquery-ui.  Please download "
                                                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------

**Comment by QuLogic** [comment]
> (base) C:\Users\DiYing>python --version
> Python 3.7.6
> 
> (base) C:\Users\DiYing>pip3 install C:\Users\DiYing\Downloads\imageai-2.1.5-py3-none-any.whl
> Processing c:\users\diying\downloads\imageai-2.1.5-py3-none-any.whl
> Collecting pillow (from imageai==2.1.5)
> ...
> c:\users\diying\appdata\local\programs\python\python35\lib\site-packages

Your `pip3` is for a different Python.

**Comment by yingdi11** [comment]
You are right. should I use pip instead of pip3?

**Comment by pySRURGS** [comment]
> You are right. should I use pip instead of pip3?

Well, your pip probably points to python 2. You should find the pip binary that is related to your python 3.7. Helping you with that is probably beyond the scope of this issue.
