### ISSUE TITLE
icks

### ISSUE THREAD

**Issue by TheYadda** [matplotlib/matplotlib#17087]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Closing as this looks like an accident...

**Comment by TheYadda** [comment]
Yeah, sorry, I was working on a bot that used matplotlib and somehow accidentally posted a bug report while reading documentation.
