### ISSUE TITLE
Is matplotlib is compatible to play GIF ?

### ISSUE THREAD

**Issue by Eshan-Agarwal** [matplotlib/matplotlib#17083]
I have some GIF images and I am trying to play them using `matplotlib`. Is `matplotlib `supports play GIF file ?

code I am trying is : 

```py
import matplotlib.pyplot as plt
plt.imshow('sample.gif', cmap='gray')
```
Gives error:

> TypeError: Image data of dtype <U10 cannot be converted to float

**Comment by WeatherGod** [comment]
No, I think you'd want to use Pillow for that.

**Comment by Eshan-Agarwal** [comment]
Thanks for replying can you please provide some resource , I tried pillow but it not working

**Comment by timhoffm** [comment]
Matplotlib is not primarily an image viewer, in particular not for animated images. While I think one could get that to work using animations, it‘s a tedious solution. I would only recommend that if you need to combine the gif with other matplotlib functionality.

Depending on your needs pyqt might be a better choice, e.g. https://gist.github.com/Svenito/4000025
