### ISSUE TITLE
Got TypeError: 'MovieWriterRegistry' object is not an iterator

### ISSUE THREAD

**Issue by Eshan-Agarwal** [matplotlib/matplotlib#17097]
I am generating gif using `ArtistAnimation` please see below code, video is numpy.ndarray of shape (frame,height,width,channel) ie, (20,64,64,1) and got error

```py
animation = anim.ArtistAnimation(fig,list(video))
animation.save('sample.gif', writer='imagemagick', fps=fps)
```

I am using colab and install ffmpeg using `!apt install ffmpeg` still got same error.

**Comment by anntzer** [comment]
Thanks for the report.  It's a known bug in the latest version of matplotlib; it will be fixed in the next point release (https://github.com/matplotlib/matplotlib/issues/16965).
