### ISSUE TITLE
[DOC] Star symbols (*) are escaped in docs signatures.

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#17119]
### Bug report

In the current docs, the signatures render with star symbols/asterix being escaped, like

    suptitle(self, t, \*\*kwargs)

e.g.
![image](https://user-images.githubusercontent.com/23121882/79142499-e3a7c200-7dbb-11ea-8b17-aa7d5b76953d.png)
[`matplotlib.figure.Figure.suptitle`](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.figure.Figure.html?highlight=subplots_adjust#matplotlib.figure.Figure.suptitle)

**Matplotlib version**

  * Matplotlib version: current docs / devdocs

**Comment by anntzer** [comment]
I think this is https://github.com/numpy/numpydoc/pull/256; see as to how skimage fixed that.
