### ISSUE TITLE
Autoscale to automatically include a tiny margin with `Axes.errorbar()`

### ISSUE THREAD

**Issue by dmcdougall** [matplotlib/matplotlib#1711]
As reported by Neal Becker on our devloper mailing list. Here's an example that reproduces the issue:

```python
x = [3, 6, 10]
y = [1, 2, 3]
import matplotlib.pyplot as plt

plt.errorbar(x, y, 0.2)
plt.show()
```

The error bars on either end of the x-axis are not visible. The error bar 'feet' should be taken into account during the autoscaling process. The current state of v1.2.x produces this:

![Screen Shot 2013-01-27 at 13 13 35](https://f.cloud.github.com/assets/328518/101258/a9d68ce6-68b5-11e2-998b-024837085c23.png)

**Comment by x1o** [comment]
I also find it annoying slightly: ![screenshot from 2016-08-06 00-52-12](https://cloud.githubusercontent.com/assets/3007504/17451508/717e9c4e-5b78-11e6-94b1-874f60837e6a.png)
Here's what R comes up with for comparison:  ![screenshot from 2016-08-06 00-50-53](https://cloud.githubusercontent.com/assets/3007504/17451507/7178e54c-5b78-11e6-918f-7dcd80690818.png)

**Comment by efiring** [comment]
This R-like strategy of including margins is the new default for autoscaling in 2.0, which is close to being finalized.  If there is an autoscaling problem with the 2.x line, please open a new issue for it.

**Comment by x1o** [comment]
@efiring Good to hear, thank you!
