### ISSUE TITLE
Bug in Text get_window_extent()

### ISSUE THREAD

**Issue by Jogala** [matplotlib/matplotlib#17116]
When executing 

`handle_text.get_window_extent()`

where 

`handle_text = Text(0.6795880017344075, 1.05, 'lala') 
`

I get

`RuntimeError: Cannot get window extent w/o renderer`

And I think this is a bug. Because when I look into the source code of text:

https://matplotlib.org/3.2.1/_modules/matplotlib/text.html

it contains the if query:

```
        if renderer is not None:
            self._renderer = renderer
        if self._renderer is None:
            self._renderer = self.figure._cachedRenderer
        if self._renderer is None:
            raise RuntimeError('Cannot get window extent w/o renderer')
```

Like you see the last two options are contradictory.

**Comment by tacaswell** [comment]
The figure may not have a cached renderer (if it has never been drawn) so those last two are consistent.
