### ISSUE TITLE
Slow update of the canvas while pan o zoom  if ax.text  or ax.annotate is present on the Draw

### ISSUE THREAD

**Issue by MarceloBarrosVanegas** [matplotlib/matplotlib#17122]
### Bug report
It is not a bug, just that matplolib zooming or pannig becomes slow if ax.text  or ax.anotate iis added to the canvas
**Bug summary**

Zoom and Pan works as expected (fast) if there are only lines or markers in the figure, once ax.text or ax.annotate is added it becomes very slow. I intent to use this code for at least 3000 text and 1000 lines and navigate on the canvas in a GUI (PySimpleGUI). My programming experience is not extensive so might as well be the way the class is written that is causing this. The snippet is a minimal example of the issue. Thanks in advanced.

**Code for reproduction**

```python
class _Zoom_Pan_():

    def __init__(self, fig, ax1, base_scale):
        'Declarar variables'
        self.fig, self.ax1, self.base_scale, self.x_init, self.y_init, = fig, ax1, base_scale, None, None
        "Conectar funcion"
        self._add_connection("button_press_event", self._OnPress_)
        self._add_connection("motion_notify_event", self._OnMotion_)
        self._add_connection("button_release_event", self._OffPress_)
        self._add_connection("scroll_event", self._Zoom_)

    def _add_connection(self, event_name, callback):
        self.fig.canvas.mpl_connect(event_name, callback)

    def Canvas_Draw(self):
        self.fig.canvas.draw_idle()

    def _OnPress_(self, event):
        if event.xdata != None and event.button == 2:
                self. x_init, self.y_init = event.xdata, event.ydata

    def _OnMotion_(self, event):
        if self.x_init != None and event.xdata != None:
            xmin, xmax, ymin, ymax = self.ax1.axis()
            dx, dy = self.x_init - event.xdata, self.y_init - event.ydata
            self.ax1.set(xlim=(xmin + dx, xmax + dx), ylim=(ymin + dy, ymax + dy))
            self.Canvas_Draw()

    def _OffPress_(self, event):
        self.x_init = None

    def _Zoom_(self, event):
        if event.step:
            'Obtener limites de ax1'
            xmin, xmax, ymin, ymax = self.ax1.axis()
            xdata, ydata = event.xdata, event.ydata
            'Obtener factor de escala'
            if event.step < 0:
                scale_factor = 1 / self.base_scale
            if event.step > 0:
                scale_factor = self.base_scale
            'Asignar nuevos limites'
            xmin_new, xmax_new = xdata - (xdata - xmin) / scale_factor, xdata + (xmax - xdata) / scale_factor
            ymin_new, ymax_new = ydata - (ydata - ymin) / scale_factor, ydata + (ymax - ydata) / scale_factor
            self.ax1.set(xlim=(xmin_new, xmax_new), ylim=(ymin_new, ymax_new))
            self.Canvas_Draw()



import matplotlib.pyplot as plt
import numpy as np

"Create data"
count = 1000
data = np.random.rand(1, count)[0]

"plot data"
fig = plt.figure()
ax1 = fig.add_subplot(111, rasterized=True)
for i in range(len(data) - 1):
    ax1.plot([i, i + 1], [data[i], data[i + 1]], rasterized=True, gid='Line' + str(i))
    ax1.annotate('Text', xy=(np.asarray([i, i + 1]).mean(),
                         np.asarray([data[i], data[i + 1]]).mean()),
                 xytext=(np.asarray([i, i + 1]).mean(),
                         np.asarray([data[i], data[i + 1]]).mean()),
                 arrowprops=dict(arrowstyle="->", color='red'),
                 rasterized=True,
                 gid='arrow_' + str(i))

"Apply zoom and pan"
Mpl_func = _Zoom_Pan_(fig, ax1, 2.5)

"Show figure"
plt.show()
```

**Actual outcome**

Slow Pannig an Zomming

**Expected outcome**

Fast Pan and Zoom

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7
  * Other libraries: Using this code inside a PySipleGUI Canvas

conda

Default

**Comment by tacaswell** [comment]
The source of the problem is that text is extremely expensive to draw, if you have ~1k strings on the canvas I expect that is what is dominating your render time.

For panning you can in `_OnPress_` make all of the text invisible and then make them all visible and re-draw in `_OffPress_` (`ann.set_visible(False)`, `ann.set_visible(True)` respectively) which should make zooming snappy again.

**Comment by MarceloBarrosVanegas** [comment]
Hi, thanks for ressponse. It works for the pan, but the zoom function is still pretty slow, I will keep trying to solve this issue, if succefull I will share it here.

**Comment by timhoffm** [comment]
Closing as not planned: There is not much we can do here. Speeding up text rendering would be highly non-trivial. And OTOH matplotlib is more a plotting library. Thousands of texts are quite a rare case.
