### ISSUE TITLE
set_ticks() changes view limits of the axis

### ISSUE THREAD

**Issue by karlglazebrook** [matplotlib/matplotlib#17136]
### Bug report

**Bug summary**

It seems that calling ax.set_ticks() *after* the axis range has been defined with ax.set_xlim() will change that range invisibly.

This seems to me like a bit of a trap for unwary plotters.

The example code constructs a plot with two axes meant to be the same, but depending on the value of the ticks set they can end up being different.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

filename = "plot.png"

fig, ax1 = plt.subplots()
ax1.set_xlabel("X")  
ax1.set_ylabel("Y")
ax1.tick_params('y', colors='k')
ax1.set_ylim([0, 1])

ax2 = ax1.twiny()
ax2.set_ylim([0, 1])

ax2.tick_params(axis="x", colors="blue")
ax2.set_xlabel('Test2', color='b')

xx =[4.2, 4.3, 5.0]    
#xx =[4.2, 4.3]    # Try uncommenting this line!

ax1.set_xlim([4.0, 4.5])
ax2.set_xlim([4.0, 4.5])

## This changes xmin, xmax depending on values of xx 
## and makes ax2 different to ax1
ax2.xaxis.set_ticks(xx) 


plt.savefig(filename)

```

**Actual outcome**

![plot](https://user-images.githubusercontent.com/15331994/79212306-c8f04e80-7e8a-11ea-90c1-f4c3f3069a38.png)

**Expected outcome**

I would expect the plot to show the two axes (blue and black X axis) agreeing.
Note if I edit the above code to move the set_ticks() call before the set_xlim() call this does happen. But I would not expect the order these are called to matter.

A quick look at the set_ticks() source code shows it auto-expands the axis range! 
https://matplotlib.org/3.1.3/_modules/matplotlib/axis.html#Axis.set_ticks

I am not sure of the logic behind this, perhaps it should be reconsidered?

*This might be same as issue #8320 ?*

**Matplotlib version**

  * Operating system: Mac OS 10.14.6
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7.6

Used anaconda

**Comment by jklymak** [comment]
I agree that its bad API, but it has always been like that, so I don't think we can change it for those users who expect it to auto expand.

**Comment by karlglazebrook** [comment]
OK. In that case I would suggest it be added to the documentation, all that is needed is one line, and also that a AutoExpand=True keyword be added. It would be a trivial change to allow someone to call with  AutoExpand=False and not have this happen. 

Does that sound reasonable?

BTW there is also a method set_xticks() which does the same thing except it appears to be a AxesSubplot object instead?

**Comment by karlglazebrook** [comment]
PS why is their both?

**Comment by dstansby** [comment]
I'm not sure this is something that can be changed. I think the best thing here is to update the docstring of `set_ticks()` to mention that the axis limits are also updated by the method.

**Comment by timhoffm** [comment]
> BTW there is also a method set_xticks() which does the same thing except it appears to be a AxesSubplot object instead?
>
> PS why is their both?

This is part historic, part convenience. `ax.set_xticks()` is a shorthand wrapper for `ax.xaxis.set_ticks()`.

**Comment by tacaswell** [comment]
I think if we did not expand the range, we would get bug reports that ticks were not visible.

**Comment by karlglazebrook** [comment]
Sounds reasonable. A docstring update would be reasonable so at least it is documented.

How about adding an optional keyword whose default is to keep the current behaviour?

**Comment by timhoffm** [comment]
> How about adding an optional keyword whose default is to keep the current behaviour?

Can you give an example in which that would really be beneficial? I would only want to add more API if it really solves a problem.

In your example above the confusion would be there with and without such a parameter in the first place. After finding out the problem, you could solve it by setting, `set_ticks(..., update_limits=False)`. But OTOH you could equally well move `set_xlim()` below `set_ticks()` to solve it.

**Comment by timhoffm** [comment]
Removed "Good first issue" label at that was referring to docs and is solved via #17915.

Still open: Discussion on an optional keyword `update_limits`.

**Comment by karlglazebrook** [comment]
You make good points Tim. The bug cost me several hours of puzzled debugging but you are right having a keyword would have made no difference. Once the problem is known it is easy to adjust the code.

The main thing is to have it in the set_ticks() documentation, perhaps with a suggestion of how to work around it if the behaviour is not desired, as that is likely the first thing someone will check when they are seeing puzzling behaviour.

Karl

**Comment by timhoffm** [comment]
@karlglazebrook We've discussed the issue in the developer call and decided that an additional keyword `update_limits` is not worth it. As you've proposed, I've added a note how to work around the behavior in #18087.

**Comment by karlglazebrook** [comment]
Thanks! Sound reasonable.

Karl
