### ISSUE TITLE
Wrong icon on windows task bar for figure windows

### ISSUE THREAD

**Issue by MaartenBransen** [matplotlib/matplotlib#17144]
### Bug report

**Bug summary**
When opening a matplotlib figure window, the (Windows) task bar icon is not correct. It instead shows a white / blank icon. Possible duplicate of #14850?

**Description**
This issue started after updating the Spyder IDE to 4.1.2 (which required removing and reinstalling matplotlib), but the folks [over at the spyder repository](https://github.com/spyder-ide/spyder/issues/12301) indicated this was not something they control.

I tried:
* updating matplotlib from 3.1.3 to the most recent version (3.2.1) using `conda update -c conda-forge matplotlib`
* a clean reinstall of anaconda (for unrelated reasons), but the same issue was still present
* resetting the windows icon cache by removing `C:\Users\<user>\AppData\Local\IconCache.db` and restarting windows explorer
* switching backend for rendering the figure through the Spyder settings from `Automatic` to `Qt5`, `Qt4`, or `Tkinter`. In all cases the outcome was the same.

**Outcome**
![79195908-5f8f2200-7e2f-11ea-8ab6-361778ebd1f9](https://user-images.githubusercontent.com/54527765/79308098-4605dd00-7ef8-11ea-98de-ac4e2483cfe1.png)
Note the icon on the windows task bar, the white page-like icon is that of the figure window.

**Expected outcome**
Previously I would see the spyder IDE icon (which, apparently, is already strange behaviour) also for the figure windows, on another machine I see the matplotlib logo. 

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.3, but upgrading to 3.2.1 did not resolve the problem
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg (but tried also Qt4 and TKinter)
  * Python version: 3.7.6

**Comment by MaartenBransen** [comment]
Any updates on this?

**Comment by anntzer** [comment]
Looks like the correct fix is the one described in https://stackoverflow.com/a/1552105 (see also https://github.com/jupyter/qtconsole/pull/71/files), at least it works for me locally.  Except that, we should first call GetCurrentProcessExplicitAppUserModelID to check whether this had been set by someone else before (after all people may be embedding Matplotlib into their own app), and we don't like ctypes here so this needs to be done as an C extension module.
