### ISSUE TITLE
Animation issue 

### ISSUE THREAD

**Issue by JTebeka** [matplotlib/matplotlib#17152]
### Bug report

Hi, I am trying to get an animated graph (example from the website) but I just have the layout and no animation. 
Here is the codeI am using : 
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, ax = plt.subplots()
x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))
def init():  # only required for blitting to give a clean slate.
    line.set_ydata([np.nan] * len(x))
    return line,
def animate(i):
    line.set_ydata(np.sin(x + i / 100))  # update the data.
    return line,
ani = animation.FuncAnimation(
    fig, animate, init_func=init, interval=2, blit=True, save_count=50)
plt.show()

I am using : 
- macOS Catalina 
- Vscode 1.44.1
- matplotlib  3.1.3  
- python 3.7.7

I must add that I have the same problem with Plotly. Should I add something in Vscode to have animated graph. 

Thx

**Comment by ImportanceOfBeingErnest** [comment]
The code itself works fine when run with an interactive backend. First make sure that it works outside of VSCode.

**Comment by JTebeka** [comment]
I tried also on jupyter (v 6.0.3) and Spyder (v 4.1.2) and same result. No animation !

**Comment by ImportanceOfBeingErnest** [comment]
Jupyter (that is, IPython) sets a non-interactive backend by default. In Spyder the default settings are to use IPython with non-interactive backend as well. Spyder allows you to select a matplotlib backend in its user settings. In jupyter you can select an [interactive backend](https://matplotlib.org/3.1.1/tutorials/introductory/usage.html#backends), or show the animation via  [`to_html5_video`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.animation.Animation.html?highlight=jshtml#matplotlib.animation.Animation.to_html5_video) or [`to_jshtml`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.animation.Animation.html?highlight=jshtml#matplotlib.animation.Animation.to_jshtml).

**Comment by JTebeka** [comment]
So I add : myAnimation.to_jshtml() at the end of my file (in Spyder). It seems that something different happened because the red point is "at the end" of my graph and not at the beginning as previously...But I don't see anything 
Moreover, I tried also in vscode. Here no graph appears except code but no animation. 
Vscode has the same problem as Jupyter/Spyder. Does it also explain that I can't get animation with plotly neither ? 
Thx

**Comment by JTebeka** [comment]
I found on internet : 
rc("animation", html="jshtml")
rc
HTML(myAnimation.to_jshtml())

and it works even on vscode ! 
Do you have an idea for plotly...Something similar can be found (I know it is not the right place to ask but in case someone can help me)
