### ISSUE TITLE
corrupted eps files when saving and using fill_between

### ISSUE THREAD

**Issue by broulston** [matplotlib/matplotlib#17158]
### Bug report

I seem to be having an issue where my saved eps files are corrupted when using `savefig` on a plot that has called `fill_between`.

The plotting throws no errors, and if I use `show()` and the plot shows exactly as it should. If I then call for example `plt.savefig("test.png", dpi=600)` the plot saves correctly as a png.

If however I call `plt.savefig("test.eps", dpi=600)` the file is corrupted and can not be opened. 

If I run the same exact code, but without `fill_between` and save as eps, then the eps file saves correctly and can be opened.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

lam = np.linspace(start=3500.0, stop=10200.00, num=61620)
flux = 10 + np.random.rand(lam.size) / 10 + 0.0001 * lam
error = np.sqrt(flux) / 10

fig = plt.figure(figsize=(8, 6))
for ii in [0, 1, 2]:
    plt.fill_between(lam, flux + (ii) - error,
                     y2=flux + (ii) + error,
                     color='grey')
    plt.plot(lam, flux + (ii), color='black',
             linewidth=0.5, zorder=1)

plt.savefig("test_spec.eps", dpi=600)
# plt.savefig("test_spec.png", dpi=600)
plt.clf()
plt.close()
```

**Actual outcome**

<img width="1366" alt="Screen Shot 2020-04-16 at 10 37 08 AM" src="https://user-images.githubusercontent.com/29544248/79469663-74ee8280-7fce-11ea-89a8-ae00266fcde3.png">

**Expected outcome**

<img width="1556" alt="Screen Shot 2020-04-16 at 10 37 30 AM" src="https://user-images.githubusercontent.com/29544248/79469668-7750dc80-7fce-11ea-9e57-68517db7a93c.png">

**Matplotlib version**

  * Operating system: macOS 10.15.4 (19E287)
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.7
  * Jupyter version (if applicable):
  * Other libraries: 

Both matplotlib and python were installed using conda

**Comment by jklymak** [comment]
I can confirm on master, using both Preview and Ghostscript (via ImageMagick) to convert.  I don't get an error, but the image is blank.   Also `fig.savefig('test_spec.pdf')` fails.  BTW, no need for so much data, `num=100` also fails.

Interestingly, when I tried to bisect, I put `matplotlib.use('agg')` at the top to stop QT compatibility issues from being a problem, and then the code worked fine for small num, but then increasing to large num it returned a blank pdf/eps again.  

So, I agree there is something strange going on, but cannot say exactly what yet.

**Comment by broulston** [comment]
@jklymak thanks for confirming it just wasn't my computer!   

> BTW, no need for so much data, `num=100` also fails.

I wondered about this actually, if maybe it was because there are so many points. The `num=61620` was from my real data set where I need that amount because they represent actual wavelengths, so I just kept it the same to keep it as close to my use case as possible.

**Comment by anntzer** [comment]
I think this is simply hitting the limits of postscript: the postscript reference (https://www.adobe.com/content/dam/acom/en/devnet/actionscript/articles/PLRM.pdf table B2) states that in LanguageLevel 1 the maximum number of points in all active paths (including clipping paths, etc.) is typically 1500 (though implementation defined); it can be higher in LanguageLevel2 but here we're talking about more than an order of magnitude more points (I can't repro @jklymak's error with just 100 points).
I haven't checked the pdf spec but my guess is that (pdf being derived from ps) there's a similar limit.

Given that the limit is implementation-defined I don't think there's anything to do about it.  Indeed, it looks like at 61000 points + the builtin ps renderer I get a /stackoverflow error from ghostscript, but mplcairo appears to be slightly more efficient and generates a ps file that ghostscript renders fine (but very slowly); OTOH putting yet an order of magnitude more points results in a file so large that ghostscript doesn't finish rendering it in 2 minutes (though it doesn't error, which I guess is interesting?).
