### ISSUE TITLE
How to change the font of mathematical formula?

### ISSUE THREAD

**Issue by Photonico** [matplotlib/matplotlib#17155]
I have set the font via:
```
plt.rc('font', family='serif')
```
However, the font of mathematical formula (between two dollar signs) is still sans-serif.
How to change the mathmatical formula font to serif?

My code
```
import numpy as np
T = np.arange(0,1000,1)
k = 1.380649e-23
m = np.matrix([2,28,32])*1.67e-27
v = np.sqrt(3*k*T/m.T)

import matplotlib.pyplot as plt
plt.rc('font', family='serif')
plt.ticklabel_format(style='sci', scilimits=(0,0))
plt.xlabel(r"Temperature ($K$)"); plt.ylabel(r"Velocity ($ms^{-1}$)")
plt.plot(T,np.array(v[0,:].T),label="Hydrogen")
plt.plot(T,np.array(v[1,:].T),label="Nitrogen")
plt.plot(T,np.array(v[2,:].T),label="Oxygen")
plt.legend(loc='best')
```
the font of $K$, and $ms^{-1}$ in my picture is still sans-serif.

**Comment by Photonico** [comment]
I fix it via
```
matplotlib.rcParams['mathtext.fontset'] = 'cm'
```

**Comment by Photonico** [comment]
However, how to change the font of ticks and the scientistic notation?

**Comment by QuLogic** [comment]
The text is correctly serif for me, using the two rcParams you specified. For usage questions like these, please use our Discourse: https://discourse.matplotlib.org/

**Comment by Photonico** [comment]
> The text is correctly serif for me, using the two rcParams you specified. For usage questions like these, please use our Discourse: https://discourse.matplotlib.org/

I have changed the font of Mathtext via:
```
matplotlib.rcParams["mathtext.fontset"] = "cm"
plt.ticklabel_format(style="sci", scilimits=(0,0), useMathText=True)
```
The format of ticks is changed, however, the font of ticks is also serif, not cmu,
How to change the font of ticks to cmu like the mathtext in label.
