### ISSUE TITLE
Definitive docs for how to compile on Windows

### ISSUE THREAD

**Issue by dhyams** [matplotlib/matplotlib#1717]
I've managed to compile matplotlib under Windows 7, but it was a bit of a fight and I felt like a kludged one too many things.  I've not been able to find a guide for building matplotlib on Windows, except for a smattering of newsgroup posts a long time ago (http://sourceforge.net/mailarchive/message.php?msg_id=27961105)

Really this info needs to be on the website before it becomes a lost art; apparently someone is doing it (Christophe probably?) because the Windows binary releases continue to show up ;)

**Comment by WJTey** [comment]
Thank you for providing the matplotlib. Now I 'm working on a small research project with Python 2.7 and   installed Microsoft VS 2012 on my laptop. And this make me unable to run python matplotlib-winbuild\buildall.py. Do you have other alternatives to solve this?

**Comment by QuLogic** [comment]
Firstly, this bug was closed almost two years ago, and secondly, it is only a change in documentation. Please open a new issue with a full description of the problem. Comments on really old issues are just going to get lost.

**Comment by efiring** [comment]
@WJTey I think your question might better be directed to the matplotlib-users@python.org or other mailing list; it is a "how do I manage MS compilers for compiling python extensions" question, not a matplotlib issue.

**Comment by tacaswell** [comment]
If you want to build c-extensions from windows, you can not use VS2012 (it must be VS2008 for compatibility reasons).  It seems that https://www.microsoft.com/en-us/download/details.aspx?id=44266 is now the recommended compiler to use for python 2.7 extensions on windows.

If you go to python 3.5+ building on windows is decoupled from an exact version of VS and will be much easier to maintain going forward.

**Comment by smaudet** [comment]
"If you go to python 3.5+ building on windows is decoupled from an exact version of VS and will be much easier to maintain going forward."

How I wish that were true.

This build is still kind of a kludge - doesn't seem to want to build well, and there's a lot of needing of specific versions/instructions missing.

**Comment by smaudet** [comment]
Frightful problems I have encountered:

Mismatched C RT libraries
Hard-coded dependence on msvc 2010
Mysterious segfaults
Contradictory build instructions
Undocumented dependencies on empty files being present in the filesystem
