### ISSUE TITLE
How to change the thickness of the marker "x" when using scatter?

### ISSUE THREAD

**Issue by sth1997** [matplotlib/matplotlib#17192]
I'm trying to change the thickness of the marker "x" when using scatter, but I found the "linewidths" parameter doesn't work for Matplotlib version 3.1.0. 
But when I switch to Matplotlib version 1.3.1, "linewidths" parameter works well. Why? Is there something changed in newer version?
This is my code.

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib
print(matplotlib.__version__)
x = y = np.arange(5)

fig,ax = plt.subplots(1)

ax.scatter(x,y,  s=100,marker='x',color='b',linewidths=1)
ax.scatter(x,y+1,s=100,marker='x',color='r',linewidths=2)
ax.scatter(x,y+2,s=100,marker='x',color='g',linewidths=3)

plt.show()
```
This is the figure output by Matplotlib 3.1.0.
![figure_1](https://user-images.githubusercontent.com/16641156/79685995-6ffc2e00-826f-11ea-84b3-5199cda48238.png)

This is the figure output by Matplotlib 1.3.1.
![figure_2](https://user-images.githubusercontent.com/16641156/79686005-99b55500-826f-11ea-9d4f-3e22d50b5901.png)

**Comment by ImportanceOfBeingErnest** [comment]
Thanks for the report. That's indeed unexpected. A workaround for now may be to use `plot` instead of `scatter`

    ax.plot(x,y, ms=10, marker='x', mec='g', mew=3, ls="none")

or to create the marker manually and supply it to `scatter`

```
from matplotlib.markers import MarkerStyle
from matplotlib.path import Path

ms = MarkerStyle(Path([[-1,-1],[1,1], [-1,1],[1,-1]], codes=[1,2,1,2]))
ax.scatter(x,y, s=100, marker=ms, edgecolor='g', linewidths=3)
```

**Comment by ImportanceOfBeingErnest** [comment]
The culprit is here

https://github.com/matplotlib/matplotlib/blob/f369b105e6153a67b4a8065ce97344b2cfbc855c/lib/matplotlib/axes/_axes.py#L4489-L4491

where `linewidths` is overwritten in case of unfilled markers. This makes sense for the default `linewidth=None` case, but not if something different is specified. 

When fixing this, one needs to consider that `linewidths=[None, 4, None, 3, None, 4]` is probably also a valid usecase.

**Comment by tmdavison** [comment]
A workaround for now appears to be to use `linewidth` instead of `linewidths`. I don't know why this works, but presumably that's unintended and may break in the future.
