### ISSUE TITLE
NavigationToolbar2Wx limited to canvas parent is unusable in a ScrolledPanel

### ISSUE THREAD

**Issue by pjago** [matplotlib/matplotlib#17216]
**Bug summary**

In NavigationToolbar2Wx the parent is fixed as `canvas.GetParent()`, making it extra difficult to add a static navigation toolbar in a [ScrolledPanel canvas](https://stackoverflow.com/questions/55549651/wxpython-make-the-matplotlib-navigationtoolbar-static-for-a-figure-inside-scro). The direct attempt results in a unusable toolbar.

**Code for reproduction**

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar
import wx
import wx.lib.scrolledpanel as scrolled
import seaborn as sns
%matplotlib inline

class PlotScrolled(wx.Panel):
  def __init__(self, parent, figure, id=-1, **kwargs):
    wx.Panel.__init__(self, parent, id=id, **kwargs)
    self.figure = figure
    self.figure.set_facecolor('white')
    self.scroll = scrolled.ScrolledPanel(self, -1, style = wx.TAB_TRAVERSAL|wx.SUNKEN_BORDER)
    self.canvas = FigureCanvas(self.scroll, -1, self.figure)
    self.canvas.draw()
    self.scroll.SetAutoLayout(1)
    self.scroll.SetupScrolling(scroll_x=False, scroll_y=True)
    sp_sizer = wx.BoxSizer(wx.VERTICAL)
    sp_sizer.Add(self.canvas, 1, wx.EXPAND)
    self.scroll.SetSizer(sp_sizer)
    ## here is the problem: can't pass parent=self
    self.toolbar = NavigationToolbar(self.canvas)
    self.toolbar.Realize()
    sizer = wx.BoxSizer(wx.VERTICAL)
    sizer.Add(self.scroll, 1, wx.EXPAND)
    sizer.Add(self.toolbar, 0, wx.LEFT | wx.EXPAND)
    self.SetSizer(sizer)

app = wx.App()
frame = wx.Frame(None, -1, 'Plotter', pos=(0, 0), size=wx.DisplaySize())
iris = sns.load_dataset("iris")
grid = sns.pairplot(iris)
plotter = PlotScrolled(frame, grid.fig)
frame.Show()
app.MainLoop()
```
**Actual outcome**

<img width="944" alt="not ok" src="https://user-images.githubusercontent.com/7795187/80007225-5a1f8080-849c-11ea-9d83-5b3118d7203b.png">

**Expected outcome**

<img width="944" alt="ok" src="https://user-images.githubusercontent.com/7795187/80007255-63a8e880-849c-11ea-869d-8286f5d23bdd.png">

**Matplotlib version**
  * Operating system: Windows
  * Matplotlib version: 3.1.3
  * Matplotlib backend: WXAgg
  * Python version: 3.7.6

**Comment by anntzer** [comment]
1) please provide a *complete* example for reproduction.
2) can you just call Reparent to move the toolbar where it needs to be?

**Comment by pjago** [comment]
1. completed the example
2. adding `self.toolbar.Reparent(self)` also solves the issue! thx

**Comment by anntzer** [comment]
So I guess we can close this?
