### ISSUE TITLE
Full-Sky (360deg) image with projection=WCS not drawing the horizontal axis ticks/labels.

### ISSUE THREAD

**Issue by mireianievas** [matplotlib/matplotlib#17224]
I'm trying to overlay some sources over a full-sky image from the Fermi-LAT (in my case the diffuse model, can be found here: https://fermi.gsfc.nasa.gov/ssc/data/analysis/software/aux/4fgl/gll_iem_v07.fits ).

I open the fits file with astropy as follows

```
import astropy.io.fits as pyfits
diffusemap = pyfits.open("gll_iem_v07.fits")

```
Then I get the WCS information from the hdu using astropy.wcs.WCS and use the projection option in add_subplot to adapt the axes.

```
mywcs = astropy.wcs.WCS(diffusemap[0])

MyFig = plt.figure(figsize=(8,3),dpi=150)
MyPlot = MyFig.add_subplot(111, projection=mywcs[0], label='overlays')
data = np.sum(diffusemap[0].data,axis=0)

im = MyPlot.imshow(data,
              norm=mcolors.LogNorm(vmin=np.min(data),vmax=0.1*np.max(data)),
              cmap='inferno',
              origin='lower',zorder=-100)

overlay = MyPlot.get_coords_overlay('fk5')
overlay.grid(color='white', lw=0.3, ls='dotted')

MyFig.colorbar(im)

MyPlot.set_ylabel("Galactic Latitude")
MyPlot.set_xlabel("Galactic Longitude")

im.set_clip_path(MyPlot.coords.frame.patch)

MyFig
```

What I get

![image](https://user-images.githubusercontent.com/2607760/80080111-6addfe00-8551-11ea-9c7d-8dfe9f57cd2d.png)

Is there any reason why the 'Galactic Longitude' (horizontal axis) is now drawn at all? There are no ticks, or labels and the axis label is ignored completely. I tried to set the zorder and tried to see if the axis is hidden by specifying an alpha=0.5, but there is simply no X axis.

**Expected outcome**

**Matplotlib version**

  * Operating system: Archlinux
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.8.1
  * Jupyter version (if applicable): 4.6.1 (jupyter-core) / 5.3.4 (client) / 6.0.0 (console)
  * Other libraries: astropy (4.0), astropy-healpix (0.7.0)

I installed everything through conda and pip.

**Comment by jklymak** [comment]
This would be better asked at astropy. If there is something we can help with and you have a reproducible example that doesn’t use a downstream library feel free to reopen.   Thanks.
