### ISSUE TITLE
Path simplification causes unexpected distortion in tiny subplots saved to PDF

### ISSUE THREAD

**Issue by mzucker** [matplotlib/matplotlib#17238]
### Bug report

**Bug summary**

When developing some computational geometry code where precision of shapes was important, the default path simplification settings made me think my code was doing incorrect things. 

Caveat: this is not an error per se, it is a situation where matplotlib's default settings led to lost productivity. I was encouraged by the matplotlib twitter account to file this report. 
<https://twitter.com/matplotlib/status/1253602462176509953>

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

arc_radius = 0.15

# generate points along an arc
def arc_points(ctr, theta0, theta1):
    theta = np.linspace(theta0, theta1, 65).reshape(-1, 1)
    pts = ctr + arc_radius*np.hstack((np.cos(theta), np.sin(theta)))
    return pts

############################################################
# generate some "skyline" contours with rounded top corners

spans = [(1.0, 2.0, 0.2),
         (3.0, 4.0, 0.3),
         (5.0, 6.0, 0.1)]

skyline_arrays = [ np.array([[spans[0][0]-1, 0]]) ]

for x0, x1, y in spans:
    
    skyline_arrays.extend([
        np.array([[x0-arc_radius, 0]]),
        arc_points([x0, y], np.pi, np.pi/2),
        arc_points([x1, y], np.pi/2, 0),
        np.array([[x1+arc_radius, 0]])
    ])

skyline_arrays.append(np.array([[spans[-1][1]+1, 0]]))

skyline = np.vstack(tuple(skyline_arrays))

############################################################
# make a bunch of subplots so that each one is tiny 

rows = 4
cols = 4
count = rows*cols

for i in range(count):

    # change rc params
    if i < count//2:
        threshold = 1.0/9.0
    else:
        threshold = 0.0

    matplotlib.rcParams['path.simplify_threshold'] = threshold
    label = 'path.simplify_threshold = {:g}'.format(threshold)

    # kick off a subplot
    plt.subplot(rows, cols, i+1)

    # plot the curve
    plt.plot(skyline[:,0], skyline[:,1], 'b-', linewidth=0.2, zorder=0)

    # finish subplot
    plt.axis('equal')
    plt.axis('off')
    plt.text(3.5, -0.5, label, ha='center', va='top', fontsize=4)

# save figure to vector output format
plt.savefig('matplotlib_small_plot_oddity.pdf')
```

**Actual outcome**

The "skyline" figures in the plots generated have slanted tops and sides, and the corners are uneven.

![default_threshold](https://user-images.githubusercontent.com/3287580/80241737-237b6e80-8632-11ea-9b3b-2c3cc0d4c223.png)

**Expected outcome**

The skyline figures have vertical sides and horizontal tops with correctly rounded corners.

![zero_threshold](https://user-images.githubusercontent.com/3287580/80241782-368e3e80-8632-11ea-8cb0-4926b8800aff.png)

**Matplotlib version**
Matplot version 3.2.0 with Python 3.7.7, both installed via MacPorts.

**Comment by mzucker** [comment]
It's clearer in <https://twitter.com/matt_zucker/status/1253568262345981958> but it would be tougher to get that data into a neat tiny test script.

**Comment by jklymak** [comment]
Is there someway we could make that more discoverable?  Or do you think this should be set to 0 by default?

**Comment by mzucker** [comment]
I'm wondering if it makes sense to set path simplification to 0 by default for vector output devices? The default behavior should be fine for rendering to raster images. Like maybe a separate rc parameter for path.simplify_vector_devices which defaults to False?

**Comment by dopplershift** [comment]
Not having thought hard about it, defaulting to off for vector output seems reasonable. The whole point of path simplification is to gain performance when the difference in results is undetectable. Vector output is not one of those cases.

**Comment by WeatherGod** [comment]
Note, I don't even think we would need an rc param or whatever, we would
just need to have vector backends specify no path simplification as it
iterates the paths while saving.

**Comment by jklymak** [comment]
I guess the issue is that path simplification acted as a kind of compression making the vector files smaller.  Probably more of an issue 15 years ago, but we may still want an rcParam?

**Comment by dopplershift** [comment]
Well if there's realized increases to file sizes, we should consider that. I wasn't this might actually have benefits currently to our vector output. I wonder what the impact would be on our current set of images in the test suite (purely as a benchmark of file size increase)

**Comment by tacaswell** [comment]
the path simplification in vector backends is particularly brutal as I strongly suspect it is done at "72dpi".

Where this will be a problem is for people using svg to save massively oversampled data.  I have personally thrown 10-100k long vectors at Matplotlib on a regular basis that I then saved as pdfs for papers (multi-scale time series are fun!).

**Comment by jklymak** [comment]
Sure, I do that as well, but then I rasterize things like that at 600 dpi since no one can see all the detail anyway.

**Comment by brunobeltran** [comment]
My feeling is that if people want to compress their files, we should give them the option to do that, but I often am using matplotlib to compare results of numerical simulations to analytical theory by eye...and the easiest way to do that is often to make a plot and zoom in really far.

I also was unaware of this default simplification, and would add my voice to the crowd saying that if you want to compress your PDFs, you should have to ask for it. Doing it by default is "surprising".

In terms of awareness, I worry that adding a tutorial or more docs won't help people actually realize that this is a thing. Instead, I think it would be very natural and discoverable as a new kwarg to `plt.savefig`, for example. That's the docstring people will probably be looking at as they're making their figure and wondering how to "compress it", I would guess.

**Comment by brunobeltran** [comment]
> the path simplification in vector backends is particularly brutal as I strongly suspect it is done at "72dpi".
> 
> Where this will be a problem is for people using svg to save massively oversampled data. I have personally thrown 10-100k long vectors at Matplotlib on a regular basis that I then saved as pdfs for papers (multi-scale time series are fun!).

**Comment by brunobeltran** [comment]
Sorry, weird github bug closed the issue when I asked it to delete a comment, reopened.

**Comment by brunobeltran** [comment]
> I have personally thrown 10-100k long vectors at Matplotlib on a regular basis that I then saved as pdfs for papers (multi-scale time series are fun!).

I feel like anytime I have data this big, I also have space for a PDF file to be saved at least on the first pass (and then likely deleted and replaced with a rasterized or simplified one). In these extreme cases I feel like the user will tend to notice that `savefig` is taking a really long time and easily infer that it's just saving all of the data points.

> Sure, I do that as well, but then I rasterize things like that at 600 dpi since no one can see all the detail anyway.

Another solution that has been suggested before would be to finally separate the actual "DPI" from the 72.0 that's used as a in->pts unit conversion value (that currently lives in `renderer.dpi` for all the vector renderers). Then we can just set the default `dpi` for vector renderers to something more reasonable like 600 and a lot of these complaints about path intersection not working, simplification being too aggressive, etc would just disappear?

**Comment by tacaswell** [comment]
> Then we can just set the default dpi for vector renderers to something more reasonable like 600 and a lot of these complaints about path intersection not working, simplification being too aggressive, etc would just disappear?

I would expect to just push those problems out ~7x so just less frequent.  This is going to get quantized  at some point (worst case we are going to hit float precision) so I think this is probably a good idea, but not a complete panacea. 

I am not sure off the top of my head that the simplification is done someplace where it is easy to be aware of what backend you are using...

**Comment by kbrose** [comment]
Path simplification is done here:

1. https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/path.py#L472-L490, which directly calls
1. https://github.com/matplotlib/matplotlib/blob/master/src/_path_wrapper.cpp#L598-L673, which directly calls
1. https://github.com/matplotlib/matplotlib/blob/master/src/_path.h#L1035-L1072, which instantiates the `PathSimplifier` object, causing the actual simplification at
1. https://github.com/matplotlib/matplotlib/blob/master/src/path_converters.h#L555

The `Path` object is generally not aware of the backend AFAIK, but you can control whether or not simplification happens through its `should_simplify` and `simplify_threshold` attributes.

**Comment by brunobeltran** [comment]
> I am not sure off the top of my head that the simplification is done someplace where it is easy to be aware of what backend you are using...

The simplification that matters is actually triggered by each backend's `draw_path`. 

For context, the SVG backend currently decides whether to simplify using 

```python
path.should_simplify and rgbFace is None and gc.get_hatch_path() is None
```

**Comment by kbrose** [comment]
Yep, you're right. The same is true of the PDF backend (which I think is what OP issue is about), but both should probably be updated together. https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py#L1768-L1775
