### ISSUE TITLE
3D scatter plot is in background when it's not supposed to be

### ISSUE THREAD

**Issue by MishaRuko** [matplotlib/matplotlib#17237]
### Bug report

When plotting a surface/wireframe plot and a 3D scatter plot on the same axes, the scatter plot is below the surface/wireframe plot even when it should be above it.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt

xgrid, ygrid = np.meshgrid(np.arange(-8, 9, 0.5), np.arange(-8, 9, 0.5))

f = lambda x, y: x**2+y**2
z = f(xgrid, ygrid)

fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

ax.scatter3D([0], [0], [150], color="red")
ax.plot_wireframe(xgrid, ygrid, z)

plt.show()
```

**Actual outcome**
https://i.stack.imgur.com/bHsrD.png - the scatter plot(red dot) is under the wireframe plot
https://i.stack.imgur.com/gY7fu.png - the scatter plot is actually above the plot when viewed from the side.

**Expected outcome**
https://imgur.com/a/IXEg2qd - the scatter plot is above the wireframe plot like it should be

**Matplotlib version**

  * Operating system: MacOS (doesn't work on windows either)
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.2 (doesn't work with 3.7.2 either)
  * Other libraries: numpy: 1.18.2

 
Installed matplotlib using pip3

**Comment by anntzer** [comment]
This is a known limitation, described at https://matplotlib.org/devdocs/api/toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles, and also mentioned in many other issues in the tracker.  As noted by @scottshambaugh, it is unlikely to be ever fixed without a complete rewrite of the 3d renderer.
