### ISSUE TITLE
tick modifier doesn't get styled with ticks

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#17259]
When using `plt.yticks(color="red")`, the tick "modifier" (in this case the `1e-5` on top of the y-axis) is not adapted accordingly:
```python
import matplotlib.pyplot as plt


x = [1, 2, 3]
y = [1.0e-5, 1.5e-5, 1.6e-5]

plt.plot(x, y)
plt.yticks(color="red")
plt.show()
```
![a](https://user-images.githubusercontent.com/181628/80591929-d7a83b00-8a1e-11ea-8dc1-6ee63ea60fa6.png)

**Comment by timhoffm** [comment]
I suppose this is sort of intentional. `plt.yticks()` only applies to the tick labels. 

You can alternatively use `plt.tick_params('y', labelcolor="red")`.

**Comment by nschloe** [comment]
Thanks!
