### ISSUE TITLE
hexbin plot, PolyCollection and inconsistent facecolor values

### ISSUE THREAD

**Issue by Finfalter** [matplotlib/matplotlib#17251]
### Bug report
The method `get_facecolors()` evaluates to different values depending if I run it in *pure* Python (in PyCharm) or in a Jupyter Notebook. 

The example is the same as [in this bug report](https://github.com/mwaskom/seaborn/issues/1734).

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Define some dummy data
x = np.array([1,1,1,1.5,1.5,2])
y = np.array([1,1,1,1,1,1])

g = sns.JointGrid(x=x, y=y, xlim=(1,2), ylim=(0,2))

g = g.plot_joint(plt.hexbin, C=np.ones(x.shape), reduce_C_function=np.sum, extent=[1, 2, 0.5, 1.5],
                 gridsize=3, linewidths=1, edgecolors='face')

# Get the PolyCollection of hexbin patches
polycollection = g.ax_joint.get_children()[0]
assert isinstance(polycollection, matplotlib.collections.PolyCollection)

# I would expect the result to be an array of shape (3,4) but am getting (1,4)
# plt.draw() # <-- this line influences the result
print(polycollection.get_facecolors())
```

**Outcome in notebook without plt.draw()**
```
[[0.12156863 0.46666667 0.70588235 1.        ]]
```

**Outcome in notebook with plt.draw()**
```
[[0.993248 0.906157 0.143936 1.      ]
 [0.127568 0.566949 0.550556 1.      ]
 [0.267004 0.004874 0.329415 1.      ]]
```

**Outcome in Python/PyCharm regardless of plt.draw()**
```
[[0.12156863 0.46666667 0.70588235 1.        ]]
```

**Expected outcome**
```
[[0.993248 0.906157 0.143936 1.      ]
 [0.127568 0.566949 0.550556 1.      ]
 [0.267004 0.004874 0.329415 1.      ]]
```
I plan to run my code (similar to this example) in a cloud environment. It should run correctly in *pure* python. How do I do it?

**Matplotlib version**

  * Operating system: Ubuntu 19.10
  * Matplotlib version:  3.1.3 (both, in PyCharm as well as in Jupyter)
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
      - PyCharm: Qt5Agg
      - Jupyter: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.7 (both, in PyCharm as well as in Jupyter)
  * Jupyter version (if applicable): 4.6.3 (core)

**Comment by QuLogic** [comment]
`plt.draw()` is lazy; if you want to force a draw, use `fig.canvas.draw()`.

**Comment by Finfalter** [comment]
Thanks for your quick reply. Is there any other means to trigger an evaluation of `get_facecolors()`? As I said, in *pure* Python/PyCharm, `plt.draw()`does not work at all (and I wonder where `fig` would come from - there is none in the example above, right?)

**Comment by WeatherGod** [comment]
"fig = plt.gcf()" would get you the current figure object. Oftentimes, the
figure object is implicitly created for you and you don't need to carry it
around.

**Comment by Finfalter** [comment]
Thanks for clarification, WeatherGod. 
The combination of hints works for me, even in Python/PyCharm: 
`fig = plt.gcf().canvas.draw()` before invoking `get_facecolors()`
