### ISSUE TITLE
mplstyle: grid.dashes?

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#17273]
I would like to translate the grid spec
```python
plt.grid(axis="y", dashes=(10, 10), lw=0.5, color="#969696")
```
into a mplstyle file. I  have almost everything, but I don't know how to translate `dashes`.
```
axes.grid: True
axes.grid.axis: y
grid.color     : 969696
grid.linewidth : 0.5
# grid.linestyle : --
# grid.dashes : 10, 10
```
Any hints?

**Comment by QuLogic** [comment]
`linestyle` accepts dash sequences.

**Comment by story645** [comment]
You can see a list of valid linestyles at https://matplotlib.org/gallery/lines_bars_and_markers/linestyles.html#sphx-glr-gallery-lines-bars-and-markers-linestyles-py. 

Also questions such as these which are neither bug reports nor feature requests are better suited for https://discourse.matplotlib.org/
