### ISSUE TITLE
Incompetent Documentation

### ISSUE THREAD

**Issue by myRandomFiles** [matplotlib/matplotlib#17280]
I'd never hire anyone contributing to the release of matplotlib, because the documentation is so amateurish, it has wasted millions of hours of Python's users' time. I was once a hacker too who wrote software without documentation, but then I grew up, moved out of dad's house, and started writing API's for other people to use, not just for me to use by myself.

**Comment by WeatherGod** [comment]
Thank you for taking the time to provide us feedback. Do you have anything in particular you wish to point out to us that could be improved? If this is just an airing of your opinion, there are several other venues for doing so besides a project's bug tracker. I will close this bug report for now, but if you have anything in particular you'd wish to point out to be addressed, we can re-open.

**Comment by myRandomFiles** [comment]
> Do you have anything in particular you wish to point out to us that could be improved?

Drawing letters in a black square was easier on my Atari 520 ST in 1985 than it is in matplotlib in 2020. That's a giant bug.
