### ISSUE TITLE
Create Date Formatter/Locator Reference

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#17283]
Examples of using the date formatters and locators is currently scattered haphazardly across the docs:
* [Dates documentation](https://matplotlib.org/api/dates_api.html?highlight=dates#module-matplotlib.dates)
* [Concise Date Formatter](https://matplotlib.org/gallery/ticks_and_spines/date_concise_formatter.html#sphx-glr-gallery-ticks-and-spines-date-concise-formatter-py)
* [Date tick labels](https://matplotlib.org/gallery/text_labels_and_annotations/date.html#sphx-glr-gallery-text-labels-and-annotations-date-py) 
* [Date Demo RRule](https://matplotlib.org/gallery/ticks_and_spines/date_demo_rrule.html#sphx-glr-gallery-ticks-and-spines-date-demo-rrule-py)
* [Date Index Formatter](https://matplotlib.org/gallery/ticks_and_spines/date_index_formatter2.html#sphx-glr-gallery-ticks-and-spines-date-index-formatter2-py)
* [Date Demo Convert](https://matplotlib.org/gallery/ticks_and_spines/date_demo_convert.html#sphx-glr-gallery-ticks-and-spines-date-demo-convert-py)

There currently isn't a good reference doc for the date formatters and locators.  It would be useful to have one example that's structurally/stylistically a combination of:
* [Locators Example](https://matplotlib.org/gallery/ticks_and_spines/tick-locators.html#sphx-glr-gallery-ticks-and-spines-tick-locators-py)
* [Formatters Example](https://matplotlib.org/gallery/ticks_and_spines/tick-formatters.html#sphx-glr-gallery-ticks-and-spines-tick-formatters-py)

**Comment by arunavkonwar** [comment]
Hi, I am new here. Can I take this issue up and work on it? Thanks :)

**Comment by story645** [comment]
Go for it, any issue without an attached PR is up for grabs.

**Comment by arunavkonwar** [comment]
@story645 Hi, I am running to errors trying to build the documentation in html format. I `cd`ed into `doc/` directory and ran `make html` but being running into the following errors:

`Makefile:30: recipe for target 'html' failed`
`make: *** [html] Error 2`
`

any guidance on how to properly build the docs would be really helpful. thanks :)

**Comment by story645** [comment]
Hi, awesome that you're working on this but please direct troubleshooting questions to discourse.matplotlib.org and please provide more details like the current version of matplotlib which you are running and the output of  `make html --verbose`

**Comment by arunavkonwar** [comment]
hi @story645 , I am working on consolidating the examples you mentioned into one single page. I was wondering where should this page be placed in the overall directory? 

I realize that the docs are currently broadly placed in `doc/`, `tutorials/`, and `examples/` directories.

Thanks :)

**Comment by story645** [comment]
I'm leaning towards placing it in examples with the other formatter/locator examples.

**Comment by StefRe** [comment]
@arunavkonwar Are you still working on this one?  

if not - @story645 : is it something like this what you had in mind?
![Figure_1](https://user-images.githubusercontent.com/19879328/144475957-b32e91d9-66ad-416e-bef6-dee1176e67f4.png)  
<br><br><br>  
![Figure_2](https://user-images.githubusercontent.com/19879328/144475969-23f0ab67-1a83-4f67-91c3-90733ebeff77.png)

**Comment by story645** [comment]
@StefRe I really like it!

**Comment by StefRe** [comment]
Along with the [Date Index Formatter](https://matplotlib.org/stable/gallery/ticks/date_index_formatter2.html) example you mentioned above, there's also a [Custom tick formatter for time series](https://matplotlib.org/stable/gallery/text_labels_and_annotations/date_index_formatter.html) example. Both examples illustrate the same thing - any objections if I consolidate them into one example placed in the [Ticks section](https://matplotlib.org/stable/gallery/index.html#ticks)?

**Comment by story645** [comment]
I think that sounds fine.
