### ISSUE TITLE
Matplotlib renders square-inch frames with inconsistent sizes.

### ISSUE THREAD

**Issue by myRandomFiles** [matplotlib/matplotlib#17307]
Sometimes `figsize=(1,1)` means one thing, and other times it means another thing:

```
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(1, 1))
plt.show()

fig = plt.figure(figsize=(1, 1))
ax = fig.add_axes([0, 0, 1, 1])
ax.set_axis_off()
plt.show()
```
![matplotlib000](https://user-images.githubusercontent.com/60956662/80893214-2ce58600-8c85-11ea-8a74-ea2f861ba146.png)

**Comment by timhoffm** [comment]
The jupyter inline backend defaults to `bbox_inches: 'tight', which changes the figure size so that all plot elements are visible. You can deactivate that behavior using

~~~
%config InlineBackend.print_figure_kwargs = {'bbox_inches':None}
~~~

**Comment by myRandomFiles** [comment]
Thank you.

**Comment by myRandomFiles** [comment]
> %config InlineBackend.print_figure_kwargs = {'bbox_inches':None}

"InlineBackend" returns nothing when I search the JupyterLab documentation. Where did you learn about this? Is it specified anywhere?
