### ISSUE TITLE
how convert shape to text in .eps with matplotlib

### ISSUE THREAD

**Issue by magic01man01** [matplotlib/matplotlib#17303]
Hellow everybody
I create file type(eps) with matplotlib but thats not text in file.eps.
that is shape Instead of text(font) in file type(eps).

this is My code:

> label = ax.annotate(artext , xy=(x, y), fontsize=8, ha="center" )

**Comment by QuLogic** [comment]
I believe you need to set the `ps.fonttype` rcParam.

**Comment by dstansby** [comment]
Since this seems to have been solved I'm going to close. Feel free to comment or re-open if it hasn't been solved.
