### ISSUE TITLE
No grid for min values in polar plots

### ISSUE THREAD

**Issue by ffteja** [matplotlib/matplotlib#1730]
Grid ylines and ticks are not drawn for y <= 0 in polar plots

Ex :
![no grid for min values in polar plots](https://f.cloud.github.com/assets/3061902/118647/6ded9586-6c83-11e2-85e4-cbccb0e9c860.png)

The bug is true in matplotlib 1.1.1 and 1.2.0. Thanks.

from matplotlib.pyplot import figure, show
import numpy as np

x = np.arange(0,7,0.001)
y = np.arange(-2.0,5.0, 0.001)
fig = figure()

ax = fig.add_subplot(111, polar=True)
ax.plot(x, y)
ax.autoscale_view(True,True,True)

fig.show()
raw_input()

**Comment by ffteja** [comment]
Hi tacaswell.
Any update on the topic since?

**Comment by tacaswell** [comment]
No one (that I am aware of) has shown interest in implementing this.

The MEP has moved to http://matplotlib.org/devdocs/devel/MEP/MEP24.html / https://github.com/matplotlib/matplotlib/tree/master/doc/devel/MEP which still needs to be fleshed out.
