### ISSUE TITLE
figure background color not respected by savefig()

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#17321]
The figure background color is not respected by `savefig()`. MWE:
```python
import matplotlib.pyplot as plt

fig = plt.figure()
plt.plot([1, 2, 3], [1, 2, 3])

plt.gca().set_facecolor('#2d2d2d')
plt.gcf().patch.set_facecolor('#2d2d2d')

# plt.show()
plt.savefig("out.png")
```
show():
![out1](https://user-images.githubusercontent.com/181628/80948584-b49cd300-8df2-11ea-8c29-ba7b096c4f63.png)

savefig():
![out](https://user-images.githubusercontent.com/181628/80948592-b8c8f080-8df2-11ea-998a-c3e69e065e7c.png)

**Comment by anntzer** [comment]
I think this is basically covered by https://github.com/matplotlib/matplotlib/pull/15111?

**Comment by nschloe** [comment]
Right, duplicate of https://github.com/matplotlib/matplotlib/issues/7619.
