### ISSUE TITLE
Regression in add_subplot..

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#17343]
https://github.com/matplotlib/matplotlib/pull/16527 419fafeac34c added checks for `add_subplot` that break:

```python
import matplotlib.pyplot as plt

fig = plt.figure()

ax = fig.add_subplot(3, 4, 1)
ax2 = fig.add_subplot(3, 2, (3, 5))
plt.show()
```

### Old behaviour

![Figure_1](https://user-images.githubusercontent.com/1562854/81225095-89a2b280-8f9d-11ea-946d-80c917975612.png)

### New behaviour:

```
  ax2 = fig.add_subplot(3, 2, (3, 5))
Traceback (most recent call last):
  File "testPlots.py", line 6, in <module>
    ax2 = fig.add_subplot(3, 2, (3, 5))
  File "/Users/jklymak/matplotlib/lib/matplotlib/figure.py", line 1376, in add_subplot
    args = tuple(map(int, args))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

**Comment by jklymak** [comment]
This hasn't been released yet, so should get a fix before 3.3 goes in (or be reverted)

**Comment by story645** [comment]
did not know you could do axes spanning via add_subplot - is this a thing we want to advertise?

**Comment by jklymak** [comment]
Well, I don't think we can break it, and it seems a useful feature.  Note that this usage is also compatible with matlab's

**Comment by efiring** [comment]
This must rank among the ugliest carry-overs from the early attempt at Matlab compatibility.  Can we at least document it as such--"un-Pythonic, unreadable, not recommended"?

**Comment by jklymak** [comment]
Hmmm.  Well I don’t know if the other ways of doing the same thing are so great that this deserves so much approbation.  Making a gridspec and passing slices to add_subplot is a bit convoluted.

**Comment by timhoffm** [comment]
Wait, what?!? It took me 5 minutes to find out what `fig.add_subplot(3, 2, (3, 5))` is supposed to do. This is *far* more crazy than `subplot(325)` (personal opinion).

I wouldn't be opposed deprecating it. Apparently we did neither have documentation nor tests. But if this get's documented instead, we should note that this is for MATLAB compatibility and maybe discourage it's use. IMHO We shouldn't  judge our APIs (un-pythonic/unreadable).

**Comment by efiring** [comment]
Well, yes, I wasn't seriously proposing wording for our documentation.  I would support deprecation in some form.  I think https://github.com/matplotlib/matplotlib/pull/16603 is the basis for a better API for typical uses of add_subplot, but it doesn't include the ability of add_subplot to add one subplot at a time, potentially overlapping each other.

Maybe we need to think a little more about exactly what APIs we want to end up with in the long run.  As time goes on, Matlab compatibility becomes less useful, and more of a burden.

**Comment by jklymak** [comment]
The Matplotlib alternatives to `ax = fig.add_subplot(3, 2, (3, 5))` are:

```python
gs = fig.add_gridspec(3, 2)
ax = fig.add_subplot(gs[1:, 0])
```
or `ax = plt.subplot2grid(3, 2, (1, 0), rowspan=2, fig=fig)`.  

I substantially prefer the gridspec method of the three, but I don't consider any of them particularly awesome to justify deprecating any of them.
