### ISSUE TITLE
pie get_window_extent not correct

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#17342]
the objects returned by `pie` don't seem to have the correct bounding boxes...

```python 
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms
from matplotlib.patches import Rectangle

labels = ['Fashion', 'Theatre Literature Arts', 'Manners and Customs', 'Image of Women', 'Love', 'Idea of Man', 'Politics', 'Reason', 'Family', 'Education and Formation', 'Structure of Society', 'Image of Men']
sizes = [31, 24, 16, 14, 12, 9, 3, 2, 2, 2, 2, 2]
colors = ['#33691E', '#9768D1', '#BDC6FF', '#FC7D49', '#CD0402', '#BEDB39', '#FFF176', '#FA5B0F', '#FE4D98', '#4A148C', '#8C8C8C', '#A5FFD2']

fig, ax = plt.subplots()

pp = ax.pie(sizes, autopct=None, colors=colors, shadow=False, startangle=90, frame=True)
ax.axis('equal')
plt.draw()
p = pp[0][0]
bb = ax.transAxes.inverted().transform_bbox(p.get_window_extent())
ax.add_patch(
    Rectangle((bb.x0, bb.y0), bb.width, bb.height, linewidth=1,edgecolor='r',facecolor='none',
    transform=ax.transAxes))

fig.savefig('./TestPie.png')

```

yields:

![TestPie](https://user-images.githubusercontent.com/1562854/81216999-bbf9e300-8f90-11ea-90f0-6e1f36d90f4d.png)

The impact on `bbox_inches='tight'` is that it doesn't trim to the edge of the pie.

**Comment by QuLogic** [comment]
The objects are `matplotlib.patches.Wedge`, which does not implement `get_window_extent` itself, but defers to `Patch`'s, which returns `self.get_path().get_extents(self.get_transform())`.

AFAICT, `self.get_path()` is correct there, and even `.get_path().get_extents()` makes sense, but passing a transform gives something weird: `Bbox(x0=-415.9999549489312, y0=28.424129737030903, x1=80.00000000000003, y1=422.4)`

**Comment by QuLogic** [comment]
This took way too long to figure out, but the problem in _this example_ is that `plt.draw` is lazy. Replace it with `fig.canvas.draw()`, and the result is correct:
![TestPie](https://user-images.githubusercontent.com/302469/81258876-a9b98c80-9004-11ea-852c-04b46850c925.png)
I can't say what's wrong with tight layout.

**Comment by QuLogic** [comment]
So do you have an example for tight layout? Because this report is currently invalid.

**Comment by jklymak** [comment]
Yep sorry!  I don't understand why `plt.draw` is lazy, but whatever...
