### ISSUE TITLE
changed imshow interpolation behavior 

### ISSUE THREAD

**Issue by bbuzz31** [matplotlib/matplotlib#17345]
I'm way out of my comfort zone here so apologies in advance.

### Bug report

**Bug summary**
The latest matplotlib release (v3.2.1) seems to be handling interpolation when `Nans` are present (at the least) differently in `imshow` than the previous version. 
To achieve the same -- and correct! -- output as v3.1.2 I now have to explicitly pass `interpolation = 'none' (breaking a lot of my former code, where no `interpolation` flag was specified).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

Z = np.ones([600, 800])
Z.ravel()[np.random.choice(Z.size, 2000, replace=False)] = np.nan

fig, (axe0, axe1) = plt.subplots(figsize=(10,10), ncols=2)
c                 = axe0.imshow(Z, cmap='Greys_r')
axe0.set_title('Default interpolation')

c = axe1.imshow(Z, interpolation='none', cmap='Greys_r')
axe1.set_title("interpolation='none'")

fig.tight_layout()
plt.show()


```

**Actual outcome**

![Screen Shot 2020-05-06 at 18 16 17](https://user-images.githubusercontent.com/15522503/81233901-afdc4880-8fc5-11ea-8850-cc550864d39a.png)

**Expected outcome**
The right panel is correct and produced in v3.1.2 without passing a value to the `interpolation` flag.

**Matplotlib version**

  * Operating system: MacOS Catalina
  * Matplotlib version: 3.2.1 and 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): tested on MacOSX and Qt5
  * Python version: 3.7.6

installed via conda, conda-forge

**Comment by jklymak** [comment]
Thats correct,  and the was a purposeful change in 3.2 to reduce anti-aliasing.  If you are having to use `interpolation='none'` then you are downsampling, and interpolation='none' is randomly throwing out data bits.  In the above you are representing 600 data points in far less than 500 pixels.  To not have downsampling, you should consider setting the dpi high enough that you have over 1200 pixels.  

https://matplotlib.org/gallery/images_contours_and_fields/image_antialiasing.html#sphx-glr-gallery-images-contours-and-fields-image-antialiasing-py

**Comment by bbuzz31** [comment]
Sounds good, thanks.
