### ISSUE TITLE
Feature Request: make 'visible' available to `tick_params()`

### ISSUE THREAD

**Issue by DanielGoldfarb** [matplotlib/matplotlib#17356]
Some tick label attributes, for example `rotation`, are available to be set by either `pyplot.setp()` or by `Axes.tick_params()`.   

For example, the following, as far as I can tell, are equivalent:

    plt.setp(ax.get_xticklabels(), rotation=45)

is the same as:

    ax.tick_params(axis='x', rotation=45)
---
*However* although I can write:

    plt.setp(ax.get_xticklabels(), visible=False)

**I cannot write:**

    ax.tick_params(axis='x', visible=False)

If I do, the following exception is raised:

    ValueError: keyword visible is not recognized; valid keywords are ...
    /site-packages/matplotlib/axis.py:961: ValueError

**Is there a reason why not all attributes are available via `tick_params()`?**
**Is it possible to add `visible`?**   

Thanks.

**Comment by QuLogic** [comment]
There're more than one tick you can control via that function. The visibility is controlled by the `(label){bottom,top,left,right}` arguments.

**Comment by DanielGoldfarb** [comment]
So, to confirm, instead of

    ax.tick_params(axis='x', visible=False)

I should write

    ax.tick_params(axis='x', labelbottom=False)

Correct?   I will give that a try.

**Comment by DanielGoldfarb** [comment]
@QuLogic -  thank worked!  thanks!
