### ISSUE TITLE
`_path.get_path_collection_extents` potentially wrong return value

### ISSUE THREAD

**Issue by akhmerov** [matplotlib/matplotlib#1735]
`_path.get_path_collection_extents`, when applied to a collections with `offsets=[]` treats the offsets as if they were [0, 0](this behavior is used in path.get_paths_extents).

This interpretation of an empty collection is error-prone, and caused #1490. Hence it would be desirable to decide what should `path.get_path_collection_extents` return when given an empty collection, and have `path.get_path_extents` not rely on current behavior.

This issue is created to not lose track of the bug, while closing #1490 and merging #1497.

**Comment by oscargus** [comment]
I've rebased the PR deprecating passing an empty offset. #23200
