### ISSUE TITLE
Collections do not respect `marker=','`

### ISSUE THREAD

**Issue by brunobeltran** [matplotlib/matplotlib#17364]
### Bug report

**Bug summary**

Found this after misunderstanding a question on twitter. 

Making a plot with a single pixel at a given location is not too tricky, the pixel marker (`,`) is designed specifically for this purpose, and treated specially by `Line2D.draw`.

However, using scatter instead (where we get a collection object), the "pixel" MarkerStyle is actually many pixels wide.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot(0, 0, marker=',')  # is actually one pixel
fig, ax = plt.subplots()
ax.plot(0, 0, marker=',')  # is many pixels
```

**Actual outcome**

![plot_single_pixel](https://user-images.githubusercontent.com/1475390/81430460-4ae33880-9114-11ea-9323-23b1428c6215.png)
![scatter_single_pixel](https://user-images.githubusercontent.com/1475390/81430462-4c146580-9114-11ea-845c-bb4356350b78.png)

**Expected outcome**

Both should have markers that are a pixel wide.

**Matplotlib version**

  * Operating system: Debian Jessie
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg
  * Python version: 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries:

**Comment by brunobeltran** [comment]
Seems to have been some weird artifact of a long-running python session. Closing until I can reproduce again.

**Comment by brunobeltran** [comment]
So far, chased this down to `lines.py:843`, where we explicitly check for the pixel marker. Whereas of course a Collection's `.draw` method has no knowledge of whether a specific `MarkerStyle` was used.

**Comment by jklymak** [comment]
I think this is a duplicate?

**Comment by brunobeltran** [comment]
I'll search better, github was glitching out earlier when it tried to recommend me similar issues.

**Comment by brunobeltran** [comment]
dup of #11460
