### ISSUE TITLE
savefig and %pylab interactive are different from eachother

### ISSUE THREAD

**Issue by sorenwacker** [matplotlib/matplotlib#17368]
```
conda create -c conda-forge -n env -y python=3.8 pandas=1.0.3 scikit-learn=0.22.2 pip=20.1 matplotlib=3.2.1 seaborn=0.10.1 biopython=1.76 pyvis=0.1.7.0 jupyterlab=2.1.2 jupyterlab-git=0.20.0 ipywidgets=7.5.1 jupyter_nbextensions_configurator=0.4.1 xlrd=1.2.0 statsmodels=0.11.1 pillow=7.1.2
````

Execute this code in JupyterLab cell:

```
%pylab inline
import numpy as np
import matplotlib.pyplot as plt

figure(figsize=(3,3))
for i in range(3):
    x = np.linspace(0,10, 100)
    y = x + np.random.normal(0, 1, len(x))
    plt.plot(x, y, label=f'Plot {i}')

title('Demonstration')
xlabel('x')
ylabel('y')
legend()
grid()

tight_layout()
savefig('demo.png', dpi=300)
```

This code executed in a JupyterLab notebook produces a figure where the legend is in the upper left corner.  But the saved figure has the legend in the lower right corner.

**Comment by jklymak** [comment]
legend's position is determined automatically by default and can move around if the dpi (for instance) changes.  If you want it to stay somewhere, specify the `loc` kwarg to `legend`.

**Comment by tacaswell** [comment]
Thank you for the good report @soerendip !

```python
import numpy as np
import matplotlib.pyplot as plt

for dpi in [50, 72, 100, 200, 300]:
    fig, ax = plt.subplots(figsize=(3, 3))
    for i in range(3):
        x = np.linspace(0, 10, 100)
        y = x + np.random.normal(0, 1, len(x)) * 2
        ax.plot(x, y, label=f"Plot {i}")

    ax.set_title("Demonstration")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.legend()
    ax.grid()

    fig.tight_layout()
    fig.savefig(f"/tmp/demo{dpi=}.png", dpi=dpi)

```

With that I get the 50dpi one to be lower right and everything else to be upper left.   I suspect that this is going to also be very data dependent. The logic for picking the legend location is https://github.com/matplotlib/matplotlib/blob/b786dcdbeee9544e386a6904ff4f9e27bf6f5fc7/lib/matplotlib/legend.py#L1011-L1055 

On it's face this looks like it is working correctly, but given that the figure size is fixed and the font size is fixed, why should the dpi change the intersections?  I'm (a little bit) worried that we have some weird draw / cached size issues here with sorting out how big we expect the text to be?

**Comment by Mandeep0001** [comment]
Hi @tacaswell , Im interested in solving this issue. Can you please elaborate a little on draw/cached size issue that you mentioned above or give direction in which way to explore further?
