### ISSUE TITLE
import matplotlib.pyplot as plt failed...

### ISSUE THREAD

**Issue by eshwarkamal** [matplotlib/matplotlib#17374]
![dwe](https://user-images.githubusercontent.com/39938591/81477927-e7eac200-9237-11ea-982f-1ce3ae8b4580.PNG)
Please anyone help me

**Comment by story645** [comment]
Please post your version of matplotlib. 
```python
import matplotlib
print(matplotlib.__version__)
```

**Comment by tacaswell** [comment]
I think this is due to overlapping installations of Matplotlib so you are seeing files from multiple versions which is leading to inconsistent results.  I suggest fully uninstalling and re-installing Matplotlib.

xref https://github.com/matplotlib/matplotlib/issues/15167#issuecomment-626380188

**Comment by dstansby** [comment]
I'm going to close this since there hasn't been any response - @eshwarkamal if you still have problems feel free to re-open or leave a comment below.
