### ISSUE TITLE
Feature request: please add an argument 'label' to plt.colorbar() to set the colobar label.

### ISSUE THREAD

**Issue by soerendip** [matplotlib/matplotlib#17370]
This should be made more simple.

[Discussion](https://stackoverflow.com/questions/15908371/matplotlib-colorbars-and-its-text-labels)

Please, add a keyword that easily sets the label on the generated colorbar:

```
plt.colorbar(label='z')
```

instead of 

```
cbar = plt.colorbar()
cbar.ax.set_ylabel('z')
```

**Comment by jklymak** [comment]
Colorbar accepts a label kwarg.

**Comment by tacaswell** [comment]
Can you show us how that fails for you?

The stackoverflow question you refer to was more about putting labels inside the colorbar, not the axis label, did you mean to link to a different question on SO?

**Comment by jklymak** [comment]
I’ll close but few free to discuss if there still is a problem.
