### ISSUE TITLE
Problem using "argparse" after import of matplotlib.pyplot

### ISSUE THREAD

**Issue by BDonnot** [matplotlib/matplotlib#17379]
### Bug report

Hello,

I tried to use argparse after import matplotlib.pyplot and this causes argparse not recognizing any arguments.

**Code for reproduction**

The python code is the following:
```python
# Paste your code here
import sys
print("Number of arguments: ", len(sys.argv)) 
print("The arguments are: ", str(sys.argv))
import matplotlib.pyplot as plt
print("Number of arguments after import: ", len(sys.argv))
print("The arguments after import are: ", str(sys.argv))
import argparse
parser = argparse.ArgumentParser(description="Train baseline DDQN")
parser.add_argument("--name",
                    help="Name given to your model.")
args = parser.parse_args()
print("args.name: {}".format(args.name))
```

**Actual outcome**

And i called it from bash the following manner. And here is the output
```
> DuelQSimple$ python3 test_argparse.py --name D3QN_2
Number of arguments:  3
The arguments are:  ['test_argparse.py', '--name', 'D3QN_2']
Number of arguments after import:  1
The arguments after import are:  ['test_argparse.py']
args.name: None
```

**Expected outcome**

When i remove the line importing matplot.pyplot i got the following **correct** results

```
> DuelQSimple$ python3 test_argparse.py --name D3QN_2
Number of arguments:  3
The arguments are:  ['test_argparse.py', '--name', 'D3QN_2']
Number of arguments after import:  3
The arguments after import are:  ['test_argparse.py', '--name', 'D3QN_2']
args.name: D3QN_2

```

**Matplotlib version**

  * Operating system:
```
>~$ hostnamectl
   Static hostname: XXXXXX
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: XXXXXXX
           Boot ID: XXXXXX
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-28-generic
      Architecture: x86-64
```

  * Matplotlib version: '3.2.1'
  * Matplotlib backend (`print(matplotlib.get_backend())`): `GTK3Agg`
  * Python version: 
```
> DuelQSimple$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
  * Jupyter version (if applicable): NA
  * Other libraries: NA

Matplotlib was installed via pip with the following command:
```
> DuelQSimple$ pip3 install -U matplotlib
```

I tried to look elsewhere on the issues but couldn't find anything related to this problem.

Thanks for your help

Benjamin

**Comment by anntzer** [comment]
This is actually a bug in PyGObject, as this can be repro'd by replacing `import matplotlib.pyplot as plt` by `from gi.repository import Gtk, Gdk`.  Effecitvely, that's https://gitlab.gnome.org/GNOME/pygobject/-/issues/72.

**Comment by xdever** [comment]
I just lost 2 hours debugging this.

In case you switch the backend manually to Agg, it works.

```python
import matplotlib
matplotlib.use("agg")
import matplotlib.pyplot as plt
```

The funny thing is that if I check what ```matplotlib.get_backend()``` returns, it is agg both before and after switching.

**Comment by BDonnot** [comment]
Hello :-)

Thanks a lot for the update.

This issue arises in a package and it was not easy to make sure that in each situation the proper import was done correctly.

So instead, I managed to get it working by manually changing the backend used by default by matplotlib to use "TkAgg" instead, following these steps:
- install tkinter properly: `sudo apt-get install python3-tk` (for my ubuntu, probably similar for other linux environments)
- locate the matplotlib configuration file. From within a python "shell": 
```python
import matplotlib
matplotlib.matplotlib_fname()
```
- edit this file and setup the backend TkAgg. After edition the file looks like this:
```
# lots of stuff above
## ***************************************************************************
## * BACKENDS                                                                *
## ***************************************************************************
## The default backend.  If you omit this parameter, the first working
## backend from the following list is used:
##     MacOSX Qt5Agg Qt4Agg Gtk3Agg TkAgg WxAgg Agg
## Other choices include:
##     Qt5Cairo Qt4Cairo GTK3Cairo TkCairo WxCairo Cairo Wx
##     PS PDF SVG Template
## You can also deploy your own backend outside of matplotlib by referring to
backend : TkAgg
# lots of stuff below
```
(the last line has been modified, before modification it was simply `# backend : Agg`)

Thanks a lot for your time guys I really appreciated your help that allowed me to understand the issue and to have a "decent" fix :-)

I hope with this issue people will not spend, like you or me, couple of hours to figure out why some key words arguments of the bash script are not parsed properly in their scripts ;-)

**Comment by QuLogic** [comment]
Don't do that; it'll get overwritten on package upgrade. Use [your own personal copy](https://matplotlib.org/tutorials/introductory/customizing.html#customizing-with-matplotlibrc-files) instead.
