### ISSUE TITLE
Plotting an error band along a curve

### ISSUE THREAD

**Issue by Waljakov** [matplotlib/matplotlib#17398]
### Bug report

**Bug summary**

pyplot.fill_between(x, y1, y2) does not fill areas, where curves y1 and y2 are crossing.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

def lissajous(t):
    """Calculate Lissajous Curve"""
    x = np.cos(t)
    y = np.sin(2 * t)
    return x, y

data = np.arange(0, 2 * np.pi, 0.01)

plt.plot(*lissajous(data))
plt.fill_between(
    lissajous(data)[0], lissajous(data)[1] - 0.5, lissajous(data)[1] + 0.5, alpha=0.25
)

plt.show()
```

**Actual outcome**

![Lissajous_issue](https://user-images.githubusercontent.com/47927690/81837956-ca726c80-9545-11ea-9e3d-582b2c4d984c.png)

**Expected outcome**

![Lissajous_expected](https://user-images.githubusercontent.com/47927690/81839131-6c468900-9547-11ea-92a0-4cd0c370c399.png)

**Note**
I came across this problem while trying to use fill_between() as 'errorbars' for parametric functions. If this is not the intended use, I would be glad if someone has suggestions for a workaround.
Keep up the good work!

**Matplotlib version**

  * Operating system: Arch Linux x86_64, Kernel 5.6.11-arch1-1
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.7
  * Jupyter version (if applicable):
  * Other libraries: numpy: 1.18.1

matplotlib installed via anaconda

**Comment by QuLogic** [comment]
I don't think `fill_between` was written to interpret self-intersections. Also, our path filling code seems to always use even-odd, and there's no exposed way to change that to non-zero.

I think the only way you can do this is to split the input and avoid the cross.

**Comment by QuLogic** [comment]
And for errorbars, is that quite the best method? It only shows a vertical offset, but maybe you want those errorbars to be perpendicular to the stroke? For something like that, you could use a [path effect](https://matplotlib.org/gallery/misc/patheffect_demo.html) to add a second wider stroke underneath.

**Comment by Waljakov** [comment]
Sadly, avoiding the cross is not an option for me, because I wanted to use this for plotting x,y, uncertainty of a curve fitting that can include crossings. But maybe path effect might do the trick. 
Thank you for your help, I will give it a try.

But nonetheless I think it would be a nice feature to have a convenient option to plot (x,y)-errorbars for line-plots. I would imagine that there are a lot of use-cases, especially for plotting uncertainties of curve fittings. So maybe this is more a feature request than a bug report. 
What do you think?

**Comment by timhoffm** [comment]
We don't have many examples for parametrized curves in the x, y plane. Therefore I suppose there hasn't been particular attention to these kinds of plots and in particular not how to add error bands.

Strokes might serve as a simple approximation, but I don't think you can vary width along the stroke. Additionally, stroke width is given in points not data-space. While you can achieve the desired effect, it will be quite hacky.


For true error bands, you'd create a `PathPatch`, with two paths. For every point calculate the tangent, offest the point to +/-err and add these points to the paths.

This would actually be a nice function. However, I suppose it would still not handle crossings.

The Donut example is a simple illustration of `PathPatches`: https://matplotlib.org/devdocs/gallery/shapes_and_collections/donut.html#sphx-glr-gallery-shapes-and-collections-donut-py

**Comment by Waljakov** [comment]
I didn't notice it at first, but as you said strokes won't work for me because I need to be able to vary the width along the curve.
I also had a quick look at `PathPatches` and modified the [Donut example](https://matplotlib.org/devdocs/gallery/shapes_and_collections/donut.html#sphx-glr-gallery-shapes-and-collections-donut-py) (see *Details*). But as you already mentioned, it handles crossings the same way.

<details>

Modified [Donut example](https://matplotlib.org/devdocs/gallery/shapes_and_collections/donut.html#sphx-glr-gallery-shapes-and-collections-donut-py)

```python
import numpy as np
import matplotlib.path as mpath
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt

def lissajous(r):
    t = np.arange(0, np.pi * 2.0, 0.01)
    t = t.reshape((len(t), 1))
    x = np.cos(t)
    y = r+np.sin(2 * t)
    return x, y

Path = mpath.Path

fig, ax = plt.subplots()

inside_vertices = np.hstack((lissajous(-0.5)))
outside_vertices = np.hstack((lissajous(0.5)))

codes = np.ones(
    len(inside_vertices), dtype=mpath.Path.code_type) * mpath.Path.LINETO
codes[0] = mpath.Path.MOVETO

# Concatenate the inside and outside subpaths together, changing their
# order as needed
vertices = np.concatenate((outside_vertices[::1],
                           inside_vertices[::-1]))
# The codes will be all "LINETO" commands, except for "MOVETO"s at the
# beginning of each subpath
all_codes = np.concatenate((codes, codes))
# Create the Path object
path = mpath.Path(vertices, all_codes)
# Add plot it
patch = mpatches.PathPatch(path, edgecolor='black', alpha=0.25)
ax.add_patch(patch)
ax.plot(*lissajous(0))
plt.show()
```

![Lissajous_PathPatches](https://user-images.githubusercontent.com/47927690/81958534-7089a980-960e-11ea-8aa9-0cda282e9413.png)

</details>

**Comment by timhoffm** [comment]
~~~
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt

phi = np.linspace(0, 2.*np.pi, 80)
r = 0.5 + np.cos(phi)
x, y = r * np.cos(phi), r * np.sin(phi)
err = 0.1 * np.sin(np.linspace(0, 4*np.pi, len(x)))**2 + 0.03

fig, ax = plt.subplots()
ax.plot(x, y, 'o-')


# calculate normals via derivatives of splines
tck, u = splprep([x, y], s=0)
dx, dy = splev(u, tck, der=1)
l = np.hypot(dx, dy)
nx = dy / l
ny = -dx / l

# end points of errors
x2 = x + nx * err 
y2 = y + ny * err
x3 = x - nx * err
y3 = y - ny * err

vertices = np.block([[x2, x3[::-1]],
                     [y2, y3[::-1]]]).T
codes = mpath.Path.LINETO * np.ones(len(vertices), dtype=mpath.Path.code_type)
codes[0] = codes[len(x2)] = mpath.Path.MOVETO
path = mpath.Path(vertices, codes)

patch = mpatches.PathPatch(path, facecolor='C0', edgecolor='none', alpha=0.3)
ax.add_patch(patch)
~~~

![grafik](https://user-images.githubusercontent.com/2836374/81995169-d9dade00-9649-11ea-8f0d-397b87bacd24.png)

**Comment by Waljakov** [comment]
Thank you very much @timhoffm, I really appreciate your efforts!
I applied this method to my project and it works very well.
