### ISSUE TITLE
alpha is not set correctly when using eps format

### ISSUE THREAD

**Issue by ppurka** [matplotlib/matplotlib#1740]
Consider the following piece of code:

```
from matplotlib.figure import Figure
figure=Figure()
subplot = figure.add_subplot(111)
import matplotlib.patches as patches
p = patches.Polygon([(0,0), (1,2), (0,1), (-1,2)], fill=True, alpha=0.1)
patches.Patch.get_facecolor(p)
Out[6]: (0.0, 0.0, 1.0, 0.1)

subplot.add_patch(p)
from matplotlib.backends.backend_agg import FigureCanvasAgg
figure.set_canvas(FigureCanvasAgg(figure))
figure.savefig('a.eps')
figure.savefig('a.pdf')
```

The image `a.eps` gets a solid fill that would be obtained if we gave `alpha=1` (but `alpha=0.0` gives an empty fill, as it should). And the image `a.pdf` gets the correct alpha 0.1 fill.

**Comment by darkdragon-001** [comment]
In 764227fee8dc556b4abbf63dc88980f3b7938bce, the following warning was added

https://github.com/matplotlib/matplotlib/blob/43e7d3bbc37aee97635f011db2088e709454af7e/lib/matplotlib/backends/backend_ps.py#L783

How can I explicitly remove transparency from my figure and avoid this warning?

**Comment by tacaswell** [comment]
@darkdragon-001 To answer that we would probably have to see your code.  This question is probably best handled on the mailing list.

My complete knee-jerk guess is that you have a legend in your figure which now defaults to a semi-transparent background.
