### ISSUE TITLE
[Question] How to delete an axes?

### ISSUE THREAD

**Issue by WenyinWei** [matplotlib/matplotlib#17409]
### Question request

**Summary**
Axes.inset_axes  make a child axes. I used it to locate my color bar at a suitable place. But If I just clear the original axes, the new inset axes won't be cleared together. I am wondering if there is any way to clear them together.

**Code for reproduction**
```python
axins = inset_axes(ax,
    width="5%",  # width = 5% of parent_bbox width
    height="35%",  # height : 50%
    loc='lower right',
    borderpad=0.5)
```

**Expected outcome**
How to remove the inset axes who is a child axes to its parent axes.

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: python 3.7.5 from pip 20.0.2
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
Use `axins.remove()`.

For questions, please use [our Discourse](https://discourse.matplotlib.org/) as this issue tracker is for bug reports.
