### ISSUE TITLE
Bugged Year label when plotting time series data with Pandas dataframe

### ISSUE THREAD

**Issue by HiIamJeff** [matplotlib/matplotlib#17419]
### Bug report

**Bug summary**
Hi, I found a weird bug about Matplotlib with time-series data. I want to plot a line graph to see the data trend. However, when I use a locator function (MonthLocator()), My year label would be very weird (inconsistent year displays and strange numbers) like [this](https://imgur.com/a/nDNu1Um).

It seems like that Matplotlib has a hard time to recognize the "year" of my datetime index (Month and date label are fine).
p.s.1 If I don't use set_major_locator() and set_major_formatter() then the Matplotlib can correctly display year in the label.
p.s.2 This is the ultimate [graph](https://imgur.com/a/5IFzTyp) I plan to fix and the example below is a simple demonstration

**Code for reproduction**

```python
import pandas as pd
import matplotlib as mpl
import matplotlib.dates as dates

df = pd.DataFrame(list(zip([680, 718, 471, 686], ['200304', '200305', '200306', '200307'])), columns=['target','time'])
df_tsa = df.copy()
df_tsa.index = pd.to_datetime(df_tsa['time'], format='%Y%m').rename('Date')
ax = df_tsa['target'].plot(figsize=(12,6))
ax.xaxis.set_major_locator(dates.MonthLocator())
ax.xaxis.set_major_formatter(dates.DateFormatter("%Y-%m"))
```

**Actual outcome**
https://imgur.com/a/nDNu1Um

**Matplotlib version**

  * Operating system: Windows 10
  * Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
  * pandas version: 1.0.1
  * matplotlib version: 3.1.3 
  * Matplotlib backend: module://ipykernel.pylab.backend_inline

**Comment by jklymak** [comment]
I think pandas used completely different locators and formatters for dates.  Did you ask them about this?  Or conversely, try this without using the pandas version of plot and deregister the pandas converters?

**Comment by HiIamJeff** [comment]
Hi @jklymak, I haven't asked them because this only happens when it comes to "Year" (Month and date are good so I figured could be something with mlp). What do you mean by "deregister the pandas converters" and do you mind demoing a simple adaption with my example code? Thanks for replying!

**Comment by ImportanceOfBeingErnest** [comment]
If anything this is probably a "bug" in the pandas documentation. Pandas uses a different datetime representation in case of equally spaced time series (and does not tell users about it, it seems). 
You can use `x_compat=True` (which is "documented" [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#suppressing-tick-resolution-adjustment)), to force it to not do that - as a side effect it will also not use its own formatters/locators.

**Comment by tacaswell** [comment]
Something is going very wrong in the conversion, probably a bit on our side a bit on the Pandas side.

Pandas uses both the major and minor ticks, `ax.xaxis.set_minor_locator(mticker.NullLocator()) ` will remove "correct" labels.

To plot dates we convert the (unitful) input data to float representation of days from the epoch (which used to Jan 1 year 0 , in 3.3 will be the unix epoch), we use those (unitless) floats to plot the data, etc.  When we go to label the ticks we look at where the tick is in the unitless data and convert back to a string version of the unitful data.  For this to work the converter and the formatter need to agree on what the transforms are.  If we look at the converted data we see

```python

In [13]: plt.gca().lines[0]._xy                                                                                                                                      
Out[13]: 
array([[399., 680.],
       [400., 718.],
       [401., 471.],
       [402., 686.]])
```

which given @ImportanceOfBeingErnest noting that they use a different converter, I suspect that is an index of months from the unix epoch.

This means that if you do to use `x_compat` none of the date formatters we ship will work with the plots that Pandas produces.

----


As a side note, the minor formatter that pandas is using here is one that makes use of knowing which tick index you are on on to only show the year in the first one.

**Comment by jklymak** [comment]
> As a side note, the minor formatter that pandas is using here is one that makes use of knowing which tick index you are on on to only show the year in the first one.

See, that `loc` kwarg does come in handy :wink:

**Comment by HiIamJeff** [comment]
I see. Thanks for the in-depth explanation and the detail is kind of going over my head. I think I will find other best practices to do what I try to achieve with time-series data.

p.s. I actually tested with "x_compact=True" and it works fine for line plots. However, this doesn't work when I tried plotting bar plots. This might sound noob, but do you know any workaround to do that?
```
ax = df_tsa['target'].plot(figsize=(12,6), x_compat=True, kind='bar')
# AttributeError: Unknown property x_compat
# when I tried without x_compat, then there is no label in x-axis

```

**Comment by ImportanceOfBeingErnest** [comment]
Correct, pandas bar plots are categorical, the bars are simply at positions 0,1,2,...; therefore no datetime ticking is happening. You can use matplotlib bar plots if you need datetime-aware ticking or continue using pandas and then just impose your own ticks with `ax.set_xticks` and `ax.set_xticklabels`.

**Comment by HiIamJeff** [comment]
Ah, I get it! Thanks for your timely responses!

**Comment by AndrewBraunEE** [comment]
I was actually able to reproduce this bug on 3.0.3 of matplotlib, actually for a class, Machine Learning for Trading at GATech OMSCS.

Here's our environment:
https://lucylabs.gatech.edu/ml4t/fall2020/local-environment/

However when I upgraded to matplotlib 3.3.4, the problem went away.

My plotting code is something to the equivalent:

plt.plot(dataframe.index (just a datetime column), y_values)
...
plt.grid()
ax = plt.gca()
#Major
locator = mdates.AutoDateLocator()
Axis.set_major_locator(ax.xaxis, locator)
ax.xaxis.set_major_formatter(DateFormatter("%m/%d/%y"))
...

When plotting 2008 - 2009 matplotlib would display 1939 or 1940. I messed around a little bit with the major locator and formatter and I would also get some labels that looked like OPs.

Upgrading matplotlib resolved this issue, so probably some commit in between fixed this issue.
