### ISSUE TITLE
Document the dependency on the type1ec LaTeX package 

### ISSUE THREAD

**Issue by adeak** [matplotlib/matplotlib#17412]
I've just run into https://github.com/matplotlib/matplotlib/issues/16911. The problem is that the `type1ec` LaTeX package is necessary when `text.latex.unicode` is `True` in the `rcParams` (which is the default since 3.0). On debian this is part of the `cm-super` system package. I've had some trouble discovering this information.

  1. As of https://github.com/matplotlib/matplotlib/pull/14151 the problem is clear at least: `type1ec` is missing. (Although I got this error using a completely innocent, ascii-only, as far as I know ligature-free label in a plot. The error hadn't come up two figures earlier with other, innocent, ascii-only labels. And this is without `text.usetex`.)
  2. This LaTeX package [isn't mentioned anywhere on the matplotlib website](https://matplotlib.org/search.html?q=type1ec), and [only one closed issue](https://github.com/matplotlib/matplotlib/issues/16911) mentions it.
  3. It's not trivial to track down the appropriate debian package, fortunately the linked issue took care of this.
  4. As a side note, I read that the default for `text.latex.unicode` changed to `True` in 3.0 [here](https://github.com/matplotlib/matplotlib/pull/14151), but this is not mentioned [in the easy-to-find What's new](https://matplotlib.org/users/prev_whats_new/whats_new_3.0.html), only in the [hard-to-discover API changes](https://matplotlib.org/api/prev_api_changes/api_changes_3.0.0.html).

Ideally the dependency should be mentioned somewhere, perhaps among [the installation guide](https://matplotlib.org/users/installing.html). Currently that page mentions

> LaTeX and GhostScript (>=9.0) : for rendering text with LaTeX;

In [Text rendering with LaTeX](https://matplotlib.org/tutorials/text/usetex.html) (which focusses on `usetex`) it mentions

> On Ubuntu and Gentoo, the base texlive install does not ship with the type1cm package. You may need to install some of the extra packages to get all the goodies that come bundled with other latex distributions.

Note that `type1cm` is part of `texlive-latex-extra` which is a straightforward system package to install for LaTeX stuff, and for matplotlib in particular. However, `type1ec` is not included there, and what's worse, `apt search type1ec` doesn't turn up any resuts (unlike the same for `type1cm`).

**Comment by r0cketr1kky** [comment]
Hi @adeak , I'm currently documenting the installation procedures on all systems(Ubuntu, Debian, Windows, Conda) so I can include this dependency in the docs as you suggested :)

**Comment by adeak** [comment]
@r0cketr1kky sounds great, thanks!

**Comment by r0cketr1kky** [comment]
I've added it on my PR checklist so that I don't forget to include this :)

**Comment by marty90** [comment]
+1
