### ISSUE TITLE
Scatter produce multiple colors for a single RGB/RGBA input

### ISSUE THREAD

**Issue by MaozGelbart** [matplotlib/matplotlib#17423]
### Bug report

**Bug summary**

Scatter [docs](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.axes.Axes.scatter.html?highlight=scatter#matplotlib.axes.Axes.scatter) say that in order to provide a single RGB/RGBA color for all scatter elements, it is required to pass a 2D array with a single row for `c` argument input:

> If you want to specify the same RGB or RGBA value for all points, use a 2-D array with a single row. Otherwise, value- matching will have precedence in case of a size matching with x and y.

When x/y shape is 3 and RGB is passed as a 2D array with a single row (e.g. `c=[[1, 0.5, 0.05]]`), or when x/y shape is 4 and RGBA is passed as a 2D array with a single row, the plot elements have several different colors (taken from the default colormap?) while all should have the same color. The problem occurs for both `plt.scatter` and `ax.scatter` calls, and also if `c` input is provided as a numpy array of shape (1,3) for RGB or (1,4) for RGBA instead of a nested list. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.scatter(range(3), range(3), c=[[1, 0.5, 0.05]])
#alternatively, for RGBA scenario
plt.scatter(range(4), range(4), c=[[1, 0.5, 0.05, 1]])
```

**Actual outcome**
![840-mpl](https://user-images.githubusercontent.com/13831112/82084053-5d043e80-96f3-11ea-9d01-5b8afa216e0a.png)

**Expected outcome**
All points have the same color: RGB (1, 0.5, 0.05).

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.7.3

Matplotlib installed through pip

**Comment by story645** [comment]
This is a regression bug because it works as expected on 3.1.2
![image](https://user-images.githubusercontent.com/1300499/82088850-835cb680-96c0-11ea-8b97-49d1056b4846.png)

**Comment by QuLogic** [comment]
Bisects to 5a5c2f6ade2bb5cf92c9fde50ed07872e6b559f2, or #13959 by @efiring.

I'm not actually sure why we want to flatten `c` since the docs say "If you want to specify the same RGB or RGBA value for all points, use a 2-D array with a single row.", but it should work if `c` is the same length as `x`/`y`.

**Comment by mwaskom** [comment]
IMO this is a pretty serious regression; it makes seaborn plots wrong with no straightforward way for the user to work around it. Could it please get a release critical tag?

**Comment by tacaswell** [comment]
If you know ahead of time that you want to specify an RGG(A) color not values to be colormapped you can use the `color` kwarg which has none of the ambiguity.

See #17499 for fix.

**Comment by mwaskom** [comment]
`seaborn.scatterplot` can produce varying-color scatterplots though. It would be possible to check the shape of the color array after semantic mapping and conditionally dispatch to different matplotlib kwargs, but boy would it be messy...

**Comment by tacaswell** [comment]
We currently have that code in mpl and it _is_ rather messy (which is why it keeps breaking :/ )
