### ISSUE TITLE
artists' dimensions not considered in xlim, ylim

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#17420]
When plotting a `Circle`, much of it will be cut off by default:
```python
import matplotlib.pyplot as plt

plt.gca().set_aspect("equal")

plt.plot([-1, 1], [0, 0], "k")

circ0 = plt.Circle((0, 0), 0.5)
plt.gca().add_artist(circ0)
# plt.autoscale()  # no change

plt.show()
```
![out](https://user-images.githubusercontent.com/181628/82065398-57e0c880-96ce-11ea-949f-738086e6605c.png)

This is with
```
matplotlib.__version__
```
```
3.2.1
```

**Comment by jklymak** [comment]
Primitive artists probably should not expect to take part in autoscaling.  We may not be consistent in this, but It’s really hard to autoscale primitives in particular because we dont know what their transform is.

**Comment by ImportanceOfBeingErnest** [comment]
Use 

```
plt.gca().add_patch(circ0)
plt.autoscale()
```

**Comment by nschloe** [comment]
@ImportanceOfBeingErnest Not working.

**Comment by ImportanceOfBeingErnest** [comment]
Instead of a thumb down and a "not working", a constructive reaction would be to tell in which version you tested this and how the result looks like.

**Comment by nschloe** [comment]
@ImportanceOfBeingErnest Sorry, didn't mean to be rude. I was so plain because the suggestion changed nothing at all. Will post code with results and versions momentarily.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, `add_artist` will not change anything, that's why we have `add_patch` - which is what I suggested.

**Comment by nschloe** [comment]
Aha! I misread it. Thanks!
