### ISSUE TITLE
right click -> close plot ->Spyder crash

### ISSUE THREAD

**Issue by TomClarkMassSpec** [matplotlib/matplotlib#17429]
### Bug report

**Bug summary**

I right click -> close plot ->Spyder crash
**Code for reproduction**
Its not in my code per se. I write ##plt.hist(x_list, bins = 50, range = (0,150000))##  to generate one plot a time. I have a few plots open. I can generate using different sources and packages. I right click on any plot in upper right console window under plots tab. Drop down gives option to close plot. Spyder IDE vanishes.  oh

**Matplotlib version** 3.1.3

  * Operating system: masOS Cataline 10.15.4
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7.4
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 
from Bio import SeqIO
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Conda

Default

**Comment by timhoffm** [comment]
This sounds more like a spyder issue. At least the bug starts with an action in their code. Debugging the problem has to start there. Please report the bug to spyder.

**Comment by oscargus** [comment]
As Spyder now renders in a separate plot window by default I will close this.

Please reopen if it is not working and add details about which backend is used. (As this probably is an issue with the backend-Spyder interaction and most likely on the Spyder side.)
