### ISSUE TITLE
is_numlike

### ISSUE THREAD

**Issue by fmartin2912** [matplotlib/matplotlib#17441]
In matplotlib-documentation you write:
>=====>
cbook.is_numlike only performs an instance check
matplotlib.cbook.is_numlike now only checks that its argument is an instance of (numbers.Number, np.Number). In particular, this means that arrays are now not num-like.
<=====<

Here is what I get when I work on python-console: 
>=====>
>>> import matplotlib.cbook
>>> matplotlib.__version__
'3.2.1'
>>> dir(matplotlib.cbook)
['CallbackRegistry', 'Grouper', 'IgnoredKeywordWarning', 'MatplotlibDeprecationWarning', 'Path', 'STEP_LOOKUP_MAP', 'Stack', 'WeakMethod', '_OrderedSet', '_StrongRef', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_array_perimeter', '_check_1d', '_check_and_log_subprocess', '_check_getitem', '_check_in_list', '_check_isinstance', '_classproperty', '_combine_masks', '_dedent_regex', '_define_aliases', '_delete_parameter', '_exception_printer', '_find_dedent_regex', '_get_data_path', '_lock_path', '_lockstr', '_make_keyword_only', '_pformat_subprocess', '_premultiplied_argb32_to_unmultiplied_rgba8888', '_rename_parameter', '_reshape_2D', '_safezip_msg', '_setattr_cm', '_str_equal', '_str_lower_equal', '_suppress_matplotlib_deprecation_warning', '_to_unmasked_float_array', '_topmost_artist', '_unmultiplied_rgba8888_to_premultiplied_argb32', '_warn_external', 'boxplot_stats', 'collections', 'contextlib', 'contiguous_regions', 'dedent', 'delete_masked_points', 'deprecated', 'deprecation', 'file_requires_unicode', 'flatten', 'functools', 'get_label', 'get_realpath_and_stat', 'get_sample_data', 'glob', 'gzip', 'index_of', 'is_hashable', 'is_math_text', 'is_scalar_or_string', 'is_writable_file_like', 'iterable', 'itertools', 'local_over_kwdict', 'locale', 'ls_mapper', 'ls_mapper_r', 'matplotlib', 'maxdict', 'mplDeprecation', 'normalize_kwargs', 'np', 'numbers', 'open_file_cm', 'operator', 'os', 'print_cycles', 'pts_to_midstep', 'pts_to_poststep', 'pts_to_prestep', 're', 'report_memory', 'safe_first_element', 'safe_masked_invalid', 'safezip', 'sanitize_sequence', 'shlex', 'silent_list', 'simple_linear_interpolation', 'strip_math', 'subprocess', 'sys', 'time', 'to_filehandle', 'traceback', 'types', 'violin_stats', 'warn_deprecated', 'warnings', 'weakref']
<=====<

And obviously there is no "is_numlike". 

Is there a new version of matplotlib to be distributed? Or is there a workaround? 

Greetings
Martin

**Comment by story645** [comment]
`is_numlike` is deprecated and it's recommended that you use  `isinstance(..., numbers.Number)` instead. 
https://matplotlib.org/devdocs/api/prev_api_changes/api_changes_3.2.0/removals.html?highlight=is_numlike
