### ISSUE TITLE
%matplotlib inline called from IPython turns interactive mode off, forever and only for scripts

### ISSUE THREAD

**Issue by vincenzooo** [matplotlib/matplotlib#17454]
### Bug report

**Bug summary**

After calling `%matplotlib inline` from IPython shell, matplotlib interactive mode is turned off for  commands inside scripts and cannot be turned on again, irrespectively from the interactive status in the console.

**Code for reproduction**

```python
# <this is file test_plot3.py>
from matplotlib import pyplot as plt
from matplotlib import get_backend
print('interactive: ',plt.isinteractive())
print('backend: ',get_backend())
plt.plot([1,2,3],[2,3,4])

```

**Actual outcome**

```
<Running the shell commands from ipython console:>
In [1]: %run test_plot3.py
interactive:  False
backend:  Qt5Agg

In [2]: plt.ion()

In [3]: %matplotlib inline

In [4]: %matplotlib
Using matplotlib backend: Qt5Agg

In [5]: plt.ion()

In [6]: plt.isinteractive()
Out[6]: True

In [7]: %run test_plot3.py
interactive:  False
backend:  Qt5Agg
```

**Matplotlib version**

  * Operating system: Windows 10 Home 64 bit
  * Matplotlib version: 
In [9]: matplotlib.__version__
Out[9]: '3.2.1'
  * Python version:
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

conda with default

**Comment by tacaswell** [comment]
attn @Carreau as this may be an IPython issue (as that is where the both the `%matplotlib` and `%run` magics are defined).

**Comment by vincenzooo** [comment]
Thanks. 
If it can be interesting, I am finding some other similar odd behavior.

For example this script contains three version of same functions, two of which fail on second execution if the script is launched from IPython console with `%run`. All functions work if they are imported and called explicitly from console. 

**Code for reproduction**

<this is file demo.py>
```
import matplotlib
import matplotlib.pyplot as plt
from IPython import get_ipython

#all three work if run called from console, but 2 and 3 fail if called from __main__

def demo_display():

    """works:
    %matplotlib
    matplotlib.use()
    """

    #save current status
    be = matplotlib.get_backend()    

    #wrap and execute plot
    get_ipython().magic('matplotlib') 
    plt.plot([1,2,3],[1,-1,1])

    #restore status
    matplotlib.use(be) #this works with `matplotlib`, but not with 'matplotlib inline'

def demo_display2():
    """Fails on second run:
        %matplotlib
        plt.switch_backend()
        """
    
    #save current status
    be = matplotlib.get_backend()    

    #wrap and execute plot
    get_ipython().magic('matplotlib') 
    plt.plot([1,2,3],[1,-1,1])

    #restore status
    plt.switch_backend(be)  #this fails on second execution

def demo_display3():
    """temporarily modify  a test function with plotting commmands"""
    """Fails on second run:
        %matplotlib inline
        plt.switch_backend()
        """
        
    #save current status
    be = matplotlib.get_backend()    

    #wrap and execute plot
    get_ipython().magic('matplotlib inline') #this works well in notebook, not in ipython shell
    plt.plot([1,2,3],[1,-1,1])

    #restore status
    matplotlib.use(be) #this works with `matplotlib`, but not with 'matplotlib inline'
        
if __name__ == "__main__":

    demo_display()   #runs from console and from __main__
    #demo_display2()   #runs from __main__. runs only once from console
    #demo_display3()   #runs from __main__. runs only once from console

```

**Actual outcome**
Importing and running any of the functions in the scripts, they are executed.
If called from __main__, functions 2 and 3 are executed a first time, but fails on second execution. Error message is:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c34c2ff19293> in <module>
----> 1 get_ipython().run_line_magic('run', 'demo_display')

~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2316             with self.builtin_trap:
-> 2317                 result = fn(*args, **kwargs)
   2318             return result
   2319

<decorator-gen-60> in run(self, parameter_s, runner, file_finder)

~\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188
    189         if callable(arg):

~\Anaconda3\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    825                     else:
    826                         # regular execution
--> 827                         run()
    828
    829             if 'i' in opts:

~\Anaconda3\lib\site-packages\IPython\core\magics\execution.py in run()
    811                         def run():
    812                             runner(filename, prog_ns, prog_ns,
--> 813                                     exit_ignore=exit_ignore)
    814
    815                     if 't' in opts:

~\Anaconda3\lib\site-packages\IPython\core\pylabtools.py in mpl_execfile(fname, *where, **kw)
    182         matplotlib.interactive(is_interactive)
    183         # make rendering call now, if the user tried to do it
--> 184         if plt.draw_if_interactive.called:
    185             plt.draw()
    186             plt.draw_if_interactive.called = False

AttributeError: 'function' object has no attribute 'called'`

**Matplotlib version**

  * Operating system: Windows 10 Home 64 bit
  * Matplotlib version: 
In [9]: matplotlib.__version__
Out[9]: '3.2.1'
  * Python version:
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by tacaswell** [comment]
I have a memory of doing work on this recently, but can not find where.

**Comment by vincenzooo** [comment]
I am with matplotlib 3.7.1
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

The behavior in second post is not reproduced (it works without errors now).
The first one still behaves in the same way, Unfortunately I forgot why it was a problem.
