### ISSUE TITLE
Sould return self._facecolor3d for 3d plot.

### ISSUE THREAD

**Issue by julien-blanchon** [matplotlib/matplotlib#17450]
https://github.com/matplotlib/matplotlib/blob/6c02d680e14c12fe431d70ff83dff0f7659c59f2/lib/mpl_toolkits/mplot3d/art3d.py#L732

**Comment by QuLogic** [comment]
Is this a suggestion, a bug report, or a feature request? Please provide more context.

**Comment by dstansby** [comment]
I'm going to close this - if you can provide some more context then please feel free to re-open this issue or open a new one!
