### ISSUE TITLE
RectangleSelector fails to clear itself after being toggled inactive and then back to active.

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#17476]
### Bug report

**Bug summary**

Run examples/widgets/rectangle_selector.py.  Draw a rectangle.  Draw another rectangle: the first one is cleared out.  Toggle the selector inactive with "Q".  Toggle it back to active with "A".  Draw yet another rectangle: the second rectangle doesn't get cleared out.

**Expected outcome**

Older rectangles get cleared out regardless of whether the widget was momentarily toggled inactive previously.

**Matplotlib version**

  * Operating system: archlinux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): any
  * Python version: 38
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
Hmm, Q causes the window to close now...

**Comment by anntzer** [comment]
that was fixed in https://github.com/matplotlib/matplotlib/pull/17475.
