### ISSUE TITLE
how to set MultiCursor unvisible in a custom MultiCursor?

### ISSUE THREAD

**Issue by wangyexiang** [matplotlib/matplotlib#17505]
How to set `MultiCursor` unvisible when the `event.inaxes` is None in a custom MultiCursor?  As you can see,  the `Cursor` class will be set the cursor be unvisible when `event.inaxes != self.ax`, and how to achieve this effect in `MultiCursor `class?
**my code:**
```
import matplotlib.pyplot as plt
from matplotlib.widgets import MultiCursor
import numpy as np

class mymulticursor(MultiCursor):
    def __init__(self, canvas, axes, useblit=True, horizOn=False, vertOn=True,
                 **lineprops):
        super().__init__(canvas=canvas, axes=axes, useblit=useblit, horizOn=horizOn, vertOn=vertOn,
                         **lineprops)

    def onmove(self, event):
        if event.inaxes is None:
            for line in self.vlines + self.hlines:
                line.set_visible(False)    # this doesn't work.
            print('unvisible..')
            return
        super().onmove(event=event)

t = np.arange(0.0, 2.0, 0.01)
s1 = np.sin(2*np.pi*t)
s2 = np.sin(4*np.pi*t)
fig = plt.figure()
ax1 = fig.add_subplot(211)
ax1.plot(t, s1)

ax2 = fig.add_subplot(212, sharex=ax1)
ax2.plot(t, s2)

cursor = mymulticursor(fig.canvas, (ax1, ax2), color='r', lw=1, horizOn=True, vertOn=True)
plt.show()
```

**Matplotlib version**

  * Operating system: win 7 64bit
  * Matplotlib version: 3.2.1
  * Python version:3.7.7

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/blob/7484a86cddbbb881576377328861389a36d52361/lib/matplotlib/widgets.py#L2143-L2157

The super method you are calling sets them as visible again.

Either use the `self.visible` knob or fully re-implement `onmove`.  If you have further questions please ask them in https://discourse.matplotlib.org.

I am going to close this as I do not think there is any action to be taken at the library level.

Sorry this fell trough the cracks for 3 years...
