### ISSUE TITLE
Quadmesh.set_array should validate dimensions

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#17508]
#16908 has added the ability to call `Quadmesh.set_array` with a 2-D argument.
When a Quadmesh is instantiated, its grid of vertices is fixed.  It would be good to
have `set_array` validate its argument so that regardless of whether it has already
been flattened or whether it is a 2-D array such as one would supply to `pcolormesh`,
its dimensions are consistent with the dimensions of the vertex grid.

**Comment by tacaswell** [comment]
This is a good first issue because it does not require changes to the public API, but medium difficulty because it does involve adding a bit of state to the Artist and working through the history / variety of data shapes that can be passed in to determine what we need to check against.

**Comment by WGussev** [comment]
@tacaswell 
Hello, I'd like to work on the issue. It's my first contribution, so I'd like to ask, what is the workflow? fork -> create new branch (form which one) -> make changes -> open a PR :sweat_smile:

**Comment by timhoffm** [comment]
These may help:
https://matplotlib.org/devdocs/devel/contributing.html#contributing-code
https://matplotlib.org/devdocs/devel/coding_guide.html#pull-request-guidelines

**Comment by petor-traffs** [comment]
Hello!! I'm looking to make my first contribution in an Open Source project! I was wondering if this issue is still available. If so, is there anything I could start with? Thank you in advance!

**Comment by dopplershift** [comment]
The issue is still open and there aren't any linked Pull Requests, so have at it!

**Comment by jeffreypaul15** [comment]
From what I understand, `set_array` needs to validate it's arguments if it has been flattened or is still a 2D array. Am I missing anything out anything else?
