### ISSUE TITLE
dict unpacking broken for `.plot` in 3.2

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#17502]
Edited this issue about 14 times, here is the minimal works/doesn't:

## Works:
```python
d = {4:1, 6:2}
plt.bar(d.keys(), d.values())
```
## doesn't work
```python
d = {4:1, 6:2}
plt.plot(d.keys(), d.values())
```
doesn't work as of '3.2.1.post2558.dev0+geeeafe9c2' & support for this was added in #6787

**Comment by jklymak** [comment]
Bisects to 2445465c3fca611a3

**Comment by story645** [comment]
@jklymak thanks for finding that, was unsure where to start on the debugging. And yeah, though not sure where to put them - there's preprocess data tests but they mock out the plot calls. But I guess can throw an integration test in there...

Also how do you bisect?

**Comment by jklymak** [comment]
Git bisect.  Very helpful tool if you know something used to work!

**Comment by story645** [comment]
thanks! and figured I can shove the tests into units since that's where the issue happens 😅
