### ISSUE TITLE
The markers are not hollow when I use ax.scatter() and set markers.MarkerStyle()'s fillstyle to 'none'. My usage is wrong?

### ISSUE THREAD

**Issue by NoahFeng** [matplotlib/matplotlib#17527]
I want to set markers hollow. So I make a costomed `markers.MarkerStyle` and set the paramter `fillstyle='none'`. But I don't get what I want.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from matplotlib import markers
import numpy as np
xy = np.random.rand(10, 2)
fig, ax = plt.subplots()
style = markers.MarkerStyle(marker='o', fillstyle='none')
ax.scatter(xy[:, 0], xy[:, 1], marker=style)
plt.show()
```

**Actual outcome**

![Snipaste_2020-05-28_18-17-01](https://user-images.githubusercontent.com/28953763/83129663-b87cf600-a10f-11ea-917e-a2aa4e084bd1.PNG)

**Expected outcome**
This is what I want.
![Snipaste_2020-05-28_18-20-13](https://user-images.githubusercontent.com/28953763/83129794-e95d2b00-a10f-11ea-92ff-d293503dd84a.PNG)

When I check out the source code about the [matplotlib.markers.MarkerStyle](https://matplotlib.org/3.2.1/_modules/matplotlib/markers.html#MarkerStyle), I find:
![Snipaste_2020-05-28_18-27-40](https://user-images.githubusercontent.com/28953763/83130501-f890a880-a110-11ea-93ab-2458eb7a521c.PNG)
It seems that it doesn't process `fillstyle='none'`.
I don't know why. Maybe my usage is wrong. Could anyone help me?

**Matplotlib version**

  * Operating system: Win10
  * Matplotlib version: 3.1.1
  * Python version: 3.6.6

**Comment by timhoffm** [comment]
This is indeed a bug - `fillstyle='none' was not respected by `scatter()`.

**Workarounds**
- If you don't need specific `scatter()` properties (like varying color or size) the simplest appoach is using `plot()`:
  ~~~
  ax.plot(xy[:, 0], xy[:, 1], 'o', markerfacecolor='none')
  ~~~

- For `scatter()` you can directly define the properties as keyword arguments:
  ~~~
  ax.scatter(xy[:, 0], xy[:, 1], marker='o', facecolors='none', edgecolors='C0')
  ~~~
