### ISSUE TITLE
Z-order of the gridlines from the top axis cannot be set

### ISSUE THREAD

**Issue by mohammadsamani** [matplotlib/matplotlib#17528]
### Bug report

**Bug summary**

The gridlines from the top axis ignore the zorder and they appear on top of everything, including the plotted data and the legends. I played with setting zorders to different values. Also tried set_axisbelow(True) to no avail.

**Code for reproduction**

```python
fig, ax = plt.subplots()
x = np.linspace(0,1,101)
ax.plot(x, x, 'o', label='Very linear data')
ax.legend().set_zorder(5)
axtop = ax.twiny()
ax.set_axisbelow(True)
axtop.set_axisbelow(True)
axtop.grid(zorder=-1)
```
**Actual outcome**
![image](https://user-images.githubusercontent.com/21316940/83137022-b2bfea00-a0e8-11ea-9530-4276cc911eec.png)

**Matplotlib version**

  * Operating system: Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
  * Matplotlib version: 3.0.3
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
  * Jupyter version (if applicable): Jupyter Hub 4.4.0

**Comment by jklymak** [comment]
The second axes is drawn after the first and zorder is by axes so everything in the second axes will be above everything in the first.

**Comment by mohammadsamani** [comment]
Thanks for the explanation. Is there a way to fix that? I want the gridlines from top to be under the data points and legends.

**Comment by mohammadsamani** [comment]
I guess one could change the order in which the axes are created, as a work-around:

```fig, ax = plt.subplots()
ax.grid()
axb = ax.twiny()
axb.xaxis.tick_bottom()
x = np.linspace(0,1,101)
axb.plot(x, x, 'o', label='Very linear data')
axb.legend()
ax.xaxis.tick_top()
```
Annoying, but it works.

![image](https://user-images.githubusercontent.com/21316940/83162475-19093480-a10a-11ea-9665-fbe587d5e337.png)

**Comment by jklymak** [comment]
We could *probably* expose the order of axes: its just a list, but we don't...

**Comment by jklymak** [comment]
Oh, we do.  the `zorder` of the axes is respected but you have to make the mani axes have no background color:

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
x = np.linspace(0,1,101)
ax.plot(x, x, 'o', label='Very linear data')
ax.legend().set_zorder(5)
ax.set_facecolor('none')

axtop = ax.twiny()
axtop.grid()
axtop.set_zorder(-1)

plt.show()
```

**Comment by jklymak** [comment]
I'll close, because I don't think we can get into the business of having z-orders between axes.
