### ISSUE TITLE
hat graphs need an example...

### ISSUE THREAD

**Issue by zerothi** [matplotlib/matplotlib#17537]
New plot format.

It would be really cool if matplotlib also support hat graphs.

They are a small difference from `bar` plots by removing the baseline part of the bar's.
See here for details:
https://cognitiveresearchjournal.springeropen.com/articles/10.1186/s41235-019-0182-3

**Comment by jklymak** [comment]
This would need a relatively specialized API.  At first glance it seems most appropriate to an external library.

**Comment by QuLogic** [comment]
I didn't read the whole paper, but if all it is is starting the bars at some other baseline, then this can be achieved using the `bottom` keyword argument:
```python
import matplotlib.pyplot as plt
import numpy as np


labels = ['A', 'B']
result1 = np.array([3, 2.7])
result2 = np.array([4, 5.5])

x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, np.zeros_like(result1), width,
                bottom=result1, fill=False)
rects2 = ax.bar(x + width/2, result2 - result1, width,
                bottom=result1, fill=False)

ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_xlabel('Treatment')
ax.set_ylim(bottom=0)
ax.set_ylabel('Score')

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/302469/83315037-6e694280-a1eb-11ea-957a-5a7f1e69766e.png)

**Comment by timhoffm** [comment]
We could add an example for that to the gallery. @zerothi would you be interested in writing one and opening a pull request?

**Comment by zerothi** [comment]
I would be happy to do this (at some point) ;)
It may take some time until I get familiar with your gallery!

**Comment by timhoffm** [comment]
👍 Feel free to ask for guidance if needed.

**Comment by timhoffm** [comment]
## 👉 Task

- Write an an example. You may start from @QuLogic's code https://github.com/matplotlib/matplotlib/issues/17537#issuecomment-636247193

**Comment by anushkrishnav** [comment]
I would like to work on it . But this is my first time . Would need some guidance and help @timhoffm

**Comment by timhoffm** [comment]
@anushkrishnav Sorry, I don't have the time to guide you in detail. See the the documentation on [contributing documentation](https://matplotlib.org/devdocs/devel/contributing.html#contributing-documentation).

**Comment by adityakuppa26** [comment]
@timhoffm @zerothi Should a new section be created altogether under the examples for hat graphs or should it be under the bar graph section of examples?

**Comment by timhoffm** [comment]
Go for examples/lines_bars_and_markers

**Comment by zerothi** [comment]
@anushkrishnav thanks for taking this up! :+1:

**Comment by anushkrishnav** [comment]
> @anushkrishnav thanks for taking this up!

I am almost done . First time contributor so trying to figure stuff out.

**Comment by QuLogic** [comment]
Added in #18205.
