### ISSUE TITLE
Markers of some types are not drawn in the custom legend

### ISSUE THREAD

**Issue by evgenykurbatov** [matplotlib/matplotlib#17554]
### Bug report

I tried to use the `Line2D` class to make a custom legend, like in [example](https://matplotlib.org/3.2.1/gallery/text_labels_and_annotations/custom_legends.html). The marker of types 'o', 's', and '*' (and maybe some others) are drawn with a specified color, but 'x' and some others are drawn with white. It is seen as the white strokes on the legend box (see the sample code).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

fig, ax = plt.subplots()
custom = [ Line2D([], [], marker='x', color='w', label='Fail',
                  markerfacecolor='g', markersize=25) ]
#custom[0].set_marker('x')    ## Direct setting of the marker type doesn't help
ax.legend(handles=custom)
plt.show()
#plt.savefig('markers-issue.eps')
```

**Software**
  * Operating system: Debian 10, Ubuntu 16.04
  * Matplotlib version: 3.1.3
  * Matplotlib backend: Qt5Agg, EPS
  * Python version: 3.7.5
  * Conda version: 4.8.3

I'm using conda v.4.8.3 installed from the official site to $HOME/opt.

**Comment by QuLogic** [comment]
The 'x' marker is not filled and comprised entirely of edges. You need to set `markeredgecolor` if you want to override `color` for it.

**Comment by evgenykurbatov** [comment]
В Tue, 02 Jun 2020 23:06:28 -0700
Elliott Sales de Andrade <notifications@github.com> пишет:

> The 'x' marker is not filled and comprised entirely of edges. You
> need to set `markeredgecolor` if you want to override `color` for it.
> 

Damn. I've already forked the Matplotlib to fix this 'bug'.
Thanks!

**Comment by jseabold** [comment]
For anyone else coming across this, you might also need to set `markeredgewidth` to get it to show up.
