### ISSUE TITLE
Make well-adjusted colorbars the default (in my own workspace)

### ISSUE THREAD

**Issue by LauraOlivera** [matplotlib/matplotlib#17559]
Hi, I hope this is not a repeated issue: I searched keywords and couldn't find anything, but maybe I missed it, as there are many issues.
### Question

Essentially I was wondering if there is anyway to make "nice" colorbar placement the **default** in any way. I have been playing with custom mplstyles but I can't find a way to solve this. I need this to be irregardless of the figsize (I know that for the default figsize, the colorbar actually looks alright, but I usually need larger figures)

**Current default**

Right now for any figsize different than the default, the colorbar does not look well adjusted with the main plot. Using tight_layout or constrained_layout doesn't make it better. 

**Simple example of current outcome**

```python
import matplotlib.pyplot as plt
import numpy as np
data = np.random.randn(50,50)
fig = plt.figure(figsize=(10,10))
plt.imshow(data)
plt.xlabel('test x')
plt.ylabel('test y')
plt.title('test title')
plt.colorbar()
plt.show()
```

![image](https://user-images.githubusercontent.com/22521727/83666039-9cc09680-a5cc-11ea-9cd7-72aed3c7faf1.png)

**Desired default behaviour**

So what I always end up doing is this
```
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.axes_grid1 import make_axes_locatable
data = np.random.randn(50,50)
fig = plt.figure(figsize=(10,10))
ax = plt.gca()
im = plt.imshow(data)
plt.xlabel('test x')
plt.ylabel('test y')
plt.title('test title')
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
cbar = plt.colorbar(im, cax=cax)
plt.show()
```
which results in this

![image](https://user-images.githubusercontent.com/22521727/83666556-66cfe200-a5cd-11ea-87ca-2c7960d91c3d.png)

But given that I pretty much **never** want the first behaviour, I would like to somehow make the second one the default. Is this even possible? If so, what would be the best way?? Is it possible to modify colorbar settings through styles?

Just to clarify I am not asking for this to be changed in general, but for instructions on how to make it the default for **my install** (maybe through custom styles and such).

Thanks in advance

**Matplotlib version 3.2.1 ** 

  * Operating system: Ubuntu 18.04.4
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.3
  * Matplotlib installed through conda-forge

**Comment by jklymak** [comment]
The issue here is that `plt.imshow` defaults to `ax.set_aspect(1.0)`.  This shrinks the axes in the long dimension and the colorbar gets left behind. 

We are working on a general fix to this, but its not ready yet.  There is no way to make the divider method default, but you could easily write your own wrapper if you like that method.

**Comment by LauraOlivera** [comment]
Thank you for your quick reply. I will just do that then.
