### ISSUE TITLE
Text Rotation Relative To Line is broken

### ISSUE THREAD

**Issue by Mark-BC** [matplotlib/matplotlib#17571]
### Bug report

**Bug summary**

The example code to demonstrate how to rotate text is broken as of version 3.2.0.  Either a bug has been introduced into matplotlib or the API has changed and the demo code is obsolete.

**Code for reproduction**

Please compare  the result of the following two identical pages of code:

[https://matplotlib.org/3.1.3/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html](url)

[https://matplotlib.org/3.2.0/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html](url)

The pages are identical, but the code has different results.

**Actual outcome**

The improperly rotated text, in the second link above and in the latest version matplotlib v3.2.1

**Expected outcome**

The matplotlib v3.1.3 link above shows the expected, correct output.

**Matplotlib version**

  * Operating system:  N/A
  * Matplotlib version:  3.2.0 and newer
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: N/A
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

**Comment by anntzer** [comment]
This is already tracked at https://github.com/matplotlib/matplotlib/issues/17005.  Thanks for the report.
