### ISSUE TITLE
Vertical alignment of tick labels containing minus in font size other than 10 with usetex=True

### ISSUE THREAD

**Issue by adambrown1** [matplotlib/matplotlib#17574]
### Bug report

**Bug summary**

When TeX is used to typset text, minus signs cause a vertical offset in tick labels for certain font sizes. This is related to #6323, which was fixed but only for given font sizes.

The problem with the fix in #16366 seems to be that it looks for character 0 in font "cmsy10". I am not an expert, but I think the 10 refers to the font size, and for example "cmsy8" is used for 8 pt font.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
fig = plt.figure(dpi=300)
plt.rc('text', usetex=True)
ax = fig.add_subplot(1,2,1)
plt.plot((-7.,0.,7.), (-1.,0.,1.), 'r-')
plt.rc('text', usetex=True)
ax = fig.add_subplot(1,2,2)
plt.plot((-7.,0.,7.), (-1.,0.,1.), 'r-')
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()
```

**Outcome**

![bad_minus_size_8](https://user-images.githubusercontent.com/22192046/83796550-791b5000-a6a1-11ea-92e0-7b030521876c.png)

On the left (font size 10) axis labels are correctly aligned are whereas on the right (font size 8) those labels which contain a minus sign are noticably lower.

**Matplotlib version**
  * Operating system: mac OS 10.15.4
  * Matplotlib version: 3.2.1 (installed using pip, with #16366 manually applied)
  * Matplotlib backend `module://ipykernel.pylab.backend_inline`:
  * Python version: 3.7.1
  * Jupyter version (if applicable): 4.4.0

**Comment by anntzer** [comment]
Changing the check to match any `cmsy\d+` seems reasonable, do you want to make a PR?

**Comment by jkseppan** [comment]
Another solution could be to add `\vphantom{-}` to the beginning of all tick labels when usetex is enabled.
