### ISSUE TITLE
StopIteration fall inside FuncAnimation

### ISSUE THREAD

**Issue by OlegWorld** [matplotlib/matplotlib#17570]
Found out that this code:

```
import matplotlib.pyplot as plt
import matplotlib.animation as animation


def update(coordinates):
    return [plt.scatter(x=coordinates[0], y=coordinates[1])]


if __name__ == '__main__':
    gen = ((i, i) for i in range(10))

    fig = plt.figure()
    ani = animation.FuncAnimation(fig, update, frames=gen)
    plt.show()
```

falls with the following traceback:
```
Traceback (most recent call last):
  File "/home/oleg/anaconda3/envs/raf/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "/home/oleg/anaconda3/envs/raf/lib/python3.8/site-packages/matplotlib/animation.py", line 1449, in _step
    self._init_draw()
  File "/home/oleg/anaconda3/envs/raf/lib/python3.8/site-packages/matplotlib/animation.py", line 1732, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
StopIteration
```

I may be wrong, but i think, that it should work fine?

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Backend Qt5Agg is interactive backend. Turning interactive mode on.
Qt5Agg
  * Python version: 3.8
  * Jupyter version (if applicable): -
  * Other libraries: -

**Comment by tacaswell** [comment]
Can you try with mpl 3.2?  This works without raising on something very close to the current master branch.

------

As written this may look right, but is probably not doing what you want.  The code creating a new Artist every time through the update function (when you call `plt.scatter`) that have 1 point in it.  If you loop through the generator more than once the artists will start to overlap and drawing will get slower and slower.

Instead you want to create the artists once up front and then use `sc.set_offlets` to update the x/y positions with the new data.

**Comment by tacaswell** [comment]
This works ~correctly (but warns about us guessing the cache wrong). 

My previous comments about this "working" but not doing what is wanted still stand.
