### ISSUE TITLE
Linter complains about unexpected data-type, however, docs say this is possible 

### ISSUE THREAD

**Issue by kernelizd** [matplotlib/matplotlib#17583]
### Bug report
With respect to `FuncAnimation`, when you pass to `frame` a function generator, the linter complains. The function works seamlessly, but the linter keeps complaining. If you could fix the docs so that a generator is also expected, just like FuncAnimation documentation says.

**Bug summary**
Please look at the linter

![image](https://user-images.githubusercontent.com/46288868/83939156-e8b64a00-a81d-11ea-8851-5f133077f34c.png)

**Code for reproduction**
Any FuncAnimation with the frame argument being a generator.

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by QuLogic** [comment]
Matplotlib does not declare _any_ types. If your linter is complaining, it seems a problem with your linter.

**Comment by QuLogic** [comment]
As a note, Matplotlib 3.8 will have type hints, and I believe that should guide your linter into allowing the right things now.
