### ISSUE TITLE
y limit with dashed or dotted lines hangs with somewhat big data

### ISSUE THREAD

**Issue by fmder** [matplotlib/matplotlib#1758]
When plotting uncontinuous lines and rescaling the y axis to centre the view on some part of the data matplotlib hangs in the show() function forcing me to kill the process.

How to reproduce the bug: 

```python

import matplotlib.pyplot as plt
import numpy
a = 2**numpy.arange(0, 50)
plt.plot(a, "--")
plt.ylim([0, 100])
plt.show()
```

This does work perfectly with a continuous line or when the data is smaller and uncontinuous lines.
I use matplotlib 1.2.0 on OSX 10.7.5 and I have Python 2.7.3 installed as a famework (with homebrew).

**Comment by efiring** [comment]
Closed by #6178.
