### ISSUE TITLE
Master doc builds broken

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#17595]
DOC builds fail across PRs with

~~~
/home/circleci/project/lib/mpl_toolkits/axisartist/axis_artist.py:docstring of mpl_toolkits.axisartist.axis_artist.BezierPath.__init__:57: WARNING: py:meth reference target not found: set_linestyle
/home/circleci/project/lib/mpl_toolkits/axisartist/axis_artist.py:docstring of mpl_toolkits.axisartist.axis_artist.BezierPath.__init__:57: WARNING: py:meth reference target not found: set_marker
/home/circleci/project/lib/mpl_toolkits/axisartist/axis_artist.py:docstring of mpl_toolkits.axisartist.axis_artist.BezierPath.__init__:57: WARNING: py:meth reference target not found: set_drawstyle
~~~

Maybe related to #17587. I don‘t see how exactly that could cause the error, but that recently changed BezierPath. If so, needs backporting as well.

**Comment by tacaswell** [comment]
I think master branch is fixed again, however circle runs the doc build on the tip of the PR branch not an the proposed merge commit (like travis does) so any PRs opened before #17487 landed are going to have the failure or need a rebase.
