### ISSUE TITLE
Axis auto scaling resulting in unituitive and misleading output

### ISSUE THREAD

**Issue by Peppershaker** [matplotlib/matplotlib#17626]
Summary
When large, uniform numbers are plotted, the Y axis auto scales or formats to make it more readable, however, at times this makes the output incredibly misleading.

### Bug report

**Reproduction**
```
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(1,1001)
y = np.ones(1000) * 2.6 * 10 **6
plt.scatter(x=x, y=y)
```

**Actual outcome**
![Annotation 2020-06-13 014546](https://user-images.githubusercontent.com/15576531/84563422-b5415700-ad18-11ea-89fa-2109884801d8.jpg)

**Expected outcome**
The y axis should be vertically centered on 2.6, not 0

**Matplotlib version**
  * Operating system: Windows, Anaconda
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.1
 

Please tell us how you installed matplotlib and python e.g., from source, pip, conda
Conda

If you installed from conda, please specify which channel you used if not the default
Default

**Comment by timhoffm** [comment]
This is the offset notation. The pending #17604 improves the documentation; preview: https://38549-1385122-gh.circle-artifacts.com/0/doc/build/html/api/ticker_api.html?highlight=scalarformatter#matplotlib.ticker.ScalarFormatter. You can control the behavior via ˋ rcParams["axes.formatter.useoffset"]ˋ.

**Comment by Peppershaker** [comment]
ok thank you
