### ISSUE TITLE
Use of Python deprecated APIs.

### ISSUE THREAD

**Issue by methane** [matplotlib/matplotlib#17629]
See here.

https://github.com/matplotlib/matplotlib/blob/f80d56e69ba2b8a583540c75f1bf8494738839cc/src/ft2font_wrapper.cpp#L638-L640

PyUnicode_GET_SIZE, PyUnicode_AsUnicode, and Py_UNICODE are deprecated.
We are planning to remove them in Python 3.11.

Please replace them with PyUnicode_GET_LENGTH, PyUnicode_READ, and Py_UCS4.

**Comment by tacaswell** [comment]
Is there a way to make the deprecations fatal at compile time?
