### ISSUE TITLE
Stackplot fails for small numbers

### ISSUE THREAD

**Issue by svaberg** [matplotlib/matplotlib#17633]
### Bug report

**Bug summary**

It appears that `stackplot` fails for small numbers in version 3.2.1, or at least something goes wrong in my clean installation, see figures below.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x =  [0, 1]
y1 = 1e-8*np.ones_like(x)
y2 = 1e-9*np.ones_like(x)

fig, axs = plt.subplots(2, 1)
axs[0].stackplot(x, y1, y2)  # This plot is fine
axs[1].stackplot(x, y1/10, y2/10)  # This plot is wrong
plt.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/3267619/84637648-4d1d8b80-af39-11ea-8f33-624ef07089e6.png)
Something went wrong in the second subplot.

**Expected outcome**
Expected this, as generated with `matplotlib` version 3.1.2
![mpl312](https://user-images.githubusercontent.com/3267619/84637520-219aa100-af39-11ea-8319-e9166e6d9f64.png)

**Matplotlib version**

  * Operating system: macOS 10.12.6 (Sierra)
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.3

Created a conda environment with only the`numpy` package, then installed matplotlib with `pip`.

**Comment by jklymak** [comment]
Bisects to 0911f8abe, https://github.com/matplotlib/matplotlib/pull/13980  ping @anntzer
