### ISSUE TITLE
I am trying to plot 1 -d plot for iris data set but its not showing blank plot 

### ISSUE THREAD

**Issue by mi44164** [matplotlib/matplotlib#17631]
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
#sns.set_style("whitegrid");
iris_setosa = iris.loc[iris["Species"] == "setosa"];
iris_virginica = iris.loc[iris["Species"] == "verginica"];
iris_versicolor = iris.loc[iris["Species"] == "versicolor"];

plt.plot(iris_setosa['Petal_length'],np.zeros_like(iris_setosa['Petal_length']),'o',label='setosa')
plt.plot(iris_virginica['Petal_length'],np.zeros_like(iris_virginica['Petal_length']),'o',label='virginica')
plt.plot(iris_versicolor['Petal_length'],np.zeros_like(iris_versicolor['Petal_length']),'o',label='versicolor')
#plt.grid()
plt.xlabel= ('Petal_length')
plt.legend()
plt.show()

**Comment by tacaswell** [comment]
This example does not say where `iris` comes from and these keys don't match the iris set from seaborn.  Can you provide us with a copy-paste-runable example that shows the problem?

**Comment by mi44164** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/64636868/84986248-d7036980-b170-11ea-819e-19cc2173add6.png)
![Screenshot (2)](https://user-images.githubusercontent.com/64636868/84986269-dff43b00-b170-




here
here
11ea-80a6-5f275fa89ad2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/64636868/84986282-e5518580-b170-11ea-9605-dada75e500de.png)
![Screenshot (4)](https://user-images.githubusercontent.com/64636868/84986291-eb476680-b170-11ea-8632-826e3adbc453.png)
![Screenshot (5)](https://user-images.githubusercontent.com/64636868/84986304-f0a4b100-b170-11ea-9476-f13c542267de.png)



Here Attached all the screenshot with code.


I didn't get this point **" Can you provide us with a copy-paste-runable example that shows the problem?"**

**Comment by mi44164** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/64636868/84986849-cf909000-b171-11ea-9836-867887ab48b6.png)
![Screenshot (7)](https://user-images.githubusercontent.com/64636868/84986852-d0c1bd00-b171-11ea-8f83-7aa762d52994.png)
![Screenshot (8)](https://user-images.githubusercontent.com/64636868/84986854-d15a5380-b171-11ea-97ec-9ca5ee392104.png)
![Screenshot (9)](https://user-images.githubusercontent.com/64636868/84986856-d1f2ea00-b171-11ea-9ee4-4b38339b64a1.png)
![Screenshot (10)](https://user-images.githubusercontent.com/64636868/84986857-d1f2ea00-b171-11ea-998e-46d5d69bd984.png)




**The below screenshot the picture code shows me an error because in the output the graph shows only the blank graph with the white grid instead of some observation point on the plot.**
![Screenshot (11)](https://user-images.githubusercontent.com/64636868/84986859-d28b8080-b171-11ea-81c3-b99fea11eabe.png)

**Comment by QuLogic** [comment]
The species names are `Iris-*` (see second screenshot); you are plotting an empty DataFrame.
