### ISSUE TITLE
Changing the application name (not window title!)

### ISSUE THREAD

**Issue by TravelTrader** [matplotlib/matplotlib#17630]
I am running matplotlib on Ubuntu 18.04.
And of course, I know how to change the title of the graph and the title of the window.
But what about the application name?

I mean the name - always 'Matplotlib' - below the icon when a pyplot graph was created by a python code and I switch my open applications by ALT+^ (in gnome/Ubuntu).

Because _**I am using codes with several charts and they are open at the same time and over some hours. To watch them I would like to name them to find them faster.**_

So, to say it shortly:
**How can I change the application name from 'Matplotlib' to anything else?**

Thanks a lot and greetings from a fan of your library!

**Comment by tacaswell** [comment]
The exact details will depend on which GUI details you are using.  You will need to either create the core "Application" object for the framework (ex `QApplication`) with your name of choice before importing Matplotlib or use the GUI framework to change the title (ex https://stackoverflow.com/questions/13291310/qt-application-title).  I don't think we have a framework agnostic API for for this in Matplotlib.

**Comment by anntzer** [comment]
> I don't think we have a framework agnostic API for for this in Matplotlib.

I very much think we should not have such an API.

**Comment by anntzer** [comment]
Let's close this as wontfix, given that @timhoffm agrees.
