### ISSUE TITLE
Cannot copy LinearSegmentedColormap

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#17634]
### Bug report

**Bug summary**

On current master, trying to do `set_bad()` on a globally registered colormap raises a deprecation warning:
```
MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = mpl.cm.get_cmap(gray).copy()
```

If the colormap is a `LinearSegmentedColormap` it's not possible to copy it though, and trying to raises this error:
```
  File "test.py", line 6, in <module>
    gray.copy()
AttributeError: 'LinearSegmentedColormap' object has no attribute 'copy'
```

**Code for reproduction**

```python
import matplotlib.cm as cm

gray = cm.get_cmap('gray')
# Next line raises a warning
gray.set_bad(color='red')
# Next line raises an exception
gray = gray.copy()
```

**Matplotlib version**

  * Operating system: macos
  * Matplotlib version: 3.2.1.post2858+gc3bfeb9c3 installed from source
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by greglucas** [comment]
Good catch, sorry about that! I think I must have added a `copy()` function in one of my future planning PRs and forgot about this here. I made the simple fix in the new PR by updating the documentation which hopefully helps clarify this.

**Comment by tacaswell** [comment]
Thanks for the quick response @greglucas !
