### ISSUE TITLE
NEP 29 : Stop support fro Python 3.6 soon ?

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#17652]
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) numpy/numpy#14086 suggest dropping Python 3.6 support soon.  Matplotlib is a co-signer.

Dask is [considering it](https://github.com/dask/community/issues/66), will matplotlib consider following nep 29 and remove Python 3.6 from official support?

**Comment by Carreau** [comment]
cc @tacaswell

**Comment by QuLogic** [comment]
After 3.3, I believe.

**Comment by timhoffm** [comment]
Yes. See also https://matplotlib.org/devdocs/devel/min_dep_policy.html#python-and-numpy

**Comment by tacaswell** [comment]
Yes, as soon as we get the 3.3RC1 tagged and a v3.3.x branch going we should drop py36 on CI and on the master branch.
