### ISSUE TITLE
FiveThirtyEight plot style not working

### ISSUE THREAD

**Issue by RafeyIqbalRahman** [matplotlib/matplotlib#17650]
### Bug report

**Bug summary**

The FiveThirtyEight plot style is not working in a particular case. I've also imported the Matplotlib patches but that doesn't seem to work as well.

**Code for reproduction**

The following code will run after uploading the .xlsx file provided at the end of the issue, in the IDE.
```
import matplotlib.pyplot as plt
from matplotlib import patches
plt.style.use('fivethirtyeight')
from numpy import linspace, min, max
from sklearn.ensemble import IsolationForest
from pandas import DataFrame, read_excel
from io import BytesIO
from google.colab import files
uploaded = files.upload()

df = read_excel(BytesIO(uploaded['assumed_PHA.csv']))

cols = ['X1',
        'lat',]
fig, axs = plt.subplots(1,
                        2,
                        figsize=(20, 5),
                        facecolor='w',
                        edgecolor='k',)
axs = axs.ravel()

for i, column in enumerate(cols):
    isolation_forest = IsolationForest(contamination='auto')
    isolation_forest.fit(df[column].values.reshape(-1,1))

    xx = linspace(df[column].min(),
                  df[column].max(),
                  len(df)).reshape(-1,1)
    anomaly_score = isolation_forest.decision_function(xx)
    outlier = isolation_forest.predict(xx)
    
    axs[i].plot(xx,
                anomaly_score,
                label='anomaly score',)
    axs[i].fill_between(xx.T[0], 
                        min(anomaly_score),
                        max(anomaly_score), 
                        where=outlier==-1,
                        color='r', 
                        alpha=.4,
                        label='outlier region',)
    axs[i].legend()
    axs[i].set_title(column)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/59226057/84817796-fabe9680-b02e-11ea-9995-9674befba2ce.png)

**Expected outcome**

The image below is from another program. The image is used for reference as to what a FiveThirtyEight style plot looks like.

![image](https://user-images.githubusercontent.com/59226057/84817970-35c0ca00-b02f-11ea-99a5-3a21c9706593.png)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Other libraries: NumPy (1.18.4)
                             Pandas (1.0.3)
                             Scikit-learn (0.22.2.post1)

Matplotlib was installed using `import matplotlib.pyplot as plt`.

[assumed_PHA.xlsx](https://github.com/matplotlib/matplotlib/files/4788689/assumed_PHA.xlsx)

**Comment by story645** [comment]
So just ran your code on google collab ([link](https://colab.research.google.com/drive/1DlwOpxLLOSe1-cKyh2n4FKfD9FWx8uw-?usp=sharing)) and I get this:

![image](https://user-images.githubusercontent.com/1300499/84862173-ac19f800-b040-11ea-84b4-ccbe1399ab9b.png)

With the following packages
* CPython 3.6.9
* IPython 5.5.0
* matplotlib 3.2.1
* numpy 1.18.5
* pandas 1.0.4
* sklearn 0.22.2.post1

Can you please provide more info on your specific environment?

**Comment by RafeyIqbalRahman** [comment]
> So just ran your code on google collab ([link](https://colab.research.google.com/drive/1DlwOpxLLOSe1-cKyh2n4FKfD9FWx8uw-?usp=sharing)) and I get this:
> 
> ![image](https://user-images.githubusercontent.com/1300499/84862173-ac19f800-b040-11ea-84b4-ccbe1399ab9b.png)
> 
> With the following packages
> 
> * CPython 3.6.9
> * IPython 5.5.0
> * matplotlib 3.2.1
> * numpy 1.18.5
> * pandas 1.0.4
> * sklearn 0.22.2.post1
> 
> Can you please provide more info on your specific environment?

I just removed the Matplotlib patches from my code. The FiveThirtyEight plot style loaded. I'll close this issue now.
