### ISSUE TITLE
Enhancement: Set tick and ticklabel colors separately from matplotlib style file

### ISSUE THREAD

**Issue by rbnvrw** [matplotlib/matplotlib#17659]
I am using a matplotlib style file and I would like to set the color of the tick marks and tick labels individually.

The color of the ticks is set via the `xtick` or `ytick.color` attribute here:
https://github.com/matplotlib/matplotlib/blob/31e26cc73918ff20c44af8cb1d59256e67df996d/lib/matplotlib/axis.py#L116

However, the same `xtick` or `ytick.color` attribute also sets the color of the tick label:
https://github.com/matplotlib/matplotlib/blob/31e26cc73918ff20c44af8cb1d59256e67df996d/lib/matplotlib/axis.py#L123

I propose to add a new rcParam `xtick.labelcolor` and `ytick.labelcolor` with which these colors can be set separately. I'm willing to work on a PR if necessary.

**Comment by jklymak** [comment]
I’m leery of the ever increasing scope of the rcParam file.  Is this something you really need as a default versus something you can just change occasionally when you need it?

**Comment by rbnvrw** [comment]
I see your point. However I think this is a pretty basic use case. In my particular example, I'd like to have plots with light gray axes lines and tick lines, but the tick labels should be readable on a white background and therefore I'd like to change those to black. It makes sense to do this via rcParams/style files because then the default "styling" will be applied to all plots that use it.

**Comment by rbnvrw** [comment]
Additionally, there was also a request from someone else a few years back, so I'm probably not the only one: https://stackoverflow.com/questions/50038678/matplotlib-custom-styles-different-tick-color-and-tick-label-color

**Comment by jklymak** [comment]
I see, I guess that is a fair enough style choice.

**Comment by rbnvrw** [comment]
This is merged, so I'll close this issue now.
