### ISSUE TITLE
Gridspec is not applied to figure but should.

### ISSUE THREAD

**Issue by phfrohring** [matplotlib/matplotlib#17660]
### Bug report

**Bug summary**

```
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from IPython.display import display


fig = plt.figure(constrained_layout=True)
plt.close()
fig.set_size_inches((5,5))
grid = gridspec.GridSpec(ncols=2, nrows=2, figure=fig)
fig_ax1 = fig.add_subplot(grid[0, 0])
display(fig)
print("-------------------------")
fig_ax2 = fig.add_subplot(grid[0, 1])
display(fig)
```

Gives:

![xxx](https://user-images.githubusercontent.com/10885649/84879110-0fc91300-b08b-11ea-967a-7cfabd36b6e8.png)

**Expected outcome**

![xxx](https://user-images.githubusercontent.com/10885649/84879254-43a43880-b08b-11ea-940a-8042cabe8bd4.png)

**Matplotlib version**

```
mpl.__version__: 3.2.1
os.name: posix
mpl.get_backend(): module://ipykernel.pylab.backend_inline
sys.version: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.1
ipython          : 7.13.0
ipykernel        : 5.1.1
jupyter client   : 6.0.0
jupyter lab      : 1.2.14
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
```

**Comment by tacaswell** [comment]
This works as expected (modulo removing the `plt.close()` to not close the figure early) in Qt5Agg.  

I suspect that this is something going wrong in either the inline backend or the IPython display (and in further complicated by inline defaulting to `bbox_inches='tight'`).  Is it only adding axes that does not get reflected?  If you plot to the first axes does it get picked up?

**Comment by phfrohring** [comment]
> I suspect that this is something going wrong in either the inline backend or the IPython display 

Yes. If one removes the first `display(fig)` we get the code below:

```
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from IPython.display import display


fig = plt.figure(constrained_layout=True)
plt.close()
fig.set_size_inches((5,5))
grid = gridspec.GridSpec(ncols=2, nrows=2, figure=fig)
fig_ax1 = fig.add_subplot(grid[0, 0])
fig_ax2 = fig.add_subplot(grid[0, 1])
display(fig)
```

This one does yield the expected result (it's how I generated the expected outcome).

I don't understand why a call to `display` would yield this observed behaviour.

**Comment by tacaswell** [comment]
My knne-jerk guess is that the display machinery is caching the results.

**Comment by phfrohring** [comment]
So, it would be something to report to the authors of `display` I guess ?
Cannot decide if this the expected behaviour, but it's surprising.
