### ISSUE TITLE
BUG: plot_trisurf for Triangles in y-z-plane

### ISSUE THREAD

**Issue by GeorgBrantegger** [matplotlib/matplotlib#17682]
### Bug report

**Bug summary**

I wanted to plot a triangle consisting of 3 3D points in the y-z plane. When running the code, I got an error message, claiming the triangulation was not possible.

**Code for reproduction**

```python
# Paste your code here
################################### fixed preamble
import matplotlib
matplotlib.__version__

import platform
platform.python_version()
###################################
################################### import stuff
import numpy as np
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D
###################################

################################### create the points
#reshape for consistent indexing with rest of my project code
A = np.array([0,1,5],dtype=float).reshape(1,3)
B = np.array([0,2,2],dtype=float).reshape(1,3)
C = np.array([0,1,2],dtype=float).reshape(1,3) 
###################################
################################### createing a np.array from the points
base_tri = np.array([A,B,C]).reshape([3,3])
###################################
################################### plotting
fig1 = plt.figure()
ax1 = fig1.add_subplot(111, projection='3d')
ax1.plot_trisurf(base_tri[:,0],base_tri[:,1],base_tri[:,2])

ax1.scatter(A[0,0],A[0,1],A[0,2])
ax1.scatter(B[0,0],B[0,1],B[0,2])
ax1.scatter(C[0,0],C[0,1],C[0,2])
plt.show()
###################################
```

**Actual outcome**

```
# If applicable, paste the console output here
Traceback (most recent call last):
  File "c:/Users/.../bug_report.py", line 
26, in <module>
    ax1.plot_trisurf(base_tri[:,0],base_tri[:,1],base_tri[:,2])
  File "C:\Users\...\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 1956, in plot_trisurf
    Triangulation.get_from_args_and_kwargs(*args, **kwargs)
  File "C:\...\Anaconda3\lib\site-packages\matplotlib\tri\triangulation.py", line 167, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "C:\...\Anaconda3\lib\site-packages\matplotlib\tri\triangulation.py", line 54, in __init__
    self.triangles, self._neighbors = _qhull.delaunay(x, y)
ValueError: x and y arrays must consist of at least 3 unique points
```

**Expected outcome**

Well, I expected to get a triangle in the y-z plane.
I saw the value error "x and y arrays must consist of at least 3 unique points" but I don't understand why in a 3D space the triangulation only works when the points don't lie in a plane not parallel to y-z or x-z. 

**Matplotlib version**

  * Operating system: Windows 1909
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:3.7.6
  * Jupyter version (if applicable): /
  * Other libraries: numpy 1.18.1

I think I installed everything from conda, but I am not sure.

**Comment by jklymak** [comment]
I think you are looking for trick_surf3d?  https://matplotlib.org/examples/mplot3d/trisurf3d_demo.html

**Comment by GeorgBrantegger** [comment]
The plot command in this example is the same as I used: >plot_trisurf(x,y,z)<
I verified, that this command works with points not lying in the y,z-plane.
I tried:
A = np.array([1,1,5],dtype=float).reshape(1,3)
B = np.array([2,2,2],dtype=float).reshape(1,3)
C = np.array([3,1,2],dtype=float).reshape(1,3)
and it works fine.
I am confused by the error message, that tells me "x and y arrays must consist of at least 3 unique points", which I dont understand since in 3D space we have x,y and z coordinates. And the points I used are unique.

**Comment by jklymak** [comment]
The triangulation is in x-y and the third dimension is z.  You are indeed repeating co-ordinates in x-y, so it can't make a triangle in x-y.  It seems to me that you really want a Poly3DCollection?  https://matplotlib.org/api/_as_gen/mpl_toolkits.mplot3d.art3d.Poly3DCollection.html  

But I'm not an expert on the 3-D plotting.

**Comment by timhoffm** [comment]
Since there is no feedback, I'll assume this is resolved. Please report back, if this is still an issue.

**Comment by wnederpel** [comment]
The discussion here does not provide the solution to the problem, but there is a solution.

You cannot plot 2D triangles in 3D space with Poly3DCollection, as it is a collection to plot 3D polygons, let alone 2D triangles which would be lines when projected to the x-y plane.

You can however (from the mobius band example [here](https://matplotlib.org/stable/tutorials/toolkits/mplot3d.html#tri-surface-plots)) define surface parameters of your surface, triangulate those with Triangulation, and plot it with the associated x y z coordinates using plot_trisurf(x, y, z, triangles=my_triangles).

Hope this will help someone figure this out faster than I did.
