### ISSUE TITLE
getpwuid(): uid not found: 99

### ISSUE THREAD

**Issue by fcomte** [matplotlib/matplotlib#17707]
Hello

I am using a container image of tensorflow.
Inside it, the uid is 99 and there is no user map to it in /etc/passwd

I get the following error when I import matplotlib "getpwuid(): uid not found: 99"
Name: matplotlib
Version: 3.2.1

**Comment by jklymak** [comment]
Can you provide the full traceback.  We do not call `getpwuid()`.

**Comment by fcomte** [comment]
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/lib/python3.6/pathlib.py in gethomedir(self, username)
    359             try:
--> 360                 return os.environ['HOME']
    361             except KeyError:

/usr/lib/python3.6/os.py in __getitem__(self, key)
    668             # raise KeyError with the original key value
--> 669             raise KeyError(key) from None
    670         return self.decodevalue(value)

KeyError: 'HOME'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-0484cd13f94d> in <module>
----> 1 import matplotlib

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in <module>
   1013 
   1014 # this is the instance used by the matplotlib classes
-> 1015 rcParams = rc_params()
   1016 
   1017 

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    876 def rc_params(fail_on_error=False):
    877     """Construct a `RcParams` instance from the default Matplotlib rc file."""
--> 878     return rc_params_from_file(matplotlib_fname(), fail_on_error)
    879 
    880 

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in matplotlib_fname()
    729         yield os.path.join(_get_data_path(), 'matplotlibrc')
    730 
--> 731     for fname in gen_candidates():
    732         if os.path.exists(fname) and not os.path.isdir(fname):
    733             return fname

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in gen_candidates()
    726             yield matplotlibrc
    727             yield os.path.join(matplotlibrc, 'matplotlibrc')
--> 728         yield os.path.join(get_configdir(), 'matplotlibrc')
    729         yield os.path.join(_get_data_path(), 'matplotlibrc')
    730 

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in wrapper(**kwargs)
    274         nonlocal called, ret
    275         if not called:
--> 276             ret = func(**kwargs)
    277             called = True
    278             _log.debug(fmt, ret)

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in get_configdir()
    607     5. A writable directory could not be found or created; return None.
    608     """
--> 609     return _get_config_or_cache_dir(_get_xdg_config_dir())
    610 
    611 

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in _get_xdg_config_dir()
    560     <http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html>`_.
    561     """
--> 562     return os.environ.get('XDG_CONFIG_HOME') or str(Path.home() / ".config")
    563 
    564 

/usr/lib/python3.6/pathlib.py in home(cls)
   1060         returned by os.path.expanduser('~')).
   1061         """
-> 1062         return cls(cls()._flavour.gethomedir(None))
   1063 
   1064     def samefile(self, other_path):

/usr/lib/python3.6/pathlib.py in gethomedir(self, username)
    361             except KeyError:
    362                 import pwd
--> 363                 return pwd.getpwuid(os.getuid()).pw_dir
    364         else:
    365             import pwd

KeyError: 'getpwuid(): uid not found: 99'`

**Comment by jklymak** [comment]
So with your setup you cannot even call `Path.home()` from the standard library.  I'm not clear what the point of such a setup is, or if its reasonable for us to support.  Perhaps @anntzer or @tacaswell would know better.

**Comment by tacaswell** [comment]
This can probably be fixed via the container configuration in the short run, but this is something that we should support gracefully.

**Comment by fcomte** [comment]
I am using mesos universal container runtime .. this is why it is really easy to solve in container runtime

**Comment by tacaswell** [comment]
The function that is failing (https://docs.python.org/3/library/pwd.html#pwd.getpwuid) is trying to look up information about the user that is currently running.  I am not convinced that this should be expected to fail in a properly configured container (but I am not an expert sysadmin).

**Comment by fcomte** [comment]
It should not fail indeed

**Comment by QuLogic** [comment]
I don't understand why, if you can't fix `/etc/passwd`, you can't set `HOME` before running your script?

**Comment by timhoffm** [comment]
Configuration aside, IMHO, `Path.home()` should not raise this KeyError (https://bugs.python.org/issue41082).

**Comment by fcomte** [comment]
> I don't understand why, if you can't fix `/etc/passwd`, you can't set `HOME` before running your script?

I fix `/etc/passwd` with a new docker image from the previous one, but i am still surprised by this behaviour in such a scenario

**Comment by tacaswell** [comment]
We should be defensively catching an exceptions that may be raised on import as they are non-recoverable by the user.

**Comment by tacaswell** [comment]
With mpl 3.9 will require python 3.10 which fixes this bug upstream.
