### ISSUE TITLE
Mention rasterized option in more methods

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#17708]
We should mention rasterized in a few places in the docstrings of relavent methods.  Ie pcolormesh, contour etc.  This option is probably the number one reason I started to use matplotlib,  but it seems a lot of people don’t realize it exists.

**Comment by timhoffm** [comment]
Also, https://matplotlib.org/gallery/misc/rasterization_demo.html should get some explanation.

**Comment by marychrisgo** [comment]
@timhoffm I'd like to take on this issue (putting explanatory text for rasterization demo)!

**Comment by tacaswell** [comment]
@jklymak How do you pass this through to contour?  @phil-sparks worked on this a bit at the pydata sprint and we could not sort out how to easily set this on contour / contourf.

**Comment by jklymak** [comment]
Really?  I thought rasterized worked on contour, but maybe I'm incorrect.

**Comment by tacaswell** [comment]
```
In [91]: ctr = plt.contour(np.arange(42).reshape(7, 6), rasterized=True)
<ipython-input-91-3a9a3dad7a49>:1: UserWarning: The following kwargs were not used by contour: 'rasterized'
  ctr = plt.contour(np.arange(42).reshape(7, 6), rasterized=True)
```

**Comment by jklymak** [comment]
Thats a pretty obvious wishlist item.  Particularly for `contourf` I can imagine it would be nice to rasterize sometimes
