### ISSUE TITLE
Patches output different from code

### ISSUE THREAD

**Issue by Dave-12-cr** [matplotlib/matplotlib#17706]
I'm adding a set of patches to my Matplotlib chart, the problem is that those patches look different from how i'm generating them from my code. I have an array of data, and i'm using that data to print the patches, here is my code:

```
for x in MyData:
    if x[1] > 150 and x[1] < 200:
        new_patch = Rectangle(xy=(x[0], x[1]), width=1.3, height=0.51, angle=0, color='#dd00ff', alpha=0.3)
        ax1.add_patch(new_patch)
    elif x[1] > 200 and x[1] < 350:
        new_patch = Rectangle(xy=(x[0], x[1]), width=1.3, height=0.5, angle=0, color='#00ffd9', alpha=0.6)
        ax1.add_patch(new_patch)
```
Output:

![q](https://user-images.githubusercontent.com/67102155/85231589-d11fb980-b3f8-11ea-965b-03dde93e4f2f.png)
![qq](https://user-images.githubusercontent.com/67102155/85231604-ef85b500-b3f8-11ea-8558-2d9bacb605b3.png)

There are a few things to note here:

1)The purple patches have not the same alpha, while in my code they have the same alpha. You can see that there is a brighter purple line, while the others have not the same brightness.
2)The purple and teal patches have the same brightness, while on my code the teal patch (#00ffd9) has double the alpha of purple.
Can someone explain me why does that happen? Is that a matplotlib bug? Or is the problem with my code? Am i using wrong parameters to set the patches? Any kind of advice is appreciated.

**Comment by timhoffm** [comment]
Please provide a full minimal example, so that we can run it and inspect it ourselves.

**Comment by tacaswell** [comment]
@Dave-12-cr Did you sort out what was going on?
