### ISSUE TITLE
inset_locator.mark_inset() misplaces box connectors

### ISSUE THREAD

**Issue by joreiff** [matplotlib/matplotlib#17711]
### Bug report

**Bug summary**

`inset_locator.mark_inset()` sometimes misplaces the box connector lines if x/y limits on the parent `Axes` have not been explicitly set. Updating the plot (e.g. by saving the figure) seems to fix it.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import mpl_toolkits.axes_grid1.inset_locator as miloc

fig, (inset, full) = plt.subplots(ncols=2)

# swapping the axes makes the example work
# full, inset = inset, full

full.plot([-1, 0], [-1, 0])
inset.set_xlim(-0.6, -0.4)
inset.set_ylim(-0.6, -0.4)

# workaround
# full.set_xlim(-1.0, 0.0)
# full.set_ylim(-1.0, 0.0)

miloc.mark_inset(full, inset, 1, 4)
fig.savefig('Bug.png')
# saving the figure a second time produces the expected result
fig.savefig('NoBug.png')
```

**Actual outcome**

![Bug](https://user-images.githubusercontent.com/3749578/85268866-619cdf00-b477-11ea-8899-ca66f7be435a.png)

**Expected outcome**

![NoBug](https://user-images.githubusercontent.com/3749578/85268916-71b4be80-b477-11ea-9bfc-e0c7d1b0af17.png)

This issue was not present in version 3.0.2.

**Matplotlib version**

  * Operating system: Fedora and Debian
  * Matplotlib version: 3.2.1 and 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg` and `agg`
  * Python version: 3.8
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Installed via pip on Debian and both pip and dnf on Fedora.

**Comment by jklymak** [comment]
I don't know if you need some feature of the axes_grid1 implementation, but the following seems to work fine:

```python
import matplotlib.pyplot as plt

fig, (inset, full) = plt.subplots(ncols=2)

full.plot([-1, 0], [-1, 0])
inset.set_xlim(-0.6, -0.4)
inset.set_ylim(-0.6, -0.4)

full.indicate_inset_zoom(inset)
plt.show()
```

![inset](https://user-images.githubusercontent.com/1562854/85310640-1aa7ed00-b469-11ea-9a0a-27d044ad6950.png)

**Comment by jklymak** [comment]
For me, the bug with axis_grid1 bisects to 160de568e1f6d3e5e, https://github.com/matplotlib/matplotlib/pull/13593 , which probably makes sense, but I've not thought about it too hard yet.  @anntzer ?

**Comment by anntzer** [comment]
Yes, I understand the bug, but it's rather tricky to fix unless we introduce a full loop in Figure.draw where we go through all axes and autoscale them all (I guess perhaps at the same time as running the locators to position them...) before actually drawing them...

**Comment by jklymak** [comment]
I'd see if the OP really needs this to work in `axes_grid1` or if they will be happy with the more "modern" version.  Even when it worked the result is not particularly nice in axes_grid1....

**Comment by joreiff** [comment]
Thanks for the fast reply! I did discover that calling `full.get_xlim()` before saving/showing the figure fixes the problem, so I have a workaround for now.

The reason I did not use `indicate_inset_zoom` is that
1. I was working on existing code that preceded this function,
2. I have more code to make `mark_inset` pretty and
3. `indicate_inset_zoom` is marked as experimental in the documentation.

If you would consider `indicate_inset_zoom` stable enough, however, I can switch to it in the future.

**Comment by jklymak** [comment]
@joreiff, I think the main library' version is probably stable.  We've not received too many complaints about it, which either means it works fine, or no one is using it :wink:

**Comment by joreiff** [comment]
@jklymak In this case, I will be happy using the new API in the future. If fixing this bug is tricky and `indicate_inset_zoom` is functionally equivalent, it may be a good idea to deprecate `mark_inset` at some point. Feel free to close this issue if you like.

**Comment by jklymak** [comment]
No, it should definitely stay open.  I doubt axes_grid1 will ever be completely deprecated, and someone may want to fix this.
