### ISSUE TITLE
Error using set_window_title 

### ISSUE THREAD

**Issue by NHades** [matplotlib/matplotlib#17713]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by NHades** [comment]
duplicate

**Comment by tacaswell** [comment]
@NHades Which issue is this a duplicate of?

**Comment by QuLogic** [comment]
#17716, I assume.

**Comment by NHades** [comment]
Yes, sorry. while looking up code and then switched to a new windows it autosaved
