### ISSUE TITLE
Different results using imshow

### ISSUE THREAD

**Issue by jomey** [matplotlib/matplotlib#17722]
### Bug report

**Bug summary**

`imshow()` plots different results between versions 3.1.2 and 3.2.2 for masked numpy arrays. The latest version is missing pixels that were plotted in the older version.

**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as plt

arr = np.ma.masked_values(
    np.load('test.npz')['arr_0'],
    -9999
)
np.ma.masked_where(arr <= 0, arr, copy=False);

plt.figure()
plt.imshow(arr);
```

**Actual outcome**

* Expected and correct result with 3.1.2
![Unknown-1](https://user-images.githubusercontent.com/178649/85324214-a54b1500-b486-11ea-8971-af055ecc2dca.png)

* Results using 3.2.2
![Unknown](https://user-images.githubusercontent.com/178649/85324221-a9773280-b486-11ea-98f3-2f1e78bb0430.png)

**TestFile**
[test.pyz](https://drive.google.com/file/d/1upNDEqmw7P6Ij8h9Xy0ACBt3t_471DCO/view)

Both versions were installed via conda. Numpy is 1.18.5

**Comment by jklymak** [comment]
3.2 changed the anti-aliasing of downsampled images.  
https://matplotlib.org/3.2.1/api/api_changes.html#default-image-interpolation

To get the old behaviour, you need to call `plt.imshow(arr, interpolation='none')`.  

However, note that if the antialiasing filter is kicking in, the you really don't have enough pixels to represent your data, and might consider increasing your dpi and/or figure size to ensure that it is all being plotted.    Note that for 3.2.2 example, if you zoom in your data will start appearing.

**Comment by jomey** [comment]
@JackKelly - Thank you for pointing me for the docs. I was looking for the wrong search terms.

Setting the interpolation to `none` brings back the old results.

**Comment by jomey** [comment]
Update 2 and logging for others to find this:
As Jack noted, I was indeed missing enough pixels to display the data values. The array has the shape of: 5617, 4676 and increasing the dpi in combination with the figure size showed proper results.
