### ISSUE TITLE
Using backend Template and plt.tight_layout raises UnboundLocalError

### ISSUE THREAD

**Issue by jni** [matplotlib/matplotlib#17730]
Matplotlib 3.3.0rc1 appears to be breaking our documentation builds at scikit-image, see 

https://travis-ci.org/github/scikit-image/scikit-image/jobs/701180133#L5665-L5691

I was able to create a minimal example that reproduces the error on my machine, see code below.

### Bug report

**Bug summary**

```python
import numpy as np
import matplotlib
matplotlib.use('Template')
import matplotlib.pyplot as plt

fig, axes = plt.subplots()
axes.imshow(np.random.random((5, 5)), cmap=plt.cm.gray)
plt.tight_layout()
```

**Actual outcome**

```pytb
Traceback (most recent call last):
  File "mpl_error.py", line 8, in <module>
    plt.tight_layout()
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1489, in tight_layout
    gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/figure.py", line 2604, in tight_layout
    renderer = get_renderer(self)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 176, in get_renderer
    return backend_bases._get_renderer(fig)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1556, in _get_renderer
    return renderer
UnboundLocalError: local variable 'renderer' referenced before assignment
```

**Expected outcome**

No crash.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.0rc1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Template
  * Python version: 3.8.3
  * Jupyter version (if applicable): N/A
  * Other libraries: 1.19.0

**Installation**

```
conda create -n matplotlib-rc python=3.8
conda activate matplotlib-rc
pip install --pre matplotlib numpy
```

**Comment by jklymak** [comment]
Thanks for checking the RC!  Much appreciated.

Is there a reason you are using "Template" instead of "Agg"?  I don't think we meant for template to be public (in the mists of time).

**Comment by QuLogic** [comment]
Does the Template backend actually do anything? I would not expect it to actually produce any usable figures.

**Comment by jni** [comment]
> Thanks for checking the RC! Much appreciated.

Yeah I'm *so* happy we set up pre-release testing! :blush: 

> Is there a reason you are using "Template" instead of "Agg"?

Dunno! The mists of time is a good way to describe the time when that part of the config was written. I can try changing it to Agg and see if that fixes our CI, but still, UnboundLocalErrors should not be possible. :slightly_smiling_face: 

> I would not expect it to actually produce any usable figures.

It's not supposed to, this particular check in our CI just tests that the examples run without incident.

Also, if Template does approximately nothing, would that make the examples run faster?
