### ISSUE TITLE
Rename "array" (and perhaps "fields") section of Axes API

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#17733]
### Bug report

**Bug summary**

The axes_api page current includes
![test](https://user-images.githubusercontent.com/1322974/85425549-985b1e00-b579-11ea-9317-9807d48b8f52.png)

I would say "array" is not a great name here (1D arrays are also arrays :-))  I guess "images" could be a reasonable replacement?  Note that there's already "fields" below for barbs/quiver(key)/streamplot, but perhaps that one could be renamed "vector fields", too...

(Also, the fact that the summary for imshow is cut after i.e. is tracked at https://github.com/sphinx-doc/sphinx/issues/7865.)

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 322
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
I don't like "images" because we really have an issue with people thinking we are an image processing library.  And I dont' think of pseudocolor plots as images per-se.  Anything wrong with "2-D Arrays"?

**Comment by story645** [comment]
Images & Tables ?

**Comment by timhoffm** [comment]
+1 for "2D arrays" and "Vector fields".

**Comment by QuLogic** [comment]
> (Also, the fact that the summary for imshow is cut after i.e. is tracked at [sphinx-doc/sphinx#7865](https://github.com/sphinx-doc/sphinx/issues/7865).)

This bit can be fixed by the last commit in #17752.
