### ISSUE TITLE
Redraw event not always issued after canvas resize

### ISSUE THREAD

**Issue by pjb1008** [matplotlib/matplotlib#17771]
### Bug report

My GTK application includes a graph drawn using matplotlib. Every so often, after _rapidly_ resizing the application window, the graph shows only the background and not the animated content. 

After a short time (usually several seconds), the graph will appear again and be animated as normal.

I'm using the gtk3agg backend. 
When the canvas resize event happens, I'm calculating and setting the x axis limits.
When the canvas draw event happens, I'm taking a snapshot of the static background.
When the gio timer event happens, I restore the background by blitting and draw the animated lines on top.

Normally a resize event is followed by a redraw event and the graph looks perfect.
When the problem happens, the redraw event is the last event the application receives. The graph does not display correctly until the next redraw event.
I can induce the problem more easily if I add a delay to the resize event handler.

**Code for reproduction**

```python
#!/usr/bin/python3

from collections import deque
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject
import math
from matplotlib.figure import Figure
from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg as FigureCanvas
import time
import signal

class my_window(Gtk.Window):
    def __init__(self):
        super().__init__()

        # This is the line data
        self.x_series = deque(maxlen=1000)
        self.y_series = deque(maxlen=1000)
        self.x = 0

        # The line and the x-axis will be animated
        self.background = None
        self.fig = Figure()
        self.canvas = FigureCanvas(self.fig)
        self.ax = self.fig.add_subplot(111, facecolor="#eeeeff")
        self.ax.xaxis.set_animated(True)
        self.ax.grid()
        self.red_line, = self.ax.plot([], [], "r", animated=True)

        # Connect signal handlers
        self.canvas.mpl_connect("draw_event", self.draw_handler)
        self.canvas.mpl_connect("resize_event", self.canvas_resized)
        self.timer=GObject.timeout_add(20, self.update_graph)

        # Add the graph to the window
        self.add(self.canvas)
        self.canvas.show()
        self.set_size_request(300, 300)
        self.show()

    def canvas_resized(self, e):
        # When the canvas is resized, change the axes so that
        #  - the resolution is fixed
        #  - new data appears at the right, and
        #  - y=0 is half way up the y-axis
        geom = self.ax.get_window_extent()
        w = (geom.x1-geom.x0)/50
        h = (geom.y1-geom.y0)/100
        self.ax.set_xlim(self.x - w, self.x)
        self.ax.set_ylim(-h, +h)
        time.sleep(0.5) # Provoke the bug a bit more easily.

    def draw_handler(self, draw_event):
        # Take a copy of the background
        self.background = self.fig.canvas.copy_from_bbox(self.fig.bbox)
        self.draw_lines()

    def update_graph(self):
        # Add the new data
        self.x_series.append(self.x)
        self.y_series.append(math.sin(self.x*2*math.pi))        
        self.x += 0.01

        if self.background is None: return True
        
        # Update the x-axis
        x_min, x_max = self.ax.get_xlim()
        w = x_max - x_min
        self.ax.set_xlim(self.x - w, self.x)
    
        self.draw_lines()
        return True
    
    def draw_lines(self):
        self.red_line.set_data(self.x_series, self.y_series)
        self.fig.canvas.restore_region(self.background)
        self.ax.draw_artist(self.red_line)
        self.ax.xaxis.draw(self.fig.canvas.renderer)
        self.fig.canvas.blit(self.ax.clipbox)

if __name__ == "__main__":
    win = my_window()
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Gtk.main()
```

**Actual outcome**
(This image was being resized vertically when it broke.)
![broken](https://user-images.githubusercontent.com/4499413/85878609-e453d000-b7d0-11ea-8f29-35ff55f3c227.png)

**Expected outcome**
![working](https://user-images.githubusercontent.com/4499413/85878684-051c2580-b7d1-11ea-9f49-e13019643485.png)

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version: 2.1.1 (from Ubuntu package 2.1.1-2ubuntu3)
  * Matplotlib backend: GTK3Agg
  * Python version: 3.6.9
  * Other libraries: GTK 3.30.22

**Comment by QuLogic** [comment]
Please try with a newer version of Matplotlib; that version is very old.

**Comment by pjb1008** [comment]
Hi,

I hadn't realised quite how old the Ubuntu 18 package is. I just tried matplotlib-3.2.2, installed with pip3, and now my code works correctly.
Thank you!

Peter
________________________________

**Comment by GerfriedC** [comment]
What about using plt.ion(). Should that redraw immediately in case of resizing between the plot events?
Since it does not on Raspberry OS, how to ensure? 
Many thanks

**Comment by tacaswell** [comment]
@GerfriedC I would not expect `plt.ion()` to affect when redraws happen once the event loop is running (see https://matplotlib.org/stable/users/interactive.html#interactive-mode for details of what it controls).
