### ISSUE TITLE
spacing between ticks

### ISSUE THREAD

**Issue by deadstar1** [matplotlib/matplotlib#17779]
### Bug report

**Bug summary**

How can I control the spacing between subplot's y ticks? I have 2 scatter plots on a subplot, on the first scatter plot the Ys are always equal to 0, and on the second scatter plot I have a y values that are ranging from 7.0 to 7.25 and more. There is too much space between 0 and 7, and there is no space between from 7 to 7.25( it should be like this 0, 7.000,7.005,7.010,7.015,7.020,7.025, and so on)

**Code for reproduction**

```python
import random
import matplotlib.pyplot as plt
import numpy as np
import mpld3
x = [x for x in range(100)]
y=[random.uniform(7, 8) for x in range(100)]
y1=[0 for x in range(100)]
fig, ax = plt.subplots()
ax.scatter(x,y)
ax.scatter(x,y1)
fig.show()
```

**Actual outcome**

```
https://i.stack.imgur.com/MWfol.gif
```

**Expected outcome**

Does not show the interval between 0 and 7

**Matplotlib version**

  * Operating system: windows 10
  * Matplotlib version:  latest
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg
  * Python version:3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
Unless I am mistaken, this appears to be an issue with mpld3, not with matplotlib?

**Comment by deadstar1** [comment]
nope I did not use mpld3

**Comment by anntzer** [comment]
You are importing mpld3 in your example.

**Comment by deadstar1** [comment]
yes, but to use the mpld3 'mpld3.display(fig)' should be called?

**Comment by jklymak** [comment]
You’ve already posted this on stackoverflow which  is the more appropriate venue for this sort of question.  I’m going to close here because this is not a bug. Thanks for your interest in matplotlib

**Comment by tacaswell** [comment]
![so](https://user-images.githubusercontent.com/199813/85937987-f28c1400-b8d6-11ea-8ddf-a7076bac3803.png)

```python
import random
import matplotlib.pyplot as plt
x = [x for x in range(100)]
y=[random.uniform(7, 8) for x in range(100)]
y1=[0 for x in range(100)]
fig, ax = plt.subplots()
ax.scatter(x,y)
ax.scatter(x,y1)
fig.show()
```

I can not reproduce this without importing mpld3.

**Comment by deadstar1** [comment]
@tacaswell really? works fine on me 
![image](https://user-images.githubusercontent.com/6646675/85941242-4b4dc200-b954-11ea-9ec5-5463453f6ed5.png)

**Comment by jklymak** [comment]
@deadstar1 What effect are you trying to achieve if not what's plotted above?  That is a linear y axis - the distance between 0 and 8 is eight times the distance between 7 and 8, which is what a linear axis is supposed to do.

**Comment by jklymak** [comment]
Perhaps you want to make a non-linear scale of some sort: https://matplotlib.org/devdocs/gallery/scales/scales.html
