### ISSUE TITLE
subplot: get_position() and set_position() are inconsistent 

### ISSUE THREAD

**Issue by jan-janssen** [matplotlib/matplotlib#17777]
### Bug report

**Bug summary**

get_position() and set_position() are inconsistent 

**Code for reproduction**

```python
box1 = ax1.get_position()
print(box1)
ax1.set_position([box1.x0, box1.y0, box1.x1-box1.x0, box1.y1-box1.y0])
box2 = ax1.get_position()
print(box2)
ax1.set_position([box1.x0, box1.y0, box1.x1, box1.y1])
box3 = ax1.get_position()
print(box3)
```

**Actual outcome**

```
Bbox(x0=0.125, y0=0.125, x1=0.9, y1=0.88)
Bbox(x0=0.125, y0=0.125, x1=0.9, y1=0.88)
Bbox(x0=0.125, y0=0.125, x1=1.025, y1=1.005)
```

**Expected outcome**

```
Bbox(x0=0.125, y0=0.125, x1=0.9, y1=0.88)
Bbox(x0=0.125, y0=0.125, x1=0.775, y1=0.755)
Bbox(x0=0.125, y0=0.125, x1=0.775, y1=0.755)
```

get_position() and set_position() should be consistent.

**Matplotlib version**

  * Operating system: Linux and Mac OS X
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable): 6.0.3 
  * Other libraries: 

I installed matplotlib via conda using the conda-forge channel.

**Comment by jklymak** [comment]
The list For set_postion is x0 , y0, width, height.   https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_position.html

**Comment by jklymak** [comment]
I'm going to close this, because `set/get_position` is working as expected, as per your example.  You're "expected" is incorrect.  `x1/y1` are the position of the corner, not the width/height.  If you want the box width and height, please use `box1.width, box1.height`.

**Comment by tacaswell** [comment]
That is a bit of a trap we have left for users, but given that we want to internally normalize to a `bbox`, maintain return type stability on `get_position`, and it has been like this for a very long time I don't think there is much we can do about this other than document it better.

When specifying the location of an Axes (left, bottom, width, height) seems to match the way people want to think about more often that (left, bottom, right, top) (which is probably why the API was built this way to begin with) but even if we wanted to change the API, I am not sure that it would be worth the disruption.  I also am not convinced that it is worth adding a flag to control the meaning of the a list, it is probably better to direct users to 
https://matplotlib.org/api/transformations.html?highlight=from_bounds#matplotlib.transforms.Bbox.from_bounds and https://matplotlib.org/api/transformations.html?highlight=from_bounds#matplotlib.transforms.Bbox.from_extents to generate the bbox based on which way they prefer to think about the coordinates.


I would add that you you can pass the return value from `get_position` into `set_position` and it does round-trip as expected)

```python
In [13]: fig, (ax1, ax2, ax3) = plt.subplots(3, 1) 
    ...: box1 = ax1.get_position() 
    ...: print(box1) 
    ...: ax1.set_position(box1) 
    ...: box2 = ax1.get_position() 
    ...: print(box2) 
    ...: ax1.set_position(box2) 
    ...: box3 = ax1.get_position() 
    ...: print(box3)  
Bbox(x0=0.125, y0=0.6535294117647059, x1=0.9, y1=0.88)
Bbox(x0=0.125, y0=0.6535294117647059, x1=0.9, y1=0.88)
Bbox(x0=0.125, y0=0.6535294117647059, x1=0.9, y1=0.88)

```
