### ISSUE TITLE
newbie question about polar plots

### ISSUE THREAD

**Issue by lonnietc** [matplotlib/matplotlib#17785]
Hi All,
I am a newbie to matplotlib having just now come across it.

I need to make a polar plot similar to 
![image](https://user-images.githubusercontent.com/15264930/85952506-c3f25580-b937-11ea-8806-18ecc6a944a2.png)

which is really just an archimedean number spiral that plots little circles (labeled integers) at each integer location but am not sure how to go about it.

I did come across the matplotlib polar demo:

https://matplotlib.org/gallery/pie_and_polar_charts/polar_demo.html

If, I could add small labeled circles at each integer location along the spiral then that might work for me.

Any help would be greatly appreciated.
Thanks in advance.

**Comment by jklymak** [comment]
Please ask for help on discourse.matplotlib.org or stackoverflow.com.   Thanks!
