### ISSUE TITLE
Pyplot methods should link to their parents

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#17786]
Pyplot methods should refer to their parents when possible.   Ie plt.xlabel should have a “see also” to ax.set_xlabel

**Comment by gauravsawant** [comment]
Can I pick up this issue?

**Comment by jklymak** [comment]
@gauravsawant absolutely!  Thanks for your interest.  The only gotcha is that some  of the methods are created via boilerplate from their parents.  Dealing with that may be harder than the hard-coded methods.  Be sure to ping us if you have questions.

**Comment by timhoffm** [comment]
The boilerplate functions are conceptually easier. They just map to the `Axes` equivalent. It's just a matter of ammending the docstring in the boilerplate code. The other pyplot functions are the ones that need individual descriptions as they don't simply match 1:1. Some of them already have comments on this see e.g. the notes in https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.xticks.html.

I think boilerplate and individual links should be done in two separate PRs as the required abilities are quite different.

On a general note, we should come up with a helpful message. IMHO a "See Also" without further comment is not very helpful. Something along the lines "This is the *pyplot wrapper* for `Axes.text`", where *pyplot wrapper* should be a link to an explanation of the pyplot vs. OO concepts - which I don't think we have a good summary of right now :cry:. For the time being https://matplotlib.org/devdocs/api/index.html#usage-patterns may do.

Also to be considered: Should this be a "See also", or part of the "Notes" section or some dedicated (to be created) admonition. I would favor this to be consistent for all pyplot functions and some have already notes (e.g. https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.xticks.html).

**Comment by jklymak** [comment]
I almost think that See Also is enough.  I don't know if we need a bunch of verbiage pointing out the two usage concepts for each docstring.  But it is hard for folks who are used to `plt.xlabel` who then decide they need an axes handle, and then have to idea how to add an xlabel.

**Comment by timhoffm** [comment]
"See also" is de-facto used to link to similar and related functions. After reading the docstrings of the functions, one should be able to judge which function one should use for a given use-case. `plt.xlabel` and `Axes.set_xlabel` do exactly the same thing. The only difference is the usage idiom, and that should be mentioned somehow.

> But it is hard for folks who are used to plt.xlabel who then decide they need an axes handle, and then have to idea how to add an xlabel.

In contrast, I imagine someone only used to pyplot reading the docs. If you are not familiar with the topic `pyplot` vs. OO usage pattern, a link without further explanation is confusing.

**Comment by story645** [comment]
xref against #15922 cause I think an extra layer of confusion is that most of the examples in the pyplot section are actually OO.
But also all for this since I think it's part of what frustrated https://twitter.com/ecpensiveLife/status/1278804210793033729?s=19

**Comment by timhoffm** [comment]
Semi-OT, pyplot serves two purposes

1) the function based interface
2) "behind the scenes tasks" backend selection / figure management (+ creation with appropriate wiring) / event loop.

Number 2. is often still needed when using the OO interface, which makes it a bit confusing (also OO-style starts with `pyplot.subplots` or `pyplot.figure`). We're really not good at explaining this.

In the long run, I would like to see 2. moved out of pyplot (maybe dirctly into `matplotlib`); e.g. one could have `mpl.subplots()` and `mpl.figure()` as entry points so that the OO approach wound not import pyplot at all.

**Comment by sjvrijn** [comment]
@gauravsawant Are you still working on this? Maybe we can work together on this if you're stuck

**Comment by tacaswell** [comment]
I think we should only do the pyplot -> Axes method links but not the Axes method -> pyplot links.

**Comment by timhoffm** [comment]
Closed by #27909.
