### ISSUE TITLE
when using plt.tight_layout(), figure title overlaps subplot titles

### ISSUE THREAD

**Issue by dfmim** [matplotlib/matplotlib#17792]
### Bug report

I have a figure with 2x3 subplots. Each subplot has a title as does the whole figure. However, even when using plt.tight_layout(), the figure title overlaps the subplot titles on the top row. Looking at StackOverflow, this has been a problem for a while.

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt
fig, axs = plt.subplots(2, 3)
fig.suptitle('ANON-WL0002')
axs[0, 0].set_title('Slice Dice')
axs[0, 1].set_title('Volumetric Dice')
axs[1, 0].set_title('Slice Hausdorff Dist.')
axs[1, 1].set_title('Volumetric Hausdorff Dist.')
axs[0, 2].set_title('All Slice Dice')
axs[1, 2].set_title('All Volumetric Dice')
plt.tight_layout()
plt.show()

```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/67604360/86045768-0db36c80-ba1a-11ea-934e-4a40f362ff43.png)

**Expected outcome**
The 'ANON-WL0002' should be above the subplot titles

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries: 

matplotlib installed as part of anaconda distribution

**Comment by anntzer** [comment]
Thanks for the report. This was fixed by https://github.com/matplotlib/matplotlib/pull/17219 which will be in 3.3.0.

**Comment by jklymak** [comment]
This is also a feature of `constrained_layout`.
