### ISSUE TITLE
Setting the norm on imshow object removes colorbar ylabel

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/matplotlib#17804]
### Bug report

**Bug summary**

When using `set_norm` on an existing `Image` object created with `imshow`, the `ylabel` on the colorbar disappears.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

fig, ax = plt.subplots(1, 1)
im = ax.imshow(np.random.random([10, 10]))
cb = plt.colorbar(im)
cb.ax.set_ylabel("Some values")
```
yields
![Screenshot_2020-06-30_14-17-14](https://user-images.githubusercontent.com/39047984/86125103-69462e80-badc-11ea-8c36-bffbea509ab7.png)

and then, after using `set_norm`
```Py
im.set_norm(Normalize(vmin=0.4, vmax=0.6))
fig
```
the colorbal label `Some values` on the right hand side has disappeared:
![Screenshot_2020-06-30_14-18-11](https://user-images.githubusercontent.com/39047984/86125202-8aa71a80-badc-11ea-943d-9cd117209ed1.png)

Maybe a new colobar gets generated and the label gets lost in the process?

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): inline
  * Python version: 3.7
  * Jupyter version (if applicable): 
  * Other libraries: 

`matplotlib` installed via `conda` (conda-forge)

**Comment by timhoffm** [comment]
The recommended way of setting the colorbar label is `cb.set_label("Some values")`, which also handles changing the norm correctly.

`cb.ax.set_ylabel("Some values")` is messing a bit with the internal state. (Not saying it should not work nevertheless (would have to look into the details of the colorbar for this).
