### ISSUE TITLE
Wheel support for aarch64

### ISSUE THREAD

**Issue by odidev** [matplotlib/matplotlib#17813]
**Summary**
Installing matplotlib on aarch64 via pip using command "pip3 install matplotlib" tries to build wheel from source code

**Problem description**
matplotlib don't have wheel for aarch64 on PyPI repository. So, while installing matplotlib via pip on aarch64, pip builds wheel for same resulting in it takes more time to install matplotlib. Making wheel available for aarch64 will benefit aarch64 users by minimizing matplotlib installation time.

**Expected Output**
Pip should be able to download matplotlib wheel from PyPI repository rather than building it from source code.

@matplotlib-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make matplotlib wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by tacaswell** [comment]
We build our mac/linux wheels via https://github.com/MacPython/matplotlib-wheels . I think the best way to move this forward would be a open a PR there to add aarch64 to the build matrix.

**Comment by odidev** [comment]
@tacaswell, thanks for the quick response. I will start working on this.

**Comment by dopplershift** [comment]
Closing in favor of having work on the other repo.

**Comment by androiddrew** [comment]
Did this get resolved?

**Comment by QuLogic** [comment]
There are aarch64 wheels for 3.4.0+.

**Comment by androiddrew** [comment]
@QuLogic Is there documentation for building and older release on Py3.6 and aarch64?

**Comment by QuLogic** [comment]
Everything is handled by cibuildwheel (#19402).
