### ISSUE TITLE
(documentation, possible first-timer bug) Typo and grammar on Legends and Annotations for tight layout guide page

### ISSUE THREAD

**Issue by ianozsvald** [matplotlib/matplotlib#17817]
### Bug report

On this page https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html we have "have the axes shring a bit to" and the text ought to read "have the axes shrin**k** a bit to".

Perhaps also "Another option is to use AxesGrid1 toolkit to explicitly create an axes for colorbar." could be "Another option is to use **the** AxesGrid1 toolkit to explicitly create an axes for **the** colorbar.".

**Comment by timhoffm** [comment]
Thanks for the report.
