### ISSUE TITLE
How to plot like DensityPlot3D?

### ISSUE THREAD

**Issue by Arlo-2020** [matplotlib/matplotlib#17854]
I want to visualize a function f(x,y,z). The DensityPlot3D function of Mathematica can be implemented.When I tried to do the same with the Scatter function of Matplotlib, I found it was not as precise as Mathematica. Or just too crude.The main problem is that scatter function cannot realize continuous change of x, y and z. If I drastically reduced the step size of the three axis data changes, the drawing time would be intolerable. So is there a better way I don't know? Thanks!

**Comment by jklymak** [comment]
Can you ask this at discourse.matplotlib.org?   Thanks!
