### ISSUE TITLE
problem while using 'symlog' Y scale

### ISSUE THREAD

**Issue by suzannejin** [matplotlib/matplotlib#17857]
I have a symmetrical data with both negative and positive values, and I want to change the Y axis to 'symlog' scale. But, after I set it to 'symlog' with linthreshy=0.0005, the symmetry is lost in a small part (with a small blank space in the upper side), as you can see from the figure below. What can be the problem?

![image](https://user-images.githubusercontent.com/43495634/86951966-8d47e680-c152-11ea-8f4d-b8074362abe4.png)

**Comment by jklymak** [comment]
@suzannejin please provide a [minimal reproducible working example](http://www.sscce.org).  Thanks

**Comment by jklymak** [comment]
I’m going to close here as I see you are discussing at https://stackoverflow.com/questions/62800853/matplotlib-symlog-axis-scaling-inconsistency
