### ISSUE TITLE
Add Hatch Example to gallery

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#17855]
The gallery has demos for using hatches:
* [Hatch Demo](https://matplotlib.org/devdocs/gallery/shapes_and_collections/hatch_demo.html#sphx-glr-gallery-shapes-and-collections-hatch-demo-py)
* [Contourf Hatching](https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contourf_hatching.html#sphx-glr-gallery-images-contours-and-fields-contourf-hatching-py)
* [Hatch filled histograms](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/filled_step.html#sphx-glr-gallery-lines-bars-and-markers-filled-step-py)

But there's no canonical example in the style of [markers](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/marker_reference.html#sphx-glr-gallery-lines-bars-and-markers-marker-reference-py) so it's a bit hard to find the list of hatches. Closest I could get was the API docs for [`.set_hatch`](https://matplotlib.org/devdocs/api/collections_api.html?highlight=hatches#matplotlib.collections.AsteriskPolygonCollection.set_hatch):

At a minimum the example should go through the basic hatches in the style of the marker docs w/ a simple patch like a square.
```
/   - diagonal hatching
\   - back diagonal
|   - vertical
-   - horizontal
+   - crossed
x   - crossed diagonal
o   - small circle
O   - large circle
.   - dots
*   - stars
```
****

the motivation for this issue was https://twitter.com/martinfleis/status/1280788674632966145
![image](https://user-images.githubusercontent.com/1300499/86938694-ae86e380-c10e-11ea-8d42-8a06462e573e.png)

**Comment by forrestm** [comment]
I'd be humbled if allowed to take this as my first issue. Could you recommend a name for the example? Maybe `shapes_and_collections/marker_styles.py` ?

**Comment by story645** [comment]
Go for it, generally if an issue is unassigned it's up for grabs. I think `hatches_styles.py` since this is a hatches example might be a bit clearer.

**Comment by forrestm** [comment]
I just created a PR. Let me know if there are any issues. Thanks!
