### ISSUE TITLE
[question] Why only major minor grid

### ISSUE THREAD

**Issue by stheid** [matplotlib/matplotlib#17866]
discussion related to #11773

![image](https://user-images.githubusercontent.com/2736207/87017267-12251580-c1d0-11ea-8748-c0de3ab531c6.png)
I am trying to plot something with week days.

- major tick monday
- minor tick workweek
- third level all days. (dashed)

## Question
Why is it constrained to minor and major and will there ever be plans to allow more flexibility?

**Comment by timhoffm** [comment]
In the early days, Matplotlib was modeled after MATLAB, which uses the major/minor pattern.

I agree that this is an unnecessary limitation. There is a rough idea floating  for rewriting the Axis/Tick/Grid logic, which then also would allow arbitrary levels. But that'd be a major endeavor and like not happening and time soon.

**Comment by stheid** [comment]
"major endeavor" :D

Thanks for the feedback. Historic decisions ...

**Comment by jklymak** [comment]
What would the API for this even be?  Ive never seen a plot with three levels of grids or tick marks, so this seems *very* specialized.  If I wanted something like that, I would just do it by hand with `axhline` and `axvline` calls.

**Comment by stheid** [comment]
see my example. In date scenarios this makes definetly sense to show multiple granularieties to allow for better coloring or so on. Of course i could program that on my one using axhline and so on, but why do i have a library when i program everything myself. I am not a C programmer.
