### ISSUE TITLE
Minor xtick list truncation

### ISSUE THREAD

**Issue by zoof** [matplotlib/matplotlib#17870]
### Bug report

**Bug summary**

When setting custom minor `xticks`, the list of `xticks` seems to be truncated for an `xtick` value of 20.  With a value of 20.01, the list is not truncated.  See https://discourse.matplotlib.org/t/solved-weird-truncation-of-minor-xticks/21370

**Code for reproduction**

```python
x_c_h = 17.
x_c_l = 20.

ax = plt.axes()

ax.set_xticks([x_c_h,x_c_l,], minor=True)
ax.set_xticklabels(['$x_c^h$', '$x_c^l$'], minor=True)

plt.xlim(0, 25)
```

**Actual outcome**

![truncate](https://user-images.githubusercontent.com/1737483/87088099-300b6e00-c202-11ea-867c-25c43d8f5a40.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

I expect the `xtick` list to not be truncated.

**Matplotlib version**
  * Operating system: Debian Buster
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable): 
  * Other libraries: Using Anaconda distribution

**Comment by timhoffm** [comment]
Minor ticks at positions of major ticks are removed by default. You can prevent that by `ax.xaxis.set_remove_overlapping_locs(False)`. However, the major and minor labels are then drawn on top of each other.
