### ISSUE TITLE
module 'wx' has no attribute 'FONTWEIGHT_LIGHT'

### ISSUE THREAD

**Issue by Shawn-Zhuang** [matplotlib/matplotlib#17874]
### Bug report

**Bug summary**
error occured whenI run the code of a specific project
```
  File "/root/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_wx.py", line 155, in RendererWx
    100: wx.FONTWEIGHT_LIGHT,
AttributeError: module 'wx' has no attribute 'FONTWEIGHT_LIGHT'
```
How to fix this? Is it because of the version of wx?
When I run import wx and wx.__version__, it is in the side-package of VTK.
```
(base) root@6e64d0f6dcca:~/SA-SSD# python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.__file__
'/root/anaconda3/lib/python3.7/site-packages/vtk/wx/__init__.py'
```

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Ubuntu 18.01, docker image
  * Matplotlib version:  3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
errors occur
```
  File "/root/anaconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 40, in _get_running_interactive_framework
    if wx and wx.GetApp():
AttributeError: module 'wx' has no attribute 'GetApp'
```
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: 

conda

**Comment by timhoffm** [comment]
This seems like a broken installation. `import wx` should not import vtk.wx. Check
```
Import sys
print(sys.path)
```
Likely wx is in there but shouldn't.

**Comment by timhoffm** [comment]
Closing due to lack of feedback.
