### ISSUE TITLE
Issue with set_xticks in 3D basemap with 'lcc' projection

### ISSUE THREAD

**Issue by ZhangAllen98** [matplotlib/matplotlib#17873]
I am using the  `mplot3d` and `basemap` to plot some data. I found if I use the `cyl` projection, the following codes would generate a normal figure. However, if I use the `lcc` projection, the `set_xticks` or `set_yticks` seems to have some problems. [![plots with lcc projection][1]][1]
 
All the meridians or parallels values are overlayed in the corner. How should I fix it?

    import numpy as np
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    from mpl_toolkits.basemap import Basemap
    
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    extent = [10,80,0,60]
    bm = Basemap(llcrnrlon=extent[0], llcrnrlat=extent[2],
                 urcrnrlon=extent[1], urcrnrlat=extent[3],
                 lat_0=30,lon_0=45,projection='lcc',  
                 # projection='cyl',
                 resolution='l', fix_aspect=False, ax=ax)
    ax.add_collection3d(bm.drawcoastlines(linewidth=0.25))
    ax.add_collection3d(bm.drawcountries(linewidth=0.35))
    ax.view_init(azim = 230, elev = 50)
    ax.set_xlabel(u'Longitude (°E)', labelpad=10)
    ax.set_ylabel(u'Latitude (°N)', labelpad=10)
    ax.set_zlabel(u'Altitude (ft)', labelpad=20)
    # Add meridian and parallel gridlines
    lon_step = 30
    lat_step = 30
    meridians = np.arange(extent[0], extent[1]+lon_step, lon_step)
    parallels = np.arange(extent[2], extent[3]+lat_step, lat_step)
    ax.set_yticks(parallels)
    ax.set_yticklabels(parallels)
    ax.set_xticks(meridians)
    ax.set_xticklabels(meridians)

    ax.set_zlim(0., 40000.)
    plt.show()

  [1]: https://i.stack.imgur.com/5aI5j.png

**Comment by WeatherGod** [comment]
The problem is that you need to project the lat/lons into the lambert
conformal projection.

Also, please note that basemap is no longer actively supported, although
admittedly, I am not sure how one can do 3D plots like this with cartopy.
