### ISSUE TITLE
Unexpected text placement when calling annotate within a loop

### ISSUE THREAD

**Issue by gpitton** [matplotlib/matplotlib#17887]
### Bug report

**Bug summary**
`annotate` does not place the text correctly when the coordinates are specified with a mathematical operation.

**Code for reproduction**

```python

import matplotlib
import matplotlib.pyplot as plt

points = [[0, 0], [1, 1], [1, 0]]
coeffs = [1, 1, 1]

x = [p[0] for p in points]
y = [p[1] for p in points]

plt.figure()
for i, c in enumerate(coeffs):
    plt.annotate(str(c), (x[i] + 0.2, y[i] + 0.2))
    #plt.text(s=str(c), x=x[i] + 0.2, y=y[i] + 0.2)


plt.axis('off')
plt.savefig('test.svg')
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/9949324/87222046-74188300-c368-11ea-9152-9f564d5b075d.png)

**Expected outcome**
I was expecting to see the digit "1" appearing three times, arranged in a triangular shape.
The same problem appears if I use `text` instead of `annotate`, as in the commented line.

It seems that removing the sum in `x[i] + 0.2` solves the problem, but this does not seem to be the expected behaviour.

**Matplotlib version**
  * Operating system: Linux (ubuntu)
  * Matplotlib version: 3.2.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.7

I installed python and matplotlib with conda, using the default channel.

**Comment by jklymak** [comment]
You are annotating outside your axes limits of [0, 1], so the annotations are clipped.    `annotation` and `text` don't participate in the autoscaling of the axes.  This is expected behaviour, so I'm closing. Your work around is `plt.xlim(0, 1.3); plt.ylim(0, 1.3)`.
