### ISSUE TITLE
hidden y-ticks despite using tight_layout() with basemap

### ISSUE THREAD

**Issue by jerabaul29** [matplotlib/matplotlib#17880]
Despite using ```tight_layout()```, the y-ticks corresponding to parallels are hidden by pcolormesh colorbars.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

fig, ax = plt.subplots()

basemap_obj = Basemap(llcrnrlon=4.0, llcrnrlat=55.5, urcrnrlon=13.0, urcrnrlat=61.5,
                      lat_0="58.0", lon_0=7.0,
                      projection="lcc"
                      )

parallels = np.array([56.5, 60.5])
basemap_obj.drawparallels(parallels, labels=[False, True, True, False])
meridians = np.array([6.0, 11.0])
basemap_obj.drawmeridians(meridians, labels=[True, False, False, True])

lat = np.array([[56.5, 56.5], [60.5, 60.5]])
lon = np.array([[6., 11.], [6., 11.]])
dat = np.array([[1., 1.], [1., 1.]])

(lon_m, lat_m) = basemap_obj(lon, lat)

my_cmap = plt.get_cmap('rainbow')

cs = basemap_obj.pcolormesh(lon_m, lat_m, dat, cmap=my_cmap)
cb = basemap_obj.colorbar(cs, label="label")

plt.tight_layout()

plt.savefig("example.png")

plt.show()
```

**Actual outcome**

![example](https://user-images.githubusercontent.com/8382834/87160311-0fefb380-c2c3-11ea-8124-bc253cfb6bb2.png)

**Expected outcome**

I would hope / expect that tight_layout() could help avoid the hiding. At the current time, this can be obtained by adding a pad, for example changing to:

```python
cb = basemap_obj.colorbar(cs, label="label", pad=0.60)
```
produces a figure without the hiding.

![example](https://user-images.githubusercontent.com/8382834/87160938-103c7e80-c2c4-11ea-89b1-3e09d0a18740.png)

Any way that tight_layout could do that without the user to need to do anything? That would be very helpful, as I had to spend quite a bit of time to find the way to solve it, and I guess other users have the same problem now and then :) .

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.2.2
  * Matplotlib backend: GTK3Agg
  * Python version: 3.8.2
  * Other libraries: basemap 1.2.1, installed with ```sudo apt-get install -y python-mpltoolkits.basemap```

Maplotlib installed from pip.

**Comment by jklymak** [comment]
This is really a Basemap issue, not a matplotlib issue, since 
```
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.yaxis.tick_right()
pc = ax.pcolormesh(np.random.randn(30, 30))
fig.colorbar(pc)

plt.tight_layout()
plt.savefig("example.png")

plt.show()
```

works fine.  

Unfortunately basemap is end-of-life.  I can't even get it to work with master matplotlib.  We really suggest people use carroty these days (whether it has the same problem, I'm not sure).  

I'm going to close this here, because there is not anything matplotlib can directly do.

**Comment by jerabaul29** [comment]
Ok, thanks for the info, will check carroty :) .

**Comment by jklymak** [comment]
Carrots are good, but I guess I meant cartopy :wink:

**Comment by jerabaul29** [comment]
Autocorrect 😂😂

**Comment by jerabaul29** [comment]
(but you were the first to write carroty, so it is not only my autocorrector 😂)
