### ISSUE TITLE
Unwanted ticks and scientific labels added to log scale when set for scaler labels

### ISSUE THREAD

**Issue by BoulderPapa** [matplotlib/matplotlib#17886]
A log scale for the y axis is wanted with scaler labels. Depending on the range of y values, extra ticks with scientific notation for the labels are added to the plot. The scalar labels and tick marks are there as they should be.

Using Jupyter Notebook 6.0.3, Python 3.8.2, IPython 7.14.0 and matplotlib 3.2.2 on MacOS Catalina:

Sample Code:

fig = plt.figure()

ax=fig.add_axes([0.,0.,1.,1.],yscale='log')

ax.yaxis.set_major_locator(mticker.MaxNLocator())
ax.yaxis.set_major_formatter(ScalarFormatter())

ax.plot([1,3,5],[60,360,110])

plt.show()

Output:

![image](https://user-images.githubusercontent.com/34756212/87215919-25cb9b80-c2f8-11ea-9275-764021cb6cde.png)

The labels 6 x 10^1 and 3 x 10^2 and their tick marks should not be there and are not reported by get commands.

Using Jupyter Notebook 6.0.3, Python 3.8.2, IPython 7.14.0 and matplotlib 3.2.2 on MacOS Catalina
Python installed with Homebrew, everything else loaded with pip in my single venv virtual environment.

**Comment by efiring** [comment]
Those labels and ticks are coming from the minor locator, which was set, along with a corresponding major locator, when you set the scale to 'log'.  If you include the line
```python
ax.yaxis.set_minor_locator(mticker.NullLocator())
```
the minor ticks will go away.
I can see why you would be surprised by what you found, but it's not a bug.

**Comment by BoulderPapa** [comment]
Thanks, I tried everything I could think of over a two day period. With your help I got it working. Still seems like strange behavior, but I understand.
