### ISSUE TITLE
macosx backend warns when using the zoom method

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#17905]
### Bug report

**Bug summary**

The current master branch warns about calling release() at zoom stop within the macosx backend (all the others work fine for me). This seems like it should warn if an external user is creating their own backend or overriding functionality, but not the included macosx backend, since there is no way for a user to get rid of the message. (Panning seemed to be fine, even though there is a similar warning in the backend_bases there)

**Code for reproduction**

```python
In [1]: import matplotlib

In [2]: matplotlib.use('macosx')

In [3]: import matplotlib.pyplot as plt

In [4]: fig, ax = plt.subplots()

In [5]: ax.plot([0, 1], [0, 1])
Out[5]: [<matplotlib.lines.Line2D at 0x7fcb3910d850>]

In [6]: plt.show()
MatplotlibDeprecationWarning: Calling an overridden release() at zoom stop is deprecated since 3.3 and will be removed two minor releases later; override release_zoom() instead.
```

**Expected outcome**

No warning from an MPL included backend.

**Comment by dstansby** [comment]
I can reproduce this on master, and with 3.3.0rc1. Going to label as release critical as we probably don't want deprecation warnings showing up when doing normal things.
