### ISSUE TITLE
rcParams restrictions on frame_formats are out of sync with supported values (HTMLWriter)

### ISSUE THREAD

**Issue by bmcfee** [matplotlib/matplotlib#17908]
### Bug report

jshtml animation uses `HTMLWriter` to render animation frames.  Digging into the code for this, we see that HTMLWriter lists `supported_formats`:

https://github.com/matplotlib/matplotlib/blob/c54a5a9b45eff7148e73e9134f206126842307e1/lib/matplotlib/animation.py#L785

However, there is no way to make use of this.  The `to_jshtml` method of animation does not provide an interface to specify the frame format, so it must be pulled from `rcParams`.  `rcParams`, in turn, does not allow `svg` as an option.

**Code for reproduction**

```python
import matplotlib
matplotlib.rcParams['animation.frame_format'] = 'svg'
```

**Actual outcome**

```python
# ... traceback cruft

ValueError: Key animation.frame_format: Unrecognized animation.frame_format string 'svg': valid strings are ['png', 'jpeg', 'tiff', 'raw', 'rgba']
```

**Expected outcome**

rcParams should allow setting frame formats that are supported by any animation writer, not just the ones supported by all.

Aside: `rcParams` allows `raw` but HTMLWriter doesn't.  So there's already precedent.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg  (but irrelevant to this issue)
  * Python version: 3.7.6
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

conda (main anaconda)

**Comment by story645** [comment]
Thanks for opening the PR against the rcparams. Would it be feasible/make sense to add it as a keyword argument to MovieWriter (and therefore it's subclasses)?

**Comment by bmcfee** [comment]
> Would it be feasible/make sense to add it as a keyword argument to MovieWriter (and therefore it's subclasses)?

I don't see why not.  However, looking at the code for this, I think there might be a bigger family of changes to be made to expose writer behavior through the `Animation` object.  For example, there's no obvious way to set loop/reflect behavior in `to_jshtml`, and the natural way to do it would be exposing keyword arguments like you suggest.

Maybe it makes more sense to handle that in a separate PR?

**Comment by bmcfee** [comment]
To follow up on this, the current call to `HTMLWriter` only passes three arguments:

https://github.com/matplotlib/matplotlib/blob/6b2cecc5f6cd598477507d8765020eb35a99b107/lib/matplotlib/animation.py#L1359-L1361

but there are several more parameters that it could set:

https://github.com/matplotlib/matplotlib/blob/6b2cecc5f6cd598477507d8765020eb35a99b107/lib/matplotlib/animation.py#L796-L798

So we could thread through the `frame_format` parameter in this PR, but I think it might be better handled in a separate PR that focuses entirely on exposing internal animation parameters.  This I think is independent of the issue in this thread, where the rcParams does not allow us to set a default at all currently.  Fixing the rcparams check (#17909 ) seems necessary to me, exposing more API seems nice-to-have.
