### ISSUE TITLE
Extend hatch reference

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#17918]
Followup to #17884.

😲 I just learned that you can

- repeat symbols to increase density, e.g. `hatch='//'`
- combine symbols, e.g. `hatch='/-'` for a rhomic pattern

To do:

- Add both variants to the hatch style reference. I'd go for description + example below the existing overview.
- For the existing overview reduce the figure size to (9, 4.5). The figure is currently larger than the available horizontal space and is thus scaled down resulting in a blurred appearance.

Ping @forrestm: You might be interested in picking this up.

**Comment by forrestm** [comment]
Absolutely, thanks.

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib/pull/17917

**Comment by WeatherGod** [comment]
I think this lends credence to the argument that there should be two separate things, a quick-to-grok reference of the available hatches (which was recently merged into the documentation), and a demo showcasing what is possible with the hatches like this. The first is a useful reference table, while the second is showcasing via code how to use hatches.

**Comment by timhoffm** [comment]
I would split it slightly differently:

- Reference: "Which hatches can I use?". This includes the basic hatches as well as repetition and composition rules.
- Example: "How do I apply hatches?". Example plot(s) using selected hatches.

**Comment by jklymak** [comment]
I'd just put the "reference only" on a cheatsheet.  

The fundamental problem is too many examples.  If I were organizing the examples featuring "hatch" I'd just put them all on one page and call it "hatching".  Then if someone wants to add hatches to a contour or a bar, they would find their example there.  To me this would be much more sensible than one hatch examples in "lines, bars and markers", one in "images contours and fields" and, now, two in "shapes and collections".  

But clearly I am outvoted on this...

**Comment by story645** [comment]
> I'd just put them all on one page and call it "hatching". Then if someone wants to add hatches to a contour or a bar, they would find their example there. To me this would be much more sensible than one hatch examples in "lines, bars and markers", one in "images contours and fields" and, now, two in "shapes and collections".

I actually agree w/ you here, but I think it's a question of what's the focus of the example, and also the real solution here probably is if we could tag examples and then the user could filter down to just the tags they're interested in.

**Comment by jklymak** [comment]
... again, I don't think there is any benefit to examples being restricted to only one "focus", "purpose", or type of user.  We are needlessly segmenting information.

**Comment by story645** [comment]
>... again, I don't think there is any benefit to examples being restricted to only one "focus", "purpose", or type of user. We are needlessly segmenting information.

I find it sometimes really hard w/ some of the more complex examples to parse out which piece of code is doing the thing I'm interested in and that's fundamentally why I want the smaller examples to scaffold the more complex ones (that I think should more often be smallish tutorials of building block, building block, composite). And maybe you're right that the reference examples shouldn't really live in the gallery but that seems to be the first place many users look. 

Also the drum I keep banging is that it's a discoverability problem - is the user looking for hatches or are they looking for images and see oh hatching might be cool, do they know we call colormapping normalization, etc? Especially w/ the gallery having so many images, a skim often isn't enough to find the thing you're after...and I think the complex examples risk obscuring that even more.

**Comment by forrestm** [comment]
I have created the PR-- Added density and combination hatching examples #17921 . I created the combination examples shown below. Let me know if different combinations are preferred.
![download-1](https://user-images.githubusercontent.com/11200528/87456228-3ddb3d80-c5cc-11ea-98ae-a2f813a1bc94.png)

**Comment by jklymak** [comment]
> I find it sometimes really hard w/ some of the more complex examples to parse out which piece of code is doing the thing I'm interested in and that's fundamentally why I want the smaller examples to scaffold the more complex ones

I would address that by having the individual examples increase in complexity, versus having multiple examples.  

> Also the drum I keep banging is that it's a discoverability problem 

Thats a good drum to bang.  But I would still say its easier to discover things if the library features are laid out in a concisely.

**Comment by story645** [comment]
Thanks @forrestm - I particularly like '+o' 😉 

> I would address that by having the individual examples increase in complexity, versus having multiple examples.

My concern their is users would focus on the final figure in the example and not realize that the building blocks they also need are in there...and we can't cover every possible fully fleshed out figure.

**Comment by jklymak** [comment]
> My concern their is users would focus on the final figure in the example

Examples can have multiple figures.  I don't know why users would fixate on the final figure and not the first.

**Comment by story645** [comment]
> Examples can have multiple figures. I don't know why users would fixate on the final figure and not the first.

because that's usually the thumbnail being used to generate the sphinx gallery preview which is what folks are using to browse the gallery.

**Comment by jklymak** [comment]
The thumbnail is the first figure by [default](https://sphinx-gallery.github.io/stable/configuration.html#choosing-the-thumbnail-image), and you can change which figure gets the thumbnail with a comment near the top:

```
# sphinx_gallery_thumbnail_number = 7
```

**Comment by story645** [comment]
but @jklymak in the example/gallery case, what would you choose as the thumbnail/title combination to fully convey that the example has all those steps?

**Comment by timhoffm** [comment]
Closed by #17921.

I propose to keep the example / reference organization discussion for another time. Possibly with a separate issue or in the dev call.
