### ISSUE TITLE
how to update y axis data in a 3D graph

### ISSUE THREAD

**Issue by arshdeepsingh2267** [matplotlib/matplotlib#17934]
If we consider a 2D graph, then `something.set_ydata(dataY)` "set_ydata" is used to update y axis data. Likewise, is it possible to update y axis data in a 3D graph, as it says:
`something.set_ydata(data_np)`
`AttributeError: 'Poly3DCollection' object has no attribute 'set_ydata'`

**Comment by dopplershift** [comment]
That's because in this case the return is a `Poly3DCollection`, which is a subclass of `PolyCollection`--these classes do not have (for either 2D or 3D) a `set_ydata` method. You need to use `set_verts`.
