### ISSUE TITLE
documenattion and behavior do not match for suppressing (PDF) metadata

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#17936]
### Bug report

**Bug summary**

We document that if you pass `metadata=None` through to the `PdfPages` we will not emit the auto-generated creator / producer / date metadata (https://matplotlib.org/3.3.0/api/backend_pdf_api.html#matplotlib.backends.backend_pdf.PdfPages) the code does not actually support this:

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from io import BytesIO
buf = BytesIO()
plt.gcf().savefig(buf, metadata=None, format='pdf')
buf.seek(0)
assert b'Matplotlib' not in buf.getvalue()

```

**Actual outcome**

```
----> 1 assert b'Matplotlib' not in buf.getvalue()

AssertionError: 
```

-----

Labeling this as a good first issue as there is no API design or controversy here (the code does not do what it is documented to do and I do not think it is controversial to have a way to fully suppress the generation of meta-adat).   

The fix is likely spread across `Figure.savefig`, `FigureCanvasPdf.print_pdf`, and the `PdfPages` class.  I suspect we need to change of the default values to a sentinal (rather than `None`), but not sure exactly where.  This should be straight forward and contained to one module, but not an issue to learn Python on.

**Comment by QuLogic** [comment]
It doesn't actually say that; what it says is if you pass a _value_ of `None`, then the specified key will be overridden.
```
>>> import matplotlib.pyplot as plt
>>> from io import BytesIO
>>> buf = BytesIO()
>>> plt.gcf().savefig(buf, metadata={'Creator': None, 'Producer': None}, format='pdf')
>>> buf.seek(0)
>>> assert b'Matplotlib' not in buf.getvalue()
```
(no exception raised)

**Comment by JonathanSheng** [comment]
new to open source, curious to help

**Comment by yuyichao** [comment]
Ref https://github.com/matplotlib/matplotlib/pull/17969#discussion_r456927866 . Seems to me that this would be a breaking change and if done, needs to apply to all backends supporting metadata.

**Comment by jklymak** [comment]
Yes, I agree with that.  I'll close because I don't think this is too desirable, but @tacaswell feel free to re-open if you disagree and think we should support this.

**Comment by tacaswell** [comment]
I'm going to re-open this as currently our docs and our behavior are out of sync.  Either we need to make the code do what the docstring says it does or change the docstring to match the code.

**Comment by QuLogic** [comment]
But it's _not_ what our docs say: https://github.com/matplotlib/matplotlib/issues/17936#issuecomment-658979110

**Comment by tacaswell** [comment]
:sheep: ok, definitely a reading-comprehension failure on my part...
