### ISSUE TITLE
rc_context context manager does not correctly enable latex preamble

### ISSUE THREAD

**Issue by mueslo** [matplotlib/matplotlib#17931]
### Bug report

**Bug summary**

rc_context does not enable latex preamble

```python
import matplotlib as mpl
import matplotlib.pyplot as plt

with mpl.rc_context(rc={'text.usetex': True, 'font.family': 'serif', 'text.latex.preamble': r'\usepackage{xfrac}'}):
    plt.plot([0, 1, 2], [0, 1, 4])
    plt.title(r'$\sfrac{7}{2}$')

plt.show()
```

**Actual outcome**

```
! Undefined control sequence.
<recently read> \sfrac

l.14 ...ze{12.000000}{15.000000}{\sffamily $\sfrac
                                                  {7}{2}$}
No pages of output.
Transcript written on 299b9741a445257722d94d8d424b0440.log.
```
preamble not contained in intermediate `.tex` file

With `plt.rc('text.latex', preamble=r'\usepackage{xfrac}')` before the context manager, it renders correctly, but of course globally sets the preamble which is undesired.

**Expected outcome**

Renders correctly and preamble contains '\usepackage{xfrac}'

**Matplotlib version**

  * Operating system: N/A
  * Matplotlib version: matplotlib==3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): does not depend on backend
  * Python version: 3.8
  * Jupyter version (if applicable): also occurs outside of jupyter
  * Other libraries: N/A

**Comment by QuLogic** [comment]
This is deep in the code somewhere, because I thought the problem was that running LaTeX happened at draw time (and thus outside the context.) However, indenting `plt.show()` to be in the context manager does _not_ fix it.

**Comment by anntzer** [comment]
That's just because a closing `$` is missing.
Making each Text object remember the corresponding preamble at its instantiation time would be possible, but is it really worth the effort?

**Comment by mueslo** [comment]
> 
> 
> That's just because a closing `$` is missing.
> Making each Text object remember the corresponding preamble at its instantiation time would be possible, but is it really worth the effort?

If it remembers the 'text.usetex' property (which it does), it should also remember all other related properties, otherwise it is highly inconsistent.

**Comment by anntzer** [comment]
Remember that text.latex.preamble is not officially supported.  I would suggest just documenting the limitation, e.g.
```patch
diff --git i/lib/matplotlib/text.py w/lib/matplotlib/text.py
index 196c29fa5..21b2f3458 100644
--- i/lib/matplotlib/text.py
+++ w/lib/matplotlib/text.py
@@ -1198,6 +1198,14 @@ class Text(Artist):
         usetex : bool or None
             Whether to render using TeX, ``None`` means to use
             :rc:`text.usetex`.
+
+        Notes
+        -----
+        usetex mode can be further customized using :rc:`text.latex.preamble`,
+        but this setting is only supported on a best-effort basis.  This
+        rcParam is only read and applied at draw time; hence, if using, for
+        example, `.rc_context` to temporarily set it, the context manager
+        should wrap the call to `~.pyplot.show()` or `~.Figure.savefig`.
         """
         if usetex is None:
             self._usetex = rcParams['text.usetex']
```
Note that e.g. in your case you could just globally set `rcParams["text.latex.usetex"] = r"\usepackage{xfrac}"` and things would work just fine.  Adding the setting on a per-Text object basis would also need to figure out e.g. whether we re-read the setting if one does `text.set_usetex(False); text.set_usetex(True)`.

**Comment by mforbes** [comment]
Issues are not just limited to `usetex`.  Some aspects of setting fonts will also fail if the figure is displayed or saved outside of the context.  The key is to make sure the figure is displayed in the context.

```python
# Running in a Jupyter notebook
%pylab inline

style_dict = {
    'text.usetex': False,
    'font.family': "serif",
    #'font.family': "Times New Roman",  # Setting this directly works.
    'font.serif': ["Times New Roman", "Palatino"],
}

with plt.style.context(style_dict, after_reset=True):
    plt.title("PRQabc123.456")
    display(plt.gcf())       # Works
    plt.savefig("good.png")  # Works
plt.savefig("bad.png")      # Fails - falls back to DejaVu Serif
plt.show()                  # Fails - falls back to DejaVu Serif
```

**Comment by fpavogt** [comment]
Just stumbled upon this issue myself (i.e. the fact that `rc_context` does not enable `text.latex.preamble`), and am very relieved to see that this is known bug 😜 . 

Bearing in mind that `text.latex.preamble` is not officially supported, is there a way around this bug ? 
(Would this discussion perhaps be a better fit for matplotlib's discourse ?)

My current workaround is to set `text.latex.preamble` separately using `plt.style.use()` (which evidently is not ideal, since it is no longer within the context). Applying this to the top (fixed) MWE, I noticed that for this to work, `plt.style.use()` must be called from *outside* the context. Namely:

```
import matplotlib as mpl
import matplotlib.pyplot as plt

# Calling plt.style.use() here as the intended effect ...
plt.style.use({'text.latex.preamble': r'\usepackage{xfrac}'}) 

with mpl.rc_context(rc={'text.usetex': True, 'font.family': 'serif', 'text.latex.preamble': r'\usepackage{xfrac}'}):

    # ... but calling plt.style.use() here has no effect !
    #plt.style.use({'text.latex.preamble': r'\usepackage{xfrac}'}) 

    plt.plot([0, 1, 2], [0, 1, 4])
    plt.title(r'$\sfrac{7}{2}$')
    plt.show()
```

Is this expected ? I naively would have expected `plt.style.use()` to have the same impact everywhere ... but maybe I just don't understand all the implications of using it in context ?

(Side note: while debugging this, care should be take to clear the "LaTeX - mpl" cache each time. Else, **if** the given LaTeX string(s) could be processed once, then the example will always "work" because nothing is actually re-processed, but just fetched from the cache.)

**Comment by fpavogt** [comment]
Using Python 3.11.4 and matplotlib 3.7.2, this issue looks fixed to me. I can now set the `text.latex.preamble` rcParams correctly in a context, as illustrated with the following MWE:

```
import matplotlib as mpl

# Set a fancy matplotlib context ...
with mpl.rc_context(rc={'text.usetex': True, 'font.family': 'serif',
                        'text.latex.preamble': r'\usepackage{xfrac}'}):

    print('\nInside context:')
    print(f"  'text.usetex': {mpl.rcParams['text.usetex']}")
    print(f"  'text.latex.preamble': {mpl.rcParams['text.latex.preamble']}")

# Verify that out-of-context, things still look like the default ...
print('\nOutside context:')
print(f"  'text.usetex': {mpl.rcParams['text.usetex']}")
print(f"  'text.latex.preamble': {mpl.rcParams['text.latex.preamble']}")
```

which returns:

```
Inside context:
  'text.usetex': True
  'text.latex.preamble': \usepackage{xfrac}

Outside context:
  'text.usetex': False
  'text.latex.preamble': 
```

**Comment by tacaswell** [comment]
Given @fpavogt comment I am going to close this.  Thank you!
