### ISSUE TITLE
Label subscript cutoff when increasing dpi

### ISSUE THREAD

**Issue by jacobmerson** [matplotlib/matplotlib#17944]
### Bug report

**Bug summary**

When using a (latex) fraction in the y axis the subscript is cutoff when the dpi and fontsize are increased. This behavior does not appear when using the default settings for figure dpi (100).

**Code for reproduction**
```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots(dpi=300)
ax.set_ylabel(r"$\frac{E_0}{E_{\infty}}$",
              rotation=0,fontsize=30,labelpad=20)
plt.savefig("test.png")
```

**Actual outcome**
![test](https://user-images.githubusercontent.com/2366140/87635244-b8ab7200-c70c-11ea-98ce-ef815c7a7b72.png)

**Expected outcome**
I do not expect the subscript to be cutoff.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.6
  * Jupyter version (if applicable): N/A
  * Other libraries: None

Matplotlib was installed with baseline anaconda python

**Comment by anntzer** [comment]
looks like a dupe of https://github.com/matplotlib/matplotlib/issues/15313.
