### ISSUE TITLE
Better Black&White/Gray color scheme, potentially cycling hatches ?

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#17945]
The current B&W/gray theme is a bit harsh and have either too strong or too weak contrast (IMHO), with few choices, some libraries like seaborn (sns.countplot) will actually count the number of color and may decide not to use the default style is not enough variants are available. 

THere are cases where you cannot avoid BW/grayscale, in particular when printing in many examples, which is often the case for books. 

Poking around I thought of trying to have themes cycles through both colors and hatches/patterns to give a different style to no avail.

I might be able to get a real-world use case example, but will need to adapt the code/data as it is copyrighted. 

(Issue Prompted by twitter thread https://twitter.com/story645/status/1283599892741488640)

**Comment by WeatherGod** [comment]
Are you having difficulty with specifying cycling hatches/linestyles in the property cycler of the style file? Are you running into bugs? I know there used to be an issue awhile ago where if you have hatches in your property cycle, and then did `plot()`, it'll fail because hatch isn't a valid property for Line2D objects, or something to that effect, but I am pretty sure that has been addressed since then.

I certainly would love to see hatch and line style cycling used more in the various styles.

**Comment by Carreau** [comment]
> Are you having difficulty with specifying cycling hatches/linestyles in the property cycler of the style file?

Yes for that, I haven't figured that out. 

> Are you running into bugs?

In seaborn I guess it does not take hatches into consideration for "how many styles are available". I'm also not sure all plots are going to cycle through hatches/colors, but I haven't spent too much time on it. 

my local modification to `matplotlib/mpl-data/stylelib/grayscale.mplstyle` so far are:

```
-axes.prop_cycle: cycler('color', ['0.00', '0.40', '0.60', '0.70'])
+axes.prop_cycle: cycler('color', ['0.20', '0.40', '0.60', '0.80']) +  cycler('linestyle', ['-', '--', ':', '-.'])
```

And I would need to spend more time on it to see what is possible and what it affects.

So far I've went with tweaking the style on a per-graph basis.

**Comment by jklymak** [comment]
> So far I've went with tweaking the style on a per-graph basis.

I'd argue that's what everyone should do.  For some plots dashes or dots look great.  For other plots they are terrible.  For some plots changing the line thickness is the easiest thing.  I'm not sure there are general solutions here?

**Comment by WeatherGod** [comment]
Could you provide more detail about the problems you are having? One common pitfall I have seen is people trying to spread the property cycle spec out across multiple lines. This is tricky to do in mplstyle files (maybe impossible, I don't remember)

**Comment by Carreau** [comment]
> I'd argue that's what everyone should do. For some plots dashes or dots look great. For other plots they are terrible. For some plots changing the line thickness is the easiest thing. I'm not sure there are general solutions here?

Well but if you can allow me to tweak only 20% of all the plots, and avoid having to do the same tweaks everytime, it is worth it. I understand that you can't make _everything_ perfect, 
but really _pure black_ as the default first color in grayscale ?  And only four variants of gray ?

> Could you provide more detail about the problems you are having? One common pitfall I have seen is people trying to spread the property cycle spec out across multiple lines. This is tricky to do in mplstyle files (maybe impossible, I don't remember)

No I don't think it was it, and I'll have to retry. It's also not something I can easily share as it is not mine and have copyright questions, but I can try to reduce it. Also the code has change quite a bit and I'll have to get a version where all the manual adjustments that other have do to make it B&W are reverted which could take some time, and also this is more a meta issue "The default B&W is not great", there will likely be lots of smaller specific problem.

**Comment by story645** [comment]
> For some plots dashes or dots look great. For other plots they are terrible. For some plots changing the line thickness is the easiest thing
MEP26/#6550 - artist level styling is kinda getting at that. 

And I encouraged @Carreau to open the issue 'cause I've been in a similar boat (graphs for [Italian Prisons in the Age of Positivism, 1861-1914 ](https://www.bloomsbury.com/uk/italian-prisons-in-the-age-of-positivism-1861-1914-9781350055346/)) and reused a lot of the same 5 colors that worked across graphs so a style sheet would likely work. Totally agree that black should not be the first color in the cycle (and probably shouldn't be there at all).

**Comment by jklymak** [comment]
I'm sure new styles are always welcome!  Is there more being asked for here? 

>MEP26/#6550 - artist level styling is kinda getting at that. 

Dashes and dots work well for smooth data; they don't work if there is a lot of high frequency content in your data - you need continuous lines.  Both of them would still be created using `Line2D`
