### ISSUE TITLE
Wheels not compatible with numpy 1.15

### ISSUE THREAD

**Issue by takluyver** [matplotlib/matplotlib#17951]
The metadata in the wheels claims `numpy (>=1.15)` is required. But installing with numpy 1.15.4 doesn't work:

```python
$ python3 -m venv testenv
$ testenv/bin/pip install matplotlib 'numpy<1.16'
# ... matplotlib installs from a wheel ...
$ testenv/bin/python -c "import matplotlib.pyplot"
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/takluyver/Code/pycalibration/testenv/lib64/python3.8/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/home/takluyver/Code/pycalibration/testenv/lib64/python3.8/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
```

It works with `numpy<1.17` (which gets 1.16.6).

I noticed this because numpy 1.15.4 appears to be the default on Travis for Python 3.7.

**Comment by billbrod** [comment]
We've also had this problem, showing up in the same way (numpy 1.15.4 on Travis for Python 3.7)

**Comment by tacaswell** [comment]
Labeled as 3.3.1, but we may want to re-build and re-upload the wheels for 3.3.0 as I suspect that this is a packaging issue.

**Comment by tacaswell** [comment]
I just pushed https://github.com/MacPython/matplotlib-wheels/commit/4f28d775243ff4de77c75acbd617b62e426ae75b to  https://github.com/MacPython/matplotlib-wheels/tree/build-3.3.x .  I think what happened was we were pinning too-old in the base environment and then pip was happily upgrading numpy to 1.19 to run the build:

https://travis-ci.org/github/MacPython/matplotlib-wheels/jobs/708920769#L1228-L1229

I guess we now get to learn how to mark packages as "bad" on pypi and replace them :/

**Comment by tacaswell** [comment]
ok, so the wheels now published to https://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/ work and using `wheel unpack` and `wheel pack --build-number` we can re-pack the wheels with a different file name (but the same version) so pypi will take them.

We have the same problem with the OSX wheels so we should do this process with all of them.  That leaves the question of if we should leave the broken wheels up or delete them?

**Comment by tacaswell** [comment]
I have uploaded the wheels generated by  https://github.com/MacPython/matplotlib-wheels/commit/47e4290d86f3fa8a29529f392ef0fd766ccc1ef2 to pypy as build 1

----

code that re-packed everything:

```xonsh
for fname in p'../'.glob('matplotlib*whl'):
    print(fname)
    wheel unpack @(fname)
    wheel pack --build-number=1 matplotlib-3.3.0
    rm -rf matplotlib-3.3.0
```

**Comment by tacaswell** [comment]
@takluyver Can you confirm that things are working for you again?

**Comment by takluyver** [comment]
The build in question is working again. Thanks for responding so quickly! :-)
