### ISSUE TITLE
Feature Request (Documentation): Add links to google colab for various examples.

### ISSUE THREAD

**Issue by ishank-dev** [matplotlib/matplotlib#17950]
**Feature summary**

I often feel the need to execute the code right after I see the example or tutorials. Having the examples hosted on google colab would certainly help in quickly running the code as well as it will allow beginners to run the code right on the browser if they have no prior experience with python notebook or command-line tools.

**Comment by jklymak** [comment]
This closely related to the request to host such links to binder.  #11415  

I don't personally see the need for such a functionality, and I think it will lead to a lot of bug reports about things not working on binder or google colab.  But thats just my vote.

**Comment by story645** [comment]
I'm +1 on binder since we already generate the notebooks as part of sphinx-gallery builds & can host our own binder instance & automate some things via github actions. 

I'm -1 on collab since it's google owned and run and that lack of control already often makes it annoying to run collab scripts.

**Comment by jklymak** [comment]
Lets close this as basically a duplicate and carry on any discussion at #11415...
