### ISSUE TITLE
ConciseFormatter doesn't always label start of year properly

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#17958]
The January in this plot doesn't get labeled as 2021 in this plot:

>using `AutoDateLocator(minticks=20, maxticks=30)` you get
>![image](https://user-images.githubusercontent.com/34161/87840541-1054f500-c855-11ea-9999-4491dd538015.png)
>
>There are no `zeroes` helping at the year mark here (actually the zero are month because of the wrong level), which makes >for a pretty fun read of this plot.
> People wonder: is it 2020-2021 or 2021-2022 ? Why is there `Jun` in the bottom right?

_Originally posted by @leolchat in https://github.com/matplotlib/matplotlib/pull/17269#issuecomment-660394605_

```python
import matplotlib.pyplot as plt
import numpy as np
plt.rcParams['date.converter'] = 'concise'
import matplotlib.dates as mdates

locator = mdates.AutoDateLocator(minticks=20, maxticks=30)

dates = [np.datetime64( '2020-06-06 18:08:30'),  np.datetime64('2021-06-06 18:08:31')]

fig, ax = plt.subplots()
ax.plot(dates, [0, 1])
ax.set_xlim(np.datetime64( '2020-06-06 18:08:30.3'), np.datetime64( '2021-06-06 18:08:30.5'))
ax.xaxis.set_major_locator(locator)
plt.show()

```

**Comment by leolchat** [comment]
That is because the level is at the day level, not month (which is showed by the offset which includes the month `2021-Jun`).
That level is correct with the current level definition (https://github.com/matplotlib/matplotlib/pull/17269#issuecomment-659849982):
>The code goes backwards to test the level because you want the level to be at the smallest non-repeating level. i.e. you could have "2012, Apr, Jul, Oct, 2013, Apr" and that can't be at the annual level (0) because you want the months to be labelled (i.e. level 1).

**Comment by jklymak** [comment]
Yes, that's right.  For it would be nice to have a way to go up two levels if necessary (hopefully three levels are not necessary)

**Comment by leolchat** [comment]
I have started 2 PRs showing different possible options, will post them soon.
