### ISSUE TITLE
Document how to use mathtext to obtain unicode minus instead of dashes for negative numbers

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#17967]
When using `FormatStrFormatter` on the *x*-axis, the negative numbers have a dash - in front instead of a minus −.

```python
θ = linspace(-1.5, 0) * 2 * π
y = sin(θ)
plot(θ / π, y)
gca().xaxis.set_major_formatter(FormatStrFormatter('%g π'))
```

![-sine-π](https://user-images.githubusercontent.com/2119355/87868680-6cf40500-c966-11ea-9919-dff7697dafff.png)

Without the formatter, all looks good.

```python
x = linspace(-1.5, 0)
y = sin(x * 2 * π)
plot(x, y)
```

![-sine](https://user-images.githubusercontent.com/2119355/87868620-d0c9fe00-c965-11ea-9c06-76ec8c4fe764.png)

I'm wondering who's handling the conversion of the dash into a minus, and how to recreate that when using `FormatStrFormatter`.

**Comment by dstansby** [comment]
It's python string formatting that's directly formatting the number, the code is `return self.fmt % x`, so I think you have to find a format code that formats the string with a minus.

**Comment by timhoffm** [comment]
Should `FormatStrFormatter` respect `rcParams['axes.unicode_minus']`? On the one hand, one could argue that ``FormatStrFormatter` is just the plain string formatter. On the other hand, Formatters are used to generate the tick labels and one can argue that they should respect the corresponding rcParam.

**Comment by jklymak** [comment]
I don't think we have any way to know if the user meant minus or dash unless you want to catch `%g`...

**Comment by Atcold** [comment]
You can parse the string for `%g`, and replace it with *minus* `abs() if` *negative* `else abs()`.

**Comment by timhoffm** [comment]
The %-formatting syntax is more complex: https://docs.python.org/3.8/library/stdtypes.html#old-string-formatting

We should (at least try to) match all variants; including e.g.
- `%.3f`
- `%03d`

etc.

I don't think one can use named explessions like `%(number)03d` , but to be checked.

**Comment by tacaswell** [comment]
I do not think we want to go down the path of special casing particular format strings.  Not clear why we would want to treat `%g' differently that '%f' etc.

Looking at the formatters we ship, only 3 of them currently respect the rcparam

| formatter | fixes minus |
| -----|----|
IndexFormater | no|
|NullFomatter | no|
| FixedFormatter | no |
| FuncFormatter| no |
| FormatStrFormatter| no |
| StrMethodFormatter | no |
| OldScalerFormater | no |
| ScalarFormatter | yes |
| LogFormatter | no |
| LogFormaterMathText | no |
| LogFormatterSciNotation| no |
| LogitFormatter | no |
|EngFormatter | yes |
| PercentFormatter | yes |

Making them all _start_ to respect it would be a pretty big change and adding a flag on the instances to indicate if they should respect another flag seems like one level of indirection too much.

At a minimum we should add a flag to the init of the formatters to determine if they do the replacement or not.   I can see a bunch of plausible paths for how to treat the rcparam.


-----

It looks like this was last touched in 8c4df386438619b872d954865761b4631032ba05 / https://github.com/matplotlib/matplotlib/pull/14949 but I don't _think_ it changes this behavior.

@Atcold is this a change of behavior from 3.2?

**Comment by anntzer** [comment]
Even if we "fix" FormatStrFormatter and StrMethodFormatter this still won't work for FuncFormatter (because good luck parsing things like `lambda x, p: f"{x:.4g}" if x >= 0 else f"MINUS {-x:.4g}"` or whatnot).  I guess the right solution is actually to rely on mathtext for the conversion (mathtext always replaces minus by unicode minus between $'s), e.g. `FormatStrFormatter("$%g$")` in the OP's case (or `FormatStrFormatter(r"$\mathdefault{%g}$")`) to be super safe.

**Comment by Atcold** [comment]
@tacaswell, I just tried this on `3.2.2`.
@anntzer, yes, `FormatStrFormatter("$%g$")` does what I wanted **if** I'm not `style.use(['bmh'])`, which is forcing LaTeX rendering (is this a bug?).

**Comment by anntzer** [comment]
No, that's (likely) just because bmh sets `rcParams["mathtext.fontset"]` to "cm" (i.e., use computer modern fonts).  Adjust that setting to your convenience.

**Comment by jklymak** [comment]
Needs an example pointing out that mathtext should be used if you want a unicode minus.  Otherwise, there isn't any action items here....

**Comment by tacaswell** [comment]
On the call we discussed that in the cases of the formatters that do not respect the rcparam they are one where either negative numbers should not come up (logit), we are already using mathtext, or the user is providing us with an arbitrary formatting string / function when we can not blindly replace `-` with unicode-minus because we can not reliably tell the difference between `-5` and `a-b`.

**Comment by timhoffm** [comment]
Leading dashes (Or space followed by dash) would be a strong indication for a minus in the generic formatter case. But I'm ok not trying to guess.

**Comment by Atcold** [comment]
> Needs an example pointing out that mathtext should be used if you want a unicode minus. Otherwise, there isn't any action items here....

Do I need to provide something? My example, in the first post, shows the unexpected behaviour.

**Comment by timhoffm** [comment]
@Atcold the problem description is clear.

The discussion is about the solution, which is proposed as better documenting the current behavior and indicating how to force the unicode minus via math text.

**Comment by IlievskiV** [comment]
Hi, is this issue still open? Can I try to document it as described in the discussion?

**Comment by timhoffm** [comment]
@IlievskiV Yes, this is still relevant. Go for it.

**Comment by The-Inky** [comment]
Hi, is this still relevant? If no one else is working on this, may I pick this up?

**Comment by timhoffm** [comment]
Yes, this is still relevant. Go for it.

**Comment by The-Inky** [comment]
Hey, I have made a PR for this issue, please let me know if this is okay:  https://github.com/matplotlib/matplotlib/pull/19665
