### ISSUE TITLE
Setting `Date` metadata to `None` does not remove the date metadata from the SVG file

### ISSUE THREAD

**Issue by yuyichao** [matplotlib/matplotlib#17968]
### Bug report

See title. The new metadata support for SVG backend does not seem to honor a `None` Date metadata.

**Code for reproduction**

```python
plot([1, 2], [2, 3])
savefig("a.svg", metadata={'Date': None})
```

**Actual outcome**

The output svg file contains the `Date` metedata

**Expected outcome**

As the [doc](https://matplotlib.org/3.3.0/api/backend_svg_api.html#matplotlib.backends.backend_svg.FigureCanvasSVG.print_svg) says

> Values have been predefined for 'Creator', 'Date', 'Format', and 'Type'. They can be removed by setting them to None.

Setting the other three to `None` indeed works but not for `Date`.

**Matplotlib version**
  * Operating system: ArchLinux
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg`
  * Python version: 3.8.3
  * Jupyter version (if applicable): (core: 4.6.3) not applicable

Installed from ArchLinux repo.

**Comment by yuyichao** [comment]
Seems that the `Date` metadata is indeed handled differently [here](https://github.com/matplotlib/matplotlib/blob/4723dabd7885080a326e8ed65a15ce49ab5d4d31/lib/matplotlib/backends/backend_svg.py#L325-L340) from the other three. Is it done this way to compute the date lazily? If that's the case the code should probably check if `Date` is set to `None` explicitly first.

**Comment by jklymak** [comment]
This is similar to #17936 for PDF...

**Comment by tacaswell** [comment]
This is different from #17936 as with PDF it is documented that it does not insert _any_ metadata, this is not honoring that the user is suppressing a particular field.
