### ISSUE TITLE
Better radians axis handling

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#17964]
Objective: having the *x*-axis scaled by 1 / π, and have the ticks saying 0, π/2, π (fractions of π)…
I'm aware of the [current *trick*](https://matplotlib.org/3.2.1/gallery/units/radian_demo.html), but:

 - I don't want to bring along an additional script (`basic_units.py`);
 - I don't want to change my input *x* (multiply it by stuff);
 - I don't want LaTeX to be generated (looks weird, and I'm fine with Unicode);
 - If your *x*-axis get's longer, it breaks (it cannot generate too many ticks, and no one asked it to).

I would welcome an argument called `x_radians=True` which would handle the rescaling internally and the display of Unicode π fractions.

> P.S. Here's what I've been up to.
>
> ![lbfgs_1 00π](https://user-images.githubusercontent.com/2119355/87866273-a2402900-c94d-11ea-8004-844c781e42c1.png)

**Comment by jklymak** [comment]
There are a bunch of solutions at https://stackoverflow.com/questions/40642061/how-to-set-axis-ticks-in-multiples-of-pi-python-matplotlib mostly using Locators and Formatters, in varying degrees of complexity.  I don't think this will ever be a kwarg as its not general enough, and where do the requests for specialized axes end?  Thats why Locators and Formatters were made....

**Comment by Atcold** [comment]
I see.

A follow up question about [this answer](https://stackoverflow.com/a/53586826/2247039). To my eyes, `title(r'Multiples of $\pi$')` gets rendered as Unicode (and not LaTeX). If I do try, I get the LaTeX font instead. Why is that?

So, I see, this could be enough:

```python
x = linspace(0, 3 * π)
y = sin(x)
plot(x / π, y)
gca().xaxis.set_major_formatter(FormatStrFormatter('%g π'))
```

![sine-π](https://user-images.githubusercontent.com/2119355/87868517-77150400-c964-11ea-8ed7-a12077d1c7f1.png)

**Comment by Atcold** [comment]
I've just realised that `style.use(['bmh'])` forces LaTeX rendering. I'm trying to figure out is this is wanted / an expected behaviour. Smells like a bug, though.

**Comment by anntzer** [comment]
see https://github.com/matplotlib/matplotlib/issues/17967#issuecomment-662330574

**Comment by Atcold** [comment]
I'm satisfied with [this option](https://github.com/matplotlib/matplotlib/issues/17964#issuecomment-660593784). Closing this issue.
