### ISSUE TITLE
Grid linestyle interferes with numpy.polyfit (numpy.linalg.LinAlgError)

### ISSUE THREAD

**Issue by StephenRoille** [matplotlib/matplotlib#17980]
### Bug report

I am not sure if this is the right place to file this issue because the actual error is raised by the `numpy.linalg` module.
However, my guess is that `matplotlib` is at the origin of a `numpy.linalg.LinAlgError` when plotting right before using `numpy.polyfit`. The error is only raised when using certains grid `linestyle`.

**Code for reproduction**

I spent hours figuring out the origin of the error because the traceback pointed me in the wrong direction. After following many false leads, I could reduce the error to the below snippet. To reproduce the issue no plot is necessary. Changing the grid `linestyle` is sufficient.

```python
import matplotlib.pyplot as plt
import numpy as np

linestyles = ["--", "dashed", "-.", ":", "dotted", "-", "solid", "none", "", " "]
for linestyle in linestyles:
    try:
        # select plot grid linestyle
        plt.grid(linestyle=linestyle)
        # fit array using polynomial
        arr = np.arange(10)
        np.polyfit(arr, arr, deg=1)
    except np.linalg.LinAlgError as e:
        print(f"using linestyle ({linestyle!r}) raised:\n  {e}")
    else:
        print(f"using linestyle ({linestyle!r}) worked")
```

**Actual outcome**

```
using linestyle ('--') raised:
  SVD did not converge in Linear Least Squares
using linestyle ('dashed') raised:
  SVD did not converge in Linear Least Squares
using linestyle ('-.') raised:
  SVD did not converge in Linear Least Squares
using linestyle (':') raised:
  SVD did not converge in Linear Least Squares
using linestyle ('dotted') raised:
  SVD did not converge in Linear Least Squares
using linestyle ('-') worked
using linestyle ('solid') worked
using linestyle ('none') worked
using linestyle ('') worked
using linestyle (' ') worked
```

**Expected outcome**

I would expect `matplotlib` to not interfere with the `numpy` fitting procedure. I tried two different methods (both failed):
  * `numpy.polyfit`;
  * `numpy.polynomial.polynomial.polyfit`.

According to my research the `numpy.linalg.LinAlgError` is usually raised when these methods are called using non-sanitized datasets (containing `NaN` and/or `inf` values), which is not the case in the aforementioned example.

**Matplotlib version**
  * Operating Sytem: Windows 10 Home (64-bit)
  * Matplotlib version: 3.3.0 (installed using `pip`)
  * Matplotlib backend: `TkAgg`
  * Numpy version: 1.19.0 (installed using `pip`)
  * Python version: 3.6.4 (64-bits)
  * Text Editor: Sublime Text 3.2.2 (build 3211) 

Thanks for your attention. I’m looking forward to hearing your thoughts 👍😉

**Comment by WeatherGod** [comment]
That's really unusual and there really shouldn't be any reason why that can happen (at least, nothing sensible). Just did a test using your code using mpl v3.2.1 and numpy v1.18.4 without issues. I updated to mpl v3.3.0 and the script reported no issues. Currently updating numpy to see if that is the culprit.

**Comment by WeatherGod** [comment]
yeah, updating numpy to v1.19 (all of this via conda) yielded no problems (doing this on WSL2, in case the platform makes the difference).

**Comment by jklymak** [comment]
Perhaps you have some sort of namespace pollution.  Just as a hunch please check

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
linestyles = ["--", "dashed", "-.", ":", "dotted", "-", "solid", "none", "", " "]
for linestyle in linestyles:
    try:
        # select plot grid linestyle
        ax.grid(linestyle=linestyle)
        # fit array using polynomial
        arr = np.arange(10)
        np.polyfit(arr, arr, deg=1)
    except np.linalg.LinAlgError as e:
        print(f"using linestyle ({linestyle!r}) raised:\n  {e}")
    else:
        print(f"using linestyle ({linestyle!r}) worked")
```

I can't reproduce this either on master...

**Comment by tacaswell** [comment]
I also can not reproduce this (with master-branch of numpy).

What is the traceback you are getting?

**Comment by StephenRoille** [comment]
Thank you for responding so quickly. I tried to change `plt.plot` with `ax.plot` after creating the `ax` object using the `plt.subplots` method and I get exactly the same error.

**Code**

```python

import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.grid(linestyle="dashed")  # commenting this line removes the error
arr = np.arange(10)
np.polyfit(arr, arr, deg=1)
```

**Traceback**

Instead of running this script from Sublime Text, I ran it from the Terminal and I got additional lines in the traceback mentionning a certain **DLASCLS**. Any idea what this is?

```bash

** On entry to DLASCLS parameter number  4 had an illegal value
** On entry to DLASCLS parameter number  4 had an illegal value
** On entry to DLASCLS parameter number  4 had an illegal value
** On entry to DLASCLS parameter number  4 had an illegal value 
** On entry to DLASCLS parameter number  5 had an illegal value
** On entry to DLASCLS parameter number  4 had an illegal value

Traceback (most recent call last):
  File "test.py", line 12, in <module> np.polyfit(arr, arr, deg=1)
  File "<__array_function__ internals>", line 6, in polyfit
  File "...\venv\lib\site-packages\numpy\lib\polynomial.py", line 629, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 6, in lstsq
  File "...\venv\lib\site-packages\numpy\linalg\linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "...\venv\lib\site-packages\numpy\linalg\linalg.py", line 100, in
    _raise_linalgerror_lstsq raise LinAlgError("SVD did not converge in Linear Least Squares")
  numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares
```

**Dependencies**

OS: Window 10 Home (64-bit)
Python: 3.6.4 compiled with MSC v.1900 64 bit (AMD64)

cycler: 0.10.0                                                                                                     
kiwisolver: 1.2.0                                                                                                  
matplotlib: 3.3.0                                                                                                  
numpy: 1.19.0                                                                                                      
Pillow: 7.2.0                                                                                                      
pyparsing: 2.4.7                                                                                                   
python-dateutil: 2.8.1                                                                                             
six: 1.15.0 

**Important**

No errors occur when running the above script with Python 3.8.3 (32-bit, intel), Python 3.7.3 (32-bit, intel) and Python 3.6.4 (32-bit, intel). The error seemingly appears only with the Python interpreter compiled with AMD64.

**Related issue**

According to this [thread](http://numpy-discussion.10968.n7.nabble.com/MKL-ValueError-On-entry-to-DLASCL-parameter-number-5-had-an-illegal-value-td39894.html), the problem might be:

>  It is possible that the problem being solved is numerically sensitive and that the treatment of underflow/overflow due to compiler flags might be producing zeros or infs

I am style puzzeled by the fact that this error only appears using certain grid `linestyle` when interacting with the `pyplot` module.

Thank you for your time.

**Comment by StephenRoille** [comment]
**Additional Thoughts**

I tried the exact same steps using Python 3.6.4 (AMD64) but instead of installing `numpy` with a straight `pip install numpy` (which lets Python decides what version best fits its needs), I used [unofficial Windows binaries](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy). 

I downloaded the appropriate wheel for my OS (`numpy‑1.19.0+mkl‑cp36‑cp36m‑win_amd64.whl`)
to make use of the **Intel Math Kernel Library** (MKL) instead of the vanilla `numpy` library.

With this library `matplotlib` does not interfere with `numpy` anymore and the aforementioned snippets work just fine.

I close the issue for now since the origin of the error is not clear. Is it `numpy` or is it `matplotlib`? I would really appreciate if someone could try to reproduce the original error on various OSes with Python 64-bit and no MKL to identify if the `plt.grid(linestyle="--")` provoke a `numpy.linalg.LinAlgError`.

Feel free to re-open if you encounter a similar issue.

**Comment by StephenRoille** [comment]
I want to add a few details to the discussion I closed quite a while ago because it seems that other people have encoutered it recently (#18559 , #18157).

The problem DOES NOT come from `matplotlib` but from `numpy`.

If you meet all the following conditions, you are likely to face the aforementioned errors:

- you are using both `matplotlib` and `numpy` (I am not sure about the versions concerned);
- you rely on the **linear algebra** features from `numpy` (directly or indirectly);
- you are on **Windows 10 build 2004**;
- you are using the [**OpenBLAS**](https://en.wikipedia.org/wiki/OpenBLAS) instead of the [**MKL**](https://en.wikipedia.org/wiki/Math_Kernel_Library) linear algebra kernel.

The fix I proposed at the time was to download and re-install `numpy` using the appropriate `numpy+mkl` version from the list of [unofficial libraries](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy).

Today, I discovered that the `numpy` team officially recognized this issue on their [GitHub release page](https://github.com/numpy/numpy/releases/tag/v1.19.2). The team is currently woking to find a solution, but for now the suggestion agree with the fix I proposed earlier in this thread:

>  There is a known problem with Windows 10 version=2004 and OpenBLAS svd
>  that we are trying to debug. If you are running that Windows version you
>  should use a NumPy version that links to the MKL library, earlier
> Windows versions are fine.

I hope this helps 😉
