### ISSUE TITLE
New warning: Substituting symbol \perp from STIXGeneral

### ISSUE THREAD

**Issue by sballin** [matplotlib/matplotlib#17998]
### Bug report

A new warning appears as of version 3.3, which is not present in 3.2.2:

    Substituting symbol \perp from STIXGeneral

The default font settings have not been changed in any way. If I change to stix, the warning goes away, but I would like to keep using the default font.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.figure()
plt.title(r'$\perp$')
plt.show()
```

**Expected outcome**

No warning, as in 3.2.2

**Matplotlib version**

  * Operating system: macOS 10.15.6 and Ubuntu
  * Matplotlib version: 3.3 installed via pip
  * Matplotlib backend: Qt5Agg, MacOSX, PdfPages, possibly others
  * Python version: 3.7

**Comment by anntzer** [comment]
I've seen the warning too.  My guess is that this should just be downgraded to a _log.info -- it's something worth noting when debugging, but it's not worth nagging the end-user about it.
