### ISSUE TITLE
Interactive plots too large in safari with V3.3.0

### ISSUE THREAD

**Issue by maxroberts** [matplotlib/matplotlib#17997]
### Bug report

**Bug summary**

In Jupyter notebooks when using interactive plotting (%matplotlib notebook or %matplotlib nbagg), plots are created too large in Safari starting with V3.3.0, but are fine in Firefox. By too large, about half the figure is out of view of the NB viewer display. Resolved this (for now) by rolling back to V3.2.2.

Here is an image of the problem:

<img width="1097" alt="Screen Shot 2020-07-21 at 8 01 19 AM" src="https://user-images.githubusercontent.com/12839165/88071218-6a410d80-cb28-11ea-8460-5b29d588b7a0.png">

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: V3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: Python 3.8.4
  * Jupyter version (if applicable): 

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.3
jupyter client   : 6.1.6
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

Everything is installed with pip and I'm using homebrew. Thanks!

**Comment by maxroberts** [comment]
Maybe related to "NbAgg and WebAgg no longer use jQuery & jQuery UI"?

**Comment by jklymak** [comment]
Can you supply a reproducible example?  I use nbagg on master on safari all the time and haven't had any issues so it would be helpful to know if it's something in your setup.

**Comment by takluyver** [comment]
Could this be related to #18132?

**Comment by jklymak** [comment]
Closing for lack of response
