### ISSUE TITLE
type stubs for matplotlib

### ISSUE THREAD

**Issue by tekumara** [matplotlib/matplotlib#17991]
Would be great if matplotlib shipped with type stubs.

**Comment by story645** [comment]
The dev team may rivisit now that numpy has types. Is there any argument you'd like to add to the previous discussions #15926 & #13798 ?

**Comment by tekumara** [comment]
FYI: pylance ships matplotlib stubs already, but they are proprietary (for now) and may end up in pyright see  https://github.com/microsoft/pyright/issues/861

**Comment by tacaswell** [comment]
I'm going to close this as we are well aware that type annotations exist and adding them across the library is a bigger project than should be tracked in a single issue.  I stand by we should let numpy go through a couple of release cylces with the types before we start to adopt them to let the dust settle a bit.

It is my understanding that the MSFT stubs are auto-generated by walking the code which suggests it is not urgent that we take this on (as the tools that will benefit the most from the stubs can generate their own).

**Comment by jakebailey** [comment]
> It is my understanding that the MSFT stubs are auto-generated by walking the code which suggests it is not urgent that we take this on (as the tools that will benefit the most from the stubs can generate their own).

FWIW, this isn't the case; what's shipped with Pylance I wrote by hand over the course of a weekend conference; they certainly aren't meant to be proprietary in any sense and will end up in https://github.com/microsoft/python-type-stubs (them not being there is an oversight).

Sorry for bumping an old thread (time flies), I'm just now spending some long-overdue time addressing issues in those stubs and was checking on the state of typing here.
