### ISSUE TITLE
Add cheatsheets to docs

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#18019]
We have official very nice cheatsheets at https://github.com/matplotlib/cheatsheets and it'd be nice to prominently link them out from the homepage and possibly embed them in the docs. 

attn @timhoffm & @rougier

**Comment by timhoffm** [comment]
I will think of something.

**Comment by QuLogic** [comment]
Also keep in mind #14966, which are different kinds of cheat sheets, but you may want to put them in the same section.

**Comment by rougier** [comment]
Do you have a direct link to the other cheat sheets? (I got lost in the different links)

**Comment by story645** [comment]
@QuLogic & @rougier nobody has picked up that PR so I'm not sure it's relevant yet.

**Comment by QuLogic** [comment]
Yea, they're not written; I'm just pointing them out as something that we might want to put in the same place.
