### ISSUE TITLE
Prevent ticks too close to axis edges

### ISSUE THREAD

**Issue by beojan** [matplotlib/matplotlib#18015]
I'm using GridSpec to place two axes (with a shared x-axis) right next to each other. I'd like to prevent ticks being drawn too close to the ends of one of the y-axes to prevent the tick labels overlapping. Is this possible?

**Comment by jklymak** [comment]
Can you ask on discourse.matplotlib.org with a working example?  This doesn't sound like a bug.  Thanks!
