### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'backends'

### ISSUE THREAD

**Issue by umesh-timalsina** [matplotlib/matplotlib#18022]
### Bug report

**Bug summary**
Switching backends using matplotlib v3.3.0 fails for custom backend. I have a custom backend developed for matplotlib. Which is used to get state of the current figure data. Before `v3.3.0`, I used `MPLBACKEND` env variable to switch backends. This fails in `v3.3.0` it fails with the following error message:

```sh
File "/path/to/conda/python3.7/site-packages/matplotlib/pyplot.py", line 283, in switch_backend
    matplotlib.backends.backend = newbackend
AttributeError: module 'matplotlib' has no attribute 'backends'
```

**Code for reproduction**

```sh
$ export MPLBACKEND=module://my_custom_backend
```

```python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.3.0'
>>> from matplotlib import pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2319, in <module>
    switch_backend(rcParams["backend"])
  File "/home/umesh/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 283, in switch_backend
    matplotlib.backends.backend = newbackend
AttributeError: module 'matplotlib' has no attribute 'backends'
>>> 

```

**Actual outcome**

```sh
AttributeError: module 'matplotlib' has no attribute 'backends'
```

**Matplotlib version**

  * Operating system:  (Linux Mint 19.3 Tricia)
  * Matplotlib version: 3.3.0
  * Matplotlib backend : Problem with switching backend
  * Python version: 3.7

**Comment by tacaswell** [comment]
Sorry about that, I see the issue and working on a fix.  If you do `import matplotlib.backends` before you import pyplot it should work as a workaround for now.

**Comment by umesh-timalsina** [comment]
@tacaswell. Thanks, that should work for now.

**Comment by tacaswell** [comment]
Out of curiosity, what backend do you have that does not extend at least one of the backends we ship?

**Comment by umesh-timalsina** [comment]
https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/backend_deepforge.py
A `plt.show()` converts the matplotlib figure into a state that are saved as nodes attributes for a Model in [deepforge](https://github.com/deepforge-dev/deepforge)

We convert matplotlib figure to a JSON object to display it in browser in `plotly`. Some concepts are borrowed from https://github.com/mpld3/mplexporter.

**Comment by tacaswell** [comment]
You probably want to re-order https://github.com/deepforge-dev/deepforge/blob/325bf698c3b23816bf47f5a0482f5b73d92f0b7b/src/plugins/GenerateJob/templates/backend_deepforge.py#L357-L359 to run `figure.draw()` first as that will trigger various draw-time things (like limits) that you are capturing.

**Comment by umesh-timalsina** [comment]
@tacaswell Thanks. I have opened an issue that might be helpful for https://github.com/deepforge-dev/deepforge/pull/1747 which uses the custom backend togehter with [plotly.py](https://github.com/plotly/plotly.py)'s matplotlib to plotly converter with 3D Figure support.

**Comment by verifiedanswer** [comment]
[[Solved] AttributeError: partially initialized module ‘matplotlib.backends.backend_macosx’ has no attribute ‘FigureCanvas’](https://verifiedanswer.com/attributeerror-partially-initialized-module-matplotlib-backends-backend-macosx-has-no-attribute-figurecanvas/)
