### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'bar'

### ISSUE THREAD

**Issue by simeon9696** [matplotlib/matplotlib#18035]
### Bug report

**Bug summary**
Plotting a bar graph using Matplotlib on Raspbian OS yields `AttributeError: 'NoneType' object has no attribute 'bar'`. I developed the code on windows and then cloned the repo on the Pi. Everything works on windows so I'm not sure why this is happening.

**Code for reproduction**

```
        f = Figure(figsize=(10, 5), dpi=100)
        self.ax = f.add_subplot()
        

        self.fieldname=[]
        self.fieldvalue=[]
        for index in range(len(sheetData.index.values)): 
            self.fieldname.append(str(sheetData.iloc[index,[0]].values).strip('[]').replace("'",''))
            self.fieldvalue.append(int(str(sheetData.iloc[index,[1]].values).strip('[]').replace("'",'')))

        rects1 = self.ax.bar(self.fieldname, self.fieldvalue, width, label=f'{headings[0]}')
        self.ax.set_xticklabels(self.fieldname, rotation=45, ha='right')
        self.ax.set_ylabel(f'{headings[1]}')
        #self.ax.set_xlabel(f'{headings[0]}')
        self.ax.set_title(f'{headings[0]} vs {headings[1]}')
        self.ax.legend()
        degrees = 70
        
        canvas = FigureCanvasTkAgg(f, master=self)
        canvas.draw()
        self.autolabel(rects1, "center")
```

***Actual Outcome**
```
Traceback (most recent call last):
  File "bargraphtutor.py", line 127, in <module>
    app = BarGraphTutor()
  File "bargraphtutor.py", line 81, in __init__
    frame = F(parent=container, controller=self)
  File "/home/pi/Desktop/3020-math-app/pages/easyplotpage.py", line 64, in __init__
    rects1 = self.ax.bar(self.fieldname, self.fieldvalue, width, label=f'{headings[0]}')
AttributeError: 'NoneType' object has no attribute 'bar'
```

**Matplotlib version**

  * Operating system: Raspbian v10 (buster)
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.73
  * Other libraries: 

I installed it using pip3 install matplotlib

**Comment by jklymak** [comment]
@simeon9696 we won't really be able to help without a reproducible example including your imports.  However, its clear that somehow your `f.add_subplot` is returning `None` for some reason, or you are subsequently setting self.ax to None.

**Comment by simeon9696** [comment]
@jklymak Thanks for the feedback! I'll definitely do that in future bug reports. I was able to get it to work by just upgrading the version of matplotlib from v3.0.2 to 3.3.0

`sudo pip3 uninstall matplotlib`
`python3 -m pip install -U --user matplotlib`
