### ISSUE TITLE
gouraud shading in pcolormesh produces a PDF file not compatible with Adobe Illustrator

### ISSUE THREAD

**Issue by gokceneraslan** [matplotlib/matplotlib#18034]
### Bug report

**Bug summary**

When I was editing some plots produced by plotnine, I encountered something weird in Illustrator due to the shading of the colorbar. I reported it [here](https://github.com/has2k1/plotnine/issues/422) but the following is the matplotlib version to reproduce it.

When `pcolormesh` is used with shading='gouraud' and rasterized=False, produced PDFs are rendered fine but when I try to edit the color mesh in Adobe Illustrator, it complains about an `unknown imaging construct`. The complaint goes away when I pass `rasterized=True` or `shading='flat'`. I wonder what exactly is the unknown construct and how we can fix this in matplotlib (assuming that it's not an issue with the Illustrator)

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x1 = np.random.randn(100)
x2 = np.random.randn(100)
x3 = np.random.randn(100, 100)

fig, ax = plt.subplots()

quadMeshCol = ax.pcolormesh(x1, x2, x3, shading='gouraud', rasterized=False)
fig.savefig('matplotlib-pcolormesh-gouraud-rasterfalse.pdf')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/1140359/88304036-baa99e00-ccd5-11ea-9eb9-fb9807607599.png)

Blue X indicates the `unknown construct`.

**Expected outcome**

![image](https://user-images.githubusercontent.com/1140359/88304115-d745d600-ccd5-11ea-85cd-d88e17267981.png)

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.8
  * Jupyter version (if applicable):
  * Other libraries: 

Installed via pip.

**Comment by gokceneraslan** [comment]
The content of a minimal PDF with the unrecognized object:

```PDF
%PDF-1.4
%¨‹ ´∫
1 0 obj
<< /Pages 2 0 R /Type /Catalog >>
endobj
8 0 obj
<< /ExtGState 4 0 R /Font 3 0 R /Pattern 5 0 R
/ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /Shading 6 0 R
/XObject 7 0 R >>
endobj
10 0 obj
<< /Annots [ ] /Contents 9 0 R
/Group << /CS /DeviceRGB /S /Transparency /Type /Group >>
/MediaBox [ 0 0 432 288 ] /Parent 2 0 R /Resources 8 0 R /Type /Page >>
endobj
9 0 obj
<< /Filter /FlateDecode /Length 11 0 R >>
stream
xúmè›
Ç@ÖÔÁ)ŒË˛Y{k›YA ¶I
&‘ÎwL≠(/ñ93sŒ≠F-q™QˆP®˘–à∑≈˝í˚∞Aﬁã‚ºg
ÎıUç˜Tj™ïH+º¡u`ºîƒ¡Æ±ﬁG~ê◊IöƒFŒ±•„≠?Ká1d≠|z=ÏnNhßf‘‘TÄq8*ÙïdËf≥¡äóñÏ3ﬁ7Ñ>¥Õ/-ó_ßìi)ì…oÑJ–
endstream
endobj
11 0 obj
176
endobj
3 0 obj
<< >>
endobj
4 0 obj
<< /A1 << /CA 0 /Type /ExtGState /ca 1 >>
/A2 << /CA 1 /Type /ExtGState /ca 1 >> >>
endobj
5 0 obj
<< >>
endobj
12 0 obj
<< /AntiAlias false /BitsPerComponent 8 /BitsPerCoordinate 32
/BitsPerFlag 8 /ColorSpace /DeviceRGB
/Decode [ -202 644.8 -220 509.44 0 1 0 1 0 1 ] /Filter /FlateDecode
/Length 71 /ShadingType 4 >>
stream
xúcÿ4ªi{‰
≈
≤˘æ)µÓ ˆ√«ıˇˇˇ·YU(‚ ˆ2ı{~.å!j`‚ 3AÏøœUP‘ ã#€ã§{ûK´
endstream
endobj
6 0 obj
<< /GT0 12 0 R >>
endobj
7 0 obj
<< >>
endobj
2 0 obj
<< /Count 1 /Kids [ 10 0 R ] /Type /Pages >>
endobj
13 0 obj
<< /CreationDate (D:20200723182428-04'00')
/Creator (Matplotlib v3.3.0, https://matplotlib.org)
/Producer (Matplotlib pdf backend v3.3.0) >>
endobj
xref
0 14
0000000000 65535 f 
0000000016 00000 n 
0000001153 00000 n 
0000000656 00000 n 
0000000677 00000 n 
0000000776 00000 n 
0000001099 00000 n 
0000001132 00000 n 
0000000065 00000 n 
0000000385 00000 n 
0000000208 00000 n 
0000000636 00000 n 
0000000797 00000 n 
0000001213 00000 n 
trailer
<< /Info 13 0 R /Root 1 0 R /Size 14 >>
startxref
1370
%%EOF
```

Generated with the following code:

```python
import matplotlib.pyplot as plt
import numpy as np

x1 = np.random.randn(2)
x2 = np.random.randn(2)
x3 = np.random.randn(2, 2)

fig, ax = plt.subplots()

quadMeshCol = ax.pcolormesh(x1, x2, x3, shading='gouraud', rasterized=False)
ax.set_xticklabels([])
ax.set_yticklabels([])
ax.set_xticks([])
ax.set_yticks([])

fig.savefig('matplotlib-pcolormesh-gouraud-rasterfalse.pdf')
```

**Comment by jklymak** [comment]
I'm skeptical there is anything we can do about this, beyond suggest you don't use gouraud if you expect to open it in Illustrator; here is a thread from 2007; I doubt this has ever worked.  https://printplanet.com/threads/an-unknown-imaging-construct-was-encoutered.968/

**Comment by gokceneraslan** [comment]
OK, if you are sure that everything is ok with the pdf, feel free to close the issue. It'd be great to hear also @jkseppan 's optinion, since it looks like he's the last person implemented alpha in the gourad shading  code.

**Comment by QuLogic** [comment]
`qpdf --check` does not complain about the file. It loads in evince (though very slowly), but not okular (though maybe it's also just slow). It doesn't look anything like your expected image though. The real question is whether it loads in Adobe Reader?

**Comment by tacaswell** [comment]
okular loads _eventually_.

The thing I am unsure about is the x and y are random so I am not sure what "right" here is.

**Comment by gokceneraslan** [comment]
Code with non-random x and y:

```python
import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([2, 10])
x2 = np.array([1, 2])
x3 = np.array([[1,4], [2,2]])

fig, ax = plt.subplots()

quadMeshCol = ax.pcolormesh(x1, x2, x3, shading='gouraud', rasterized=False)
ax.set_xticklabels([])
ax.set_yticklabels([])
ax.set_xticks([])
ax.set_yticks([])

fig.savefig('matplotlib-pcolormesh-gouraud-rasterfalse.pdf')
```

How it looks like (and hopefully how it's supposed to look like):

![image](https://user-images.githubusercontent.com/1140359/88350926-97f1a680-cd22-11ea-9244-0f774b96ad04.png)

**Comment by jklymak** [comment]
It looks fine in Acrobat, Preview, and PDFExpert on a Mac.  I don't have AcrobatReader, but doubt its any different

<img width="1519" alt="Acrobat" src="https://user-images.githubusercontent.com/1562854/88351860-987f4280-cd0c-11ea-955e-85a0aef242f6.png">

**Comment by jkseppan** [comment]
While Adobe Illustrator comes from the same company as PDF, it far predates the current PDF standard. Originally its `.ai` files were just EPS files with special comments, though that has probably changed by now. I'm guessing that its drawing model still does not have all the features of PDF, so some PDF objects will be imported poorly into the AI format. My recommendation would be to rasterize the shaded images if they are going to be imported into AI.

Does the Cairo backend produce a more useful result? Or is there other software that outputs pdf files with similar shading that are importable into AI? If so, it might be interesting to look at their outputs.

**Comment by jkseppan** [comment]
It seems based on the reports in various comments that PDF renderers handle the resulting file fine, it's just Adobe Illustrator that fails. I'm not opposed to adding a workaround for AI, but that would have to be done by someone who can test with AI, so I suggest we close this issue for now.
