### ISSUE TITLE
Cannot access hexbin data when `xscale='log'` and `yscale='log'` are set.

### ISSUE THREAD

**Issue by mankoff** [matplotlib/matplotlib#18045]
### Bug report

```python
plt.hexbin([1,10,100],[1,10,100], mincnt=1).get_offsets()
plt.hexbin([1,10,100],[1,10,100], mincnt=1, xscale='log', yscale='log').get_offsets()
```

I've made a log-log hexbin plot and would like to access the points generated by `hexbin` so I can make a contour. I cannot access these points for two reasons:

1) The documentation is incorrect and states that `PolyCollection.get_offset()` should be called, but it is `PolyCollection.get_offsets()` (note plural). See 1st bullet point under `returns` here https://matplotlib.org/3.3.0/api/_as_gen/matplotlib.pyplot.hexbin.html

2) When I call `get_offsets()` if `xscale='log'` and `yscale='log'` are set, I only get `array([[0., 0.]])` rather than the points.

**Comment by rgmumufeng** [comment]
It seems that the "no hexbin data for log scale" issue still exists. Is there any update for this issue?

**Comment by mankoff** [comment]
Still open. Would still like to use this feature with log log plots.

**Comment by dstansby** [comment]
The first half of the issue (documentation) is fixed. I can confirm the second half is still an issue though.
