### ISSUE TITLE
Setting tick labels or legend text bold independently

### ISSUE THREAD

**Issue by ipcamit** [matplotlib/matplotlib#18056]
### Bug report

I can set size of legend text and tick labels independently using `rc("legend",fontsize=12)` and `ax.tick_params(labelsize=12)`. However I cannot find any method where I can only make tick labels or legend text bold independently. `rc('font',weight="bold")` makes both of them bold together. No respite on SO too. Is it possible?  
**Code for reproduction**

**Matplotlib version**

  * Operating system: Mac OSX 10.11
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version:3.7.7

**Comment by timhoffm** [comment]
There are no rcParams for this, i.e. you cannot set this globally.

You can however obtain the respective text objects an modify them; e.g. `Legend.get_texts()` / `Legend.get_title()`, `[tick.label1 for tick in ax.xaxis.majorTicks]`.

**Comment by ruijpbastos** [comment]
Would it maybe make sense to add a global setting for this?

**Comment by timhoffm** [comment]
#19304 solves the part for the legend title.
