### ISSUE TITLE
Question: Adapt pgf spacing below and above plot

### ISSUE THREAD

**Issue by matu3ba** [matplotlib/matplotlib#18054]
### Bug report

**Bug summary**

A lot space below and above the plot is wasted on using pgf as backend and one needs to do tex hackery to get the spacing right.
(`\abovecaptionskip` and `\belowcaptionskip`)
Does pgf offer an option to adapt the space? Otherwise I would need to use pdf, which kind of defeats the purpose of the pgf backend.
I searched for "matplotlib pgf space", but found no solutions yet.

**Code for reproduction**

```python
matplotlib.use("pgf")
matplotlib.rcParams.update({
    "pgf.texsystem": "lualatex",
    'font.family': 'serif',
    'text.usetex': True,
    'pgf.rcfonts': False,
    #'figure.constrained_layout.use': True, # does not matter if activated or not
    plt.rcParams['figure.figsize'] = 3.347115, 3.5 # does this break spacing? 
    # I need width, but dont care about height since I can use align

})
plt.rcParams['figure.figsize'] = 3.347115, 3.5 #good enough? 4.5,4.
...
plt.savefig('markVoxbytimeCubeSphere.pgf')
```

**Actual outcome**

![cropped_bigwhitespace](https://user-images.githubusercontent.com/13089667/88439192-cea2ec00-ce0a-11ea-8302-dfc291cd6171.png)

**Expected outcome**

Less space wasted or some configuration to set the space left,right,below and above for the pgf backend.

**Matplotlib version**

  * Operating system: Linux Manjaro
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): pgf
  * Python version: 3.7

**Comment by jklymak** [comment]
... are you using `tight_layout`, `constrained_layout`, `bbox_inches='tight'` or `subplots_adjust`?  I don't know anything about the pdf backend, but is the result really different with a different backend?  

Finally, please give us a complete reproducible example so we can see what you have done already to adjust the spacing.

**Comment by matu3ba** [comment]
@jklymak Sorry for the inconvenience, this seems to be backend-independent and was my fault (because tikz plots are created without margin/padding).
Could you create an example for `plt.savefig('markVoxbytimeREALexamples.pgf', bbox_inches='tight', pad_inches = 0)` for the `margin` examples [here](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.margins.html)?

The term `padding` is not intuitive, because the margin around the plots+text seems to be called padding.
Alternatively a box model like for CSS, which explains all things on the start page could help. If I go to the start page, I usually just use the examples and modify them.

**Comment by jklymak** [comment]
Those are data margins, not figure margins - perhaps unfortunately named, but unlikely to change now

**Comment by matu3ba** [comment]
@jklymak Could you modify one of the examples in [margin](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.margins.html), so it uses 0 padding for saving? 
Having no example with `pad_inches=0` certainly does not help.
Otherwise this is resolved.

**Comment by jklymak** [comment]
OK, glad you got it sorted.
