### ISSUE TITLE
Add symmetric norm for colormaps

### ISSUE THREAD

**Issue by endolith** [matplotlib/matplotlib#1806]
There was previously discussion about this but I don't think it ever happened:

> Yes, that is exactly what I have in mind. I have a branch started to do this, but it is not ready yet. I am thinking of a kwarg called "vmid" to go with "vmin" and "vmax", the idea being that if it is not None then it expands any specified or autoscaled range in the manner you describe.

https://github.com/matplotlib/matplotlib/issues/875#issuecomment-6105796

> Just wanted to note here that I have a SymmetricNorm class which auto-scales evenly around a centre point.
> It sounds like it could do the trick (and potentially avoid mutually exclusive keywords) and I'd be happy to share.

https://github.com/SciTools/iris/blob/master/lib/iris/palette.py#L164

**Comment by petehuang** [comment]
Tracing related PRs, it seems like the most current related work sits in #7294

**Comment by QuLogic** [comment]
Implemented in #17709.
