### ISSUE TITLE
vertical alignment of \sum depends on the presence of subscripts and superscripts

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18085]
### Bug report

**Code for reproduction**

```python
from pylab import *
text(.5, .5, r"$\sum x\quad\sum^nx\quad\sum_nx\quad\sum_n^nx$"); axhline(.5)
```

**Actual outcome**

![out](https://user-images.githubusercontent.com/1322974/88571752-6c323180-d03e-11ea-9102-f2f4a702f264.png)

**Expected outcome**

All sum signs should have the same vertical alignment.  In fact it looks like TeX uses something like mathtext's first case, i.e. the bottom horizontal line goes *below* the baseline (which seems esthetically reasonable):
![out](https://user-images.githubusercontent.com/1322974/88571949-b3b8bd80-d03e-11ea-8ab9-230d087f880d.png)
(just pass `usetex=True` to `text()` to check).

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 38
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by oscargus** [comment]
In current main it is slightly better:
![image](https://user-images.githubusercontent.com/8114497/148689532-f4daca31-7e4d-4f38-bcc4-081ce5d1e14a.png)

So now three out of four looks the same (and alright).
