### ISSUE TITLE
Axis Ticks Below Plotted Line

### ISSUE THREAD

**Issue by boada** [matplotlib/matplotlib#18099]
### Bug report

**Bug summary**

The axis ticks are below the line that I plotted. 

**Code for reproduction**

Not super great code, but it reproduced the problem.

```python
import matplotlib.pyplot as plt
import numpy as np

y = 0.01 + np.random.random(1000)* 10
x = np.random.random(1000)

fig, ax = plt.subplots(figsize=(7, 7 * (np.sqrt(5.) - 1.0) / 2.0))
ax.set_xlim(0.02,0.75)
ax.set_ylim(0.01, 20)
ax.tick_params(zorder=10)
ax.semilogy()

ax.scatter(x,y)
ax.plot([0.001, 1], [0.001, 10], c='r')
```

**Actual outcome**

![Capture](https://user-images.githubusercontent.com/6586069/88708534-c46e3f80-d0e1-11ea-8d64-0b831f175e5b.PNG)

**Expected outcome**

MPL version: 3.2.0

The ticks should be on top of the plotted line. See the right hand side of the plot. 

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version:  3.2.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.8
  * Jupyter version (if applicable): 1.0.0 (notebook version: 6.0.3)
  * Other libraries: 

MPL installed from pip. Python built from source.

**Comment by oscargus** [comment]
See the `set_axisbelow` method: https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_axisbelow.html

or set the `zorder` parameter for the individual elements.
