### ISSUE TITLE
Adding Text Annotation when Co-plotting Shrinks Subplots when Tight Layout is Applied

### ISSUE THREAD

**Issue by bawood2** [matplotlib/matplotlib#18098]
### Bug report

**Bug summary**

Vertical annotations shrink subplots when a figure handle's `tight_layout` is set to True.  The expectation is that annotations would overlap the subplots.  

Looking at the documentation...

https://matplotlib.org/3.2.2/tutorials/intermediate/tight_layout_guide.html#caveats

> tight_layout() only considers ticklabels, axis labels, and titles. Thus, other artists may be clipped and also may overlap

With that in mind,  `tight_layout` should not consider `Text` annotations, and shouldn't adjust the subplot size when added.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,np.pi*2,1000)
y = np.sin(x)
dy = np.cos(x)
dy2 = -np.sin(x)

for b in [False,True]:

    h, ax = plt.subplots(3,1,sharex = True)
    h.set_tight_layout(b)
    ax[0].plot(x,y)
    ax[1].plot(x,dy)
    ax[2].plot(x,dy2)

    ax[2].annotate(s = f'Annotation When Tight Layout is {b}', xy = (np.pi,-1), rotation = 'vertical')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/20617349/88705768-9a168500-d0d5-11ea-969c-dbcaec24ac8d.png)

**Expected outcome**

In this case,  `tight_layout` is set to FALSE just to see visually what it looks like with the text overlayed

![image](https://user-images.githubusercontent.com/20617349/88705827-aac6fb00-d0d5-11ea-84d4-25c0e3214b18.png)

**Matplotlib version**

  * Operating system: CentOS Linux 7 (Core)
  * Matplotlib version:  3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable):
  * Other libraries: numpy 1.18.5

conda

conda-forge

**Comment by jklymak** [comment]
This is an error in the documentation, in that it wasn't updated when this was changed.

As you can imagine, there are just as many complaints when the annotations are clipped or ignored, so we a) made the default that they are not ignored, and b) gave you a toggle to allow them to be ignored.  All artists have a `set_in_layout` method, which you can set to False here.  

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,np.pi*2,1000)
y = np.sin(x)
dy = np.cos(x)
dy2 = -np.sin(x)

for b in [False,True]:

    h, ax = plt.subplots(3,1,sharex = True)
    h.set_tight_layout(b)
    ax[0].plot(x,y)
    ax[1].plot(x,dy)
    ax[2].plot(x,dy2)

    an = ax[2].annotate(s = f'Annotation When Tight Layout is {b}', xy = (np.pi,-1), rotation = 'vertical')
    an.set_in_layout(False)
    plt.show()
```

![TL](https://user-images.githubusercontent.com/1562854/88708863-2b332f00-d0c9-11ea-866d-b011ae250984.png)

**Comment by bawood2** [comment]
@jklymak Thank you for the help on this one, and also the quick turn around.  Yeah,  its easy to imagine the complaints.  Glad to hear that the solution to this was as easy as setting `set_in_layout`.   Thanks again!

**Comment by jklymak** [comment]
@bawood2 feel free to review #18100 to make sure it would have been clear...  Thanks for the report!

**Comment by bawood2** [comment]
@jklymak Reviewed the doc updates in #18100, and agree that it would have been clear, especially with the prompt to use `set_in_layout`
