### ISSUE TITLE
Feature Request: Allow hexbin to use a string for parameter C to refer to column in data (DataFrame)

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotlib#18097]
### Feature request

Currently the `hexbin` function allows for its first two parameters `x` and `y` to be strings of `data` (usually a pandas DataFrame), but not `C`

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame(np.random.rand(100000, 3))
df.columns = ['a', 'b', 'c']
plt.hexbin('a', 'b', C='c', data=df)
```

Results in `IndexError: string index out of range`

Currently, you must pass in `C` as a Series/array
plt.hexbin('a', 'b', C=df['c'], data=df)

**Comment by jklymak** [comment]
Do we allow the string for other z-data?  i.e. `pcolormesh` or `imshow`?

**Comment by timhoffm** [comment]
Yes we do. In fact, for `pcolormesh` and `imshow` we allow all parameters, including e.g. `cmap` - not sure if that's intentional.

![grafik](https://user-images.githubusercontent.com/2836374/88695188-d5c74400-d101-11ea-8462-959d42ec78a5.png)

But at least 'C' should be allowed for hexbin.

**Comment by tacaswell** [comment]
It working for cmap seems like a mistake...
