### ISSUE TITLE
A simple 3D scatter plot with %matplotlib notebook is not working

### ISSUE THREAD

**Issue by chudur-budur** [matplotlib/matplotlib#18132]
### Bug report

**Bug summary**

A simple 3D scatter plot is not working on jupyter notebook when `%matplotlib notebook` is enabled. However, it is working for `%matplotlib inline`

An extremely large, blank window appears that spans beyond the page.

**Code for reproduction**

```python
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

A = np.random.random((100,3))
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(A[:,0], A[:,1], A[:,2])
plt.show()
```

**Actual outcome**
![Fail case](https://i.postimg.cc/3RqQjy4f/Screen-Shot-2020-07-30-at-9-44-51-PM.png)

**Expected outcome**

Expecting a 3D scatter plot of `A`.

**Matplotlib version**

  * Operating system: posix Darwin 19.6.0
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.5
  * Jupyter version (if applicable): 
     - jupyter core     : 4.6.3
     - jupyter-notebook : 6.0.3
     - qtconsole        : 4.7.5
     - ipython          : 7.16.1
     - ipykernel        : 5.3.4
     - jupyter client   : 6.1.6
     - jupyter lab      : not installed
     - nbconvert        : 5.6.1
     - ipywidgets       : 7.5.1
     - nbformat         : 5.0.7
     - traitlets        : 4.3.3
  * Other libraries: numpy 1.19.1, scipy 1.5.2

**Comment by QuLogic** [comment]
What browser are you using?

**Comment by chudur-budur** [comment]
> What browser are you using?

Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by QuLogic** [comment]
I cannot reproduce in Firefox at all, but in Chromium, it isn't huge. Instead, only about a quarter of the figure is visible, so something weird is definitely going on.

**Comment by QuLogic** [comment]
This seems to be a bug in Chrome's Resize Observer implementation; it defines `entry.contentBoxSize`, but `entry.contentBoxSize.inlineSize` is undefined.

If you go to [this page](https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html) and move the slider, does the text size change, or does _only_ the width of the box get bigger?

A workaround is:
```patch
diff --git a/lib/matplotlib/backends/web_backend/js/mpl.js b/lib/matplotlib/backends/web_backend/js/mpl.js
index f7ef50dab..1aced9e6a 100644
--- a/lib/matplotlib/backends/web_backend/js/mpl.js                                  
+++ b/lib/matplotlib/backends/web_backend/js/mpl.js
@@ -171,7 +171,7 @@ mpl.figure.prototype._init_canvas = function () {
         for (var i = 0; i < nentries; i++) {                     
             var entry = entries[i];             
             var width, height;                  
-            if (entry.contentBoxSize) {         
+            if (entry.contentBoxSize && entry.contentBoxSize.inlineSize !== undefined && entry.contentBoxSize.blockSize !== undefined) {
                 width = entry.contentBoxSize.inlineSize;                                                                                 
                 height = entry.contentBoxSize.blockSize;                                                                               
             } else {                                                                                                                   
```

**Comment by chudur-budur** [comment]
> This seems to be a bug in Chrome's Resize Observer implementation; it defines `entry.contentBoxSize`, but `entry.contentBoxSize.inlineSize` is undefined.
> 
> If you go to [this page](https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html) and move the slider, does the text size change, or does _only_ the width of the box get bigger?
> 
> A workaround is:
> 
> ```diff
> diff --git a/lib/matplotlib/backends/web_backend/js/mpl.js b/lib/matplotlib/backends/web_backend/js/mpl.js
> index f7ef50dab..1aced9e6a 100644
> --- a/lib/matplotlib/backends/web_backend/js/mpl.js                                  
> +++ b/lib/matplotlib/backends/web_backend/js/mpl.js
> @@ -171,7 +171,7 @@ mpl.figure.prototype._init_canvas = function () {
>          for (var i = 0; i < nentries; i++) {                     
>              var entry = entries[i];             
>              var width, height;                  
> -            if (entry.contentBoxSize) {         
> +            if (entry.contentBoxSize && entry.contentBoxSize.inlineSize !== undefined && entry.contentBoxSize.blockSize !== undefined) {
>                  width = entry.contentBoxSize.inlineSize;                                                                                 
>                  height = entry.contentBoxSize.blockSize;                                                                               
>              } else {                                                                                                                   
> ```

Yes, that slider page is working on my chrome. I will test `mpl.js` with your modification as soon as possible.

**Comment by QuLogic** [comment]
> Yes, that slider page is working on my chrome.

Do you mean the font gets bigger? It doesn't work for me.
