### ISSUE TITLE
axhspan() in empty plots changes the xlimits of plots sharing the X axis

### ISSUE THREAD

**Issue by martinber** [matplotlib/matplotlib#18137]
### Bug report

Consider you have a figure with multiple subplots sharing the X axis (`fig.subplots(2, 2, sharex="all")`). When using `axhspan()` in an Ax without data, the rest of Axes will change the X axis potentially leaving data outside the range.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax1, ax2 = fig.subplots(2, 1, sharex="all")
ax1.set_title("ax1")
ax2.set_title("ax2")

ax1.scatter([1, 2, 3, 4], [2, 3, 2, 3])
ax2.axhspan(-5, 5, alpha=0.2)

fig.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/6921727/89043601-18199c80-d31f-11ea-979c-01ad46e3ab3f.png)

**Expected outcome**

I expected both Axes to use a shared X axis in the range 1 to 4, because the data covers that interval

![image](https://user-images.githubusercontent.com/6921727/89043717-4e571c00-d31f-11ea-9a50-db2f35fc5ed8.png)

**Matplotlib version**

  * Operating system: Debian 10
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.3
  * Jupyter version (if applicable): Happens outside of Jupyter as well

Installed via pip. Running inside a `python3 -m venv`

Thank you!

**Comment by tacaswell** [comment]
This is another issue with making auto-scaling lazier.  If you put a `fig.canvas.draw()` in before you call `ax2.axhspan()` things work correctly.

**Comment by tacaswell** [comment]
This is a good first issue because there is no API design, I do not think it is desirable for the axhspan to completely clobber the x-scaling, but medium because it will involve walking through the auto scaling logic which is a bit convoluted due to a) trying to be lazy b) needing to touch a lot of different parts of the code.

Related to https://github.com/matplotlib/matplotlib/issues/17417

**Comment by learner296** [comment]
Hello @martinber, I am interested in this issue and want to contribute.

**Comment by martinber** [comment]
Hello. I understand that this project does not "assign" issues to people, so you can try to solve it without asking for permission.

Also, I'm not part of this project, but if you need something you can ask here. I will try to help too if I can

**Comment by learner296** [comment]
Thank you @martinber.  I am a novice in open source projects contribution. Please let me know how to get started? You want both interval use the same range on both x and y-axis?

**Comment by martinber** [comment]
You should fork this project and start to dig into the code to find the solution, then you can make a Pull Request. Regarding this issue, I have no idea how matplotlib works or how to solve it.

In particular, I wanted both Axes to share the same x-axis range. See that the first Ax has data and that the second Ax has no data. Normally, both should have the range [1; 4], but if I use ahvspan in the Ax without data, both Axes share the interval [-0.05; 0.05]

By the way, check the pull request linked above, looks like someone already fixed this
