### ISSUE TITLE
Bug introduced in V3.3.0 (not in V3.2.2) 'NavigationToolbar2Tk' object has no attribute '_active'

### ISSUE THREAD

**Issue by MohamadHarastani** [matplotlib/matplotlib#18148]
### Bug report

**Bug summary**
I have a code to select points from a plot. Whenever the toolbar is active (to zoom or move right-left), it ignores the mouse event.
The line of code that is checking if the toolbar is active or not has a bug in the latest update (V3.3.0). A downgrade to V3.2.2 solves the problem. 

**Code for reproduction**

```python
        # ignore click event if toolbar is active
        if self.ax.figure.canvas.manager.toolbar._active is not None: 
            return
```

**Actual outcome**

```
    if self.ax.figure.canvas.manager.toolbar._active is not None:
AttributeError: 'NavigationToolbar2Tk' object has no attribute '_active'
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Ubuntu20 and Centos7
  * Matplotlib version: 3.3.0
  * Matplotlib backend: TkAgg
  * Python version: 3.8.3
  * With conda (Anaconda3 default) and without conda, I get the same error

**Comment by timhoffm** [comment]
By standard Python convention, the underscore prefix marks `_active` as private. This should not be accessed by user code. We reserve the freedom to modify or remove private state without prior notice. - Without this freedom a development would be virtually impossible because every change could break user code.

**Comment by MohamadHarastani** [comment]
Thanks a lot for your help. I confirm that `self.ax.get_navigate_mode()` solves my issue.
However, this function returns None before any use of the toolbar. Once the toolbar is activated (ex: zoom button on) then deactivated (ex: zoom button off) it starts to return ' ' (empty string).
To verify that the toolbar is not active, I had to check the following:
`        if self.ax.get_navigate_mode() is not None and self.ax.get_navigate_mode() != '': 
`
Nevertheless, this solves my issue.
All respect,
Mohamad

**Comment by dopplershift** [comment]
FYI, that code is equivalent to:
```python
if self.ax.get_navigate_mode():
```

**Comment by MohamadHarastani** [comment]
Thanks a lot.

**Comment by QuLogic** [comment]
You may want to go through [`canvas.widgetlock`](https://matplotlib.org/api/widgets_api.html#matplotlib.widgets.LockDraw).
