### ISSUE TITLE
The parameter “fmt” doesn’t have the same behaviour in plot and plot_date

### ISSUE THREAD

**Issue by kevinlacaille** [matplotlib/matplotlib#18141]
In _pyplot.plot_, the parameter _fmt_ defines basic formatting like color, marker and linestyle. 

In _pyplot.plot_date_, the parameter _fmt_ defines the plot format string. 

This is inconsistency may lead to errors.

**Comment by tacaswell** [comment]
@kevinlacaille Do you have an example that shows what you mean?

**Comment by timhoffm** [comment]
It's not clear if that's meant, but here's the inconsisteny known for `plot_date`:

It's a known issue that the defaults of `plot()` an `plot_date()` are different (see #17548).
This can't/won't be fixed (https://github.com/matplotlib/matplotlib/issues/17548#issuecomment-637103831).

If `plot_date()` causes confusion, we should really soft-depreacate it (https://github.com/matplotlib/matplotlib/issues/17548#issuecomment-638323728).

**Comment by jklymak** [comment]
Just to clarify: the `fmt` kwarg means *exactly* the same thing in `plt.plot` and `plt.plot_date`, but it has different defaults in each method.

**Comment by kevinlacaille** [comment]
> It's not clear if that's meant, but here's the inconsisteny known for `plot_date`:
> 
> 
> 
> It's a known issue that the defaults of `plot()` an `plot_date()` are different (see #17548).
> 
> This can't/won't be fixed (https://github.com/matplotlib/matplotlib/issues/17548#issuecomment-637103831).
> 
> 
> 
> If `plot_date()` causes confusion, we should really soft-depreacate it (https://github.com/matplotlib/matplotlib/issues/17548#issuecomment-638323728).

I hadn't seen this issue. This is exactly what I was trying to convey - the default's are different, also pointed out by @jklymak , nice catch!
