### ISSUE TITLE
Feature request: poisson errorbar for hist

### ISSUE THREAD

**Issue by piti118** [matplotlib/matplotlib#1815]
Most of histogram have poisson error. would be nice to have something like `hist( xxxxx, errorbar=True)` Right now we have to do something similar to

``` pythonn
h, e, p = hist(data, bins=100)
errorbar((e[1:]+e[:-1])/2., h, sqrt(h))
```

Few additional point
- a plus if it does asymmetric error bar
- another plus if it can take into account the weight correctly for both using sum(weight^2) or  just sum(weight).

**Comment by petehuang** [comment]
This hasn't been updated in a while.

#2241 stalled but seems like there was good progress made. If you are interested in working on this, I highly suggest you take a look there.

Recommend labeling as Difficulty: Medium

**Comment by efiring** [comment]
OK, it might be medium.  That's probably optimistic.  I think this really needs to be done in the context of a rationalized, refactored system for handling histograms, as @tacaswell suggested above.

**Comment by jklymak** [comment]
I'm going to close this.  a) its really old, b) I don't think Matplotlib should make any assumptions about the underlying statistics that go into deciding errorbars.  

So the remaining issue is whether its worth decorating the histograms with a `valerr` or `yerr` argument and drawing errorbars.  I'm not seeing a compelling case other than computing the midpoints of the bins and passing to `errorbar` is mildly irritating.  The problem with rolling the decorator in with the histogram plotting is then folks will want to pass a bunch of `errorbar` kwargs to control their properties.   I don't think the complication is worth it.  

It seems to me that if someone has a use case for always adding Poisson error bars to a histogram, they could write themselves a pretty straightforward wrapper.

**Comment by Nestak2** [comment]
> I'm not seeing a compelling case other than computing the midpoints of the bins and passing to `errorbar` is mildly irritating.
 
It's not just that. Further, `plt.hist` offers the `density=True` option, which `errorbar` doesn't. And every once in a while I run into this problem

> It seems to me that if someone has a use case for always adding Poisson error bars to a histogram, they could write themselves a pretty straightforward wrapper.

But it doesn't need to be a Poisson error. It would be really great to just have the option `plt.hist(data, bins=bins, err=err_array)` and the user can provide himself the precalculated `err_array` array for the errorbars
