### ISSUE TITLE
custom Grid system

### ISSUE THREAD

**Issue by Mike-HubGit** [matplotlib/matplotlib#18155]
Not a bug report but I didn't know where I should ask this. Please do not hesitate to tell me where I should ask such a question.

I would like to make my own "grid" system for a "black" - like chart :

![](http://www.jdotec.net/s3i/TD_Info/Black/images/black_1.gif)

could you give me a starting point from that; some advice ? What object I should inheritate from to customize it for example ?

Thanks a lot,
    Mike

**Comment by jklymak** [comment]
Hi Mike,  This would probably be better at discourse.matplotlib.org.    Thanks!

**Comment by Mike-HubGit** [comment]
Thanks for your anwser !
