### ISSUE TITLE
Wrong xticks in plotting datetime by AutoDateLocator

### ISSUE THREAD

**Issue by ShafinKhadem** [matplotlib/matplotlib#18164]
### Bug report

AutoDateLocator produces wrong xticks in plotting 2D list of datetime when 1st sublist is empty. Instead of datetime, it produces some floating point numbers in xticks.

**Code for reproduction**

```python
import datetime as dt
from matplotlib import pyplot as plt

all_times = [[], [dt.datetime(2020, 7, 1, 0, 0, 0)]]
plt.hist(all_times)

```

**Actual outcome**

![outcome](https://user-images.githubusercontent.com/26321479/89270496-39e78c00-d65d-11ea-9702-4eb17db0936c.png)

**Expected outcome**

xticks should be surrounding 2020-07-01.

**Matplotlib version**

  * Operating system: Kubuntu 20.04
  * Matplotlib version: 3.3.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.8.2

matplotlib was installed using pip.

**Comment by jklymak** [comment]
Thats expected behaviour - by passing empty data, the units registry thinks you mean floats and hence plots floats.  In the case of a mix of types, the units system chooses the most generic type, which is floats

**Comment by ShafinKhadem** [comment]
@jklymak If the units system chooses the most generic type, shouldn't it produce same output if 2nd sublist is empty instead of 1st sublist? But it produces perfectly fine (different) output if 2nd sublist is empty:

Code:

```python3
import datetime as dt
from matplotlib import pyplot as plt

all_times = [[dt.datetime(2020, 7, 1, 0, 0, 0)], []]
plt.hist(all_times)
```
Output:
![case2](https://user-images.githubusercontent.com/26321479/89334590-97f58d00-d6b8-11ea-91dc-69e33ec2799c.png)

**Comment by jklymak** [comment]
Sorry, I guess I should have said it chooses the *first* element.  You could argue that it should ignore "some" bad values (empty list elements, `None`, `np.NaN`, `np.Inf`, `np.NaT`, etc) at the beginning, and indeed this was talked about at some point, but too much pre-processing magic can have bad side effects.
