### ISSUE TITLE
Add feature request template

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#18160]
### Problem
On matplotlib.org the official guidance for feature requests is now to open a github issue:
![image](https://user-images.githubusercontent.com/10111092/89195354-aa67ad80-d576-11ea-8f85-85e3a675519d.png)
however there is currently only a bug report template. This can induce doubts for someone new to github that it is ok to open an issue for a feature request. Additionally feature requests may be less structured than is optimal without the guidelines provided by a template.

### Proposed Solution

Create a feature request template and have all official new issue links lead to: https://github.com/matplotlib/matplotlib/issues/new/choose

### Additional Context

I made the same suggestion at jupyterlab in https://github.com/jupyterlab/jupyterlab/issues/8226 and we implemented it with the below template:
```
name: Feature Request
about: Suggest something to add to JupyterLab
labels: type:Enhancement
---

<!--
Welcome! Thanks for thinking of a way to improve JupyterLab. If this solves a problem for you, then it probably solves that problem for lots of people! So the whole community will benefit from this request.


Before creating a new feature request please search the issues for relevant feature requests.
-->

### Problem

<!-- Provide a clear and concise description of what problem this feature will solve. For example:

* I'm always frustrated when [...] because [...]
* I would like it if [...] happened when I [...] because [...]
-->

### Proposed Solution

<!-- Provide a clear and concise description of a way to accomplish what you want. For example:

* Add an option so that when [...]  [...] will happen
 -->

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]
-->
```

**Comment by story645** [comment]
Totally agree/this has been on a to do list forever and just hasn't jumped to the top of the queue. You're welcome to open this PR (but then please also make the bug template!).
