### ISSUE TITLE
why not upload the offline website with the zip？？？？？

### ISSUE THREAD

**Issue by dingli06** [matplotlib/matplotlib#18209]
**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Thanks for your interest in matplotlib, but this isn't actionable.  Thanks!

**Comment by QuLogic** [comment]
If you want a self-contained version of the docs, you can download the PDF version at https://matplotlib.org/Matplotlib.pdf It is unlikely that we will include this in the sdist or binary wheels, as that would double the size.

**Comment by tacaswell** [comment]
The website is hosted from https://github.com/matplotlib/matplotlib.github.com so you if you need an offline copy of our html docs you can clone that (and host internally if needed).
