### ISSUE TITLE
Incorrect output for gourad shading in pcolormesh

### ISSUE THREAD

**Issue by petar-andrejic** [matplotlib/matplotlib#18208]
### Bug report

**Bug summary**
In version 3.3.0 gourad shading gives incorrect output for `pcolormesh`.  Using nearest neighbour gives the correct output still. The output is somehow shifted and/or rotated. Using 3.2.0 gives correct results for both.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.use('Agg')

x = np.linspace(-10, 10, 100)
y = np.linspace(0, 5, 50)

x_grd, y_grd = np.meshgrid(x,y)

f = np.exp(-(x_grd - y_grd * 0.4)**2)

plt.figure()

for shading in ['gourad', 'nearest']:
    plt.clf()
    plt.pcolormesh(x, y, f, shading=shading, norm=mpl.colors.LogNorm())
    plt.savefig(f'test_v{mpl.__version__}_s_{shading}.png')
```

**Actual outcome**
In matplotlib 3.3.0

With gourad:
![test_v3 3 0_s_gourad](https://user-images.githubusercontent.com/17103815/89735077-33438500-da60-11ea-9a02-7a848db46b41.png)

With nearest:
![test_v3 3 0_s_nearest](https://user-images.githubusercontent.com/17103815/89735079-35a5df00-da60-11ea-9d80-d9cc4bd51f88.png)

**Expected outcome**
In matplotlib 3.2.0

With gourad:
![test_v3 2 0_s_gourad](https://user-images.githubusercontent.com/17103815/89735140-bbc22580-da60-11ea-86a4-4d61cf26dcf8.png)

With nearest:
![test_v3 2 0_s_nearest](https://user-images.githubusercontent.com/17103815/89735187-05ab0b80-da61-11ea-9aa8-ec56e0a68498.png)

**Matplotlib version**

  * Operating system: macOS 10.15.6 
  * Matplotlib version: 3.3.0
  * Matplotlib backend: agg
  * Python version: 3.7.4
  * Jupyter version (if applicable): N/A
  * Other libraries: numpy 1.19.1

Python installed via anaconda, numpy and matplotlib installed via pip in a fresh virtual environment.

**Comment by jklymak** [comment]
You are misspelling `'gouraud'`.  See #18076 and #18079 for better argument checking.
