### ISSUE TITLE
Updated WxAgg NavigationToolbar2 breaks custom toolbars

### ISSUE THREAD

**Issue by jbhopkins** [matplotlib/matplotlib#18212]
### Bug report

**Bug summary**

In matplotlib 3.3, the WxAgg backend NavigationToolbar2 has added a readout of the cursor position on the far right of the toolbar. This breaks the layout of custom toolbars where users have added their own buttons or other widgets. Because the cursor position is added with a stretchspacer, any widget added after it as also added to the far right of the toolbar. In addition (possibly due to adding the custom widgets after the toolbar is initially realized?), the cursor readout can appear under the custom toolbar buttons.

Here's a custom toolbar from a program I maintain using matplotlib 3.3 and 3.2.2.

With 3.2.2:
<img width="388" alt="custom_toolbar_mpl3p2p2" src="https://user-images.githubusercontent.com/23534688/89801803-41dc7b80-daf6-11ea-832b-e5eb53c09eec.png">

With 3.3:
<img width="537" alt="custom_toolbar_mpl3p3" src="https://user-images.githubusercontent.com/23534688/89801810-443ed580-daf6-11ea-9179-194dfe0e724e.png">

**Code for reproduction**

```python
import wx
import matplotlib as mpl
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg

class CustomToolbar(NavigationToolbar2WxAgg):
    def __init__(self, canvas):

        NavigationToolbar2WxAgg.__init__(self, canvas)

        move_bitmap = wx.Bitmap('./images/move.png')
        self.AddCheckTool(wx.ID_ANY, '', move_bitmap, shortHelp='Second Move Button')

class PlotFrame(wx.Frame):
    def __init__(self, parent, title, *args, **kwargs):
        wx.Frame.__init__(self, parent, title=title, *args, **kwargs)

        self.fig = mpl.figure.Figure((5,4))
        self.subplot1 = self.fig.add_subplot(111)
        self.canvas = FigureCanvasWxAgg(self, wx.ID_ANY, self.fig)

        self.toolbar = CustomToolbar(self.canvas)
        self.toolbar.Realize()

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.canvas, 1, wx.LEFT | wx.TOP | wx.GROW)
        sizer.Add(self.toolbar, 0, wx.GROW)

        self.SetSizer(sizer)
        self.Layout()
        self.Fit()
        self.CenterOnScreen()
        self.Show(True)

if __name__ == '__main__':
    app = wx.App(False)
    frame = PlotFrame(None, 'My Plot Frame')
    app.MainLoop()
```

**Actual outcome**
Actual outcome with 3.3:
<img width="499" alt="actual_outcome" src="https://user-images.githubusercontent.com/23534688/89802138-b0b9d480-daf6-11ea-8e93-0e9338c6356f.png">

**Expected outcome**
Expected outcome (as with previous versions, using 3.2.2):
<img width="501" alt="expected_outcome" src="https://user-images.githubusercontent.com/23534688/89802179-c4fdd180-daf6-11ea-8c43-029673c2da8c.png">

**Matplotlib version**
  * Operating system: MacOS 10.14.6
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): WxAgg
  * Python version: 3.7.6
  * Other libraries: wxpython 4.0.4

Everything installed through conda. Matplotlib 3.2.2 installed from the main channel, 3.3.0 installed from conda-forge channel.

**Comment by jbhopkins** [comment]
There are a couple ways I've thought of this could be fixed, neither of them particularly hard. If someone tells me what the preferred option is, or suggests another option, I'm happy to do the coding and make a pull request.

Option 1:
Add a keyword argument to the NavigationToolbar2Wx class, something like 'show_mouse_pos=True'. If this is True (default), then show the cursor readout in the toolbar (current behavior). If it isn't, then don't add the cursor position to the toolbar. I've tested this and it's easy to implement.

Option 2:
Don't add the stretch spacer for the cursor position. If you have the cursor position just after the save button, and you save the tool id  for the cursor readout ``StaticText`` in the ``self.wx_ids`` dictionary, someone could then programmatically remove the cursor readout using ``wx.ToolBar.DeleteTool``. At least in my testing I could remove the stretch spacer using this function, so this option would require that stretch spacer not be added. I've tested this and it's easy to implement.


I prefer option 1, because that provides a clean API for those who don't want the cursor readout. Option 2 would require anyone who wants to do this to go digging around in the backend code. However, I don't know if there are constraints on the API for these NavigationToolbars in general across backends that might make that a less appealing option.

**Comment by tacaswell** [comment]
Option 1 is better here, it gives you a clean way out and will match the qt5 toolbar https://github.com/matplotlib/matplotlib/blob/7b562264b38b64f34979d06ef97c8cdcc222e8e6/lib/matplotlib/backends/backend_qt5.py#L654-L655

I do not disagree that `show_mouse_pos` is a more descriptive name, but for consistency we should match `coordinates`.

**Comment by QuLogic** [comment]
Note, we would like to release 3.3.1 in a day or two, if you could get that PR in soonish.
