### ISSUE TITLE
Figure out why test_interactive_backend fails on Travis macOS

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#18213]
In the interest of getting 3.3.1 out, we skipped the `test_interactive_backend` test on Travis macOS. It works correctly on a 'real' macOS machine from MacStadium, so we were okay with this for now. However, we should get to the bottom of this failure, whether it's because of old macOS settings on Travis, or whether it's something we can't rely on overall.

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: `master`+#18184 (45d748b44270a23b830e1a7aa7586267408819b9)
  * Matplotlib backend (`print(matplotlib.get_backend())`): macOS
  * Python version: 3.8.5

Marked as Good first issue, as this _should_ be self-contained to the macOS backend and CI, but Medium difficulty, because it's CI...

**Comment by QuLogic** [comment]
Also, cc @jkseppan since you worked on the Travis macOS build. Note that the code in #18184 that was reverted to used to work fine, but that was before the Travis changes.

**Comment by dopplershift** [comment]
Well it's not just CI, I can't get that test to pass at all on my system. What I'm seeing on my system is that the two images in that test are saved with two different DPI's. Here's the before image (Mac Preview says 100 dpi):
![before](https://user-images.githubusercontent.com/221526/90321956-ab4ff600-df0b-11ea-9e89-a934bbef549b.png)

And here's the after (Mac Preview says 200 DPI):
![after](https://user-images.githubusercontent.com/221526/90321959-b0ad4080-df0b-11ea-8a80-6f49038fd595.png)

I can get the test to pass by passing `dpi=100` to the two calls to `savefig()` in the test. That doesn't feel like a fix, though--why would the DPI change in this code?
```python
fig, ax = plt.subplots()
assert_equal(
    type(fig.canvas).__module__,
    "matplotlib.backends.backend_{}".format(backend))

ax.plot([0, 1], [2, 3])

timer = fig.canvas.new_timer(1.)  # Test that floats are cast to int as needed.
timer.add_callback(FigureCanvasBase.key_press_event, fig.canvas, "q")
# Trigger quitting upon draw.
fig.canvas.mpl_connect("draw_event", lambda event: timer.start())
fig.canvas.mpl_connect("close_event", print)

result = io.BytesIO()
fig.savefig(result, format='png')

plt.show()

# Ensure that the window is really closed.
plt.pause(0.5)

# Test that saving works after interactive window is closed, but the figure is
# not deleted.
result_after = io.BytesIO()
fig.savefig(result_after, format='png')
```

**Comment by dopplershift** [comment]
Here's the minimum reproducible case for getting the DPI change:
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
fig.savefig('before.png')

plt.pause(0.5)  # Need for change in DPI; plt.show() also equivalent

fig.savefig('after.png')
```

**Comment by dopplershift** [comment]
So the issue is that the macosx backend assumes its device scale is 1.0 until it does a draw, then it knows it from the graphics context. Just need to plumb something in to allow it to know that from the start.

**Comment by LuiGiovanni** [comment]
Hello! This is my first time contributing, I'd like to work on this issue. Is there anything I should do previously or some steps I need to follow?

**Comment by QuLogic** [comment]
I think @dopplershift is working on this in the above-linked PR; I don't know what the state of it is at this moment.

**Comment by dopplershift** [comment]
I've poked at it, but I don't have anything useful to share IIRC.

**Comment by dstansby** [comment]
Can this be closed now we've migrated off Travis?
