### ISSUE TITLE
The way to scatter in a sphere style.

### ISSUE THREAD

**Issue by heatwind** [matplotlib/matplotlib#18211]
Dear matplotlib users:
I used this code to plot scatter in sphere-like marker:
```python
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from matplotlib.cbook import get_sample_data
def getImage(path):
    return OffsetImage(plt.imread(path), zoom=0.03)
    
fig = plt.figure(figsize=[5,4],dpi=300)
ax1 = fig.add_subplot(1,1,1)

X=[0,100,200,300,400,500]
Y1=[i*0.1 for i in X ]
Y2=[i*0.2 for i in X ]
paths1 = ['a.png']*len(X)
paths2 = ['b.png']*len(X)
for x0, y0, path in zip(X,Y1,paths1):
    ab = AnnotationBbox(getImage(path), (x0, y0), frameon=False)
    ax1.add_artist(ab)
for x0, y0, path in zip(X,Y2,paths2):
    ab = AnnotationBbox(getImage(path), (x0, y0), frameon=False)
    ax1.add_artist(ab)
plt.xlim([0,500])
plt.ylim([0,100])
plt.savefig('scatter_sphere_marker.png')
```
'a.png' and 'b.png':
<img src="https://user-images.githubusercontent.com/45888086/89854662-065db200-dbc7-11ea-81c1-13e154b833dc.png" width="100" height="100" >      <img src="https://user-images.githubusercontent.com/45888086/89854668-0a89cf80-dbc7-11ea-916f-9e887df1975f.png" width="100" height="100" >
The output is:
 <img src="https://user-images.githubusercontent.com/45888086/89855062-10cc7b80-dbc8-11ea-859c-ae142cbaf7a6.png" width="400" height="320" >

There are some problems:

1. How to add legend?
2. How to erase the excess part of the sphere?
3. Is there any other way to draw this sphere maker? Ploting like this is still too much trouble.

 <img src="https://user-images.githubusercontent.com/45888086/89855237-918b7780-dbc8-11ea-95c7-f914ae281573.png" width="300" height="250" >

**Comment by story645** [comment]
Hello, is there some way in which we could improve our docs or API to make this task easier or clearer?
If you do not have constructive suggestions for the code or docs, then the appropriate venue for these sorts of questions is https://discourse.matplotlib.org/

If we do not hear back from you here in a day or two, someone will close this issue.

**Comment by heatwind** [comment]
> Hello, is there some way in which we could improve our docs or API to make this task easier or clearer?
> If you do not have constructive suggestions for the code or docs, then the appropriate venue for these sorts of questions is https://discourse.matplotlib.org/
> 
> If we do not hear back from you here in a day or two, someone will close this issue.

Thanks for your advice! I have modified the issue.

**Comment by heatwind** [comment]
Can someone tell me why this issue was closed? This question is very clear! @timhoffm

**Comment by WeatherGod** [comment]
Just to be clear, this questions is an excellent question to ask! However, this is an issue tracker, not a community support forum. The appropriate place for this question would be the Discourse link mentioned earlier.

**Comment by timhoffm** [comment]
Discourse thread: https://discourse.matplotlib.org/t/is-there-a-way-to-draw-such-a-scatter-plot/21470
