### ISSUE TITLE
Python plot similar to Matlab's stackedplot()

### ISSUE THREAD

**Issue by addarnr** [matplotlib/matplotlib#18217]
Hello,
Is there a plot function available in Python that is same as Matlab's stackedplot()?
stackedplot() in Matlab can line plot several variables with the same X axis and are stacked vertically. Additionally, there is a scope in this plot that shows the value of all variables for a given X just by moving the cursor (please see the plot below). I have been able to generate subplots in Python with no issues, however, not able to add a scope like this that shows the value of all variables by moving the cursor. Is this feature available in Python?

Thanks much for your help in advance!

![stackedplot scope2](https://user-images.githubusercontent.com/34237024/89889882-04c8c580-db98-11ea-9d4a-bf4179980d6a.png)

**Comment by QuLogic** [comment]
I think you're looking for [MultiCursor](https://matplotlib.org/api/widgets_api.html#matplotlib.widgets.MultiCursor). For annotated values, take a look at [mplcursor](https://mplcursors.readthedocs.io/) or [mpldatacursor](https://github.com/joferkington/mpldatacursor).

Please use our [Discourse](https://discourse.matplotlib.org) for further usage questions.
