### ISSUE TITLE
It is painful as a new user, to figure out what AxesSubplot is

### ISSUE THREAD

**Issue by aathan** [matplotlib/matplotlib#18222]
### Bug report

Try googling "AxesSubplot" which is the type you get back from a plt.gca() call. Try finding this class in the docs. Try searching for this class in the source code.

Poor new users trying to figure out what they're dealing with...

(It's a dynamic class created in _subplot.py that is a subclass of Axes, but ... boy was that a pain to detangle. Asked it's class for it's __module__, etc... Have mercy on new users and make it easier to find documentation for dynamic classes.)

(and no, it's not good enough that google does show Axes in its result, because it's not AxesSubplot, and if you're chasing down an AttributeError, or have a typo in a function call that you believe it "should" respond to, you're in a mindset of thinking "this must not be an Axes")

**Comment by timhoffm** [comment]
As a remark, `gca()` will return an `Axes` or a subclass thereof. For example `plt.axes([0, 0, 1, 1])` will result in the current axes being an `Axes` instance directly.

Would have a more descriptive docstring of `AxesSubplot` have helped?

**Comment by aathan** [comment]
I'm pretty sure plt.gca() was returning an AxesSubplot. See #18220 for the code. Anything that fixes the online docs and/or increases the probability that a user will quickly understand what AxesSubplot is, would be an improvement.

**Comment by tacaswell** [comment]
Can you be a bit more specific about what changes to the documentation would have helped?

As a side note, my go-to tools when exploring new classes (looking at the mro and isinstance checks)

```python

In [13]: isinstance(plt.gca(), matplotlib.axes.Axes)                                                                                                                                                                                                                                                   
Out[13]: True

In [14]: type(plt.gca()).mro()                                                                                                                                                                                                                                                                         
Out[14]: 
[matplotlib.axes._subplots.AxesSubplot,
 matplotlib.axes._subplots.SubplotBase,
 matplotlib.axes._axes.Axes,
 matplotlib.axes._base._AxesBase,
 matplotlib.artist.Artist,
 object]
```

both seem pretty clear.

**Comment by aathan** [comment]
Thomas, I agree. Those things are clear. If it wasn't clear above, the specific fixes I recommend are:

1) Ensuring that an <insert favorite search engine> search of AxesSubplot leads to a useful documentation page *that appears to be about AxesSubplot* (and points you to Axes for more info)
2) Ensuring that the docstring for AxesSubplot includes words like "AxesSubplot *is* the Axes instance for certain plots, returned by calls such as gca(), and does not have any special plotting related behaviors related to subplots per-se. It is a dynamically generated class for persistence (pickling) purposes."
3) Ensuring that at the matplotlib.org site, the search box returns non-empty results for "AxesSubplot" -- preferably a link to Axes documentation per # 1 & # 5. Currently it returns one result and it's not helpful documentation, titled "origin and extent in imshow"
4) Mentioning AxesSubplot (and any other Subplot dynamic classes) in their parent class' documentation (i.e., # 1)
5) Including the names of likely frequently encountered autogenerated subclasses in the .py that generates them

As things currently stand, AxesSubplot is frequently encountered when using matplotlib but isn't even mentioned in the docs. This leads to many questions about what it might be, whether it is a true Axes or (per its name) doing some special forwarding or modified behaviors for contained Axes of subplots, etc ... and when one goes to find the source code to make sure it's the Axes you want to be talking to ... you end up not finding it easily because it's name appears nowhere in the source code either.

I hope that helps :)

Matplotlib is awesome.

**Comment by jklymak** [comment]
I agree this is painful.  Its made worse by the fact that we use a factory to create the subclass, so its really hard as a beginner interested in the internals to trace how the class is even defined.  It would be nice to figure out a reasonable place to explain this.

**Comment by timhoffm** [comment]
In principle, it should be possible to document dynamically created classes in Sphinx because AFAIK it uses introspection and no static code analysis.

**Comment by DingXuefeng** [comment]
I think adding the sentence "AxesSubplot" is a dynamically created class inheriting SubplotBase" in the docstring of `SubplotBase` (https://matplotlib.org/3.3.0/api/_as_gen/matplotlib.axes.SubplotBase.html) would be enough.

**Comment by anntzer** [comment]
Actually, looking at it again, I think it may be reasonable to just push all the SubplotBase functionality either to the base Axes class (with `ax.get_subplotspec` returning None if the axes is not gridspec-positioned) or, for lower level stuff (`is_first_row`, etc.) to the SubplotSpec.  This means that one would have to change all the `isinstance(ax, SubplotBase)` checks to `ax.get_subplotspec() is not None` which seems fine (you even save an import ;-)), but gets rid of the main dynamically generated subclass, which is a big simplification...
The Axes and Subplot constructor signatures are different (one takes a rectangle and the other something convertible to a SubplotSpec) but we can easily support both at least during the transition period (and possibly forever); in any case direct instantiations of Axes/Subplots are rare as one usually relies on add_subplot/add_axes/subplots.

**Comment by anntzer** [comment]
AxesSubplot is going away; this started in #18564.  While this will still take a couple of releases to finish (because of backcompat-imposed waits), I think this issue can be closed as it will basically fix itself once the deprecations in #18564 expire.  Feel free to reopen if you disagree.

**Comment by raamana** [comment]
just wanted to say I agree with the sentiment of pain with `AxesSubplot` expressed here, and wanted to bring a relevant question of mine over at MPL discord to your attention: https://discourse.matplotlib.org/t/comparing-axessubplot-with-axes/22676?u=raamana

**Comment by anntzer** [comment]
AxesSubplot is going away; the deprecation machinery is already in (cf mpl.axes._subplots), now someone (mostly) just needs to pull the thread and remove everything...

**Comment by raamana** [comment]
thanks @anntzer, I noticed that. I guess you are suggesting not to deal with it all, which would mean me not using `plt.subplots()` (or any derivatives of `pyplot` really to be future-proof) which would return an AxesSubplots. What do you recommend as a clear and robust alternative to 
```python
fig, axes = plt.subplots(n_rows, n_cols, figsize)
```
that doesn't depend on any subplot mechanism, and returns the "unadulterated" native `Axes`? 

I am assuming GridSpec only deals with geometry (and not create axes), and the new mosaic compositional mechanism still returns AxesSubplots:

```python
from matplotlib import pyplot as plt
fig = plt.figure(constrained_layout=True)
ax_dict = fig.subplot_mosaic(
    [
        ["bar", "plot"],
        ["hist", "image"],
    ],
)

ax_dict
Out[22]: 
{'bar': <AxesSubplot:label='bar'>,
 'plot': <AxesSubplot:label='plot'>,
 'hist': <AxesSubplot:label='hist'>,
 'image': <AxesSubplot:label='image'>}
``` 

i have created grids of axes before e.g. in the `mrivis` [library](https://github.com/raamana/mrivis/blob/fe6523d7f0c6be375503e6c6b160fff804b8eec2/mrivis/base.py#L508), but I am hoping MPL team may have a more native or better solution, that'll likely to remain the codebase for a longtime to come (so I dont have to worry about deprecations and future changes)

Thanks you for help.

**Comment by anntzer** [comment]
See https://discourse.matplotlib.org/t/comparing-axessubplot-with-axes/22676/3.

**Comment by kate-jeffreys** [comment]
FWIW: TIL what `AxesSubplot` is by reading this issue. Thank you @aathan!

**Comment by davidgilbertson** [comment]
For anyone who found this and is not yet on v3.7, know that `AxesSubplot` is now gone (although true to form, isn't actually mentioned anywhere in release notes!)

**Comment by jklymak** [comment]
>  true to form

Ouch - PRs gratefully accepted, even for post-facto improvements to the release notes - sometimes things get overlooked with the finite developer time at our disposal https://github.com/matplotlib/matplotlib/blob/main/doc/users/prev_whats_new/whats_new_3.7.0.rst

**Comment by tacaswell** [comment]
Please see discussion at https://github.com/matplotlib/matplotlib/issues/25228#issuecomment-1433799981 as to why we did not consider this an API change.

**Comment by davidgilbertson** [comment]
Sorry @jklymak I didn't mean it in an ouchy way at all, I actually thought it was quite funny that the elusive `AxesSubplot` would leave the API without a trace. Certainly not meant as a criticism of anyone.

**Comment by tacaswell** [comment]
This is a good example of why text-only communication is hard!

Reading your message with a joking tone of voice is funny (that class is a ghost and disappeared like one) vs and angry one (the good for nothing devs once again changed things) induce very different responses.
