### ISSUE TITLE
_reshape_2D function behavior changed, breaks hist for some cases in 3.3.0

### ISSUE THREAD

**Issue by RyanBaten** [matplotlib/matplotlib#18234]
### Bug report

**Bug summary**

In version 3.2.2, plt.hist(df['class']) will produce a correct histogram where df['class'] is a series of strings. In version 3.3.0, _reshape_2D gives different output in this case, leading to slow computation and a graph with too many bars.

**Code for reproduction**

```python
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('titanic')
plt.hist(df['class'])
```

**Actual outcome**

This is under matplotlib 3.3.0:
![image](https://user-images.githubusercontent.com/11932155/90066285-c2dc7400-dcaa-11ea-8a7d-03ddade13fbf.png)

This is _reshape_2D under 3.3.0:
![image](https://user-images.githubusercontent.com/11932155/90066985-b4db2300-dcab-11ea-86bb-c4d843f57555.png)

**Expected outcome**

This is under matplotlib 3.2.2:
![image](https://user-images.githubusercontent.com/11932155/90066468-03d48880-dcab-11ea-9f7d-42e76bec4621.png)

This is _reshape_2D under 3.2.2:
![image](https://user-images.githubusercontent.com/11932155/90067025-c45a6c00-dcab-11ea-9c88-16c23ef107ec.png)

Can produce the same output for 3.3.0 by putting the series in a list but ideally I think the behavior should remain the same since this unexpectedly  also breaks other function behavior relying on this (pandas.DataFrame.hist(), plt.hist())

**Matplotlib version**

  * Operating system: macOS Mojave 10.14.6
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.4
  * Jupyter version (if applicable):
  * Other libraries: numpy: 1.18.1, pandas: 1.1.0, seaborn: 0.9.0

matplot lib installed via pip

**Comment by tacaswell** [comment]
Thanks for reporting this.

In the future please always post code and text output as text rather than screen shots.

**Comment by tacaswell** [comment]
Do you have this problem with all pandas series or just categorical?

**Comment by tacaswell** [comment]
As a workaround, 

```python
plt.hist(np.array((df['class'])))
```

will get back the old plotting behavior.  Something is not quite right with the way we are trying to duck-type pandas catarogical series. I suspect the right fix is for pandas to register a converter on their side that tells us how to interpret them...

**Comment by jklymak** [comment]
This bisects to #17821 and #17289 where we messed with `_reshape_2D` to keep bumpy happy.

**Comment by jklymak** [comment]
I do think that if we first-class pandas like this, we need to have far more comprehensive pandas testing to catch stuff like this.

**Comment by RyanBaten** [comment]
To address @tacaswell 's question:
Found this to not just be the case for categorical.
`>>> series = pd.Series(['a', 'b', 'b', 'c', 'd'])
>>> plt.hist(series)
(array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]), array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. ]), <a list of 5 BarContainer objects>)
>>> plt.show()
>>> series.dtype
dtype('O')`

![image](https://user-images.githubusercontent.com/11932155/90157670-3f269400-dd4b-11ea-88e5-ec8eb508f167.png)

The workaround
`plt.hist(np.array((df['class'])))`
and `plt.hist([df['class']])` both produce expected output as it was under the older version.


For series that are 'int64' dtype, the output is as expected (although the bars are not centered in both 3.3.0 and 3.2.2).
`>>> series = pd.Series([1,2,3,4,5,4,3,2,3,4,3,2])
>>> series.dtype
dtype('int64')
>>> plt.hist(series)
(array([1., 0., 3., 0., 0., 4., 0., 3., 0., 1.]), array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ]), <BarContainer object of 10 artists>)
>>> plt.show()`

![image](https://user-images.githubusercontent.com/11932155/90158002-a8a6a280-dd4b-11ea-8784-865d725cfc5e.png)

**Comment by jklymak** [comment]
> Found this to not just be the case for categorical.

I'm confused.  Categoricals has the problems, and integers do not, right?

**Comment by RyanBaten** [comment]
Yes, problem exists for 'category' and 'object' but not integers.

**Comment by jklymak** [comment]
The problem is that `if isinstance(xi, collections.abc.Iterable):` returns True for a string, but we really want it to be false...

**Comment by jklymak** [comment]
Basically categoricals never got a test with hist at all.  

```python 
import matplotlib.pyplot as plt
ser = ['a', 'b', 'b', 'c', 'd', 'ff', 'ff', 'a']
plt.hist(ser)
plt.show()
```
fails...  The fix is pretty easy, but we need to fix the tests as well...
