### ISSUE TITLE
LaTeX overset: unknown symbol

### ISSUE THREAD

**Issue by maxdevblock** [matplotlib/matplotlib#18241]
### Bug report

**Bug summary**

LaTeX parser error with `\overset` symbol

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.text(0, 0, r"$x \overset{f}{\rightarrow} y$")
```

**Actual outcome**

```
ValueError: 
x \overset{f}\rightarrow y
  ^
Unknown symbol: \overset, found '\'  (at char 2), (line:1, col:3)
```

**Expected outcome**

overset: http://tex.wikidot.com/snippets:overset-and-underset

**Matplotlib version**

  * Operating system: macOS 10.15.5
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.7.7
  * Jupyter version: 6.0.3 (IPython 7.13.0)

`matplotlib` installed with `pip`.

**Comment by QuLogic** [comment]
Fixed by #18916.
