### ISSUE TITLE
test_never_update is flaky

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#18246]
### Bug report

So far, I've only seen this on macOS CI. `test_never_update` crashes and thus fails.

On #18235, I had to restart macOS on Azure 4 times to pass. In #18243 it failed on Travis _and_ Azure, but only macOS.

cc @richardsheridan

**Matplotlib version**
  * Operating system: macOS, mostly
  * Matplotlib version: master-ish
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.8 / 3.8.5

**Comment by QuLogic** [comment]
[Here is the log from #18235](https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=13719&view=logs&j=c5b8964a-4208-5c0f-e21e-ad77bfbb5473); if you click Show Previous Attempts on the side bar, you can find logs from the crashing runs. Apparently someone else also restarted it 3 more times, too.

**Comment by richardsheridan** [comment]
I don't have access to macOS to test so I might not be much help. Re-running the full test suite on my local machine, I did notice that the test leaves two windows hanging around after. This doesn't happen on a partial run of test_backends_interactive.py, so there might be some spooky interaction at a distance. Perhaps we could try running the test in a subprocess?

**Comment by tacaswell** [comment]
Thanks for looking at this @richardsheridan !

**Comment by richardsheridan** [comment]
Learned two things from these PRs:

1. Subprocess isolation works to keep the test worker from crashing at least. In the stderr of those tests on macos it seems it can't find [configure_subplots](https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=13769&view=logs&j=4ad51567-0346-541f-ed03-c02090903d19&t=6d23625a-f2f5-54de-5ec8-f054a313fc89&l=185) even though it's clearly part of the declared [interface](https://github.com/matplotlib/matplotlib/blob/792756c60975520e9993379a14711c08459ad11c/src/_macosx.m#L869).
2. Taking a little care to destroy tkinter when you're done is enough to fix the weird long-lived windows when I run the full test suite locally, but it doesn't fix the crashes on macos. Unless we're prepared to go full [cpython test suite](https://github.com/python/cpython/blob/3.9/Lib/tkinter/test/support.py) on it, I'd say the subprocess strategy is the way to go.

I think we'll need someone with a mac and some experience with _macosx.m to debug missing attribute problem.

**Comment by QuLogic** [comment]
You should not be seeing `NavigationToolbar2Mac` if you are running with TkAgg. The subprocess is using the default backend, so it's not testing what you think it's testing. Set `'MPLBACKEND': 'TkAgg'` in `env` to force it to use TkAgg.

**Comment by dopplershift** [comment]
On my mac, running 10.15.6 and Python 3.8, I can't get `test_never_update` to fail. I also can't get `test_interactive_backend[toolbar2-macosx]` ever to pass...
