### ISSUE TITLE
Why does the colormap Greys_r (for vmin=0 and vmax=1) not just directly  reproduce numbers between 0 and 1?

### ISSUE THREAD

**Issue by lorenzop97** [matplotlib/matplotlib#18255]
I wanted to plot a gray image using pyplot.imshow(), that had been converted 
to a grayscale 2D-array. After researching a little, I found out that I had to use 
vmin=0 and vmin=1 (or 0 and 255 respectively) to get the right colors. However, 
I noticed that the contrast was still not correctly reproduced. 
I played around and found out that the Greys_r colormap, even when given values
between 0 and 1 doesn't exactly reproduce them but slightly changes them (don't 
even know how). 

I also tried with the parameter norm=mpl.colors.NoNorm(), it still gave the same result.
So, how do I correctly show a simple grayscale image without distorting the colors then?

**Example code:**
[test.png](https://user-images.githubusercontent.com/45875208/90254452-0c5fc700-de43-11ea-828f-120460149063.png)
```
import matplotlib as mpl
import numpy as np

im = mpl.image.imread(test.png) #this is still an RGB-data img
plt.figure()
plt.imshow(im)

#now take just one channel (they are all identical)
plt.figure()
plt.imshow(im[:,:,0],cmap="Greys_r",vmin=0,vmax=1)

plt.show()

#The issue becomes even more apparent when feeding a linear sequence
Greys_r = mpl.pyplot.get_cmap("Greys_r")
print("This linearly seperated sequence:")
print(np.linspace(0,1,11))
print("becomes:")
print(Greys_r(np.linspace(0,1,11)))
```

**Output:**
![image](https://user-images.githubusercontent.com/45875208/90254769-8f811d00-de43-11ea-899d-075025ff5647.png)
![image](https://user-images.githubusercontent.com/45875208/90254779-9576fe00-de43-11ea-9036-1a7693008e55.png)
Feeding a linearly seperated sequence:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
becomes:
[[0.         0.         0.         1.        ]
 [0.11380238 0.11380238 0.11380238 1.        ]
 [0.25098039 0.25098039 0.25098039 1.        ]
 [0.37130334 0.37130334 0.37130334 1.        ]
 [0.47843137 0.47843137 0.47843137 1.        ]
 [0.59063437 0.59063437 0.59063437 1.        ]
 [0.71058824 0.71058824 0.71058824 1.        ]
 [0.80878124 0.80878124 0.80878124 1.        ]
 [0.88705882 0.88705882 0.88705882 1.        ]
 [0.9538639  0.9538639  0.9538639  1.        ]
 [1.         1.         1.         1.        ]]

**Comment by jklymak** [comment]
Can you take this up on discourse.matplotlib.org?   There is also lots of discussion about this on stackoverflow.  Thanks!
