### ISSUE TITLE
Circle and CirclePolygon on datetime plots is painful (more generally, uniform patches on non-uniform axes)

### ISSUE THREAD

**Issue by aathan** [matplotlib/matplotlib#18267]
### Problem

Some patches (notably Circle and CirclePolygon, regular polygon etc) are defined in terms of a single parameter where that parameter may not have a suitable interpretation on Axes with an aspect ratio that is not 1, and are thus very difficult to use in data space. When the aspect ratio is << 1 or >> 1, the result can be a line, or a dot, or invisible, and can this can be very confusing. E.g., a datetime plot of Y values in the 1000s spanning an hour has X value spans < 1, but Y values 1000x larger.

Further, the transformation API docs do not mention how to easily combine transforms AND there is no built-in call to get a transform from data space (non-unit aspect ratio) to axis space (unit aspect ratio).

Meanwhile, other patches (such as Rectangle) operate in data-space just fine, creating the impression patches should generally function well in data space.

In the code sample below, only the c1 circle displays properly, and it must be defined in axes space (0..1,0..1), which requires transforming the data coordinate to axes space, which requires knowing about the + operator on transform objects, and inverted() ... PITA.

### Proposed Solution

I do not know the matplotlib API well enough to suggest an API improvement that is consistent with your design, but I certainly think some sugar could be added to make using Circle, CirclePolygon, etc patches less painful. E.g., if a patch knew it was parameterized in terms of a particular data dimension (x or y), the appropriate transform could be applied (e.g., by Axes.add_patch())

Could be  as simple as a radius_xdata or radius_ydata parameter to signal radius size vs the given axis.

### Additional context and prior art

```
  # Create new plot
   fig = plt.figure()
   ax = fig.add_subplot(111)

   # Create rectangle x coordinates
   startTime = datetime(year=2020,month=7,day=6,hour=6)
   endTime = startTime + timedelta(seconds = 600)

   # convert to matplotlib date representation
   start = mdates.date2num(startTime)
   end = mdates.date2num(endTime)
   middle = (start+end)/2
   width = end - start

   # assign date locator / formatter to the x-axis to get proper labels
   locator = mdates.AutoDateLocator(minticks=3)
   formatter = mdates.AutoDateFormatter(locator)
   ax.xaxis.set_major_locator(locator)
   ax.xaxis.set_major_formatter(formatter)

   # set the limits
   plt.xlim([start-width, end+width])
   plt.ylim([8000, 10000])

   xlim = ax.get_xlim()
   ylim = ax.get_ylim()

   xspan = xlim[1]-xlim[0]
   yspan = ylim[1]-ylim[0]

   axis_to_data = ax.transAxes + ax.transData.inverted()
   data_to_axis = axis_to_data.inverted()
   trans = data_to_axis.transform

   rect = mpatches.Rectangle((start, 9000), width, 500, color='yellow')

   circle_center = (middle,9250)
   circle_radius_datax = xspan/10
   circle_radius_datay = yspan/10
   circle_radius_ax = trans((xlim[0]+circle_radius_datax,0))[0] # will "by definition" be 0.1 bc datax=xspan/10
   assert round(circle_radius_ax/0.1)==1

   # Plot rectangle
   c1 = mpatches.CirclePolygon(trans(circle_center),radius=circle_radius_ax,resolution=6,color='red',transform=ax.transAxes)
   c2_d = mpatches.CirclePolygon(circle_center,radius=circle_radius_datax,resolution=6,color='green',transform=ax.transData)
   c3_d = mpatches.CirclePolygon(circle_center,radius=circle_radius_datay,resolution=6,color='blue',transform=ax.transData)
   c2_dx = mpatches.CirclePolygon(circle_center,radius=circle_radius_datax,resolution=6,color='green',transform=data_to_axis)
   c3_dx = mpatches.CirclePolygon(circle_center,radius=circle_radius_datay,resolution=6,color='blue',transform=data_to_axis)
   ax.add_patch(rect)
   ax.add_patch(c2_d)
   ax.add_patch(c3_d)
   ax.add_patch(c2_dx)
   ax.add_patch(c3_dx)
   ax.add_patch(c1)
```

**Comment by jklymak** [comment]
What I think you want to do is possible, but Patches are relatively advanced usage particularly if you are going to mix dates in.  You dont say what units the radius should be in. Overall I would suggest you could get help at discourse.matplotlib.org and open a new issue if there is a proposed API change, so I'll close this here.  Thanks for your understanding
