### ISSUE TITLE
Wheel of Matplotlib is not building for Linux system. throwing requirement.parse(numpy>1.11) error

### ISSUE THREAD

**Issue by saurabhawasthi000** [matplotlib/matplotlib#18262]
I am building a wheel for linux distribution but only for Matplotlib it is not going through. I am getting below error eveytime.
I have already provided numpy version greater than 1.11 but still it is not able to find. The numpy package is present in the local directory where it checks for dependent packages. But still only for Matplotlib i am seeing this error. Please help in checking this. Let me know if any other information is required.

 distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy>=1.11')
   OUT
   OUT       Edit setup.cfg to change the build options; suppress output with --quiet.
   OUT
   OUT       BUILDING MATPLOTLIB
   OUT         matplotlib: yes [3.2.2]
   OUT             python: yes [3.7.4 (default, Jun 17 2020, 10:25:02)  [GCC 4.8.5]]
   OUT           platform: yes [linux]
   OUT        sample_data: yes [installing]
   OUT              tests: no  [skipping due to configuration]
   OUT                agg: yes [installing]
   OUT              tkagg: yes [installing; run-time loading from Python Tcl/Tk]
   OUT             macosx: no  [Mac OS-X only]
   OUT
 ERR   Command "python setup.py egg_info" failed with error code 1 in
 ERR   Execution of bin/compile failed (exit value 1)

**Comment by tacaswell** [comment]
This is probably better discussed at https://discourse.matplotlib.org/.  It is very hard to debug the information base on what you have told us, but I suspect that there is something wrong with your Python or numpy installation (either it is not picking it up or the meta-data is missing and distuils is not seeing it).

**Comment by QuLogic** [comment]
Closing as non-actionable.
