### ISSUE TITLE
showing Jalali (in Persian) dates in x-axis of plot ( except just changing locale to 'fa_IR')

### ISSUE THREAD

**Issue by minaee** [matplotlib/matplotlib#18268]
### Problem

I want to plot a `dataframe` that it's index is containing `datetimes`. 
I converted the `Georgian` `datetimes` to [Jalali](https://en.wikipedia.org/wiki/Jalali_calendar) using [jdatetime](https://github.com/slashmili/python-jalali) or [khayyam](https://pypi.org/project/Khayyam/). 

When you use `xaxis.set_major_formatter(mdates.DateFormatter('%d-%b'))`. you ask the matplotlib to show the month names in `x-axis`.

- if you pass Gerorgian datetimes to matplotlib, it will show the name of `i`th month. For example, instead of `1` it prints `Jan` or instead of `3` it prints `Mar`.

- If you just pass Jalali `datetimes`, the matplotlib still convert the number of months to their Georgian names.

- If you pass Jalali `datetimes` and set `locale` to `fa-IR`. Matplotlib show the **Georgian month names** in Persian. i.e, it prints `مارس` which is Persian equivalent of `March`.

I want to show month names in `jalali` and Persian. 
for example: the first month of Jalali calendar is `فروردین`. I want matplotlib to show  `فروردین` instead of `Jan` when the number `1` is passed to it as `%B` or an abbreviated form of month names when the format is defined as `%b`.

### Proposed Solution

1. one way is to accept the output of currently available Georgian to Jalali convertors as I mentioned earlier.

2. another option which comes to my mind is to set a feature which uses other calendars.

### Additional context and prior art

I requested same compatibility from those convertors [here](https://github.com/slashmili/python-jalali/issues/68#issuecomment-674348266) 
(In addition, any help on how can I do it with currently available features is strongly appreciated because I have asked it on [SO](https://stackoverflow.com/questions/63356748/is-there-a-way-to-show-persian-date-in-x-axis-of-matplotlib-plot) and other platforms, but I couldn't manage to find a way.)

**Comment by jklymak** [comment]
I think your best approach would be to write a locator and formatter (and unit converter) that specifically work with jdatetime using the converters for datetime in dates.py as a guide.  Depending on jdatetimes compatibility with datetime that may be simple wrappers around the existing locators and formatters. I'm not sure though that we would want this in the core library.

**Comment by minaee** [comment]
> I think your best approach would be to write a locator and formatter (and unit converter) that specifically work with jdatetime using the converters for datetime in dates.py as a guide. Depending on jdatetimes compatibility with datetime that may be simple wrappers around the existing locators and formatters. I'm not sure though that we would want this in the core library.

Can you give me a clue on how to start writing a locator and formatted?

**Comment by jklymak** [comment]
Suggest working backwards from the `DateConverter`, and use `jdatetime` as the type to trigger registering the `JDateconverter` and `JDateformatter`.  https://github.com/matplotlib/matplotlib/blob/792756c60975520e9993379a14711c08459ad11c/lib/matplotlib/dates.py#L1874

I'm going to close this as won't fix on our end, but if you still have questions, suggest discourse.matplotlib.org - I or someone else will be happy to help.  I think its fair to say this is niche enough that we won't extend core support to Jalai dates - but we encourage you to make your own package, or work with the `jdatetime` folks to make a matplotlib add-on to their package.
