### ISSUE TITLE
Add CI Intervall to boxplot notch documentation

### ISSUE THREAD

**Issue by mame98** [matplotlib/matplotlib#18272]
### Problem

The boxplot Method allows to show the confidence interval around the median by using the notch parameter. However there is no documentation on which ci is used, I assume it is the 95% CI or did I miss something?

### Suggested Improvement

At least document which confidence interval is used. Maybe one could consider adding a Parameter to specify A confidence interval?

**Comment by jklymak** [comment]
Its set by `conf_intervals` isn't it?

**Comment by mame98** [comment]
Yeah, i dont know how I missed that 🤦 

However I still think there should be a clarification what the default CI is?

**Comment by jklymak** [comment]
Maybe?  And the notch description should refer to conf_interval also as well?

**Comment by QuLogic** [comment]
The default is determined by *bootstrap*, which is mentioned in the *notch* docstring.
