### ISSUE TITLE
Module for drawing... "different" sankey diagrams

### ISSUE THREAD

**Issue by toobaz** [matplotlib/matplotlib#18281]
### Problem

When I wanted to draw a sankey diagram in matplotlib, I discovered that the interface offered by ``matplotlib.sankey`` was on one hand extremely powerful, but on the other hand much more complicated than other solutions on the market. Specifically, it required me to think about positions in space, while I really only wanted to think about data, and to obtain the standard, horizontally-oriented diagrams that you mostly get if you search for "sankey" on google.

### Proposed Solution

... so I wrote a small module to do what I had in mind, and you can find it here:

https://github.com/toobaz/mpl_sankey

... with examples here:

https://github.com/toobaz/mpl_sankey/blob/master/notebooks/Examples.ipynb

Now, I would be happy to donate my code to matplotlib. I do see two possible obstacles:
 - my code depends on numpy _and_ pandas (although the user _can_ pass simple lists of lists)
 - maplotlib already has a (completely different) ``sankey`` module

If these are insurmountable, then my code can still live as a standalone project ;-)

Notice that my code _could_ be generalized a bit by allowing users to specify positions in space, but I don't think it will ever be able to cover all use cases of the current ``matplolitb.sankey`` (specifically: different blocks of labels in a same transition, possibly with different orientations).

**Comment by jklymak** [comment]
We won't take a pandas dependency and as you say we already have a sankey implementation.  I suppose if you had suggestions for how to simplify the existing API or had a light wrapper around it that might be considered. Otherwise we'd be happy, I'm sure, to link your third party package.

**Comment by toobaz** [comment]
> We won't take a pandas dependency

Clearly I assumed pandas would be an optional dependency, but I perfectly understand your choice, as the functionality introduced would be useless without.

> I suppose if you had suggestions for how to simplify the existing API or had a light wrapper around it that might be considered

I'm afraid there's not much to simplify, because the aim is really different. For instance the graphs my implementation produces have "blocks" that connect flows, the ``matplotlib.sankey`` doesn't and, on the opposite, has all flows end with an arrow, which wouldn't even blend well inside a block (yes, you can put ``head_angle=180``, but the heads will still not be aligned). My code draws flows as cubic Bézier curves (and couldn't do otherwise, as they must start and end horizontally), ``matplotlib.sankey`` uses (I think) quadratic polynomials...

There's a possibility that my implementation could be rewritten to only use ``numpy`` without too much pain... but still _some_ pain (mainly for some ``groupby`` operations): should there ever be interest, I'll be happy to try.

**Comment by story645** [comment]
> Specifically, it required me to think about positions in space, while I really only wanted to think about data, and to obtain the standard, horizontally-oriented diagrams that you mostly get if you search for "sankey" on google.

As much as I know we should have fewer plots on axes/pyplot, I think that's the currently existing best place for this new plotting method you've essentially created. Either that or maybe as a `sankey.plot/sankey.chart/sankey.diagram`?

**Comment by timhoffm** [comment]
IMHO this should start as a third-party library. That way it stays more flexible. If it has proven stable and useful we can always consider to integrate it in core Matplotlib later.

There is the option to add this under the matplotlib github project as `matplotlib/mpl_sankey`. However, we need to clarify maintenance. @toobaz would you be interested and willing to maintain and develop the project further?

**Comment by toobaz** [comment]
Keeping this third-party under the matplotlib github project seems like a good idea.

Concerning maintainership, the developments I have in mind are few (basically just (i) adding flow-specific labels (ii) allowing flows to skip some blocks (iii) allowing the user to specify node position (iv) allowing for different data input formats) but I certainly mean to both evaluate PRs and fix bugs.

**Comment by timhoffm** [comment]
Ping @tacaswell: How's the process for adding a third-party package to the Matplotlib GitHub project?

**Comment by sandrotosi** [comment]
I was pointed to this report after i opened #19351 , and this is exactly what i'm looking for, so i'm gonna add my comments here and i would definitely welcome its inclusion in mpl.

@toobaz this kind of diagrams are called [alluvial diagrams](https://en.wikipedia.org/wiki/Alluvial_diagram) so one possible path forward for inclusion in matplotlib would be to rename to that, so that it wont shadow [`matplotlib.sankey()`](https://matplotlib.org/3.3.3/api/sankey_api.html) (unless you have a plan to merge this as a sub-feature of that API, but they seem rather different that they deserve 2 separate APIs)

one feature i'd like to see is the count of each stage in each column; this would meant, in your example ![i](https://raw.githubusercontent.com/toobaz/mpl_sankey/master/notebooks/featured.png) the number 5.5 next to `a` in column `first`, 5 next to `1` in column `Then`, etc

**Comment by toobaz** [comment]
> this kind of diagrams are called [alluvial diagrams](https://en.wikipedia.org/wiki/Alluvial_diagram)

I thank you for the clarification (I had no idea), but the kind of diagrams my module produces are really what people mostly refer to when mentioning sankey diagrams... maybe it's [plotly's fault](https://plotly.com/python/sankey-diagram/) or [google's](https://developers.google.com/chart/interactive/docs/gallery/sankey)?

That is to say: I'm happy to use the more correct name, but I'd like to make sure (e.g. in the docs to the ``sankey`` submodule) that people looking for "sankey" related to matplotlib do find it.

> one feature i'd like to see is the count of each stage in each column

Yep, that definitely makes sense, I'm just unsure about the optimal API. Care to comment in https://github.com/toobaz/mpl_sankey/pull/1 ?

**Comment by sandrotosi** [comment]
> > this kind of diagrams are called [alluvial diagrams](https://en.wikipedia.org/wiki/Alluvial_diagram)
> 
> I thank you for the clarification (I had no idea), but the kind of diagrams my module produces are really what people mostly refer to when mentioning sankey diagrams... maybe it's [plotly's fault](https://plotly.com/python/sankey-diagram/) or [google's](https://developers.google.com/chart/interactive/docs/gallery/sankey)?

from what i can see from wikipedia, it looks like [alluvial diagrams](https://en.wikipedia.org/wiki/Alluvial_diagram) are _a type of Sankey diagram that uses the same kind of representation to depict how items re-group_; so it looks like it's a specialization of the more general [Sankey diagrams](https://en.wikipedia.org/wiki/Sankey_diagram) which they define as _a type of flow diagram in which the width of the arrows is proportional to the flow rate_

> That is to say: I'm happy to use the more correct name, but I'd like to make sure (e.g. in the docs to the `sankey` submodule) that people looking for "sankey" related to matplotlib do find it.

this is interesting: i knew i saw this type of diagrams, so i started googling around for image of "flow diagrams" (or something like that), until i found that all the references were pointing to alluvial diagrams, and **not** Sankey diagrams. I may also have ignored the sankey diagrams because the example on the mpl doc website did not show the type of diagrams i was looking for.

> > one feature i'd like to see is the count of each stage in each column
> 
> Yep, that definitely makes sense, I'm just unsure about the optimal API. Care to comment in [toobaz/mpl_sankey#1](https://github.com/toobaz/mpl_sankey/pull/1) ?

thanks, will do!

**Comment by oscargus** [comment]
It seems like the discussion about maintaining this under the matplotlib organization got stalled. On the other hand, it seems like @toobaz has made progress maintaining this. 

However, it seems like it is not in the third party tools: https://matplotlib.org/mpl-third-party/

@toobaz if you want to add it there it will get better visibility and maybe we can close this for now? https://github.com/matplotlib/mpl-third-party

**Comment by toobaz** [comment]
> @toobaz if you want to add it there it will get better visibility and maybe we can close this for now? https://github.com/matplotlib/mpl-third-party

Sure, I'm still open to any solution for integration with Matplotlib - even just with that list. Should I do anything?

**Comment by oscargus** [comment]
You can open a PR in that repo with the info about mpl_sankey and it will end up in the list (when merged, which is pretty quick usually).

**Comment by toobaz** [comment]
> You can open a PR in that repo with the info about mpl_sankey and it will end up in the list (when merged, which is pretty quick usually).

Done: https://github.com/matplotlib/mpl-third-party/pull/159

I guess this can be closed.
