### ISSUE TITLE
could we reset label for the z-axis?

### ISSUE THREAD

**Issue by yangxuyu** [matplotlib/matplotlib#18285]
### Problem
we could set the label for the x-axis and y-axis,so  why not could reset  label for the z-axis. 

### Proposed Solution
I believe this feature just need a few minutes to slove.pleace think about it. 

### Additional context and prior art
Thank you sincerely

**Comment by jklymak** [comment]
Not really clear what you are asking for.  There is a set_zlabel method on the axes - is that not adequate?
