### ISSUE TITLE
Floating point image RGB values must be in the 0..1 range

### ISSUE THREAD

**Issue by freekklein** [matplotlib/matplotlib#18280]
### Bug report

**Bug summary**
Image cannot be saved after the image is resized with open-cv. In older version of matplotlib (3.1.3) below code works.
matplotlib==3.3.1
opencv-contrib-python  3.4.2.16

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import cv2

img = plt.imread('image.png')
res_1 = cv2.resize(img, dsize=(200, 200), interpolation=cv2.INTER_CUBIC)  
plt.imsave('test_1.png', res_1)  # does not work

res_2 = cv2.resize(img, dsize=(200, 200))
plt.imsave('test_2.png', res_2)  # does work
```

**Actual outcome**
```
~\Anaconda\envs\image-classification\lib\site-packages\matplotlib\image.py in imsave(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)
   1565             rgba = arr
   1566         else:
-> 1567             rgba = sm.to_rgba(arr, bytes=True)
   1568         if pil_kwargs is None:
   1569             pil_kwargs = {}

~\Anaconda\envs\image-classification\lib\site-packages\matplotlib\cm.py in to_rgba(self, x, alpha, bytes, norm)
    312                 if xx.dtype.kind == 'f':
    313                     if norm and (xx.max() > 1 or xx.min() < 0):
--> 314                         raise ValueError("Floating point image RGB values "
    315                                          "must be in the 0..1 range.")
    316                     if bytes:

ValueError: Floating point image RGB values must be in the 0..1 range.
```

**Expected outcome**
In matplotlib==3.1.3 above python code works. 

**Matplotlib version**: 3.3.1
  * Operating system: Microsoft
  * Matplotlib version: 3.3.1
  * Matplotlib backend: //ipykernel.pylab.backend_inline
  * Python version: 3.7.6
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: opencv-contrib-python==3.4.2.16

pip: 20.2.2
conda: 4.8.2

**Comment by timhoffm** [comment]
Cubic interpolation can overshoot and thus generate values outside of the range of values of the original image.

I guess the current behavior is correct and we were doing some bogus clipping or scaling before. - To be checked.

If your image has values outside the 0..1 range, you should scale or clip yourself before passing that to imsave.

**Comment by QuLogic** [comment]
Since they're cast to uint8, overflows would wrap around:

```python
In [2]: x = np.array([0, 1, 1.3, 5, -0.4])                                                                                                            

In [3]: (x * 255)                                                                                                                                     
Out[3]: array([   0. ,  255. ,  331.5, 1275. , -102. ])

In [4]: (x * 255).astype(np.uint8)                                                                                                                    
Out[4]: array([  0, 255,  75, 251, 154], dtype=uint8)
```

This is pretty likely not what you want, so you really need to clip the input before hand.
