### ISSUE TITLE
Automatic title placement wrong if parent axes is off the page

### ISSUE THREAD

**Issue by jnboehm** [matplotlib/matplotlib#18283]
### Bug report

**Bug summary**
When calculating the extent of a subplot axes, its contents depend on whether  title has been set in the axes below, i. e. the unrelated title bleeds into the extent and gets exported when saving while specifying the `bbox_inches`.

The extent itself doesn't seem to be the problem, but the inclusion of artefacts that should not be included in the plot, and aren't visible in the full figure (in the bounding box) are included and saved when giving an explicit bounding box to `fig.savefig`. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, axs = plt.subplots(2, 1)
axs[0].plot([1,2], [3,4])
extent = axs[0].get_window_extent().transformed(fig.dpi_scale_trans.inverted())
fig.savefig('/tmp/expected.png', bbox_inches=extent)
axs[1].set_title('pls ignore me')
# extents are actually unchanged
extent2 = axs[0].get_window_extent().transformed(fig.dpi_scale_trans.inverted())
fig.savefig('/tmp/actual.png', bbox_inches=extent2)
fig.savefig('/tmp/full.png')
```

**Actual outcome**
The title of `axs[1]` is shown.

![actual](https://user-images.githubusercontent.com/12418563/90521441-cd937f00-e16a-11ea-8dfa-4d7d70f854b5.png)

**Expected outcome**
 It should not be included, as visible in the full picture.

![expected](https://user-images.githubusercontent.com/12418563/90521447-cff5d900-e16a-11ea-974f-ca05a134f48b.png)
![full](https://user-images.githubusercontent.com/12418563/90521459-d421f680-e16a-11ea-84b8-725a7526eef1.png)

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.2

Environment has been installed with the default conda channel.

**Comment by jklymak** [comment]
I can take a look at this.  OTOH. An you make sure you've got the right code for the pictures. The code doesn't have a plot command but the images do. Further I don't understand why the axis labels etc are being trimmed.

**Comment by jnboehm** [comment]
Thanks for the reply.  I forgot to paste the `plot` commans, I edited the snippet above accordingly.

As per https://github.com/matplotlib/matplotlib/pull/12716, the behavior of the labels being trimmed is expected (and what I wanted).  Using `ax.get_tightbbox(renderer)` results in a similar issue as can be seen in the example, where the title should not be shown either (due to `constrained_layout=True`):

```python
fig, axs = plt.subplots(2, 1, constrained_layout=True)
axs[0].plot([1,2], [3,4])                                              
axs[1].set_title('pls ignore me')                                      
Text(0.5, 1.0, 'pls ignore me')
bbox = axs[0].get_tightbbox(fig.canvas.get_renderer()).transformed(fig.dpi_scale_trans.inverted())                                            
fig.savefig('/tmp/actual_bbox.png', bbox_inches=bbox)                  
fig.savefig('/tmp/full.png', bbox_inches=bbox)                         
```

with the actual out come looking like 
![actual_bbox](https://user-images.githubusercontent.com/12418563/90525694-d20e6680-e16f-11ea-835f-19b3f6248759.png)

whereas the full figure shows that the title should not be shown:
![full](https://user-images.githubusercontent.com/12418563/90525684-cd49b280-e16f-11ea-94f0-89e5769dd131.png)

**Comment by jklymak** [comment]
Sorry how does constrained_layout come into this?  Did you use constrained_layout in the original?

**Comment by jnboehm** [comment]
My bad, I thought it made a difference for `get_tightbbox` but it doesn't seem to.  Without it, I get the following code
```python
fig, axs = plt.subplots(2, 1)
axs[0].plot([1,2], [3,4])
axs[1].set_title('pls ignore me')
bbox = axs[0].get_tightbbox(fig.canvas.get_renderer()).transformed(fig.dpi_scale_trans.inverted())
fig.savefig('/tmp/actual_bbox.png', bbox_inches=bbox)
fig.savefig('/tmp/full.png')
```

With slightly different placements of the axis text, with the cropped figure showing
![actual_bbox](https://user-images.githubusercontent.com/12418563/90527112-77760a00-e171-11ea-8e3d-4d75f1876328.png)

whereas the full figure shows that the title is placed elsewhere:
![full](https://user-images.githubusercontent.com/12418563/90527200-8fe62480-e171-11ea-87dd-85d42ec666a5.png)

In any case, the issue I have relates more directly to `get_window_extent()`, where the title should not be in the cropped output at all.  Sorry for the confusion.

**Comment by jklymak** [comment]
Thanks, so the issue is not with `get_window_extents` its with the automatic title repositioning.  We reposition the title to avoid all decorators on the axis, but we start at y=0.  Since you cut the whole axes out, the title gets left at 0.  

1. To fix your immediate issue, you can place the title manually by specifying its position in axes co-ordinates: `set_title('boo', y=1)`
2. I'll add a check to the title placement algorithm for the axes being off the page which seems to fix this.

**Comment by jnboehm** [comment]
For the example above, specifying `axs[1].set_title('bla', y=1)` does not change the outcome of the script.  I've worked around this for now by just not specifying the title before using it (if someone else stumbles upon this).

Thanks for looking into it!

**Comment by jklymak** [comment]
OK, maybe you need a slightly more recent Matplotlib.  `y=1.000001` should work with 3.2.1?

**Comment by jnboehm** [comment]
That also did not help with 3.2.1.  I have updated to 3.3.1 now and there it works with either of the values.  Thank you.
