### ISSUE TITLE
How to modify ticklabels in axisartist?

### ISSUE THREAD

**Issue by gc13141112** [matplotlib/matplotlib#18295]
![image](https://user-images.githubusercontent.com/20677298/90609601-e701fd00-e236-11ea-8dd9-5912b9367043.png)
Unlike the ticklabels of the mainline matplotlib, I don't along change the ticklabels in [artist](https://matplotlib.org/3.1.3/_modules/mpl_toolkits/axisartist/axis_artist.html)?  Has anyone seen this kind of problem before?

**Comment by anntzer** [comment]
No, I think this is a valid request.
