### ISSUE TITLE
Canvas redraws during any motion when Button is present

### ISSUE THREAD

**Issue by yoda-vid** [matplotlib/matplotlib#18303]
### Bug report

**Bug summary**

I encountered a performance regression starting in Matplotlib v3.3.0 when using a figure with a button widget. Any mouse motion appears to trigger canvas draw events. The issue bisected to commit f6b88917ac2a1c2fdfe25c144d1b81bd7003b3d1 and is not present in v3.2.2.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from matplotlib.widgets import Button

if __name__ == "__main__":
    def on_draw(evt):
        global redraw_count
        redraw_count += 1
        btn.label.set_text(btn_txt.format(redraw_count))
    
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    redraw_count = 0
    btn_txt = "Redraws: {}"
    btn = Button(ax, btn_txt.format(redraw_count))
    fig.canvas.mpl_connect("draw_event", on_draw)
    plt.show()

```

**Actual outcome**

Motion anywhere in the figure increments the number of redraw events. The issue appears to result from the comparison between the Button's stored color value and the Axes's returned facecolor (see [here](https://github.com/matplotlib/matplotlib/blob/v3.3.1/lib/matplotlib/widgets.py#L214)). The default Button color is given and stored as a string of a float, while the Axes `get_facecolor` returns a tuple in RGBA format.

**Expected outcome**

Redraws are only triggered when moving into or out of the button to show the hover color change. A workaround is to give the `color` and `hovercolor` parameters to `Button` as RGBA values, such as:

```
btn = Button(ax, "Label", color=(0.2, 0.3, 0.4, 1.0), hovercolor=(0.3, 0.4, 0.5, 1.0))
```

A fix would be to convert the found color value in the `Button._motion` function to RGBA when comparing with the current facecolor, such as this change in the `Button` class (after adding an import to `colors`):

```
    def _motion(self, event):
        if self.ignore(event):
            return
        c = self.hovercolor if event.inaxes == self.ax else self.color
        # changed c to colors.to_rgba(c)
        if colors.to_rgba(c) != self.ax.get_facecolor():
            self.ax.set_facecolor(c)
            if self.drawon:
                self.ax.figure.canvas.draw()
```

If this seems reasonable, I can submit a PR.

**Matplotlib version**

  * Operating system: macOS 10.15.5
  * Matplotlib version: 3.3.1 (tested on latest commit, ce6ac2d174e396abab9e17577f3721f33bd7d41f)
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.6
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

**Comment by anntzer** [comment]
Probably you can convert *both* values to RGBA (in theory the axes facecolor could also be in whatever format), but other than that the fix looks good, go for it.

**Comment by yoda-vid** [comment]
Thanks, I'll convert both values to RGBA for the color comparison.

I also realized that the TextBox has this same issue, as seen with this similar example:

```
from matplotlib import pyplot as plt
from matplotlib.widgets import TextBox

if __name__ == "__main__":
    def on_draw(evt):
        global redraw_count
        redraw_count += 1
        text_box.label.set_text(box_txt.format(redraw_count))
    
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    redraw_count = 0
    box_txt = "Redraws: {}"
    text_box = TextBox(ax, box_txt.format(redraw_count))
    fig.canvas.mpl_connect("draw_event", on_draw)
    plt.show()
```

The same fix applies in my testing, and I'll submit the PR.

**Comment by QuLogic** [comment]
Fixed by the above PR.
