### ISSUE TITLE
"How to use Matplotlib in a web application server" should be made an example

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#18301]
### Problem

https://matplotlib.org/devdocs/faq/howto_faq.html#how-to-use-matplotlib-in-a-web-application-server 

should be moved to examples. Possibly category [Embedding Matplotlib in a graphical user interface](https://matplotlib.org/devdocs/gallery/index.html#embedding-matplotlib-in-graphical-user-interfaces) or [Miscellaneous](https://matplotlib.org/devdocs/gallery/index.html#miscellaneous).

**Comment by story645** [comment]
I think while embedding isn't the most accurate, it's a really natural place for the example to live in terms of folks finding it.

**Comment by Patil2099** [comment]
Hi @timhoffm, I would love to help you in fixing this issue, Can I get some instruction on how to do it because I am new here!

**Comment by timhoffm** [comment]
General info: [Matplotlib documentation guide](https://matplotlib.org/devel/documenting_mpl.html).

Specific actions to do here:

- Remove the indicated section from `doc/faq/howto_faq.rst`
- Create a new example file `examples/user_interfaces/web_application_sever_sgskip.py` with the respective content.

These example `.py` files are converted to documentation via [sphinx gallery](https://sphinx-gallery.github.io/stable/index.html). (The `_sgskip` suffix tells sphinx gallery not to execute the example - we don't want to run it because we don't have the necessary dependencies and it does not create a displayable figure.

**Comment by matttatum97** [comment]
Hey @timhoffm, is this issue still open, and could I also take a shot at it? I'm also new to open source and this seems like a good first issue for me to try. I think I can do it based on your previous instructions. Thanks!

**Comment by timhoffm** [comment]
@matttatum97 thanks for your interest. Let's give @Patil2099 time to respond:

@Patil2099 are you still interested in working on this? If we're not hearing from you within 2 days, I'll assume you've withdrawn from the work and @matttatum97 will take over.

**Comment by Patil2099** [comment]
Sorry for the late reply @timhoffm. I will start working on it.  Sorry @matttatum97

**Comment by anishkabhatia** [comment]
Is it still open for contribution? @timhoffm

**Comment by timhoffm** [comment]
@anishkabhatia Sorry, this is already addressed in #18767.
