### ISSUE TITLE
Type42 font embedding broken for fonts without glyph names

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18307]
### Bug report

**Bug summary**

Setting `pdf.fonttype` or `ps.fonttype` to 42 and using a font with no glyph names (i.e. for which FT_HAS_GLYPH_NAMES returns 0) results in non-displayed text.

**Code for reproduction**

Arial is a prominent font with no glyph names (so it's not a completely obscure edge case...).

```python
from pathlib import Path
rcParams.update({"pdf.fonttype": 42, "ps.fonttype": 42}
figtext(.5, .5, "ab", font="arial")
savefig("/tmp/test.pdf")
savefig("/tmp/test.ps")
```

**Actual outcome**

Files are displayed as empty.

**Expected outcome**

Text is shown.

---

Again https://github.com/matplotlib/matplotlib/pull/18143 may be relevant here: perhaps fontTools can generate the glyph names table if needed?

**Matplotlib version**

  * Operating system: fedora
  * Matplotlib version: master
  * Python version: 38

**Comment by QuLogic** [comment]
I can't reproduce this on Windows, at least for PDF output on `main`. The Arial font there appears to have flags of `FT_FACE_FLAG_SCALABLE  | FT_FACE_FLAG_SFNT | FT_FACE_FLAG_HORIZONTAL | FT_FACE_FLAG_KERNING | FT_FACE_FLAG_EXTERNAL_STREAM | FT_FACE_FLAG_HINTER`.

**Comment by anntzer** [comment]
Indeed, this seems to have been fixed in the meantime (likely due to the switch to fonttools).
