### ISSUE TITLE
Add easily comparable version info to toplevel

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18312]
### Problem

Currently matplotlib only exposes `__version__`.  For quick version checks, exposing either a `version_info` tuple (which can be compared with other tuples) or a `LooseVersion` instance (which can be properly compared with other strings) would be a small usability improvement.

(In practice I guess boring string comparisons will work just fine until we hit mpl 3.10 or 4.10 which is unlikely to happen soon, but that feels quite dirty :))

### Proposed Solution

I guess I slightly prefer `LooseVersion`, but exposing just a `version_info` tuple is much more common in other packages (and perhaps simpler to understand).  The hardest(?) part is probably just bikeshedding this point :-)

### Additional context and prior art

`version_info` is a pretty common thing (citation needed).

**Comment by timhoffm** [comment]
It seems that `__version_info__` is the way to go.

### Prior art
- There's no official specification for version tuples. [PEP 396 - Module Version Numbers](https://www.python.org/dev/peps/pep-0396/) only defines the string `__version__`.

- Many projects don't bother with version tuples.

- When they do, `__version_info__` seems to be a common thing:
  - [Stackoverflow discussion](https://stackoverflow.com/a/466694)
  - [PySide2](https://doc.qt.io/qtforpython-5.12/pysideversion.html#printing-project-and-qt-version) uses it.

- Python itself has the string [sys.version](https://docs.python.org/3/library/sys.html#sys.version) and the (named)tuple [sys.version_info](https://docs.python.org/3/library/sys.html#sys.version_info). In analogy to that `__version_info__` next to `__version__` makes sense for packages.
