### ISSUE TITLE
set_pickradius not working similar to deprecated set_picker

### ISSUE THREAD

**Issue by NHades** [matplotlib/matplotlib#18358]
### Bug report

Replacing the deprecated set_picker with set_pickradius does not produce same effect of selecting items from within legend.  Code below is from matplotlib website examples shows the issue by using set_pickradius.  With set_picker the lines could be selected and hidden.  With set_pickradius nothing occurs.  Actually, there is no connection to trigger function anymore. 

**Code for reproduction**

```python
# code from: https://matplotlib.org/3.1.1/gallery/event_handling/legend_picking.html
import numpy as np
import matplotlib.pyplot as plt

t = np.arange(0.0, 0.2, 0.1)
y1 = 2 * np.sin(2 * np.pi * t)
y2 = 4 * np.sin(2 * np.pi * 2 * t)

fig, ax = plt.subplots()
ax.set_title('Click on legend line to toggle line on/off')
line1, = ax.plot(t, y1, lw=2, label='1 HZ')
line2, = ax.plot(t, y2, lw=2, label='2 HZ')
leg = ax.legend(loc='upper left', fancybox=True, shadow=True)
leg.get_frame().set_alpha(0.4)

# we will set up a dict mapping legend line to orig line, and enable
# picking on the legend line
lines = [line1, line2]
lined = dict()
for legline, origline in zip(leg.get_lines(), lines):
    legline.set_pickradius(5)  # 5 pts tolerance
    lined[legline] = origline

def onpick(event):
    print('Legened Picked')
    # on the pick event, find the orig line corresponding to the
    # legend proxy line, and toggle the visibility
    legline = event.artist
    origline = lined[legline]
    vis = not origline.get_visible()
    origline.set_visible(vis)
    # Change the alpha on the line in the legend so we can see what lines
    # have been toggled
    if vis:
        legline.set_alpha(1.0)
    else:
        legline.set_alpha(0.2)
    fig.canvas.draw()

fig.canvas.mpl_connect('pick_event', onpick)
plt.show()
```

**Expected outcome**
clicking on legend items hides lines. 

**Matplotlib version**

  * Operating system: Operating system: Win 10
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):matplotlib.backends.backend_qt5agg
  * Python version:3.7.9
  * Jupyter version (if applicable):
  * Other libraries: 

 pip

**Comment by QuLogic** [comment]
`Axes.set_picker` is not deprecated. `Axes.set_picker(5)` to mean enable-and-set-radius is deprecated. You still need to enable picking, and then modify radius if desired:
```python
for legline, origline in zip(leg.get_lines(), lines):
    legline.set_picker(True)  # Enable picking on the legend line.
    legline.set_pickradius(5)  # 5 pts tolerance
    lined[legline] = origline
```

**Comment by NHades** [comment]
Thanks @QuLogic!

It was not clear from deprecating message that set_picker is still needed. 
Also, code in example @ https://matplotlib.org/3.1.1/gallery/event_handling/legend_picking.html  should be updated to new version.

**Comment by QuLogic** [comment]
That example is for 3.1.1; the current version is correct: https://matplotlib.org/3.3.1/gallery/event_handling/legend_picking.html
