### ISSUE TITLE
ha="right" breaks AnchoredText placement.

### ISSUE THREAD

**Issue by janosh** [matplotlib/matplotlib#18363]
### Bug report

**Bug summary**

Setting `ha="right"` through the `prop` kwarg breaks `AnchoredText` placement.

**Code for reproduction**

```py
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnchoredText

prop = {"ha": "right", "bbox": {"lw": 0.5, "facecolor": "white"}}
text_box = AnchoredText("test\ntest long text for ha", prop=prop, loc="upper right", pad=0.2)
plt.gca().add_artist(text_box)
```

**Actual outcome**

![bug](https://user-images.githubusercontent.com/30958850/91442341-fe15a000-e871-11ea-946c-5ba00e9c1daf.png)

**Expected outcome**

I was expecting the text box to end up in the same place it does when not setting `ha="right"`:

![normal](https://user-images.githubusercontent.com/30958850/91442600-62d0fa80-e872-11ea-8f92-d41fd17fff42.png)

**Matplotlib version**
  * Operating system: macOS 10.15.6
  * Matplotlib version: 3.2.1 (pip-installed)
  * Matplotlib backend: `module://ipykernel.pylab.backend_inline`
  * Python version: 3.6.10

**Comment by QuLogic** [comment]
You should have seen a warning that said using the `*alignment` options is not supported with `AnchoredText`. In 3.3, it's a hard error.

**Comment by QuLogic** [comment]
At least horizontal alignment seems pretty straightforward to add support for.
