### ISSUE TITLE
Plotting Scores over the Years - Error

### ISSUE THREAD

**Issue by FluorescentNight** [matplotlib/matplotlib#18373]
Hi, 

Could anyone please help me out with this I'm not sure why I have this error and have tried researching fixes but have not found any.

**TypeError:** the dtypes of parameters x (object) and width (float64) are incompatible

Here is my code: 

`xx = {1915, 1921, 1994, 2008, 2010, 2018}
yy = {6.7, 8.3, 8.9, 9.0, 8.8, 7.8}

plt.bar(xx, yy)
plt.xlabel('Years')
plt.ylabel('Scores')
plt.title('Scores over the Years')
plt.show()`

**Comment by WeatherGod** [comment]
It is because `xx` is a set, not a list.
