### ISSUE TITLE
The various set_3d_properties() methods are undocumented.

### ISSUE THREAD

**Issue by QuocAnhVu** [matplotlib/matplotlib#18387]
### Problem

I found the method used in this example here: https://matplotlib.org/gallery/animation/simple_3danim.html
And see various references throughout the API here: https://matplotlib.org/mpl_toolkits/mplot3d/api.html

But the example is opaque and the API documentation is blank.

### Suggested Improvement

There should be a blurb explaining the purpose of the method and the semantic meaning of its arguments. There should be an example of a manipulation using the method.

**Comment by oscargus** [comment]
Updating the link to documentation: https://matplotlib.org/stable/api/toolkits/mplot3d.html

**Comment by timhoffm** [comment]
In #19572 I proposed to make these methods private.

**Comment by oscargus** [comment]
Most (all?) of these are now documented.
