### ISSUE TITLE
Allow using None as linestyle

### ISSUE THREAD

**Issue by danijoo** [matplotlib/matplotlib#18382]
### Problem
I think its quite frustrating that the `linestyle` and `marker` parameter have different behaviour when passing `None` to them: For markers, `None` means no/invisible markers. For linestyle, `None` means default linestyle. Wouldn't it make sense if passing `None` as linestyle parameter would result in no visible line similar to the behaviour of marker style? 

### Proposed Solution
I propose to change the default behaviour of the linestyle so that `None` also means "nothing" for linestyle. I.e:

```python
  def set_linestyle(self, ls):
        if ls is None:
            ls = "None"
        ... #(current implementation follows)
```

**Comment by QuLogic** [comment]
Passing `None` means the default in both cases; the default line is visible and the default marker is not.

**Comment by danijoo** [comment]
fair enough. If you think of it this way, it actually makes sense!

**Comment by QuLogic** [comment]
Also note, you can pass `'None'` (as a _string_) to both to turn them off, which though a bit confusingly named, seems consistent.
