### ISSUE TITLE
Bug: bad transform on axis after call to plot() (incl. workaround)

### ISSUE THREAD

**Issue by shenberg** [matplotlib/matplotlib#18383]
### Bug report

**Bug summary**

Drawing patches using an Axis's transform on the figure containing the axis produces bad results directly after a call to `ax.plot()`.

The Axis's `transformData` is stale directly after `plot()` call and accessing a property such as `ax.viewLim` updates the `transformData`.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
ax.plot(np.linspace(1, 2, 5))

# NOTE: Comment-in the line below to work around the issue
#ax.viewLim

# try to draw a rectangle on the figure directly
d = ax.transData.transform([2, 1.5])
inverse_fig_transform = fig.transFigure.inverted()

rect = matplotlib.patches.Rectangle(inverse_fig_transform.transform(d), 0.1, 0.1, transform=fig.transFigure)
fig.add_artist(rect)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/653972/91754695-84afe180-ebd2-11ea-9f72-53aa402e939a.png)

**Expected outcome**

To obtain the expected result, simply comment in the statement `ax.viewLim` in the above snippet (look for `# NOTE`) and re-run it.

![image](https://user-images.githubusercontent.com/653972/91754801-b3c65300-ebd2-11ea-878e-5966c684605c.png)

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.1 (found on 3.2.1)
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.9
  * Jupyter version (if applicable): core: 4.6.3 notebook: 6.0.3 ipykernel: 5.3.0
  * Other libraries: numpy==1.19.0

I installed using pip3 install --user.

**Comment by jklymak** [comment]
Can you give more context about what you are trying to do here?  It seems you should just use ax.transData to make the rectangle.  Why do you want to use transFigure?

**Comment by shenberg** [comment]
Sure. In reality, I'm drawing lines between data points in two different subplots. I cut it down to this example to show the issue.

**Comment by QuLogic** [comment]
You will want to use [`ConnectionPatch`](https://matplotlib.org/api/_as_gen/matplotlib.patches.ConnectionPatch.html) for that.

**Comment by shenberg** [comment]
@QuLogic Thanks! That's a much more elegant solution. I think what I did should work but it definitely felt iffy, like it's not the matplotlib way. This is a proper solution.

**Comment by QuLogic** [comment]
With regards to the original issue, it's generally working as expected, if under-documented. The Axes limits are lazily-evaluated, and thus so is the transform. This is quite fine if you attach the transform to something as it will go stale with everything else. However, if you do a manual transform (as done to find the point `d`), then you need to ensure that everything is evaluated first.

In order to do that, you need to call something that gets the limits, such as `ax.viewLim` or `ax.get_xlim()` or force a draw, `fig.canvas.draw()`.
