### ISSUE TITLE
How to get Quadmesh coordinates

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#18399]
### Describe the issue

**Summary**

Right now, the coordinates of a Quadmesh, returned from pcolormesh, are not available to the end-user. They are stored internally in the `coordinates` attribute. This is an issue for Cartopy, when we need to know where the MPL calculated coordinates are located to know whether we should mask some cells for users.

### Proposed fix

Add a `.get_coordinates()` method that returns the private attribute to Quadmesh. This would be minimally invasive, and only ensures that Cartopy isn't relying on a private attribute.

Related to #18317, and my proposed fix in https://github.com/SciTools/cartopy/pull/1646 that relies on the private attribute.

**Comment by dopplershift** [comment]
Should this instead be `get_xydata()` to mirror the API name on `Line2D`?

**Comment by greglucas** [comment]
That would be fine with me. I only went with coordinates because that is what it is called internally :)

The other question is what we should return `_coordinates` is internally stored as shape (nx+1, ny+1, 2). That would be my preference, but there are a lot of legacy raveled data too so I could see [(nx+1)*(ny+1), 2] or similar forms.

**Comment by jklymak** [comment]
I'd return as x,y and x and y have shape `(nx+1, ny+1)`.

**Comment by greglucas** [comment]
`get_xydata` returns (N, 2) apparently: https://github.com/matplotlib/matplotlib/blob/d9214de25afe57a2363e38082222d131b1fd8558/lib/matplotlib/lines.py#L1015-L1021

Quadmesh `get_array()` returns a flattened array (nx*ny, )

Too many options :)

**Comment by greglucas** [comment]
I just opened up #18472 with the basic implementation. I figured we can continue the discussion about the API under the review over there.
