### ISSUE TITLE
%matplotlib notebook magic no longer shows plots

### ISSUE THREAD

**Issue by rsokl** [matplotlib/matplotlib#18396]
### Bug report

**Bug summary**

In Firefox (haven't tested other browsers), the `%matplotlib notebook` magic causes plots to not render.

Changing to `%matplotlib inline` will produce the plot

**Code for reproduction**

```python
import matplotlib.pyplot as plt
%matplotlib notebook

fig, ax = plt.subplots()
ax.plot(range(10))
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/29104956/92021242-7a532c00-ed27-11ea-9fa1-26ca2af3346a.png)

**Expected outcome**

I expect a plot to be produced by the above code, instead of that weird charm that it displayed

**Matplotlib version**

  * Operating system:  Ubuntu 18.04.4
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.9
  * Jupyter version (if applicable):
  * Other libraries: 
```
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.18.1           py37h5ca1d4c_0
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
```

Installed from conda, default channel.

**Comment by QuLogic** [comment]
What version of Firefox?

**Comment by ianhi** [comment]
@rsokl have you tried flipping the order of the first two lines?
when I run your example I get a blank plot:
![image](https://user-images.githubusercontent.com/10111092/92071013-aac4b580-ed7b-11ea-9d6e-621677e1f255.png)

with this error in the console:
```
Exception inside the 'handler_close' callback: TypeError: this is undefined
    handle_close http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:727
    socket_on_message http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:542
    comm_websocket_adapter http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:692
    _callback http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37260
    handle_msg http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37268
    CommManager.prototype.comm_msg/this.comms[content.comm_id]< http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37198
 mpl.figure.prototype.handle_close@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:727:5
socket_on_message@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:542:25
comm_websocket_adapter/<@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1 line 35520 > eval:692:12
Comm.prototype._callback@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37260:24
Comm.prototype.handle_msg@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37268:21
CommManager.prototype.comm_msg/this.comms[content.comm_id]<@http://localhost:8889/static/notebook/js/main.min.js?v=f71d682290e3b718d369f11ba1d1aef1:37198:42
```
also subsequent plots are embedded without interactivity
![image](https://user-images.githubusercontent.com/10111092/92071115-e65f7f80-ed7b-11ea-8652-c06021c18022.png)


However if I swap the order of the first two lines
```python
%matplotlib notebook
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot(range(10))
```

then everything works as expected.

OS: PopOS 20.04 (basically ubuntu)
Browser: Firefox 78.0.1
matplotlib version: 3.3.1
python: '3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) \n[GCC 7.5.0]'

**Comment by ianhi** [comment]
Also, I just checked and I see the same behavior on Chrome  83.0.4103.116 (Official Build) (64-bit)

**Comment by rsokl** [comment]
Firefox Quantum 68.11.0esr (64-bit)

@ianhi  unfortunately, neither of those behaviors manifest for me


![image](https://user-images.githubusercontent.com/29104956/92129827-04f06580-edd2-11ea-8150-db6c2d05f37a.png)

**Comment by QuLogic** [comment]
> Firefox Quantum 68.11.0esr (64-bit)

Ah, this is the same as #18481. See the workaround in https://github.com/matplotlib/matplotlib/issues/18481#issuecomment-692337027

**Comment by jklymak** [comment]
I don't think there is any reason for both issues to be open?
