### ISSUE TITLE
redirect contribute to dev version

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#18402]
### Problem
Many new contributors start at either https://matplotlib.org/devel/index.html or https://matplotlib.org/users/installing.html and often end up installing the latest release rather than the dev release from master. 

### Suggested Improvement
these were both proposed on today's GSOD call:
1. redirect the contribute button on the homepage to https://matplotlib.org/devdocs/devel/index.html & add language about checking out https://matplotlib.org/ docs when developing
2. Add a link/obnoxious banner to the dev docs on https://matplotlib.org/devel/index.html

**Comment by rajpratyush** [comment]
> add language about checking out https://matplotlib.org/ docs when developing

@story645 could not understand this?

**Comment by QuLogic** [comment]
This issue is a bit outdated, as we probably want to move contributing docs to https://github.com/matplotlib/mpl-brochure-site/ instead.

**Comment by story645** [comment]
I thought they were getting moved to a third contribute-docs repo, but yeah this might be questionably actionable.
@rajpratyush yeah sorry incomplete link there, I meant folks should check the development version of the docs at dev.matplotlib.org before putting in a doc pr

**Comment by rajpratyush** [comment]
@story645 So the solutions for this issue could be :

1.  we need to explicitly mention the contributors to install the dev version rather than latest release.

2. redirect the contribute button on the homepage to https://matplotlib.org/devdocs/devel/index.html

3. Add a link to the dev docs on https://matplotlib.org/devel/index.html

4.  Tell the developers to check the development version of the docs at dev.matplotlib.org before putting in a doc PR.

**Comment by story645** [comment]
Sounds like a reasonable plan.
Going by @QuLogic's comment, is more that this issue is maybe stalled until we decide what we're doing w/ the contributing guide, but I think most of the proposed changes would carry over to a moved contribute guide anyway (especially the thing about docs).

**Comment by rajpratyush** [comment]
@story645 that was my one of the concerns that this issue maybe stale for a while. When do you think the work on this will begin?

**Comment by story645** [comment]
closing in favor of #22866 and the rest of the action items have been incorporated into docs/templates
