### ISSUE TITLE
Double-click events are not recognised in Jupyter notebook

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/matplotlib#18404]
### Bug report

**Bug summary**

Using the first example from the [events documentation](https://matplotlib.org/3.3.1/users/event_handling.html) detects double-click events properly in the Qt backend, but when used in a Jupyter notebook, the two clicks are recognised as two separate single click events.

**Code for reproduction**

I've adapted the code to show the contents of the `event` as the figure title instead of a `print` statement, because the output of `print` statements inside functions triggered by events disappear in Jupyter notebooks.

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

def onclick(event):
    ax.set_title('%s click: button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
          ('double' if event.dblclick else 'single', event.button,
           event.x, event.y, event.xdata, event.ydata))

cid = fig.canvas.mpl_connect('button_press_event', onclick)
```

**Actual outcome**

The title always says `single-click`, no matter how fast I do my double-clicking.

![Screenshot at 2020-09-04 08-02-20](https://user-images.githubusercontent.com/39047984/92204984-ffa02300-ee84-11ea-9f2d-c4a932cc91cc.png)

The double click events are properly captured when using the standard Qt window renderer.
I have tried both the default `%matplotlib notebook` backend and the `ipympl` widget backend, and they show identical behaviour.

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg, ipympl
  * Python version: 3.7.6
  * Jupyter version (if applicable): jupyter_client=6.1.6, jupyter_core=4.6.3, notebook=6.0.3
  * Other libraries: 

Installed in a `conda` env from `conda-forge`.

**Comment by tacaswell** [comment]
In the desktop backends we rely on the framework to detect the double click, hopefully this fix is as simple as getting the js to do the same for us.

**Comment by tacaswell** [comment]
Labeled as good first issue as the changes should be relatively localized (as it only related to how we pass mouse events from the js frontend back to the Python side), but medium difficulty as it will require understanding some of the internals of our event system (to fabricate the correct Event on the python side), the protocol we use between the front end and the python process, and working in both Python and JS.

I think each of these task is well contained and tractable for someone who is comfortable working in both js and python.

**Comment by hershd23** [comment]
Hi, I'd like to take the issue if it's available. I am a first timer here, although I have PR's at other places (Not merged yet). Also, I am comfortable with both js and python.

**Comment by ianhi** [comment]
Ipympl has a different javascript setup than nbagg so this will also need to be fixed there. I opened https://github.com/matplotlib/ipympl/issues/261 on the ipympl with a quote of the original post in this issue. 


> I've adapted the code to show the contents of the event as the figure title instead of a print statement, because the output of print statements inside functions triggered by events disappear in Jupyter notebooks.

In jupyterlab you can see them by opening the Log Console and setting the level to `info`:
![image](https://user-images.githubusercontent.com/10111092/92335205-0a181380-f063-11ea-8bf0-61f25b7dd2c6.png)
and then you can see the events in the log console:
![image](https://user-images.githubusercontent.com/10111092/92335287-d5f12280-f063-11ea-95e3-c3cb827003eb.png)

You can also use an `ipywidgets.Output` to capture the output and display it.

```python
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
fig, ax = plt.subplots()
ax.plot(np.random.rand(10))
out = widgets.Output()

@out.capture()
def onclick(event):
    print(event)
    ax.set_title('%s click: button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
          ('double' if event.dblclick else 'single', event.button,
           event.x, event.y, event.xdata, event.ydata))
display(out)
cid = fig.canvas.mpl_connect('button_press_event', onclick)
```

**Comment by nvaytet** [comment]
@ianhi nice! I didn't know about the Log Console trick.

Another workaround is to use `os.write`, as I suggested in this other issue: https://github.com/jupyter/notebook/issues/244#issuecomment-682390836

**Comment by tacaswell** [comment]
@hershd23 It is "up for grabs" until someone starts working on it.
