### ISSUE TITLE
Error executing code from Tutorial  "The Lifecycle of a Plot"

### ISSUE THREAD

**Issue by guidocattani** [matplotlib/matplotlib#18416]
https://matplotlib.org/3.3.1/tutorials/introductory/lifecycle.html#sphx-glr-tutorials-introductory-lifecycle-py

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-e66fce682daa> in <module>
     17 ax.set(xlim=[-10000, 140000], xlabel='Total Revenue', ylabel='Company',
     18        title='Company Revenue')
---> 19 ax.xaxis.set_major_formatter(currency)
     20 ax.set_xticks([0, 25e3, 50e3, 75e3, 100e3, 125e3])
     21 fig.subplots_adjust(right=.1)

~/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in set_major_formatter(self, formatter)
   1626         formatter : `~matplotlib.ticker.Formatter`
   1627         """
-> 1628         cbook._check_isinstance(mticker.Formatter, formatter=formatter)
   1629         self.isDefault_majfmt = False
   1630         self.major.formatter = formatter

~/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py in _check_isinstance(_types, **kwargs)
   2126                     ", ".join(names[:-1]) + " or " + names[-1]
   2127                     if len(names) > 1 else names[0],
-> 2128                     type_name(type(v))))
   2129 
   2130 

TypeError: 'formatter' must be an instance of matplotlib.ticker.Formatter, not a function

**Comment by jklymak** [comment]
What version of matplotlib are you using?

**Comment by jklymak** [comment]
You are using an older version of Matplotlib.  Please use the appropriate docs for the appropriate version: i.e. https://matplotlib.org/3.2.0/tutorials/introductory/lifecycle.html#sphx-glr-tutorials-introductory-lifecycle-py has an extra step that is not necessary in 3.3.1
