### ISSUE TITLE
Raster-to-vector conversion with matplotlib.

### ISSUE THREAD

**Issue by hongyi-zhao** [matplotlib/matplotlib#18410]
Hi,

Can I convert images in raster formats, say, JPG, PNG, GIF to PDF, SVG, EPS formats with matplotlib?

Best regards,
HY

**Comment by jklymak** [comment]
Not directly, no.

**Comment by tacaswell** [comment]
If you have a Maptlotlib Figure object in Python you can directly save it as raster or vector formats, but if you only have the saved raster file we can not help you.

**Comment by timhoffm** [comment]
General file conversion is out of the scope of Matplotlib.
