### ISSUE TITLE
Errors executing code from log-demo Tutorial

### ISSUE THREAD

**Issue by guidocattani** [matplotlib/matplotlib#18414]
Errors executing code in Tutorial

https://matplotlib.org/3.3.1/gallery/scales/log_demo.html

### Problems
1. TypeError: LogScale got an unexpected keyword argument 'base'

2. LogScale got an unexpected keyword argument 'nonpositive'

**Comment by jklymak** [comment]
Our docs won't pass if there is such an error so i suspect you are using a different version of matplotlib.

**Comment by jklymak** [comment]
This works fine w/ 3.3.1, so please use the appropriate version of matplotlib docs according to your version of matplotlib.  Thanks
