### ISSUE TITLE
yaxis.set_label_position("right") resets "horizontalalignment"

### ISSUE THREAD

**Issue by andrzejnovak** [matplotlib/matplotlib#18427]
### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib.pyplot as plt

f, axs = plt.subplots(1, 2)
axs[0].set_ylabel("XXXXXX", y=1, ha='right')
axs[1].set_ylabel("XXXXXX", y=1, ha='right')
axs[1].yaxis.set_label_position("right")
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/13226500/92377592-a8a88100-f104-11ea-818b-8ec8f594de66.png)

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.3.1'
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
It looks like there is an explicit resetting of the ha https://github.com/matplotlib/matplotlib/blob/2c265edcd8e04c736e7f3cf821d6d36ba90efb61/lib/matplotlib/axis.py#L2332-L2346

which came in via b2a80a7a5685f42533d06f2c4cb4fd223e2aa46f / https://github.com/matplotlib/matplotlib/pull/1589 which looks like it was done to make sure color bar labels show up correctly.   If I remove that line the tests still pass locally so I am cautiously optimistic that we can fix this...

**Comment by tacaswell** [comment]
Labeling as 3.4 as this has been the behavior from 1.3.
