### ISSUE TITLE
Scatter plots not taking different colours on sucessive runs.

### ISSUE THREAD

**Issue by dreaquil** [matplotlib/matplotlib#18437]
### Bug report

**Bug summary**
I am trying to create a simple plot (single figure) with multiple scatter plots of different colours in a Jupyter Notebook. However, when I run a for loop to plot different parts of my pandas dataframe, all points are plotted with the final iteration's colour. I can confirm that all the points from the prior loops are there. 

This is the dataframe:

<img src="https://i.ibb.co/1fwxJ8b/df.jpg">

**Code for reproduction**

```python
plt.figure()
for cycle in range(5):
    filtered_df = full_df[(full_df['type']=='heating') & (full_df['cycle'] == cycle)]
    plt.scatter(filtered_df['temperature'], filtered_df['focal_value'], label=cycle)
plt.legend()
plt.grid()
plt.show()
```

**Actual outcome**

<img src="https://i.ibb.co/rGmrD1h/download.png">

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10 +WSL
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.6.9
  * Jupyter version (if applicable): 1.0.0 
  * Notebook version: 6.0.3
  * Pandas: 1.0.4

I installed matplotlib in a venv using pip.

**Comment by QuLogic** [comment]
The example is incomplete without the dataframe. Please simplify it so that it can be run.
