### ISSUE TITLE
We need Object Oriented Programming

### ISSUE THREAD

**Issue by Access-Rend** [matplotlib/matplotlib#18433]
How could I know which Object I'm drawing currently?
I can hardly see wich plot is handled form a part of code.
**WE NEED Object Oriented Programming INSTEAD OF  Procedure Oriented Programming.** 
: (

**Comment by Access-Rend** [comment]
matplotlib should not bee so uneasy to use

**Comment by story645** [comment]
We have an object oriented API. You can find more info at https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

I'm going to close this because it's unclear what the actionable next step is, but will reopen if there is one.

**Comment by jklymak** [comment]
While complaints like this are valid, they would be more helpful if you gave us some idea how you tried to learn, and how that was inadequate.  Thanks!

**Comment by Access-Rend** [comment]
> While complaints like this are valid, they would be more helpful if you gave us some idea how you tried to learn, and how that was inadequate. Thanks!

Thanks for replying!
I learnt other libraries via thier README or Document, and they write them donw at **start**.
For instance, like [User Guide of GSON](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Overview)
Most developer prefer a guide like that, my colleagues and I just wanna a easy document for reading.
I spent half hour to know how I can use **GSON**, but I have spent 2h on **Matplotlib** and still bothered by its type design.
Btw, we are not a Science worker.

**Comment by jklymak** [comment]
Matplotlib is significantly complicated that it cannot just be documented via a Readme.  Please read our tutorials or one of the many excellent tutorials on the web.
