### ISSUE TITLE
ImportError: cannot import name 'dedent' from 'matplotlib.cbook'

### ISSUE THREAD

**Issue by AgilentGCMS** [matplotlib/matplotlib#18432]
### Bug report

**Bug summary**

I had a perfectly functional installation of matplotlib and basemap on my mac via macports. I recently upgraded all outdated macport packages. Now trying to import basemap gives me the error `ImportError: cannot import name 'dedent' from 'matplotlib.cbook'`

**Code for reproduction**

```python
import mpl_toolkits.basemap
```

**Actual outcome**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fbe8065c757c> in <module>
----> 1 import mpl_toolkits.basemap

~/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py in <module>
     48 from matplotlib.image import imread
     49 import sys, os, math
---> 50 from .proj import Proj
     51 import numpy as np
     52 import numpy.ma as ma

~/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mpl_toolkits/basemap/proj.py in <module>
      4 import pyproj
      5 import math
----> 6 from matplotlib.cbook import dedent
      7
      8 __version__ = '1.2.2'

ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/cbook/__init__.py)
```

**Expected outcome**

I expect to be able to use basemap as before. Something in the matplotlib version bump broke this. I have tried uninstalling and reinstalling matplotlib and basemap, but no dice.

**Matplotlib version**

  * Operating system: MacOS 10.15.5
  * Matplotlib version: 3.3.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.8.5
  * Other libraries: 

Both matplotlib and basemap were installed via macports.

**Comment by WeatherGod** [comment]
macports must have not updated their basemap package. The latest and final
release of basemap has the fix for this.

Also, re-emphasizing the "final"-ness of basemap. It is dead. Please use
Cartopy.

**Comment by jklymak** [comment]
Closing as a version mismatch issue (also next time, please indicate the version of the library w the problem)

**Comment by AgilentGCMS** [comment]
@WeatherGod What is the basemap version with the fix? I have 1.2.1.

Also, I am aware of the final-ness of matplotlib, and would love to switch full time to cartopy. It's just that I find cartopy to be significantly more buggy and less well documented, with features that simply worked in basemap producing unexpected results in cartopy (this is just my impression). Even [a simple scatter plot](https://github.com/SciTools/cartopy/issues/1597) does not work as expected. Every few months I give cartopy a try, and either come across a bug/unexpected feature or cannot find how to do something, and go back to basemap. In many cases, the "defaults" in basemap -- such as which rivers are plotted and with what line thickness -- are simply more suitable for my purpose. 

All this is to say, thank you for maintaining basemap for as long as you have, even though you've been trying for years to move people away from basemap and to cartopy :-)

**Comment by WeatherGod** [comment]
v1.2.2 is the release.

And yes, I totally understand the difficulties with the cartopy transition,
which is why I have been encouraging the transition for several years in
order to help shake out the bugs and missing features. One of the
attractive things about basemap is its code stability. This is
unintentional as it is nearly impossible to make useful changes to the
library due to its design and almost complete lack of unit tests. Cartopy
is in good hands, but it does have some big shoes to fill.

Another interesting package that isn't quite the same thing, but is neat is
pyGMT: https://github.com/GenericMappingTools/pygmt

**Comment by AgilentGCMS** [comment]
FYI, I installed the latest basemap release, and I no longer have the issue I originally reported, thanks! Curiously, even though the name of the zip file is [v1.2.2rel.zip](https://github.com/matplotlib/basemap/archive/v1.2.2rel.zip), checking the version from within python with 
```python
import mpl_toolkits.basemap
print(mpl_toolkits.basemap.__version__)
``` 
still shows 1.2.1. Maybe that's something you want to fix.

Indeed, cartopy has some big shoes to fill :-) I'll give it another go.

And pygmt sure produces some pretty maps!

**Comment by WeatherGod** [comment]
Oh, oops, I forgot to update the information in the file when I released
the new version.
