### ISSUE TITLE
question with tricontour with mask

### ISSUE THREAD

**Issue by peterspy** [matplotlib/matplotlib#18448]
Dear developer,

I have a question related to plt.tricontour. I am trying the same thing as issue #10167.

I used the below line to draw a contour result from unstructured mesh. But the error says "SyntaxError: positional argument follows keyword argument".

cs1 = axes.tricontour(x, y, elem2, mask=trimask_1, gphh_M2_1, np.linspace(30,330,11), 'colors'='w')

I am new to python. Thanks in advance for replying this question.

Pengyang

**Comment by jklymak** [comment]
You can't call a keyword argument and then non keyword argument after.  Please google the error if this is still unclear.
