### ISSUE TITLE
Download/Export button on citation page

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#18442]
## Problem
The [citing matplotlib](https://matplotlib.org/citing.html) page provides the citation in bibtex form, which reference managers like Zotero don't have a way to paste in to process. But if you download a .bib entry, Zotero will pick it up and process it.

### Proposed Solution
While yes, folks can copy & paste the bibtex entry into a text file, that introduces extra step(s) for a situation where the fix is relatively straightforward:
1. pull the bibtex block out of /doc/citing.rst into its own file
2. include it with highlighting using the [literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) directive
3. add a download link using the [download](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=Referencing%20downloadable%20files#role-download) role. 

### Additional context and prior art
The ieeexplore citation has a 'download' option: 
![image](https://user-images.githubusercontent.com/1300499/92647381-cbc66280-f2b5-11ea-9076-08839b105139.png)

**Comment by jklymak** [comment]
As a workaround: https://forums.zotero.org/discussion/70420/allow-pasting-of-bibtex-entries  Looks like you can paste from clipboard...
