### ISSUE TITLE
src/_ttconv.o: file not recognized while attempting to install on aarch64

### ISSUE THREAD

**Issue by stuart-little** [matplotlib/matplotlib#18443]
### Bug report

**Bug summary**

I am trying to install on `aarch64` running `Android 10`, in the [Termux](https://github.com/termux/) terminal emulator.

I have `Python 3.8.5` and the dependencies, as far as I can tell. I am cloning this repo and issuing 

```
pip install .
```
in the resulting directory. The build fails: a [full log](https://termbin.com/8rt0), where you'll find errors of the form

```
build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o: file not recognized: file format not recognized
```
or as in the title:
```
build/temp.linux-aarch64-3.8/src/_ttconv.o: file not recognized: file format not recognized
```

**Code for reproduction**

As mentioned, issuing

```python
pip install .
```
in my circumstances: `Termux` on `Android 10`, having cloned this repo.

**Actual outcome**

Full output linked in the [pastebin](https://termbin.com/8rt0) above.

**Expected outcome**

Successful installation.

**Matplotlib version**

Latest matplotlib, cloned from here.

  * Operating system: `Android 10`
  * Matplotlib version: clone of this repo
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: 3.8.5
  * Jupyter version (if applicable): 4.6.3 (core)
  * Other libraries: ?

---

I have a posted an [issue](https://github.com/termux/termux-packages/issues/5787#issue-696938449) with the Termux folks too, but they seem stumped by the errors..

**Comment by QuLogic** [comment]
You should follow up with termux. I don't see how there's anything we can do here if your compiler is producing broken output.

**Comment by stuart-little** [comment]
@QuLogic I think there might be more to this:

Inspired by [other reports](https://github.com/numba/llvmlite/issues/54) of similar errors apparently resulting from `LLVM` choking on `-flto`, I installed the `binutils-gold` package and did

```
export LDFLAGS=" -lm -lcompiler_rt -fuse-ld=gold"
```
before trying again. The original errors are gone now! Instead, I have [new ones](https://termbin.com/zfar):

```
/data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o:1:3: invalid character                               /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o:1:3: syntax error, unexpected $end                   /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o: not an object or archive                            /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/mplutils.o:1:3: invalid character                                         /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/mplutils.o:1:3: syntax error, unexpected $end
```
and so on.

**Comment by tacaswell** [comment]
@stuart-little We would take a PR to adjust the flags if we can reliably detect being on a system where `-flto` is broken.

**Comment by QuLogic** [comment]
If it's LTO, we have a flag you can set to disable it: #17623 You can copy `setup.cfg.template` to `setup.cfg`, uncomment `enable_lto=False`, and see if that has an effect.

**Comment by stuart-little** [comment]
Well, that might be the issue, but I'm still out of my depth here.. I've also tried compiling with `gcc-10` instead, but am still erroring out. Differently though, as [this other paste](https://termbin.com/7g1uj) shows:

```
242 | char* strrchr(char* const s __pass_object_size, int c) __prefer_this_overload {                        
 |     
 ^~~~~~~~~~~~~~~~~~~~~~ 
/data/data/com.termux/files/usr/include/string.h:251:50: error: attributes are not allowed on a function-definition                                              251 | const char* strstr(const char* h, const char* n) __prefer_this_overload {
| 
^~~~~~~~~~~~~~~~~~~~~~                           
In file included from /data/data/com.termux/files/usr/include/c++/v1/string.h:60,  from /data/data/com.termux/files/usr/include/stdio.h:47,                                                  from /data/data/com.termux/files/usr/include/c++/v1/stdio.h:107,                                          from /data/data/com.termux/files/usr/include/python3.8/Python.h:25,                                       from src/mplutils.h:30,                              from src/mplutils.cpp:3:            /data/data/com.termux/files/usr/include/string.h:251:13: error: ambiguating new declaration of 'const char* strstr(const char*, const char*)'
```

**Comment by stuart-little** [comment]
@QuLogic That was it, thank you: commenting out `enable_lto=False` in `setup.cfg` resulted in an installation.

**Comment by jklymak** [comment]
@stuart-little can we close this then?  Like I *guess* we could put something in to make sure lto worked or automatically set it to false.  Not sure if lto has an easy test...
