### ISSUE TITLE
nbagg: Closing a figure from the notebook does not close the python figure

### ISSUE THREAD

**Issue by sbitzer** [matplotlib/matplotlib#18447]
I'm reporting a digression from previous behaviour of the nbagg backend in Jupyter notebooks. Until matplotlib 3.2.2, when I refreshed an interactive figure in a notebook cell by re-executing the cell, the existing figure would be closed and a new one created using the old figure number (when the cell also created the original figure). In matplotlib 3.3.1 the old figure is replaced by the new figure (with a new figure number) in the notebook output, but the old figure still exists in the kernel.

I guess this is related to "NbAgg and WebAgg no longer use jQuery & jQuery UI" from the release notes of matplotlib 3.3.0. Also, ipympl has the same issue: matplotlib/ipympl#4.

This can be tested in a notebook with:
```python
%matplotlib notebook
import matplotlib.pyplot as plt
```

```python
fig = plt.figure()
plt.get_fignums()
```

I saw this behaviour in recent versions of Firefox and Google Chrome.

I have manually applied 2c9a85ba in case this would reintroduce the old behaviour (which I prefer), but it didn't.

**Comment by jklymak** [comment]
Is this related to #17086 #17053?  @QuLogic ?   This seems a pretty major regression - I certainly have notebooks with dozens of figures that I will then execute dozens of times.

**Comment by QuLogic** [comment]
I think this is because jQuery has a wrapped `remove` event, but it doesn't actually exist in HTML/JS, so [this change](https://github.com/matplotlib/matplotlib/commit/5356ef0e2f49afb409c1b18f9bd87cdb737299ad#diff-60598e8514f705b6426dd9c11a56cebaL154-R165) is never triggered to close the figure.
