### ISSUE TITLE
MacOSX backend fails with animation in certain scripts

### ISSUE THREAD

**Issue by retifrav** [matplotlib/matplotlib#18451]
#### Bug summary

The `MacOSX` matplot backend fails with animation in certain Python scripts. On other platforms (Windows and Linux) the same animation from the same script works fine with their default backends: https://retifrav.github.io/blog/2020/09/05/matplotlib-animation-macos/video/animation.mp4

The animation also works fine on Mac OS with `TkAgg` backend.

#### Code for reproduction

The full script is a bit long, so I published it here: https://gist.github.com/retifrav/b884ce647c8ef26678c2b6408d4b8306

#### Actual outcome

No animation being played, not even the first frame.

#### Expected outcome

The animation plays like it does on Windows and Linux platforms (as it's shown on the video in the beginning of this report).

#### Matplotlib version

- Operating system: Mac OS 10.15.6
- Matplotlib version: 3.3.1
- Matplotlib backend: MacOSX
- Python version: 3.8.5
- Other libraries: numpy 1.19.1

Python was installed using Homebrew, matplotlib was installed using pip.

[Original thread](https://discourse.matplotlib.org/t/matplotlib-animation-works-on-windows-and-linux-but-not-on-mac-os/21530) at the forum.

**Comment by jklymak** [comment]
Is this a regression or did it never work?  Also a shorter example would be helpful.  Do the examples in the docs work? Thanks for your help!

**Comment by retifrav** [comment]
I don't know if it worked before, this is the first version of matplotlib I ever worked with.
Sadly I don't have a shorted example, only this full script.
Examples from documentation work fine.

**Comment by tacaswell** [comment]
If you change line 104 -> `blit=False` does it work?

**Comment by tacaswell** [comment]
My knee-jerk guess is that the blitting support on osx got broken recently.

**Comment by QuLogic** [comment]
This definitely has to do with blitting, but it doesn't seem to have ever worked, as far back as at least 3.1.0.

**Comment by QuLogic** [comment]
If you set `line, = ax[1].plot(x, r)` first, and then do `line.set_ydata(u)` in `animate`, it _seems_ to work.

**Comment by retifrav** [comment]
> If you change line 104 -> `blit=False`

With `blit=False` the animation starts to play, but it doesn't "clear" previous frames, so it ends up looking like this:

<img width="752" alt="blit-false" src="https://user-images.githubusercontent.com/6904927/92886675-1fe75900-f414-11ea-89e6-5f4acc2ff54f.png">

> If you set `line, = ax[1].plot(x, r)` first, and then do `line.set_ydata(u)` in animate

With `blit=True` that doesn't have any effect, and with `blit=False` it ends up loking similar to previous case:

<img width="752" alt="blit-false-ydata" src="https://user-images.githubusercontent.com/6904927/92887264-a3a14580-f414-11ea-9f3c-8cbc863980ed.png">

**Comment by tacaswell** [comment]
Can you please reduce this to a minimal case that will fit in the issue?

**Comment by retifrav** [comment]
All the variables in the script seem to participate in the final result one way or another, so even if I managed to minimize the script, it would be shorter by perhaps 20%, so it's not really worth it. On top of that, I don't quite understand the math being used there, so I'm afraid I won't be able to do much about it anyway. I can only say that original script was even longer, so that's already an optimized (to the best of my capabilities) version.

**Comment by QuLogic** [comment]
This is basically because the macosx baskend doesn't really implement `blit`; it just requests a draw. It'd probably better to mark the backend as not supporting blitting.

**Comment by dstansby** [comment]
If you change line 92 to
```python
line.set_xdata(x)
line.set_ydata(u)
```
does it work? Currently you're adding a new line to the plot each time, instead of modifying the existing line.

FWIW I can get https://matplotlib.org/gallery/animation/simple_anim.html#sphx-glr-gallery-animation-simple-anim-py to work fine with `macosx` and blitting.

**Comment by retifrav** [comment]
Then script fails because `line` becomes undefined that way.
And if I add these *after* line 92, then the result is the same as with original script, so they don't seem to change anything.

**Comment by dstansby** [comment]
> > If you change line 92
> 
> Then script fails, because `line` becomes undefined that way.

What if you create the line before and outside of `animate`, and then update the line in `animate` (similar to the example I linked to)?

**Comment by retifrav** [comment]
Right! Now I understand where this "rainbow" effect comes from. That was a silly overlook.

And that way the animation now works with `MacOSX` backend too: https://retifrav.github.io/blog/2020/09/05/matplotlib-animation-macos/video/animation2.mp4
The horizontal line is weird though, as with `TkAgg` backend it's not present.
