### ISSUE TITLE
create a graph, But how to get the adj_matrix???

### ISSUE THREAD

**Issue by tanjia123456** [matplotlib/matplotlib#18467]
hello, if I use matplotlib to draw a three-dimensional graph, how can I find its adjacency matrix?

`

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import logging
import re
import numpy as np

# 创建日志对象
logger = logging.getLogger()
screen_handler = logging.StreamHandler()
formater = logging.Formatter('%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s')
screen_handler.setFormatter(formater)
logger.addHandler(screen_handler)
logger.setLevel(logging.DEBUG)

# 读取文件
with open("./HLN-12-1vertices.txt","r",encoding="utf-8") as f:
    data = f.readlines()#根据打开的文件按行读取数据
pattern = re.compile("\[(.*?)\]")
data_vertices = []
for value in data:
    temp = pattern.findall(value.strip())[0].split(" ")
    data_vertices.append([float(i) for i in temp if i != ""])#vertices的内容，特别是坐标点的内容都是浮点数，所以用float(i)
data_vertices = np.array(data_vertices)
logger.info("vertices:{}".format(data_vertices))

with open("./HLN-12-1triangles.txt","r",encoding="utf-8") as f:
    data = f.readlines()
data_triangles = []
for value in data:
    data_triangles.append([int(i) for i in value.split(" ") if i != ""][1:])#triangle 里面都是整数，所以用int(i)
    # split() 通过指定分隔符对字符串进行切片，str -- 分隔符，默认为所有的空字符，包括空格、换行(\n)、制表符(\t)等。
data_triangles = np.array(data_triangles)
logger.info("triangles:{}".format(data_vertices))

# 创建绘图对象
fig = plt.figure()
ax = fig.add_subplot(111,projection="3d")#111表明只有一个图  121就是显示在两个图中得左图  122就是显示在两个图中得右图
ax.plot_trisurf(data_vertices[:,0],data_vertices[:,1],data_vertices[:,2],triangles = data_triangles,color="#F8A599") # 此处可以调节颜色
#ax.plot_trisurf(data_vertices[:,0],data_vertices[:,1],data_vertices[:,2],triangles=data_triangles, color=(0,0,0,0), edgecolor='Gray')
#在color您指定作为facecolor; 如果您想有透明的面孔，而不是alpha=0通过color=(r,g,b,0)；该0元组将是facecolor的alpha; 因此会产生透明的面孔；
ax.set_zlabel('Z')  # 坐标轴
ax.set_ylabel('Y')
ax.set_xlabel('X')
plt.title("HLN-12-1 graph")
plt.savefig('HLN-12-1 graph.jpg')
plt.show()

`

**Comment by jklymak** [comment]
Hi this is an issue tracker. If you need help discourse.matplotlib.org is a better resource.  Thanks for your understanding!
