### ISSUE TITLE
add get_color for ax.get_legend()

### ISSUE THREAD

**Issue by StevenLi-DS** [matplotlib/matplotlib#18471]
I'm trying to get the color of the markers in the legend, but it doesn't seem like `ax.get_legend()` has a method for it.
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.scatter(1, 2, label='point 1', color='r')
ax.scatter(4, 3, label='point 2', color='b')
ax.legend()

for attr in dir(ax.get_legend()):
    if 'color' in attr:
        print(attr)
```
![download](https://user-images.githubusercontent.com/33796896/93031372-4c5bca80-f5f8-11ea-9f95-eb5b6928d9c0.png)

**Comment by story645** [comment]
Why do you need this info given that the legend takes its color from the plot?

**Comment by StevenLi-DS** [comment]
For example, I may need to change the shape of the legend after the fact but keep the color of it.

**Comment by jklymak** [comment]
I think this info is in https://matplotlib.org/3.3.1/tutorials/intermediate/legend_guide.html  If you have further questions, suggest https://discourse.matplotlib.org is a better venue.   I'll close this here.  Thanks for your understanding.

**Comment by StevenLi-DS** [comment]
@jklymak I did read it including all the examples I can find online. They all require you to define the colors before you plot. But I need to get the color after I plotted the figure.

**Comment by jklymak** [comment]
Again, lets please take this to discourse.matplotlib.org.  Did you try `legend.get_patches`?  https://matplotlib.org/3.3.1/api/legend_api.html#matplotlib.legend.Legend.get_patches

**Comment by StevenLi-DS** [comment]
`ax.get_legend().get_patches()` returns me an empty list `<a list of 0 Patch objects>`. am I missing something?

**Comment by tacaswell** [comment]
@StevenLi-DS Can we please move this to https://discouse.matplotlib.org ?  It is a better venue for this sort of discussion.

**Comment by StevenLi-DS** [comment]
@tacaswell Hi, sorry I never used that site.
I couldn't found a workaround about the issue I have, so I open this issue as a feature request. I don't know why this doesn't fit on Github. If there is a solution for this, it should perhaps be shared on SO. so I'm confused with the purpose of https://discourse.matplotlib.org.

**Comment by StevenLi-DS** [comment]
https://discourse.matplotlib.org/t/add-get-color-for-ax-get-legend/21558
