### ISSUE TITLE
Axes.secondary_xaxis() does not allow for changing ticks or inheriting and transforming ticks from main axis

### ISSUE THREAD

**Issue by ilanbiala** [matplotlib/matplotlib#18486]
### Bug report

**Bug summary**

[`Axes.secondary_xaxis()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.secondary_xaxis.html?highlight=secondary_xaxis#matplotlib.axes.Axes.secondary_xaxis) allows you to a create a secondary axis with a transform applied to the main axis range, but the secondary axis does not inherit the new ticks from the main axis, even if the secondary axis is created after modifications to the main axis.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker


# Treats x = 20 as the zero point for the secondary axis, and also treats the secondary axis as 1/10th scale
def shift_and_scale_forwards(x):
    return (x - 20) / 10

def shift_and_scale_backwards(x):
    return (x * 10) + 20


fig = plt.figure()
ax0 = fig.add_subplot()
ax0.plot(range(0, 500, 5))
ax0.xaxis.set_major_locator(ticker.MultipleLocator(10))
top_ax0 = ax0.secondary_xaxis("top", functions=(shift_and_scale_forwards, shift_and_scale_backwards))
fig.show()
```

**Actual outcome**

<img width="752" alt="Screen Shot 2020-09-14 at 8 11 31 PM" src="https://user-images.githubusercontent.com/3695164/93150214-85fb0700-f6c6-11ea-9ddf-a9f9bdd8a46d.png">

```
# ax0.get_xticks() yields array([-10.,   0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.])
# top_ax0.get_xticks() yields array([-4., -2.,  0.,  2.,  4.,  6.,  8., 10.])
```

**Expected outcome**

`top_ax0` would have the same number of ticks as `ax0`.

**Matplotlib version**

  * Operating system: macOS Catalina 10.15.4 and Ubuntu Linux 16.04 LTS
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX on macOS, and agg on Ubuntu
  * Python version: 3.8.5 on Linux and 3.7.4 on Ubuntu
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

I used pip for both macOS and Ubuntu.

**Comment by jklymak** [comment]
The ticks don't transform as well and aren't designed to.  If you want them to, I guess you can do `top_ax0.set_xticks(shift_and_scale_forwards(ax0.get_xticks())` manually.

**Comment by ilanbiala** [comment]
Why aren't they designed to, and why is inheriting the ticks from the main axis not expected behavior? I'd expect that if I set the ticks on the main axis before I create the secondary axis that the secondary axis would have the same ticks..if I didn't do it in order I could at least be convinced that that's expected.

**Comment by ilanbiala** [comment]
Also, why is it not possible to add a locator on a secondary axis?

**Comment by jklymak** [comment]
@ilanbiala Happy to discuss this at discourse.matplotlib.org but not on the Issue tracker.  Please see https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/secondary_axis.html#sphx-glr-gallery-subplots-axes-and-figures-secondary-axis-py for more info.  

> Also, why is it not possible to add a locator on a secondary axis?

It is possible (see same link above).
