### ISSUE TITLE
"%matplotlib notebook" not working in firefox with matplotlib 3.3.1 

### ISSUE THREAD

**Issue by stefanazzz** [matplotlib/matplotlib#18481]
### Bug report

**Bug summary**

using "%matplotlib notebook"  to get interactive plots in notebook running on firefox browser stopped working upon upgrade from matplotlib 3.1.1 to 3.3.1. Firefox 68.0.1 (64-bit) for Linux MINT. 

Still works fine in google chrome. Other interactive like "%matplotlib widget" or "%matplotlib ipympl" are OK in both firefox & chrome. 

No error message, just a small triangle appears in lieu if the plot in the notebook.

**Code for reproduction**

```python
# Paste your code here
%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt
fig,ax=plt.subplots()
ax.plot([0,1,2],[1.1,2.3,4],'o');
print(matplotlib.__version__)
#
#
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/45072850/93125400-facc4200-f6c2-11ea-8e6d-99502f93cbdf.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

![image](https://user-images.githubusercontent.com/45072850/93125467-19cad400-f6c3-11ea-9532-17c4e80e860a.png)

 
Used to work in matplotlib 3.1.1

**Matplotlib version**

  * Operating system: Linux MINT
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.8 | packaged by conda-forge
  * Jupyter version (if applicable): 
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.5
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

  * Other libraries: 

install from conda

channels:
  - gimli
  - anaconda
  - conda-forge
  - defaults

**Comment by jklymak** [comment]
I cannot reproduce this on master with Firefox (80.0.1 (64-bit)) on my mac.  1) that's a pretty old firefox? 2) maybe change the order to put the `%matplotlib notebook` after the import?

**Comment by QuLogic** [comment]
I can reproduce this with IceCat, which is still on the 68 ESR line.

**Comment by QuLogic** [comment]
I thought it was older, but you actually need Firefox 69 for `ResizeObserver`. I could try and find a shim if we want to continue supporting ESR.

**Comment by QuLogic** [comment]
Ah, so it turns out that Firefox 68 does support `ResizeObserver`, but it was experimental and hidden behind a flag. If you go to `about:config`, and set `layout.css.resizeobserver.enabled` to true, then it's fixed. As there's a workaround, I don't want to hold up 3.3.2 on this, but maybe for 3.3.3 (if that happens), we can think about the shim idea.

**Comment by stefanazzz** [comment]
I confirm that setting layout.css.resizeobserver.enabled to true in firefox
fixes it.
However I am sharing notebooks with other users, this will force each
firefox user to implement the fix on their own browser, not ideal.
Maybe the idea of a fix in 3.3.3 is not bad, unless future firefox releases
revert to true resizeobserver by default.
--And Thanks!


On Mon, Sep 14, 2020 at 11:01 PM Elliott Sales de Andrade <
notifications@github.com> wrote:
>
> Ah, so it turns out that Firefox 68 does support ResizeObserver, but it
was experimental and hidden behind a flag. If you go to about:config, and
set layout.css.resizeobserver.enabled to true, then it's fixed. As there's
a workaround, I don't want to hold up 3.3.2 on this, but maybe for 3.3.3
(if that happens), we can think about the shim idea.

**Comment by QuLogic** [comment]
It's enabled in all releases after 68; this is only a problem in ESR.

**Comment by stefanazzz** [comment]
Sounds like problem will fix itself with next browser update then. No
reason to follow up.
Cheers
