### ISSUE TITLE
Add a method to access the list of registered colormaps

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#18490]
### Describe the issue

I noticed that the linked issues to PR
https://github.com/matplotlib/matplotlib/pull/16991
all want a public way to access the registered colormap names without resorting to importing pyplot. That PR removed the cm.cmap_d dictionary, but left nothing in its place.

There were a few suggestions in this thread: https://github.com/matplotlib/matplotlib/pull/16991#discussion_r415267245

**Summary**

Create a way to access the keys of the colormap registry within the `mpl.cm` module.

### Proposed fix

Some ideas:
`mpl.cm.get_cmap_names()`
`mpl.cm.get_registered_cmaps()`
keeping consistency with pyplot: `mpl.cm.colormaps()`
... something else entirely

**Comment by timhoffm** [comment]
IMHO, the colormaps should be accessed via a global `colormaps` mapping. See #18503 for a rough sketch.
