### ISSUE TITLE
Create page with advice for writing a third party package

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#18496]
### Problem

There is low discoverability for several things that would make life easier for a third party package developer. For example, I had no idea what a trove classifier even was until it was suggested to me here https://github.com/ianhi/mpl-interactions/issues/25. I also didn't know that it was ok for me to try  to advertise via matplolib (e.g. 3rd party packages page, `@matplotlib` on twitter)

Understanding copywrite can also be tricky, for example see this [discourse conversation](https://discourse.matplotlib.org/t/docs-for-a-method-wrapping-a-matplotlib-method/21055/4?u=ianhi)

### Suggested Improvement

Create a `Creating A Third Party Package` page on the docs. Here's an initial list of topics I think would be helpful:

**practical**
- practical copyright rules
   - If it were homework and you didn't acknowledge would it be cheating?
   - If yes then .... (e..g add a comment and include a license file in ___ folder)
- point out that [pytest-mpl](https://github.com/matplotlib/pytest-mpl) exists
- admonish the use of matplotlib private methods
- information on how to passing through docstrings from https://discourse.matplotlib.org/t/docs-for-a-method-wrapping-a-matplotlib-method/21055
- link to, or subsume, https://colcarroll.github.io/yourplotlib/

**communication**
- Encourage tweeting about your package to `@matplotlib`
   - Link to https://github.com/matplotlib/governance/blob/master/communications_guidelines.md for full explanation
- Explain the standard for inclusion in the third-party-packages list/encourage or discourage this
- Mention the 3rd party packages section on discourse
     - Provide an example questions issue template redirecting questions there? (Mine is [here](https://github.com/ianhi/mpl-interactions/blob/master/.github/ISSUE_TEMPLATE/question.md))

ping @story645

**Comment by ianhi** [comment]
Also:
https://github.com/NSLS-II/scientific-python-cookiecutter
and 
https://nsls-ii.github.io/scientific-python-cookiecutter/

**Comment by story645** [comment]
Page should also suggest adding "Framework :: Matplotlib" classifier to setup.py install, and maybe linking to the core python packaging tutorial (cookie cutter can be a bit much for some things).

**Comment by ianhi** [comment]
I tried to take most the points in the first post here and incorporate them into https://github.com/ianhi/matplotlib-extension-cookiecutter

**Comment by jklymak** [comment]
@ianhi that looks really useful...

**Comment by jklymak** [comment]
I think this is basically closed by the cookie cutter, or do we need to document it somewhere?

**Comment by ianhi** [comment]
yup good call @jklymak !
