### ISSUE TITLE
Mostly unused glossary still exists in our docs

### ISSUE THREAD

**Issue by brunobeltran** [matplotlib/matplotlib#18491]
### Problem

Discussed in the GSOD call, this feels like something that we wanted to add at some point but never really got around to using. It currently just contains a list of backends (mostly) and links out to their respective external pages.

https://matplotlib.org/glossary/index.html?highlight=glossary

### Suggested Improvement

After making sure that the places that link to the glossary correctly link out to the appropriate pages, the glossary should probably just be deleted (consensus on call).

**Comment by timhoffm** [comment]
Closed by #18696.
