### ISSUE TITLE
NavigationToolbar2QT DeprecationWarning draw method

### ISSUE THREAD

**Issue by tommasomazzoni** [matplotlib/matplotlib#18518]
Drawing a navigation toolbar in a PyQt5 widget generates a deprecation warning which suggests a solution which is not implemented.

**Code for reproduction**

```python
import matplotlib
import PyQt5.QtWidgets as QtW

widget = QtW.QWidget()
fig = matplotlib.figure.Figure()
canvas = matplotlib.backends.backend_qt5agg.FigureCanvasQTAgg(fig)
navi_toolbar = matplotlib.backends.backend_qt5agg.NavigationToolbar2QT(canvas, widget)
navi_toolbar.draw()
```

```
<ipython-input-2-d1a49595b197>:8: MatplotlibDeprecationWarning: 
The draw function was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use toolbar.canvas.draw_idle() instead.
  navi_toolbar.draw()
```

Instead, using navi_toolbar.draw_idle() generets the following error:

```
AttributeError: 'NavigationToolbar2QT' object has no attribute 'draw_idle'
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.3.1
  * Matplotlib backend : Qt5Agg
  * Python version: 3.8.5
  *  PyQt5 : 5.9.2

**Comment by tacaswell** [comment]
It is `navi_toolbar.canvas.draw_idle()` not `navi_toolbar.draw_idle()`.  In your code snippet you already have a handle to the Canvas (as `canvas`), it is better practice to do `canvas.draw_idle()` rather than drawing the figure via the toolbar.
