### ISSUE TITLE
Please provide more image attribute setting options in the gui display control

### ISSUE THREAD

**Issue by CatNofishing** [matplotlib/matplotlib#18541]
Compared with matlab, matploltib's gui control is too simple, you have to set properties through a lot of code, which is very difficult for beginners or inexperienced people. I hope you can provide more setting properties in the gui display component
![image](https://user-images.githubusercontent.com/33288114/93876388-5c1a9380-fd09-11ea-8c8d-037f9f855d59.png)
![image](https://user-images.githubusercontent.com/33288114/93876461-76ed0800-fd09-11ea-8454-f489bc4e5425.png)

**Comment by jklymak** [comment]
We have a MEP that is relatively far along to allow folks to add more widgets.  https://matplotlib.org/3.2.0/devel/MEP/MEP22.html  I'm not sure how much traction adding more buttons to the default toolbar will get.  What particular functionality do you wish was there?

**Comment by CatNofishing** [comment]
![image](https://user-images.githubusercontent.com/33288114/93951014-c36f2c80-fd77-11ea-88f5-8a6a176b7f08.png)
![image](https://user-images.githubusercontent.com/33288114/93951182-35e00c80-fd78-11ea-8568-f866f4a9835f.png)

I think all the functions in the matlab menu tool options are very convenient. Please consider adding similar functions, which will greatly reduce the user's difficulty in using matplotlib.😁

**Comment by timhoffm** [comment]
I understand the request, but full GUI configurability is a different philosophy. At it's core, Matplotlib is a library, and we strongly believe in defining plots through code for reproducibility.

The GUI window with basic editing functionality is a nice add-on. But we do not aspire to add lots of configurability there. That's out of scope for the project. There are third-party projects building on top of matplotlib and going that direction (see e.g. [sviewgui](https://matplotlib.org/thirdpartypackages/index.html#sviewgui)
