### ISSUE TITLE
pcolor deprecation warning with default settings

### ISSUE THREAD

**Issue by johnomotani** [matplotlib/matplotlib#18546]
### Bug report

**Bug summary**

`pcolor()` produces a deprecation warning with default settings.

The default of `rcParams['pcolor.shading']` seems to be `'flat'`, which is deprecated (at least sometimes). Maybe the default should be changed to `'auto'` or `'nearest'`?

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np

x = np.arange(2.)
y = np.arange(2.)
z = np.ones([2,2])

plt.pcolor(x,y,z)
```

**Actual outcome**

```
MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  plt.pcolor(x,y,z)
```

**Expected outcome**

No warning

**Matplotlib version**

  * Operating system: Linux Mint 19
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.6
  * Jupyter version (if applicable): N/A
  * Other libraries: None

Installed with conda from conda-forge

**Comment by jklymak** [comment]
This was purposefully done.  "flat" was the previous default, and we need a deprecation period before we change it.  If you wish to avoid the warning, then you can manually do what flat does in this case and drop the extra row and column:
```
plt.pcolor(x, y, z[:-1, :-1])
```

See #16258 for a discussion.

I guess its a question of whether we have deprecated this long enough to change the default.

**Comment by johnomotani** [comment]
OK, that makes sense. Thanks @jklymak! BTW I think the new `"nearest"` is much better!
