### ISSUE TITLE
Use plt.stairs in animated histogram example

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#18570]
### Problem
It should be possible to radically simplify https://matplotlib.org/3.3.1/gallery/animation/animated_histogram.html#sphx-glr-gallery-animation-animated-histogram-py by using the new `stairs` methods https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.stairs.html?highlight=stairs#matplotlib.axes.Axes.stairs

### Suggested Improvement
Option 1: Replace the existing example with one using `plt.stairs` and the return values `set_data` method
Option 2: Use `plt.stairs` for the animation example and rename the current example to something about manipulating patches manually.

**Comment by timhoffm** [comment]
IMHO the example is clear and simple through #18821. No need for further action.
