### ISSUE TITLE
Create a LogSlider Widget

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#18571]
### Problem
The Slider widget currently only allows for a linear scale. Sometimes it's nice to have interactive control over LogSpaced values so a LogSlider would be great for this.

### Proposed Solution
Two parts:
1. Add an argument to `Slider` that can be used transform from the slider position (0,1) to arbitrary values
2. Create a `LogSlider` as a subclass of `Slider` that sets that transform as approriate log scaling.

### Additional context and prior art

https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#FloatLogSlider

**Comment by anntzer** [comment]
Actually you can just do `slider.ax.set_xscale("log")` and mostly be done with it, instead of having one Slider class per scale (actually you also need to re-remove the ticks, but that's a separate issue).

**Comment by ianhi** [comment]
I found removing the ticks to be non-obvious (ended up two answers deep on SO :O) so here is the technique for posterity:
```python
slider.ax.set_xscale("log")
slider.ax.set_xticks([])
ax.get_xaxis().set_tick_params(which='minor', size=0) # necessary to hide the minor ticks
``` 
based on https://stackoverflow.com/a/38777797/835607


:+1:  to a docs page or example showing how to do this.

**Comment by anntzer** [comment]
I think the problem is effectively tracked at #18572.
