### ISSUE TITLE
%matplotlib notebook figures do not display until all cells finish evaluating

### ISSUE THREAD

**Issue by johnomotani** [matplotlib/matplotlib#18596]
### Bug report

**Bug summary**

When using the `nbAgg` backend in a Jupyter notebook with `%matplotlib notebook` and creating several plots at once, none of the plots display until all cells currently being evaluated are finished, even if they are in different cells. This is especially problematic if an exception occurs somewhere in a long notebook - all the figures in cells before the cell with the exception will be blank, even though they completed successfully.

Not sure if this is a Matplotlib issue, or a Jupyter issue. Possibly related to #18138 and #17576?

**Code for reproduction**

### Example 1
Large arrays used so that the delay between figure boxes being created and plots actually being shown in them (after all cells complete execution) is noticable. Run all cells at once with 'Cell->Run all'.

**Code for reproduction**
cell 1
```python
%matplotlib notebook
from matplotlib import pyplot as plt
import numpy as np

d = np.random.rand(10000,5000)
plt.figure()
plt.pcolormesh(d)
```
cell 2
```python
plt.figure()
plt.pcolormesh(d)
```
cell 3
```python
plt.figure()
plt.pcolormesh(d)
```

**Actual outcome**

Figures display correctly, but not until all cells finish executing

**Expected outcome**

Each cell displays when it finishes, before the next cell starts executing.

### Example 2
Run all cells at once with 'Cell->Run all'. This one fails even with small arrays

**Code for reproduction**
cell 1
```python
%matplotlib notebook
from matplotlib import pyplot as plt
import numpy as np

d = np.random.rand(100,100)
plt.figure()
plt.pcolormesh(d)
```
cell 2
```python
plt.figure()
raise ValueError()
plt.pcolormesh(d)
```

**Actual outcome**
![actual_screenshot](https://user-images.githubusercontent.com/3958036/94375139-65d93800-0109-11eb-8340-f8374c32630b.png)

**Expected outcome**
expected same as the output of running each cell individually
![expected](https://user-images.githubusercontent.com/3958036/94375157-8e613200-0109-11eb-8b34-a4503d44aa0f.png)

**Matplotlib version**

  * Operating system: Linux Mint 19
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.6
  * Jupyter version (if applicable): 6.1.4
  * Other libraries: 

Installed using conda, from conda-forge.

**Comment by QuLogic** [comment]
This is pretty much the same as #18138, in that the only thing in the notebook is a small JavaScript shim, and it has to wait for the Python side to send the image, which can't be done until the code is finished running. I don't know exactly how Jupyter's cells or Matplotlib's message handler is prioritized, but I guess Jupyter's is the one that wins.

**Comment by johnomotani** [comment]
> This is pretty much the same as #18138

I'd hoped that this one might have a greater chance of being fixable, because when the Jupyter cell finishes it seems reasonable that there'd be a way to have some sort of 'display the image now' action trigger. Although from what @QuLogic says maybe it's the Jupyter handler that causes the problem, so this should really be an issue on Jupyter - can anyone confirm that? I can open an issue on the Jupyter repo, although it might be better if someone from here who actually understands the problem could do so...

**Comment by ianhi** [comment]
Also the same in `ipympl` discussed here: https://github.com/matplotlib/ipympl/issues/258
