### ISSUE TITLE
direct api to add error bars to lineplots and scatterplots

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#18598]
### Problem

Currently error bars can only be drawn through `axes.Axes.errorbar`.
While the existing api is fine, I think the discoverability would be improved by adding support for adding support for `xerr` and `yerr`  kwargs in `axes.Axes.scatter` and `axes.Axes.plot` directly.

### Proposed Solution

Here's what I'd like to work
```python
# -- scatterplot with error bars --
# current
ax.errorbar(data=data, x="x", y="y", xerr="xerr", yerr="yerr", fmt="o")

# proposed
ax.scatter(data=data, x="x", y="y", xerr="xerr", yerr="yerr")

# -- lineplot with error bars --
# current
ax.errorbar(data=data, x="x", y="y", xerr="xerr", yerr="yerr", fmt="-")

# proposed
ax.plot(data=data, x="x", y="y", xerr="xerr", yerr="yerr")
```

### Additional context and prior art

This would improve downstream projects that encapsulate `axes.Axes.plot` and `axes.Axes.scatter`.
For instance `seaborn.regplot` (https://seaborn.pydata.org/generated/seaborn.regplot.html?highlight=regplot#seaborn.regplot) would benefit from such a change and would naturally gain support for user defined error bars through `xerr` and `yerr`.

A simple and maybe naive approach would be to isolate the errorbar functionality from `axes.Axis.errorbar`. I anticipate a side effect would be that a lot of other keyword arguments, specific to `axes.Axis.errorbar` require support in `axes.Axis.plot` and `axes.Axis.scatter`, though hopefully they could be simply passed down through `**kwargs` ?

**Comment by jklymak** [comment]
>  I anticipate a side effect would be that a lot of other keyword arguments,

Thats the biggest issue here.  You would need an errorbar-kwargs dictionary, and that is a clunky API.  Unfortunately, you can't just pass the **kwargs because error bars and plot markers share many of the same kwargs.

**Comment by neutrinoceros** [comment]
> You would need an errorbar-kwargs dictionary, and that is a clunky API

Absolutely. I'm sure there must be a better way, but I currently can't think of one that would keep the refactor lightweight.

**Comment by jklymak** [comment]
You can have concise or flexible, but not usually both. In this case I think it makes sense for the two sets of artists to have their own methods.  Users and/or downstream libraries are always welcome to make their own wrappers....

**Comment by timhoffm** [comment]
I agree with @jklymak's analysis. Adding error-bar functionality to these plotting functions directly would bloat the API too much.

As API lead, I'll take the authority to close this.

@neutrinoceros anyway thanks for the proposal. User feedback is always welcome.

**Comment by neutrinoceros** [comment]
I understand, thanks for stepping in.
