### ISSUE TITLE
Axes3D with PolyCollection broken

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#186]
[Original report at SourceForge, opened Wed Jan 12 16:21:04 2011](https://sourceforge.net/tracker/?func=detail&aid=3156579&group_id=80706&atid=560720)

There seems to be a regression within mpl_toolkits.mplot3d.Axes3D: it works flawless to plot a set of polygons in 2D but stacking these in 3D fails for two reasons:
* the polygons are created wrongfully, with an extra line from the last vertice back to the origin,
* the stacking is wrong.

See attached file for demonstration.

### SourceForge History

* On Wed Jan 12 16:21:04 2011, by danielmader: File Added: 398526: mpl3D.py

**Comment by WeatherGod** [comment]
This should have been fixed when #4784 was fixed a while ago. Since we lost the original script, I can't confirm this one way or another, but I believe we are now always respecting the Path codes.
