### ISSUE TITLE
Support making movies from saved images

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#18613]
`MovieWriter` already has all the needed pieces, should "just" be enough to add an API (function, static method, not sure at the moment) that takes a list of filenames/`Path`s as source, and a destination filename/`Path`.

**Comment by timhoffm** [comment]
While we might be able to do this with less or more effort, this is not a core functionality for Matplotlib.

In the same sense, we don't offer image up-/down-sampling, which we basically could through our interpolation methods.

Not finally saying, we shouldn't do this. But at least consider making this a tiny standalone package depending on Matplotlib.

**Comment by story645** [comment]
I think that sorta exists in the form of https://pypi.org/project/gif/

**Comment by dopplershift** [comment]
I disagree. 

Currently, we support making a movie from `Figure` + collection of `Artists`, during which we internally generate a bunch of PNGs (potentially on disk).

We have many users who, for a variety of reasons including where a lot of data are involved and using `ArtistAnimation` would hold onto too much data, prefer to save their frames manually and then create a movie, rather than use the `Animation` classes. What I'm proposing is to allow them to access the process we're already doing and use it when they've manually already taken care of creating an image/frame from the `Figure`. To me it doesn't make sense to allow the former case and explicitly say we're not going to handle the latter--especially when there are quite normal use cases that are not met by what we already support.

**Comment by timhoffm** [comment]
Well, I don't have a strong opinion on this. if you think it's useful and fits in the scope of our functionality and API, go for it.

**Comment by jklymak** [comment]
I think it is outside scope.  Matplotlib makes a bunch of pngs, and then there are infinite options for making them an infinite number of movie formats.  I don't see the appeal of gatekeeping all those.

**Comment by story645** [comment]
I agree w/ @dopplershift that it'd be good to have inside mpl
 For me mostly in an I'd love to be able to use this to pull in pngs made in parallel that I could then wrap w ani.to_jshtml() to have an interactive movie.
