### ISSUE TITLE
Returning bytes data from savefig

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18614]
### Problem

#6909 is a PR, abandoned by the original author, that made `bytestring = fig.savefig(None, **kwargs)` equivalent to `import io; buf = io.BytesIO(); fig.savefig(buf, **kwargs); bytestring = buf.getvalue()` which is in itself a handy simplification.  I think there was general agreement about the feature, it just needs some tests (which should be made simpler than in the original PR -- that was one of the remaining sticky points, I think).

### Proposed Solution

Revive #6909.

**Comment by hs2361** [comment]
The current way of saving the figure as a byte string is by using None as the file name, correct? The original PR wanted to add a new method (to_bytes or write_bytes) to the fig object to make this conversion more explicit? I'm new to the community, so I would be grateful if you could give me some more guidance.

**Comment by jklymak** [comment]
No thats backwards.  `None` was the proposed way to do that.  The current way is to make a BytesIO buffer and write to that instead of a disk buffer..

**Comment by hs2361** [comment]
> No thats backwards. `None` was the proposed way to do that. The current way is to make a BytesIO buffer and write to that instead of a disk buffer..

Ok, so instead of making a new method on the fig object, you're proposing that whenever `None` is entered as the file name, it savefig should return a bytes string. Is that correct?

**Comment by jklymak** [comment]
Thats my understanding, but of course you should check the PR details.

**Comment by hs2361** [comment]
@tacaswell is of the opinion that we shouldn't change the return type of the `savefig` method simply based on an input type or a kwarg (refer to [this comment](https://github.com/matplotlib/matplotlib/pull/6909#issuecomment-238072758)). He suggested that we could add it as a separate function rather than adding another method to `Figure`.

**Comment by jklymak** [comment]
... keep reading 😉

**Comment by hs2361** [comment]
Oh alright, @tacaswell in this comment (https://github.com/matplotlib/matplotlib/pull/6909#issuecomment-239988278) said that he thinks using `None` as the file name should return a bytestring. I will try to re-implement what was done in the PR then, if that's alright?

**Comment by jklymak** [comment]
@hs2361 I think that would be fine.  I don't personally need this feature, but sounds like @anntzer thinks it would be useful?

**Comment by hs2361** [comment]
> @hs2361 I think that would be fine. I don't personally need this feature, but sounds like @anntzer thinks it would be useful?

@anntzer also mentioned simplifying the tests. @efiring mentioned in the comments for the PR that the tests were unnecessarily complex for the code being added in.

**Comment by timhoffm** [comment]
We decided against this API. See https://github.com/matplotlib/matplotlib/pull/18768#issuecomment-721392284
