### ISSUE TITLE
tight_layout / constrained_layout now working properly with configure subplots dialog from toolbar

### ISSUE THREAD

**Issue by Stassels** [matplotlib/matplotlib#18632]
**Bug summary**
When creating embedded plot in Qt, I want my plots to be shown nicely without too much white space around plots/subplots for various screen resolutions. (different PC's). For that I can use tight_layout or constrained_layout that are working as expected.
But then, when I open configure subplots dialog from toolbar, it's not working properly. With tight_layout, changing the parameters results in no change. For constrained_layout, parameters shown when opening dialog are different than the actual layout. Change one even slightly changes whole position of axes.

**Code for reproduction**

```python
import sys
from PySide2 import QtCore, QtWidgets
if QtCore.qVersion() >= "5.":
    from matplotlib.backends.backend_qt5agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
else:
    from matplotlib.backends.backend_qt4agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure

class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self._main = QtWidgets.QWidget()
        self.setCentralWidget(self._main)
        layout = QtWidgets.QVBoxLayout(self._main)

        canvas = FigureCanvas(Figure(constrained_layout=True))
        layout.addWidget(canvas)
        layout.addWidget(NavigationToolbar(canvas, self._main))

        self.ax = canvas.figure.subplots(2, 2)
        canvas.draw_idle()

if __name__ == "__main__":
    # Check whether there is already a running QApplication (e.g., if running
    # from an IDE).
    qapp = QtWidgets.QApplication.instance()
    if not qapp:
        qapp = QtWidgets.QApplication(sys.argv)

    app = ApplicationWindow()
    app.show()
    app.activateWindow()
    app.raise_()
    qapp.exec_()
```

**Expected outcome**
Configure subplots work with tight_layout / constrained_layout properly.

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.3.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7
  * Other libraries: PySide2 5.15.1

**Comment by anntzer** [comment]
This is not dependent on Qt or embedding.  Rather, you should add a single call to `fig.tight_layout()` before drawing; if using `Figure(tight_layout=True)` then Matplotlib *always* triggers a tight_layout upon draw, which discards the settings from the UI (but that's the documented semantics).  For constrained layout the situation is similar; I think you need to call `fig.set_constrained_layout(True); fig.execute_constrained_layout()`, although (ping @jklymak) perhaps it would make sense to support `fig.execute_constrained_layout()` on a figure where `set_constrained_layout(True)` was *not* previously called, and have that just do a single constrained layout now, with no action on future draws?  (i.e. something like `if not self.get_constrained_layout(): disable_later = True; self.set_constrained_layout(True); self.execute_constrained_layout(); if disable_later: self.set_constrained_layout(False)`)

**Comment by jklymak** [comment]
The point of constrained_layout and tight_layout is to automatically set the parameters that the subplot tool tries to set for you.  As such, the subplot tool is ignored by those routines.  tight_layout sets those parameters though, so its results are reflected in the GUI that pops up, and is more compatible.  constrained_layout does not set those parameters, so it is, indeed, completely incompatible.  

I suppose its possible we could post-facto calculate the subplot parameters or some approximation of them after constrained_layout runs, but I'm not really sure what the point would be.  If you are going to mess with the parameters post-facto anyway, might as well start from scratch rather than worrying about what constrained_layout said?  In which case, just turn constrained layout off when opening the subplot tool: `fig.set_constrained_layout(False)`.  I suppose we could do that automatically when the tool is opened, or at least pop up a warning...

**Comment by tacaswell** [comment]
"Use constrained layout to get what the computer thinks is 'best' and then tweak it to what I, as the human, think is right" is a pretty compelling story.

That said, the minimum we should do here is to disable the UI if constrained layout is enabled (as "I wish it worked" is a better bug to have open than "It destroyed my layout" ;) ) .

I apparently do not understand how either subplot params or contrained layout works, can someone point me in the right direction to what (code?) to read to sort that out for my self?

**Comment by tacaswell** [comment]
Given the warning / behavior in the code in https://github.com/matplotlib/matplotlib/blob/9cbb29dc36c747ab9b6dd5c7c7c80ca18e6cda4f/lib/matplotlib/figure.py#L2403-L2442 we probably should post-fact compute an approximation of the values.

**Comment by jklymak** [comment]
The point of constrained layout is that the equivalent of `wspace` is a variable between the columns.  This allows different space for different decorators (i.e. labels or not, and colorbars or not).  So its not possible, except for simple cases, to calculate those values.

**Comment by Stassels** [comment]
Thanks for replies. As @jklymak suggested I disable tight_layout  `fig.set_tight_layout(False)` right before opening configure subplots. Values then are fine and responsive to change. So that works as expected and is good for me.

**Comment by tacaswell** [comment]
Ah, that make sense @jklymak .  Guess we need to disable the adjuster when using constrained layout?  Should we poison the subplot params with nans or something similar?

**Comment by jklymak** [comment]
I guess we could lock folks out from using the subplot tool when constrained layout is True.  It definitely won't do anything and maybe people should be warned.  @Stassels would that have helped you sort this out?   

I guess we could also add a constrained_layout toggle to the subplot tool that blanks out the GUI, toggles tight_layout off, and toggles CL.  If someone opens the subplot tool when CL is active that toggle would be active as well, and the state would be clear?

I'm more skeptical about poisoning the subplotparam values, as someone could be toggling between using constrained layout and not, and may want the subplot params to be persistent across this toggles, even if they do nothing when they have constrained_layout on.
