### ISSUE TITLE
get_ylim() and get_xlim() changing transformations from data to display coordinates

### ISSUE THREAD

**Issue by pmbm95** [matplotlib/matplotlib#18635]
### Bug report

**Bug summary**

"get_ylim()" and "get_yxim()" are changing the result of the transformation from data to display coordinates in matplotlib (I'm using version 3.2.1)
**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

dpi = 80
plt.rcParams.update({'font.size': 12})
fig, ax = plt.subplots(figsize=(1280/dpi, 720/dpi), dpi=dpi)

x = np.arange(200)
y = - 0.1 * x
ax.plot(x, y)

points = ax.transData.transform(np.vstack((x, y)).T).astype(int)
print(points[:5])

ax.get_ylim()

points = ax.transData.transform(np.vstack((x, y)).T).astype(int)
print(points[:5])
```

**Actual outcome**

```
[[ 160   79]
 [1152   23]
 [2144  -31]
 [3136  -87]
 [4128 -142]]
[[205 608]
 [209 605]
 [214 603]
 [218 600]
 [223 598]]
```
**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version:  3.2.1
  * Matplotlib backend : TkAgg
  * Python version: 3.8.2

**Comment by jklymak** [comment]
I think what is happening is automatic limits are evaluated lazily, so before you call `ax.get_ylim()` the ylimits are a default (0, 1).  The first transformation is relative to those being the limits.  When you call `ax.get_ylim()` the proper y limits are set and the transformation returns the positions relative to (-20, 0) (plus a margin).  So, this all makes sense, and is working properly, if a little unexpectedly.  You can prove it to yourself by manually setting ax.set_ylim(-30, 10) or whatever you like, and then see that the transformation doesn't change.

**Comment by tacaswell** [comment]
This is the third or forth issue we have had recently which boils down to:

 - transforms are internally mutable (this is for both efficiency reasons and bookkeeping reasons)
 - we are lazy about making sure the transforms are consistent with the rest of the state of the Figure (and have been getting lazier)

If you want to use transforms for your own purposes outside of the draw process, you need to explicitly trigger a draw before you grab the transform.  

We recently changed a "note box" to a "warning box" in https://matplotlib.org/devdocs/tutorials/advanced/transforms_tutorial.html#sphx-glr-tutorials-advanced-transforms-tutorial-py , but  we probably need to add a simplified version of that warning to the top of both that page and the API docs for transforms.
