### ISSUE TITLE
Time series heat map - new plot type?

### ISSUE THREAD

**Issue by ecotner** [matplotlib/matplotlib#18643]
### Problem

A while back I was working on a project that involves a bit of time series segmentation/clustering, and found it difficult to visualize my clusters in the "standard" way, which involved simply using `plt.plot` for each series in my data set and setting `alpha` to some really low number. I had tens of thousands of such series, and besides taking a long time to run through the loop of plotting some small subsample (plotting everything this way takes an agonizing amount of time), the other major drawback was that apparently there is a lower limit to `alpha` of `1/256`, below which nothing would show up. Even with the setting this low, layering large numbers of time series on top of each other just leads to a solid slab of color that makes it difficult to visualize. Yet another factor is that time series with large slopes (both positive and negative) contribute more heavily than series with small slopes to the color of the plot.

### Proposed Solution

I came up with what I think is a fairly nice solution, which is instead of plotting the time series as stacked line plots, to plot them as 2D histograms where each bin counts the number of (potentially _interpolated_) points that fall in that region. This has a number of advantages:
1. way faster than stacking line plots because there is only a single artist being drawn
2. much more flexible color scheme; colors are automatically normalized or can be changed to represent a log scale, etc.
2. color scheme is actually indicative of the density of points and does not suffer from the bias of time series with high/low slopes

I managed to save the code and kind of forgot about it until now, I have it in a repo [here](https://github.com/ecotner/visualizations/blob/master/timeseries_heatmap/timeseries_heatmap.py). There is probably a good deal of improvement that can be done, especially with regards to interpolation techniques.

### Additional context and prior art

These are some old plots from over a year ago, so I don't have access to the data anymore, but you can probably recreate something similar with the code from the repo linked above. Here are some comparisons of the heat map method (left) and standard stacked line plot (right) on some randomly generated toy data:

![ts_heatmap_comparison_log_scale](https://user-images.githubusercontent.com/10482181/94981910-22653c00-0504-11eb-9e75-01507bae1b3c.png)

![ts_heatmap_comparison](https://user-images.githubusercontent.com/10482181/94981912-25f8c300-0504-11eb-8c3e-7e5f7174e1c9.png)

An example of same data with different color schemes:

![ts_density_color_schemes](https://user-images.githubusercontent.com/10482181/94981941-8851c380-0504-11eb-9f6d-6dbe2f0769c6.png)

And here are some of the clusters that I was able to find in my data set at the time:

![2019-05-21_cluster_time_series_heatmap](https://user-images.githubusercontent.com/10482181/94982072-948a5080-0505-11eb-9f67-31f6b99584c2.png)

Unfortunately I don't think I'm at liberty to divulge what the data actually represents, but it's monthly data, and you can see that there is a bit of interpolation going on between months in order to give it a more "continuous" look.

So, what do you think? Would this be a helpful new plot type? It's basically built on top of pre-existing plot types, so it is probably not too difficult to implement!

**Comment by jklymak** [comment]
Those look great, but I'm not clear on the difference with `hist2d`.  You appear to be interpolating between the points, but I don't understand why.  I'm sure there is a good reason, but its seems too domain specific for general use.

**Comment by ecotner** [comment]
Hey, thanks for the feedback.

So the entire reason for using `hist2d` to create this kind of plot is to get around the downsides I mentioned of applying `plt.plot` to time series data. You're right, it _is_ `hist2d`, but the data you pass in needs to be preprocessed in a nontrivial way (that takes a while to figure out) before `hist2d` is applied.

The reason for the interpolation is because since the data is time series, naturally you want to see how values change from time step to time step, within a single series. The temporal correlation matters. With `plot` you automatically get that because points are connected with lines. If you try to directly plot time series data with `hist2d`, you will essentially just get a sequence of 1d histograms, and all temporal correlation is lost. The interpolation attempts to mimic "connecting the dots" of the time series so that you can see this correlation again.

The utility is definitely specific to working with time series data, but it's not just clustering/segmentation (like I was doing) that would benefit from its use. I would think anyone that has more than a couple thousand time series that they need to visualize would find it useful; I think it could be most generally helpful when doing EDA because you could plot everything at once and then inspect the plot for substructure to identify patterns.

**Comment by jklymak** [comment]
I see, you are including the lines between the dots in the heat map.  This would definitely make a great example.  

I'm not convinced its a necessary feature though.  This is basically just pre-processing the input to hist2d in a specific way.  We are trying to get away from doing processing at the matplotlib level, and leaving that for users and downstream libraries.   

This code is basically just:
```python
t = np.arange(20)
x = np.random.randn(100, 20)
dtfine = 0.1
tfine = np.arange(0, 20, dtfine)
xfine = np.zeros(100, 20/dtfine)
for j in range(100):
   xfine[j] = np.interp(tfine, t, x)
ax.hist2d(tfine, xfine, bins, range)
```
which doesn't seem to require any matplotlib internals to implement.

**Comment by ecotner** [comment]
Yeah I see what you mean... Do you think maybe a library like `pandas` that has more of a focus on time series might be a better such downstream library?

Also, by "This would definitely make a great example", do you mean add it to the gallery in the documentation website?

**Comment by jklymak** [comment]
I think an example would be great for matplotlib's example page.  Whether it fits into one of the downstream packages like pandas or seaborn I'm not sure.

**Comment by ecotner** [comment]
Ok, how exactly would I do that? Do I just drop a script in `examples/misc`?

**Comment by jklymak** [comment]
I'd put it in `examples/statistics`, but there are a few places it could go.  I would encourage you to use `np.interp` rather than essentially coding it yourself.
