### ISSUE TITLE
Inconsistent setting of axis limits with autoscale=False

### ISSUE THREAD

**Issue by sbitzer** [matplotlib/matplotlib#18662]
### Bug report

**Bug summary**

When setting `ax.set_autoscaley_on(False)` before a call to `ax.get_ylim()`, y-limits are set to the default [0, 1] despite data already being drawn outside this range while without setting autoscale to False all data would be displayed properly. Matplotlib appears to mix up the order of the given instructions.

**Code for reproduction**

```python
_, axes = plt.subplots(2, 1, sharex=True)

for ax, pdata in zip(axes, [data[:, :3], data[:, 3:]]):
    ax.plot(pdata, lw=1)
    ax.set_autoscaley_on(False)
    l, = ax.plot([500, 500], ax.get_ylim(), 'k')
    
_ = ax.set_ylim(-3, 3)
```

**Actual outcome**
![grafik](https://user-images.githubusercontent.com/320128/95095738-b6fdb300-072b-11eb-888a-ecfb30897f37.png)

**Expected outcome**
(without `_ = ax.set_ylim(-3, 3)`)
![grafik](https://user-images.githubusercontent.com/320128/95096099-24a9df00-072c-11eb-91ef-63c0fd4c258b.png)

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.3.1, 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): notebook, qt5, inline
  * Python version: 3.8, 3.7
  * Jupyter version (if applicable): 1.0.0, notebook 6.1.4

**Comment by jklymak** [comment]
autolimits are now set lazily, i.e. they won't be set until a draw takes place.  If you want the limits to be set for the current artists, I think you can just call `ax.relim()`.

**Comment by sbitzer** [comment]
Thanks, good to know, but `relim` doesn't do the job, as the following
```python
_, axes = plt.subplots(2, 1, sharex=True)

for ax, pdata in zip(axes, [data[:, :3], data[:, 3:]]):
    ax.plot(pdata, lw=1)
    ax.relim()
    ax.set_autoscaley_on(False)
    ax.relim()
    l, = ax.plot([500, 500], ax.get_ylim(), 'k')
    
_ = ax.set_ylim(-3, 3)
```

still produces

![grafik](https://user-images.githubusercontent.com/320128/95174975-148d1080-07bb-11eb-9066-f00805c6b505.png)

I also tried to put `plt.draw()`, or `plt.show()` in there without effect.

**Comment by jklymak** [comment]
Just to explain, autoscaling is expensive, so we don't keep doing it every time an artist is added.  if you set `autoscaley` to False before calling `autoscale_view`, then you don't get an autoscale.  This is working properly.  OTOH if it could have been more clear in the docs, suggested improvements are always welcome.

**Comment by jklymak** [comment]
Let us know if #18671 would be an improvement.

**Comment by jklymak** [comment]
BTW, presumably you know about `axvline` and that this song and dance is not necessary?

**Comment by jklymak** [comment]
Even simpler, calling `get_ylim` will do the autolim for you:

```python
import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(2, 1, sharex=True)

for i in range(2):
    ax = axes[i]
    ax.plot(np.random.randn(1000), lw=1)
    l, = ax.plot([500, 500], ax.get_ylim(), 'k')
    ax.set_autoscaley_on(False)

ax.set_ylim(-3, 3)
plt.show()
```

**Comment by sbitzer** [comment]
> 
> 
> BTW, presumably you know about `axvline` and that this song and dance is not necessary?

Actually, no! This certainly does much more elegantly what I want.

The clarification in the docs on autoscale is also good. I wondered whether a note on lazy evaluation of limits should also be added to get_ylim, but as a call of this appears to trigger the evaluation of limits, this won't be necessary.

In summary:
- I was confused by lazy evaluation of automatic axis limit rescaling
- due to lazy evaluation autoscale=False before any call to `fig.canvas.draw()`, or `ax.autoscale_view()` will leave
  limits at default (0, 1) despite earlier calls to plotting functions
- autoscale docs will now mention the dependence of autoscale on draw events or call to `autoscale_view()`

The only bit remaining unclear to fully understand the autoscaling of axis limits is now:
- When does matplotlib internally trigger `fig.canvas.draw()`, or `ax.autoscale_view()`?
