### ISSUE TITLE
3D Graph In Matplotlib

### ISSUE THREAD

**Issue by imsanjoykb** [matplotlib/matplotlib#18660]
```
fig = plt.figure(figsize= (10,6))

ax = plt.axes(projection = '3d')

zline = np.linspace(0, 15, 1000)
xline = np.sin(zline)
yline = np.cos(zline)

ax.plot3D(xline, yline, zline, 'red')
```
![matplotlib](https://user-images.githubusercontent.com/40058484/95065231-a7b14200-06f8-11eb-8701-4482613b16f7.PNG)

**Comment by WeatherGod** [comment]
Are you reporting a bug in our documentation somewhere? It is not clear what this issue is being opened for.

**Comment by y1s1h1** [comment]
Hey !
Is this issue still open?

**Comment by WeatherGod** [comment]
So far, no issue has even been identified. We are waiting for clarification.

**Comment by jklymak** [comment]
Feel free to request a reopen if more info is forthcoming.

**Comment by imsanjoykb** [comment]
Problem Solved.
