### ISSUE TITLE
CPython 3.9 wheels

### ISSUE THREAD

**Issue by frenzymadness** [matplotlib/matplotlib#18677]
### Describe the issue

Hello. Could you please release CPython 3.9 manylinux wheels on PyPI?

Python 3.9.0 final was released this week: https://www.python.org/downloads/release/python-390/

Thank You.

**Comment by QuLogic** [comment]
This won't be useful until our dependencies have wheels.

**Comment by tacaswell** [comment]
We are aware of the need for wheels, we will get them up when we can.  Closing this issue as we do not need to track this.

**Comment by hroncok** [comment]
> This won't be useful until our dependencies have wheels.

kiwisolver and numpy have wheels now.

**Comment by hroncok** [comment]
> Closing this issue as we do not need to track this.

I ma a bit confused. Where is the proper place to track this?
