### ISSUE TITLE
QT backend changes locale

### ISSUE THREAD

**Issue by phillipberndt** [matplotlib/matplotlib#1867]
I originally filed this as a bug against IPython, see https://github.com/ipython/ipython/issues/3103

At some point, the QT backend calls setlocale() to localize the program. This leads to problems with other Python libraries relying on the default setting "C", especially in the parsing of floating point numbers: In Germany, we use "," as a decimal separator. In my case, I tried to use Cantera, a chemical kinetics library, which, due to the wrong locale setting, effectively floor()ed all numbers and produced lots of errors. See the bug report over at IPython for details.

Testcase:

``` python
>>> from ctypes import CDLL, c_char_p
>>> setlocale = CDLL("libc.so.6").setlocale
>>> setlocale.restype = c_char_p
>>> locale = lambda: setlocale(0, 0)
>>> locale()
'C'
>>> import matplotlib
>>> matplotlib.use('Qt4Agg')
>>> from pylab import *
>>> locale()
'C'
>>> plot(1, 2)
[<matplotlib.lines.Line2D object at 0x37d7090>]
>>> locale()
'de_DE.UTF-8'
```

It clearly is QT which calls setlocale:

``` python
>>> # Define locale() as above
>>> import qt
>>> a = qt.QApplication()
>>> a = qt.QApplication([])
>>> w = qt.QWidget()
>>> w.show()
>>> locale()
'de_DE.UTF-8'
```

I however still suggest you to store the old `setlocale(0)` value before initializing QT and restore it using `setlocale(0, foo)` afterwards: If I write a script using a toolkit like QT, I expect it to mess with my environment. When I use a plotting module which does all the magic in the background, I do not. Alternatively, please put a warning somewhere, in large, friendly letters ;-)

**Comment by pitrou** [comment]
Related issue: https://github.com/numba/numba/issues/1569

**Comment by mdboom** [comment]
Yeah -- I suppose it's fairly rare to run libllvm in a GUI application so this never got tested.
