### ISSUE TITLE
pyplot.contour() uses wrong linestyle under certain circumstances

### ISSUE THREAD

**Issue by mhabedan** [matplotlib/matplotlib#18681]
### Bug report

**Bug summary**

When drawing a contour with pyplot.contour() and giving two levels, the lower being below any appearing height value, the higher-level contour is drawn with the lower-level linestyle.

In the example below, a mesh is filled with the values 1 and 0.93. Contours shall be drawn at the 0.68 (dashed) and 0.95 (solid) level. Due to the choice of values in the mesh, only the contour at level 0.95 is expected to appear. It does, but it is dashed instead of solid.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt


delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z = np.ones(shape=(len(x), len(y)))
for i in range(len(Z)):
        for j in range(len(Z[0])):
                if i<j: continue
                Z[i, j] = 0.93

fig, ax = plt.subplots()
ax.pcolormesh(X, Y, Z.T)
ax.contour(X, Y, Z.T, levels=[0.68, 0.95], linestyles=["dashed", "solid"], colors="white")
plt.show()
```

**Actual outcome**

The MWE gives the following output:
![image](https://user-images.githubusercontent.com/67378401/95343711-21902980-08b9-11eb-93fb-01e7f0dd83ed.png)
We get the diagonal that is expected but it is dashed, marking the 0.68-level, instead of solid which would mark 0.95.

**Expected outcome**

The MWE works also with Python 3.8.2/ Matplotlib 3.1.2. There it gives the following result which seems correct (the diagonal being solid now):
![image](https://user-images.githubusercontent.com/67378401/95343481-e261d880-08b8-11eb-905e-6ee3b4cee86b.png)

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 2.2.5
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.18rc1

Matplotlib as installed within Ubuntu 20.04 by default.

**Comment by tacaswell** [comment]
Unfortunately, there are currently no plans to to another 2.2.x release.  Given that it works on 3.1 (which we also do not plan to release any more bug-fix releases for), I think we should close this with no action as "already fixed".

**Comment by jklymak** [comment]
Closing, unless there is a massive uprising demanding we extend py2 support even longer.
