### ISSUE TITLE
add a `dlines` method to matplotlib.axes.Axes allowing plotting any (diagonal) lines, not just horizontal or vertical

### ISSUE THREAD

**Issue by yportier** [matplotlib/matplotlib#18692]
### Problem
`matplotlib.axes.Axes.hlines` and `matplotlib.axes.Axes.hlines` are two very similar methods for drawing horizontal and vertical lines and could be thought of being special case implementations of a more general `matplotlib.axes.Axes._lines` method which would draw "diagonal" lines. This generic method however, does not exist.  

### Proposed Solution
* Add a `matplotlib.axes.Axes.dlines` which will allow drawing any line
* Optionnally, rewrite `hlines` and `vlines` to delegate plotting to `dlines`, making them effectively special cases of a generic function

### Possible implementation

A possible implementation could be as below.  
Note: I am unsure I fully understand the use of the `_preprocess_data` decorator's  `label_namer` keyword, so I have left it out.

```
@_preprocess_data(replace_names=["xmin", "xmax", "ymin", "ymax", "colors"])
def dlines(self, xmin, ymin, xmax, ymax, colors=None, linestyles='solid', label='', **kwargs):
    """
    Plot lines from *xmin*, *ymin to *xmax*, *ymax*.

    Parameters
    ----------
    xmin, ymin : float or array-like
        Respective x and y of each line's beginning.
        
    xmax, ymax : float or array-like
        Respective x and y of each line's end.

    colors : list of colors, default: :rc:`lines.color`

    linestyles : {'solid', 'dashed', 'dashdot', 'dotted'}, optional

    label : str, default: ''

    Returns
    -------
    `~matplotlib.collections.LineCollection`

    Other Parameters
    ----------------
    **kwargs :  `~matplotlib.collections.LineCollection` properties.

    See Also
    --------
    hlines : horizontal lines
    vlines : vertical lines
    """

    # We do the conversion first since not all unitized data is uniform
    # process the unit information
    self._process_unit_info(xdata=[xmin, xmax], ydata=[ymin, ymax], kwargs=kwargs)
    xmin = self.convert_xunits(xmin)
    xmax = self.convert_xunits(xmax)
    ymin = self.convert_yunits(ymin)
    ymax = self.convert_yunits(ymax)

    if not np.iterable(xmin):
        xmin = [xmin]
    if not np.iterable(xmax):
        xmax = [xmax]
    if not np.iterable(ymin):
        ymin = [ymin]
    if not np.iterable(ymax):
        ymax = [ymax]

    # Create and combine masked_arrays from input
    xmin, xmax, ymin, ymax = cbook._combine_masks(xmin, xmax, ymin, ymax)
    xmin = np.ravel(xmin)
    xmax = np.ravel(xmax)
    ymin = np.ravel(ymin)
    ymax = np.ravel(ymax)
    
    size = max(len(xmin), len(xmax), len(ymin), len(ymax))

    masked_verts = np.ma.empty((size, 2, 2))
    masked_verts[:, 0, 0] = xmin
    masked_verts[:, 0, 1] = ymin
    masked_verts[:, 1, 0] = xmax
    masked_verts[:, 1, 1] = ymax

    lines = mcoll.LineCollection(masked_verts, colors=colors, linestyles=linestyles, label=label)
    self.add_collection(lines, autolim=False)
    lines.update(kwargs)

    if size > 0:
        minx = min(xmin.min(), xmax.min())
        maxx = max(xmin.max(), xmax.max())
        miny = min(ymin.min(), ymax.min())
        maxy = max(ymin.max(), ymax.max())

        corners = (minx, miny), (maxx, maxy)
        self.update_datalim(corners)
        self._request_autoscale_view()

    return lines
```

**Comment by jklymak** [comment]
Pretty sure this is already implemented as ax.axline.  Thanks for the suggestion though!

**Comment by WeatherGod** [comment]
https://matplotlib.org/3.3.1/users/whats_new.html#new-axes-axline-method

**Comment by timhoffm** [comment]
While `axline()` draws a single line, this draws a line collection. Analogous to `axhline()` vs `hlines()`. So this has some justification.

**Comment by yportier** [comment]
aren't `axline` drawing infinite lines ? this is not what I was proposing

**Comment by jklymak** [comment]
If these are meant to be finite lines, then I don't understand the advantage over the *much* more general `plot(x, y)`.

**Comment by yportier** [comment]
plot(x, y) will plot one line but not a collection of them, right ? it's convenient to draw many lines in one go with `hlines` and `vlines`, but we are forced to choose between horizontal or vertical, why not allow any line ?

**Comment by jklymak** [comment]
`plot` will create as many lines as you have rows in y.  It has the added advantage that you don't need to specify a different x for each column (though you can if you want).  

```python
import matplotlib.pyplot as plt
import numpy as np

ymin = np.array([1, 2, 3])
ymax = np.array([2, 4, 1])

x = np.array([1, 2])
y = np.vstack((ymin, ymax)).T

fig, ax = plt.subplots()
aa = ax.plot(x.T, y.T, color='blue')
```

So, the only substantive difference I'm seeing is that the three lines are not packed in a single collection.  Someone would have to argue pretty hard that having them in a collection is somehow a lot better to make it worth expanding the API.

**Comment by jklymak** [comment]
^ sorry, the above needs some editing, but github seems to be having issues.  But you get the idea.

**Comment by yportier** [comment]
Fair enough, I didn't realize this was possible with plot... my bad for not catching this in the docs:
> They can also be scalars, or two-dimensional (in that case, the columns represent separate data sets).

Thanks for your consideration.

**Comment by jklymak** [comment]
Well, again, thanks for the suggestion and interest in helping!
