### ISSUE TITLE
Projecting Contours Using 3D API Draws Weird Thin Strip Or Raises ValueError

### ISSUE THREAD

**Issue by ellabebop** [matplotlib/matplotlib#18695]
This case is similar to [this](https://matplotlib.org/gallery/mplot3d/contour3d_3.html) 3D example from the docs, but with a point cloud instead of sampling a smooth surface. The example projects 2D contours onto each of the three coordinate planes.  When I try doing the same onto the other two planes, I get either a weird contour collapsed down to a thin strip floating above the axes, or a `ValueError`.  This shows the weird contour,

![](https://i.stack.imgur.com/Ekw9d.png)

and here's the exception.  Between the two, the exception happens on about 95% of all runs.

    Traceback (most recent call last):
      File ".../matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
        self.draw()
      File ".../matplotlib/backends/backend_agg.py", line 433, in draw
        self.figure.draw(self.renderer)
      File ".../matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File ".../matplotlib/figure.py", line 1475, in draw
        renderer, self, artists, self.suppressComposite)
      File ".../matplotlib/image.py", line 141, in _draw_list_compositing_images
        a.draw(renderer)
      File ".../mpl_toolkits/mplot3d/axes3d.py", line 281, in draw
        reverse=True)):
      File ".../mpl_toolkits/mplot3d/axes3d.py", line 280, in <lambda>
        key=lambda col: col.do_3d_projection(renderer),
      File ".../mpl_toolkits/mplot3d/art3d.py", line 226, in do_3d_projection
        self._segments3d]
      File ".../mpl_toolkits/mplot3d/art3d.py", line 225, in <listcomp>
        proj3d.proj_trans_points(points, renderer.M) for points in
      File ".../mpl_toolkits/mplot3d/proj3d.py", line 188, in proj_trans_points
        xs, ys, zs = zip(*points)
    ValueError: not enough values to unpack (expected 3, got 0)

Here's an example of the problem. This version works. Uncomment one or both of the calls to `ax.contour()` in the `plot()` function to see the weird contours, or more likely, the exception.

``` python
import math
import sys
import matplotlib as mpl
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d
import numpy as np
import scipy.spatial

#np.random.seed(4)
numPts = 1000                                       # number of points in cloud
scatter = False                         # adds scatter plot to show point cloud


def main():
    (pts, f) = mkData()                                # create the point cloud
    tris = mkTris(pts)                                         # triangulate it
    plot(pts, tris, f)                                                # plot it


def plot(pts, tris, f):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    cmap = plt.get_cmap("coolwarm")

    collec = ax.plot_trisurf(tris, pts[:, 2], cmap=cmap)
    colors = np.mean(f[tris.triangles], axis=1)
    collec.set_array(colors)
    collec.autoscale()

    (xr, yr, zr, xMin, yMin, zMin, zMax) = resample(ax, tris, f)
    ax.set_zlim(zMin, zMax)      # default always includes zero for some reason

    #
    # Uncomment one or both of these lines to see the problem.
    #
    ax.contour(xr, yr, zr, 10, zdir="z", cmap=cmap, offset=zMin)
    #ax.contour(xr, yr, zr, 10, zdir="x", cmap=cmap, offset=xMin)
    #ax.contour(xr, yr, zr, 10, zdir="y", cmap=cmap, offset=yMin)

    if scatter:
        ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2], alpha=0.1)

    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")
    fig.colorbar(collec, shrink=0.5, aspect=5)
    plt.show()


def mkData():
    """
    Create a random point cloud near a random plane, and define a function on
    the plane for colors and contours.
    """
    offset = 1                   # generate points near a unit square, xy-plane
    pts = 2 * np.random.rand(numPts, 3) - 1
    pts[:, 2] = offset * (2 * np.random.rand(numPts) - 1)

    x = 2 * np.ravel(pts[:, 0])
    y = 2 * np.ravel(pts[:, 1])
    f = x * np.exp(-x**2 - y**2)      # just some function for colors, contours

    width = 100                       # scale unit square to a larger rectangle
    height = 20
    pts[:, 0] *= width
    pts[:, 1] *= height

    (e1, e2, e3) =[2 * np.pi * np.random.rand() for _ in range(3)]
    (c1, s1) = (math.cos(e1), math.sin(e1))           # rotate scaled rectangle
    (c2, s2) = (math.cos(e2), math.sin(e2))
    (c3, s3) = (math.cos(e3), math.sin(e3))
    Ta2b = np.array((                     # do not have scipy.spatial.transform
        [               c1  *c2,       s2,              -s1 * c2],
        [s1 * s3 - c1 * s2 * c3,  c2 * c3, c1 *s3 + s1 * s2 * c3],
        [s1 * c3 + c1 * s2 * s3, -c2 * s3, c1 *c3 - s1 * s2 * s3]))

    pts = (Ta2b @ pts.T).T

    dist = 500                                 # translate away from the origin
    Ra2bNb = dist * (2 * np.random.rand(3, 1) - 1)

    pts += Ra2bNb.T

    return (pts, f)


def mkTris(pts):                                  # triangulate the point cloud
    u = np.ravel(pts[:, 0])
    v = np.ravel(pts[:, 1])

    try:
        return mpl.tri.Triangulation(u, v)
    except (ValueError, RuntimeError) as ex:
        sys.exit(f"Unable to compute triangulation: {ex}.")


def resample(ax, tris, f):         # resample triangulation onto a regular grid
    (xMin, xMax) = ax.get_xlim()
    (yMin, yMax) = ax.get_ylim()
    (zMin, zMax) = ax.get_zlim()

    x = np.linspace(xMin, xMax, 30)
    y = np.linspace(yMin, yMax, 30)

    (xm, ym)=np.meshgrid(x, y)

    interp = mpl.tri.triinterpolate.LinearTriInterpolator(tris, f)
    zm = interp(xm, ym)

    return (xm, ym, zm, xMin, yMin, zMin, zMax)

if __name__ == "__main__":
    main()
```

This is with matplotlib 2.2.2 and 3.1.1. Thanks.

Jim

**Comment by QuLogic** [comment]
I'm not sure your resampling is doing what you want. If you print it out, you will find various masked out values, and it is somewhere around ±0.5, _not_ between `zMin` and `zMax`.

**Comment by ellabebop** [comment]
You're exactly right.  The interpolator is producing function values over the triangles, not **z**-coordinates.  I was passing them to `ax.contour()` as if they were coordinates in the problem calls.  To get what I want, I need to interpolate **z**-coordinates too, and pass the right combinations of those to the `ax.contour()` calls.  This was my mistake, not a bug.  Thanks.
