### ISSUE TITLE
Class deprecation machinery and mixins

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18690]
### Bug report

In
```python
@cbook.deprecated("3.4")
class Mixin:
    pass

class Base:
    def __init__(self, x): self.x = x

class Mixed(Mixin, Base):
    pass

Mixed(x=1)
```
the last line raises a rather puzzling
```
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```
because the deprecation machinery grabs `object.__init__` to install the deprecation emitter on `Mixin`.  (This is not a theoretical case, see e.g. #18675.)

There's a few possible solutions:
- "it's too rare, let's not bother"
- forbid deprecation of classes where `__init__` is not defined (which I think is the main failing case)
- make `cbook.deprecated` actually create another class that inherits from `Mixin` and has its own `__init__` (which gets wrapped in `cbook.deprecated()` and just calls `super().__init__`), instead of monkey-patching `Mixin`'s original `__init__`.

**Matplotlib version**

  * Operating system: n/a
  * Matplotlib version: HEAD
  * Matplotlib backend (`print(matplotlib.get_backend())`): n/a
  * Python version: n/a
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
> forbid deprecation of classes where __init__ is not defined (which I think is the main failing case)

Would that raise when I try to deprecate a class? If so, IMHO that's the right amount of effort to put in. The third solution feels a bit over-engineered. And the first might through confusing messages at our users.

**Comment by anntzer** [comment]
Actually I'll take back what I said, we can't just forbid the deprecation of classes with no `__init__`, as they're perfectly fine as long as they're not involved in multiple inheritance, and there's actually cases where we deprecate such classes (e.g. currently `IgnoredKeywordWarning`).

**Comment by timhoffm** [comment]
So maybe just document that the decorator does not work with multiple inheritance? I don't think it's worth adding heavy machinery for this case.
