### ISSUE TITLE
The setting style is not in effect,the color of the histogram is still single blue

### ISSUE THREAD

**Issue by syejing** [matplotlib/matplotlib#18714]
Under jupyter notebook, plt.style.use ('seaborn '), the color of the column in the bar chart will change with the order of the Seaborn color plate. But in the background I wrote, the color of the column in the bar chart is all the default blue. Who can tell me why this is? Big head

**Comment by timhoffm** [comment]
Please provide a minimal example. I cannot follow your description.

**Comment by syejing** [comment]
This is my own backend:
`
import matplotlib
from matplotlib.backend_bases import Gcf
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from kernel.python3.kernel import Kernel
import io
import binascii


def show(*args, **kwargs):
    try:
        for num, figmanager in enumerate(Gcf.get_all_fig_managers()):
            fig = figmanager.canvas.figure

            # build keyword args
            kw = {
                "format": 'png',
                "facecolor": fig.get_facecolor(),
                "edgecolor": fig.get_edgecolor(),
                "dpi": fig.dpi,
                "bbox_inches": 'tight',
            }

            bytes_io = io.BytesIO()
            canvas = FigureCanvas(figmanager.canvas.figure)
            canvas.print_figure(bytes_io, **kw)
            data = bytes_io.getvalue()
            img_data = binascii.b2a_base64(data)
            kernel = Kernel()
            kernel.display_hook({'category': 'image', 'content': img_data.decode()}, False)
    finally:
        if Gcf.get_all_fig_managers():
            matplotlib.pyplot.close('all')
`
This is my front-end code:
`
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')
data = pd.read_csv('data.csv', index_col=0, parse_dates=True)
data.head()
data.pct_change().mean().plot(kind='bar',figsize=(10,6))
plt.show()
`

If the line chart is displayed directly, the color of each line is displayed according to the Seaborn color board,such as
`
data.plot(figsize=(10,12), subplots=True)
plt.show()
`

**Comment by syejing** [comment]
I have set the style of Matplotlib, but the style of the rectangle in borcontainer has not changed

**Comment by syejing** [comment]
I understand, plt.legend () found that there is only one legend. The question is why the bar with only one legend in jupyter notebook will automatically change the color of each column in X axis according to the Seaborn color board?

**Comment by syejing** [comment]
I feel that this is what jupyter notebook has done secretly, not Matplotlib

**Comment by syejing** [comment]
`
color_palette_sns = plt.rcParams['axes.prop_cycle'].by_key()['color']
data.pct_change().mean().plot(kind='bar',figsize=(10,6), color=color_palette_sns)
plt.show()
`

This is the solution to the problem
