### ISSUE TITLE
Tick formatting issues on horizontal histogram with datetime on 3.3.2

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#18717]
### Bug report

**Bug summary**

Ticks are not correctly formatted when passing `orientation='horizontal'` to ``plt.histogram`` when the values are of type datetime.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
plt.hist(np.random.randint(0, 10000, size=300).astype('datetime64[D]'), orientation='horizontal')
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/449558/95808737-fabf6200-0cc1-11eb-95ce-6bbc5b306aa3.png)

**Expected outcome**
xticks are not formatted as dates (they are counts), yticks are formatted at dates (they are bins).

Installed from pypi.

Something seems to be happening here: https://github.com/matplotlib/matplotlib/blob/5cc6a15cc2958c07a30d100ebb602da848a62843/lib/matplotlib/axes/_axes.py#L6509

But I didn't properly follow it.

**Comment by timhoffm** [comment]
Thanks for the report. This is broken on 3.2.2 but works on master:

![grafik](https://user-images.githubusercontent.com/2836374/95913235-37fc2080-0da4-11eb-868d-68470f36377a.png)

There have been some unit-handling changes recently. I assume that they have fixed the issue en-passant.

**Comment by amueller** [comment]
thank you!
