### ISSUE TITLE
Use Axes instead of axes in the docs.

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#18726]
### Problem

From https://github.com/matplotlib/matplotlib/pull/18707#discussion_r504403247:

Using lower-case "axes" in docstrings such as
~~~
Return whether any artists have been added to the axes.
~~~
 is slightly ambiguous due to Axes being a special concept in Matplotlib not matching the plain english meaning.

### Suggested Improvement

Always use "Axes" when referring to an `Axes` but not wanting to link to the class, .i.e.
~~~
Return whether any artists have been added to the Axes.
~~~

*Note:* This is a different compared to "figure".

Cases that should not become uppercase, include in particular
- "axes" as a simple plural of axis
- compound words like "axes space", "axes coordinates"

**Comment by jhalak27** [comment]
Hey, I am new here. Is this issue still open?

**Comment by timhoffm** [comment]
Yes it is. You oared welcome to pick it up if you like.

**Comment by jhalak27** [comment]
Could you let me know which `axes` should I change? Bit confused.

**Comment by timhoffm** [comment]
There's an ambiguity:

- "axes" as plural of axis; e.g. the docstring of [get_autoscale_on()](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.get_autoscale_on.html)
- "axes" referring to an instance of the class [Axes](https://matplotlib.org/api/axes_api.html?highlight=axes#the-axes-class), which is a central concept in Matplotlib. e.g. the docstring of [get_title()](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.get_title.html).

All latter usages in docstrings should be changed to "Axes".

Note: This is a tedious task. "axes" is probably one of the most used words in docstrings, and it's also often used in code. I strongly suggest to use advanced searching methods to find possible candidates. E.g. PyCharm supports limiting the search to string-literals. Additionally I suggest, searching case-sensitvie and whole words. We only want to change plain text, no markup such as `` `~.axes.Axes.scatter` `` or `` `~.floating_axes.GridHelperCurveLinear` ``, so it might be good to actually search for " axes" (including the leading space). That's for narrowing down possible candidates. Each of the results must then be investigated which of the above two categories it belongs to.

That said, you don't have to do the whole library. It's ok to start with one or a few modules.

**Comment by jklymak** [comment]
I'm totally for enforcing this when docs get changed; I'm somewhat more ambivalent about the cost/benefit of a big search-and-replace PR that engenders many rebases.

**Comment by timhoffm** [comment]
If we don't search/replace, the policy is effectively useless as only a negligible fraction of docstrings will be changed. Then we could just leave this and not bother at all.

**Comment by jklymak** [comment]
Well, maybe it'd be useful to start with a few modules first.  I.e. if all of `_axes.py` were done that would go a long way to making the world more consistent.
