### ISSUE TITLE
No coordinates after set_ticklabels()

### ISSUE THREAD

**Issue by KCrux** [matplotlib/matplotlib#18727]
### Bug report

**Bug summary**

After changing the ticklabels of an axis, the coordinates (in the toolbar) of this axis are no longer displayed. 

In the following example no y coordinate (in the toolbar) will be displayed, only the x coordinate.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

x = [1, 2, 3]
y = [1, 2, 0]

ax.plot(x, y)

yticks = [0, 1, 2]

ax.set_yticks(yticks)
ax.set_yticklabels(yticks)

plt.show()
```

**Matplotlib version**

  * Operating system: Windows10
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.9
  * Jupyter version (if applicable):
  * Other libraries: 

Downloaded fresh Python 3.7.9 from their webside. Installed matplotlib with pip.

**Comment by timhoffm** [comment]
By setting explicit ticklabels, they are treated as arbitrary strings, which we do not show because there is generally no order and no "in-between" values for arbitrary strings.  That the label corresponds to the value is now a coincidence of your implementation.

You might want to use a Locator instead to define the tick positions. See

- https://matplotlib.org/3.3.2/api/ticker_api.html#tick-locating-and-formatting
- https://matplotlib.org/3.3.2/gallery/ticks_and_spines/tick-locators.html

**Comment by KCrux** [comment]
Thanks @timhoffm for the fast feedback.

Sure there can't be an order. 
I expected that the labels are just ordinary labels and the coordinates continue to use the ticks.

In my case the labels just give improved information about the ticks while the tick positions are still relevant. Seems like this may not be possible to realize.

**Comment by jklymak** [comment]
I'm actually not sure I agree with this behaviour.  I think the readout should continue to spit something out even if the ticks are hard-formatted.

**Comment by timhoffm** [comment]
@KCrux you could patch `ax.fmt_ydata = lambda x: f'{x:.3f}'`.

@jklymak What should "something" be by default for a FixedFormatter?

**Comment by jklymak** [comment]
The formatter is just formatting numbers.  "something" should be the numbers in between, even if the format is not quite right.

**Comment by anntzer** [comment]
But what should happen if one sets the labels to `"foo", "bar", "baz"`?

**Comment by timhoffm** [comment]
One *could* show the underlying numerics, because technically, the axis is still continously numeric. But I'm not a big fan of that. Though won't block.

**Comment by jklymak** [comment]
I don't think we should confuse *units*, and in particular *categorical* units with labelling ticks on float axes.  If its units, then we can convert to something the formatter can handle (i.e. if the cursor is closer to "foo" than "bar" we can say "foo").  

If its just a float axis I think we should assume that the data are floats and the user has just chosen to reformat the ticks.  i.e if I set a tick to be `np.pi` and change the label to `$\pi$`, I would still prefer the cursor to keep showing me the floats around pi.

**Comment by anntzer** [comment]
That seems not unreasonable to me.

**Comment by KCrux** [comment]
@timhoffm thank you for the hint. This 100% solved my problem :-).

For me the intuitive use of ticklabels is to just change the label, not the numerical value. So I would expect the coordinates to further display the numerical value. I may be biased by my current use case.

Ofc there might be cases where users want to display categorical data. In this case you might add a boolean 'categorical'. In this case the categorical data would be displayed as jklymak suggested.

Just my two cents ;-). I'm happy with ````ax.fmt_ydata = lambda x: f'{x:.3f}'```` 👍

**Comment by timhoffm** [comment]
Category formatters behave well and the mouse-coordinates indeed show the nearest category.

On the other hand, `ax.set_yticks([1, 2, 3]); ax.set_yticklabels([1, 2, 3])` creates a `FuncFormatter` with a dict, which only returns values a the exact positions (see also the plot below). @jklymak @anntzer I'm not clear what to do in this case. In principle, it is be the job of the formatter to generate the strings to be displayed.

---

In this plot, the character arrays are data values formatted with the respective axis formatter. I've used dashes to mark positions that were evaluated but the formatter returns an empty string.

![grafik](https://user-images.githubusercontent.com/2836374/96199654-4d19b080-0f58-11eb-9ecc-e25191c331fd.png)


~~~
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.plot(['a', 'b', 'c'], [1, 3, 2])
ax.set_yticks([1, 2, 3])
ax.set_yticklabels([1, 2, 3])

# xaxis: StrCategoryFormatter
ax.set_xlim(-1, 4)
xfmt = ax.xaxis.get_major_formatter()
ax.text(0.5, -0.4, xfmt.__class__.__name__)
for x in np.arange(-1, 4, 0.1):
    ax.text(x, 0, xfmt(x) or '|', ha='center')

# yaxis: FuncFormatter with from dict
#   func = functools.partial(self._format_with_dict, tickd)  # axis.py:1737
ax.set_ylim(-1, 4)
yfmt = ax.yaxis.get_major_formatter()
ax.text(-0.3, 1, yfmt.__class__.__name__, rotation=90)
for y in np.arange(0, 4, 0.1):
    ax.text(0, y, yfmt(y) or '-', va='center')
~~~
