### ISSUE TITLE
ColorbarBase.set_label() kwargs not documented

### ISSUE THREAD

**Issue by johnomotani** [matplotlib/matplotlib#18739]
### Problem

The kwargs of `ColorbarBase.set_label()` are not documented https://matplotlib.org/3.3.2/api/colorbar_api.html#matplotlib.colorbar.ColorbarBase.set_label

### Suggested Improvement

It would be nice if all the kwargs were listed and explained. I only found out that `labelpad` existed through an answer on StackOverflow, and the only way to find out what other arguments there might be seems to be to trawl through the source code...

**Comment by sinAshish** [comment]
Hi, I would like to work on this!

**Comment by tacaswell** [comment]
The kwargs get passed through to either `ax.set_xlabel` or `ax.set_ylabel` (e.g. 
https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html?highlight=set_xlabel#matplotlib-axes-axes-set-xlabel) which in turn pass through to any property of `Text`.

**Comment by oscargus** [comment]
This is currently improved as (have not checked when):

Keyword arguments are passed to [set_xlabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html#matplotlib.axes.Axes.set_xlabel) / [set_ylabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_ylabel.html#matplotlib.axes.Axes.set_ylabel). Supported keywords are labelpad and [Text](https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text) properties.

So I am closing this as completed.
