### ISSUE TITLE
Use range of z values for set_rasterization_zorder

### ISSUE THREAD

**Issue by lsawade** [matplotlib/matplotlib#18742]
### Problem

I already encountered the situation a couple of times that I had a polygon located in a plane below an alpha<1.0, sparse 2d-histogram, which, in turn, was below a set of scattered points. The current implementation of `Axes.set_rasterization_zorder(z)` only allows to make everything rasterized below a certain `zorder`.
The problem is that I don't want the polygon or the scattered data to be rasterized, but only the histogram sandwiched between the two. 

### Proposed Solution

Use `zrange` to rasterize, meaning, the Rasterization range would be, e.g. `zpolygon` < `z` < `zscatter`. 

### Additional context and prior art

I haven't tried to implement it myself, but I assume that it wouldn't be too complicated. That being said, I don't know whether there are some underlying issues in terms of merging Axes elements into one prior to exporting the figures.

**Comment by tacaswell** [comment]
The section of code you would have to change is:

https://github.com/matplotlib/matplotlib/blob/df9223f065a647c4f2da7dfad784a111c25984e0/lib/matplotlib/axes/_base.py#L2814-L2824

So while the code change shouldn't be that bad, I am skeptical of how complex the API for this is going to get.  If we can do one range, would people ask for a second range of rasterized output?

That said, you can call `artist.set_rasterized` on individual artists.  If you set that on each of the patches in the histogram it merge all of the patches into one raster at the correct z-level (I remember there was some recent work on making the merging more expansive, not sure exactly off the top of my head what the minimum version to get this behavior is)

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.scatter(range(5), range(5), zorder=0)
*_, patches = ax.hist(np.random.randn(500), zorder=1)
ax.plot(np.linspace(-2*np.pi, 2*np.pi, 512), np.sin(np.linspace(-2*np.pi, 2*np.pi, 512)))
[p.set_rasterized(True) for p in patches]
fig.savefig('/tmp/test.svg')
```

**Comment by anntzer** [comment]
I agree we should not expand the API on set_rasterization_order and prefer just setting rasterized by looping over the artists.

**Comment by lsawade** [comment]
Sorry for the late answer! I didn't see this until now..

Actually the code you provide, @tacaswell, is actually great and all I need, if that means keeping the API cleaner, I can work with that. It's really just a corner case!

Thank you! Can be closed from my point of view!

Cheers!

**Comment by tacaswell** [comment]
@lsawade Great!

**Comment by DavidRRice** [comment]
Hi, I wanted to put in 2-cents, that I think a minimal and maximum rasterization z-order is appropriate and wouldn't expand the API greatly. It's common to have a lot of data plotted that you want to be rasterized, but you don't want the grid-lines or any elements behind the data to be rasterized.
