### ISSUE TITLE
Pin cheatsheets repository

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#18750]
@tacaswell let's pin the cheatsheets repository at https://github.com/matplotlib.

You may unpin cycler, which is the least used pinned repo.

**Comment by story645** [comment]
@dopplershift & @efiring can also do that!

**Comment by efiring** [comment]
You're right, that was easy.  Done. (I hope the cycler enthusiasts aren't too unhappy; if they are, it's easy to re-pin it.)

**Comment by tacaswell** [comment]
I applied a bit more editorial opinions to the order.

:cry: for cycler.

**Comment by story645** [comment]
@tacaswell pin cycler instead of pytest-mpl?

**Comment by timhoffm** [comment]
Poor cycler. 😿  But it has less forks and less stars than mpl-test. And IMHO testing your figures is a more common problem than wanting fancy cycling.

**Comment by tacaswell** [comment]
Yeah, I agree pytest-mpl is a better thing to pin than cycler (my personal attachment to cycler aside).
