### ISSUE TITLE
Multiple calls of boxplot on the same axis causes overdrawn labels

### ISSUE THREAD

**Issue by francibm97** [matplotlib/matplotlib#18759]
### Bug report

**Bug summary**

When `boxplot` is called multiple times on the same axis with `manage_ticks=True`, ticks and labels can get duplicated and be overdrawn.

I believe this problem to be caused in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L4062-L4072 because there, on the second boxplot call, the new `locs` of the `FixedLocator` and `seq` of `FixedFormatter` are just appended to the previous ones without removing duplicates.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1)
_ = ax.scatter(['a'], [1])
_ = ax.scatter(['a'], [1])
fig.canvas.draw()

print(ax.xaxis.get_ticklabels())
# Returns [Text(0, 0, 'a')] which is ok

fig, ax = plt.subplots(1, 1)
_ = ax.boxplot([1,2,3])
_ = ax.boxplot([5,6,7])
fig.canvas.draw()

print(ax.xaxis.get_ticklabels())
# Returns [Text(1, 0, '1'), Text(1, 0, '1')] which causes overdrawn labels
```

The boxplot above is quite unreasonable, however this problem rises also in saner plots, such as the case of two shared axes with one boxplot each.

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(2, 1, sharex=True)
_ = ax[0].boxplot([1,2,3])
_ = ax[1].boxplot([1,2,3])

fig.canvas.draw()

print(ax[1].xaxis.get_ticklabels())
# Returns [Text(1, 0, '1'), Text(1, 0, '1')]
```

**Expected outcome**

I think that, in the instance of the shared axes, a user should not be required to set `manage_ticks=False` and set the locators and formatters by themselves in order to get the correct result.
But that is debatable, so I actually wonder if this is a bug or intended behaviour.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Sharing an axes means they have the same ticks.  I don't think we should have fancy logic to make sure the user is not duplicating tick labels.  The solution above is not to turn off managing the labels, but to turn off sharing.

**Comment by francibm97** [comment]
Yes you are right, I did not think of that: one can simply turn off sharing and hide the x-axis labels in the top row to achieve the same result that I was thinking about (and that would be a poor visualisation anyways). Thanks!

**Comment by jklymak** [comment]
Well I didn't mean you couldn't advocate for different behaviour, but it's not a bug per-se.  checking for duplicate ticks is possible, but going to lead to all sorts of float round off questions, etc.

**Comment by francibm97** [comment]
Sorry for misinterpreting what you meant and yes, I agree that checking for duplicate ticks is problematic and also it would not be all that useful since these plots are edge cases and a much simpler solution is already available
