### ISSUE TITLE
Should certifi be included in the list of dependencies?

### ISSUE THREAD

**Issue by danielshub** [matplotlib/matplotlib#18762]
### Problem
When trying to start psychopy on Arch Linux and error is thrown because the matplotlib dependency on the certifi package is not installed. This is not surprising since certifi is listed in the requires.txt file in the matplotlib egg-info and the Arch package of matplotlib does not include certifi as a requirement. While certifi appears to be a requirement in setup.py, the installation guide (https://matplotlib.org/users/installing.html#dependencies) does not list it as a dependency

### Suggested Improvement
If certifi is truly a dependency, it should be listed in the documentation

**Comment by timhoffm** [comment]
The other way round. We've removed certifi as a dependency. #18670
