### ISSUE TITLE
Matplotlib 3.0.3 cannot be installed on Mac with Python 3.9

### ISSUE THREAD

**Issue by ArHo420** [matplotlib/matplotlib#18774]
**Code for reproduction**
pip install matplotlib==3.0.3

**Actual outcome**
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-install-k3pk87qd/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-install-k3pk87qd/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-pip-egg-info-m9z40y6h
         cwd: /private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-install-k3pk87qd/matplotlib/
    Complete output (22 lines):
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-install-k3pk87qd/matplotlib/setup.py", line 203, in <module>
        result = package.check()
      File "/private/var/folders/3n/0y9jz6l5433dk95nqmkt6sq00000gn/T/pip-install-k3pk87qd/matplotlib/setupext.py", line 981, in check
        import numpy
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
    
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.9.0 (v3.9.0:9cf6752276, Oct  5 2020,
                            11:29:23)  [Clang 6.0 (clang-600.0.57)]]
                  platform: yes [darwin]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jklymak** [comment]
This is a duplicate: #18711
