### ISSUE TITLE
`FuncAnimation` + save() takes significantly longer to complete with a `figure()` instance vs a `Figure()` one

### ISSUE THREAD

**Issue by SoundSpinning** [matplotlib/matplotlib#18785]
### Bug report

**Bug summary**

`FuncAnimation` (as called from a .save() to a movie command), takes significantly longer to complete when passing a `figure()` instance type vs a `Figure()` one. A lot of testing performed with differently defined animations all show a similar problem, with some tests using `figure()` can take twice as long.

**Code for reproduction**

```python
"""
A simple `FuncAnimation` example: figure() vs Figure() Performance
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from tqdm.auto import tqdm
import time

plt.style.use("ggplot")  # set plot style
fig, ax = plt.subplots() # this creates a figure() instance

x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))

def animate(i):
    line.set_ydata(np.sin(x + i/10.0))  # update the data
    return line,
# Init only required for blitting to give a clean slate.
def init():
    line.set_ydata(np.ma.array(x, mask=True))
    return line,

# Run #1
now = time.time()
ani_f = animation.FuncAnimation(
    fig, animate, tqdm(np.arange(200), initial=1), init_func=init, interval=25, blit=True)
plt.close()

ani_f.save("ani_f.mp4")
end = time.time()
print(f"Run #1: `FuncAnimation` took {(end - now):.3f}s with `figure()`")

# Run #2
fig = plt.Figure() # this creates a Figure() instance
ax = fig.add_subplot()

now = time.time()
ani_F = animation.FuncAnimation(
    fig, animate, tqdm(np.arange(200), initial=1), init_func=init, interval=25, blit=True)
plt.close()

ani_F.save("ani_F.mp4")
end = time.time()
print(f"Run #2: `FuncAnimation` took {(end - now):.3f}s with `Figure()`")
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/12704331/96735327-5faa4480-13b3-11eb-8df2-ba7507a114cd.png)

**Expected outcome**

I expected the same times for both runs: using `figure()` or `Figure()` as input to `FuncAnimation`.

**Matplotlib version**

  * Operating system: Windows 10, 10.0.19041
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.8.6
  * Jupyter version (if applicable): 6.1.4

All installed via `conda` from a `Miniconda3` set up. All packages are installed from `conda-forge` first when available on that channel.

**Comment by jklymak** [comment]
Did you check the output animations?  Neither does what I assume you want...

```python
"""
A simple `FuncAnimation` example: figure() vs Figure() Performance
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time


def animate(i):
    line.set_ydata(np.sin(x + i/10.0))  # update the data
    return line,

x = np.arange(0, 2*np.pi, 0.01)

fig, ax = plt.subplots() # this creates a figure() instance
# Run #1
line, = ax.plot(np.sin(x))
now = time.time()
ani_f = animation.FuncAnimation(
    fig, animate, np.arange(200), interval=25, blit=True)
plt.close()

ani_f.save("ani_f.mp4")
end = time.time()
print(f"Run #1: `FuncAnimation` took {(end - now):.3f}s with `figure()`")


# Run #2
fig = plt.Figure() # this creates a Figure() instance
ax = fig.add_subplot()

line, = ax.plot(np.sin(x))
now = time.time()
ani_F = animation.FuncAnimation(
    fig, animate, np.arange(200),interval=25, blit=True)
plt.close()

ani_F.save("ani_F2.mp4")
end = time.time()
print(f"Run #2: `FuncAnimation` took {(end - now):.3f}s with `Figure()`")
```

Does give me what I assume you want.  

The difference is that the two mp4 files are different sizes.  

I'll close because I don't think there is anything particularly to do here...

**Comment by SoundSpinning** [comment]
Oh, how very clumsy of me, apologies for this. However, your code shows the issue I'm trying to understand: Run#2 with `Figure()` is 14% faster. This issue escalates when you start adding custom settings to the figure and `save()`. Can you please try the code at the bottom, which is just expanded from yours, but with settings closer to the actual application I was originally trying?
When I run it on my PC I get this **output**:
```
Run #1 starts
Run #1: `FuncAnimation` took 32.44s with `figure()`
Run #2 starts
Run #2: `FuncAnimation` took 15.72s with `Figure()`
Run2 vs Run1 time difference:
 `FuncAnimation` took 51.55% less time with `Figure()`.
 So `FuncAnimation` with `Figure()` is 2.06 times faster than with `figure()`.
```
In my actual application I have 1000s of frames to deal with, with several custom settings on different figures plus dpi on save(). **2 x faster with `Figure()`** is a significant issue for large datasets to animate from. I hope now it is more clear why my query. I'm just trying to understand why, so I can set some 'hard wire' animation rules in my main code.
Many thanks for your time.

**Code**
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time

plt.style.use("ggplot")  # set plot style
def animate(i):
    line.set_ydata(np.sin(x + i/10.0))  # update the data
    return line,
x = np.arange(0, 2*np.pi, 0.01)

dpi = 100
figsize = (4, 3)
fontsize = "x-small"
colour = "dimgray"

# Run #1
fig, ax = plt.subplots() # this creates a figure() instance
fig.set_size_inches(figsize)
ax.set_title("Simple sine wave animation", fontsize="medium")
ax.set_xlabel("Time (s)", color=colour, fontsize=fontsize)
ax.set_ylabel("Amplitudes", color=colour, fontsize=fontsize)
ax.tick_params(labelsize=fontsize)
fig.set_tight_layout(True)
line, = ax.plot(np.sin(x))

print("Run #1 starts")
now = time.time()
ani_f = animation.FuncAnimation(
    fig, animate, np.arange(200), interval=25, blit=True)
plt.close()
ani_f.save("ani_fig1.mp4", dpi=dpi)
end = time.time()
time1 = end - now
print(f"Run #1: `FuncAnimation` took {time1:.2f}s with `figure()`")

# Run #2
fig = plt.Figure() # this creates a Figure() instance
ax = fig.add_subplot()
fig.set_size_inches(figsize)
ax.set_title("Simple sine wave animation", fontsize="medium")
ax.set_xlabel("Time (s)", color=colour, fontsize=fontsize)
ax.set_ylabel("Amplitudes", color=colour, fontsize=fontsize)
ax.tick_params(labelsize=fontsize)
fig.set_tight_layout(True)
line, = ax.plot(np.sin(x))

print("Run #2 starts")
now = time.time()
ani_F = animation.FuncAnimation(
    fig, animate, np.arange(200), interval=25, blit=True)
plt.close()
ani_F.save("ani_Fig2.mp4", dpi=dpi)
end = time.time()
time2 = end - now
print(f"Run #2: `FuncAnimation` took {time2:.2f}s with `Figure()`")
print(f"Run2 vs Run1 time difference:\n `FuncAnimation` took {100-(time2*100/time1):.2f}% less time with `Figure()`.\n"
f" So `FuncAnimation` with `Figure()` is {time1/time2:.2f} times faster than with `figure()`.")
```

**Comment by QuLogic** [comment]
I can't reproduce this; in fact it's the opposite:
```
$ python ../mpl-tests/issue18785a.py 
Run #1 starts
Run #1: `FuncAnimation` took 6.21s with `figure()`
Run #2 starts
Run #2: `FuncAnimation` took 7.12s with `Figure()`
Run2 vs Run1 time difference:
 `FuncAnimation` took -14.64% less time with `Figure()`.
 So `FuncAnimation` with `Figure()` is 0.87 times faster than with `figure()`.
```

**Comment by SoundSpinning** [comment]
Thanks for this, good point...
```
ffmpeg                    4.3.1                ha925a31_0    conda-forge
pillow                    8.0.0            py38h1d4d63c_0    conda-forge
```
Have just tried as GIF with `pillow`, and I get near enough the same numbers as with `ffmpeg`.
When I check `animation.writers.list()`:
```
['pillow', 'ffmpeg', 'ffmpeg_file', 'html']
```

However, I've just added to the import lines this:
```
import matplotlib
matplotlib.use("Agg")
```
and I get very different results vs above with `ffmpeg`:
```
Run #1 starts
Run #1: `FuncAnimation` took 20.26s with `figure()`
Run #2 starts
Run #2: `FuncAnimation` took 15.73s with `Figure()`
Run2 vs Run1 time difference:
 `FuncAnimation` took 22.35% less time with `Figure()`.
 So `FuncAnimation` with `Figure()` is 1.29 times faster than with `figure()`.
```
So, `figure()` is faster, and `Figure()` is the same than my 1st check. From 2 x faster to 1.3 times.
Any thoughts? Thanks.

**Comment by jklymak** [comment]
It's because one of them has twice the resolution of the other, at least on my machine

**Comment by SoundSpinning** [comment]
How do you mean, what has higher resolution? In DPIs or what?

**Comment by jklymak** [comment]
Look at the size of your movies.

**Comment by tacaswell** [comment]
the easy test is to add a `plt.ioff()` to the top, the more complicated test is to add prints to the `draw` method of Figure.

**Comment by jklymak** [comment]
Yes, if you draw two frames with `figure` it calls Draw 5 times, but only the expected 2 times with `Figure`.

**Comment by SoundSpinning** [comment]
Thank you all for the replies. I'm learning, which is good.
I tried `plt.ioff()` and made no difference with `agg` on, 1.3 x faster with `Figure()`.
What do you suggest I test next, happy to have a list of stuff to try, if you are tied up with other stuff.

**Comment by QuLogic** [comment]
What backends were you using that showed the slower behaviour?

**Comment by jklymak** [comment]
The double draws happen with `matplotlib.use('Agg')` on master.

**Comment by SoundSpinning** [comment]
@QuLogic: As stated in my 1st question abt backends:
Matplotlib backend (print(matplotlib.get_backend())): `module://ipykernel.pylab.backend_inline`

Then I switched to `agg`, and same results, as far as I can tell.

**Comment by greglucas** [comment]
I can confirm the extra draws, even with interactive mode off. A quick way of testing the number of draws is to add in a counter to the draw events, something like this to the original example.

```python
global i
i = 0
def draw_event(x):
    global i
    print("DRAW", i)
    i += 1
```

It arises due to a `draw_idle()` call before `grab_frame()` in the save of the animation. Some backends have noops for `draw_idle()` which avoids the extra draw call.

`_draw_next_frame()` has a `draw_idle()` call, which happens before saving the frame which issues another draw call.
https://github.com/matplotlib/matplotlib/blob/2e957301cbb8a9924e5a0d02a4efed414e9d025a/lib/matplotlib/animation.py#L1083-L1087

Here is the offending `draw_idle()` call in `_post_draw()` of animation. We might be able to get rid of that draw_idle call when saving the figure, but that would require moving some of the frame-stepping logic around.
https://github.com/matplotlib/matplotlib/blob/2e957301cbb8a9924e5a0d02a4efed414e9d025a/lib/matplotlib/animation.py#L1144

Using FigureCanvasBase (Figure): no extra draw calls because `canvas.draw()` is not implemented.
https://github.com/matplotlib/matplotlib/blob/2e957301cbb8a9924e5a0d02a4efed414e9d025a/lib/matplotlib/backend_bases.py#L1955

Other backends:
**agg:** has a `draw()` method that calls `figure.draw()` leading to an extra draw call.
https://github.com/matplotlib/matplotlib/blob/2e957301cbb8a9924e5a0d02a4efed414e9d025a/lib/matplotlib/backends/backend_agg.py#L424

**qtagg:** also has an extra draw.

**tkagg:** Does **not** have an extra draw. It goes into draw_idle(), but the events never fire, so it doesn't trigger a draw. Maybe the event loop isn't spinning right away? (`after_idle()` never fires)
https://github.com/matplotlib/matplotlib/blob/2e957301cbb8a9924e5a0d02a4efed414e9d025a/lib/matplotlib/backends/_backend_tk.py#L259

**cairos:** None of these have an extra draw.
