### ISSUE TITLE
I can't install on python 3.9

### ISSUE THREAD

**Issue by rafapaz** [matplotlib/matplotlib#18784]
Dear, when trying to install matplotlib in python 3.9 an error occurred:
fails because kiwisolver cannot be installed. Among a lot of error output is: WARNING: The wheel package is not available.

I suppose needing to add 3.9 support and provide wheels.

**Comment by jklymak** [comment]
Yes, 3.9 wheels are not available for many packages yet that matplotlib depends on.  This is already noted.
