### ISSUE TITLE
subplots warning when called with an integer argument

### ISSUE THREAD

**Issue by fbosio** [matplotlib/matplotlib#18805]
## Description

If you call `plt.subplot` with three arguments and the third one is a `bool`, [the `pyplot` module warns you about it](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L1211). I think that `pyplot` should give a similar warning if you make a mistake _the other way around_, i.e., if you run, for instance, `plt.subplots(231)` which will try to create... 231 rows! And this error is more common that you think, see this [comment in an issue about `plt.subplot`](https://github.com/matplotlib/matplotlib/issues/12513#issuecomment-429972905) in case you're wondering.

## Proposed fix
I'm not a `matplotlib` developer myself, but I did take a look at the `pyplot.py` file and I think that maybe some wrapper of the `subplots` function could be made, in order to check the number, type and value of the arguments given to the function.
For example, [line 1242](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L1242) reads
```python
def subplots(nrows=1, ncols=1, sharex=False, sharey=False, squeeze=True,                            
             subplot_kw=None, gridspec_kw=None, **fig_kw):
````
so this could be changed to something like
```python
def subplots(*args, **fig_kw):
    if (len(args) == 1 and isinstance(args[0], Integral)
            and 100 <= args[0] <= 999):
        cbook._warn_external(f'The nrows argument to subplots is {args[0]}. '
                             f'Did you intend to use subplot({args[0]})?')

    _subplots(*args, **fig_kw)

def _subplots(nrows=1, ncols=1, sharex=False, sharey=False, squeeze=True,                            
             subplot_kw=None, gridspec_kw=None, **fig_kw):
```
but I let _you_ the details! :grinning: I hope I have made myself clear at least.

Regards.

**Comment by jklymak** [comment]
Thanks for the suggestion.  Personally, I'm not in favour of this warning.  Its not like its super mysterious what has happened when the 213 subplots show up.  We are also trying to soft-deprecate `subplot(213)` so I don't think that adding checks for its misuse are worth the extra complication...

**Comment by fbosio** [comment]
Thanks for your time!

> Its not like its super mysterious what has happened when the 213 subplots show up.

_If_ they show up... 213 subplots could be a _very_ time-consuming task if one doesn't have the right hardware to stand for it. And trust me, when they show up, you just see some kind of multicolored-weird-unclear stains in the figure, which hardly tell you what's going on. Anyway...

> We are also trying to soft-deprecate `subplot(213)` so I don't think that adding checks for its misuse are worth the extra complication...

What you wrote is also very reasonable to me. I don't like that MATLAB-like-inherited function signature either :smile: so consider this issue closed! :tada: 

Thank you one more time.
