### ISSUE TITLE
colormap generalization

### ISSUE THREAD

**Issue by rwijtvliet** [matplotlib/matplotlib#18809]
### Problem

The current implementation of colormaps maps a 1D float interval onto a 1D color spectrum. Meaning, I can use a colormap to find the color that 'matches' a **single** float value.

Sometimes, however, I'd like to get the color that matches a **pair** or **triplet** of float values. 

A use case: coloring locations on a city map, where the color for each location is calculated from 2 values: the time needed to get there by car, and the time needed to get there by public transport. Or, from 3 values, if the time needed to get there by bike is also included. In that case, the color could be picked from a color triangle like [this one](https://github.com/rwijtvliet/interpol/blob/master/img/cmap3_transport_full.png).

### Proposed Solution

I ran into this problem and created a solution here: [https://github.com/rwijtvliet/interpol](https://github.com/rwijtvliet/interpol).

Now, please note I've only created this for myself and probably needs a lot of work to be able to get merged into `matplotlib`. For example, there is no unit tests whatsoever.

### Proposed Way Forward

1. A core developer has a look a the linked project to check out, what I mean, and to judge if this is something the `matplotlib` package would actually benefit from including. (The examples at the ends of the sections `ColorMap2` and `ColorMap3` in the readme are the best places to start to get an idea of what I mean.)
2. If yes, someone probably has some suggestions regarding how to start on a PR for this feature. I'd gladly help to get this included into the project, but my coding skills are insufficient to do this without by myself.

But let's first see if this is deemed of interest. :)

**Comment by timhoffm** [comment]
@rwijtvliet Thanks for the proposal! I see where this is useful.

Mapping multiple values to a color is a rather specialized application. Given the vast scope of visualization, we try to keep Matplotlib focused on core features to keep it manageable. The proposed way forward here is to create a third-party package. This also has the advantage, that you can move the development at your own pace independent of the Matplotlib release cycle.

We'd be happy to include such a package in https://matplotlib.org/thirdpartypackages/index.html. If there's interest, there's also the possibility to host third-party repositories under the [Matplotlib GitHub Project](https://github.com/matplotlib).

If a separate project is too big, it's also possible to add code as an [example](https://matplotlib.org/gallery/index.html). Though it seems one needs quite a bit of code, which could make the example hard to read.

**Comment by tacaswell** [comment]
We also had a GSOC student take a pass at this 3 years but it ended up not being merged (yet): https://github.com/matplotlib/matplotlib/pull/8738 .

The examples in the README are pretty nifty @rwijtvliet  :)

I suggest having a look at https://github.com/NSLS-II/scientific-python-cookiecutter / https://nsls-ii.github.io/scientific-python-cookiecutter/ for how to bootstrap the code you have into a full package.

**Comment by ianhi** [comment]
There's also a list of pieces of info I thought might helpful when making a 3rd party packages here: https://github.com/matplotlib/matplotlib/issues/18496

**Comment by rwijtvliet** [comment]
Hey guys, thanks for the feedback, much appreciated. 

[#8738](https://github.com/matplotlib/matplotlib/pull/8738) is similar in accepting >1 float, but different in not returning a color based on the *relative* difference (i.e., it accepts quantities with unequal physical units). But I'm sure I can learn a lot from that code.

I'll see what the best way to go about things is here and start with posting an example.

**Comment by jklymak** [comment]
@rwijtvliet You add an example by adding python code in `examples/`

**Comment by timhoffm** [comment]
See also https://matplotlib.org/devel/documenting_mpl.html#writing-examples-and-tutorials

**Comment by jklymak** [comment]
This is basically https://github.com/matplotlib/matplotlib/issues/14168, so lets close this...
