### ISSUE TITLE
\t fails to render with plt.annotate()

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/matplotlib#18813]
### Bug report

**Bug summary**
The string literal "tab" `\t` does not render correctly on figures when used in plt.annotate.

**Code for reproduction**

```python
plt.figure()
plt.plot([0,5,5,5,5,5])
plt.annotate('\tTab', xy=(1, 1),)
plt.annotate('Text\nNewLine', xy=(2, 2),)
plt.annotate('Text \tTab', xy=(3,3),)
```

**Actual outcome**

![Figure 34](https://user-images.githubusercontent.com/2721423/97163022-512ba680-1780-11eb-98bd-f5549de6720e.png)

**Expected outcome**
Indenting the text in the figure by a tab-distance (possibly 4 spaces), although I do not know exactly what that is supposed to be. The failing render may be intentional, as the amount of whitespace could be ambiguous. Perhaps a warning should be shown?

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.31
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipympl.backend_nbagg (and inline)
  * Python version: 3.8.5

Installed from conda-forge.

**Comment by anntzer** [comment]
At least with master there's a warning:
```
.../matplotlib/backends/backend_agg.py:240: RuntimeWarning: Glyph 9 missing from current font.
  font.set_text(s, 0.0, flags=flags)
.../matplotlib/backends/backend_agg.py:203: RuntimeWarning: Glyph 9 missing from current font.
  font.set_text(s, 0, flags=flags)
```
I don't think we should try to guess what a tab-width is supposed to be (because the obvious next step would be to make tab stops configurable...), so I'd say the current behavior is fine, and I suggest to close this as wontfix.

**Comment by thomasaarholt** [comment]
That's fine. I couldn't find it mentioned in a previous issue, so I thought I'd raise it for clarity.
