### ISSUE TITLE
AttributeError: 'Figure' object has no attribute '_remove_ax'

### ISSUE THREAD

**Issue by khanfarhan10** [matplotlib/matplotlib#18836]
### Bug report

**Bug summary**

While trying tor retrieve  my saved 3-D figure as a pickle file, this error pops up. Maybe add utility for saving to 3d formats???

**Code for reproduction**
You can download the pickle file from [here](https://github.com/khanfarhan10/DIMENSIONALITY_REDUCTION/raw/master/FigureObject.fig.pickle)

```python
import numpy as np               # Mathematical Functions , Linear Algebra, Matrix Operations
import pandas as pd              # Data Manipulations,  Data Analysis/Storing/Preparation
import matplotlib.pyplot as plt  # Simple Data Visualization , Basic Plotting Utilities
plt.style.use("dark_background") #just a preference of the authors, adds visual attractiveness

%matplotlib notebook

from mpl_toolkits.mplot3d import Axes3D

import pickle
figx = pickle.load(open('FigureObject.fig.pickle', 'rb'))

#figx.show() # Show the figure, edit it, etc.!

figx.figure
```

**Actual outcome**

```
/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: This figure was saved with matplotlib version 3.2.2 and is unlikely to function correctly.
  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-cd10a2a88638> in <module>
      1 import pickle
----> 2 figx = pickle.load(open('FigureObject.fig.pickle', 'rb'))
      3 
      4 #figx.show() # Show the figure, edit it, etc.!
      5 

AttributeError: 'Figure' object has no attribute '_remove_ax'
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Jupyter Cloud [here] (https://notebooks.gesis.org/binder/jupyter/user/ipython-ipython-in-depth-89l6d2ji/notebooks/binder/Index.ipynb)
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.6.11
  * Jupyter version (if applicable):
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.0
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```
  * Other libraries: from mpl_toolkits.mplot3d import Axes3D

**Comment by anntzer** [comment]
That's what the warning at the top says:
> This figure was saved with matplotlib version 3.2.2 and is unlikely to function correctly.

i.e. we do not support loading pickles on a matplotlib version different from the one where it was saved (see discussion at https://github.com/matplotlib/matplotlib/issues/16562).
