### ISSUE TITLE
MNT: Remove AxesStack and deprecated behavior of reuse of existing axes with same arguments

### ISSUE THREAD

**Issue by lpsinger** [matplotlib/matplotlib#18832]
### Describe the issue

**Summary**

In Matplotlib 2.1, the behavior of reusing existing axes when created with the same arguments was deprecated (see #9037). The request is to finally remove this behavior.

My immediate motivation is that I have a [collection of projection classes](https://git.ligo.org/lscsoft/ligo.skymap/-/blob/master/ligo/skymap/plot/allsky.py) that take as a keyword argument an instance of [astropy.coordinates.SkyCoord](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord), which [as of Astropy 4.1 are no longer hashable](https://docs.astropy.org/en/stable/whatsnew/4.1.html#whatsnew-4-1-inplace-skycoord) (see also astropy/astropy#9857). This unexpectedly broke my code because I had not realized that projection keyword arguments had to be hashable.

### Proposed fix

Remove the AxesStack class, remove the `Figure._make_key` method, and update the documentation to reflect the removal of the old deprecated behavior.

**Comment by tacaswell** [comment]
@anntzer do you already have a branch for this?

**Comment by anntzer** [comment]
IIRC I kind of gave up on that due to unclearness of what we want to keep supporting, e.g. wrt. `gca(projection=..., ...)` (https://github.com/matplotlib/matplotlib/issues/10700) (which goes through the same AxesStack info).  Probably you need to make some executive decisions on that :)

**Comment by lpsinger** [comment]
@anntzer, after studying #10700, my suggestion is:

1.  In the next release of Matplotlib:
    * Deprecate kwargs for `gca()`
    * Remove projection kwargs lookup (for `gca()` and also `subplots()`, etc.)
    * If `gca()` is called without kwargs, simply return the current axes
    * If `gca()` kwargs matches the kwargs of the current axes, return those axes, otherwise raise an exception
2.  In a future release of Matplotlib:
    * Remove kwargs entirely from `gca()`

What do you think?

**Comment by anntzer** [comment]
I am personally fine with fully deprecating all kwargs to gca(), but there was some pushback wrt. subplot() in https://github.com/matplotlib/matplotlib/issues/12513 (and IIRC these basically go through the same machinery) and I had little interest in fighting that fight, which is why I decided to let @tacaswell decide :)

**Comment by lpsinger** [comment]
@tacaswell, what do you think? I am happy to take a stab at the above changes, if you agree with the approach.

**Comment by lpsinger** [comment]
How do we want to handle a call to gca() without kwargs when there are not yet any axes? Return None? Or return a new axes?

**Comment by anntzer** [comment]
That should definitely return a new axes (I'd guess that's an *extremely* common use case).
