### ISSUE TITLE
ScalarMappable should copy its input and allow non-arrays

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18841]
### Problem

Recently I wanted to draw some colormapped vlines.  As LineCollection inherits from ScalarMappable, one can indeed write e.g.
```python
from pylab import *
xs = vals = np.arange(10)
plt.vlines(xs, 0, 1, array=vals)
plt.show()
```
and get
![test](https://user-images.githubusercontent.com/1322974/97629847-ff5c7800-1a2e-11eb-8905-e0fd43ffbd56.png)

Unfortunately,
1) The `array` kwarg only accepts ndarrays, and not e.g. nested lists: `plt.vlines(np.arange(10), 0, 1, array=[*range(10)])` crashes (at draw time, which is even worse) with "AttributeError: 'list' object has no attribute 'ndim'".  This is unlike most other Axes/pyplot APIs (e.g. `imshow`), which happily accept lists (nested/2D lists, for imshow).
2) The `array` kwarg is not copied, so later changes to it get reflected back into the artist (i.e. doing `vals[5] = 45` *after* the call to `vlines` still affects the line colors).  Again, this is unlike other Axes/pyplot APIs (e.g. `imshow`), which insulate the artist from later changes to the input.

### Proposed Solution

Make a copy of the input and cast it to arrays.  (Well, modulo unit handling...)

### Additional context and prior art

Behave like `imshow`.

**Comment by aitikgupta** [comment]
I'd love to take this up! :)
Initial scanning leads to the following points:
- In case of `imshow`, `_ImageBase` class inherits from `ScalarMappable`, but overrides its `set_array` function as:
https://github.com/matplotlib/matplotlib/blob/59bfcfa8ff479d228502e3561e02fe4f70599505/lib/matplotlib/image.py#L733-L743
- `imshow` doesn't raise this error as its `set_data` (called from `set_array`) copies the original array and checks for numpy casts:
https://github.com/matplotlib/matplotlib/blob/59bfcfa8ff479d228502e3561e02fe4f70599505/lib/matplotlib/image.py#L696-L701
- In case of `vlines`, `ScalarMappable` is inherited again, but there's no overriding its `set_array` function, which evidently just accepts `ndarray`:
https://github.com/matplotlib/matplotlib/blob/59bfcfa8ff479d228502e3561e02fe4f70599505/lib/matplotlib/cm.py#L363-L372

**Comment by aitikgupta** [comment]
To solve this, I added `set_array` to `Collection` class, overriding it again. It will need some reviews, I'll issue a PR for the same.
