### ISSUE TITLE
Improve GitHub labels

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#18855]
As discussed some time ago on the dev call, we need better GitHub labels to manage issues and PRs.

I don't think we'll manage to rebuild labels from scratch (or if we do, that it would be the perfect system). Therefore I propose to incrementally evolve the labels.

I've collected all present labels in a [google spreadsheet](https://docs.google.com/spreadsheets/d/177NizYe252uXIHupx9emQkMX28Sz34F-44_unlsKn6E/edit?usp=sharing)

I did a rough classification:
- **State**: Something to do with "next action"
- **Topic**: Which part of matplotlib does it address?
- **Scope**: This is only sort of a collection of non-state non-topic labels. One might split or rename this, but it's currently not my focus.

For now, I'm focussing on **State**, because the notion of "next action" has been identified to be important (c.f. https://hackmd.io/P3Hrfoy9RSKRA4-mXMKW2A#PR-closing-philosophy).

I propose the following:
- Rename all state labels `label name` to `state: label name`.
  _Rationale_: The prefix distinguishes these labels from other classes (which may or may not grow a prefix themselves later on).
- Change the colors to a simple 4-color scheme based on who must do the next action to move the issue/PR forward:
  ![grafik](https://user-images.githubusercontent.com/2836374/97790928-7760a480-1bcd-11eb-869b-f7e9ee8f88be.png) 
  _Rationale_: By this coloring we can immediately see whether the issue/PR needs an action from our side, which is the most important aspect for issue management. IMO the 4 colors are enough. One could add slight variations, e.g. different greys for different "no action" labels, but then again, nobody will exactly remember these. So let's keep it simple for a start. We can still refine this later if needed.

**Comment by story645** [comment]
I like this plan, and we should probably recolor anything else that uses these colors to something else so there's no conflict.
(also we should consolidate the MEPs to MEP: #)

**Comment by timhoffm** [comment]
- Renamed and recolored all status labels.
- Recolored some other labels that used one of the above colors.

**Comment by QuLogic** [comment]
FYI, 'Still Needs Manual Backport' is added by the bot, and so your rename and re-color of it didn't have any effect (cf #18929).
