### ISSUE TITLE
Is the time (x-axis) in specgram being incorrectly calculated by a factor of 2?

### ISSUE THREAD

**Issue by GastonMazzei** [matplotlib/matplotlib#18859]
Hello, I have noticed that the following code generates a spectrogram that scales the time by 2x. 

<b>Can someone please test it on other files? or else I'll do so with more time during the following weeks</b>

```python
import wave
import pylab

import numpy as np
import matplotlib.pyplot as plt

def get_wav_info(wav_file):
    wav = wave.open(wav_file, 'r')
    frames = wav.readframes(-1)
    sound_info = pylab.frombuffer(frames, 'int16')
    frame_rate = wav.getframerate()
    wav.close()
    return sound_info, frame_rate

def graph_spectrogram(wav_file):
    f,ax = pylab.subplots(1,figsize=(15, 5))
    sound_info, frame_rate = get_wav_info(wav_file)
    ax.specgram(sound_info, Fs=frame_rate)
    plt.show()

graph_spectrogram('directory/name.wav')
````

Sampling frequency is 44.1kHz and I've noticed that forcing it to be 88.2kHz  fixed it. 
(i.e. changing the code like this)

```python
#ax.specgram(sound_info, Fs=frame_rate)
ax.specgram(sound_info, Fs=int(44100 * 2))
``` 
<b>The conclusion is that there might be a factor of 2 misplaced in the time calculation</b>

<b>reference to time:</b>
https://github.com/matplotlib/matplotlib/blob/e69e2e6e22d180b73b04caca37417a89feea7097/lib/matplotlib/mlab.py#L424

<i>Thank you for your time</i>

**Comment by jklymak** [comment]
How are you diagnosing that there is a problem?

**Comment by GastonMazzei** [comment]
> How are you diagnosing that there is a problem?

Hello, 

After (visually) noting that the output image has 30 seconds in the x-axis but the original audio had 15 seconds, I ran:

```python
# Manually input the length of the wav file used for testing
length_of_the_wav_file = 15

_1, _2, TIME,  *_3 = ax.specgram(sound_info, Fs=frame_rate)

print(np.max(TIME)>=2*length_of_the_wav_file
```
>> True

So the point being made is that the output max time doubles the input time by a factor of two; please test it yourself with a new ".wav" file. I'm sorry the final part of the code involves manually inputting the length of your testing file.

**Comment by jklymak** [comment]
The specgram demo https://matplotlib.org/gallery/images_contours_and_fields/specgram_demo.html looks right to me, so I suspect your data input method.  Perhaps make your own time variable with `np.arange(len(sound_info))/sample_rate` and see if your time series is really 15 s long.

**Comment by GastonMazzei** [comment]
Thanks for the advice @jklymak 
<b>The doubling factor was due to it being fed a stereo file (2 channels)</b>
I am very sorry for the trouble, and I thank you for your time 

closing
