### ISSUE TITLE
Matplotlib result plot inconsistent between versions 2.2.2 and 3.2.2

### ISSUE THREAD

**Issue by CrashLaker** [matplotlib/matplotlib#18864]
Hi all,

I'm trying to understand what am I doing wrong when ploting a bar chart.
I could spot this because I had two environments with two different matplotlib versions installed.

I'm trying this on Amazon Linux 2.
```bash
yum -y install python3 python3-pip
pip3 install pandas matplotlib
# python3-3.7.9-1.amzn2.0.1.x86_64
```

So the code is this one:
```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd

size = list(range(1,11))
x = pd.to_datetime([pd.Timestamp(2020,i,1) for i in size])
y = size[:]

fig, ax = plt.subplots(1,1,figsize=(16,5))
ax.bar(x.values, y, width=10)
fig.savefig('a.png')
```

### When using matplotlib==3.2.2
![image](https://user-images.githubusercontent.com/4432491/97813229-74b18e00-1c65-11eb-9e5f-221676f189ee.png)

### When using matplotlib==2.2.2
![image](https://user-images.githubusercontent.com/4432491/97813262-b17d8500-1c65-11eb-8e83-0012a1e240c7.png)

Using Matplotlib==3.2.2
I could barely get to see the bar width only when using values below 1.
```python3
ax.bar(x.values, y, width=0.9)
```
![image](https://user-images.githubusercontent.com/4432491/97813303-f3a6c680-1c65-11eb-815e-a2919993cd72.png)

**Comment by timhoffm** [comment]
Mixing different data types in *x* and *width* results in undefined behavior. In your case *x* is `np.datetime64`. What should a width of 10 mean on a date axis?

The correct way is to specify the with in the same "unit" system as *x*. In your case:

~~~
ax.bar(x.values, y, width=np.timedelta64(20, 'D'))
~~~

![grafik](https://user-images.githubusercontent.com/2836374/97816197-e7396280-1c93-11eb-9bc7-05e04056b0b8.png)

**Comment by dopplershift** [comment]
Closing since I don't think there's anything actionable here on the matplotlib side, but feel free to re-open if there's something we can do here.
