### ISSUE TITLE
TeX in legends ignores rcParams

### ISSUE THREAD

**Issue by sven-frotscher** [matplotlib/matplotlib#18861]
### Bug report
`pyplot.legend` and `pyplot.figlegend` do not observe `pyplot.rcParams` when using TeX in labels.
This may also be an issue with the docs which do not mention that (or a way to configure the TeX output in legends).

#### Code for reproduction

```python
# Get version info
from matplotlib import __version__ as mpl_version
from matplotlib import get_backend as mpl_get_backend
from platform import python_version

print("matplotlib version:", mpl_version)
print("using backend", mpl_get_backend())
print("python version:", python_version())

# Demonstration example
from matplotlib import pyplot as plt

plt.rcParams["font.family"] = "serif"

x = [0, 1]
y = [1, 0]

plt.plot(x, y, label="$y=1-x$")
plt.legend()  # or plt.figlegend()
plt.show()
```

#### Actual outcome
```
matplotlib version: 3.3.2
using backend Qt5Agg
python version: 3.6.9
```
![](https://user-images.githubusercontent.com/67124493/97809823-b47d7300-1c6f-11eb-9978-cc956d171aff.png)

#### Expected outcome
The TeX in the (figure) legend gets rendered with the font specified in `pyplot.rcParams`, like the axes' labels do.

#### Matplotlib version
  * Operating system: Ubuntu 18.04.5
  * Matplotlib version: 3.32 (installed using `pip install matplotlib`)
    * `python3-matplotlib` installed using `apt`, which shows version `2.1.1-2ubuntu3`, probably not using that
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.9
    * `apt` says `3.6.9-1~18.04ubuntu1.3`
  * Jupyter version: Not using Jupyter

**Comment by anntzer** [comment]
This doesn't have anything to do with legends in particular, this is simply because mathtext doesn't obey `rcParams["font.family"]` but instead uses `rcParams["mathtext.fontset"]` (https://matplotlib.org/tutorials/text/mathtext.html), which you can for example set to `dejavuserif`.

**Comment by sven-frotscher** [comment]
Thank you, @anntzer, for the swift and helpful reply :)
