### ISSUE TITLE
tight_layout does not adjust for rotated ylabel

### ISSUE THREAD

**Issue by Alalalalaki** [matplotlib/matplotlib#18878]
### Bug report

**Bug summary**

tight_layout does adjust for xlabel rotation but not for ylabel rotation

**Code for reproduction**

```python
def example_plot(ax, fontsize=12):
    ax.plot([1, 2])

    ax.locator_params(nbins=3)
    ax.set_xlabel('x-label', fontsize=fontsize)
    ax.set_ylabel('y-label', fontsize=fontsize)
    ax.set_title('Title', fontsize=fontsize)

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(nrows=2, ncols=2)
example_plot(ax1)
ax1.set_ylabel("Some Long Y Label", rotation=0)
example_plot(ax2)
example_plot(ax3)
example_plot(ax4)
ax4.set_xlabel("Some Long X Label", rotation=90)
plt.tight_layout()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/31154974/97976287-cc8af900-1e0d-11eb-809d-5a7e9174001c.png)

**Expected outcome**

tight_layout also works for rotated ylabel.

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
To get the effect you are after you need to change the horizontal alignment of the ylabel from "center" to "right":

```python
ax1.set_ylabel("Some Long Y Label", rotation=0, horizontalalignment='right')
```

There is some confusion as to what happens when we rotate text and what "verticalalignment" and "horizontalalignment" mean, but I think its well-defined, so I'll close this here.  Thanks!
