### ISSUE TITLE
3D Scatter Plot with Colorbar is not saved correctly with savefig

### ISSUE THREAD

**Issue by JakubPolanowski** [matplotlib/matplotlib#18885]
### Bug report

**Bug summary**

When saving a 3D scatter plot with a color bar using `savefig` (either `plt.savefig` or `fig.savefig`), the data point colors are incorrect on the saved image, however the inline image (I'm using jupyter lab notebooks) is fine, the issue is only present when saving the figure. Note that this only happens when a colorbar is added to the figure, when a figure with points colored according to a set of values is saved, the issue does not occur. So it would seem that this issue is caused by some interaction of savefig and colorbar. 

I've tried both matplotlib version 3.3.1 and 3.3.2 and in both versions this occurs. I've also tried downgrading to version 3.2.1, in version 3.2.1 this does not occur, so it seems some change in 3.3.1 is the cause of this issue.

**Code for reproduction**

Requirements: matplotlib 3.3.1 or 3.3.2 

The following requirements are purely for setting up an example dataset which I used in the following code snippet to generate an example dataset to plot, as such I'm not listing the version numbers.

Optional: pandas, numpy

Also note that I used JupyterLab notebook to run the code, although given that I was able to 'fix' the issue by downgrading to matplotlib version 3.2.1 I don't think there is any link between running the code in JupyterLab and the issue itself.

```python

#importing packages 
import matplotlib.pyplot as plt

import numpy as np
import itertools
import pandas as pd

# example data setup 
data = list(itertools.product(*[np.arange(0, 5, 1), np.arange(0, 5, 1), np.arange(0, 5, 1)]))
df = pd.DataFrame(data, columns=['x', 'y', 'z'])

df['c'] = df['x'] + df['y']

# plotting

## no color bar example (no issue)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d', proj_type = 'ortho')

sc = ax.scatter(
    df['x'], 
    df['y'],
    df['z'],
    c=df['c'],
    s=40  # size is purely to make it easier to see
)  

plt.savefig('example no colorbar save.png')  # dpi has no effect, purely to make it easier to zoom into the figure

## color bar example (ISSUE)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d', proj_type = 'ortho')

sc = ax.scatter(
    df['x'], 
    df['y'],
    df['z'],
    c=df['c'],
    s=40  # size is purely to make it easier to see
)  

fig.colorbar(sc)

plt.savefig('example colorbar save.png', dpi=300)  # dpi has no effect, purely to make it easier to zoom into the figure

```

**Actual outcome**

![example colorbar save](https://user-images.githubusercontent.com/65884015/98034158-8a00f680-1de4-11eb-938d-66f31c6472ae.png)

This is being the saved figure with a color bar (note that if you zoom in the outlines of the data points are correct - see expected outcome below - but the fill of the points is incorrect). 

Note that if no colorbar is added, the plot saves correctly as shown below. 

![example no colorbar save](https://user-images.githubusercontent.com/65884015/98034501-13b0c400-1de5-11eb-9e33-aa26d03834d1.png)

**Expected outcome**

This is a screenshot of the colorbar chart as it is shown inline in the JupyterLab notebook.

![example figure color barscreenshot](https://user-images.githubusercontent.com/65884015/98034913-b8cb9c80-1de5-11eb-8509-302eecf1ef44.PNG)

And this is a screenshot of the **non** colorbar chart as it is shown inline in the JupyterLab notebook, note this one is essentially the exact same as the saved version, so the issue is purely with the colorbar/savefig interaction. 

![example figure screenshot](https://user-images.githubusercontent.com/65884015/98034934-bff2aa80-1de5-11eb-9abe-338726fcdb1f.PNG)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.8.5
  * Jupyter version (if applicable): 2.2.6
  * Other libraries: pandas, numpy, itertools (python built in library) 

Everything has been installed via conda, with all packages listed being install from the default channel.

**Comment by anntzer** [comment]
bisects to https://github.com/matplotlib/matplotlib/pull/17378 (@timhoffm), although even before that there was already a slight difference between the colorbar and non-colorbar versions: the colorbar version has fully opaque markers whereas the non-colorbar one has partially transparent markers.

**Comment by JakubPolanowski** [comment]
> bisects to #17378 (@timhoffm), although even before that there was already a slight difference between the colorbar and non-colorbar versions: the colorbar version has fully opaque markers whereas the non-colorbar one has partially transparent markers.

Is there any somewhat simple workaround? Aside from just downgrading?

**Comment by timhoffm** [comment]
> Is there any somewhat simple workaround? Aside from just downgrading?

Um, probably not.

> although even before that there was already a slight difference between the colorbar and non-colorbar versions: the colorbar version has fully opaque markers whereas the non-colorbar one has partially transparent markers.

This is a good hint: `Path3DCollection.do_3d_projection()` adds the transparency, and since #17378 it reorders the points. Apparently, when using a colorbar, the `Path3DCollection` facecolors are updated/overwritten through a different code path.

In fact, I can break the example without the colorbar by adding `sc.autoscale_None()`. Needs further investigation.

**Comment by QuLogic** [comment]
Since we always recalculate on draw, I suggest something like: https://github.com/matplotlib/matplotlib/commit/6c0c30b234c6bbc6d0e3aecd4685fe10bd4c8eb7 applied to all 3D artists.

**Comment by tacaswell** [comment]
I do not understand why the output from inline (which is under the hood calling savefig!) works...

**Comment by tacaswell** [comment]
To answer my own question, it is because of the `bbox_inches='tight'` if you add that (which makes us do two internal renders) or save the figure a second time it "works".  I suspect Tim's suggestion of `sc.changed` is the right place to start...

**Comment by tacaswell** [comment]
Well, that was fun to track down!  See the long docstring on the helper in #18929 if you are interested.  In short, `do_3d_projection` and `update_scalarmappable` were both writing to the same place so we need to make sure they run in the right order.
