### ISSUE TITLE
Incorrect version requirement message from setup.py

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18882]
### Bug report

**Bug summary**

`python3.6 setup.py` currently prints
```
Beginning with Matplotlib 3.1, Python 3.7 or above is required.
You are using Python 3.6.
```
but 3.7 is actually only required since Matplotlib 3.4.

Would be nice to fix before 3.4 is actually released.

**Comment by hs2361** [comment]
@anntzer That was the only change to be made, right?

**Comment by anntzer** [comment]
yes
