### ISSUE TITLE
Feature request: mathtext support for \displaystyle

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#1888]
When I give matplotlib a annotation string such as

```
$\frac{A}{B} = C$
```

and I specify a fontsize of 18, the A and B are rendered at 12.6 pt, while the C is rendered at 18 pt. I want A, B, and C to all be the same size.

In a LaTeX document, if you give the commands

```
\begin{equation}
\frac{A}{B} = C
\end{equation}
```

you get a fraction, where A, B, and C are all the same size, but if you do

```
$\frac{A}{B} = C$
```

inline with text, you get the A and B rendered at 12.6 pt, while the C is rendered at 18 pt. Thus it appears matplotlib's mathtext is emulating LaTeX's inline mode. In LaTeX you can write

```
$\displaystyle\frac{A}{B} = C$
```

and then A, B, and C are all the same size, even in inline mode. I tried this in matplotlib, but mathtext did not recognize the command \displaystyle. =(

I am aware I can use \displaystyle if I change text.usetex to true in my .matplotlibrc file, but I would like to stay with mathtext since it is a lot faster.  Is there a chance of implementing \displaystyle in math text?  If not, does anyone have a work around?

My setup: matplotlib v1.2.0, python 2.7, OS X 10.8.3

**Comment by petehuang** [comment]
This hasn't been updated in a while. I'm wondering about the priority of this issue given that there's a good workaround. I guess it depends on how far we want MPL to go into this territory

**Comment by breedlun** [comment]
I am obviously biased, but this issue still matters to me.  I realize it would be a large effort for mathtext to recreate everything in LaTeX, but I think `\displaystyle` fractions are one feature that deserves to be implemented.  I have been using matplotlib intensively for three years now and I have not run into any other shortcoming in mathtext that gets in my way more than this one.  Any time I want to normalize a variable by another variable, I have to use `a / b` instead of `\frac{a}{b}`.

If no one has made any headway on this issue by this summer, I should have some time to work on it.  I am a newbie when it comes to heavy duty TeX, but I am willing to learn.

**Comment by watkinrt** [comment]
I just ran into this problem and would be interested in a fix. Like breedlun, I thought I could get over it, but I can't (maybe its because we both had the same thesis adviser who broke us). It appears that my library has Knuth's "METAFONT : the program" book (i.e., Volume C), but sadly not "TeX: The Program". If I were to get the book, how intensive would it be for me to implement this feature? I've meddled around with the underbelly of matplotlib some, so I am familiar with much of its structure. I also have extensive experience with LaTeX and some with TeX.

**Comment by breedlun** [comment]
Hah!  That's great that you find your way to this same issue.  Best of luck, and let me know if I can help.

Ben

**Comment by watkinrt** [comment]
Just poking around in mathtex.py, I think it should be pretty easy to implement this functionality. It looks like the tex macro \genfrac had been implement, which is the base macro for making things like \frac, \binom, \stackrel, etc; the usage of \genfrac is { \genfrac #1 #2 #3 #4 #5 #6  }, where #1 is left delimiter, #2 is the right delimiter, #3 is the fraction bar thickness, #4 is the style (0: displaystyle, 1: textstyle, 2: scriptstyle, 3: scriptscriptstyle), #5 is the numerator, and #6 is the denominator. It looks like the current implementation of the child macros \frac, \binom, etc all are hard coded to use the \textstyle style (i.e., \displaystyle is ignored). If I have time this weekend, I'll see if I can get the style to depend on the input style.

**Comment by anntzer** [comment]
#8151 implemented \dfrac, which covers the initial request.  That doesn't cover all of \displaystyle, but I'll close this until there are other concrete points to implement.
