### ISSUE TITLE
wrong bounds checking in streamplot start_points

### ISSUE THREAD

**Issue by d70-t** [matplotlib/matplotlib#18898]
### Bug report

The bounds check for the `start_points` argument is wrong if the `x` or `y` coordinates are not in ascending order:

```python
import matplotlib.pylab as plt
import numpy as np

u = np.ones((2, 2))
v = np.zeros((2, 2))
x = np.array([0, 10])

y = np.array([10, 0])  # (a)
#y = np.array([0, 10])  # (b)

plt.streamplot(x, y, u, v, start_points=[[5, 5]])  # (c)
#plt.streamplot(x, y, u, v)  # (d)

plt.show()
```

The code results in
```
ValueError: Starting point (5.0, 5.0) outside of data boundaries
```

I would have expected that a plot with one streamline is created. The error goes away **either** if I replace `(a)` with `(b)` **or** if I replace `(c)` with `(d)`. Thus if `start_points` are **not** given, plotting a descending range works totally fine.

**Matplotlib version**

  * Operating system: macOS 10.15.7
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.6
  * Other libraries: numpy: 1.19.2

Matplotlib has been installed via `pip`.

**Comment by tacaswell** [comment]
It looks like the code in `streamplot` (via `Grid`) assumes that `x` and `y` are monotonic, evenly spaced, and increasing.  We do a bunch of checks that it is actually a grid and evenly spaced in https://github.com/matplotlib/matplotlib/blob/eeef6e59386c6cebe2960213128c6a84906ddda9/lib/matplotlib/streamplot.py#L314-L351 but not that it is increasing.  I think the options here are:

 - document that x/y should be increasing and add a check to fail with a better error (my preference as it is the status quo)
 - find a way to make the the decreasing input working (either by normalizing the input or bound checking but this will require checking that it actually works correctly as I am not sure that we have traced through all of the integration code to make sure we do not make any assumptions that the step is positive)

**Comment by aitikgupta** [comment]
I can take this up, looks pretty straightforward.
Should all the `Grid` objects have this check? Or just the `streamplot` function.
In other words, can there be a `Grid` object which does not adhere to having x/y in a decreasing fashion?

**Comment by timhoffm** [comment]
Since `matplotlib.streamplot.Grid` is only used for `streamplot()`, it's reasonable to implement the constraint there.
