### ISSUE TITLE
xticks labels not available after a plt.hist

### ISSUE THREAD

**Issue by durandg12** [matplotlib/matplotlib#18890]
### Bug report

**Bug summary**

I want to access the labels ot the xticks produced by a histogram plot (`plt.hist`), to modify them, but calling `plt.xitcks()` has an output totally different than what I can see on the plotted histogram. The labels returned by `plt.xitcks()` are a bunch of `Text(0, 0, '')`, and their number is not the same as the number of ticks seen on the plot. 

Note that I know that I can modifiy the xticks labels with `matplotlib.ticker.FuncFormatter` without having to retrieve them with `plt.xitcks()`. But the data I use is of type `numpy.datetime64` and matplotlib converts it internally in some floats that I can't really work with because I don't know how matplotlib do the conversion back and forth between those floats and the dates (is it worth opening another issue about that ?)

**Code for reproduction**

```python
import pandas as pd
from matplotlib import pyplot as plt

df = pd.DataFrame({"col1": [1, 4, 4]}
)
plt.hist(x="col1", data=df)
locs, labels = plt.xticks()
print(locs)
print(labels)

```

**Actual outcome**

```
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, '')]

```
<img width="399" alt="Capture d’écran 2020-11-04 à 20 33 42" src="https://user-images.githubusercontent.com/45902885/98159556-17277680-1edd-11eb-9482-e464e3d4c9bd.png">

Notably, the two lists `locs` and `labels` have length 9 whereas we  see only 7 ticks on the image.

**Expected outcome**

Those are the expected lists returned by `plt.xticks()`:
```
[1.  1.5 2.  2.5 3.  3.5 4. ]
[Text(1.0, 0, '1.0'), Text(1.5, 0, '1.5'), Text(2.0, 0, '2.0'), Text(2.5, 0, '2.5'), Text(3.0, 0, '3.0'), Text(3.5, 0, '3.5'), Text(4.0, 0, '4.0')]
```

This is the result I get if I force the xticks by adding the following lines after the previous code:
```python
real_ticks_locs = [1., 1.5, 2., 2.5, 3., 3.5, 4.]
real_ticks_labels = [1., 1.5, 2., 2.5, 3., 3.5, 4.]
plt.xticks(real_ticks_locs, real_ticks_labels)
locs, labels = plt.xticks()
print(locs)
print(labels)
```
and in that  case I get the exact same image.

**Matplotlib version**
  * Operating system:  macOS 10.13.6
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.8.5
  * Jupyter version (if applicable): output of `jupyter --version`in a terminal:
  ```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.5
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

Python installed from Homebrew, matplotlib installed from pip.

**Comment by timhoffm** [comment]
The tick labels are lazily evaluated during draw.

You can manually force that by `plt.draw()`.

**Comment by durandg12** [comment]
@timhoffm I tried to insert `plt.draw()` just after the call to `plt.hist` and now the labels are no longer empty `Text(0, 0, '')`.

There is still a problem with the number of ticks though. The returned lists still have length 9 for 7 ticks on the figure, so if I do the following:
```python
plt.hist(x="col1", data=df)
plt.draw()
locs, labels = plt.xticks()
plt.xticks(locs, labels)
```
the figure changes.

**Comment by jklymak** [comment]
Yes that is unfortunate behaviour but it was a hack put in place to handle ticks close to the axis min or max.  I personally think this was a mistake, but it's there now and hard to remove.

**Comment by jklymak** [comment]
I'll close as I don't think there are any next-actions here...
