### ISSUE TITLE
Different figsize behaviours for Axes3D in 3.2.2 and 3.3.2

### ISSUE THREAD

**Issue by mori-summer** [matplotlib/matplotlib#18906]
### Bug report

**Bug summary**

The `figsize` keyword in matplotlib 3.3.2 does not seem to work for Axes3D as in 3.2.2.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

fig = plt.figure(figsize=(5, 2), dpi=200)
ax = fig.add_subplot(projection='3d')
pltx, plty = np.meshgrid(np.linspace(-5, 5, 300), np.linspace(-5, 5, 300))
pltz = np.sin(pltx) + np.sin(plty)
ax.plot_wireframe(pltx, plty, pltz, cmap='Reds_r', alpha=0.2)
ax.set_zticks([-2, 0, 2])
plt.show()
```

**Actual outcome**

Outcome in *Google Colab* (the same outcome shows on Windows jupyter lab):

![mat3 3 2](https://user-images.githubusercontent.com/68106447/98321184-607fdf00-201f-11eb-96af-9a79e86bd3bb.png)

Outcome by a `script.py` on Windows:

![mat3 3 2 command](https://user-images.githubusercontent.com/68106447/98321250-91601400-201f-11eb-8e8e-c8c81c80c458.png)

**Expected outcome**

Outcome in *Google Colab* by **matplotlib 3.2.2**:

![mat3 2 2](https://user-images.githubusercontent.com/68106447/98321450-10ede300-2020-11eb-9afb-20e131c5c1e6.png)

**Matplotlib version**

  * Operating system: Windows 10 & Google Colab
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.12 (Windows) & 3.6.9 (Colab)
  * Jupyter version (if applicable): 4.6.3 (Windows) & 4.5.0 (Colab)

**Comment by QuLogic** [comment]
This is an expected change; `Axes3D` is no longer distorted to fit in the 2D box: https://matplotlib.org/users/whats_new.html#axes3d-no-longer-distorts-the-3d-plot-to-match-the-2d-aspect-ratio
