### ISSUE TITLE
Current `tight_layout` example raises UserWarning

### ISSUE THREAD

**Issue by brunobeltran** [matplotlib/matplotlib#18904]
### Problem

As can be seen in the [tight layout docs](https://matplotlib.org/tutorials/intermediate/tight_layout_guide.html) (Ctrl-F for "Out:"), `GridSpec.tight_layout` raises a `UserWarning` whenever there are `Axes` in a figure that come from other `GridSpec` besides `self`.

Is this the intended API?

If so, is the use case being demonstrated when that warning is raised (using different subplot specs to render in different `rect`'s within a single figure, without needed nested gridspec's) deprecated? Should we be instead encouraging users to use nested GridSpec's instead for this use-case?

If not, then should there be a flag to `tight_layout` that tells it to ignore other `Axes` in the figure, like a "I know what I'm doing" flag? I can't see a way for `tight_layout.get_subplotspec_list` to differentiate, currently, (and this may be due to a lack of my own imagination) between the two relevant options: 

1. the user accidentally passed in a subplotspec that doesn't encompass the entire figure (I guess that's what the warning is for), OR
2. whether they intentionally are passing in gridspec that only describes a subset of Axes (as it's being used in the example)

**Comment by jklymak** [comment]
What is the warning?

**Comment by brunobeltran** [comment]
The following code:

```python
fig = plt.figure()

gs1 = gridspec.GridSpec(2, 1)
ax1 = fig.add_subplot(gs1[0])
ax2 = fig.add_subplot(gs1[1])

example_plot(ax1)
example_plot(ax2)

gs1.tight_layout(fig, rect=[0, 0, 0.5, 1])

gs2 = gridspec.GridSpec(3, 1)

for ss in gs2:
    ax = fig.add_subplot(ss)
    example_plot(ax)
    ax.set_title("")
    ax.set_xlabel("")

ax.set_xlabel("x-label", fontsize=12)

gs2.tight_layout(fig, rect=[0.5, 0, 1, 1], h_pad=0.5)
``` 

Raises the following warning:

```python
/matplotlib/tutorials/intermediate/tight_layout_guide.py:227: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  gs2.tight_layout(fig, rect=[0.5, 0, 1, 1], h_pad=0.5)
```

This is because when we call `GridSpec.tight_layout`, it check if any of the `Axes` in the figure don't belong in the current `GridSpec` (`self`):

https://github.com/matplotlib/matplotlib/blob/eeef6e59386c6cebe2960213128c6a84906ddda9/lib/matplotlib/gridspec.py#L543-L548

**Comment by jklymak** [comment]
That warning is there for a good reason, and should stay.  In this case the user is doing something sophisticated, it *does* work with `tight_layout` but its really hard to write a check that ignores this case, but catches other incompatible axes.    

I don't think its true that our docs should never issue UserWarnings.

**Comment by jklymak** [comment]
... and of course the new canonical way to do this is with subfigure and constrained_layout

**Comment by brunobeltran** [comment]
Regardless of whether our docs should or should not issue Warnings (I strongly think they should do their best to *not*, but we can have that conversation in the relevant PR). I guess I was hoping there was a way to do this from within GridSpec, but if you don't see a path forward to having some way to catch these cases and not others, then I'll happily defer to your expertise here, sorry for wasting your time.

I'll just make a separate PR modifying the GridSpec example to point to subfigure as the "modern" way to do these more advanced layout tricks.

**Comment by jklymak** [comment]
Sure you can do it with gridspec and `constrained_layout` using subgridspecs (https://matplotlib.org/devdocs/tutorials/intermediate/constrainedlayout_guide.html#use-with-gridspec).  But that would hardly fit in the `tight_layout` demo.  If you simply wanted to remove the example, I wouldn't object.
