### ISSUE TITLE
Arcs with large radii not drawn with jupyter inline backend

### ISSUE THREAD

**Issue by Lucas-Steinmann** [matplotlib/matplotlib#18918]
### Bug report

**Bug summary**

I'm trying to draw arcs with large radii (in comparison to the image size) and with their center outside the image.
The arc is drawn until a specific size at which it should still be visible, but is not drawn.
The width at which it fails, appears random to me.
The bug does not appear when using the default desktop backend (Qt5Agg) but appears both in ``%matplotlib inline`` and ``matplotlib widget`` in Jupyter notebooks

An other issue with Arcs with large radii was fixed here #17547. But since my matplotlib version is 3.2.2, it should be fixed.

**Code for reproduction**

Executed in a Jupyter Notebook (actually Jupyter Lab, but I hope that does not matter):
```python
%matplotlib inline
```
```python
import matplotlib.pyplot as plt
from matplotlib import patches
import numpy as np
```
```python
plt.close()
fig, ax = plt.subplots()
ax.imshow(np.zeros((750, 1180, 3)))
arc = patches.Arc((600,-1490), 1362, 2163*2, angle=0, theta1=0, theta2=360, color='green')
ax.add_patch(arc)
arc = patches.Arc((600,-1490), 1363, 2163*2, angle=0, theta1=0, theta2=360, color='red')
ax.add_patch(arc)
plt.show()
```
The only difference between the two arcs is the extent of the first axis (``width``). 
**Note**: Depending on the figsize and whether I used ``widget`` or ``inline`` as backend, the threshold at which the plotting failed changed drastically (sometimes as low as 800).
This means, to reproduce it, you might have to increase or decrease the width to find the point of failure.

**Actual outcome**
![index](https://user-images.githubusercontent.com/5488609/98564027-27a86a00-22ac-11eb-8c62-872e5cf49551.png)

**Expected outcome**

Both red and green arc are drawn (red would be drawn over green).
The green line doesn't matter actually, it is just there to show that it works with smaller radii.

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline (fails for ``width>=1363``) and and module://ipympl.backend_nbagg (fails for ``width>=914``).

  * Python version: 3.6.9
  * Jupyter version (if applicable): 4.6.3
  * Other libraries:

**Comment by jklymak** [comment]
So we can take jupyter out of this, can you reproduce with `savefig('name.png', bbox_inches='tight')`?  That is what `%inline` does, and will make your problem more reproducible. 

I'm not sure from the above description what `width` is referring to.  If you can create the problem by specifying the figure width in `plt.subplots` that would help

**Comment by Lucas-Steinmann** [comment]
Hi thank you for your quick answer.

> I'm not sure from the above description what width is referring to. If you can create the problem by specifying the figure width in plt.subplots that would help

Sorry, I was referring to the ``width`` parameter of the ``matplotlib.patches.Arc`` classes ``__init__``: ``matplotlib.patches.Arc(xy, width, height, angle=0.0, theta1=0.0, theta2=360.0, **kwargs)``. In my case above, the arc did not draw, if I set the ``width`` of the arc to a value greater than 1362.
The figure size was left as default.

> So we can take jupyter out of this, can you reproduce with ``savefig('name.png', bbox_inches='tight')``? That is what ``%inline`` does, and will make your problem more reproducible.

Ok, good to know. I was able to reproduce it running this as regular python script:
```python3
import matplotlib.pyplot as plt
from matplotlib import patches
import numpy as np
fig, ax = plt.subplots()
ax.imshow(np.zeros((750, 1180, 3)))
arc = patches.Arc(xy=(600,-1490), width=1118, height=4326, angle=0, theta1=0, theta2=360, color='green')
ax.add_patch(arc)
arc = patches.Arc(xy=(600,-1490), width=1119, height=4326, angle=0, theta1=0, theta2=360, color='red')
ax.add_patch(arc)
plt.savefig('name.png', bbox_inches='tight')
```
As you can see I lowered the ``width`` parameter to 1118/1119, since that is now the point at which it fails.
For you, it might be even another value.
**Actual Output**
![name](https://user-images.githubusercontent.com/5488609/98574280-0483b780-22b8-11eb-962f-c43dcbfdddfd.png)

**Expected output**
Red arc is also drawn.

**Comment by tacaswell** [comment]
I can not reproduce this on ~the current default branch, 3.3.2 or 3.2.2

```python
import matplotlib.pyplot as plt
from matplotlib import patches
import matplotlib as mpl
import numpy as np
fig, ax = plt.subplots()
ax.patch.set_color('k')
for i, w in enumerate((1000, 1500, 2000, 2500)): 
    arc = patches.Arc(xy=(600,-1500), width=w, height=4326, angle=0, theta1=0, theta2=360, color=f'C{i%10}', lw=5, linestyle=(i%5, (5, 5)))
    ax.add_patch(arc)
ax.set_xlim(0, 1180)
ax.set_ylim(0, 750)
ax.set_title(mpl.__version__)
fig.savefig('name.png', bbox_inches='tight')
```

**Comment by tacaswell** [comment]
![name](https://user-images.githubusercontent.com/199813/98579486-b907e400-228c-11eb-8520-700d952cd5de.png)

**Comment by jklymak** [comment]
Yes I can't reproduce either.  If fiddling with the `width` changes things, please hardcode the problematic figure width and dpi.  

ie like:
```
fig, ax = plt.subplots(figsize=(4.6, 6.4), dpi=100)
...
fig.savefig('name.png', bbox_inches='tight', dpi=100)
```
so we can all be working off the same page...

**Comment by Lucas-Steinmann** [comment]
I continued debugging and realised today that I do not have a lower matplotlib version. When I ran ``matplotlib.__version__``, I must have messed up my ``PYTHON_PATH``. Should have executed it as part of my example.

Sorry for wasting your time. It works fine know, after installing the current version.
