### ISSUE TITLE
Warn re: Axes3D constructor behavior change in mpl3.4

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#18939]
According to `git bisect`, 261f7062860df88d08451d810d1036853390673d by @anntzer broke the following code, adapted from the examples -- it produces a blank / empty plot:
```
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = Axes3D(fig)
# ax = fig.gca(projection='3d')
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
surf = ax.plot_surface(X, Y, Z)
```
If you comment out the `ax = Axes3D(fig)` line and use `ax = fig.gca(projection='3d')`, it works fine. It also works fine on the preceding commit 34f99a9e82232c4bd53aeb430539d89e2bd2c0c9.

**Comment by anntzer** [comment]
That was actually mostly discussed in https://github.com/matplotlib/matplotlib/pull/18356.  The change was definitely intentional (as both #18356 and #18564 needed it) and documented at https://github.com/matplotlib/matplotlib/blob/master/doc/api/next_api_changes/behavior/18564-AL.rst; do you want to discuss reverting it, or emit a warning, or something else?

**Comment by larsoner** [comment]
Ahh I just didn't notice that change. A warning that it is no longer added would have made finding the problem immediately apparent, so +1 for that solution if it's tractable.

**Comment by anntzer** [comment]
I think we can (temporarily) add a warning in `Axes3D.__del__` checking whether the axes has ever been added to a figure.

**Comment by larsoner** [comment]
Actually a simpler approach would be just to add a `add=True` argument to `Axes3D`. Then people who used it like I did get their behavior preserved, and internally `matplotlib` can do `add=False`. Then there isn't any need for the release notes or user changes. And hopefully it's just two lines `if add: fig.add_subplot(self)` or so.
