### ISSUE TITLE
stairs() crashes with no values and one edge

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#18934]
### Bug report

**Bug summary**

Currently calling `stairs` with no values and a single edge crashes with an AttributeError.

**Code for reproduction**

```python
from pylab import *; stairs([], [0])
```

**Actual outcome**

```
AttributeError: 'StepPatch' object has no attribute '_path'
```

**Expected outcome**

The zero-value, single-edge case can occur naturally when using stairs to plot piecewise-constant functions (rather than pre-binned histograms), and it would seem reasonable to simply be a no-op in that case (except for adjusting the xlims to include the edge position (just like `plot([0], [0])` effectively draws nothing but adjusts the data limits).
Even if we decide that we really do not want to support this case (I would disagree with such a choice), we should at least error out cleanly rather than with an obscure AttributeError.

**Matplotlib version**

  * Operating system:
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
I'd rather error out.

`plot([0], [0])` is well defined: it's a point at (0, 0). It's only by coincidence that you don't see anything because markers are not drawn in the default plot style.

However, a stair with no values and a single edge is graphically ill-defined: You cannot express that in terms of a `Path`, because you have a defined *x*-coordinate for the step position, but no specification for any *y*.

**Comment by anntzer** [comment]
(After https://github.com/matplotlib/matplotlib/pull/18943 we instead get an AttributeError: `need at least one array to concatenate`.)

Is that really a problem?  We can just set the Path to the empty one (`Path([], [])`); I would argue that what really matters is that `patch.get_data()` still returns something sensical (which it does).

**Comment by timhoffm** [comment]
Might work. I'm not sure about

> except for adjusting the xlims to include the edge position (just like plot([0], [0]) effectively draws nothing but adjusts the data limits.

- whether this should happen. - I can imagine both cases in which this is desired and others in which it is not desired.
- where in the code that gets triggered (doesn't come naturally from the empty path).

Note that you need to `Path(np.empty([0, 2]))`. `Path([], [])` does not work (even though you could make that work if you want).

**Comment by anntzer** [comment]
> whether this should happen. - I can imagine both cases in which this is desired and others in which it is not desired.

I would say yes and hope to support the cases where this is not desired using my long-standing proposal to add an `in_autoscale` flag to all artists.  (Then you can toggle it off as desired.)

> where in the code that gets triggered (doesn't come naturally from the empty path).

For all(?) artists this happens in the Axes method, not in the Artist constructor, and the Axes method certainly knows the actual position that has been passed.  But in fact even the StepPatch knows that position (it is stored separately as `._edges` and returned in `.get_data()`.

> Note that you need to Path(np.empty([0, 2])).

Indeed.

**Comment by jklymak** [comment]
Note this goes deeper - `h = Path(np.empty([0, 2]))` instantiates a path, but `print(h)` fails, and who knows what else.  I don't think Path is setup to take empty arrays.

**Comment by anntzer** [comment]
> `print(h)` fails

Does it?  I get
```
Path(array([], shape=(0, 2), dtype=float64), None)
```

**Comment by QuLogic** [comment]
`stairs` hasn't been released yet; we should decide on this now.

**Comment by jklymak** [comment]
I guess - I wasn't too worried about having a zero-array bug.  If someone can get it working with an empty path, then great - I tried and got an error, so I'm not sure how easy it is.

**Comment by anntzer** [comment]
Can you provide a repro for the bug you mention?  As above I can't repro it...
