### ISSUE TITLE
Inconsistent width of thin non-antialiased lines in 1 pixel : 1 unit Axes

### ISSUE THREAD

**Issue by alexiscoutinho** [matplotlib/matplotlib#18945]
### Bug report

**Bug summary**

The width of thin not `antialiased` lines strangely oscillates as `linewidth` is decreased, at least in the following circumstance. For example, on an `Axes` scaled to be 1 pixel : 1 unit and with origin in the x-middle of a pixel (0.09 * 10 in * 155 dpi = 139.5 px left of the `Axes`).

**Code for reproduction**

```python
from matplotlib.pyplot import figure
from matplotlib.patches import Rectangle

fig = figure(figsize=(10, 10), dpi=155)
ax = fig.add_axes([0.09, 0.1, 0.86, 0.8])
ax.minorticks_on()
ax.grid(which='both', ls=':')

for i, x in enumerate(range(100, 600, 50)):
    x -= i % 2
    ax.add_patch(Rectangle((x, 700), 3, 250))
    x += 1.5
    lw = round(1 - i / 10, 1)
    ax.plot([x, x], [710, 940], antialiased=False, color='red', linewidth=lw, snap=True)
    ax.text(x, 670, lw, horizontalalignment='center')

ax.axis([0, 1333, 0, 1240])
fig.savefig("lw.png")
```

Note that the 0.09 in the `Axes` creation makes `snap=True` necessary. Furthermore, 0.86 / 0.8 = 1333 / 1240, making the axis properly scaled. Finally, I'm using a high `dpi` so that the grid lines are 2 pixels wide, easing positions comparison.

**Actual outcome**

Zoom in to view individual pixels...

![lw](https://user-images.githubusercontent.com/26471497/99114091-0955ad80-25cf-11eb-8348-ef99c9cc219a.png)

**Expected outcome**

That the not `antialiased` line width monotonically and discretely decreases as `linewidth` is decreased.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.8.1

Don't know how Python was installed (using an university machine). Matplotlib installed via pip.

**Comment by jklymak** [comment]
Line widths are in points.  If you specify 155 dpi, then the widths are quantized as 1/155 * 72 = 0.465.  That you would get aliasing artifacts as you make the lines thinner and force them to snap is expected behaviour. Thats why we have anti-aliasing.

**Comment by alexiscoutinho** [comment]
Why would there be expected artifacts? Does the snapping behavior (center/edge) depend on the decimals of the linewidth? Besides, in my case, anti-aliasing is not an option.

**Comment by jklymak** [comment]
Well, the Nyquist sampling theorem says you need two pixels to resolve any signal.  So anything finer than that will be aliased.  

Perhaps you could be more specific about what you are trying to do and explain why you want to resolve linewidths that are less than one-pixel.

**Comment by alexiscoutinho** [comment]
I actually don't want widths of less than one pixel. I just thought it was very strange for the final pixel width to fluctuate like that. Before you defined the points to pixels conversion, I was manually exploring the parameter space to find the sweet spot. It would have been much easier to achieve it if any small but non-zero linewidth (without anti-aliasing) always resulted in 1 pixel. I will look into that Nyquist theorem though.

**Comment by jklymak** [comment]
Is it OK to close this?  Aliasing leads to strange effects like this, but if there is no substantive concern we have enough open issues.  OTOH if you want to dig into the code and make sure it makes sense to you, reporting back to discourse.matplotlib.org would be interesting. Thanks...

**Comment by alexiscoutinho** [comment]
@jklymak Thanks. Maybe it would be useful to write a small note about this in the docs. By the way, where is the points to pixels relationship (the formula you gave) defined? I've been using matplotlib for a long time and I was never certain what points really meant. I think future user confusion would be avoided if they were hinted to only use properly calculated widths instead of exploring `lw`'s parameter space.

**Comment by jklymak** [comment]
Points are the same points you specify font sizes in: https://en.wikipedia.org/wiki/Point_(typography) 1 point = 1/72"

**Comment by alexiscoutinho** [comment]
Oh, I just realized something I should have noticed before. If I change the left Axes padding and consequently turn off snapping, linewidths work like a charm, thus `snap` is crucial. So, are the above artifacts related to the order in which linewidth and snap are processed? Would order change the outcome? And is this order question even applicable?

**Comment by alexiscoutinho** [comment]
@jklymak Sorry, but I think my edited mention didn't work. The above is my last doubt.

**Comment by jklymak** [comment]
I saw this, but wasn't sure what you wanted comment on?  In general, you should just use anti-aliasing for sub-pixel lines, or if you don't like that, then use a higher dpi or a vector backend where dpi does not matter.  Sure, you won't have problems with aliasing if you precisely line up your lines with pixels, but if you are going to do that, why not just make an image array and save that instead rather than using high-level general plotting routines like `plot`?

**Comment by alexiscoutinho** [comment]
I understand. I'm using `plot` for its great convenience. I think it would have been more efficient if I looked in the code for the things I mentioned, but it's not a big deal so I'll settle with this issue.
