### ISSUE TITLE
Add sphinx-gallery cross ref instructions to documenting guide

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#18959]
### Problem
The section in the documenting docs on [cross referencing](https://matplotlib.org/devel/documenting_mpl.html#referring-to-other-documents-and-sections) includes instructions for sphinx, but not for sphinx gallery. 

### Suggested Improvement
Add a sentence like "examples and tutorials are .py files rendered into `rst` using the sphinx-gallery plugin. The pattern for cross referencing these documents is `:ref:`sphx_glr_\<folder\>_\<pyfile\>`, for example:
```
:ref:`sphx_glr_tutorials_provisional_mosaic.py`
```
More info at https://sphinx-gallery.github.io/stable/auto_examples/plot_0_sin.html?highlight=cross%20reference#cross-referencing

**Comment by anntzer** [comment]
Actually using
```rst
:doc:`/gallery/foo/bar`
```
is better, as that's not s-g specific but works basically always.

**Comment by story645** [comment]
🤷 seemed to be creating problems on this weeks GSOD call? 
attn: @tacaswell

**Comment by timhoffm** [comment]
I think `:doc:` would be fine. IIRC Jerome tried to reference the heading of the example/tutorial using `:ref:`.
