### ISSUE TITLE
Composite images in PS to not respect axes background color

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#1895]
When multiple images are placed on an axes, a composite image is created containing all of them.  Unfortunately, since PS does not support alpha, the background of the axes does not show through.  The obvious choice is to turn off image compositing, however, `make_image` still expands each image to fill the entire axes, so only the topmost image will be visible.  This will require some finagling, but it seems the thing to do is to stop non-composited images from taking up the entire axes.

**Comment by anntzer** [comment]
afaict this has been fixed, likely by the 2.0 image refactor?
```python
from pylab import *

ax = plt.figure().add_subplot(facecolor="r")
ax.imshow(np.random.rand(4, 4, 4), extent=(0, 2, 0, 2))
ax.imshow(np.random.rand(4, 4, 4), extent=(1, 3, 1, 3))
ax.set(xlim=(0, 3), ylim=(0, 3))
ax.figure.savefig("/tmp/test.ps")
plt.show()
```
has the axes facecolor correctly showing through.
