### ISSUE TITLE
Table CSS needs cleanup

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#18962]
### Bug report

in `mpl.css` we have:
~~~
table.docutils th {
    [...]
    width: 100px;
}
~~~

which causes problems for some tables, e.g. [here](https://49333-1385122-gh.circle-artifacts.com/0/doc/build/html/tutorials/introductory/getting_started.html#sphx-glr-tutorials-introductory-getting-started-py)
![grafik](https://user-images.githubusercontent.com/2836374/99315140-7a60c380-2862-11eb-9a2c-e1ae62e7f767.png)

Note: This only happens on Firefox, not on Safari/Chrome/Edge.

The *width* limit came in via #2184. (ping @NelleV?)

I suppose it could be removed - anyway imposing a fixed width on basically all `<th>` does not seem reasonable. AFAICS there is almost no effect. The only difference I found is that the table in the *loc* parameter in https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.axes.Axes.legend.html#matplotlib.axes.Axes.legend wraps it's header:

with width:
![grafik](https://user-images.githubusercontent.com/2836374/99314758-daa33580-2861-11eb-8953-31348f7b084f.png)

without width:
![grafik](https://user-images.githubusercontent.com/2836374/99314816-fad2f480-2861-11eb-9ff6-97c792c65c90.png)

#### Required Actions:
1. Remove the width parameter.
2. Find out why the legend loc table header wraps and add some CSS to prevent that.

**Comment by sj00coder** [comment]
Sir I want to work on it.

**Comment by timhoffm** [comment]
Thanks! Please do.

**Comment by sj00coder** [comment]
Sir mpl.css do not exist.
![image](https://user-images.githubusercontent.com/65244030/99872098-6374f500-2c05-11eb-84a6-d7878a8ebbd6.png)
Is there any other file or any other source please tell ?

**Comment by timhoffm** [comment]
It's directly in the `_static` folder: https://github.com/matplotlib/matplotlib/blob/master/doc/_static/mpl.css

**Comment by sj00coder** [comment]
is It alright?
![image](https://user-images.githubusercontent.com/65244030/99907610-c482f280-2d03-11eb-85a1-7b5eb41d3634.png)

**Comment by sj00coder** [comment]
> is It alright?
> ![image](https://user-images.githubusercontent.com/65244030/99907610-c482f280-2d03-11eb-85a1-7b5eb41d3634.png)

should I send the PR with the above changes,sir?

**Comment by sj00coder** [comment]
Sir I am trying to open docs in build mode and I got this error.
![image](https://user-images.githubusercontent.com/65244030/100095117-08026b80-2e80-11eb-87bb-6a1547dbd926.png)
please help me out this. Or suggest me a another way to open docs in editable mode.

**Comment by timhoffm** [comment]
You are developing on windows. As the message says, you need to install the "Build Tools for Visual Studio". This is needed to compile the low-level C parts of Matplotlib.

**Comment by DarthK240** [comment]
Hi, is this issue is still open?

**Comment by timhoffm** [comment]
This is still open.

**Comment by Joe-Sin7h** [comment]
Hello! This is my first time contributing to an open source project , I would like to work on this issue .
can i get assigned ?

**Comment by timhoffm** [comment]
Thanks for your interest! We don't have a formal assignment. Since the above users have not reported back, I assume they don't work on it anymore. So you are free to pick it up.

**Comment by rajpratyush** [comment]
hello @timhoffm Is this issue still open for work ??? If so, I would like to work on it 
Please let me know if I can work on this

**Comment by timhoffm** [comment]
@rajpratyush Yes, this is still open.

**Comment by rajpratyush** [comment]
can you please guide me ? @timhoffm

**Comment by timhoffm** [comment]
You need to find out how CSS has to be adapted so that we can remove the above mentioned `width: 100px` entry, but the table in the loc parameter in https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.axes.Axes.legend.html#matplotlib.axes.Axes.legend does not wraps it's header.

To do so, you can directly work with the CSS tools in your browser on the above page.

Unfortunately, I'm not a CSS expert and thus cannot give any tips what to look for when adapting the CSS.

**Comment by rajpratyush** [comment]
@timhoffm since you mentioned this occurs only on Firefox how about adding a CSS property reserved only for Firefox browsers. but we do need to observe the effects of removing the width parameter in other browsers. I can test it on Edge/Chrome/Firefox. can you provide me the changes came into effect when you removed the width parameter in other browsers? Did they worked fine? else we have add CSS property reserved for Chrome and other browsers.(I personally believe that Edge/Chrome can have same CSS property as both of them work on chromium projects now)

**Comment by rajpratyush** [comment]
@timhoffm today I was testing the page if the page worked fine when width was set to 102 px in Firefox and even it worked fine in all other browsers chrome and edge as well

**Comment by rajpratyush** [comment]
And considering why it is being wrapped in 2 lines, there is some inherited css parameter that is causing this to happen @timhoffm i live tested it.

**Comment by timhoffm** [comment]
> Today I was testing the page if the page worked fine when width was set to 102 px

I'm afraid I'm not following. We don't want a predefined width at all, because that cuasing problems with other tables with much longer headings.

> And considering why it is being wrapped in 2 lines, there is some inherited css parameter that is causing this to happen @timhoffm i live tested it.

Great! Can you be specific which inherited CSS parameter is causing this?

**Comment by rajpratyush** [comment]
Yes sure lemme test it again and i shall deliver the report by the end of the day @timhoffm

**Comment by rajpratyush** [comment]
@timhoffm removed the width parameter and added few lines and now tested it on chrome /Firefox/Edge and changes are exactly as you wanted.

**Comment by rajpratyush** [comment]
@timhoffm Check the PR #19387

**Comment by rajpratyush** [comment]
@timhoffm can you please review the PR
