### ISSUE TITLE
Method only preparing and returning a figure 

### ISSUE THREAD

**Issue by MCilento93** [matplotlib/matplotlib#18960]
I gave a look around but I didn't find a clear explanation for this doubt.

I want to 'prepare' figures of various type (imshow, plot, histogram and so forth) in methods returning the figure itself. My question is: **how can I avoid that along the running, the method plots the figure** (I am using ipython console through spyder or jupyter) ?
And using plt.close() at the end of the method works, but the figure for a fraction of time will be showed. 

Is this correct or am I thinking wrong? Is there a way to only prepare and not show?

Thank you,
Sincerely

**Comment by QuLogic** [comment]
I think you are asking about disabling [interactive mode](https://matplotlib.org/users/interactive.html#interactive-mode).

**Comment by MCilento93** [comment]
Ohh maybe yes 😊
I will give a try today (in the core module when figures are created I'll set plt.ion() in the main for testing purposes.
Elsewhere at the top of the module I'll set plt.ioff().

**Comment by timhoffm** [comment]
You can use `plot.ioff()` as a context manager in your helper functions.

**Comment by QuLogic** [comment]
That's not in a release yet.

**Comment by MCilento93** [comment]
matplotlib in my current conda environment is at the release 3.1.1.
Not enough?

**Comment by timhoffm** [comment]
Closing as solved. Please report back if there is anything left to do.
