### ISSUE TITLE
disabling rcParams['keymap.all_axes'] gives DeprecationWarning

### ISSUE THREAD

**Issue by Lewn** [matplotlib/matplotlib#18979]
### Bug report
When disabling rcParams['keymap.all_axes'] programatically, I get a DepricationWarning. From the source code, it seems like setting it to None should be the course of action, but that gives a ValueError

Relevant source code:
https://github.com/matplotlib/matplotlib/blob/e125ffbae5662bf215ff258148e52bcae999921b/lib/matplotlib/__init__.py#L574-L586
https://github.com/matplotlib/matplotlib/blob/e125ffbae5662bf215ff258148e52bcae999921b/lib/matplotlib/__init__.py#L615
https://github.com/matplotlib/matplotlib/blob/e125ffbae5662bf215ff258148e52bcae999921b/lib/matplotlib/__init__.py#L623-L626
https://github.com/matplotlib/matplotlib/blob/e125ffbae5662bf215ff258148e52bcae999921b/lib/matplotlib/__init__.py#L636-L640

**Bug summary**

**Code for reproduction**
```python
In [1]: from matplotlib import rcParams, __version__

In [2]: rcParams['keymap.all_axes'] = ''
<ipython-input-2-4856d63685f1>:1: MatplotlibDeprecationWarning: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  rcParams['keymap.all_axes'] = ''

In [3]: rcParams['keymap.all_axes'] = None
Traceback (most recent call last):

  File "<ipython-input-3-f2698027375d>", line 1, in <module>
    rcParams['keymap.all_axes'] = None

  File "C:\ProgramData\Miniconda3\envs\py38_forge_20201116\lib\site-packages\matplotlib\__init__.py", line 679, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None

ValueError: Key keymap.all_axes: Expected str or other non-set iterable, but got None


In [4]: __version__
Out[4]: '3.3.3'
```

**Expected outcome**

Being able to unbind the 'a' key from the keymap without a warning.

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.6
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Installed through conda, using the conda-forge channel

**Comment by timhoffm** [comment]
The deprecation has expired in 3.5 via #19796.
