### ISSUE TITLE
Add scale(x)(y) parameter(s) to imshow as in plot

### ISSUE THREAD

**Issue by alexiscoutinho** [matplotlib/matplotlib#18970]
### Problem

In situations where an `Axes` has a large background image/map (`extent` greater than axis limits) and the axis limits are supposed to be controlled by other artists, like paths, it would be very helpful to have toggling parameters like `scalex` and `scaley` as in `Axes.plot`. Right now, even if you fix the limits after `imshow`, the moment you let autoscale do its thing (which is desired) it rescales to show the whole image.

### Proposed Solution

A very simple and probably naive solution would be to wrap the `imshow` line below in an `if` where `scalexy` is `True` by default:

```python
if scalexy:
    im.set_extent(im.get_extent())
```

**Comment by anntzer** [comment]
I think that's basically https://github.com/matplotlib/matplotlib/pull/15595 (more or less...)?

**Comment by alexiscoutinho** [comment]
Yes.

**Comment by timhoffm** [comment]
I close this in favor of #15595. It's better to have this as an Artist property rather than putting explicit `scalex`/`scaley` parameters in all kinds of plot functions.
