### ISSUE TITLE
Contour label demo would benefit from some more info and/or references.

### ISSUE THREAD

**Issue by jonnyhtw** [matplotlib/matplotlib#18974]
### Problem
Hi there

* I found the first example in the [contour label demo](https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/contour_label_demo.html) to be unclear because it uses the format statements `%r` and `%%` without explanation or reference.
* I have included a screenshot of the part of the docs that I am referring to.

### Suggested Improvement

* I think it would improve the documentation to include further information on this or provide a reference for further reading.

All the best.

Jonny Williams

![image](https://user-images.githubusercontent.com/12940715/99595468-a5613800-2a59-11eb-9098-bfeff164cac0.png)

**Comment by timhoffm** [comment]
This is "only" standard Python percent formatting (`%r` formatting with `repr()`, `%%` being a literal percent).

Anyway, The formatting has been replaced in #18976 
For the updated version see https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contour_label_demo.html

**Comment by jonnyhtw** [comment]
> This is "only" standard Python percent formatting (`%r` formatting with `repr()`, `%%` being a literal percent).
> 
> Anyway, The formatting has been replaced in #18976
> For the updated version see https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contour_label_demo.html

Thanks Tim, that's a lot clearer now I think. 😄
