### ISSUE TITLE
%matplotlib defaults

### ISSUE THREAD

**Issue by SimonBXu** [matplotlib/matplotlib#18982]
Hi, 

I entered `%matplotlib inline ` into jupyterlab 2.2.6, and everything works. I just didn't like it and wanted to switch back to whatever my default setting was. I've never made adjustment to matplot until today. My plots used to resize when I resized my window but it was not interactive nor was I using `%matplotlib widget`. 

I've tried `%matplotlib notebook` but it tells me `Javascript Error: IPython is not defined`.  Searching online, I've tried just `%matplotlib`, `%matplotlib nbagg`, `%matplotlib nbAgg` - none of them which works. As I'm switching around (clearing the output, killing the kernel, and refreshing the page - even restarting jupyter), I either get the same JS error or I get the message "No module ipympl" or "GUI cannot be switched: use [notebook/widget/qt etc.]" - at which point it just picks something random because it says it switched to notebook, but I run the plot and I get the JS error. So essentially, I am just going around in circles. (Edit: some time the output runs but nothing is displayed)  

I went ahead and installed `ipympl` and the `jupyter-matplot extension` and tried `matplotlib widget` but the output looks entirely different. For example, I was unable to get the plot to display directly below each chunk of code

How can I get back to the non-widget default?

**Comment by jklymak** [comment]
Please see: https://stackoverflow.com/questions/51922480/javascript-error-ipython-is-not-defined-in-jupyterlab   

It really seems like you just want to use jupyter, and not jupyter lab.  Please discuss on discourse.matplotlib.org if you need more help, but this is not a bug on the Matplotlib side.

**Comment by SimonBXu** [comment]
@jklymak Sorry, but I don't understand why this issue was closed. To your points, 1. I have been using jupyterlab for quite some time now so I rather stick with it. 2. I also never said it was a bug on the matplot side, which is what I thought community support was for and also why I did not post this in Bug report. 

I have ready gone through these stackoverflow channels and spent about 2 hours googling, `%matplotlib inline` works fine but it displays as a static image. This was not the setting prior today, and I did not use the widget prior to today either, I simply want to get back to where I was for jupyterlab and I can't find a solution.

**Comment by jklymak** [comment]
GitHub issues are for issues not user help.  But someone will probably help you on the discourse page.  Please take this there.  Thanks.

**Comment by SimonBXu** [comment]
The community/support says "If you have a usage question" but thanks. I'll move it to discourse.

**Comment by jklymak** [comment]
```
<!--
**If your issue is a usage question, please submit it in one of these other channels instead:**
- The Matplotlib community forum: https://discourse.matplotlib.org/
- StackOverflow with the Matplotlib tag: https://stackoverflow.com/questions/tagged/matplotlib

The issue tracker is used only to report issues and feature requests. For
questions, please use either of the above platforms. Most question issues are
closed without an answer on this issue tracker. Thanks for your understanding.
-->
```
