### ISSUE TITLE
exit with "macOS 11 or later required !" on macOS 11.1

### ISSUE THREAD

**Issue by cbosoft** [matplotlib/matplotlib#18988]
### Bug report

**Bug summary**

Trying to plot results in exit 134 with message "macOS 11 or later required !" on macOS 11.1 beta.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
plt.plot([0], [0]) # -> crash
```

Perhaps an issue in TkAgg backend: does not occur in plain 'agg', or 'macosx' backends.

**Actual outcome**

```
$ python                   
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from matplotlib import pyplot as plt
>>> plt.plot([0], [0])
macOS 11 or later required !
[1]    45316 abort      python
```

**Expected outcome**

A Lines2D object to be returned.

**Matplotlib version**

  * Operating system: macOS 11.1 (beta)
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.6
  * Jupyter version (if applicable): na
  * Other libraries: na

python installed on mac from homebrew. matplotlib then installed via pip.

**Comment by jklymak** [comment]
Can you try `import tkinter as tk`?  If that fails, you will have to report to python.  I'm skeptical this is something we can help with.

**Comment by cbosoft** [comment]
Bizarrely, no change it seems to be working okay now. Sorry for the bug report clutter, I think something weird happened as my laptop updated which has resolved itself after rebooting.

**Comment by mbreyt** [comment]
I have the same issue (only difference is the exit code : 1389)
Rebooting didn't work for me !

**Comment by EiraBaccay** [comment]
I also have the same issue

**Comment by OkkarMin** [comment]
I too am having the same issue, the problem surface after updating to

MacOS 11.1 (20C69)
XCode Version 12.3 (12C33)

**Comment by jklymak** [comment]
Did any of you try to import tkinter as suggested above?

**Comment by OkkarMin** [comment]
Yup I did, take a look at screenshot below

![Screenshot 2020-12-21 at 2 36 58 PM](https://user-images.githubusercontent.com/24297303/102746842-0900bd00-439a-11eb-9112-d7ba8da488f7.png)

![Screenshot 2020-12-21 at 2 37 03 PM](https://user-images.githubusercontent.com/24297303/102746847-0b631700-439a-11eb-974d-d0f4a0108fd6.png)

**Comment by jklymak** [comment]
This is a python issue: https://bugs.python.org/issue42480  Suggest you try Qt5 or macOSx backend as an alternative.
