### ISSUE TITLE
Latex path not found on macOS

### ISSUE THREAD

**Issue by andreamoro-git** [matplotlib/matplotlib#18991]
matplotlib cannot find the LaTeX installation on my mac (OS Catalina 10.15.7). The error is

`RuntimeError: Failed to process string with tex because latex could not be found`

LaTeX works fine on the command prompt and so do the commands dvips and gs.

I'm trying the test case from documentation using Python 3.7 on spyder
```
import matplotlib as mpl
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"]})

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Palatino"],
})

import numpy as np
import matplotlib
matplotlib.rcParams['text.usetex'] = True
import matplotlib.pyplot as plt


t = np.linspace(0.0, 1.0, 100)
s = np.cos(4 * np.pi * t) + 2

fig, ax = plt.subplots(figsize=(6, 4), tight_layout=True)
ax.plot(t, s)

ax.set_xlabel(r'\textbf{time (s)}')
ax.set_ylabel('\\textit{Velocity (\N{DEGREE SIGN}/sec)}', fontsize=16)
ax.set_title(r'\TeX\ is Number $\displaystyle\sum_{n=1}^\infty'
             r'\frac{-e^{i\pi}}{2^n}$!', fontsize=16, color='r')
```

**Comment by tacaswell** [comment]
Can you look at 

```python
import os
print(os.environ['PATH'])
```

and verify that it matches the path you see from the shell?

**Comment by andreamoro-git** [comment]
Thanks. No they are different, a bunch of things are missing, in particular this: /Library/TeX/texbin
Any way to add it?

**Comment by andreamoro-git** [comment]
Another piece of info, hopefully it helps. The path that shows up by the print command is in /etc/paths, the one missing is in /etc/paths.d/TeX which apparently is ignored by Python.

**Comment by andreamoro-git** [comment]
Hi I narrowed down this bug to an anaconda issue. The path issue does not arise when running python from the command line, nor if opening spyder from the command line. It arises only when running spyder from anaconda. 

I think this can be safely closed.

**Comment by andreamoro-git** [comment]
See comment above

**Comment by tacaswell** [comment]
Glad you got this sorted @andreamoro-git !

**Comment by Cyrkhan** [comment]
I have the same problem with IDLE furnished with Python 3.13 : it cannot find LaTeX which is properly installed on my Mac (Mac OS Sequoia). So :
- If I run the above test code in a IDLE shell, il doesn't found LaTeX,
- If I open the same code in Terminal shell, it works, but I'm facing the Apple bug : `Python[2002:42657] +[IMKInputSession subclass]: chose IMKInputSession_Modern`
In both cases, something goes wrong. And I don't see howor where to fix the LaTeX path for python IDLE.
