### ISSUE TITLE
RecursionError: maximum recursion depth exceeded&AttributeError: module 'matplotlib.pyplot' has no attribute 'switch_backend'

### ISSUE THREAD

**Issue by NeilChangYanpeng** [matplotlib/matplotlib#19004]
I got error when importing matplotlib in python console!

![图片](https://user-images.githubusercontent.com/41663460/100222154-a829c480-2f54-11eb-861f-f6571b0c1528.png)

But there is no error in Terminal when using matplotlib.

![图片](https://user-images.githubusercontent.com/41663460/100222343-e8894280-2f54-11eb-90e3-033e85f67402.png)

Does anyone know how to solve it, thank you!

**Comment by WeatherGod** [comment]
This looks like a bug or some sort of bad interaction with an older version
of PyCharms. I would check for an update to PyCharms first.

**Comment by NeilChangYanpeng** [comment]
Thank you for your advice，I will have a try.

**Comment by jklymak** [comment]
I'll close, but feel free to ask for a reopen if you think this is something matplotlib can help with.
