### ISSUE TITLE
Formalize discouraged API (= softer deprecations)

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#19017]
### Proposal

Some parts of our API should not be used anymore. However they are potentially too widely used so that we cannot deprecate them. We sometimes informally use "soft deprecation" for these.

I propose to call these "discouraged API" instead and formalize what that means.

### Details

Terminology: "deprecated" has the connotation of being removed some time in the future. "soft-deprecated" is not a well-defined and commonly known term AFAICS. So "discouraged" is more clear to the end-user.

We'll then have to following categories of API not to be used anymore:

- *deprecated*: Has a removal version set.
- *pending deprecation*: Is planned to be deprecated in the future. This is essentially a signal to downstream libraries that they should not use this anymore, and can prevent end users seeing deprecation warnings from internal Matplotlib calls of downstream libraries.
- *discouraged*: Should not be used, but will be available indefinitely for backward compatibility.

Deprecations and pending deprecations have already a formalized way of documentation and warning.

Discouraged API should get a corresponding note in the docs. To be discussed whether we also want to warn on it's usage. I tend to say no to not annoy users.

**Comment by jklymak** [comment]
This seems reasonable to me.  Are there similar standards in other packages?  That would help us decide how to make this more public.

**Comment by timhoffm** [comment]
I'm not aware of any standards in other packages. I wouldn't be surprised if Matplotlib is the package that has to carry the most discouraged API around (because of the combination of wide-spread use and age / change of paradigms). Probably it's not an issue big enough for most other libs.

**Comment by story645** [comment]
Apparently the [R lifecycle package](https://cran.r-project.org/web/packages/lifecycle/vignettes/lifecycle.html) uses the term soft-deprecate, but I'm 💯 on board w/ switching to "discouraged"  or something equally more discriptive/less idiomatic.

**Comment by mwaskom** [comment]
I suggested on gitter a while back (is it possible to search?) an "opinionated API" mode that one could activate to generate warnings on usage of discouraged aspects of the API. I had in mind things like the state-machine interface, but that could get folded in here too. Would require some work to really be useful, but it would go a long way towards helping people adopt standardized, modern usage patterns without totally breaking the millions of lines of (bad but effective) matplotlib code on stackoverflow, etc..

**Comment by timhoffm** [comment]
We have implicitly adopted the following standard for discouraged API (which is undocumented):

---

API that we do not want users to use in new code anymore, but which we don't want to deprecate and revmove for backward-compatibility reasons, should be marked as *deprecated* in the following way:

- If a whole function is discouraged:
  - add `.. admonition:: Discouraged` in the first text block after the summary line.
    *Motivation:* This information should be very pronunced in the docstring
  - prepend `[*Discouraged*]` to the summary line of the docstring.
    *Motivation*: We want the discouraged flag to show up in function overviews (e.g. [get_xaxis here](https://matplotlib.org/stable/api/axes_api.html#axis-limits)).

- If a parameter (or certain values of it) is discouraged add `.. admonition:: Discouraged` to an appropriate place in the parameter description.

---

I propose to make this official. This needs

1. General approval - **If you agree with the above, please upvote this comment**
2. Documentation, possibly at https://matplotlib.org/stable/devel/contribute.html#api-changes and/or https://matplotlib.org/stable/devel/document.html

**Comment by rcomer** [comment]
I also like the suggestion at https://github.com/matplotlib/matplotlib/issues/19017#issuecomment-735240421 for some opt-in warnings.  Our group has a lot of old code that generates many plots.  It would be great to be able to identify this sort of thing easily when doing other clean-up work.

**Comment by timhoffm** [comment]
> I also like the suggestion at https://github.com/matplotlib/matplotlib/issues/19017#issuecomment-735240421 for some opt-in warnings. Our group has a lot of old code that generates many plots. It would be great to be able to identify this sort of thing easily when doing other clean-up work.

Sure, that's a reasonable extension. Probably a good idea to create decorators for it. Organisationally, this is an additional feature and second step based on top of the above proposal.

**Comment by timhoffm** [comment]
I consider the formalization complete through https://github.com/matplotlib/matplotlib/pull/29078 and https://github.com/matplotlib/matplotlib/issues/19017.

@rcomer If you want to further enhance by creating opt-in warnings. Please create an additional issue or PR to track that.
