### ISSUE TITLE
matplotlib.use(BACKEND) does not persist in the notebook scope depending on import order

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/matplotlib#19032]
### Bug report

**Bug summary**

When trying to automatically switch to the `nbAgg` (or `notebook`) backend in a module `__init__.py`, I am seeing some strange behaviour depending on if I import `matplotlib.pyplot` before or after I set the backend.

**Code for reproduction**

I make a small dummy module: in a folder named `dummy`, I create a `__init__.py` file that contains

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.use('nbAgg')
```

Then, inside the notebook, I have (note that `import dummy` is in a separate cell.
```python
import dummy
```
```python
import matplotlib
matplotlib.get_backend()
```

This prints `'module://ipykernel.pylab.backend_inline'`.

Now if I change the backend **before** i import `pyplot` in `dummy/__init__.py`:
```python
import matplotlib as mpl
mpl.use('nbAgg')
import matplotlib.pyplot as plt
```
Then `matplotlib.get_backend()` prints `'nbAgg'`.

Even more interestingly, if I go back to importing `pyplot` before I switch the backend:
```python
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.use('nbAgg')
```
but then put all the notebook code in the same cell, `get_backend()` prints `nbAgg`. However, when I call it a second time, it then prints `'module://ipykernel.pylab.backend_inline'`.
![Screenshot at 2020-11-27 14-13-44](https://user-images.githubusercontent.com/39047984/100453245-f2c55100-30ba-11eb-8dd7-d40c93e2f9ab.png)

It seems that something happens when `pyplot` is imported that occurs after the cell has finished executing.

**Matplotlib version**

This happens with matplotlib 3.3.3 but **not** with version 3.2.2. With 3.2.2 the `get_backend()` always returns `nbAgg`, as expected.

I observe the same behaviour when trying to use the `widget` backend (`'module://ipympl.backend_nbagg'`) instead of `nbAgg`.

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 3.7
  * Jupyter version (if applicable): notebook 6.1
  * Other libraries: 

Installed in `conda` env from `conda-forge`.

**Comment by QuLogic** [comment]
I cannot reproduce this using:
```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.1
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```
The inline backend comes from ipykernel/IPython, and what triggers it to load is not really controlled by Matplotlib. I suspect it is one of those that changed, or does unsupported things, and not a change from 3.2.2.

> Now if I change the backend **before** i import `pyplot` in `dummy/__init__.py`:

Note that this is still always a good idea, as you never can be certain what modules `pyplot` might load and initialize before your desired backend.

**Comment by jklymak** [comment]
I don't think there is an action item here, but feel free to request a re-open.
