### ISSUE TITLE
matplotlib.mathtext dont support nth power

### ISSUE THREAD

**Issue by Doctor-Young** [matplotlib/matplotlib#19047]
When using Axes.text(), I found that it seems can't draw the nth power. For example, \sqrt[n]{a} or \sqrt[\uproot{3}n]{a} cannot be parsed. 

An error will occur： Expected \sqrt{value}, found'['

I think the n-th power is a very common symbol. I don't know if there are other ways of expression. If so, please let me know. If not, I suggest adding support for it.

**Comment by anntzer** [comment]
Thanks for the report; I believe this is already tracked at https://github.com/matplotlib/matplotlib/issues/8665.
