### ISSUE TITLE
v3.3.0 Regression, Animation draws artists multiple times.

### ISSUE THREAD

**Issue by has2k1** [matplotlib/matplotlib#19040]
### Bug report

**Bug summary**

The Animation classes `ArtistAnimation` and `FunAnimation` over draw onto the figure causing thick lines and "blocky" texts. This is a regression that ships in v3.3.0 (i.e v3.2.2 is good) and is still present in v3.3.3.

**Code for reproduction**
```python
import itertools

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# for animation in the notebook
from matplotlib import rc
rc('animation', html='html5')

def data_gen():
    for cnt in itertools.count():
        t = cnt / 10
        yield t, np.sin(2*np.pi*t) * np.exp(-t/10.)


def init():
    ax.set_ylim(-1.1, 1.1)
    ax.set_xlim(0, 10)
    del xdata[:]
    del ydata[:]
    line.set_data(xdata, ydata)
    return line,

fig, ax = plt.subplots()
fig.set_size_inches(8, 6)
line, = ax.plot([], [], lw=2)
ax.grid()
xdata, ydata = [], []


def run(data):
    # update the data
    t, y = data
    xdata.append(t)
    ydata.append(y)
    xmin, xmax = ax.get_xlim()

    if t >= xmax:
        ax.set_xlim(xmin, 2*xmax)
        ax.figure.canvas.draw()
    line.set_data(xdata, ydata)

    return line,

ani = animation.FuncAnimation(fig, run, data_gen, interval=10, init_func=init)
ani
```

**Actual outcome (v3.3.3)**

![bad-v3 3 3](https://user-images.githubusercontent.com/780341/100518191-1fec2f00-31a1-11eb-9bed-8d13e71b2f90.png)

**Expected outcome (v3.2.2)**

![good-v3 2 2](https://user-images.githubusercontent.com/780341/100518207-32feff00-31a1-11eb-9c01-9857c75755c6.png)

The regression is clearly visible for the ticks and tick labels and less visible (in above example) is that it affects the plotting and legend too.

**Comment by dopplershift** [comment]
What OS/platform are you running on?

**Comment by has2k1** [comment]
> What OS/platform are you running on?

os: Linux
installation-method: pip

**Comment by QuLogic** [comment]
Bisects to 57462b6 by @anntzer, because the Figure facecolor is transparent. I'm not sure why that is though, since the rcParam default is 'white' (no transparency).

**Comment by anntzer** [comment]
I can't repro this :/

**Comment by QuLogic** [comment]
Oh, it's not nbagg, but because the inline backend (from ipykernel, not Matplotlib) sets the backend transparent. Like JPEG, we should probably merge the background with white when saving animations (though only for formats that don't support transparency?) Though it seems that animations don't save with transparency correctly then?

**Comment by has2k1** [comment]
> Bisects to [57462b6](https://github.com/matplotlib/matplotlib/commit/57462b6477e727d96be76310f19d203440ba3e35) by @anntzer, because the Figure facecolor is transparent. I'm not sure why that is though, since the rcParam default is 'white' (no transparency).

It looks rather innocuous!

**Comment by anntzer** [comment]
> Like JPEG, we should probably merge the background with white when saving animations (though only for formats that don't support transparency?) Though it seems that animations don't save with transparency correctly then?

I guess so?  I'll readily admit no knowledge whatsoever of the inline backend and notebook interactions :)

**Comment by billbrod** [comment]
I've had this same issue (I was comparing v3.3.0 and v3.1.0, running in Jupyter lab), and found out that `rcParams['savefig.facecolor']` was `'auto'`. Changing it back to `'white'` (as had been the case in v3.1.0) fixed the issue.

**Comment by tacaswell** [comment]
I think we are missing a "clear the buffer" someplace.  As this is not using blitting we should not be preserving state across draws...

**Comment by billbrod** [comment]
I actually was doing this with `blit=True` (sorry, missed the fact that the original post didn't).

**Comment by jklymak** [comment]
I'm a little lost as to the problem here.  Is this only an issue in the notebook?  Using which backend?  Because the above works fine in Qt5agg

**Comment by tacaswell** [comment]
I think this is very specific to the inline backend.

**Comment by tacaswell** [comment]
it seems that the `renderer.clear()` method in Agg is not doing what we think it should be doing...

**Comment by tacaswell** [comment]
```diff
diff --git a/src/_backend_agg.cpp b/src/_backend_agg.cpp
index 6ae11167e8..e31e1a9e31 100644
--- a/src/_backend_agg.cpp
+++ b/src/_backend_agg.cpp
@@ -47,7 +47,7 @@ RendererAgg::RendererAgg(unsigned int width, unsigned int height, double dpi)
       rendererBin(),
       theRasterizer(8192),
       lastclippath(NULL),
-      _fill_color(agg::rgba(1, 1, 1, 0))
+      _fill_color(agg::rgba(1, 1, 1, 1))
 {
     unsigned stride(width * 4);
 

```

fixes the problem so this is definitely an Agg bug.

**Comment by tacaswell** [comment]
no, I think I am being much too quick to jump to conclusions.  It is definitely alpha related, but clear works correctly :relaxed: .

I think that the @QuLogic was on the right path in https://github.com/matplotlib/matplotlib/issues/19040#issuecomment-736337467 .  It seems that h264 does not support alpha, I suspect that that means the alpha channel is just being dropped and the very blocking output is due to the anti-aliasing turning into an effective dilation operation.

A patch that fixes this:

```diff
diff --git a/lib/matplotlib/animation.py b/lib/matplotlib/animation.py
index af9b9b82b3..acf44938ce 100644
--- a/lib/matplotlib/animation.py
+++ b/lib/matplotlib/animation.py
@@ -37,7 +37,7 @@ import matplotlib as mpl
 from matplotlib._animation_data import (
     DISPLAY_TEMPLATE, INCLUDED_FRAMES, JS_INCLUDE, STYLE_INCLUDE)
 from matplotlib import _api, cbook
-
+import matplotlib.colors as mcolors
 
 _log = logging.getLogger(__name__)
 
@@ -1094,6 +1094,9 @@ class Animation:
 
         if savefig_kwargs is None:
             savefig_kwargs = {}
+        else:
+            # we are going to mutate this below
+            savefig_kwargs = dict(savefig_kwargs)
 
         if fps is None and hasattr(self, '_interval'):
             # Convert interval in ms to frames per second
@@ -1149,6 +1152,18 @@ class Animation:
             _log.info("Disabling savefig.bbox = 'tight', as it may cause "
                       "frame size to vary, which is inappropriate for "
                       "animation.")
+
+        facecolor = savefig_kwargs.get('facecolor',
+                                       mpl.rcParams['savefig.facecolor'])
+        if facecolor == 'auto':
+            facecolor = self._fig.get_facecolor()
+
+        def _pre_composite_to_white(color):
+            r, g, b, a = mcolors.to_rgba(color)
+            return a * np.array([r, g, b]) + 1 - a
+
+        savefig_kwargs['facecolor'] = _pre_composite_to_white(facecolor)
+        savefig_kwargs['transparent'] = False   # just to be safe!
         # canvas._is_saving = True makes the draw_event animation-starting
         # callback a no-op; canvas.manager = None prevents resizing the GUI
         # widget (both are likewise done in savefig()).

```

lifting what we do with jpeg to pre-composite to white.

**Comment by anntzer** [comment]
Seems reasonable. Would be nice to figure out if "transparent animation" is a thing at all?

**Comment by tacaswell** [comment]
I suspect it is encoding dependent as animated gifs definitely support transparency.
