### ISSUE TITLE
Crash when plotting scatterplot

### ISSUE THREAD

**Issue by justingruenberg** [matplotlib/matplotlib#19058]
### Bug report

**Bug summary**

When plotting a scatter plot, the script crashes.  There is no error message displayed, it just *ends*.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

xs = [1, 2, 3]
ys = [1, 2, float("nan")]

plt.plot(xs, ys)
plt.show() # works as expected, third point (3, NaN) isn't displayed

plt.scatter(xs, ys)
plt.show() # shows window, entire chart is black.  

print("done") # this is never reached
```

**Actual outcome**

The first plot using `plt.plot` is displayed.  The second plot using `plt.scatter` is not displayed.  The print statement is not reached.

**Expected outcome**

Scatter plot is displayed, or an exception is thrown.

**Matplotlib version**
  * Operating system: Windows 10 19042.662
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.5
  * Other libraries: [env.txt](https://github.com/matplotlib/matplotlib/files/5631995/env.txt)

**Comment by QuLogic** [comment]
Does this work?
```
python -c "from PyQt5.QtWidgets import *; app = QApplication([]); win = QMainWindow(); win.show(); app.exec()"
```

**Comment by justingruenberg** [comment]
Yes, it opens up a blank window.

**Comment by tacaswell** [comment]
@justingruenberg If you reverse the order of the plots does the scatter work and the plot fail?  When we get black windows that is usually a sign that something is going wrong with the GUI integration (not with the plotting code).  It looks like you have a pretty old version of qt/pyqt5, can you try updating those to the latest (suggest a new conda environment) .

If you do 

```python
import matplotlib
matplotlib.use('tkagg')
```

before you make your first figure do both work?

**Comment by justingruenberg** [comment]
If I reorder the plots so the scatter is first, no window appears at all.  The script ends with no warning/errors.

Adding in the code to switch to tkagg, the same behavior happens (no window, script ends, no warning, no errors)

I changed the script to only do the scatter, and savefig instead of show.

```python
import matplotlib.pyplot as plt

import matplotlib
matplotlib.use('tkagg')

xs = [1, 2, 3]
ys = [1, 2, 3]

plt.scatter(xs, ys)  
plt.savefig("test.png")

print("done") # this is never reached
```

Same behavior, for this too. Same with/without the lines to use tkagg. Same with PNG and SVG.

Created a new environment with these commands:
```console
> conda create --name test-env
> conda activate test-env
> conda install matplotlib
```

Same results.  Though, this is the same as before which was a new environment that I upgraded matplotlib to 3.1.3.  

Updating pyqt (which brings in qt 5.12.9)
```console
> conda install pyqt=5.12.3
```

The window opens and stays open longer than before.  The background is standard control color and not black.  The window closes, no console output at all.

I'm going to try to delete my entire conda install and start fresh later today.

**Comment by justingruenberg** [comment]
Ok... deleted miniconda and tried reinstalling.

The latest miniconda installer didn't work for me.  The installer showed an error about not creating menus.  Uninstalled, rebooted.

Tried an older miniconda installer (4.7.12.1), that worked.    Installed matplotlib.  Tried the script, and same behavior (black screen, crash).

I've got no idea what's going on here.

**Comment by justingruenberg** [comment]
I attached a debugger to the process, and this is the exception when it crashes.

Exception thrown at 0x00007FFD2A812042 (mkl_core.dll) in python.exe: 0xC0000005: Access violation writing location 0x0000008F873E325E.

**Comment by jklymak** [comment]
Seems like your issues are more fundamental than matplotlib.    Probably a dll clash.  You probably need to take this up w/ anaconda support.  If its OK, I am going to close because we can't really help any further.  But if you again narrow down to a reproducible matplotlib issue, please feel free to open a new issue.

**Comment by justingruenberg** [comment]
I agree -- thanks for the help, though.
