### ISSUE TITLE
Docs 3.3.3 PDF missing 404

### ISSUE THREAD

**Issue by davidyakobovitch** [matplotlib/matplotlib#19065]
### Problem

Link for 3.3.3 is broken on public site for pdf docs
https://matplotlib.org/3.3.3/Matplotlib.pdf

https://matplotlib.org/3.3.3/contents.html

### Suggested Improvement

PDF on page needs to be fixed or file uploaded

**Comment by QuLogic** [comment]
I'm aware; they were not buildable at the time of release.

In the meantime, the non-versioned link should work https://matplotlib.org/Matplotlib.pdf and get you the 3.3.2 PDF.

**Comment by Joe-Sin7h** [comment]
Hello! This is my first time contributing to an open source project , I would like to work on this issue .
can i get assigned ?

**Comment by QuLogic** [comment]
Thank you for your interest; there is already a PR in progress to fix this #18948.

**Comment by QuLogic** [comment]
This is now up.
