### ISSUE TITLE
Pillow promoted to a hard dependency?

### ISSUE THREAD

**Issue by jmd-dk** [matplotlib/matplotlib#19061]
It appears that Pillow has become a hard dependency as of Matplotlib 3.3.0. Is this true? It's listed as such [here](https://matplotlib.org/3.3.0/users/installing.html#dependencies), though I can't find further documentation on this. As this change has the potential to break build workflows (which is the case for me), I would expect to find such a change in the '[What's new?](https://matplotlib.org/3.3.0/users/whats_new.html)'.

I'm trying to build Matplotlib 3.3.3 from source on Linux, using pip. It used to work fine with 3.2. Now it attempts to install Pillow, fails due to missing jpeg library, which in turn aborts the installation of matplotlib.

As I'm installing against Python 3.9, I'm a little dubious about whether the problem in fact is with the missing Pillow. As I see Pillow has been moved from an optional to hard dependency between Matplotlib 3.2 and 3.3 though, I thought I would ask what that's about. I.e. is this change "real"/indented, and is it necessary?

**Comment by jklymak** [comment]
Yes, we now require pillow rather than home-rolled png libraries, per the API change note: https://matplotlib.org/api/api_changes.html  

We could revert that change, but I doubt there is much appetite to do so unless there is a super-compelling reason.  When possible we try and offload code to other projects.  You may consider using a package manager to install pillow and then doing the dev install of matplotlib...

**Comment by jmd-dk** [comment]
OK, thanks. So pillow is now absolutely required, while libpng is no longer used at all (not even by Pillow, as far as I understand).

I'm maintaining an automatic build pipeline which has to function without root privileges, so dev installing is out of the question. I think I should be able to guarantee a successful pillow install (not from source) using pip, after which I can install Matplotlib from source.

**Comment by jklymak** [comment]
OK, hope it works out.  I'll close this, but feel free to re-open if you think there is anything we need to address.. Thanks...

**Comment by jmd-dk** [comment]
> I'll close this

That's fine, I think my problem is solved.

On an only slightly related note: The referenced [docs](https://matplotlib.org/3.3.0/users/installing.html#dependencies) state that kiwisolver >= 1.0.0 is required, whereas `kiwisolver>=1.0.1` is used in [`setup.py`](https://github.com/matplotlib/matplotlib/blob/v3.3.3/setup.py).
