### ISSUE TITLE
Missing ‘s’ in the documentation of pyplot.subplots

### ISSUE THREAD

**Issue by Dreamingnoisy** [matplotlib/matplotlib#19068]
### Problem
The 's' characters are missing in the first given code example of pyplot.subplots

Codes in the documentation

fig, (ax1, ax2) = plt.subplot(1, 2)
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplot(2, 2)

It should be 

fig, (ax1, ax2) = plt.subplots(1, 2)
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2) 
Here is the link:
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots.html#matplotlib.pyplot.subplots

### Suggested Improvement
It is not a big problem, but if you like please correct it.

**Comment by QuLogic** [comment]
This has already been fixed by #18975.
