### ISSUE TITLE
Issue while creating the distribution histogram using .hist()

### ISSUE THREAD

**Issue by Andrej-BG** [matplotlib/matplotlib#19069]
This is my first time opening an issue ever so please do not judge strictly. the problem occurred in a too simple situation, so maybe I misunderstood something. I'm just at the beginning of learning the data science and mess around with some packages and methods. But I'll be glad to be useful in the case the problem described below really takes place.

### Bug report

**Bug summary**

While plotting the histogram of the random distribution with only even values, the last value on the histogram displayed as odd.

**Code for reproduction**

```python
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
list = [1,2,5,4,5,2,5,3,6,5,4,2,4,5,1,2,2,3,3,3]
list = {'first':list, 'second':np.array(list)*2}
df = pd.DataFrame(list)
plt.hist(df.second)
plt.show()
```
**Actual outcome**

After the line 7:
```
(array([2., 0., 5., 0., 4., 0., 3., 0., 5., 1.]), array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]), <BarContainer object of 10 artists>)
```

**Expected outcome**

Obviously there should be no a single 11 value, but should be a single 12 value!
```
(array([2., 0., 5., 0., 4., 0., 3., 0., 5., 0., 1.]), array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]), <BarContainer object of 11 artists>)
```

**Matplotlib version**
  * Operating system: Windows 10 Pro 2004 19041.360
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.3
  * Numpy version: 1.19.4
  * Pandas version: 1.1.4

python from https://www.python.org/downloads/
pip install matplotlib
every other package also was installed using pip

Thanks in advance.

**Comment by jklymak** [comment]
The second array are the bin edges.  Your value of 12 is exactly on the border of the bin edges.  If you want the bin edges to be unambiguous specify them to be non-integers.  `plt.hist(df.second, bins=np.arange(1.5,12.6, 1.0))`.

I'm going to close because there is no bug here.  Questions like this are better directed to discourse.matplotlib.org.  They can always be escalated to an issue from there.
