### ISSUE TITLE
Matplotlib ax.set_thetagrids value error problem

### ISSUE THREAD

**Issue by iamz33** [matplotlib/matplotlib#19070]
### Bug report

**Bug summary**

Unable to plot radar plots with the same code. I was able to generate earlier. Since the update, I guess the problem 

**Code for reproduction**

```python
raf = pd.read_excel('RAF.xlsx', index_col=0)
for i in range(0, len(raf)):
    
    labels = np.array(raf.columns)
    stats = raf.iloc[i]
    angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)
    stats=np.concatenate((stats,[stats[0]]))
    angles=np.concatenate((angles,[angles[0]]))
    fig=plt.figure()
    ax = fig.add_subplot(111, polar=True)
    ax.plot(angles, stats, 'o-', linewidth=2)
    ax.fill(angles, stats, alpha=0.25)
    ax.set_thetagrids(angles * 180/np.pi, labels)
    ax.set_yticks(np.arange(0,100,20))
    ax.set_title(raf.index[i])
    ax.grid(True)
    plt.savefig('Radarplot '+raf.index[i]+'.png')

```

**Actual outcome**

```
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

runfile('C:/Users/Zee/.spyder-py3/radarplot.py', wdir='C:/Users/Zee/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\Zee\.spyder-py3\radarplot.py", line 65, in <module>
    ax.set_thetagrids(angles * 180/np.pi, labels)

  File "C:\Users\Zee\anaconda3\lib\site-packages\matplotlib\projections\polar.py", line 1346, in set_thetagrids
    self.set_xticklabels(labels)

  File "C:\Users\Zee\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)

  File "C:\Users\Zee\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Zee\anaconda3\lib\site-packages\matplotlib\axis.py", line 1796, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)

  File "C:\Users\Zee\anaconda3\lib\site-packages\matplotlib\axis.py", line 1717, in set_ticklabels
    raise ValueError(

ValueError: The number of FixedLocator locations (12), usually from a call to set_ticks, does not match the number of ticklabels (11).
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Win10
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable): Spyder
  * Other libraries: 

pip install matplotlib --upgrade
pip install conda

**Comment by jklymak** [comment]
Can you give us something reproducible so we don't have to guess what is in `RAF.xlsx`?  Preferable with hand-generated data.

**Comment by iamz33** [comment]
raf.xlsx --> RAF  Score (between 1 to 100 = ylim for radar plots for each index)
cols--> Scenarios on radar plot = thetagrids for each index
Dataset raf.xlsx to be plotted : 

            | GWLPRC | GWLP | GWL   | PRC    | RC      | G       | W        | L        | P       | R     | C
--         | --             | --        | --       | --      | --        | --       | --        | --       | --      | --     | --
Wind   | 0               | 0         | 0       | 12.5   | 18.75  |  25     | 0         | 0        | 0       | 50   | 0
PV       | 25             | 25        | 25     | 56.25 | 75     | 50      | 25        | 25      | 50     | 100  | 25
CSP     | 62.5           | 50       | 50     | 56.25 | 93.75 | 0        | 50       | 50      | 25     | 75    | 75
Hydro | 68.75         | 81.25   | 100   | 25     | 6.25    | 75      | 100     | 100    | 75     | 25    | 50
Coal    | 93.75        | 93.75    | 75     | 100   | 56.25  | 100    | 75       | 75      | 100   | 0      | 100

**Comment by anntzer** [comment]
That's exactly what the error message says: you have 11 labels, but 12 locations because you appended `angles[0]` to `angles`.
