### ISSUE TITLE
Qt backend's Figure options to support axis units

### ISSUE THREAD

**Issue by soininen** [matplotlib/matplotlib#19075]
### Problem

We often use datetimes on X axis. However, Qt backend's figure options dialog converts these to floating point numbers making it all but possible to edit the axis xmin and xmax.

### Proposed Solution

Make the options dialog deal with axis units more properly, e.g. datetimes could be shown using `QDateTimeEdit` widget.

I managed to get this working for datetimes and X axis on a monkey-patched options dialog by replacing line 37 in `matploglib/backends/qt_editor` by

```python
    if isinstance(axes.xaxis.converter, DateConverter):
        xmin, xmax = tuple(num2date(lim) for lim in axes.get_xlim())
    else:
        xmin, xmax = map(float, axes.get_xlim())
```

Would this be an acceptable way of dealing with the units in general? I would be willing to work on a Pull request on this.

**Comment by anntzer** [comment]
That seems reasonable (in the absence of having a way to get unitized limits back, but I guess that's not going to happen until we have a general unconverter (https://github.com/matplotlib/matplotlib/pull/12270, https://github.com/matplotlib/matplotlib/pull/16922)).
Note that I'd guess the patch at https://github.com/matplotlib/matplotlib/issues/18958#issuecomment-727779571 would still be needed to support PySide2, though.

**Comment by jklymak** [comment]
Right, thats a reasonable hack for one converter, but not for units in general.  I'd be mildly against having a bunch of special casing of dates, but maybe its worth the pain?

**Comment by soininen** [comment]
I cannot say I am fully happy with the `isinstance()` solution myself so I am all ears if there is a better way to do this. Maybe this could work as a stopgap solution until something like a general unconverted gets implemented, though?
