### ISSUE TITLE
Unwanted clipping of 3d plots

### ISSUE THREAD

**Issue by RubendeBruin** [matplotlib/matplotlib#19096]
I'm working with the 3D axis of matplotlib to create an interactive output for a FEM model. The user can pan, zoom and rotate. However the drawn part of the model seems to be restricted to a fixed square, no matter the aspect of the figure.

### Bug report

**Bug summary**

Clipping on sides of 3D plot.

When creating a 3d plot and then zooming in the figure does not utilize all available space. 

**Code for reproduction**

Reproduce:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from numpy import arange, sin, pi

fig = plt.figure(figsize=(10,2), frameon=True)
ax = fig.add_subplot(111, projection='3d')

t = arange(0.0, 3.0, 0.01)
s = sin(2 * pi * t)
ax.axes.plot(t, s)

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/34062862/101923026-29c55780-3bcf-11eb-8d1b-913884692697.png)

**Expected outcome**

(minus my paint drawing skills)

I would like the lines to be drawn outside the box as well:

![image](https://user-images.githubusercontent.com/34062862/101923480-ba9c3300-3bcf-11eb-9a81-1ccd6a09c117.png)

**Matplotlib version**

3.3.3

**Comment by jklymak** [comment]
This is clipping.  You can turn clipping off for your line with set_clipping(False)

**Comment by timhoffm** [comment]
or `plot(t, s, clip_on=False)`.

Note also that you should do `ax.plot(...)` and not `ax.axes.plot(...)`. `axes` gives the Axes an Artist belongs to, and an Axes (which is an Artist) belongs to itself. So `ax.axes` is `ax`.

**Comment by RubendeBruin** [comment]
@timhoffm , @jklymak 
Excellent, thanks!
