### ISSUE TITLE
axisartist axis_direction bug

### ISSUE THREAD

**Issue by jasondet** [matplotlib/matplotlib#19099]
### Bug report

**Bug summary**

Floating axes in axisartist seem to ignore axis_direction

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits import axisartist

fig = plt.figure()
ax = axisartist.Subplot(fig, 111)
fig.add_subplot(ax)
ax.axis['bottom', 'top', 'right', 'left'].set_visible(False)
ax.axis['x'] = ax.new_floating_axis(nth_coord=0, value=0, axis_direction='bottom')
ax.axis['y'] = ax.new_floating_axis(nth_coord=1, value=0, axis_direction='left')
plt.show()
```

**Actual outcome**

![axbug](https://user-images.githubusercontent.com/2238942/101941846-6aa47880-3b9d-11eb-8b09-10a1f78774c8.png)

**Expected outcome**

I expect the y-axis tick labels to appear on the left side of the axis as described [here](https://matplotlib.org/3.1.1/api/_as_gen/mpl_toolkits.axisartist.axis_artist.html#classes).

I'll note that also for the x-axis changing 'bottom' to 'top' doesn't move the x-axis label positions either. axis_direction seems to be totally ignored.

**Matplotlib version**

  * Operating system: Mac OS Catalina 10.15.7
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.9.0
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

I installed matplotlib via "pip install matplotlib"

**Comment by anntzer** [comment]
```patch
diff --git i/lib/mpl_toolkits/axisartist/axislines.py w/lib/mpl_toolkits/axisartist/axislines.py
index 05e1d1cd6..2ef20d763 100644
--- i/lib/mpl_toolkits/axisartist/axislines.py
+++ w/lib/mpl_toolkits/axisartist/axislines.py
@@ -411,7 +411,7 @@ class GridHelperRectlinear(GridHelperBase):
         _helper = AxisArtistHelperRectlinear.Floating(
             axes, nth_coord, value, axis_direction)
 
-        axisline = AxisArtist(axes, _helper)
+        axisline = AxisArtist(axes, _helper, axis_direction=axis_direction)
 
         axisline.line.set_clip_on(True)
         axisline.line.set_clip_box(axisline.axes.bbox)
```
seems like a reasonable fix?
