### ISSUE TITLE
support for ticks crossing axes in axisartist

### ISSUE THREAD

**Issue by jasondet** [matplotlib/matplotlib#19101]
### Problem

axisartist by default draws ticks on the opposite side of the labels. It provides a method `Ticks.set_tick_out()` to change it to draw ticks on the same side of the label. However, there is no way to draw ticks across both sides.

### Proposed Solution

Please add a function to `axisartist.Ticks` that enables one to draw ticks on both sides of the axis.

### Additional context and prior art

Drawing tick marks spanning an axis is a [common artistic choice](https://www.google.com/search?tbm=isch&tbs=rimg:CTwslveVfEbOYcrYmUgmLTfK) and should be possible in axisartist.

**Comment by jklymak** [comment]
@jasondet is there a reason you are using `axisartist` for your end-use rather than axis objects from the main library?  Things in mpl-toolkit tend to be substantially less polished.

**Comment by anntzer** [comment]
I actually had this mostly already implemented, see #19102.  @jasondet if you are interested in the feature, consider trying to push my patch over the finish line :)

**Comment by jasondet** [comment]
> @jasondet is there a reason you are using `axisartist` for your end-use rather than axis objects from the main library? Things in mpl-toolkit tend to be substantially less polished.

I'm trying to make axes that cross in the middle of the plot rather than at the corner, like in [this example](https://matplotlib.org/3.3.3/gallery/axisartist/simple_axisartist1.html). The example uses axisartist, so I tried using axisartist. I did end up doing it myself with Axis objects from the main library as axisartist was unusable.

**Comment by jklymak** [comment]
Yes tis unfortunate that demo comes up so high in the google search.  It should really have disclaimer at the top and point to the core library version: https://matplotlib.org/gallery/ticks_and_spines/spine_placement_demo.html

**Comment by anushkrishnav** [comment]
I can work on the Issue

**Comment by QuLogic** [comment]
This is now implemented by #30369
