### ISSUE TITLE
axisartist documentation missing for classes and functions, and has typos

### ISSUE THREAD

**Issue by jasondet** [matplotlib/matplotlib#19100]
### Problem

I was trying to follow [this example](https://matplotlib.org/3.3.3/gallery/axisartist/simple_axisartist1.html) using axisartist but several of the main functions called there have no documentation that I could find via google or by clicking links in the existing documentation. In particular:

- I couldn't find documentation for `axisart.Subplot()`, at least not from the links in the [toolkits page](https://matplotlib.org/3.3.3/api/toolkits/index.html#matplotlib-axisartist-toolkit). Usage examples are given in the [axisartist tutorial](https://matplotlib.org/3.3.3/tutorials/toolkits/axisartist.html) but for example what the heck are the "1, 1, 1" arguments?? I was able to guess that the return value was AxisArtist but it would be nice to have been told that.
- The [documentation for AxisArtist](https://matplotlib.org/3.3.3/api/_as_gen/mpl_toolkits.axisartist.axis_artist.AxisArtist.html) is missing documentation for `new_floating_axis()`.
- <s> The [axisartist.axis_artist docs page](https://matplotlib.org/3.3.3/api/_as_gen/mpl_toolkits.axisartist.axis_artist.html) has a typo: `ax.axis["bottom"].major_ticks.set_ticks_out(True)` should be `ax.axis["bottom"].major_ticks.set_tick_out(True)` (remove 's' after 'tick' in 'set_tick_out')</s> *done*

### Suggested Improvement

- add proper sphinx documentation for all classes in axistartist
- add proper sphinx documentation for all functions of all classes in axisartist
- check all code snippets in documentation for typos

**Comment by aflahkhan** [comment]
I can fix the typo, can I try that part only?

**Comment by timhoffm** [comment]
@aflah02 sure. :+1:

**Comment by aflah02** [comment]
I've generated a pull request for that @timhoffm, I couldn't figure out how to add this issue to my pull request so I'm commenting the link here -https://github.com/matplotlib/matplotlib/pull/19192

**Comment by jklymak** [comment]
You can just type "closes #12345" in the issue description

**Comment by aflah02** [comment]
ohkk thanks @jklymak

**Comment by timhoffm** [comment]
Typo has been fixed. The documentation still needs improvement.
