### ISSUE TITLE
plt.plot()/plt.show() does nothing when you attempt to plot list of empty lists 

### ISSUE THREAD

**Issue by wjwalcher** [matplotlib/matplotlib#19112]
### Bug report

**Bug summary**

I was trying to plot something and accidentally was passing in a list of empty lists ```[[...], [...]]``` to ```plt.plot()```. However, neither ```plt.plot()``` nor ```plt.show()``` provided me with any error message. Instead, my program hung and I was left scratching my head as to why things weren't working! 
It seems like in this situation, there should be some sort of error raised.

**Code for reproduction**

```python
valid_errors = []
for i in range(1, 8):
  valid_errors.append(valid_errors)

plt.plot(range(1, 8), valid_errors)
plt.xlabel("Number of Filters")
plt.ylabel("Validation Error")
plt.show()
```

**Actual outcome**

Nothing happens, and my python program simply hangs. 

**Expected outcome**

One would expect this should not ever work, therefore an error should be raised.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.6
  * Jupyter version (if applicable): N/A

Matplotlib installed via pip3

**Comment by timhoffm** [comment]
With the first three lines, you are creating a list that references itself 8 times. Such recursive lists are not supported by Matplotlib (and likely this list is not what you want anyway).

**Comment by QuLogic** [comment]
I'm going to close this, as what you have is a recursive data structure, which we can't really do anything about.

**Comment by tacaswell** [comment]
I would also note that the actually hang is happening in numpy.  It may be worth opening a bug report with them

```ipython

In [1]: import numpy as np

In [2]: x = []

In [3]: x.append(x)

In [4]: x.append(x)

In [5]: x.append(x)

In [6]: x.append(x)

In [7]: np.asarray(x)
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by timhoffm** [comment]
This is tracked at https://github.com/numpy/numpy/issues/14934.
