### ISSUE TITLE
ConciseDateFormatter should suppress offset text when largest scale is in years

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19118]
### Bug report

**Bug summary**

When plotting years-scale data with ConciseDateFormatter, the offset text is redundant.

**Code for reproduction**

```python
import datetime; from pylab import *
plot([datetime.datetime.now(), datetime.datetime.now() + datetime.timedelta(days=365)], [0, 0])
```

**Actual outcome**

![out](https://user-images.githubusercontent.com/1322974/102202659-e832f600-3ec7-11eb-971a-3d807f39f40b.png)

**Expected outcome**

The extra "2022" should go away.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 39
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
I'm happy to help with this, but I think its relatively straight forward, so maybe a good first issue for someone interested in contributing?

**Comment by QuLogic** [comment]
Sure, your assignment could just be signing up to do a review later, too.

**Comment by harrymknight** [comment]
Hi, could I have a go at solving this issue?

**Comment by jklymak** [comment]
Yes, if an issue doesn't have a linked PR, anyone is welcome to try to fix.

**Comment by harrymknight** [comment]
I'm having trouble reproducing the issue. With the code,

```python
import datetime
import matplotlib
matplotlib.use('qt5agg', force=True)
import matplotlib.pyplot as plt
plt.plot([datetime.datetime.now(), datetime.datetime.now() + datetime.timedelta(days=365)], [0, 0])
```
The x-axis differs from the actual outcome

![bug-19118](https://user-images.githubusercontent.com/20374093/102492652-e86af700-4069-11eb-8cb6-f13cbc015db7.jpg)

**Comment by jklymak** [comment]
Thats because you are not using ConciseDateFormatter.   Please see https://matplotlib.org/gallery/ticks_and_spines/date_concise_formatter.html
