### ISSUE TITLE
webAgg example broken - maybe mpl.js broken?

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#19129]
### Bug report

Extracting the extra bug discovered in https://github.com/matplotlib/matplotlib/issues/19116#issuecomment-745785226

**Bug summary**
The code in https://matplotlib.org/devdocs/gallery/user_interfaces/embedding_webagg_sgskip.html does not display anything in the browser when running master matplotlib (https://github.com/matplotlib/matplotlib/commit/27aaf0c378f767d5bcff4f2a65664485fba1f69b)

**Code for reproduction**

- Download the example from the docs
- run it using latest matplotlib
- open http://127.0.0.1:8080/
- See no plot

**Actual outcome**

No plot + this DOM exception in the JS console:

```
Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable mpl.js:394
    send_message http://127.0.0.1:8080/mpl.js:394
    _init_canvas http://127.0.0.1:8080/mpl.js:161
    figure http://127.0.0.1:8080/mpl.js:55
    <anonymous> http://127.0.0.1:8080/:40
```

**Expected outcome**
A working interactive plot shows up

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: https://github.com/matplotlib/matplotlib/commit/27aaf0c378f767d5bcff4f2a65664485fba1f69b
  * Matplotlib backend (`print(matplotlib.get_backend())`): webAgg
  * Python version: 3.9.0
  * Browser: Firefox 83.0

Installed python from conda-forge:
```
Python 3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:59:50) 
[GCC 7.5.0] on linux
```

**Comment by QuLogic** [comment]
This is also broken as of v3.3.3, but I'm sure I tested this then due to backporting fixes for older Firefox. I wonder if this was a change in Firefox that broke it.

**Comment by tacaswell** [comment]
In chrome derivative on 3.3.3 I get a slightly better error:

```
﻿
mpl.js:390 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at mpl.figure.send_message (http://localhost:8080/mpl.js:390:13)
    at mpl.figure._init_canvas (http://localhost:8080/mpl.js:161:13)
    at new mpl.figure (http://localhost:8080/mpl.js:55:10)
    at HTMLDocument.<anonymous> (http://localhost:8080/:40:21)
```

I also manually tested this in prep of 3.3.3 .  Could the problem be on the other side and someting changed in tornado's websockets?

**Comment by QuLogic** [comment]
This bisects to #18361, which sends the pixel ratio message earlier (in `_init_canvas`); I suppose leaving it to the `ws.onopen` might be fine, but needs testing?

**Comment by tacaswell** [comment]
:sheep:

**Comment by tacaswell** [comment]
I did just verify that nbagg still works on v3.3.3 so that is good at least.   Presumably we go through a slightly different song/dance to stand the js side figure up in the two cases?

**Comment by QuLogic** [comment]
Yes, nbagg uses a proxy to a WebSocket from ipykernel, which I assume is already stood up before we get it.

**Comment by aathan** [comment]
I (independently) found and fixed this bug in the manner suggested above, so the fix is corroborated. This was in matplotlib 3.3.3 vs recent Firefox. Just to be explicitly clear, what I am saying is:Ttriggering the call to mpl.figure() (in all_figures*.html or single_figure*.html) via websocket.onopen() works.

(see https://discourse.matplotlib.org/t/webagg-backend-js-bug-websocket-not-ready/21796)

**Comment by QuLogic** [comment]
I suggest you open a pull request so we can review the change better.
