### ISSUE TITLE
Reference to PSF COC in contributing docs

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#19135]
### Problem
In https://matplotlib.org/devel/contributing.html the first line writes:
> We follow the Python Software Foundation Code of Conduct in everything we do.

which is no longer strictly true given that there is matplotlib COC?

**Comment by story645** [comment]
So this is because devel is not devdocs https://matplotlib.org/devdocs/devel/contributing.html which has the write wording. Maybe needs to be backported?

**Comment by ianhi** [comment]
oooh i see. If you do backport it also backport those blue buttons at the top. Those are great!

**Comment by story645** [comment]
Was @timhoffm, who has been redoing the website in stages!

**Comment by timhoffm** [comment]
At some point I more or less stopped backporting documentation changes because of the hassle with conflicts. The docs have existed for years in the present form and IMHO it's no the end of the world if the documentation updates wait some more weeks to get public when 3.4 comes out.
