### ISSUE TITLE
matplotlib.pyplot.plot fails on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by danielkulenkamp** [matplotlib/matplotlib#19149]
### Bug report

**Bug summary**

After upgrading to Big Sur 11.1 (20C69), I am unable to plot and all of my plotting scripts are broken. matplotlib fails with Abort trap: 6. Everything was working fine before the update. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig = plt.figure() # also fails with plt.plot()
```

**Actual outcome**

```
macOS 11 or later required !
Abort trap: 6
```

**Expected outcome**

You should be able to continue on with the script at this point and view a plot. 

**Matplotlib version**

  * Operating system: macOS 11.1 (20C69)
  * Matplotlib version: 3.3.3
  * Matplotlib backend: TkAgg
  * Python version: 3.9.0

I've tested by installing from pip, as well as installing the source code directly from the git repository. I've also tested on python 3.7.6. 

Any help would be appreciated!

**Comment by danielkulenkamp** [comment]
I did some more digging and it looks like this is an issue with tkinter, not matplotlib. Apparently there's an issue with how hombrew manages the installation. I installed instead with the official installer and it solved my issue.

**Comment by jklymak** [comment]
Glad you got it fixed!

In general for hard failures like this its good to 

1. test the backend without matplotlib (usually something like `import tk`)
2. try other backends

That will help us narrow down if it is something we can help with.

**Comment by danielkulenkamp** [comment]
Thanks for the advice! I will keep it in mind next time I have an issue!
