### ISSUE TITLE
Bug in parameter file persistency within Jupyter

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#19158]
### Bug report

**Bug summary**

I find that at least one of my parameters defined in a local `matplotlibrc` file is not persistent when I import multiple times from matplotlib, within a Jupyter notebook

**Code for reproduction**

my matplotlibrc file, contained in the same directory as the notebook, reads

```
figure.figsize = 8.0, 5.5 
```

If I only run a single import, it is read correctly
```python
>>> import matplotlib as mpl
>>> print(mpl.rcParams["figure.figsize"])
[8.0, 5.5]
```

Whereas if I run a second import, e.g.
```python
>>> import matplotlib as mpl
>>> import matplotlib.pyplot as plt
>>> print(mpl.rcParams["figure.figsize"])
[6.0, 4.0]
```

Note that this problem specifically appear from within a notebook (using jupyter lab). The behaviour is correct from a simple (I)Python session.

**Expected outcome**
My parameters should be persistent against multiple import statements.

**Matplotlib version**
  * Operating system: MacOS 11.1
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.8.5
  * Jupyter version (if applicable):
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.6
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```

I installed python with hombrew + pyenv, then matplotlib with pip.

**Comment by mwaskom** [comment]
I think the issue here is that importing `matplotlib.pyplot` in the notebook activates the inline backend, which sets its own rcParams including the figure size: https://github.com/ipython/ipykernel/blob/9cc8ea7103b8bb5a124b6906870994753dcdaf64/ipykernel/pylab/config.py#L45

**Comment by jklymak** [comment]
Good catch @mwaskom   I believe that you can set this in your python config file somewhere, but I don't think this is directly a Matplotlib issue so I'll close.  Thanks!

**Comment by mwaskom** [comment]
This looks like the right approach: https://stackoverflow.com/questions/35939989/matplotlib-configuration-for-inline-backend-in-jupyter-notebook
