### ISSUE TITLE
PillowWriter GIF duration and loop

### ISSUE THREAD

**Issue by znstrider** [matplotlib/matplotlib#19169]
### Current PillowWriter functionality does not allow me to specify the duration for each of the gif frames and it is not possible to not have the gif loop.
Additionally, I frequently get a **ValueError: buffer is not large enough** when animating multi axes figures. (Not sure if this is a common problem).

Animation to help introduce a visual story can be quite beneficial to understanding and for that I would like to be able to not loop the gif and "pause" the gif via different durations for all frames.

### Proposed Solution

1) add duration=None, loop=0 arguments to setup() and to a PillowWriter specific saving context_manager.
To not loop we can specify loop=None and then we specifically need to not pass the loop argument to save() in finish().

2) What is the difference between Image.frombuffer and Image.open(buf)? I find that Image.open(buf) solves my problem of the ValueError: buffer is not large enough.
It seems to take more time for me though. (about +33%)

3) removed unused variable assignment: renderer = self.fig.canvas.get_renderer() from grab_frame()

```
class PillowWriter(AbstractMovieWriter):
    @classmethod
    def isAvailable(cls):
        return True

    def setup(self, fig, outfile, dpi=None, duration=None, loop=None):
        super().setup(fig, outfile, dpi=dpi)
        self.duration = duration
        self.loop = loop
        self._frames = []

    def grab_frame(self, **savefig_kwargs):
        buf = BytesIO()
        self.fig.savefig(
            buf, **{**savefig_kwargs, "dpi": self.dpi})
        self._frames.append(Image.open(buf))

    def finish(self):
        duration = self.duration or int(1000 / self.fps)

        # to not loop at all we need to avoid passing the loop argument to save
        if self.loop is None:
            self._frames[0].save(
                self.outfile, save_all=True, append_images=self._frames[1:],
                duration=duration)
        else:
            self._frames[0].save(
                self.outfile, save_all=True, append_images=self._frames[1:],
                duration=duration, loop=self.loop)

    @contextlib.contextmanager
    def saving(self, fig, outfile, dpi, duration=None, loop=0, *args, **kwargs):
        """
        Context manager to facilitate writing the movie file.
        ``*args, **kw`` are any parameters that should be passed to `setup`.
        """
        # This particular sequence is what contextlib.contextmanager wants
        self.setup(fig, outfile, dpi, duration, loop, *args, **kwargs)
        try:
            yield self
        finally:
            self.finish()
```

### Additional context and prior art

endless looping for gifs was introduced here:
https://github.com/matplotlib/matplotlib/pull/11789

Documentation would have to be updated I suppose.
If this seems like a useful improvement to the PillowWriter I could go ahead and create a PR.

**Comment by jklymak** [comment]
You can pause an animation programatically by just changing your `dt` between frames in your script.    

I think its reasonable to ask that the looping doesn't happen, but you'd need to write an API for all the writers.  We made Pillow do this to be consistent with imagemagick.  It would be unfortunate to have them drift apart.

If you are getting buffer errors, its because you cannot hold your animation in memory.  The "solution" is to not try and make an animation this way, but rather to save pngs to a folder and then animate using a command line tool (like imagemagick).  Personally, I find this more flexible anyway, so its what I always do.

**Comment by znstrider** [comment]
> You can pause an animation programatically by just changing your `dt` between frames in your script.

How do I do that, where can I specify any 'dt' variable? There is none in the whole matplotlib animation module.

> I think its reasonable to ask that the looping doesn't happen, but you'd need to write an API for all the writers. We made Pillow do this to be consistent with imagemagick. It would be unfortunate to have them drift apart.

Yeah, I understand this concern and I was worried that this might be a problem to integrate it this way into matplotlib.

> If you are getting buffer errors, its because you cannot hold your animation in memory. The "solution" is to not try and make an animation this way, but rather to save pngs to a folder and then animate using a command line tool (like imagemagick). Personally, I find this more flexible anyway, so its what I always do.

I doubt any not as advanced user like you would use a command line tool for something like this and it seems unnecessarily bothersome. Why would I go to that length if in fact I *can* make an animation in that much simpler way (using Image.open)?

What's the need or upside to using .frombuffer()?

**Comment by jklymak** [comment]
> > You can pause an animation programatically by just changing your `dt` between frames in your script.
> 
> How do I do that, where can I specify any 'dt' variable? There is none in the whole matplotlib animation module.

In your script, you must somehow define what is in each frame, typically using a timestep.  If you want to slow down or pause, simply repeat frames, or don't advance the information as fast.  


> I doubt any not as advanced user like you would use a command line tool for something like this and it seems unnecessarily bothersome. Why would I go to that length if in fact I _can_ make an animation in that much simpler way (using Image.open)?

I'm not that sophisticated - I just google "make movie list images command line".  And frankly these days I just use Quicktime  on my Mac.  If I wanted to pause or slow anything down, I'd just use Adobe Premier (our university has a license, and I got good at using it for online teaching).  

The point is that Matplotlib offers a relatively sophisticated animation writer - we can make it more and more complicated, with the attendant maintenance burden, or we can simply point out that there are more flexible tools out there.  

> What's the need or upside to using Image.frombuffer()? It is Image.frombuffer() that is raising the buffer error.

`PillowWriter` simply writes the individual RGBA buffer to a BytesIO buffer and then uses that buffer to make a Pillow image.  By using `PillowWriter` you need to store all the frames in memory as Pillow images before the gif is written, so I imagine you eventually run out of memory.    I'm not sure how Pillow works, but maybe its possible to write frames during creation and free up memory...

**Comment by znstrider** [comment]
> In your script, you must somehow define what is in each frame, typically using a timestep. If you want to slow down or pause, simply repeat frames, or don't advance the information as fast.
>

Yeah, I didn't think of doing that because being able to use a duration argument seems much easier.

> The point is that Matplotlib offers a relatively sophisticated animation writer - we can make it more and more complicated, with the attendant maintenance burden, or we can simply point out that there are more flexible tools out there.
> 

Point taken.
If this makes the maintenance burden vs perceived gain unattractive, then sure, I and other people can and have to use other tools if they want that functionality. And one can always go back to saving the images and then creating the gif from that.

It's also possible it's not a frequent use case, so I can see your point of view.

**Comment by jklymak** [comment]
An animation is just a series of frames, displayed one after another at a certain frame rate.  If we allowed each plot to have a different duration in an animation, then we would have to either heavily oversample the frames, or interpolate between the frames in time.  There are lots of tools that do this, but I'd strongly argue is outside Matplotlib's domain.

**Comment by znstrider** [comment]
Alright, thanks for taking the time to discuss this, I'll close the issue.

**Comment by jklymak** [comment]
I think the looping request is still valid?

**Comment by znstrider** [comment]
I am not looking to contribute do that anymore.

**Comment by znstrider** [comment]
I adapted the celluloid package though to make image snapshots of the whole figure which can then be saved as a gif using imageio, which provides loop and duration functionality.

https://github.com/znstrider/mplcamera
