### ISSUE TITLE
LineCollection does not respect facecolor attribute

### ISSUE THREAD

**Issue by meakbiyik** [matplotlib/matplotlib#19168]
### Bug report

**Bug summary**

LineCollection does not use facecolors, I have tried all possible aliases and attribute combinations but even in the simplest case, it does not work.

**Code for reproduction**

```python
from matplotlib.collections import LineCollection
from matplotlib import pyplot as plt

lines = LineCollection([[(0,0),(1,1)]], facecolors=(1,1,1,1), colors=(0,0,0,1), lw=100)
fig = plt.figure()
ax = plt.gca()
ax.add_collection(lines)
```

Beware that the `colors` attribute in LineCollection is fed to the `edgecolors` of `Collection` object. Removing that did not help.

**Actual outcome**

![image](https://user-images.githubusercontent.com/23424198/102989069-4e95c500-4515-11eb-9485-b183fcbc6910.png)

**Expected outcome**

A white filling, preferably. I would also be delighted if alpha works for facecolors, i.e. I can make the insides transparent.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline (but it does not work for saving the figure either)
  * Python version: 3.8.6

**Comment by WeatherGod** [comment]
You are drawing a single line segment. The facecolor would only apply for
the area contained by a linear ring of line segments. The line itself will
get its color from the "color" argument, as you have in your example.

**Comment by jklymak** [comment]
What would you like "filled"?  A line, by definition, is not filled.  If you fill your 100-pt line with white, where should the fill stop and the stroke begin?   

Suggest you use a filled polygon: https://matplotlib.org/api/patches_api.html

**Comment by meakbiyik** [comment]
@jklymak Do I misinterpret this definition? I think it exactly means "filling in the line", and not any kind of polygon that the lines create, as that would require a lot other information.

>  facecolorscolor or list of color, default: 'none'
>  The facecolors of the LineCollection. Setting to a value other than 'none' will lead to each line being "filled in" as if there was an implicit line segment joining the last and first points of that line back around to each other. In order to manually specify what should count as the "interior" of each line, please use PathCollection instead, where the "interior" can be specified by appropriate usage of CLOSEPOLY.

@WeatherGod Furthermore, if it is as you mean, then it still does not work:

```python
from matplotlib.collections import LineCollection
from matplotlib import pyplot as plt

lines = LineCollection([[(0,0),(0.3,0.5),(1,1),(0,0)]], facecolors=(1,1,1,1), colors=(0,0,0,1), lw=10)
fig = plt.figure()
ax = plt.gca()
ax.add_collection(lines)
```

outputs 

![image](https://user-images.githubusercontent.com/23424198/103017428-e1e5ef00-4543-11eb-9040-0518e55475b9.png)

**Comment by meakbiyik** [comment]
@WeatherGod It is apparently as you said. Though, it took some interpretation of "facecolors" to get that. I will use PathPatch for this purpose I think. 

Thanks a lot!
