### ISSUE TITLE
mathtext \lim is vertically misaligned

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19178]
### Bug report

**Bug summary**

All's in the title.

**Code for reproduction**

```python
from pylab import *
figtext(.5, .5, r"$\lim_{x\to\infty}f(x)$", size=48)
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1322974/103169108-4bfade80-4839-11eb-8b28-a3bb05f39133.png)
The `\lim` is clearly too high.

**Expected outcome**

Proper vertical alignment.

Likely the same problem affects all operators listed in `_overunder_functions`.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: head
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 38
  * Jupyter version (if applicable):
  * Other libraries: 

@aitikgupta perhaps you may be interested looking at this too? (up to you, of course).

**Comment by aitikgupta** [comment]
I can look into this 👍🏼
