### ISSUE TITLE
Build fails on MacOS 11.1 and python3.9 on arm64e and x86_64

### ISSUE THREAD

**Issue by rucarrol** [matplotlib/matplotlib#19177]
### Bug report

Building matplotlib on big sur/M1 hardware fails with AssertionError:

```
AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_universal2')
```

This fails for both x86 emulation mode, and native M1 mode. 

**Code for reproduction**

For emulation mode: 

```python
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
arch -x86_64 python3.9 setup.py bdist_wheel
```

For Native mode: 

```python
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
arch -arm64 python3.9 setup.py bdist_wheel
```

We fail every time in building `_common.cpython-39-darwin.so`

**Actual outcome**

See line 1989 on [this gist](https://gist.github.com/rucarrol/3b5ed4a364375391287bca7445836b1f#file-gistfile1-txt-L1989)

**Expected outcome**

Successful build. 

**Matplotlib version**

  * Operating system: MacOS 11.1 (uname -a: Darwin MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64)
  * Matplotlib version: Whatever is at HEAD
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01)
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by matthew-brett** [comment]
Do you have the latest pip (20.3.x)?  I think that added support for M1
tags.

https://pip.pypa.io/en/stable/news/

**Comment by rucarrol** [comment]
That seems to be it, thanks!
