### ISSUE TITLE
Clear up definition of wspace

### ISSUE THREAD

**Issue by dsg03** [matplotlib/matplotlib#19193]
Hi, I am using gridspec to create subplots, and am finding it difficult to understand the definition of wspace. The documentation says that wspace is: "The amount of width reserved for space between subplots, expressed as a fraction of the average axis width" (https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.gridspec.GridSpec.html#matplotlib.gridspec.GridSpec).

Here is an example of what I am trying to achieve:

I want to have the center subplot be exactly square. I initially define wspace in inches and attempt to convert it to what is defined in the documentation. However, my conversion is not correct because the center subplot is not square. Could you please clarify how to do the conversion?

```
# Define sizes of subplots
center_width = 5
center_height = 5

left_width = 1
right_width = 0.1
top_height = 0.25
bottom_height = 1

wspace = 0.25
hspace = 0.05

# Initiate the figure, gridspec, and subplots
total_size = (left_width + center_width + wspace + right_width, 
              top_height + hspace + center_height + hspace + bottom_height)

width_gs_right = center_width + wspace + right_width
average_width = (center_width * 3 + right_width * 3) / 6

width_ratios_gs_right = (center_width / width_gs_right, right_width / width_gs_right)
height_ratios = (top_height / total_size[1], center_height / total_size[1], bottom_height / total_size[1])

fig = plt.figure(figsize=total_size, constrained_layout=False)
gs_left = GridSpec(left=0, right=left_width / total_size[0], nrows=3, ncols=1, 
                   height_ratios=height_ratios, hspace=hspace)
gs_right = GridSpec(left=left_width / total_size[0], right=1, nrows=3, ncols=2, 
                    width_ratios=width_ratios_gs_right, wspace=wspace / average_width, 
                    height_ratios=height_ratios, hspace=hspace)


fig.add_subplot(gs_left[0, 0])
fig.add_subplot(gs_left[1, 0])
fig.add_subplot(gs_left[2, 0])
fig.add_subplot(gs_right[0, 0])
fig.add_subplot(gs_right[1, 0])
fig.add_subplot(gs_right[2, 0])
fig.add_subplot(gs_right[0, 1])
fig.add_subplot(gs_right[1, 1])
fig.add_subplot(gs_right[2, 1])

plt.show()
```

mpl version 3.3.2
platform version 1.0.8
sys version output '3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56) \n[Clang 10.0.1 ]'

Thank you!

**Comment by jklymak** [comment]
https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/axes_box_aspect.html will make the axes be the aspect you want.  The wspace parameter is not going to know about your nested gridspec.   And setting wspace this way will not be robust to figure resizing.  

The other alternative is to place the axes manually which works fine if you are dealing with a fixed size figure.

**Comment by jklymak** [comment]
I'm going to close this as more appropriate for discourse.  The issue here is that you are mixing gridspecs.  "average_width" only applies to the active gridspec, not axes in other grid specs.  Feel free to discuss further at discourse.matplotlib.org.  If you want to see the code, it is at https://github.com/matplotlib/matplotlib/blob/d0f8f81db744e303c263e6b56ebcd83c4c190801/lib/matplotlib/gridspec.py#L145
