### ISSUE TITLE
Savefig does not issue a warning on a non-existent keyword n

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#192]
[Original report at SourceForge, opened Tue Feb  8 16:27:19 2011](https://sourceforge.net/tracker/?func=detail&aid=3175903&group_id=80706&atid=560720)

savefig does not issue a warning on a non-existent keyword name

Example
Savefig('filename.png', NonExistant=True)
Will not throw any warning.  This is especially important if you accidentally misspell an argument, such as:
Savefig('filename.png', tranperent=True)
Notice 'transperent' instead of 'transparent'

**Comment by tacaswell** [comment]
Started to look into this again, it is a rat's nest.

`print_figure` throws the kitchen sink at the underlying print functions so if we want to lock this down we need to lock down the union of the keywords expected in all of the print functions.

**Comment by anntzer** [comment]
fwiw mplcairo simply lists the (extra) allowed kwargs in mplcairo.base._check_print_extra_kwargs, and throws if anything not in there is passed.

**Comment by QuLogic** [comment]
Unfortunately, there's some incomplete implementations of some keyword arguments in some backends that makes this a bit more difficult than it should be.
