### ISSUE TITLE
How to acquire the z value for a constructed 3D plot when given x,y coordinates

### ISSUE THREAD

**Issue by Cinderella0709** [matplotlib/matplotlib#19202]
Hi, authors,

I have a small demand, but I didn't find a good solution. Could you give me some advice? 

**My problem is:** I have constructed a 3D plot by providing x,y,z for function **plot_surface**, then I have a series of 2D points that need to be mapped onto the surface. Is there a direct function to achieve this mapping? 
Alternatively, the problem can be solved by acquiring the z values of 2D points. But I didn't find how to get z values by x and y coordinates. However, I find that I can get the position when the mouse is pointing to a point on the plot, but I can't acquire it from the code (such as a function or property of the object).

Best,
Lin

**Comment by jklymak** [comment]
User questions are best brought up in discourse.matplotlib.org.  Thanks!
