### ISSUE TITLE
Z-Value of a single point 3D plot.() gets rounded down 

### ISSUE THREAD

**Issue by Wihtedeka** [matplotlib/matplotlib#19218]
### Bug report

When plotting a single point using .plot() it doesn't plot the z value as expected. Using .scatter() gives the correct result, so does including multiple points in .plot().  

**Code for reproduction**

```python
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.plot([0], [0], [0.5], 'ok')

```
Produces the following image 
![OnePoint](https://user-images.githubusercontent.com/24702406/103464496-5f73e100-4d34-11eb-8cd2-c5df3f481861.png)

Despite the z values being 0.5 you can see that it's plotted as 0.0 . Similarly
```python 
ax.plot([0], [0], [1.5]) 
```
is plotted as scatter([0], [0], [1]). 
 
If you include a second point it's plotted correctly, however:
```python
ax.plot([0, 0], [0, 0], [0, 0.5], 'ok')
```
![TwoPoints](https://user-images.githubusercontent.com/24702406/103464502-6bf83980-4d34-11eb-9676-e4ae173cd5cb.png)

Using 
```python
ax.scatter([0], [0], [0.5])   
```
also produces the correct output. 

**Matplotlib version**

  * Operating system: Windows 7 
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'TkAgg'
  * Python version: 3.7.4
Matplotlib installed via pip

**Comment by anntzer** [comment]
Thanks for the report.  This has been fixed in 3.3.0 as a side effect of https://github.com/matplotlib/matplotlib/pull/16003.
