### ISSUE TITLE
Add public API for setting an axis unit converter

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#19229]
### Problem

I would like to define and use a custom unit converter class. The existing `mpl.units.registry` system is type-based, which does not work for my usecase. I need my converter to generalize over types. But I also know exactly which (existing) axis objects should use the converter.

The closest I can get in associating a custom converter with an existing axis, following the code in `axis.update_units` is

```python
ax = plt.figure().subplots()
ax.xaxis.converter = CustomConverter()
ax.xaxis._update_axisinfo()
ax.xaxis.stale = True
```

### Proposed Solution

A public `axis.set_converter` API would solve this problem, e.g.

```python
ax = plt.figure().subplots()
ax.set_converter(CustomConverter())
```

The idea is that this would basically do what `Axis.update_units` does, but consuming a `ConversionInterface` rather than consuming data and then getting a converter from the registry.

### Additional context and prior art

The other thing I would mention is that I could probably work-around this problem if the registry lookup were based on the container `dtype` rather than the type of the individual elements (as is currently the case). But that seems to complexify the existing API, whereas the this proposal would add an orthogonal API, and it is probably better for that reason.

**Comment by tacaswell** [comment]
This would not be enough as https://github.com/matplotlib/matplotlib/pull/10206 added a cut-out (which was refactored a bit in https://github.com/matplotlib/matplotlib/pull/13738 and https://github.com/matplotlib/matplotlib/pull/14363) to not try and convert numbers.

In addition to adding `set_converter` would would have to extend the public API of the converters to at the instance level bail out of trying to do the conversion.  It looks like we could do this by over-riding `is_numlike` on sub-classes, but then we can not defer the "check if we need to predict a converter" step (which has been in the code base from 84ede567056bde8411446146854b86cdb2ff5ae3 )

**Comment by jklymak** [comment]
I think we could remove the cutout and make dealing with numbers the prerogative of the converter?

**Comment by mwaskom** [comment]
FYI I've decided to solve this in seaborn by internally coercing data to strings in situations where it should receive "categorical" treatment. I I think, for now at least, I don't need any changes in matplotlib to support this particular use-case. I'm going to close the issue, but if you think this is a good idea independently of my narrow problem, feel free to re-open.

**Comment by jklymak** [comment]
I think we should keep this open for the upcoming unit work.
