### ISSUE TITLE
tick labels displaced vertically with text.usetex and xcolor

### ISSUE THREAD

**Issue by darthoctopus** [matplotlib/matplotlib#19234]
### Bug report

Tick labels on vertical axes are displaced downwards when `text.usetex` is set to True.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True
plt.scatter([0, 1, 2, 3], [2,3,1,6])
plt.show()
#
```

**Actual outcome**

![Screenshot from 2021-01-04 10-51-12](https://user-images.githubusercontent.com/5761408/103553326-4fb2e480-4e7b-11eb-96ce-cb4d8e1de90d.png)

**Expected outcome**

![Screenshot from 2021-01-04 10-51-57](https://user-images.githubusercontent.com/5761408/103553397-62c5b480-4e7b-11eb-870d-2cfd58dc62b5.png)

This change happened between 3.2.1 and 3.2.2 (can reproduce in 3.2.2 onwards, inclusive)

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 3.2.2 onwards
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.9
  * Jupyter version (if applicable): 6.1.6
  * Other libraries: N/A

Matplotlib installed with pip

**Comment by darthoctopus** [comment]
I am able to resolve the issue by undoing the changes made to `dviread.py` in #16476.

**Comment by jklymak** [comment]
I cannot reproduce using either master or v3.2.2.   Do you have a pristine matplotlibrc?

**Comment by tacaswell** [comment]
Can you try clearing `~/.cache/matplotlib/tex.cache`? 

My guess is that across that version upgrade we changed the baseline, the output of latex changed, but the hash we use to name the files did not.  Thus you are seeing a miss-match between where the code that places the image of the text on the output thinks the output is vs where the code that generates the output thought it should have been.

**Comment by darthoctopus** [comment]
- The issue persists after wiping my matplotlib cache directory and restarting the kernel
- I found that the issue was resolved by removing this snippet: `\usepackage[dvipsnames]{xcolor}` from my latex preamble in matplotlibrc. However, I would like not to lose this functionality. Is there any alternative solution that allows me to both use latex and also change text colour inside equations?

**Comment by tacaswell** [comment]
I suspect that we will need to make the logic `divread.py` more sophisticated to cope with what ever changes xcolor adds?

attn @anntzer

**Comment by tacaswell** [comment]
For completeness the minimal repro case is

```python
plt.rcParams.find_all('preamble')
import matplotlib.pyplot as plt
plt.rcParams['text.latex.preamble'] = r'\usepackage[dvipsnames]{xcolor}'
plt.rcParams['text.usetex'] = True
plt.scatter([0, 1, 2, 3], [2,3,1,6])
plt.show()
```

and I can reproduce the bug.

**Comment by anntzer** [comment]
Thanks for the report.  Looks like the following patch fixes the bug, can you confirm?
```patch
diff --git i/lib/matplotlib/dviread.py w/lib/matplotlib/dviread.py
index 6f65de52b..6b7b52dc1 100644
--- i/lib/matplotlib/dviread.py
+++ w/lib/matplotlib/dviread.py
@@ -313,18 +313,26 @@ class Dvi:
         #   xxx comment
         #   down
         #   push
-        #     down, down
+        #     down
+        #     <push, push, xxx, right, xxx, pop, pop>  # if using xcolor
+        #     down
         #     push
         #       down (possibly multiple)
         #       push  <=  here, v is the baseline position.
         #         etc.
         # (dviasm is useful to explore this structure.)
+        # Thus, we use the vertical position at the first time the stack depth
+        # reaches 3, while at least three "downs" have been executed, as the
+        # baseline (the "down" count is necessary to handle xcolor).
+        downs = 0
         self._baseline_v = None
         while True:
             byte = self.file.read(1)[0]
             self._dtable[byte](self, byte)
+            downs += self._dtable[byte].__name__ == "_down"
             if (self._baseline_v is None
-                    and len(getattr(self, "stack", [])) == 3):
+                    and len(getattr(self, "stack", [])) == 3
+                    and downs >= 4):
                 self._baseline_v = self.v
             if byte == 140:                         # end of page
                 return True
```

**Comment by darthoctopus** [comment]
I can confirm that the patch fixes the issue for me. thanks for the quick response!

**Comment by tacaswell** [comment]
@darthoctopus Would you be interested in opening a PR with that patch and a test?
