### ISSUE TITLE
Document how to write a References section in examples

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#19232]
This should go into https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials

Also:
- Check if we can use another pattern than the hack using a code block and importing the desired functions. It seems we could also use a documentation block (c.f. https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation bullet point 2.)
- Consider adding the possibility for linking between examples. Is this technically only a ".. seealso::" directive?

**Comment by ianhi** [comment]
> Consider adding the possibility for linking between examples. Is this technically only a ".. seealso::" directive?

I think ideally there would be a `minigallery` defined by the example. Though im not sure sphinx-gallery supports that.

**Comment by rajpratyush** [comment]
@timhoffm does this issue needs work?

**Comment by timhoffm** [comment]
Yes it does.

There are multiple things to do here:

The trivial thing would be to just write down what we're currently doing. See, e.g. https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/fill.html#references.

However this is more like a hack with several drawbacks, which is why I'm a bit hesitant to document it as the recommended solution
- You need to put `import matplotlib` in
- You get the `Out[]` line.
- You have to mention `pyplot` as well as `Axes` to get references in both docs.

Also, I had the impression that this way of writing code and let sphinx gallery discover it does not always work, but I cannot point at an example right now.

The good solution would be to write a sphinx directive

~~~
.. gallery-reference::
   matplotlib.axes.Axes.fill
   matplotlib.pyplot.fill
   matplotlib.axes.Axes.axis
   matplotlib.pyplot.axis
~~~

That'd possibly be need to be done upstream in sphinx-gallery.

**Comment by timhoffm** [comment]
### Proposal: Switch to

~~~
###############################################################################
#
# .. admonition:: References
#
#    The use of the following functions, methods, classes and modules is shown
#    in this example:
#
#    - `matplotlib.axes.Axes.fill` / `matplotlib.pyplot.fill`
#    - `matplotlib.axes.Axes.axis` / `matplotlib.pyplot.axis`
~~~

Which results in

![grafik](https://user-images.githubusercontent.com/2836374/112550238-5ccada00-8dbf-11eb-961f-e295fcbfe98f.png)

This works without defining any new directives.

### For comparison: Current look

![grafik](https://user-images.githubusercontent.com/2836374/112550480-baf7bd00-8dbf-11eb-8db4-2643bbb93612.png)
