### ISSUE TITLE
Multicursor Widget not working with nbAgg backend

### ISSUE THREAD

**Issue by KIC** [matplotlib/matplotlib#19235]
Here is the very same plot via GUI and notepad backend, as you can see the cursor is only displayed at the last subplot in the notebook and not as expected in all subplots.

https://user-images.githubusercontent.com/10957396/103562316-244fea00-4ebb-11eb-9391-d4eb2604dab5.mp4

https://user-images.githubusercontent.com/10957396/103562319-25811700-4ebb-11eb-9fe9-5613de1379fe.mp4

**Comment by story645** [comment]
Hello can you please post a small code snippet that triggers this error?

**Comment by jklymak** [comment]
Closing for lack of follow up, but few free to request a re-open if you can provide more details
