### ISSUE TITLE
ERROR: Command errored out with exit status -4

### ISSUE THREAD

**Issue by rushi12565** [matplotlib/matplotlib#19250]
```ERROR: Command errored out with exit status -4:                                                  command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aiua7wzo/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aiua7wzo/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info                                                      cwd: /tmp/pip-install-aiua7wzo/matplotlib/                                                 Complete output (19 lines):                                                                     Edit setup.cfg to change the build options; suppress output with --quiet.                                                                       BUILDING MATPLOTLIB                               matplotlib: yes [3.3.1]                             python: yes [3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]]                             platform: yes [linux]                        sample_data: yes [installing]                         tests: no  [skipping due to configuration]                                                     macosx: no  [Mac OS-X only]                                                               running egg_info                                creating /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info                  writing /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/PKG-INFO          writing dependency_links to /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/dependency_links.txt                          writing namespace_packages to /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/namespace_packages.txt                      writing requirements to /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/requires.txt                                      writing top-level names to /tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/top_level.txt                                  writing manifest file '/tmp/pip-install-aiua7wzo/matplotlib/pip-egg-info/matplotlib.egg-info/SOURCES.txt'                                       ----------------------------------------    ERROR: Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.```

**Comment by jklymak** [comment]
Can you please format this, let us know what you were trying to do, and the version information we have requested?

**Comment by rushi12565** [comment]
yea my bad srry
I was trying to install a software on ubuntu which was installed on termux (I just wanted to try it 😅)and it had the following requirements

ConfigArgParse~=0.14
Flask-Caching~=1.8.0
ImageHash~=4.0
bitstring~=3.1
dataclasses>=0.6
geopy~=1.20
gevent==1.4.0
gpxdata~=1.2
imutils~=0.5
loguru~=0.4.0
matplotlib~=3.1
mysql-connector~=2.2
mysqlclient~=1.4
opencv-python>=4.1,<4.3
psutil~=5.6
pytesseract~=0.3
requests~=2.22
s2sphere~=0.2
websockets>=7
numpy~=1.18.0
apkutils~=0.6.6
matlink-gpapi~=0.4.4.5
greenlet!=0.4.17

these are the details of the ubuntu version, 

LSB Version: core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch                                          
Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS              
Release:20.04                           
Codename:focal

And while installing the requirements I came through this error,

 ERROR: Command errored out with exit status -4:                                                  command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hqr_0a4e/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hqr_0a4e/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info          cwd: /tmp/pip-install-hqr_0a4e/matplotlib/                                                 Complete output (19 lines):                                                     
Edit setup.cfg to change the build options; suppress output with --quiet.                       
```

BUILDING MATPLOTLIB                               matplotlib: yes [3.3.3]                             python: yes [3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]]                             platform: yes [linux]                        sample_data: yes [installing]            
tests: no  [skipping due to configuration] macosx: no  [Mac OS-X only]               

running egg_info                                creating /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info     writing /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/PKG-INFO     writing dependency_links to /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/dependency_links.txt     writing namespace_packages to /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/namespace_packages.txt     writing requirements to /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/requires.txt     writing top-level names to /tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/top_level.txt     writing manifest file '/tmp/pip-install-hqr_0a4e/matplotlib/pip-egg-info/matplotlib.egg-info/SOURCES.txt'     ----------------------------------------   
ERROR: Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.        
```

**Comment by rushi12565** [comment]
![2021-1-7_8-59-20](https://user-images.githubusercontent.com/74148058/103847873-21c1e000-50c7-11eb-8071-868a9367707e.PNG)

**Comment by timhoffm** [comment]
How did you install? pip or with your linux package manager or in another way?`What exactly were your commands?

**Comment by rushi12565** [comment]
I actually ran it with the pip command and Matplotlib was a requirement mentioned in the requirements text file

pip3 install - r requirements.txt

I already mentioned what were in the requirements text file

**Comment by jklymak** [comment]
Try a new environment and see if you can just install matplotlib?  Sounds like you have a package or library conflict - this error isn't something matplotlib is directly causing.  Did you "check the logs for full command output"?  Sometimes the answer is there.   I'm going to close because there isn't really an identified matploptlib bug, but you can either continue the discussion here, or move to discourse.matplotlib.org.  Of course we can reopen if we identify a bug that matplotlib can help with.

**Comment by JulioLP** [comment]
This is related to using numpy 1.19.5 in ARM processors. Solved here:

https://forums.developer.nvidia.com/t/troubles-installing-matplotlib-on-nano-with-python-3-7-3-8-and-a-virtual-env/166837
