### ISSUE TITLE
matplotlib.hist() density argument does not function as described

### ISSUE THREAD

**Issue by PhanatosZou** [matplotlib/matplotlib#19251]
### Bug report

hist() density argument does not function as described, and the area under histogram does not sum to 1

**Code for reproduction**

```python
import numpy as np
x = np.random.normal(12, 5, 1000)
n, bins, _  = plt.hist(x, bins = 50, density = True)
print(np.sum(n))
```

**Actual outcome**

```
1.629514751433083
```
<img src="https://user-images.githubusercontent.com/31944252/103816494-e9b09380-5019-11eb-8418-00e296a6bbf8.png" width="300" height="200">

**Expected outcome**

```
1.0
```

**Matplotlib version**

  * Operating system: ubuntu 16.04
  * Matplotlib version: 3.1.0
  * Python version: 3.6.8 
  * Jupyter version (if applicable): 5.7.8

**Comment by jklymak** [comment]
It *integrates* to one

```python
import matplotlib.pyplot as plt

import numpy as np
x = np.random.normal(12, 5, 1000)
n, bins, _  = plt.hist(x, bins = 50, density = True)
print(np.sum(n))
print(np.sum(n * np.diff(bins)))
```

```
1.4745857682498098
1.0
```

The docstring reads: 

```
density : bool, default: False
            If ``True``, draw and return a probability density: each bin
            will display the bin's raw count divided by the total number of
            counts *and the bin width*
            (``density = counts / (sum(counts) * np.diff(bins))``),
            so that the area under the histogram integrates to 1
            (``np.sum(density * np.diff(bins)) == 1``).

            If *stacked* is also ``True``, the sum of the histograms is
            normalized to 1.
```

I'm going to close because we have whittled this docstring to death.  However, if there were someway this could be more clear, please do comment below.

**Comment by PhanatosZou** [comment]
Got it. I referred to an older version of the doc.
