### ISSUE TITLE
Missing marker in documentation of plot

### ISSUE THREAD

**Issue by malinkallen** [matplotlib/matplotlib#19274]
### Problem
In the documentation of `plot` (https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.pyplot.plot.html), there is a list of markers. The marker 'x' (lower-case x) is included, but not 'X' (upper-case X). However, specifying upper-case 'X' works fine, and the marker is bolder than when I use lower-case 'x'.

### Suggested Improvement
Include upper-case 'X' in the list of markers.

**Matplotlib version**
I use matplotlib 3.1.2 on Ubuntu 20.04.

**Comment by timhoffm** [comment]
There's probably missing more. All of the unfilled and fill markers with a string representation from https://matplotlib.org/3.3.3/gallery/lines_bars_and_markers/marker_reference.html#sphx-glr-gallery-lines-bars-and-markers-marker-reference-py should work.
