### ISSUE TITLE
Progress callback in animation.save doesn't include writer conversion time

### ISSUE THREAD

**Issue by logancyang** [matplotlib/matplotlib#19270]
I'm trying to use this callback when generating a big gif.

```py
anim.save(
    "test.gif",
    writer="imagemagick",
    fps=30,
    progress_callback=lambda i, n: print(i),
)
```

The problem is it gets stuck at the end when `i` reaches `n` but the saving isn't actually complete. It seems after i reaches n, the writer is working hard to convert the frames into gif. That time is significant compared to the part covered by this progress callback. How do I include the writer into the progress?

**Comment by jklymak** [comment]
The way that is designed, I don't think you can.  Matplotlib and python have no idea what `imagmagick` is doing once it has started.  I'm going to close because I don't think we can help here.

**Comment by logancyang** [comment]
Fair, but I think the whole point of the progress tracking is defeated though.

**Comment by jklymak** [comment]
If it doesn't already at least have a message that it is starting up imagemagick, that seems doable.

**Comment by anntzer** [comment]
Maybe just call `progress_callback(n, n)` at the end and let the user handle that in whatever way they like?

**Comment by logancyang** [comment]
@anntzer Yeah that's what I'm doing for now. I'm using `tqdm` and added a message at the last callback "Converting to gif, it may take a while..." It would be nice that the callback can make it explicit that there's another stage after the last callback.

**Comment by timhoffm** [comment]
> Maybe just call `progress_callback(n, n)` at the end and let the user handle that in whatever way they like?

Sounds reasonable given the currently available API. Still, that needs explicit documentation what's happening after the callback `(n, n)`.

> It would be nice that the callback can make it explicit that there's another stage after the last callback.

Given the existing callback signature `def func(current_frame: int, total_frames: int)` we cannot make it explicit. I don't think this warrants an API change.

**Comment by logancyang** [comment]
I don't have a strong opinion what should be done here, just providing user feedback. You guys can decide what makes sense. 

Initially I didn't know about the progress callback, and the save process was a black box that took a long time. Then I found out about progress callback from stackoverflow. Tinkering with it for a bit I found it gets stuck at (n, n) (not really stuck but you need to check the process monitor to know that writer "imagemagick" is running). Anything that tells the user what it's doing will be helpful, imho.

**Comment by tacaswell** [comment]
I think the best we can do is to add a note to the callback docstring.  In general the "write to disk" part is done via shelling out to another process which we don't have any visibility into so there is no straight forward way to provide any finer grained progress information (as we do not have it!).

**Comment by logancyang** [comment]
Makes sense. I'll just close this issue then. The comments here are helpful, thanks everyone.
