### ISSUE TITLE
imshow with very large arrays not working as expected

### ISSUE THREAD

**Issue by Lioscro** [matplotlib/matplotlib#19276]
### Bug report

**Bug summary**

Hello, I am using `plt.imshow` to plot a very large array (~ 1 row x 150 million columns), and have noticed that the colors are not displayed properly.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

# Very large
array = np.zeros(150000000, dtype=np.uint8)
array[len(array) // 2:] = 1
fig, ax = plt.subplots(figsize=(10, 3))
im = ax.imshow(array.reshape(1, -1), vmin=0, vmax=1, aspect='auto')
fig.colorbar(im, ax=ax)

# 10x smaller
array = np.zeros(15000000, dtype=np.uint8)
array[len(array) // 2:] = 1
fig, ax = plt.subplots(figsize=(10, 3))
im = ax.imshow(array.reshape(1, -1), vmin=0, vmax=1, aspect='auto')
fig.colorbar(im, ax=ax)
```

**Actual outcome**
Very large
![image](https://user-images.githubusercontent.com/1281521/104198905-cd836c80-53f4-11eb-8b31-932a30da23db.png)

10x smaller
![image](https://user-images.githubusercontent.com/1281521/104198876-c4929b00-53f4-11eb-93ba-a1e6b45dcd54.png)

**Expected outcome**
Since we set the later half of the array to 1 (and the rest is 0), we expect the image to change color at 75 million, but we see that all pixels are colored as 0.

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.3.2 (also tested on 3.3.3)
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.8.3 (also tested on 3.6.9)
  * Jupyter version (if applicable):
  * Other libraries: 
```
ipython                       7.18.1
ipython-genutils              0.2.0
jupyter                       1.0.0
jupyter-client                6.1.7
jupyter-console               6.2.0
jupyter-core                  4.6.3
jupyterlab                    2.2.8
jupyterlab-pygments           0.1.1
jupyterlab-server             1.2.0
```
Python installed via miniconda, but matplotlib was installed via pip.

**Comment by jklymak** [comment]
I can reproduce this on Qt5Agg - they both are wrong, though N=1.5e6 works fine.   I don't have any good guesses as to the cause...

**Comment by jklymak** [comment]
Is this a regression?  i.e. did it ever work?

**Comment by Lioscro** [comment]
Hi, @jklymak, I'm not sure what you mean by regression, but I just noticed this behavior today when I was manually checking some plots I had generated last week. For a bit of context, I am plotting mutations along a mouse chromosome (which ranges from 216 million to 81 million in length).
Also, yes I've also noticed below a certain length the plot "seems" correct.

**Comment by jklymak** [comment]
But how are you *actually* looking at 216e6 data points in the x-direction?  My screen only has 5120 pixels in the x direction, and I wouldn't want to try and show more than 2560 data points, unless I were very careful to make sure I lined up with pixels.    I think you are going to have to do something more sophisticated than just `imshow` on the raw data set.

**Comment by Lioscro** [comment]
No, this never worked for me, at least in the limited amount of time I've been working with this data.

The purpose of my plot is to visualize mutation "hotspots" that usually occur in "chunks" (large contiguous parts along the chromosome). The ability to view each individual datapoint is not important for my purposes.

Additionally, here is an example of the behavior with multiple values.
```
array = np.zeros(1000000, dtype=np.uint8)
n_steps = 7
step_size = len(array) // (n_steps + 1)
for n, i in enumerate(range(0, len(array), step_size)):
    array[i:] = n
fig, ax = plt.subplots(figsize=(10, 3))
plt.imshow(array.reshape(1, -1), vmin=0, vmax=7, aspect='auto')
fig.colorbar(im, ax=ax)
```
![image](https://user-images.githubusercontent.com/1281521/104225371-4e9e2c00-5414-11eb-9968-0e2b030f1c63.png)

```
array = np.zeros(10000000, dtype=np.uint8)
n_steps = 7
step_size = len(array) // (n_steps + 1)
for n, i in enumerate(range(0, len(array), step_size)):
    array[i:] = n
fig, ax = plt.subplots(figsize=(10, 3))
plt.imshow(array.reshape(1, -1), vmin=0, vmax=7, aspect='auto')
fig.colorbar(im, ax=ax)
fig.patch.set_facecolor('white')
```
![image](https://user-images.githubusercontent.com/1281521/104225412-5a89ee00-5414-11eb-8eb0-a819452fe428.png)

**Comment by jklymak** [comment]
Right, so you are *grossly* under sampled if you use `imshow` on these data sets.  If I had 216e6 data points and was looking for hotspots, I would average some and then decimate...

Matplotlib can't do this sort of thing for you because we dont' know what the right filtering or decimation is for your data set.  

If you want to discuss more, please do so at discourse.matplotlib.org, where discussing data processing is more appropriate.  

We can keep this open, but we probably should just warn if an image is too big, rather than worrying about fixing this.

**Comment by Lioscro** [comment]
Yes, I believe a warning would be sufficient, as plotting such large datasets probably don't happen as often and in such cases there are ways to appropriately scale down the data (such as with binning). I wanted to report the issue as it is different from what I expected and was not aware such a restriction existed!

**Comment by dstansby** [comment]
I can reproduce this, on both QT5Agg and macos backends. The change seems to occur somewhere between an array size of 2**23 adn 2**24 for me. Interestingly, the tooltip that gives the mouseover value reports the correct value (0 on the left half of the image, 1 on the right) even if it's displayed wrong.

**Comment by dstansby** [comment]
Doing some digging, and the issue is on this line:
https://github.com/matplotlib/matplotlib/blob/1eef019109b64ee4085732544cb5e310e69451ab/lib/matplotlib/image.py#L492
With a large array, it is resampled so all of the resampled data ends up as 0, whereas for the slightly smaller array that works it is resampled correctly. Looks like this is going to be an issue in the `_image` C layer.

**Comment by jklymak** [comment]
Be interesting to see if https://github.com/matplotlib/matplotlib/pull/18782 fixes this, since it skips some of the funky resampling..

**Comment by dstansby** [comment]
More weirdness, in case it helps anyone trying to debug this... setting the last 2/3 of the array to 1, should result in this (with a low array size):
![good](https://user-images.githubusercontent.com/6197628/105646311-27753f00-5e97-11eb-93f6-d6960e2f0899.png)
but instead results in this (I have to set the size to 2e24 to get this):
![bad](https://user-images.githubusercontent.com/6197628/105646302-17f5f600-5e97-11eb-9f0b-8e696106fcc0.png)

**Comment by dstansby** [comment]
And finally (for tonight), I think I have discovered that the issue is for image widths (maybe image sizes?) that are > 2\*\*23. Not sure what's special about that's causing something to go wrong on the C (more specifically, I think AGG) level, but at this point I think it would be reasonable to add a warning if an image going into `image._resample()` is larger than that.

Also worth noting this is backend independent, as `AxesImage`s drawing code in `_make_image()` goes directly to `image._resample()`

**Comment by QuLogic** [comment]
Agg coordinates are limited to signed 24-bit integers:
https://github.com/matplotlib/matplotlib/blob/07aa92b15195381e9c3ee07f62ba7602caa5a46f/src/path_converters.h#L26-L29

**Comment by dstansby** [comment]
That would explain it. I think the action items here are:
- Work out if it's the width, or size of the image, that matters (should be easy to do by adding a row to the array in the above example)
- Add an appropriate warning to `resample()` if it is given an array bigger than this width or size.

Happy to do this, but might be a little while before I get round to it.

**Comment by jklymak** [comment]
I still think you should go ahead and downsample in python first.  A warning is fine, but easily ignored - plotting wrapped data can lead to misleading error.

**Comment by anntzer** [comment]
> Add an appropriate warning to resample() if it is given an array bigger than this width or size.

> A warning is fine, but easily ignored

I would just error out, as the result would be clearly nonsensical.

**Comment by jklymak** [comment]
Sure, but then at what point should we error out?   Like sending images with 2^20 entries is also nonsensical if you only have 2000 pixels.   I think we should consider at least a log message if subsampling is greater than a factor of 5.

**Comment by dstansby** [comment]
> Sure, but then at what point should we error out? Like sending images with 2^20 entries is also nonsensical if you only have 2000 pixels.

I appreciate it can be problematic if you're interested in variations on scales shorter than the downsampling scale, that doesn't stop me looking at 4k images all the time on my 1080p monitor.

> I think we should consider at least a log message if subsampling is greater than a factor of 5.

I wouldn't be against a debug log regardless of the subsampling factor.

**Comment by jklymak** [comment]
The point is that erroring out stops the analysis which *could* sensibly continue by Sub sampling and interactive zooming.  Subsampling gives you some idea what is in the image even it is aliased.    Note that we were always aliased on subsampling until very recently so aliasing huge images is hardly a great sin.
