### ISSUE TITLE
[Newbie]Can I put Marker='option' of Scatter() as a ndarray? 

### ISSUE THREAD

**Issue by RGB-000000** [matplotlib/matplotlib#19284]
![image](https://user-images.githubusercontent.com/76979073/104343010-cc5e5680-553e-11eb-8a33-e74e9fbdd0ab.png)

![image](https://user-images.githubusercontent.com/76979073/104343057-d6805500-553e-11eb-9f37-7d0b50a43487.png)

from what I've printed, the shape of ndarray seems to fit each other.

![image](https://user-images.githubusercontent.com/76979073/104343216-04659980-553f-11eb-8181-4a1847f9c89f.png)
ValueError: could not convert string to float: 'o'
I thought marker should get strings...

Please help

**Comment by jklymak** [comment]
Can you ask questions like this at discourse.matplotlib.org?  Thanks for your understanding....

**Comment by RGB-000000** [comment]
> Can you ask questions like this at discourse.matplotlib.org? Thanks for your understanding....

Thank you!
