### ISSUE TITLE
Proposed setting for 24/7/365 operation for graphic output from a script started by another script. 

### ISSUE THREAD

**Issue by GerfriedC** [matplotlib/matplotlib#19295]
Hello,
 using a raspberry PI Zero I had to start the python script from the shell without matplolib output capability, since running it in the GUI lead to a frequent crash of the GTK, including matplotlib in the script
What is the correct way of starting a python script with matplotlib output, where the script is loaded on runtime? 
many thanks

**Comment by jklymak** [comment]
Please open a discussion at discourse.matplotlib.org.  Thanks!
