### ISSUE TITLE
Problems with stacked bar plots

### ISSUE THREAD

**Issue by RoniHaas** [matplotlib/matplotlib#19302]
Hi! We would appreciate your help with a problem that suddenly occurred, using matplotlib for stacked bar plots.

Using this core code:
 
![image](https://user-images.githubusercontent.com/39231609/104707392-01c49900-5725-11eb-9802-8ca06a3d248f.png)

We were able to generate great plots without any problem, like this:
 
![image](https://user-images.githubusercontent.com/39231609/104708157-fde54680-5725-11eb-8a58-ed449f0a89f5.png)

Since one of the users run on the server this command: 
`Pip install matplotlib –user
`
suddenly, the plots are not always created (the tiff file in not created or created but empty) and if they do, the colors are merged and the text overlaps each other:

![image](https://user-images.githubusercontent.com/39231609/104707970-caa2b780-5725-11eb-87c2-cfc394632aa2.png)

Any idea why is this and how to fix this?
Thank you!!!

**Comment by jklymak** [comment]
Please discuss in discourse.matplotlib.org.  Also please provide a minimal complete working example if you post there.  We can open a big report if one can be narrowed down. Thanks!
