### ISSUE TITLE
Reduce whitespace in Choosing Colormaps tutorial plots

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#19308]
In the Choosing Colormaps tutorial (https://matplotlib.org/tutorials/colors/colormaps.html), there's currently a lot of whitespace in the plots showing the different colourbars. It would be a bit nicer if this whitespace could be removed:

![Screenshot 2021-01-17 at 12 14 20](https://user-images.githubusercontent.com/6197628/104840155-877b4c80-58bd-11eb-8b1f-a58b95ae19b7.png)

**Comment by Kushagrabainsla** [comment]
I want to contribute, it's my first time, can you help me figure out where I've to start?

**Comment by jklymak** [comment]
https://matplotlib.org/devel/index.html and you will want to edit https://github.com/matplotlib/matplotlib/blob/master/tutorials/colors/colormaps.py

**Comment by Kushagrabainsla** [comment]
I tried running the script, it's giving a value error :
ValueError: Colormap turbo is not recognized.

**Comment by rajpratyush** [comment]
is this issue still open??

**Comment by jklymak** [comment]
No its not....
