### ISSUE TITLE
constrained_layout + fixed-aspect axes + bbox_inches="tight"

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19339]
### Bug report

**Bug summary**

constrained_layout, fixed aspect axes (e.g. from `imshow`), and savefig(bbox_inches="tight") don't play well together.

**Code for reproduction**

```python
fig = plt.figure(constrained_layout=True)
fig.add_subplot().imshow(np.random.rand(10, 10))
fig.savefig("/tmp/out.png", bbox_inches="tight")
```

**Actual outcome**

![out](https://user-images.githubusercontent.com/1322974/105507607-b03f7f80-5ccb-11eb-8a00-70ed5130b1e5.png)

The axes are cropped, and the aspect=1 is lost (pixels are not square anymore, but slightly elongated).

**Expected outcome**

Not the above.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): HEAD
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 39
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Huh, thats strange.  I almost never use bbox_inches='tight' so I haven't come across that one.  As a work around, you can of course trigger a draw and then turn CL off after it has done its thing.  

```python
plt.show()
fig.set_constrained_layout(False)
fig.savefig("/tmp/out.png", bbox_inches="tight")
```

**Comment by jklymak** [comment]
I'll note that this is a 3.4 regression with the CL overhaul, but I will try and fix it soonish...

**Comment by tacaswell** [comment]
@jklymak Should we block 3.4 over this?

**Comment by jklymak** [comment]
I don't know how many people this would break, I don't know the 3.4 timescale and I don't know how willing we are to turn around a quick 3.4.1.    The workaround is pretty mild.  OTOH we could revert the CL overhaul and reintroduce after this is fixed?  A bit inelegant to introduce a big change on a point release but I don't mind shepherding it through.

**Comment by tacaswell** [comment]
I don't think we should backout the CL overhaul (that is the worst of all possible options).

We almost always have a X.Y.1 release within a month of the X.Y.0 so I do expect that to be pretty fast.  Current goal for 3.4 is RC next week (week of Jan 25).

**Comment by jklymak** [comment]
I guess one other consideration is this does break `%matplotlib inline`, at least when folks are using fixed-aspect axes.  I can promise to try and fix over the w/e, but no gauruntees.
