### ISSUE TITLE
Add support for alluvial diagrams

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#19351]
Hello,
[alluvial diagrams](https://en.wikipedia.org/wiki/Alluvial_diagram) are a great way to represent changes thru time of quantities from sources to destinations (they are also sometimes referred to as energy flows, since they were popularized by diagrams showing how different sources of energy, hydro/nuclear/coal/etc, were distributed and/or used to various uses).

They are often defined as a special case of [Sankey diagrams](https://en.wikipedia.org/wiki/Sankey_diagram) (but not all [agrees](http://www.datasmith.org/2020/05/02/alluvial-plots-vs-sankey-diagrams/)) but when i looked at [Sankey diagrams in mpl](https://matplotlib.org/3.3.3/api/sankey_api.html), they dont really allow to create alluvial diags.

There was an early [implementation](https://github.com/vinsburg/alluvial_diagram) of alluvial flows, but that project no longer works properly with up-to-date mpl.

I think alluvial diagrams would be a great addition to matploltib.

Thanks!

**Comment by story645** [comment]
would the module described in #18281 support the plots you're interested in?

**Comment by sandrotosi** [comment]
Indeed, that seems really close to what i need, i'm gonna play with it a bit and confirm -- thanks!

**Comment by sandrotosi** [comment]
@story645 i added my comments there and i was able to use that module for what i need: do you want to keep this open or shall we close it and follow up on #18281 ?

**Comment by story645** [comment]
Thanks, will close then 😄
