### ISSUE TITLE
Size of pie chart affected by frame?

### ISSUE THREAD

**Issue by twisterior** [matplotlib/matplotlib#19365]
Hi all.

Is it an issue or on purpose that enabling and disabling the frame in plt.pie() results in different sized pie charts? In my opinion the code below should provide identical sized charts. If it is on purpose, can you give me a reference? I am using the conda version of python (3.7) but colleagues experience the same behavior.

Best regards

**Code for reproduction**

```python
import matplotlib.pyplot as plt
f = plt.figure(figsize=(10,5),dpi=300)
ax1 = f.add_axes([0,0,0.5,1])
ax2 = f.add_axes([0.5,0,0.5,1])
ax1.pie([180,180],center=(0.5,0.5),radius=0.5,frame=False)
ax2.pie([180,180],center=(0.5,0.5),radius=0.5,frame=True)
plt.show()
```

**Actual outcome**
![Figure_1](https://user-images.githubusercontent.com/59151225/105855946-ec832080-5fe8-11eb-9c47-302218c4b4f2.png)

**Expected outcome**
![Figure_2](https://user-images.githubusercontent.com/59151225/105856068-150b1a80-5fe9-11eb-8567-c1de8387013e.png)

**Comment by jklymak** [comment]
Looks like it is on purpose?   I agree its not very consistent.   https://github.com/matplotlib/matplotlib/blob/2ea0d6337fad12bc2941c168a4e78c63cb12036a/lib/matplotlib/axes/_axes.py#L3153

**Comment by twisterior** [comment]
Indeed - this looks really strange to me. At least, I know now the exact factor to fit the radius. Thanks!
