### ISSUE TITLE
Streamplot raises RuntimeWarning when parameter arrowsize=0

### ISSUE THREAD

**Issue by peterdsharpe** [matplotlib/matplotlib#19361]
### Bug report

The streamplot function `matplotlib.pyplot.streamplot()` gives an unhandled `RuntimeWarning` when the argument `arrowsize=0` is passed to it. The intended purpose of passing this argument is to create a streamplot with lines but no arrows. While this strategy works, it raises a `RuntimeWarning`.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

w = 3
Y, X = np.mgrid[-w:w:100j, -w:w:100j]
U = -1 - X ** 2 + Y
V = 1 + X - Y ** 2
speed = np.sqrt(U ** 2 + V ** 2)

plt.figure()
plt.streamplot(X, Y, U, V, arrowsize=0)
plt.show()
```

**Actual outcome**

```
...site-packages\matplotlib\patches.py:2993: RuntimeWarning: invalid value encountered in double_scalars
  cos_t, sin_t = head_length / head_dist, head_width / head_dist
```

**Expected outcome**

No `RuntimeWarning` should be raised.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://backend_interagg
  * Python version: 3.8.5
  * Jupyter version (if applicable): N/A
  * Other libraries: NumPy 1.19.1

pip installed.

**Comment by oscargus** [comment]
The suggested way to get a `streamplot` without arrowheads is to pass `arrowstyle='-'`, so
`plt.streamplot(X, Y, U, V, arrowstyle='-')`.

I'll close this, but feel free to reopen if you think that there are still issues or have suggestions how to make this clearer.
