### ISSUE TITLE
v3.3.0 breaks sca(ax)

### ISSUE THREAD

**Issue by david-c-wong** [matplotlib/matplotlib#19380]
Hi,

I encountered an error calling sca(ax) together with usage of FigureCanvasTkAgg().  Following would be a simple sequence illustrating the problem.
```
 // Note that plt.gca().figure == figure
... = FigureCanvasTkAgg(figure, ...)
plt.sca(plt.gca())
```
The problem is because FigureCanvasTkAgg(...) will call FigureCanvasBase.__init__(...) which resets the manager field needed in sca().  Below are the listing showing the problem:
```
class FigureCanvasBase:
    def __init__(self, figure):
        ...
        figure.set_canvas(self)
        self.figure = figure
        **# Here it is setting canvas.manager to None!!**
        self.manager = None
        ...

def sca(ax):
    """
    Set the current Axes to *ax* and the current Figure to the parent of *ax*.
    """
    if not hasattr(ax.figure.canvas, "manager"):
        raise ValueError("Axes parent figure is not managed by pyplot")
      **# !!! ax.figure.canvas.manager is None!**
    _pylab_helpers.Gcf.set_active(ax.figure.canvas.manager)
    ax.figure.sca(ax)
```

For workaround, I checked out old version of sca(ax) from 3.2.2 and it seems to be working.  On the other hand, I am not sure whether the old version is robust in v3.3.0 despite of this working situation.
```
def sca(ax):
    """
    Set the current Axes instance to *ax*.

    The current Figure is updated to the parent of *ax*.
    """
    managers = _pylab_helpers.Gcf.get_all_fig_managers()
    for m in managers:
        if ax in m.canvas.figure.axes:
            _pylab_helpers.Gcf.set_active(m)
            m.canvas.figure.sca(ax)
            return
    raise ValueError("Axes instance argument was not found in a figure")
```
Please check and see whether bring back of old version of sca(ax) is a correct fix of this issue.

**Comment by QuLogic** [comment]
Please provide a _complete_ example. Have you tried with 3.3.3?

**Comment by jklymak** [comment]
`plt.sca(plt.gca())` certainly seems tautological!

**Comment by david-c-wong** [comment]
I will try to create a complete standalone example to reproduce the bug.  Note that plt.sca(plt.gca()) is just used to trigger the bug and not what we did for the program we developed.  It's essentially demonstrating a simple statement "a=a" failed after something has been done to the plot.  Note that the same statement "plt(sca(plt.gca())" was running fine before the line "... = FigureCanvasTkAgg(figure, ...)".

**Comment by david-c-wong** [comment]
Hi, 

Sorry for the delay.  I am pasting a bug repeater below.

> import matplotlib.pyplot as plt
> import tkinter as tk
> from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
> root = tk.Tk()
> fig, ax = plt.subplots()
> canvas = FigureCanvasTkAgg(fig, root)
> plt.sca(plt.gca())
> root.mainloop()

To reproduce the error I used Python 3.7.7 and matplotlib version 3.3.4.

>>> plt.sca(plt.gca())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\matplotlib\pyplot.py", line 984, in sca
    _pylab_helpers.Gcf.set_active(ax.figure.canvas.manager)
  File "C:\...\lib\site-packages\matplotlib\_pylab_helpers.py", line 127, in set_active
    cls.figs[manager.num] = manager
AttributeError: 'NoneType' object has no attribute 'num'

I then re-ran the program with Python 3.7.7 and matplotlib 3.2.2 and no longer got the bug.

Thanks.

david

**Comment by tacaswell** [comment]
I think the problem here is that you are "stealing" the figure from the pyplot, if you are embedding in a full GUI (which it looks like you are doing given that you are creating `FigureCanvasTkAgg` and running your own main loop),   Does your application work if you don't do `plt.sca(plt.gca())` ?  Mixing GUI objects that you are explicitly managing and the implicit pyplot API can lead to other surprising / brittle behavior.

It looks like the source of the change is 9f6f02249afe96ffa830cdcc3c0f3e9a0ae5f662 which switched from searching all known managers for the one that contains the ax you passed to asking the axes's figure's canvas for its manager.  Because you created your own canvas it does not have a manager, hence the failure.

**Comment by jklymak** [comment]
@david-c-wong is this still an issue?  Is there something in the docs you feel we should fix?

**Comment by david-c-wong** [comment]
This is still an issue as my code breaks if I use the new sca() function.  As a workaround, I simply copied the old implementation of sca(ax) (listed above) and paste it to my code and use it.  

Looking at the code, it seems to be doing a reasonable job by iterating managers to find the axis and do the right thing about the manager and the relevant axis.  

Since this works I did not come back here to request for fix.  On the other hand, if that implementation is more robust than current one, would it make sense to bring back that implementation ?  Or if there are some features added for new implementation, would it be sensing making to bring the new features to the old implementation carefully so less code would be broken?

Thanks.

**Comment by jklymak** [comment]
I think the consensus here is that you were simply taking advantage of an undocumented side- effect and that you should not be using `pyplot` in your Tk app.

**Comment by david-c-wong** [comment]
Do you mean I could not use matplotlib plot in my Tk app or you have a recipes for that use case?  I think we were following some examples like https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html to develop our code.

**Comment by jklymak** [comment]
No of course you embed your figure in a tk window.  But pyplot routines will not work.  Just use the object oriented ones.  

That example is a bit goofy because it uses a chained method call. fig.add_subplot().plot().  Better for beginners would be ax=fig.add_subplot(), ax.plot().  Where ax is the axes object you are trying to get.

**Comment by david-c-wong** [comment]
I see.  So, by object oriented calls, you are suggesting us to invoke the method of the object (axis or figure) explicitly rather than using the calls assuming current axis or current figure.

Assuming this is the case, it is a great suggestion.  We also heading to that direction these days as we move forward.  We found it's indeed less error prone and easier to follow.

Thanks for your suggestions.
