### ISSUE TITLE
imshow colormap axis labels not being returned if plt.show() not called inside of a function

### ISSUE THREAD

**Issue by lkev** [matplotlib/matplotlib#19381]
### Bug report

**Bug summary**

Say `ax` is an axis which contains an `imshow` plot and `colorbar`, which has been returned from a function. Labels for the colorbar axis are incorrect when using `ax.collections[0].colorbar.ax.get_yticklabels()` when `plt.show()` is not called from within that function. The labels are blank or in some cases just string versions of their tick value (e.g. `['0.0', '0.2', '0.5']`, even when there are words set for the labels (e.g. `['A', 'B', 'C']`).

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt


def cbar(show):
    fig, ax = plt.subplots(figsize=(6, 1))
    mesh = ax.pcolormesh(np.arange(100).reshape((10, 10)))
    cbar = fig.colorbar(mesh, ax=ax)
    cbar.set_ticks([0, 20, 80])
    cbar.set_ticklabels(['A', 'B', 'C'])

    if show:
        plt.show()
    plt.close()

    return ax


ax_show = cbar(True)
ax_noshow = cbar(False)
labels_show = [
    tick.get_text() for tick in
    ax_show.collections[0].colorbar.ax.get_yticklabels()
        ]
labels_noshow = [
    tick.get_text() for tick in
    ax_noshow.collections[0].colorbar.ax.get_yticklabels()
        ]

print(labels_show)
print(labels_noshow)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/3269734/106059665-f12ffd80-60ea-11eb-9499-3ccf5a4f89e4.png)
```python
['A', 'B', 'C']
['', '', '']
```

**Expected outcome**

Both `labels_show` and `labels_noshow` should both be `['A', 'B', 'C']`

**Matplotlib version**

  * Operating system: **OSX 11.1**
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): **3.3.3**
  * Matplotlib backend (`print(matplotlib.get_backend())`):  `module://ipykernel.pylab.backend_inline`
  * Python version: **3.8.5 64-bit**
  * Jupyter version (if applicable): **N/A**
  * Other libraries: **numpy 1.19.4**

installed from default conda channel

**Comment by jklymak** [comment]
Yes, thats how it is with all axes - the ticks are not populated until a draw.  You can trigger a draw by `fig.canvas.draw()` if you dont' want to pop a figure up.

**Comment by lkev** [comment]
Ah ok gotcha thanks. Is there a reason for the inconsistency between colorbar axes and the main plot axis in the below?

```python
def cbar(show):
    fig, ax = plt.subplots(figsize=(6, 1))
    ax.set_xticklabels(['Zero', 'Two', 'Four', 'Six', 'Eight', 'Ten'])
    mesh = ax.pcolormesh(np.arange(100).reshape((10, 10)))
    cbar = fig.colorbar(mesh, ax=ax)
    cbar.set_ticks([0, 20, 80])
    cbar.set_ticklabels(['A', 'B', 'C'])

    if show:
        plt.show()
    plt.close()

    return fig, ax


fig_noshow, ax_noshow = cbar(False)
cbar_labels_noshow = [
    tick.get_text() for tick in
    fig_noshow.axes[0].get_yticklabels()
        ]
xaxis_labels_noshow = [
    tick.get_text() for tick in
    fig_noshow.axes[0].get_xticklabels()
        ]

print(cbar_labels_noshow)
print(xaxis_labels_noshow)
```
```python
>>> ['', '', '']
>>> ['Zero', 'Two', 'Four', 'Six', 'Eight', 'Ten']
```

**Comment by jklymak** [comment]
Colorbars have various inconsistencies?  We are trying to drag colorbar to be the same as axes, but it is work: https://github.com/matplotlib/matplotlib/pull/18900 I wouldn't recommend anyone look at this deeper until #18900 is in.  For now, just go ahead and trigger a draw if you somehow lost track of what ticks you manually set.

**Comment by lkev** [comment]
Thanks - good to know. I've tried `fig.canvas.draw()`, but still getting the same result back. I've done it both inside and outside the function. Should this be the case?

**Comment by jklymak** [comment]
If I replace `plt.show` with `plt.canvas.draw()` in your code above, I get the same result....

**Comment by lkev** [comment]
I think I see where the issue is. When I replace it with `plt.draw()`, it works. But I can't get it to work when running tests (my test env is the same env I described above):

I originally came across this issue while writing a test for a plotting function I'm working on.


```python
class TestCbar(unittest.TestCase):
    def test_cbar_noshow(self):
        fig, _ = cbar(False)
        result = [
            tick.get_text() for tick in
            fig.axes[1].get_yticklabels()
        ]
        expected = ['A', 'B', 'C']

        self.assertListEqual(result, expected)
```

Result:
```
======================================================================
FAIL: test_cbar_noshow (test_plots.TestCbar)
----------------------------------------------------------------------
Traceback (most recent call last):

AssertionError: Lists differ: ['', '', ''] != ['A', 'B', 'C']

First differing element 0:
''
'A'

- ['', '', '']
+ ['A', 'B', 'C']
?   +    +    +


----------------------------------------------------------------------
Ran 1 test

FAILED (failures=1)
```

**Comment by dstansby** [comment]
I wonder if this issue is specific to the `module://ipykernel.pylab.backend_inline` kernel.

**Comment by jklymak** [comment]
Are there any actual action items here, or can this be closed?
