### ISSUE TITLE
Inconsistent default color cycle behavior in ax.bar and ax.fill_between 

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#19385]
### Bug report

**Bug summary**

`ax.bar` and `ax.fill_between` are inconsistent in terms of whether they advance the color cycle if `facecolor` but not `color` are specified.

This is a pretty minor bug but it drove me nuts tracking it down so I figured I'd report it.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

x1, y1 = [0, 1], [1, 2]
x2, y2 = [2, 3], [1, 2]

ax1 = plt.figure().subplots()
ax1.bar(x1, y1, facecolor=".5")
ax1.bar(x2, y2)

ax2 = plt.figure().subplots()
ax2.fill_between(x1, y1, facecolor=".5")
ax2.fill_between(x2, y2)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/315810/106077452-8e853480-60df-11eb-924b-e9665a7ab389.png)
![image](https://user-images.githubusercontent.com/315810/106077505-abba0300-60df-11eb-9955-ac3620669e81.png)

**Expected outcome**

I'd expect the second artist(s) to have the same color in the two plots. I'm not sure which is "correct". Actually ... `scatter` looks like `fill_between` so I guess `bar` is the odd-one-out here.

**Matplotlib version**

  * Operating system: macos
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): pylab inline
  * Python version:  3.8

**Comment by tacaswell** [comment]
If you pass `color=0.5` to `ax.bar` the color cycle does not advance so this is something subtle.

**Comment by WeatherGod** [comment]
The property cycle does not advance if all of the keys for the cycler are
already specified (modulo some weirdness between whether or not the
particular plotting function actually uses the keys or not). At least, in
theory.

The facecolor/edgecolor/linecolor equivalence to color is something I don't
think I ever really thought about when I designed the system. Might need to
be thought out more completely.

**Comment by mwaskom** [comment]
I can get bar to behave with

```python
plt.bar(0, 1, facecolor=".5", color="none")
plt.bar(1, 2)
```

fwiw

**Comment by WeatherGod** [comment]
Yeah, that makes sense. The check is simply for the existence of the
specified keys, not whether or not the keys specified anything that gets
ignored. Again, this just means we need to rethink the logic here a bit.

To expand a bit, imagine a property cycle that has "hatch" in it as well as
"color", and also consider plot() in addition to bar() and fill_between().
How should they advance their respective cycles? (Remember, plot() and
hist()/bar()/fill_between() have separate copies of the same cycler).

**Comment by mwaskom** [comment]
> (Remember, plot() and hist()/bar()/fill_between() have separate copies of the same cycler).

Is that true? I know `plot` has a distinct cycle but I think most of the other functions share a cycle, e.g.

```python
plt.fill_between([0, 1], [0, 1])
plt.bar(2, 2)
plt.scatter(3, 1.5, s=300)
```

![image](https://user-images.githubusercontent.com/315810/106138561-4a734d80-613a-11eb-9636-46f0b62ef9fd.png)

**Comment by WeatherGod** [comment]
Indeed, we are saying the same thing. Sorry for the confusion.
