### ISSUE TITLE
ellipse size in a legend

### ISSUE THREAD

**Issue by miniufo** [matplotlib/matplotlib#19397]
I have to plot diffusivity (or tidal) ellipses using different scales and add a proper legend to show their scales like this figure:
![image](https://user-images.githubusercontent.com/9312831/106221417-8bda2a80-6218-11eb-8437-135794386014.png)
I have struggled quite a time to do this and found that the scales of the plot and legend are not the same.  For vector, there is a [`ax.quiverkey` function](https://matplotlib.org/3.3.3/gallery/images_contours_and_fields/quiver_demo.html#sphx-glr-gallery-images-contours-and-fields-quiver-demo-py).  I just want to know if there is a ellipse equivalent to that so I can do this in a easy and clean way.  Thanks.

**Comment by jklymak** [comment]
You will have to do some work, but does https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html help?

**Comment by miniufo** [comment]
Thanks @jklymak , I tried various methods with `ax.legend` and the most closest solution is [here](https://stackoverflow.com/questions/58274611/want-to-plot-different-sized-colored-ellipses-on-matplotlib-legend).  However, I found that the size of the ellipse I put in the legend is not the same as those in the plot, even when their major/minor axes are exactly the same.

Currently, I add some messy codes of three extra ellipses, three texts, and a white box, and put them properly so that they look like a legend.  This is vulnerable and have to be adjusted when the figure size changes or adjust the size of the ellipses.  Just want to know if there is a better way like `ax.quiverkey`.

**Comment by jklymak** [comment]
I see.  No I don't think there is an "Ellipse Key".  Quiver plots are quite a bit more prevalent.  I would expect that a stand-alone "ellipse-key" wouldn't be out of the question.  However for any legend-like functions the kwarg list quickly gets large..
