### ISSUE TITLE
Boxplot: Median line too long after changing linewidth

### ISSUE THREAD

**Issue by Kadabash** [matplotlib/matplotlib#19409]
When changing the `linewidth` property of the median line in boxplots, the line will extend beyond the box width.

For example,
```python
import matplotlib.pyplot as plt

data = [[1, 2, 3, 4, 5]]
fig, ax = plt.subplots()
ax.boxplot(data,
           medianprops={"linewidth": 8})
```
gives (on Matplotlib 3.2.2):
[<img src="https://user-images.githubusercontent.com/26203394/106387844-8a089680-63d3-11eb-944b-e22ead07b4ea.jpg" width=450>](https://user-images.githubusercontent.com/26203394/106387844-8a089680-63d3-11eb-944b-e22ead07b4ea.jpg)

By simply chaning the `solid_capstyle` propery to `"butt"` in
```python
ax.boxplot(data,
           medianprops={"linewidth": 8,
                        "solid_capstyle": "butt"})
```
I was able to improve this a bit (I stole that trick from [here](https://stackoverflow.com/a/10297860)):
[<img src="https://user-images.githubusercontent.com/26203394/106387859-a0aeed80-63d3-11eb-8948-5ffac5306052.jpg" width=450>](https://user-images.githubusercontent.com/26203394/106387859-a0aeed80-63d3-11eb-8948-5ffac5306052.jpg)

Ideally, one could now reduce the median line length such that it no longer overlaps with the black bounding line of the box.
Since the box line width is only accessible in "points" units, it would need to be transformed to data units.
I was unable to get this to work, though.

Would it be possible/desirable to change the default setting for `solid_capstyle`?
Could this be handled in a different way?

**Comment by anntzer** [comment]
Likely it's a zorder issue? #18216/#17247 likely matter too.

**Comment by Kadabash** [comment]
Just another note: The *mean* (as opposed to *median* lines) do not seem to have the same issue:
```python
data = [[1, 2, 3, 4, 7]]
fig, ax = plt.subplots()
ax.boxplot(data,
           showmeans=True,
           meanline=True,
           meanprops={"linewidth": 8})
```
gives me
[<img src="https://user-images.githubusercontent.com/26203394/106388383-32b7f580-63d6-11eb-808b-ffd99add329b.jpg" width=450>](https://user-images.githubusercontent.com/26203394/106388383-32b7f580-63d6-11eb-808b-ffd99add329b.jpg)
where the line length is fine. (The line is broken because that is the default mean line style.)

**Comment by Kadabash** [comment]
A symptomatic workaround for the overlapping issue would be to change
```python
zdelta = 0.1
```
in [this line](https://github.com/matplotlib/matplotlib/blob/603cf1a8d3030a8e16f0a51516ef9fd9b70e5e7b/lib/matplotlib/axes/_axes.py#L3992) to
```python
zdelta = - 0.1
```
That resolves it for me.

As far as I can see, `zdelta` is only used for drawing mean and median lines, so changing that should be safe.

**Comment by tacaswell** [comment]
There are different cap styles for solid lines and dashed lines.

This is also a case where the re-scaling of the dash pattern with linewidth is not an improvement...

**Comment by oscargus** [comment]
Zooming in gives that the zorder for the mean line indeed should be changed as well (as it is clear that there are different cap styles). 

![image](https://user-images.githubusercontent.com/8114497/172006290-aec4d4a7-f457-42b3-bde5-f7cb9694d60e.png)

**Comment by oscargus** [comment]
Should be a first good issue: change the default cap style and the zorder. Problems may involve testing.

**Comment by kidkoder432** [comment]
> There are different cap styles for solid lines and dashed lines.

Where are these defined? Maybe changing the default cap style would help.

**Comment by kidkoder432** [comment]
> > There are different cap styles for solid lines and dashed lines.
> 
> Where are these defined? Maybe changing the default cap style would help.

Nevermind, found it in `lines.py:299`
