### ISSUE TITLE
Transforms and datetime axis

### ISSUE THREAD

**Issue by Phlya** [matplotlib/matplotlib#19408]
### Bug report
I posted this on the discourse a few days ago and didn't receive any response. Hoping it gets some attention here.

**Transforms don't play well with datetime axes - or am I doing something wrong?**

I am trying to help a user with adjustText to use it together with a time series plot: https://stackoverflow.com/questions/65835978/timeline-of-events-setting-annotation-location/65856798#65856798

Recently adjust_text got some improvements to work with arbitrary transforms, which helps it work with, I thought, any kind of matplotlib axes, and it definitely helped with maps and projections, for example.
However it seems to be broken when working with datetime axes. Older versions, I think, would give some random chaotic results, unless the plot was actually created using `plot_date`, while currently it just breaks. Unfortunately, I personally have zero experience working with this time series data, and it’s quite confusing. Here is a simple example that produces the same error as what I get when using adjust_text:

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.dates as mdates
from datetime import datetime
names = ['v2.2.4', 'v3.0.3', 'v3.0.2', 'v3.0.1', 'v3.0.0', 'v2.2.3',
        'v2.2.2', 'v2.2.1', 'v2.2.0', 'v2.1.2', 'v2.1.1', 'v2.1.0',
        'v2.0.2', 'v2.0.1', 'v2.0.0', 'v1.5.3', 'v1.5.2', 'v1.5.1',
        'v1.5.0', 'v1.4.3', 'v1.4.2', 'v1.4.1', 'v1.4.0']

dates = ['2019-02-26', '2019-02-26', '2018-11-10', '2018-11-10',
            '2018-09-18', '2018-08-10', '2018-03-17', '2018-03-16',
            '2018-03-06', '2018-01-18', '2017-12-10', '2017-10-07',
            '2017-05-10', '2017-05-02', '2017-01-17', '2016-09-09',
            '2016-07-03', '2016-01-10', '2015-10-29', '2015-02-16',
            '2014-10-26', '2014-10-18', '2014-08-26']
dates = [datetime.strptime(d, "%Y-%m-%d") for d in dates]
levels = np.tile([-5, 5, -3, 3, -1, 1],
                 int(np.ceil(len(dates)/6)))[:len(dates)]

f, ax = plt.subplots()
ax.scatter(dates, levels)
texts = []
for x, y, l in zip(dates, levels, names):
    texts.append(ax.text(x, y, l))
texts[0].get_transform().transform(texts[0].get_position())
```

**Actual outcome**

Which produces the plot as expected, but the last line gives an error that I don’t understand:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-36886e03c6a3> in <module>
      4 for x, y, l in zip(dates, levels, names):
      5     texts.append(ax.text(x, y, l))
----> 6 texts[0].get_transform().transform(texts[0].get_position())

~/miniconda/envs/adjustText/lib/python3.7/site-packages/matplotlib/transforms.py in transform(self, values)
   1403 
   1404         # Transform the values
-> 1405         res = self.transform_affine(self.transform_non_affine(values))
   1406 
   1407         # Convert the result back to the shape of the input values.

~/miniconda/envs/adjustText/lib/python3.7/site-packages/matplotlib/transforms.py in transform_affine(self, points)
   2363     def transform_affine(self, points):
   2364         # docstring inherited
-> 2365         return self.get_affine().transform(points)
   2366 
   2367     def transform_non_affine(self, points):

~/miniconda/envs/adjustText/lib/python3.7/site-packages/matplotlib/transforms.py in transform(self, values)
   1714     def transform(self, values):
   1715         # docstring inherited
-> 1716         return self.transform_affine(values)
   1717 
   1718     def transform_affine(self, values):

~/miniconda/envs/adjustText/lib/python3.7/site-packages/matplotlib/transforms.py in transform_affine(self, points)
   1796             tpoints = affine_transform(points.data, mtx)
   1797             return np.ma.MaskedArray(tpoints, mask=np.ma.getmask(points))
-> 1798         return affine_transform(points, mtx)
   1799 
   1800     if DEBUG:

TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

```

**Expected outcome**
Transformed coordinate of the text object.

Is this a wrong way to use datetimes when plotting? Or is there a different way to use transforms when there are datetimes in play? Or is it a bug? Thanks!

**Matplotlib version**

  * Operating system: Ubuntu 20.04
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.7
  * Jupyter version (if applicable): Jupyter Lab 2.1.4
  * Other libraries:

**Comment by jklymak** [comment]
Apparently `text.get_position` returns the un-converted x and y, but the transforms work after units have been converted to floats.  Use `mdates.date2num` on the first element of the position.  

I think a todo could be to make that clear in the docstring.  Oddly the relevant information is included as a comment:

```python
    def get_position(self):
        """Return the (x, y) position of the text."""
        # This should return the same data (possible unitized) as was
        # specified with 'set_x' and 'set_y'.
        return self._x, self._y
```

**Comment by Phlya** [comment]
Thanks a lot, calling `mdates.date2num` on the time coordinate when calling `plt.text` solves the issue.

Perhaps this can go inside `adjust_text` in a try-except clause then...

**Comment by jklymak** [comment]
You can/should(?) call `ax.convert_xunits`?

**Comment by Phlya** [comment]
Woah next level of magic, thank you!

**Comment by Phlya** [comment]
Ah, but this one way or another has to be done before calling `plt.text`?

**Comment by jklymak** [comment]
ax.text calls convert_xunits (or something similar) before it knows where to draw things, but it stores unitized data in txt._x and txt._y so it can redo the conversion if the units change somehow.   So, you really should add units back if you call txt.set_x.

**Comment by Phlya** [comment]
Sorry, now I am more confused. I don't call txt.set_x anywhere... Is that part of calling a transform?

I think I don't fully understand either the transforms, or the units, and in combination I don't get it in general.

**Comment by jklymak** [comment]
Maybe I need a more complete example - I thought you were moving the text to a new position.

**Comment by Phlya** [comment]
In general that's the final idea, in adjustText - but in this example I am not doing anything like that explicitly...

**Comment by jklymak** [comment]
OK, but I don't see why this has to be done before `plt.text`.

**Comment by Phlya** [comment]
Because, as I understood it, text objects need to be created using the unit-converted values... I.e. either 
```python
for x, y, l in zip(dates, levels, names):
    texts.append(ax.text(mdates.date2num(x), y, l))
```
or (I guess more general applicable to any unit type)
```python
for x, y, l in zip(ax.convert_xunits(dates), levels, names):
    texts.append(ax.text(x, y, l))
```
Did I misunderstand something?

**Comment by jklymak** [comment]
No, you don't need to do that.  Presumably you don't want your users to have to do that. 

You need to do the conversion at the `texts[0].get_transform().transform(texts[0].get_position())` step.

**Comment by Phlya** [comment]
Right, I see what you mean now! Perfect, that works, thank you so much.
