### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.artist'

### ISSUE THREAD

**Issue by kapilbhise** [matplotlib/matplotlib#19414]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by kapilbhise** [comment]
what should i do?

**Comment by jklymak** [comment]
You should check your install and follow up on discourse.matplotlib.org.  Thanks

**Comment by kapilbhise** [comment]
Upgraded the library using pip install --upgrade matplotlib  and issue got resolved.
