### ISSUE TITLE
Fix mistake in documentation

### ISSUE THREAD

**Issue by alessandro-giusti** [matplotlib/matplotlib#19427]
It looks like that [here](https://github.com/matplotlib/matplotlib/blob/a5ea869114fd67ee4db17b22e77a1e495f45336f/examples/statistics/boxplot.py#L63), specifying `linestyle='none'` has no effect. If the goal was to remove the marker edges, it should be substituted with `markeredgecolor='none'`.

**Comment by QuLogic** [comment]
Fixed by #19589.
