### ISSUE TITLE
Ylim with Bar Chart

### ISSUE THREAD

**Issue by berkdemir** [matplotlib/matplotlib#19428]
I think the bar chart's ylim does not behave as expected. 
Based on the demo presented [here ](https://matplotlib.org/2.0.2/examples/api/barchart_demo.html), I have added plt.ylim(top=30) and bars extended outside. 

Expected behaviour is that bars will be cut-off at the top of the figure.

![image](https://user-images.githubusercontent.com/40423004/106587425-a8e56500-655a-11eb-98b1-c505bddcc5d6.png)
![image](https://user-images.githubusercontent.com/40423004/106587443-adaa1900-655a-11eb-9120-263b3bb1d88d.png)

```python
import numpy as np
import matplotlib.pyplot as plt

N = 5
men_means = (20, 35, 30, 35, 27)
men_std = (2, 3, 4, 1, 2)

ind = np.arange(N)  # the x locations for the groups
width = 0.35       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(ind, men_means, width, color='r', yerr=men_std)

women_means = (25, 32, 34, 20, 25)
women_std = (3, 5, 2, 3, 3)
rects2 = ax.bar(ind + width, women_means, width, color='y', yerr=women_std)

ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.set_xticks(ind + width / 2)
ax.set_xticklabels(('G1', 'G2', 'G3', 'G4', 'G5'))

plt.ylim(top=30) # THIS IS THE PART I HAVE ADDED

ax.legend((rects1[0], rects2[0]), ('Men', 'Women'))


def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()/2., 1.05*height,
                '%d' % int(height),
                ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)

plt.show()
```

**Comment by QuLogic** [comment]
What version of Matplotlib?

The bars do not extend outside for me.

**Comment by berkdemir** [comment]
> What version of Matplotlib?
> 
> The bars do not extend outside for me.

3.3.2 with Spyder.
I have tried on Google Colab ith 3.2.2.
![image](https://user-images.githubusercontent.com/40423004/106739726-81f66400-662a-11eb-983f-9360f733e6b8.png)

**Comment by oscargus** [comment]
Texts are not clipped by default (which have resulted in a number of issues, but also avoided a number of issues). In your case, you explicitly add texts and therefore would need to set `clip_on=True` when creating the text.

Why the bars draws outside is not clear. Which backend was it that gave that problem? (Most likely it is a backend issue.)

**Comment by jklymak** [comment]
I'll close for lack of response
