### ISSUE TITLE
Switch to pydata-sphinx-theme

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#19423]
### Current status:

- We vendor our own sphinx theme that is based on an ancient verson of the alabaster theme. which has been heavily modified over time. The theme is a bit hard to maintain, and things can fall apart if sphinx does some changes (indeed we recently had a broken search #19279).
- The current layout is not responsive.
- Parts of the current layout look dated (which is subjective of course).

### Proposal:
Reuse https://github.com/pydata/pydata-sphinx-theme, which has been adopted by some major numfocus projects.

I anticipate less maintainance effort on our side, because the theme is shared between multiple major projects.

I like the idea that major numfocus projects have similar but still distinct designs. One should recognize that numpy and matplotlib are related, but I still want to immediately see if I'm on numpy, pandas or matplotlib docs.
This needs som customization in terms of fonts, color, etc., Ideally make these things configurable options upstream in pydata-sphinx-theme so that we can just set it in `conf.py` and the theme does the rest.

This will also need some disentangling of the current `mpl.css` for keeping parts we still need in a same or similar form (e.g. gallery layout, version box, ...).

**Comment by jklymak** [comment]
If its responsive, then :+1: :+1: :+1:   I do prefer our color scheme to the numpy one, which seems a bit bare-bones.  But I won't complain...

**Comment by story645** [comment]
I like what the bokeh site is doing & think that might be a good inspiration for incorporating mpl.colors. https://docs.bokeh.org/en/dev/

I'm definitely +1 on something phone friendly

**Comment by rajpratyush** [comment]
@timhoffm I want to work on this issue. I would like to sort the disentangling of current mpl.css while someone else can do the customization of conf.py in collaboration or if you guide me I can even do it

**Comment by jklymak** [comment]
I would guess they have to be done together?   Eat bet is to just give it a try and see what breaks.  I wouldn't spend a lot of time polishing it until there is consensus that it's a good idea.  So even if it is 75% good that would really help us know what's involved.

**Comment by rajpratyush** [comment]
I can do it but I would need some guidance on it @jklymak

**Comment by jklymak** [comment]
Follow the instructions, build the website and see what it looks like?  Beyond that, I'd have to figure it out just like you would.

**Comment by rajpratyush** [comment]
sureee

**Comment by rajpratyush** [comment]
@jklymak well I edited the conf.py how to view the website ?

**Comment by jklymak** [comment]
Suggest you build the docs: https://matplotlib.org/devdocs/devel/documenting_mpl.html  https://www.sphinx-doc.org/

**Comment by tacaswell** [comment]
I have started to take a pass at this, will try to push what I have gotten done later tonight.  It breaks a lot of things :)

**Comment by tacaswell** [comment]
#19731 @rajpratyush Can you get the branch in that PR to build locally?

**Comment by rajpratyush** [comment]
@tacaswell I have got the dependencies and set up the dev environment but i don't have a latex system yet.

no I don't have access to the branch locally
