### ISSUE TITLE
ConciseDateFormatter is not timezone aware

### ISSUE THREAD

**Issue by cosama** [matplotlib/matplotlib#19420]
### Bug report

**Bug summary**

I was working with `datetime` objects and wanted to plot them and was very excited about finding the `ConciseDateFormatter` as it seems to produce exactly what I wanted. My data spans multiple days and upon closer inspection I realized that the ticks seemed to not coincide with the start of the days in my data. I started to look into this and found out that the problem was, that my `datetime` objects had timezone information attached to them, however the formatter put the ticks at utc start of day. This can be very confusing.

The `ConciseDateFormatter` already has a timezone keyword, but in my example I am not sure what it is doing. I am not sure what the best way to resolve this would be but maybe an additional keyword, that allows to define a timezone the ticks will be related to might help, or simply use the timezone of the actual data (for example the first element).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np
import datetime, pytz
import matplotlib.dates as mdates

import matplotlib
print(matplotlib.__version__, matplotlib.get_backend())

dt = datetime.timedelta(hours=1)
t_utc = [datetime.datetime(2021, 1, 1, 0, 0, 0)]
t_pac = [datetime.datetime(2021, 1, 1, 0, 0, 0, tzinfo=pytz.timezone("US/Pacific"))]
for i in range(24*3):
    t_utc.append(t_utc[-1] + dt)
    t_pac.append(t_pac[-1] + dt)

data = np.repeat(np.arange(0, 3), 24)

date_locator = mdates.AutoDateLocator(minticks=3, maxticks=4)
date_formatter = mdates.ConciseDateFormatter(date_locator, tz=pytz.timezone("US/Pacific"))
plt.figure()
plt.gca().xaxis.set_major_locator(date_locator)
plt.gca().xaxis.set_major_formatter(date_formatter)
plt.plot(t_utc[:-1], data, ".", label='utc')
plt.plot(t_pac[:-1], data + 0.5, ".", label="pacific")
plt.grid()
plt.legend()
plt.savefig("utc_vs_pac.png")
```

**Actual outcome**

![utc_vs_pac](https://user-images.githubusercontent.com/7439971/106514142-bf22f080-6488-11eb-9657-f69db2adf2f1.png)

**Expected outcome**

I would assume that the ticks should coincide with the timezone, i.e. they are placed at the start of day in that timezone, not utc.

**Matplotlib version**
  * Operating system: Fedora 31
  * Matplotlib version : 3.3.4 
  * Matplotlib backend:  Qt5Agg
  * Python version: Python 3.7.9

**Comment by jklymak** [comment]
Timezones are indeed confusing, but the ticks are positioned by the Locator, so you need to tell it to change timezone as well:

```
date_locator = mdates.AutoDateLocator(minticks=3, maxticks=4, tz=pytz.timezone("US/Pacific"))
```

I'm going to close because I think this is working as expected, but feel free to continue discussion here if its not clear and we can always re-open.

**Comment by cosama** [comment]
@jklymak Thank you so much, that is exactly what I was looking for. Would you guys be willing to add a merge request if I add my `code reproduction` with a discussion of that to https://github.com/matplotlib/matplotlib/blob/master/examples/ticks_and_spines/date_concise_formatter.py?

**Comment by cosama** [comment]
Actually don't understand why the formatter has a `tz` field to start with. At least in the example I imagined it only leads to some weird result of moving stuff back a day (that looks like a bug), but doesn't treat the input data any different:

```
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np
import datetime, pytz
import matplotlib.dates as mdates

import matplotlib
print(matplotlib.__version__, matplotlib.get_backend())

dt = datetime.timedelta(hours=1)
t_utc = [datetime.datetime(2021, 1, 1, 0, 0, 0)]
t_pac = [datetime.datetime(2021, 1, 1, 0, 0, 0, tzinfo=pytz.timezone("US/Pacific"))]
for i in range(24*3):
    t_utc.append(t_utc[-1] + dt)
    t_pac.append(t_pac[-1] + dt)

data = np.repeat(np.arange(0, 3), 24)
# for i in zip(t_utc[:-1], t_pac, data):
#     print(i)

locators = {
    "utc": mdates.AutoDateLocator(minticks=3, maxticks=4),
    "pac": mdates.AutoDateLocator(minticks=3, maxticks=4, tz=pytz.timezone("US/Pacific"))
}
formatters = {
    "utc": lambda x : mdates.ConciseDateFormatter(x),
    "pac": lambda x : mdates.ConciseDateFormatter(x, tz=pytz.timezone("US/Pacific"))
}
fig, ax = plt.subplots(4, figsize=(7, 7))

i = 0
for lc in locators.keys():
    for fr in formatters.keys():
        ax[i].set_title(f"Locator '{lc}' Formatter '{fr}'")
        ax[i].xaxis.set_major_locator(locators[lc])
        ax[i].xaxis.set_major_formatter(formatters[fr](locators[lc]))
        ax[i].plot(t_utc[:-1], data, ".", label='utc')
        ax[i].plot(t_pac[:-1], data + 0.5, ".", label="pacific")
        ax[i].grid()
        ax[i].legend()
        i += 1
plt.tight_layout()
plt.savefig("utc_vs_pac.png")
```
![utc_vs_pac](https://user-images.githubusercontent.com/7439971/106531475-2c437f80-64a3-11eb-9c95-39cd3e9cc13a.png)

**Comment by jklymak** [comment]
Zoom in so you can see hours, and you will see that the label change.  Or use the longer formatter.  The tick is no longer at midnight because your locator is in a different time zone than your formatter.  You could argue that they should be coupled, and I wouldn't argue, but that is not how they are architected, and we can't really change it.
