### ISSUE TITLE
Tricontour documentation and examples should be updated in line with contour

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#19431]
Some contour/contourf keyword arguments (hatches, linewidths, linestyles) also work with tricontour/tricontourf but they are not documented and there are no examples of their use.

**Comment by raman-thakur** [comment]
@ianthomas23 I would like to work on that can I??

**Comment by jklymak** [comment]
@raman-thakur if there are no linked PRs feel free to get started.  Please consult https://matplotlib.org/stable/devel/index.html and ask if you have any questions.

**Comment by raman-thakur** [comment]
well before that can I have a short and brief google meet or zoom call so as to better discuss the layout of matplotlib's docs page?

**Comment by jklymak** [comment]
There are extensive written instructions here: https://matplotlib.org/stable/devel/documenting_mpl.html  Short clarifications are welcome at https://gitter.im/matplotlib/matplotlib or longer ones at https://discourse.matplotlib.org.    While we try to be welcoming to new contributors, a zoom call is probably beyond what the (volunteer) dev team has the bandwidth for.

**Comment by vaibhavarora102** [comment]
@jklymak  
sir, can I contribute to this issue as:
1.) new to this project
2.)done with all the steps mentioned here https://matplotlib.org/stable/devel/contributing.html   

Waiting for your positive response

**Comment by ianthomas23** [comment]
@vaibhavarora102 You don't really need to ask permission to contribute.  If you would like to write a PR then please go ahead.

It might be sensible to check if @raman-thakur is working on it first, to avoid duplication of effort.

**Comment by AkM-2018** [comment]
**tricontour(\*args, \*\*kwargs)** does not include documentation for- **antialiased, nchunk, corner_mask, vmin, vmax**
**tricontourf(\*args, \*\*kwargs)** does not include documentation for- **hatches, nchunk, corner_mask, vmin, vmax**

I should add the missing ones in **tricontour.py**, correct?

**Comment by ianthomas23** [comment]
Documentation is fixed by PRs #20135 and #20171.  Hatching example still needs to be done.

**Comment by QuLogic** [comment]
Hatching example is done by #20574.
