### ISSUE TITLE
legend doesn't work with stackplot

### ISSUE THREAD

**Issue by thegrinner** [matplotlib/matplotlib#1943]
I've been trying to add a legend to a stackplot and been having a great deal of trouble. I've tried several approachs: `legend()`, `legend(labels=[blah]`, `legend([blah])`, and even proxy artists. The proxy artists are the only approach that works - the first two don't even show a legend box, and the third shows an empty legend.

The first case does output a warning about missing labels, but there's no documentation for how to resolve the issue.

It appears root cause is there are no handles or labels for the stackplot (`ax.get_legend_handles_labels()` returns two empty lists).

Best case this would be fixed, but there should at least be a documentation update outlining the fact that the stackplot needs proxy artists.

Here's a working example (uses the stackplot example code):
```
import numpy as np
from matplotlib import pyplot as plt

fnx = lambda : np.random.randint(5, 50, 10)
y = np.row_stack((fnx(), fnx(), fnx()))
x = np.arange(10)

y1, y2, y3 = fnx(), fnx(), fnx()

# Test with just legend()
print("legend() test")
fig = plt.figure()
ax = fig.add_subplot(111)
ax.stackplot(x, y)
# Note handles and labels are both empty lists
handles, labels = ax.get_legend_handles_labels()
print(handles,labels)
ax.legend()
plt.show()

# Test passing in some labels by hand
print("legend(['1','2','3']) test")
fig = plt.figure()
ax = fig.add_subplot(111)
ax.stackplot(x, y)
ax.legend(['1','2','3'])
plt.show()

# Test using proxy legend
print("proxy test")
fig = plt.figure()
ax = fig.add_subplot(111)
ax.stackplot(x, y1, y2, y3)

# This provides a proxy artist, with an arbitrary color of red
p = plt.Rectangle((0, 0), 1, 1, fc="r")
ax.legend([p], ['test'])

plt.show()
```

This outputs
```
legend() test
[] []
C:\Python33\lib\site-packages\matplotlib\axes.py:4603: UserWarning: No labeled o
bjects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labeled objects found. "
legend(['1','2','3']) test
proxy test
```

More details:
Windows XP SP3 (32 bit)
matplotlib 1.2.1
Python 3.3
Obtained from downloads page on website
No customizations to matplotlibrc

**Comment by ax3l** [comment]
@thegrinner @goxberry @dmcdougall fixed in `1.5` (tested with `1.5.1`) via #3303

thanks a lot!
