### ISSUE TITLE
fill_between,  step='post' and NaN

### ISSUE THREAD

**Issue by mankoff** [matplotlib/matplotlib#19444]
Off-by-one error if using `fill_between`, `step='post'`

```python
import matplotlib.pyplot as plt
import pandas as pd

fig = plt.figure(1)
ax = fig.add_subplot(111)

df = pd.DataFrame(index=pd.date_range(start='2000-01-01', periods=10, freq='1D'))
df['data'] = [1,2,3,-4,-5,-6,7,8,9,-10]

df.plot(ax=ax, drawstyle='steps-post')
ax.fill_between(df[df > 0].index, df[df > 0].values.flatten(), step='post')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/145117/106748570-46cc4480-65da-11eb-8e38-83e2d4e02fc2.png)

**Expected outcome**

Some of the `df[df > 0]` columns are not filled.

**Matplotlib version**

  * Operating system:  Linux Kubuntu 20.04
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.5
  * Jupyter version (if applicable): IPython 7.17.0

**Comment by jklymak** [comment]
If possible can you simplify this to Matplotlib with no dates, no pandas, and maybe the latest release?  I think fill-between may have had some work recently.   Thanks!

**Comment by jklymak** [comment]
For instance if I do:

```python 
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(1)
ax = fig.add_subplot(111)
x = np.arange(30)
np.random.seed(1)
y = np.cumsum(np.random.randn(30))
y = y - np.mean(y)
ax.plot(x, y, drawstyle='steps-post')
yy = y
yy[y<0] = 0
ax.fill_between(x, yy, step='post')
plt.show()
```

I get what I think you are trying to do, so I'm guessing this is actually to do with how you are using pandas (but I could certainly be wrong):

![TestFill](https://user-images.githubusercontent.com/1562854/106772791-35dcfc80-65f5-11eb-929c-a558799e529f.png)

**Comment by mankoff** [comment]
Yes this works with the extra code you've provided: `yy = y; yy[y<0] = 0`.

Thanks for the push to simplify the bug. It is an NaN bug, and I think this should work with NaNs, although replacing NaNs with 0 is not a big burden.

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

fig = plt.figure(1)
ax = fig.add_subplot(111)

x = np.arange(1,11)
y = np.array([1,2,3,-4,-5,-6,7,8,9,-10])
yn = np.where(y > 0, y, np.nan)

ax.plot(x, y, drawstyle='steps-post')
ax.fill_between(x, yn, step='post')
plt.show()
```

The above code generates the first graphic: https://user-images.githubusercontent.com/145117/106748570-46cc4480-65da-11eb-8e38-83e2d4e02fc2.png

**Comment by mankoff** [comment]
See related: #15065 and https://github.com/matplotlib/matplotlib/issues/16635
