### ISSUE TITLE
Bug in Rendering Navigation Toolbar in tkinter on MacOS [MPL 3.3.4]

### ISSUE THREAD

**Issue by DaveL17** [matplotlib/matplotlib#19443]
### Bug report

Rendering of the navigation toolbar within a tkinter gui exhibits considerable flickering. This is especially pronounced when the x/y coordinates are tracked.

**Code for reproduction**

```python
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import matplotlib
matplotlib.use('TkAgg')
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, NavigationToolbar2Tk)
from matplotlib.figure import Figure
import tkinter as tk
from tkinter import ttk


class Application(tk.Frame):

    def __init__(self, master=None):

        tk.Frame.__init__(self, master)
        self.data_set = []
        self.init_ui()
        self.widget = None

    def init_ui(self):
        self.grid(row=0, column=0)

        # Draw a blank plot as a part of setting up the UI.
        plt = Figure(figsize=(6, 4), dpi=100)
        ax = plt.add_subplot(111)
        ax.plot(0, 0)

        # Add plot to window
        canvas = FigureCanvasTkAgg(plt, master=self)
        self.widget = canvas.get_tk_widget()
        self.widget.grid(row=1, column=0, columnspan=3)

        # Add toolbar to window
        toolbar_frame = tk.Frame(master=root)
        toolbar_frame.grid(row=1, column=0)
        toolbar = NavigationToolbar2Tk(canvas, toolbar_frame)
        toolbar.pack(side=tk.TOP, fill=tk.BOTH, expand=1)

# =====================================================================
root = tk.Tk()

app = Application(master=root)
app.mainloop()
```

**Matplotlib version**

  * Operating system: Mac OS 10.15.7
  * Matplotlib version: 3.3.4
  * Matplotlib backend: tkagg, tkcairo, macosx all display the issue.
  * Python version: 3.8.6
  * Other libraries: tkinter

* Matplotlib was installed within a virtual environment using pip.
* Note that when the code is adjusted to run under Matplotlib 1.3.1 under Python 2.7, the toolbar renders perfectly.
* When the toolbar is rendered with a `.show()` call, it does not flicker.
* Calling `init_ui()` from within or outside the Application class doesn't make a difference.
* Packing or gridding the toolbar doesn't seem to make a difference.

**Comment by QuLogic** [comment]
@DaveL17 / @greglucas do you think this is still a problem in a current release?

**Comment by DaveL17** [comment]
@QuLogic / @greglucas - I ran the above code and didn't see the flickering; however, my environment has changed somewhat since reporting the issue:

- Operating system: Mac OS 13.6 (was 10.15.7)
- Matplotlib version: 3.5.1 (was 3.3.4)
- Python version: 3.10 (was 3.8.6)

I'm going to go ahead and close this issue as it no longer appears to occur.  Cheers.

**Comment by greglucas** [comment]
I am not sure what the exact issue was because I'm not able to reproduce the flickering on main or on v3.3.4. The text does move the toolbar boxes around based on text-width with different numbers which perhaps looks like flickering. I think it is fine to close it.
