### ISSUE TITLE
axline transform support broke axline in loglog scale

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19445]
### Bug report

**Bug summary**

https://github.com/matplotlib/matplotlib/pull/18647 broke loglog scale axlines.

**Code for reproduction**

```python
loglog([.3, .6], [.3, .6], ".-"); axline((1, 1e-3), (10, 1e-2), c="k")
```

**Actual outcome**

![new](https://user-images.githubusercontent.com/1322974/106779717-8f6e1700-6647-11eb-9234-caddf2f69a13.png)
one can zoom out a bit and get
![zoomedout](https://user-images.githubusercontent.com/1322974/106779737-95fc8e80-6647-11eb-98d6-5c13916a6b41.png)

**Expected outcome**

What we had before #18647:
![old](https://user-images.githubusercontent.com/1322974/106779792-a0b72380-6647-11eb-9791-02c68dac9e1c.png)

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): head
  * Matplotlib backend (`print(matplotlib.get_backend())`): mplcairo
  * Python version: 39

Release critical, as it's a regression in 3.4 against 3.3.

**Comment by anntzer** [comment]
@johan12345 Any chance you can have a look at this?

**Comment by johan12345** [comment]
Hi! Sorry for this. I can reproduce the issue and think I have found a fix. Will send a PR :)
