### ISSUE TITLE
Restrict input dataset by limit values

### ISSUE THREAD

**Issue by fwillo** [matplotlib/matplotlib#19453]
### Bug report

**Bug summary**
I ran into an unusual problem when using the vector output of matplotlib (here PDFs) and upload it to a journal website (or import them in Mathematica, which I found out luckily in order to reproduce the problem locally). A problem, which primarily can be located in the importing programs, probably reveals another in matplotlib .

The whole input data is used when plotting, although limitations like `xlim` or `ylim` are set. Programs, that import figures not correctly, tend to degroup all elements in PDFs and suddenly the whole data set is in front of the figures facecolor.

My expectation would be that the figure limitations also result in limitation of the input data set for various reasons (e.g. optimizations, only drawing presented data points)

**Code for reproduction**
```python
from matplotlib import pyplot as plt
import numpy as np

fig = plt.figure(num=1, figsize=(10,8))
ax  = plt.subplot(111, polar=True)

r   = np.linspace(0, 3,       num=1000)
phi = np.linspace(0, 2*np.pi, num=1000)

rlim = 1

z = np.zeros((1000,1000))
for i in range(1000):
    for j in range(1000):
        z[i, j] = np.exp(-r[i]**2)

# Fix
# z = z[r <= rlim,:]
# r = r[r <= rlim]

ax.contourf(phi, r, z, cmap=plt.get_cmap("coolwarm"))

ax.set_xlim([0, 2*np.pi])
ax.set_ylim([0, rlim])

fig.savefig('output.pdf', quality=100, dpi=600)
```

And in Mathematica (for reproduction)
```mathematica
Import["output.pdf"]
```

**Actual outcome**
Please see the generated output in the list below. Files with cart are made with `polar=False`, files with mathematica in it are the results respectively imported in Mathematica.

- [output.pdf](https://github.com/matplotlib/matplotlib/files/5926699/output.pdf)
- [output-cart.pdf](https://github.com/matplotlib/matplotlib/files/5926700/output-cart.pdf)
- [output-cart-mathematica.pdf](https://github.com/matplotlib/matplotlib/files/5926701/output-cart-mathematica.pdf)
- [output-mathematica.pdf](https://github.com/matplotlib/matplotlib/files/5926702/output-mathematica.pdf)

**Expected outcome**
The files with mathematica in the filename should be the same as files without it.

**Matplotlib version**

  * Operating system: Windows 10 64-bit 1909
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.9
  * Jupyter version (if applicable): -
  * Other libraries: numpy (1.19.3)

I installed matplotlib via the Windows Setup File of Spyder. Mathematica is in the version 12.0.0 (64-bit).

**Comment by anntzer** [comment]
My personal view is that Matplotlib cannot be expected to implement a vector clipping algorithm to work around the fact that Mathematica is not implementing one correctly despite it being present in the pdf spec (IOW, this is a bug in Mathematica, not in Matplotlib).

**Comment by fwillo** [comment]
I agree with you, as already mentioned in my post. Primarily the problem resides in the used programs (which is not Mathmematica solely, I experienced it on various journal websites). However, my point being is that drawing elements not visible in the endproduct might be an overkill and would solve such issues as well.

**Comment by jklymak** [comment]
The problem isn't elements that are "not visible" its elements that are partially clipped.  In your example output-cart, the light blue contour get from 0.9 to 1.1, and spans the limit of y=1.0 - we would have to detect that the polygon is partly out of the axes, remove the polygon and make a new one that only goes to 1.0.  Given that a clip box is a language feature shared with svg and eps, and one that Matplotlib was designed around, I think there is very little chance anyone is going to implement an object clip layer at the matplotlib level to reshape objects to clip them. 

OTOH, I believe if you post-process with ghostscript, it will clean up the file and do the clipping for you:

https://stackoverflow.com/questions/21706976/ghostscript-removes-content-outside-the-crop-box

**Comment by fwillo** [comment]
I see. Recalculate already drawn polygons sound messy. But what objects preprocessing the input data to the set limits? E.g. as my commented lines in the minimal example?

**Comment by jklymak** [comment]
That won't help if the objects still need to be clipped (i.e. a large marker, or polygon).
