### ISSUE TITLE
sphinxsidebar text overflow

### ISSUE THREAD

**Issue by aitikgupta** [matplotlib/matplotlib#19450]
### Describe the issue

**Summary**
The `sphinxsidebar` in some pages lets the text overflow, ref:
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.tight_layout.html
![image](https://user-images.githubusercontent.com/43996118/106022875-4ae4f780-60ec-11eb-9a81-51e06535bede.png)

### Proposed fix
> @brunobeltran: adding overflow_wrap to the appropriate element in the custom mpl css (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)
if we increase sidebar width, I assume it would have to be responsive, and that's a pretty big rabbit-hole to go down. on the other hand specifying overflow-wrap would probably be an immediate improvement (and we would probably want it to be set regardless of if we eventually increase the width)

/cc @timhoffm 

(issue moved from https://github.com/matplotlib/matplotlib.github.com/issues/52 to here)

**Comment by timhoffm** [comment]
The "Related Topics" section is gone in recent docs, so there is at least less that can overflow :smile:.
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.tight_layout.html

I'm undecided which one is better: Wrapping makes it a bit harder to read, but has a better visual apearance.:

![grafik](https://user-images.githubusercontent.com/2836374/106959749-6464ef80-673b-11eb-921d-bb64ccf2c634.png)

![grafik](https://user-images.githubusercontent.com/2836374/106959802-75156580-673b-11eb-9371-8c5b0a01c1d0.png)

I'm ok if anybody puts in a PR on this.

**Comment by jklymak** [comment]
Can we not drop the prefixes?

**Comment by timhoffm** [comment]
> Can we not drop the prefixes?

Likely not easily. The heading is generated by as part of the minigallery of sphinx-gallery, and from a quick look it could only be changed manually, but not in a template. If anybody wants to dig into this:

- [Minigallery docs](https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation)
- [autosummary.rst](https://github.com/matplotlib/matplotlib/blob/master/doc/_templates/autosummary.rst) defines the `.. minigallery::` directive which would have to be adapted.

**Comment by rajpratyush** [comment]
@timhoffm I would like to put a PR on this just let me know what are files associated with this? 

and would you rather prefer text to be wrapped or or just reduce the font size so as to fit the test into the required space

**Comment by timhoffm** [comment]
All CSS is int https://github.com/matplotlib/matplotlib/blob/master/doc/_static/mpl.css.

Text should be wrapped as it should only happen in some more rare cases and we should not change the font size to keep a consistent layout.

**Comment by jklymak** [comment]
I think this is obviated by pydata sphinx style.
