### ISSUE TITLE
Epoch issue with version 3.3.4

### ISSUE THREAD

**Issue by adybbroe** [matplotlib/matplotlib#19451]
### Bug report

**Bug summary**

Using `plot_date` on the axis the year/epoch labels gets screwed up. I see there has been similar issues in the past and also with Pandas, but the below code is confined to matplotlib.

Same code works in older version, see below.

**Code for reproduction**

```
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

dtobj = datetime(2020, 7, 1)
endtime = datetime(2020, 12, 31)
delta_t = timedelta(days=1)

dtl = []
while dtobj < endtime:
    dtl.append(dtobj.toordinal())
    dtobj = dtobj + delta_t

fig = plt.figure(figsize=(9, 7))
ax = fig.add_subplot(111)
ax.plot_date(dtl, range(len(dtl)), '-')
ax.autoscale_view()
fig.autofmt_xdate()
plt.show()
```

**Actual outcome**

![mpl_epoch_issue_v334](https://user-images.githubusercontent.com/169069/106901874-82f5c700-66f8-11eb-9b21-65d1b3586b19.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Here the corresponding output with matplotlib version 3.2.2:

![mpl_epoch_issue_v322](https://user-images.githubusercontent.com/169069/106902622-53938a00-66f9-11eb-8bcf-ea52d886ba50.png)

**Matplotlib version**

Conda environment:
3.3.4-py38h578d9bd_0 (Python 3.8)

  * Operating system: Linux RHEL 8
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Sorry this broke for you, but this isn't really a bug per-se.  In the above you do not need to convert to ordinal:

```python
while dtobj < endtime:
    dtl.append(dtobj)
    dtobj = dtobj + delta_t
```
plots perfectly well.  

However, if you do need to convert to ordinal for some reason then you can do:

```python
old_epoch = '0000-12-31T00:00:00'
mdates.set_epoch(old_epoch)
```

or if you want to use the modern epoch:
```python
oldepoch = np.datetime64('0000-12-31T00:00:00')
dtl = []
while dtobj < endtime:
    dtl.append(dtobj.toordinal() + mdates.date2num(oldepoch))
    dtobj = dtobj + delta_t
```

Please see: https://matplotlib.org/stable/gallery/ticks_and_spines/date_precision_and_epochs.html

**Comment by jklymak** [comment]
I'm going to close because this is working as expected.

**Comment by adybbroe** [comment]
Ok, great, many thanks for the explanation and help!
I believe the `toordinal()` was needed in older versions? I have a faint memory that I spend some time getting this to work some years back. Could that be so?

**Comment by jklymak** [comment]
Maybe a long time ago you had to do that.  Or if you were not using timedelta but rather floats?  If you want to stay consistent to matplotlib you can still use date2num which will use the current epoch.
