### ISSUE TITLE
[bug] segmentation fault when try to savefig a pdf with Chinese font

### ISSUE THREAD

**Issue by Freed-Wu** [matplotlib/matplotlib#19469]
## Environment

- linux 5.4.13
- python 3.9.0b3
- ipython 7.19.0
- matplotlib 3.3.3
- texlive 2019-r1 (maybe useful)
- qt 5.15.0 (maybe useful)
- jupter 1.0.0-r2 (but i use ipython in terminal not jupyter)

## Reproduce Procedures

```ipython
%matplotlib qt
import matplotlib.pyplot as plt
fig,ax=plt.subplots(1,1)
ax.set_xlabel('测试',fontdict={'family': 'WenQuanYi Micro Hei'})
plt.savefig('a.pdf')
```

```shell
[1]    50554 segmentation fault (core dumped)  ipython
```

## Note

WenQuanYi Micro Hei is a open source chinese font and can be installed by
`sudo emerge -av media-fonts/wqy-microhei` in my distribution. replacing it
with any Chinese font will result in the same bug. if replace it with any
non-Chinese font will not output Chinese character and avoid the bug.

if the picture format is png, the bug will not occur, and the file `a.png`
will be normal.

**Comment by anntzer** [comment]
Thanks for the report.
I believe this is fixed by https://github.com/matplotlib/matplotlib/pull/18181 in the soon-to-be-released Matplotlib 3.4.  Feel free to request a reopen if that issue persists after that patch.
