### ISSUE TITLE
Error with datetime axis on fill_between

### ISSUE THREAD

**Issue by Rblivingstone** [matplotlib/matplotlib#19465]
I get the following error using fill_between():

`ValueError: view limit minimum -8.824463999922536e+16 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units
`
Here's the code that I am using:

```
ax.plot(df1['dt'],df1['fcast'],label='forecast',color='k',ls='--')
ax.fill_between(x=df1['dt'],y1=fcast[2][:,0],y2=fcast[2][:,1],alpha=0.1)
plt.show()
```

But this code runs just fine, which leads me to believe that the issue is with fill_between.

```
ax.plot(df1['dt'],df1['fcast'],label='forecast',color='k',ls='--')
ax.plot(df1['dt'],fcast[2][:,0],color='r')
ax.plot(df1['dt'],fcast[2][:,1],color='r')
plt.show()
```

**Comment by jklymak** [comment]
Can you  supply us with stand-alone example that we can run, preferably w/o pandas?

**Comment by Rblivingstone** [comment]
Interesting, seems to be something funny with pandas. This breaks:

```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dt = np.array(['2020-12-07T00:00:00.000000000', '2020-12-08T00:00:00.000000000',
       '2020-12-09T00:00:00.000000000']).astype('datetime64[ns]')
fcast = [810.61,822.34,799.65]
lower = [593.66884765, 604.64722788, 579.790854]
upper = [1027.56754569, 1040.03925445, 1019.51604813]
df = pd.DataFrame()
df['dt']=dt
df['fcast'] = fcast
df['lower'] = lower
df['upper'] = upper

fig, ax = plt.subplots()
ax.plot(df['dt'],df['fcast'])
ax.fill_between(df['dt'],df['lower'],df['upper'])
plt.show()
```
But this one doesn't:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dt = np.array(['2020-12-07T00:00:00.000000000', '2020-12-08T00:00:00.000000000',
       '2020-12-09T00:00:00.000000000']).astype('datetime64[ns]')
fcast = [810.61,822.34,799.65]
lower = [593.66884765, 604.64722788, 579.790854]
upper = [1027.56754569, 1040.03925445, 1019.51604813]
df = pd.DataFrame()
df['dt']=dt
df['fcast'] = fcast
df['lower'] = lower
df['upper'] = upper

fig, ax = plt.subplots()
ax.plot(dt,fcast)
ax.fill_between(dt,lower,upper)
plt.show()

**Comment by jklymak** [comment]
Make sure you are using recent matplotlib and pandas....

**Comment by dstansby** [comment]
What versions of matplotlib and pandas are you using? I can get both your examples working on the latest version of matplotlib and pandas.

**Comment by jklymak** [comment]
Lets go ahead and close for lack of response....  We can always reopen.
