### ISSUE TITLE
Quiver docs don't have a return section

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#19464]
### Problem
The doc(string) for `ax.quiver` doesn't include a `Returns` section that shows that it returns a `matplotlib.quiver.Quiver` 
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.quiver.html

This makes it tricky to click through from that page to see the methods of this object.

This is because the axes quiver method takes a straight copy of the quiver init docstring.

https://github.com/matplotlib/matplotlib/blob/4da4cf9da681d1ddfd17cb60e78588e2c55a1e23/lib/matplotlib/axes/_axes.py#L5099

### Suggested Improvement
add a `Returns` section.

**Comment by aryanxk02** [comment]
Hey there @ianhi I am new to open source contribution. I want to solve this issue. Would be helpful if you guide me through this. THAN YOU!

**Comment by jklymak** [comment]
@aryanxk02 Guidance for how to contribute is at: https://matplotlib.org/stable/devel/index.html  If you have a solution to the above, you post a pull request.

**Comment by K-Monty** [comment]
Hi, I am also new to open source contribution. I have made a first-attempt on this issue: https://github.com/matplotlib/matplotlib/pull/19562#issue-578292384, but it doesn't seem to work. Any guidance(s) are welcomed!

**Comment by QuLogic** [comment]
Closed by #19566.
