### ISSUE TITLE
2 Different mappings for same formula

### ISSUE THREAD

**Issue by Eftakhari** [matplotlib/matplotlib#19470]
### Bug report

**Bug summary**

I receive two different mappings (one of them is obviously wrong) for a single piece of math formula in both "pyplot" & "matplotlib.pyplot"! 

**Bug Details**
I've encountered a problem with both "pylab" and "matplotlib.pyplot".
As documented in attached photos the graph of the function i'm working with are not correct! 
The correct form of the function must follow the lead of scattered points but it's rotated 90° clockwise (Math: -90°)!
This function is one of the famous ones,AS in MATLAB output the line that connects deepest valley point to top of the hill must be "y=x" but here is "y=-x"
the scattered points are correct due to their color code, but not the "surface imaging", please see through this problem if the library functions are a little buggy.

**Code for reproduction**

```python *(jupyter notebook)

import numpy as np
from scipy import interpolate
import pylab as py

def func(x,y):
    return (x+y)*np.exp(-(x**2 + y**2))

x = np.random.uniform(-1, 1, size=50)
y = np.random.uniform(-1, 1, size=50)
fvals = func(x,y)
newfunc = interpolate.Rbf(x, y, fvals, function='multiquadric')
xnew, ynew = np.mgrid[-1:1:1000j, -1:1:1000j]
fnew = newfunc(xnew, ynew)

# Create image plot by pylab
py.figure(1)
py.clf()
py.imshow(fnew, extent=[-1,1, -1,1], cmap=py.cm.jet)
py.scatter(x,y,30,fvals,cmap=py.cm.jet)
py.show()

# Create image plot by matplotlib
import matplotlib.pyplot as mp
mp.figure(1)
mp.clf()
mp.imshow(fnew, extent=[-1,1, -1,1], cmap=mp.cm.jet)
mp.scatter(x,y,30,fvals,cmap=mp.cm.jet)
mp.show()
```

**Actual outcome**

Is Attached as: "Bug.png"
![Bug](https://user-images.githubusercontent.com/76484959/107136282-0db40d00-6917-11eb-9ac0-bd7f807c3995.png)
**Expected outcome**

Is attached as: "Correct.png"
![Correct](https://user-images.githubusercontent.com/76484959/107136322-2fad8f80-6917-11eb-8c8f-0020dd9aaa4a.png)

**Matplotlib version**

  * Operating system: MS Win-7 x64 (Ultimate)
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  Out [1]: '3.3.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`):  
  Out [2]: module://ipykernel.pylab.backend_inline
  * Python version: 
  Out [3]: '3.8.5'
  * Jupyter version (if applicable):  6.2.0
  * Other libraries: 
   numpy: '1.19.2'
   scipy: '1.5.2'

I'm working with Anaconda: "Anaconda3 2020.07 x86_64" from: "https://www.anaconda.com/" and it is updated with: "conda update --all" command in command prompt.

**Comment by jklymak** [comment]
Please see https://matplotlib.org/stable
/tutorials/intermediate/imshow_extent.html for a discussion of how to use extent in imshow.  For less ambiguity perhaps try pcolormesh.  

I'm going to close because I don't think there is a bug here.  If you have more questions please do ask at discourse.matplotlib.com
