### ISSUE TITLE
Reformatting the Files

### ISSUE THREAD

**Issue by rajpratyush** [matplotlib/matplotlib#19489]
### Describe the issue
The code in various files are not formatted properly.
**Summary**
Actually I was working on a different issue but I just ran Black which is code formatting tool on entire local repository. Only 55 files were found be having proper format. rest all needed formatting.
 A short 1-2 sentences that succinctly describe what could be improved -->
Add some tests for code formatting as well.
### Proposed fix
Reformat all the files using Black.
As Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead. so it will help other contributors to understand the code better.

**Comment by QuLogic** [comment]
We don't use black; see #18796.
