### ISSUE TITLE
Update azure ubuntu images to 18.04, or update texlive in CI

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19494]
### Describe the issue

**Summary**

The pgf/luatex tests have been flaky for a while on azure (see e.g. https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=17033).  Based on the logs
```
E               ! LuaTeX error ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-02-12.lua:11111
E               : attempt to get length of local 'lookupdata' (a number value).
E               <to be read again> 
E               \scan_stop: 
E               <*> .../work/1/s/lib/matplotlib/mpl-data/fonts/ttf/}]
```
I have traced this back to a piece of code in luaotfload that has been removed in early 2016 from luaotfload (https://github.com/latex3/luaotfload/commit/0cf41dff08cdc61119a2598cf1fa501cd15bfc54 / https://github.com/contextgarden/context-mirror/commit/788487819ccf38a8478cc2afd88e0c0b088d0ec1 are the specific commits, grep for `local function ligature` in `src/fontloader/misc/fontloader-font-otn.lua` (`fontloader-2016-02-12.lua` is a concatenated version of the lua sources)).  I don't think it's worth spending more time on a 5y old bug(?) in luatex, so perhaps we could consider either updating the azure ubuntu images to 18.04, or, if we really want to keep the 16.04 images, figure out how to use a more recent texlive in it.

**Comment by QuLogic** [comment]
16.04 should be EOL in a couple months, so we can update rather soon.
