### ISSUE TITLE
Add user defined font entry with custom name

### ISSUE THREAD

**Issue by spajak** [matplotlib/matplotlib#19508]
### Problem

In order to add a custom font with chosen alias (name) i find myself doing this:

```py
from matplotlib.font_manager import fontManager, FontEntry

fontManager.ttflist.append(FontEntry(
    fname='MyFont1.ttf',
    name='MyFont1',
    size='large',
    style='normal',
    variant='normal',
    weight='normal',
    stretch='normal'
))
```

This is the only way I can use the font 'MyFont1' by name in code (like set_title) and in rcParams.

### Proposed Solution

New function add_font_entry(entry):

```py
from matplotlib.font_manager import add_font_entry

add_font_entry(
    fname='MyFont1.ttf',
    name='MyFont1',
    size='large',
    style='normal',
    variant='normal',
    weight='normal',
    stretch='normal'
)

```

**Comment by anntzer** [comment]
There's https://matplotlib.org/stable/api/font_manager_api.html#matplotlib.font_manager.FontManager.addfont?

**Comment by spajak** [comment]
but `FontProperties` has no name as contructor parameter, so there is no way to set font alias (MyFont1)

**Comment by anntzer** [comment]
Fair point, but why is this use case so important that we'd need to add an API specifically for it (especially when you can directly manipulate the list instead)?  For example, we don't let users rename linejoins and linecaps either.

**Comment by spajak** [comment]
What if font named MyFont1 is already installed in system? System font will be prioritized

**Comment by spajak** [comment]
If you think, in this rare case, manipulating `fontManager.ttflist` directly is ok then I won't insist on changing the API

**Comment by anntzer** [comment]
> What if font named MyFont1 is already installed in system? System font will be prioritized

OK, that's a very reasonable point.  But even then, how do you make sure that the name you pick does not exist on the system already, and isn't also used by some other 3rd party library that wants to use the same trick?  I have the feeling that if you really want Matplotlib to use a specific font file, you should just set the font via its path (`font=Path("/path/to/font.ttf")` works on recent Matplotlibs) and bypass the rest of the font selection system.

**Comment by spajak** [comment]
Use `font=Path(..)` where?

Well, in CSS there is the same situation:

```css
@font-face {
    font-family: MyFont1;
    src: url(MyFont1.ttf);
}
```

Where names may collide, we use namespaces.

**Comment by anntzer** [comment]
> Use font=Path(..) where?

Whereever you would have used `family="MyFont1"`.

> Where names may collide, we use namespaces.

I don't actually know what happens in CSS if two `@font-face` both claim to implement the same font-family with different src?

Also, would it be enough if we just made sure that if multiple fonts indeed have the same font-family, then we pick the *last* one in the list?  This way user-added fonts would win.

**Comment by spajak** [comment]
> Also, would it be enough if we just made sure that if multiple fonts indeed have the same font-family, then we pick the _last_ one in the list? This way user-added fonts would win.

Yes. That would be ok.
Thanks

**Comment by aitikgupta** [comment]
There are 2 considerations here:
1. If a system-font and user-provided font have the same name. (rcParams['font.family'] = "some_font" should take the _last_ one to break ties between same names, since `addfont` method _appends_ to the end of ttf/afmlist)
2. User can't "name" a custom font (at least in the current `addfont` method), since matplotlib gets the font name from the font file instead.
