### ISSUE TITLE
How do i rotate x axis text values

### ISSUE THREAD

**Issue by bsbilal** [matplotlib/matplotlib#19512]
version 3.1.3
I have date data. But all x labels seems intertwined..
Thanks for all comments.

![image](https://user-images.githubusercontent.com/9121424/107888839-e87b5c00-6f1f-11eb-908e-23aa7d840e62.png)

`plt.bar(dfr['Tarih'],dfr['Bugünkü Vefat Sayýsý'])

plt.xlabel('tarih')

plt.ylabel('vefat')

plt.show()`

**Comment by jklymak** [comment]
There are lots of ways: https://stackoverflow.com/questions/43152502/how-can-i-rotate-xticklabels-in-matplotlib-so-that-the-spacing-between-each-xtic  Please take further discussion to discourse.matplotlib.org.  Thanks!
