### ISSUE TITLE
ImportError: cannot import name "pyplot" from "matplotlib" (unknown location)

### ISSUE THREAD

**Issue by bpinedaf** [matplotlib/matplotlib#19513]
Hi, I've been using the matplotlib library but by some reason today started to fail while trying to load pyplot.

This is the error I have now:

>>> import matplotlib
>>> from matplotlib import pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'pyplot' from 'matplotlib' (unknown location)

I've been trying several things like downgrading and uninstalling - reinstalling using conda and pip but with the same result.

Please, help me with this.

I'm running this on Anaconda in Windows 10..

**Comment by jklymak** [comment]
Wild guess would be that you have a file named `matplotlib.py` somewhere in your python path.  But this is more appropriate to discourse.matplotlib.org, so feel free to provide more diagnostic info there.
