### ISSUE TITLE
Adding text with kwarg 'font' overwrites previous kwargs

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#19527]
### Bug report

**Bug summary**

When adding text, if you use the (undocumented) kwarg `font`, it works but overwrites previous kwargs like `fontsize` and `fontstyle` with defaults.  This does not happen if you use other kwarg options like `fontname`, `name`, `fontdict['name']`, etc instead of `font`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(4.5, 5))
ax.axis('off')
name = 'DejaVu Sans Mono'

ax.text(0,  1.05, "kwarg fontsize", fontsize=20, name=name)
ax.text(0,  0.95, "kwarg fontsize", name=name, fontsize=20)

ax.text(0,  0.8,  "kwarg fontname", fontsize=20, fontname=name)
ax.text(0,  0.7,  "kwarg fontname", fontname=name, fontsize=20)

ax.text(0,  0.55, "kwarg fontdict['font']", fontsize=20, fontdict={'font': name})
ax.text(0,  0.45, "kwarg fontdict['font']", fontdict={'font': name}, fontsize=20)

ax.text(0,  0.3,  "kwarg fontdict['name']", fontsize=20, fontdict={'name': name})
ax.text(0,  0.2,  "kwarg fontdict['name']", fontdict={'name': name}, fontsize=20)

ax.text(0,  0.05, "kwarg font", fontsize=20, font=name)
ax.text(0, -0.05, "kwarg font", font=name, fontsize=20)
plt.show()
```

**Actual outcome**

![text_problem](https://user-images.githubusercontent.com/580326/108059262-232ee280-704d-11eb-9a4e-eae5fee13dc3.png)

**Expected outcome**

One of these 2 options:
- It should produce the correct results regardless of kwarg order.
- kwarg `font` shouldn't work at all.

**Matplotlib version**

  * Matplotlib version: 3.3.4
  * Matplotlib backend: Qt5Agg
  * Python version: 3.9.1
Installed via conda.

**Comment by anntzer** [comment]
`font` is just a shorthand for `fontproperties`.  I think the problem is the same as the one described at https://github.com/matplotlib/matplotlib/issues/16389#issuecomment-585110776, and a similar solution applies.

**Comment by ianthomas23** [comment]
@anntzer Thanks for the clarification.  I'll label this as a duplicate and close it.  The above script can be used as one of the tests for the eventual fix.
