### ISSUE TITLE
"Auto-wrapping text" example does not work with inline backend, add link to bugreport/workaround

### ISSUE THREAD

**Issue by mghansen256** [matplotlib/matplotlib#19523]
### Problem

In the matplotlib gallery, there is an auto-wrapping example, which also provides a sample jupyter notebook:

[https://matplotlib.org/stable/gallery/text_labels_and_annotations/autowrap.html](https://matplotlib.org/stable/gallery/text_labels_and_annotations/autowrap.html)

However, due to bug #10869, the auto-wrapping in Jupyter does not work. 

### Suggested Improvement

It would be nice if a note about #10869 could be added in the example, or even possibly the fix indicated in that bug report be included in the notebook.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: **3.3.3** and **3.2.2**
  * Matplotlib documentation version: Stable version from the website, as linked to above

**Comment by jklymak** [comment]
It does work in jupyter, just not with the inline backend.

**Comment by mghansen256** [comment]
Yes, and the example explicitly uses the inline backend since it has the statement "%matplotlib inline" at the top in the Jupyter file.

**Comment by timhoffm** [comment]
As written in https://github.com/matplotlib/matplotlib/issues/10869#issuecomment-376399570 the issue cannot be fixed.

All we can do is improve documentation.

**Comment by tacaswell** [comment]
It is the string vs the rubber band...and the spring always wins.

**Comment by anntzer** [comment]
from
```python
    def _get_wrap_line_width(self):
        """
        Return the maximum line width for wrapping text based on the current
        orientation.
        """
        x0, y0 = self.get_transform().transform(self.get_position())
        figure_box = self.get_figure().get_window_extent()
        ...
```
I guess it may just be a matter of using the right window extents and allowing the user to set `wrap` to any artist (whose extents are used as wrap limits) -- probably BboxImage's API is similar enough to serve as inspiration for specifying bounds?

**Comment by jklymak** [comment]
Agreed, wrapping on the figure isn't that useful compared to wrapping on a bounding box or an axes
