### ISSUE TITLE
Add draw_style to fill_between

### ISSUE THREAD

**Issue by jllamasaspa** [matplotlib/matplotlib#19524]
### Problem
I would like it if the area painted by fill_between aligned properly with a plot that has draw_style flags

### Proposed Solution
I would propose to add draw_style to fill_between

### Additional context and prior art
Having a plot_date that has drawstyle="steps-post" if you use fill_between the area that is painted is just the area like if the drawstyle was set to the default value and generates a filled area that does not fit inside the lines.
What I am proposing here is that fill_between has the option to receive the same drawstyle that exists in as an example in plot_date so that the area that is filled with color and the lines of the plot are aligned properly.
![image](https://user-images.githubusercontent.com/66196409/108042184-55602600-6ff4-11eb-89f2-2712d09aeb13.png)

**Comment by QuLogic** [comment]
`fill_between` accepts `step='post'`, which I think does what you want?

**Comment by jllamasaspa** [comment]
Thanks and sorry :-(
