### ISSUE TITLE
Stem plot creates diagonal connections

### ISSUE THREAD

**Issue by ViHammer** [matplotlib/matplotlib#19537]
### Bug report

**Bug summary**

I want to plot x/y data as bars, using the `stem` command. The first array (`coords_sample1s[i]`) contains the positions, the second one (`percentages_sample1s[i]`) the y-values. This produces a plot, where some of the stems are connected. 
This goes against my undestanding of the documentation: "A stem plot plots vertical lines at each x location from the baseline to y, and places a marker there."

**Code for reproduction**

The twin axis plots the grey line, and can be ignored, I included it only for completeness.

```python
for i in range(len(sample1s)):
        axs[i].stem(coords_sample1s[i], percentages_sample1s[i], markerfmt='', bottom=0)
        axs[i].ticklabel_format(useOffset=False, style='plain')
        axs[i].set_ylim(-0.05, 1.05)
        axs[i].axvspan(int(dmr[2]), int(dmr[3]), alpha=0.3, color='orange')
        axs[i].set_xlim([min_coord-20, max_coord+20])
        twins.append(axs[i].twinx())
        twins[i].plot(coords_sample1s[i], covs_sample1s[i], '-', color=(96/255, 96/255, 96/255, 0.8), linewidth=0.5)
        twins[i].set_ylim([-(max_cov / 20), max_cov + (max_cov / 20)]) 
        twins[i].yaxis.set_major_locator(MaxNLocator(integer=True))
        axs[i].set_xlabel("position", fontsize=8)
        axs[i].set_ylabel("ratio methylated", fontsize=8)
        twins[i].set_ylabel("coverage", fontsize=8)
```

**Actual outcome**

![stemplot](https://user-images.githubusercontent.com/43847498/108394273-d564d680-7214-11eb-87be-e83ece83ce74.PNG)

**Expected outcome**
I am expecting a result similar to this, with independent stems:
![stemplot2](https://user-images.githubusercontent.com/43847498/108394497-0cd38300-7215-11eb-9eb9-49890699e449.PNG)

**important packages in my conda environment**

  * matplotlib 3.3.4
  * matplotlib-base 3.3.4
  * python 3.8.5

**Comment by jklymak** [comment]
Can you discuss in https://discourse.matplotlib.org with code that is self-contained and as minimal as possible?  I'll close this for now, but we can reopen if an issue is found.

**Comment by ViHammer** [comment]
Sure, will do.
