### ISSUE TITLE
Regression in 3.4.0rc1 in creating ListedColormap from a set

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#19544]
### Bug report

**Bug summary**

Apparently I have some code that creates a `ListedColormap` object from a set of RGB tuples (I'm not sure why) and this fails on the 3.4.0 release candidate, but didn't previously.

**Code for reproduction**

```python
import matplotlib as mpl
print(mpl.__version__)
colors = [(0, .5, 1), (1, .2, .5), (.4, 1, .2)]
cmap = mpl.colors.ListedColormap(set(colors))
print(cmap([0, .5, 1]))
```

**Actual outcome**

```python-traceback
3.4.0rc1
Traceback (most recent call last):
  File "mpl_debug.py", line 5, in <module>
    print(cmap([0, .5, 1]))
  File "/Users/mwaskom/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py", line 598, in __call__
    self._init()
  File "/Users/mwaskom/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py", line 1036, in _init
    self._lut[:-3] = to_rgba_array(self.colors)
  File "/Users/mwaskom/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py", line 369, in to_rgba_array
    rgba = np.column_stack([c, np.ones(len(c))])
  File "<__array_function__ internals>", line 5, in column_stack
  File "/Users/mwaskom/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3
```

**Expected outcome**

```
3.3.2
[[1.  0.2 0.5 1. ]
 [0.4 1.  0.2 1. ]
 [0.  0.5 1.  1. ]]
```

**Matplotlib version**

  * Operating system: macos
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.4.0.rc1
  * Matplotlib backend (`print(matplotlib.get_backend())`):  macosx
  * Python version: 3.8.x
  * Jupyter version (if applicable): na
  * Other libraries: 

Installed the release candidate by pointing pip at the tarball on the github releases page.

**Comment by mwaskom** [comment]
I am not sure exactly what changed in matplotlib to cause this but I think it can be avoided by simply casting the input to list in `ListedColormap`. I'm not sure if that will cause downstream issues if the input is an array, but something like

```
class ListedColormap(Colormap):
    def __init__(self, colors, name='from_list', N=None):
        self.monochrome = False  # Are all colors identical? (for contour.py)
        if N is None:
            if not isinstance(colors, np.ndarray):
                colors = list(colors)
            self.colors = colors
            N = len(colors)
```

Could work?

Maybe you'd want to check for `colors.__array__`? Not sure.

**Comment by tacaswell** [comment]
Given that set order is not stable, I am not sure that on the mpl side we should accept sets to listed colormap. I argue that the code passing a set of RGB tuples is at best using undefined behavior and at worst buggy.

----

set order is stable to repeated iteration in a process, but not between processes or if you add/remove things.

```
(bleeding) /tmp 
✔ 10:53:59 $ python -c "print(set(['b', 'c', 'a']))"
{'a', 'b', 'c'}
(bleeding) /tmp 
✔ 10:54:00 $ python -c "print(set(['b', 'c', 'a']))"
{'b', 'a', 'c'}
(bleeding) /tmp 
✔ 10:54:01 $ python -c "print(set(['b', 'c', 'a']))"
{'c', 'a', 'b'}
(bleeding) /tmp 
✔ 10:54:01 $ python -c "print(set(['b', 'c', 'a']))"
{'c', 'b', 'a'}
(bleeding) /tmp 
✔ 10:54:01 $ python -c "print(set(['b', 'c', 'a']))"
{'b', 'a', 'c'}
(bleeding) /tmp 
✔ 10:54:02 $ python -c "print(set(['b', 'c', 'a']))"
{'b', 'a', 'c'}
(bleeding) /tmp 
✔ 10:54:03 $ python -c "print(set(['b', 'c', 'a']))"
{'c', 'a', 'b'}
```

**Comment by tacaswell** [comment]
Also, thank you for testing the RC :tada:

**Comment by mwaskom** [comment]
I basically agree that there's no real reason to accept sets in `ListedColormap` (or to pass sets — although in my case the 
ordering logic is handled externally and everything is weird but functional).

But unfortunately this change (which AFAICT is probably somewhere deeper, in the RGB handling code) does break seaborn without a practicable user-space workaround.

So one option (suggested above) would be to coerce listy-things to list, and hence accept sets even though they don't make much sense. Alternatively, it would make sense for `ListedColormap` to typecheck the input and raise if it's not a list or array (which is what the docstring does claim to accept), but I would ask that this get a deprecation cycle.

**Comment by mwaskom** [comment]
Ah, here's another case where a sequence-y input used to work but now fails:

```python
mpl.colors.ListedColormap("rgbyck")([0, 1, 2, 3, 4])
```

**Comment by mwaskom** [comment]
Here's another one that makes some amount of sense, but stops working on 3.4.0.rc1:

```python
palette = {"red": (1, 0, 0), "green": (0, 1, 0), "blue": (0, 0, 1)}
mpl.colors.ListedColormap(palette.values())([0, 1, 2])
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-112-72ef5d2e590e> in <module>
----> 1 mpl.colors.ListedColormap(palette.values())([0, 1, 2])

~/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py in __call__(self, X, alpha, bytes)
    596         """
    597         if not self._isinit:
--> 598             self._init()
    599
    600         mask_bad = X.mask if np.ma.is_masked(X) else np.isnan(X)  # Mask nan's.

~/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py in _init(self)
   1034     def _init(self):
   1035         self._lut = np.zeros((self.N + 3, 4), float)
-> 1036         self._lut[:-3] = to_rgba_array(self.colors)
   1037         self._isinit = True
   1038         self._set_extremes()

~/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/matplotlib/colors.py in to_rgba_array(c, alpha)
    367     lens = {len(cc) if isinstance(cc, (list, tuple)) else -1 for cc in c}
    368     if lens == {3}:
--> 369         rgba = np.column_stack([c, np.ones(len(c))])
    370     elif lens == {4}:
    371         rgba = np.array(c)

<__array_function__ internals> in column_stack(*args, **kwargs)

~/miniconda3/envs/mpl34_test/lib/python3.8/site-packages/numpy/lib/shape_base.py in column_stack(tup)
    654             arr = array(arr, copy=False, subok=True, ndmin=2).T
    655         arrays.append(arr)
--> 656     return _nx.concatenate(arrays, 1)
    657
    658

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3
```

**Comment by anntzer** [comment]
you could just add a check for `collections.abc.Set` if you want to be extra extra safe, but I wouldn't overly worry about it either (I'd guess there's a lot of other places where we accidentally accept sets (because they can be turned into lists) even though they don't make much sense there).

**Comment by mwaskom** [comment]
I think the problem here is that `lens = {len(cc) if isinstance(cc, (list, tuple)) else -1 for cc in c}` works when `c` is a generic iterable (set, string, dict values), but in `np.column_stack` `c` ends up as an object array with `arr.shape[0] == 1`, causing the error.

I expect this is going to lead to subtle problems in other functions that take this path.

**Comment by WeatherGod** [comment]
Just as a sanity check, can we get confirmation that numpy itself isn't the
cause? i.e., that the two versions of matplotlib you are testing have the
same version of numpy?

**Comment by mwaskom** [comment]
Good thinking. numpy is 1.19.2 in both environments.

The set and dict issue reduces to

```python
a = np.asarray({1, 2, 3}); b = np.array([4, 5, 6]); np.column_stack([a, b])
```

in numpy, if you want to check across versions.

The sequence of single color codes, interestingly, fails on a different path.

**Comment by mwaskom** [comment]
Can I ask for a triage tag here? If this new behavior is going to persist into the 3.4 release, I'll need to push out a point release to do damage control.

**Comment by jklymak** [comment]
Sure we can add to today's dev call.  Does anyone remember what changed?

**Comment by jklymak** [comment]
Bisects to https://github.com/matplotlib/matplotlib/pull/19287 @anntzer

**Comment by jklymak** [comment]
We are assuming that we can call `np.column_stack([c, np.ones(len(c))])` on `colors = [(0, .5, 1), (1, .2, .5), (.4, 1, .2)];colors=set(colors)` which we did to speed things up in the case that colors was clearly a list of 3 or 4 tuples.  I guess we can check for a set, warn, and convert to a list.

**Comment by mwaskom** [comment]
Don't forget the other examples I posted (of which `dict_values` seems like the most reasonable thing to expect to work here).

I think the question is when you do `np.asarray(c)` do you get a `float` dtype (will work) or an `object` dtype (will not).

**Comment by jklymak** [comment]
yeah, but if we do that, I'm guessing we may as well just revert #19287

**Comment by mwaskom** [comment]
IMO #19287 is probably incorrect because it assumes that an iterable of length {3,4} sequences is equivalent to a Nx{3,4} ndarray, which the counterexamples given here demonstrate is not necessarily the case.

**Comment by anntzer** [comment]
Not tested, but I guess something like
```patch
diff --git i/lib/matplotlib/colors.py w/lib/matplotlib/colors.py
index 943008f92..ae3e35e10 100644
--- i/lib/matplotlib/colors.py
+++ w/lib/matplotlib/colors.py
@@ -364,12 +364,14 @@ def to_rgba_array(c, alpha=None):
 
     # Quick path if the whole sequence can be directly converted to a numpy
     # array in one shot.
-    lens = {len(cc) if isinstance(cc, (list, tuple)) else -1 for cc in c}
-    if lens == {3}:
-        rgba = np.column_stack([c, np.ones(len(c))])
-    elif lens == {4}:
-        rgba = np.array(c)
-    else:
+    rgba = None
+    if isinstance(c, list):
+        lens = {len(cc) if isinstance(cc, (list, tuple)) else -1 for cc in c}
+        if lens == {3}:
+            rgba = np.column_stack([c, np.ones(len(c))])
+        elif lens == {4}:
+            rgba = np.array(c)
+    if rgba is None:
         rgba = np.array([to_rgba(cc) for cc in c])
 
     if alpha is not None:
```
would help?

**Comment by jklymak** [comment]
See #19583 for a quick fix as above.  

Its fine for us to fix this here, but in general, undocumented calls are discouraged: [ListedColormap](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.ListedColormap.html) and friends want either a list or an array, not any iterable.  That it worked before is unsupported happenstance!

**Comment by mwaskom** [comment]
> In general, undocumented calls are discouraged: ListedColormap and friends want either a list or an array, not any iterable. That it worked before is unsupported happenstance!

Fair enough, although if you're going to treat the documented input types as restrictive, it's encouraged to check and raise on invalid inputs :)

**Comment by jklymak** [comment]
...be careful what you ask for 😀
