### ISSUE TITLE
Axes.get_xticks() returns a numpy array but Axes.get_xticks(minor=True) returns a plain list

### ISSUE THREAD

**Issue by emazep** [matplotlib/matplotlib#19559]
`Axes.get_{x|y}ticks()` called with no actual parameters or with `minor=False` returns a numpy array, but if the same method is called with `minor=True`, then it returns a plain list, as showed by the following snippet:

```python
import matplotlib.pyplot as plt

_, ax = plt.subplots()

print(type(ax.get_xticks()))
print(type(ax.get_xticks(minor=True)))
```

which produces:

```
<class 'numpy.ndarray'>
<class 'list'>
```

so my question is if this is the intended behaviour. It's not just a question of consistency, since this discrepancy in return types can cause unexpected errors in code not entirely fanciful like this:

```python
# given the snippet above
major_locs = ax.get_xticks(minor=False)
minor_locs = ax.get_xticks(minor=True)
locs = major_locs + minor_locs
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

      1 major_locs = ax.get_xticks(minor=False)
      2 minor_locs = ax.get_xticks(minor=True)
----> 3 locs = major_locs + minor_locs

ValueError: operands could not be broadcast together with shapes (6,) (0,)
```

so I wonder if it could at least be documented.

Thank you for the great work!

**Matplotlib version**
  * Operating system: any
  * Matplotlib version: 3.3.4 
  * Matplotlib backend: module://ipykernel.pylab.backend_inline 
  * Python version: 3.8.8

**Comment by smartlixx** [comment]
Based on the definition of `axis.get_ticklocs`:

https://github.com/matplotlib/matplotlib/blob/a510e32a37a8b4e0bc4e8384df20c7b45abd9913/lib/matplotlib/axis.py#L1269-L1272

When one calls `ax.get_xticks()` or `ax.get_xticks(minor=False)`, `get_minorticklocs()` is called:

https://github.com/matplotlib/matplotlib/blob/a510e32a37a8b4e0bc4e8384df20c7b45abd9913/lib/matplotlib/axis.py#L1251-L1267

which will return `matplotlib.ticker.Locator` or `list` depending on if there is overlapping between major and minor ticks.

When one calls `ax.get_xticks(minor=True)`, `get_majorticklocs()` will be called instead:

https://github.com/matplotlib/matplotlib/blob/a510e32a37a8b4e0bc4e8384df20c7b45abd9913/lib/matplotlib/axis.py#L1247-L1249

which will return `matplotlib.ticker.Locator`. 

The solution is to modify `get_minorticklocs()` to return `matplotlib.ticker.Locator` when there are overlapping minor and major ticks, i.e., from `list` to `matplotlib.ticker.Locator`. I am not sure how to do this type conversion.

**Comment by emazep** [comment]
And what about the other way around, that is always returning a plain list instead? I see it slightly handier in the use-cases I can think of.
