### ISSUE TITLE
ValueError: Invalid RGBA argument: 'G'

### ISSUE THREAD

**Issue by seanxwh** [matplotlib/matplotlib#19569]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#

 318                  bbox=dict(facecolor='none', edgecolor='0.82'), fontweight='bold')
    319
--> 320       plt.savefig(path_main+ '\Graph_cBSi_Para.png', bbox_inches='tight', dpi = 200)
    321
    322       ################ploting color map for S21 data

```

**Actual outcome**

c:\program files\python38\lib\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    857 def savefig(*args, **kwargs):
    858     fig = gcf()
--> 859     res = fig.savefig(*args, **kwargs)
    860     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    861     return res

c:\program files\python38\lib\site-packages\matplotlib\figure.py in savefig(self, fname, transparent, **kwargs)
   2309                 patch.set_edgecolor('none')
   2310
-> 2311         self.canvas.print_figure(fname, **kwargs)
   2312
   2313         if transparent:

c:\program files\python38\lib\site-packages\matplotlib\backends\backend_qt5agg.py in print_figure(self, *args, **kwargs)
     79
     80     def print_figure(self, *args, **kwargs):
---> 81         super().print_figure(*args, **kwargs)
     82         self.draw()
     83

c:\program files\python38\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194
   2195                     bbox_inches = self.figure.get_tightbbox(

c:\program files\python38\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

c:\program files\python38\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1861
   1862             self.patch.draw(renderer)
-> 1863             mimage._draw_list_compositing_images(
   1864                 renderer, self, artists, self.suppressComposite)
   1865

c:\program files\python38\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

c:\program files\python38\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

c:\program files\python38\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412
    413     return wrapper

c:\program files\python38\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2745             renderer.stop_rasterizing()
   2746
-> 2747         mimage._draw_list_compositing_images(renderer, self, artists)
   2748
   2749         renderer.close_group('axes')

c:\program files\python38\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

c:\program files\python38\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

c:\program files\python38\lib\site-packages\matplotlib\axis.py in draw(self, renderer, *args, **kwargs)
   1176         self._update_label_position(renderer)
   1177
-> 1178         self.label.draw(renderer)
   1179
   1180         self._update_offset_text_position(ticklabelBoxes, ticklabelBoxes2)

c:\program files\python38\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

c:\program files\python38\lib\site-packages\matplotlib\text.py in draw(self, renderer)
    697
    698             gc = renderer.new_gc()
--> 699             gc.set_foreground(textobj.get_color())
    700             gc.set_alpha(textobj.get_alpha())
    701             gc.set_url(textobj._url)

c:\program files\python38\lib\site-packages\matplotlib\backend_bases.py in set_foreground(self, fg, isRGBA)
    953             self._rgb = fg
    954         else:
--> 955             self._rgb = colors.to_rgba(fg)
    956
    957     def set_joinstyle(self, js):

c:\program files\python38\lib\site-packages\matplotlib\colors.py in to_rgba(c, alpha)
    187         rgba = None
    188     if rgba is None:  # Suppress exception chaining of cache lookup failure.
--> 189         rgba = _to_rgba_no_colorcycle(c, alpha)
    190         try:
    191             _colors_full_map.cache[c, alpha] = rgba

c:\program files\python38\lib\site-packages\matplotlib\colors.py in _to_rgba_no_colorcycle(c, alpha)
    258                     f"Value must be within 0-1 range")
    259             return c, c, c, alpha if alpha is not None else 1.
--> 260         raise ValueError(f"Invalid RGBA argument: {orig_c!r}")
    261     # tuple color.
    262     if not np.iterable(c):

ValueError: Invalid RGBA argument: 'G'

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: windows 10 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable): 
  * Other libraries: 

pip

**Comment by jklymak** [comment]
What artist were you trying to make? Please provide a full example.

**Comment by seanxwh** [comment]
Sorry the version of matplotlib that I have issue at is 3.3.2
error didn't show up after rolled back to 3.1.2
@jklymak  How do I find the artist that you mentioned?
Thanks for helping

**Comment by jklymak** [comment]
Exactly what did you call to get the error?

**Comment by seanxwh** [comment]
the program that I used called `plt.savefig` like 
` plt.savefig(path_main+ '\Graph_cBSi_Para.png', bbox_inches='tight', dpi = 200)`
no error in 3.1.2

**Comment by jklymak** [comment]
Yes but how did the plot get made?

**Comment by seanxwh** [comment]
@jklymak, sorry I don't have enough knowledge on that, how can you tell? any reference? 
Thanks

**Comment by jklymak** [comment]
How did you make the figure you are trying to save?

**Comment by seanxwh** [comment]
i think is `fig = plt.figure` and `ax = fig.add_subplot`

**Comment by jklymak** [comment]
OK, we can't help further if you can't reproduce the problem with a self-contained block of code (http://sscce.org). It seems maybe you did not actually write the original code. I'm going to close here, but feel free to discuss at discourse.matplotlib.org   You may also have a look at our tutorials. https://matplotlib.org/stable/tutorials/index.html
