### ISSUE TITLE
Memory leak with FuncAnimation and matshow.

### ISSUE THREAD

**Issue by david-hoffman** [matplotlib/matplotlib#19561]
### Bug report

**Bug summary**

Using `FuncAnimation` to update an image (`matshow` or `imshow`) causes a memory leak on Windows. I've tested MacOS as well and it doesn't seem to be a problem.

**Code for reproduction**

```python
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# test_memory_leak.py
"""Test memory leak."""

import matplotlib as mpl

mpl.use("Qt5Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation


def images(shape=(4096, 4096)):
    """Image stream."""
    while True:
        yield np.random.randint(256, size=shape, dtype="uint16")


def make_display():
    """Make display, returns update function."""
    # initialize plots
    fig, ax_img = plt.subplots()

    # image plots
    img_plot = ax_img.matshow(np.empty((64, 64)), vmin=-1, vmax=1, cmap="Greys_r")
    ax_img.set_title("Image")
    ax_img.set_aspect(1)

    ax_img.xaxis.set_major_locator(plt.NullLocator())
    ax_img.yaxis.set_major_locator(plt.NullLocator())

    data_shape = (0, 0)

    def update_func(img):

        nonlocal data_shape

        img_plot.set_data(img)
        img_plot.set_clim(img.min(), img.max())

        if data_shape != img.shape:
            ny, nx = img.shape
            img_plot.set_extent((-0.5, nx + 0.5, ny + 0.5, -0.5))
            data_shape = img.shape

        ax_img.autoscale_view()

        return img_plot

    return update_func, fig


def live():
    """Show live image."""
    update_func, fig = make_display()

    ani = FuncAnimation(
        fig, update_func, frames=images(), interval=1, cache_frame_data=False, save_count=0
    )
    plt.show()


if __name__ == "__main__":
    live()

```

**Matplotlib version**

  * Operating system: Windows 10 Version 1909 (OS Build 18363.1016)
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg` (I've tested `TkAgg` too)
  * Python version: 3.9.1

All installed with `conda`

**Comment by anntzer** [comment]
I can repro the leak on master using memory_profiler; a quick check with objgraph suggests that we are not leaking python objects, but C-level ones...

**Comment by david-hoffman** [comment]
Seems like adding `repeat=False` to the `FuncAnimation` call solves the problem.

**Comment by QuLogic** [comment]
Using `tracemalloc`, I can find that the leak is on the random call:
```
  def images(shape=(4096, 4096)):
      """Image stream."""
      while True:
          yield np.random.randint(256, size=shape, dtype="uint16")
```

Since it's not likely that that leaks at this point, I looked at what @david-hoffman said, and that appears to be it.

With `repeat=True`, the frames are passed to `itertools.tee` and thus every array of random data is held on to for the next loop, but there isn't one. So I guess this is working as intended, but needs better documentation.
