### ISSUE TITLE
axes.get_bars()

### ISSUE THREAD

**Issue by Simplimus** [matplotlib/matplotlib#19565]
### Problem
I would like to change the appearance of a stacked bar plot, e.g. change the color of the top bars.

If I had multiple lines, I would use matplotlib.axes.Axes.get_lines() to get a list of all line handles and change the line appearance.
Now with bar plots, such a function does not exist (or I couldn't find it).
People have asked for this feature before.
https://stackoverflow.com/questions/22688915/how-do-i-get-all-bars-in-a-matplotlib-bar-chart
The suggestion in the mentioned thread is to store the handle upon creation like 
rects1 = ax.bar(x - width/2, men_means, width, label='Men')
in this example
https://matplotlib.org/3.1.1/gallery/lines_bars_and_markers/barchart.html#sphx-glr-gallery-lines-bars-and-markers-barchart-py

However, I specifically want to change the appearance of a plot after the fact. I want to automatically make them corporate design compliant and export the figure with just one command. And for that, I need a getter function for the handles for each bar.

### Proposed Solution
Create a function
axes.get_bars()
that returns a list of all bar plots. Each element in the list should be a matplotlib.container.BarContainer, just like the return of matplotlib.axes.Axes.bar().

Thank you.

**Comment by jklymak** [comment]
Just call `get_artists` and search for the ones you want.  We are trying to go the other way of not maintaining separate lists.  

However, if you have the axes object, then you certainly could have stored the handle to the bars, or just set the colors correctly in the first place.

**Comment by mwaskom** [comment]
> However, if you have the axes object, then you certainly could have stored the handle to the bars, or just set the colors correctly in the first place.

That's not true; pandas and seaborn and probably others will return the Axes but not the artists. (And may or may not expose complete customization through their call API).

That said @Simplimus the `Axes.patches` list will have the artists you're looking for. If you look at the source for `get_lines` it's basically doing the same thing (with a slightly nicer repr).

```
    def get_lines(self):
        """Return a list of lines contained by the Axes."""
        return cbook.silent_list('Line2D', self.lines)
```

**Comment by jklymak** [comment]
Yes fair enough.  And in general it is `ax.artists` that contains the general list.  `ax.get_children` gets all the axes artists including the ones that make the axes.  

I don't think it makes sense to have a wrapper for every type of artist.  The alternative is that we add `get_foo` for every type of artist; see #18216 for how we are going the other way internally.

**Comment by timhoffm** [comment]
We do not store the sematic representation "bar" internally. We only store artist types: lines, patches, and cannot say whether a certain patch represents a bar. Therefore, we can't provide `get_bars()` even if we wanted to. For simple cases, If your plot only contains bars, `ax.patches` will do.

> > However, if you have the axes object, then you certainly could have stored the handle to the bars, or just set the colors correctly in the first place.
> 
> That's not true; pandas and seaborn and probably others will return the Axes but not the artists. (And may or may not expose complete customization through their call API).

If you choose to use higher-level interfaces, that may mean that customizability is limited. It's not the responsibility of matplotlib to work around limitations / design decisions in seaborn or pandas.

I'm closing this as not actionable.

**Comment by rcomer** [comment]
> I'm closing this as not actionable.

👀
