### ISSUE TITLE
plt.pause crashes GTK3Agg

### ISSUE THREAD

**Issue by tfpf** [matplotlib/matplotlib#19593]
### Bug report
**Bug summary**

Calling [`plt.pause`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pause.html) inside a [callback](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.connect.html) crashes the GTK3Agg backend.

**Code for reproduction**
```python
import matplotlib as mpl
mpl.use('GTK3Agg')

import matplotlib.pyplot as plt

def do_nothing(event):
    print('In callback.')
    plt.pause(1)

fig = plt.figure()
fig.canvas.mpl_connect('resize_event', do_nothing)

ax = fig.add_subplot()
ax.plot(0, 0, 'o')
plt.show()
```

**Actual outcome**
```
In callback.
**
Gtk:ERROR:../../../../gtk/gtkwindow.c:10698:gtk_window_present_with_time: assertion failed: (gdk_window != NULL)
Bail out! Gtk:ERROR:../../../../gtk/gtkwindow.c:10698:gtk_window_present_with_time: assertion failed: (gdk_window != NULL)
Aborted (core dumped)
```

**Expected outcome**

The graph should be plotted. No crashes should occur.

**Matplotlib version**
  * Operating system: Linux Mint 20 (Ulyana)
  * Matplotlib version: 3.3.3 (installed via `pip install matplotlib`)
  * Matplotlib backend: GTK3Agg
  * Python version: 3.8.5
  * GTK version: 3.0

**More Details**

The problem disappears upon doing either of the following.
  * Using the TkAgg backend.
  * Removing the line `plt.pause(1)`.

**Comment by anntzer** [comment]
Looks like
```patch
diff --git i/lib/matplotlib/backends/backend_gtk3.py w/lib/matplotlib/backends/backend_gtk3.py
index 246cab755..d68340b9f 100644
--- i/lib/matplotlib/backends/backend_gtk3.py
+++ w/lib/matplotlib/backends/backend_gtk3.py
@@ -391,7 +391,11 @@ class FigureManagerGTK3(FigureManagerBase):
         # show the figure window
         self.window.show()
         self.canvas.draw()
-        if mpl.rcParams['figure.raise_window']:
+        # If this is called by a callback early during init, self.window (a
+        # GtkWindow) may not have an associated low-level GdkWindow
+        # (self.window.get_window()) yet, and present() would crash -- hence
+        # the check.
+        if mpl.rcParams['figure.raise_window'] and self.window.get_window():
             self.window.present()
 
     def full_screen_toggle(self):
```
works?

**Comment by tfpf** [comment]
Indeed, this seems to fix the problem.

Is it possible that other backends might have the same issue?

**Comment by anntzer** [comment]
fwiw I can't repro the failure on wx.

**Comment by tfpf** [comment]
Oh, then it could be due to a problem with my WX installation. I now recall not having done it properly. 

Either way, I guess that’s that for this issue.
