### ISSUE TITLE
Can't download matplotlib with pip download

### ISSUE THREAD

**Issue by data-toaster** [matplotlib/matplotlib#19590]
### Bug report

**Bug summary**

Hi, I need to use matplotlib in a linux box that is not connected to the internet, so I normally download python pkgs elsewhere then move them to the vm and use pip with --no-index and --find-links to my local "repo" folder.  
However, there's no way to download matplotlib. I tried several combinations of platform, abi, etc, but in the end the command I use goes along the lines of the following: `python3 -m pip download --only-binary=:all: --platform linux_x86_64 matplotlib` 

**Code for reproduction**

In a box connected to the internet, try `python3 -m pip download --only-binary=:all: --platform linux_x86_64 matplotlib`

**Actual outcome**
```
Collecting matplotlib
Could not find a version that satisfies the requirement matplotlib (from versions: )
No matching distribution found for matplotlib
```
**Expected outcome**

Download the package wheel.

**Matplotlib version**
Tried the latest 3.3.4
  * Operating system: Tried to download from Linux, OSX, Windows. 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): n/a
  * Python version: 3.6
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

Perhaps I'm doing something wrong? 
Thanks

**Comment by tacaswell** [comment]
I think you need to remove the platform tag as pip is trying to pull all of the dependencies, some of which have no-arch/universal wheels, hence it fails to find a valid platform specific wheel for e.g. cycler.

I am going to close this as I do not think there is anything we can do on the Matplotlib side of things.  You may want to open an issue with pip if you think this behavior is buggy.

-------

```
/tmp 
✘ 09:42:53 $ python3.6 -m venv /tmp/old36
/tmp
✔ 09:43:05 $ vox activate /tmp/old36
Activated "/tmp/old36".
(old36) /tmp 
✔ 09:44:53 $ python3 -m pip download --only-binary=:all: matplotlib
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl
  Saved ./matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/a7/1b/cbd8ae738719b5f41592a12057ef5442e2ed5f5cb5451f8fc7e9f8875a1a/kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
  Saved ./kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
  Saved ./python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting numpy>=1.15 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
  Saved ./numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
  Saved ./cycler-0.10.0-py2.py3-none-any.whl
Collecting pillow>=6.2.0 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/b6/c0/442d9d87e0da00bf856ef6dd4916f84a2d710b5f1a367d42d7f3c4e99a6c/Pillow-8.1.0-cp36-cp36m-manylinux1_x86_64.whl
  Saved ./Pillow-8.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
  Saved ./pyparsing-2.4.7-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
  Saved ./six-1.15.0-py2.py3-none-any.whl
Successfully downloaded matplotlib kiwisolver python-dateutil numpy cycler pillow pyparsing six
You are using pip version 18.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(old36) /tmp 
```

**Comment by data-toaster** [comment]
yeah, I'll ask on SO, the issue is more on the pip side.
The reason I was using platform  is because the majority of times users download pkgs from windows workstations.

**Comment by tacaswell** [comment]
> The reason I was using platform is because the majority of times users download pkgs from windows workstations.

Ah, fair enough.  This is definitely a pip issue not a mpl issue though. Good luck!
