### ISSUE TITLE
StopIteration crash with FuncAnimation and FFMpegWriter

### ISSUE THREAD

**Issue by petercorke** [matplotlib/matplotlib#19599]
### Bug report

**Bug summary**

Very similar to closed issue #13676, but this occurs when `frames` is an iterator, **and** a movie is being written **and** a block is called.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, FFMpegWriter

fig, ax = plt.subplots()
plt.plot([1,2,3],[2,4,3])
def update(frame):
	print(frame)
	return []
animation = FuncAnimation(fig, update, frames=iter(range(10)), blit=False, interval=100, repeat=False)

FFwriter = FFMpegWriter(fps=100, extra_args=['-vcodec', 'libx264'])
animation.save('test.mp4', writer=FFwriter)

print('** starting block')
plt.show(block=True)
print('  done with block')
```

While arguably a `block` is not essential, in my application I generally need to use a `block` somewhere downstream in the program to hold a plot for the user, and that is what triggers the exception.

**Actual outcome**

The file is always saved, but an exception is thrown.

```
** starting block
Traceback (most recent call last):
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/site-packages/matplotlib/animation.py", line 975, in _start
    self._init_draw()
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/site-packages/matplotlib/animation.py", line 1719, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
StopIteration
  done with block
```

**Expected outcome**

No exception thrown.

I can't catch and ignore this exception since it's thrown by a background thead.

**Matplotlib version**
  * MacOS 10.15.7
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.5
  * Jupyter version (if applicable): n/a
  * Other libraries: 

pip installed

**Comment by dopplershift** [comment]
What's triggering the exception is that you pass in an iterator, which can only be used once, but you're both showing and saving the animation, which requires running through the iterator twice.

The easiest way is instead of passing an iterator directly for `frames`, pass a callable that returns an iterator, like:

```python
animation = FuncAnimation(fig, update, frames=lambda: iter(range(10)), blit=False, interval=100, repeat=False)
```
