### ISSUE TITLE
Inconsistent behavior of subplots_adjust() with tight_layout

### ISSUE THREAD

**Issue by chaochinyang** [matplotlib/matplotlib#19604]
### Bug report

**Bug summary**

When passing hspace=0 or wspace=0 to subplot_adjust(), the boundary of adjacent axes should be merged without space, as the example at the page

[Creating adjacent subplots](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/ganged_plots.html#sphx-glr-gallery-subplots-axes-and-figures-ganged-plots-py)

However, when tight_layout is turned on, there is always space between the axes.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, sharex=True, sharey=True,
    tight_layout=True)
fig.subplots_adjust(wspace=0, hspace=0)

plt.show()
```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/11709830/109438088-23c86100-79dd-11eb-8994-85d495351c76.png)

**Expected outcome**

![Figure_2](https://user-images.githubusercontent.com/11709830/109438111-36db3100-79dd-11eb-8b5b-06b7878ddbc3.png)

**Matplotlib version**

  * Operating system: macOS Big Sur 11.2.2
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.5
  * Jupyter version (if applicable): 
  * Other libraries: 

I use the Anaconda distribution for accessing my Python and Matplotlib.

**Comment by jklymak** [comment]
tight_layout resets all the settings set by `subplots_adjust`.  Suggest you use the pad arguments.  Please see https://matplotlib.org/stable/tutorials/intermediate/tight_layout_guide.html#sphx-glr-tutorials-intermediate-tight-layout-guide-py and further discussion on https://discourse.matplotlib.org  Thanks
