### ISSUE TITLE
Curves with same label not appearing in Figure options (only the last one)

### ISSUE THREAD

**Issue by axtschmied** [matplotlib/matplotlib#19607]
### Bug report

**Bug summary**
If there are multiple curves with the same label in a figure/subplot, only the last one of them can be selected in the *Figure options* window under the *Curves* tab. In the legend however, they appear as they should.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
plt.plot([0,1],[0,1],label="line")
plt.plot([0,1],[1,0],label="line")
plt.legend()
plt.show()
```

**Actual outcome**
See description above and the image below.

![figure_options](https://user-images.githubusercontent.com/28358038/109487440-80328b80-7a84-11eb-81a2-b95fab397d9f.png)

**Expected outcome**
All curves should be listed in the *Figure options* window, even if they have the same label.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.5
  * Jupyter version (if applicable): -
  * Other libraries: -

Matplotlib has been installed with pip.

**Comment by timhoffm** [comment]
The GUI logic is based on a dict with labels as keys:
https://github.com/matplotlib/matplotlib/blob/6a35abfa2efdaf3b9efe49d4398164fa4cc6c3a3/lib/matplotlib/backends/qt_editor/figureoptions.py#L69

This could be rewritten using lists. Note however, that you'll get two "laden" entries in your example, and it's hard to tell which entry is for which line.

**Comment by axtschmied** [comment]
> This could be rewritten using lists. Note however, that you'll get two "laden" entries in your example, and it's hard to tell which entry is for which line.

I don't think this is a huge concern, unless somebody has lots of curves with the same name (which would probably cause even bigger problems than this).

**Comment by timhoffm** [comment]
> I don't think this is a huge concern

I agree. We should just be aware of this. Duplicate names in the legend are still quite clear as the legend is essentially a mapping handle -> name. OTOH here we use the name as a key and don't have any visual help what that corresponds to.
