### ISSUE TITLE
Replace use of Python/C API with numpy::array_view in _tri.cpp and qhull_wrap.c

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#19627]
`_tri.cpp` and `qhull_wrap.c` use the Python/C API to create numpy arrays, e.g.:

https://github.com/matplotlib/matplotlib/blob/bc972942bd41a32c7cd693a3f29a29442d2d6e3f/src/tri/_tri.cpp#L638-L639

It would be better to use our `numpy::array_view` wrappers instead, e.g.

https://github.com/matplotlib/matplotlib/blob/bc972942bd41a32c7cd693a3f29a29442d2d6e3f/src/_contour.cpp#L440

as it is simpler and deals with reference counting and raising exceptions for us.

Self-assigning.

**Comment by rajpratyush** [comment]
@ianthomas if you are not working on the issue can I take it up ?

**Comment by ianthomas23** [comment]
@rajpratyush I haven't started to work on this issue so if you would like to then please go ahead.  I will unassign myself.

My issue report gave an example of what to do for numpy arrays that are created in C/C++ and returned to Python.  I've realised that `qhull_wrap.c` also needs updating for numpy arrays that are passed in the other direction.  For example

https://github.com/matplotlib/matplotlib/blob/200ebe1dcb8c8adb9ed4d177f02a57686ffef085/src/qhull_wrap.c#L275-L283

needs to be more like 

https://github.com/matplotlib/matplotlib/blob/200ebe1dcb8c8adb9ed4d177f02a57686ffef085/src/_contour_wrapper.cpp#L36-L44

If you have any questions then ask away.  I know this part of the codebase pretty well.

**Comment by rajpratyush** [comment]
@ianthomas23 surely I would like to give it a try.

**Comment by ianthomas** [comment]
Prettty sure that’s @ianthomas23 you’re looking for

**Comment by QuLogic** [comment]
Converting `qhull_wrap.c` ostensibly means converting it to C++. This is not too difficult, though it does entail fixing some problems with differing standards. But do we also want to convert to Qhull's C++ API? Then we can drop the `goto`s, probably.

**Comment by ianthomas23** [comment]
I'd intended the minimal changes of renaming `qhull_wrap.c` to `qhull_wrap.cpp` and just changing the array reading/writing.  So the wrapper would be mostly C but compiled with a C++ compiler.  Might also need a few tweaks like `extern "C"` wrapping of include files, etc.  This could be done without having to understand qhull's slightly quirky API.

I hadn't considered switching to qhull's C++ API.  It seems to me to be a work in progress and not fully nailed down, so unnecessarily risky for mpl to adopt.

**Comment by QuLogic** [comment]
I opened a separate PR as it was quite a bit long to add to the first one. I didn't bother with the Qhull C++ API, which seems difficult to decipher.

**Comment by ianthomas23** [comment]
OK. I'm probably the most appropriate person to review both PRs so I'll assign myself.
