### ISSUE TITLE
plt.figure() breaks std::stof

### ISSUE THREAD

**Issue by timonegk** [matplotlib/matplotlib#19628]
### Bug report

I am using matplotlib in python code that also calls a python module written in cpp. I now noticed that `plt.figure()` breaks `std::stof` in the cpp extension.

**Code for reproduction**

Put this in `example.cpp`:
```cpp
#include <boost/python.hpp>
#include <string>

float start() {
  std::string str("0.1");
  return std::stof(str);
}

BOOST_PYTHON_MODULE (example) {
  boost::python::def("start", &start);
}
```
Then, compile it to `example.so` (I used `g++ example.cpp -fPIC -shared -I/usr/include/python3.9 -lboost_python39 -lpython3.9 -o example.so`).

In a python script in the same folder, execute
```python
import example
import matplotlib.pyplot as plt
print(example.start())
plt.figure()
print(example.start())
```

**Actual outcome**

```
0.10000000149011612
0.0
```

**Expected outcome**

Both times, the same result should be returned.

**Matplotlib version**
  * Operating system: Debian Testing
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4 (installed via pip)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.9.1 (installed as system package)
  * Other libraries: Boost Python 1.74.0

I could not reproduce the issue on Ubuntu 18.04 (Python 3.6, Matplotlib 3.2.1 / agg), so it might be a problem with my setup.

**Comment by timonegk** [comment]
We could reproduce the issue with Arch Linux (Python 3.9.2, Matplotlib 3.3.4 / Qt5Agg) where the issue occurs already on the pyplot import (even before calling `figure()`).
The issue could not be reproduced on Debian Testing (Python 3.9.1, Matplotlib 3.3.4 / TkAgg), so it might be a problem with the Qt5Agg backend.

**Comment by anntzer** [comment]
Possibly due to the same root cause as #6706?

**Comment by timonegk** [comment]
Yes! That seems to be the problem cause. My `LC_NUMERIC` locale before `plt.figure` is `(None, None)`. After that, it's `('de_DE', 'UTF-8')` (which is my system setting for `LC_NUMERIC` and probably expects `,` instead of the decimal point). When I reset the locale to `(None, None)`, the cpp code works again.

**Comment by anntzer** [comment]
I'll close as "not due to Matplotlib, but to Qt" then.
