### ISSUE TITLE
subplot mosaic 1 element list

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#19631]
**Bug summary**
Passing in a one element list splits it up as if it was string input, when it should treat it as 1 axes. 

**Code for reproduction**
```python
fig, axd = plt.subplot_mosaic(['triangle'])
```
**Actual outcome**
![image](https://user-images.githubusercontent.com/1300499/109868401-8f0c7000-7c35-11eb-82ab-eed516cd47f3.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/1300499/109868504-b2cfb600-7c35-11eb-9aad-926dbf6c9190.png)

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Did you try making it a list of lists?  Because you can't have the string shortcut and support a single string as well.

**Comment by jklymak** [comment]
`fig, axd = plt.subplot_mosaic([['triangle']])` works.

`fig, axd = plt.subplot_mosaic(['triangle', 'boo'])` doesn't work either. so I think all lists need to be 2-D.  I guess you could argue that `['triangle']` should get the same warning as `['triangle', 'boo']`, but...

**Comment by timhoffm** [comment]
We're not supporting 1D lists because it's not obvious whether that should be interpreted as columns or rows, c.f. #17939.
I agree that this should fail with a proper message.

**Comment by story645** [comment]
Since this is the1D list of one object case- there is no row/column ambiguity - is only the 1 axes. Also I thought there was a pick one - either strings or lists -but this to me feels like clobbering the string shorthand with the list behavior.

**Comment by tacaswell** [comment]
I see the bug, it is an oversight in the list-of-list validation where we fail to check if the _first_ element of the outer list is a string :facepalm: , PR coming.
