### ISSUE TITLE
Unexpected (and unremovable) tick labels on log scale plots.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [matplotlib/matplotlib#19642]
### Bug report

Log scale plots will have sometimes have tick labels that cannot be removed by `plt.*ticks` and `ax.set_*ticklabels`, and are unaffected by `ax.set_*ticks`. These ticks labels only show up on the default axes (left and bottom).

In the examples below, the result is invariant to the positioning of all calls except `ax.set_*scale` (which is the ~expected behavior).

A colab notebook with the code for reproduction can be found [here](https://colab.research.google.com/drive/1Eshdw--Qyz6wnaIFYSpsWK2V-0gwp9rG?usp=sharing).

```python
import matplotlib.pyplot as plt
plt.style.use("seaborn-whitegrid")  # Not necessary but makes seeing expected ticks easier.
import numpy as np

# Other values for ymin, ymax, and step also error.
ymin = 220
ymax = 440
step = 1 / 12
ticks = 2 ** np.arange(np.log2(ymin), np.log2(ymax + step), step)
```

```python
# Unaffected by plt.*ticks and ax.set_*ticklabels.
fig, ax = plt.subplots()
ax.scatter([], [])
ax.set_yscale("log")
ax.set_ylim(ymin, ymax)
ax.set_yticklabels([])

# Shows expected behavior (not necessary to reproduce bug).
ax.tick_params(labelright=True)
```

![image](https://user-images.githubusercontent.com/40036383/110048565-f1807180-7d04-11eb-9528-c50417098c73.png)

```python
# Unaffected by ax.set_*ticks.
fig, ax = plt.subplots()

# Shows expected behavior (not necessary to reproduce bug).
ax.tick_params(labelright=True)

# Placing this after labelright has the same effect.
ax.scatter([], [])
ax.set_yscale("log")
ax.set_ylim(ymin, ymax)
ax.set_yticks(ticks)
```

![image](https://user-images.githubusercontent.com/40036383/110048932-b2065500-7d05-11eb-81f3-ed564cbfc69c.png)

### Environment info

  * Operating systems: Linux, macOS 
  * Matplotlib version: `3.2.2` via `pip`
  * Matplotlib backends: `module://ipykernel.pylab.backend_inline`, `MacOSX`
  * Python versions: `3.6.10`, `3.8.6`

**Comment by jklymak** [comment]
The "extra" ticks are minor ticks, which you can control with `which='minor'`  https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.tick_params.html

Feel free to discuss further at https://discourse.matplotlib.org, but I don't think there is any bug here. Thanks!

**Comment by phoenix-meadowlark** [comment]
Oh, minor ticks show up so rarely I didn't think they were ever auto generated – thanks!
