### ISSUE TITLE
The Recommended Random Number Generation In NumPy

### ISSUE THREAD

**Issue by ArnuldOnData** [matplotlib/matplotlib#19670]
### Problem

Matplotlib documentation still uses old method of random number generation in NumPy. I think we can update the code to use newer method. Newer method was intropduced in NumPy 1.17 and recommended by NumPy over the older method (even though the older method still works)

* I found [histogram example](https://matplotlib.org/stable/gallery/statistics/hist.html) can be updated with newer code.

### Suggested Improvement

* We can change the code to shown in [this GitHub gist](https://gist.github.com/ArnuldOnData/3d298ccb3f4ba5b94006bdc55b8ea3d3)
* Entire documenation regarding recommended method is in [NumPy docs](https://numpy.org/doc/stable/reference/random/index.html#random-quick-start)  
* Here is a visualization/output from the code in gist above: 

![matplotlib-numpy-random](https://user-images.githubusercontent.com/60259411/110422384-42a5b200-80c5-11eb-888e-ad8fc9809b73.png)

**Matplotlib version**

  * Operating system: **Arch Linux**
  * Matplotlib version: **3.3.4** (matplotlib.__version__)
  * Python version: **3.9.2**  (platform.python_version())
  * Matplotlib documentation version: **Doc version v3.3.4** (as seen at the bottom of the [histogram page](https://matplotlib.org/stable/gallery/statistics/hist.html) )

**Comment by ria-19** [comment]
Hi, I am a beginner in the open-source world, can I work on this issue?

**Comment by jklymak** [comment]
Anyone can work on an issue if there is no existing PR. If there is a PR it's nice to ask the author first.

**Comment by ria-19** [comment]
Okay, thank you.

**Comment by rajpratyush** [comment]
@jklymak Can you tell me where the file to be changed are located?

**Comment by story645** [comment]
@rajpratyush unless a core developer happens to know off hand, it'll take them about as long to dig into the docs to find it as it would take you. One method though of finding the right file is running 'git grep' on your local version of the repo w/ some words that are specific to the example.

**Comment by ArnuldOnData** [comment]
@rajpratyush Whole of the process and how-to, for contributing your code, is explained here:

https://matplotlib.org/stable/devel/index.html

**Comment by rajpratyush** [comment]
Sure @story645 Lemme look for it. Thanks for assistance
