### ISSUE TITLE
How to multiply sequence by non int . Error

### ISSUE THREAD

**Issue by adityat9083** [matplotlib/matplotlib#19675]
![IMG_20210310_024818](https://user-images.githubusercontent.com/79998790/110540791-edad7e80-814c-11eb-874e-72dc2f6217d8.jpg)
![IMG_20210310_024828](https://user-images.githubusercontent.com/79998790/110540809-f2723280-814c-11eb-9740-2396482e4827.jpg)

**Comment by timhoffm** [comment]
This is not a matplotlib issue. You're trying to multiply a pure python list by a float.

With a minimal effort of narrowing down the error, you should have been able to realize that. Please investigate your errors more carefully before posting to issue trackers. Also posting screenshots of code is bad practice, you should create a minimal example instead and post that as code. Creating such lazy and thoughtless issues waste valuable developer time!
