### ISSUE TITLE
Matplotlib plots lose transparency when saving as pdf

### ISSUE THREAD

**Issue by mnissov** [matplotlib/matplotlib#19672]
### Bug report

**Bug summary**
Saving a plot using `fig.savefig()` with the argument `transparent=True` produces a plot without transparency if saved as `pdf`, this works for `svg` and `png`.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2*np.pi)
y = np.cos(x)

fig, ax = plt.subplots(figsize=(10,6))
ax.plot(x, y, '--')

fig.savefig('example.pdf', transparent=True, bbox_inches='tight')
fig.savefig('example.svg', transparent=True, bbox_inches='tight')
```

**Matplotlib version**

  * Operating system: Linux - EndeavourOS
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.9.2
  * Jupyter version (if applicable): 
  * Other libraries: 

Matplotlib installed using conda
```bash
[morten@endeavour ~]$ conda list | grep matplotlib
matplotlib                3.3.4            py39hf3d152e_0    conda-forge
matplotlib-base           3.3.4            py39h62a2d02_0 
```

**Comment by jklymak** [comment]
I think the file is transparent, just most PDF viewers add a white background.  In Adobe Acrobat if you toggle Preferences:Page Display:Show Transparency Grid  you will see that your PDF is indeed transparent, whereas if you use Transparent=False you will not.  
<img width="437" alt="trans" src="https://user-images.githubusercontent.com/1562854/110492688-462a4080-80a7-11eb-9874-20ff05886ce2.png">

**Comment by mnissov** [comment]
I had tried adding it to a powerpoint and it blocked the background, maybe it's something else then
