### ISSUE TITLE
Canvas reset after using zoom and adding line

### ISSUE THREAD

**Issue by Stassels** [matplotlib/matplotlib#19684]
### Bug report

When I create plot in qt, use zoom tool and then add another line, view limit resets. But when I create plot, use pan tool and then add another line, ax limits does not reset. 

**Code for reproduction**

```python

import sys
import numpy as np
from PySide2 import QtWidgets
from matplotlib.backends.backend_qt5agg import (
    FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure

class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self._main = QtWidgets.QWidget()
        self.setCentralWidget(self._main)
        layout = QtWidgets.QVBoxLayout(self._main)

        canvas = FigureCanvas(Figure(constrained_layout=True))
        layout.addWidget(canvas)
        layout.addWidget(NavigationToolbar(canvas, self._main))
        button = QtWidgets.QPushButton('Click me')
        layout.addWidget(button)
        button.clicked.connect(self.add_line)

        self.ax = canvas.figure.subplots(1,1)

        x = np.arange(0,4*np.pi,0.1)
        y = np.sin(x)
        self.ax.plot(x,y)
        canvas.draw_idle()

    def add_line(self):
        x = np.arange(-8,4*np.pi,0.05)
        y = np.cos(x)
        self.ax.plot(x,y)
        self.ax.figure.canvas.draw_idle()

if __name__ == "__main__":
    qapp = QtWidgets.QApplication(sys.argv)
    app = ApplicationWindow()
    app.show()
    app.activateWindow()
    app.raise_()
    qapp.exec_()




```

**Expected behavior**
After using zoom tool and adding new line, ax limits should be preserved. I can't think why it behaves differently than pan tool, so I am reporting it as bug, but maybe it's a feature.

**Matplotlib version**

  * Operating system: Ubuntu 18.04.5 LTS
  * Matplotlib version: 3.3.4
  * Matplotlib backend: Qt5Agg
  * Python version: Python 3.8
  * PySide2 version: 5.15.2

**Comment by timhoffm** [comment]
By default `ax.plot(x,y)` scales the view to show all newly added data. If you want to prevent changing the view, pass the keyword arguments `scalex=False, scaley=False`.
