### ISSUE TITLE
License doc cleanup

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#19687]
- We have the license text twice:
  - `docs/user/license.rst` includes `|version|` in multiple places. It says specifically "License agreement for matplotlib |version|".
  - `LICENSE/LICENSE` only states "License agreement for matplotlib versions 1.3.0 and later"
  IMO we should only have one license text.
- We have extensive coverage for pre-1.3.0 copyright and license in https://matplotlib.org/stable/users/license.html. Do we have to provide that information at all? If we have to, would it be sufficient to "For copyright and license of matplotlib prior to version 1.3.0 see https://matplotlib.org/1.3.0/users/license.html".

**Comment by rajpratyush** [comment]
@timhoffm Can I take up this issue?

**Comment by rajpratyush** [comment]
@timhoffm few queries here.  though do we have to keep both the files license or not ? if we have to keep one then which one

**Comment by timhoffm** [comment]
I don't have the background to decide what can/cannot be done about the licenses.

**Comment by rajpratyush** [comment]
@timhoffm then whom should I consult for rectifying this issue

**Comment by timhoffm** [comment]
@rajpratyush thanks for your interest. However, I don't think you can contribute here. The difficult part is finding out what we want to/have to do. This is something we have to disucuss among core devs.

**Comment by rajpratyush** [comment]
@timhoffm no issues
