### ISSUE TITLE
pgf baseline images are OS-dependent

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19682]
### Describe the issue

**Summary**

https://github.com/matplotlib/matplotlib/pull/19255 seems to now be blocked on the fact that pgf baseline images that work on ubuntu 16.04 do not work on ubuntu 20.04, likely because some parts of texlive changed their outputs between the two releases.

In fact I have seen the same problem locally -- I have (since a long time ago) been unable to get the pgf tests to pass locally (arch or fedora, self-installed texlive), getting image comparison errors.

### Proposed fix

TBD

Some notes:
We could remove text from the baseline images, and move text testing to separate tests.  Looks like pdflatex's text output can be checked directly by parsing the pdf with pikepdf, but that's not the case for xelatex and lualatex (due to font charmap intricacies).  lualatex's text output, OTOH, could perhaps by tested using https://github.com/Josef-Friedrich/nodetree (which seems to come by default e.g. in texlive-luatex), or more simply something like http://wiki.luatex.org/index.php/Traversing_TeX_nodes.

Another solution would be to use *dvi* output (for the text tests), which is possible also for both xetex (`xelatex -no-pdf`) and luatex (`dvilualatex`), slightly expand matplotlib.dviread to parse xetex-dvi and luatex-dvi as well, and test these outputs.

**Comment by QuLogic** [comment]
We don't have `ubuntu-16.04` any more. I think I might have fixed this for latest Ubuntu and Fedora in #25068.
