### ISSUE TITLE
 option for removing bounding box when saving as SVG with plt.savefig("file.svg")

### ISSUE THREAD

**Issue by ithinkido** [matplotlib/matplotlib#19698]
### Problem
When saving to svg, plt creates a bounding box. There is an option for setting this to transparent, but as svg format still recognises this as a path, it is not the same as bounding-box = None

### Proposed Solution

Add the option Bbox= True or False
### Additional context and prior art

This is how Matplotlib renders the result:
![image](https://user-images.githubusercontent.com/52834821/111035721-f8516780-841b-11eb-9785-2e239ae5ca68.png)
but this is what is actualy generated.
![image](https://user-images.githubusercontent.com/52834821/111035753-26cf4280-841c-11eb-9aa3-82b66b9b2917.png)
the current SVG still has the bounding box path ( although it is set to transparent) 
-->

**Comment by jklymak** [comment]
The boundingbox is the size of the canvas.  Will any viewers actually load it with no boundingbox?   A quick google search indicates Latex at least will not.

**Comment by ithinkido** [comment]
> 
> 
> The boundingbox is the size of the canvas. Will any viewers actually load it with no boundingbox? A quick google search indicates Latex at least will not.

As this is a valid path, ALL svg viewers will load it, however , it is (at best) transparent. This does not mean it is not there.

**Comment by jklymak** [comment]
Sorry I meant will viewers load an svg with no boundingbox?

**Comment by ithinkido** [comment]
> 
> 
> Sorry I meant will viewers load an svg with no boundingbox?
I would say yes, this is the same svg , but instaed of using boundingbox, (which is a path)
` 
<path d="M 0 345.6 
L 460.8 345.6 
L 460.8 0 
L 0 0 
z
" style="fill:none;"/`

you could use view box

`
 viewBox="0 0 460.8 345.6"
   width="460.8pt"
`
which would be the correct page definition and not a path
At the moment the bounding box method is "forcing " a page pize by existing. It would be better to simply define the page size.
[testw_bounding_box.zip](https://github.com/matplotlib/matplotlib/files/6135165/testw_bounding_box.zip)
[test_view_box.zip](https://github.com/matplotlib/matplotlib/files/6135166/test_view_box.zip)

**Comment by QuLogic** [comment]
What exactly is the code you are using to produce this svg?

**Comment by ithinkido** [comment]
I am processing an image using skimage and using Matplotlib to show and save the svg.
`plt.axis('off')`   
`plt.box(False)`    
`plt.savefig("test.svg", bbox_inches ="tight")`    
`plt.show()`    

[scribbleLines.zip](https://github.com/matplotlib/matplotlib/files/6149612/scribbleLines.zip)

**Comment by anntzer** [comment]
@ithinkido Is what you want actually `gcf().patch.set_visible(False)`? (from your examples, it looks like you're perhaps actually trying to get rid of the figure patch, rather than the bounding box?)

**Comment by ithinkido** [comment]
> 
> 
> @ithinkido Is what you want actually `gcf().patch.set_visible(False)`? (from your examples, it looks like you're perhaps actually trying to get rid of the figure patch, rather than the bounding box?)

Yes, that works perfectly. Thanks
