### ISSUE TITLE
path.sketch doesn't apply to PolyCollection

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#19693]
### Bug report

**Bug summary**
PolyCollection lines aren't affected by changes to the path.sketch rcparam, even though patches 
are-the docs say that polycollection defaults to patch RC params
![image](https://user-images.githubusercontent.com/1300499/110989164-7ab82980-833f-11eb-848a-0325e828974e.png)

**Code for reproduction**
```python
import numpy as np

import matplotlib.collections as mcollections
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from matplotlib import rcParams


rcParams['path.sketch'] = (.5, 25, 20)

fig, (ax1, ax2) = plt.subplots(ncols=2)
f1 = mpatches.Rectangle((.25,.25), .5, .5, facecolor='white', edgecolor='C0', linewidth=2)
ax1.add_patch(f1)

verts = np.array([[[1,-1], [1,1], [2.4, 1.5], [2.4, -.5]],
                 [[-.4,1.5],[-.4,-.5],[1,-1],[1,1]],
                 [[-.4, 1.5], [1, 2],[2.4, 1.5], [1,1]]])
verts2 = verts*.25 + [.3]
p = mcollections.PolyCollection(np.vstack([verts, verts2]), facecolor='white', edgecolor='C0', linewidth=2)
ax2.add_collection(p)
```

**Matplotlib version**
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): jupyter inline

**Comment by oscargus** [comment]
It seems to be an issue with the rendering as `p.get_sketch_params()` returns the correct value.

**Comment by oscargus** [comment]
It also seems to be an issue with the agg-backend. Saving as PDF or SVG gives the correct result.

Btw, is it expected that the rightmost spine should have a bit of blue? This is consistent over all formats.
