### ISSUE TITLE
DLL load failed while importing ft2font - V S Code

### ISSUE THREAD

**Issue by akrsrivastava** [matplotlib/matplotlib#19692]
### Bug report

**ImportError: DLL load failed while importing ft2font: The specified module could not be found.
Happens only in Visual Studio Code. Runs OK in Jupyter Lab**

**Code for reproduction**

```python
import matplotlib
#
#
```

**Actual outcome**

```
ImportError: DLL load failed while importing ft2font: The specified module could not be found.
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): :matplotlib-3.3.4-py38haa95532_0
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 3.8.5
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by miab44** [comment]
I am experiencing the same issue, where VSCode doesn't allow import of matplotlib, but it works in Jupyter Lab.

Still have not found a resolution.

**Comment by tacaswell** [comment]
Please make sure that you have selected the right environment / interpreter / kernel in vscode.  The most reliable way to check if the Python you are using the Python you think you are using is:

```python
import sys
print(sys.executable)
```

I'm going to close this issue as I think this is a vscode configuration or installation issue.  I suggest reaching out to their support channels or starting a discussion at https://discourse.matplotlib.org

**Comment by miab44** [comment]
Thanks @tacaswell . You made me realize that it probably deals with vscode itself. I resolved this issue by installing the extension: "Python Extension Pack" on vscode. Now, all matplotlib related modules work. ...you were correct, this should be closed because it is not actually a matplotlib issue :)
