### ISSUE TITLE
Setting pickradius regression in 3.4.0rc

### ISSUE THREAD

**Issue by ericpre** [matplotlib/matplotlib#19700]
### Bug report

**Bug summary**

The pickradius doesn't seem to be set in matplotlib 3.4.0rc, while this is working fine in 3.3.4.
Using ``axline.set_pickradius(value)`` works fine.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

def pick_handler(event):
    print('picked')

fig, ax = plt.subplots()
plt.plot([0, 1, 2])
fig.canvas.mpl_connect('pick_event', pick_handler)

value = 15
axline = plt.axhline(y=1, color="red", pickradius=value, picker=True)
```

**Actual outcome**

The pickradius should be set in the call of `plt.axhline`.

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by QuLogic** [comment]
This came from 02376324b2604c32a2753ad07add3086ffd872f9, #19336

**Comment by QuLogic** [comment]
Going back to before a2de5bbe3437e19c2886cf481b8a53e714a1ae51 (which is what the above commit reverts), it didn't use to work either.

**Comment by QuLogic** [comment]
When it was deprecated, there was a `bool` check added, but reverting dropped that. I suppose we should add that back in, since people are relying on it now.

**Comment by ericpre** [comment]
Thanks!
