### ISSUE TITLE
MEP29

### ISSUE THREAD

**Issue by MihaiAnton** [matplotlib/matplotlib#19708]
### Problem

One serious problem is how to deal with text having both latex and html-like tags. [MEP29](https://matplotlib.org/stable/devel/MEP/MEP29.html)

### Proposed Solution

This MEP proposes to add lightweight markup to the text artist.

### Additional context and prior art

Using different size/color/family in a text annotation is difficult because the text method accepts argument for size/color/family/weight/etc. that are used for the whole text. But, if one wants, for example, to have different colors, one has to look at the gallery where one such example is provided: http://matplotlib.org/examples/text_labels_and_annotations/rainbow_text.html

This example takes a list of strings as well as a list of colors which makes it cumbersome to use. An alternative would be to use a restricted set of pango-like markup and to interpret this markup.

**Comment by QuLogic** [comment]
I don't understand this issue; why did you just copy out the MEP?

**Comment by MihaiAnton** [comment]
Hi @QuLogic . We are a team of 4 students from [TU Delft](https://www.tudelft.nl/en/) and want to implement this MEP, thus we created this issue to start with. Should we just reference the MEP without adding the description, which is, indeed, the one from the MEP?

**Comment by QuLogic** [comment]
If you complete some work on this, just open a PR? I don't see any need to duplicate the information in a MEP and an issue.
