### ISSUE TITLE
Notebook plotting regression in 3.4.0rc*

### ISSUE THREAD

**Issue by ericpre** [matplotlib/matplotlib#19701]
### Bug report

**Bug summary**

Blitting support have been added in the notebook backend, however, it is fully working, see https://github.com/matplotlib/matplotlib/issues/19633 and in particular https://github.com/matplotlib/matplotlib/issues/19633#issuecomment-795966581.

This breaks plotting for libraries using the `supports_blit` property of the canvas to know if [blitting should be used](https://github.com/hyperspy/hyperspy/blob/5cd76133ae408d50e573d4bf6cf903b03fd8efb1/hyperspy/drawing/figure.py#L59). 

Even if I am really looking forward using blitting in the notebook/ipympl backend, in 3.4.0rc, it seems that this is not ready to be fully used and it breaks plotting in the notebook of hyperspy.
Would it be make sense to have `supports_blit` returns `False` for the notebook backend until blitting is working fine?

**Code for reproduction**

It is difficult to provide a minimum example because of https://github.com/matplotlib/matplotlib/issues/19633#issuecomment-795966581 but it can be reproduce using hyperspy:

```python
# Paste your code here
%matplotlib notebook
import hyperspy.api as hs

s = hs.datasets.artificial_data.get_core_loss_eels_line_scan_signal()
s.plot()
```
**Actual outcome**

![notebook_blitting](https://user-images.githubusercontent.com/11851990/111069015-fe4e5380-84c2-11eb-837d-8d3476f2b9bb.jpg)

Similarly ss reported in by @ianhi in #19633, this will use 100% of a CPU. Also, the width of the figure is not correct and the axes disappear when changing the size of the figure:
![notebook_blitting-resize](https://user-images.githubusercontent.com/11851990/111069361-9bf65280-84c4-11eb-9b94-f81a80f6b130.jpg)

**Expected outcome**

Using blitting should work as with other backend, until then, blitting should not be defined as supported for the notebook/ipympl backend.

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by tacaswell** [comment]
I agree we need to back off claiming nbagg supports blitting (so we can get 3.4.0 out the door), hopefully this is simple but detail oriented fix in the book keeping in nbagg and we can have this cleared up for 3.4.1.

**Comment by ericpre** [comment]
Thanks, I feel less worried now!
