### ISSUE TITLE
Sphinx copy button is overflowing outside the code snippet

### ISSUE THREAD

**Issue by rajpratyush** [matplotlib/matplotlib#19710]
### Problem
The copy button generated by the sphinx copy button extension is outside the code snippet.
![Screenshot (705)](https://user-images.githubusercontent.com/53184883/111165570-33db6580-85c5-11eb-84d4-e7f7b13f2df2.png)

### Suggested Improvement

**Matplotlib version**

  * Operating system:
  * Matplotlib version: (`import matplotlib; print(matplotlib.__version__)`)
  * Matplotlib documentation version: (is listed under the logo)

**Comment by jklymak** [comment]
That comes in from https://github.com/executablebooks/sphinx-copybutton  The overlap doesn't bother me, but you can probably fix via css somehow

**Comment by timhoffm** [comment]
I've already provided a fix upstream: https://github.com/executablebooks/sphinx-copybutton/pull/104

We have to wait for the next release of sphinx-copybutton.
