### ISSUE TITLE
Some API reference pages have no "examples using this" section, even though they are explicitly listed by some examples

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19715]
### Problem

The `examples/showcase/bachelors_degree_by_gender.py` example explicitly lists `matplotlib.artist.Artist.set_visible` in its "The use of the following functions, methods, classes and modules 
is shown in this example" block, but https://matplotlib.org/devdocs/api/_as_gen/matplotlib.artist.Artist.set_visible.html#matplotlib.artist.Artist.set_visible currently has no "Examples using set_visible" block.

### Suggested Improvement

**Matplotlib version**

  * Operating system:
  * Matplotlib version: (`import matplotlib; print(matplotlib.__version__)`)
  * Matplotlib documentation version: (is listed under the logo) 3.3.4.post2588

**Comment by timhoffm** [comment]
This is likely an issue of sphinx-gallery.

**Comment by anntzer** [comment]
Seems fixed?
