### ISSUE TITLE
Creating Virtual environment Docs is Depreciated

### ISSUE THREAD

**Issue by rajpratyush** [matplotlib/matplotlib#19729]
### Problem
Creating a dedicated environment for setting up Matplotlib for development needs to be updated 
https://matplotlib.org/devdocs/devel/development_setup.html#installing-for-devs

### Suggested Improvement
https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/
as per this website the process to create a virtual environment is different 

**Matplotlib version**

  * Operating system: any
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):
  * Matplotlib documentation version (is listed under the logo):

**Comment by tacaswell** [comment]
I think we match https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment  to use `python -m venv /path/to/env`?

If you put the env in the cwd (which is pretty standard in application development) or out of the tree (I think more common in library development) is a matter of taste.

**Comment by rajpratyush** [comment]
i was mentioning about the second code snippet whenever i tried running the activate.bat it failed to create. @tacaswell and using the exact instructions as per website then only my the virtual environment could be created.

**Comment by timhoffm** [comment]
I cannot follow. When I create a venv, the scripts folder contains `activate.bat` and `activate`.

Interestingly, both work. Does this run on the linux subsystem for windows?

The recommendation for `activate` also on windows is at least 4 years old:
https://github.com/pypa/packaging.python.org/blame/main/source/guides/installing-using-pip-and-virtual-environments.rst#L145

**Comment by rajpratyush** [comment]
I dont have a reference but i have attched a screenshot where activate .bat wasn't working for windows so i just propose to divide it for linux mac and windows subsystems

**Comment by rajpratyush** [comment]
I dont have a reference but i have attached a screenshot where activate .bat wasn't working for windows so i just propose to divide it for linux mac and windows subsystems

**Comment by anntzer** [comment]
Please provide such a screenshot.

**Comment by QuLogic** [comment]
This doesn't seem actionable without a response.
