### ISSUE TITLE
head size of FancyArrowPatch is "invisibly small" by default

### ISSUE THREAD

**Issue by grahamgower** [matplotlib/matplotlib#19721]
### Problem

The [`FancyArrowPatch`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html)  docs give the (mistaken) impression that the arrow will have display coords with `head_length=0.4`, `head_width=0.2`. However this cannot be the case, because with the default values FancyArrowPatch just produces a line (the arrow head is too small to be visible).

```python
import matplotlib
import matplotlib.pyplot as plt

fap = matplotlib.patches.FancyArrowPatch(
    (10, 10),
    (20, 20),
)
_, ax = plt.subplots()
ax.add_patch(fap)
ax.autoscale_view()
ax.set_title(f"matplotlib {matplotlib.__version__}")
plt.show()
```
![arrow-is-line](https://user-images.githubusercontent.com/8665077/111445304-92aaf700-870b-11eb-9219-aefed9400687.png)

Compounding the problem, it's not clear what coordinate space is in use for the various [`ArrowStyle`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.ArrowStyle.html) attributes (hint: it's not the data coords either). After some frustration, I discovered the most useful way to obtain a visible arrow head is to increase the FancyArrrowPatch's `mutation_scale`.

```python
import matplotlib
import matplotlib.pyplot as plt

fap = matplotlib.patches.FancyArrowPatch(
    (10, 10),
    (20, 20),
    mutation_scale=50,
)
_, ax = plt.subplots()
ax.add_patch(fap)
ax.autoscale_view()
ax.set_title(f"matplotlib {matplotlib.__version__}")
plt.show()
```
![arrow-is-arrow](https://user-images.githubusercontent.com/8665077/111445331-99396e80-870b-11eb-8ec5-1edba42d4c8c.png)

### Suggested Improvement

Presumably this can't be fixed due to a desire for backwards compatibility. But the default behaviour is confusing. A note in the docs suggesting that the arrow head won't be visible with the default parameters would be helpful (and perhaps a suggestion to increase `mutation_scale`). More specific information about what coordinate space is being used would be a bonus.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version 3.3.4
  * Matplotlib documentation version 3.3.4

**Comment by marbled-toast** [comment]
A pull request is in progress.
