### ISSUE TITLE
The examples are not useful for people that want to plot real data instead of numpy functions.

### ISSUE THREAD

**Issue by crogersarvr** [matplotlib/matplotlib#19720]

**Comment by jklymak** [comment]
Numpy arrays are numpy arrays, whether they come from functions or data.  Maybe you can provide more detail.

**Comment by story645** [comment]
As Jody said, the examples in the gallery for the most part lean into standard scientific data analysis techniques. There are generally few real world case studies in the docs because they carry a heavy maintenance cost, but there are some examples in the blog https://matplotlib.org/matplotblog/
And as Jody said, if you provide more detail on what you mean by real world, there might be space to create or clarify an example.

**Comment by WeatherGod** [comment]
I had gotten a similar complaint once about one of my matplotlib tutorials.
In discussing it with the person, it seemed like what they either thought
that the data sources (and the means to load them) were important for
plotting, or that they felt like they were missing something by there not
being demonstrations on how to load up data. The person was new to python
and the scipy ecosystem at the time, so they were trying to jump into it
all with my tutorial and the numpy tutorial. They had not taken one of the
other tutorials yet that would have shown how to deal with data loading and
saving, so they didn't know that there was more to learn still that is
orthogonal to matplotlib plotting.

Not exactly sure how to address this sort of mindset, as I would think that
it would be susceptible to overfitting to specific mechanisms of data
loading as well.

**Comment by story645** [comment]
Yeah, I'm hoping #19703 might make it clearer what structure each plot expects & that may make it easier to apply to folks specific use cases.
In theory I agree that more real world use cases would be good, but there are so many data containers and each domain specific library does its own thing and the "library everyone uses" changes so often that I question the practicality of anything except a sort of user contributed external repo/blog approach.

**Comment by tacaswell** [comment]
Closing this as it is not really clear what we can do to make this better. 

At the end of the day our APIs expect array-like inputs no matter how you get a hold of them.
