### ISSUE TITLE
Specify Colors with RGB as copied from a color picker with [0-255] interval

### ISSUE THREAD

**Issue by blaylockbk** [matplotlib/matplotlib#19737]
According to the [matplotlib docs](https://matplotlib.org/stable/tutorials/colors/colors.html), you can specify colors as an RGB "tuple of float values in closed interval [0, 1] (e.g., (0.1, 0.2, 0.5) or (0.1, 0.2, 0.5, 0.3))".

This is a limitation to users because color picker tools give RGB values as integers from [0-255]

Copying an RGB color from [W3 schools color picker](https://www.w3schools.com/colors/colors_picker.asp)
![image](https://user-images.githubusercontent.com/6249613/111672032-c4d55b00-87d6-11eb-9bdf-e9248bfdf9d5.png)

Copying RGB color from Google Color Picker
![image](https://user-images.githubusercontent.com/6249613/111673960-bdaf4c80-87d8-11eb-9683-1c19b3af7823.png)

Copying RGB from VS code color picker
![image](https://user-images.githubusercontent.com/6249613/111672086-d454a400-87d6-11eb-82fc-eec88e09ad6e.png)

When I copy an RGB color value from a color picker, it is a bit cumbersome that I need to convert it to a numpy array and then divide by 255 to get the RGB values in the [0-1] interval. Instead, I would like to the use RGB values in the form they are copied from color picker tools. 

**Could matplotlib add the ability to also accept a tuple of values [0-255] as an acceptable color?**

## The current method to use RGB values copied from a color picker
```python
import matplotlib.pyplot as plt
RGB = (37, 240, 10)
RGB = np.array(RGB)/255
plt.plot([1,2,3], color=RGB)
```
## What I would like to do
```python
import matplotlib.pyplot as plt
plt.plot([1,2,3], color=(39, 82, 224))       # <--  ValueError: RGBA values should be within 0-1 range
```

Note: alpha values would still be a decimal, `(39, 82, 224, 0.45)`

**Comment by jklymak** [comment]
Thanks for the suggestion.  However when you pass `color=(0.5, 0.5, 0.5)` how would we know which convention you were converting from?  Also, we do take hex colors (see https://matplotlib.org/stable/tutorials/colors/colors.html).  I'm going to close as won't fix because I don't think its possible to do this and remain backwards compatible...

**Comment by tacaswell** [comment]
This is a reasonable request, but it leads to the issue of how we can (robustly) tell if the user meant to give us ints in [0,255] on floats in [0, 1].

Type checking is plausible, but then should we explode for `(1.0, 20, 35)` and what do we do with `(1, 1, 1)` vs `(1.0, 1, 1)`?  If we look at value ranges, then that still leaves `(1, 1, 1)` as ambiguous!

I think the proposal of mixed int-for-RGB, float-for-A would be extremely confusing as it would make the rules for deciding how to interpret even more complex.

In 2/3 of those screen shots you also have the hex values which we do take as colors already.
