### ISSUE TITLE
Problem with imshow when using masked data.

### ISSUE THREAD

**Issue by RafaelCarlquist** [matplotlib/matplotlib#19738]
Hello everyone,

I am having some trouble using imshow to plot images that have masked data. It looks like a sample problem when plotting the data. The code works fine with matplotlib 2.2.5 but breaks with versions 3.3.4 and 3.3.2.

I was not able to reproduce the problem with artificial data. I've saved some data to reproduce the problem as .txt:

[numpy_raster.txt](https://github.com/matplotlib/matplotlib/files/6166273/numpy_raster.txt)

## Code:

```
import numpy as np
import numpy.ma as ma
from numpy import genfromtxt
import matplotlib.pyplot as plt

data = genfromtxt('numpy_raster.csv', delimiter=',') # loading data

data_masked = ma.masked_values(data, -1) # masking data for value equals -1

fig, ax = plt.subplots(1,1,figsize=(8,8)) # plot data
ax.imshow(data_masked, cmap='viridis')
plt.show()
```

## Results

The correct result for version 2.2.5 is:

![image](https://user-images.githubusercontent.com/32001527/111670506-ab440b80-87f6-11eb-8c88-06f398c1d4e0.png)

This is the expected result. I've checked with other libraries in different languages.

The wrong result for version 3.3.4 and 3.3.2 is:

![image](https://user-images.githubusercontent.com/32001527/111670866-17267400-87f7-11eb-871a-5dd6b70a03b8.png)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: As noted above 2.2.5 works fine but 3.3.2 and 3.3.4 do not work
  * Matplotlib backend: module://ipykernel.pylab.backend_inline 
  * Python version: 3.8

This problem happens installing matplotlib via conda and/or pip.

Thank you all, 

Best,

Rafael

**Comment by timhoffm** [comment]
The defaults for interpolation changed at some point. Interpolation including NaN values will result in a pixel to be NaN if any of the values taking part in the interpolation of that pixel is none.

Use `ax.imshow(data_masked, cmap='viridis', interpolation='none')` to get the old behavior.

**Comment by RafaelCarlquist** [comment]
Thank you very much for the answer.
