### ISSUE TITLE
points to data coordinates

### ISSUE THREAD

**Issue by marnec** [matplotlib/matplotlib#19747]
### Problem

In the [transform tutorial](https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html), section: 'Data coordinates', there is no reference to how to transform data from points to data coordinates and despite days of researching I can't wrap my head around it.

### Suggested Improvement
Since in the code snippet of that section the 'offset points' coordindate system is used, it would be extremely useful to know how to convert from points to data coordinates.

**Matplotlib version**

  * Operating system: ubuntu18
  * Matplotlib version 3.3.4:
  * Matplotlib documentation version 3.3.4:

**Comment by jklymak** [comment]
I think you just want fig.dpi_scale_trans.  The conversion from inches to points is a factor of 72.  I'll close but feel free to discuss at discourse.Matplotlib.org.
