### ISSUE TITLE
Overlay created by `Axes.indicate_inset_zoom` does not adjust when changing inset ranges

### ISSUE THREAD

**Issue by pulkin** [matplotlib/matplotlib#19768]
`Axes.indicate_inset_zoom` just creates a static overlay which does not adjust when inset axes ranges are changed. Additional calls to `Axes.indicate_inset_zoom` will create new overlays. It is expected that the result of this
```python
ax.indicate_inset_zoom(ax_inset)
ax_inset.set_xlim(new_lim)
```
and this
```python
ax_inset.set_xlim(new_lim)
ax.indicate_inset_zoom(ax_inset)
```
are exactly the same.

**Comment by jklymak** [comment]
That would be a new feature, and I guess would require a callback.  The indicators are indeed quite static.

**Comment by QuLogic** [comment]
In order to implement this, I think we will have to add an `InsetIndicator` sort of container that can manage everything. This could also take care of pan/zoom on the original Axes as well.
