### ISSUE TITLE
get contour auto label coordinates

### ISSUE THREAD

**Issue by friedrichknuth** [matplotlib/matplotlib#19773]
Is it possible to easily access the automatically determined contour label coordinates?

Contour example from [the documentation](https://matplotlib.org/stable/gallery/images_contours_and_fields/contour_demo.html)

```
import matplotlib
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2

fig, ax = plt.subplots()
CS = ax.contour(X, Y, Z)
CS_labels = x.clabel(CS, inline=True, fontsize=10)
ax.set_title('Simplest default with labels')
```

### Proposed Solution

I would like to do something like:

`label_locations = CS_labels.label_coords` 

where   `label_locations` is an array of (x,y) coordinates for each automatically determined label. It would be helpful to have access to this auto-determined set and modify manually as needed, especially when dealing with labels in [geospatial coordinates](https://scitools.org.uk/cartopy/docs/latest/gallery/contour_labels.html).

### Additional context

Related to https://github.com/matplotlib/matplotlib/issues/613

Also asked on [stackoverflow](https://stackoverflow.com/questions/66807997/get-matplotlib-cartopy-contour-auto-label-coordinates)

**Comment by jklymak** [comment]
Does `CS_labels[0].get_position()` not work?

**Comment by friedrichknuth** [comment]
Excellent - thank you! This works in matplotlib, but not in cartopy. 

From [their example](https://scitools.org.uk/cartopy/docs/latest/gallery/contour_labels.html)

```
CS_labels = ax.clabel(
    line_c,  # Typically best results when labelling line contours.
    colors=['black'],
    manual=False,  # Automatic placement vs manual placement.
    inline=True,  # Cut the line where the label will be placed.
    fmt=' {:.0f} '.format,  # Labes as integers, with some extra space.
)
```

returns `'NoneType'` for `CS_labels` so `CS_labels[0].get_position()` cannot be accessed. I will ask the question there.
