### ISSUE TITLE
Marker sizes in Axes3D scatter plot are changing all the time

### ISSUE THREAD

**Issue by OliverLew** [matplotlib/matplotlib#19787]
### Bug report

**Bug summary**

The marker sizes that specified with `s=` argument in `scatter` function are wrong, and even worse, the markers are changing their sizes every time the plot is re-rendered (panning or resizing). It seems that the sizes are randomly reassigned to these markers.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()

# matplotlib 3.4
ax = Axes3D(fig, auto_add_to_figure=False)
fig.add_axes(ax)
# matplotlib 3.3.4
# Axes3D(fig)

x = np.random.rand(200)
y = np.random.rand(200)
z = np.random.rand(200)
ax.scatter(x, y, z, s=x*50)

plt.show()
```

**Actual outcome**

https://user-images.githubusercontent.com/12032219/112714930-df66ad00-8f17-11eb-8800-292ac7cf4e02.mp4

**Expected outcome**

As shown in the screen recording, the sizes are correct and not changing. `matplotlib` was 3.3.4 in the following example.

https://user-images.githubusercontent.com/12032219/112715101-6cf6cc80-8f19-11eb-963a-4fc1d9b6e40f.mp4

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.9.2
  * Jupyter version (if applicable): Not using it
  * Other libraries: numpy 1.20.1

I installed both python, numpy and matplotlib with `pacman` package manager from Arch's official repository.

**Comment by jklymak** [comment]
This bisects to e6d9cbb5a4b1fc14f  (https://github.com/matplotlib/matplotlib/pull/18189)  Ping @tacaswell.

**Comment by tacaswell** [comment]
Well, that is quite bad.

Thank you for the bisect @jklymak Looking at this now.

**Comment by tacaswell** [comment]
The issue is that when we re-compute the 3D projection we resort the values based on their depth from the viewer (so markers "in the back" do not render "in the front").  We have a bunch of logic to make sure that the colors also track, but we need the same logic to be added to the size.

if you add color to this example you see that they keep their colors even if their sizes jump around.

```python

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()

# matplotlib 3.4
ax = Axes3D(fig, auto_add_to_figure=False)
fig.add_axes(ax)
# matplotlib 3.3.4
# Axes3D(fig)

x = np.random.rand(200)
y = np.random.rand(200)
z = np.random.rand(200)
ax.scatter(x, y, z, s=x*50, c=x**2)

plt.show()
```

**Comment by tacaswell** [comment]
Attn @QuLogic This appears to be super broken.

I have been testing with:

```python
th = np.linspace(0, 2*np.pi*6, 2000)

x = np.sin(th)
y = np.cos(th)
z = th
sc = ax.scatter(x, y, z, s=(5 + th), c=th**2)
```

which has both a color and size structure I can predict what should be.

**Comment by tacaswell** [comment]
The color mapping was broken by 4c3d6449249a9e4790865f2a7e825be591581958 via https://github.com/matplotlib/matplotlib/pull/18480 

There are enough coupled changes here (both to the mplot3d code and the colors),  I do not think this is something we are going to be able to revert our way out of.

**Comment by tacaswell** [comment]
```python

import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure()



try:
    # matplotlib 3.4
    ax = Axes3D(fig, auto_add_to_figure=False)
    fig.add_axes(ax)
except AttributeError:
    # matplotlib 3.3.4
    ax = Axes3D(fig)
    if ax not in fig.axes:
        fig.add_axes(ax)

th = np.linspace(0, 2*np.pi*6, 2000)

x = np.sin(th)
y = np.cos(th)
z = th
sc = ax.scatter(x, y, z, s=(5 + th), c=th**2)
fig.savefig('/tmp/a.png')
fig.savefig('/tmp/b.png')
plt.show()

```

OK, figured out why this passed tests (at least as far as the size goes, the first render is right!):

![a](https://user-images.githubusercontent.com/199813/112767975-9ed66480-8fe7-11eb-857e-ce4e7c747ae6.png)

![b](https://user-images.githubusercontent.com/199813/112767986-ac8bea00-8fe7-11eb-84bc-b08d60ed4115.png)

It also looks like all of our tests with 3D scatter than do not have fixed color are using the figure comparison method so they are wrong together and we missed the color regression :disappointed: .

**Comment by tacaswell** [comment]
## v3.3.4
![a](https://user-images.githubusercontent.com/199813/112889983-5335c080-90a4-11eb-9b4f-bd1c926e2f70.png)

## #19812

![a](https://user-images.githubusercontent.com/199813/112890129-7b252400-90a4-11eb-8257-dc3de3382f52.png)

**Comment by tacaswell** [comment]
```python
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib as mpl

fig = plt.figure()


try:
    # matplotlib 3.4
    ax = Axes3D(fig, auto_add_to_figure=False)
    fig.add_axes(ax)
except AttributeError:
    # matplotlib 3.3.4
    ax = Axes3D(fig)
    if ax not in fig.axes:
        fig.add_axes(ax)

th = np.linspace(0, 2 * np.pi * 6, 2000)

x = np.sin(th)
y = np.cos(th)
z = th
sc = ax.scatter(x, y, z, s=(1 + th * 5), c=th ** 2)
fig.suptitle(mpl.__version__)
fig.savefig("/tmp/a.png", bbox_inches="tight")
fig.savefig("/tmp/b.png")
fig.savefig("/tmp/c.png")
plt.show()

```
