### ISSUE TITLE
[BUG] Agg Backend doesn't call `close_event`

### ISSUE THREAD

**Issue by alexrockhill** [matplotlib/matplotlib#19792]
### Bug report

Other backends properly call the close event, but it seems there is an issue with `Agg` specific to 3.4.

```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')

def _close(event):
    print(event)


fig, ax = plt.subplots()
fig.canvas.mpl_connect('close_event', _close)
plt.close(fig)

matplotlib.use('Qt5Agg')
fig, ax = plt.subplots()
fig.canvas.mpl_connect('close_event', _close)
plt.close(fig)
```

**Actual outcome**

No call to close for `Agg`.

**Expected outcome**

Calls from both backends with print outputs.

**Matplotlib version**
  * Operating system: All
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: ~3.8
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by alexrockhill** [comment]
https://github.com/mne-tools/mne-python/pull/9201

**Comment by anntzer** [comment]
Is this specific to 3.4?  https://github.com/matplotlib/matplotlib/issues/18609 already discussed this at length, but that was in 3.3.

**Comment by alexrockhill** [comment]
Huh, some tests started failing related to this after the change to 3.4 but I just checked and it was in 3.3 so I better check to see what actually changed. Thanks for the comment.
