### ISSUE TITLE
If the y values are close 1, they plot as 0

### ISSUE THREAD

**Issue by ondrejch** [matplotlib/matplotlib#19802]
### Bug report

**Bug summary**

If the y values are close 1, they plot as near 0 instead of near 1.

**Code for reproduction**

```python

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [1.0, 1.000000000000031, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013, 1.0000000000000013]

fig = plt.plot(x, y, color='black', linewidth=2)
plt.savefig('test.pdf', bbox_inches='tight')
```

**Actual outcome**

Line near y=0
```
# If applicable, paste the console output here
#
#
```

**Expected outcome**
Line near y=1

**Matplotlib version**

  * Operating system: 
 Linux Centos 8, Ubuntu 20.04
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
3.3.0, 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
Qt5Agg
  * Python version: 3.6.8, 3.8.5
  * Jupyter version (if applicable): 
  * Other libraries: 

Linux distribution packages.

**Comment by jklymak** [comment]
There is an "offset" of one that should be indicated on the axes.  Feel free to discuss further, but I will close.
