### ISSUE TITLE
[proposal] split QT backend to standalone project under matplotlib umbrella

### ISSUE THREAD

**Issue by congzhangzh** [matplotlib/matplotlib#19804]
### Problem

QT backend is hard to use, especially for QT have two python binding(Qt for Python and PyQt) and the official binding is even fast involved(QT5/Qt6, QML)

this make how to embedded it be hard work, like what should I do if,

1. I use Qt for Python 5/Qt for Python
2. I use PyQt5/PyQt6
3. I mix(with my upstream package) PyQt/Qt for Python
3. the Operating System/Conda upstream mismatch with my own version

### Proposed Solution

Split Qt Version/Python Binding to a different subproject, and these project evolution themselves.

for the user side, the user chooses what they need, all these is pay for what you need. code is easy to unstand and maintains
 
### Additional context and prior art

1. migration to new qt version/qt binding will be an easy action, if the qt upstream has a breaking change, and the downstream try to keep compitable, that will be very hard to do, you need a new abstraction to fix these problems. 
2. the user code will be as easy as https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_qt_sgskip.html , and the maintainer's work should be easy now,  done by the different community and keep with upstream.

A super mini implement base on many brilliant user, https://github.com/medlab/matplotlibqml 

But I think if matploitlib upstream maintenance these projects will be a more heath way, or these weekend projects will be sure die some week's later.

**Comment by congzhangzh** [comment]
@anntzer @ericpre hi, hope to get your advice here :)

Tks,
Cong

**Comment by anntzer** [comment]
I think you should feel free to publish a fork of the qt backends similar to matplotlibqml if you want (e.g. for qt6 support now, I guess?), but given that it's effectively the default backend for most users, we'll want to keep on shipping our own.

**Comment by ericpre** [comment]
@congzhangzh, I don't think I can advise on this, you may have tagged the wrong person!

**Comment by jklymak** [comment]
Yeah, I'll close this.  Of course anyone is welcome to fork whatever they want.  However, there is no plan to stop shipping the backend ourselves.
