### ISSUE TITLE
Issue with pcolormesh with shared DateTime x-axis

### ISSUE THREAD

**Issue by Woutah** [matplotlib/matplotlib#19808]
### Bug report

I came across an issue when creating a sublot with a pcolormesh and a shared datetime x-axis. I believe this to have something to do with the tick format, although I'm not sure... 

The intention of the code below is to visualize the classes for each time-period. This seems to work only if the formatting of the two x-axes correspond. The issue can toggled by (un)commenting the line with the "<---(Un)Comment this line to reproduce issue"-comment. Also see: https://imgur.com/a/egZwn5J

**Code for reproduction**

```python
import pandas as pd
from datetime import datetime, timezone
from matplotlib import cm
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D
from matplotlib.dates import date2num 
import matplotlib.dates as mdates

def bar(df, ax, color_column): 
        classes = df[color_column].unique() #get all classes
        colors = cm.rainbow(np.linspace(0,1,len(classes))) #get new color for each one
        dt_pred_arr = df[["DateTime", color_column]].to_numpy()

        X = []
        Y = []
        Z = []

        for idx, (dt, pred) in enumerate(dt_pred_arr): 
            if pred in classes: #For predicted classes
                X.append(dt)
                Y.append(0)
                Z.append(int(np.where(classes==pred)[0])) #class index
 
        cMap = matplotlib.colors.ListedColormap(colors) #Color map (use Z to map colors)

        Z = [np.array(Z)[:-1], np.array(Z)[:-1]]
        ax.pcolormesh(X, [0, 1], Z, cmap=cMap, shading='flat')
        legend_colors = [Line2D([0], [0], color=color, lw=4) for color in colors]
        ax.legend(legend_colors, classes, loc='lower center', bbox_to_anchor=(0.5, -1.4), ncol = len(classes))


data = [
    (datetime(2020, 1, 11, 10, tzinfo=timezone.utc), 5,1, "Class1"),
    (datetime(2020, 1, 11, 11, tzinfo=timezone.utc), 5,4, "Class2"),
    (datetime(2020, 1, 11, 12, tzinfo=timezone.utc), 5,4, "Class2"),
    (datetime(2020, 1, 11, 13, tzinfo=timezone.utc), 2,7, "Class5"),
    (datetime(2020, 1, 11, 14, tzinfo=timezone.utc), 2,1, "Class5"),
    (datetime(2020, 1, 11, 15, tzinfo=timezone.utc), 5,9, "Class1"), 
    #(datetime(2020, 1, 11, 15, tzinfo=timezone.utc), 5,9, "Class1")  #<-----------------(Un)comment this line to reproduce issue
]


df = pd.DataFrame(data=data, columns=["DateTime", "Value1","Value2", "Class"])
fig, ax = plt.subplots(2, sharex=True, gridspec_kw={'height_ratios': [5, 1]})
df[["DateTime", "Value1", "Value2"]].plot(x="DateTime", ax=ax[0])
bar(df, ax=ax[1], color_column="Class")
plt.show()
```

**Expected vs actual outcome**

https://imgur.com/a/egZwn5J

**Matplotlib version**

  * Operating system: Win10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.7
  * Other libraries: Pandas

**Comment by jklymak** [comment]
If possible, can you reproduce this without pandas, and make it as simple as possible?  There is a lot of extraneous info here and you will get someone to look at it sooner if it is simplified.

**Comment by Woutah** [comment]
Thank you for your response. As you suggested, I removed the dependence on pandas, this seems to fix the issue. 

This is probably something I'd have to report to pandas instead, since it relates to df.plot() (maybe an issue with Datetime vs timestamp, which is used by pandas?), so I will be closing this issue.

**Comment by jklymak** [comment]
Yeah, matplotlib handling of datetimes and pandas datetime have subtle differences.  Please do open with pandas, and ping us if there is something matplotlib should be doing to improve the interaction here.  Thanks!
