### ISSUE TITLE
Month names not set as text when using usetex

### ISSUE THREAD

**Issue by maxnoe** [matplotlib/matplotlib#19836]
### Bug report

From the image in the release notes for matplotlib 3.4 here:
https://matplotlib.org/stable/users/whats_new.html#date-formatters-now-respect-usetex-rcparam

The dateformatter does not use text mode for the month names but sets them like `$Aug$`. Which is bad typography, since it will be typeset as the mathematical expression `A * u * g`, not the text `Aug`.

**Comment by smartlixx** [comment]
If amsmath's `\text` is not introduced in the near future, we can modify `_wrap_in_tex` function to differentiate alphabets and other characters, leaving alphabets out from `\mathdefault`.  This way is a little clumsy, but it works. A PR can be open with this approach.

**Comment by tacaswell** [comment]
@maxnoe Was this a change from 3.3?
