### ISSUE TITLE
Subclasses of Polygon with numpydoc xref throws error b/c of CapStyle, JoinStyle

### ISSUE THREAD

**Issue by nstarman** [matplotlib/matplotlib#19839]
### Problem

The sphinx links to `CapStyle`  and `JoinStyle` in v3.4.0 are relative to the file, so a subclass of `matplotlib.patches.Patch` in a package with numpydoc xref (https://numpydoc.readthedocs.io/en/latest/install.html) turned on cannot link to the objects and errors with.
```WARNING: py:obj reference target not found: CapStyle```
```WARNING: py:obj reference target not found: JoinStyle```

https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch.set_capstyle
https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch.set_joinstyle

```
   @docstring.interpd
    def set_capstyle(self, s):
        """
        Set the `.CapStyle`.

        Parameters
        ----------
        s : `.CapStyle` or %(CapStyle)s
        """
        cs = CapStyle(s)
        self._capstyle = cs
        self.stale = True
```

**Edit:**

The problem also appears to involve ``Patches.__init__``. I can monkey-patch a fix with 

```
Polygon.__init__.__doc__ = Polygon.__init__.__doc__.replace(
    "`.CapStyle`", "``matplotlib._enums.CapStyle``")
Polygon.__init__.__doc__ = Polygon.__init__.__doc__.replace(
    "`.JoinStyle`", "``matplotlib._enums.JoinStyle``")
Polygon.set_capstyle.__doc__ = Polygon.set_capstyle.__doc__.replace(
    "`.CapStyle`", "``matplotlib._enums.CapStyle``")
Polygon.set_joinstyle.__doc__ = Polygon.set_joinstyle.__doc__.replace(
    "`.JoinStyle`", "``matplotlib._enums.JoinStyle``")
```

### Suggested Improvement

* This line could be be changed to say
```
   @docstring.interpd
    def set_capstyle(self, s):
        """
        Set the `~matplotlib._enums.CapStyle`.

        Parameters
        ----------
        s : `~matplotlib._enums.CapStyle` or %(CapStyle)s
        """
        cs = CapStyle(s)
        self._capstyle = cs
        self.stale = True
```

**Matplotlib version**

  * Operating system: Big Sur & Ubuntu
  * Matplotlib version 3.4.0
  * Matplotlib documentation version (is listed under the logo): 3.4.0

**Comment by timhoffm** [comment]
The use of private modules is a workaround. The classes themselves are not public, but the concepts they describe are. We need a location to document these concepts and the simplest solution is with the classes that represent these concepts. There are other ways to solve this as I've proposed in #18544, but that would require additional machinery and was not appreciated in that discussion.

as for the xref thing, I do not fully understand where the warning is coming from and need to have a closer look.

**Comment by nstarman** [comment]
As far as I can tell, the xref issue stems from the fact that references to `CapStyle` and `JoinStyle` are relative paths, not absolute. I've found for other references in Astropy that changing `` `.object` `` to `` `~package.subpackage.object` `` resolves the issue

**Comment by pllim** [comment]
Circling back here... The patch suggested above did get around the ReadTheDocs "fail on warning" problem; see #11466 though you still see those warnings in the log but they somehow not blocking RTD check. FYI 🤷

**Comment by anntzer** [comment]
I think this may be related to https://github.com/sphinx-doc/sphinx/issues/6211 (which I basically opened based on my experience with matplotlib)?

**Comment by anntzer** [comment]
I am bit confused why this specific dotted reference breaks your build whereas a lot of other dotted references (e.g. `.Transform`) don't?

**Comment by pllim** [comment]
@anntzer , these are the warnings (it breaks because we have RTD set to fail on warning):

```
MatplotlibDeprecationWarning:
The validCap attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  return getattr(obj, attr, *defargs)
```
```
MatplotlibDeprecationWarning:
The validJoin attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  return getattr(obj, attr, *defargs)
```

The code in `astropy` does not specifically have them, but rather a subclass inherited them. And then Sphinx tries to render docstring for inherited attributes. We also use `sphinx-automodapi` plugin to render it. So, it is really a perfect storm of a few things put together.

References: astropy/astropy#11458 astropy/sphinx-automodapi#125

**Comment by timhoffm** [comment]
I'm now confused: Are you breaking because of the deprecation warnings or because of "reference target not found" in the first comment above?

**Comment by pllim** [comment]
Ah, not really. I was redirected to this issue from #19850 . I specifically speaking about the `MatplotlibDeprecationWarning`. I don't know what the "reference target not found" issue is about but I think @nstarman found a fix.

**Comment by nstarman** [comment]
Originally it was both, but we monkey-patched a solution to the "reference target not found" error by editing the matplotlib docstrings before subclassing Polygon.

**Comment by nstarman** [comment]
It is presumably still an error if the monkey-patch is removed.

**Comment by timhoffm** [comment]
In the dev call today, we decided to replace the types (specifically CapStyle) by plain references, i.e.

```
s : `.CapStyle` or %(CapStyle)s
```
to
```
s : CapStyle_ or %(CapStyle)s
```

These should be resolved via intersphinx so that the monkey-patching becomes obsolete.

The deprecation warning is a separate topic, I'll reopen #19850.

**Comment by pllim** [comment]
@nstarman , suggestion from https://github.com/matplotlib/matplotlib/issues/19850#issuecomment-816227976 is a no-go, so I think the monkeypatch is there to stay until `astropy` can bump minversion of matplotlib to the version that has removed the deprecated attributes. FYI.

**Comment by timhoffm** [comment]
@pllim @nstarman AFAICT these two issues are completely unrelated.

The planned change here (https://github.com/matplotlib/matplotlib/issues/19839#issuecomment-816207094) should make the monkey-patching obsolete.

**Comment by pllim** [comment]
I can't say I understand what's going on either. RTD passes with the monkey patch. Maybe the warning is red herring after all. 🤷🏻‍♀️

**Comment by jklymak** [comment]
I can't tell from the above if this is still an issue.  I would guess not, so I'll close, but feel free to request a re-open with the current state of things.

**Comment by pllim** [comment]
We still have the hack in the code but no time to revisit.

* https://github.com/astropy/astropy/issues/11458

**Comment by jklymak** [comment]
Please open a new issue(s) if you still need help narrowing down the scope.
