### ISSUE TITLE
matplotlib version

### ISSUE THREAD

**Issue by aaastorrs** [matplotlib/matplotlib#19831]
### Bug report

**Bug summary**

Trying to install scipy with 
pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose --no-warn-script-location

Get error message ending with:
AttributeError: module 'matplotlib' has no attribute '__version__'

**Code for reproduction**

```python
%conda uninstall matplotlib
%pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose --no-warn-script-location
```

**Actual outcome**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Documents\Python_Scripts\startup.py in <module>
     15 from astropy.io.fits import getheader
     16 from astropy.io.fits import getdata
---> 17 from astropy.visualization import (MinMaxInterval, SqrtStretch, ImageNormalize)
     18 # conda config --add channels http://ssb.stsci.edu/astroconda

~\Anaconda3\lib\site-packages\astropy\visualization\__init__.py in <module>
      4 from .interval import *
      5 from .mpl_normalize import *
----> 6 from .mpl_style import *
      7 from .stretch import *
      8 from .transform import *

~\Anaconda3\lib\site-packages\astropy\visualization\mpl_style.py in <module>
      9 
     10 # This returns False if matplotlib cannot be imported
---> 11 MATPLOTLIB = minversion('matplotlib', __minimum_matplotlib_version__)
     12 
     13 

~\Anaconda3\lib\site-packages\astropy\utils\introspection.py in minversion(module, version, inclusive, version_path)
    141 
    142     if '.' not in version_path:
--> 143         have_version = getattr(module, version_path)
    144     else:
    145         have_version = resolve_name(module.__name__, version_path)

AttributeError: module 'matplotlib' has no attribute '__version__'
```

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by WeatherGod** [comment]
You seem to have a python startup script that executes every time python is
started. This startup script is setting things up for astropy, which is
unrelated to what is being installed. matplotlib isn't installed yet at
this point, so it can't even find matplotlib let alone the "missing"
attribute.

**Comment by WeatherGod** [comment]
I seriously doubt it is ever even hitting any of the packages' setup.py. Looking at the traceback, astropy is involved, but astropy is not one of the packages being installed (or even a dependency of any of these). The only way astropy got involved is through a python startup file, as clued by the name of the file at the start of the traceback.

**Comment by WeatherGod** [comment]
Btw, the use of `--user` is a trick to have some "global" packages across conda environments. It sort of works, but you need to be real careful about it.

**Comment by jklymak** [comment]
I'll close but feel free to discuss further at discourse.matplotlib.org.

**Comment by aaastorrs** [comment]
Thanks very much! Things are perking now...
Alex
