### ISSUE TITLE
collection with alpha + colorer

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#19843]
### Bug report

**Bug summary**

The newest version of matplotlib supports non-constant alpha values for collections, which is awesome. Unfortunately it seems that it breaks when used in combination with a colorbar

**Code for reproduction**

The code here works fine if either line with `#ALPHA` or `#CBAR` is commented out, but it breaks if they're both active
```python
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import numpy as np

fig, ax = plt.subplots()

x1 = x2 = x3 = np.linspace(0, 1, 10)
alpha = np.clip((1 - x3), 0.1, 1)

points = np.array([x1, x2]).T.reshape(-1, 1, 2)
segments = np.concatenate([points[:-1], points[1:]], axis=1)

lc = LineCollection(
    segments,
    lw=10,
    alpha=alpha,      # ALPHA
)
line = ax.add_collection(lc)

fig.colorbar(line)    # CBAR
```

**Actual outcome**

```
ValueError: Data array shape, (256,) is incompatible with alpha array shape, (10,). This can 
occur with the deprecated behavior of the "flat" shading option, in which a row and/or column
of the data array is dropped.
...
AttributeError: 'NoneType' object has no attribute 'reshape'
```

**Expected outcome**

I guess the most intuitive behaviour would be that the colobar ignored the alpha parameter altogether, but that might create api inconsistencies because it looks like it works fine with constant values. (modulo that the collection object has be processed with e.g. `line.set_array(x1)`).

If no universally satisfying behaviour can be implemented, I guess the error that pops up should at least acknowledge what the real issue is.

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.9.1
  * Jupyter version (if applicable): NA
  * Other libraries: 

I installed matplotlib using pip

**Comment by QuLogic** [comment]
cc @efiring

**Comment by dflowcodes** [comment]
My partner and I are taking a look at this for a School project, let me know if you have any objections!

**Comment by efiring** [comment]
@dflowcodes Go for it!  Keep us posted.  This looks like something we will want to find a clean fix for ASAP. I hope it will turn out to be reasonably simple.  I haven't looked.
