### ISSUE TITLE
Axes.bar_label(...) Not Working: axes has no attribute

### ISSUE THREAD

**Issue by DavidD003** [matplotlib/matplotlib#19840]
### Bug report

**Bug summary**

The code presented in the documentation at : https://matplotlib.org/stable/gallery/lines_bars_and_markers/horizontal_barchart_distribution.html
does not work, it gives an AttributeError. I experience this on collab as well as my PC

See the above doc for code to reproduce

```
AttributeError: 'AxesSubplot' object has no attribute 'bar_label'
```

**Expected outcome**
See the linked docs

**Matplotlib version**
MatPlotlib 3.3.2
  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend :  Qt5Agg
  * Python version: 3.8.5
  * Jupyter version: whatever Colab is using

**Comment by jklymak** [comment]
That is a 3.4 feature.

**Comment by DavidD003** [comment]
> That is a 3.4 feature.
I've been trying to install Matplotlib 3.4.1 through Anaconda but I can't figure it out. I've tried looking at anaconda and Conda documentation. Help much appreciated in getting access to this latest version of matplotlib
