### ISSUE TITLE
matplotlib 3.4.0 bug with 3D scatter plots and array of different marker sizes

### ISSUE THREAD

**Issue by demconpeter** [matplotlib/matplotlib#19844]
On Windows 10 with matplotlib 3.4.0, when using the mouse to manually rotate a 3D scatter plot with an array of different marker sizes, all marker sizes vary visibly, by a lot. Although I encountered this problem with my own code, the very same problem can be shown with the public example https://likegeeks.com/3d-plotting-in-python/#Plot_markers_of_varying_size 

Reverting to matplotlib 3.3.1 fixes the problem, proving that it is a new bug in matplotlib 3.4.0.

Thanks

**Comment by jklymak** [comment]
Yes, this was a major bug, that is now fixed in 3.4.1 Sorry for the bother...
