### ISSUE TITLE
imshow with LogNorm and large data ranges: pixelation and crashes

### ISSUE THREAD

**Issue by chrishavlin** [matplotlib/matplotlib#19851]
### Bug report

**Bug summary**

Using `imshow` with `LogNorm` scaling and a large range results in pixelation and crashes. This is related to Issue #18415 but the fix that went in there doesn't seem to be general enough.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

data = np.full((500, 500), 1e30, dtype=np.float64)
data[0:250, :] = 1e12

fig, ax = plt.subplots()
im = ax.imshow(data, norm=LogNorm())
plt.colorbar(im)
plt.show()
```

Results in 

![Screenshot from 2021-04-02 11-59-57](https://user-images.githubusercontent.com/22038879/113436808-00614f00-93ab-11eb-9e22-6fbe887b3404.png)

**Expected outcome**

Outcome should be similar to the case with a slightly smaller data range:

```python
data = np.full((500, 500), 1e30, dtype=np.float64)
data[0:250, :] = 1e13

fig, ax = plt.subplots()
im = ax.imshow(np.log10(data))
plt.colorbar(im)
plt.show()
```

![Screenshot from 2021-04-02 12-04-12](https://user-images.githubusercontent.com/22038879/113437067-8f6e6700-93ab-11eb-90c3-af5abc0e9f28.png)

An additional manifestation of this bug that causes a crash is when the data contains a zero point, the `vmin` rescaling still results in a 0 value even when setting `vmin`: 

```python
data = np.full((500, 500), 1e30, dtype=np.float64)
data[0:250, :] = 1e12
data[0,0] = 0.

fig, ax = plt.subplots()
im = ax.imshow(data, norm=LogNorm(vmin=1e12, vmax=1e30))
plt.show()
```

results in 

```
~/.pyenv/versions/3.8.0/envs/sandbox/lib/python3.8/site-packages/matplotlib/colors.py in __call__(self, value, clip)
   1463             t_vmin, t_vmax = self._trf.transform([self.vmin, self.vmax])
   1464             if not np.isfinite([t_vmin, t_vmax]).all():
-> 1465                 raise ValueError("Invalid vmin or vmax")
   1466             t_value -= t_vmin
   1467             t_value /= (t_vmax - t_vmin)

ValueError: Invalid vmin or vmax
```

Using a smaller range for `vmin` and `vmax` avoids the error but results in a pixelated plot:

```python
data = np.full((500, 500), 1e30, dtype=np.float64)
data[0:250, :] = 1e12
data[0,0] = 0.

fig, ax = plt.subplots()
im = ax.imshow(data, norm=LogNorm(vmin=1e20, vmax=1e30))
plt.show()
```
![Screenshot from 2021-04-02 12-10-02](https://user-images.githubusercontent.com/22038879/113437517-600c2a00-93ac-11eb-89b0-ce0caf4a8af3.png)

**Matplotlib version**
matplotlib 3.4.1

**Comment by chrishavlin** [comment]
Oh, I should have searched the open issue more thoroughly -- I think #19748 and the related fix going in may cover the case here.

**Comment by jklymak** [comment]
yep!  Feel free to comment there!
