### ISSUE TITLE
Importing pyplot messes with command line argument parsing

### ISSUE THREAD

**Issue by Nikratio** [matplotlib/matplotlib#1986]
Consider this:

```
[0] nelarikon:~/tmp$ cat argparsebug.py
#!/usr/bin/env python

from __future__ import division, print_function, absolute_import
from argparse import ArgumentParser
import matplotlib
import matplotlib.pyplot as plt

parser = ArgumentParser()

parser.add_argument("--name", type=str, default=None,
                    help="Prefix for files to load")

options = parser.parse_args()
print('Name is %s' % repr(options.name))
print('matplotlib version:', matplotlib.__version__)
[0] nelarikon:~/tmp$ ./argparsebug.py --name foo
Name is None
matplotlib version: 1.2.0
```

Removing the `import matplotlib.pyplot as plt` line gives the correct output,
```
[0] nelarikon:~/tmp$ ./argparsebug.py --name foo
Name is 'foo'
matplotlib version: 1.2.0
```

**Comment by tacaswell** [comment]
Should this fall under the color overhaul 2.0 breaking changes?  

I am -0.5, am flagging it for discussion.

**Comment by efiring** [comment]
It seems like this needs to go through a deprecation cycle, unfortunately.  Maybe the thing to do right away is add some documentation, including a warning that it will go away.

**Comment by efiring** [comment]
This can no longer be reproduced, even on mpl 1.3.1, based on testing by @tacaswell.  Evidently it was fixed some time in the misty past.

**Comment by moonfriend** [comment]
I have this issue with matplotlib 3.1.0 on python3

**Comment by QuLogic** [comment]
There is no manipulation of `sys.argv` on 3.1.0.

**Comment by moonfriend** [comment]
Yes you are write probably on python2

`mo@m:~/tbin$ cat test_args.py
#!/usr/bin/env python2                                                                                         
# -*- coding: utf-8 -*-

import sys
import matplotlib.pyplot as plt

if __name__ == '__main__':
    print(sys.argv)
`
The result is different between python2 and python3
`moghimim@m-01124:~/tbin$ python2 ./test_args.py --name foo
['./test_args.py', '--name', 'foo']
moghimim@m-01124:~/tbin$ python3 ./test_args.py --name foo
['./test_args.py']
`
and it only happens for "--name" input argument
`moghimim@m-01124:~/tbin$ python3 ./test_args.py --namex foo
['./test_args.py', '--namex', 'foo']
`

my current versions of matplotlib:
`moghimim@m-01124:~/tbin$ python2 -c "import matplotlib;print(matplotlib.__version__)"
2.2.4
moghimim@m-01124:~/tbin$ python3 -c "import matplotlib;print(matplotlib.__version__)"
3.1.0
`
