### ISSUE TITLE
vmin and vmax have no effect for plot_surface()

### ISSUE THREAD

**Issue by johnomotani** [matplotlib/matplotlib#19870]
### Bug report

**Bug summary**

Passing `vmin` and `vmax` arguments to `plot_surface()` seems to have no effect. I expected these arguments to change the limits of the vertical scale.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np

data = np.random.rand(5,6)
y, x = np.meshgrid(np.arange(6), np.arange(5))

# no vmin, vmax
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface(x, y, data)

# try to use vmin, vmax
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface(x, y, data, vmin=-10.0, vmax=10.0)

plt.show()
```

**Actual outcome**

Plot without `vmin`/`vmax`
![no_vmin_vmax](https://user-images.githubusercontent.com/3958036/113601674-8abee280-9639-11eb-9c35-fbb4b3f5aef8.png)

Plot trying to set `vmin`/`vmax`
![with_vmin_vmax](https://user-images.githubusercontent.com/3958036/113601711-97dbd180-9639-11eb-937d-35f6684220c5.png)

**Expected outcome**

Expected the two plots to be different, with the second having an expanded vertical axis.

**Matplotlib version**

  * Operating system: Linux Mint 20.1 Cinnamon
  * Matplotlib version 3.4.1
  * Matplotlib backend: Qt5Agg
  * Python version: 3.8.6
  * Other libraries: numpy-1.20.2

Installed from conda (conda-forge channel).

**Comment by jklymak** [comment]
Vmin and vmax are fro the colormapping, they do not affect the zlim.  I'll close but feel free to discuss at discourse.Matplotlib.org.
