### ISSUE TITLE
Add "copy to clipboard" to the Toolbar

### ISSUE THREAD

**Issue by ryggyr** [matplotlib/matplotlib#1987]
Wishlist: a "copy image to clipboard" button in the Toolbar for interactive backends.

For the wx backend, I've had some success with adding such a button by altering the function matplotlib.backends.NavigationToolbar2Wx._init_toolbar() in backend_wx.py so that the last line:

```
self.Realize()
```

is replaced by:

```
    _NTB2_COPY = wx.NewId()
    self.AddSimpleTool(_NTB2_COPY, _load_bitmap('stock_up.xpm'),
                        'Copy', 'Copy plot image to clipboard') 
    bind(self, wx.EVT_TOOL, self.copy, id=_NTB2_COPY) 

    self.Realize()

def copy(self, evt):
    self.canvas.Copy_to_Clipboard(event=evt) # bmp image
```

**Comment by fariza** [comment]
For reference, the GTK3 tool that allows to copy the canvas to the clipboard is

```
class CopyToolGTK3(ToolBase):
    '''Copy canvas to clipboard'''
    default_keymap = 'ctrl+c'
    description = 'Copy canvas'

    def trigger(self, *args, **kwargs):
        clipboard = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
        window = self.figure.canvas.get_window()
        x, y, width, height = window.get_geometry()
        pb = Gdk.pixbuf_get_from_window(window, x, y, width, height)
        clipboard.set_image(pb)
```

The idea is to get the same for all the backends, and then include it as default.

**Comment by thomasaarholt** [comment]
Could I bring this back from the silence? This would still be useful.

**Comment by fariza** [comment]
@thomasaarholt yes indeed this is useful.
The reason I didn't add it as default tool is... (I'm ashamed) is because I wasn't able to get it to work with Tkinter :blush: . 

The default tools have to be available in all the backends. At this moment the Toolmanager is working with Gtk3 and Tkinter, so if we want this to be added, we have to make Tkinter's version.

If you can help out and get it to work with Tkinter, then we can add it, and in that way, we force all other backends to have it also (when they are being ported).

**Comment by thomasaarholt** [comment]
@fariza, I am only just beginning to get to know Python as a developer, and in the writing-up stage of my PhD. :) (It was due to the last bit that I realised that it might be a useful feature) After I've finished my thesis, I'd love to take a look!

**Comment by marcwell** [comment]
If I may cast a vote, as a (former, at least for now) Matlab user I would also find this feature extremely useful.

As of now I right click the toolbar of the Qt4 backend, uncheck the checkbox to hide the toolbar and use ksnapshot to grab a snapshot of the window region. Of course having a button would make everything faster :)

**Comment by fariza** [comment]
@marcwell as I said before, I am waiting for volunteers to implement the tool for other backends. So far I have only Gtk3

**Comment by smcinerney** [comment]
and StackOverflow post https://stackoverflow.com/questions/3571117/customizing-matplotlib-image-display-to-add-copy-paste

**Comment by fariza** [comment]
I just started the work on the implementation, I need help for QT and TK... volunteers?

**Comment by timhoffm** [comment]
I could do the Qt part at some point. But not before in a month or so. So if someone else is quicker, go for it.

**Comment by jklymak** [comment]
#10446 is merged - I'll close this as done, but feel free to re-open if I'm misunderstanding....
