### ISSUE TITLE
Use SVG backend in documentation for sharper images

### ISSUE THREAD

**Issue by ma-sadeghi** [matplotlib/matplotlib#19880]
This is a random snippet from `matplotlib`'s documentation. As you can see, the figure is blurry. If you use SVG backend, they'll look much sharper and prettier.
![image](https://user-images.githubusercontent.com/14086031/113702119-16228d00-96a7-11eb-9c72-2c9147ff3d87.png)

**Comment by jklymak** [comment]
Agreed, except many figures would also need the rasterized=True option turned on for some artists

See also

**Comment by QuLogic** [comment]
We did switch to SVG once (#5677), but it had to be reverted due to bugs.
