### ISSUE TITLE
symlog is not in scale setting

### ISSUE THREAD

**Issue by currydai** [matplotlib/matplotlib#19906]
### Problem
when i use the toolbar ,i can find the symlog ,there just have linear,log,logit!

**Comment by jklymak** [comment]
Which toolbar do you mean?  `set_xscale('symlog')` definitely works..

**Comment by timhoffm** [comment]
Likely the figure options GUI dialog.

**Comment by currydai** [comment]
> 可能的图形选项GUI对话框。

This is exactly what I wanted and it worked. Thank you again for your work!
