### ISSUE TITLE
Selecting axes when customizing gives <anonymous AxesSubplot>

### ISSUE THREAD

**Issue by nafanh** [matplotlib/matplotlib#19929]
When you click the customize button in the figure and try to choose an individual subplot(axes), the names are <anonymous AxesSubplot>. Is there a way for the user to modify these names to something more descriptive? Thanks

![Screenshot 2021-04-10 000357](https://user-images.githubusercontent.com/29495707/114258982-4496b580-9990-11eb-9919-ca263ea4f1a2.png)

**Comment by nafanh** [comment]
I found a way to make it work by using matplotlib.axes.Axes.set_title method.
However, when I added the parameter 'loc = right' , it still shows as <anonymous AxesSubplot>
For example:
```
ax[i, j].set_title('Time', fontsize=8, loc='right')
```
gives the above output. Is there a reason for this? thanks again.

**Comment by timhoffm** [comment]
Currently, the 'right' title is not checked for the axes selection. More specifically, the titles are constructed here

https://github.com/matplotlib/matplotlib/blob/ccd368cdff56308ebf9eb073ef4a851db63036c5/lib/matplotlib/backends/backend_qt5.py#L696

which gives you a full idea of the elements checked and priorities for generating that name.
