### ISSUE TITLE
Add image guidelines for third party package page 

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#19945]
This should be added to the "how to add to this page" paragraph on the third party package page.
- images should not be wider than 900px. Otherwise they will overflow the layout.
- run the image through an optimizer like  https://tinypng.com/ to save  bandwidth and repo size

**Comment by timhoffm** [comment]
I'm not pixel-perfect-sure on 900px. Might be a few more, but 900 is a good guideline.

Will this be affected by the migration to the pydata sphinx template?

**Comment by yashhd** [comment]
Hi. I want to contribute to this issue as this will be my first-ever contribution. I'm not able to find the third party package page on this repo. Could anyone of y'all help me with this? @story645 @timhoffm

**Comment by story645** [comment]
https://www.github.com/matplotlib/matplotlib/tree/master/doc%2Fthirdpartypackages

**Comment by jklymak** [comment]
Hold off on this since I think we agreed this page was going to be replaced by matplotlib/mpl-third-party

**Comment by yashhd** [comment]
I think I had visited this page but I couldn't find the "how to add to this page" paragraph here. @story645

**Comment by story645** [comment]
closing since that page is being phased out in favor of https://github.com/matplotlib/mpl-third-party which doesn't support images (yet?)
