### ISSUE TITLE
Subplots - Can't deactivate Minorticks 

### ISSUE THREAD

**Issue by nikchha** [matplotlib/matplotlib#19942]
### Bug report

**Bug summary**

Hi,

I am working on a plot with 10 subplots containing 3 axis each. Until today, Minorticks were never visible as I thought was the default behavior. However, when compiling again today, Minorticks appeared, and I cannot disable them again.
I tried: using `ax.minorticks_off()` on every axis, , using xticks with the `minor=False` keyword, setting the minor locator to NullLocator, and removing the matplotlib cache. Nothing works.

**Code for reproduction**

```python

```
EDIT: Standalone Example below

**Actual outcome**

-> Standalone Example below

```
# If applicable, paste the console output here
#
#
```
EDIT:  Standalone Example below
**Expected outcome**

Same plot but without minor ticks!

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'MacOSX'
  * Python version: 3.8.8
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Please create a self-contained and complete minimal example.  We can't run this and many of your objects are of unknown origin because you have not included your imports.  Thanks!

**Comment by nikchha** [comment]
Hi,

sorry for not providing a standalone example yesterday. Below you will find a reproducible Code for the problem. Also: Why does the major tick Locator not work properly when removing the spines with the rcParams?

**Code for Reproduction**
```python
%matplotlib inline
import matplotlib.pyplot as plt

X = [x for x in range(2003, 2021)]
Y = [y for y in range(20, 38)]

cols = 2
rows = 2

fig, ax = plt.subplots(
    ncols=cols, nrows=rows, sharey=True, sharex=True
)


plt.rcParams.update({"font.size": 5})
plt.rcParams["axes.spines.right"] = False
plt.rcParams["axes.spines.left"] = False
plt.rcParams["axes.spines.top"] = False
plt.rcParams["axes.spines.bottom"] = False


for col in range(cols):
    for row in range(rows):
        ax[col][row].minorticks_off()
        ax[col][row].bar(X, Y, color="gainsboro")
```

**Outcome**

![test](https://user-images.githubusercontent.com/37020365/114359722-8e3ff580-9b74-11eb-8f1e-a279b4478187.png)

**Comment by jklymak** [comment]
Sorry, I don't see any minor ticks in that plot?  I'm also not following your second question about the major locator not working.

**Comment by nikchha** [comment]
Sorry, I am fairly new to matplotlib. I thought the little strokes at each ytick and xtick are called minorticks. But if they are not minorticks - how do I deactivate them?

The second part is about the overlapping xticklabels. If I am not changing the rcParams, the Locator only uses every nth label to avoid overlapping.

**Comment by jklymak** [comment]
Let's move this discussion to discourse.Matplotlib.org.  Thanks for your understanding!
