### ISSUE TITLE
Add unit-testing capability for matplotlib objects

### ISSUE THREAD

**Issue by edmundsj** [matplotlib/matplotlib#19957]
### Problem

So I love unit tests - I write them all the time. They are incredibly useful. And I love matplotlib. Also incredibly useful. But as of right now, matplotlib does not support unit testing, and so ne'er the twain shall meet. I have several modules written which are responsible for generating particular types of plots, and I *want* to check that the figures generated are correct, according to some specification that I have of what they should contain (i.e. how many points, where they are, what the color/linestyle/legends are). What I *don't* want to do is check that two *images* are equivalent, because this requires actually generating images, using an excessive amount of memory for the purposes of a simple unit test.

The other 'big two' (numpy and pandas) both provide testing frameworks (functions such as ``np.testing.assert_equal`` and ``pd.testing.assert_frame_equal`` which I have found immensely useful. I want something similar for matplotlib.

### Proposed Solution

What I've currently done to get around this deficiency is write my own methods to compare two figures, ``assert_figures_equal``, which goes through and checks that all the ``Axes`` in that figure are equal, which itself checks that all the ``collections`` and ``lines`` in each ``Axes`` are equal, as well as the ``xticks``, ``yticks``, ``linetsyle`` and so on. Currently, it doesn't look through everything, but this is just because I haven't got around to it yet. I have personally found this functionality immensely useful in tetsing code based on matplotlib (does this code actually generate the figure that I want given that I feed it the correct data?), and they are in use in all of the modules that I have written which generate plots. As far as I can tell, a matplotlib ``figure`` has a finite number of objects, and it would be pretty easy to get through all of them quickly. In practice, I typically generate ~30 plots in the course of my unit testing and these tests don't take excessively long to finish. 

### Additional context and prior art

```
def assert_figures_equal(actual_fig, desired_fig, atol=1e-15, rtol=1e-10):
    actual_axes = actual_fig.axes
    desired_axes = desired_fig.axes
    for actual_ax, desired_ax in zip_longest(actual_axes, desired_axes):
        assert_axes_equal(actual_ax, desired_ax, atol=atol, rtol=rtol)

def assert_axes_equal(actual_ax, desired_ax, atol=1e-15, rtol=1e-10):
    """
    Asserts that two axes are equal
    """
    actual_lines = actual_ax.get_lines()
    desired_lines = desired_ax.get_lines()
    assert_equal(len(actual_lines), len(desired_lines),
            err_msg='Number of lines in Axes not equal')
    for actual_line, desired_line in zip_longest(actual_lines, desired_lines):
        assert_line_equal(actual_line, desired_line, atol=atol, rtol=rtol)

    actual_collections = actual_ax.collections
    desired_collections = desired_ax.collections
    for actual_collection, desired_collection in \
        zip_longest(actual_collections, desired_collections):
        assert_collection_equal(actual_collection, desired_collection,
                atol=atol, rtol=rtol)

    actual_xticks = actual_ax.get_xticks()
    actual_yticks = actual_ax.get_yticks()
    desired_xticks = desired_ax.get_xticks()
    desired_yticks = desired_ax.get_yticks()
    assert_array_equal(actual_xticks, desired_xticks, err_msg='xticks')
    assert_array_equal(actual_yticks, desired_yticks, err_msg='yticks')
    
    actual_xscale = actual_ax.get_xscale()
    actual_yscale = actual_ax.get_yscale()
    desired_xscale = desired_ax.get_xscale()
    desired_yscale = desired_ax.get_yscale()
    assert_equal(actual_xscale, desired_xscale, err_msg='xscale')
    assert_equal(actual_yscale, desired_yscale, err_msg='yscale')

    actual_xlabel = actual_ax.get_xlabel()
    actual_ylabel = actual_ax.get_ylabel()
    desired_xlabel = desired_ax.get_xlabel()
    desired_ylabel = desired_ax.get_ylabel()
    assert_equal(actual_xlabel, desired_xlabel, err_msg='xlabel')
    assert_equal(actual_ylabel, desired_ylabel, err_msg='ylabel')

def assert_line_equal(actual_line, desired_line, atol=1e-15, rtol=1e-10):
    """
    Check that two matplotlib lines are equal (have the same raw data)
    """
    actual_xdata = actual_line.get_xdata()
    actual_ydata = actual_line.get_ydata()
    desired_xdata = desired_line.get_xdata()
    desired_ydata = desired_line.get_ydata()
    assert_allclose(actual_xdata, desired_xdata,
            err_msg='xdata', atol=atol, rtol=rtol)
    assert_allclose(actual_ydata, desired_ydata,
            err_msg='ydata', atol=atol,rtol=rtol)

    actual_linewidth = actual_line.get_linewidth()
    desired_linewidth = desired_line.get_linewidth()
    assert_equal(actual_linewidth, desired_linewidth, err_msg='linewidth')

    actual_linestyle = actual_line.get_linestyle()
    desired_linestyle = desired_line.get_linestyle()
    assert_equal(actual_linestyle, desired_linestyle,
            err_msg='linestyle')

    actual_alpha = actual_line.get_alpha()
    desired_alpha = desired_line.get_alpha()
    assert_equal(actual_alpha, desired_alpha, err_msg='alpha')

def assert_collection_equal(actual_collection, desired_collection,
        atol=1e-15, rtol=1e-10):
    actual_points = actual_collection.get_offsets()
    desired_points = desired_collection.get_offsets()
    assert_allclose(actual_points, desired_points,
            atol=atol, rtol=rtol, err_msg='Scatter plot points')

```

**Comment by jklymak** [comment]
I don't understand how you create the "truth" in these tests.

**Comment by edmundsj** [comment]
By explicitly creating the desired figure, either with matplotlib's methods ``ax.plot()`` or directly by setting the attributes in the relevant ``Axes`` or ``Figure``.

So a full test script might look like:
```
desired_figure = Figure()
desired_axes = desired_figure.subplots()
desired_axes.plot([1, 2, 3, 6])

actual_figure = some_function_that_creates_a_figure(some_data)
assert_figures_equal(actual_figure, desired_figure)
```

**Comment by jklymak** [comment]
You could serialize the two figures and check that they were equal, but I doubt that the serialized objects would be smaller than a png or svg.  (I'm also not sure the serialized objects are the same - they may use unique ids for the objects). 

Anything else is going to be super leaky.  In the above, you assert that the collections are equal, but they could look radically different based on the other 50 collection attributes you haven't checked for.  I don't think there will be any appetite for querying every attribute and making sure they are equal all the way down the artists tree.  But maybe its easier than I think.

**Comment by anntzer** [comment]
Perhaps `check_figures_equal` is close enough to what you're looking for?

**Comment by anntzer** [comment]
I'll close this on the assumption that check_figures_equal is good enough; feel free to ping to reopen if not.
