### ISSUE TITLE
Annotation on figure object

### ISSUE THREAD

**Issue by cvanelteren** [matplotlib/matplotlib#19969]
# Background

Hi I am not sure if this is the correct space. I use mpl pretty much every day and I to get some input on a feature request I was thinking about. I have sometimes lots of figures layed out in the grid (which became extra easy with the new `subplot_mosaic` functionality) and I often writting some overhead to get general axis labels of annotations 
### Problem
In order to get general axes we may write something like

```python
layout = np.random.rand(3, 3).astype(object)
fig = plt.figure()
ax = fig.subplot_mosaic(layout)

for axi in ax.values():
    axi.imshow(np.random.rand(10, 10))
    


# overhead 
fig.subplots_adjust(hspace = .5)
maxi = fig.add_subplot(111,
                       frameon = 0,
                       xticks = [],
                       yticks = [],
                       )
for spine in "left top bottom right".split():
    maxi.spines[spine].set_visible(False)
maxi.set_xlabel("test x", labelpad = 25)
maxi.set_ylabel("test y", labelpad = 25)
fig.show()
```
![test](https://user-images.githubusercontent.com/19485143/114904143-d29ef000-9e17-11eb-94b0-094c210871db.png)
# Proposed solution
In the docs I can tell that the axes object is removed from figure. I would argue that it makes sense to add this functionality back in. We would then be able to write
```python
fig.set(xlabel = "test" ...)
fig.annotate()
```

**Comment by jklymak** [comment]
I think this is just `supxlabel` and `supylabel`: https://matplotlib.org/stable/gallery/subplots_axes_and_figures/figure_title.html

**Comment by cvanelteren** [comment]
ah! I was not aware of these function, many thanks ;-)!
