### ISSUE TITLE
CenteredNorm with halfrange raises exception when passed to imshow

### ISSUE THREAD

**Issue by marxide** [matplotlib/matplotlib#19972]
### Bug report

**Bug summary**

Passing a `CenteredNorm` instance with a set _halfrange_ to `imshow` _norm_ kwarg raises an exception.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib.colors import CenteredNorm
import numpy as np

data = np.random.random((100, 100))

fig, ax = plt.subplots()
im = ax.imshow(data, norm=CenteredNorm(halfrange=0.2))
fig.colorbar(im)
```

**Actual outcome**

```
AttributeError: 'CenteredNorm' object has no attribute 'vmax'
```

**Expected outcome**

An imshow plot with a colorbar clipped to [-0.2, 0.2].

I am currently working around this by using `TwoSlopeNorm` instead and forcing the two scales to be equal, i.e.

```python
TwoSlopeNorm(0, vmin=-0.2, vmax=0.2)
```

**Matplotlib version**

  * Operating system: macOS 11.2.3
  * Matplotlib version: 3.4.1 
  * Matplotlib backend: ipykernel.pylab.backend_inline
  * Python version: 3.8.8
  * Jupyter version (if applicable): 3.0.8

Installed with conda using the conda-forge channel.

**Comment by jklymak** [comment]
Thanks for the report.  @jpmattern I think you are the `CenteredNorm` guru?

**Comment by jpmattern** [comment]
Great to see that `CenteredNorm` is being used, I'll take a look at the error.

**Comment by jpmattern** [comment]
Created a pull request for the bugfix. Somewhat embarrassingly, all it took was to add a 
```
self.vmax = None
```
in the constructor (and a `self.vmin = None` just to be safe).
