### ISSUE TITLE
Mismatch between angle of arrows in "quiver" plot and lines drawn with "plot" for rectangular figure sizes

### ISSUE THREAD

**Issue by jzilly** [matplotlib/matplotlib#19985]
### Bug report

**Bug summary**
For rectangular figure sizes, the arrows drawn by the command "quiver" no longer point in the same directions of lines plotted using the "plot" command. For square figure sizes this mismatch does not appear. 

**Code for reproduction**

```python
# Rectangular example of mismatch between quiver angle and plt.plot angle
import matplotlib.pyplot as plt
import matplotlib

# ANGLE MISMATCH BETWEEN PLOT FROM (0,0) to (1,1) and arrows pointing in (1,1) direction
matplotlib.rcParams['figure.figsize'] = 8,6
plt.figure(1)
plt.plot([0, 1], [0, 1])
plt.quiver(0, 0, 1, 1)
plt.quiver(0.5, 0.5, 1, 1)
plt.quiver(1, 1, 1, 1)
plt.axis('off')

# WORKS CORRECTLY WITH SQUARE FIGSIZE
matplotlib.rcParams['figure.figsize'] = 6,6
plt.figure(2)
plt.plot([0, 1], [0, 1])
plt.quiver(0, 0, 1, 1)
plt.quiver(0.5, 0.5, 1, 1)
plt.quiver(1, 1, 1, 1)
plt.axis('off')
plt.show()



```

**Actual outcome**
[rectangular_mismatch.pdf](https://github.com/matplotlib/matplotlib/files/6325741/rectangular_mismatch.pdf)
[square_no_mismatch.pdf](https://github.com/matplotlib/matplotlib/files/6325742/square_no_mismatch.pdf)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

Ideally, the direction of arrows in quiver should adapt to the aspect ratio of the figures. Currently an arrow in (1,1) direction following a 45 degree angle keeps this exact angle even when the aspect ratio is changed. 
However this no longer corresponds to direction (1,1) for regular plotting such as done with the "plot" command. 

**Matplotlib version**
Operating system Mac OS 10.13.6
Python version 3.7.6
Matplotlib version 3.1.2
Matplotlib backend: MacOSX
Jupyter version 1.0.0 (reproduced also in jupyter notebook)
(When plotting with %matplotlib inline the default appears to be rectangular on the system I used and therefore has the same unaligned direction of arrows in quiver)

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries: 

Matplotlib is installed via pip
Python is installed via brew on Mac

**Comment by jklymak** [comment]
Quivers are drawn in data space.  For more discussion please use discourse.Matplotlib.org.  Thanks!

**Comment by tacaswell** [comment]
Also see the `angles` kwarg on `ax.quiver` https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver that controls how the `U,V` values are translated into angles.

I think you want to pass `angles='xy'`.

**Comment by jzilly** [comment]
Thank you! That explains it completely.
