### ISSUE TITLE
rename fig.draw_no_output

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20001]
https://github.com/matplotlib/matplotlib/pull/19968 introduced a no-output draw `fig.draw_no_output()` which does what `fig.canvas.draw()` does, but with presumably less side effects.  This change should be better reflected in the code base, tests, and docs.  

Good first issue, because there isn't really anything tricky here.  If someone takes it on, it may be preferable to take it on in stages so it is not a megalithic change.

**Comment by timhoffm** [comment]
I agree with https://github.com/matplotlib/matplotlib/pull/19968#pullrequestreview-637165882 that we should try to think of a better name before rolling this out everywhere.

**Comment by tacaswell** [comment]
Sorry if I jumped the gun on merging with this name

xref https://github.com/matplotlib/matplotlib/pull/19765#issuecomment-809411124

**Comment by jklymak** [comment]
I await a better name with bated breath!

**Comment by timhoffm** [comment]
Coming from https://github.com/matplotlib/matplotlib/pull/19968#pullrequestreview-637165882

> `draw` has basically grown to do "mean" two things:
> 
> 1) crawl the artist tree
> 2) actually do things involving the renderer

We'll get to the name when we can name those two things. I'm not quite sure what exactly 1 actually does, but that's the name we need. This needs somebody who knows exactly what is done internally. Might be it's `layout_artists`. Then we could say `draw` = `layout_artists` + `render`.

If nobody steps up, we can try to find the name jointly in the next dev call.

**Comment by jklymak** [comment]
The routine walks the artist tree and calls the `draw` method on every artist.  It just stops short of outputting the results to the renderer.

**Comment by story645** [comment]
I call the all put together but not rendered thing the graphic, since in the visualization literature is a graphic whether it's theoretical or rendered to an image. Probably stole the terminology from Grammar of Graphics
![image](https://user-images.githubusercontent.com/1300499/115160468-45050f80-a066-11eb-9cec-4ba5289ec37e.png)
which is probably a short hand for graphical design (from  "A Presentation Tool" by Jock Mackinlay)
![image](https://user-images.githubusercontent.com/1300499/115160158-c196ee80-a064-11eb-8b94-ef82ea849ded.png)

**Comment by jklymak** [comment]
I think we are after a verb, not a noun, and I think we call those things "Artists".

**Comment by tacaswell** [comment]
> I'm not quite sure what exactly 1 actually does

The way this is implemented is that we do `fig.draw(render_with_no_op_methods)`.  Thus, everything on the `Artist` side of the draw (resolving anything lazy (limits, some RBGA mapping that we cache, some truncation in Line2D, resolve any "relative to other artist" transfroms), computing how big the text will be, sort where ticks are, etc) will happen.  In the normal course of events, the `Artist.draw` methods are responsible for boiling down everything it knows from the user and using that information to set up `GraphicConext`s and call the `renderer.draw_XYZ` methods (see https://matplotlib.org/stable/api/backend_bases_api.html#matplotlib.backend_bases.RendererBase it is out of these primitives (which map closely to the SVG primitives) that we make _everything_).  Exactly what gets done in `draw_xyz` is up to the backend (e.g. in svg this produces text, in the case of AGG it composites another layer onto its internal buffer) and in the `draw_no_output` case it does nothing.   

Concretely, if we look at `Axis.draw` https://github.com/matplotlib/matplotlib/blob/bf9ae97cdfb6c810bf57d317ce3988a98ff43abc/lib/matplotlib/axis.py#L1116-L1145 we see that it:

 - does a short-circuit check
 - opens a group (matters in some of the vector backends)
 - updates the ticks (`self._update_ticks()` is where we sort out who is visible etc and all of the logic to re-use ticks lives)
 - loop over the ticks to draw and call their `draws` 
 - sorts out where the axis label should be
 - asks the `Text` object that is the label to please draw itself
 - does the same song/dance with the offset text (this is for when we say '+1e10')
 - close the group and mark it self as not-stale 

At no point in here did we actually _use_ the renderer, we have to go a couple of more level down through https://github.com/matplotlib/matplotlib/blob/bf9ae97cdfb6c810bf57d317ce3988a98ff43abc/lib/matplotlib/axis.py#L302-L312 to https://github.com/matplotlib/matplotlib/blob/bf9ae97cdfb6c810bf57d317ce3988a98ff43abc/lib/matplotlib/text.py#L737-L744 or https://github.com/matplotlib/matplotlib/blob/bf9ae97cdfb6c810bf57d317ce3988a98ff43abc/lib/matplotlib/lines.py#L753-L777 to find the renderer methods in use.

It should also be noted, that when we talk about doing stuff on a GPU we usually get stuck on "we do too much in Python", it is this aspect of doing lots and lots of work in the `Artist.draw` method.  On the other hand, this design is also what lets us support the variety of backends that we do!

This suggest `draw_no_render` is a better name?

I suspect the historical path we took to get to the collection of `draw` methods is that the very first version of Matplotlib was a gtk application gtk uses `draw` in this context (e.g. https://developer.gnome.org/gtkmm-tutorial/stable/sec-cairo-drawing-lines.html.en).  This is pretty thematically consistent with GUI toolkits for "the code that runs to sort out what color the pixels on the screen should be" as QT uses "paint" in this context.

-------

In the first diagram what GoG calls "Graphic" is what we call "Artist" and in the second the construction of the Artists is what is labeled "Graphical Design".  In both cases we are worried about details inside of the "Render" or "render" parts so I do not think either is going to provide us useful naming guidance in this case.

**Comment by brunobeltran** [comment]
> Thus, everything on the `Artist` side of the draw (resolving anything lazy (limits, some RBGA mapping that we cache, some truncation in Line2D, resolve any "relative to other artist" transfroms), computing how big the text will be, sort where ticks are, etc) will happen.

This is exactly the thing which Eric and I are hoping we find a "name" for.

> In the normal course of events, the Artist.draw methods are responsible for
> 1.  boiling down everything it knows from the user and
> 2. using that information to set up GraphicConexts and call the renderer.draw_XYZ methods

(numbering added by me). I think from an API design perspective, the fact that we implement `draw_no_output` by (basically) setting a flag that lets us skip step (2), doesn't matter, because most users don't and shouldn't have to know that.

From a usage perspective, it feels like the user trying to build a mental model should be primed (by the function's name) to understand that these are two different steps that happen when you draw a figure, and that this function basically does the first one.

I approved the existing name because I don't have a better suggestion. But if we do have a good name for (1), we should use it.

**Comment by brunobeltran** [comment]
>  `layout_artists`. Then we could say `draw` = `layout_artists` + `render`.

I can definitely get behind this. 

> The routine walks the artist tree and calls the `draw` method on every artist. It just stops short of outputting the results to the renderer.

but I don't think the implementation should affect the naming.

"layout" might not be "all encompassing" enough, but is basically what I was hoping for.

**Comment by brunobeltran** [comment]
To summarize:

```python
fig.draw
```

is "semantically" just

```python
for artist in fig.crawl_tree():
    artist.draw()  # basically "artist.layout()" + "artist.render()"
```

Obviously, we can't change the name of `Artist.draw`, but from the perspective of *using* a figure, there's no reason you should need to know how we implement "layout" and "render" on the artist level, but you will definitely have uses for doing just one or both.

**Comment by timhoffm** [comment]
Some more ideas:

- `Artist.update()` would be more general, but that's already taken for batch property updates**. 
- `Artist.update_state()` might work.
- `Artist.unstale()` is too jargony IMHO.

** Side note: `Artist.update()` seems almost identical with `Artist.set()`. After we expire the reorder deprecation in `set()`, the remaining differences will be
- `update()` takes a dict, but `set()` takes kwargs.
- `update()` seems not to normalize the parameters
Maybe we should look into if we want to straighten that API. Oh, and there's also `Artist.setp()` which does something similar. 😨

**Comment by jklymak** [comment]
I'm not sure it is terribly practical to change the nomenclature all the way back to `Artist`.    That seems a lot of churn for little practical gain.  

Again, I'll remind folks were are trying to come up with a replacement name for `fig.canvas.draw` which has served the purpose for 15 years despite not containing *any* indication that it did not actually produce an output.  That the replacement should also contain the verb `draw` makes perfect sense to me a) because that is the historical verb and b) because that is what it is doing, *except* it stops at the point of making an output.  I think of it as drawing something in your favourite graphics program, but never sending it to the printer. 

I suppose the verb "compose" is really what is happening here, and maybe `fig.compose_no_output` would be OK, but given we call this "draw" everywhere else, I'm still not particularly convinced the slight difference in verb is that helpful.

**Comment by tacaswell** [comment]
I renamed and re-labeled this issue to reflect the discussion we are actually having here ;)

**Comment by timhoffm** [comment]
I like `compose()`. `_no_output` postfix is unneeded there as composing does not have a notion of output in the first place.

I agree with @brunobeltran that the naming here does not need to reflect implementation (or low-level naming).

At the semantic top level. we'd have "drawing is composing + renderding". The low-level implementation can only draw. The realization of an isolated `compose()` is done by drawing with a null-renderer.

**Comment by QuLogic** [comment]
This is going out in 3.5 soon; does anyone have any new/final opinions on renaming?
