### ISSUE TITLE
Support for list/array of labels when plotting matrices with plot using label option

### ISSUE THREAD

**Issue by mmarras** [matplotlib/matplotlib#20008]
### Problem
Assuming I have two matrices `X`, `Y` both of shape lets say (10,1024) where each row ( one of 10) represents a vector to be plotted. Using `pyplot.plot` this can be plotted rather straight forward as `plot(X.T,Y.T)`. Now if I have a list of labels of `len` 10 it would be very convenient to be able to just pass this on to the `label` option. This is expected to work since, it is what I would do, if I were to plot just a two vectors `Xvec` and `Yvec` of shape (1,1024), but afaik does not work.
   

### Proposed Solution
If the input to plot is a matrix `(X.T).shape=(n,m)` , n,m>1 and not a vector, the label argument should accept `listoflabels` a list/array of size m as input.

`pyplot.plot(X.T,Y.T,label=listoflabels)`

### Additional context and prior art
Currently the list of labels can be passed to `pyplot.legend()` already, I just believe a user can expect that if you can plot multiple lines at once, that the same interface will also allow you to label those. 

This
```python
pyplot.plot(X.T,Y.T)
pyplot.legend(listoflables)
```

does 
what I would expect from
```python
pyplot.plot(X.T,Y.T,label=listoflabels)
pyplot.legend()
```

**Comment by jklymak** [comment]
I'm 98% sure this is #16178.  I'll close, but feel free to ask for a re-open if I'm mistaken.
