### ISSUE TITLE
undefined symbol: PyPyUnicode_ReadChar

### ISSUE THREAD

**Issue by yuan8901** [matplotlib/matplotlib#20014]
When I tried to run matplotlib with pypy3, I got the following error.  pypy version [PyPy 7.3.1 with GCC 9.3.0].  Matplotlib version 
matplotlib-3.3.4-pp36-pypy36_pp73-manylinux2010_x86_64.whl

from . import ft2font
pypy3.6/site-packages/matplotlib/ft2font.pypy36-pp73-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_ReadChar

**Comment by tacaswell** [comment]
I can not reproduce this, but I only have access to 

```
✔ 19:41:06 $ python --version
Python 3.7.10 (51efa818fd9b24f625078c65e8e2f6a5ac24d572, Apr 11 2021, 13:25:22)
[PyPy 7.3.4 with GCC 10.2.0]
```

which pulls  `matplotlib-3.3.4-pp37-pypy37_pp73-manylinux2010_x86_64.whl`

attn @mattip .

**Comment by mattip** [comment]
That C-API function was added [in PyPy v.7.3.2](https://doc.pypy.org/en/latest/release-v7.3.2.html#python-3-6-c-api). Please update to the latest PyPy version.

**Comment by jklymak** [comment]
Lets close for now, but @yuan8901 please ping us if that doesn't fix the problem.

**Comment by anntzer** [comment]
If the pypy wheels can't specify micro-release version requirements, perhaps the version check at the point of use
```c
#if defined(PYPY_VERSION) && (PYPY_VERSION_NUM  < 0x07030200)
        Py_UNICODE *unistr = PyUnicode_AsUnicode(textobj);
        for (size_t i = 0; i < size; ++i) {
            codepoints[i] = unistr[i];
        }
#else
        for (size_t i = 0; i < size; ++i) {
            codepoints[i] = PyUnicode_ReadChar(textobj, i);
        }
#endif
```
should just use a version bound of `0x07040000`?  This way the wheels stay always valid, even though they may use a *slightly* less optimal version on PyPy 7.3.{0,1}.
