### ISSUE TITLE
Minor changes about stackplot documentation

### ISSUE THREAD

**Issue by motimace** [matplotlib/matplotlib#20036]
### Problem
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.stackplot.html#matplotlib.axes.Axes.stackplot

I found **labels** & **colors** to be unclear because `Length N list of str` & `Length N list of color` made me think that `Length` have to be equal to `length of x`. It is better that `length of labels & colors` is equal to data series length (M).

### Suggested Improvement

**labels**: list
A sequence of strings providing the labels for each data series.

**colors**: list, default: None
A list or tuple of colors. These will be cycled through and used to colour the stacked areas.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.4.1
  * Matplotlib documentation version (is listed under the logo): 3.4.1

**Comment by QuLogic** [comment]
Please see the linked PR above.
