### ISSUE TITLE
polar() axvspan incorrectly forces r-limits

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20030]
### Bug report

**Bug summary**

In cartesian axes, an axvspan() does not set y-limits, only x-limits: this is expected, as axvspan are defined as spanning (by default) the entire y-span, regardless of the y-limits.

In polar axes, axvspan() should likewise not set r-limits, but in fact they do force the upper r-lim to be at least 1.

**Code for reproduction**

```python
from pylab import *
subplot(121); axvspan(0, 1); plot([.1, .2], c="C1")
subplot(122, projection="polar"); axvspan(0, 1); plot([.1, .2], c="C1")
show()
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/1322974/115474042-e219a100-a23c-11eb-91a7-c1e025ca4d07.png)
The cartesian axes' y-lims correctly go from 0.1 to 0.2 plus margins, but the upper r-lim of the polar axes incorrectly goes all the way to 1.

**Expected outcome**

The upper r-lim of the polar axes goes to 0.2 plus margins.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): head (3.4.etc)
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 39
  * Jupyter version (if applicable): 
  * Other libraries: 

-----

In `_AxesBase._update_patch_limits`, the critical point is
```python
            updatex, updatey = patch.get_transform().\
                contains_branch_seperately(self.transData)
```
For cartesian axes, the patch's transform is indeed unrelated to transData in the `x` direction, so it is not taken into account.  OTOH, for polar axes, the transforms are not separable, so `updatex = False`, causing the bug.  I'm not sure how easy that would be to fix at that level (I guess the correct `updatex` is really "does `patch.get_transform()` (restricted to the x output) change if the xlims are changed", which smells like doing automatic differentiation on the transform tree).

An alternative (uglier, but perhaps more practical) approach would be to just hard-code that case in axvspan...

**Comment by dstansby** [comment]
I think this is fixed now, I checked on current `main`. Please re-open if I'm wrong!
