### ISSUE TITLE
AttributeError: module 'sip' has no attribute 'setapi'

### ISSUE THREAD

**Issue by talhaanwarch** [matplotlib/matplotlib#20040]
OS: Windows 10
Python: 3.8.5
On a fresh virtual environment, i installed `matplotlib` version `3.4.1`. When I import using
`import matplotlib.pyplot as plt`
It throws
`AttributeError: module 'sip' has no attribute 'setapi'`
With a bit of search, I see it is because of pyqt5. 
Simply installing pyqt5 latest version `5.15.4` using
`pip install PyQt5` resolve the error.

If matplotlib is using pyqt5, I believe it should be installed while installing `matlotlib`. Currently installing matplotlib is not installing pyqt. It install these packages `numpy, six, python-dateutil, cycler, kiwisolver, pillow, pyparsing, matplotlib`

Complete error log
```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    import matplotlib.pyplot as plt
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\pyplot.py", line 2469, in <module>
    switch_backend(rcParams["backend"])
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\__init__.py", line 619, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\pyplot.py", line 257, in switch_backend
    switch_backend(candidate)
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 13, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\qt_compat.py", line 174, in <module>
    _setup()
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\qt_compat.py", line 134, in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
  File "D:\tutorials\automl\venv2\lib\site-packages\matplotlib\backends\qt_compat.py", line 117, in _setup_pyqt4_internal
    sip.setapi(_sip_api, api)
AttributeError: module 'sip' has no attribute 'setapi'
```

**Comment by QuLogic** [comment]
Despite the file name, that file is used for Qt 4 and 5, and your problem is with 4. Installing PyQt5 made it pick that first instead, but did not actually fix the error. What version of PyQt4 do you have installed?

**Comment by QuLogic** [comment]
And also what version of `sip`?

**Comment by talhaanwarch** [comment]
Please check
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1

**Comment by QuLogic** [comment]
4, not 5

**Comment by talhaanwarch** [comment]
Pardon me, I did not understand, here is all packages currently installed.
```
cycler==0.10.0
kiwisolver==1.3.1
matplotlib==3.4.1
numpy==1.20.2
Pillow==8.2.0
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
python-dateutil==2.8.1
six==1.15.0
```
Should I install pyqt4 ? How can I install it? I did not find any pip version of it

**Comment by QuLogic** [comment]
Are you sure you are using the same venv? The only way to get to that line of code is if PyQt4 is already imported into Python, which means it was available at some point to the Python you were running.

**Comment by talhaanwarch** [comment]
Uninstalling the pyqt5 packages mentioned above brings back the error. Though it's a fresh virtual environment. Still, I checked in anaconda may be I have pyqt4 installed somewhere. But I am unable to find it. 
The virtual environment is created using `python -m venv venv2`

**Comment by talhaanwarch** [comment]
I checked using qmake --version, still it showing qt5

**Comment by QuLogic** [comment]
Do you have a `matplotlibrc` file, or `QT_ENV` set in the environment? Does `python -c 'import PyQt4; print(PyQt4.__file__)` output anything?

**Comment by talhaanwarch** [comment]
`python -c 'import PyQt4; print(PyQt4.__file__)` gives 
`ModuleNotFoundError: No module named 'PyQt4'`. 
How to check matplotlibrc file, or QT_ENV set in the environment?

**Comment by talhaanwarch** [comment]
It should be worthy to notice that this issue does not arise with matplolib version 3.2.0. All packages installed in virtual env is as follow
```
cycler==0.10.0
kiwisolver==1.3.1
matplotlib==3.2.0
numpy==1.20.2
pyparsing==2.4.7
python-dateutil==2.8.1
six==1.15.0
```

**Comment by QuLogic** [comment]
You can check where `matplotlibrc` is [here](https://matplotlib.org/stable/tutorials/introductory/customizing.html?highlight=matplotlibrc#customizing-with-matplotlibrc-files), and the `QT_ENV` environment variable from checking `os.environ`.

**Comment by QuLogic** [comment]
Also, what about `python -c 'import sip; print(sip.__file__)`?
