### ISSUE TITLE
Pcolormesh Polar Projection omits data when mesh is above certain size

### ISSUE THREAD

**Issue by mtgraves** [matplotlib/matplotlib#20056]
### Bug report

**Bug summary**

When too large of a mesh is passed to pcolormesh, when using polar projection, some of the data seems to be omitted.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

# This works...
angular_mesh, radial_mesh = np.meshgrid(
        np.radians(np.linspace(-90, 90, 500)),
        np.linspace(0.5, 20.0, 500)
)

data = np.ones(angular_mesh.shape)

plt.figure()
ax = plt.subplot(111, projection='polar')
plt.pcolormesh(
        angular_mesh,
        radial_mesh, 
        data[:-1, :-1],
)
plt.colorbar()
plt.show()

# This does NOT...
angular_mesh, radial_mesh = np.meshgrid(
        np.radians(np.linspace(-90, 90, 4000)),
        np.linspace(0.5, 20.0, 4000)
)

data = np.ones(angular_mesh.shape)

plt.figure()
ax = plt.subplot(111, projection='polar')
plt.pcolormesh(
        angular_mesh,
        radial_mesh, 
        data[:-1, :-1],
)
plt.colorbar()
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2545006/115923635-87569400-a44c-11eb-89f1-2326c72690a6.png)

**Expected outcome**

Should show data all the way down to 0.5 on the radial axis of the plot.

**Matplotlib version**

  * Operating system: centOS 7 and Windows 10 (both experience issue)
  * Matplotlib version): 3.3.2
  * Matplotlib backend: TkAgg
  * Python version: 3.8.6
  * Jupyter version (if applicable): N/A
  * Other libraries: 

pip installation

**Comment by jklymak** [comment]
This is not a reproducible example.  Please clear your kernel and try again and you will see that you have not defined the variables you think you are plotting.  Please include the imports, and try running as a standalone script before submitting.

**Comment by mtgraves** [comment]
Sorry, transcription error when going from my actual code to making a more generic example.  Fixed.

**Comment by jklymak** [comment]
Did you test it, because it works fine for me on Qt5Agg and master and v3.3.2.  maybe its just a TkAgg bug, but...

**Comment by mtgraves** [comment]
Sorry, please try again.  My apologies, trying to multitask and not giving this issue input enough attention.

**Comment by jklymak** [comment]
OK, 16 million quadrilaterals, projected onto a non-linear axes that is 3 inches by 3 inches will tend to be problematic.  You can rasterize the pcolormesh, and make the figure bigger, and you will get something that is a bit better.  But you will almost certainly have aliasing on any reasonable sized monitor, or most formats you would save to, unless you use an extremely high dpi.  Personally I would decimate in some reasonable fashion.

**Comment by mtgraves** [comment]
Is there some reason why it appears to work fine when polar projection is not used?

**Comment by jklymak** [comment]
It doesn't work fine - you are heavily aliased at 4000 points across a 5-inch canvas unless you display at 800 dpi.  What happens with polar is that now you have 4000 points all crowded onto a few pixels near the origin.

**Comment by mtgraves** [comment]
I believe that you are absolutely correct my friend.  I'll close this, but could you enlighten me as to why the data shows up 'blank' in those crowded regions?

**Comment by jklymak** [comment]
My guess is that AGG rounds the polygons to the nearest pixel and if all the points on the polygon have the same value it doesn't draw the polygon.  So while every pixel has a polygon it it, they are all degenerate.   But I'm not 100% sure...

**Comment by mtgraves** [comment]
Before I close this, I should ask:  do you have a sense of the limit at which this problem should start to manifest itself in such a way that this behavior is observed?  It does not seem that the DPI + figure size needs to be set such that each data point has its own 'spot' in the plot for the data to be rendered as opposed to 'left blank' as reported above.  How could one go about investigating a sane way of computing a desired DPI such that figures are not too large in size but still have the appropriate rendering parameters to avoid this issue?  Is there any standard way of approaching this?

**Comment by jklymak** [comment]
I would look at the source code and either use a debugger or print statements and figure out what is going on.

**Comment by mtgraves** [comment]
ok thanks again for the help/education here
