### ISSUE TITLE
API docs currently include entries for class `__dict__`, `__module__`, `__weakref__`

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20080]
### Problem

The attributes mentioned in the issue title are clearly internal and should not be documented (*possibly* unless we explicitly override them, if ever).

See e.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.__dict__ https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.__module__ https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.__weakref__

### Suggested Improvement

Suppress these attributes in the docs.

**Matplotlib version**
  * Matplotlib documentation version (is listed under the logo): both 3.4.1 and 3.4.1.post544.

**Comment by timhoffm** [comment]
Incorrect closing reference.
