### ISSUE TITLE
incorrect tight_layouting with separate, differently-sized gridspecs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20093]
### Bug report

**Bug summary**

tight_layout seems to intend to support handling subplots that are specified using different gridspecs as long as one's nrows/ncols is as multiple of the other's, but actually fails to reach a correct tight layout.

**Code for reproduction**

(using `subplot()` should be the same as recreating a gridspec from scratch each time)

```python
# 2 on first row, 4 on second row
# bad approach
fig = figure(tight_layout=True)
subplot(221); subplot(222); subplot(245); subplot(246); subplot(247); subplot(248)

# good approach
fig = figure(tight_layout=True); gs = fig.add_gridspec(2, 4); a = fig.add_subplot
a(gs[0, 0:2]); a(gs[0, 2:4]); a(gs[1, 0]); a(gs[1, 1]); a(gs[1, 2]); a(gs[1, 3])
```

**Actual outcome**

"bad" approach:
![bad](https://user-images.githubusercontent.com/1322974/116287260-7e3d2e00-a790-11eb-8bab-ce4072d13bfa.png)
"good" approach:
![good](https://user-images.githubusercontent.com/1322974/116287270-81381e80-a790-11eb-91b7-1f1239f3c16d.png)

Note that
* tight_layouting `subplot(221); subplot(222); subplot(223); subplot(224)` works just fine
* tight_layouting `subplot(221); subplot(222); subplot(234); subplot(235); subplot(236)` (2 on the first row, 3 on the second) warns "tight_layout not applied: number of columns in subplot specifications must be multiples of one another." suggesting that there was an intent of making "2 on first row, 4 on second row" work.
* `fig = figure(tight_layout=True); gs = fig.add_gridspec(2, 6); a = fig.add_subplot; a(gs[0, 0:3]); a(gs[0, 3:6]); a(gs[1, 0:2]); a(gs[1, 2:4]); a(gs[1, 4:6])` (2 on first row, 3 on second row, but using a single gridspec) works.

**Expected outcome**

Correct tight_layouting in the "bad".  Or at least warn as in the 2-and-3-case and just give up on tight_layouting.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): head
  * Matplotlib backend (`print(matplotlib.get_backend())`): mplcairo
  * Python version: 39
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Is there a reason you would do this in tight_layout instead of constrained_layout?

**Comment by anntzer** [comment]
Not at all, I was just looking at the tight_layout code (as can be seen from the other PRs) and noticed the exact-multiple check and wanted to have a look at it working and noticed it not working...

**Comment by anntzer** [comment]
Upon further look, I convinced myself that this basically cannot be made to work as is: indeed, something like
```python
fig = figure(tight_layout=True); a = fig.add_subplot
gs0 = fig.add_gridspec(2, 2)
a(gs0[0, 0]); a(gs0[0, 1])
gs1 = fig.add_gridspec(2, 4)
a(gs1[1, 0]); a(gs1[1, 1]); a(gs1[1, 2]); a(gs1[1, 3])
```
also fails.  This is because tight_layout tries to achieve its goal by setting a single wspace value (and margins), but wspace is defined as the inter-axes pad width *as a fraction of the average Axes width*, but that average axes width is different for a (2, 2) gridspec and a (2, 4) gridspec, so the spacing ends up being physically different in the two rows...

I guess a proper solution is possible, where tight_layout first computes a common large gridspec for all axes (basically using the lcm() of nrows and ncols of all gridspecs), remaps the subsplotspecs to that large gridspec, performs tight_layout (calling subplots_adjust, which moves the axes to the desired positions), and then swaps back the original gridspecs to hide all that from the end user (which IIRC was something @jklymak proposed at some point?), but that seems to be a lot of work when there's basically CL which does this much better anyways.  So perhaps instead we should just refuse to tight_layout different gridspecs (just like we already refuse to tight_layout gridspecs that are not multiples of one another), especially given that the error/warning message can point people to use CL instead?

**Comment by jklymak** [comment]
So `subplot2grid` will reuse a gridspec if it is the same.  `add_subplot` should also work if you do 

```
subplot(2,4, (1, 3) ); subplot(2, 4, (2, 5)); subplot(2,4,5); subplot(2,4,6); subplot(2,4,7); subplot(2,4,8)
```

with constrained_layout.  Does *that* work for `tight_layout`?

**Comment by jklymak** [comment]
Following up, this works fine:

```python
import matplotlib.pyplot as plt
# 2 on first row, 4 on second row
# bad approach
fig = plt.figure(tight_layout=True)
fig.add_subplot(2, 4, (1, 2)); 
fig.add_subplot(2,4, (3, 4));
for i in range(1, 5):
    fig.add_subplot(2, 4, 4+i); 
plt.show()
```

**Comment by anntzer** [comment]
In both of your examples, all subplots use a (2, 4) gridspec, so that's fine?

**Comment by jklymak** [comment]
Right.  Then the logic all works for both layout methods.

**Comment by anntzer** [comment]
I think we all agree here; my question now is whether we should just stop pretending to support having two (or more) different gridspecs at the same time.

**Comment by anntzer** [comment]
Summary of discussion on call was to deprecate support for non-matching case.

**Comment by jklymak** [comment]
It's not impossible to normalize the gridspecs but it becomes a pain to reassign a new subplotspec to an existing axes if the big axes are created first.  I'm not quite sure what you mean by deprecating this, though.  Do you mean tightlayout will just eventually not run?  That's going to be hard when the user has specifically specified two gridspecs that are beside each other (using the rect arguement).  We would have to check that the gridspecs are different but also disjoint.  Seems a bit too magical.  Probably better for folks to just see it doesn't work and for the docs to be clear about what they need to do in order for it to work.

**Comment by anntzer** [comment]
After some thought, I agree it's better to just leave things as they are (also to avoid spurious warnings in case one is using a different gridspec but has an axes that spans the whole width).
Temporarily re-gridding (e.g. from a 2-col and 3-col layout to a 6-col layout) is also not going to work in case one has additionally specified width_ratios/height_ratios.
So let's just close as wontfix; I'll just add some comments to the implementation describing the limitations.
