### ISSUE TITLE
How to draw a three-dimensional image

### ISSUE THREAD

**Issue by sivanWu0222** [matplotlib/matplotlib#20103]
### Problem
How to draw a three-dimensional image, as shown in the figure below, a large three-dimensional image consists of many small three-dimensional images, and I can customize the corresponding pixel value of the small three-dimensional image

![6vuRjZ](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/6vuRjZ.png)

**Comment by QuLogic** [comment]
See the source of the example: https://matplotlib.org/stable/gallery/mplot3d/voxels_numpy_logo.html

Please use [discourse](https://discourse.matplotlib.org) for further usage questions.
