### ISSUE TITLE
problem using custom fonts in Latex mode

### ISSUE THREAD

**Issue by gnikiforov** [matplotlib/matplotlib#20110]
### Bug report

**Bug summary**

When trying to use Proxima Nova with Latex, the correct font is not rendered unless a very convoluted sequence of commands is executed.

**Code for reproduction**

```python
# -*- coding:utf-8 -*-
import matplotlib as mpl

mpl.use("pgf")

mpl.rcParams.update({
    'font.family': 'sans-serif',
    'text.usetex': True,
    'pgf.rcfonts': False,
    'pgf.texsystem': 'lualatex',
    'pgf.preamble': r'\usepackage{fontspec} \setmainfont{Proxima Nova}',
})

import matplotlib.pyplot as plt

plt.plot([1, 2, 3])
plt.xlabel(r'x label a little bit longer', fontsize=10)
plt.ylabel(r'Something in small caps', fontsize=10)

plt.savefig('test.pdf')
```

**Actual outcome**

[test_a.pdf](https://github.com/matplotlib/matplotlib/files/6400089/test_a.pdf)

The font is not Proxima Nova, but rather the default sans-serif DejaVu Sans.

**Expected outcome**

[test_pn.pdf](https://github.com/matplotlib/matplotlib/files/6400097/test_pn.pdf)

In order to get the correct output, I found the following workaround:

1. Restart Spyder.
2. Delete .matplotlib/tex.cache folder
3. Replace `'font.family': 'sans-serif'` and `\setmainfont{Proxima Nova}` in the code above with `'font.family': 'serif'` and `\setmainfont{Times New Roman}` respectively
4. Run Python. This produces an output with Times New Roman font.
[test_tnr.pdf](https://github.com/matplotlib/matplotlib/files/6400115/test_tnr.pdf)
5. Revert back to `'font.family': 'sans-serif'` and `\setmainfont{Proxima Nova}`
6. Run Python again. This time the correct Proxima Nova font is rendered.

I understand why I might need to delete the tex.cache folder. However I do not understand why Proxima Nova is not rendered unless first another font is used. I was looking at the `.matplotlib/fontlist-v330.json` file and Proxima Nova appears a few times in it, while the Times New Roman font appears only once. I wonder if this might be a clue.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.3.2 
  * Matplotlib backend: pgf
  * Python version: 3.9.4
  * Jupyter version (if applicable): 
  * Other libraries: Anaconda, Spyder 4

Installed matplotlib from conda using the default channel.

**Comment by anntzer** [comment]
I'm not exactly sure why your complex manipulation makes things work, but the underlying issue is (I believe) because you ask Matplotlib to draw using font.family = sans-serif (which makes Matplotlib use `\sffamily`), but then set the *main* (i.e., serif) font to Proxima Nova (I don't have that font here to test, but I tried with others).  You should either set font.family to serif, or call `\setsansfont{Proxima Nova}` (regardless of whether it's actually a sans-serif font or not).

**Comment by gnikiforov** [comment]
Thank you so much for your response. 

Just to clarify:

Using 

`mpl.rcParams.update({
    'font.family': '**serif**',
    'text.usetex': True,
    'pgf.rcfonts': False,
    'pgf.texsystem': 'lualatex',
    'pgf.preamble': r'\usepackage{fontspec} **\setmainfont{Proxima Nova}**',
})`

Did NOT work. However

`mpl.rcParams.update({
    'font.family': '**sans-serif**',
    'text.usetex': True,
    'pgf.rcfonts': False,
    'pgf.texsystem': 'lualatex',
    'pgf.preamble': r'\usepackage{fontspec} **\setsansfont{Proxima Nova}**',
})`

DID work.

I guess the trick is to use the command `\setsansfont` when wanting to use a sans-serif font. I think I had a misunderstanding that selecting a specific sans-serif font makes it the _main_ font. Thank you once again.
