### ISSUE TITLE
axes.titlecolor no longer available?

### ISSUE THREAD

**Issue by DannyVanpoucke** [matplotlib/matplotlib#20112]
### Problem
Migrating a python project to a different computer, a perfectly working jupyter notebook now starts throwing warning wrt matplotlib. 
Following warning was obtained:
"
Bad key "axes.titlecolor" on line 3 in
./GraphStyle.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
"
The link above no longer exists (and was probably the source of the originally obtained mplstyle.(But I can no longer be certain, as I created this function >6months ago)

### Suggested Improvement
Either reintroduce this key or provide information on it's replacement?

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.1.0.
  * Matplotlib documentation version (is listed under the logo): "https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template"

**Comment by anntzer** [comment]
axes.titlecolor was only added in Matplotlib 3.2, your version is too old.

**Comment by DannyVanpoucke** [comment]
thx.
