### ISSUE TITLE
Adding cmocean and CMasher to the colormaps tutorial

### ISSUE THREAD

**Issue by 1313e** [matplotlib/matplotlib#20121]
### Problem

There is a tutorial on choosing colormaps in MPL on the online docs [here](https://matplotlib.org/stable/tutorials/colors/colormaps.html), which I frequently point others to when they want to know what colormaps are available in MPL.
It also provides references to `palettable` and `colorcet` as great sources for properly made colormaps (which I fully agree with).
However, what I am missing, is references to MPL's own `cmocean` (or, at least, I know that MPL is hosting it) and [CMasher](https://github.com/1313e/CMasher).

### Suggested Improvement

Given the popularity of both packages and that most people I know usually tend to use either one of these when looking for colormaps, I think it would be beneficial if both packages are mentioned as well in the tutorial.
After all, the more properly made colormaps people can find, the lower the chances are that someone will use one that is not properly made or well-suited for their specific application (like `jet`).

I did find that the tutorial can be found [here](https://github.com/matplotlib/matplotlib/blob/master/tutorials/colors/colormaps.py), so if required, I can add these references myself.

**Matplotlib version**

  * Operating system: Windows 10/Ubuntu 20.04
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib documentation version (is listed under the logo): 3.4.1

**Comment by story645** [comment]
Alternatively, what about removing the references to palatteble and colorcet and replace with a link to the colormaps section of https://matplotlib.org/mpl-third-party/#colormaps-and-styles ? (And please add cmasher there!)

**Comment by 1313e** [comment]
> Alternatively, what about removing the references to palatteble and colorcet and replace with a link to the colormaps section of https://matplotlib.org/mpl-third-party/#colormaps-and-styles ? (And please add cmasher there!)

That would work as well, and might make it easier to add other resources later.

**Comment by 1313e** [comment]
@story645 Would you like me to add those links to that section or...?

**Comment by story645** [comment]
Yes, please! Thanks!

**Comment by 1313e** [comment]
Just to make sure I do it right: On which branch should I base my fork branch?

**Comment by story645** [comment]
Master - stuff will get backported to other branches as needed.

**Comment by 1313e** [comment]
I created a PR for this in #20196.

**Comment by jklymak** [comment]
Closed by #20196
