### ISSUE TITLE
Unable to use 'ds' keyword in plt.errorbar

### ISSUE THREAD

**Issue by jeffburggraf** [matplotlib/matplotlib#20137]
### Bug report

**Bug summary**

In version 3.4.1, passing the 'ds' kwarg to plt.errorbar results in an attribute error. 
**Code for reproduction**

```python
from matplotlib import pyplot as plt
plt.errorbar(x=[1, 2], y=[1, 2], yerr=[1, 2], ds='steps-mid')
```

**Actual outcome**

```
AttributeError: 'LineCollection' object has no property 'drawstyle'
```

**Matplotlib version**

  * Operating system: Catalina (10.15.7) 
  * Matplotlib version: 3.4.1 
  * Matplotlib backend: MacOSX 
  * Python version: 3.8.8
  * Other libraries: Fresh conda environment 

Installed matplotlib via conda using the default channel.

**Comment by jklymak** [comment]
Did it ever work?   I am not sure what this kwarg is supposed to do for errorbar...

**Comment by jeffburggraf** [comment]
I believe so, at least it worked in the previous version.

**Comment by jklymak** [comment]
What do you expect it to do though?  

The kwarg documentation is for markers, which don't use `drawstyle`.  Its unfortunate `drawstyle` is in there, but its for completeness with other plot calls.  Its entirely possible this didn't error before, but I don't think it ever did anything either.

**Comment by jeffburggraf** [comment]
I use the kwarg to produce histograms like this:

![Screenshot 2021-05-02 221241](https://user-images.githubusercontent.com/10396095/116843070-a1524e00-ab93-11eb-8b85-47832740560e.png)

There is a package called mplhep, which is just a wrapper for mpl, that makes it easy to produce these types of histograms. Unfortunately, mplhep is broken in the current mpl version.

**Comment by anntzer** [comment]
This was fixed in https://github.com/matplotlib/matplotlib/pull/19888.
