### ISSUE TITLE
 Crash when plotting scatterplot (reopen of #19058)

### ISSUE THREAD

**Issue by FabKoala** [matplotlib/matplotlib#20158]
### Bug report

**Bug summary**

This problem is similar as issue #19058 but on Linux without anaconda.
I use Matplotlib for months without problem : essentially plot and pcolormesh.
When I try to scatter (basicaly) it crashes without message. When using python console (in a terminal) the console ends (as with ctrl-d).

**Code for reproduction**
Here is a minimal script :
```python
import numpy as np
import matplotlib.pyplot as plt 

plt.ion()
x = np.random.random(10)
y = np.random.random(10)

print('Check point #1')
plt.plot(x,y)
print('Check point #2')
plt.waitforbuttonpress(timeout=3)
plt.scatter(x,y)
print('Check point #3')
plt.waitforbuttonpress(timeout=3)
print('Check point final')
```

**Actual outcome**
Here is the output
```
fafi@ACER-antix2:~/Develop/bacAsable
$ python scattercrash.py 
Check point #1
Check point #2
Check point #3
Instruction non permise
fafi@ACER-antix2:~/Develop/bacAsable
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Linux : 4.9.212-antix.1-486-smp (based on Debian 10 'buster')
  * Matplotlib version : 3.3.3 (installed via pip. No virtual env)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.9.1 via sources ([GCC 8.3.0] on linux)
  * Other libraries: see pip list result :
```
$ pip list
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
Babel                         2.9.0
beautifulsoup4                4.9.3
certifi                       2020.12.5
chardet                       4.0.0
click                         7.1.2
cycler                        0.10.0
docutils                      0.16
idna                          2.10
imagesize                     1.2.0
Jinja2                        2.11.3
joblib                        1.0.1
kiwisolver                    1.3.1
MarkupSafe                    1.1.1
matplotlib                    3.3.3
nltk                          3.5
numpy                         1.19.5
packaging                     20.9
pandas                        1.2.3
Pillow                        8.1.0
pip                           21.1.1
Pygments                      2.7.4
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2021.1
regex                         2020.11.13
requests                      2.25.1
scikit-learn                  0.24.1
scipy                         1.6.0
setuptools                    51.3.3
six                           1.15.0
snowballstemmer               2.1.0
soupsieve                     2.2
Sphinx                        3.5.0.dev20210212
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
threadpoolctl                 2.1.0
tk                            0.1.0
tqdm                          4.59.0
urllib3                       1.26.3
wheel                         0.36.2
```

thanks for helping

Fafi

**Comment by jklymak** [comment]
It doesn't do that for most folks, so it must be something strange with your setup.  
- try other backends
- try a fresh virtual environment 
- try anaconda to get all the non-python dependencies

Maybe others have a good trace dump method of debugging these sorts of things.  If a core is dumped that could be helpful.

**Comment by tacaswell** [comment]
As you definitely have a compiler, I would try re-installing numpy / pandas / matplotlib / anything with c-extensions with 

```
pip install --no-binary :all: numpy
pip install --no-binary :all: matplotlib
pip install --no-binary :all: pandas
...
```

to force them to re-compile on your system.   My knee-jerk guess from looking up antiX linux is that due to their commitment to supporting older machines, some of the wheels published to pypi assume that you have CPU instructions that are not available in your setup (I am at the _edge_ of my understanding here).

**Comment by jklymak** [comment]
I'll close for lack of follow up but feel free to request a re-open if you still think there is something we can do

**Comment by FabKoala** [comment]
Hy,

I just found that the problem was with my (very) old computer which does
not have a certain function implemented. Thus for those old machines, one
has to not upgrade numpy further than 1.19.4.
the simple solution for my computer :
          sudo pip3 uninstall matplotlib numpy
          sudo pip3 install numpy==1.19.4
          sudo pip3 install matplotlib

Hopefully it could be useful for others.

Thanks

Fabrice

Le jeu. 20 mai 2021 à 05:25, Jody Klymak ***@***.***> a
écrit :
