### ISSUE TITLE
%matplotlib widget forwards scroll events to browser

### ISSUE THREAD

**Issue by spapa013** [matplotlib/matplotlib#20179]
### Bug report

**Bug summary**

%matplotlib widget backend does not behave consistently with %matplotlib notebook. 

%matplotlib notebook consumes the scroll event and does not forward to browser. 

%matplotlib widget also receives the scroll event but still passes it to the browser. This means when i try to use the scroll event for the plot I end up scrolling up and down the page. 

related to #8911

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
%matplotlib widget
plt.plot(np.random.rand(10))
```

**Actual outcome**

```
Scrolling works, but it scrolls the browser as well.
```

**Expected outcome**
```
Scrolling works, but does not scroll the browser.
```
**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipympl.backend_nbagg
  * Python version: 3.6.8
  * Jupyter version (if applicable): Jupyter notebook 6.0.1
  * Other libraries: ipywidgets

 installed via pip

**Comment by jklymak** [comment]
Should this be reported at https://github.com/matplotlib/ipympl ?

**Comment by QuLogic** [comment]
Yes, `%matplotlib widget` is implemented by ipympl.
