### ISSUE TITLE
a2.clear() modifies a1

### ISSUE THREAD

**Issue by pdalet** [matplotlib/matplotlib#20195]
### Bug report

a2.clear() modifies a1

I create 2 subplots a1 (left) and a2 (right) ,  with a2=a1.twinx().
When I clear a2  (a2.clear()) , I modify a1 (axes y, ticks color)

Test on ubuntu 20.04 64bits
python3.7
matplotlib 3.4.2 with backend wxpyton
matplotlib installed from pypi with pip.

```python
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
from math import sin,pi,sqrt

#display
ms=1E-3             #ms
duration=40*ms #40ms
N=100                 # N points per period - display
f=50                    #frequency
T=1/f                   #period
Nmax=int(duration*N/T)+1

#sampling
Ne=20                 # Ne points per period - sampling
fe=Ne*f                 #sampling period
Nemax=int(duration*fe)+1

#ADC
Vref=5
Nbit=8
q=Vref/(2**Nbit -1)

#data
vmax=1*sqrt(2)
t   = [float(i*T/N) for i in range(0,Nmax)]
te = [float(i/fe) for i in range(0,Nemax)]
v  = [vmax*sin(2*pi*f*t[i]) + vmax for i in range(0,Nmax)]
Nombre = [ (vmax*sin(2*pi*f*te[i]) + vmax)/q for i in range(0,Nemax)]

#plot
fig, a1 = plt.subplots()
plt.subplots_adjust(left=0.10, bottom=0.25)
a1.grid(True)
a1.set_xlim(0,t[Nmax-1])
a1.set_ylim(0,  5)
a1.set_ylabel('Tension', fontsize=16, color= 'red')
a1.tick_params(axis='y', labelcolor='tab:red') 
a1.set_xlabel('Temps', fontsize=16)
a1.set_title(r'$Echantillonneur-Bloqueur-CAN\ (Sample-Hold-ADC)$',color='b',fontsize=20)  

a2=a1.twinx()
a2.set_ylabel('Nombre', fontsize=16, color= 'blue' )
a2.set_ylim(0,  300)
a2.tick_params(axis='y', labelcolor='tab:blue')

a1.plot(t, v,  color='red')
a2.step(te, Nombre, where='post')  

          
def update(val):
        fe=val*f            
        Nemax=int(duration*fe)+1
        te = [float(i/fe) for i in range(0,Nemax)]
        Nombre = [ (vmax*sin(2*pi*f*te[i]) + vmax)/q for i in range(0,Nemax)]

        a1.clear()
        a1.grid(True)
        a1.set_xlim(0,t[Nmax-1])
        a1.set_ylim(0,  5)
        a1.set_ylabel('Tension', fontsize=16, color= 'red')
        a1.tick_params(axis='y', labelcolor='tab:red') 
        a1.set_xlabel('Temps', fontsize=16)
        a1.set_title(r'$Echantillonneur-Bloqueur-CAN\ (Sample-Hold-ADC)$',color='b',fontsize=20)
        a1.plot(t, v,  color='red')
        
        a2.clear()  # <---------------------------------------------------------------------
        a2.set_ylabel('Nombre', fontsize=16, color= 'blue' )
        a2.set_ylim(0, 300)
        a2.tick_params(axis='y', labelcolor='tab:blue')
        a2.step(te, Nombre, where='post')  


# horizontal slider to control the fe/f
axfreq = plt.axes([0.10, 0.1, 0.80, 0.03], facecolor= 'lightgoldenrodyellow')
freq_slider = Slider( ax=axfreq,label='fe/f', valmin=1, valmax=50, valinit=10)
freq_slider.on_changed(update)

figManager = plt.get_current_fig_manager()
figManager.window.showMaximized()
plt.show()
```
philippe DALET
FRance

**Comment by jklymak** [comment]
This will get more timely help if you minimize it considerably (this is full of extra labeling, grids, etc etc).  You can probably also strip the widget aspect from it, and maximizing the figure etc.  .  I also do not understand what you mean by "... I modify a1 (axes y, ticks color)"

**Comment by jklymak** [comment]
Please see http://sscce.org

**Comment by pdalet** [comment]
I have finished my script. see the right vertical axe.  All works well, except the right axe.

import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, RadioButtons
from math import sin,pi,sqrt

#display
ms=1E-3             #ms
duration=40*ms #40ms
N=100                 # N points per period - display
f=50                    #frequency
T=1/f                   #period
Nmax=int(duration*N/T)+1

#sampling
Ne=20                 # Ne points per period - sampling
fe=Ne*f                 #samplnig period
Nemax=int(duration*fe)+1

#ADC  0-5V 8bits
Vref=5
q=Vref/(2**8 -1)

#data
vmax=1*sqrt(2)
t   = [(i*T/N) for i in range(0,Nmax)]
te = [(i/fe) for i in range(0,Nemax)]
v  = [vmax*sin(2*pi*f*t[i]) + vmax for i in range(0,Nmax)]
ve  = [vmax*sin(2*pi*f*te[i]) + vmax for i in range(0,Nemax)]
Nombre = [int((vmax*sin(2*pi*f*te[i]) + vmax)/q) for i in range(0,Nemax)]

#plot
fig, a1 = plt.subplots()
plt.subplots_adjust(left=0.20, bottom=0.25)
a1.grid(True)
a1.set_xlim(0,t[Nmax-1])
a1.set_ylim(0,  5)
a1.set_ylabel('Tension', fontsize=16, color= 'red')
a1.tick_params(axis='y', labelcolor='tab:red') 
a1.set_xlabel('Temps', fontsize=16)
a1.set_title(r'$Echantillonneur-Bloqueur-CAN\ (Sample-Hold-ADC)$',color='b',fontsize=20)  

a2=a1.twinx()
a2.set_ylabel('Nombre', fontsize=16, color= 'blue' )
ymax=300
a2.set_ylim(0,ymax)
a2.tick_params(axis='y', labelcolor='tab:blue')

a1.plot(t, v,  'r', te,  ve , 'ro')
a2.step(te, Nombre, where='post')  

def Plot():
        global te, Nombre,a1, a2
        te = [(i/fe) for i in range(0,Nemax)]
        ve  = [vmax*sin(2*pi*f*te[i]) + vmax for i in range(0,Nemax)]
        Nombre = [int((vmax*sin(2*pi*f*te[i]) + vmax)/q) for i in range(0,Nemax)]

        a1.clear()
        a1.grid(True)
        a1.set_xlim(0,t[Nmax-1])
        a1.set_ylim(0,  5)
        a1.set_ylabel('Tension', fontsize=16, color= 'red')
        a1.tick_params(axis='y', labelcolor='tab:red') 
        a1.set_xlabel('Temps', fontsize=16)
        a1.set_title(r'$Echantillonneur-Bloqueur-CAN\ (Sample-Hold-ADC)$',color='b',fontsize=20)
        a1.plot(t, v, 'r', te, ve, 'ro')
        
        a2.clear()
        a2.set_ylabel('Nombre', fontsize=16, color= 'blue' )
        a2.set_ylim(0, ymax)
        a2.tick_params(axis='y', labelcolor='tab:blue')
        a2.step(te, Nombre, where='post')
        fig.canvas.draw_idle()

def freqfunc(val):
        global fe,Nemax
        fe=val*f
        Nemax=int(duration*fe)+1
        Plot()

def bitfunc(label):
        global q,ymax
        if (label=='16 bits'):  q=Vref/(2**16 -1);ymax=70000
        if (label=='12 bits'):  q=Vref/(2**12 -1);ymax=4500
        if (label=='8 bits'):   q=Vref/(2**8 -1);ymax=300
        Plot()

# horizontal slider to control the fe/f
axfreq = plt.axes([0.20, 0.1, 0.70, 0.03], facecolor= 'lightgoldenrodyellow')
freq_slider = Slider( ax=axfreq, label='fe/f', valmin=1, valmax=50, valinit=10)
freq_slider.on_changed(freqfunc)
# radio button
rax = plt.axes([0.025, 0.6, 0.10, 0.15], facecolor='lightgoldenrodyellow')
radio = RadioButtons(rax, ('16 bits', '12 bits', '8 bits'), active=2)
radio.on_clicked(bitfunc)

figManager = plt.get_current_fig_manager()
figManager.window.showMaximized()
plt.show()

Thanks 
Philippe Dalet
