### ISSUE TITLE
contour edge case with all data below levels and a surrounding field of zeros

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#20203]
### Bug report

**Bug summary**

If I attempt to make a contour plot with data that is entirely below the lowest level, and the data has a field of zeros around it, I get an unexpected contour between the zeros and anything positive.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

y = np.linspace(-10, 10, 20)
x_2d, y_2d = np.meshgrid(y, y)

data = np.cos(x_2d * np.pi/10.) + np.cos(y_2d * np.pi/10.)
np.place(data, data < 0., 0.)

levels = [3, 6]
colors = ['b', 'r']

plt.contour(data, levels=levels, colors=colors)

plt.show()
```

**Actual outcome**

![bug_zeros_line](https://user-images.githubusercontent.com/10599679/117796800-4f6e8f80-b247-11eb-8d6c-d97c55057ea4.png)

**Expected outcome**

The plot should be blank, which is what happens if the call to `np.place` is skipped.

**Matplotlib version**

  * Operating system: RHEL7.9
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.8
  * Jupyter version (if applicable): N/A
  * Other libraries: numpy 1.20.2

**Comment by ianthomas23** [comment]
I've confirmed that this is a bug.  If the levels for a line contour plot are all outside of the `z` limits, the levels are replaced by the lower z limit, here:
https://github.com/matplotlib/matplotlib/blob/a9c5224dbc1a31b85c5b58544ea5063df13f0737/lib/matplotlib/contour.py#L1141-L1147

Here is a simple reproducer:
```python
import matplotlib.pyplot as plt

z = [[0, 0], [0, 1]]
cs = ax[0].contour(z, levels=levels)
ax[0].set_title(f'levels_in={levels}, levels_out={cs.levels}')

levels = [2]
cs = ax[1].contour(z, levels=levels)
ax[1].set_title(f'levels_in={levels}, levels_out={cs.levels}')

fig.tight_layout()
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/580326/117807414-8480df00-b253-11eb-8ac3-3522e033d5b1.png)
Under most circumstances we'd get away with this behaviour.  However, if there is a quad which has the lower-z value on 3 of its 4 corners then half the area of the quad is at the lower level and the contour line is calculated on the upper edge of this triangle (see #19691 for detailed explanation).

I presume that if the user specifies the contour levels then we should not modify them, even if this means that no contour lines are plotted.  But I suspect there may be issues about colorbars being displayed without any contents?

**Comment by rcomer** [comment]
Thanks @ianthomas23 for taking a look at this and providing an explanation.  With this knowledge we can make a simple workaround in the user code by setting a new, artificial, localised minimum before plotting.  E.g.

```python
data[0, 0] = -1
```
