### ISSUE TITLE
ax.twinx().spines.right not accessible from ipython session

### ISSUE THREAD

**Issue by timjim333** [matplotlib/matplotlib#20230]
### Bug report

**Bug summary**

It seems like accessing the spines of a twin axis doesn't work as expected from an ipython session - noticed from [this question on SO](https://stackoverflow.com/questions/67529651/move-third-y-axis-to-right/67530980#67530980). Sorry, I didn't have a chance t specifically isolate the issue.

**Code for reproduction**

```python
# ipython terminal
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.subplots_adjust(right=0.75)
twin1 = ax.twinx()
twin2 = ax.twinx()
twin2.spines.right.set_position(("axes", 1.2))
```

**Actual outcome**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-81ef357c19ae> in <module>
      4 twin1 = ax.twinx()
      5 twin2 = ax.twinx()
----> 6 twin2.spines.right.set_position(("axes", 1.2))

AttributeError: 'collections.OrderedDict' object has no attribute 'right'
```

**Expected outcome**

For the `right` attribute to be accessible in `twin2.spines` in the ipython terminal, as it is when running a script.

**Matplotlib version**

  * Operating system: CentOS 8
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): '3.2.2'
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable): 
  * Other libraries: 

conda base

**Comment by timhoffm** [comment]
This feature has only been introduced in Matplotlib 3.4.0:
https://matplotlib.org/3.4.0/users/whats_new.html#axes-spines-access-shortcuts

Please update if you want to use it.

**Comment by timjim333** [comment]
Thanks for the update. You might want to add that note [to the tutorial](https://matplotlib.org/stable/gallery/ticks_and_spines/multiple_yaxis_with_spines.html) which doesn't mention it.

It is strange that it doesn't cause any issues when running the script directly, however! The inconsistent behaviour made me (and another user) think it was bug rather than a feature to be implemented.

**Comment by tacaswell** [comment]
@timjim333 The docs do have the version number at the top.  If you want to see the v3.2.2 docs for the same tutorial it is at https://matplotlib.org/3.2.2/gallery/ticks_and_spines/multiple_yaxis_with_spines.html (which uses `__getiem__` rather than attribute access).

If you are seeing this in IPython and not when run as a script, then I suspect you have overlapping virtual environments and are running the scripts against another Python / Matplotlib version than when you are in IPython!

**Comment by timjim333** [comment]
@tacaswell Ah, thanks for the hint. That makes sense - I was running the script directly in my IDE (which was a different environment that had 3.4.0 installed)! I suspect the OP in the SO post must have done the same.

**Comment by Shone1214** [comment]
```
twin2.spines.right.set_position(("axes", 1.2))
```
modify the code：
```
twin2.spines["right"].set_position(("axes", 1.2))
```
