### ISSUE TITLE
inset_axes should have some sort of `set_position`

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20236]
`ax.inset_axes` does not allow `set_position` or `set_transform` if the user wants to change the position of an inset axes.  This s probably easy to add, but I think means that `inset_axes` would need to have a new axes subclass that overloads those methods.

**Comment by jklymak** [comment]
x-ref: https://stackoverflow.com/questions/67542636/how-to-update-positions-of-inset-axes-in-matplotlib

**Comment by jeffreypaul15** [comment]
@jklymak Could I give this a go?

**Comment by jklymak** [comment]
I think so.  Right now `inset_axes` is just a normal `Axes`.  It would be an API change to hoist it to a new subclass (`InsetAxes`?).  But then `bounds` could be modified via `set_position`, and `transform` via `set_transform`.  I think its pretty straightforward. 

However, as you've seen, API decisions can be a bit involved, so just be prepared for some back and forth.

**Comment by QuLogic** [comment]
This seems to be a duplicate of #12985?

**Comment by QuLogic** [comment]
Going to close as a duplicate of #12985.
