### ISSUE TITLE
TkAgg build seems to favor Framework Tcl/Tk on OS-X

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#2025]
As reported on the mailing list thread "missing ticks in inverted log axis", it seems that the setup.py script favors the Framework Tcl/Tk when building the tkagg extension.

```
elif sys.platform == 'darwin':
            # this config section lifted directly from Imaging - thanks to
            # the effbot!

            # First test for a MacOSX/darwin framework install
            from os.path import join, exists
            framework_dirs = [
                join(os.getenv('HOME'), '/Library/Frameworks'),
                '/Library/Frameworks',
                '/System/Library/Frameworks/',
            ]
```

I assume this was in here for a reason -- it's been like that for ages.  Do any Mac users have any thoughts/solutions?

Cc: @pelson, @r-owen

**Comment by petehuang** [comment]
Any thoughts? @efiring @mdehoon continuing to ping you if you have any

**Comment by efiring** [comment]
I'm going to close this as obscure and out of date. I suspect Tcl-Tk version problems will be with us until the end of time, especially on OSX with its multiple moving targets (Macports, homebrew, etc.

**Comment by QuLogic** [comment]
In 2.0, we load Tk at runtime from whatever exists at that point; I assume that will also help as we won't be tied down to one specific version from build time.
