### ISSUE TITLE
3.4.2: matplotlib against downloaded copy of freetype

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#20256]
Most of the leading linux distribution have intentionally cut off access to public network.
I cannot find find any details how to build matplotlib against system freetype DSO and looks like matplotlib is downloading, building and linking statically against freetype.
Is it any official way of building matplotlib against system freetype?

**Comment by tacaswell** [comment]
Please see https://matplotlib.org/stable/devel/dependencies.html#c-libraries

Be warned that if you are going to use system freetype the test suite will likely not pass.  You may want to look at the patches the Fedora carries (@QuLogic is the expert there) to run our tests against modern freetype.

**Comment by kloczek** [comment]
Is it possible somehow pass `system_freetype=true` without editing setup.cfg?

**Comment by tacaswell** [comment]
You can configure the file it looks at with an ENV

https://github.com/matplotlib/matplotlib/blob/4723f8a42c8190f5cb287aca8fdf80ec6c37b102/setupext.py#L180-L181
