### ISSUE TITLE
seaborn-colorblind style inconsistent with upstream seaborn colors.

### ISSUE THREAD

**Issue by bixel** [matplotlib/matplotlib#20252]
Apparently
```python
plt.style.use('seaborn-colorblind')
```
yields a different color cycle than the one documented in the [seaborn docs](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes).
Especially the greenish color at the second place can be confusing as we're used to 1. blue 2. orange 3. green colors and so on.

I've translated the seaborn colors via
```python
[
    ''.join([f'{int(255 * h):02x}'.upper() for h in c])
    for c in sns.color_palette('colorblind')
]
> ['0173B2', 'DE8F05', '029E73', 'D55E00', 'CC78BC', 'CA9161', 'FBAFE4', '949494', 'ECE133', '56B4E9']
```
I guess this should go into https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/stylelib/seaborn-colorblind.mplstyle.

**Comment by mwaskom** [comment]
This is a duplicate of https://github.com/matplotlib/matplotlib/pull/13680; all of matplotlib's packaged "seaborn" style sheets are out of sync with the seaborn library.

**Comment by bixel** [comment]
Ok thanks for the pointer, I didn't find that discussion. I'd say this issue is superseded by the discussions in #13680 and related issues.
