### ISSUE TITLE
"$$" can not be displayed by ax.text()

### ISSUE THREAD

**Issue by raphaelquast** [matplotlib/matplotlib#20266]
### Bug report

**Bug summary**
I guess the minimal code-example tells it all...

**Code for reproduction**

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.text(1, 2, "$$")
```

**Actual outcome**

```
Out[1]: Text(1, 2, '$$')Traceback (most recent call last):
  File " ...\lib\site-packages\matplotlib\_mathtext.py", line 2277, in parse
    result = self._expression.parseString(s)
  File " ...\lib\site-packages\pyparsing.py", line 1955, in parseString
    raise exc
  File " ...\lib\site-packages\pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File " ...\lib\site-packages\matplotlib\backends\backend_qt5.py", line 475, in _draw_idle
    self.draw()
  File " ...\lib\site-packages\matplotlib\backends\backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File " ...\lib\site-packages\matplotlib\artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File " ...\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File " ...\lib\site-packages\matplotlib\figure.py", line 2780, in draw
    mimage._draw_list_compositing_images(
  File " ...\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File " ...\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File " ...\lib\site-packages\matplotlib\_api\deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File " ...\lib\site-packages\matplotlib\axes\_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File " ...\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File " ...\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File " ...\lib\site-packages\matplotlib\text.py", line 679, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File " ...\lib\site-packages\matplotlib\text.py", line 314, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File " ...\lib\site-packages\matplotlib\backends\backend_agg.py", line 235, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File " ...\lib\site-packages\matplotlib\mathtext.py", line 452, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File " ...\lib\site-packages\matplotlib\mathtext.py", line 473, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File " ...\lib\site-packages\matplotlib\_mathtext.py", line 2279, in parse
    raise ValueError("\n".join(["",
ValueError: 
$$
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.4.2
  * Matplotlib backend: QT5Agg
  * Python version: 3.8.8
  * Jupyter version (if applicable): -
  * Other libraries: -

` conda install -c conda-forge matplotlib`

**Comment by jklymak** [comment]
`'$$'` sends the string to the latex parser.  Which cannot find anything between the dollar signs and fails.  I guess you could argue that it should just no-op.  OTOH if you actually want dollar signs, you need to escape them: `'\$\$'`

**Comment by raphaelquast** [comment]
hey, thanks for the quick response!

my problem actually originated from a gui that is used to dynamically update a text-instance...
(escaping the dollar-signs is not a very elegant option since you would need to communicate this to the user...)
- everything works just fine until a user accidentally types `$$`, then the plot crashes immediately
  - note that this also affects [TextBox widgets](https://matplotlib.org/stable/gallery/widgets/textbox.html)

A simple check for empty strings in the parser would solve this while keeping the 
(awesome!) latex-parsing functionality intact ...

**Comment by jklymak** [comment]
I think thats a fair request.  I suspect its not super hard to fix.  @aitikgupta are you familiar with this corner of the code?

**Comment by raphaelquast** [comment]
awesome, thanks!

I've just noticed that this could be fixed more properly by ignoring latex-errors in general! 

- would also fix inputs like `$\unknown_command$` which raise a `ParseFatalException`

**Comment by jklymak** [comment]
Not sure I would go that far - I think we want parsing errors to fail.  I'm not even sure `"$$"` shouldn't fail...

**Comment by aitikgupta** [comment]
Ah, I was intending to open this issue for a while. I brought this up on Gitter a while ago while talking about interactivity.

> Talking about interactivity, currently there's no way to get back to the correct state in GUI when an error occurs right?
Eg: When you use a TextBox with `$ some_mathtext $` and if that's invalid (can happen a lot) we see a nice error log in terminal, but the GUI is in invalid state now, and there's no way to get it working again unless I start over.

@anntzer:
> @aitikgupta  I'm not sure what cases you refer too, but I guess these should be considered as bugs

It's either of these 2 things:
1. As @jklymak says escape the empty mathtext (`"$$"`) in-general.
2. A better way would be to let the errors persist even when `"$$"` is parsed, however, for interactive things like a `TextBox widget`, or any further downstream GUI, when we parse mathtext, just use a `try & catch`, or raise a warning instead of error, anything which _does not_ make the GUI go haywire - in an invalid state.

2nd will solve OP's problem, as well as keep mathtext in intended behaviour - (we want parsing errors to fail, but just not for GUI).

**Comment by jklymak** [comment]
Right, so whether `$\badcommand$ fails or not, the GUI should deal with it gracefully.  I don't know how the GUI works exactly, but it should probably have a catch if its possible at that level.

**Comment by QuLogic** [comment]
> A better way would be to let the errors persist even when `"$$"` is parsed, however, for interactive things like a `TextBox widget`, or any further downstream GUI, when we parse mathtext, just use a `try & catch`, or raise a warning instead of error, anything which _does not_ make the GUI go haywire - in an invalid state.

I don't think `TextBox` should parse _any_ mathtext. That's a consequence of using `Text` to display things, but I don't think it's an intentional behaviour.

**Comment by jklymak** [comment]
Dev call agrees with the above!

**Comment by aitikgupta** [comment]
Hmm, even if we magically somehow force only `TextBox` to not parse any mathtext, the original problem would still stand, i.e,
```python
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.text(1, 2, "$$")
```

I propose we add a parameter to `Text` class, something like `override_math`, which will force that text object to not parse any mathtext, just like we have a check for usetex in `_preprocess_math`: https://github.com/matplotlib/matplotlib/blob/11258c27be3a83832bff8659bd1a03ea2ad35aa6/lib/matplotlib/text.py#L1229-L1232

This would solve both problems, as well as what @anntzer mentioned in dev call: people wanting option to remove mathttext parsing altogether in their text objects.

**Comment by QuLogic** [comment]
Well, I don't think it's strictly necessary to introduce that solely for `TextBox`, but if people want it for regular `Text` too, that's an easy way to fix it.

**Comment by raphaelquast** [comment]
Hey, since I opened this I thought I'll add my 2 cents from the user-perspective :

I think it would be nice if instead of raising an error you display something like `<LaTex error>` on the plot and print the latex-traceback as a warning to the console.
This way you could keep the parsing while potential gui-users are also informed that there's something wrong with the latex code.

...and maybe add an option to switch the latex parsing between "warn" and "raise"  or "off".

**Comment by tacaswell** [comment]
That is a good idea @raphaelquast !  I would suggest a slightly different name (`parse_mode=..`) and values with:

- `'literal'` : no attempts at parsing as math
- `'math'` : the current behavior (and should stay the default)
- `'math-forgiving'` : math parsing, but fallback to "literal" if things fail
- `'math-error'` : replaces with `<LaTeX error>` if parsing fails

**Comment by aitikgupta** [comment]
The general `parse_mode` as suggested above does make sense as a general `Text` property, however @raphaelquast is referring to 'gui-users'. which means widgets like `TextBox`.

Even if we include this parse_mode, these widgets will still be (or should be) making `parse_mode = literal`, as the base concept of https://github.com/matplotlib/matplotlib/pull/20367 or https://github.com/matplotlib/matplotlib/issues/20266#issuecomment-844667321.

To fully accept @raphaelquast's request we'd be going against "TextBox shouldn't parse mathtext _at all_".

**Comment by tacaswell** [comment]
Right, I think those modes go on `mtext.Text` and the `TextBox` sets the correct value on the underlying `Text` object.

**Comment by raphaelquast** [comment]
awesome! thanks for fixing this! 🚀
