### ISSUE TITLE
Multicursor not showing on subplots when zooming in and then back out 

### ISSUE THREAD

**Issue by JayVaz18** [matplotlib/matplotlib#20271]
I currently have a figure that contains 5 subplots and have been using multicursor to generate a vertical line through all of the subplots on hover. However, when I zoom in using the interactive window (I'm using nbagg and have tried others to no avail), the multicursor line disappears. Then, when I zoom back out, the multicursor line still isn't there. Is there a way to fix this? I've read across the internet of a possible widget lock that can be causing this, but I would like to zoom in and have the multicursor line appear just as it would when I don't zoom in. The code below is straight from the docs and screenshots to show the error. 

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import MultiCursor

t = np.arange(0.0, 2.0, 0.01)
s1 = np.sin(2*np.pi*t)
s2 = np.sin(4*np.pi*t)

fig, (ax1, ax2) = plt.subplots(2, sharex=True)
ax1.plot(t, s1)
ax2.plot(t, s2)

multi = MultiCursor(fig.canvas, (ax1, ax2), color='r', lw=1)
plt.show()
```

Before zoom:

```
<img width="2048" alt="Screen Shot 2021-05-20 at 9 40 54 AM" src="https://user-images.githubusercontent.com/72083618/118988997-ac58fc80-b94f-11eb-808f-3e9b3405c964.png">


```

After zoom (cursor was on the line):

<img width="2048" alt="Screen Shot 2021-05-20 at 9 41 17 AM" src="https://user-images.githubusercontent.com/72083618/118989055-b8dd5500-b94f-11eb-9aa4-7d9a494a6efa.png">

**Comment by JayVaz18** [comment]
Sorry, here's the image before zoom:

<img width="2048" alt="Screen Shot 2021-05-20 at 9 40 54 AM" src="https://user-images.githubusercontent.com/72083618/118989316-efb36b00-b94f-11eb-91f0-7b1afebc17bd.png">

**Comment by timhoffm** [comment]
Starting point for further investigation: After zooming, the callback function `onmove()` for the `motion_notify_event` does not get called anymore.

**Comment by QuLogic** [comment]
I don't see any problem with `onmove` being called? What does happen is that in _all_ widgets, if the widget lock is taken, then it disables itself. Starting the pan or zoom tools takes the widget lock, so this is working as intended?

**Comment by timhoffm** [comment]
I see: As soon as you activate any tool, the interaction is disabled.

In the present case the mouse is used for zooming, so it does not make sense to move the MultiCursor along. When you deactivate the zoom tool, the MultiCursor starts working again.
