### ISSUE TITLE
UnsupportedOperation: File or stream is not seekable.

### ISSUE THREAD

**Issue by devanshi-09** [matplotlib/matplotlib#20270]
Trying to save multiple image in a loop using : 
plt.imsave(filepath,image,cmap="gray")
file extention is "png" and the path is correct still getting the error:
"UnsupportedOperation: File or stream is not seekable."

The screenshot is attached below for the reference. Kindly help with this issue.
 
![Capture](https://user-images.githubusercontent.com/62321263/118971542-2cea1e00-b98d-11eb-886b-e5d196111edb.png)
`

**Comment by jklymak** [comment]
This is a pillow error, not a Matplotlib error. However, my guess is that you either have something wrong with your filesystem, or you have a typo in your filename.  I'll close, but feel free to discuss at discourse.matplotlib.org perhaps with minimal code.  Thanks!
