### ISSUE TITLE
Somebug happened,when I use matplotlib in pypy or PyPy PYPY

### ISSUE THREAD

**Issue by daibitao19** [matplotlib/matplotlib#20283]
I install matplotlib in pypy by downloading the wheel in https://www.lfd.uci.edu/~gohlke/pythonlibs/ and its name is matplotlib‑3.4.2‑pp37‑pypy37_pp73‑win_amd64.whl. My pypy version is Python 3.7.10 (51efa818fd9b, Apr 04 2021, 12:09:32) [PyPy 7.3.4 with MSC v.1927 64 bit (AMD64)] on win32.

But when I import matplolib something wrong happended.

Traceback (most recent call last): File "", line 1, in File "C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\site-packages\matplotlib_init_.py", line 107, in from . import api, cbook, docstring, rcsetup File "C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\site-packages\matplotlib\cbook_init.py", line 31, in from matplotlib import _api, _c_internal_utils ImportError: cannot import name '_c_internal_utils'

Can anyone else help?Very thankful

**Comment by daibitao19** [comment]
>>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_c_internal_utils'

**Comment by QuLogic** [comment]
These wheels are not built by us; you'd need to ask @cgohlke.

**Comment by daibitao19** [comment]
> These wheels are not built by us; you'd need to ask @cgohlke.
But when I run pypy3 -m pip install matplotlib in cmd , it failed again.
C:\Users\Bitao_Dai>pypy3 -m pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.4.2.tar.gz (37.3 MB)
Requirement already satisfied: cycler>=0.10 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: numpy>=1.16 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (1.20.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (8.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: six in c:\users\bitao_dai\pypy3.7-v7.3.4-win64\site-packages (from cycler>=0.10->matplotlib) (1.16.0)
Using legacy 'setup.py install' for matplotlib, since package 'wheel' is not installed.
Installing collected packages: matplotlib
    Running setup.py install for matplotlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\pypy3.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BITAO_~1\\AppData\\Local\\Temp\\pip-install-e3jvpojc\\matplotlib_d49ca819955745568829baec86a6a792\\setup.py'"'"'; __file__='"'"'C:\\Users\\BITAO_~1\\AppData\\Local\\Temp\\pip-install-e3jvpojc\\matplotlib_d49ca819955745568829baec86a6a792\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\BITAO_~1\AppData\Local\Temp\pip-record-xgmbjmar\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\include\matplotlib'
****************
 error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\pypy3.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BITAO_~1\\AppData\\Local\\Temp\\pip-install-e3jvpojc\\matplotlib_d49ca819955745568829baec86a6a792\\setup.py'"'"'; __file__='"'"'C:\\Users\\BITAO_~1\\AppData\\Local\\Temp\\pip-install-e3jvpojc\\matplotlib_d49ca819955745568829baec86a6a792\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\BITAO_~1\AppData\Local\Temp\pip-record-xgmbjmar\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Bitao_Dai\pypy3.7-v7.3.4-win64\include\matplotlib' Check the logs for full command output.

**Comment by jklymak** [comment]
Please discuss this at discourse.matplotlib.org.  if you are going to build from source you will need a C++ compiler.  Thanks!

**Comment by cgohlke** [comment]
You need [pypy3.7 >= 7.3.5rc2](https://downloads.python.org/pypy/).

**Comment by daibitao19** [comment]
Thank you. I have downloaded pypy3.7-v7.3.5rc3-win64.zip. But somethong wrong has happened.

 import matplotlib
Traceback (most recent call last):
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\pypy3.exe"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by daibitao19** [comment]
> You need [pypy3.7 >= 7.3.5rc2](https://downloads.python.org/pypy/).

And then I uninstall my original numpy and download the wheel numpy-1.20.3+mkl-pp37-pypy37_pp73-win_amd64.whl in your website. 
And I install the matplotlib again.
But bug happened again.

C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\Scripts>pypy3
Python 3.7.10 (77787b8f4c49, May 15 2021, 11:51:36)
[PyPy 7.3.5 with MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\matplotlib\__init__.py", line 157, in <module>
    _check_versions()
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\site-packages\matplotlib\__init__.py", line 151, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\Bitao_Dai\pypy3.7-v7.3.5rc3-win64\lib-python\3\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1015, in _gcd_import
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load
  File "<frozen importlib._bootstrap>", line 974, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kiwisolver'

**Comment by cgohlke** [comment]
> ModuleNotFoundError: No module named 'kiwisolver'

https://www.lfd.uci.edu/~gohlke/pythonlibs/#kiwisolver

**Comment by daibitao19** [comment]
> > ModuleNotFoundError: No module named 'kiwisolver'
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#kiwisolver

Words is hard to convey my appreciate. I've spent the night and the morning looking for a solution.
I've uninstall my original kiwisolver and install kiwisolver in your website. And finally I succeed in installing matplotlib in pypy.
Thank you. Thank you. Thank you.
I think we should let more people know how to install packages in pypy by your way.
In fact use the normal pypye- m pip install xxxx
always makes many trouble e.g. Command errored out with exit status 1 ,Visual C++14.

**Comment by cgohlke** [comment]
Once v7.3.5 is released, WinPython and conda-forge will catch up and you'll see more binaries on PyPI.

**Comment by Aniwax** [comment]
Thanks for the discussion. It solved my problem as well. My only question is, what's the difference between pacakges https://www.lfd.uci.edu/~gohlke/pythonlibs/ and things on `pip index` @cgohlke. And is there any plan from the  `matplotlib` @QuLogic @jklymak to release official wheel that could be installed with pypy?

**Comment by Aniwax** [comment]
Another completely off the topic question: If I want to build a `.whl` file for a python package to be installed on `pypy`, since there isn't one for the package I waned to install, would you be so kind to point me some resources on how to do it? @cgohlke  

Thank you so much 😉

**Comment by QuLogic** [comment]
Yes, when there's a working PyPy for Python 3.7 on all platforms in cibuildwheel.
