### ISSUE TITLE
why plt.savefig() doesn't work? When save figure, latitude does not show while longitude show correctly

### ISSUE THREAD

**Issue by linlintamu** [matplotlib/matplotlib#20286]
### Bug report

**Bug summary**

I am plotting global distribution of precipitation. So my figure should have longitude on the x-axis and latitude on the y-axis.

The figure show correctly inside jupyter notebook, with latitude and longitude shown correctly as desired.

However, when saving the figure using plt.savefigure(), and check the saved figure, the latitude labels disappear...

Does anyone know the reason?

**Code for reproduction**

```python
import xarray as xr
import numpy as np
import glob
import copy
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.gridspec as gridspec

from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import matplotlib.ticker as mticker
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import pandas as pd
import cartopy.crs as ccrs
%matplotlib inline

dpi = 100

fig = plt.figure(figsize=(1600/dpi, 1600/dpi), dpi=dpi) 

spec = gridspec.GridSpec(ncols=2, nrows=4,figure=fig,left=0.15,bottom=0.1,right=0.7,top=0.9)

spec.update(wspace=0.2,hspace=0.3)

ax = []

for ii in range(8):

    if ii <= 1:
        ax.append(fig.add_subplot(spec[0, ii],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)

    elif (ii >=2) and (ii <=3):
        ax.append(fig.add_subplot(spec[1, ii-2],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    elif (ii >=4) and (ii <=5):
        ax.append(fig.add_subplot(spec[2, ii-4],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    elif ii>=6:
        ax.append(fig.add_subplot(spec[3, ii-6],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    ax[-1].coastlines(resolution='110m',linewidth=0.8,color='black',linestyle='solid',alpha=0.7)
    ax[-1].set_global()
    ax[-1].set_title('',loc='left')
    ax[-1].set_extent([0.,357.5,-90,90],crs=ccrs.PlateCarree())

    gl = ax[-1].gridlines(crs=ccrs.PlateCarree(), draw_labels=True,linewidth=2, color='gray', alpha=1.0, linestyle='--')
    gl.top_labels = False
    gl.left_labels= True
    gl.right_labels=False
    gl.bottom_labels=True
    gl.xlines = False
    gl.ylines = False
    gl.xlocator = mticker.FixedLocator([-120,-60,180,120,60])
    gl.ylocator = mticker.FixedLocator([-90,-60,-30,0,30,60,90])
    gl.xformatter = LONGITUDE_FORMATTER
    gl.yformatter = LATITUDE_FORMATTER


plt.savefig("***.jpg",bbox_inches='tight',dpi=300,pad_inches=0.15)
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
I cannot reproduce your issue with 3.4.2, and even if there were an issue, its not clear that this is not cartopy's problem.  Its possible you have a problem with %matplotlib inline.  You can always trigger an extra draw - perhaps there is a draw issue with inline and bbox_inches tight.  i.e. `fig.draw_no_output()`...

**Comment by linlintamu** [comment]
![precip_globalmap_total_fig10_testlat](https://user-images.githubusercontent.com/56164034/119236874-62af1400-baff-11eb-93cb-b16f97574379.jpg)

**Comment by jklymak** [comment]
Please discuss with cartopy.  Howver I cannot reproduce your problem.  Thanks!
