### ISSUE TITLE
Streamplot requires that X and Y arrays be increasing

### ISSUE THREAD

**Issue by tbartholomaus** [matplotlib/matplotlib#20282]
### Bug report

**Bug summary**

If the X and Y ndarrays that are used to define a U and V field are decreasing, rather than increasing, grids, then the start_points functionality creates an error.  start_points will not be identified as within the X and Y grids, in error.

The problem emerges during the relatively narrow, overly strict, error checking at lines 158-159, where the smallest values are assumed to be the first values of X and Y.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

w = 3
Y, X = np.mgrid[w:-w:-100j, -w:w:105j]
U = -1 - X**2 + Y
V = 1 + X - Y**2
speed = np.sqrt(U**2 + V**2)

fig, ax = plt.subplots()
ax.streamplot(X, Y, U, V, start_points=np.array([[-2, -2]]))
```

**Actual outcome**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-288cd2052aad> in <module>
      9 
     10 fig, ax = plt.subplots()
---> 11 ax.streamplot(X, Y, U, V, start_points=np.array([[-2, -2]]))

~/anaconda3/envs/spatialenv21a/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1445     def inner(ax, *args, data=None, **kwargs):
   1446         if data is None:
-> 1447             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1448 
   1449         bound = new_sig.bind(ax, *args, **kwargs)

~/anaconda3/envs/spatialenv21a/lib/python3.7/site-packages/matplotlib/streamplot.py in streamplot(axes, x, y, u, v, density, linewidth, color, cmap, norm, arrowsize, arrowstyle, minlength, transform, zorder, start_points, maxlength, integration_direction)
    159                     grid.y_origin <= ys <= grid.y_origin + grid.height):
    160                 raise ValueError("Starting point ({}, {}) outside of data "
--> 161                                  "boundaries".format(xs, ys))
    162 
    163         # Convert start_points from data to array coords

ValueError: Starting point (-2.0, -2.0) outside of data boundaries```
```

**Expected outcome**
![Figure 2](https://user-images.githubusercontent.com/24902730/119187426-2f508480-ba2e-11eb-9c94-9d13806cdc82.png)

**Matplotlib version**

  * Operating system: Mac 11.2.3
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`):  module://ipympl.backend_nbagg
  * Python version: 3.7.10
  * Jupyter version (if applicable): 
  * Other libraries: 

conda

conda-forge

**Comment by jklymak** [comment]
This is explicitly documented:  https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.streamplot.html

```
x, y1D/2D arrays
Evenly spaced strictly increasing arrays to make a grid.
```

Are you reporting a bug or asking for a new feature?

**Comment by tbartholomaus** [comment]
Ah- I didn't catch that.  Then either a "bug" in my careful reading of documentation, or what seems like a "feature request" for modestly more flexibility in streamplot.  I'd have done this through a pull request, but it looks like the script is written with a specific philosophy in mind (re: use of a grid class) so I reckon I'd leave it for someone else.

**Comment by tbartholomaus** [comment]
Sorry if this is a pain- my geospatial data often comes "upside down", with the origin in the top left, rather than bottom left.  And it took me a while to figure out what the problem was.

**Comment by jklymak** [comment]
I can see that - maybe an easy fix is better argument checking rather than a mysterious message far down the stack?

**Comment by QuLogic** [comment]
There is a check for this; it, along with the clarification of the docs, was added in 3.4.0 in #18947.
