### ISSUE TITLE
plt.quiver linestyle option doesn't work?.....

### ISSUE THREAD

**Issue by wjddyd66** [matplotlib/matplotlib#20298]
### Bug report

**Bug summary**
**I set the linestyle option of plt.quiver, but a straight line always comes out.**  
Did you write the wrong code? Or do I need to change the Matplotlib Version?

**Code for reproduction**

```python
def draw(x, y):
    xPlusy = ((x[0]+y[0])/2,(x[1]+y[1])/2)
    array = np.array([[0, 0, x[0], x[1]],
                      [0, 0, y[0], y[1]],
                      [0, 0, xPlusy[0], xPlusy[1]]])
   
    X, Y, U, V = zip(*array)
    print("X =",X)
    print("Y =",Y)
    print("U =",U)
    print("V =",V)
    plt.figure()
    plt.figure(figsize=(16,10))
    plt.ylabel('Y-axis')
    plt.xlabel('X-axis')
    ax = plt.gca()
    ax.quiver(X, Y, U, V, angles='xy', scale_units='xy',color=['b','r','g'],scale=1, linestyle=':')
    ax.set_xlim([-4, 6])
    ax.set_ylim([-1, 5])
    # ax.axis('off')
    # plt.draw()
    plt.show()

a = np.array([-3, 0])
b = np.array([4, 4])

draw(a, b)
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/37298751/119444056-98553680-bd65-11eb-9495-6bd29013f272.png)

**Matplotlib version**

  * Operating system: MAC or Linux(Both same issue....)
![image](https://user-images.githubusercontent.com/37298751/119444332-039f0880-bd66-11eb-947d-a3de0cbf0e32.png)

**Comment by timhoffm** [comment]
The issue is that Quivers are actually polygons and the linestyle would apply to their outline (which by default has no color and zero width so you don't see an effect of linestyle). When applying `linestyle='--', linewidth=2, edgecolor='m'`, you'll get:

![grafik](https://user-images.githubusercontent.com/2836374/119477122-faef0800-bd4e-11eb-9082-5cc84cdcf275.png)

**Comment by wjddyd66** [comment]
Thanks!, It works! Sorry for late reply.
