### ISSUE TITLE
YearLocator dropped replaced attribute

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20313]
Is it worth putting in the a property what warns on get/set?  On one hand, most likely no one is using this, on the other hand it is not much work to make sure we do not needlessly break anyone who is trying to access this.

_Originally posted by @tacaswell in https://github.com/matplotlib/matplotlib/pull/19348#r639954916_

In #19348 the `YearLocator.replaced` attribute was not documented, nor was it tested, so it was dropped with an API note.  @tacaswell suggested than maybe instead we should have a setter/getter that does the right thing?

**Comment by timhoffm** [comment]
I'm ok with not going through a deprecation here (that's why I merged #19348). While I'm usually very catious with breaking changes, I dare to be pragmatic here and assume that this is too obscure that anybody will use it. But if somebody wants to do the deprecation dance, I'm not holding you up.

**Comment by QuLogic** [comment]
The removal was in 3.5, and our two-release deprecation cycle means that it would be removed now in 3.7, if one was put in at the time. It is probably unlikely that anyone has had an issue with this removal, as I don't recall any bug reports about it.
