### ISSUE TITLE
QuadMesh default for shading inadvertently changed.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20322]
In #20237 we messed with the signature for QuadMesh.  However the default for shading was changed from `'flat'` to `False`, which is not an allowable value.  

1. This should be fixed, both in the code and the change note
2. QuadMesh should probably gain a test on the values of the *shading* kwarg.  

Thanks @jeffreypaul15 for noting this.

**Comment by jeffreypaul15** [comment]
Can I open a PR for this?

**Comment by tacaswell** [comment]
@jeffreypaul15 Yes please!
