### ISSUE TITLE
New normalized colorbar doesn't handle the color of np.nan values as a proper color

### ISSUE THREAD

**Issue by xushanthu-2014** [matplotlib/matplotlib#20325]
### New normalized colorbar doesn't handle the color of np.nan values as a proper color

**I plotted a data with np.NaN. And I also want to change the center value of the colorbar due to the distribution of original data. But when I change the Vmin, Vmax and vcenter value of the colorbar, the color of np.NaN value changes to other colors other than white. So how can I fix that?**

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors_tmp
class MidpointNormalize(colors_tmp.Normalize):
    def __init__(self, vmin=None, vmax=None, vcenter=None, clip=False):
        self.vcenter = vcenter
        colors_tmp.Normalize.__init__(self, vmin, vmax, clip)

    def __call__(self, value, clip=None):
        # I'm ignoring masked values and all kinds of edge cases to make a
        # simple example...
        x, y = [self.vmin, self.vcenter, self.vmax], [0, 0.5, 1]
        return np.ma.masked_array(np.interp(value, x, y))

fig, ax = plt.subplots(1,1)
sc = ax.imshow(img)

axpos = ax.get_position()
cbar_ax = fig.add_axes(
    [axpos.x1, axpos.y0, 0.01, axpos.height])  # l, b, w, h
cbar = fig.colorbar(sc, cax=cbar_ax)

fig, ax = plt.subplots(1,1)
sc = ax.imshow(img)

axpos = ax.get_position()
cbar_ax = fig.add_axes(
    [axpos.x1, axpos.y0, 0.01, axpos.height])  # l, b, w, h
cbar = fig.colorbar(sc, cax=cbar_ax)
midnorm = MidpointNormalize(vmin=0, vcenter=200, vmax=500)
cbar.mappable.set_norm(midnorm)
cbar.mappable.set_cmap('BrBG')

fig, ax = plt.subplots(1,1)
sc = ax.imshow(img)

axpos = ax.get_position()
cbar_ax = fig.add_axes(
    [axpos.x1, axpos.y0, 0.01, axpos.height])  # l, b, w, h
cbar = fig.colorbar(sc, cax=cbar_ax)
midnorm = MidpointNormalize(vmin=0, vcenter=800, vmax=1000)
cbar.mappable.set_norm(midnorm)
cbar.mappable.set_cmap('BrBG')
```

**The figures are listed as below:**

![](https://i.stack.imgur.com/MbKZc.png)

![](https://i.stack.imgur.com/qHaQo.jpg)

![](https://i.stack.imgur.com/JAmi3.jpg)

**For the expected outcome, I expected the np.NaN values would be plotted as white in the last two figures as what the first figure does. I didn't find any argument to control the np.NaN values in my case. I tried the ax.set_patch, and also set_bad(color=white), but they don't work...So how can I fix this issue? Thanks!**

**Matplotlib version**

  * Operating system MacOS: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7
  * Jupyter version (if applicable): Run in Spyder
  * Other libraries: None

**Comment by greglucas** [comment]
How did you use `set_bad`? You are passing in strings for the colormap.
You need to modify the colormap object to set the bad colors, something like this:
`cmap = plt.get_cmap('BrBG').with_extremes(bad='white')`

**Comment by jklymak** [comment]
I think this is more appropriate to discourse.matplotlib.org.  If you identify an issue there, please feel free to open an issue here, but as @greglucas says, `with_extremes` is the easiest way to sed the bad color.

**Comment by xushanthu-2014** [comment]
> .with_extremes(bad='white')

Hi @greglucas, thanks for your reply! I used
```
        current_cmap = cbar.get_cmap()
        current_cmap.set_bad(color = "white")
```
but it doesn't work... and for ```cmap = plt.get_cmap('BrBG').with_extremes(bad='white')```, I didn't find the ```with_extremes``` in ```cbar.mappable.get_cmap()```. It was said that ```AttributeError: 'LinearSegmentedColormap' object has no attribute 'with_extremes'```. So how could I use ```with_extremes``` for ```cbar```? thanks a lot!

**Comment by jklymak** [comment]
@xushanthu-2014 please take this to discourse.matplotlib.org, or continue the discussion you started on stackoverflow.  Please do not double-post, and please don't use GitHub for user help.
