### ISSUE TITLE
New colorbar doesn't handle norms without a scale properly...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#20324]
As reported at astropy by @dstansby:  (astropy/astropy#11800) colorbars with norms that do *not* have a scale associated with them are not being ticked properly.  

```
import matplotlib.pyplot as plt 
import numpy as np
import matplotlib.colors as mcolors

fig, ax = plt.subplots()

pc = ax.imshow(np.arange(100).reshape(10, 10), norm=mcolors.TwoSlopeNorm(20, 0, 100), cmap='RdBu_r')

cb = fig.colorbar(pc, extend='both')
plt.show()

```

### 3.4.2 (correct)

![olddd](https://user-images.githubusercontent.com/1562854/120031714-05f3a380-bfae-11eb-9e14-622cf95f7b3c.png)

### Master (incorrect)

![newww](https://user-images.githubusercontent.com/1562854/120031742-0ee47500-bfae-11eb-9089-244fd8790434.png)

**Comment by jklymak** [comment]
BTW, I'm pretty sure this is an easy fix, but apparently we don't visually test any norms that are not created from scales anymore...  (though everyone should create their norm from a scale these days ;-))

**Comment by pllim** [comment]
Is it just me or the "incorrect" and "correct" plots look exactly the same?

**Comment by pllim** [comment]
Oh wait... Ah, I see the colors around "20" and "80" are different. Hard to tell at a glance when the sizes differ. Sorry for the noise.

**Comment by jklymak** [comment]
The other issue is that we could argue the 3.4.2 plot was incorrect, and that the colors should be the same in both before and after, but the scale should change.
