### ISSUE TITLE
FuncAnimation Named Arguments

### ISSUE THREAD

**Issue by Zeyuzhao** [matplotlib/matplotlib#20326]
### Problem

I would like to use named arguments in FuncAnimation.

Currently:
```
ani = matplotlib.animation.FuncAnimation(
  fig, update, frames=len(raw_history),
  interval=500, repeat=True, repeat_delay=1,
  fargs=(raw_history, action_history, style)
)
```
This would be slightly cumbersome when I change the order / type of arguments my function accepts. I could use `functools` to attach named parameters to the function `update`, but it would be nice if `FuncAnimation` can support this feature.

### Proposed Solution
```
ani = matplotlib.animation.FuncAnimation(
  fig, update, frames=len(raw_history),
  interval=500, repeat=True, repeat_delay=1,
  fkwargs={'raw_history': raw_history, 'action_history': action_history, 'style': style}
)
```
We keep the `fargs` parameter, but we also add an `fkwargs` for keyword parameters.

**Comment by anntzer** [comment]
I don't particularly like `fargs` to begin with (I prefer functools.partial), but given that it's here, adding fkwargs seems reasonable.

**Comment by timhoffm** [comment]
So why don‘t we discourage fargs and avertize partial instead, including the note that you can use kwargs there?

**Comment by anntzer** [comment]
That works for me too.

**Comment by jeffreypaul15** [comment]
This would just require adding fkwargs as keyword arguments right? I also noticed that `fargs` doesn't really have any sort of test written for it, can I give it a go?

**Comment by timhoffm** [comment]
Um, no. [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) lets you create new functions with some parameters bound.

This works for both positional
```
my_update = partial(update, raw_history, action_history, style)
```
and keyword argumetns
```
my_update = partial(update, raw_history=raw_history, action_history=action_history, style=style)
```
or any combination. This is a builtin capability of python and does not require any changes within matplotlib (except maybe that we should encourage this use in the `FuncAnimation` docs).

You can pass `my_update` to `FuncAnimation`, or use it inlined:
```
from functools import partial

ani = matplotlib.animation.FuncAnimation(
  fig,
  partial(update, raw_history=raw_history, action_history=action_history, style=style),
  frames=len(raw_history), interval=500, repeat=True, repeat_delay=1,
)
```

**Comment by tacaswell** [comment]
In defense of saying "use partial" rather than adding support for `fkwargs` is cite https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_later

> The optional positional args will be passed to the callback when it is called. If you want the callback to be called with keyword arguments use functools.partial().

**Comment by tacaswell** [comment]
@jeffreypaul15 What would be super helpful would be a note in the `FuncAnitamation` docstring pointing users at `functools.partial` and maybe updating / tweaking an existing example or adding a new example that make use of `functools.partial`.
