### ISSUE TITLE
```boxplot``` shows number of data?

### ISSUE THREAD

**Issue by DachuanZhao** [matplotlib/matplotlib#20335]
### Problem

I'm always frustrated when I use ```boxplot``` because it can't shows the number of data of every box .
And here is the [stackoverflow](https://stackoverflow.com/questions/67761622/boxplot-shows-number-of-data/67761793#67761793) .

### Proposed Solution

Add a bool parameter ```show_number_of_data``` in ```boxplot```

**Comment by timhoffm** [comment]
I don't think it's a reasonable idea to add that functionality to `boxplot` itself. `boxplot` in itself already has a lot of parameters. The problem with adding a `show_number_of_data` parameter is that it won't stay with this single parameter. As soon as we do that, people want to be able to specify its position relative to the box horizontally and vertically, possibly with additional offsets. You'll want to specify font size, color etc. Just compare what's configured in the linked stackoverflow example. This would end up with several additional parameters.

While I understand the desire to have just this one convenient extra, it would lead us down a rabbit hole and is asking too much of the function `boxplot`.

The recommendation for this is to either

- make a standalone function for labelling. See https://matplotlib.org/3.4.2/api/_as_gen/matplotlib.axes.Axes.bar_label.html for an example of bar labelling. If this gets more user attraction, we could add such a function to core Matplotlib. But for starters, I recommend that you write your own. And we'll see if there are more people wanting this as core Matplotlib function. (anybody, please comment below if you do).
- or wrap the boxplot in your own `numbered_boxplot()` function. For the stackoverflow example this would be something like:

```
def numbered_boxplot(*, **kwargs):
    box_plot = sns.boxplot(**kwargs)

    df = kwargs['data']
    x = kwargs['x']
    medians = df.groupby([x])['Col1'].median()
    counts = (df.groupby([x])['Col1'].count())

    vertical_offset = df['Col1'].median() * 0.05 # offset from median for display

    for xtick in box_plot.get_xticks():
        box_plot.text(xtick,medians[xtick] + vertical_offset,counts[xtick], 
                horizontalalignment='center',size='medium',color='w',weight='bold')
```

**Comment by tanujdhiman** [comment]
@timhoffm Yes.

**Comment by anntzer** [comment]
I agree with @timhoffm.  I'll close this, but we *could* consider the addition of a boxplot_label method similar to bar_label, if someone wants to PR that...
