### ISSUE TITLE
Cannot save plot as any format other than .png when using TkAgg backend on macOS

### ISSUE THREAD

**Issue by ssantichaivekin** [matplotlib/matplotlib#20357]
### Bug report

**Bug summary**

Cannot save plot from the graphical user interface as a format that is not .png when using TkAgg backend on macOS.
- This bug occurs when using Python.org python distribution but does not occur when using Homebrew's python distribution `brew install python@3.7`.
- This bug does not occur when using the default matplotlib backend (I assume it's `macosx`).

**Code for reproduction**

```python
import matplotlib
matplotlib.use('TkAgg') # remove this line -> bugs gone!
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.show()
```

**Actual outcome**

<img width="1128" alt="Screen Shot 2564-06-03 at 23 53 41" src="https://user-images.githubusercontent.com/19219105/120682763-0799fb80-c4c7-11eb-8c97-4b09b53ef8ec.png">
Other formats aside from .png are grayed out as shown in the photo.

**Expected outcome**

Other formats aside from .png are not grayed out and the user can save the file in other formats.

**Matplotlib version**

  * Operating system: macOS Big Sur 11.2 (20D64)
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: tried on 3.7.10 and 3.9.5 both installed from Python.org
  * Tck/Tk version: 8.6

This bug seems to be caused by interactions with newer versions of tk shipped with Python.org distributions. The homebrew python distribution `brew install python@3.7` which does not ship with tk does not cause this bug.

Related issue: https://github.com/ssantichaivekin/empress/issues/229

**Comment by tacaswell** [comment]
If you type `'Fig1.pdf'`  into the filename does it save a pdf?

> This bug occurs when using Python.org python distribution but does not occur when using Homebrew's python distribution brew install python@3.7.

This makes me worry that the issue is differences in the version of tk that is being used between the Python.org version and homebrew.

https://github.com/matplotlib/matplotlib/blob/11258c27be3a83832bff8659bd1a03ea2ad35aa6/lib/matplotlib/backends/_backend_tk.py#L697-L705
is where we set up create the file dialog so it might be worth testing if an extracted version of this code works with tkinter outside of Matplotlib.

attn @richardsheridan

**Comment by ssantichaivekin** [comment]
@tacaswell If I type `.pdf` in the filename and press save, this box will pop up saying I cannot save as `.pdf`.

<img width="169" alt="Screen Shot 2021-06-04 at 9 50 52 AM" src="https://user-images.githubusercontent.com/19219105/120738637-6472d180-c51a-11eb-89e5-3a2101223e9b.png">

**Comment by richardsheridan** [comment]
I won't be much help since I don't have access to a mac, but I tend to agree it looks more like a tkinter bug than a matplotlib bug.

**Comment by ssantichaivekin** [comment]
@tacaswell I will try to solve this issue and open a pull request.

**Comment by ssantichaivekin** [comment]
It seems that this is a tkinter problem indeed. This simple tkinter code also reproduces the bug:
```python
from tkinter.filedialog import asksaveasfilename
asksaveasfilename(
    filetypes=[
        ("Text files", "*.txt"),
        ("Microsoft Word file", "*.docx"),
    ]
)
```

<img width="839" alt="Screen Shot 2021-06-05 at 1 33 08 PM" src="https://user-images.githubusercontent.com/19219105/120882505-94959f80-c602-11eb-8374-8a985a244e46.png">
