### ISSUE TITLE
Distorted Plots when using Floating Axes in Jupyter Notebooks

### ISSUE THREAD

**Issue by znusbick** [matplotlib/matplotlib#20366]
### Bug report

When running the following in my terminal, the correct images come up, but when running it through a jupyter notebook, the images are distorted.

```python
from matplotlib.transforms import Affine2D
import mpl_toolkits.axisartist.floating_axes as floating_axes
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist.grid_finder import (FixedLocator, MaxNLocator,
                                                 DictFormatter)

fig = plt.figure(figsize=(8, 4))
    
tr = Affine2D().scale(2, 1).rotate_deg(30)

    
grid_helper = floating_axes.GridHelperCurveLinear(
    tr, extremes=(-0.5, 3.5, 0, 4),
    grid_locator1=MaxNLocator(nbins=4),
    grid_locator2=MaxNLocator(nbins=4))

    
ax = fig.add_subplot(
    131, axes_class=floating_axes.FloatingAxes, grid_helper=grid_helper)

aux_ax = ax.get_aux_axes(tr)


fig.subplots_adjust(wspace=0.3, left=0.05, right=0.95)

aux_ax.bar([0, 1, 2, 3], [3, 2, 1, 3])

plt.show()

```

A simple bar graph rotated 30 degrees should be the outcome.  This happens when running a .py file through the terminal, but not in a notebook.

I am running Jupyter Notebook 6.4.0 with Python 3.8 and Matplotllib 3.4.  Matplotlib was installed through Pip.

**Comment by jklymak** [comment]
Are you running with %matplotlib inline?   If so, that will resize your figure and possibly distort your axes because it calls bbox_inches='tight' before rendering the figure.  I think you can turn that off.  Or use %matplotlib notebook.  Perhaps the underlying issue could be fixed, but it's likely not easy

**Comment by znusbick** [comment]
> Are you running with %matplotlib inline? If so, that will resize your figure and possibly distort your axes because it calls bbox_inches='tight' before rendering the figure. I think you can turn that off. Or use %matplotlib notebook. Perhaps the underlying issue could be fixed, but it's likely not easy

This is exactly it, the graphs look perfect now.  Thank you!

**Comment by jklymak** [comment]
It should probably still work with bbox_inches=tight, but, as you might imagine, that is hard...
