### ISSUE TITLE
Potential bug and potential solution about no texts in saved eps file

### ISSUE THREAD

**Issue by xushanthu-2014** [matplotlib/matplotlib#20364]
### no legend texts and tick labels in saved eps file

**There are no legend texts and tick labels in the saved eps file. Sometimes there are texts, but other times there are not. I checked that, I found that when I plot figures of long legend texts or long tick labels, there are no texts in the saved .eps file. My codes are pretty long. And I checked the small example you posted in https://github.com/matplotlib/matplotlib/issues/11372/, it worked fine. It's not easy to extract a small example to illustrate this because it sometimes works while sometimes it does not work. I will try to make a small example and get it back to you.**

When I simply use
```
import matplotlib
matplotlib.use('PS') 
```
It does not work, and the outcome is as below

![image](https://user-images.githubusercontent.com/60925333/120796504-2d60e800-c53b-11eb-845d-fadc7bf06cf6.png)

You can see that there is no texts in my legend and tick labels. But when I turn the texts to latex label as following:
```
import matplotlib
matplotlib.use('PS') 
matplotlib.rcParams['text.usetex'] = True
```
![image](https://user-images.githubusercontent.com/60925333/120796716-6ef19300-c53b-11eb-8860-b720702260e8.png)

It worked as below. So I guess there may be some bug of the default text fonts of Matplotlib?

(btw, the padding and the width of colorbar between two figures may be different, this is because I also fine-tuned the figure after I found how to solve the issue...I don't know why it didn't work previously, and don't understand why it worked when I turn the text.usetex to true...**notice that I don't use latex font in my figure**...so maybe there could be some bugs in the default font size of Matplotlib so that eps does not support it when the texts are too long?)

**Matplotlib version**

  * Operating system: macOS Catalina 10.15.6
  * Matplotlib version : 3.4.2
  * Matplotlib backend: PS
  * Python version: 3.7
  * EPS viewer: Preview in MacOS

**Comment by jklymak** [comment]
Maybe try `matplotlib.use('Agg')`m and then save as PDF after: `fig.savefig('out.pdf')`  Otherwise we'd need some more info about your settings and code.

**Comment by xushanthu-2014** [comment]
No, I tried ```matplotlib.use('Agg')```, it does not work. And for .pdf file, yes I could save it to pdf file. But under some specific situations, maybe only .eps file works.

**Comment by jklymak** [comment]
Closing for lack of follow up, but feel free to request a re-open if you have more details.
