### ISSUE TITLE
Change name of variables in histogram example

### ISSUE THREAD

**Issue by ainar** [matplotlib/matplotlib#20379]
I googled how to plot a distribution with matplotlib, and I found [this page](https://matplotlib.org/stable/gallery/statistics/hist.html).

I struggled understanding what happened there:
> To generate a 1D histogram we only need a single vector of numbers. For a 2D histogram we'll need a second vector. We'll generate both below, and show the histogram for each vector.
[...]
```
x = np.random.randn(N_points)
y = .4 * x + np.random.randn(100000) + 5
```

Problem is that variables are called `x` and `y` but have nothing to do with axis x and y (usually abscissa and ordinate).

Code is there:
https://github.com/matplotlib/matplotlib/blob/401aa2f7f2c155165b77d8e5f7cb98270f42054a/examples/statistics/hist.py#L30

Is there anything to do to to ease the understanding? I suggest to change the name of the variables from `x` and `y` to something else.

**Comment by timhoffm** [comment]
I suppose the first plot is intended to show the marginal distributions for x and y of the 2D random distribution. I agree that this is totally confusing as it is written here.

In general, I'm unclear what this example/guide is trying to communicate. It seems like a histogram tutorial, but only touching an arbitrary subset of features. As a rough outline:

1) 2D histograms are a separate functionality and should be pulled out to their own example. The should also be cross-ref'd with the `hexbin` example.
2) There are about a handful of "basic" histogram examples (not counting "using histograms to plot a cumulative distribution" or "prodcing multiple histograms side by side"). One should check if some of them can be merged together.

Point 1) and 2) can be done independently.
