### ISSUE TITLE
Test Coverage for TextBox

### ISSUE THREAD

**Issue by aitikgupta** [matplotlib/matplotlib#20370]
### Describe the issue
Currently, we have 0 test coverage for widgets like `TextBox`.
Other widgets are tested here: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_widgets.py

**Summary**
Following up from https://github.com/matplotlib/matplotlib/pull/20367#issuecomment-855178732, there might exist more widgets that aren't tested at all, but TextBox seems likely to be used by a substantial audience, so might be worth the attention.

### Proposed fix
Simple tests could involve testing `set_val`, `stop_typing`, callbacks like `on_text_change`, `on_submit`, etc could be a good starting point.

**Comment by hewittk** [comment]
Hi, I'm interested in taking this issue.

**Comment by aitikgupta** [comment]
Sure @hewittk, go ahead! :)
The relevant entrypoint is already mentioned in the issue, and if you face issues you can ping it here, or our [gitter](https://gitter.im/matplotlib/matplotlib) channel.

**Comment by dmatos2012** [comment]
Fixed by #20451
