### ISSUE TITLE
shrink argument in matplotlib.patches.annotate does not exist in FancyArrow

### ISSUE THREAD

**Issue by Martititi** [matplotlib/matplotlib#20389]
Hi,
### Problem

The documentation here:
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.annotate.html
suggests that you can use a "shrink" argument in a dictionary arrowprops containing options for drawing the FancyArrowPath.
However, it looks like it doesn't exist anymore and has been replaced by shrinkA and shrinkB, as documented here:
https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html#matplotlib.patches.FancyArrowPatch

### Suggested Improvement
Instead of writing shrink, maybe you can write shrinkA and shrinkB in the matplotlib.pyplot.annotate.html

**Matplotlib version**
  * Matplotlib documentation version (is listed under the logo): v3.4.2-2-gf801f04d09-dirty.
I see it's written dirty, I hope I'm on the right documentation haha ^^

Have a good one!
M.D.

**Comment by jklymak** [comment]
Shrink is a shortcut.  ShrinkA and shrinkB are described lower down in the annotate doc.  Did you try using shrink and it didn't work?

**Comment by Martititi** [comment]
I see. Indeed, I didn't see shinkA/B in there.


Yes, I used shrink, but I got this:
AttributeError: 'FancyArrowPatch' object has no property 'shrink'

**Comment by Martititi** [comment]
Nevermind, I didn't read well enough.
It's written shrink is forbidden in case I use the arrowstyle argument.

Sorry for the time spent here, and thank you for your work.

**Comment by jklymak** [comment]
Please provide more details how you got that error.  Shrink is only a valid key for the dict passed to arrowprops on the annotate method.  If that is not working that is a bug.
