### ISSUE TITLE
Using ax.spines with a polar plot

### ISSUE THREAD

**Issue by iosphere777** [matplotlib/matplotlib#20396]
Hello! I have a request but I think I should explain my problem first:

I'm trying to make a wedge shaped frame where I can have the ticks along the radial axis appear on the inside or outside of the axis. I've been plotting the ticks as little lines with ax.plot, so in order to make them appear outside of the theta limit, I had to increase the limit. This new frame is too large, so I'm trying to get rid of the frame on the right radial axis (or just move it). I think an image will help: 
<img width="497" alt="Screen Shot 2021-06-09 at 10 29 52 AM" src="https://user-images.githubusercontent.com/85631634/121389732-b3ee3e80-c91a-11eb-84aa-f312a404c6c6.png">

I was able to get rid the top theta axis using ax.spines["polar"].set_visible(False), then redraw it as an arc in the right location, so I was thinking I could do something similar for the radial axis, but I can't find any good examples with spines. Is there a way to use ax.spines to alter the radial axis in a polar plot like this? 

My code is pretty long and probably rather inefficient (I am a beginner, sorry), but if you think that might be helpful to see here it is: [(.](https://github.com/znusbick/Slicing/blob/main/pie%20plot%20with%20matplotlib%20polar%20.ipynb)

**Comment by jklymak** [comment]
Can we move this to discourse.Matplotlib.org, at least until a specific feature is being asked for?  Thanks!
