### ISSUE TITLE
Add ability to pass different kwargs when adding different subplots simultaneously through`plt.subplots`

### ISSUE THREAD

**Issue by phinate** [matplotlib/matplotlib#20392]
### Problem

I was just messing aroung with trying to see if I could use the (super nice!) `plt.subplot_mosaic` function with a mixture of 2d and 3d axes, but didn't get anywhere. Looking into it, it seems like it could be possible with `subplot_kw = {"projection": "3d"}`, but this is static across the different subplots (or more accurately, calls to `plt.add_subplot`).

### Proposed Solution

From looking at the source code (specifically at these line in `gridspec.py`, since that's where I believe the function calls eventually end up) it seems like it may be possible to package `subplot_kw`s in an object of size `_nrows` x `_ncols`, since that is the dimensions iterated over.https://github.com/matplotlib/matplotlib/blob/9c530bce8d9c25afee831310382b98e01a96146f/lib/matplotlib/gridspec.py#L299-L308

The only part that's unclear to me from an implementation standpoint is whether this would necessitate a new kwarg itself, or perhaps one can use single dispatch or conditional logic to handle the case where `subplot_kw` is not dict-like.

Happy to have a go if this is desired and/or the functionality exists already and I'm blindsighted to it :)

### Additional context and prior art

Could be many scenarios where one would want to control each subplot! I think it would be super neat to be able to do all this from one call to `plt.subplots` :D

**Comment by jklymak** [comment]
We have a way to do this already, which is to make the gridspec and then add the axes individually. I'm not sure how constructing an array of dicts is a preferable interface.

**Comment by phinate** [comment]
That's fair, though that gets tedious for complicated layouts -- helper functions in `plt.subplots` and `plt.subplot_mosaic` are the starting point for those kind of tasks, and I thought it could be useful to have that build in, since I didn't find a way to quickly modify one individual subplot to change its `projection` to 3d.

**Comment by jklymak** [comment]
You cannot change an axes' projection trivially.  However, you can get the subplotspec and make a new axes like:

```python
import matplotlib.pyplot as plt 

fig = plt.figure()
axs = fig.subplot_mosaic([['A', 'B'], ['C', 'B']])
ss = axs['B'].get_subplotspec()
axs['B'].remove()
axs['B'] = fig.add_subplot(ss, projection='3d')
plt.show()
```

**Comment by phinate** [comment]
Ah, this makes a lot of sense! That covers my particular use case,  thanks :)

Happy for the issue to be closed if you don't deem the original post to be an appropriate feature, but also open to more discussion!
