### ISSUE TITLE
Zooming with mouse wheel

### ISSUE THREAD

**Issue by srkunze** [matplotlib/matplotlib#20406]
### Problem

I usually want to zoom into some specific regions of a plot. Using the "rectangle" method feels slow given that Google Maps and similar services allow zooming using the mouse wheel.

### Proposed Solution

There are some work-arounds available on SO and gists. But I would love to see a standard solution which simply works out of the box.

### Additional context and prior art

https://stackoverflow.com/questions/11551049/matplotlib-plot-zooming-with-scroll-wheel

**Comment by ianhi** [comment]
Also https://github.com/matplotlib/matplotlib/issues/18159

**Comment by timhoffm** [comment]
I'll close this as a duplicate.
