### ISSUE TITLE
Using the slider to change color range

### ISSUE THREAD

**Issue by Korbinhu** [matplotlib/matplotlib#20433]
### Problem
In the current version of matplotlib.pyplot, the only way to change the color range is to set up limit and low limit separately. But for the requirement of frequently change the color range to significantly displaying data, it is not convenient to use the input value method. To this end, I suggesting to add a new feature or change the original setting to utilizing the slider to replace the input valve box.

**Comment by timhoffm** [comment]
Please be a little more specific. What is the context of this request? Are you referring to a specific example?

**Comment by story645** [comment]
is the functionality in #19515 similar to what you're requesting?

**Comment by Korbinhu** [comment]
Sorry! It is my carelessness. What I refer to is the general panel in Matplotlib as shown below:
![屏幕截图 2021-06-15 103002](https://user-images.githubusercontent.com/37903338/121984807-34eb8100-cdc6-11eb-8f52-711e3eceb87f.png)
However, change the colormap range by changing the value in the input box is not convenient. And what I want is to change this input box to a slider, which looks like below:
![屏幕截图 2021-06-15 103002 - 副本](https://user-images.githubusercontent.com/37903338/121985003-8ac02900-cdc6-11eb-83f4-652856cb04f8.png)

**Comment by QuLogic** [comment]
But what would be the minimum and maximum on _that_ slider?

**Comment by Korbinhu** [comment]
> But what would be the minimum and maximum on _that_ slider?

It is a good choice to change the minimum and maximum valve automatically or manually. Indeed, it should be changeable.

**Comment by timhoffm** [comment]
I'm closing this as beyond the scope of what core Matplotlib is aiming at and able to support.
We're primarily a plotting library for programmatic use. Configuarbility via a GUI is limited to basic use cases.

In particular, the case of colorbar range is not trivial. As pointed above, sliders need to have a range, but there is no generally suitable range. Additionally, one still needs the numeric controls to be able to set exact values. This means, both sliders and numeric controls must be syncronized. This is more complexity than what we are willing to add to the basic GUI.

We recommend that you add your slider for interactivity yourself. Direct ways would be matplotlib widgets (see e.g. https://matplotlib.org/3.4.2/gallery/widgets/range_slider.html) or [ipywidgets](https://ipywidgets.readthedocs.io/en/latest/) if you work with notebooks.

**Comment by jklymak** [comment]
I'll re-open, as this is basically exactly what is being proposed in #19515 - I'd rather see it implemented here first, rather than be part of the main GUI, at least until we get the kinks worked out....

**Comment by ianhi** [comment]
> We recommend that you add your slider for interactivity yourself. Direct ways would be matplotlib widgets (see e.g. https://matplotlib.org/3.4.2/gallery/widgets/range_slider.html) or ipywidgets if you work with notebooks.

If you are using an imshow and the underlying data isn't changing then you can use a rangeslider with the limits set to the max and min of the image. I'm not sure if this is exactly the same as what that gui is doing but I've found that hooking up the slider callback to the `vmin/vmax` of the images norm to be convenient. If you want this pre-implemented you can follow this example:  https://mpl-interactions.readthedocs.io/en/stable/examples/imshow.html#vmin-and-vmax:-thresholding-an-image (the gif uses ipywidgets but it will also work with pure matplotlib)

**Comment by QuLogic** [comment]
As a compromise, I think we can change these to spin boxes.  That would at least let you scroll through the values, similar to a slider. But unlike sliders, setting a plus/minus infinity range will not mean the increments are basically unusable.

**Comment by timhoffm** [comment]
Note also that the dialog has an „Apply“ button, which reduces usability as an interactive control .

**Comment by Korbinhu** [comment]
> As a compromise, I think we can change these to spin boxes. That would at least let you scroll through the values, similar to a slider. But unlike sliders, setting a plus/minus infinity range will not mean the increments are basically unusable.

I think that will be a good choice.

**Comment by Korbinhu** [comment]
> > We recommend that you add your slider for interactivity yourself. Direct ways would be matplotlib widgets (see e.g. https://matplotlib.org/3.4.2/gallery/widgets/range_slider.html) or ipywidgets if you work with notebooks.
> 
> If you are using an imshow and the underlying data isn't changing then you can use a rangeslider with the limits set to the max and min of the image. I'm not sure if this is exactly the same as what that gui is doing but I've found that hooking up the slider callback to the `vmin/vmax` of the images norm to be convenient. If you want this pre-implemented you can follow this example: https://mpl-interactions.readthedocs.io/en/stable/examples/imshow.html#vmin-and-vmax:-thresholding-an-image (the gif uses ipywidgets but it will also work with pure matplotlib)

An excellent solution. But in this method, it is also not convenient for us when saving the figure, because the interactive tool will be saved as well, and we have to deal with it in other software.

**Comment by timhoffm** [comment]
> I'll re-open, as this is basically exactly what is being proposed in #19515 - I'd rather see it implemented here first, rather than be part of the main GUI, at least until we get the kinks worked out....

Since #19515 has landed more than two years ago, I close this again as unneeded.
