### ISSUE TITLE
Horizontal colorbar position off in pdf when using subplots with constrained_layout 

### ISSUE THREAD

**Issue by maxnoe** [matplotlib/matplotlib#20434]
### Bug report

**Bug summary**

When storing plots as pdf, the colorbar is at the wrong position, off by a small amount:

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib

print(matplotlib.__version__)

rng = np.random.default_rng(0)
image = rng.normal(size=(40, 40))

# only happens at this exact figure size....
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(2.976338729763387, 1.4881693648816936), constrained_layout=True)
img1 = ax1.imshow(image)
img2 = ax2.imshow(image)
fig.colorbar(img1, orientation='horizontal', ax=ax1)
fig.colorbar(img2, orientation='horizontal', ax=ax2)
plt.savefig('colorbar.pdf')
```

**Actual outcome**

png converted from pdf output using `pdftoppm -r 600 -png -singlefile colorbar.pdf colorbar`:

![colorbar](https://user-images.githubusercontent.com/5488440/121939432-50667580-cd4d-11eb-8c95-cdb375c63842.png)

**Matplotlib version**

  * Operating system: Manjaro Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2 
  * Matplotlib backend (`print(matplotlib.get_backend())`): pdf (since plot saved as pdf)
  * Python version: 3.9.5

**Comment by jklymak** [comment]
It's not clear what you mean by "wrong".  Can you clarify?

**Comment by LukasNickel** [comment]
More or less exact.
`figsize=(2.97, 1.488)` and some slightly different values will also do the trick

**Comment by LukasNickel** [comment]
> It's not clear what you mean by "wrong". Can you clarify?

If you look closely at the colorbar, the colors and the border do not align perfectly

**Comment by jklymak** [comment]
I believe this is #6827.  (Note it has nothing to do with constrained_layout.). Suggest we close as a duplicate unless you think this is different.

**Comment by LukasNickel** [comment]
Interesting!
It seems indeed this only happens with the `dpi` set to `<=120`

**Comment by jklymak** [comment]
I mean it always happens, you just can't see it at higher resolution :wink:
