### ISSUE TITLE
Wrong text vertical position with LaTeX enabled

### ISSUE THREAD

**Issue by Lionel-dS** [matplotlib/matplotlib#20440]
### Bug report

**Bug summary**
Wrong vertical positioning of text elements when `rcParams['text.usetex']=True`.
The text kwarg `va="baseline"` and `"center_baseline"` seems to be the origin.
This is somehow linked to the inclusion, in the preamble of at least one of these two LaTeX packages: `chemformula` and `siunitx`. Oddly, it _does not depend_ on the use of these packages...
The error differs with `style.use('classic')`.

**Code for reproduction**
```python
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rcParams['axes.axisbelow'] = True       # Comment it for 'modern' version
plt.style.use('classic')                    # Comment it for 'modern' version
mpl.rcParams['text.usetex']=True
preamble=[r"\usepackage{siunitx}"]
preamble.append(r"\usepackage{chemformula}")# Comment it for 'siunitx' alone
mpl.rcParams['text.latex.preamble']=r"".join(preamble)
plt.plot()
plt.xlabel("X act")
plt.ylabel("This is Y")
plt.title("\LaTeX~with 'chemformula' or both in 'modern' MPL")
plt.text(-.05,0,"< Text at (-.05,0) baseline",color='r',va="baseline")
plt.text(-.05,0,"< Text at (-.05,0) center baseline",color='g',va="center_baseline")
plt.text(-.05,0,"< Text at (-.05,0) bottom",color='b',va="bottom")
```

**Displayed figures**
![Classic-SI](https://user-images.githubusercontent.com/85837764/122063937-fc14d180-cdf0-11eb-82d8-a15cd9756fb4.png)
![Modern-SI](https://user-images.githubusercontent.com/85837764/122063247-5feaca80-cdf0-11eb-857c-bd5e394241da.png)
![Classic-ChF](https://user-images.githubusercontent.com/85837764/122063198-582b2600-cdf0-11eb-8b5e-6eee3261c770.png)
![Modern-ChF](https://user-images.githubusercontent.com/85837764/122063228-5cefda00-cdf0-11eb-8ff6-42b997e005ca.png)

**Matplotlib version**

  * Operating system: MacOS Catalina 10.15.7
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.10 (anaconda 64bits up to date)
  * LaTeX: TeX Live 2021 (MacTeX)

**Comment by jklymak** [comment]
I _can_ reproduce on 3.3.4, but it is fixed on 3.4.2, so please upgrade.  Thanks!

**Comment by anntzer** [comment]
Actually I can repro with master with chemformula?

**Comment by jklymak** [comment]
Really? On v3.4.2 and master it works fine for me with chemformula enabled. TexLive2020, MacOS 11.x,  maybe its the "old" TexLive on my machine?

**Comment by anntzer** [comment]
I have texlive2021, I don't know if that's the difference.

**Comment by Lionel-dS** [comment]
Thanks! I hope the last version of mpl will comme soon with anaconda.
