### ISSUE TITLE
The document is incorrectly converted.

### ISSUE THREAD

**Issue by MasaYan24** [matplotlib/matplotlib#20468]
This may be happening in other places as well.

In the following function's argument, the _subs_ is passed as a tuple. And it is correct.
https://github.com/matplotlib/matplotlib/blob/b71ee62437c6305439fe796609a191a25ca072b5/lib/matplotlib/ticker.py#L2272

But if it is documented, the argument _subs_ is passed as a scalar. This is wrong.
https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.LogLocator
```console
class matplotlib.ticker.LogLocator(base=10.0, subs=1.0, numdecs=4, numticks=None)[source]
```

**Comment by timhoffm** [comment]
Thanks for the report!

This is a sphinx issue. I've reported this upstream in https://github.com/sphinx-doc/sphinx/issues/9364.

I'm closing this because we cannot do anything about it.
