### ISSUE TITLE
1D histogram returned from pcolormesh

### ISSUE THREAD

**Issue by clairekope** [matplotlib/matplotlib#20463]
### Bug report

**Bug summary**

I am plotting data with `pcolormesh` using `norm=LogNorm`. When I specify the optional X and Y bins, a 1D histogram is plotted instead of my expected 2D histogram.

**Code for reproduction**

[test_data.txt](https://github.com/matplotlib/matplotlib/files/6671918/test_data.txt)
[test_x.txt](https://github.com/matplotlib/matplotlib/files/6671919/test_x.txt)
[test_y.txt](https://github.com/matplotlib/matplotlib/files/6671920/test_y.txt)

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

x = np.genfromtxt("test_x.txt")
y = np.genfromtxt("test_y.txt")
data = np.genfromtxt("test_data.txt")

plt.pcolormesh(x, y, data, norm=LogNorm())
```

**Actual outcome**

This is a screengrab from jupyterlab but the bug also occurs in script form.

![goof](https://user-images.githubusercontent.com/16690685/122440166-4ec5c900-cf6a-11eb-8cbb-440e94a0da4a.png)

**Expected outcome**

Expected image was generated with Matplotlib 3.2.2 on a different system (still python 3.7). Minor differences might be apparent in the data, and overplotted lines are not included in the minimally working example. But this image displays the correct histogram behavior (2D instead of 1D) and correct axis extent/tick behavior.

![image](https://user-images.githubusercontent.com/16690685/122440852-f5aa6500-cf6a-11eb-8cb9-466d69fb154f.png)

**Matplotlib version**

  * Operating system: Linux Mint 19.3
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4 & 3.4.1 (tested both)
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.9
  * Jupyter version (if applicable): jupyterlab 3.0.7, but also occurs in script form
  * Other libraries: yt-4.0.dev0 (built from source; commit 89424c219) was used to extract the attached data

Matplotlib was installed via pip.

**Comment by jklymak** [comment]
There is no possibility that `pcolormesh` is returning a histogram from that exact code!  Please start from a fresh environment; you have somehow crossed definitions somewhere.  I'll close here; user help is available at https://discourse.matplotlib.org   Thanks!

**Comment by clairekope** [comment]
It absolutely does. I created a fresh environment.
```
$ conda create --name fresh matplotlib
$ conda activate fresh
$ which python
/home/claire/miniconda3/envs/fresh/bin/python
$ python pcolormesh_mwe.py 
$ cat pcolormesh_mwe.py 
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

x = np.genfromtxt("test_x.txt")
y = np.genfromtxt("test_y.txt")
data = np.genfromtxt("test_data.txt")

plt.pcolormesh(x, y, data, norm=LogNorm())
plt.show()

```
![image](https://user-images.githubusercontent.com/16690685/122445220-5340b080-cf6f-11eb-8fe4-98f574c6926c.png)

**Comment by jklymak** [comment]
My sincere apologies, you are correct.  I have zero idea what is causing this....

**Comment by tacaswell** [comment]
I think you also need to do

```python
ax.set_yscale('log')
ax.set_xscale('log')
```

as the correct plot has log scaling, the wrong one in linear and I think the main section on of the wrong plot is the little hat on the right plot.

**Comment by jklymak** [comment]
Yeah, this is not a histogram, the white space are zeros in your data.

**Comment by clairekope** [comment]
Ohh you are absolutely right. My apologies! Thanks for your time.

**Comment by jklymak** [comment]
![Figure_1](https://user-images.githubusercontent.com/1562854/122447850-0520b280-cf59-11eb-9956-79c332e31b20.png)

**Comment by tacaswell** [comment]
@clairekope Glad we got this sorted, good luck!
