### ISSUE TITLE
Modifier key press events not recognized on MacOSX backend

### ISSUE THREAD

**Issue by Pixadus** [matplotlib/matplotlib#20486]
### Bug report

**Bug summary**

Key press events identify every key, except modifiers (control, option, command and shift). This behaviour is different from that of Linux and Windows where modifiers are recognized. This behaviour is identical to what was presented in #9835, and supposedly fixed in #9836.   

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig = plt.figure()

def on_key(event):
    print('you pressed', event.key, event.xdata, event.ydata)

fig.canvas.mpl_connect('key_press_event', on_key)
plt.show()
```

**Actual outcome**

All characters recognized, except modifier keys. 

**Expected outcome**

We should be seeing identifiers, such as `shift` and `control` as output from the above script. 

**Matplotlib version**

  * Operating system: MacOS Big Sur 11.4
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.9.5
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

**Comment by tacaswell** [comment]
@Pixadus Could you check if this works for you on the 3.3.x series?  We did some work in 3.4 to unify the key handling and I'm worried we put a regression in.

Can you also check if this works with other backends (eg qtagg on tkagg) on OSX?

**Comment by Pixadus** [comment]
I took a look at it using `matplotlib==3.3.0`, however it exhibited the same behavior. Following your idea, I changed versions to `matplotlib=2.2.0`, the version this original issue was fixed in, and it still did not reveal any modifiers. 

Using `matplotlib.use('TkAgg')` with the code above _did_  show modifier keys, indicating it might just be an issue with the `MacOSX` backend. 

One additional thing of note - this computer is using one of the new M1 ARM-based processors. I'm not sure if that would impact this at all, but thought I should note.

**Comment by tacaswell** [comment]
This does seem like there is as issue newer versions of OSX.

This comment + commented code is worrying:

https://github.com/matplotlib/matplotlib/blob/6f92db0fc6aad8dfcdb197202b969a01e4391fde/src/_macosx.m#L2158-L2180

but I think the code that is actually run is:

https://github.com/matplotlib/matplotlib/blob/6f92db0fc6aad8dfcdb197202b969a01e4391fde/src/_macosx.m#L2024-L2086

but I have not traced through everything.
