### ISSUE TITLE
Documentation on Interpolations for imshow and Image antialiasing

### ISSUE THREAD

**Issue by Neoanarika** [matplotlib/matplotlib#20494]
### Problem

I found interpolations for imshow and image antialiasing to be unclear because for natural images it is fair to use hanning interpolations due to the frequency spectrum for natural images but for something like a matrix of random Bernoulli this can lead to aliasing effects and other interpolations schemes such as nearest would be more appropriate. In general, this also gives a good example for why we should use matshow instead for imshow to visualise matrices. 

Aliasing effects for hanning interpolations
<img width="1368" alt="Screenshot 2021-06-23 at 9 05 22 PM" src="https://user-images.githubusercontent.com/5188337/123101599-d037c280-d466-11eb-9548-1e63e0b14c86.png">

No aliasing effects for nearest interpolations
<img width="1377" alt="Screenshot 2021-06-23 at 9 05 36 PM" src="https://user-images.githubusercontent.com/5188337/123101604-d168ef80-d466-11eb-859a-ae5eedbeaca3.png">

Links:
- https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html
- https://matplotlib.org/stable/gallery/images_contours_and_fields/image_antialiasing.html

### Suggested Improvement

Include an example such as the one above of when nearest interpolations or matshow would be more appropriate then imshow with hanning. 

Code to reproduce the aliasing effects: 
https://colab.research.google.com/drive/1rnIc1mRPLz9nCsmg6Kt4G5erR3_A6dGv?usp=sharing

**Comment by jklymak** [comment]
Please include code in issues, its hard to tell what `X` is.

If the anti-aliasing is kicking in, you do not have enough resolution to see any details.  

There is a documentation draft at #18749 explaining the difference between data interpolation and optical anti-aliasing.  

There is a PR at #18782 to add optical anti-aliasing.  There is a pretty firm plan to make that available for 3.5.

**Comment by Neoanarika** [comment]
Hi @jklymak, X is a random matrix with Bernoulli distributions

<img width="1374" alt="Screenshot 2021-06-24 at 12 36 23 AM" src="https://user-images.githubusercontent.com/5188337/123135349-43036680-d484-11eb-9b6e-c5d3ff775858.png">

**Comment by jklymak** [comment]
As pointed out this would be closed by #18749 and #18782

(Code can be included in GitHub pages directly.  Please do not post screenshots.)  I'll close here as we are already aware of this concern and tracking it.
