### ISSUE TITLE
AnchoredText can not set prop

### ISSUE THREAD

**Issue by lwk1542** [matplotlib/matplotlib#20491]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by QuLogic** [comment]
Please fill in some details.

**Comment by timhoffm** [comment]
I'm closing due to lack of response. We're happy to reopen if you provide proper information.
