### ISSUE TITLE
rcParams['axes.autolimit_mode'] = 'round_numbers' is broken

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#20508]
### Bug report

... since 3.2.0. Compare the second plot in

https://matplotlib.org/3.2.0/gallery/ticks_and_spines/auto_ticks.html
https://matplotlib.org/3.1.1/gallery/ticks_and_spines/auto_ticks.html

Given that nobody has missed this so far, we might consider just removing this feature instead of repairing. If somebody really wants this, they can still calculate and set the limits themselves.

**Comment by anntzer** [comment]
It's not broken, just one of the many settings that don't work from within rc_context(): it's the value at show()time that gets used.
In the case of the tutorial we probably just need to switch to directly assigning to `rcParams`.
