### ISSUE TITLE
basemap drawmeridians not working?

### ISSUE THREAD

**Issue by am-thyst** [matplotlib/matplotlib#20506]
Usually basemap works fine for me, and even drawmeridians() worked fine until I tried this plot. I don't understand why it isn't working. Here's a reproducible code:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np

fig = plt.figure()
ax = fig.add_axes([0.1,0.1,0.8,0.8])

m = Basemap(projection='cyl',llcrnrlat=14.5,urcrnrlat=16.5,\
            llcrnrlon=-61,urcrnrlon=-62.5, resolution='h')

m.drawmeridians(np.arange(0,360,0.5),labels=[0,0,0,1],linewidth=1,fontsize=15,color="grey")
m.drawparallels(np.arange(0,180,0.5),labels=[1,0,0,0], linewidth=1,fontsize=15,color="grey")
m.drawcoastlines()

plt.show()
```

m.drawmeridians() just returns an empty {} and here's the output:

![image](https://user-images.githubusercontent.com/41115380/123290671-60c6df00-d509-11eb-8443-85df5734938a.png)

I really can't figure out what's happening - it works fine on a bigger domain. Surely there should be 5 meridians drawn on this plot? I've tried playing with the labels argument too but nothing works.

Versions: 
python: 3.8.5
matplotlib: 3.2.2
basemap: 1.3.0
basemap-data-hires: 1.2.2

**Comment by jklymak** [comment]
Please ask at https://github.com/matplotlib/basemap but be aware that basemap is not supported any more.

**Comment by am-thyst** [comment]
@jklymak  what's the recommended alternative to basemap?

**Comment by WeatherGod** [comment]
Cartopy

**Comment by jklymak** [comment]
I guess its easy to also point out that -62.5 is west of -61

**Comment by am-thyst** [comment]
@jklymak  ah how did I miss that! Thanks! It's definitely time for me to take a break.
