### ISSUE TITLE
Wrong shape of Z in documentation of contour

### ISSUE THREAD

**Issue by hobler** [matplotlib/matplotlib#20517]
The documentation of contour([X, Y,] Z, [levels], **kwargs) says that the shape of Z must be (M,N) where M=len(X) and N=len(Y). But shape of Z is required to be (N,M).
[contour_bug.txt](https://github.com/matplotlib/matplotlib/files/6715106/contour_bug.txt)

**Comment by timhoffm** [comment]
Thanks for the report. This has recently been fixed in #20495.
