### ISSUE TITLE
Bad boxplot legend entries

### ISSUE THREAD

**Issue by RSKothari** [matplotlib/matplotlib#20512]
### Describe the issue

**Legend for entries in boxplot are displayed as thin lines as opposed to patches**

When we have multiple box plots in the same axis, legend shows thin lines as opposed to boxes and it is difficult to tell entries apart. This issue has been documented at this link with a reproducible example.

### Proposed fix

I don't have a solution :( 

Link: https://stackoverflow.com/questions/68124486/improve-matplotlib-legend-for-boxplots-by-showing-patches-instead-of-lines

**Comment by story645** [comment]
Do you think the legend should use boxes as illustrated in the answer to that question? ![fGWNP.png](https://user-images.githubusercontent.com/1300499/123377207-b9be6380-d559-11eb-90d4-1e75db9ea860.png)

**Comment by RSKothari** [comment]
@story645 Yes, I think that should be the default behavior of legend when used on `boxplot`.

**Comment by anntzer** [comment]
I think this is *mostly* a matter of setting `label="_nolegend_"` on all artists generated by boxplot except the box itself (the black lines in the SO example come from the fact that we currently try to generate legend entries for the whiskers, caps, and outliers).
Even better would be to have a custom handler for boxplots, but that seems to be much more work.

**Comment by saranti** [comment]
Ever since v3.5, the first entry in the legend is shown as a rectangular patch with the rest shown as lines:

![box](https://github.com/matplotlib/matplotlib/assets/9763064/a7f44191-92ef-4854-bacf-101ab3ed168a)

It's the same regardless of the number of entries.
