### ISSUE TITLE
Toolbar zoom doesn't change autoscale status for versions 3.2.0 and above

### ISSUE THREAD

**Issue by trapezoid677** [matplotlib/matplotlib#20519]
When zooming using the toolbar icon, the autoscale status (for x and y) returned by Axes.get_autoscale_on() always remains True starting with version 3.2.0 and all versions above. It is working correctly with version 3.1.3.

**Comment by QuLogic** [comment]
Bisects to 2f6d98c3fe, or #17067; I _think_ this was unintended. cc @anntzer.
