### ISSUE TITLE
Improve 'Writing ReST Pages' section on docs

### ISSUE THREAD

**Issue by aitikgupta** [matplotlib/matplotlib#20522]
### Suggested Improvement
The documentation on reStructuredText: https://matplotlib.org/stable/devel/documenting_mpl.html#writing-rest-pages lacks some very common formatting like specifying the heading types (which is arbitrary in general, but might be worth putting down in docs for consistency throughout the documentation while writing/modifying one), links, etc.

The reST documentation links to: https://docutils.sourceforge.io/rst.html#reference-documentation, but it might also be worth pointing to a Sphinx side of it: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html (which seems a bit easier to read and navigate for someone new to writing docs).

I also didn't find anything which allows a user to directly open the generated docs: `make show`. (even though it generates local HTML files, it might be worth adding this command to docs as well).

**Matplotlib version**

  * Operating system:
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):
  * Matplotlib documentation version (is listed under the logo):

**Comment by timhoffm** [comment]
Most of above should be addressed by #20534.

I've opened a separate dedicated issue for the headings, which we explicitly have to document because there is no universal convention.

In "Writing ReST pages" we should only document formatting that is specific to Matplotlib. General "very common formatting" is covered by the links to Sphinx and docutils, we should not repeat that. AFAICS all other specific topics are already covered in "Writing ReST pages". But you are welcome to propose additional content that we may have overlooked.

**Comment by aitikgupta** [comment]
>  General "very common formatting" is covered by the links to Sphinx and docutils, we should not repeat that.

Yeah, I just added that we can also add a link to Sphinx side of the documentation.

> all other specific topics are already covered in "Writing ReST pages"

I think the docs still miss a written guide/sample which allows a user to directly open the generated docs: `make show`.
(even though it generates local HTML files, @tacaswell pointed out in one of the gitter messages about this command:
"there is `make show` which will open it but also `doc/build/html`",
and putting it in docs might be easier for somebody writing documentation?)

In general, this issue's first paragraph I think would well enough be handled by https://github.com/matplotlib/matplotlib/issues/20534, the second and third paragraph still need to be addressed. (if I correctly read @timhoffm's comment that is 😅)

**Comment by timhoffm** [comment]
Sorry, I mixed up the ticket numbers. Please read my comment above again, which now links correctly to the respectively mentioned content.

**Comment by aitikgupta** [comment]
> Sorry, I mixed up the ticket numbers.

Ah, no problem. I think the merged PR solves this issue entirely (except headings, for which we have a new issue).
Closing 👍🏼
