### ISSUE TITLE
Docs for building matplotlib on aarch64

### ISSUE THREAD

**Issue by sarthfrey** [matplotlib/matplotlib#20521]
### Problem

Based on https://github.com/matplotlib/matplotlib/issues/17813 this package can be built on aarch64, are these aarch64 builds available in any repository, or is building manually the only option?

### Suggested Improvement

Document state of each build: if it's available in a repo, build steps, etc

**Comment by QuLogic** [comment]
They're available on PyPI like any other wheels: https://pypi.org/project/matplotlib/#files

I'm not sure what to document here? Just install it as on any other architecture.

**Comment by sarthfrey** [comment]
Thanks @QuLogic currently I'm trying to build matplotlib 3.3.4 against numpy 1.19 (a lower version of numpy than usual). Based on https://github.com/matplotlib/matplotlib/blob/master/.github/workflows/cibuildwheel.yml the `min-numpy-version` indicates this should be possible - do you know how to do this?

**Comment by jklymak** [comment]
@sarthfrey your question is pretty ambiguous.  User help is available at https://discourse.matplotlib.org and I think this is more appropriately discussed there.  But in general, `pip install matplotlib==3.3.4 numpy==1.19` is how you access different versions.  I'm going to close and encourage using discourse at least until a definitive action item is identified. Thanks
