### ISSUE TITLE
Inconsistent behavior of Axes.fill_between with color and data orientation

### ISSUE THREAD

**Issue by gibsramen** [matplotlib/matplotlib#20526]
### Bug report

**Bug summary**

When passing a `color` to `Axes.fill_between`, the plot can have strange artifacts depending on the data order.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss

rng = np.random.default_rng(seed=42)

y = rng.poisson(3, 200)
kernel = ss.gaussian_kde(y)
x = np.linspace(-2, 10, 500)
values = kernel(x)

fig, axs = plt.subplots(2, 2, figsize=(10, 8))

axs[0, 0].fill_between(x, values)
axs[0, 1].fill_between(values, x)

axs[1, 0].fill_between(x, values, color="red")
axs[1, 1].fill_between(values, x, color="red")
```
**Outcome**

![image](https://user-images.githubusercontent.com/4030868/123533632-bc40ca80-d6cb-11eb-9f04-9e90ace50f2c.png)

The plot in the bottom right has a strange line going from `x = 0` to what seems to be the max value of `x`. This only occurs when the color is passed into `ax.fill_between` and for a certain orientation of the data. Additionally, the data plotted in red seems to extend farther along the margins than the default plot (e.g. the bottom right plot clearly extends to `y = 10`).

I have circumvented this issue in the meantime by plotting without color and just setting the `facecolor` of the curve manually. 

**Matplotlib version**
  * Operating system: macOS Big Sur 11.1
  * Matplotlib version: 3.4.2
  * Matplotlib backend: MacOSX
  * Python version: 3.9.5
  * Other libraries: 
    * Numpy 1.21.0
    * SciPy 1.6.3

Installed through conda from conda forge. Originally encountered this issue on Python 3.7.10.

**Comment by timhoffm** [comment]
In general, you cannot do `fill_between(values, x)`. That it works is in one case is pure coincidence. Filling has a direction. The signature is `Axes.fill_between(x, y1, y2=0, ...)`, i.e. you fill the vertical range *y1* and *y2* at the positions *x*. If you want to specify a horizontal range, you have to use [fill_betweenx()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.fill_betweenx.html), i.e.

```
axs[1, 1].fill_between(y=x, x1=values, color="red")
```
