### ISSUE TITLE
contour for cyclic functions

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#20548]
I tried to get a contour plot of the complex angles of a particular function, but always got one level too many around zeros and infinities. Consider the following MWE which is supposed to plot the contour line for `pi / 4` only. It plots `pi / 4` alright, but also `pi`.
```python
import numpy as np
import matplotlib.pyplot as plt

xmin, xmax = -3.0, 3.0
ymin, ymax = -3.0, 3.0
nx, ny = 500, 500

x = np.linspace(xmin, xmax, nx)
y = np.linspace(ymin, ymax, ny)
X, Y = np.meshgrid(x, y)
fZ = np.angle(X + 1j * Y)

plt.contour(X, Y, fZ, levels=[0.25 * np.pi], colors="k")
plt.gca().set_aspect("equal")
plt.show()
```
![screenshot](https://user-images.githubusercontent.com/181628/123930099-b5e27500-d98f-11eb-8339-0864d5f80e7d.png)

This is with mpl 3.4.2.

_Edit:_ A very similar report is [on stackoverflow](https://stackoverflow.com/q/16197171/353337).

**Comment by QuLogic** [comment]
Below the line is -pi, above the line is +pi; this transitions past pi/4, so there's a line there. That seems expected, if not desired. The problem's not really a discontinuity, but a wrap/cyclic value. Maybe that needs a different contouring algorithm.

**Comment by nschloe** [comment]
The easiest thing is perhaps to manually remove that part of the contour. Is it possible to retrieve and manipulate the contour lines?

**Comment by nschloe** [comment]
Got it:
```python
import numpy as np
import matplotlib.pyplot as plt

xmin, xmax = -3.0, 3.0
ymin, ymax = -3.0, 3.0
nx, ny = 500, 500

x = np.linspace(xmin, xmax, nx)
y = np.linspace(ymin, ymax, ny)
X, Y = np.meshgrid(x, y)
fZ = np.angle(X + 1j * Y)

level = 0.25 * np.pi
c = plt.contour(X, Y, fZ, levels=[level], colors="k")

lc = c.collections[0]
new_segments = []
for segment in lc.get_segments():
    x, y = segment.T
    z = x + 1j * y
    is_false = np.abs(np.angle(z) - level) > 1.0e-5
    x[is_false] = np.nan
    y[is_false] = np.nan
    new_segments.append(np.column_stack([x, y]))

lc.set_segments(new_segments)

plt.gca().set_aspect("equal")
plt.show()
```
![screenshot](https://user-images.githubusercontent.com/181628/123947121-4aed6a00-d9a0-11eb-8d0f-b67b740d0e1c.png)

**Comment by nschloe** [comment]
I finally got it all done: Proper grid lines in [cplot](https://github.com/nschloe/cplot)!

![a3](https://user-images.githubusercontent.com/181628/124122825-cf122100-da76-11eb-9417-2efdbaf87930.png)

(They indicate the the absolute value and the angle.) Thanks again for the hint!
