### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.numerix'

### ISSUE THREAD

**Issue by elcolie** [matplotlib/matplotlib#20545]
### Bug report

ModuleNotFoundError: No module named 'matplotlib.numerix'

**Code for reproduction**

```python
import matplotlib.numerix as nx
import pylab as p

def boltzman(x, xmid, tau):
    """
    evaluate the boltzman function with midpoint xmid and time constant tau
    over x
    """
    return 1. / (1. + nx.exp(-(x-xmid)/tau))

x = nx.arange(-6, 6, .01)
S = boltzman(x, 0, 1)
Z = 1-boltzman(x, 0.5, 1)
p.plot(x, S, x, Z, color='red', lw=2)
p.show()
```

**Actual outcome**

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_13/3092351171.py in <module>
----> 1 import matplotlib.numerix as nx
      2 import pylab as p
      3 
      4 def boltzman(x, xmid, tau):
      5     """

ModuleNotFoundError: No module named 'matplotlib.numerix'
```

**Expected outcome**

**Matplotlib version**

  * Operating system: OSX 10.15.7
  * Matplotlib version 3.3.4+2.g422e5374f (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend module://ipykernel.pylab.backend_inline (`print(matplotlib.get_backend())`): 
  * Python version: 3.8.6
  * Jupyter version (if applicable): 
```
  jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.21.0
ipykernel        : 6.0.0a0
jupyter client   : 6.1.11
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5
```

Default installation

**Comment by story645** [comment]
Numerix has been deprecated since 0.98 (https://matplotlib.org/stable/api/prev_api_changes/api_changes_0.98.x.html), but you can get that functionality from numpy

```python
import numpy as np

np.arange(-6, 6, .01)
```

**Comment by QuLogic** [comment]
And it was removed in 1.1 https://matplotlib.org/stable/users/prev_whats_new/whats_new_1.1.html#numerix-support-removed If you're following some sort of tutorial, it is _highly_ outdated.
