### ISSUE TITLE
Expose legend's line: `legline._legmarker` as public

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#20552]
### Problem
I would like to be able to modify the alpha of both the line and marker in a legend as an extension of this example: https://matplotlib.org/stable/gallery/event_handling/legend_picking.html

However, currently the only way to access the marker in in the legend in order to set it's alpha value is via the private `legline._legmarker` attribute.
https://github.com/matplotlib/matplotlib/blob/108e1b0caa575bb761c8d5b21b2c7c14faea514a/lib/matplotlib/legend_handler.py#L254

This is not ideal for the reasons that @jklymak noted in https://github.com/matplotlib/matplotlib/issues/9155#issuecomment-327238310

> This is pretty hacky, and the undrscore means it could go away.

So with the current public api the best you can achieve is:
![image](https://user-images.githubusercontent.com/10111092/123998222-45dbeb00-d99f-11eb-8aa9-a96aa80e4eee.png)

when what I want is:
![image](https://user-images.githubusercontent.com/10111092/123998174-3b215600-d99f-11eb-8039-b40bf53f0531.png)

### Proposed Solution

The simplest solution would be to drop the underscore on the legmarker and add modifying the marker to the example as a way of documenting.

**Comment by tacaswell** [comment]
Labeling this as a good first issue as the tasks are:

 - remove an underscore (in several places)
 - add a new-feature note
 - add example

_might_ be worth keeping the `_` version around to be kind to anyone who was using this "un-officially" but am 50/50 on that.

**Comment by QuLogic** [comment]
Looks like a typo in the issue number.

**Comment by ianhi** [comment]
> might be worth keeping the _ version around to be kind to anyone who was using this "un-officially" but am 50/50 on that.

I'm :+1:  on keeping the `_` version with a (deprecation?) warning attached. There are ~1000 results on github for `_legmarker` https://github.com/search?q=_legmarker&type=code and on a personal note my newest pypi package uses it.

**Comment by QuLogic** [comment]
I think this would effectively be fixed by #11358.

**Comment by anntzer** [comment]
Agreed that #11358 would be nice.

**Comment by param-thakker** [comment]
Hi @tacaswell, is this still open? I'm a first time contributor and would love to work on it.
