### ISSUE TITLE
Have `[Source]` in api docs link to github

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#20557]
### Problem
The `source` link in the docs:
![image](https://user-images.githubusercontent.com/10111092/124034481-41c4c300-d9c9-11eb-9419-410711c583b6.png)

links to the matplotlib source on the website. This is ok, but subsequent navigation of the code is more frustrating than on github. For example I can't figure out how to the get to the folder containing https://matplotlib.org/stable/_modules/matplotlib/widgets.html#AxesWidget

### Suggested Improvement
Have these be appropriate permalinks to github. This is what scipy does, see: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html#scipy.spatial.distance.cdist

I think the downside is in the archaeology sense that github is perhap more impermanent than the matplotlib website.

**Comment by param-thakker** [comment]
Hi @ianhi , Can I work on this? I'm a first time contributor. Also, where can I find this source link in the codebase?

**Comment by ianhi** [comment]
Hi @param-thakker anyone is welcome to work on any issue so feel free to have a go at it. That said this issue probably deserves some discussion from other people before being implemented as it's not clear that everyone would view it as an improvement.

**Comment by timhoffm** [comment]
:+1: On this. Those code pages are massive in our code base (to an extend that we've deactivated upload of these pages for CI) and the code is on github anyway. I don't think impermanence of github is a practical issue. The only downside would be that you might loose the docs source link for old versions if GitHub goes away and we move to something else. That's as unlikely as it's bearable.

@param-thakker You're welcome to work on this.
The source links are generated by sphinx. One can modify this behavior through the [sphinx.ext.linkcode](plugin https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html).

See also https://github.com/scipy/scipy/blob/b8bdbbf112413e9a8f5e209fc05d3b8927718b28/doc/source/conf.py#L427 for the solution in SciPy.

**Comment by tacaswell** [comment]
There is also some re-hosting of our docs on internal (air-gapped) networks or just on laptops so there are some use cases where having all of the links be internal is nice.

**Comment by timhoffm** [comment]
It was decided on the dev call, that we want to move to linking to github. @param-thakker You are welcome to pick this up.

**Comment by jklymak** [comment]
Note we also would like it so there was a switch on the sphinx config to build with the rendered source so folks could optionally build the old way, if feasible

**Comment by rajpratyush** [comment]
is this issue still open for work?

**Comment by timhoffm** [comment]
Yes. You‘re welcome to pick it up.

**Comment by chachaleo** [comment]
Is this issue still open?

**Comment by timhoffm** [comment]
This is still open, but with a proposed solution in #20673.

**Comment by dmatos2012** [comment]
Merged in #20673
