### ISSUE TITLE
Change in custom norm colour map display

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#20581]
Compare https://matplotlib.org/stable/tutorials/colors/colormapnorms.html

![image](https://user-images.githubusercontent.com/302469/124570164-9d9daa80-de14-11eb-86b4-91979081c562.png)

vs https://matplotlib.org/devdocs/tutorials/colors/colormapnorms.html

![image](https://user-images.githubusercontent.com/302469/124570133-97a7c980-de14-11eb-9072-4c63204bf1d7.png)

The same thing happens with the custom norm at the end of the tutorial. I'm not sure about `TwoSlopeNorm`, but at least for the custom one, the 0 is definitely not supposed to be in the middle. This _half_ broke when merging #20054, with the 0 tick at the old place but the 0 colour in the middle. Then with d1c5a6ab163f507e8b0f1b3871e0de8d72266098, the 0 tick also moved to the middle.

**Comment by jklymak** [comment]
The tick moving to the middle is expected - colorbars are supposed to space equally in colourspace (i.e. consider log norm).  

The -1000 is more problematic, as that is simply incorrect I believe.  Part of the issue here is that two-slope norm doesn't have a scale, and hence doesn't have good ticking.

**Comment by jklymak** [comment]
... the Custom norm is in even worse shape ;-)

**Comment by jklymak** [comment]
OK, the -1000 is because TwoSlopeNorm didn't extrapolate at all, and so -1000 == -500.  Adding extrapolation fixes that.

The `MidpointNormalize` example was broken because `MidpointNormalize` did not define an inverse.  Defining an inverse also fixes this.
