### ISSUE TITLE
plt.subplot_mosaic error with sharex/sharey argument

### ISSUE THREAD

**Issue by jnboehm** [matplotlib/matplotlib#20604]
### Bug report
Using the argument sharex or sharey with a call to subplot_mosaic results in an error.  It is not possible to create a figure with shared x- or y-axis with subplot_mosaic.

The [devdoc documentation](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.subplot_mosaic.html) mentions the arguments for sharex/sharey, whereas the [classic api](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot_mosaic.html) does not mention them for the version 2.4.2. Could it be that this bug is already fixed for an unreleased version?

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.subplot_mosaic("a", sharey=True)
```

**Actual outcome**

The keyword argument is passed on to the constructor of Figure, which does not understand the keyword argument.
```
TypeError: __init__() got an unexpected keyword argument 'sharey'
```

**Expected outcome**

The figure is created with the respective axis shared across axes.

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.9.6
  * Jupyter version (if applicable): n/a
  * Other libraries: n/a

Matplotlib was installed via system packages.

**Comment by jklymak** [comment]
Yes the sharing is new.  You can set the sharing post-facto.

**Comment by jnboehm** [comment]
Thank you for the information! For completeness sake, how would I go about this? I have not found anything regarding this in the documentation, or is that also not yet released?

In any case, thanks for the answer, I'll close this then and wait for the next release.

**Comment by jklymak** [comment]
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.sharex.html
