### ISSUE TITLE
BUG: Lost functionality of interactive selector update

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#20618]
In MNE we allow users to update the selector colors, and have:
```
        selector.rect.set_color(color)
        selector.rectprops.update(dict(facecolor=color))
```
This now emits a deprecation warning from #20113, but it doesn't indicate how code should be migrated. I looked at this and #20558 and hoped / thought maybe I could find some `selector.set_*` or `selector.handle_props` or something to modify but I don't see anything. How should we update our code? (And it might be worth improving the deprecation warning to give some hints to anyone else who hits this issue.) Maybe with something like this?
```
selector.artists[0].set_color(color)
```
the `artists[0]` is the `selector.rect`. But this just seems like a hack workaround, and if there are properties held internally it will not "stick" so I'm guessing it's not the right idea...

_Originally posted by @larsoner in https://github.com/matplotlib/matplotlib/issues/20113#issuecomment-877345562_

**Comment by jklymak** [comment]
@ericpre @timhoffm any suggestions here?  Thanks!

**Comment by ericpre** [comment]
I would lean toward having something along the line of `selector.set_props` and `selector.set_handle_props` for all selectors. Should it be done as part as part of #20585, where there is a discussion about renaming corresponding parameters?

**Comment by QuLogic** [comment]
Well, since that's merged, it'll have to be a new PR, but yes, I expect it should be some `.set_*` methods, and not accessing the child artists directly.
