### ISSUE TITLE
Axis transforms don't work correctly in jupyterlab

### ISSUE THREAD

**Issue by vincenzon** [matplotlib/matplotlib#20619]
Calls to ax.transAxes  / ax.transData do not work as expected when called within the same jupyterlab cell as the ax.plot call. If they are run in a different cell, they work as expected.

In a jupyter cell run:

```
fig, ax = plt.subplots()
ax.plot([10,20,30], [0.1, 0.2, 0.3])
ax.transAxes.inverted().transform(ax.transData.transform((20, 0.2)))
```
I expect to get back something like (0.5, 0.5) since the given data point (20, 0.2) is at the center of the plot. Instead the above returns the original point (20, 0.2). 

If I run the same transformation in a different cell,

```
ax.transAxes.inverted().transform(ax.transData.transform((20, 0.2)))
```

I get the expected output (0.5, 0.5).

Matplotlib: 3.4.2
Backend: module://ipykernel.pylab.backend_inline 

Jupyterlab: Version 3.0.16

**Comment by jklymak** [comment]
The default limits are 0...1, and they don't get changed until you trigger a relim, which you can do with `ax.autoscale_view()`.  

We prefer user help to go to https://discourse.matplotlib.org.  We can always open a bug report if a bug is identified.

**Comment by vincenzon** [comment]
OK, for future searchers:

```
fig, ax = plt.subplots()
ax.plot([10,20,30], [0.1, 0.2, 0.3])
ax.transAxes.inverted().transform(ax.transData.transform((20, 0.2)))
ax.autoscale_view()
ax.transAxes.inverted().transform(ax.transData.transform((20, 0.2)))
```

In a single cell produces the correct result. My bad. not a bug, just unexpected behavior that looks like one.
