### ISSUE TITLE
MarkerStyle transformation not carried over to legend

### ISSUE THREAD

**Issue by mdaeron** [matplotlib/matplotlib#20613]
### Bug report

When I transform a MarkerStyle, it displays fine in the plot but not in the legend.

**Code for reproduction**

```python
import matplotlib.pyplot as ppl
from matplotlib.markers import MarkerStyle

hdiamond = MarkerStyle("d")
hdiamond._transform.rotate_deg(90)

ppl.plot(0, 0, marker = hdiamond, label = 'foo', ls = 'None')
ppl.legend()

ppl.show()
```

**Actual outcome**

<img width="278" alt="Screen Shot 2021-07-09 at 13 33 33" src="https://user-images.githubusercontent.com/33901276/125083891-32303300-e0c9-11eb-8c51-4f6ed05aab37.png">

**Matplotlib version**

  * Operating system: macOS 10.15.7 (19H15)
  * Matplotlib version: 3.3.4
  * Matplotlib backend: MacOSX
  * Python version: 3.7.10

**Comment by jklymak** [comment]
_transform is private.  Is this how we want end users making rotated markers?

**Comment by jklymak** [comment]
My understanding is that to rotate markers you should create a new Marker and specify it's path. That should work with legend.

**Comment by anntzer** [comment]
Ah, indeed, I missed the fact that this was accessing a private attribute...

**Comment by mdaeron** [comment]
So just to be sure, rotating built-in markers is not supported?

@jklymak, the only way I know to create a new marker is:

````python
import matplotlib.pyplot as ppl

m1 = [(0,-1), (-2,0), (0,1), (2,0), (0,-1)]
m2 = 'd'
m3 = [(-1,0), (0,3**0.5), (1,0), (-1,0)]

kw = dict(mfc = 'w', mew = 20, ms = 100)

ppl.plot(-1, 0, marker = m1, **kw)
ppl.plot(1, 0, marker = m2, **kw)

ppl.axis([-2, 2, -1, 1])
ppl.show()
````
Which yields:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/33901276/125093569-b804ac00-e0d2-11eb-813d-b1f5d0b11b2b.png">

The two methods look nothing alike because AFAIK there is no user-facing method to specify the `joinstyle` for path-defined markers. Am I missing another way to produce "pointy" horizontal diamonds?

**Comment by jklymak** [comment]
First, as far as I can tell the code above works fine on 3.4.2 - the marker is rotated 90 degrees in the legend

We could close this, or turn into an issue about better access to marker methods.  In particular, I don't see why we wouldn't expose joinstyle for the user to modify when creating a marker.  I think it should also be possible to have a `transform` argument, but transforms are always a bit messy.

**Comment by jklymak** [comment]
See #19195 for discussion of this.  I'll add the discussion of join style and close here, but PRs welcome for adding more functionality to markers!

**Comment by mdaeron** [comment]
> First, as far as I can tell the code above works fine on 3.4.2 - the marker is rotated 90 degrees in the legend

Oh, great, that's good news. Thanks.

> We could close this, or turn into an issue about better access to marker methods. In particular, I don't see why we wouldn't expose joinstyle for the user to modify when creating a marker.

That would be really neat, especially since something like `(5, 1, 0)` produces a star with yet another joinstyle (`bevel`).

**Comment by jklymak** [comment]
Adding rotation has the approval of the core devs, someone just has to do it!  I don't see why anyone would object to adding jointstyle at the same time.
