### ISSUE TITLE
stackplot scaling/plotting problem?

### ISSUE THREAD

**Issue by dudelovetech** [matplotlib/matplotlib#20622]
Matplotlib version affected: 3.4.2
Python version: 3.7.8

Hi,
I have encountered this issue with the 'stackplot ' feature, when there a sudden drop of the value of the data points, in my case: 90K to 30K. the plot doesn't show the correct value on the graph.

Output graph: please see the circled data points
![image](https://user-images.githubusercontent.com/20567254/125144199-f6e63200-e0d1-11eb-8a90-11e2328aec79.png)

Expected graph:
![image](https://user-images.githubusercontent.com/20567254/125144288-3ad93700-e0d2-11eb-97f8-5edb7171e005.png)

I've also attached the dataset I used, the issue occurred at X-axis = 8.55555
[dataset.txt](https://github.com/matplotlib/matplotlib/files/6794292/dataset.txt)

**Comment by jklymak** [comment]
Please open a discussion at https://discourse.matplotlib.org with a self-contained example of the issue, including minimal code.  Thanks for your understanding!
