### ISSUE TITLE
PyPy wheels are pinned to v3.3, so pypy-based wheels for latest versions are not available

### ISSUE THREAD

**Issue by mattip** [matplotlib/matplotlib#20637]
### Bug report

**Bug summary**

In the cibuildwheel configuration there is a condition to pin PyPy wheels on 3.3 https://github.com/matplotlib/matplotlib/blob/14b34fd18685d037fc4d67d40df69b602b22ec7f/.github/workflows/cibuildwheel.yml#L96-L100

Is that on purpose? I would be nice to have PyPy wheels for the latest versions

**Comment by QuLogic** [comment]
PyPy did not support 3.7, which was our minimum in 3.4. The initial releases that did were not in cibuildwheel and also buggy, but new releases may have fixed it.

**Comment by QuLogic** [comment]
Test build: https://github.com/QuLogic/matplotlib/actions/runs/1024626242

**Comment by QuLogic** [comment]
OK, guess there still hasn't been a release adding `Py_DTSF_ADD_DOT_0`; new test build: https://github.com/QuLogic/matplotlib/actions/runs/1024666763

**Comment by mattip** [comment]
It was added in v7.3.4, released in April. I wonder why cibuildwheel is not using the latest v7.3.5 released in May, which fixes some problems with win64.

**Comment by mattip** [comment]
The latest build is missing METH_FASTCALL, which was also added in v7.3.4

**Comment by QuLogic** [comment]
I don't know why, but yea, waiting for cibuildwheel to update is what I remember now. 

We can actually build 3.4, except for aarch64, looks like: https://github.com/QuLogic/matplotlib/runs/3052871926

**Comment by QuLogic** [comment]
Testing with cibuildwheel 2: https://github.com/QuLogic/matplotlib/actions/runs/1046732676

**Comment by mattip** [comment]
Cool!

**Comment by tacaswell** [comment]
This appears to be broken on the default branch after I merged 3.4.x up.

```
gcc -pthread -DNDEBUG -O2 -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_backends__tkagg_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -Isrc -I/opt/pypy/pypy3.7-7.3.3/site-packages/numpy/core/include -I/opt/pypy/pypy3.7-7.3.3/include -c src/_tkagg.cpp -o build/temp.linux-x86_64-3.7/matplotlib.backends._tkagg/src/_tkagg.o -fvisibility=hidden -flto
1110
    src/_tkagg.cpp:208:7: error: ‘METH_FASTCALL’ was not declared in this scope
1111
           METH_FASTCALL },
1112
           ^~~~~~~~~~~~~
1113
    src/_tkagg.cpp:208:7: note: suggested alternative: ‘METH_STATIC’
1114
           METH_FASTCALL },
1115
           ^~~~~~~~~~~~~
1116
           METH_STATIC
1117
    error: command 'gcc' failed with exit status 1
1118
    ----------------------------------------
```

**Comment by tacaswell** [comment]
The `METH_FASTCALL` line came in via 741ee02d184586747155aa69ca2e5a8c584a3beb / https://github.com/matplotlib/matplotlib/pull/19167

**Comment by tacaswell** [comment]
Sigh, I should read the top of the thread before posting, I see @mattip predicted this problem in https://github.com/matplotlib/matplotlib/issues/20637#issuecomment-878781730

**Comment by QuLogic** [comment]
Ah yes, that's why I only sent the original CI change to v3.4.x.
