### ISSUE TITLE
DOC: Document patch deprecation

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#20635]
### Problem

In #20481 `colorbar.patch` was deprecated, so doing for example (in our code that [makes a DraggableColorbar](https://github.com/mne-tools/mne-python/blob/a8c197d47cb32d07b16cf8e257ff168b05d9fe1a/mne/viz/utils.py#L1241-L1252)):
```
cbar.patch.figure.canvas.mpl_connect('button_press_event', on_press)
```
Now yields:
```
The patch attribute was deprecated in Matplotlib 3.5 and will be removed two minor releases later.
```

### Suggested Improvement

It would be good to know what other attribute to use instead of `cbar.patch` in order to do things like control interaction. It would be nice if the emitted warning and API notes were updated, but at least one or the other would help.

**Comment by jklymak** [comment]
Cbar.ax.figure should work.

**Comment by larsoner** [comment]
Ahh yes, that's true in my case because I want the figure anyway. Feel free to close, or leave open if you think it's worth adding a note about how the patch properties might otherwise be modified (since it's possible people might be using `cbar.patch` somehow that way, too?)

**Comment by jklymak** [comment]
The patch really wasn't doing anything, so it's hard to know what message would be helpful in general. 

Btw thanks a lot for testing master!
