### ISSUE TITLE
imshow displayed color for same value changes

### ISSUE THREAD

**Issue by yumasheta** [matplotlib/matplotlib#20657]
### Bug report

**Bug summary**

When using `imshow` to plot a 2D numpy array with fixed values, the color of the same cell (with fixed value) changes only based on how many other colors are displayed.

**Code for reproduction**

Preparation code (sorry for the large data set, but its the shortest I could reproduce the issue with)
```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
cmap = matplotlib.cm.get_cmap(name="nipy_spectral")
bounds = list(range(-1, 33))
norm = matplotlib.colors.BoundaryNorm(bounds, cmap.N)
clb = fig.colorbar(
            matplotlib.cm.ScalarMappable(norm=norm, cmap=cmap),
            orientation="horizontal",
            location="top",
        )
clb.set_ticks(bounds)

data = np.array([[20.0, 20.0, 7.0, 7.0, 15.0, 15.0, 11.0, 11.0, 11.0, 11.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 1.0, 1.0,
         1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 16.0, 16.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 7.0, 7.0, 7.0, 7.0, 15.0, 15.0,
         11.0, 11.0, 24.0],
        [20.0, 20.0, 7.0, 7.0, 15.0, 15.0, 11.0, 11.0, 11.0, 11.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 1.0, 1.0,
         1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 16.0, 16.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 7.0, 7.0, 7.0, 7.0, 15.0, 15.0,
         11.0, 11.0, 24.0],
        [20.0, 20.0, 7.0, 7.0, 11.0, 11.0, 11.0, 11.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 7.0, 7.0, 7.0, 7.0, 11.0, 11.0,
         24.0],
        [20.0, 20.0, 7.0, 7.0, 11.0, 11.0, 11.0, 11.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0,
         16.0, 16.0, 16.0, 16.0, 16.0, 7.0, 7.0, 7.0, 7.0, 11.0, 11.0,
         24.0]])
```
If you then execute this the output is correct:
```python
ax.imshow(data[:,:-1], norm=norm, cmap=cmap, origin="lower")
plt.show()
```
![Figure_correct](https://user-images.githubusercontent.com/59456929/125982941-5a36089a-20ee-4aa3-b9d8-9333cbbb1b9b.png)

But if you add the last column, the output is incorrect, the cells in the center have changed color.
```python
ax.imshow(data, norm=norm, cmap=cmap, origin="lower")
plt.show()
```
![Figure_incorrect](https://user-images.githubusercontent.com/59456929/125982945-f6e70e25-c84f-412d-b8e9-6171afa3c22e.png)

To narrow the bug down:
If you plot the full data, but change the last column to a value that is already present, the output is correct again.
So this looks like an issue of how many colors, not how much data is plotted.

**Expected outcome**

The cells in the center shouldn't change color based on what other colors are displayed.

**Matplotlib version**

  * Operating system: Linux 5.12.15-arch1-1 x86_64 GNU/Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Reproducable for TkAgg, and Jupyterlab widget
  * Python version: 3.9.6
  * Jupyter version (if applicable): 
     - ipykernel: 6.0.2
     - notebook: 6.4.0
     - jupyterlab: 3.0.16
  * Other libraries: 
     - numpy: 1.21

Installed via pip in Python `venv` virtual environment.

**Comment by jklymak** [comment]
This is a pretty classic over-under problem.  Your bounds are right on 0 and 1 and your data is right in 0 and 1.  Given that, which colour do you expect to be shown when z=1.0.  The color above 1.0 or the color below?  Floating point round off picks one or the other for you and as you can see that is not deterministic.  

Suggest you put your bounds solidly bracketing the values. 

Also, why are you making the colorbar independently of the image?  You can just pass the mappable returned from imshow rather than making a dummy mappable. 

I'm going to close as there is no bug per-se

**Comment by yumasheta** [comment]
Thank you very much. Also for the tips.
I also thought it was an over/under issue. But it was reproducable for many different color setups. But I'm no expert, that's why I'm here.

To get proper behavior for the example code in this post one should use like @jklymak said:
```python
bounds = np.arange(-1.5, 32.5)
```
This ensures that the boundaries of the different color zones are centerd around the data points.

Thanks again.
