### ISSUE TITLE
Minor grid line not showing when a minor tick falls on a major tick

### ISSUE THREAD

**Issue by peguerosdc** [matplotlib/matplotlib#20653]
### Bug report

**Bug summary**
Grid lines setting `which='minor'` not showing when a minor tick happens to be at a major tick (that's my theory).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

# create sample matrix
matrix = np.random.default_rng(seed=42).random((50,50))

# create sample ticks
ticks = np.arange(0.2,1.8,0.032)
X, Y = np.meshgrid(ticks, ticks)

# plot (colors and alpha are chosen to emphasize the bug)
fig, ax = plt.subplots(figsize=(9,9))
ax.pcolormesh(X, Y, matrix, alpha=0.2)
ax.set_xticks(ticks, minor=True)
ax.set_yticks(ticks, minor=True)
ax.grid(which="minor", color="black")
plt.show()
```

**Actual outcome**

Notice in the image below that there are two missing grid lines for `x=1, y=1`. By inspecting the minor ticks `ticks` (see the output below), you can notice that `x=1, y=1` is indeed a minor tick, but is probably hidden because it happens to fall on a major tick as well (in this case, major ticks are the default).

![bug](https://user-images.githubusercontent.com/7889726/125797958-51d126af-98d1-4196-b489-a61889026df1.png)

````python
# outcome of print(ticks)
[0.2   0.232 0.264 0.296 0.328 0.36  0.392 0.424 0.456 0.488 0.52  0.552
 0.584 0.616 0.648 0.68  0.712 0.744 0.776 0.808 0.84  0.872 0.904 0.936
 0.968 1.    1.032 1.064 1.096 1.128 1.16  1.192 1.224 1.256 1.288 1.32
 1.352 1.384 1.416 1.448 1.48  1.512 1.544 1.576 1.608 1.64  1.672 1.704
 1.736 1.768]
````

**Expected outcome**

I am expecting to see a grid line at `x=1, y=1` which I have drawn with a red line using Paint in the image below.

![bug](https://user-images.githubusercontent.com/7889726/125799084-08a37ef0-b6d3-4ed8-a438-457156398f85.png)

**Matplotlib version**

  * Operating system: I have tried on Ubuntu 20.04.2 and CERN's Linux version
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.10
  * Other libraries: numpy 1.20.1

Matplotlib and Numpy were installed using `pip install matplotlib numpy`

**Comment by timhoffm** [comment]
By default, minor grid positions that overlap with major grid positions are removed to prevent double draws, which can look weird in case of antialiasing.

You can prevent that removal by:
```
ax.xaxis.remove_overlapping_locs = False
ax.yaxis.remove_overlapping_locs = False
```
