### ISSUE TITLE
MAINT: CircleCI build merged PRs

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#20658]
### Describe the issue

CircleCI (unlike Travis, AppVeyor, Azure, GitHub Actions, etc.) by default just builds PR branches themselves, as opposed to those PRs merged with `upstream/master`. This forces people to rebase to deal with issues that crop up, for example in https://github.com/matplotlib/matplotlib/pull/20585#issuecomment-881693489, and also decreases uniformity across CIs.

### Proposed fix

For a while (years?) in MNE now we have manually merged pull requests after the `checkout` step. I'm happy to [port our code](https://github.com/mne-tools/mne-python/blob/main/.circleci/config.yml#L64-L72) if people agree it would be useful. The only time it breaks or dies is when there are merge conflicts (i.e., the code can't be successfully merged), which arguably is fine behavior because people should merge/rebase at that point anyway.

*EDIT:* Also need [these lines](https://github.com/mne-tools/mne-python/blob/main/.circleci/config.yml#L27-L31)

**Comment by QuLogic** [comment]
Sure, feel free to PR it here. I've also been meaning to cop the better name for the CircleCI artifact check job that you have.
