### ISSUE TITLE
Matplotlib does not work on M1 mac running on VS Code Insiders (Apple Silicon)

### ISSUE THREAD

**Issue by michaelwaldman** [matplotlib/matplotlib#20667]
### Bug report

**Bug summary**

I can not under any circumstance import matplotlib for usage on my m1 mac. I have everything set to translate through Rosetta, or in native Apple Silicon dev environment. I get the following stack trace which leads me to believe that it's using x86 (or a dependency is)

**Code for reproduction**

```python3 
# import matplotlib
#
#
```

**Actual outcome**
Stack trace error

# If applicable, paste the console output here

    import matplotlib
```
  File "/Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/matplotlib/rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "/Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/matplotlib/animation.py", line 34, in <module>
    from PIL import Image
  File "/Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): no suitable image found.  Did find:
        /Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
        /Users/michaelwaldman/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
```

**Expected outcome**
being able to use and run matplotlib 

**Matplotlib version**

  * Operating system:  OS X Big Sur 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):  3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): unable to do this since I can't import 
  * Python version:  3.9.6
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by anntzer** [comment]
Based on the traceback, you cannot even import `PIL` (which is a dependency of Matplotlib).  So you should report the issue to them (at https://github.com/python-pillow/Pillow), and figure out how to make `from PIL import Image` work.
