### ISSUE TITLE
Small issue with "Save figure" dialog

### ISSUE THREAD

**Issue by klonuo** [matplotlib/matplotlib#2068]
In below dialog screenshot "Save as type" listbox is misleading, as it just filters contents from current folder and it doesn't save to selected format unless user changes the filename extension to match selected output format.

Common dialogs with "Save as type" listbox, just show the name of the file and extension is deduced from selected listbox item.

Also while posting this, I'll note merely esthetic, that this dialog call is very old, but I don't know how normal "Save as" dialog can be evoked

![screenshot](http://i.imgur.com/QWBLKuo.png)

**Comment by petehuang** [comment]
1.5.3 - TkAgg currently changes the file name to match the extension chosen in the "Save as type" field

**Comment by jklymak** [comment]
PyQT doesn't have this dialog, and @petehuang says its fixed for TkAgg, so I'll close this, but feel free to reopen if I'm wrong.
