### ISSUE TITLE
Legend.get_lines() not returning same object as in ax.legend(handels)

### ISSUE THREAD

**Issue by ukleiner** [matplotlib/matplotlib#20681]
### Bug report

**Bug summary**

When creating a custom legend the Line2D objects returned by the legend get_lines() functions aren't the Line2D objects used to create the custom legend.  
I'm doing an interactive legend and this complicates my code as now I need to relay on the order of the lines coming back from get_lines().
I tried to follow the legend creation process and didn't find the creation of new Line2D objects, so I'm unable to contibute a fix.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
lines = [Line2D([0], [0], color='blue', ls='solid', lw=2),
         Line2D([0], [0], color='red', ls='solid', lw=2)]

fig, ax = plt.subplots(1, 1, figsize=(4, 4))

legend_lines, line_names = lines, ['a', 'b']
leg = ax.legend(legend_lines, line_names)
plt.show()
print(legend_lines, leg.get_lines())
```

**Actual outcome**

```
[<matplotlib.lines.Line2D object at 0x7f196a888670>, <matplotlib.lines.Line2D object at 0x7f196a850ee0>]
[<matplotlib.lines.Line2D object at 0x7f196a80dca0>, <matplotlib.lines.Line2D object at 0x7f196a819430>]
```

**Expected outcome**
The same objects in both lists

**Matplotlib version**

  * Operating system: *Debian 10.10*
  * Matplotlib version: *3.3.4*
  * Matplotlib backend: *module://ipykernel.pylab.backend_inline*
  * Python version: *3.9.1*
  * Jupyter version: *3.0.3*
  * Other libraries: 
Installed with conda from the default channel

**Comment by jklymak** [comment]
The assumption is that the line you pass in is one that you want a legend created _for_ - its not the actual line Matplotlib draws in the legend.  Happy for suggestions as to how this could have been clearer in the documentation.  I'm not really clear from the above what you are trying to ultimately do, but I don't think there is a bug here.

**Comment by ukleiner** [comment]
You are right, I was expecting a behavior for a very specific case.

**Comment by jklymak** [comment]
Feel free to discuss more at discourse.matplotlib.org if there is more we can help with!
