### ISSUE TITLE
offsetbox AnnotationBbox updates OffsetImage without initiating a new instance of the AnnotationBbox object

### ISSUE THREAD

**Issue by rbcsong** [matplotlib/matplotlib#20685]

**Comment by jklymak** [comment]
Can you provide some code to explain what you mean?

**Comment by rbcsong** [comment]
I found a walk around by display/change images in subplot.
I will let you know if the walk around could be worked out.
Appreciate your prompt response.

**Comment by jklymak** [comment]
I'll close here, but feel free to ask for a reopen if you have more details.  Thanks!

**Comment by rbcsong** [comment]
Hi Jody,The method ax.clear() was used in my case to refresh data. You may close this case.Thank you so much,Liping
    On Thursday, July 22, 2021, 10:35:01 AM EDT, Jody Klymak ***@***.***> wrote:  
 
 


I'll close here, but feel free to ask for a reopen if you have more details. Thanks!
