### ISSUE TITLE
Is there any potential imprecision for tricontourf? 

### ISSUE THREAD

**Issue by zhangxiaofan993** [matplotlib/matplotlib#20694]
### Suggested Improvement

**Matplotlib version**

  * Operating system:
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`):
  * Matplotlib documentation version (is listed under the logo):

**Comment by jklymak** [comment]
Can you clarify this?  All contouring is interpolation so I'm not clear what the question refers to.

**Comment by zhangxiaofan993** [comment]
Thank you for your reply! Based on my understanding, I could input my self-defined triangles to tricontourf so that it will use interpolation to generate contours. But I don't know the internal logic of interpolation. For example, does it use the triangles' centre to draw the contour? 
(I am a starter to this field, please forgive me if the question is stupid)

**Comment by zhangxiaofan993** [comment]
Also, for interpolation, there are linear interpolation, cosine interpolation, bilinear interpolation, etc. What kind of interpolation do we use for tricontourf?

**Comment by jklymak** [comment]
Please move algorithm discussion to https://discourse.matplotlib.org.  Thanks for your understanding!

**Comment by zhangxiaofan993** [comment]
Thank you!
