### ISSUE TITLE
Retina+jpeg option in jupyter

### ISSUE THREAD

**Issue by nspies-celsiustx** [matplotlib/matplotlib#20697]
### Problem

I often work with complex matplotlib figures with millions of points, which I've been displaying in my notebooks using the ipython magic `%config InlineBackend.figure_format = 'retina'`. Unfortunately, these inline images are quite large in terms of file size.

I'm looking for general suggestions on how to reduce the size of my ipynb files, which can grow into the 10s or even hundreds of MB in size and become a bit unwieldy.

### Proposed Solution

One thought I had was to switch to generating jpegs, but while it looks like I can meaningfully reduce the file size by switching the backend to jpeg and increasing the dpi to 2x:

```python
from matplotlib import rcParams
%config InlineBackend.figure_format = 'jpeg'
rcParams['figure.dpi'] = 200
```

I can't figure out how to size them appropriately for a retina display (they're twice as large as they should be, and slightly blurry). Is there a way to display jpegs in jupyter notebooks at similar resolution and size to the defaults provided by `'retina'` mode?

### Additional context and prior art

(Moved here from [this question](https://stackoverflow.com/questions/68429854/reduce-file-size-of-matplotlib-images-in-jupyter-notebooks) on stackoverflow.)

**Comment by jklymak** [comment]
This is an ipython configuration, and should be discussed on one of their channels.  

I doubt you will get any substantial improvements from jpg over png.  You will either have to drop to 100 dpi (for a factor of 4 drop) or manage your notebooks so they do not have so many figures in them.  

I'm going to close this here.

**Comment by nspies-celsiustx** [comment]
> This is an ipython configuration, and should be discussed on one of their channels.

Do you know where this configuration lives? Happy to open an issue there, but it's hard to understand how the different parts of the ecosystem take care of these things.

**Comment by jklymak** [comment]
https://github.com/ipython/matplotlib-inline
