### ISSUE TITLE
problem with closing Delaunay triangulation for a 3D geometry 

### ISSUE THREAD

**Issue by elifoo** [matplotlib/matplotlib#20691]
I'm trying to use matplotlib.tri function to obtain a 3D surface starting from a points cloud. The example that I report is a simplification of a more complex case to which I will then have to go and apply the code. I cannot understand why the result of the triangulation is not a closed surface. The geometry is quite simple, but I cannot understand why the triangulation does not close in on itself, but remains open. I have already tried to add a replica of the first points of the array, but the result does not change.

Any idea?

Thanks a lot!

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.tri as mtri

my_array = np.array([[ 2.83,  0.,    2.83],
 [ 0.,    2.83,  2.83],
 [-2.83,  0.,    2.83],
 [-0.,   -2.83 , 2.83],
 [ 2.83, -0. ,   2.83],
 [ 4.,    0. ,   0.  ],
 [ 0.,    4. ,   0.  ],
 [-4.,   0.  ,  0.  ],
 [-0.,   -4. ,   0.  ],
 [ 4.,  -0.  ,  0.  ],
 [ 2.83,  0. ,  -2.83],
 [ 0.,    2.83, -2.83],
 [-2.83,  0. ,  -2.83],
 [-0.,   -2.83, -2.83],
 [ 2.83, -0.,   -2.83]])



rad = np.linalg.norm(my_array, axis=1)
zen = np.arccos(my_array[:,2] / rad)
azi = np.arctan2(my_array[:,1], my_array[:,0])
    
triang_matplot = mtri.Triangulation(zen, azi).triangles


fig = plt.figure()
ax  = plt.axes(projection='3d')
ax.plot_trisurf(my_array[:,0], my_array[:,1], my_array[:,2], triangles=triang_matplot, cmap=plt.cm.RdYlBu)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

plt.show()


 
```

  * Operating system:  mac os 11.0
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): v. 3.3.3
  * Python version: 3.7.2

**Comment by jklymak** [comment]
Perhaps this could be discussed at https://discourse.matplotlib.org until a bug is identified?  Thanks for your understanding.
