### ISSUE TITLE
Streamplot Excluding Values or Lagging Values

### ISSUE THREAD

**Issue by michaelavs** [matplotlib/matplotlib#20700]
### Bug report

**Bug summary**

We are using streamplot to plot wind vectors in a vertical cross section plot. When printing the vector values out, the values indicate the vectors/streams should be going in one direction, but are instead plotting in a different direction. It appears that the issue may be that the data is being shifted on the outer data points, but towards the middle the data is being plotted correctly.

**Code for reproduction**

A link to the PR with full code: https://github.com/NCAR/GeoCAT-examples/pull/377/files 
Example of the data used and the streamplot call:
```python
# We attempt to recreate curly vectors with Matplotlib's streamplot function.
# streamplot requires the input parameter x, y to be evenly spaced strictly increasing arrays.
# Therefore we interpolate the original dataset onto an manually set, evenly spaced grid.
# There are probably more suitable interpolation routines than scipy's interp2d,
# but we do not have a standardized procedure for interpolation for streamplot as of this point.

# regularly spaced grid spanning the domain of x and y
xi = np.linspace(T['lat'].min(), T['lat'].max(), T['lat'].size)
yi = np.linspace(T['plev'].min(), T['plev'].max(), T['plev'].size)

# interp2d function creates interpolator classes
u_func = interp2d(T['lat'], T['plev'], V)
v_func = interp2d(T['lat'], T['plev'], wscale)
uCi = u_func(xi, yi)
vCi = v_func(xi, yi)

# Use streamplot to resemble curly vector
ax.streamplot(xi,
              yi,
              uCi,
              vCi,
              linewidth=0.5,
              density=2.0,
              arrowsize=0.7,
              arrowstyle='->',
              color='black',
              integration_direction='backward')
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/43652875/126351465-646b3db3-9be0-466c-9797-3291a36956d5.png)

```
# Using print statement to get the data ending in the bottom right corner of the plot:
print(xi[-1], '\n', uCi[-1], '\n', yi[-1],'\n', vCi[-1])
```
Yields:
```
87.86380004882812 
 [        nan         nan         nan  9.10609946  9.96490747 10.05100591
 10.02028723  5.8806693   1.91754698 -0.45503035 -1.47028324 -2.02342618
 -3.10894523 -4.02239422 -4.0318033  -3.17770667 -2.08648038 -1.58350315
 -1.40862297 -0.99775607 -0.56486768 -0.24857158  0.03063131  0.05289909
 -0.03224718  0.31239994  0.83799752  0.82292371  0.03899019 -1.00969351
 -1.37562045 -0.71866031  0.25565939  0.94128388  1.1784061   0.71532519
 -0.14007985 -0.62180622 -0.83093877 -1.22145464 -1.55633001 -1.69134959
 -1.65104571 -1.34737551 -0.66869868  0.28753878  0.87091469  0.30167497
 -0.88334064 -1.39366938 -1.36401842 -1.3742743  -1.26788581 -1.11150169
 -1.31900556 -1.25264353 -0.71608451  0.03890722  0.79599765  1.63949759
  1.81510566  1.37471521  0.86682685 -0.01197778] 
 900.0 
 [         nan          nan          nan 130.3611604  104.5385977
  68.92200324  48.40933714  -2.14139051 -22.47025063 -33.67125367
 -33.97668646 -32.26421813 -35.74751203 -23.45717115  -3.7260186
   5.29953699   5.78778922  -2.58911159  -2.79749448  16.38533941
  23.95939593  14.95667187  13.04704437  15.18092188  15.71739901
  15.67410181  -6.33579756 -39.25501978 -35.44800926 -15.89421275
 -24.2086606  -18.86332904  21.87416832  32.91458739   1.96618779
 -11.23789821   1.97345665   3.01164184 -13.98737324 -19.48240896
   4.4158896   32.76829408  40.70595259  43.68320917  44.98286062
  25.41354972   2.06000515  -3.00912489 -10.33525993 -17.31754861
  -6.74459543  -4.40112253 -12.6679496   -3.96490329   9.09023639
  -0.74144307 -15.91432006  -6.65229152  -1.09735159   2.32518633
   9.54650155   6.49148      5.16408421  11.9824823 ]
```
The right hand side of the plot is the most glaringly different part of the plot. The bottom level of vectors, if I'm reading this correctly, should be sloping upwardsBut throughout the plot there are other, smaller, differences with direction and magnitude of the vectors.

**Expected outcome**
Based on the values located in xi and yi, the vectors should be pointed primarily upwards. The original plot that we are attempting to recreate looks like:
![image](https://user-images.githubusercontent.com/43652875/126382110-2d669ea7-4656-4004-8cd2-58a8b62ec1b0.png)
Where you can see the right hand side has vectors going upwards. 

I noticed there was an [issue](https://github.com/matplotlib/matplotlib/issues/11452) about 3 years ago that had a very similar problem with streamplot and was due to an internal interpolation routine. I'm not sure if this is the exact same issue we are having, I did read the source code and it is up-to-date with the same fix as that issue, but maybe a place to start?

**Matplotlib version**

  * Operating system: macos Catalina 10.15.7
  * Matplotlib version 3.3.0 (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend module://backend_interagg(`print(matplotlib.get_backend())`): 
  * Python version: 3.8.10
  * Other libraries: 
 Scipy: 1.7.0
numpy: 1.21.0
metpy: 1.0.1
xarray: 0.18.2
 * Also uses function from GeoCAT-comp "[interp_hybrid_to_pressure](https://github.com/NCAR/geocat-comp/blob/main/src/geocat/comp/interp_hybrid_to_pressure.py)"

All packages were installed via conda forge from a .yml file.

**Comment by jklymak** [comment]
Can you narrow this down, preferably with a small synthetic data set?  Otherwise, it will be pretty hard for us to help.

**Comment by jklymak** [comment]
.. in fact if anything, it looks to me that you have your `v` (actually w) in exactly the opposite direction in these two plots.  I'm going to take the liberty of closing this, but definitely feel free to ask for a re-open if you extract the x, y, u, and v as stand-alone numpy arrays, and you identify unexpected behaviour on our end.  Thanks!

**Comment by jklymak** [comment]
Thanks for the understanding - just to keep the gigantic issue list clean ;-)
