### ISSUE TITLE
matplotlib.spines.Spine.get_extents provides wrong values in interactive mode

### ISSUE THREAD

**Issue by ljbrannmark** [matplotlib/matplotlib#20714]
### Bug report

**Bug summary**

I want to get the extents of my left axis spine, in display coordinates on Bbox format, using ax.spines['left'].get_extents().

In interactive mode, I would not expect to have to call fig.canvas.draw() or plt.pause() before calling ax.spines['left'].get_extents(). But apparently the wrong value is returned unless I first manually update the figure. Is this expected behavior in interactive mode?

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.cos(x)

plt.ion()

fig, ax = plt.subplots(figsize=(8,6))

ax.plot(x, y)
ax.set_title("Plot of y=sin(x)")
ax.set_xlabel('x')
ax.set_ylabel('sin x')

ax.spines['left'].set_bounds((-0.8, 0.8))

print('Result before fig.canvas.draw(): ', ax.spines['left'].get_extents())

fig.canvas.draw()  #plt.pause(0.01) also works

print('Result after fig.canvas.draw(): ', ax.spines['left'].get_extents())
```

**Actual outcome**

```
Result before fig.canvas.draw():  Bbox(x0=100.0, y0=527.538, x1=100.0, y1=527.538)
Result after fig.canvas.draw():  Bbox(x0=100.0, y0=128.99001414349192, x1=100.0, y1=464.99889046038794)
```

**Expected outcome**

**Matplotlib version**

  * Operating system:  Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable): 
  * Other libraries: numpy 1.19.5

**Comment by jklymak** [comment]
matplotlib does some things lazily, and updating the spine extents is one of these.  I'll close as this is expected behaviour.  (also for newer Matplotlib you can do `fig.draw_no_output()`.
