### ISSUE TITLE
ticklabels for range objects as integers rather than floats

### ISSUE THREAD

**Issue by ptoche** [matplotlib/matplotlib#20722]
According to https://docs.python.org/3/library/stdtypes.html, 'range' objects take 'integers'. I would therefore expect matplotlib to set the tick labels as integers, rather than floats. 

Feature request: treat range objects as lists of integers and not cast them to float.

    import matplotlib.pyplot as plt
    x = range(5, 9)
    y = []
    for n in x:
        y.append(n*(n+1)/2)
        print('type(x) = ', type(x))
    plt.scatter(x, y)
    plt.show()

Actual output:

![a](https://user-images.githubusercontent.com/6339274/126724438-17c220a1-be09-4981-8a4e-93c7d5fcbb83.png)

Expected/ Preferred output:

![b](https://user-images.githubusercontent.com/6339274/126725624-8ca6f898-9d7f-4da6-9a33-91cd1a248554.png)

Typecasting with `x = int(x)` does not help. The only workaround I found is `x = list(map(str, x)). 

I could also add this to my preamble, but it's un-memorizable, so I prefer casting to string:

    from matplotlib.ticker import MaxNLocator
    plt.axes().xaxis.set_major_locator(MaxNLocator(integer=True))

**Comment by jklymak** [comment]
You'd probably need to add a unit handler for lists of integers.  I think that would be pretty confusing personally, but you could try and get a PR in to do that.
