### ISSUE TITLE
Cursor in TextBox goes in slightly different points when surrounded from the same letters

### ISSUE THREAD

**Issue by Tortar** [matplotlib/matplotlib#20742]
### Bug report

**Bug summary**

The cursor in the TextBox widget goes in slightly different points when surrounded from the same letters

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from matplotlib.widgets import TextBox

class TextBox_new(TextBox) :
    
    def __init__(self, *args, **kwargs): 

        super(TextBox_new, self).__init__(*args, **kwargs) 

        self.text_disp.set_size(20) 


coord_box = [0.2, 0.2, 0.3, 0.175]
Box_input = plt.axes(coord_box)
text_box = TextBox_new(ax = Box_input, label = "")

text_box.set_val("10iiiiiiiiiii")

plt.show()
```

**Actual outcome**

this two different outcomes describe the issue because how you can see (otherwise zoom a bit) the cursor goes in two different places, but it should go in just one:

![fifth](https://user-images.githubusercontent.com/68152031/127077808-14767ec6-2d2e-41c8-b56c-f4dcac500de8.PNG)

![forth](https://user-images.githubusercontent.com/68152031/127077693-065f25ef-8cb7-4ce5-bc4d-087effe6e4a1.PNG)

**Expected outcome**

The same position for the cursor

**Matplotlib version**

  * Operating system: Windows 10 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.7
  * Jupyter version (if applicable): 
  * Other libraries: 

I installed matplotlib from pip

**Comment by Tortar** [comment]
I have noticed that if you set a very big font size the problem disappear, so maybe it is something due to rounding error?

**Comment by jklymak** [comment]
Does the cursor snap to a pixel?

**Comment by timhoffm** [comment]
Yes, the cursor snaps to pixels. This is needed to get the same cursor appearance in every position. If we would allow subpixel positions, the cursor would look different in different positions due to antialiasing.

I'm closing as won't fix. The current behavior is the best option.
