### ISSUE TITLE
[Bug]: subfigure position shifts on y-axis when x kwarg added to supxlabel

### ISSUE THREAD

**Issue by fluviotect** [matplotlib/matplotlib#20760]
### Bug summary

Location of subfigure shifts lower on y-axis when 'x' kwarg is used for supxlabel for that subfigure.
I've also posted to StackOverflow: https://stackoverflow.com/q/68567315/9249533

### Code for reproduction

```python
fig = plt.figure(constrained_layout=True, figsize=(10, 8))

# create top/bottom subfigs
# see https://stackoverflow.com/a/68553015/9249533
(subfig_t, subfig_b) = fig.subfigures(2, 1, hspace=0.05, height_ratios=[1, 3])

# put ax0 in top subfig
ax0 = subfig_t.subplots()

# create left/right subfigs nested in bottom subfig
(subfig_bl, subfig_br) = subfig_b.subfigures(1, 2, wspace=0.1, width_ratios=[3, 1])

# put ax1-ax3 in gridspec of bottom-left subfig
gs = subfig_bl.add_gridspec(nrows=1, ncols=9)

ax1 = subfig_bl.add_subplot(gs[0, :3])
ax2 = subfig_bl.add_subplot(gs[0, 3:6], sharey=ax1)
ax3 = subfig_bl.add_subplot(gs[0, 6:9], sharey=ax1)


ax1.set_title('Nov. 7 to Nov. 13')
ax2.set_title('Nov. 13 to Nov. 27')
ax3.set_title('Nov. 27 to Dec. 31')
ax2.get_yaxis().set_visible(False)
ax3.get_yaxis().set_visible(False)

subfig_bl.supxlabel("My Subfigure Label", x=0.54, size=12, fontweight='bold')

# put ax4 in bottom-right subfig
ax4 = subfig_br.subplots()
ax4.set_title('Some Other Title')
subfig_br.supxlabel('Other Subfigure SubLabel', size=12, fontweight='bold')
```

### Actual outcome

Body of subfigure shifts downward (lower on y-axis) and covers supxlabel

![image](https://user-images.githubusercontent.com/41835370/127401472-20570876-b098-4cc8-bed4-d58d5cfe9669.png)

### Expected outcome

subfigure position doesn't change. supxlabel shifts to right.

![image](https://user-images.githubusercontent.com/41835370/127401167-48803a9c-9d2c-4b52-b109-eec49cdc89de.png)

### Operating system

Windows 10 Pro

### Matplotlib Version

3.4.2

### Python version

3.9.5

### Jupyter version

3.0.16

### Installation

conda

### Conda channel

conda-forge

**Comment by jklymak** [comment]
This has nothing to do with subfigures, right?  This happens if you specify x or y in supx/ylabel even on a normal figure, I think.

**Comment by fluviotect** [comment]
Not sure.  I've only used suptitles to date.  Will do some more digging.  Cheers

**Comment by jklymak** [comment]
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(constrained_layout=True)
fig.supxlabel('Boo', x=0.54)
plt.show()
```
does the same thing.  I think this is an easy-ish fix, but you'll need a private workaround for now:

```python
lab = fig.supxlabel('Boo', x=0.7)
lab._autopos = True
```

**Comment by fluviotect** [comment]
Cheers!  that did the trick.

I see you've been involved with some other issues....is this a bug or did I mis-identify? If bug, should I re-title?

Also, if you want to post to the [SO](https://stackoverflow.com/q/68567315/9249533), I'll mark as accepted.

**Comment by jklymak** [comment]
No please don't post on S/O!  This is just a bug (or misfeature, I suppose), and folks really shouldn't need to set the private attribute.

**Comment by fluviotect** [comment]
Understood.  I deleted the SO question.
