### ISSUE TITLE
[Doc]: Add external resources to devdoc landing page

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#20762]
### Documentation Link

https://matplotlib.org/devdocs/

### Problem

The new landing page that went in with #20737 doesn't have the external resources (https://matplotlib.org/stable/resources/index.html). 

### Suggested improvement

External resources should probably be under learn until the page is spun off into its own thing. 

### Matplotlib Version

3.4.2.post1550+g7413aa92b5

### Matplotlib documentation version

3.4.2.post1550+g7413aa92b5

**Comment by timhoffm** [comment]
Closed by #20849.
