### ISSUE TITLE
[Doc]: Aliased methods in mplot3d appear twice in the docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20764]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.scatter

### Problem

Note that both scatter() and scatter3D() appear, although they are strict aliases of one another, duplicating much content.  (I'm not suggesting to get rid of the alias, just to dedupe them in the docs.)  Quite a few other methods exhibit the same duplication.

### Matplotlib Version

3.4.2.post1559+g3a46327c9c

### Matplotlib documentation version

3.4.2.post1559+g3a46327c9c

**Comment by marbled-toast** [comment]
This is no longer an issue.
