### ISSUE TITLE
[Bug]: from matplotlib import pyplot ERROR

### ISSUE THREAD

**Issue by panhaoyu** [matplotlib/matplotlib#20774]
### Bug summary

I'm from China and perhaps there's something wrong about it. I tried to fix it, but the project is tooooo complicated, so sorry that no solution for it.

```text
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from matplotlib import pyplot
Cannot decode configuration file C:\Users\panha\.matplotlib\stylelib\science.mplstyle with encoding cp936, check LANG and LC_* variables.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python39\lib\site-packages\matplotlib\pyplot.py", line 39, in <module>
    from matplotlib import rcsetup, style
  File "D:\Python39\lib\site-packages\matplotlib\style\__init__.py", line 1, in <module>
    from .core import use, context, available, library, reload_library
  File "D:\Python39\lib\site-packages\matplotlib\style\core.py", line 221, in <module>
    reload_library()
  File "D:\Python39\lib\site-packages\matplotlib\style\core.py", line 217, in reload_library
    library = update_user_library(_base_library)
  File "D:\Python39\lib\site-packages\matplotlib\style\core.py", line 174, in update_user_library
    styles = read_style_directory(stylelib_path)
  File "D:\Python39\lib\site-packages\matplotlib\style\core.py", line 184, in read_style_directory
    styles[path.stem] = rc_params_from_file(
  File "D:\Python39\lib\site-packages\matplotlib\__init__.py", line 798, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error=fail_on_error)
  File "D:\Python39\lib\site-packages\matplotlib\__init__.py", line 729, in _rc_params_in_file
    for line_no, line in enumerate(fd, 1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xc4 in position 44: illegal multibyte sequence
```

### Code for reproduction

```python
from matplotlib import pyplot
```

### Actual outcome

fail

### Expected outcome

run

### Operating system

windows 10

### Matplotlib Version

3.4.2

### Matplotlib Backend

unable to run

### Python version

3.9.6

### Installation

pip

**Comment by anntzer** [comment]
This looks like a misconfigured locale, but I wonder whether the correct solution here is to stop reading the matplotlibrc file using the user locale (as is currently done) and instead use e.g. the same method as python uses to determine the source file encoding (as defined by https://www.python.org/dev/peps/pep-0263/ and implemented by https://docs.python.org/3/library/tokenize.html#tokenize.open).  In particular, the idea is to make the interpretation of a file solely dependent of its binary contents, and independent of the OS locale configuration.  For example, currently, on a system where the default encoding is shift_jis_2004 or shift_jisx0213, the default matplotlibrc file would be (slightly) misread, as the `~` character (default value of savefig.directory) would be misread as `‾`.

**Comment by panhaoyu** [comment]
In the Chinese python community, it's a common consense that any text file should be opened with such code:

```python
with open('path.txt', mode='r', encoding='utf-8') as f:
    content=f.read()
```

hope to be helpful.

**Comment by panhaoyu** [comment]
And I just read the whole .matplotlib directory on my computer, i haven't found any Chinese character

**Comment by panhaoyu** [comment]
I removed the .matplotlib directory and now everything works well. Sorry I forgot to backup the directory for debug. I think I can close this issue.
