### ISSUE TITLE
[Bug]: wrong text alignment in svg export

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#20784]
### Bug summary

When exporting a figure to `svg`, for `rotation=90` text is always left-alignment, no matter how `va` and `ha` are actually set.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig,ax = plt.subplots()
for va in ['bottom','top']:
    for ha in ['left','right']:
        ax.annotate( f"{ha}+{va}",
                     xy=(1,0.5), xycoords='data',
                     va=va, ha=ha )
        ax.annotate( f"{ha}+{va}",
                     xy=(0.5,1.0), xycoords='data',
                     rotation=90,
                     va=va, ha=ha )

from matplotlib import rcParams
rcParams['svg.fonttype'] = 'none'
fig.savefig('figure.svg', format='svg')
```

### Actual outcome

(the code produces `figure.svg` which I cannot upload, because the type is not supported)

Here I open the `.svg` file in inkscape to illustrate the outcome:
![observed](https://user-images.githubusercontent.com/12622691/127876793-e74f0b24-feca-427c-888e-0ba9ad6ff081.gif)

### Expected outcome

This is the alignment that I intend to achieve, but which seems to be impossible to produce:

![expected](https://user-images.githubusercontent.com/12622691/127876904-2e809807-5963-4ea5-8a10-336a3338a7dd.gif)

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.3.2

### Matplotlib Backend

Qt5Agg

### Python version

3.8.6

### Installation

conda

### Conda channel

conda-forge

**Comment by QuLogic** [comment]
I think what you want is to set the rotation mode to 'anchor':
```python
        ax.annotate(f"{ha}+{va}",
                    xy=(0.5,1.0), xycoords='data',
                    rotation=90, rotation_mode='anchor',
                    va=va, ha=ha )
```

**Comment by baloe** [comment]
> I think what you want is to set the Text rotation mode to 'anchor':
> 
> ```python
>         ax.annotate(f"{ha}+{va}",
>                     xy=(0.5, 1.0), xycoords='data',
>                     rotation=90, rotation_mode='anchor',
>                     va=va, ha=ha)
> ```

You are right, `rotation_mode='anchor'` is what I need(ed). Thank you for pointing that out,
and sorry for the noise!
