### ISSUE TITLE
[Bug]: _supylabel get_in_layout() typo?

### ISSUE THREAD

**Issue by sspagnol** [matplotlib/matplotlib#20782]
### Bug summary

Is the line in 
(https://github.com/matplotlib/matplotlib/blob/e291cdbbf1bfb58415f30be6d2217350248e7dec/lib/matplotlib[_make_margin_suptitles]/_constrained_layout.py#L304) function correct, namely

```
if fig._supylabel is not None and fig._supxlabel.get_in_layout():
```

Should that be a fig._supylabel.get_in_layout() ?

### Code for reproduction

```python
from matplotlib.cbook import get_sample_data
import matplotlib.pyplot as plt

import numpy as np

x = np.linspace(0.0, 5.0, 501)

fig, (ax1, ax2) = plt.subplots(2, 1, constrained_layout=True, sharex=True)
ax1.plot(x, np.cos(6*x) * np.exp(-x))
ax1.set_xlabel('time (s)')

ax2.plot(x, np.cos(6*x))
ax2.set_xlabel('time (s)')
ax2.set_title('undamped')

fig.supylabel('supylabel', fontsize=16)
fig.show()
```

### Actual outcome

  File "C:\Users\username\Miniconda3\envs\test\lib\site-packages\matplotlib\_constrained_layout.py", line 306, in _make_margin_suptitles
    if fig._supylabel is not None and fig._supylabel.get_in_layout():
AttributeError: 'NoneType' object has no attribute 'get_in_layout'

### Expected outcome

figure to show

### Operating system

Windows 10

### Matplotlib Version

3.4.2

### Matplotlib Backend

Qt5Agg

**Comment by jklymak** [comment]
That does look to be a bug.  Thanks!  Feel free to open a Pull Request to fix it if you have the bandwidth...

**Comment by sandipanpanda** [comment]
Hi there, I am new to open source and jumped in  finding a good first issue. I want to submit a PR. Can you assign me?

**Comment by jklymak** [comment]
We don't usually assign for PRs, but if one is already open, better not to cross post.  In this case I believe this is still free.
