### ISSUE TITLE
[ENH]: Add a pane color key to change the 3d plot pane color (matplotlibrc) 

### ISSUE THREAD

**Issue by erdmsen** [matplotlib/matplotlib#20780]
### Problem

Key for 3d plot pane color is missing in both matplotlibrc and rcParams

### Proposed solution

Please add the key to the next version

**Comment by story645** [comment]
I think you and @timhoffm opened issues simultaneously 'cause #20781 is a duplicate. Closing this one cause his has a little more detail, please comment on it if there's anything missing and thank you for opening the issue.
