### ISSUE TITLE
[Doc]: "Bachelor's degrees by gender" example is more or less dufte

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#20794]
### Documentation Link

https://matplotlib.org/stable/gallery/showcase/bachelors_degrees_by_gender.html

### Problem

I just noticed that one example in the documentation can be produced (more or less) with far less code using the [dufte](https://github.com/nschloe/dufte) style. In particular, `dufte.legend()` automatically adapts the label positions. Here is the code and the two images (note that most of the code is reading the data):
```python
import csv

import dufte
import matplotlib.pyplot as plt
import numpy as np

# read the data
filename = "percent_bachelors_degrees_women_usa.csv"
with open(filename) as f:
    reader = csv.reader(f)
    labels = next(reader)
labels = labels[1:]
#
data = np.array(np.genfromtxt(filename, delimiter=","))[1:]
year = data[:, 0]
data = data[:, 1:].T

# sort by last value
idx = np.argsort(-data[:, -1])
data = data[idx]
labels = [labels[i] for i in idx]

# create the plot
plt.style.use(dufte.style)

fig, ax = plt.subplots(1, 1, figsize=(12, 14))

for label, values in zip(labels, data):
    ax.plot(year, values, label=label)

plt.title(
    "Percentage of Bachelor's degrees conferred to women in "
    "the U.S.A. by major (1970-2011)"
)
plt.ylim(0, 100)

ax.yaxis.set_major_formatter("{x:.0f}%")
dufte.legend()

plt.savefig("out.png", bbox_inches="tight")
```

![out](https://user-images.githubusercontent.com/181628/128387900-cd095725-b2d8-4d88-abed-1b4da420b350.png)

![g](https://user-images.githubusercontent.com/181628/128387494-5111d174-1c8c-469f-9b25-4e84162fe266.png)

### Suggested improvement

Perhaps that's worth mentioning this in the docs.

### Matplotlib Version

3.4.2

### Matplotlib documentation version

3.4.2

**Comment by jklymak** [comment]
We try not to add dependencies, even to the doc builds.  Similarly, I am not sure we want to explicitly call out every package that would make various examples more bespoke?  There are lots of possible helper packages around and we can't be exhaustive   Packages also fall out of date. Overall I think doing this sort of call out would really add to our maintenance burden.

**Comment by tacaswell** [comment]
I am :+1: and adding verbiage to the example pointing out that `dufte` exists.  The point of the example is to show that this sort of plot is possible (if requires a bit of work).  If people want to make that sort of plot, then by all means we should point them at a package that makes it easier to get what they want!

However, I agree with @jklymak that we should avoid depending on dufte to build the docs.
