### ISSUE TITLE
Confusing `if` condition in transforms.py

### ISSUE THREAD

**Issue by hawkinsw** [matplotlib/matplotlib#20798]
https://github.com/matplotlib/matplotlib/blob/c34fa777b2fb99e4e4148ac6e288cd83f88d0def/lib/matplotlib/transforms.py#L2719

I am new the code base and saw this line of code and it seemed odd. Can someone help me understand why it is correct? 

@QuLogic

**Comment by hawkinsw** [comment]
Ignore me. I had my precedence of operations wrong. I see what it is doing now!!

Will

**Comment by tacaswell** [comment]
I'm glad you got this sorted @hawkinsw !  In the future, we would prefer to handle questions like this either in https://gitter.im/matplotlib/matplotlib or https://discourse.matplotlib.org
