### ISSUE TITLE
Add ability to disable callbacks temporarily

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#20802]
It may be useful to update some attributes on an object that has callbacks temporarily and we don't want those callback signals being processed during that time.

I guess we could add a `disabling_callbacks()` context manager on CallbackRegistry?
```python
with self.norm.callbacks.disabling_callbacks(), cbook._setattr_cm(self.norm, ...): ...
```

_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/19553#discussion_r684096220_

**Comment by timhoffm** [comment]
Naming suggestion: `callbacks_disabled()` or even only `disabled()`:
```
with self.norm.callbacks.disabled():
```

**Comment by QuLogic** [comment]
In Qt, this is `Widget->blockSignals`, and in GTK, it is `g_signal_handlers_block_*`. Wx has a `wxEventBlocker` that you add on a widget to temporarily stop events. Not sure if Tk has anything similar.

IOW, it seems like 'block' is the common term for this for events, though I don't know if these callbacks qualify as 'events'.
