### ISSUE TITLE
[Bug]: \Cap and \Cup in mathtext are inconsistent

### ISSUE THREAD

**Issue by tfpf** [matplotlib/matplotlib#20809]
### Bug summary

`\Cap` and `\Cup` are rendered correctly when only when using Dejavu Sans, not the other fonts.

### Code for reproduction

```python
import matplotlib as mpl
import matplotlib.pyplot as plt

for font in ['dejavusans', 'dejavuserif', 'cm', 'stix', 'stixsans']:
    mpl.rcParams['mathtext.fontset'] = font
    plt.axes().text(0.5, 0.5, r'$\Cap\cap\Cup\cup$' + font)
    plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/19171016/128640716-d4d74ceb-ffd8-4828-ab4a-53b4e559090d.png)
Dejavu Sans looks right.

![image](https://user-images.githubusercontent.com/19171016/128640722-67a509e3-0d96-4445-837c-8f531e36261d.png)
![image](https://user-images.githubusercontent.com/19171016/128640726-403ddeeb-dcf5-43db-88b2-b8b94fd0fa27.png)
![image](https://user-images.githubusercontent.com/19171016/128640727-28e30e1c-a3f3-482c-ac8e-5313536fe6a9.png)
![image](https://user-images.githubusercontent.com/19171016/128640729-ceda8935-daa8-49b8-9c3c-a8f4476de3e0.png)
Dejavu Serif, Computer Modern, STIX and STIX Sans have got it wrong.

### Expected outcome

Dejavu Serif, Computer Modern, STIX and STIX Sans should render `\Cup` and `\Cap` the same way Dejavu Sans does.

### Operating system

Windows 10

### Matplotlib Version

3.2.2

### Matplotlib Backend

module://ipykernel.pylab.backend_inline (Google Colaboratory)

### Python version

3.7.11

### Jupyter version

5.2.2

**Comment by QuLogic** [comment]
DejaVu Sans has these glyphs, but DejaVu Serif does not, and apparently none of the CM fonts do either. So it falls back to STIX, and those fonts are buggy, as they have those glyphs swapped. The fonts tables for STIX 2 appear correct, so they've probably fixed it, but upgrading that is a major endeavour.
