### ISSUE TITLE
Python 3.10 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [matplotlib/matplotlib#20811]
Hello.

Could you please release CPython 3.10 manylinux wheels on PyPI? 

Python 3.10.0 release candidate 1 was released this week: https://www.python.org/downloads/release/python-3100rc1/

It should be quite safe to release wheels for release candidate. ABI for Python 3.10 should be frozen from now on, even for bugfixes. From release notes: 

> There will be no ABI changes from this point forward in the 3.10 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by tacaswell** [comment]
We use https://github.com/matplotlib/matplotlib/blob/master/.github/workflows/cibuildwheel.yml to build the wheels.  A PR to that file adding 3.10 would greatly expedite getting the wheels up.

**Comment by tacaswell** [comment]
Labeled as good first issue because it requires no understanding of Matplotlib internals or API discussion to get done (but does require familiarity with wheel building and CI systems).

**Comment by jklymak** [comment]
Have we been testing 3.10?

**Comment by QuLogic** [comment]
Fedora koschei has been testing 3.4.3 with Python 3.10. We'll get master tested when there's a tag out, but @tacaswell has been running latest everything.

**Comment by hrnciar** [comment]
> We use https://github.com/matplotlib/matplotlib/blob/master/.github/workflows/cibuildwheel.yml to build the wheels. A PR to that file adding 3.10 would greatly expedite getting the wheels up.

I've opened PR #20819, but it is currently blocked on numpy's wheel.
