### ISSUE TITLE
[Bug]: Lowercase Greek letters not showing properly in PDF when using Times font

### ISSUE THREAD

**Issue by gmatheou** [matplotlib/matplotlib#20827]
### Bug summary

Lowercase Greek letter not showing properly in PDF when using Times font.
Behavior is fine with other fonts and other outputs.
Please see code. 

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Times"],
})

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2*np.pi*t)

plt.plot(t, s)
plt.title(r'$\alpha_i > \beta_i \Phi \Xi \Theta \theta \Gamma$', fontsize=20)
plt.text(1, -0.6, r'$\sum_{i=0}^\infty x_i$', fontsize=20)
plt.text(0.6, 0.6, r'$\mathcal{A}\mathrm{sin}(2 \omega t)$',
         fontsize=20)
plt.xlabel('time (s)')
plt.ylabel('volts (mV)')
#plt.show()


plt.savefig("test.pdf", dpi=400, bbox_inches = 'tight', pad_inches = 0.1)
```

### Actual outcome

[test.pdf](https://github.com/matplotlib/matplotlib/files/6968885/test.pdf)

### Expected outcome

Lowercase greek letters should show properly

### Operating system

macOS 11.2.3

### Matplotlib Version

3.2.1

### Matplotlib Backend

MacOSX

### Python version

3.7.10

**Comment by jklymak** [comment]
There was a bug like this, but I cannot reproduce now - you will note that there are plenty of other issues with your PDF....  Please upgrade matplotlib.

**Comment by jklymak** [comment]
Please see #16087
