### ISSUE TITLE
[Bug]: Matplotlib cannot connect to x display with wsl2

### ISSUE THREAD

**Issue by pavaninguva** [matplotlib/matplotlib#20836]
### Bug summary

When using WSL 2 for linux on windows, matplotlib is unable to connect to the X display. However, upon switching to WSL1, it works pefectly fine. This is for matplotlib 3.4.2 with VcXsrv. 

### Code for reproduction

```python
plt.show()
```

### Actual outcome

The error "Could not connect to any X Display" is generated. 

### Expected outcome

The plot should appear. 

### Operating system

Ubuntu

### Matplotlib Version

3.4.2 

### Matplotlib Backend

Qt5Agg

### Python version

3.8.11

### Installation

conda

**Comment by tacaswell** [comment]
Does an Qt application work? Coping the code from https://github.com/matplotlib/matplotlib/issues/20789#issuecomment-893024137 can you try

```python
from PyQt5.QtWidgets import *
app = QApplication([])
label = QLabel('Hello World!')
label.show()
app.exec_()

```

?

**Comment by timhoffm** [comment]
Closing for lack of response. Please re-open if this is still an issue.
