### ISSUE TITLE
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.

### ISSUE THREAD

**Issue by thangckt** [matplotlib/matplotlib#20831]
### Bug summary

I get the warning: findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
and finally fall in the error: ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled

### Code for reproduction

The error occur when I use an Mathtext:
```python
ax.set_ylabel(r'$(J/m^2)$')
```

Without this line, the code can run without error

### Actual outcome

```pytb
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-75353f321df5> in <module>
     33 fig1.subplots_adjust(wspace=0.25)
     34 with PdfPages('stud1_Surface_Energy_0K.pdf') as myPDF:            # save multi-figures in 1 pdf file
---> 35     myPDF.savefig(fig1, dpi=300, bbox_inches='tight', pad_inches=0.05)     # this accept any keyword arguments of plt.savefig()
     36 plt.show()

.......

   1363             else:
-> 1364                 raise ValueError(f"Failed to find font {prop}, and fallback "
   1365                                  f"to the default font was disabled")
   1366         else:

ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
```

### Expected outcome

na

### Operating system

Windows

### Matplotlib Version

3.4.2 

### Matplotlib Backend

'module://ipykernel.pylab.backend_inline'

### Python version

3.7 

### Jupyter version

jupyterlab 3.1.4

### Installation

conda

### Conda channel

conda-forge

**Comment by QuLogic** [comment]
Please provide a complete, but short, example.

**Comment by thangckt** [comment]
Dear @QuLogic 

I am not clear what did use mean?
The error come when I use this: ax.set_ylabel(r'$(J/m^2)$')

**Comment by QuLogic** [comment]
That is not enough to reproduce the problem.

**Comment by thangckt** [comment]
import matplotlib.pyplot as plt
fig, ax = plt.subplots(nrows=1, ncols=1)
ax.set_ylabel(r'Surface energy $(J.m^{-2})$')

**Comment by QuLogic** [comment]
That doesn't fail either. Do you have some custom `matplotlibrc` changes?

**Comment by thangckt** [comment]
Dear @QuLogic

I did not apply any custom setting
That is all thing drive me to the error
The error come when I use an Mathtext:
ax.set_ylabel(r'$(J/m^2)$')
![image](https://user-images.githubusercontent.com/46436648/132776517-750a35e0-7a65-4169-a891-efc75432a93c.png)

**Comment by jklymak** [comment]
I'm going to close as not reproducible, but feel free to ask for a re-open if there is something we can specifically help with.

**Comment by ksunden** [comment]
As it happens, one of my former labmates (@jscheeler1) was having a very similar issue earlier today.

In his case, the only thing he were using LaTeX for was Greek letters, e.g. `$\Gamma$` and the quick workaround I had him use was to just use unicode Greek letters rather than LaTeX... but I could probably work with him to actually hash out where the actual issue lies.

They were using Spyder and an interactive backend (not fully sure which), but it was Windows and conda-forge installed.

**Comment by AlexaMilken2000** [comment]
EL FORMATO LATEX DE $$ NO ME PERMITE ALGUIEN ME AYUDA

![Image](https://github.com/user-attachments/assets/eea32df5-8b0a-457e-ba77-59297ceed54a)

**Comment by larsoner** [comment]
I just wanted to chime in here and say I was having a similar issue, sometimes when making plots I'd see a bunch of stuff in my terminal (like 12-15 lines worth):
```
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
...
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeOneSym'] not found. Falling back to DejaVu Sans.
...
findfont: Font family ['cmsy10'] not found. Falling back to DejaVu Sans.
...
```
They were harmless but annoying. Doing:
```
rm ~/.cache/matplotlib
```
fixed the problem for me!

In retrospect, given these messages were about LaTeX fonts, I realized I'd removed a bunch of LaTeX stuff from my system some months ago. I suspect this caused the cache to be out of date, so clearing it would make sense as a fix.

If it's helpful I can try installing and uninstalling etc. to further diagnose the issue and see if I can come up with a set of commands to cause the problem, but given the workaround is simple maybe it could just go in a FAQ somewhere (or just let people's web searches maybe land them here...).

**Comment by larsoner** [comment]
... and I should have said: credit to https://stackoverflow.com/a/49884009/2175965 to pointing this out as a fix! Looking back it it, given it has hundreds of upvotes, it might be worth a FAQ entry perhaps
