### ISSUE TITLE
Matplotlib 3.4.3 wheel unable to build - cannot find Python.h

### ISSUE THREAD

**Issue by thegnarwhals** [matplotlib/matplotlib#20834]
In a minimal docker container with python3-dev installed, `pip install matplotlib==3.4.3` gives an error ending
```
...
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_backends__backend_agg_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -DFREETYPE_BUILD_TYPE=local -Ibuild/freetype-2.6.1/include -Iextern/agg24-svn/include -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/usr/include/python3.8 -c src/mplutils.cpp -o build/temp.linux-x86_64-3.8/src/mplutils.o -fvisibility=hidden -flto
    In file included from src/mplutils.cpp:3:0:
    src/mplutils.h:30:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u5hy07s_/matplotlib_f8f90367c2be475d814b963c95f58343/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u5hy07s_/matplotlib_f8f90367c2be475d814b963c95f58343/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7zap5ode/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/matplotlib Check the logs for full command output.
```

edit: minimal example:
```
docker run -it --rm --net host ubuntu:18.04
# Inside docker container:
apt-get update -y && apt-get install python3.8 python3-pip -y && python3.8 -m pip install --upgrade pip
python3.8 -m pip install --no-binary matplotlib matplotlib  # this fails
apt list --installed | grep python3-dev

# Output:
# libpython3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
# python3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
```

**Comment by jklymak** [comment]
This is being tracked on the PyPi side here: https://github.com/pypa/pypi-support/issues/1261

**Comment by tacaswell** [comment]
A workaround is to add `--only-binary matplotlib` to your pip invocation to make sure you do not have to compile.

Can you post the docker file?  If python-dev is installed then I'm worried something deeper is going wrong if we are not finding Python.h.

**Comment by thegnarwhals** [comment]
Thank you both, @tacaswell I'm afraid can't post the dockerfile, it's part of my company's IP, but trying to get a minimal reproducible example locally.

**Comment by charliekang** [comment]
We get this, shall I file a different issue? 

```
1523    lto1: fatal error: bytecode stream in file ‘build/freetype-2.6.1/objs/.libs/libfreetype.a’ generated with LTO version 8.1 instead of the expected 6.2
1524    compilation terminated.
1525    lto-wrapper: fatal error: x86_64-linux-gnu-g++ returned 1 exit status
1526    compilation terminated.
1527    /usr/bin/ld: error: lto-wrapper failed
1528    collect2: error: ld returned 1 exit status
1529    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

**Comment by tacaswell** [comment]
@charliekang Yes, that looks like a different compilation issue, can you please open a new issue and include the details about which complier and platform you are on?

**Comment by tacaswell** [comment]
@charliekang Are you hitting this in a conda env?  If so, please either install their compilers, pin to only binary mpl if you want to install from pypi or install Matplotlib through conda. 

xref https://github.com/ContinuumIO/anaconda-issues/issues/6619

**Comment by charliekang** [comment]
@tacaswell Thanks will do. We are running in an Docker environment and this just arise with 3.4.3 as 3.4.2 was fine.

**Comment by thegnarwhals** [comment]
@tacaswell Minimal reproducible example:
```
docker run -it --rm --net host ubuntu:18.04
# Inside docker container:
apt-get update -y && apt-get install python3.8 python3-pip -y && python3.8 -m pip install --upgrade pip
python3.8 -m pip install --no-binary matplotlib matplotlib  # this fails
apt list --installed | grep python3-dev

# Output:
# libpython3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
# python3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
```
Does this work for you?

**Comment by tacaswell** [comment]
Oh, sorry, I missed you explicitly _do_ want to compile @thegnarwhals 🐑 .  We are currently getting a bunch of other reports of "Matplotlib won't install" because of the missing wheel that my brain auto-completed too much. 

I think your issue is that you are installing and running with python3.8, but `python3-dev` is the py3.6 headers.

Adding

```
apt-get install python3.8-dev
```

matplotlib complies for me.

```
root@d038074eface:/# apt list --installed | grep 'python3.*-dev'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpython3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
libpython3.6-dev/bionic-updates,bionic-security,now 3.6.9-1~18.04ubuntu1.4 amd64 [installed,automatic]
libpython3.8-dev/bionic-updates,bionic-security,now 3.8.0-3~18.04.1 amd64 [installed,automatic]
python3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed,automatic]
python3.6-dev/bionic-updates,bionic-security,now 3.6.9-1~18.04ubuntu1.4 amd64 [installed,automatic]
python3.8-dev/bionic-updates,bionic-security,now 3.8.0-3~18.04.1 amd64 [installed]

```

**Comment by tacaswell** [comment]
@charliekang Can you post any part of the docker file you are having issues with?  I see you are at intel, are you using gcc or the intel compliers?

My current understanding is due to a pypi / CDN issue not all of the uploaded wheels are visible to everyone for mpl3.4.3 so with 3.4.2 you were likely not trying to compile from source because you were grabbing the wheel which elided what ever build issue you are having.

**Comment by thegnarwhals** [comment]
Yes! @tacaswell that's perfect, thank you! I don't explicitly want to compile but for some reason installing my requirements.txt ends up compiling matplotlib (I suppose there's an intermediate library that insists on source for some reason, perhaps because of the missing wheel, so you were right to autocomplete) - I was just trying to get the same behaviour locally and this was the quickest way. Thanks again!

**Comment by tacaswell** [comment]
@thegnarwhals In that case I think `pip install --only-binary matplotlib -r requirements.txt` is probably your best bet going forward (it will solve your problem now, protect you from us having another wheel-issue in the future, and we are going to keep uploading wheels as long as wheels are a thing so it is unlikely to accidentally pin you back).

**Comment by thegnarwhals** [comment]
Works for me, thanks!

**Comment by tacaswell** [comment]
It looks like you can do one better and put 

```
matplotlib --only-binary matplotlib 
```

directly in your requirements.txt.

**Comment by charliekang** [comment]
@tacaswell Our Dockerfile is similar to the one posted but with gcc-9/g++-9 & clang-tidy-9

But as mentioned, we have changed it to `--only-binary` or `--prefer-binary`

Thanks again

**Comment by tacaswell** [comment]
This is resolved its self on the pypi side so closing this.  Sorry for this disruption everyone.
