### ISSUE TITLE
frames around texts in current master is different from that of v1.2

### ISSUE THREAD

**Issue by leejjoon** [matplotlib/matplotlib#2084]
In the current master, text frames are drawn with unnecessary space around text whose ascent and descent is smaller than those of "lp". The word "unnecessary" is rather personal, so we may need to discuss what should be the correct behavior. Consider a following example

```
import matplotlib.pyplot as plt

plt.figure(figsize=(7, 3))
plt.text(0.2, 0.5, "o", size=40,
         bbox=dict(boxstyle="square,pad=0.", alpha=0.3))
plt.text(0.5, 0.5, "o$_{o_{o_{o_{o_{o}}}}}$", size=40,
         bbox=dict(boxstyle="square,pad=0.", alpha=0.3))
plt.plot([0.2, 0.5], [0.5, 0.5], "+r", ms=10, mew=4)
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.show()
```

In v1.2, it produced (with usetex=False)

![test_fancybox_v1 2](https://f.cloud.github.com/assets/95962/580117/b5b7ae70-c880-11e2-812e-a3ec41944bf8.png)

Now it produces 

![test_fancybox_master](https://f.cloud.github.com/assets/95962/580119/c50837e6-c880-11e2-8059-e5aca5e79856.png)

Note that the frame around "o" is different. What is the desired behavior? Or do we want this to be optional?

As a separate issue, frame is shifted in the current master when text.usetex=True and text.latex.preview=False,

![test_fancybox_master_usetex](https://f.cloud.github.com/assets/95962/580123/ec73534c-c880-11e2-9009-f9b7ed3531f1.png)

**Comment by petehuang** [comment]
@mdboom has there been any work on the MEP you mentioned? If not, it may be productive for you, @leejjoon, to help detail the other issues.

In the meantime, I would rename this issue as `ENH: Make text frame padding optional` or similar

**Comment by tacaswell** [comment]
This is how this example renders in 3.7.0:

![so](https://user-images.githubusercontent.com/199813/222508064-15447a95-68c9-4e8c-8af7-f4ce76423d6a.png)

which looks like something about the way we render (nested) subscripts has also changed.

This behavior has been like this for long enough now I think we should not go back and for most of our internal purposes (layout) having mostly-stable height computation seems better than both the height and width being dependent on the exact characters (e.g. if you have a series of figures with different x labels all using constrained layout and you flip through them the axes should not jump around).
