### ISSUE TITLE
[Bug]: Inconsistent bar's width in bar()

### ISSUE THREAD

**Issue by willemavjc** [matplotlib/matplotlib#20844]
### Bug summary

The width of the bars "graphed" is varying while it should be constant. This happens whether the `width` is specified or not. This only happens for a few percentage of the bars (3 over 100 in the test case).

### Code for reproduction

```python
import matplotlib.pyplot as pl
pl.rcParams['figure.figsize'] = (20,6)
pl.style.use('seaborn-darkgrid')

...

    threshold = np.linspace(1, 100, num=100)
    recall    = []
    precision = []
    index = labels.index(word) if word else 0
​
    for x in threshold:
        p, r, _, _ = precision_recall_fscore_support(y_test, (pr*100>=x).astype(np.int8).flatten())
        recall.append(r[index]*100)
        precision.append(p[index]*100)
​
    pl.bar(threshold-0.20, recall   , width=0.40)
    pl.bar(threshold+0.20, precision, width=0.40)
    pl.xlabel('Threshold (%)')
    pl.ylabel('Measures (%)')
    pl.title('Evolution of precision over recall measures')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/321359/129606086-42ae9d6c-84d9-4fd6-ac68-888628283964.png)

One can see the blue bars have sometimes different widths.

### Expected outcome

Constant width.

### Operating system

Windows, CentOS

### Matplotlib Version

3.4.2

### Python version

3.9.6

### Jupyter version

3.1.2 (JupyterLab)

### Installation

pip

**Comment by timhoffm** [comment]
This is a rasterization effect. Bars are coerced to integer pixel widths. Otherwise, their edges would be blurred by antialiasing. Therefore bars at different positions may vary by one pixel.

**Comment by willemavjc** [comment]
Hmm... I still don't get it. If bars are all coerced to integer pixel width, then why does that width vary? Shouldn't they share the SAME integer pixel width value??

**Comment by timhoffm** [comment]
No. Simple example:

You want 4 bars in the interval [0, 1] with no margins. The bar edges are thus at the data positions 0, 0.25, 0.5, 0.75, 1.
If your figure is now 10px wide, you'll have pixel edges at every 0.1 data coordinates. The bar edges 0.25 and 0.75 have to be shifted to the next 0.1 position. Thus you'll get bar edges at 0, 0.3, 0.5, 0.8, 1; i.e. the bars are 3, 2, 3 and 2 pixels wide.

**Comment by jklymak** [comment]
You can set snap=False when you create the bar as well and get rid of this.   I'm not sure why it is true by default for bars actually.

**Comment by willemavjc** [comment]
@jklymak You made my day. Woohoo! Now, I can show some graphs without fearing critics on the dumb random widths.

**Comment by jklymak** [comment]
Great, but note the basic advice to use more dpi is also very relevant here!

**Comment by willemavjc** [comment]
Hmm... Would you mind explaining it a bit further? I do not know much but I thought that DPI was for printers, PPI for screens ...meaning that for screens there's not much we can do about that as we cannot make the number of pixels varying, the thing being more a manufacturer thing than anything.

/me sank

**Comment by timhoffm** [comment]
> but I thought that DPI was for printers, PPI for screens 

We (and I think most GUI frameworks) don’t make that distinction. Consider DPI a synonym for PPI for screens.
That said, DPI was also used a bit sloppy above. Effectively, what you need is more pixels. In matplotlib, the number of pixels is the figure size times `figure.dpi`. 

> for screens there's not much we can do about that as we cannot make the number of pixels varying,

Correct for a given screen. But as technology is moving towards higher-resolution screens and UI scaling, the effect will become less visible.

**Comment by timhoffm** [comment]
> You can set snap=False when you create the bar as well and get rid of this. I'm not sure why it is true by default for bars actually.

@jklymak I think true is the correct default as long as there are many pixels per bar, which should be the case for the majority of bar plots.

**Comment by jklymak** [comment]
> @jklymak I think true is the correct default as long as there are many pixels per bar, which should be the case for the majority of bar plots.

I guess I don't understand why it would be better for well-resolved plots versus just antialiasing the patch?

**Comment by timhoffm** [comment]
In the following exmple, I've deactivate snapping for "Men". Note that the edges of the blue bars are blurred due to antialiasing.

![grafik](https://user-images.githubusercontent.com/2836374/130076767-c6b6453b-5504-4c35-a667-85227741a764.png)

**Comment by jklymak** [comment]
Sure, but why would we say the antialiased one is worse?  At decent resolution I'd say it's better, and at low pixels-per-bar I'd say it is _far_ better.

**Comment by timhoffm** [comment]
I'd say blurred edges are generally not good (same reason we snap ticks).

It's a trade of between blur and "exact" position. And for graphs as the above with not very many bars (which I assume are the most common use of bar charts), exact edge position is not important. YMMV, but IMHO the decision is either way not clear enough to justify an API change, so the default is what it is.

**Comment by jklymak** [comment]
My understanding is that we snap ticks because they are often one pixel wide, and antialiasing something so thin makes it almost invisible.  

An argument for not antialiasing is that we antialias against the background rather than adjacent polygons.  So in the version of the above with orange and blue bars there ends up being a whitish band between the two bars where the antialiasing has happened with the white background. 

However I do think that as screens improve and hidpi becomes the norm we should reconsider some of our defaults.  However I am not suggesting we do so here
