### ISSUE TITLE
[MNT]: CMake-built freetype is not supported on Windows

### ISSUE THREAD

**Issue by mathstuf** [matplotlib/matplotlib#20845]
### Summary

When freetype is built on Windows using its CMake build, `matplotlib` cannot find it and there are no knobs available to give hints as to where the headers and libraries live.

### Proposed fix

More robust support for finding `freetype` on Windows without `freetype-config` (not present in a CMake build).

**Comment by anntzer** [comment]
Are the knobs documented at https://matplotlib.org/devdocs/devel/dependencies.html#c-libraries (specifically, the CL and LINK environment variables) not sufficient?

**Comment by mathstuf** [comment]
Ah, I missed those. Yes, those are sufficient, thanks.
