### ISSUE TITLE
[ENH]: matplotlib.pyplot.bar_label - add parameter to skip 0 length labels

### ISSUE THREAD

**Issue by trenton3983** [matplotlib/matplotlib#20841]
### Problem

- [`matplotlib.pyplot.bar_label`][1] is a wonderful addition.
- The problem is when it adds a label for 0, or very small lengths
  - This requires a list comprehension to customize / remove the labels to be sent to the `labels` parameter.
  - Examples [1][2] and [2][3]

  [1]: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar_label.html
  [2]: https://stackoverflow.com/a/68785457/7758804
  [3]: https://stackoverflow.com/a/64202669/7758804

### Proposed solution

- Add a new parameter which skips all labels of length 0; it could be a bool (e.g. `skip=True`)
- Alternatively, add a parameter which skips labels for a range of values (e.g. `skip=[-0.5:0.5]`)
  -  This option seems more useful.

**Comment by jklymak** [comment]
Seems reasonable.  I also wonder about adding the ability for fmt to take a function instead is a string.  That way you could easily exclude whatever values you want.

**Comment by timhoffm** [comment]
Agreed that we should provide more flexibility.

I propose to follow @jklymak's suggestion to support a callable for fmt. Skipping is problematic as we return a list of texts. We should not leave out elements in that list, because position equivalence between the bar and the returned text is important. Also skipping is a very specific action, whereas formatting is more general; and skipping could be needed on various conditions, that we don't want to predefine in the API.

A callable for format should be able to address all use cases that skipping can.

**Comment by story645** [comment]
can the callable be any of the tickformatters?

**Comment by trenton3983** [comment]
> Skipping is problematic as we return a list of texts.

Maybe _skipping_ is not the ideal word. Since a list of text is returned, it seems feasible to replace undesired labels with `''`, as in the examples.

Minimally, it seems `0` values should be replaced with `''` in the returned list (depending on a bool parameter), and would require the least effort.

**Comment by kkoutris** [comment]
I would like to work on this issue. Can someone guide me a bit?

**Comment by tacaswell** [comment]
In a number of places in the code base where we take in a way to format a string, particularly around formatting ticks where the user can pass format strings or a callable with a signature than looks like

```python
def make_strring(val : float): -> str
     ....
```

The work here is to:
 - implement the logic in matplotlib.pyplot.bar_label to detect if the input is a string or a callable
 - add a test
 - add documentation

Bonus points if the API on the function can match the tick formatters (they take some extra tick-specific details that might not make sense to carry over though).

**Comment by lordrasmus** [comment]
in 3.7 this is now possible

i think this issue can be closed

**Comment by ksunden** [comment]
Indeed, closed by #23690
