### ISSUE TITLE
Add deprecation for colormaps

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#20853]
This is tracking for the next stage of the colormap registry, pulled out of the original PR so that it doesn't get lost. (Originally written by @timhoffm)

### Overall goal

The registry is a more natural structure for managing colormaps. We have data and corresponding functions that are tightly related. IMHO it's a much nicer API for the user and easier to extend. And we get rid of some API quirks in the functions like `get_cmap(.. lut=...)` or the parameter order `register_cmap(name, cmap)` where name is optional.

### Target state
- the `matplotlib.cm` colormap functions should eventually be removed:
  - `matplotlib.cm.register_cmap(...)` - use `mpl.colormaps.register(...)` instead
  - `matplotlib.cm.unregister_cmap(...)` - use `mpl.colormaps.unregister(...)` instead
  - `matplotlib.cm.get_cmap(name)` - use `mpl.colormaps[name]` instead, followed by `.resampled()` if needed to cover `get_cmap(lut=...)`.
- <s>I'm open for discussion if we keep the pyplot functions or replace them with the registry as well.</s> Suggestion on pyplot:
  - eventually remove `plt.register_cmap` - use `mpl.colormaps.register(...)` instead. - This is a fundamental operation and IMHO beyond the scope of `pyplot`
  - keep `plt.get_cmap()` - This is too widely used to be removed. But eventually remove its `lut` parameter in favor of `plt.get_cmap().resampled()`.

### Transition path
While I would like to eventually remove the `matplotlib.cm` functions, I propose a prolonged transition path because they are quite fundamental functions also used in third party libraries:
- For 3.5: introduce the registry as is in this PR; *discourage* the `cm` functions. This is to see if we have missed something important in the design and get user feedback. - Maybe we should declare the registry experimental. 
- For 3.6: Introduce a pending deprecation on all functions that we want to eventually remove. This is the time where all downstream libraries should start switching to using the registry.
- For 3.7 (or later): Deprecate all the functions we want to remove.
- For 3.9 (or later): Remove all the functions we want to remove.

**I strongly advocate to introduce this PR in 3.5. If everything goes well, we don't need modifications (only extensions) to the registry, which means that downstream libraries would have 3.5 as a minimum dependency when they switch to the registry.**

### On read-only colormaps
The registry colormap access already returns copies of the colormaps and by that implements the change to `get_cmap`, which is scheduled to take effect in 3.6 (#19766). He can be quicker here, because the new API does not have to maintain backward compatibility for the deprecation period.
Other than that, the registry is independent of cmap mutability.

_Originally posted by @timhoffm in https://github.com/matplotlib/matplotlib/issues/18503#issuecomment-898873054_

**Comment by tacaswell** [comment]
A flaw in our plans is that `get_cmap` take as second `lut` argument which we do not have a public API to do.  There is a private API for this (`cmap._resample()` via https://github.com/matplotlib/matplotlib/pull/5283).  I think this is show-stopping to get this done for 3.6.

I'm still going to try and get the PR to do all of this done, but am skeptical we want to force it through.

**Comment by timhoffm** [comment]
As written in https://github.com/matplotlib/matplotlib/pull/23668#pullrequestreview-1078785524, it's ok to postpone `get_cmap` to 3.7 if it's too complicated.

**Comment by jklymak** [comment]
Given that we are linking this issue in the What's New,  I'd really appreciate it if the issue was edited to explicitly explain what is being deprecated, and what is replacing it.  I've been following this peripherally, and even for me, the comment above, cut and pasted from elsewhere, is too vague for me to understand the roadmap, so I fear that our users are not going to understand it either.  Or in #23668 or whatever follows from it, lay it out in the what's new and don't refer to a cryptic issue?

**Comment by timhoffm** [comment]
@jklymak I've rewritten the "Target state" and "Transition path" paragraphs above. Is that more clear now?

**Comment by QuLogic** [comment]
The deprecation was bumped in #24846 for 3.7; this now moves to 3.9 for the _final_ part.

**Comment by Baharis** [comment]
Colormaps can be still accessed in version 3.7.0 using the following syntax: `getattr(matplotlib.cm, 'colormap_name', None)`. This seems to be the simplest way to use a default colormap without a `try/except` block. It also does not raise any `DeprecationWarning`s. Is this syntax discouraged or expected to be deprecated in the future?

**Comment by s-banach** [comment]
The deprecation warning says to use `matplotlib.colormaps`, but there is no file `colormaps.py`, and my type checker complains "colormaps is not a known member of module matplotlib".
The default colormaps should all be static code, there's no need to do any fancy dynamic stuff that breaks type checkers.

**Comment by timhoffm** [comment]
`colormaps` is a private variable in `matplotlib.cm`, which is imported to public names in the namespaces `matplotlib` and `matplotlib.pyplot`. Nothing dynamic. I would have expected that type checkers can handle this.

**Comment by ksunden** [comment]
Note that matplotlib 3.8 (due out soon) will ship with our own type stubs (for the first time) that will help clarify this to type checkers. 

https://github.com/matplotlib/matplotlib/blob/4f65e66d1dcf9788d542fc893ee2e40940304da1/lib/matplotlib/__init__.pyi#L114

Colormaps in the registry are actually a dynamic set of things, that _can_ be changed at run time (and many such as the `<name>_r` are generated dynamically as well).

Note that most of this implementation was done _before_ static type checking was a thing in Python, and well I have personally invested time into trying to make it better and more usable, there certainly are still (and will be for the foreseeable future) rough edges of the static type checkability of Matplotlib.

(@timhoffm, I think the lack of a `__all__` may be making the type checkers ignore the import, but it is included in the pyi file)

**Comment by ksunden** [comment]
(`__all__` is in the version of `__init__.py` on main, but not for any released version)

**Comment by s-banach** [comment]
Sorry for sending a grumpy message, and thank you for your thoughtful response.

**Comment by timhoffm** [comment]
At least PyCharm seems not to be able to pick up the type also on master:
![image](https://github.com/matplotlib/matplotlib/assets/2836374/4fe75836-f19f-43aa-86b2-1c7f6ab2f5e3)

It may be worth reconsidering the setup logic and distribute the CorormapRegistry to matplotlib and pyplot via a function `cm._get_colormaps`.

**Comment by ksunden** [comment]
Hmmm, my editor integration (powered by pyright), and mypy/pyright cli with default settings at least, are perfectly happy  with it:

```python
import matplotlib
from typing import reveal_type

col = matplotlib.colormaps
reveal_type(col)
```

Mypy cli:

```
$ mypy test.py
test.py:5: note: Revealed type is "matplotlib.cm.ColormapRegistry"
Success: no issues found in 1 source file
```

Pyright cli:

```
$ pyright test.py
/home/kyle/play/test.py
  /home/kyle/play/test.py:5:13 - information: Type of "col" is "ColormapRegistry"
0 errors, 0 warnings, 1 information 
```

(Editor is literally just inlined version of pyright CLI)

Not sure what pycharm is using to do type checking, but those two are generally considered the biggest ones...

**Comment by WeatherGod** [comment]
> Colormaps can be still accessed in version 3.7.0 using the following syntax: `getattr(matplotlib.cm, 'colormap_name', None)` or `matplotlib.cm.jet`. This seems to be the simplest way to use a default colormap without a `try/except` block. It also does not raise any `DeprecationWarning`s. Is this syntax discouraged or expected to be deprecated in the future?
> 
> Issue #19609 mentions this disambiguity, but does not really address my question.

Re-upping this. I just came across some old code that I'm updating. Is `matplotlib.cm.Blues` going to break in the near future?

**Comment by timhoffm** [comment]
There are no concrete plans to remove `matplotlib.cm.Blues` in the near future. Though I would not recommend using these. `matplotlib.colormaps['Blues']` is clearer, only a bit longer and also works for custom registered colormaps. If we remove this, it will get a regular deprecation period, so you'll have two minor versions of heads up.

**Comment by QuLogic** [comment]
I believe this is complete with the merging of #26965.

**Comment by geo7** [comment]
Sorry but I can't seem to find a clear approach to use of the `lut` argument, I have code such as: 

```python
            color_map = mpl.cm.get_cmap(name="cool", lut=100)
```
And from the above it seems I'd use something like `matplotlib.colormaps['cool'].resampled()` ? I'm pretty sure I can't just use `.resampled()` and have it represent whatever the previous value of `lut` was, but I'm unsure how I would go about replacing the code I've provided based on the issue description here. Thanks!

**Comment by Erotemic** [comment]
Would have been nice to see deprecation warnings for `mpl.cm.get_cmap` rather than running into errors after it was entirely removed. Maybe I missed them in which case, ignore the noise.

**Comment by alhom** [comment]
Yes, it would have been nice... and it seems related to Python choices for default warnings, though: 
https://peps.python.org/pep-0565/

Now that we manually enabled DeprecationWarnings, we also found out that distutils is being deprecated.... which we are currently using to account for deprecated APIs...
