### ISSUE TITLE
[Doc]: Incorrect copyright start year at the bottom of devdocs page

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20854]
### Documentation Link

https://matplotlib.org/devdocs/index.html

### Problem

Bottom copyright starts with
> © Copyright 2021 - 2012 John Hunter, ...

Compare with stable docs:
> © Copyright 2002 - 2012 John Hunter, ...

### Matplotlib Version

master

### Matplotlib documentation version

3.4.2.post1702+g0a4a10c5a1

**Comment by QuLogic** [comment]
This appears correct when I build locally. I am using 0.5 of the theme, since it's faster, but while there were some refactorings, I don't see anything that should have changed in the templates.

**Comment by QuLogic** [comment]
Turns out this is some kind of [misfeature to follow `SOURCE_DATE_EPOCH`](https://github.com/sphinx-doc/sphinx/issues/3451#issuecomment-877801728) in Sphinx, but we already handle that. The regex is not difficult to bypass, so I will PR a fix soon.
