### ISSUE TITLE
[ENH]: Provide more commonly needed `stairs` option for `fill_between`

### ISSUE THREAD

**Issue by michaelosthege** [matplotlib/matplotlib#20860]
### Problem

The [`pyplot.fill_between` function has a `steps` option](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.fill_between.html) to plot a step function, **but the more commonly needed use case are stairs**.

The [`pyplot.step` function](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.step.html#matplotlib.pyplot.step) itself recommends to use [`pyplot.stairs`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.stairs.html):

![grafik](https://user-images.githubusercontent.com/5894642/130040860-8bcf8cbe-aa77-4e33-9170-c4c1a6d3693c.png)

The following code achieves the desired result, albeit with an inconvenient stacking at the user side:
```python
edges = numpy.array([0, 3, 8, 10])
heights = numpy.array([1, 3, 5])

pyplot.stairs(heights, edges, baseline=None)

heightsplus = numpy.hstack([heights, heights[-1][None]])
pyplot.fill_between(
    edges,
    heightsplus+0.5,
    heightsplus-0.5,
    step="post",
    alpha=0.2
)
```
![grafik](https://user-images.githubusercontent.com/5894642/130043853-1e1c9766-dfcf-4151-9136-8d0ddb3710fd.png)

### Proposed solution

Either by adding a `stairs: bool` kwarg, or by automatically detecting `len(ind_dir) == len(ind) + 1` the [`fill_between_x_or_y`](https://github.com/matplotlib/matplotlib/blob/bd42020c3bec3f787d181e0eee37bcf983b151a5/lib/matplotlib/axes/_axes.py#L5065) could switch to a stairs mode.

**Comment by timhoffm** [comment]
You can achieve a between-filled stair by using `baseline` and `fill=True`:

```
plt.stairs(heights, edges, baseline=[0, 0.5, 2], fill=True, alpha=0.2)
```
![grafik](https://user-images.githubusercontent.com/2836374/130075465-474ed1df-6529-4eb2-af7c-fe5efb8846b2.png)

**Comment by michaelosthege** [comment]
Thanks for the tip!
I'm actually using `fill_between` through [a helper function from PyMC3](https://github.com/pymc-devs/pymc3/blob/main/pymc3/gp/util.py#L141-L151), but I'll put it on my list to implement a change or workaround in there. After all `pyplot.stairs` is a relatively new thing.
