### ISSUE TITLE
3.5.0b1 regression: boxplot does not populate ax.artists list

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#20895]
### Bug summary

See title

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
X = np.random.randn(100, 5)
ax = plt.figure().subplots()
ax.boxplot(X, patch_artist=True)
assert ax.artists
```

### Actual outcome

AssertionError

### Expected outcome

pass

### Matplotlib Version

3.5.0b1

### Installation

pip

**Comment by mwaskom** [comment]
It looks like they patch artists have just moved, `assert ax.patches` fails on current release but passes on 3.5.0b1.

`ax.patches` is a better home for them, but it is going to be mildly annoying to deal with the change.

**Comment by QuLogic** [comment]
Yes, this is intentional; all `Artist`s are treated equally, and the `.lines`, `.patches`, etc are generated on the fly based on subclass. As `patch_artist=True` creates a `PathPatch`, it ends up in `ax.patches`. Unfortunately, I don't think there's a quick workaround.

**Comment by mwaskom** [comment]
I think it may not be worth maintaining backwards compatibility here, although it is an abrupt break and will likely cause problems for someone. (I will need to fix some tests, although I don't *think* it will affect user-facing behavior...)

That said, one could imagine solutions for backwards compatibility ... e.g. methods with changed behavior could populate a special "deprecated" list, with metadata about where they used to go, then when the artist lists are constructed (on the fly, as accessed), they could pull in the appropriate deprecated artists and fire a warning.

It's late and I'm sleepy, so that might not be clear ... and it might not be worth the work. But perhaps worth considering ...

**Comment by mwaskom** [comment]
Closing as 3.5 has been released.
