### ISSUE TITLE
3.5.0b1: ax.contour generates different artists

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#20906]
### Bug summary

The artists added when using `ax.contour` have changed abruptly from 3.4 to the 3.5 beta. This causes issues for workflows that use the artist properties.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

xx, yy = np.mgrid[-3:3:.01, 0:1:.05]
zz = np.sin(xx * yy)

ax = plt.figure().subplots()
ax.contour(xx, yy, zz)
print(ax.collections[0].__class__)
```

### Actual outcome

The result on 3.5.0b1:
```python
<class 'matplotlib.collections.PathCollection'>
```

### Expected outcome

The result on 3.4.1:
```python
<class 'matplotlib.collections.LineCollection'>
```

**Comment by timhoffm** [comment]
Is @QuLogic ‘s documentation enough to close this issue?
