### ISSUE TITLE
[Bug]: Animation error message

### ISSUE THREAD

**Issue by Gallywix-L** [matplotlib/matplotlib#20909]
### Bug summary

once I executed my code by matplotlib.animation,  The programe response this without any animation: D:\Program Files\Python\Python38\lib\site-packages\matplotlib\animation.py:973: UserWarning: Animation was deleted without rendering anything. This is most likely unintended. To prevent deletion, assign the Animation to a variable that exists for as long as you need the Animation.

### Code for reproduction

```python
import matplotlib.animation
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import font_manager
import pandas as pd
from matplotlib.animation import FuncAnimation


def update(date):
    # ax.clear()
    # dg = df[["Country", date]].sort_values(by=date, ascending=True).tail(10)
    ax.barh(range(10), df[date])


# 创建画布和初始参数
fig, ax = plt.subplots(figsize=(10, 5.625), dpi=100)

# 准备数据
df = pd.read_csv(r".\csv_test.csv")

date_list = df.columns[1:].unique().tolist()
# print(date_list)

a = FuncAnimation(fig=fig, func=update, frames=date_list, interval=50)
```

### Actual outcome

"D:\Program Files\Python\Python38\python.exe" "D:/pyCharm Project/Bar_chart_race/Barchart_race.py"
['2020/4/8', '2020/4/9', '2020/4/10', '2020/4/11', '2020/4/12']
3.4.3
D:\Program Files\Python\Python38\lib\site-packages\matplotlib\animation.py:973: UserWarning: Animation was deleted without rendering anything. This is most likely unintended. To prevent deletion, assign the Animation to a variable that exists for as long as you need the Animation.

Process finished with exit code 0

### Expected outcome

a live plot

### Operating system

Windows

### Matplotlib Version

3.4.3

### Python version

3.8.10

**Comment by rohit-v-gore** [comment]
Having this issue on Mac, ran plt.show(), iterates once and then does not populate data into the plot. Running an M1 chip anyone know what the problem is?
