### ISSUE TITLE
Improving ease of contribution for beginner student contributors

### ISSUE THREAD

**Issue by itsmingjie** [matplotlib/matplotlib#20923]
Dear matplotlib maintainers,

We're reaching out on behalf of an ongoing partnership between California State University Monterey Bay's [Computing Talent Initiative](https://computingtalentinitiative.org/) and [CodeDay](https://www.codeday.org/), a nonprofit organization. We're working on a program for college students who are new to contributing to open-source software, and we'd love to invite them to help closing some "good first issues" in your project! 

One of the goals of our program is to get more students to become comfortable with contributing to larger open source projects. A large codebase can be really intimidating to look at at first, so we'd love to invite you to host a short webcast to help students establish a mental modal of your codebase! 

If you are interested, our team (cc @SchmitzAndrew) will work with you to create/improve beginner-friendly documentation on how the code is structured, and how to get a local development environment running. We'll also provide primary mentorship to the students. In exchange, we'll need 30-45 minutes of time from a maintainer, and a commitment to be friendly to the students who are opening their first pull request. 

I'm open to discussing more below if you have questions! You can also get in touch with me directly at [mingjie@codeday.org](mailto:mingjie@codeday.org). 

Mingjie, Program @CodeDay
Berkeley CS'24

---
_If you would not like to participate, please feel free directly close this issue — sorry for the interruption!_

**Comment by tacaswell** [comment]
> and a commitment to be friendly to the students who are opening their first pull request.

This one is easy as that is already the expectation (and not just for students, for anyone opening any PR)!

> In exchange, we'll need 30-45 minutes of time from a maintainer, 

Adding this to our developer meeting agenda (unless someone wants to preemptively volunteer).

> We'll also provide primary mentorship to the students.

That is good, the biggest problems we have had in the past with student programs like this is a wave of un-mentored first time contributors that over-saturates our ability to review PRs and mentor new contributors.

**Comment by itsmingjie** [comment]
Thank you @tacaswell for your help! Please keep me updated if there's any interest from the developer meeting (you can directly email any contact info to me if desired). 

> That is good, the biggest problems we have had in the past with student programs like this is a wave of un-mentored first time contributors that over-saturates our ability to review PRs and mentor new contributors.

I'm also happy to provide partial examples of past mentored student contributions for reference/example. Ultimately, we want this program to be able to benefit both the students and the OSS community, so definitely let us know if you have other thoughts and suggestions to improve the quality of potential first-time contributors!

**Comment by tacaswell** [comment]
@itsmingjie We did not get to discussing this in more than passing on our call this week.  Can you wait another week for an answer?

**Comment by itsmingjie** [comment]
@tacaswell no worries! Just keep us updated. Thanks!

**Comment by tacaswell** [comment]
@itsmingjie  What is your timeline for this?

At this point we do not have anyone who is able to commit the time we think would be required on our side to do your request justice.   That said, if PRs come in from students they will be reviewed on a best effort-basis (just like any other PR!).

However, we are part of a recently funded grant from CZI (lead by @melissawm) that is funding Contributor Experience Leads across Matpoltlib, numpy, scipy, and pandas.  Many of the goals of this grant ([grant text](https://figshare.com/articles/online_resource/Advancing_an_inclusive_culture_in_the_scientific_Python_ecosystem/16548063) ) align extremely well with what you are proposing (improving on boarding is literally in the job description!).  Can we defer answering firmly either way until we have filled this position (the job posting just went up: https://quansight.breezy.hr/p/361a2e7da19b-contributor-experience-lead )?

I think once we have someone to fill the CEL role we will have a better idea for how we want to approach this.

----

As another point that came up in our discussions today is that historically contributors who are already Matplotlib users have had a much better time getting started as contributors (many of our problems are not "what is the right algorithm" but "what _should_ this do?") and having experience with plotting and data visualization as a means to an ends in some other context is extremely useful!

----

We very much appreciate you reaching out to us ahead of time and are very supportive (in principle) of what you are doing 👍🏻

**Comment by itsmingjie** [comment]
@tacaswell thanks for all this! 

re: timeline -- We have one cohort starting this October, but our partners at CSU would love to do one each season. So if we can't work something out that quickly, we're happy to reach out again for the next one around February! And yup, feel free to defer solid responses until you are able to (congrats on the grant!)

re: new contributors -- totally! I'm confident that we'll have quite a few students who have some experience with it (I think it's quite widely taught in intro data science curriculum in college classrooms). We're happy to provide some context in that direction when we're suggesting projects to students. 

Thanks for the kind words again -- just keep us updated when you have more information! In the meantime matplotlib remains something that we can suggest students contribute to with slightly less direct mentorship. We should also have some mentors who can help with higher-level/more generic questions.
