### ISSUE TITLE
[Bug]: figsize not updated when using ax.set_aspect('equal')

### ISSUE THREAD

**Issue by suddenlyfleck** [matplotlib/matplotlib#20953]
### Bug summary

When calling `ax.set_aspect('equal')` (or `plt.axis('image')`) for a `hist2d`,  the output of `fig.get_size_inches()` is not updated.

As far as I can tell, this causes problematic behavior when used in combination with GridSpec / gridspec_kw.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
 
x = np.random.normal(size=50000)
y = x * 3 + np.random.normal(size=50000)
fig, ax = plt.subplots()
ax.hist2d(x, y, bins=(30,30))

figsize1 = fig.get_size_inches()
ax.set_aspect('equal')
figsize2 = fig.get_size_inches()

print(all(figsize1 == figsize2)) # should be False
```

### Actual outcome

`True`

### Expected outcome

`False`

### Operating system

Debian

### Matplotlib Version

3.4.1

**Comment by jklymak** [comment]
This is expected behaviour.  The axes size and/or aspect does not affect the figure size.  

What is perhaps confusing you is if you are using bbox_inches=tight or the in-line backend for jupyter, then the figure is trimmed when it is saved (or rendered).

**Comment by QuLogic** [comment]
As noted, this is expected behaviour. The Figure and the Axes sizes are independent, other than one being clipped in the other.

**Comment by suddenlyfleck** [comment]
Is there any way to get the size of the displayed object after having set `ax.set_aspect('equal')`?

**Comment by jklymak** [comment]
Please ask for help with more details (preferably a self contained example so we can understand what object you are trying to get the size for) at https://discourse.matplotlib.org.  Thanks!
