### ISSUE TITLE
[ENH]: Multi-threaded implementation of plot3D

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#20968]
### Problem

* When using matplotlib for plotting 100 millions of points with 3d projection and plot3D, I noticed it uses only single thread on CPU. Any plans to speed this up by using multi-threaded implementation?

### Proposed solution

Multi-threaded implementation of plot3D

**Comment by timhoffm** [comment]
I believe this would be very hard to impossible as the underlying AGG renderer does not support multithreading and the problem is not separable.
