### ISSUE TITLE
[Bug]: ToolManager does not respect rcParams["keymap.<any>"] set after import time

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#20998]
### Bug summary

ToolManager currently reads `rcParams["keymap.{home,forward,etc.}"]` at import time, so any programmatic changes (even before any figure gets instantiated) is lost.  (I guess one *could* argue that supporting changes to the keymap after the toolmanager has been instantiated is not so important (though still desirable -- that's the behavior of classic toolbars), but at least it should be possible to change them immediately after import time.)

### Code for reproduction

```python
from pylab import *
plt.rcParams["toolbar"] = "toolmanager"; rcParams["keymap.quit"] = "Z"; plot()

then press "Z".
```

### Actual outcome

Nothing happens.

### Expected outcome

The figure closes.

### Matplotlib Version

master (unreleased, pre 3.5)

**Comment by timhoffm** [comment]
I think the correct solution is to read the respective rcParams at Tool-instatiation time. AFAICS this would mean that changed params take effect for new figures but not for existing figures.
