### ISSUE TITLE
[Bug]: Figure Size Cannot be Changed on Linux

### ISSUE THREAD

**Issue by andrfgs** [matplotlib/matplotlib#20996]
### Bug summary

 `plt.figure(figsize=(x, y))` and `fig.set_size_inches(x, y)` should change the figure size to specified `x` and `y` values in inches. But they do nothing at all on Linux, under X.

I know only one of them is meant to be used but neither work.

### Code for reproduction

```python
import numpy as np
from matplotlib import pyplot as plt

data = np.random.normal(size=50)
plt.figure(figsize=(3, 3))
plt.plot(range(0, len(data)), data)
fig = plt.gcf()
fig.set_size_inches(3, 3, forward=True)
plt.show()
```

### Actual outcome

The graph is shown in the default window size, ignoring either  `plt.figure(figsize=(x, y))` nor `fig.set_size_inches(x, y)`.

Neither  `plt.figure(figsize=(x, y))` nor `fig.set_size_inches(x, y)` seem to do anything for any values of `x`and `y`. Using `fig.set_size_inches(x, y, forward=True)` doesn't work either.

### Expected outcome

Figure size should be changed to the given values. In the code example, it should change the figure size to 3x3 inches, though any value I tried gets ignored.

### Operating system

Arch Linux

### Matplotlib Version

3.3.3

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8

### Other libraries

Using KDE (Qt) under an X Server (Xorg)

### Installation

pip

**Comment by timhoffm** [comment]
I cannot reproduce this behavior (it changes correctly here). Can you please try with another backend? E.g. insert *before* the pyplot import:
```
import matplotlib as mpl
mpl.use('tkagg')
```

**Comment by jklymak** [comment]
Also check that you are not using a window manager that automatically tiles windows.
