### ISSUE TITLE
[Bug]: regression with LineCollection + TwoSlopeNorm colorbar in matplotlib 3.5.0b1

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#20993]
### Bug summary

Some image comparison tests in a project of mine are failing when running matplotlib 3.50b1

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import TwoSlopeNorm
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)
# generate some data within some interval that doesn't have 0 its central value
z = y + 0.5

points = np.array([x, y]).T.reshape(-1, 1, 2)
segments = np.concatenate([points[:-1], points[1:]], axis=1)

# adapted from
# https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html
lc = LineCollection(segments, norm=TwoSlopeNorm(0), cmap="RdYlBu")
lc.set_array(z)

fig, ax = plt.subplots()

# this line is just to compensate for the fact that the limits are not
# automatically handled when the plot just contains a single LineCollection artist
ax.set(xlim=(0, 10), ylim=(-1, 1))

line = ax.add_collection(lc)
fig.colorbar(line)
```

### Actual outcome

![linecollection_mpl_v3 5 0b1](https://user-images.githubusercontent.com/14075922/132093627-e0e2ae13-77eb-4668-8894-42b9a15991ab.png)

### Expected outcome

This is the results with matplotlib 3.4.3
![linecollection_mpl_v3 4 3](https://user-images.githubusercontent.com/14075922/132093617-9b889a1a-6e9c-4ea9-a50c-a1957a1ea004.png)

### Operating system

OS/X

### Matplotlib Version

3.5.0b1

### Matplotlib Backend

MacOSX

### Python version

3.9.6

### Jupyter version

N/A

### Installation

pip

**Comment by neutrinoceros** [comment]
I should add that this seems specific to `LineCollection`. Now if I run a similar test for a contour plot

```python
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np

x, y = np.mgrid[1:100, 1:100]
z = np.random.random_sample(x.shape) - 0.75

fig, ax = plt.subplots()
im = ax.contourf(x, y, z, levels=50, cmap="RdYlBu", norm=TwoSlopeNorm(0))
cbar = fig.colorbar(im)
```
I get consistent results in matplotlib 3.4.3 and 3.5.0b1
![contourf_mpl_v3 5 0b1](https://user-images.githubusercontent.com/14075922/132093707-10f22be6-07bc-477e-8bbd-a9627124eabd.png)
This image was obtained with 3.5.0b1 and the behaviour is consistent with what the colorbar looks like for a `LineCollection` object in matplotlib 3.4.3 shown in the OP

**Comment by jklymak** [comment]
The 3.5 example above is an expected change and correct in my opinion.

**Comment by neutrinoceros** [comment]
In any case the behavior seems inconsistent between LineCollection and contour plots. Actually both outcomes seem reasonable to me as a user, and I would not mind too much if the change was actually embraced in the next release, I'm mostly worried that having such inconsistencies will make maintenance much harder down the road.

**Comment by jklymak** [comment]
There are _many_ inconsistencies between contour colorbars compared to other scalar mapable colorbars.   For instance:

```python
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm, LogNorm
import numpy as np

x, y = np.mgrid[1:100, 1:100]
z = np.abs(np.random.randn(*x.shape))

fig, ax = plt.subplots(1, 2, constrained_layout=True)
im = ax[0].contourf(x, y, z, levels=50, cmap="RdYlBu", norm=LogNorm(vmin=0.01, vmax=10))
cbar = fig.colorbar(im, ax=ax[0])

im = ax[1].pcolormesh(x, y, z, cmap="RdYlBu", norm=LogNorm(vmin=0.01, vmax=10))
cbar = fig.colorbar(im, ax=ax[1])
plt.show()
```

yields:

![Out](https://user-images.githubusercontent.com/1562854/132118545-b4cd811a-cb43-48f7-a835-3dc397d7b11b.png)

While I think that can/should be improved to be consistent with other scalar mappables, I don't think there is a regression, because I think this has been this way for a long time.

**Comment by neutrinoceros** [comment]
Feel free to change the title of the ticket if it helps triaging it.

**Comment by jklymak** [comment]
So, sorry, that example was a bit misleading because of #19856

However, a better example is

```python
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm, LogNorm
import numpy as np

x, y = np.mgrid[1:100, 1:100]
z = np.abs(np.random.randn(*x.shape))

fig, ax = plt.subplots(2, 2, constrained_layout=True)
im = ax[0, 0].contourf(x, y, z, levels=np.linspace(0.1, 10, 20), cmap="RdYlBu", norm=LogNorm(vmin=0.1, vmax=10))
cbar = fig.colorbar(im, ax=ax[0, 0])
ax[0, 0].set_title('linear spaced contours')

im = ax[0, 1].contourf(x, y, z, levels=np.logspace(-1, 1, 20), cmap="RdYlBu", norm=LogNorm(vmin=0.1, vmax=10))
cbar = fig.colorbar(im, ax=ax[0, 1])
ax[0, 1].set_title('logarithmically spaced contours')

im = ax[1, 0].pcolormesh(x, y, z, cmap="RdYlBu", norm=LogNorm(vmin=0.1, vmax=10))
ax[1, 0].set_title('pcolormesh')
cbar = fig.colorbar(im, ax=ax[1, 0])
fig.savefig('/Users/jklymak/downloads/Ex2.png', dpi=100)
plt.show()
```

So, what is happening here?  First note that for all three examples the colormapping is the same.  1.0 is the middle of the colormap.  

The colorbar is plotting the contours equally spaced on the axes, such that each contour level gets the same amount of space on the colorbar.  When you specify the contours linearly, there are far more of them above 1.0 than below, and that part of the axes is emphasized.  The axes are formatted with a default formatter. 

Its _possible_ we could toggle this to have the colorbar follow the norm, but that would be a feature request.

**Comment by neutrinoceros** [comment]
Your explanation with contour plots makes a lot of sense. However, it seems to me that it actually reinforces my point

>  there are far more of them above 1.0 than below, and that part of the axes is emphasized.

So in my OP, there are more levels above 0 than bellow, so I'm _expecting_ the colorbar to emphasise this, which is exactly what matplotlib 3.4.3 does. I do not understand how the 3.5.0b1 version is doing it better.
Perhaps more importantly, it doesn't seem like there's an easy way for me to reproduce my figures as I know them if I eventually migrate to 3.5. Is there ?

**Comment by jklymak** [comment]
The two-slope norm puts the _same_ number of colours above and below the midpoint, and the new colorbar in 3.5 properly reflects that.  

If you want the old behaviour, I believe you can just change the colorbar scale to be linear. (Away from computer so I'd have to check the details)

**Comment by jklymak** [comment]
As below, you can just set the colorbar yscale:

```python
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import TwoSlopeNorm
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)
# generate some data within some interval that doesn't have 0 its central value
z = y + 0.5

points = np.array([x, y]).T.reshape(-1, 1, 2)
segments = np.concatenate([points[:-1], points[1:]], axis=1)

fig, axs = plt.subplots(1, 2, constrained_layout=True)

for ind in range(2):
    ax = axs[ind]
    # this line is just to compensate for the fact that the limits are not
    # automatically handled when the plot just contains a single LineCollection artist
    ax.set(xlim=(0, 10), ylim=(-1, 1))
    lc = LineCollection(segments, norm=TwoSlopeNorm(0), cmap="RdYlBu")
    lc.set_array(z)

    line = ax.add_collection(lc)
    cbar = fig.colorbar(line, ax=ax)
    if ind == 1:
        cbar.ax.set_yscale('linear')
        ax.set_title('Linear colorbar')
    else:
        ax.set_title('Default colorbar')
fig.savefig('/Users/jklymak/downloads/Ex3.png', dpi=100)
plt.show()
```

I _wanted_ to add ` cb.set_scale`, but that may still be future discussion.  

![Ex3](https://user-images.githubusercontent.com/1562854/132228104-009b4c79-3608-4475-a7da-0928dfe1538d.png)

**Comment by neutrinoceros** [comment]
Great ! I'll use that then.

> I wanted to add cb.set_scale, but that may still be future discussion.

yeah well, Rome wasn't built in a day. I deeply appreciate the gigantic effort you've been undertaking, and the time you've been pouring in answering my annoying questions and reports :)

I think this can be closed now, thank you so much for you help !

**Comment by jklymak** [comment]
Well norms are definitely confusing.  I think the confusing thing here is when the norm gets applied, before or after digitization  by contour levels or the finite colormap.  One of the main points of #20054 was to make norms _other_ than log norm behave like lognorm.   OTOH, if the release notes aren't clear enough about that, we should try and fix them before the final release.

**Comment by neutrinoceros** [comment]
TBH it didn't occur to me that this change _could_ be desired when I reported, so I didn't lookup the release notes.

**Comment by jklymak** [comment]
Again, consider the logarithmic case; almost certainly you do not want a linear axes in that case.   For the two-slope norm, presumably if you want a different magnification on either side of zero you also want different resolution in the scale.

**Comment by neutrinoceros** [comment]
In the future, probably. Right now I'm just trying to maintain existing scripts for figures that are part of a scientific publication, so reproducibility is what I care most about here :)

**Comment by jklymak** [comment]
You could package your environment somehow rather than try and make it work on future versions of everything.

**Comment by neutrinoceros** [comment]
True. I actually wasn't trying, just _accidentally_ ended up testing with a beta version

**Comment by tacaswell** [comment]
It is yet another API change, but we should also think about making the Locators on colorbars default to putting a tick on the top/bottom of the range.

**Comment by jklymak** [comment]
@tacaswell we don't delimit the top and bottom for normal axes.   Is it desirable for colorbars for some reason?   

In the case of two-slope norm, it is currently using the linear locator, but it should probably have a custom locator that has a tick at the midpoint, and ticks out differently above and below the midpoint.
