### ISSUE TITLE
[Doc]: axes.titley not found in plt.rcParams.keys().

### ISSUE THREAD

**Issue by sarthakforwet** [matplotlib/matplotlib#20992]
### Documentation Link

https://matplotlib.org/stable/gallery/text_labels_and_annotations/titles_demo.html

### Problem

While working on a project, I came to discover that I wasn't able to call `plt.rcParams[axes.titley]` but it was being used in the tutorial itself. I think I am making a mistake in the way of calling it. However, if we could not find any mistake in my code, the documention corresponding to this key would then be required to be updated.

![image](https://user-images.githubusercontent.com/46163196/132082944-48d2408c-a969-4b69-af27-4d6cdcf50d22.png)

### Matplotlib Version

3.2.2

### Matplotlib documentation version

3.4.3

**Comment by jklymak** [comment]
Please use discourse.Matplotlib.org or stackoverflow for user help.  Of course if there is a concrete change to be made to the docs come back and let us know.  Also please avoid screenshots of your code in any site. Thanks for your understanding!

**Comment by timhoffm** [comment]
`rcParams['axes.titley']` has only been introduced in Matplotlib 3.3. Please update if you want to use it.

https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.3.0.html#axes-set-title-gains-a-y-keyword-argument-to-control-auto-positioning
