### ISSUE TITLE
[ENH]: Convert non-real numbers to categorical data

### ISSUE THREAD

**Issue by Illviljan** [matplotlib/matplotlib#21001]
### Problem

I think since categorical data works great in mpl there is some opportunity to improve plotting other data types as well.

Which one of these plots are more useful for these complex numbers?

```python
import numpy as np 
import matplotlib.pyplot as plt


x = 1j * np.arange(0, 5)
y = np.arange(5, 10)
plt.plot(x, y)
ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)
```
![image](https://user-images.githubusercontent.com/14371165/132037646-8ade69af-9201-4218-a2d2-1cb1c6954328.png)

```python
x = 1j * np.arange(0, 5)
y = np.arange(5, 10)
plt.plot(np.vectorize(str)(x), y)
```
![image](https://user-images.githubusercontent.com/14371165/132037845-cf04623e-5f36-4d65-b5b4-b2433366fe14.png)

Or how about being able to plot these coordinate-like objects:
```python
import pandas as pd


arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
a = pd.MultiIndex.from_arrays(arrays, names=('number', 'color')).to_numpy()
b = np.arange(4, 8)
plt.plot(np.vectorize(str)(a), b)
```
![image](https://user-images.githubusercontent.com/14371165/132048322-fb83cdbf-9720-4ed4-b75e-52bb7a41055f.png)

### Proposed solution

When the data has correct `.shape` but isn't a real number, convert it to categorical data using `np.vectorize(str)`.

**Comment by jklymak** [comment]
This would arbitrarily converting all unregistered types to strings.  

```python 
x = 1j * np.array([0, 2, 1, 4])
y = np.arange(5, 10)
plt.plot(np.vectorize(str)(x), y)
```

would not plot as the user would expect, and I think it is better to error and for the user to tell us what they mean explicitly.  Confusion about categorical plotting is already rampant on StackOverflow, and this would compound the issue.

**Comment by Illviljan** [comment]
So what result does a user expect when plotting a complex number along the x-axis?

**Comment by jklymak** [comment]
I'd argue that is up to the user - they can explicitly convert it to a real depending on their need.

**Comment by mwaskom** [comment]
Maybe you want `plt.plot(x.imag, y)`?

**Comment by Illviljan** [comment]
No, I want the elements inside the 1d array (complex, MultiIndex-like or object) to be shown by default on the plot. 

Here's another example:
```python
x = 1j + np.arange(0, 5)
y = np.arange(5, 10)
plt.plot(np.vectorize(str)(x), y)
```
![image](https://user-images.githubusercontent.com/14371165/132039166-720de3f9-ef16-419b-aaf6-68f9dac6c59f.png)

@jklymak's example changes the order of elements which can be fixed using `np.argsort` before converting to string. The jump between 2 to 4 not being twice the distance in the plot will indeed not be handled though.

I can see just throwing errors is easier maintanence-wise. But I suppose I prefer it to just show what's inside the 1d array instead of erroring or converting to real float values.

**Comment by mwaskom** [comment]
What happens when

a) you have variation in both the real and imaginary parts of your vector
b) you have more than a handful of unique values

?

**Comment by Illviljan** [comment]
a) They will be shown in whatever order `np.argsort` decides is proper. So some kind of flattened version.
b) I suppose you mean how to hide labels? My idea was for it to behave the same as categoricals does currently. So I guess it wont handle it?

**Comment by mwaskom** [comment]
I would like to learn about FFTs. So I do

```python
x = np.arange(1000)
y = np.sin(x / 10) + np.random.normal(0, .5, x.size)
fy = np.fft.fftshift(np.fft.fft(y))
```

and then look at the result with 

```python
plt.plot(fy)
```
![image](https://user-images.githubusercontent.com/315810/132139296-6b1b8299-4342-4c54-bbec-7f9e64797e8c.png)

I get a warning about the imaginary part getting discarded — ok, I need to figure out what's up with that, but I get a plot that makes some sense and an explicit message about what matplotlib did internally to handle an ambiguous input.

But if I do (or if matplotlib does the equivalent of)

```python
plt.plot(np.vectorize(str)(fy))
```
![image](https://user-images.githubusercontent.com/315810/132139371-bd9c8148-5fef-4504-ad4a-01326c5eab1a.png)

then I get a result that is a) not close to any conception of "correct" and b) impossible to understand unless I have some esoteric knowledge about how matplotlib categoricals work.

**Comment by Illviljan** [comment]
The fact the labels are unreadable is true now with any categoricals so that's a different issue, I think you can get the same look with all the available types of flowers in the world as well.

So fy contains complex numbers:
```python
>>> fy
array([ 5.29094322e+00-3.10862447e-15j, -1.28916629e+01+6.21354386e+00j,
        3.86355927e+00+1.38505901e+01j,  9.26447280e+00+9.10987625e+00j,
(...)
```
In a dream world we would have been able to read `5.29094322e+00-3.10862447e-15j` from the ylabels and notice that the complex numbers are being plotted matches the elements in `fy` exactly. So I would come to the conclusion that I got exactly what I asked for when coding `plt.plot(fy)`.

**Comment by mwaskom** [comment]
> The fact the labels are unreadable is true now with any categoricals so that's a different issue

It is, but there is an assumption about "categorical" data that you don't have "too many" unique values of it. 

That assumption doesn't always hold, of course, and the current behavior is definitely a source of confusion at times, but it's hard to avoid: if you have an ordinal list of strings, there's no way to omit some of them without destroying information, except in special cases.

But complex numbers tend to pop up most commonly in situations where you're doing some kind of signal processing and likely have a large number of unique values. (At least that's been my experience — because matplotlib is used in such a wide range of domains, I'm sure others have had a different experience). So unlike with "true" categories, where you can reasonably hope that a large cardinality is the rare case, small cardinality is very likely the rare, unusual case when you're talking about complex numbers.

>  So I would come to the conclusion that I got exactly what I asked for when coding `plt.plot(fy)`

Expectations are like opinions (and the other thing) but complex numbers are often visualized on a 2D plane where the real and imaginary parts map to the x and y axes. If *I* were to expect any "magical" handling of `plt.plot(fy)`, it would be that.

And different people will understand themselves to be "asking for" different things there, but I would disagree that giving matplotlib a complex **number** and having it plot a **string** instead is doing "exactly" what was asked

**Comment by Illviljan** [comment]
> It is, but there is an assumption about "categorical" data that you don't have "too many" unique values of it.

My opinion (another one) here is that matplotlib should start filtering them once it starts looking like shit. For example by hiding every other categorical or something like that until the text height times the number of labels is less than the total axis height. 

By looking at some of our plots it looks like around 20 categoricals it will start to fill up the entire axis.  +20 categoricals seems doable to me but any more and it will become unreadable (but technically not destroyed!).

The labels should pop up again if you zoom in a little just like floats would do, and if the categoricals were sorted it should be pretty easy guessing where the missing labels should be.

> Expectations are like opinions (and the other thing) but complex numbers are often visualized on a 2D plane where the real and imaginary parts map to the x and y axes. If _I_ were to expect any "magical" handling of `plt.plot(fy)`, it would be that.

But `plt.plot(fy)` as you know always implies `plt.plot(x=np.arange(len(fy)), y=fy)` in the world of matplotlib. That's why I wouldn't expect `plt.plot(fy)` to all of a sudden decide to behave like `plt.plot(x=fy.real, y=fy.imag)` even though it's the typical way complex numbers are plotted.

**Comment by mwaskom** [comment]
That's an interesting (if contestable) idea about how matplotlib should handle the tick labels for dense categorical axes.

But even if label overlap was not an issue, I still think that it's very unclear why complex numbers should be coerced to strings and plotted with interval spacing by default. You motived your proposal with a toy example where you only had variation in the imaginary part, and the imaginary values had unit spacing. But what about the more general case?

Or, specifically, even if you could read the y tick labels on the FFT plot, what insight about the structure of the data is afforded by a constant diagonal line?
