### ISSUE TITLE
[Bug]: distutils deprecation

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#21057]
### Bug summary

[Python 3.10 formally deprecated distutils.](https://www.python.org/dev/peps/pep-0632/)
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
matplotlib still contains a few occurrences which should probably be removed:
```
setup.py:from distutils.errors import CompileError
setup.py:from distutils.dist import Distribution
setup.py:setup(  # Finally, pass this all along to distutils to do the heavy lifting.
setupext.py:from distutils import ccompiler, sysconfig
setupext.py:from distutils.core import Extension
setupext.py:        Return or yield a list of C extensions (`distutils.core.Extension`
```

### Code for reproduction

```python
-
```

### Actual outcome

-

### Expected outcome

-

### Operating system

Ubuntu

### Matplotlib Version

master

**Comment by QuLogic** [comment]
I was aware, but setuptools does not fully replace distutils: pypa/setuptools#2698
