### ISSUE TITLE
imshow size limitation

### ISSUE THREAD

**Issue by NeedAName** [matplotlib/matplotlib#2105]
imshow() and matshow() fail to display matrices larger than 2^15 in horizontal dimension,
e.g.:
M = np.ones((100,100000))
plt.imshow(M, cmap='jet', aspect='auto', alpha = 1, origin = 'lower', interpolation = 'none')
plt.show()

matplotlib 1.2.1, 
ubuntu gnome 12.10

**Comment by petehuang** [comment]
Reconfirming on 1.5.3 and TkAgg

**Comment by dstansby** [comment]
The original code snipped seems to work fine for me on both `macosx` and `Qt5Agg` backends, so closing. If this is still an issue with a recent release, please re-open or post a comment!
