### ISSUE TITLE
[ENH]: A data-type check is missed in cm.ScalarMappable.set_array()

### ISSUE THREAD

**Issue by MiguelonGonzalez** [matplotlib/matplotlib#21095]
### Problem

If a list is introduced to cm.ScalarMappable.set_array() method, no error is raised and, nevertheless, probably an error will be raised.

At least, it's raised when using collections:

AttributeError: 'list' object has no attribute 'ndim'

### Proposed solution

I think it could be great to add a data type check when data is introduced to this method Although the own name of the method means that the enter data-type must be a numpy array, I think it could be less messy if an exception (or something similar) would be added within this method.

**Comment by jklymak** [comment]
Thanks for reporting this.  Can you provide a runnable example?

**Comment by anntzer** [comment]
This is almost certainly fixed by https://github.com/matplotlib/matplotlib/pull/18870 in matplotlib 3.5.
