### ISSUE TITLE
Image not same size as plot

### ISSUE THREAD

**Issue by gersmit** [matplotlib/matplotlib#21094]
**I save an image with from pyresample.geometry import AreaDefinition :**
local_scn.save_dataset(masked_img[0],
                       filename='/home/pi/a-satpy-testen/images/'+ file_name + ' transp_scn'+'.png',
                       overlay={'coast_dir': '/home/pi/a-satpy-testen/GSHHS_DATA_ROOT/',
                                'overlays': {'grid': grid,
                                             'coasts': coast,
                                             'borders': borders,
                                             'rivers': rivers
                                            }})

**Then i load image:**
fig = plt.figure(figsize=(10, 7.5))

fname = '/home/pi/a-satpy-testen/images/'+ file_name + ' transp_scn'+'.png'
img_extent = (-10, 25, 32, 58)  #== lon-, lat-, lon+, lat+ == same coordinate as i save the image
img = plt.imread(fname)

land = cartopy.feature.NaturalEarthFeature('physical', 'land', 
                            '10m', edgecolor='face', facecolor='beige')

ax = plt.axes(projection=ccrs.PlateCarree())
plt.title(file_name + ' satellite\n'
          '2012 09/26/2012 20:50 UTC')

ax.add_feature(land, facecolor='green', zorder=1, alpha=0.1)
ax.coastlines(resolution='50m', color='blue', linewidth=1)
ax.add_feature(cfeature.BORDERS.with_scale('50m'))
ax.imshow(img, origin='upper', extent=img_extent, transform=ccrs.PlateCarree())

ax.axis('tight') 
plt.savefig('/home/pi/a-satpy-testen/images/'+ file_name + ' transp_background' +'.png', transparent=True)
plt.show()

**Why is the coordinate not the same, there is a diverence between blue and white coastlines, see attachement.
What do i have to do to make the coordinates equal**
![coordinate not the same JPG](https://user-images.githubusercontent.com/38345229/133596697-3307fca2-2b6d-480b-8d80-3ec0f1af3862.jpg)

**Comment by jklymak** [comment]
First please take user help to https://discourse.matpltolib.org.  Second, your question is about cartopy, which is a library built on top of matplotlib. https://scitools.org.uk/cartopy/docs/latest/  My guess is some error in how you are saving the original image, or that it is being saved to a projection so it should be plotted with a different transform.  I'll close here though as off topic.  Thanks!
