### ISSUE TITLE
[Bug]: Errorbars separated from markers with negative errors

### ISSUE THREAD

**Issue by nbrunett** [matplotlib/matplotlib#21101]
### Bug summary

If unique upper and lower errors are specified, and one of them is negative, then the errorbar will appear separate from the marker. It looks like this was mentioned ages ago in #2717 but I could not find a follow up to that issue.

### Code for reproduction

```python
import matplotlib.pyplot as plt

# 1
plt.errorbar([0], [0], yerr=[[-0.5], [1]], marker="o")

# 2
plt.errorbar([0], [0], xerr=[[-0.5], [1]], marker="o")

# 3
plt.errorbar([0], [0], xerr=[[-0.5], [1]], yerr=[[-0.5], [1]], marker="o")
```

### Actual outcome

# 1

![image](https://user-images.githubusercontent.com/7672534/133683908-e7b6f58d-67b7-46ae-a570-6a09ba1bbca8.png)

# 2

![image](https://user-images.githubusercontent.com/7672534/133683996-58793a04-0027-49ad-85d4-2213ceeea5bf.png)

# 3

![image](https://user-images.githubusercontent.com/7672534/133684029-f1bce9ec-f7b7-4fdf-aced-15f60262fdf7.png)

### Expected outcome

I understand the documentation states that the error inputs should be positive values, but I would expect some error like `ValueError` when there is a negative value provided, rather than it trying to make the plot. I would prefer an error being thrown and the plot not being made.

### Operating system

CentOS Linux release 7.9.2009 (Core)

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.6

### Jupyter version

3.1.9

### Installation

conda

**Comment by tacaswell** [comment]
So I see why it is doing this ('we draw the error bar from `(val - lower_error, val + upper_error)`), but I agree, if we document that negative errors should not work, we should do the validation and raise ValueError

The tasks here are:

 - add validator to at at least the `errorbar` method
 - investigate how much work it would be to add validation to updating the errorbars after-the-fact (I think in that case the user has to do the offsets them selves so there may be nothing we _can_ do)
 - add a test

**Comment by lucafs** [comment]
take

**Comment by lucafs** [comment]
I will try to work on this near future.
