### ISSUE TITLE
[Doc] Collapse menu on mobile by default

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#21117]
On mobile the menu is expanded, which takes up all the space.
![Screenshot_20210918-211922.jpg](https://user-images.githubusercontent.com/1300499/133912498-81f64fc7-265d-489e-84c6-f987adddd7ab.jpg)

Probably an easy fix, but can the default be that menus are collapsed?
![Screenshot_20210918-212419__01.jpg](https://user-images.githubusercontent.com/1300499/133912529-891ce895-6079-4563-8c23-c713121ac0b4.jpg)

**Comment by timhoffm** [comment]
Isn‘t that something to report upstream to the pydata-Sphinx-theme?

**Comment by story645** [comment]
Have no idea if it's a way we implement it thing or a default...

**Comment by timhoffm** [comment]
If you look at the sub-pages of https://numpy.org/doc/stable/, the menu is expanded as well, so I assume it's the default.
