### ISSUE TITLE
Qt swapping ctrl and cmd on OSX

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#21110]
There is special casing for ctl / cmd in the Qt backend on OSX

https://github.com/matplotlib/matplotlib/blob/9465538da0ebd041c3a87f7b004339c17576ae55/lib/matplotlib/backends/backend_qt.py#L49-L51

That is making the tests fail.  

Looking at a US mac keyboard on the left side I see:

```
ctrl | option | command
```

and looking at US windows keyboard I see

```
ctrl | meta (aka windows) | alt
```

however that does not tell us what keycodes they actually generate.

We used to implement this logic differently (before we unified the qt backend code) 

### 3.4.3

https://github.com/matplotlib/matplotlib/blob/919145fe9849c999aa491457c6de6faede5959c3/lib/matplotlib/backends/backend_qt5.py#L62-L67

### 3.2.2

https://github.com/matplotlib/matplotlib/blob/a1a5298b0d4a8d8230103d0fa8d369fca7fdeea0/lib/matplotlib/backends/backend_qt5.py#L70-L85

This swapping goes all the way back to 5fdd68adac02827bb28f17ea88d2a6996c4acb1d (2012).

I think we need to:

 - have a mac user with a mac keyboard veryify that the keys they hit match the keycodes we expect
 - if the keys are right to the human typing then fix the tests (probably by tweaking what the key-codes fed in are)
 - if the keys are wrong to the human typing
    - if they are consistent across mpl versions on osx: gnash our teeth in despair and figure out how we want to fix this (on one hand, we should make sure that the key-codes are consistent across platfroms, on the other hand we do not want to break existing OSX users).
    - if they changed from 3.4 to the default branch, fix the re-mapping

I also have a worry that Qt has started to fix this for us.

----

FYI: I just ran the latest tests and these are now failing for me and I'm wondering if it has to do with being on a mac? The tests look like they are swapping cmd/ctrl, so I tried swapping the modifier keys on my system and that didn't help.

```bash
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[Qt5Agg-control] - AssertionError: assert 'cmd+a' == 'ctrl+a'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[Qt5Agg-alt_control] - AssertionError: assert 'alt+cmd' == 'alt+control'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[Qt5Agg-control_alt] - AssertionError: assert 'cmd+alt' == 'ctrl+alt'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[Qt5Agg-modifier_order] - AssertionError: assert 'cmd+alt+ctrl+á' == 'ctrl+alt+super+á'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[Qt5Agg-backspace_mod] - AssertionError: assert 'cmd+backspace' == 'ctrl+backspace'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[QtAgg-control] - AssertionError: assert 'cmd+a' == 'ctrl+a'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[QtAgg-alt_control] - AssertionError: assert 'alt+cmd' == 'alt+control'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[QtAgg-control_alt] - AssertionError: assert 'cmd+alt' == 'ctrl+alt'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[QtAgg-modifier_order] - AssertionError: assert 'cmd+alt+ctrl+á' == 'ctrl+alt+super+á'
FAILED lib/matplotlib/tests/test_backend_qt.py::test_correct_key[QtAgg-backspace_mod] - AssertionError: assert 'cmd+backspace' == 'ctrl+backspace'
```

It looks like these _may_ be getting skipped on the macos-latest CI?

```bash
SKIPPED [22] lib/matplotlib/tests/test_backend_qt.py:168: No usable Qt bindings
```

_Originally posted by @greglucas in https://github.com/matplotlib/matplotlib/issues/20868#issuecomment-921432176_

**Comment by dstansby** [comment]
https://doc.qt.io/qt-5/qt.html#Modifier-enum says:

> Note: On macOS, the CTRL value corresponds to the Command keys on the keyboard, and the META value corresponds to the Control keys.

so I think the failing tests make sense; as an example, with `qt_key = 'Key_A'` and`qt_mods = ['ControlModifier']` we should be identifying this as `ctrl+A`, apart from on macOS where `ControlModifier` means the Command key has been pressed. So the solution seems to be change the expected answer in the tests if run on macOS.

**Comment by tacaswell** [comment]
>  So the solution seems to be change the expected answer in the tests if run on macOS.

Expected answer or input?  I would lean towards the input side as what we want is "the user hit the key that produces ctrl in our output" which from a user point of view is what we want to preserve.

**Comment by timhoffm** [comment]
Ctrl on Mac is something different than Ctrl on other platforms, it just happens to have the same name. On a Mac, the equivalent to `Ctrl` is `Cmd` (e.g. `Cmd+C` is copy).

Qt as a cross-platform framework has decided to map this internally, so that `Cmd+C` will still give the `Qt::CTRL` modifier, which is reasonable because this way the application code does not have to distinguish between platforms.

Without checking, I think our current behavior is
- on Mac: `Cmd-C` -> `Qt::CTRL+Qt::Key_C` -> `'cmd-c'`
- on other: `Ctrl-C` -> `Qt::CTRL+Qt::Key_C` -> `'ctrl-c'`

Since `test_backend_qt.py::test_correct_key` entries at the Qt level, we have to adapt the expected outputs to make the tests pass.


A second question is whether this native remapping is reasonable or if we should behave like Qt. If platform independence is desireable, we could introduce a rcParam that allows to configure that. We cannot switch hard without breaking user code.
