### ISSUE TITLE
[Bug]: Line2D should copy its inputs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#21147]
### Bug summary

Currently, Line2D doesn't copy its inputs if they are already arrays.  Most of the time, in-place modifications to the input arrays do *not* affect the draw line, because there is a cache that doesn't get invalidated, but in some circumstances, it *is* possible for these modifications to affect the drawn line.

Instead, Line2D should just copy its inputs.  This was rejected in #736 on a memory-saving argument, but note that AxesImage (which would typically have much bigger (2D) inputs than Line2D (which has 1D inputs)) does a copy, which if anything is much worse memory-wise.

### Code for reproduction

```python
from pylab import *
t = arange(0, 6, 2)
l, = plot(t, t, ".-")
savefig("/tmp/1.png")
t[:] = range(3)  # in place change
savefig("/tmp/2.png")  # no effect
l.set_drawstyle("steps")  # ... unless we trigger a cache invalidation
savefig("/tmp/3.png")  # in fact, only the x array got updated, not the y
```

### Actual outcome

(1)
![1](https://user-images.githubusercontent.com/1322974/134257080-5f1afea6-59b0-429b-9ab4-bb4187942139.png)
(2) (same as (1))
![2](https://user-images.githubusercontent.com/1322974/134257087-a2dc2907-819e-4e50-8028-946677fff811.png)
(3) (different, but only x got updated, not y)
![3](https://user-images.githubusercontent.com/1322974/134257088-854fcbd6-407b-434e-b9cb-5583a8be3d77.png)

### Expected outcome

Modifying `t` a posteriori should not affect the Line2D.  Compare e.g. with AxesImage:
```python
im = arange(9).reshape(3, 3)
imshow(im)
savefig("/tmp/4.png")
im[:, :] = im[::-1, ::-1]
savefig("/tmp/5.png")
```
Both images are identical.

### Operating system

linux

### Matplotlib Version

3.5b1

### Matplotlib Backend

mplcairo

### Python version

39

### Installation

source

**Comment by aitikgupta** [comment]
Seems like a well defined what-to-do (with a lot of examples at other places in the code) -- adding it as a good first issue/hacktoberfest-accepted

**Comment by pedabraham** [comment]
Hi 🙋‍♂️ I would like to see if I can solve the problem.
Just to make sure that I understood the expected outcome in the example. Should the **y** be ending in 2, right?
