### ISSUE TITLE
[Bug]: eps fail on epstopdf conversion in v3.4.1 but not v3.1.3

### ISSUE THREAD

**Issue by leaxael** [matplotlib/matplotlib#21155]
### Bug summary

Plot graph and save with `plt.savefig('out.eps')`. In shell do `epstopdf out.eps`. The eps produced in matplotlib v3.1.3 would convert without problems. However, epstopdf reported errors for the eps produced by matplotlib v3.4.1.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np 

# test data
d = np.random.rand(100, 4)  

# stacked barplot
bottom = [0]*len(d)
plt.figure(figsize=(15,6))  # tall
for i in range(0, 4):
    plt.bar(range(len(d)), [_[i] for _ in d], width=1, 
            label='abcd'[i], 
            bottom=bottom)
    bottom = np.array(bottom) + np.array([_[i] for _ in d])

# crop
ax = plt.gca()
ax.set_xlim(xmin=0, xmax=len(d))
ax.set_ylim(ymin=0, ymax=1)

legend = ax.legend(frameon=False, bbox_to_anchor=(1, 0.95, 0, 0),
   markerfirst = False,
   markerscale=5, fontsize=legend_font_size)

# save
plt.savefig('testplot.eps')
plt.show()

# then in bash do: epstopdf testplot.eps
```

### Actual outcome

Failed epstopdf run reports:

```
Error: /undefined in --setcachedevice--
Operand stack:
   CharStrings   --dict:5/13(L)--   i   --nostringval--   1300   0   113   -29   1114   1556
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2047   1   3   %oparray_pop   2046   1   3   %oparray_pop   --nostringval--   2026   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--
Dictionary stack:
   --dict:956/1684(ro)(G)--   --dict:0/20(G)--   --dict:82/200(L)--   --dict:10/11(L)--   --dict:6/10(L)--   --dict:5/13(L)--
Current allocation mode is local
GPL Ghostscript 9.25: Unrecoverable error, exit code 1
```

### Expected outcome

Expect `epstopdf` to work. The code snippet will work if ran with matplotlib v3.1.3.

### Operating system

Ubuntu and CentOS6

### Matplotlib Version

3.4.1

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.7.6

### Jupyter version

6.3.0

### Other libraries

`epstopdf --version` says:

```
epstopdf ($Id: epstopdf.pl 45306 2017-09-14 21:41:37Z karl $) 2.27
Copyright 2009-2017 Karl Berry et al.
Copyright 2002-2009 Gerben Wierda et al.
Copyright 1998-2001 Sebastian Rahtz et al.
License RBSD: Revised BSD <http://www.xfree86.org/3.3.6/COPYRIGHT2.html#5>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### Installation

pip

**Comment by jklymak** [comment]
Can you narrow this down any further, i.e. do you _need_ to be plotting a bar plot, or add a legend?

FWIW, I cannot reproduce this on master, using exactly the same epstopdf as you and (more importantly) Ghostscript 9.52.  Are you _sure_ the same thing works for 3.1.3 with the same epstopdf/gs?  Maybe you changed gs versions?

**Comment by leaxael** [comment]
I tried a bit more. So first, it turned out to be only affecting 3.4.1 or maybe some versions earlier, but not 3.4.2 or 3.4.3. Guess it's time for me to update. 

This issue isn't seen in many of my other test plots with v3.4.1. I'm not sure what exactly went wrong with this particular specimen, but applying changes of `backends/backend_ps.py` in [this commit](https://github.com/matplotlib/matplotlib/commit/3e94489220d72278b4f98a37f41a79b01f13de13), which used `_d` instead of `d` glyph, would make the v3.4.1 eps output to be compatible with `epstopdf`, so I assume this is the culprit. 

Thank you!

**Comment by jklymak** [comment]
OK, thanks for getting back to us - possible a bug snuck in, and then was subsequently fixed.  Sorry for the confusion!
