### ISSUE TITLE
[ENH]: saving images in webp format

### ISSUE THREAD

**Issue by LinasNas** [matplotlib/matplotlib#21162]
### Problem

I've noticed that matplotlib currently doesn't support saving images in webp format, which I later confirmed by looking into supported file formats in [backend_bases.py](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py) file. 

Saving images in webp would definitely be useful for users who want to upload the graphs they generate in matplotlib to the web. Compression to webp helps significantly reduce the image size, without losing quality. More information about webp can be found [here](https://developers.google.com/speed/webp).

### Proposed solution

Would it be possible to add webp as a supported image saving format? It seems that ```Pillow``` package is automatically installed as a dependency when installing ```matplotlib```. ```Pillow``` makes it relatively easy to convert an image to webp using the ```save()``` method. More detailed information can be found in the [documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html?highlight=webp#webp)

**Comment by jklymak** [comment]
I think if pillow supports this, it is a pretty easy thing to add.

**Comment by AtulKarn** [comment]
Can I work on this issue? I am new to open source and it looks like a good place to start

**Comment by jklymak** [comment]
Hi @AtulKarn Yes.  Please read our contributing guide.  Otherwise, we do not "assign" issues, so feel free to make a PR.  In terms of etiquette, it is fine for anyone to submit a PR, but once a PR is submitted, it is usually preferable to work with the original PR author than submit a competing PR.

**Comment by timhoffm** [comment]
It's also good to comment that you have started working on a PR to prevent accidental duplicate work. But as said, you don't have to ask to work on something.

**Comment by AtulKarn** [comment]
Thanks for the response. I will work on this and read the guide and also ask if I have any difficulties.

**Comment by Critical07** [comment]
Hey, can I work on this? I am new to open source and wanted to start from here.

**Comment by timhoffm** [comment]
@Critical07 please note that @AtulKarn has announced that he'll be working on the issue. Please coordinate with him to prevent duplicate work or choose another issue.

**Comment by AtulKarn** [comment]
@Critical07 Hi. I am currently working on this, and if I am unable to do it in a few days, then you can take it. I will mention if I am unable to complete it

**Comment by aitikgupta** [comment]
Added a `hacktoberfest-accepted` label, so any related PR will add on to users' contribution count.

**Comment by remram44** [comment]
`hacktoberfest-accepted` is used to mark PRs as accepted, it does nothing on issues. Since this repository has the `hacktoberfest` topic, it is unnecessary to use the label as merging or approving a PR will already make it count.

See: https://hacktoberfest.digitalocean.com/resources/participation

**Comment by dewanshrawat15** [comment]
@jklymak I think Pillow does support saving images in webp. Reference [this](https://medium.com/@ajeet214/image-type-conversion-jpg-png-jpg-webp-png-webp-with-python-7d5df09394c9) medium article

**Comment by Critical07** [comment]
@AtulKarn OK I'll wait take your time
