### ISSUE TITLE
[Bug]: scatter plot use pie marker loose some pieces

### ISSUE THREAD

**Issue by dhtc** [matplotlib/matplotlib#21176]
### Bug summary

Some low ratio parts will be missed in the scatter plot using pie marker. In R, using the scatterpie package, when the ratio is low, it can still occupy some area like shown in expect outcome.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

#function to draw pie charts on map
def draw_pie(ax,X=0, Y=0, size = 15000000): 
    xy = []; s=[]
    start = 0.0 
    ratios=[0.00004]*1000 + [0.96]
    for ratio in ratios:
        x = [0] + np.cos(np.linspace(2*np.pi*start,2*np.pi*(start+ratio))).tolist() #30
        y = [0] + np.sin(np.linspace(2*np.pi*start,2*np.pi*(start+ratio))).tolist() #30

        xy1 = np.column_stack([x, y])
        s1 = np.abs(xy1).max()

        xy.append(xy1)
        s.append(s1)
        start -= ratio

    for xyi, si in zip(xy,s):
       ax.scatter([X],[Y] , marker=(xyi), s=size*si**2, edgecolor="none")

fig, ax = plt.subplots() 

X,Y=166,50 
draw_pie(ax,X, Y,size=150000)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/20806068/134764450-ce6acbaa-5f9d-48df-a28d-fe430c6fb1a1.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/20806068/134764477-b1c9b845-c80d-4815-b9e0-adaae1021f59.png)

### Operating system

Red hat

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.7

### Jupyter version

2.3.2

### Installation

conda

**Comment by jklymak** [comment]
This seems like you are asking us to debug your draw_pie function.  Can you isolate what method you do not feel is acting as documented?

**Comment by dhtc** [comment]
> This seems like you are asking us to debug your draw_pie function. Can you isolate what method you do not feel is acting as documented?

Hi, thanks for the fast response. And, you can see I have generated 1001 pieces using this code `ratios=[0.00004]*1000 + [0.96]`. And I plot them using `ax.scatter([X],[Y] , marker=(xyi), s=size*si**2, edgecolor="none")`. But it seems that the piece of 0.96 percent is drawn correctly, while those 0.0004 pieces are missed. Though every piece of those 1000 pieces accounts for a small ratio, it would be a large part when adding them up. So, could you give me some advice to fix it? Thanks in advance!

**Comment by jklymak** [comment]
User help is offered at discourse.matplotlib.org. If you isolate a bug feel free to request a reopen. I suspect your marker sizes are simply too small and don't get drawn.  It's possible this is premature optimization on our part, but I am also not sure it isn't a mistake in your code.  Please try and isolate to something simpler than your draw_pie function.  Thanks for your understanding!

**Comment by jklymak** [comment]
If you debug this, you will find you are covering your small pies with the large one.
