### ISSUE TITLE
I need both shared_xaxes = True and x-axis value display

### ISSUE THREAD

**Issue by kurikabocya** [matplotlib/matplotlib#21170]
### Problem

I need both shared_xaxes = True and x-axis value display
My web is made by make_subplots(rows=20, cols=1, shared_xaxes=True,,)
So, x-axis value is diaplayed on the bottom or 20th row **ONLY**.
This is very inconvinient.
But the 'shared_xaxes = True' is mandatory for our purpose.

### Proposed solution

When shared_xaxes = True,
please show axis value on each every row!!!

**Comment by jklymak** [comment]
Please report to plotly directly.  Thanks.
