### ISSUE TITLE
make_subplots and the first row is fixed and not scrollable

### ISSUE THREAD

**Issue by kurikabocya** [matplotlib/matplotlib#21173]
### Problem

My make_subpltos is below
   fig = make_subplots(
        rows=chartCount,  <-- 20 rows
        cols=1,
        shared_xaxes=True,
        subplot_titles=chart,
        row_heights=my_row_heights,
        vertical_spacing=my_vertical_spacing,
        specs=my_specs
    )

The first row is special and must be references always.
The other rows  must be scrolled.

Currently, this cannot be possible.
So, I put two of the same figure on web.
This is very cubersome.

So, please add fix row feature.

**Comment by jklymak** [comment]
I think you have us confused with plotly.  https://plotly.com/python-api-reference/generated/plotly.subplots.make_subplots.html. Please report to them. Thanks.
