### ISSUE TITLE
[Doc]: The main site lacks of GTK4 backend documentation

### ISSUE THREAD

**Issue by rivanfebrian123** [matplotlib/matplotlib#21185]
### Documentation Link

https://matplotlib.org/stable/search.html?q=gtk4#

### Problem

Currently, the main site only provides GTK3 backend documentation (and tutorials). Since GTK4 backend is now supported, it should also be documented

### Suggested improvement

Some better and more comprehensive tutorials are also needed for this backend

### Matplotlib Version

Not applicable

### Matplotlib documentation version

3.4.3

**Comment by anntzer** [comment]
This is because gtk4 is only supported by not-yet-released versions: https://matplotlib.org/devdocs/search.html?q=gtk4.
