### ISSUE TITLE
[Bug]: pip._internal.exceptions.DistributionNotFound: No matching distribution found for matplotlib

### ISSUE THREAD

**Issue by ManPython** [matplotlib/matplotlib#21214]
### Bug summary

I see, that matplotlib not supporting well the installation version 
`'pip install matplotlib==3.4.1`
https://stackoverflow.com/questions/66932479/how-do-i-install-matplotlib-3-4-1-in-anaconda#comment122478587_66932922

### Code for reproduction

```python
`'pip install matplotlib==3.4.1`
```

### Actual outcome

pip._internal.exceptions.DistributionNotFound: No matching distribution found for matplotlib

### Expected outcome

Installed

### Matplotlib Version

3.4.2

### Installation

pip

**Comment by tacaswell** [comment]
There is not enough information here to help you.  Please fill in all of the requested in formation (os,python version, etc) and ping to have this re-opened.
