### ISSUE TITLE
horizontal line in SVG not visible in Chrome, but visible in IE and Illustrator.

### ISSUE THREAD

**Issue by alias-neo** [matplotlib/matplotlib#2124]
See discussion here:
http://stackoverflow.com/questions/16999586/matplotlib-wont-plot-line-of-same-x-values/17000144?noredirect=1#comment24658630_17000144

If a graph is generated with a single horizontal line, the line is not visible in Chrome, but it is in Illustrator and in Internet Explorer.

As soon as the line stops being "straight" it becomes visible. This is not a reproduction of the vertical/horizontal issue with zoom/refresh.

**Comment by cwtuan** [comment]
fix:
```
<line
  x1="10" y1="1"
  x2="90" y2="1.0001" // hack: horizontal line in SVG not visible in Chrome
  stroke="#FF0000"
  strokeWidth="1"/>
 
```

Ref: http://code.tonytuan.org/2016/09/svg-horizontal-line-not-visible-in.html

**Comment by tacaswell** [comment]
@cwtuan That is not really a great fix, the issues is a bug in the renderer.

**Comment by shaundavin13** [comment]
DO NOT FEAR! I HAVE FOUND THE SOLUTION! The reason it's not rendering is because the containing SVG element has 0 height!!! Just put svg {min-height: 1px;} in your global CSS and it will fix the issue. 

*takes a bow*

**Comment by juanitoddd** [comment]
I have the same problem, Chrome & Firefox do not render horizontal lines using a mask, Edge does
I am going with @cwtuan solution, by adding `0.001 px` to one of the Y properties.
Ugly but it works

**Comment by mwiedeV1** [comment]
> I have the same problem, Chrome & Firefox do not render horizontal lines using a mask, Edge does I am going with [@cwtuan](https://github.com/cwtuan) solution, by adding `0.001 px` to one of the Y properties. Ugly but it works

It depends on lineGradient element.
If a vertical lineGradient is assigned for filling and the line has y1 equal to y2 then the line is not shown, because there is no height for gradient.
Use fill="#xxxxxx" instead of fill="url(#gradient)"
