### ISSUE TITLE
Bug showing blank graphs with SDR

### ISSUE THREAD

**Issue by alexxmarsh44** [matplotlib/matplotlib#21243]
plt.psd(samples) shows a blank graph.  This is a fresh linux debian install with code that normally works with matplotlib.

Matplotlib Version
3.4.3
Platform Python Version
3.7.3

Code Snippit:

```
import uhd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import sys
print(matplotlib.__version__)
import platform
print(platform.python_version())
import matplotlib.animation as animation
#matplotlib.use('TkAgg')
np.set_printoptions(threshold=sys.maxsize)

usrp = uhd.usrp.MultiUSRP()
samples = usrp.recv_num_samps(10000, 100e6, 1e6, [0], 100)
print(samples[0:10])

fig = plt.figure()
ax1 = fig.add_subplot(1, 1, 1)

def animate(i):
    #ax1.clear()
    #samples = usrp.recv_num_samps(10000, 100e6, 1e6, [0], 100)
    #fft1 = np.fft.fft(samples)
    #plt.ylim(-10, 10)
    #plt.plot(samples, marker="o")
    #plt.show()
    ax1.psd(samples[0:10])

    #plt.show(block=False)
    #plt.pause(00.01)


ani = animation.FuncAnimation(fig, animate, interval=1)
plt.show()
```

expected outcome:

A power spectrum density graph from the software defined radio.

Actual outcome:

![Screenshot_2021-09-30_21-53-04](https://user-images.githubusercontent.com/59932969/135567880-0d3034b3-c329-4871-b8f1-8adb49678eac.png)

**Comment by jklymak** [comment]
We can't help you without access to the data.  Try without animating and then check your data stream.  If this really worked with previous matplotlibs it would be helpful for you to test with that version and tell us what that was.

**Comment by alexxmarsh44** [comment]
It is just a stream that outputs IQ data in the form of a numpy array consisting of complex numbers.

Here is a portion of the data it's actually 10000 complex numbers long.

`[[1.82958424e-01+7.32444040e-03j  7.66014382e-02+6.34784857e-03j
  -2.34076921e-02+4.53504957e-02j -1.17191048e-02+2.39265058e-02j
   4.92873825e-02+8.09655860e-02j  4.09863479e-02+1.11270458e-01j
   3.38755385e-03+1.38065711e-01j  7.22067729e-02+3.65916826e-02j"
   1.37119636e-01+1.99896190e-02j  4.53504957e-02-8.75881035e-03j
  -4.85244207e-03+1.85247306e-02j  5.70695996e-02+2.14545075e-02j
  -9.07620266e-02+4.78224941e-02j  4.88296035e-04+6.29291534e-02j]]`

It is a software defined radio.  The version it worked with is this identical version of everything including the os.  I reformatted my harddrive and am in the process of rebuilding and here I am unable to see a graph after relying heavily on matplotlib for my software development prior to this.  All of my scripts are works in progress that worked before so the script hasn't changed.

I cannot use that working version as it was my corrupted harddrive install.  I back all of my data up though so I have all the scripts and I thought I had all of the software as I installed everything from either pip or apt install.

**Comment by timhoffm** [comment]
When feeding your data sample into the posted code, I get a working plot:

![grafik](https://user-images.githubusercontent.com/2836374/135688300-a821cdf9-910c-42a6-8069-9a8119807067.png)

Please drill down your problem to a self-contained repoducible example. Otherwise we cannot inspect and analyse the issue.

**Comment by alexxmarsh44** [comment]
I am using matplotlib on now an arch linux build and the problem is obviously reproducible as it happens on another distro.

`[[ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.99633753+0.998779j    0.87582   +0.44743177j
   0.8167972 -0.99929786j -0.8709675 -0.90459895j -0.9631639 -0.99929786j
  -0.99441487-0.4664753j  -0.83141553+0.9988095j   0.79580045+0.74846625j
   0.9231542 +0.998779j    0.8992582 -0.08050781j  0.9060638 -0.99926734j
   0.90511775-0.8417003j   0.9158297 -0.99926734j  0.12878808-0.5977354j
  -0.6167484 +0.84948254j -0.66063404+0.9148837j   0.37763596+0.82409114j
   0.76409173+0.9939266j   0.74166065+0.43522435j -0.5679799 -0.99929786j
  -0.99243116-0.9412211j  -0.8977933 -0.9007231j   0.52888566+0.46595648j
   0.9441509 +0.6211431j   0.88998055+0.998779j    0.8524123 -0.04635761j
  -0.7880182 -0.99926734j -0.99929786-0.9207432j  -0.9509565 -0.94219774j
  -0.9300208 +0.79094803j  0.68993175+0.83141553j  0.97097665+0.998779j
   0.8514357 +0.24982446j  0.9890131 -0.99929786j -0.3830072 -0.8772849j
  -0.99929786-0.99929786j -0.7914363 -0.7548141j  -0.99926734+0.8026366j
   0.09073151+0.89825106j  0.9988095 +0.8826561j   0.88802737+0.8626665j
   0.8772849 +0.94756895j  0.966582  -0.24887839j -0.63039017-0.99926734j
  -0.9939266 -0.27619246j -0.99929786+0.92364246j  0.09271521+0.886593j
   0.998779  +0.8592179j   0.7211522 +0.87145585j -0.23908195-0.7953427j
  -0.9309669 -0.9817192j  -0.9363382 -0.8738668j   0.5796379 -0.45768598j
   0.9988095 -0.00830103j  0.8260443 +0.10586868j  0.98559505-0.08001951j
   0.7040924 -0.5655078j  -0.84658325-0.8485059j  -0.99926734-0.9651476j
  -0.9300208 -0.78948313j -0.9792777 -0.4640033j   0.33277375+0.15515606j
   0.9441509 -0.05465864j  0.8850976 -0.2356944j   0.9070404 -0.22101499j
   0.92413074+0.35813463j  0.76213855-0.99929786j -0.8958401 -0.49232447j
  -0.9631639 +0.14590895j -0.9563583 +0.8045898j   0.6162601 +0.9021574j
   0.998779  +0.84557617j  0.8158206 +0.9909968j   0.998779  -0.07565536j
  -0.05075227-0.99926734j -0.99926734-0.777764j   -0.7850885 -0.99929786j
  -0.99929786+0.27420875j -0.10831016+0.96902347j  0.998779  +0.86803776j
   0.88119125+0.8621477j   0.8787497 +0.9485456j   0.9988095 -0.48454225j
   0.3478804 -0.99926734j -0.99929786-0.8758505j  -0.8738668 -0.99926734j
  -0.969054  -0.01074251j  0.42695385+0.9895014j   0.6664936 +0.6064942j
   0.9988095 +0.4454786j ]]`

Theres the full data example and blank plot.
![alexx1](https://user-images.githubusercontent.com/59932969/135693907-07a604b2-55fe-4732-88e1-378838f020cc.png)

**Comment by alexxmarsh44** [comment]
Are you sure it working is reporoducable?  Example can you give me what distro your using and how you install matplotlib and python so I can reproduce it working on my machine?

**Comment by jklymak** [comment]
Just printing numbers is not a self-contained reproducible example.  Please make a complete and self contained reproducible example that only uses matplotlib and numpy (no uhd, or other modules) , and we can reopen if the problem is matplotlib.
