### ISSUE TITLE
[ENH]: implement stackplot as pcolormesh (quadmesh) to avoid seams

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#21257]
### Problem

When using stackplot, the patches are drawn as individual artists. When rendering those one by one, the patches are anti-aliased against the white background, creating shine-through seams between the patches. This is a known problem, see https://github.com/matplotlib/matplotlib/issues/21255 and the links therein.

```python
import matplotlib.pyplot as plt

x = [0, 1]
y1 = [0.5, 0.6]
y2 = [0.5, 0.4]
plt.stackplot(x, y1, y2, colors=["tab:blue", "tab:purple"])

plt.savefig("out.png")
```
![out](https://user-images.githubusercontent.com/181628/135670001-9b2125f4-6773-4912-8fc8-677d2762d2ec.png)

Zoom:
![screenshot](https://user-images.githubusercontent.com/181628/135670093-8e56e959-bd4f-4052-b7b0-ae2e4a38a101.png)

### Proposed solution

To get rid of the seams, we have to give the renderer the opportunity to know the neighboring patches. One possibility that fits the stackplot use case well is [pcolormesh](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pcolormesh.html). (Note that all sections in a stackplot are stacked quads.)

An MWE:
```python
import matplotlib.colors
import matplotlib.pyplot as plt

X = [
    [0.0, 1.0],
    [0.0, 1.0],
    [0.0, 1.0],
]
Y = [
    [0.0, 0.0],
    [0.4, 0.6],
    [1.0, 1.0],
]

# color specification is a bit clumsy
cmap = matplotlib.colors.ListedColormap(["tab:blue", "tab:purple"])
C = [[0], [1]]
plt.pcolormesh(X, Y, C, cmap=cmap)

# plt.show()
plt.savefig("out.png")
```
![out](https://user-images.githubusercontent.com/181628/135670360-c9420815-33ea-46a2-b0a9-a0bc4c86f39a.png)

![screenshot](https://user-images.githubusercontent.com/181628/135670421-21ed4cce-9b40-4b22-911b-94ae85b1624a.png)

Not antialiasing here, but it's arguably better than the background leaks.

**Comment by anntzer** [comment]
You could also just pass `antialiased=False` to stackplot if you are willing to give up on antialiasing.

**Comment by nschloe** [comment]
True, the result is the same. I guess this would only make sense if pcolormesh would antialiase. Why doesn't it, even if `antialiased=True` is given?

**Comment by anntzer** [comment]
Likely because our implementation of quadmesh doesn't actually do it...  Probably needs some work, related to https://github.com/matplotlib/matplotlib/issues/5694#issuecomment-168465122 / https://discourse.matplotlib.org/t/flash-rendering-in-the-agg-backend/17768.

**Comment by nschloe** [comment]
I asked myself of SVG renderers deal with adjacent polygons, and it turns out, they don't; see [this stackoverflow question](https://stackoverflow.com/q/47451435/353337) on the following shape with a white see-through line between the triangles:

![f](https://user-images.githubusercontent.com/181628/135689969-5bb5098c-7f88-4438-b650-384e1e5ee43c.png)

In SVG, you can add `shape-rendering="crispEdges"` to get the same effect as `antialiased=False` in mpl: No background shimmers, but jagged lines. Considering the fact that one has to choose between those two things in SVG, I'd be hard-pressed to expect more from mpl. Closing.
