### ISSUE TITLE
[Bug]: suboptimal color interpolation

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#21255]
### Bug summary

Sometimes, when two blocks of color sit next to each other, the PNG save will interpolate between the colors incorrectly, leading to a visible "seam" between the areas.

### Code for reproduction

```python
import matplotlib.pyplot as plt

x = [0, 1]
y1 = [0.5, 0.55]
y2 = [0.5, 0.45]

plt.stackplot(x, y1, y2, colors=["tab:blue", "tab:purple"])
# plt.gca().set_facecolor("k") 

plt.savefig("out.png")
```

### Actual outcome

![out](https://user-images.githubusercontent.com/181628/135659761-4d949039-6c1a-41ab-ac4d-2269ab82dc13.png)

Zoom:

![screenshot](https://user-images.githubusercontent.com/181628/135659884-44345a13-17fd-4113-b918-0f74041fa18d.png)

With a black background:

![screenshot](https://user-images.githubusercontent.com/181628/135663067-049db29b-efaa-42e0-a6f2-546ef69179fe.png)

### Expected outcome

As @timhoffm points out, the artists antialias against the background, not against their neighbors, leading to this funny behavior.

**Comment by timhoffm** [comment]
The two color patches belong to different artists. I suppose the effect is that they are individually antialiased against the white background because they do not know that their edges coincide.

But there are other people here that have a better understanding of this.

**Comment by nschloe** [comment]
You're right. I've tested it against a black background, and indeed the seam is dark.

**Comment by anntzer** [comment]
This is basically the same as https://github.com/matplotlib/matplotlib/issues/5694 (see also https://github.com/matplotlib/matplotlib/issues/9574), AFAICT.
