### ISSUE TITLE
[Bug]: broken minor ticks for colorbar with SymlogNorm

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#21258]
### Bug summary

This bug has been with us for a few months in yt, though only reported a couple days ago https://github.com/yt-project/yt/issues/3535

I finally decided to track it down and discovered it only occurred since matplotlib 3.2.0 came out.
The breaking change bisects down to
- https://github.com/matplotlib/matplotlib/commit/dc51a68352fd5f1a209c55f2ffb7bdc6f7728159
- https://github.com/matplotlib/matplotlib/pull/13506

here's a pure matplotlib script that reproduce the problematic behaviour seen in yt

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import SymLogNorm

prng = np.random.RandomState(0)
data = prng.random_sample((100, 100)) - 0.5
VMIN = -0.5
VMAX = 0.5
LINTHRESH = 1e-2

fig, ax = plt.subplots()

NORM = SymLogNorm(linthresh=LINTHRESH, vmin=VMIN, vmax=VMAX)
im = ax.imshow(data, norm=NORM)

cax = fig.add_axes([0.8, 0.1, 0.02, 0.8])
cb = fig.colorbar(im, cax=cax)

ticks = [
    -0.5, -0.4, -0.3, -0.2, -0.1,
    -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01,
    0.0,
    0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09,
    0.1, 0.2, 0.3, 0.4, 0.5
]
mticks = NORM(ticks)
cax.yaxis.set_ticks(mticks, minor=True)

fig.savefig("/tmp/symlog_mpl.png")
```

### Actual outcome

![symlog_mpl](https://user-images.githubusercontent.com/14075922/135677417-5e6d8cfd-89b6-4f40-97b2-c25117aacfe8.png)

### Expected outcome

Here's the result of same script run with matplotlib 5c791a80ebf2d48da62a9397a6e93530ebe199c2 (last commit where this worked)
![symlog_mpl](https://user-images.githubusercontent.com/14075922/135677472-e122fdc5-1665-495e-86ef-cd99db368508.png)

### Matplotlib Version

3.2.0 to 3.4.3

### Matplotlib Backend

MacOSX

### Python version

3.9.7

**Comment by jklymak** [comment]
I don't understand why you are doing `mticks=NORM(ticks)`.  If you don't do that, and pass ticks instead of `mticks` it works fine.  If you run the ticks through the norm they end up outside [vmin, vmax] and the colorbar limits are expanded to where there is white space.

**Comment by neutrinoceros** [comment]
I tried that, and the result isn't consistent with what I obtain in matplotlib 3.1.x
![symlog_mpl](https://user-images.githubusercontent.com/14075922/135688399-24d1396f-ae1d-4566-8664-062607d59733.png)

In the context of yt, I'm looking for a way to seamlessly support matplotlib versions from 2.2 to current with minimal differences.
My current solution is to completely renounce drawing minor ticks on syslog-normed colorbars, see
https://github.com/yt-project/yt/pull/3536/files

**Comment by jklymak** [comment]
Please try that on master though.  3.5 has significant updates for colorbars.

**Comment by jklymak** [comment]
On master: 

```python
ticks = [
    -0.5, -0.4, -0.3, -0.2, -0.1,
    -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01,
    0.0,
    0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09,
    0.1, 0.2, 0.3, 0.4, 0.5
]
cax.yaxis.set_ticks(ticks, minor=True)
```

![symlogn](https://user-images.githubusercontent.com/1562854/135706807-dd330069-ebf2-4775-b46b-549c32fe4314.png)

**Comment by jklymak** [comment]
@neutrinoceros if the above is OK, suggest we close.   We can't go back in time and fix the old broken behaviour, but I think the new behaviour is correct.

**Comment by neutrinoceros** [comment]
Agreed. I've been testing your suggestion with matplotlib' master within yt and it seems to work fine there too, with one difference that I'm 99% sure is on the yt side of things, so I'll close here. Thank you so much for your help !

**Comment by jklymak** [comment]
No problem - these weird interactions with colorbars and their axes was why we did the colorbar overhaul for 3.5.  Basically the idea is that colorbars active axis is exactly the same as any other Matplotlib axis.
