### ISSUE TITLE
[ENH]: Point scaling for performance.

### ISSUE THREAD

**Issue by makingglitches** [matplotlib/matplotlib#21252]
### Problem

I attempt to the following very simple piece of code:

```
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt

def fn(x,y):
    return x**2+y**2+2*x**3+2*y**3

fig = plt.figure()
ax = plt.axes(projection='3d')

for x in range(100):
    for y in range (100):
        ax.scatter(x/100,y/100,fn(x,y)/fn(100,100), c=['green'])

plt.show()
```

It plots, yes 100^2 points. But this doesn't seem to be something that should take several minutes to complete, and when the viewer does appear its acting like its trying to update a view off all 10,000 of them. 

Anyway it takes several minutes to run and when it finally displays the viewer lags and is unusuable.

### Proposed solution

Perhaps there is a way to create a viewport and determine what the general shape is for far away views, and limit what is seen when zoomed in ?

I know there has to be some way of this.

Example:

QGIS can view 20 GB file sectionally, and supports zooming out to view a very large surface which accounts for the whole dataset.

Thanks so much.

**Comment by anntzer** [comment]
You need to vectorize your plotting, e.g.
```python
xs = np.arange(100)
ys = np.arange(100)
ax.scatter(xs/100,ys/100,fn(xs,ys)/fn(100,100), c=['green'])
```

Although there are some mplot3d-specific plotting issues, this is not one of them; making a plot with 1e4 separate artists will always be slow, and the benefits of vectorization are standard in the numpy ecosystem.  Thus, closing.
