### ISSUE TITLE
[Bug] 3.4.3: sphinx 4.2.0 warnings

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#21272]
### Bug summary

Looks like `matplotlib` documentation is not ready for sphinx 4.2.0 and during generate documentation is emited +730 warnings.

### Code for reproduction

```python
PYTHONPATH=$PWD/build/$(cd build; ls -1d lib*) MATPLOTLIBRC=$PWD/doc/ \
/usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
```

### Actual outcome

Full log is in attacment
[python-matplotlib.sphinx.txt](https://github.com/matplotlib/matplotlib/files/7274514/python-matplotlib.sphinx.txt)

### Expected outcome

No errors or wanrings.

### Operating system

Linux/x86_64

### Matplotlib Version

3.4.3

### Python version

3.8.12

### Installation

source

**Comment by tacaswell** [comment]
https://app.circleci.com/pipelines/github/matplotlib/matplotlib/12082/workflows/c629669e-4eb7-4149-8f85-e01c25dcf148/jobs/64025 is building with no warnings on sphinx 4.2.  

Please try building the docs using the documented method of the included makefile: https://matplotlib.org/stable/devel/documenting_mpl.html#building-the-docs

**Comment by kloczek** [comment]
1) Issue only is that your method is not working
```console
/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/doc
[tkloczko@barrel doc]$ make man
Running Sphinx v4.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/doc/conf.py", line 19, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

make: *** [Makefile:33: man] Error 2
```
2) Method in this case is not relevant because generally  setuptools<>sphinx integration is correctly implemented in `matplotlib`. Using that integration is only handy way of building that documentation without care where copy.py file actually is.
3) In the documentation build log is only part about reading input files and there is no even single line about documentation rendering
4) As you may see I'm building roff man pages because this is still most popular/frequently/commonly used U*nix documentation format. Please try to reproduce what I'm doing instead just replying ItWorksForMe™️. You need html as you want to publish that documentation to provide it online. I'm building man page because I need to package that as rpm and Solaris IPS package.

**Comment by jklymak** [comment]
If you are not going to follow our build instructions, then you will have to muddle through as best you can via your own methods.  If you come up with a more general way to do things that will work universally, definitely feel welcome to propose a PR.  However, given that this indeed "Works for us" I'm going to close this.

**Comment by kloczek** [comment]
Moment where I did not followed build procedure?
