### ISSUE TITLE
legend.get_window_extent() fails

### ISSUE THREAD

**Issue by durack1** [matplotlib/matplotlib#21285]
### Bug summary

It seems a bug has crept in with `points_to_pixels` not available as a function called by `get_window_extent`

### Code for reproduction

```python
(Pdb) leg2 = plt.legend(loc='upper left', ncol=2, fontsize=8)
(Pdb) leg2.get_window_extent()
*** AttributeError: 'NoneType' object has no attribute 'points_to_pixels'
(Pdb) print(matplotlib.__version__)
3.4.2
(Pdb) print(matplotlib.get_backend())
MacOSX
(Pdb) import sys; print(sys.version_info)
sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)
$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.1
ipython          : 7.25.0
ipykernel        : 6.0.1
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

### Actual outcome

Error, as above

### Expected outcome

I expected to get coords

### Operating system

MacOS 11.6

### Matplotlib Version

3.4.2

### Matplotlib Backend

MacOSX

### Python version

3.9.6

### Jupyter version

core 4.7.1; notebook 6.4.0

### Installation

conda

### Conda channel

conda-forge

**Comment by QuLogic** [comment]
I believe this was fixed by #22745.
