### ISSUE TITLE
[Bug]: minor grids only shown if major ticks exist

### ISSUE THREAD

**Issue by tomicapretto** [matplotlib/matplotlib#21323]
### Bug summary

Grid for minor ticks are not plotted unless you also include major ticks

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.plot([1, 2], [1, 2])
ax.set_xticks([1, 1.2, 1.4, 1.6, 1.8, 2], minor=True)
ax.xaxis.grid(which="minor")
```

### Actual outcome

![image](https://user-images.githubusercontent.com/25507629/136640278-15b1a33f-5b3f-4a17-beea-bacb66dad6e2.png)

### Expected outcome

Expected grid lines for minor ticks to appear. 

If you do the following (add major ticks as well as minor ticks), then grid lines for minor ticks appear

```python
fig, ax = plt.subplots()

ax.plot([1, 2], [1, 2])
ax.set_xticks([1, 1.2, 1.4, 1.6, 1.8, 2], minor=True)
ax.set_xticks([1.5], minor=False)
ax.xaxis.grid(which="minor")
```

![image](https://user-images.githubusercontent.com/25507629/136640345-273b87ff-2598-41eb-bbce-62a7387443af.png)

On the other hand, also note that if minor ticks share some values with major ticks, these are not drawn. For example:

```python
fig, ax = plt.subplots()

ax.plot([1, 2], [1, 2])
ax.set_xticks([1, 1.2, 1.4, 1.5, 1.6, 1.8, 2], minor=True)
ax.set_xticks([1, 1.5, 2], minor=False)
ax.xaxis.grid(which="minor")
```

![image](https://user-images.githubusercontent.com/25507629/136640399-1de359dc-606a-41e4-86c4-a47a373fa246.png)

Which does not draw the grid lines at 1, 1.5, and 2 

I don't know if this is a bug, or simply behavior I wasn't expecting.

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.4.2

### Installation

pip

**Comment by jklymak** [comment]
I think its true we don't have the ability to draw minor grids without major grids.  I think not too many folks want one without the other.  However, I'm not off the top of my head understanding _why_ its not being drawn.

**Comment by tomicapretto** [comment]
This was my use case:

![image](https://user-images.githubusercontent.com/25507629/136673657-f3d8bb52-b8b5-4cd2-a63e-1be3c4828156.png)

For the x-axis, my original plan was to have `[-3, -2, -1, 0, 1, 2, 3]` as the minor ticks, showing the grid, and `[-2, 0, 2]` as the major ticks, not showing the grid. In the end, I did:

```python
ax.set_xticks([-2, 0, 2], minor=False)
ax.set_xticks([-3, -1, 1, 3], minor=True)
ax.xaxis.grid(True, which="both")
```

which worked as expected.

I'm not familiar with Matplotlib internals, but if there's something I can do to help on this issue, please count on me.

**Comment by tomicapretto** [comment]
What do you mean by "do the reverse"?

**Comment by StefRe** [comment]
If you add `ax.xaxis.remove_overlapping_locs = False` the grid lines are drawn:

```
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.plot([1, 2], [1, 2])
ax.set_xticks([1, 1.2, 1.4, 1.6, 1.8, 2], minor=True)
ax.xaxis.remove_overlapping_locs = False
ax.xaxis.grid(which="minor")
```
![grafik](https://user-images.githubusercontent.com/19879328/178949701-7d389411-2909-40ef-82ad-bd532788c9c8.png)

Maybe there should be a note about it in the docs for `grid`.

**Comment by StefRe** [comment]
So this is not a bug but intended behavior, which admittedly is not very easy to find in the docs. I think it's worth to add a note about the suppression of major tick lines if they coincide with minor tick locations in the docs of [`grid`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.grid.html) with a reference to [`remove_overlapping_locs`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axis.Axis.remove_overlapping_locs.html).

**Comment by StefRe** [comment]
@tomicapretto You may close it or leave it open if you think there should be a note about it in the docs (see https://github.com/matplotlib/matplotlib/issues/21323#issuecomment-1184232317).

**Comment by tomicapretto** [comment]
Let's close this one because it is not a bug. It would be more appropriate to open another issue asking to update the documentation with a mention to this behavior.

Thanks again for the clarification!
