### ISSUE TITLE
negative polar values

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#2133]
A issue raised in this (http://stackoverflow.com/questions/17154006/pyplot-polar-scatter-plot-color-for-sign) SO question, the way that polar plots handles negative numbers changed between 1.2.0 and 1.2.1.

If this is an un-intentional change, should probably be fixed before 1.3.0.

maybe related to #1603

**Comment by Shooter23** [comment]
https://en.wikipedia.org/wiki/Polar_coordinate_system

Under "Uniqueness of polar coordinates":

"Similarly, any polar coordinate is identical to the coordinate with the negative radial component and the opposite direction (adding 180° to the polar angle)."

This suggests that the original behavior was correct.

**Comment by timhoffm** [comment]
That is true if you really want to plot polar coordinates (which also implies you always have to start from 0 radius in the center). Even though the projection is called 'polar', this radial plot has a broader scope in which negative values may actually exist at certain angles and are not equivalent to the absolute value rotated by 180 degrees.
