### ISSUE TITLE
MatPlotLib Figure Freezing on Windows 

### ISSUE THREAD

**Issue by dmikkili** [matplotlib/matplotlib#2134]
Python version: 2.7; Windows version: 7; Matplotlib version 1.2.1

I'm making an interactive plot (set with `plt.ion()`) while some other parts of my script do some calculations, and I update the plot frequently with calls to `plt.draw()`. I noticed that when I click the figure window of the interactively drawn plot and try to move it around, the figure stops updating and Windows tags the process "Not Responding", but the script continues to run without a problem. If I don't click the figure window, everything is ok. 

I've read that some people have had this issue before [on other forums](http://wxpython-users.1045709.n5.nabble.com/matplotlib-amp-wxPython-question-td2358678.html) and they got around the problem by using different backends, but my computer doesn't respond differently to other backends. What can I do?

**Comment by keonkim** [comment]
for anyone find this link on google, (which i did) 
http://stackoverflow.com/questions/3441874/matplotlib-animation-either-freezes-after-a-few-frames-or-just-doesnt-work

above link will help
