### ISSUE TITLE
[ENH]: Allow setting include/libs etc for FreeType and other dependencies

### ISSUE THREAD

**Issue by fanselm** [matplotlib/matplotlib#21366]
### Problem

I am trying to create a Conan package for Matplotlib as we need strict control over every package and their dependencies for a shipped product.

I have now spent two days trying to wrangle Matplotlib's `setup.py` into using the version of FreeType that we provide through Conan, but it can only ever use either the one it downloads itself or the one it autodetects on the system. This is simply not acceptable for people that need to ship a version of matplotlib that can't depend on what machine it was built on.

### Proposed solution

If one provides an automatic build script like `setup.py`, there should always be a way to bypass all this "automagic" behavior  and just provide hardcoded paths to dependencies.

One could set these in e.g. `setup.cfg`:

```
freetype_includes_dirs = /path/to/freetype/include
freetype_lib_dirs = /path/to/freetype/lib
freetype_libs = -lfreetype
```

or as arguments to setup.py

**Comment by QuLogic** [comment]
FreeType is found with pkg-config; set `PKG_CONFIG`/`PKG_CONFIG_PATH` correctly and it will find what you want. This is standard for Linux library packaging, and there's no need for something custom in Matplotlib.
