### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [matplotlib/matplotlib#21386]
### Summary

:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

### Proposed fix

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/matplotlib/lokal -name '*.py')
```

**Comment by rcomer** [comment]
Having browsed some of the [equivalent threads in other projects](https://github.com/issues?q=is%3Aissue+author%3Aelfring+archived%3Afalse+augmented+sort%3Acomments-desc+), I do not see value in keeping this one open: many maintainers got frustrated trying to engage and some (e.g. in pylint) concluded this is a bot.
