### ISSUE TITLE
[Doc]:  describe deprecation process more explicitly

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#21393]
### Documentation Link

https://matplotlib.org/devdocs/api/_api_api.html?highlight=deprecation#matplotlib._api.deprecation.warn_deprecated

### Problem

I'm deeply confused about whether `since` is the last release that has the arg or the first release without it. It's documented as `The release at which this API became deprecated.` which I assume is following some convention, but is not clear to me since I do not know the convention.

### Suggested improvement

Add a sentence to the since docstring (and possibly to https://matplotlib.org/devdocs/devel/contributing.html#api-changes) saying something like: the last release containing this code. I think https://docs.moodle.org/dev/Deprecation do a good job at illustrating the convention. 

Edit: as @QuLogic suggested,  don't  modify the docstring but explain the deprecation to removal process more explicitly in the API changes part of the dev guide.

### Matplotlib Version

dev

### Matplotlib documentation version

dev

**Comment by jklymak** [comment]
Its the release where the argument was first deprecated.  So if you have a PR with a 3.6 milestone, and you deprecate something you would put since='3.6'

**Comment by story645** [comment]
> Its the release where the argument was first deprecated. 

@QuLogic made the same point, but the mpl docs on deprecation don't unpack what the  'deprecation'  process is. What I'm gathering from your and Elliot's comments is that the since kwarg marks when the deprecation process was initiated for whichever arg is being deprecated.

**Comment by jklymak** [comment]
The process is that you get your instance of `warn_deprecated` into the codebase!

**Comment by anntzer** [comment]
Is https://matplotlib.org/devdocs/devel/contributing.html#api-changes not sufficient?

**Comment by sveneschlbeck** [comment]
Apart from my PR, there are two other questions concerning this (that occured to me when reading the docs):

1. In ``contributing.rst``, under the heading ``API changes``, all that's written about are Deprecations but there are other API changes apart from Deprecations, right? (e.g. Removals, Behavior Changes, etc.). I am thinking of this: https://github.com/matplotlib/matplotlib/blob/main/doc/api/next_api_changes/README.rst  

2. What linking has to be done now? This goes to @story645 specifically, since you mentioned "cross-linking"...

**Comment by timhoffm** [comment]
> all that's written about are Deprecations but there are other API changes apart from Deprecations, right? (e.g. Removals, Behavior Changes, etc.).

A deprecation is not an API change; it's a note on an upcoming API change. Deprecating an API is mandatory before changing it.

I think this whole API section is flawed and would need to be rewritten from scatch:

Audience:


Messages:
- API stability is a great value. Changing an API is a pain for the affected users. We only change an API if the benefit is larget than the pain. This is a careful decsision.
- Rules
  - Deprecations are targeted at the next point-release (i.e. 3.x.0).
  - Deprecated API may be removed two point-releases after they were deprecated.
- How to deprecate:
  - Doc announcement
  - Runtime warning (if possible)
  - If there is an alternative for the deprecated API, that should already be available during the deprecation period if possible. (I assume that's what the below point was trying to say, but got it mixed up.)
 
I think this bullet point from the existing docs is wrong:
> The deprecated API should, to the maximum extent possible, remain fully functional during the deprecation period. In cases where this is not possible, the deprecation must never make a given piece of code do something different than it was before; at least an exception should be raised.

The old API *must* remain fully functional during the deprecation period.

**Comment by sveneschlbeck** [comment]
Thanks for clarifying that, I'll look into it

**Comment by sveneschlbeck** [comment]
``made by the API constency lead developer`` What does constency mean? Do you mean consistency or something like that? @timhoffm

**Comment by timhoffm** [comment]
Yes, I meant "consistency".

**Comment by sveneschlbeck** [comment]
@timhoffm Updated the docs, hope I thought of the points you mentioned #21626
