### ISSUE TITLE
Make Cmd-W close the window using QT4 on OS X

### ISSUE THREAD

**Issue by dmcdougall** [matplotlib/matplotlib#2140]
Currently Cmd-W does nothing, and Ctrl-W closes the window.  This should be swapped to be consistent with both:  a) other backends; and b) OS X keyboard shortcuts.

Originally discussed in #1902.

**Comment by petehuang** [comment]
Can someone on OSX try to reconfirm this?

**Comment by jenshnielsen** [comment]
With QT5 the situation seems to be the same. You can close a figure with `ctrl-w` but not with `cmd-w`
