### ISSUE TITLE
"pyplot.plot_date()" is not changing the line colors using "color_cycle"

### ISSUE THREAD

**Issue by saullocastro** [matplotlib/matplotlib#2148]
Please, check this question in Stackoverflow:
http://stackoverflow.com/q/17250392/832621
 which motivated this bug report.

The OP identified that when trying to plot using `plot_date()` the colors are not changed accordingly to the `color_cycle` specified. Actually they are not changing at all.
With `plot()` it works perfectly.
I tried to change the colors from `plot_date()` using:
`plt.rc('axes', **{'color_cycle':['r', 'g']})`
`plt.rcParams['axes.color_cycle']=['r','g']`
and
setting the matplotlibrc file to the local folder with `axes.color_cycle : r, g`.

they all did not work.

thank you very much and congratulations for the great package which Matploblib already is!
Saullo Castro

**Comment by omkarkulkarni** [comment]
fmt is for the shape, what can we use for size. 
I tried with m or ms or s but all throw error.
