### ISSUE TITLE
[Bug]: color blocking with imshow, interpolation="nearest" or "none"

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#21499]
### Bug summary

I use matplotlib's `imshow` and `"nearest"` interpolation to display some colorful images. They look alright on screen, but when decreasing the window size, or when storing it as a PNG or SVG, some weird color blocking artifacts appear.

### Code for reproduction

With this image:

![cplot](https://user-images.githubusercontent.com/181628/139452564-cc269ec9-b853-4ff5-9cb9-4a0390c4e30e.png)

and this code:

```python
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

img = mpimg.imread("cplot.png")

imgplot = plt.imshow(
    img,
    interpolation="nearest",  # or "none"
)
plt.savefig("out.png")
plt.show()
```

### Actual outcome

When looked at on screen: :heavy_check_mark: 

![full](https://user-images.githubusercontent.com/181628/139452642-e1b27c93-aee3-4d7c-9715-8d5433df8a73.png)

When decreasing window size Color blocking :x: 

![small](https://user-images.githubusercontent.com/181628/139452674-de22c4ad-4acc-4e00-aebe-f78eebac4b91.png)

When storing as PNG: Color blocking :x: 

![out](https://user-images.githubusercontent.com/181628/139452778-59a13f58-4094-4433-a888-574dff2276c8.png)

### Expected outcome

Everything as in full display mode.

### Operating system

Ubuntu

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg

### Python version

3.9.7

### Installation

pip

**Comment by timhoffm** [comment]
@nschloe is there something we have to do on the matplotlib side? If so, please provide a minimal example. Otherwise we should close this
