### ISSUE TITLE
[Bug]: Text sometimes is missing when figure saved to EPS

### ISSUE THREAD

**Issue by uranix** [matplotlib/matplotlib#21509]
### Bug summary

I'm using cartopy to render data in polar projection. After an update I noticed that labels and title is not anymore rendered in saved eps file, though it was rendered in Jupyter notebook. I managed to simplify the code and found that matplotlib=3.3.4 does not suffer from the problem, while matplotlib=3.4.3 does.

The testing environment was obtained by calls
```
conda create -c conda-forge -n mpl-3.3.4 matplotlib=3.3.4 cartopy=0.18.0 python=3.7
conda create -c conda-forge -n mpl-3.4.3 matplotlib=3.4.3 cartopy=0.18.0 python=3.7
```

Might be related to #20364

### Code for reproduction

```python
#!/usr/bin/env python
# coding: utf-8

import matplotlib.pyplot as plt
import cartopy.crs as ccrs 
import matplotlib.ticker as mticker

def test(spacing, name):
    m = ccrs.NorthPolarStereo(central_longitude=0)
    plt.figure(figsize=(13, 13))
    plt.rc('font', size=16)
    ax = plt.axes(projection=m)
    plt.title('>>> do you see me <<<')
    ax.set_extent((-180, 180, 15, 90), crs=ccrs.PlateCarree())
    gl = ax.gridlines(draw_labels=False)
    gl.xlocator = mticker.FixedLocator(range(-180, 180, spacing))
    plt.savefig(name, bbox_inches='tight')
    
test(40, '/tmp/good.eps')
test(30, '/tmp/bad.eps')
```

### Actual outcome

An eps file with no `>>> do you see me <<<` message. (matplotlib v3.4.3)

![image](https://user-images.githubusercontent.com/1182947/139561361-6774c7fe-045b-4a53-bb5c-91227ed6c154.png)

### Expected outcome

An eps file with `>>> do you see me <<<` message. (matplotlib v3.3.4)

![image](https://user-images.githubusercontent.com/1182947/139561379-69844d05-aade-4e11-96ad-b12b3196cc63.png)

### Operating system

Debian GNU/Linux bookworm, Linux Mint 20.2 Uma

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.7.12

### Jupyter version

not used

### Other libraries

cartopy=0.18.0

### Installation

conda

### Conda channel

conda-forge

**Comment by anntzer** [comment]
I can't easily test with cartopy 0.18.0 right now, but at least with 0.20, I cannot repro the issue.

**Comment by uranix** [comment]
Unfortunately also reproduces with cartopy 0.20.0 on my machine

**Comment by anntzer** [comment]
Perhaps try attaching the eps file, so that we can check whether it's a problem on the viewer side?

**Comment by uranix** [comment]
The `mpl_3.4.3_bad.eps` is the only one without text rendered, the others are for reference

[results.zip](https://github.com/matplotlib/matplotlib/files/7452818/results.zip)

**Comment by anntzer** [comment]
Thanks, at least I can see that your files do fail to render properly on my side too.

**Comment by uranix** [comment]
Please let me know if I could gather some more debug information, maybe some intermediate representation.

**Comment by anntzer** [comment]
Probably the most helpful would be a repro without cartopy.

**Comment by uranix** [comment]
I think I've found the bug. The produced eps file has a number of shortcuts like `m` for `moveto`, `l` for `lineto` and (important) `ce` for `closepath eofill`.

When a clip path is defined in eps file it is also defined so can be reused later. It looks like
```(postscript)
/c1 {
721.386016 727.92 m
721.386016 7.2 l
7.2 7.2 l
7.2 727.92 l
721.386016 727.92 l

clip
newpath
} bind def
```
Well in my case this paths are not reused and the same path is defined again and again with names `c1`, `c2`, ..., `c9`, `ca`, `cb`, ..., and eventually `ce`.
So in fact the clip command shadows the closepath command and the rest of the document is screwed.

Well I see two problems here:
1. Obvious name clash that causes the bug
2. Redefinition of a same path again and again

Also I've played a bit with the script and noticed that eps output is not stable: that clipping paths are sometimes reused and sometimes are not. Everything else seems to be consistent (except for the header). I wrote a loop to save eps and in 7 cases of 20 the text was missing and it was present in 13 other cases.

**Comment by anntzer** [comment]
Ah, thanks, that's a great investigation!  Here's a repro without cartopy, and where one indeed needs to define many clip paths:
```python
import matplotlib.pyplot as plt
fig, axs = plt.subplots(4, 4, subplot_kw=dict(projection="polar"))
for ax in axs.flat:
    ax.set(xticks=[], yticks=[])
    ax.plot([1, 2])
fig.suptitle("hello, world")
fig.savefig("/tmp/test.eps")
plt.show()
```
Replacing (4, 4) by (4, 3) (for example) avoids defining the "ce" path and doesn't show the problem.

I guess the shortest solution is to just not generate colliding clippath names, i.e.
```patch
diff --git i/lib/matplotlib/backends/backend_ps.py w/lib/matplotlib/backends/backend_ps.py
index 35c61b08f2..8c88bfa3c7 100644
--- i/lib/matplotlib/backends/backend_ps.py
+++ w/lib/matplotlib/backends/backend_ps.py
@@ -429,7 +429,7 @@ class RendererPS(_backend_pdf_ps.RendererPDFPSBase):
             key = (path, id(trf))
             custom_clip_cmd = self._clip_paths.get(key)
             if custom_clip_cmd is None:
-                custom_clip_cmd = "c%x" % len(self._clip_paths)
+                custom_clip_cmd = "c%d" % len(self._clip_paths)
                 self._pswriter.write(f"""\
 /{custom_clip_cmd} {{
 {self._convert_path(path, trf, simplify=False)}
@@ -570,7 +570,7 @@ grestore
         path_codes = []
         for i, (path, transform) in enumerate(self._iter_collection_raw_paths(
                 master_transform, paths, all_transforms)):
-            name = 'p%x_%x' % (self._path_collection_id, i)
+            name = 'p%d_%d' % (self._path_collection_id, i)
             path_bytes = self._convert_path(path, transform, simplify=False)
             self._pswriter.write(f"""\
 /{name} {{
```
(the second change is not needed, but is for consistency).
