### ISSUE TITLE
request a new function

### ISSUE THREAD

**Issue by Raymone6290** [matplotlib/matplotlib#21503]
hello, I have a need to use matplotlib to draw a picture. I have two two-demensional arrays with same shape, and they represent two different characters, say, height and weight. now I need to draw a three-demensional picture, a surface(height) with color(weight), the final effect is like the file attached. I have thought about it for a while but I cannot figure it out, can you please provide me with some idea? thanks a lot!
![quest](https://user-images.githubusercontent.com/59287356/139519204-6e232543-d9f3-4b5f-bb1a-f26f395a40f2.jpg)

**Comment by jklymak** [comment]
Please move discussion to discourse.matplotlib.com or stackoverflow.  Thanks for your understanding!

**Comment by WeatherGod** [comment]
No need for a new function. The facecolors argument is where you'd set the
colors. See
https://matplotlib.org/stable/gallery/mplot3d/surface3d_3.html#sphx-glr-gallery-mplot3d-surface3d-3-py
for the basic idea. Would be good to include a fuller example in discourse
as Jody suggests.
