### ISSUE TITLE
[Bug]: pyright: error: "colors" is not a known member of module 

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#21505]
### Bug summary

When running
```sh
pyright --lib dummy.py
```
on
```python
import matplotlib as mpl

mpl.colors
mpl.cm
```
one gets
```sh
  /tmp/dummy.py:3:5 - error: "colors" is not a known member of module (reportGeneralTypeIssues)
  /tmp/dummy.py:4:5 - error: "cm" is not a known member of module (reportGeneralTypeIssues)
```
Other submodules are fine.

### Code for reproduction

```python
See above.
```

### Actual outcome

See above.

### Expected outcome

No errors.

### Matplotlib Version

3.4.3

### Python version

3.9.7

### Installation

pip

**Comment by anntzer** [comment]
I would call this a bug on pyright's side, not us...

**Comment by nschloe** [comment]
Moved there. https://github.com/microsoft/pyright/issues/2516
