### ISSUE TITLE
[Bug]: import matplotlib run error-ImportError: dlopen(ft2font.cpython-38-darwin.so, 0x0002):symbol not found in flat namespace '_FT_Done_Face'

### ISSUE THREAD

**Issue by kmlch-git** [matplotlib/matplotlib#21502]
### Bug summary

code:
import matplotlib

run, then report error:
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/ft2font.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_FT_Done_Face'

### Code for reproduction

```python
import matplotlib
```

### Actual outcome

/usr/local/bin/python3.8 /Users/lch/python/pythonmy/main.py
Traceback (most recent call last):
  File "/Users/lch/python/pythonmy/main.py", line 1, in <module>
    import matplotlib
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/__init__.py", line 208, in <module>
    _check_versions()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/__init__.py", line 193, in _check_versions
    from . import ft2font
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/ft2font.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_FT_Done_Face'

### Expected outcome

the code can run normally.

### Operating system

macOS 12.0.1/CPU:Apple M1 Pro

### Matplotlib Version

3.5.0rc1

### Python version

3.8.10

### Other libraries

pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.7
cycler             0.10.0
fonttools          4.27.1
idna               3.3
kiwisolver         1.3.2
matplotlib         3.5.0rc1
numpy              1.21.3
packaging          21.0
pandas             1.3.4
Pillow             8.4.0
pip                21.3.1
pyparsing          3.0.3
python-dateutil    2.8.2
pytz               2021.3
requests           2.26.0
setuptools         58.3.0
setuptools-scm     6.3.2
six                1.16.0
tomli              1.2.2
urllib3            1.26.7
wheel              0.37.0

### Installation

pip

**Comment by QuLogic** [comment]
Did you install the universal2 wheel or the arm64 wheel?

**Comment by QuLogic** [comment]
Can you also try with the latest wheels built from v3.5.x? You can find them in the [build artifacts](https://github.com/matplotlib/matplotlib/actions/workflows/cibuildwheel.yml?query=branch%3Av3.5.x).

**Comment by kmlch-git** [comment]
> Can you also try with the latest wheels built from v3.5.x? You can find them in the [build artifacts](https://github.com/matplotlib/matplotlib/actions/workflows/cibuildwheel.yml?query=branch%3Av3.5.x).

Thank you, QuLogic.
Download the lastest wheels, matplotlib-3.5.0rc2.dev110, and install the whl file, matplotlib-3.5.0rc2.dev110+g39e9fb6991-cp38-cp38-macosx_11_0_arm64.whl, then run the example, now run normally.

**Comment by kmlch-git** [comment]
The problem is resolved.

**Comment by QuLogic** [comment]
BTW, since it seems you're on Apple Silicon, can you [run the test suite](https://matplotlib.org/devdocs/devel/testing.html) and report back the results? No CI supports running Apple Silicon quickly yet.
