### ISSUE TITLE
[Doc]: Error message of validate_whiskers is not updated

### ISSUE THREAD

**Issue by yy0931** [matplotlib/matplotlib#21514]
### Documentation Link

https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/lib/matplotlib/rcsetup.py#L417

### Problem

`validate_whiskers` does not accept `"range"` but it is included in the error message.
https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/lib/matplotlib/rcsetup.py#L410-L419

Support for `boxplot.whiskers: range` was removed in [a commit one year ago](https://github.com/matplotlib/matplotlib/commit/6636090#diff-cbdeb0e4217c66c0eab3ff5027da14906cb705419722f8269bc9ccaadd2422b1L509-L523).

### Matplotlib Version

v3.5.0rc1

### Matplotlib documentation version

none

**Comment by l-e-e-l-a** [comment]
hi. would like to work on this.

**Comment by sveneschlbeck** [comment]
@l-e-e-l-a Did you already take care of this? Otherwise I would like to help

**Comment by sveneschlbeck** [comment]
@yy0931 Where/in which module is the new behavior of boxplot.whiskers defined?

**Comment by yy0931** [comment]
@sveneschlbeck

The validator of `boxplot.whiskers` is defined at this line.

https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/lib/matplotlib/rcsetup.py#L853

The line 1239 can be ignored as validate_whiskers is not a list.
https://github.com/matplotlib/matplotlib/blob/b09aad279b5dcfc49dcf43e0b064eee664ddaf68/lib/matplotlib/rcsetup.py#L1239

`rcParams` calls the validator when the value of its item is about to change.

https://github.com/matplotlib/matplotlib/blob/8ba4f2b3833a80a754ca0d52a6e2c695207de771/lib/matplotlib/__init__.py#L606-L606

https://github.com/matplotlib/matplotlib/blob/8ba4f2b3833a80a754ca0d52a6e2c695207de771/lib/matplotlib/__init__.py#L632-L636

The implementation of validate_whiskers means that:
1. Try to parse the input as `[float, float]`
2. otherwise, try to parse as float

So all you have to do is to delete `'range',`.

**Comment by sveneschlbeck** [comment]
@yy0931 Thanks a lot for the info, I appreciate the effort.

**Comment by l-e-e-l-a** [comment]
> @l-e-e-l-a Did you already take care of this? Otherwise I would like to help

@sveneschlbeck thanku for pitching in. i was a bit occupied this week and could not contribute.

**Comment by sveneschlbeck** [comment]
@l-e-e-l-a No problem :)

**Comment by sveneschlbeck** [comment]
@timhoffm It got a bit messy with the last commit containing unrelated files. Decided to go the safe way and do a clean, new PR
