### ISSUE TITLE
[Bug]: segmentation fault on plt.plot()

### ISSUE THREAD

**Issue by orrp** [matplotlib/matplotlib#21515]
### Bug summary

When calling plt.plot(), I get a segmentation fault.

### Code for reproduction

```python
import matplotlib.pyplot as plt

y = [1, 2, 3]
plt.plot(y)
plt.show()
```

### Actual outcome

segmentation fault

### Expected outcome

A simple plot

### Operating system

OS/X 11.6

### Matplotlib Version

2.2.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.7.11

### Installation

conda

### Conda channel

not sure :/

**Comment by orrp** [comment]
I'm guessing more logs / details are necessary. Please let me know how I can be of assistance.

**Comment by jklymak** [comment]
You could fill out the issue template with the most commonly needed info like what your environment is and how you installed matplotlib

**Comment by WeatherGod** [comment]
Why is the matplotlib version so old? Version 2.2.2 is from several years ago. I would first try a newer install.

**Comment by jklymak** [comment]
good catch - I dont' think 2.2.x was compatible with py3.7

**Comment by orrp** [comment]
Updating matplotlib to 3.4 made the issue go away. Thanks!
