### ISSUE TITLE
[Doc]: Little Typo on Introductory Tutorial

### ISSUE THREAD

**Issue by selormtamakloe** [matplotlib/matplotlib#21526]
### Documentation Link

https://matplotlib.org/stable/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

### Problem

<img width="572" alt="matplotlib-preferable-to-pick" src="https://user-images.githubusercontent.com/62969274/139950322-57373590-845d-4288-bd95-9b3d22182668.png">

### Suggested improvement

"Matplotlib's documentation and examples use both the OO and the pyplot approaches (which are equally powerful), and you should feel free to use either (however, it is **preferable pick** one of them and stick to it"

Should rather be **preferable to pick**

### Matplotlib Version

3.4.3

### Matplotlib documentation version

check the typo

**Comment by story645** [comment]
Totally right, would you like to put in the Pull Request? The file that needs to be edited is  https://github.com/matplotlib/matplotlib/blob/main/tutorials/introductory/usage.py

**Comment by selormtamakloe** [comment]
@story645 , I put in the Pull Request - https://github.com/matplotlib/matplotlib/pull/21535/files.
Actually my first time creating one.
Thanks for sharing the link to the file.

**Comment by QuLogic** [comment]
Closed by #21535.
