### ISSUE TITLE
[Bug]: matplotlib 3.5 crash on Python 3.11-alpha

### ISSUE THREAD

**Issue by PerchunPak** [matplotlib/matplotlib#21522]
### Bug summary

[Here](https://github.com/matplotlib/matplotlib/issues/21384#issuecomment-947033285) was said that I should use matplotlib 3.5 on Python 3.11, but it is crashing too

### Code for reproduction

```python
name: Try Python 11-alpha to install matplotlib 3.5.0

on: [push]

jobs:
  py11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11-dev
    - name: Update PIP
      run: pip install -U pip
    - name: Install matplotlib
      run: pip install -U matplotlib==3.5.0rc1
```

### Actual outcome

It is too large
https://pastebin.com/6FWZQkmR

### Expected outcome

*You can imagine this*

### Operating system

Github Actions, ubuntu-latest

### Matplotlib Version

matplotlib 3.5.0rc1

### Python version

https://github.com/actions/python-versions/releases/tag/3.11.0-alpha.1-117932

### Installation

pip

**Comment by QuLogic** [comment]
You are failing to build a working NumPy, not Matplotlib.
