### ISSUE TITLE
[Doc]: subplot_mosaic docstring should link to the tutorial

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#21532]

**Comment by sveneschlbeck** [comment]
@timhoffm Could you specify the issue for me? In what way should it "link" to the tutorial?  
Do you want a connection between the subplot_mosaic docstring in ``pyplot.py`` or ``figure.py``?

**Comment by tacaswell** [comment]
Thank you for your interest @sveneschlbeck !  The typical way we claim issues is by opening a PR addressing them.

I beleive that this is the tutorial Tim is suggesting to link to: https://matplotlib.org/stable/tutorials/provisional/mosaic.html

The pyplot docs are inherited from the figure.py docs (the `tools/boilerplate.py` script generates most of the code in pyplot) so you would update the docstring in `figure.py` and re-run boilerplate (and then commit both sets of changes).  See https://github.com/matplotlib/matplotlib/blob/f96eb636cf096310a94d82aaeabfc44d96077a9d/lib/matplotlib/axes/_axes.py#L2234-L2237 for an example of how this linking can be done.

I suggest you take a look at https://matplotlib.org/stable/devel/index.html for details about our workflow and https://matplotlib.org/stable/devel/documenting_mpl.html#documenting-matplotlib for notes about rst and how Matplotlib uses it.

**Comment by sveneschlbeck** [comment]
Thank you very much @tacaswell for your support. I'll look into it and open a PR :)

**Comment by sveneschlbeck** [comment]
@tacaswell rerunning the boilerplate script results in the following error. Any idea? Is this a mistake on my end?

Traceback (most recent call last):
  File "boilerplate.py", line 384, in <module>
    build_pyplot(pyplot_path)
  File "boilerplate.py", line 374, in build_pyplot
    pyplot.writelines(boilerplate_gen())
  File "boilerplate.py", line 319, in boilerplate_gen
    yield generate_function(name, f'Figure.{called_name}',
  File "boilerplate.py", line 142, in generate_function
    decorator = _api.deprecation.DECORATORS.get(meth)
AttributeError: module 'matplotlib._api.deprecation' has no attribute 'DECORATORS'

**Comment by timhoffm** [comment]
`pyplot.subplot_mosaic` is not auto-generated by `boilerplate.py`. You can ignore that, instead it needs manual editing as well.

@tacaswell FYI, running `boilerplate.py` is only necessary if signatures change. The docstring is automatically synchronized via the `@_copy_docstring_and_deprecators` decorator.

**Comment by tacaswell** [comment]
🐑 sorry for the misinformation, that is what I get for relying on my memory rather than checking the code!

**Comment by sveneschlbeck** [comment]
@timhoffm What do you mean by "manual editing as well"? I already added the link to the figure.py...do I need to take something else into consideration then, now that the boilerplate thing is off the table?

@tacaswell No problem, Tim was replying so fast, I had just begun to read into it :)

**Comment by sveneschlbeck** [comment]
@timhoffm Do you mean a reference to the docs as in ``figure.py`` but for ``pyplot.py``?

**Comment by tacaswell** [comment]
Yes, the docstring of `pyplot.subplot_mosaic` is not inherited like the auto-generated docstrings: https://github.com/matplotlib/matplotlib/blob/3d7dea59d99b2135ec1ce6eca08706f37c9f423e/lib/matplotlib/pyplot.py#L1444-L1519

**Comment by timhoffm** [comment]
Closed by #21546.
