### ISSUE TITLE
[Bug]: cm fontset in log scale does not use Unicode minus

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#21540]
### Bug summary

Minuses are shown as dashes when choosing the log scale, both in the exponent and in front of the actual number.

### Code for reproduction

```python
plot([-10, 10], [-10, 10])
yscale('symlog', linthresh=.1)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/2119355/140376782-5a49290b-22af-49aa-bac3-44e62afdb547.png)

### Expected outcome

Minuses should be shown as minuses and not dashes.

### Operating system

OS/X

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.1

### Jupyter version

3.2.1

### Installation

conda

**Comment by QuLogic** [comment]
This looks fine to me:
![image](https://user-images.githubusercontent.com/302469/140430353-34825867-7071-40cd-8716-72c94db6d779.png)
Maybe it's your theme?

**Comment by dstansby** [comment]
Yes, works fine for me on v3.4.3 and the following code: 
```python
from matplotlib.pyplot import *

plot([-10, 10], [-10, 10])
yscale('symlog', linthresh=.1)
show()
``

I'm going to close as not an issue as two of us have checked - @Atcold feel free to comment/re-open if you think we've missed something.

**Comment by Atcold** [comment]
Adding `style.use(['bmh'])` will show the bug.
So the theme is breaking it.

@QuLogic that didn't really look too fine to me, haha.
![image](https://user-images.githubusercontent.com/2119355/142695612-47a7290c-3c79-4938-bf88-bbdf4119a273.png)

**Comment by QuLogic** [comment]
Ah, `bmh` sets the `cm` fontset, and that doesn't appear to support the minus sign properly. Also, it doesn't seem like the Log formatters do any minus sign glyph substitution, but I may have missed it.

You can replicate this more easily by setting `mpl.rcParams['mathtext.fontset'] = 'cm'`, and if you don't mind going back to DejaVu Sans, can work around it by setting `mpl.rcParams['mathtext.fontset'] = 'dejavusans'` after setting the style.

**Comment by QuLogic** [comment]
A possible fix may be to do:
```diff
diff --git a/lib/matplotlib/ticker.py b/lib/matplotlib/ticker.py
index 6d8fa5419b..c759403bbf 100644
--- a/lib/matplotlib/ticker.py
+++ b/lib/matplotlib/ticker.py
@@ -1066,7 +1066,7 @@ class LogFormatterMathtext(LogFormatter):
         if x == 0:  # Symlog
             return r'$\mathdefault{0}$'
 
-        sign_string = '-' if x < 0 else ''
+        sign_string = self.fix_minus('-') if x < 0 else ''
         x = abs(x)
         b = self._base
 ```
though I'm not sure if this should be applied to `LogFormatter` as well (probably it should).

**Comment by anntzer** [comment]
Agreed that we should use fix_minus in as many places as possible.

**Comment by Atcold** [comment]
Thanks for going to the bottom of this.
