### ISSUE TITLE
[Bug]: plot_directive extension doesn't respect figsize

### ISSUE THREAD

**Issue by ma-sadeghi** [matplotlib/matplotlib#21541]
### Bug summary

When plotting in docstrings, the `figsize` argument doesn't get considered.

### Code for reproduction

```python
"""
.. plot::

   import matplotlib.pyplot as plt
   x = [1, 2, 3, 4]
   y = [1, 2, 3, 4]
   fig, ax = plt.subplots(figsize=(4, 4))
   ax.plot(x, y, "o-")
   plt.show()
"""
```

### Actual outcome

![image](https://user-images.githubusercontent.com/14086031/140423619-7374fb19-d887-44fa-a98a-6fc0e8ac62e1.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/14086031/140423644-35bbbaa2-c006-4191-bdae-353d9718a1ab.png)

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.4.3

### Python version

3.8.10

### Installation

conda

### Conda channel

conda-forge

**Comment by QuLogic** [comment]
This definitely works in Matplotlib docs; do you have a complete example?

**Comment by ma-sadeghi** [comment]
Thanks for your quick reply @QuLogic! I'm really sorry, I just realized that `sphinx` was rendering a cached version of the figure, I removed the `_build` folder and rebuilt the docs and everything looks fine. Thanks once again!
