### ISSUE TITLE
[Bug]: RangeSlider does not reset

### ISSUE THREAD

**Issue by PBiret** [matplotlib/matplotlib#21578]
### Bug summary

Using the reset() function for a `RangeSlider` throws a numpy error due to the default `if self.val != self.valinit:` in the `SliderBase` class in `widgets.py` comparing arrays. Suggestion is overrinding the function and using `np.array_equal` to compare `val` and `valinit`.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.widgets import RangeSlider

ax_example = plt.axes()
slider = RangeSlider(
        ax=ax_example,
        label = "example",
        valmin=0,
        valmax=10)


slider.reset()
```

### Actual outcome

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Expected outcome

None

### Operating system

windows 10

### Matplotlib Version

'3.4.3'

### Python version

'3.9.7'

### Installation

pip

**Comment by jklymak** [comment]
@ianhi I think maybe you we last working on sliders?  If you had time to take a look it would be much appreciated!

**Comment by PBiret** [comment]
Manually messing with the source file fixed the issue on my end but unfortunately I don't have time to make a clean PR with utests. Thanks for taking care of it 😄
