### ISSUE TITLE
[Bug]: Incorrect error bar on log scale

### ISSUE THREAD

**Issue by fnareoh** [matplotlib/matplotlib#21579]
### Bug summary

Thank you for the amazing work!

The issue is different from #163, the behavior is that if you try to plot a zero point (without any error) on a logscale (y) graph the error bar of the previous point is not plotting correctly, see the example where mini0 error bar is incorrect (desired behavior in mini1):
https://imgur.com/a/lP75nwU

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.axes()
ax.set_yscale("log")

ys =[7, 0]
ys2 =[1, 1]
errs =[5, 0]
xs = [0, 1]
ax.errorbar(xs, ys,fmt="o-", yerr=errs)
ax.errorbar(xs, ys2,fmt="o-")
fig.savefig('mini0.png')
fig.clear()
ax = plt.axes()
ax.set_yscale("log")
ys =[7, 1]
ax.errorbar(xs, ys,fmt="o-", yerr=errs)
ax.errorbar(xs, ys2,fmt="o-")
fig.savefig('mini1.png')
```

### Actual outcome

![mini0](https://user-images.githubusercontent.com/25690234/141095626-ddbed597-3d59-48bc-9984-af33a1c17202.png)

![mini1](https://user-images.githubusercontent.com/25690234/141095638-e44afe0c-487c-4457-857f-f0f05efb698a.png)

### Expected outcome

I expected the errorbar in mini0 for the first point to be as in mini1, not going to 0. As in my use case not plotting the point at 0 in logscale made sense I didn't expected it to impact the previous point error bar.

### Matplotlib Version

3.4.3

**Comment by jklymak** [comment]
First I found this slightly easier to see what is going on:

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2)

for nn, ax in enumerate(axs):

    if nn==0:
        ys = [7, 7, 0]
    else:
        ys = [7, 7, 0.00001]
    errs = 5
    xs = [0, 1, 2]
    ax.errorbar(xs, ys, fmt="o-", yerr=errs, ecolor='C1')
    ax.set_ylim([1e-4, 30])
    ax.set_yscale("log")
plt.show()
```

This gives: 

![Figure_1](https://user-images.githubusercontent.com/1562854/141099028-629b5c86-b532-4118-9278-7480db0a0945.png)

So note that `errorbar` tries to draw the connecting line down to 1e-81 or whatever it sets the zero to, and the blue line down to 1e-81 _covers_ the actual error bar...

Note that you get the same behaviour from 

```python
fig, ax = plt.subplots()
ax.semilogy([0, 1, 2], [7, 7, 0])
ax.set_ylim([1e-4, 30])
plt.show()
```

So I'm not sure we will change this anytime soon.  I'm not sure there is an action item here...

**Comment by fnareoh** [comment]
Hum ok I see, I would have never suspected this and didn't see anybody with the same issue! Thank you very much for the clarification!
