### ISSUE TITLE
xkcd painbow colormap

### ISSUE THREAD

**Issue by KOLANICH** [matplotlib/matplotlib#21589]
![2537: Painbow Award](https://imgs.xkcd.com/comics/painbow_award.png)

Not sure that it makes sense to include it into matplotlib, but it is obvious that if Randall used a colormap into his comics, sooner or later some xkcd fan would reverse engineer it and make available as a package. Here is a package for R: https://github.com/steveharoz/painbow , it would worth nothing to translate it into a matplotlib colormap. Again, I don't think matplotlib should be bloated with it (and other xkcd-related stuff), but as a separate optional package - why not.

**Comment by tacaswell** [comment]
I will reject any PR to add the `'painbow'` color map to Matplotlib.

If you @KOLANICH (or anyone else) want to it this as a third-party package you are more than welcome to. 

attn @1313e as someone who maintains a third-party package of colormaps.
