### ISSUE TITLE
[Doc]: `ax.voxels` links to wrong method.

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/matplotlib#21608]
### Documentation Link

https://matplotlib.org/stable/gallery/mplot3d/voxels.html

### Problem

![image](https://user-images.githubusercontent.com/44469195/141435227-e9d8a51d-d447-460f-8bdf-66399ad14379.png)
The line `ax.voxels` links here:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray

### Suggested improvement

It should link here instead:
https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.voxels

### Matplotlib Version

3.4.3

### Matplotlib documentation version

3.4.3

**Comment by jklymak** [comment]
We don't have any control over that directly, but someone should rename the `voxels` variable to not be the same as the method, and then the proper link should emerge?

**Comment by kolibril13** [comment]
I've made a pr here : #21609
