### ISSUE TITLE
[Bug]: Jupyter inline plots look blurry on high res display

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/matplotlib#21610]
### Bug summary

On an MacBook Air with resolution of 2560 x 1600 and 227 pixels per inch, Jupyter inline plots look blurry.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)
fig, ax = plt.subplots()
ax.plot(t, s)
ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
#plt.rcParams['figure.dpi'] = 150
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/44469195/141457013-376854af-a3b0-4c92-bc11-a8ddc75c8212.png)
I've tried to increase the dpi by using `plt.rcParams['figure.dpi'] = 150`

![image](https://user-images.githubusercontent.com/44469195/141457175-3458a871-afce-4ffd-bb94-9623deec96a3.png)

But it only zoomed the plot, while still being blurry.

### Expected outcome

The same plot as above, but sharp.
I can think of two ways to achieve this:
A) Matplotlib check's the pixels per inch of the screen and chooses the output dpi and Jupyter canvas size accordingly
B) There could be an extra option to rescale the Jupyter canvas, so it does not grow bigger when using `plt.rcParams['figure.dpi'] = 150` . That way, the user can have sharp plots and Matplotlib does not need to know the screen resolution.

### Operating system

MacBook Air (M1, 2020) , macOS monterey

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

Python 3.9.5 

### Jupyter version

Jupyter Lab Version 3.0.16

**Comment by jklymak** [comment]
We don't maintain inline, ipython does.  However note there is a configuration option: https://gist.github.com/minrk/3301035

**Comment by kolibril13** [comment]
Thanks a lot for pointing me to this resource. That solved my problem. For anyone who will find this issue in future, here are two options: 
# i) Set InlineBackend figure_format to 'retina'
```py
import matplotlib.pyplot as plt
import numpy as np
%config InlineBackend.figure_format='retina' ## <- here

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)
fig, ax = plt.subplots()
ax.plot(t, s)
ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
plt.show()
```
# ii) Set InlineBackend to svg format:
```py
import matplotlib.pyplot as plt
import numpy as np
%config InlineBackend.figure_format = 'svg' ## <- here
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)
fig, ax = plt.subplots()
ax.plot(t, s)
ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
plt.show()
```
