### ISSUE TITLE
plot_types/ README.rst Hyperlink issue

### ISSUE THREAD

**Issue by 19lyaejin** [matplotlib/matplotlib#21620]
### Documentation Link

https://github.com/matplotlib/matplotlib/tree/main/plot_types

### Problem

I found that the README.rst file in the project's plot_types folder has a problem with hyperlinks.
In the sentence "See the gallery for many more examples and the tutorials page for longer examples.",
**there are two hyperlinks activated on the word 'gallery' and 'tutorials', but both of them are not working (404 error).** 

### Suggested improvement

The hyperlink on the word '**gallary**' should be fixed to 'https://matplotlib.org/stable/gallery/index.html', 
and the hyperlink on the word 'tutorials' should be fixed to 'https://matplotlib.org/stable/tutorials/index.html'. 

Thank you and hope you have a wonderful weekend.

### Matplotlib Version

import matplotlib; print("matplotlib 3.4.3")

### Matplotlib documentation version

matplotlib 3.4.3

**Comment by timhoffm** [comment]
Thanks for the report. The gallery and example pages are autogenerated during the doc build process. They do not exist statically on GitHub. The relevant thing is that the built docs work: https://matplotlib.org/devdocs/plot_types/index.html

**Comment by 19lyaejin** [comment]
Got it! Thank you:)
