### ISSUE TITLE
[Bug]: Getting imshow warning when floats are in valid range.

### ISSUE THREAD

**Issue by amogh7joshi** [matplotlib/matplotlib#21629]
### Bug summary

When displaying an image of dtype `float32`, whose minimum value is `0.06` (truncated) and whose maximum value is `1.0`, I get a warning stating that input data is being clipped  for floats, when the data is within the valid range. It would seem that this error shouldn't be arising. Perhaps in the place where this warning is being delivered, a "<" needs to be replaced with "<="?

### Code for reproduction

```python
-
```

### Actual outcome

```
11-13-2021 18:53:31 WARNING - matplotlib.image: Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
```

### Expected outcome

I shouldn't be getting this warning.

### Operating system

OSX

### Matplotlib Version

matplotlib.__version__

### Matplotlib Backend

module://backend_interagg

### Python version

3.9

### Installation

pip

**Comment by greglucas** [comment]
I can't reproduce, do you have a minimal reproducible example?

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0.06, 1.0, 50*30*3, dtype=np.float32)

rgb = x.reshape((50, 30, 3))

fig, ax = plt.subplots()
ax.imshow(rgb)

plt.show()
```

**Comment by amogh7joshi** [comment]
I don't have a specific reproducible example, the code that I'm using is on some specific local images, but I get the following values:

1. `image.dtype`: `float32`
2. `image.max()`: `1.0`
3. `image.min()`: `0.0666`

**Comment by greglucas** [comment]
We will need a little more help to reproduce the issue here then, because I gave a pretty minimal example that I think has the same properties:
`dtype: float32, max: 1.0, min: 0.05999999865889549`

Does the error still occur if you normalize your image by the max? `image = image/image.max()`

**Comment by tacaswell** [comment]
Can you please that the value is actually `1.0 ` and not ~1 EPS above 1.0 , but being truncated by the repr.  The easiest way is probably `print(1.0 - image.max())`.

Our test is currently https://github.com/matplotlib/matplotlib/blob/5d2e97e36bc70e9a0e2ea0ea8ad8ed64b35920bf/lib/matplotlib/image.py#L700-L701

so my suspicion is that this is yet another case of floating point's finite precision being a pain.

See https://github.com/matplotlib/matplotlib/pull/18487/files and the section on floating point for a rough description of what I think is going on.

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open if you still need help.
