### ISSUE TITLE
[Bug]: gtk + multiprocess do not work well together

### ISSUE THREAD

**Issue by erichstuder** [matplotlib/matplotlib#21627]
### Bug summary

Hello

If I call some matplotlib functions in a process I get about a 20s delay and an error message.
After that error message things seem to work fine though.
As far as I can see at the moment this happens only if I call a matplotlib function.

regards
erichstuder

### Code for reproduction

```python
from multiprocessing import Process
import matplotlib.pyplot as plt

def processFunction():
    plt.subplots()

Process(target=processFunction).start()
```

### Actual outcome

(PlotAll.py:27024): GVFS-WARNING **: 18:45:28.293: Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.Daemon: Timeout was reached (g-io-error-quark, 24)

### Expected outcome

no delay, no error

### Operating system

Debian

### Matplotlib Version

3.4.3

### Matplotlib Backend

GTK3Agg

### Python version

3.9.2

### Installation

pip

**Comment by tacaswell** [comment]
Try moving the pyplot import into your function?  I suspect that the gtk objects do not cope well with mutiprocess.  If you do not actually need GUI support in your sub-processes, try switching to use a non-GUI backend.

**Comment by erichstuder** [comment]
So i moved the import into the function.

```
from multiprocessing import Process

def processFunction():
    import matplotlib.pyplot as plt
    plt.subplots()

Process(target=processFunction).start()
```

This solves the problem.
Many thanks!

But can you explain why this works?
All the explanations, I found so far, tell that one should put the imports at the beginning of the module.
Is this a well defined behavior or some kind of "magic"?

**Comment by timhoffm** [comment]
> All the explanations, I found so far, tell that one should put the imports at the beginning of the module.

Generally, that is correct. However, there are special cases that need different handling. I haven't looked into the present case so cannot comment on its details specifically. Anyway, multiprocessing runs the function in a separate python process. This is simple for pure functions that only depend on their inputs. However, pyplot has a complex internal state for the figures, that the pyplot functions interact with. By running the import within the function, that state is properly initialized in the child process.
