### ISSUE TITLE
[Bug]: numpy 1.22 masked units test failure

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#21632]
### Bug summary

Testing with numpy 1.22 produces one test failure in Matplotlib. I'm not sure if it is in the way the test is designed, or something more intrinsic to the units handling.

### Code for reproduction

```python
python -m pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
pytest lib/matplotlib/tests/test_units.py::test_plot_masked_units
```

### Actual outcome

Link to CI run logs for this: https://github.com/greglucas/matplotlib/runs/4204821077?check_suite_focus=true

### Expected outcome

No failing test

### Matplotlib Version

3.5.0.dev2515+g6c9adc9b33

**Comment by tacaswell** [comment]
I can confirm this, looking into into it...

**Comment by tacaswell** [comment]
bisecting numpy changes is not fast 😞

**Comment by tacaswell** [comment]
```
$ git bisect bad
beacb394e94a517d1c84f8a50f9e18f3bf11ced5 is the first bad commit
commit beacb394e94a517d1c84f8a50f9e18f3bf11ced5
Author: default-303 <ajayds2001@gmail.com>
Date:   Wed May 26 18:36:36 2021 +0530

    MAINT: Removed 'if' block which served no purpose in core.py and removed '_linalgRealType(t)' function from linalg.py

 numpy/linalg/linalg.py | 4 ----
 numpy/ma/core.py       | 7 -------
 2 files changed, 11 deletions(-)

```

Not clear if the issue is a real issue or something about our test.

**Comment by dopplershift** [comment]
This is a real issue that I can reproduce with `pint`, which is what the `Quantity` class in `test_units.py` is designed to replicate. I'll continue the discussion in numpy/numpy#20372.

**Comment by greglucas** [comment]
This was resolved upstream in numpy by reverting part of that commit: #20386
