### ISSUE TITLE
[ENH]: Add a nightly wheel build

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#21635]
### Problem

Automated testing of third party packages against the latest matplotlib currently requires installing from source which takes quite a while.

### Proposed solution

Add a github action (with cibuildwheel maybe?) that builds the latest matplotlib on one or a few OSes x python versions. Somethign like:

Python 3.8 and 3.9 on latest ubuntu

These wheels should then be uploaded to a consistent place (maybe somewhere on maptlotlib.org?) with a clear naming scheme so it's easy to install then from a scheduled github action.

**Comment by tacaswell** [comment]
I think we build them already (https://github.com/matplotlib/matplotlib/actions/workflows/cibuildwheel.yml) on every merge to main and 3.5.x, but do not upload them anyplace yet.

**Comment by ianhi** [comment]
oooooh -  Thats almost perfect! 

You can get a list of them with:
```
curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/matplotlib/matplotlib/actions/artifacts
```
( following https://docs.github.com/en/rest/reference/actions) and from there it should be possible to install the correct version. The only issue is then that the download is pretty large (284 MB!).

So an amended version of this request is to upload two artifacts from that workflow:

1. The current `wheels` as is
2. A subset of the wheels (e.g. Ubuntu, x86_64, CPython) named something like CI-test-wheels
