### ISSUE TITLE
[Bug]: subplot parameter window appearing 1/4 size on macosx

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#21648]
### Bug summary

On the `macosx` backend, the subplot adjustment window is appearing 1/4 sized for me:
<img width="601" alt="Screenshot 2021-11-16 at 10 33 33" src="https://user-images.githubusercontent.com/6197628/141969735-3974c596-36f8-4170-8ce6-9c0ee4082df0.png">

I'm using a retina display at (2560 × 1600) resolution.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
plt.show()
```

### Actual outcome

Compressed interactive widgets.

### Expected outcome

Widgets fill full window.

### Operating system

macOS Big Sur (11.6)

### Matplotlib Version

matplotlib-3.5.0.dev2555+g4a44cb277e

### Matplotlib Backend

macosx

### Python version

3.9.7

### Installation

git checkout

**Comment by dstansby** [comment]
Bisects to ab61cbe79cd2350e2fd082aa44adac195d7f7b69 from https://github.com/matplotlib/matplotlib/pull/21365 (ping @QuLogic)

**Comment by anntzer** [comment]
I don't have a mac to try, but does replacing the entire body of configure_subplot() in _macosx.m by something like (untested, may be missing a semicolon or have some typos)
```objc
-(void)configure_subplots:(id)sender
{
    PyGILState_STATE gstate = PyGILState_Ensure();
    PyObject *mod = NULL, *base_class = NULL, *ret = NULL;
    if (!(mod = PyImport_ImportModule("matplotlib.backend_bases"))
        || !(base_class = PyObject_GetAttrString(mod, "NavigationToolbar2"))
        || !(ret = PyObject_CallMethod(base_class, "configure_subplots", toolbar))) {
        PyErr_Print();
    }
    Py_XDECREF(mod);
    Py_XDECREF(base_class);
    Py_XDECREF(ret);
    PyGILState_Release(gstate);
}
```
work?  (effectively making it inherit the base class implementation, which is after all good enough for most other backends).

**Comment by QuLogic** [comment]
That seems to work, though I also parented the window so that it closes properly, and is slightly more linked to the plot window. I don't know if it fixes retina displays though.
