### ISSUE TITLE
Table Cutting while SVG[Bug]: 

### ISSUE THREAD

**Issue by pascalbuehler1973** [matplotlib/matplotlib#21647]
### Bug summary

![image](https://user-images.githubusercontent.com/26140279/141943195-4728eeb6-429f-4027-98f3-f84c6d412d49.png)

when i plot a figure with table in svg, a part of the table is cut off. but when i show the picture, the table ist fine adjusted

### Code for reproduction

```python
#Darstellung
fig = plt.figure(figsize=(8,8));
plt.subplots_adjust(left=0.1, bottom=0.10, right=0.90, top=0.95, wspace=0.1, hspace=0.1);
plt.rc('font', size=10)
plt.plot(O[0], O[1], color='red', linestyle='-', linewidth=1, label=Mheader[1]);
plt.plot(O[0], O[2]*1000, color='blue', linestyle='-', linewidth=1, label="Current I [mA]");
plt.grid(color='black', linestyle='--', linewidth=0.5);
ax = fig.gca();
ax.set_title(r'$Smart\ Sensor\ Power\ Measurement\ with\ MQTT\ +\ LED\ \slash\ \vartheta=23 ^\circ C\ \slash\ \varphi=30\%r.F.\ \slash\ \ p=101325Pa$', fontsize=12);
ax.set_xticks(np.arange(0, max(O[0]), 50));
ax.set_yticks(np.arange(0, 36, 2));
#ax.set_yticks(np.arange(0, 100, 5));
ax.set_xlabel(Mheader[0]);  
ax.set_ylabel(Mheader[1]+" / "+"$Current\ I\ [mA]$");
ax.legend(loc='lower left'); 
ax2=ax.twinx();
plt.plot(O[0], O[3], color='green', linestyle='-', linewidth=1, label=Mheader[3]);
plt.plot(O[0], O[4], color='brown', linestyle='-', linewidth=1, label=Mheader[4]);
plt.plot(O[0], O[5], color='purple', linestyle='-', linewidth=1, label=Mheader[5]);
ax2.set_yticks(np.arange(0, 1.280, 0.08));
#ax2.set_yticks(np.arange(0, 2.0, 0.1));
ax2.set_ylabel(Mheader[3]+" / "+Mheader[4]+" / "+Mheader[5]);
ax2.legend(loc='lower right');
#Graphik Text
columns=Mheader[1:];
rows=(["$Mean\ \mu$","$Deviation\ 1\\sigma$","$Percent\ \%$"]);
txt = np.around([Mittel[1:], STABW[1:], Percent[1:]], decimals=4);
plt.table(cellText=txt,cellLoc='center',rowLabels=rows,colLabels=columns,colLoc='center',loc='bottom');
#Graphikerstellung
figurename=path[0]+name[0]+ending[1];
plt.savefig(figurename);
plt.show();
```

### Actual outcome

-

### Expected outcome

Table in the automatic saved picture

### Additional information

-

### Operating system

Windows 10

### Matplotlib Version

3.4.1

### Matplotlib Backend

-

### Python version

3.7

### Jupyter version

-

### Installation

pip

**Comment by jklymak** [comment]
Please indicate the backend, and give us a reproducible example - my guess would be you are using a backend that does the equivalent of `savefig(figurename, bbox_inches='tight')` and the table is really off the figure.  Try using that kwarg in your savefig command, but feel free to request a re-open if that does not help (and you can provide a reproducible minimal example).    Thanks

**Comment by pascalbuehler1973** [comment]
I try. thanks

Am Di., 16. Nov. 2021 um 09:29 Uhr schrieb Jody Klymak <
***@***.***>:
