### ISSUE TITLE
[Bug] 3.4.3: ft2font DSO module underlinking issue

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#21642]
### Bug summary

Looks like ft2font cpython DSO module is not linked with underlinked libbrotli.
After build on buulding documentation sphinx fails because it ft2font module cannot be loaded

### Code for reproduction

```python
`python3 setup.py build` with

[tkloczko@ss-desktop matplotlib-3.4.3]$ cat mplsetup.cfg
[libs]
system_freetype = True
system_qhull = True

[packages]
tests = True
toolkits = True
toolkits_tests = True
```

### Actual outcome

During building documentation:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx

Edit setup.cfg to change the build options; suppress output with --quiet.

BUILDING MATPLOTLIB
  matplotlib: yes [3.4.3]
      python: yes [3.8.12 (default, Sep 17 2021, 04:04:49)  [GCC 11.2.1 20210728
                  (Red Hat 11.2.1-1)]]
    platform: yes [linux]
       tests: no  [skipping due to configuration]
      macosx: no  [Mac OS-X only]

/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running build_sphinx
Running Sphinx v4.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/doc/conf.py", line 19, in <module>
    import matplotlib
  File "/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/build/lib.linux-x86_64-3.8/matplotlib/__init__.py", line 157, in <module>
    _check_versions()
  File "/home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/build/lib.linux-x86_64-3.8/matplotlib/__init__.py", line 142, in _check_versions
    from . import ft2font
ImportError: /home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/build/lib.linux-x86_64-3.8/matplotlib/ft2font.cpython-38-x86_64-linux-gnu.so: undefined symbol: BrotliDecoderDecompress
```
and indeed DSO is not linked with libbrotli
```console
[tkloczko@ss-desktop SPECS]$ objdump -x /home/tkloczko/rpmbuild/BUILD/matplotlib-3.4.3/build/lib.linux-x86_64-3.8/matplotlib/ft2font.cpython-38-x86_64-linux-gnu.so | grep NEED
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  VERNEED              0x0000000000003538
  VERNEEDNUM           0x0000000000000004
```

### Expected outcome

generated module should be linked with ncessary libraries.

### Operating system

Linux/x86_64

### Matplotlib Version

3.4.3

### Python version

3.8.12

### Jupyter version

N/A

**Comment by tacaswell** [comment]
Running with that `mplsetup.cfg` on main and buliding against FT2.11 on Arch I get:

```
objdump -x  build/lib.linux-x86_64-3.10/matplotlib/ft2font.cpython-310-x86_64-linux-gnu.so | grep NEEDED
  NEEDED               libfreetype.so.6
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
```

However, we recently renamed the config file and for 3.4.3 the file should be name `setup.cfg`, renaming it as such I get:

```
objdump -x  build/lib.linux-x86_64-3.10/matplotlib/ft2font.cpython-310-x86_64-linux-gnu.so | grep NEEDED
  NEEDED               libfreetype.so.6
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6

```

However, in the case where ft2font is built against our internal freetype build (which is FT2.6.1) the I get `objdump` outputs that look like yours, however that far pre-dates the addition of Brotli to freetype (which was added in ~2019 to support WOFF).  I am confused how you managed to end up with a statically linked ft2font which depends on libbrotli.

I am skeptical that there is anything we can do on the Matplotlib side and believe that this is another issue with your bespoke RPM build system.

**Comment by kloczek** [comment]
Just found that I had no patch (from Fedora) which updates matplotlib to be able build it against system FT2.11  so effectively mplsetup.cfg have been ignored so it is exactly the same case as you found.

BTW. Do you have maybe some plan to make 3.4.4 releases with FT2.11 update and few other?
Looks like it is still some work which needs to be done to make final 3.5.0 so maybe it would be good to make such small incremental update as probably all OS distribution are using FT2.11 (?)

**Comment by tacaswell** [comment]
I'm going to close this as it sounds like you have a path forward to fixing your build system.
