### ISSUE TITLE
[Doc]: Broken changelog link for 3.5.0rc1

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#21650]
### Documentation Link

https://matplotlib.org/stable/index.html and https://matplotlib.org/3.5.0/index.html

### Problem

The changelog link for 3.5.0rc1 here
![mpl](https://user-images.githubusercontent.com/1322974/142010361-e17f5db9-85a8-483a-9cae-96bb8dfb574f.png)
and likewise on the left of the new front page is broken.  Not sure whether the release of 3.5 is going to fix that, but pointing it out just in case...

### Matplotlib Version

3.5.0rc1

**Comment by tacaswell** [comment]
Those are controlled via a somewhat over-complicated html injection system via https://github.com/matplotlib/matplotlib.github.com/blob/main/versions.html

I just fixed it "live" https://github.com/matplotlib/matplotlib.github.com/commit/f05eff34109b4d263b64f3a3ad6bbaff646f2112

**Comment by QuLogic** [comment]
This should be fixed whenever the site cache is cleared up.
