### ISSUE TITLE
[Doc]: 3.5.0 PDF is unavailable

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#21655]
### Problem

There are some issues with the structure of the PDF, so I have not yet posted it.

For example, the  ToC for the PDF in 3.5.0 looks like:
![Screenshot from 2021-11-16 20-10-48](https://user-images.githubusercontent.com/302469/142091075-b684eecd-0118-4cb4-892b-08f3f966a854.png)
compared with the HTML which looks like:
![image](https://user-images.githubusercontent.com/302469/142091230-12565e2b-c17d-42bc-a79c-f2fa976db871.png)
The 'Installing from source' and 'Installing FAQ' both appear before the 'Installation' page, but are hidden in the HTML version.

### Matplotlib Version

3.5.0

**Comment by QuLogic** [comment]
@jklymak @timhoffm You last re-arranged the docs to have Tutorials/Examples first, and then the User Guide:
![image](https://user-images.githubusercontent.com/302469/142284339-4f112c01-b488-40eb-b5bf-b7def2661033.png)
This is OK in the website, because we have the top bar that can link to any of those.

But in the PDF, it's all very linear, and it seems odd to have a bunch of tutorials first, followed by a Getting Started and Installation Guide. Since this doesn't really affect the HTML site that much, what do you think of re-ordering these?

**Comment by jklymak** [comment]
@timhoffm was the proponent of reordering them.  I'm fine either way.

**Comment by jklymak** [comment]
The other approach is to just have the TOC in the middle of the page, and
```
- :doc:`/tutorials/index` 
- :doc:`/gallery/index`
```
instead of explicit TOC here..

**Comment by timhoffm** [comment]
I have the feeling that this is the result of not having a clear hierarchical structure in the docs. But I don't want to dive down into docs structure again right now. So I'm fine with any solution that works to fix the PDF.

**Comment by QuLogic** [comment]
The PDF has now been shrunk and uploaded with 3.5.1; I will not attempt to fix it for 3.5.0.
