### ISSUE TITLE
[Bug]: ax.add_collection3d throws warning Mean of empty slice

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#21652]
### Bug summary

Whatever I plot with ax.add_collection3d, I get several runtime warnings.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np

ax = plt.figure().add_subplot(projection='3d')
vertices=np.array(
    [[0., 0., 0.],
     [0., 1., 0.],
     [0., 0., 1.]])
pc=Poly3DCollection(vertices.T) 
ax.add_collection3d(pc)
plt.show()
```
*edit (Tim Hoffmann): made the example self-contained*

### Actual outcome

```
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

### Expected outcome

No warnings.

### Operating system

Ubuntu 18

### Matplotlib Version

3.3.4

### Matplotlib Backend

Qt5Agg

### Python version

3.6.9

### Installation

pip

**Comment by timhoffm** [comment]
According to the docs (https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.art3d.Poly3DCollection.html), you have to pass a list of (N, 3) array-likes, i.e. the correct call is:

`pc=Poly3DCollection([vertices.T])`

We should however check the input and error out there.

**Comment by keithbriggs** [comment]
Thanks for the reply. I may have posted a  bad example. However, even with good inputs and with a correct plot produced, I still get the warnings. Basically, I always get them, whatever the inputs. The output plots are all fine.

**Comment by timhoffm** [comment]
As written above, you need to pass a *list* of 2D arrays, not a single 2D array.

**Comment by keithbriggs** [comment]
Thanks again, that fixes everything!
