### ISSUE TITLE
[Bug]: New plot directive error in 3.5.0

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#21668]
### Bug summary

In sunpy we have a doctest that is inside a plot directive, that also has some doctest flags, in particular `doctest: +REMOTE_DATA`. Building the docs with matplotlib 3.4.3 works fine, but with 3.5.0 it fails.

### Code for reproduction

```python
.. plot::
   :include-source:

   sunpy Map uses coordinates to specify locations on the image, and to plot
   overlays on plots of maps. When a Map is created, a coordinate frame is
   constructed from the header information. This can be accessed using
   ``.coordinate_frame``:

   >>> import sunpy.map
   >>> from sunpy.data.sample import AIA_171_IMAGE   # doctest: +REMOTE_DATA
   >>> m = sunpy.map.Map(AIA_171_IMAGE)  # doctest: +REMOTE_DATA
```

### Actual outcome

`/Users/dstansby/github/sunpy/docs/guide/units-coordinates.rst:200: WARNING: line 7 of the doctest for <string> has an invalid option: '+REMOTE_DATA'`

### Expected outcome

No warning raised.

### Operating system

macOS

### Matplotlib Version

3.5.0

### Python version

3.9.6

### Installation

pip

**Comment by anntzer** [comment]
My guess is that the short term fix is for you to explicitly register the extra doctest options (e.g. in your conf.py), as already done by pytest-doctestplus
https://github.com/astropy/pytest-doctestplus/blob/e1225358cbcea26415696d194745c6262e45a075/pytest_doctestplus/output_checker.py#L17-L29

**Comment by pllim** [comment]
Seems weird to have to re-register them when we already installed `pytest-doctestplus` to use them.

**Comment by anntzer** [comment]
I would assume that by default, sphinx has no reason to load pytest plugins?

**Comment by embray** [comment]
I'm surprised this would have anything to do with matplotlib at all.  What is the normal purpose of including a doctest inside a `.. plot` directive?  How does that end up rendering for users?

If the doctest is run with pytest it shouldn't care if the doctest is inside a `plot` directive.  However, if it's something special matplotlib does, then it could be relevant, if matplotlib is using its own doctest parser.

**Comment by tacaswell** [comment]
The reason this showed up as a Matplotlib issues is that in f900c34799ea30e3c041902eee77c12694d65400 / https://github.com/matplotlib/matplotlib/pull/20109 we switched from using our own implementation to extract the python code from a doctest block and now we are using doctest (and doctest is helpfully checking options for us!) 

```python

In [13]: doctest.script_from_examples('>>> from sunpy.data.sample import AIA_171_IMAGE   # doctest: +REMOTE_DATA')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-b4d9cd6a6dd4> in <module>
----> 1 doctest.script_from_examples('>>> from sunpy.data.sample import AIA_171_IMAGE   # doctest: +REMOTE_DATA')

/usr/lib/python3.9/doctest.py in script_from_examples(s)
   2572        """
   2573     output = []
-> 2574     for piece in DocTestParser().parse(s):
   2575         if isinstance(piece, Example):
   2576             # Add the example's source code (strip trailing NL)

/usr/lib/python3.9/doctest.py in parse(self, string, name)
    649             # Extract info from the regexp match.
    650             (source, options, want, exc_msg) = \
--> 651                      self._parse_example(m, name, lineno)
    652             # Create an Example, and add it to the list.
    653             if not self._IS_BLANK_OR_COMMENT(source):

/usr/lib/python3.9/doctest.py in _parse_example(self, m, name, lineno)
    730 
    731         # Extract options from the source.
--> 732         options = self._find_options(source, name, lineno)
    733 
    734         return source, options, want, exc_msg

/usr/lib/python3.9/doctest.py in _find_options(self, source, name, lineno)
    759                 if (option[0] not in '+-' or
    760                     option[1:] not in OPTIONFLAGS_BY_NAME):
--> 761                     raise ValueError('line %r of the doctest for %s '
    762                                      'has an invalid option: %r' %
    763                                      (lineno+1, name, option))

ValueError: line 1 of the doctest for <string> has an invalid option: '+REMOTE_DATA'

In [14]: 
```

I think, unfortunately, @anntzer 's suggestion is the best path forward (or finding a way to get `pytest-doctestplus` to also register itself someplace sphinx will find?).

**Comment by dstansby** [comment]
Thanks for the quick replies - I guess I'm happy closing this then given the proposed solution seems reasonable.

**Comment by tacaswell** [comment]
I am not sure if we can strip off trailing comment without actually parsing the Python (as we can not delete the end of `print('# a test')`. 

Sorry about causing some chaos for astropy/sunpy.

**Comment by pllim** [comment]
Thank you for the quick replies and workaround! 😸

**Comment by anntzer** [comment]
Would the following have helped?
```patch
diff --git i/lib/matplotlib/sphinxext/plot_directive.py w/lib/matplotlib/sphinxext/plot_directive.py
index 4024bccdde..463692bb12 100644
--- i/lib/matplotlib/sphinxext/plot_directive.py
+++ w/lib/matplotlib/sphinxext/plot_directive.py
@@ -41,6 +41,10 @@ The source code for the plot may be included in one of three ways:
         >>> import matplotlib.pyplot as plt
         >>> plt.plot([1, 2, 3], [4, 5, 6])
 
+   Note that in that case, the contents will be preprocessed using
+   `doctest.script_from_examples`; in particular, option flags needs to be
+   valid (or registered using `doctest.register_optionflag`).
+
 Options
 -------
```

If yes, feel free to open a PR with the patch.

**Comment by pllim** [comment]
> Would the following have helped?

For me, not really. I wasn't even looking at the doc for plot directive... I can't speak for others.
