### ISSUE TITLE
[Bug]: matplotlib.pyplot.quiver orde of parameters inconsistency with documentation.

### ISSUE THREAD

**Issue by igorkolesnikov13** [matplotlib/matplotlib#21675]
### Bug summary

Matplotlib.pyplot.quiver seems to be mixing parameters of U and V values (inverse order cited in documentation). This causes wrong visualization of gradient field. 

### Code for reproduction

```python
Google Colab Notebook: https://colab.research.google.com/drive/1sq8Dn7wdNqbfRmz2SyQnj0MfRirxmneA?usp=sharing

----------------------

import numpy as np
from matplotlib import pyplot as plt
import astropy.io.fits as fits

"""# Auxiliary functions"""
def makeGaussian(size, fwhm = 3, center=None):
    """ Make a square gaussian kernel.

    size is the length of a side of the square
    fwhm is full-width-half-maximum, which
    can be thought of as an effective radius.
    """

    x = np.arange(0, size, 1, float)
    y = x[:,np.newaxis]

    if center is None:
        x0 = y0 = size // 2
    else:
        x0 = center[0]
        y0 = center[1]

    return np.exp(-4*np.log(2) * ((x-x0)**2 + (y-y0)**2) / fwhm**2)

def create_circular_mask(h, w, center=None, radius=None):

    if center is None: # use the middle of the image
        center = (int(w/2), int(h/2))
    if radius is None: # use the smallest distance between the center and image walls
        radius = min(center[0], center[1], w-center[0], h-center[1])

    Y, X = np.ogrid[:h, :w]
    dist_from_center = np.sqrt((X - center[0])**2 + (Y-center[1])**2)

    mask = dist_from_center <= radius
    return mask

def plotGradientField(dx, dy):
    figSize = 10
    fig, ax = plt.subplots(figsize=(figSize, figSize), dpi=120)
    x, y = np.meshgrid(np.arange(0, dx.shape[1], 1), np.arange(0, dy.shape[0], 1))
    ax.quiver(x, y, dx, dy)

def readFitsImage(folder, fileName):
    fitsFile = fits.open(folder+fileName)
    np_array = np.array(fitsFile[0].data, np.float32)
    fitsFile.close()
    return np_array

"""# Getting data"""
imageSize = (100,100)
gaussianMatrix = makeGaussian(imageSize[0],imageSize[1])

radius = imageSize[0]/4
mask = create_circular_mask(imageSize[0], imageSize[1], radius=radius)

nan_image = gaussianMatrix.copy()
nan_image[~mask] = np.nan

"""# Generation gradient field"""
x,y = np.gradient(nan_image)

"""# Plotting - current result"""
fig, ax = plt.subplots(figsize=(10, 10), dpi=120)
ax.quiver(x, y)

"""# Plotting - Expected result"""
fig, ax = plt.subplots(figsize=(10, 10), dpi=120)
ax.quiver(y, x)
```

### Actual outcome

![actual](https://user-images.githubusercontent.com/42065340/142516496-fd98db21-12bd-45ea-b0b8-ddb2b797a39e.png)

### Expected outcome

![expected](https://user-images.githubusercontent.com/42065340/142516538-e52df9d5-08d1-48e2-bd14-19547106aca7.png)

### Additional information

Just to clarify, the quiver method is working properly. The problem consists in the divergence with documentation and logic (usually, x comes first, and then y). Short snippet:
`
x,y = numpy.gradient(array_2d) 

plt.quiver(x,y) <- as per documentation, produces wrong result

plt.quiver(y,x) <- inverse to documentation, produces right result
`

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.4.3

### Matplotlib Backend

import matplotlib; print(matplotlib.get_backend())

### Python version

Python 3.9.7

### Jupyter version

IPython          : 7.29.0

### Installation

conda

**Comment by jklymak** [comment]
I don't think the documentation is incorrect.  Please try with a simpler example like `quiver(1, 0.2)`.

**Comment by igorkolesnikov13** [comment]
I did try the suggested example. Thank you. It seems to make sense (the arrow tends to point to greater value direction).

Then the problem seems to be of the different nature. The Gaussian field should produce a gradient field with all the arrows inwards. To achieve this, you need to switch parameters. This seems wrong.

The resulting plot (arrows pointing in different directions) of the order of parameters recommended by documentation is just don't make sense...

**Comment by jklymak** [comment]
How you derive the vectors from what you are calling a "Gaussian field" is off topic for our issue tracker.  Thanks for your understanding
