### ISSUE TITLE
[Bug]: 3.5.0 colorbar outside of its axis when saved into vectorial formats

### ISSUE THREAD

**Issue by Cgadal** [matplotlib/matplotlib#21672]
### Bug summary

For some figure/subplot/colorbar axis aspect ratios, the colorbar is outside of its axes when saved into vectorial formats (pdf, svg).

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 100, 100)
y = np.linspace(0, 100, 100)
z = x[None, :]**2 + y[:, None]**2

fig, axarr = plt.subplots(1, 2, figsize=(3, 2.8789385625),
                          constrained_layout=True, sharey=True)
ax = axarr[0]
a = ax.pcolormesh(x, y, z, snap=True)
fig.colorbar(a, ax=ax, location='top')
#
ax = axarr[1]
a = ax.pcolormesh(x, y, z, snap=True)
fig.colorbar(a, ax=ax, location='top')
plt.savefig('test_colorbar.pdf')
plt.savefig('test_colorbar.svg')
plt.savefig('test_colorbar.png', dpi=800)
```

### Actual outcome

![Screenshot from 2021-11-18 17-01-03](https://user-images.githubusercontent.com/48522112/142451121-8094060b-a020-4ee4-bfdb-410a322da62b.png)

### Expected outcome

The colorbar should be within its axis, and not shifted upward.

### Additional information

- It does not occur when the figure is saved to non-vectorial format (i.e png, etc ..)
- In this case, it does not occur for all figure aspect ratios.
-  It was already the case in matplotlib 3.4.3

### Operating system

Ubuntu 20

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.8.10

### Installation

pip

**Comment by jklymak** [comment]
Yes, this is very old  #6827  @brunobeltran  fixed it, but his PR has languished #17182
