### ISSUE TITLE
[Bug]: ConciseDateFormatter not showing offset

### ISSUE THREAD

**Issue by Stassels** [matplotlib/matplotlib#21670]
### Bug summary

When I create time series plot with too big time range, I can't see offset in lower right corner.

### Code for reproduction

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

LEN = 40000
dt_index = pd.date_range('2013-01-01 00:00', periods=LEN, freq='5min')
df = pd.DataFrame({'data': np.random.randint(10, size=LEN)},index=dt_index)

fig, ax = plt.subplots()
import matplotlib.dates as mdates

locator = mdates.AutoDateLocator()
formatter = mdates.ConciseDateFormatter(locator)
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)

ax.plot(df.index, df.data)

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/65774287/142439531-cf2296e3-fe13-4761-9e69-74c2cac7826e.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/65774287/142439628-02a10b6b-9a95-4d1c-96e5-7f6f38907da2.png)

### Additional information

When changing time range with fewer points, I can see the offset as seen in expected outcome.

### Operating system

Ubuntu 

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg

### Python version

3.9

**Comment by jklymak** [comment]
There is no offset if the year is indicated in the axis somewhere.  I think this is expected behaviour.

**Comment by Stassels** [comment]
> There is no offset if the year is indicated in the axis somewhere. I think this is expected behaviour.

Sorry, I probably didn't wrote it clearly enough.
When I use pan/zoom tool and zoom in to months/days/day, I still can't see the offset. I think that's not expected behavior.

But when I use this example and change LEN to 35000 and then use pan/zoom tool and zoom out, I can see the offset in any zoom level.

**Comment by dstansby** [comment]
Thanks for the self contained example; I can reproduce this bug.

**Comment by jklymak** [comment]
Thanks both!  #21785 should fix this.
