### ISSUE TITLE
[Bug]: matplotlib code hangs on plt.plot()

### ISSUE THREAD

**Issue by TerpstraS** [matplotlib/matplotlib#21678]
### Bug summary

When I try to use certain functions from matplotlib, my code gets stuck at those functions. For example, my code can run plt.figure(), but the execution of the code gets stuck at plt.plot(...). No error codes are produced, and I can't interrupt execution using ctrl+c.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()

x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)

plt.plot(x, y)
plt.show()
```

### Actual outcome

No outcome is produced, code keeps running at the plt.plot(x, y) statement. If I run 
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

in my program, I get the following output:

```
DEBUG:matplotlib:matplotlib data path: 
/home/sjoerd/miniconda3/lib/python3.9/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/sjoerd/.config/matplotlib
DEBUG:matplotlib:matplotlib version 3.4.3
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: [...] whole list of modules loaded, not shown here
DEBUG:matplotlib:CACHEDIR=/home/sjoerd/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/sjoerd/.cache/matplotlib/fontlist-v330.json
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend Qt5Agg version unknown.
```

### Expected outcome

Expected outcome is a simple x,y-plot.

### Additional information

The bug happened after I installed [citrix workplace](https://www.citrix.com/nl-nl/products/receiver.html) on my Linux Mint 5.4.0-70-generic installation. After removing citrix workplace from my system, the bug disappeared. See also my [question](https://stackoverflow.com/questions/70010835/python-matplotlib-code-hangs-on-plt-plot) on stackoverflow.

### Operating system

Linux Mint

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg, error is independent of which backend trying to use (e.g. Qt4Agg)

### Python version

3.9.7, error also happens with 3.8.*

### Installation

conda

**Comment by jklymak** [comment]
Can you open any qt5 applications?  If not, we can't directly help...

**Comment by TerpstraS** [comment]
I will take this up with citrix, as the problem seems to be caused by them, and not primarily by matplotlib.
