### ISSUE TITLE
[MNT]: Close subplot_parameters window when main figure closes

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#21679]
### Summary

If you click the subplot parameters button from the toolbar, a new window pops up. If you then close the main figure window, the subplot parameters window will still be there and keep the session alive. I would expect the main figure window to close the subplot parameters pop up as well on close. (same experience on macosx and qt5agg)

### Proposed fix

Keep a child reference to the subplot parameters window around that we can then close automatically for the user?

**Comment by anntzer** [comment]
Probably you do something like connecting to close_event?
