### ISSUE TITLE
[Doc]: Wrong link to the ready-made citation entry

### ISSUE THREAD

**Issue by simonthor** [matplotlib/matplotlib#21702]
### Documentation Link

https://github.com/matplotlib/matplotlib#citing-matplotlib

### Problem

The links in the README and on matplotlib.org to the ready-made citation entry redirects to https://matplotlib.org/stable/citing.html, which gives a 404 error.

### Suggested improvement

I am guessing that creating a citing.html would be the easiest solution. If this takes a long time to implement, maybe the hyperlinks should link to https://matplotlib.org/3.4.3/citing.html in the meantime?

### Matplotlib Version

3.5.0

**Comment by tacaswell** [comment]
Would be better to point it at https://matplotlib.org/stable/users/project/citing.html (which is where it got moved to).

**Comment by simonthor** [comment]
Thank you for sharing the link! Was looking around for it but could not find it myself.
