### ISSUE TITLE
[Bug]: y axis using a 'symlog' doesn't work properly

### ISSUE THREAD

**Issue by WallsnBridges** [matplotlib/matplotlib#21709]
### Bug summary

I plotted two different graphs using 'symlog'.
One worked properly, but the other doesn't. Perhaps a bug? or I did something wrong?

### Code for reproduction

```python
%matplotlib inline

import matplotlib.pyplot as plt

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = 10, 5


import obspy
from obspy.clients.fdsn import Client

c = Client("IRIS")

starttime = obspy.UTCDateTime(2016, 12, 26, 0, 58, 50)
endtime = starttime + 6400

st = c.get_waveforms(network = "KS", station = "SEO2", location = "", channel = "BH*",
                     starttime = starttime, endtime = endtime)

inv = c.get_stations(network = "KS", station = "SEO2", location = "", channel = "BH*",
                     starttime = starttime, endtime = endtime, level = "response")

st.slice(endtime = starttime + 3600).copy().taper(0.05).filter(
    "bandpass", freqmin=1.0 / 500.0, freqmax=1.0 / 50.0)


import numpy as np

tr = st.select(component = "Z")[0].copy().taper(0.05)
D = np.fft.rfft(tr.data)
freqs = np.fft.rfftfreq(tr.stats.npts, d = tr.stats.delta)

plt.plot(freqs, np.abs(D))
plt.xlim(0.2E-4, 0.8)
plt.ylim(300, 3E7)
plt.xlabel("Frequency [mHz]")
plt.yscale('symlog')
plt.show()


tr = st.select(component = "Z").copy().remove_response(inventory = inv, 
                                                     output = "DISP")[0]
D = np.fft.rfft(tr.data)
freqs = np.fft.rfftfreq(tr.stats.npts, d = tr.stats.delta)

plt.plot(freqs, np.abs(D))
plt.xlim(0.2E-4, 0.8)
plt.ylim(0, 0.01)
plt.xlabel("Frequency [mHz]")
plt.yscale('symlog')
plt.show();
```

### Actual outcome

![symlog_1](https://user-images.githubusercontent.com/92560657/142825212-23759a6d-fa71-4039-8b7e-bba8b903cf27.png)
![symlog_2](https://user-images.githubusercontent.com/92560657/142825217-945dccfe-7edc-4268-a705-e2c7e17d2831.png)

### Expected outcome

The second graph should be plotted as log scale, but the result was in linear scale. 
Only the numbers written on a y axis changes.
the data has not changed at all.

### Additional information

Perhaps this could be similar problems to #15077 or [this one](https://discourse.matplotlib.org/t/tests-test-axes-test-symlog-failed/14481). I'm not sure.

Plus, I've tested in different version of Matplotlin(3.3.4), Python(3.3.8) and Jupyter(6.3.0). the outcome was the same.

### Operating system

Windows

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.5

### Jupyter version

6.4.5

### Installation

conda

**Comment by jklymak** [comment]
Please see the `lin_thresh` kwarg to symlog.  All your data is under the default of 1.0, and hence is plotted linearly.  https://matplotlib.org/stable/gallery/scales/symlog_demo.html

**Comment by WallsnBridges** [comment]
It worked! thanks a lot! have a nice day :)
