### ISSUE TITLE
how get the rgb value of a pixel from image, scene

### ISSUE THREAD

**Issue by gersmit** [matplotlib/matplotlib#21701]
### Problem

I have this : area = new_scn[chan].attrs['area']
How I can I get the pixel RGB value from scene new_scn[chan] by coordinate or row,col from image 

Thanks in advance

**Comment by jklymak** [comment]
This channel is for bug reports not user help.  Please respect the need to keep this channel on topic.

**Comment by jklymak** [comment]
Please post to https://discourse.matplotlib.org
