### ISSUE TITLE
[MNT]: cat: setup.cfg.template: No such file or directory 

### ISSUE THREAD

**Issue by brobr** [matplotlib/matplotlib#21713]
### Summary

Hi, when trying to build matplotlib-3.5.0 using a setup.py-based script (to produce a package that can be distributed for Slackware64) halts on:
>cat: setup.cfg.template: No such file or directory 

Building the previous matplotlib-3.4.3 that way goes without a hitch

**Comment by jklymak** [comment]
please see https://github.com/matplotlib/matplotlib/pull/20871

**Comment by tacaswell** [comment]
We do note this in https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#matplotlib-specific-build-options-moved-from-setup-cfg-to-mplsetup-cfg but did not note that the template files were also renamed, working an a PR to add the extra sentence.

**Comment by brobr** [comment]
Thanks, got mpl building now (after adapting my script).
