### ISSUE TITLE
[MNT]: Is the macosx backend (very slowly) leaking strings?

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#21722]
### Summary

macosx.m contains the following snippets:
```objc
static PyObject*
FigureManager_set_window_title(FigureManager* self,
                               PyObject *args, PyObject *kwds)
// elided
        NSString* ns_title = [[[NSString alloc]
                               initWithCString: title
                               encoding: NSUTF8StringEncoding] autorelease];
        [window setTitle: ns_title];
// elided
```
and
```objc
static PyObject*
choose_save_file(PyObject* unused, PyObject* args)
// elided
    [panel setTitle: [NSString stringWithCString: title
                                        encoding: NSASCIIStringEncoding]];
    NSString* ns_default_filename =
        [[NSString alloc]
         initWithCString: default_filename
         encoding: NSUTF8StringEncoding];
    [panel setNameFieldStringValue: ns_default_filename];
// elided
```
I'm don't know anything about autorelease semantics, but it seems a bit worrying that set_window_title makes some GC-related action on ns_title (`autorelease`) whereas choose_save_file doesn't, just using `title` and `ns_default_filename` directly.  Or perhaps nothing matters and the `autorelease` in set_window_title is redundant?

**Comment by QuLogic** [comment]
`ns_default_filename` is released on the next line, so it's fine. I think `title` is fine too, as we didn't call `alloc` explicitly, so it defaults to `autorelease`, according to https://stackoverflow.com/a/2713941

**Comment by QuLogic** [comment]
OK, the links from SO were broken, but I think I've found [the archived docs](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html) which explains it.

Basically,
* `alloc` needs `autorelease` or `release`
* Normal constructor (without `alloc`) is `autorelease`

We should probably just use the default constructor and not bother with explicit `release` or `autorelease`.

**Comment by dstansby** [comment]
Is this fixed by https://github.com/matplotlib/matplotlib/pull/23060 and/or https://github.com/matplotlib/matplotlib/pull/23558?

**Comment by anntzer** [comment]
Hard for me to judge, but at least the offending code isn't there anymore.

**Comment by QuLogic** [comment]
I think #23060 is likely to have fixed it.
