### ISSUE TITLE
[Bug]: The default Pyplot buttons are unresponsive with Python 3.9.9.

### ISSUE THREAD

**Issue by KennethEvans** [matplotlib/matplotlib#21736]
### Bug summary

See https://stackoverflow.com/questions/70072297/pyplot-buttons-do-not-work-reliably-on-windows-10.

I have only tried Python 3.7 as installed in Visual Studio 2019 (where the buttons are ok) and Python 3.9.9, which I installed myself from python.org, (where they do not). I am using Matplotlib 3.5.0 with Python 3.9.9, and have tested 3.3.4 and 3.4.3. I am using 3.3.4 with Python 3.7.

I admit it seems strange that no one else has reported this as far as I can tell.

This is on Windows 10.

### Code for reproduction

```python
from math import radians, degrees
import numpy as np
import matplotlib.pyplot as plt

def main():
    x = np.arange(0, radians(1800), radians(12))
    theta = np.arange(0, 1800, 12)
    plt.plot(theta, np.cos(x), 'b')
    plt.title("Plot of cos(x)")
    plt.ylabel("cos(x)")
    plt.xlabel("x, degrees")
    plt.xticks(np.arange(0, 1801, 180))
    plt.grid(True)
    plt.show()

main()
```

### Actual outcome

Buttons usually do not respond (don't show they are pressed and don't do anything). Occasionally they do. Home can typically be depressed but almost never restores the plot.

### Expected outcome

Buttons respond (show they are pressed) and do what they should.

### Additional information

Works in 3.7.

### Operating system

Windows 10

### Matplotlib Version

3.5.0, 3.3.4, 3.4.3

### Python version

3.9.9

### Installation

pip

**Comment by jklymak** [comment]
Please make sure that you have updated all libraries associated with your GUI backend.  If you install via `pip` GUI libraries do not necessarily get updated, and can have inconsistencies across python versions.

I'm going to close this here, as I'm not sure we can help you directly with install problems.  We strongly suggest anaconda or another package manager that downloads non-python libraries in a  consistent manner.  

If you would like to follow up, please feel free to do so at https://discourse.matplotlib.org  Thanks!

**Comment by David-OConnor** [comment]
Same with 3.10.

Here are details: Buttons work on plot start. If you change dimensions, they stop working. If you move the window, they start again.

I was on Python 3.9 using a recent version of MPL. No bug.

I did a clean reinstall of Python and all Dependencies, with Python 3.10 and MPL 3.5.1. Bug started.

Windows 11. PyQt5 backend.
