### ISSUE TITLE
[Bug]: No module named 'mpl_toolkits.axes_grid1.colorbar'

### ISSUE THREAD

**Issue by gfjlcw** [matplotlib/matplotlib#21738]
### Bug summary

Can't find the module even though I have already installed matplotlib

### Code for reproduction

```python
from mpl_toolkits.axes_grid1.colorbar import colorbar
```

### Actual outcome

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/Users/gabri/Desktop/vaccine/severity_signatures/dashboarding/pages/GSE100299.py", line 26, in <module>
    from mpl_toolkits.axes_grid1.colorbar import colorbar
ModuleNotFoundError: No module named 'mpl_toolkits.axes_grid1.colorbar'

### Expected outcome

No error

### Operating system

OS

### Matplotlib Version

3.5.0

### Python version

3.8.8

### Installation

pip

**Comment by QuLogic** [comment]
This was removed in 3.4: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#modules

**Comment by ZhaohuiZhang0809** [comment]
Works for matplotlib 3.3. For later versions, use matplotlib.colorbar.
