### ISSUE TITLE
[Bug]: Possible bug on arrows in annotation

### ISSUE THREAD

**Issue by jason-sachs** [matplotlib/matplotlib#21733]
### Bug summary

Arrow behavior in `axes.annotate` is inconsistent depending on the direction of the xy coordinate.

Arrow line begins at center of text in cases of horizontal/vertical lines, but begins at lower left of text in cases of diagonal lines.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.set_xlim(0,1)
ax.set_ylim(0,1)
ax.set_aspect('equal')
ax.grid(True)
for target in ((0.2,0.2),(0.2,0.4),(0.2,0.6),(0.4,0.2),(0.6,0.2)):
    ax.annotate('Blah! Blah blah blah.',xy=target, xytext=(0.6,0.6),
                 bbox=dict(boxstyle='round', facecolor='none'),
                 ha='center',va='center',
                 arrowprops=dict(facecolor='black',width=0.8,headwidth=5,connectionstyle="arc3,rad=0"))
```

### Actual outcome:

![matplotlib2](https://user-images.githubusercontent.com/10506541/143145770-d98622f5-4319-4bc6-8f9f-b4c8ef51510e.png)

### Expected outcome

Arrow starting point should be consistent, or at least adjustable; relpos is not available as a FancyArrowPatch key, so if I add it, I get `AttributeError: 'FancyArrowPatch' object has no property 'relpos'`

### Operating system

Windows

### Matplotlib Version

import matplotlib; print(matplotlib.__version__)

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.7.4

### Jupyter version

6.1.4

### Installation

conda

**Comment by timhoffm** [comment]
The question is: On which angles do we want to change the anchor point?

![grafik](https://user-images.githubusercontent.com/2836374/143214641-89b3f566-f766-4e88-8bf4-b4e8b2171b51.png)


```
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.set(xlim =(0, 2), ylim=(0, 2))
ax.set_aspect('equal')
ax.grid(True)

phi = np.linspace(0, 2*np.pi, 37)
x = np.cos(phi) + 1
y = np.sin(phi) + 1

for xi, yi in zip(x, y):
    ax.annotate('Blah! Blah blah blah.',xy=(xi, yi), xytext=(1, 1),
                 bbox=dict(boxstyle='round', facecolor='none'),
                 ha='center',va='center',
                 arrowprops=dict(facecolor='black',width=0.8,headwidth=5,connectionstyle="arc3,rad=0"))
```

**Comment by anntzer** [comment]
The relevant logic is at https://github.com/matplotlib/matplotlib/blob/73304d2936730939609880cb27068f2777e940c5/lib/matplotlib/text.py#L1932-L1937 I think.

**Comment by jason-sachs** [comment]
I don't mind the existing implementation if it's documented -- it was a bit of a surprise to me.

**Comment by jason-sachs** [comment]
Eventually, I gave up trying to do what I wanted (just have arrows emanating from the center of the block by trying to use `relpos` as I mentioned in #21732 ) and took [an approach in StackOverflow](https://stackoverflow.com/a/43800620/44330) and just created separate annotations for the arrows and for the text.

**Comment by timhoffm** [comment]
> what I wanted (just have arrows emanating from the center of the block by trying to use relpos as I mentioned in #21732 )

@jason-sachs that's possible if you specify an arrowstyle, e.g. `arrowprops=dict(arrowstyle='-|>', facecolor='black')`.
There are two different draw routines and I hope #21743 makes this more clear.

**Comment by jason-sachs** [comment]
Yeah, I tried that, but using `arrowstyle` doesn't let me get the type of arrowhead I want.

**Comment by timhoffm** [comment]
Which type of head would you want?
