### ISSUE TITLE
[Doc]: relpos is not valid for FancyArrowPatch

### ISSUE THREAD

**Issue by jason-sachs** [matplotlib/matplotlib#21732]
### Documentation Link

https://matplotlib.org/stable/api/text_api.html

### Problem

`arrowprops` section states

>Valid keys for FancyArrowPatch are: 
>  ...
> relpos

but relpos is not a valid kwarg for FancyArrowPatch. 

### Suggested improvement

Fix so that the docs state allowable keys. I can't figure out when `relpos` is allowed and when it is not.

### Matplotlib Version

3.4.3

**Comment by timhoffm** [comment]
This seems like a leftover from removing YAArrow (#4178).

The arrowprops docstring is outdated in multiple ways:
- the width, headwidth headlength, shrink, frac parameters are only allowed if there is no "arrowstyle". But they are ignored - should probably be deprecated.
- Three are now more arrowstyles available from FancyArrowPatch.
- relpos is not a FancyArrowPatch attribute. It's handled explicitly - functionality to be inferred from the code.

**Comment by timhoffm** [comment]
Closed by #21743.
