### ISSUE TITLE
[Bug]: Can not pickle figure with constrained_layout

### ISSUE THREAD

**Issue by mseitzer** [matplotlib/matplotlib#21744]
### Bug summary

Pickling a figure with constrained layout on does not work.

### Code for reproduction

```python
import pickle
from matplotlib import pyplot as plt

fig, ax = plt.subplots(constrained_layout=True)

with open('fig.pkl', 'wb') as f:
    pickle.dump(fig, f)
```

### Actual outcome

```
Traceback (most recent call last):
  File "matplotlib_pickle_bug.py", line 7, in <module>
    pickle.dump(fig, f)
TypeError: cannot pickle 'kiwisolver.Solver' object
```

### Expected outcome

The figure is pickled. Or, if this is actually not supported, a more informative error message should be thrown, like "Pickling figures with constrained_layout=True is not supported".

### Operating system

Ubuntu 18.04

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8.12

### Installation

conda

**Comment by anntzer** [comment]
Thanks for the report.  I can reproduce the issue on 3.4.3 but this seems to have been fixed on 3.5.0, so I'll close this; feel free to ping for reopen if that's still an issue.
