### ISSUE TITLE
[Bug]:  cannot reset label of axis to center

### ISSUE THREAD

**Issue by decacent** [matplotlib/matplotlib#21772]
### Bug summary

When I do once of setting xlabel of ylabel to left of right, it cannot reset label of axis to center any way.

### Code for reproduction

```python
if I do once:
ax.set_xlabel("my label",loc="left ") 
or:
ax.set_xlabel("my label",loc="right")
the following will have no any effect:
ax.set_xlabel("my label",loc="center")
```

### Actual outcome

No any output

### Expected outcome

reset the label to center 

### Operating system

win 10 x64

### Matplotlib Version

3.4.3 and 3.5

### Matplotlib Backend

Qt5, Qt6,

### Python version

3.9, 3,10

### Installation

pip

**Comment by jklymak** [comment]
Confirmed.  Note that if you do `set_xlabel('label', loc='left'); set_xlabel('label', loc='right');` it works, so "center" is being ignored.  This is an easy fix, so I'll mark as good first issue.  It just needs a fix in `set_xlabel` and `set_ylabel` and it requires a test in `test_axes.py`.

**Comment by sveneschlbeck** [comment]
@jklymak This seems to be just another ``elif`` clause in the function definition, right? Currently, the ``kwargs.update`` sets ``x=0`` for left, ``x=1`` for right. Should center then be ``x=2`` or should this be renumbered? I'm not sure if I understand this correctly...

**Comment by hansinahuja** [comment]
@sveneschlbeck The position is scaled from [0, 1] so it should be 0.5. There was also another error in set_ylabel() where `horizontalposition` was getting reset instead of `verticalposition`
Making a PR, hope I didn't step on your toes there!
