### ISSUE TITLE
[Bug]: Pandas plot does not accept Columns for `color` keyword

### ISSUE THREAD

**Issue by mosc9575** [matplotlib/matplotlib#21795]
### Bug summary

I tried to plot a scatterplot with different groups, with one color for each group. I thought is is enought to pass the name of the column to the `color`-keyword, but this throws an error:

 `ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not ['color']`.

### Code for reproduction

```python
import pandas as pd

df = pd.DataFrame({
 'A': {1: 6, 2: 2, 3: 1, 4: 8, 5: 6},
 'B': {1: 2, 2: 10, 3: 3, 4: 1, 5: 1},
 'pos': {1: 1, 2: 2, 3: 4, 4: 1, 5: 1},
 'color': {1: 'red', 2: 'blue', 3: 'green', 4: 'red', 5: 'red'}
})

df >>>
   A   B  color
1  6   2    red
2  2  10   blue
3  1   3  green
4  8   1    red
5  6   1    red


# s.plot(x='A', y='B', kind='scatter', color=s['color'].values)
df.plot(x='A', y='B', kind='scatter', color='color')
```

### Actual outcome

Right now I get an error:
 `ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not ['color']`.

### Expected outcome

I expect this figure, which was generated using the commented line 

```s.plot(x='A', y='B', kind='scatter', color=s['color'].values)```

![grafik](https://user-images.githubusercontent.com/68053396/143857872-f4b74b12-a808-4ed2-be55-46faf5951db4.png)

### Operating system

 Linux-5.10.0-8-amd64-x86_64-with-glibc2.31

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.7

### Jupyter version

6.4.4

### Installation

conda

**Comment by jklymak** [comment]
We don't maintain `df.plot`, so please take up with pandas.pydata.org.  Thanks!

**Comment by jklymak** [comment]
The issue could still be on our side, but if so, then please isolate it to work without pandas....

**Comment by mosc9575** [comment]
I opend a ticket [#44670](https://github.com/pandas-dev/pandas/issues/44670) in pandas and it looks like a misstake there. There is a working solution. Thank you again.

**Comment by mosc9575** [comment]
@jklymak I came back to this issue and I found out that [`scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) has the keyword `c` instead of `color` which is used in [`bar`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html). This seems like a inconsistency and not very intuativ (to mee). 

Since pandas trys to pass the keywords without any changes, the `c` keyword can be found in both libraries.

Is this a bug and should this issue be reopend?

**Comment by jklymak** [comment]
No this has been this way for many years, and changing has been discussed and rejected in the past.

**Comment by mosc9575** [comment]
Thanks for your response. In this case this is closed for me, too.
