### ISSUE TITLE
[Bug]: Slow speed on remote server

### ISSUE THREAD

**Issue by zxdawn** [matplotlib/matplotlib#21847]
### Bug summary

I tried to plot large datasets on a remote server connected by ssh. The speed is quite slow compared with that on my laptop. Note that it's just plotting and saving figures by executing the script in the terminal.

### Code for reproduction

```python
import time
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt 

import warnings
warnings.filterwarnings('ignore')

offset = -40 
lon = np.linspace(offset, 360 + offset - 1, 3000)
lat = np.linspace(-60, 60 + 1, 500)
state = np.random.RandomState(51423)
data = state.rand(len(lat), len(lon))

def pyplot_test():
    start = time.time()
    fig, ax = plt.subplots(figsize=(4,4), subplot_kw=dict(projection=ccrs.Stereographic()))
    ax.coastlines()
    ax.pcolormesh(lon, lat, data, cmap='viridis', transform=ccrs.PlateCarree())
    end = time.time()
    print('pyplot plot cost: ', end - start)
    fig.savefig('test_pyplot.jpg', dpi=300)
    save_end = time.time()
    print('pyplot save cost: ', save_end - end)

pyplot_test()
```

### Actual outcome

On the remote server:
```
pyplot plot cost:  13.034125566482544
pyplot save cost:  13.91758131980896
```

On my laptop:
```
pyplot plot cost:  2.2724406719207764
pyplot save cost:  1.7109076976776123
```

### Expected outcome

The speed of plotting on the remote server is as quick as the local one.

### Operating system

Ubuntu

### Matplotlib Version

3.5.0

### Python version

3.8.12

### Installation

conda

**Comment by jklymak** [comment]
I'll close this as there is not really any way we can help you debug this.  Reasons servers are slow vary, but can include slow disks, not enough RAM, other users using the server, etc etc.  You are better to take this up with your system administrators.  Thanks!

**Comment by zxdawn** [comment]
Find out! That was caused by the old version pf proj. In case anyone has a similar problem, please see [here](https://github.com/lukelbd/proplot/issues/306#issuecomment-985459623).
