### ISSUE TITLE
[Doc]: TypeError: set_ticks() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by thekswenson** [matplotlib/matplotlib#21854]
### Documentation Link

https://matplotlib.org/stable/gallery/images_contours_and_fields/image_annotated_heatmap.html

### Problem

I'm trying to run the example given at:  https://matplotlib.org/stable/gallery/images_contours_and_fields/image_annotated_heatmap.html

I get two different unrelated errors:

- TypeError: set_ticks() got an unexpected keyword argument 'labels'
- TypeError: unhashable type: 'slice'

### Suggested improvement

I'm not familiar enough with matplotlib to fix the issue.

### Matplotlib Version

3.3.4

**Comment by jklymak** [comment]
You are reading the docs for 3.5 but using 3.4.3.  Substitute 3.4.3 for stable in the link.
