### ISSUE TITLE
[Doc]: Remove example "prop_cycle property markevery in rcParams"

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#21863]
### Documentation Link

https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/markevery_prop_cycle.html

### Problem

This is basically a proof that a bug was fixed, but is not instructive as an example (and horrible from a visual perspective).

### Suggested improvement

Convert the code into a test.

A `@check_figures_equal` comparing rcParams prop-cycle vs. explicitly set via keyword should do.

### Matplotlib Version

3.5.0

**Comment by ojeda-e** [comment]
Can I help with this test @timhoffm? I'll be happy to give it a try. :)

**Comment by timhoffm** [comment]
Sure. You're welcome!
