### ISSUE TITLE
[Doc]: redirect-from directive appears broken?

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#21876]
### Documentation Link

https://matplotlib.org/devdocs/

### Problem

We have a number of `.. redirect-from::` directives that are supposed to create a redirect html in the old location.  That appears to have broken. 

ie. `doc/users/faq/troubleshooting_faq.rst` has a `.. redirect-from:: /faq/troubleshooting_faq` which is _supposed_ to make a file https://matplotlib.org/devdocs/faq/troubleshooting_faq.html that redirects to https://matplotlib.org/devdocs/users/faq/troubleshooting_faq.html  However that file is not being created and so far as I can see no error messages are being emitted.  

This is loaded from `doc/sphinxext/redirect_from.py`

### Suggested improvement

This should be fixed

### Matplotlib Version

main

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/pull/19686 broke the redirects, as noted by https://github.com/matplotlib/matplotlib/pull/19686#issuecomment-835246535, but it was never followed up on.

**Comment by QuLogic** [comment]
It's working again when I'm building 3.5.0 right now (though not for the original build). Possibly this is because I did/didn't run in parallel, I don't remember exactly.

**Comment by jklymak** [comment]
Interesting.  I think you must have run in parallel, because they don't work when not running in parallel (ahem, I think)

**Comment by QuLogic** [comment]
Yes, I think you're right; looking back in my command history, it does appear to be with `-j`.

**Comment by jklymak** [comment]
That seems like a good clue!  (BTW< there _must_ be a way to suppress building the API docs for testing via conf.py, but I am not sure what it is...
