### ISSUE TITLE
[MNT]: make axis labels of 3d axis anchor-rotate

### ISSUE THREAD

**Issue by baloe** [matplotlib/matplotlib#21878]
### Summary

Although visually centered to the corresponding axis, axis label text is by default actually left-aligned in exported svg figures:

```python
import matplotlib
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(3.5,3.5), dpi=80)
ax1 = fig.add_subplot(111, projection='3d')

fig.suptitle(f"matplotlib v{matplotlib.__version__}")

ax1.plot([1,1,10,10], [1,10,10,10], [1,1,1,10], marker="o")

ax1.set_xlabel('xlabel')
ax1.set_ylabel('ylabel')
ax1.set_zlabel('zlabel')

from matplotlib import rcParams
rcParams['svg.fonttype'] = 'none'
fig.savefig('figure.svg', format='svg')
```

`figure.svg` in Inkscape:  
![actual_behavior](https://user-images.githubusercontent.com/12622691/145075733-f79d3ba4-8e6c-4e3f-9ca8-807f0e4cf820.gif)

I find that this is a bit of a surprise for the less experienced user because the yaxis label in ordinary axes is actually centered.
Hence I would expect the following  outcome:

![expected_behavior](https://user-images.githubusercontent.com/12622691/145075792-cc0aa88d-6f9c-49f9-9c60-95ab5c45118d.gif)

Of course one can simply use 
```
ax1.set_xlabel('xlabel', rotation_mode='anchor')
ax1.set_ylabel('ylabel', rotation_mode='anchor')
ax1.set_zlabel('zlabel', rotation_mode='anchor')
```
to achieve the desired outcome, but 

### Proposed fix

I tend to think that making `rotation_mode='anchor'` the default for the labels of 3d axes would be more consistent, because this is how vertical labels are handled in ordinary 2d axes.

**Comment by baloe** [comment]
Ah one needs
```
ax1.set_xlabel('xlabel', rotation_mode='anchor')
ax1.set_ylabel('ylabel', rotation_mode='anchor')
ax1.set_zlabel('zlabel', rotation_mode='anchor')
```
I keep running into that one, https://github.com/matplotlib/matplotlib/issues/20784
sorry for the noise.

**Comment by oscargus** [comment]
The y-axis in 2D-plots use `rotation_mode='anchor'`, but not the x-axis.

This should be rather straightforward and I think it makes sense to get the svg-formatting capability if nothing else. Not sure if it will break anything else though...
