### ISSUE TITLE
[Doc]: rrulewrapper not included in API docs

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#21880]
### Documentation Link

https://matplotlib.org/devdocs/api/dates_api.html

### Problem

https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L982-L983 has no docstring and hence can't be referred to in the documentation from:
* https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L144
* https://github.com/matplotlib/matplotlib/blob/21ea3fb2bcebbbe3daa32e8dd3d14ce335355cea/examples/ticks/date_formatters_locators.py#L89

### Suggested improvement

Remove the reference https://github.com/matplotlib/matplotlib/blob/21ea3fb2bcebbbe3daa32e8dd3d14ce335355cea/examples/ticks/date_formatters_locators.py#L89 or add docstring for `rrulewrapper` (see https://github.com/matplotlib/matplotlib/pull/21874#issuecomment-988567232).

### Matplotlib Version

3.6.0.dev910+g505cdff57c

**Comment by ianhi** [comment]
Was this fixed by #21993 ?

**Comment by tacaswell** [comment]
Closed by #21993!

**Comment by StefRe** [comment]
@ianhi Actually this wasn't fixed at all, but I'm OK with closing this issue. I already wrote in my [comment](https://github.com/matplotlib/matplotlib/pull/21993#issuecomment-996724071) that PR #21993 pro forma added a docstring but it didn't address the issue #21880 in any way (maybe it's may fault not to have chosen a better title for this issue: the actual issue is that `rrulewrapper` is not documented in any meaningful way and hence cannot be referenced from examples or the documentation).

**Comment by tacaswell** [comment]
I changed the title and re-opened.
