### ISSUE TITLE
Improve logging for remote benchmarking/debugging

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#2190]
It would be nice to move to the built-in logging module and also reassess the kinds of things we are logging with an eye to:
- making it easier for users to provide something to the core team to more easily debug their problems
- do some basic profiling (such as framerate) to measure performance problems

**Comment by story645** [comment]
ties into #2188

**Comment by anntzer** [comment]
Move to logging is done as of 2.2.
Profiling is almost certainly better done by profiling tools...
