### ISSUE TITLE
[Bug]: EPS savefig messed up by 'figure.autolayout' rcParam on 3.5.0

### ISSUE THREAD

**Issue by alex180500** [matplotlib/matplotlib#21930]
### Bug summary

Setting 'figure.autolayout' to 'True' removes most of the EPS savefig.

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.rcParams['figure.autolayout'] = 'True'

plt.plot([1, 2, 3], [1, 2, 3], 'o-')
plt.title(r'$\sum_{i=0}^{\infty} x_i$ just a test')
plt.savefig('test2.eps', format='eps')
```

### Actual outcome

Actual image after being exported from gimp (300dpi)

![actual](https://user-images.githubusercontent.com/30732244/145681524-ace8a931-20c2-4fd3-86f7-4421e003b902.jpeg)

This is the EPS file:
https://we.tl/t-ka6aoUGxKm

### Expected outcome

Expect the image in ".eps" file like this.

![expected](https://user-images.githubusercontent.com/30732244/145681516-61387c50-b4d5-4e35-9658-12aab0383c7c.jpeg)

This is the EPS file:
https://we.tl/t-Q7WBPMwDcy

### Additional information

I found this bug by an accident while using a custom ".mplstyle" on Matplotlib 3.5.0
Seems like this rcParam `['figure.autolayout'] = 'True'` destroys about 2/3 of the eps file.
`plt.tightlayout()` seem to not affect the result, the bug happens only with this rcParam on the latest matplotlib version.

```py
import matplotlib.pyplot as plt

plt.plot([1, 2, 3], [1, 2, 3], 'o-')
plt.title(r'$\sum_{i=0}^{\infty} x_i$ just a test')
plt.savefig('test2.eps', format='eps')
```
This is the code for the expected outcome.

### Operating system

Windows

### Matplotlib Version

Bug present only on 3.5.0

### Matplotlib Backend

Qt5Agg

### Python version

Tested with 3.10 and 3.9

### Installation

conda

**Comment by jklymak** [comment]
I can confirm this, but I don't understand it.  If you instead do 

```python
import matplotlib.pyplot as plt

# plt.rcParams['figure.autolayout'] = 'True'
 
plt.figure(layout='tight')
plt.plot([1, 2, 3], [1, 2, 3], 'o-')
plt.title(r'$\sum_{i=0}^{\infty} x_i$ just a test')
plt.savefig('test2.eps', format='eps')
```

it works fine.  

If you use the rcParam and save as PDF it works fine.   So I'm not sure why the ps backend is doing something different.

**Comment by jklymak** [comment]
Same behaviour with `plt.rcParams['figure.constrained_layout.use'] = True`.

**Comment by alex180500** [comment]
Still not fixed in 3.5.1

**Comment by jklymak** [comment]
someone will have to dig into it before it gets fixed.

**Comment by QuLogic** [comment]
> ```python
> plt.figure(layout='tight')
> ```

I'm not sure how you got this to work, I see no appreciable difference in the file between the `rcParam` vs the parameter (i.e., both are broken).

**Comment by jklymak** [comment]
Oh good, I must have been mixing up files somehow.  Glad that it is consistent between the ways to set tight_layout...

**Comment by alex180500** [comment]
I've just tested it out and...

```py
plt.figure(layout='tight')
```

gives a broken result like with the `rcParam`.

But

```py
plt.tight_layout()
```

does not. 🤔

**Comment by shmilee** [comment]
> I've just tested it out and...
> 
> ```python
> plt.figure(layout='tight')
> ```
> 
> gives a broken result like with the `rcParam`.
> 
> But
> 
> ```python
> plt.tight_layout()
> ```
> 
> does not. thinking

Same here with version 3.5.1 in archlinux.
And some lines are lost at the end of broken eps, like `gsave`, `grestore` things:
```
 FontName currentdict end definefont pop
 end
 %%EndProlog
 mpldict begin
 68.4 288 translate
 475.2 216 0 0 clipbox
-gsave
-0 0 m
-475.2 0 l
-475.2 216 l
-0 216 l
-cl
-1.000 setgray
-fill
-grestore
-
-................ more lines
-
-gsave
-
-384.960000 50.672828 translate
-0.000000 rotate
-0.000000 0 m /T glyphshow
-grestore

 end
 showpage
```
