### ISSUE TITLE
[Bug]: Using matploblib plot crashes conda kernel

### ISSUE THREAD

**Issue by arjun-majumdar** [matplotlib/matplotlib#21938]
### Bug summary

I have Windows 10, conda 4.10.3 with Python 3.9.7 and dependencies

matplotlib-base==3.5.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
numpy==1.21.2
numpy-base==1.21.2 

(amongst other installed packages). When I try to create plots using matplotlib.pyplot:

### Code for reproduction

```python
plt.plot(...)
# OR-
plt.scatter(...)
plt.show()
```

### Actual outcome

```
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5 already initialized. OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

### Expected outcome

visualization

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Python version

3.9.7

### Installation

conda

[@tacaswell edited to add markup]

**Comment by tacaswell** [comment]
We do not directly do anything with openMP.  Given that the error refers to intel products, I assume that this is related to numpy and mkl.    From this information it is hard to determine exactly what (a full trackback may help), however I suspect that this is an installation issue.  I suggest you try the following:

 1. create a new conda enviroment and re-install everything from scratch.  If you have updated in place it is possible that you have ended up with an inconsistent set of packaging that link to different versions of mkl
 2. make sure you can import and use numpy
 3. add your other imports back in one by one until you find the two that have this conflict

Did you packages from from anaconda's default channel or from conda-forge?

I'm going to close this as there is nothing that we can do on the Matplotlib side to help you.  If you are still having trouble, can you follow up in https://discourse.matplotlib.org/c/community/install/13 ?
