### ISSUE TITLE
[Bug]: tkinter.TclError: couldn't open "matplotlib.ppm": no such file or directory

### ISSUE THREAD

**Issue by pkyuen34** [matplotlib/matplotlib#21940]
### Bug summary

I have the below intermittent error when making sublots, but strangely the error is gone after rerunning. Would anyone please advise what causes the error? Thank you.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
```

### Actual outcome

```python
Traceback (most recent call last):
  File "/mnt/share/saber/report.py", line 502, in save_figure
    fig, ax = plt.subplots()
  File "/opt/tljh/user/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1209, in subplots
    fig = figure(**fig_kw)
  File "/opt/tljh/user/lib/python3.7/site-packages/matplotlib/pyplot.py", line 545, in figure
    **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/opt/tljh/user/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 959, in new_figure_manager_given_figure
    icon_img = tk.PhotoImage(file=icon_fname, master=window)
  File "/opt/tljh/user/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/opt/tljh/user/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/tmp/_MEIFJXm2U/mpl-data/images/matplotlib.ppm": no such file or directory
```

### Expected outcome

![image](https://user-images.githubusercontent.com/96095009/145921302-a8f556e9-e2a5-4123-8628-bc7d612ed23a.png)

### Operating system

Ubuntu 18.04

### Matplotlib Version

3.1.3

### Matplotlib Backend

tkinter

### Python version

3.7.3

### Jupyter version

Jupyter Lab 2.1.4

### Installation

pip

[@tacaswell edited to add markup]

**Comment by tacaswell** [comment]
There are a bunch of things that are confusing about this report.  This error is failing to load the tk backend, but you report using the inline backend.

The other thing that confuses me is that it seems the install location is `/opt/tljh/user/lib/python3.7/`, but the icon is being loaded from `/tmp/_MEIFJXm2U/mpl-data/images/matplotlib.ppm`? 

This is also a very old version of Matplotlib, can you try updating?

**Comment by QuLogic** [comment]
The path is created using `rcParams['datapath']`, so it _could_ end up pointing to `/tmp` if that rcParam was changed.

**Comment by pkyuen34** [comment]
> There are a bunch of things that are confusing about this report. This error is failing to load the tk backend, but you report using the inline backend.
> 
> The other thing that confuses me is that it seems the install location is `/opt/tljh/user/lib/python3.7/`, but the icon is being loaded from `/tmp/_MEIFJXm2U/mpl-data/images/matplotlib.ppm`?
> 
> This is also a very old version of Matplotlib, can you try updating?

I am sorry that the backend used should be the built-in tkinter and I edited the additional information. Would you please explain to me what an "icon" is and what is the "matplotlib.ppm" file? I will try to update it later but since it involves a lot of users I do not want to do it unless I have to.

**Comment by pkyuen34** [comment]
> The path is created using `rcParams['datapath']`, so it _could_ end up pointing to `/tmp` if that rcParam was changed.

Thank you, let me check the default "datapath" value and see if it has been changed in the middle of the run.

**Comment by anntzer** [comment]
Not sure how relevant this is here, but _MEI tmpdirs typically come from pyinstaller.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/blob/4a3f033fdd9d55aeb712bc4254a8fcf5f759d66c/lib/matplotlib/backends/_backend_tk.py#L953-L964

That it is the relevant code.  We try to set the icon on the tk window to be our logo (rather than the default icon tk uses).  It should be finding https://github.com/matplotlib/matplotlib/blob/v3.1.3/lib/matplotlib/mpl-data/images/matplotlib.ppm .  If you can find that file and point `rcParamas['datapath']` at it, you may be able to get it working again (or drop that file where your system seems to be looking?).

If this is a centralized installation (not sure if "many users" means you are pushing out to many or have many hitting the same install environment) and you can not resolve this another way you can do the (slightly hacky) trick of just removing the offending lines (this is the moral equivalent of the down-stream packagers patching us). 

------

I'm inclined to close this as it is against a very old version of mpl, I think there are a couple of possible work-arounds, and I am 95% sure that this is due to a local installation issue.

**Comment by pkyuen34** [comment]
> https://github.com/matplotlib/matplotlib/blob/4a3f033fdd9d55aeb712bc4254a8fcf5f759d66c/lib/matplotlib/backends/_backend_tk.py#L953-L964
> 
> That it is the relevant code. We try to set the icon on the tk window to be our logo (rather than the default icon tk uses). It should be finding https://github.com/matplotlib/matplotlib/blob/v3.1.3/lib/matplotlib/mpl-data/images/matplotlib.ppm . If you can find that file and point `rcParamas['datapath']` at it, you may be able to get it working again (or drop that file where your system seems to be looking?).
> 
> If this is a centralized installation (not sure if "many users" means you are pushing out to many or have many hitting the same install environment) and you can not resolve this another way you can do the (slightly hacky) trick of just removing the offending lines (this is the moral equivalent of the down-stream packagers patching us).
> 
> I'm inclined to close this as it is against a very old version of mpl, I think there are a couple of possible work-arounds, and I am 95% sure that this is due to a local installation issue.

Thank you for the explanation. We found out that it is an issue of different versions of matplotlib used between the imported library packed by the PyInstaller (3.2.1) and the shell that's created to run the code (3.1.3). So essentially that error line is looking for matplotlib.ppm but in the library tmp folder it only has matplotlib_128.ppm.

We can close the issue, thank you.
