### ISSUE TITLE
[Bug]: Strange behavior with FuncAnimation

### ISSUE THREAD

**Issue by dentistfrankchen** [matplotlib/matplotlib#21949]
### Bug summary

generating wrong image

### Code for reproduction

```python
%matplotlib ipympl

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time

fig, ax = plt.subplots()

XX=[1,2,3]
YY=[2,4,6]
line, = ax.plot(XX,YY)

ax.set_xlim(-2,100)
ax.set_ylim(-2,100)

num=0

def init():
    line.set_ydata(YY)
    line.set_xdata(XX)
    return line,

def animate(i):
    '''while ii!=3:
        XX[ii]+=1
        ii+=1'''

    for ii in XX:
        ii+=1
    line.set_ydata(YY)
    line.set_xdata(XX)
    return line,

ani = animation.FuncAnimation(
    fig, animate,init_func=init,interval=50, blit=True, save_count=50) #interval is millisecond

plt.show()
```

### Actual outcome

I wanted a image that will change as time changes, however actually the image just doesn't change.

### Expected outcome

the line will move as time changes.

### Additional information

the fix is to replace the "for" sentence with while loop(the quoted part)

I do not know why. Something wrong with the for sentence?

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

ipympl

### Python version

3.8.1

### Jupyter version

3.0.16

### Installation

pip

**Comment by dentistfrankchen** [comment]
I forgot to mention that I am using jupyter inside vscode.

**Comment by jklymak** [comment]
Please take user help to https://discourse.matplotlib.org.  I dont' think you have a Matplotlib bug here.  Thanks for your understanding!

**Comment by dentistfrankchen** [comment]
There is INDEED a bug. Why the while part is working well and the for part can not?

**Comment by dentistfrankchen** [comment]
What i do not understand is:
the code:
ii=0
while ii!=3:
        XX[ii]+=1
        ii+=1'''

should work in the same way as:
for ii in XX:
        ii+=1

BUT now they are not working in the same way. Isn't this a bug?
