### ISSUE TITLE
[ENH]: Use `repr` instead of `str` in the error message

### ISSUE THREAD

**Issue by e5f6bd** [matplotlib/matplotlib#21959]
### Problem

I mistakenly supplied `"blue\n"` as the argument `c` for [`matplotlib.axes.Axes.scatter
`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib-axes-axes-scatter), then `matplitlib` claimed for illegal color name like this:

```
ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not blue
```

I was not aware that the argument actually contained a trailing newline so I was very confused. 

### Proposed solution

The error message would be nicer if it outputs user's input via `repr`.
For example, in this case the error message [here](https://github.com/matplotlib/matplotlib/blob/v3.5.1/lib/matplotlib/axes/_axes.py#L4230-L4232) can be easily replced with:

```python
                    raise ValueError(
                        f"'c' argument must be a color, a sequence of colors, "
                        f"or a sequence of numbers, not {c!r}") from 
```

so that we may now get an easy-to-troubleshoot error like this:

```
ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not "blue\n"
```

This kind of improvement can be applied to many other places.

**Comment by tacaswell** [comment]
Labeling this as a good first issue as this is a straight forward change that should not bring up any API design issues (yes technically changing the wording of an error message may break someone, but that is so brittle I am not going to worry about that).  Will need a test (the new line example is a good one!).

**Comment by tacaswell** [comment]
@e5f6bd If you are interested in opening a PR with this change, please have at it!

**Comment by e5f6bd** [comment]
@e5f6bd Thanks, but I'm a bit busy recently, so I'll leave this chance to someone else.

**Comment by not-so-rabh** [comment]
@tacaswell is it okay if I take this up?

**Comment by AnkitKumar2698** [comment]
If this issue has not been resolved yet and nobody working on it  I would like to try it

**Comment by story645** [comment]
Looks like #21968 is assessing this issue

**Comment by AnkitKumar2698** [comment]
yeah but the issue still open

**Comment by Cloverwave** [comment]
Working on this now in axes_.py,
future plans to work on this in _all_ files with error raising.

**Comment by Cloverwave** [comment]
Also converting f strings to template strings where I see them in raised errors
