### ISSUE TITLE
[Bug]: Funcanimation has some problem with vscode

### ISSUE THREAD

**Issue by dentistfrankchen** [matplotlib/matplotlib#21951]
### Bug summary

THIS IS NOT A POST FOR COMMUNITY HELP.

THIS IS A BUG REPORT.

PLEASE DO NOT CLOSE BEFORE REPLICATION.

### Code for reproduction

```python
%matplotlib ipympl

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time

fig, ax = plt.subplots()

XX=[1,2,3]
YY=[2,4,6]
line, = ax.plot(XX,YY)

ax.set_xlim(-2,100)
ax.set_ylim(-2,100)

num=0

def init():
    line.set_ydata(YY)
    line.set_xdata(XX)
    return line,

def animate(i):
    ii=0
    while ii!=3:
        XX[ii]+=1
        ii+=1

    '''for ii in XX:
        ii+=1'''
    line.set_ydata(YY)
    line.set_xdata(XX)
    return line,

ani = animation.FuncAnimation(
    fig, animate,init_func=init,interval=50, blit=True, save_count=50) #interval is millisecond

plt.show()
```

### Actual outcome

the pic do not move.

### Expected outcome

the pic should move.

### Additional information

use while instead of for can solve this problem.

### Operating system

windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

ipympl

### Python version

3.8.1

### Jupyter version

3.0.16

### Installation

pip

**Comment by dentistfrankchen** [comment]
Now the code runs well. However if you use the for loop i quoted, the bug will appear.

**Comment by dentistfrankchen** [comment]
In general, the while loop is working well, however the for loop is not.

**Comment by WeatherGod** [comment]
In the for-loop version, you are doing `ii+=1`. This does *not* update the
`XX` list in-place. Integers and floats are immutable in python, so doing
this only creates a new integer or float and assigns it to the variable,
completely losing its connection to the `XX` list. The same would happen if
`XX` was a numpy array.

In the while loop, the line is `XX[ii] += 1`, which will make a new integer
or float, but then explicitly assigns it back into the `XX` list.

I hope that clears it up for you.

**Comment by jklymak** [comment]
@dentistfrankchen this is not a general help with python forum.  Again please post to https://discourse.matplotlib.org and do not open duplicate reports.

**Comment by WeatherGod** [comment]
Agreed that is the better place to have handled this. And while discussing
the problem there, if it was discovered to be a bug with matplotlib, we
would have then opened a bug report here.
