### ISSUE TITLE
[Bug]: Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize

### ISSUE THREAD

**Issue by polaron-cao** [matplotlib/matplotlib#21950]
### Bug summary

This issue happen in matplotlib version 3.5.1 while it is ok in version 3.3.3

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
x = np.array(range(1, 1000))
y = x**2
for k in range(100):
    with PdfPages(f'test{k}.pdf') as pdf:
        for i in range(1000):
            plt.plot(x, y)
            pdf.savefig()
            plt.close('all')
            print(f'test{k} {i} finished!')
    print(f'test{k}.pdf finished!')
```

### Actual outcome

test0 0 finished!
test0 1 finished!
test0 2 finished!
test0 3 finished!
test0 4 finished!
test0 5 finished!
test0 6 finished!
test0 7 finished!
test0 8 finished!
test0 9 finished!
test0 10 finished!
test0 11 finished!
test0 12 finished!
test0 13 finished!
test0 14 finished!
test0 15 finished!
test0 16 finished!
test0 17 finished!
test0 18 finished!
test0 19 finished!
test0 20 finished!
test0 21 finished!
test0 22 finished!
test0 23 finished!
test0 24 finished!
test0 25 finished!
test0 26 finished!
test0 27 finished!
test0 28 finished!
test0 29 finished!
test0 30 finished!
test0 31 finished!
test0 32 finished!
test0 33 finished!
test0 34 finished!
test0 35 finished!
test0 36 finished!
test0 37 finished!
test0 38 finished!
test0 39 finished!
test0 40 finished!
test0 41 finished!
test0 42 finished!
test0 43 finished!
test0 44 finished!
test0 45 finished!
test0 46 finished!
test0 47 finished!
test0 48 finished!
test0 49 finished!
test0 50 finished!
test0 51 finished!
test0 52 finished!
test0 53 finished!
test0 54 finished!
test0 55 finished!
test0 56 finished!
test0 57 finished!
test0 58 finished!
test0 59 finished!
test0 60 finished!
test0 61 finished!
test0 62 finished!
test0 63 finished!
test0 64 finished!
test0 65 finished!
test0 66 finished!
test0 67 finished!
test0 68 finished!
test0 69 finished!
test0 70 finished!
test0 71 finished!
test0 72 finished!
test0 73 finished!
test0 74 finished!
test0 75 finished!
test0 76 finished!
test0 77 finished!
test0 78 finished!
test0 79 finished!
test0 80 finished!
test0 81 finished!
test0 82 finished!
test0 83 finished!
test0 84 finished!
test0 85 finished!
test0 86 finished!
test0 87 finished!
test0 88 finished!
test0 89 finished!
test0 90 finished!
test0 91 finished!
test0 92 finished!
test0 93 finished!
test0 94 finished!
test0 95 finished!
test0 96 finished!
test0 97 finished!
test0 98 finished!
test0 99 finished!
test0 100 finished!
test0 101 finished!
test0 102 finished!
test0 103 finished!
test0 104 finished!
test0 105 finished!
test0 106 finished!
test0 107 finished!
test0 108 finished!
test0 109 finished!
test0 110 finished!
test0 111 finished!
test0 112 finished!
test0 113 finished!
test0 114 finished!
test0 115 finished!
test0 116 finished!
test0 117 finished!
test0 118 finished!
test0 119 finished!
test0 120 finished!
test0 121 finished!
test0 122 finished!
test0 123 finished!
test0 124 finished!
test0 125 finished!
test0 126 finished!
test0 127 finished!
test0 128 finished!
test0 129 finished!
test0 130 finished!
test0 131 finished!
test0 132 finished!
test0 133 finished!
test0 134 finished!
test0 135 finished!
test0 136 finished!
test0 137 finished!
test0 138 finished!
test0 139 finished!
test0 140 finished!
test0 141 finished!
test0 142 finished!
test0 143 finished!
test0 144 finished!
test0 145 finished!
test0 146 finished!
test0 147 finished!
test0 148 finished!
test0 149 finished!
test0 150 finished!
test0 151 finished!
test0 152 finished!
test0 153 finished!
test0 154 finished!
test0 155 finished!
test0 156 finished!
test0 157 finished!
test0 158 finished!
test0 159 finished!
test0 160 finished!
test0 161 finished!
test0 162 finished!
test0 163 finished!
test0 164 finished!
test0 165 finished!
test0 166 finished!
test0 167 finished!
test0 168 finished!
test0 169 finished!
test0 170 finished!
test0 171 finished!
test0 172 finished!
test0 173 finished!
test0 174 finished!
test0 175 finished!
test0 176 finished!
test0 177 finished!
test0 178 finished!
test0 179 finished!
test0 180 finished!
test0 181 finished!
test0 182 finished!
test0 183 finished!
test0 184 finished!
test0 185 finished!
test0 186 finished!
test0 187 finished!
test0 188 finished!
test0 189 finished!
test0 190 finished!
test0 191 finished!
test0 192 finished!
test0 193 finished!
test0 194 finished!
test0 195 finished!
test0 196 finished!
test0 197 finished!
test0 198 finished!
test0 199 finished!
test0 200 finished!
test0 201 finished!
test0 202 finished!
test0 203 finished!
test0 204 finished!
test0 205 finished!
test0 206 finished!
test0 207 finished!
test0 208 finished!
test0 209 finished!
test0 210 finished!
test0 211 finished!
test0 212 finished!
test0 213 finished!
test0 214 finished!
test0 215 finished!
test0 216 finished!
test0 217 finished!
test0 218 finished!
test0 219 finished!
test0 220 finished!
test0 221 finished!
test0 222 finished!
test0 223 finished!
test0 224 finished!
test0 225 finished!
test0 226 finished!
test0 227 finished!
test0 228 finished!
test0 229 finished!
test0 230 finished!
test0 231 finished!
test0 232 finished!
test0 233 finished!
test0 234 finished!
test0 235 finished!
test0 236 finished!
test0 237 finished!
test0 238 finished!
test0 239 finished!
test0 240 finished!
test0 241 finished!
test0 242 finished!
test0 243 finished!
test0 244 finished!
test0 245 finished!
test0 246 finished!
test0 247 finished!
test0 248 finished!
test0 249 finished!
test0 250 finished!
test0 251 finished!
test0 252 finished!
test0 253 finished!
test0 254 finished!
test0 255 finished!
test0 256 finished!
test0 257 finished!
test0 258 finished!
test0 259 finished!
test0 260 finished!
test0 261 finished!
test0 262 finished!
test0 263 finished!
test0 264 finished!
test0 265 finished!
test0 266 finished!
test0 267 finished!
test0 268 finished!
test0 269 finished!
test0 270 finished!
test0 271 finished!
test0 272 finished!
test0 273 finished!
test0 274 finished!
test0 275 finished!
test0 276 finished!
test0 277 finished!
test0 278 finished!
test0 279 finished!
test0 280 finished!
test0 281 finished!
test0 282 finished!
test0 283 finished!
test0 284 finished!
test0 285 finished!
test0 286 finished!
test0 287 finished!
test0 288 finished!
test0 289 finished!
test0 290 finished!
test0 291 finished!
test0 292 finished!
test0 293 finished!
test0 294 finished!
test0 295 finished!
test0 296 finished!
test0 297 finished!
test0 298 finished!
test0 299 finished!
test0 300 finished!
test0 301 finished!
test0 302 finished!
test0 303 finished!
test0 304 finished!
test0 305 finished!
test0 306 finished!
test0 307 finished!
test0 308 finished!
test0 309 finished!
test0 310 finished!
test0 311 finished!
test0 312 finished!
test0 313 finished!
test0 314 finished!
test0 315 finished!
test0 316 finished!
test0 317 finished!
test0 318 finished!
test0 319 finished!
test0 320 finished!
test0 321 finished!
test0 322 finished!
test0 323 finished!
test0 324 finished!
test0 325 finished!
test0 326 finished!
test0 327 finished!
test0 328 finished!
test0 329 finished!
test0 330 finished!
test0 331 finished!
test0 332 finished!
test0 333 finished!
test0 334 finished!
test0 335 finished!
test0 336 finished!
test0 337 finished!
test0 338 finished!
test0 339 finished!
test0 340 finished!
test0 341 finished!
test0 342 finished!
test0 343 finished!
test0 344 finished!
test0 345 finished!
test0 346 finished!
test0 347 finished!
test0 348 finished!
test0 349 finished!
test0 350 finished!
test0 351 finished!
test0 352 finished!
test0 353 finished!
test0 354 finished!
test0 355 finished!
Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize

### Expected outcome

test0 0 finished!
test0 1 finished!
test0 2 finished!
test0 3 finished!
test0 4 finished!
test0 5 finished!
test0 6 finished!
test0 7 finished!
test0 8 finished!
test0 9 finished!
test0 10 finished!
test0 11 finished!
test0 12 finished!
...
...
...
test99.pdf finished!

### Operating system

Window10

### Matplotlib Version

3.5.1

### Python version

3.8.3

### Jupyter version

6.1.5

### Installation

pip

**Comment by jklymak** [comment]
Please try with `Agg` since you are not doing anything with Tk here?

**Comment by anntzer** [comment]
I cannot repro even when actually using tkagg.

**Comment by polaron-cao** [comment]
> Please try with `Agg` since you are not doing anything with Tk here?

I just wonder why it works for 3.3.3 but not for 3.5.1 as both version use TkAgg as backend

**Comment by jklymak** [comment]
It could be a memory issue, and 3.5.1 uses more memory somehow.  But regardless you shouldn't need a Tk here.

**Comment by tacaswell** [comment]
We made some changes to the way we managed the Tk event loop.  I suspect that what is happening is that even though you are closing the figures, there is still some object related to the GUI hanging around waiting for the event loop to spin to safely clean them selves up.  Eventually this leads to some sort of resource exhaustion.

While I'm sorry that this broke on you, I think the changes to how we handle the tk event loop are still correct (it fixed _other_ bugs),  using `Agg` should work on every version of Matplotlib, and you should get (marginally) better performance to boot!

As you are always saving pdf, you could also do `matplotlib.use('pdf')` which will give you another (marginal) speed up.

I'm going to close this as I do not think there is any action we can/will take on the Matplotlib side.

**Comment by polaron-cao** [comment]
> We made some changes to the way we managed the Tk event loop. I suspect that what is happening is that even though you are closing the figures, there is still some object related to the GUI hanging around waiting for the event loop to spin to safely clean them selves up. Eventually this leads to some sort of resource exhaustion.
> 
> While I'm sorry that this broke on you, I think the changes to how we handle the tk event loop are still correct (it fixed _other_ bugs), using `Agg` should work on every version of Matplotlib, and you should get (marginally) better performance to boot!
> 
> As you are always saving pdf, you could also do `matplotlib.use('pdf')` which will give you another (marginal) speed up.
> 
> I'm going to close this as I do not think there is any action we can/will take on the Matplotlib side.
Yes. I get 60% speed up with 'Agg' backend compared to default backend 'TkAgg' in matplotlib version 3.3.3.  Thanks!

**Comment by polaron-cao** [comment]
> We made some changes to the way we managed the Tk event loop. I suspect that what is happening is that even though you are closing the figures, there is still some object related to the GUI hanging around waiting for the event loop to spin to safely clean them selves up. Eventually this leads to some sort of resource exhaustion.
> 
> While I'm sorry that this broke on you, I think the changes to how we handle the tk event loop are still correct (it fixed _other_ bugs), using `Agg` should work on every version of Matplotlib, and you should get (marginally) better performance to boot!
> 
> As you are always saving pdf, you could also do `matplotlib.use('pdf')` which will give you another (marginal) speed up.
> 
> I'm going to close this as I do not think there is any action we can/will take on the Matplotlib side.

Yes. I got 60% speed up using backend 'Agg' compared to default backend 'TkAgg' with version 3.3.3. Thanks!

**Comment by tacaswell** [comment]
> It seems 'Agg' is still faster than 'pdf' backend.

I do not understand that, but this is why you benchmark because your guess at what is the bottle neck is always wrong ;)
