### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PerchunPak** [matplotlib/matplotlib#21960]
### Bug summary

Using Termux 0.117 (in play market there is deprecated version, see termux installation)

### Code for reproduction

```python
pip install matplotlib
```

### Actual outcome

This is really big log
https://pastebin.com/DeBBNT6q

### Expected outcome

Installed successful

### Operating system

Termux

### Matplotlib Version

3.5.1

### Python version

Python 3.10.1

### Installation

pip

**Comment by jklymak** [comment]
You are unable to build freetype because it looks like you do not have an acceptable compiler.  This is not a good forum for general install problems, so I'll close here.  Please follow up in https://discourse.matplotlib.org.  Thanks for your understanding.

**Comment by PerchunPak** [comment]
I already have clang and make, even more I have freetype. This was installed when I needed to compile Pillow.
```
~ $ pkg install clang make freetype                                         Checking availability of current mirror: ok                                 Hit:1 https://termux.mentality.rip/termux-main stable InRelease             Hit:2 https://packages.termux.org/apt/termux-games games InRelease          Hit:3 https://packages.termux.org/apt/termux-science science InRelease
Get:4 https://packages.termux.org/apt/termux-x11 x11 InRelease [7858 B]
Get:5 https://packages.termux.org/apt/termux-x11 x11/main aarch64 Packages [82.6 kB]
Fetched 90.5 kB in 5s (19.6 kB/s)
Reading package lists... Done                                               Building dependency tree... Done
Reading state information... Done
All packages are up to date.                                                Reading package lists... Done
Building dependency tree... Done
Reading state information... Done                                           clang is already the newest version (13.0.0-3).                             freetype is already the newest version (2.11.0).                            make is already the newest version (4.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by PerchunPak** [comment]
Fixed using `pkg install binutils` which install also command ld and other.
