### ISSUE TITLE
[Bug]: Regression: Setting alpha on legend handle changes patch color

### ISSUE THREAD

**Issue by wavexx** [matplotlib/matplotlib#21966]
### Bug summary

Bug #11702 seems to have reappeared: calling set_alpha on a legend handle causes the color of the patch in the legend to change in a filled area plot.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame({
    'sales': [3, 2, 3],
    'visits': [20, 42, 28],
    'day': [1, 2, 3],
})

df.plot.area(x='day')
legend = plt.legend()
for p in legend.get_patches():
    p.set_alpha(1)
```

### Actual outcome

![2021-12-15T173908](https://user-images.githubusercontent.com/1017726/146228281-75cf9850-27c2-4fca-b32a-8c21114199c8.png)

### Expected outcome

The patch for 'visits' should be orange.

### Additional information

This was working fine at least until mpl 3.3.4.

As for the previous workaround, calling set_facecolor(get_facecolor()) before calling set_alpha() works. I'm using legend.get_patches() here instead of iterating through the handles directly, but there's no difference.

### Operating system

Linux (debian unstable)

### Matplotlib Version

3.5.0

### Matplotlib Backend

Qt5Agg or agg

### Python version

3.9.9

### Jupyter version

n/a

### Installation

Linux package manager

**Comment by jklymak** [comment]
The test in #11703 is still in the code base and passing, so I'm not sure how this could still be a bug. Can you reproduce w/o pandas?  

```
def test_alpha_handles():
    x, n, hh = plt.hist([1, 2, 3], alpha=0.25, label='data', color='red')
    legend = plt.legend()
    for lh in legend.legendHandles:
        lh.set_alpha(1.0)
    assert lh.get_facecolor()[:-1] == hh[1].get_facecolor()[:-1]
    assert lh.get_edgecolor()[:-1] == hh[1].get_edgecolor()[:-1]
```

Is it something subtle about the difference between setting the handles and the patches?  It should be the same.

**Comment by wavexx** [comment]
On Wed, Dec 15 2021, Jody Klymak wrote:
> The test in #11703 is still in the code base and passing, so I'm not
> sure how this could still be a bug. Can you reproduce w/o pandas?

I briefly tried also the original code, but plt.hist() doesn't have this
issue. A simple line plot also seems to work.

This is the shortest repro I came up after reducing it.
Of note, is that pandas didn't change (using 1.3.4).

> Is it something subtle about the difference between setting the handles
> and the patches? It should be the same.

No, as written, they behave the same. I happened to use get_patches() in
this case, but I tested both.

**Comment by jklymak** [comment]
This seems like someone who is familiar with what pandas does w their legend needs to help sort this out.  I would suggest opening with them if there is no native matplotlib repo?

**Comment by tacaswell** [comment]
I do not expect them to be doing anything fancy, I think we just need to look at what the class of `Artist` is being used in the plot and what the type of the `Artist` in the handler is. 

I suspect we are just going to discover that there is another class that needs `update_from` updated.

**Comment by StefRe** [comment]
Has nothing to do with pandas, can reproduce it with mpl without pandas. I found the culprit. Will make a PR after checking if this issues shows some else too.
