### ISSUE TITLE
[Doc]: Clarify default capstyle

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#21979]
### Documentation Link

https://matplotlib.org/devdocs/api/_enums_api.html#matplotlib._enums.CapStyle

### Problem

The demo states that the default capstyle is `projecting`, which is true for `Line2D` but not for `PathPatch` (where the default is 'butt').

```
import matplotlib.pyplot as plt
import matplotlib as mpl

fig,ax = plt.subplots(figsize=(2,1), layout='constrained')

xx = [0, 1]
yy = [0, 0]
ax.plot(xx, yy, lw=12, color='tab:blue')
ax.plot(xx, yy, lw=1, color='black')
ax.plot(xx, yy, 'o', color='tab:red', markersize=3)
ax.add_patch(mpl.patches.PathPatch(mpl.path.Path([[0, 0],[1, 0]]), lw=20, color='C1'))
ax.set_axis_off()
```
![Figure_6](https://user-images.githubusercontent.com/19879328/146409515-77a44d73-2cae-4bc4-ab7c-c185cf035e83.png)

(see also https://stackoverflow.com/a/70381813/3944322)

### Suggested improvement

Change `(default)` to `(default for Line2D)` in https://github.com/matplotlib/matplotlib/blob/98115e9b5134f4c71dc196a56f6ed8df4737174a/lib/matplotlib/_enums.py#L171

### Matplotlib Version

3.5.0

**Comment by timhoffm** [comment]
If we mention the `Line2D` default, we should also mention the `PathPatch` default.

I'm undecided whether that's still reasonable in the plot or whether we should discuss defaults in a dedicated section. I tend to go with the latter.

Joinstyle is also different (#18597). While at it, it should be addressed in the same fashion.

**Comment by StefRe** [comment]
> whether we should discuss defaults in a dedicated section

maybe just document the default capstyle in `set_capstyle`:
https://github.com/matplotlib/matplotlib/blob/be354096b60a091a030ea4b2ed8868756343a435/lib/matplotlib/patches.py#L473-L475
https://github.com/matplotlib/matplotlib/blob/092f8330b4192410a0067f634a467a0b600cb1db/lib/matplotlib/collections.py#L632-L634
https://github.com/matplotlib/matplotlib/blob/092f8330b4192410a0067f634a467a0b600cb1db/lib/matplotlib/lines.py#L1343-L1346
https://github.com/matplotlib/matplotlib/blob/092f8330b4192410a0067f634a467a0b600cb1db/lib/matplotlib/lines.py#L1329-L1331

In addition to that we could determine the default `capstyle` programmatically in the demo, so that it's always up-to-date, even if one forgets about the demo when changing the default sometime in the future:
```
import matplotlib as mpl

fig = mpl.pyplot.figure(figsize=(4, 1.2))
ax = fig.add_axes([0.1, 0, 0.8, 0.8])
ax.set_axis_off()
ax.set(title='Cap style', ylim=(-.5, 1.5))

default_l2d = mpl.lines.Line2D([], []).get_solid_capstyle()
default_pp = mpl.patches.PathPatch(mpl.path.Path([[0, 0], [0, 0]])).get_capstyle().name

for x, style in enumerate(['butt', 'round', 'projecting']):
    if style == default_l2d == default_pp:
        default = '(default)'
    elif style == default_l2d:
        default = '(default for Line2D)'
    elif style == default_pp:
        default = '(default for PathPatch)'
    else:
        default = ''
    ax.text(x+0.25, 0.85, f'{style}\n{default}'.strip(), ha='center', va='center')
    xx = [x, x+0.5]
    yy = [0, 0]
    ax.plot(xx, yy, lw=12, color='tab:blue', solid_capstyle=style)
    ax.plot(xx, yy, lw=1, color='black')
    ax.plot(xx, yy, 'o', color='tab:red', markersize=3) 
```
![Figure_1](https://user-images.githubusercontent.com/19879328/146454522-bed4d622-3d14-4402-99d2-0332e8a24e88.png)

(the same for `joinstyle`)

**Comment by StefRe** [comment]
While making the example I noticed the following inconsistency: 
https://github.com/matplotlib/matplotlib/blob/be354096b60a091a030ea4b2ed8868756343a435/lib/matplotlib/patches.py#L485-L487 and
https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/lib/matplotlib/markers.py#L327-L328
return a `CapStyle` object while the other 3 methods return a string (i.e. `...capstyle.name`).  

Is this something a separate issue should be opened? (at least it should be documented which type is returned in each case).

**Comment by StefRe** [comment]
There's another exception (which is, however, correctly documented #13647):
https://github.com/matplotlib/matplotlib/blob/1535cdc3500762088e53178efc22956365dcdac7/lib/matplotlib/patches.py#L4277-L4282

**Comment by StefRe** [comment]
And the last one:
https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/lib/matplotlib/markers.py#L288

Also not documented:
https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/lib/matplotlib/markers.py#L249-L250

**Comment by StefRe** [comment]
In total we seem to have the following defaults (hope that I didn't overlook anything) :

- 'projecting' for `Line2D`
- 'round' for `FancyArrowPatch`
- 'butt' for all other

So maybe it's indeed not so good an idea to give the defaults in the demo but rather document them with their classes.
