### ISSUE TITLE
[Bug]: Working with PyQt5, the different import order will make different result.

### ISSUE THREAD

**Issue by MusYi** [matplotlib/matplotlib#21998]
### Bug summary

Working with PyQt5, the different import order will make different result.

- If import PyQt5 before import matplotlib, the program will run normally. 
- If import PyQt5 after import matplotlib, the program will riase `TypeError` at the method of `QLayout.addWidget`.

### Code for reproduction

```python
import sys

# program run correctly, if import PyQt5 here before import matplotlib
# from PyQt5.QtWidgets import QApplication, QVBoxLayout, QWidget 
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
# program will raise TypeError, if import import PyQt5 after import matplotlib
from PyQt5.QtWidgets import QApplication, QVBoxLayout, QWidget

if __name__ == "__main__":
    app = QApplication(sys.argv)
    # init figure
    fig = Figure()
    fig_canvas = FigureCanvas(fig)
    # init widget
    layout = QVBoxLayout()
    layout.addWidget(fig_canvas) # TypeError here, if import PyQt5 after import matlpotlib
    win = QWidget()
    win.setLayout(layout)
    # run
    win.show()
    sys.exit(app.exec())
```

### Actual outcome
```
TypeError
addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'FigureCanvasQTAgg'
  File "E:\CODE\Python\testroom.py", line 17, in <module>
    layout.addWidget(fig_canvas)
```

### Expected outcome

expect no TypeError

### Additional information

This Bug will not happen at the version v3.4.x of matplotlib.

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

Python 3.8.10

### Installation

pip

**Comment by QuLogic** [comment]
Both ways work fine for me; are you certain that Matplotlib loaded PyQt5 and not PySide2?

See [this explanation](https://matplotlib.org/stable/users/explain/backends.html#qt-api-usage), but the safest way to guarantee that Matplotlib loads the intended Qt wrapper is to import it first.

**Comment by MusYi** [comment]
Thanks, I got it.

I tried it in a new python environment which just install matplotlib and pyqt5, the program will run correctlly.

So I checked the python pip environment which cause the TypeError, it contains both pyqt5 and pyside6.

At that time the matplotlib automatically import pyside6, which will conflict with the later imported pyqt5 and generate an error.

Thanks again!

**Comment by QuLogic** [comment]
Ah yes, this would have broken in 3.5, because it added support for both Python wrappers of Qt6.

**Comment by tacaswell** [comment]
I am going to re-open this, even though you can work around this by changing the import order, we should not have that sort of brittleness.  I'm working on a PR to fix this.

**Comment by weversonmachado** [comment]
Obrigado!
