### ISSUE TITLE
[Bug]: matplotlib 3.3 changed how plt.hist handles iterables of zero-dimensional arrays.

### ISSUE THREAD

**Issue by jakevdp** [matplotlib/matplotlib#22016]
### Bug summary

matplotlib 3.3 changed how `plt.hist` handles iterables of zero-dimensional arrays. This has come up because JAX has no scalar type, and recently changed its iteration protocol to return zero-dimensional JAX arrays rather than numpy scalars (see https://github.com/google/jax/issues/8899). But note that this issue can be reproduced without JAX, and is a case where matplotlib changed its behavior between version 3.2.2 and version 3.3.0.

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
data = [np.asarray(i) for i in [1, 2, 2, 3, 3, 3, 4, 4, 5]]
plt.hist(data)
plt.title(f'matplotlib version={matplotlib.__version__}')
```

### Actual outcome

Outcome in matplotlib 3.2.2:
![download-4](https://user-images.githubusercontent.com/781659/146812602-21da7136-a59a-4734-92d1-1fc47c34075b.png)

Outcome in matplotlib 3.3.0:
![download-5](https://user-images.githubusercontent.com/781659/146812625-7b862a02-60ec-4ab2-a7e6-c99cd8de7460.png)

### Expected outcome

I expect that version 3.3.0 and later will produce the same chart as 3.2.2 and earlier.

### Matplotlib Version

3.3.0 and newer

### Python version

all Python versions

**Comment by shoyer** [comment]
JAX arrays can also be converted entirely into NumPy arrays via an `__array__` method.

Perhaps matplotlib used to use `__array__` array but then stopped, e.g., in an attempt at better support for duck typing?

**Comment by jakevdp** [comment]
No, the regression has nothing to do with JAX. The repro above only uses numpy.

This was introduced by #17821, I think, which incorrectly assumes that anything that satisfies `isinstance(x, collections.abc.Iterable)` is iterable.

**Comment by jklymak** [comment]
Matplotlib should do what we can to be compatible, but I hope there is a good reason for x being an instance of iterable, but not actually being iterable, because that is pretty inconsistent!

**Comment by jakevdp** [comment]
The reason for this mismatch is that the `isinstance` check depends on properties of the class (such as whether `__iter__` or `__len__` and `__getitem__` are defined), while actual iterability depends on properties of the instance. So there's no way, for example, for numpy to make zero-dimensional arrays return False for `isinstance(arr, Iterable)` without making **all** arrays evaluate to False.

It's generally true that checking for iterability vs `isinstance` checks is problematic for this reason (see e.g. https://stackoverflow.com/a/1952481)

**Comment by jklymak** [comment]
Sure I get that, but OTOH, I don't see why `iter(np.array(1))` can't just return `1` and then stop iterating.

**Comment by jakevdp** [comment]
I disagree with that, but that kind of breaking change is something that would be better discussed in a NEP.
