### ISSUE TITLE
[Bug]: CI doc build is broken

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#22015]
### Bug summary

Just as an FYI for developers, it looks like we're running into https://github.com/pypa/setuptools/issues/2938 with setuptools 60.0.0 in our circlCI doc build.

### Code for reproduction

```python
n/a
```

### Actual outcome

n/a

### Expected outcome

n/a

### Matplotlib Version

n/a

**Comment by tacaswell** [comment]
should we just ban that setuptools version?

**Comment by timhoffm** [comment]
+1 for banning, possibly also 60.0.1, see https://github.com/pypa/setuptools/issues/2938

**Comment by tacaswell** [comment]
There is now a 60.0.2 out so we may have taken the "just wait and it will fix it self" approach ;)

**Comment by QuLogic** [comment]
Waiting it out [appears to have worked](https://app.circleci.com/pipelines/github/matplotlib/matplotlib/13687/workflows/c87219a4-7d42-4b19-aaf9-a6895c305ddc/jobs/65660).
