### ISSUE TITLE
[Bug]: Mouseover coordinate/value text should be right aligned

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22012]
### Bug summary

Currently, when the mouseover coordinates/value text has two lines (typically when hovering over an imshow()):
- qt right aligns the text
- tk center aligns the text
- gtk and wx left aligns the text
- (I haven't checked for macos and jupyter)

Given that the text is shown at the right edge of the toolbar, I think right aligning looks better?  This is probably just a matter of passing the right flags to the widget constructors, hence labeling as good first issue.

### Code for reproduction

`from pylab import *; imshow([[1, 2]])` and mouseover with various backends.

### Actual outcome

Variable alignment depending on backend.

### Expected outcome

Consistent alignment.

### Operating system

arch linux

### Matplotlib Version

3.5.1

### Matplotlib Backend

all

### Python version

3.10

### Jupyter version

none

### Installation

git checkout

**Comment by gajendra0180** [comment]
Hey! I would like to fix this issue if nobody has yet started working on it.
Thanks.

**Comment by gajendra0180** [comment]
@anntzer 

> This is probably just a matter of passing the right flags to the widget constructors.

My apologies I am new to this project 😅 , I tried hard finding the files containing this "_widget constructors_" but not able to find. Can you please give a hint or direction as to where I can find it?

I have reproduced the bug on gtk,qt and tk.Attaching the screenshots for the same.
Thanks.

![gtk](https://user-images.githubusercontent.com/68333209/146926737-8c10aa5d-dd8c-48b3-be23-9de78dbfab98.png)
![qt](https://user-images.githubusercontent.com/68333209/146926750-33276b98-5b67-4bc5-affd-d332fa5048df.png)
![tk](https://user-images.githubusercontent.com/68333209/146926752-713876d9-dffa-4c47-8f84-f5714aa75151.png)

**Comment by gajendra0180** [comment]
Hey @anntzer can you help me a bit?

**Comment by anntzer** [comment]
Sorry, I'll be unavailable over the holidays period.

**Comment by huskhi** [comment]
hey! I would like to work this issue if it has been resolved and no one is working at it.

**Comment by gajendra0180** [comment]
Sure @huskhi

**Comment by oscargus** [comment]
I've opened a PR in #22110 (guessing that there may not come one from other sources).
