### ISSUE TITLE
Autoscale does not work for artists added with Axes.add_artist

### ISSUE THREAD

**Issue by hohlraum** [matplotlib/matplotlib#2202]
Adding an artist through Axes.add_artist() does not update the data limits of the plot, so autoscale does not work.

``` python
ax=gca()
circ = Circle((0,0), 5)

ax.add_patch(circ)   #autoscale works for this
#ax.add_artist(circ)  #autoscale does not work for this

ax.relim()  # not strictly necessary
ax.autoscale(True)
plt.show()

```

**Comment by tricostume** [comment]
Sorry just one question as completeness very related to this topic. How can I then paste an image at a specific position on a given axes (which also contains an image)? I mean I was using OffsetImage in combination with AnnotationBbox but I noticed their reference frames are independent and thus (e.g.) resizing only works for the outer axes. I need that both the image on the given axes and the image to be overlaid refer to the same pixels space.

**Comment by timhoffm** [comment]
Hm, wouldn't it be easier to merge the underlying pixel representations and update with the joint data using `AxesImage.set_data()`?
