### ISSUE TITLE
Allow negative radial grid values in polar.py

### ISSUE THREAD

**Issue by dtimson** [matplotlib/matplotlib#2203]
In PolarAxes.set_rgrids(), remove the test for rmin <= 0.

Explanation: while it is possible to plot negative values in a polar plot (e.g. antenna gain down to -30 dB, as a function of azimuth), placing radial grids at negative values is rejected, for no apparent reason.

**Comment by dstansby** [comment]
I think this is now fixed by #4699 @QuLogic ?

**Comment by QuLogic** [comment]
Yes, dunno why it wasn't tagged before.
