### ISSUE TITLE
[Bug]: invert_yaxis function cannot invert the "over value" in colorbar axes

### ISSUE THREAD

**Issue by PKUliubaojian** [matplotlib/matplotlib#22052]
### Bug summary

The "over value" and the "under value" of colormap are not correctly shown when using ax.invert_yaxis (invert_xaxis if the colorbar is horizontal) function.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
im=plt.imshow(np.arange(10000).reshape(100,100),vmax=9000,vmin=1000)
cb=plt.colorbar(im,extend='both')
cb.ax.invert_yaxis()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/31818986/147364868-31b36095-c446-401f-99fe-28b344e20c06.png)

### Expected outcome

The "over value" and the "under value" could be shown in the right location by the way. The "under value" is expected to be at the top, if the y axis is reverted.

If this is not a bug, would it be a feature?

### Operating system

CentOs

### Matplotlib Version

3.5.0

### Python version

3.9.7

**Comment by oscargus** [comment]
I played around to see if I could sort this out, but to no avail. However, I found another interesting aspects of this (that partly prevented me from fixing it).

There seem to be a fundamental difference between how the `colorbar` axes works and the images axes.

Executing
```
import numpy as np
import matplotlib.pyplot as plt
im=plt.imshow(np.arange(10000).reshape(100,100),vmax=9000,vmin=1000)
cb=plt.colorbar(im,extend='both')
```
leads to (obtained from `im.figure`)
![image](https://user-images.githubusercontent.com/8114497/147390165-d37c2fda-4f01-4359-a45e-0936b6775f4b.png)

Now, executing 
```
cb.ax.invert_yaxis()
```
leads to you result:
![image](https://user-images.githubusercontent.com/8114497/147390175-2ff29ffa-f578-47fb-9e1f-1ed99203fa64.png)

However, executing
```
im.changed()
```
will restore the image to the first.

This is as opposed to doing 
```
im.axes.invert_yaxis()
```
which leads to:
![image](https://user-images.githubusercontent.com/8114497/147390194-337326e1-cad9-44dc-ac21-6f6718e2c3ad.png)
and further `im.changed()` does not revert it.

I really have no idea how this is supposed to work, but it seems like this creates a bit of a problem. If nothing else that something reverts the `get_inverted()`-flag for the y-axis when calling update.

I'm thinking if it may be better to have a `reversed` keyword to the `colorbar`-command? This would make things a bit easier. But then, there may be people realizing how this should be changed "properly".

**Comment by jklymak** [comment]
First, did invert ever work with extends?  

Second, I don;t think the fix should be too hard. 

Third, "changed" is relatively new, so the semantics of linking the colorbar and mappable are probably still up for modulation.  However, ignoring changing the mappable for the moment, I think this should be an easy check for which end the extend triangles are put.

**Comment by oscargus** [comment]
You are probably correct that it is not that hard with a reasonable understanding of the code base. I tried out changing this:
https://github.com/matplotlib/matplotlib/blob/ac2a14581949bcf869e969f28a21ee479d2fc250/lib/matplotlib/colorbar.py#L649 to check if the long axis was inverted and then set the color based on that.

The "problem" is that this method is not called when `invert_yaxis()` is called (and I couldn't figure out exactly what caused the colors in the bar to flip).

**Comment by jklymak** [comment]
Colorbars were _very_ recently changed to be more like normal axes.  So invert_yaxis is just the normal axes method, which just sets the ylim to be inverted.  

I forget how the color of the over/under are set in the colorbar code, but we could maybe move that logic to draw time.  

However, I'm not sold on doing a _lot_ of surgery for this "feature".  I'm not sure why someone _really_ needs an inverted colorbar axes, and I don't think we have every allowed one.   So the value of adding this should be weighted against the complexity.

**Comment by aidanheerdegen** [comment]
I can provide an example where this is useful (and pretty common): bathymetry data, i.e. ocean "topography". It is usual for the surface to be 0m and depths expressed as positive numbers increasing with depth. In this case it makes sense to have an inverted colorbar with the option of an extend arrow, as it is common to adjust the displayed bathymetry levels, to better display bathymetric features.

The original error is reproduced below

![Screen Shot 2022-01-31 at 12 22 01 pm](https://user-images.githubusercontent.com/6063709/151727050-7da3f1e7-68ba-4657-9137-6ad125116253.png)
