### ISSUE TITLE
[Bug]: MPL using QtAgg breaks Tk

### ISSUE THREAD

**Issue by sausix** [matplotlib/matplotlib#22059]
### Bug summary

matplotlib.pyplot.figure() breaks tkinter.Scale while using `QtAgg` which is chosen implicitly on at least my system.
The **default backend** without explicitly calling `matplotlib.use` should **not** break tkinter.
MPL, Tk and Qt should be usable independently and of course platform independend.

### Code for reproduction

```python
# -*- coding: utf-8 -*-

import sys
import tkinter
import matplotlib
from matplotlib.pyplot import new_figure_manager, figure, Figure

print(sys.version)  # 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
print(matplotlib._get_version())  # 3.5.1


# matplotlib.use('QtAgg')   # Implicit default, breaks tkinter
# matplotlib.use('TkAgg')   # Fixes, but holds tk.mainloop()
# matplotlib.use('Agg')     # Fixes
print(matplotlib.get_backend())  # QtAgg


# Problematic call:
f = figure()  # <- If used, it breaks tk if (implicitly) using QtAgg backend

# Causing internal call below figure()
# fm = matplotlib.pyplot._backend_mod.new_figure_manager(1, figsize=None, dpi=None,
#                            facecolor=None, edgecolor=None, frameon=True,
#                            FigureClass=Figure)
# print(fm)  # <matplotlib.backends.backend_qt.FigureManagerQT object at 0x7f633fe09fc0>


def slide_event(data):
    # Normally prints with decimal point: 6.5 <class 'str'>
    print(data, type(data))


# Minimal Tkinter code with a Scale widget
r = tkinter.Tk()
slider = tkinter.Scale(r, from_=0., to=10., resolution=.5,  # resolution must be a fraction to avoid int mode
                       orient=tkinter.HORIZONTAL,
                       command=slide_event)

slider.pack()

# Setting any decimal
slider.set(6.5)  # slide_event prints decimal comma: 6,5 <class 'str'>

r.mainloop()
```

### Actual outcome

The tkinter.Scale gets **unresponsive** and calls its assigned command once with string argument "**6,5**" containing **decimal comma** propably due to localization (Germany)

It's a bug in my optinion because of inconsistent behaviour of a code snippet.

### Expected outcome

Tkinter should stay responsive and independent while MPL uses or may use Qt backend.

Some systems may not have a Qt or Tk backend. So there should not be a strict reqirement to determine a backend in the main program manually for each system. MPL should just choose the best option without breaking other things.

Others programmers also may spend hours to find such a bug like me in future.

### Additional information

Qt6 6.2.2-3

Fixes
`matplotlib.use('TkAgg')`   # Fixes, but holds tk.mainloop() forever
`matplotlib.use('Agg')`     # Fixes all, but is not default

Maybe the bug is more related to Tkinter.

### Operating system

Arch Linux (1 day after last update)

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

Python 3.10.1

### Jupyter version

Arch package manager (v3.5.1-1)

**Comment by jklymak** [comment]
You can't run two guis from the same thread and expect them both to be responsive. Our default GUI is a convenience, but it cannot I regratte itself post-facto with a GUI you open later. If you are going to open a gui toolkit manually you will have to embed matplotlib in it manually.

**Comment by anntzer** [comment]
This is basically the same as https://github.com/matplotlib/matplotlib/issues/6706, and is essentially due to a limitation in how qt & tk work (see discussion in linked issue, and other issues that link to it).
