### ISSUE TITLE
[Bug]: fail to setup on system freetype

### ISSUE THREAD

**Issue by wqh17101** [matplotlib/matplotlib#22068]
### Bug summary

FreeType version 2.3 or higher is required. You may unset the system_freetype entry in setup.cfg to let Matplotlib download it.
I got this when i am using freetype 2.10.4 to build
![image](https://user-images.githubusercontent.com/26429138/147740660-10c64be0-3b33-45aa-a4ee-1bc5bd933e7e.png)
![image](https://user-images.githubusercontent.com/26429138/147740743-03428738-534e-406e-89f9-979d9968bb27.png)

### Code for reproduction

```python
1. download freetype 2.10.4 and unzip to `build` dir
2. modify setup.cfg and set system_freetype=True
3. modify `LOCAL_FREETYPE_VERSION` in setupext.py to 2.10.4
4. python setup.py bdist_wheel
5. get the bug
```

### Actual outcome

build failed

### Expected outcome

build successfully

### Operating system

linux

### Matplotlib Version

3.4.3

### Python version

3.8.5

**Comment by jklymak** [comment]
System freetype does not allow matplotlib to download freetype.  Just the opposite, it uses your system freetype.  What version is your system freetype?

**Comment by wqh17101** [comment]
> System freetype does not allow matplotlib to download freetype. Just the opposite, it uses your system freetype. What version is your system freetype?

2.10.4

**Comment by wqh17101** [comment]
i fixed it by `export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig/:/usr/lib/pkgconfig/:/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH`  when build

**Comment by jklymak** [comment]
People get this error frequently when they do not have their library path setup correctly.  We prefer to help debug these sort of things at https://discourse.matplotlib.org

An actionable item here might be a better error message that says what version for freetype was found, or if no freetype was found.

**Comment by wqh17101** [comment]
Thank you for your help.
I found that there are two ways to build matplotlib with my own freetype. 
1. install my own freetype and export PKG_CONFIG_PATH and set system_freetype=True
2. copy the source code of my own freetype ot matplotlib/build and modify `LOCAL_FREETYPE_VERSION` in setupext.py to 2.10.4.
Both of this can work.

**Comment by tacaswell** [comment]
With option 1 we are actually linking against the pre-built freetype on your system.  With option 2 we are still building our own freetype but with a version that happens to match your system version.

**Comment by QuLogic** [comment]
> An actionable item here might be a better error message that says what version for freetype was found, or if no freetype was found.

The error message already includes the version of FreeType used. In this case, the FreeType header `ft2build.h` was found, but it is completely bogus, because it does not define any FreeType symbols (this would have expanded the version in the message).

There's not really anything we can do here if you have a broken installation.
