### ISSUE TITLE
[Bug]: Autopositioned title overlaps with offset text

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#22062]
### Bug summary

Autopositioned title overlaps with offset text of y axis.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([1e8, 2e8])
ax.set_title('Title', loc='left')
plt.show()
```

### Actual outcome

![old](https://user-images.githubusercontent.com/19879328/147657214-f312cb80-a06b-44ab-8678-0125209a1203.png)

### Expected outcome

Title would move to not overlap with offset text (as it is the case for a top x axis).

### Matplotlib Version

3.5.1

**Comment by dstansby** [comment]
I'm not 100% sure we guarantee that artists won't be overlapping by default. If you do `.tight_layout()` or `.constrained_layout()`, does the title still overlap with the offset text?

**Comment by StefRe** [comment]
Yes, title overlaps with both `layout='constrained'` and `layout='tight'`. The title is moved up (if `Axes._autotitlepos` is True) to not overlap with a top x axis, but an y axis offset text is currently not taken into account.
