### ISSUE TITLE
[Bug]: Memory leak with colorbar.make_axes

### ISSUE THREAD

**Issue by vdrhtc** [matplotlib/matplotlib#22085]
### Bug summary

When using `matplotlib.colorbar.make_axes` function, `plt.close()` does not clear the new colorbar axes from memory. Tested for the Qt5 backend only. Maybe related to #22002, at least in the sense that I see no leak for Qt5 when no colorbar axes are added.

### Code for reproduction

```python
%pylab qt5
from matplotlib import colorbar
import psutil
import gc

p = psutil.Process()
for i in range(5):
    fig, ax = plt.subplots(1,1)
    ax.imshow(random.normal(size=(100,100)))
    cax = colorbar.make_axes(ax)
    plt.savefig("test.png")
    plt.pause(0.1)
    plt.close(fig)
    del fig
    del ax
    del cax
    gc.collect()
    print(p.memory_full_info().uss/1e6)
```

### Actual outcome

250.744832
255.209472
259.514368
264.13056
268.099584

### Expected outcome

Constant memory usage, as is when the line
`    cax = colorbar.make_axes(ax)`
is commented out.

### Operating system

Windows

### Matplotlib Version

3.4.2

### Matplotlib Backend

Qt5Agg (PyQt)

### Python version

3.7.6

### Installation

from source (.tar.gz)

**Comment by vdrhtc** [comment]
Oh, also just found #22040, probably mine is a duplicate.

**Comment by jklymak** [comment]
Perhaps also test the latest matplotlib.  There were substantial changes to colorbar for 3.5. FWIW, I don;t know what make_axes is supposed to do in your code.

**Comment by jklymak** [comment]
OK, I can confirm this when `make_axes` is used.  When `make_axes_gridspec` is used, there is no memory leak.

**Comment by jklymak** [comment]
If I insert
```python
...
    del ax 
    del cax._colorbar_info
    del cax
...
```

then the memory leak goes away.  

This is defined in `make_axes` 👍

**Comment by vdrhtc** [comment]
Yes, I found that grid spec helps, too, thank you!

**Comment by jklymak** [comment]
The culprit is `parents = np.atleast_1d(parents).ravel()`.  If I get rid of this, no memory leak.  However, this is needed, and I am not sure why it leaks.

**Comment by vdrhtc** [comment]
@jklymak Thank you very much!
