### ISSUE TITLE
[Bug]: NavigationToolbar2WxAgg set_message Bug

### ISSUE THREAD

**Issue by randytbushman** [matplotlib/matplotlib#22086]
### Bug summary

When the cursor moves around the plot, it is supposed to update the text in the toolbar with the current coordinates. Instead, the text appears mostly off-screen to the right with this backend.

### Code for reproduction

```python
import wx
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar
from matplotlib.figure import Figure


class MainFrame(wx.Frame):
    def __init__(self):
        super().__init__(parent=None, title='Debugging')
        panel = GraphPanel(self)
        self.Show()


class GraphPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent=parent, style=wx.SUNKEN_BORDER)
        canvas = FigureCanvas(self, -1, Figure())
        canvas.SetMinSize(wx.Size(1, 1))
        NavigationToolbar(canvas)
        figure = canvas.figure
        axes = figure.add_subplot(111)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(canvas, 1, wx.EXPAND)
        sizer.Add(canvas.toolbar, 0, wx.EXPAND)
        self.SetSizer(sizer)

        self.Fit()


if __name__ == '__main__':
    app = wx.App()
    frame = MainFrame()
    app.MainLoop()
```

### Actual outcome

![BugReport](https://user-images.githubusercontent.com/72278417/147889152-4e9b0f08-2a6b-47fd-95f1-b7837b36c75b.png)

### Expected outcome

The red box in the lower right-hand corner represents the text. The text should not appear off-screen and should appear more toward the right. 

### Additional information

One hacky solution is to call Realize() after set_message is called. This causes the text to flicker, however.

Another hacky solution is to add another stretchable space, tool, or control to the toolbar. 

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

WXAgg

### Python version

3.8

### Installation

pip

**Comment by anntzer** [comment]
I think this is the same issue as #22014 so let's continue the discussion there; still, thanks for the report :)
