### ISSUE TITLE
[Doc]: No documentation on ArtistList

### ISSUE THREAD

**Issue by sdbbs** [matplotlib/matplotlib#22094]
### Documentation Link

https://matplotlib.org/stable/search.html?q=artistlist

### Problem

I tried looking for `Axes.ArtistList` (for me, due to bug 22093), but nothing is returned at this time:

![image](https://user-images.githubusercontent.com/48317456/147933345-a47bcfbb-efc4-4f8e-ab7b-94f89ebe0ccb.png)

### Suggested improvement

I'm assuming a lot of the documentation is autogenerated, so maybe it will also be possible to add some documentation, also about `ArtistList`?

### Matplotlib Version

3.5.0+

**Comment by soma2000-lang** [comment]
@sdbbs  I would like to work on this issue. Please assign me this.

**Comment by jklymak** [comment]
@soma2000-lang we don't "assign" issues typically.  Just put in a PR if you put one together.  Please see https://matplotlib.org/stable/devel/index.html and feel free to drop in on gitter.

**Comment by timhoffm** [comment]
@soma2000-lang Sorry to have taken up this issue, but in addition to adding ArtistList to the docs, it needed some clarification in it's documentation. That would have been more cumbersome to communicate than to just write up. I hope you find other interesting issues to work on and we'll see you again.
