### ISSUE TITLE
[Bug]: imshow extents can't have units?

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#22105]
### Bug summary

imshow extents cannot be expressed with units.

### Code for reproduction

```python
fig, ax = plt.subplots()
dates = np.arange("2020-01-01","2020-01-10 23:00", dtype='datetime64[h]')
ys = np.random.random(dates.size)
arr = np.random.random((10, 10))

ax.imshow(arr, extent=[dates[0], dates[1], 0, 10])
```

### Actual outcome

```
Traceback (most recent call last):
  File "/Users/jklymak/matplotlib/testImshow.py", line 12, in <module>
    ax.imshow(arr, extent=[dates[0], dates[1], 0, 10])
  File "/Users/jklymak/matplotlib/lib/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/__init__.py", line 1413, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_axes.py", line 5504, in imshow
    im.set_extent(im.get_extent())
  File "/Users/jklymak/matplotlib/lib/matplotlib/image.py", line 955, in set_extent
    self.axes.update_datalim(corners)
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_base.py", line 2477, in update_datalim
    if not np.any(np.isfinite(xys)):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Expected outcome

the extents are passed through the units machinery....

### Matplotlib Version

master

**Comment by tacaswell** [comment]
Labeling this as "good first issue" because there in no API choices to be made here, we already have strong conventions for how we handle data with units so it is good for someone new to Matplotlib.  However, this issue will require understanding how we handle input with units so you should be comfortable exploring the Matplotlib codebase.  The logic in `set_xlim` and `set_ylim` is probably a good place to copy off of.

**Comment by Huntersoulz** [comment]
@tacaswell  This is my first time contributing. Can i take up this issue?

**Comment by jklymak** [comment]
We don't usually assign, so unless there is a linked PR, feel free to contribute.  https://matplotlib.org/stable/devel/index.html  Thanks

**Comment by Dhruv454000** [comment]
can you help with expected output?

**Comment by mylasem** [comment]
@tacaswell I see that this issue is still open so I am going to give it a try.

**Comment by jklymak** [comment]
I believe #22230 is still active.  Please work with the author of that PR if you would like to help fix this.  Thanks!

**Comment by WarrenWeckesser** [comment]
FYI: This stackoverflow quesiton looks like an instance of this issue: https://stackoverflow.com/questions/72993532/datetime64-values-ufunc-isfinite-not-supported-for-the-input-types
