### ISSUE TITLE
[Bug]: png icon image fails to load for manually defined tool buttons

### ISSUE THREAD

**Issue by bobeldering** [matplotlib/matplotlib#22131]
### Bug summary

The ToolBase class has the interface of overriding the property 'image' containing the path to an image file to be displayed as the icon of the tool button:
https://matplotlib.org/stable/api/backend_tools_api.html#matplotlib.backend_tools.ToolBase.image
This image fails to load on Qt5 backends for PNG image files.

### Code for reproduction

```python
import matplotlib
matplotlib.use("Qt5Agg")
matplotlib.rcParams["toolbar"] = "toolmanager"
from matplotlib.backend_tools import ToolToggleBase
import matplotlib.pyplot as plt

class ExampleToolToggle(ToolToggleBase):
    image = "/tmp/example.png"

figure, axis = plt.subplots()
tool_manager = figure.canvas.manager.toolmanager
tool_manager.add_tool("example", ExampleToolToggle)
toolbar = figure.canvas.manager.toolbar
toolbar.add_tool(tool_manager.get_tool("example"), "zoompan", 0)
plt.show()
```

### Actual outcome

The name of the tool is displayed instead of the image in the toolbar.

### Expected outcome

The image displayed in the toolbar.

### Additional information

This bug was introduced in version 3.3.0 (3.2.2 works fine). 
The problem is caused by ToolbarQt calling the _icon method of NavigationToolbar2QT at:
https://github.com/matplotlib/matplotlib/blob/710fce3df95e22701bd68bf6af2c8adbc9d67a79/lib/matplotlib/backends/backend_qt.py#L924

The _icon method unconditionally changes the path by inserting '_large' before the '.png' suffix:
https://github.com/matplotlib/matplotlib/blob/710fce3df95e22701bd68bf6af2c8adbc9d67a79/lib/matplotlib/backends/backend_qt.py#L680

Before version 3.3.0 a _icon method of ToolbarQt itself was called, which didn't have the path mangling.

### Operating system

Ubuntu

### Matplotlib Version

3.5.1

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8.12

### Installation

pip

**Comment by oscargus** [comment]
Should be possible to use `isNull` to check if the `QPixMap` exists and if not use the original file name. 

https://doc.qt.io/qtforpython-5/PySide2/QtGui/QPixmap.html#PySide2.QtGui.PySide2.QtGui.QPixmap.isNull

**Comment by timhoffm** [comment]
Thanks for the hint! It's even easier to check the file existence directly in python.

**Comment by oscargus** [comment]
Yeah, your are correct. Your fix is clearly better than using `isNull` (except for the case that `*_large.png` exists, but is not a valid png, but nothing I had in mind when suggesting it.)
