### ISSUE TITLE
[MNT]: update default branch for codecov

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#22178]
### Summary

Codecov still shows coverage using master as default branch (although the link points to main).

### Proposed fix

See https://github.com/statsmodels/statsmodels/issues/7424 for how to fix it.

**Comment by dopplershift** [comment]
This should be done now. Please re-open if you find there's still something wrong.

**Comment by oscargus** [comment]
Looks great! Thanks!

**Comment by tacaswell** [comment]
Sorry I missed this when we did the branch rename.  I got everything in the repo but did not think to look for configuration that was stored outside of the repo.
