### ISSUE TITLE
scatter plot with extreme small alpha

### ISSUE THREAD

**Issue by tliu1023** [matplotlib/matplotlib#22227]
### Bug summary

I need to plot a scatter plot to represent the correlation between x & y. data size is about 5e6. so I choose an extremely small alpha value to let the color focus on the line y=x, but the scatter plot disappear when alpha<=0.001.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt


gt = np.random.uniform(size=5000000)
pred = gt + np.random.uniform(-0.1, 0.1, size=5000000)
fig1 = plt.figure()
ax1 = fig1.add_subplot(111)
ax1.scatter(gt, pred, s=5, zorder=10, facecolors='none', edgecolors='k', alpha=0.001)
ax1.plot([0,1], [0,1], 'r-', alpha=0.75, zorder=20, linewidth=3)
ax1.set_aspect('equal')
ax1.set_xlim((0., 1))
ax1.set_ylim((0., 1))
ax1.set_xlabel("Ground Truth")
ax1.set_ylabel("Prediction")
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/52925480/149394456-730c8198-8cbb-4469-927f-e07621b3350b.png)

### Expected outcome

it should come with the scatter point.

### Operating system

OS/X

### Matplotlib Version

3.3.1

### Matplotlib Backend

MacOSX

### Python version

Python 3.6.9

### Installation

pip

**Comment by anntzer** [comment]
alpha values are rounded to the nearest 1/256th, so 0.001 gets rounded to zero.  There's support for unrounded alphas ("floating point surfaces") in mplcairo (https://github.com/matplotlib/mplcairo), but it seems unlikely the agg-\* backends will ever support that.
Suggesting to close as can't fix, although we *could* consider expanding the docs on this topic.
