### ISSUE TITLE
[ENH]:  Suppress The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

### ISSUE THREAD

**Issue by fteufel** [matplotlib/matplotlib#22226]
### Problem

I have a script that allows the user to specify the format of the plots that are generated. This is very straightforward as it only requires changing the `format` argument in `fig.savefig()`. However, `format="eps"` triggers this message:
```
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
```
The warning is of course totally fine, but I am looking for a way to suppress it as it does not matter to the user. I tried `warnings.filterwarnings( "ignore")` without luck. Is there a way to suppress this message?

**Comment by anntzer** [comment]
You should be able to control this with https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.set_loglevel
