### ISSUE TITLE
Provide links to API docs in examples

### ISSUE THREAD

**Issue by drevicko** [matplotlib/matplotlib#2222]
It would be very useful to provide links to matplotlib API docs for methods/objects/etc.. used in examples. This could be a part of [MEP12](https://github.com/matplotlib/matplotlib/wiki/MEP12).

An intuitive approach could be to automatically render links in displayed code. If that sort of thing is not already in Sphynx, I guess I'm suggesting a sphynx extension (and should go over there to suggest it ;) 

Some (not so good) alternatives could be to associate links to API docs with certain tags or to include a few hand-coded links in each example page. Not so good as it would be incomplete (many methods/... used would not be linked) and would lead to inconsistencies (some examples much better linked than others).

**Comment by petehuang** [comment]
This would still be useful, and a Sphinx extension would be nice, but wondering if it would ever get done. Could turn this into a larger doc project.

**Comment by tacaswell** [comment]
@NelleV is this something sphinx-gallery can already do?

**Comment by dopplershift** [comment]
Yes, though in brief attempts I've not made it work for my own stuff. See for example:
https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py

**Comment by tacaswell** [comment]
Tagged as new-contributor friendly as this is self-contained from the rest of the library, but hard as it involves learning how to write / modify sphinx extensions

**Comment by NelleV** [comment]
Yes, that feature is in sphinx-gallery

**Comment by NelleV** [comment]
@tacaswell is the ticket to migrate to sphinx gallery or to reimplement the feature ? If it is to migrate to sphinx-gallery, we already have a ticket opened.

**Comment by petehuang** [comment]
@NelleV Wow this is cool!

I believe this is to migrate; sounds like we want the examples to look like this https://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py

**Comment by choldgraf** [comment]
This issue is now taken care of with the migration to sphinx-gallery. There are still some kinks to work out, but the general functionality is there and should be spot-checked with subsequent issues / PRs. I think we should close this

**Comment by WeatherGod** [comment]
Agreed, closing.
