### ISSUE TITLE
[Bug]: can't use matplotlib

### ISSUE THREAD

**Issue by lucianadelcastillo** [matplotlib/matplotlib#22252]
### Bug summary

Matplotlib is written like shit. You should choose some proper naming conventions and give structure to your mess.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

def box(n):
    path = np.concatenate([np.linspace(-0.1, -0.1 + 0.1j, 10),\
                           np.linspace(-0.1 + 0.1j, -np.pi * n + 0.1j, 30 * n),\
                           np.linspace(-np.pi * n + 0.1j, -np.pi * n - 0.1j, 20),\
                           np.linspace(-np.pi * n - 0.1j, -0.1 -0.1j, 30 * n),\
                           np.linspace(-0.1 - 0.1j, -0.1, 10)])
    return path

def animate_path(path):
    fig = plt.figure()
    ax = plt.axes(xlim=(min(np.real(path)) - 1, max(np.real(path) + 1)),\
                        ylim=(min(np.imag(path)) - 1, max(np.imag(path) + 1)))
    xdata = []
    ydata = []
    def init(): 
        # creating an empty plot/frame 
        line.set_data([], [], lw=3) 
        return line, 
    def update(n):
        xdata.append(np.real(path[n-1]))
        ydata.append(np.imag(path[n-1]))
        line.set_data(xdata, ydata)
        return line,
    anim = animation.FuncAnimation(fig, update, init_func=init, frames=len(path), interval=20, blit=True)
    return anim       
        
box3 = box(3)
#plt.plot(np.real(box3), np.imag(box3))
anim=animate_path(box3)
HTML(anim.to_html5_video())
```

### Actual outcome

Spaghetti with shit

### Expected outcome

An easy to use library

### Matplotlib Version

all

**Comment by jklymak** [comment]
Unfortunately this is a little too general to be actionable.  If you have specific suggestions for improvement (that won't also break thousands of users) please fill out a new more specific request

Finally invectives are against our code of conduct so please use professional language in future issues and PRs.  

We do hope you learn to enjoy Matplotlib. Suggest you start with our usage guide on the main docs page. If there is anything mystifying in there please reach out ah discourse.matplotlib.org. Thanks!

**Comment by tacaswell** [comment]
This is not a constructive issue and in clear violation of our Code of Conduct https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md#our-standards .
