### ISSUE TITLE
[Bug]: Can NOT save images in full-screen/maximized window.

### ISSUE THREAD

**Issue by ZhengdiYu** [matplotlib/matplotlib#22267]
### Bug summary

With plt.get_current_fig_manager().window.showMaximized(), I can get a maximized window in viewer, which relatively  has a better quality than the default window. 

However when I call plt.savefig(), it still saves a degenerated version, which is not full-screen. **It's **NOT** something related to dpi or resolution**. **It's a fundamental difference, It's more than a problem of resolution and dpi**. Having the same resolution and dpi just results in a 'enlarged' default image, which has worse and coarse quality than full-screen version. :

The only thing I can come up with is to adjust the dot size and line width when the window size change. However, it's also not practical for us to do so. We need a way to save the image directly in the way it is in the full-screen view. I have no idea why this would be so difficult as it's already there.

Fullscreen image:
![image](https://user-images.githubusercontent.com/63605407/150186013-3724f1a5-5b38-4f87-9513-b38d14e39f79.png)

Saved image (default size, which is not fullscreen):
![image](https://user-images.githubusercontent.com/63605407/150187097-d2bac91c-6910-41ff-8508-aa050e6bbe11.png)

As you can see, the coordinate scale are even different. It's more than a problem of resolution and dpi.

How can I save the first one. It is impossible to save hundreds of images by clicking on the 'save as' button on the window.

The only thing I can come up with is to adjust the dot size and line width when the window size change. However, it's also not practical for us to do so. We need a way to save the image directly in the way it is in the full-screen view. I have no idea why this would be so difficult as it's already there.

### Code for reproduction

```python
Sorry I can't give you exactly the same code as the pictures. But I think the problem is very clear and it's definitely not an issue of my code. We can get a similar issue using any data:
import numpy as np
import matplotlib.pyplot as plt


np.random.seed(19680801)


N = 50
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area = (30 * np.random.rand(N))**2  # 0 to 15 point radii

plt.scatter(x, y, s=area, c=colors, alpha=0.5)

plt.title("RUNOOB Scatter Test")

plt.show()
plt.savefig('1.png')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/63605407/150188678-27c74c2a-b222-455a-8630-4a3e6d6f132f.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/63605407/150188632-330abc0f-a849-4f26-bcad-a614fbb61c09.png)

### Additional information

All the answer I found before were saying either 'plt.get_current_fig_manager().window.showMaximized()' or change the dpi and resolution. However **NONE** of them are even related to this BUG. 

If it's not a bug, I think this should be updated. It's really not practical for people to spend several hours to save the figures one by one.

### Operating system

Windows10

### Matplotlib Version

3.3.2

### Matplotlib Backend

Qt5Agg

### Python version

3.6

### Installation

pip

**Comment by jklymak** [comment]
As you have found, `savefig` creates a new canvas.  When it does so, it knows nothing about the state of your other canvases, and creates a new one.  How big is that canvas?  If it is a raster backend, it is width * dpi by height * dpi, where width and height are set by `fig.set_size_inches` (or when you create the figure initially) and by the dpi which you can set via `fig.set_dpi()` or when you call `savefig`.  Again this new canvas doesn't care what you did in the GUI to another canvas.

If you want a big figure you need to call `fig.set_size_inches`.  

I suppose you could request that changing the GUI changes the underlying figure size, but that would be a huge breaking change for most folks, so you'd need to propose an API to make that optional.  

You may also have suggestions for where we may have made this more clear.

**Comment by ZhengdiYu** [comment]
> As you have found, `savefig` creates a new canvas. When it does so, it knows nothing about the state of your other canvases, and creates a new one. How big is that canvas? If it is a raster backend, it is width * dpi by height * dpi, where width and height are set by `fig.set_size_inches` (or when you create the figure initially) and by the dpi which you can set via `fig.set_dpi()` or when you call `savefig`. Again this new canvas doesn't care what you did in the GUI to another canvas.
> 
> If you want a big figure you need to call `fig.set_size_inches`.
> 
> I suppose you could request that changing the GUI changes the underlying figure size, but that would be a huge breaking change for most folks, so you'd need to propose an API to make that optional.
> 
> You may also have suggestions for where we may have made this more clear.

Thanks for your quick apply. 

However, I have already tried what you said. It just yields a larger picture with higher resolution. But still with bad quality and less detailed than the full-screen version, as you can see in my supplementary picture above. A larger picture is not what I want. I just want it to be as detailed as in the full screen mode. When I set_size_inches / dpi / or something else. It's still messed up (points knocking each other)

**Comment by jklymak** [comment]
Please make a reproducible example that shows the problem.  Your code above does _not_ set the figure size nor change the dpi of the saved figure

**Comment by jklymak** [comment]
For instance, here is the result of 

```python
fig, ax = plt.subplots(figsize=(17,10))
ax.scatter(x, y, s=area, c=colors, alpha=0.5)
ax.set_title("RUNOOB Scatter Test")
fig.savefig('test.png', dpi=200)
```
![Test](https://user-images.githubusercontent.com/1562854/150212962-727355fb-30f0-4c7b-86ed-aafab971116b.png)

**Comment by timhoffm** [comment]
Closing due to lack of feedback. Please report back with a reproducible example if the issue still exists.
