### ISSUE TITLE
Deprecate/remove maxdict

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#22278]
The maxdict in matplotlib's cbook is only used in one place in Matplotlib.
https://github.com/matplotlib/matplotlib/blob/bedc2021a59d735e420d31c916fb0725aa9e8673/lib/matplotlib/text.py#L111
It can probably be updated to `functools.cache` now, with some work to figure out exactly where to put the cache decorator.

@greglucas Actually, switching to lru_cache would be a bit annoying, because the caching on fontproperties must be based on `hash(fontproperties)` (as fontproperties themselves are mutable) but then you can't get back the fontproperties from the hash...
(Again, it may be possible to add more indirection around that but it may not really be worth it for now...)

_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/22271#issuecomment-1017936197_

**Comment by timhoffm** [comment]
We can immediately deprecate it, and still have enough time to figure out whether we need it internally or can remove it.

**Comment by anntzer** [comment]
Done by #22271.
