### ISSUE TITLE
[Doc]: Exchange step() for stairs() in the Plot types - Basic section

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#22277]
### Documentation Link

https://matplotlib.org/devdocs/plot_types/index.html#basic

### Problem

`step()` is quite particular and a bit difficult to understand. I assume that most step-like plots come from data where you know the step points and the values in between.

**Comment by story645** [comment]
should maybe be both & the difference shown clearly?

**Comment by timhoffm** [comment]
> difference shown clearly

I don't know how to do that with the minimalistic approach of the plot types. And I assume step is rarely needed (The plot types section only shows a selection of most common (?) plots. I'd be open tomswitch to showing all, but we should be consistent in our selection.

**Comment by story645** [comment]
> to switch to showing all
I thought the plot types gallery was for showing all the plot types, just very briefly

The difference between stair and step is  step:len(x)=len(y) and stair:len(x)=len(y)+1 which I think can be made explicit in how the variables are constructed?

**Comment by jklymak** [comment]
step was just originally chosen because that is what's in the cheatsheet.  :+1: to change to stairs, and probably change the cheatsheet too?
