### ISSUE TITLE
[Bug]: Jupyterlab matplotlib randomly decides not to draw some charts. It's also slow in drawing.

### ISSUE THREAD

**Issue by monopoly-db** [matplotlib/matplotlib#22272]
### Bug summary

I am plotting a lot of line charts from a cell in Jupyterlab notebook. matplotlib randomly drops a few of these charts when drawing (all I see is an empty area where the plot should have been.)

See: https://stackoverflow.com/questions/70779723/jupyterlab-matplotlib-randomly-decides-not-to-draw-some-charts-its-also-slow-i

### Code for reproduction

```python
# Cell 1
%matplotlib widget

import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import pandas as pd
import math
import ipywidgets as widgets

mpl.rcParams['figure.max_open_warning'] = 0
mpl.rcParams['figure.figsize'] = (10,10)

# Cell 2
df = pd.read_csv("disk_stats.csv")
print(df.head())
glb_dict_disks = {k: v for k, v in df.groupby('Disk Serialno')}

# Cell 3
def hbox_charts(titles, x, y):
    plt.style.use('dark_background')
    plt.ioff()

    assert(len(x) == len(titles))
    assert(len(x) == len(y))
    
    canvases = []
    for s in range(len(titles)):
        x_points = x[s]
        y_points = y[s]
        
        fig, axes = plt.subplots(sharex=True, constrained_layout=False, figsize=(4, 3))
        plt.title(titles[s])
        axes.plot(x_points, y_points)
        canvases.append(fig.canvas)

    plt.ion()
    box_layout = widgets.Layout(flex_flow='row wrap')
    display(widgets.HBox(canvases, layout=box_layout))

# Break down into sets of 20 charts each. HBox maybe seems to be having trouble 
# displaying a lot of charts in one go. Create a separate HBox for each set
# of 20 charts.
def feed_disks_data(start=0, end=0):
    CHARTS_PER_SET = 20
    kv_disks = glb_dict_disks.items()
    titles = [f"{idx}:{serial}: Read / Write IOPS" for idx, serial in enumerate(glb_dict_disks.keys())]
    x = [data.index for data in glb_dict_disks.values()]
    y = [data.RdIops for data in glb_dict_disks.values()]
    sets = math.ceil(len(kv_disks) / CHARTS_PER_SET)
    
    remaining = len(titles)
    for s in range(sets):
        set_first = s * CHARTS_PER_SET
        set_last = min(set_first + CHARTS_PER_SET, set_first + remaining)
        remaining = remaining - CHARTS_PER_SET

        print(f"Drawing charts {set_first}:{set_last}")
        hbox_charts(titles[set_first:set_last], x[set_first:set_last], y[set_first:set_last])
        
feed_disks_data()
```

### Actual outcome

<img width="1079" alt="Screen Shot 2022-01-19 at 8 40 37 PM" src="https://user-images.githubusercontent.com/6857926/150246986-db84565f-b0b8-4633-b031-86fe8f1e8b9e.png">

### Expected outcome

Expected all charts to be displayed.

### Operating system

Server on CentOS7. Client: Chrome Version 97.0.4692.71 MacOS Catalina 10.15.7 (19H1217)

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://ipympl.backend_nbagg

### Python version

3.9.5

### Jupyter version

6.4.6

### Installation

conda

**Comment by QuLogic** [comment]
> module://ipympl.backend_nbagg

This backend is [here](https://github.com/matplotlib/ipympl); you should probably report there first.

**Comment by jklymak** [comment]
I'm actually going to close here, because this has a bunch of non Matplotlib in it, and you are messing around with canvases inside widgets.  Suggest if you report to ipympl that you make a self contained example.  However for your problem I would use subplots rather than pack 20 different figures in widgets.

**Comment by monopoly-db** [comment]
@jklymak Could you please explain why messing with canvases is a problem here? I was using the method being used here by @thomasaarholt: https://github.com/matplotlib/ipympl/issues/203.

Anyway I wrote a command line plotting test script where matplotlib works just fine. So it does seem to be a problem with ipympl. I'll move this there, although an answer to the above question would be great!

**Comment by tacaswell** [comment]
> Could you please explain why messing with canvases is a problem here?

My knee-jerk guess is that you are ending up with the canvas having two containers that are trying to drive it (the original manager and the hbox).

I would try creating the figure and canvas objects directily without pyplot (like the the examples in https://matplotlib.org/stable/gallery/index.html#embedding-matplotlib-in-graphical-user-interfaces).  That will let you fully control the life-cycle and display of the figures.

**Comment by monopoly-db** [comment]
> > Could you please explain why messing with canvases is a problem here?
> 
> I have no idea if it is the problem, but when debugging its easier to simplify the problem as far as possible, so including non-standard plotting methods is a good first thing to remove.

Being a new user of matplotlib it's hard for me to figure out what is standard and what is not. Googling around for my answers just gave me too many different tracks to explore most of which did not work for me. I did not imagine using a library would be this hard! Totally underestimated the effort required to plot "just a bunch of graphs"!

Thanks for the help!

**Comment by jklymak** [comment]
If all you want to do is display 20 figures from the same cell, you don't need all the Hbox stuff:

```python
%matplotlib widget
import matplotlib.pyplot as plt
for i in range(20):
    fig, ax = plt.subplots()
```

works fine.  If you start monkeying around with non-standard ways of embedding the widgets that you found on a GitHub issue posted by one of the project developers, what you are doing is "non-standard".  For your issue, if you want more than one plot side by side, just do the simple thing and call subplots: `fig, axs = plt.subplots(nrows=N, ncols=M, figsize=(w,h))` where you adjust the width or height as needed.
