### ISSUE TITLE
[Question] Customize plot ticklines (2DLines)

### ISSUE THREAD

**Issue by antoinecollet5** [matplotlib/matplotlib#22296]
To format the tick of a plot in a nice way, there are tick locatters to modify the positions, and formatters to modify labels (`matplotlib.ticker`). We can create our own classes from it which is great.

I was wondering if we can do the same to configure the 2Dlines of the tick. Usually this is done with `matplotlib.axes.Axes.tick_params`. But what if I want to modify some ticks in particular.

For instance, I want to make the tick overlapping the plot frame edges transparent. I can do that with something like:

```python
def make_ticks_overlapping_axis_frame_invisible(ax: Axes) -> None:
    """
    Make the ticks overlapping the frame of the axis invisible.
    
    It does not modify the labels, only make the ticks overlapping
    the frame edges as transparent.
    
    Parameters
    ----------
    ax_name : str
        The given axis name.
    
    Returns
    -------
    None.
    
    """
    # For the x axis
    xticks = ax.get_xticks()
    xlines = ax.xaxis.get_ticklines()
    xlim = ax.get_xlim()
    if xticks[0] == xlim[0]:
        xlines[0].set_visible(False) # Most left tick of the bottom edge
        xlines[1].set_visible(False) # Most right tick of the bottom edge
    if xticks[-1] == xlim[-1]:
        xlines[-2].set_visible(False) # Most left tick of the top edge
        xlines[-1].set_visible(False) # Most right tick of the top edge
    
    # For the y axis
    yticks = ax.get_yticks()
    ylines = ax.yaxis.get_ticklines()
    ylim = ax.get_ylim()
    if yticks[0] == ylim[0]:
        ylines[0].set_visible(False) # Bottom tick of the left edge
        ylines[1].set_visible(False) # Bottom tick of the right edge
        # xlabels = xlabels[1:]
    if yticks[-1] == ylim[-1]:
        ylines[-2].set_visible(False) # Top tick of the left edge
        ylines[-1].set_visible(False) # Top tick of the right edge
```

However, it gets messy if the graph is updated (if the xlim/ylim change). I am looking for a more dynamic way to do it.
Does anyone has any idea ?
Thank you in advance,

A great mpl fan :)

**Comment by QuLogic** [comment]
I'm not so sure there are any easier ways.

However, for usage questions, please [post on our discourse instead](https://discourse.matplotlib.org).
