### ISSUE TITLE
[Bug]: Args for tripcolor

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [matplotlib/matplotlib#22303]
### Bug summary
Thanks for matplotlib! 
`tripcolor` fails if colors are passed with named argument i.e `c=values` instead of just `values`. The error is not very informative and it seems a dangerous practice to ignore `kwargs` and only use `args`.

```bash
  File "/mnt/session_space/conda_envs/latest39/lib/python3.9/site-packages/matplotlib/tri/tripcolor.py", line 57, in tripcolor
    C = np.asarray(args[0])
IndexError: list index out of range
```

### Code for reproduction

```python
plt.tripcolor(vertices[:,0], vertices[:,1], c=values, triangles=triangles)
```

### Actual outcome

```bash
  File "/mnt/session_space/conda_envs/latest39/lib/python3.9/site-packages/matplotlib/tri/tripcolor.py", line 57, in tripcolor
    C = np.asarray(args[0])
IndexError: list index out of range
```

### Expected outcome

a successful plot.

### Matplotlib Version

3.5.1

**Comment by QuLogic** [comment]
Please provide a complete example. (Also, I don't think `c` is a valid keyword argument to `tripcolor`.)

**Comment by jklymak** [comment]
I'll close for lack of response, but do request a re-open if there is still an issue here.

**Comment by anntzer** [comment]
Basically `tripcolor(np.random.rand(5), np.random.rand(5), C=np.random.rand(5))` currently fails with the not-so-informative error message above (the correct invocation is `tripcolor(np.random.rand(5), np.random.rand(5), np.random.rand(5))`).  I think we should indeed *not* allow passing C by keyword, only positionally (see https://github.com/matplotlib/matplotlib/issues/11526 for essentially the same discussion on quiver); however the error could be made clearer.

**Comment by timhoffm** [comment]
Unfortunately, the API is heavily overloaded. We need an `*args` parameter that can take many forms, and we cannot get rid of it without major API breakage. Things to do:

- Clarify which APIs we want to support
- Improve the documentation
- Cleanup the parameter parsing. There seem some assumptions to be baked in. Probably we should have an internal parser function `triangulation, C, kwargs = parse_params(args, kwargs)` that we can unittest the defined API against, and that issues reasonable warnings.
