### ISSUE TITLE
[Bug]: Line3DCollection, unlike LineCollection, returns empty list when get_segments() is called

### ISSUE THREAD

**Issue by hazrmard** [matplotlib/matplotlib#22336]
### Bug summary

The Line3DCollection plots lines ok, but when I go to access the line segments, the `get_segments()` method returns an empty list. This behavior is the opposite of the 2D case where a `LineCollection.get_segment()` methods gives me the list of line segments as I want.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from mpl_toolkits.mplot3d.art3d import Line3DCollection

# 3d example which does not work
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
lines = [
    [(0,0,0), (1,1,0)],
    [(0,0,0), (-1,1,0)]
]
col = Line3DCollection(lines)
ax.add_collection(col)   # same result using add_collection3d()
print(col.get_segments()) # []??????


# 2D example which works
fig = plt.figure()
ax = fig.add_subplot()
lines = [
    [(0,0), (1,1)],
    [(0,0), (-1,1)]
]
col = LineCollection(lines)
ax.add_collection(col)
print(col.get_segments()) # a list of segments, as expected
```

### Actual outcome

Outcome of 3D case, which does not work:
![image](https://user-images.githubusercontent.com/11132213/151437675-b8bdd1e0-8cd7-4ceb-b61c-690b3ae085a9.png)

Outcome of 2D case, which works:
![image](https://user-images.githubusercontent.com/11132213/151437725-64a48589-e6fa-4141-8753-17e7d73c47e8.png)

### Expected outcome

A list of arrays containing points describing 3D line segments

```
[array([[0., 0., 0.],
       [1., 1., 0.]]), array([[ 0.,  0., 0.],
       [-1.,  1., 0.]])]
```

### Additional information

python=3.9.9, matplotlib=3.5.1

### Operating system

Linux

### Matplotlib Version

3.5.1

### Matplotlib Backend

nbAgg

### Python version

3.9.9

### Jupyter version

notebook=6.4.7, IPython=8.0.1

### Installation

conda

**Comment by tacaswell** [comment]
The way that the 3D artists work is that they hold the 3D data, do the projection (in CPU) and the push the results down to the 2D artist at draw time.  By forcing a draw before you ask for the the segments:

```python
col = Line3DCollection(lines)
ax.add_collection(col)   # same result using add_collection3d()
fig.draw_without_rendering()   # get the draw method to compute the projections 
print(col.get_segments()) # shows results

```

However, these will be the project-to-2D version of the segments, not the 3D segments.  Unfortunately we can not change this because we use these public methods as part of the draw process!
