### ISSUE TITLE
[Bug]: GridSpec or related change between 3.4.3 and 3.5.1

### ISSUE THREAD

**Issue by KelSolaar** [matplotlib/matplotlib#22341]
### Bug summary

Hi,

One of our colorimetric report is broken since 3.5.x, it is working correctly in 3.4.3 thus I'm wondering if there have been significant changes in the GridSpec between those two versions? I haven't seen anything relevant in the release notes.

### Code for reproduction

No minimal reproducible case yet as the code is complex: https://github.com/colour-science/colour/blob/065e7d6494d6d41330f34024b48d673fed8d6e82/colour/plotting/tm3018/report.py#L235

### Actual outcome

![image](https://user-images.githubusercontent.com/99779/151527729-79c41527-e149-49b5-80c4-cfe868bb7077.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/99779/151527878-8bd0e800-535f-4271-8235-d9c4bb3e601a.png)

### Additional information

Working in 3.4.3, broken in 3.5.x

### Operating system

macOS

### Matplotlib Version

3.5.1

### Matplotlib Backend

MacOSX

### Python version

3.9.9

### Installation

pip

**Comment by jklymak** [comment]
There is a bug in constrained layout for repeated gridspec keys.  Can you try on master and see if this is fixed.  The fix should be in for 3.5.2

**Comment by KelSolaar** [comment]
Hi @jklymak,

I will try it later this week!

**Comment by oscargus** [comment]
@KelSolaar have you been able to try this out?

**Comment by jklymak** [comment]
Lets close.  I'm 99.9% sure this has been fixed.  If not, we can re-open or make a new issue.  Thanks!

**Comment by KelSolaar** [comment]
I haven't had a chance to try but I'll report back if any issues on future releases!
