### ISSUE TITLE
[Bug]: Capstyle has no effect on FancyArrow

### ISSUE THREAD

**Issue by mapfiable** [matplotlib/matplotlib#22340]
### Bug summary

I was trying to create a [`FancyArrow`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrow.html#matplotlib-patches-fancyarrow) with a butt, but changing the [`capstyle`](https://matplotlib.org/stable/api/_enums_api.html#matplotlib._enums.CapStyle) has no effect. I guess this is related to [#13641](https://github.com/matplotlib/matplotlib/issues/13641/)?

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrow


fig, ax = plt.subplots()
for i, cs in enumerate(['butt', 'round', 'projecting']):
    arrow = FancyArrow(0, 0+i, 1, 0, width=0.1, capstyle=cs)
    ax.add_patch(arrow)

ax.relim()
ax.autoscale_view()
fig.show()
```

### Actual outcome

![grafik](https://user-images.githubusercontent.com/48512334/151515503-9230faf1-ff4a-4217-9284-152946d6eb18.png)

### Expected outcome

Something similar to this:

![grafik](https://user-images.githubusercontent.com/48512334/151516054-58fc08f3-3bc2-425b-b416-5c32e0388606.png)

### Matplotlib Version

3.5.1

### Installation

pip

**Comment by jklymak** [comment]
I'm confused - there are no caps in the arrow patches, so where would you expect those styles to have effect?

**Comment by mapfiable** [comment]
Ooh, ok. But then what is the non-pointy end of the arrow called? I thought that's the cap. But I guess in that case I missunderstood the kwarg. What is it supposed to do instead then / in what case does it have an effect? Also, does that mean I cannot get a `FancyArrow` with a round butt?

**Comment by jklymak** [comment]
Fancy Arrow is a patch, and the lines outlining the patch are what have a cap style and join style.  Those do not affect the shape of the patch.  I don't see that FancyArrow allows different tail shapes, and the head shapes are restricted to width and length.  So if you want a different shape, you will have to make a PolygonPatch and pass the path yourself.

**Comment by mapfiable** [comment]
Ah, ok, I get it now, sorry. I also found [this `FancyArrow` demo](https://matplotlib.org/3.1.0/gallery/text_labels_and_annotations/fancyarrow_demo.html), but it never had anything to do with `FancyArrows`, did it? The [new version](https://matplotlib.org/stable/gallery/text_labels_and_annotations/fancyarrow_demo.html) doesn't mention `FancyArrow` anymore (except in the url), so I guess it only works for `annotation` arrows? If not, I guess it would be nice to have something like `.->` defining an arrow with a round tail.

**Comment by jklymak** [comment]
OK, lets close this, and if you would like to make a feature request, that would be great...
