### ISSUE TITLE
Animation docs should include a simple "save as gif with pillow" example

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22374]
### Problem

pillow is the only animation writer that does not require additional dependencies (we already depend on pillow in any case) but it is not the default writer.  I think the main animation formation it can save to is gif.

There should be a simple "save as gif with pillow example" with its own entry in https://matplotlib.org/devdocs/gallery/index#animation (although some of the examples have a few lines on saving as mp4 with ffmpeg, 1. it is not even clear from the index which are these examples, and 2. ffmpeg may or may not be present on the user's machine).

### Matplotlib Version

3.6.0.dev1512

**Comment by timhoffm** [comment]
What we really need is an animation tutorial/explanation. This should explain the logic of animations and could then also have a section on saving to file. The individual examples should link to the tutorial for further information.

**Comment by story645** [comment]
Labeling good first issue because this is relatively simple and stand alone. Also agree we need a user level "how to animate" tutorial, but I think this example can be generated independent of that.

**Comment by kostyafarber** [comment]
This sounds interesting. Any suggestions on what animation we would want to use for this example?

**Comment by kostyafarber** [comment]
No worries I'll have a look at it and try mock something up.

**Comment by kostyafarber** [comment]
Hey,

Are we thinking something simple like this?

![scatter](https://user-images.githubusercontent.com/73378227/193472955-332ad697-99a4-4b1d-b977-0bc9f22f5969.gif)

Also what would be the best way we want to write the save to gif as?

```python
# To save the animation, use e.g.
#
# ani.save("movie.mp4")
#
# or
#
# writer = animation.FFMpegWriter(
#     fps=15, metadata=dict(artist='Me'), bitrate=1800)
# ani.save("movie.mp4", writer=writer)
```

Something along these lines?

Cheers,
Kostya

**Comment by kostyafarber** [comment]
No worries I'll have a look into it and post the code block here. Thanks.

**Comment by kostyafarber** [comment]
> @story645 

How does this look?

```python
# To save the animation using Pillow as a gif, use e.g.
#
# writer = animation.PillowWriter(fps=15,
#                                 metadata=dict(artist='Me'),
#                                 bitrate=1800)
# ani.save('scatter.gif', writer=writer)
```

**Comment by kostyafarber** [comment]
@story645 just had a thought if it's not in comments when the docs are built will the code generate an image if it has `ani.save('scatter.gif', writer=writer)` uncommented?

Might be better to comment out then?

**Comment by kostyafarber** [comment]
PR at: https://github.com/matplotlib/matplotlib/pull/24096

**Comment by melissawm** [comment]
Now that the animation tutorial has been merged, do we still need to keep this issue open?

**Comment by timhoffm** [comment]
This is now covered in https://matplotlib.org/devdocs/users/explain/animations/animations.html#saving-animations
