### ISSUE TITLE
[Doc]: Animation doc thumbnails are misaligned.

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22373]
### Documentation Link

https://matplotlib.org/devdocs/gallery/index#animation

### Problem

Example thumbnails are normally aligned over 4 columns, but the animation thumbnails are misaligned.
![Screenshot](https://user-images.githubusercontent.com/1322974/152032828-c737323d-b063-40be-9ce3-74b78f6b72f2.png)

### Suggested improvement

Align the thumbnails.

### Matplotlib Version

HEAD (3.6.0.dev1512)

**Comment by QuLogic** [comment]
The images have a max height and width, and the Rain animation is taller than it is wide, so it ends up thinner than (almost?) all other thumbnails. The thumbnail container does not have a fixed width, and adding one would fix this.

**Comment by QuLogic** [comment]
Maybe the CSS changes in https://github.com/sphinx-gallery/sphinx-gallery/pull/906 will help with this?

**Comment by QuLogic** [comment]
I think this is fixed in 3.5.3 due to the new sphinx-gallery.
