### ISSUE TITLE
[ENH]: Improve plt.arrow default head shape

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#22379]
### Problem

The default for the head width/length of the fancy arrow patch are not very good. See for example: https://philbull.wordpress.com/2012/04/05/drawing-arrows-in-matplotlib/

This means that in order to get a usable arrow you need to mess around with options such as `head_length` which can be tricky to learn about. 

### Proposed solution

Use a new heuristic for head sizing as a default behavior. 

@kmdalton suggested the below function `norm_arrow` which you can see gives better defaults in two basic test cases.

```python
import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(2,2)

lims = (
    [-1, 1],
    [-10,10],
)

def norm_arrow(ax, x1, y1, x2, y2, head_scale=0.1, head_width=None, **kwargs):
    norm = np.sqrt((x2-x1)*(x2-x1) + (y2-y1)*(y2-y1))
    l = head_scale*norm
    w = head_width if head_width is not None else 0.5*l
    ax.arrow(x1, y1, x2, y2, head_width=w, head_length=l, length_includes_head=True, **kwargs)

axes[0][1].set_title("Norm based default")
axes[0][0].set_title("Current Default")

for axs, lim in zip(axes, lims):
    axs[0].set_ylim(lim)
    axs[0].set_xlim(lim)
    axs[1].set_ylim(lim)
    axs[1].set_xlim(lim)

    axs[0].arrow( 0, 0, lim[1]/2, lim[1]/2, fc="k", ec="k" )
    norm_arrow(axs[1], 0, 0, lim[1]/2, lim[1]/2, fc="k", ec="k" )

plt.show()
```

![image](https://user-images.githubusercontent.com/10111092/152208475-47fb6e1d-dfa3-4223-bc19-5089f2b24a92.png)

**Comment by kmdalton** [comment]
The function should actually be the following:

```python
def norm_arrow(ax, x1, y1, x2, y2, head_scale=0.1, head_width=None, **kwargs):
    dx,dy = x2-x1,y2-y1
    norm = np.sqrt(dx*dx + dy*dy)
    l = head_scale*norm
    w = head_width if head_width is not None else 0.5*l
    ax.arrow(x1, y1, dx, dy, head_width=w, head_length=l, length_includes_head=True, **kwargs)
```

The original version only works for arrows that start at the origin (oops).

**Comment by jklymak** [comment]
Plt.arrow is definitely broken and we have considered deprecating it. 

But scaling arrow heads by the length of the arrow does not strike me as a very good solution either.  For one arrow it looks good, but different length arrows will have different arrow heads.  Also non-equal aspect ratio axes will have different head sizes depending on if the arrow points in one direction or the other.  

Rather the arrowhead should dimensioned and drawn in physical units, which I am pretty sure is what happens with plt.annotate.

**Comment by jklymak** [comment]
Crossref https://github.com/matplotlib/matplotlib/issues/20387 for discussion of deprecating `arrow`.

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib/pull/22382 for the purposed deprecation...

**Comment by kmdalton** [comment]
I concur that `plt.annotate` draws nicer arrows. However, it has a number of drawbacks. In particular it does not
 - add handles for `plt.legend` based on `label=`
 - use the axes `prop_cycler` to set the color

**Comment by ianhi** [comment]
closing in favor of https://github.com/matplotlib/matplotlib/issues/22390
