### ISSUE TITLE
[MNT]: Subplots of different sizes when using cartopy

### ISSUE THREAD

**Issue by AndrewWilliams3142** [matplotlib/matplotlib#22377]
### Bug summary

I often make graphs which have one "normal" subplot (e.g., a scatterplot) and another subplot which is a `cartopy` map. 

To do this, the easiest way I've found is to use `subplot2grid()`, however I have found that the subplots which are created are not of the same size! For example, see the example below, where the `cartopy` subplot  is significantly smaller than the other subplot.

My current workaround is to make a `subplot2grid()` grid which has a very large dimension (e.g. 100 rows by 100 cols), and then I can force the subplots to be the same "size" by making the `colspan` and `rowspan` larger or smaller, but this is definitely not ideal.

Am I doing something wrong? Or is this something fundamental about using cartopy with matplotlib? 

Thanks very much!
Andrew

### Code for reproduction

```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

fig = plt.figure()

ax0 = plt.subplot2grid((1, 2), (0, 0), colspan=1, rowspan=1, projection=ccrs.PlateCarree())
ax1 = plt.subplot2grid((1, 2), (0, 1), colspan=1, rowspan=1)

ax0.coastlines()

ax1.plot(np.arange(5), np.arange(5))
```

### Actual outcome

![error](https://user-images.githubusercontent.com/56925856/152201776-6e37a9ac-86b3-4b99-b0ef-727e859384ac.jpg)

### Expected outcome

Having the cartopy subplot being the same size as the "normal" subplot

### Matplotlib Version

3.3.3

**Comment by jklymak** [comment]
Yes this is expected behaviour.  Please follow up on discourse.matplotlib.org.  Thanks!
