### ISSUE TITLE
[Bug]:how can  i want plot subplots by using loop

### ISSUE THREAD

**Issue by haritha1022** [matplotlib/matplotlib#22372]
### Bug summary

my code is very large without iteration so i am trying create a loop but i am failed

### Code for reproduction

```python
import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np

#Opening and reading data
data=xr.open_dataset("zuv500hpa.nc")
print(data)




x=data.longitude[::5]; 
y=data.latitude[::5]
u=data.u[0,::5,::5]; 
v=data.v[0,::5,::5]
z=data.z[:]





fig=plt.figure(figsize=(8,15))
hrs=np.arange(0,7)
for i in hrs:
 
 ax = plt.subplot(projection=ccrs.PlateCarree())
 z[i].plot.pcolormesh(cmap="turbo",vmin=54690,vmax=57500, ax = ax)
 #plt.ax.set_extent([60,100,38,0])
 ax.coastlines()
 ax.set_extent([60, 100, 38, 0])
 #ax.add_feature(cf.BORDERS)
 #ax.colorbar(cb, pad='2%',label='pa',extend='both',location='right')
 #plt.colorbar(cb)
 ax.quiver(x,y,u,v, angles='xy', scale_units='xy', scale=6)
 hrs=i+1



plt.savefig("sujjiwinds.eps")
plt.show()
```

### Actual outcome

it only giving first plot

### Expected outcome

subplots

### Operating system

ubuntu

### Matplotlib Version

3.4.3

### Matplotlib Backend

import matplotlib.pyplot as plt

### Python version

3.9.7

**Comment by jklymak** [comment]
Hi thanks for the interest in Matplotlib but this is not a suitable forum for user help.  Please follow up at https://discourse.matplotlib.org preferably with a self-contained minimal example.  

Thanks for your understanding.

**Comment by jklymak** [comment]
Fwiw plt.subplot just keeps using the same subplot over and over. Create more than one subplot and populate

**Comment by haritha1022** [comment]
ok

**Comment by haritha1022** [comment]
sir actually loop is working but some letters in the panel plot is are
missing see color bar and super title some letters are missing this is my
actually problem


here is my code


import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np
data=xr.open_dataset("zuv500hpa.nc")
print(data)
x=data.longitude[::5];
y=data.latitude[::5]
u=data.u[0,::5,::5];
v=data.v[0,::5,::5]
z=data.z[:]
fig = plt.figure(figsize=(20,20))

hrs=np.arange(0,4)
for i in hrs:

 ax = fig.add_subplot(2,2,i+1,projection=ccrs.PlateCarree())
 z[i].plot.pcolormesh(cmap="coolwarm",vmin = 53900, vmax=57900,ax =
ax,add_colorbar=True)
 #plt.ax.set_extent([60,100,38,0])
 ax.coastlines()
 ax.set_extent([60, 100, 38, 0])
 #ax.add_feature(cf.BORDERS)
 #ax.colorbar(cb, pad='2%',label='pa',extend='both',location='right')
 ax.quiver(x,y,u,v, angles='xy', scale_units='xy', scale=6)
 hrs=i+1
plt.suptitle('height')
plt.savefig("at2.eps")

plt.show()
plt.tight_layout()
 at2.eps
<https://drive.google.com/file/d/1XPInQ_PkkjLqtbzsa6U7ZM4WScLsnx58/view?usp=drive_web>
