### ISSUE TITLE
[Bug]: Plot lines not clearing when moving to Windows 10 from Windows 7 

### ISSUE THREAD

**Issue by Grandpa-G** [matplotlib/matplotlib#22381]
### Bug summary

The repainting of the moving plotlines are not completely cleared. Works correctly on Windows 7 but not on Windows 10. Using v 3.5.1

Notice the red circled areas where there are extra lines that are not expected. The lines look like past portions of the plot. The plot moves from right to left over time. This does not use animation.

### Code for reproduction

```python
Some of the code relevant

        for c in range(0, 15):
            fig.canvas.blit(ax[c].bbox)

        fig.canvas.flush_events()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/10815188/152274491-0250e338-d0be-4ce1-b5dc-2dd03f2f9646.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/10815188/152273938-150156b6-105b-4a8b-b438-e3420196e9aa.png)

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

Windows 7 3.8.1  Windows 10 3.9.7

### Installation

pip

**Comment by timhoffm** [comment]
Please try to boil this down to a minimal executable example. The information above is too vague for us to be able to inspect the issue.

**Comment by Grandpa-G** [comment]
Here is a portion of the main program that will fail on windows 10 but not on Windows 7. This will only produce a graph in the left middle plot.

here is the program
https://pastebin.com/hpE8gt70

Here is the data file. Make the data file name bms_esc_log_2022_01_08_17_17_42.csv
https://pastebin.com/ZPNNhQgu

**Comment by jklymak** [comment]
@Grandpa-G Please reduce to a minimal self-contained example.  If this is a robust failure, it will fail with a far simpler plot that does not depend on external data: http://sscce.org

**Comment by Grandpa-G** [comment]
I don't see how  you can say the data is different, they both use exactly the same data file. These are not static plots as I explained. The snapshots just come at different times based on how fast I can snap it.

What seems to be the problem with using a simple file to get the data? This is a real world example and needs to have data being feed to it. I am not sure what you are expecting the script to be reduced to.

**Comment by jklymak** [comment]
I'll close for lack of a minimal reproducible example.
