### ISSUE TITLE
[Bug]: stackplot cannot set edgecolor resulting in artifacts

### ISSUE THREAD

**Issue by tlkaufmann** [matplotlib/matplotlib#22386]
### Bug summary

Shown below is a minimal example of my use-case for `stackplot`.  I noticed a strange artifact that happened if a value is zero.

I wanted to change this behavior by setting the edgecolor but that doesn't work.

Looking into the source code for `stackplot` one can see that edgecolor is never explicitely passed to `fill_between` (unlike `facecolor`) and therefore it doesn't really work:
```python
        r.append(axes.fill_between(x, stack[i, :], stack[i + 1, :],
                                   facecolor=color, label=next(labels, None),
                                   **kwargs))
```

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(10)
y0 = [1, 1] + 8*[0]
y1 = np.cumsum(np.random.uniform(0, 1, size=10))
y2 = np.cumsum(np.random.uniform(0, 1, size=10))
y3 = np.cumsum(np.random.uniform(0, 1, size=10))

y2[:3] = 0

colors=['grey', 'blue', 'red', 'blue']

y = np.stack([y0, y1, y2, y3])
im = plt.stackplot(x, y, colors=colors, ec=colors, lw=1)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/17513791/152384186-275a49d4-47d1-49b2-a63b-147694b02670.png)

### Expected outcome

Should look like this:
![image](https://user-images.githubusercontent.com/17513791/152440289-59435222-3702-4e5b-ae7a-4fd099481a3e.png)

I.e. the thin grey line is missing.

Note that the shapes are slightly different because the data is generated randomly.

### Matplotlib Version

3.4.3

### Installation

conda

**Comment by tlkaufmann** [comment]
Although this can be fixed if edgecolor is used, this seems to be rather an issue with `fill_between` as the below example shows

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(10)
y0 = [1] + 9*[0]
y1 = np.cumsum(np.random.uniform(0, 1, size=10))
y2 = np.cumsum(np.random.uniform(0, 1, size=10))
y3 = np.cumsum(np.random.uniform(0, 1, size=10))

y2[:3] = 0

colors=['grey', 'blue', 'red', 'blue']

y = np.stack([y0, y1, y2, y3])
im = plt.fill_between(x, 10*[0], y0, facecolors=colors[0], ec=colors[0], lw=1)
im = plt.fill_between(x, y0, y0 + y1, facecolors=colors[1], ec=colors[1], lw=1)
im = plt.fill_between(x, y0 + y1, y0 + y1 + y2, facecolor=colors[2], ec=colors[2], lw=1)
im = plt.fill_between(x, y0 + y1 + y2, y0 + y1 + y2 + y3, facecolor=colors[3], ec=colors[3], lw=1)
```

![image](https://user-images.githubusercontent.com/17513791/152385313-bd491fe4-eb45-4a32-a3d1-c4381105d86d.png)

**Comment by tlkaufmann** [comment]
I have come up with a hacky solution to this problem. The idea is to not plot a segment if `y1 == y2`, i.e. height zero.

It involves the following changes to `matplotlib/lib/matplotlib/stackplot.py`:

```python
    y = np.row_stack(args)
    mask = (y != 0)

...

    # Color between array i-1 and array i
    for i in range(len(y) - 1):
        color = ax._get_lines.get_next_color()
        cur_mask = mask[i+1, :]
        cur_mask = cur_mask | np.roll(
            np.pad(cur_mask, 1), -1)[1:-1] | np.roll(np.pad(cur_mask, 1), 1)[1:-1]

        r.append(ax.fill_between(x[cur_mask], stack[i, :][cur_mask], stack[i+1, :][cur_mask],
                                 facecolor=color, edgecolor=color, label=next(labels, None),
                                 **kwargs))
```

I could open a pull request if this change is of interest?

**Comment by QuLogic** [comment]
I don't know what the problem is because your expected outcome is:

> No artifacts in the plot

but you did not explain what the artifacts are, and apparently both plots you have given are wrong in different ways?

**Comment by tlkaufmann** [comment]
Thanks for you comment @QuLogic . I have updated the description with an image of how I expect the output to look like.
The plot I gave in my first comment also has this thin red line.
The thin line is removed with the changes I proposed in my 2nd comment.

Hope this clears things up

**Comment by timhoffm** [comment]
The reason for this effect is that all `kwargs` parameter are applied as is to every `fill_between()` call. Only `colors` are mapped throughout the datasets. You can see by setting `lw=3` that actually all edges are the first color, i.e. grey. That a list of colors is still accepted lies deeper in the underlying `PolygonCollection`. Whether that should be allowed in stackplot is to be discussed separately.

What I don't understand in the first place is why you want to set edgecolors at all. Could you please clarify that motivation?

**Comment by tlkaufmann** [comment]
@timhoffm you are right. I think I wrote this issue in a confusing way because I didn't really understand the problem. I have created a new issue that is (hopefully phrased more clearly) and will close this one for now.

The new issue:
https://github.com/matplotlib/matplotlib/issues/22393
