### ISSUE TITLE
[Bug]: Matplotlib cbook init causes code to hang for ~130s in Visual Studio Code with WSL2

### ISSUE THREAD

**Issue by mjg41** [matplotlib/matplotlib#22385]
### Bug summary

[Matplotlib cbook init](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/cbook/__init__.py) causes code to hang for ~130s in Visual Studio Code with WSL2.
A bodge fix can be performed by replacing the following line: https://github.com/matplotlib/matplotlib/blob/eda1404e1b5c85e2b1ae9f293368e775e186fd17/lib/matplotlib/cbook/__init__.py#L89
with a simple `if True:` statement, which removes the hang time.

### Code for reproduction

```python
import matplotlib.pyplot as plt
```

### Actual outcome

The code hangs for ~130s just on importing `matplotlib.pyplot`, as below:

![code_delay](https://user-images.githubusercontent.com/93525584/152335093-ae88959e-576a-4a5f-af23-96d3b50106aa.png)

### Expected outcome

The code should not hang. Using the bodge fix this command completes almost instantly (as expected).

### Additional information

This is run in Visual Studio Code using WSL 2 with Ubuntu-20.04 and the VSCode Remote-WSL-Extension.
Thats is, the WSL terminal is opened, and VSCode is run from there with `code .`

### Operating system

WSL 2

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

3.8.10

**Comment by jklymak** [comment]
Thanks for the helpful report.  Does `import matplotlib; matplotlib.use('agg')`  temporarily fix your problem without editing source? 

Any idea where in display_is_valid this is hanging up? Its c-code, and it seems you are meeting the conditions to try and spin up a display, but then it hangs part way through.  i.e. you are reporting as _linux_, you have DISPLAY in your environment, and it manages to import X11. 

You also refer to VSCode - I'm not clear what that has to do with it?  How are you invoking your script?  In a notebook?

**Comment by mjg41** [comment]
You're welcome. Using `import matplotlib; matplotlib.use('agg'); import matplotlib.pyplot` does fix my issue. Note that importing only matplotlib does not cause the code to hang, it is importing pyplot that is the problem, but this does fix that.

I'm sorry, I don't and have little understanding about what's going on under the hood. Happy to run any tests for you that might be informative.

VSCode is the key issue. Using the standard bash terminal within WSL 2 does not have this issue. However using the integrated WSL 2 bash terminal within VSCode (which is what I'd rather use) is where this issue arises and my scripts hang.

**Comment by tacaswell** [comment]
When you say it hang for ~130s is that when you gave up and killed it or when it finally returned?

What are the EVNVARS in that bash shell?  As @jklymak this code is trying to sort out if we have a live X11 or Wayland session (if we are in a desktop enviroment) or not (if we are on a headless server).   The logic is roughly:
1. is the expected env defined?
2. if so, try to load the .so's
3. if that works try to connect to the display to prove it works

I can easily imagine either step 2 or step 3 going sideways in a bash shell in vscode talking to WSL.  Does launching other gui application for the bash shell in vscode work (like `xeyes`  or `xelgears`)?

**Comment by tacaswell** [comment]
and going up a level, if you do not tell us what backend to use, we try to infer it by introspecting the environment and giving you the "best" backend we can.  The first thing we check is if you have already imported and started to use one of the GUI toolkits (in which case we use that one), otherwise we go through them until we find one that imports.  One of the "toolkits" is "headless" that jumps out of trying any of the interactive backends and goes straight to Agg.

**Comment by mjg41** [comment]
Thank you for this. You were right in that `xeyes` also didn't work.

I think this is something to do with the strange way in which WSL2 sets the DISPLAY variable. I googled how to sort this more robustly and managed to find something which now works. I now no longer get the hang time for `matplotlib` or `xeyes`.

Appreciate your quick responses and help resolving this issue.

**Comment by tacaswell** [comment]
@mjg41 Could you add any note about what did fix this to help the next person who has this problem?

**Comment by mjg41** [comment]
Yes no problem. For WSL2 I needed the following X11 forwarding rule (there were many on forums online but this is what worked for me.):
`export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"`
See the posts below for more details:
> Editing [moloned's answer](https://github.com/microsoft/WSL/issues/6430#issuecomment-760936710) to below fixed the issue for me: `export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"`
