### ISSUE TITLE
[MNT]: gtk4 backends are not tested on GHA

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22389]
### Summary

All's in the title.  See e.g. https://github.com/matplotlib/matplotlib/runs/5056485756?check_suite_focus=true#step:12:184 ("SKIPPED [2] lib/matplotlib/tests/test_backends_interactive.py:159: Skipping {'MPLBACKEND': 'gtk4agg'} because no usable GTK bindings"), also check codecov at https://app.codecov.io/gh/matplotlib/matplotlib/blob/447160e0c78a3f834696fbf6b4dca967d9bd05a4/lib/matplotlib/backends/backend_gtk4.py.

### Proposed fix

Install whatever dependencies are needed to run gtk4 on CI.

**Comment by QuLogic** [comment]
Yes, this is because GTK4 is not available until Ubuntu 21.04, and we only have 18.04 and 20.04

**Comment by anntzer** [comment]
OK, I guess you can close this as non-actionable for now or keep it as a reminder to add it once newer images are available.

**Comment by QuLogic** [comment]
These were added on Ubuntu in #26090 and macOS in #26605.
