### ISSUE TITLE
[Doc]: Remove "keywords" line at the bottom of all examples

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22391]
### Documentation Link

https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/bar_label_demo.html

### Problem

All of the examples contain the following line at the bottom of the page: "Keywords: matplotlib code example, codex, python plot, pyplot".  This should be removed, although removal of codex should be coordinated with the search page, which currently states

> If you want to limit your search to working code examples, include the keyword "codex" (mnemonic for code example) in your search, e.g., "codex ellipse".

### Matplotlib Version

3.6.0.dev1530

**Comment by soma2000-lang** [comment]
I am working on this issue.

**Comment by tacaswell** [comment]
Why do we want to remove them rather than making them more accurate?

Can we at least preserve 'codex' for the search functionality?

**Comment by anntzer** [comment]
We can certainly make them more accurate instead of removing them; my point is more that right now they are totally uninformative (except for "codex").

**Comment by timhoffm** [comment]
I find "codex" very jargony. Also, you have to read the heading of the search result site to know about it. I bet most of the users only use the search field in the side bar and then look through the results.

What I would find more usable is
1) have different symbols for different result categories (example, tutorial, api ...)
2) A filter on the result categories

But that's going into sphinx, and I don't have time for that.

If you want to keep keywords for serach (?) reasons, can we make them invisible to the user? IMHO the don't have a benefit for the reader of the example and thus are only clutter.

**Comment by QuLogic** [comment]
I have an idea of how to implement that, but it's tied to our hosting issues. We can maybe discuss on the call when I have the budget drawn up.

**Comment by jklymak** [comment]
> If you want to keep keywords for serach (?) reasons, can we make them invisible to the user? IMHO the don't have a benefit for the reader of the example and thus are only clutter.

sphinx allows a `meta` directive that can contain keywords, which will go in the html meta rather than printed on the page.  Given that we are injecting these somehow, I'm sure we could instead inject them to the meta directive.

**Comment by timhoffm** [comment]
The cheapest way is probably to make the text white. Maybe that's a good hack until we come up with something better.
