### ISSUE TITLE
[Doc]: Site renders poorly on mobile

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#22395]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.quiver.Quiver.html#matplotlib.quiver.Quiver

### Problem

Going to the docs on mobile is not a great experience. 

1. You have to scroll through the whole table of contents to get to the main content
2. there is bad line wrapping
![image](https://user-images.githubusercontent.com/10111092/152603682-f5f761d1-6898-4a54-a58b-52c68d55238d.png)
![image](https://user-images.githubusercontent.com/10111092/152603879-de2e83be-8d89-4284-b158-7c947674bdb0.png)

perhaps other things as well

You can see this either on your phone or through browser dev tools such as https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

### Suggested improvement

more responsive css i guess? Probably having more sections not be displayed unless expanded

### Matplotlib Version

3.5+

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/pull/21667 fixes issue 1.  Not sure what you can do about wrapping code.

**Comment by timhoffm** [comment]
Wrapping:
in basic.css: `dl.field-list {display: grid}` should be removed for small screens:

![grafik](https://user-images.githubusercontent.com/2836374/152610067-625a8a8f-6327-4541-83ad-1e043d42780e.png)

This should be reported upstream to the pydata-sphinx-theme and fixed there.

**Comment by sjvrijn** [comment]
It seems fixed for me. Does anyone else still have this problem? Otherwise I guess this issue can be closed

![Screenshot_20230112-082602](https://user-images.githubusercontent.com/8833517/212004297-da4bfed1-30db-428d-9a9e-04419a184a2c.png)
![Screenshot_20230112-082553](https://user-images.githubusercontent.com/8833517/212004290-de6b6b50-e2e2-49ae-994f-a79cee59dd0c.png)

**Comment by timhoffm** [comment]
Thanks for the reminder! This is fixed upstream.
