### ISSUE TITLE
[Bug]: Incorrect weights for Google fonts

### ISSUE THREAD

**Issue by AlvaroFurlani** [matplotlib/matplotlib#22399]
### Bug summary

The Thin and ExtraLight styles of [Public Sans](https://fonts.google.com/specimen/Public+Sans) do not work as expected in matplotlib. Both of them are being assigned the weight 250, rather than 100 and 200, respectively (verified both through some prints with FontManager and in the fontlist-v330.json file in the cache directory).

### Code for reproduction

```python
from matplotlib import font_manager
fm = font_manager.FontManager()

for font in fm.ttflist:
    if 'Public Sans' in font.name and font.style == 'normal':
        print(f'{font.weight}: {font.fname}')
```

### Actual outcome

Weight 400: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Regular.ttf
Weight 250: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Thin.ttf **_<-- incorrect_**
Weight 300: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Light.ttf
Weight 600: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-SemiBold.ttf
Weight 900: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Black.ttf
Weight 700: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Bold.ttf
Weight 800: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-ExtraBold.ttf
Weight 500: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Medium.ttf
Weight 250: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-ExtraLight.ttf **_<-- incorrect_**

### Expected outcome

Weight 400: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Regular.ttf
**_Weight 100: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Thin.ttf_**
Weight 300: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Light.ttf
Weight 600: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-SemiBold.ttf
Weight 900: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Black.ttf
Weight 700: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Bold.ttf
Weight 800: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-ExtraBold.ttf
Weight 500: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-Medium.ttf
**_Weight 200: C:\Users\afurlan\AppData\Local\Microsoft\Windows\Fonts\PublicSans-ExtraLight.ttf_**

### Additional information

In the .ttf files, it is clear that these styles have different weight. So my guess is that the problem is ocurring on the matplotlib side.

![image](https://user-images.githubusercontent.com/13244268/152618525-f6d4b676-4e4c-4c48-b6a9-36cab7b33438.png)

### Operating system

Windows

### Matplotlib Version

3.5.0

### Matplotlib Backend

Qt5Agg

### Python version

3.9.7

### Installation

conda

**Comment by QuLogic** [comment]
The weights appear wrong in the font file themselves; the OS/2 weight class on the Thin and ExtraLight fonts is 250.

This is already fixed in the fonts themselves: https://github.com/uswds/public-sans/pull/122
You can maybe watch this [Google Fonts update](https://github.com/google/fonts/issues/3953), or download the corrected fonts from upstream.
