### ISSUE TITLE
[MNT]: Confusing prompt in docs issue template

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#22403]
### Summary

In the docs issue template it prompts for the matplotlib version from python 
![image](https://user-images.githubusercontent.com/10111092/152629886-7905183b-ec13-4991-b332-eefa8d20df2f.png)

this is confusing because I most interact with the docs via the browser

### Proposed fix

change prompts to something like: "version of docs website"

**Comment by story645** [comment]
I think the docs version was supposed to be taken care of by link to doc & this is supposed to be asking for library version, but agree it's confusing an either 
1) it should ask for doc version w/ directions on how to find em
2) the prompt should be more explicit "Matplotlib library version"
