### ISSUE TITLE
[Bug]: pyplot.bar: Missing bars when number of values are large

### ISSUE THREAD

**Issue by reddragon** [matplotlib/matplotlib#22400]
### Bug summary

When providing a large number of `x` and `height` values, there are often missing bars. 

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

num_elems = 35000
x = np.sort(np.random.random(num_elems))
plt.bar(range(num_elems), x)
```

### Actual outcome

The expected outcome should be a smooth right-triangle.

### Expected outcome

![image](https://user-images.githubusercontent.com/186566/152627282-8c80d38f-1744-416e-8083-0f311a1574c5.png)

### Matplotlib Version

3.3.4

### Matplotlib Backend

module://IPython.kernel.zmq.pylab.backend_inline

**Comment by QuLogic** [comment]
Pretty sure this is a duplicate of #8808; please see the [explanation there](https://github.com/matplotlib/matplotlib/issues/8808#issuecomment-311349594).

**Comment by reddragon** [comment]
Thanks, this worked!
