### ISSUE TITLE
[Bug]: bar_label overlaps bars when y-axis is inverted

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [matplotlib/matplotlib#22414]
### Bug summary

bar_label overlaps bars when the y-axis is inverted

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np


labels = ['G1', 'G2', 'G3', 'G4', 'G5']
men_means = [20, 34, 30, 35, 27]
women_means = [25, 32, 34, 20, 25]

x = np.arange(len(labels))  # the label locations
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, men_means, width, label='Men')
rects2 = ax.bar(x + width/2, women_means, width, label='Women')

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.legend()
ax.invert_yaxis()
ax.bar_label(rects1, padding=3)
ax.bar_label(rects2, padding=3)

fig.tight_layout()

plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/36672242/152670689-3cc97576-b465-4d73-b0ae-324d77cc8ec8.png)

### Expected outcome

The bar_label most be stay at the end of the bar without overlapping it, but with the y-axis inverted
![Figure_1](https://user-images.githubusercontent.com/36672242/152670704-61ac01fb-d24c-42a4-a874-18dd21b3ba37.png)

### Matplotlib Version

3.5.1

### Installation

pip

**Comment by mwaskom** [comment]
This happens because the padding is specified in points, not data units, so it's not affected by the scale (or reversal) of the axis. You could put the labels below downwards-oriented bars by setting `padding` to a negative number. But the problem is that matplotlib hardcodes the horizontal / vertical alignment (based on some logic) so this does not work:

```python
f, ax = plt.subplots()
ax.invert_yaxis()
bars = ax.bar(["a", "b", "c"], [1, 2, 3])
ax.bar_label(bars, padding=-3, va="top")
```
```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/pk/kq0vw6sj3ssd914z55j1qmzc0000gn/T/ipykernel_13824/3695422629.py in <module>
      2 ax.invert_yaxis()
      3 bars = ax.bar(["a", "b", "c"], [1, 2, 3])
----> 4 ax.bar_label(bars, padding=-3, va="top")

~/miniconda3/envs/seaborn-py39-latest/lib/python3.9/site-packages/matplotlib/axes/_axes.py in bar_label(self, container, labels, fmt, label_type, padding, **kwargs)
   2673                 lbl = ''
   2674 
-> 2675             annotation = self.annotate(fmt % value if lbl is None else lbl,
   2676                                        xy, xytext, textcoords="offset points",
   2677                                        ha=ha, va=va, **kwargs)

TypeError: matplotlib.axes._axes.Axes.annotate() got multiple values for keyword argument 'va'
```

IMO the feature request here should be "respect `ha`/`va` passed in by user, using the existing logic to set _defaults_. It's relevant for more general usecases too because it's reasonable to want "edge" style bar labels that are inside the bar rather than above it (i.e. like this, which currently requires fine-tuning of the padding to looks good):

![image](https://user-images.githubusercontent.com/315810/153419537-9935ea7f-07a4-4ba4-8f5a-5a9850fe28f3.png)

**Comment by Valdes-Tresanco-MS** [comment]
Thanks for your reply.
In some cases, putting the label inside the bar may not be suitable, for example when the representation of the bar is small. In this case, the label will overlap the borders and could significantly hinder the display.

I think that the alignment should be handled internally without the need for the user to take into account if the axis was inverted to define it.
As I see the `bar_label` method handles this according to whether the data value is positive or negative. My proposal is the following:

This internal function gets if the data is positive or not. 
https://github.com/matplotlib/matplotlib/blob/541a7867ad35cad2c1d7f20905edbda7087a09a6/lib/matplotlib/axes/_axes.py#L2609-L2612

Here we check if the axis is inverted and if the orientation is horizontal as this orientation should not change the alignment
```python
# want to know whether to put label on positive or negative direction
# cannot use np.sign here because it will return 0 if x == 0
a, b = self.yaxis.get_view_interval()
inverted = a > b
def sign(x, orientation='vertical'):
    if inverted and orientation=='vertical':
        return -1 if x >= 0 else 1
    else:
        return 1 if x >= 0 else -1
```
https://github.com/matplotlib/matplotlib/blob/541a7867ad35cad2c1d7f20905edbda7087a09a6/lib/matplotlib/axes/_axes.py#L2667-L2680
Here, when the alignment is set, we check if the axis was inverted
```python
if orientation == "vertical":
    xytext = 0, sign(dat) * padding
else:
    xytext = sign(dat, orientation) * padding, 0

if label_type == "center":
    ha, va = "center", "center"
elif label_type == "edge":
    if orientation == "vertical":
        ha = 'center'
        if inverted:
            va = 'top' if dat > 0 else 'bottom'  # also handles NaN
        else:
            va = 'top' if dat < 0 else 'bottom'  # also handles NaN
    elif orientation == "horizontal":
        ha = 'right' if dat < 0 else 'left'  # also handles NaN
        va = 'center'
```

Now work as expected.
``` python
f, axes = plt.subplots(2, 2)
(ax1, ax2), (ax3, ax4) = axes
bars1 = ax1.bar(["a", "b", "c", "d"], [1, 2, 3, -3])
ax1.bar_label(bars1, padding=3)
ax1.set_title('Vertical Normal yaxis')

bars2 = ax2.bar(["a", "b", "c", "d"], [1, 2, 3, -3])
ax2.invert_yaxis()
ax2.bar_label(bars2, padding=3)
ax2.set_title('Vertical Inverted yaxis')

bars3 = ax3.barh(["a", "b", "c", "d"], [1, 2, 3, -3])
ax3.bar_label(bars3, padding=3)
ax3.set_title('Horizontal Normal yaxis')

bars4 = ax4.barh(["a", "b", "c", "d"], [1, 2, 3, -3])
ax4.invert_yaxis()
ax4.bar_label(bars4, padding=3)
ax4.set_title('Horizontal Inverted yaxis')
```
![Figure_1](https://user-images.githubusercontent.com/36672242/153465435-6d8ad827-2601-4191-8056-8a79134441dc.png)

Happy to open a PR if you consider this as the solution.
Mario

**Comment by Valdes-Tresanco-MS** [comment]
I noticed now that, I have to consider if the x-axis is inverted for the case of horizontal bars, but basically, it would be similar to the previous one, so I could implement it

**Comment by Valdes-Tresanco-MS** [comment]
Sure

**Comment by mwaskom** [comment]
IMO would also be good to fix the ha/va hard coding even if you also want to deal with the more complicated inversion logic

**Comment by Valdes-Tresanco-MS** [comment]
@mwaskom Agree with you, but that would take further code review, which is out of my hands (I don't have time :( ). The solution I proposed fixes the bug, at least superficially until your suggestion can be implemented

**Comment by mwaskom** [comment]
The solution to my thing is quite simple, you'd just add `ha`/`va` to `kwargs` with `set_default` rather than passing directly. But you have no obligation to volunteer more time than you have available, of course.

**Comment by timhoffm** [comment]
@mwaskom do you want to move your comment to a separate issue so that it doesn't get lost?
