### ISSUE TITLE
[Bug]: Default colorbar tick values still used when specifying custom tick values

### ISSUE THREAD

**Issue by bhilbert4** [matplotlib/matplotlib#22425]
### Bug summary

I'm trying to display an image with an accompanying colorbar. I have defined a custom list of tick values as well as tick labels for the colorbar. However, when I create the figure, the colorbar shows both the custom ticks and ticklabels as well as the ticks and ticklabels that would be used by default (i.e. if no custom ticks were defined.) Am I not calling something correctly?

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors

# Create image
image = np.random.random((256, 2048))

# Set the figure size
fig, ax = plt.subplots(figsize=(8, 6))

shiftmin = 1
shiftmax = 2

cax = ax.imshow(image, norm=colors.LogNorm(vmin=shiftmin,vmax=shiftmax), cmap='viridis')
plt.gca().invert_yaxis()

tickvals = np.logspace(np.log10(shiftmin), np.log10(shiftmax), 5)

format_string = "%.3f"
tlabelstr = [format_string % number for number in tickvals]

cbar = fig.colorbar(cax, ticks=tickvals, format=format_string, location='right', fraction=0.2, extend='both', label='something')
cbar.set_ticklabels(tlabelstr)
ax.set_xlabel('Pixels')
ax.set_ylabel('Pixels')
plt.show()
```

### Actual outcome

<img width="609" alt="Screen Shot 2022-02-07 at 10 34 43 AM" src="https://user-images.githubusercontent.com/11775426/152819628-f9046306-a301-4955-ab3b-2fc4e5bc288d.png">

### Expected outcome

I expected to see a figure as above, but without the ticks and ticklabels that are in scientific notation. My input ticklabels are [1.000, 1.189, 1.414, 1.682, 2.000]

### Additional information

I don't recall seeing this issue when I originally wrote the code a couple of years ago.

### Operating system

OSX 10.15

### Matplotlib Version

3.5.1

### Matplotlib Backend

MacOSX, also agg

### Python version

3.8.5

### Installation

pip

**Comment by jklymak** [comment]
The extra labeled ticks are actually minor ticks because your colors dont span a factor of 10.  The same thing would happen for any axis.  I think you can remove the ticks set_ticks([], which='minor')

**Comment by bhilbert4** [comment]
Thanks. That seems to remove my specified ticks, but not the default ticks though. I guess it makes sense that it also considers my ticks as minor since they don't span a factor of 10?

**Comment by jklymak** [comment]
That's correct - this is the same behaviour with a normal axes as well...
