### ISSUE TITLE
axes limits with aspect='equal'

### ISSUE THREAD

**Issue by akhmerov** [matplotlib/matplotlib#2243]
When `axes` `aspect='equal'`, an axis with zero extent might not have any padding, which results in a completely scrambled plot. To reproduce:

    from matplotlib import pyplot
    fig = pyplot.figure()
    ax = fig.subplot(111, aspect='equal')
    ax.scatter([0, 0], [1, 0])  # Change to ax.plot([0, 0]) for something that works ok
    pyplot.show()  # A plot with one of the axes having size zero.

I am not completely sure what is the extent of this bug. `plot` of a horisontal line with  `aspect='equal'` produces a properly padded plot.

**Comment by efiring** [comment]
Maps and images are examples of cases where adjustable=box is desired.  I don't see any compelling reason to change the default--and I am pretty sure it would break quite a lot of existing user code.  The scatter example here is a corner case, and it easy to deal with it.  Therefore I am going to close this.
