### ISSUE TITLE
Embed EPS/SVG in Matplotlib figure and ensure that they remain in vector format in the final output.

### ISSUE THREAD

**Issue by hongyi-zhao** [matplotlib/matplotlib#22455]
I've an EPS file named as `f6mmP.eps`, which is slightly edited from [this eps file](https://www.cryst.ehu.es/cryst/kvec/fig/f6mmP.ps) by inkscape, as shown below: 

![image](https://user-images.githubusercontent.com/11155854/153702639-cee7509a-1d45-4d74-9cd6-0962631dc686.png)

Now, I want to embed the above EPS file in one of my Matplotlib figure and ensure that it remains in vector format in the final output. Based on the guidance/comment [here](https://moonbooks.org/Articles/How-to-insert-an-image-a-picture-or-a-photo-in-a-matplotlib-figure/) and [here](https://stackoverflow.com/a/35164285), I figured out  the following code snippet:

```python
from matplotlib.offsetbox import TextArea, DrawingArea, OffsetImage, AnnotationBbox

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

fig, ax = plt.subplots()

ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

arr_lena = mpimg.imread('f6mmP.eps')

imagebox = OffsetImage(arr_lena, zoom=0.5)

ab = AnnotationBbox(imagebox, (0.8, 0.6))

ax.add_artist(ab)

plt.grid()

plt.draw()
plt.savefig("my_test.eps")
plt.show()
```

However, the EPS file embedded using the above method seems very blurred in the final result file, as shown below:

![image](https://user-images.githubusercontent.com/11155854/153702652-3eb3afae-5f88-412a-a9f8-cf81666a6bb5.png)

So, I want to know if I can embed an EPS/SVG in Matplotlib figure and ensure that they remain in vector format in the final output.

See [here](https://discuss.python.org/t/embed-eps-svg-in-matplotlib-figure-and-ensure-that-they-remain-in-vector-format-in-the-final-output/13670) for related discussions.

Regards,
HZ

**Comment by jklymak** [comment]
You cannot embed a vector graphic in a matplotlib figure directly.  You are embedding a bitmapped version.  I'll close here and suggest if you have more usage question that you post at discourse.matplotlib.org.  Thanks.

**Comment by hongyi-zhao** [comment]
I've noticed the following packages which aim to do the similar job discussed here:

https://github.com/btel/svg_utils
https://github.com/whitead/skunk
