### ISSUE TITLE
[Bug]: pyplot.legend() cannot adjust the fontsize of the title

### ISSUE THREAD

**Issue by orange-Nan** [matplotlib/matplotlib#22461]
### Bug summary

I want to adjust the fontsize of the legend title to fit the content of my image. 
I tried to use 'prop' and 'fontsize', but they can only adjust the font of the legend.

### Code for reproduction

```python
wa1.legend(fontsize=15,bbox_to_anchor=(0.94,-0.25),title='wind speed in each direction',borderpad=0.5,labelspacing=0.4)
```

### Actual outcome

![windrose](https://user-images.githubusercontent.com/71633656/153745104-1ab9d95b-5d07-46e1-b135-3b031bcdc255.jpg)

### Expected outcome

I know that I can make my legend title font look bigger by making the figure size smaller, but this will make the image less sharp, which is not what I want.

### Operating system

Windows

### Matplotlib Version

3.5.0

### Python version

3.8.12

### Installation

pip

**Comment by timhoffm** [comment]
There is a separate `title_fontsize` parameter: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html?highlight=legend#matplotlib.pyplot.legend

**Comment by orange-Nan** [comment]
Thank you very much for your reply. I have solved this problem.
