### ISSUE TITLE
[Bug]: formlayout fails on PyQt6 due to the unqualified enum ShowAlphaChannel in class ColorButton

### ISSUE THREAD

**Issue by MAKOMO** [matplotlib/matplotlib#22471]
### Bug summary

```QtWidgets.QColorDialog.ShowAlphaChannel```

needs to be qualified on PyQt6 as

```QtWidgets.QColorDialog.ColorDialogOption.ShowAlphaChannel```

in class ColorButton (backends/qt_editor/_formlayout.py)

or the ```_enum()``` magic needs to be applied.

### Code for reproduction

```python
Open figureoptions:figure_edit and click one of those color edit buttons
```

### Actual outcome

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/backends/qt_editor/_formlayout.py", line 74, in choose_color
    QtWidgets.QColorDialog.ShowAlphaChannel)
AttributeError: type object 'QColorDialog' has no attribute 'ShowAlphaChannel'
```

### Expected outcome

The color chooser dialog of the operating system should open

### Operating system

tested on macOS but should affect all platforms

### Matplotlib Version

3.5.1 and trunk

### Matplotlib Backend

PyQt6

### Python version

3.10.2

### Installation

pip

**Comment by QuLogic** [comment]
Probably `_enum`; would you like to open a PR with that change?

**Comment by MAKOMO** [comment]
Could you just quickly raise such a PR. For me it is too troublesome currently. Thanks!

**Comment by MAKOMO** [comment]
PR #22479 created
