### ISSUE TITLE
[Bug]: Subsequent scatter plots work incorrectly

### ISSUE THREAD

**Issue by nakhodnov17** [matplotlib/matplotlib#22470]
### Bug summary

Two subsequent scatter plots produce incorrect output when calling first scatter with [0], [0] argument.  Other arguments for first scatter plot (eg. [1], [1]) seems to produce correct output.

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt

plt.scatter([0], [0])
plt.scatter([3], [3])
plt.savefig(f'test_v{matplotlib.__version__}_{matplotlib.get_backend()}.jpg')
```

### Actual outcome

![test_v3 5 1_TkAgg](https://user-images.githubusercontent.com/32146790/153923934-f344ee9c-17a1-4330-aaad-cc920028e1e3.jpg)

### Expected outcome

![test_v3 4 3_TkAgg](https://user-images.githubusercontent.com/32146790/153923941-98c8eb0f-34a2-4365-b87e-6ca43eaf9d54.jpg)

### Additional information

I can reproduce this behaviour on Windows and Ubuntu for matplotlib versions >= 3.5.0 and for different backends.

### Operating system

Ubuntu

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

Python 3.9.7

### Installation

conda

**Comment by anntzer** [comment]
I can confirm the problem; this bisects to 1f4708b310 (#20717).
