### ISSUE TITLE
[Bug]: Contourf unable to plot row of integers in array with mostly nans

### ISSUE THREAD

**Issue by jdldeauna** [matplotlib/matplotlib#22522]
### Bug summary

Contourf can't plot integer values if they are present in a single row in array of mostly NaNs. 

### Code for reproduction

```python
import numpy as np
from matplotlib import pyplot as plt

a = np.empty((10,10))
a[:] = np.nan
a[9] = 1
plt.contourf(a, hatches=['\\'])

```

### Actual outcome

![Actual outcome](https://user-images.githubusercontent.com/67194538/155012044-5cffc0c5-1981-46c6-a258-94bf2b98a499.png)

### Expected outcome

This is the result if two rows are integers:
```python
a = np.empty((10,10))
a[:] = np.nan
a[[8,9]] = 1
plt.contourf(a, hatches=['\\'])
```
![Expected outcome](https://user-images.githubusercontent.com/67194538/155012067-f6aa7be1-d553-4c49-9665-2a178d9e92f0.png)

### Matplotlib Version

3.5.1

**Comment by jklymak** [comment]
This is expected behaviour - contour find contours between well-defined data points - if there is NaN there is nowhere for that line to go.  Our algorithm is described here: https://en.wikipedia.org/wiki/Marching_squares  I'm not sure what action you want here.

**Comment by jdldeauna** [comment]
Thank you for the response! I wasn't aware of the Marching squares algorithm. I think I will need to find alternatives to contourf for plotting this type of dataset.
