### ISSUE TITLE
[Bug]: unable to install matplotlib

### ISSUE THREAD

**Issue by Lilpablo999** [matplotlib/matplotlib#22524]
### Bug summary

please help i was unable to install matplotlib 
 here is the error i got 

### Code for reproduction

```python
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.3.4)
```

### Actual outcome

Python 3.9.8 (main, Nov  7 2021, 15:47:09) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print (matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'matplotlib' is not defined
>>> 

### Expected outcome

Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.3.4)

### Matplotlib Version

>> print (matplotlib.__version__) Traceback (most recent call last):   File "<stdin>", line 1, in <module> NameError: name 'matplotlib' is not defined >>>

**Comment by ksunden** [comment]
I believe you are missing the import of matplotlib:

```python
Python 3.10.0 (default, Oct  5 2021, 10:39:14) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> matplotlib.__version__  # Reproduce the behavior you identify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'matplotlib' is not defined
>>> 
>>> 
>>> # Now import matplotlib so the python session loads the library
>>> import matplotlib
>>> matplotlib.__version__
'3.5.1'
>>> 
```

**Comment by Lilpablo999** [comment]
am try to install matplotlib please here is the error i got 
 pip install matplotlib
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.3.4)

**Comment by jklymak** [comment]
Please take this to discourse.matplotlib.org.  Thanks!
