### ISSUE TITLE
[Doc]: 

### ISSUE THREAD

**Issue by gituser789** [matplotlib/matplotlib#22526]
### Documentation Link

https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_qt_sgskip.html

### Problem

Incomplete command
```
from matplotlib.backends.backend_qtagg import (
    FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
```

### Suggested improvement

```
from matplotlib.backends.backend_qtagg import (FigureCanvasQTAgg as FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
```

**Comment by anntzer** [comment]
This is not needed; FigureCanvas is the standard name by which a backend exports a canvas class.
(Also the code just works fine to me?)
