### ISSUE TITLE
aplpy with zoomed_inset_axes not showing contour plot

### ISSUE THREAD

**Issue by vmahat** [matplotlib/matplotlib#22531]
I have an issue using aplpy combined with zoomed_inset_axes to show an image with contours, and then a zoom-in of the same image with the same contours. The main image with contours shows correctly, and the inset of the main image shows correctly, however the contours are not being plot in the inset for some reason:

`fig_zoom=plt.figure()`
`fig=aplpy.FITSFigure(image,figure=fig_zoom,north=True)`
`fitscontour=fits.open(contours)`
`fig.show_contour(fitscontour,levels=contour_levels,colors=contourcolor,dimensions=[0,1],slices=[0]) #This shows image with contours correctly`

`axes=fig_zoom.axes[0]`
`axins=zoomed_inset_axes(axes,zoom=2,loc=1)`
`axins.imshow(image,cmap=cmap, norm=LogNorm(vmin=mean+vminfactor*noise,vmax=vmax*vmaxfactor)) #This shows inset of main image correctly`
`axins.contour(fitscontour,levels=contour_levels,colors=contourcolor,dimensions=[0,1],slices=[0]) #This does not show any contours in the inset image`

Any ideas why the contours of the inset are not being plot?

**Comment by jklymak** [comment]
You are mixing a fits method (whatever that is) and matplotlib methods.  I don't think this is actionable on our side.
