### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lewisc2** [matplotlib/matplotlib#22538]
### Bug summary

Using a macbook (Monterey version 12.2.1) I exported plots as pdfs and they looked fine in powerpoint. I then put the powerpoint file on a thumbdrive to put the powerpoint on a PC. When I pulled up the powerpoint, the alphashape and the fill in the kde plots (see below) was not retained in the plot.

### Code for reproduction

```python
import os
import sys
from descartes import PolygonPatch
import matplotlib.pyplot as plt
import alphashape
import pandas as pd
import numpy as np
import seaborn as sns


array = np.random.randint(10,90,(10,3))

df = pd.DataFrame(array, index=np.arange(10), columns=['a','b','c'])

length = len(df)
myfield = np.zeros((length,2))
myfield[:,0] = df.a
myfield[:,1] = df.b
#make the polygon
mypolygon = alphashape.alphashape(myfield,0.001).buffer(0.5)

fig, ax = plt.subplots(1,1, figsize = (10,8))

ax.plot(df.a,df.b,'.',c='grey')
ax.add_patch(PolygonPatch(mypolygon, alpha=0.2, fc='k',ec='k',label='label'))

plt.tight_layout()
#plt.savefig('path.pdf',format = 'pdf',dpi = 500,bbox_inches = 'tight')

fig, ax = plt.subplots(1,1, figsize = (10,8))
sns.kdeplot(df.c, bw_method='silverman', ax=ax, color='darkkhaki', fill=True, alpha=0.5, label='label')
#plt.savefig('path_II.pdf',format = 'pdf',dpi = 500,bbox_inches = 'tight')
```

### Actual outcome

I no longer have access to the PC, unfortunately. 

### Expected outcome

<img width="732" alt="Screen Shot 2022-02-22 at 3 18 02 PM" src="https://user-images.githubusercontent.com/65908927/155236010-b088ee39-f7f9-4562-9e8d-d8677b9be555.png">
<img width="632" alt="Screen Shot 2022-02-22 at 3 18 10 PM" src="https://user-images.githubusercontent.com/65908927/155236029-cd7ec39c-a011-43d4-a43d-adea671bc69d.png">

### Operating system

OS/X Monterey v12.2.1

### Matplotlib Version

3.4.3

### Python version

3.9.7

### Installation

pip

**Comment by greglucas** [comment]
I don't think there is anything we can do here. It sounds like a powerpoint issue, and there are often problems with transferring those files between Mac and PC. Maybe try transferring the PDF directly rather than embedded in the powerpoint. Feel free to reopen if you can identify a reproducible example.
