### ISSUE TITLE
matplotlib makes python lose focus

### ISSUE THREAD

**Issue by ibell** [matplotlib/matplotlib#2253]
This seems to have cropped up roundabout 1.2.1, and I tried to see whether it worked in 1.3rc5, but I couldn't get 1.3rc5 to work at all.  A topic for another ticket.

When you use matplotlib and do a plot, python loses focus. I think it might be spawning another process which momentarily gets focus, but I can't tell.  The end result is that matplotlib results in python getting and losing focus, which is very annoying if for instance you have a long-running batch which is doing plotting and you are trying to do other things on the computer.

**Comment by QuLogic** [comment]
IIUC, this is covered by the `figure.raise_window` rcParam.
