### ISSUE TITLE
[Doc]: Erroneous legend

### ISSUE THREAD

**Issue by ugGit** [matplotlib/matplotlib#22535]
### Documentation Link

https://matplotlib.org/stable/api/figure_api.html?highlight=figure#module-matplotlib.figure

### Problem

Disclaimer: not sure if doc was the right tag

I'm currently trying to implement a radar chart. It works as intended in the example from the docs. However, already the example contains a bug: the legend is wrong.
![image](https://user-images.githubusercontent.com/22294372/155176432-391b3d9c-64ad-460c-85db-23920670fd91.png)

As visible on the screenshot above, the color/icons of the legend are not corresponding to the graph. It looks like the lines and the content (fill) of the polygons are treated separately and therefore listed as single elements in the legend.

### Suggested improvement

Show for each data either the line color or filling color.

**Comment by anntzer** [comment]
This is fixed as of master: https://matplotlib.org/devdocs/gallery/specialty_plots/radar_chart.html.

**Comment by tacaswell** [comment]
Do we need / want to backport the fix to this for 3.5.x?

**Comment by anntzer** [comment]
It's a doc only fix, see https://github.com/matplotlib/matplotlib/pull/22458.

**Comment by QuLogic** [comment]
That PR was already backported to 3.5.x.
