### ISSUE TITLE
"extend" keyword of matplotlib.colors.BoundaryNorm broken

### ISSUE THREAD

**Issue by JosjaVanBever** [matplotlib/matplotlib#22533]
It seems like the 'extend' keyword of the matplotlib.colors.BoundaryNorm constructor got broken. A minimal example is shown below.

    user@computer:~$ python
    Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
    [GCC 9.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy as np
    >>> import matplotlib.colors as colors
    >>> bounds = np.linspace(0, 2, 11)
    >>> norm = colors.BoundaryNorm(boundaries=bounds, ncolors=256, extend='max')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: __init__() got an unexpected keyword argument 'extend'
    >>> 

See also https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.BoundaryNorm.html and https://github.com/matplotlib/matplotlib/issues/4850.

**Comment by oscargus** [comment]
I cannot seem to reproduce it. What does 
```
import matplotlib as mpl
mpl.__version__
```
return?

**Comment by JosjaVanBever** [comment]
Ok, this might explain it. On apt under ubuntu 20 LTS, the most recent stable release is '3.1.2'.

Apologizes. Are there simple ways to get a more recent version?
