### ISSUE TITLE
[Bug]: mathmode in ylabels

### ISSUE THREAD

**Issue by JPelda** [matplotlib/matplotlib#22551]
### Bug summary

If using mathmode in y-labels and in particular \sum or \frac, the legend is not expanded to the real figure bbox_to_anchor=(0, 0, 1, 0) outside the figure. That means the legend frame is not in line with the y-labels. This occurs also if a second y axis is set with
ax2 = ax.twinx()

### Code for reproduction

```python
fig, ax = plt.subplots()

ax.plot([1,2,3], label='test')
ax.set_ylabel(r'$C^{\frac{\sum^{n}_{i=1} A}{\sum^{n}_{i=1} B}}$')

# If not using plt.tight_layout(...) it is even worse.
plt.tight_layout(pad=0.02, w_pad=0.5, h_pad=.5)

fig.legend(loc='upper left', bbox_to_anchor=(0, -0.02, 1, 0),
                        fancybox=True, shadow=False,
                        ncol=3, borderaxespad=0,
                        framealpha=1, mode='expand')

fig.savefig('test.pdf', backend='pgf', bbox_inches='tight', pad_inches=0.02)
```

### Actual outcome

![Unbenannt](https://user-images.githubusercontent.com/22002057/155505600-1779c338-314c-4f40-82c7-dbf9b12e7877.PNG)

### Expected outcome

The should be no white space between the figures edge and the legend frame.

### Operating system

Windoof 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

3.7

### Installation

conda

**Comment by anntzer** [comment]
FWIW I cannot reproduce the problem(?)

**Comment by JPelda** [comment]
Thank you for the fast answer! I found out, that if setting
matplotlib.use('pgf')
at the very start of the program everything is fine.

**Comment by timhoffm** [comment]
> Maybe it matters, which matplotlib.stylesheet is used.

Likely, this is what I get:

![grafik](https://user-images.githubusercontent.com/2836374/156941786-e4849362-3fa2-4650-ac5b-359c2d9340de.png)

Do you have a custom matplotlibrc file? If so, please try removing it and add relvant changes to the example code above to make it reproducible for us.

**Comment by JPelda** [comment]
Strange thing, I can nether reproduce the problem myself, too. Tried the same console, same settings, etc. However, meanwhile I changed also some installation so I really can not find the original settings where the above mentioned problem occurred. Sorry.
