### ISSUE TITLE
XKCD-style doesn't work with LineCollection

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#2255]
The following code:

```
import numpy as np

from matplotlib import pyplot as plt
from matplotlib.collections import LineCollection

plt.xkcd()

lc = LineCollection([([[0.3,0.3], [0.3, 0.7]])])

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.add_collection(lc)
ax.set_xlim(0., 1.)
ax.set_ylim(0., 1.)
fig.savefig('test.png')
```

produces the following plot:

![test](https://f.cloud.github.com/assets/314716/868523/1dae6e80-f7aa-11e2-9a66-b36bba4292a8.png)

i.e. the blue line is not xicdified. Is there an easy way to fix this?

cc @jakevdp

**Comment by liangz0707** [comment]
@mdboom  I meet this problem when use "PatchCollection". I want to know if it be changed know?

**Comment by tacaswell** [comment]
Same idea, create each patch independently.
