### ISSUE TITLE
Can't import plot_directive in Python 3

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#2256]
I haven't yet figured out if this is an issue with Sphinx or Matplotlib, but when building some documentation in Python 3 that requires the `plot_directive`, I get:

```
Running Sphinx v1.1.3

Extension error:
Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'exceptions')
```

which is not very informative. This is with the latest dev versions of Matplotlib and Sphinx.

**Comment by 935749995haji** [comment]
I have the same problem.Can anyone tell me how to slove this problem in detail? Thanks a lot.

**Comment by WeatherGod** [comment]
This particular problem has been solved for a long time. You might have a
different one that results in the same failure. Could you please open a new
bug report with more details?
