### ISSUE TITLE
[Bug]: Replacement for epoch2num behaves differently (does not accept arrays)

### ISSUE THREAD

**Issue by laolux** [matplotlib/matplotlib#22579]
### Bug summary

matplotlib.dates.epoch2num is deprecated. The new method suggested in the deprecation warning behaves differently: It does not accept arrays.

### Code for reproduction

```python
import matplotlib
import matplotlib.dates
import numpy
datelist = numpy.zeros((2))
datelist[0] = 123456789
datelist[1] = 123456789.1
print(matplotlib.dates.epoch2num(datelist))
import datetime
print(matplotlib.dates.date2num(matplotlib.dates.datetime.datetime.utcfromtimestamp(datelist)))
```

### Actual outcome

The new method crashes with
`TypeError: only integer scalar arrays can be converted to a scalar index`

### Expected outcome

The new method returns the same result as `epoch2num`: An numpy array with the correct values from the conversion.

### Additional information

Workaround by hand is to convert the input array entry for entry and write it to an output array. Works, but is potentially slower (depending on the internals of `epoch2num`) and can be quite some work to implement everywhere where `epoch2num` needs to be replaced.

Note: everything works fine as long as only scalars are involved.

### Operating system

Fedora

### Matplotlib Version

3.5.1

### Python version

Python 3.10.2

### Installation

Linux package manager

**Comment by tacaswell** [comment]
The error here is coming from the Python standard library:

```python
datetime.datetime.utcfromtimestamp(datelist)
```

not taking numpy arrays.

If you want datetime objects in numpy array it may be better to use numpy `datetime64` types (see https://numpy.org/doc/stable/reference/arrays.datetime.html) which does work as expected with the new function:

```python
In [17]: import matplotlib
    ...: import matplotlib.dates
    ...: import numpy
    ...: datelist = numpy.array([1000*123456789,int(1000*123456789.1)] , dtype='datetime64[ms]')
    ...: # print(matplotlib.dates.epoch2num(datelist))
    ...: import datetime
    ...: print(matplotlib.dates.date2num(datelist))
[1428.89802083 1428.89802199]

```

----

@laolux What are you doing with these functions?  There may a better way to do it that avoids having to use them directly.

**Comment by laolux** [comment]
@tacaswell I am extracting data from a sqlite database where I store sensor data (temperature etc) alongside with a timestamp. So I get the data as an Nx2 array. Then I use `matplotlib.dates.epoch2num` to convert the timestamps and plot them with `plot_date(converted_timestamp, data)`. So nothing very fancy and I can use the workaround as sketched above. I just noticed the deprecation warning, tried the suggested replacement and when that failed I decided to report it as a bug. So I do not need this functionality, but other users might.

Maybe it is easier to just share my code to show my use case. Be advised, it is far from beautiful, but oh well... Feel free to criticize, feel free to ignore.

    import sqlite3
    import numpy as np
    import matplotlib
    import matplotlib.dates
    import matplotlib.pyplot as plt
    import datetime
    
    def sqlite_import(filename, tablename):
        db = sqlite3.connect(filename)
        cur = db.cursor()
        cur.execute(f'select * from {tablename}')
        res = cur.fetchall()
        return np.array(res)
    
    def main():
        primary_temperature_data = sqlite_import(filename='sensor_data.db',
                                                 tablename='primary_temperature_data')
        primary_pressure_data = sqlite_import(filename='sensor_data.db',
                                                 tablename='primary_pressure_data')
        primary_humidity_data = sqlite_import(filename='sensor_data.db',
                                                 tablename='primary_humidity_data')
        times_temperature = matplotlib.dates.epoch2num((primary_temperature_data[:,0]))
        print(primary_temperature_data[10,0])
        #times_temperature = matplotlib.dates.date2num(datetime.datetime.utcfromtimestamp(primary_temperature_data[:,0]))
        times_pressure = matplotlib.dates.epoch2num(primary_pressure_data[:,0]) # can be different number of entries
        times_humidity = matplotlib.dates.epoch2num(primary_humidity_data[:,0]) # can be different number of entries
        # Sensor data recording is not perfect.
        # If the server is unavailable at the wrong time, then maybe one value is not transmitted yet and lost.
        fig = plt.figure(figsize=(30/2.54, 20/2.54))
        ax = fig.add_subplot(221)
        ax.plot_date(times_temperature, primary_temperature_data[:,1])
        ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter("%d.%m %H:%M"))
        ax.set_ylabel('Temperature')
        ax2 = fig.add_subplot(222, sharex=ax)
        ax2.plot_date(times_pressure, primary_pressure_data[:,1])
        ax2.xaxis.set_major_formatter(matplotlib.dates.DateFormatter("%d.%m %H:%M"))
        ax2.set_ylabel('Pressure')
        ax3 = fig.add_subplot(223, sharex=ax)
        ax3.plot_date(times_humidity, primary_humidity_data[:,1])
        ax3.xaxis.set_major_formatter(matplotlib.dates.DateFormatter("%d.%m %H:%M"))
        ax3.set_ylabel('Humidity')
        fig.autofmt_xdate()
        fig.tight_layout()
        plt.show()
    
    if __name__ == '__main__':
        main()

The data can be found here. Sorry, did not know any better way to share a sqlite file.

https://mega.nz/file/whkV2a5R#yvXsPit45_7e4o0M4mzE_rlguGRa4ubZF6L5ISMSOEQ

**Comment by tacaswell** [comment]
@laolux I think the best "fix" for you is to not directly use the functions in `matpltolib.dates`.  You can use `datetime.datetime` to process the timestamps -> datetime objects or use `np.datetime64`.  Which ever way you go, you can then pass that result directly to `ax.plot(times, data)` and we should "do the right thing".  I think this will make your code work with all (recent) versions of Matplotlib and reduce the complexity of your code.

You might also like `plt.subplot_mosaic` to help do your Axes layout ;)
