### ISSUE TITLE
[ENH]: Provide `axis('equal')` for `Axes3D`.

### ISSUE THREAD

**Issue by patquem** [matplotlib/matplotlib#22570]
### Bug summary

In the example below, I wish to observe a unitary 3D cube in its diagonal axis (1, 1, 1). 
azimut and elevation angle should be both 45°, normally. 
Why do I need to set elevation = 28° ????
Thanks,
Patrick

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 3, figsize=(15, 5),
                       subplot_kw=dict(projection="3d",
                                       proj_type='ortho'))

ax[0].voxels(np.ones((1, 1, 1)), facecolors=[0, 0, 0, 0], edgecolors='k')
ax[0].quiver(0, 0, 0, 1, 1, 1, color='r', linewidth=5)

ax[1].set_title("azim=45°, elev=45°")
ax[1].voxels(np.ones((1, 1, 1)), facecolors=[0, 0, 0, 0], edgecolors='k')
ax[1].view_init(azim=45, elev=45)
ax[1].quiver(0, 0, 0, 1, 1, 1, color='r', linewidth=5)

ax[2].set_title("azim=45°, elev=28°")
ax[2].voxels(np.ones((1, 1, 1)), facecolors=[0, 0, 0, 0], edgecolors='k')
ax[2].view_init(azim=45, elev=28)
ax[2].quiver(0, 0, 0, 1, 1, 1, color='r', linewidth=5)

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/16154687/155963232-a1a75e0a-0a37-4f07-bce3-e58e458bbcdb.png)

### Expected outcome

view_init(azim=45, elev=45) and not view_init(azim=45, elev=28) to have the expected 3D representation

### Operating system

Windows

### Matplotlib Version

3.4.2

### Python version

Python 3.7.7

### Installation

pip

**Comment by oscargus** [comment]
Ideally, it should be possible to do `ax[1].axis('equal')` to obtain what you are looking for (see https://matplotlib.org/stable/gallery/subplots_axes_and_figures/axis_equal_demo.html). However, `Axes3D` does not (yet) support that:

```
Traceback (most recent call last):

  Input In [18] in <module>
    ax[1].axis('equal')

  File /local/data1/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_base.py:2047 in axis
    self.set_aspect('equal', adjustable='datalim')

  File /local/data1/miniconda3/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py:311 in set_aspect
    raise NotImplementedError(

NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.
```

**Comment by oscargus** [comment]
You can get a bit closer by using: `ax[1].set_box_aspect((4, 4, 4))`, but it is still not exact. (Of course, you can probably find a better value for the last number, but that is about as bad as 28 degrees...) Now it at least looks like a cube.

**Comment by patquem** [comment]
Hi @oscargus,
Thanks for your reply. 
using ax[1].set_box_aspect((4, 4, 4)), the elevation angle to set is now 32°. It's better but not enough.
Whatever the solution to be developed (axis('equal') ?), elev=45° should satisfy the correct elevation angle of view, not an approximated one.
I hope you will be able to find a solution to fix that.

**Comment by patquem** [comment]
The values that allow to recover the correct elevation angle are :  `ax.set_box_aspect((1, 1, np.sqrt(2))`
but working with this box_aspect, the shape are obviously stretched along the z-axis. 
This can not be the solution :(

```
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(2, 2, figsize=(9, 10),
                       subplot_kw=dict(projection="3d",
                                       proj_type='ortho'))


def plot(ax, box_aspect, azim, elev):
    ax.scatter(0, 0, 0, s=50)
    ax.scatter(1, 1, 1, s=50)
    ax.voxels(np.ones((1, 1, 1)), facecolors=[0, 0, 0, 0], ec='k',
              ls=(0, (5, 10)))
    ax.set_box_aspect(box_aspect)
    ax.view_init(azim=azim, elev=elev)
    ax.set_title(f"box_aspect={np.round(box_aspect, 2)}\n"
                 f"azim={azim}, elev={elev}")


plot(ax[0][0], (1., 1., 1.), None, None)
plot(ax[0][1], (1., 1., 1.), 45, 45)
plot(ax[1][0], (1., 1., np.sqrt(2.)), None, None)
plot(ax[1][1], (1., 1., np.sqrt(2.)), 45, 45)

plt.show()
```
![image](https://user-images.githubusercontent.com/16154687/156178724-3bf19c05-fcfd-46f1-ad9b-289214b1667d.png)

**Comment by jondo** [comment]
B.t.w., this is a successor of  #1077.
