### ISSUE TITLE
[Bug]: FontManager.addfont doesn't accept pathlib.Path of TTF font

### ISSUE THREAD

**Issue by twm** [matplotlib/matplotlib#22582]
### Bug summary

The [`FontManager.addfont()`](https://github.com/matplotlib/matplotlib/blob/710fce3df95e22701bd68bf6af2c8adbc9d67a79/lib/matplotlib/font_manager.py#L1077-L1094) method is documented as accepting a path-like, but if a path-like for a .ttf font file is passed it raises `TypeError`

### Code for reproduction

```python
from pathlib import Path
from matplotlib import get_data_path, __version__
from matplotlib.font_manager import fontManager

path = Path(get_data_path()) / "fonts" / "ttf" / "cmr10.ttf"

print("matplotlib", __version__)
fontManager.addfont(str(path))  # Works
print("str ok")
fontManager.addfont(path)  # TypeError
print("path ok")
```

### Actual outcome

```
matplotlib 3.5.1
str ok
Traceback (most recent call last):
  File "/home/twm/dev/roofs/repro.py", line 10, in <module>
    fontManager.addfont(path)  # TypeError
  File "/home/twm/dev/roofs/venv/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1092, in addfont
    font = ft2font.FT2Font(path)
TypeError: First argument must be a path or binary-mode file object
```

### Expected outcome

```
matplotlib 3.5.1
str ok
path ok
```

### Additional information

It looks like the simplest fix would be to convert path-likes to `str` since [`FT2Font` is implemented in C++](https://github.com/matplotlib/matplotlib/blob/9197433d50ed77c37a2d5fcb4e0a3f4b26112c8e/src/ft2font.cpp).

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.9.5

### Jupyter version

N/A

### Installation

pip

**Comment by oscargus** [comment]
The easy fix seems to be replacing `path` with `str(path)` in 
https://github.com/matplotlib/matplotlib/blob/a8534072ccf123c2651336b003baa1e4ce47a481/lib/matplotlib/font_manager.py#L1100

but probably the same thing will happen for an afm-font. Which means that maybe the right thing is to simplify convert path to a string before the if, `path = str(path)` (and then convert it back to a `Path` when checking the suffix...). Or change the documentation to clarify what path-like means.

**Comment by timhoffm** [comment]
We should support `Path` as a parameter to `addfont()`.

Both, `FT2Font()` and `afmFontProperty()` should receive a str. You can do either `path = str(path)` at the top, or `str(path)` in both calls. Either way seems fine.
