### ISSUE TITLE
[Bug]: matplotlib hangs on windows Github Action

### ISSUE THREAD

**Issue by tdegeus** [matplotlib/matplotlib#22616]
### Bug summary

On my CI, `matplotlib` hangs without output

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
plt.close(fig)
```

### Actual outcome

Matplotlib hangs indefinitely (no output). See CI on https://github.com/tdegeus/test_matplotlib

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

3.10.2

### Installation

conda

**Comment by tacaswell** [comment]
Do you actually need the GUI windows?   If not, then forcing to a non-GUI backend (like `matplotlib.use('agg')`)  may solve your problem.

If you do in fact need the GUI window, taking a look at what we do (https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/tests/test_backends_interactive.py)  to get GUIs to run on CI.

Can you add some print statements to sort out exactly which line is is hanging on, vary `plt.ion()` vs `plt.ioff()`, adding `plt.show(block=False)`, `plt.pause(5)`, and/or running manually running the Qt main loop (either directly or through our wrappers)?

We do not run any windows via GHA (but we do via azure pipelines) so unfortunately we do not have a clear example of this working.

**Comment by tdegeus** [comment]
Thanks for you response @tacaswell . I can confirm that with
```yaml
    - name: Set matplotlib backend
       run: echo "MPLBACKEND=Agg" >> $GITHUB_ENV
```
everything works. Thanks for that!

I should note however that my CI on GHA has been working well for quite some time. So did it start failing because the default backend recently changed? Or is there a bug with the backend? 

I can do some more debugging. However, I don't really know how to further reduce code than
```python
fig, ax = plt.subplots()
```
with already hangs with `QtAgg`.

**Comment by tacaswell** [comment]
My guess is that this in as artifact of the recent update to the windows image that GHA uses.

The next thing to check is if you can create a qApp and start it in the same context (I suspect that is what is going wrong, but if that works then it is something on the mpl side).

**Comment by timhoffm** [comment]
Closing for lack of response.
