### ISSUE TITLE
[Bug]: I want  to give title to the every subplot

### ISSUE THREAD

**Issue by satya0210** [matplotlib/matplotlib#22621]
### Bug summary

i have 42 plots by using loop i have created those plots now i just to give title to the each plot

### Code for reproduction

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
fig,ax=plt.subplots(nrows=7,ncols=6,figsize=(16,12),sharex=True,sharey=True,tight_layout=True)
title =["JANUARY","FEBRURY","MARCH","APRIL",'MARCH','APRIL','MAY','JUNE','JULY','AGUST','SEPTEMBER','OCT','NOV','DEC']
ax=ax.ravel()
for i in range(0,42):
    ax[i].plot(tf.iloc[:,0],tf.iloc[:,i+1],color="blue")
     plt.gca().set_title(title[i])
```

### Actual outcome

titles are not applying on the suplots

### Expected outcome

titles with figures

### Matplotlib Version

matplotlib   2.3.4

### Python version

python3

**Comment by QuLogic** [comment]
I'm not really sure what you're asking, but for user questions please post on Discourse https://discourse.matplotlib.org

**Comment by satya0210** [comment]
Thank you for your response.
