### ISSUE TITLE
[Bug]: The x-axis ticks overlapping  on each other 

### ISSUE THREAD

**Issue by haritha1022** [matplotlib/matplotlib#22620]
### Bug summary

![one](https://user-images.githubusercontent.com/97615200/157181948-c51612d3-4a01-4d95-8ed1-9524a0505545.png)
I want to plot subplots to each when I created loop and  tried to plot the x-axis overlap on each  other because the are many values as shown in figure

### Code for reproduction

```python
import pandas as pd
import matplotlib.pyplot as pyplot
import numpy as np
df=pd.read_table('C:\\Users\\91960\\OneDrive\\Desktop\\SK\\SU_BULKRICH_2014.txt')
plt.plot(fn.loc[fn['mm']==1]['dd/tt'],fn.loc[fn['mm']==1]['BRIG'])
plt.xticks(rotation=45)
plt.savefig('jan.eps')
plt.title('january')
```

### Actual outcome

the x-axis ticks overlapping on each other  in the figure

### Expected outcome

how can i get neat and clear x-axis ticks

### Operating system

windows

### Matplotlib Version

matplotlib   2.3.4

### Python version

python3

**Comment by timhoffm** [comment]
Please check, whether this solves your issue: https://matplotlib.org/devdocs/users/faq/howto_faq.html#why-do-i-have-so-many-ticks-and-or-why-are-they-out-of-order

**Comment by haritha1022** [comment]
axs[i].xaxis.set_major_locator(ticker.MultipleLocator(tick_spacing))
this is the command that i have used sir

**Comment by jklymak** [comment]
Please take user help to discourse.matplotlib.org.  Thanks for your understanding!

**Comment by haritha1022** [comment]
Thanks, I'll check it out.

**Comment by haritha1022** [comment]
Thank you for your Response sir
i have seen the link that you send  I tried to give major tickers to avoid
overlapping but it doesn't work
I am very new to python o am unable find the right way to avoid this
overlapping
