### ISSUE TITLE
[ENH]: support rect with constrained_layout ("layout only to part of the figure")

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22623]
### Problem

tight_layout supports a rect option ("layout axes so that they fit within this rect instead of filling the entire figure").  It could be nice if constrained_layout also supported that.

As an example use case, requested by @jklymak on gitter:
```python
from pylab import *

fig = figure(layout="constrained")
axs = fig.subplots(1, 3)
for ax in axs:
    for i in range(3):
        ax.plot(rand(3), rand(3), label=f"dataset {i}")
axs[1].legend(ncol=3, loc="lower center", bbox_to_anchor=(0.5, 1.0))

fig = figure(layout="constrained")
axs = fig.subplots(1, 3)
for ax in axs:
    for i in range(3):
        ax.plot(rand(3), rand(3), label=f"dataset {i}")
fig.legend(handles=axs[0].lines, ncol=3, loc="upper center")

show()
```
This draws e.g. three different coordinates of three datasets, and tries to have a single one-line legend at the center top.

The first try gives
![1](https://user-images.githubusercontent.com/1322974/157240217-d0b6107f-f4c0-4a8c-a63e-da26454adbc5.png)
i.e. it would work if set_in_layout could be used to take the legend's y extent, but not its x extent (now that I think of it, that may be the better solution).
The second try gives
![2](https://user-images.githubusercontent.com/1322974/157240367-48ecbf43-cad2-48c1-b31d-a2a127563dd2.png)
which is where I think a rect option would work to avoid the axes overlapping the legend (you'd have to tweak the value a bit manually, though, to specify the upper bound of the rect).  (Perhaps not the nicest solution, but "could work when you just want to get a plot done".)

**Comment by jklymak** [comment]
See also #19743, though I'm not sure that always works.  

However, I can imagine this is a reasonable request for many other reasons.  Not sure how easy it is to achieve...
