### ISSUE TITLE
[ENH]: enable passing of projection keyword to Axes.inset_axes

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#22630]
### Problem

Most methods to create an `Axes` instance (e.g. [Figure.add_axes](https://matplotlib.org/stable/api/figure_api.html?highlight=add_axes#matplotlib.figure.Figure.add_axes), [pyplot.subplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html?highlight=subplot#matplotlib.pyplot.subplot)) allow passing of the `projection` keyword in order to return an instance of a subclass of `Axes`.  It would be useful if [Axes.inset_axes](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.inset_axes.html?highlight=inset_axes#matplotlib.axes.Axes.inset_axes) could do the same.

See also #22608 where there was some agreement that this would be useful, but that was not the right solution.

### Proposed solution

I'm unfamilar with the Matplotlib codebase, but I _think_ the relevant functionality is contained within [Figure._process_projection_requirements](https://github.com/matplotlib/matplotlib/blob/09b17b128440e18cec4a0958dd2dc5b86c9bd146/lib/matplotlib/figure.py#L1524).  So perhaps `inset_axes` could reuse that somehow.

**Comment by mylasem** [comment]
I am working on this one!
