### ISSUE TITLE
[ENH]: MacOSX backend to use sRGB instead of GenericRGB colorspace

### ISSUE THREAD

**Issue by remia** [matplotlib/matplotlib#22638]
### Problem

When using the MacOSX backend, the window is currently tagged with the [GenericRGB](https://github.com/matplotlib/matplotlib/blob/main/src/_macosx.m#L1208) colour space. This colour space is not really common anymore and sRGB should probably be preferred. This produce unexpected results after Apple ColorSync convert your pixel data to the display profile if you are unaware of this unusual choice.

### Proposed solution

Replacing the [GenericRGB](https://developer.apple.com/documentation/coregraphics/kcgcolorspacegenericrgb) space by [sRGB](https://developer.apple.com/documentation/coregraphics/kcgcolorspacesrgb), as suggested in the Apple documentation.

**Comment by greglucas** [comment]
Seems reasonable, care to open a PR with that fix?
