### ISSUE TITLE
Leave color parameter empty should be fine[ENH]: 

### ISSUE THREAD

**Issue by iszhi** [matplotlib/matplotlib#22662]
### Problem

Sometimes, I want to leave the facecolor empty to avoid overlap with other point and at the same time, I don't want to use alpha parameter since it will change the color actually. What I want is to ask you if you can remove the warning _"MatplotlibDeprecationWarning: Using a string of single character colors as a color sequence is deprecated. Use an explicit list instead."_

```python
import matplotlib.pyplot as plt

plt.scatter([0,1,2],[1,1,1],s=500,marker='o',edgecolor='k',c='')
plt.scatter([0,1,2],[1,1,1],s=50,marker='o',edgecolor='b',c='')

plt.show()
```

**Comment by oscargus** [comment]
Note that this raises an error in recent versions.

You can just pass an empty list instead:

```
import matplotlib.pyplot as plt

plt.scatter([0,1,2],[1,1,1],s=500,marker='o',edgecolor='k',c=[])
plt.scatter([0,1,2],[1,1,1],s=50,marker='o',edgecolor='b',c=[])

plt.show()
```

or None depending on what you want to achieve.

Although one can discuss if these two checks should change order:
https://github.com/matplotlib/matplotlib/blob/96af8c52c7beb373c1970cd71916e0c6e1231db7/lib/matplotlib/colors.py#L364-L370

It is not clear if an empty string should be considered "a string of single character colors" or not.

**Comment by tacaswell** [comment]
You want to spell this as:

```python
import matplotlib.pyplot as plt

plt.scatter([0,1,2],[1,1,1],s=500,marker='o',edgecolor='k',color='none')
plt.scatter([0,1,2],[1,1,1],s=50,marker='o',edgecolor='b',color='none')

plt.show()
```

as `'none'` not `''` is the correct spelling for "no color" (and has a short-cut to turn it into a 0 length array https://github.com/matplotlib/matplotlib/blob/96af8c52c7beb373c1970cd71916e0c6e1231db7/lib/matplotlib/colors.py#L350-L355).

**Comment by oscargus** [comment]
> separate check for an empty string

Swapping the two if-clauses in the code I linked would solve it. But I agree that it is not the way to go.

**Comment by oscargus** [comment]
I improved the error message for passing an empty string so that it is obvious what the correct way of doing it is. See #22665

**Comment by iszhi** [comment]
Many thanks for the above answers and the improvement work. As making a summary, both of `c="none"` and `c=[]` won't raise warning anymore.
