### ISSUE TITLE
[Doc]: Dash.app can't display the image

### ISSUE THREAD

**Issue by duckbill** [matplotlib/matplotlib#22660]
### Problem

* I download the matplotlib3.5.1 on my Dash.app in macbook pro. The document about all the image not displayed! and I change the matplotlib3.4.3, it worked well! So I think the version 3.5.1 may have some mistakes!

*  And my macpro version is 10.14.6,and my Dash.app version is 4.6.7.

**Comment by tacaswell** [comment]
@duckbill There is not enough information here to help you.  I think you are refering to https://kapeli.com/dash (which I was not aware existing until just now)?  If that is the case, please direct this report to them as we do not support third-party commercial products.

If you are referring to plotly dash, I still think this report should go to them first.

In either case, if there are specific unintentional changes or regressions in the Matplotlib library or the way we build the documentation we can talk about either reverting them or making sure down stream tools adapt.  However as-is this is not actionable.  

If I have miss-understood please ask to have this re-opened!
