### ISSUE TITLE
[Bug]: Contour artifacts outside bounds

### ISSUE THREAD

**Issue by jschueller** [matplotlib/matplotlib#22661]
### Bug summary

when plotting multiple coutours with legend some artifacts show outside the graph bounds

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import math as m

fig = plt.figure()
ax = fig.add_subplot(111)
levels= [1.72892e-05,0.000135817,0.00036173,0.000818297,0.00185113,0.00393889,0.00928167,0.0205726,0.0484776,0.103152]
nx=50
ny=50
x = np.linspace(-3.5,3.5,nx)
y = np.linspace(-3.5,3.5,ny)
X, Y = np.meshgrid(x, y)
Z = np.zeros((nx,ny))
for i in range(nx):
    for j in range(ny):
        Z[i,j]=1.0/(2.0*m.pi)*m.exp(-0.5*(x[i]**2+y[j]**2))
for level in levels:
    contourset = ax.contour(X, Y, Z, levels=[level])
    contourset.collections[0].set_label(str(level))
ax.legend()
plt.show()
fig.savefig('/tmp/contour_bug.png')
```

### Actual outcome

![ct_bug](https://user-images.githubusercontent.com/3832365/158764330-3024f1a9-58a5-4df6-a401-c1f83fea92d0.png)

### Expected outcome

no artifacts on the top-right corner

### Additional information

this worked in earlier versions, but reverting to 3.5.0 or 3.5.1 didnt help
we also had windows reports
doesnt happen if the legend is disabled
switching to tkagg didnt help

### Operating system

Archlinux

### Matplotlib Version

3.5.2

### Matplotlib Backend

QtAgg

### Python version

3.10.2

### Jupyter version

NA

### Installation

Linux package manager

**Comment by oscargus** [comment]
See #11134 (although the latest comments seem to indicate that at some stage set_label was a better option).

You can do something like this instead:

```
import numpy as np
import matplotlib.pyplot as plt
import math as m

fig = plt.figure()
ax = fig.add_subplot(111)
levels= [1.72892e-05,0.000135817,0.00036173,0.000818297,0.00185113,0.00393889,0.00928167,0.0205726,0.0484776,0.103152]
nx=50
ny=50
x = np.linspace(-3.5,3.5,nx)
y = np.linspace(-3.5,3.5,ny)
X, Y = np.meshgrid(x, y)
Z = np.zeros((nx,ny))
for i in range(nx):
    for j in range(ny):
        Z[i,j]=1.0/(2.0*m.pi)*m.exp(-0.5*(x[i]**2+y[j]**2))
leg_elem = []
for level in levels:
    contourset = ax.contour(X, Y, Z, levels=[level])
    e, _ = contourset.legend_elements()
    leg_elem.append(e[0])    
ax.legend(leg_elem, list(map(str, levels)))
plt.show()
```

**Comment by oscargus** [comment]
A guess to why this happens is that (as far as I can tell), the legend wants lines for the markers and using your approach it only sets that paths. So the contour artifacts are actually the line markers of the legend, but since they are paths instead of lines they show up in an "unusual" position.

**Comment by jschueller** [comment]
thanks for the answer, I fixed our code by specifying handles from legend_elements() to ax.legend as you suggested and this works for us
