### ISSUE TITLE
legend show error ？

### ISSUE THREAD

**Issue by henryccl** [matplotlib/matplotlib#22664]
### Bug summary

I using following code to plot a curve, but the legend showed doesn't match the color and marker in the plot. Why?

### Code for reproduction

```python
`import numpy as np
import matplotlib.pyplot as plt
import json


def plot_curve(path=r"test2.json", plot_word=["loss", "accu"]):

    # matplotlib marker config
    marker_list = [">", "<", "o", "v", "p", "+", "*", ".", ","]
    color_list = ["deepskyblue", "deeppink", "springgreen", "tomato", "wheat"]
    np.random.shuffle(marker_list)
    marker_list = marker_list[:len(plot_word)]
    word_marker_dict = dict(zip(plot_word, marker_list))

    # train
    with open(path, "r") as f:
        lines = f.readlines()
    legend_dict = []

    for w in plot_word:
        word_box = []
        epoch_box = []
        for i, l in enumerate(lines):
            data_dict = json.loads(l)
            if i != 0 and data_dict["mode"] == "train":
                epoch_box.append(data_dict["epoch"])
                word_box.append(data_dict[w])
        plt.plot(epoch_box, word_box)
        plt.plot(epoch_box, word_box, c=color_list[0], marker=word_marker_dict[w])
        legend_dict.append("train " + w)

    # val
    for w in plot_word:
        word_box = []
        epoch_box = []
        for i, l in enumerate(lines):
            data_dict = json.loads(l)
            if i != 0 and data_dict["mode"] == "val":
                epoch_box.append(data_dict["epoch"])
                word_box.append(data_dict[w])
        plt.plot(epoch_box, word_box, c=color_list[1], marker=word_marker_dict[w])
        legend_dict.append("val " + w)

    plt.legend(legend_dict)
    plt.savefig("tt")
    plt.show()


if __name__ == '__main__':
    plot_curve()`



The content of test2.json are as follow:
`{"epoch": 1, "mode": "train", "loss": 0.987, "accu": 0.76}
{"epoch": 2, "mode": "train", "loss": 0.187, "accu": 0.56}
{"epoch": 3, "mode": "train", "loss": 0.987, "accu": 0.86}
{"epoch": 4, "mode": "train", "loss": 0.487, "accu": 0.66}
{"epoch": 5, "mode": "train", "loss": 0.987, "accu": 0.86}
{"epoch": 5, "mode": "val", "loss": 0.687, "accu": 0.86}
{"epoch": 6, "mode": "train", "loss": 0.987, "accu": 0.76}
{"epoch": 7, "mode": "train", "loss": 0.787, "accu": 0.86}
{"epoch": 8, "mode": "train", "loss": 0.987, "accu": 0.26}
{"epoch": 9, "mode": "train", "loss": 0.987, "accu": 0.86}
{"epoch": 10, "mode": "train", "loss": 0.987, "accu": 0.86}
{"epoch": 10, "mode": "val", "loss": 0.787, "accu": 0.16}`
```

### Actual outcome

![image](https://user-images.githubusercontent.com/44051761/158943302-f75f363b-10e4-410b-b003-4d164f4a6683.png)

### Expected outcome

Normal plot

### Matplotlib Version

3.5.1

**Comment by raphaelquast** [comment]
hey, I'm no matplotlib dev but since I read your issue I thought I'll quickly respond 😅 

- either use `plt.plot(label="adsf")` and later `plt.legend()`  (names & patches will be assigned accordingly)
- or use 
```python
l1, = plt.plot(...)
l2, = plt.plot(...)
plt.legend([l1, l2], ["label1", "label2"])
```

--- 

The way how you try to assign your labels does NOT assure correct order and is explicitly descouraged in the docs:
> This call signature is discouraged, because the relation between plot elements and labels is only implicit by their order and can easily be mixed up.
```
ax.plot([1, 2, 3])
ax.plot([5, 6, 7])
 ax.legend(['First line', 'Second line'])
```
see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html for more details.

**Comment by henryccl** [comment]
oh！Thank you for your detailed answer！And my problem has been solved.

**Comment by aminevsaziz** [comment]
> hey, I'm no matplotlib dev but since I read your issue I thought I'll quickly respond 😅
> 
> * either use `plt.plot(label="adsf")` and later `plt.legend()`  (names & patches will be assigned accordingly)
> * or use
> 
> ```python
> l1, = plt.plot(...)
> l2, = plt.plot(...)
> plt.legend([l1, l2], ["label1", "label2"])
> ```
> 
> The way how you try to assign your labels does NOT assure correct order and is explicitly descouraged in the docs:
> 
> > This call signature is discouraged, because the relation between plot elements and labels is only implicit by their order and can easily be mixed up.
> 
> ```
> ax.plot([1, 2, 3])
> ax.plot([5, 6, 7])
>  ax.legend(['First line', 'Second line'])
> ```
> 
> see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html for more details.

Interesting🙌
