### ISSUE TITLE
[Doc]: plot_format adaption invalidates sphinx cache

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#22671]
### Problem

https://github.com/matplotlib/matplotlib/pull/20730/commits/76d4a3ef38ad968cd8f1c9dacc7d7df2a2bead6b introduced a reduction of the plot formats (if 'html' docs: only 'png'; if 'latex' docs: only 'pdf'). The implementation does the config change delayed via the hook ` app.connect('builder-inited', reduce_plot_formats)`. Unfortunately this makes sphinx always believe that the config changed:

> updating environment: [config changed ('plot_formats')] 1757 added, 4 changed, 0 removed

This is basically irrelevant for CI, where we always build docs from scratch, but it increases the build time for local incremental builds significantly, and thus makes local doc building and thus documentation work quite annoying.

**Comment by anntzer** [comment]
Probably needs something like
```patch
diff --git i/lib/matplotlib/sphinxext/plot_directive.py w/lib/matplotlib/sphinxext/plot_directive.py
index 4024bccdde..e878aa5225 100644
--- i/lib/matplotlib/sphinxext/plot_directive.py
+++ w/lib/matplotlib/sphinxext/plot_directive.py
@@ -547,6 +547,12 @@ def get_plot_formats(config):
             formats.append((str(fmt[0]), int(fmt[1])))
         else:
             raise PlotError('invalid image format "%r" in plot_formats' % fmt)
+    # Rename "is_release_build" in conf.py to "not is_matplotlib_dev_build".
+    if getattr(config, "is_matplotlib_dev_build"):
+        if setup.app.builder.name == "html":
+            formats = [(fmt, dpi) for fmt, dpi in formats if fmt == "html"]
+        elif setup.app.builder.name == "latex":
+            ...
     return formats
```
?

**Comment by timhoffm** [comment]
Alternatively:
```
build_target = ('html' if 'html' in sys.argv else
                'latex' if 'latex' in sys.argv else
                'other')

plot_formats = {
    'html': [('png', 100)],
    'latex': [('pdf', 100)],
    'other': [('png', 100), ('pdf', 100)] 
}[build_target]
```

That `sys.argv` check is a bit wonky, but on the plus side we have explicit declarative `plot_formats` and don't need to do any live-patching of the formats.

**Comment by tacaswell** [comment]
`make html latex` is also valid so probably merged them?
