### ISSUE TITLE
[Bug]: plt.show resizes figure after Python upgrade to 3.9.11

### ISSUE THREAD

**Issue by silvertonsils** [matplotlib/matplotlib#22688]
### Bug summary

I recently updated Python from 3.9.x (not sure which one, seem to recall quite low number, maybe 3.9.2-ish?) to 3.9.11.

I was working on drawing shapes to a Matplotlib figure, using primarily figure methods and avoiding axes methods because of the autoscaling feature keeping resizing the axis limits. However, now whenever I plt.show anything, it resizes the figure dimensions!! For example, with a 640x480 figure, I immediately do plt.show() and it resizes the figure to 800x600!!! This results in any centred shapes being moved to the bottom left quadrant!!!

Immediately prior to the plt.show() a ‘print (fig)’ instruction still shows a 640x480 figure (0 Axes), while immediately after it shows a 800x600 figure (still 0 Axes).

What’s going on?!!!?

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure()
print (fig)
plt.show()
print (fig)
```

### Actual outcome

========== RESTART: C:/Users/Owner/Documents/Python/3D Pyplot/test2.py =========
Figure(640x480)
Figure(800x600)

### Expected outcome

========== RESTART: C:/Users/Owner/Documents/Python/3D Pyplot/test2.py =========
Figure(640x480)
Figure(640x480)

### Additional information

Previously worked fine on earlier version of Python 3.9.x (possibly 3.9.2?). Have developed multiple files progressing through various stages of development, but then got bogged down tryng to figure why my maths was wrong and shapes all kept ending up towards bottom left quadrant! Finally boiled it down to this issue.

Have tried various attempts at disabling autoscaling on Axes, and reducing margins etc., but nothing seems to help

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.9.11

### Jupyter version

n/a

### Installation

pip

**Comment by tacaswell** [comment]
This is likely due to a change in the tk version interacting with the high-dpi support. 

Do you have to rely on placing things in pixel and place them in one of the other coordinate systems?

**Comment by QuLogic** [comment]
800x600 / 640x480 is 1.25; is your display at 1.25 scaling? Otherwise, it's not HiDPI support that's triggering it.

**Comment by silvertonsils** [comment]
> 



> This is likely due to a change in the tk version interacting with the high-dpi support.
> 
> Do you have to rely on placing things in pixel and place them in one of the other coordinate systems?

Prefer to use Figure methods and use (what I thought was a fixed scale) pixel-oriented positions, to avoid any potential axes rescaling. Seemed simpler than having to keep swapping co-ordinate systems. Worked fine on previous version, having done something like 20 different .py files working through various stages. Then when updated Python minor version, it all went horribly wrong :'(
May try backtracking through earlier minor versions to isolate it, or even try version 3.10 (but then need to re-install packages cos they all disappear!!)? :'(

**Comment by tacaswell** [comment]
Without knowing what you are doing it is very hard to give good advise, but if you want to work at the figure level, you can still use 'figure fraction" an say "I want to put this an the center (0.5, 0.5) of the Figure" which will always be at the center independent of the figure size or dpi.   

See https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html for an overview of the various coordinate systems you can work with in general and https://matplotlib.org/stable/tutorials/text/annotations.html#using-complex-coordinates-with-annotations if you want to place things a spcefic distance from other things.

Placing things in pixels is not robust against resizing the figure (Matplotlib's canonical view of the figure size is in inches which makes sense if you start from the point of view of making journal article figures for print)  but also against changing the DPI (which can happen when you save the figure).  Additionally, Matplotlib can write out to vector formats (like svg/pdf/eps) where the notion of "pixel" is fuzzy at best.  If it worked before, that was mostly due to luck rather than something we guarantee will work.

----


> because Matplotlib's base unit is pixels.

I do not agree with this.  The transforms target "screen units" which in the case of the Agg renderers happens to be pixels.

**Comment by jklymak** [comment]
> I do not agree with this. The transforms target "screen units" which in the case of the Agg renderers happens to be pixels.

The Identity transform is documented to be in pixels...

https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html

```
The pixel coordinate system of the display window; (0, 0) is bottom left of the window, and (width, height) is top right of the display window in pixels.
```

... though I agree the analogy breaks down for vector backends.  However, the point is that pixels is a brittle co-ordinate system, whereas an inch is an inch (or 2.54 cm).  Of course users can also scale their displays to non-native resolutions, but if they do that presumably they expect a 10 point font to look smaller or larger that 10/72 inches.

**Comment by tacaswell** [comment]
Hmm, then I think we should re-word that bit of the tutorial.  My understanding is that our `Transform` objects do not have any notion of units (they are "just" matrices or functions) so it is up to the human to keep track of what the input / output spaces are without the aid of the computer. 

In the case of "display" because you are already in the final coordinate system, the transform to get you there is the identity.

**Comment by silvertonsils** [comment]
Many thanks to all of you who responded. All of the information is very useful.

For your information, I was trying to draw 3D objects in a figure (I wanted to exercise my vector and matrix maths, and deal with motion and rotation and all that juicy stuff!). So I wanted to use the entire figure size with no axis lines, and no space allocated for axis labels, lines or margins. I know they can be turned off, but all that seemed to get a bit messy, and using Figure methods seemed so much easier.

I am also aware that maybe matplotlib is not the best tool for doing this, but I've started now, so I'll finish ... :-P

I would like to summarise what I've managed to boil the problem down to:
1. My PC was set at 125% display scaling and resolution in Windows settings (marked as 'recommended')
2. Previously, with an older version of Python 3.9.x, I had no problems, but on upgrading to 3.9.11 matplotlib kept resizing the figure after first draw (640x480 to 800x600) [I presume it was the associated upgrade of Matplotlib that changed things, but I initially associated it to the Python upgrade]
3. After further investigation (as an ex-software engineer of MANY years, I am very conscious of isolating problems down to the bare minimum for re-creation by others!), I reset it back to 100%, rebooted the PC (not sure if this was necessary) and re-tried the problems - they were all fixed. Figure size was preserved at 640x480 after drawing again. I noticed that the problem seemed to be that DPI was being reset from 100 (default) to 125 (presumably grabbed from Windows setting).

However, I would also like to make some observations as a user:
1. If I set the figure dimensions (size and DPI), they should be respected and preserved after draw/show regardless of system settings. Otherwise, all item positions and dimensions are being corrupted, and either have to be recalculated or a draw/show initiated before any calculations are done
2. I'm not sure, but I have concerns that any subsequent draw/plot may result in yet another rescaling
3. If matplotlib wants to take into account any system scaling, then maybe that should affect the 'default' values of DPI that are used by calls. I seem to recall that manually setting the DPI to 125 still resulted in a figure rescaling and change of DPI.
4. As a user, I expect any 'system' operations to be transparent. If I set a figure size/DPI, I expect that to BE the figure size/DPI.

I will also investigate the 'figure fraction' method of positioning too. That sounds interesting.

Again, many thanks to all who responded. I am very grateful. I'll let you know how I get on

**Comment by silvertonsils** [comment]
Further update:

Just tried at 125% display scaling again.

If I set DPI to 125 first, then figure size/scaling seems to be preserved. Just need to figure out how to get system DPI first and then set figure DPI before do any drawing.

`
import matplotlib.pyplot as plt

fig=plt.figure()
fig
<Figure size 640x480 with 0 Axes>
fig.get_dpi()
100.0
fig.set_dpi(125)
fig.get_dpi()
125
fig.get_size_inches()
array([6.4, 4.8])
fig
<Figure size 800x600 with 1 Axes>
plt.show()
fig
<Figure size 800x600 with 1 Axes>
fig.get_dpi()
125
fig.get_size_inches()
array([6.4, 4.8])
`

**Comment by silvertonsils** [comment]
Managed to find a workaround (hesitate to call it a solution, as I still think the underlying behaviour is inconsistent)!!!

If I force a figure draw initially using `plt.pause(1)` or `plt.waitforbuttonpress(1)`, then the figure gets updated and the dpi changed. From then on I can use 'figure' methods as expected. Unfortunately, a `plt.show(block=False)` is insufficient - it still leaves the dpi unchanged, then any subsequent draw again updates the dpi and messes up object positioning/size on figure.

```
fig=plt.figure()                # default 640x480 at 100 dpi
print('Initial figure:',fig)
##plt.waitforbuttonpress(1)
plt.pause(1)                    # 'pause' forces dpi to display scaling
##plt.show(block=False)           # 'show' doesn't force dpi
print('After "show":',fig)      # changes to 125 dpi at 125%, so 800x600
                                # to maintain physical size
```

this gives expected output:
> Initial figure: Figure(640x480)
> After "show": Figure(800x600)

I also changed to using 'figure'-relative positioning using 'ax.transData' to transform for 'figure' co-ordinates [0 to 1] to 'display' co-ordinates (pixels) [800x600]:

```
> # use transform to derive physical position in figure (pixels)
> centre=fig.transFigure.transform_point([0.5,0.5])
> print('Centre in "figure" co-ordinates: [0.5, 0.5]')
> print('Centre transformed into "display" co-ordinates (pixels)', centre)
> 
> # draw circle at 'centre', but using figure to maintain aspect ratio
> print('Draw 50 pixel circle positioned at centre of screen.')
> fig.patches.append(Circle(centre, radius=50))
> plt.show(block=False)
```

**BUT THIS ONLY WORKED PROPERLY AFTER AGAIN TRIGGERING DPI UPDATE AS ABOVE**

> Centre in "figure" co-ordinates: [0.5, 0.5]
> Centre transformed into "display" co-ordinates (pixels) [400. 300.]
> Draw 50 pixel circle positioned at centre of screen.


So my latest approach is:
1. Force initial draw using `plt.pause(1)` [has to be 1 sec, 0 doesn't do it]. This updates dpi setting
2. Use figure-relative positioning and transform to display/pixel co-ordinates for positioning objects in figure
3. Use display/pixel-relative co-ordinates for object-relative sizes
4. Use **figure** methods for drawing to display/pixel co-ordinates

Again, many thanks for all those who stepped up to answer!!

**Comment by silvertonsils** [comment]
> Without knowing what you are doing it is very hard to give good advise, but if you want to work at the figure level, you can still use 'figure fraction" an say "I want to put this an the center (0.5, 0.5) of the Figure" which will always be at the center independent of the figure size or dpi.

Sorry @tacaswell , but this is NOT THE CASE :'(

```
>>> import matplotlib.pyplot as plt
>>> from matplotlib.patches import Circle
>>> fig=plt.figure()
>>> fig.transFigure.transform([0.5,0.5])
array([320., 240.])
>>> centre=fig.transFigure.transform([0.5,0.5])
>>> fig.patches.append(Circle(centre,radius=100))
>>> plt.show()
```
This sets everything up with [640x480 at 100 dpi], but then draws it rescaled at [800x600 at 125 dpi], so the circle is left-downward shifted to origin

**Comment by greglucas** [comment]
1. For updating a figure you can specifically request a draw with `fig.canvas.draw()` or `fig.draw_without_rendering()`, so you shouldn't have to pause for any amount of time.
2. You have grabbed the transform object and done the transforms yourself before requesting a draw, so you are explicitly setting the location and not enabling updates. You should put the transform into the object so that it can stay in-sync with the draws. `Circle((0.5, 0.5), radius=0.2, transform=fig.transFigure)` You should be able to resize the figure window and see the Circle stay in the middle of the figure.

**Comment by silvertonsils** [comment]
@greglucas thanks for the reply. Unfortunately, this ends up with an oval 'circle', as n% of x-axis is not the same as n% of y-axis. This will always be the case with a standard aspect ratio. The only way around this is to force `ax.axis('equal')` or `ax.axis('square')`.

However, this was only an attempt to illustrate the underlying situation. I am attempting to preserve scaling of objects that have a predefined shape, across rotating and moving. The cleanest way I can do that without maintaining separate x- and y-axis 'unit steps' is by using pixel co-ordinates (so a 100x100 square stays 'square' regardless of orientation). The problem is that following a recent update, matplotlib now overrides the figure dpi setting after the initial `plt.show()` according to the system display scaling factor - so with my display set to 125% scaling, the 'default' 100 dpi gets changed to 125 dpi. This means all my carefully calculated pixel positions (and indeed 'figure' or 'display' based ones) get origin-shifted (left-down). This is what I was trying to demonstrate in the last post.

The only ways I've found to work around this are:
1. Force initial figure to have 125 dpi - but this isn't really flexible. If my display scaling changes, or I port my code to another machine it all goes wrong again.
2. Force a 'dummy' draw to trigger the dpi override BEFORE I do any positioning or calculations

**Comment by jklymak** [comment]
Try fig.dpi_scale_trans to specify perfect circles, regardless of dpi changes.

**Comment by jklymak** [comment]
See in particular:

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

fig=plt.figure()
# Make a 1-inch radius circle in the bottom left corner, just touching the edge
fig.patches.append(Circle([1, 1], radius=1, transform=fig.dpi_scale_trans))
plt.show()
```

Note how resizing the figure keeps the patch in the same absolute position and size.  This will also work if you change dpi because you move between screens with different dpi scaling.

**Comment by silvertonsils** [comment]
@jklymak  Many thanks for your reply  .

That's helpful for single- or low-quantity plots, but I'm looking at doing a constantly updating image, with possibly multiple 3D objects being projected onto the 2D screen (figure), and it gets quite long-winded putting in these long transform argument strings each time (yes, I know there's ways to shorten it - redefine methods, use literals, whatever - and I know Python/matplotlib are not really meant for dynamic image plotting, but rather one-off graph/diagram plotting for including in documents ... but I've started now, so I'll finish, and I'm stubborn and arrogant to believe I can do it!! :-P ).
For now, I've sort of reached an acceptable work around with an initial `plt.pause(0.1)` to trigger the initial rescale, and then just carry on with the new scaling.
