### ISSUE TITLE
[Bug]: DoubleClick not working for MouseEvent

### ISSUE THREAD

**Issue by raamana** [matplotlib/matplotlib#22681]
### Bug summary

Double Click is not getting recognized as `True` in `MouseEvent.dblclick`. 

I see them as two separate single clicks but the second one's `MouseEvent.dblclick` is False in MPL 3.5.1. It works fine on 3.5.0 and 3.4.3.

### Code for reproduction

Actual code is here in [VisualQC](https://github.com/raamana/visualqc/blob/92d06e1e6587df17e86cdcd0dcf27cd8d81d2516/visualqc/freesurfer.py#L173)

CLI instructions to reproduce from this codebase are rather complicated needing a lot of setup, unfortunately. But the simplest example to reproduce is here:

```python

from matplotlib import pyplot as plt
import numpy as np

def onclick(event):
    print('MouseEvent: button value {} name {} dblclk: {}'
          ''.format(event.button.value, event.button.name, event.dblclick))

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

cid = fig.canvas.mpl_connect('button_press_event', onclick)

fig.canvas.manager.show()
fig.canvas.draw_idle()

# starting a 'blocking' loop to let the user interact
fig.canvas.start_event_loop(timeout=-1)

fig.canvas.mpl_disconnect(cid)

```

### Actual outcome

<  single click >
MouseEvent: button value 1 name LEFT dblclk:
<  right click >
MouseEvent: button value 3 name RIGHT dblclk:
<  double click with trackpad on MacBook pro >
MouseEvent: button value 1 name LEFT dblclk:
MouseEvent: button value 1 name LEFT dblclk:
<  right click >
MouseEvent: button value 3 name RIGHT dblclk:
<  double click external mouse >
MouseEvent: button value 1 name LEFT dblclk:
MouseEvent: button value 1 name LEFT dblclk:

### Expected outcome

% single click 
MouseEvent: button value 1 name LEFT dblclk: False
< right click >
MouseEvent: button value 3 name RIGHT dblclk: False
<  double click with trackpad on MacBook pro >
MouseEvent: button value 2 name LEFT dblclk: True
<  right click >
MouseEvent: button value 3 name RIGHT dblclk: False
<  double click external mouse >
MouseEvent: button value 2 name LEFT dblclk: True

### Additional information

numpy 1.17.4 / scipy 1.1.0 / matplotlib 3.5.1
python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)]
platform Darwin-21.3.0-x86_64-i386-64bit
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

### Operating system

MacOS Darwin-21.3.0

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.7.2

### Installation

pip

**Comment by raamana** [comment]
ignore the `dblclick` part in the logging output as I didn't add a argument for it in the print statement but the main point remains.

**Comment by QuLogic** [comment]
Please provide a _complete_ example.

**Comment by raamana** [comment]
here you go! Sorry about that, I thought it would take lot more than what was needed.

```python

from matplotlib import pyplot as plt
import numpy as np

def onclick(event):
    print('MouseEvent: button value {} name {} dblclk: {}'
          ''.format(event.button.value, event.button.name, event.dblclick))

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

cid = fig.canvas.mpl_connect('button_press_event', onclick)

fig.canvas.manager.show()
fig.canvas.draw_idle()

# starting a 'blocking' loop to let the user interact
fig.canvas.start_event_loop(timeout=-1)

fig.canvas.mpl_disconnect(cid)

```

**Comment by raamana** [comment]
this is version info of various related packages:
```
numpy 1.17.4 / scipy 1.1.0 / matplotlib 3.5.1
python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)]
platform Darwin-21.3.0-x86_64-i386-64bit
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

```

**Comment by tacaswell** [comment]
We rely on the underlying GUI toolkit (in this case Tk) to determine if it is a double click https://github.com/matplotlib/matplotlib/blob/e3c819516689ce436e90cd11b1dd2948e7a5f6f2/lib/matplotlib/backends/_backend_tk.py#L186-L188 rather than trying to do the timing / debouncing our selves. 

Looking at https://web.archive.org/web/20201111211515id_/https://effbot.org/tkinterbook/tkinter-events-and-bindings.htm it indicates that:

> <Double-Button-1>
> Button 1 was double clicked. You can use Double or Triple as prefixes. Note that if you bind to both a single click (<Button-1>) and a double click, both bindings will be called.

This behavior is _roughly_ consistent with Qt6 (with qt6 clicking very fast alternates False / True, where as with Tk reports a double click if the previous click was "fast enough".

Unfortunately, I think this is the expected behavior.  I suspect you will have to do your own event de-bouncing (start a time on single click to do the single click action and cancel it on double click).
 
## tk vs qt


```python
from matplotlib import pyplot as plt
import numpy as np
import time

next_time = time.monotonic()
def onclick(event):
    global next_time
    last_time, next_time = next_time, time.monotonic()
    print(f'Δt = {next_time - last_time} MouseEvent: button value {event.button.value} name {event.button.name} dblclk: {event.dblclick}')

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

cid = fig.canvas.mpl_connect('button_press_event', onclick)

fig.canvas.manager.show()
fig.canvas.draw_idle()

# starting a 'blocking' loop to let the user interact
fig.canvas.start_event_loop(timeout=-1)

fig.canvas.mpl_disconnect(cid)

```
### qt
```
Δt = 1.6626579939984367 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.7177702879998833 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.619829313000082 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.4738164880036493 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.1262232259978191 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.39228243099933024 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.11260399300226709 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.3133027009971556 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.11402525199810043 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.45802419500250835 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.12989301799825625 MouseEvent: button value 1 name LEFT dblclk: True

```

### tk
```
Δt = 1.1145763840031577 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.6722701600010623 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.6034620790014742 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.13823219099867856 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.35866492799686966 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.12933389500540216 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.12844550099543994 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13769338899874128 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13583121199917514 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13768732600146905 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.16931153800396714 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.25327031099732267 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.15408681400003843 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13557181500073057 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.1707060429980629 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13582403400505427 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 5.6813316459956695 MouseEvent: button value 1 name LEFT dblclk: False


```

**Comment by QuLogic** [comment]
> Double Click is getting captured as two separate single clicks!

Oh, sorry I missed that you said this. That is definitely expected behaviour. A double click is a single click + a double click in most (all?) windowing toolkits. For example, from the GDK docs:

> Double and triple-clicks result in a sequence of events being received. For double-clicks the order of events will be:
>
> * `GDK_BUTTON_PRESS`
> * `GDK_BUTTON_RELEASE`
> * `GDK_BUTTON_PRESS`
> * `GDK_2BUTTON_PRESS`
> * `GDK_BUTTON_RELEASE`
>
> Note that the first click is received just like a normal button press, while the second click results in a `GDK_2BUTTON_PRESS` being received just after the `GDK_BUTTON_PRESS`.

In Qt, there is this note:

> Note: The widget will also receive mouse press and mouse release events in addition to the double click event. And if another widget that overlaps this widget disappears in response to press or release events, then this widget will only receive the double click event. It is up to the developer to ensure that the application interprets these events correctly.

**Comment by raamana** [comment]
so i just tested MPL 3.4.3 and 3.5.0, and the double click is recognized correctly, and that seems to be broken in 3.5.1

you're right that double click does generates two MouseEvents, but for my purposes it works because `event.dblclick` is True for the second event of the double click

**Comment by greglucas** [comment]
Just to clarify, you **never** receive a double click on 3.5.1 no matter how fast/slow you click?
Nothing jumps out to me in the version diff: https://github.com/matplotlib/matplotlib/compare/v3.5.0...v3.5.1

Some other possible things to check:
* Are you using the same Python and Tk versions in the 3.5.0 / 3.5.1 comparison?
* Is tk the only backend you're having issues with, or do macosx and qt backends have the same issues?

**Comment by raamana** [comment]
thanks @greglucas -- good point! can you tell me how to control the Tk versions for matplotlib? 

`pip show tkinter` doesn't show anything to me.

`import tkinter; tkinter.TkVersion` returns 8.6, same as TclVersion

**Comment by tacaswell** [comment]
the version of tk is controlled by who ever built Python for you.  My output above for close to the current main branch, this is with 3.5.1:

```python
$ ipython
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %matplotlib tk

In [2]: from matplotlib import pyplot as plt
   ...: import numpy as np
   ...: import time
   ...: 
   ...: next_time = time.monotonic()
   ...: def onclick(event):
   ...:     global next_time
   ...:     last_time, next_time = next_time, time.monotonic()
   ...:     print(f'Δt = {next_time - last_time} MouseEvent: button value {event.button.value} name {event.button.name} dblclk: {event.dblclick}')
   ...: 
   ...: fig, ax = plt.subplots()
   ...: ax.plot(np.random.rand(10))
   ...: 
   ...: cid = fig.canvas.mpl_connect('button_press_event', onclick)
   ...: 
   ...: fig.canvas.manager.show()
   ...: fig.canvas.draw_idle()
   ...: 
   ...: # starting a 'blocking' loop to let the user interact
   ...: fig.canvas.start_event_loop(timeout=-1)
   ...: 
   ...: fig.canvas.mpl_disconnect(cid)
Δt = 1.2224636229984753 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.4206599940007436 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.7403648319996137 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.11793542700070248 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.33819175899952825 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13985677900018345 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.1572449350005627 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.14999296699897968 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13636275700082479 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.16310802299994975 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.13144328300040797 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.15117090399871813 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.8309049649997178 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.26578765000158455 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.5675629069992283 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.14643023499957053 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.3879566569994495 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.12760672500007786 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.4407780390010885 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.1532936299990979 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.15614204600024095 MouseEvent: button value 1 name LEFT dblclk: True

In [4]: import matplotlib

In [5]: print(matplotlib.__version__)
3.5.1

In [7]: import tkinter

In [8]: print(tkinter.TkVersion)
8.6

In [9]: 


```

Can you run the version of this code with the timing?

**Comment by raamana** [comment]
Hey @tacaswell here is the result with timing. So after a bit of cleanup locally (.egg_info and __pycache__ etc), and reinstall of 3.5.1, it seems it works in the _toy_ script above. But it does not in my codebase for some reason. I am not sure what changed during this series of uninstall and install and cleanups, and it appears I am doing something in my codebase that doesn't set `MouseEvent.dblclick` to be True for the second mouse event of a double click. It did work for a few years before for older versions. Appreciate your help in locating the source of this issue.

```
Δt = 7.408150936 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 1.5759932479999996 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.17893176599999983 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 2.3836946070000007 MouseEvent: button value 3 name RIGHT dblclk: False
Δt = 2.552134412999999 MouseEvent: button value 3 name RIGHT dblclk: False
Δt = 0.18884820999999974 MouseEvent: button value 3 name RIGHT dblclk: True
Δt = 2.8419044300000014 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 1.8435534830000009 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.8805765779999994 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.16309317600000028 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.8311335589999977 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.17650670800000157 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.2242729059999995 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.17590394500000173 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 0.1425152539999992 MouseEvent: button value 1 name LEFT dblclk: True
Δt = 1.2920347419999985 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 1.7947408419999995 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.8464139360000011 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.9492331199999988 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 1.9615346000000002 MouseEvent: button value 1 name LEFT dblclk: False
Δt = 0.17476960700000177 MouseEvent: button value 1 name LEFT dblclk: True
```

**Comment by raamana** [comment]
two things I set in my library related to MPL, that are different from the toy script we ran, are below. I am not sure if they interact with MouseEvent code.

```python
import matplotlib

matplotlib.interactive(True)

# disabling all default keyboard shortcuts
for key in [k for k in plt.rcParams.keys() if k.startswith('keymap')]:
    plt.rcParams[key] = ''
```

**Comment by raamana** [comment]
again, they existed before and the double click functionality worked. 

Also, I am on macOS 12 btw, perhaps that could be the source too.

**Comment by tacaswell** [comment]
A thought I had was that the callback on the single click was taking too long and that was preventing the UI from ever processing that there were two clicks, but if you put a `time.sleep(5)` in the test script I still get the right double-click identification, it just takes a while to fully train the queue of events.

Can you point me at a full-blown example + sample data?

**Comment by raamana** [comment]
I think you nailed it -- I had a `plt.draw()` call for each mouse event [here](https://github.com/raamana/visualqc/blob/92d06e1e6587df17e86cdcd0dcf27cd8d81d2516/visualqc/freesurfer.py#L205) 

and without that, I get the `MouseEvent.dblclick` set to True as expected.

Not sure if `plt.draw()` is smart in updating only what's changed or if it force redraws everything on the figure, but that seems to have been causing delays. I've over 40+ axes (mostly 2D images, few of them wth a lot of contours on these images), that explains it.

but the double click generating two clicks is throwing off my current implementation, so i'll have to rework it or rely on something much more unambiguous like `Ctrl+Click`

**Comment by raamana** [comment]
here is the definition for `plt.draw()` - it appears it's smart but also equivalent to `fig.canvas.draw_idle()`. I also have another call to `fig.canvas.draw_idle()` before the `fig.canvas.start_event_loop(timeout=-1)` blocking loop, so this `plt.draw()` seems redundant and unnecessary.

```python
def draw():
    """
    Redraw the current figure.

    This is used to update a figure that has been altered, but not
    automatically re-drawn.  If interactive mode is on (via `.ion()`), this
    should be only rarely needed, but there may be ways to modify the state of
    a figure without marking it as "stale".  Please report these cases as bugs.

    This is equivalent to calling ``fig.canvas.draw_idle()``, where ``fig`` is
    the current figure.
    """
    gcf().canvas.draw_idle()
```

**Comment by tacaswell** [comment]
>  rely on something much more unambiguous like Ctrl+Click

This is probably better for a number of reasons (including accessibility)

> Not sure if plt.draw() is smart in updating only what's changed or if it force redraws everything on the figure, 

it is not. See  https://matplotlib.org/stable/tutorials/advanced/blitting.html for how you can probably get some big speed ups, but at the cost of tracking a fair amout of work.  I think it is plausible to do "auto blitting", but that is a decent sized project.

I wonder if the `draw` is actually happening on the event loop so that is successfully slowing down the clicks where as my sleep was not.

Can we close this as I am not sure there is anything we can do upstream to fix this?

**Comment by raamana** [comment]
Yes, let's close it. Thanks everyone for your help. Appreciate it.

**Comment by tacaswell** [comment]
We are completely relying on the UI toolkit to tell us when there is a double click.  I do not think you want to start second guessing that.

**Comment by raamana** [comment]
just quick FYI that this delay is affecting the recognition of key_press_events as well as `alt+s` is broadcast as two keys starting with alt and then an s. this would make it difficult or impossible for me to support multi-key keyboard shortcuts.

**Comment by raamana** [comment]
weirdly enough, this behaviour seems restricted to `alt` key only as `ctrl+s` or `super+s` are getting recognized correctly. I tested both an external as well as builtin keyboards for my MacBook pro

**Comment by tacaswell** [comment]
As with mouse clicks, we are at the mercy of what the UI toolkits choose to send us.    My instinct is that the behavior of alt is correct (in that you can ignore events you do not care about) vs ctrl/super (you can to do something about events you were never sent).

**Comment by raamana** [comment]
interesting - from the "user" perspective, esp. for research software, when I press `alt+s` i expect to receive an `alt+s` you know! so many weird things i am learning in trying to offer an interactive solution for a research problem :)

**Comment by tacaswell** [comment]
Please remember both that Matplotlib has a very wide user base, so it is very common that different users will have _wildly_ different expectations of what the "obvious" behavior is and than complexity (similar to entropy) can not actually be removed, it can only be moved around ;) 

If we did not present the key press (and release) of the modifier keys we would get bug reports the other way!  They are, to be fair, "keys" in the most literal sense (they are a thing on the keyboard you can push) so it is simpler to treat it like any other key than it is to make them "special".  Additionally, there are things you might want to do tracking only the modifiers ("hold down alt to get help overlay") that you could not do if we only gave you access to the modifiers + some other (non-modifier) key.

**Comment by raamana** [comment]
true! I realize the complexity of MPL user base, but can you elaborate more on what sort of users/domains/applications would expect `alt+s` to be broadcast as two keys? I personally haven't come across them so I am curious.

**Comment by tacaswell** [comment]
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1)
fig.canvas.mpl_connect('key_press_event', lambda key_event: print(f'press {key_event.key!r}'))
fig.canvas.mpl_connect('key_release_event', lambda key_event: print(f'release {key_event.key!r}'))
plt.show()
```

you should see a stream of 

```
press 'alt'
press 'alt+a'
release 'alt+a'
release 'alt'
press 'control'
press 'ctrl+alt'
release 'ctrl+alt'
release 'control'
press 'control'
press 'ctrl+alt'
press 'ctrl+alt+s'
release 'ctrl+alt+s'
release 'ctrl+alt'
release 'control'
press 'control'
release 'control'
press 'control'
release 'control'
```

You do get press/release events for `alt+s`, but you also get press/release events for just alt.  If you do not care about the bare alt events, ignore them, but if you did want them and we do not provide them you are out of luck.   Something I think would be a reasonable UI would be the case where you have multi-modal data (think multi-channel florescence microscopy + bright field or images of a sample + aligned schematic of there things should be).  You may want one of those layers to be easily visible on demand, but not always there.  You could hook up callbacks such that when alt is pressed the layer is made visible and on release made invisible.  It is better to do this with the modifier keys than a "nornmal" key because the UI frameworks will auto-repeat letters but not the modifiers (hold down 'a' in the example above vs holding down ctrl!).

**Comment by raamana** [comment]
i tried the script above, I could get `ctrl+s`, `super+s` but never `alt+s`.. also some weird `ß` instead of `s`

```bash
press 'alt'
release 'alt'
press 'alt'
release 'alt'
press 'alt'
release 'alt'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'control'
press 'ctrl+s'
press 'super+??'
press 'super+s'
release 'super+s'
release 'meta'
press 'super+meta'
press 'super+s'
release 'super+s'
release 'meta'
press 'alt'
press 'ß'
release 'ß'
release 'alt'
press 'control'
press 'ctrl+s'
press 'super+??'
press 'super+s'
release 'meta'
release 's'
```

**Comment by tacaswell** [comment]
> i tried the script above, I could get ctrl+s, super+s but never alt+s.. also some weird ß instead of s

That is a bug!  

Can you open a new issue?  Please include what kind of keyboard you have, what language your OS is in, if this is consistent across toolkits, and if that happens with other non-'s' keys?  Does it happen with both alts?

My guess is that you are getting into deadkeys / extra levels of shift which is turning alt-s into https://en.wikipedia.org/wiki/%C3%9F which according to wikipedia is a type of s in German (I will defer to our German speakers to verify).

**Comment by jklymak** [comment]
I think that's how MacOS works? There is no real "Alt" key.  "Option" gives you different characters... option-r: ®.  option-t †.  etc.

**Comment by tacaswell** [comment]
> "Option" gives you different characters... option-r: ®. option-t †. etc.

oh, interesting.  We do have some re-mapping internally to rename 'option' to 'alt' https://github.com/matplotlib/matplotlib/blob/1ab4a53d1cce6a8692d5439660f292683f4f7296/src/_macosx.m#L1543-L1545 

Maybe we should be dropping 'option' on the floor and document that we do not have alt on OSX?

**Comment by jklymak** [comment]
I think alt/option are usually considered the same, but I don't know what you do about the Mac translating alt-t to a unicode character before it shows up as alt-t

**Comment by greglucas** [comment]
Looks like this is only a tk issue? I can't reproduce in the macosx backend, or the qt5agg backends. In tk I get `option-r: ®` and on the others I get `option-r: alt+r`

I don't think we should drop option in the macosx backend, this indicates they are equivalent I think:
https://developer.apple.com/documentation/appkit/nsevent/modifierflags/1642431-option
Rather, there is probably an update that needs to be made in `_backend_tk.py` to handle the modifier keys similar to the other backends.

**Comment by tacaswell** [comment]
ok, so this issue is restricted to:
 - tk backend
 - on OSX
?

https://github.com/matplotlib/matplotlib/blob/1ab4a53d1cce6a8692d5439660f292683f4f7296/lib/matplotlib/backends/_backend_tk.py#L179

to

https://github.com/matplotlib/matplotlib/blob/1ab4a53d1cce6a8692d5439660f292683f4f7296/lib/matplotlib/backends/_backend_tk.py#L356-L358

to 

https://github.com/matplotlib/matplotlib/blob/1ab4a53d1cce6a8692d5439660f292683f4f7296/lib/matplotlib/backends/_backend_tk.py#L317-L352

is the call chain on our side.  This makes me think that the conversion is happening before it gets to us (but someone with a mac should probably verify that).

**Comment by greglucas** [comment]
I agree with that, it seems like it is happening somewhere earlier in the stack. The event passed in has this repr:
`<KeyPress event state=Mod2 keysym=registered keycode=260047022 char='®' x=358 y=271>`
which is already modified.

**Comment by QuLogic** [comment]
In the macosx backend, we ask for `charactersIgnoringModifiers`. According to the docs, there is [`characters`](https://developer.apple.com/documentation/appkit/nsevent/1534183-characters?language=objc) and [`charactersIgnoringModifiers`](https://developer.apple.com/documentation/appkit/nsevent/1524605-charactersignoringmodifiers?language=objc); the former does translation to dead keys/Unicode/etc., while the latter tells us the value exactly.

Presumably Tk is asking for the former, but I don't know if we can tell it to do the latter.
