### ISSUE TITLE
examples/showcase/xkcd.py does not show line randomization on Mac OS X

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#2269]
Running the xkcd.py does not show the randomized lines as on the pics shown on the matplotlib homepage. The Comic font, however, is shown. See the images below. This is verified on OS X 10.7.5 and OS X 10.8.? with Python 2.7.5 and Python 3.3.2, matplotlib installed from the just released tar. 

``` bash
# python 
Python 2.7.5 (v2.7.5:ab05e7dd2788, May 13 2013, 13:18:45) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'1.3.0'
>>> quit()
# cd matplotlib-1.3.0/examples/showcase
# python xkcd.py
```

![screen shot 2013-08-01 at 18 05 53](https://f.cloud.github.com/assets/2933457/895085/22526950-fac5-11e2-86f9-c705cc75b9e6.png)
![screen shot 2013-08-01 at 18 05 55](https://f.cloud.github.com/assets/2933457/895092/2985041c-fac5-11e2-9787-aeb219766d94.png)

**Comment by xiumingzhang** [comment]
jmason86's solution saved me much trouble going through all those hassle. Thanks Mason!

**Comment by liangz0707** [comment]
With following code  my circle is also  rendered as regular plots . There should be a bad circle, isn't it ?

>matplotlib.use('QT4Agg')
>patches = []
>fig, ax = plt.subplots()
>circle = Circle((0.2, 0.12), 0.1)
>patches.append(circle)
>p = PatchCollection(patches)
>ax.add_collection(p)
>plt.show()
