### ISSUE TITLE
[Bug]: the version of whl which is generated by my self is wrong

### ISSUE THREAD

**Issue by wqh17101** [matplotlib/matplotlib#22695]
### Bug summary

Hi there
i git clone this repo and switch to the tag 3.5.1
then python setup.py bdist_wheel
and get a whl named `matplotlib-3.5.2.dev0+g710fce3df9.d20220324` not matplotlib-3.5.1

### Code for reproduction

```python
python setup.py bdist_wheel
```

### Actual outcome

 `matplotlib-3.5.2.dev0+g710fce3df9.d20220324`

### Expected outcome

get a whl named "matplotlib-3.5.1"

### Operating system

Linux

### Matplotlib Version

3.5.1

### Installation

from source (.tar.gz)

**Comment by timhoffm** [comment]
This is intended. We use the release-branch-semver version scheme: https://github.com/pypa/setuptools_scm/blob/main/README.rst#version-number-construction

**Comment by tacaswell** [comment]
I can not reproduce this:

```
✔ 18:35:09 $ git checkout 710fce3df95e22701bd68bf6af2c8adbc9d67a79
HEAD is now at 710fce3df9 REL: v3.5.1
(sys310) ~/s/p/m/mpl35x v3.5.1|✓
✔ 18:36:57 $ git clean -xfd
Removing .eggs/
Removing LICENSE/LICENSE_QHULL
Removing __pycache__/
Removing build/
Removing dist/
Removing lib/matplotlib.egg-info/
Removing lib/matplotlib/_version.py
Removing tmp/
(sys310) ~/s/p/m/mpl35x v3.5.1|✓
✔ 18:37:19 $ python setup.py bdist_wheel > /dev/null 2> /dev/null
(sys310) ~/s/p/m/mpl35x v3.5.1|✓
✔ 18:37:58 $ ls dist/
matplotlib-3.5.1-cp310-cp310-linux_x86_64.whl
(sys310) ~/s/p/m/mpl35x v3.5.1|✓
✔ 18:38:04 $

```
