### ISSUE TITLE
very slow importing matplotlib

### ISSUE THREAD

**Issue by GengSS** [matplotlib/matplotlib#22692]
hello, 
i encountered an issue of very slow importing matplotlib,
here is the output of the cProfile, it seems that the issue is due to the matplotlib._c_internal_utils.display_is_valid,
but I do not know how to fix it

Best,
Geng

```
  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    6.089    2.030    6.089    2.030 {built-in method matplotlib._c_internal_utils.display_is_valid}
      283    0.022    0.000    0.022    0.000 {built-in method marshal.loads}
    50/48    0.022    0.000    0.023    0.000 {built-in method _imp.create_dynamic}
     2775    0.016    0.000    0.027    0.000 inspect.py:626(cleandoc)
 2617/181    0.015    0.000    0.042    0.000 sre_parse.py:493(_parse)
1157/1005    0.010    0.000    0.068    0.000 {built-in method builtins.__build_class__}
      327    0.009    0.000    0.009    0.000 {built-in method builtins.compile}
```

[@tacaswell edited to add markup]

**Comment by tacaswell** [comment]
That is running https://github.com/matplotlib/matplotlib/blob/647afe6b0620593e8e6b90212d9fa55f5ba18df5/src/_c_internal_utils.c#L12-L62 This looks to me like one (or more) of those calls is taking a long time to time out (which seems odd).  Can you give us any more context about what the system set up is like?

**Comment by GengSS** [comment]
Hi tacaswell,
Thank you very much,
the code you showed inspired me to check the DISPLAY environmental variable,
I was using the mobaxterm for WSL (ubuntu20.04) , which seems to slow down importing maptlotlib.
However, when I switch to another terminal for the WSL, the import of the matplotlib is very smooth without lagging.

The slow matplotlib import seems to due to X11 setup in Mobaxterm.

Best
Geng

**Comment by tacaswell** [comment]
@GengSS It looks like mobaxterm is a commercial product, do you pay them and if so can you report this to them?

I'm inclined to close this issue as it appears to be an issue with a specific X11 server on a specific machine (searching for other reports of this I am seeing mobaxterm being recommended so I assume this is not and consistent issue).

Please ping to have this reopened if this is actually a widespread problem that we need to document or work around.
