### ISSUE TITLE
MAtplolib pan and zoom dead slow on new PC

### ISSUE THREAD

**Issue by cjthedj** [matplotlib/matplotlib#22727]
I just got a new PC. My very complex set of matplotlib based plotting now runs like a dog. 9 seconds plus response times to any panning or zooming. The new  PC itself is twice as fast as the old one running the initial plot creation scripts. The old PC matplotlib version was 3.3.2 New one 3.5.1. Both using TkAgg backend.  
  Win64 PCs. Both have 80G of RAM at least.  
  I tried reverting matplotlib to version on old PC but it errored.
  Python now 3.9 was 3.8. Tried lots of googling but I can't even understand some of the answers,
  Smells of a bug since similar things have been reported, or a setup issue on the new PC.

After a bit more investigation it would appear that the plots generated with pcolormesh are causing the issue. Other non-pcolormesh plots are zooming at the expected speed but the little crosshair cursor that you get when you hit the magnifying glass icon is not appearing in any windows.
   Even trying to pop a pcolormesh window to the front by clicking on it takes ages.

**Comment by cjthedj** [comment]
I am but a humble user of python and MAtplotlib. My knowledge of how github works is virtually non-existent,
However I REALLY need this fixed. 
  If matplotlib 3.52 release is imminent then I can wait.
  If not , is there a way of getting "early access" to the fix? My use of matplotlib is quite complex and does stretch the tool. I could try the fixes for you in a "real user application"  and report back.  I would need an "idiots guide" to getting 3.5.2 if this sounds like a good idea.

**Comment by jklymak** [comment]
The bug was introduced in 3.5, so you can install 3.4 and be fine until 3.5.2 comes out.  Conversely you can install from source:  https://matplotlib.org/stable/users/installing/index.html#installing-from-source

**Comment by cjthedj** [comment]
WOW 3.4 is SO much faster than 3.3.2 on my old machine. Some redraw times have gone down from several seconds to well under half a second
