### ISSUE TITLE
[Bug]: Clipped Toolbar icons

### ISSUE THREAD

**Issue by vijaypanchalr3** [matplotlib/matplotlib#22741]
### Bug summary

![Screenshot from 2022-03-31 11-11-18](https://user-images.githubusercontent.com/72692300/160986074-c0f86957-86b3-475e-9dfa-eec78826c5fc.png)

why interactive navigation icons are broken?

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.plot(t,qt,'ro',ms=1)
plt.show()
```

### Actual outcome

broken icons in interactive navigation bar in matplotlib pyplot window.

### Expected outcome

i expected to be fixed sized icons, which fit in place and space.

### Operating system

debian

### Matplotlib Version

3.5.1

### Python version

3.9.2

### Installation

pip

**Comment by tacaswell** [comment]
If you resize the window does it get better/worse?

I suspect the plot is unrelated and 

```python
import matplotlib.pyplot as plt
plt.figure()
plt.show()
```

would be enough to reproduce this. 

I think this is the qt backend (can you please confirm that)?  Are you using Qt5 or Qt6?  The toolbar is  fully layeout in the GUI toolkit so this may also depend on your window manager and any zooming / scaling / high-dpi settings you have enabled.

**Comment by QuLogic** [comment]
I don't think that's the default font; are you using a custom theme? Does it work correctly in other Qt apps?

**Comment by jklymak** [comment]
I'll close for lack of response...

**Comment by vijaypanchalr3** [comment]
Sorry for my carelessness and irresponsiveness, this will not happen again
