### ISSUE TITLE
Document distutil vs setuptools issues or fix usage 

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#22765]
Following on to #22756 

> setuptools 60 re-enabled their local copy of distutils: pypa/setuptools#2896
>
> This apparently fails to set up paths that can find msbuild, so switch back the standard library distutils.

We had to set an additional ENV on azure to un-break CI.  Do we need to document this change in the windows source install instructions as well?  Or is it better to change how we are using setuptools/distutils?

**Comment by QuLogic** [comment]
cibuildwheel is on setuptools 66 and we don't set the env there; I'll try reverting that PR to see if we can drop it.
