### ISSUE TITLE
[Bug]: .eps greyscale hatching of patches when lw=0

### ISSUE THREAD

**Issue by topper91** [matplotlib/matplotlib#22792]
### Bug summary

Export to .eps-format of patches that are filled with a colored hatch pattern appear in greyscale color when linewidth of the patch is set to zero.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse

ax = plt.gca()
ax.add_patch(Ellipse((0, 0), 1, 1, hatch='/', facecolor='none', edgecolor='r', linewidth=0))

plt.savefig(r"E:\mwe.png")
plt.savefig(r"E:\mwe.eps")

plt.show()
```

### Actual outcome

.eps-file converted to .png-format using GIMP 2.10.30

![mwe_converted_from_eps](https://user-images.githubusercontent.com/103106780/161935980-8c98154f-9144-466e-ad57-028f0fda5e63.png)

### Expected outcome

.png-file exported by matplotlib

![mwe](https://user-images.githubusercontent.com/103106780/161936360-d3b40b32-5505-4f75-8011-f9b8197e9405.png)

.eps-file exported by matplotlib with linewidth > 0 converted to .png-format using GIMP 2.10.30

![mwe_2_converted_from_eps](https://user-images.githubusercontent.com/103106780/161936833-3e5319bf-eccf-4fdb-b955-092bd300aa59.png)

### Additional information

It happens when linewidth is set to zero.

I don't know if it worked in earlier versions.

I had a look on the eps-commands in the file. (I don't know anything about eps-format.) It is most likely due to certain eps-commands being removed when linewidth is set to zero, including a command for the line color.

### Operating system

Windows 10

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

3.9.10

### Jupyter version

n/a

### Installation

pip

**Comment by jklymak** [comment]
Thanks for the helpful bug summary and looking into the possible cause (which sounds reasonable).  Not sure who will step up to fix this, but it does seem like somehow the colours are not getting set.  Perhaps see if pdf works?

**Comment by topper91** [comment]
thx for the quick response. pdf-export works just fine.

**Comment by oscargus** [comment]
A quick diff between the mwe here and one with setting linewidth to 0.1.

```
(base) lnx00073 [~]> diff mwe.eps mwe2.eps 
2c2
< %%Title: mwe.eps
---
> %%Title: mwe2.eps
4c4
< %%CreationDate: Wed Apr  6 16:08:50 2022
---
> %%CreationDate: Wed Apr  6 16:09:28 2022
242a243,247
> 0.100 setlinewidth
> 0 setlinejoin
> 0 setlinecap
> [] 0 setdash
> 1.000 0.000 0.000 setrgbcolor
291a297
> stroke
295,296d300
< 0 setlinecap
< [] 0 setdash
```
I'd say that it is these lines that are not executing:
https://github.com/matplotlib/matplotlib/blob/574580c7d173bf08a23678d302b711492b971f3c/lib/matplotlib/backends/backend_ps.py#L776-L781 as mightstroke is False (as linewidth is 0). 

Moving the color-setting out of the if-clause seems to solve this problem, but I am not sure if it causes other issues.
