### ISSUE TITLE
[Bug]: Quiver not working with subfigure?

### ISSUE THREAD

**Issue by henry2004y** [matplotlib/matplotlib#22804]
### Bug summary

There seems to be an issue when trying to plot quivers in the axes created within subfigures.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig = plt.figure()
subfigs = fig.subfigures(1, 2)
axsLeft = subfigs[0].subplots(1, 2)
axsLeft[0].quiver(1,1,1,1)
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5117, in quiver
    q = mquiver.Quiver(self, *args, **kw)
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/quiver.py", line 510, in __init__
    self._cid = ax.figure.callbacks.connect('dpi_changed', on_dpi_change)
AttributeError: 'SubFigure' object has no attribute 'callbacks'

### Expected outcome

Expect the same outcome as

```python
fig, ax = plt.subplots(1, 2,)
ax[0].quiver(1,1,1,1)
```

### Operating system

Ubuntu

### Matplotlib Version

3.4.3

### Python version

3.8.5

**Comment by jklymak** [comment]
Thanks for the report.  We will have to figure out how to properly set up the callbacks here.  Not thrilled that quiver needs a callback versus doing things in inches/physical units, but that doesn't change the fact that subfigure should have a callback.
