### ISSUE TITLE
[Doc]: Make rect argument consistent in the docstrings

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#22819]
### Problem

The `rect` argument to functions is inconsistently documented in the codebase. We should consolidate the argument into a single choice.

The options I found searching for `rect : ` are:
```bash
rect : tuple[float, float, float, float], optional
rect : sequence of float
rect : tuple (left, bottom, right, top), default: (0, 0, 1, 1)
rect : tuple of 4 floats, default: (0, 0, 1, 1)
rect : [left, bottom, width, height]
rect : (float, float, float, float)
```

### Suggested improvement

Update all `rect` arguments to a single choice of one of the above for consistency.

**Comment by Sync271** [comment]
I'd like to work on this.

Below, while creating an instance of  `Grid`, it not only accepts a tuple but also an integer. Do I not touch the integer part and just make changes to the documentation of the tuple?
https://github.com/matplotlib/matplotlib/blob/2df11ccd4221d4a1d7001ab374e44f8f3c51316f/lib/mpl_toolkits/axes_grid1/axes_grid.py#L86-L88
