### ISSUE TITLE
[ENH]: zplane/splane/freqz/freqs plotting

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#22867]
### Problem

These are quite convenient to have when working in particular areas (e.g. DSP, which I do).

Basically, zplane and splane are scatter plots of complex values using two different types of markers with some identification of multiples and a unit circle for zplane.

freqz/freqs compute the magnitude and phase response of a discrete/continuous transfer function and plots them in separate subplots (although one could/should really partition it in a more convenient way so that one can plot one of them in an arbitrary subplot). scipy has some basic functionality in that one can provide a callable that plots something as part of the freqz call, one use for these functions would be to provide a simple function to use here (right now, a lambda expression must be used). See: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.freqz.html

The benefit would be to have these as convenience functions rather than having to write a bunch of lines every time (although no major effort, possibly neglecting the multiple pole/zero detection).

### Proposed solution

These should probably go in the mlab module, but I also know that there are ideas to move mlab out of the matplotlib core.

So should I start by deprecating the mlab methods (and the functions in pylab) and move these to a separate package or add these functions in mlab for a later move? Or just leave it as these should be handled on a case by case basis by anyone needing them? (Or create a third-party library.)

Here is what probably many use for zplane now: https://gist.github.com/endolith/4625838

There are multiple implementation details to be discussed, like transfer functions or poles/zeros (or frequency responses as in the scipy.signal.freqz callable), but I would like to get some general opinions on the idea.

**Comment by jklymak** [comment]
I would vote for start the new toolbox, and start deprecating the old when you think its mature enough to go forward?

**Comment by oscargus** [comment]
Closing this and at some stage hopefully introducing mpl-signal (or something).

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib-extension-cookiecutter may be helpful!
