### ISSUE TITLE
[Bug]: SymLogNorm not working properly

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#22870]
### Bug summary

(It is, sort of, well known that this is broken, see e.g. #16398, but good to have a separate issue for it in case someone is tempted to give it a go.)
Here is an example for a colorbar, but a similar behavior is seen elsewhere:

https://github.com/matplotlib/matplotlib/blob/a7b7260bf06c20d408215d95ce20a1a01c12e5b1/tutorials/colors/colormapnorms.py#L132-L148

gives 

![image](https://user-images.githubusercontent.com/8114497/164436930-f659320b-4fb1-405a-986e-61746dc71dc2.png)

As seen, the top colorbar has a messed scale.

### Code for reproduction

```python
See above.
```

### Actual outcome

Overlapping tick labels.

### Expected outcome

Non-overlapping tick labels.

### Matplotlib Version

Current main (pre-3.6.0)

**Comment by jklymak** [comment]
I don't think this is a colorbar issue in particular. Don't you get the same with any symlognorm axis?

**Comment by oscargus** [comment]
You are probably right. Just saw it there. I'll edit appropriately.
