### ISSUE TITLE
CapStyle with radius linewidth/2

### ISSUE THREAD

**Issue by Zefeng-Wu** [matplotlib/matplotlib#22873]
Hi there, I have a question about the matplotlib class-matplotlib._enums.CapStyle(value). In the "round" mode, the capsemicircular cap is added to the end of the line with the radius of linewidth/2. However, I expect that the red points can be located at rightly the edge of the line or line2D ([see the link](https://matplotlib.org/stable/api/_enums_api.html#matplotlib._enums.CapStyle)).In other words, I expect the radius is a **negative** value so that the line with the cap added can start with 0.  How to control the default setting?

**Comment by timhoffm** [comment]
The three supported capstyles are universal. You find them e.g. in the specifcations of [PDF](https://www.debenu.com/docs/pdf_library_reference/SetLineCap.php), [cairo](https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-line-cap-t) and [svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap). Other styles are not supported by the rendering engines. We have no way of further configuring that behavior.
