### ISSUE TITLE
[Bug]: Unexpected savefig() overwrite deprecation warning

### ISSUE THREAD

**Issue by bsunnquist** [matplotlib/matplotlib#22872]
### Bug summary

I'm getting a deprecation warning when saving a plot with overwrite=True, but I can't find any alternatives, and am not sure if the warning is expected.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
plt.scatter(np.arange(5), np.arange(5))
plt.savefig('plot.png', overwrite=True)
```

### Actual outcome

`<ipython-input-3-18305a314a52>:1: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "overwrite" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig('plot.png', overwrite=True)`

### Expected outcome

Either no warning, or an example of what to use in the future besides overwrite.

### Matplotlib Version

3.4.2

### Matplotlib Backend

MacOSX

### Python version

3.9.11

**Comment by jklymak** [comment]
Savefig just overwrites, so why do you want that kwarg at all?

**Comment by bsunnquist** [comment]
Thanks, wasn't aware that was the default anyway, will close this

**Comment by QuLogic** [comment]
That argument never existed; the warning is that passing an unknown argument is no longer supported, not that that argument is no longer supported (because it never was.)
