### ISSUE TITLE
Alpha values smaller than 1/256

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#2287]
At the moment, using alpha values of less than 1/256 results in nothing being drawn, which is an issue if one wants to draw e.g. tens of thousands of overlapping lines with e.g. alpha=0.001 since nothing is shown in the end. The following example illustrates the issue:

```
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
for p in range(10):
    n = 2 ** p
    alpha = 1. / n
    for i in range(n):
        ax.plot([0., 1.], [p, p], lw=10, alpha=alpha, color='blue')
ax.xaxis.set_visible(False)
ax.set_ylim(-1., 11.)
ax.set_ylabel('p')
fig.savefig('line.png')
```

which results in:

![line](https://f.cloud.github.com/assets/314716/938434/1a5ddb3c-00fe-11e3-8fd2-b3eb9d431de9.png)

For p=9 and 10, the 'correct' result is a blue line with alpha=1 but I imagine that the alpha must be treated internally using 8 bits. First, is this a bug, and if not, is there a way to enable a 'high-precision alpha' mode that would give the 'correct' result?

The reason I am interested in this is because I want to show a plot of density of tens of thousands of lines but I don't care about seeing individual lines.

**Comment by ferret-guy** [comment]
I know this is an old issue but this became a problem for me when rendering dense plots of points, and trying to use alpha to visualize density. Looks like the most dense places have ~1k overlapping points and at the lowest alpha settings, most of the interesting part of the graph looks is a solid flat bock.

**Comment by WeatherGod** [comment]
I would strongly suggest using hexbin for such situations. I do this quite
often and doing so has revealed quite interesting patterns that were hidden
in those "solid flat" areas.

**Comment by anntzer** [comment]
Alternatively, you can use https://github.com/matplotlib/mplcairo/ (though only with cairo>=1.17.2); using `mplcairo.set_options(float_surface=True)` uses a floating point surface that accumulates alpha with high accuracy.

**Comment by charlierunkle64** [comment]
One solution, that worked for me as I stumbled over the same issue: just set a small line width (lw). Goes hand in hand with the alpha setting when you plot 1e4 to 1e7 lines in one plot. Thanks for your ideas everybody, helped me as well.
