### ISSUE TITLE
[ENH]: mpl_toolkkits with datetime

### ISSUE THREAD

**Issue by liu-6666** [matplotlib/matplotlib#22888]
### Problem

Hello everyone, I recently tried to draw 3D images using matplotlib, where I want to use the **z axis as the timeline**, but always report errors, only support strings and float numbers.
The data for the z-axis is datetime after processing with **pandas**,I can use this set of data as a timeline for a two-dimensional image, but I don't always do it when drawing a three-dimensional image.After reviewing the manual I felt that drawing 3D images does not support processing, datetime format data.
I was very distressed and didn't know what to do with this

**Comment by anntzer** [comment]
This is a known limitation, already tracked at #22207.
