### ISSUE TITLE
rainbow text example is broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#22893]
Currently, the example is broken again:
https://matplotlib.org/stable/gallery/text_labels_and_annotations/rainbow_text.html
<img width="559" alt="image" src="https://user-images.githubusercontent.com/44469195/165059458-cd34437f-b55d-470f-9972-b93d207abe5b.png">
However, the spacing looks fine when running the exact same script locally.
Mabye there is a certain `rcParams` set in the documentation, that is causing this issue?

_Originally posted by @kolibril13 in https://github.com/matplotlib/matplotlib/issues/13914#issuecomment-1108307727_

**Comment by tacaswell** [comment]
I think this is a good first issue (constrained problem, hopefully no API design), but medium difficulty because it will require understanding how we do font layout.

I have suspicion that this is related to the dpi being different from when we grab the text

Because we are now building high-dpi versions of the images we have 2 copies of each figure in the docs (which has contributed to our run-away artifact size).  The normal DPI one is correct:

https://matplotlib.org/stable/_images/sphx_glr_rainbow_text_001.png
![image](https://user-images.githubusercontent.com/199813/165106854-7117a305-47e6-449f-8f44-690b42816eef.png)
but the hi-dpi one is busted https://matplotlib.org/stable/_images/sphx_glr_rainbow_text_001_2_0x.png 
![image](https://user-images.githubusercontent.com/199813/165106963-ebb017e0-efca-440b-9918-7b74a0829205.png)

The issue is that in the example we are using the computed size in screen units of the previous word to compute the offset.  When we change the DPI anything sized in physical units (e.g. the text) will change size in screen units, hence the squishing we see because the offset is ~half what it needs to be.

The fix is to use one of the method from https://matplotlib.org/stable/tutorials/text/annotations.html#using-complex-coordinates-with-annotations here (either 2 or 5 I think) so that the computation of the actual offset is not done until draw time).

**Comment by kkoutris** [comment]
I'd like to work on this issue, but I don't know where to start(I'm just getting started to open source contributing). Can you @tacaswell guide me?

**Comment by tacaswell** [comment]
https://matplotlib.org/stable/devel/contributing.html#contributing-code is a good place to start with getting the code checked out ready to go.

In this case the only code that needs to change is the code in the example so you should be able to work on this without installing Matplotlib from source if you do not want to.

Between my and Jody's comments I think there is enough information on how to modify the example (the problem is we offset text in _pixels_ which we compute at one DPI but when the figure is saved at a different DPI the offset is wrong). 

I would get the example code into some context where you can easily modify and run it, hack at it until it looks right when saved with both `fig.savefig(..., dpi=100)` and `fig.savefig(..., dpi=200)`.  Once you have that working, commit the changes to the example on a feature branch and open a PR!

**Comment by wannieman98** [comment]
Hi, can I try working on it if the issue is still open?
