### ISSUE TITLE
[Bug]: axes.set_position() does not work properly

### ISSUE THREAD

**Issue by mapfiable** [matplotlib/matplotlib#22902]
### Bug summary

I'm trying to create a custom colorbar (hence the code below is loosely based on [this post](https://stackoverflow.com/q/71384228/5472354)), and while creating the data and colorbar itself works fairly well, I'm having trouble aligning the colorbar with the corresponding plot. I'm trying to use `axes.set_position()`, but for some reason, the `y`-values are overwritten. 

This is probably related to [#12917](https://github.com/matplotlib/matplotlib/issues/12917#issue-386520116) and [#12985](https://github.com/matplotlib/matplotlib/issues/12985#issue-390720532) (and maybe also [this post](https://discuss.python.org/t/issue-with-ax-set-position-not-working-for-subplot-added-with-add-subplot/5647)). I tried the `which` kwarg but it didn't help.
I also checked if it has to do with `constrained_layout=True`, but neither removing the keyword or using `tight_layout` solves the problem.

Lasty, I also tried using the [`HBoxDivider`](https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_hbox_divider.html#sphx-glr-gallery-axes-grid1-demo-axes-hbox-divider-py) to align the axes but didn't get it to work.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2, constrained_layout=True)
img = np.random.uniform(-2, 2, (100, 100))

axs[0].imshow(img)
axs[0].set(xlabel='x', ylabel='y')

axs[1].imshow(np.rot90(img), aspect=10)
axs[1].set(xlabel='y', ylabel='x')
axs[1].yaxis.set_label_position("right")
axs[1].yaxis.tick_right()

# readjust the axes
fig.canvas.draw_idle()  # necessary to get the proper positions

pos = axs[0].get_position()
pos2 = axs[1].get_position()
pos.x1 += 0.1

print('before')
print(pos.y0, pos2.y0)
print(pos.y1, pos2.y1)

pos.y0 = pos2.y0
pos.y1 = pos2.y1

print('after changing values')
print(pos.y0, pos2.y0)
print(pos.y1, pos2.y1)

axs[0].set_position(pos)
# this doesn't work either
# axs[0].set_position([pos.x0, pos2.y0, pos.x1 - pos.x0, pos2.y1 - pos2.y0])

print('after setting new position')
pos = axs[0].get_position()

print(pos.y0, pos2.y0)
print(pos.y1, pos2.y1)

fig.show()
```

### Actual outcome

![grafik](https://user-images.githubusercontent.com/48512334/165299270-34d8f344-6338-4eb5-b951-721d08970446.png)

### Expected outcome

Both axes being aligned and having the same height.

### Matplotlib Version

3.4.3

**Comment by jklymak** [comment]
This is behaving as expected (see the docs for `set_position` https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.axes.Axes.set_position.html#matplotlib.axes.Axes.set_position.  You may also check https://matplotlib.org/stable/gallery/subplots_axes_and_figures/colorbar_placement.html#colorbars-with-fixed-aspect-ratio-axes.    Please take user help to discourse.matplotlib.org.  Thanks for your understanding!

**Comment by mapfiable** [comment]
Hi @jklymak thanks for your quick reply. I'd be happy to post my issue there, but the platform doesn't allow me to:
![grafik](https://user-images.githubusercontent.com/48512334/165325335-1d311556-e49b-41ea-b18f-3c10179190d7.png)
I've no idea which host it is referring to, but even when I start deleting links, it tells me since I'm a new user, I can only include two links anyways. That seems a bit over-restrictive. How can I properly ask a question when I cannot inlcude all the relevant information?

So it doesn't get lost, here's my reply I intended to post along the original issue:

> Now it was pointed out in my original post that this is working as intended, but I'm not really sure I understand. Why would using `axes.set_position()` not setting the position according to the input data be the intention? I was also directed towards the [documentation](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.axes.Axes.set_position.html#matplotlib-axes-axes-set-position) of `axes.set_position()`, which I already consulted, but unfortunately, it doesn't tell me how to solve my issue.
Lastly, I was also pointed to [this tutorial about colorbar positioning](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/colorbar_placement.html#colorbars-with-fixed-aspect-ratio-axes), which seems to be pretty relevant. However, because I'm not using the standard way of creating a colorbar, I don't know how to apply the solutions presented there to my problem.

**Comment by jklymak** [comment]
`set_position` indeed positions the axes, but then `set_aspect(1)` squeezes one of the two dimensions so that the axes has a 1:1 aspect ratio.  Unless the position you pass to `set_position` has a 1:1 aspect ratio, the axes "active" position will be shorter than the "original". 

The tutorial suggests using `inset_axes` to create an axes that tracks the parent.

**Comment by tacaswell** [comment]
> That seems a bit over-restrictive. How can I properly ask a question when I cannot inlcude all the relevant information?

Fair. we recently pushed up the number of images, pushing up the number of links also makes sense.  Discourse is aimed to be used by the general internet which is notable a terrible place and the default new user limits are set to discourage people posting spam/scam messages.

-----


Also look at `ax.set_adjustable` to control if we re-position the Axes or change the data limits to match the requested aspect ratio.

Coincidentally there was just a related post on our discourse: https://discourse.matplotlib.org/t/gridspec-and-top-alignment-of-two-subplots-of-different-height/22747/5

**Comment by jklymak** [comment]
Off topic, but I do wonder if we can move discussions like this to GitHub discussions.  We've tried discourse for a while, but maybe its time to re-evaluate if it is the right tool for us.

**Comment by tacaswell** [comment]
@jklymak Start a discussion on discourse ;)

**Comment by mapfiable** [comment]
> Fair. we recently pushed up the number of images, pushing up the number of links also makes sense. Discourse is aimed to be used by the general internet which is notable a terrible place and the default new user limits are set to discourage people posting spam/scam messages.

Thanks for considering. I haven't used discourse anywhere else, but it seems like a decent platform. But yes, posting something as a new user can be pretty frustrating, especially if you get such vague error messages. Surely it must be possible to include the offending link(s) in the message? Or better yet, have it live-check the urls while you are still typing and warn you. Same goes maybe for the number of links and images? Maybe similar the the character counter that you see for character-limited fields?

And thanks for the additional info!
