### ISSUE TITLE
[Doc]:  Typo in triage acknowledgment

### ISSUE THREAD

**Issue by noatamir** [matplotlib/matplotlib#22900]
### Documentation Link

https://matplotlib.org/devdocs/devel/triage.html#acknowledgments

### Problem

* There is a typo in the acknowledgment: `sckit-learn` is misspelled (missing the first i). 
<img width="387" alt="Screenshot 2022-04-26 at 14 06 59" src="https://user-images.githubusercontent.com/6564007/165296547-9083ce4e-db18-469c-b189-7bb9c3983f07.png">

### Suggested improvement

* change to `scikit-learn`.

**Comment by tacaswell** [comment]
This was closed by #22904
