### ISSUE TITLE
Quiver unexpectedly transposes input matrices

### ISSUE THREAD

**Issue by andreamoro-git** [matplotlib/matplotlib#22903]
### Bug summary

When being fed a matrix of directions, quiver behaves unexpectedly. With the following code I expect the bottom-right arrow (element [2,0]) to point to the left. However, it's the top-left as in the attached figure.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.array(range(3))
y = x
nb_points = x.size
X,Y = np.meshgrid(x,y)

# set up north-east directions for all points
U = np.ones((nb_points, nb_points))
V = np.ones((nb_points, nb_points))

# change bottom-right element (x=2, y=0) to point to the left
U[2,0] = -3

#colors
M = (np.hypot(U, V))   

plt.gca().set_aspect('equal')
plt.quiver(X, Y, U, V, M, units='width', pivot='middle')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/34944866/165324119-2defa4df-a5ae-438b-9d46-90e726bcfc16.png)

### Expected outcome

I expect the bottom-right arrow to point left

### Operating system

MacOS

### Matplotlib Version

3.5.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.5 (default, May 18 2021, 12:31:01) 

### Installation

pip

**Comment by andreamoro-git** [comment]
The following produces the expected result instead:
```plt.quiver(X, Y, np.transpose(U), np.transpose(V), np.transpose(M), units='width', pivot='middle')
```

**Comment by jklymak** [comment]
Y[2,0]=2, right?  We are putting the arrow in the right place and this is behaving as expected.  I'll close this and if you require further discussion please discuss at discourse.matplotlib.org.
