### ISSUE TITLE
[Doc]: Duplicated toc entries

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#22905]
### Documentation Link

https://matplotlib.org/stable/users/explain/interactive.html

### Problem

The "interactive figures and asynchronous programming" and "event handling and picking" entries both appear twice (at two different levels) in the left bar TOC.
![if](https://user-images.githubusercontent.com/1322974/165348427-f00fd45e-1f9c-41e5-abde-979e5479dda0.png)

Also, having both "interactive figures" and "interactive figures and asynchronous programming" at the same level under "explainations" at https://matplotlib.org/stable/users/index.html is perhaps not optimal either:
![ug](https://user-images.githubusercontent.com/1322974/165348828-fc2403b0-bcbf-4a8a-873e-618aa75e9c29.png)

**Comment by Croadden** [comment]
I think I can handle it
