### ISSUE TITLE
"ab;cd" missing in subplot_mosaic tutorial

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#22917]
### Documentation Link

https://matplotlib.org/devdocs/tutorials/provisional/mosaic.html

### Problem

As of #18763, "ab;cd" is valid input into subplot_mosaic to generate a 2x2 plot. While the docs were updated, the tutorial wasn't. 

### Suggested improvement

Add a paragraph to the [string shorthand section](https://matplotlib.org/devdocs/tutorials/provisional/mosaic.html#string-short-hand) demonstrating the "ab;cd" notation.

**Comment by jklymak** [comment]
I thought we decided to not feature that shorthand on purpose?

**Comment by story645** [comment]
can't find reference of not featuring it in original issue or meeting notes?

**Comment by timhoffm** [comment]
Why should we not feature the shorthand. Since we  have decided that it's a reasonable API we also should advertise it.
