### ISSUE TITLE
[Bug]: figure.raise_window rcParam does not work on MacOSX backend

### ISSUE THREAD

**Issue by carlosgmartin** [matplotlib/matplotlib#22915]
### Bug summary

The figure.raise_window rcParam does not work on MacOSX backend.

Related: 
- https://github.com/matplotlib/matplotlib/issues/596
- https://github.com/matplotlib/matplotlib/issues/8692
- https://github.com/matplotlib/matplotlib/pull/15440
- https://stackoverflow.com/questions/44278369/how-to-keep-matplotlib-python-window-in-background
- https://stackoverflow.com/questions/45729092/make-interactive-matplotlib-window-not-pop-to-front-on-each-update-windows-7/45734500

### Code for reproduction

```python
from matplotlib import pyplot as plt
from matplotlib import rcParams

rcParams['figure.raise_window'] = False
while True:
    plt.plot()
    plt.pause(.0001)
```

### Actual outcome

Window is raised on every call to `pause`.

### Expected outcome

Window should not be raised.

### Operating system

macOS

### Matplotlib Version

3.5.1

### Matplotlib Backend

MacOSX

### Python version

Python 3.10.2

### Installation

pip

**Comment by greglucas** [comment]
Thanks for the easily reproducible example. I put a fix in https://github.com/matplotlib/matplotlib/pull/22928 if you're interested in testing that out at all.

**Comment by carlosgmartin** [comment]
@greglucas Works for me. Thanks.
