### ISSUE TITLE
[Bug]: ax.clabel() returns None, when I set a projection to ax?

### ISSUE THREAD

**Issue by 664787022** [matplotlib/matplotlib#22927]
### Bug summary

plt.clabel() or ax.clabel() should return A list of text instances for the labels.
However, when i add a projection parameter to ax, plt.clabel() or ax.clabel()  returns a None.
I don't know what happend. How can i get returned result in this situation?

### Code for reproduction

```python
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt


delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2

fig = plt.figure(figsize=(15,8))
ax = fig.add_subplot(1,1,1,projection=ccrs.PlateCarree())
CS = ax.contour(X, Y, Z,transform=ccrs.PlateCarree())
label = ax.clabel(CS, inline=True, fontsize=10)
print(label)
```

### Actual outcome

None

### Expected outcome

<a list of 7 text.Text objects>

### Operating system

Window10

### Matplotlib Version

3.5.1

### Matplotlib Backend

Qt5Agg

### Python version

3.8.3

### Installation

conda

**Comment by greglucas** [comment]
I can't reproduce this. I get the list of text objects printed out running with the latest Cartopy and Matplotlib. Perhaps you are using an old version of Cartopy?

**Comment by Croadden** [comment]
@greglucas Tried to reproduce on Python 3.8.3 with Matplotlib 3.5.1and latest Cartopy & Shapely versions. Can't reproduce it too. @664787022 could you please reinstall [related libs](https://stackoverflow.com/questions/70177062/cartopy-not-able-to-identify-geos-for-proj-install-on-windows)? I'm pretty sure you have some issues with them. Also be careful when reinstalling Cartopy, geos and Shapely - they havae different packages for different Python versions.

**Comment by 664787022** [comment]
> @greglucas Tried to reproduce on Python 3.8.3 with Matplotlib 3.5.1and latest Cartopy & Shapely versions. Can't reproduce it too. @664787022 could you please reinstall [related libs](https://stackoverflow.com/questions/70177062/cartopy-not-able-to-identify-geos-for-proj-install-on-windows)? I'm pretty sure you have some issues with them. Also be careful when reinstalling Cartopy, geos and Shapely - they havae different packages for different Python versions.

Thanks!  It works after I updated my Cartopy to latest version.
