### ISSUE TITLE
[ENH]: Global setting to make `/mathdefault` the default math type 

### ISSUE THREAD

**Issue by qzhang234** [matplotlib/matplotlib#22937]
### Problem

I am trying to generate scientific journal compatible figures in Matplotlib. Most of the journals have specific font requirements (e.g. Times New Roman) and I find myself typing something like `$\mathdefault{_x}$` instead of just `${_x}$` throughout the script, which reduces the readability of the scrpit.

### Proposed solution

Is it possible to have a global setting like `matplotlib.rcParams` that can be set once for the entire figure?

**Comment by tfpf** [comment]
It is possible to set a single font for the entire figure, but multiple `rcParams` have to be set. As a workaround to avoid having to type `mathdefault` over and over again, if it is specifically Times New Roman that is needed, consider using STIX, which is designed to blend with Times New Roman. 

    import matplotlib.pyplot as plt
    plt.rc('mathtext', fontset='stix')
    plt.rc('font', family='STIXGeneral')
    plt.text(.1, .5, 'Normal Text\n$y=e^x$\n$\mathbf{A}x=b$', size=20)
    plt.show()

![same_font_in_mpl](https://user-images.githubusercontent.com/19171016/166111953-a6247946-97b3-4983-bb14-993a8122769b.png)

Any other font can be used as well.

    import matplotlib.pyplot as plt
    plt.rc('mathtext', fontset='custom', it='Segoe Script:italic', bf='Segoe Script:bold', rm='Segoe Script')
    plt.rc('font', family='Segoe Script')
    plt.text(.1, .5, 'Normal Text\n$y=e^x$\n$\mathbf{A}x=b$', size=20)
    plt.show()

**Comment by anntzer** [comment]
I believe that the solution linked on discourse (setting mathtext.fontset = "custom", mathtext.rm = ..., mathtext.sf = ... as desired) is effectively the correct one, and using STIX as suggested by @tfpf should work too.  Closing, but feel free to ping for reopen if you think more should be done.
