### ISSUE TITLE
tex option not respected by date x-axis

### ISSUE THREAD

**Issue by cpcloud** [matplotlib/matplotlib#2294]
Here's a notebook that shows the issue:

http://nbviewer.ipython.org/6218078

**Comment by jklymak** [comment]
Thanks for the self-contained example.  But, seems to work for me.  Like sure, it looks bad...

![figuretex](https://user-images.githubusercontent.com/1562854/45978082-30705000-c000-11e8-9965-f182c4b51420.png)

**Comment by ImportanceOfBeingErnest** [comment]
I think the OP is aiming at the different fonts being used for the x- and y-ticklabels.

**Comment by dstansby** [comment]
Yeah, it kind of works, but those '2's don't look the same to me
