### ISSUE TITLE
[Doc]: v3.5.1 github stats are missing

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#22954]
### Documentation Link

https://matplotlib.org/devdocs/users/prev_whats_new/github_stats_3.5.1.html

### Problem

It seems that https://matplotlib.org/devdocs/users/github_stats.html contains the correct data but is not mentioning the 3.5.1 version number neither in filename nor in title.

**Comment by tacaswell** [comment]
attn @QuLogic

**Comment by QuLogic** [comment]
They aren't missing; the stats for the latest release are always in `github_stats.html`. We can add the version into the title there, I suppose.
