### ISSUE TITLE
[MNT]: macos-latest memory leak over threshold

### ISSUE THREAD

**Issue by andrew-fennell** [matplotlib/matplotlib#22959]
### Summary

`macos-latest` test is failing. Memory leakage is slightly over the threshold.

Failing test:
`lib/matplotlib/tests/test_backends_interactive.py:559: AssertionError`

Exact assertion error:
`assert growth <= acceptable_memory_leakage`
`assert 30457856 <= 30000000`

Example of test failing: [macos-latest failing](https://github.com/matplotlib/matplotlib/runs/6252442019?check_suite_focus=true)

### Proposed fix

Raise threshold.

**Comment by andrew-fennell** [comment]
Threshold can be raised by 1000000 (double 457856) to account for fluctuation.

**Comment by andrew-fennell** [comment]
@oscargus I think my original solution (#22961) didn't cover the whole problem. The original examples of this test failing was specifically with macosx and the threshold was less than 1000000 off.

The test that is failing:
https://github.com/matplotlib/matplotlib/blob/2e70254e860d7946035a3b0e50be9e08e78fd36e/lib/matplotlib/tests/test_backends_interactive.py#L543-L556

Here is an example of this tests still failing: https://github.com/matplotlib/matplotlib/runs/6246645151?check_suite_focus=true

Should I make this adjustment?
`@pytest.mark.parametrize("time_mem", [(0.0, 2_000_000), (0.1, 35_000_000)])`

**Comment by andrew-fennell** [comment]
Talked about in dev call: https://hackmd.io/jd_7FjxNQ4y7XgNknvmvGQ#memory-issue

**Comment by tacaswell** [comment]
Looking at this in detail, I was wrong about how the tests are run.  They are in their own process so the inter-test interaction should not be a problem.  It seems there is just a lot of variation, but we do not know why. 

I think that in addition to the OSX backend on osx, we also need to increase the threshold when running with tkagg on osx.  I'm going to open a PR with that stage and also write up an issue starting the discussion about how we may need to find a more stable way to benchmark these memory issues.
