### ISSUE TITLE
Vertical text alignment in multi-line legend entries

### ISSUE THREAD

**Issue by shikasta-net** [matplotlib/matplotlib#2295]
Hello, I have a problem which seems to be uncommon and I think might be a design bug. Whenever I have an entry in a legend with more than one line of text, the marker is always placed on the last line, not the first. Also, I don't seem to be able to specify the vertical position anywhere so there is no way to override this. As an example:

![lag_time-concentration_cfc](https://f.cloud.github.com/assets/1693155/957863/98a6be6a-0459-11e3-8586-8611a896d641.png)

The label is created with latex, but does the same with ordinary text, I generate the legend with the command:

page.legend(handles, labels, borderaxespad=0.5, handleheight=1.2, labelspacing=0.5, bbox_to_anchor=(0.06,lgnd_height/(fig_height+lgnd_height)), loc='upper left')   

where the anchor is to sort out the external positioning, but has no effect as the same result is produced by 
page.legend(handles, labels, loc=1) 
but isn't so clear an illustration.

Thanks.

**Comment by eggsperde** [comment]
Apologies for resurrecting this thread! I think this would be very helpful to have in mpl... unfortunately I was not able to get it working with the changes in the source of mpl 2.0 as suggested above. Is there something else I could try?

![image](https://cloud.githubusercontent.com/assets/19581262/22527069/a3fe685a-e932-11e6-8188-975afc44c614.png)
