### ISSUE TITLE
[Bug]: Colorbar extend patches do not have correct alpha

### ISSUE THREAD

**Issue by ortk95** [matplotlib/matplotlib#22970]
### Bug summary

When a colorbar has `extend != 'neither'`, the triangles at the end of the colorbar always have `alpha=1`, even when the rest of the colorbar has a different alpha value.

### Code for reproduction

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt

img = np.random.rand(5, 10)
alpha = 0.5

plt.subplot(1, 2, 1)
plt.imshow(img, alpha=alpha, cmap='RdBu')
plt.colorbar(extend='both', orientation='horizontal', label='Current behaviour')

# Temporary fix to manually set the alpha of the extend patches
# doesn't look perfect, but is an improvement over the current behaviour
plt.subplot(1, 2, 2)
plt.imshow(img, alpha=alpha, cmap='RdBu')
cb = plt.colorbar(extend='both', orientation='horizontal', label='Temporary fix')
for patch in cb._extend_patches:
    patch.set_alpha(alpha)

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/26504228/166689164-2e0f569b-7b5d-4bbd-becd-1e7b45a68cde.png)

### Expected outcome

The triangles at the end of the colorbar should have the same alpha as the colorbar (i.e. roughly like the temporary fix above)

### Operating system

OS/X

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.4

### Installation

conda

**Comment by jklymak** [comment]
What happens if you do set_over and set_under?    I actually think the behaviour of the Colorbar alpha matching the alpha of the image is questionable behaviour.

**Comment by ortk95** [comment]
I've just tested this with an older conda environment and the colorbar and triangles have consistent alpha with matplotlib 3.4.3, so this appears to be an issue introduced in a recent update
<img width="511" alt="image" src="https://user-images.githubusercontent.com/26504228/166700225-cd3fffed-2ced-4b61-b069-1f76af5c644a.png">
Figure generated using code in https://github.com/matplotlib/matplotlib/issues/22970#issuecomment-1117358628 using matplotlib 3.4.3 (rather than 3.5.2)

**Comment by greglucas** [comment]
You can specify an RGBA fill in the over:
`cmap.set_over((1, 0, 0, 0.2))`
which does show a light fill, but I tend to agree that the old way was more consistent with what someone would expect. I think this is probably due to the previous versions drawing the extends as part of the primary mesh, while now it is a separate patch.

I think the fix here is to add `self.alpha` into the PathPatch creation of the extends.
https://github.com/matplotlib/matplotlib/blob/f8cd2c9f532f65f8b2e3dec6d54e03c48721233c/lib/matplotlib/colorbar.py#L729-L735

**Comment by jklymak** [comment]
Yes, we definitely changed how the extents are handled.  

OTOH someone, at some point, went in and put plumbing in to change the Colorbar alpha to match the mappable alpha.  I guess that's OK-ish if the the mappable has one alpha, but becomes meaningless if the mappable has multiple alphas (as an image can).  Better in this case would be to make the colormap have an alpha.  I'm not convinced that the original feature was that great.

**Comment by greglucas** [comment]
> Better in this case would be to make the colormap have an alpha

I agree. The colormap does already have an alpha, but it can be out of sync with the image here since the image/mappable has a different alpha. Sorting out how to get the colormap and image to keep their alpha's in-sync may be a bit of a bigger refactor though. I think the fix I put above is a minimal update to get this working again.

**Comment by jklymak** [comment]
Right, I guess I just think our API gets to be messy because of too many automatic hooks that then overlap in functionality.

**Comment by kkoutris** [comment]
I would like to work on this. Is anyone working on it?

**Comment by tacaswell** [comment]
@kkoutris Go for it!  If there is not a linked PR it is safe to assume there is not active work going on.

**Comment by kkoutris** [comment]
@tacaswell if you have the time, can you guide me a bit on what to change to fix this issue?

**Comment by jklymak** [comment]
@kkoutris  https://github.com/matplotlib/matplotlib/issues/22970#issuecomment-1117375968 basically says how to fix the issue.

**Comment by Wikignometry** [comment]
Since I don't see a PR, @kkoutris are you still working on this or could I pick up this issue?
