### ISSUE TITLE
axes.xmargin/ymargin rcParam behaves differently than pyplot.margins()

### ISSUE THREAD

**Issue by funnell** [matplotlib/matplotlib#2298]
When setting the axes.xmargin paramter in my matplotlibrc file to say, 0.05, the margins are increased by much more than 0.05. If I adjust the margins using pyplot.margins(0.05) then I see the expected behaviour.
This seems to be related to the 'tight' parameter in the margins function as setting tight=False reproduces the behaviour of setting the axes.xmargin rcParam.

I suggest having the axes.xmargin/ymargin rcParams behave the same way as the default behaviour of pyplot.margins by having autoscale(tight=True) be run when setting these rcParams. Otherwise, perhaps an autoscale rcParam might be useful?

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. What is the latest discussion / development for this topic? Thanks!
