### ISSUE TITLE
[Doc]: Add toggle prompt to python snippets(prompts) on docs

### ISSUE THREAD

**Issue by dmatos2012** [matplotlib/matplotlib#22982]
### Documentation Link

https://matplotlib.org/devdocs/users/faq/troubleshooting_faq.html#matplotlib-configuration-and-cache-directory-locations

### Problem

Hi, 

I was reading through the docs, and found myself needing these snippets (with `<<<` on it) quite regularly, specially when debugging something about configs or when using `class X` [examples.](https://matplotlib.org/devdocs/api/backend_bases_api.html?highlight=backend#matplotlib.backend_bases.FigureCanvasBase.pick) In order to do so, I either had to type myself the snippet on the python REPL, or copy the snippet and delete the  `<<<` on the prompt, which depending on how many lines it is, it can be a bit cumbersome, even if its a one liner.

### Suggested improvement

Add a toggle prompt that allows to hide the `<<<` like python docs do. I have a PR(not posted) that would add the `sphinx-toggleprompt` and it would fix that minor thing which I found super useful. See below how it would look (as opposed to the one on the docs link)
![image](https://user-images.githubusercontent.com/11776554/166882254-27fe4f51-b65e-4204-8fce-c8e3d6a00e61.png)

Is this something you guys would find useful? PR would only add `sphinx-toggleprompt` and an offset for positioning

**Comment by QuLogic** [comment]
The `>>>` on that page are marked as non-selectable in CSS; it's unfortunate that the copy button still includes them, but selecting and copying should work.

**Comment by dmatos2012** [comment]
Thats true, but the most intuitive would be for the `copy` button to already to that for you, but as you mentioned it doesnt, and you only find out after you have copied. So manually selecting does work, but I found a prompt to be also helpful.

**Comment by timhoffm** [comment]
I have the impression that toggling the pompt is not what a user actually wants to achieve. If it's about copying code, we should make that work directly and only provide an additional crutch that people have to know and understand.

Possibly we want https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells though one should have a quick thought whether that's appropriate everywhere since it is a global configuration.

**Comment by dmatos2012** [comment]
I like that @timhoffm. I just tried with the setting `copybutton_prompt_text = ">>> "` and tried it, and does what we would expect it to do. However, as you mention it can break maybe other copy snippets? I tried around the docs and found it to be working very nicely, prompt or not. Any other places that could be edge cases? Docs are huge :D

**Comment by timhoffm** [comment]
You sould use `copybutton_prompt_text = r'>>> |\.\.\. '` to also catch line continuations like

```
>>> with callbacks.blocked(signal='drink'):
...     callbacks.process('drink', 123)  # nothing will be called
```

I have skimmed through the docs and haven't found a reason not to do this. So this would be an improvement. @dmatos2012 would you be willing to open a PR?
