### ISSUE TITLE
[Bug]: colorbar error when combined array alpha_blending imshow

### ISSUE THREAD

**Issue by zseremo** [matplotlib/matplotlib#22983]
### Bug summary

Trying to alpha_blend my imshow. It's working, until i would like to add colorbar ( and i like to). 

### Code for reproduction

```python
cmap = colors.ListedColormap(['black','red','yellow','green','blue','magenta'])
bounds=[0.5,1.5,2.5,3.5,4.5,5.5,6.5]
norm = colors.BoundaryNorm(bounds, cmap.N)
    
img = plt.imshow(C3_a_ind.reshape(202,125),cmap=cmap, norm=norm,alpha=alpha1)
cbar= plt.colorbar(img, cmap=cmap, norm=norm, boundaries=bounds, ticks=[1,2,3,4,5,6])
cbar.ax.set_yticklabels(['egyes','kettes','hármas','négyes', 'ötös', 'hatos'])
```

### Actual outcome

TypeError                                 Traceback (most recent call last)
<ipython-input-218-c3411fe8e4bc> in <module>
      6 #print(isnan(pl_data))
      7 img = plt.imshow(C3_a_ind.reshape(202,125),cmap=cmap, norm=norm,alpha=alpha1)
----> 8 cbar= plt.colorbar(img, cmap=cmap, norm=norm, boundaries=bounds, ticks=[1,2,3,4,5,6])
      9 #cbar.ax.set_yticklabels(['egyes','kettes','hármas','négyes', 'ötös', 'hatos'])

/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py in colorbar(mappable, cax, ax, **kw)
   2007     if ax is None:
   2008         ax = gca()
-> 2009     ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
   2010     return ret
   2011 colorbar.__doc__ = matplotlib.colorbar.colorbar_doc

/opt/conda/lib/python3.8/site-packages/matplotlib/figure.py in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   2236                              'panchor']
   2237         cb_kw = {k: v for k, v in kw.items() if k not in NON_COLORBAR_KEYS}
-> 2238         cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
   2239 
   2240         self.sca(current_ax)

/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py in colorbar_factory(cax, mappable, **kwargs)
   1683         cb = ColorbarPatch(cax, mappable, **kwargs)
   1684     else:
-> 1685         cb = Colorbar(cax, mappable, **kwargs)
   1686 
   1687     cid = mappable.callbacksSM.connect('changed', cb.on_mappable_changed)

/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py in __init__(self, ax, mappable, **kw)
   1228                 kw['alpha'] = mappable.get_alpha()
   1229 
-> 1230             ColorbarBase.__init__(self, ax, **kw)
   1231 
   1232     def on_mappable_changed(self, mappable):

/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py in __init__(self, ax, cmap, norm, alpha, values, boundaries, orientation, ticklocation, extend, spacing, ticks, format, drawedges, filled, extendfrac, extendrect, label)
    504         else:
    505             self.formatter = format  # Assume it is a Formatter or None
--> 506         self.draw_all()
    507 
    508     def _extend_lower(self):

/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py in draw_all(self)
    540         self._config_axes(X, Y)
    541         if self.filled:
--> 542             self._add_solids(X, Y, C)
    543 
    544     def config_axis(self):

/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py in _add_solids(self, X, Y, C)
    821                   edgecolors='None')
    822         _log.debug('Setting pcolormesh')
--> 823         col = self.ax.pcolormesh(*args, **kw)
    824         # self.add_observer(col) # We should observe, not be observed...
    825 

/opt/conda/lib/python3.8/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_axes.py in pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   6117                                     antialiased=antialiased, shading=shading,
   6118                                     **kwargs)
-> 6119         collection.set_alpha(alpha)
   6120         collection.set_array(C)
   6121         collection.set_cmap(cmap)

/opt/conda/lib/python3.8/site-packages/matplotlib/collections.py in set_alpha(self, alpha)
    769     def set_alpha(self, alpha):
    770         # docstring inherited
--> 771         super().set_alpha(alpha)
    772         self.update_dict['array'] = True
    773         self._set_facecolor(self._original_facecolor)

/opt/conda/lib/python3.8/site-packages/matplotlib/artist.py in set_alpha(self, alpha)
    930         """
    931         if alpha is not None and not isinstance(alpha, Number):
--> 932             raise TypeError('alpha must be a float or None')
    933         self._alpha = alpha
    934         self.pchanged()

TypeError: alpha must be a float or None
![Képernyőkép 2022-05-05 133235](https://user-images.githubusercontent.com/104985415/166914857-d82dd129-ba32-4a28-ab1b-9ee8c9239321.png)

### Expected outcome

As you can see the colorbars colors dissapear. I would liek to keep them like the pic i attach here:
![Képernyőkép 2022-05-05 133403](https://user-images.githubusercontent.com/104985415/166915091-5fd5a32a-9adf-4804-b89e-71fb8aa9b366.png)

(This example pic made whit alpha=none )

### Additional information

If i imshow it without colorbar there wont be error massage, and plots well the fig, ofc without colorbar....  
![Képernyőkép 2022-05-05 133723](https://user-images.githubusercontent.com/104985415/166915538-1d215aa4-45ab-4367-879f-4e770eb5381e.png)

### Matplotlib Version

 3.2.2

### Python version

3.8.3

### Jupyter version

6.0.3

**Comment by oscargus** [comment]
It seems to work in current main (with a random image with random alpha values). Please update to 3.5.2 if nothing else.
