### ISSUE TITLE
[ENH]: Add option to return streamline ending locations from streamplot

### ISSUE THREAD

**Issue by michelob23** [matplotlib/matplotlib#22985]
### Problem

In the field of groundwater modeling, we often perform well capture zone analyses using streamlines. To this end, it would be very useful if Matplotlib's streamplot() function had an option to return the ending locations of the streamlines. That way, I could identify which streamlines terminated at the well and color them differently - it is these streamlines that define the "capture zone." 

### Proposed solution

Please consider providing an option to return the ending locations of streamlines from the streamplot function. I imagine these locations are embedded somewhere in the code already.

**Comment by jklymak** [comment]
You can access the streamlines in `streamlines.lines.get_segments`, but that is probably as public as we would like to get with the streamline properties.  Thanks for the suggestion!
