### ISSUE TITLE
Independent use of imshow interpolation methods[ENH]: 

### ISSUE THREAD

**Issue by wangrenz** [matplotlib/matplotlib#22990]
### Problem

I want to use the interpolation method of imshow alone, but I found it was written in C++.

scipy doesn't have these interpolation methods, like: bessel,lanczos, etc.

Is there any other route to achieve?

**Comment by tacaswell** [comment]
I am 👎🏻 on exposing our interpolations methods as stand-alone functions.  While I understand the desire, it is too far outside of our core mission.

**Comment by jklymak** [comment]
I strongly agree.  I believe they are also backend dependent (eg built into agg) so not in favour of trying to add a layer at top level.
