### ISSUE TITLE
[Doc]: Add figure to `subplots_adjust`

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23005]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots_adjust.html

### Problem

"Inspired" by https://github.com/matplotlib/cheatsheets/issues/109

A figure would help understanding the different parameters

### Suggested improvement

Add a figure looking similar to the one in the cheatsheet, but correct and only containing the argument parameters.

**Comment by kkoutris** [comment]
I would like to work on it.
