### ISSUE TITLE
[Bug]: ax.set_facecolor('grey') requires the plot to be interacted with before updating the colour

### ISSUE THREAD

**Issue by EmptyString1999** [matplotlib/matplotlib#23016]
### Bug summary

When running the code below and saving the image the face colour does not change, it is only when you first do `plt.show()` and then interact with the graph does it change it, at which point it does not save correctly. For the current project i need to generate 300+ charts so having to open each one to interact with and then save isn't really feasible on a time constraint. I have linked code to replicate below.

### Code for reproduction

```python
In console
----
plt.subplot()
plt.gca().set_facecolor('grey')
plt.savefig('this.png')
```

### Actual outcome

a blank graph is saved with a white background

### Expected outcome

a blank graph is saved with a grey background

### Additional information

there was a similar issue a while back #9007 that may be relevant to this

### Operating system

MacOS Monterey 

### Matplotlib Version

3.5.1

### Matplotlib Backend

MacOSX

### Python version

3.9.10

### Jupyter version

N/A

### Installation

pip

**Comment by greglucas** [comment]
I can't reproduce this in a normal console or ipython with the macosx backend (tested on 3.5.1). Maybe you have a global style file hanging around modifying your savefig arguments through the rcParams?

**Comment by jklymak** [comment]
In particular check savefig.transparent is set to False.

**Comment by EmptyString1999** [comment]
Hi,

my apologies for a late reply, i have tried all of the previous suggestions
and none of them seem to be working, I would also like to just note for my
case i need to output as SVG.

kind regards
Ethan Price

**Comment by greglucas** [comment]
I still can't reproduce even with svg. Did you try `plt.savefig('this.svg', transparent=False)`? This gives me a gray background axes, setting `transparent=True` gives me no background.

**Comment by EmptyString1999** [comment]
yep still getting the same error, could this be a mac thing then? seems
strange if so

**Comment by jklymak** [comment]
I cannot reproduce, either with svg or png.  I am on a Mac, but printing should be agnostic as to your operating system.  Please post the _exact_ code you are using, run as a script, not from console, and the files you produce with that code.

**Comment by jklymak** [comment]
I'll close for lack of response.  Two devs w/ Macs cannot reproduce this and no further details have been provided.

**Comment by EmptyString1999** [comment]
Hi Greg,

Thank you for getting back to me on this issue, sorry for the late reply
have been stack in meetings all day, I haven't had a chance to try your
solution yet but will do this afternoon.

Kind regards
Ethan Price
