### ISSUE TITLE
[Doc]: Use python3 instead of python3.x in osx specific docs

### ISSUE THREAD

**Issue by andrew-fennell** [matplotlib/matplotlib#23025]
## Summary
This was something discussed in #23009.

> There is most definitely a better thing than `3.6` to use because we don't support 3.6 anymore 😄  We should probably change all of the `python3.x` to `python3` everywhere... Unfortunately, mac is still only shipping with python2 by default (on my recently upgraded system at least), so `python` is not good enough here.

_Originally posted by @greglucas in https://github.com/matplotlib/matplotlib/pull/23009#discussion_r868003825_

## Proposed fix
At minimum, fix this in the installation guide, where it was mentioned in #23009. I think this should be changed everywhere in the docs. There is no reason to specifically suggest the use of `python3.x`, rather than `python3`.

**Comment by oscargus** [comment]
I think this can be closed now as I cannot find any `python3.x` in the source.
