### ISSUE TITLE
[ENH]: `compare_images`: allow choice of directory for diff image

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#23032]
### Problem

We have a suite that writes out many images to a directory, and we have a directory of known good images that we can use as reference when we make code changes.  I wrote a script that walks through the two directories and pairwise compares the images using `matplotlib.testing.compare_images`.  This all works fine when I generate the test images myself, but recently I wanted to use it on my colleague's output when I was reviewing his code change.  Of course the script fell over because it tried to write the diff image to his disk space, to which I don't have write access.

### Proposed solution

If `compare_images` accepted a keyword to specify where the difference image is written, I could set it to somewhere I have write access.

**Comment by jklymak** [comment]
Can the user easily work around this with a soft link?  If so, I'd rather we kept this simple.

**Comment by greglucas** [comment]
There is also the pytest-mpl package, which allows you to specify output directories for the comparisons.
https://github.com/matplotlib/pytest-mpl

**Comment by rcomer** [comment]
Thanks for taking the time to consider this.  The task as outlined by @tacaswell looks a bit too involved for me to commit to in the short term (though I wouldn't rule it out in the medium term).  I would need to learn `pathlib` for a start!

> @greglucas the pytest-mpl package

In my case I'm not writing tests as such, just looping through pairs of images and, if a difference is found, popping up an image viewer so I can eyeball it.

> @jklymak Can the user easily work around this with a soft link?

Actually this works great for my case:

```python
    with tempfile.TemporaryDirectory() as tmpdirname:
        tempimage = os.path.join(tmpdirname, os.path.basename(newimage))
        os.symlink(newimage, tempimage)
        try:
            result_string = mcompare.compare_images(oldimage, tempimage, tol=0)
```
I guess it would need more thought if you wanted to retain the directory structure, but I'm deleting each diff before comparing the next pair, so that's not a problem for my current case.

So I think I withdraw my feature request.  I'll leave it up to you whether you want to leave this open for the "third hand" use case outlined above.

**Comment by tacaswell** [comment]
I'm going to close this.  If we get to the "third-hand" use case above we can reopen/reconsider when we understand the actual need rather than my current wild peculation.

Thank you @rcomer , I think this was a useful discussion and I hope everyone is satisfied with where it landed.
