### ISSUE TITLE
[Bug]: colorbar axes title clobbers extend arrow

### ISSUE THREAD

**Issue by nspies-celsiustx** [matplotlib/matplotlib#23041]
### Bug summary

Adding a title to a colorbar works fine in most cases, but misplaces the title text when using `extend=max` as argument to `plt.colorbar()`.

### Code for reproduction

```python
fig, ax = plt.subplots(figsize=(6,6))
x, y, z = [np.random.random(100) for i in range(3)]

scatter = ax.scatter(x, y, c=z)
cbar = plt.colorbar(scatter, extend="max", ax=ax)
cbar.ax.set_title("asdf")
```

### Actual outcome

![image](https://user-images.githubusercontent.com/50211122/168171540-7c175017-3276-45a5-8945-de12e4215e73.png)

### Expected outcome

I would expect the title text to be above the colorbar including the arrow. This is what happens when running the above code but without `extend="max"`:

```python
fig, ax = plt.subplots(figsize=(6,6))
x, y, z = [np.random.random(100) for i in range(3)]

scatter = ax.scatter(x, y, c=z)
cbar = plt.colorbar(scatter, ax=ax)
cbar.ax.set_title("asdf")
```

![image](https://user-images.githubusercontent.com/50211122/168171600-c6eef2f2-ed94-4f42-9f9e-4d37944d8bf4.png)

### Additional information

Aesthetically, this is less of an issue with smaller figure sizes but it should generally place the text in the right place irrespective of figure dimensions.

### Matplotlib Version

3.5.1

**Comment by jklymak** [comment]
This is fixed in 3.5.2 and was closed by #22313. Sorry for the bother
