### ISSUE TITLE
Add an argument rotate_labels to pie chart

### ISSUE THREAD

**Issue by mmokrejs** [matplotlib/matplotlib#2304]
The text descriptions of individual pie slices are always output in horizontal orientation. Therefore, texts often overwrite each other. One can get around a bit by setting larger labeldistance but only unless there are too many slices close to each other.

Please provide an argument so that the text descriptions would follow the angle of its corresponding pie slice.

This has been discussed at http://matplotlib.1069221.n5.nabble.com/A-pie-chart-with-rotated-text-labels-td39059.html

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. I don't think there has been any update (please correct me otherwise) and a PR is still welcome.

**Comment by WeatherGod** [comment]
I would tag this as a fairly easy task for a newcomer. It would need a bit
more fleshing out on what exactly the API should be, and what sore of
rcparams should be added, but the implementation itself should be fairly
straight-forward once we have a spec.

**Comment by tacaswell** [comment]
This is self-contained (touches exactly one function), but tagged as medium as some thought is needed about the API.

The simplest API would be a bool flag of `rotate=True`, but taking a vector of angles would give more (too much?) flexibility.

Implementation wise, should probably make sure the text is as 'right side up' as possible.
