### ISSUE TITLE
[Doc]: Docstring for artist.Artist.set_agg_filter is incorrect

### ISSUE THREAD

**Issue by joezuntz** [matplotlib/matplotlib#23050]
### Documentation Link

https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.artist.Artist.set_agg_filter.html#matplotlib.artist.Artist.set_agg_filter

### Problem

The docstring for artist.Artist.set_agg_filter states that it accepts "A filter function, which takes a (m, n, 3) float array and a dpi value, and returns a (m, n, 3) array."

This seems to be incorrect - the filter function can actually accept (m, n, 3) or (m, n, 4) arrays, depending on whether an alpha channel is used, and must also return two offsets from the lower-left corner, as described here:
https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/backends/backend_agg.py#L384

### Suggested improvement

The parameter part of the docstring at https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/artist.py#L925-L939 should be something like:

```
        filter_func : callable
            A filter function, which takes a (m, n, depth) float array and a dpi
            value, and returns a (m, n, depth) array and two offsets from the bottom 
            left corner of the image
            .. ACCEPTS: a filter function, which takes a (m, n, 3) float array
                and a dpi value, and returns a (m, n, 3) array and two offsets
                from the bottom left corner of the image
```

**Comment by SaumyaBhushan** [comment]
@joezuntz I would like to work on this.

**Comment by tacaswell** [comment]
@SaumyaBhushan please do!  Looking forward to seeing your PR.

**Comment by SaumyaBhushan** [comment]
Thanks @joezuntz

**Comment by QuLogic** [comment]
Seems to have been fixed by the above PR.
