### ISSUE TITLE
Request: Set figure size in pixels, not inches

### ISSUE THREAD

**Issue by nbigaouette** [matplotlib/matplotlib#2305]
Working with inches is counter-intuitive in my work flow, and I'm pretty sure it is for many people.

For example, I often generate a figure and save it using the GUI. The saved png thus  have a nice resolution of 2400x1220. Now I want to automate the saving but have to translate this pixel resolution to inches and dpi, which I have no clue.

Google is full of questions about this. Most answers suggest calculating the size in inches using a dpi value and the pixel size. Why not integrate this directly in matplotlib? 

This [wiki page](http://wiki.scipy.org/Cookbook/Matplotlib/AdjustingImageSize) explain the usage of set_figsize_inches(). Setting the figure size in inches //does// require having a dpi value somewhere. I think having a set_figsize_pixels() would be really useful.

Thanks

**Comment by patquem** [comment]
Hello,

For 1 week I am trying desesperatly to find a method allowing to save a tricontourf on a 2D numpy.array for which I set the size (to know precisely the link between pixel and physical lenght or in anoteher world the pixel size).
I was enjoyed to find your post, but I didn't arrive to set precisely what I am looking for.

Here is a part of my code 

    frame1 = plt.gca()
    frame1.axes.set_axis_off() # to remove axis when building final 2D array
    
     # Since my original shape is contained in a [10;10]x[10;10] bounding box, I set my axis as following
    plt.xlim(-12,12)
    plt.ylim(-12,12)
    plt.gca().set_aspect('equal', adjustable='box')
    
    # I use what you wrote to set my future 2D array to 1024x1024 resolution
    fig = plt.gcf()
    DPI = fig.get_dpi()
    fig.set_size_inches(1024.0/float(DPI),1024.0/float(DPI))    
    
    # Here is my 2D projection of my 3D shapes (it works well and fast)
    plt.tricontourf(x, y, triangles, z, levels=levels)
    
    # save and reload image
    buffer_ = StringIO()
    plt.savefig( buffer_, format = "png", bbox_inches = 'tight', pad_inches = 0)
    buffer_.seek(0)

    image = PIL.Image.open( buffer_ )

    ar = np.asarray(image)
    print ar
    print ar.shape    # ?? my array is (1015L, 1032L, 4L) not (1024L, 1024L, 4L) as expected. 

What to do to exactly recover a 1024x1024 image ? Thank you.

**Comment by tacaswell** [comment]
If you use `bbox_inches='tight'` it resizes the figure to 'shirnk wrap' the
visible artists in your figure.

Tom

**Comment by patquem** [comment]
deleting `bbox_inches='tight' my final resolution becomes square :) but with 1280x1280 pixels :((
So what to do, to really control-impose the resolution of my final image ?

**Comment by jenshnielsen** [comment]
Matplotlib has both a onscreen DPI and a Savefig DPI. In 1.5 the they are 80 and 100 by default. If 2.x we will change them to be identical. I think fig.DPI will return the display not the save dpi. 

 One way of working around this should be to force the savefig dpi to match the onscreen one:

```
plt.savefig( ... dpi='figure') 
```

**Comment by patquem** [comment]
Excellent !  That preserves the good resolution (1024x1024). Thanks Jens.
My code does now what I want, 
To make it better (in term of CPU performance), instead of saving then reading a .png file do you see a fastest method to project contourf on the 2D array ? (get_array ?)

**Comment by eromoe** [comment]
In jupyter 
```
fig = gcf()
DPI = fig.get_dpi()
fig.set_size_inches(2400.0/float(DPI),1220.0/float(DPI))
```
doesn't give me exact picture with 2400, 1220  .
I just want to make sure how wide this figure is .

----

My target is automatically set a compact and beatuful xlabels, default gap in  is too wide for me .I am trying to 
1. get figure width in pixel
2. get my font size, calculate xlabel length in pixel
3. if I set rotation, calculate the vertical edge and horizon edge lenghts in pixel
4. if  (xlabel number) * (horizon edge lenght) > figure width in pixel, go to 6 ,  else go to 5
5.  xlabel number = xlabel number/ 2 , go to 4
6. generate xlabel and set to figure .

I also don't understand why matplotlib doesn't achieve this kind of display of xlabel.

**Comment by ImportanceOfBeingErnest** [comment]
@eromoe That is due to a default setting in jupyter (i.e. IPykernel's inline backend) and hence out of matplotlib direct control. You can make sure to not produce figures via the `bbox_inches="tight"` option by setting

    %config InlineBackend.print_figure_kwargs = {'bbox_inches':None}

in jupyter.

**Comment by wayneworkman** [comment]
I have this error:
`ValueError: Image size of 500000x1100 pixels is too large. It must be less than 2^16 in each direction.`
I found this github issue hoping to find out how to set image size in pixels, since the limit is pixels.
Would be nice if I can define image size with pixels instead of inches, just as an option.
