### ISSUE TITLE
[Bug]: QT5Agg gui crashes when using Figure Options (if more than 1 axis is present)

### ISSUE THREAD

**Issue by raphaelquast** [matplotlib/matplotlib#23103]
### Bug summary

this is a follow-up for #22543

to summarize:

The QT gui window crashes and becomes completely irresponsive if I click on the "figure-options" button 
for a figure containing more than 1 axes.

- the issue ONLY happens in interactive mode. with `plt.ioff()` all works as expected.
- the issue happens in a "plain" python console
- the issue does NOT occur in a "plain" IPython console
  - (however it does appear in the Spyder IDE using a IPython QT console)

I checked and explicitly using `plt.show(block=True/False)` or a plain `plt.show()` does not help.

![mpl_issue](https://user-images.githubusercontent.com/22773387/169487758-360e1c2b-6d8a-4a8c-a14b-586426a05cf7.gif)

### Code for reproduction

```python
# clicking on the "figure options" button on one of the following figures crashes the gui:
import matplotlib.pyplot as plt
plt.ion()
f, ax = plt.subplots(2)
# >> now edit the axis limits in the gui

import matplotlib.pyplot as plt
plt.ion()
f, ax = plt.subplots()
ax2 = ax.twinx()
# >> now edit the axis limits in the gui
```

### Actual outcome

gui crashes

### Expected outcome

gui remains responsive

### Operating system

Windows

### Matplotlib Version

3.5.2

### Matplotlib Backend

QT5Agg

### Python version

3.7.12

### Installation

conda

**Comment by jklymak** [comment]
I cannot reproduce on MacOS.

**Comment by raphaelquast** [comment]
To make sure this is not an issue with my local setup I did a quick check in a fresh minimal env with:
```
conda create -n mpltest -c conda-forge matplotlib
```
I still get the same behavior with `python 3.10.4` and `matplotlib 3.5.2` (running on `windows 10`)
(`TkAgg` backend works as expected)

**Comment by oscargus** [comment]
I can confirm this on Windows 10. (Works without problems on Linux as well.)

To me it seems like the axis selection dialogue quickly shows up or is then either closed or positioned behind the plot window. As one need to select an axis, one cannot really do anything.

**Comment by timhoffm** [comment]
I'm confirming that this is not fundamentally a Qt bug:
```
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QInputDialog

def show_dialog():
    QInputDialog.getItem(window, "Title", "Label:", ['item 1', 'item 2'], 0, False)

app = QApplication([])
window = QMainWindow()
window.resize(300, 200)
button = QPushButton('Click', window)
button.clicked.connect(show_dialog)

window.show()
app.exec()
```

has the dialog on top. So this is somehow on us. (Well, we could have guessed that because it only happens under very special circumstances).

**Comment by raphaelquast** [comment]
Hey, just noticed that this was actually already fixed by 423f465988089d7bb92e43f1d3d28efbd54b3b44
(e.g. making the window non-blocking does the job)

Thanks! 🥳

**Comment by raphaelquast** [comment]
@J-Sorenson Since I'm also using Spyder, I did a quick check to see if I can reproduce this.  However, with the latest `Spyder 5.4.2` and `matplotlib  3.6.3` I don't get any issues (e.g. popups and edit dialogs work just fine).

**Comment by J-Sorenson** [comment]
> @J-Sorenson Since I'm also using Spyder, I did a quick check to see if I can reproduce this. However, with the latest `Spyder 5.4.2` and `matplotlib 3.6.3` I don't get any issues (e.g. popups and edit dialogs work just fine).

Sounds hopeful.  However, I'll have to wait until the new Spyder is available on the Enterprise Anaconda server.
