### ISSUE TITLE
[Bug]: inconsistent handling of dates near year 0001

### ISSUE THREAD

**Issue by hdouglas** [matplotlib/matplotlib#23117]
When attempting to plot dates near year 0001 using matplotlib.dates' datetime format, the conversion to ordinal and back is handled differently depending on what dates are called. 

### Code for reproduction 
```
import matplotlib.pyplot as plt 
import matplotlib.dates as mdates

# Set some datetime ranges close to year 0001 
a = ['0050-01-16','0050-02-16','0050-03-16']
a1 = mdates.datestr2num(a)
dates1 = mdates.num2date(a1)
print(dates1)

b = ['0010-01-16','0010-02-16','0010-03-16']
b1 = mdates.datestr2num(b)
dates2 = mdates.num2date(b1)
print(dates2)

c = ['0003-01-16','0003-02-16','0003-03-16']
c1 = mdates.datestr2num(c)
dates3 = mdates.num2date(c1)
print(dates3)

# Plot only the earlier two sets
fig1 = plt.figure(figsize=(10,5))
ax = fig1.add_subplot(111)
ax.plot(dates2,[1,2,3],'bo')
ax.plot(dates3,[1,2,3],'ro')

# Plot all three
fig2 = plt.figure(figsize=(10,5))
ax = fig2.add_subplot(111)
ax.plot(dates1,[1,2,3],'ko')
ax.plot(dates2,[1,2,3],'bo')
ax.plot(dates3,[1,2,3],'ro')
```

### Expected outcome
Both fig1 and fig2 plot some dates and values

### Actual outcome
fig1 plots, and attempting to plot fig2 returns the following error:
```
File ".../miniconda3/envs/sb03/lib/python3.9/site-packages/matplotlib/dates.py", line 350, in _from_ordinalf
    raise ValueError(f'Date ordinal {x} converts to {dt} (using '

ValueError: Date ordinal -719278.3 converts to 0000-09-06T16:47:59.999992 (using epoch 1970-01-01T00:00:00), but Matplotlib dates must be between year 0001 and 9999.
```
### Matplotlib version 
3.5.0

### Python version
3.9.7

### OS
Mac OS 10.15.7

Apologies if I haven't nailed the bug reporting format - this is my first issue report.

**Comment by oscargus** [comment]
I think the problem is that the plot is trying to create a tick in year 0000 and that Matplotlib cannot handle that. It works for the first plot as the range is smaller so automatic tick creating doesn't go below year 0001.

You can get around this by setting the limits explicitly before plotting. Something like:
```
ax.set_xlim((mdates.num2date(mdates.datestr2num('0001-01-01')), mdates.num2date(mdates.datestr2num('0051-01-01'))))
```
will fix this particular problem.

**Comment by jklymak** [comment]
Yes our tickers depend on rrule which depend on the datetime module, which does not allow dates less than year 0001.  

Is there a reason you are plotting such precise dates from 2000 years ago?

**Comment by hdouglas** [comment]
Thanks! I hadn't picked up that it was to do with the automatic tick creating. The workaround works for me.

I am working with climate models that are simulating hypothetical scenarios, so the data have precise dates, but start at year "1".

**Comment by jklymak** [comment]
Just as a comment - many climate models Im familiar with have a relatively loose idea of dates. Are you sure our Gregorian tickers are even appropriate?
