### ISSUE TITLE
[Bug]: BrokenBarHCollection background coloring is not coloring the right section when more than 2 sections are set

### ISSUE THREAD

**Issue by cyrpaut** [matplotlib/matplotlib#23143]
### Bug summary

When using multiple section coloring (more than 1), the second and third section colored is not following the indications passed as an argument. Could be in separate collections object of one object as a list.

### Code for reproduction

```python
fig, ax = plt.subplots(nrows=2, figsize=(10,10))
df = pd.DataFrame(np.random.randint(0,100,size=(100, 2)), columns=list('AB'))

# Does not set the right span for x on the third feature
df['A'].plot(ax=ax[0])

c1 = collections.BrokenBarHCollection([(0,10)], (0,100), facecolor='gray', alpha=0.1)
c2 = collections.BrokenBarHCollection([(20,30)], (0,100), facecolor='blue', alpha=0.1)
c3 = collections.BrokenBarHCollection([(40,50)], (0,100) , facecolor='red', alpha=0.1)

ax[0].add_collection(c1)
ax[0].add_collection(c2)
ax[0].add_collection(c3)

df['B'].plot(ax=ax[1])
c4 = collections.BrokenBarHCollection([(0,10), (20,30), (40,50)], (0,100), facecolor='red', alpha=0.1)

ax[1].add_collection(c4)
```

### Actual outcome

![error_BrokerBarHCollection](https://user-images.githubusercontent.com/15875320/170569316-c2452b76-da3c-4ae5-8bf7-ac91ac50d692.svg)

### Expected outcome

I would expect 
* The second section to span over (20, 30) and instead is span over (20,50)
* the third section to span over (40,50) and instead it span over (40, 90)

### Additional information

It does not work under '3.5.1'. I upgraded to '3.5.2' but it does not change the result.

### Operating system

Ubuntu

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.8.10

### Jupyter version

3.4.2

### Installation

pip

**Comment by jklymak** [comment]
The x values are (x0, xwidth),  so (20, 30) will span 20 to 50.  I think this is behaving properly...
