### ISSUE TITLE
imsave() should allow to store EXIF tags

### ISSUE THREAD

**Issue by jwuttke** [matplotlib/matplotlib#2314]
When processing an image using

```
im = misc.imread( fnam )
# modify im
misc.imsave( fnam, im )
```

all EXIF tags are lost.

Optional support for EXIF would be very useful for photo processing. What about the following?:

```
im, tags = misc.imread( fnam )
# modify im, using e.g. ... tags['DateTimeOriginal']
misc.imsave( fnam, im, exif=tags )
```

**Comment by petehuang** [comment]
Can someone provide instructions for reproduction to help confirm in later MPL versions?

**Comment by tacaswell** [comment]
This may be supported now via https://github.com/matplotlib/matplotlib/pull/7349

**Comment by QuLogic** [comment]
That only added PNG, which doesn't technically support EXIF. I would guess the target here is JPG; the interface would be the same as #7349 probably, with a difference in implementation of course.

**Comment by anntzer** [comment]
One can now just rely on Pillow's exif support (https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#png-exif-data) and pass kwargs to Pillow via the pil_kwargs parameter.
