### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by erik-jan-climate** [matplotlib/matplotlib#23159]
### Bug summary

subfigures: 
Errors, fails: 
1)    .clabel(cConH,  inline=True,inline_spacing=0, fontsize=2.6)   error: 
"object has no attribute '_cachedRenderer' "

2) cb.set_label(label='abc')   
Error:  no effect, no label set to each of the (in my case: 3, here just shown 2) colorbars

### Actual outcome

![image](https://user-images.githubusercontent.com/18178178/170869891-db87e43f-5558-4fac-aa6a-411b96e290a3.png)

With subfigures (3subfig, each 4panels) the colorbar of each subfig misses:   ticklabels & colorbarlabel. 

In addition:  Setting  .clabel()  to show inline contour labels (here: a two digit number.  This error/requirement applies here only to the upper 4 panels, the other panels are not meant to show contour lines)  fails with error: 
"object has no attribute '_cachedRenderer' "

(To create this uploaded coarse and intermediate figure, I've commented out the respective line, but my aim is to include this inline label information for my final figure;  so I like to re-activate this line asap) 

.  All of these failing features (missing colorbar ticklabels and colorbarlabel, and inline contour labels)  appear properly when creating separate figures with matplotlib (= 3 separate figures, each with 4panels). So I suspect that the subfigure codes in matplotlib are not (yet) 100% compatible and supporting all features that are supported when creating individual figures (without applying subfigure)

### Support and Response aim to this request 
Please let me know as soon as there are source code improvements and/or bugfixes related to any subfigure source code chapters in matplotlib. 

### Expected outcome

1) Ticklabels at each of my 3 colorbars  (here on github, only two colorbars are shown as illustrative examples): 
![image](https://user-images.githubusercontent.com/18178178/170871954-1f801699-0056-4086-89fa-683f199c08ca.png)

2) A colorbar label for each subfigure (e.g. to show the units and physical quantity represented by the color of each colorbar, example: see picture above this text line)
3) Inline contourlabels in the upper four subplots of the first subfigure: 
![image](https://user-images.githubusercontent.com/18178178/170871928-9b239fde-c00a-4aac-b0cd-c9b44c183b74.png)

###

### Operating system

Unix, centos, HPC, conda env (most recent)

### Matplotlib Version

3.5.2

### Matplotlib Backend

pdf

### Python version

3.9.13

### Jupyter version

-

### Installation

conda

**Comment by jklymak** [comment]
Please provide a complete and reproducible standalone example.   It's not possible to infer what has gone wrong from this.

**Comment by jklymak** [comment]
I'll close for now due to lack of response.   However, if you cobble together a self-contained example, happy to re-open.  Thanks!

**Comment by jklymak** [comment]
(PS I somewhat suspect your figures are simply too small, and that you are not using constrained_layout).
