### ISSUE TITLE
[MNT]: requirements/testing/minver.txt could also test oldest-supported pytest version

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#23154]
### Summary

pytest.ini claims that we support pytest>=3.6; we could add a version pin in requirements/testing/minver.txt to check that 3.6 is indeed supported (I don't know if that's actually the case!).

**Comment by SaumyaBhushan** [comment]
@anntzer Should I add **pytest>=3.6;** in the requirement.txt file.

**Comment by SaumyaBhushan** [comment]
Will it work as a solution for this?

**Comment by timhoffm** [comment]
If we add the constraint, we should validate that it's correct.

I'm a bit hesitant whether we need that constraint. Lower constraints are increasing from time to time and we won't know that because we don't test with the lowest versions. We would only learn from that if a user (or dev) happens to have such an installation and reports back. Unless somebody does something very specific setting up a new environment from requirements will fetch the most recent version.

**Comment by anntzer** [comment]
It should be validated, yes. I don't really mind if we do, but if we don't, we should remove the claimed version bound in pytest.ini.

**Comment by shade34321** [comment]
Is all that is needed is to set up a virtual env, ensure pytest 3.6 is installed, and run the tests? If so I think I can do that and would like to work on this for hacktoberfest.

**Comment by tacaswell** [comment]
@shade34321 Doing this as on one-off test locally is useful information, however what this issue is proposing is to change the CI configuration so that one of our jobs runs with the version of pytest that we claim is the minimum supported version.

**Comment by shade34321** [comment]
That makes more sense! I was curious how just running it once and awhile would be that helpful. Is the proposed solution above of adding it [here](https://github.com/matplotlib/matplotlib/blob/main/requirements/testing/minver.txt) sufficient? Then fixing anything that is broken or upgrading the min version to something that does work? Regardless it doesn't sound too difficult and would like to work on this if possible.

**Comment by Shikharishere** [comment]
Is this issue still open??

**Comment by tacaswell** [comment]
Yes, I believe so.

**Comment by Shikharishere** [comment]
Okayy

**Comment by harshvardhan2707** [comment]
So if I understand clearly, just ```pytest==3.6.0``` needs to be inserted [here](https://github.com/matplotlib/matplotlib/blob/main/requirements/testing/minver.txt)?

**Comment by tacaswell** [comment]
Yes.
