### ISSUE TITLE
[MNT]: better microsecond handling in mpl.dates.dateformatter

### ISSUE THREAD

**Issue by bradlipovsky** [matplotlib/matplotlib#23179]
### Summary

mpl.dates.DateFormatter('%H:%M:%S.%f') returns too many digits in the microseconds
Available solutions seem convoluted (see: https://stackoverflow.com/questions/11040177/datetime-round-trim-number-of-digits-in-microseconds)

**Comment by jklymak** [comment]
Can you elaborate with a minimal example and what you think the result should be?

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open.
