### ISSUE TITLE
[Doc]: Bracket ArrowStyle Angle Unclear

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#23176]
### Documentation Link

https://matplotlib.org/devdocs/users/prev_whats_new/whats_new_3.4.0.html?highlight=bracket#angles-on-bracket-arrow-styles

### Problem
I can't tell from this figure what Angle = 60 is relative to, since the top angle is >60 and the lower angle is <60 in the first example, and '0 degrees means perpendicular to the line' is buried in the api docs (I missed what that means like 6 times)

![image](https://user-images.githubusercontent.com/1300499/171474679-ee821900-35a2-4355-8759-bff6aad1ab63.png)

### Suggested improvement

An example, that's cross referenced against the API docs, where the angle is marked up, similar to the [scale invariant](https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/angle_annotation.html) docs
![image](https://user-images.githubusercontent.com/1300499/171475277-86bcfd55-fe76-42e6-970a-f2d1eeb05f68.png)

I think it'd be nice to include the formulas for setting the bracket horizontal or vertical relative to the axes, but that's totally extra. I think it's a good first issue since it's completely standalone, a relatively small addition, and this information is missing.

**Comment by lucasricci** [comment]
Hello, I would like to work with that issue. However, I think I did not completely understand your idea, it is to draw the angles in the image to make it more clear, like in your sugestion?

**Comment by story645** [comment]
Exactly, a
1. new gallery example (this may end up appended to an existing example, but easier if you start it new)
2. that looks like the bracket example from what's new
3. where the angle argument is annotated like in the scale invariant angle

**Comment by lucasricci** [comment]
@story645 Something like this?
![image](https://user-images.githubusercontent.com/62891523/173466842-5b06c0aa-b8e3-48e8-8845-28647779e64b.png)

**Comment by story645** [comment]
Yup, except the angle is always between the brace and the perpendicular

**Comment by lucasricci** [comment]
I see, but I'm unsure how I would do that with matplotlib

**Comment by story645** [comment]
I think by importing the ArcAnnotation class from the scale invariant example (you can cross link in the text) and using that to label the angles. I think the perpendicular can be drawn using either vlines or plot.

**Comment by lucasricci** [comment]
Ok, thanks. I'll see this tomorrow

**Comment by lucasricci** [comment]
I successfully created the lines using `vlines()` but I can't do the same with `Arc()`

![Figure_1](https://user-images.githubusercontent.com/62891523/173940835-23a1416a-addc-4b77-9e31-eccba9b57f90.png)

**Comment by jacoverster** [comment]
Hi @story645, can I contribute to this issue? Is this what you are looking for:

![image](https://user-images.githubusercontent.com/22006760/194542736-8ef183c2-9e5b-474e-b9e5-33e0ffecea17.png)

**Comment by timhoffm** [comment]
Bonus: Maybe add an arrow head to the grey arc to indicate the angle direction?

**Comment by jacoverster** [comment]
Sure thing @timhoffm, I'll look into that.

**Comment by jacoverster** [comment]
Hi @timhoffm, I looked at some ways of adding the arrows.

One way is to simply add a FancyArrowPatch to the plot (as shown below), but this won't be scale invariant.

![image](https://user-images.githubusercontent.com/22006760/195007400-eb8d7de1-b7a8-495e-ae0a-0915c9610f6a.png)

Secondly, I added an arrow annotation to AngleAnnotation (similar to the text annotation):

`self.arrow = ax.annotate("", xy=(0.5, 0.5), xytext=(0, 0), arrowprops=arrowprops, **self.kw)`

I then tried to update it's position at plot time. I can easily set self.arrow.yx (similar to self.text.xy) but can't access the xytext variable (arrow._arrow_relpos I believe) to tell the updated arrow where to point from.

Is it possible to set this during plot time, and if not do you have any other suggestions? Perhaps the scale invariant solution is fine?

**Comment by timhoffm** [comment]
The `FancyArrowPatch` is fine here. This is mainly used as a static illustration in the docs. Scale invariance is not important.

**Comment by jacoverster** [comment]
Ok thanks for the guidance @story645, first contributor here so a lot to learn 👌🏻😁 Appreciate it.

Should I delete the PR?
