### ISSUE TITLE
Things to add to mathtext tests

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23211]
This PR serves as a place to collect things that needs testing in mathtext. As we currently try to not add too many new reference images in the repo, it makes sense to collect things and add them in a single image. This holds for things being removed due to modifications or simply new things that are fixed. 

* overunder expressions #23209, basically anything in https://github.com/matplotlib/matplotlib/blob/f8ab9522c2a1bb4ec9e524a12124e3416f8c6701/lib/matplotlib/_mathtext.py#L1672-L1677 especially when there is only an over part

This is the list of strings for generating tests: https://github.com/matplotlib/matplotlib/blob/f8ab9522c2a1bb4ec9e524a12124e3416f8c6701/lib/matplotlib/tests/test_mathtext.py#L17

**Comment by QuLogic** [comment]
I'm a little confused what the action going forward here is.

**Comment by oscargus** [comment]
It may be to close this. I was under the impression that there were a number of PRs where tests were removed (like improved spacing), but I am no longer convinced that is the case.

(Still I think that there are expressions that are not so well tested, like all the accents supported.)
