### ISSUE TITLE
[MNT]: Rename examples with "test" in the name

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#23214]
### Summary

Some example files have "something_test.py" in their name which can be picked up as tests and isn't really a clear example name. These could probably be renamed.

Identified in: https://github.com/matplotlib/matplotlib/pull/23130

Example of a poor name: https://github.com/matplotlib/matplotlib/blob/main/examples/scales/log_test.py

cc: @matthewfeickert

### Proposed fix

Update all non-test files with "test" in their name to something else.

**Comment by matthewfeickert** [comment]
Thanks for taking the time for write this up @greglucas! I'll put it on the docket for tomorrow. :+1:

**Comment by matthewfeickert** [comment]
As of 8e2987b9804b6eaa32b8ffa40059e0d5267960ee there are only 4 `.py` files that match the problematic pattern

```console
$ find examples/ -type f -iname "*test*.py"
examples/scales/log_test.py
examples/text_labels_and_annotations/usetex_baseline_test.py
examples/units/evans_test.py
examples/units/artist_tests.py
```

so this should be easy to cleanup.
