### ISSUE TITLE
[ENH]: matplotlib.figure.Figure add axis method.

### ISSUE THREAD

**Issue by evan0greenup** [matplotlib/matplotlib#23210]
### Problem

Currently, if a figure is created by `matplotlib.figure.Figure()`, then if user want to turn axis off, `Figure` object doesn't have `axis()` method like what `matplotlib.pyplot` do.

### Proposed solution

It would be nice to add a method in `matplotlib.figure.Figure()`.

**Comment by jklymak** [comment]
The axes object has the axis method, not the figure.
