### ISSUE TITLE
[ENH]: Make it so that linestyle works the same way as color when plotting several bars, lines, scatter points, etc.

### ISSUE THREAD

**Issue by AndreasBugten** [matplotlib/matplotlib#23222]
### Problem

Hello!

I am trying to plot a series of bars within a bar plot, and I want each bar to have its own color and linestyle. I intend to achieve this by using a list of colors, and a list of linestyles, and then simply plot the bars and set the color and linestyle to their respective lists. This works for color, but not for linestyle, since the linestyle function does not recognize a list as input.

Below I have two code snippets, and their respective outputs, which highlights the problem.

First, without using linestyle:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/106192446/172563688-bb3d68cf-5aed-4a3a-9b56-b2c1bdfb172e.png">

Then, using linestyle:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/106192446/172563953-bf041d1a-fe28-4046-8653-479584bd6f33.png">

I have checked that all of the linestyles are compatible with the plt.bar function.

**Comment by oscargus** [comment]
Some parameters are dealt with here and a cycler is created which is used to loop over for each rectangle patch:
https://github.com/matplotlib/matplotlib/blob/8e2987b9804b6eaa32b8ffa40059e0d5267960ee/lib/matplotlib/axes/_axes.py#L2381-L2392

The remaining parameters are added to the rectangle patch here:
https://github.com/matplotlib/matplotlib/blob/8e2987b9804b6eaa32b8ffa40059e0d5267960ee/lib/matplotlib/axes/_axes.py#L2430

I see two possible solutions:
1. Create a cycler for the linestyles/dashpatterns.
2. Add the remaining parameters to the BarCollection instead. (Not sure this works though.)

I'll take this into consideration in #23056 and see if something can be done to make simplify this procedure.

**Comment by timhoffm** [comment]
I think it has been a design mistake that `bar()` can style individual bars separately. Conceptually, all bars from one call belong to one logical data set (which has multiple values). For example, one can only set one label.

Therefore I suggest not to expand further in this direction. We generally don't want trivial vectorization on the methods as that increases implementation complexity.

```
for x, y, color, linestyle in zip([1, 1.25, 1.5, 1.75], [2, 2, 2, 2], colors, linestyles):
    ax.bar(x, y, 0.05, color=color, linestyle=linestyle)
```
seems simple enough.

**Comment by timhoffm** [comment]
@AndreasBugten thanks for the suggestion. As laid out in the comment above, I don't want to expand the `bar()` API to style individual bars separately.
