### ISSUE TITLE
[MNT]: Replace numpy.random in tests by default_rng

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#23224]
as documented in #23221.

To be checked: Is this the same algorithm as before? If not tests would fail and we should not replace the existing calls.

**Comment by story645** [comment]
I'm a little confused how this diverges from the discussions in #19706

**Comment by timhoffm** [comment]
#19706 changed user-facing examples. The fear there is that users are sitting on older versions of matplotlib and numpy and get an error when they copy the example code.

Here the scope is limited to tests. We require numpy 1.17+ for the current codebase and that also applies to tests. People working on matplotlib cannot fall into the numpy-too-old trap.

**Comment by tacaswell** [comment]
I am 50/50 if the tests pass with the new generator (seems like a bunch of work and code changes for a low pay-off if numpy is not going to deprecate the old API) and 👎🏻 if this change requires any tests to be changed (because changing tests is a bad idea on principle).

**Comment by timhoffm** [comment]
I'm fine with closing. But then we should add a note as a follow up to #23221 that existing tests should be kept with the old API.

**Comment by tacaswell** [comment]
I honestly neutral on this.  Despite my concerns, Jody is right that this is an easy first issue and people are at least as likely to find another test and copy-paste-edit rather than read the docs and write one from scratch so it will be easier on everyone if our tests all follow the documentation.  

We should at least find out if it breaks stuff before before closing.

**Comment by rcomer** [comment]
I tried this with [one test](https://github.com/matplotlib/matplotlib/compare/main...rcomer:matplotlib:random-tests) and it fails.  A lot of tests in that module that use random data are also using `check_figures_equal`, so would presumably be fine if the generated data changed.  Some tests in the module use random data without setting a seed.

**Comment by QuLogic** [comment]
Isn't that because you didn't change the `standard_normal` on the next line, causing it to use the default (un-seeded) generator?

**Comment by rcomer** [comment]
:woman_facepalming: now [updated](https://github.com/matplotlib/matplotlib/commit/a38be52c57b7adca3f877533c25f004a07991f3d), but the test still fails.

**Comment by QuLogic** [comment]
Yes, it appears that `default_rng` uses PCG64, while the older global functions use MT19937, though I'm not sure how to best replicate that with the objects.

**Comment by timhoffm** [comment]
My 2 cents: If this cannot be simply replaced, it's not worth the effort.

**Comment by rcomer** [comment]
I think the consensus here is that, because the new generator does not give the same numbers, we should not go forward with the replacement.

> @tacaswell 👎🏻 if this change requires any tests to be changed

> @timhoffm If this cannot be simply replaced, it's not worth the effort.

So I am going to close.  Obviously re-open if you disagree.

**Comment by WeatherGod** [comment]
It should be noted that numpy specifically chose *not* to deprecate the old
method because it would disrupt many unit tests across many projects that
simply needed a consistent sequence of pseudo-random numbers.
