### ISSUE TITLE
[Bug]: importing matplotlib removes --name argument from sys.argv

### ISSUE THREAD

**Issue by Solonets** [matplotlib/matplotlib#23236]
### Bug summary

importing matplotlib removes `--name` argument from sys.argv

### Code for reproduction

test.py:
```python

import sys
print (sys.argv)
import matplotlib.pyplot as plt
print (sys.argv)
```
```
python3 test.py --param1 1 --name 2 --param2 3
```

### Actual outcome

['test.py', '--param1', '1', '--name', '2', '--param2', '3']
['test.py', '--param1', '1', '--param2', '3']

### Expected outcome

['test.py', '--param1', '1', '--name', '2', '--param2', '3']
['test.py', '--param1', '1', '--name', '2', '--param2', '3']

### Operating system

Ubuntu

### Matplotlib Version

3.5.1

### Matplotlib Backend

GTK3Agg

### Python version

Python 3.8.10

### Installation

pip

**Comment by WeatherGod** [comment]
Yeah, I am not seeing any *.py file in our source tree that modifies
sys.argv. That means that chances are, it is being done by one of our
dependencies. This isn't going to be fun to track down...
