### ISSUE TITLE
How to turn off markers in stem plot [Doc]: 

### ISSUE THREAD

**Issue by alan-isaac** [matplotlib/matplotlib#23230]
### Documentation Link

https://matplotlib.org/devdocs/api/markers_api.html

### Problem

* `" "` or `""` are offered for nothing, but with a stem plot, these behave very differently. (The latter draws a connecting line to the marker points.) This is either a matter of missing documentation or a bug in `stem`.

### Suggested improvement

* Clarify the difference between the empty string and a single space (or if that is a bug in stem, fix that bug).
* The choice for "no marker" should have more prominence; it was hard to find. I recommend putting it at the top if possible.
* Markers are used by `stem` but this is not in the list at the top.

**Comment by oscargus** [comment]
Thanks for the report and suggestions!

`""` is clearly a bug. I do not really see anything strange with `" "`, but I may miss something?

I agree that a link to the markers should be there. Not sure that no marker should be at the top in that document (most would look for markers, not getting rid of it), but clearly worth mentioning in stem how to get rid of it.

Btw, it seems like there are more issues with `markerfmt`. Based on the documentation: 
> A string defining the color and/or shape of the marker

But just specifying the color will give a line, not the default marker with that color.

**Comment by alan-isaac** [comment]
Sorry to have been unclear: my point was only that `""` and `" "` seem to be documented as synonyms but in fact produce different behavior. If I understand you, that is because the behavior with `""` is buggy; they should in fact be synonyms. Then, that will be fine. Thanks!

**Comment by timhoffm** [comment]
This was fixed in #23233.
