### ISSUE TITLE
[Bug]: Wrong rendering of raw text, TeX style of \theta 

### ISSUE THREAD

**Issue by Sahuta** [matplotlib/matplotlib#23234]
### Bug summary

When I run following code, only "\theta" is rendered wrong, ignoring "\t".

### Code for reproduction

```python
plt.title(r"$\alpha="+str(alpha)+", k_3="+str(k3)+", k="+str(k)+", \theta = \cos\pi$")
```

### Actual outcome

\theta rendered as "heta", Both k_3 and \cos, neighbors of \theta are truly rendered.
![output](https://user-images.githubusercontent.com/26105150/172983431-3373b91e-6429-4e94-8b3e-b049ed9df321.png)

### Expected outcome

re-enclose \theta by r"$$", \theta will be rendered well.

```
plt.title(r"$\alpha="+str(alpha)+", k_3="+str(k3)+", k="+str(k)+", $"+r"$\theta = \cos"+str(2*m)+"\pi$")
```
![output2](https://user-images.githubusercontent.com/26105150/172983463-20f8d447-2374-4d81-929d-3d5ab786ddbe.png)

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.7

### Jupyter version

VScode extentions v2022.4.1021342353

### Installation

conda

**Comment by Sahuta** [comment]
I found that the of the issue was
```
Text(0.5, 1.0, '$\\alpha=0.1, k_3=25, k=0.1,\theta_0 = \\cos\\pi$')
```
.
\theta needs backslash

**Comment by jklymak** [comment]
\t is tab in ascii so you need to escape it somehow. This is expected behaviour.  Where would you expect This to be documented that you did not find?

**Comment by Sahuta** [comment]
I see, sorry for that
