### ISSUE TITLE
What does "Use Vendor the code instead" mean?

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#23244]
We started getting this deprecation warning but I don't know what to do with it. Is there somewhere in your documentation that would explain this more? Thanks! Example log: https://github.com/astropy/astropy/runs/6838665326?check_suite_focus=true

```
matplotlib._api.deprecation.MatplotlibDeprecationWarning: The checkdep_usetex function
was deprecated in Matplotlib 3.6 and will be removed two minor releases later.
Use Vendor the code instead.
```

We use it like this:

```python
 TEX_UNAVAILABLE = not matplotlib.checkdep_usetex(True)
```

Hard to tell from the traceback where this is coming from inside matplotlib because the warning went through a generic `matplotlib/_api/deprecation.py`.

**Comment by timhoffm** [comment]
Sorry for the confusion. The message is a bit awkward because it’s generated via a template. 

`checkdep_usetex` was not intended as public API and we are going to remove it. If you need the functionality you should  take a copy of the code and maintain it yourself.

**Comment by pllim** [comment]
That is unfortunate. Won't that promote code duplication, especially since you'll still be using it internally anyway? Anyways, my original question is answered, so I am closing the issue. Thanks!

**Comment by jklymak** [comment]
Downstream libraries (or anyone) are certainly welcome to use our private methods.  We simply don't guarantee their stability. If you want to avoid the warning just use the private method (but don't raise an issue if it breaks in the future).
