### ISSUE TITLE
[Bug]: pcolormesh with Gouraud shading artifact in ps output

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23252]
### Bug summary

There seems to be some artifact when exporting a pcolormesh with Gouraud shading as ps. This only happens with ps and not eps. At least when rendered with gsview.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

nrows = 3
ncols = 5
Z = np.arange((nrows + 1) * (ncols + 1)).reshape((nrows + 1), (ncols + 1))
x = np.arange(ncols + 1)
y = np.arange(nrows + 1)

fig, ax = plt.subplots()
ax.pcolormesh(x, y, Z, shading='gouraud', vmin=Z.min(), vmax=Z.max());
fig.savefig('gouraud.ps')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/8114497/173199594-21f9e089-467b-4f94-b3e1-24d3255ca815.png)

Screenshot from gsview

### Expected outcome

No white gap.

### Matplotlib Version

3.6.0.dev2700+gee7c4a079e.d20220611

### Installation

git checkout

**Comment by QuLogic** [comment]
I cannot reproduce this in `evince`, not in Ghostscript directly with `gs gouraud.ps`. I think `gsview` is quite outdated and maybe shouldn't be relied upon.

**Comment by oscargus** [comment]
I'll close this as it is probably rendered-dependent and it is likely a gsview issue (turns out I do not even longer have gsview installed...).
