### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Fernando961226** [matplotlib/matplotlib#23283]
### Bug summary

Saving a figure using the name 'CON' creates an error. 

### Code for reproduction

```python
import os
import numpy as np 
import matplotlib.pyplot as plt
import cv2 as cv
from PIL import Image




fwd =  'E:\\Documents\\My Work Space\\Work\\Graduate School\\Databases\\Sea Ice\\Test\\Artificial Images'

texture_folder_name = 'Feature'
slope_type = 'High'

img = cv.imread(os.path.join(fwd,slope_type+' Slope.jpg'))
img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)


plt.figure(figsize=(10,10))
plt.imshow(img,cmap='gray')
plt.xticks([])
plt.yticks([])
plt.savefig('CON')
plt.close()
```

### Actual outcome

Exception has occurred: UnsupportedOperation
File or stream is not seekable.
  File "E:\Documents\My Work Space\Work\Graduate School\Software\Python\Sea-Ice-texture-features\Artificial_Image.py", line 54, in texture_features
    plt.savefig('CON')
  File "E:\Documents\My Work Space\Work\Graduate School\Software\Python\Sea-Ice-texture-features\Artificial_Image.py", line 70, in <module>
    texture_features(fwd, texture_folder_name, data_name)

### Expected outcome

The expected outcome is to save the image

### Operating system

windows 10

### Matplotlib Version

  3.5.2     

### Python version

3.9.12

### Installation

pip

**Comment by QuLogic** [comment]
Windows does not support files named `CON`; there is nothing we can do about this.
