### ISSUE TITLE
[ENH]: add the opportunity to change the theta space to (-pi,pi) for polar plots

### ISSUE THREAD

**Issue by skoldobskiy** [matplotlib/matplotlib#23297]
### Problem

Hello!

I am trying to have a plot in polar coordinates for which the values in the interval ($\pi$; $2\pi$) will be negative, however, without success.

This is needed, in particular, for agreement with the galactic coordinate system used in astronomy which is typically given in (-$\pi$,$\pi$) range.
I did not find any possibility to change the axes system. I ask you to consider the opportunity to add this feature in the future releases.
Thanks!

![image](https://user-images.githubusercontent.com/64313360/174349808-63f42dd4-d12f-4810-b2e8-5eeefa05f0ad.png)

P.S. I am using the method of plotting described here: [https://stackoverflow.com/questions/36513312/polar-heatmaps-in-python](url)

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open.
