### ISSUE TITLE
Set_color method for line2d object in latest document not work 

### ISSUE THREAD

**Issue by skywateryang** [matplotlib/matplotlib#23296]
### Documentation Link

https://matplotlib.org/stable/gallery/pyplots/fig_axes_customize_simple.html#sphx-glr-gallery-pyplots-fig-axes-customize-simple-py

### Problem

In this link I provide, I found some part of the code in latest matplotlib version not work(3.5.x). This part works for 3.2.1, but not work now, while the latest document hasn't been changed.

Code as below, as you see, here set_color method for Line2D object not work actually, with the ticklines still being black rather green
`for line in ax1.yaxis.get_ticklines:    
    line.set_color('tab:green') `

### Suggested improvement

Change this line from ` line.set_color('tab:green')` to `line.set_markeredgecolor("tab:green")`

**Comment by tacaswell** [comment]
Interesting, bisecting via the docs confirms that 

https://matplotlib.org/3.2.2/gallery/pyplots/fig_axes_customize_simple.html#sphx-glr-gallery-pyplots-fig-axes-customize-simple-py is correct and https://matplotlib.org/3.3.0/gallery/pyplots/fig_axes_customize_simple.html#sphx-glr-gallery-pyplots-fig-axes-customize-simple-py is broken.

I am a bit curious the underlying change was that caused this, but it is been the new way (for what ever reason) long enough now going back to the old behavior could be more disruptive than just staying as we are.

@skywateryang If that changes makes the ticks render as green can you please open a PR with that change?

**Comment by skywateryang** [comment]
@tacaswell Thanks for reply.
I have tried create a PR as below. 
https://github.com/matplotlib/matplotlib/pull/23300
Since this is my first time to create PR, not sure whether I did it in a correct way. Let me know if there are any problems.
