### ISSUE TITLE
Make hist with 'step' histtype draw Line2D instead of Patch

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#233]
[Original report at SourceForge, opened Fri Feb 11 22:02:28 2011](https://sourceforge.net/tracker/?func=detail&aid=3178834&group_id=80706&atid=560722)

One of the annoying things about axes.hist is that with histtype='step' the automatic legend style is an empty box, instead of a line, as I would expect. This behaviour doesn't seem to make sense, because it seems a line would be much more appropriate for this case. Example code to demonstrate this:

import matplotlib.pyplot as plt
plt.hist([0,1,1,2,2,2], [0,1,2,3], histtype='step', label="histtype='step'")
plt.legend()
plt.show()

With the current uncustomisability of legend styles one can get around this by using proxy Line2D objects in building the legend, but this can be a common operation and becomes messy and annoying.

The cause of this is the fact that in axes.py::7799 (current SVN head), in axes.hist, patch objects are always created, even for the line-based step style. I searched the tracker, and couldn't find this mentioned before.

Attached is a patch that makes the very simple change of swapping out the call to .fill for .plot (only the function is changed here, not yet the documentation), and it appears to work but I haven't tested exhaustively.
- Is this intended behaviour, that I am just not understanding the requirement for?
- This will cause the return signature to possibly include Line2D's, instead of just patches. Will this break anything?

Thoughts?
### SourceForge History
- On Fri Feb 11 22:02:28 2011, by ndevenish: File Added: 401440: histtype_plot.patch

**Comment by tlatorre-uchicago** [comment]
Is there any example on how to make it plot with lines instead of empty boxes? The only reference I could find was https://stackoverflow.com/questions/19988556/how-to-use-alternative-legend-handler-for-histogram.

**Comment by andrzejnovak** [comment]
This is still bothering me in 2019.

**Comment by tlatorre-uchicago** [comment]
There is a working solution here: https://stackoverflow.com/questions/47490586/change-the-legend-format-of-python-histogram.
