### ISSUE TITLE
[Bug]: segfault while subplotting large dataframes

### ISSUE THREAD

**Issue by PaulZeroOne** [matplotlib/matplotlib#23304]
### Bug summary

I have tried most dataframe memory reduction techniques however, I get segfault whenever I'm trying to subplot multiple graphs. It works fine if I plot each graph individually.

### Code for reproduction

```python
for col in hrlogic.columns:
    plt.subplot(5,5,i)
    plt.plot(x,hrlogic[col],label=(f"R = %d"%hrlogic[col].astype(bool).sum()))
    plt.title(col)
    plt.legend()
```

### Actual outcome

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61397 entries, 0 to 61396
Data columns (total 16 columns):
 #   Column                                                                          Non-Null Count  Dtype   
---  ------                                                                          --------------  -----   
 0   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_ahb_config_armdma[1:0]  61397 non-null  category
 1   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_ahb_dma3_0[1:0]         61397 non-null  category
 2   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_ahb_dma3_1[1:0]         61397 non-null  category
 3   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_aton_s0[1:0]            61397 non-null  category
 4   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster1_cfg[1:0]  61397 non-null  category
 5   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster2_cfg[1:0]  61397 non-null  category
 6   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster3_cfg[1:0]  61397 non-null  category
 7   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster4_cfg[1:0]  61397 non-null  category
 8   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster5_cfg[1:0]  61397 non-null  category
 9   tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dimc_cluster6_cfg[1:0]  61397 non-null  category
 10  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dma3_0_config[1:0]      61397 non-null  category
 11  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dma3_1_config[1:0]      61397 non-null  category
 12  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dma_arm1[1:0]           61397 non-null  category
 13  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_dma_arm2[1:0]           61397 non-null  category
 14  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_m4_host_id[1:0]         61397 non-null  category
 15  tbench.u_mcu.chip_top.I_dimc_system_top.I_nic400.htrans_m4_host_sb[1:0]         61397 non-null  category
dtypes: category(16)
memory usage: 961.3 KB
None
/sw/freetools/python/3.7.2/rh70_64/modules/matplotlib/cbook/__init__.py:1402: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x[:, None]
/sw/freetools/python/3.7.2/rh70_64/modules/pandas/core/internals/blocks.py:1558: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  return self.values[slicer]
/sw/freetools/python/3.7.2/rh70_64/modules/pandas/core/series.py:1032: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  return np.asarray(self._values[indexer])
/sw/freetools/python/3.7.2/rh70_64/modules/matplotlib/axes/_base.py:276: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x = x[:, np.newaxis]
/sw/freetools/python/3.7.2/rh70_64/modules/matplotlib/axes/_base.py:278: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  y = y[:, np.newaxis]
NIC_new.py:201: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(5,5,i)
NIC_new.py:211: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(5,5,i)
NIC_new.py:221: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(5,5,i)
NIC_new.py:231: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(5,5,i)
/sw/freetools/python/3.7.2/rh70_64/lib/python3.7/tkinter/__init__.py:1705: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  return self.func(*args)
Segmentation fault

### Expected outcome

should plot a graph.

### Matplotlib Version

3.1.1

### Python version

3.7.2

### Installation

Linux package manager

**Comment by jklymak** [comment]
We can't really help if we don't know what is in hrlogic or x.   You may also want to not use tkagg and try agg and just print to a file to see if that works.

**Comment by tacaswell** [comment]
Can you make a random dataframe this is big enough to generate this problem?

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open if you make an example.
