### ISSUE TITLE
[Bug]: Wrong fontsize of SVG picture when displaying on PPT

### ISSUE THREAD

**Issue by gouwei1** [matplotlib/matplotlib#23305]
### Bug summary

Hi,

I want to output svg format to display on office PowerPoint, while the fontsize is wrong after adding the code: plt.rcParams['svg.fonttype'] = 'none', otherwise the word are separated as single letters after ungrouping. Is that a bug?

Best,
Wei

### Code for reproduction

```python
label=['1','2','3']
value=[1000,2000,3000]
x_label='Species'
y_label='Count'
fontsize_=20


from matplotlib import pyplot as plt
fig, ax = plt.subplots()
p1=ax.bar(label, value,alpha=0.5)
plt.rcParams['svg.fonttype'] = 'none'
plt.xlabel(x_label,fontsize=fontsize_)
plt.ylabel(y_label,fontsize=fontsize_)
plt.xticks(fontsize=fontsize_) 
plt.yticks(fontsize=fontsize_) 
plt.tight_layout()
plt.show()
```

### Actual outcome

The fontsize is smaller when in PPT.

### Expected outcome

The fontsize should be consistent with the setting.

### Matplotlib Version

3.5.2

**Comment by jklymak** [comment]
I can't reproduce this using Chrome as the viewer.  Did you try other svg viewers beyond Powerpoint?

**Comment by timhoffm** [comment]
The simpler example
```
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
plt.supfigure('Some text', fontsize=20)
plt.savefig('test.svg')
```
yields

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="460.8pt" height="345.6pt" viewBox="0 0 460.8 345.6" xmlns="http://www.w3.org/2000/svg" version="1.1">
 <metadata>
 [...]
 </metadata>
 <defs>
  <style type="text/css">*{stroke-linejoin: round; stroke-linecap: butt}</style>
 </defs>
 <g id="figure_1">
  <g id="patch_1">
   <path d="M 0 345.6 
L 460.8 345.6 
L 460.8 0 
L 0 0 
z
" style="fill: #ffffff"/>
  </g>
  <g id="text_1">
   <text style="font: 20px 'sans-serif'; text-anchor: middle" x="230.4" y="22.108875" transform="rotate(-0, 230.4, 22.108875)">Some text</text>
  </g>
 </g>
</svg>
```

Which seems correct.

The rendering:
![grafik](https://user-images.githubusercontent.com/2836374/174658277-707fd192-013f-486f-b131-77b8a10320b8.png)

- SVG text in Chrome and PowerPoint text elements have the same size
- SVG text in powerpoint is smaller

From this I conclude that PowerPoint does not render the SVG correctly.

**Comment by timhoffm** [comment]
Also note

```
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
plt.subplots()
plt.title('Some text', fontsize=30)  # much larger font
plt.savefig('test.svg')
```

![grafik](https://user-images.githubusercontent.com/2836374/174659321-34a3e95a-7c49-4c4f-8c4b-ece3d6547670.png)

So PowerPoint does not seem to handle fontsize in SVG at all.

**Comment by gouwei1** [comment]
Hi,

Thanks for your detailed reply. I also found when SVG was imported in Adobe illustrator, then output still as svg, the fontsize can be larger in PPT. But inkscape can not do that, so I can not use command line to handle it using inkscape. Does AI support command line? (It does not seem to support that) 

Best,
Wei

**Comment by pank** [comment]
For what it is worth, the "problem" seems to be that Word does not parse the `font` property (maybe because it's only a css property and not an SVG presentation attribute?). Wouldn't it in any case be easier to to use the presentation attributes (`font-size`, `font-weight`, `font-style`, ...). 

The following screenshot shows the output of this code and one where I have replaced the `font` with the presentation properties.

``` python
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
plt.suptitle('Some text', fontsize=20, weight="bold")
plt.savefig('test.svg')
```

![image](https://github.com/matplotlib/matplotlib/assets/666845/ea42de08-3e0d-4f9b-9496-3fb321200859)
