### ISSUE TITLE
[ENH]: Figure to image bytes

### ISSUE THREAD

**Issue by xk4rimx** [matplotlib/matplotlib#23319]
### Problem

It'd be nice to add an internal method that transforms the current figure into image bytes without having to save it to disk.
Maybe like a `.to_image()` method.

### Proposed solution

I've found a workaround, but I'm not too sure about it to open a PR:

```python
import io
import numpy as np
import matplotlib.pyplot as plt

y = [np.sin(x) for x in range(10)]
plt.plot(y)

with io.BytesIO() as buffer:  # use buffer memory
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image = buffer.getvalue()
```

**Comment by jklymak** [comment]
You can do that, or draw to the renderer and grab tha.  See https://stackoverflow.com/questions/35355930/matplotlib-figure-to-image-as-a-numpy-array

I don't think we need to add an API for this, but maybe others will disagree.
