### ISSUE TITLE
[Bug]: Event loop issue with Macosx backend

### ISSUE THREAD

**Issue by charwick** [matplotlib/matplotlib#23327]
### Bug summary

The Macosx backend won't show a window until all the processing is completed, even when calling `plt.show()` beforehand. For a continuously updating figure, this means that it will just hang forever without displaying anything. I can do this fine in Tkagg, but I'd like to be able to display retina-quality images.

### Code for reproduction

```python
import matplotlib, random
import matplotlib.pyplot as plt

matplotlib.use('macosx') #Works fine with tkagg
data = []

#Initial Draw
fig, axes = plt.subplots(1)
line, = axes.plot(data, label='Some data', color='#CC0000')
fig.canvas.draw_idle()
plt.show(block=False)

while True:
	data += [random.randint(0,50) for i in range(20)]

	tseries = range(0, len(data))
	line.set_ydata(data)
	line.set_xdata(tseries)
	axes.relim()
	axes.autoscale_view(tight=False)

	if fig.stale: fig.canvas.draw()
	fig.canvas.flush_events() #Listen for user input
```

### Actual outcome

Python hangs forever, waiting for the `while` loop to complete.

### Expected outcome

As with Tkagg, it should launch the window first and continuously update the plot.

### Operating system

Mac OS 10.15

### Matplotlib Version

3.5.2

### Matplotlib Backend

MACOSX

### Python version

3.10.5

### Installation

pip

**Comment by greglucas** [comment]
This works much better on main than 3.5, showing the constantly updating figure as expected. However, the user-input part still doesn't work quite right. I can't click on the pan/zoom tool and interrupt the updates like tk/qt event loops. There is still something missing from the flush_events on macosx I think. In fact, the window has the close/minimize buttons grayed out during the updates, so it doesn't want to respond to user input at all...
