### ISSUE TITLE
[Bug]: `plt.autoscale()` failes for partial `Arc`

### ISSUE THREAD

**Issue by StFroese** [matplotlib/matplotlib#23329]
### Bug summary

Using `plt.autoscale()` for an `Arc` with `theta1` & `theta2` for a not full ellipse results in a wrong scaling.

For example:
```
Arc((0,0),1,1,theta1=0,theta2=90)
```

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Arc

fig, ax = plt.subplots()
ax.add_patch(Arc((0,0),1,1,theta1=0,theta2=90))

plt.autoscale()
plt.show()
```

### Actual outcome

![Figure](https://user-images.githubusercontent.com/44728015/175262940-24616216-0e4e-40f1-aec8-4299022cc58a.png)

### Expected outcome

I think it would be better to have a zoomed in version of the partial arc. Like this:

![FigureC](https://user-images.githubusercontent.com/44728015/175263312-871baf0e-1457-4082-8440-320af90f1d3e.png)

### Matplotlib Version

3.5.2

**Comment by oscargus** [comment]
The reason is that the path that is stored is for a complete Ellipse and that the angles are not taken into account until draw time.  As the bounding box is determined from the saved path this is what happens...

This can be seen be e.g. 
```
from matplotlib.patches import Arc
a = Arc((0,0),1,1,theta1=0,theta2=90)
print(a.get_path())
print(a.get_extents())
```
A solution to this is probably to define a better `get_path`-method for `Arc`.

**Comment by oscargus** [comment]
This is vaguely related (solving this may solve that): https://github.com/matplotlib/matplotlib/issues/19550

Also this can be worth considering: https://github.com/matplotlib/matplotlib/issues/11266

**Comment by StFroese** [comment]
@oscargus Thanks a lot!
