### ISSUE TITLE
[Doc]: gallery example "Discrete distribution as horizontal bar chart" doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#23345]
### Documentation Link

https://matplotlib.org/stable/gallery/lines_bars_and_markers/horizontal_barchart_distribution.html

### Problem

```
Traceback (most recent call last):
  File "matplotlib_horiz_bar_chart.py", line 53, in <module>
    survey(results, category_names)
  File "matplotlib_horiz_bar_chart.py", line 30, in survey
    category_colors = plt.colormaps['RdYlGn'](
TypeError: 'function' object is not subscriptable

```

**Comment by keithbriggs** [comment]
After fixing the cmap problem, there is another issue:

```
Traceback (most recent call last):
  File "matplotlib_horiz_bar_chart.py", line 54, in <module>
    survey(results, category_names)
  File "matplotlib_horiz_bar_chart.py", line 48, in survey
    ax.bar_label(rects, label_type='center', color=text_color)
AttributeError: 'AxesSubplot' object has no attribute 'bar_label'
```

**Comment by jklymak** [comment]
You are using an older version of Matplotlib.  Please use the pull down menu and choose the docs that are appropriate for your version.  Also next time please include all information requested in the issue template.  🙏

**Comment by jklymak** [comment]
Ooops, apologies, that pull down does not exist yet ;-). However, you can manually choose your version by editing the address and replacing "stable" with "3.1.1" or whatever version you are on.
