### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by K20shores** [matplotlib/matplotlib#23343]
### Bug summary

When there are too many hourly data points with a date-time axis, formatting the date-time tick labels to show only one for the beginning in the month results in far too many tick labels and tick labels showing the wrong year.

### Code for reproduction

```python
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

times=pd.date_range(start='2021-01-01', end='2021-12-31', freq='1h')
adf = pd.DataFrame({
    'time': times,
    'A': np.random.rand(times.shape[0]),
    'B': np.random.rand(times.shape[0]) * 100
})

# uncomment to produce second image
#for col in adf.columns:
#     adf.loc[adf.sample(frac=0.7).index, col] = np.nan
adf.set_index('time', inplace=True)

fig, ax = plt.subplots(dpi=300)

ax2 = ax.twinx()

a = adf.plot(y='A', ax=ax, color='blue', alpha=0.3, legend=False)
b = adf.plot(y='B', ax=ax2, color='red', alpha=0.3, legend=False)

ax.legend([
    a.get_lines()[0],
    b.get_lines()[0]
], ['A', 'B'])

ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d-%y'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
ax.tick_params(axis='x', rotation=30)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/13836216/175664242-26314190-e73d-4cc5-be80-6bc21020e591.png)

### Expected outcome

The image below was produced by dropping much of the data. See the commented out code in the snippet above. Uncomment those two lines to produce this image. In this second image, the tick labels are only at the beginning of the month and there are only 13 of them, not the seemingly hundreds from the first image.

![image](https://user-images.githubusercontent.com/13836216/175664257-8fc5a032-73a4-4708-85c3-e5118eac5a06.png)

### Operating system

macOS Monterey 12.3.1

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.4

### Jupyter version

6.4.11

### Installation

conda

**Comment by jklymak** [comment]
Can you reproduce this issue without importing pandas?  Thanks!

**Comment by tacaswell** [comment]
I am relatively sure the issue is that when Pandas detects you have a time index it install it's own locator and formatters that have a different notion of the epoch and timescale than our unit system (and locactors/formatters) have.

**Comment by K20shores** [comment]
Ah, it was pandas.

The below code works. Not a matplotlib bug. Thanks
```
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(dpi=300)

ax2 = ax.twinx()

ax.plot(times, np.random.rand(times.shape[0]), color='blue', alpha=0.3)
ax2.plot(times, np.random.rand(times.shape[0]) * 100, color='red', alpha=0.3)
              
ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d-%y'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
ax.tick_params(axis='x', rotation=30)
```

**Comment by jklymak** [comment]
Is there a linked pandas issue?  I wouldn't mind trying to work with them so this doesn't happen any more.

**Comment by K20shores** [comment]
I did not make one. I can if you'd really like to work on this.

**Comment by tacaswell** [comment]
> I did not make one. I can if you'd really like to work on this.

This has come up before (which is why we had guesses as to the problem ;) ).  We would like this tracked on the Pandas side so they can fix it and so we have an issue to point to the next time this gets reported to us.
