### ISSUE TITLE
[Bug]: subplots_mosaic shared axes does not work as expected(?)

### ISSUE THREAD

**Issue by kratsg** [matplotlib/matplotlib#23356]
### Bug summary

After remembering a very nice [tweet](https://twitter.com/matplotlib/status/1382083838818594816) from matplotlib's twitter account about `subplots_mosaic`, I decided to try it and use the quoted

> Totally, they're full Axes objects! axd['A']. share {x,y}(axd['B'])

functionality.

### Code for reproduction

```python
fig = plt.figure()
ax = fig.subplot_mosaic("""AB
CD""")
ax['A'].sharex(ax['C'])
ax['A'].sharey(ax['B'])
```

### Actual outcome

![Screen Shot 2022-06-27 at 9 03 36 PM](https://user-images.githubusercontent.com/761483/176093474-94098e1e-d51a-4999-b40a-bb44b9dd186a.png)

### Expected outcome

I expected something more like

```python
fig, ax = plt.subplots(2,2, sharex=True, sharey=True)
```

![Screen Shot 2022-06-27 at 9 08 24 PM](https://user-images.githubusercontent.com/761483/176093501-d1144a7b-0818-4eb0-8bcd-5779adb6f9a2.png)

where the tick labels are shifted towards the outer edges.

### Operating system

macOS 10.13.6

### Matplotlib Version

3.5.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.9.13

### Jupyter version

6.4.12

### Installation

pip

**Comment by jklymak** [comment]
Thats not how post-facto sharing works.  However, subplots_mosaic takes sharex and sharey arguments.

**Comment by story645** [comment]
> Thats not how post-facto sharing works.  

would it be possible to make post-facto sharing work that way or too much work since it'd require checking where the axes are in the grid? (Like it only makes sense to turn off ticks when the axes are adjacent)

**Comment by jklymak** [comment]
Anything is possible, but you'd have to do it so that it didn't break previous behaviour.  But currently sharing an axes doesn't mean stripping redundant tick labels - it means locking the x or y limits to each other.

**Comment by kratsg** [comment]
> Anything is possible, but you'd have to do it so that it didn't break previous behaviour. But currently sharing an axes doesn't mean stripping redundant tick labels - it means locking the x or y limits to each other.

Oh, I didn't realize that was the actual behavior. I'm used to what the `sharex` / `sharey` does which had always (from what I recall) stripped the redundant tick labels. Is there a way to get that behavior with subplots_mosaic? Or do i need to manually turn off tick labels for each axis I care about?

**Comment by jklymak** [comment]
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot_mosaic.html takes `sharex` and `sharey` kwargs.
