### ISSUE TITLE
[Doc]: bar examples should probably not have "score by ... gender" in them...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#23352]
### Documentation Link

https://matplotlib.org/devdocs/gallery/index

### Problem

Our very first examples have "scores by gender" in them.  I don't think this adds anything to the examples and is easy to make more generic.

**Comment by Shubham-100** [comment]
Hey @jklymak, I am a newcomer, I would like to take this up. Do you want "scores by gender" to be removed or...?

**Comment by jklymak** [comment]
Yes, come up with some other binary identifier that ideally is not related to intrinsic human characteristics, and recast the examples.  Bonus points if its something obvious, intuitive, and fun....

**Comment by jklymak** [comment]
I would also highlight this one as needlessly political: https://matplotlib.org/devdocs/gallery/showcase/bachelors_degrees_by_gender.html, though that would take some more research to find nice time series...

**Comment by mwaskom** [comment]
> I would also highlight this one as needlessly political: https://matplotlib.org/devdocs/gallery/showcase/bachelors_degrees_by_gender.html

I've always thought this was a funny one — [when this dataset came out](https://www.npr.org/sections/money/2014/10/21/357629765/when-women-stopped-coding) it was interesting for showing that growth in CS was on trend up to the early 80s before suddenly reversing as an outlier. But in the matplotlib example, CS is drawn in a light gray and very easy to miss. Redrawing the example like in the NPR article (showing fewer majors and *emphasizing* CS) would be a more interesting example ... though also political I suppose.

**Comment by story645** [comment]
> though also political I suppose.

I like this example cause I'm a data point (CS or engineering depending on how they coded), which is why I find calling it political a bit  I dunno depressing. The example  should  probably be updated to include more recent data, and possibly contextualized w/ the numbers for men and folks of other genders (if that data is available) but I dunno if it's inherently controversial. (I really don't think it's saying anything that's out of line w/ Matplotlib values).

**Comment by jklymak** [comment]
I think the _examples_ should show folks how to use matplotlib and maybe tentatively wade into the controversial subject of how to effectively and pleasingly portray data.  Any other commentary should be put somewhere else.

**Comment by SourajitaDewasi** [comment]
Hi @jklymak 
I am a beginner and I wanted to contribute to open source specifically to Matplotlib I use daily in my data analysis projects. I think an example that is not political or not controversial could be five groups: G1, G2, G3, G4, G5 and if they like tea or coffee. 

Or five age groups and if they are comfortable with in-person communication or online communication.

**Comment by scottshambaugh** [comment]
Here's a list of the specific examples which are affected:

- https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/bar_label_demo.html#sphx-glr-gallery-lines-bars-and-markers-bar-label-demo-py
- https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/bar_stacked.html
- https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/barchart.html#sphx-glr-gallery-lines-bars-and-markers-barchart-py
- https://matplotlib.org/devdocs/gallery/units/bar_unit_demo.html#sphx-glr-gallery-units-bar-unit-demo-py

**Comment by SourajitaDewasi** [comment]
With the following code I was able to obtain this result. I am inserting both the images below. This is just for the bar_label_demo example. Can you please guide me how to move from here?
![Stacked Bar Graph Demo Code](https://user-images.githubusercontent.com/89794866/180635286-278da655-7369-45be-8539-153cc56f6a07.jpg)
![Stacked Bar Graph](https://user-images.githubusercontent.com/89794866/180635288-85247fc9-2658-4c0e-810c-ea66cbd5a4e3.jpg)

Thanks in advance!

**Comment by jklymak** [comment]
This seems fine, though who knows how controversial Tea/Coffee will be ;-)

https://matplotlib.org/stable/devel/index.html describes how to make pull requests...

**Comment by SourajitaDewasi** [comment]
Thank you @jklymak . I will complete this as soon as possible!

**Comment by QuLogic** [comment]
Seems like it.
