### ISSUE TITLE
[Bug]: ICE default IO error handler doing an exit

### ISSUE THREAD

**Issue by brobr** [matplotlib/matplotlib#23369]
### Bug summary

With a large figure, python 3.9  crashes with `ICE default IO error handler doing an exit(), pid = <python3>, errno = 32`.

I get this error when building a very large figure with about 110 axes from a dataframe of 166.6 KB (110 columns; 192 rows, mostly 0-values). 

With `plt.show()`  a window frame gets created but stays blank/transparant and eventually python cops out with the IO error (most of the time).

With `plt.savefig`, to a svg file, the error still pops up, but after the file gets generated (11.8 Mb; see a derived png attached). I can see the file filling up to completion before the program ends with the error.

With or without `plt.close()` following `plt.savefig` or `plot.show()` the error occurs.

![figure_1](https://user-images.githubusercontent.com/3693709/176485746-aec14903-4ccc-49b9-8bd2-4c04a4b98b33.png)

1 cpu core out of 8 (12.5% ) is used and ~ 3.8% out of 32 GB available memory.

When building from a smaller data set (23 columns) the error does not pop up and the figure gets displayed and can be saved from the gui. (12.5% cpu; 1.5% memory used)

### Code for reproduction

```python
Too complex, sorry, and cannot quickly come up with something that emulates it. Maybe it's my coding (but the figure gets made, see the savefig-output).
```

### Actual outcome

See above description.

### Expected outcome

Expected to see the figure and save it from the gui-window it gets displayed in.

### Additional information

The problem is with the number of axes, in case of the error, these have to be put in one by one; when there are less axes there is no problem.

Depending on how the data is grouped, a gridspec gets defined with cells giving space for one data-column. 

In the case of the error, each data-column describes a distribution of how many fragments of a particular length are found in a sample. To display this, each gridspec-cell gets filled with an axis showing the bardiagram of the distribution (~192 values per data-column).  

When only total numbers of these fragments (i.e. one value per data-column) need to be shown, a whole group of samples can be displayed in one axis, still with one grid-cell for each column.  This is done with the same set of classes/functions: 

![Screenshot_2022-06-29_18-22-49](https://user-images.githubusercontent.com/3693709/176497701-07ce2e3d-d211-4a47-b863-c2fb25165d33.png)

I've googled on the IO error but did not get any further than some 2011 posts on the issue tracker here.

Is there something I can do/try at my end to analyze this better or find a solution?

### Operating system

Slackware64-15.0+ (current)

### Matplotlib Version

Matplotlib-3.5.2

### Matplotlib Backend

QtAgg

### Python version

Python 3.9.13

### Jupyter version

not relevant

### Installation

from source (.tar.gz)

**Comment by timhoffm** [comment]
Trying to narrow this down without a reproducible example:

> With or without `plt.close()` following `plt.savefig` or `plot.show()` the error occurs.

Which command exactly produces the error?

Does it also happen if you create an empty figure of that size (a) only the figure without subplots (b) including the subplots but no data?

**Comment by jklymak** [comment]
Please make a reproducible example with random data, and with only numpy and Matplotlib as imports, otherwise we cannot track down what the problem is.

**Comment by brobr** [comment]
Hi,
It took me some time to get something together and it seems to be linked to seaborn. 

When I do not involve seaborn to plot the bars (but plot directly from the dataframe) the test does not end in a crash.
[testCrash.py.txt](https://github.com/matplotlib/matplotlib/files/9020965/testCrash.py.txt)

Also in my program, bypassing all things seaborn seems to prevent the crash (the created svg file is much smaller in size).
This is still not really a solution as the program uses a lot of seaborn styling. Somehow it still seems to do with memory or something. When it crashes memory-usage is near 3.5% when it ends normally it is below 2.8% (of 32GB)

At my end, the first program run sometimes work; then the crashes happen on subsequent runs.

datafile:
[crash1.txt](https://github.com/matplotlib/matplotlib/files/9020748/crash1.txt)

**Comment by brobr** [comment]
Did you get the crash when the seaborn command `ax=sns.barplot()` in the function `def broken_lengths(self, sample, ax)` is active?

> bash-5.1$ perror 32
OS error code  32:  Broken pipe

When running the program the crash happens when using each of these (with plotting from the dataframe by `dfs.plot()` ) 
>  #sns.set_style(GRIDSTYLE)
    #sns.plotting_context(CONTEXT) #"notebook", font_scale=1.5)
    #sns.set_palette(PALETTE)

or when setting a context in matplotlib via `@mpl.rc_context(get_context())` as decorator for the function calling the plot.

Each of the lines below setting a grid value are causing the error... in each case memory usage hits 3% or over.

>def get_context(font_size = CSFONTSZ):
    """Returns common values for matplotlib rc parameters"""
    return {
           # 'backend': 'Qt5Agg',
            'font.size': font_size, #CSFONTSZ, # 12
           # 'grid.alpha': GRIDALPHA,
           # 'grid.color': GRIDCOLOR,
           # 'axes.grid.axis': GRIDAXIS,
           # 'axes.grid.which': GRIDWHICH,
           # 'axes.grid': GRID,
            'font.family': SNSFNTFAM,
            'figure.facecolor' : FIGCOL,
            'savefig.format': FIGFORMAT,
            'savefig.directory': FIGDIR,
            }

It doesn't happen though when all this extra stuff is included in the testCrash.py; there it only goes wrong with `ax=sns.barplot()`; with  `dfs.plot()` instead it completes (plus getting beyond 3% memory usage; so that seems not as relevant). Will try to rebuild seaborn...
            ax=ax,

**Comment by tacaswell** [comment]
https://stackoverflow.com/questions/39270988/ice-default-io-error-handler-doing-an-exit-pid-errno-32-when-running looks related. 

If you do not need the UI window, try setting `matplotlib.use('svg')` (as it seems you are saving svgs?). 

----

It looks like the issue is coming from http://www.xfree86.org/4.5.0/ice.pdf (Inter-Client Exchange Protocol).  We are definitely not directly using this, but Qt maybe.  This seems to be a not-uncommon problem, but all of the posts about this seem to resolve in "I deleted some config and now it works!" which is not very satisfying.

My _guess_ is that this is an interaction between the Qt application and your desktop manager.   As others have said, without a copy-pastable example we can not really help debug this but I fear than even if you find a simple example that reliably crashes for you, it may depend on the details of which versions of Qt / PyQt / window manager than slackware is providing.

**Comment by brobr** [comment]
@tacaswell: Yes I saw that post; thought it seemed quite old and the qt5 backend is newer than what was found to work (qt4agg). On my Slackware box there is PyQt5-5.15.2 and qt5-5.15.4_20220611. Saving directly to svg could be a work around for large files. Still it seems odd. Can seaborn interfere with changing matplotlib rc.parameters?

Ha, you're right about the ICE/QT combo, setting the backend to TkAgg lets the test file complete with `ax=sns.barplot()` (instead of `dfs.plot()`) and also the main program completes without the error!

I'll try dumping .ICEAuthority next and see what happens when using the Qt5Agg again.

**Comment by brobr** [comment]
Ok, removing the .ICEAuthority file before a reboot (resulting in a 0 kb file on re-login) did not prevent the error when the default backend ('QtAgg') is used. Need to stick to TkAgg when this error occurs...
