### ISSUE TITLE
[MNT]: pcolormesh interactive plot lower performance (big difference) for 3.5.1 vs 3.2.2

### ISSUE THREAD

**Issue by Jrcarand** [matplotlib/matplotlib#23367]
### Summary

I am not sure if this is the right place to submit this, if here or bug report.
My data is (8560,1024) of float 64 (~70MB). But I routinely plot datasets >600MB and never encountered this issue.
After updating my system yesterday I noticed an extreme drop in performance while interacting with pcolormesh (resizing window, zoom to rectangle, coordinate display) for the above dataset. The window keeps freezing and taking a really long time to perform things. I do not know which version I had before except that I had python 3.8.X and that matplotlib was from somewhere between Nov. 2020 and Sep. 2021. To narrow things down I tried two different environments, and performance is like before (no hiccups) after rolling matplotlib's version back to 3.2.2. I did not try to see which version started to lag considerably. I list the packages I think are the most relevant for the two environments.

Use cases, "up-to-date" environment, bad performance in interactive pcolormesh:
python: 3.9.12
matplotlib: 3.5.1
qt5: 5.9.7
pyqt: 5.9.2
numpy: 1.22.3

Older version, good performance:
python: 3.8.13
matplotlib: 3.2.2
qt5: 5.9.7
pyqt: 5.9.2
numpy: 1.22.3

On my very limited knowledge of this kind of things, its either python or matplotlib.

**Comment by greglucas** [comment]
This is a known issue and it should be fixed in 3.5.2, please upgrade to the latest version.
xref: https://github.com/matplotlib/matplotlib/issues/23164

**Comment by jklymak** [comment]
also https://github.com/matplotlib/matplotlib/issues/21917
