### ISSUE TITLE
[Bug]: markerfacecoloralt not supported when drawing errorbars

### ISSUE THREAD

**Issue by wqian94** [matplotlib/matplotlib#23375]
### Bug summary

Although the documentation says that all Line2D `kwargs` should be supported, only a small handful actually are:

https://github.com/matplotlib/matplotlib/blob/4f5cacfde9024076d9ab0cb6ad1c9a7cf352d5f9/lib/matplotlib/axes/_axes.py#L3393

`markerfacecoloralt` is not among that list.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

# example data
x = np.arange(0.1, 4, 0.5)
y = np.exp(-x)

# example error bar values that vary with x-position
error = 0.1 + 0.2 * x

fig, ax = plt.subplots(1, 1)
ax.errorbar(x, y, yerr=error, fmt='-o', markerfacecoloralt='white')
ax.set_title('variable, symmetric error')
```

### Actual outcome

`AttributeError: 'LineCollection' object has no property 'markerfacecoloralt'`

### Expected outcome

No error

### Additional information

`markerfacecoloralt` needs to be added to this list: https://github.com/matplotlib/matplotlib/blob/4f5cacfde9024076d9ab0cb6ad1c9a7cf352d5f9/lib/matplotlib/axes/_axes.py#L3393

Better yet, automagically check against the signature of `Line2D`.

### Operating system

Ubuntu 20.04.4

### Matplotlib Version

3.5.2

### Matplotlib Backend

QtAgg

### Python version

3.8.10

### Installation

pip

**Comment by oscargus** [comment]
Solved by #23475
