### ISSUE TITLE
[Bug]: Newer versions of matplotlib ignore xlabel on colorbar axis

### ISSUE THREAD

**Issue by bbuzz31** [matplotlib/matplotlib#23398]
### Bug summary

xlabel on colorbar no longer shows up. 
See bottom of colorbar in the attached plots.

Works in matplotlib v3.4.3.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

arr       = np.random.rand(10, 10)

fig, axes = plt.subplots()
im        = axes.imshow(arr)

divider = make_axes_locatable(axes)
cbar_ax = divider.append_axes('right', size='5%', pad=0.5)
cbar    = plt.colorbar(im, cax=cbar_ax)


cbar_ax.set_xlabel('Xlabel') # no longer works
cbar.set_label('YLabel')

plt.show()
```

### Actual outcome

![MWE_new_wrong](https://user-images.githubusercontent.com/15522503/177852838-7ccecc30-5bfc-4581-9e87-f482de81b5af.png)

### Expected outcome

![MWE_old_right](https://user-images.githubusercontent.com/15522503/177852859-9b51b3c0-1824-4937-9474-b3edfba852f1.png)

### Matplotlib Version

3.5.2

**Comment by oscargus** [comment]
It seems like it is set, but not rendered.

```
<Axes:xlabel='Xlabel', ylabel='YLabel'>
```

**Comment by jklymak** [comment]
I think this is pretty easy as it is a straight bug and there are no API decisions.  Just replace the `set_visible(False)` with whatever incantation makes the ticks and labels go away on the short axis. And add a test, probably an image test.

**Comment by timhoffm** [comment]
No. You are welcome to pick this up if you like.

**Comment by tacaswell** [comment]
@WarrenWeckesser It would have never even occurred to me to try that, but that is super clever!

We should only set things to invisible on init so they can be re-enabled if needed.

We will also need to add public API to access the short axis so I think this is a 3.6 feature.

**Comment by QuLogic** [comment]
I think that exposing the short/long Axis (for which there are already private methods) is a separate issue to restoring the `xlabel` by default, which can be done following @jklymak's advice here: https://github.com/matplotlib/matplotlib/issues/23398#issuecomment-1178607153
