### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AndrewWilliams3142** [matplotlib/matplotlib#23396]
### Bug summary

Unexpected colorbar behaviour with `TwoSlopeNorm`.  Colorbar "aspect ratio" varies either side of the zero line

### Code for reproduction

```python
divnorm=colors.TwoSlopeNorm(vmin=-4., vcenter=0., vmax=2)
d = np.random.normal(.4,2,(10,10))
plt.imshow(d,cmap=plt.cm.RdBu,norm=divnorm)
plt.colorbar()
plt.show()
```

### Actual outcome

Actual outcome
![image](https://user-images.githubusercontent.com/56925856/177789650-aa8fec6d-bb5c-41df-b577-4d450a0a3612.png)

### Expected outcome

Expected outcome (running the same code but on v 3.3.3 instead of v3.5.2)
![image](https://user-images.githubusercontent.com/56925856/177789779-003b069e-c1bb-4652-b520-3f2ef739abbc.png)

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.9

### Jupyter version

3.4.2

### Installation

conda

**Comment by jklymak** [comment]
As of 3.5.0 this is expected behaviour, and discussed here: #22197. If you want the linear scale `cb.ax.set_yscale('linear')` will give that to you.
