### ISSUE TITLE
[Doc]: SpanSelector example only a static image

### ISSUE THREAD

**Issue by albertlarson** [matplotlib/matplotlib#23395]
### Documentation Link

https://matplotlib.org/devdocs/gallery/widgets/span_selector.html

### Problem

I've noticed this in a couple instances, but was requested via twitter to report this one. I think a visitor would expect the spanselector example to be a dynamic, working version. When I go to the stable or dev link, it appears as a static image.

### Suggested improvement

A working example would be helpful for users to know how spanselector actually works. This seems like a great feature that folks might like to embed in their websites.

**Comment by albertlarson** [comment]
I'll give it a try when I have a few moments. I expect the example will
work.

Would be neat to see something like this implemented for the gallery:
https://mpld3.github.io/index.html

On Thu, Jul 7, 2022 at 10:43 AM hannah ***@***.***> wrote:

> 😶 I'm the one who suggested you open the bug report, but this isn't
> really a bug. Unfortunately the way our gallery works, we currently can't
> embed interactive examples. If you run the example locally, does it work?
>
> #19222
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matplotlib_matplotlib_issues_19222&d=DwMFaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=OXDwawBS6GXlFfXqFbWbjA&m=GmIf6gsm-Chp1RGCJ4mop4GFSQFau3MCpQSerU_cfKYFmetGGnVcTyTOvT4GVakz&s=68sM-MsNPw7ugS7ogp6TtW99uhyjVWlaku_g0rJTU7k&e=>
> has a discussion on adding gifs, would that maybe work?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matplotlib_matplotlib_issues_23395-23issuecomment-2D1177725913&d=DwMFaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=OXDwawBS6GXlFfXqFbWbjA&m=GmIf6gsm-Chp1RGCJ4mop4GFSQFau3MCpQSerU_cfKYFmetGGnVcTyTOvT4GVakz&s=Rw4BB4vGg8OXFFCZx-hqh9CJeHwrusWBZlAuhBo6ZIU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOXB42GG4CSLLPW66KOFT4DVS3UHFANCNFSM525PL4ZA&d=DwMFaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=OXDwawBS6GXlFfXqFbWbjA&m=GmIf6gsm-Chp1RGCJ4mop4GFSQFau3MCpQSerU_cfKYFmetGGnVcTyTOvT4GVakz&s=SuUezxmiyTarTzEdpaFSs2woDClwW1s2hAO75tpn7oE&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Albe

**Comment by albertlarson** [comment]
Was able to make sample plot here in IDE. I wonder if it will work with webagg...

https://matplotlib.org/stable/gallery/user_interfaces/embedding_webagg_sgskip.html

**Comment by QuLogic** [comment]
This is actually a duplicate of #19222.
