### ISSUE TITLE
[Bug]: Irregular pixel widths in rasterized pcolor

### ISSUE THREAD

**Issue by mschroen** [matplotlib/matplotlib#23391]
### Bug summary

Pixel widths appear irregularly in `pcolor(x, y, z, rasterized=True)`, while `x` and `y` are regular. Using `rasterized=False` provides correct (equal size) pixels, but saving the figure to `.png` (instead of `.pdf`) will show the same irregular pixel width bug.

It looks like a resampling bug, which messes up precise data visualization completely.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
x, y = np.meshgrid(range(500), range(2))
z = [np.tile([0,1],250), np.tile([0,1],250)]
fig, ax = plt.subplots(1,1, figsize=(10,2))
im = ax.pcolor(x, y, z, rasterized=True)
ax.set_xticks(np.arange(0,40))
fig.savefig('test.pdf')
plt.show()
```

### Actual outcome

In the resulting plot, some pixels are thinner, and some are thicker, than they should be. 
`rasterize=True` (zoom-in to the lower left corner)
![grafik](https://user-images.githubusercontent.com/7942719/177547093-64eb91af-1345-4be1-a04c-e99bd7ccfd49.png)

### Expected outcome

`rasterize=False` (zoom-in to the lower left corner)
![grafik](https://user-images.githubusercontent.com/7942719/177547007-82796b90-1863-4370-8718-0a1c744b3119.png)

### Additional information

- This behaviour depends on the number of pixels plotted, for me it becomes visible above `len(x)>100`.
- The spread between thicker and thinner lines increases with increasing size of the input array.
- If the view is reduced to a lower number of pixels (e.g., `ax.set_xlim(0,10)`), the effect is no longer visible.

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

inline

### Python version

3.9.6

### Installation

pip

**Comment by jklymak** [comment]
I'm going to close as an understood problem tracked in https://github.com/matplotlib/matplotlib/issues/6827 among other places.  Yes this is very annoying, and there is a partial solution that we hope to implement soon...  Thanks,

**Comment by tacaswell** [comment]
Try passing 

```
fig.savefig('test.pdf', dpi=300)
```

which should increase the effective dpi that the artists are rasterized at (by default it as at 72 dpi).
