### ISSUE TITLE
[ENH]: Library for business charts, ex. four-quadrant plot

### ISSUE THREAD

**Issue by ebauch** [matplotlib/matplotlib#23408]
### Problem

I am always surprised when I am looking for a business chart that doesn't exist out of the box in matplotlib. For example, I wanted to create a four-quadrant plot, ex. 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/3758223/178119482-ccb58a1c-aa1e-4065-a678-ab2171303e97.png">
Quadrant plots are very common in business. It is a styled version of a scatter plot but styling it is quite tricky. If you look at the [amount of code required](https://medium.com/@ctnormand1/the-four-quadrant-chart-3debe0dfdd77) to make a scatter plot look like this, it made me wonder if there is a wrapper/function in matplotlib, or better, a library for great-looking business charts. I couldn't find anything like it after googling. 

FYI: This might exists and I just haven't found it. 

### Proposed solution

Have a matplotlib function available that can make quadrant plots with minimal code required.

**Comment by tacaswell** [comment]
This is not something that I think we would put into the core library.  It is a niche plot and the linked solution is only ~80 lines of code. Additionally, I could imagine that there are some obvious elaborations (marker (shape, color, size), text {size, color, deconfliction...}, different highlighting strategies, different input (take a dataframe!), ...) that reasonable people will disagree on the utility and spelling of.

I think the best path forward for this is for you (or the author of the linked code) to put that in an installable package and publish it to pypi.  Managing this as a stand-alone package has several benefits to you:

 - you can release as early and often as you want and are not tied to our relatively slow release cycle
 - you can experiment with the API and change it as much as you want where as if it goes into core the API is very locked
 - you can take in data types as input (like pandas data frames) that we can not have a direct dependency on
 - it will be maintained by people who use this type of visualization day-to-day

Another option would be to add this as an example to the documentation.

----

In either case, make sure to get the permission of the original author (or re-write it from scratch) as it is not clear what the copyright on code in medium posts is!
