### ISSUE TITLE
PatchCollection doesn't properly handle FancyArrowPatch, breaking StreamplotSet.arrows

### ISSUE THREAD

**Issue by cgevans** [matplotlib/matplotlib#2341]
As discussed in [this SO question](http://stackoverflow.com/questions/18409444/how-to-update-color-of-streamplot-in-matplotlib/18409978#18409978) and [this mailing list thread](http://matplotlib.1069221.n5.nabble.com/Problem-with-PatchCollection-and-FancyArrowPatch-td40372.html), PatchCollection cannot handle FancyArrowPatch patches, as the paths for FancyArrowPatch can't be evaluated during PatchCollection creation. It appears that an issue was never created for this... please let me know if I'm being stupid and not noticing one.

As such, the StreamplotSet.arrows PatchCollection appears to be entirely useless. In fact, streamplot() doesn't even add the collection to the axis, instead adding the individual patches, and then creating an apparently unused PatchCollection to return. This means that things that should work, like, for a StreamplotSet `s`, doing `s.arrows.set_visible(False)`, will not work, nor, to my knowledge, will doing anything with StreamplotSet.arrows have the desired result.

As discussed in the mailing list thread, one potential solution to this would be to create a FancyArrowPatchCollection class especially for FancyArrowPatch, and then use this for streamplot; someone in the thread also gives a rudimentary class. If I have time, I might try to implement this, but does anyone have any better ideas?

**Comment by petehuang** [comment]
Confirming this is still an issue in 1.5.3

```python
import numpy as np
import matplotlib.pyplot as plt

w = 3
Y, X = np.mgrid[-w:w:100j, -w:w:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2

c = plt.streamplot(X, Y, U, V, color=(0,0,0,1))
c.lines.set_alpha(0)
c.arrows.set_alpha(0)
plt.show()
```

PR still welcome here, would recommend reading through #2500 despite it stalling.

Recommend labeling with confirmed bug

**Comment by rodogi** [comment]
Just to comment that fixing this bug will  benefit  networkx arrow-drawing (see [here](https://github.com/networkx/networkx/pull/2760)) as arrows are `FancyArrowPatch` instances.

**Comment by anntzer** [comment]
I had a quick look at this.  I think the solution likely involves using PatchCollection with TransformedPatchPath entries, so that the transform info stays in the collection.  But additionally, the draw-time computation done in FancyArrowPatch will need to move from `get_path_in_displaycoord` to a custom transform subclass, which contains the relevant logic but will be able to be combined with other transforms); this is likely the trickier part.

**Comment by yves-surrel** [comment]
Will this bug be ever fixed? I need to plot hundreds of annotations and it is awfully slow...

**Comment by robinfissum** [comment]
My `some_streamplotset.arrows.remove()` continues to fail... Any updates on this?
