### ISSUE TITLE
[Bug]: `rcParams["figure.figsize"]` will be reset the first time `plt.plot` invoke

### ISSUE THREAD

**Issue by PaleNeutron** [matplotlib/matplotlib#23428]
### Bug summary

`plt.rcParams["figure.figsize"]` will be reset the first time `plt.plot` invoke.

### Code for reproduction

```python
import pandas as pd
import matplotlib.pyplot as plt

data = [[78, 37,  8],
       [35, 40, 79],
       [73,  0, 88],
       [80, 51, 55],
       [78, 34, 10],
       [73, 45,  0],
       [73, 43, 49],
       [15, 32, 76],
       [27, 70, 13]]
df = pd.DataFrame(data)
df
plt.rcParams["figure.figsize"] = [12, 6]
plt.plot(df)
plt.show()
print(plt.rcParams["figure.figsize"])
plt.rcParams["figure.figsize"] = [12, 6]
plt.plot(df)
plt.show()
```

### Actual outcome

<img width="590" alt="image" src="https://user-images.githubusercontent.com/8296331/179136993-bcc75532-499a-4536-862c-b9f01bbb6b05.png">

### Expected outcome

figure size is `12,6` the first time

### Operating system

windows & linux

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.5

### Jupyter version

6.4.12

### Installation

pip

**Comment by tacaswell** [comment]
This is a known and fixed bug which was exposed by 3.5.2 and fixed by https://github.com/ipython/matplotlib-inline/pull/14 but I think we need a new release of matplotlib-inline.
