### ISSUE TITLE
[Bug]: Axes.indicate_inset connectors affect constrained layout

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#23425]
### Bug summary

When adding `indicate_inset` on constrained figures, the position of Axes changes from a figure without indicators. This can be worked around by manually setting the connectors out of layout.

### Code for reproduction

```python
import matplotlib.pyplot as plt

for i in range(2):
    fig, axs = plt.subplots(2, 1, constrained_layout=True)
    for ax in axs:
        ax.plot([1, 2, 3])
    axs[1].set_xlim(0.5, 1.5)

# Add inset indicators only on the second figure.
_, conns = axs[0].indicate_inset_zoom(axs[1])

plt.show()
```

### Actual outcome

Without connectors:
![Figure_1](https://user-images.githubusercontent.com/302469/179059333-fd4c22de-a3dd-4c0a-84cf-6211e5ca2630.png)
With connectors:
![Figure_2](https://user-images.githubusercontent.com/302469/179059345-a38f39dc-feaf-406d-93ea-e03bc0454227.png)
There is now some extra space between the two vertically.

### Expected outcome

If you add:
```
for con in conns:
    con.set_in_layout(False)
```
then the Axes as positioned the same as the original image:
![Figure_3](https://user-images.githubusercontent.com/302469/179059565-285bed32-0699-4ae9-8fb4-8a0e2c721d25.png)

### Matplotlib Version

37ccdca5028725b3b9d689b42947b6284a73d690

### Installation

git checkout

**Comment by rcomer** [comment]
The [constrained layout guide](https://matplotlib.org/devdocs/users/explain/axes/constrainedlayout_guide.html#other-caveats) and [ConnectionPatch docstring](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.patches.ConnectionPatch.html#matplotlib.patches.ConnectionPatch) recommend that `ConnectionPatch`s are either added to the figure or dis-included from the layout :thinking:
