### ISSUE TITLE
[Doc]: Card title background got lost

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#23421]
### Problem

... probably in recent CSS changes. I'm unclear whether this was intentional, but the white spaces look now out-of-proportion. Compare:

https://matplotlib.org/devdocs/
![grafik](https://user-images.githubusercontent.com/2836374/178602457-44d4201f-4223-47e2-9a24-6f2b78d30660.png)

https://matplotlib.org/stable/
![grafik](https://user-images.githubusercontent.com/2836374/178602365-baa7438c-3ca7-488e-8c4e-064b6b3d28a7.png)

**Comment by jklymak** [comment]
No it wasn't intentional, just fell back to the default for dark mode compatibility.  We could add more styling back if desired.

**Comment by rajpratyush** [comment]
shall i work on this issue?

**Comment by timhoffm** [comment]
This is fixed through a new release of pydata-sphinx-theme. They chose to remove the background but have added back the line separating heading from content. This is good enough for me.

![image](https://user-images.githubusercontent.com/2836374/189000181-9510decf-34a0-4564-8d90-4ef90ec63605.png)
