### ISSUE TITLE
[Doc]: Double : in dev-docs 

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23446]
### Documentation Link

https://matplotlib.org/devdocs/api/

### Problem

Not sure if this has always been the case, but considering the recent style changes etc..

![image](https://user-images.githubusercontent.com/8114497/179735610-2841cbf0-b0af-4a64-9f90-2215a7cf8f85.png)

There are double : after the Parameters and Return headings.

**Comment by QuLogic** [comment]
This appears to be a Sphinx+docutils issue: https://github.com/sphinx-doc/sphinx/issues/10594; just waiting for 5.0.3 to fix it.

**Comment by oscargus** [comment]
No longer a problem in recent Sphinx.
