### ISSUE TITLE
[Bug]: string representation of `event.button` is different when using f-strings 

### ISSUE THREAD

**Issue by raphaelquast** [matplotlib/matplotlib#23460]
### Bug summary

I'm not sure to what extent this is a bug or a feature, but to me this behavior was quite unexpected
and this inconsistency was the reason for some issues on my side so I thought I'll report it:

At the moment the `event.button` property returns 2 different values if I evaluate it as string or within an f-string:

- `str(event.button)` gives `"MouseButton.LEFT"`
- `f"{event.button}"` gives `1`

### Code for reproduction

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots()
f.canvas.mpl_connect("button_press_event", lambda event: print("using str(event.button):", str(event.button), "\nusing f'{event.button}':", f"{event.button}"))
```

### Actual outcome
```python
>>> using str(event.button): "MouseButton.LEFT"
>>> using f'{event.button}': "1"
```
### Expected outcome

I'd expect to get the same output for both methods.

### Additional information

f-strings use `.__format__()` while `str()` uses `.__str__()` to get the values which is the cause for this ambiguity.

### Operating system

Windows

### Matplotlib Version

3.5.1

### Matplotlib Backend

Qt5Agg

### Python version

3.7.12

### Installation

conda

**Comment by oscargus** [comment]
`MouseButton` inherits from `IntEnum`, which in turn inherits from `Enum` (both from the `enum` module).

`Enum` has:
https://github.com/python/cpython/blob/b60c3d2f7efede5d80bde2aec0b558b12814a0b3/Lib/enum.py#L749-L750
and
https://github.com/python/cpython/blob/b60c3d2f7efede5d80bde2aec0b558b12814a0b3/Lib/enum.py#L764-L781

So this is really a consequence of the Python standard module.

**Comment by raphaelquast** [comment]
thanks for the quick response! 

OK, so this is really just a subtlety of `IntEnum`...
(seems that there are others that find this confusing as well [stackoverflow: f-string representation different than str()](https://stackoverflow.com/questions/72449482/f-string-representation-different-than-str) )

From my side this can be closed since there's really not much one can do about it (except overriding __format__ which would most certainly cause more problems than it solves...) 

I'll just make sure that I stick to one of the methods throughout my code 😅 

```python
from enum import Enum
class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

c = Color(1)

str(c)
>>>   "Color.RED"

f"{c}"
>>>   "Color.RED"
```

```python
from enum import IntEnum
class Color(IntEnum):
    RED = 1
    GREEN = 2
    BLUE = 3

c = Color(1)

str(c)
>>>   "Color.RED"

f"{c}"
>>>   "1"
```

**Comment by oscargus** [comment]
You can do `f"{c!s}"` to get the string version, if you prefer f-strings.

(I also learnt a bit looking into it!)

**Comment by raphaelquast** [comment]
> You can do `f"{c!s}"` to get the string version, if you prefer f-strings.
> 
> (I also learnt a bit looking into it!)

Same here 😄  Thanks, yep that would work as well!

**Comment by tacaswell** [comment]
This is a change in behavior on our part (we did not used to inherit from `IntEnum` before `IntEnum` existed in our minimum supported Python, however I do not think we should do anything (other than maybe retro-actively put in a API change note) because the new behavior is the upstream behavior and we should (when possible) align our behavior with upstream as much as possible.
