### ISSUE TITLE
Colorbar autoscale handling an array of one value

### ISSUE THREAD

**Issue by gurglespuge** [matplotlib/matplotlib#2347]
When plotting with imshow an array with all one value.

```
a = ones((10,10))
imshow(a)
colorbar()
show()
```

colorbar.py:829: RuntimeWarning: invalid value encountered in divide
  z = np.take(y, i0) + (xn - np.take(b, i0)) \* dy / db

The output is thus:

![figure_1](https://f.cloud.github.com/assets/4734945/1037462/26f03b78-0f50-11e3-8304-a6685c9d09f5.png)

I realize this is a corner case, but it would be very useful for the colorbar auto scale to somehow indicate the value.

Putting this code into colorbar.py
 _locate function

immediately before the return(z) call

```
if np.isnan(z).any():$                                                 
    z = np.array(range(1,len(x)))/float(len(x))$  
```

remedies the problem for me.

I can send a patch file for fork, if anyone is interested.

I presume this is not the best way to remedy the issue for matplotlib proper, probably better to detect the condition earlier and deal with it, then screen for nan's

**Comment by cas0010** [comment]
I'm rather new to this site, but did this issue ever get resolved? I'm trying to use colorbar on arrays with the same value over most positions. I'm getting the error message discussed above and tried the 

if np.isnan(z).any():$                                                 
    z = np.array(range(1,len(x)))/float(len(x))$  

tip, but still have an error message. Any help with this would be great.

**Comment by WeatherGod** [comment]
I think so, I can't reproduce it using code from the master branch.  Which version of matplotlib are you using?

**Comment by cas0010** [comment]
I'm using matplotlib 1.3.0.
