### ISSUE TITLE
[Bug]: colorbar doesn't scale properly using `imshow` with diverging cmap and normalization (>=3.5.0)

### ISSUE THREAD

**Issue by alex-l-kong** [matplotlib/matplotlib#23477]
### Bug summary

In `matplotlib` versions 3.5.0 or later, using `imshow` with a diverging colormap and a custom normalizer won't scale the colorbar properly if `vmax` is changed on the normalizer. This issue does not appear with previous versions of `matplotlib`.

### Code for reproduction

```python
from matplotlib.colors import Normalize
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

class ZScoreNormalize(Normalize):
    """Normalizer tailored for zscore heatmaps

    Map each value of an incoming vector each between 0 and 1, which
    is the interval for cmaps.

    The mapping consists of two separate linearly interpolated intervals:

        [vmin,vcenter] -> [0.0,0.5]
        [vcenter,vmax] -> [0.5,1.0]

    """
    def __init__(self, vmin=-1, vcenter=0, vmax=1):
        """Initial ZScoreNormalize

        vmin < vcenter < vmax

        Args:
            vmin (float):
                Value to map to 0 in the colormap
            vcenter (float):
                Value to map to .5 in the colormap
            vmax (float):
                Value to map to 1 in the colormap
        """
        self.vcenter = vcenter
        super().__init__(vmin, vmax)

    def calibrate(self, values):
        self.vmin = min([np.min(values), 0])
        self.vcenter = 0.0
        self.vmax = np.max(values)

    def __call__(self, value: np.ndarray, clip=None):
        """Map ndarray to the interval [0, 1]. The clip argument is unused."""
        result, is_scalar = self.process_value(value)

        normalized_values = np.interp(
            result,
            [self.vmin, self.vcenter, self.vmax],
            [0, 0.5, 1.]
        )

random_arr = np.random.uniform(-5, 10, size=(16, 16))
normalizer = ZScoreNormalize(-1, 0, 1)

im_c = plt.imshow(
    random_arr,
    norm=normalizer,
    cmap=sns.diverging_palette(240, 10, n=3, as_cmap=True),
    aspect='auto',
    picker=True
)

cb_c = plt.colorbar(im_c, orientation='horizontal')
_ = cb_c.ax.xaxis.set_tick_params(which='both', labelsize=7, labelrotation=90)

normalizer.calibrate(random_arr)

im_c.set_data(random_arr)
im_c.set_extent((0, 100, 0, 20))
im_c.set_clim(normalizer.vmin, normalizer.vmax)
```

### Actual outcome

<img width="254" alt="Screen Shot 2022-07-22 at 1 41 46 PM" src="https://user-images.githubusercontent.com/31424707/180564457-ac5c298b-b0ce-4615-8dc4-55ac8c472d90.png">

### Expected outcome

<img width="250" alt="Screen Shot 2022-07-22 at 1 42 22 PM" src="https://user-images.githubusercontent.com/31424707/180564582-838806dc-1c5d-4c1a-a9e8-706dcbabe0b1.png">

### Operating system

Debian (bullseye)

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.7

### Jupyter version

3.4.3

### Installation

pip

**Comment by jklymak** [comment]
If you want the colorbar to work, you need to provide in inverse method to your Norm as of 3.5:

```python
    def inverse(self, value):
        result = np.interp(value,
        [0, 0.5, 1],
        [self.vmin, self.vcenter, self.vmax],
        )
        return result
```

Sorry for the bother, but it does allow proper non-linear axes.

**Comment by jklymak** [comment]
I'll close this because norms have _always_ had inverses, so users creating there own norms should define them.  I think an argument could be made that Normalize should have had a base class with NotImplementedError for things we require...

BTW, to get _exactly_ the same plot as before, you also need to set the scale to be linear: `cb_c.ax.set_xscale('linear')`
