### ISSUE TITLE
hatch linewidth patch

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#235]
[Original report at SourceForge, opened Tue Feb 22 17:26:22 2011](https://sourceforge.net/tracker/?func=detail&aid=3189557&group_id=80706&atid=560722)

The pdf backend uses a 0.1pt linewidth for hatch marks, which, depending on scaling and ultimate output, can make them impossible to see.  I haven't looked at any non-pdf backends (pdf seems to be the only one that implements a writeHatches function), and I don't know if the rc var name is reasonable, but this seems like the beginning of a fix everyone can enjoy.

### SourceForge History

* On Tue Feb 22 17:26:22 2011, by jcmdev0: File Added: 402433: hatch_linewidth_svn.diff

**Comment by rabernat** [comment]
I just hit this problem. Has it really not been fixed yet?

**Comment by rodrigob** [comment]
nope. the PR never made it in.

**Comment by WeatherGod** [comment]
Looking over the PR, it looks like tests were failing and the PR was
incomplete anyway. There are some fundamental issues with how hatching is
implemented that made it difficult to complete. There is no one place for
hatching to be taken care of, and we even have a place where hatching is
implemented in some C++ code, so it doesn't get any direct access to
rcParams. Hatching might need an overhaul first before this feature can get
added.

On Wed, Nov 11, 2015 at 11:52 AM, Rodrigo Benenson <notifications@github.com

**Comment by mdboom** [comment]
I'm going to reopen this for examination during the style changes.  There's sort of two questions here:

1) What is the right default width for hatchlines?  I'd argue the current default is not ideal (and it's also not the same across backends).
2) Exposing that as a parameter both in the hatch specifier and an rcParam

I'd say resolving (1) is critical for 2.0 while we're changing other style things.  (2) would also be really nice, but could be punted on if we can't get it done.
