### ISSUE TITLE
Pointless debug message on GUI repaint

### ISSUE THREAD

**Issue by alexdewar** [matplotlib/matplotlib#23512]
https://github.com/matplotlib/matplotlib/blob/862f85d37a0f0da270d93aa3a59157bb9f1553d3/lib/matplotlib/backends/backend_wx.py#L612

I am embedding a matplotlib plot in my wxpython GUI application and stdout is being spammed with messages like this:
```
2022/07/29 07:59:09 [DEBUG] backend_wx.gui_repaint(606): <class 'matplotlib.backends.backend_wxagg.FigureCanvasWxAgg'> - gui_repaint()
2022/07/29 07:59:10 [DEBUG] backend_wx.gui_repaint(606): <class 'matplotlib.backends.backend_wxagg.FigureCanvasWxAgg'> - gui_repaint()
```

Yes, I can suppress this by calling ``set_loglevel()``, but I'm not sure why this statement is needed in the first place. (Or, if it is, maybe the default log level should be "warning" instead -- ordinary users don't need debug messages.)

**Comment by oscargus** [comment]
There are indeed quite a lot of debug messages in the wx-backend. Setting the log-level seems to make sense, although probably many of the wx-messages are not really required (anymore).

**Comment by jklymak** [comment]
@alexdewar "DEBUG" is the lowest logging level (i.e. most verbose). I think we reserve the right to spam it as we see fit.  If you don't want our messages, `logging.getLogger("matplotlib").setLevel(logging.CRITICAL)` after you set your basic config should suppress all our messages.

**Comment by alexdewar** [comment]
You do have the right to spam as you see fit (assuming that you feel this particular message adds something), *however* I think it is perhaps worth considering whether the average user (i.e. not a ``matplotlib`` developer) wants log spam *by default* :wink: 

Verbose debugging messages are fine for developers, but I feel like it should be an opt-in thing, not an opt-out one.

**Comment by jklymak** [comment]
The default logging level is WARNING.  If you are being spammed by our DEBUG messages, either you, or a library you are using, has set the logging level lower.

**Comment by alexdewar** [comment]
Ohhh I see. That's weird... It must be being set somewhere in a library I'm using.

Sorry for the noise!

**Comment by jklymak** [comment]
No problem - some libraries set the default log level, and that is super confusing.
