### ISSUE TITLE
[Bug]: Beach balls are drawn as ellipses

### ISSUE THREAD

**Issue by wangliang1989** [matplotlib/matplotlib#23520]
### Bug summary

Beach balls should be drawn as perfect circles at any time, but they are drawn as ellipses when the horizontal and vertical coordinates use different scales.

### Code for reproduction

```python
#!/usr/bin/env python
import matplotlib.pyplot as plt
from obspy.imaging.beachball import beach
import matplotlib

print(matplotlib.__version__)
fig = plt.gca()
ball = beach([150, 90, 0], xy=(25, 50), width=20)
fig.add_collection(ball)
fig.set_aspect(0.5)
fig.set_xlim((0, 50))
fig.set_ylim((0, 100))
plt.savefig('bug.pdf', format='pdf')
```

### Actual outcome

<img width="576" alt="image" src="https://user-images.githubusercontent.com/12059719/181867446-6d7411b4-17db-4258-b450-2c0feff60130.png">

### Expected outcome

The bass should be perfect circle.

### Operating system

MacOSX

### Matplotlib Version

3.2.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.8.3

### Jupyter version

6.0.3

**Comment by jklymak** [comment]
Beach is not a matplotlib method so it's not clear how we can help.  Please give us a standalone example that doesn't use obspy.

**Comment by wangliang1989** [comment]
> Beach is not a matplotlib method so it's not clear how we can help. Please give us a standalone example that doesn't use obspy.

Sorry, I don't understand. I think plotting a beach ball is a function of matplotlib. I am new to python. So, you mean the problem is from obspy?

**Comment by jklymak** [comment]
I don't know where the problem is, but your `beach` method is being imported from obspy, not Matplotlib, so that is probably the correct place to ask questions.

In general, Matplotlib axes can have arbitrary aspect ratio.  I expect if you did ax.set_aspect('equal') your beach ball would be a circle.

**Comment by wangliang1989** [comment]
Yes, if ax.set_aspect('equal'),the ball will be circle. But, I want the horizontal and vertical coordinates have the same length.

**Comment by timhoffm** [comment]
Please report to https://github.com/obspy/obspy/issues. I suspect this has to be addressed on their side.

**Comment by wangliang1989** [comment]
This code can fix this question and be written to those who also encounter this problem and search on the Internet in the future:
````
#!/usr/bin/env python
import matplotlib.pyplot as plt
from obspy.imaging.beachball import beach

np1 = [150, 87, 1]
mt = [-2.39, 1.04, 1.35, 0.57, -2.94, -0.94]

fig, ax = plt.subplots(figsize=(5, 5))
beach1 = beach(np1, xy=(5, 90), width=50, axes=ax)
beach2 = beach(mt, xy=(20, 50), width=50, axes=ax)
ax.add_collection(beach1)
ax.add_collection(beach2)
ax.set_xlim((0, 50))
ax.set_ylim((0, 100))
plt.savefig('bug.pdf', format='pdf')
````
