### ISSUE TITLE
[Bug]: pyplot suptitle horizontalalign 

### ISSUE THREAD

**Issue by gregomelo** [matplotlib/matplotlib#23522]
### Bug summary

Hey.

I am trying to use horizontalalignment parameter, but it did not work as well.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

plt.title('Left Title', loc='left')

plt.suptitle('Left Suptitle', ha='left')

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/87508395/181907972-4ba97468-2d7a-40c4-a9dc-2b3d9b59c0b4.png)

### Expected outcome

I expected that title and suptitle horizontal alignment were equal.

### Operating system

Windows

### Matplotlib Version

'3.2.2'

### Matplotlib Backend

'module://ipykernel.pylab.backend_inline'

### Python version

3.8.3

### Installation

conda

**Comment by jklymak** [comment]
This is expected behaviour.  The alignment is relative to the x position which is 0.5 of the figure width.  The title "loc" keyword changes the position of the title.  Suptitle takes and x and y parameter so I'll close this as won't fix.
