### ISSUE TITLE
[Bug]: customized marker (mode='vert') in scatter plot seems incorrect

### ISSUE THREAD

**Issue by frankligy** [matplotlib/matplotlib#23545]
### Bug summary

When I was trying to draw a scatter plot with each dot being a pie chart following the official tutorial (https://matplotlib.org/stable/gallery/lines_bars_and_markers/scatter_piecharts.html), I found the behaviors of the marker is not exactly as what I expected, let me clarify.

### Code for reproduction

```python
r1 = 0.1
size = 60
x1 = np.cos(2 * np.pi * np.linspace(0,r1))
y1 = np.sin(2 * np.pi * np.linspace(0,r1))
xy1 = np.row_stack([[0, 0], np.column_stack([x1, y1])])
fig, ax = plt.subplots()
ax.scatter([0.5], [0.5], marker=xy1, s=size**2, facecolor='blue')
```

### Actual outcome

Although the arc looks decent at first glance, when zooming in, the problem appears:

<img width="1102" alt="Screen Shot 2022-08-03 at 1 08 07 PM" src="https://user-images.githubusercontent.com/59619831/182676097-95d1f874-60c1-409a-8caf-72febd657152.png">

### Expected outcome

I would expect the outcome to be a perfect a arc without the three problematic regions that I described above.

### Operating system

OS/X

### Matplotlib Version

3.5.2

### Matplotlib Backend

MacOSX

### Python version

3.7.13

**Comment by tacaswell** [comment]
If you plot the data you are using for the marker via `plt.plot(*xy1.T, lw=50)` you get 
![so](https://user-images.githubusercontent.com/199813/182686038-faf3aea8-0436-45f2-a979-6d8e98f990dc.png) or using scatter with slightly different styling 

```python
ax.scatter([0.5], [0.5], marker=xy1, s=size**2, facecolor='blue', edgecolor='red', lw=50)
```
gives (with some manual panning)
![so](https://user-images.githubusercontent.com/199813/182686688-17e31d99-9eaf-4f74-8eb3-932669f27ee4.png)


The default miter style is round and the default cap style is butt (or projecting).  What is going on is that we are drawing the bottom edge and the part of the arc as a path (which explains the rectangle and the round corner on the bottom.  When we get to the top point we then fill in the shape using a straight line (but no drawn edge) back to the starting point hence the apparent sharp point.

To get what you want I think you need to make a `Path` object (https://matplotlib.org/stable/api/path_api.html#module-matplotlib.path).  Have to run to a meeting but I think the codes you want are : 

```
MOVETO 0 0
LINETO  0 1
CURVE3 (middle of arc)
CURVE3 (top of arc)
CLOSEPOLY 0 0
```

Also look into the `Arc` artists, we may have a helper that just gives you the correct `Path`.

**Comment by frankligy** [comment]
Hi @tacaswell thanks so much for the explanation, I didn't realize the presence of the edge, based on your instruction, this can be easily resolved by setting `lw=0`.  Maybe I will suggest to add that to the official tutorial as well, because current tutorial is actually not considering it. thanks again for the help!

**Comment by tacaswell** [comment]
@frankligy Are you OK with closing this issue?

**Comment by tacaswell** [comment]
If you are interested in opening the PR to the docs I would be happy to review it!

**Comment by tacaswell** [comment]
```python
import matplotlib.pyplot as plt
from matplotlib.markers import MarkerStyle
from matplotlib.path import Path

p = Path(
    [
        [0, 0],
        [1, 0],
        [np.cos(2 * np.pi * 0.05), np.sin(2 * np.pi * 0.05)],
        [np.cos(2 * np.pi * 0.1), np.sin(2 * np.pi * 0.1)],
        [0, 0],
    ],
    [Path.MOVETO, Path.LINETO, Path.CURVE3, Path.CURVE3, Path.CLOSEPOLY],
)
ms = MarkerStyle(p)
plt.scatter(
    [0.5], [0.5], marker=ms, s=size**2, facecolor="blue", edgecolor="red", lw=50
)

````

(plus some manual panning) gives

![so](https://user-images.githubusercontent.com/199813/182889463-fe303769-a6b5-4531-bce0-c74fbbc814da.png)
