### ISSUE TITLE
[Bug]: Installing matplotlib

### ISSUE THREAD

**Issue by frankvp11** [matplotlib/matplotlib#23564]
### Bug summary

I am trying to use Docker to install matplotlib, but it keeps failing, and sometimes it tries to recursively reinstall it. It then tells me that there is no matching distribution from version .... even though in the list of version it includes it. 

### Code for reproduction

```python
pip install matplotlib==2.1.0
```

### Actual outcome

 ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64k3rvg6/matplotlib_35b798495e2b4c85b6ce1973ee5bc1dd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64k3rvg6/matplotlib_35b798495e2b4c85b6ce1973ee5bc1dd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xwy49kwk
       cwd: /tmp/pip-install-64k3rvg6/matplotlib_35b798495e2b4c85b6ce1973ee5bc1dd/
  Complete output (73 lines):
  ============================================================================
  Edit setup.cfg to change the build options
  
  BUILDING MATPLOTLIB
              matplotlib: yes [2.1.0]
                  python: yes [3.6.9 (default, Jun 29 2022, 11:45:57)  [GCC
                          8.4.0]]
                platform: yes [linux]
  
  REQUIRED DEPENDENCIES AND EXTENSIONS
                   numpy: yes [not found. pip may install it below.]
                     six: yes [using six version 1.11.0]
                dateutil: yes [dateutil was not found. It is required for date
                          axis support. pip/easy_install may attempt to
                          install it after matplotlib.]
  backports.functools_lru_cache: yes [Not required]
            subprocess32: yes [Not required]
                    pytz: yes [pytz was not found. pip/easy_install may
                          attempt to install it after matplotlib.]
                  cycler: yes [cycler was not found. pip/easy_install may
                          attempt to install it after matplotlib.]
                 tornado: yes [tornado was not found. It is required for the
                          WebAgg backend. pip/easy_install may attempt to
                          install it after matplotlib.]
               pyparsing: yes [pyparsing was not found. It is required for
                          mathtext support. pip/easy_install may attempt to
                          install it after matplotlib.]
                  libagg: yes [pkg-config information for 'libagg' could not
                          be found. Using local copy.]
                freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                          could not be found.  You may need to install the
                          development package.]
                     png: no  [pkg-config information for 'libpng' could not
                          be found.]
                   qhull: yes [pkg-config information for 'libqhull' could not
                          be found. Using local copy.]
  
  OPTIONAL SUBPACKAGES
             sample_data: yes [installing]
                toolkits: yes [installing]
                   tests: no  [skipping due to configuration]
          toolkits_tests: no  [skipping due to configuration]
  
  OPTIONAL BACKEND EXTENSIONS
                  macosx: no  [Mac OS-X only]
                  qt5agg: no  [PySide2 not found; PyQt5 not found]
                  qt4agg: no  [PySide not found; PyQt4 not found]
                 gtk3agg: no  [Requires gtk3 development files to be
                          installed.]
               gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                  gtkagg: no  [Requires pygtk]
                   tkagg: yes [installing; run-time loading from Python Tcl /
                          Tk]
                   wxagg: no  [requires wxPython]
                     gtk: no  [Requires pygtk]
                     agg: yes [installing]
                   cairo: no  [cairocffi or pycairo not found]
               windowing: no  [Microsoft Windows only]
  
  OPTIONAL LATEX DEPENDENCIES
                  dvipng: no
             ghostscript: no
                   latex: no
                 pdftops: no
  
  OPTIONAL PACKAGE DATA
                    dlls: no  [skipping due to configuration]
  
  ============================================================================
                          * The following required packages can not be built:
                          * freetype, png * Try installing freetype with `apt-
                          * get install libfreetype6-dev` * Try installing png
                          * with `apt-get install libpng12-dev`
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6c/90/cf10bb2020d2811da811a49601f6eafcda022c6ccd296fd05aba093dee96/matplotlib-2.1.0.tar.gz#sha256=4b5f16c9cefde553ea79975305dcaa67c8e13d927b6e55aa14b4a8d867e25387 (from https://pypi.org/simple/matplotlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement matplotlib==2.1.0 (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4)
ERROR: No matching distribution found for matplotlib==2.1.0
The command '/bin/sh -c apt-get --assume-yes update     && apt-get --assume-yes upgrade     && apt-get install --assume-yes git     && apt-get install --assume-yes python3-pip     && apt-get install python3-dev -y     && apt-get install pkg-config     && python3 -m pip install --upgrade pip     && python3 -m pip install --upgrade setuptools     cmake     Cython     pycocotools     matplotlib==2.1.0     numpy==1.19.4     torch==1.9     torchvision     pycuda' returned a non-zero code: 1

### Expected outcome

"You have successfully installed matplotlib" or whatever

### Additional information

I am using python3.6
I am not sure- I am using a Jetson TX2 if that helps
It is getting installed from (i believe pycuda) 

### Operating system

ubuntu 18.04

### Matplotlib Version

Im trying to get 2.1.0

### Matplotlib Backend

NA

### Python version

python3.6

### Jupyter version

na

### Installation

pip

**Comment by jklymak** [comment]
Please take up install issues on https://discourse.matplotlib.org Thanks for your understanding.
