### ISSUE TITLE
[ENH]: Z-axis/3D support for Figure options

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23566]
### Problem

The QT backend do have a figure option dialogue which allows changing a few parameters for the x and y axes, but not the z axes (when there is one).

### Proposed solution

Add support for z axes (when there is one).

**Comment by oscargus** [comment]
Probably a quite good way to solve it is to loop over the possible axis rather than have everything hard coded like it is now.

Also, changing the limits to "Min" and "Max" rather than "Left"/"Bottom" and "Right"/"Top" should be a thing.

**Comment by oscargus** [comment]
This may be a good first issue, but requires quite a bit of understanding of how Python works with naming etc to change it into loops and some understanding of Qt.

**Comment by chahak13** [comment]
Hi @oscargus ! I was taking a look at this and would try to work on it. Is this open for contributions?

**Comment by oscargus** [comment]
Sure! You are very welcome to give it a go!

**Comment by chahak13** [comment]
Thanks! Do you have any suggested starting points for me? I took a look at `backend_qt.py` and I believe that this is for the `Configure subplots` tool? The toolbox that sets the `Configure subplots` tool uses `SubplotParams` names (`top`, `bottom`, `left`, `right`) to set attributes.

**Comment by oscargus** [comment]
This is the file that contains the figure options dialog:

https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/qt_editor/figureoptions.py

I'd start by making it general so that there is no need to hardcode x and y, so calling functions with a dynamic name and loop over x and y. When that works, it would "just" be to also loop over z as well (if there is a z). 

Note that even if you do not pull it off completely, just modifying the code to be more modular would be a step.

From a quick look it seems like the `general` list could be split into a dictionary containing the general information and then the specific information for each axis.

A problem here is that there are no automatic tests for it, so one will need to manually test after changing something to make sure it still works.

**Comment by oscargus** [comment]
Making a dict may not be a good idea as it seems like the underlying GUI expects a list of tuples:
https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/qt_editor/_formlayout.py

So maybe conditionally extend `general` with zdata if there exists and then try to expand it correctly.

**Comment by oscargus** [comment]
`axes._axis_map` will get you a dictionary with axis names and axes.

You can replace, say, `axes.get_xlabel()` with `getattr(axes, f"get_{axis}label")()` if `axis = 'x'` and so on.

**Comment by chahak13** [comment]
Thanks, @oscargus, this is really helpful. I'll get to working on it today.

**Comment by melissawm** [comment]
Hi @chahak13 - is this issue fixed by your PR?

**Comment by chahak13** [comment]
Yep! @melissawm
