### ISSUE TITLE
[Doc]: mpl_toolkits.axes_grid still mentioned as maintained

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23560]
### Documentation Link

https://matplotlib.org/stable/api/toolkits/axes_grid.html?highlight=axes_grid

### Problem

As far as I can tell, it is completely removed.

### Suggested improvement

Change the wording to say something correct. Possibly when it was removed.

**Comment by oscargus** [comment]
I realize now that this is solved by import magic.

**Comment by oscargus** [comment]
Oh, and I also realize that this was actually removed in #22886 but that https://github.com/matplotlib/matplotlib/blob/main/doc/api/toolkits/axes_grid.rst wasn't removed or edited.

Not sure what the best thing is to do here. Remove and redirect to `axes_grid1` (possibly with a note that some functionality is in `axisartist`)?

**Comment by tacaswell** [comment]
not a blocker for rc2
