### ISSUE TITLE
[ENH]: Coordinate axes ticks at multiples of a number (like π)

### ISSUE THREAD

**Issue by tfpf** [matplotlib/matplotlib#23568]
### Problem

Plots of trigonometric functions don't look 'professional' because the ticks on the horizontal axis are drawn at rational coordinates.
```
import matplotlib.pyplot as plt
(fig, ax) = plt.subplots()
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = np.sin(x)
ax.plot(x, y)
ax.grid(True)
plt.show()
```
![sin1](https://user-images.githubusercontent.com/19171016/183255075-14c6e48b-aab2-4674-9eb7-9486795124d2.png)

### Proposed solution

I while ago, I wrote a helper function to generate ticks and labels. It's not pretty (and not optimal either), but it works.
```
import fractions
import matplotlib.pyplot as plt
import numpy as np

def _labels_and_ticks(first, last, step, symbol=r'\pi', symval=np.pi):
    try:
        s_num, s_den = symbol.split('/')
    except ValueError:
        s_num = symbol
        s_den = '1'
    coefficients = np.arange(first, last + step / 2, step)

    labels = []
    for i, coefficient in enumerate(coefficients):
        value = fractions.Fraction(coefficient).limit_denominator()
        num = value.numerator
        den = value.denominator

        # Case 1: `coefficient` is zero.
        if not num:
            labels.append('$0$')
            continue

        # Case 2: `coefficient` is non-zero.
        builder = ['$']
        if num < 0:
            builder.append('-')
            num = abs(num)
        is_fraction = den != 1 or s_den != '1'
        if is_fraction:
            builder.append(r'\dfrac{')
        if num != 1:
            builder.append(f'{num}')
        if s_num != '1' or num == 1:
            builder.append(s_num)
        if is_fraction:
            builder.append(r'}{')
        if den != 1:
            builder.append(f'{den}')
        if s_den != '1':
            builder.append(s_den)
        if is_fraction:
            builder.append(r'}')
        builder.append('$')
        labels.append(''.join(builder))
    return (labels, symval * coefficients)

(fig, ax) = plt.subplots()
labels, ticks = _labels_and_ticks(-2, 2, 0.25)
ax.set_xticks(ticks, labels)
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = np.sin(x)
ax.plot(x, y)
ax.grid(True)
plt.show()
```
![sin2](https://user-images.githubusercontent.com/19171016/183255133-4fcd98e6-b669-49ea-b34e-5d087e5a6605.png)

It can also handle fractions.
```
(fig, ax) = plt.subplots()
labels, ticks = _labels_and_ticks(-2, 2, 1/6, r'\pi/\gamma', np.pi/np.euler_gamma)
ax.set_xticks(ticks, labels)
x = np.linspace(-2 * np.pi / np.euler_gamma, 2 * np.pi / np.euler_gamma, 1000)
y = np.sin(np.euler_gamma * x)
ax.plot(x, y)
ax.grid(True)
plt.show()
```
![sin3](https://user-images.githubusercontent.com/19171016/183255286-8a0dcd36-75af-491e-a210-7ca5a5675ee0.png)

Would be nice to have this feature in Matplotlib.

**Comment by jklymak** [comment]
What API do you propose this have?  There is no way we can have this turned on by default.  Perhaps consult our ticker API.  I thought there was an example of this in the gallery, but I can't find it.  I think this is either an example, or a proposed new locator/formatter pair.

**Comment by tfpf** [comment]
> What API do you propose this have?

Exactly the question I was hoping to get an answer to. Having checked the ticker API, I think this will require a new formatter class? (But more importantly, is this feature viable?)

**Comment by jklymak** [comment]
I think it would be better as an example as it's quite specialized.

**Comment by oscargus** [comment]
I have something similar in mplsignal (which is probably not close to being released yet): https://github.com/oscargus/mplsignal/blob/main/mplsignal/ticker.py

I implemented a `FactorLocator` and `FactorFormatter`, which currently uses a `MaxNLocator` on the sequence with a divided factor and then prints with the factor concatenated. That would not give rational factors though.

Based on that a `PiLocator` and `PiFormatter` are readily implemented.

**Comment by oscargus** [comment]
This gives the following for your original code:
![image](https://user-images.githubusercontent.com/8114497/183299917-e1dce53d-2909-4e52-a135-cc359f4e702c.png)

**Comment by tfpf** [comment]
This is really nice. I guess there's not much point reinventing the wheel.
