### ISSUE TITLE
cxxsupport.cxx not found

### ISSUE THREAD

**Issue by megies** [matplotlib/matplotlib#2359]
Is matplotlib supposed to use its included `cxxsupport.cxx` file in case it is not present in the used python environment / system? If so, the lookup seems to fail in some cases. I can give directions how to reproduce (debian squeeze) if anybody is interested.

Also, the path that is fixed in https://github.com/matplotlib/matplotlib/blob/7d40606b35f7f62b2e7c26d04d75aed034cbdd44/setupext.py#L708-L709 is not valid for Debian. [Debian has it in](http://packages.debian.org/wheezy/all/python-cxx-dev/filelist) '/usr/share/python2.6/CXX' and (EDIT:) ~~'/usr/share/python2.6/CXX'~~ '/usr/share/python2.7/CXX' instead of '/usr/src/CXX'.

**Comment by tacaswell** [comment]
@mdboom This should be irrelevant now that you ripped pycxx out of the c++ layer?

Closing, please re-open if I am wrong.

**Comment by mdboom** [comment]
Yes -- this still affects 1.4.x, but beyond that is a non-issue now that PyCXX is gone.
