### ISSUE TITLE
[Bug]: `CbarAxesBase.toggle_label` doesn't seem to work properly

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23595]
### Bug summary

It appears as if `CbarAxesBase.toggle_label` and therefore, maybe, `SimpleAxisArtist.toggle` and possibly something else does not work as expected.

Probably related to the colorbar rewrite?

### Code for reproduction

https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_grid.html

### Actual outcome

The two middle figures have visible tick labels for the color bar.

### Expected outcome

No visible tick labels.

### Additional information

There seems to be some sort of mismatch between the `_axisnum` property and the location of the labels. It seems to work if the labels are located at the same side as the colorbar, i.e., right and bottom.

### Operating system

Arch

### Matplotlib Version

3.5.2 and `main`

### Installation

git checkout

**Comment by oscargus** [comment]
Marking as good first issue, but medium as it requires digging in how to modify the calls here (and possibly deprecating/replacing any other methods that may be affected).

**Comment by oscargus** [comment]
@vorbrodt Thanks for your interest! We do typically not assign persons to issues, but feel free to work on it anyway. Your note will most likely lead to people focusing on other issues instead,

**Comment by oscargus** [comment]
Just noting that there are some other demos that also use `toggle_label`, where it appears as the output is not really as expected:

https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_grid2.html
https://matplotlib.org/stable/gallery/axes_grid1/demo_edge_colorbar.html

Going back to 3.4.3, they probably are as expected:
https://matplotlib.org/3.4.3/gallery/axes_grid1/demo_axes_grid2.html
https://matplotlib.org/3.4.3/gallery/axes_grid1/demo_edge_colorbar.html
https://matplotlib.org/3.4.3/gallery/axes_grid1/demo_axes_grid.html

(Although demo_edge_colorbar.html seems to be missing a label on the left figure in all available versions of the documentation...)

**Comment by vorbrodt** [comment]
Okay, I see. I'll be working on this issue.

**Comment by oscargus** [comment]
The problem seems related to `self._axisnum` having the wrong value so https://github.com/matplotlib/matplotlib/blob/b298423d7e0e91aa1e844c3ccaf14bf48de7b222/lib/mpl_toolkits/axes_grid1/mpl_axes.py#L118-L120
is not correct.

**Comment by xtanion** [comment]
Hi @oscargus, I was trying to fix this issue...maybe `self._axisnum` isn't incorrect (As it is 1 for `bottom` and `left` axes & 2 for `top` & `right`). The issue seems to be related with the `colorbar` having two labels when it's set to `top` and `left`. I managed to solve it by disabling the bottom and right axes for both cases.  Is it the expected outcome?
![Figure_1](https://user-images.githubusercontent.com/74976752/224162351-0e1cd73f-cb72-4d41-a5e4-cfbc505d007e.png)

**Comment by anntzer** [comment]
Bisects to #20054.

**Comment by jklymak** [comment]
I don't quite understand how this can bisect to #20054?  That PR is for the normal colorbar axes, not the CbarAxes?

**Comment by anntzer** [comment]
cbaraxes ultimately uses normal colorbars (it's just an axes subclass that adds a colorbar() method *on the axes* to draw colorbars on that axes).
