### ISSUE TITLE
[MNT]: Only a subset of attributes set via `Axes.tick_params()` are accessible via public methods and attributes

### ISSUE THREAD

**Issue by stefmolin** [matplotlib/matplotlib#23603]
### Summary

Only a subset of attributes set via `Axes.tick_params()` are accessible via public methods and attributes. For example, `pad` is accessible via `get_pad()` on a `Tick` object, but if you want the width you have to access a private member `_width`. When building on top of Matplotlib, writing a test can sometimes require accessing these attributes to test the code, but ideally, we wouldn't need to access private members. For the [use case](https://github.com/mwaskom/seaborn/pull/2944) that came up, this isn't a big deal as I was able to switch to `get_pad()` for the test, but I was surprised there was no `get_width()` method like with other parts of the API.

**Comment by oscargus** [comment]
I guess that one can add a `get_tick_params()` method that returns a dictionary of all parameters? Or let `tick_params()` return it (although there will be a minor inconvenience as the default `axis='both'` should error).

**Comment by stefmolin** [comment]
Do you mean something like `Axes.xaxis.get_tick_params()`?

**Comment by timhoffm** [comment]
This is fundamentally a reasonable idea. There are some caveats however.

Basically, we need to return a copy of `Axis._major_tick_kw` / `Axis._minor_tick_kw` (which is what `tick_params` effectively does https://github.com/matplotlib/matplotlib/blob/069ab8704097bdfd9acda49310f6305030ee83ee/lib/matplotlib/axis.py#L937).

Note that these dicts only store deviations from the defaults. Only returning these would be different from getters of single properties. It would be cumbersome up to unfeasible, and maybe impractical to return the values for all tick properties. Note also that the setter `tick_params` does not cover all tick properties currently, and that maybe we won't always have a simple correspondence between `tick_params` and the individual tick properties  in the future (https://github.com/matplotlib/matplotlib/issues/20644#issuecomment-901939636).

As mentioned above `axis='both'` and possibly `which='both'` should error out.

**Comment by stefmolin** [comment]
@timhoffm - Are you suggesting that I add `Axes.get_tick_params()`, `Axis.get_tick_params()`, or both similar to how `Axis.set_tick_params()` and `Axes.tick_params()` are implemented?

**Comment by QuLogic** [comment]
Seems like this should be closed by #23692.
