### ISSUE TITLE
[Bug]: without Built Distributions wheel file, pip install failed on version 3.5.3

### ISSUE THREAD

**Issue by xuanqing** [matplotlib/matplotlib#23604]
### Bug summary

no wheel file for version 3.5.3
and got failure in install from source code

on platform: Win10, 64bit

### Code for reproduction

```python
pip install -U matplotlib
```

### Actual outcome

  Running setup.py install for matplotlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for matplotlib did not run successfully.
  │ exit code: 1
  ╰─> [562 lines of output]

      Edit mplsetup.cfg to change the build options; suppress output with --quiet.

.......

error: legacy-install-failure

× Encountered error while trying to install package.
╰─> matplotlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Expected outcome

Successfully installed matplotlib-3.5.3

### Additional information

there are wheel files for pre version like
[matplotlib · PyPI]( https://pypi.org/project/matplotlib/3.5.2/#files )
 but only a sdist file for version 3.5.3
[matplotlib · PyPI]( https://pypi.org/project/matplotlib/3.5.3/#files )

### Operating system

Windows 10 64bit

### Matplotlib Version

3.5.3

### Python version

3.10.5

### Installation

pip

**Comment by madhavajay** [comment]
+1 this is happening to me on Python 3.7 and Python 3.10 on Intel macOS.

**Comment by jrast** [comment]
I think this can be closed. The wheels have been uploaded just now: https://pypi.org/project/matplotlib/3.5.3/#files

**Comment by xuanqing** [comment]
wheel files upload on [matplotlib · PyPI]( https://pypi.org/project/matplotlib/3.5.3/#files )
Successfully installed matplotlib-3.5.3 with pip
