### ISSUE TITLE
[Bug]: Figure.colorbar triggers colormesh deprecation

### ISSUE THREAD

**Issue by mroeschke** [matplotlib/matplotlib#23614]
### Bug summary

xref https://github.com/matplotlib/matplotlib/issues/21723

In pandas, we have this matplotlib code calling `Figure.colorbar` which is triggering the colormesh deprecation:

```
Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.
```

https://github.com/pandas-dev/pandas/blob/03b4095f9de08af16db9698f15161b5a13a42286/pandas/plotting/_matplotlib/core.py#L1175-L1176

And calling `ax.grid(False)` does not address the deprecation

```
diff --git a/pandas/plotting/_matplotlib/core.py b/pandas/plotting/_matplotlib/core.py
index ee7493813f..69c749e84b 100644
--- a/pandas/plotting/_matplotlib/core.py
+++ b/pandas/plotting/_matplotlib/core.py
@@ -1172,6 +1172,7 @@ class PlanePlot(MPLPlot, ABC):
         # GH33389, if ax is used multiple times, we should always
         # use the last one which contains the latest information
         # about the ax
+        ax.grid(False)
         img = ax.collections[-1]
         return self.fig.colorbar(img, ax=ax, **kwds)
```

### Code for reproduction

```python
https://github.com/pandas-dev/pandas/blob/03b4095f9de08af16db9698f15161b5a13a42286/pandas/plotting/_matplotlib/core.py#L1175-L1176
```

### Actual outcome

`Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.`

### Expected outcome

No deprecation warning.

### Matplotlib Version

3.5.2

**Comment by timhoffm** [comment]
Please provide a minimal executable example that displays the behavior.

It seems that for some reason the colorbar axes got a grid, which is a bit unusual. We need the example to see how you are setting up the figure and be able to trace what is happening.

**Comment by oscargus** [comment]
I believe that this was fixed in #22216 and will be in 3.6.0. 

Most likely you have a style that sets the grid to be `True`.

**Comment by oscargus** [comment]
@mroeschke can you please try with the 3.6 rc and see if this is still an issue?

**Comment by mroeschke** [comment]
Sorry for the delay in responding. I just tested this with the 3.6.0rc and the warning disappeared. Thanks for the help!
