### ISSUE TITLE
[Bug]: unintended space between comma and digit when using useMathText = True together with comma as decimal separator

### ISSUE THREAD

**Issue by der-zi** [matplotlib/matplotlib#23626]
### Bug summary

When I turn on "useMathText" in matplotlib in the intention to replace 1e6 by $\times 10^6$, the formatting of the commas in the tick labels themselves get wrong. Before they are correct in the form "3,5", with "useMathText" they become "3, 5", with (half?) a whitespace between the comma and the following digit.
![correct_but_ugly_dec_power](https://user-images.githubusercontent.com/51455597/184684246-11786b6c-560a-4915-87d9-cd8ecd86d866.png)
![incorrect](https://user-images.githubusercontent.com/51455597/184684250-4f741478-53c8-476c-92af-457588945573.png)

### Code for reproduction

```python
%matplotlib inline
import locale
locale.setlocale(locale.LC_ALL, "deu_deu")
import matplotlib.pyplot as plt

plt.rcParams['axes.formatter.use_locale'] = True

fig, ax = plt.subplots()
x = [1000, 2000, 3000, 3.5e6]
y = [1, 4, 3, 5]
ax.plot(x, y, linestyle = "", marker = "o")
ax.set_xlabel("the x-axis")
ax.ticklabel_format(axis = 'x', useMathText = True)
```

### Actual outcome

the formatting of the decimal power is altered, but the ticklabels themselves are rendered incorrectly (additional space between comma and following digit)

### Expected outcome

the formatting of the decimal power is altered, and the ticklabels themselves are rendered correctly (as before adding useMathText = True)

### Additional information

apparently, matplotlib uses LaTeX to render the mathematical notation of power, and also changes the way the normal ticklabels are created to TeX mode.
however, when using comma as decimal separator in TeX you have to consider that it is written by americans, using the comma as an element separator, not decimal separator, and therefore in standard configuration automatically adds a space behind the comma.

this can be fixed by using 
3{,}5
 or 
3,\\!5 
or 
\num{3,5} or \num{3.5} with siunitx configured correctly 
or with the package icomma.

(Also, when already using the locale set to german, one could be expecting \cdot rather than \times. There should be an option to choose between these) 

### Matplotlib Version

3.5.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.7

### Jupyter version

6.4.10

### Installation

pip

**Comment by oscargus** [comment]
This is probably the place to fix it:

https://github.com/matplotlib/matplotlib/blob/d3038bfbe9a83a4b810f09555eb8570359de5ac2/lib/matplotlib/ticker.py#L531-L536

The main issue is most likely how to deal with format strings that already includes a `,`... Probably one should try and escape those somehow, replace `','` with `'{,}'` and get rid of the escapes.

**Comment by oscargus** [comment]
For `\cdot` vs `\times`, probably the most feasible way is to provide configuration using something like `rcParams['text.formatter.exponent_separator']` (or whatever a better name is).

**Comment by anntzer** [comment]
> The main issue is most likely how to deal with format strings that already includes a `,`

A possibility is perhaps to just copypaste the logic of python's format_string (https://github.com/python/cpython/blob/f7e7bf161aaec5a5cffdcec7c97e1f09e445421b/Lib/locale.py#L213), split out format specifiers and non-specifiers and brace-escape the non-specifiers.

**Comment by oscargus** [comment]
Marking as a good first issue, but medium, as it is well defined what should happen, but maybe not so straightforward to solve.

**Comment by evanandresen** [comment]
Currently working on this issue.

**Comment by evanandresen** [comment]
> This is probably the place to fix it:
> 
> https://github.com/matplotlib/matplotlib/blob/d3038bfbe9a83a4b810f09555eb8570359de5ac2/lib/matplotlib/ticker.py#L531-L536
> 
> The main issue is most likely how to deal with format strings that already includes a `,`... Probably one should try and escape those somehow, replace `','` with `'{,}'` and get rid of the escapes. Given that `self._useMathText` is True.

I have a quick fix PR ready to submit that changes the "," to "{,}" under the given conditions. I'm unsure how I would implement a pytest for this change. Is it necessary because it is a small and mostly visual change and if so does anyone have advice on what to assert?

**Comment by evanandresen** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/73536999/192863771-c474314f-abc6-43b8-90ed-6eb7d051fba4.png">

It looks like my fix actually messes up the xy values of the cursor location. What exactly is this feature of the plot called so I can find it in the code? (The plot element that shows the coordinates of the cursor)

**Comment by oscargus** [comment]
It is set with `set_message` and the formatting is done using `_mouse_event_to_message`. 

https://github.com/matplotlib/matplotlib/blob/a283d20f9d682543e40a3d5acb63f299aee92aa4/lib/matplotlib/backend_bases.py#L3044-L3072

**Comment by oscargus** [comment]
For the testing, it probably makes sense to have a parameterized test for a few locales (one using `,` and one using `.`).
https://docs.python.org/3/library/locale.html
Set up the locale, set up an Axes with relevant limits and check the tick labels. 

``` python
@pytest.mark.parametrize("loc, result", (('DE', (r'3,5 \times 10^3', ...))
def test_locale_comma(loc, result):
   locale.setlocale(locale.LC_ALL, loc)
  ...
  assert ... == result
```

Maybe even create a formatter that uses a `,` elsewhere and use that to check that it becomes correct (although it is, sort of, a quite unusual case).

**Comment by evanandresen** [comment]
Just writing the test now. Weirdly I'm getting different behavior in the test environment than my personal python program for testing. Under my own program I get the ticks as the coefficient of scientific notation...
<img width="175" alt="image" src="https://user-images.githubusercontent.com/73536999/193123477-2ae63c8d-a64e-46fc-86c2-6e60822a8837.png">
While in the pytest I've written I get the complete number 
![image](https://user-images.githubusercontent.com/73536999/193124437-421a42ff-2154-4341-8d06-b8decdfe622f.png)
Despite the code being as far as I can tell identical (same configuration)
<img width="472" alt="image" src="https://user-images.githubusercontent.com/73536999/193124390-d7819aad-a371-4616-8bd7-f23e96c2580b.png">
Is there a known reason why I am getting two different outcomes here?

**Comment by devRD** [comment]
Is anyone working on this issue? I would like to work on this issue following the discussion here and the discussion from #24079

**Comment by rcomer** [comment]
Thanks @devRD, it seems likely that #24079 has stalled, so I think it’s fine to pick this up if you are interested.  It would be good to bring it to a conclusion.
