### ISSUE TITLE
[MNT]: make.bat not parsing sphinxopt

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#23622]
### Summary

passing arguments to sphinx doesn't work, but [the documented way](https://matplotlib.org/devdocs/devel/documenting_mpl.html#documenting-matplotlib) is supposed to. Pretty sure it's that https://github.com/matplotlib/matplotlib/blob/a68f21f589b1747cccf30d2f9bd460bacf397003/doc/make.bat#L13 overwrites any input. Checked via

```cmd
> set SPHINXOPTS=-j4 -Dplot_gallery=0
> echo %SPHINXOPTS%
-j4 -Dplot_gallery=0
> make html
> echo %SPHINXOPTS%
-W
```
and yeah I tried `` and no quote versions

### Proposed fix

Amend `make.bat` so that it parses and correctly sets `SPHINXOPTS` arguments. <s>This is a medium good first issue in that it's self contained, but requires knowing how to write .bat files. </s>

**Comment by anntzer** [comment]
I think this should be fixed on sphinx's side, no?

**Comment by timhoffm** [comment]
I think

https://github.com/matplotlib/matplotlib/blob/a68f21f589b1747cccf30d2f9bd460bacf397003/doc/make.bat#L13

Is our addition. In fact, it seems like you added it

https://github.com/matplotlib/matplotlib/commit/b4b1f64275f26670056f23ef0c4e484ec66cadff

**Comment by anntzer** [comment]
What I mean is, it would be nicer if upstream's make.bat also supported SPHINXOPTS.

**Comment by story645** [comment]
Not sure if I'm parsing the discussion on https://github.com/sphinx-doc/sphinx/issues/3741 correctly, but it seems like it's won't fix on their side

**Comment by QuLogic** [comment]
With the `Makefile`, you use `O` to pass additional options, and only use `SPHINXOPTS` if you want to override our setting of `-W`. But the `make.bat` sets `O`, and I assume that overrides the outer environment.

Can we not just remove the `set O=` and suggest using `O` on both systems? (Obviously this doesn't help if you want to turn off `-W`)
