### ISSUE TITLE
[MNT]: Python 3.11 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [matplotlib/matplotlib#23645]
### Summary

Hello.

Could you please release CPython 3.11 manylinux wheels on PyPI?

Python 3.11.0 release candidate 1 was released: https://discuss.python.org/t/python-3-11-1rc1-is-now-available/18068/7

It should be quite safe to release wheels for the release candidate. ABI for Python 3.11 should be frozen from now on, even for bug fixes. From release notes:

    There will be no ABI changes from this point forward in the 3.11 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by oscargus** [comment]
The wheel building for 3.11 was merged yesterday #23637 so I guess that it should be quite straightforward for anyone with the right bits set (not me). There should if nothing else be nightly builds available "soon" (as soon as a 405-error is sorted out, see the 04:14 post today at https://gitter.im/matplotlib/matplotlib ).

**Comment by tacaswell** [comment]
We are planning to have wheels for 3.6 and going forward.  We have not historically gone back and made wheels for past release so I am going to close is done.
