### ISSUE TITLE
TTF fonts loaded from file are not embedded/displayed properly when saved to pdf

### ISSUE THREAD

**Issue by mkresch** [matplotlib/matplotlib#23650]
### Bug summary

With matplotlib 3.5.3, when using a font from a TTF file the font is not preserved when saving to pdf.  Display -- i.e. plt.show() -- and saving to .png seem to work just fine.

The [mistral font](https://ttfonts.net/font/1004_Mistral.htm) was used for the demo below.

### Code for reproduction

```python
#!/usr/bin/env python

import pathlib
import matplotlib.pyplot as plt

plt.text(0.2,0.5,"mistral",font=pathlib.Path("mistral.ttf"))

plt.savefig(f"mistral.png")
plt.savefig(f"mistral.pdf")
```

### Actual outcome
Note that you may have to download the pdf to see the lack of font while the correctly rendered png should appear below.  I've also attached a png screenshot of the pdf for easy reference.
[mistral.pdf](https://github.com/matplotlib/matplotlib/files/9365240/mistral.pdf)
![mistral_pdf_screenshot](https://user-images.githubusercontent.com/4021479/185217225-35a8d51a-ce0f-4a91-8a12-d9c0e508016b.png)
![mistral](https://user-images.githubusercontent.com/4021479/185214431-39227c7e-d4f8-4309-b774-5b1e6b005d42.png)

### Expected outcome

Both the .png and the .pdf should show the selected font (in this case, mistral).
[mistral_3.3.3.pdf](https://github.com/matplotlib/matplotlib/files/9365251/mistral_3.3.3.pdf)
![mistral_3 3 3](https://user-images.githubusercontent.com/4021479/185214762-a6417437-0cf7-4eef-a9d4-1f1c0fd8a9ad.png)

### Additional information

As seen in the expected outcomes, this worked in matplotlib-3.3.3.   I'm not sure about other versions.  I also tried with a number of different backends, including "pdf" and "TkAgg" and a few versions of python (3.9.x and 3.10.x).

### Operating system

Linux

### Matplotlib Version

3.5.3

### Matplotlib Backend

Qt5Agg

### Python version

3.9.13

### Installation

pip

**Comment by mkresch** [comment]
Thanks for speedy reply.
I just installed the nightly wheel (as per your link) and ran my test script and it seems to work fine.

**Comment by tacaswell** [comment]
I'm going to close this as fixed (even if we have not tracked down exactly what was wrong or when it was fixed).
