### ISSUE TITLE
[ENH]: 2D ball sympol like origin in marking

### ISSUE THREAD

**Issue by niubiworker** [matplotlib/matplotlib#23671]
### Problem

Recently, it was found that there is no option to draw bright dot spherical symbols in 2D during drawing. I don't know how to solve this problem

**Comment by story645** [comment]
Hi, this was discussed in https://discourse.matplotlib.org/t/is-there-a-way-to-draw-such-a-scatter-plot/21470 

Does the solution shown there work for you? 

Also I'm gonna close this since it's a duplicate of #8926. Feel free to follow up on the original issue or the discourse thread.

**Comment by niubiworker** [comment]
The discussion was very interesting, but it did not solve all the problems
