### ISSUE TITLE
[Bug]: barplot does not show anything when x or bottom start and end with NaN

### ISSUE THREAD

**Issue by Gullumluvl** [matplotlib/matplotlib#23687]
### Bug summary

I am not sure if this is a bug or an optimization, but in most cases it is fine to plot bars of arrays containing NaN (only the NaN values are not displayed, the rest is ok).

Here I found that when the `x` array or the `bottom` array have NaNs at the extremities, no bar is displayed.

(`barh` has the same behavior).

### Code for reproduction

```python
import numpy as np, matplotlib as mpl, matplotlib.pyplot as plt

barx = np.arange(3, dtype=float)
barheights = np.array([0.5, 1.5, 2.0])
barstarts=np.array([0.77]*3)

barx[[0,2]] = np.NaN
# alternatively:
#barstarts[[0,2]] = np.NaN

fig, ax = plt.subplots()

ax.bar(barx, barheights, bottom=barstarts)
# Not ok, nothing shown!

# Same behavior with ax.barh:
ax.barh(barx, barheights, left=barstarts)

# However, the behavior is correct when NaN only affect the 'heights' argument:

fig, ax = plt.subplots()
ax.bar(np.arange(3), np.array([np.NaN, 1, np.NaN]), bottom=np.array([0.2, 0.3, 0.4]))
# OK, one bar is displayed.
```

### Actual outcome

zero bar displayed

### Expected outcome

Non-NaN elements should be shown

### Operating system

Ubuntu 20.04.3

### Matplotlib Version

3.5.3

### Matplotlib Backend

TkAgg, pdf

### Python version

3.8.10

### Jupyter version

ipython

### Installation

pip

**Comment by tacaswell** [comment]
I can reproduce this, but do not understand it yet.

**Comment by tacaswell** [comment]
In 7c4b000c423c9e136da52d75ebecdcd312156a8f / https://github.com/matplotlib/matplotlib/pull/12903 we added some logic to make sure that width would work with interesting units, notable time deltas and and datetime data.

To do this we effective add the width to the first element of the x data, run it through the conversion machinery, and then subtract off the already converted value of the first data point to convert the "width" in (possibly unitful) user data into our internal version of it.  However, if the first point in `nan`, then the width is  poisoned to also be `nan` which means that when we make the `Rectangles` the x positions are `nan` which then (correctly) does not render anything.

**Comment by jklymak** [comment]
I guess we should be using the new safe_first_element excluding NaNs?

**Comment by tacaswell** [comment]
The new one only drops `None`, but I just finished adapting it to work with `nan` as well.  PR shortly....
