### ISSUE TITLE
[Bug]: `Axes.bar_label()` on log scale does not center the label.

### ISSUE THREAD

**Issue by stefmolin** [matplotlib/matplotlib#23688]
### Bug summary

When plotting on a log scale, if you pass `label_type='center'` to `Axes.bar_label()` the resulting labels are not centered in the bar, since the labels are being centered using the original base 10 scale.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
ax.bar_label(bar_container, label_type='center')
```

### Actual outcome

<img width="360" alt="Screen Shot 2022-08-20 at 6 07 03 PM" src="https://user-images.githubusercontent.com/24376333/185767610-d8e19e74-27bb-410e-8ad8-a9d7ebac77bc.png">

### Expected outcome

I was expecting the labels to be in the center of the bar.

### Additional information

The label should be placed using figure coordinates rather than data coordinates. I'm not sure how to get that information from the rectangles though.

### Operating system

M1 Mac

### Matplotlib Version

main branch

### Installation

git checkout

**Comment by tacaswell** [comment]
https://matplotlib.org/stable/tutorials/text/annotations.html#using-complex-coordinates-with-annotations I think you want to use option 2 in that section and place the text relative to the bounding box of the rectangle.

The back-compatibility on this may require some thought.

**Comment by stefmolin** [comment]
@tacaswell - Did you mean something like this?

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
for bar in bar_container:
    ax.annotate(f'{bar.get_width():,d}',
                xy=(0.5, 0.5), xycoords=bar,
                xytext=(0, 0), textcoords='offset points',
                ha='center', va='center')
```

This only seems to work if the `x` in `xy` is 1, as I can move the text vertically by changing the `y` and the result is as expected. However, if I change the `x` value to 0.5 to place it halfway along the bar, nothing shows up, and if I do 0.99 the text is way beyond the beginning of the x-axis:
<img width="931" alt="Screen Shot 2022-08-21 at 11 27 43 AM" src="https://user-images.githubusercontent.com/24376333/185798542-69382a88-95d5-4c61-8578-f8c7b2ef5bf8.png">

**Comment by tacaswell** [comment]
Oh, that makes sense. The bounding bax it is using is not clipped so the left edge is way off the the left at where ever the very small number we clip 0 up to in log scale is.  Same log problem, but from the other side.....

**Comment by anntzer** [comment]
The following (which was made easy by your debugging above!) seems to work:
```python
from matplotlib.transforms import Bbox
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
for bar in bar_container:
    ax.annotate(
        f'{bar.get_width():,d}',
        xy=(0.5, 0.5),
        xycoords=lambda r, b=bar: Bbox.intersection(b.get_window_extent(r), b.get_clip_box()),
        xytext=(0, 0), textcoords='offset points',
        ha='center', va='center')

plt.show()
```

**Comment by stefmolin** [comment]
Thanks @anntzer &ndash; I'm glad my debugging helped get to the bottom of this. Can I put in a PR to update `Axes.bar_label()` to properly handle the `label_type='center'` going forward? Unless this is something you don't want in the API, it seems more robust than what is already there and I imagine the logic will work for any axis scale.

**Comment by anntzer** [comment]
Seems good to me (although I admittedly haven't followed the whole discussion).
