### ISSUE TITLE
[ENH]: Add f-string formatting to labels in `Axes.bar_label()` 

### ISSUE THREAD

**Issue by stefmolin** [matplotlib/matplotlib#23689]
### Problem

I would like to be able to use a format string like `,d` to format bar labels with commas for the thousands separators.

### Proposed solution

Update the `fmt` parameter to also accept f-string style formats. To format the label, we first check what kind of format is provided and call `fmt.format(value)` or `fmt % value` accordingly.

**Comment by stefmolin** [comment]
I've opened PR https://github.com/matplotlib/matplotlib/pull/23690 with my proposed solution implemented. I will go back and complete the rest of the tasks (docstrings, tests, etc.) once it's decided whether to move forward with this.

**Comment by timhoffm** [comment]
Closed by #23690.
