### ISSUE TITLE
[MNT]: Use mpl.rcParams internally

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#23680]
### Summary

Originally mentioned in https://github.com/matplotlib/matplotlib/issues/16181#issue-548352957

Don't import `rcParams` into matplotlib modules directly:

```
# NO:
from matplotlib import rcParams
...
rcParams[...]
```
This has the disadvantage that `rcParams` get into the module namespace and people easily start using that (e.g. `from matplotlib import cm; cm.rcParams`).

Instead use
```
# YES:
import matplotlib as mpl
...
mpl.rcParams[...]
```
While in theory people could still access it via `mpl` (e.g. `cm.mpl.rcParams`), this is far more unlikely and good enough for us. - We also don't shield other module imports.

Note: It's also ok to use `plt.rcParams` if you happen to have pyplot anyway and would have to import mpl. This is in particular true for examples. But most matplotlib modules should not depend on `pyplot`.

There are many places in the library that need fixing, so it's ok to do this step-by-step.

Related PRs:

- #16406
- #16525
- #16780
- #23676
- #23678

**Comment by oscargus** [comment]
Great! I seem to recall that I saw this somewhere, but couldn't recall where.

**Comment by oscargus** [comment]
Maybe we should consider a test for this to make sure that it is not accidentally added again?

**Comment by timhoffm** [comment]
> Maybe we should consider a test for this to make sure that it is not accidentally added again?

Feel free to do that if you like. However, it's not super important.

**Comment by timhoffm** [comment]
This is done. I don't think we need the effort for a test.
