### ISSUE TITLE
[Doc]: scatter points

### ISSUE THREAD

**Issue by niubiworker** [matplotlib/matplotlib#23700]
### Problem

what is mean the marker size in points**2 in scatter, I do not understand it.

**Comment by jklymak** [comment]
If you set the size to 10 then the diameter is 2 * sqrt(10 / pi) = 3.56 points.  One point is 1/72 inch.

**Comment by niubiworker** [comment]
> 

if I set the dpi=720, how long the diameter? thank you!

**Comment by oscargus** [comment]
It is still 3.56 points = 3.56/72 = 0.049 inches = 1.2 mm. With 720 dpi it should be 35.6 dots.

**Comment by niubiworker** [comment]
ok, thank you!

**Comment by story645** [comment]
I think the actionable next step would be to amend `the marker size in points` to `the marker size in typographic points (1/72 in)`, 
https://github.com/matplotlib/matplotlib/blob/36f27457d7781c0dbb6da3b875e98f0a3fac0f64/lib/matplotlib/axes/_axes.py#L4392-L4394

Honestly not sure though if we want to do that or if a better solution is to set up a glossary page (which was removed in #18696 but then specific to backends) to cross link these types of things against.

**Comment by timhoffm** [comment]
I think the local addition is the simpler solution for now.
