### ISSUE TITLE
[Bug]: pyplot.savefig(..., bb_inches='tight') raises MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by macraild** [matplotlib/matplotlib#23703]
### Bug summary

pyplot.savefig(..., bb_inches='tight') raises MatplotlibDeprecationWarning, but this deprecation is not documented anywhere I can find

### Code for reproduction

```python
plt.plot([0,1], [0,1])
plt.xlabel("A multiline\naxis label")
plt.savefig('test.svg', bb_inches='tight')
```

### Actual outcome

 MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bb_inches" which is no longer supported as of 3.3 and will become an error in 3.6

and the axis label falls outside of the bounding box

### Expected outcome

A documented deprecation, with some indication of how to force plt.savefig() to use a bounding box consistent with the figure

### Matplotlib Version

matplotlib-3.5.3

### Matplotlib Backend

QtAgg

**Comment by oscargus** [comment]
I think that you want to pass `bbox_inches='tight'`? 

(The deprecation is, if I understand it correctly, that `savefig` no longer "swallows" incorrect arguments, but actually warns/errors.)

**Comment by macraild** [comment]
Ooops. Thanks for the clarification
