### ISSUE TITLE
test_Normalize fails on aarch64/ppc64le/s390x

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#23707]
https://github.com/matplotlib/matplotlib/blob/4cf54f4f837a3ba974f9fac9255dc0db227064bc/lib/matplotlib/tests/test_colors.py#L577-L579

This seems to be a bit too strict now, as it is failing on aarch64, ppc64le, and s390x, where the result is 0.50096339.

Also, on my 64-bit AMD system, which is apparently using `np.float128` for `np.longdouble` (though I don't know if that means 80-bit internally), it seems to return 0.5 exactly, which seems the opposite of the comment.

_Originally posted by @QuLogic in https://github.com/matplotlib/matplotlib/pull/21634#discussion_r951848616_

**Comment by QuLogic** [comment]
On my (64-bit AMD) system, we have this precision info:
```
>>> np.finfo(np.longdouble)
finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)
```
On aarch64, ppc64le, and s390x, it is:
```
>>> np.finfo(np.longdouble)
finfo(resolution=1e-33, min=-1.189731495357231765085759326628007e+4932, max=1.189731495357231765085759326628007e+4932, dtype=float128)
```

So I guess that `resolution` difference explains the comment at least.

But that means the test needs some loosening. However, I'm not sure why the nightly tests precipitated this change, @greglucas.

**Comment by greglucas** [comment]
I _think_ that the necessary change was above that update and I was updating the area and saw that we were only testing that was between `0 < x < 1` which seemed way too loose to me. So, it seems fine to loosen this back up again if it is causing issues on other platforms.
