### ISSUE TITLE
[Bug]: register_cmap deprecation message seems wrong

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#23719]
### Bug summary

See title

### Code for reproduction

```python
import matplotlib as mpl
mpl.cm.register_cmap("test", mpl.colors.ListedColormap(["C0", "C1"]))
```

### Actual outcome

```
PendingDeprecationWarning: The register_cmap function will be deprecated in a future version.
Use ``matplotlib.colormaps.register_cmap(name)`` instead.
```

### Expected outcome

I think there's two problems here:
- The function is called `matplotlib.colormaps.register`
- The signature for that function is `mpl.colormaps.register(cmap, *, name=None, force=False)`

### Matplotlib Version

3.6.0.rc1

**Comment by tacaswell** [comment]
This is already fixed in #23710
