### ISSUE TITLE
[ENH]: How about update freetype to 2.12.1

### ISSUE THREAD

**Issue by wqh17101** [matplotlib/matplotlib#23723]
### Problem

FreeType 2.10.4 released on 2020-10-20. It is better for us to update
![image](https://user-images.githubusercontent.com/26429138/186308099-fc75f3b9-5066-4fd3-8666-c531b59bea21.png)

**Comment by anntzer** [comment]
See discussion at https://github.com/matplotlib/matplotlib/issues/20842 for why this is not done.

**Comment by rwmajor2** [comment]
@tacaswell How do we build against a specific version?

**Comment by tacaswell** [comment]
@rwmajor2 Please see https://matplotlib.org/stable/devel/dependencies.html#c-libraries for how to use system libraries.  If you want the mpl build system to download and build a specific version, patchhttps://github.com/matplotlib/matplotlib/blob/0640e720b3856d177a3c2f0e332658f59e38625f/setupext.py#L151-L193
