### ISSUE TITLE
[Bug]: 3.5.2 in IPython does not update plots

### ISSUE THREAD

**Issue by aaronm6** [matplotlib/matplotlib#23720]
### Bug summary

When running IPython (using python v3.9) and invoking the `--matplotlib` option to initiate interactive mode, a feature is broken in going from mpl 3.5.1 to 3.5.2.  Whenever one creates a figure and executes plot statements (and other statements that changes the plot like xlabel), the figure should be updated automatically.  This works successfully with >=3.5.1.  However, with 3.5.2, whenever a change is made the only way to get the plot to update is to click the pan or zoom tool.  

It's not clear to me whether the issue is with matplotlib or IPython, but the problem goes away when I revert to matplotlib 3.5.1.

### Code for reproduction

```python
$ ipython3-3.9 --matplotlib
Python 3.9.13 (main, May 21 2022, 02:36:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: MacOSX

In [1]: import matplotlib.pyplot as plt

In [2]: plt.figure() # figure is created successfully
Out[2]: <Figure size 1280x960 with 0 Axes>

In [3]: plt.plot([1,2,3],'.') # no visual change to figure window, unless pan/zoom tool is used.
Out[3]: [<matplotlib.lines.Line2D at 0x129db4160>]

In [4]: plt.xlabel('x axis') # no visual change to figure window, unless pan/zoom tool is used.
Out[4]: Text(0.5, 0, 'x axis')

In [5]: plt.ylabel('y axis') # no visual change to figure window, unless pan/zoom tool is used.
Out[5]: Text(63.31944444444443, 0.5, 'y axis')

In [6]: plt.show()  # no effect
```

### Actual outcome

Graphical issue; no stdout/stderr

### Expected outcome

At each line in the code example, the expected behavior (as with <=3.5.1) is that the open figure will update with the given command.

### Operating system

macOS v11.6.8

### Matplotlib Version

3.5.2

### Matplotlib Backend

MacOSX

### Python version

3.9

### Jupyter version

(not using jupyter)

**Comment by QuLogic** [comment]
Have you tried with 3.5.3?

**Comment by greglucas** [comment]
I can verify this does fail on 3.5.2, but works as expected on 3.5.3 and main.
