### ISSUE TITLE
Quiver not Shown until change view 3D

### ISSUE THREAD

**Issue by DRLing2021** [matplotlib/matplotlib#23736]
### Bug summary

It is planned to show a quiver when mouse pick a point from a 3D scatter collection in our project. Because the 3D scatter size is large, about 40,000 pt today and will be as large as 4M pt in real life, the canvas.show() does not perform fast enough. What we are doing is use quiver.draw and canvas flush_event to replace the canvas.draw()  for a faster screen update when mouse pick a point. The part of the code looks like following:

        my_qvr = self.axes.quiver(px_flat, py_flat, pz_flat, u, v, w, colors ="r") #length=0.1, normalize=True) 
        vv = my_qvr.get_visible()
        print("visible is ",vv)
        self.rdrer = self.canvas.get_renderer()
        my_qvr.draw(self.rdrer)  ## no effect 
        self.canvas.update()
        # self.canvas.draw()
        self.canvas.flush_events()

Unfortunately after replacement the quiver will not appear until we mouse drag the 3D scatter plot with a view change. Do you have any idea about the weird result? Any walk around is appreciated.   

### Code for reproduction

```python
my_qvr = self.axes.quiver(px_flat, py_flat, pz_flat, u, v, w, colors ="r") #length=0.1, normalize=True) 
        print("--- type of quiver is ",type(my_qvr))
        self.canvas.blit(self.fig.bbox)
        vv = my_qvr.get_visible()
        print("visible is ",vv)
        self.rdrer = self.canvas.get_renderer()
        my_qvr.draw(self.rdrer)  ## no effect 
        # my_qvr.update()
        # self.axes.draw(my_qvr)  ## not working,quiver is not draw -aable
        draw_list = self.axes.get_children()
        print("draw list is ",draw_list)
        # self.axes.redraw_in_frame()  ## poor performance
        self.canvas.update()
        # self.canvas.draw()
        self.canvas.flush_events()
```

### Actual outcome

No display of quiver. 

### Expected outcome

Quiver displayed 

### Operating system

Windows

### Matplotlib Version

3.5.3

### Matplotlib Backend

QtAgg

### Python version

3.8.3

### Jupyter version

6.0.3

### Installation

pip

**Comment by tacaswell** [comment]
I think that https://matplotlib.org/stable/tutorials/advanced/blitting.html will provide guidance on achieving what you want. 

The very short version is that we are effectively doing double-buffering, `my_qvr.draw(self.rdrer)` updates Matplotlib's internal state of what the rasterized version of the Figure is, but there is a second step to copy that buffer to the GUI widget (and hence the screen for you to see).  In addition to calling `obj.draw(...)` you will also need to manage the "clean" snapshot and restore it or you will see the overlay of all the times you click.

I am going to close this because I think all of the tools you need exist and are documented.  Please ping to have this re-opened if you think there is a bug and open an issues on https://discourse.matplotli.org if you need additional support!

**Comment by DRLing2021** [comment]
Hi Thomas,

Thank you for your prompt response! 

I beleive you meant the following two steps to be added into our codes: 

 1.1 ==>   bg = self.canvas.copy_from_bbox(self.fig.bbox)
        my_qvr = self.axes.quiver(px_flat, py_flat, pz_flat, u, v, w, colors ="r") #length=0.1, normalize=True) 
        self.canvas.blit(self.fig.bbox)
        self.rdrer = self.canvas.get_renderer()
        my_qvr.draw(self.rdrer)  ## no effect 
 2 ==>    self.axes.draw_artist(my_qvr)  ## not working 
 1.2 ==>  self.canvas.restore_region(bg)
        self.canvas.update()
        # self.canvas.draw()
        self.canvas.flush_events()

The code run withou erro but the issue still exits.  


***@***.***
 
From: Thomas A Caswell
Date: 2022-08-26 02:53
To: matplotlib/matplotlib
CC: DRLing2021; Author
Subject: Re: [matplotlib/matplotlib] Quiver not Shown until change view 3D (Issue #23736)
I think that https://matplotlib.org/stable/tutorials/advanced/blitting.html will provide guidance on achieving what you want.
The very short version is that we are effectively doing double-buffering, my_qvr.draw(self.rdrer) updates Matplotlib's internal state of what the rasterized version of the Figure is, but there is a second step to copy that buffer to the GUI widget (and hence the screen for you to see). In addition to calling obj.draw(...) you will also need to manage the "clean" snapshot and restore it or you will see the overlay of all the times you click.
I am going to close this because I think all of the tools you need exist and are documented. Please ping to have this re-opened if you think there is a bug and open an issues on https://discourse.matplotli.org if you need additional support!
―

**Comment by jklymak** [comment]
Please follow up on https://discourse.matplotlib.org thanks!

**Comment by DRLing2021** [comment]
Hi Thomas,

Thank you for your prompt response! 

I beleive you meant the following three steps (1.1,1,2 and 2) to be added so that the  buffer is copied to the GUI widget and the background is restored.

 1.1 ==>   bg = self.canvas.copy_from_bbox(self.fig.bbox)
        my_qvr = self.axes.quiver(px_flat, py_flat, pz_flat, u, v, w, colors ="r") #length=0.1, normalize=True) 
        self.canvas.blit(self.fig.bbox)
        self.rdrer = self.canvas.get_renderer()
        my_qvr.draw(self.rdrer)  ## no effect 
 2 ==>    self.axes.draw_artist(my_qvr)  ## not working 
 1.2 ==>  self.canvas.restore_region(bg)
        self.canvas.update()
        # self.canvas.draw()
        self.canvas.flush_events()

The above codes run without error but the issue still exits. I share the following screen copy as following. Step0 establishes the base, the 3D scatter; then pick three points on it, you got the one looks same as step0 without any change; finally after use mouse to change the view slightly, you got three quivers appeared. The supposed result is to display the quivers at step2 immediately. 


![base](https://user-images.githubusercontent.com/112079246/186789550-5f9cb04c-90d1-4d67-aae9-e9886d2cc02f.png)
![pick_3](https://user-images.githubusercontent.com/112079246/186789554-79c7de20-5594-4ad9-9f0a-86b3176ef1aa.png)
![pick_3_+_change_view](https://user-images.githubusercontent.com/112079246/186789557-081546b6-2213-4101-bb7d-c29d51a61fa0.png)

**Comment by tacaswell** [comment]
@DRLing2021 Can we please move this to discourse?  Make sure to include a runnable example when you post there.  It is much easier to help if we can copy-paste-run the code.

**Comment by DRLing2021** [comment]
Sure. Will do

**Comment by DRLing2021** [comment]
@tacaswell Update discourse. Forgive us since I am a new user to both platforms.

**Comment by DRLing2021** [comment]
As a new user I am not sure if put it on the right place at discourse. I paste the link here just in case: [Https://github.com/matplotlib/matplotlib/issues/23736# follow up - Quiver not shown until a view change](https://discourse.matplotlib.org/t/https-github-com-matplotlib-matplotlib-issues-23736-follow-up-quiver-not-shown-until-a-view-change/23083)

**Comment by jklymak** [comment]
Hopefully someone will help you on discourse.  However we are a volunteer based organization so you will need to wait for someone to take an interest.
