### ISSUE TITLE
matplotlib 1.3.0 doesn't compile with Solaris Studio 12.1 CC

### ISSUE THREAD

**Issue by podlipnik** [matplotlib/matplotlib#2375]
# python setup.py build
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.3.0]
                python: yes [2.6.4 (r264:75706, Jun 26 2012, 21:27:36) [C]]
              platform: yes [sunos5]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.7.1]
              dateutil: yes [using dateutil version 2.1]
               tornado: yes [using tornado version 3.1.1]
             pyparsing: yes [using pyparsing version 2.0.1]
                 pycxx: yes [Couldn't import.  Using local copy.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 14.1.8]
                   png: yes [version 1.2.49]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt4agg: no  [PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: yes [version 73770]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: yes [version 9.00]
                 latex: no
               pdftops: yes [version 0.14.4]

/usr/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'use_2to3'
  warnings.warn(msg)
running build
running build_py
copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.solaris-2.10-i86pc-2.6/matplotlib/mpl-data
running build_ext
building 'matplotlib.ft2font' extension
/usr/lib/python2.6/pycc -DNDEBUG -KPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DPYCXX_ISO_CPP_LIB=1 -I/usr/local/include -I. -I/usr/sfw/include -I/usr/sfw/include/freetype2 -I/usr/lib/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/ft2font.cpp -o build/temp.solaris-2.10-i86pc-2.6/src/ft2font.o
CC: Warning: Option -fPIC passed to ld, if ld is invoked, ignored otherwise
"/usr/sfw/include/freetype2/freetype/config/ftconfig.h", line 83: Warning (Anachronism): Attempt to redefine SIZEOF_LONG without using #undef.
"src/ft2font.h", line 84: Error: PythonClass may not have a type qualifier.
"src/ft2font.h", line 84: Error: Py::PythonClass<Py::T> cannot be initialized in a constructor.
"src/ft2font.h", line 84: Error: Could not find Py::PythonClass<Glyph>::PythonClass() to initialize base class.
"/usr/lib/python2.6/site-packages/numpy/core/include/numpy/ndarraytypes.h", line 209: Warning: Identifier expected instead of "}".
"src/ft2font.cpp", line 849: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1021: Warning: ptsize hides FT2Font::ptsize.
"src/ft2font.cpp", line 1022: Warning: dpi hides FT2Font::dpi.
"src/ft2font.cpp", line 1024: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1328: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1378: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1738: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1789: Warning: error hides FT2Font::error.
"src/ft2font.cpp", line 1992: Warning: angle hides FT2Font::angle.
"src/ft2font.cpp", line 2070: Warning: error hides FT2Font::error.
3 Error(s) and 12 Warning(s) detected.
error: command '/usr/lib/python2.6/pycc' failed with exit status 3
# 

Looks like this is still not fixed. Any idea how to get matplotlib compiled on Solaris 10 x86?

Borut

**Comment by tacaswell** [comment]
Has anyone with a solaris box tried to recompile with 1.5.0?  There were some pretty major refactoring of the c++ wrapping layer and minor refactoring it `_try`

**Comment by mdboom** [comment]
I used to have access to Solaris at STScI, but even they were phasing it out.

**Comment by joan-smith** [comment]
I'm no longer working on Solaris machines, so haven't tried with a more recent version. Sorry!

**Comment by efiring** [comment]
This looks like a case of "can't fix it", and declining importance as Solaris machines become less common.  Closing.
