### ISSUE TITLE
[Bug]: Spines clipped in ps backend with `usetex=True` saving as eps

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23776]
### Bug summary

When saving a wide eps with `text.usetex=True`, the spine is clipped, but no other artists.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.rcParams['text.usetex']=True
plt.figure(figsize=(20, 4))
plt.plot([0, 1], [0, 1], 'b')
plt.savefig('clippedspine.eps')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/8114497/187451212-edaa687a-22df-4835-bb8b-e184f4468a0b.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/8114497/187451513-c8fe6248-c493-4f52-84ef-cc3cc8745b51.png)

### Additional information

Expected output not using `usetex`.

Saving as ps stores using letter paper, so the whole paper is clipped.

The line is just there to illustrate that lines are not clipped as such (nor are texts).

It seems like the spine covers the same absolute width when changing figure width.

### Operating system

CentOS

### Matplotlib Version

3.6.0.dev3474+g8179d12.d20220830

### Python version

3.8.13

### Installation

git checkout

**Comment by tacaswell** [comment]
I assume this is a very old bug so tagging for 3.7.

**Comment by oscargus** [comment]
This is a consequence of distilling. If using #23775 and removing the tick labels one do get the correct results. Also, saving as ps, the whole image is not clipped to letter sized paper (which it is in current main).

Possibly related issues: #22291 #22416

**Comment by oscargus** [comment]
It seems like the lines are actually of correct length in the eps, drawn to x-position 16300 where they are not visible beyond x-position ~5000.

**Comment by oscargus** [comment]
It may be that this is actually a rendered issue with gsview. Trying now again with evince, it seems to work correctly.
