### ISSUE TITLE
[Doc]: Version switcher broken in devdocs

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23794]
### Documentation Link

https://matplotlib.org/devdocs/index.html

### Problem

A / is missing so switching to e.g. stable gives `https://matplotlib.org/stableindex.html`.

Marking as rc as I assume that the idea is to include the version switcher in 3.6?

### Suggested improvement

Add the missing / (I have no idea where unfortunately...).

**Comment by oscargus** [comment]
Now, going to 3.6.0, say https://matplotlib.org/3.6.0/devel/index.html it seems like the version switcher goes to the main page of that version, not the same page with different version as above.

Also, it seems like the logo in the top right corner points at the same page one is currently visiting, not the main page.

**Comment by oscargus** [comment]
cc: @melissawm as some of these may be consequences of #23225?

**Comment by jklymak** [comment]
Yeah, its interesting - it works for the release candidate...

**Comment by melissawm** [comment]
It looks like the links are missing a `/` - this should be fixed by #23835. 

> Also, it seems like the logo in the top right corner points at the same page one is currently visiting, not the main page.

Can you clarify which logo? Clicking on the matplotlib logo brings me to the main page, so I may be missing something.
