### ISSUE TITLE
[Bug]: skip nan in the beginning of the array

### ISSUE THREAD

**Issue by Freed-Wu** [matplotlib/matplotlib#23797]
### Bug summary

<https://github.com/piccolomo/plotext/issues/114#issuecomment-1234299418>

I am not sure if it is a bug or an expected behaviour.

### Code for reproduction

```python
from matplotlib import pyplot as plt
y = plt.sin()
import numpy as np
y[:40] = [np.nan] * 40
plt.scatter(y)
plt.show()
```

### Actual outcome

Actual: A plot which x range is [40, 200].

### Expected outcome

Expected: A plot which x range is [0, 200], but [0, 40] don't have any number.

### Matplotlib Version

3.5.2

### Installation

Linux package manager

**Comment by tacaswell** [comment]
I think this is actually an autoscaling issue rather than a bug in how we handle nans.

I would have to check the code to be completely sure, but I think we auto-scale based on valid points, if there is a `nan` in the y-value it is not a valid point so we are auto-scaling the x limits to show you the valid data.  The alternative of using different subsets of the data to autoscale the x and y directions seems like it would be more confusing.

I think if you set `ax.set_xlim(0, len(y))` you will get what you expect?

**Comment by Freed-Wu** [comment]
```python
import matplotlib.pyplot as plt
from plotext import sin
y = sin()
import numpy as np
y[:40] = [np.nan] * 40
fig, ax=plt.subplots()
plt.scatter(range(len(y)), y)
ax.set_xlim(0, len(y))
plt.show()
```

> I think if you set ax.set_xlim(0, len(y)) you will get what you expect?

Right. :smile:

**Comment by tacaswell** [comment]
@Freed-Wu Are you OK closing this issue?  Although I am biased to current behavior, I do see case for the behavior you expected.  However, changing the behavior now would be a backwards incompatible change (and someone who is relying on the current behavior will report we broke their plotting) and the ways I (on only a bit of thought) see to configure how the autoscaling work are both very complicated on the Matplotlib side and only marginally easier than you explicitly setting the limits.

**Comment by Freed-Wu** [comment]
Thanks!

**Comment by tacaswell** [comment]
@Freed-Wu You should also consider adding plotext to https://matplotlib.org/mpl-third-party/ and use the Matplotlib classifier (instructions on how to do bothe are at the top of that page).

**Comment by Freed-Wu** [comment]
Plotext doesn't require matplotlib as its dependence, I concern it is right? @piccolomo

**Comment by piccolomo** [comment]
> Plotext doesn't require matplotlib as its dependence, I concern it is right? @piccolomo

True, but I could consider adding it to https://matplotlib.org/mpl-third-party/ if @tacaswell thinks it is useful.

**Comment by tacaswell** [comment]
I leave it to you. I did not dig too deeply and inferred from linked bug report that you used Matplotlib.  If think of the plotex as a Matplotlib extension add your self, if you think of it as a stand-alone-thing that happens to use Matplotlib then it seems reasonable to not add yourself.
