### ISSUE TITLE
[ENH]: Colorbar based on `Artists`

### ISSUE THREAD

**Issue by Mr-Milk** [matplotlib/matplotlib#23793]
### Problem

When creating multiple elements on one figure, we need to create multiple legends and colorbars. It's possible to layout multiple legend instances using `Packer` since it's based on `Artist`. However, it's difficult to layout colorbar with legend since colorbar is `Axes`. Therefore, adding a colorbar implementation based on `Artist` can benefit users in two ways:
1. Position colorbar like legend
2. Align and layout colorbar with legend

**Use case**:
This is an example from R package [complexHeatmap](https://github.com/jokergoo/ComplexHeatmap)
![unnamed-chunk-3-1](https://user-images.githubusercontent.com/23433306/187864090-2debcb85-d926-4d68-9287-3964b466fb85.png)

**Comment by timhoffm** [comment]
I suppose basing a colorbar on an Artist ist really difficult. 

Alternatives to consider:
- be able to place an Axes inside an Artist.
- Better layout for Axes. - In fact, maybe this can already achieved by using [subfigures](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subfigures.html).

**Comment by jklymak** [comment]
I'm not really following this request. Axes are Artists, so it would be helpful if you explained what behaviour you want that is not currently obtainable, preferably with specific examples.

**Comment by Mr-Milk** [comment]
@timhoffm For this use case, I think placing `Axes` inside `Artist` may be a good solution. The example I showed can be achieved with `subfigures` but may need a lot of tweaks to get the desired result. It's not as easy to use as grouping using `Packer`.

**Example**:

If I want to group the two legends below together.

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
from matplotlib.patches import Patch

fig, ax = plt.subplots()

legend1 = Legend(ax, 
                handles=[Patch(), Patch()], 
                labels=["Item 1", "Item 2"], loc="upper right")
legend2 = Legend(ax, 
                handles=[Patch(color="r"), Patch(color="r")], 
                labels=["Item 1", "Item 2"], loc="lower right")

ax.add_artist(legend1)
ax.add_artist(legend2)
```
![download](https://user-images.githubusercontent.com/23433306/188046493-ede1d28a-787a-477a-a0e3-3ad92573a671.png)

I can use the offsetbox to group them so I don't have to position them one by one.

```python
from matplotlib.offsetbox import HPacker, AnchoredOffsetbox

fig, ax = plt.subplots()

legend1 = Legend(ax, 
                handles=[Patch(), Patch()], 
                labels=["Item 1", "Item 2"], loc="upper right")
legend2 = Legend(ax, 
                handles=[Patch(color="r"), Patch(color="r")], 
                labels=["Item 1", "Item 2"], loc="lower right")
pack = HPacker(sep=5, pad=5,
               children=[
                   legend1.get_children()[0], 
                   legend2.get_children()[0]
               ])

pack_legend = AnchoredOffsetbox(child=pack, loc="upper right")
ax.add_artist(pack_legend)
```
![download](https://user-images.githubusercontent.com/23433306/188047054-20a37575-f743-4fe3-975a-23ea0fbde771.png)

However, if I want to place the colorbar with legend. (Like what's shown in the use case)

```python
fig, ax = plt.subplots()
pcm = ax.pcolormesh(np.random.random((10, 10)), cmap='RdBu')
cb = fig.colorbar(pcm, ax=ax)
cb.remove()

legend = Legend(ax, handles=[Patch()], labels=["Item 1"])
pack = HPacker(children=[cb.ax, legend], pad=0, sep=0)
pack_legend_cbar = AnchoredOffsetbox(child=pack, loc="upper right")
ax.add_artist(pack_legend_cbar)
```

This will raise an error : `AttributeError: 'AxesSubplot' object has no attribute 'get_extent'`.

**Comment by Mr-Milk** [comment]
Sorry, I'm not familiar with the render cycle, but judging from the trackback, implementing the `get_extent` for the `Axes` class maybe a good start, this may also require the method is implemented for every element that can be put within the `Axes` (Every subclass of `Artist`?).

**Comment by jklymak** [comment]
I think legends are packable containers hence you can pack them.  Most artists are not pickable, but you can wrap them in a container to make them packable. I'd suggest that approach, rather than trying to make all arbitrary artists have a get_extent.   Most artists already have get_window_extent and/or get_tightbbox.  I'd be very skeptical of attempting to add a new type of extent.

**Comment by Mr-Milk** [comment]
It's acceptable to manually adjust one or two, but if I have many legends and colorbar for a plot with many parts, it would be better to have them layout automatically.

Like this:
![image](https://user-images.githubusercontent.com/23433306/188258913-545ba2f6-6d92-44c0-82bc-a2c9cee08e6d.png)

**Comment by jklymak** [comment]
It will be a challenge to come up with an API to do something like that "automatically".  But regardless, if you want to try, wrap your colorbar in a DrawingArea, which accepts an arbitrary artist.  Do not try and make axes or colorbars directly a subclass of Container, as that is mixing paradigms.

**Comment by Mr-Milk** [comment]
I tried following code, which wraps the axes of colorbar in the `DrawingArea`. However, the axes can't properly render. It somehow rerender the colorboar again in the same axes twice and leave empty axes in the last axes.

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.offsetbox import DrawingArea, AnchoredOffsetbox

fig, (ax1, ax2, ax3) = plt.subplots(1, 3)

c = ax1.pcolormesh(np.random.randn(10, 10))
cb = fig.colorbar(c, ax2)
cb.remove()

da = DrawingArea(5, 5)
da.add_artist(cb.ax)

pack = AnchoredOffsetbox(child=da, loc="upper right")
ax3.add_artist(pack)
```
![image](https://user-images.githubusercontent.com/23433306/188410141-24cdbc47-c11a-4289-a31d-41a1b5cc1cd7.png)

**Comment by jklymak** [comment]
Isn't the colorbar the artist, not it's axes?

**Comment by Mr-Milk** [comment]
The colorbar class is not inherited from `Artist`.

**Comment by jklymak** [comment]
I'd try with a simpler axes than a colorbar first, and see if that can be packed, or see if there are packable axes in the Container hierarchy.  If that works, then I'd try and track down how to get colorbar to work.

**Comment by jklymak** [comment]
I'll close this, but feel free to ask for a re-open, or open a new issue that specifically outlines what new feature is being asked for.
