### ISSUE TITLE
[ENH]: Subfigures and Mosaic

### ISSUE THREAD

**Issue by abcamiletto** [matplotlib/matplotlib#23801]
### Problem

I'm working with subplots_mosaic and it's been amazing! 
The problem I'm facing is the following:
I would like to create two subfigures with the subplots_mosaic paradigm. It doesn't seem like that is possible: if you create subfigure with add_subfigure or with the subfigure constructure i don't see a way to use the mosaic option.

Is this correct? Would be amazing to use both of them

**Comment by jklymak** [comment]
Not sure if you meant to close this, but subplot_mosaic supports nesting to make subfigures.  I'm not sure why you say subfigures don't work with mosaic: does `subfig.add_mosaic(['a', 'b'])` not work for you?
