### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#23803]
Currently LGTM.com is used, but they will stop operating at the end of the year, https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/. There has been an attempt to use CodeQL https://github.com/matplotlib/matplotlib/pull/22446 but a bit more working is needed.

pylint/flake8 sorts out some of the issues though for the Python code.

Related: https://github.com/matplotlib/matplotlib/issues/17063

Should we try to get CodeQL up and running? Any other code checking tool/site worth considering?

**Comment by tacaswell** [comment]
We should get #22446 fixed up and merged.

**Comment by tacaswell** [comment]
I moved the work to #23812 because I did not want to force-push to upstream (even if it was on just one branch).

**Comment by oscargus** [comment]
Thanks! I think it looks good, but have limited experience with CodeQL.

What I liked about LGTM was that it also showed things that "could be better", it kept a database and didn't complain too loudly. Good thing with CodeQL (as I understand it) is that it will complain quite loudly if someone tries to introduce something really bad, but may not of the type "you could write this like that instead".

Maybe we should revisit the flake8 settings at some stage?

**Comment by tacaswell** [comment]
This is closed by #23812
