### ISSUE TITLE
backend_gtk3agg.py calls set_device_scale

### ISSUE THREAD

**Issue by bernstei** [matplotlib/matplotlib#23827]
There appears to be a mismatch between the `pycairo` methods that are used and the version that is tested for at import time, and the one that is apparently automatically installed by pip.

There's a call to `set_device_scale` https://github.com/matplotlib/matplotlib/blob/ca9a779a0008ad2c77657a3ebf907f79f076bc86/lib/matplotlib/backends/backend_gtk3agg.py#L41

The cairo back end seems to require 1.11.0 https://github.com/matplotlib/matplotlib/blob/dc7b7859dca38b9655d65092b81020f33577f925/lib/matplotlib/backends/backend_cairo.py#L17

However, that method appears to have introduced in 1.14.0 https://github.com/pygobject/pycairo/blob/f7c52987339546dbe60f3962efca4d8a45351d9b/NEWS#L311

 The documented dependency should also be corrected.

**Comment by bernstei** [comment]
backend_gtk3agg.py uses cairo: https://github.com/matplotlib/matplotlib/blob/ca9a779a0008ad2c77657a3ebf907f79f076bc86/lib/matplotlib/backends/backend_gtk3agg.py#L7

And under at least some circumstances If you have cairo 1.11.1 installed, the import doesn't complain, but then you get an error when you try to plot.  Here's a message from a colleague who ran into this (Ubuntu on WSL):
```
In [5]: from matplotlib import pyplot as plt
In [6]: x=[1,2,3,4];y=[1,4,9,16]
In [7]: plt.plot(x,y);plt.show()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/VENV/kmcos/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3agg.py:47, in FigureCanvasGTK3Agg.on_draw_event(self, widget, ctx)
     43 buf = cbook._unmultiplied_rgba8888_to_premultiplied_argb32(
     44     np.asarray(self.copy_from_bbox(bbox)))
     45 image = cairo.ImageSurface.create_for_data(
     46     buf.ravel().data, cairo.FORMAT_ARGB32, width, height)
---> 47 image.set_device_scale(scale, scale)
     48 ctx.set_source_surface(image, x / scale, y / scale)
     49 ctx.paint()
AttributeError: 'cairo.ImageSurface' object has no attribute 'set_device_scale'
```

The installed version of cairo for this user is 1.11.1, which the import is happy with, but fails to actually run, due to an attempt to call a method that apparently wasn't introduced until 1.14.0.

**Comment by tacaswell** [comment]
Indeed, we document pycairo 1.11 https://matplotlib.org/devdocs/devel/dependencies.html#backends

pycairo is from 2017 which is well old enough so we should bump our dependency checking/documentation to 1.14.

**Comment by anntzer** [comment]
By the way, looks like I forgot to update that list in #23538: gtk-based backends strictly depend on pycairo; cairocffi is not an option.
