### ISSUE TITLE
[Bug]: set_aspect with negative argument leads to infinite loop

### ISSUE THREAD

**Issue by jvanhoefer** [matplotlib/matplotlib#23847]
### Bug summary

When calling `plt.gca().set_aspect(-1)` it leads to a infinite loop, where `ValueError: 'box_aspect' and 'fig_aspect' must be positive` repeatedly, until I terminate python.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.plot()
plt.gca().set_aspect(-1)
```

### Actual outcome

`ValueError: 'box_aspect' and 'fig_aspect' must be positive` is thrown repeatedly

### Expected outcome

either a single Value Error, or that you get the same as if you would invert the y-axis, but with a 1:1 aspect ratio.

### Operating system

iOS

### Matplotlib Version

3.5.3

### Matplotlib Backend

MacOSX

### Python version

3.10

### Installation

pip

**Comment by timhoffm** [comment]
Please provide more info: a full minimal example (the code snippet above does not raise) and the full stack trace.

---

Side note: Possibly someting in the backend/event loop. With Qt backend I get

```
Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 477, in _draw_idle
    self.draw()
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/figure.py", line 2823, in draw
    artists = self._get_draw_artists(renderer)
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/figure.py", line 238, in _get_draw_artists
    ax.apply_aspect()
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 1895, in apply_aspect
    pb1 = pb.shrunk_to_aspect(box_aspect, pb, fig_aspect)
  File "/home/tim/anaconda3/envs/mpl35/lib/python3.10/site-packages/matplotlib/transforms.py", line 558, in shrunk_to_aspect
    raise ValueError("'box_aspect' and 'fig_aspect' must be positive")
ValueError: 'box_aspect' and 'fig_aspect' must be positive
```
and an empty but responsive figure window. As expected the interpreter is blocked while the window is open. When closing the window, the prompt returns.

**Comment by tacaswell** [comment]
Steps needed:

 - add validation in `set_aspect` that will raise for negative values
 - add a test that it raises

**Comment by ZzN1NJ4** [comment]
Hello, May I work on this issue please sir/ma'am ?

**Comment by timhoffm** [comment]
@ZzN1NJ4 Go for it.

**Comment by jvanhoefer** [comment]
As a more general remark: Setting the aspect ratio via `set_aspect` does not work together with inverting the y axis with `invert_yaxis`. (As `invert_yaxis` does not give an equal aspect ratio, while `set_aspect(1)` leaves me with a non-inverted y axis...). 

Should I open a feature-request issue on that?

**Comment by jklymak** [comment]
That seems like a bug, and a yes, please open a different issue

**Comment by jvanhoefer** [comment]
Regarding my above comment: It turned out, that the issue was with some other part of the code I was working on, and matplotlib actually works fine there. Sorry for the confusion.

**Comment by KelsonXie** [comment]
Hey, I would like to tackle this issue if you don't mind.

**Comment by wolbek** [comment]
Hello Sir/Madam, I would like to contribute to this issue.

**Comment by tacaswell** [comment]
@wolbek Please open a PR!  As we have said above, we do not assign issues pre-PR (opening the PR is claiming the work ;) ).

**Comment by ajjayymahato** [comment]
Hi there! I would like to work on this issue. Can you please assign this issue to me?

**Comment by QuLogic** [comment]
We do not assign issues. As you can see above there is already a PR open, though it is currently in draft.
