### ISSUE TITLE
[Bug]: The point marker is not actually unfilled

### ISSUE THREAD

**Issue by msrosenberg** [matplotlib/matplotlib#23849]
### Bug summary

According to the documentation (https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html), the point marker (.) is an unfilled marker and thus displayed using only a single color. However, if you plot a point with both a color and an edgecolor, both colors are actually displayed. 

### Code for reproduction

```python
import matplotlib.pyplot as pyplot

x = [i for i in range(10)]
y = [i for i in range(10)]
pyplot.scatter(x, y, color="black", marker=".", edgecolors="red", s=200)
pyplot.show()
```

### Actual outcome

The points in the figures are black with red borders.

![Figure_1](https://user-images.githubusercontent.com/311285/189397640-5199ed04-851f-4ece-a9e6-5d2feeb9e945.png)

### Expected outcome

The points in the figure should be solid black.

### Operating system

Windows

### Matplotlib Version

3.5.3

**Comment by msrosenberg** [comment]
This bug/discrepancy does not appear to occur with other unfilled markers, such as the variously facing carets, markers 4 through 11. It appears unique to the point marker.

**Comment by timhoffm** [comment]
To me the question is: What is the best way forward? Should we make '.' unfilled, or just change the docs and move '.'  to the filled markers in the docs. I'm leaning towards the latter.

**Comment by msrosenberg** [comment]
I'm not a matplotlib developer and have no strong opinion (changing the doc would likely be easier), but if you just move it to the filled markers, I suppose the practical question is what is the difference between point and circle, other than circles tend to be larger than points for the same scale/size? Presumably there was a reason to have two distinct circular markers at some point (even three, perhaps, if you count pixel); my assumption was that someone(s) thought it was a good idea to have both filled and unfilled versions. 

I think all of the other markers are distinct in some manner; the only difference between point and circle would become size?

**Comment by timhoffm** [comment]
> Presumably there was a reason to have two distinct circular markers at some point

The existence of the circle *and* point marker is surely motivated by [MATLAB having both](https://de.mathworks.com/help/matlab/creating_plots/specify-line-and-marker-appearance-in-plots.html). I could imagine that at the time of implementation, people mainly cared about the default look. And that filled/unfilled was not a deliberate choice for the point markers. - It may well be that the only difference is size. But to be sure, we'd need to do a lot of archeology.

**Comment by jklymak** [comment]
Is this just not a case of the (relatively new) Marker reference being incorrect, and "point" should have been in the filled marker group?  (https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html). If thats been the implementation forever, it seems hard to change it now.  The marker API page makes no mention of whether this marker (or most others) is filled or not: https://matplotlib.org/stable/api/markers_api.html

**Comment by timhoffm** [comment]
> Is this just not a case of the (relatively new) Marker reference being incorrect, and "point" should have been in the filled marker group?

Agreed. We should declare this a doc issue and fix the marker reference.
