### ISSUE TITLE
[Bug]: constrained layout pickle error

### ISSUE THREAD

**Issue by Alex-x90** [matplotlib/matplotlib#23856]
### Bug summary

When constrained_layout is enabled for a figure it errors with `TypeError: cannot pickle 'kiwisolver.Solver' object` when attempting to pickle the figure.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import pickle
import numpy as np

fig = plt.figure(constrained_layout=True)
ax = fig.add_subplot(1,1,1)
ax.imshow(np.random.rand(28,28), cmap="gray", interpolation="None")

fig2 = pickle.loads(pickle.dumps(fig))

plt.show()
```

### Actual outcome

Program errors with `TypeError: cannot pickle 'kiwisolver.Solver' object`.

### Expected outcome

Figure is successfully pickled and program displays both figures.

### Additional information

Setting constrained_layout to false allows the figures to properly display with no errors.

### Operating system

Windows

### Matplotlib Version

3.4.3

### Matplotlib Backend

TkAgg

### Python version

3.8.1

### Jupyter version

6.4.6

### Installation

pip

**Comment by jklymak** [comment]
Pretty sure this was fixed a long time ago, and indeed works fine on main.  Please upgrade your Matplotlib.

**Comment by Alex-x90** [comment]
> Pretty sure this was fixed a long time ago, and indeed works fine on main. Please upgrade your Matplotlib.

I've noticed something is different with figure sizes and the font in newer version of matplotlib. How can I use the same overall layout settings that I have in my current version?

**Comment by jklymak** [comment]
That would require more information.

I will make my usually comment that I am skeptical that pickling figures has any practical advantages.  Maybe you can just not use pickle on them.

**Comment by Alex-x90** [comment]
I'm using pickling to work around another bug [#23809](https://github.com/matplotlib/matplotlib/issues/23809). What other info would I need to replicate how it look in the older version I'm currently using?

**Comment by Alex-x90** [comment]
For reference what my project looks like in version I'm using vs. current version:
![image](https://user-images.githubusercontent.com/40383341/189506591-e6352d25-56a2-4196-ab56-4a26435eebba.png)
![image](https://user-images.githubusercontent.com/40383341/189506612-bb366263-39e3-419c-91cd-d11a15b4b85d.png)

**Comment by jklymak** [comment]
You would need an example of before and after and any settings in your matplotlibrc

From the above, I have no idea why the panels got wider - you may want to color your figure backgrounds to see if its really that the figures are a different size or if your GUI is making the panels a different size.  

You might also want to check your dpi ratios as we have improved the handling of dpi ratios in the last little while, but it may be interfering with whatever your GUI framework is doing.   If you have the ability to change your DPI ratio on your system, change it and see if the problem gets better/worse.  You may just need to re-architect with the proper dpi ratio.  

If you want help here, I'd make a far simpler, self-contained GUI that shows the problem and open a new issue, or discuss at https://discourse.matplotlib.org
