### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#2387]
matplotlib's import sections at the top of files are really messy.

We should go through and:

1) Convert everything to absolute imports where appropriate (to avoid problems like the ambiguity between `collections` and `matplotlib.collections`, for example)
2) Remove unused imports
3) Per PEP8, sort imports into:
   - standard library imports
   - related third party imports
   - local application/library specific imports
4) Favor importing modules rather than members of modules -- that leads to a large global namespace in the module with larger potential for namespace clashes.

Additionally, I've never been much of a fan of

```
from matplotlib import transforms as mtransforms
```

though I understand the need when the module name is too generic.  I'd prefer to reduce this usage by renaming where appropriate.

Perhaps instead we do:

```
from matplotlib import transforms as mpl_transforms
```

Before I embark on this, I thought I'd get some feedback.  @pelson, @dmcdougall, @NelleV, @WeatherGod, @efiring

**Comment by efiring** [comment]
@mdboom, I think that as part of the PEP-8-ification, much of this has been done--maybe most of the noncontroversial parts.  Can this issue be closed?

**Comment by pelson** [comment]
Yep. Not all of the suggestions have been done, and there is always room for improvement, but I don't think the existence of this issue will make any difference to any future work.
