### ISSUE TITLE
[Doc]: Thumbnail title in gallery show rst formatting characters

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#23884]
### Documentation Link

https://matplotlib.org/devdocs/tutorials/index.html#intermediate

### Problem

for instance here:

![image](https://user-images.githubusercontent.com/19879328/189995776-e11a23b2-5f03-4f9b-bf51-e8bc0d9076f4.png)

This is caused by https://github.com/sphinx-gallery/sphinx-gallery/pull/906. I'm not sure if this can be fixed on matplotlib's side or must be addressed in sg. See also https://github.com/sphinx-gallery/sphinx-gallery/issues/998. 

### Suggested improvement

The title should be just `origin and extent in imshow` without `*`, `~.Axes.` prefix and backticks.

**Comment by timhoffm** [comment]
Agreed that we should not use markup in headings.

Maybe we can make the wording more explicit though. How about

> imshow(): Behavior of parameters origin and extent

**Comment by QuLogic** [comment]
It would be best if this were fixed in sphinx-gallery; never know if we might accidentally introduce formatting in a title somewhere later.

**Comment by timhoffm** [comment]
The question generally is how? While *emphasis* may be viable, do you really want to have links, literal code etc in a title?

**Comment by QuLogic** [comment]
We already disallow links in headings, but it's only enforced when we notice it. For the sphinx-gallery cards, it'd be better to strip all formatting.

**Comment by StefRe** [comment]
My intention when opening this issue was not so much to change the examples and tutorials but restore the behavior of sg < 0.11.0 where any formatting was stripped from the title, see [the old docs](https://matplotlib.org/2.2.5/tutorials/index.html):  

![grafik](https://user-images.githubusercontent.com/19879328/190075415-2398030f-2bab-45d7-ae2e-3c2c32c7c786.png)

The question was more if this could be achieved by some CSS voodoo on the part of matplotlib instead of waiting for a fix in sg.

**Comment by timhoffm** [comment]
This would need to be addressed in Sphinx-gallery.

**Comment by StefRe** [comment]
I've opened an issue there: https://github.com/sphinx-gallery/sphinx-gallery/issues/1002

**Comment by StefRe** [comment]
The original example above has no thumbnail anymore (due to #25395). With Sphinx Gallery 0.12.2 and https://github.com/sphinx-gallery/sphinx-gallery/pull/1108 there's only a single case left which will be fixed by #25508 .
