### ISSUE TITLE
[Bug]: Unable to plot WRF output in polar projection properly.

### ISSUE THREAD

**Issue by zemega** [matplotlib/matplotlib#23890]
### Bug summary

Weather Research and Forecasting, WRF  (https://github.com/wrf-model/WRF) output in polar projection could not be plotted by matplotlib and/or cartopy properly. 

Please find the file needed in https://drive.google.com/drive/folders/1HJaU83dCUxIiXs7QQZkuI63TxdW0bbEu?usp=sharing.
The file name for this is wrfout_d02_HGT.nc. This is a sample with only one variable, it's around 6.1 MB. This problem also happens in wrfout_d01_HGT.nc, but I will work on this later.

### Code for reproduction

```python
import wrf
from netCDF4 import Dataset
import matplotlib
import matplotlib.pyplot as plt
from cartopy import crs
from wrf import (getvar, get_cartopy, latlon_coords)

# Load the dataset
WRF_File = Dataset('wrfout_d02_HGT.nc')

# Extract terrrain height variable "slp" at time index 0 using getvar
ter = getvar(WRF_File, 'ter')

# Extract cartopy object and lat/lon coordinates using get_cartopy and latlon_coords
cart_proj = get_cartopy(ter)
lats, lons = latlon_coords(ter)

# Create a figure and axes object
fig = plt.figure(figsize=(5,5))
# Set map projection with cart_proj.
ax = plt.axes(projection=cart_proj) 

# Set contour levels 
lvl = np.arange(200, 4000, 500)

# Add contour lines
plt.contour(lons,
            lats,
            ter,
            levels=lvl,
            colors='k',
            transform=crs.PlateCarree())

# Add filled contour lines
#plt.contourf(lons,
#             lats,
#             ter,
#             levels=lvl,
#             transform=crs.PlateCarree(),
#             cmap='viridis')

# Add colorbar
#plt.colorbar(ax=ax, shrink=0.7)

plt.show()
```

### Actual outcome

Contour lines only
![Domain02-matplotlib](https://user-images.githubusercontent.com/47267219/190289181-f1ee6f3f-b080-4325-8da7-f4de5f16b5e6.png)

Filled contour
![Domain02-matplotlib-filled-contour](https://user-images.githubusercontent.com/47267219/190289621-8d7864fb-5644-42d9-8db6-6e562f745293.png)

As you can see there's wierd rotating polygon being plotted in the middle area of the plot.

### Expected outcome

This a preview of what the plot should look like using ncview.
![ncview_d02_hgt](https://user-images.githubusercontent.com/47267219/190289438-1a4ffd02-2f90-46f2-b19e-0b0485139cc8.png)

### Additional information

Using ncview to illustrate the lat/lon position of the files, here is how it looks like:
![ncview_d02_xlat](https://user-images.githubusercontent.com/47267219/190290116-a38f4bb1-29d9-489e-ac47-2ce0b4f7dfa3.png)![ncview_d02_xlong](https://user-images.githubusercontent.com/47267219/190290130-64c75dca-fb35-46ea-8dd2-4a84a830efe0.png)

As you can see, there is a discontinuation where longitude 180 meets -180. I suspect this may be a problem. I'm saying this from my experience in handling a child domain `wrfout_d03_HGT.nc`. In  `wrfout_d03_HGT.nc`, the data crosses the line where  longitude 180 meets -180. To simplify this, its can be illustrated as  177, 179, -179, -177. I changed this into 177, 179, 181, 183 as ad-hoc fix. As you can see below, the first one is without the ad-hoc fix, and the second one is with the ad-hoc fix. I believe this by itself is also a problem, whether it's the same problem as I'm writing this, I'm not sure.
![Domain03-matplotlib-default](https://user-images.githubusercontent.com/47267219/190291440-e2b036f3-d326-4190-86fb-473200f0a542.png)
![Domain03-matplotlib-updated](https://user-images.githubusercontent.com/47267219/190291447-f4526728-eafd-4b57-9a77-73c9befdc234.png)

This leads me to believe that there is a problem somewhere when matplotlib+cartopy tries to plot wrf output in polar projection, specifically, when 180 meets -180. I did try changing it to 0 to 360, but the problem remains.

Here's the domain configuration for WRF model if you need it.

```
&geogrid
 parent_id =           1,   1,   2,     3,
 parent_grid_ratio =   1,   3,   3,      3,
 e_we           =    369, 730, 676,  634,
 e_sn           =    485, 730,736,715,
 i_parent_start =      1,  59, 223,   185,
 j_parent_start =      1, 128, 354,  348,
 geog_data_res  = '10m', '10m', '2m', '30s',
 dx = 27000,
 dy = 27000,
 map_proj = 'polar',
 ref_lat   = -87.4
 ref_lon   = 180.0
 truelat1  = -71.0,
 truelat2  = -91.0,
 stand_lon = 180.
 geog_data_path = '../GEOG'
 ! opt_geogrid_tbl_path = './'
/
```

### Operating system

Ubuntu WSL inside Windows 10

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.6

### Jupyter version

IPython          : 8.4.0 ipykernel        : 6.15.2 ipywidgets       : not installed jupyter_client   : 7.3.5 jupyter_core     : 4.11.1 jupyter_server   : not installed jupyterlab       : not installed nbclient         : not installed nbconvert        : not installed nbformat         : not installed notebook         : not installed qtconsole        : not installed traitlets        : 5.3.0

### Installation

conda

**Comment by jklymak** [comment]
I think this would be better reported to cartopy?

**Comment by zemega** [comment]
> I think this would be better reported to cartopy?

Alright, I'll open an issue over cartopy as well.

**Comment by jklymak** [comment]
Well let's close it here, unless you have a reproducible example with just matplotlib.  If there is action on out side we can reopen or open a new issue.
