### ISSUE TITLE
[Doc]: add animation examples to show animated subplots

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#23909]
### Documentation Link

https://matplotlib.org/devdocs/gallery/animation/index.html

### Problem

Figured it'd be useful to have at least one example in the docs to show that it's possible and encourage the use of the OO paradigm. There used to be a [subplot example](https://matplotlib.org/2.1.2/gallery/animation/subplots.html), but <strike>that was back when it was overly complicated to do animated subplots.</strike> it was removed in #10125

### Suggested improvement

Add a new example showing how animation on subplots work. I originally thought of merging existing examples but they all feel overly complicated so I think this should be super simple, like 3 plots: sine/cosine/tangent and two lines each in the style of https://matplotlib.org/devdocs/gallery/animation/simple_anim.html#sphx-glr-gallery-animation-simple-anim-py

I was thinking something like this, but if there's an easier or alternative, we should probably show that (too/instead of):

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, (ax1, ax2, ax3) = plt.subplots()

x = np.arange(0, 2*np.pi, 0.01)
line1, = ax1.plot(x, np.sin(x))
line2, = ax2.plot(x, np.cos(x))
line3, = ax3.plot(x, np.tan(x))

def animate(i):
    line1.set_ydata(np.sin(x + i / 50))  # update the data.
    line2.set_ydata(np.sin(x + i / 50)) 
    line3.set_ydata(np.sin(x + i / 50)) 
    return [line1, line2, line3]


ani = animation.FuncAnimation(
    fig, animate, interval=20, blit=True, save_count=50)

```

**Comment by dopplershift** [comment]
> but that was back when it was overly complicated to do animated subplots.

I'll agree that the example was overly complicated, but I don't think anything has changed in regards to animating. They are, and have always been, just another `Axes`. Is there an issue I missed?

**Comment by dopplershift** [comment]
> That example was removed in #10125 and also yes I saw code and didn't read carefully that actual mechanisms didn't change 😖 sorry!
> 

No worries, I think having an example that shows how to properly manage artists across different `Axes` is definitely useful to have. Just wanted to make sure I wasn't misunderstanding something else.

**Comment by timhoffm** [comment]
I think a projection of a circular motion would be a nice example. Similar to https://www.youtube.com/watch?v=cx-qHZwsLqs


Left ax: circle with a rotating point and a line from that point vertically to the x axis(= the y component)

Right ax: y(r) = sin(r), and a vertical line moving along r. One should see that both vertical lines always have the same height.

**Comment by StefRe** [comment]
something like this?
![animation](https://user-images.githubusercontent.com/19879328/190874602-4bef2826-9c0a-4181-b212-f2e3248cb421.gif)

**Comment by timhoffm** [comment]
Great! I wasn't sure how difficult the connection line between the two Axes was, and thus proposed the vertical lines, but this is even bette.
