### ISSUE TITLE
[Doc]: API docs pages shorter than one full screen seem bottom aligned

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#23908]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.axes_grid1.anchored_artists.html (for example)

### Problem

The main text is bottom-aligned, leaving a lot of blank space at the top.
![screenshot](https://user-images.githubusercontent.com/1322974/190618222-66e27e28-cfb0-4c26-aeb9-62443b5010ef.png)

**Comment by timhoffm** [comment]
Just found https://numpydoc.readthedocs.io/en/latest/, which is also bottom-aligned.

Digging deeper, this is an issue in pydata-sphinx-theme and will be resolved in the 0.11 release.

**Comment by timhoffm** [comment]
The upstream fix has reached our docs.
