### ISSUE TITLE
[Bug]: v3.6.0 breaking code that worked till v3.5.3

### ISSUE THREAD

**Issue by lssatvik** [matplotlib/matplotlib#23924]
### Bug summary

I have been receiving an error from shap package since September 15 that I could not make sense of, and which used to work earlier. I found out today, that on September 15 matplotlib, which is a dependency of shap was updated, and is the source of the issue. Please let me know if this issue is a bug or intended.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3456652/190871190-d10a0895-1ab0-435d-8c25-b608312563f3.png">
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/3456652/190870770-ab6bdb1e-d223-4afe-bc40-ebc9dc03dc7f.png">

I have been using the latest shap v0.41.

### Code for reproduction

```python
shap.summary_plot(shapv, x, show=False)
```

### Actual outcome

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/3456652/190870928-fb2e153d-f57b-4f0c-b301-38bd039be2af.png">

### Expected outcome

No error as with v3.5.3 . Am not familiar with the functioning of matplotlib.

### Matplotlib Version

3.6.0

### Python version

3.9.13

### Installation

pip

**Comment by jklymak** [comment]
You will likely need to pin your install to 3.5.3.  It would be good to open an issue with `shap` and then have them follow up with us on why they are creating an artist-less colorbar.

**Comment by jklymak** [comment]
BTW there should have been a warning previously - if there wasn't we missed an edge case, but it would be good to know what code would cause that edge case.  Thanks,

**Comment by lssatvik** [comment]
> You will likely need to pin your install to 3.5.3. It would be good to open an issue with `shap` and then have them follow up with us on why they are creating an artist-less colorbar.

Already did, but I don't think shap community is as active as matplotlib.

> BTW there should have been a warning previously - if there wasn't we missed an edge case, but it would be good to know what code would cause that edge case. Thanks,

I have never looked into the implementation of matplotlib or shap. Will let you know if I find the edge case.

**Comment by jklymak** [comment]
I'll take the liberty of closing for now, but feel free to request a re-open if you have more information.

**Comment by jklaise** [comment]
@lssatvik I've opened a PR to fix this in the `shap` library: https://github.com/slundberg/shap/pull/2697

**Comment by lssatvik** [comment]
Thank you @jklaise, it seems you also found my bug report on shap page.
