### ISSUE TITLE
[ENH]: Just get the plot data not including white spaces

### ISSUE THREAD

**Issue by Flock1** [matplotlib/matplotlib#23927]
### Problem

A lot of plots are used for machine learning. These plots contain white spaces that are just pure noise. So there should be a way to get just the data instead.

**Comment by Flock1** [comment]
A lot of us convert the signal to time-frequency plots using libraries like `mne` and `librosa`, which use `matplotlib` as a plotting tool. Even if I try to get rid of the axes and ticks, I end up getting an image like this:
![image](https://user-images.githubusercontent.com/15093420/190887088-84890d71-1423-43c0-b8ae-2604249c8cc2.png)
The white spaces on the edges are not at all important and need to be got rid of. Is that an already implemented feature in matplotlib?

**Comment by timhoffm** [comment]
Do you mean the margins outside the black box?

**Comment by Flock1** [comment]
Yes.

**Comment by tacaswell** [comment]
I think this is a question about how to use the layout tools.  Exactly what is best for you will depend on the details of how you are setting up the figure / axes so it is difficult to give a definitive answer.

One apporach is to use constrained or tight layout (see https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html) or to manually set the axes to fill the full figure (`ax.set_position([0, 0, 1, 1]) (see https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_position.html).

If you have further questions, please move this discussion do https://discourse.matplotlib.org

**Comment by Flock1** [comment]
But at least there should be a feature in matplotlib to just get the data. I know there's `.data` but it gives the white spaces. So in matplotlib, you can add a `bool` type argument that will return just the plot data (without white spaces) so that all these settings that you're suggesting can be avoided.

**Comment by Flock1** [comment]
> One apporach is to use constrained or tight layout

I tried that. this was my code:
```
plt.axis('off')
plt.imshow(img_orig_2)
plt.savefig('test.png', bbox_inches='tight',pad_inches = 0, dpi = 180)
plt.show()
```
But it didn't work

**Comment by jklymak** [comment]
Please follow up on discourse, preferably with a minimal self-contained example that "doesn't work".  Something is wrong if bbox_inches="tight" is not working, but it is impossible to tell without seeing an example.  Thanks

**Comment by Flock1** [comment]
I mean, all I'm trying to do is to use [this](https://mne.tools/stable/auto_tutorials/time-freq/20_sensors_time_frequency.html#inspect-power) code and get a plot without any labels, ticks or white spaces. These libraries use matplotlib for plotting so maybe it's a feature that can be added to matplotlib.

**Comment by jklymak** [comment]
Our code, without mne, can indeed trim the whitespace, so we already have the feature you are requesting, and have had it for many many years.    Please follow up with `mne` if you cannot trim the whitespace using their plotting methods.  Come back to us if you can reproduce the problem using just matplotlib and numpy.

**Comment by Flock1** [comment]
Can you tell me where that feature is or how to use it?

**Comment by jklymak** [comment]
`fig.savefig('boo.png', bbox_inches='tight', pad=0)`.

**Comment by Flock1** [comment]
I did that, as mentioned above. It still shows the white spaces.

**Comment by jklymak** [comment]
Yes,

> Please follow up with mne if you cannot trim the whitespace using their plotting methods. Come back to us if you can reproduce the problem using just matplotlib and numpy.

**Comment by Flock1** [comment]
Okay. One last thing. Is it possible to get this `bbox_inches` and `pad` without running `savefig`?
