### ISSUE TITLE
[Doc]: Adding animations to Youtube channel

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#23955]
### Documentation Link

https://matplotlib.org/devdocs/devel/documenting_mpl.html#adding-animations

### Problem

There is just 1 (!) video in the linked channel (added 10 years ago). My understanding is that the [Discourse Showcase section](https://discourse.matplotlib.org/c/showcase/7) would be the right place for such animations?

### Suggested improvement

Remove the _Adding animations_ section from the docs.

**Comment by timhoffm** [comment]
> and if so, your handles on those accounts.

better:

> and if so, optionally your handles on those accounts so that we can mention you.

**Comment by StefRe** [comment]
> replacing w/ a link to discourse showcase would be awesome

We're talking here about the _Writing Documentation_ section of the developer's docs, therefore I'd rather remove the _Adding animations_ subsection instead of replacing it by something else. Animations get perfectly well embedded in the documentation by sphinx without the need of linking to youtube.

There's already a link to discourse in the [Contributing](https://matplotlib.org/devdocs/index.html#contributing) section, so I guess the suggested text would better go into the pinned [About the Showcase Category post](https://discourse.matplotlib.org/t/about-the-showcase-category/20507).
