### ISSUE TITLE
[ENH]: Make rubber band more visible

### ISSUE THREAD

**Issue by komoto48g** [matplotlib/matplotlib#23969]
### Problem

If the image is dark such as diffraction patterns, the rubber band is hardly visible.

### Proposed solution

Candidates would be,
1. Draw xor masked line (similar to `Cursor`).
2. Paint with a semi-transparent color inside the rectangle (similar to ver 3.3.4).

![Clipboard01](https://user-images.githubusercontent.com/83063554/191326323-24d6334a-46e3-4f6f-9202-49b3e2a79707.png)

**Comment by QuLogic** [comment]
With what backend? The rubber band should be alternating black and white in most (but not all in 3.5.3, IIRC.)

**Comment by anntzer** [comment]
IIRC it's wx which used that colored rectangle previously.  Currently it doesn't draw the white dashes; seems straightforward enough to add that.  Looking at other backends, I believe tk and macos also need the improvement.
Marking as good first issue (but medium as you need to fiddle with GUI toolkits (and ObjC for the macos backend) -- it's not necessary for a PR to handle all backends at once).

**Comment by oscargus** [comment]
The MacOS-backend has a separate issue with a bit of possibly useful details: #23777

**Comment by oscargus** [comment]
For wx one can add the following line before https://github.com/matplotlib/matplotlib/blob/4a62222ff48eae3b8027813ed4313362cfb39da0/lib/matplotlib/backends/backend_wx.py#L629-L632

``` python
            drawDC.DrawLineList(
                [(x0, y0, x1, y0), (x1, y0, x1, y1),
                 (x0, y0, x0, y1), (x0, y1, x1, y1)],
                wx.Pen('WHITE', 1, wx.PENSTYLE_SOLID))
``` 

wx does not support 0-length dashes, so one cannot start with a gap (as far as I can tell).

Bonuses:
* Only create the point-list once per call
* Only create the pens once per CanvasBase instance.

**Comment by komoto48g** [comment]
Thank you for your consideration of this issue. I tested on Windows 10 with matplotlib 3.5.3/WxAgg and TkAgg. The two seem slightly different:
WxAgg => black dashed line
TkAgg => black solid line
The black and white line is also nice.
