### ISSUE TITLE
[Doc]: Examples Gallery Layout changed to one or two columns

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#23976]
### Documentation Link

https://matplotlib.org/devdocs/gallery/spines/index.html

### Problem

Galleries **without text,** e.g. [Spines](https://matplotlib.org/devdocs/gallery/spines/index.html) are shown in a one or two column layout with broad margins at both sides (galleries **without text**, e.g. [Color](https://matplotlib.org/devdocs/gallery/color/index.html) don't seem to be affected, but sometimes have a big top margin).    
The only gallery that didn't change and looks normal is [Embedding Matplotlib in graphical user interfaces](https://matplotlib.org/devdocs/gallery/user_interfaces/index.html) which _only contains placeholder images_.  
This change might be caused by https://github.com/sphinx-gallery/sphinx-gallery/pull/906 ?

**CURRENT (3.6/3.7):**
![grafik](https://user-images.githubusercontent.com/19879328/191553569-076413aa-3130-4e48-8bda-8582ff487e41.png)

**PREVIOUS (3.5):**
![grafik](https://user-images.githubusercontent.com/19879328/191553800-085942e0-3920-47cb-a998-eeb0b1b8a3b9.png)

### Suggested improvement

Restore old layout.

**Comment by QuLogic** [comment]
This should be reported to sphinx-gallery.

**Comment by StefRe** [comment]
@QuLogic: Thanks! I added a comment there: https://github.com/pydata/pydata-sphinx-theme/issues/904#issuecomment-1254578925

So we can close the issue here in matplotlib?

**Comment by timhoffm** [comment]
The question is whether we want to add 
```
.bd-article-container {
  width: 100%;
}
```
as a temporary workaround on our side until pydata-sphinx-theme has released a fixed version.
