### ISSUE TITLE
[Doc]: Uniform tile height in sphinx-gallery overviews

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#23996]
### Problem

Recent releases of Sphinx gallery dynamically determine the tile height on the overview page.As a result the heights can differ per line:

![image](https://user-images.githubusercontent.com/2836374/192113459-e71a13d8-fd5c-4e7c-9cd5-560d502abc69.png)

### Suggested improvement

Is that ok, or do we want to go back to a more uniform height? In case of the latter, the suggestion from sphinx-gallery is to use a `min-height` CSS attribute. I propose to add this so that the tiles have at least the height one would get with two text lines.

![image](https://user-images.githubusercontent.com/2836374/192113634-2bb8bf2e-b5eb-4759-abf8-0e911820e5cd.png)

**Comment by QuLogic** [comment]
According to [this](https://stackoverflow.com/a/50254778), it's rather easy to do with one additional CSS setting. I'm not entirely convinced it's necessary, but note that doing so increases the page height by 8%.

**Comment by timhoffm** [comment]
Let's close this for now.
