### ISSUE TITLE
[Bug]: Font-Fallback implemented in 3.6.0 does not work for title or labels

### ISSUE THREAD

**Issue by tinyboxvk** [matplotlib/matplotlib#23992]
### Bug summary

Font-Fallback implemented in https://github.com/matplotlib/matplotlib/pull/20740 does not work for title or labels.

### Code for reproduction

```python
import matplotlib.pyplot as plt


def plot_graph():
    fig, ax = plt.subplots(figsize=(6, 3))
    text = 'There are 多个汉字 👈👉 in between!'
    plt.rcParams['font.family'] = ['Segoe UI Emoji', 'SimHei']
    plt.figtext(0.3, 0.7, text)
    plt.title(text)
    plt.xlabel(text)
    plt.ylabel(text)
    plt.show()


plot_graph()
```

### Actual outcome

![2022-09-23_22-07-35_python](https://user-images.githubusercontent.com/13696594/192073786-b92f7eca-f12c-4fe3-a574-7718f65c0de4.png)

### Expected outcome

Title and labels should be displayed correctly like the figtext.

### Operating system

Windows

### Matplotlib Version

3.6.0

### Matplotlib Backend

TkAgg

### Python version

3.10.7

### Installation

pip

**Comment by anzhi0708** [comment]
![image](https://user-images.githubusercontent.com/57821133/192073892-880fb1db-41c8-45f8-a91e-66aa47ff2209.png)

Same, macOS 12.3

**Comment by QuLogic** [comment]
> ```python
>     fig, ax = plt.subplots(figsize=(6, 3))
>     text = 'There are 多个汉字 👈👉 in between!'
>     plt.rcParams['font.family'] = ['Segoe UI Emoji', 'SimHei']
> ```

That's because you set the `rcParam` after creating the figure. The same thing would happen to the other text if you put it after `figtext` as well.

You need to set the `rcParam` before calling `plt.subplots`.
