### ISSUE TITLE
[Bug]: Warning: "meta NOT subset; don't know how to subset; dropped" comes out when using custom fonts( like Times New Roman) and saving figure as PDF(TrueType), 

### ISSUE THREAD

**Issue by remaker789** [matplotlib/matplotlib#24025]
### Bug summary

When using custom fonts( like Times New Roman) and saving the figure as PDF(TrueType),  the terminal gives a warning: "meta NOT subset; don't know how to subset; dropped"

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['font.family'] = "Times New Roman"

x = np.arange(1,6,1)
y= x**2
plt.plot(x,y)
plt.savefig("./test.pdf")

plt.show()
```

### Actual outcome

meta NOT subset; don't know how to subset; dropped
[test.pdf](https://github.com/matplotlib/matplotlib/files/9660578/test.pdf)

### Expected outcome

I would like to know if the warning: "meta NOT subset; don't know how to subset; dropped" will affect the output figure. It would be good news for me if this warning can be figured out.

### Operating system

Windows

### Matplotlib Version

3.6.0

### Matplotlib Backend

QtAgg

### Python version

Python 3.9.12

### Installation

pip

**Comment by QuLogic** [comment]
I couldn't see any issues in the output PDF. But I'm also not sure where that output is from, as it doesn't appear in Matplotlib code.
