### ISSUE TITLE
[Doc]: Most of the pyplot examples don't use the pyplot interface

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#24023]
### Documentation Link

https://matplotlib.org/devdocs/gallery/pyplots/index.html

### Problem

There are 19 [pyplot examples](https://matplotlib.org/devdocs/gallery/pyplots/index.html) but only 7 of them actually use the pyplot interface:

- [Infinite lines](https://matplotlib.org/devdocs/gallery/pyplots/axline.html)
- [plot() format string](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_formatstr.html) (very trivial)
- [Pyplot Mathtext](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_mathtext.html)
- [Pyplot Simple](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_simple.html) (very simple indeed)
- [Pyplot Text](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_text.html)
- [Pyplot Three](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_three.html)
- [Pyplot Two Subplots](https://matplotlib.org/devdocs/gallery/pyplots/pyplot_two_subplots.html)

The majority of the "pyplot" examples in fact use the OO interface.

### Suggested improvement

**a)** move the 12 example using the OO interface to the corresponding sections 

or 

**b)** rewrite them using the pyplot interface 

While this doesn't appear to be a big issue to experienced matplotlib users it might confuse new users.

**Comment by jklymak** [comment]
They should be moved/removed and this section removed.
