### ISSUE TITLE
[Bug]: logit axes causes ax.text to fail with "posx and posy should be finite values"

### ISSUE THREAD

**Issue by ChrisOKay** [matplotlib/matplotlib#24057]
### Bug summary

When using a logit scale, the placement of text via ax.text() is not successful anymore. The error message "posx and posy should be finite values" is displayed instead. Might be connected to #11202. 

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.text(1, 1, "hello world")
ax.set_xscale("logit")
plt.show()
```

### Actual outcome

posx and posy should be finite values

### Expected outcome

no error

### Additional information

[pierreolivierbonin](https://github.com/pierreolivierbonin) had the same issue in Feb 2021, so it is present at least since then.

### Operating system

Windows 10

### Matplotlib Version

3.6.0

### Matplotlib Backend

QtAgg

### Python version

3.9.12

### Installation

pip

**Comment by oscargus** [comment]
As the positioning is in data coordinates and 1 is mapped to infinity for the logit-scale this happens. Compare to what you are effectively doing:

``` python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
ax.text(np.inf, 1, "hello world")
plt.show()
```

**Comment by ChrisOKay** [comment]
oh, absolutely. I had formatted my scale to percent and hence thought that "1" would be a valid coordinate.
Thanks for the clarification, this is clearly not a bug.
