### ISSUE TITLE
No error message in matplotlib.axes.Axes.legend() if there are more labels than handles

### ISSUE THREAD

**Issue by haferburg** [matplotlib/matplotlib#24050]
I had a bug in my code where I called `plot()` six times, stored the handles in a list, then called `legend()` with six handles, but seven labels for the legend.

It would have been very helpful if matplotlib raised an exception in this case.

`matplotlib.__version__` is 3.6.0, Python 3.9.6.

**Comment by QuLogic** [comment]
This seems like a pretty straightforward fix that could be a Good first issue for someone. It should be a matter of going into `_parse_legend_args` and verifying that the inputs are of a consistent length.

**Comment by tusharkulkarni008** [comment]
may I try and fix this

**Comment by QuLogic** [comment]
We don't assign issues; feel free to work on it.

**Comment by carverde** [comment]
I would like to work on this!

**Comment by timhoffm** [comment]
@carverde there is already an open PR 24050. Please either add your suggestions as comment there, or choose another issue to work on.

**Comment by tacaswell** [comment]
I changed this to medium difficulty because of some of the subtleties that came up in the discussion in #24061.

**Comment by tusharkulkarni008** [comment]
> I changed this to medium difficulty because of some of the subtleties that came up in the discussion in #24061.

how to gauge depth of an issue from an noob standpoint?. I am asking because I raised a PR which was woefully shortsighted

**Comment by timhoffm** [comment]
> how to gauge depth of an issue from an noob standpoint?

I think you can't. That's why we have the `Good first issue` and `Difficulty: ...` tags. If in doubt, feel fredd to ask. But as you can see, sometimes also the core devs don't oversee the difficulty.
