### ISSUE TITLE
[ENH]: Resizing the figure with webagg backend by dragging the corner

### ISSUE THREAD

**Issue by zhizheng1** [matplotlib/matplotlib#24075]
### Problem

I was able to back port the logic in ipympl to enable figure resizing by dragging the bottom right corner. It involves only modification to a JS file (mpl.js) to handle mouse click and movements. Does this sound interesting to anyone if I make a PR?

https://user-images.githubusercontent.com/114848324/193451951-c07869c9-cb53-4e48-91d0-1fb03650d04e.mov

### Proposed solution

Add around 10-20 lines in mpl.js to handle mouse click and movements for resizing logic.

**Comment by tacaswell** [comment]
@zhizheng1 Yes, I think that PR would be welcome and non-controversial!

**Comment by zhizheng1** [comment]
I have submitted a PR. Please review and let me know (I've been using it for a few months).

**Comment by zhizheng1** [comment]
Closing and reopening a new issue as it's only limited to Safari browser.
