### ISSUE TITLE
[Doc]: search broken on Matplotlib homepage

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#24074]
### Problem

If I browse directly to https://matplotlib.org/, I can access the new search button in the top bar.  However, searching from here gives a serious lack of results

![Screenshot from 2022-10-02 11-17-48](https://user-images.githubusercontent.com/10599679/193449185-6f66f7c5-ea58-461e-815a-b8293330b7d8.png)

Once I click pretty much any link from the homepage, I am looking at the stable docs, and then the search works fine.  This is with Firefox on Ubuntu Linux, but I get the same result with Safari on iOS.

### Suggested improvement

Ideally the homepage search would link through to the stable docs search.  Alternatively, if the search button was removed from the homepage then we would always click through to docs for a specific release before searching.

**Comment by BoseSj** [comment]
I would like to work on this.

**Comment by greglucas** [comment]
I think this is also the same issue as https://github.com/matplotlib/mpl-brochure-site/issues/65 since this is built from the brochure site, but probably good to keep this issue open in the main repository so people know it is an issue!

**Comment by BoseSj** [comment]
Yeah, that's right! Can you tell me about how work on this, possible ways to fix this issue?

**Comment by QuLogic** [comment]
`/search.html` now redirects to `/stable/search.html` and appears to be giving the right results.
