### ISSUE TITLE
verify quoting method in svg backend for font names

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#24080]
In the svg backend we need to treat generic and specific font names differently.  We are currently using `repr` to achieve this, but we need to verify that this is robust to if repr goes with single or double quotes and if any of the consumers of svg would care.

> We have used `repr()` before and it seems to have worked, but technically `repr()` is not exactly quoting. Would both single and double quotes be ok? Unlikely, but in theory Python could change that in repr (or possibly more likely an interpreter other than CPython could use other quotes). Also, can we be sure we will never have byte strings here?
>
> It's more defensive to f-string the quotes explicitly.

_Originally posted by @timhoffm in https://github.com/matplotlib/matplotlib/pull/24066#discussion_r985289613_

**Comment by tacaswell** [comment]
Labeling this as a good first issues because it will only require a very minimal change to the mpl code base and no existing familiarity with it, but medium because it requires researching the implications of quotes in strings is the SVG spec / behavior of down stream readers.

**Comment by anntzer** [comment]
Single and double quotes are equally valid, and backslash-escaping quotes is valid as well: https://developer.mozilla.org/en-US/docs/Web/CSS/string

**Comment by victorian177** [comment]
I would like to take this issue on.

**Comment by victorian177** [comment]
@tacaswell If I understand the issue correctly when the `_format_font_names` function is called, you will always have the fonts printed with different quoting styles (single for specific and double for generic fonts)?
 https://github.com/matplotlib/matplotlib/blob/7de767e927b4b4f5212e268c6432107116752d85/lib/matplotlib/backends/backend_svg.py#L1157-L1172

**Comment by anntzer** [comment]
Actually using `f"'{name}'"` seems worse as you'd need to escape single quotes in `name`.  In practice it's unlikely to matter because you probably(?) can't have quotes in font names, but still...

**Comment by tacaswell** [comment]
I'm leaning towards "close with no action" if @timhoffm agrees.

**Comment by victorian177** [comment]
> The question here is now: do we care enough about that eventuality to use f-strings to force a particular quoting or close this with no action?
> 
> @victorian177 Please look at the code again now that #24066 is merged.

@tacaswell Thanks for replying. I have looked at the code.

**Comment by timhoffm** [comment]
Given https://github.com/matplotlib/matplotlib/issues/24080#issuecomment-1265601608 and https://github.com/matplotlib/matplotlib/issues/24080#issuecomment-1265987692 `repr()` is indeed a good solution.

I'm "closing with no action". Sorry for the noise.

@victorian177 Thank you for your willingness to contribute. It turns out, there is nothing to do here. I hope you find another interesting issue to work on.
