### ISSUE TITLE
[MNT]: location of `TriMesh` changed between v3.5.x and v3.6

### ISSUE THREAD

**Issue by raphaelquast** [matplotlib/matplotlib#24105]
### Summary

In matplotlib <v3.6 `TriMesh` could be imported via 
```python
from matplotlib.tri import TriMesh
```

since v3.6 i get the following error:
```python
ImportError: cannot import 'TriMesh' from 'matplotlib.tri' ...
```

The correct import now is 
```python
from matplotlib.collections import TriMesh
```

### Proposed fix

maybe allow `TriMesh` import from `matplotlib.tri` for backward-compatibility reasons?

**Comment by oscargus** [comment]
This happened in #23554 although it wasn't the purpose of that PR... 

On one hand one should probably import from where the class is defined/documented (`collections` in this case) On the other hand, I can see that one may easily guess that `TriMesh` should reside in `tri`. On the third hand, if one should always be able to import from an "arbitrary" location for compatibility reasons, it will be even harder to modify anything.

I tag this for discussion.

**Comment by raphaelquast** [comment]
@oscargus I close this since I think a backport for the import-location is actually really not necessary (and as long as nobody else complains I think it's save to leave it as-is )
