### ISSUE TITLE
[Bug]: Incorrect position of the bar after using bar3d

### ISSUE THREAD

**Issue by codingforpleasure** [matplotlib/matplotlib#24101]
### Bug summary

After using the bar3d() function, it seems the 3d bar's position is not in the correct location for some reason,
I have tried it both in Ubuntu and Windows, the same problem appears in both OS's.

### Code for reproduction

```python
x = [2]
y = [2]
z = [2]

colors = ['skyblue']

dx = [1]
dy = [1]
dz = [1]

plt.figure(figsize=(0, 12))
ax = plt.axes(projection='3d')
ax.bar3d(x, y, z, dx, dy, dz, color=colors)
ax.set_xticks(range(7))
ax.set_xlim(0, 6)
ax.set_yticks(range(7))
ax.set_ylim(0, 6)
ax.set_zticks(range(7))
ax.set_zlim(0, 6)
ax.set_xlabel("X", labelpad=12)
ax.set_ylabel("Y", labelpad=12)
ax.set_zlabel("Z", labelpad=12)
ax.set_title("Example of a Bug")
plt.show()
```

### Actual outcome
![image](https://user-images.githubusercontent.com/1729719/194213656-76f512ff-4e66-4857-8946-fdc6b8614a17.png)

### Expected outcome

The box should appear in the corresponding coordinates (2,2,2)

### Additional information

I have no clue how come the bug appears.

### Operating system

Ubuntu and Windows

### Matplotlib Version

3.5.3

### Matplotlib Backend

TkAgg

### Python version

Python 3.8.10

### Installation

pip

**Comment by oscargus** [comment]
The bug seems to be triggered when all three `xlim`/`ylim`/`zlim` are set, but two works. (At least from a quick check.)

**Comment by oscargus** [comment]
Ah, clever.... It all makes sense then. Thanks!

Closing this, but feel free to reopen @codingforpleasure if you disagree.
