### ISSUE TITLE
[ENH]: Allow show() to timeout with a user-specified timeout

### ISSUE THREAD

**Issue by bje-** [matplotlib/matplotlib#24114]
### Problem

I want to test my Python application with complete test coverage. This means running plotting code that ultimately calls `show()` from `matplotlib.pyplot`. It would be good if `show()` could block, but timeout after a specified number of seconds. If the testsuite is being run by a human, they can visually inspect the plot while it's showing, but if the test is being run by a CI system, the testsuite won't block.

### Proposed solution

Add a new argument to `show()` with a default of `None`.

**Comment by timhoffm** [comment]
If you have popping up windows, you may want to use [pytest-xvfb](https://github.com/The-Compiler/pytest-xvfb) for CI.

That said, popping up windows is generally not a good test strategy. In CI it's only a smoke test. Visual inspection by humans does only a mediocre content validation and is cumbersome. You may want to use [pytest-mpl](https://github.com/matplotlib/pytest-mpl) instead.

**Comment by bje-** [comment]
Wow, `pytest-mpl` is far better than anything I had imagined. Thanks!
