### ISSUE TITLE
[ENH]: Implementation of matrix in mathtext without usetex.

### ISSUE THREAD

**Issue by ichibha** [matplotlib/matplotlib#24135]
### Problem

I'd like to display equations using matplotlib in realtime. However, matrix and array require usetex=true and slows down rendering significantly. 

### Proposed solution

It is very helpful if you could implement the matrix or array to work without usetex=true.

**Comment by ichibha** [comment]
I close this issue because this is a duplicate of #321.

**Comment by jklymak** [comment]
That issue is so old because no one who really wants it has stepped forward to do the work.  No doubt because it is quite difficult and there isn't a lot of call for this given that we allow rendering TeX.
