### ISSUE TITLE
[Bug]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'

### ISSUE THREAD

**Issue by srikanthravipati** [matplotlib/matplotlib#24155]
### Bug summary

Error while importing matplotlib qt backend. 

The version details are as below
matplotlib: 3.6.1
pyside: 6.4.0
python: 3.9.9

on a macOS-M1 machine.

### Code for reproduction

```python
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import QtCore, QtGui, _BackendQT, FigureCanvasQT
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 72, in <module>
    _MODIFIER_KEYS = [
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 73, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'

### Expected outcome

No error!

### Operating system

OS/X

### Matplotlib Version

3.6.1

### Matplotlib Backend

MacOSX

### Python version

3.9.9

### Installation

pip

**Comment by tacaswell** [comment]
pyside 6.4.0 went up on pypi about 2 hours ago.  I suspect something changed about how the handle enums and we will need to adjust.

This is a good first issue because the behavior is "should import" and the changes should be localized to only `backend_qt.py` and `qt_compat.py`, but medium difficulty because it will require understanding what the changes to PySide6 were and how to adapt our shim layers to work with both these changes, the previous behavior of Pyside and PyQt's behavior.

**Comment by larsoner** [comment]
FYI I expect this to break stuff for a lot of folks. It broke a bunch of our CIs in MNE-Python :(

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=22361&view=logs&jobId=dded70eb-633c-5c42-e995-a7f8d1f99d91&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=1ccededa-7e7e-5a92-87ce-e531d760d025

**Comment by abey79** [comment]
This is most likely related to the Enum change, see [here](https://www.qt.io/blog/qt-for-python-release-6.4-is-finally-here).

**Comment by Marroh** [comment]
I resolved the issue by downgrading PySide6 to a version earlier than 6.4.0.👌

**Comment by ReubenVandezande** [comment]
Can confirm I also see this:

```
>>> import PySide6
>>> PySide6.__version__
'6.5.3'
>>> import matplotlib
>>> matplotlib.__version__
'3.5.3'
>>> from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File ".../matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import (
  File ".../matplotlib/backends/backend_qt.py", line 76, in <module>
    for mod, key in [
  File ".../matplotlib/backends/backend_qt.py", line 76, in <listcomp>
    for mod, key in [
TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'
```

**Comment by rcomer** [comment]
@ReubenVandezande please upgrade your Matplotlib to version 3.6.2 or higher.
