### ISSUE TITLE
[Bug]: "findfont: Font family not found" spam upon fallback

### ISSUE THREAD

**Issue by OverLordGoldDragon** [matplotlib/matplotlib#24185]
### Bug summary

The point of a "fallback" is to use the next match so there shouldn't be any message, if I understand correctly. Here it's printed even if the _previous_ font matched.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.title("msg", fontfamily=('arial', 'helvetica'))
```

### Actual outcome

Text(0.5, 1.0, 'msg')findfont: Font family 'helvetica' not found.
findfont: Font family 'helvetica' not found.
findfont: Font family 'helvetica' not found.
findfont: Font family 'helvetica' not found.
findfont: Font family 'helvetica' not found.
findfont: Font family 'helvetica' not found.

### Expected outcome

Text(0.5, 1.0, 'msg')

### Additional information

After `conda install -c conda-forge matplotlib==3.6.1`, before I had `3.4.3`

### Operating system

Windows 10

### Matplotlib Version

3.6.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.12

### Installation

conda

**Comment by tacaswell** [comment]
Fallback is for finding missing glyphs not missing fonts.

I think in this case you have told Matplotlib "please use arial and then for any glyph that arial does not have try to use helvetica" and Matplotlib is telling you "I can don't do what you asked because I can not find helvetica" and we should be warning you that there is a missing font.

**Comment by Tillsten** [comment]
Sorry, but this was a change without deprecation warning. I still think one warning should be enough, right now and spams the console every draw.

**Comment by tacaswell** [comment]
There is some very confusing naming conventions here.  `fontfamily` is an alias for `family` which is different than the generic fonts (which what that example is about), https://matplotlib.org/stable/users/explain/fonts.html#how-matplotlib-selects-fonts is an attempt to explain this.

@Tillsten can you give an example that used to work and now warns too much?  It is not clear to me if the OP is reporting a regression here or a misunderstanding of what "fallback" meant and if the "generic font families" are involved or not.
