### ISSUE TITLE
[Doc]: Create Animation Tutorial

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#24228]
### Documentation Link

https://matplotlib.org/devdocs/tutorials/index.html

### Problem

It'd be good to have a one stop animation tutorial that gives an overview of the different animation methods and different writers. This overlaps with #19520 and #24159 and advocated for in #22374
 
Mostly opened this issue so we could maybe hash out a proposed outline & document what folks would want in a tutorial. 

### Suggested improvement

Tutorial sections 
1. [Animation Classes](https://matplotlib.org/devdocs/api/animation_api.html#animation) - brief overview of funcanimation and artist animation[^1]:
    1. [FuncAnimation](https://matplotlib.org/devdocs/api/animation_api.html#funcanimation): most common artist types[^2]:
        1. [Line2D](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) 
        2. [PathCollection](https://matplotlib.org/devdocs/api/collections_api.html#matplotlib.collections.PathCollection)
        3. [AxesImage](https://matplotlib.org/devdocs/api/image_api.html#matplotlib.image.AxesImage)
        4. maybe patches and contours?
    2. [ArtistAnimation](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.animation.ArtistAnimation.html)
 2. [Animation Writers](https://matplotlib.org/devdocs/api/animation_api.html#writer-classes):
     1. demos of saving a `FuncAnimation` and an `ArtistAnimation` with each
     2. possibly the table of `(writer, file types, dependencies)` proposed in #24159 should be here
 3. Advanced Topics:
     1. Linkout to [blitting reference](https://matplotlib.org/devdocs/tutorials/advanced/blitting.html) here  
        
[^1]: I think it's that func takes a function that updates an artist and may or may not return it, while artist takes the list of changed artists? A pro/con table or table of use cases would also maybe be good
[^2]: yes this might change if a unified abstraction goes in but that's probably ages out so documenting current state is useful

**Comment by chahak13** [comment]
Hi! I've been working on a package that also uses matplotlib's animation module ([maige](github.com/chahak13/maige). I've been planning to spend some time in the animation module and can maybe help out with this?

**Comment by chahak13** [comment]
Great, thanks! I'll give this a shot

**Comment by chahak13** [comment]
Hi, I had a question about this. In pipe-based writer classes, the supported formats will be governed by the utility being used (`ffmpeg`/`imagemagick`), since the frames are passed to them directly. Is my understanding right?

**Comment by dopplershift** [comment]
Assuming by "supported formats", you mean the final saved animation format (e.g. gif, mp4), then yes, that's controlled by the tool being used.

**Comment by chahak13** [comment]
Yes, that's what I meant. Thanks!

**Comment by chahak13** [comment]
I've started working on this in #24274. I started out with writing the code for simple animations for different animation classes. I'll add the write-up to it now. My idea is to try and cover at least all the topics mentioned in various issues related to animation module. Let me know if there are any suggestions. Thanks!
