### ISSUE TITLE
[Bug]: Matplotlib lines are not aligned with scatter points when plotting to Pdf

### ISSUE THREAD

**Issue by jan-grass** [matplotlib/matplotlib#24260]
### Bug summary

It appears that there are some small inaccuracies when using `plt.plot()` for generating Pdfs with Matplotlib. In the following I have a simple example, where lines plotted with `plt.plot()` are not aligned with the original data points plotted with `plt.scatter()`. The differences are small but could still be noticed in some real-world examples in papers etc when looking closely at the Pdf. A PNG plot (with high DPI) does not show the misalignment between lines and scatter points. 

To me this behavior is quite surprising. What is going on here? Is this maybe intended as an automatic downsampling of very dense data plotted in small figures?
I could reproduce this effect across different backends (Agg, Pdf, Pgf) and Pdf viewers (Adobe Acrobat Reader, SumatraPdf etc).

I have previously posted this as a question on Stackoverflow: [Link](https://stackoverflow.com/questions/74147057/matplotlib-lines-appear-not-to-be-accurate-when-plotting-to-pdf)

### Code for reproduction

```python
import numpy as np
import matplotlib as mlp
mlp.use("Agg")
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(1.0,1.5))
X = np.arange(0,12,0.01)
data = np.sin(X) + np.random.normal(0, 0.005, (len(X),))
plt.plot(X, data, color='b', linewidth=0.06)
plt.scatter(X, data, color='k', s=0.05, linewidths=0)
fig.savefig("res.pdf", bbox_inches='tight')
fig.savefig("res.png", bbox_inches='tight', dpi=5000)
```

### Actual outcome

The Pdf looks like this:
![grafik](https://user-images.githubusercontent.com/60299675/197529950-050d3ad5-8952-417a-8244-5e054c93b1f5.png)

When zooming in on the details, the blue points and black line are not aligned:
![grafik](https://user-images.githubusercontent.com/60299675/197530548-81d17424-d0c6-42b8-bfc9-e2c34e809201.png)

### Expected outcome

The PNG image (with very high DPI) looks like this:
![grafik](https://user-images.githubusercontent.com/60299675/197529609-3195f09b-6c22-44b9-8640-a9c97c4245d5.png)

When zooming in on the details, we get the following result (the blue points and black line are aligned):
![grafik](https://user-images.githubusercontent.com/60299675/197529719-18b804c2-7f6e-4ed6-8492-7a558f8d8e8b.png)

### Additional information

The misalignment was visible across different backends (Agg, Pdf, Pgf) with very similar results (but maybe least prominent for Pgf). I have also tested several Pdf viewers.

The misalignment is also visible against the `plt.fill_between()` lines (and visible even without zooming in):
![grafik](https://user-images.githubusercontent.com/60299675/197531777-5996c595-eb8f-4948-a2cb-ebc83833f7db.png)

I have provided another example with the same setting and very pronounced misalignment [here](https://stackoverflow.com/questions/74147057/matplotlib-lines-appear-not-to-be-accurate-when-plotting-to-pdf).

### Operating system

Windows

### Matplotlib Version

3.6.1

### Matplotlib Backend

Agg

### Python version

3.10.6

### Installation

conda

**Comment by tacaswell** [comment]
The culprit here is likely a combination of path simplification, the tiny figure size, and the effective DPI used for the pdf being 72.

See https://matplotlib.org/stable/users/explain/performance.html#line-segment-simplification for details, but 

```python
mpl.rcParams['path.simplify'] = False
```

is probably the fix you want.

**Comment by jan-grass** [comment]
Thanks a lot. This fixes the problem!
