### ISSUE TITLE
[ENH]: Scale Invariant Arrow Styling

### ISSUE THREAD

**Issue by suuuehgi** [matplotlib/matplotlib#24272]
### Problem

When using `pyplot.arrow`, the coordinates `x, y, dx, dy` are within the same coordinate system than the styling kwargs, resulting in different appearances, when used on multiple plots with different scales.

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(nrows=3, layout='constrained')

for ii, ax in enumerate(axs.flat):

    ax.set_xlim( [ ii/5, 1 - ii/5 ] )
    ax.set_ylim( [ .5 - (ii+1)/50, .5 + (ii+1)/50 ] )

    ax.arrow( 1 - ii/5, .5, 2 * ii/5 - 1, 0, length_includes_head=True, linewidth=0, width=.01 )
```

![arrows](https://user-images.githubusercontent.com/7861774/197810373-fb3466bd-7c24-4590-92f2-1363e2c5cc09.jpg)

`transform=ax.transAxes` transforms both, placement and appearance, resulting in homogeneous appearance and hard to handle placement.

![arrows2](https://user-images.githubusercontent.com/7861774/197811685-7e2e26ca-5114-4f82-aa09-8eacec374ad0.jpg)

### Proposed solution

Having coordinates `x, y, dx, dy` in data coordinates and styling kwargs in axes coordinates.

(And `length_includes_head=True` as default *cough*)

**Comment by jklymak** [comment]
I'm going to close this, as there are quite a few issues saying the same thing.   We should boost it to the call this week, but I think the plan is to deprecate arrow: https://github.com/matplotlib/matplotlib/issues/20387

**Comment by suuuehgi** [comment]
> I'm going to close this, as there are quite a few issues saying the same thing.

Sorry, I haven't found them.

> We should boost it to the call this week [...]

All right, thank you!

In the meantime, is there anything other than a manual / cumbersome transformation like `ax.transAxes.inverted().transform(ax.transData.transform((x,y)))`?

**Comment by tacaswell** [comment]
`ax.annotate` is probably the best option https://matplotlib.org/stable/tutorials/text/annotations.html#sphx-glr-tutorials-text-annotations-py when used with an empty string.

**Comment by suuuehgi** [comment]
> `ax.annotate` is probably the best option https://matplotlib.org/stable/tutorials/text/annotations.html#sphx-glr-tutorials-text-annotations-py when used with an empty string.

Nice! 🥳 I store it in my box of secret mpl knowledge next to the `get_xticks`-thing. 😋

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(nrows=3, layout='constrained')

for ii, ax in enumerate(axs.flat):

    ax.set_xlim( [ ii/5, 1 - ii/5 ] )
    ax.set_ylim( [ .5 - (ii + 1) / 50, .5 + (ii + 1) / 50 ] )

    ax.annotate( "", xytext=(1 - ii/5, .5), xy=(ii/5, .5), arrowprops={ 'width':2, 'linewidth':0 } )
```

![arrow](https://user-images.githubusercontent.com/7861774/198023734-132a63d5-9c59-44d9-901d-5a38837fb976.jpg)

**Comment by timhoffm** [comment]
Should we put a note admonition in the arrow docstring? I mean it’s documented in the notes section, but that can be overlooked easily.
