### ISSUE TITLE
[Bug]: Saving window no responding when I try to save a figure

### ISSUE THREAD

**Issue by SM6251** [matplotlib/matplotlib#24292]
### Bug summary

When I try to save a figure plotted with matplotlib in iPython3 (Qt5Agg backend) I can not select other directory than the default one because the pop-up saving window is irresponsive, only save and cancel buttons work. This only happens when interative=True ( plt.ion() ) though. In a addition when I click on "save" I get the following warning:

Gtk-Message: 14:53:05.865: GtkDialog mapped without a transient parent. This is discouraged.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.ion()
plt.plot((1,2,3,4,5))
```

### Actual outcome

Gtk-Message: 14:53:05.865: GtkDialog mapped without a transient parent. This is discouraged.

### Expected outcome

Not a frozen window 

### Operating system

Xubuntu

### Matplotlib Version

3.3.4

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.6.9

### Installation

pip

**Comment by tacaswell** [comment]
Which IPython version are you using?  If it is indeed something from the 3 series (which is from ~2015), some of the automatic integrations may not be there.

If you use the
```
%matplotlib
```
magic does it work?

Also see https://matplotlib.org/stable/users/explain/interactive.html

I'm also a bit confused why gtk errors are coming out of the qt backend.

**Comment by SM6251** [comment]
ipython3 --version
7.16.3 

The magic command works, but shows this:

In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/sadig/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
Using matplotlib backend: Qt5Agg

**Comment by tacaswell** [comment]
Those warnings are a bit odd, but are harmless.  

I also just read more carefully the mpl version of see you are on 3.3 which we no longer support.  Do you have similar issues with mpl 3.6?

If using the magic fixes the problem and you can not reproduce this issue on a newer version of Matplotlib I would like to close this issue with no further action.

**Comment by jklymak** [comment]
I'll close for lack of response.
