### ISSUE TITLE
[Doc]:  Axes limits not updated in animate decay

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#24296]
### Documentation Link

https://matplotlib.org/devdocs/gallery/animation/animate_decay.html#sphx-glr-gallery-animation-animate-decay-py

### Problem

Animate decay claims it shows how to `changing axes limits during an animation` in the run method

``` python
def run(data):
    # update the data
    t, y = data
    xdata.append(t)
    ydata.append(y)
    xmin, xmax = ax.get_xlim()

    if t >= xmax:
        ax.set_xlim(xmin, 2*xmax)
        ax.figure.canvas.draw()
    line.set_data(xdata, ydata)
```
but the limits aren't actually changing:

https://user-images.githubusercontent.com/1300499/198712225-68dc2c33-aa64-4ee3-8e82-b40d013f5e23.mp4

### Suggested improvement

Either option is fine with me:

* fix code so xlims dynamically updated
* remove lim updating code and statement saying this example shows how to update limits

**Comment by QuLogic** [comment]
The example works, but that's the default xlim, and it is not running long enough in the docs to show the change. I'm not sure where the cutoff is, as the code itself runs infinitely.

**Comment by oscargus** [comment]
Slightly related to https://github.com/matplotlib/matplotlib/pull/24131 (which removes the automatic truncation).
