### ISSUE TITLE
[ENH]: Set connector line properties directly from indicate_inset

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#24317]
### Problem

According to https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.indicate_inset.html#matplotlib.axes.Axes.indicate_inset
`edgecolor`, `facecolor`, `alpha` and `zorder` are set on both the rectangle can connector lines. However, it can be quite convenient to be able to set other line properties, such as `linestyle` and `linewidth` directly as well, which are now passed to the rectangle only. 

### Proposed solution

As it is not a good idea to change the behavior, I suggest that a `connector_kw` argument is added so that those can be passed directly.

**Comment by timhoffm** [comment]
Isn’t this issue #23424 / PR #24082 ?

**Comment by oscargus** [comment]
Correct... I did search but didn't find it...
