### ISSUE TITLE
[Doc]: Lazy loading for images

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#24331]
### Problem

Since docutils 0.18.2, there is a global config option [image-loading](https://docutils.sourceforge.io/docs/user/config.html#image-loading). This sets the [loading](https://www.w3schools.com/tags/att_img_loading.asp) attribute of `<img>`.

Applying this to our docs should be as simple as adding the following to `doc/docutils.conf`:
```
[html5 writer]
image_loading: lazy
```

However, in a quick test this did not seem to have any effect on my machine. Can somebody else please try this?

**Comment by sam-sw** [comment]
I'm not sure that adding the `image_loading: lazy` option under `[html5 writer]` works, but I get images set with the `loading="lazy"` attribute if I add the option under the pre-existing `[html4css1 writer]`.

At a first glance images within anchor tags (for instance the logo or image link to 'Matplotlib cheatsheets' on the main page) don't appear to have the lazy-loading attribute, but other images (for instance on the 'Plot types' page) do.
