### ISSUE TITLE
[Bug]: y axis scrambled when 2D plotting from a long list

### ISSUE THREAD

**Issue by mcba** [matplotlib/matplotlib#24348]
### Bug summary

For a particular dataset, a simple 2D plot has a completely scrambled y axis when the number of data points is large, even if the points are outside the limits to be plotted.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import pandas as pd

# Uncomment the following line to show the bug.
data = pd.read_csv("https://mcba1.phys.unsw.edu.au/~mcba/mpl-bug.csv")

# Use the following line instead of the one above to show the expected result.
#data = pd.read_csv("https://mcba1.phys.unsw.edu.au/~mcba/mpl-bug.csv", nrows = 1000)

plt.plot(data['x'], data['y'])
plt.xlim(100,200)
plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/6678959/199659809-d50a0882-b33b-48cc-a18c-d6c629bfedb4.png)

### Expected outcome

![Figure_2](https://user-images.githubusercontent.com/6678959/199659899-c6f917c7-b4a9-47de-abbf-94808c4dc820.png)

### Additional information

The CSV file begins like this:

x,y
0,103.51
1,103.556
2,103.593
3,103.642

and continues for a total of 126503 lines. The first column is just the index.

The bug seems to happen at a fixed number of lines read from the CSV file. E.g., 30000 lines works fine and plots the data in under a second, 40000 lines shows the bug and uses 100% CPU for 30 seconds. The subset of data plotted should be the same in both cases, since we are only plotting from index 100 to 200.

When the bug occurs, the y axis is multivalued, i.e., as you move the cursor up the y axis you see the y value going up and down, not monotonically increasing.

Converting the pandas data structures to Python lists prior to plotting makes no difference.

### Operating system

Ubuntu 20.04 and 22.04

### Matplotlib Version

3.6.0

### Matplotlib Backend

GTK3Agg

### Python version

Python 3.8.10

### Installation

pip

**Comment by QuLogic** [comment]
```
>>> data = pd.read_csv("https://mcba1.phys.unsw.edu.au/~mcba/mpl-bug.csv")
>>> data.dtypes
x     int64
y    object
```

Your `y` data is a bunch of strings and treated as categoricals. If you want them to be treated numerically, you need to convert them to numbers.

**Comment by ksunden** [comment]
You can fix your particular dataset by passing `na_values = "#VALUE!"` to the `read_csv` call, which will replace that string with NaN

**Comment by timhoffm** [comment]
In case somebody else stumbles over this. Here is the full explanation: https://matplotlib.org/stable/users/faq/howto_faq.html#why-do-i-have-so-many-ticks-and-or-why-are-they-out-of-order

**Comment by mcba** [comment]
Thanks everyone for the quick replies, and sorry to bother you. I did check the types of the two columns and verified they were int64 and float64, but this must have been with a subset of the CSV file. The problem was caused by this single line in the CSV file:

31963,#VALUE!

Thanks again.
