### ISSUE TITLE
xaxis alignment non linear on input array not starting at 0

### ISSUE THREAD

**Issue by madmin23** [matplotlib/matplotlib#24345]
I encountered an issue were the value 0.5 on the x-axis would not appear in the middle between the tickmarks '0' and '1', but rather in the first third. Mouseover coordinates would still show correct values.
minimal code example:
```
import numpy as np
import matplotlib.pyplot as plt
simplelist=np.arange(0.5,5.0,0.1)
plt.plot(simplelist,simplelist)
plt.show()
```
this error does not appear when the array is starting at 0:
```
import numpy as np
import matplotlib.pyplot as plt
simplelist=np.arange(0,5.0,0.1)
plt.plot(simplelist,simplelist)
plt.show()
```

**Comment by tacaswell** [comment]
Can you please include a saved image showing this issue?  If I run this code with the default settings the left edge of the data limits in 0.28 not 0 so 0.5 is in the correct place.

```python
import numpy as np
import matplotlib.pyplot as plt
simplelist=np.arange(0.5,5.0,0.1)
plt.plot(simplelist,simplelist)
print(plt.gca().get_xlim())
plt.show()
```

prints

```
(0.28, 5.119999999999998)
```

**Comment by madmin23** [comment]
In the first image (bugged version, array starting at 0.5) you can see that the value '0.5' is not actually in the middle of '0' and '1'
![bugged_array_0p5](https://user-images.githubusercontent.com/98223634/199515568-9ae263dc-8df1-4a41-b62d-1d53b8e42aba.png)

If the array starts at 0 though:
![correct_array_0](https://user-images.githubusercontent.com/98223634/199515588-7fafecc6-c044-4d2f-bfaf-20c228d2fab4.png)

the axis has correct linear scaling.

**Comment by madmin23** [comment]
Okay worked it out! It's just the lower xlim defaulting to a value which looks visually confusing, but is working as intended i gues. I'm closing this now, sorry for the inconvenience

**Comment by tacaswell** [comment]
See the discussion at https://matplotlib.org/stable/users/prev_whats_new/dflt_style_changes.html#auto-limits with notes on how to change the auto-limit behavior always put the view limits at "nice" values (rather than a "nice pad" away from the data).

**Comment by tacaswell** [comment]
I took the liberty of changing the issue title to one that will cause maintainers heart rate to jump less when they scroll by it ;)
