### ISSUE TITLE
Move mimetypes from webagg to backend_bases

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#2434]
It might be better if the mimetype was stored along side the extensions of the various image types we support so that multiple backends could take advantage of them.

Follow on to #2311.  @andreabedini

**Comment by petehuang** [comment]
This is still up for grabs. Look here if interested:

https://github.com/matplotlib/matplotlib/blob/master/examples/user_interfaces/embedding_webagg.py#L138
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_webagg.py#L186

**Comment by anntzer** [comment]
We're not making use of that info in any other backend, so it's just fine staying in backend_webagg for now rather than becoming another public API (IMO).
