### ISSUE TITLE
[ENH]: imshow support for multiple slice image volume

### ISSUE THREAD

**Issue by ustcfdm** [matplotlib/matplotlib#24360]
### Problem

I need to display an image volume with multiple slices, similar to [sliceViewer](https://ww2.mathworks.cn/help/images/ref/sliceviewer.html) in Matlab. However, the current [imshow](https://matplotlib.org/stable/plot_types/arrays/imshow.html#imshow-z) function only supports RBG(A) or 2D scalar data.

### Proposed solution

The code example [here](https://matplotlib.org/stable/gallery/event_handling/image_slices_viewer.html#image-slices-viewer) shows how to display multiple slice images, but there is a lot of code to write, which is not convenient. Maybe one solution is to provide a wrap function (i.e. `imshow_3d` or `slice_viewer`) that implements the example code somehow?

**Comment by ustcfdm** [comment]
I just tried to write a wrap function for the example code [here](https://matplotlib.org/stable/gallery/event_handling/image_slices_viewer.html#image-slices-viewer), but the scroll wheel doesn't work. The reason is beyond my knowledge. Does anyone know why?

**Comment by oscargus** [comment]
Does the example work if you just run the example code as is? (Just to work out if it is an OS/backend issue or not. For reference it works for me on CentOS 7 with QtAgg.)

**Comment by ustcfdm** [comment]
> Does the example work if you just run the example code as is? (Just to work out if it is an OS/backend issue or not. For reference it works for me on CentOS 7 with QtAgg.)

Thanks for your reply. I figured that I have to return and receive the variable `tracker` to make the scroll wheel work. I guess this is related to the life cycle of variable `tracker`? An example code is below:

```python
import numpy as np
import matplotlib.pyplot as plt

# Fixing random state for reproducibility
np.random.seed(19680801)

class IndexTracker:
    def __init__(self, ax, X):
        self.ax = ax
        ax.set_title('use scroll wheel to navigate images')

        self.X = X
        rows, cols, self.slices = X.shape
        self.ind = self.slices//2

        self.im = ax.imshow(self.X[:, :, self.ind])
        self.update()

    def on_scroll(self, event):
        print("%s %s" % (event.button, event.step))
        if event.button == 'up':
            self.ind = (self.ind + 1) % self.slices
        else:
            self.ind = (self.ind - 1) % self.slices
        self.update()

    def update(self):
        self.im.set_data(self.X[:, :, self.ind])
        self.ax.set_ylabel('slice %s' % self.ind)
        self.im.axes.figure.canvas.draw()


def imshow_3d(img):
    fig, ax = plt.subplots()
    tracker = IndexTracker(ax, img)
    fig.canvas.mpl_connect('scroll_event', tracker.on_scroll)
    
    return tracker


X = np.random.rand(20, 20, 40)

# scroll wheel does not work
imshow_3d(X)

# scroll works
whatever = imshow_3d(X)

```

This is not an elegant solution though, because I have to return the variable `tracker`. In addition, the y label is occupied by slice index. An ideal solution is something like [sliceViewer](https://ww2.mathworks.cn/help/images/ref/sliceviewer.html) in Matlab, which has a slider to allowing changing slices.

**Comment by ksunden** [comment]
Also, if your primary goal is a nice, interactive, viewer for multidimensional image data, you may be interested in https://napari.org

**Comment by tacaswell** [comment]
> I guess this is related to the life cycle of variable tracker? An example code is below:

Yes, we only hold onto weak refs to the objects when the callbacks get registered so when the object get garbage collected the callbacks go away and hence no interaction.  (There has been some discussion of changing that so our callbacks hold hard references but that is _well_ outside of scope here).

In addition to (as time suggests) making it clear in this example you need to keep the tracker alive, it might be worth adding a linked slider from `matplotlib.widgets`?

**Comment by tacaswell** [comment]
Tasks:
 - add note about keeping tracker alive (easy difficulty)
 - add linked slider to example (medium difficulty)

Adding the slider is medium because it will require linking some callbacks and convincing everyone it is a good idea ;)

**Comment by timhoffm** [comment]
I'm -0.5 on adding a slider. This makes the example much more complex and is outside the scope of the event-handing topic.

**Comment by jklymak** [comment]
I wonder if the title of the example should be changed?  If you search image slicing in Python on Google, you get this page which is not very good for the stated purpose and not the actual point of the example.

**Comment by timhoffm** [comment]
I don't get Matplotlib on the first page of google results :man_shrugging: 

Anyway, changing the title is a good idea -> done.
For simplicity, I've kept the filename.
