### ISSUE TITLE
[Bug]: TextBox does not work with MacOSX backend

### ISSUE THREAD

**Issue by rkishony** [matplotlib/matplotlib#24372]
### Bug summary

When creating widgets.TextBox with MacOSX backend, the text box is shown but cannot be edited.

### Code for reproduction

```python
%matplotlib osx
import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox
TextBox(ax=plt.gca(), label='radius', initial='2')
```

### Actual outcome

TextBox appear but is not active

### Expected outcome

TextBox should allow editting

### Operating system

osx

### Matplotlib Version

2.5.3

### Matplotlib Backend

MacOSX

### Python version

3.10

### Jupyter version

6.4.12

### Installation

pip

**Comment by QuLogic** [comment]
> ```python
> TextBox(ax=plt.gca(), label='radius', initial='2')
> ```

You need to assign this to something so it doesn't get garbage collected, as noted in its docs.

**Comment by rkishony** [comment]
The bug persists even if we keep a reference to the TextBox.

Namely, the following code produce a TextBox that is non-editable on MaxOSX backend (yet, it is ok on TK backend):

```python
%matplotlib osx
import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox
h = TextBox(ax=plt.gca(), label='radius', initial='2')
```

**Comment by greglucas** [comment]
I'm able to edit the textbox on current main, so I think this has likely been fixed in a more recent version. 2.x is quite an old version of Matplotlib now and there has been a lot of work on the macosx backend since then.

**Comment by rkishony** [comment]
fantastic - thanks !
btw: the original issue was raised for Ver 3.5.3 (2.5.3 was a typo - sorry)
