### ISSUE TITLE
log scale and polar broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#24383]
[09192022_NaCl_0-2mmS_3mmD_0D_0-0.01inc_0.5dpm(high res).txt](https://github.com/matplotlib/matplotlib/files/9944614/09192022_NaCl_0-2mmS_3mmD_0D_0-0.01inc_0.5dpm.high.res.txt)

Example of working code is:

```python
     fig, ax = subplots( 1, 1,
                        figsize=(8, 8),
                        subplot_kw={ 'projection':'polar' },
                        )
    xvals, yvals = data
    # yscale('log')
    # ax.set_theta_zero_location( 'N' )
    # ax.set_theta_direction( -1 )
    # ax.set_rscale( 'log' )
    # ax.set_rlim((0,max(yvals)))
    
    polar( xvals, yvals,
             label=params.get( 'datalabel' ),
             )
    
    savefig( f"{params.get( 'fname' )}_polar" )
    close( fig=fig )
```

Plot functions correctly(ish) but when set to a log-plot the plot malfunctions: the error ""posx and posy should be finite values"" and the entire plot is a blank circle. The 'r' labels are still not correct normally.

_Originally posted by @Gerald-Meyers in https://github.com/matplotlib/matplotlib/issues/11202#issuecomment-1304637288_

**Comment by tacaswell** [comment]
@Gerald-Meyers could you possibly trim that data down to the minimal needed to reproduce (or is this not data dependent)?

**Comment by chahak13** [comment]
This bug doesn't seem data dependent. Here's a small reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, figsize=(8, 8),
                        subplot_kw={'projection': 'polar'})
xvals, yvals = [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]
ax.plot(xvals, yvals)
ax.set_yscale('log')
plt.show()
```
Which gives this error
```
/home/chahak/Documents/matplotlib/issue_24383.py:14: UserWarning: Attempt to set non-positive ylim on a log-scaled axis will be ignored.
  plt.show()
posx and posy should be finite values
posx and posy should be finite values
```

**Comment by ksunden** [comment]
Appears to be related to `RadialLocator.view_limits`

https://github.com/matplotlib/matplotlib/blob/9d8fde258d66168f20800155af614c8ca0bb8e24/lib/matplotlib/projections/polar.py#L434-L439

In particular I'm suspicious that the vmin capping at 0 may not be desirable with log scale, but haven't fully worked out the details.

**Comment by QuLogic** [comment]
The 0 cap was added to preserve old behaviour from when it didn't support negative radii. However, I don't think log scales were supported then either.

**Comment by dstansby** [comment]
I've idependently stumbled upon this investigating something else. An even smaller example:
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.set_yscale('log')

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/6197628/201484399-f5c6bd8b-fd8a-4eae-a678-503d0bfc0689.png)
```python
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
/Users/dstansby/github/matplotlib/lib/matplotlib/scale.py:253: RuntimeWarning: overflow encountered in power
  return np.power(self.base, a)
```

**Comment by dstansby** [comment]
At least one issue is the polar limits are not being set to finite values (ie. on a log scale, vmin > 0):
```python
import matplotlib.pyplot as plt

for kw in [{}, dict(subplot_kw={'projection': 'polar'})]:
    fig, ax = plt.subplots(**kw)
    ax.set_yscale('log')
    print(ax.get_ylim(), kw)
```

(0.8912509381337456, 11.220184543019636) {}
(0.0, 1.0) {'subplot_kw': {'projection': 'polar'}}

**Comment by Gerald-Meyers** [comment]
> @Gerald-Meyers could you possibly trim that data down to the minimal needed to reproduce (or is this not data dependent)?

I can assure you I tested this on 6 different data sets. The data is not the problem. It it matters, you are more than welcome to slice the data when you np.genfromtxt. The polar plot did function as expected without radial log-scale. However, the circular grid lines for the r values ranged from 0 to 1, not from 0 to 1e7.

For example, here is normal plot of one of my data sets without any log-scale over the domain [20,80]=Δ60 degrees. 
![image](https://user-images.githubusercontent.com/5313641/201495012-4fa921ef-2251-421f-a24b-33ef4469607d.png)

Here is the same data set, but with the extra line of code
fig, ax = subplots( 1, 1,
                        figsize=(8, 8),
                        subplot_kw={'projection':'polar'} # <- extra line
                        )
![image](https://user-images.githubusercontent.com/5313641/201495068-fb4f773a-41ef-4361-a9b3-5c67297cfd21.png)

And the same polar plot when I enable the radial log-scale with 
plt.yscale('log')
![image](https://user-images.githubusercontent.com/5313641/201495100-b1beeaa8-bc88-4ddd-a57a-e0c7af8e1ee5.png)


Here is another data set over a 1 degree domain.
![image](https://user-images.githubusercontent.com/5313641/201495137-6d974d93-f2dd-48e0-a5b6-b85f9192da59.png)

And the same data with polar as before.
![image](https://user-images.githubusercontent.com/5313641/201495156-c42a1be7-6ec8-433f-ad1c-ba22e8d71821.png)

And with log scale.
![image](https://user-images.githubusercontent.com/5313641/201495169-85f90e0b-9bfd-46e5-85d5-0f694642c95f.png)

**Comment by Gerald-Meyers** [comment]
[09192022_NaCl_0-2mmS_3mmD_0D_0-0.01inc_0.5dpm(high res).txt](https://github.com/matplotlib/matplotlib/files/9996002/09192022_NaCl_0-2mmS_3mmD_0D_0-0.01inc_0.5dpm.high.res.txt)
[09192022_NaCl_2mmS_3mmD_1D_0-0.05inc_0.5dpm(no shield).txt](https://github.com/matplotlib/matplotlib/files/9996003/09192022_NaCl_2mmS_3mmD_1D_0-0.05inc_0.5dpm.no.shield.txt)
[09192022_NaCl_2mmS_3mmD_1D-0-0.05inc_0.5dpm.txt](https://github.com/matplotlib/matplotlib/files/9996004/09192022_NaCl_2mmS_3mmD_1D-0-0.05inc_0.5dpm.txt)
[09212022_LiF_0-2mmS_3mmD_0D_0-01inc_0-5dpm(high res).txt](https://github.com/matplotlib/matplotlib/files/9996005/09212022_LiF_0-2mmS_3mmD_0D_0-01inc_0-5dpm.high.res.txt)
[09212022LiF_2mmS_3mmD_1D_0-05inc_10dpm(no shield).txt](https://github.com/matplotlib/matplotlib/files/9996006/09212022LiF_2mmS_3mmD_1D_0-05inc_10dpm.no.shield.txt)
[09212022LiF_2mmS_3mmD_1D_0-05inc_10dpm(shield).txt](https://github.com/matplotlib/matplotlib/files/9996007/09212022LiF_2mmS_3mmD_1D_0-05inc_10dpm.shield.txt)

In any case, here is the rest of the data I was using.

**Comment by ZhiweiBai** [comment]
I found a solution to this problem, just upgrade the package `pip install --upgrade matplotlib`
