### ISSUE TITLE
[Bug]: plt.tight_layout() after layout='constrained' should at least warn

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#24387]
If a user does something like

```python
fig, axs = plt.subplots(2, 2, layout='constrained')
..
plt.tight_layout()
```
`tight_layout` is called, and `constrained_layout` is ignored.  This was originally done because `constrained_layout` was experimental.  However, people seem to think `constrained_layout` is not working because they have copy-and-pasted, or reflexively added `plt.tight_layout`.  

I'd propose that we at least warn if `plt.tight_layout` is called on a figure with an active layout manager.  I'd also be open to this being an error.

**Comment by timhoffm** [comment]
Yes.
