### ISSUE TITLE
[Doc]: alpha setting for annotation `TextArea`

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#24390]
### Bug summary

I've been adding annotations following the excellent examples at [AnnotationBbox demo](https://matplotlib.org/stable/gallery/text_labels_and_annotations/demo_annotation_box.html#sphx-glr-gallery-text-labels-and-annotations-demo-annotation-box-py), but I'd like to make the text box transparent.  From the [TextArea docs](https://matplotlib.org/stable/api/offsetbox_api.html#matplotlib.offsetbox.TextArea.set) it looks like `my_text_area.set(alpha=x)` should work, but it doesn't seem to have any effect.

Perhaps there is another way to set this that I have missed?

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.offsetbox import TextArea, AnnotationBbox

import numpy as np

rng = np.random.default_rng()

data = rng.normal(size=30)

plt.rcdefaults()

_ , ax = plt.subplots()
ax.hist(data)

offsetbox = TextArea('Look over there!')
offsetbox.set(alpha=0.3)

ab = AnnotationBbox(offsetbox, (0.8, 0.8),
            xybox=(0, 1),
            xycoords='axes fraction',
            boxcoords='data',
            arrowprops=dict(arrowstyle="->"))

ax.add_artist(ab)

plt.show()
```

### Actual outcome

![mpl_annotation_box_alpha](https://user-images.githubusercontent.com/10599679/200327684-8719ff0a-93b1-4f13-90df-aa365105eb55.png)

### Expected outcome

The text box should be transparent.

### Additional information

I tried a few versions back to 3.3, but the result was the same.

### Operating system

RHEL7

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

3.8.13

### Jupyter version

N/A

### Installation

conda

**Comment by QuLogic** [comment]
You'll need to pass `bboxprops=dict(alpha=0.3)` to the `AnnotationBbox`. The `TextArea` does not draw any background.

**Comment by rcomer** [comment]
Thanks @QuLogic, that did the trick.  So I guess there isn't actually a bug here.  Possibly a documentation issue?  Or should we close this?

**Comment by oscargus** [comment]
Seems like there arguments are not documented: `bboxprops=None, arrowprops=None, fontsize=None` so that can for sure be a good idea. Probably with a comment about how to make it transparent (which seems like a common enough use case).
