### ISSUE TITLE
[Doc]: font_manager docs show header in quote box; backend_tools docs header is a link

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#24398]
### Documentation Link

https://matplotlib.org/stable/api/font_manager_api.html https://matplotlib.org/stable/api/backend_tools_api.html

### Problem

Compare the rendered font_manager docs with the backend_tools (or any other module) docs:
![fm](https://user-images.githubusercontent.com/1322974/200562171-ffbab0c3-52e8-4059-92d9-a1357fc7a993.png)
![bt](https://user-images.githubusercontent.com/1322974/200562185-117ff428-c089-4f88-aafd-22d6064355bd.png)
The toplevel font_manager text ("A module for finding, managing, and using fonts across platforms...") is in a quote box, slightly grayed out; it shouldn't be so (as is the case for all other modules).
The backend_tools toplevel header ("matplotlib.backend_tools") is a link to itself; it shouldn't be so (as is the case for all other modules).

**Comment by timhoffm** [comment]
- `backend_tools` issue fixed in #24402 
- I don't understand why there is a quote box in `font_manager`

**Comment by QuLogic** [comment]
The `font_manager` bit doesn't happen for me locally; also, the sidebar uses regular text instead of code for every entry. Possibly this is because my local environment is still on pydata-sphinx-theme 0.9.0.
