### ISSUE TITLE
Grid and line display problems

### ISSUE THREAD

**Issue by CZH-cpu** [matplotlib/matplotlib#24442]
![pro1](https://user-images.githubusercontent.com/70466243/201512844-18bd6100-fac7-4b61-bc0c-2c4d5b43be78.png)
![pro2](https://user-images.githubusercontent.com/70466243/201512878-b30b8b29-824a-4348-8c26-8caad74522c2.png)
In the generated image, the grid and lines are interrupted, how can I solve it?

**Comment by timhoffm** [comment]
It looks like you are plotting an extra dashed white line.

If that's not the issue, please provide a minimal code example showing the effect. Otherwise, we can't investigate the issue and can't help.

**Comment by CZH-cpu** [comment]
It's the unexpected white line, thank you!
