### ISSUE TITLE
[MNT]: Fix or drop support for Tk 8.4

### ISSUE THREAD

**Issue by daniilS** [matplotlib/matplotlib#24450]
### Summary

Currently, the minimum version of Tcl/Tk supported by mpl is 8.4, which is also the [lowest supported version](https://github.com/python/cpython/blob/82ca2839c9ec6bf9a9400e791a52411824df67f3/Modules/_tkinter.c#L10-L15) for CPython 8.5-8.10. However, as highlighted in #8680, we don't fully support 8.4: [`show()`](https://github.com/matplotlib/matplotlib/blob/1fa74675ac38f768090525b6acad1fecd7db61f6/lib/matplotlib/backends/_backend_tk.py#LL533-L534) uses the `-topmost` attribute, which was only added to Linux in 8.5, and [`full_screen_toggle()`](https://github.com/matplotlib/matplotlib/blob/1fa74675ac38f768090525b6acad1fecd7db61f6/lib/matplotlib/backends/_backend_tk.py#LL569-L571) uses `-fullscreen`, which only worked on Mac OS X before 8.5.

However, I haven't seen a single other bug report using 8.4, and can't find any builds of Python 3.8+ that ship with it, so that may explain the lack of issues other than #8680.

### Proposed fix

Two options:
- Fix support for 8.4, catching TclErrors in the two functions above
- Drop support for 8.4. This would allow, among other things, [setting a default](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/_backend_tk.py#LL822-L827) and retrieving the selected format in Tk "save figure" dialogs, and using native Ttk widgets in any future updates (such as if anyone ever decides to port figureoptions to Tk).

**Comment by timhoffm** [comment]
To 8.5 was released in 2007. I claim that anybody who must rely on versions older than that should not need future Matplotlib versions. - And the lack of feedback on the currently broken support backs that. So let's bump the dependency and not bother to implement a fix.

**Comment by daniilS** [comment]
Great, in that case I'll make a PR soon for the updated save dialog and see if there's any other changes we can now make.
