### ISSUE TITLE
[Bug]: Default plot color cycler

### ISSUE THREAD

**Issue by alex-luci** [matplotlib/matplotlib#24452]
### Bug summary

When updating from version 3.5.0 to 3.6.2, the default plot color cycler changed and there's no documentation indicating it should have. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.style.use('_mpl-gallery')
fig, ax = plt.subplots()
for num in [1, 2, 3, 4]:
    ax.plot(0, num, 'o')

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/112210700/201736510-70047b42-cd01-4c24-8655-f47c6d8a36c8.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/112210700/201736741-ad418fb7-fa68-4f59-8c6d-741f83396056.png)

### Additional information

Documentation says that the default cycler should be:
```
('color', ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'])
```
It displays expected colors in version 3.5.0, but not in version 3.6.2.

Found fix:
```
import matplotlib as mpl
from cycler import cycler
mpl.rcParams['axes.prop_cycle'] = cycler('color', [ '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'])
```
But that should not be necessary as that should be the default

### Operating system

Ubuntu

### Matplotlib Version

3.6.2

### Python version

3.8.10

### Installation

pip

**Comment by tacaswell** [comment]
That is an internal style file, this is not a regression.

**Comment by alex-luci** [comment]
I did not have a specific reason for using the mpl-gallery style. Removed that and colors are as expected. Thank you!
