### ISSUE TITLE
Open Internet Explorer with make show [Documentation]: 

### ISSUE THREAD

**Issue by sajjad-ali60** [matplotlib/matplotlib#24451]
### Bug summary

I have built documentation by `make html`. It built the documentation with some warnings.
After the documentation i opened the folder `/build/html/` folder but couldn't find any html files. Then execute the `make show` command, it opens the internet explorer and nothing shown there. my default browser is microsoft edge.
I don't know why is this happening.
[here](https://1drv.ms/t/s!Ak1RUL7i7AyEgjTKJ28bbPNbRXVY?e=dPN3Nd) are logs while building documentation

### Code for reproduction

```python
follow the instruction given in the documentation.
```

### Actual outcome

the internet explorer is opened after Showing locally built docs by `make show`

### Expected outcome

the documentation should be shown in the form of webpages in the browser.

### Operating system

Windows 10 Pro Version	22H2

### Matplotlib Version

3.7.0.dev633+g9f96205464

### Matplotlib Backend

agg

### Python version

Python 3.10.8

### Jupyter version

IPython          : 8.6.0 ipykernel        : 6.17.0 ipywidgets       : 8.0.2 jupyter_client   : 7.4.4 jupyter_core     : 4.11.2 jupyter_server   : not installed jupyterlab       : not installed nbclient         : not installed nbconvert        : not installed nbformat         : not installed notebook         : not installed qtconsole        : not installed traitlets        : 5.5.0

### Installation

from source (.tar.gz)

**Comment by jklymak** [comment]
You seem to have a crossed install, in particular, your toolkits are not compatible with latest matplotlib.  Suggest checking your install, usually by removing the toolkit part of the install, perhaps manually.  Any follow up should be in https://discourse.matplotlib.org, as install issues are not usually actionable by the project.  Thanks for your understanding.
