### ISSUE TITLE
[Bug]: CheckBoxes should be square, not rectangular

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#24471]
### Bug summary

In #24428 I noted that RadioButtons used to be elliptical, and I fixed that in #24455 to make them circular while only emitting a deprecation warning if users tried to access the `.circles` attribute (and even then, they directly go back to the old behavior).

CheckButtons have the same issue: they are rectangular if the parent axes is not square.  This issue can (most likely) be fixed in exactly the same manner as #24455 (see https://github.com/matplotlib/matplotlib/issues/24428#issuecomment-1314952906), preferably again keeping the backcompat layer and making things transparent to end users who don't try to access individual artists.

Tagging as good first issue it should(?) mostly be doing the same thing as #24455, but medium difficulty as you need to wrangle a bit with artists and transforms.

### Code for reproduction

```python
https://matplotlib.org/stable/gallery/widgets/check_buttons.html and make the window very wide
```

### Actual outcome

Checkboxes become rectangular.

### Expected outcome

They stay square.

### Operating system

any

### Matplotlib Version

3.7.0.dev691+g218cdffb53

### Matplotlib Backend

any

### Python version

3.10

### Jupyter version

ENOSUCHLIB

### Installation

git checkout

**Comment by chahak13** [comment]
This looks like a fun problem. Can I pick this up?

**Comment by protocolog** [comment]
I am Student of BITS Pilani, India. Please assign me this issue.

**Comment by rcomer** [comment]
Hi @protocolog thank you for your enthusiasm, but there is already an open pull request to address this issue at #24474.
