### ISSUE TITLE
[Bug]: plt.tick_params() influences rounding of read pointcloud in open3d. 

### ISSUE THREAD

**Issue by cmosig** [matplotlib/matplotlib#24497]
### Bug summary

When I use `plt.tick_params()` before loading a pointcloud with open3d, the read pointcloud gets rounded to whole integer values. 

Existing stackoverflow question on this: https://stackoverflow.com/questions/74467675/rounding-of-read-pointcloud-when-using-matplotlibs-tick-params

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
import open3d as o3d

# X | line of code in question 
plt.tick_params(axis='both', labelsize=1) 

# read pointcloud
pcd = o3d.io.read_point_cloud("../pointcloud_820_1880.pcd")
points = np.asarray(pcd.points)
print(points)
```

### Actual outcome

    [[ 829. 1899.  101.]
     [ 835. 1899.  112.]
     [ 831. 1899.   92.]
     ...
     [ 821. 1899.   77.]
     [ 821. 1899.   77.]
     [ 821. 1899.   77.]]

### Expected outcome

      [[ 829.88127 1899.80715  101.29749]
       [ 835.85224 1899.55968  112.49222]
       [ 831.75095 1899.8053    92.93788]
       ...
       [ 821.95337 1899.16928   77.34216]
       [ 821.96948 1899.16988   77.6308 ]
       [ 821.97324 1899.17001   77.72527]]

### Additional information

When I remove  the line in question X, then I get the "expected outcome". I also get the expected outcome if I move the line in question below reading the pointcloud.

### Operating system

Ubuntu 20.04.5 LTS

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

Python 3.9.15

### Installation

pip

**Comment by jklymak** [comment]
As I'm sure you've surmised that seems impossible.  However, without a reproducible example we cannot investigate from our end.   I would be flabbergasted to learn that we do anything that should affect rounding on an unconnected object.

**Comment by cmosig** [comment]
I can't upload a `.pcd` file here, but below are the contents of a file with which I am able to reproduce this behavior every single time: 

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 1238796
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1
DATA ascii
829.88127 1899.80715 101.29749 7.560041649e-39
```

Also versions of the other libraries:
```
>>> import numpy; numpy.__version__
'1.22.3'
>>> import open3d; open3d.__version__
'0.15.2'
```

Do you need anything else? Happy to provide more information!

**Comment by jklymak** [comment]
Perhaps someone here has expertise with open3d but I would report this to open3d. We dont set some setting that automatically rounds data being read by other libraries.  

Does their read routine somehow use Matplotlib?   

That's not to say the bug definitely is not on our end.  Just that it's probably easier for open3d folks to guess where the problem is.

**Comment by cmosig** [comment]
@jklymak submitted to open3d (https://github.com/isl-org/Open3D/issues/5706), let's see what the response is there :)

**Comment by tacaswell** [comment]
Are the number actually rounded or did the repr change?

Can you check `sys.modules` before and after `plt.tick_params(axis='both', labelsize=1)`?  My guess is that because our final import of the backend is now super lazy we do not actually import the backends until needed and that this is a side-effect of a side-effect of an import.

**Comment by jklymak** [comment]
We change the numpy repr?

**Comment by jklymak** [comment]
Well print(10*points) would determine that.

**Comment by tacaswell** [comment]
I also can not reproduce this:

```python
✔ 09:56:55 $ ipython
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: import open3d as o3d

In [2]: plt.tick_params(axis='both', labelsize=1)

In [3]: np.asarray(o3d.io.read_point_cloud("/tmp/test.pcd").points)
Out[3]: array([[ 829.88127, 1899.80715,  101.29749]])


In [4]: import numpy; numpy.__version__
Out[4]: '1.23.4'

In [5]: import open3d; open3d.__version__
Out[5]: '0.16.0'

In [6]: import matplotlib; matplotlib.__version__
Out[6]: '3.6.2'

```

**Comment by cmosig** [comment]
> Are the number actually rounded or did the repr change?

I am not sure, the datatype in the numpy array is float64.
 
> Can you check `sys.modules` before and after `plt.tick_params(axis='both', labelsize=1)`? My guess is that because our final import of the backend is now super lazy we do not actually import the backends until needed and that this is a side-effect of a side-effect of an import.

Not sure what to look out for exactly. The length of the dictionary returned by `sys.modules` does not change, if that helps?

**Comment by cmosig** [comment]
> I also can not reproduce this:

> In [4]: import numpy; numpy.__version__
> Out[4]: '1.23.4'

my version is 1.22.3

> 
> In [5]: import open3d; open3d.__version__
> Out[5]: '0.16.0'

0.15.2 for me

> 
> In [6]: import matplotlib; matplotlib.__version__
> Out[6]: '3.6.2'
> ```

using 3.5.1

**Comment by tacaswell** [comment]
> I am not sure, but the datatype in the numpy array is float64.

Either multiply by 10 an Jody suggests or do `float(points[0, 0])`.  The question is if the value is really `1899.0` or just has the print out truncated.

>  The length of the dictionary returned by sys.modules does not change, if that helps?

Well, that blows up my import theory.

@cmosig Can you try with the latest versions of mpl and open3d ?

**Comment by cmosig** [comment]
> > I am not sure, but the datatype in the numpy array is float64.
> 
> Either multiply by 10 an Jody suggests or do `float(points[0, 0])`. The question is if the value is really `1899.0` or just has the print out truncated.

Multiplying by 10: `[[ 8290. 18990.  1010.]]`, so it does really get rounded and it's not the printout.
 
> @cmosig Can you try with the latest versions of mpl and open3d ?

Okay, I set up venv with:
```
Python 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0] on linux
>...
>>> o3d.__version__
'0.16.0'
>>> matplotlib.__version__
'3.6.2'
>>> np.__version__
'1.23.4'
```

And I get `[[ 829.88127 1899.80715  101.29749]]`, which means this behaviour does not happen for the latest versions / python3.10.

**Comment by cmosig** [comment]
@jklymak yes, you are right with the latest version of open3d and matplotlib 3.5.1, the issue is not there. matplotlib is a dependency of open3d, so maybe they do interact somehow.

**Comment by jklymak** [comment]
Let's close on our end.  Please ask for a reopen if there really is a weird side effect that we can help with. But it sounds like open3d had a bug that for some reason depended on us, and that they have fixed it.

**Comment by tacaswell** [comment]
This is a wild bug!  I am morbidly curious what the root cause is....

Even going back to you exact versions I can not reproduce this:

```python
✔ 11:31:35 $ ipython
Python 3.9.15 (main, Oct 19 2022, 14:23:40)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: import open3d as o3d

In [2]: plt.tick_params(axis='both', labelsize=1)

In [3]: np.asarray(o3d.io.read_point_cloud("/tmp/test.pcd").points)
Out[3]: array([[ 829.88127, 1899.80715,  101.29749]])

In [4]: import numpy; numpy.__version__
Out[4]: '1.22.3'

In [5]: import open3d; open3d.__version__
Out[5]: '0.15.2'

In [6]: import matplotlib; matplotlib.__version__
Out[6]: '3.5.1'

```

**Comment by cmosig** [comment]
Hmm so, I set a new virtual environment with exactly my above configuration (so the one you tried) and here I also dont get the issue. I only get the issue with my existing virtual environment. So that one must somehow be broken in a non-obvious way... wow

**Comment by tacaswell** [comment]
I would do a careful comparison of `pip list` between those two envs.....

**Comment by cmosig** [comment]
There are upwards of 50 packages where versions don't match. Don't think I want go through each and everyone of them..
I attached the list of the packages in the env where we have this behavior though.
 
[env_pip_list.txt](https://github.com/matplotlib/matplotlib/files/10043704/env_pip_list.txt)
