### ISSUE TITLE
[Bug]: Mask erosion using np.ma.mask_where()

### ISSUE THREAD

**Issue by sbonaretti** [matplotlib/matplotlib#24565]
### Bug summary

Hi, 

I am trying to overlay two images:
- `img_slice` (fig. 1) : a gray level image 
- `segm_slice` (fig. 2): a segmentation of `img_slice` 

To render the overlay, I am manipulating `segm_slice` in two ways, obtaining to different images:
- `segm_slice_masked_stack` (fig. 3): It is the corresponding rgb image, obtained with the command `np.dstack()` 
- `segm_slice_masked_where` (fig. 5): It is the corresponding masked image, obtained with the command `np.ma.mask_where()` 

When I overlay `img_slice` with one of the two manipulated segmentations, I obtain a not optimal result:
- `img_slice + segm_slice_masked_stack` (fig. 4): Obtained by fig.1 + fig. 3. The red nicely overlays the hole object region, however, there is some opacity due to alpha
- `img_slice + segm_slice_masked_where` (fig. 6): Obtained by fig.1 + fig. 5. In figure 5, the red area seems eroded and this manifests as a reduced overlay

How can I create and render `segm_slice_masked_where` (fig. 5) without erosion?

Thanks!  
Serena 

### Code for reproduction

```python
import SimpleITK as sitk
import numpy as np
import matplotlib.pyplot as plt

# load the slice
img_slice = sitk.ReadImage("slice.mha")

# gaussian to smooth the image
gaussian = sitk.SmoothingRecursiveGaussianImageFilter()
gaussian.SetSigma(0.1)
gaussian_slice = gaussian.Execute(img_slice)

# threshold the image to create the segmented binary image
segm_slice = sitk.BinaryThreshold(gaussian_slice, lowerThreshold=550, upperThreshold=np.max(sitk.GetArrayFromImage(gaussian_slice))+1, insideValue=1, outsideValue=0) # +1 to round up the decimal
segm_slice = sitk.Mask(segm_slice, sitk.Not(segm_slice > 1), 1)

# figure
plt.rcParams['figure.figsize'] = [10, 10]
fig, ax = plt.subplots(3,2)

# transform image and segmentation to numpy for compatibility with matplotlib
img_slice_np = sitk.GetArrayFromImage(img_slice)
segm_slice_np = sitk.GetArrayFromImage(segm_slice)

# calculate the mask in two ways
# 1. the binarized image is transformed in an rgb image
zero_slice = np.zeros((segm_slice_np.shape[0], segm_slice_np.shape[1]))
segm_slice_masked_stack = np.dstack((segm_slice_np, zero_slice, zero_slice))
# 2. the binarized image is transformed in a mask using masked_where
segm_slice_masked_where = np.ma.masked_where(segm_slice_np == 0, segm_slice_np)

# show the image slice
ax[0,0].imshow(img_slice_np, "gray") 
ax[0,0].set_title("img_slice") 
ax[0,0].axis("off")
ax[0,0].annotate('1', c="white", fontweight="bold", fontsize = 16, xy=(20, 350))

# show the binarized image slice 
ax[0,1].imshow(segm_slice_np, "gray") 
ax[0,1].set_title("segm_slice")
ax[0,1].axis("off")
ax[0,1].annotate('2', c="white", fontweight="bold", fontsize = 16, xy=(20, 350))

# show the image slice with the overlayed segmentation as an rgb image
ax[1,0].imshow(segm_slice_masked_stack, 'hsv', interpolation=None);
ax[1,0].set_title("segm_slice_masked_stack")
ax[1,0].axis("off")
ax[1,0].annotate('3', c="white", fontweight="bold", fontsize = 16, xy=(20, 350))
ax[1,1].imshow(img_slice_np, "gray"); 
ax[1,1].set_title("img_slice + segm_slice_masked_stack"); 
ax[1,1].axis("off")
ax[1,1].imshow(segm_slice_masked_stack, 'hsv', interpolation=None, alpha=0.3)
ax[1,1].annotate('4', c="white", fontweight="bold", fontsize = 16, xy=(20, 350))

# show the image slice with the overlayed segmentation masked using masked_where
zero_slice = np.zeros((segm_slice_np.shape[0], segm_slice_np.shape[1]))
segm_slice_masked_stack = np.dstack((segm_slice_np, zero_slice, zero_slice))
ax[2,0].imshow(segm_slice_masked_where, 'hsv', interpolation=None);
ax[2,0].set_title("segm_slice_masked_where")
ax[2,0].axis("off")
ax[2,0].annotate('5', c="black", fontweight="bold", fontsize = 16, xy=(20, 350))
ax[2,1].imshow(img_slice_np, "gray"); 
ax[2,1].set_title("img_slice + segm_slice_masked_where"); 
ax[2,1].axis("off")
ax[2,1].imshow(segm_slice_masked_where, 'hsv', interpolation=None, alpha=1);
ax[2,1].annotate('6', c="white", fontweight="bold", fontsize = 16, xy=(20, 350));
```

### Actual outcome

![masked_images](https://user-images.githubusercontent.com/13563701/204541963-e73766e6-eb87-4565-9868-6b17ad324115.png)

### Expected outcome

![masked_images](https://user-images.githubusercontent.com/13563701/204541896-50f061ba-93ff-4f0a-9453-921af9702ce4.png)

### Matplotlib Version

3.5.1

### Installation

conda

**Comment by tacaswell** [comment]
I think this is an issue of doing interpolation in data space or in RGB(A) space, however given https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html#interpolations-for-imshow 's description of what 'none' should do and 
https://matplotlib.org/stable/gallery/images_contours_and_fields/image_antialiasing.html I think we either have a bug or incorrect documentation.

**Comment by tacaswell** [comment]
I agree with @WeatherGod , we probably should be at least warning if the user passes in a colormap and an RGB(A) image.

**Comment by sbonaretti** [comment]
> I agree with @WeatherGod , we probably should be at least warning if the user passes in a colormap and an RGB(A) image.

Yes, please! There are many blogs around recommending to use `masked_where()` or `masked_array()` 
See e.g.: https://stackoverflow.com/questions/31877353/overlay-an-image-segmentation-with-numpy-and-matplotlib
