### ISSUE TITLE
Add a possibility to easily combine matshow with dendrogram to create an R-style heatmap

### ISSUE THREAD

**Issue by oxananu** [matplotlib/matplotlib#2456]
It would be nice to have an easy way of plotting an R-style heatmap using matplotlib. A plot like this is useful when visualizing hierarchical clustering results. 

An example of how it can be done in Python now: http://altanalyze.blogspot.se/2012/06/hierarchical-clustering-heatmaps-in.html 

Heatmap function in R:
http://stat.ethz.ch/R-manual/R-patched/library/stats/html/heatmap.html

**Comment by petehuang** [comment]
This hasn't been updated in a while. There has been no movement on the related issues. PRs still welcome, it'd be cool to see!

The example code linked the original post can be found here: http://code.activestate.com/recipes/578175-hierarchical-clustering-heatmap-python/

The dendrogram comes from `scipy.cluster.hierarchy` so I'm wondering what the solution in matplotlib would look like to take that as input.

Recommend labeling as Difficulty: Medium?

**Comment by timhoffm** [comment]
This can be achieved using [seaborn clustermap](https://seaborn.pydata.org/generated/seaborn.clustermap.html). It's sufficient to leave this specialized plot to the downstream library. I don't think Matplotlib itself needs to implement this.
