### ISSUE TITLE
[Bug]: TwoSlopeNorm does not work with colorbar's spacing='proportional'

### ISSUE THREAD

**Issue by davidmnielsen** [matplotlib/matplotlib#24563]
### Bug summary

Fixing vcenter with matplotlib.colors.TwoSlopeNorm streches the colorbar. The option spacing='proportional' in the colorbar function doesn't work as one would expect. Here is a [stackexchange question](https://stackoverflow.com/questions/74613524/how-to-fix-streched-colorbar-with-matplotlibs-twtoslopenorm).

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import matplotlib.cbook as cbook
from matplotlib import cm

delta = 0.01
x = np.arange(0, 2.001, delta)
y = np.arange(0.0, 2.001, delta)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

cmap = cm.seismic

fig = plt.figure(figsize=(16,5))

ax = fig.add_subplot(131)
plt.pcolormesh(Z, cmap=cmap, vmin=0, vmax=9)
plt.title('White position depends on vmin-vmax range')
plt.colorbar(extend='max')

ax = fig.add_subplot(132)
plt.pcolormesh(Z, cmap=cmap, norm=colors.TwoSlopeNorm(vmin=0, vmax=9, vcenter=1))
plt.title('White position is fixed, but colorbar is streched')
plt.colorbar(extend='max')

ax = fig.add_subplot(133)
plt.pcolormesh(Z, cmap=cmap, norm=colors.TwoSlopeNorm(vmin=0, vmax=9, vcenter=1))
plt.title('spacing="proportional" does not work')
plt.colorbar(extend='max', spacing='proportional')

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/39162069/204526002-cf64c4da-8f59-426c-a3a5-c68b81e8cd40.png)

### Expected outcome

I would expect the colorbar to use as much space for the 0-1 range as it does for the other unit intervals when combining TwoSlopeNorm with spacing='proportional' (third plot in the example). 

### Matplotlib Version

3.6.1

**Comment by davidmnielsen** [comment]
I was pointed to the discussion at #22197

**Comment by jklymak** [comment]
`proportional` is if you have boundaries (eg contours).  You are using `pcolormesh` so there are no natural boundaries.  As pointed out in #22197, you want to set the scale to linear.

**Comment by davidmnielsen** [comment]
Indeed `proportional` works with `contourf`, but then the `vmax` value seems to be ignored.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from matplotlib import cm

delta = 0.01
x = np.arange(0, 2.001, delta)
y = np.arange(0.0, 2.001, delta)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

fig = plt.figure(figsize=(6,3))
ax = fig.add_subplot(121)
m1 = plt.contourf(Z, cmap=cm.seismic, norm=colors.TwoSlopeNorm(vmin=0, vmax=3, vcenter=1))
plt.colorbar(m1, extend='max', spacing='proportional')

ax = fig.add_subplot(122)
m2 = plt.contourf(Z, cmap=cm.seismic, norm=colors.TwoSlopeNorm(vmin=0, vmax=20, vcenter=1))
plt.colorbar(m2, extend='max', spacing='proportional')

plt.tight_layout()
plt.show()
``` 

![Screenshot 2022-11-29 at 20 44 11](https://user-images.githubusercontent.com/39162069/204632601-237baf95-f09a-461e-8151-919593b6b170.png)

**Comment by jklymak** [comment]
It's not ignored - you have no contours out there.  Vmin and vmax do not determine the contours to use, and the colorbar only shows the contours you have made

**Comment by davidmnielsen** [comment]
Right, sorry. The maximum is set by the data.

**Comment by davidmnielsen** [comment]
Just pasting this here for future reference:

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from matplotlib import cm

delta = 0.01
x = np.arange(0, 4.001, delta)
y = np.arange(0.0, 4.001, delta)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

fig = plt.figure(figsize=(6,3))
ax = fig.add_subplot(121)
m1 = plt.contourf(Z, cmap=cm.seismic, levels=np.arange(0,33,1), norm=colors.TwoSlopeNorm(vmin=0, vmax=32, vcenter=1), extend='max')
plt.colorbar(m1)

ax = fig.add_subplot(122)
m1 = plt.pcolormesh(Z, cmap=cm.seismic, norm=colors.TwoSlopeNorm(vmin=0, vmax=32, vcenter=1))
cb = plt.colorbar(m1, extend='max', spacing='proportional')
cb.ax.set_yscale('linear')

plt.tight_layout()
plt.show()
```
