### ISSUE TITLE
[Bug]: Extension error (sphinx.ext.linkcode) while building docs

### ISSUE THREAD

**Issue by sajjad-ali60** [matplotlib/matplotlib#24574]
### Bug summary

while building documentation the execution throws the below error and exit
```reading sources... [ 47%] api/backend_cairo_api
Extension error (sphinx.ext.linkcode):
Handler <function doctree_read at 0x0000026E71784700> for event 'doctree-read' threw an exception (exception: path is on mount 'C:', start on mount 'E:')
make: *** [Makefile:39: html] Error 2
```
[here](https://gist.github.com/sajjad-ali60/8de8842d19f64c7608a26f333c1d8098) is the log of `make html`

### Code for reproduction

followed the documentation for writing matplotlib docs

### Actual outcome

```
reading sources... [ 47%] api/backend_cairo_api
Extension error (sphinx.ext.linkcode):
Handler <function doctree_read at 0x0000026E71784700> for event 'doctree-read' threw an exception (exception: path is on mount 'C:', start on mount 'E:')
make: *** [Makefile:39: html] Error 2
```

### Expected outcome

it should print successfully build documentation and shows the html files in `build/html` folder

### Additional information

[requirements.txt](https://gist.github.com/sajjad-ali60/ced6a704d0d0cfdf4a8df668121d5e63) file
gcc version : 12.2.0
clang version : 14.0.6
VC++ compiler tools version : 14.34.31933

### Operating system

Windows 10 Pro Version	22H2

### Matplotlib Version

3.7.0.dev817+g9b7c902fd72e

### Matplotlib Backend

agg

### Python version

3.10.8

### Jupyter version

not installed

### Installation

from source (.tar.gz)

**Comment by QuLogic** [comment]
You need to run with `O=-T` to get a full traceback from Sphinx.

**Comment by sajjad-ali60** [comment]
> You need to run with `O=-T` to get a full traceback from Sphinx.

here is the traceback from Sphinx with `make O=-T html`

```Running Sphinx v5.3.0
Building Documentation for Matplotlib: 3.7.0.dev817+g9b7c902fd72e
fatal: not a git repository (or any of the parent directories): .git

Sphinx error:
Builder name O not registered or available through entry point
```

**Comment by tacaswell** [comment]
That is a pretty unique error message, so I think it is coming from https://github.com/python/cpython/blob/0547a981ae413248b21a6bb0cb62dda7d236fe45/Lib/ntpath.py#L780-L782 which is in `relpath`.  Which suggests that two paths sphinx expected to be relative to each other are on diffrenet drives which (I think) is something you can not express on windows?

Without information about how everything is checked out and installed I am not sure if there is anything do to help and suspect it is unlikely that there is anything we can do in Matplotlib (other than document to not do what ever it is that is causing this situation).

**Comment by sajjad-ali60** [comment]
> On windows you gotta do:
> 
> ```shell
>  set O=-T & make html
> ```
> 
> https://matplotlib.org/devdocs/devel/documenting_mpl.html#building-the-docs

ok my bad. i saw the documentation there was written just like that.
now [here](https://gist.github.com/sajjad-ali60/e546c5d8c3ae6d903f994794f1fd4c4b) is the traceback from sphinix with `set O=-T & make html`

**Comment by QuLogic** [comment]
You can work around this by setting `link_github = True` to `False` in `doc/conf.py`.

**Comment by VeckoTheGecko** [comment]
Not 100% the same error message, but I fixed this by fixing correcting my [`linkcode_resolve()` function](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html#confval-linkcode_resolve)
