### ISSUE TITLE
[ENH]: provide public API for styling radio buttons

### ISSUE THREAD

**Issue by drammock** [matplotlib/matplotlib#24583]
### Problem

after #24455, we lost access to RadioButton circles through the public API. I'm requesting that there be a public way to style the individual radio button circles.

*use case:* Over at MNE-Python we use a set of RadioButtons in a signal annotation GUI (so users could select e.g. the "blink" or "motion artifact" button and then click-drag across the plot to add a corresponding annotation to that time span).  We color-code those annotations so we need a way to access the radio button circles individually, to set the color, edge color, and alpha. We also set the size and linewidth to make the buttons easy to click and the colors easier to distinguish. Here's a screenshot:

![Screenshot_2022-12-02_12-09-47](https://user-images.githubusercontent.com/1810515/205358168-9d67d067-d439-4f7e-8920-78406bdc58bc.png)

cc @larsoner 

### Proposed solution

make `self._buttons` public?

**Comment by anntzer** [comment]
Sure, making buttons public seems reasonable as you have a real use case for that.
