### ISSUE TITLE
[Bug]: plt.pause errors with set_wakeup_fd on thread with QtAgg backend

### ISSUE THREAD

**Issue by jamesbraza** [matplotlib/matplotlib#24586]
### Bug summary

When trying to perform `plt.pause(0.1)` on a thread (with thread-safety implemented), I get denied by a `ValueError`:

```python
ValueError: set_wakeup_fd only works in main thread of the main interpreter
```

I do have thread-safety implemented with a `threading.Lock`.  Should this `Exception` happen, given I have thread safety enforced?

### Code for reproduction

```python
from threading import Lock, Thread

import matplotlib
import matplotlib.pyplot as plt

matplotlib.use("QtAgg")

fig, ax = plt.subplots()

# NOTE: matplotlib is not thread safe, so use a Lock
# SEE: https://matplotlib.org/stable/users/faq/howto_faq.html#work-with-threads
plt_lock = Lock()

with plt_lock:
    plt.pause(0.1)


def on_thread() -> None:
    with plt_lock:
        plt.pause(0.1)


thread = Thread(target=on_thread)
thread.start()
thread.join()
```

### Actual outcome

```
/path/to/file.py:20: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.pause(0.1)
Exception in thread Thread-1 (on_thread):
Traceback (most recent call last):
  File "/path/to/.pyenv/versions/3.10.8/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/path/to/.pyenv/versions/3.10.8/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/file.py", line 20, in on_thread
    plt.pause(0.1)
  File "/path/to/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 557, in pause
    canvas.start_event_loop(interval)
  File "/path/to/venv/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 407, in start_event_loop
    with _maybe_allow_interrupt(event_loop):
  File "/path/to/.pyenv/versions/3.10.8/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/path/to/venv/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 233, in _maybe_allow_interrupt
    old_wakeup_fd = signal.set_wakeup_fd(wsock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter
```

### Expected outcome

I am not sure what to expect, other than someone more knowledgeable about `matplotlib` will probably tell me not to do multithreading.

### Additional information

As a substitute to `plt.pause` I am able to attain success on the thread with:

```python
fig.canvas.draw()
fig.canvas.flush_events()
```

### Operating system

macOS Monterey version 12.6

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

3.10.8

### Jupyter version

n/a

### Installation

pip

**Comment by tacaswell** [comment]
`plt.pause` is running the GUI event loop under the hood for you, which typically means it must be run on the main thread.  If you did not hit this issue, you would have hit others.

The thing you would need to guard with a lock is:
 - anything that will update the state of the figure (via adding new artists or mutating existing artists)
 - anything that could run `Figure.draw`

**Comment by jamesbraza** [comment]
Okay I follow what you're saying.  I wanted to bring this to `matplotlib`'s attention in case there was something unexpected taking place.

Seems it's expected, so I will close this out, thank you!
