### ISSUE TITLE
[Doc]: non-members cannot mention or access teams

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#24599]
### Documentation Link

https://matplotlib.org/devdocs/devel/triage.html

### Problem

The triage page encourages anyone to tag `@matplotlib/triageteam` to suggest triage actions for an issue.  It also provides a link to https://github.com/orgs/matplotlib/teams/triageteam, to find members of the triage team.

Similarly, the PR welcome message encourages pinging
https://github.com/matplotlib/matplotlib/blob/7f7dfc9303326c283593270cfcdb1b439781563a/.github/workflows/pr_welcome.yml#L22

I’m fairly sure you need to be an organisation member to either ping a team or view the team pages.

### Suggested improvement

Suggest a different way to get team members’ attention.  Just comment on the issue/PR?  Post on gitter?

**Comment by tacaswell** [comment]
per https://docs.github.com/en/organizations/organizing-members-into-teams/changing-team-visibility

> People who are not members of the organization cannot view any teams.

so we seem out of luck on this.  We should at least remove the incorrect information.

**Comment by tacaswell** [comment]
testing if I can ping @matplotlib/triageteam (sorry, there may be a couple of these).

**Comment by maffettone** [comment]
testing if I can ping @matplotlib/triageteam

**Comment by rcomer** [comment]
I am not in the triage team but I got notification from both as I am subscribed to the issue.  In my emails the team shows as a link for @tacaswell's comment but not for @maffettone's.

**Comment by dmatos2012** [comment]
I can see both the "Testing if I can ping" and yours @tacaswell . Got also email notifications

**Comment by rcomer** [comment]
Also, I think if you are in a team that gets pinged on an issue you are then subscribed to it and will get notifications for subsequent comments.  So a better test may be if @maffettone tries to ping on an issue that someone in triage team is not yet subscribed to.

**Comment by maffettone** [comment]
https://github.com/matplotlib/matplotlib/issues/26046

**Comment by scottshambaugh** [comment]
I got email notifications from Thomas' first ping.
