### ISSUE TITLE
[Bug]: Non-interactive backends miss resize with aspect='equal'

### ISSUE THREAD

**Issue by Descanonge** [matplotlib/matplotlib#24591]
### Bug summary

Hi,
I am used to call `fig.canvas.draw()` before saving to disk to make sure everything is in place. But it is failing when specifying aspect 'equal' on axes.

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.rcdefaults()
plt.switch_backend('tkagg')

fig, axes = plt.subplots(1, 3, figsize=(7, 2), subplot_kw=dict(box_aspect=1))

for ax in axes:
    ax.set_xlabel('X')
    ax.set_title('TITLE')

fig.canvas.draw()
# fig.canvas.draw_idle()
# fig.canvas.flush_events()
fig.savefig('test.png')
```

### Actual outcome

The result from savefig, the xlabels are cropped out:
![test](https://user-images.githubusercontent.com/52320542/205415635-629a49bf-44de-4e8e-af49-6a5189161219.png)

### Expected outcome

A screenshot of the Tk window after the script has run:
![Screenshot from 2022-12-03 02-20-36](https://user-images.githubusercontent.com/52320542/205415624-7febe54d-3614-4ec8-ad6c-e410629788d9.png)

### Additional information

It seems a resize of the axes happens only after the interactive GUI pops up.

To make sure all dimensions are computed/resized `plt.pause(1)` or
```
fig.canvas.draw_idle()
fig.canvas.flush_events()
```
do work but only for interactive backends, and I see no solution when using a non-interactive backend (in batch scripts for instance). Is this expected behaviour ?

NB: I am using IPython with the `%matplotlib tk` magic.

### Operating system

Debian

### Matplotlib Version

3.6.2

### Matplotlib Backend

TkAgg / Agg / Pdf

### Python version

3.10.8

### Jupyter version

IPython 8.6.0 with %matplotlib tk

### Installation

conda

**Comment by QuLogic** [comment]
I see no difference when running as a script from the command line with the TkAgg backend, whether I uncomment the lines or add a `plt.show()` at the end. This is either caused by your window manager resizing the window when it opens, or something in the `%matplotlib` magic from IPython.

**Comment by Descanonge** [comment]
You're right the window manager is the culprit ! I should have thought of that, I use an extension to undecorate windows upon creation. I did not anticipate the windows would be resized to take up the space left by the decorations/borders.
Thanks for trying to reproduce it.
