### ISSUE TITLE
[Bug]: MacOSX backend windows have no accessibility data

### ISSUE THREAD

**Issue by jdtsmith** [matplotlib/matplotlib#24608]
### Bug summary

A very common way of interacting with windows on MacOS is through Apple's [Accessibility Framework](https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/index.html#//apple_ref/doc/uid/TP40001078-CH254-SW1), which is used for all manner of screen manipulations, voice readers, etc.  For example, sight-impaired people can use voice commands to select buttons or have control names read to them, users can use accessibility controls to move and arrange windows, etc. 

I have discovered that the plotting windows produced in the "Python" app of the MacOSX backend are created without any accessibility information whatsoever.  I used the "Accessibility Inspector" to check this.  I've never encountered this before; in fact I didn't think it was possible.  Is it a known issue?

### Code for reproduction

```python
Simply create a MacOSX backend window and attempt to inspect it with "Accessibility Inspector".
```

### Actual outcome

A seemingly normal MacOS window is created, but it has no accessibility controls or data of any kind. 

### Expected outcome

Like all modern MacOS applications, Python windows come with at least basic accessibility controls.

### Operating system

MacOS

### Matplotlib Version

3.5.2

### Matplotlib Backend

MacOSX

### Python version

3.10.8 

### Jupyter version

n/a

### Installation

pip

**Comment by greglucas** [comment]
I don't think this is exclusive to the macosx backend. I can't pick up anything with `tkagg` or `qt5agg` backends either.

**Comment by jdtsmith** [comment]
Thanks.  With `--matplotlib=qt5` I do find accessibility info on the plot window:

![image](https://user-images.githubusercontent.com/93749/205709286-f88b9463-ff51-44c0-8611-5767d3d9ab04.png)

It's much slower than macosx backend though, so it would be great to add accessibility data to that.

**Comment by greglucas** [comment]
@jdtsmith, I've never used the Accessibility Inspector before, is there something I need to do to get it to capture the window properly? It doesn't register anything for me on any of the backends. I have been running with `MPLBACKEND=qt5agg python test.py` (running with `ipython --matplotlib=qt5` and inputting interactively didn't work for me either.

We are including the ApplicationServices header, but maybe there is some more explicit work we need to do in the macosx backend. PRs very welcome on this!
https://github.com/matplotlib/matplotlib/blob/b080109515489cd07a7e21f5999d183485a0f8a3/src/_macosx.m#L3

**Comment by jdtsmith** [comment]
You hit option-space and that activates the cursor to grab any elements (which is highlighted in green).  Clicking on an element then "freezes" it so you can inspect the information.   You'll notice that the macosx backend plot window is invisible to Accessibility Inspector. 

Unfortunately I've never implemented such a thing in Objective C; just a "user" of accessibility data via a tool called Hammerspoon.

**Comment by greglucas** [comment]
> You'll notice that the macosx backend plot window is invisible to Accessibility Inspector.

That is what all of the Matplotlib backends look like to me :( The highlighted green selector gets all of the surrounding windows but doesn't ever see the Matplotlib ones as you mention.

> Unfortunately I've never implemented such a thing in Objective C; just a "user" of accessibility data via a tool called Hammerspoon.

If you are interested in improving Matplotlib's accessibility in other ways or chiming in with advice, we have a few current issues surrounding alt-text and ARIA where your input would be welcome!
https://github.com/matplotlib/matplotlib/pull/21328
https://github.com/matplotlib/matplotlib/issues/24309

**Comment by greglucas** [comment]
I think the root of the problem is which compiled `python` we are using to run our programs. To get accessibility features we need a Framework build of Python.

If I create a new virtual environment from a brew-installed Python 3.11 and use that, I get the accessibility information on all of the buttons and windows.

```bash
python3.11 -m venv .env
source .env/bin/activate
pip3 install matplotlib==3.7.1
python3 test_script.py
```

However, if I use a conda environment's python (which is non-framework), then the window is invisible to the accessibility panel as you described. If you are in conda, you can choose a framework build of Python with "w" `pythonw test_script.py` which then also shows the accessibility information.

Unfortunately, I don't think there is anything we can do on the Matplotlib side for this.

**Comment by jdtsmith** [comment]
Note that QT backends offer accessibility with non-framework python versions.  It's not clear how they manage that yet the MacOSX backend does not.

**Comment by greglucas** [comment]
> Note that QT backends offer accessibility with non-framework python versions. It's not clear how they manage that yet the MacOSX backend does not.

I can't reproduce that with the same pyqt versions as you posted above. I need a framework python version to get QT and Tk windows to show up in the accessibility framework as well. How are you installing python and matplotlib for the different situations?

**Comment by jdtsmith** [comment]
I take that back.  I am indeed using a framework build (brew-installed), yet the MacOS backend does _not_ provide accessibility information, unlike QT.  This is Python 3.11.3, MPL 3.7.1.

**Comment by greglucas** [comment]
Odd, and you are running the same python with each of the backends? Here is a quick screencap with a fresh install of matplotlib==3.7.1 bringing up a simple figure window with the macosx backend and then showing the accessibility options that appear on the right when clicking the pan button.
<img width="1228" alt="image" src="https://github.com/matplotlib/matplotlib/assets/12417828/cca71e15-ad20-4b8a-80f6-8d29c28c4956">

Some other thoughts for differences: M1/arm Mac (I'm on intel), XCode/clang versions.
