### ISSUE TITLE
[Bug]: plt.imsave produces corrupted image

### ISSUE THREAD

**Issue by amorgun** [matplotlib/matplotlib#24610]
### Bug summary

After saving with `plt.imsave` loaded image is different from the original.
`PIL.Image.save` works fine.
Here is a notebook for reproducing this behavior: https://colab.research.google.com/gist/amorgun/5791b37699d1cb2de272320a9ffd1278/matplotlib-imsave-bug-demo.ipynb

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.cbook import get_sample_data
from PIL import Image

test_image_file = get_sample_data("grace_hopper.jpg", asfileobj=False)
input_image = Image.open(test_image_file)
plt.imsave('somefile', input_image, format='jpeg')
loaded = plt.imread('somefile')
plt.imshow(loaded)
plt.show()
```

### Actual outcome

![grace_hopper_bad](https://user-images.githubusercontent.com/10599679/205495217-c4b7eaa0-91fd-4b08-abd2-7ccb5250c1ff.png)

### Expected outcome

![grace_hopper_good](https://user-images.githubusercontent.com/10599679/205495200-9f2386a3-ca63-4a9d-b17d-532f3a267775.png)

### Matplotlib Version

3.6.2

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.8.15 (default, Oct 12 2022, 19:14:39) 

### Jupyter version

5.7.16

### Installation

pip

**Comment by tfpf** [comment]
This isn't a Matplotlib bug.
```
input_image = Image.open('test_image.jpeg')
```
does not load the image in the format Matplotlib expects. Use
```
import numpy as np
input_image = np.array(Image.open('test_image.jpeg'))
```
instead.

**Comment by rcomer** [comment]
Thanks @tfpf, that solves it.  I have also taken the liberty to replace the image used in the OP with a Matplotlib sample file.  I believe the original image used approches the limits of our [code of conduct](https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md).

**Comment by tacaswell** [comment]
Thank you @rcomer.  I agree and have removed the original version from the edit history.

**Comment by amorgun** [comment]
Isn't it somewhat inconsistent that `plt.imshow` works fine with PIL Image but `plt.imsave` does not?

**Comment by tacaswell** [comment]
I suspect that there is an extra "if we do not know what this is cast to numpy array" step in `imshow` but not `imsave`, however I think that is a happy accident in imshow not a deficiency in imsave.

I do not think we would not decline a PR making PIL objects work with imsave, but I also do not think it is a bug we need to track.
