### ISSUE TITLE
[Doc]: above vs below wording in async programming

### ISSUE THREAD

**Issue by jamesbraza** [matplotlib/matplotlib#24632]
### Documentation Link

https://matplotlib.org/stable/users/explain/interactive_guide.html#input-hook-integration

### Problem

There is a sentence:
> If you want the GUI to be responsive during long running code it is necessary to periodically flush the GUI event queue as described [above](https://matplotlib.org/stable/users/explain/interactive_guide.html#spin-event-loop).

However, if you click the link, it takes you further down the page.  Yes this is a docs nit, but for a half second the "above" being incorrect made me question if I'd enough coffee yet.

### Suggested improvement

> If you want the GUI to be responsive during long running code it is necessary to periodically flush the GUI event queue as described in the [explicit event loop control section](https://matplotlib.org/stable/users/explain/interactive_guide.html#spin-event-loop).

I think using words like "above" and "below" are brittle and likely to become stale.

**Comment by Busayo-ojo** [comment]
Hi @tacaswell Can I work on this?
