### ISSUE TITLE
[ENH]: Set color of legend shadow

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#24663]
### Problem

There was a PR to set the shadow color for legend which is now closed: #18668 

### Proposed solution

Revive that PR. The fair thing to do is to add a Co-authored-by with the original author even if it looks like you will have to copy-and-paste the code. (If you rewrite it independently, there is of course no need to do that.) 

Note that there are still some review comments left to handle.

**Comment by tuncbkose** [comment]
I was thinking of reviving the linked PR, but I saw something that confused me a bit. 
In a code like `ax.legend(shadow="y")` should `"y"` be interpreted as `"yellow"` or `True` (as in yes)?

More generally, in [test_rcparams.py](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/tests/test_rcparams.py), there are some expressions (under `validate_bool`) that presumably should be accepted as booleans:
```
('t', 'y', 'yes', 'on', 'true', '1', 1, True)
('f', 'n', 'no', 'off', 'false', '0', 0, False)
```
Is there a principled way to check if a `shadow` argument is one of these beyond just copy-pasting the tuple? Or is something like
```
if is_color_like(shadow):
    ...
elif shadow in ('t', 'y', 'yes', 'on', 'true', '1', 1, True):
    ...
elif shadow in ('f', 'n', 'no', 'off', 'false', '0', 0, False):
    pass
else:
    raise ValueError('shadow must be a valid color or bool')
```
good enough?

**Comment by anntzer** [comment]
I think deprecating the interpretation of t/f/y/n as bools in rcparams would be reasonable too.

**Comment by Shikharishere** [comment]
is this issue still open? If yes I would like take it.......

**Comment by tuncbkose** [comment]
There is already some work done and discussion in the linked pull request. I was hoping to finish it next week but feel free to help if you'd like.
