### ISSUE TITLE
[Doc]: quiver_doc etc leads to documentation of the documentation string

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#24676]
### Documentation Link

https://matplotlib.org/3.6.2/api/_as_gen/matplotlib.quiver.Quiver.html#matplotlib.quiver.Quiver.quiver_doc

### Problem

I guess we do not really want this. Is it for some backward compatibility, some issue if not there, a side effect of some other change, or just a mistake?

### Suggested improvement

Option 1: Do not define `quiver_doc`, but rely on `_quiver_doc` (same goes for barbs_doc https://matplotlib.org/3.6.2/api/_as_gen/matplotlib.quiver.Barbs.html#matplotlib.quiver.Barbs.barbs_doc ).

Option 2: update the rst to skip these.

**Comment by rcomer** [comment]
Yikes!

**Comment by QuLogic** [comment]
I don't think there's much argument for these being public; they likely should be deprecated and removed.
