### ISSUE TITLE
[Bug]: Not possible to set window size or position

### ISSUE THREAD

**Issue by Prsodk** [matplotlib/matplotlib#24682]
### Bug summary

The set position part of fig.canvas.manager.window.setGeometry(x, y, width, height) does not work in pyqt backend.
Likewise the fig.canvas.manager.window.move(x, y) does not work.

### Code for reproduction

```python
import matplotlib
matplotlib.use('qtagg')     # using PyQt6 6.4.0 as well as PyQt5
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
fig.canvas.manager.window.setGeometry(0,0,500,300)
# does not work in Python 2.11 and matplotlib 3.6.2
# plot size is set ok, but position is ignored

ax.plot([1, 2], [1, 2])
fig.canvas.manager.window.move(0,0)
# also does not work

plt.show()
```

### Actual outcome

/home/preben/Pictures/Screenshots/Screenshot from 2022-12-09 22-33-19.png

### Expected outcome

/home/preben/Pictures/Screenshots/Screenshot from 2022-12-09 22-53-05.png

### Additional information

whatever position parameters, figure is plotted in the same place

### Operating system

Fedora 37

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg    PyQt6-6.4.0 and also PyQt5-5.15.7

### Python version

3.11.0

### Installation

pip

**Comment by Prsodk** [comment]
Sorry,  don't know where to upload images.

**Comment by tacaswell** [comment]
- Did this used to work?
- Does it work if you run this after the windows are shown?

**Comment by Prsodk** [comment]
It workes in previous installation Python 3.9 on Fedora 33 .  Unknown backend (but setGeometry compatible)

**Comment by Prsodk** [comment]
I am using plt.show(). So it's blocking further attempt

**Comment by Prsodk** [comment]
Oops. I said Python 2,11 above. I meant Python 3.11

**Comment by tacaswell** [comment]
This works for me:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

plt.pause(.1)  # <- spins the GUI event loop, makes sure qapp exists and has said hello.

fig.canvas.manager.window.setGeometry(0,0,500,700)
# plot size is set ok, but position is ignored

ax.plot([1, 2], [1, 2])
fig.canvas.manager.window.move(0,0)
# also does not work

plt.show()

```

which makes me think that there is some race condition with exactly how the GUI starts up.

I am suspicious of two things:

 - the work done to make selecting and importing the modules for the backend lazier (which has had a few really weird edge cases) but if that is the case it is unlikely we are going to back out those changes (because it means we do not flash through using the Qt backend if you really want gtk 😱 ).
 - a change in the underlying Qt / pyqt version

**Comment by QuLogic** [comment]
If you're on Wayland, then clients are not allowed to force a window position. It is up to the window manager whether it allows it or not, and I don't think Gnome does. It may continue to work with X11 for the time being.

**Comment by Prsodk** [comment]
The problem was the nouveau driver. Installed Nvidia driver, and it worked again.

**Comment by QuLogic** [comment]
It is more likely that the nVidia driver does not support Wayland, and you are now on X11.
