### ISSUE TITLE
Update Research Notice on README.md 

### ISSUE THREAD

**Issue by smarklow** [matplotlib/matplotlib#24717]
Update the Research Notice to change from present to past tense;

Before

***
Please note that this repository is participating in a study into sustainability of open source projects. Data will be gathered about this repository for approximately the next 12 months, starting from June 2021.

Data collected will include number of contributors, number of PRs, time taken to close/merge these PRs, and issues closed.

For more information, please visit [the informational page](https://sustainable-open-science-and-software.github.io/) or download the [participant information sheet](https://sustainable-open-science-and-software.github.io/assets/PIS_sustainable_software.pdf).
***
Proposed changes after
***
Please note for those that participated in the study into the sustainability in open source projects, data was gathered about this repository, starting from June 2021, with final surveys being complete in June 2022.

Data collected included number of contributors, number of PRs, time taken to close/merge these PRs, and issues closed.

For more information, please visit [the informational page](https://sustainable-open-science-and-software.github.io/) or download the [participant information sheet](https://sustainable-open-science-and-software.github.io/assets/PIS_sustainable_software.pdf).
***

**Comment by smarklow** [comment]
Opened this before completing the issue

**Comment by smarklow** [comment]
Another alternative to this could explain the current state of this research as of November 2022, which states the study is in the data analysis stage.

**Comment by timhoffm** [comment]
I think we can remove that section because data acquisition is finished and any current activity in the repo will not go into the study.

**Comment by tacaswell** [comment]
Either way, I would like to get feedback from @yochannah on this.

**Comment by yochannah** [comment]
Thanks - you're right, please do remove it all! Any data collected will only be over the period when the statement was up, and we're not gathering new data.
