### ISSUE TITLE
[Bug]: Using plot in pycharm reports an error ‘Process finished with exit code -1066598274 (0xC06D007E)’.

### ISSUE THREAD

**Issue by Iron-Man666** [matplotlib/matplotlib#24726]
### Bug summary

Cannot generate graphs using matplotlib.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)
plt.show()
```

### Actual outcome

D:\program\anaconda\python.exe D:/program/PyCharm2020.1.3/work/DataProcess.py

Process finished with exit code -1066598274 (0xC06D007E)

### Expected outcome

This should have graphics generated.

### Operating system

windows11 21H2

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.8.10

### Installation

conda

**Comment by timhoffm** [comment]
Does this also happen without PyCharm? If not, I suspect that the problem lies within PyCharm, which brings its own rendering backend for matplotlib. Also, please try to update PyCharm and Matplotlib to the newest versions.

**Comment by tacaswell** [comment]
I would also try making a fresh conda environment.

**Comment by oscargus** [comment]
(Fat fingers and laggy phone...)

**Comment by jklymak** [comment]
Closing for lack of response, but feel free to request a re-open
