### ISSUE TITLE
[Doc]: tables in "notes" cut off content

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#24741]
### Documentation Link

https://matplotlib.org/stable/users/explain/event_handling.html#event-connections

### Problem

The table describing what key presses and modifiers are doing is put into a `.. note:` context and therefore it is completely cut off on the right hand side (there is another column missing). There are some differences depending on screen width with how much of the table is shown.

### Suggested improvement

There are at least a few options:
1) Add css or some other way to handle a horizontal scrollable table.
2) Remove the `.. note:` and switch to a sub-section header? Note that even with this, the scroll wheel is all the way at the bottom of the page and confusing that it is scrollable. (Is there a way to make only a section have a horizontal scroll bar?)
3) Split the table up into multiple tables.

**Comment by oscargus** [comment]
I get between five and seven columns visible depending on zoom level...

**Comment by tacaswell** [comment]
That is important enough I think we should remove the `.. note` in this case.

**Comment by QuLogic** [comment]
> Add css or some other way to handle a horizontal scrollable table.

This should be pretty straightforward to do; is it fine to add everywhere? (I'd guess so if we want to avoid similar things happening elsewhere, but I don't know how to find them.)

**Comment by QuLogic** [comment]
We could also change this table in tabs: https://sphinx-design.readthedocs.io/en/pydata-theme/tabs.html though note that does mean we have to copy the `Key(s) pressed` column for every one.

**Comment by QuLogic** [comment]
I went through all the tables I could find that were indented and could not find any more that were cut off (and no others were in notes, IIRC).
