### ISSUE TITLE
[Doc]: Left Ventricle Bullseye example unexpected output regression

### ISSUE THREAD

**Issue by rraihansaputra** [matplotlib/matplotlib#24771]
### Documentation Link

https://matplotlib.org/stable/gallery/specialty_plots/leftventricle_bulleye.html

### Problem

https://github.com/matplotlib/matplotlib/blob/ecf6e26f0b0241bdc80466e13ee0c13a0c12f412/examples/specialty_plots/leftventricle_bulleye.py

The Left Ventricle bullseye example has an unexpected output in which the area shaded is not aligned with the border. This is not the case in the 3.1.1 docs.

![image](https://user-images.githubusercontent.com/8604926/208382965-e4baf50a-74b3-4aae-b388-88b3b83de5fe.png)
Current Doc output.

![image](https://user-images.githubusercontent.com/8604926/208383029-99f1ac46-75fc-4cf3-bb59-1fe2dbd258be.png)
3.1.1 doc output. https://matplotlib.org/3.1.1/gallery/specialty_plots/leftventricle_bulleye.html

### Suggested improvement

I managed to "fix" the sample code for my use but I feel there is a bug related to the functions used in the example. I'm not too familiar with the APIs and the data projection to polar coordinates so I feel it's better for someone more familiar to explain what happened here.

Might be related to this issue too: https://github.com/matplotlib/matplotlib/issues/16029

**Comment by oscargus** [comment]
This seems to have changed between 3.2 and 3.3.

My guess is `shading='auto'` was introduced there, which most likely selects `nearest` based on the outcome of the figures. It should use `flat`, but just changing to `flat` leads to:

```
TypeError: Dimensions of C (128, 2) are incompatible with X (2) and/or Y (128); see help(pcolormesh)
```
