### ISSUE TITLE
[Bug]: Tkinter Backen Mainloop Exception

### ISSUE THREAD

**Issue by Patrick-marki** [matplotlib/matplotlib#24787]
### Bug summary

After updating Matplotlib from 3.5.3 to >=3.6 we are facing isses with the tkinter backend.

The error we are getting shown below. 
![image](https://user-images.githubusercontent.com/18247357/208642087-e946aebc-26bb-4114-b523-0b0b823c7055.png)

### Code for reproduction

```python
not available
```

### Actual outcome

The exception from tkinter will kill our main thread

### Expected outcome

Plotting is possible.

### Matplotlib Version

3.6

### Installation

pip

**Comment by tacaswell** [comment]
Can you produce a minimal reproduction case for this?  It is very hard to debug this without any information about how you are using Matplotlib.

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open.
