### ISSUE TITLE
[ENH]: Logarithmic scale does not support minus

### ISSUE THREAD

**Issue by tambetvali** [matplotlib/matplotlib#24798]
### Problem

I did set it to logarithmic scale, but I had to put only positive values there - I used plus values also for spendings, not only the incomes. Still, I can see logarithmic scale can go well downwards if you use -log(-value) for minus, where you use log(value) for plus.

### Proposed solution

Hello!

Logarithmic scale simply cuts off minus values. It would be better if it does -log(-value), going to minus with the same function as it goes to plus - I use it to see bars, which have very small numbers together with very big numbers, and minus numbers do as well. If you go down with the same function as you go up, it is better - current version simply cuts them off and does not provide anything for minus values.

**Comment by oscargus** [comment]
Won't you get the same result for 0.001 and -1000 using that approach? The problem is that log for negative numbers is either undefined or complex-valued (depending on if you allow that), so there isn't really a valid way to do this that will not upset lots of users.

**Comment by tambetvali** [comment]
If this upsets users, maybe there could be another name for this scale. Theoretically, just go down the same speed as you go up is what I mean - -((--10)^10) for negative value of 10. So it will speed up downwards the same way as it speeds up upwards.

In my case, I had some sales numbers, where some were very small and some very big - with linear scale, small numbers became invisible. I used log to make them visible besides the big numbers. I need negative values to make the same effect apply for negative numbers.

https://www.omnicalculator.com/math/negative-log is about the correct math of the logarithms. It says "The logarithm of a negative real number is not defined." But which is defined, is that we can use log scales to put very small numbers besides with very big numbers, so that they appear on the same axes - like having comparison of electron, bacteria, planet earth and a star, we will see nothing in linear scale, but by applying log twice, we get them almost the same size, even confusingly. If we want negative scales side-by-side, to compare hole in a paper with paper itself, or to compare outcomes and incomes as in my case, then trivially we should go down from zero with the same acceleration as up. Acceleration is maybe a keyword here. https://socratic.org/questions/what-is-the-logarithm-of-a-negative-number

Maybe not to name this thing a "log", but with some specific name ..about this 0.001 and -1000 question, I could define logarithms as something I see on a screen - it's an accelerating value and it makes big and small numbers comparable by size. Is there a mathematical function, which accelerates and makes small and big positive and negative numbers comparable by size? I think searching or defining such function, which will definitely look logarithm-like, would not by itself break maths and upset users, so maybe that's the goal I should have meant :)

**Comment by greglucas** [comment]
We have two scales now that will behave like you want I think, `asinh` and `symlog` https://matplotlib.org/stable/gallery/scales/asinh_demo.html. We won't change the behavior of log or any other mathematical function, instead you should transform your data before plotting with Matplotlib if you want an alternative behavior.

**Comment by tambetvali** [comment]
Thanks this is what I meant!
