### ISSUE TITLE
[ENH]: 

### ISSUE THREAD

**Issue by MR-T77** [matplotlib/matplotlib#24793]
### Problem

Is there any smart way (ie, not completely manual) to plot time-indexed data on top of a musical stave?
If I have a isometric stave, that stave has a implied time scale:
[![enter image description here][1]][1] 

I want to plot some time-indexed analysis, let's say the waveform and spectrogram in reference to this implied timescale. 
[![enter image description here][2]][2]

I tried with matplotlib.imshow but there's lack of real control on the scale and display of the background, and is not easy to use that background as a scale.
The best I got to was by a lot of manual editing, but I'd like something automated for large-scale analysis.
Does anyone know of any solution to this?
[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/Suctq.png
  [2]: https://i.stack.imgur.com/8Mawy.png
  [3]: https://i.stack.imgur.com/htsPS.png

**Comment by jklymak** [comment]
Yes - use pcolormesh and specify x so that it lines up with the axes above.  

I'll close this as user help us better dealt with at discourse.MatPlotLib.org

**Comment by MR-T77** [comment]
> Yes - use pcolormesh and specify x so that it lines up with the axes above.
> 
> I'll close this as user help us better dealt with at discourse.MatPlotLib.org

Would you care to detail a little bit more? I'm unable to use pcolormesh to show a background image.

**Comment by MR-T77** [comment]
> Yes - use pcolormesh and specify x so that it lines up with the axes above.

I already did (but I'm not getting any feedback).
