### ISSUE TITLE
Consider increasing figure.titlesize for seaborn-talk

### ISSUE THREAD

**Issue by paulcaprioli** [matplotlib/matplotlib#24813]
The styles seaborn-paper, seaborn-talk, and seaborn-poster all set `figure.titlesize` to `large`, i.e. `12.0`.   This looks good for the paper style, but I suggest it should be scaled accordingly for the other two styles.  Otherwise, the title set by `fig.suptitle()` is too small relative to the xlabel, etc.

I am using the following:
```
mpl.rcParams['figure.titlesize'] = 1.25 * mpl.rcParams['axes.titlesize']
```

**Comment by tacaswell** [comment]
Unfortunately we consider the visual appearance to be part of our API and hence changing the the styles is an API change so it is very unlikely that we will make this change (and we are renaming these styles in mpl3.6 https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed).

`mpl.style.use` can take a list of inputs https://matplotlib.org/stable/api/style_api.html#matplotlib.style.use so you should be able to do something like

```python
mpl.style.use(['seaborn-v0_8-talk', {'figure.titlesize': 15}])
```

to easily override any settings you want to adjust.
