### ISSUE TITLE
[Bug]: findSystemFonts should not look in subdirectories of C:\Users\Admin\AppData\Local\Microsoft\Windows\Fonts

### ISSUE THREAD

**Issue by moi15moi** [matplotlib/matplotlib#24836]
### Bug summary

findSystemFonts takes the font in the directory: ``C:\Users\USER_NAME\AppData\Local\Microsoft\Windows\Fonts\Deleted``

It should not take them. They are supposedly deleted. It is better to ignore them.

It is basically the same issue as #22859, but with another directory.
The PR #24655 should probably correct this problem.

### Code for reproduction

```python
from matplotlib import font_manager
font_manager.findSystemFonts()
```

### Actual outcome

font_manager.findSystemFonts retrieve fonts from the folder: ``C:\Users\USER_NAME\AppData\Local\Microsoft\Windows\Fonts\Deleted``

### Expected outcome

font_manager.findSystemFonts should not retrieve fonts from the folder: ``C:\Users\USER_NAME\AppData\Local\Microsoft\Windows\Fonts\Deleted``

### Operating system

Windows 10

### Matplotlib Version

3.6.2

### Installation

pip

**Comment by QuLogic** [comment]
This appears to have been fixed by #24655.
