### ISSUE TITLE
[MNT]: how to use jacksboro_fault_dem.npz

### ISSUE THREAD

**Issue by MrmaderatorYT** [matplotlib/matplotlib#24833]
### Summary

Hi, i want to create own matrix and in docs i saw this file: jacksboro_fault_dem.npz i opened it like arhive and in wrote python code and i saw that file elevation.npy is matrix and i saw that dx,dy is cordinates. But I didn`t understood how i can use it and why this files in npz file

**Comment by jklymak** [comment]
Please discuss at https://discourse.matplotlib.org.  Thanks.
