### ISSUE TITLE
animation with 'ffmpeg' backend incompative with 'bounding_box=tight'

### ISSUE THREAD

**Issue by vlsd** [matplotlib/matplotlib#2483]
I am using ffmpeg 2.0.1 and python2.7. When I save an animation using the (default) ffmpeg backend I do not get an error but the video comes out all garbled. 

This is due to setting the `bounding_box=tight` option in matplotlibrc (see comments below).

Running the script with --verbose-debug I do get an ffmpeg error:

```
Invalid buffer size, packet size 2440992 < expected frame_size 3780000944.4kbits/s
Error while decoding stream #0:0: Invalid argument
```

The full log is here https://gist.github.com/6787110

At the very least we should document this issue, and maybe throw a warning/exception to save people time when they run into this. Pull request #2493 includes a version of this.

**Comment by chipmuenk** [comment]
Using the latest ffmpeg and matplotlib 1.5.0rc3 under Windows 7, the problem still persists. Has it been fixed somewhere?

As this was my first attempt with animations, it cost me a few hours until I finally stumbled across this thread ...
