### ISSUE TITLE
[Doc]: Add alt-text to images in 3.6 release notes

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#24844]
### Documentation Link

https://matplotlib.org/devdocs/users/prev_whats_new/whats_new_3.6.0.html

### Suggested Improvement

We should try using the `:alt:` option of the [`..plot` directive](https://matplotlib.org/devdocs/api/sphinxext_plot_directive_api.html#module-matplotlib.sphinxext.plot_directive), eg:

```rst
.. plot: 
   :alt: 4 identical 2 by 2 heatmaps, each cell a different color: purple, blue, yellow, green going clockwise from upper left corner
the 4 heatmaps are laid out in a 2 by 2 grid with minimum white space between the heatmaps
 
    fig, axs = plt.subplots(2, 2, figsize=(5, 3),
                            sharex=True, sharey=True, layout='compressed')
    for ax in axs.flat:
        ax.imshow([[0, 1], [2, 3]])
    fig.suptitle("fixed-aspect plots, layout='compressed'")

```

I think it's a good first issue because it's editing one file https://github.com/matplotlib/matplotlib/blob/main/doc/users/prev_whats_new/whats_new_3.6.0.rst and I wrote alt text for some of the images at https://twitter.com/matplotlib/status/1588567713034534913 so there are examples (it can totally be improved though). 
There's also some guidance at [How to write alt-text for scientific communication and diagrams](https://heyzine.com/flip-book/f3c7f85cdc.html) and we have a gitter channel for discussing all things accessibility at [gitter.im/matplotlib/accessibility](https://gitter.im/matplotlib/accessibility)

**Comment by hasanrashid** [comment]
I'd like to take this on as a first time contributor

**Comment by hasanrashid** [comment]
https://github.com/matplotlib/matplotlib/pull/24878 is ready for review
