### ISSUE TITLE
[Bug]: controlling text on toolbar in wx

### ISSUE THREAD

**Issue by briantoby** [matplotlib/matplotlib#24867]
### Bug summary

I'm unable to remove the "pan/zoom" and "zoom rect" text from toolbar. Normally coordinates and status messages show up in the toolbar. With the wxpython backend the text shows up under widgets I have added to the toolbar but in windows they show up on top. The coordinates can be suppressed using `<Fig>.format_coord = lambda x,y: ""` but it does not appear there is a way to remove the "pan/zoom" and "zoom rect" text.

### Code for reproduction

```python
n/a
```

### Actual outcome

<img width="434" alt="image" src="https://user-images.githubusercontent.com/9433704/210257573-9d062086-06ff-4f57-a017-5c7f6f6ca59c.png">

### Expected outcome

<img width="433" alt="image" src="https://user-images.githubusercontent.com/9433704/210257530-1899a90e-6619-47e3-8cbf-91ab234718d4.png">

### Additional information

The wx implementation for the toolbar seems a bit problematic. I'd like to just leave space for the text, but have not seen any way to do that with the offered API. 

### Operating system

multiple

### Matplotlib Version

3.6.2

### Matplotlib Backend

wxpython

### Python version

3.10

### Installation

conda

**Comment by anntzer** [comment]
We could consider just getting rid of that text altogether (on all backends); I'm not sure it adds much given that the buttons already have tooltips.
