### ISSUE TITLE
[Bug]: Terminal never ends after closing tkinter window with a matplotlib graph

### ISSUE THREAD

**Issue by acgc99** [matplotlib/matplotlib#24874]
### Bug summary

If you close a `tkinter` window with a `matplotlib` figure using the window exit button, the terminal command never ends.

### Code for reproduction

```python
import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
import sys

root = tk.Tk()

fig = plt.figure()
ax = fig.add_subplot()

canvas = FigureCanvasTkAgg(fig, master=root)
canvas.draw()

toolbar = NavigationToolbar2Tk(canvas, root, pack_toolbar=False)
toolbar.update()

canvas.get_tk_widget().pack()
toolbar.pack()

tk.Button(root, text="Exit", command=lambda:sys.exit()).pack()

root.mainloop()

print("Hello")
```

### Actual outcome

You can see the result in this YouTube video [https://youtu.be/vd64-FwteDM](url)

### Expected outcome

The terminal command should end

### Additional information

It seems that this bug is related to Windows, because in Ubuntu does not happen [https://stackoverflow.com/questions/74976538/python-session-kept-open-after-closing-tkinter-window-with-a-matplotlib-graph?noredirect=1#comment132344227_74976538](url)

PowerShell version

    Name                           Value
    ----                           -----
    PSVersion                      5.1.22621.963
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.22621.963
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1

### Operating system

Windows 11

### Matplotlib Version

3.6.2

### Matplotlib Backend

TkAgg

### Python version

3.11.1

### Installation

pip

**Comment by jklymak** [comment]
Using `plt.figure` seems like a dangerous way to instantiate a `Figure` you are going to add to your own GUI.  You should probably just make a `Figure` instance.  See https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html.

**Comment by acgc99** [comment]
Using `matplotib.figure.Figure` instead of `matplotlib.pyplot.figure` solves the issue. Also the GUI changes its appearance using one thing or another.

**Comment by jklymak** [comment]
I'll close as I don't think there is an action item for us.  Thanks!
