### ISSUE TITLE
[Doc]: tutorials and user-doc organization...

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#24900]
The "tutorials" section of the docs is really mostly _not_ a tutorial, but long-form discussion of library features, and how the library works.  These are done using sphinx-gallery, which is quite convenient for writing docs with lots of plotting examples in them.  

I would argue that much of the material in Tutorials should be considered part of the Users Guide, and organized in the TOC that way.  It's possible some of the "tutorials" could just be made rst files, and edited in rst going froward.  That would ideally require some sort of tool to "run" all the `.. plot::` directives in the rst without compiling the whole doc suite.  Such a tool would be generally useful as well, and shouldn't be that hard to make.  However, even leaving the "tutorials" as sphinx-gallery  python files may be fine if we organize them in the User Guide TOC.

**Comment by rcomer** [comment]
This seems similar to #24746

**Comment by jklymak** [comment]
Ooops, for sure.  I looked for that, but somehow didn't find it??
