### ISSUE TITLE
[MNT]: Further explanation about license using

### ISSUE THREAD

**Issue by Ashley123456789** [matplotlib/matplotlib#24903]
### Summary

When I **import** matplotlib as a third-party dependency, 

- Should I comply with the LICENSE (i.e., Python Software Foundation License, PSFL)? Is the **import** action considered as **to reproduce, prepare derivative works, distribute, and use ...** in the PSFL text?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than PSFL for my projects?

Looking forward to your reply.

**Comment by tacaswell** [comment]
We can not provide legal advice, please consult with your lawyer.
