### ISSUE TITLE
[Bug]: Suptitle not visible with subfigures

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#24910]
### Bug summary

In a fairly basic example using subfigures, a suptitle added to the parent figure is not visible:

### Code for reproduction

```python
f = plt.figure(figsize=(4, 3))
sf1, sf2 = f.subfigures(1, 2)
sf1.subplots()
sf2.subplots()
f.suptitle("It's a bird, it's a plane, it's a suptitle")
```

### Actual outcome

![test](https://user-images.githubusercontent.com/315810/211206529-a3249ee9-6de1-4f0d-8be4-3e46f6f484dc.png)

### Expected outcome

Visible suptitle.

### Additional information

It looks like this is happening because the subfigures have a solid facecolor that obscure the suptitle:

```python
f = plt.figure(figsize=(4, 3))
sf1, sf2 = f.subfigures(1, 2)
sf1.subplots()
sf2.subplots()
sf1.set_facecolor((.8, 0, 0, .3))
f.suptitle("It's a bird, it's a plane, it's a suptitle")
```
![test](https://user-images.githubusercontent.com/315810/211206669-1b39ecf7-ce7c-444b-851f-8e994538cee1.png)

Setting the zorder of the suptitle to a large number has no apparent effect.

### Matplotlib Version

3.6.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

**Comment by jklymak** [comment]
I don't think we specifically set the background color of subfigures to anything different than a figure, which defaults to white.  We could, by default, make subfigures transparent, but not 100% clear to me that is the right thing to do.  

FWIW, this problem goes away with `layout='constrained'` which makes the subfigure the correct size to allow the suptitle.

**Comment by thuiop** [comment]
Ah, so that was what happened. I was really confused by the issue as I could still see that the Text object was correctly in the fig.texts ; I had also tried moving it around in the figure and it did not work, probably because it was still under the subfigures (although in my case I thought that I was using the constrained layout while seaborn actually deactivated it, which added to the confusion).
I do agree that this is definitely an easy trap to fall in for which I would not expect a non-expert user to quickly find the solution (using constrained layout). There is probably a way to make the suptitle show above the subfigures anyway but it does not seem obvious to me ; I agree with the case for having transparent subfigures (but could be missing something as well).

**Comment by anntzer** [comment]
Not that it really matters for the discussion here, but

> I don't think tight_layout accounts for suptitles

has been fixed in https://github.com/matplotlib/matplotlib/pull/17219.

**Comment by jklymak** [comment]
Just to clarify - suptitles now works for simple cases that tight_layout works on.  However it does not work for subfigures or other nested layouts.

**Comment by jklymak** [comment]
> neither layout engine handles similar edge cases like manually added text artists representing captions or panel labels. (Right?)

I'm not sure what you mean by this - certainly if you attach text to an axes, constrained_layout will make all the axes smaller to make sure there is no overlap, just like it does for titles and ticklabels...

For this particular issue, I think someone could easily put in a PR to make the default facecolor for subfigures "none" and see what people think.  I agree it's probably fine for 99.9% of cases, and easy to change to something else if desired.   I'll mark as a good first issue and I don't think its hard, though anyone interested in pursuing should be prepared to advocate for it.

**Comment by mwaskom** [comment]
> I'm not sure what you mean by this

I would typically specify panel labels or a caption by adding text to the figure object, not the axes:

```python
f, axs = plt.subplots(2, 2, constrained_layout=True)
f.text(.99, .01, "Source: I made it up", size=15, va="bottom", ha="right")
```
<img width=500 src="https://user-images.githubusercontent.com/315810/217524409-47a83ef3-bb36-4b4d-9123-1f9278b964c4.png" />

**Comment by jklymak** [comment]
Yes I see. Definitely the layout engines cannot avoid random figure objects, so space would have to be reserved for a "caption" like this.

**Comment by mwaskom** [comment]
Yeah — there's a separate issue about adding a `Figure.caption` concept that layout algorithms could then be smart about (https://github.com/matplotlib/matplotlib/issues/23873) but the point here is that there are other edge cases for this issue that are not solved even by non-default "best practices".

**Comment by robrighter** [comment]
I created a pull request to satisfy the suggested solution above. This makes "none" the default facecolor for subfigures:

https://github.com/matplotlib/matplotlib/pull/25255
