### ISSUE TITLE
[Bug]: Part of graph goes off screen when saved in Jupyter Notebook

### ISSUE THREAD

**Issue by NoaVidovic** [matplotlib/matplotlib#24915]
### Bug summary

When a long graph is saved, part of it goes off screen upon saving it as a file, but it appears normal in the notebook.
I used to use similar code to what is attached below without spawning the bug and it didn't use to cause problems (I am unsure of what version of matplotlib that was using, but this bug is in matplotlib 3.6.2)

### Code for reproduction

```python
//I cannot post the entire code, but the repository is public at https://github.com/NoaVidovic/pgm-symmetry-pg

def plot_pgm(ordering, name, n_plots=3, nums=False):
    fig, ax = plt.subplots(n_plots, figsize=(15*3/n_plots, 10*n_plots))
    l = len(ordering)//n_plots
    y_lim_upper = max([ pgm_symmetry_indices[p] for p in ordering ]) * 1.05
    
    if n_plots == 1:
        ax = [ax]
        
    if len(ordering) % n_plots != 0:
        l += 1

    for i in range(n_plots):
        s, e = i*l, (i+1)*l
        num_name = f' ({(i+1)}/{n_plots})' if n_plots > 1 else ''

        r = len(ordering[s:e])
        bars = ax[i].bar(range(r), [ pgm_symmetry_indices[p] for p in ordering[s:e] ])
        ax[i].set_xticks(range(r), labels=ordering[s:e])
        ax[i].tick_params(axis='both', labelsize=FS_TICK)
        ax[i].set_title(f'Symmetry index of different paragenetic modes{num_name}', fontsize=FS_TITLE)
        ax[i].set_ylim(0, y_lim_upper)

    # [ print(f'{p}:\t {sym:.3f}') for p, sym in pgm_symmetry_indices.items() ]

        if nums:
            for n_minerals, bar in zip([ n_minerals_in_pgm[p] for p in ordering[s:e] ], bars):
                ax[i].text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                           f'{n_minerals}',
                           ha='center', va='bottom', fontsize=FS_SAMPLE
                          )

    plt.savefig(f'results/{name}.png', dpi=300*3/n_plots)

plot_pgm(['Lunar'] + default_ordering, 'graph_pgm_1', n_plots=1, nums=True)
```

### Actual outcome

This is what is seen once the file is saved
![graph_pgm_1](https://user-images.githubusercontent.com/31285853/211366119-78ebda2a-dd11-4c96-9ec6-bed5f5673ede.png)

### Expected outcome

This is what is seen in the notebook
![image](https://user-images.githubusercontent.com/31285853/211366050-3f679ddf-bb35-4eda-a3a6-0d0967ac4741.png)

### Additional information

This only seems to happen with graphs that are very horizontally stretched

### Operating system

Windows

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

3.10.8

### Jupyter version

6.5.2

### Installation

conda

**Comment by jklymak** [comment]
Please post at https://discourse.matplotlib.org with a reproducible example.  However, the inline backend saves with `bbox_inches='tight'` which you are not doing with your `savefig` call, so the outputs will be different.  We can re-open if a bug is determined at discourse.
