### ISSUE TITLE
[ENH]: Include something equivalent to Matlab's tiledlayout and nexttile

### ISSUE THREAD

**Issue by benoitespinola** [matplotlib/matplotlib#24953]
### Problem

Plotting data in subplots can sometimes be a pain. For instance, if you want to create one plot for each day of the year.
```
import numpy as np
import matplotlib.pyplot as plt

def days_in_year(year):
    return (np.datetime64(f'{(year+1)}-01-01')-np.datetime64(f'{(year)}-01-01')).astype(int)

print(days_in_year(2013)) # 365 days
print(days_in_year(2012)) # 366 days
print(days_in_year(2014)) # 365 days

# 21*18 >= 366
n_cols = 18
n_rows = 21

fig, axs = plt.subplots(n_cols, n_rows,  sharex = True,  sharey = True)

for d in range(days_in_year(2013)):
    x = np.random.rand(20)
    y = np.random.rand(20)
    
    # calculate the plot location
    col = d % n_cols # prone to error
    row = int(d/n_cols) # prone to error

    # plot
    axs[col,row].scatter(x,y) # again, prone to error row,col vs col,row

plt.show()
```
Note that the number of days can change according to the year, it is not easy to find a good grid that fits all the data. You also need to hide the tiles that remain unused. Additionally, if you have too many rows, this method will not display the tick labels for the bottom-most plots (because they are not the last row). Finally, there are many points where errors can be made, potentially leading to unexpected results.

### Proposed solution

It would be far more convenient to have an easy way to sequentially plot.
One could start a subplot object that contains zero plots.
Then you add plots in a sequential manner. You get a row vector with plots and a linear index (for instance, 0 to len - 1).
Once you are done making the plots, you can call a function that will produce the layout. You may pass the number of columns and rows for this layout and how to fill (by column or row). You then can show or save the figure.

Example code:

```
import numpy as np
import matplotlib.pyplot as plt

def days_in_year(year):
    return (np.datetime64(f'{(year+1)}-01-01')-np.datetime64(f'{(year)}-01-01')).astype(int)

print(days_in_year(2013)) # 365 days
print(days_in_year(2012)) # 366 days
print(days_in_year(2014)) # 365 days

tile = plt.tiled(sharex = True,  sharey = True)

for d in range(days_in_year(2013)):
    x = np.random.rand(20)
    y = np.random.rand(20)
    
    tile.nexttile()

    # plots in the current tile
    tile.scatter(x,y)

tile.tile[2].plot([0, 0], [0, 1]) # add a plot to an existing tile

tile.layout(height = 21, width= 18, fill_by = 'row') 
plt.show()
```
Providing a too little width x height after creating the tiles throws an error.
The layout can be built in advance too, in this case there is only width x height tiles available.
If there are new tiles, the layout adds a row or column according to the fill_by argument.

By default fill_by fills by row:
0 1 2 3
4 5 6 7
...

Alternatively, one can fill by column:
0 4
1 5
2 6
3 7
...

One could give either height or width and the counterpart could be calculated automatically
For instance:
`tile.layout(height = 21, fill_by = 'row')`
Calculates the smallest number for width:
`width = math.ceil(len(tiles)/height)`

There could be a default height and width that could be calculated using sqrt of the length of tiles
```
width = math.ceil(sqrt(len(tiles)))
height = math.floor(sqrt(len(tiles)))
``` 

Only the last width tiles would have the x-axis displayed, the other tiles have it hidden by default
The missing tiles in the width x height layout are by default hidden.

**Comment by anntzer** [comment]
Note that in your initial example you can replace `axs[col,row]` by `axs.ravel()[d]` (flat index), but I agree that the kind of functionality proposed here can be nice sometimes.  IIRC @tacaswell wrote an example implementation on gitter some time ago?  I think it's mostly a matter of dynamically creating the right gridspec/subplotspecs and calling set_subplotspec on all relevant axes.

**Comment by benoitespinola** [comment]
The issue with axs.ravel()[d] is that it only gives the option to fill the axes by column (if I do not mistake):
0 1 2
3 4 5
...

It does **not** give you the option to fill by column:
0 3...
1 4...
2 5...

This addition would make Matplotlib easier to manipulate for users with little coding experience.

**Comment by anntzer** [comment]
That would just be `axs.T.ravel()[d]`.

**Comment by benoitespinola** [comment]
The other thing that this approach (nexttile) would give, is to make it possible for the last n_col plots to have the labels in the x-axis back on (currently, in subplots, this is a pain to implement... I have been trying with no success so far).

In other words, if your grid is 3 columns and 2 rows, and you plot by row you get something like:
no_x_label, no_x_label, x_label
x_label, x_label, no_plot

**Comment by QuLogic** [comment]
You may be interested in [grid-strategy](https://github.com/matplotlib/grid-strategy).

**Comment by anntzer** [comment]
> make it possible for the last n_col plots to have the labels in the x-axis back on

Right now deciding whether to put in the ticks or not is controlled by `ax.label_outer()`; we could certainly add an option to `label_outer` to make it restore xticks for any axes that doesn't have an axes below it, even if not on the last row.

**Comment by benoitespinola** [comment]
One issue/user challenge with ax.label_outer() is that it will only display the axes for the outermost plots in the grid. If the grid is not complete, it will not display the axes for the last plot in a row (or column). A way around this could be that each placeholder has a boolean flag is_empty, which is True when creating the subplots object. if there is a plotting command for that placeholder, that boolean goes to False. One could then think that for each row, if a placeholder plot has empty or hidden plots until the outer-most placeholder in the rows direction, then the axis is drawn, The same applies for the columns. Note that I suggest this behavior also for hidden plots. There could be a variable to select the behavior (3 options) such as it will draw the axes on the outermost 'visible' (default), 'hidden' (that would not draw the axes for a visible plot that has a hidden plot after it in the direction of the rows/columns). This is why I am suggesting the n last plots to have the axes drawn (including the labels), where n = n_rows (or n_cols if the plots are filled by column). This boolean flag stating if the plot has been drawn or not can also be used when calling nexttile, it would just go to the first available plot when one does axes.ravel().

**Comment by tacaswell** [comment]
https://tacaswell.github.io/dynamic-axes-count.html is a write up of a "Axes factory generator".

If you make a dense grid you can make the Axes you do not want not visible and then do a pass over them to "turn off the xticks on all but the bottom" (https://github.com/bluesky/bluesky/blob/d2b6bddd4415cdb2946fe8d552bd704bc9932c11/bluesky/callbacks/best_effort.py#L231-L235 is an example from some of my BNL work), but I agree with @anntzer that extending `label_outer` to do this natively is reasonable.

**Comment by jklymak** [comment]
This seems like something some people may want, but adding tick labels to the last visible row is kind of ugly if they are staggered, particularly if you are using constrained layout to minimize white space.  Note that if you do this with tight layout you will get a whole lot of white space on every axes.  Personally, I'd just leave the labels empty and assume readers can key off the labeled axes on the bottom row.

**Comment by tacaswell** [comment]
I think the long comment at https://github.com/matplotlib/matplotlib/issues/26097#issuecomment-1584882257 also applies here and I am going to also close this PR with no action.

The TL;DR is that while this is a useful capability, we think it is best started as a third-party library to be able to quickly sort through the API space.

This issue brings up one more API choice : how do you structure access to already created Axes?
