### ISSUE TITLE
[Bug]: for non-rectilinear axes, axvline/axhline should behave as "draw a gridline at that x/y"

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#24996]
### Bug summary

Currently, on polar axes, axvline correctly draws a radial line at a given angle, but axhline draws nothing.  It would be nice if axhline provided an easy way to draw a circle at a given radius (= a line at constant r), something for which I don't think there's an easy API right now.
More generally, for arbitrary axes, it seems that axvline and axhline have "clear" generalizations as "draw a gridline at a given x or y value".
(And likewise for axvspan/axhspan.)

### Code for reproduction

```python
from pylab import *
polar(); axvline(-np.radians(22.5), color="C0"); axhline(.5, color="C1")
```

### Actual outcome

![test](https://user-images.githubusercontent.com/1322974/212559659-c9c5479e-2693-4a66-9df9-c155e12112b2.png)

### Expected outcome

For polar axes, the solution is to explicitly set _interpolation_steps, i.e.
`axhline(.5, color="C1").get_path()._interpolation_steps = 180`.  (Otherwise, what happens is that both ends of the axhline (at theta=0 and theta=2pi) end up being transformed to the same point and a degenerate, null line is drawn.)
![test](https://user-images.githubusercontent.com/1322974/212559679-29845dbb-9aa8-42cd-8155-3ab1953a10d8.png)
Perhaps axvline/axhline should simply do that.

### Additional information

One could ultimately consider drawing gridlines using axhline/axvline, if this is fixed.

### Operating system

fedora

### Matplotlib Version

3.7.0.dev1370+g651a87407a

### Matplotlib Backend

mplcairo

### Python version

3.10

### Jupyter version

ENOSUCHLIB

### Installation

git checkout

**Comment by javivallejo** [comment]
+1 to this issue.
Also, when using polar axes, yticks label cannot be modified with `matplotlib.axes.Axes.tick_params` (for example moving the label to be on top of the line instead of being on the right side).
