### ISSUE TITLE
[Bug]: Error raised when setting the colorbar 'horizontal'

### ISSUE THREAD

**Issue by auroralin0408** [matplotlib/matplotlib#25011]
### Bug summary

It turned out great when using a vertical colorbar, but when I add `orientation='horizontal'`, the output bacame little weird with no right color on it.

### Code for reproduction

```python
cf = ax1.contourf(x,y,z,levels=np.linspace(0,60,51),\
                 extend='max',cmap = cm)
cbticks = np.arange(0,70,10)
cb= fig.colorbar(cf,ax=ax1,pad=0.05,ticks=cbticks,\
                  shrink=0.8,extend='min',orientation='horizontal')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/118411170/212903118-32c855f9-bda1-42e6-800e-e67f044569c2.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/118411170/212903348-de610d0d-b5a4-4c89-b876-9944c6e61a5e.png)
it's supposed to be horizontal version of the colorbar.

### Operating system

Windows

### Matplotlib Version

3.5.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.15

### Jupyter version

6.5.2

### Installation

conda

**Comment by oscargus** [comment]
Can you please provide the traceback of the error?

**Comment by auroralin0408** [comment]
It can run successfully without any traceback, but the weird picture it output may indicate there's something wrong... And I don't know why.

**Comment by auroralin0408** [comment]
I checked my code once again, and found the reason. It was bcs `cb.ax.set_yticks( ); cb.ax.set_ylabel( )` following the `fig.colorbar` where y need to be changed.
Sorry to bother you, and really thanks !!

**Comment by oscargus** [comment]
OK! Good that it was solved! (I interpreted "raised" in the title as an exception.)
