### ISSUE TITLE
[Bug]: disk is under heavy load

### ISSUE THREAD

**Issue by progLks** [matplotlib/matplotlib#25012]
### Bug summary

When a lot of plots is saved sequently, disk is under heavy load (about 20Gb on 40 plots, about 2000 input operation per second)

### Code for reproduction

```python
Sorry, could not create a minimal example that reproduces this. Just wanted to leave a note.
```

### Actual outcome

After calling plt.savefig(path, dpi=300) - file ../matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf is read about thousand of times. plot object has 2 subplots and text(about 10 text units).

### Expected outcome

No disk load.

### Additional information

'Agg' backend is used
plt.close() is called after plt.savefig().
Problem occurs on arch, but not occurs on OS/X.

### Operating system

Arch

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

3.8

### Installation

pip

**Comment by jklymak** [comment]
We can't help or debug the issue if you don't give us a minimal reproducer that we can run.  Please clarify the issue.

**Comment by tacaswell** [comment]
> After calling plt.savefig(path, dpi=300) - file ../matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf is read about thousand of times. plot object has 2 subplots and text(about 10 text units).

Can you please try with 3.6?  This sounds like there is something wrong with our font caching logic and that code was significantly re-worked in 3.6 as part of the fontfallback work.

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open...
