### ISSUE TITLE
[Bug]: Scatter plot squares occasionally become rectangles

### ISSUE THREAD

**Issue by acroner** [matplotlib/matplotlib#25020]
### Bug summary

Scatter plot markers sometimes vary in shape (become rectangles) when using scatter with 'square' marker, (unique) size parameter and 'none' in either facecolor or edgecolor.
Using plot() works as expected.

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.scatter(range(10), range(10), marker = 's', s = 20, facecolors = 'none', edgecolors = 'b')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/16317578/213205932-28f6340b-4ce1-41dd-bfea-6f63beb7711b.png)

### Expected outcome

When using a square marker and unique size, all symbols would be expected to be an identically sized and shaped square (generated with plot() ):
![image](https://user-images.githubusercontent.com/16317578/213212965-81a705ac-2078-4f72-9b6c-c5d8b7a018ff.png)

### Additional information

Happened in both Windows11, Matplotlib 3.5.2, Python 3.9.13, as well in Zorin (Ubuntu), Matplotlib 3.3.4, Python 3.8.3

### Operating system

Zorin (Ubuntu), Windows 11

### Matplotlib Version

3.3.4, 3.5.2

### Matplotlib Backend

module://ipykernel.pylab.backend_inline, module://matplotlib_inline.backend_inline

### Python version

3.8.3, 3.9.13

### Installation

None

**Comment by jklymak** [comment]
This is just pixel-snapping.  You can pass `snap=False` to remove this effect, but you will get aliasing in low-resolution images.  I'm going to close because this is expected behaviour.
