### ISSUE TITLE
[Bug]: `\geqslant`, `\leqslant` and `\eqslantgtr` are not spaced like their non-slanted versions

### ISSUE THREAD

**Issue by tfpf** [matplotlib/matplotlib#25042]
### Bug summary

There should be a space on both sides of these operators.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.text(.3, .2, r'$a\leq2$', size=40)
plt.text(.3, .4, r'$a\leqslant2$', size=40)
plt.text(.3, .6, r'$a\geqslant2$', size=40)
plt.text(.3, .8, r'$a\eqslantgtr2$', size=40)
plt.show()
```

### Actual outcome

![nospace](https://user-images.githubusercontent.com/19171016/213753931-d8967214-f480-4b8c-b24a-e9b84d1a46e4.jpg)

### Expected outcome

Spacing should be the same for all of these symbols.

### Operating system

Debian GNU/Linux 11 (bullseye)

### Matplotlib Version

3.5.0.dev7385+ge6bf91dcfd

### Matplotlib Backend

TkAgg

### Python version

Python 3.9.2

### Installation

git checkout

**Comment by anntzer** [comment]
Seems easy enough to add them to `Parser._relation_symbols`, but the bigger question is whether there is a more automated way to get the list of symbols that need spacing around them instead of doing so by hand.

**Comment by oscargus** [comment]
There is a list in `doc/sphinxext/math_symbol_table.py` although that includes both binary operation and relation symbols.

Also, I guess that it is good if the added symbols exists in `_mathtext_data.py` (which these does).
