### ISSUE TITLE
[ENH]: Plotting masked arrays correctly in 3D line plot

### ISSUE THREAD

**Issue by lars-nagel** [matplotlib/matplotlib#25043]
### Problem

It would be great if the masking feature worked in 3D plots:

```
import matplotlib.pyplot as plt
import numpy as np

# Create some data
x = np.linspace(0, 10, 100)
y = np.linspace(0, 10, 100)
z = np.sin(x) * np.cos(y)

# Mask some of the data
mask = z > 0.5
z = np.ma.array(z, mask=mask)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(x, y, z)
fig.show()
```

Currently, all of the data is plotted.

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this

**Comment by rcomer** [comment]
Hi @jalajk24, welcome to Matplotlib!  Anyone is welcome to work on anything but, if you are new, it may be better to look through our [Good First Issues](https://github.com/matplotlib/matplotlib/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+first+issue%22).  Please also have a look at our [Contributing Guide](https://matplotlib.org/stable/devel/contributing.html).
