### ISSUE TITLE
Why doesn't fill_between work?

### ISSUE THREAD

**Issue by LuchoValr** [matplotlib/matplotlib#25059]
### Bug summary

In this Bayesian deep learning code I try to plot the mean and standard deviation in different ways but they don't appear on the plot.

### Code for reproduction

```python
import numpy as np
X = np.random.rand(20,1) * 10 -5
y = np.sin(X)
X.shape,y.shape
((20, 1), (20, 1))

X_test = np.arange(-10,10,0.1)
X_test = np.expand_dims(X_test,-1)
probs = []
for i in range(100):
    out = model.predict(X_test)
    probs.append(out)
p = np.array(probs)
mean = np.mean(p,axis=0)
std = np.std(p,axis=0)
p.shape



import matplotlib.pyplot as plt
plt.figure(figsize=(10,7))
plt.plot(X_test,mean,c='blue')

lower_bound = mean - std * 0.5
upper_bound =  mean + std * 0.5
plt.fill_between(X_test.flatten(),upper_bound.flatten(),lower_bound.flatten(),alpha=0.25, facecolor='blue')

lower_bound = mean - std
upper_bound =  mean + std
plt.fill_between(X_test.flatten(),upper_bound.flatten(),lower_bound.flatten(),alpha=0.25, facecolor='blue')

lower_bound = mean - std * 2
upper_bound =  mean + std * 2
plt.fill_between(X_test.flatten(),upper_bound.flatten(),lower_bound.flatten(),alpha=0.25, facecolor='blue')

plt.scatter(X,y,c='black')
```

### Actual outcome

![graph](https://user-images.githubusercontent.com/101154811/213926071-4d2b3bf7-3886-49e0-acca-5645dac0869f.png)

### Expected outcome

![descarga](https://user-images.githubusercontent.com/101154811/213926114-ca2c0b62-c835-4740-8991-881f57502a01.png)

### Matplotlib Version

3.5.3

### Installation

None

**Comment by dstansby** [comment]
Please could you re-write the example to remove `keras`? That way it's much easier for us to debug and understand what is going on with minimal dependencies.

**Comment by LuchoValr** [comment]
> 



> Please could you re-write the example to remove `keras`? That way it's much easier for us to debug and understand what is going on with minimal dependencies.

Done

**Comment by jklymak** [comment]
You were asked to move this discussion to discourse.  Please do not open repeat issues until a bug has been identified.
