### ISSUE TITLE
[Doc]: How to show an ASCII hyphen in math text without using TeX?

### ISSUE THREAD

**Issue by raymondlanger** [matplotlib/matplotlib#25053]
### Problem

There is no explanation how to show an ASCII hyphen in math text without using TeX. It is unclear how to avoid the conversion of '-' into a minus sign.

### Suggested improvement

The documentation should explain how to show an ASCII hyphen in math text, or warn that this requires using TeX.

**Comment by raymondlanger** [comment]
Inserting the Unicode character `u"\u2010"` worked for me. I've answered my question on [stackoverflow](https://stackoverflow.com/questions/75195123/how-to-write-a-subscripted-hyphen-within-matplotlib-math-text-without-tex/75196595#75196595), but I don't know whether there is a better solution.

**Comment by anntzer** [comment]
I think this would basically be fixed by #22173 which would let you write `\text{-}`, which is also one of the approaches suggested for TeX at https://tex.stackexchange.com/questions/123211/a-short-hyphen-in-a-math-formula.
