### ISSUE TITLE
[Bug]: Issue with the 'bmh' style assuming existing style settings in VSCode dark mode

### ISSUE THREAD

**Issue by mlubej** [matplotlib/matplotlib#25076]
### Bug summary

If someone is using the dark mode in VSCode Notebooks along with the user setting `"jupyter.themeMatplotlibPlots": true`, the default output image looks like this:

![image](https://user-images.githubusercontent.com/37869250/214520647-1288fe5b-3a4d-4157-acac-5dc4222d54fb.png)

This is not the problem, I guess the vscode dark theme does this by default. If I set the `plt.style.use('default')`, then everything works as expected.

![image](https://user-images.githubusercontent.com/37869250/214520822-c68f585d-674a-46be-a425-9f53c9020b11.png)

However, if I use my favorite theme, 'bmh', I get the following:

![image](https://user-images.githubusercontent.com/37869250/214521001-db6a3478-c11d-43c3-ba03-a4718228a0ea.png)

If I want the output I expect, I first have to set the "default" theme, and then the "bmh" theme to get the correct output

e.g.

```python
plt.style.use('default')
plt.style.use('bmh')
```

![image](https://user-images.githubusercontent.com/37869250/214521131-21444eea-7f1f-4dd8-90b2-f5bd958e952f.png)

I'm not sure why VSCode sets all of this to dark more, (I don't want this), but it seems that also the "bmh" isn't "complete" and assumes some defaults from before and doesn't overwrite them.

It might make sense to make the styles more complete.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

# plt.style.use('default')
plt.style.use('bmh')

x = np.linspace(0, 1, 11)
y = 2 * x * 2 + 1

plt.plot(x, y)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/37869250/214522366-42eb8fd4-9602-43a1-9911-e039c897d91a.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/37869250/214522412-109f6dd0-85ad-427c-a4b4-c28410bdbd12.png)

### Additional information

- using VSCode Notebooks on Mac OS Monterey
- VSCode dark mode
- VSCode setting snippet:

```json
"jupyter.themeMatplotlibPlots": true,
```

### Operating system

Mac OS Monterey

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.8.7

### Jupyter version

6.4.6

### Installation

pip

**Comment by QuLogic** [comment]
> ```python
> plt.style.use('default')
> plt.style.use('bmh')
> ```

Note, you can merge these:
```python
plt.style.use(['default', 'bmh'])
```

I'm not sure what `bmh` expects or doesn't.

**Comment by tacaswell** [comment]
I am very hesitant to change anything about the named styles and it was indeed intentional that styles were not required to change every parameter so that it was possible to combine them.

The way that vscode/jupyter is setting the style is via the `rcParams` (as is the `mpl.style` module) so it does make sense that if two things, that do not know about each other, are going to conflict.

Does setting `"jupyter.themeMatplotlibPlots": false,` also fix the problem?

**Comment by mlubej** [comment]
> I am very hesitant to change anything about the named styles and it was indeed intentional that styles were not required to change every parameter so that it was possible to combine them.

OK, if that was not the intention, then I'm completely satisfied with the solution of combining styles.

> Does setting "jupyter.themeMatplotlibPlots": false, also fix the problem?

Hmm.. I remember a different, unacceptable behavior when I set it to `false` in the past, but now I don't seem to be having this behavior.

In this case I am then able to get a proper plot only with the `bmh` style.

However, in this case then it seems that the transparency of the image copied from the notebook gets tampered with. It looks fine in the notebook, but if I paste it here, the axes are transparent:

![image](https://user-images.githubusercontent.com/37869250/214791616-b4785c23-3ac8-420a-9b02-e4925362eb8e.png)

I can solve this by doing `fig.patch.set_alpha(1)` (assuming you have the fig object defined). I wasn't able to fix this problem using the `rcParams`, but only via the `set_alpha` method. Am I missing something? 

I tried doing the following:

```python
plt.rcParams['axes.facecolor'] = 'white'
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['figure.edgecolor'] = 'white'
plt.rcParams['savefig.facecolor'] = 'white'
plt.rcParams['savefig.edgecolor'] = 'white'
```

but nothing helped. I didn't see any relevant transparency setting in the rcParams.

**Comment by tacaswell** [comment]
I suspect that logic lives in a combination of https://github.com/ipython/matplotlib-inline and https://github.com/ipython/ipython/blob/1b5674ca8bbac62daa42eb460848173c0542cf2e/IPython/core/pylabtools.py and the `'savefig.transparent'` rcparams.

We can only generate png (/ svg) of the figure when requested.  If you are not explicitly calling `fig.savefig` (or `print_figure`), something else is calling it for you and then embedding it in the notebook.  Jupyter / vscode (reasonably) changes the defaults and adds some additional logic into that save process.  It may be better to raise these issues with those projects.

**Comment by mlubej** [comment]
Agreed. Closing. Thank you!
