### ISSUE TITLE
Relim not working correctly with images

### ISSUE THREAD

**Issue by giovanni-rosotti** [matplotlib/matplotlib#2508]
It seems that relim is not working correctly with images produced by imshow. A minimum working example follows:

```
import matplotlib.pyplot as plt
import numpy as np
ax=plt.gca()
image = np.ones((100,100))

ax.imshow(image,extent=(-0.5,0.5,-0.5,0.5))
ax.relim()
ax.autoscale()

plt.show()
```

You can see that after the call to autoscale, the limits are incorrectly set to (-0.05,0.05,-0.05,0.05). This was working correctly in 1.2.1, and it has been broken in 1.3.0. I tracked down the problem to a line in relim, namely self.dataLim.set_points(mtransforms.Bbox.null().get_points()). Commenting that line solves the problem. However, as I don't know what that line was supposed to do, I can't just propose to delete it.

**Comment by guzhuo0624** [comment]
I don't know if this is the right way to fix it #4137
