### ISSUE TITLE
Add note in contrib guide admonishing against use of f strings in logs

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#25080]
>Can a note about this be put somewhere on the [contributing code](https://matplotlib.org/devdocs/devel/contributing.html#using-logging-for-debug-messages) page? I worry that this is the type of thing that will get changed in either direction 16 times.

_Originally posted by @story645 in https://github.com/matplotlib/matplotlib/issues/25073#issuecomment-1403711269_

**Comment by neutrinoceros** [comment]
How about using `flake8-logging-format` ?
