### ISSUE TITLE
Add an `.annotate` method to Artist

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#25094]
I use `FancyArrowPatch` a lot to make diagrams and they have a lot of arrows and I'd really like [tikz-like](https://rmwu.github.io/tutorial/latex/2019/11/21/positioning/) positioning of labels along the arrow.  The [arrow demo](https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/arrow_demo.html#arrow-demo) has an example of the sort of manual work that goes into trying to position each label correctly and it'd be nice to move all that positioning logic inside a method on `FancyArrowPatch`. 

![image](https://user-images.githubusercontent.com/1300499/215160433-73dc5919-c4ff-4a10-8528-3d4c9958b522.png)

(Discussion of migrating arrow to vector and therefore FancyArrowPatch so it could take advantage is at #22435)

For this method, we can reuse the 'ha' and 'va' arguments relative to the line, w/ n additional offset argument (here relpos, but possibly something closer to the annotate api offset(xoffset, yoffset))

```python
ar = FancyArrowPatch
ar.set_label(str, offset= ratio on interval of line, pad) #base off tikz api
```
| left | right | center (default)|
| ----| --------| -------|  
| label </br> ----->| -----> </br >label| --label-->|
        
| top | bottom | center (default)|
| ----| --------| -------|  
| label | -----> | --label-->|
| ----->|</br >label| |

| relpos=0| relpos=1|relpos=.5 (default)|
|----------|----------|-------------------|
| label----->| ----->label|---label--->|

maybe  |--a1--[bbox]--a2-->

_Originally posted by @story645 in https://github.com/matplotlib/matplotlib/issues/22223#issuecomment-1011577069_

ETA: Based on the discussion below, where I've landed is that an `.annotate` method on artist would give me the bookkeeping I want - ease of keeping track of which annotation I put on what-and be fairly generalizable. 
            
```python
def annotate(self, label=None, xy=None, xytext=None, **annotation_kwargs):
     matplotlib.text.Annotation(text, xy, xytext, xycoords=self, **kwargs)
```
with annotations I guess added as child artists/sibling artists -> do we have a mechanism for this?

**Comment by jklymak** [comment]
An Annotation class is a FancyArrowPatch and a Text.  This sounds like it could be a compound Artist like that, or even just an Annotation object, perhaps with more Text placement knobs, or a child class.  I don't think FancyArrowPatch on its own should grow a text method, and it almost certainly should not be called `set_label` since for every other Artist `set_label` sets the label to be used for legends.

**Comment by tacaswell** [comment]
The core problem here is that we _need_ all of those knobs.  Reducing the number or changing the parameterization either throws out useful functionality or just masks the problem.  I think we should take inspiration from https://docs.python.org/3/library/itertools.html#itertools-recipes and write up as functions a whole lot of these alternate paramaterization. 

Either they happen to be what users want (and then they can copy-paste and be done), the are close enough that users can tweak them a little bit, or they are extensive enough to provide inspiration for what the users actually need to write for them selves.

**Comment by tacaswell** [comment]
Given that you just wrote the example can you please directly open the PR 😄 .

**Comment by anntzer** [comment]
See also https://github.com/matplotlib/matplotlib/issues/22223#issuecomment-1011957191: I think the idea of having an easy way to specify coordinates in units relative to another artist's bounding box is something worth exploring.

**Comment by timhoffm** [comment]
AFAIK, we don't have Artists that have functions to create and add other Artists to a figure/ axes. I'm hesitant to change this as this adds complexity to the Artist (for example the function would have to determine whether the parent artist is in an Axes or figure and behave accordingly)  Also, `artist.annotate()` conveys the impression to me that the annotation is attached to the artist, which e.g. would imply that the annotation would move with the artist. However, I don't think we can do this (or implement this without strong user demand).
IMHO the current API is good enough. It should only be documented better, which is done in #25100.

**Comment by jklymak** [comment]
> I think draggable annotations would be really really cool,

Can draggable annotations not already be supported by draggable text?  If you can just drag the annotation wherever you like, why would it need to be attached to a parent artist?  

> than my actual use case of annotating almost everything in a figure I'm making.

A lot of your use cases seem to be diagraming.  I'm not against diagramming in Matplotlib per-se, but it's a bit orthogonal to the main point of Matplotlib - there are lots of great diagramming GUI-based programs in the world.

**Comment by timhoffm** [comment]
> Can draggable annotations not already be supported by draggable text?

The point here was rather that you drag the artist and the annotation follows along, e.g. you have
![image](https://user-images.githubusercontent.com/1300499/215175726-d4c402a8-7d38-4890-8ced-2b8a7c47088b.png)
and either drag the artist or modify it in an animation, then if the annotation *belongs* to the artist, it should follow where the artist is going.

**Comment by jklymak** [comment]
That seems OK - Do we have an artist transform object - having that evaluated at draw time doesn't seem too hard.

**Comment by rcomer** [comment]
What currently happens if you set `xycoords=my_artist` within `annotate` and then move the artist?  Intuitively, I would expect the text moves with the artist.

**Comment by anntzer** [comment]
@jklymak I think that's close to my IndirectTransform proposal at https://github.com/matplotlib/matplotlib/issues/22223#issuecomment-1011957191?
