### ISSUE TITLE
[Bug]: Scatter plotting of a circle in polar coordinates produces... cardioid!

### ISSUE THREAD

**Issue by fingoldo** [matplotlib/matplotlib#25090]
### Bug summary

I'm happy to withdraw this issue if I'm doing something wrong, but what's expected to be a circle gets drawn as a cardioid, I can't see a reason why.

Wolfram alpha gets it [right ](https://www.wolframalpha.com/input?i=polar+plot&assumption=%7B%22C%22%2C+%22polar+plot%22%7D+-%3E+%7B%22Calculator%22%7D&assumption=%7B%22F%22%2C+%22PolarPlot%22%2C+%22plotfunction%22%7D+-%3E%222*cos%28x%29%22&key=2sj82)though.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

N = 250
sample_phi = 2 * np.pi * np.random.rand(N)
sample_rho = 2 * np.cos(sample_phi)

fig = plt.figure()
ax = fig.add_subplot(projection="polar")
ax.scatter(
    sample_phi, sample_rho,
)
```

### Actual outcome

A chart of a cardioid

[![image](https://www.linkpicture.com/q/photo_2023-01-26_17-33-50.jpg)](https://www.linkpicture.com/view.php?img=LPic63d2976a13cc2848930116)

### Expected outcome

A chart of a circle

[![image](https://www.linkpicture.com/q/photo_2023-01-26_17-33-51-2.jpg)](https://www.linkpicture.com/view.php?img=LPic63d29818a064f976084690)

### Additional information

No idea yet

### Operating system

Windows

### Matplotlib Version

3.6.3

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

Python 3.8.8

### Jupyter version

6.3.0

### Installation

conda

**Comment by jklymak** [comment]
Please discuss at https://discourse.Matplotlib.org.  We can open an issue if a bug is determined.

**Comment by fingoldo** [comment]
I think it's a bug, as with default parameters matplotlib draws something that does not exist in the math reality.
Temporary solution for the ones who stumble on this: limit the r-axis like

`ax.set_rlim(0, 2)`

for [these ](https://discourse.matplotlib.org/t/scatter-plotting-of-a-circle-in-polar-coordinates-produces-cardioid/23508/3) reasons.

You can close the issue again if the number of opened issues is a bigger problem for you than software quality, I won't reopen it anymore.

**Comment by jklymak** [comment]
You passed negative values of r, and then Matplotlib plotted them. You can claim there is no such thing as negative r, but Matplotlib is a general purpose plotting library where people need to plot in all sorts of co-ordinate systems, so we allow negative r.  If you disagree strongly enough to try to get a PR in then https://matplotlib.org/devdocs/devel/contributing.html.  However, you will have to engineer the change such that it doesn't break existing users who may depend on negative values being acceptable.
