### ISSUE TITLE
[Bug]: in VScode, plot closes after script ends or pauses execution until manually closed

### ISSUE THREAD

**Issue by DoudiCoder** [matplotlib/matplotlib#25105]
### Bug summary

In vscode, a script that creates a plot displays the plot but then the program pauses until the plot is closed. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()
```

### Actual outcome

Running the code causes the plot window to open and pause execution until closed. Alternatively, stopping code execution closes the window. 

### Expected outcome

The plot window to open and remain open without blocking the script.

### Additional information

Removing plt.show() or replacing it with plt.show(block=False) doesn't cause the script to pause, but then again there's no plot window in the end.
I'm not using jupyter here, just VS Code's debugger. The launch.json contains: "console": "internalConsole", "internalConsoleOptions": "openOnSessionStart".

### Operating system

MacOS 13.1

### Matplotlib Version

3.6.3

### Matplotlib Backend

MacOS

### Python version

3.10.9

### Installation

pip

**Comment by jklymak** [comment]
This sounds like normal behaviour to me.  Can you clarify why you expect a different behaviour?

**Comment by DoudiCoder** [comment]
Hey, thanks. I was expecting the plots to remain open once the program completed running (or for there to be a way to do that). And ideally without having to pause the script, but I guess I could live with that if I didn't have to close the plot to proceed.

**Comment by jklymak** [comment]
Windows typically close when their parent process dies.  There is no real way to keep them alive.  We have a new guide on figures - perhaps that's I'll help. https://matplotlib.org/devdocs/users/explain/figures.html. Please follow up at https://discourse.Matplotlib.org

**Comment by tacaswell** [comment]
https://matplotlib.org/stable/users/explain/interactive.html and https://matplotlib.org/stable/users/explain/interactive_guide.html are also relevant your question.

The integration of GUI frameworks into debugger repls is extra complicated.
