### ISSUE TITLE
[Bug]: Setting ticks marks on a single spine doesn't work properly

### ISSUE THREAD

**Issue by WWakker** [matplotlib/matplotlib#25117]
### Bug summary

When setting the tick length on the top spine only, it is also applied to the bottom spine, creating space between the bottom of the chart and the axis labels.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot(range(2020, 2025),
        range(-2, 3))

ax.spines['top'].set_position('zero')
ax.spines['bottom'].set_visible(False)
ax.tick_params(labelbottom=True, labeltop=False, bottom=False, top=True)
ax.spines['top'].axis.set_tick_params(length=10)
ax.set_xticks(range(2020, 2025))

plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/63314097/215852450-5f0db731-6256-48df-893c-1ff1352b8d38.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/63314097/215852485-16f455c4-30f5-4905-b0ca-336d9aea5399.png)

### Operating system

Windows

### Matplotlib Version

3.3.4

### Matplotlib Backend

TkAgg

### Python version

3.6.13

### Installation

pip

**Comment by jklymak** [comment]
I don't think the tick parameters are customizable between the top and bottom spines; note that `ax.spines['top'].axis` is the same object as `ax.spines['bottom'].axis`.  

If you want a different spine in the middle of your figure with no labels, you could try using `ax.secondary_xaxis` (https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.secondary_xaxis.html).  It should be completely configurable independent of the main x-axis.  The only issue is that I don't know that you can pin secondary_xaxis to a data value (eg. 0). versus a location on the axes (eg. 0.5)

**Comment by WWakker** [comment]
Okay thanks a lot for clarifying. I could solve the problem completely like this:

```python
import matplotlib.pyplot as plt


def get_location(ax, value, axis='x'):
    lb, ub = ax.get_ylim() if axis == 'y' else ax.get_xlim()
    assert lb <= value <= ub, f"value must be between {lb} and {ub}, found: {value}"
    return value - lb / (ub - lb)


fig, ax = plt.subplots()
ax.plot(range(2021, 2025),
        range(-1, 3))

ax.tick_params(labelbottom=True, bottom=False, top=False)
ax2 = ax.secondary_xaxis(location=get_location(ax=ax, value=0, axis='y'))
ax2.tick_params(labelbottom=False, direction='in', length=10)
ax.set_xticks(range(2021, 2025))

plt.show()
```

![image](https://user-images.githubusercontent.com/63314097/215876683-f66ef7d6-9a65-4f5b-9ab3-f5940588be4c.png)


Closing the issue.

**Comment by jklymak** [comment]
Slight follow up in #25119 - would be nice to be able to place the secondary axes in data co-ordinates
