### ISSUE TITLE
NavigationToolbar breaks if axes are added during use.

### ISSUE THREAD

**Issue by tonysyu** [matplotlib/matplotlib#2511]
The NavigationToolbar saves the history of view limits in a stack. Each time the view is changed, the toolbar pushes the view limits for each axes onto the stack. Each time you go back it pops out the last view limits for each axes.

If you change the number of axes in-between changes to the view limits, then the number of pops won't match the number of pushes (or at least they won't correspond to the correct axes).

Maybe the view stack could be stored on each axes object. Alternatively, the toolbar could store a dictionary mapping axes to view stacks (this might require some manual clean up if axes are deleted).

See also PR #1849.

To reproduce:

```python
plt.subplot(211)
plt.plot([0, 1])

# Pan or zoom the plot.
# If you press the Home button now, you'll return to the original view limits.

plt.subplot(212)

# If you press the Home button now, nothing will happen
```

**Comment by fariza** [comment]
The PRs solved the problem
