### ISSUE TITLE
[Bug]: ax.text() Is Not Rendered If X Specified With ax.plot()

### ISSUE THREAD

**Issue by Matthew1471** [matplotlib/matplotlib#25127]
### Bug summary

ax.text() is not rendered if x values are supplied to ax.plot()

### Code for reproduction

```python
# Straight from the example : https://matplotlib.org/stable/users/explain/api_interfaces.html#api-interfaces

import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.subplots()

# Text works!
#ax.plot([0, 0.5, 1, 0.2])

# Text no works!
ax.plot([1, 2, 3, 4], [0, 0.5, 1, 0.2])

# Text drawing.
ax.text(0, 0, 'Hello!')

plt.show()
```

### Actual outcome

Text is not displayed.

### Expected outcome

Text is displayed.

### Additional information

I narrowed it down to plot with x values means text is not displayed.

### Operating system

Windows

### Matplotlib Version

3.6.3

### Matplotlib Backend

TkAgg

### Python version

3.9.7

### Jupyter version

N/A

### Installation

pip

**Comment by jklymak** [comment]
`text` doesn't change the ylim of the axes like `plot` does, so it is there, just off the axes.   This is expected behaviour.  If you want it to show up then `ax.set_ylim(0, 1.2)`.  Further discussion can be had at https://discourse.matplotlib.org.  Thanks!

**Comment by Matthew1471** [comment]
`ax.set_ylim(0, 1.2)` does not cause the text to show either.

**Comment by timhoffm** [comment]
> `text` doesn't change the ylim of the axes.

Should we have an optional keyword argument that does relim? It seems handy in some cases. Not only is manual limit setting by the user cumbersome and error-prone, it also deactivates future auto-scaling, which may not be desired.

**Comment by jklymak** [comment]
You can autolim on the text anchor, but cannot autolim on the text extent without getting stuck in loops like we did for scatter fixed-size markers.

**Comment by tacaswell** [comment]
If you want to put text relative to a point, see `ax.annotate`.

We have been through the discussion about if text is "data" or "decoration" a couple of times and in the past have come down on the "decoration" side of things which says we should not take text into account in the auto-limit code.  I will make a new issue with thoughts on how to make this happen.
