### ISSUE TITLE
Toolbar layout changed since updated from v3.4.2 to v3.6.3

### ISSUE THREAD

**Issue by aliada77** [matplotlib/matplotlib#25141]
### Bug summary

Since I have updated my matplotlib from v3.4.2 to 3.6.3, Toolbar layout and location has been changed. I had to downgrade matplotlib back to 3.4.2 to have original toolbar layout. I haven't changed anything else with my code. And as I mentioned upon downgrading, toolbar changed back to original layout. I've attached screenshots of both versions.

Please let me know if I'm missing something or this is quite normal with newer versions?

![matplotlib0](https://user-images.githubusercontent.com/83587237/216522733-f471dbb5-66f6-4000-b8e3-da54b46e572a.jpg)
![matplotlib1](https://user-images.githubusercontent.com/83587237/216522741-c235705a-e6cb-466b-b527-fa4329e1169d.jpg)

### Code for reproduction

```python
my code hasn't changed!

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
```

### Actual outcome

![matplotlib1](https://user-images.githubusercontent.com/83587237/216522969-66591ba9-e7c7-4c99-8e65-d77c8196efe4.jpg)

### Expected outcome

![matplotlib0](https://user-images.githubusercontent.com/83587237/216522950-2d4c760d-b85b-4dcf-a247-5162e194d8ad.jpg)

### Operating system

Windows 10

### Matplotlib Version

3.6.3

### Matplotlib Backend

QtAgg

### Installation

None

**Comment by tacaswell** [comment]
Are you sure you are using the Qt backend in both cases?

**Comment by aliada77** [comment]
yes

**Comment by aliada77** [comment]
when I downgrade the matplotlib to 3.4.2, it's Qt5Agg

**Comment by aliada77** [comment]
Thanks @tacaswell , got it fixed with plt.switch_backend('Qt5Agg')
