### ISSUE TITLE
[Bug]: Stale information drawn by animation when using a second Y axis in an tkinter embedded plot

### ISSUE THREAD

**Issue by TheWicklowWolf** [matplotlib/matplotlib#25169]
### Bug summary

Similar to #19116

Animation works correctly when there is a single Y-Axis, however there is an issue when a second Y-Axis is added.
The stale data only exists when plotting against the second Y-Axis.

### Code Elements

```python
self.fig = plt.Figure(layout="constrained")        
self.ax = self.figurePlot.add_subplot(111)
self.embedPlot= FigureCanvasTkAgg(self.fig, self.canvas)

self.anim = animation.FuncAnimation(self.fig, animate, init_func=init, frames=100, interval=1000)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/111055425/217307450-8bb3cf5a-f2c5-4e91-b1f4-ee45d7323647.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/111055425/217306047-0b7a98ff-f024-4d85-9182-6928db2fa4d7.png)

Windows
Matplotlib: 3.6.2
Backend: TkAgg
Python: 3.11.1

**Comment by jklymak** [comment]
Can you provide a full self contained, minimal, example?  The snippet above is not runnable.

**Comment by TheWicklowWolf** [comment]
The Minimal example is not exhibiting the same issue....

**Comment by jklymak** [comment]
That will make it even harder for us to replicate ;-)

**Comment by TheWicklowWolf** [comment]
For some reason the init_func is called again and it looks like that is adding another axis on top (with the old data still visible)...
what cause the init_func to be called again without any error messages?

**Comment by jklymak** [comment]
We have no way to tell w/o an animal example.  I'm going to close for now.  If you would like to discuss further https://disourse.matplotlib.org is a good place to do that.  We can always open another issue if we identify a bug.
