### ISSUE TITLE
bar() (and possibly other plots) should take an array of string labels for x axis

### ISSUE THREAD

**Issue by stevengj** [matplotlib/matplotlib#2516]
It's pretty common to have bar charts where the x axis is a set of string labels rather than numbers.  This can currently be done in pyplot with e.g.
```
bar([1,2,3],[4,3,6], align='center')
gca().xaxis.set_ticks([1, 2, 3])
gca().xaxis.set_ticklabels(['one', 'two', 'three'])
```
but it would be much nicer to simply support
```
bar(['one', 'two', 'three'], [4,3,6])
```
Similarly for `barh` and possibly some other plot types.

cc: @alanedelman

**Comment by yuschat** [comment]
xticks can take care of the labeling problem associated with bar charts. see example below:

import matplotlib.pyplot as plt
x=[1,2,3,4]
labels=['jan','feb','mar','apr']
y=[40,70,30,54]
plt.bar(x,y, align='center')
plt.xticks(x, labels)

Output is shown below:
![bar_chart](https://cloud.githubusercontent.com/assets/12863464/11017148/20cf5490-854b-11e5-87b5-03309b23b2a1.png)
