### ISSUE TITLE
[ENH]: Option for extending Matplotlib's plt.Axes object

### ISSUE THREAD

**Issue by rraadd88** [matplotlib/matplotlib#25178]
### Problem

For customizing matplotlib subplots, I have coded many functions over the years. (I hope I am not the only one doing that.) 
Here are dummy examples of how such functions look like:
```
def set_custom_object1(ax):
      <code to do stuff>
      return ax
def set_custom_object2(ax):
      <code to do stuff>
      return ax
## usage
set_custom_object1(ax)
set_custom_object2(ax)
```

Instead of this way, for convenience, I would like if I could "attach" such functions as attributes to the `plt.Axes` object. Then I could instead easily call them this way in a chained manner:
```
## usage
(ax
  .customize.set_custom_object1(..)
  .customize.set_custom_object2(..)
)
```
Here, ideally a `.customize` attribute could separate my custom functions from the long list (hay-stack) of the default attributes of `plt.Axes`.

Could this be possible out of the box with the current matplotlib API or in some other way?

### Proposed solution

1. Applicability of Custom Figure subclasses: https://matplotlib.org/stable/gallery/subplots_axes_and_figures/custom_figure_class.html
I am not sure if 
(1) it could be applicable to subplots and 
(2) if it could be compatible with subfigures which I started using quite often. 

2. For example, Pandas API extension system: https://pandas.pydata.org/docs/development/extending.html 
I know and have used the pandas API extension system to add custom functions. It is quite convenient and very easy to set up. I wonder if would be possible to have such a facility with matplotlib's `plt.Axes` object.

**Comment by timhoffm** [comment]
Thanks for the proposal.

I'm -1 on adding this natively as an option in matplotlib. We already have too many API paradigms, and adding method changing on top would only add to the confusion.

That said, you can monkey-patch this behavior onto a standard matplotlib:

```
import matplotlib.pyplot as plt
from matplotlib.axes import Axes

# one-time setup

class CustomMethods:
    def __init__(self, ax):
        self.ax = ax

    def plot_with_circles(self, x, y):
        print('plot')
        self.ax.plot(x, y, 'o')
        return self.ax


def _customize(ax):
    if not hasattr(ax, '_custom_methods'):
        ax._custom_methods = CustomMethods(ax)
    return ax._custom_methods


Axes.customize = property(_customize)


# usage example

fig, ax = plt.subplots()
(ax
    .customize.plot_with_circles([0, 1, 2], [1, 3, 2])
    .customize.plot_with_circles([0, 1, 2], [2, 2.5, 4])
)

plt.show()
```

**Comment by mwaskom** [comment]
IMO, trying to get your methods attached to the Axes itself is slightly overthinking things. If you're chaining more than once, calling a special accessor namespace for each method is going to involve more typing than initializing your chain with the class and then chaining _its_ methods.

e.g. using @timhoffm's approach:

```python
(
    CustomMethods(ax)
    .fancy_plot(...)
    .fancy_text(...)
)
```

(of course, `CustomMethods` probably isn't the best class name for this pattern).

**Comment by timhoffm** [comment]
> What about adding this as a gallery example -> "extending the mpl axes object"?

No, sorry. Gallery examples should generally reflect good practice. I very much don't want to encourage people to monkey-patch other libraries and/or change API paradigms on the the fly. If anything such a thing should be published as a third party package with a well defined goal, design and documentation.

---

There are actually two parts in this request

- **Support custom methods on the the Axes namespace (or subnamespace).** This is a reasonable request per-se. We do have the annoying structural difference that builtin functionalies are methods, third-party functionalities are functions. There is no easy solution to this. There's an inherent danger of clashes between external additions and future internal naming needs.
  A milder version of this would be custom accessors [like in pandas](https://pandas.pydata.org/docs/development/extending.html?highlight=plotting%20backend#registering-custom-accessors), though I'd still find this quite audacious. *This would need a very careful design decision.*
- **Support method chaining.** While I see the point of method chaining and it could be discussed when designing a new API, we should not mix more paradigms into the existing APIs.

**Comment by jklymak** [comment]
I think our longer term API discussions have explicitly been going the other way so that we hope to have more submodules like `matplotlib.unstructured.tricontour(ax, x, y, z)` rather than `ax.tricontour()`.  I'm not sure this will ever happen, but it would make the main library more like third-party libraries.  

But I'm not convinced there is an action item here - I'd vote to close this.

**Comment by timhoffm** [comment]
> I think our longer term API discussions have explicitly been going the other way

That is true, but we don’t have a definite master plan for a new API. I think part of that tendency is that it’s a clean solution, whereas everything else has the naming clash problem. OTOH there is value in having a single point of reference and not needing to import bits and pieces from various modules.

Either way, such decisions are among the most fundamental and need an extremely careful consideration. I don’t see that we are working on this any time soon.

**Comment by jklymak** [comment]
>  OTOH there is value in having a single point of reference and not needing to import bits and pieces from various modules.

Agreed - however numpy and script get around this by allowing access to some submodules when you import the top-level module.  Maybe we could do the same.  However, I am somewhat skeptical about this approach, and agree that having the axes as a reference point makes sense and makes for less cluttered plotting code - typing `mpl.basic.scatter(x, y, ax=ax)` every line is not really ideal.  

But anyway, this is off topic here - @rraadd88 thanks for thinking of this, but this would be a big change beyond the scope of a single issue.  I'm going to close this here because I don't think there is anything actionable.
