### ISSUE TITLE
[Bug]: pcolormesh very slow when using log axes

### ISSUE THREAD

**Issue by Ostkreutz** [matplotlib/matplotlib#25171]
### Bug summary

I am plotting a 2D histogram of data contained in a feather file. When using linear axes plotting takes around 1s. However, when using log axes plotting takes about 10s. Masking the array to exclude 0s does not make a difference.
I am using a Jupyter Notebook in VSCodium with Python 3.9.13 (Anaconda, base environment) and matplotlib version 3.5.2.

### Code for reproduction

```python
%matplotlib widget
import feather
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

df_prime = pd.read_feather("FileName")
Z_prime, x_prime, y_prime = np.histogram2d(df_prime.x, df_prime.x, bins=(500, 500))
Z_prime = np.ma.masked_array(Z_prime, Z_prime == 0)

fig = plt.figure(figsize=(2.5 * 13.5 / 2.54, 1.5 * 13.5 / 2.54))
plt.tick_params(labelsize=14)

plt.pcolormesh(x_prime, y_prime, Z_prime.T, norm=LogNorm(), cmap='jet', alpha=0.75)
plt.colorbar(label="Counts in bin")
plt.xscale("log")
plt.yscale("log")
plt.show()
```

### Actual outcome

Outcome is as expected concerning content but takes unexpectedly long.

### Expected outcome

The time to produce the plot should be similar when using linear or log scale.

### Operating system

Arch

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://ipympl.backend_nbagg

### Python version

3.9.13

### Jupyter version

6.4.12

### Installation

None

**Comment by jklymak** [comment]
Can you reproduce using numpy, perhaps with numpy.random.randn?  Or at the very least, let us know how large the data is?  

Note Matplotlib added a misfeature for a release where mousing over a pcolormesh would be very slow. But that doesn't sound like your current issue

**Comment by Ostkreutz** [comment]
Thanks for the quick response. Once the data is plotted mousing over it is no problem (zooming in takes some time though). 
The data being plotted is not very large after passing it through `np.histogram2d` the sizes are the following: `x_prime.shape` = `y_prime.shape` = `(501,)` and `Z_prime.shape` return `(500, 500)`. The data size is determined by the amount of bins specified in `np.histogram2d`. Increasing the size of Z_prime to (1000, 1000) results in an increase in plotting time of about a factor of 4. 

It also does not matter if the `np.histogram2d` command is in the same cell or not. Meaning that the plotting seems to responsible for the slow execution speed.

**Comment by jklymak** [comment]
On Matplotlib main, it is definitely a bit slower to have a log scale than not, but I'm not sure what we can do about that. For 2000x2000 I get 
with log: 0.6046700477600098 s
with linear: 0.4670751094818115 s

Are you saving to svg in your notebook?  If I do that I get for 500x500:

```
with log: 4.928969860076904
with linear: 5.520771026611328
```

If you want to speed up svg saves you can rasterize the pcolormesh: 

```
plt.pcolormesh(x_prime, y_prime, Z_prime.T, norm=LogNorm(), cmap='jet', alpha=0.75, rasterized=True)
```

and then I recover the png save times.  


```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time

N = 500
x_prime = y_prime = np.arange(N+1)
Z_prime = np.random.randn(N, N)
Z_prime = np.ma.masked_array(Z_prime, Z_prime <= 0)

t0 = time.time()
fig = plt.figure(figsize=(2.5 * 13.5 / 2.54, 1.5 * 13.5 / 2.54))
plt.pcolormesh(x_prime, y_prime, Z_prime.T, norm=LogNorm(), cmap='jet', alpha=0.75, rasterized=True)
plt.colorbar(label="Counts in bin")
plt.xscale("log")
plt.yscale("log")
fig.savefig('Log.svg')
print(time.time()-t0)


t0 = time.time()
fig = plt.figure(figsize=(2.5 * 13.5 / 2.54, 1.5 * 13.5 / 2.54))
plt.tick_params(labelsize=14)

plt.pcolormesh(x_prime, y_prime, Z_prime.T, norm=LogNorm(), cmap='jet', alpha=0.75, rasterized=True)
plt.colorbar(label="Counts in bin")
fig.savefig('Linear.svg')
print(time.time()-t0)
```

**Comment by Ostkreutz** [comment]
Thank you for the response. At the moment I saving it as a .png file and that is perfectly fast.
However, it looks like it has to do with my data for some reason. Creating a random array with numpy I don't observe any noticeable difference between linear and log scale. I will have to look into if there is something wrong with my data I guess.

Thank you for your help, it is greatly appreciated and sorry for bothering.

**Comment by jklymak** [comment]
I'm going to close - please ask for a re-open or open a new issue if you think there still is something we can do here...
