### ISSUE TITLE
[ENH]: Align titles of subplots, similar to `fig.align_labels`

### ISSUE THREAD

**Issue by rraadd88** [matplotlib/matplotlib#25180]
### Problem

While formatting figures, along with aligning axis labels, aligning titles is often necessary. To do that, without the availability of a simple and convenient method like `fig.align_labels`, I find myself going through multiple rounds of 

Plotting → changing `y` parameter of `ax.set_title` → replotting.

Plus the re-alignments are necessary if the figure/subplot size and layout are changed.

![image](https://user-images.githubusercontent.com/9945034/217891731-4a989436-f452-4a8a-9e61-3ffdad001126.png)

Could there be a simple and convenient way to align the titles of subplots, using maybe a method that is similar to `fig.align_labels`?

### Proposed solution

Perhaps the general method of how labels are aligned using `fig.align_labels` could be extended to align titles.  I am no expert on `matplotlib`'s API, but I wonder if [`cbook.Grouper`](https://github.com/matplotlib/matplotlib/blob/c23ccdde6f0f8c071b09a88770e24452f2859e99/lib/matplotlib/figure.py#L1391) could do this.

FYI, I know there is a way to align titles [using `subfigures` and `suptitles`](https://stackoverflow.com/a/71764078). But I would prefer not to convert subplots to subfigures only to align titles.

**Comment by jklymak** [comment]
I don't think there is any huge blocker on that.  But lets keep discussion in #22376
