### ISSUE TITLE
annotate places the number 1 off center when saved as a pdf

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#2519]
I am finding that the annotate function places the number 1 off center when the figure is saved as a pdf. All other numbers appear to be fine. For example,

```
import matplotlib.pylab as plt
fig = plt.figure(figsize = (5,5))
ax = plt.subplot(111)
ax.plot([0,1], [0,1])

txts = ['1', '2', '3']
y_coords = [0.9, 0.8, 0.7]
for txt, y_coord in zip(txts, y_coords):
    ax.annotate(txt, xy = (0.25, y_coord), \
        size=36, va='center', ha='center', fontname = 'Helvetica', \
        bbox=dict(boxstyle='square', fc = 'w'))

plt.savefig('Test.pdf', bbox_inches = 'tight', pad_inches = 0)
plt.savefig('Test.jpg', bbox_inches = 'tight', pad_inches = 0)
```

produces a pdf file that looks like this

![pdf](http://s7.postimg.org/w41b8tj6z/Test1_page_1.jpg)

and a jpg file that looks like this

![jpg](http://s11.postimg.org/nldehvzgz/Test.jpg)

In the pdf, the 1 is not in the center of the rectangle, but the 2 and 3 are in the centers of their respective rectangles. In the jpg, all three numbers are in the center of their respective rectangles. If I was creating rasterized images I would be happy with the jpg, but I really want a pdf output.

Is this a bug?

I am using Matplotlib 1.2.1 on Python 2.7.3 under Mac OS X 10.8.5

**Comment by story645** [comment]
this seems really similar to #2627

**Comment by QuLogic** [comment]
This looks perfectly fine to me, but the original screenshots are gone, so I don't know what the problem was.

**Comment by breedlun** [comment]
When I run 

```
import matplotlib.pylab as plt
fig = plt.figure(figsize = (5,5))
ax = plt.subplot(111)
ax.plot([0,1], [0,1])

txts = ['1', '2', '3']
y_coords = [0.9, 0.7, 0.5]
for txt, y_coord in zip(txts, y_coords):
    ax.annotate(txt, xy = (0.25, y_coord), \
        size=36, va='center', ha='center', fontname = 'BitStream Vera Sans', \
        bbox=dict(boxstyle='square', fc = 'w'))

plt.savefig('Test.pdf', bbox_inches = 'tight', pad_inches = 0)
plt.savefig('Test.png', bbox_inches = 'tight', pad_inches = 0)
```

in matplotlib 2.2.3, here is the pdf:
[Test.pdf](https://github.com/matplotlib/matplotlib/files/4529453/Test.pdf)
and here is the png:
![Test](https://user-images.githubusercontent.com/4099759/80223045-fa90b480-8604-11ea-8c2c-21b2dfbeabbc.png)

They look pretty similar to me.  Either something changed over the last 6.5 years or I became less picky.  (I tried to load an old version of matplotlib on my hard drive to see if things were different 6.5 years ago, but pyplot failed to import.)  My only complaint is the bounding boxes are too low relative to the text in both the pdf and png, but that is different from the original issue, so I am closing.
