### ISSUE TITLE
Urgent: Update project size

### ISSUE THREAD

**Issue by henrykironde** [matplotlib/matplotlib#25208]
Please add the missing required, 175 or 350 hr designation. Also add the expected outcomes and level of difficulty.
A good example is https://github.com/colour-science/GSoC/blob/master/2023/GSoC-2023-Project-Ideas.md#implement-support-for-cxf---color-exchange-format
@ksunden 

https://github.com/matplotlib/matplotlib/wiki/GSoC-2023-Ideas

**Comment by ksunden** [comment]
I will take care of this shortly.

**Comment by ksunden** [comment]
Updated the wiki page

**Comment by henrykironde** [comment]
@ksunden you have a project that has both 175 and 350. Please use either 175 of 350 not both.

**Comment by ksunden** [comment]
> It is also possible that a given project idea could be 175 hours or 350 hours depending on the scope of the idea. If the GSoC contributor proposes to do a smaller scope of the idea then it might be a 175 hr project versus if they propose doing more work with their proposal it could be a 350 hour project.

From: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list#

I read that as very specifically and explicitly allowing such projects.

**Comment by henrykironde** [comment]
Think about it this way: If you have a budget and you have to choose organizations (projects) based on the budget, It is more likely that you will choose those organizations that have an explicit budget. 

If you are not sure about a project, you can use 350 and downgrade it later. Or if you choose 175 hours and more time is needed, Google may provide extensions. For the purposes of the organization getting through the selection round, be explicit with the hours, please. We were asked to rectify that, and I am supposed to report back today.

**Comment by ksunden** [comment]
Okay, I've updated
