### ISSUE TITLE
[Doc]: `layout="none"` for figure constructor?

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#25223]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.figure.html

### Problem

Suppose you have constrained layout turned on in general via `rcParams`, but want to not use it for a particular figure.  This seems to work

```python
import matplotlib.pyplot as plt

plt.rcParams["figure.constrained_layout.use"] = True
fig = plt.figure(layout="none")
print(fig.get_layout_engine())
```
```
None
```
but `layout="none"` is not documented as a valid option in either `pyplot.figure` or the [Figure](https://matplotlib.org/devdocs/api/figure_api.html#matplotlib.figure.Figure) constructor.

### Suggested improvement

Should  `layout="none"`  be documented as a valid option?

**Comment by timhoffm** [comment]
Yes! 👍

**Comment by rcomer** [comment]
Thanks @RishabhSpark, the relevant docstrings are [here for pyplot.figure](https://github.com/matplotlib/matplotlib/blob/50fc5dd4475caa9d1d39f50780ee1da137bb99db/lib/matplotlib/pyplot.py#L700-L774) and [here for the Figure constructor](https://github.com/matplotlib/matplotlib/blob/50fc5dd4475caa9d1d39f50780ee1da137bb99db/lib/matplotlib/figure.py#L2381-L2460).  For bonus points, you could also add the `layout="compressed"` option to the `pyplot.figure` docstring, as that is also missing.

**Comment by QuLogic** [comment]
It appears you've added 'compressed', but not 'none' as well?
