### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gmyMing** [matplotlib/matplotlib#25227]
### Bug summary

Failed to use matplotlib.pylot on windows

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-1,1,50)
y1=2*x+1
y2=x**2
plt.figure()
plt.plot(x,y1)
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/39206813/219301773-76b6dbc7-012f-4871-b4e2-ce2af58fc8f0.png)

### Expected outcome

it should generate a line figure

### Additional information

all simple plot programs I ran failed
python version is 3.10.0
matplotlib is 3.7.0
I ran this program on windows 10.
I installed matplotlib through the pycharm interpreter. 

### Operating system

windows

### Matplotlib Version

3.7.0

### Jupyter version

3.7.0

### Installation

pip

**Comment by anntzer** [comment]
Please indicate your version of pycharm.

**Comment by gmyMing** [comment]
> Please indicate your version of pycharm.

![image](https://user-images.githubusercontent.com/39206813/219577022-43afad80-ef71-4c82-b432-b1f83d20248a.png)
the version is 2022.2. btw, Due to the security rule of my company, we cannot installed these softwares casually. These softwares are installed by the company IT department. I am not sure whether this will affect using Matplotlib

**Comment by anntzer** [comment]
I cannot check right now but it seems extremely unlikely that that version of pycharm is compatible with Matplotlib 3.7, at least given https://github.com/JetBrains/intellij-community/commit/808410bf8b98a6f91af5612b74271555317f2852.
Please consider downgrading Matplotlib if you cannot upgrade pycharm.
