### ISSUE TITLE
[Bug]: Subplotnumber as a tuple is broken

### ISSUE THREAD

**Issue by HabermannR** [matplotlib/matplotlib#25229]
### Bug summary

It should be possible to give the subpolt as tuple:
        fig : `matplotlib.figure.Figure`

        *args : tuple (*nrows*, *ncols*, *index*) 

### Code for reproduction

```python
from matplotlib.transforms import Affine2D
import mpl_toolkits.axisartist.floating_axes as floating_axes
import matplotlib.pyplot as plt


fig = plt.figure(1, figsize=(8, 4))
tr = Affine2D().scale(2, 1).rotate_deg(30)

grid_helper = floating_axes.GridHelperCurveLinear(
        tr, extremes=(0, 4, 0, 4))
ax1 = floating_axes.FloatingSubplot(fig, (1,1,1), grid_helper=grid_helper)
fig.add_subplot(ax1)
```

### Actual outcome

  File "C:\Temp\pythonProjectTestMatplotlib\Test2.py", line 11, in <module>
    ax1 = floating_axes.FloatingSubplot(fig, (1,1,1), grid_helper=grid_helper)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\axes\_subplots.py", line 36, in __init__
    self.set_subplotspec(SubplotSpec._from_subplot_args(fig, args))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\gridspec.py", line 578, in _from_subplot_args
    raise ValueError(
ValueError: Single argument to subplot must be a three-digit integer, not (1, 1, 1)

### Expected outcome

plot the subplot, as
ax1 = floating_axes.FloatingSubplot(fig, 111, grid_helper=grid_helper)

### Additional information

Gridspec.py:
    def _from_subplot_args(figure, args):
        """
        Construct a `.SubplotSpec` from a parent `.Figure` and either

        - a `.SubplotSpec` -- returned as is;
        - one or three numbers -- a MATLAB-style subplot specifier.
        """
        if len(args) == 1:

but args is a tuple with len 1, and then the tuple is inside this.
Bugfix:

        try:
            l = len(args[0])
        except:
            l = 1
        if l == 1:
            arg, = args
            if isinstance(arg, SubplotSpec):
                return arg
            elif not isinstance(arg, Integral):
                raise ValueError(
                    f"Single argument to subplot must be a three-digit "
                    f"integer, not {arg!r}")
            try:
                rows, cols, num = map(int, str(arg))
            except ValueError:
                raise ValueError(
                    f"Single argument to subplot must be a three-digit "
                    f"integer, not {arg!r}") from None
        elif l == 3:
            rows, cols, num = args[0]
        else:
            raise TypeError(f"subplot() takes 1 or 3 positional arguments but "
                            f"{len(args)} were given")

### Matplotlib Version

3.6.3

### Installation

pip

**Comment by rcomer** [comment]
Thanks @HabermannR for taking the time to raise this.  The example works if you specify your tuple elements as individual arguments, i.e.

```python
ax1 = floating_axes.FloatingSubplot(fig, 1,1,1, grid_helper=grid_helper)
```

This form is consistent with [pyplot.subplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html#matplotlib-pyplot-subplot) and [Figure.add_subplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html#matplotlib-pyplot-subplot), so I am not sure that supporting a tuple is intended.  Did that work in a previous version, or could you link to some documentation that suggests it should work?
