### ISSUE TITLE
[ENH]: add organizational charts to supported plots

### ISSUE THREAD

**Issue by rbt94** [matplotlib/matplotlib#25222]
### Problem

I would like to efficiently use matplotlib to produce also organizational charts like the Ishikawa (fishbone) diagram to include also the cause-effect relationships into professional and academical documents. For the Ishikawa case, it could be interesting to modify the treeplot by using a fractal layout for the spines. 

Thank you for your consideration.

**Comment by jklymak** [comment]
Thanks for your interest in improving Matplotlib!  

That type of chart is super-specialized and I would expect better suited to an external library.  We don't provide a tree plot, either, though https://github.com/erdogant/treeplot does.  If the external library proved popular, and/or there was a compelling reason it needed to be in core, it would certainly be possible to consider.

**Comment by jklymak** [comment]
Think about this more, it is definitely something that should be developed elsewhere.  The API for this will be extremely broad, so best to refine it first.  Please feel free to approach us again if there is a package that should be subsumed, or if it is not possible to make what you want without changing Matplotlib internals.

**Comment by rbt94** [comment]
Thank you @jklymak for the support. I will try to ask the same to some dedicated projects or I will implement it for specific cases little by little. 
Regards,
Robert

**Comment by rbt94** [comment]
PS: For one that will read the post in the future, I have implemented only the Ishikawa plot from scratch by using only matplotlib and numpy. 
You can find the code here: [fishbone diagram using Python or graphviz](https://stackoverflow.com/questions/51348536/fishbone-diagram-using-python-or-graphviz)

**Comment by jklymak** [comment]
Great!  Your s/o post seems modest sized so consider adding to our examples?
