### ISSUE TITLE
[Bug]: colors.PowerNorm results in incorrect colorbar

### ISSUE THREAD

**Issue by julietbravo** [matplotlib/matplotlib#25239]
### Bug summary

`colors.PowerNorm` ignores the (in this case) `vmin` values, and the resulting colorbar seems to b incorrect.

### Code for reproduction

```python
import matplotlib.pyplot as pl
import matplotlib.colors as colors
import numpy as np
    
data = np.random.random(100*100).reshape(100,100) * 600 + 398
    
pl.figure()
pl.imshow(data, cmap=pl.cm.terrain, norm=colors.PowerNorm(gamma=0.2, vmin=398, vmax=1000))
pl.colorbar()
```

### Actual outcome

It seems that `vmin` is changed to some pretty number (in this case 300), but as a result, the colorbar seems to be incorrect. In the screenshot, my mouse is hoovering over the blue data point, which has a value of 398.062 (see value in top right corner of window). However, corresponding values in the colorbar are greenish, while blue colors correspond to much lower numbers.

![Screenshot_20230217_102233](https://user-images.githubusercontent.com/1067637/219608204-943746e0-cd01-4f8e-9cd3-b79e0e690c37.png)

### Expected outcome

I would expect matplotlib to respect the `vmin` and `vmax` values that I set in `colors.PowerNorm`.

You can best see the correct outcome if you manually set `vmin` at the value that matplotlib chooses:

```
import matplotlib.pyplot as pl
import matplotlib.colors as colors
import numpy as np

data = np.random.random(100*100).reshape(100,100) * 600 + 398

pl.figure()
pl.subplot(121)
pl.imshow(data, cmap=pl.cm.terrain, norm=colors.PowerNorm(gamma=0.2, vmin=398, vmax=1000))
cb=pl.colorbar()

pl.subplot(122)
pl.imshow(data, cmap=pl.cm.terrain, norm=colors.PowerNorm(gamma=0.2, vmin=300, vmax=1000))
cb=pl.colorbar()
```

![Figure_4](https://user-images.githubusercontent.com/1067637/219611832-d1ec17f0-2302-4cf0-a29f-cdb6ab28b1cb.png)

### Operating system

Manjaro Linux

### Matplotlib Version

3.6.2

### Matplotlib Backend

Qt5Agg

### Python version

3.10.9

### Jupyter version

None

### Installation

pip

**Comment by dstansby** [comment]
I can reproduce this, thanks for the clear example. It's also present on older versions (3.5.0 and 3.6.0), so isn't a recent bug.

**Comment by dstansby** [comment]
And it looks like this is an issue with the colobar axis labelling, not the actual data limits on the colobar. If I hover over the bottom of the colorbar, values of ~398 show up, so it's just the labelling of the colorbar that's going wrong.

**Comment by jklymak** [comment]
`PowerNorm(300)` returns 0, so any value below 398 gets returns at the 0 point of the colorbar.  The automatic tick finding tries 300, and it gets put at 0 so it stays.

The offending line is at https://github.com/matplotlib/matplotlib/blob/238e275b2f931bee0589ae3a742f58e302f804cb/lib/matplotlib/colors.py#L1889. 

In my opinion PowerNorm is broken in other ways: it maps to 0 to 1 first, and then applies the power law, whereas our other Norms apply the transform first and then normalize from 0 to 1.   

$$ \frac{(x-m)^\gamma}{(M-m)^\gamma} \neq \frac{(x^\gamma - m^\gamma)}{M^\gamma - m^\gamma}$$
