### ISSUE TITLE
[Bug]: Huge margin with `supxlabel`, `y` not working as intended

### ISSUE THREAD

**Issue by OverLordGoldDragon** [matplotlib/matplotlib#25231]
### Bug summary

Feels like a bug but unsure if qualifies. `y` doesn't work as intended in `supxlabel`, in that there's a dependence on `figsize` and `nrows`, yet it's supposedly fractional. Not terrible with few `nrows`, but really bad with many.

Ideally the positioning is independent of `nrows` and `figsize`, but practically there shouldn't be such massive gaps.

### Code for reproduction

```python
fig, _ = plt.subplots(20, 1, figsize=(10, 20))
fig.supxlabel("supxlabel")
```

### Actual outcome

<img src="https://i.stack.imgur.com/gop8B.png">

### Expected outcome

In this case, `y=0.1` does the trick, but not always.

![image](https://user-images.githubusercontent.com/16495490/219392611-21106320-61e8-4bad-a46f-e9a6c900e571.png)

### Operating system

Windows 10

### Matplotlib Version

3.6.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.4

### Installation

conda

**Comment by jklymak** [comment]
The default axes placement is y=0.1, whereas the supxlabel is at 0.   If you want automated layout., where the axes sizes are expanded to fill the figure, use `layout='constrained'`.   I'm going to close, as this is working as expected, but happy to discuss further in https://discourse.matplotlib.org

**Comment by OverLordGoldDragon** [comment]
`layout='constrained'`
```
D:\Anaconda\envs\jgpu-env\lib\site-packages\IPython\core\events.py:89: UserWarning: constrained_layout not applied because axes sizes collapsed to zero.  Try making figure larger or axes decorations smaller.
  func(*args, **kwargs)
D:\Anaconda\envs\jgpu-env\lib\site-packages\IPython\core\pylabtools.py:151: UserWarning: constrained_layout not applied because axes sizes collapsed to zero.  Try making figure larger or axes decorations smaller.
  fig.canvas.print_figure(bytes_io, **kw)
```
> working as expected

So what is "figure coordinates" in

> y : float, default: 0.01
    The y location of the text in figure coordinates.

 The default `y=.01` depends on `figsize`, so it doesn't appear to be fraction of figure size. I searched "matplotlib figure coordinates", couldn't find docs, so at least this should be clarified @jklymak

**Comment by jklymak** [comment]
Fraction of figure size does depend on figure size.  0 is the bottom, 1 is the top, 0.5 is the middle.

**Comment by OverLordGoldDragon** [comment]
`y=0.1` on height of `10` is `1` but on `20` isn't `2`, is what I'm saying (and showing in OP).

**Comment by OverLordGoldDragon** [comment]
In the first figure `y` acts as a negative fraction of figure size, it enlarges the figure, I don't see any meaningful definition of "figure coordinates" that'd behave this way.

**Comment by jklymak** [comment]
The inline backend uses bbox_inches="tight" to display graphs.  Please save as png using savefig without `bbox_inches='tight'` and this will all be less mysterious.

**Comment by jklymak** [comment]
- Constrained_layout will fix the space between the supxlabel and the axes.  It will fail altogether if you put too many axes into too small a space, so for your 12 inch tall case it fails for the 20 inch tall it works just fine
- bbox_inches='tight' trims around all artists.  Your confusion about the meaning of figure-relative units comes from bbox_inches changing the size of the figure _after_ the artists have been placed.

**Comment by OverLordGoldDragon** [comment]
Well I've found my workaround with a formula and I still think `y`'s functionality could be explained better, but thanks for the info.

**Comment by tacaswell** [comment]
@OverLordGoldDragon Now that you understand this, what wording in the documentation would have made this clearer?  E.g. if what would you write now to communicate to your past-self that would have avoided your confusion?

**Comment by OverLordGoldDragon** [comment]
Well, I don't understand it. What I know is "look back to this post and read docs of the mentioned kwargs, they'll probably explain it". To me it still looks like an API that fights itself, in that there's some kwargs that make life easier, but we can't use them if we want advanced functionality. I'll mind this post if I ever do understand it though.

p.s., my workaround is [`y = np.sqrt(height) / 100 * 2.2`](https://stackoverflow.com/a/75474113/10133797) for `height` 5 to 25.

**Comment by jklymak** [comment]
Again strongly suggest you just use constrained layout to avoid manually tweaking your figures like this. Your scaling above won't survive xlabels added individual axes, colorbars, etc.   https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html

```python
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
# import matplotlib.cm as cm
import numpy as np

fig, axs = plt.subplots(6, 2, figsize=(4, 8),
                        facecolor='lightskyblue',
                        sharex=True, sharey=True)
fig.supxlabel('supxlabel, default', fontsize='medium')
```
![default](https://user-images.githubusercontent.com/1562854/220399366-6f170cd1-a18f-48f5-8a20-3c979c7939e8.png)


```python

fig, axs = plt.subplots(6, 2, figsize=(4, 8),
                        facecolor='lightskyblue',
                        sharex=True, sharey=True)
fig.supxlabel('supxlabel, y=0.05', fontsize='medium', y=0.05)
```
![Manual](https://user-images.githubusercontent.com/1562854/220399500-b05d2852-19e8-4160-b74c-906d1e6b5686.png)

```python
fig, axs = plt.subplots(6, 2, figsize=(4, 8),
                        facecolor='lightskyblue',
                        layout='constrained', sharex=True,
                        sharey=True)
fig.supxlabel('supxlabel, constrained', fontsize='medium')
```
![Constrained](https://user-images.githubusercontent.com/1562854/220399580-f238c58d-6985-45df-87a1-9ad36ea4ffe6.png)
