### ISSUE TITLE
[Bug]: tricontourf collections structure different than contourf

### ISSUE THREAD

**Issue by cvr** [matplotlib/matplotlib#25241]
### Bug summary

When creating a filled contour with `contourf` one gets a `matplotlib.contour.QuadContourSet` which is a collection of paths. These follow some generic rules where each individual filled shape is an individual entity (with 1 exterior line-ring and the N interior line-rings demarcate holes, unless the signs is the same as the exterior line).

But when creating a filled contour with `tricontourf` the structure of the equivalent object, `matplotlib.tri.tricontour.TriContourSet`, is significantly different. The paths are all merged together into a giant path for each contour level.

Though this draws correctly on screen, this then creates problems if the paths are to be used for other purposes (e.g. to be processed in Shapely for example).

![bug_matplotlib_tricontour_quadpath](https://user-images.githubusercontent.com/1119116/219628376-0daa3904-d841-43f6-bf06-0eb814382602.png)
![bug_matplotlib_tricontour_tripath](https://user-images.githubusercontent.com/1119116/219628398-f097ba88-e444-46e6-a045-31b49ca946be.png)
![bug_matplotlib_tricontour](https://user-images.githubusercontent.com/1119116/219635625-eba291b9-9e9a-4e70-b1de-84f35cc537b5.png)

### Code for reproduction

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.path
import matplotlib.patches
import matplotlib.tri

def path2polygons(path):
    """Convert a matplotlib.path.Path to a set of polygons."""
    assert isinstance(path, mpl.path.Path), f"Type of input is {type(path)} instead of Path"
    codesOld = path.codes[path.codes != mpl.path.Path.CLOSEPOLY]
    vertsOld = path.vertices[path.codes != mpl.path.Path.CLOSEPOLY]
    jj = np.append(np.flatnonzero(codesOld == path.MOVETO), [len(codesOld)])
    verts, codes = [], []
    for ji, je in zip(jj[:-1], jj[1:]):
        codes.extend( list(codesOld[ji:je]) + [mpl.path.Path.CLOSEPOLY] )
        verts.extend( list(vertsOld[ji:je]) + [vertsOld[ji]] )
    return mpl.path.Path(verts, codes).to_polygons()


def plotPath(path, ax=None, **kwargs):
    polygons = path2polygons(path)
    ax = ptl.gca() if None is ax else ax
    if not 'facecolor' in kwargs.keys() or 'fc' in kwargs.keys():
        kwargs['facecolor'] = 'turquoise'
    if not 'edgecolor' in kwargs.keys() or 'ec' in kwargs.keys():
        kwargs['edgecolor'] = 'turquoise'
    ax.add_patch(mpl.patches.PathPatch(path, **kwargs))
    return


## create bogus field
F = np.zeros((7, 14), dtype=float)
F[1:6,1:10] = 2.
F[1:6,12:] = 2.
F[2:5,2:5] = 4.
F[3,3] = 6.
F[2:5,6:9] = 0.
F[3,7] = -2.
F[3,13:] = 4.
X, Y = np.meshgrid(*map(range, F.shape[::-1]),  indexing='xy')

lev = [-1, 1, 3, 5]
cmap = plt.cm.plasma



plt.close('all')
fig, axs = plt.subplots(2, 2)
axs = axs.flatten()

ax = axs[0]
ax.set_title('quad contour')
c4 = ax.contourf(X, Y, F, levels=lev, cmap=cmap, extend='both')
_ = [path.set_edgecolor("face") for path in c4.collections]  # https://stackoverflow.com/a/73805556/921580
_ = [c.set_linewidth(1e-8) for c in c4.collections]

axs[1].set_title('quad paths')
axs[1].set_xlim(*axs[0].get_xlim())
axs[1].set_ylim(*axs[0].get_ylim())
for c in c4.collections:
    for path in c.get_paths():
        plotPath(path, ax=axs[1], facecolor=c.get_facecolor(), edgecolor=c.get_edgecolor(), linewidth=c.get_linewidth())

ax = axs[2]
ax.set_title('tri contour')
tri = mpl.tri.Triangulation(X.flatten(), Y.flatten())
v = F.flatten()
# mask = mpl.tri.TriAnalyzer(tri).get_flat_tri_mask(min_circle_ratio=.01)  # mask badly shaped triangles
c3 = ax.tricontourf(tri, v, levels=lev, cmap=cmap, extend='both')
_ = [path.set_edgecolor("face") for path in c3.collections]  # https://stackoverflow.com/a/73805556/921580
_ = [c.set_linewidth(1e-8) for c in c3.collections]
ax.triplot(tri, color='k', lw=.5, alpha=.1)

axs[3].set_title('tri paths')
axs[3].set_xlim(*axs[2].get_xlim())
axs[3].set_ylim(*axs[2].get_ylim())
for c in c3.collections:
    for path in c.get_paths():
        plotPath(path, ax=axs[3], facecolor=c.get_facecolor(), edgecolor=c.get_edgecolor(), linewidth=c.get_linewidth())

#cb = plt.colorbar(cf, cax=cax)
fig.tight_layout(pad=.4, w_pad=.5, h_pad=.5)
plt.savefig("bug_matplotlib_tricontour.png")

plt.show()


print(f"number of paths in Quad Contour collection: {[len(c.get_paths()) for c in c4.collections]}")
print(f"number of paths in Tri  Contour collection: {[len(c.get_paths()) for c in c3.collections]}")

print(f"Focusing on one path only:")
print(f"Quad Contour collection[3].get_paths():\n{c4.collections[3].get_paths()}")
print(f"Tri  Contour collection[3].get_paths():\n{c3.collections[3].get_paths()}")
```

### Actual outcome

![bug_matplotlib_tricontour_tripath](https://user-images.githubusercontent.com/1119116/219628398-f097ba88-e444-46e6-a045-31b49ca946be.png)

### Expected outcome

Something similar to the structure that a Quad Contour returns.
![bug_matplotlib_tricontour_quadpath](https://user-images.githubusercontent.com/1119116/219628376-0daa3904-d841-43f6-bf06-0eb814382602.png)

### Operating system

Debian 10

### Matplotlib Version

3.4.1

### Matplotlib Backend

TkAgg

### Python version

3.7.3

### Installation

pip

**Comment by ianthomas23** [comment]
@cvr You are correct, the format of data generated by `tricontourf` is different to that generated by `contourf`. `tricontourf` does not identify which polygons are outer boundaries and associate them with their corresponding inner boundaries, whereas `contourf` does. This is unlikely to change. In fact it is much more likely that `contourf` might change to a similar format to `tricontourf` than the other way around.

Note that `matplotlib` is a plotting library and the internal data formats used are those that are both (1) available and (2) suitable for plotting. If you want to use the calculated data for some other purpose outside of `matplotlib` then you are welcome to do so but if the format isn't to your satisfaction then it is your responsibility to convert it, not `matplotlib`'s. I am pretty sure that it is trivial to do this in `shapely` but I am not an expert in that area.

**Comment by dstansby** [comment]
As per the above comment I'll close this as not planned.

**Comment by rcomer** [comment]
In fact we have gone the other way:

> The paths are all merged together into a giant path for each contour level.

Is true for the `QuadContourSet` since v3.8.0.
