### ISSUE TITLE
[Doc]: Add annotated image of the figure GUI to explain what the different buttons do

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib#25266]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/interactive.html

### Problem

We currently don't have documentation that I can find which shows how to interact with the figure GUI. The buttons have tooltips, but if a user is not familiar with that mode of getting information then they might be at a loss of what to do.

![image](https://user-images.githubusercontent.com/14363975/220168907-e0dcba0f-2dca-42f8-9b44-3bddc9be6739.png)

### Suggested improvement

It would be nice to include at least an annotated image of the GUI calling out what the different buttons do. We can also use this opportunity to document the hover coordinates. Note that we should cover both 2D and 3D plots, as the rotate/pan/zoom behavior is slightly different between them.

It would be even better if we had a short video / animated gif showing someone interacting with the plot using the GUI buttons.

**Comment by tacaswell** [comment]
https://matplotlib.org/2.2.5/users/navigation_toolbar.html?highlight=interactive used to exist and 

https://matplotlib.org/3.2.0/users/navigation_toolbar.html?highlight=interactive appears to be the last version where it exists....

It appears that I am the villain here and deleted this page it in bb8058aaac96b682460b65bbe9dc59cdac8d6315 😞

**Comment by tacaswell** [comment]
I'm working on a PR to just put this page back more-or-less as-was, but there may still be more work to do to fold in to the current docs more effectively

**Comment by tacaswell** [comment]
I am going to close this as addressed by #25926.

Using icon images has advantages over an annotated screen shots.  It is no extra files (we have to have the icons), will stay in sync if we ever change them, and makes the documentation GUI toolkit agnostic (we put the toolbar at the top / bottom / side depending on the toolkit)
