### ISSUE TITLE
Vertical alignment of text is too high

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#2527]
One of the improvements to matplotlib 1.3.0 is supposed to be improved vertical alignment of text, but it appears to have gotten worse in my experience.  Here is an example:

    import matplotlib.pylab as plt
    mpl.rcParams['font.size'] = 24
    fig = plt.figure(figsize = (5,5))
    ax = plt.subplot(111)
    ax.plot([0,1], [0,1])

    txts = ['1', '2', '3']
    y_coords = [0.8, 0.5, 0.2]
    for txt, y_coord in zip(txts, y_coords):
        ax.annotate(txt, xy = (0.25, y_coord), fontname = 'Helvetica', \
            size=36, va='center', ha='center', \
            bbox=dict(boxstyle='square', fc = 'w'))

    plt.savefig('Test.png', bbox_inches = 'tight', pad_inches = 0)

In matplotlib 1.2.1 the png looks like this

![test_mpl_1 2 1](https://f.cloud.github.com/assets/4099759/1348845/084b2db4-36d7-11e3-8366-613f010a891b.png)

but in matplotlib 1.3.0 the png looks like this

![test_mpl_1 3](https://f.cloud.github.com/assets/4099759/1348848/4dfc388a-36d7-11e3-85d8-3fffd7e15fba.png)

The numbers in the the v1.3.0 png are too high.  The numbers should be in the center of the rectangular boxes, and the center of the tick mark numbers should line up with the tick marks.

**Comment by efiring** [comment]
@mdboom, is there some possible compromise?  Maybe reduce the bottom padding?  Aesthetically, @breedlun is right; for numbers or anything without descenders, the present centering doesn't look good.

**Comment by breedlun** [comment]
Does #6200 fix the vertical alignment for all text, or just y-tick mark text?

**Comment by tacaswell** [comment]
Just y tick by default, but introduced a new alignment value you can use
anywhere.

**Comment by breedlun** [comment]
OK.  I will try out this new alignment value before v2.0 gets released.

**Comment by breedlun** [comment]
I finally got around to trying v2.0.  The alignment of vertical tick mark labels looks great!  In addition, I noticed that the subscripts and superscripts generated by mathtext have better vertical positioning too. Thanks @mdboom!  Virtually none of the default changes in v2.0 affect me (I have all my own defaults set up), but the improved vertical alignment/positioning made the upgrade worth it.
