### ISSUE TITLE
[Bug]: plotting with Figure and subplots no longer works?

### ISSUE THREAD

**Issue by cottrell** [matplotlib/matplotlib#25301]
### Bug summary

Has the api changed? Or is this a bug? Nothing coming up immediately in search results 
![image](https://user-images.githubusercontent.com/223276/220893226-e616d985-55e8-4521-855e-f023ca53f9ed.png)

### Code for reproduction

```python
from pylab import *
fig = Figure()
ax = fig.subplots(1, 1)
ax.plot(np.random.randn(10), np.random.randn(10))
fig.show()
```
```


### Actual outcome

from pylab import *
fig = Figure()
ax = fig.subplots(1, 1)
ax.plot(np.random.randn(10), np.random.randn(10))
fig.show()

### Expected outcome

fails to show plot, see error

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.7

### Matplotlib Backend

'module://matplotlib_inline.backend_inline'

### Python version

3.10.4

### Jupyter version

6.5.2

### Installation

pip

**Comment by cottrell** [comment]
Ok, this is some other library incepting me: `figure` not `Figure` ... error ends up being pretty confusing. Closing but leaving in case other folks land here it might be helpful.

**Comment by tacaswell** [comment]
Please see https://github.com/matplotlib/mpl-gui / https://matplotlib.org/mpl-gui for work on how to make this sort of thing simpler.

**Comment by tacaswell** [comment]
A version of this exception exists back to mpl 1.2.0 so I do not think this is a recent change in behavior.

**Comment by QuLogic** [comment]
This is the problem with using `from pylab import *`; you don't know where things come from, and you don't know that you accidentally typoed something similar. `pylab` is _very_ much discouraged at this point, as it mixes Matplotlib, NumPy, and who knows what else into the same namespace.

**Comment by cottrell** [comment]
> what do you think would be a more helpful error message?

Basically the error is fine I just didn't see the upper lower case difference.
