### ISSUE TITLE
CI: isort should check plot_types?

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#25303]
### Summary

https://github.com/matplotlib/matplotlib/blob/17db60b4de127347b319e60a7ae24224efbea09e/.pre-commit-config.yaml#L50 doesn't include `plot_types`.  Not sure if that was on purpose or not.  ping @dstansby, https://github.com/matplotlib/matplotlib/pull/25099

**Comment by dstansby** [comment]
This was not on purpose, I wasn't aware of this folder so thanks for pinging me! I'll get a PR in to add it.
