### ISSUE TITLE
[Bug]: Font difference in Ubuntu for latest matplotlib

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#25314]
### Bug summary

The latest matplotlib has slightly different font positioning on Ubuntu than the released 3.7

This was discovered by `ipympl`s tests here: https://github.com/matplotlib/ipympl/pull/514#issuecomment-1424456573

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib import __version__
import numpy as np

x = np.linspace(0,100,1000)
y = np.sin(x)


fig, ax = plt.subplots()
ax.plot(x,y)
plt.savefig(f"{__version__}.png")
```

### Actual outcome

Run first with `3.7.0`

 and then with nightly wheel
(`pip install --upgrade --pre --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple --extra-index-url https://pypi.org/simple matplotlib`

This gives two images where the labels of the positive y-ticks are shifted slightly.  Here's me toggling between the two generated images:

![Peek 2023-02-23 18-33](https://user-images.githubusercontent.com/10111092/221055423-101c3cac-6175-4cb1-a46b-c680ce5300b2.gif)

And here is the diff image from the ipympl tests

![ipympl-ipynb-cell-0-diff](https://user-images.githubusercontent.com/10111092/221055125-92a5f893-3e3b-4395-868e-be1e4ed7aa5f.png)

### Expected outcome

No differences

### Additional information

We also run latest tests on macos, and those did not fail, so this seems to be specific to ubuntu.

### Operating system

Ubuntu

### Matplotlib Version

latest

### Installation

None

**Comment by ianhi** [comment]
quick bump of this - I'm pretty sure this should be considered a bug but would love to hear from someone else

**Comment by jklymak** [comment]
Are you locking your freetype between the two tests?  We have a lot of image tests like this that would have broken if this were a change in Matplotlib.

**Comment by tacaswell** [comment]
If installing from the wheels we should have pinned freetype.

**Comment by QuLogic** [comment]
AFAICT, ipympl tests install matplotlib from conda-forge. This is built against conda-forge's FreeType and thus text rendering is dependent on which one conda-forge has.

If you want a fixed version, then you need to install our wheels, or install from the `conda-forge/label/testing` label, like we do in Cartopy https://github.com/SciTools/cartopy/blob/main/environment.yml#L18
