### ISSUE TITLE
axis.get_offset_text() doesn't work properly

### ISSUE THREAD

**Issue by wanghao6736** [matplotlib/matplotlib#25357]
https://github.com/matplotlib/matplotlib/blob/d6dd1b79142e4e2483244c25ff1e3ddb664722d3/lib/matplotlib/axis.py#L1398-L1400
matplotlib version: 3.6.3
python version: 3.10.6
I am trying to get the offset of the y axis, and my code is like:
```
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot()
fig.subplots_adjust(top=0.85)

# data
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)*1e-5

# get offset text
ax.plot(x, y, 'o')
ax.xaxis.get_major_formatter().set_useOffset(True)
offset = ax.yaxis.get_offset_text()
print(offset) # expected output: Text(0, 0.5, '1e-5'), actual output: Text(0, 0.5, '')

plt.show()
```
the output picture indicates that the offset of y axis is '1e-5', but the get_offset_text() function gets ''.
then I try to change the text style of the offset, so i add a few lines above `plt.show()`:
```
# set offset style
offset.set_backgroundcolor('y')
offset.set_color('r') # change the offset color
```
it turns out just fine, which means, I think, the get_offset_text() does return the offset object, but the offset text is not included, and that makes me confused.
the output pictures are listed below:
before changing style:
![image](https://user-images.githubusercontent.com/44387878/222108339-014e103f-5679-453d-a49a-716a25f320ba.png)

after changing style:
![image](https://user-images.githubusercontent.com/44387878/222108007-f64fc1fa-7568-421d-85d1-3a562cdc15f2.png)

**Comment by oscargus** [comment]
The offset-text is only created when drawing, so if you do `ax.figure.draw_without_rendering()` before getting the text it will be OK.

(One can also see that the y-location of the text is not correct in your current output.)

**Comment by wanghao6736** [comment]
> The offset-text is only created when drawing, so if you do `ax.figure.draw_without_rendering()` before getting the text it will be OK.
> 
> (One can also see that the y-location of the text is not correct in your current output.)

thanks a lot, I tried as you said, and it worked
