### ISSUE TITLE
[Bug]: Inconsistent size/padx for spacers in NavigationToolbar2Tk._rescale and _Spacer

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25365]
### Bug summary

NavigationToolbar2Tk._Spacer sets the spacer size to 18p and the padx to 3p, but _rescale sets them to 22p and 4p respectively.

### Code for reproduction

```python
# in ipython, tk backend
from pylab import *

plot(); show()

# In theory this should be triggered upon moving the window
# to a monitor with a different dpi, which I don't have,
# but one can also call _rescale manually
gcf().canvas.toolbar._rescale()
```

### Actual outcome

The spacer becomes larger and with more space around it.

### Expected outcome

No change to spacer size(?)

### Additional information

I stumbled upon this while considering whether we could entirely get rid of _Spacer() and just add a RIDGE Frame instead and rely on _rescale() to set the size of the spacer as needed; the idea being to avoid the call to a private method in the https://matplotlib.org/stable/gallery/user_interfaces/mplcvd.html example while also not adding a new method for adding spacers.

### Matplotlib Version

3.7

### Matplotlib Backend

tkagg

### Python version

3.11

### Installation

git checkout

**Comment by QuLogic** [comment]
I think 18p is the correct one, but it's strange that the 22p line was added later. Maybe something happened in between a rebase.

**Comment by QuLogic** [comment]
Or actually, I see that it was you that pointed out the images were too big https://github.com/matplotlib/matplotlib/pull/19167#issuecomment-837486377, and both changes were in that PR, so I probably just accidentally only changed the one place.
