### ISSUE TITLE
fill_between and a y log axis

### ISSUE THREAD

**Issue by rubenvb** [matplotlib/matplotlib#2536]
When using fill_between and a log-scaled y axis, fill_between fails to do as its name says. An example I plucked [off the internet](http://matplotlib.1069221.n5.nabble.com/strange-behaviour-with-fill-between-td38670.html) while searching for this issue:

    import matplotlib.pyplot as plt
    import numpy as np

    #values to plot
    x = np.linspace( 1, 10, num=100 )
    y = np.exp( -x**2 )
    y[50:] = 0
    yerr = y* np.random.rand(100)

    #figure
    fig = plt.figure()

    ax1 = fig.add_subplot(121)  #first axes: linear
    ax1.errorbar( x,y,yerr, c='r' )
    ax1.fill_between( x,y-yerr,y+yerr, color='b', alpha=0.4 )

    ax2 = fig.add_subplot(122)  #second axes: logarithmic
    ax2.errorbar( x,y,yerr, c='r' )
    ax2.fill_between( x,y-yerr,y+yerr, color='b', alpha=0.4 )
    ax2.set_xscale( "log" )
    ax2.set_yscale( "log" )

    plt.show()

Notice the diagonal line connecting the last and first data points.
But this also shows when filling between two curves, where the filling stops on the straight line connecting the first and last data point, instead of further down to the next curve (or plain 0's).

A workaround was also presented in the same place:

    positive = y - yerr > 0
    ax2.fill_between( x,y-yerr,y+yerr, where=positive, color='b', alpha=0.4)

but this is suboptimal as the filling should Just Work ®.

**Comment by tacaswell** [comment]
This seems to have been fixed (at least on master):

![so](https://cloud.githubusercontent.com/assets/199813/6094402/a004c14a-aef6-11e4-9cf9-7983889f14de.png)
