### ISSUE TITLE
[Bug]: ConnectionAbortedError: [WinError 10053] failed to send plot to http://127.0.0.1:63342

### ISSUE THREAD

**Issue by SkyChang121** [matplotlib/matplotlib#25362]
### Bug summary

When using matplotlib to paint on pycharm, an error occurs if the image is large. The first is to fail to send plot to http://127.0.0.1:63342. Then [Bug]: ConnectionAbortedError: [WinError 10053] stops the local file. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import seaborn as sns
CorrData=pd.DataFrame(Data[:,0:99])

a=CorrData.corr()
data_shape = a.shape
data_rows = data_shape[0]


plt.subplots(figsize=(data_rows+1, data_rows+1))
sns.heatmap(a, annot=True, vmax=1, square=True, cmap="Blues")
plt.show()
```

### Actual outcome

Error: failed to send plot to http://127.0.0.1:63342
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pycharm_display\datalore\display\display_.py", line 60, in _send_display_message
    urlopen(url, buffer)
  File "C:\Python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "C:\Python\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Python\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Python\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] 

### Expected outcome

we should actually get a simple correlation analysis diagram

### Additional information

Possible cause
1.The image generated by matplotlib is too large to pass SciView's display mechanism (I don't understand how it displays images). 
2.pycharm problem, or related to the asynchronous communication library asyncio. 
A solution
The problem isn't with matplotlib, because we know it can draw bigger pictures. One option is not to use plt.show. Instead, save the file directly and open it.

import seaborn as sns
import matplotlib.pyplot as plt
import os
CorrData=pd.DataFrame(Data[:,0:99])

a=CorrData.corr()
data_shape = a.shape
data_rows = data_shape[0]

plt.subplots(figsize=(data_rows+1, data_rows+1))
sns.heatmap(a, annot=True, vmax=1, square=True, cmap="Blues")
plt.savefig(file_name.jpg, bbox_inches='tight')
os.system(f'start {file_name}')

### Matplotlib Version

3.3.2

### Matplotlib Backend

module://backend_interagg

### Python version

Python 3.7.4

### Installation

pip

**Comment by QuLogic** [comment]
This is an error in PyCharm's backend; you will need to report an issue to them.

**Comment by tacaswell** [comment]
I am going to close this as I do not think there is anything we can do in Matplotlib, these issues should be reported to pycharm and SciView.

**Comment by SkyChang121** [comment]
> 



> I am going to close this as I do not think there is anything we can do in Matplotlib, these issues should be reported to pycharm and SciView.

OK. thank you
