### ISSUE TITLE
[Bug]: RGBA in [0, 255] not work in matshow and imshow

### ISSUE THREAD

**Issue by Syuukakou** [matplotlib/matplotlib#25374]
### Bug summary

RGBA in [0, 255] like `[128, 128, 128, 1.0]` not work in matshow and imshow, only RGBA in [0, 1] like `[0.5, 0.5, 0.5, 1.0]` worked

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(
    ncols=2, nrows=2,
    figsize=(10, 10)
)
mat0 = np.array([
    # [[128/255, 128/255, 128/255, 1]]
    [[128, 128, 128, 1]]
])
mat1 = np.array([
    [[128/255, 128/255, 128/255, 1]]
    # [[128, 128, 128, 1]]
])
im0 = np.array([
    # [[128/255, 128/255, 128/255, 1]]
    [[128, 128, 128, 1]]
])
im1 = np.array([
    [[128/255, 128/255, 128/255, 1]]
    # [[128, 128, 128, 1]]
])
axes[0, 0].matshow(mat0, origin='lower')
axes[0, 0].set_title('RGBA in [0, 255] (matshow)')
axes[0, 1].matshow(mat1, origin='lower')
axes[0, 1].set_title('RGBA in [0, 1] (matshow)')
axes[1, 0].imshow(im0, origin='lower')
axes[1, 0].set_title('RGBA in [0, 255] (imshow)')
axes[1, 1].imshow(im1, origin='lower')
axes[1, 1].set_title('RGBA in [0, 1] (imshow)')

plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/32434879/222741594-a1ef88fc-36fd-4641-a902-e00f19e597ff.png)

### Expected outcome

Only RGBA in [0, 1] worked in matshow and imshow.
it may be a bug.

### Matplotlib Version

3.7.0

### Python version

Python 3.11.2

### Installation

pip

**Comment by rcomer** [comment]
Hi @Syuukakou, I think the difference is that for your integer case you need to set the alpha also in the range [0-255].  I tried changing your example using

```python
mat0 = np.array([
    # [[128/255, 128/255, 128/255, 1]]
    [[128, 128, 128, 255]]
])
```
and this made it consistent with the float case.

**Comment by jklymak** [comment]
I'll close this.  I think it's pretty clear from the documentation that this is the convention.
