### ISSUE TITLE
[Doc]: Unclear Documentation when setting up dev environment through GitHub Codespaces: Issues with strict branch protocol and virtual environment creation

### ISSUE THREAD

**Issue by Higgs32584** [matplotlib/matplotlib#25398]
### Documentation Link

https://matplotlib.org/stable/devel/development_setup.html

### Problem

Close this if the deviation from instructions is insufficient to warrant a change, or if this kind of documentation is not in the scope of matplotlib documentation.

- To be fair, I don't know if this added documentation is necessary. Still, setting up the dev environment through GitHub codespaces, I ran into a few issues that I needed more documentation.
- I don't know if one can assume that only pro developers use GitHub codespaces, but the way they advertise it as a quick startup environment, unlike AWS, for instance.
- This documentation is unclear, mainly because there are a few points of differences between the way that one begins development through their own machine rather than through codespaces.

1. Github codespaces force pretty strict branch protocol, so if you did:

*git clone https://github.com/EXAMPLE_USERNAME/matplotlib*
*cd matplotlib*

You would be unable to commit to any branch on your forked repo. MAYBE this has more to do with documentation under GitHub, and close this if you want, but it was enough to trip me up significantly as a new Open Source developer.

I created a blank codespace and did the commands above, as described in the development setup, only to receive an error of 403 whenever I tried to push to my forked repo. I thought the 403 error was enforced by matplotlib, and not by github, which was why I was so confused for a long time, and did not check the github docs

 Instead, one has to navigate to the forked repo on GitHub, create a branch, and then click on code, codespaces, and then add the codespace, so you do not have to do the commands up above, just immediately start out in the branch.

2. Secondly, creating a virtual environment on Github is forbidden as well, and the inability to do so might also trip up a new developer.

There are technically fewer steps to take when doing github codespaces, but following the instructions described in the dev setup tripped me up a lot until I figured it out.

### Suggested improvement

I suggest adding a section describing setting up a development environment using GitHub codespace. Since we want to ensure easy development setup, including how to set up a dev environment through GitHub codespace should be included in the documentation. As someone new to Open source, although I have a few years of SWE experience in college, I had trouble setting up the initial dev environment with the documentation provided.

**Comment by tacaswell** [comment]
I think adding a (sub)-section to developing as "Do it in code spaces" (and renaming the one we have to "Do it on your own machine" or similar) would be a very welcome addition to our development docs!


----


The issues with permission to push back to branches is all github (but it sort of makes sense because I suspect when you launch off of a given branch they check it out for you and then insert a secret that lets you push back to ONLY that branch in the container (other wise you are leaking secrets that may be too powerful!)).  While I think we could reasonably say "that is a GH docs problem", I think we should document the easy path through.

----

How do they prevent creating virtual environments if they give you access to a python version and a writable file system?  I guess they could have burned out `venv` from the standard library....

**Comment by ksunden** [comment]
I've not used code spaces at all, so not fully sure on what their "standard" workflow is, but if they are a bit more transitive/set up to work on only a single branch per instance, then perhaps venvs are less necessary there. While installing on system python is sometimes problematic, mostly that is for longer term reasons, and if a given code space is only used for a single PR, probably not as important.

Perhaps doing `pip install --user -r requirements/dev/dev-requirements.txt` is a pragmatic intermediate in such an environment between installing directly on system python and using venvs. (As much as I think venvs are the better solution for local dev)

**Comment by jklymak** [comment]
@Higgs32584 any notes you can take for working in code spaces would probably be welcome addition to our docs.  I would guess none of the devs use codespaces.  How does it work for testing when you need to popup interactive windows routinely to test Matplotlib?

**Comment by melissawm** [comment]
Let me ping @craiglpeters and @jungaretti and share https://github.com/numpy/numpy/pull/22718 which might be similar to this.

**Comment by Higgs32584** [comment]
@jklymak so pretty much I just test with running python in the interactive window. Running to output the graphs, as well as running the pre-commit tests are not too different from the instructions.

**Comment by Higgs32584** [comment]
Correction: the venv works now, but I do not know why it wasn't working before

**Comment by melissawm** [comment]
Yup that's how I do it too! Maybe we can add docs for this?

**Comment by Higgs32584** [comment]
@melissawm I think we should; I can write up a page on it or so.
