### ISSUE TITLE
[Doc]: Not possible to see upcoming what's new etc?

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#25445]
### Documentation Link

https://matplotlib.org/devdocs/users/release_notes.html

### Problem

It used to be possible to see the upcoming what's new and API change notes in the doc builds (I think in "devdocs", but also in test doc builds).

Useful to see how your notes render.

### Suggested improvement

Get that back.

**Comment by timhoffm** [comment]
Closed by #25235
