### ISSUE TITLE
[Doc]: possible typo in example: "Using histograms to plot a cumulative distribution"

### ISSUE THREAD

**Issue by terilias** [matplotlib/matplotlib#25458]
### Documentation Link

https://matplotlib.org/devdocs/gallery/statistics/histogram_cumulative.html

### Problem

I found that in this example, many times the word "normed" is used to refer in a parameter of the hist function. But I am looking for this parameter in the [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html) and can't find it. So, I  thought that maybe the correct parameter is "cumulative" or "density". But, of course maybe I have misunderstood something...

### Suggested improvement

Use a word that refer to a parameter of the hist function.

**Comment by rcomer** [comment]
Thanks @terilias, you are right.  The _normed_ parameter was renamed to _density_ at v3.3.
https://matplotlib.org/devdocs/api/prev_api_changes/api_changes_3.3.0.html

**Comment by ColeBurch** [comment]
Hello @rcomer, I believe that I have fixed this issue and have opened a PR, #25461. This is my first ever PR so apologies if I have not done everything correctly.
