### ISSUE TITLE
[ENH]: distinguish between left and right yaxis with respect to interactivity

### ISSUE THREAD

**Issue by brobr** [matplotlib/matplotlib#25466]
### Problem

To implement scale change on an y-axis I use the axis itself as a button via `ax.yaxis.set_picker(true)`.
Now, unexpectantly, it turns out that both yaxis's are responsive (and not only the left yaxis that seems the active one because of the labels and ticks). Also there seems to be no handle for distinguishing between the left or right yaxis.

This leads to unexpected scale-changes, that is unintended click-effects when nearby the right yaxis other responsive elements are placed but the yaxis happens to catch the mousepress intended for any of those elements.

For a consistent user-interface experience in this case, the duplicated yaxis interactivity is not helpful. Alternatives, say the y-label itself as button or the built-in scale-change functionality are not applicable (for reasons how the figure is set up ).

      import numpy as np
      import matplotlib.pyplot as plt
      from matplotlib.axis import YAxis,XAxis

      def onpick(pevent): #PickEvent
            print(pevent.artist)
           if isinstance(pevent.artist,YAxis):
                  print(pevent.artist.majorTicks)
                  print(pevent.artist.label)
                  print(pevent.artist.get_majorticklabels())
                  print(pevent.artist.get_ticks_position())   # only gives 'left', the rcparam setting; not 
                  print(pevent.artist.axes.get_ybound())
                  pevent.artist.axes.set_ylabel('y clicked')
          if isinstance(pevent.artist,XAxis):
                  pevent.artist.axes.set_ylabel('x clicked')
          fig.canvas.draw_idle()

       x = np.linspace(0, 2, 100)  # Sample data.

      # Note that even in the OO-style, we use `.pyplot.figure` to create the Figure.
      fig, ax = plt.subplots(figsize=(5, 2.7), layout='constrained')
      ax.plot(x, x, label='linear')  # Plot some data on the axes.
      ax.plot(x, x**2, label='quadratic')  # Plot more data on the axes...
      ax.plot(x, x**3, label='cubic')  # ... and some more.
      ax.set_xlabel('x label')  # Add an x-label to the axes.
      ax.set_ylabel('y label')  # Add a y-label to the axes.
      #ax.set_title("Simple Plot")  # Add a title to the axes.
      ax.yaxis.set_picker(True)
      ax.xaxis.set_picker(True)
      fig.canvas.mpl_connect('pick_event', onpick)
      ax.legend()  # Add a legend.

      plt.show()

Is there a way to check which of the two yaxis's has been clicked? I looked around but could not find anything. If not, maybe below suggestion might be valid.

### Proposed solution

The placement of the ticks and labels on the left or the right axis is governed by rcparams like `ytick.left: True`.
  
Maybe a similar approach is easy to implement that could help to define which yaxis is reponsive (i.e. gets the picker-activity), say with a rcparam `yaxis.picker.left: True; yaxis.picker.right: False; ` in the matplotlibrc.

For the xaxis comparable additions `xaxis.picker.top: True; xaxis.picker.bottom: False; ` would be relevant too.

**Comment by anntzer** [comment]
You may want to use picking on spines (https://matplotlib.org/stable/gallery/spines/spines.html) instead.

**Comment by brobr** [comment]
Thanks, I did look into that, trying to use the spines, but did not get it to work with my own figure; maybe I am doing something wrong? Below the adapted demo script.

    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib.axis import YAxis,XAxis
    from matplotlib.spines import Spine
    from matplotlib.text import Text

    def onpick(pevent): #PickEvent
        print(pevent.artist)
        if isinstance(pevent.artist,Spine):
            print(pevent.artist)
            pevent.artist.axes.set_ylabel('spine clicked')
        if isinstance(pevent.artist,YAxis):
            print(pevent.artist.majorTicks)
            print(pevent.artist.label)
            print(pevent.artist.get_ticks_position())
            print(pevent.artist.axes.get_ybound())
            pevent.artist.axes.set_ylabel('y clicked')
        if isinstance(pevent.artist,XAxis):
            pevent.artist.axes.set_ylabel('x clicked')
        if isinstance(pevent.artist,Text):
            ax.set_ylabel('y reset')
        fig.canvas.draw_idle()


    
    x = np.linspace(0, 2, 100)  # Sample data.

    fig, ax = plt.subplots(figsize=(5, 2.7), layout='constrained')
    ax.plot(x, x, label='linear') 
    ax.plot(x, x**2, label='quadratic')
    ax.plot(x, x**3, label='cubic')
    ax.set_xlabel('x label')
    ax.set_ylabel('y label')
    ax.xaxis.label.set_picker(True)
    ax.spines.left.set_picker(15) # set interactivity for a default axis pickradius
    ax.spines.right.set_visible(False)
    ax.spines.top.set_visible(False)
    #ax.yaxis.set_picker(True)
    #ax.xaxis.set_picker(True) # does not seem to change interactivity spines.left.picker
    fig.canvas.mpl_connect('pick_event', onpick)
    leg = ax.legend()  # Add a legend.
    leg.set_draggable(True) # to check more click events
    print(
        f"ax.spines.left.pickable(): {ax.spines.left.pickable()}, {ax.spines.left.get_picker()}\n"
        f"ax.spines.left.zorder: {ax.spines.left.zorder}\n"
        f"ax.yaxis.zorder: {ax.yaxis.zorder}\n"
        f"legend.zorder: {leg.zorder}\n"
    )
    plt.show()

I never register a pickevent related to `ax.spines.left`

**Comment by anntzer** [comment]
Indeed, you are correct.  Investigating this a bit more, there's already an issue for the pickability of spines at #18879, so I'll close this one as a duplicated; feel free to comment on that other issue.
