### ISSUE TITLE
matplotlib.pyplot.imshow(img, cmap='gray) displays a white image as black

### ISSUE THREAD

**Issue by whroberts1411** [matplotlib/matplotlib#25468]
Software versions:
Python : 3.9.16,  JupyterLab : 3.5.3,  Matplotlib : 3.7.0,  Numpy : 1.21.5
The following code was run in a Jupyter Notebook in 3 separate cells :

```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

img = np.zeros((20, 20))
plt.imshow(img, cmap='gray')           # displays an all-black image as expected

img2 = img + 255
plt.imshow(img2, cmap='gray')        # displays an all-black image - should be all white?

img2[2][1] = 0                                  # change any pixel to black
plt.imshow(img2, cmap='gray')       # now displays an all white image, with a single black pixel
```

Is this a bug, or is it the intended behaviour?

**Comment by rcomer** [comment]
This is the documented behaviour.
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib.axes.Axes.imshow

> The values are mapped to colors using normalization and a colormap.

> By default, a linear scaling is used, mapping the lowest value to 0 and the highest to 1.
