### ISSUE TITLE
Candlestick shadow is drawn after candlestick body

### ISSUE THREAD

**Issue by c0indev3l** [matplotlib/matplotlib#2546]
Hello,

in this example
http://matplotlib.org/examples/pylab_examples/finance_demo.html
there is a little display bug.
Candlestick shadows (vertical segment) should be drawn before candlestick body.
see http://en.wikipedia.org/wiki/Candlestick_chart

Kind regards

**Comment by lifetime42** [comment]
thank you very much for your function jdgd1. exactly what i was looking for. it didnt make it into the master branch? how come?

**Comment by efiring** [comment]
#3016 needed some revision, and seems to have been closed inadvertently, based on the last comment in it.  We still need someone to maintain the finance module. I don't think we want to lose the apparent progress in that PR if we can avoid it.

**Comment by lifetime42** [comment]
Thank you for the link to the code discussion, I ended up altering the finance.py according to jdgd1s input; I dont use the dark/light scheme but a simple replacement of the edgecolor does work wonderfully with =None in constructor so the rest of the code can stay the same. The real issue here was the zorder and the vlines. Now the charts looks just as I wanted.

**Comment by jdgd1** [comment]
@lifetkme42 Glad to hear the code worked for you. Let me know if any issues arise. 

@efiring I will take a look at the code again today and try to clean it up a little. As I mentioned in the past I'm happy to help, but not as sure I have the time to responsible for maintaining it.

**Comment by tacaswell** [comment]
@jdgd1 If you have _any_ time or expertise it will be an improvement.

**Comment by jdgd1** [comment]
@tacaswell ok, I will help as much as I can. Let me know where to start.

**Comment by tacaswell** [comment]
@jdgd1 For starters, can you review #5160 ?

@ssanderson is a dev at Quantopian who has expressed (very very) lose interest in also helping with the finance module, it is probably worth getting in touch with him.

A survey of what is in the finance module would be good to do.  Are the functions we have actually useful to a 'typical' finance type anymore?  Are there obvious functions we are missing?  A major struggle with that package right now is that none of the core-devs _do_ finance so we lack the domain expertise to answer these questions.

Related, I don't think we have any prose documentation for the finance module, turning some of the examples in to more proper tutorials might be worth doing.

There has been some discussion of splitting the finance module out of core mpl (into a `mpl-finance` repo in the matplotlib gh org).  If we did this, then it could pick up a pandas dependency which would definitely help increase the relevance to current finance users.  This may be something that the pandas folks would be willing to help with.

I know this is a daunting list and by no means expect you to tackle all of it, but just trying to make the point that this is a domain where there is significant opportunity to have a major impact.

**Comment by jdgd1** [comment]
@tacaswell wow, you weren't kidding - that is quite the list. Will start with checking out #5160 and then trying to get in touch with @ssanderson. I've actually been spending a good bit of time lately working between Quantopian/zipline, so that could work out well.

Post those two things will start digging into the finance module and making my own list of what I think can go vs. what's missing.

**Comment by ssanderson** [comment]
@jdgd1, @tacaswell hello!

**Comment by ssanderson** [comment]
(@tacaswell I just realized I've owed you an email reply for like 3 months...sorry about that)

**Comment by tacaswell** [comment]
@ssanderson Don't worry, that still leaves me way in the red in terms of net-emails-owed.

**Comment by ssanderson** [comment]
A couple notes on the discussion here:

- I/we am/are interested in helping out with mpl.finance, but I'm not sure anyone has the bandwidth to make a sustained contribution right now.  Zipline is basically being completely rewritten from the ground up on 2 different fronts right now, so we're stretched a bit thin.
- I'm probably not any more qualified than the MPL devs to comment on things like how to display candlesticks properly, but I **can** at least help provide real-world user stories/issues from our user base.  I suspect that our [forums](https://www.quantopian.com/posts) would also be an interesting place to ask for feedback/comments on this stuff.
- Most of the interesting work we've done in financial visualization at Quantopian has been building visualizations for analyzing portfolio performance.  @twiecki and co have been working on [pyfolio](https://github.com/quantopian/pyfolio), which is built primarily on top of pandas, matplotlib, and seaborn.  I'm not sure what the right relationship would be between that project and `mpl.finance`.

**Comment by lifetime42** [comment]
I only picked up python recently and I just started using matplotlib, but I can tell you these charts are looking quite nice and easy to handle (I used jfreechart before)

Things the finance modul could use are eg.
-hollow/filled candlesticks (tc2000 style) adding additional information to one candle
-easy subchart addition right into the chart itself or below for indicators
-easy access to daw into the chart itself eg. support/resistance lines etc

to make @jdgd1 list even longer ;-)

**Comment by femtotrader** [comment]
@tacaswell @ssanderson +1 for `mpl-finance` as a separate repository with Numpy/Pandas as dependency.

**Comment by femtotrader** [comment]
Pinging some people from PyData / Pandas-DataReader and others who might be interested in a Matplotlib / Numpy / Pandas / Finance plotting lib @davidastephens @bashtage @hayd @jorisvandenbossche

**Comment by femtotrader** [comment]
The scope of such a lib could be (or not) to be able to display "realtime" plot. PyQtGraph is nice for realtime plot so pinging also @campagnola

See

http://www.pyqtgraph.org/
http://stackoverflow.com/questions/24670856/the-fastest-way-to-add-a-new-data-bar-with-pyqtgraph

**Comment by genliu777** [comment]
so far i use t`hecandlestick2_ohlc`, and come across the same shadow line through the real body!  this question has been put here almost 3 years and not solved!!

**Comment by rkahun** [comment]
There is a quick resolving, use z-order. It works without any side effect for me.
(By default lines have 2 and patches have 1 as z_order.
 Of course, color of edges and shadows has not changed)

```python
shadows, bodies = candlestick2_ohlc(ax, .... )
shadows.set_zorder(0)
bodies.set_zorder(1)
```
