### ISSUE TITLE
[ENH]: please provide support for latest `freetype` 2.13.0

### ISSUE THREAD

**Issue by kloczek** [matplotlib/matplotlib#25471]
### Problem

Looks like latest version of the `freetype` which is supported by `matplotlib` is 2.6.1.
This version has been released **+seven** yerars ago.
In fedora it is possible to find patch which adds support for `freetype` 2.12.1.
https://src.fedoraproject.org/rpms/python-matplotlib/raw/rawhide/f/0003-Set-FreeType-version-to-2.12.1-and-update-tolerances.patch

### Proposed solution
it would be really nice if it will be possible to build latest `matplotlib` against latest DSO `freetype` 2.13.0.

Doable? 🤔

**Comment by tacaswell** [comment]
We believe it is possible to build against system freetype (see https://matplotlib.org/stable/devel/dependencies.html#c-libraries) and via the fedora reubilds have confirmed that Matplotlib does compile against freetype 2.13.0.

The version we pin in our build process is for two reasons:

 1. to have a fixed version for our image comparison tests
 2. to make it easier for new contributors to get up and running

Downstream packagers are free (and do!) build Matplotlib against what ever version of freetype they want to.

There is no action to be taken here and we are tracking efforts to update the version of freetype we use for testing else where.

If you have an example of Matplotlib failing to build with a newer version of freetype please open a new issue with the build failure.

**Comment by kloczek** [comment]
So why not commit that patch into `matplotlib` tree?

**Comment by oscargus** [comment]
It is supported in the tree. Just follow the instructions in the link provided above.
