### ISSUE TITLE
[MNT]: artifact redirector not redirecting

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#25488]
### Summary

https://github.com/matplotlib/matplotlib/actions/runs/4449806502/jobs/7814485660

Fails with a pretty inscrutable message 

```
Error: Cannot read properties of undefined (reading 'length')
```

**Comment by rcomer** [comment]
The same error is show in Cartopy, so I have opened https://github.com/larsoner/circleci-artifacts-redirector-action/issues/38.

**Comment by rcomer** [comment]
Closed by https://github.com/larsoner/circleci-artifacts-redirector-action/pull/39
