### ISSUE TITLE
[Doc]: users/explain bare index looks bad

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#25493]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/index.html

### Problem

This is very bare bones, and could be substantially improved

- figures?
- A bit of introduction to what the section is meant to do.
- visual elements for the different sections?

**Comment by jklymak** [comment]
@story645 For sure, https://matplotlib.org/devdocs/users/index.html and https://matplotlib.org/devdocs/users/explain/index.html should be fixed. 

#24493 actually had a bunch of reasonable ideas. I think we should not over-stress about it, and just choose one and go with it.  Nothing is perfect, and we will never get 100% consensus on these things, but most of the ideas in there were better than the status quo.  If you wanted to pick one that was relatively comprehensive, we can try it for a while and tweak later.  We should get something in soonish so we can live with it for a while before the release (Aug?)

FWIW, I like the idea of having graphics on these pages.  There are lots of thumbnails already in the docs that we can use to visually guide the reader.

**Comment by rcomer** [comment]
Was this addressed by #26110?

**Comment by jklymak** [comment]
Yep!
