### ISSUE TITLE
Using CenterNorm in imshow with a given halfrange does display data when not displaying the colorbar

### ISSUE THREAD

**Issue by TomFD** [matplotlib/matplotlib#25523]
### Problem description

A simple plot is empty under the following cirumstances:

Use the standard example:

```
import matplotlib.pyplot as plt
from matplotlib.colors import CenteredNorm
import numpy as np

data = np.random.random((100, 100))

fig, ax = plt.subplots()
im = ax.imshow(data, norm=CenteredNorm(halfrange=0.2))
fig.colorbar(im)

plt.show(block=True)
```

If you now delete the line `fig.colorbar(im)`, the data is not shown (white content). If you then remove `halfrange=0.2` the data appears again. This is unexpected as one needs to see the data even by giving a certain halfrange and without the colorbar.

### Standard (expected) outcome

![image](https://user-images.githubusercontent.com/44144239/226737117-741eff5c-408d-46fa-a499-68661a979470.png)

## Outcome without colorbar line
![image](https://user-images.githubusercontent.com/44144239/226736997-9300a979-8aba-4faf-a1e2-aa60dbeb2537.png)

### System

Microsoft Windows [Version 10.0.25300.1000]
VS Code 1.76.2
Python 3.10.8

Tested as python script and Jupyter notebook
@jpmattern

**Comment by jklymak** [comment]
What version of Matplotlib?  I can't produce this on main, nor on 3.7.0, 3.7.1

**Comment by TomFD** [comment]
That was with 3.6.2 .. sorry I did not try the latest. Now I remember why after updating to 3.7.1 .. conflicts with pillow, need reinstallation etc. now I'm in the package hell again and give up for today. I'll try it later.
Anyway, thanks and hopefully this "easy" update resolves it.

**Comment by ksunden** [comment]
https://github.com/matplotlib/matplotlib/commit/84def85c848a172afab987298eb402bd39aceeaa

This behavior was changed to be precisely what you expected in #24132

Therefore I'm going to close this issue. Hope you figure out your package conflicts.
