### ISSUE TITLE
[Doc]: `TABLEAU_COLORS` `XKCD_COLORS` etc undocumented

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#25521]
### Documentation Link

https://matplotlib.org/devdocs/api/colors_api.html#module-matplotlib.colors

### Problem

The exported color arrays 
https://github.com/matplotlib/matplotlib/blob/31d83a869ee4edf5eeec80a0aea31ba46e7c6e79/lib/matplotlib/colors.py#L57

are not documented in: https://matplotlib.org/devdocs/api/colors_api.html#module-matplotlib.colors

I've always considered considered importing these directly to a stable part of the API, something supported by the usage in the examples: https://github.com/matplotlib/matplotlib/blob/31d83a869ee4edf5eeec80a0aea31ba46e7c6e79/galleries/examples/color/named_colors.py#L107

**Comment by timhoffm** [comment]
Agreed, that they are public (otherwise we should have used a leading underscore).

The fix is to manually add `.. py:data::` for these in https://github.com/matplotlib/matplotlib/blob/main/doc/api/colors_api.rst
