### ISSUE TITLE
[Bug]: Autoscale not working for matplotlib.collections.PathCollection

### ISSUE THREAD

**Issue by morales-gregorio** [matplotlib/matplotlib#25540]
### Bug summary

The autoscale limits do not work when using `mpl.collections.PathCollection`

### Code for reproduction

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

fig, axs = plt.subplots(1, 3, figsize=(6, 2))

# One red triangle as a simple path
# In my use case these are parsed from vector graphics
my_path = mpl.path.Path(np.array([[7, 7], [7, 15], [15, 15], [7, 7]]))

# Add same path to all axes
for ax in axs:
    collection = mpl.collections.PathCollection([my_path],
                                                edgecolors='k', 
                                                facecolors='r')
    ax.add_artist(collection)

# Use autoscale in first axes
ax = axs[0]
ax.autoscale()
ax.set_title('ax.autoscale()')

# Use margin in second axes
ax = axs[1]
ax.margins(0.1)
ax.set_title('ax.margins(0.1)')

# Manually set limits in third axes
ax = axs[2]
ax.set_xlim(0, 20)
ax.set_ylim(0, 20)
ax.set_title('ax.set_xlim(0, 20)\nax.set_ylim(0, 20)')

plt.savefig('PathCollection_autoscale_bug.png', facecolor='w', bbox_inches='tight')
```

### Actual outcome

![PathCollection_autoscale_bug](https://user-images.githubusercontent.com/43403140/227563080-68ab409b-a501-4708-8dfb-0d66b1d82da7.png)

### Expected outcome

The outcome of autoscaling should show the path(s) and automatically update the x and y limits so that the paths are not out of view. 

### Operating system

Ubuntu

### Matplotlib Version

3.7.1.

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.11.0

### Installation

None

**Comment by jklymak** [comment]
Anything you need to use `add_artist` for does not participate in an autolim.  This is well understood, and maybe best tracked at #25139, so I'll close as duplicate.

**Comment by WeatherGod** [comment]
Also, you can use `ax.add_collection(collection, autolim=True)`
