### ISSUE TITLE
[Bug]: imshow() truncates large arrays

### ISSUE THREAD

**Issue by rcasperson** [matplotlib/matplotlib#25561]
### Bug summary

2D arrays with more than about 8.000.000 columns are truncated on the right side. 

### Code for reproduction

```python
import numpy as np
from matplotlib import pyplot

for length in range(6000000,10000000,500000):
    s = .5 * np.sin(np.linspace(0,6*np.pi,length))
    pyplot.plot(s)
    pyplot.imshow(s.reshape((1,len(s))),aspect='auto',cmap='seismic')
    pyplot.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/20534033/227931365-bcabad57-5ec4-4591-8980-320da4740fea.png)

Image truncated on the right if length > 8000000.

### Expected outcome

![image](https://user-images.githubusercontent.com/20534033/227930731-4b3744d2-05d4-4a9e-9f0c-9beb4b5872f3.png)

Expected same outcome independent of length.

### Operating system

Windows 10

### Matplotlib Version

3.1.0

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.7.3

### Installation

pip

**Comment by rcomer** [comment]
I just tried this with Matplotlib v3.6.3, and got the following
```
[site-packages-path]/matplotlib/image.py:175: UserWarning: Data with more than 2**23 columns cannot be accurately displayed. Downsampling to less than 2**23 columns before displaying. To remove this warning, manually downsample your data.
  warnings.warn(msg.format(n='2**23 columns'))
```
It looks like the warning has been added since v3.1.

**Comment by rcomer** [comment]
From the code comment, this seems to be a limitation of the AGG renderer, so I suspect there is nothing we can do about this within Matplotlib
https://github.com/matplotlib/matplotlib/blob/676773859604eddb3bf7ac782a6af0cf978162b6/lib/matplotlib/image.py#L168-L173
