### ISSUE TITLE
[Bug]: imshow interpolation='none' ignored when using savefig() to PDF format

### ISSUE THREAD

**Issue by larrybradley** [matplotlib/matplotlib#25575]
### Bug summary

When using `imshow` with `interpolation='none'` and then saving the figure to PDF using `savefig()`, the PDF file output does not match the screen/notebook output.  It appears that interpolation is still being applied to the PDF output.  This bug is manifested only with 'none' interpolation with PDF filetype output.  Setting `interpolation` to `None` or `'nearest'` gives the correct result with PDF output (and screen/file match).  PNG, JPG, and SVG output filetypes all produce the correct results.  MWE below.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

data = np.zeros((25, 25))
data[8:16, 8:16] = 100

fig, ax = plt.subplots()
ax.imshow(data, interpolation='none')
fig.savefig('output.pdf')
```

### Actual outcome

Notebook/screen output (correct):

![screen](https://user-images.githubusercontent.com/4992897/228700365-d1d1e1cb-3a81-4b32-b5ac-1931a9078bbc.png)

PDF File output (incorrect):
[output.pdf](https://github.com/matplotlib/matplotlib/files/11106733/output.pdf)

### Expected outcome

The output PDF file would not have interpolation applied (matching the screen output).

### Operating system

macos

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.11.2

### Jupyter version

6.5.3

### Installation

pip

**Comment by ksunden** [comment]
What precisely is different? The pdf and the image you show look identical to me (I mean, I didn't do pixel by pixel comparisons)

It's _possible_ that what you are seeing is from your PDF viewer.

See also: #24425 (especially as you are on macos, though that had to do with `gouraud` shading, I'd expect 'none' to be less problematic in general)

I will note that `"none"` is documented as only supported by `agg`, `ps`, and `pdf` backends (`backend_inline` builds on top of `agg`, so I'd expect it _should_ work, but wouldn't be too surprised to learn there are expected subtle differences...)

"none" on other backends falls back to "nearest"

**Comment by larrybradley** [comment]
@ksunden Many thanks for the quick reply!  Very surprisingly the issue *is* caused by my PDF viewer (`Preview` on macos)!  Here's a screenshot:

<img width="480" alt="preview" src="https://user-images.githubusercontent.com/4992897/228711014-6e8f1cd5-00af-4cd0-ad1b-7d7b3464c5b3.png">

When I open the PDF file in other tools (e.g., gimp, inkscape, chrome) it looks correct (no interpolation).  Interestingly, it's also interpolated in `Safari`.  So I assume this is a bug with `Preview` (and `Safari`) and not the result of malformed PDF output.  Thanks!

**Comment by larrybradley** [comment]
It's odd though that the PDF file produced by `interpolation='nearest'` looks fine in `Preview`.

**Comment by jklymak** [comment]
Yeah, that is pretty strange.  This does seem to be a Preview issue - Acrobat Reader does have this behaviour either.  However, I'm not clear why 'none' and 'nearest' behave differently as I don't see anything in the PDF backend that indicates it knows what interpolation was used, and I'm pretty sure the image that gets sent to the PDF viewer is just made with our normal Agg image compositing.

**Comment by ksunden** [comment]
There is a difference for the rendering of AxesImage objects between `"none"` and `"nearest"` (note that `None` as in `NoneType` means "use rcparam", which defaults to `"antialiased"`, not `"none"`)

For the PDF backend, `"none"` means "directly use this image, using pdf to scale it appropriately" and "nearest" (and other interpolation strategies) mean "Do the rendering first to a (72 dpi?) canvas, then put _that_ image into the pdf as a png)

Adding a quick `print(data.shape)` to the `_writeImg` method of `backend_pdf.PdfFile` reveals this difference:

https://github.com/matplotlib/matplotlib/blob/c8aaa903df68d6c82c59cb5a344b11232a4493e8/lib/matplotlib/backends/backend_pdf.py#L1721

```python
import numpy as np
import matplotlib.pyplot as plt

data = np.zeros((3, 3))
data[1, 1] = 100

fig, (ax,ax1) = plt.subplots(ncols=2)
ax.imshow(data, interpolation='none')
ax1.imshow(data, interpolation='nearest')
fig.savefig('output.pdf')
```

prints:

```
(3, 3, 3)
(226, 226, 3)
```

Indicating that the "none" image is passed directly, but the "nearest" image is rendered onto a 226x226 image first.

Both look identical (in most viewers, but Apple's rendering in Preview/Safari seems to apply a blur to the image that is more noticeable in lower resolution):

[output.pdf](https://github.com/matplotlib/matplotlib/files/11108048/output.pdf)

![image](https://user-images.githubusercontent.com/2501846/228737775-50489f40-e25d-42d2-8619-878b55aa425c.png)

The code which governs this looks to be:

https://github.com/matplotlib/matplotlib/blob/b3bd929cf07ea35479fded8f739126ccc39edd6d/lib/matplotlib/image.py#L633-L636

In particular `_check_unsampled_image`, for which the default implementation for AxesImage is:

https://github.com/matplotlib/matplotlib/blob/b3bd929cf07ea35479fded8f739126ccc39edd6d/lib/matplotlib/image.py#L952-L954

(Along with the check that the backend supports it, which the PDF backend _does_)

I think this is working as intended on our end at least

I could see an argument for extending some documentation somewhere, perhaps stating explicitly in the docstring for `AxesImage.set_interpolation` that "none" means "do not resample" (there is a note there already that it is only supported in certain backends and falls back to "nearest").
It is also already rather explicitly documented in https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html

https://github.com/matplotlib/matplotlib/blob/b3bd929cf07ea35479fded8f739126ccc39edd6d/lib/matplotlib/image.py#L756-L770

**Comment by ksunden** [comment]
One more note:

I suspect that there is an option in Preview's config to turn off this behavior, judging from https://pdf.wondershare.com/pdf-editor-mac/pdf-blurry-in-preview-on-mac.html

My guess is that they introduced this (and turned it on by default...) for hi-dpi screens to make the text (especially) look better. but the problem here is that they are applying this filter in image space, not in screen space (and in general, maybe shouldn't be applying it at all on images...)

I don't have a mac to check this with, but that is my suspicion.

**Comment by jklymak** [comment]
OK, so 'none' in PDF is sending a 25x25 image to the PDF, whereas all the other interpolators are interpolating onto the 100-dpi resolution (or whatever resolution is set in savefig).  That explains the behaviour.   However, it seems to me that there should still be a clarification in the docstring which really does make it sound like "none" == "nearest" for the PDF backend, whereas thats not at all the case.

**Comment by ksunden** [comment]
Rereading the docstring, not sure what I would add:

> If 'none', the image is 
         shown as is without interpolating. 'none' is only supported in 
         agg, ps and pdf backends and will fall back to 'nearest' mode 
         for other backends. 
         
That actually reads to me as exactly what is happening, and explicitly stating that pdf (and agg/ps) _do_ have different behavior.

Always happy to have more clarity, but when I was thinking about what I'd add, my first thought was pretty much exactly what is already there.

**Comment by jklymak** [comment]
I mean this isn't actually true is it?  There is no way the Agg backend doesn't do any up- or downsampling?

**Comment by ksunden** [comment]
Yeah, that is very much the case:

```
lib/matplotlib/backends/backend_pgf.py
600:    def option_scale_image(self):
601-        # docstring inherited
602-        return True

lib/matplotlib/backends/backend_svg.py
914:    def option_scale_image(self):
915-        # docstring inherited
916-        return True

lib/matplotlib/backends/_backend_pdf_ps.py
91:    def option_scale_image(self):
92-        # docstring inherited
93-        return True  # PDF and PS support arbitrary image scaling.

lib/matplotlib/backends/backend_agg.py
298:    def option_scale_image(self):
299-        # docstring inherited
300-        return False
```

Default is False:
```
lib/matplotlib/backend_bases.py
501:    def option_scale_image(self):
502-        """
503-        Return whether arbitrary affine transformations in `draw_image` are
504-        supported (True for most vector backends).
505-        """
506-        return False
```

**Comment by sangfengchn** [comment]
I encountered the same issue when trying to save a figure as a pdf file. However, I discovered that setting the interpolation parameter to 'nearest' or omitting it altogether resolved the issue. Meanwhile, the dpi needs to be setting in the subplots funtion. Otherwise, the edges of figure in the pdf file will not be clear enough.
