### ISSUE TITLE
error checking should be performed as early as possible (here: non-ASCII str's in e.g. ylabel())

### ISSUE THREAD

**Issue by hmeine** [matplotlib/matplotlib#2560]
When using set_ylabel('Täst') in the ipython notebook, there will not be any plot, but also no error message visible.  The real problem is that the notebook does not show exceptions that happen in draw(), but also in the console ipython, an exception raised by set_ylabel() itself would be rendered much better than the one coming asynchroneously from draw().

If possible, an exception like this one:

```
  File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 1797, in is_math_text
    "matplotlib display text must have all code points < 128 or use "
ValueError: matplotlib display text must have all code points < 128 or use Unicode strings
```

should already be raised in the Text() constructor (or whereever appropriate).

**Comment by petehuang** [comment]
What's the exact action for MPL for this issue?

**Comment by WeatherGod** [comment]
I think we punted this to the traitlets work

**Comment by petehuang** [comment]
For visitor reference, traitlets discussion/work sitting in #4762.

Guess we can leave this open (...ugh) but need to remember to come back to this once traitlets work is complete

**Comment by anntzer** [comment]
set_ylabel raises an exception now
```
$ python2 -c 'from pylab import *; gca().set_ylabel("Täst")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 254, in set_ylabel
    return self.yaxis.set_label_text(ylabel, fontdict, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/axis.py", line 1505, in set_label_text
    self.label.set_text(label)
  File "/usr/lib/python2.7/site-packages/matplotlib/text.py", line 1212, in set_text
    self._text = '%s' % (s,)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```
so closing (unless I'm mistaken?).  The traitlets work is tracked in a number of other issues.
