### ISSUE TITLE
[Doc]: better document default margins

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#25613]
I notice that the [autoscaling section in the user guide](https://matplotlib.org/devdocs/users/explain/axes/autoscale.html#margins) states
> The default margin around the data limits is 5%

This should perhaps be updated to indicate that it defaults to the rcParam (which defaults to 5%).  Possibly the docstrings of the various margin setting methods could also be updated to state where the default comes from.

_Originally posted by @rcomer in https://github.com/matplotlib/matplotlib/issues/25599#issuecomment-1493407846_

**Comment by Darshanjaji** [comment]
assign to me

**Comment by timhoffm** [comment]
You are welcome to submit a pull request right away.
