### ISSUE TITLE
[MNT]:  Unused function parameters in backend_bases.py

### ISSUE THREAD

**Issue by theoniko** [matplotlib/matplotlib#25614]
### Summary

There are some unused function parameters reported by solarlint which i think can be removed and cleanup the function.
I am not sure if the reason is  to support backward compatibility.
![image](https://user-images.githubusercontent.com/28800819/229895654-b8c3b603-a3c9-4808-aa3d-cb576601edba.png)

Please let me know if i can remove them.

**Comment by ksunden** [comment]
Backend bases is full of abstract classes (not actually enforced as in "uses the metaclass `abc.ABCMeta`", but in the logical sense)

As such it is defining the signatures for subclasses to implement, and therefore the unused variables should _not_ be removed. The purpose of these classes is to define these interfaces.

Some of these are by default no-op calls, others will `raise NotImplementedError` or return perform some other default behavior that may not change based on some parameters, but those parameters are still expected to be passed in.

**Comment by anntzer** [comment]
Agreed that these are basically false positives.
