### ISSUE TITLE
[Bug]: ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by f-assene** [matplotlib/matplotlib#25612]
### Bug summary

Cartopy does not work anymore with Matplotlib

### Code for reproduction

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cpf

#%%
fig = plt.figure(facecolor='w',dpi=300)
axe = plt.axes(projection=ccrs.PlateCarree())
```

### Actual outcome

```
fig = plt.figure(facecolor='w',dpi=300)
axe = plt.axes(projection=ccrs.PlateCarree())
Traceback (most recent call last):

  Cell In[2], line 2
    axe = plt.axes(projection=ccrs.PlateCarree())

  File /data/vdi/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py:1122 in axes
    return fig.add_subplot(**kwargs)

  File /data/vdi/anaconda3/lib/python3.9/site-packages/matplotlib/figure.py:757 in add_subplot
    ax = projection_class(self, *args, **pkw)

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py:419 in __init__
    super().__init__(*args, **kwargs)

  File /data/vdi/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py:683 in __init__
    self.clear()

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py:599 in clear
    self.__clear()

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py:586 in __clear
    self._boundary()

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py:1556 in _boundary
    trans_path = proj_to_data.transform_path(path)

  File /data/vdi/anaconda3/lib/python3.9/site-packages/matplotlib/transforms.py:1595 in transform_path
    return self.transform_path_affine(self.transform_path_non_affine(path))

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py:170 in transform_path_non_affine
    new_vertices = self.target_projection.quick_vertices_transform(

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/crs.py:1365 in quick_vertices_transform
    return_value = super().quick_vertices_transform(vertices, src_crs)

  File /data/vdi/anaconda3/lib/python3.9/site-packages/cartopy/crs.py:1250 in quick_vertices_transform
    if (x.min() >= x_limits[0] and x.max() <= x_limits[1] and

  File /data/vdi/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py:44 in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)

ValueError: zero-size array to reduction operation minimum which has no identity

<Figure size 1800x1200 with 0 Axes>
```

### Expected outcome

Should work without error.

### Additional information

**# Conda list** 
`# packages in environment at /data/vdi/anaconda3:
#

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39h06a4308_1  
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-client           1.11.1           py39h06a4308_0  
anaconda-navigator        2.4.0            py39h06a4308_0  
anyio                     3.5.0            py39h06a4308_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
arrow                     1.2.3            py39h06a4308_1  
astroid                   2.14.2           py39h06a4308_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     22.1.0           py39h06a4308_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.11.0           py39h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.12.0           py39h06a4308_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.6.0           py39h06a4308_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
boltons                   23.0.0           py39h06a4308_0  
bottleneck                1.3.5            py39h7deecbd_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cartopy                   0.21.1                   pypi_0    pypi
cdo                       1.5.7                    pypi_0    pypi
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h5eee18b_3  
cftime                    1.6.2                    pypi_0    pypi
chardet                   4.0.0           py39h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py39h06a4308_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2            py39h06a4308_1  
colorama                  0.4.6            py39h06a4308_0  
comm                      0.1.2            py39h06a4308_0  
conda                     23.3.1           py39hf3d152e_0    conda-forge
conda-build               3.24.0           py39h06a4308_0  
conda-content-trust       0.1.3            py39h06a4308_0  
conda-env                 2.6.0                         1  
conda-package-handling    2.0.2            py39h06a4308_0  
conda-package-streaming   0.7.0            py39h06a4308_0  
conda-repo-cli            1.0.41           py39h06a4308_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
confuse                   1.5.0              pyhd3eb1b0_0  
contourpy                 1.0.5            py39hdb19cb5_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              40.0.0                   pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
data                      0.4                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.0.7                    pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.6            py39h06a4308_0  
docstring-to-markdown     0.11             py39h06a4308_0  
docutils                  0.18.1           py39h06a4308_3  
entrypoints               0.4              py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.9                h6a678d5_0  
filelock                  3.9.0            py39h06a4308_0  
flake8                    6.0.0            py39h06a4308_0  
flask                     2.2.3                    pypi_0    pypi
flit-core                 3.8.0            py39h06a4308_0  
fontconfig                2.14.1               h52c9d5c_1  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.18.3           py39h06a4308_0  
geos                      0.2.3                    pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
glib                      2.69.1               he621ea3_2  
glob2                     0.7                pyhd3eb1b0_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
gsw                       3.6.16.post1             pypi_0    pypi
htmlmin                   0.1.12             pyhd3eb1b0_1  
icu                       58.2                 he6710b0_3  
idna                      3.4              py39h06a4308_0  
imagehash                 4.3.1            py39h06a4308_0  
imageio                   2.27.0                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
imagesize                 1.4.1            py39h06a4308_0  
importlib-metadata        6.0.0            py39h06a4308_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
inflection                0.5.1            py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.19.2           py39hb070fc8_0  
ipython                   8.10.0           py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.0.4            py39h06a4308_0  
isort                     5.9.3              pyhd3eb1b0_0  
itsdangerous              2.1.2                    pypi_0    pypi
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.18.1           py39h06a4308_1  
jeepney                   0.7.1              pyhd3eb1b0_0  
jellyfish                 0.9.0            py39h7f8727e_0  
jinja2                    3.1.2            py39h06a4308_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
joblib                    1.1.1            py39h06a4308_0  
jpeg                      9e                   h5eee18b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3           py39h06a4308_0  
jupyter_client            7.4.9            py39h06a4308_0  
jupyter_core              5.3.0            py39h06a4308_0  
jupyter_server            1.23.4           py39h06a4308_0  
jupyterlab                3.5.3            py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.21.0           py39h06a4308_0  
jupyterlab_widgets        3.0.5            py39h06a4308_0  
keyring                   23.13.1          py39h06a4308_0  
kiwisolver                1.4.4            py39h6a678d5_0  
krb5                      1.19.4               h568e23c_0  
latex                     0.7.0                    pypi_0    pypi
lazy-object-proxy         1.6.0            py39h27cfd23_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libarchive                3.6.2                hab531cd_0  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  10.0.1          default_hb85057a_2  
libcurl                   7.88.1               h91b91d3_0  
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
liblief                   0.12.3               h6a678d5_0  
libllvm10                 10.0.1               hbcb73fb_5  
libnghttp2                1.46.0               hce63b2e_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.9                 h16c4e8d_3  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.0                h6a678d5_2  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                hfa300c1_0  
libxml2                   2.9.14               h74e7548_0  
libxslt                   1.1.35               h4e12654_0  
llvmlite                  0.39.1                   pypi_0    pypi
lxml                      4.9.1            py39h1edc446_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py39h7f8727e_0  
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6            py39h06a4308_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
missingno                 0.4.2              pyhd3eb1b0_1  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
more-itertools            8.12.0             pyhd3eb1b0_0  
moviepy                   1.0.3                    pypi_0    pypi
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3            py39h06a4308_1  
navigator-updater         0.3.0            py39h06a4308_0  
nbclassic                 0.5.3            py39h06a4308_0  
nbclient                  0.5.13           py39h06a4308_0  
nbconvert                 6.5.4            py39h06a4308_0  
nbformat                  5.7.0            py39h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py39h06a4308_0  
netcdf4                   1.6.1                    pypi_0    pypi
networkx                  2.8.4            py39h06a4308_1  
notebook                  6.5.3            py39h06a4308_0  
notebook-shim             0.2.2            py39h06a4308_0  
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numba                     0.56.4                   pypi_0    pypi
numexpr                   2.8.4            py39he184ba9_0  
numpy                     1.23.5           py39h14f4228_0  
numpy-base                1.23.5           py39h31eccc5_0  
numpydoc                  1.5.0            py39h06a4308_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0             py39h06a4308_0  
pandas                    1.5.3            py39h417a72b_0  
pandas-profiling          2.9.0              pyhd3eb1b0_0    anaconda
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.10.3           py39h06a4308_0  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
phik                      0.12.3           py39hdb19cb5_0  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.0.1                   pypi_0    pypi
pkginfo                   1.9.6            py39h06a4308_0  
platformdirs              2.5.2            py39h06a4308_0  
pluggy                    1.0.0            py39h06a4308_1  
ply                       3.11             py39h06a4308_0  
pooch                     1.4.0              pyhd3eb1b0_0  
poyo                      0.5.0              pyhd3eb1b0_0  
proglog                   0.1.10                   pypi_0    pypi
proj                      0.2.0                    pypi_0    pypi
prometheus_client         0.14.1           py39h06a4308_0  
prompt-toolkit            3.0.36           py39h06a4308_0  
psutil                    5.9.0            py39h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-lief                   0.12.3           py39h6a678d5_0  
py4j                      0.10.9.5                 pypi_0    pypi
pycodestyle               2.10.0           py39h06a4308_0  
pycosat                   0.6.4            py39h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.3.0            py39h06a4308_0  
pyflakes                  3.0.1            py39h06a4308_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.4.0            py39h06a4308_0  
pylint                    2.16.2           py39h06a4308_0  
pylint-venv               2.3.0            py39h06a4308_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyopenssl                 23.1.0                   pypi_0    pypi
pyparsing                 3.0.9            py39h06a4308_0  
pyproj                    3.4.1            py39hb83c990_0  
pyqt                      5.15.7           py39h6a678d5_1  
pyqt5-sip                 12.11.0          py39h6a678d5_1  
pyqtwebengine             5.15.7           py39h6a678d5_1  
pyrsistent                0.18.0           py39heee7806_0  
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0  
pyspark                   3.3.1                    pypi_0    pypi
python                    3.9.16               h7a1cb2a_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39h06a4308_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.2.1            py39h06a4308_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.7.1            py39h06a4308_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytoolconfig              1.2.5            py39h06a4308_1  
pytz                      2022.7           py39h06a4308_0  
pywavelets                1.4.1            py39h5eee18b_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    6.0              py39h5eee18b_1  
pyzmq                     23.2.0           py39h6a678d5_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.2.2            py39h06a4308_0  
qt-main                   5.15.2               h327a75a_7  
qt-webengine              5.15.9               hd2b0992_4  
qtawesome                 1.2.2            py39h06a4308_0  
qtconsole                 5.4.0            py39h06a4308_0  
qtpy                      2.2.0            py39h06a4308_0  
qtwebkit                  5.212                h4eab89a_4  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1           py39h06a4308_1  
ripgrep                   13.0.0               hbdeaff8_0  
rope                      1.7.0            py39h06a4308_0  
rtree                     1.0.1            py39h06a4308_0  
ruamel.yaml               0.17.21          py39h5eee18b_0  
ruamel.yaml.clib          0.2.6            py39h5eee18b_1  
scipy                     1.10.0           py39h14f4228_1  
seaborn                   0.12.2           py39h06a4308_0  
secretstorage             3.3.1            py39h06a4308_1  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                65.6.3           py39h06a4308_0  
shapely                   1.8.5                    pypi_0    pypi
shutilwhich               1.1.0                    pypi_0    pypi
simple-colors             0.1.5                    pypi_0    pypi
sip                       6.6.2            py39h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py39h06a4308_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.4              py39h06a4308_0  
sphinx                    5.0.2            py39h06a4308_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.4.1            py39h06a4308_0  
spyder-kernels            2.4.1            py39h06a4308_0  
sqlite                    3.41.1               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tangled-up-in-unicode     0.2.0            py39h06a4308_0  
tempdir                   0.7.1                    pypi_0    pypi
terminado                 0.17.1           py39h06a4308_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss2                  1.2.1            py39h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39h06a4308_0  
tomlkit                   0.11.1           py39h06a4308_0  
toolz                     0.12.0           py39h06a4308_0  
tornado                   6.2              py39h5eee18b_0  
tqdm                      4.65.0           py39hb070fc8_0  
traitlets                 5.7.1            py39h06a4308_0  
typing-extensions         4.4.0            py39h06a4308_0  
typing_extensions         4.4.0            py39h06a4308_0  
tzdata                    2023c                h04d1e81_0  
ujson                     5.4.0            py39h6a678d5_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.15          py39h06a4308_0  
visions                   0.5.0              pyhd3eb1b0_0  
watchdog                  2.1.6            py39h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
websocket-client          0.58.0           py39h06a4308_4  
werkzeug                  2.2.3                    pypi_0    pypi
whatthepatch              1.0.2            py39h06a4308_0  
wheel                     0.38.4           py39h06a4308_0  
widgetsnbextension        4.0.5            py39h06a4308_0  
wrapt                     1.14.1           py39h5eee18b_0  
wurlitzer                 3.0.2            py39h06a4308_0  
xarray                    2023.3.0                 pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.11.0           py39h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0           py39h5eee18b_0  
zstd                      1.5.4                hc292b87_0  

`

**pip list** 
`Package                       Version
----------------------------- ------------
alabaster                     0.7.12
anaconda-client               1.11.1
anaconda-navigator            2.4.0
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
asttokens                     2.0.5
atomicwrites                  1.4.0
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
beautifulsoup4                4.12.0
binaryornot                   0.4.4
black                         22.6.0
bleach                        4.1.0
boltons                       23.0.0
Bottleneck                    1.3.5
brotlipy                      0.7.0
Cartopy                       0.21.1
cdo                           1.5.7
certifi                       2022.12.7
cffi                          1.15.1
cftime                        1.6.2
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.6
comm                          0.1.2
conda                         23.3.1
conda-build                   3.24.0
conda-content-trust           0.1.3
conda-package-handling        2.0.2
conda_package_streaming       0.7.0
conda-repo-cli                1.0.41
conda-token                   0.4.0
conda-verify                  3.4.2
confuse                       1.5.0
contourpy                     1.0.5
cookiecutter                  1.7.3
cryptography                  40.0.0
cycler                        0.11.0
data                          0.4
debugpy                       1.5.1
decorator                     5.0.7
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docstring-to-markdown         0.11
docutils                      0.18.1
entrypoints                   0.4
executing                     0.8.3
fastjsonschema                2.16.2
filelock                      3.9.0
flake8                        6.0.0
Flask                         2.2.3
flit_core                     3.8.0
fonttools                     4.25.0
funcsigs                      1.0.2
future                        0.18.3
geos                          0.2.3
glob2                         0.7
gsw                           3.6.16.post1
htmlmin                       0.1.12
idna                          3.4
ImageHash                     4.3.1
imageio                       2.27.0
imageio-ffmpeg                0.4.8
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.2.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       8.10.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.9.3
itsdangerous                  2.1.2
jaraco.classes                3.2.1
jedi                          0.18.1
jeepney                       0.7.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
joblib                        1.1.1
json5                         0.9.6
jsonpatch                     1.32
jsonpointer                   2.1
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.3.0
jupyter-server                1.23.4
jupyterlab                    3.5.3
jupyterlab-pygments           0.1.2
jupyterlab_server             2.21.0
jupyterlab-widgets            3.0.5
keyring                       23.13.1
kiwisolver                    1.4.4
latex                         0.7.0
lazy-object-proxy             1.6.0
libarchive-c                  2.9
llvmlite                      0.39.1
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
missingno                     0.4.2
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                8.12.0
moviepy                       1.0.3
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.3.0
nbclassic                     0.5.3
nbclient                      0.5.13
nbconvert                     6.5.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
netCDF4                       1.6.1
networkx                      2.8.4
notebook                      6.5.3
notebook_shim                 0.2.2
numba                         0.56.4
numexpr                       2.8.4
numpy                         1.23.5
numpydoc                      1.5.0
packaging                     23.0
pandas                        1.5.3
pandas-profiling              2.9.0
pandocfilters                 1.5.0
parso                         0.8.3
pathlib                       1.0.1
pathspec                      0.10.3
pexpect                       4.8.0
phik                          0.12.3
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.0.1
pkginfo                       1.9.6
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
pooch                         1.4.0
poyo                          0.5.0
proglog                       0.1.10
proj                          0.2.0
prometheus-client             0.14.1
prompt-toolkit                3.0.36
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py4j                          0.10.9.5
pycodestyle                   2.10.0
pycosat                       0.6.4
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.0.1
Pygments                      2.11.2
PyJWT                         2.4.0
pylint                        2.16.2
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pyOpenSSL                     23.1.0
pyparsing                     3.0.9
pyproj                        3.4.1
PyQt5-sip                     12.11.0
pyrsistent                    0.18.0
pyshp                         2.3.1
PySocks                       1.7.1
pyspark                       3.3.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.1
python-slugify                5.0.2
pytoolconfig                  1.2.5
pytz                          2022.7
PyWavelets                    1.4.1
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.0
QtPy                          2.2.0
requests                      2.28.1
rope                          1.7.0
Rtree                         1.0.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scipy                         1.10.0
seaborn                       0.12.2
SecretStorage                 3.3.1
Send2Trash                    1.8.0
setuptools                    65.6.3
Shapely                       1.8.5
shutilwhich                   1.1.0
simple-colors                 0.1.5
sip                           6.6.2
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.1
spyder-kernels                2.4.1
stack-data                    0.2.0
tangled-up-in-unicode         0.2.0
tempdir                       0.7.1
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
toolz                         0.12.0
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.7.1
typing_extensions             4.4.0
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.15
visions                       0.5.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.2.3
whatthepatch                  1.0.2
wheel                         0.38.4
widgetsnbextension            4.0.5
wrapt                         1.14.1
wurlitzer                     3.0.2
xarray                        2023.3.0
yapf                          0.31.0
zipp                          3.11.0
zstandard                     0.19.0
`

### Operating system

System version CentOS Linux 7 (Core)

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.16

### Jupyter version

3.5.3

### Installation

pip

**Comment by greglucas** [comment]
I can't reproduce this with the most recent Cartopy and Matplotlib versions. Are you sure you are using the versions of packages you think in this virtual environment? It looks like there is a mix of pypi and conda packages in there. I'd suggest creating a new conda environment to test. If you still have issues, this should be reported to Cartopy's issue tracker since it is an issue downstream: https://github.com/SciTools/cartopy/issues
