### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute '_all_deprecated'

### ISSUE THREAD

**Issue by salvarezaie** [matplotlib/matplotlib#25633]
I am getting this error. My matplot is updated. I tried to uninstall and install it again, and still same problem. 
File ~\anaconda3\lib\site-packages\matplotlib\_api\__init__.py:226, in caching_module_getattr.<locals>.__getattr__(name)
    224 if name in props:
    225     return props[name].__get__(instance)
--> 226 raise AttributeError(
    227     f"module {cls.__module__!r} has no attribute {name!r}")

AttributeError: module 'matplotlib' has no attribute '_all_deprecated'

**Comment by jklymak** [comment]
You have an install problem.  Let's follow up at https://discourse.matplotlib.org and revisit here if a Matplotliub bug is found.
