### ISSUE TITLE
[Doc]: matplotlibrc.template does not exist anymore

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#25678]
### Documentation Link

https://matplotlib.org/stable/api/rcsetup_api.html

### Problem

"Any additions or deletions to the parameter set listed here should also be propagated to the matplotlibrc.template in Matplotlib's root source directory."

matplotlibrc.template is now called matplotlibrc and located in lib/matplotlib/mpl-data/

Grepping:
```
lib/matplotlib/__init__.py:https://github.com/matplotlib/matplotlib/blob/%(version)s/matplotlibrc.template
lib/matplotlib/font_manager.py:            matplotlibrc.template file
lib/matplotlib/rcsetup.py:propagated to the :file:`matplotlibrc.template` in Matplotlib's root source
lib/matplotlib/rcsetup.py:# The rcParams defaults are defined in matplotlibrc.template, which gets copied
lib/matplotlib/rcsetup.py:_hardcoded_defaults = {  # Defaults not inferred from matplotlibrc.template...
lib/matplotlib/text.py:            :ref:`matplotlibrc.template file
```

### Suggested improvement

Update all references to matplotlibrc.template, except for those in old change notes:
```
doc/users/prev_whats_new/changelog.rst:    matplotlibrc.template so that text will be scaled by default when changing
doc/users/prev_whats_new/changelog.rst:    commented out all default values in matplotlibrc.template Default values
doc/users/prev_whats_new/github_stats_3.1.1.rst:* :ghpull:`14409`: Backport PR #14335 on branch v3.1.x (Add explanation of animation.embed_limit to matplotlibrc.template)
doc/users/prev_whats_new/github_stats_3.1.1.rst:* :ghpull:`14335`: Add explanation of animation.embed_limit to matplotlibrc.template
doc/users/prev_whats_new/github_stats_3.2.0.rst:* :ghpull:`15108`: Fix doc build and resync matplotlibrc.template with actual defaults.
doc/users/prev_whats_new/github_stats_3.2.0.rst:* :ghpull:`14723`: Cleanup some parameter descriptions in matplotlibrc.template
doc/users/prev_whats_new/github_stats_3.2.0.rst:* :ghpull:`14709`: Try to improve the readability and styling of matplotlibrc.template file
doc/users/prev_whats_new/github_stats_3.2.0.rst:* :ghpull:`14671`: Improve readability of matplotlibrc.template
doc/users/prev_whats_new/github_stats_3.3.0.rst:* :ghpull:`15029`: Get default params from matplotlibrc.template.
doc/users/prev_whats_new/github_stats_3.3.0.rst:* :ghpull:`16523`: Reorder mathtext rcparams in matplotlibrc template.
doc/users/prev_whats_new/github_stats_3.3.0.rst:* :ghpull:`15023`: Simplify formatting of matplotlibrc.template.
doc/users/prev_whats_new/github_stats_3.5.0.rst:* :ghpull:`19603`: Remove matplotlibrc.template.
doc/users/prev_whats_new/github_stats_3.5.0.rst:* :ghpull:`19718`: Small style fixes to matplotlibrc.template.
```
(The above should **BE KEPT**.)

**Comment by Higgs32584** [comment]
This might be a good first issue!

**Comment by farukalampro** [comment]
@oscargus hey, I am new as a contributor. How can assign myself to this issue?

**Comment by rcomer** [comment]
@farukalampro you are welcome to submit a pull request for any issue, but we do not assign them.  Please see our contributors’ guide:
https://matplotlib.org/devdocs/devel/contributing.html

**Comment by farukalampro** [comment]
Hey, Thanks for your comment. I am one kind of new in github. Want to
improve my skill. Can you help me? I saw your profile. You achieved many
thing. Do you have any team? Do you or anything like LinkedIn or WhatsApp
where you can talk?

**Comment by farukalampro** [comment]
@rcomer hey, thanks for your comment. Here is my gmail mdfarukt222@gmail.com 

Can you send me a message?. I need guideline to start with open source.

**Comment by rcomer** [comment]
The guide I linked above describes the best place to ask for help.  I am not going to email you, sorry.

**Comment by farukalampro** [comment]
@rcomer thanks dear

**Comment by ksunden** [comment]
@Shashwatpandey4 it looks like you have your entire virtual environment added in git, which is why precommit is flagging codespell in our dependencies and preventing the commit from completing

**Comment by Shashwatpandey4** [comment]
Thanks for the response @ksunden i've added my vitual environment folder to .gitignore, i'm still not able to commit 

![image](https://user-images.githubusercontent.com/41941051/232579710-0064b1f7-45bf-4d20-827a-5731ddc5e8e5.png)

**Comment by ksunden** [comment]
@Shashwatpandey4 you still have your environment added, you'll need to `git reset venv` to remove them from your `git add` (`.gitignore` only affects future adds, not past adds)

I would generally recommend either setting up your venvs _outside_ of the git repo or changing your _personal_ global gitignore to avoid editing project `.gitignore`s for your workflow:

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by Shashwatpandey4** [comment]
@ksunden i've remove the virtual environment files from the git index, now i'm able to commit, i've already raised a pull request

**Comment by Higgs32584** [comment]
you can go to pull request to open a new one, and then make sure to reference the issue number so that it is linked @Shashwatpandey4
