### ISSUE TITLE
Matplotlib Animation.save() hangs from stalled pipe

### ISSUE THREAD

**Issue by snaphat** [matplotlib/matplotlib#2568]
This is to report that an early fix for a bug doesn't actually work:
https://github.com/matplotlib/matplotlib/commit/b83627514cc4c1ecd2e1dfe62212c10f4b72a9f7

FFmpeg pushes status information about frames/fps/time/bitrate/etc to stderr regardless of the log level so the buffer is going to eventually fill and stall the pipe when enough information is pushed.

There are three possible solutions I see:

1) Redirecting stderr to a file and read that if an exception is raised.

2) Disabling blocking on the non-redirected file descriptor and reading/buffering the stderr into memory manually similar to the following: 
http://chase-seibert.github.io/blog/2012/11/16/python-subprocess-asynchronous-read-stdout.html

3) Don't redirect stderr for printing on error.

**Comment by tacaswell** [comment]
According to my last comment, this is only an issue for 3.2 that we no longer 'officially' support, closing.
