### ISSUE TITLE
[Bug]: _get_legend_handles_labels() method doesn't work when the first charactere of the label is "_"

### ISSUE THREAD

**Issue by thiagoricardop** [matplotlib/matplotlib#25683]
### Bug summary

I'm using the matplot lib to plot some data and when I try to get the labels of the databases it doesn't work if the label starts with an underscore "_", and the function _get_legend_handles_labels() in the legend.py file doesn't get the labels and the handles to put in the legend.
This is the original code that only add labels and handles to the lists if the condition "label and not label.startswith('_')".
def _get_legend_handles_labels(axs, legend_handler_map=None):
    """
    Return handles and labels for legend, internal method.

    """
    handles = []
    labels = []

    for handle in _get_legend_handles(axs, legend_handler_map):
        label = handle.get_label()
        if label and not label.startswith('_'):
            handles.append(handle)
            labels.append(label)
    return handles, labels

### Code for reproduction

```python
# possible solution

def _get_legend_handles_labels(axs, legend_handler_map=None):
    """
    Return handles and labels for legend, internal method.

    """
    handles = []
    labels = []

    for handle in _get_legend_handles(axs, legend_handler_map):
        label = handle.get_label()
        if label and label.startswith('_'):
            handles.append(handle)
            labels.append(label[1:])
        else:
            handles.append(handle)
            labels.append(label)
    return handles, labels
```

### Actual outcome

![image](https://user-images.githubusercontent.com/110063560/232094824-47b0d3a7-5ae1-4236-a611-c03e084092ad.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/110063560/232095417-ed219c3a-f649-4c19-9299-7045147a1e8c.png)
![image](https://user-images.githubusercontent.com/110063560/232095873-073bcaa1-6044-4fe1-8a88-bf4a20851c95.png)

### Operating system

Ubuntu

### Matplotlib Version

3.3.4

### Python version

3.6.8

### Installation

None

**Comment by ksunden** [comment]
As @chahak13 said, this is intended, documented behavior which is not likely to change, as it has been so for a long time and many people (as well as internally) rely on this behavior to _exclude_ items from the legends.

You can either strip the underscore (`label.lstrip("_")`) or add whitespace to the front of the label strings (if you don't want to offset horizontally, a "zero-width space" (`"\u200c"`) will disable the ignore while not changing the glyphs created.)

Since there is no action to take on our end, I'll close this issue

**Comment by tacaswell** [comment]
It might be worth adding the note about `"\u200c"` to the docs.   I had never thought to do that before.

**Comment by Stifi-IFX** [comment]
I think due to https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.10.0.html#artists-explicitly-passed-in-will-no-longer-be-filtered-by-legend-based-on-their-label the issue should be reopened.

**Comment by rcomer** [comment]
@Stifi-IFX if you are having a problem with current Matplotlib, please open a new issue.  The change you note should not affect the automatic detection of handles and labels.
