### ISSUE TITLE
[Bug]: Unexpected warnings with GTK4agg backend.

### ISSUE THREAD

**Issue by brobr** [matplotlib/matplotlib#25688]
### Bug summary

After an upgrade to gobject-introspection-1.76.1 one gets unexpected warnings with GTK4Agg backend. Maybe these are coming from GTK4 and not matplotlib because they are still popping up when matplotlib warnings have been turned off. This is shown when items are removed from the toolbar:

      /usr/lib64/python3.9/site-packages/matplotlib/backend_bases.py:3412: Warning: Attempting to freeze the notification queue for object GtkImage[0x5caa550]; Property notification does not work during instance finalization.
      lambda event: self.remove_toolitem(event.tool.name))

No such warnings come up with GTK3Agg, QtAgg or TkAgg (change `#`  in `get_backend()` in code-example below)

### Code for reproduction

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# test_backend_toolbar
#
# adapted from https://matplotlib.org/stable/gallery/user_interfaces/toolmanager_sgskip.html

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.backend_tools import ToolBase, ToolToggleBase
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    mpl.rcParams['toolbar'] = 'toolmanager'


def get_backend():
    """Returns common values for matplotlib rc parameters."""
    return {
            #'backend': "TkAgg",
            #'backend': "QtAgg",
            #'backend': "GTK3Agg",
            'backend': "GTK4Agg",
            }

class ListTools(ToolBase):
    """List all the tools controlled by the `ToolManager`."""
    default_keymap = 'm'  # keyboard shortcut
    description = 'List Tools'

    def trigger(self, *args, **kwargs):
        print('_' * 80)
        fmt_tool = "{:12} {:45} {}".format
        print(fmt_tool('Name (id)', 'Tool description', 'Keymap'))
        print('-' * 80)
        tools = self.toolmanager.tools
        for name in sorted(tools):
            if not tools[name].description:
                continue
            keys = ', '.join(sorted(self.toolmanager.get_tool_keymap(name)))
            print(fmt_tool(name, tools[name].description, keys))
        print('_' * 80)
        fmt_active_toggle = "{0!s:12} {1!s:45}".format
        print("Active Toggle tools")
        print(fmt_active_toggle("Group", "Active"))
        print('-' * 80)
        for group, active in self.toolmanager.active_toggle.items():
            print(fmt_active_toggle(group, active))


class GroupHideTool(ToolToggleBase):
    """Show lines with a given gid."""
    default_keymap = 'S'
    description = 'Show by gid'
    default_toggled = True

    def __init__(self, *args, gid, **kwargs):
        self.gid = gid
        super().__init__(*args, **kwargs)

    def enable(self, *args):
        self.set_lines_visibility(True)

    def disable(self, *args):
        self.set_lines_visibility(False)

    def set_lines_visibility(self, state):
        for ax in self.figure.get_axes():
            for line in ax.get_lines():
                if line.get_gid() == self.gid:
                    line.set_visible(state)
        self.figure.canvas.draw()


@mpl.rc_context(get_backend())
def run_dialog():
    fig = plt.figure()
    plt.plot([1, 2, 3], gid='mygroup')
    plt.plot([2, 3, 4], gid='unknown')
    plt.plot([3, 2, 1], gid='mygroup')

    # Add the custom tools that we created
    fig.canvas.manager.toolmanager.add_tool('List', ListTools)
    fig.canvas.manager.toolmanager.add_tool('Show', GroupHideTool, gid='mygroup')

    # Add an existing tool to new group `foo`.
    # It can be added as many times as we want
    fig.canvas.manager.toolbar.add_tool('zoom', 'foo')

    # Remove the forward button
    fig.canvas.manager.toolmanager.remove_tool('forward')

    # To add a custom tool to the toolbar at specific location inside
    # the navigation group
    fig.canvas.manager.toolbar.add_tool('Show', 'navigation', 1)

    plt.show()

def main(args):
    run_dialog()
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
```

### Actual outcome

Figure gets displayed OK when script is run from console but with warnings that in my application are unwanted because they overshadow data displayed  for a user to see or copy.

### Expected outcome

no warnings

### Additional information

This worked fine prior to the gobject update. Don't know where to go to file this bug as I only see it with matplotlib and then when using the GTK4Agg backend.

### Operating system

Slackware linux, 64-bit 15.0+

### Matplotlib Version

3.7.1

### Matplotlib Backend

GTK4Agg

### Python version

3.9.16

### Jupyter version

na

### Installation

from source (.tar.gz)

**Comment by QuLogic** [comment]
With what version of GTK4 and GLib?

**Comment by brobr** [comment]
Sorry, didn't see your question sooner.

*  gtk4-4.8.3
*   glib-1.2.10

**Comment by QuLogic** [comment]
GTK2+ uses the `glib2` package (or whatever Slackware names it), not glib 1.

**Comment by brobr** [comment]
bash-5.2$ ls /var/log/packages/glib*
/var/log/packages/glib-1.2.10-x86_64-9
/var/log/packages/glib-networking-2.76.0-x86_64-1
/var/log/packages/glib2-2.76.1-x86_64-1

**Comment by QuLogic** [comment]
> gtk4-4.8.3
> glib2-2.76.1-x86_64-1

You will need to update to GTK4 4.10 to fix the warning; this is an upstream change: https://gitlab.gnome.org/GNOME/gtk/-/issues/5420

**Comment by brobr** [comment]
Ok, thanks for this advice, will test that. Yes it looked like it was a problem outwith matplotlib. 

Cheers

**Comment by brobr** [comment]
Hi, I tried gtk4-4.10.3. This gave me a fatal error see below (also after Slackware upgraded to glib2-2.76.2). 

Back to gtk4-4.8 and backend Grk3Agg:

        Traceback (most recent call last):
          File "/usr/lib64/python3.9/site-packages/matplotlib/backends/backend_gtk4.py", line 19, in <module>
            gi.require_version("Gtk", "4.0")
          File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 129, in require_version
            raise ValueError('Namespace %s not available for version %s' %
        ValueError: Namespace Gtk not available for version 4.0
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/home/rob/PROGRAMMING/PYTHON/COALISPR/coalispr/coalispr/coalispr.py", line 1012, in main
            coalispr(args)
          File "/home/rob/PROGRAMMING/PYTHON/COALISPR/coalispr/coalispr/coalispr.py", line 1002, in coalispr
            f(args)
          File "/home/rob/PROGRAMMING/PYTHON/COALISPR/coalispr/coalispr/coalispr.py", line 495, in showgraphs
            show_chr(chrnam_ , tag=tag_, refs=refs_, setlist=samples_, unsel=u_,
          File "/home/rob/PROGRAMMING/PYTHON/COALISPR/coalispr/coalispr/bedgraph_analyze/process_bedgraphs.py", line 634, in show_chr
            plot_chrset(chrnam, [df1, df2], setname, refs, unsel_, title, dowhat, scale,
          File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
            return func(*args, **kwds)
          File "/home/rob/PROGRAMMING/PYTHON/COALISPR/coalispr/coalispr/bedgraph_analyze/bedgraph_plots.py", line 440, in plot_chrset
            fig = plt.figure(figsize=(printwidth, printheight))
          File "/usr/lib64/python3.9/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
            return func(*args, **kwargs)
          File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 840, in figure
            manager = new_figure_manager(
          File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 383, in new_figure_manager
            _warn_if_gui_out_of_main_thread()
          File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 361, in _warn_if_gui_out_of_main_thread
            if _get_required_interactive_framework(_get_backend_mod()):
          File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 208, in _get_backend_mod
            switch_backend(rcParams._get("backend"))
          File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 271, in switch_backend
            backend_mod = importlib.import_module(
          File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
          File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 850, in exec_module
          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
          File "/usr/lib64/python3.9/site-packages/matplotlib/backends/backend_gtk4agg.py", line 4, in <module>
            from . import backend_agg, backend_gtk4
          File "/usr/lib64/python3.9/site-packages/matplotlib/backends/backend_gtk4.py", line 23, in <module>
            raise ImportError from e
        ImportError

**Comment by QuLogic** [comment]
Your GTK4 package appears to be missing gobject-introspection files; I don't think we can help with Slackware packaging issues.

**Comment by brobr** [comment]
It is on the system.....: ?

gobject-introspection-1.76.1

**Comment by brobr** [comment]
The error started to happen since glib2 got updated to 2.76.  Hmm. Ok Thanks for the help.
