### ISSUE TITLE
[Bug]: codecov.yml is invalid

### ISSUE THREAD

**Issue by stefmolin** [matplotlib/matplotlib#25695]
### Bug summary

I was using the `codecov.yml` file as an example for setting up a personal project and discovered that the file is actually invalid. I'm happy to put in a PR to fix if you are still using this.

### Code for reproduction

```python
cat .github/codecov.yml | curl --data-binary @- https://codecov.io/validate
```

### Actual outcome

```output
Error at ['coverage', 'status', 'project', 'library', 'paths']:
must be of list type
```

### Expected outcome

```output
Valid!

{
  ...
}
```

### Matplotlib Version

main

### Installation

None

**Comment by oscargus** [comment]
Please go ahead! At least I am regularly checking it and I think that many reviewers rely on it for the PR feedback.
