### ISSUE TITLE
[Bug]: Cannot set attributes on collections and artists

### ISSUE THREAD

**Issue by albavilanova** [matplotlib/matplotlib#25716]
### Bug summary

Good morning,

I was about to test https://github.com/matplotlib/matplotlib/issues/25426 and found a bug in the version 3.7.1 (the stable one) and also in the main branch, which didn't appear using Matplotlib 3.4.3. 

We have a PyQT application where we update the data on each plot very frequently. To remove the data we use:

```
ax.collections = []
ax.artists = []
```

Sometimes we need to keep some types of collections/artists and remove others, such as in:

```
ax.artists = list([artist for artist in ax.artists if type(artist) == AnchoredOffsetbox])
```

This stopped working in newer versions of Matplotlib, giving the following error:

```
AttributeError: can't set attribute
```

I don't know if this change was intended and if there is a workaround solution for this problem. Attached you can find a simple example of reproducible code.

Thank you in advance,
Alba

### Code for reproduction

```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

# Define crs
data_crs = ccrs.PlateCarree()
projection = ccrs.Robinson()

# Create map
ax = plt.axes(projection=projection)
ax.coastlines()
ax.set_global()

# Add points
latitude = [20, 40]
longitude = [0, 30]
ax.scatter(latitude, longitude, transform=data_crs)

# Remove points (ERROR: AttributeError: can't set attribute)
# This works with Matplotlib 3.4.3 and Cartopy 0.21.1
# It doesn't when I use Matplotlib 3.7.1
ax.collections = []

# Show map without points
plt.show()
```

### Actual outcome

```
AttributeError: can't set attribute
```

### Expected outcome

A global map without points, since we have removed them.

### Operating system

Ubuntu

### Matplotlib Version

3.7.1

### Python version

3.9

### Installation

pip

**Comment by rcomer** [comment]
Hi @albavilanova, thanks for testing #25426!  It looks like you now need to remove your unwanted artists individually, see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#axes-children-are-no-longer-separated-by-type

I’m going to close this because I do not think it’s a bug in Matplotlib.  But you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.

**Comment by albavilanova** [comment]
Hi @rcomer, thank you for the link, it was really helpful. 

For those who end up in this issue and don't know how to get around this, you can use this workaround to find the indices to remove, sort them and remove them from the collections.

```
inds_to_remove = []
for element_ind, element in enumerate(ax.collections):
    # TODO: Personalize your conditions (if you need to remove some specific type, etc.)
    inds_to_remove.append(element_ind)

for element_ind in sorted(inds_to_remove, reverse=True):
    ax.collections[element_ind].remove()
```

Since `ax.collections` is a `FeatureArtist`, it not possible to directly do:
```
for element in ax.collections:
    element_ind = ax.collections.index(element)
    ax.collections[element_ind].remove()
```

**Comment by QuLogic** [comment]
> ```
>     element_ind = ax.collections.index(element)
>     ax.collections[element_ind].remove()
> ```

But `ax.collections[ax.collections.index(element)] == element`, so there's no need to indirect it with the index. The only catch is that you'd be modifying a list that you're iterating, so you need to make a copy:
```python
for element in ax.collections[:]:
    if True:  # Whatever condition is needed.
        element.remove()
```

**Comment by albavilanova** [comment]
@QuLogic thank you for the input, the problem I have with that method doing:
```
collections = copy.deepcopy(ax.collections)
for element in collections:
    ax.collections[ax.collections.index(element)].remove()
```
is that `deepcopy` gives me different reference objects in `collections` and `ax.collections`, so I am getting a `ValueError` (not found).

**Comment by QuLogic** [comment]
There's no need for a deep copy; as in my example, a shallow copy is sufficient.
