### ISSUE TITLE
[Bug]:  'tuple' object has no attribute 'get_array'

### ISSUE THREAD

**Issue by chuwenhao123** [matplotlib/matplotlib#25717]
### Bug summary

I used the function "hist2d" to draw a picture with 2 subplots in matplotlib (version 3.7.1), and the colorbar of this picture cannot be set directly.  But for the function "hexbin", the colorbar can be set directly.  So how can i set the colobar for pictures with subplots using the function "hist2d"?

### Code for reproduction

```python
from matplotlib import pyplot as plt
import matplotlib as mpl
import numpy as np
from matplotlib.colors import LogNorm


mu, sigma = 3., 1. 
s = np.random.lognormal(mu, sigma, 10000)
mu, sigma = 4., 1. 
ss = np.random.lognormal(mu, sigma, 10000)


fig,ax=plt.subplots(1,2,figsize=(12,8),dpi=600)
axs1=ax[0].hist2d(s,ss,bins=120,cmap='jet',norm=LogNorm())
axs2=ax[1].hexbin(s,ss,bins='log',cmap='jet')
cbar=plt.colorbar(axs1,ax=ax[1])
```

### Actual outcome

File C:\anaconda\lib\site-packages\matplotlib\colorbar.py:306, in Colorbar.__init__(self, ax, mappable, cmap, norm, alpha, values, boundaries, orientation, ticklocation, extend, spacing, ticks, format, drawedges, filled, extendfrac, extendrect, label, location)
    302     mappable = cm.ScalarMappable(norm=norm, cmap=cmap)
    304 # Ensure the given mappable's norm has appropriate vmin and vmax
    305 # set even if mappable.draw has not yet been called.
--> 306 if mappable.get_array() is not None:
    307     mappable.autoscale_None()
    309 self.mappable = mappable

AttributeError: 'tuple' object has no attribute 'get_array'

### Expected outcome

![image](https://user-images.githubusercontent.com/51478550/232715174-5af8d086-ba3e-4a4b-a9e8-5e5dc1022e93.png)

### Matplotlib Version

3.7.1

### Installation

None

**Comment by ksunden** [comment]
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.hist2d.html#matplotlib.axes.Axes.hist2d

Hist2d has multiple return values (i.e. it returns a tuple of four things, the last of which is a QuadMesh image object)
Color bar expects only a ScalarMappable (which QuadMesh is one) so you would need to pass `axs1[-1]`

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.hexbin.html#matplotlib.axes.Axes.hexbin

Hexbin directly returns a PolyCollection object (no additional values, and is also a ScalarMappable)
