### ISSUE TITLE
[MNT]: Switch docs/examples to use Noto Sans CJK instead of WenQuanYi Zen Hei as CJK font

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25724]
### Summary

Some examples use WenQuanYi Zen Hei as CJK (chinese/japanese/korean) font, but it is less convenient to install on macos (#16112); other examples already rely on Noto Sans CJK, which is still available on Homebrew, so we could just as well always rely on that font instead.

### Proposed fix

Replace usage of WenQuanYi Zen Hei by Noto Sans CJK in the docs/galleries.

**Comment by Ayush-mishra-0-0** [comment]
How can I contribute here? Can you plz help?

**Comment by FahadYameen** [comment]
if no one is working on it so can  I start to work in this issue as my first open source contribution?

**Comment by ksunden** [comment]
@FahadYameen this particular issue already has a PR associated with it, perhaps look among our other open issues.
