### ISSUE TITLE
site access; SSL certificate error

### ISSUE THREAD

**Issue by matthiasfabry** [matplotlib/matplotlib#25731]
Obviously, this is not a code issue, but I'm unsure where to report this.

I'm trying to access https://matplotlib.org/, but I'm getting CloudFlare invalid SSL certificate errors (error code 526).
I'm located in Belgium if that's at all relevant.

**Comment by rcomer** [comment]
Thanks @matthiasfabry, it looks like this has also been noted on our [Gitter Chat](https://app.gitter.im/#/room/#matplotlib_matplotlib:gitter.im).  Probably good to have the issue here too as it's a likely place for people to come looking.

**Comment by tacaswell** [comment]
Thank you.  I'm pretty sure we understand the issue and will have it fixed by COB US Eastern time today.

**Comment by Higgs32584** [comment]
What is going on with the site, its still down

**Comment by QuLogic** [comment]
This is now fixed.

**Comment by NATRIST-0** [comment]
the forum is down :(

**Comment by QuLogic** [comment]
Not sure why Let's Encrypt didn't refresh, but the app was rebuilt so it should be good now.
