### ISSUE TITLE
saving map to pdf increases memory usage 5x [Bug]: 

### ISSUE THREAD

**Issue by ozak** [matplotlib/matplotlib#25748]
### Bug summary

Saving a map in pdf format uses 5x the memory compared to jpg or png in some applications. See [this jupyter notebook with the comparison](https://www.dropbox.com/s/cnqgbt12m9v8yzi/memory-usage.ipynb?dl=0)

### Code for reproduction

```python
# Example taken from
# https://www.python-graph-gallery.com/choropleth-map-geopandas-python
# Import the geopandas and geoplot libraries
import geopandas as gpd
import geoplot as gplt
import geoplot.crs as gcrs

# Load the json file with county coordinates
geoData = gpd.read_file('https://raw.githubusercontent.com/holtzy/The-Python-Graph-Gallery/master/static/data/US-counties.geojson')

# Make sure the "id" column is an integer
geoData.id = geoData.id.astype(str).astype(int)

# Remove Alaska, Hawaii and Puerto Rico.
stateToRemove = ['02', '15', '72']
geoData = geoData[~geoData.STATE.isin(stateToRemove)]

# Basic plot with just county outlines
gplt.polyplot(geoData, figsize=(20, 4));

# library
import pandas as pd
import seaborn as sns

# Read file
%memit data = pd.read_csv('https://raw.githubusercontent.com/holtzy/The-Python-Graph-Gallery/master/static/data/unemployment-x.csv') # peak memory: 2678.21 MiB, increment: 0.00 MiB

# Show the distribution of unemployment rate
sns.distplot( data["rate"], hist=True, kde=False, rug=False );

fullData = geoData.merge(data, left_on=['id'], right_on=['id'])
fullData.head(2)

# Initialize the figure
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(16, 12))

# Set up the color sheme:
import mapclassify as mc
scheme = mc.Quantiles(fullData['rate'], k=10)

# Map
gplt.choropleth(fullData, 
    hue="rate", 
    linewidth=.1,
    scheme=scheme, cmap='inferno_r',
    legend=True,
    edgecolor='black',
    ax=ax
);

ax.set_title('Unemployment rate in US counties', fontsize=13);

def map_plot(filetype):
    # Initialize the figure
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(1, 1, figsize=(16, 12))

    # Set up the color sheme:
    import mapclassify as mc
    scheme = mc.Quantiles(fullData['rate'], k=10)

    # Map
    gplt.choropleth(fullData, 
        hue="rate", 
        linewidth=.1,
        scheme=scheme, cmap='inferno_r',
        legend=True,
        edgecolor='black',
        ax=ax
    );

    ax.set_title('Unemployment rate in US counties', fontsize=13);
    plt.savefig('figure.' + filetype, dpi=300, bbox_inches='tight')
    pass

# Memory profile of creating and saving figure (very similar in all 3 types and less than original data
%memit map_plot('pdf') # peak memory: 376.74 MiB, increment: 9.99 MiB
%memit map_plot('png') # peak memory: 506.78 MiB, increment: 123.27 MiB
%memit map_plot('jpg') # peak memory: 528.48 MiB, increment: 18.90 MiB

######
# Now use countries around the world

# Web & file access
import requests
import io

headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'}

url = 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip'
r = requests.get(url, headers=headers)

%memit countries = gpd.read_file(io.BytesIO(r.content)) # peak memory: 2679.46 MiB, increment: 0.97 MiB

# Function to plot
def MyChloropleth(filetype, save=False, edgecolor='white', facecolor='lightgray'):
    #Plot
    ax = gplt.choropleth(
        countries, hue='POP_EST', projection=gcrs.PlateCarree(central_longitude=0.0, globe=None),
        edgecolor='white', linewidth=1,
        cmap='Reds', 
        figsize=(24, 16),
        rasterized=True,
    )
    gplt.polyplot(
        countries, projection=gcrs.PlateCarree(central_longitude=0.0, globe=None),
        edgecolor=edgecolor, facecolor=facecolor,
        ax=ax,
        rasterized=True,
    )
    if save:
        plt.savefig('figure.' + filetype, dpi=300, bbox_inches='tight')
    pass

# Plotting without saving
%memit MyChloropleth('pdf') # peak memory: 3511.76 MiB, increment: 4.16 MiB

# Plotting and saving as pdf
%memit MyChloropleth('pdf', save=True) # peak memory: 16682.68 MiB, increment: 16017.70 MiB

# Plotting and saving as png
%memit MyChloropleth('png', save=True) # peak memory: 3752.54 MiB, increment: 242.16 MiB

# Plotting and saving as jpg
%memit MyChloropleth('jpg', save=True) # peak memory: 3537.41 MiB, increment: 0.30 MiB
```

### Actual outcome

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/650534/233714286-29747181-0bbc-43e7-bcfd-19f0578a6f7c.png">
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/650534/233714308-db943a37-b5d8-4725-b042-157a22ecc4aa.png">
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/650534/233714343-fa578907-7f92-4f17-baa2-19bb7103d9bb.png">
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/650534/233714377-d25c34f8-e7d5-443a-bb6a-dbd96ac953f9.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/650534/233714428-a3bfede1-a68d-41c9-b953-dda173c367b9.png">
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/650534/233714467-fa0a21e9-0d3d-4f90-a147-9de2c2af6e4a.png">
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/650534/233714499-76fe93fe-916b-4612-9bf3-9d3e0caa3521.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/650534/233714531-e8369219-eb62-42df-ac0d-1f60410bd45b.png">

### Expected outcome

The outcome is the same, just memory usage varies incredibly.

### Additional information

I have tried this on various machines and installations with the same result.

### Operating system

OSX/Linux

### Matplotlib Version

3.5.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.8

### Jupyter version

notebook 6.5.3, lab 3.6.3

### Installation

conda

**Comment by jklymak** [comment]
Each artist you rasterize in PDF is painted onto a separate canvas. I'm not sure how choropleth or polyglot work, but it's possible you are making many canvases in the PDF case.  I'd turn rasterize off.

In general, this sort of report is better worked out at https://discourse.matplotlib.org before opening a bug report.  It's also helpful if you can concoct an example that doesn't rely on a downstream libraries (or discuss with them first).  I'm going to close here because I don't think there is a Matplotlib action to take here, but we can re-open if thats incorrect. Thanks.

**Comment by ozak** [comment]
@jklymak You may be right! Removing the `rasterized=True` option decreased memory usage significantly

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/650534/233725197-8f345d6d-c50c-4ad3-aeee-1cdebf21cb3b.png">


Thanks! Strangely the recommendation used to be to use `rasterized=True` to ensure pdf files were smaller. See, e.g., [here](https://stackoverflow.com/questions/10685495/reducing-the-size-of-pdf-figure-file-in-matplotlib). So what would be the best way to get smaller pdf files? `jpg` and `png` are about 300-600K, `pdf` is 9.6MB.
