### ISSUE TITLE
Mplot3d PostScript output wall face colors messed up in output file

### ISSUE THREAD

**Issue by excetara2** [matplotlib/matplotlib#2575]
I have version 1.4.x of matplotlib. The minimal example shows the case below. 

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
plt.savefig('testing.eps')

Written by Benjamin Root as a response on the mailing list but still has not been fixed:
Diving into the eps output, I can tell that the grid lines are being output to the file, but it seems like the color of the gridline matches that particular wall's color, which is why we can't see it.  The odd thing is that the line colors are correct, but for some reason, the face colors are wrong for eps.  Looking at the output for pdf and png, the walls are not shaded nearly as much as it is in eps.  There is probably something messed up in our PS backend that is misinterpreting the grayscale color information it is getting.

**Comment by dennylin93** [comment]
Fix in #7060.

**Comment by tacaswell** [comment]
To follow up, it looks like the issue is that the 'wall' faces have alpha which gets discarded in eps (because eps just does not support alpha).  The grid lines going invisible is probably just a rendering order issue.

**Comment by dennylin93** [comment]
The y-plane and grid lines have the same RGB but different alphas, so they end up being the same colour when rendered in EPS. The order seems to be fine; changing the colour of either of them makes the lines visible.

**Comment by tacaswell** [comment]
@dennylin93 Ah, that makes sense and I now understand your fix.   Thanks!
