### ISSUE TITLE
[Bug]: Plot does not show unless it is resized

### ISSUE THREAD

**Issue by bjmarfito** [matplotlib/matplotlib#25768]
### Bug summary

The plot generated from matplotlib.pyplot does not show automatically. Instead, I need to resize the window plot for it to show.

### Code for reproduction

```python
from matplotlib import pyplot as plt
import numpy as np
a = np.array([1, 7, 8, 12])
b = np.array([9, 6, 2, 5])
plt.figure(1, figsize=(8,4))
plt.axis([0,15,0,10])
plt.plot(a,b)
plt.show()
```

### Actual outcome

<img width="868" alt="actual" src="https://user-images.githubusercontent.com/21336508/234519254-7f77de94-706a-4b03-b8a7-3a6133757b25.png">

### Expected outcome

<img width="928" alt="expected" src="https://user-images.githubusercontent.com/21336508/234519302-3be9a507-e3df-4f39-aba4-0dedd3c8e3e0.png">

### Operating system

macOS 13.3.1

### Matplotlib Version

3.7.1

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.3

### Installation

None

**Comment by tacaswell** [comment]
Are you running this as a stand alone script or by typing into a terminal? If a terminal, which one?

Looks like we are missing a draw command?  My guess is minimizing and the restoring the window should also work as would be adding `plt.gcf().canvas.draw_idle()` right before the `show()`.

**Comment by jklymak** [comment]
And do you use any non-standard window managers (moom, etc)?

**Comment by bjmarfito** [comment]
Hi, sorry for the late response. The problem still persists in my computer. 
@tacaswell, I ran it in a terminal using iTerm. 

@greglucas, I did not used multiple figures. I messed up with the title of the figure in the screenshot. 

@jkl, I used magnet as one of my window managers.

Attaching the screenshots of my terminal and the output after running the plt.show() script.
<img width="912" alt="output" src="https://user-images.githubusercontent.com/21336508/235050914-60d73a8c-5396-4cc4-95f2-b8b2e2b199a6.png">


<img width="653" alt="script_in_terminal" src="https://user-images.githubusercontent.com/21336508/235050898-385269c9-1618-4ace-84ec-3e7dd5d67abd.png">

**Comment by bjmarfito** [comment]
Screenshot after resizing the plot.
<img width="995" alt="resize" src="https://user-images.githubusercontent.com/21336508/235051064-b42f291e-d2f9-49ec-9550-55f16a14a585.png">

**Comment by jklymak** [comment]
I'd suggest turning magnet off and seeing if the problem persists.

**Comment by bjmarfito** [comment]
@jklymak, I turned off magnet and still the problem persists.

**Comment by wrnod** [comment]
Can confirm this problem exists on Intel Macos 13.3.1, Python 3.11.3, matplotlib 3.7.1. Interestingly in the given example the problem does not exist for me, but in other code.

**Comment by greglucas** [comment]
Unfortunately, I still can't reproduce the issue. Is there something external we need to install to see this or a system setting we need to enable? I've tried running on an external monitor and HiDPI display and both work as expected for me.

**Comment by bjmarfito** [comment]
Thank you all. This issue is not present anymore after I upgraded my arm64 Mac to macOS 13.4.

**Comment by wrnod** [comment]
This is not resolved. Updating to 13.4 did not resolve the issue.
<img width="642" alt="Screenshot 2023-06-11 at 13 57 13" src="https://github.com/matplotlib/matplotlib/assets/122595287/a947cfb9-b3ff-49dd-9d8e-119d619d4a7f">

**Comment by jklymak** [comment]
@wrnod you and OP may have some system setting or utility that is causing the problem.  It's hard for us to debug without more information.

**Comment by bjmarfito** [comment]
Hi @wrnod, I will reopen this issue until it is resolved.

**Comment by greglucas** [comment]
@wrnod are you able to provide any additional information to help with debugging? None of the maintainers are able to reproduce this which makes it really hard to track down what is going wrong. If you have explicit steps you're taking, or previous versions that work and ones that caused issues that would be valuable information.

1. Are you calling a test script from the command line, running interactively, using Jupyter, ... (give explicit steps)
2. What Python are you using? Is it installed from Brew, Conda, or manually installed, ...
3. Are you using a window manager on the system?
4. Are there any other system settings that come to your mind on possibly making a difference here?

**Comment by wrnod** [comment]
> @wrnod are you able to provide any additional information to help with debugging? None of the maintainers are able to reproduce this which makes it really hard to track down what is going wrong. If you have explicit steps you're taking, or previous versions that work and ones that caused issues that would be valuable information.
> 
>     1. Are you calling a test script from the command line, running interactively, using Jupyter, ... (give explicit steps)
> 
>     2. What Python are you using? Is it installed from Brew, Conda, or manually installed, ...
> 
>     3. Are you using a window manager on the system?
> 
>     4. Are there any other system settings that come to your mind on possibly making a difference here?

Thank you for the follow-up questions. Unfortunately I can't share the code, since it is proprietery. I will try to isolate the issue when I have some time. The issue started for me after updgrading to Python 3.11.3 and matplotlib 3.7.1.

**Comment by jklymak** [comment]
I'll close for lack of further details, but feel free to request a re-open.
