### ISSUE TITLE
[Bug]: scatter unfilled marker with dashed linestyle produces fine solid lines connecting the dashes in pdf output

### ISSUE THREAD

**Issue by zizard** [matplotlib/matplotlib#25795]
### Bug summary

When plotting with scatter with an unfilled marker and dashed linestyle and pdf output, it produces a very fine solid line connecting the dashes.

### Code for reproduction

```python
import matplotlib
matplotlib.use('pdf')
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.scatter(3.0, 4.0, s=20000.0, marker='_', linestyle='--')
fig.savefig('dmp_test.pdf')
```

### Actual outcome

This code produces a dashed line with an extremely fine connecting solid line in the pdf output, visible when zoomed in. The image below is a cropped screenshot of the pdf zoomed in to the marker.
![dashedmarker](https://user-images.githubusercontent.com/54122132/235382777-f4d89b03-3156-404b-ac36-cfb1eced9d07.png)

### Expected outcome

I expected a dashed line marker without any fine solid line.

### Additional information

I get the same result for other unfilled markers. But filled markers with no fill colour work as expected, with no fine solid line.
Messing with face colour or edge colour doesn't seem to do anything.
There is no connecting line for eps output, neither for png, nor for svg.

### Matplotlib Version

3.7.1

### Python version

3.9.12

### Installation

pip

**Comment by QuLogic** [comment]
I cannot reproduce this in Evince, Firefox, or importing into Inkscape. This seems to be an issue specific to your PDF viewer.

**Comment by chahak13** [comment]
Can't reproduce on Zathura either.

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open.
