### ISSUE TITLE
[Bug]: Memory leak in constrained_layout

### ISSUE THREAD

**Issue by H4dr1en** [matplotlib/matplotlib#25819]
### Bug summary

`constrained_layout=True` produces a memory leak.

### Code for reproduction

```python
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
from tqdm import tqdm

for i in tqdm(range(1000), total=1000):
    fig = plt.figure(constrained_layout=True, figsize=(10, 10))
    gs = fig.add_gridspec(2, 4)
    ax = fig.add_subplot(gs[:, :2])
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    fig.savefig('test.png')
    plt.close("all")
```

### Actual outcome

With `constrained_layout=True`:

![fails](https://user-images.githubusercontent.com/16240134/236440797-39d2d291-3f61-4098-830b-1651406b38a4.png)

### Expected outcome

With `constrained_layout=False`:

![works](https://user-images.githubusercontent.com/16240134/236440878-f40d1079-f076-4e3f-915b-0718e4b7efbe.png)

### Additional information

Not tested in earlier versions.

### Operating system

Ubuntu

### Matplotlib Version

3.7.1

### Matplotlib Backend

agg

### Python version

3.8

### Installation

pip

**Comment by tacaswell** [comment]
I can confirm this (but less scientifically, I just watched the reported memory usage in btop).

**Comment by jklymak** [comment]
Agreed this is leaking.  Not sure why

```python
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
import gc
#from tqdm import tqdm

import linecache
import os
import tracemalloc

def display_top(snapshot, key_type='lineno', limit=10):
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
        tracemalloc.Filter(False, "<unknown>"),
    ))
    top_stats = snapshot.statistics(key_type)

    print("Top %s lines" % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        frame = stat.traceback[0]
        print("#%s: %s:%s: %.1f KiB"
              % (index, frame.filename, frame.lineno, stat.size / 1024))
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print('    %s' % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print("%s other: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print("Total allocated size: %.1f KiB" % (total / 1024))

tracemalloc.start()


for i in range(1000):
    fig, ax = plt.subplots(constrained_layout=True, figsize=(10, 10))
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    fig.draw_without_rendering()
    plt.close(fig)
    gc.collect()


snapshot = tracemalloc.take_snapshot()
display_top(snapshot)
```

yields the following.  Perhaps folks more cognizant of python types will know why that may cause problems.  Do dictionaries have some sort of memory-releasing problem?  I think its possible to rewrite layoutgrid without using dictionaries...

```
Top 10 lines
#1: /Users/jklymak/matplotlib/lib/matplotlib/_layoutgrid.py:96: 1343.8 KiB
    self.margin_vals[todo] = np.zeros(nrows)
#2: /Users/jklymak/matplotlib/lib/matplotlib/_layoutgrid.py:104: 1062.5 KiB
    self.margins[todo] = [Variable(f'{sn}margins[{todo}][{i}]')
#3: /Users/jklymak/matplotlib/lib/matplotlib/_layoutgrid.py:89: 1062.5 KiB
    self.margins[todo] = [Variable(f'{sn}margins[{todo}][{i}]')
#4: /Users/jklymak/matplotlib/lib/matplotlib/_layoutgrid.py:76: 875.0 KiB
    self.margin_vals[todo] = np.zeros(ncols)
#5: /Users/jklymak/matplotlib/lib/matplotlib/text.py:69: 832.0 KiB
    return _get_text_metrics_with_cache_impl(
#6: /Users/jklymak/mambaforge/envs/mpl-dev/lib/python3.11/copyreg.py:105: 593.0 KiB
    return cls.__new__(cls, *args)
#7: /Users/jklymak/matplotlib/lib/matplotlib/_layoutgrid.py:95: 453.1 KiB
    self.margins[todo] = np.empty((nrows), dtype=object)
#8: /Users/jklymak/matplotlib/lib/matplotlib/_constrained_layout.py:168: 273.5 KiB
    layoutgrids[fig] = mlayoutgrid.LayoutGrid(parent=rect, name='figlb')
#9: /Users/jklymak/matplotlib/lib/matplotlib/_constrained_layout.py:210: 273.5 KiB
    layoutgrids[gs] = mlayoutgrid.LayoutGrid(
#10: /Users/jklymak/mambaforge/envs/mpl-dev/lib/python3.11/copy.py:280: 270.5 KiB
    y.__dict__.update(state)
```

**Comment by tacaswell** [comment]
Before we start speculating on there being a bug in Python's memory management, we should look at our caching 

https://github.com/matplotlib/matplotlib/blob/f1a8b92e64479ed75b17e461d646c2587cd7e5af/lib/matplotlib/text.py#L65-L77

looks like it is keeping a ~4K element cache and I suspect we may not hit that in the non-constrained case.

**Comment by timhoffm** [comment]
> Do dictionaries have some sort of memory-releasing problem?

I would be very surprised if that was the case. Dicts are so fundamental (not only as a popular data type but also as the mechanism behind obeject attributes) that a memory leak there would for sure have already been notice.

**Comment by greglucas** [comment]
The `LayoutGrid` is not being collected, but I can't see what is keeping it alive by tracking the backreferences. Is this a possible issue in the KiwiSolver layer with those Variables or solver keeping things alive?

```
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
import objgraph
import random

for i in range(25):
    fig = plt.figure(constrained_layout=True, figsize=(10, 10))
    gs = fig.add_gridspec(2, 4)
    ax = fig.add_subplot(gs[:, :2])
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    fig.savefig('test.png')
    plt.close("all")
    objgraph.show_growth(limit=50)

objgraph.show_backrefs(
    random.choice(objgraph.by_type('LayoutGrid')),
    filename='chain.png', max_depth=50, refcounts=True)
```

**Comment by QuLogic** [comment]
I guess I'd point out that there should be a `gc.collect` in the loop, but it doesn't actually fix or reduce anything for me. The growth I see is even per loop at:
```
Variable            128       +64
list               5009       +32
dict               6903       +11
FontProperties       58        +7
LayoutGrid            4        +2
weakref            2502        +1
tuple              6910        +1
```
Exporting all backrefs for `LayoutGrid` show the one for the gridspec and one for the figure. But the ref counts are as you've found larger than the number of objects that `objgraph` finds pointing to it.

You can also cut down the inside of the loop to:
```python
    fig = plt.figure(constrained_layout=True, figsize=(10, 10))
    gs = fig.add_gridspec(2, 4)
    ax = fig.add_subplot(gs[:, :2])
    fig.get_layout_engine().execute(fig)
    plt.close("all")
```
but without the Axes or the gridspec, or execute, then there's no leak.

So you can actually change the loop to:
```python
fig = plt.figure(constrained_layout=True, figsize=(10, 10))
gs = fig.add_gridspec(2, 4)
ax = fig.add_subplot(gs[:, :2])
for i in range(25):
    fig.get_layout_engine().execute(fig)
    objgraph.show_growth(limit=5000)
```
which produces:
```
Variable        128       +64
list           4867       +32
dict           6615        +4
LayoutGrid        4        +2
```

`LayoutGrid` contains a reference to its parent rect _or_ `LayoutGrid`, and `LayoutGrid` also contains a NumPy array of children. As multiple `gc.collect()` in the loop do nothing, I suspect that this cross into C-managed arrays is causing Python to be unable to see the cycle.

**Comment by QuLogic** [comment]
I can also confirm that deleting an end of the cycle after `execute` will fix the leak. But I think there's a better fix of removing the cycle altogether to investigate.
