### ISSUE TITLE
[Bug]: Shouldn't the default colormap for tableau-colorblind10 be Cividis?

### ISSUE THREAD

**Issue by Gabriel-p** [matplotlib/matplotlib#25820]
### Bug summary

According to [this post from 2018](https://matplotlib.org/stable/users/prev_whats_new/whats_new_2.2.html#new-style-colorblind-friendly-color-cycle)  `tableau-colorblind10t` is the colorblind friendly cycle and `Cividis` is the colorblind friendly colormap. But if I use the `tableau-colorblind10t` style the colormap used by default is not `Cividis`.

Shouldn't it be?

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('tableau-colorblind10')

fig, ax = plt.subplots()
pcm = ax.pcolormesh(np.random.rand(32,32))
fig.colorbar(pcm)
plt.show()
```

### Actual outcome

![Captura de pantalla de 2023-05-05 10 56 03](https://user-images.githubusercontent.com/6054951/236477964-f6c38f2b-19f5-410f-809d-2f2753e33806.png)

### Expected outcome

![Captura de pantalla de 2023-05-05 10 56 51](https://user-images.githubusercontent.com/6054951/236478113-f7b778bc-20c6-474b-8eca-19238ba00fc6.png)

### Matplotlib Version

3.6.2

### Matplotlib Backend

QtAgg

### Python version

Python 3.10.9

### Installation

conda

**Comment by WeatherGod** [comment]
colormaps and color cycles are two different things. Colormaps operate on a
continuous scale, while color cycles are discrete. You want color cycles to
have colors that are as far apart from each other as possible in order to
be distinguishable.

**Comment by Gabriel-p** [comment]
Yes but the `tableau-colorblind10t` style is presented as colorblind friendly and does not use a colorblind friendly colormap. The fact that such a colormap is available makes this decision even more confusing.

**Comment by jklymak** [comment]
tableau-colorblind10 is a style, which can include a default colormap via `image.cmap`.  However, we are very conservative on changing styles as they are considered API.  In this case `viridis` is supposed to be colourblind friendly, so it's not clear there is a lot of justification to change the style to use `cividis`.

**Comment by Gabriel-p** [comment]
> viridis is supposed to be colourblind friendly

I was not aware of this. This fact makes this a non issue so closing now, thank you!
