### ISSUE TITLE
[Doc][Examples Gallery]: Side Navigation Section breaks on Animation examples

### ISSUE THREAD

**Issue by codingtosh** [matplotlib/matplotlib#25836]
### Documentation Link

https://matplotlib.org/devdocs/gallery/animation/index.html

### Problem

Steps: 
1. Go to [Animations](https://matplotlib.org/devdocs/gallery/animation/index.html) from the navigation section on the left hand side.
2. Click on the animation examples either from the side navigation section or from the thumbnails in the main page. 

**Expected Outcome:** Side navigation section continues to show the links of examples gallery
![expected behavior](https://user-images.githubusercontent.com/81802035/236882377-8cc7912b-d0c0-428c-9744-9ebd95f1a6de.png)

**Actual Outcome:** Side navigation section shows the matplotlib API reference links instead.
 
![unexpected behavior](https://user-images.githubusercontent.com/81802035/236882402-21dc4766-5aec-4b65-ab9a-a138ecbc5294.png)

**Result:** UX is negatively affected, navigation is inconsistent compared to everywhere else in the documentation.

**Note:** Not reproducible for these examples, breaks for all other animation examples: 
- [pyplot animation](https://matplotlib.org/devdocs/gallery/animation/animation_demo.html)
- [Multiple axes animation](https://matplotlib.org/devdocs/gallery/animation/multiple_axes.html)
- [pasuing and resuming an animation](https://matplotlib.org/devdocs/gallery/animation/pause_resume.html)
- [animated scatter saved as gif](https://matplotlib.org/devdocs/gallery/animation/simple_scatter.html)

**Possible reasons:** Animation renderer could have something to do with it, but then again, the above 4 examples don't reflect that. Needs root cause analysis.  

**Reproducible in** Mozilla Firefox, Edge as well as Chrome. Reproducible across devdocs, stable and the older versions.

**Actionability:** The scope is limited to the Animation examples in the Examples Gallery as far as I have found out. For now, this issue isn't critical or high priority.  

### Suggested improvement

The section navigation div should contain the toctree of the Examples gallery links, not the API reference links. 
Fix  should have this result:
Unexpected div: 
![unexpected div](https://user-images.githubusercontent.com/81802035/236885741-db45d37a-04e6-493a-a846-6540e1fe85dd.png)
should be more like the expected div: 
![expected div](https://user-images.githubusercontent.com/81802035/236885811-fa09729c-8eb1-4477-9167-a60ce6c8744c.png)

**Comment by codingtosh** [comment]
@story645 @melissawm This was the issue we discussed. Web dev isn't my forte, but should be labelled good-first-issue imo.

**Comment by ksunden** [comment]
I have the (unproven) suspicion that all that is required is changing one of the following two headings (plus perhaps checking links to them):

https://github.com/matplotlib/matplotlib/blob/1539614d4c81dad47970e34a76eb5c377146ea7a/galleries/examples/animation/README.txt#L5-L6

https://github.com/matplotlib/matplotlib/blob/1539614d4c81dad47970e34a76eb5c377146ea7a/doc/api/animation_api.rst?plain=1#L15-L16

Marking as good first issue.

**Comment by sajal1123** [comment]
Hi @codingtosh, I was exploring the code and noticed that the autosummary directive in `animation_api.rst` does not follow the template provided in `autosummary.rst`. Could this be the source of this issue?
<img width="1306" alt="Screenshot 2023-05-10 at 1 57 08 AM" src="https://github.com/matplotlib/matplotlib/assets/113067506/de8de6ed-4095-43e4-aa5c-0ceb899bdf04">

I am new to this repository(and open source), so apologies if I'm missing something trivial.

**Comment by codingtosh** [comment]
Hi @sajal1123 Thanks for looking into this, welcome to the community and open source in general. Have fun! 

As a starting point, you should go over  [this](https://matplotlib.org/devdocs/devel/contributing.html) and then [this](https://github.com/matplotlib/matplotlib/blob/main/doc/devel/documenting_mpl.rst) to help you set up the environment and test the changes locally. 

You can also join the matplotlib gitter server and get in the the [incubator channel](https://matplotlib.org/devdocs/devel/contributing.html#contributor-incubator)  where members can help you through with your first PR. 

I'm new to this community and the project as well,  you can wait for maintainers to comment on your PR or tag @melissawm @story645 @ksunden @tacaswell as they're seasoned contributors in this community and will be able to review and merge your changes in production.

Generally, you should ask the maintainers to assign you a specific issue before you open the PR as this prevents multiple contributors from working on the same issue. But according to the contributing guide above, there is no such practice here in matplotlib. So you can claim an issue simply by commenting on this issue thread and then opening the PR. It will be good to reference this issue number in the PR you open to provide context to the reviewers.  Make sure the issue number is prefixed by a pound sign(#) which will create the hyperlink on github.

Another useful practice is to use `git blame` in your cli to see who has authored the lines you intend to change and the commit they did it in(helps you understand the context of the change).  Then you can tag them in your PR as well. Alterantively, you can use the github platform to see the authorship info like [here](https://github.com/matplotlib/matplotlib/blame/main/doc/api/axes_api.rst#L262). 

While I may not be able to help you directly with the changes, let me know if you face any blockers pertaining to git or open source in general.

**Comment by QuLogic** [comment]
Fixed by #25977.
