### ISSUE TITLE
[Bug]: show() or savefig() freeze Python 3.8, 100% CPU

### ISSUE THREAD

**Issue by unixb0y** [matplotlib/matplotlib#25849]
### Bug summary

I'm running Python3.8 on a Ubuntu 18.04.6 LTS (32-bit) box.
Tried different Matplotlib releases, even back to version 3.0.3, always the same issue. CPU goes to 100%, empty Window pops up (in case of `show`) and Python freezes up; have to kill it manually.

### Code for reproduction

```python
# Example 1
import matplotlib.pyplot as plt
plt.plot([1,2,3],[3,0,3])
plt.show()

# Example 2
import matplotlib.pyplot as plt
plt.plot([1,2,3],[3,0,3])
plt.savefig("test.png")
```

### Actual outcome

Freeze

### Expected outcome

Plot as pop-up / file on disk

### Operating system

Ubuntu 18.04.6 LTS

### Matplotlib Version

3.0.3 up to 3.7.0

### Matplotlib Backend

TkAgg

### Python version

Python 3.8.0

### Installation

pip

**Comment by unixb0y** [comment]
Bump

**Comment by jklymak** [comment]
Please try a hello world tk program:

```
# Python tkinter hello world program

from tkinter import *

root = Tk()
a = Label(root, text ="Hello World")
a.pack()

root.mainloop()
```

if that freezes then your tk installation is broken.  You can also try with Qt instead.

**Comment by rcomer** [comment]
I am going to close this one as it is not clear whether the problem was with Matplotlib.  Also, as of Matplotlib v3.8 we no longer support Python v3.8, so there is nothing we could do here even if the problem was in Matplotlib.
