### ISSUE TITLE
[MNT]: add tests for nargs_error

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#25864]
Add tests that check that `nargs_error` gets raised correctly for `legend`, `stem`, `pcolorfast`, and `cycler` from #25863. It's a good first issue since the conditions that should trigger the error can be ported to the tests.

**Comment by turnipseason** [comment]
Hi! I wanted to try this out to practice writing tests. I haven't really done it before, so I wanted to ask before proceeding. Should it look something like this? 

```
def test_nargs_stem():
    import matplotlib.pyplot as plt
    import numpy as np

    with pytest.raises(TypeError):
        x = np.linspace(0.1, 2 * np.pi, 41)
        y = np.exp(np.sin(x))

        plt.stem(x, 123, 434, y)
```

Thanks in advance :)
