### ISSUE TITLE
[Bug]: dot missing from "$i$", "$j$" markers

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25903]
### Bug summary

Matplotlib supports mathtext expressions as custom markers, but using "$i$" or "$j$" as a marker results in dotless i and j (even though the dot is correctly present in normal mathtext uses).

### Code for reproduction

```python
from pylab import *; scatter([0], [0], marker="$j$"); text(.01, .01, "$j$")
```

### Actual outcome

![test](https://github.com/matplotlib/matplotlib/assets/1322974/4a173afc-1243-46c5-99c4-08bcc02947aa)

### Expected outcome

Dot not missing from i/j

### Operating system

macos

### Matplotlib Version

3.8.0.dev1065+g10e8bf134c

### Matplotlib Backend

qtagg

### Python version

3.11

### Jupyter version

ENOSUCHLIB

### Installation

git checkout

**Comment by QuLogic** [comment]
It's there:
```
from pylab import *; scatter([0], [0], marker="$ij$", s=500); text(.01, .01, "$ij$"); show()
```
![Capture](https://github.com/matplotlib/matplotlib/assets/302469/4c7e1940-42aa-4d3e-b55b-34aac1901eb3)
I think it's just getting hidden by the edge:
```
from pylab import *; scatter([0], [0], marker="$ij$", linewidth=0); text(.01, .01, "$ij$"); show()
```
![Capture](https://github.com/matplotlib/matplotlib/assets/302469/df03f28e-04d4-4457-963b-922bec81672c)

**Comment by anntzer** [comment]
Oops!
