### ISSUE TITLE
[ENH]: Add test for annotate(textcoods="offset fontsize")

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25907]
### Problem

annotate() currently supports (in particular) specifying the position of the text in "offset points" and "offset pixels" relative to the position of the point being annotated.
It would be nice to also support "offset font" (perhaps spelt "offset fontsize", but I'm not sure the extra verbosity helps), which would be a offset but in units of the fontsize (of the annotation text).  This is useful e.g. when using annotate() to generate subplot labels (#25905), where it makes sense to say "I want to put the label at the top right of the axes, offset from the corner by half-a-fontsize rightwards and downwards" (`xytext=(.5, -.5), xycoords="offset font"`).

-----

As noted below this is actually already present (and has now been documented as such), but adding tests would be nice.

**Comment by anntzer** [comment]
No, because that requires measuring the actual width of the glyphs, which depends on the actual text.

**Comment by saranti** [comment]
Isn't that what this `fontisize` parameter does?
https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/text.py#L1510

**Comment by oscargus** [comment]
It is not tested though, so good actions here are probably to add a test to make sure that it does what it appears to, and to add documentation for it (as well as `offset fraction`). Maybe, update an example with it as well.

A secondary task may be to extend `OffsetFrom` to handle `fraction` and `fontsize` in case of an `Artist`. Although one can just as well open an separate issue for that.

**Comment by saranti** [comment]
`offset fraction` is returning an AttributeError at the moment because the bbox isn't being passed to `bbox0`. I was able to get it working by passing it here on line 1500 but it seems more like a hack. I also don't know if it's supposed to be a fraction of the figure or the axes?
> https://github.com/matplotlib/matplotlib/blob/ffd3b12969e4ab630e678617c68492bc238924fa/lib/matplotlib/text.py#L1498-L1500

**Comment by oscargus** [comment]
You are correct. Didn't think that far, just looked at the possible combinations. One would need `offset axes fraction` etc, but probably not worth it.

**Comment by anntzer** [comment]
This should mostly be handled by #25940, modulo tests.

**Comment by niranjank2022** [comment]
> No, because that requires measuring the actual width of the glyphs, which depends on the actual text.
> 
> I guess it may be a good idea, though, to rewrite the rainbow_text example using annotate(), further taking advantage of annotate()'s ability to take a Artist (i.e., its extent) as transform: each word can just be positioned at the bottom right corner relative to the previous one. (Support for the vertical text case is left as an exercise to the reader.) (Note in particular that the current version of rainbow_text seems, AFAICT, not robust against dpi changes; the approach proposed above may be better in that respect.)

"
_annotate()'s ability to take a Artist (i.e., its extent) as transform:_
"
I don't understand what are you trying to say by this. Do we have to create **Artist object (matplotlib.artist.Artist)** with required properties and assign it to the keyword argument **transform**?
