### ISSUE TITLE
[Doc]: Rewrite rainbow_text example to use annotate()

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25941]
### Documentation Link

https://matplotlib.org/stable/gallery/text_labels_and_annotations/rainbow_text.html

### Problem

As noted in https://github.com/matplotlib/matplotlib/issues/25907#issuecomment-1552641490, the rainbow_text example can likely be rewritten in a simpler fashion using annotate(), similarly to #25905, more simply than with explicit offset_copies.

### Suggested improvement

Rewrite the example using annotate().

**Comment by niranjank2022** [comment]
I would like to work on this. Please assign me this task.

**Comment by niranjank2022** [comment]
I went through the Contributing Guidelines, it is mentioned that we can create PR and work on it. But, I have a doubt, which branch should I have to use for PR? Please help!

**Comment by rcomer** [comment]
Thanks for your interest in contributing @niranjank2022!  You should create a new branch to make the change.  We have some workflow guidance here:
https://matplotlib.org/devdocs/devel/development_workflow.html

**Comment by niranjank2022** [comment]
Thank you. I will create a PR once I finish my changes, by tomorrow._

**Comment by Mubin17** [comment]
```python
import matplotlib.pyplot as plt

def rainbow_text(x, y, strings, colors, orientation='horizontal',
                 ax=None, **kwargs):
    """
    Take a list of *strings* and *colors* and place them next to each
    other, with text strings[i] being shown in colors[i].

    Parameters
    ----------
    x, y : float
        Text position in data coordinates.
    strings : list of str
        The strings to draw.
    colors : list of color
        The colors to use.
    orientation : {'horizontal', 'vertical'}
    ax : Axes, optional
        The Axes to draw into. If None, the current axes will be used.
    **kwargs
        All other keyword arguments are passed to plt.annotate(), so you can
        set the font size, family, etc.
    """
    if ax is None:
        ax = plt.gca()
    
    assert orientation in ['horizontal', 'vertical']
    if orientation == 'vertical':
        kwargs.update(rotation=90, verticalalignment='bottom')
    
    for s, c in zip(strings, colors):
        ax.annotate(s + " ", (x, y), color=c, **kwargs)
        if orientation == 'horizontal':
            x += 0.1
        else:
            y += 0.1

words = "all unicorns poop rainbows ! ! !".split()
colors = ['red', 'orange', 'gold', 'lawngreen', 'lightseagreen', 'royalblue',
          'blueviolet']
plt.figure(figsize=(6, 6), dpi=100)
rainbow_text(0.1, 0.05, words, colors, size=18)
rainbow_text(0.05, 0.1, words, colors, orientation='vertical', size=18)
plt.show()
```
<img width="526" alt="Screenshot 2023-05-26 at 12 22 40 AM" src="https://github.com/matplotlib/matplotlib/assets/48038715/fd9f697a-7d53-41d6-890e-5b4e1c03b887">

@anntzer The code above is my attempt to rewrite rainbow_text simpler fashion using annotate(), however, I am having an issue formatting text appropriately within the figure. Do have any suggestions on how can I fix that? Thanks

**Comment by anntzer** [comment]
I don't have the actual implementation written, figuring that out is the point of the issue.

**Comment by anntzer** [comment]
> since decomposing text position is hard

Really not so much.  The implementation is basically
```python
from pylab import *

t0 = text(.1, .1, "hello", c="C0")
t1 = annotate(
    "world",
    xy=(1, 0), xycoords=t0,  # Immediately to the left of t0.
    xytext=(.5, 0), textcoords="offset fontsize",  # Shifted by half a fontsize (for spacing).
    va="bottom", c="C1")
...
show()
```
One just needs to wrap this in a proper loop over the words and figure out the correct alignment flags for the vertical case.

> Recolor the pixel image with a continuos gradient and write it back?

That's more or less already showcased at https://matplotlib.org/stable/gallery/text_labels_and_annotations/demo_text_path.html.

**Comment by timhoffm** [comment]
> That's more or less already showcased 

👍 

Isn‘t that enough then? A rainbow-by-word coloring doesn’t seem too useful. Maybe replace  this example by one that colors single words in a text? (I assume that would also need the proposed annotate pattern)

**Comment by anntzer** [comment]
I agree the rainbow-by-word example is not really useful in itself indeed (except for the fact that it produces selectable text in pdf output, which is a slightly niche requirement for the usecase here), but demo-ing positioning-relative-to-another artist (as in the implementation I suggest) is nice (IMO).
Perhaps this example could just include both approaches.
