### ISSUE TITLE
[ENH]: could there be a long-term stable API to access the log base from a SymLogNorm object ?

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/matplotlib#25946]
### Problem

As of matplotlib 3.7, `matplotlib.colors.SymLogNorm` instances expose their `linthresh` parameter publicly, but not their `base`, though it is still possible to retrieve it via private attributes. For illustration:

```python
from matplotlib.colors import SymLogNorm

sln = sln = SymLogNorm(linthresh=1, base=5)
print(f"{sln.linthresh=}, {sln._trf.base=}") 
```
outputs
```
sln.linthresh=1, sln._trf.base=5
```

yt has custom routines to determine colorbar ticks for symlog norms, so it needs to know how the norm was parametrised.
At the moment there is no public API to retrieve the `base` parameter, so it cannot be done in a future-proof fashion.

### Proposed solution

It suffices to re-expose the attribute as is already done for `linthresh`

```patch
diff --git a/lib/matplotlib/colors.py b/lib/matplotlib/colors.py
index 434bb54235..f4939fd1a7 100644
--- a/lib/matplotlib/colors.py
+++ b/lib/matplotlib/colors.py
@@ -1844,6 +1844,14 @@ class SymLogNorm(Normalize):
     def linthresh(self, value):
         self._scale.linthresh = value

+    @property
+    def base(self):
+        return self._trf.base
+
+    @base.setter
+    def base(self, value):
+        self._trf.base = value
+

 @make_norm_from_scale(
     scale.AsinhScale,
```

would this change be acceptable ?

**Comment by anntzer** [comment]
I *think* it would be better for scale-derived norms to gain a `get_scale()` method (name up to bikeshedding), and then you can just do `norm.get_scale().base`.  These norms are just thin wrappers around the corresponding scales anyways and I'd rather not copy-paste all properties present on the scale up one level to the norm.

**Comment by neutrinoceros** [comment]
I agree that this is a better solution.
I note that the `Axis` class already has a `get_scale` method, which returns a `str`, so it *may* be confusing to reuse the name. A read-only `scale` property (no setter method) would work too and avoid this slight concern.

**Comment by neutrinoceros** [comment]
Turns out I don't need it in the context I thought I did: I'm already able to retrieve everything I need using only public API, I just have to get down the attribute tree from the axis object rather than the norm.

AFAIC this can be closed as "wont fix", but I'll leave it at the discretion of maintainers.

**Comment by timhoffm** [comment]
Thanks for the reply. As long as nobody calls for the proposed additional API, we won't add it. I'll close as "not planned". Anybody, please speak up if you see a need for this. We will then reconsider.
