### ISSUE TITLE
[Bug]: A colormap named "shiftedcmap" is already registered.

### ISSUE THREAD

**Issue by firatgundem** [matplotlib/matplotlib#25953]
### Bug summary

Hello,
I am trying to create a map based on an MGWR analysis and I used matplotlib.colors to visualize varying coefficients.  But I kept getting an error "A colormap named "shiftedcmap" is already registered." and could not figure it out. I am new to python and could you please help me to solve it? The codes are below: 

### Code for reproduction

```python
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(45,20))
ax0 = axes[0]
ax0.set_title('GWR Percent Foreign Born Surface (BW: ' + str(gwr_bw) +')', fontsize=40)
ax1 = axes[1]
ax1.set_title('MGWR Percent Foreign Born Surface (BW: ' + str(mgwr_bw[1]) +')', fontsize=40)
cmap = plt.cm.seismic
gwr_min = georgia_shp['gwr_fb'].min()
gwr_max = georgia_shp['gwr_fb'].max()
mgwr_min = georgia_shp['mgwr_fb'].min()
mgwr_max = georgia_shp['mgwr_fb'].max()
vmin = np.min([gwr_min, mgwr_min])
vmax = np.max([gwr_max, mgwr_max])

if (vmin < 0) & (vmax < 0):
    cmap = truncate_colormap(cmap, 0.0, 0.5)
elif (vmin > 0) & (vmax > 0):
    cmap = truncate_colormap(cmap, 0.5, 1.0)

cmap = shift_colormap(cmap, start=0.0, midpoint=1 - vmax/(vmax + abs(vmin)), stop=1.)
    
sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=vmin, vmax=vmax))

georgia_shp.plot('gwr_fb', cmap=sm.cmap, ax=ax0, vmin=vmin, vmax=vmax, **{'edgecolor':'black', 'alpha':.65})
if (gwr_filtered_t[:,1] == 0).any():
    georgia_shp[gwr_filtered_t[:,1] == 0].plot(color='lightgrey', ax=ax0, **{'edgecolor':'black'})

georgia_shp.plot('mgwr_fb', cmap=sm.cmap, ax=ax1, vmin=vmin, vmax=vmax, **{'edgecolor':'black', 'alpha':.65})
if (mgwr_filtered_t[:,1] == 0).any():
    georgia_shp[mgwr_filtered_t[:,1] == 0].plot(color='lightgrey', ax=ax1, **{'edgecolor':'black'})
    
fig.tight_layout()    
fig.subplots_adjust(right=0.9)
cax = fig.add_axes([0.92, 0.14, 0.03, 0.75])
sm._A = []
cbar = fig.colorbar(sm, cax=cax)
cbar.ax.tick_params(labelsize=50) 
ax0.get_xaxis().set_visible(False)
ax0.get_yaxis().set_visible(False)
ax1.get_xaxis().set_visible(False)
ax1.get_yaxis().set_visible(False)
plt.show()
```

### Actual outcome

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[84], line 22
     19     cmap = truncate_colormap(cmap, 0.5, 1.0)
     20 #Otherwise, there are positive and negative values so the colormap so zero is the midpoint
     21 else:
---> 22     cmap = shift_colormap(cmap, start=0.0, midpoint=1 - vmax/(vmax + abs(vmin)), stop=1.)
     24 sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=vmin, vmax=vmax))
     26 georgia_shp.plot('gwr_SEGE_Skor', cmap=sm.cmap, ax=ax0, vmin=vmin, vmax=vmax, **{'edgecolor':'black', 'alpha':.65})

File ~\anaconda3\lib\site-packages\mgwr\utils.py:56, in shift_colormap(cmap, start, midpoint, stop, name)
     53     cdict['alpha'].append((si, a, a))
     55 new_cmap = mpl.colors.LinearSegmentedColormap(name, cdict)
---> 56 plt.register_cmap(cmap=new_cmap)
     58 return new_cmap

File ~\anaconda3\lib\site-packages\matplotlib\_api\deprecation.py:200, in deprecated.<locals>.deprecate.<locals>.wrapper(*args, **kwargs)
    198 def wrapper(*args, **kwargs):
    199     emit_warning()
--> 200     return func(*args, **kwargs)

File ~\anaconda3\lib\site-packages\matplotlib\cm.py:263, in register_cmap(name, cmap, override_builtin)
    259 # override_builtin is allowed here for backward compatibility
    260 # this is just a shim to enable that to work privately in
    261 # the global ColormapRegistry
    262 _colormaps._allow_override_builtin = override_builtin
--> 263 _colormaps.register(cmap, name=name, force=override_builtin)
    264 _colormaps._allow_override_builtin = False

File ~\anaconda3\lib\site-packages\matplotlib\cm.py:136, in ColormapRegistry.register(self, cmap, name, force)
    132 if name in self:
    133     if not force:
    134         # don't allow registering an already existing cmap
    135         # unless explicitly asked to
--> 136         raise ValueError(
    137             f'A colormap named "{name}" is already registered.')
    138     elif (name in self._builtin_cmaps
    139             and not self._allow_override_builtin):
    140         # We don't allow overriding a builtin unless privately
    141         # coming from register_cmap()
    142         raise ValueError("Re-registering the builtin cmap "
    143                          f"{name!r} is not allowed.")

ValueError: A colormap named "shiftedcmap" is already registered.

### Expected outcome

I want to see a map here but something interesting happens. First, it gives a map for the intercept. Then I got the error above for the dependent variables. And then I am getting the same error even for the intercept that I visualized before.

### Additional information

For the whole codes and analysis see

https://pysal.org/notebooks/model/mgwr/MGWR_Georgia_example.html

### Operating system

Windows 10

### Matplotlib Version

3.7.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.11

### Jupyter version

6.5.2

### Installation

conda

**Comment by rcomer** [comment]
It looks like @timhoffm’s suggestion should fix this.  
I’m going to close this because I do not think it’s a bug in Matplotlib.  But @firatgundem you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.

**Comment by firatgundem** [comment]
Thank you @timhoffm for the answer. Since I am new to Python, I am trying to do the manipulation that you advised. I tried to find what should I write instead of "shift_colormap" in the line "cmap = shift_colormap(cmap, start=0.0, midpoint=1 - vmax/(vmax + abs(vmin)), stop=1.)"  but could not figure it out. Could you please elaborate more? Thanks.

**Comment by tacaswell** [comment]
@firatgundem Please ask that question (with a minimal code example of what you have tried and did not work) on https://discourse.matplotlib.org .  We try to keep the issue tracker restricted to bugs and feature discussion rather than general user support.
