### ISSUE TITLE
[ENH]: plt.subplots type function that uses 'nsubplots' instead of 'nrows' and 'ncols'

### ISSUE THREAD

**Issue by hudsonhoch** [matplotlib/matplotlib#25971]
### Problem

I would like to be able to call a `plt.subplots` type function that creates a figure and axes that best maintains a desired figure shape. Basically a function that nicely tiles  `nsubplots` in a figure.

### Proposed solution

A very basic solution would be something like the following:

```
def create_subplots(nsubplots, ratio=.5, overflow_cols=True):
    nrows = int(round(nsubplots ** ratio))
    ncols = int(round(nsubplots ** (1-ratio)))
    if nrows * ncols < nsubplots:
        if overflow_cols:
            ncols += 1
        else:
            nrows += 1
    fig = plt.figure()
    axs = [fig.add_subplot(nrows,ncols,i+1) for i in range(nsubplots)]
    return fig, axs             
```
And of course other arguments should be able to be used similar to the keyword arguments of `plt.subplots`. I think somehow incorporating `width_ratios` and `height_ratios` would make this very useful.

**Comment by jklymak** [comment]
This just kicks the mental math from figuring out the nearest multiples to figuring out how to get your factor parameter to work.  If I want 10 subplots I don't think it's too much mental arithmetic to ask the user to decide between 1x10, 2x5 or 3x4 and their converses.  Whereas I'm not sure what factor to use to get those results.

**Comment by tacaswell** [comment]
Also see https://github.com/matplotlib/grid-strategy for a package that does this statically.  That implementation also deals with trying to pack them nicely and not create the extra axes.

https://tacaswell.github.io/dynamic-axes-count.html is a probably too-cute bit of code that will let you dynamically add axes and attempt to re-flow them.

I also have concerns with the proposed code that it treats the users requested number of axes as a suggestion.

Rather than adding a new method, I would go with a helper like

```python
def guess_grid_shape(atleast_n, ratio=.5, overflow='row'):
    nrows = int(round(nsubplots ** ratio))
    ncols = int(round(nsubplots ** (1-ratio)))
    while nrows * ncols < nsubplots:
        if overflow == 'cols':
            ncols += 1
        else:
            nrows += 1
    return nrows, ncols
```

which you could use as

```python
fig, ax = plt.subplots(*guess_grid_shape(15), ...)
```

However, I'm not immediately sure that there is an obvious "correct" way to parameterize this and where it might live in Matplotlib.

**Comment by hudsonhoch** [comment]
> Also see https://github.com/matplotlib/grid-strategy for a package that does this statically. That implementation also deals with trying to pack them nicely and not create the extra axes.
> 
> https://tacaswell.github.io/dynamic-axes-count.html is a probably too-cute bit of code that will let you dynamically add axes and attempt to re-flow them.
> 
> I also have concerns with the proposed code that it treats the users requested number of axes as a suggestion.
> 
> Rather than adding a new method, I would go with a helper like
> 
> ```python
> def guess_grid_shape(atleast_n, ratio=.5, overflow='row'):
>     nrows = int(round(nsubplots ** ratio))
>     ncols = int(round(nsubplots ** (1-ratio)))
>     while nrows * ncols < nsubplots:
>         if overflow == 'cols':
>             ncols += 1
>         else:
>             nrows += 1
>     return nrows, ncols
> ```
> 
> which you could use as
> 
> ```python
> fig, ax = plt.subplots(*guess_grid_shape(15), ...)
> ```
> 
> However, I'm not immediately sure that there is an obvious "correct" way to parameterize this and where it might live in Matplotlib.

The users requested number is of axes is upheld in line `axs = [fig.add_subplot(nrows,ncols,i+1) for i in range(nsubplots)]`: so extra axes are not created. The `ratio` argument parameterizes how horizontal or vertical you want your figure to be. `ratio` needs to be in the interval [0,1] where `ratio=1` would create a purely vertical figure (`nsubplots` x 1) and `ratio=0` would create a purely horizontal figure (1 x `nsubplots`). Hence `ratio=.5` tries to keep the figure as square as possible.

I currently already use this as a helper function and in response to @jklymak I agree it's not too bad to do some mental math, but it is useful for creating a variable number of plots (which I happen to do quite often).

The grid-strategy package appears to do what I'm looking for: does this mean this kind of functionality shouldn't be part of matplotlib's package?

**Comment by tacaswell** [comment]
> The users requested number is of axes is upheld in line axs = [fig.add_subplot(nrows,ncols,i+1) for i in range(nsubplots)]: s

🐑 sorry, missed that detail when reading the code.


> The grid-strategy package appears to do what I'm looking for:

Yes, we think that this is better served via a third-party package rather than in the main repository.
