### ISSUE TITLE
[Doc]: Cleanup viewlims example

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#25979]
### Documentation Link

https://matplotlib.org/stable/gallery/event_handling/viewlims.html

### Problem

The viewlims example is nice, but
- subclassing Rectangle to make it callable and thus usable as a xlim_changed callback seems a bit weird, probably better to use some plain function callback that closes over the rectangle object.
- accessing ax.viewLim is a bit unidiomatic, ax.get_xlim()/ax.get_ylim() seem like the normal approach.

**Comment by QuLogic** [comment]
As far as the code goes itself, I think the `Rectangle` could be replaced by ` RectangleSelector` (with `interactive=True`, this works quite nicely), but I wonder what this example is showing specifically and whether it makes sense to do that.

**Comment by anntzer** [comment]
I think the advantage of using viewlims is that this also handles pans, zoomouts, etc.
