### ISSUE TITLE
[MNT]: Cleanup ticklabel_format(..., style=)

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#25974]
### Summary

Half a note to self, but anybody can pick this up.

https://github.com/matplotlib/matplotlib/blob/6a323c043b77154656b28fd34ac4ca6dfb0ecf9b/lib/matplotlib/axes/_base.py#L3191

defaults `style=''`, which is only used at:

https://github.com/matplotlib/matplotlib/blob/6a323c043b77154656b28fd34ac4ca6dfb0ecf9b/lib/matplotlib/axes/_base.py#L3245-L3246

### Proposed fix

- Consistency: Change the default value to `None`, like for all the other kwargs here, which has the sematincs `None` = *do not change*.
- Document that 'sci' and 'scientific' are equivalent. (Or maybe deprecate 'sci'?)

**Comment by EddieEngineers** [comment]
Hey Tim, I can put a PR in for this - keen to learn more about the Matplotlib library :)

**Comment by EddieEngineers** [comment]
> Document that 'sci' and 'scientific' are equivalent. (Or maybe deprecate 'sci'?)

I'm not sure where the documentation is to update, do you mind pointing me in the right direction? :)

**Comment by rcomer** [comment]
@EddieEngineers I think just in the method’s docstring.

**Comment by pedrompecanha** [comment]
Hi guys! If I understood correctly, a method has inconsistent default values, and a lack of documentation. I saw that the previous attempt didn't continue until the end. Could I take it over and solve the issues? It would be a brilliant opportunity for me to learn. Thanks in advance!

**Comment by timhoffm** [comment]
@pedrompecanha Go for it!

**Comment by pedrompecanha** [comment]
Done @timhoffm! Thank you for the encouragement. I'll be ready to fix anything related to my PR relatively quickly!
