### ISSUE TITLE
[ENH]: Make all default color schemes colorblind safe ones

### ISSUE THREAD

**Issue by babryce** [matplotlib/matplotlib#25997]
### Problem

1 in 12 men are colorblind. (https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/color-blindness)
Yet computer software including matplotlib generally ignore this with default colors schemes that are impossible for these persons to read. It is absurd to exclude 4% of all people for a marginal perceived improvement in aesthetics.

Matplotlib should take the lead at least having the default color schemes colorblind safe. A bigger statement would be to remove all non-colorblind safe color schemes. Arguments that they are available are not valid, defaults matter. It should not be the default to exclude 4% of viewers. Too many people are unaware to choose or in too much of a hurry to. It should absolutely be the default thing to do.

### Proposed solution

Make tableau-colorblind10 the default, or similar as per:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239
https://matplotlib.org/stable/users/prev_whats_new/whats_new_2.2.html#new-style-colorblind-friendly-color-cycle

Etc.

**Comment by jklymak** [comment]
This is tracked at https://github.com/matplotlib/matplotlib/issues/14331. Unfortunately default style changes are breaking API and there is no way to deprecate, so they happen rarely.  I'll close here, but feel free to comment at #14331.
