### ISSUE TITLE
[MNT]: decrease timeout on interactive tests locally

### ISSUE THREAD

**Issue by greglucas** [matplotlib/matplotlib#26031]
### Summary

120 seconds is an extremely long timeout when running locally and having failures. It would be good to only set the 120 seconds on CI/remote systems and have a shorter 10-20 second timeout for most contributors with reasonable CPU architectures.
https://github.com/matplotlib/matplotlib/blob/515cce40f14a4fe4eed15ddaa569052badb71229/lib/matplotlib/tests/test_backends_interactive.py#L79

Labeling good first issue because it is very contained and should likely just need some investigation into environment variables and detecting platforms we are running on.

### Proposed fix

Set the `_test_timeout` variable differently depending on whether we are running on CI or not.

**Comment by tacaswell** [comment]
ENV is probably better than code in the test suite to try and discover CI platforms (as it will inevitably bit-rot).  It is easier to add a line in CI to set the timeout to be huge.

**Comment by 0xedl** [comment]
i believe i have solved the issue.
by adding changing it to:

_test_timeout = 20  # Default to a short timeout for most contributors
if os.getenv('CI'):  # Check if running in a CI environment
    _test_timeout = 120  # A reasonably safe value for slower architectures.

**Comment by tacaswell** [comment]
@rkverma2001 As noted above, we do not assign issues, however there is an open PR addressing this so I would recommend looking at a different issue.  When you find one you like just start working on it and open a PR when you are ready.

**Comment by rkverma2001** [comment]
@tacaswell Thank you.
