### ISSUE TITLE
[Bug]: Annotations offset by a negative number are slightly shorter than ones offset by positive numbers

### ISSUE THREAD

**Issue by saranti** [matplotlib/matplotlib#26063]
### Bug summary

When I have 2 annotations pointing to the same y coordinate, the one with text that is offset by a positive number is rendered correctly but the annotation with text offset by a negative number is offset by a slightly shorter amount.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot((-2, 2), [0, 0])
ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)
Y = 105
a = 'This annotation reaches y 1.5'
b = 'This one is short'
for i in range(2):
    ax.annotate(a, xy=(0, 0),
                xytext=(0, Y),
                fontsize='9',
                horizontalalignment='center',
                xycoords='data',
                textcoords='offset points',
                arrowprops=dict(arrowstyle="->",
                                linewidth=2,
                                color='red'))
    Y *= -1
    a = b
plt.grid(visible=True)
plt.show()
```

### Actual outcome

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/Hx9w1qNR/an.png' border='0' alt='an'/></a>

### Expected outcome

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/mr98c6c2/an2.png' border='0' alt='an2'/></a>

### Additional information

I get the same result whether I use `offset points`, `offset fontsize`, `offset pixels` or `data` .

### Operating system

Windows 11

### Matplotlib Version

3.7.1

### Matplotlib Backend

QtAgg

### Python version

3.11.1

### Installation

pip

**Comment by ksunden** [comment]
If you specify `verticalalignment="center"`, it should make them the same length. The default anchor point is the bottom left corner of the text, but you can change vertical and horizontal behavior independently. 

https://matplotlib.org/stable/gallery/text_labels_and_annotations/text_alignment.html

The default is the bottom left.

**Comment by saranti** [comment]
Thanks, that's exactly what I needed.
