### ISSUE TITLE
[ENH]: Built-in linear regression 

### ISSUE THREAD

**Issue by thiagoluisbecker** [matplotlib/matplotlib#26087]
### Problem

Currently there is no built-in Linear Regression plot, it doesn't seem too dificult to implement since the scatter plot exists.

```py
import numpy as np

def linear_regression(points):
    # Extract x and y values from the array of tuples
    x = np.array([point[0] for point in points])
    y = np.array([point[1] for point in points])

    # Calculate the number of data points
    n = len(points)

    # Calculate the mean of x and y
    mean_x = np.mean(x)
    mean_y = np.mean(y)

    # Calculate the slope and intercept
    numerator = np.sum((x - mean_x) * (y - mean_y))
    denominator = np.sum((x - mean_x) ** 2)
    slope = numerator / denominator
    intercept = mean_y - slope * mean_x

    return slope, intercept
```

### Proposed solution

Use scatter plot and linear regression function to generate a linear regression plot.

**Comment by jklymak** [comment]
Doing this properly is a little opinionated for Matplotlib - we really try to not mix analysis with plotting, though `hist` and `hist2d` are exceptions.  You may want to look at seaborn's regression tools: https://seaborn.pydata.org/tutorial/regression.html

**Comment by ksunden** [comment]
we fit into the broader scientific python ecosystem, and as such consider many "raw" computation as out of scope, especially when they are implemented by other commonly used packages, such as `numpy` or `scipy`

In fact, both numpy and scipy have routines which will compute a linear regression to get the slope and intercept:

- Scipy has [`scipy.stats.linregress`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html)
- Numpy has [`polyfit`](https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html#numpy-polyfit), which (with deg=1) can do a linear regression, but can also do quadratic, cubic, etc least-squares regression

In any case, after extracting slope and intercept from the return values (numpy returns as an array, scipy returns as scalars, both can also return other info about the regression such as quality of fit, etc)

The call to mpl is just `ax.plot(xvals, slope*xvals + intercept)`

**Comment by tacaswell** [comment]
As a comment on what the (general) API for this would look like we would need to expose the full parameter lists of both `scatter` and `plot` along with what ever parameters the actual fitting would need.  If we did that at the level of generality we strive for I think the API would be harder work with than having 3 lines in your code!

I am going to go ahead and close this as it in very unlikely we will implement this or take a PR that does so.

Thank you for the suggestion @thiagoluisbecker and I hope we hear from you again!

**Comment by jklymak** [comment]
@thiagoluisbecker Thanks for your interest in improving matplotlib, but we probably won't add this.  Note also https://matplotlib.org/stable/tutorials/introductory/quick_start.html#making-a-helper-functions .  I have my own library that I install on each environment and then call function like yours above.

**Comment by rcomer** [comment]
> We show linear regression in the [anscombs quartet](https://matplotlib.org/devdocs/gallery/specialty_plots/anscombe.html#sphx-glr-gallery-specialty-plots-anscombe-py) example, but it's a little buried there.

`axline` is the method I’ve been wanting and didn’t know existed.  Thank you!

**Comment by thiagoluisbecker** [comment]
Oh, ok! Thanks for all feedbacks!
