### ISSUE TITLE
[Bug]:  Momentary freeze issue when updating an embedded animated plot in tkinter...

### ISSUE THREAD

**Issue by TheWicklowWolf** [matplotlib/matplotlib#26119]
### Bug summary

I have a live/animated plot with dynamic x and y axes, data is incoming every 100ms (via a separate thread) and the plot is updated every second. The issue is that there is a hitch on every update. Is there a way to optimize the performance of the plot updating in this Tkinter-Matplotlib integration? 

If I use `blit = True` the plot is smooth, however I cannot use `blit` as I'm updating the axes...

### Code for reproduction

```python
Here is a skeleton code of my implementation:

from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.animation as animation

def data_thread():
    # Thread that updates data
    y.append()
    x.append()

def animate(i):
    plotArray.set_dat(x,y)
    return (self.plotArray,)

if __name__ == "__main__":
    root = tk.Tk()

    fig = Figure()
    ax = fig.add_subplot(111)
    
    canvas = FigureCanvasTkAgg(fig, master=root)  

    ani = animation.FuncAnimation(fig, animate, interval=1000, blit=False)
	canvas.draw()
	
    tk.mainloop()
```

### Actual outcome

![matplotlib](https://github.com/matplotlib/matplotlib/assets/111055425/30fbea3d-d27b-4f34-9f0c-9e463989663c)

### Expected outcome

.

### Matplotlib Version

3.7.1

### Installation

None

**Comment by tacaswell** [comment]
Can you please post this (with a runnable code examples and axis labels on your plots ;) ) on https://discourse.matplotlib.org ?  I think this is a usage question, not a bug report.
