### ISSUE TITLE
[Bug]: NavigationToolbar2 mouse over event causes toolbar height increase and axes reposition

### ISSUE THREAD

**Issue by EspritElf** [matplotlib/matplotlib#26124]
### Bug summary

Anytime I mouse over a pcolor or imshow axes, the mouse cursor event displays the coordinates in the toolbar with a '\n' causing a new line, increasing the toolbar height and repositioning my axes. Removing the '\n' removes the toolbar height change.

### Code for reproduction

```python
@staticmethod
    def _mouse_event_to_message(event):
        if event.inaxes and event.inaxes.get_navigate():
            try:
                s = event.inaxes.format_coord(event.xdata, event.ydata)
            except (ValueError, OverflowError):
                pass
            else:
                s = s.rstrip()
                artists = [a for a in event.inaxes._mouseover_set
                           if a.contains(event)[0] and a.get_visible()]
                if artists:
                    a = cbook._topmost_artist(artists)
                    if a is not event.inaxes.patch:
                        data = a.get_cursor_data(event)
                        if data is not None:
                            data_str = a.format_cursor_data(data).rstrip()
                            if data_str:
                                s = s + '\n' + data_str
                return s
        return ""
```

### Actual outcome

[Screencast from 06-14-2023 01:52:20 PM.webm](https://github.com/matplotlib/matplotlib/assets/46389730/5c32cbff-74cf-43bf-a3bb-f66db99f813d)

### Expected outcome

Removing the \n corrects the behavior.  

[Screencast from 06-14-2023 02:15:23 PM.webm](https://github.com/matplotlib/matplotlib/assets/46389730/cc9070a4-003a-49f3-9e2b-af384c32a22a)

### Additional information

pcolor and imshow figures

### Operating system

Ubuntu 22.04

### Matplotlib Version

3.7.1

### Matplotlib Backend

tkAgg

### Python version

3.10.6

### Installation

pip

**Comment by KalebNiven** [comment]
Hi
The height of the text you displayed with '\n' is longer than current height of the toolbar.
I think you need to customize the height of the bar so that the text can't resize height of the toolbar.
You can reference this.
https://stackoverflow.com/questions/65649688/customizing-the-height-in-bar-chart-matplotlib

**Comment by EspritElf** [comment]
The stackoverflow question you referenced discusses how to increase the height of the bar chart to the top of the axes, not the height of the toolbar. I would rather the mouse cursor data go all on one line instead of creating a new line and relying on the toolbar to have enough height to accomodate, but wow would you increase the toolbar height? I haven't found a way to increase the toolbar height. 

I wonder what the reason was in 2020 to change from
 `s = s + ' ' + data_str` 
to this
`s = s + '\n ' + data_str`

The code change doesn't state a reason.

**Comment by QuLogic** [comment]
From the question mark being there, it appears that you are using the non-default `toolmanager2` option?

**Comment by EspritElf** [comment]
Hi @QuLogic,
Yes that's correct, I am using toolmanager, pardon for not mentioning that in my original post. I have mulitple figures that I wish to sync together and I need to add an additional button for a matlab-like datatips. Does the extra line not show up if I use the regular toolbar? I would have to see if can implement what I need with the standard one if that's the case.

**Comment by QuLogic** [comment]
Yes, in the default toolbar, there is a spacer to ensure that it doesn't change heights based on the status message:
https://github.com/matplotlib/matplotlib/blob/a1f9e0fc03b5c4ec7eadef9723ea48168d0e992f/lib/matplotlib/backends/_backend_tk.py#L638-L644
This appears to be missing from the toolmanager version. You could probably manually pack a similar item into the toolbar yourself in the meantime to prevent the same problem.

**Comment by EspritElf** [comment]
I'm not sure how to add that to the toolmanager toolbar, I just use the rcParams command to set the toolbar to toolmanager. I did remove the toolmanager code to switch back to the standard toolbar and it does correctly display without the toolbar height changing, but the toolbar height just appears too big for my taste, I'm used to smaller size toolbars. I think I'll just change the line of code to omit the newline and document it for the future. Thanks for taking the time to check into this, I appreciate it!

**Comment by QuLogic** [comment]
Also interestingly, I can't reproduce the problem in a conda environment, but can in Fedora because the default font is a different size.

**Comment by anntzer** [comment]
> I would have to see if can implement what I need with the standard one if that's the case.

You may want to consider trying the figure.hooks rcparam, see https://matplotlib.org/stable/gallery/user_interfaces/mplcvd.html (also documented in the docstring of plt.figure()).

**Comment by EspritElf** [comment]
Ahh, so that's how you configure the toolbar! I am porting a matlab project to python/matplotlib/numpy and am still learning my way around matplotlib, but so far I love it. I was having issues with the speed of rendering until I found the pcolorfast method, now it is just as fast as matlab and the processing is quite a bit faster. I am pretty sure it's the way the algorithms were refactored but it's really making the effort worthwhile. Thanks for the tip!

**Comment by anntzer** [comment]
Happy to hear that you like matplotlib.

It's pretty normal that you hadn't heard about figure.hooks, as that functionality is very new; previously only toolmanager was available (but it was somewhat poorly maintained).  Depending on user feedback we may consider tweaks to figure.hooks, so feel free to comment on that (preferably on a fresh issue, as closed issues typically don't get as much attention).

**Comment by EspritElf** [comment]
Thanks I will do that, I was going over hooks and the figure initialization and start-up and a few use cases I would like to investigate came to mind. I'll be sure to report if I notice anything that may be of use to the development team.
