### ISSUE TITLE
[ENH]: Divergent greyscale / grayscale colormap

### ISSUE THREAD

**Issue by buhtz** [matplotlib/matplotlib#26123]
### Problem

Looking into the [docu](https://matplotlib.org/stable/tutorials/colors/colormaps.html#diverging) it seems there is no _Divergent colormap_ just using grayscales.

Sometimes author guidelines of journals do request it or sometimes you need to print it and just have a greyscale printer around.

### Proposed solution

Just offering a Divergent Colormap using colors from black to white. I would prefer to have white in the middle and black left/right.

Maybe relevant: #18608

**Comment by jklymak** [comment]
https://matplotlib.org/stable/tutorials/colors/colormap-manipulation.html shows you how to do this.

```
top = mpl.colormaps['Greys_r'].resampled(128)
bottom = mpl.colormaps['Greys'].resampled(128)

newcolors = np.vstack((top(np.linspace(0, 1, 128)),
                       bottom(np.linspace(0, 1, 128))))
newcmp = ListedColormap(newcolors, name='DivergingGrey')
```

If you know of a package that has a diverging greyscale colormap, or a published example of such, that may be helpful. As described, I don't think Matplotlib should offer such a colormap by default.  It is impossible to tell what side of zero any of the data is, so it does not seem very quantitatively useful. Maybe something where the gradients were different on either side of zero might work?  Or a few distinct greys on either side of zero?  

I'm going to close this as not planned, but a) if you have a solid proposal we can re-open, or b) feel free to discuss in https://discourse.matplotlib.org.

**Comment by buhtz** [comment]
>  It is impossible to tell what side of zero any of the data is, so it does not seem very quantitatively useful.

There is no need to tell the side in every case. For example in a correlation matrix where the values between `-1` and `+1`.

I just want to know how far away they are from `0`. I don't care of the side in the first place. I also do annotate such matrix. So I can read the numbers to tell the side.

For a first look it is much easier to read if there are just light and dark cells.

**Comment by jklymak** [comment]
For that case you can either use the recipe above or just use abs(x) when you make the pcolormesh/imshow of your matrix

**Comment by buhtz** [comment]
> For that case you can either use the recipe above or just use abs(x) when you make the pcolormesh/imshow of your matrix

Yes I can. But this is not a solution but a workaround. That is why I asked for a feature in seaborn because I think it will make life easier and your package better.

I just asked. Maybe it is out of scope or design borders of your package.
