### ISSUE TITLE
[Bug]: Getting " AttributeError: '_AxesStack' object has no attribute 'clear' " for any plot

### ISSUE THREAD

**Issue by Jballbe** [matplotlib/matplotlib#26147]
### Bug summary

Hi, 
For any plot I am trying to produce I am getting the same AttributeError. I even tried some example code from matplotlib website

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

fruits = ['apple', 'blueberry', 'cherry', 'orange']
counts = [40, 100, 30, 55]
bar_labels = ['red', 'blue', '_red', 'orange']
bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange']

ax.bar(fruits, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('fruit supply')
ax.set_title('Fruit supply by kind and color')
ax.legend(title='Fruit color')

plt.show()
```

### Actual outcome

Traceback (most recent call last):

  Cell In[257], line 3
    fig, ax = plt.subplots()

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/_api/deprecation.py:471 in wrapper
    An unbound method, i.e. an expression of the form

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/pyplot.py:1439 in subplots
    fig, ax = plt.subplots()

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/pyplot.py:797 in figure
    `.pyplot.close` on the figures you are not using, because this will

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/pyplot.py:316 in new_figure_manager
    if manager:

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:27 in new_figure_manager
    return new_figure_manager_given_figure(num, FigureClass(*args, **kwargs))

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/figure.py:2276 in __init__
    """

  File ~/anaconda3/envs/allen3.9/lib/python3.9/site-packages/matplotlib/figure.py:2735 in clf

AttributeError: '_AxesStack' object has no attribute 'clear'

### Expected outcome

I just want to have a plot

### Operating system

MacOS 13.4 

### Matplotlib Version

3.4.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.16

### Installation

pip

**Comment by rcomer** [comment]
It looks like you have a problem with your installation.  You appear to be using a mixture of conda and pip, which may be part of the problem if you have made successive updates.  I would try starting again with a clean environment.  Otherwise, please open a question over at Discourse, where we have a dedicated category for installation problems.
https://discourse.matplotlib.org/c/community/install/13

I’m going to close this because I do not think it’s a bug in Matplotlib.
