### ISSUE TITLE
Impossible to get the z value of a line in 3D

### ISSUE THREAD

**Issue by nippotam** [matplotlib/matplotlib#26146]
### Bug summary

Traceback (most recent call last):
  File "slider.py", line 318, in <module>
    plot_functions_3D(functions_list, colors_list)
  File "slider.py", line 181, in plot_functions_3D
    add_arrow_3d(line3d, d=10)
  File "slider.py", line 88, in add_arrow_3d
    zdata = line.get_zdata()
AttributeError: 'Line3D' object has no attribute 'get_zdata'

### Code for reproduction

```python
ax_main = fig.add_subplot(111, projection='3d')  # Use 3D projection
   for function in list_functions:
        result = [function(ti) for ti in t]
        x, y, z = zip(*result)
        line, = ax_main.plot(x, y, z)  # Use plot() for 3D plot
        add_arrow_3d(line, d=10)
        lines.append(line)

def add_arrow_3d(line):
    """
    Add an arrow to a line in a 3D plot every d steps.
    xdata = line.get_xdata()
    ydata = line.get_ydata()
    zdata = line.get_zdata() # -> error


seems not coherent here in art3D.py 
 @artist.allow_rasterization
    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
        self.set_data(xs, ys) #-> zs is not used
        super().draw(renderer)
        self.stale = False

and here : 
    def set_3d_properties(self, zs=0, zdir='z'):
        xs = self.get_xdata()
        ys = self.get_ydata()
        zs = np.broadcast_to(zs, len(XS)) #-> why we have not self.get_zdata() ?
        self._verts3d = juggle_axes(xs, ys, zs, zdir)
        self.stale = True
```

### Actual outcome

 Traceback (most recent call last):
  File "slider.py", line 318, in <module>
    plot_functions_3D(functions_list, colors_list)
  File "slider.py", line 181, in plot_functions_3D
    add_arrow_3d(line3d, d=10)
  File "slider.py", line 88, in add_arrow_3d
    zdata = line.get_zdata()
AttributeError: 'Line3D' object has no attribute 'get_zdata'

### Expected outcome

the z value

### Operating system

Mac OS

### Matplotlib Version

Version: ImageMagick 7.1.1-6 Q16-HDRI x86_64 21020 https://imagemagick.org Copyright: (C) 1999 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC HDRI Modules OpenMP(5.0)  Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib Compiler: gcc (4.2) Usage: import [options ...] [ file ]

### Python version

3.7

### Installation

pip

**Comment by saranti** [comment]
To get the value of xyz in Line3D, you use the [get_data_3d](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.art3d.Line3D.html#mpl_toolkits.mplot3d.art3d.Line3D.get_data_3d) function:
```py
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Line3D

x = [.1, .3, .5, .8]
y = [.2, .4, .6, .7]
z = [.5, .8, .3, .4]

fig, ax = plt.subplots(subplot_kw=dict(projection='3d'))

line = Line3D(x, y, z)
ax.add_line(line)

xyz_data = line.get_data_3d()

d = ('x', 'y', 'z')
for i, v in enumerate(xyz_data):
    print(f"{d[i]}_data = {v}")

```
```
output:
x_data = [0.1, 0.3, 0.5, 0.8]
y_data = [0.2, 0.4, 0.6, 0.7]
z_data = [0.5, 0.8, 0.3, 0.4]
```

Lines3D does not have a `get_zdata` function (nor  `get_xdata`, `get_ydata`). Lines2D has the latter 2. I don't know why it's done that way, maybe someone else can explain that.

**Comment by rcomer** [comment]
`Line3D` does have `get_xdata` and `get_ydata`, because it inherits from `Line2D`.  They do not return what you might assume though.  Taking @saranti's example:
```python
In [4]: print(line.get_xdata())
[-0.05707041 -0.02580673  0.00561798  0.04085197]

In [5]: print(line.get_ydata())
[-0.00343793  0.02330351 -0.00973062 -0.0060572 ]

```
My guess is that these are the values after translating the 3D data to the two dimension needed for drawing.

**Comment by oscargus** [comment]
Yes, quite a lot of the idea of the 3D classes is to have the 3D data separated and then make the objects behave as 2D objects projected to the correct location. Looking at the `Line3D` the `draw`-method does exactly that:

https://github.com/matplotlib/matplotlib/blob/a73c347b11a39c4b64a817da3b523ce53225ae50/lib/mpl_toolkits/mplot3d/art3d.py#L262-L267

`_verts3d` are mapped to 2D and then set as data to the `Line2D` which is then drawn.

**Comment by oscargus** [comment]
I opened a PR adding a note to the documentation about this: #26148

Not sure if there is much more we can do?
