### ISSUE TITLE
[Bug]: aspect ratio with share axis

### ISSUE THREAD

**Issue by jlocatelli74** [matplotlib/matplotlib#26163]
### Bug summary

when I'm using Scatter plot with histograms ans add a aspect ratio on the main plot, the share axis doesn't change it size according the size to the main plot. I'll take the example on the matplotlib example and only add a aspect ratio.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

# Fixing random state for reproducibility
np.random.seed(19680801)

# some random data
x = np.random.randn(1000)
y = np.random.randn(1000)


def scatter_hist(x, y, ax, ax_histx, ax_histy):
    # no labels
    ax_histx.tick_params(axis="x", labelbottom=False)
    ax_histy.tick_params(axis="y", labelleft=False)

    # the scatter plot:
    ax.scatter(x, y)

    # now determine nice limits by hand:
    binwidth = 0.25
    xymax = max(np.max(np.abs(x)), np.max(np.abs(y)))
    lim = (int(xymax/binwidth) + 1) * binwidth

    bins = np.arange(-lim, lim + binwidth, binwidth)
    ax_histx.hist(x, bins=bins)
    ax_histy.hist(y, bins=bins, orientation='horizontal')
    
    # Start with a square Figure.
fig = plt.figure(figsize=(6, 6))
# Add a gridspec with two rows and two columns and a ratio of 1 to 4 between
# the size of the marginal axes and the main axes in both directions.
# Also adjust the subplot parameters for a square plot.
gs = fig.add_gridspec(2, 2,  width_ratios=(4, 1), height_ratios=(1, 4),
                      left=0.1, right=0.9, bottom=0.1, top=0.9,
                      wspace=0.05, hspace=0.05)
# Create the Axes.
ax = fig.add_subplot(gs[1, 0])
ax_histx = fig.add_subplot(gs[0, 0], sharex=ax)
ax_histy = fig.add_subplot(gs[1, 1], sharey=ax)
# Draw the scatter plot and marginals.
scatter_hist(x, y, ax, ax_histx, ax_histy)

ax.set_aspect(0.5)

plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/65216088/a4336b80-e640-491c-97e9-f1829b539c46)

### Expected outcome

The right histogram should change it vertical dimension

### Operating system

Ubuntu

### Matplotlib Version

3.1.6

### Matplotlib Backend

QtAgg

### Python version

 3.10.6

### Installation

pip

**Comment by jklymak** [comment]
There are two examples of this at https://matplotlib.org/stable/gallery/lines_bars_and_markers/scatter_hist.html#sphx-glr-gallery-lines-bars-and-markers-scatter-hist-py. I prefer the inset_axes method, but your taste may vary.  Please use https://discourse.matplotlib.org for user questions.  Thanks...

**Comment by rcomer** [comment]
Isn’t the point here that the righthand plot shares its y-axis with the central plot, so you might expect the vertical extent of the righthand plot to reduce along with the central plot when you set the aspect ratio?

**Comment by jklymak** [comment]
Yes, but the right hand plot doesn't know anything about the left hand plot, it just knows what space it has been allocated, and fills that up.  The way to make them track each other robustly and without manual futzing is to use `inset_axes` where the child is positioned relative to the parent.

**Comment by jlocatelli74** [comment]
Thanks for your answers, I'will used inset_axes that working as we want withe aspect ratio.
