### ISSUE TITLE
[MNT]: Best way to detect new plot from code chunk

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#26172]
### Summary

With apologies - I tried asking over at [Matplotlib discourse](https://discourse.matplotlib.org/t/best-way-to-detect-new-figure-in-jupyter-code-cell/23889) - but it was beginning to look pretty quiet over there.

To recap - I have been doing some  [work to the Reticulate package](https://github.com/rstudio/reticulate/pull/1394).  Reticulate is an R package for executing Python code, that, like Jupyter, has the concept of code cells (or "chunks" in the R lingo).

Like Jupyter, it has to detect if the user has generated a plot in the code cell, and, if so, display it automatically (without `plt.show()`).

At the moment, we’re using an unsatisfying heuristic, of looking for expressions returning Matplotlib objects.

But - what is the best and recommended way to detect whether a particular cell of code has produced a new figure, and how many? I mean, what is the best way of writing wrapping code of form:

```python
starting_figures = get_number_of_figures()
run_code_in_cell()
if len(get_number_of_figures()) > len(starting_figures):
    # Do something to embed plots
```

I know from my [nb2plots days](https://github.com/matthew-brett/nb2plots/blob/main/nb2plots/nbplots.py#LL1011C20-L1011C46) that there is `matplotlib._pylab_helpers.Gcf` - but the underscore there made me worry that wasn’t the best approach.

**Comment by anntzer** [comment]
Is plt.get_fignums (or diffing plt.get_figlabels between consecutive calls) what you're looking for?

**Comment by matthew-brett** [comment]
Ah - yes - thanks much for that - https://github.com/rstudio/reticulate/pull/1401

**Comment by matthew-brett** [comment]
Closing ...
