### ISSUE TITLE
[Bug]: ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\anaconda3\lib\site-packages\matplotlib\__init__.py)

### ISSUE THREAD

**Issue by satya0210** [matplotlib/matplotlib#26181]
### Bug summary

i have upgraded my pandas,numpy 2 days back
previosly when i was plotting using my code i didnt get any problem
now i was getting value error while
then i again i upgraded my matplotlib
i was getting this error
ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\\anaconda3\lib\site-packages\matplotlib\__init__.py)

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import matplotlib.dates as mdates
from scipy import stats
from scipy.stats import pearsonr
```

### Actual outcome

ImportError                               Traceback (most recent call last)
<ipython-input-4-3ef1622bdcb7> in <module>
      1 import numpy as np
----> 2 import matplotlib.pyplot as plt
      3 import pandas as pd
      4 import seaborn as sns
      5 import matplotlib.dates as mdates

~\anaconda3\lib\site-packages\matplotlib\__init__.py in <module>
    105 # cbook must import matplotlib only within function
    106 # definitions, so it is safe to import from it here.
--> 107 from . import cbook, rcsetup
    108 from matplotlib.cbook import MatplotlibDeprecationWarning, sanitize_sequence
    109 from matplotlib.cbook import mplDeprecation  # deprecated

~\anaconda3\lib\site-packages\matplotlib\rcsetup.py in <module>
     24 import numpy as np
     25 
---> 26 from matplotlib import animation, cbook
     27 from matplotlib.cbook import ls_mapper
     28 from matplotlib.fontconfig_pattern import parse_fontconfig_pattern

ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\anaconda3\lib\site-packages\matplotlib\__init__.py)

### Expected outcome

the code should run

### Operating system

windows

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.8.8

### Jupyter version

6.3.0

### Installation

pip

**Comment by astromancer** [comment]
Not a conda user, but I've had similar issues with circular imports come up with editable installs when switching between major versions with git in the command line. Reinstalling usually fixes it.

**Comment by tacaswell** [comment]
Mixing conda and pip it is very possible that you have ended up with a "chimera" installation with some files from one version of Matplotlib and some files from another which (understandably) does always work.

I think the correct path forward here is to re-install everything with conda.  To be extra safe I would start with a new environment...

I am going to close this as, but if you have further issues please post to https://discourse.matplotlib.org/c/community/install/13 as we try to keep the issue tracker for bugs and handle user support on discourse.
