### ISSUE TITLE
[Doc]: 

### ISSUE THREAD

**Issue by ahobeost** [matplotlib/matplotlib#26192]
### Documentation Link

https://matplotlib.org/stable/api/testing_api.html#module-matplotlib.testing.compare

### Problem

First of all, thanks for your awesome work!

I'd like to compare two SVGs against each other, similar to how I can compare PDFs using methods in mpl.testing.compare.
In the documentation, the comparable formats include "svg".

![image](https://github.com/matplotlib/matplotlib/assets/122869062/e5f80c02-4576-4cfb-b1c9-285ef8d00de3)

When I run the same, however, "svg" is not part of the list.

![image](https://github.com/matplotlib/matplotlib/assets/122869062/34c3b0f6-8106-458f-a953-47f606462e2c)

Trying to use SVGs also does not work:
![image](https://github.com/matplotlib/matplotlib/assets/122869062/e0db9416-c7da-4a99-971d-d0004fc77da5)

This is on Windows, in case that is relevant.

### Suggested improvement

It would be great if this functionality would be included.

**Comment by jklymak** [comment]
For svg you need to install Inkscape to do the conversion to png.

**Comment by ahobeost** [comment]
Thanks @jklymak!
The issue ended up being the following:
![image](https://github.com/matplotlib/matplotlib/assets/122869062/cce49828-f777-40be-ba8b-f9ed59788d18)
