### ISSUE TITLE
[Bug]: issue using LaTeX fonts

### ISSUE THREAD

**Issue by tchen01** [matplotlib/matplotlib#26209]
### Bug summary

When trying to use non-standard fonts with LaTeX the code raises the error
`FileNotFoundError: Matplotlib's TeX implementation searched for a file named 'phvr7t.tfm' in your texmf tree, but could not find it`

### Code for reproduction

```python
import matplotlib.pylab as plt

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "Helvetica"
})

plt.plot([0,1], [0,1])
plt.show()
```

### Actual outcome

The error is raised

### Expected outcome

I expect the code to generate a figure

### Additional information

I think the issue is in this file: https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/dviread.py

It seems that line 1082 it is successful, but then in line 1087 sets path to `None`.  This causes the exception at 1109.

If instead I force the code into the fallback at 1088, then it my figure is generated as intended.

I wonder whether 1082 would ever fail. Perhaps the exception should be for whether the search is successful or not.

Separately, I'm not really sure why the search wasn't successful. When I run the `kpsewhich.lua` file from the terminal it works fine. So perhaps there is an issue with the function as well?

### Matplotlib Version

3.7.1

### Installation

None

**Comment by ksunden** [comment]
This is very dependent on how Matplotlib was installed and on the platform, that would be useful info to have. And also how was LaTeX installed (which is also super relevant here)?

For instance, I do not see this error on my machine. 

It could be that you have two different LaTeX installations or something.

Line 1082 would fail if `luatex` (specifically) was not installed, we have fallbacks for other TeX implementations.

**Comment by tchen01** [comment]
Thanks for the response. It looks like the problem was that the `luatex` from my distro was still in /usr/bin/. My apologies for wasting time over something I should have caught.

> Line 1082 would fail if luatex (specifically) was not installed, we have fallbacks for other TeX implementations.

Got it, that makes sense.

**Comment by francois-rozet** [comment]
Hello @ksunden, I have the same issue. Specifically, plotting anything with `'text.usetex': True` crashes with the error message

```
Matplotlib's TeX implementation searched for a file named 'cmss10.tfm' in your texmf tree, but could not find it
```

I have investigated and it seems that the _LuatexKpsewhich](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/dviread.py#L991) object instantiated

https://github.com/matplotlib/matplotlib/blob/f533687dc14a2715650a29fc017180103e527f9e/lib/matplotlib/dviread.py#L1039-L1042

fails to look up the filename.

**Comment by ksunden** [comment]
I am skeptical about trying to work around what are fundamentally installation issues.

If it could be detected easily with a fairly minimal change (e.g. expanding the `except` to more than just `FileNotFoundError`), I'm not so opposed to it, but also not super interested in putting in code paths that are hard to trigger... If you are having a problem with packaging, please report that to your systems packagers (I will note I have not seen this on any of my debian/ubuntu based machines).
