### ISSUE TITLE
[ENH]: function naming is inconsistent between, e.g. matplotlib.pyplot and matplotlib.axes.Axes

### ISSUE THREAD

**Issue by JohnAtl** [matplotlib/matplotlib#26207]
### Problem

I'm always frustrated when: I need to call functions on, say, `axes`, and my initial attempts fail because a lot of the function names begin with `set_`, while their `pyplot` counterparts do not.    

`ax.set_xlabel('my label')` vs. `plt.xlabel('my label')`
`ax.set_title('The Title')` vs. `plt.title('The Title')`

### Proposed solution

Perhaps create aliases for the `axes` functions to match the `pyplot` functions.

**Comment by tacaswell** [comment]
@JohnAtl Can we close this issue and keep the discussion in #15938 ?
