### ISSUE TITLE
[Doc]: FancyBboxPatch shows a wrong type hint for `xy` parameter.

### ISSUE THREAD

**Issue by Geometrein** [matplotlib/matplotlib#26222]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyBboxPatch.html

### Problem

FancyBboxPatch shows `float` as the suggested type for `xy` parameter. However 'xy' should be a tuple of two floats. Seem like it is caused by missing parenthesis.

### Suggested improvement

Change the type hint form `xy: float, float` to `xy: (float, float)`

**Comment by QuLogic** [comment]
That sounds correct; would you like to open a PR?

**Comment by Geometrein** [comment]
Sure, will do!
