### ISSUE TITLE
[Doc]: document how to get list of registered colormaps

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#26244]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/colors/colormaps.html

### Problem

Getting a full list of colormaps is documented in the cmap registry call function and far as I can tell nowhere else. 

https://github.com/matplotlib/matplotlib/blob/f017315dd5e56c367e43fc7458fd0ed5fd9482a2/lib/matplotlib/cm.py#L100C1-L107C1

### Suggested improvement

I think documentation of how to get a full list of registered colormaps should be added to: 

- [ ] [matplotlib.colormaps](https://matplotlib.org/devdocs/api/matplotlib_configuration_api.html#matplotlib.colormaps) docs
- [ ] top of the [choosing colormaps](https://matplotlib.org/devdocs/users/explain/colors/colormaps.html#colormaps) tutorial

**Comment by MrZaurik** [comment]
Like a function or what are you meaning?. Look at this
![image](https://github.com/matplotlib/matplotlib/assets/139176477/e9c77004-0530-46db-b850-fcbe07d914da)
Actually this are the colors that you can choose for your plots. In the left side you can see the name, and next to this the colormap.

**Comment by oscargus** [comment]
I think it means that something like the following should be added:

```
To get a list of all registered colormaps, you can do::

    from matplotlib import colormaps
    list(colormaps)
```

**Comment by MrZaurik** [comment]
Perfect. I'll be work on this.

**Comment by MrZaurik** [comment]
Okay, my progress was the following, I wrote a few lines in the file colormaps.py where I create a function called listColormaps() the important thing is that according to the type of colormap it will list the available patterns.

Now, I find it useful to declare in a global way the variables of the colormap types that exist, that is to say: Perceptually, Sequential, Sequential2, Cyclic, Qualitative, Miscellaneous. In such a way that if more patterns are developed it will be easier to extend the functionalities. 

Attached is the code

```py
# New function to list the actually colormaps on matplotlib
def listColormaps(category):
    # Define a dictionary that maps each category to its corresponding list of colormaps
    colormaps_by_category = {
        'Perceptually': ['viridis', 'plasma', 'inferno', 'magma', 'cividis'],
        'Sequential': ['Greys', 'Purples', 'Blues', 'Greens', 'Oranges', 'Reds',
                       'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu', 'BuPu',
                       'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn'],
        'Sequential2': ['binary', 'gist_yarg', 'gist_gray', 'gray', 'bone',
                        'pink', 'spring', 'summer', 'autumn', 'winter', 'cool',
                        'Wistia', 'hot', 'afmhot', 'gist_heat', 'copper'],
        'Diverging': ['PiYG', 'PRGn', 'BrBG', 'PuOr', 'RdGy', 'RdBu', 'RdYlBu',
                      'RdYlGn', 'Spectral', 'coolwarm', 'bwr', 'seismic'],
        'Cyclic': ['twilight', 'twilight_shifted', 'hsv'],
        'Qualitative': ['Pastel1', 'Pastel2', 'Paired', 'Accent', 'Dark2',
                        'Set1', 'Set2', 'Set3', 'tab10', 'tab20', 'tab20b',
                        'tab20c'],
        'Miscellaneous': ['flag', 'prism', 'ocean', 'gist_earth', 'terrain',
                          'gist_stern', 'gnuplot', 'gnuplot2', 'CMRmap',
                          'cubehelix', 'brg', 'gist_rainbow', 'rainbow', 'jet',
                          'turbo', 'nipy_spectral', 'gist_ncar']
    }

    # Return the list of colormaps for the given category, or an empty list if the category is not found
    return colormaps_by_category.get(category, [])

```

**Comment by tacaswell** [comment]
In https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.ColormapRegistry it is clearly marked as a subsclass of a `Mapping` and say 

> Read access uses a dict-like interface mapping names to Colormaps:

I think it is reasonable to expect users to infer that `list(my_mapping)` gets you all of the keys in the mapping. 

I think at most we need a note in explain/colors/colormaps.html to the same effect.
