### ISSUE TITLE
Markers in XKCD style

### ISSUE THREAD

**Issue by stfivic** [matplotlib/matplotlib#2625]
Currently, XKCD style is not applied on markers in a plots (e.g. created with plot(x,y,'o') or scatter(X,Y,marker='s')). It would be nice if circles, squares, crosses etc. looks like they are hand drawn.

**Comment by petehuang** [comment]
Reporting from 1.5.3

I think XKCD style applies to markers now, provided you're calling `matplotlib.pyplot.xkcd()` before drawing

**Comment by tacaswell** [comment]
@petehuang How did you test?


```python
 matplotlib.pyplot.xkcd()
plt.plot(range(5), 'o', ms=15)
```

Gives 
![so](https://cloud.githubusercontent.com/assets/199813/21556234/ecb2455a-cdec-11e6-9029-a5944e2636b2.png)

**Comment by petehuang** [comment]
Oops, my bad, you're right
