### ISSUE TITLE
[Bug]: dpi='figure' option no longer working in ``savefig``

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#26252]
### Bug summary

The default ``dpi='figure'`` option in ``savefig`` no longer appears to work correctly - instead the DPI is a fixed value.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure()
fig.set_dpi(10)
ax = fig.add_subplot(1, 1, 1)
fig.savefig("test_dpi.png", dpi="figure")
```

### Actual outcome

A 100 DPI figure:

![test_dpi](https://github.com/matplotlib/matplotlib/assets/314716/017b1cae-e49c-4eac-b1de-a7620b5f5ebe)

### Expected outcome

A 10 DPI figure:

![test_dpi](https://github.com/matplotlib/matplotlib/assets/314716/d7a9ccf7-ee7a-457a-b056-657747efd258)

### Additional information

I bisected this and it appears to have been introduced in https://github.com/matplotlib/matplotlib/pull/19126 - prior to this, it worked fine.

### Operating system

All platforms

### Matplotlib Version

Bug first appeared in Matplotlib 3.5

### Matplotlib Backend

MacOS X and Agg

### Python version

3.11 but seen in other Python versions

### Installation

pip

**Comment by astrofrog** [comment]
This may be a duplicate of https://github.com/matplotlib/matplotlib/issues/24644?

**Comment by tacaswell** [comment]
I'm going to close this in favor of tracking this is #24644, but I do not think we should consider `Figure.set_dpi` as a candidate for deprecation!
