### ISSUE TITLE
[Doc]: Incorrectly drawn bounding box

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#26264]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/figure/figure_intro.html#saving-figures

### Problem

If you have a high-dpi screen (or download the 2x png) the dashed line is the wrong size and shape.

**Comment by tacaswell** [comment]
Thanks to @QuLogic I now have a plan to fix this.

**Comment by jklymak** [comment]
Oh yeah, I noticed that the other day.  It's a function of the 2x images not having the correct bounding box. The 1x is fine (and indeed any fix might break that ;-). 
![](https://matplotlib.org/devdocs/_downloads/acd92db5db80c16ad46152e69561cc6b/figure_intro-5.png)

**Comment by tacaswell** [comment]
```python

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

fig, ax = plt.subplots(figsize=(4, 2), facecolor='lightskyblue')
ax.set_position([0.1, 0.2, 0.8, 0.7])
ax.set_aspect(1)
bb = ax.get_tightbbox()
bb = bb.padded(10)
bb = bb.transformed(fig.dpi_scale_trans.inverted())
fancy = FancyBboxPatch(bb.p0, bb.width, bb.height, fc='none',
                       ec=(0, 0.0, 0, 0.5), lw=2, linestyle='--',
                       transform=fig.dpi_scale_trans,
                       clip_on=False, boxstyle='Square, pad=0')
ax.add_patch(fancy)

```

is the fix.  Discovered that `FancyBboxPatch` pads its input a bit so took a _bit_ of iteration to get there.
