### ISSUE TITLE
[Bug]: qt window blank after using save button

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#26272]
### Bug summary

If you use the "save" button on Qt after the save the window is blank until a redraw is forced (resize the window, pan/zoom by guessing where the axes were, etc).

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt

matplotlib.use('qtagg')
plt.plot(range(5))
plt.show()

# click the save button
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/199813/b9edd284-e6a6-4347-90b4-cddb6a5ea114)

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/199813/fce9f3be-1d05-477b-9cab-5b20751c515f)

### Additional information

- see it with both blocking and non-blocking `show()`
- do not see it with tk (did not test other GUI frameworks)

I think this is a blocker for 3.8 as Qt is the backend a lot of people end up using (because it is the first in our list and conda install pyqt as a Matplotlib dependency) 

### Operating system

Arch

### Matplotlib Version

3.8.0.dev1477+gb274f78060 (~main)

### Matplotlib Backend

QtAgg (with pyqt6)

### Python version

Python 3.13.0a0 (it is actually a branch from a PR)

### Jupyter version

NA

### Installation

git checkout

**Comment by ksunden** [comment]
I do not seem to be able to reproduce in my main dev environment (python 3.11)

**Comment by rcomer** [comment]
I did reproduce using my mpl-dev environment (made using the conda yml).

**Comment by oscargus** [comment]
Can reproduce on Win 11, Python 3.9 and Qt6.

**Comment by rcomer** [comment]
My Ubuntu laptop has only pyqt5, and does not reproduce the problem.

**Comment by rcomer** [comment]
I reproduced on my work machine (RHEL7) but cannot reproduce on my Ubuntu laptop with either pyqt 5 or 6.  I think @ksunden mentioned someone that he uses something related to Ubuntu?

**Comment by jklymak** [comment]
I can reproduce on my Mac dev environment if that helps

```
pyqt                      5.15.7          py311h7203e35_3    conda-forge
...
python                    3.11.0          h3ba56d0_1_cpython    conda-forge
```

**Comment by QuLogic** [comment]
Bisect points to #25713, so I'll do some investigation.
