### ISSUE TITLE
[Bug]: The shadow area can't be rendered by Browsers based on chromium kernel

### ISSUE THREAD

**Issue by WYYAHYT** [matplotlib/matplotlib#26306]
### Bug summary

I ploted a figure with shadow and saved it as pdf, it is available on the jupyter console, but it can't be rendered by browsers like Chrome and Edge.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(5)
stn = [[0, 0, 80, 57, 16], [0, 0, 60, 32, 0]]
fstn = [[10, 22, 61, 84, 119], [8, 19, 29, 47, 44]]
features = [[0, 1, 88, 133, 0], [0, 1, 59, 20, 0]]

fig = plt.figure()
ax = fig.add_axes([0.1, 0.13, 0.8, 0.8])

total_width, n = 0.9, 3
width = total_width / n
x = x - (total_width - width) / 2
ax.set_xticks([0, 1, 2, 3, 4])
ax.set_xticklabels(('64\n(Conv1)', '128\n(Conv2)', '1024\n(Conv3)', '512\n(FC1)', '256\n(FC2)')) 
ax.set_ylim(0, 140)
ax.set_xlabel("filter numbers", fontsize=12)
ax.set_ylabel("update times", fontsize=12)
stn_ax_total = ax.bar(x, stn[0],  width=width, color='#1E90FF', label='stn')
stn_ax_fake = ax.bar(x, stn[1], width=width, color='#1E90FF', hatch='/'*8)
ax.bar_label(stn_ax_total, label_type='edge')
# ax.bar_label(stn_ax_fake, label_type='edge')
fstn_ax_total = ax.bar(x + width, fstn[0], width=width, color='#3CB371', label='fstn')
fstn_ax_fake = ax.bar(x + width, fstn[1], width=width, color='#3CB371', hatch='/'*8)
ax.bar_label(fstn_ax_total, label_type='edge')
# ax.bar_label(fstn_ax_fake, label_type='edge')
features_ax_total = ax.bar(x + 2 * width, features[0], width=width, color='#CD853F', label='features')
features_ax_fake = ax.bar(x + 2 * width, features[1], width=width, color='#CD853F', hatch='/'*8)
ax.bar_label(features_ax_total, label_type='edge')
# ax.grid(axis='y', color = 'gray', linestyle = '--', linewidth = 0.2)
ax.legend(loc="upper left")
plt.text(0.240, 6, r'$\times$', dict(size=10, color='red'))
# plt.show()
plt.tight_layout()
plt.savefig("./test.pdf", dpi=600)
```

### Actual outcome

Actual renderring output on Edge browser: [on_Edge](https://github.com/matplotlib/matplotlib/assets/94819873/b5687034-f0d1-43f5-ae17-a01c687f8e90)

### Expected outcome

![right_out](https://github.com/matplotlib/matplotlib/assets/94819873/c5b4ac21-b0da-4d9f-b0c4-81d04321afa1)

### Matplotlib Version

3.5.3

### Python version

3.7.16

### Jupyter version

6.5.4

### Installation

None

**Comment by tacaswell** [comment]
Does

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

fig, ax = plt.subplots()

ax.add_artist(Rectangle((0, 0), .5, .5, color='red'))
ax.add_artist(Rectangle((.5, .5), .5, .5, facecolor='blue', hatch='//', edgecolor='k'))

fig.savefig('/tmp/test.pdf')
fig.savefig('/tmp/test.png')
```

show the issue for you?  I do not have easy access to edge, but the pdf looks OK to me in brave, vivalid, chrome, chromium, and firefox.

If you can see the issue with that simpler figure then we will need to sort out if we are emitting pdfs that to not match the spec of if edge's pdf renderer is buggy (we have found bugs in renderer libraries before with svg).

**Comment by tacaswell** [comment]
[test.pdf](https://github.com/matplotlib/matplotlib/files/12052535/test.pdf)

It lets us attach pdfs now!

**Comment by QuLogic** [comment]
This appears to be about hatching, not shadows. And this is a known issue with certain renderers, but unknown how it might be fixed.

Closing, as this is tracked in #11418.
