### ISSUE TITLE
[Doc]: Confusing directions in prerelease banner

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#26355]
### Problem

The devdocs warning banner has been restored recently.

![image](https://github.com/matplotlib/matplotlib/assets/2836374/53cd0f85-01ee-4d4e-a5c3-ac3cfb1d7283)

e.g. https://output.circle-artifacts.com/output/job/daa43345-555b-45d6-b6eb-6bfaa9f85dbb/artifacts/0/doc/build/html/index.html

I find 
> Try searching for the released version of this page instead?

quite confusing.

While the related page is likely the first hit, the search page is quite busy and it's hard to see where one wants to go:

![image](https://github.com/matplotlib/matplotlib/assets/2836374/997e70e2-dab6-4d9f-8957-579d3cb28999)

### Suggested improvement

Instead I suggest that the link should be named "Switch to the released version of this page" and have the same effect as selecting "stable" from the version dropdown.

**Comment by timhoffm** [comment]
>  OTOH it will 404 if the page doesn't exist in the released docs. I'm not sure if the link is needed or not.

I can live without the link, but a direct link is ok as well.

404s should be quite rare. They only uccur for pages that we created or moved in the devdocs since the latest release. It's only the development deltas and they fix themselves with the next release. I even suppose that for the 404 cases, the current search mechanism will often not provide an adequate result. The search is by section title, and if we rename a page (e.g. "Development" -> "Contributing") it's likely that the name is not similar anymore.

**Comment by timhoffm** [comment]
Circle outputs are largely irrelevant. People will only get there through github/circle and know that they are in a dev context.

AFAIK one of the main reasons for the banner was that some of these pages showed up in google. I think that has been solved. So the question is, who is getting to devdocs unintendedly at all?

Anyway, I don't want to spend too much effort here. If somebody can make a link to stable, that's good. Otherwise I'll set up a PR to remove the link part completely.

**Comment by timhoffm** [comment]
We now have a new banner:

![image](https://github.com/user-attachments/assets/6d28ae9a-81cc-4d89-ab7f-f03774165d30)

Didn't check, but likely through a newer pydata-sphinx-theme version.

**Comment by QuLogic** [comment]
Yes, it was switched back on in #28336.
