### ISSUE TITLE
[ENH]: Backend Context Manager

### ISSUE THREAD

**Issue by randolf-scholz** [matplotlib/matplotlib#26362]
### Problem

Instead of [`switch_backend`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.switch_backend.html#matplotlib.pyplot.switch_backend), sometimes it might be more appropriate to only use a backend within a context. For example: [temporarily disable figures from showing](https://stackoverflow.com/questions/15713279/calling-pylab-savefig-without-display-in-ipython).

Context managers are the right tool, to ensure `switch_backend` is called again when exiting the context, even if an exception occured.

### Proposed solution

Add a context manager for backends analogous to [`matplotlib.style.context`](https://matplotlib.org/stable/api/style_api.html#matplotlib.style.context).

**Comment by nishar7** [comment]
I am interested in solving this issue.

**Comment by randolf-scholz** [comment]
@timhoffm When I opened this issue, I was writing a library functions that creates multi-page pdf from some timeseries data using `matplotlib`. There were some issues when calling this function from within a jupyter-notebook, which I solved by wrapping the function into a context-manager that switched the backend.

**Comment by timhoffm** [comment]
> There were some issues when calling this function from within a jupyter-notebook

What exactly? The only issue that I could imagine is that the figure is not closed in your function and thus ipython will render it.

**Comment by timhoffm** [comment]
Since matplotlib 3.1 you can create standalone Figures and save them to files. This is likely the better approach for creating isolated plots in a function, compared to fighting the pyplot state.

See for example https://matplotlib.org/devdocs/gallery/user_interfaces/web_application_server_sgskip.html
