### ISSUE TITLE
[doc]: add 'validate' section to install docs

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#26379]
### Documentation Link

https://matplotlib.org/devdocs/devel/development_setup.html

### Problem

The install docs don't have instructions on how to check that the install went through correctly. I think, especially for new contributors, it'd be helpful if we offered a drop more guidance.

### Suggested improvement

Add a new section to https://github.com/matplotlib/matplotlib/blob/main/doc/devel/development_setup.rst after install in editable mode. This section should:

1. Have instructions for checking that the version that's installed <strike>matches the last commit `import matplotib; matplotib.__version__`</strike> is the repo `import matplotlib; matplotlib.__file__`

3. Link to the running the tests page to verify that the code installed clean: https://github.com/matplotlib/matplotlib/blob/main/doc/devel/testing.rst#L35
4. Link to the  building the docs page to verify that the docs build clean: https://github.com/matplotlib/matplotlib/blob/main/doc/devel/document.rst

Tests and docs should be sentences with links (or a bullet list of table) and not the instructions specifically so that this section acts as an introduction/nudge to those pages and so that we won't have to maintain two sets of instructions.

**Comment by timhoffm** [comment]
> 1. Have instructions for checking that the version that's installed matches the last commit `import matplotib; matplotib.__version__`

I'd rather check that `matplotlib.__file__` is the checked out git repo.

**Comment by rcomer** [comment]
Should 2 and 3 come with a warning that they are quite expensive to run?  Also, how much should a contributor worry if some tests fail?  Because some do for me, and I have reason to believe I’m not alone https://github.com/matplotlib/matplotlib/pull/17096#issuecomment-755460601
