### ISSUE TITLE
[ENH]: How to do partial coloring of strings/text？

### ISSUE THREAD

**Issue by dai7599** [matplotlib/matplotlib#26378]
### Problem

Hi,  with follow code:
```
bbox = dict(
    facecolor='white',
    edgecolor='black',
    boxstyle='round,pad=0.2',
)

fig.text(0.12, 0.2,"Today is cloudy" , bbox=bbox)
```
I can get a text: "Today is cloudy"  in a box,  but I'd like to turn "today" into "red" on its own, they're still in a box as a whole.
If I use the `text = r'$\textcolor{red}{Today}$' + ' is cloudy'`,
I will get the error: `Unknown symbol: \textcolor, found '\'  (at char 0), (line:1, col:1)`
So, how to do this?

### Proposed solution

I would like to have a flexible way to set different colors in a string.
Thanks!

**Comment by anntzer** [comment]
For using `\textcolor` this is tracked at #6724 and I think it's a reasonable issue worth looking at.
For the non-usetex case I think this is reasonably well handled by the third-party packages (to whom we can offload the problem of maintaining a specialized formatting language :)) that @story645 pointed to.
