### ISSUE TITLE
[Doc]: Link to gitter is broken in the banner

### ISSUE THREAD

**Issue by stevezhang1999** [matplotlib/matplotlib#26391]
### Documentation Link

https://matplotlib.org/stable/index.html

### Problem

The link to gitter is broken in the top banner, which I guess is outdated.

### Suggested improvement

This link should be good: https://gitter.im/matplotlib/matplotlib

**Comment by jklymak** [comment]
I believe this needs to be fixed at mpl-sphinx-theme.  Thanks for the report, I will close here.

**Comment by jklymak** [comment]
> @jklymak just as an FYI, you can transfer issues between repos you have write permissions on. It's on the lower right hand side:

Sadly not on the iOS app, so far as I can tell.
