### ISSUE TITLE
[Bug]: The vertical end line of BarAB is not center aligned with plot marker

### ISSUE THREAD

**Issue by ilongshan** [matplotlib/matplotlib#26437]
### Bug summary

The vertical end line of BarAB is not center aligned with plot marker.

### Code for reproduction

```python
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 4, 2]
fig, ax = plt.subplots()
ax.plot(x, y, "-o")
ax.annotate("",
            xy=(x[1], y[1]),
            xytext=(x[3], y[3]),
            xycoords="data",
            arrowprops=dict(color="blue", arrowstyle="|-|"),
            textcoords="data",
            ha='center', va='bottom'
            )

plt.show()
```

### Actual outcome

![myplot](https://github.com/matplotlib/matplotlib/assets/7447401/29f06959-2e42-43c1-a3f6-856970a8f2c2)

### Expected outcome

The start and end vertical line should be in the center of markers at (2, 4) and (4,4).

### Operating system

OS/X

### Matplotlib Version

3.7.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.4

### Installation

None

**Comment by timhoffm** [comment]
The ends are on the marker if you set the shrink to 0: `arrowprops=dict(color="blue", arrowstyle="|-|", shrinkA=0, shrinkB=0),`

**Comment by ilongshan** [comment]
Thanks @jklymak @timhoffm, I have set the shrink as suggested. The issue has been resolved.
