### ISSUE TITLE
[Bug]: Key text.latex.preamble: Could not convert ['\\usepackage{bm}'] to str

### ISSUE THREAD

**Issue by SchroedingersLion** [matplotlib/matplotlib#26464]
### Bug summary

[Not sure that this is correct here].

I use Ubuntu 20.04 and freshly installed Anaconda and Latex (the texlive-latex-extra package).
I am trying to use bold symbols in matplotlib figures. Following guidance on other sites [https://stackoverflow.com/questions/58460963/how-to-write-bold-italics-in-math-mode-in-python-matplotlib](url) I try to set
`plt.rcParams['text.latex.preamble'] = [r'\usepackage{bm}']`,
but it gives me 
`ValueError: Key text.latex.preamble: Could not convert ['\\usepackage{bm}'] to str`

It might be an Anaconda rather than a Matplotlib thing though. Any help is appreciated!

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True
plt.rcParams['text.latex.preamble'] = [r'\usepackage{bm}']
```

### Actual outcome

plt.rcParams['text.latex.preamble'] = [r'\usepackage{bm}']

  File ~/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py:718 in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None

ValueError: Key text.latex.preamble: Could not convert ['\\usepackage{bm}'] to str`

### Expected outcome

I'd like to use the \bm latex command in plot labels and titles.

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.7.1

### Matplotlib Backend

Qt5Agg

### Python version

3.11.3

### Installation

conda

**Comment by timhoffm** [comment]
I think you have to pass a single str, not a list of str.

**Comment by SchroedingersLion** [comment]
Thanks @timhoffm,
this seems to work but gives me another error:
`...
  File "/home/anaconda3/lib/python3.11/site-packages/matplotlib/texmanager.py", line 259, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: Failed to process string with tex because dvipng could not be found`

**Comment by drudox** [comment]
but what if you need more than a package to be used in Latex... befor Im used in this way:


`plt.rcParams['text.latex.preamble'] = [r'\usepackage{amsmath}', r'\usepackage[osf,sc]{mathpazo}']`
but how can I do now ? I got the same error

**Comment by QuLogic** [comment]
Just pass a single string; there's nothing different between one package or multiple.

**Comment by drudox** [comment]
what do you mean single string ? like : 

 `plt.rcParams['text.latex.preamble'] ="\usepackage{amsmath}, \usepackage[osf,sc]{mathpazo}'"
`
thanks for your support!

**Comment by QuLogic** [comment]
The string should be as you would write it in LaTeX. No extra commas or quotes.

**Comment by drudox** [comment]
I didn t catch sorry :( can you make an example ... you mean this : 

plt.rcParams['text.latex.preamble'] =  "  \usepackage{amsmath}  \usepackage[osf,sc]{mathpazo} "
