### ISSUE TITLE
[Bug]: 3D Plots with Jupyter Notebooks get cropped in VS Code and Jupyter Lab

### ISSUE THREAD

**Issue by DavidSiretMarques** [matplotlib/matplotlib#26465]
### Bug summary

When trying to do a 3D plot in VS Code, the crop gets cropped, not showing the z-label. See [this issue](https://github.com/microsoft/vscode-jupyter/issues/13661) for more information

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
# Fixing random state for reproducibility
np.random.seed(19680801)
def randrange(n, vmin, vmax):
"""
Helper function to make an array of random numbers having shape (n, )
with each number distributed Uniform(vmin, vmax)."""
return (vmax - vmin)*np.random.rand(n) + vmin
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
n = 100
# For each set of style and range settings, plot n random points in the box
# defined by x in [23, 32], y in [0, 100], z in [zlow, zhigh].
for m, zlow, zhigh in [('o', -50, -25), ('^', -30, -5)]:
    xs = randrange(n, 23, 32)
    ys = randrange(n, 0, 100)
    zs = randrange(n, zlow, zhigh)
    ax.scatter(xs, ys, zs, marker=m)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()
```

### Actual outcome

In Jupyter lab online it works:

![image](https://github.com/microsoft/vscode-jupyter/assets/57282198/64a72138-17ea-4688-8119-555bf6c87d64)

In VS Code it crops the plot:

![image](https://github.com/microsoft/vscode-jupyter/assets/57282198/798b9407-d07c-4d92-9845-ccca90b9bc28)

And apparently in Jupyter Lab in a machine it crops the plot too (I haven't tried this, I was told this was the case in the other issue I've referenced)

### Expected outcome

I'd expect all the plots to behave like the one in Jupyter lab online, i.e.

![image](https://github.com/microsoft/vscode-jupyter/assets/57282198/64a72138-17ea-4688-8119-555bf6c87d64)

### Additional information

I downloaded the [scatter 3d ipynb](https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html) from the matplotlib site and run it in my machine inside VS Code, the plot gets cropped

### Operating system

Windows

### Matplotlib Version

3.7.1

### Matplotlib Backend

QtAgg

### Python version

3.9.16

### Jupyter version

6.5.4

### Installation

conda

**Comment by tacaswell** [comment]
I suspect that this is another case of the inline backend saving with `bbox_inches='tight'`.  I suspect in all cases if you do `fig.savefig(...)` it will be clipped.

Do you have a figure size set in rcparams?  If I run the code I get:

![so](https://github.com/matplotlib/matplotlib/assets/199813/0e65d627-de04-45fc-9c18-6124a3a9ea5c)

note that there is a bunch of white space on either side and the figure has a 4:3 ratio.

**Comment by DavidSiretMarques** [comment]
Not that I'm aware of... I just downloaded the [3dscatter.ipynb](https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html) from the matplotlib examples page and run it. The image gets cropped in the z-label.

**Comment by DavidSiretMarques** [comment]
I tried doing the `fig.savefig(...)` and the image (see below) isn't cropped
![figure](https://github.com/matplotlib/matplotlib/assets/57282198/5ace53fc-5303-42df-bea5-bc4d85922cb0)

 but in the inline it is, so it seems your suspicions might be correct.

How can it be solved?

**Comment by DavidSiretMarques** [comment]
That seems to solve the problem, although now it has a bunch of blank space around, Thanks for everything, you may close the issue now if you want (I do think there should be some changes if the default is giving this cropping behavior... But that's for you to decide

Thanks again

**Comment by timhoffm** [comment]
That default setting is in the responsibility of the ipython InlineBackend. Changes to that would need to be discussed there.
