### ISSUE TITLE
[ENH]: Add interpolation_stage selector for images in qt figureoptions

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#26477]
### Problem

There's already an interactive qt selector for the interpolation method, but not yet for the interpolation_stage, which is just as (if not more) important.

### Proposed solution

Add it.

**Comment by Tsufael** [comment]
Hi,

I'm working on this issue as my first contribution to matplotlib.

I added the qt selector for interpolation_stage and it appears to be working. However, I currently hardcoded 'data' and 'rgba' as the possible options for the selector and I was wondering what would be the best way to get the option names.

The qt_selector for interpolations gets the valid options from matplotlib.image.interpolations_names, but there's no matplotlib.image.interpolation_stages_names. Should it be added?

I also saw there's a line in lib/matplotlib/image.pyi:76 stating the possible values for interpolation_stage are 'data', 'rgba' and None, but I'm not sure about how to use it to get those values or if it would be appropriate.

Maybe I'm overthinking it and hordcoding is fine as there are only two possible options, I just wanted to make sure it don't breaks if the names changed or more options were to be added in the future.

**Comment by jklymak** [comment]
Hardcoding should be fine.  There are really only two possibilities.

**Comment by AnnaMastori** [comment]
Hi, 
@Tsufael are you still working on the pull request ? If not, I would like to give it a try.

**Comment by Tsufael** [comment]
Hi @AnnaMastori,
I have opened [this PR](https://github.com/matplotlib/matplotlib/pull/26500) on this issue.
I'll try to fix the mypy error this week following what oscargus said.
