### ISSUE TITLE
[Doc]: match 3D plot types listings titles to other titles

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#26486]
### Documentation Link

https://matplotlib.org/devdocs/plot_types/index.html

### Problem

The plot listings in plots types all have signature + data args except the 3D section. 

### Suggested improvement

The titles of the 3d plots should be updated to match the format of the other titles, which is `function_name(data specific args)`

**Comment by SunSummoner** [comment]
@story645 can you assign this issue to me, if its not already taken?

**Comment by SunSummoner** [comment]
No worries @story645. Can I work on the open issues without PRs?
