### ISSUE TITLE
[ENH]: Support for html color names

### ISSUE THREAD

**Issue by czwilling** [matplotlib/matplotlib#26496]
### Problem

* color argument in all plots does only accept a limited set of  colors.

### Proposed solution

For better readibility and usability it would really be helpful to support a larger set of html color names, e.g. as in [https://htmlcolorcodes.com/color-names/](https://htmlcolorcodes.com/color-names/)

**Comment by rcomer** [comment]
We support these CSS colour names:
https://matplotlib.org/stable/gallery/color/named_colors.html#css-colors
