### ISSUE TITLE
[Bug]: 3d interactive axes rotation is uninituitive

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#26492]
### Summary

Clicking and moving the mouse e.g. left-right over the top part of a 3d axes seems to always rotate the axes along the *data* z-direction, no matter what that direction is on screen.  This means that if the data z-axis is oriented "normal to the screen", then the same mouse motion can rotate the axes visually clockwise or counterclockwise (first two cases below); if the data z-axis is oriented "in the screen" then the rotation is again different (last case below).

https://github.com/matplotlib/matplotlib/assets/1322974/98588ba4-f81d-4469-9ced-3df237d182e6

### Proposed fix

Probably(?) mouse-interactive rotations should be relative to *screen* directions rather than *data* axes directions.

For the record, the axes above were generated with
```python
a0, a1, a2 = plt.figure(figsize=(12, 4)).subplots(1, 3, subplot_kw=dict(projection="3d", xlabel="x", ylabel="y", zlabel="z"))
a0.elev, a0.azim, a0.roll = -90, 90, 0
a1.elev, a1.azim, a1.roll = 90, 90, 0
a2.elev, a2.azim, a2.roll = 0, 90, 0
```

**Comment by WeatherGod** [comment]
I agree. The interaction has always been janky, but I could never quite put
my finger on it. I think your assessment is right.

**Comment by patilniraj8** [comment]
You can reach out to us through this mail nirajpatil849@gmail.com We would like to contribute in this

**Comment by anntzer** [comment]
Superseded by #28288.
