### ISSUE TITLE
[Doc]: Pyplot Axes – tuple or list?

### ISSUE THREAD

**Issue by EngineerKhan** [matplotlib/matplotlib#26508]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axes.html

### Problem

It reads: "4-tuple of floats rect = [left, bottom, width, height]. "

Shouldn't it be a list?

### Suggested improvement

Perhaps we should go for the tuples here.

**Comment by rcomer** [comment]
Thanks @EngineerKhan, I think either will work, but I agree this docstring should be self-consistent.  Changing it as you say would make it match [fig.add_axes](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_axes) (which it calls underneath).  Would you like to make a PR?

**Comment by EngineerKhan** [comment]
@rcomer I have made the PR. Please check if it sounds good.

**Comment by rcomer** [comment]
@EngineerKhan I cannot see a pull request from you.

**Comment by EngineerKhan** [comment]
@rcomer Maybe I done it wrongly? Can you please check [it](https://github.com/EngineerKhan/matplotlib/commit/1fb92fcaf7423ebe282d7a7dc0f8f1214c055e95) again?

**Comment by rcomer** [comment]
@EngineerKhan it looks like you still need to create the pull request from your branch.  If you go [here](https://github.com/matplotlib/matplotlib/pulls) then you should see a "New pull request" button.

**Comment by EngineerKhan** [comment]
@rcomer My bad. I have made [one now](https://github.com/matplotlib/matplotlib/pull/26521). Hope it's the right way to do it.
