### ISSUE TITLE
[ENH]: Automate subplots layout with `n` subplots

### ISSUE THREAD

**Issue by tinosulzer** [matplotlib/matplotlib#26512]
### Problem

I often have a list of `n` things to plot in different subplots, and I want to create subplots automatically that have an as-square-as-possible layout. For example, if I have 2-3 subplots, I only want 1 row, if I have 4-8, I want 2 rows of 2-4, if I have 9, I want 3x3, etc.
Additionally, the default figsize should scale with the number of figures.

### Proposed solution

Full solution including MWE:
```
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-1,1,100)
powers = {i: x**i for i in range(7)}

# Solution #########
n = len(powers)
n_rows = int(n // np.sqrt(n))
n_cols = int(np.ceil(n / n_rows))
figwidth_default = min(15, 4 * n_cols)
figheight_default = min(8, 1 + 3 * n_rows)
figsize = (figwidth_default, figheight_default)
fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize, layout="constrained")
################

for ax, (name, power) in zip(axes.flatten(), powers.items()):
    ax.plot(x, power)
    ax.set_title(f"x^{name}")
plt.show()
```

**Comment by oscargus** [comment]
You may want to consider using https://github.com/matplotlib/grid-strategy

**Comment by tinosulzer** [comment]
Perfect, thank you!
