### ISSUE TITLE
``CGContextRef is NULL`` of `tight_layout` with MacOSX backend

### ISSUE THREAD

**Issue by eteq** [matplotlib/matplotlib#2654]
This may be related to #166, but has a quite different immediate cause, so I'm reporting it separately. It *might* be that I should instead report this in ipython, so feel free to redirect me there, if that's more appropriate

If I do the following in ipython started with ``ipython -pylab=MacOSX`` :
```
def dp(x):
    plt.figure()
    plt.plot(x)
    plt.tight_layout()
dp(arange(10))
```
I get a  ``CGContextRef is NULL`` exception (full traceback in the first comment).  The plot still appears, but it does not have the tight-layout applied.  If I change the function instead to:
```
def dp(x):
    plt.figure()
    plt.plot(x)
    plt.draw()
    plt.tight_layout()
```
it *does* work, with no exception.  

Not that the same thing also happens if I use subplots instead of a single figure.

**Comment by huangshiyu13** [comment]
I just add plt.show() before tight_layout() as below. And it works for me.

`import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="dark")
rs = np.random.RandomState(50)

# Set up the matplotlib figure
f, axes = plt.subplots(3, 3, figsize=(9, 9), sharex=True, sharey=True)

# Rotate the starting point around the cubehelix hue circle
for ax, s in zip(axes.flat, np.linspace(0, 3, 10)):

    # Create a cubehelix colormap to use with kdeplot
    cmap = sns.cubehelix_palette(start=s, light=1, as_cmap=True)

    # Generate and plot a random bivariate dataset
    x, y = rs.randn(2, 50)
    sns.kdeplot(x, y, cmap=cmap, shade=True, cut=5, ax=ax)
    ax.set(xlim=(-3, 3), ylim=(-3, 3))
plt.show()  # I just add this line, and it works
f.tight_layout()`
