### ISSUE TITLE
[Bug]: full-width axvspan does not reach the borders evenly on all sides

### ISSUE THREAD

**Issue by milosivanovic** [matplotlib/matplotlib#26559]
### Bug summary

1. Take the code from https://matplotlib.org/stable/gallery/lines_bars_and_markers/simple_plot.html
2. Set x margin to zero
3. Add `axvspan` with a border and higher zorder than the rest of the plot (border only set here for emphasis) across the entire x axis

The `axvspan`'s border draws on **top of the plot's top and left border**, but not the **bottom and right border**.

I'm not exactly sure which border should come out on top here. My guess would be that the plot's border should always contain everything within it, meaning the avxspan should not cover the top and left plot border.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.margins(x=0)
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
plt.axvspan(0, 2, facecolor='0.9', alpha=0.8, zorder=12, edgecolor='red')

fig.savefig("test.png")
plt.show()
```

### Actual outcome

![axvspan_simple](https://github.com/matplotlib/matplotlib/assets/1274505/236ef37f-74ed-4ddd-aa71-934b8d9e10d4)

### Expected outcome

Either the plot's (black) border should be on top, or the axvspan's (red) border should be on top.

### Matplotlib Version

3.7.2

### Installation

None

**Comment by ksunden** [comment]
With a zorder of 12, I would expect the vspan to be on top (spines have a default zorder of 2.5)

If you do not specify the zorder, then it defaults to 1 and is correctly drawn such that the black spines are above the red vspan.

It becomes a bit more obvious what is happening if you increase the linewidth, eg `lw=4`.
The clip box (which prevents things from the axes from being drawn outside of the axes) for the axes applies to the vspan's polygon, but not to the spines, thus at the edge, some pixels are considered "inside" the clip box, and some are considered "outside". Combine that with pixel-snapping of drawing the spine's lines, this is edge case behavior that I don't think there is a "correct" answer for. Increasing DPI may help, but see below for more complete answers.


- If you just want consistent, consider setting zorder to `2.4` (or some other number that is above the other things in the plot (usually mostly 1.0) but below the spines (2.4), or raise the spine's zorder)

- If you _want_ the vspan to have its full borders, consider setting the clip box  to have a bit of padding:

```python
import matplotlib.transforms as mtransforms

span = ax.axvspan(...)
span.set_clip_box(mtransforms.TransformedBbox(mtransforms.Bbox.unit().padded(.01), ax.transAxes))
```

The default is a unit bbox transformed by transAxes
Note that .01 is in Axes relative units, and thus the desirable number will depend on the size of the axes. (It's not a problem for the vspan being within the axes or right on the edge, but if the vspan is wider on either side, it is perhaps undesireable for that edge to extend over the spines.)
A more proper fix would be to pad in screen space, which is possible, but a bit harder to do in a way that will allow for figure/axes resizes (e.g. interactive window changing size)...

- if all you want is a static figure, then the following will suffice:

```python
span = ax.axvspan(...)
span.set_clip_box(span.get_clip_box().padded(4)) # Number is in units of pixels here, so how how large will depend on linewidth, dpi, etc.
```

Note that `.padded` strips the clip box of its relation to `transAxes`, and thus you will get weird clipping happening if the figure canvas is resized.

After investigating, I think this _is_ an edge case, but is "expected" behavior in some sense, so I think I will close with no action.
