### ISSUE TITLE
matplotlib not working in python 3.11.4[Bug]: 

### ISSUE THREAD

**Issue by kashif1973** [matplotlib/matplotlib#26561]
### Bug summary

cannot run code.

### Code for reproduction

```python
import numpy as np
#from random import gauss
#from random import seed
#from pandas import Series
import matplotlib.pyplot as plt 
#import math

###variable declaration
R=0.000001 #radiaus of particle
beta=0.23 # shape factor
Ad=9.2#characteristic nanoscale defect area
gamma=4*10**-2 #surface tension
tau=.0001 #line tension

phi=-(np.pi/2)#spatial perturbation
lamda=((Ad)/(2*3.14*R)) #averge contcat line position

mu=0.001#viscosity of liquid
lamda_m=10**-9# characteristic size of adsorption site
KbT=(1.38**-24)*293 # boltzman constant with tempartaure
nu=0.001#moleculer volume in liquid phase 1
khi=3 #scaling factor
#deltaF=(beta*gamma*Ad)#surface energy perturbation
deltaF=19*KbT


##quantities moved out of the for-loop:
theta_e=((np.pi*110)/180) #equilibrium contact angle
Z_e=-R*np.cos(theta_e)#equilibrium position of particle
C=3.14*gamma*(R-Z_e) #additive constant
w_a=gamma*lamda_m**2*(1-np.cos(theta_e)) #work of adhesion

#########################################
Z=0.0000001 #particle position
##time=1
dt=1

Z_all = []
time_all = np.arange(1, 100, dt)
# seed random number generator
# seed(0)
np.random.seed(0)
# create white noise series
##series = [gauss(0.0, 1.0) for i in range(1)]
##series = Series(series)
series = np.random.normal(0.0, 1.0, len(time_all))

for time, S in zip(time_all,series):
#####simulation loop#######
    Z_all.append(Z)
    theta=np.arccos(-Z/R) #contact angle
    Fsz= (gamma*np.pi*(Z-Z_e)**2)+(tau*2*np.pi*np.sqrt(R**2-Z**2))+C
    Fz=Fsz+(0.5*deltaF*np.sin((2*np.pi/lamda)*(Z-Z_e)-phi))#surface force
    #dFz=(((gamma*Ad)/2)*np.sin(2*np.pi/lamda))+((Z-Z_e)*(2*gamma*np.pi))-((tau*2*np.pi*Z)/(np.sqrt(R**2-Z**2)))
    dFz=(deltaF*np.sin(2*np.pi/lamda))+((Z-Z_e)*(2*gamma*np.pi))-((tau*2*np.pi*Z)/(np.sqrt(R**2-Z**2)))
    epsilon_z=2*np.pi*R*np.sin(theta)*mu*(nu/(lamda_m**3))*np.exp(w_a/KbT)#transitional drag
    epsilon_s=khi*mu*((4*np.pi**2*R**2)/np.sqrt(Ad))*(1-(Z/R)**2)
    epsilon=epsilon_z+epsilon_s
    Ft=np.sqrt(2*KbT*epsilon)*S #series #thermal force
    v=(dFz+Ft)/epsilon ##new velocity
    Z=Z+v*dt #new position    
    print('z=',Z)
    print('v=',v)
    print('Fz=',Fz)
    print('dFz',dFz)
    print('time',time)    


fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(8,4))

axes[0].plot(Z_all,time_all)
axes[0].set_xlabel('Z')
axes[0].set_ylabel('t')

axes[1].plot(time_all, Z_all)
axes[1].set_xlabel('t')
axes[1].set_ylabel('Z')

fig.tight_layout()

plt.show()
```

### Actual outcome

following error occured after installing matplotlib
Traceback (most recent call last):
  File "d:\python\Other codes\PathPlanning-master\Search_based_Planning\Search_2D\try.py", line 5, in <module>
    import matplotlib.pyplot as plt
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Other codes\PathPlanning-master\venv\Lib\site-packages\matplotlib\__init__.py", line 242, in <module>
    _check_versions()
  File "D:\python\Other codes\PathPlanning-master\venv\Lib\site-packages\matplotlib\__init__.py", line 236, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Other codes\PathPlanning-master\venv\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.
PS D:\python\Other codes\PathPlanning-master> 

### Expected outcome

cannot run therefore expected output cannot be pasted

### Matplotlib Version

3.7.2

### Installation

pip

**Comment by stevezhang1999** [comment]
You could try reinstalling `kiwisolver` or the whole venv. Fore more information see https://github.com/matplotlib/matplotlib/issues/25680

**Comment by kashif1973** [comment]
yes installed again but same error persists
