### ISSUE TITLE
[ENH]: Support SubFigure.remove()

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#26593]
### Problem

Currently SubFigures cannot be remove()d from the parent figure.  The API would be more consistent if that was possible.

### Proposed solution

Implement SubFigure.remove().

**Comment by nithin-nk** [comment]
I'll work on this

**Comment by jklymak** [comment]
`sfig.remove()` would remove the subfigure and all its children from the figure.   Note that our removal machinery is non-trivial, but doing something similar as what is done for axes should work.  I'm not 100% sure how the tree gets traversed. 

If someone works on this, it would be nice to write up your notes so we can document how `remove` is meant to work.
