### ISSUE TITLE
[Bug]: Histogram plot collapses to thin lines under some circumstances

### ISSUE THREAD

**Issue by afarcy** [matplotlib/matplotlib#26592]
### Bug summary

Histogram plot usually works fine but when values differ by a very small amount the plot is not scaled properly and bins become very thin.

The demo code uses a vector full of the same values (`0.025`), then introduces a very small delta (`DELTA`). The vector now contains 2 (or `N_BASE_VALUES`) possible values.
The plot is done with an histogram with 20 (or `N_COLUMNS`) bins.

### Code for reproduction

```python
import numpy
import matplotlib.pyplot as plt


N_BASE_VALUES = 2
DELTA = 1.0e-14
N_COLUMNS = 20
if True: # Almost nothing shown. But if you zoom around 0, 2 vertical lines appear.
    DELTA = 1.0e-15
    if False: # Show a line.
        N_COLUMNS = 21

x = numpy.full((64,), 0.025)
numerical_error = numpy.random.randint(0, N_BASE_VALUES, x.shape)
numerical_error = numerical_error * 2 - 1 # Random 0, 1 (or also -1 if N_BASE_VALUES == 3)

x = x + numerical_error * DELTA # Introduce some variance.

#hist, bins = numpy.histogram(x, N_COLUMNS)
#print(hist, bins)

fig, ax = plt.subplots()
n, bins, _ = ax.hist(x, N_COLUMNS, align='left')
print(n, bins)

plt.show()
```

### Actual outcome

A plot with 2 visible bins.
Put `False` in both ifs to see the "normal" behavior.

### Expected outcome

Several manifestations:
1. Enable the 1st `if`. Nothing is shown but zooming around x=0 one can see the bins appear. Basically the axis are not correct.
2. Enable the 2nd `if`. Now a tall vertical line is shown. Again, zooming make the 2 bins appear.

### Additional information

Prototyping with small standalone python script (so tkinter/TkAgg backend) but the issue is visible from a complete Qt application too.

### Operating system

Debian

### Matplotlib Version

3.6.3

### Matplotlib Backend

TkAgg

### Python version

3.11.2

### Installation

pip

**Comment by timhoffm** [comment]
With `DELTA = 1.0e-15`, you are very close to the double precision limit. The histogram and/or bar position calculation are likely affected by numerical jitter, which explains why the bars appear and disappear when zooming. This is a fundamental limit of your numerical representation and we cannot do anything about this.
