### ISSUE TITLE
[Doc]: Inappropriate example in gallery

### ISSUE THREAD

**Issue by jsdodge** [matplotlib/matplotlib#26604]
### Documentation Link

https://matplotlib.org/stable/gallery/statistics/histogram_features.html

### Problem

* Given the sordid historical misuse of IQ, this gallery example unnecessarily reinforces a crude association between IQ and "smarts" that distracts from the main point, which is to show how to make a histogram.
* Any attempt to contextualize the meaning of IQ would further distract from this point, so it would be better to just change the axis labels to avoid the negative association.

### Suggested improvement

* Remove the axis labels altogether, as was done [here](https://matplotlib.org/stable/gallery/statistics/hist.html#histograms), or change the simulation example to something more neutral, such as the masses of apples from a hypothetical farm.

**Comment by jklymak** [comment]
I agree that examples should avoid issues to do with humans that could be misconstrued, no matter how well meaning. This is a pretty easy fix if anyone wants to come up with a better example.

**Comment by gautamsagar99** [comment]
Hello,

I'm new to open source contribution, I want to solve this good first issue. I hope no one had created a PR for this issue can I start working on it?

Thanks

**Comment by RohanG610** [comment]
Is this issue still open?

**Comment by sagniksantra** [comment]
If the issue is still open, can you please assign me? Would love to work on it.

**Comment by rcomer** [comment]
@sagniksantra we do not assign issues.  Please see our contributors’ guide:
https://matplotlib.org/devdocs/devel/contributing.html
