### ISSUE TITLE
[Bug]: An axis' aspect ratio is not inherrited by ax.quiver arrows

### ISSUE THREAD

**Issue by asher-m** [matplotlib/matplotlib#26611]
### Bug summary

Arrows drawn by `ax.quiver` do not inherit the aspect ratio of the axis to which the arrows belong.

This is demonstrably true when the user specifies a non-equal aspect ratio, but it also seems to be true even when the aspect ratio is chosen by matplotlib (ie., only figure size is specified.)

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np



xx, yy = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
u, v = 10 * np.ones_like(xx), 10 * np.ones_like(yy)

#### BAD
fig, ax = plt.subplots()
ax.quiver(xx, yy, u, v)
ax.set_aspect(0.1)
plt.savefig('bad.png')

#### GOOD
fig, ax = plt.subplots()
ax.quiver(xx, yy, u, v)
ax.set_aspect(1)  # or `ax.set_aspect('equal')`
plt.savefig('good.png')
```

### Actual outcome

Bad—notice that the _drawn_ angle of the arrows is _still_ 45°, despite the aspect ratio being 1:0.1.  As shown, the angle of the arrows should be arctan(0.1 / 1) = 5.7° (roughly flat):
![bad](https://github.com/matplotlib/matplotlib/assets/29708595/0b6fe00f-65f4-461d-a0d4-cca7052f466e)

Good:
![good](https://github.com/matplotlib/matplotlib/assets/29708595/aacbe408-70b8-48f5-870b-6ed46b009c9c)

### Expected outcome

Aspect of the figure should also adjust the aspect ratio of the arrows.  For example, with square/equal aspect ratio, as above:
![good](https://github.com/matplotlib/matplotlib/assets/29708595/e7197223-4086-401d-bc89-0a7cdd74131e)

Or, from the following code:
```python
import matplotlib.pyplot as plt
import numpy as np



xx, yy = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
u, v = 10 * np.ones_like(xx), 10 * np.ones_like(yy)

#### FIXED
fig, ax = plt.subplots()
ax.set_aspect(0.1)  # this seems like an unfortunate "fix"; there are definitely better options
ax.quiver(xx, yy, u, v * ax.get_aspect())
plt.savefig('fixed.png')
```
![fixed](https://github.com/matplotlib/matplotlib/assets/29708595/45ad7128-5aa4-4b08-8c28-9b01c9a26ca5)

(Ie., the aspect ratio of the figure should be used to draw the arrows/slope field.)

### Additional information

If this is an intentional design decision, it should be documented that arrows are not drawn with respect to the aspect ratio of the figure, and that the user should consider this and implement any change necessary to their code, (ie., `v *= ax.get_aspect()`).

### Operating system

Windows

### Matplotlib Version

3.7.1

### Matplotlib Backend

QtAgg

### Python version

Python 3.11.4

### Jupyter version

6.5.4

### Installation

conda

**Comment by timhoffm** [comment]
you need to set `quiver(..., angle="xy")` if you want the arrow direction to be in data coordinates.

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver
