### ISSUE TITLE
[Doc]: FAQ is not reachable anymore via the main menu

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#26627]
### Documentation Link

https://matplotlib.org/devdocs/users/faq/index.html

### Problem

AFAICS the only link to this page (and child pages) is in the boxes on the index page https://matplotlib.org/devdocs/.

This is hard to find.

IMHO all pages should be accessible via a chain of links starting from the main menu, because the main menu is the entry point to navigating the site.

**Comment by timhoffm** [comment]
> Um what do you mean by main menu in this context given that it's in the main index?

I want to click on a menu item here:
![grafik](https://github.com/matplotlib/matplotlib/assets/2836374/fa8881de-78ed-485e-928e-51aca92de35e)

and on the opened page possibly 1-2 subsequent clicks on toc entries to reach the FAQ.

**Comment by jklymak** [comment]
Getting Started, Install, and FAQ were all moved to the top level index in https://github.com/matplotlib/matplotlib/pull/26332. None of them is currently accessible from any links in the upper bar (except the Matplotlib logo)
