### ISSUE TITLE
[Doc]: Reduce references to set_tight_layout

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#26637]
### Documentation Link

https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.set_tight_layout

### Problem

`set_tight_layout` is deprecated.
```
galleries/users_explain/axes/tight_layout_guide.py:# time the figure is redrawn, you can call ``fig.set_tight_layout(True)``, or,
lib/matplotlib/figure.py:            Whether to use the tight layout mechanism. See `.set_tight_layout`.
lib/matplotlib/figure.py:                ``tight_layout=True`` and use `.set_tight_layout` otherwise.
lib/matplotlib/figure.py:              decorations do not overlap. See `.set_tight_layout` for
```

### Suggested improvement

Better to point to something else. Not sure if that should be `TightLayoutEngine` or the tight layout guide or what.

**Comment by QuLogic** [comment]
> `` galleries/users_explain/axes/tight_layout_guide.py:# time the figure is redrawn, you can call ``fig.set_tight_layout(True)``, or, ``

This one is gone already.

> lib/matplotlib/figure.py:            Whether to use the tight layout mechanism. See `.set_tight_layout`.
> lib/matplotlib/figure.py:                ``tight_layout=True`` and use `.set_tight_layout` otherwise.

These are cross references for the `tight_layout` parameter, which is also discouraged, so I don't know that they need to be removed.

> lib/matplotlib/figure.py:              decorations do not overlap. See `.set_tight_layout` for

This one is the `layout` parameter, and maybe should point to `TightLayoutEngine` as well.
