### ISSUE TITLE
[Bug]: Subplots display problem on MacOS

### ISSUE THREAD

**Issue by H-tr** [matplotlib/matplotlib#26630]
### Bug summary

One of the subplots couldn't display on screen for mac

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

Fm = 100
t1 = np.linspace(0, 0.1, 200)
y1 = np.sin(2 * np.pi * Fm * t1 + np.pi / 6)  # Sine wave

fig, (ax1, ax2) = plt.subplots(1, 2, figsize = (10, 4), constrained_layout = True)
ax1.plot(t1, y1, 'b', label='continuous')
ax1.set_title("Sine wave")
ax1.set_xlabel('time in sec')
ax1.set_ylabel('y(t)')

fs1 = int(input("Enter the sampling frequency: ")) # sampling rate
n1 = np.arange(0, 0.1 * fs1) / fs1
x1 = np.sin(2 * np.pi * Fm * n1 + np.pi / 6)
ax2.plot(n1, x1, 'b', label='discrete')
ax2.set_title("discrete time signal x(n) with fs = " + str(fs1))
ax2.set_xlabel('time in sec')
ax2.set_ylabel('x(t)')

plt.show()
```

### Actual outcome

![WechatIMG9894](https://github.com/matplotlib/matplotlib/assets/63481622/d5aadaa4-bce2-4dcb-8016-149a1d842b33)

### Expected outcome

![WechatIMG9895](https://github.com/matplotlib/matplotlib/assets/63481622/d62b9d51-fa64-43cd-84d1-3f21a120a4cc)

### Additional information

The figure is correct after saving it.

### Operating system

MacOSX, Ventura 13.5

### Matplotlib Version

3.7.2

### Matplotlib Backend

MacOSX

### Python version

3.8.17

### Installation

pip

**Comment by timhoffm** [comment]
Does it work with other backends?

e.g. prepend
```
import matplotlib
matplotlib.use("TkAgg")
```

**Comment by H-tr** [comment]
It works on TkAgg

**Comment by greglucas** [comment]
I can reproduce the error on `3.7.2`, but it works with the release candidate `pip install --pre matplotlib==3.8.0rc1`. Are we making another 3.7 patch release and would this be worth bisecting to find what fixed it and backporting?

**Comment by timhoffm** [comment]
3.8 should be out soonish. Let's not invest extra effort here.

**Comment by QuLogic** [comment]
> I can reproduce the error on `3.7.2`, but it works with the release candidate `pip install --pre matplotlib==3.8.0rc1`. Are we making another 3.7 patch release and would this be worth bisecting to find what fixed it and backporting? (my inclination is to not find and backport this and the solution being to upgrade once 3.8 is out)

I do plan to do 3.7.3 by the beginning of next week (or preferably end of this one), regardless of if we can figure out #26463, so if you want to go look, you can, but it'd have to be fixed rather quickly
