### ISSUE TITLE
MultiCursor widget feature request - independent axes

### ISSUE THREAD

**Issue by kogelnik** [matplotlib/matplotlib#2664]
The MultiCursor widget allows for <i>x</i> and <i>y</i> cursor support across a number of axes.  When <i>horizOn</i> is enabled, a horizontal cursor line is drawn.  This is drawn on all axes regardless of if they are shared or not, provided that the <i>y</i> value of the pointer axes is in the <i>y</i> data range of the other axes.  

Where data is <i>unrelated</i> this is not a desirable feature.  Therefore I would like to ask for a new feature that would just draw the horizontal cursor line for the axes where the pointer is, and not for any other.  For generality is may be nice to offer per axes control, but initially just inhibiting this shared behavior would be good.  Perhaps call it <i>horiz_local</i>.

Thanks!

```
# show how x cursor line in drawn on multiple axes when data range overlaps
import matplotlib.pyplot as plt
from matplotlib.widgets import MultiCursor
import numpy as np

x = np.arange(0.0, 10.0)
y1 = np.arange(0.0, 10.0)
y2 = np.arange(15.0, 5.0, -1)

fig = plt.figure()
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212, sharex=ax1)

ax1.plot(x, y1)
ax2.plot(x, y2)

cursor = MultiCursor(
  fig.canvas, (ax1, ax2), color='r', lw=1, horizOn=True, vertOn=True)

plt.show()
```

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue. Thanks!

**Comment by anntzer** [comment]
I think the idea was to get the vertical cursor shared across axes but the horizontal one only on a given axis, which seems like a reasonable request.

**Comment by plasim** [comment]
I'm voting for this feature. Now having to make multiple MultiCursor/Cursors to achieve this. The order of these needs to be specific to avoid blit leaving some subplots without cursor line. Not sure but also the drawing speed might be reduced with multiple blit elements.

**Comment by landsite** [comment]
A simple workaround to this is on the manipulation of hlines list that is used by MultiCursor internally.
