### ISSUE TITLE
[ENH]: fillstyle argument None should be equivalent to 'none'

### ISSUE THREAD

**Issue by whbdupree** [matplotlib/matplotlib#26678]
### Problem

I get frustrated when I use fillstyle, because I am often trying to create empty circles. I always always always type out `fillstyle=None`, which is neither a valid argument nor throws a warning or error.

### Proposed solution

Please make `fillstyle=None` equivalent to `fillstyle='none'`

**Comment by jklymak** [comment]
For better or worse, "None" in Matplotlib means "default". This is very pervasive in the library so I don't think we can change it even if we wanted to.

**Comment by anntzer** [comment]
Agreed this is consistent with Matplotlib's standard semantics (which may not be Python's standard semantics, but heh).
