### ISSUE TITLE
[Bug]: deprecated functions conflict with PySide's snake_case __feature__

### ISSUE THREAD

**Issue by ctismer** [matplotlib/matplotlib#26677]
### Bug summary

When using the PySide snake_case feature, we get a clash with deprecated functions in backend_bases.py .
The simple cure to work around that is to remove those deprecated 3.6-functions.

### Code for reproduction

```python
test_graphing.py:
-----------------
import numpy as np

# https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_qt_sgskip.html
from matplotlib.backends.qt_compat import QtWidgets as qtw
from matplotlib.backends.backend_qtagg import (
    FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure


class MatplotlibWidget(qtw.QWidget):
    def __init__(self):
        super().__init__()
        layout = qtw.QVBoxLayout(self)

        fig = Figure()
        self.canvas = FigureCanvas(fig)

        layout.addWidget(NavigationToolbar(self.canvas, self))
        layout.addWidget(self.canvas)

        self.ax = self.canvas.figure.subplots()
        
        self.test_draw()

    def draw_line(self, data):
        line, = self.ax.plot(*data)
        self.canvas.draw()

    def test_draw(self):
        x = np.arange(20)
        y = np.random.random(size=len(x))
        self.draw_line((x, y))

if __name__ == "__main__":
    app = qtw.QApplication([])
    mw = MatplotlibWidget()

    mw.show()
    app.exec()

test_main_for_graphing.py:
--------------------------
from test_graphing import MatplotlibWidget
from PySide6 import QtWidgets as qtw
from __feature__ import snake_case

class MainWindow(qtw.QMainWindow):

    def __init__(self):
        super().__init__()

        self.graph = MatplotlibWidget()
        self._center_widget = qtw.QWidget()
        
        self._center_layout = qtw.QHBoxLayout(self._center_widget)

        # self.setCentralWidget(self._center_widget)  # regular
        self.set_central_widget(self._center_widget)  # snake case

        # self._center_layout.addWidget(self.graph)  # regular
        self._center_layout.add_widget(self.graph)  # snake case
        
if __name__ == "__main__":
    app = qtw.QApplication([])
    mw = MainWindow()

    mw.show()
    app.exec()
```

### Actual outcome

/Users/tismer/src/QtC/pyside-setup/test_main_for_graphing.py:25: MatplotlibDeprecationWarning: The resize_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('resize_event', ResizeEvent(...)) instead.
  mw.show()
Traceback (most recent call last):
  File "/Users/tismer/src/QtC/pyside-setup/test_main_for_graphing.py", line 25, in <module>
    mw.show()
  File "/Users/tismer/.pyenv/versions/3.11.3-debug/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 200, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: FigureCanvasBase.resize_event() takes 1 positional argument but 2 were given

### Expected outcome

When there is no clash with deprecated functions, a nice graphic is shown.

### Matplotlib Version

3.7.2

### Matplotlib Backend

QtAgg

### Python version

3.11.3

### Installation

pip

**Comment by QuLogic** [comment]
3.6-deprecated functions will be removed in 3.8, so there's not really anything to be done, since that will be out soon.
