### ISSUE TITLE
[Bug]: Matplotlib animated plot causes Tkinter GUI to stutter

### ISSUE THREAD

**Issue by TheWicklowWolf** [matplotlib/matplotlib#26692]
### Bug summary

Issue with Animated Plot and Tkinter GUI

### Code for reproduction

```python
import random
import time
import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib import animation
import threading


root = tk.Tk()
gui_text = tk.StringVar()
tk.Label(root, textvariable=gui_text).pack()
x = []
y = []


def data_thread():
    while True:
        random_value = random.random()
        x.append(len(x))
        y.append(random_value)
        gui_text.set(f"Random Value: {random_value:.2f}")
        time.sleep(0.09)


def init():
    plot_data.set_data([], [])
    return (plot_data,)


def animate(frame):
    plot_data.set_data(x, y)
    plot_axes.relim()
    plot_axes.autoscale_view(True)
    return (plot_data,)


plot_figure = plt.figure()
plot_axes = plt.axes()
(plot_data,) = plot_axes.plot([], [])

animation = animation.FuncAnimation(plot_figure, animate, init_func=init, interval=1000, blit=False)
plt.show(block=False)

thread = threading.Thread(target=data_thread)
thread.daemon = True
thread.start()

root.mainloop()
```

### Actual outcome

![tk](https://github.com/matplotlib/matplotlib/assets/111055425/370c3fc2-b747-4abb-8e52-c9a514ce534a)

### Expected outcome

As you can see when the plot is updating/animating (every second) the gui stops updating the value. Is there anyway to prevent this?

### Matplotlib Version

3.7.2

### Matplotlib Backend

TkAgg

### Python version

3.11

### Installation

None

**Comment by jklymak** [comment]
I don't understand what you mean here.  What value "stops updating"?

**Comment by TheWicklowWolf** [comment]
> I don't understand what you mean here. What value "stops updating"?

Apologies, I wasn't very clear.

I meant the Tkinter GUI part-> Random Value: 

As you can see there is a momentary pause when the plot is updating, and I'm trying to find out if there is a way to prevent this.

**Comment by jklymak** [comment]
You screenshot above shows 5 updates, and they all seem 1 s apart, so again I'm not clear what stutter you are referring to.

**Comment by TheWicklowWolf** [comment]
> I would guess there isn't a lot you can do about this other than speed up the Matplotlib plotting, perhaps by using 

Yeah I was thinking that.

I can't use blit because of the dynamic axes, and I tried using `plt.style.use("fast")` but that made no difference.
