### ISSUE TITLE
[Bug]: Histogram shows non-existant numbers in bins near zero in some cases.

### ISSUE THREAD

**Issue by sumadithya** [matplotlib/matplotlib#26697]
### Bug summary

For the same data, changing the range makes the values in some bins disappear.
Notice that only the range is changed in the following screenshots.

Notice the frequency at the bin near zero.
![hist1](https://github.com/matplotlib/matplotlib/assets/27889757/23b7b366-1ec0-4d27-9bb9-4ecde32e87eb)
![hist2](https://github.com/matplotlib/matplotlib/assets/27889757/1ff5771c-7e14-4244-b0d9-5215b0312636)

Following is a zip file which extracts to a `.npy` file which contains the data used for plotting the histogram.
[flowtest.zip](https://github.com/matplotlib/matplotlib/files/12521358/flowtest.zip)

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

img = np.load('flowtest.npy')
flatimg = img.flatten()

plt.hist(flatimg, bins = 1000, range = (-9, 0))
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram')
plt.show()
```

### Actual outcome

![hist1](https://github.com/matplotlib/matplotlib/assets/27889757/23b7b366-1ec0-4d27-9bb9-4ecde32e87eb)

### Expected outcome

A histogram similar to this:
![hist2](https://github.com/matplotlib/matplotlib/assets/27889757/1ff5771c-7e14-4244-b0d9-5215b0312636)

But with range -9 to 0.

### Additional information

The values zero probably do not exist. Trying to print values above '-0.001' gave nothing.

### Operating system

Ubuntu 22.04.2 LTS

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12

### Jupyter version

6.5.5

### Installation

pip

**Comment by rcomer** [comment]
I think the peak near zero is genuine.  You have 2044 values that are close to zero.

```python
In [2]: test = np.load("flowtest.npy")

In [5]: np.isclose(test, 0).sum()
Out[5]: 2044
```
I suspect the reason the peak doesn't always show is that 1000 bins is too many for the resolution of the image.  So you could try decreasing the number of bins or increasing the figure size or dpi.

**Comment by jklymak** [comment]
Use histtype='stairfilled' to mitigate this.  I'm going to close as there isn't much to be done here, though I wonder if this should go under our faq as it comes up a lot.
