### ISSUE TITLE
issue: pip3 install matplotlib==3.5.0 for Python 3.11

### ISSUE THREAD

**Issue by EP-PBednarczyk** [matplotlib/matplotlib#26715]
### Bug summary

When I try to install pip3 install matplotlib==3.5.0 for Python 3.11, I have received: pip3 install matplotlib==3.5.0
Collecting matplotlib==3.5.0
  Using cached matplotlib-3.5.0.tar.gz (35.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pbednarczyk\AppData\Local\Temp\pip-install-_kx0c7lf\matplotlib_8a3cbe550c474e71b1c06c962adbebe5\setup.py", line 39, in <module>
          from setupext import print_raw, print_status
      ImportError: cannot import name 'print_raw' from 'setupext' (C:\Users\pbednarczyk\Pawel_Bednarczyk_materialy\matlab_python\python-3.11.2-embed-amd64\Lib\site-packages\setupext\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
![matlib_issue](https://github.com/matplotlib/matplotlib/assets/126777469/e7b62b67-5da1-443f-a7c2-99b55ccd366c)
.

I was trying discus with ChatGPT but it do not know. 
![matplotlib_issue3](https://github.com/matplotlib/matplotlib/assets/126777469/deb76da4-948a-4ed8-a396-d50ac6d322c6)
![matplotlib_issue4](https://github.com/matplotlib/matplotlib/assets/126777469/4e9258ee-21ff-43e3-8fb9-f4145c3e4f08)
![matplotlib_issue5](https://github.com/matplotlib/matplotlib/assets/126777469/f8268f5b-1af1-4565-a204-736ca041637b)
![matlib_issue](https://github.com/matplotlib/matplotlib/assets/126777469/32e4484b-cc68-4cea-8fbf-651ea3e34317)
![matplotlib_issue2](https://github.com/matplotlib/matplotlib/assets/126777469/bb0452e0-67fa-4092-a84a-60c6587f5ebb)
![matplotlib_issue3](https://github.com/matplotlib/matplotlib/assets/126777469/b4466f97-2906-4bc3-acd4-5711b8a6253c)
![matplotlib_issue4](https://github.com/matplotlib/matplotlib/assets/126777469/cba24af4-bfbf-4780-ae0c-5c6b5a79f14f)
![matplotlib_issue5](https://github.com/matplotlib/matplotlib/assets/126777469/ebb81313-23a3-4315-a592-cc510f7083a8)
![matlib_issue](https://github.com/matplotlib/matplotlib/assets/126777469/91ce4c5a-45be-45cc-afc9-0486abd0909e)
![matplotlib_issue2](https://github.com/matplotlib/matplotlib/assets/126777469/e25f444a-825d-4bbf-9314-7cf3cbf078ac)

### Code for reproduction

```python
install pip3 install matplotlib==3.5.0 for Python 3.11
```

### Actual outcome

![matlib_issue](https://github.com/matplotlib/matplotlib/assets/126777469/477b49c4-d6fa-49b4-953f-86b1c48dd41f)
![matplotlib_issue2](https://github.com/matplotlib/matplotlib/assets/126777469/bbc023c3-1872-4821-9f87-5b39ae7ebe8a)
![matplotlib_issue3](https://github.com/matplotlib/matplotlib/assets/126777469/a93f65ed-887d-47b0-9238-1a2484b8a913)
![matplotlib_issue4](https://github.com/matplotlib/matplotlib/assets/126777469/8e149635-f5c6-474e-8ea7-2d0335392980)
![matplotlib_issue5](https://github.com/matplotlib/matplotlib/assets/126777469/599b355a-28b7-4c2f-86e3-331ffb0581ce)

pip3 install matplotlib==3.5.0
Collecting matplotlib==3.5.0
  Using cached matplotlib-3.5.0.tar.gz (35.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pbednarczyk\AppData\Local\Temp\pip-install-_kx0c7lf\matplotlib_8a3cbe550c474e71b1c06c962adbebe5\setup.py", line 39, in <module>
          from setupext import print_raw, print_status
      ImportError: cannot import name 'print_raw' from 'setupext' (C:\Users\pbednarczyk\Pawel_Bednarczyk_materialy\matlab_python\python-3.11.2-embed-amd64\Lib\site-packages\setupext\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected outcome

When I try to install pip3 install matplotlib==3.5.0 for Python 3.11, I have received: pip3 install matplotlib==3.5.0
Collecting matplotlib==3.5.0
  Using cached matplotlib-3.5.0.tar.gz (35.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pbednarczyk\AppData\Local\Temp\pip-install-_kx0c7lf\matplotlib_8a3cbe550c474e71b1c06c962adbebe5\setup.py", line 39, in <module>
          from setupext import print_raw, print_status
      ImportError: cannot import name 'print_raw' from 'setupext' (C:\Users\pbednarczyk\Pawel_Bednarczyk_materialy\matlab_python\python-3.11.2-embed-amd64\Lib\site-packages\setupext\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
![matlib_issue](https://github.com/matplotlib/matplotlib/assets/126777469/e7b62b67-5da1-443f-a7c2-99b55ccd366c)
.

### Additional information

chat GPT said: "Contact Matplotlib Community: If the issue persists, it may be worth reaching out to the Matplotlib community or checking their official documentation and GitHub repository for updates or compatibility information related to Python 3.11.2."

### Operating system

windows 10

### Matplotlib Version

3.5.0

### Matplotlib Backend

no version backen AttributeError: module 'wx' has no attribute 'Thread_IsMain'

### Python version

3.11

### Jupyter version

pycharm 2023.2.1

### Installation

pip

**Comment by jklymak** [comment]
Matplotlib 3.5 (released Nov 2021) does not support python 3.11 (released Oct 2022).  You will have to use an older python. 

I'm not sure if there is something we should be changing on our side for our pip recipes.  Pinnng python versions seems bad in general, but something broke in setup here.

**Comment by QuLogic** [comment]
Python 3.11 support was only really properly added in Matplotlib 3.6: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#new-wheel-architectures

There is nothing we can do to fix this, as all we can do is make new releases and the OP is _explicitly_ asking for 3.5.0.
