### ISSUE TITLE
[Bug]: `fig.canvas.manager.key_press` no longer exists. 

### ISSUE THREAD

**Issue by paulbrodersen** [matplotlib/matplotlib#26713]
### Bug summary

I am trying to temporarily and reversibly disconnect matplotlib's own key press events.
This used to be the way to do this:

```python
fig.canvas.mpl_disconnect(fig.canvas.manager.key_press_handler_id)
# Do stuff
fig.canvas.manager.key_press_handler_id \
    = fig.canvas.mpl_connect('key_press_event', fig.canvas.manager.key_press)
```

However, the method `fig.manager.key_press` seems to no longer exist in recent matplotlib versions.
The `fig.manager.key_press_handler_id` attribute is still there, so I assume the method has just been moved somewhere else but I can't find it.

How do I temporarily disable matplotlib's event handling now?

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
fig.canvas.manager.key_press
```

### Actual outcome

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 fig.canvas.manager.key_press

AttributeError: 'FigureManagerQT' object has no attribute 'key_press'
```

### Expected outcome

No attribute error. 

### Matplotlib Version

3.7.0

### Matplotlib Backend

Tested with QtAgg, TkAgg

### Installation

None

**Comment by anntzer** [comment]
I believe connecting `backend_bases.key_press_handler` instead should work.  For your use case I would perhaps instead just temporarily remove all keymaps, i.e. `with mpl.rc_context({k: [] for k in mpl.rcParams if k.startswith("keymap.")}): ...`.

**Comment by paulbrodersen** [comment]
> I believe connecting backend_bases.key_press_handler instead should work.

Works like a charm. Much obliged for the quick response.

**Comment by tacaswell** [comment]
This method was deprecated in 3.4 https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#backend-deprecations and removed in 3.6 https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#classes-methods-and-attributes so this should have been warning for a while.

**Comment by paulbrodersen** [comment]
@tacaswell For every deprecation cycle length, there is someone who updates infrequently enough to miss the deprecation notice. I think this virtual environment was on 3.3.1 before I upgraded. ;-)
