### ISSUE TITLE
[Bug]: plot.figure() generates TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by sphrases** [matplotlib/matplotlib#26749]
### Bug summary

During coding, randomly, plt.figure() generates the error TypeError: 'list' object is not callable.
I have tried executing the code python versions 3.7, 3.9 and 3.9 and also tried different venv setups. 
Finally, i have tried to execute the code on google collab.
Even just the import and function call results in the error.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
    plt.figure()
```

### Actual outcome

Code doesn't execute and results in TypeError: 'list' object is not callable

### Expected outcome

Show an empty plot

### Additional information

![image](https://github.com/matplotlib/matplotlib/assets/11139334/86d8c0c1-9365-4f46-b3a0-732408b96253)

### Matplotlib Version

3.7.1

### Installation

None

**Comment by jklymak** [comment]
This is a sign of a crossed install. Suggest you discuss at https://discourse.Matplotlib.org as this highly unlikely to be a bug in Matplotlib.
