### ISSUE TITLE
[MNT]: PyInstaller does not include DLL for _cext import

### ISSUE THREAD

**Issue by mapcreatorGuus** [matplotlib/matplotlib#26745]
### Summary

Creating an executable with PyInstaller (5.13.2) and matplotlib 3.7.3 can cause the following error:

ImportError: DLL failed to load while importing _cext: The specified module cannot be found.

I am using Python 3.11.5, with these packages installed:
altgraph                  0.17.3
attrs                     23.1.0
boto3                     1.28.45
botocore                  1.31.45
certifi                   2023.7.22
charset-normalizer        3.2.0
click                     8.1.7
click-plugins             1.1.1
cligj                     0.7.2
colorama                  0.4.6
contourpy                 1.1.0
cycler                    0.11.0
Fiona                     1.9.4.post1
fonttools                 4.42.1
idna                      3.4
isodate                   0.6.1
jmespath                  1.0.1
kiwisolver                1.4.5
lxml                      4.9.3
matplotlib                3.7.3
numpy                     1.25.2
packaging                 23.1
pefile                    2023.2.7
Pillow                    10.0.0
pip                       23.2.1
platformdirs              3.10.0
psycopg2                  2.9.7
pyinstaller               5.13.2
pyinstaller-hooks-contrib 2023.8
pyparsing                 3.1.1
pyproj                    3.6.0
python-dateutil           2.8.2
pytz                      2023.3.post1
pywin32-ctypes            0.2.2
requests                  2.31.0
requests-file             1.5.1
requests-toolbelt         1.0.0
s3transfer                0.6.2
setuptools                68.2.1
shapely                   2.0.1
six                       1.16.0
urllib3                   2.0.4
wheel                     0.41.2
zeep                      4.2.1

I am not sure what other information to share that could help. Annoyingly enough, it does run fine on my own computer (which makes sense since my development setup probably installed all DLLs properly to run the Python program in the first place). When I opened this on a different computer with no Python installed, I got this error.

### Proposed fix

From what I found elsewhere about such PyInstaller issues, I assume something needs to be included in the PyInstaller hooks of matplotlib.

**Comment by QuLogic** [comment]
`_cext` is part of kiwisolver, not Matplotlib.
