### ISSUE TITLE
[Bug]: Problems with matplotlib.animation

### ISSUE THREAD

**Issue by Jicming** [matplotlib/matplotlib#26759]
### Bug summary

When usingmatplotlib.animation, start the animation, and in the update function update()  of the animation, frames  will have two occurrences of 0，If the frame value is 1, you want the update()  function to only execute once, but it will still execute twice. The code is shown below. It may not be a bug, but it's really difficult to handle programs that only run once

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def update(frame):
    print(frame)

    if frame == 0:
        ani1.event_source.stop()
ani1 = animation.FuncAnimation(plt.gcf(), update, frames=1, interval=100, repeat=False)
plt.show()
#Output twice: 0, but when the frame is equal to 1, it should be output once: 0
```

### Actual outcome

0
0

### Expected outcome

0

### Operating system

Windows

### Matplotlib Version

3.7.3

### Matplotlib Backend

TkAgg

### Python version

Python 3.10.2

### Jupyter version

7.0.3

### Installation

pip

**Comment by jklymak** [comment]
Please see https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html. 
```
init_func

A function used to draw a clear frame. If not given, the results of drawing from the first item in the frames sequence will be used. This function will be called once before the first frame.
```

If you don't want this to happen, then set `init_func` to something that does what you want.  

I'm going to close this as expected and documented.
