### ISSUE TITLE
[Bug]: Cannot plot correct fig in polar coordinates

### ISSUE THREAD

**Issue by December0w0** [matplotlib/matplotlib#26771]
### Bug summary

I was trying to use contourf or pcolormesh to draw a contour map in polar coordinate. However, the figure is very strange. Without painting in the polar coordinate, the figure seems to be normal. 

### Code for reproduction

```python
#画图（绘制不同仰角的图，以下图片使用极坐标系绘制）
    fig=plt.figure(figsize=(30,25))
    ax1=fig.add_subplot(2,2,1,projection="polar")
    vel_raw_fig=vel_raw_lin[0,:,:]
    radius_print,azimuths=np.meshgrid(radius,azimuth_theta) #使用contourf
    ax1.set_theta_zero_location('N', offset=0.0) #使得坐标轴的0°对准正北方
    ax1.set_theta_direction(-1)#使得东方在右边，即顺时针旋转
    a1=ax1.pcolormesh(azimuths,radius_print,vel_raw_fig,cmap='RdBu_r')
    cb3=plt.colorbar(a1)
```

### Actual outcome
![QQ图片20230914175030](https://github.com/matplotlib/matplotlib/assets/144080271/c7382fba-e132-4426-85b1-c6e345d8b53b)
figure 1: figure spawned by pcolormesh
![97}F3E EWN56DY6}W0GY5`G](https://github.com/matplotlib/matplotlib/assets/144080271/90de6b01-2f66-402b-ab22-c472608e20a8)
figure 2: figure spawned by contourf

### Expected outcome

The figure in the cartesian coordinate (the X-axis is the azimuth and the Y-axis is the radius) as followed.
![1D7 }5UL`QF`V$E%% F OVB](https://github.com/matplotlib/matplotlib/assets/144080271/5f968101-b44d-4e82-aa9e-a677671ecd15)
figure 3: figure spawned by pcolormesh
![{$BRH)TMQ81`MUL~U6$OW`R](https://github.com/matplotlib/matplotlib/assets/144080271/0eba2eb9-ae2f-46eb-ae99-f82dc6efc01b)
figure 4: figure spawned by contourf

### Additional information

The data was attracted in the NetCDF4 file.

### Operating system

Windows 11

### Matplotlib Version

3.7.1

### Python version

3.11

### Installation

pip

**Comment by ksunden** [comment]
Can you provide a complete (numpy/mpl only) reproducible example?

It is hard to make many assertions without knowing the contents of the arrays being plotted.
Preferably it can be reproduced with much smaller data that can be more easily reasoned about.

I think it is possibly just that you need to convert your angles into radians from degrees (e.g. use `np.deg2rad(azimuths)`)

**Comment by December0w0** [comment]
> Can you provide a complete (numpy/mpl only) reproducible example?
> 
> It is hard to make many assertions without knowing the contents of the arrays being plotted. Preferably it can be reproduced with much smaller data that can be more easily reasoned about.
> 
> I think it is possibly just that you need to convert your angles into radians from degrees (e.g. use `np.deg2rad(azimuths)`)

Yess!!! I added np.deg2rad(azimuths) and the problem was solved. Thanks a lot. I'll close the issue.
