### ISSUE TITLE
[MNT]: Improve typing of FigureManagerBase

### ISSUE THREAD

**Issue by jeremynac** [matplotlib/matplotlib#26772]
### Summary

The usability and readability of the class FigureManagerBase (in backend_bases.py) is negatively impacted by a lack of typing for the "canvas" attribute.
It is working correctly but not marked as being of type FigureCanvasBase.
It impacts the typing and readability of multiple methods of the FigureManagerBase which use or return the canvas attribute.

### Proposed fix

Simply add the typing for that attribute in the constructor of FigureManagerBase.

**Comment by ksunden** [comment]
This type hint _is_ included in the `pyi` stub file (which is new for 3.8.0), so I'm going to close this issue
