### ISSUE TITLE
Please upload new dev wheel so we pick up 3.9.dev after 3.8 release

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#26786]
Hello! I see that you released 3.8 14 hours ago, but the dev wheel for the next release (3.9.dev?) is not present in https://anaconda.org/scientific-python-nightly-wheels/matplotlib/files . As a result grabbing a dev wheel results in the test suite silently grabbing your stable 3.8, which is very confusing.

Thanks!

**Comment by pllim** [comment]
FWIW I just checked again and this is what I see.

![Screenshot 2023-09-18 124345](https://github.com/matplotlib/matplotlib/assets/2090236/42dbd0f4-2da6-49d1-9ad8-a8409ceeb9a6)

**Comment by ksunden** [comment]
We need to merge #26785 for the version number on main to be updated, that has to go through our normal PR flow, as it is a change to `main`, which is a protected branch.

Once that is merged, the next wheel will be uploaded automatically with the new version number.

**Comment by pllim** [comment]
>  the next wheel will be uploaded automatically 

Like by tomorrow or a few days? Thanks!

**Comment by ksunden** [comment]
The upload workflow runs at 01:23 UTC, so evening in US timezones

**Comment by QuLogic** [comment]
[This job](https://github.com/matplotlib/matplotlib/actions/runs/6230067211) finished a couple hours ago and uploaded `3.9.0.dev238+ge861ea2ff6`.

**Comment by pllim** [comment]
Thank you!
