### ISSUE TITLE
[Bug]: inconsistent results when formatting ticklabels by get_text() in time axis

### ISSUE THREAD

**Issue by stevenlis** [matplotlib/matplotlib#26791]
### Bug summary

I'm trying to format ticklabels based on text on a time x axis.I have been experiencing inconsistent results with various formatters.

### Code for reproduction

```python
import pandas as pd
import numpy as np
from datetime import date

import matplotlib.pyplot as plt
from matplotlib.dates import MonthLocator
from matplotlib.dates import ConciseDateFormatter

xs = [pd.date_range(f'{y}-07-01', '2021-12-31', freq='M')
      for y in range(2016, 2019)]
ys = [np.random.rand(len(x)) for x in xs]

fig, axs = plt.subplots(3, 1, figsize=(10, 8))
for ax, x, y in zip(axs, xs, ys):
    ax.plot(x, y)

    locator = MonthLocator((1, 4, 7, 10))
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(ConciseDateFormatter(locator))

    for text in ax.get_xaxis().get_ticklabels():
        # print(text.get_text())
        if text.get_text().startswith('20'):
            text.set_fontsize(10)
        else:
            text.set_fontsize(5)

    ax.set_xlim(date(2016, 7, 1))
```
### Actual outcome

![ed619ab1-d916-4d40-ab27-61d8adedeee8](https://github.com/matplotlib/matplotlib/assets/33796896/964d58e6-05d9-4524-a778-956f17288c21)

If you print the `get_text()` function, all the texts appear to be fine. However, for unknown reasons, certain texts are not picked by the `set_fontsize()` method.

### Expected outcome

All the "20YY" will be set to fontsize 10

### Operating system

OS/X

### Matplotlib Version

3.7.1

### Python version

3.10

### Installation

None

**Comment by jklymak** [comment]
You set the tick fontsize, but then change the tick values because you `set_xlim`.  If you put the `set_xlim` before the tick manipulation it works fine.  

If you don't want this to be brittle, set the major locator to years, and the minor locator to months 4, 7, 10, and change the size of the minor tick labels...

```
for ax, x, y in zip(axs, xs, ys):
    ax.plot(x, y)

    locator = YearLocator()
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(ConciseDateFormatter(locator))

    locator = MonthLocator((1, 4, 7, 10))
    ax.xaxis.set_minor_locator(locator)
    ax.xaxis.set_minor_formatter(ConciseDateFormatter(locator))
    ax.tick_params(axis='x', labelsize=7, which='minor')

    ax.set_xlim(date(2016, 7, 1))
```

I'm going to close this because there its relatively well understood that ticks need to be finalized before you reach into them and manually muck with them.

**Comment by stevenlis** [comment]
Thank you @jklymak Could you pls take a look at this: [SO](https://stackoverflow.com/questions/77115609/format-time-axis-to-only-display-tick-labels-after-a-certain-date). Does this also have something to do with the finalization of ticks?
