### ISSUE TITLE
[Bug]: use_locale leads to curly brackets around decimal separator

### ISSUE THREAD

**Issue by aaronschueddekopf** [matplotlib/matplotlib#26803]
### Bug summary

If I set `plt.rcParams["axes.formatter.use_locale"] = True`, the decimal separator is displayed in curly brackets in v3.8.0. This was not the case in 3.7.3. But only when the decimal separator is a comma.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import locale

locale.setlocale(locale.LC_NUMERIC, 'de')

plt.rcParams["axes.formatter.use_locale"] = True
fig = plt.Figure()
plt.plot([0, 1, 2, 3, 4], [0.1, 0.13, 0.09, 0.105, 0.13])
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/90246476/8983f269-30da-43c9-951b-e8d0c67ca66b)

### Expected outcome

As described in the bug description, in v 3.7.3 this simply led to a comma as decimal separator which is not displayed in curly brackets

### Operating system

Windows 11

### Matplotlib Version

3.8.0

### Matplotlib Backend

Qt5Agg

### Python version

3.10.11

### Installation

pip

**Comment by oscargus** [comment]
Ahh, as a work-around for now you can use mathtext for the formatter by adding:
```
plt.rcParams["axes.formatter.use_mathtext"] = True
```

**Comment by aaronschueddekopf** [comment]
@oscargus that's great! Thanks!
