### ISSUE TITLE
[Bug]: `ValueError: The truth value...` when an ndarray is passed to the `color` kwarg of `axes3d.scatter`

### ISSUE THREAD

**Issue by joshuacwnewton** [matplotlib/matplotlib#26821]
### Bug summary

Passing a numpy array to the `color` argument of `ax.scatter` results in a `ValueError` when `ax` is initialized with `projection='3d'`. This error began occurring in our CI after the release of matplotlib 3.8.0.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(1, 0, 0, color=np.array([0, 0, 0, 1]))
plt.show()
```

### Actual outcome

Traceback from our CI suite:

```python
  File "/home/runner/sct_6.1.dev0/testing/cli/test_cli_sct_dmri_display_bvecs.py", line 17, in test_sct_dmri_display_bvecs_png_exists
    sct_dmri_display_bvecs.main(argv=['-bvec', sct_test_path('dmri', 'bvecs.txt')])
  File "/home/runner/sct_6.1.dev0/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py", line 176, in main
    ax.scatter(x[i], y[i], z[i], color=shell_colors[bvals[i]], alpha=0.7)
  File "/home/runner/sct_6.1.dev0/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/runner/sct_6.1.dev0/python/envs/venv_sct/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2377, in scatter
    if kwargs.get('color', None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Expected outcome

No error.

### Additional information

> NB: This is legacy code I'm maintaining but haven't actually written myself -- I only began looking at it after our CI threw an error after the upgrade from matplotlib 3.7.3 to 3.8.0.

- If I remove `projection='3d'`, the code does not error out.
- If I pass a list (`[0, 0, 0, 1]`) rather than an ndarray, the code does not error out, and displays a black, opaque point:

![image](https://github.com/matplotlib/matplotlib/assets/16181459/e1aee2f3-d74b-4972-9b12-a193548cbd09)

### Operating system

Ubuntu 22.04

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://backend_interagg

### Python version

3.9.17, 3.10.12

### Jupyter version

N/A

### Installation

pip

**Comment by ksunden** [comment]
This behavior was changed in #26249

I think that the conditional should actually be:

```python
if "color" in kwargs:
```

as it is using `.get` really only to determine if it is present or not.

**Comment by timhoffm** [comment]
I think the condition actually should be
```
If kwargs.get("color") is not Nonr:
```
To make explicit color=None work and comply with

> c Defaults to [None](https://docs.python.org/3/library/constants.html#None). In that case the marker color is determined by the value of color, facecolor or facecolors. In case those are not specified or [None](https://docs.python.org/3/library/constants.html#None), the marker color is determined by the next color of the Axes' current "shape and fill" color cycle.

from https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter
