### ISSUE TITLE
[Bug]: Problem with useLocale in ticklabel_format

### ISSUE THREAD

**Issue by GezaLaTeX** [matplotlib/matplotlib#26838]
### Bug summary

With french locale settings, the decimal comma is enclosed in braces.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 1, 10)

fig, ax=plt.subplots()
ax.ticklabel_format(useLocale='True')
ax.plot(x, x**2,'o')
plt.show()
```

### Actual outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/145553854/3bd4024d-11a3-4ce4-a97d-b2225c81bea7)

### Expected outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/145553854/4bbae246-8c21-4f18-941e-97b2b73b7a2f)

### Operating system

Ubuntu

### Matplotlib Version

3.8.0

### Matplotlib Backend

Qt5Agg

### Python version

3.11.4

### Installation

pip

**Comment by rcomer** [comment]
Thanks for the report @GezaLaTeX!  This one has already been reported at #26803 and fixed ready for the first patch release.  Note that https://github.com/matplotlib/matplotlib/issues/26803#issuecomment-1722865810 describes a workaround for the meantime.
