### ISSUE TITLE
[Bug]: Saved figure doesn't execulde the outer boarder

### ISSUE THREAD

**Issue by itsMohammedThaier** [matplotlib/matplotlib#26832]
### Bug summary

I think matplotlib.pyplot.savefig('name.jpg',dpi=300,**bbox_inches='tight'**) should the figure without the outer boarder

Saved figure:
![y](https://github.com/matplotlib/matplotlib/assets/70210166/e7919663-9ce4-4f91-b78c-6a5e1f7d1065)

Expected:
![y](https://github.com/matplotlib/matplotlib/assets/70210166/a378bba2-2b67-473b-acb7-9d504b232bee)

### Code for reproduction

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from perlin_noise import PerlinNoise
import math

#Data1
c1 = (.01,.01,.01)
c2 = (.9,.9,.9)
noise = PerlinNoise(octaves=1,seed=np.random.randint(0,100))
n = 100

#Data2
xS = (np.random.random(n)-.5)*2
yS = (np.random.random(n)-.5)*2

#Customization
mpl.rcParams['savefig.facecolor'] = (1,1,1)
mpl.rcParams['axes.facecolor'] = c1

#Plotting
fig,ax = plt.subplots(figsize=(5,5))
ax.set_xlim(-1,1)
ax.set_ylim(-1,1)
tmpX,tmpY = 0,0
for i in range(len(xS)):
    for k in range(len(yS)):
        eff = noise([xS[i],yS[k]])
        pX = math.cos(eff*math.pi*2)*1
        pY = math.sin(eff*math.pi*2)*1
        ax.plot((pX,tmpX),(pY,tmpY),alpha=.05,color=c2,linewidth=.3)
        tmpX,tmpY = pX,pY

#Rendering
plt.savefig('y.jpg',dpi=1000,bbox_inches='tight')
plt.show()
```

### Actual outcome

![y](https://github.com/matplotlib/matplotlib/assets/70210166/ada5e0ae-e0c2-40c7-8bd8-8b63d09e982e)

### Expected outcome

![y](https://github.com/matplotlib/matplotlib/assets/70210166/ec0a2ff5-bf3a-458e-be59-7c0a39459e7b)

### Operating system

Windows 10

### Matplotlib Version

3.7.3

### Python version

3.10.9

### Installation

pip

**Comment by QuLogic** [comment]
The ticks and the spines are part of the figure, and `bbox_inches='tight'` crops to the size of the figure elements; if you don't want them to be saved, then you will need to turn them off.
