### ISSUE TITLE
[Bug]: plot arguments color = "C0" and simply "C0" lead to different results.

### ISSUE THREAD

**Issue by ecciv** [matplotlib/matplotlib#26839]
### Bug summary

I was surprised to find that if I:

1. activate a custom stylesheet
2. create a figure
3. create a plot using `plt.plot(x,y,color="C0")`
I get a different result than if I do
5. `plt.plot(x,y,"C0")`

In the former case, the color is "tab:blue", i.e. the default style C0. However in the second case, I get the intended first color of my custom prop cycler.

If this is intended, this needs to be explained on https://matplotlib.org/stable/users/explain/colors/colors.html#specifying-colors

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.style.use("seaborn")
plt.plot([0,1], [0,1], color="C0")
plt.plot([0,1], [0,2], "C0")
plt.show()
```

### Actual outcome

Different colours :)

### Expected outcome

Same colours :)

### Operating system

Windows

### Matplotlib Version

3.7.1

### Installation

conda

**Comment by tacaswell** [comment]
I tweaked the example a bit to be easier to see if the colors were the same:

```python
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")
plt.plot([0,1], [0,1], color="C0", lw=10)
plt.plot([0,1], [1,0], "C0", lw=10)
plt.show()
```

![so](https://github.com/matplotlib/matplotlib/assets/199813/4934f018-bb18-469b-bb3f-1343d329319c)

I can not reproduce this with 3.7.1 or 3.8.0

**Comment by ecciv** [comment]
boah, I'm sorry about that. Here's a minimal example that actually reproduces the problem...

```
import matplotlib.pyplot as plt

plt.style.use("bmh")
plt.figure()
plt.plot([1, 1], [0, 1])
plt.show(block=False)

plt.style.use("seaborn")
plt.figure()
plt.plot([0, 1], [0.6, 0.6], "C1", lw=3)
plt.plot([0, 1], [0.4, 0.4], color="C1", lw=3)
plt.show(block=False)

plt.style.use("default")
plt.figure()
plt.plot([0, 1], [0, 1])
plt.show(block=True)
```
![image](https://github.com/matplotlib/matplotlib/assets/70523470/72488ace-35a4-4c15-8556-9401fd7ae823)

Where both lines in the second plot should be green, one becomes orange. I'm not sure what part of the other plots induce this strange behavior, but if I remove them, the issue seems to go away.

**Comment by tacaswell** [comment]
ok, I can reproduce this now.

It is an issue of when we resolve the meaning of 'CN'.  In the case of the positional argument we evaluate it early, with the case of the color kwarg we evaluate it late.  If you change the color cycle between when you set the color and when the figure is rendered, you get the 'CN' at draw time not at `obj.set_color` time (which happens in `__init__` of `Line2D`).

A "fix" is to force a draw in between:

```python
plt.style.use("seaborn-v0_8")
plt.figure()
plt.plot([0, 1], [0.6, 0.6], "C1", lw=3)
plt.plot([0, 1], [0.4, 0.4], color="C1", lw=3)
plt.show(block=False)
plt.pause(.1)

plt.style.use("default")
plt.figure()
plt.plot([0, 1], [0, 1])
plt.show(block=True)
```

You can also reproduce this issue with the context manager:

```python
import matplotlib.pyplot as plt

with plt.style.context("seaborn-v0_8"):
    plt.figure()
    plt.plot([0, 1], [0.6, 0.6], "C1", lw=3)
    plt.plot([0, 1], [0.4, 0.4], color="C1", lw=3)
    plt.show(block=False)
```

**Comment by anntzer** [comment]
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/12967, which already has some discussion about what behavior we should prefer.

**Comment by ecciv** [comment]
Thanks anntzer, you’re right. I’m all team eager evaluation.

I’m writing a collection of stylesheets for my engineering firm, and I want to explain in the docs that we don’t need a function that ruterns the color cycle, because we can use Cn instead. But this is a big caveat now… use Cn but don’t use color=Cn 🫣
