### ISSUE TITLE
[Bug]: LaTeX rendering with text.usetex = True not working

### ISSUE THREAD

**Issue by runehoejlund** [matplotlib/matplotlib#26842]
### Bug summary

For a long time I have been able to render text in matplotlib plots with LaTeX. However, matplotlib rendering of plots with LaTeX has suddenly stopped working out of the blue. 

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({"text.usetex": True})

x = np.linspace(0, 1)
plt.plot(x, x**2, label=r'$x^2$')
plt.legend()
plt.show()
```

### Actual outcome

When I try running the lines above in my conda base environment, I get the following error:
`
"name": "FileNotFoundError",
"message": "missing font metrics file: cmss10",
...
`

If I run it from another conda environment, I get the following error:
```
"name": "RuntimeError",
"message": "dvipng was not able to process the following string:\nb'$\\\\\\\\mathdefault{0.0}$'\n\nHere is the full command invocation and its output:\n\ndvipng -bg Transparent -D 100.0 -T tight -o ~/.matplotlib/tex.cache/db/4d/db4d5952387611c107afe7f60b9dfb1b.png ~/.matplotlib/tex.cache/03/4c/034c697e4966133bcd6756494b8f530a.dvi\n\ndyld: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib\n  Referenced from: /usr/local/opt/gd/lib/libgd.3.dylib\n  Reason: image not found\n\n\n",
```

### Expected outcome

The code should produce a simple plot of a polynomial with text rendered with LaTeX.

### Additional information

I have LaTeX installed (via mactex installed via homebrew) and the TeX-installation appears to be included in my $PATH which is:
```
~/opt/anaconda3/envs/mgo/bin:
~/opt/anaconda3/condabin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/Library/TeX/texbin:
/opt/X11/bin:
/Library/Apple/usr/bin
```

I have tried deleting the `.matplotlib/tex.cache`directory without any improvements. I have also tried reinstalling mactex and installing conda's texlive-core package, but nothing works. Typing `which latex` in terminal yields `/usr/local/bin/latex` both with and without a conda environment activated.

Is this a bug in matplotlib, or am I doing something wrong? Do you have any suggestions for fixing the issue?

### Operating system

macOS Big Sur (11.7.10).

### Matplotlib Version

3.7.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.12

### Installation

conda

**Comment by QuLogic** [comment]
```
dvipng was not able to process the following string:
b'$\\\\mathdefault{0.0}$'

Here is the full command invocation and its output:

dvipng -bg Transparent -D 100.0 -T tight -o ~/.matplotlib/tex.cache/db/4d/db4d5952387611c107afe7f60b9dfb1b.png ~/.matplotlib/tex.cache/03/4c/034c697e4966133bcd6756494b8f530a.dvi

dyld: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: /usr/local/opt/gd/lib/libgd.3.dylib
  Reason: image not found
```

Your `dvipng` executable is broken; this is a problem from mactex and/or brew, but you'll have to work that out yourself.

**Comment by runehoejlund** [comment]
Thanks for your reply @QuLogic. I see it was a problem on my side then. I have fixed the issue now by removing all installed homebrew packages and reinstalling anaconda and reinstalling texlive via homebrew.
