### ISSUE TITLE
[Bug]: Decimal separator is "{,}" instead of "," when locale is set

### ISSUE THREAD

**Issue by pvlplv** [matplotlib/matplotlib#26856]
### Bug summary

Matplotlib pyplot.plot plots `{,}` as decimal separator instead of `,` in Y axis tick labels when locale with comma as decimal separator is set (for instance "de_DE").

### Code for reproduction

```python
# %%
import locale

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 1)

# %% Y axis labels have "." as decimal separator
plt.plot(x)
plt.show()

# %% Y axis labels have "{,}" instead of "," as decimal separator when locale is set
locale.setlocale(category=locale.LC_ALL, locale="de_DE.UTF-8")
plt.rcParams["axes.formatter.use_locale"] = True
plt.plot(x)
plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/36270842/650ce76e-be13-4700-b055-229b053b672f)

### Expected outcome

Plot with `,` as decimal separator in Y axis tick labels.

### Operating system

OS/X

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.11.5

### Jupyter version

4.0.6

### Installation

conda

**Comment by oscargus** [comment]
It is fixed in #26804 and will be in 3.8.1. For now, there is a way around it described in (one of) the earlier issue https://github.com/matplotlib/matplotlib/issues/26803#issuecomment-1722865810
