### ISSUE TITLE
[Bug]: Plot window not shown in Mac OS with backend set to default MacOSX

### ISSUE THREAD

**Issue by CarrascoCesar** [matplotlib/matplotlib#26869]
### Bug summary

Under version 3.8.0 the plot window does not appear when using MacOSX as the backend (default under Mac OS).  This is not an issues with the previous 3.7.3 version or when backend is set to TkAgg.

### Code for reproduction

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

from matplotlib import cm

# matplotlib.use(backend="TkAgg")

plt.style.use("_mpl-gallery")

# Make data
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface(X, Y, Z, vmin=Z.min() * 2, cmap=cm.Blues)

ax.set(xticklabels=[], yticklabels=[], zticklabels=[])

plt.show(block=False)

input("Hit [return] to end")
plt.close("all")
```

### Actual outcome

No plot is generated.

### Expected outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/131495172/b4ba7774-f2fc-4da1-85e6-bb9200802f11)

### Additional information

If the code line
# matplotlib.use(backend="TkAgg")
is uncommented the code will work as expected.

### Operating system

Mac OS 13.5.2

### Matplotlib Version

3.8.0

### Matplotlib Backend

MacOSX

### Python version

3.11.5

### Installation

conda

**Comment by greglucas** [comment]
I can confirm this doesn't work anymore with `show(block=False)`, if you do block it works as expected. This came in via #25966 where we fixed sigint handling, but apparently introduced this.

Specifically, it looks like it was the second cleanup commit removing unnecessary code: https://github.com/matplotlib/matplotlib/pull/25966/commits/ec6717aa7ad66868a3dc6186af031b970bb21c8e

@anntzer I am guessing this may be related to the multiple signal tests being flaky as well... and this comment: https://github.com/matplotlib/matplotlib/pull/25966#issuecomment-1657181517

Nothing obvious jumps out to me at first glance other than the old versions specifically calling `CFRunLoopRun()` within a while true block.
https://github.com/matplotlib/matplotlib/pull/25966/commits/ec6717aa7ad66868a3dc6186af031b970bb21c8e#diff-f8af2176752b51c29acf55ec5cc5d912f5459e19ed40559edcd78aaf7a6f6863L160

**Comment by tacaswell** [comment]
Is `input` running an event loop for us?

**Comment by greglucas** [comment]
I think the root cause of this is that the cleanup removed the `PyOS_InputHook` function that was in place and ran an event loop while waiting for the standard input. I just put up PR https://github.com/matplotlib/matplotlib/pull/26970 to try and re-implement some of that logic and things work as I'd expect, but happy to know if something still doesn't work or if there is a better way to do anything over there as well.

**Comment by tacaswell** [comment]
🤦🏻 Sorry I missed that when reviewing #26970 .
