### ISSUE TITLE
[ENH]: Release memory when raising error

### ISSUE THREAD

**Issue by Moooongo** [matplotlib/matplotlib#26879]
### Problem

I am plotting a very large dataset. When an error occurs during plotting, such as when plt.plot(X, Y) raises a memory error, the memory assigned for plotting is not released until I manually run plt.close() at a later point.

A nice feature to have would be to release the allocated memory automatically when errors as such occur.

### Proposed solution

Release the allocated memory before raising memory error (or possibly other errors.)

**Comment by tacaswell** [comment]
We can not release the memory while there are still references to the Python objects using it.  It would also be really surprising that if on an exception (which we may not be in a position to even catch) we cleared the Figure (which is still not guaranteed to actually release the memory) would be very surprising)

There is at least a reference to the top level Figure in pyplot (`plt.close()` drops our reference to the `Figure`) and that will (recursively) hold reference to everything else in the tree.   For bettor or worse, our artist tree is linked both directions so if you have a refernce to a plotted artist anywhere that will also keep the objects alive.

Another place that references can "hide" is in traceback object which holds onto the locals of every frame in the traceback (which is super useful for debugging!).

**Comment by Moooongo** [comment]
This might not be the right place to ask, but my actual traceback (at least the matplotlib traceback) looks like this. There is a separate traceback for numpy.concatenate that occurs occasionally. One of the problems that I noticed was that all of my data were in np.float32 to conserve memory, but it seems the default float for numpy is np.float64. So perhaps when matplotlib calls these numpy functions with default arguments, it asks for more memory that it actually needs? Is there a way of working around that?

````
File ~\anaconda3\Lib\site-packages\matplotlib\pyplot.py:2812, in plot(scalex, scaley, data, *args, **kwargs)
   2810 @_copy_docstring_and_deprecators(Axes.plot)
   2811 def plot(*args, scalex=True, scaley=True, data=None, **kwargs):
-> 2812     return gca().plot(
   2813         *args, scalex=scalex, scaley=scaley,
   2814         **({"data": data} if data is not None else {}), **kwargs)

File ~\anaconda3\Lib\site-packages\matplotlib\axes\_axes.py:1690, in Axes.plot(self, scalex, scaley, data, *args, **kwargs)
   1688 lines = [*self._get_lines(*args, data=data, **kwargs)]
   1689 for line in lines:
-> 1690     self.add_line(line)
   1691 if scalex:
   1692     self._request_autoscale_view("x")

File ~\anaconda3\Lib\site-packages\matplotlib\axes\_base.py:2304, in _AxesBase.add_line(self, line)
   2301 if line.get_clip_path() is None:
   2302     line.set_clip_path(self.patch)
-> 2304 self._update_line_limits(line)
   2305 if not line.get_label():
   2306     line.set_label(f'_child{len(self._children)}')

File ~\anaconda3\Lib\site-packages\matplotlib\axes\_base.py:2327, in _AxesBase._update_line_limits(self, line)
   2323 def _update_line_limits(self, line):
   2324     """
   2325     Figures out the data limit of the given line, updating self.dataLim.
   2326     """
-> 2327     path = line.get_path()
   2328     if path.vertices.size == 0:
   2329         return

File ~\anaconda3\Lib\site-packages\matplotlib\lines.py:1029, in Line2D.get_path(self)
   1027 """Return the `~matplotlib.path.Path` associated with this line."""
   1028 if self._invalidy or self._invalidx:
-> 1029     self.recache()
   1030 return self._path

File ~\anaconda3\Lib\site-packages\matplotlib\lines.py:662, in Line2D.recache(self, always)
    660 if always or self._invalidy:
    661     yconv = self.convert_yunits(self._yorig)
--> 662     y = _to_unmasked_float_array(yconv).ravel()
    663 else:
    664     y = self._y

File ~\anaconda3\Lib\site-packages\matplotlib\cbook\__init__.py:1335, in _to_unmasked_float_array(x)
   1333     return np.ma.asarray(x, float).filled(np.nan)
   1334 else:
-> 1335     return np.asarray(x, float)

MemoryError: Unable to allocate 382. MiB for an array with shape (50030001,) and data type float64
````

**Comment by jwLuo6413** [comment]
Any progress? I have encountered the same issue like this when plotting big geotiff raster file with imshow() function. Necessary traceback details shown below:

Environment: python3.10.14, Jupyter in Visual Studio Code
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[2], line 278
    275 lazPath = lidarDir + "azerbaijan/ShemakhiPoints-0-11.laz"
    276 # pcdDs = o3d.io.read_point_cloud("/mnt/d/Downloads/ShemakhiPoints-0-11.pcd")
    277 # o3d.visualization.draw_geometries([pcdDs])
--> 278 elevation_roughness_pcd(inDir = lidarDir + "azerbaijan/", merge = True, spatialRes = 2.0, interpAlg = "idw", noData = -9999.0, outMerge = lidarDir + "azerbaijan/azerbaijan_merge_float32.tif", \
    279                         srAlg = 'area_ratio', inSlope = lidarDir + "azerbaijan/azerbaijan_slope_float32.tif", inAspect = lidarDir + "azerbaijan/azerbaijan_aspect.tif", \
    280                         kernelSize = 3, outSr = lidarDir + "azerbaijan/azerbaijan_sr_area_ratio.tif", reproj = False, visual = True, norm = True)

Cell In[2], line 246, in elevation_roughness_pcd(inDir, merge, spatialRes, interpAlg, noData, outMerge, srAlg, inSlope, inAspect, kernelSize, outSr, reproj, visual, norm)
    244 crs = ccrs.PlateCarree()
    245 ax = fig.add_subplot(1, 2, 1, projection = crs)
--> 246 demPlot = ax.imshow(demArr.astype(np.float32), cmap = 'terrain', extent = [xDemMin, xDemMax, yDemMin, yDemMax])
    247 fig.colorbar(demPlot, ax = ax, pad = 0.10, fraction = 0.028, orientation = 'vertical')
    248 ax.xaxis.set_major_formatter(LONGITUDE_FORMATTER)

File d:\miniconda\envs\polynyas\lib\site-packages\cartopy\mpl\geoaxes.py:307, in _add_transform.<locals>.wrapper(self, *args, **kwargs)
    302     raise ValueError(f'Invalid transform: Spherical {func.__name__} '
    303                      'is not supported - consider using '
    304                      'PlateCarree/RotatedPole.')
    306 kwargs['transfrm'] = transform
--> 307 return func(self, *args, **kwargs)

File d:\miniconda\envs\polynyas\lib\site-packages\cartopy\mpl\geoaxes.py:1314, in GeoAxes.imshow(self, img, *args, **kwargs)
   1312 from cartopy.img_transform import warp_array
   1313 original_extent = extent
-> 1314 img, extent = warp_array(img,
   1315                          source_proj=transform,
   1316                          source_extent=original_extent,
   1317                          target_proj=self.projection,
   1318                          target_res=regrid_shape,
   1319                          target_extent=target_extent,
   1320                          mask_extrapolated=True,
   1321                          )
   1322 alpha = kwargs.pop('alpha', None)
   1323 if np.array(alpha).ndim == 2:

File d:\miniconda\envs\polynyas\lib\site-packages\cartopy\img_transform.py:192, in warp_array(array, target_proj, source_proj, target_res, source_extent, target_extent, mask_extrapolated)
    186 # XXX Take into account the extents of the original to determine
    187 # target_extents?
    188 target_native_x, target_native_y, extent = mesh_projection(
    189     target_proj, target_res[0], target_res[1],
    190     x_extents=target_x_extents, y_extents=target_y_extents)
--> 192 array = regrid(array, source_native_xy[0], source_native_xy[1],
    193                source_proj, target_proj,
    194                target_native_x, target_native_y,
    195                mask_extrapolated)
    196 return array, extent

File d:\miniconda\envs\polynyas\lib\site-packages\cartopy\img_transform.py:261, in regrid(array, source_x_coords, source_y_coords, source_proj, target_proj, target_x_points, target_y_points, mask_extrapolated)
    224 """
    225 Regrid the data array from the source projection to the target projection.
    226 
   (...)
    257 
    258 """
    260 # Stack our original xyz array, this will also wrap coords when necessary
--> 261 xyz = source_proj.transform_points(source_proj,
    262                                    source_x_coords.flatten(),
    263                                    source_y_coords.flatten())
    264 # Transform the target points into the source projection
    265 target_xyz = source_proj.transform_points(target_proj,
    266                                           target_x_points.flatten(),
    267                                           target_y_points.flatten())

File d:\miniconda\envs\polynyas\lib\site-packages\cartopy\crs.py:413, in CRS.transform_points(self, src_crs, x, y, z, trap)
    408         raise ValueError('x, y, and z arrays must have the same '
    409                          'length')
    411 npts = x.shape[0]
--> 413 result = np.empty([npts, 3], dtype=np.double)
    414 if npts:
    415     if self == src_crs and (
    416             isinstance(src_crs, _CylindricalProjection) or
    417             self.is_geodetic()):
    418         # convert from [0,360] to [-180,180]

MemoryError: Unable to allocate 33.2 GiB for an array with shape (1483694745, 3) and data type float64

Note: if there is no solution in matplotlib, is there any alternative python packages to recommend for very large big geotiff file visualization?

**Comment by timhoffm** [comment]
@jwLuo6413 your case is a bit different: The memory allocation comes from cartopy, more specifically from inside `GeoAxes.imshow` not from matplotlib itself. We have no control over that.

**Comment by tacaswell** [comment]
I'm going to close this as:
 - we can not reliably release memory (and if we could it would have unexpected side effects in most cases)
 - we make a fair number of internal copies of data and do scale up to float64.  there is undoubtedly a a lot of ways we can reduce internal memory usage, but I'm not sure that switching to float32 is the first thing to reach for (I'm a bit worried about the loss of precision in general).
 - scaling up big images can indeed get expensive and there is nothing we can do about exceeding memory in cartopy.

**Comment by jwLuo6413** [comment]
@timhoffm @tacaswell Get it. Many thanks!

**Comment by jwLuo6413** [comment]
@story645 Thanks for your assistance. Unfortunately, I cannot utilize rasterio to open and visualize big geotiff file as you recommend right now because some program is running, which consumes large proportion of memory of my laptop (~70% of entire RAM 64GB). Leave me more time :).

**Comment by Moooongo** [comment]
An eventual solution that I have resorted to, is to downsample the dataset before plotting (e.g. plot every other datapoint.) Of course at the cost of plot resolution, which was an acceptable compromise for me.
