### ISSUE TITLE
[ENH]: Make ScalarMappable callable

### ISSUE THREAD

**Issue by landoskape** [matplotlib/matplotlib#26911]
### Problem

In matplotlib, colormaps are callable but `ScalarMappables` are not callable. However, adding a colorbar to a figure requires a `ScalarMappable`. It would be useful to make `ScalarMappable` callable (for convenience) so they can be used interchangeably with colormap objects. This way, a user that wants to make a colorbar from a colormap doesn't need to use the second step of making a `ScalarMappable`, they can just use a `ScalarMappable` from the beginning. 

### Proposed solution

`ScalarMappables` already have the method called ``to_rgba(x, alpha=None, bytes=False, norm=True)``. So this feature request would be as simple as adding a ``__call__`` method that has identical inputs and deploys ``to_rgba()``.

```
def __call__(self, x, alpha=None, bytes=False, norm=True):
        """
        Return a normalized RGBA array corresponding to *x*.
        This is a convenience function that is identical to ``to_rgba``. For 
        more information, see the documentation for that method. 
        """
        return self.to_rgba(x, alpha=alpha, bytes=bytes, norm=norm)
```

**Comment by landoskape** [comment]
Addressed with pull request #26912

**Comment by anntzer** [comment]
A colorbar needs not only a colormap, but also a norm (to know how to label the values). In your proposal, how are the labels on the colorbar determined, and more generally can you please provide code for the intended use case?

**Comment by jklymak** [comment]
I don't think that's going to fly, though I understand the motivation.  You would normally just do

```python
norm = mpl.colors.Normalize(vmin=0, vmax=N-1)
cmap = mpl.colors.get_cmap('plasma')
sm = mpl.cm.ScalarMappable(cmap=cmap, norm=norm)
for n, d in enumerate(data):
   ax.plot(d, c=cmap(norm(n)))
fig.colorbar(sm, ax=ax)
```

I think it would be very bizarre for a `ScalarMappable` to return a colormap and the above does not seem too convoluted, at least for the special case where your `ScalarMappable` is not the thing you are adding directly to the plot.

**Comment by landoskape** [comment]
Understood, thanks for the explanation!
