### ISSUE TITLE
Should `ContourSet.allsegs` and `.allkinds` be deprecated?

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#26913]
> ... decoding paths is a lot harder than dealing with a list segments.  Given that contourpy returns a list of segments I think it would be nice if we made that available to users. It seems that is where we were before the deprecation, so perhaps it should be reconsidered?

_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/issues/26863#issuecomment-1732654726_

**Comment by jklymak** [comment]
Or maybe instead of leaving them as properties, they are rewritten as a helper `get_allsegs_allkinds()`? Again appreciate that some folks will want to access this directly from contourpy, but making this available doesn't seem too crufty to me.

**Comment by anntzer** [comment]
Perhaps more general would be to have a `Path().split()` method (name up to bikeshedding) that takes a compound path (i.e. possibly with internal MOVETOs) and splits it in paths without internal MOVETOs? (i.e. the opposite of Path.make_compound_path)
Then the requested functionality would be something like `[(subpath.vertices, subpath.codes) for path in contour.get_paths() for subpath in path.split()]`.

**Comment by jklymak** [comment]
That seems reasonable, if an implementation detail.  The above is still a mouthful for most people.

**Comment by anntzer** [comment]
I'm a bit curious, though about why MOVETOs are a problem for you.  After all, if you already handle allkinds, that means you already handle CLOSEPOLYs and need to differentiate between open and closed polygons, which seems already more complex than splitting at MOVETOs?

**Comment by anntzer** [comment]
I don't feel overly strongly about this; we could just restore the old allsegs/allkinds properties (and fix them to match the old format, as you note in https://github.com/matplotlib/matplotlib/issues/26863#issuecomment-1732807216, and mark them clearly as "exposed for practicality" so that they don't get removed in a future cleanup).
