### ISSUE TITLE
[ENH]: Add lookup table argument to ``get_cmap`` for automatic resampling

### ISSUE THREAD

**Issue by landoskape** [matplotlib/matplotlib#26925]
## Lack of forward consistency in the recommended replacement for a deprecated method
``matplotlib.cm.get_cmap()`` is deprecated. The recommended replacement is ``matplotlib.colormaps.get_cmap`` or ``matplotlib.colormaps[<name>]``. However, these replacements do not have the option to automatically resample the colormap using an optional input argument `lut`, like ``cm.get_cmap()`` does. 

## Example use case 
```python
import matplotlib as mpl

# Currently, users can automatically resample a colormap as follows:
N=5
jet_cmap = mpl.cm.get_cmap('jet', N)

# Once `cm.get_cmap` is fully deprecated, users will have to call `resampled` instead of using the `lut` argument:
jet_cmap = mpl.colormaps.get_cmap('jet')
jet_cmap = jet_cmap.resampled(N)
```

Is the plan for users to call ``resampled(<N>)`` themselves? Or would it be helpful to add the `lut` argument to ``matplotlib.colormaps.get_cmap``?

### Proposed solution

It seems easy enough to add the `lut` argument to the [``get_cmap()``](https://github.com/matplotlib/matplotlib/blob/v3.8.0/lib/matplotlib/cm.py#L194C30-L194C30) method of ``ColormapRegistry``.

## New code suggestion
```python
    def get_cmap(self, cmap, lut=None):
        """
        Return a color map specified through *cmap*.

        Parameters
        ----------
        cmap : str or `~matplotlib.colors.Colormap` or None

            - if a `.Colormap`, return it
            - if a string, look it up in ``mpl.colormaps``
            - if None, return the Colormap defined in :rc:`image.cmap`

        lut : int or None, default: None
             If *name* is not already a Colormap instance and *lut* is not None, the
             colormap will be resampled to have *lut* entries in the lookup table.

        Returns
        -------
        Colormap
        """
        # get the default color map
        if cmap is None:
            out_cmap = self[mpl.rcParams["image.cmap"]]

        # if the user passed in a Colormap, simply return it
        if isinstance(cmap, colors.Colormap):
            out_cmap = cmap
        if isinstance(cmap, str):
            _api.check_in_list(sorted(_colormaps), cmap=cmap)
            # otherwise, it must be a string so look it up
            out_cmap = self[cmap]
        raise TypeError(
            'get_cmap expects None or an instance of a str or Colormap . ' +
            f'you passed {cmap!r} of type {type(cmap)}'
        )

       if lut is None:
            return out_cmap
       else:
            return out_cmap.resampled(lut)
```

## Potential Issue
This could generate strange behavior in the case where the input `cmap` is already a colormap...

However, forward consistency seems valuable since the new ``colormaps.get_cmap()`` is recommended as a replacement for ``cm.get_cmap()`` but it has less functionality.

**Comment by greglucas** [comment]
There was a whats new note about the replacement: https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#colormap-method-for-creating-a-different-lookup-table-size

It is better to be explicit with the resampling through the `resampled(N)` method call and doesn't add any additional typing. The colormaps registry should only return what is in the registry and then it is up to the user to do what they want after the fact. The recommended replacement for your example is: `mpl.colormaps['jet'].resampled(N)`

**Comment by landoskape** [comment]
Ah, I see. Thanks for pointing me there.
