### ISSUE TITLE
Provide public access to the toolbar state for widget interaction

### ISSUE THREAD

**Issue by jlaura** [matplotlib/matplotlib#2694]
Currently the state of the MPL toolbar is not publicly available and must be accessed via `fig.canvas.manager.toolbar._active`.    Accessing via `_active` is dangerous as it is private and could potentially be altered without notice [link].(http://stackoverflow.com/questions/20711148/ignore-matplotlib-cursor-widget-when-toolbar-widget-selected/20712813#20712813.)

Is it possible to provide public access to the toolbar state so that widgets can 'fire' only when a toolbar item is not selected.  As an example, if a cursor widget is used to generate subplots, it currently generates a subplot based on the point of an initial pan or zoom request (toolbar item).

@tacaswell

**Comment by fariza** [comment]
MEP22 solved this problem. `fig.canvas.manager.toolmanager.active_toggle` returns the currently toggled tools
I'm closing this issue, please reopen if necessary
