### ISSUE TITLE
[Doc]: Python 3.8 support dropped?

### ISSUE THREAD

**Issue by veenstrajelmer** [matplotlib/matplotlib#26948]
### Documentation Link

https://github.com/matplotlib/matplotlib/releases/tag/v3.8.0

### Problem

* I noticed that matplotlib might not support python 3.8 anymore in [setup.py](https://github.com/matplotlib/matplotlib/blob/e3a5cee92bf10f07608f9e638f8d586ba81f16c7/setup.py#L11-L12)
* It is more common to put this in [pyproject.toml like xarray](https://github.com/pydata/xarray/blob/c3b5ead8cdbce38157265fd449a2a641cc118066/pyproject.toml#L22)
* At least it would be good to also add it to the release notes of the version where it was dropped. If I understand setup.py correctly, this would be [matplotlib 3.8](https://github.com/matplotlib/matplotlib/releases/tag/v3.8.0)

### Suggested improvement

see above

**Comment by ksunden** [comment]
This is listed in our changelog under the development subheading, along with other dependency version bumps:

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#increase-to-minimum-supported-versions-of-dependencies

We generally follow SPEC 0/NEP 29

- https://scientific-python.org/specs/spec-0000/
- https://numpy.org/neps/nep-0029-deprecation_policy.html

Matplotlib/setup.py predate pyproject.toml and were the standard for specifying this information for many years.

That said, we are in the process of updating our build system (see #26621) which will include having all of this metadata in pyproject.toml.

**Comment by veenstrajelmer** [comment]
Thanks for the clarification, I will now close this issue as you pointed out it is already being worked on.
