### ISSUE TITLE
[MNT]: Lock out Formatters/Locators if pandas is registered

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#26950]
### Summary

Pandas has their own time unit converter and Locators and Formatters.  Our date Locators and Formatters don't work with theirs, but people wanting to customize what pandas does keep trying to use them.   

https://stackoverflow.com/questions/77196777/matplot-lib-x-axis-shows-1970-as-the-starting-year-of-time-series-dates
https://stackoverflow.com/questions/64919511/dateformatter-is-bringing-1970-as-year-not-the-original-year-in-the-dataset?noredirect=1&lq=1

I think we should at least warn if the converter is not compatible with the Formatter, and we may need to special case pandas here.  This is difficult for us, because we really don't want pandas as a dependency.  

### Proposed fix

Somehow lock out our date Formatters and Locators if pandas Locators and Formatters are in the registry.

**Comment by rcomer** [comment]
Is this effectively the same problem as the nc-time-axis one?  #24951

**Comment by jklymak** [comment]
It is.  Thanks for the reminder!  I'll close here and edit that title and tags so I can find it again
