### ISSUE TITLE
[Bug]: animated_histogram missing control bar

### ISSUE THREAD

**Issue by irmo322** [matplotlib/matplotlib#26977]
### Bug summary

https://matplotlib.org/stable/gallery/animation/animated_histogram.html
shows an animated histogram with a nice control bar for playing forward, backward, sliding, etc...
When running the example script on my computer, it shows the animation but not the control bar.
When running it through jupyter notebook, it's not animated and there is no control bar.

### Code for reproduction

```python
"""
==================
Animated histogram
==================

Use histogram's `.BarContainer` to draw a bunch of rectangles for an animated
histogram.
"""

import matplotlib.pyplot as plt
import numpy as np

import matplotlib.animation as animation

# Fixing random state for reproducibility
np.random.seed(19680801)
# Fixing bin edges
HIST_BINS = np.linspace(-4, 4, 100)

# histogram our data with numpy
data = np.random.randn(1000)
n, _ = np.histogram(data, HIST_BINS)

# %%
# To animate the histogram, we need an ``animate`` function, which generates
# a random set of numbers and updates the heights of rectangles. We utilize a
# python closure to track an instance of `.BarContainer` whose `.Rectangle`
# patches we shall update.


def prepare_animation(bar_container):

    def animate(frame_number):
        # simulate new data coming in
        data = np.random.randn(1000)
        n, _ = np.histogram(data, HIST_BINS)
        for count, rect in zip(n, bar_container.patches):
            rect.set_height(count)
        return bar_container.patches
    return animate

# %%
# Using :func:`~matplotlib.pyplot.hist` allows us to get an instance of
# `.BarContainer`, which is a collection of `.Rectangle` instances. Calling
# ``prepare_animation`` will define ``animate`` function working with supplied
# `.BarContainer`, all this is used to setup `.FuncAnimation`.

# Output generated via `matplotlib.animation.Animation.to_jshtml`.

fig, ax = plt.subplots()
_, _, bar_container = ax.hist(data, HIST_BINS, lw=1,
                              ec="yellow", fc="green", alpha=0.5)
ax.set_ylim(top=55)  # set safe limit to ensure that all data is visible.

ani = animation.FuncAnimation(fig, prepare_animation(bar_container), 50,
                              repeat=False, blit=True)
plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/11430779/d246c9ba-056b-4a92-ab07-1e78706e3cf6)

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/11430779/4d13b829-10db-4c8c-90b7-d275a0c3067a)

### Operating system

Windows 10

### Matplotlib Version

3.7.2

### Matplotlib Backend

QtAgg

### Python version

3.9.18

### Jupyter version

6.4.8

### Installation

conda

**Comment by ksunden** [comment]
Those controls are specific to the [`Animation.HTMLWriter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.HTMLWriter.html#matplotlib.animation.HTMLWriter), which _is_ used for our gallery examples, but this is expected behavior for other usages (and in fact, the buttons are not rendered in mpl at all). They rely on using your browser's javascript.



We do have callbacks and methods that such controls _could_ be implemented using matplotlib widgets, but they are not implemented (at least not within the library itself) to my knowledge:

https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html#pausing-and-resuming-animations

**Comment by irmo322** [comment]
I see, thank you for the explanation :)

**Comment by irmo322** [comment]
@story645 indeed, this work like a charm in jupyter.
(following https://stackoverflow.com/questions/43445103/inline-animations-in-jupyter)
