### ISSUE TITLE
Path snapping does not respect quantization scale appropriate for Retina displays

### ISSUE THREAD

**Issue by piannucci** [matplotlib/matplotlib#2697]
Here's a toy version of something I'm working on:

<pre>import numpy as np, pylab as pl
N = M = 10
n = 1000
a = (np.random.standard_normal((n,N,M)) + 1j * np.random.standard_normal((n,N,M))) * .5**.5
b = np.linalg.svd(a)
pl.clf()
for i in xrange(b[1].shape[1]):
    _=pl.hist(b[1][:,i], bins=100, histtype='step', normed=True)
</pre>

If you run this with the macosx backend on a Retina display and carefully resize the window, you will find that the path snapping algorithm is snapping to the nearest two-pixel boundary, rather than the intended behavior of snapping to the nearest one-pixel boundary.

I speculate that this is also an issue with marker placement and hatching.

Two solutions are apparent.

One is for the macosx backend to do a little dance of rescaling the transform matrices before and after passing paths through the path iterator.  This seems like a pain and not very portable.  I believe that the other backends will be growing high-DPI flavors soon!  [edit: just took a look and it seems like only the macosx backend uses the PathCleanupIterator.  Is that correct?]

The other solution is for the path iterator to take the image magnification factor as an argument, and thread this through the code to the actual path snapper.

Incidentally, we might consider renaming the image magnification factor since it matters for vectors too.

**Comment by efiring** [comment]
The fix for this will probably be either via a partly new backend with agg for OSX, and/or the use of qt5agg, which should support Retina displays.

**Comment by mdboom** [comment]
Fixed by #6178
