### ISSUE TITLE
[Doc]: Histogram path example renders poorly in HTML

### ISSUE THREAD

**Issue by ksunden** [matplotlib/matplotlib#26990]
### Documentation Link

https://matplotlib.org/stable/gallery/misc/histogram_path.html#sphx-glr-gallery-misc-histogram-path-py

### Problem

This plot renders poorly in the gallery web page as it is a single figure that is modified over two cells, but is displayed only after the first cell

All modifications from the second cell are not shown and an empty plot is displayed for the second subplot.

### Suggested improvement

The two subplots could be made into different figures so each one gets rendered under their own cell.

Or if there is a way to tell sphinx-gallery to show the same figure twice (not sure if this exists).

Or the code blocks could be combined into one so there is only one figure rendered.

**Comment by niviPy** [comment]
I would like to work on this.

**Comment by niviPy** [comment]
Created a PR. @story645

**Comment by niviPy** [comment]
@story645, I have updated PR with a commit for review suggestions. Any update?
