### ISSUE TITLE
[Bug]: ContourLabeler.clabel with manual != False breaks unconnected contours

### ISSUE THREAD

**Issue by rho-novatron** [matplotlib/matplotlib#27062]
### Bug summary

When adding contour label positions manually (either via clicking or specifying an iterable of positions), contours with disconnected parts are not handled correctly, but sometimes rejoined seemingly arbitrarily.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
x, y = np.mgrid[-1:1:21j, -1:1:21j]

cs = ax.contour(x, y, 1/np.sqrt(0.01+(x+0.3)**2+y**2) + 1/np.sqrt(0.01+(x-0.3)**2+y**2), levels=[7])
cs.clabel(manual=[(0.2, 0.1)])
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/100362316/2a3136bc-17f6-483a-a6a3-e8a3a1ad8877)

### Expected outcome

As it looked in matplotlib 3.7.3:
![image](https://github.com/matplotlib/matplotlib/assets/100362316/7a1ab0a4-5799-4468-a4e4-3e9b19b79766)

### Matplotlib Version

3.8.0

### Installation

conda

**Comment by jklymak** [comment]
Did this break, or did it never work?

**Comment by rho-novatron** [comment]
It looks correct in 3.7.3.

**Comment by rho-novatron** [comment]
It is also still broken in main now (https://github.com/matplotlib/matplotlib/commit/6501209c3091898176b0a9179b32ad4edf9bf47e )

**Comment by ksunden** [comment]
I was able to fix this with a one line change, there was a line that struck me as possibly wrong when looking into #26971, but it was not related to that one, and was instead related to this bug. I'll add it to #27045

**Comment by rho-novatron** [comment]
Yay - the one-liner works for me. Thanks!
