### ISSUE TITLE
Fix limits if one axis scale is 'log'

### ISSUE THREAD

**Issue by swagner-astro** [matplotlib/matplotlib#27085]
### Problem

I am plotting my data (x,y) and want to show the x-axis in logscale. Because there are some negative values in x, the log10 can not be computed for all. This results in nans which are simply omitted when plotting (and this is what I want) but the y-axis limits are not updated for these missing values. It would be helpful to automatically set new axis limits if there are nans in the data. 

Example:

```
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(-10, 11, 1) 
plt.plot(x,x, marker='d')
```
![Screen Shot 2023-10-11 at 20 40 14](https://github.com/matplotlib/matplotlib/assets/80106004/f1364c90-9801-4506-b836-282908719b29)

and when I add the log scale on the x-axis, the negative values are omitted but the y-axis is not updated (even though I set nonpositive to 'clip' -- so maybe this is a bug?)
```
x = np.arange(-10, 11, 1) 
plt.plot(x,x, marker='d')
plt.xscale('log', nonpositive='clip')
```
![Screen Shot 2023-10-13 at 15 53 02](https://github.com/matplotlib/matplotlib/assets/80106004/bcf97d2e-10e7-4202-8128-589ee565a9f5)

In order to manually set `ylim`one would need to know the exact values of the data, so I suggest this could be adjusted automatically.

### Setup
Python 3.8.8
Matplotlib 3.7.1
Numpy 1.24.3
notebook 6.2.0 (executing and plotting in jupyter notebook)
on macOS 12.6.2 (Monterey)

### Proposed solution

Idea: 
If the xscale is set to 'log' and there are negative values in x, take the position of minimum of x < 0 and set y value at that position as new limit (ideally with the same margin as in the rest of the figure):

assuming self is the axis
```
margin = 0.1
if len(x[x<0]) !=0 and self.get_xscale=='log':
    ii_x_g0 = np.min(np.where(x>0))
    self.set_ylim(bottom = y[ii_x_g0] - y[ii_x_g0] * margin)

```

**Comment by jklymak** [comment]
Did you try ax.relim?

**Comment by swagner-astro** [comment]
No, ax.relim() did not work. (Don't actually remember if I did try it already, so thank you for the suggestion!)

Let me also add: I am working in a jupyter notebook (will add this in my post)
notebook 6.2.0

**Comment by ksunden** [comment]
The problem here is that we don't mask out NaN values of the opposite axis, and I'm not sure there is a particularly good way of doing that either. The X-axis values are re-lim'd because the transformed values are NaN, but the Y-axis values are untouched. yes it doesn't actually draw the points when either value is NaN, but the data still exists and is passed to the limit functions.

**Comment by swagner-astro** [comment]
How about the proposed solution "if the axes that is plotted in log contains negative values, adjust the other axis correspondingly"? At least when I set nonpositive = 'clip' that is what I would expect.

**Comment by tacaswell** [comment]
This is an alternate version the requests to auto-scale axis A based on the current view limits of axis B which we do not support in any other cases.  In other cases we have declined to support sub-range auto limits so I think we should do so here as well (xref https://github.com/matplotlib/matplotlib/issues/2123#issuecomment-1459777188 ).

This is also a confusion about what `nonpositive='clip'` means. 
 Per https://matplotlib.org/stable/api/scale_api.html#matplotlib.scale.LogScale the difference is with 'clip' when the transform code encounters a invalid value it either makes it "smaller than possible" (see  https://github.com/matplotlib/matplotlib/pull/9477) but still include it in the plotted data vs `'mask'` allows the `nan` to propagate through effectively not plotting the points.

In the case of 'clip' this means we draw a line from your last point to "very far left" and what ever y.  For reasonable limits, this effectively means a horizontal line, but if you set the limits to be almost the range of floats then you get somewhat funny results:

```python
import matplotlib.pyplot as plt
import numpy as np

fig, axd = plt.subplot_mosaic('A;B')

x = np.arange(-10, 11)

for ax, marker in zip(axd.values(), 'ds'):
    ax.plot(x, x, marker=marker)
    ax.plot([-10, 10], [-10, 10])
    ax.set_xscale('log', nonpositive='clip')

axd["B"].set_xlim(left=1e-300)    
```

![so](https://github.com/matplotlib/matplotlib/assets/199813/cc03fdaa-9cf6-4f12-bf56-85850ebf463e)

I'm going to close this as "not implementable" and refer future discussion to #2123 .
