### ISSUE TITLE
Unexpected behaviour with path.contains_points

### ISSUE THREAD

**Issue by cpelley** [matplotlib/matplotlib#2708]
The following example issustrates the unexpected behaviour I experienced, where points contained within the cut-out section return True by path.contains_points where I expect False (tested against master).

``` Python
import numpy as np

import matplotlib.pyplot as plt
from matplotlib.path import Path
from matplotlib.patches import PathPatch


vertices = np.array(
    [[-180., -90.],
     [-180., 90.],
     [180., 90.],
     [180., -90.],
     [0., -34.],
     [0.2, 89.],
     [-78., 89.],
     [-78., -34.]])

codes = np.array(
    [1, 2, 2, 2, 1, 2, 2, 2],
    dtype=np.uint8) 

path = Path(vertices, codes)
patch = PathPatch(path, facecolor='#cccccc', edgecolor='#999999')

plt.figure()

ax = plt.gca()
ax.add_patch(patch)
ax.set_xlim(-260, 260)
ax.set_ylim(-90, 100)

# Set of points to test if inside path
points = [[val, 0] for val in np.arange(-250, 300, 100)]
inside = path.contains_points(points)

# plot point draw ordering
order = 0
for vertex in vertices:
    plt.text(vertex[0], vertex[1], order)
    order += 1

# Print status for each point
for ins, pnt in zip(inside, points):
    print pnt, ins
    plt.text(pnt[0], pnt[1], ins)

plt.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/2071643/2789393/d26861a6-cbac-11e3-8f09-5ec5d4f1b4a0.png)

**Comment by doctor-ian** [comment]
+1

**Comment by oscargus** [comment]
Seems like there are Python bindings for Clipper now: https://pypi.org/project/pyclipper/

But also that there is a never version of Clipper, Clipper2: http://www.angusj.com/clipper2/Docs/Overview.htm

**Comment by tacaswell** [comment]
It also looks like GPC has had drama.  The linked website says it is no longer distributed by the author with a link we wikipedia what links to a MIT licensed with a licensing story I do not believe ( https://github.com/rickbrew/GeneralPolygonClipper ) so lets continue to stay away from that....

**Comment by tacaswell** [comment]
also, clipper2 looks like a good reason to use pybind11 if we want to go that way.
