### ISSUE TITLE
[Bug]: build failure with meson + python 3.11/3.12 + macos14.0

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#27107]
### Bug summary

I fail to build matplotlib HEAD with python 3.11/3.12 (freshly updated mamba environment) on macos14.0

### Code for reproduction

From a matplotlib repo:
```sh
git clean -xdf && pip install --no-build-isolation -ve .
```

### Actual outcome

```
Using pip 23.1.2 from /Users/antony/mambaforge/envs/default/lib/python3.12/site-packages/pip (python 3.12)
User install by explicit request
Created temporary directory: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-build-tracker-wb1h_5bj
Initialized build tracking at /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-build-tracker-wb1h_5bj
Created build tracker: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-build-tracker-wb1h_5bj
Entered build tracker: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-build-tracker-wb1h_5bj
Created temporary directory: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-install-80otcewo
Created temporary directory: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-ephem-wheel-cache-2d3i6u_d
Obtaining file:///Users/antony/src/extern/matplotlib
  Added file:///Users/antony/src/extern/matplotlib to build tracker '/private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-build-tracker-wb1h_5bj'
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Created temporary directory: /private/var/folders/19/mg_y1scj38z0v1v99tgtkn3m0000gn/T/pip-modern-metadata-qm6cfgxp
  Running command Preparing editable metadata (pyproject.toml)
  + meson setup /Users/antony/src/extern/matplotlib /Users/antony/src/extern/matplotlib/build/cp312 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/Users/antony/src/extern/matplotlib/build/cp312/meson-python-native-file.ini
  The Meson build system
  Version: 1.2.2
  Source dir: /Users/antony/src/extern/matplotlib
  Build dir: /Users/antony/src/extern/matplotlib/build/cp312
  Build type: native build
  Project name: matplotlib
  Project version: 3.9.0.dev0

  ../../meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version -fdiagnostics-color`
  stdout:
  stderr: ld: unknown options: --version
  clang: error: linker command failed with exit code 1 (use -v to see invocation)


  A full log can be found at /Users/antony/src/extern/matplotlib/build/cp312/meson-logs/meson-log.txt
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

### Expected outcome

build succeeds

### Additional information

- It's unclear to me whether that's rather an issue on meson-python's side.
- `cc -Wl,--version -fdiagnostics-color` indeed errors as above.  `cc` is `/usr/bin/cc`, `cc --version` is:
```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Operating system

macos 14

### Matplotlib Version

v3.8.0-447-g112a225738

### Installation

None

**Comment by QuLogic** [comment]
Can you check what's actually being tested in `meson-log.txt`?

**Comment by ksunden** [comment]
GNU `ld` supports `--version`, but LLVM `ld` from macos does not support `--version` ( it does support `-v` though, which is roughly equivalent)

GNU `ld` also supports `-v`, though `--version` additionally outputs copyright info, whereas `ld -v` just gives the one line.

**Comment by ksunden** [comment]
(That said, I do not see this error with my setup, which is using pip/virtualenv rather than conda/mamba envs/packages)

Also I guess its probably BSD `ld` rather than "LLVM", but the point stands (`bsd` is not actually mentioned in either the `-v` or the man page, but it seems more correct)

**Comment by anntzer** [comment]
meson-log.txt, back on python3.11 (though I suspect 3.12 would be the same):
```
Build started at 2023-10-17T08:53:30.600154
Main binary: /opt/homebrew/opt/python@3.11/bin/python3.11
Build Options: -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/Users/antony/src/extern/matplotlib/build/cp311/meson-python-native-file.ini
Python system: Darwin
The Meson build system
Version: 1.2.2
Source dir: /Users/antony/src/extern/matplotlib
Build dir: /Users/antony/src/extern/matplotlib/build/cp311
Build type: native build
Project name: matplotlib
Project version: 3.9.0.dev0
-----------
Detecting compiler via: `cc --version` -> 0
stdout:
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
-----------
Running command: cc -E -dM -
-----
-----------
Detecting linker via: `cc -Wl,--version -fdiagnostics-color` -> 1
stderr:
ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-----------

../../meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version -fdiagnostics-color`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
hmm... that's interesting that it seems to find homebrew's python (even though I am in an active mamba environment, where typing python at the shell indeed gives me mamba's python); however, I guess that may be another separate issue?

**Comment by QuLogic** [comment]
Do you perhaps have Meson installed via homebrew and not the mamba environment? I'd expect that might be why it's finding an unexpected Python.

**Comment by anntzer** [comment]
Ah, indeed.  Fixed that (meson is now installed in the env and I even removed the homebrew one just to be sure).  The logs now show that the correct (mamba) python is found, but the error (regarding `ld --version`) remains the same.

**Comment by anntzer** [comment]
Seems like an upstream bug actually, see https://github.com/mesonbuild/meson/issues/12282 -- the LDFLAGS fix does work for me.
May still be worth a note or a workaround?

**Comment by QuLogic** [comment]
Yes, it seems to be an Xcode 15 problem, but I wasn't able to work out if there's any update that would fix it.

**Comment by QuLogic** [comment]
@anntzer did Meson 1.3.0 help here?

**Comment by anntzer** [comment]
Even meson 1.2.3 fixed this, thanks.

**Comment by QuLogic** [comment]
> I'm also having issues with editable installs not working at all anymore... will try to do a proper writeup.

Remember to pass `--no-build-isolation` for those (don't know why `pip` would not default to that).

**Comment by anntzer** [comment]
Yes, this was with --no-build-isolation.
...
Although after uninstalling and reinstalling pybind11 (which is what the editable install was complaining about), everything works again (well, if I pass LDFLAGS).  Sorry for the lack of clean repro, I let you know if I manage to get one.

**Comment by anntzer** [comment]
This got fixed by itself at some point.
