### ISSUE TITLE
[Bug]: Wrong Result In Specific Calculation Task

### ISSUE THREAD

**Issue by dreamyouonly** [matplotlib/matplotlib#27112]
### Bug summary

During the work, I encountered the problem of inconsistency between drawing and data. I confirmed that the data source was correct through debugging and direct output. But by drawing directly on the enumeration values, the library behaves normally.Through testing, it was discovered that matplotlib behaves incorrectly in specific computing tasks.It is not clear whether all wrong use cases have been found, but [1000,999] is the main one that has been found so far.The characteristics discovered so far are that the first element of the list must satisfy the form of 10 raised to the nth power, and the subsequent elements must be 1 less than the first element.The code to reproduce is very simple.

### Code for reproduction

```python
import numpy as np
from matplotlib import pyplot as plt

a=[10000,9999]
b=np.array(a)

plt.plot(a)
plt.savefig('res2.png',dpi=100)
```

### Actual outcome

![res2](https://github.com/matplotlib/matplotlib/assets/51074339/309c312f-7dcf-483a-93c3-39c5fdc5cf73)

### Expected outcome

Obviously the first point should be 1000 and the second point should be 999.

### Additional information

The environment is as follows:

wjt@563745WJT:/mnt/c/Users/WJT$ pip list
Package                Version
---------------------- -------------
blinker                1.4
brewer2mpl             1.4.1
command-not-found      0.3
contourpy              1.1.1
cryptography           3.4.8
cycler                 0.12.1
dbus-python            1.2.18
distro                 1.7.0
distro-info            1.1build1
fonttools              4.43.1
ggplot                 0.11.5
httplib2               0.20.2
importlib-metadata     4.6.4
jeepney                0.7.1
keyring                23.5.0
kiwisolver             1.4.5
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
matplotlib             3.8.0
more-itertools         8.10.0
netifaces              0.11.0
numpy                  1.26.1
oauthlib               3.2.0
packaging              23.2
pandas                 2.1.1
patsy                  0.5.3
Pillow                 10.1.0
pip                    22.0.2
Pygments               2.11.2
PyGObject              3.42.1
PyJWT                  2.3.0
pyparsing              2.4.7
python-apt             2.4.0+ubuntu1
python-dateutil        2.8.2
pytz                   2023.3.post1
PyYAML                 5.4.1
scipy                  1.11.3
seaborn                0.13.0
SecretStorage          3.3.1
setuptools             59.6.0
six                    1.16.0
ssh-import-id          5.11
statsmodels            0.14.0
systemd-python         234
tzdata                 2023.3
ubuntu-advantage-tools 8001
ufw                    0.36.1
unattended-upgrades    0.1
wadllib                1.3.6
wheel                  0.37.1
zipp                   1.0.0

**It is currently known that this problem exists in 3.8.0, 3.7.1, 3.4.4.There is reason to suspect that this problem persists across multiple versions.**

### Operating system

Ubuntu/Ubuntu WSL

### Matplotlib Version

3.8.0

### Python version

3.10.12

### Installation

pip

**Comment by ksunden** [comment]
There is an offset on the axis of 1e4, so the y axis should be read as `10000 + 0` for the first point and `10000 - 1` for the second point.

This is expected behavior

**Comment by dreamyouonly** [comment]
Matplotlib is such a famous module that it has made me suspect that there is something wrong with my usage many times, but I think there shouldn't be anything wrong with just a few lines?

**Comment by ksunden** [comment]
https://matplotlib.org/stable/users/faq.html#prevent-ticklabels-from-having-an-offset

**Comment by dreamyouonly** [comment]
My doubts have been cleared, thank you for your quick and effective reply!

> https://matplotlib.org/stable/users/faq.html#prevent-ticklabels-from-having-an-offset
