### ISSUE TITLE
[ENH]: Generate warning in case subplots(sharex="all") vs different x-scales

### ISSUE THREAD

**Issue by george0st** [matplotlib/matplotlib#27124]
### Problem

It will be useful to **generate warning** in case that code contains more plots and these plots need to set different x-scale (with xticks). In case of subplots with sharex='all', it will block to slow relevant x-label descriptions.

    fig, ax = plt.subplots(2, 1, **sharex="all"**, squeeze=False, figsize=(15, 6))
    ...
    ax_cur.set_xticks(x_lst)

### Proposed solution

Generate warning in case of blocked functions see:

- subplots with sharex='all'
- and more plots with different setting of x-scale (with xticks)

**Comment by ksunden** [comment]
I'm not sure what you mean here, when axes are shared their xscales/xticks are changed together, so both will have the same ticks, and both will have the scale/ticks set to the new values. This is expected behavior, and we are quite unlikely to add warnings on expected behavior.

If you do not want these things to be shared, then don't use `sharex`, as that is the meaning of `sharex`.

Your example does not demonstrate setting different scales. it is not clear what `ax_cur` is and how it fits in here.

**Comment by george0st** [comment]
I had a problem to see x-axis description for first subplot (I used Axes.set_xticks). See sample of code:

```
import matplotlib.axes
import matplotlib.pyplot as plt

y_lst=[100,200,150,500]
x_lst=[2,4,8,16]

plt.style.use("bmh") #"ggplot" "seaborn-v0_8-poster"
fig, ax = plt.subplots(2, 1, sharex="all", squeeze=False, figsize=(15, 6))
ax_cur: matplotlib.axes.Axes = ax[0][0]

plt.suptitle("Performance",weight='bold', fontsize=18, ha="center", va="top")
ax_cur.set_title("title", fontsize=14,ha="center", va="top")

ax_cur.plot(x_lst, y_lst, color='green', linestyle="-")
ax_cur.legend()
ax_cur.set_ylabel('RTF [calls/sec]')
ax_cur.set_xticks(x_lst)

plt.grid()
plt.show()
```
See the output:
![Figure_1](https://github.com/matplotlib/matplotlib/assets/95856749/ce1a1e3c-6d0e-457e-8fd5-3b20be118cdf)

I solved the issue based on  sharex="none", but it will be useful to generate warning for coders (only idea).

**Comment by tacaswell** [comment]
That is the expected behavior,  see the description in https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.subplots

I am going to close this as it sounds like you can get the desired behavior by passing `sharex='none'` or by not palling `sharex` at all.

**Comment by jklymak** [comment]
It's not clear from this what you expected to be warned about?  The two x-axises are shared, therefore the same, therefore the tick labels are removed from the "interior" plot.  If you didn't want this effect, you should not have set `sharex`.
