### ISSUE TITLE
[MNT]: create a skipif decorator for missing fonts

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27121]
### Summary

A ton of the testing code dealing with fonts has something like the following code block in it

``` python
fp = fm.FontProperties(family=[family_name])

found_file_name = Path(fm.findfont(fp)).name
if file_name not in found_file_name:
    pytest.skip(f"Font {family_name} ({file_name}) is missing")
```

### Proposed fix

I think it'd be a lot cleaner if this could be wrapped up as a `@skipif_font_missing` decorator/fixture. Something like

```python
@skipif_font_missing(['Dejavu Sans', `Noto SansTC`]):
def test_font(family_name):
    # testing code
```

possibly with a nesting option when you want to explicitely test lists
```python
@skipif_font_missing([['Dejavu Sans', `Noto SansTC`]]):
def test_font(family_name):
    for font in family_name:
```

If new contributors are interested in working on this, this function would be added to [matplotlib.testing.decorators](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/testing/decorators.py). This issue requires working knowledge of pytest and some fluency with how matplotlib works with fonts.

**Comment by tacaswell** [comment]
I am going to close this because when we someone tried to implement this we discovered that it was more complex that anticipated and we can continue to live with the minor duplication.
