### ISSUE TITLE
[Bug]: macosx backend pause() cannot be ctrl-c'd

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#27120]
### Bug summary

Unlike with other backends, a plt.pause() on a macosx figure cannot be interrupted with ctrl-c.

### Code for reproduction

```sh
python -c 'from pylab import *; plot(); show(block=False); pause(5)'
```
Then press ctrl-c while the pause is running.

### Actual outcome

pause() is not interrupted.

### Expected outcome

pause is interrupted, like for other backends.

### Additional information

Likely the solution is the same as for qt: the ctrl-c handling code in FigureManagerMac.start_main_loop (i.e. _maybe_allow_interrupt, for the qt case) needs to be more or less duplicated into FigureCanvasMac.start_event_loop -- (except that right now FigureCanvasMac.start_event_loop is implemented in ObjC so things need to be moved around a bit).

### Operating system

macOS

### Matplotlib Version

v3.8.0-447-g112a225738

### Matplotlib Backend

macosx

### Python version

3.11

### Jupyter version

enosuchlib

### Installation

git checkout

**Comment by QuLogic** [comment]
Was this fixed by @greglucas PR?

**Comment by anntzer** [comment]
No.
