### ISSUE TITLE
[ENH]: Multi hatching in `ax.stackplot()`

### ISSUE THREAD

**Issue by pawjast** [matplotlib/matplotlib#27146]
### Problem

`ax.stackplot()` is used for conveniently plotting stacked area plot.

The documentation says that any `**kwargs` is passed on to `ax.fill_between`.

So, it all works fine if I work with colours, but not so much with hatching pattern.

If I want to add hatching, this is what I get by default:
```python
import matplotlib.pyplot as plt
import numpy as np

# Data
cols = 10
rows = 4

data = (
    np.reshape(np.arange(0, cols, 1), (1, -1)) ** 2
    + np.reshape(np.arange(0, rows), (-1, 1))
    + np.random.random((rows, cols))*5
)

# Plot
fig, ax = plt.subplots(
    figsize=(10,6),
    facecolor="white",
    layout="constrained"
)
fig.suptitle(
    "with hatching",
    fontsize=25,
    weight="bold"
)

x = range(data.shape[1])
ax.stackplot(
    x, data,
    hatch="x"
)

ax.set_xlim(0, 9)
ax.set_ylim(0, 350)
```

The outcome:
![image](https://github.com/matplotlib/matplotlib/assets/8880777/7b767630-2e72-4039-93b9-6d5cb6f53c8c)

But I would be more interested in getting something like this:
![image](https://github.com/matplotlib/matplotlib/assets/8880777/feb3e55c-ba6f-4faf-b725-3d5934721a0a)

### Proposed solution

The calling signature would be the same as before with exception that the `hatch` parameter would accept e.g. a list with `hatching` styles you want to use.

Example:
```python
ax.stackplot(
    x, data,
    hatch=["x", "\\", ".", "-"]
)
```

The example I've used above in the problem was create using the code below and in this case it varies the hatching by the density:
```python
fig, ax = plt.subplots(
    figsize=(10,6),
    facecolor="white",
    layout="constrained"
)
fig.suptitle(
    "with individual hatching",
    fontsize=25,
    weight="bold"
)

x = range(data.shape[1])
stack_baseline = np.zeros((data.shape[1]))
for i, y in enumerate(data):
    ax.fill_between(
        x, stack_baseline, y+stack_baseline,
        facecolor=(1, 1, 1, 0),
        hatch="x"*(data.shape[0]-i)
    )
    stack_baseline += y

ax.set_xlim(0, 9)
ax.set_ylim(0, 350)
```

**Comment by KartikeyBartwal** [comment]
Hello!
Don't you think 'with hatching' looks cleaner and makes it easier to extract insights? It's never a bad idea to have another style of representation at our disposal, but what is your opinion on this?

**Comment by rcomer** [comment]
To me this request seems analogous to the _hatch_ parameter added to pie at v3.7.
https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.7.0.html#hatch-parameter-for-pie

**Comment by timhoffm** [comment]
This is a reaonable request.

It's a good first issue because the change is local in https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/stackplot.py#L18-L127

and you can simply handle hatching analogous to the existing color handling.

**Comment by pawjast** [comment]
> Hello! Don't you think 'with hatching' looks cleaner and makes it easier to extract insights? It's never a bad idea to have another style of representation at our disposal, but what is your opinion on this?

To me, uniform hatching covering the whole data area is purely decorative and you still need colours to understand the data. As oppose to when you have individual hatching styles. Then you can go only with the hatching fill and remove the colours. Scientific papers are often required to be made in a way so you can print them in black and white. And they often use hatching for this purpose to distinguish between different areas.

**Comment by nbarlowATI** [comment]
Hi!  I agree on the usefulness of having different hatching styles in a stack plot, and had a go at implementing this following the guidance above (many thanks for making this so clear and newbie-friendly BTW!) in the draft PR: https://github.com/matplotlib/matplotlib/pull/27158
