### ISSUE TITLE
Small figsize yield wrong dimensions

### ISSUE THREAD

**Issue by ibell** [matplotlib/matplotlib#2716]
I am having issues with small figures that I am trying to generate.  Here is a minimal working example that demonstrates the issue:

```
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(0.5,0.5))
plt.savefig('small.png',dpi = 100)
```

which yields a file `small.png` with dimensions 291 x 50 (wxh) so the height is being properly handled, but the width is not.  This seems to be a bug.  I seem to recall having similar issues with large figures, I can post another mwe for large figsize too.

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Can anyone repro using the details provided above? Thanks!

**Comment by tacaswell** [comment]
This is almost certainly due to the GUI maintaining some minimum size, (presumably for the toolbar?)

Doing `fig.set_size_inches((.5, .5), forward=False)` after it is created, or if you do not need the GUI just using `'Agg'` are probably the best work-around.

**Comment by tacaswell** [comment]
And I can reproduce this:

```
16:51 $ ipython2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.use('wxagg')

In [3]: import matplotlib.pyplot as plt
/usr/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [4]: plt.ion()

In [5]: plt.figure(figsize=(.5, .5))
Out[5]: <matplotlib.figure.Figure at 0x7fef6770a9d0>

In [6]: fig = plt.gcf()

In [7]: fig.get_size_inches()
Out[7]: array([ 3.55,  0.5 ])

In [8]: 


```

**Comment by pdhall99** [comment]
I find the same problem with the TkAgg backend:
```
Python 2.7.13 (default, Dec 18 2016, 05:36:31) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.use('tkagg')

In [3]: import matplotlib.pyplot as plt

In [4]: plt.ion()

In [5]: fig = plt.figure(figsize=(.5, .5))

In [6]: fig.get_size_inches()
Out[6]: array([ 2.2,  0.5])

In [7]: plt.rcParams['toolbar'] = 'None'

In [8]: fig_without_toolbar = plt.figure(figsize=(.5, .5))

In [9]: fig_without_toolbar.get_size_inches()
Out[9]: array([ 0.5,  0.5])
```

**Matplotlib version**

- Matplotlib 2.0.0, Python 2.7.13, OSX
- Installed with MacPorts

**Comment by DietmarSchwertberger** [comment]
For wx this one would be a possible workaround:
https://github.com/DietmarSchwertberger/matplotlib/commit/4cd5499f4ca8b8aefca66e17fdf181d50e239d7f

Example, after creation of the frame:
![workaround2716](https://user-images.githubusercontent.com/5512021/36347155-73d50e78-1450-11e8-9de8-00e44221aade.png)
After a minimal resize by the user:
![workaround2716_resized](https://user-images.githubusercontent.com/5512021/36347165-9db594e2-1450-11e8-8acb-fef19bd34388.png)

**Comment by oliversheridanmethven** [comment]
Is there anything in the `rcParams` which could be modified to fix this? (I can't see any canvas "re-size"  or "preserve aspect_atio" options).
