### ISSUE TITLE
[MNT]: Reducing repetitive computations and simplified rotation calculation in proj3d.py

### ISSUE THREAD

**Issue by Akshat111111** [matplotlib/matplotlib#27186]
### Summary

It would be great  to reduce the repetitive computations by storing the repetitive values like (1/dx,1/dy,1/dz). Apart from it using the Numpy function effectively for vectored operations will be also helpful.
And  the rotation_about_vector function can be also enhanced by removing not required intermediate variables.

### Proposed fix

This requires installing NumPy from https://pypi.anaconda.org/scientific-python before building (assuming no build isolation, but I suspect that is already the case).

**Comment by QuLogic** [comment]
> This requires installing NumPy from https://pypi.anaconda.org/scientific-python before building (assuming no build isolation, but I suspect that is already the case).

I don't know what this would have to do with it, but we aren't going to start requiring an in-development version of NumPy, as we follow [SPEC-0000](https://scientific-python.org/specs/spec-0000/).

**Comment by tacaswell** [comment]
We have found that (as of the last time we bench marked) for very small (3x3) arrays the overhead of making a numpy array actually made things slower than just doing it.

I am going to close this issue as I do not think we want to track work on micro-optimizations but will always consider PRs that improve performance (assuming they come with bench marks).

**Comment by Akshat111111** [comment]
> > This requires installing NumPy from https://pypi.anaconda.org/scientific-python before building (assuming no build isolation, but I suspect that is already the case).
> 
> I don't know what this would have to do with it, but we aren't going to start requiring an in-development version of NumPy, as we follow [SPEC-0000](https://scientific-python.org/specs/spec-0000/).

Thankyou for specifying the usage of SPEC,I got the point.

**Comment by Akshat111111** [comment]
> We have found that (as of the last time we bench marked) for very small (3x3) arrays the overhead of making a numpy array actually made things slower than just doing it.
> 
> I am going to close this issue as I do not think we want to track work on micro-optimizations but will always consider PRs that improve performance (assuming they come with bench marks).

 I will work on more complex issues for now
