### ISSUE TITLE
[Bug]: Axis tick labels not written according to ScalarFormatter

### ISSUE THREAD

**Issue by olcc** [matplotlib/matplotlib#27198]
### Bug summary

I want _scalar_ ticklabels on a log axis, but changing the Formatter to ScalarFormatter does not modify all the ticklabels accordingly.

### Code for reproduction

```python
x = linspace(1,5)
fig = pyplot.figure()
ax = fig.add_subplot()
ax.semilogx(x, log(x))

fmt = ScalarFormatter()
fmt.set_scientific(False)
ax.xaxis.set_major_formatter(fmt)
```

### Actual outcome

The ticklabels shown are: "1.00", "2 x 10^0", "3 x 10^0",...

### Expected outcome

I expect to get scalar labels: "1", "2", "3",...

### Operating system

Windows

### Matplotlib Version

3.8.0

### Installation

None

**Comment by ksunden** [comment]
The 2, 3, etc. are actually _minor_ ticks, not _major_ ticks, so adding:

```python
ax.xaxis.set_minor_formatter(fmt)
```

Will get you what you want, I think.

**Comment by olcc** [comment]
Oups... You are right!
