### ISSUE TITLE
DOC: Point to step in stairs plot-type entry

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27194]
I think we could make stairs/step a bit easier to navigate by adding a drop of roadmapping by changing the intro sentence in the [stairs](https://matplotlib.org/devdocs/plot_types/basic/stairs.html) plot type entry:
https://github.com/matplotlib/matplotlib/blob/879cf769efa6801c1a949f9fe75c9626709c6314/galleries/plot_types/basic/stairs.py#L6

to something that sets expectations for stairs and points folks to steps when appropriate. Something like:
```rst
See `~matplotlib.axes.Axes.stairs` when plotting $y$ between $(x_i, x_{i+1})$ and ~`matplotlib.axes.Axes.step` when plotting $y$ at $x$.  
```
> Kinda like how pcolormesh has a little descriptor https://matplotlib.org/devdocs/plot_types/arrays/pcolormesh.html#sphx-glr-plot-types-arrays-pcolormesh-py
_Originally posted by @story645 in https://github.com/matplotlib/matplotlib/pull/26233#pullrequestreview-1509416306_

**Comment by ascodeasice** [comment]
Hi, can I work on this issue?

**Comment by pat8901** [comment]
I've reviewed the linked pull request, and I'm uncertain about the current status, whether the issue is still open or if the pull request is awaiting review. Could someone with more information provide an update?
