### ISSUE TITLE
limited number of grid lines in matplotlib?

### ISSUE THREAD

**Issue by bhlevca** [matplotlib/matplotlib#2722]
It appears that there is a limit (quite low ~ 500) of vertical grid lines that can be represented in a matplotlib graph.

I attached 3 graphs with minor grids :+1: 

1) 4hoursinterval-bad has ~ 300 vertical grid lines, but should have completed the whole X axis would have ended up with 600 vertical grid lines.
2) 4hoursinterval-good has ~ 420 vertical grid lines (reduced time interval)
3) 8hoursinterval-good has ~ 300 vertical grid lines. It covers the whole required time  interval, but at a lower resolution.

Therefore, I assume that there is either a bug somewhere or there is a limit in the code. If there is a limit is that documented anywhere?

![4hourintervalgrid-bad](https://f.cloud.github.com/assets/182494/1895215/1ddce502-7b1d-11e3-843d-c408d9a64476.png)
![4hourinterval-good](https://f.cloud.github.com/assets/182494/1895214/1ddcaf92-7b1d-11e3-901b-05b2b3d310c8.png)
![8hoursinterval-good](https://f.cloud.github.com/assets/182494/1895216/1dde0234-7b1d-11e3-8c44-40a189028367.png)

**Comment by petehuang** [comment]
Throwing in an update - seems like @efiring's summary still stands (thanks!), but would be useful for someone to dig back in and take a closer look

**Comment by efiring** [comment]
The self-contained example above is missing a line at the end:
```python
    display_temperature(x, y)
```
Now when I run it on master, I get a plot jam-packed with hourly tick lines, so maybe the problem has been fixed.  I will close it. @bhlevca, you can reopen it if you can post an example illustrating the problem on master.

**Comment by tacaswell** [comment]
The date tick code got a lot of work is the last year-ish.

**Comment by QuLogic** [comment]
Seems to work with 1.5.3, too.
