### ISSUE TITLE
[Doc]: Explicitly state the difference of `set_*` and `get_*`.

### ISSUE THREAD

**Issue by Jacfger** [matplotlib/matplotlib#27233]
### Documentation Link

https://matplotlib.org/stable/api/collections_api.html#matplotlib.collections.Collection.set_facecolor

### Problem

I found the documentation of the function `set_facecolors()` wasn't quite clear to me as in my recent issue I realize `set_facecolors()` wasn't actually the same as directly modifying `get_facecolors()` (And the only major difference for me was setting `stale=True`, probably because we can't set methods to `const` in Python).

https://github.com/matplotlib/matplotlib/issues/27216 

### Suggested improvement

I think it would be wise to explicitly state that the `set_*` functions mark the elements/axes or anything as "stale" which trigger redrawing when next `draw()` is invoked. 

I was looking into how to add it myself but as it turns out there were a lot of `set_*` functions. So I might as well ask if this is a good or stupid idea before I do it.

**Comment by anntzer** [comment]
I think this duplicates #24479 (see in particular https://github.com/matplotlib/matplotlib/issues/24479#issuecomment-1318217851 for concrete proposals).  Closing, but feel free to restart the discussion on the other thread.
