### ISSUE TITLE
[Bug]: Matplotlib hangs on Spyder run on Mac

### ISSUE THREAD

**Issue by SRattan16** [matplotlib/matplotlib#27231]
### Bug summary

I have a very basic code on my work computer to create a plot in Spyder using Matplotlib. I am new to Mac OS and installed Spyder through a standalone installer as my organization does not allow Anaconda. I have the most updated versions of Matplotlib, Spyder and Python. On running the code to generate an interactive plot, I see a white window that's frozen and hangs up. I can run Spyder only after I force quit the window.

Also, my backend is set to Automatic (Spyder-->preferences-->IPython console-->Graphics-->Backend-->automatic). 
Plot works fine when I set it to inline but the disadvantage there is that it's not interactive. 

### Code for reproduction

```python
import matplotlib.pyplot as plt

a=[1,2,3,4,5]
b=[1,4,6,8,10]
plt.plot(a,b)
plt.show()
```

### Actual outcome

<img width="970" alt="Screenshot 2023-10-29 at 5 19 49 PM" src="https://github.com/matplotlib/matplotlib/assets/31229269/8960d90a-4ffc-4ad7-bc2c-f684358b9cc6">

### Expected outcome

I was expecting to create a plot that works fine when I set backend to 'inline' 

### Operating system

Mac OS

### Matplotlib Version

3.8.0

### Matplotlib Backend

Qt5Agg

### Python version

3.9.6

### Installation

pip

**Comment by rcomer** [comment]
Do you see any output in the console when the window hangs?  Also what happens if you set the backend to a specific interactive one?

A colleague of mine recently had a similar problem in pycharm: the traceback showed that it was somehow defaulting to the macos backend, although she was using Linux…

**Comment by QuLogic** [comment]
Are you sure you are using the Qt5Agg backend? That one has the toolbar on the top of the figure and has separators between button groups.

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/pull/26669 may help in asking people to debug issues like this.

**Comment by greglucas** [comment]
Closing for lack of response. Feel free to add more information and we can reopen.
