### ISSUE TITLE
Class

### ISSUE THREAD

**Issue by Sushmachandana** [matplotlib/matplotlib#27241]
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('seaborn-poster')
 # sampling rate
sr = 100
# sampling interval
ts = 1.0/sr
t = np.arange(0,1,ts)
freq = 1.
x = 3*np.sin(2*np.pi*freq*t)
freq = 4
x += np.sin(2*np.pi*freq*t)
freq = 7 
x += 0.5* np.sin(2*np.pi*freq*t)
plt.figure(figsize = (8, 6))
plt.plot(t, x, 'r')
plt.ylabel('Amplitude')
plt.show()

**Comment by tacaswell** [comment]
I am going to close this for now.  Please ping to have this re-opened if there is bug to be reported here.
