### ISSUE TITLE
[ENH]: scatter should be able to take a list of edgecolors

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27242]
### Problem

Scatter already takes a list of colors, would be nice if it also took a list of edgecolors since those are also colors. 

### Proposed solution

Allow scatter to take in and set edgecolors on a permarker basis same as it does for colors

**Comment by mwaskom** [comment]
It's not documented but I think it actually already does?

```python
plt.scatter([1, 2, 3], [1, 2, 3], s=500, c="w", ec=["r", "b", "g"])
```
![image](https://github.com/matplotlib/matplotlib/assets/315810/b9b6c6e0-dc33-4543-b53b-a53cbe87ee32)

**Comment by rcomer** [comment]
[Scatter doc](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter) does list an _edgecolors_ parameter.
