### ISSUE TITLE
[Bug]: Segmentation fault when resizing on Python 3.12 and MacOS 14

### ISSUE THREAD

**Issue by JRI98** [matplotlib/matplotlib#27262]
### Bug summary

I upgraded Python from 3.11 to 3.12 and now I am unable to resize the window, even with a simple plot.
Apart from that, the plots are displayed correctly and I can move the window.

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.subplots()
plt.show()
```

### Actual outcome

[1]    xxxxx segmentation fault  python3.12 main.py

### Expected outcome

I expected the window to be resized without crashing

### Operating system

MacOS 14

### Matplotlib Version

3.8.1

### Matplotlib Backend

MacOSX

### Python version

3.12.0

### Installation

pip

**Comment by dopplershift** [comment]
Confirming that I was able to reproduce with Python 3.12 and Matplotlib 3.8.1 from conda-forge, macOS 14.1 on an M2.

**Comment by greglucas** [comment]
I cannot reproduce on an Intel Mac with matplotlib 3.8.1 from PyPI, so possibly just ARM related? Does 3.8.0 work as expected?

**Comment by JRI98** [comment]
> I cannot reproduce on an Intel Mac with matplotlib 3.8.1 from PyPI, so possibly just ARM related? Does 3.8.0 work as expected?

Yeah I forgot to mention this happens on an M1.
I also tried version 3.8.0 and 3.7.0, but get the same result. The bug appears to be related to Python 3.12

**Comment by tacaswell** [comment]
This suggests that the issues is with our extension module and have been bit by the c-level changes in upstream.

**Comment by ksunden** [comment]
Bisects to https://github.com/python/cpython/commit/df3173d28ef25a0f97d2cca8cf4e64e062a08d06 (python/cpython#101660)

That commit changed memory allocation behavior, though not immediately obvious to me what we are doing wrong (if anything).

The stated intent of the change is to enable per-subinterpretter GIL, though we do not (intentionally) use that feature (though the commit message does indicate value outside of that, and also states that the errors are indicative of problems down the line).
