### ISSUE TITLE
[Doc]: Two license pages in docs

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27277]
### Problem

We've got license files in user/project and in contribute and it's very unclear if this is an artifact of doc reshuffling or  b/c they mean different things:
* https://matplotlib.org/devdocs/devel/license.html
* https://matplotlib.org/devdocs/users/project/license.html

### Suggested improvement

Far as I can tell, the page in contribute looks more like an explainer for the license than a license page. If that's the case they should be merged into the page under project, otherwise each page should have clearer framing explaining what it's about.  

ETA: I think the contribute/licensees one is supposed to be "Which dependencies am I allowed to add to Matplotlib?"

**Comment by tacaswell** [comment]
One is an editorial explanation of why we have the license we do, the other is actually the License.

I do not think we should merge editorial content with the actual license as opinions may vary about choices, but the actual license is a statement of history/fact.

We should consider extending the second page to include the text of all the other files in https://github.com/matplotlib/matplotlib/tree/main/LICENSE
