### ISSUE TITLE
[Bug]: constrained layout annotation edge case

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#27284]
### Bug summary

Adapted from [this StackOverflow post](https://stackoverflow.com/questions/77435415/cant-create-text-and-annotations-outside-matplotlib-graph).  Constrained layout doesn't seem to cope with this combination of artists if the figure is square - the annotation is off the side of the figure.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(figsize=(7, 7), facecolor='lightgrey', layout='constrained')

# Define some graph offsets
start_x = 18
start_y = 18
end_x = 24
end_y = 24

# Draw an arrow
ax.annotate('Target',
            xy = (18, 20),
            xytext = (14, 20),
            arrowprops = dict(facecolor ='red', shrink = 0.05, width = 2.5),
            ha = 'center')

# Set the limits of the plot
ax.set_xlim(start_x, end_x)
ax.set_ylim(end_y, start_y)

# Customize the grid
plt.gca().set_aspect('equal', adjustable='box') # Make the grid equal in both dimensions
ax.xaxis.tick_top()                             # Move the X-Axis to the top

# Title
fig.suptitle("THE TITLE" + '\nSubtitle\n 1\n 2\n 3\n 4\n\n', fontsize=18)

plt.grid()
plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/10599679/2d56ea87-5917-46dc-bfd8-7dc1fccf0861)

### Expected outcome

I got this by just slightly resizing the  gui window.
![image](https://github.com/matplotlib/matplotlib/assets/10599679/3e86ebc6-0e0b-413f-8ba6-ca6af3593a24)

### Additional information

- Seems to be specific to a square figure.  A figsize of e.g. (7, 6) works fine.
- Calling `fig.draw_without_rendering()` before `plt.show()` does not make a difference.

### Operating system

Ubuntu

### Matplotlib Version

3.8.0 and main

### Matplotlib Backend

QtAgg

### Python version

3.11.6

### Jupyter version

N/A

### Installation

conda

**Comment by jklymak** [comment]
I think there are a lot of red herrings here.  I can reproduce with

```import matplotlib.pyplot as plt

fig, ax = plt.subplots(layout='constrained')

# Draw an arrow
ax.annotate('Target',
            xy = (18, 20),
            xytext = (14, 20),
            arrowprops = dict(facecolor ='red', shrink = 0.05, width = 2.5),
            ha = 'center')

# Set the limits of the plot
ax.set_xlim(18, 24)
ax.set_ylim(18, 24)

plt.show()
```

I think this is getting caught in a funky loop; the annotation is specified in data units, outside the axes.  So step one, we say that the bounding box is such that we need to shrink the axes by a factor of 0.6.  We do that, but that now means that the arrow is 0.6 smaller, so the algorithm does its second pass and says that there is more room, so makes the axes a factor of 1.25 larger.  But that also makes the arrow larger, and now it is off the page again.  The algorithm does the redraw twice,  If it did it an odd number of times, there would be too much space, and an even number of times the annotation will be clipped.

I don't think there is a lot we can do about this, and one wonders why the user wants to do this, as that would determine what the "better" solution might be. If it were me, I'd make a second invisible axes next to the parent, and explicitly save space for the annotations.

**Comment by jklymak** [comment]
And just to be clear, the aspect-ratio stuff allows the drawing to work when the figure is wide enough, but not if it's too narrow.  But that isn't the root of the problem.

**Comment by rcomer** [comment]
Thanks for your speedy diagnosis @jklymak. I guess we close this then.
