### ISSUE TITLE
[ENH]: Force exact exponent for tick formatting

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27341]
### Problem

The stackplot demo is slightly confusing b/c it says in millions and has a sort of implied multiply the number by 1e6, so was trying to make that explicit in #27335 and far as I can tell that's not actually possible. [set_scientific/set_powerlimits/set_scilimits](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.ScalarFormatter.set_scientific) set a threshold but like here I set a threshold to 6 and it decides to round up. 

![image](https://github.com/matplotlib/matplotlib/assets/1300499/20fd13f6-72c8-4308-8fff-31cc84530104)

### Proposed solution

Either like `useOffset` change the signature of `set_scientific` so that it can also take in a value that forces the exponent or add a new method on ticker + add/overload a paramter on `ticklable_format` that does the same.

**Comment by StefRe** [comment]
I'm afraid I don't understand what you're trying to do - maybe you can make a freehand sketch of the desired output.
