### ISSUE TITLE
[Bug]: UserWarning: Unable to import Axes3D - Multiple Matplotlib Versions Installed

### ISSUE THREAD

**Issue by ducmn** [matplotlib/matplotlib#27342]
### Bug summary

The warning erroneously mentions "multiple Matplotlib versions," misleadingly attributing the issue to version conflicts. In reality, the problem seems rooted in an error within Matplotlib's code, potentially linked to a path misconfiguration impeding the proper import of the Axes3D module.

### Code for reproduction

```python
import matplotlib.pyplot as plt
```

### Actual outcome

AppData\Roaming\Python\Python39\site-packages\matplotlib\projections\__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

### Expected outcome

The expected outcome is the successful import of Axes3D without triggering any warnings about multiple Matplotlib versions.

### Additional information

Has this worked in earlier versions? Yes.
Do you know why this bug is happening? No.
Do you maybe even know a fix? Not yet.

### Operating system

Windows

### Matplotlib Version

3.8.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.12

### Jupyter version

3.4.7

### Installation

pip

**Comment by rcomer** [comment]
Could you promote the warning to an exception and post the full traceback?  E.g.

```python
import warnings

warnings.filterwarnings("error")

import matplotlib.pyplot as plt
```

**Comment by ducmn** [comment]
> Are you doing this in a virtual environment, or using plain system python?

It happens for both plain & virtual environments; it only yields a warning the first time the import is run, but not on the second time the same code is run. Error pops up every time the kernel is restarted.

**Comment by ducmn** [comment]
> Could you promote the warning to an exception and post the full traceback? E.g.
> 
> ```python
> import warnings
> 
> warnings.filterwarnings("error")
> 
> import matplotlib.pyplot as plt
> ```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python39\site-packages\matplotlib\projections\__init__.py:60
     59 try:
---> 60     from mpl_toolkits.mplot3d import axes3d
     61 except ImportError:

File E:\Miniconda\envs\insight_analytics\lib\site-packages\mpl_toolkits\mplot3d\__init__.py:1
----> 1 from .axes3d import Axes3D

File E:\Miniconda\envs\insight_analytics\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py:23
     21 import numpy as np
---> 23 from matplotlib import _api, cbook, docstring, _preprocess_data
     24 import matplotlib.artist as martist

ImportError: cannot import name 'docstring' from 'matplotlib' (C:\Users\duc.nguyen\AppData\Roaming\Python\Python39\site-packages\matplotlib\__init__.py)

During handling of the above exception, another exception occurred:

UserWarning                               Traceback (most recent call last)
Cell In[2], line 5
      1 import warnings
      3 warnings.filterwarnings("error")
----> 5 import matplotlib.pyplot as plt

File ~\AppData\Roaming\Python\Python39\site-packages\matplotlib\pyplot.py:66
     63 from matplotlib import _docstring
     64 from matplotlib.backend_bases import (
     65     FigureCanvasBase, FigureManagerBase, MouseButton)
---> 66 from matplotlib.figure import Figure, FigureBase, figaspect
     67 from matplotlib.gridspec import GridSpec, SubplotSpec
     68 from matplotlib import rcsetup, rcParamsDefault, rcParamsOrig

File ~\AppData\Roaming\Python\Python39\site-packages\matplotlib\figure.py:43
     40 import numpy as np
     42 import matplotlib as mpl
---> 43 from matplotlib import _blocking_input, backend_bases, _docstring, projections
     44 from matplotlib.artist import (
     45     Artist, allow_rasterization, _finalize_rasterization)
     46 from matplotlib.backend_bases import (
     47     DrawEvent, FigureCanvasBase, NonGuiException, MouseButton, _get_renderer)

File ~\AppData\Roaming\Python\Python39\site-packages\matplotlib\projections\__init__.py:63
     61 except ImportError:
     62     import warnings
---> 63     warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
     64                   "Matplotlib being installed (e.g. as a system package and as a pip "
     65                   "package). As a result, the 3D projection is not available.")
     66     Axes3D = None
     69 class ProjectionRegistry:

UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.

**Comment by ducmn** [comment]
This behaviour happens in both plain system Python & in virtual environment.

**Comment by ducmn** [comment]
Probably too niche of an issue.

**Comment by ducmn** [comment]
Probably too niche of an issue.

**Comment by rcomer** [comment]
@ducmn not sure about “too niche” but I suspect it’s a problem in your setup rather than a Matplotlib bug.  Basically, you shouldn’t be able to import anything from a conda environment when that environment isn’t activated.  I don’t know how to debug why it is happening here though.

**Comment by ksunden** [comment]
It is very much another presentation of what is discussed in #26827. The workaround which warns (but doesn't error) is a partial fix, but there is a reason that issue was not closed. The cause is indeed exactly what the warning says: multiple matplotlib versions are installed and accessible (at least the mpl-toolkits namespace package portion).

There is more discussion of the details in that issue, but the short version is that setuptools has deprecated the way we did namespace packages (mpl-toolkits, where the 3d code is implemented) so we were a bit painted into a corner. The workaround unfortunately doesn't allow using the 3D functionality (and at least probably other mpl_toolkits functionality), but otherwise the library is unaffected.

It is a bit less "too niche" and more "no one knows how to fix it without going back to using deprecated functionality, which will just land us back here soon"

**Comment by GER-Jani** [comment]
I'm using pip and system wide installed packages. Conda is not installed and I got this trackback:

<details open>
<summary>Show Traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Python\Python310\site-packages\matplotlib\projections\__init__.py", line 60, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "C:\Program Files\Python310\lib\site-packages\mpl_toolkits\mplot3d\__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "C:\Program Files\Python310\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (C:\Users\user_name\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\Git\python_project\run.py", line 5, in <module>
    from survey_evaluator.evaluator import evaluate_json_survey, evaluate_total_json_surveys
  File "C:\Users\user_name\Git\python_project\survey_evaluator\evaluator.py", line 11, in <module>
    from survey_evaluator.p_05_c_03_graphical_representation import generate_graphical_representation
  File "C:\Users\user_name\Git\python_project\survey_evaluator\p_05_c_03_graphical_representation.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\user_name\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "C:\Users\user_name\AppData\Roaming\Python\Python310\site-packages\matplotlib\figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "C:\Users\user_name\AppData\Roaming\Python\Python310\site-packages\matplotlib\projections\__init__.py", line 63, in <module>
    warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
```

</details>

**Comment by ksunden** [comment]
You appear to be treating warnings as errors there, as we catch the error and warn to avoid silently failing.

**Comment by saim074** [comment]
I was getting the same warning. I uninstalled matplotlib `pip uninstall matplotlib` and then didn't install it again. It stopped giving the warning.

**Comment by DimitriBolt** [comment]
I have the same error.
I try to rub this command:
`import matplotlib.pyplot as plt`
Has someone found a solution?

**Comment by codesplode** [comment]
I found that this issue occured on my ubuntu system because apt had `python3-matplotlib` package installed in addition to the pip `matplotlib` package and both were different versions. I resolved by remove the apt package with `apt remove python3-matplotlib`.

**Comment by edxmorgan** [comment]
thank @codesplode you are right!

**Comment by vkrmch** [comment]
> I found that this issue occured on my ubuntu system because apt had `python3-matplotlib` package installed in addition to the pip `matplotlib` package and both were different versions. I resolved by remove the apt package with `apt remove python3-matplotlib`.
> 
> The issue is that in the system package directories, this caused there to actually be 2 matplotlib versions with or without venv.

This was driving me nuts on  Jetson Orin AGX, thanks for this solution.

**Comment by matkoniecz** [comment]
For me problem is that

> sudo apt remove python3-matplotlib

wants to remove Qgis:

> The following packages will be REMOVED:
>  androguard mnemosyne python3-matplotlib python3-qgis python3-qgis-common qgis qgis-plugin-grass

**Comment by MGAMZ** [comment]
> I found that this issue occured on my ubuntu system because apt had `python3-matplotlib` package installed in addition to the pip `matplotlib` package and both were different versions. I resolved by remove the apt package with `apt remove python3-matplotlib`.
> 
> The issue is that in the system package directories, this caused there to actually be 2 matplotlib versions with or without venv.

Thanks A Lot！

**Comment by PhPernet** [comment]
> For me problem is that
> 
> > sudo apt remove python3-matplotlib
> 
> wants to remove Qgis:
> 
> > The following packages will be REMOVED:
> > androguard mnemosyne python3-matplotlib python3-qgis python3-qgis-common qgis qgis-plugin-grass

Same for me, apt wants to remove `ros-humble-ros-gzharmonic`

**Comment by ynrng** [comment]
I am using some ros packages that depend on `python3-matplotlib`, so instead of the above suggestions, I went another way.
```
# uninstall all the numpy, cv, matplotlib relative packages by pip
pip uninstall numpy matplotlib opencv-python

# install with apt
sudo apt install python3-numpy python3-matplotlib python3-opencv

# fix dependency issues if any, optional
# fix numpy version not compatible with matplotlib
pip install "numpy=1.23"
# to fix the error "ImportError: cannot import name 'docstring' from 'matplotlib'" in [mpl_toolkits](https://stackoverflow.com/a/76907897/8262079)
pip install "basemap<2.0.0" 

# check version 
python3 -c "import cv2, numpy, matplotlib; print(cv2.__version__, numpy.__version__, matplotlib.__version__)"
# 4.5.4 1.26.4 3.8.4 <- this combination works for me
```

**Comment by mdarnold1** [comment]
The problem can occur due to certain packaging (e.g. in Debian etc).  Specifically, using setuptools and namespace means that python finds the packaged mptools first (via /usr/lib/python3/dist-packages/matplotlib-3.6.3-nspkg.pth). 

Package maintainers should fix this by adhering to PEP 420.  

Users can workaround by creating usercustomize (e.g. ~/.local/lib/python3.12/site-packages/usercustomize.py) so that python finds the user install first, something like this:

```
from pathlib import Path
import sys

_user_mpl_toolkits = Path.home() / ".local/lib/python3.12/site-packages/mpl_toolkits"
_mod = sys.modules.get("mpl_toolkits")
if _mod is not None and _user_mpl_toolkits.exists():
    _paths = list(getattr(_mod, "__path__", []))
    _user = str(_user_mpl_toolkits)
    if _user in _paths:
        _paths.remove(_user)
    _paths.insert(0, _user)
    _mod.__path__[:] = _paths
```
