### ISSUE TITLE
[ENH]: Suggest 'CN' if color is an integer

### ISSUE THREAD

**Issue by boeddeker** [matplotlib/matplotlib#27378]
### Problem

It took me some year to figure out, that matplotlib supports `'CN'` (e.g. `'C1'`) as color.
I tried `1` (integer), but that raises only a `ValueError: 1 is not a valid value for color` (triggered by `plt.plot(np.arange(10), color=1)`)
and when I implemented a workaround to support integers in our wrappers, a colleague asked about the difference to `'CN'`.

### Proposed solution

Current code:

https://github.com/matplotlib/matplotlib/blob/62a5ba4d3e3ac6f32ea4c8c9e89c62381390ac9a/lib/matplotlib/colors.py#L240-L246

Suggestion:
Add some more text to the exception message, when the type is an integer, e.g.:

```python
def _check_color_like(**kwargs): 
     """ 
     For each *key, value* pair in *kwargs*, check that *value* is color-like. 
     """ 
     for k, v in kwargs.items(): 
         if not is_color_like(v): 
             if isinstance(v, int) and k == "color" and v >= 0:
                 raise ValueError(
                     f"{v!r} is not a valid value for {k}.\n"
                     f"To get the N'th entry from mpl.rcParams['axes.prop_cycle'] you can use 'CN' instead of an integer.") 
             raise ValueError(f"{v!r} is not a valid value for {k}") 
```

**Comment by boeddeker** [comment]
> Can we improve our documentation somehow to make it clear that the format is C\d+?

Hmm. I don't know. I started with MATLAB and switched then to python/matplotlib.
So, this is the first time, that I see the [color spec doc](https://matplotlib.org/stable/users/explain/colors/colors.html#colors-def).

> I'm wondering if changing the original error message (no special case) to link to the [color spec doc](https://matplotlib.org/stable/users/explain/colors/colors.html#colors-def) would also have worked to resolve this confusion?

That sounds to me to be a good idea. It would make it easier to find the right page.

> I'm ambivalent on the proposal to support integer colors indexing into CN. I understand the convenience, but am concerned about the potential confusion w/ the float and float string formats - where the number directly maps to a color rather then the layer of indirection here.

Yes, an integer could have multiple interpretations, e.g. 1 could be white (0-1), close to black (0-255) or the second color.
Since the integer gray format 0-255 is not supported, it may be an option to use the color index for integers, but I am also not sure, whether it improves mpl or not.

I personally like it, when software tries to predict the intent and suggest what the user may want to do in the exception.

**Comment by anntzer** [comment]
We should not guess the user's intent (per the zen of python), but enumerating all possible inputs is actually not that long and probably makes sense here:
```python
    for k, v in kwargs.items():
        if not is_color_like(v):
            raise ValueError(
                f"{v!r} is not a valid value for {k}: supported inputs are "
                f"(r, g, b) and (r, g, b, a) 0-1 float tuples; "
                f"'#rrggbb', '#rrggbbaa', '#rgb', '#rgba' strings; "
                f"named color strings; "
                f"string reprs of 0-1 floats for grayscale values; "
                f"'C0', 'C1', ... strings for colors of the color cycle; "
                f"and pairs combining one of the above with an alpha value")
```
