### ISSUE TITLE
[Bug]: Error in Hexbin plot in Matplotlib 3.0 onward

### ISSUE THREAD

**Issue by Zubair-Physicist** [matplotlib/matplotlib#27383]
### Bug summary

 First, I would like to thank you for creating a wonderful matplotlib for data visualization. 

I am writing to inform you about problems in hexbin plot in the Matplotlib 3.0 onward. When I was working on my data analysis, I noticed something was wrong when we plotted the distribution of the bin in the log scale.  Moreover, the hexbin plot is correct in the previous version of the matplotlib 2.2.5.  

I've attached the files of the same. You can clearly observe that the main error is when we plot the bins in log scale. I hope you will look into the problem and update it accordingly. 

![hexplot_matplotlib3 10](https://github.com/matplotlib/matplotlib/assets/66845821/63eeb554-ab1c-4764-baac-cbe545ec56e6)
![hexplot_matplotlib2 2 5](https://github.com/matplotlib/matplotlib/assets/66845821/89f04ff2-2533-484b-83a2-07646e971851)

### Code for reproduction

```python
no code is available
```

### Actual outcome

NA

### Expected outcome

NA

### Operating system

Windows

### Matplotlib Version

3.8.2

### Python version

python 3

### Installation

conda

**Comment by ksunden** [comment]
This was actually incorrect prior to version 3.5:

https://matplotlib.org/3.5.3/api/prev_api_changes/api_changes_3.5.0.html#hexbin-with-a-log-norm

We had been adding 1 so every bin had a value, but 0 cannot be displayed on a logarithmically scaled colormap, so now it has no value (and thus are not displayed if zero). We no longer incorrectly add 1.

There was some changes during the early 3.8 series to the boundary conditions of hexbin, but default behavior should be what it used to be as of 3.8.2 (and more consistent with different modes of calling hexbin overall).

**Comment by Zubair-Physicist** [comment]
Hi,
I understand the problem with zero in the log scale.


My concern is with the color bar labeling and scaling. The hexbin plot in
matplotbin2.2.5 looks okay. The hexbin says log scale means values are
taken log10(var), not the log10(var) with log scaling of colorbar, which is
present in matplotlib 3.0 onward version.


*Example:* See the left plot where the color bar displays bin count. Let's
say the bin count is 500, then log10(500) = 2.69, which is expected to be
shown in the colorbar (see plots for hexbin plot for matplotlib 2.2.5).
Unfortunately, in the latex version of matplotlib, the value and colorbar
are different.


Please clarify it for me. And do the necessary update.

Best wishes,
Zubair Shaikh
----------------------------------------------------------

*Dr. Zubair Ibrahim Shaikh,*
*Postdoctoral Researcher,Space Sciences Laboratory (SSL),*
*University of California**, Berkeley,*
*7 Gauss Way, CA 94720, USA*

*email:* ***@***.*** ***@***.***>u*
*website: **https://sites.google.com/view/shaikhzubair/
<https://sites.google.com/view/shaikhzubair/>*
*Orcid: https://orcid.org/0000-0002-9206-632
<https://orcid.org/0000-0002-9206-6327>7*
-------------------------------------------------------------------------

**Comment by tacaswell** [comment]
I agree that the label on the colorbar should be updated.

At some point we went from having to "manually" do the log scale to the color mapping / normalization machinery doing it for us.

**Comment by Zubair-Physicist** [comment]
Thank you for understanding the problem.
I hope you will update it soon.

Best wishes,
Zubair Shaikh
----------------------------------------------------------

*Dr. Zubair Ibrahim Shaikh,*
*Postdoctoral Researcher,Space Sciences Laboratory (SSL),*
*University of California**, Berkeley,*
*7 Gauss Way, CA 94720, USA*

*email:* ***@***.*** ***@***.***>u*
*website: **https://sites.google.com/view/shaikhzubair/
<https://sites.google.com/view/shaikhzubair/>*
*Orcid: https://orcid.org/0000-0002-9206-632
<https://orcid.org/0000-0002-9206-6327>7*
-------------------------------------------------------------------------

**Comment by QuLogic** [comment]
The relevant change here was #9223, I believe.
