### ISSUE TITLE
[Bug]: None in y or yerr arrays leads to TypeError when using errorbar

### ISSUE THREAD

**Issue by verena-neufeld** [matplotlib/matplotlib#27399]
### Bug summary

When an element in the `y` or `yerr` arrays in `None` when using `errorbar`, a `TypeError` is raised.

### Code for reproduction

```python
import matplotlib.pyplot as plt

# passes
a = [1,2,None]
b = [0.1,0.2,0.3]

plt.plot(a,b)
plt.show()
plt.close()

# passes
a = [1,2,3]
b = [0.1,0.2,None]

plt.plot(a,b)
plt.show()
plt.close()

# passes
a = [1,2,None]
b = [0.1,0.2,0.3]
berr = [0.04, 0.04, 0.04]

plt.errorbar(a,b,yerr=berr)
plt.show()
plt.close()

# fails
a = [1,2,3]
b = [0.1,0.2,0.3]
berr = [0.04, 0.04, None]

plt.errorbar(a,b,yerr=berr)
plt.show()
plt.close()

# fails
a = [1,2,3]
b = [0.1,0.2,None]
berr = [0.04, 0.04, 0.3]

plt.errorbar(a,b,yerr=berr)
plt.show()
plt.close()
```

### Actual outcome

Three graphs are successfully shown. The fourth one fails with:
```
Traceback (most recent call last):
  File "<mydirectory>/plot.py", line 33, in <module>
    plt.errorbar(a,b,yerr=berr)
  File "<mypythonpackagesdirectory>/matplotlib/pyplot.py", line 2564, in errorbar
    return gca().errorbar(
           ^^^^^^^^^^^^^^^
  File "<mypythonpackagesdirectory>/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mypythonpackagesdirectory>/matplotlib/axes/_axes.py", line 3634, in errorbar
    if np.any(np.less(err, -err, out=res, where=(err == err))):
                           ^^^^
TypeError: bad operand type for unary -: 'NoneType'
```

### Expected outcome

I understand that there might not be a right outcome here but maybe, as done with `plt.plot`, a point where any of the `x`, `y`, `yerr` items are `None`, could simply not be plotted.

### Matplotlib Version

3.7.2

### Python version

3.11.4

### Installation

pip

**Comment by oscargus** [comment]
I checked this quickly and removing the check makes it now die on https://github.com/matplotlib/matplotlib/blob/88e4a4333fd36063dc04935891e228d65f5bb5cb/lib/matplotlib/axes/_axes.py#L3694
trying to multiply int and None.

I see two options:
1. Check for `None` in `err` and error with a better message (saying that `nan` should be used)
2. Convert `None` to `nan`

**Comment by verena-neufeld** [comment]
Thanks for your quick response and fix!
