### ISSUE TITLE
[ENH]: contour polygons should follow the right-hand rule

### ISSUE THREAD

**Issue by AugustinMortier** [matplotlib/matplotlib#27443]
### Problem

Hi! I am using the [geojsoncontour](https://github.com/bartromgens/geojsoncontour) library in order to create geojson files based on the matplotlib contourf function output. It looks like since the version 3.8.?, the polygons are not following the [right-hand rule](https://gis.stackexchange.com/questions/259944/polygons-and-multipolygons-should-follow-the-right-hand-rule) anymore. I noticed, in the recent release notes, some mentions of "revert contour" deprecation, and I was thinking this could be related.. I'm not even sure if this would be on matplotlib, or on geojsoncontour to make sure of that, but the latter library seems to have a limited number of contributors, so I'm trying my chance here!

**Comment by ianthomas23** [comment]
There has been no change in the orientation of contours calculated by Matplotlib, they always follow the right-hand rule provided your x and y coordinates are both increasing or both decreasing. It is certainly possible that `geojsoncontour` is making some assumption about the contours that wasn't valid for 3.8.0 but is for all other versions of Matplotlib before and after.

You probably don't want to use `geojsoncontour` if it is not actively maintained. Anyway, your workflow is unnecessarily complicated. You should use ContourPy to calculate the contours directly (which is what Matplotlib uses) and hence avoid Matplotlib's subsequent processing of those contours, and these are easily converted to Shapely geometries (see https://contourpy.readthedocs.io/en/latest/user_guide/external/shapely.html) and then you can use `shapely.to_geojson` if required.

**Comment by AugustinMortier** [comment]
Thanks a lot for your ideas! I'll investigate the ContourPy/shapely approach.

**Comment by jklymak** [comment]
I'm going to close this.  I think geojscontour is just confused by the new contour object representation, and needs an update.
