### ISSUE TITLE
[Bug]: Improper behavior of plt.subplots

### ISSUE THREAD

**Issue by aadya940** [matplotlib/matplotlib#27460]
### Bug summary

When I pass 4.0 to nrows, plt.subplots() throws an error but works fine for int(4.0). I believe this can be simply fixed by the adding the following check: `if nrows == int(nrows):`.

### Code for reproduction

```python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_excel("gdp_data.xlsx")
columns = df.columns

fig, ax = plt.subplots(nrows = (len(columns))//1, ncols=(len(columns)/2)//1)

j = 0
for i in range(len(columns)):
    sns.kdeplot(df[columns[i]], ax=ax[i // 2, j])
    j+=1
    if j == 3:
        j = 0 

plt.tight_layout()
plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/77720426/7230394e-6547-4465-af5a-f5952c4a3fc9)

### Expected outcome

Get the plots

### Operating system

Ubuntu

### Matplotlib Version

3.7.3

### Matplotlib Backend

GTK4Agg

### Python version

3.10.12

### Installation

pip

**Comment by rcomer** [comment]
I’m actually confused about how the given example is passing floats.  Since it uses floor divide, shouldn’t that automatically give integers?
