### ISSUE TITLE
[MNT]:  svg font display error in Office such as PowerPoint or Word 

### ISSUE THREAD

**Issue by xt865866473** [matplotlib/matplotlib#27509]
### Summary

When we use the code: **"svg.fonttype": "none"**, then we save the .svg files.  I can open the svg files in Chrome or Edge with right display of fonts. But when I insert svg files into PowerPoint or Word, the display of fonts is not coincide with my settings.  I don't how to solve this issue. Looking forward to your answers!!
![image](https://github.com/matplotlib/matplotlib/assets/102849631/3a073261-037f-4e7d-be88-4915dd97841b)
![image](https://github.com/matplotlib/matplotlib/assets/102849631/59c16063-0f79-41f5-aac4-c0bc8c92d416)

**Comment by ksunden** [comment]
https://matplotlib.org/stable/users/explain/text/fonts.html#fonts-in-svg

There is not a whole lot we can do about that... the tradeoff for using "none" is that it gets treated as text, but you are at the mercy of your svg renderer for the font. I'm a little surprised the size is as affected as it appears to be from your example, but if you want it to definitely look the same in different renderers, you kind of have to use "path" and lose the ability to treat it as text afterwards, unfortunately.

That or ensure that you pick a font that the other programs will render (not sure how to guarantee that)

**Comment by tacaswell** [comment]
I am going to close this issue as behavior we can not do anything about.  As Kyle says, if you use fonts your renderer does not know about then they may use alternate fonts.
