### ISSUE TITLE
Extend set_offsets to 3D for Path3DCollection, Patch3DCollection

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib#27543]
### Summary

When creating 3D animations, it's best practice to update positions for the scatter points rather than re-drawing the whole thing. However, the only way to do this currently is to write to the private attribute `_offsets3d` directly. We should have a public `set_offsets` method to mirror the 2D behavior.

See also: https://stackoverflow.com/questions/41602588/how-to-create-3d-scatter-animations

**Comment by scottshambaugh** [comment]
Note to self, `set_facecolor` seems potentially messed up too

**Comment by timhoffm** [comment]
I imagine there will be quite a number of similar cases around.

This is a major downside of the concept to promote 2D to 3D by subclassing. One would have to make sure that all 2d API and logic is overwritten. But AFAICT this has not been done.

**Comment by scottshambaugh** [comment]
This is a partial duplicate of https://github.com/matplotlib/matplotlib/issues/784

**Comment by spinicist** [comment]
Hello, after spending all morning wondering why my 3D animation with `set_offsets()` wasn't working I finally found this issue. Hence I am a +1 for fixing this please!
