### ISSUE TITLE
[Doc]: inline backend confusion

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#27585]
### Problem

The fact that the inline backend automatically uses `bbox_inches="tight"` is a source of confusion to many users when they find their plots within notebooks do not look the same as those saved with `savefig`.  I haven't found any documentation about this (happy to be pointed to it if it exists).

### Suggested improvement

Should we add an FAQ about this?

**Comment by timhoffm** [comment]
You should also mention that inline uses 72 dpi whereas the matplotlib default is 100 dpi nowadays.

**Comment by jklymak** [comment]
This is discussed here: https://matplotlib.org/devdocs/users/explain/figure/figure_intro.html#notebooks-and-ides but could also be listed in the static backends.

**Comment by rcomer** [comment]
The link that @jklymak provided is enough for me, as I just wanted something to link to when the question comes up.  Should we add something there about the resolution, per @timhoffm's comment?  Otherwise I think this could be closed as not-planned.
