### ISSUE TITLE
[Bug]: Running stubtest locally fails

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#27580]
### Bug summary

Running `python tools/stubtest.py` fails for me locally with

```
% python tools/stubtest.py              
error: matplotlib failed to find stubs
Stub:
MISSING
Runtime:
<module 'matplotlib' from '/Users/dstansby/software/matplotlib/lib/matplotlib/__init__.py'>

note: unused allowlist entry matplotlib.backends.*
note: unused allowlist entry matplotlib.tests.*
note: unused allowlist entry matplotlib.pylab.*
...
(many more note lines below here)
```

I can't work out what I need to do to fix this, and was hoping someone who knew more about the stubs could help! I followed the contributing guidelines to set up a development environment, which is working fine for tests etc.

### Code for reproduction

```python
n/a
```

### Actual outcome

Stub test fails.

### Expected outcome

Stub test runs.

### Operating system

macOS

### Matplotlib Version

3.9.0.dev896+gc1b80c56f7

### Matplotlib Backend

MacOSX

### Python version

3.11.6

### Installation

git checkout

**Comment by ksunden** [comment]
Unfortunately the way meson does editable installs doesn't work with stubtest...

It does work with a normal install.

It also does work if you edit the `.pth` file in site-packages to point to the `lib/matplotlib` folder

**Comment by dstansby** [comment]
I think updating these lines would be good:
https://github.com/matplotlib/matplotlib/blob/e5098e0dc2e5da26f659f44ce758d09c54f6b656/doc/devel/coding_guide.rst?plain=1#L91-L93

If it's not possible to run stubtest on an editable install maybe we should just remove mention of it from this section of the docs?
