### ISSUE TITLE
[Bug]: Markers with numeric name like CARETLEFT cannot be specified using a cycler

### ISSUE THREAD

**Issue by castilma** [matplotlib/matplotlib#27596]
### Bug summary

I want to cycle between multiple markerstyles, including those with a numeric value like CARETRIGHT as documented [here](https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers), but I get an exception if I add one of those.

### Code for reproduction

```python
#!/usr/bin/env python3

from cycler import cycler
import matplotlib.pyplot as plt
import matplotlib.markers as mk

cycle = cycler(marker=["+",mk.CARETRIGHT])

t=[0,1]
y=[5,6]

plt.rc('axes', prop_cycle=cycle)
plt.plot(t,y)
plt.show()
```

### Actual outcome

```
Traceback (most recent call last):
  File "/home/mcd/bugs/bug-cycler.py", line 11, in <module>
    plt.rc('axes', prop_cycle=cycle)
  File "/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 670, in rc
    matplotlib.rc(group, **kwargs)
  File "/usr/lib/python3.11/site-packages/matplotlib/__init__.py", line 1062, in rc
    rcParams[key] = v
    ~~~~~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/__init__.py", line 734, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key axes.prop_cycle: Could not convert 5 to str
```

### Expected outcome

A plot using CARETLEFT as marker.

### Additional information

This seems like it has to do with the fact, that some markers are referred to by number and not by a string like "+".
I don't know whether the problem is in matplotlib, cycler or the combination of both.

### Operating system

Artix Linux

### Matplotlib Version

3.8.1

### Matplotlib Backend

GTK4Agg

### Python version

Python 3.11.6

### Installation

Linux package manager

**Comment by WeatherGod** [comment]
Looks like the validator for the `marker` property is a stringlist
validator, so it is trying to coerce things into strings. Probably should
update the validator.

**Comment by tacaswell** [comment]
More specifically https://github.com/matplotlib/matplotlib/blob/8703dc5682d3655258d8917c1f8ef63cb1576dbb/lib/matplotlib/rcsetup.py#L648  needs to be updated to accept the int(/enum) values.

```python
In [13]: plt.rcParams['lines.marker'] = mk.CARETRIGHT
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 plt.rcParams['lines.marker'] = mk.CARETRIGHT

File /usr/lib/python3.11/site-packages/matplotlib/__init__.py:734, in RcParams.__setitem__(self, key, val)
    732         cval = self.validate[key](val)
    733     except ValueError as ve:
--> 734         raise ValueError(f"Key {key}: {ve}") from None
    735     self._set(key, cval)
    736 except KeyError as err:

ValueError: Key lines.marker: Could not convert 5 to str
```

is a simpler way exercise the same issue.

**Comment by tacaswell** [comment]
Steps:

 - update the marker validator to accept all valid marker specifications (atleast the integers, maybe the path and `Marker` classes as well)
 - add a test
 - add a whats new (if extended past integers)

Good first issue because this is very narrowly scoped, but medium because there is some meta-programming in the validator code.  Some thought will need to be given to writing a validator that works for both "live" objects and for strings coming from reading and .matplotlibrc.

**Comment by WeatherGod** [comment]
The problem might exist in several places such as
https://github.com/matplotlib/matplotlib/blob/8703dc5682d3655258d8917c1f8ef63cb1576dbb/lib/matplotlib/rcsetup.py#L911
