### ISSUE TITLE
[Bug]: `DepecrationWarning` for `datetime.datetime.utcfromtimestamp` with Python >= 3.12

### ISSUE THREAD

**Issue by jeertmans** [matplotlib/matplotlib#27600]
### Bug summary

Hello,

Not really a bug, but I noticed that Python 3.12 introduced a new deprecation warning in the `datetime` module that affects Matplotlib users and dependent packages.

I could not find any related issue, so I wanted to point it out to you.

I actually run my tests with `pytest -Werror` so I had to filter out the warning with:
`ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated:DeprecationWarning` to pass tests on Python 3.12 :-)

### Code for reproduction

```python
NA
```

### Actual outcome

Deprecation warnings are raised.

### Expected outcome

No deprecation warning

### Matplotlib Version

3.8.2

### Python version

3.12

### Installation

pip

**Comment by rcomer** [comment]
From a quick search, there is no direct usage of `utcfromtimestamp` in Matplotlib’s current codebase.  All I found was a pointer that these were removed at #25918, which was before v3.8 was released.

Could you provide a code snippet that reproduces the warning @jeertmans?

**Comment by jeertmans** [comment]
Yes sorry @rcomer, so I created a dummy PR on my repo to show failures in CI (I don't have Python 3.12 locally installed).

Actually, the warning seems to be caused by a third-party module (`dateutil`), and it looks like they have already an issue open for that: https://github.com/dateutil/dateutil/issues/1314.

Should I close this one?

Sorry for not checking that before.

**Comment by rcomer** [comment]
Thanks for checking!  Yes, it looks like there is nothing we can do for this in Matplotlib, so this issue should be closed.
