### ISSUE TITLE
[Bug]: plot_surface x and y axes reverted

### ISSUE THREAD

**Issue by explainerauthors** [matplotlib/matplotlib#27625]
### Bug summary

`ax.set_xlabel("x")` and `ax.set_ylabel("y")` label the x-axis with label "y" and the y-axis with label "x".

### Code for reproduction

```python
from typing import List

import absl.app
import absl.flags
import matplotlib.animation
import matplotlib.pyplot
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

x = [1, 1, 1, 2, 2, 2, 3, 3, 3]
y = [1, 2, 3, 1, 2, 3, 1, 2, 3]
X, Y = np.meshgrid(np.unique(x), np.unique(y))

z = [x[i] * x[i] - y[i] for i in range(len(x))]
Z = np.array(z).reshape(X.shape)

fig = matplotlib.pyplot.figure(figsize=(6, 6))
ax = fig.add_subplot(121, projection="3d")

ax.plot_surface(X, Y, Z, cmap="viridis")
ax.set_xlabel("x")
ax.set_ylabel("y")

fig.savefig("/tmp/a.png")
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/152090505/d0be5e66-da3b-4f0e-9aa4-04f7572bf10d)

### Expected outcome

The highest value of this surface should be where x=3 and y=1 because the above script plots the surface z=x^2-y and both x and y are positive. If we switch the x and y labels in the above figuer, everything looks good then.

### Operating system

Ubuntu 22.04

### Matplotlib Version

3.8.2

### Matplotlib Backend

agg

### Python version

3.10.12

### Installation

pip

**Comment by ksunden** [comment]
Your meshgrid/`np.unique` line is what is reversing that from what you expect, so `X` and `x` are different when flattened.

```python
>>> list(X.flat)
[1, 2, 3, 1, 2, 3, 1, 2, 3]
>>> x
[1, 1, 1, 2, 2, 2, 3, 3, 3]
>>> list(Y.flat)
[1, 1, 1, 2, 2, 2, 3, 3, 3]
>>> y
[1, 2, 3, 1, 2, 3, 1, 2, 3]
```

This is because `np.unique(x) == np.unique(y) == [1, 2, 3]`

But the original order is used in computing Z, but not for plotting.
