### ISSUE TITLE
Doc: Add passing args to Animation guide

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#27621]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/animations/animations.html#animations

### Problem
Superceded by #27687

Based on #27620, this is a general enough usage case that it'd be worth adding a section. 

### Suggested improvement

Add a subsection to the FuncAnimation section  and use that section to explain how to pass in arguments and show a small example. 

See func parameter for details: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.animation.FuncAnimation.html#matplotlib.animation.FuncAnimation

**Comment by Ahmedniz1** [comment]
Is this request still available? I'm trying to work on it but I feel like the description is clear enough. As an example is attached right below the funcanimation heading describing how to create animation using this class.

**Comment by vamshipy** [comment]
working on this..

**Comment by MostafaNouh0011** [comment]
Hello,
I am interested in contributing to this issue and would like to inquire if anyone is currently working on it.
