### ISSUE TITLE
animation save gets error writing to file with ffmpeg and ogv (or ogg)

### ISSUE THREAD

**Issue by moorepants** [matplotlib/matplotlib#2764]
Using: http://matplotlib.org/1.2.1/examples/animation/double_pendulum_animated.html

With these added lines at the top:

```
from matplotlib import __version__
print("matplotlib version: {}".format(__version__))
import os
os.system('ffmpeg')
```

And no `clear_temp` kwarg in the save method call. I get this for trying to make a `double_pendulum.ogv` file.

```
Python 2.7.5+ (default, Sep 19 2013, 13:48:49) 
Type "copyright", "credits" or "license" for more information.

IPython 1.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: run double_pendulum_animated.py
matplotlib version: 1.2.1
ffmpeg version 0.8.9-6:0.8.9-0ubuntu0.13.10.1, Copyright (c) 2000-2013 the Libav developers
  built on Nov  9 2013 19:09:46 with gcc 4.8.1
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/moorepants/Desktop/double_pendulum_animated.py in <module>()
     90     interval=25, blit=True, init_func=init)
     91 
---> 92 ani.save('double_pendulum.ogv', fps=15)
     93 plt.show()

/usr/local/lib/python2.7/dist-packages/matplotlib/animation.pyc in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim)
    613                     #TODO: Need to see if turning off blit is really necessary
    614                     anim._draw_next_frame(d, blit=False)
--> 615                 writer.grab_frame()
    616 
    617         # Reconnect signal for first draw if necessary

/usr/local/lib/python2.7/dist-packages/matplotlib/animation.pyc in grab_frame(self)
    197             # frame format and dpi.
    198             self.fig.savefig(self._frame_sink(), format=self.frame_format,
--> 199                 dpi=self.dpi)
    200         except RuntimeError:
    201             out, err = self._proc.communicate()

/usr/local/lib/python2.7/dist-packages/matplotlib/figure.pyc in savefig(self, *args, **kwargs)
   1368             kwargs.setdefault('edgecolor', rcParams['savefig.edgecolor'])
   1369 
-> 1370         self.canvas.print_figure(*args, **kwargs)
   1371 
   1372         if transparent:

/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.pyc in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2094                 orientation=orientation,
   2095                 bbox_inches_restore=_bbox_inches_restore,
-> 2096                 **kwargs)
   2097         finally:
   2098             if bbox_inches and restore_bbox:

/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.pyc in print_raw(self, filename_or_obj, *args, **kwargs)
    482             close = False
    483         try:
--> 484             renderer._renderer.write_rgba(filename_or_obj)
    485         finally:
    486             if close:

RuntimeError: Error writing to file

```

**Comment by mattjj** [comment]
I got the same error (also on mpl 1.4.2, Python 2.7.9, OS X, using miniconda with everything updated).

**Comment by tacaswell** [comment]
@dopplershift Do any of these tracebacks make sense to you?

Something is clearly getting messed up with the pipe.

Other things that look troubling is that `setup` discards `*args` unused...

**Comment by mattjj** [comment]
This might not be helpful, but I put an ipdb session right before the call to write_rgba and it looks like the file object is fine:

```
ipdb> print filename_or_obj
<open file '<fdopen>', mode 'wb' at 0x10cdc0300>
ipdb> renderer._renderer.write_rgba(filename_or_obj)
*** RuntimeError: Error writing to file
```

Actually, it looks like my ffmpeg might be broken... I'll reinstall it.

**Comment by mattjj** [comment]
Reinstalling ffmpeg (using MacPorts) totally fixed it for me. I noticed it was busted because I tried `ffmpeg -v` in the shell, which I probably should have done earlier. I just upgraded to Yosemite, so maybe I had an old version or something.

Sorry about that!

**Comment by dopplershift** [comment]
Glad you got it working. Please re-open if you have more problems.

**Comment by cancan101** [comment]
I am still seeing this issue (on Linux). As pointed out in https://github.com/matplotlib/matplotlib/issues/2764#issuecomment-47191449, I think the issue has to do with some DPIs not working (although the acceptable values I get are different).

**Comment by dopplershift** [comment]
Does it work if you change the writer creation line to:
```python
writer = FFMpegWriter(fps=15, metadata=metadata, codec='libtheora')
```
?

**Comment by ylockerman** [comment]
I have had the same error reported. From what I can tell matplotlib starts a ffmpeg process and then writes to it's stdin through a file interface.  What it seems like is happening is that ffmpeg sees a frame that is invalid according to the parameters given when it was called. At that time ffmpeg quits. However, the python code dose not seem to know until it tries to write to ffmpeg on the **next** frame. Thus the crash. This can happen for a large number of reasons, and I would recommend matplotlib include some way to figure out why it happened (if possible). 


It seems like it was caused (for me) by setting the bitrate too high. If you want to get some more debugging information ffmpeg adding

```python
matplotlib.rcParams['animation.ffmpeg_args'] = '-report'
```

which will cause ffmpeg to create a log file each time it is run. I found the maximum bitrate of my source images and setting the param:

```python
matplotlib.rcParams['animation.bitrate'] = 2000
```


I hope this helps. (I am using '1.4.3' on windows with WinPython)
