### ISSUE TITLE
[Doc]: `Axes.inset_axes` is still experimental

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#27648]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.inset_axes.html#matplotlib.axes.Axes.inset_axes

### Problem

I just noticed that `Axes.inset_axes` is still marked as experimental.  It seems pretty well established to me, even recommended as a method for [placing colorbars](https://matplotlib.org/stable/users/explain/axes/colorbar_placement.html#using-inset-axes).

### Suggested improvement

Is it time to remove the "experimental" warning?

**Comment by Snehaaa18** [comment]
Please assign this issue to me

**Comment by rcomer** [comment]
Hello @Snehaaa18, thank you for your enthusiasm, but we do not assign issues.  Also I would like to wait for other maintainers to comment whether it should be done before anyone makes the change.

**Comment by timhoffm** [comment]
I vote for dropping the experimental flag. The API is consistent and simple enough. And it's been around long enough that we can expect reasonable adoption so that any incompatible changes should better run through a deprecation cycle, whether we've still formally marked it as experimental or not.

**Comment by jklymak** [comment]
There was talk of adding the ordinal locations to inset_axes. However I'm 99% certain that can be done in a backwards compatible way should someone want to do that.

**Comment by timhoffm** [comment]
> There was talk of adding the ordinal locations to inset_axes. However I'm 99% certain that can be done in a backwards compatible way should someone want to do that.

Yes it could. But I tend to not do it. You either don't have control over the size and margins of the inset, or the API get's really complex. I think keeping it to the an analogous API as `Figure.add_axes()` is good enough.

**Comment by rcomer** [comment]
I think the work here is:

* Remove the experimental note from the docstring.
* Add a what’s new entry that the method is no longer experimental (it may help to look at the similar entry for `subplot_mosaic` at #24891).

**Comment by ShivamPathak99** [comment]
Working on it.
