### ISSUE TITLE
[Doc]: Confusing page on color changes

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#27673]
### Documentation Link

https://matplotlib.org/devdocs/devel/color_changes.html

### Problem

This page is a historic memo rather than documentation. But it doesn't say so.

### Suggested improvement

IMHO this can be deleted. If somebody thinks, there is still relevant information, that's worth documenting, this needs a rework and an initial admonition for context and scope.

**Comment by timhoffm** [comment]
*If* this should be kept we could also dump it into #14331 or create an issue link that in #14331.

But I'm still waiting for somebody to speak up for it.

**Comment by jklymak** [comment]
I'd get rid of it.  Historically it exists in the old version of the docs, and I don't see what use it is.

**Comment by timhoffm** [comment]
Ping @tacaswell do you have an opinion?
