### ISSUE TITLE
[Bug]: fig.suptitle unaligns Axes.inset_axes.

### ISSUE THREAD

**Issue by wandwan** [matplotlib/matplotlib#27712]
### Bug summary

fig.suptitle break Axes.inset_axes in that width height and x and y locations are incorrect.

### Code for reproduction

```python
def visualize(albedo, normals, horn_depth):
    # Stride in the plot, you may want to adjust it to different images
    stride = 15

    # Create a figure with 2x2 subplots
    fig = plt.figure(figsize=(15, 15))
    fig.suptitle("Albedo, normals and depth", fontsize=16) #Comment me out to fix!

    # showing albedo map
    ax1 = fig.add_subplot(2, 2, 1)
    albedo_max = albedo.max()
    albedo = albedo / albedo_max
    ax1.imshow(albedo, cmap="cool")
    ax1.set_title("Albedo Map")

    # showing normals as three separate channels
    ax2 = fig.add_subplot(2, 2, 2)
    ax2_1 = ax2.inset_axes([0, 0, .5, 0.5])
    ax2_1.axis('off')
    ax2_1.imshow(normals[..., 0], cmap='Reds')
    ax2_2 = ax2.inset_axes([0, 0.5, .5, 0.5])
    ax2_2.axis('off')
    ax2_2.imshow(normals[..., 1], cmap='Greens')
    ax2_3 = ax2.inset_axes([.5, 0.5, .5, 0.5])
    ax2_3.axis('off')
    ax2_3.imshow(normals[..., 2], cmap='Blues')
    ax2.set_title("Normals as three separate channels")

    # showing normals as quiver
    X, Y = np.meshgrid(np.arange(0, np.shape(normals)[0], stride),
                       np.arange(0, np.shape(normals)[1], stride))
    Z = horn_depth[::stride, ::stride]
    NX = normals[..., 0][::stride, ::stride]
    NY = normals[..., 1][::stride, ::stride]
    NZ = normals[..., 2][::stride, ::stride]
    ax3 = fig.add_subplot(2, 2, 3, projection='3d')
    ax3.quiver(X, Y, Z, NX, NY, NZ, length=10, color='#8cc4ff', linewidth=3)
    ax3.set_title("Needle Map")

    # plotting wireframe depth map
    H = horn_depth[::stride, ::stride]
    ax4 = fig.add_subplot(2, 2, 4, projection='3d')
    ax4.plot_surface(X, Y, H, cmap='cool', edgecolor='none')
    ax4.set_title("Wireframe of depth map")

    # Adjust layout
    plt.tight_layout()
    plt.show()
pickle_in = open("synthetic_data_horn.pickle", "rb")
albedo, normals, horn_depth = pickle.load(pickle_in)
visualize(albedo, normals, horn_depth)
```

### Actual outcome

Broken version (with title)
![image](https://github.com/matplotlib/matplotlib/assets/34516018/6c389f67-e415-4695-9f53-151184092c2a)

### Expected outcome

Fixed:
![image](https://github.com/matplotlib/matplotlib/assets/34516018/de69cc9d-0c52-487d-98f7-aa329c1031cd)

### Additional information

Here is the zipped pickle file for repro:
[pickle.zip](https://github.com/matplotlib/matplotlib/files/14074263/pickle.zip)

### Operating system

OS/X

### Matplotlib Version

3.8.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.11.7

### Jupyter version

7.0.6

### Installation

pip

**Comment by rcomer** [comment]
I suspect this is because `tight_layout` changed the heights of the axes to make space for the title.  So the top right main axes is no longer square.  What happens if you add `ax2.set_apect("equal")`?

**Comment by jklymak** [comment]
As another hint, I'd not use inset_axes here, but rather four calls to `ax.imshow`, with the `extent` keyword arg set to put the image in the appropriate quadrant.  eg
```
ax2.imshow(normals[..., 0], cmap='Reds', extent=[0, 0, 0.5, 0.5])
ax2.imshow(normals[..., 1], cmap='Reds', extent=[0, 0.5, 0.5, 1])
...
```

But otherwise I agree w/ @rcomer that matplotlib is behaving as expected.

**Comment by rcomer** [comment]
I’m going to close this because I do not think it’s a bug in Matplotlib.  But @wandwan you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.
