### ISSUE TITLE
[Doc]: Text in the colormap normalization gallery doesn't match the code

### ISSUE THREAD

**Issue by igurin-invn** [matplotlib/matplotlib#27727]
### Documentation Link

https://matplotlib.org/stable/gallery/images_contours_and_fields/colormap_normalizations.html#sphx-glr-gallery-images-contours-and-fields-colormap-normalizations-py

### Problem

> SymLogNorm: two humps, one negative and one positive, The positive with 5-times the amplitude. Linearly, you cannot see detail in the negative hump. Here we logarithmically scale the positive and negative data separately.
1. The equation `Z = 5 * np.exp(-X**2 - Y**2)` describes a simple Gaussian bell curve in two dimensions. There's no second hump.
2. There are no negative data. A Gaussian is always positive.

> Custom Norm: An example with a customized normalization. This one uses the example above, and normalizes the negative data differently from the positive.
1. The equation is not the same as the previous one! This one does have the two humps promised above, but they have the same amplitude.
2. The negative and positive data are normalized symmetrically. The top and bottom plots look almost the same.

### Suggested improvement

It's a gallery example, so you can do whatever you want, just please make it consistent.

**Comment by QuLogic** [comment]
It looks like this was probably accidentally changed with https://github.com/matplotlib/matplotlib/pull/9151/commits/32a2f7931b68e100898eb6c7c2ece2dc3590af82
