### ISSUE TITLE
[Bug]: Bus error in font_manager when using Matplotlib on GitHub's new free tier of hosted Apple Silicon runners for GitHub Actions

### ISSUE THREAD

**Issue by lpsinger** [matplotlib/matplotlib#27724]
### Bug summary

I am encountering a bus error in `addfont` when I am running unit tests for a package that uses matplotlib ([healpy](https://github.com/healpy/healpy)) under cibuildwheel on [GitHub's new free Apple Silicon runners](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/). I don't have a straightforward way of reproducing this outside of GitHub Actions.

### Code for reproduction

See https://github.com/healpy/healpy/pull/896

### Actual outcome

Font loading fails without crashing.

### Expected outcome

The most relevant part of the log output (https://github.com/healpy/healpy/actions/runs/7721358991/job/21047787718?pr=896) is:

```
Fatal Python error: Bus error
  Thread 0x000000016ea4f000 (most recent call first):
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 316 in wait
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 581 in wait
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1304 in run
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980 in _bootstrap_inner
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 937 in _bootstrap
  Current thread 0x00000001e4229000 (most recent call first):
    File "/private/var/folders/1k/qq3pcbf12vb6vyblh81736p40000gn/T/cibw-run-krc4imxq/cp39-macosx_arm64/venv-test/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1076 in addfont
    File "/private/var/folders/1k/qq3pcbf12vb6vyblh81736p40000gn/T/cibw-run-krc4imxq/cp39-macosx_arm64/venv-test/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1043 in __init__
    File "/private/var/folders/1k/qq3pcbf12vb6vyblh81736p40000gn/T/cibw-run-krc4imxq/cp39-macosx_arm64/venv-test/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1576 in _load_fontmanager
    File "/private/var/folders/1k/qq3pcbf12vb6vyblh81736p40000gn/T/cibw-run-krc4imxq/cp39-macosx_arm64/venv-test/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1582 in <module>
```

### Operating system

macOS

### Matplotlib Version

3.8.2

### Python version

3.9

### Installation

pip

**Comment by dstansby** [comment]
Thanks for the report. Do you know if this happens on other versions of Python, or just Python 3.9?

**Comment by QuLogic** [comment]
When setting up #27723, I wasn't able to install 3.9 directly. Does it actually make sense to produce wheels for 3.9 on arm64? I don't think there is a native build.

**Comment by QuLogic** [comment]
Hmm, maybe there were native builds, at least by the time 3.9.5 rolled out. I guess Azure didn't bother to provide them at the time, and hasn't had to add them/

**Comment by lpsinger** [comment]
> When setting up #27723, I wasn't able to install 3.9 directly. Does it actually make sense to produce wheels for 3.9 on arm64? I don't think there is a native build.

Yes, it does. cibuildwheel installs the universal2 build of Python 3.9 from python.org. I successfully built wheels for Python 3.9 on macOS arm64 in https://github.com/nasa/radbelt/pull/69.

**Comment by lpsinger** [comment]
> Thanks for the report. Do you know if this happens on other versions of Python, or just Python 3.9?

I just tried Python 3.10. It fails with the same error.

**Comment by ksunden** [comment]
I do not see this locally on my M2 Mac, so it looks like it may be specific to the cibw context? (Not really sure, but hard to narrow in on)

I tried with a few combinations of python (mostly 3.10) installs (e.g. pyenv installed (which compiles from tarballs) and python.org universal2 installer), tried just running the import line which failed from a repl and running healpy's `pytest`) I did not try running full cibw locally, which _could_ have an effect I guess...

It is happening at creating an `FT2Font` object (Which is a C-extension implemented object) So not implausible that there is something odd happening there... but its also not _completely_ broken, so not sure what it would be...

**Comment by QuLogic** [comment]
Could [this be related](https://github.com/healpy/healpy/blob/f0f1a78ed2822c8a67aeef18cb51a1a3b7b3df5c/pyproject.toml#L52-L54)?
```
[tool.cibuildwheel.macos]
before-all = "brew install automake"
environment = {"CC" = "gcc-12", "CXX" = "g++-12"}
```
Do you not want to be compiling with macOS's compilers?

**Comment by lpsinger** [comment]
> Could [this be related](https://github.com/healpy/healpy/blob/f0f1a78ed2822c8a67aeef18cb51a1a3b7b3df5c/pyproject.toml#L52-L54)?
> 
> ```
> [tool.cibuildwheel.macos]
> before-all = "brew install automake"
> environment = {"CC" = "gcc-12", "CXX" = "g++-12"}
> ```
> 
> Do you not want to be compiling with macOS's compilers?

No, we want to compile with gcc, because we use OpenMP, which as I recollect is not supported by Apple's compilers.

**Comment by QuLogic** [comment]
Could it be setting some bad threading/forking model?

**Comment by lpsinger** [comment]
Setting the environment variable `MPLBACKEND=agg` worked around this.

**Comment by tacaswell** [comment]
> Setting the environment variable MPLBACKEND=agg worked around this.

Ah, that suggests that this is somehow related to trying to use GUI tools in a headless context.

**Comment by lpsinger** [comment]
I take it back, it had nothing to do with `MPLBACKEND`; what fixed the build was not using Homebrew's gcc-12 and g++-12. (When I set `MPLBACKEND` using `CIBW_ENVIRONMENT` it erased the `CC` and `CXX` values from my pyproject.toml file.)

**Comment by tacaswell** [comment]
I'm going to close this here as I don't think there is anything we can do to solve this on our side.
