### ISSUE TITLE
[Bug]: Problems with filled contours using Lambert Conformal projections.

### ISSUE THREAD

**Issue by icbeckley** [matplotlib/matplotlib#27739]
### Bug summary

When using ccrs.LambertConformal, contourf() fails while contour succeeds. In my current testing environment I receive an error, but in other operational environments it will fail without notice. This issue does not seem to arise when using other projections.

### Code for reproduction

```python
import xarray as xr
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt

file = 'JRA_vorticity_sample.nc'
ds = xr.open_mfdataset(file, engine = 'netcdf4')

## Grid
lat = ds.latitude
lon = ds.longitude

## Extent
lat_min = 10
lat_max = 60
lon_min = (360 -70 - 40)
lon_max = (360 -70 + 40)
clon = (lon_min + lon_max)/2
extent = np.array([lon_min, lon_max, lat_min, lat_max])

## Projections
proj_map = ccrs.LambertConformal(central_longitude = clon, central_latitude = 35)
#proj_map = ccrs.Mercator(central_longitude = clon)
#proj_map = ccrs.NorthPolarStereo(central_longitude = clon)
proj_data = ccrs.PlateCarree()

## Contour Levels
clev_zeta = np.arange(3, 27, 3)

## Colormaps
cmap_zeta = plt.cm.YlOrRd

fig = plt.figure(figsize = (12,9))
ax = plt.axes(projection = proj_map)
z_order = np.arange(0,10,1)

## Extent
ax.set_extent(extent, crs = proj_data)

## Plot relative vorticity
ax.contourf(lon, lat, ds['zeta_g']*1e5, clev_zeta, transform = proj_data, cmap = cmap_zeta, zorder = z_order[3], extend = 'max')
ax.contour(lon, lat, ds['zeta_g']*1e5, clev_zeta, transform = proj_data, cmap = cmap_zeta, zorder = z_order[3], extend = 'max')
```

### Actual outcome

ValueError                                Traceback (most recent call last)
Cell In[20], line 9
      6 ax.set_extent(extent, crs = proj_data)
      8 ## Plot relative vorticity
----> 9 ax.contourf(lon, lat, ds['zeta_g']*1e5, clev_zeta, transform = proj_data, cmap = cmap_zeta, zorder = z_order[3], extend = 'max')
     10 ax.contour(lon, lat, ds['zeta_g']*1e5, clev_zeta, transform = proj_data, cmap = cmap_zeta, zorder = z_order[3], extend = 'max')

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py:315, in _add_transform.<locals>.wrapper(self, *args, **kwargs)
    310     raise ValueError(f'Invalid transform: Spherical {func.__name__} '
    311                      'is not supported - consider using '
    312                      'PlateCarree/RotatedPole.')
    314 kwargs['transform'] = transform
--> 315 return func(self, *args, **kwargs)

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py:359, in _add_transform_first.<locals>.wrapper(self, *args, **kwargs)
    357     # Use the new points as the input arguments
    358     args = (x, y, z) + args[3:]
--> 359 return func(self, *args, **kwargs)

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py:1666, in GeoAxes.contourf(self, *args, **kwargs)
   1664         self.update_datalim(extent.get_points())
   1665 else:
-> 1666     self.update_datalim(result.get_datalim(self.transData))
   1668 self.autoscale_view()
   1670 # Re-cast the contour as a GeoContourSet.

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/matplotlib/collections.py:267, in Collection.get_datalim(self, transData)
    264     return transforms.Bbox.null()
    266 if not transform.is_affine:
--> 267     paths = [transform.transform_path_non_affine(p) for p in paths]
    268     # Don't convert transform to transform.get_affine() here because
    269     # we may have transform.contains_branch(transData) but not
    270     # transforms.get_affine().contains_branch(transData).  But later,
    271     # be careful to only apply the affine part that remains.
    273 offsets = self.get_offsets()

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/matplotlib/transforms.py:2426, in CompositeGenericTransform.transform_path_non_affine(self, path)
   2424     return path
   2425 elif not self._a.is_affine and self._b.is_affine:
-> 2426     return self._a.transform_path_non_affine(path)
   2427 else:
   2428     return self._b.transform_path_non_affine(
   2429                             self._a.transform_path(path))

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py:186, in InterProjectionTransform.transform_path_non_affine(self, src_path)
    182 geoms = cpatch.path_to_geos(src_path,
    183                             getattr(self, 'force_path_ccw', False))
    185 for geom in geoms:
--> 186     proj_geom = self.target_projection.project_geometry(
    187         geom, self.source_projection)
    188     transformed_geoms.append(proj_geom)
    190 if not transformed_geoms:

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/crs.py:817, in Projection.project_geometry(self, geometry, src_crs)
    815 if not method_name:
    816     raise ValueError(f'Unsupported geometry type {geom_type!r}')
--> 817 return getattr(self, method_name)(geometry, src_crs)

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/crs.py:972, in Projection._project_polygon(self, polygon, src_crs)
    968     rings.extend(self._attach_lines_to_boundary(multi_lines, is_ccw))
    970 # Resolve all the inside vs. outside rings, and convert to the
    971 # final MultiPolygon.
--> 972 return self._rings_to_multi_polygon(rings, is_ccw)

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/cartopy/crs.py:1233, in Projection._rings_to_multi_polygon(self, rings, is_ccw)
   1230                 polygon_bits.append(polygon)
   1232 if polygon_bits:
-> 1233     multi_poly = sgeom.MultiPolygon(polygon_bits)
   1234 else:
   1235     multi_poly = sgeom.MultiPolygon()

File ~/miniconda3/envs/mpl_bug_tester/lib/python3.12/site-packages/shapely/geometry/multipolygon.py:73, in MultiPolygon.__new__(self, polygons)
     70 # This function does not accept sequences of MultiPolygons: there is
     71 # no implicit flattening.
     72 if isinstance(polygons[0], MultiPolygon):
---> 73     raise ValueError("Sequences of multi-polygons are not valid arguments")
     75 subs = []
     76 for i in range(L):

ValueError: Sequences of multi-polygons are not valid arguments

### Expected outcome

Using the provided code, and changing proj_map to the Mercator projection...
![Screenshot 2024-02-02 at 3 56 17 PM](https://github.com/matplotlib/matplotlib/assets/60024009/cc6e163f-c563-4578-b45a-7f27af268b63)

### Additional information

Data: 1.25 degree, isobaric Japanese Reanalysis Data. The example data can be obtained [here. ](https://drive.google.com/file/d/1MtZQPsMEGPiQIBsyke_UD7H8BmBFcriP/view?usp=sharing)

Environment: A .yml file for this environment can be found [here.](https://drive.google.com/file/d/1b24f2z2wRlAXePZFtk1GqJgyLHyZKhPN/view?usp=sharing)

Observations: I run operational scripts using the Lambert Conformal projection and have not had problems with this in the past. Recently I have switched machines and re-built most of my enviornments. Been having a lot of issues, especially with that projection. Sometimes it will error, other times it will provide bad output.

### Operating system

Rocky Linux release 8.9 (Green Obsidian)

### Matplotlib Version

3.8.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.12.1

### Jupyter version

4.0.5

### Installation

conda

**Comment by rcomer** [comment]
This seems similar to https://github.com/SciTools/cartopy/issues/2312.  At least, the error message is the same.  I think this is Cartopy’s problem rather than Matplotlib’s, so  I’m going to close this here.  @icbeckley please add any information you think is useful to the Cartopy issue.
