### ISSUE TITLE
[Bug]: plot_trisurf fails 

### ISSUE THREAD

**Issue by InFlyingSpaghettiMonsterWeTrust** [matplotlib/matplotlib#27735]
### Bug summary

plot_trisurf fails to apply on some points even if these points represents a plan.
For example, these 3 points : 
point1 = [0, 0, 23.27113871]
point2 = [0, 0, 0]
point3 = [0, 11.9578882, 0]
We put them in an array :
test_point = numpy.zeros((3,3))
test_point[0, :] = test_point1
test_point[1, :] = test_point2
test_point[2, :] = test_point3
The command :
surface = axes.plot_trisurf(test_point[:, 0], test_point[:, 1], test_point[:, 2])
send us an errror.
If we modify point1 to be point1 = [0.0001, 0, 23.27113871], we do not get error anymore.
It seems that plot_trisurf does not work when the plan to display is one of the principal plans defined by the equation x=0, or y=0, or z=0.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

test_point1 = [0, 0, 23.27113871]
test_point2 = [0, 0, 0]
test_point3 = [0, 11.95788882, 0]

test_point = np.zeros((3,3))
test_point[0,:] = test_point1
test_point[1,:] = test_point2
test_point[2,:] = test_point3

axes = plt.figure().add_subplot(projection="3d")
surface = axes.plot_trisurf(test_point[:,0], test_point[:,1], test_point[:,2])
plt.show()
```

### Actual outcome

According to my input I can get 2 differents errors.
The first one :

File ".../fct_util/optimisation_enveloppe.py", line 529, in <module>
    enveloppe_kd_in_Nd_after_ReLU()
  File ".../fct_util/optimisation_enveloppe.py", line 484, in enveloppe_kd_in_Nd_after_ReLU
    surface = axes.plot_trisurf(test_point[:,0], test_point[:,1], test_point[:,2])
  File "/home/****/anaconda3/envs/****/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2003, in plot_trisurf
    Triangulation.get_from_args_and_kwargs(*args, **kwargs)
  File "/home/****l/anaconda3/envs/****/lib/python3.10/site-packages/matplotlib/tri/_triangulation.py", line 167, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "/home/****/anaconda3/envs/****/lib/python3.10/site-packages/matplotlib/tri/_triangulation.py", line 60, in __init__
    self.triangles, self._neighbors = _qhull.delaunay(x, y, sys.flags.verbose)
ValueError: x and y arrays must consist of at least 3 unique points

The second error :

File "...fct_util/optimisation_enveloppe.py", line 502, in enveloppe_kd_in_Nd_after_ReLU
    surface = axes.plot_trisurf(Sommets_intermediaire[simpl,0], Sommets_intermediaire[simpl,1], Sommets_intermediaire[simpl,2], alpha=0.2)
  File "/home/****/anaconda3/envs/****/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2003, in plot_trisurf
    Triangulation.get_from_args_and_kwargs(*args, **kwargs)
  File "/home/****/anaconda3/envs/****/lib/python3.10/site-packages/matplotlib/tri/_triangulation.py", line 167, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "/home/****/anaconda3/envs/****/lib/python3.10/site-packages/matplotlib/tri/_triangulation.py", line 60, in __init__
    self.triangles, self._neighbors = _qhull.delaunay(x, y, sys.flags.verbose)
RuntimeError: Error in qhull Delaunay triangulation calculation: singular input data (exitcode=2); use python verbose option (-v) to see original qhull error.

### Expected outcome

A figure of the 3 points with the plan described by these 3 points. It should look like the following figure :
![Screenshot from 2024-02-02 11-27-08](https://github.com/matplotlib/matplotlib/assets/158564998/0ac33eb1-e8ed-4f5e-b5f5-3926ffa5b11a)

### Matplotlib Version

3.3.2

### Installation

None

**Comment by ianthomas23** [comment]
If you don't specify a triangulation, Matplotlib calculates one for you using a Delaunay triangulation in the x-y plane, ignoring the z coordinates. Two of your three points have identical (x, y) coordinates, so you only have 2 unique points which is not enough for a triangulation of even a single triangle. The error message tells you this:
```
self.triangles, self._neighbors = _qhull.delaunay(x, y, sys.flags.verbose)
ValueError: x and y arrays must consist of at least 3 unique points
```
If you don't want a Delaunay triangulation calculated for you in the x-y plane then you need to pass in your own triangulation. Something like
```python
triangles = [[0, 1, 2]]  # Triangulation of a single triangle
ax.plot_trisurf(x, y, triangles, z)
```

**Comment by InFlyingSpaghettiMonsterWeTrust** [comment]
Thank you for your fast answer.

**Comment by dstansby** [comment]
This seems resolved/explained, so I'll close.
