### ISSUE TITLE
[Bug]: imshow set_data

### ISSUE THREAD

**Issue by rougier** [matplotlib/matplotlib#27737]
### Bug summary

From the example code below, I cannot set data *after* image creation. Is that expected behavior ? How do I force image updating with the new data?

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.subplot(1,1,1)
texture = (np.indices((256,256)) // 16).sum(axis=0) % 2

# Version 1: works
# image = ax.imshow(texture, extent=[0,1,0,1])

# Version 2: not working
image = ax.imshow([[0]], extent=[0,1,0,1])
image.set_data(texture)

plt.show()
```

### Actual outcome

Blank image.

### Expected outcome

Checkerboard image.

### Operating system

OS/X

### Matplotlib Version

3.8.0

### Matplotlib Backend

MacOSX

### Python version

3.11.7

### Installation

pip

**Comment by rougier** [comment]
Missing ```image.set_clim(vmin=0, vmax=1)```

**Comment by tacaswell** [comment]
To explain what is going on a bit for those reading along at home, `image = ax.imshow([[0]], extent=[0,1,0,1])` is triggering the auto-norm logic with a singular value, picking limits of [0, 0] (consistent with the input data) and then when the data is re-set we do not automatically rescale the norm.

In addition to using `set_clim` after the fact you could also pass `vmin`/`vmax` or `norm` to the initial imshow call to explicitly set the limits (and let us auto-limit at all).
