### ISSUE TITLE
Getting error as "No module named 'matplotlib.artist'" while importing seaborn

### ISSUE THREAD

**Issue by NaveenChoudharyy** [matplotlib/matplotlib#27749]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 import seaborn as sns

File ~\anaconda3\lib\site-packages\seaborn\__init__.py:2
      1 # Import seaborn objects
----> 2 from .rcmod import *  # noqa: F401,F403
      3 from .utils import *  # noqa: F401,F403
      4 from .palettes import *  # noqa: F401,F403

File ~\anaconda3\lib\site-packages\seaborn\rcmod.py:5
      3 import matplotlib as mpl
      4 from cycler import cycler
----> 5 from . import palettes
      8 __all__ = ["set_theme", "set", "reset_defaults", "reset_orig",
      9            "axes_style", "set_style", "plotting_context", "set_context",
     10            "set_palette"]
     13 _style_keys = [
     14 
     15     "axes.facecolor",
   (...)
     50 
     51 ]

File ~\anaconda3\lib\site-packages\seaborn\palettes.py:9
      5 import matplotlib as mpl
      7 from .external import husl
----> 9 from .utils import desaturate, get_color_cycle
     10 from .colors import xkcd_rgb, crayons
     11 from ._compat import get_colormap

File ~\anaconda3\lib\site-packages\seaborn\utils.py:14
     12 import matplotlib as mpl
     13 from matplotlib.colors import to_rgb
---> 14 import matplotlib.pyplot as plt
     15 from matplotlib.cbook import normalize_kwargs
     17 from seaborn._core.typing import deprecated

File ~\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py:52
     50 from cycler import cycler
     51 import matplotlib
---> 52 import matplotlib.colorbar
     53 import matplotlib.image
     54 from matplotlib import _api

File ~\AppData\Roaming\Python\Python310\site-packages\matplotlib\colorbar.py:19
     16 import numpy as np
     18 import matplotlib as mpl
---> 19 from matplotlib import _api, cbook, collections, cm, colors, contour, ticker
     20 import matplotlib.artist as martist
     21 import matplotlib.patches as mpatches

File ~\AppData\Roaming\Python\Python310\site-packages\matplotlib\collections.py:20
     17 import numpy as np
     19 import matplotlib as mpl
---> 20 from . import (_api, _path, artist, cbook, cm, colors as mcolors, _docstring,
     21                hatch as mhatch, lines as mlines, path as mpath, transforms)
     22 from ._enums import JoinStyle, CapStyle
     25 # "color" is excluded; it is a compound setter, and its docstring differs
     26 # in LineCollection.

File ~\AppData\Roaming\Python\Python310\site-packages\matplotlib\lines.py:14
     12 import matplotlib as mpl
     13 from . import _api, cbook, colors as mcolors, _docstring
---> 14 from .artist import Artist, allow_rasterization
     15 from .cbook import (
     16     _to_unmasked_float_array, ls_mapper, ls_mapper_r, STEP_LOOKUP_MAP)
     17 from .markers import MarkerStyle

ModuleNotFoundError: No module named 'matplotlib.artist'

**Comment by timhoffm** [comment]
This is most likely not a bug in matplotlib.

You Python configuration is somehow mixed up. You're taking packages from two installations (~\anaconda3\lib\site-packages and ~\AppData\Roaming\Python\Python310\site-packages).

Please reinstall Python or fix your Python configuration manually. This is not something we can help you with. You may report back if the problem perstists when everything comes from one Python environement.
