### ISSUE TITLE
[MNT]: `_ImageBase.draw` and `Axis.draw` args and kwargs

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#27745]
### Summary

The `draw` methods of [_ImageBase](https://github.com/matplotlib/matplotlib/blob/525349b33bd40108f1f9f830323b3270f12dd72f/lib/matplotlib/image.py#L630) and [Axis](https://github.com/matplotlib/matplotlib/blob/525349b33bd40108f1f9f830323b3270f12dd72f/lib/matplotlib/axis.py#L1377) take `*args` and `**kwargs` but do not do anything with them.  The [Ribbon Box](https://matplotlib.org/stable/gallery/misc/demo_ribbon_box.html) example has an artist that inherits from `AxesImage` and also passes `*args` and `**kwargs` through `draw`.

### Proposed fix

Based on #16022 my guess is that `*args` and `**kwargs` should be removed from the signatures, though I don't know much about when and how `draw` gets called.  If they should be removed, do we need a deprecation period?

**Comment by tacaswell** [comment]
This is internal API (it is called by the Aritsts parent as part of rendering the figure (the update methods in the GUIs and the `savefig` methods eventually create a `Renderer` instance and then call `Figure.draw(renderer)` which is turn uses the visitor pattern to pass the renderer to all of the (nested) children and the result is the accumulated state on the renderer (for Agg that is an RGBA buffer we can extract, for svg it is a file-like we have been streaming text into).). 

No one should be calling this outside of the draw process so I don't think we need an deprecation period, but we should highlight it in the release notes (and be prepared to add a deprecation period if we actually broke somenone).

**Comment by rcomer** [comment]
Thanks for the explanation @tacaswell!  I ended up here because I was looking at an artist in Cartopy whose `draw` method will update colors, etc. from `kwargs` if passed.  I couldn’t think under what circumstances they would be passed so went grepping for other examples, but didn’t get any less confused!

**Comment by timhoffm** [comment]
If we want to be on the very safe side, we can still do a deprecation. There's no hurry in removing the arguments.

**Comment by tacaswell** [comment]
Once you are down the path of writing your own `draw` methods you could have a class that calls subsequent classes and odes pass something meaningful across the function call, but if downstream libraries are doing that, that is between them and themselves (so long as they do not _require_ the kwargs it matches our expectations and I see no reason we should care if they are optional).
