### ISSUE TITLE
[Bug]: Inconsistent treatment of list of labels in `plot` when the input is a dataframe

### ISSUE THREAD

**Issue by Gattocrucco** [matplotlib/matplotlib#27762]
### Bug summary

`plt.plot` interprets a dataframe as a sequence of series to be plotted, one per column. Labels can be specified by setting `label` to a list of labels matching the number of columns. If the dataframe has only one column, though, the `label` argument is interpreted as a single label, instead of a list with one element.

### Code for reproduction

```python
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

x = np.arange(5)
y = pd.DataFrame({'a': x, 'b': x + 1})

plt.figure('double', clear=True)
plt.plot(x, y, label=['A', 'B'])
plt.legend() # -> ok

plt.figure('single', clear=True)
plt.plot(x, y.drop('b', axis=1), label=['A'])
plt.legend() # -> legend label is "['A']"

plt.show()
```

### Actual outcome

<img width="592" alt="immagine" src="https://github.com/matplotlib/matplotlib/assets/9684110/aa6abbcc-dd05-459b-b4ae-acb8a0d2e998">

### Expected outcome

<img width="573" alt="immagine" src="https://github.com/matplotlib/matplotlib/assets/9684110/4dd88c38-216d-446b-a8d4-de70e299f39e">

### Operating system

macOS 14.2.1

### Matplotlib Version

3.8.2

### Matplotlib Backend

MacOSX

### Python version

3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]

### Installation

conda

**Comment by rcomer** [comment]
This isn't specific to dataframes.  The same behaviour can be seen with

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([[0, 0], [1, 2]], label=['A', 'B'])
ax.legend()
plt.show()
```
![image](https://github.com/matplotlib/matplotlib/assets/10599679/b4d55fae-0762-4c77-a95a-a23de20985fa)

```python
fig, ax = plt.subplots()
ax.plot([0, 1], label=['A'])
ax.legend()
plt.show()
```
![image](https://github.com/matplotlib/matplotlib/assets/10599679/8e93a686-fe41-431b-ae31-238b0ddff189)

**Comment by rcomer** [comment]
I tried poking the code that @timhoffm highlighted, but it seems the current behaviour is very much expected:

https://github.com/matplotlib/matplotlib/blob/d2cc4d0b0a2e1e9e8a5c1f311f0e10ef8acdb9ef/lib/matplotlib/tests/test_legend.py#L1191-L1203

**Comment by Gattocrucco** [comment]
I think the current behavior is like if `np.array([1])` yielded a 0-d array. It breaks agnostic coding patterns that do not depend on the length of things.

**Comment by timhoffm** [comment]
> I tried poking the code that @timhoffm highlighted, but it seems the current behaviour is very much expected:

My vague recollection is that #16178 should only affect the multiple-data case. Changes to the single-data case were out of scope. I believe, the test is just ensurging the single-data case is kept as is; i.e. anything passed to `label` is converted using `str`. So in a way, this behavior is expected as the de-facto behavior, but I would not claim it's necessarily intended.

We have a generalization ambiguity problem. We cannot have both:
1. For single data, convert any label object to str.
2. For N data, support a list of labels of length N.

While I see the motivation for 2 with the N=1 case, supporting that would mean to break 1. We certainly have to go through a deprecation period with this. And we'd have to consider how to handle the case one dataset, but >1 labels (as in the test). I think, if one dataset, length-1 label list gives the one element as label, the >1 labels case should error out and not create the str anymore.

I'd fundamentally support the idea of not converting iterables to str anymore - if anybody wants to take on the deprecation effort.

**Comment by jklymak** [comment]
> I'd fundamentally support the idea of not converting iterables to str anymore - if anybody wants to take on the deprecation effort.

I think we should do this - I can't think of a situation where a user would want the result above, and if for some weird reason they do, they can convert to a single string themselves.  I think the current behaviour is undesirable enough that I'm not even sure we need a full deprecation cycle for it.

**Comment by timhoffm** [comment]
I would bet that there are people who for some reason have a list as identifier for their dataset and they don't care enough to format that explicitly (`['A', 'B']` in the legend was good enough for them). Therefore, I advocate for a regular deprecation.

**Comment by rcomer** [comment]
So what should happen for the single element list during the deprecation period?  Can we implement new behaviour for that right away?

**Comment by timhoffm** [comment]
Given all context, I’d say yes. - Longer explanation will follow later (don’t want to type that on the phone)
