### ISSUE TITLE
[ENH]: multiple ax{v,h}lines

### ISSUE THREAD

**Issue by Teagum** [matplotlib/matplotlib#27760]
### Problem

I'm always frustrated when I have to write an explicit loop in order to put multiple axlines on my plots. It would be great if there was a wrapper `axvlines` that would accept an iterable as argument for the `x` parameter. So that I cloud wirte

`plt.axvlines([1, 2, 3])`

instead of

```
for i in [1, 2, 3]:
    plt.axvline(i)
```

### Proposed solution

A solution could roughly look like

```
import numbers
from typing import Iterable

import matplotlib.pyplot as plt


def axvlines(x: float | Iterable[float] = 0, ymin: float = 0, ymax: float = 1, **kwargs):
    if isinstance(x, numbers.Real):
        return plt.axvline(x, ymin, ymax, **kwargs)
    return [plt.axvline(val, ymin, ymax, **kwargs)
            for val in x]
```

An extension for the remaining parameters seems also easy.

**Comment by Teagum** [comment]
Hi @rcomer, yes, I know about hlines and vlines, but they have very different behaviour than ax{v,h}line. {h,v}lines require arguments for `xmin` and `xmin`, i.e. the length of the line. Also they update the axis limits such that there is always space between the line's endpoints and the axis spines. On the other hand axvline, draws an infinite line across the whole axis, without updating the the axis limits. And that's exactly what I need.

**Comment by timhoffm** [comment]
While technically possible, I'm quite hesitant to expand the API in this direction. This type of vectorization is not something we have in our API (except for some aspects around Collections. But Collections are a different topic and not applicable here). If we do this here, I advocate to limit this to `x` only.

To better judge the intent, what excatly is your use case? How many lines do you want to draw? Do they differ in parameters apart from `x`?

**Comment by Teagum** [comment]
> If you pass in a transform then you can have em be infinite, something like https://matplotlib.org/stable/gallery/lines_bars_and_markers/vline_hline_demo.html

Awesome, @story645! That's exactly what I wanted. And as it turns out `axvline` is essentially the code from this example.

Next time I'll first check the source before submitting an issue. Sorry for that
