### ISSUE TITLE
WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### ISSUE THREAD

**Issue by saigonesepapaya** [matplotlib/matplotlib#27775]
### Bug summary

I am using Mac m3 pro and I keep getting this error message. 
Python default interpreter path is "_not synced_" : /usr/bin/python3

I'm trying to display a black screen (following a tutorial, and the guy who does it doesn't get any error message and everything displays correctly).

Does anyone know how to fix this? Thanks a lot in advance.

### Code for reproduction

```python
import pygame
pygame.init()


win = pygame.display.set_mode((500,500))

pygame.display.set_caption("First Game")
```

### Actual outcome

Black Screen is displayed for like 1ms. And I get this message (the one in the title):

**WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.**

### Expected outcome

Black Screen should be displayed and shouldn't be disappearing unless I click on the close window button.

### Additional information

this code:
"""

import pygame
import spritesheets

pygame.init()

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption('Spritesheets')

sprite_sheet_image = pygame.image.load('doux.png').convert_alpha()
sprite_sheet = spritesheets.SpriteSheet(sprite_sheet_image)

BG = (50, 50, 50)
BLACK = (0, 0, 0)

frame_0 = sprite_sheet.get_image(0, 24, 24, 3, BLACK)
frame_1 = sprite_sheet.get_image(1, 24, 24, 3, BLACK)
frame_2 = sprite_sheet.get_image(2, 24, 24, 3, BLACK)
frame_3 = sprite_sheet.get_image(3, 24, 24, 3, BLACK)

run = True
while run:

	#update background
	screen.fill(BG)

	#show frame image
	screen.blit(frame_0, (0, 0))
	screen.blit(frame_1, (72, 0))
	screen.blit(frame_2, (150, 0))
	screen.blit(frame_3, (250, 0))

	#event handler
	for event in pygame.event.get():
		if event.type == pygame.QUIT:
			run = False

	pygame.display.update()

pygame.quit()

"""

displays something but also gives me an error message: 
**Python[3099:72313] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.**

### Operating system

OS/X

### Matplotlib Version

3.8.2

### Python version

3.12.2

### Installation

pip

**Comment by saigonesepapaya** [comment]
figured it out lol mb

**Comment by tacaswell** [comment]
Duplicate of https://github.com/matplotlib/matplotlib/issues/27389
