### ISSUE TITLE
[MNT]: Should BytesIO be closed here?

### ISSUE THREAD

**Issue by ahuang11** [matplotlib/matplotlib#27804]
### Summary

Seems like buf should be used as a contextmanager or closed manually after `get_buffer`, but not sure if it has a huge impact.
 
https://github.com/matplotlib/matplotlib/blob/v3.8.3/lib/matplotlib/animation.py#L506-L512

### Proposed fix

```python

        _validate_grabframe_kwargs(savefig_kwargs)
        with BytesIO() as buf:
            self.fig.savefig(
                buf, **{**savefig_kwargs, "format": "rgba", "dpi": self.dpi})
            self._frames.append(Image.frombuffer(
                "RGBA", self.frame_size, buf.getbuffer(), "raw", "RGBA", 0, 1))
```

**Comment by anntzer** [comment]
No; see e.g. the last post of https://groups.google.com/g/django-developers/c/_ZcdWE9c2z8.
If anything I'd rather get rid of the places where we *do* wrap BytesIO in a context manager (per the thread above), but I don't think it's really worth it either.
