### ISSUE TITLE
[Bug]: When drawing multiple curves on one graph, they cannot be displayed.

### ISSUE THREAD

**Issue by Chuan1937** [matplotlib/matplotlib#27817]
### Bug summary

When drawing multiple curves on one graph, they cannot be displayed. But when I draw 4 bars, it can be displayed。
![image](https://github.com/matplotlib/matplotlib/assets/99251452/ad3cf899-cce2-4631-b4d2-add56351cd8e)
![image](https://github.com/matplotlib/matplotlib/assets/99251452/5ef9becf-fd68-49bd-bb1f-6a3a5aff1803)

### Code for reproduction

```Python
time=np.linspace(2019,2023,155)
time=pd.DataFrame(time[-33:],columns=['Time'])
with plt.style.context(['science','ieee']):
    #绘制一张图，但accuracy每列都要绘制在一张图上
    fig,ax=plt.subplots(figsize=(15,10))
    ax.plot(time['Time'],accuracy['AIC'],label='AIC')
    ax.plot(time['Time'],accuracy['BIC'],label='BIC')
    ax.plot(time['Time'],accuracy['S-AIC'],label='S-AIC')
    # ax.plot(time['Time'],time,accuracy['S-BIC'],label='S-BIC')
    # ax.plot(time['Time'],accuracy['Simple'],label='Simple')
    # ax.plot(time['Time'],accuracy['JMA'],label='JMA')
    # ax.plot(time['Time'],accuracy['MMA'],label='MMA')
    # ax.plot(time['Time'],accuracy['MAACM'],label='MAACM')
    ax.plot(time['Time'],accuracy['REAL'],label='REAL')
    ax.set_xlabel('Time')
    ax.set_ylabel('Power')
    ax.legend()
    plt.savefig('D:\M\MATLAB Driver\\forward\Forty-fourth\\accuracy.png')
    plt.show()
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/99251452/09b129c1-ccbe-4348-8721-ce9503493bd1)
![image](https://github.com/matplotlib/matplotlib/assets/99251452/5c767a89-3109-49a3-bb38-ab1f299ecf3d)

### Expected outcome

I want it to be fully generated

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.15

### Jupyter version

6.5.2

### Installation

pip

**Comment by Chuan1937** [comment]
[](url)
[accuracy.xlsx](https://github.com/matplotlib/matplotlib/files/14392407/accuracy.xlsx)
this is the data

**Comment by rcomer** [comment]
Your code for plotting 'S-BIC' is different from all the others, as you pass `time` as an extra parameter.  Is that intentional?

**Comment by Chuan1937** [comment]
> 用于绘制“S-BIC”的代码与所有其他代码不同，因为您作为额外参数传递。这是故意的吗？`time`

Thank you for your reply, this problem was indeed due to my carelessness. Good thing I've solved it after your help
