### ISSUE TITLE
[Bug]: ".C10" does not work as plot shorthand format spec

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#27828]
### Bug summary

The plot shorthand format spec does not work when combining a Cn color with n>=10 with a linestyle or a markerstyle, e.g. ".C10".  Somewhat inconsistently, it does work when a Cn color is given by itself.

### Code for reproduction

```Python
from pylab import *; plot([0, 1], ".C10") 
# plot([0, 1], "C10") works; note that this also goes through the shorthand route
# unlike plot([0, 1], c="C10")
```

### Actual outcome

ValueError: '.C10' is not a valid format string (unrecognized character '0')

### Expected outcome

No error.

### Operating system

macos

### Matplotlib Version

3.9.0.dev1178+g88d64e5f0c

### Matplotlib Backend

any

### Python version

3.12

### Jupyter version

none

### Installation

git checkout

**Comment by ksunden** [comment]
The relevant code is:

https://github.com/matplotlib/matplotlib/blob/5e347777192b37ac77decc4f975e53ed9d87973b/lib/matplotlib/axes/_base.py#L192-L195

This is the case from the long if-elif chain that is handling the Cn colors. It only looks one character ahead (and advances the current index by exactly 2 as a result.

(If only color is provided, and multidigit `Cn` colors count for this, then that is handled prior to parsing the individual parts in this if/elif chain)
