### ISSUE TITLE
[Bug]: color=("Cn", alpha) does not work

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#27827]
### Bug summary

Reading https://matplotlib.org/stable/users/explain/colors/colors.html#color-formats it would seem like `color=("C0", .5)` (C0 color with alpha=0.5) should work, but it doesn't.

(Could also be considered a doc bug or a feature request, strictly speaking.)

### Code for reproduction

```Python
from pylab import *; plot([0, 1], c=("C0", .5))
```

### Actual outcome

ValueError: ('C0', 0.5) is not a valid value for color

### Expected outcome

No error.

### Operating system

macos

### Matplotlib Version

3.9.0.dev1178+g88d64e5f0c

### Matplotlib Backend

any

### Python version

3.12

### Jupyter version

none

### Installation

git checkout

**Comment by ksunden** [comment]
the precise logic that parses 2-element tuples into color/alpha is:

https://github.com/matplotlib/matplotlib/blob/5e347777192b37ac77decc4f975e53ed9d87973b/lib/matplotlib/colors.py#L321-L325

This appears in the private function `_to_rgba_no_colorcycle`. This function is only ever called from `to_rgba` (after handling the `Cn` case specially). Moving (or adding, I guess) the same lines to the beginning of the public `to_rgba` would allow `("C0", 0.5)` and likely not have too many other repercussions.

**Comment by FilBalza** [comment]
When trying to solve this issue, I saw that the suggested solution was already added and the code now works. Here's the commit for reference: https://github.com/matplotlib/matplotlib/commit/13b8718adeef45ba2267b72fab5cf00836535143

**Comment by rcomer** [comment]
Fixed by #28436
