### ISSUE TITLE
[Bug]: PathCollection using alpha ignores 'none' facecolors

### ISSUE THREAD

**Issue by subsurfaceiodev** [matplotlib/matplotlib#27839]
### Bug summary

As title, using alpha parameter in PathCollection, either as a list or as a scalar value, causes 'none' facecolors to be ignored / filled

### Code for reproduction

```Python
import matplotlib.pyplot as plt
from matplotlib.collections import PathCollection
from matplotlib.path import Path

# https://matplotlib.org/stable/gallery/shapes_and_collections/compound_path.html

paths = [
    Path(
        [(1, 1), (1, 2), (2, 2), (2, 1), (0, 0)],
        [Path.MOVETO] + [Path.LINETO] * 3 + [Path.CLOSEPOLY]
    ),
    Path(
        [(4, 4), (5, 5), (5, 4), (0, 0)],
        [Path.MOVETO] + [Path.LINETO] * 2 + [Path.CLOSEPOLY]
    ),
]

fig, ax = plt.subplots()
collection = PathCollection(
    paths,
    edgecolors='black',
    facecolors=['blue', 'none'],
    alpha=[1, 1],
    # alpha=1
)
collection.set_transform(ax.transData)
ax.add_artist(collection)
ax.set(xlim=(0, 5), ylim=(0, 5))
plt.show()
```

### Actual outcome

![actual](https://github.com/matplotlib/matplotlib/assets/109676812/28dd3e05-c218-4274-b586-c86639cd8c60)

### Expected outcome

![expected](https://github.com/matplotlib/matplotlib/assets/109676812/390c44e5-0fe3-40b5-97f4-b57e1a7cc81e)

### Operating system

Windows

### Matplotlib Version

3.8.3

### Python version

3.12

### Installation

pip

**Comment by chaoyihu** [comment]
When you set alpha = 1, `collections::set_alpha()` calls `_set_facecolor()`, which further calls `to_rgba_array()` in `collections.py`, Line 766: `self._facecolors = mcolors.to_rgba_array(c, self._alpha)` in which `c` is a list of strings: ["blue", "none"], and alpha is [1, 1].

In`colors::to_rgba_array()`, Line 509 - 510, the alpha param is used to replace the default alpha values in the rgba sequence:
```
if alpha is not None:
    rgba[:, 3] = alpha
```
resulting in the following change:
```
facecolor rgba before applying alpha 
[[0. 0. 1. 1.]       # this is black
 [0. 0. 0. 0.]]      # this has no color
facecolor rgba after applying alpha 
[[0. 0. 1. 1.]       # this is still black
 [0. 0. 0. 1.]]      # this becomes black
```

To produce the expected outcome, try the following code:

```
import matplotlib.pyplot as plt
from matplotlib.collections import PathCollection
from matplotlib.path import Path

# https://matplotlib.org/stable/gallery/shapes_and_collections/compound_path.html

paths = [
    Path(
        [(1, 1), (1, 2), (2, 2), (2, 1), (0, 0)],
        [Path.MOVETO] + [Path.LINETO] * 3 + [Path.CLOSEPOLY]
    ),
    Path(
        [(4, 4), (5, 5), (5, 4), (0, 0)],
        [Path.MOVETO] + [Path.LINETO] * 2 + [Path.CLOSEPOLY]
    ),
]

fig, ax = plt.subplots()
collection = PathCollection(
    paths,
    edgecolors='black',
    facecolors=['blue', (0,0,0,0)]    # represent the desired face color using a explicit rgba tuple
)
collection.set_transform(ax.transData)
ax.add_artist(collection)
ax.set(xlim=(0, 5), ylim=(0, 5))
plt.show()
```
![screenshot-matplotlib-issue-27839](https://github.com/matplotlib/matplotlib/assets/90495101/f3c11ff0-d480-4081-9579-a4cb1a666fe0)
