### ISSUE TITLE
Documentation and bug report: mplot3d and blitting

### ISSUE THREAD

**Issue by Fcp-GitHub** [matplotlib/matplotlib#27830]
### Summary
Problem with 3d animation using `FuncAnimation` and the `mplot3d` toolkit. Maybe this problem comes from not enough clarifications in the documentation. Following this it is presented a simplified version of the program that led me to these conclusions.

### Explanation
Looking through the documentation regarding animation and blitting, it is possible to see two different approaches: 
- The first one (see [here](https://matplotlib.org/stable/users/explain/animations/animations.html#funcanimation)) is presented at the first explanation page about creating animations with the `animation` module. Here it is explained that in the function passed to `FuncAnimation` there has to be some method that updates the data in each artist in order to generate the new frame. It is written that "the update function uses the `set_*` function for different artists to modify the data".
- However, the second approach (presented [here](https://matplotlib.org/stable/users/explain/animations/blitting.html#sphx-glr-users-explain-animations-blitting-py), where blitting is actually explained) tells the user to use the `draw_artist()` method in order to update/redraw efficiently the artists in the function of the render loop. I haven't found many low-level details (except some look directly at the source code) about the functioning of `FuncAnimation` or `plt.show()`, so I couldn't make real assumptions about their involvement in this.

Mixing the informations, I have encountered many problems that I will try to replicate and explain in the following code.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Line3D
from matplotlib.animation import FuncAnimation

fig = plt.figure()
ax = fig.add_subplot(projection='3d', xlim=(0,100), ylim=(0,100), zlim=(0,100))

line = Line3D( [0], [0], [0], marker="o", markersize=15, color='r', animated=True)

def update(t):
    line.set_data_3d([t],[t],[t])
    ax.draw_artist(line)
    
    return line,

anim = FuncAnimation(fig=fig, func=update, frames=None, blit=True, cache_frame_data=False)

plt.show()
```

### Actual outcome

  File "C:\Users\user\Desktop\...\axes3d_issue.py", line 13, in update
    ax.draw_artist(line)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\axes\_base.py", line 3080, in draw_artist
    a.draw(self.figure.canvas.get_renderer())
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mpl_toolkits\mplot3d\art3d.py", line 270, in draw
    xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
                                                         ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'M'

### Expected outcome

The rendering of the image.

### Additional information

Some considerations:
1. Maybe the `draw_artist()` method should be used in combination with `plt.pause()` or by API developers, but neither is specified in the documentation. Removing the `ax.draw_artist(line)` (following thus the first approach described at the beginning) is indeed a solution to the problem.
2. Using Visual Studio Code Data inspection debug tool along with `debugpy`, I've noticed that in the `update()` function  the `Line3D` artist seems to lose all the references to the parent classes `Axes3D` and `Figure`, hence some error messages. However, trying to add something like `line.axes = ax` leads directly to an exception raised due to the next problem.
3. It seems that without calling the 'Axes3D.draw()' method first, the projection matrix variable `M` of the same class is never updated from `None` to some value. Actually, calling the `Axes3D.get_proj()` method for `M` and computing the inverse matrix also for the `invM` attribute seems to work. This appears to be a flaw in every case, but maybe it corroborates the hypothesis of some kind of "reservedness" of the method for some special cases.  
If this is the case, it is not specified neither in the already cited documentation, neither in the (quite short, for some reason) `mplot3d` documentation (see [here](https://matplotlib.org/stable/users/explain/toolkits/mplot3d.html)). 

I think the documentation about this topic should be a bit clearer. Some more explanation about the inner working of some ubiquitous functions like `plt.show()` or the `clear` methods, another set of functions that is presentend unclearly, could help users understand and resolve their problems, along with using them more consciously.

### Operating system

Microsoft Windows 11 Home

### Matplotlib Version

3.8.2

### Matplotlib Backend

TkAgg

### Python version

3.12.2

### Installation

pip

**Comment by WeatherGod** [comment]
I think the main issue is that the Line3D object was never added to the
axes object. It can't draw an object it doesn't "own". Here is an example
(albeit without blitting):
https://matplotlib.org/stable/gallery/animation/random_walk.html

**Comment by WeatherGod** [comment]
I'll note that this example is probably about 10 years old, and the claim
that "set_data()" for 3D data is no longer true, as your example
demonstrates.

**Comment by Fcp-GitHub** [comment]
Ok, I have added the `ax.add_line(line)` method and it doesn't get better. Actually, the error message is pretty similar to the one at the top of the discussion. 
Checking the source code again, it still seems to be an issue related to `Axes3d` not having a projection matrix soon enough because it's `draw_artist()` method calls immediately the artist's `draw()` one and thus never initiates its projection matrix `ax.M` (that is needed by the `Line3D.draw()` method). 
Maybe the problem is that the `draw_artist()` method shouldn't be used within the `FuncAnimation`'s update function. If this is the case, it should be explicited in the documentation. I've noticed problems also with clearing functions like: `ax.clear())`, `fig.clear()`, `plt.clear()`, etc. simply put in the update function.

**Comment by timhoffm** [comment]
If you use `FuncAnimation`, follow the basic guide [here](https://matplotlib.org/stable/users/explain/animations/animations.html#funcanimation)
In particular, create an initial figure with regular plotting methods - manually instantiating Artists and trying to wire them up correctly would be a hassle. Also, you don't need any `draw_artist()`; `FuncAnimation` takes care of this.

This works:
```
fig = plt.figure()
ax = fig.add_subplot(projection='3d', xlim=(0,100), ylim=(0,100), zlim=(0,100))
line, = ax.plot([0], [0], [0], marker="o", markersize=15, color='r', animated=True)

def update(t):
    line.set_data_3d([t],[t],[t])
    return line,

anim = FuncAnimation(fig=fig, func=update, frames=100, blit=True, cache_frame_data=False)
```

**Comment by timhoffm** [comment]
#27867 fixes some general documentation issues uncovered above.

Still open: Better description of blitting in `FuncAnimation`. E.g.
- do we need `animated=True` for the Artists or does `FuncAnimation` handle this (with and without `intit_func`)?
- does blitting work at all? I don't see a difference in output or timing in my above code?

**Comment by Fcp-GitHub** [comment]
> #27867 fixes some general documentation issues uncovered above.
> 
> 
> 
> Still open: Better description of blitting in `FuncAnimation`. E.g.
> 
> - do we need `animated=True` for the Artists or does `FuncAnimation` handle this (with and without `intit_func`)?
> 
> - does blitting work at all? I don't see a difference in output or timing in my above code?

Agreed. The `animated=True` seems actually a bit extra considering that we don't need to call functions such as `draw_artist()` that appear to be mandatory using `animated` reading [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.artist.Artist.set_animated.html#matplotlib.artist.Artist.set_animated) for example.
Maybe the problem with the documentation about blitting is that it isn't clearly subdivided between the parts talking about blitting with raw animations (using `plt.clear()`) and the ones talking about the module `FuncAnimation`. There should be clear partitioning between animations with helper classes/modules and raw animations.

I think there should also be some better documentation for `mplot3d` that now has just a list of examples in it. I know its usage should be similar to the 2D counterparts, but it has its peculiarities.
