### ISSUE TITLE
[MNT]: require `python-dateutil>=2.9.0`

### ISSUE THREAD

**Issue by bersbersbers** [matplotlib/matplotlib#27841]
### Summary

Installing `matplotlib` installs `python-dateutil`. On Python 3.12, `python-dateutil<2.9.0` issues warnings, compare https://github.com/matplotlib/matplotlib/issues/27600.

### Proposed fix

I'd suggest enforcing `python-dateutil>=2.9.0` as a dependency, at least on Python 3.12.

**Comment by bersbersbers** [comment]
Related: https://github.com/pandas-dev/pandas/issues/57688

**Comment by timhoffm** [comment]
This is a downstream topic. IMHO it’s not up to us to eagerly pin that. Usually, you’ll get the new version anyway if you create a new environment. But if you don’t want that or can’t. Nothing really bad happens. You’ll only get the depreciation warning. We shouldn’t prohibit this.

**Comment by dstansby** [comment]
Agreed with the above comment, so I'll close this.
