### ISSUE TITLE
[Bug]: close_group is not called when using patheffects

### ISSUE THREAD

**Issue by sherlockdoyle** [matplotlib/matplotlib#27843]
### Bug summary

I am in the process of developing a custom `Renderer` for matplotlib. My understanding is that every `Renderer.open_group` call will have a corresponding `Renderer.close_group` call. However, when patheffects are used (at least), the `close_group` never gets called.

### Code for reproduction

```Python
from matplotlib import patheffects
from matplotlib.backend_bases import FigureCanvasBase, GraphicsContextBase, RendererBase
from matplotlib.figure import Figure
from matplotlib.path import Path
from matplotlib.transforms import Transform
from matplotlib.typing import ColorType


class Renderer(RendererBase):
    def __init__(self) -> None:
        super().__init__()
        self.indent = ''

    def open_group(self, s: str, gid: str | None = None) -> None:
        print(self.indent + 'open ' + s)
        self.indent += '  '
        return super().open_group(s, gid)

    def close_group(self, s: str) -> None:
        self.indent = self.indent[:-2]
        print(self.indent + 'close ' + s)
        return super().close_group(s)

    def draw_path(
        self, gc: GraphicsContextBase, path: Path, transform: Transform, rgbFace: ColorType | None = None
    ) -> None:
        pass


class Canvas(FigureCanvasBase):
    def draw(self):
        self.figure.draw(Renderer())


figure = Figure()
canvas = Canvas(figure)
ax = figure.gca()
ax.set_axis_off()

cg1 = ax.contour([[0, 1], [2, 3]])
cg1.set(path_effects=[patheffects.withTickedStroke(angle=135)])

canvas.draw()
```

### Actual outcome

    open figure
      open patch
      close patch
      open axes
        open QuadContourSet
        close axes
      close figure

### Expected outcome

`QuadContourSet` is closed.

    open figure
      open patch
      close patch
      open axes
        open QuadContourSet
        close QuadContourSet
      close axes
    close figure

### Additional information

After some investigation, it appears that in `Collection.draw`, [if any path effects are present](https://github.com/matplotlib/matplotlib/blob/76eaa9669471b86a2569885adf760dc388585783/lib/matplotlib/collections.py#L367), the renderer is updated to `PathEffectRenderer`. Subsequently, `close_group` is called on this updated renderer, but this call does not reach the original renderer.

### Operating system

Ubuntu

### Matplotlib Version

3.8.3

### Matplotlib Backend

Custom

### Python version

Python 3.10.12

### Installation

pip

**Comment by chaoyihu** [comment]
# Fix
Thanks for raising the issue! The problem is that `close_group` gets called by a different renderer than the renderer you defined. Omitting the path_effects parameter in your reproduction code will print "close QuadContourSet" as expected:
```
# comment out this line
# cg1.set(path_effects=[patheffects.withTickedStroke(angle=135)])
```

# Explanation

Trace the execution of this line of code in your provided example:

```
# code for reproduction
canvas.draw()
```

```
# code for reproduction
self.figure.draw(Renderer())
```

```
# figure.py, Figure::draw()
3102            mimage._draw_list_compositing_images(
3103                renderer, self, artists, self.suppressComposite)
```

```
# image.py, _draw_list_compositing_images()
131         for a in artists:
132             a.draw(renderer)
```

QuadContourSet.draw() invokes the draw method in its parent class `Collection`:

```
# collection.py, Collection::draw()
370 if self.get_path_effects():     # this condition is true since you specified the path_effects parameter
371     from matplotlib.patheffects import PathEffectRenderer
372     renderer = PathEffectRenderer(self.get_path_effects(), renderer)
```

Which changed the renderer from ```<__main__.Renderer object at 0x...(rep1)>``` (your renderer)
to ```<matplotlib.patheffects.PathEffectRenderer object at 0x...(rep2)>``` (a different renderer), thus the close statement for QuadContourSet was not printed.

**Comment by chaoyihu** [comment]
sherlockdoyle is correct. The issue can be traced down to:

```
# collection.py, Collection::draw()
370     if self.get_path_effects():  # true, as path effects are present
371         from matplotlib.patheffects import PathEffectRenderer
372         renderer = PathEffectRenderer(self.get_path_effects(), renderer)
```

where the renderer gets changed to a `PathEffectRenderer` object.

Seems that the renderer's behavior is meant to be kept unaltered besides the added path effects, but methods including `open_group` and `close_group` are not overridden in the class definition. In fact, the `PathEffectRenderer` docstring provides a note on this.

```
class PathEffectRenderer(RendererBase):
    """
    Implements a Renderer which contains another renderer.

    This proxy then intercepts draw calls, calling the appropriate
    :class:`AbstractPathEffect` draw method.

    .. note::
        Not all methods have been overridden on this RendererBase subclass.
        It may be necessary to add further methods to extend the PathEffects
        capabilities further.
    """
```

I opened a pull request overriding the two methods.
