### ISSUE TITLE
[Bug]: matplotlib.pyplot.matshow "(first dimension of the array) are displayed horizontally" but are displayed vertically

### ISSUE THREAD

**Issue by tkuraku** [matplotlib/matplotlib#27852]
### Bug summary

matshow states that  "(first dimension of the array) are displayed horizontally": https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.matshow.html#matplotlib-pyplot-matshow. However it seems that the first dimension is vertically.

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt


nx = 15
ny = 21

img = np.zeros((nx, ny))

for i in range(nx):
    for j in range(ny):
        if j == i:
            img[i, j] = 1

plt.figure()
plt.subplot(1, 2, 1)
plt.imshow(img)
plt.title('imshow')
plt.subplot(1, 2, 2)
plt.matshow(img, fignum=0)
plt.title('matshow')
plt.show()
```

### Actual outcome

First dimension is shown vertically

### Expected outcome

I would expect that the first dimension be show horizontally according to the documentation.

### Operating system

Debian 12

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12

### Installation

conda

**Comment by tkuraku** [comment]
![Screenshot from 2024-03-03 18-12-57](https://github.com/matplotlib/matplotlib/assets/11217294/c6ddb094-49e5-457c-b7c9-35abbbccbf72)

**Comment by timhoffm** [comment]
I believe the description is just wrong. Matrix indices are (row, column) and that’s what matshow displays.
