### ISSUE TITLE
[Bug]: Zoom und pan not working after writing pdf pages. 

### ISSUE THREAD

**Issue by Erwin-Wert** [matplotlib/matplotlib#27865]
### Bug summary

Ladies and Gentlemen,
Zoom und pan is not working after writing pdf pages. 
Within matplotlib version 3.7.5 it is working. 
In e.g. 3.8.3 it does not react any more.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
fig, ax = plt.subplots()
ax.plot([1, 2, 3], [4, 5, 6])
filename = "test4.pdf"
with PdfPages(filename) as pdf:
    fig.show()
    pdf.savefig() # <== if you comment this line, then zoom is working fine. However it is not getting stored.
```

### Actual outcome

![zoom not possible](https://github.com/matplotlib/matplotlib/assets/122103308/221749bd-9fe8-4e19-8ffe-96e1caaf66e9)

### Expected outcome

![zoom is possible](https://github.com/matplotlib/matplotlib/assets/122103308/8cd2229e-42d5-4519-bf74-c25cf18271c7)

### Additional information

In earlier versions it has been working fine. 
It is also not working within jupyterlab.
It was testet in Spyder IDE 5.5.1 and IDLE(Python 3.12 64-bit)
I take the earlier matplotlib version instead.

### Operating system

Windows 7, 

### Matplotlib Version

3.8.3

### Matplotlib Backend

QtAgg

### Python version

Python 3.12.2 64-bit

### Jupyter version

4.1.2

### Installation

pip

**Comment by Impaler343** [comment]
I believe a more appropriate code for reproduction is:

`import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

filename = "test4.pdf"

with PdfPages(filename) as pdf:
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [4, 5, 6])
    pdf.savefig() # <== if you comment this line, then zoom is working fine. However it is not getting stored.

plt.show()`

**Comment by Impaler343** [comment]
To solve this issue, you just need to write `plt.show()` before saving the figure. Like:

```
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
filename = "test4.pdf"

with PdfPages(filename) as pdf:
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [4, 5, 6])
    plt.show()

    fig1, ax1 = plt.subplots()
    ax1.plot([1, 2, 3, 4], [4, 5, 6, 7])
    plt.show()

    pdf.savefig() # <== if you comment this line, then zoom is working fine. However it is not getting stored.

**Comment by Impaler343** [comment]
On another note, 
<img width="625" alt="image" src="https://github.com/matplotlib/matplotlib/assets/73378019/af6dbaf6-edf8-4bb3-bd0a-34f95254d308">
The import statement is slightly incorrect `from matplotlib.backends.backend_pgf import PdfPages` and needs to be _backend_pdf_ instead of _backend_pgf_. Is it recommended to open a PR in small changes like this one?

**Comment by QuLogic** [comment]
This bisects to a6230cc72009483697be95d400eb23cdfcc7535b, or #25546, by @anntzer.

**Comment by QuLogic** [comment]
However, that appears to be exposing an existing different bug. For some reason, this context manager is not restoring the old canvas:
https://github.com/matplotlib/matplotlib/blob/9618fc6322745834dd098cadecf8e05a0917d498/lib/matplotlib/backends/backend_pdf.py#L2758-L2759

**Comment by QuLogic** [comment]
> The import statement is slightly incorrect `from matplotlib.backends.backend_pgf import PdfPages` and needs to be _backend_pdf_ instead of _backend_pgf_. Is it recommended to open a PR in small changes like this one?

That is not a typo; there are two `PdfPages` classes, one in the PDF backend and one in the PGF backend. That example uses the PDF backend, and the line is a cross-reference to the PGF backend.

**Comment by Erwin-Wert** [comment]
> To solve this issue, you just need to write `plt.show()` before saving the figure and pass the figure to the `savefig()` function. Like:
> 
> ```
> import matplotlib.pyplot as plt
> from matplotlib.backends.backend_pdf import PdfPages
> filename = "test4.pdf"
> 
> with PdfPages(filename) as pdf:
>     fig, ax = plt.subplots()
>     ax.plot([1, 2, 3], [4, 5, 6])
>     plt.show()
>     pdf.savefig(fig) # <== if you comment this line, then zoom is working fine. However it is not getting stored.
> ```
> 
> But you might have to undo changes that you did while inspecting the figure to save the original figure

The code snippet was just used to  reproduce the effect. The real application has multiple figures opened in a tkinter window. Then a function is called to export these figures to the pdf. After that I need the figures to be responsive to zoom and pan. Adding plt.show() opens an extra window with the figure. So this is not an option.

**Comment by Impaler343** [comment]
> > To solve this issue, you just need to write `plt.show()` before saving the figure and pass the figure to the `savefig()` function. Like:
> > ```
> > import matplotlib.pyplot as plt
> > from matplotlib.backends.backend_pdf import PdfPages
> > filename = "test4.pdf"
> > 
> > with PdfPages(filename) as pdf:
> >     fig, ax = plt.subplots()
> >     ax.plot([1, 2, 3], [4, 5, 6])
> >     plt.show()
> >     pdf.savefig(fig) # <== if you comment this line, then zoom is working fine. However it is not getting stored.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But you might have to undo changes that you did while inspecting the figure to save the original figure
> 
> The code snippet was just used to reproduce the effect. The real application has multiple figures opened in a tkinter window. Then a function is called to export these figures to the pdf. After that I need the figures to be responsive to zoom and pan. Adding plt.show() opens an extra window with the figure. So this is not an option.

What I collect from this is that the showing functionality must work after saving the figure. The initial code had a ```fig.show()``` function before saving the figure due to which I interpreted it in that way
