### ISSUE TITLE
Allow CircleCI to load version switcher hosted on matplotlib.org

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#27861]
I'm currently trying to bump the version of `pydata-sphinx-theme` that we're using (https://github.com/matplotlib/matplotlib/pull/27658), so we can get recent accessibility improvements from the theme. It's not currently possible to load the version switcher hosted at https://matplotlib.org/devdocs/_static/switcher.json on the documentation build that CircleCI generates. The console error is:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matplotlib.org/devdocs/_static/switcher.json?v3.8.1-1173-gfa55c9f44. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Is there anyone who has access to the Matplotlib website that can fix this to allow pages served by https://output.circle-artifacts.com to load https://matplotlib.org/devdocs/_static/switcher.json ? If this needs any more debugging, [here's a link to the full CircleCI doc build](https://output.circle-artifacts.com/output/job/e30b4122-9c27-4bb0-b8d2-c73a2534485b/artifacts/0/doc/build/html/index.html?pr=27658) on the PR updating `pydata-sphinx-theme`.

**Comment by tacaswell** [comment]
I'm not sure that we want to open up the holes required to opt out of that CORS protection.

**Comment by dstansby** [comment]
👍  in that case (I have zero knowledge/experience of these things) I'm happy to close this, and work out how to turn off the version switcher in the CircleCI build.

**Comment by dstansby** [comment]
FWIW I worked out how to use the version switcher that circleCI hosts with each artifact upload, so no need for this PR or a workaround on the circleCI builds.

**Comment by QuLogic** [comment]
Some time ago, I manually allowed this for CircleCI. However, this was not a long-term solution, so it was overwritten the next time we refreshed the server, which is why it stopped working again.
