### ISSUE TITLE
[Doc]: Latest stable version in sidebar out of date

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#27863]
### Documentation Link

https://matplotlib.org/stable/index.html

### Problem

The sidebar says 3.8.2; it should be 3.8.3, as in the title of the page.

<img width="1129" alt="Screenshot 2024-03-04 at 22 14 16" src="https://github.com/matplotlib/matplotlib/assets/6197628/c2478f52-a334-4fb1-acea-6279110736ec">

**Comment by ksunden** [comment]
Fixed by https://github.com/matplotlib/matplotlib.github.com/commit/8fd2775583275678b12f96031d4584ff0c7592f9 (May take a little time to work through caches and such)
