### ISSUE TITLE
[Doc]: Fix version switcher in devdocs

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#27876]
### Documentation Link

https://matplotlib.org/devdocs/

### Problem

In https://github.com/matplotlib/matplotlib/pull/27658 I updated the version switcher JSON link so it came from the circleCI builds when building on circleCI. It seems like https://matplotlib.org/devdocs/ is now trying to load a version switcher from circleCI too, so we need to:

1. Work out how to detect if deploying to devdocs
2. Set the version switcher URL in `docs/conf.py` correctly if this is the case

**Comment by QuLogic** [comment]
The condition is here:
https://github.com/matplotlib/matplotlib/blob/0da2da00d5a884db9c7991c31ee81d1b5dc57b63/.circleci/deploy-docs.sh#L5-L13

**Comment by dstansby** [comment]
Looks like it worked 🎉
