### ISSUE TITLE
[Bug]: Search button is broken after pydata-sphinx-theme update

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#27880]
### Bug summary

Regression of #27658 .

Clicking the button does not open the search field anymore.

### Code for reproduction

```Python
-
```

### Actual outcome

-

### Expected outcome

-

### Matplotlib Version

Devdocs

### Installation

None

**Comment by QuLogic** [comment]
Not sure what this has to do with governance, but added Release critical tag instead.

cc @dstansby

**Comment by dstansby** [comment]
Almost certainly a side effect of https://github.com/matplotlib/matplotlib/issues/27876, so when that gets fixed this should too. Worth keeping both issues open just in case.

**Comment by dstansby** [comment]
As I suspected, fixed by https://github.com/matplotlib/matplotlib/pull/27886
