### ISSUE TITLE
Hatching color in contourf function.

### ISSUE THREAD

**Issue by guziy** [matplotlib/matplotlib#2789]
It is possible to do hatching of regions using contourf function in matplotlib. Below is a working example I took from the matplotlib website. What I would like to do is to change the color of the hatching if it is possible. I tried to specify edgecolor, color and facecolor but it does not seem to work.. Thanks

```
import matplotlib.pyplot as plt
import numpy as np
# invent some numbers, turning the x and y arrays into simple
# 2d arrays, which make combining them together easier.
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)

# we no longer need x and y to be 2 dimensional, so flatten them.
x, y = x.flatten(), y.flatten()

# a plot of hatches without color with a legend
plt.figure()
n_levels = 6
plt.contour(x, y, z, n_levels, colors='black', linestyles='-')
cs = plt.contourf(x, y, z, n_levels, colors='none',
                  hatches=['.', '/', '\\', None, '\\\\', '*'],
                  extend='lower', edgecolor = "r", facecolor="blue", color = "red"
                  )

# create a legend for the contour set
artists, labels = cs.legend_elements()
plt.legend(artists, labels, handleheight=2)

plt.savefig("mpl_test.jpeg")
```

**Comment by fmaussion** [comment]
Hi @pelson , what about renaming the issue to a Feature Request and leave it open, just in case someone feels like implementing it? ;-)

Would it be difficult to do? I have only a superficial knowledge of mpl internals...

**Comment by WeatherGod** [comment]
Hatching gets a bit hairy because it is implemented differently in the
vector backends than it is in the AGG-based backends. This might be more
accessible now, though, than it was previously now that the macosx backend
has been reworked to be AGG based (there were all sorts of inconsistencies
with hatches in the macosx backend before).

**Comment by hughperkins** [comment]
Hi. How can I change the color of hatching?  I see like it might be possible by drawing twic,e but couldnt understand how.  currently my graph looks like:

![hatching_all_black](https://cloud.githubusercontent.com/assets/123560/24578126/597f9832-16da-11e7-9abd-90458f4a0008.png)

**Comment by HenryDayHall** [comment]
So I needed to plot hatched, coloured, contourf areas to denote an excluded region. This was the first hit that google gave me and it set me in the right direction. In case anyone else comes here looking for the same here is how I added colour to the hatching of contourf;

`import matplotlib.pyplot as plt
import numpy as np
import matplotlib


def contourf_hatch(*args, data=None, ax=None, hatch_color=None, **kwargs):
    if ax is None:
        ax = plt.gca()
    if hatch_color is None:  # call without modification
        print(f"You did not provide a hatch_color, so no hatch-colouring will be done")
        ax.contourf(*args, data=data, **kwargs)
    elif 'hatches' not in kwargs:  # call without modification
        print(f"You did not provide a hatches argument, so no a normal contourf plot will be made")
        ax.contourf(*args, data=data, **kwargs)
    else:  # everything is avalible to hatch the contours
        invisible_kws = {name: kwargs[name] for name in kwargs}
        invisible_kws['alpha'] = 0.
        invisible_kws.pop('hatches', None)
        contours = plt.contourf(*args, data=None, **invisible_kws)
        hatches = kwargs['hatches']
        for collection in contours.collections:
            path = collection.get_paths()[0]
            path_patch = matplotlib.patches.PathPatch(path,
                                                      edgecolor=hatch_color, hatch=hatches,
                                                      facecolor=(1.,1.,1.,0.), lw=0)
            ax.add_patch(path_patch)
            



if __name__ == '__main__':
    x = [1,2,3,4]
    y = [1,2,3,4]
    m = [[15,14,13,12],[14,12,10,8],[13,10,7,4],[12,8,4,0]]
    contourf_hatch(x, y, m, hatch_color=(0.1, 0.1, 0.8, 0.6), hatches='//', levels=[0., 12.])
    plt.show()
`

Clearly you will need to adapt it if you want more than one hatch style, or more than one colour.

**Comment by scottclowe** [comment]
Funnily enough, I was also trying to do contourf at the same time as @HenryDayHall, and he posted to this 3 year old issue while I was composing my own reply.

Here is how I got contourf with different colour hatching for each level. To do it, you run contourf once, and then loop over all the levels in the output to change the colour of the hatches.

```python
# Content as in example
# ------------------------------
import matplotlib.pyplot as plt
import numpy as np
# invent some numbers, turning the x and y arrays into simple
# 2d arrays, which make combining them together easier.
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)

# we no longer need x and y to be 2 dimensional, so flatten them.
x, y = x.flatten(), y.flatten()

# a plot of hatches without color with a legend
plt.figure()
n_levels = 6
plt.contour(x, y, z, n_levels, colors='black', linestyles='-')
cs = plt.contourf(
    x, y, z, n_levels, colors='none',
    hatches=['.', '/', '\\', None, '\\\\', '*'],
    extend='lower',
)

plt.title('Before')
plt.savefig("mpl_test_before.jpeg")

# ------------------------------
# New bit here that handles changing the color of hatches
colors = ['maroon', 'red', 'darkorange', 'gold', 'forestgreen', 'darkturquoise', 'dodgerblue', 'darkviolet']
# For each level, we set the color of its hatch 
for i, collection in enumerate(cs.collections):
    collection.set_edgecolor(colors[i % len(colors)])
# Doing this also colors in the box around each level
# We can remove the colored line around the levels by setting the linewidth to 0
for collection in cs.collections:
    collection.set_linewidth(0.)
# ------------------------------

plt.title('After')
plt.savefig("mpl_test_after.jpeg")
```

![mpl_test_before](https://user-images.githubusercontent.com/2891791/77676767-aef7d600-6f86-11ea-829f-0615252e2b37.jpeg)
![mpl_test_after](https://user-images.githubusercontent.com/2891791/77681959-0a799200-6f8e-11ea-9a69-d9389f7ec65a.jpeg)

**Comment by annemoree** [comment]
@scottclowe this works for me, thank you! I did notice however that these colors do not show up in the colorbar if you add one. Any suggestions for that?

**Comment by scottclowe** [comment]
@annemoree How about this?

It's using legend, like in the original post, instead of colorbar. I wasn't able to get colorbar to work for the base case, so please share example code if it's important to you that it is with a colarbar instead of legend.

```python
# ------------------------------
# Original code like in example
import matplotlib.pyplot as plt
import numpy as np
# invent some numbers, turning the x and y arrays into simple
# 2d arrays, which make combining them together easier.
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)

# we no longer need x and y to be 2 dimensional, so flatten them.
x, y = x.flatten(), y.flatten()

# a plot of hatches with color with a legend
fig = plt.figure()
n_levels = 6
ax = plt.contour(x, y, z, n_levels, colors='black', linestyles='-')
cs = plt.contourf(
    x, y, z, n_levels, colors='none',
    hatches=['.', '/', '\\', None, '\\\\', '*'],
    extend='lower',
)

# create a legend for the contour set
artists, labels = cs.legend_elements()
# Set the bbox so the legend appears outside the axes
plt.legend(artists, labels, handleheight=2, bbox_to_anchor=(1.04, 1), loc="upper left")

plt.title('Before')
plt.savefig("mpl_test_before.jpeg", bbox_inches="tight")

# ------------------------------
# New code that handles changing the color of hatches

colors = ['maroon', 'red', 'darkorange', 'gold', 'forestgreen',
          'darkturquoise', 'dodgerblue', 'darkviolet']
# For each level, we set the color of its hatch
for i, collection in enumerate(cs.collections):
    collection.set_edgecolor(colors[i % len(colors)])
# Doing this also colors in the box around each level
# We can remove the colored line around the levels by setting the linewidth to 0
for collection in cs.collections:
    collection.set_linewidth(0.)

# ---------------
# Handle creating legend with colors of hatches as in the figure

# create a legend for the contour set
artists, labels = cs.legend_elements()
# For each level, we set the color of its hatch in the legend too
for i, artist in enumerate(artists):
    artist.set_edgecolor(colors[i % len(colors)])
plt.legend(artists, labels, handleheight=2, bbox_to_anchor=(1.04, 1), loc="upper left")
# This fixes the color of the hatch in the legend, but unfornutately also changes
# the color of the bounding box around it

# ---------------
plt.title('After')
plt.savefig("mpl_test_after.jpeg", bbox_inches="tight")
```
![mpl_test_before](https://github.com/matplotlib/matplotlib/assets/2891791/2ee5741a-3880-461a-87e9-a12c46742265)
![mpl_test_after](https://github.com/matplotlib/matplotlib/assets/2891791/7c7cc238-dac0-4454-9335-d937e69448d4)

**Comment by GlennCreighton** [comment]
Since in newer versions of matplotlib contourf was updated to no longer contain collections, @scottclowe's great workaround no longer works.  It seems that _hatch_color is set to _edgecolors[0] no matter what in [collections.py](https://github.com/matplotlib/matplotlib/blob/44be14cc3a866e28a9ad22f36abfe8c0623cc6ac/lib/matplotlib/collections.py#L799C1-L816C26):
```
    def _set_edgecolor(self, c):
        set_hatch_color = True
        if c is None:
            if (mpl.rcParams['patch.force_edgecolor']
                    or self._edge_default
                    or cbook._str_equal(self._original_facecolor, 'none')):
                c = self._get_default_edgecolor()
            else:
                c = 'none'
                set_hatch_color = False
        if cbook._str_lower_equal(c, 'face'):
            self._edgecolors = 'face'
            self.stale = True
            return
        self._edgecolors = mcolors.to_rgba_array(c, self._alpha)
        if set_hatch_color and len(self._edgecolors):
            self._hatch_color = tuple(self._edgecolors[0])  # <-- Only first edgecolor is used
        self.stale = True
```

The only way I was able to get around this issue was to plot separate contours for each level pair, which is clunky (and could become expensive, though timing tests show similar results for this case).  Here is an example for those who might want to try it.  I think it goes without saying it would be very nice to have a more convenient way to set hatch edgecolors without this headache.

```
#!/usr/bin/env python3
# ------------------------------
# Modified code from scottclow
# https://github.com/matplotlib/matplotlib/issues/2789/#issuecomment-1613117068
# Original code like in example
import matplotlib.pyplot as plt
import numpy as np
# invent some numbers, turning the x and y arrays into simple
# 2d arrays, which make combining them together easier.
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)

# we no longer need x and y to be 2 dimensional, so flatten them.
x, y = x.flatten(), y.flatten()

# a plot of hatches with color with a legend
fig = plt.figure()
levels = [-2.4, -1.8, -1.2, -0.6, 0.0, 0.6, 1.2, 1.8, 2.4]
ax = plt.contour(x, y, z, levels, colors='black', linestyles='-')
cs = plt.contourf(
    x, y, z, levels, colors='none',
    hatches=['.', '/', '\\', None, '\\\\', '*'],
    extend='lower',
)

# create a legend for the contour set
artists, labels = cs.legend_elements()
# Set the bbox so the legend appears outside the axes
plt.legend(artists, labels, handleheight=2, bbox_to_anchor=(1.04, 1), loc="upper left")

plt.title('Before')
plt.savefig("mpl_test_before.jpeg", bbox_inches="tight")

# ------------------------------
# New code that handles changing the color of hatches

colors = ['maroon', 'red', 'darkorange', 'gold', 'forestgreen',
          'darkturquoise', 'dodgerblue', 'darkviolet']
hatches=['.', '/', '\\', None, '\\\\', '*']
artists = []
labels = []
# Loop over level pairs (note, contourf needs at least 2 levels to fill between)
for level in range(len(levels)-1):
    cs = plt.contourf(
         x, y, z, levels[level:level+2], colors='none',
         hatches=[hatches[level % len(hatches)]],
         extend='lower',
         )
    # Set edgecolor for this level
    cs.set_edgecolor(colors[level % len(colors)])
    # Handle creating legend with colors of hatches as in the figure
    artist, label = cs.legend_elements()
    # For each level, we set the color of its hatch in the legend too
    artist[0].set_edgecolor(colors[level % len(colors)])
    # Doing this also colors in the bounding box around each level in the legend
    # We can remove the colored line in the legend by setting the linewidth to 0
    artist[0].set_linewidth(0.)
    # Add to lists of artists, labels
    artists.extend(artist)
    labels.extend(label)

# Create a legend for the contour set
plt.legend(artists, labels, handleheight=2, bbox_to_anchor=(1.04, 1), loc="upper left")

# ---------------
plt.title('After')
plt.savefig("mpl_test_after.jpeg", bbox_inches="tight")
```
![image](https://github.com/user-attachments/assets/2bdf5744-9bb3-4ea5-9d18-e19a886b2687)
