### ISSUE TITLE
[Bug]: 'imshow' is adding a random blue line to my images 

### ISSUE THREAD

**Issue by smackird** [matplotlib/matplotlib#27897]
### Bug summary

'imshow' is creating a blue diagonal line overlaying what should be plain black and white data.  The line does not correspond to any data in my JSON input.

### Code for reproduction

```Python
# Step 1: Load the JSON file
        file_path = os.path.join(os.getcwd(), 'output_array.json')
        with open(file_path) as f:
            data = json.load(f)

        # Find the maximum 'x' and 'z' values in the JSON data
        max_x = max(int(item['x']) for item in data)
        max_z = max(int(item['z']) for item in data)

        # Step 2: Convert the list of dictionaries into a 2D numpy array
        array = np.zeros((max_x + 1, max_z + 1), dtype=bool)
        for item in data:
            x = int(item['x'])
            z = int(item['z'])
            value = int(item['value'])
            array[x][z] = value

        # Step 3: Use matplotlib's imshow function to display the array as an image
        plt.imshow(array, cmap='gray_r', interpolation='none')

        # Step 4: Save the image to a .png file using matplotlib's savefig function
        plt.savefig('output_array.png')
```

### Actual outcome

![output_array](https://github.com/matplotlib/matplotlib/assets/134182384/b06b03ba-3534-4147-9ea4-fec58a257469)

The plot is creating a blue line from x=0, z=1 to x=3, z=3 in all of my PNG outputs.

### Expected outcome

A black and white plot of values with no blue line

### Operating system

Win 10 Pro

### Matplotlib Version

matplotlib==3.8.3

### Matplotlib Backend

TkAgg

### Python version

Python 3.10.13

### Installation

pip

**Comment by rcomer** [comment]
Thank you for the report @smackird.  Could you provide a self-contained code example that we can run to reproduce the problem?

**Comment by rcomer** [comment]
I am going to close this.  Without a reproducing example we cannot investigate.  @smackird if you can provide such an example we can re-open.
