### ISSUE TITLE
[Bug]: Minor ticks become major ticks when minor ticks are set only

### ISSUE THREAD

**Issue by ZhaJiMan** [matplotlib/matplotlib#27919]
### Bug summary

When I set minor ticks only using `ax.set_xticks(xticks, minor=True)`, it turns out that they become major ticks. And minor ticks are located at other places. Is this behaviour reasonable?

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.tick_params(which='major', length=10, width=2, color='r')
ax.tick_params(which='minor', length=5, width=2, color='b')
ax.set_xticks(np.linspace(0, 1, 5), minor=True)
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/54382968/1ca5d777-1771-4135-9eba-48d85854502b)

### Expected outcome

Ticks at `[0.0, 0.2, 0.4, 0.6, 0.8, 1.0]` should be blue and short.

### Operating system

Windows

### Matplotlib Version

3.8.2

### Matplotlib Backend

TkAgg

### Python version

3.11.5

### Installation

conda

**Comment by QuLogic** [comment]
`np.linspace(0, 1, 5) == array([0.  , 0.25, 0.5 , 0.75, 1.  ])` so the minor ticks are at the expected places. And the `minor` parameter to `set_xticks` only determines whether that method affects the major or minor ticks. It does not turn off the major ones; those are at the default locations.

**Comment by ZhaJiMan** [comment]
My question is, the minor ticks are at the expected places indeed, but they adopt the appeareance of major ticks (long and red). And if I use

```Python
ax.set_xticks([0, 1])
ax.set_xticks(np.linspace(0, 1, 5), minor=True)
```

![image](https://github.com/matplotlib/matplotlib/assets/54382968/87610fc0-18ff-43f9-87bf-6cf82903fe91)

Now the result meets my expectation. But I cannot understand the behaviour without setting major ticks.

**Comment by QuLogic** [comment]
Those blue minor ticks are there in your original post. The major ticks are at the default locations.

The major ticks are also there in red on your second post, just not in the middle, because that's where you said to put them this time.

**Comment by ZhaJiMan** [comment]
Thanks for your explanation and patience.
I just made a stupid typo in `np.linspace` and confused the locations of minor ticks with the default locations of major ticks.
