### ISSUE TITLE
[ENH]: Adding Irregular Features to the Patches Module

### ISSUE THREAD

**Issue by Impaler343** [matplotlib/matplotlib#27980]
### Feature
I just found out that there are no ready-made shapes defined for **Irregular Shapes** or **Petal-Like** shapes. There exists features like _PathPatch_ and _Polygon_ where you specify vertices and plot the needed figure, but it would be too cumbersome to construct it from scratch. I'm assuming splotch-like figures will have a wide range of applications in domains like geography/cartography, biology or to represent a cluster on a plot.
With this method we can only make roughly radially symmetric figures. I feel it would be a valuable addition to the library, but suggestions are always welcome :)

### Additional Features
- We can increase the number of harmonics to increase irregularity
- We can increase the number of points in each wave(Increase H) to increase the number of petals
- We can change the range of _rho_ to increase or decrease the size of the petal

### Proposed solution

```
import numpy as np
import matplotlib.pyplot as plt

# Randomize amplitude and phase.
H1 = 4
rho1 = np.random.uniform(0.5, 1.0, H1) * np.logspace(-0.5, -2.5, H1)
H2 = 4
rho2 = np.random.uniform(0.5, 1.0, H2) * np.logspace(-0.5, -2.5, H2)
H3 = 4
rho3 = np.random.uniform(0.5, 1.0, H3) * np.logspace(-0.5, -2.5, H3)
H4 = 4
rho4 = np.random.uniform(0.5, 1.0, H4) * np.logspace(-0.5, -2.5, H4)

rho = np.concatenate((rho1, rho2, rho3, rho4))

H=H1+H2+H3+H4
# Accumulate r(t) over t=[0,2*pi]
t = np.linspace(0, 2 * np.pi, 101)
r = np.ones_like(t)
for h in range(H):
    r += rho[h] * np.sin(h * t)

# Reconstruct x(t), y(t)
x = r * np.cos(t)
y = r * np.sin(t)

# Plot r(t) vs t
plt.figure()
plt.plot(t, r, "r-")
plt.xlabel("t, radians")
plt.ylabel("r(t)")

# Plot x(t) and y(t)
plt.figure()
plt.plot(0, 0, "ko")
plt.plot(np.cos(t), np.sin(t), "k--")
plt.plot(x, y, "b-")
plt.xlabel("x(t)")
plt.ylabel("y(t)")
plt.axis("equal")

plt.show()
``` 

### Plot
![image](https://github.com/matplotlib/matplotlib/assets/73378019/f50ec635-fdb1-4c46-8817-a36b88ca71ab)

**Comment by timhoffm** [comment]
Do you have real-world example plots (e.g. from papers) what you want to achieve? Also, "irregular shapes or petal-like shapes" is quite broad. What are the parameters / API you would want?

Overall, from what I've understood so far, I have the impression that this is quite complex and/or only relevant to a certain domain. If that's the case a 3rd party library would be more appropriate than core matplotlib.

**Comment by Impaler343** [comment]
I was hinting at making another shape in the hatches module which would be an irregular shape. There are no research papers in general aimed at using this, but I've used lateX a lot to write applications and there exists an ```\irregularcircle``` function to do this. An irregular closed figure would also be used in say plotting the Gravel Hatch pattern:
![image](https://github.com/matplotlib/matplotlib/assets/73378019/4cd6f063-8132-43d4-a4d9-39164e42992c)

Say you want to plot something like an amoeba, you need to specify many points to draw this:
![image](https://github.com/matplotlib/matplotlib/assets/73378019/08c63d89-c5d2-4eba-8998-68a766c5227a)


By petals, I meant to say that the irregular figures can amount to somewhat regular ones like a flower by tweaking a few parameters. The concept of irregular shapes seemed like a functionality a core library should have, but yes this also sounds a bit niche. It is like including a readymade ```plus hatch``` option in addition to making available ```horizontal hatch``` and ```vertical hatch``` options which can be superimposed to give the grid hatch anyway.

Some API specifications include:

- A IrregularCircle class in the patches module 
- Changes can be made to the size, irregularity, number of petals(1 would mean a single irregular circle), border color and fill color
- Or we could do a marker named IrregularCircle with the standard marker specifications

**Comment by timhoffm** [comment]
I'd claim that such features do not fall under our [mission statement](https://matplotlib.org/stable/users/project/mission.html):

> provide data visualization tools for the Scientific Python Ecosystem.

Amoeba or island generation is more general graphics rather than data visualization. The gravel hatch could be used for data visualization, but IMHO there's no advatage compared to regualar hatches, so I don't see a case for putting the extra effort in to support that.

The [search for "latex \irregularcircle"](https://www.google.com/search?client=firefox-b-d&sca_esv=920940ff3dbc57d7&q=latex+%5Cirregularcircle&nfpr=1&sa=X&ved=2ahUKEwiMqpWi6ZaFAxW6gv0HHWmBBXYQvgUoAXoECAcQAw&biw=1299&bih=1002&dpr=1.3) suggests it's not a standard feature but a custom macro somebody has written.

I'm colsing this as not planned, because this is quite clearly not core functionality. For the drawing functions, creating a 3rd-party package is the right way to go. For hatching, a first step (and of more general interest) would be to improve the hatching API and support custom hatches; see #20690.

**Comment by tacaswell** [comment]
I agree with closing this as the API is too fluid and irregular to be a good fit upstream.


In examples in our docs:

 - https://matplotlib.org/stable/gallery/event_handling/path_editor.html#sphx-glr-gallery-event-handling-path-editor-py
 - https://matplotlib.org/stable/gallery/event_handling/poly_editor.html#sphx-glr-gallery-event-handling-poly-editor-py

that show how to interactively specify the shape which you can the pull back out and serialize.

----

In my PhD I actually had to solve exactly this problem (mostly low frequency vibrations on a circle so not _completely_ irregular).  Please reserve judgement on ~12 year old code, but I solved this problem by having an class that held a spline (that specified the shape) and then wrapping that class + a Line2D in class that managed both interactively https://github.com/tacaswell/leidenfrost/blob/78abcd84d3d2d2d4ecf15d0c77d1eeb86f5ab3e0/leidenfrost/infra.py#L334-L413 (again, please don't judge too harshly).

**Comment by Impaler343** [comment]
Interesting, spline fitting is probably the way to go if when dealing with irregular structures then!, this was too niche
