### ISSUE TITLE
[Bug]: subplot2grid not working correctly

### ISSUE THREAD

**Issue by RemiDav** [matplotlib/matplotlib#27994]
### Bug summary

When updating from 3.6.2 to 3.8.3, subplot2grid started having issues with displaying the plots.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, axlist = plt.subplots(4,1,figsize = (6,6))
ax_top = plt.subplot2grid((4, 1), (0, 0))
ax_top.set_xticks([])
ax = plt.subplot2grid((4, 1), (1, 0), rowspan=3)    
plt.show()
```

### Actual outcome

This is the output with 3.8.3

![image](https://github.com/matplotlib/matplotlib/assets/1755739/37202035-afe5-46ae-94e0-2501225471f8)

### Expected outcome

This is the output with 3.6.2

![image](https://github.com/matplotlib/matplotlib/assets/1755739/6185592a-9cad-46cc-a0c9-22f1f43a440b)

### Operating system

Windows

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.11

### Installation

conda

**Comment by rcomer** [comment]
Hi @RemiDav this is an intentional change: the axes you created with `subplots` are no longer automatically removed when you place new axes on top of them with `subplot2grid`.  You should have seen a warning about this change when you ran with v3.6.2.  I think you can get what you want with

```python
import matplotlib.pyplot as plt

fig = plt.figure(figsize = (6,6))
ax_top = plt.subplot2grid((4, 1), (0, 0))
ax_top.set_xticks([])
ax = plt.subplot2grid((4, 1), (1, 0), rowspan=3)    
plt.show()
```

**Comment by jklymak** [comment]
We purposely stopped removing overlapping axes.  So your axes created by the first call to subplots are not removed by your subsequent calls to subplot2grid. 

The solution is to not call the first call to subplots. 

I'm going to close as this is expected behaviour.  But feel free to request a reopen if there is some compelling reason you need both layers of calls
