### ISSUE TITLE
[Bug]: FancyArrowPatch: can't add more than one artist or patch

### ISSUE THREAD

**Issue by rdpeterson100** [matplotlib/matplotlib#28010]
### Bug summary

Code that worked in python2 for displaying or animating 3D arrows doesn't work if more than one arrow is displayed.

### Code for reproduction

```Python
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.patches import FancyArrowPatch
from mpl_toolkits.mplot3d import proj3d

class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        #super().__init__((0,0), (0,0), *args, **kwargs)                #either
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)   #one works
        self._verts3d = xs, ys, zs

    def do_3d_projection(self, renderer=None):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))

        #return np.min(zs)

#lines for axes
axis_x = np.linspace(-1.2, 1.2, 101)
axis_y = np.linspace(-1.2, 1.2, 101)
axis_z = np.linspace(-1.2, 1.2, 101)
axis_zero = np.zeros(101)

fig = plt.figure()
#make it a 3D figure, set limits
ax = fig.add_subplot(111, projection='3d')
ax.set_aspect("equal")
ax.set_xlim((-1.2,1.2))
ax.set_ylim((-1.2,1.2))
ax.set_zlim((-1.2,1.2))
ax.view_init(30,30)
#plot x, y, z axes
ax.plot(axis_x, axis_zero, axis_zero, 'k')
ax.plot(axis_zero, axis_y, axis_zero, 'k')
ax.plot(axis_zero, axis_zero, axis_z, 'k')
ax.text(1.4, 0, 0, 'x')
ax.text(0, 1.25, -0.05, 'y')
ax.text(0.07, 0, 1.3, 'z')
#plot two 3D arrows
##cartesian
a1 = Arrow3D([0, 1], [0, 0], [0, 0], mutation_scale=20, lw=2, arrowstyle="-|>", color="b")
a2 = Arrow3D([0, -1], [0, 0], [0, 0], mutation_scale=20, lw=2, arrowstyle="-|>", color="r")
ax.add_artist(a1)
ax.add_artist(a2)

plt.show()
```

### Actual outcome

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 1233, in _on_timer
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/backend_macosx.py", line 71, in callback_func
    callback()
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/backend_macosx.py", line 94, in _draw_idle
    self.draw()
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/backend_macosx.py", line 53, in draw
    super().draw()
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 472, in draw
    for artist in sorted(collections_and_patches,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### Expected outcome

It should plot 3D axes with a blue arrow pointed along the +x axis and a red arrow pointed along the -x axis.

### Additional information

This error doesn't happen if I just comment out either one of these lines in the code:
ax.add_artist(a1)
ax.add_artist(a2)
So I can get either the blue arrow along +x axis or the red arrow along the -X axis, but not both.

### Operating system

OS/X

### Matplotlib Version

3.8.3

### Matplotlib Backend

MacOSX

### Python version

3.11.5

### Jupyter version

none (I think) ==> command not found: jupyter

### Installation

pip

**Comment by ksunden** [comment]
You have commented out the return value of `do_3d_projection`, which is used to determine the draw order, that is what is being sorted.

Without this, it is getting the default return of `None`, and trying to compare it. If there is only one, there is no problem and no need to sort a single item, but otherwise we need to.

Uncommenting the return makes it work.

**Comment by rdpeterson100** [comment]
Thank you!!! This script works, and now I can get all my animations to work also!

I confess, I took some of that script from an online example, so I didn't know what it was doing. I commented out the return line because at some point in my experimentation, everything seemed to work without it.

*But I don't get it: it doesn't seem to matter what I return. I can return min (xs, ys, or zs). I can even do "return 0", and everything works (even my animations, which are much more complicated). 
Anything at all can be returned (except for 'None'), and everything works fine?

Anyway in case you're interested, my animations use FancyArrowPatch to generate 3D arrows, and FuncAnimation. This part of the script was what finally got them to work:

def do_3d_projection(self, renderer=0):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        return np.min(zs)
        if self.mask == False:
            FancyArrowPatch.draw(self, renderer)

**Comment by ksunden** [comment]
It is important that it returns a number, as that is what is used to sort it.

The number returned helps determine in what order things are drawn, If you return other numeric values it will still work, but some things that should be "behind" others may be drawn on top, and thus the more complicated scene you have, the more likely it is to draw things non-sensibly. With two arrows pointing directly opposite, this is not likely to be much of a problem, unless you are looking directly end on (at which point the arrow shape itself is not super visible). 

But returning None means that the comparison is trying to compare whether None < None, which does not work.

**Comment by rdpeterson100** [comment]
OK, thanks again for the help and the explanation!
