### ISSUE TITLE
[Bug]: Why does the exported svg image use a non-vector graphic internally, and how do I export it as a full vector image?

### ISSUE THREAD

**Issue by lw404-ai** [matplotlib/matplotlib#28018]
### Bug summary

Why does the exported svg image use a non-vector graphic internally, and how do I export it as a full vector image?

### Code for reproduction

```Python
plt.savefig(f"../figure/model_name.svg", format="svg", bbox_inches='tight')
```

### Actual outcome
![1712218449463.png](https://s2.loli.net/2024/04/04/sGCkZpuzTdeNW5A.png)
![1712218444228.png](https://s2.loli.net/2024/04/04/sUcwWYm3MZ82479.png)

### Expected outcome

Individually editable svg for each element

### Matplotlib Version

3.7.2

### Installation

pip

**Comment by timhoffm** [comment]
Does this help? https://matplotlib.org/stable/gallery/misc/rasterization_demo.html

**Comment by WeatherGod** [comment]
What platform are you using and what backend? What is producing those
messages?

**Comment by lw404-ai** [comment]
> Does this help? https://matplotlib.org/stable/gallery/misc/rasterization_demo.html

It doesn't work, I set rasterized=False, but the color block inside the output svg is still a pixel map and not a vector map

**Comment by lw404-ai** [comment]
```python
plt.imshow(data_matrix*100, cmap='RdYlGn', interpolation='nearest', aspect='auto', extent=[0, 35, 0, 29], rasterized=False)
```

**Comment by jklymak** [comment]
Imshow creates a raster graphic that is then put in the svg (or PDF or EPS). If you want a vector mesh, then use pcolormesh.  

I'm going to close as Matplotlib is behaving as expected here.  For further help please use discourse.matplotlib.org.

**Comment by lw404-ai** [comment]
> Imshow creates a raster graphic that is then put in the svg (or PDF or EPS). If you want a vector mesh, then use pcolormesh.
> 
> I'm going to close as Matplotlib is behaving as expected here. For further help please use discourse.matplotlib.org.

Thank you for successfully solving the problem. It's my fault. I should use pcolormesh instead of imshow. Thank you so much. : )
