### ISSUE TITLE
[Bug]: Unexpected ylim of stairs with baseline=None

### ISSUE THREAD

**Issue by rogerbalsach** [matplotlib/matplotlib#28016]
### Bug summary

I am not sure if this is a bug or a feature:
I wanted to do the following plot:
![image](https://github.com/matplotlib/matplotlib/assets/59893197/0435e50f-d9d4-41e4-ab60-de390f8530f1)

which can be done using the stairs method with `baseline=None` since I don't want the vertical lines in the extremes. But the plot I get is the following:
![image](https://github.com/matplotlib/matplotlib/assets/59893197/576e32ed-35fa-40ac-8b35-fdd4090b3753)

As I was saying, I don't know if this is the expected behaviour of stairs, but I cannot think of a case where one would like to have the lower limit fixed to 0.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

bins = [0, 2, 3, 5, 10]
x = [1.148, 1.231, 1.248, 1.25]

# Plot using stairs
plt.stairs(x, edges=bins, baseline=None)

# Plot using step, which is less convenient, but handles the limits correctly
# plt.step(bins, (*x, x[-1]), where='post')

# plt.ylim(1.1429, 1.2551)
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/59893197/576e32ed-35fa-40ac-8b35-fdd4090b3753)

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/59893197/0435e50f-d9d4-41e4-ab60-de390f8530f1)

### Additional information

The problem originates from the lines inside the stairs function
```
if baseline is None:
    baseline = 0
if orientation == 'vertical':
    patch.sticky_edges.y.append(np.min(baseline))
    self.update_datalim([(edges[0], np.min(baseline))])
else:
    patch.sticky_edges.x.append(np.min(baseline))
    self.update_datalim([(np.min(baseline), edges[0])])
```

I think that the sticky_edges should not be used when baseline is None. If that is not possible for some other reason, setting `baseline = values` instead of 0 would probably be more intuitive, or something like `baseline = (1 + self._ymargin) * np.min(values) - self._ymargin * np.max(values)`.

### Matplotlib Version

3.7.1

### Installation

None

**Comment by timhoffm** [comment]
> I think that the sticky_edges should not be used when baseline is None.

I agree. Do you want to create a pull request with a fix?

**Comment by QuLogic** [comment]
I think the documentation of the parameter is a bit lacking of what `baseline=None` means as well; is it really "no baseline"? Also, what happens with `fill=True`?

**Comment by timhoffm** [comment]
`None` really means no baseline, it leaves out the horizontal edges at the far left and right side. That can be desirable in certain situations. It's a feature. And yes fill becomes awkward in that case, see #26752.

If we want something else, https://github.com/matplotlib/matplotlib/issues/26752#issuecomment-1719178161 would be a reasonable extension.

**Comment by rogerbalsach** [comment]
> I agree. Do you want to create a pull request with a fix?

I don't have the time right now to do a PR in conditions, so if anyone else wants to implement this, go ahead. Otherwise, I can give it a shot in 1 or 2 months when I have some free time.

**Comment by DiogoCasteloCardoso** [comment]
I can create a PR for this issue
