### ISSUE TITLE
[Bug]: pcolorfast should validate that regularly spaced X or Y inputs have the right size

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28059]
### Bug summary

Currently, when X/Y are passed to pcolorfast and are regularly spaced arrays, pcolorfast just uses their first and last values for the image extents, without verifying that the coordinate sizes are actually correct.

### Code for reproduction

```Python
from pylab import *
gca().pcolorfast(arange(5), arange(13), np.random.rand(20, 20))  # or whatever sizes
```

### Actual outcome

no error

### Expected outcome

a validation error

### Operating system

any

### Matplotlib Version

3.9.0.dev1479+g8d3dfce637

### Matplotlib Backend

any

### Python version

3012

### Jupyter version

no

### Installation

git checkout

**Comment by elijahcantu** [comment]
@anntzer working on this right now.

**Comment by mnmarinaccio** [comment]
Apologies if I am misunderstanding the problem. When you say verifying that the coordinate sizes are actually correct, can you elaborate a bit more?

I understand that you mean this issue occurs if you have two regularly spaced arrays for X and Y, such as X = [1, 2, 3, 4] and Y=[2, 4, 6, 8, 10]. When those are used for example, the coordinate sizes should look like what? Do you mean the spacing of the values on each axis?
