### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sophiamaedler** [matplotlib/matplotlib#28066]
### Bug summary

ax.bar raises an exceptionwhen passed only nan data. This irrevocably breaks seaborn's histogram function (which draws and then removes a "phantom" bar to trip the color cycle). Seems to be a repeat of https://github.com/matplotlib/matplotlib/issues/24127 

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.bar([np.nan], [np.nan])
```

### Actual outcome

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[7], line 7
      5 import matplotlib.pyplot as plt
      6 f, ax = plt.subplots()
----> 7 ax.bar([np.nan], [np.nan])

File ~/mambaforge/envs/stitching/lib/python3.10/site-packages/matplotlib/__init__.py:1465, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1462 @functools.wraps(func)
   1463 def inner(ax, *args, data=None, **kwargs):
   1464     if data is None:
-> 1465         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1467     bound = new_sig.bind(ax, *args, **kwargs)
   1468     auto_label = (bound.arguments.get(label_namer)
   1469                   or bound.kwargs.get(label_namer))

File ~/mambaforge/envs/stitching/lib/python3.10/site-packages/matplotlib/axes/_axes.py:2451, in Axes.bar(self, x, height, width, bottom, align, **kwargs)
   2449 x0 = x
   2450 x = np.asarray(self.convert_xunits(x))
-> 2451 width = self._convert_dx(width, x0, x, self.convert_xunits)
   2452 if xerr is not None:
   2453     xerr = self._convert_dx(xerr, x0, x, self.convert_xunits)

File ~/mambaforge/envs/stitching/lib/python3.10/site-packages/matplotlib/axes/_axes.py:2244, in Axes._convert_dx(dx, x0, xconv, convert)
   2232 try:
...
   1713                        "support generators as input")
   1714 else:
-> 1715     return next(val for val in obj if safe_isfinite(val))

StopIteration:
```

### Expected outcome

On a linux machine running the same version of matplotlib this returns a BarCollection with one Rectangle, having nan for x and height. 

information on the linux system on which the code works:
matplotlib version: matplotlib: 3.8.4
installed with conad

python version

```
Python version
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Version info.
sys.version_info(major=3, minor=10, micro=14, releaselevel='final', serial=0)
```

### Additional information

seems to be a repeat of this issue: https://github.com/matplotlib/matplotlib/issues/24127

### Operating system

MacOS 14.4.1

### Matplotlib Version

3.8.4

### Matplotlib Backend

import matplotlib.pyplot as plt plt.imshow(image[0])

### Python version

3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ] Version info. sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)

### Installation

conda

**Comment by ksunden** [comment]
I am unable to reproduce this on my mac, and I'm struggling to think what would be platform dependent here in the first place.

We have a test for this and have not seen it failing, so I'm quite confused.

**Comment by rcomer** [comment]
@sophiamaedler just to be absolutely certain, could you add

```python
import matplotlib
print(matplotlib.__version__)
```
in the top of your script and make sure you are running with the version you think you are?

**Comment by jklymak** [comment]
I'll close as this is likely a crossed install.
