### ISSUE TITLE
[Doc]: Is there documentation for generating images with alt-text?

### ISSUE THREAD

**Issue by balajialg** [matplotlib/matplotlib#28060]
### Documentation Link

https://matplotlib.org/devdocs/api/matplotlib_configuration_api.html

### Problem

I've searched extensively for documentation on adding alt-text to images but couldn't find any relevant information despite looking through listed methods and using search terms like 'alt' and 'alt-text'. Could you kindly direct me to the appropriate documentation for this feature? If it's not yet implemented, could you please point me to the specific issue tracking this request?

### Suggested improvement

Adding the necessary information would be helpful

**Comment by timhoffm** [comment]
This is not implemented yet. See #24309.
