### ISSUE TITLE
[Bug]: matplotlib suddenly starts to trouble with datetieme objects

### ISSUE THREAD

**Issue by e-duard2** [matplotlib/matplotlib#28113]
### Bug summary

I am having unexpected troubles while trying to plot a 2D plot (matplolib.pyplot.plot) where the x axes are datetime values.

This behaviour is unexpected as I've coded similar scirpts in the past and I have never experienced such isue. Furthermore, if I place the fragment (or a similar fragment) at the very top of my script it works. But if I place agaign the same fragment at the very end it makes python to crash

### Code for reproduction

```Python
Please see my public fork of my repo where it crashes:

https://github.com/e-duard2/GNSS_DOP_BUG
```

### Actual outcome

Traceback (most recent call last):
  File "ruta_al_archivo/practica2.py", line 109, in <module>
    plt.plot(datetime_vector, GDOP)
  File "ruta_a_matplotlib/pyplot.py", line 3590, in plot
    return gca().plot(
           ^^^^^^^^^^^
  File "ruta_a_mplot3d/axes3d.py", line 1622, in plot
    self.auto_scale_xyz(xs, ys, zs, had_data)
  File "ruta_a_mplot3d/axes3d.py", line 613, in auto_scale_xyz
    self.xy_dataLim.update_from_data_xy(
  File "ruta_a_transforms.py", line 951, in update_from_data_xy
    path = Path(xy)
           ^^^^^^^^
  File "ruta_a_path.py", line 129, in __init__
    vertices = _to_unmasked_float_array(vertices)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ruta_a_cbook.py", line 1345, in _to_unmasked_float_array
    return np.asarray(x, float)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'datetime.datetime'

### Expected outcome

a pyplot plot

### Additional information

It makes no sense at all the fragment that stops working, works fine by itself on another .py file, but when joined in the main it stops working

### Matplotlib Version

matplotlib-3.8.4

### Matplotlib Backend

TkAgg

### Python version

Python 3.12.2

### Installation

pip

**Comment by e-duard2** [comment]
I have come arround the error by saving the data in a csv and then executing a sencond .py which reads the data and plots it correctly. I really makes no sense to me and I have spend one day debugging with no results.
![DOP](https://github.com/matplotlib/matplotlib/assets/108635283/0ef29d9e-632b-4df0-9cac-29131b2b59eb)

**Comment by rcomer** [comment]
When you use `pyplot.plot` you plot to the current axes, if there is one.  In this case you have created a 3D axes here:
https://github.com/e-duard2/GNSS_DOP_BUG/blob/d2c7eff03b76c32cb625f89ab32fb71160f82a2a/practica2.py#L53

but I think you want a 2D axes?

**Comment by e-duard2** [comment]
Hi!

Thank you very much for your help. Indeed `ax = plt.figure().add_subplot(projection='3d')` was placed by error as I used a previous main as template for this one. By removing this line, the issue was solved.

However, I am quite curious why this was causing trouble as I was not using a figure for plotting the target plot.
Do you have any insights about this? I wasted a great deal of time doing debugging and analysing the documentation and I did not came across to any solid answer.

Cheers

**Comment by rcomer** [comment]
Anything you plot with Matplotlib is using a figure, but when you use pyplot it does it for you behind the scenes.  You may find it less confusing to move away from pyplot and use the explicit interface, where you keep track of these things yourself: https://matplotlib.org/stable/users/explain/figure/api_interfaces.html

I’m glad you got it sorted.  I’m going to close this one as it does not show a bug in Matplotlib itself.
