### ISSUE TITLE
[Bug]: matplotlib pyplot creates a broken plot when long

### ISSUE THREAD

**Issue by estebanuri** [matplotlib/matplotlib#28137]
### Bug summary

Very long plots are broken 
As explained [here](https://stackoverflow.com/questions/78384983/matplotlib-pyplot-creates-a-broken-plot-when-long)

The plot has a broken containing frame.

### Code for reproduction

```Python
from matplotlib import pyplot as plt
import numpy as np

def plot(w, h):

    num_samples = int(w * h)
    x = w * np.random.rand(num_samples)
    y = h * np.random.rand(num_samples)
    plt.figure(figsize=(w, h))
    plt.xticks(range(w))
    plt.xlim(0, w)
    plt.ylim(0, h)
    plt.scatter(x, y)
    plt.grid()

plot(450, 3)
```

### Actual outcome

The plot has a broken containing frame.

![image](https://github.com/matplotlib/matplotlib/assets/9130985/dd544e03-221f-48c8-a597-9c4ae218ad21)

Note that

1. the lines of the containing frame are kind of dashed?
2. there are scatter dots outside the containing frame.

### Expected outcome

A correct plot,
for example if the function is invoked with smaller width the result is correct.

plot(5, 3)

![image](https://github.com/matplotlib/matplotlib/assets/9130985/c47fd4bb-e19d-44c8-910f-4f5c9a0fec2e)
 

### Operating system

OS/X, Ubuntu

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12

### Jupyter version

6.5.5

### Installation

pip

**Comment by jklymak** [comment]
It's probably possible to rewrite agg to allow larger images, but someone would have to put in the work 

As for work arounds, it would be helpful to specify why you need a figure that is 12 m (42 feet) long. The reason this never gets fixed is because such a huge figure is usually not desired.

**Comment by estebanuri** [comment]
@jklymak here I provide an extract of a real plot. 
x axis represents the time, y axis represents speed in km/h of a vehicle.
![image](https://github.com/matplotlib/matplotlib/assets/9130985/8224f45d-9653-4d77-89ea-d99758a9406c)
Notice that the displayed fonts are perfectly readable, that represents hour minutes and seconds, measured in local time.

Sure, I could create a software approach by drawing the results by tiles, this will require to create a website or to bundle the results with a software to be installed (what I can't / wouldn't want to do). I usually send the zipped image by email, so anyone can analyze it using a standard image viewer.

**Comment by rcomer** [comment]
What format do you send the images in?  I tried saving a png from the example in the OP.  It seemed to save OK but my image viewer (Eye of Gnome on Ubuntu) threw an error saying it could not display images that large.

**Comment by estebanuri** [comment]
@rcomer I save the images in .png.
I'd have to test it on linux. Currently I'm using Mac, with the default image preview application.
I have no problem visualizing with that, but I'd guess that other open source applications for image manipulation shouldn't have any problem to handle these kind of images.

**Comment by jklymak** [comment]
The fonts are readable because you have zoomed in. If you look at the whole image at once it will not be readable. 

Again this is a limitation of Matplotlib Agg renderer.  I don't think we would object to someone doing the work to relax this constraint.  However it is not currently a high priority because it is usually not desired.

**Comment by scottshambaugh** [comment]
Closing as a duplicate as https://github.com/matplotlib/matplotlib/issues/26368, which has some more discussion in it.
