### ISSUE TITLE
[ENH]: Add fill between support for 3D plots

### ISSUE THREAD

**Issue by gerazov** [matplotlib/matplotlib#28142]
### Problem

I couldn't make fill between to work for my 3D plot of a unit circle with a spectrogram sitting on top. 

I went through the example on the website (https://matplotlib.org/stable/gallery/mplot3d/polys3d.html) but couldn't adapt it to my plot.

### Proposed solution

Finally I found a repo that implements a `fill_between_3d` function and I could easily make it work.
![image](https://github.com/matplotlib/matplotlib/assets/15214418/70be5975-9371-4795-9537-28b40542ea4a)

Please consider adding it to `matplotlib`.

**Comment by scottshambaugh** [comment]
This looks very useful, and the referenced code is MIT licensed and thus could be brought directly in to matplotlib without issues. @artmenlope would you be interested in that?

**Comment by scottshambaugh** [comment]
As a side note @gerazov, do you have a link to the code you used to generate that plot? It's very nice!

**Comment by gerazov** [comment]
Thanks! It took me a while to make it :sweat_smile: 

If it makes sense I can create a PR for your examples section?
