### ISSUE TITLE
gid="sth" get lost if rasterized=True is set in hexbin

### ISSUE THREAD

**Issue by mjamroz** [matplotlib/matplotlib#2816]
Fragment below will write id="element" into the svg 

```
plt.hexbin(x,y, cmap=plt.cm.YlOrRd_r,gid="element")
plt.savefig("img.svg")
```

which is as we could expect, but 

```
plt.hexbin(x,y, cmap=plt.cm.YlOrRd_r,gid="element",rasterized=True)
plt.savefig("img.svg")
```

results in <image tag with different id (something like id="image9f9a4ebdcc")

(i am submitting new issue as tcaswell@stackoverflow suggested

**Comment by QuLogic** [comment]
The `gid` is added to _something_, a group that appears to contain one path definition and a _lot_ of clip path groups. There doesn't seem to be anything in that group, so it seems to be wasting space for what should be the image.

**Comment by QuLogic** [comment]
So when set to rasterized, there appears to be _both_ the rasterized image and that other group with the actual `gid` is the vector one underneath.

**Comment by mjamroz** [comment]
@QuLogic  thanks for commenting on this PR, it reminded me what i was working on 6 years ago :)
