### ISSUE TITLE
[Bug]: mathtext should distinguish between unary and binary minus

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28180]
### Bug summary

TeX inserts a (thin?) space after a binary minus, but not before a unary minus.  Typographically, I believe this does look nicer.
mathtext does not distinguish the two cases and always puts in a thin space.  It would be nice if it followed tex's behavior.

### Code for reproduction

```Python
from pylab import *
figtext(.2, .6, "$a=-b-c$")
figtext(.2, .5, "$a=-b-c$", usetex=True)
```

### Actual outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/1322974/a42a6019-eea7-4bc3-9397-fb2cafe4dc2c)
Compare the spacing before the "b" and the "c": they are different with usetex, but not with mathtext.

### Expected outcome

Remove the space in mathtext before the unary minus.

### Additional information

Probably involves reading the TeXbook to figure out what is TeX's logic for distinguishing unary and binary minus.
Tagging as good first issue *solely* because there should be no API design at all, but medium (-hard) difficulty because that'll require both reading the TeXbook and learning about mathtext's implementation.  However I would guess there's no "strong" technical blockers either.

### Operating system

any

### Matplotlib Version

3.10.0.dev137+g9387431ab6

### Matplotlib Backend

qtagg

### Python version

3.12

### Jupyter version

no

### Installation

git checkout

**Comment by OdileVidrine** [comment]
I did some preliminary research and it seems TeX actually does not distinguish between the unary and binary minus symbol. Maybe I was reading an outdated version of the TeXbook, but I cannot find any mention of unary operators. I will keep looking to find out what logic TeX is using to change the spacing for unary operators.

**Comment by anntzer** [comment]
Another example where I think the difference is clear:
![Figure_1](https://github.com/matplotlib/matplotlib/assets/1322974/4fafabc6-0475-4cbd-808a-584b2a8c6a69)

**Comment by OdileVidrine** [comment]
I have found the issue, the code contains logic to do different spacing for unary minus if the unary minus happens directly after a parenthesis or if the minus is the first character in the equation, but the code does not contain logic to create a unary minus after an equals sign. It is an easy fix, but I am still working on setting up a testing environment to verify my fix.
