### ISSUE TITLE
[Doc]: ConnectionError when using intersphinx: https://matplotlib.org/stable/objects.inv

### ISSUE THREAD

**Issue by amotl** [matplotlib/matplotlib#28197]
### Documentation Link

https://matplotlib.org/stable/objects.inv

### Problem

When linking to the matplotlib documentation using intersphinx, we have been able to observe those errors since yesterday night.
```
Warning, treated as error:
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://matplotlib.org/stable/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
Command exited with exit code: 2
```

The problem can be reproduced easily using curl or HTTP. This command sporadically also emits a connection error, and only succeeds occasionally.
```
$ http https://matplotlib.org/stable/objects.inv

http: error: ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) while doing a GET request to URL: https://matplotlib.org/stable/objects.inv
```

It's probably something related to Cloudflare?

**Comment by tacaswell** [comment]
Is this still occurring?  We don't see anything suspicious in the CF logs and can not reproduce.

Are you behind an additional proxy where this is occurring?

**Comment by amotl** [comment]
Hi again. Indeed, it looks like my current line connection has a bad reputation with CF. The same thing also happens with those inventories:

- https://pandas.pydata.org/pandas-docs/stable/objects.inv
- https://numpy.org/doc/stable/objects.inv

Thus, I am confident that it is only me who is observing those hiccups. If anything similar suspicious might come up in the future, people may find this issue back, and eventually continue to investigate. For now, closing this, sorry for the noise.
