### ISSUE TITLE
[MNT]: scale of the quiver does  not print the actually value  till after the figure pop up.

### ISSUE THREAD

**Issue by ahmedshaaban1** [matplotlib/matplotlib#28214]
### Summary

All, 
I am trying to print the value fo the automated scale being calculated by the quiver as the following:

```
plt.close('all’)
fig, ax = plt.subplots(1,2)
axl=ax[0].quiver(x, y, U, V,  angles='uv',scale_units='width')
ax[0].set_title('scale_units=width \n scale='+str(axl.scale))
print('left figure scale '+str(axl.scale))
print('left figure scale_units '+axl.scale_units)
axr=ax[1].quiver(x, y, U, V,  angles='uv',scale_units='height')
ax[1].set_title('sacle_units=height \n scale='+str(axl.scale))
print('right figure scale '+str(axl.scale))
print('left figure scale_units '+axl.scale_units)
fig.tight_layout()
```

Yet, as printed on the console and shown in the figure title, the scale is None, which I know is not the true value. 
>>left figure scale None
>> right figure scale None
![Figure_1](https://github.com/matplotlib/matplotlib/assets/15742456/62b88da8-4f42-4e89-82dd-42a6d34c1ee0)

### Proposed fix

After the figure popped up, I printed the scale again, and I got the correct answer. 
```
print('left figure scale '+str(axl.scale))
print('right figure scale '+str(axr.scale))
```

I got 
right figure scale 127.27922061357857
right figure scale 189.83025409097942

Is it expected that we only obtain the true scale value after the figure pops up on the scale?

**Comment by jklymak** [comment]
Thats because we don't know the scale until we know the axes limits, which we dont' know until you stop drawing things.  Call `figure.draw_without_rendering` if you need this number and cannot specify.  

I'll close here - further discussion is welcome at discourse.matplotlib.org.
