### ISSUE TITLE
[Bug]: "fill_between" not showing on some PDF readers when using "alpha"

### ISSUE THREAD

**Issue by yannickdengler** [matplotlib/matplotlib#28215]
### Bug summary

When using the "fill_between_function" and alpha in a log-log-plot and "extrapolate" by putting the first data point to [0,0], the resulting graph does not show on some PDF readers (including Zotero on mobile devices and the default reader on Android). I know that you should probably not use zeros in a log plots but it works fine when the alpha is set to default (=1). 

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(4,1, sharex=True,sharey=True)
fig.set_figheight(15)
fig.set_figwidth(4)
ax[0].fill_between([1,100], [10,100], [100,1000], color = "orange", label = "Plot 1")
ax[0].fill_between([1,100], [2,20], [20,200], color = "green", label = "Plot 2")
ax[1].fill_between([1,100], [10,100], [100,1000], color = "orange", alpha = 0.7, label = "Plot 1")
ax[1].fill_between([1,100], [2,20], [20,200], color = "green", alpha = 0.3, label = "Plot 2")
ax[2].fill_between([0,1,100], [0,10,100], [0,100,1000], color = "orange", label = "Plot 1")
ax[2].fill_between([0,1,100], [0,2,20], [0,20,200], color = "green", label = "Plot 2")
ax[3].fill_between([0,1,100], [0,10,100], [0,100,1000], color = "orange", alpha = 0.7, label = "Plot 1")
ax[3].fill_between([0,1,100], [0,2,20], [0,20,200], color = "green", alpha = 0.3, label = "Plot 2")

plt.xlim([1,100])
plt.ylim([1,2000])
ax[0].set_title("no 0 no alpha")
ax[1].set_title("no 0 but alpha")
ax[2].set_title("0 no alpha")
ax[3].set_title("0 and alpha")
ax[0].legend()
ax[1].legend()
ax[2].legend()
ax[3].legend()
ax[0].grid()
ax[1].grid()
ax[2].grid()
ax[3].grid()
plt.xscale("log")
plt.yscale("log")

plt.savefig("bug.pdf")
plt.show()
```

### Actual outcome

The fourth panel of the plot will not show on some PDF readers. On most readers it will probably show.

[bug.pdf](https://github.com/matplotlib/matplotlib/files/15292498/bug.pdf)

### Expected outcome

I would expect that the fourth panel looks just like the second panel.

### Operating system

Ubuntu

### Matplotlib Version

3.5.2

### Matplotlib Backend

GTK4Agg

### Python version

GTK4Agg

### Installation

pip

**Comment by jklymak** [comment]
This seems like a viewer problem. We clip objects to have something like x=1e-13, y=1e-13 to take care of this.  If you have hit a PDF viewer that can't render that but most do, then I think this is a bug for them, not us.  particularly as we clip the artist by default...
<img width="550" alt="Ex" src="https://github.com/matplotlib/matplotlib/assets/1562854/ff61534d-b232-4fa2-a8c6-84aceb38ad82">

My vote would be to close this as "Can't fix/Downstream fix required"
