### ISSUE TITLE
[Bug]: Inconsistent Visualization of Intervals in ax.barh for Different Duration Widths

### ISSUE THREAD

**Issue by AndreasLR** [matplotlib/matplotlib#28223]
### Bug summary

**Issue Description:**

When using ax.barh to visualize intervals, the function fails to display all intervals under certain conditions, which appears to be linked to the width of the intervals specified as duration. Specifically, intervals with a duration of 3 hours are not displayed properly, while increasing the duration to 5 hours results in correct visualization. This issue suggests a potential problem with how interval widths are handled or rendered in ax.barh.

**Steps to Reproduce:**
Refer to "code for reproduction"

**Expected Behavior:**

All intervals should be visualized consistently, regardless of their duration width.

**Actual Behavior:**

Intervals with a shorter duration (3 hours) are not visualized correctly, while longer durations (5 hours) are displayed as expected.

### Code for reproduction

```Python
from datetime import datetime, timedelta
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

duration = timedelta(hours=3)
# duration = timedelta(hours=5)
ax.barh(y=0, width=duration, left=datetime(2024, 1, 1, 6))
ax.barh(y=1, width=duration, left=datetime(2024, 1, 1, 1))

plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('bug.png')
```

### Actual outcome

Only one of two bars is rendered.
![image](https://github.com/matplotlib/matplotlib/assets/78612439/9ad98184-b0bb-4f8d-a976-043ceab01e70)

### Expected outcome

I expect both bars to appear:
![image](https://github.com/matplotlib/matplotlib/assets/78612439/e3833e42-0869-4c93-95c7-be81adc576bc)

### Operating system

Ubuntu and Manjaro

### Matplotlib Version

3.8.4

### Matplotlib Backend

agg

### Python version

3.11.8

### Installation

pip

**Comment by tacaswell** [comment]
This is a bug with the auto-limits as first bar starts immediately on the  right limit

If you draw the edges on the patches:

```python
ax.barh(y=0, width=duration, left=datetime(2024, 1, 1, 6), lw=10, ec='k')
ax.barh(y=1, width=duration, left=datetime(2024, 1, 1, 1), lw=10, ec='k')
```

you can see the left edge of the blue bar peaking out

![bug](https://github.com/matplotlib/matplotlib/assets/199813/90bce6a1-477c-481f-bcf2-e0605a18dcbd)


Why making the orange bar long enough to overlap "fixes" it is very surprising to me.

**Comment by tacaswell** [comment]
If you pan (or manually set the limits) the second bar renders correctly, it is just that it is off screen by default.

**Comment by QuLogic** [comment]
We discussed this on a call, and the problem isn't with units, but with the relative size of the positions vs the widths of the bars (i.e., when dates are made unitless, they are positioned at ~20000 vs a width of < 1 for hours). This causes some poor interaction with sticky edges. @ksunden will be opening a PR shortly.
