### ISSUE TITLE
[ENH]: Request for linestyle='.' and linestyle='.-' in plt.plot

### ISSUE THREAD

**Issue by Hari-Shankar-Karthik** [matplotlib/matplotlib#28245]
### Problem

It gets difficult to remember whether it is ls='-.' or ls='.-' for the alternating dash and dot linestyle in plt.plot. Similarly for the dotted line, I feel that ls='.' makes far more sense than ls=':'.

### Proposed solution

It is a really simple fix. All one needs to do is add appropriate OR conditions in the correct places. I would be happy to do it if you would allow so. Thanks!

**Comment by timhoffm** [comment]
Thanks for the suggestion.

Note that the long name (which I belive was taken from TeX) is "dashdot", so "-." makes sense. I'm +/-0 on adding '.-', but I'm inclined if we do that, it should not be an alias, but the line should start with the dot then as well.

I'm -1 on adding '.' as an alias to ':'. While `plot(x, y, ls='.')` could be made to work. The shorthand markerformat `plot(x, y, '.')` is already reserved for the dot-marker, so it would not work there and that incongruence would be more confusing than just having to learn ':' is the shorthand for a dotted line.

**Comment by Hari-Shankar-Karthik** [comment]
OK thank you! I was not aware of the existing convention in LaTeX and MATLAB.
