### ISSUE TITLE
[Doc]: Sphinx gallery links mispointed for Axes3D methods 

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib#28250]
### Documentation Link

https://matplotlib.org/devdocs/gallery/mplot3d/lines3d.html#sphx-glr-gallery-mplot3d-lines3d-py

### Problem

The `Axes3D` methods which are automatically linked in example code in the docs all incorrectly point towards the `Axes` methods instead.

For example `ax.plot` [here](https://matplotlib.org/devdocs/gallery/mplot3d/lines3d.html#sphx-glr-gallery-mplot3d-lines3d-py) links to [matplotlib.axes.Axes.plot](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.plot.html#matplotlib.axes.Axes.plot) instead of [mpl_toolkits.mplot3d.axes3d.Axes3D.plot](https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.plot.html#mpl_toolkits.mplot3d.axes3d.Axes3D.plot)
![image](https://github.com/matplotlib/matplotlib/assets/14363975/6c53d962-e8c0-459d-a93f-a6bd8c021826)

### Suggested improvement

Not sure if there's a way to type hint this in all the example code, or somehow make Sphinx recognize this.

**Comment by scottshambaugh** [comment]
Good find @story645 I'll give that a shot!

**Comment by scottshambaugh** [comment]
Did not work unfortunately

**Comment by larsoner** [comment]
Unfortunately not. It is a bit of a rabbit hole and I have to spend a lot of time to figure out why it does the wrong thing sometimes. In theory it should look at the `__class__` of the instance and resolve  `mpl_toolkits.mplot3d.axes3d.Axes3D` properly, not sure why it wouldn't. Maybe becaues of the `mpl_toolkits` namespace instead of `matplotlib` or something?

**Comment by QuLogic** [comment]
sphinx-gallery 0.17.0 is out now with the above fix, so this should be fixed the next time the docs are built.

**Comment by scottshambaugh** [comment]
Is there an example of a working docs build to check this? I'm not seeing one at the moment in the pipelines.

**Comment by QuLogic** [comment]
Unfortunately, 0.17.0 also broke some things, so there hasn't been a working build on CircleCI; I am discussing fixes with upstream right now, so it might have to wait for 0.17.1.

**Comment by QuLogic** [comment]
Sorry, looking at it again, this isn't fixed yet even with 0.17.0. It turns out that I've only fixed multiple modules if resolving via intersphinx, i.e., when you are _using_ Matplotlib. It didn't fix things for when you're building something and it consists of multiple modules.
