### ISSUE TITLE
Installing the matplotlib along with tensorflow in python 3.6.0 

### ISSUE THREAD

**Issue by abdullahhaidary** [matplotlib/matplotlib#28264]
### **Hello there**, 
**Currently i am working on a machine learning project which has to be done in python 3.6.0 which is an old version, i have installed tensorflow, pandas and numpy libraries but the problem i am having is with installing matplotlib, when i install it i see an error such as below :** 

{
C:\Users\PC\PycharmProjects\TensorFlow\.venv\Scripts\python.exe C:\Users\PC\PycharmProjects\TensorFlow\main.py 
Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\TensorFlow\main.py", line 2, in <module>
    import tensorflow as tf
  File "C:\Users\PC\PycharmProjects\TensorFlow\.venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\PC\PycharmProjects\TensorFlow\.venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\PC\PycharmProjects\TensorFlow\.venv\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\PC\PycharmProjects\TensorFlow\.venv\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\PC\PycharmProjects\TensorFlow\.venv\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\abc.py", line 158, in register
    if issubclass(subclass, cls):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):

  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\typing.py", line 860, in __extrahook__
    if issubclass(subclass, scls):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\abc.py", line 197, in __subclasscheck__
    if subclass in cls._abc_cache:
RecursionError: maximum recursion depth exceeded while calling a Python object

Process finished with exit code 1
}

**but when i uninstall the matplotlib everything works fine.** 

**below is the list of packages i am having in the python** 

absl-py==0.15.0
astunparse==1.6.3          
backcall==0.2.0            
cached-property==1.5.2     
cachetools==4.2.4          
certifi==2024.2.2          
charset-normalizer==2.0.12 
clang==5.0                 
colorama==0.4.5            
cycler==0.11.0             
dataclasses==0.8           
decorator==5.1.1           
flatbuffers==1.12          
gast==0.4.0                
google-auth==2.22.0        
google-auth-oauthlib==0.4.6
google-pasta==0.2.0        
grpcio==1.48.2             
h5py==3.1.0                
idna==3.7                  
importlib-metadata==4.8.3  
ipykernel==5.5.6
ipython==7.16.3
ipython-genutils==0.2.0
jedi==0.17.2
jupyter-client==6.1.12
jupyter-core==4.9.2
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.7
matplotlib @ file:///C:/Users/PC/Documents/python_assets/matplotlib-2.0.2-cp36-cp36m-win_amd64.whl
numpy==1.19.5
oauthlib==3.2.2
opt-einsum==3.3.0
pandas==0.25.3
parso==0.7.1
pickleshare==0.7.5
Pillow==8.4.0
prompt-toolkit==2.0.1
protobuf==3.19.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
Pygments==2.14.0
pyparsing==3.0.7
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==305
pyzmq==25.1.2
requests==2.27.1
requests-oauthlib==2.0.0
rsa==4.9
six==1.15.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.8.0
tensorflow-gpu @ file:///C:/Users/PC/Documents/tensorflow/tensorflow_gpu-2.6.0-cp36-cp36m-win_amd64.whl
termcolor==1.1.0
tornado==6.1
traitlets==4.3.3
typing-extensions==3.7.4.3
urllib3==1.26.18
wcwidth==0.2.13
Werkzeug==2.0.3
wrapt==1.12.1
zipp==3.6.0

**Comment by scottshambaugh** [comment]
It looks like you have installed matplotlib v2.0.2, which is an extremely old version from 2017. The most recent version of matplotlib compatible with python 3.6 is version 3.3.4 from 2021, as listed on this page: https://matplotlib.org/devdocs/devel/min_dep_policy.html#list-of-dependency-min-versions

You may be able to fix your issue by installing that version: `pip install matplotlib==3.3.4`

If that doesn't work then could you please link the installation procedure you are following for the project?

**Comment by tacaswell** [comment]
Do you have a traceback that includes Matplotlib?  That looks like it is all TF + protobuf.  

One thing that is very strange to me is that you are hitting two different set of paths in

```
...
from google.protobuf import descriptor as _descriptor
File "C:\Users\PC\PycharmProjects\TensorFlow.venv\lib\site-packages\google\protobuf\descriptor.py", line 47, in
from google.protobuf.pyext import _message
File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\abc.py", line 158, in register
...
```

One is in your venv the other looks like a global install.  My initial reaction is that this is either an installation error (where you are somehow seeing chimera environments) or a bug in what ever you used to make the venv (or both), but my expectations for how this works may be wrong on windows.

**Comment by abdullahhaidary** [comment]
> pip install matplotlib==3.3.4

**Comment by abdullahhaidary** [comment]
**Thanks from everyone** 

I found that the problem was with pyparsing==3.0.7 and i solved it by uninstalling and then installing the pyparsing=2.4.7 as pip `install pyparsing==2.4.7`
the referencing answer can be found at the link : [](https://stackoverflow.com/questions/69964466/unknown-version-in-python-library-pyparsing?newreg=d4d630e2b0f943d5b7209e4f048853c2)
