### ISSUE TITLE
polar rgb imshow xticks issue

### ISSUE THREAD

**Issue by rubenvb** [matplotlib/matplotlib#2827]
I'm currently trying to plot an HSV legend, i.e. a circle of color that becomes white as the radius goes to 0. I also posted this question on [stackoverflow](http://stackoverflow.com/questions/21935888/fixing-polar-rgb-imshow-xticks) in the hope of getting a clever workaround.

Code:

```
def complex_to_rgb(complex_data, invert=False):
  from numpy import angle, max, pi, sin, zeros
  phase = angle(complex_data)
  amplitude = abs(complex_data)
  amplitude = amplitude/max(max(amplitude))
  A = zeros((complex_data.shape[0], complex_data.shape[1], 3))
  A[:,:,0] = .5*(sin(phase)+1)*amplitude
  A[:,:,1] = .5*(sin(phase+pi/2)+1)*amplitude
  A[:,:,2] = .5*(-sin(phase)+1)*amplitude
  if(invert):
    return 1-A
  else:
    return A

import numpy as np
from matplotlib.pyplot import figure

N = 1024
x = np.linspace(-1, 1, N)
y = np.linspace(-1, 1, N)

X,Y = np.meshgrid(x,y)

R = np.sqrt(X*X + Y*Y)
PHI = np.arctan2(Y, X)

fig = figure()
ax = fig.add_subplot(111, polar=True)

ax.imshow(complex_to_rgb(R*np.exp(1j*PHI)  * (R<1), invert=True))

ax.set_xticks([-.5, 0, np.pi/2, np.pi, 3*np.pi/2])#-.5)
ax.set_yticks([0, N/3, 2*N/3, N])

ax.set_xticklabels(['', '$0$', r'$\pi/2$', r'$\pi$', r'$3\pi/2$'])
ax.set_yticklabels([])

fig.show()
```

Problem is, if I change the -.5 xtick (e.g. to +.5), the plot gets messed up and I get division by zero warnings:

```
....\lib\site-packages\matplotlib\image.py:161: RuntimeWarning: divide by zero encountered in double_scalars
  sy = dyintv/viewlim.height
....\lib\site-packages\matplotlib\image.py:190: RuntimeWarning: divide by zero encountered in double_scalars
  sy = dyintv/viewlim.height
```

I don't want the -.5 arbitrary tick mark. Why does a tick mark influence the drawing of an image?

**Comment by tacaswell** [comment]
@QuLogic As long as you are touching polar axes could you have a look at this bug as well?

**Comment by QuLogic** [comment]
As you say, it seems this bug has to do with how `imshow` does not work on polar axes. As the `imshow` appears to be ignored, the view limits are empty. Setting additional ticks triggers something that makes the view nonsingular.

Setting radial limits will fix the division issues, as will my PR at this time, but it doesn't yet fix the problem with `imshow`.

**Comment by QuLogic** [comment]
So, `imshow` is a little weird, in that it doesn't seem to do any transform on the actual data, _but_ the extent is defined in _data_ coordinates.

The problem is that the _default_ extent is to place the pixel centres on integers. For the 1024x1024 image above, that gives -0.5 to 1023.5 in both dimensions. By default, anything outside the limits will be transformed to `nan`, so the image probably gets clipped out of existence. When adding the additional tick, the data limits allow that -0.5 so it's no longer clipped.

Anyway, the short of it is that if you set reasonable data extents, it should work correctly. That is, use `ax.imshow(data, extent=(0, 2*np.pi, 0, 1024))` and it should work on 1.4.3 and master.

**Comment by rubenvb** [comment]
I can confirm @QuLogic's workaround works. Does it make sense to make the extent be set automatically for a polar Axes or would that make little sense?

**Comment by tacaswell** [comment]
@QuLogic Has the commit that fixes this been merged to master/what PR is it on?

**Comment by QuLogic** [comment]
The commit that's linked here is in #4699, but it doesn't fix the plot here. It's only for a small warning that arises from it.

The "fix" is to tweak `imshow`'s default extents so it doesn't pick something unreasonable on a polar plot. I guess this can be done by default, maybe using a wrapper in `PolarAxes`?

**Comment by tacaswell** [comment]
I can no longer get this do do anything sensible on the current master..
