### ISSUE TITLE
problem with pip install under Python 3.13.0b1 on Win 11 [Bug]: 

### ISSUE THREAD

**Issue by alan-isaac** [matplotlib/matplotlib#28286]
### Bug summary

Install fails.

### Code for reproduction

```Python
py -3.13 -m pip install matplotlib
```

### Actual outcome

install fails

### Expected outcome

install succeeds

### Additional information

Installation under 3.12 succeeds, but not under 3.13.

### Operating system

Windows 11

### Matplotlib Version

3.9

### Python version

3.13

### Installation

pip

**Comment by tacaswell** [comment]
I have been able to compile Matplotlib with the 3.13 prerelease (and the CPython main branch) on linux so this is either platform specific or due missing local build dependencies.

**Comment by alan-isaac** [comment]
```
       File "C:\Users\xxxx\AppData\Local\Temp\pip-build-env-x57h_93z\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\alani\AppData\Local\Temp\pip-build-env-x57h_93z\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
```

**Comment by tacaswell** [comment]
That is not enough context, nor is it clear from those lines if this is an issue with Matplotlib or one of our dependencies (which very likely don't have py313 wheels on pypi yet).

**Comment by alan-isaac** [comment]
> That is not enough context, nor is it clear from those lines if this is an issue with Matplotlib or one of our dependencies (which very likely don't have py313 wheels on pypi yet).

I edited the comment to add all the context I have. If you need something else, you will need to guide me.

**Comment by jklymak** [comment]
Does pip install pillow work?  If not, then that is the root of your problem

**Comment by ianthomas23** [comment]
Related pillow issue is python-pillow/Pillow#8075 which has been fixed but not released yet.

**Comment by alan-isaac** [comment]
> Does pip install pillow work? If not, then that is the root of your problem

No, `pip install pillow` does not work.

**Comment by QuLogic** [comment]
Alright, I'll close as this isn't a problem with Matplotlib.

**Comment by tacaswell** [comment]
Oh, I did come across that pillow bug, sorry for not remembering.
