### ISSUE TITLE
[Bug]: plt.imshow displays a non-zero array as all zeros

### ISSUE THREAD

**Issue by kailicao** [matplotlib/matplotlib#28281]
### Bug summary

I was trying to visualize a non-zero array (please unzip and see [test.zip](https://github.com/matplotlib/matplotlib/files/15409055/test.zip)) with `plt.imshow`.
However, `plt.imshow` displays it as all zeros, unless I set unreasonably small (in terms of absolute values) `vmin` and `vmax`.
Let's call this array `test`. Slices like `test[::2, ::2]` can be shown correctly, but `plt.imshow` does not work for `test`.

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt

with open('test.npy', 'rb') as f:
    test = np.load(f)

# this is what this array looks like
plt.imshow(test[::2, ::2], cmap='bwr', vmin=-0.05, vmax=0.05, origin='lower')
plt.tight_layout()
plt.savefig('slice.png')
plt.show()

# this is the issue I'm reporting
plt.imshow(test, cmap='bwr', vmin=-0.05, vmax=0.05, origin='lower')
plt.tight_layout()
plt.savefig('issue.png')
plt.show()
```

### Actual outcome

`# this is what this array looks like`
![slice](https://github.com/matplotlib/matplotlib/assets/89794465/940871fd-f18d-4f89-be89-de6e0fe361e5)

`# this is the issue I'm reporting`
![issue](https://github.com/matplotlib/matplotlib/assets/89794465/ac5763e9-1c91-492a-8aaf-a99652b84234)

### Expected outcome

`issue.png` is expected to look similar to `slice.png`, with higher (double in both directions) resolution.

### Additional information

Sorry, I have no idea.

### Operating system

Windows 11

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.11.7

### Jupyter version

7.0.8

### Installation

conda

**Comment by jklymak** [comment]
You are aliasing your image.  The right behaviour depends a bit on your taste, and the default is actually slated to change, but in the meantime, you may want to look at https://matplotlib.org/stable/gallery/images_contours_and_fields/image_antialiasing.html

I'd recommend `imshow(..., interpolation_stage='data', interpolation='nearest')` if you want something to show.  But the real solution is to make your data smaller or your image larger.

**Comment by jklymak** [comment]
I'm going to close this, as its expected behaviour and well understood, and the default is likely to change.  However, feel free to continue discussing if the above link is not clear.

**Comment by kailicao** [comment]
Sorry for my late reply. `imshow(..., interpolation_stage='data', interpolation='nearest')` does solve the issue, thank you. Just to clarify, I deliberately used the default setting (i.e., removed my customization) to make this issue report as concise as possible.
