### ISSUE TITLE
[Doc]: Missing comma

### ISSUE THREAD

**Issue by simond07** [matplotlib/matplotlib#28296]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.plot.html

### Problem

A comma is missing in the second list item of ‘Plot multiple data sets’:
If x and/or y are 2D arrays **insert comma here** a separate data set will be drawn for every column. 

### Suggested improvement

If x and/or y are 2D arrays, a separate data set will be drawn for every column.

**Comment by timhoffm** [comment]
Closed by #28297
