### ISSUE TITLE
[Bug]: matplotlib broke compatibility with get_cmap in new release (3.9)

### ISSUE THREAD

**Issue by servoz** [matplotlib/matplotlib#28317]
### Bug summary

matplotlib broke compatibility with get_cmap in new release (3.9).

### Code for reproduction

```Python
$ python
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.9.0'
>>> from matplotlib.cm import get_cmap
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (C:\Python39-x64\lib\site-packages\matplotlib\cm.py)
```

### Actual outcome

ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (C:\Python39-x64\lib\site-packages\matplotlib\cm.py)

### Expected outcome

no exception.

### Operating system

linux Fedora40

### Matplotlib Version

3.9

### Python version

3.12

### Installation

pip

**Comment by timhoffm** [comment]
This is an intended API change. The functionality was deprecated since version 3.7.

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#deprecation-of-top-level-cmap-registration-and-access-functions-in-mpl-cm

**Comment by servoz** [comment]
Oh thank you for your quick reply.
I'm sorry, I didn't see the MatplotlibDeprecationWarning before!
