### ISSUE TITLE
[Bug]: subfigures are added in column major order

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28344]
### Bug summary

subplots() adds axes in row-major order, but subfigures() add subfigures in column-major order

### Code for reproduction

```Python
from pylab import *

f = figure()
f.subplots(3, 3)
for i, ax in enumerate(f.axes): ax.set_title(i)
savefig("/tmp/subplots.png")

f = figure()
f.subfigures(3, 3)
for i, sf in enumerate(f.subfigs): sf.suptitle(i)
savefig("/tmp/subfigures.png")
```

### Actual outcome

subplots
![subplots](https://github.com/matplotlib/matplotlib/assets/1322974/0f972af4-492c-4621-941b-440cd9dab208)

subfigures
![subfigures](https://github.com/matplotlib/matplotlib/assets/1322974/56b98e97-2b2c-476f-acd7-e9ebe2716ecb)

### Expected outcome

Subfigures are added in row-major axis, per standard numpy defaults.

### Additional information

In practice this should rarely matter, as the subfigures don't overlap so drawing order should be irrelevant... perhaps unless some artists are positioned beyond the subfigure edge and not clipped.

The behavior directly arises from the iteration in subfigures:
```python
        sfarr = np.empty((nrows, ncols), dtype=object)
        for i in range(ncols):
            for j in range(nrows):
                sfarr[j, i] = self.add_subfigure(gs[j, i], **kwargs)
```

### Operating system

macOS

### Matplotlib Version

3.10.0.dev233+ga833d99e46

### Matplotlib Backend

qtagg

### Python version

3.12

### Jupyter version

no

### Installation

git checkout

**Comment by tacaswell** [comment]
I am in favor of flipping `subfigures` to match `subplots`.   I think this is a case where we can not warn, but should just do it (and clearly document it).  I hope this won't bite too many people who are relying on the iteration order and get us out of explaining why it is different forever.

**Comment by tacaswell** [comment]
It should also be noted that subfigures as of 3.9 (I think) now respect z-order so you can move them up and down if you have to.
