### ISSUE TITLE
[Bug]: barh plot has inverted y-axis by default

### ISSUE THREAD

**Issue by aaronchucarroll** [matplotlib/matplotlib#28361]
### Bug summary

Creating a barh plot results in the categories iterating from bottom to top. Inverting the y axis manually using ```plt.gca().invert_yaxis()``` results in a more expected and readable plot. I believe this should be the default behavior.

### Code for reproduction

```Python
categories = ['Category A', 'Category B', 'Category C', 'Category D']
values = [10, 24, 36, 15]

plt.figure(figsize=(10, 5))

plt.bar(categories, values)
plt.show()

plt.barh(categories, values)
plt.show()
```

### Actual outcome

<img width="994" alt="Screenshot 2024-06-08 at 11 08 49 AM" src="https://github.com/matplotlib/matplotlib/assets/120818400/b65894be-55ef-4fe2-86da-993000f48fd1">
<img width="861" alt="Screenshot 2024-06-08 at 11 09 07 AM" src="https://github.com/matplotlib/matplotlib/assets/120818400/e0759ed2-53fb-4a04-b44d-d214cf46a3b2">

### Expected outcome

With ```plt.gca().invert_yaxis()```,
<img width="975" alt="Screenshot 2024-06-08 at 11 20 31 AM" src="https://github.com/matplotlib/matplotlib/assets/120818400/9f5f0d0f-5adf-42df-bb54-fbf7a3e61a2b">

### Matplotlib Version

3.9.0

### Python version

3.12.3

### Installation

pip

**Comment by aaronchucarroll** [comment]
I am working on a fix

**Comment by timhoffm** [comment]
Thanks for the proposal. However, this is intended behavior. As with `bar()` the bars are placed in ascending coordinate direction. There‘s no canonical right way here. We‘re not going to change the order, because backward compatibility weights much than a subjective expectation.

**Comment by jklymak** [comment]
This seems a taste issue, not a bug?  While I agree that we usually read from the top of a page to the bottom, graphs are typically read from bottom to top, particularly in the default case of the y values being numbers.
