### ISSUE TITLE
[Bug]: Backend entry points can be erroneously duplicated

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#28367]
### Summary

Under certain circumstances outside of our control, an `entry_points`-registering backend such as `matplotlib-inline` can appear as two entry points so that we raise a `RuntimeError(f"Entry point name '{name}' duplicated")`. Reported on [Matplotlib Discourse](https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/6).

### Proposed fix

The `BackendRegistry` purposefully does not allow multiple entry points with the same name as it has no way to know which one to prefer. This has now caused a problem in the linked discussion when using system python 3.9 and a virtual environment on Rocky 9.4 Linux. Although there is only a single `entry_points.txt` file for e.g. `matplotlib-inline` the system python `importlib.metadata.entry_points` erroneously returns two identical items. I think this is because the virtualenv has both a `lib` directory and a `lib64` symlink to the `lib` directory, and this particular combination of Linux distribution, python version and use of `venv` does not check that they both refer to the same file. Regardless of where the problem really lies here, Matplotlib needs to be able to deal with it.

I'll submit a PR later in the week. I think the simplest change is to allow (i.e. discard) entry points that have the same `group` (e.g. `matplotlib.backend`), `name` (e.g. `inline`) and `value` (e.g. `matplotlib_inline.backend_inline`), and then raise if there are multiple entry points of the same `group` and `name` but different `value`.

**Comment by barguzin** [comment]
Not sure if this will be helpful, but I get the same error with Windows 11 set-up, Python 3.9 mamba environment. 

Matplotlib version 3.9.0.
Jupyter Lab version: 4.2.2

I have tried doing the force-reinstall using ```pip install --upgrade --force-reinstall matplotlib numpy==1.26.4 --user```, and it seems to import without any errors. However, after rebooting the PC, I get the same runtime error: RuntimeError: Entry point name 'inline' duplicated.

**Comment by ianthomas23** [comment]
@barguzin This has been fixed and will be in the next release.
