### ISSUE TITLE
[Bug]: AffineDeltaTransform does not appear to invalidate properly

### ISSUE THREAD

**Issue by joe-saronic** [matplotlib/matplotlib#28372]
### Bug summary

Based on https://github.com/matplotlib/matplotlib/pull/28364, the scaling transformations do not update properly when axes are zoomed in the example. Given that location does change and the scales are computed correctly, it follows that `AffineDeltaTransform` is most likely not updating correctly.

### Code for reproduction

Run example in https://github.com/matplotlib/matplotlib/pull/28364 in an interactive session. Zoom in.

Initial (unzoomed plot):

![image](https://github.com/matplotlib/matplotlib/assets/156837150/2dbf7caf-0713-442e-ac57-c9a0ba09bc86)

### Actual outcome

The on-screen size of the circle patches remains the same in pixels.

![image](https://github.com/matplotlib/matplotlib/assets/156837150/ac184d66-6956-43a3-a0b1-be8a99e0278e)

### Expected outcome

The circle patches should scale to maintain a constant height in data space while remaining circles.

![image](https://github.com/matplotlib/matplotlib/assets/156837150/1b1cd644-ad2e-4cf8-8ac5-097a04b04ea3)

### Additional information

Consistent in a couple of different venvs with recent versions on Linux

### Matplotlib Version

3.8.2

### Matplotlib Backend

QtAgg (PyQt6)

### Python version

Python 3.10.12

### Jupyter version

N/A

### Installation

pip

**Comment by anntzer** [comment]
Thanks for the report.  The fix appears to be
```patch
diff --git i/lib/matplotlib/transforms.py w/lib/matplotlib/transforms.py
index 5003e21139..e6e7a6bca6 100644
--- i/lib/matplotlib/transforms.py
+++ w/lib/matplotlib/transforms.py
@@ -2711,9 +2711,12 @@ class AffineDeltaTransform(Affine2DBase):
     This class is experimental as of 3.3, and the API may change.
     """

+    pass_through = True
+
     def __init__(self, transform, **kwargs):
         super().__init__(**kwargs)
         self._base_transform = transform
+        self.set_children(transform)

     __str__ = _make_str_method("_base_transform")
```
although I can't put my finger exactly on what are the cases where pass_through = True is required (but this is consistent with the other transform-wrapper classes).

**Comment by joe-saronic** [comment]
Ah. I figured out the `set_children` part but missed `pass_through` in my experiments. Would you like to submit a PR, or should I?

________________________________

**Comment by joe-saronic** [comment]
My experiments show that `pass_through` appears to make the delta transform be always invalid. Even when I call `get_matrix()`, which nominally sets `self._invalid = 0`, the invalid status is immediately reset to `2`
