### ISSUE TITLE
[Bug]: subfigure artists not drawn interactively

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#28384]
### Bug summary

When artists are added to a subfigure in interactive mode, they do not appear until I force a draw by resizing the window.

### Code for reproduction

```Python
$ ipython --matplotlib=qt
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt

In [2]: fig = plt.figure()

In [3]: sfig1, sfig2 = fig.subfigures(ncols=2)

In [4]: sfig2.suptitle("My Title")
Out[4]: Text(0.5, 0.98, 'My Title')

In [5]: ax = sfig1.subplots()

In [6]: ax.plot([1, 3, 2])
Out[6]: [<matplotlib.lines.Line2D at 0x73a220908ce0>]
```

### Actual outcome

Apparently empty figure
![image](https://github.com/matplotlib/matplotlib/assets/10599679/c6f531b3-cdb1-4af3-89ad-7f8d24c322b5)

### Expected outcome

If I resize the window, the artists appear
![image](https://github.com/matplotlib/matplotlib/assets/10599679/223737ec-3f78-4d58-9e3c-c2bff4833a85)

### Operating system

Ubuntu

### Matplotlib Version

`main`

### Matplotlib Backend

QtAgg and TkAgg

### Python version

3.12.3

### Installation

git checkout

**Comment by tacaswell** [comment]
Very likely the issue is that `obj.stale` is not propogating up from the sub-figure to the parent.

**Comment by jklymak** [comment]
Huh. I never use interactive mode so didn't test that! Seems a pretty big oversight.  Thanks for finding.

**Comment by tacaswell** [comment]
```diff

diff --git a/lib/matplotlib/figure.py b/lib/matplotlib/figure.py
index 9139b2ed26..9f764cc233 100644
--- a/lib/matplotlib/figure.py
+++ b/lib/matplotlib/figure.py
@@ -1636,6 +1636,8 @@ default: %(va)s
         sf = SubFigure(self, subplotspec, **kwargs)
         self.subfigs += [sf]
         sf._remove_method = self.subfigs.remove
+        sf.stale_callback = _stale_figure_callback
+        self.stale = True
         return sf
 
     def sca(self, a):

```

is the fix.  I don't have time right now to add a test etc.  I'll try to get to it later today but will not be at all angry if someone takes over.

**Comment by rcomer** [comment]
Full disclosure: this is how far I got
https://github.com/matplotlib/matplotlib/compare/main...rcomer:matplotlib:subfigure-stale

Currently the last line of the test fails.  I tried and failed to create an example to show that this matters.

Sorry, I probably should have commented right after I did this to avoid duplicating effort.

**Comment by tacaswell** [comment]
Ah, no worries.  I was feeling guilty that my initial comment had too little detail and I was wasting your time digging!

I think waiting for #28177 to land might make sense, but it is not critical as either way, the thing that triggers the automatic re-rendering is the stale state of the top-level figure (via https://github.com/matplotlib/matplotlib/blob/b19794e126c1077b83eba90fe74ab1f67362b1ba/lib/matplotlib/_pylab_helpers.py#L124-L131 which is called either via https://github.com/matplotlib/matplotlib/blob/b19794e126c1077b83eba90fe74ab1f67362b1ba/lib/matplotlib/pyplot.py#L298 after executing a cell/line in IPython or https://github.com/matplotlib/matplotlib/blob/b19794e126c1077b83eba90fe74ab1f67362b1ba/lib/matplotlib/pyplot.py#L1062-L1063 in plain Python)

**Comment by rcomer** [comment]
Thanks @tacaswell!  So, when the top `Figure` is re-drawn, does it re-draw all the artists on it, or just those ones that are currently marked "stale"?
