### ISSUE TITLE
[ENH]: A "Center" extent for imshow()

### ISSUE THREAD

**Issue by SemihGuner** [matplotlib/matplotlib#28396]
### Problem

Currently, an end user can only calculate coordinates from a corner of the images shown. [Source: Matplot's wiki](https://matplotlib.org/stable/users/explain/artists/imshow_extent.html#default-extent) . People may need to use the center of the given image for various reasons, such as educational material (drawing functions from origin point) or bounding box drawing, where the coordinate are given via the middle point of the image.

### Proposed solution

origin='center' parameter should be added to imshow() where it takes the (0,0) point to the middle of the plot.

**Comment by timhoffm** [comment]
How should that work? The index (0, 0) is at a corner of index space. Any reasonable mapping should map the index space to the complete drawing rectangle. Hence the origin has to be in a corner and cannot be centered.

**Comment by jklymak** [comment]
Thanks for the suggestion, but I'll close this.  Any extent based on a different origin is a trivial transform to get into the usual extent.  If you need to do something different you can make yourself a wrapper function pretty easily.
