### ISSUE TITLE
[Bug]: Animation does not display properly if not created at top-level regardless of gc

### ISSUE THREAD

**Issue by ananski-the-3rd** [matplotlib/matplotlib#28407]
### Bug summary

FuncAnimation does not display properly when created inside main function (same code at top level works perfectly)
GC is disabled and the animation still does not display, with a nonsense-warning message that it is garbage-collected unless plt.show is used (which it is).

### Code for reproduction

```Python
%matplotlib widget
import matplotlib.pyplot as plt
import matplotlib.animation
import numpy as np
import gc

def main() -> None:
    t = np.linspace(0,2*np.pi)
    x = np.sin(t)

    fig, ax = plt.subplots()
    l, = ax.plot([0,2*np.pi],[-1,1])

    animate = lambda i: l.set_data(t[:i], x[:i])

    ani = matplotlib.animation.FuncAnimation(fig, animate, frames=len(t))

    plt.show()
    return

if __name__ == '__main__':
    gc.disable()
    main()
```

### Actual outcome

Only the first 2 points are displayed
![image](https://github.com/matplotlib/matplotlib/assets/144336123/61afd84a-492c-4261-8e5c-d566a8cca164)

### Expected outcome

An animation that generates the sin curve bit by bit
![image](https://github.com/matplotlib/matplotlib/assets/144336123/f9d43dc4-c708-46df-b401-8a8b08ddb926)

### Matplotlib Version

3.9.0

### Matplotlib Backend

widget

### Python version

3.12.4

### Jupyter version

 v2024.5.0

### Installation

pip

**Comment by anntzer** [comment]
This is because the gc module only controls the cyclic garbage collector, not the refcount-based one, which cannot be disabled, and which is the one that matters here.  (Note that the warning only states that the animation was deleted, not that it was garbage-collected.)
