### ISSUE TITLE
There is no set_linestyle_cycle in the matplotlib axes API

### ISSUE THREAD

**Issue by rubenvb** [matplotlib/matplotlib#2841]
It would be useful to have an API to set the linestyle cycle for an axes object, just like there is one for the color cycle. It would allow one to change linestyles independently of the color, which is useful for publications that need both color and black-and-white distinguishability.

**Comment by TorbjornT** [comment]
I guess the new prop_cycler in 1.5 solves this?

**Comment by tacaswell** [comment]
Yes, that was the intention.  I think this is safe to close as completed.

```python
ax.set_prop_cycle('ls', ['-', '--', ':'])
```

Is the minimal example to cycle only the line style.
