### ISSUE TITLE
[Doc]: axhspan and axvspan now return Rectangles, not Polygons.

### ISSUE THREAD

**Issue by komoto48g** [matplotlib/matplotlib#28417]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.axvspan.html#matplotlib.axes.Axes.axvspan

### Problem

From 3.9.0 axhspan and axvspan now return Rectangles, not Polygons.

### Suggested improvement

The return value should be Rectangle.

**Comment by rcomer** [comment]
Thanks for catching that @komoto48g!  Are you interested in making a pull request to fix it?

**Comment by chrille0313** [comment]
Hi! I'm new to contributing and would like to work on this. Am I allowed to do so?

**Comment by rcomer** [comment]
@chrille0313 please do!  Everyone is welcome to contribute.

**Comment by chrille0313** [comment]
Great! I'll start working on a pull request then.

**Comment by chrille0313** [comment]
I noticed https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.axhspan.html#matplotlib.axes.Axes.axhspan has the same issue, so I will include a fix for that in the pr.

**Comment by chrille0313** [comment]
I'm having a little trouble. I updated the docstring in _axes.py as well as the return type in _axes.pyi. However, the pre-commit hooks give me the following: 
![image](https://github.com/matplotlib/matplotlib/assets/47303717/9e57f38e-807d-414b-9d28-3a69caf13a06)

I'm not sure what files to update to fix this as the linked file (pyplot.py) contains the following (see comment at the top):
![image](https://github.com/matplotlib/matplotlib/assets/47303717/7aedda29-720e-4fe6-a194-f89e03434300)

**Comment by rcomer** [comment]
boilerplate.py is here:
https://github.com/matplotlib/matplotlib/blob/main/tools/boilerplate.py

If you run that then it should make pyplot consistent with your changes.
