### ISSUE TITLE
[ENH]: Support `Axes.set_xticks(**kwargs)` to set tick params without setting fixed ticks

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28456]
### Problem

To define and rotate custom tick labels at the same time, one can use e.g. `ax.set_xticks(ticks, labels, rotation=45)`, and pass whatever additional Text properties one wants, e.g `rotation_mode="anchor"`.  On the other hand, if one wants to just rotate the default tick labels or apply other properties (which is likely the more common case), one has to use `ax.tick_params("x", rotation=45)`... and some properties are unsupported, such as `rotation_mode`.

### Proposed solution

It would seem reasonable to allow e.g. `ax.set_xticks(rotation=45, rotation_mode="anchor")`, i.e. calling set_xticks *without* actually passing ticks and labels, and interpret that as "leave the tick locator & formatter as is, but apply the given properties".

**Comment by tacaswell** [comment]
Would it be better to add the missing parameters to `ax.tick_params` ?

**Comment by anntzer** [comment]
Actually this is a dupe of #23272, let's move the discussion there.
