### ISSUE TITLE
[Bug]: Default ConciseDateFormatter offset_string confusing when axis is inverted

### ISSUE THREAD

**Issue by tbartholomaus** [matplotlib/matplotlib#28481]
### Bug summary

When an axis with dates is inverted, the offset_string plotted on the bottom right or top left of an axis is counter-intuitive or misleading when using ConciseDateFormatter.  If the axis is inverted, I'd expect either the offset string to be inverted too, or plotted in a different location.  This is especially the case when dates are plotted on the y axis and inverted, but the offset string (plotted next to the top-left tick) is most appropriate for the bottom-left tick.

### Code for reproduction

```Python
# Modeled on https://matplotlib.org/stable/gallery/ticks/date_concise_formatter.html
import datetime

import matplotlib.pyplot as plt
import numpy as np

import matplotlib.dates as mdates

base = datetime.datetime(2005, 2, 1)
dates = [base + datetime.timedelta(hours=(2 * i)) for i in range(732)]
N = len(dates)
np.random.seed(19680801)
y = np.cumsum(np.random.randn(N))

fig, ax = plt.subplots()

ax.plot(y, dates)

lims = (np.datetime64('2005-02-05'), np.datetime64('2005-04'))
ax.set_ylim(lims)
ax.invert_yaxis()

ax.yaxis.set_major_formatter(
    mdates.ConciseDateFormatter(ax.yaxis.get_major_locator()))

plt.show()
```

### Actual outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/24902730/55e52e62-f291-4815-af7c-77f295eb0600)

### Expected outcome

![Figure_1_expected](https://github.com/matplotlib/matplotlib/assets/24902730/ce30f7e4-bad5-4c5a-a2ef-e167514b4246)

### Additional information

I'm not aware of any history or context related to this problem.

### Operating system

OS/X

### Matplotlib Version

3.8.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.7

### Jupyter version

4.1.0

### Installation

conda

**Comment by jklymak** [comment]
Is this behaviour different for other types of units on the axis?  Eg does the scalar offset flip if the axis flips?

**Comment by OdileVidrine** [comment]
Is this what you mean by an axis flip? Here is the same code with ```ax.yaxis.tick_right()``` applied
![Screenshot from 2024-07-01 17-42-45](https://github.com/matplotlib/matplotlib/assets/65249488/04d81654-0c97-4959-bd08-92b313aae274)

**Comment by tbartholomaus** [comment]
> Giving this a quick glance, I think the solution is to modify this code:
> 
> https://github.com/matplotlib/matplotlib/blob/f5067c16757f4cd800ae3ba0ac25ff79d2e41a7f/lib/matplotlib/dates.py#L797-L803
> 
> 
> If axis.get_inverted() is True, then get the first date from tickdatetime (using tickdatetime[0]) instead of the last date (using tickdatetime[-1]). However I am not sure if this is the best solution or if it could break something else, I will test it.

@OdileVidrine: you're spot on here with what I've been thinking too.  And I was able to get the desired plot by modifying [line 799](https://github.com/matplotlib/matplotlib/blob/f5067c16757f4cd800ae3ba0ac25ff79d2e41a7f/lib/matplotlib/dates.py#L799) as you highlighted, exactly as you suggested.  [I hard coded it in a non-flexible way.]. Unfortunately, I'm not too savvy with proper python syntax, OOP, and the use of classes, etc, otherwise I'd implement this fix myself and submit a PR.  :(

Fundamentally, I don't understand enough of how the [format_ticks](https://github.com/matplotlib/matplotlib/blob/f5067c16757f4cd800ae3ba0ac25ff79d2e41a7f/lib/matplotlib/dates.py#L731) function works, or if something about "self" can be asked `axis.get_inverted()`

Your second comment is not what I was meaning by "axis flip," @OdileVidrine.
Thanks for your time

**Comment by tbartholomaus** [comment]
I'm not sure I understand your question, @jklymak.

**Comment by OdileVidrine** [comment]
I fixed the bug: https://github.com/matplotlib/matplotlib/blob/99f4a919bbfb428c8246ef816f8bdbcbcaa35b69/lib/matplotlib/dates.py#L797-L803
Thanks for the bug report, this probably would have gone unnoticed for a long time without it.

**Comment by OdileVidrine** [comment]
I fixed the bug here: https://github.com/OdileVidrine/matplotlib/blob/1627770d1f869ebef4266ef215c93084df8e3e4b/lib/matplotlib/dates.py#L797-L806
I'm glad you did a bug report for this, otherwise it probably would have gone unnoticed for a long time.

**Comment by tbartholomaus** [comment]
Super.  Thanks.  Will you do the PR and close this issue?

**Comment by OdileVidrine** [comment]
Yes, after I write a test and check that this change does not break anything else

**Comment by jklymak** [comment]
Sorry, my question was not a good one.  I think checking if the axis is inverted when deciding what to put in the offset is fine.  There was some discussion as to whether it made sense to have this offset in there at all, but it does seem to help many use cases.

**Comment by tbartholomaus** [comment]
Thanks to you and all the maintainers/developers!
