### ISSUE TITLE
[Bug]: `fill_between` order matters with pandas index

### ISSUE THREAD

**Issue by wd60622** [matplotlib/matplotlib#28505]
### Bug summary

The ordering of `fill_between` and pandas.DataFrame/Series.plot with datetime index differs

### Code for reproduction

```Python
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

n_dates = 52 * 3
dates = pd.date_range("2022-01-01", periods=n_dates, freq="W-MON")

seed = sum(map(ord, "Order matters"))
rng = np.random.default_rng(seed)
data = rng.normal(size=n_dates).cumsum()

ser = pd.Series(data, index=dates)
padding = 15

fig, axes = plt.subplots(ncols=2)

ax = axes[0]
ser.plot(ax=ax)
ax.fill_between(ser.index, ser - padding, ser + padding, alpha=0.25)
ax.set(title="ser.plot first")

ax = axes[1]
ax.fill_between(ser.index, ser - padding, ser + padding, alpha=0.25)
ser.plot(ax=ax)
ax.set(title="ser.plot second")

plt.show()
```

### Actual outcome

![order-matters](https://github.com/matplotlib/matplotlib/assets/57733339/fda5d7de-7fa0-488b-9e18-c37e5d97ad56)

### Expected outcome

Both orders would work the same

### Matplotlib Version

3.8.3

### Installation

None

**Comment by ksunden** [comment]
I do not think there is anything we can do upstream for this, Pandas is calling `clear`:

https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/plotting/_matplotlib/timeseries.py#L144

From the perspective of Matplotlib, we are being asked to clear and are clearing, so working as intended. (Note, I only actually saw the `clear` line in regards to TimeSeries plots, so it may well be the case that if you do something that is not a timeseries, it will not clear... Did not test to confirm that, though, and this example is a TimeSeries)

Discussion on whether or not pandas _should_ be clearing kind of have to be directed to Pandas at that point, however.

**Comment by wd60622** [comment]
> I do not think there is anything we can do upstream for this, Pandas is calling `clear`:
> 
> https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/plotting/_matplotlib/timeseries.py#L144
> 
> From the perspective of Matplotlib, we are being asked to clear and are clearing, so working as intended. (Note, I only actually saw the `clear` line in regards to TimeSeries plots, so it may well be the case that if you do something that is not a timeseries, it will not clear... Did not test to confirm that, though, and this example is a TimeSeries)
> 
> Discussion on whether or not pandas _should_ be clearing kind of have to be directed to Pandas at that point, however.



> I do not think there is anything we can do upstream for this, Pandas is calling `clear`:
> 
> https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/plotting/_matplotlib/timeseries.py#L144
> 
> From the perspective of Matplotlib, we are being asked to clear and are clearing, so working as intended. (Note, I only actually saw the `clear` line in regards to TimeSeries plots, so it may well be the case that if you do something that is not a timeseries, it will not clear... Did not test to confirm that, though, and this example is a TimeSeries)
> 
> Discussion on whether or not pandas _should_ be clearing kind of have to be directed to Pandas at that point, however.

Gotcha. Thanks for looking into it. 

Just edited the original message with a larger grid. Seems it is under pandas control. Will raise there!
