### ISSUE TITLE
[Doc]: Stackplot hatch functionality has version dependencies

### ISSUE THREAD

**Issue by RHammond2** [matplotlib/matplotlib#28533]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.stackplot.html

### Problem

The documentation for `matplotlib.pyplot.stackplot()` should indicate that matplotlib version 3.9.x or greater supports `hatch` being a list. In version 3.8.3 I was getting errors when passing a list of hatch symbols, regardless of the simplicity or complexity of the example.

If it's easier I can revisit this once I complete the body of work where this became an issue and I can submit a PR to update the documentation myself, just let me know.

**Comment by timhoffm** [comment]
Also the documented type is wrong:

![image](https://github.com/matplotlib/matplotlib/assets/2836374/c7e798d5-833a-428d-8236-a6043a75b061)

It should be
```
hatch: str or list of str, optional
```
and include in the explanation that a single str applies the same hatch to all datasets.
