### ISSUE TITLE
Rectangle accepts array as x in argument (x, y), leads to hard-to-debug errors downstream

### ISSUE THREAD

**Issue by jniediek** [matplotlib/matplotlib#28539]
`Rectangle()` allows the first argument, `(x, y)`  to be anything that has indices `[0]` and `[1]`, but `x` and `y` are not further checked. For example, if `x` is an array, the patch is created without error message. However, when calling `mpl.show()` or `savefig()`, the following `numpy` error is raised:

```
ValueError: setting an array element with a sequence. 
The requested array has an inhomogeneous shape after 1 dimensions. 
The detected shape was (4,) + inhomogeneous part.
```

This behavior is very hard to debug, since the raised error does not refer back in any way to the patch that is responsible for the problem.

MWE:

```py
import numpy as np
import matplotlib.pyplot as mpl
from matplotlib.patches import Rectangle

fig = mpl.figure()
ax = fig.add_subplot()

# The following does not raise an error
rec = Rectangle((np.array([0]), 0), 1, 1)
ax.add_artist(rec)

# The following fails
mpl.show()
```

The relevant line in the code is here:

https://github.com/matplotlib/matplotlib/blob/80c96ef3cfc464de297a9003e558deb3dc5c643b/lib/matplotlib/patches.py#L763

I think this code should check whether `xy[0]` is scalar, and fail if not. 

Please advice so that I can create a PR -- or please explain if you don't consider this a bug.

**Comment by timhoffm** [comment]
I believe the simplest change would be
```
self._x0, self._y0 = xy
```
which ensures that `xy` has to be something 2-tuple like. Alternatively, explicit length-checking, but explicit input checking is a rabbit hole.

**Comment by jniediek** [comment]
The problem is not that `xy` that `xy` has to be 2-tuple like. I would not care if `xy` is supplied as `(x, y, z)` actually. The problem is that if `x` (or `y`) are not scalars, there are errors that occur only later, when the patch is rendered.

**Comment by timhoffm** [comment]
Since Python is dynamic, these kinds of checks are cumbersome and applying them systematically leads to lots of boilerplate code. I'd claim that static checks is all we can reasonably provide here (https://github.com/matplotlib/matplotlib/blob/80c96ef3cfc464de297a9003e558deb3dc5c643b/lib/matplotlib/patches.pyi#L73). I see this as a fundamental paradim (and in this case limitation) of the language.

**Comment by jniediek** [comment]
OK!
