### ISSUE TITLE
[ENH]: Add id attribute to top level svg tag

### ISSUE THREAD

**Issue by willemsk** [matplotlib/matplotlib#28535]
### Problem

I would like to link Matplotlib SVGs directly and fully in another SVG using the `<use>` tag:

```svg
<use
  width="50" height="50"
  xlink:href="mpl.svg#svg1" id="use1"
  x="0" y="0"
/>
```

This allows one to export the linked SVGs as vectors to PDF in Inkscape. However, including a full SVG file requires the presence of an `id` attribute in the top `<svg>` tag. Currently, the first tag with a consistent `id` attribute is the `figure_1` group, but using this leads to scaling issues.

### Proposed solution

I propose to include a fixed `id="svg1"` in the top level `<svg>` tag:

```svg
<svg 
  xmlns:xlink="http://www.w3.org/1999/xlink"
  width="50pt" height="50pt"
  viewBox="0 0 50 50"
  xmlns="http://www.w3.org/2000/svg"
  version="1.1"
  id="svg1"
>
```

Which can be accomplished with a small addition to `__init__()` of the `RendererSVG` class:
```python
self._start_id = self.writer.start(
    'svg',
    width=f'{str_width}pt',
    height=f'{str_height}pt',
    viewBox=f'0 0 {str_width} {str_height}',
    xmlns="http://www.w3.org/2000/svg",
    version="1.1",
    id="svg1",
    attrib={'xmlns:xlink': "http://www.w3.org/1999/xlink"})
```

**Comment by tacaswell** [comment]
What do you mean by "consistent"?

**Comment by willemsk** [comment]
> What do you mean by "consistent"?

As in, an `id` that appears by default in all figures. In the first group, `id="figure_1"` can be changed using the `gid=` keyword in `plot()` [I believe though](https://stackoverflow.com/questions/46039835/control-class-and-id-attributes-of-matplotlib-svg-figures), though I haven't tested it yet.

**Comment by tacaswell** [comment]
It is changed by setting the `gid` on the `Figure` object.

https://github.com/matplotlib/matplotlib/blob/6b7b99927458de5980f8d5590073dd81e44e4cc5/lib/matplotlib/backends/backend_svg.py#L649-L655

so when we open a group either we use `<group>_<N>` or the user supplied gid.  Passing it to `plot` should set the gid on the `Line2D` created.

**Comment by tacaswell** [comment]
This is where we call `open_group` from the draw method of `Figure`: https://github.com/matplotlib/matplotlib/blob/6b7b99927458de5980f8d5590073dd81e44e4cc5/lib/matplotlib/figure.py#L3156
