### ISSUE TITLE
[Bug]: LineCollection, set_linestyle does not work

### ISSUE THREAD

**Issue by jonpro142** [matplotlib/matplotlib#28545]
### Bug summary

in the class LineCollection, the argument linestyle has no effect neither if set directly or if set afterwards with set_linestyle or with set(linestyle='--')
set_color does work. maybe its just linestyle that doesnt.

### Code for reproduction

```Python
coord_start = np.column_stack((x_midpts[:-1], y_midpts[:-1]))[:, np.newaxis, :]
coord_mid = np.column_stack((x, y))[:, np.newaxis, :]
coord_end = np.column_stack((x_midpts[1:], y_midpts[1:]))[:, np.newaxis, :]
segments = np.concatenate((coord_start, coord_mid, coord_end), axis=1)

lc = LineCollection(segments, **default_kwargs)
#lc.set_array(values)  # set the colors of each segment
#lc.set_linestyle(':')
#lc.set_color(c)
lc.set(color=c, linestyle='--')
```

### Actual outcome

linestyle doesnt change

### Expected outcome

linestyle should change to the type i gave as input

### Matplotlib Version

3.5.3 and 3.9.1

### Installation

None

**Comment by jonpro142** [comment]
or is that simply an optical illusion if the lines within the collections are too small to see the acutal pattern?

**Comment by timhoffm** [comment]
Please provide a fully self-contained example. We cannot judge based on an incomplete code snippet.

**Comment by jonpro142** [comment]
It was only because the lines within the collection were so small, that you couldnt see the acutal style of each line
