### ISSUE TITLE
[Bug]: Performance issues on ``plt.show()`` when the graph is already shown

### ISSUE THREAD

**Issue by Chuck321123** [matplotlib/matplotlib#28562]
### Bug summary

Plt.show() is significantly slower (>10x) and unneccesary when we already add variables to plt.

### Code for reproduction

```Python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Select this part and drag down to prevent "UsageError: Line magic function `%%timeit` not found."
%%timeit -n 2 -r 2

date_range = pd.date_range('2023-01-01', periods=50, freq='D')
np.random.seed(0)
data = np.random.randn(50, 10)
df = pd.DataFrame(data, index=date_range, columns=[f'Column_{i+1}' for i in range(10)])

plt.figure(figsize=(12, 6))
for column in df.columns:
    plt.plot(df.index, df[column], marker='', linestyle='-', linewidth=1, alpha=0.8, label=column)
plt.title('Timeseries Plot with Random Data')
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend(loc='upper right')
plt.grid(True)
plt.xticks(rotation=45)

# # Display the plot
# plt.show()
```

### Actual outcome

``23.7 ms ± 1.05 ms per loop (mean ± std. dev. of 2 runs, 2 loops each)``
``315 ms ± 1.12 ms per loop (mean ± std. dev. of 2 runs, 2 loops each)``

### Expected outcome

I expect that ``plot.show()`` (which does nothing in this case) is equally as fast as if it wasnt there

### Additional information

Unsure if I'm missing something, but just find it really weird that we can make the same plot without plt.show() while making the code significantly faster

### Operating system

Win 11

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.12.2

### Jupyter version

Im using spyder 5.5.5, but the same happened in jupyter

### Installation

pip

**Comment by timhoffm** [comment]
I suspect this is a measurement artifact. The inline backend does an implicit show at the end of the cell. T.b.c. But I assume that  is not part of the cell timing anymore, i.e. the rendering time is not accounted for in the 23ms. By adding an explicit show, you pull the rendering into the timing.

**Comment by Chuck321123** [comment]
@timhoffm I suspected the same thing afterwards. Thanks for clarifying.
