### ISSUE TITLE
[MNT]: Try improving doc build speed by using PyStemmer

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#28570]
### Summary

See the note in https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_search_language

### Proposed fix

I propse to measure what impact the use of PyStemmer would have on our docs for

1. build from scratch
2. incremental build without any changes to the previous build.

as an order-of-magnitude expectation, I know that it speeds up the sphinx-doc build by ~ 10%.

**Comment by u7228810** [comment]
Hello, has this been taken? May I complete this as my first issue please?

**Comment by u7228810** [comment]
what would be the difficulty level of this issue?

**Comment by Leoforever123** [comment]
Hello, I can try to run this test in the next couple of days, and I will provide the results as soon as possible.

**Comment by Anson0028** [comment]
For my computer, the time measurements before and after using PyStemmer are as follows:
  | Default | Using PyStemmer
-- | -- | --
Full Build | 7.52, 7.44, 8.10 | 7.01, 6.54, 6.52
Incremental Build | 6.14, 5.52, 5.57 | 5.40, 5.32, 5.28

On average, the full build time without PyStemmer is 7.55, while with PyStemmer it is 6.56, resulting in a speed improvement of approximately 13%. The average incremental build time without PyStemmer is 6.01, and with PyStemmer it is 5.33, showing a speed improvement of around 8%. There may be some measurement errors.
Should I open a PR for these results to change the documentation or something similar?
@timhoffm

**Comment by timhoffm** [comment]
Thanks @Anson0028 your measurements confirm the ~10% speedup assumption. I believe it's worth adding PyStemmer to our CI setup. Do you want to open a PR for that?

**Comment by Anson0028** [comment]
How to add PyStemmer to the CI setup? I want to do it but I don't know how to do it. Sorry to waste your time on this simple question

**Comment by timhoffm** [comment]
Add it to https://github.com/matplotlib/matplotlib/blob/main/requirements/doc/doc-requirements.txt

I think it's also reasonable to add it to https://github.com/matplotlib/matplotlib/blob/main/environment.yml

**Comment by jklymak** [comment]
Hmmm we still build a search index?  Would the faster to suppress building the index?

**Comment by timhoffm** [comment]
I don't know that one can prevent building a search index. Do you know how? - This would at least be interesting for measuring how much time is left for PyStemmer.

Also, I often use search in the CI doc build to navigate to changed docs of the PR, so I would be somewhat reluctant to deactivate that.

**Comment by jklymak** [comment]
I took a quick look, and didnt' see a way to deactivate.  It'd be great it if could be turned off, and you could use an old index if needed, but I don't really know how the index works, so maybe that is not possible.

**Comment by Anson0028** [comment]
I just opened a PR to add PyStemmer to the environment file. Please let me know if there are any errors.

**Comment by Chengyue-Fei** [comment]
I have got the environment installed but when running the command "make html". it generates an error "No module named 'matplotlib.colorizer'". I checked in the local directory and see that this file actuallly exists there. Just wondering why this problem has occurred. @timhoffm
