### ISSUE TITLE
[ENH]: Geo Projections support for inverting axis

### ISSUE THREAD

**Issue by dahlend** [matplotlib/matplotlib#28590]
### Problem

It is common in astronomy to plot the x-axis inverted from the typical direction, for example:
![image](https://github.com/user-attachments/assets/bfdc10c2-860e-4adf-8069-13a5efde8d51)

Currently if you attempt to invert the x axis of a geo projection, nothing happens:

``` python
ax = plt.subplot(2, 1, 1, projection="mollweide")
ax.invert_xaxis()    
plt.subplot(2, 1, 2, projection="mollweide")
```
![image](https://github.com/user-attachments/assets/6542c030-762c-4d2f-a757-de8030f08c4e)

The current work around is to manually invert the inputs and labels. I have seen this solution implemented in at least one astronomy package. 

Thanks for everything, I have been a regular user of matplotlib for over a decade! Great stuff!

I did some digging attempting to figure out how to implement this change myself, but I cannot figure out the internal structure of what is happening.

**Comment by rcomer** [comment]
Hi @dahlend have you tried with Cartopy?  I believe it works there https://github.com/SciTools/cartopy/issues/1606 (my field is not astronomy, so I have no deep knowledge or experience).

**Comment by timhoffm** [comment]
On a side-remark, `invert_xaxis` basically does nothing else than exchanging the xlims, i.e. (xmin, xmax) -> (xmax, xmin). If this has no effect, likely the projection ignores the limits or the limit order.

**Comment by dahlend** [comment]
Thanks, I was hoping to avoid having another dependency, but I'll look again at cartopy.
