### ISSUE TITLE
[Bug]: Version 3.5.3 is 8 times faster than 3.6.0 to 3.9.1

### ISSUE THREAD

**Issue by danielfaust** [matplotlib/matplotlib#28608]
### Bug summary

While upgrading an environment from 3.4.1 to the current 3.9.1, I noticed that the following script
```
shape = Circle((0, 0), radius=1, edgecolor='red', facecolor='red', alpha=0.1, linewidth=1.5)
for _ in range(10_000):
    ax.add_patch(shape)
```
took 14.32 seconds in 3.9.1 vs 1.75 seconds in 3.4.1.

Using flamegraphs I found the problematic function (`matplotlib/axes/_base.py::def _update_patch_limits(self, patch):`) and that version 3.5.3 was the last good one.

This is the code which changed:

**3.5.3**:
Link: https://github.com/matplotlib/matplotlib/blob/v3.5.3/lib/matplotlib/axes/_base.py#L2382C1-L2398C67
Permalink: https://github.com/matplotlib/matplotlib/blob/d04c8de4a89ab756a137ef146e8542e81041909f/lib/matplotlib/axes/_base.py#L2382C1-L2398C67

**3.6.0**:
Link: https://github.com/matplotlib/matplotlib/blob/v3.6.0/lib/matplotlib/axes/_base.py#L2433C1-L2457C67
Permalink: https://github.com/matplotlib/matplotlib/blob/a302267d7f0ec4ab05973b984f7b56db21bf524c/lib/matplotlib/axes/_base.py#L2433C1-L2457C67

The flamegraphs are:

**3.5.2** (1.75 seconds)
![framegraph-3 5 2](https://github.com/user-attachments/assets/5b78cb53-eade-4f10-8fc2-64c53277f2ff)

**3.9.1** (14.32 seconds)
![flamegraph-3 9 1](https://github.com/user-attachments/assets/896c98fc-2e6d-43f4-866f-b69a2c970c59)

You can recreate the environments via

`conda create -n test-matplotlib-3.5.3 python=3.9 matplotlib=3.5.3` and
`conda create -n test-matplotlib-3.6.0 python=3.9 matplotlib=3.6.0`

Python 3.9 is used here because it is the last version supported by 3.5.3

Activate via `conda activate test-matplotlib-3.5.3` and `conda activate test-matplotlib-3.6.0`.

Delete via `conda remove --all -n test-matplotlib-3.5.3` and `conda remove --all -n test-matplotlib-3.6.0`

The complete script follows:

### Code for reproduction

```Python
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, Rectangle, Circle

fig, ax = plt.subplots()

start_time = time.time()

# shape = Ellipse((0, 0), width=2, height=2, edgecolor='red', facecolor='red', alpha=0.1, linewidth=1.5)
# shape = Rectangle((-1, -1), width=2, height=2, edgecolor='red', facecolor='red', alpha=0.1, linewidth=1.5)
shape = Circle((0, 0), radius=1, edgecolor='red', facecolor='red', alpha=0.1, linewidth=1.5)

for _ in range(10_000):
    ax.add_patch(shape)

end_time = time.time()

print(f"Time taken to plot {iterations} iterations: {end_time - start_time} seconds")
```

### Actual outcome

The result `Time taken to plot 10000 iterations: 14.40 seconds`

### Expected outcome

The result `Time taken to plot 10000 iterations: 1.61 seconds`

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.6.0+

### Matplotlib Backend

agg

### Python version

3.8+

### Installation

conda

**Comment by jklymak** [comment]
This seems to be a conflict between doing something well and doing it fast.  In this situation I think the expectation is that you would use CircleCollection, which I assume is faster?

**Comment by danielfaust** [comment]
@jklymak I wasn't aware of these collections, thank you a lot for pointing it out.

The following code takes around 0.6 seconds in 3.9.1, so using collections is the solution.

```
import time
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
from matplotlib.patches import Circle

fig, ax = plt.subplots()

start_time = time.time()

num_circles = 10_000
np.random.seed(0)

x = np.random.uniform(-10, 10, num_circles)
y = np.random.uniform(-10, 10, num_circles)
radii = np.random.uniform(0.1, 1, num_circles)
colors = np.random.rand(num_circles, 4)  # RGBA colors with random values

patches = [Circle((x[i], y[i]), radii[i], edgecolor=colors[i][:3], facecolor=colors[i], alpha=colors[i][3], linewidth=1.5) for i in range(num_circles)]

collection = PatchCollection(patches, match_original=True)
ax.add_collection(collection)

ax.set_xlim(-15, 15)
ax.set_ylim(-15, 15)
ax.set_aspect('equal')

end_time = time.time()

print(f"Time taken to plot {num_circles} circles: {end_time - start_time} seconds")

output_file = 'circles_plot.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
```
