### ISSUE TITLE
[Bug]: `matplotlib>=3.9` + `geopandas.plot()` does not respect `matplotlib.colors.CenteredNorm`

### ISSUE THREAD

**Issue by jGaboardi** [matplotlib/matplotlib#28601]
### Bug summary

There seems to be a change in the interaction between `matplotlib` & `geopandas` in `matplotlib>=3.9` when `geopandas` accesses `matplotlib.colors.CenteredNorm` during plotting. The plotted values seem to be the original ones, not the normalized ones.

@martinfleis

### Code for reproduction

```Python
# - code in a series of gists across matplotlib & geopandas versions
# - gists include plots of {points, linestrings, polygons} to demonstrate disparity
# - see Additional information section
```

### Actual outcome

* ***Plots*** do not respect `matplotlib.colors.CenteredNorm` with certain geometry types in certain `matplotlib` versions.
* The actual values of `matplotlib.colors.CenteredNorm` are correct.

### Expected outcome

Plots should respect `matplotlib.colors.CenteredNorm` when plotting any geometric type.

### 6 gists demonstrating various outcomes

* [`matplotlib 3.6.3 - geopandas 1.0.1`](https://gist.github.com/jGaboardi/54fdce50ddbc6b161a6f489fdc3d1819) 
* [`matplotlib 3.7.3 - geopandas 1.0.1`](https://gist.github.com/jGaboardi/d7e90e06019cfee5c8585039efaf0cdf)
* [`matplotlib 3.8.4 - geopandas 1.0.1`](https://gist.github.com/jGaboardi/b90fc05674a1df92c118d79dc8fea513)
* [`matplotlib 3.9.1 - geopandas 1.0.1`](https://gist.github.com/jGaboardi/172f82647086ff4e6090acb0ede3ab7c)
* [`matplotlib 3.8.4 - geopandas 0.14.4`](https://gist.github.com/jGaboardi/8c72ee0894cab86dc876045c32c713a9)
* [`matplotlib 3.9.1 - geopandas 0.14.4`](https://gist.github.com/jGaboardi/2232b256a2ce1b68317457bccae7c52d)

### plot respects `norm=CenteredNorm()`?

```
Python implementation: CPython
Python version       : 3.11.9
IPython version      : 8.26.0

Compiler    : Clang 16.0.6 
OS          : Darwin
Release     : 23.5.0
Machine     : arm64
Processor   : arm
CPU cores   : 8
Architecture: 64bit
```

#### Holding all packages at:

```
geopandas : 1.0.1
numpy     : 1.26.4
pandas    : 2.2.2
shapely   : 2.0.5
```

| `matplotlib==v*` | `3.6.3` | `3.7.3` |  `3.8.4` | `3.9.1` | 
| --- | --- | --- | --- | --- |
| points | ❌ | ❌  | ❌ | ❌  |
| linestrings | ❌ | ✅ | ✅ | ❌  |
| polygons | ❌ | ✅ | ✅ | ❌  |

#### Holding all packages at:

```
geopandas : 0.14.4
numpy     : 1.26.4
pandas    : 2.2.2
shapely   : 2.0.5
```

| `matplotlib==v*` |  `3.8.4` | `3.9.1` | 
| --- | --- | --- |
| points   | ❌ | ❌  |
| linestrings | ✅ | ❌  |
| polygons | ✅ | ❌  |

### Operating system

OS/X

### Matplotlib Version

{3.6.3, 3.7.3, 3.8.4,	3.9.1}

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.9

### Jupyter version

7.2.1

### Installation

conda

**Comment by rcomer** [comment]
Hi @jGaboardi I'm not familiar with geopandas but it looks like the colours of the linestring/polygon plots have changed to be consistent with the points plot.  The colorbar is centred on 1, as you have specified in the norm, and the colorbar range has increased to incorporate all your data values.

So this looks to me like a bug has been fixed, and the v3.9.1 behaviour is correct.  Am I missing something?

**Comment by martinfleis** [comment]
> So this looks to me like a bug has been fixed, and the v3.9.1 behaviour is correct

Seems like it, at least from the MRE.

**Comment by jGaboardi** [comment]
> The colorbar is centred on 1, as you have specified in the norm, and the colorbar range has increased to incorporate all your data values.
>
>So this looks to me like a bug has been fixed, and the v3.9.1 behaviour is correct. Am I missing something?

@rcomer After you pointed this out, it seems obvious 😅 . I think I had been staring at it so long and also just assumed the results I marked as ✅ were "correct" since I tested against them first. Thanks for quick feedback! I will close this out.

**Comment by jklymak** [comment]
Any chance you can make a reproducible example that just uses numpy and matplotlib?  This seems to be working fine in our doc build, and it's not really possible to tell what you think is wrong with it based on the report here.

**Comment by jGaboardi** [comment]
> Any chance you can make a reproducible example that just uses `numpy` and `matplotlib`? 

No, since the issue had to do with the interplay between `matplotlib` and `geopandas`. I linked 6 (nearly) MREs demonstrating the issue I was seeing in the ***6 gists demonstrating various outcomes*** section. Those 6 MREs all produced equivalent values within the `matplotlib.colors.CenteredNorm` object, but something had been happening where those values weren't translated properly within `geopandas` plot.

At any rate, based on the comment from @rcomer we seem to have determined that it likely was a bug in `matplotlib>=3.6.3,<=3.9` that was fixed prior to the `3.9` release.

**Comment by jklymak** [comment]
Apologies.  I didn't realize the issue had been closed.

**Comment by jGaboardi** [comment]
No problem at all! I am excited that this issue got the attention of 2 devs within several hours of opening it, and we could find the resolution nearly immediately. 💪

**Comment by rcomer** [comment]
> I think I had been staring at it so long

We’ve all been there…!
