### ISSUE TITLE
[MNT]: Code style inconsistencies for docstrings in lines.py

### ISSUE THREAD

**Issue by scaccol** [matplotlib/matplotlib#28630]
### Summary

Not a large issue, just code style inconsistencies. The docstrings for the functions on lines [1543-1159 of lines.py](https://github.com/matplotlib/matplotlib/blob/b19794e126c1077b83eba90fe74ab1f67362b1ba/lib/matplotlib/lines.py#L1543-L1559) don't match formatting conventions used for other functions in the file. As per [PEP8](https://peps.python.org/pep-0008/#documentation-strings), one-liner docstrings should be kept to a single line.

### Proposed fix

```
    def get_xy1(self):
        """Return the *xy1* value of the line."""
        return self._xy1

    def get_xy2(self):
        """Return the *xy2* value of the line."""
        return self._xy2

    def get_slope(self):
        """Return the *slope* value of the line."""
        return self._slope
```

**Comment by timhoffm** [comment]
You are correct. If you want to, please open a pull request.
