### ISSUE TITLE
[Bug]: format_image_data on an image of only zeros produses a large number of zeros

### ISSUE THREAD

**Issue by trygvrad** [matplotlib/matplotlib#28648]
### Bug summary

If you use imshow, and then mouseover the image, the value is listed at the bottom of the plot.
However, if the image contains only zeros, the result is a comical number of zeros.

### Code for reproduction

```Python
import matplotlib
import numpy as np
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
im = ax.imshow(np.zeros((4, 4)))
fig.show()
```

### Actual outcome

When you mouse-over the image it shows a large number of zeros (see bottom of image).
![image](https://github.com/user-attachments/assets/e1cb7d31-31a2-48f8-afd5-0dd57446ec38)

### Expected outcome

0.0 should be at the bottom of the page and the window should retain its original size:
![image](https://github.com/user-attachments/assets/25f03995-ea55-4eea-b9ee-1763513c7cbf)

### Additional information

test_image.py→test_image_cursor_formatting()  should test this perscise functionality, but there is a bug in this test where 
```py
    data = np.ma.masked_array([0], mask=[False])
    assert im.format_cursor_data(data) == '[0]'
```
should be
```py
    data = np.ma.masked_array(0, mask=[False])
    assert im.format_cursor_data(data) == '[0]'
```
And this causes `im.format_cursor_data` to fallback and '0' is returned. 
This test should be updated as part of a PR to fix this bug. 

### Matplotlib Version

matplotlib_dev, 3.8.2

### Matplotlib Backend

TkAgg

### Installation

git checkout

**Comment by tacaswell** [comment]
The issue is singular norms.  We do a bunch of extra logic it https://github.com/matplotlib/matplotlib/blob/adb97e848ca88f0b9abc5b1c5085f548847e3f8f/lib/matplotlib/artist.py#L1349-L1377 to estimate a "good" number of digits via https://github.com/matplotlib/matplotlib/blob/adb97e848ca88f0b9abc5b1c5085f548847e3f8f/lib/matplotlib/cbook.py#L2249-L2267


```
In [10]: import matplotlib.cbook as mc

In [11]: mc._g_sig_digits(0, 0)
Out[13]: 325

In [14]: mc._g_sig_digits(0, .1)
Out[14]: 2

In [15]: mc._g_sig_digits(0, 0)
Out[15]: 325

In [16]: mc._g_sig_digits(0, .00001)
Out[16]: 6

In [17]: mc._g_sig_digits(0, .000001)
Out[17]: 7

In [18]: mc._g_sig_digits(0, .0001)
Out[18]: 5

In [19]: mc._g_sig_digits(.1, 0)
Out[19]: 17
```

I have some ideas, will open a PR shortly.
