### ISSUE TITLE
[Bug]: `matplotlib.patches.Circle`'s shape is dependent on the figsize ratio and leads to ellipses instead of actual circles

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [matplotlib/matplotlib#28667]
### Bug summary

When a circle is drawn using `matplotlib.patches.Circle`, the shape of the circle depends on the figure's aspect ratio, resulting in ellipses rather than circles in the output when the ratio is not 1.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

fig, ax = plt.subplots(figsize=(15,5))

circle = mpatches.Circle(
   xy=(0.5, 0.5),
   radius=0.05
)
fig.add_artist(circle)

ellipse = mpatches.Ellipse(
   xy=(0.4, 0.4),
   width=0.1,
   height=0.1
)
fig.add_artist(ellipse)

plt.show()
```

### Actual outcome

<img width="1173" alt="Screenshot 2024-08-05 at 14 33 30" src="https://github.com/user-attachments/assets/365a5db2-5091-4cfe-baf5-9666f2706058">

### Expected outcome

<img width="1179" alt="Screenshot 2024-08-05 at 14 35 41" src="https://github.com/user-attachments/assets/3fb8f83a-7ce0-4229-ac15-4e92b96838ab">

### Additional information

This may be expected behaviour, but if it is, I wonder if there's a workaround or if I've missed something.

The issue can be resolved by using `matplotlib.patches.Ellipse` with the same height/width ratio as used for the figure, but it implies to have "dupplicated" code when trying to draw circles.

### Operating system

MacOS Sonoma 14.5

### Matplotlib Version

3.9.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.10.13

### Installation

pip

**Comment by tacaswell** [comment]
This is behaving as expected.  By default `patch.Circle` is sized in data-space (not screen space), but when displayed is "stretched" to a different aspect ratio.

```python
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.transforms as mtransforms

fig, ax = plt.subplots(figsize=(15,5))

circle = mpatches.Circle(
   xy=(200, 200),
   radius=100,
   transform=mtransforms.IdentityTransform()
)
fig.add_artist(circle)

ellipse = mpatches.Ellipse(
   xy=(0.4, 0.4),
   width=0.1,
   height=0.1
)
fig.add_artist(ellipse)

plt.show()
```

To get something round on screen you need to specify the circle in an absolute coordinate system.  It does not look like there is a public way use `patch.Circle` to a) place the circle in data coordinates b) size/shape it in screen coordinates.  There is a private way (that we use to make the elipse selector work, but on a very quick reading, I'm not sure haw to make that public in a useful way.

If we were to try and thread different transforms for the shape and location through this is where it would have to ultimately land https://github.com/matplotlib/matplotlib/blob/d239b3620fba0002e46d216c6ab3165f5f79ec11/lib/matplotlib/patches.py#L1629-L1646

----

This is the sort of thing that should be easier to express using the https://github.com/matplotlib/data-prototype .

**Comment by JosephBARBIERDARNAL** [comment]
If this is the expected behaviour, I think we can close this issue (?). I think the use of transformations is satisfying enough (at least for my use cases).

Thanks for your quick reply!

**Comment by tacaswell** [comment]
Closing as @JosephBARBIERDARNAL is happy (enough) with this being expected behavior.

threading through multiple transforms is _possible_ but I think it would be a big-ish project which would involve API design.

**Comment by jklymak** [comment]
This is an explicit example in the transforms tutorial.  https://matplotlib.org/stable/users/explain/artists/transforms_tutorial.html#plotting-in-physical-coordinates

**Comment by JosephBARBIERDARNAL** [comment]
ah well! I'd missed it

**Comment by jklymak** [comment]
Also please don't use the identity transform unless you are ok with unexpected things happening if the dpi changes.  Fig.dpi_scale_trans will allow the object to be in physical units.

**Comment by JosephBARBIERDARNAL** [comment]
Ok, so the correct way to proceed is actually:

```python
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.transforms as mtransforms

fig, ax = plt.subplots(figsize=(15,5))

circle = mpatches.Circle(
   xy=(3, 3),
   radius=1,
   transform=fig.dpi_scale_trans
)
fig.add_artist(circle)

plt.show()
```

<img width="1178" alt="Screenshot 2024-08-05 at 17 19 02" src="https://github.com/user-attachments/assets/e816c0a9-5f22-4a38-8030-53214da90f00">

**Comment by tacaswell** [comment]
ah, yes I tried `dpi_scale_trans` but thought it went from "virtual pixels" -> "screen pixels" not "inches" -> "screen pixels" 🐑 .  However, that does explain why the circle at put at (100in, 100in) did not show up 🤣

**Comment by jklymak** [comment]
FWIW, I still think it would be better if the Identity transform were 72 dpi, and a different transform was the temporary dpi relevant one.  Its pretty confusing for our "default" unit be one that changes meaning as dpi changes.  Not sure where @QuLogic  got to in that refactor.

**Comment by tacaswell** [comment]
The path of least resistance there may to add `fig.transInches` and `ax.transInches` (even if we do not use them internally) I think we should be able to expose the right nodes out of the transform graph?

**Comment by jklymak** [comment]
Sorry, this is probably off-topic for this issue.  However, how would those be different than `fig.dpi_scale_trans` (other than having much better names!)?  

My point is just that it's confusing for the "IdentityTransform" to change if the dpi changes but the size of whatever is in that coordinate system changes size.

**Comment by tacaswell** [comment]
Mostly better (well, more consistent) name, but also putting in on Axes.
