### ISSUE TITLE
[Bug]: Windows pip install: No module named 'mesonpy'

### ISSUE THREAD

**Issue by Acly** [matplotlib/matplotlib#28663]
### Bug summary

There are no pre-built wheels for 3.9.1 on Windows. pip tries to build from source and fails.

### Code for reproduction

```Python
pip install matplotlib
```

### Actual outcome

`ModuleNotFoundError: No module named 'mesonpy'`

### Expected outcome

Installs matplotlib 3.9.1

### Additional information

I don't see any pre-built whl for Windows at https://pypi.org/project/matplotlib/3.9.1/#files
I feel like they used to be there, where have they gone?

`pip install matplotlib==3.9.0` works fine (and has pre-built wheel on pypi).

### Operating system

Windows

### Matplotlib Version

3.9.1

### Python version

3.10, 3.11

### Installation

pip

**Comment by RaenonX** [comment]
Having the same issue. https://matplotlib.org/stable/install/index.html#install-an-official-release claims that "Matplotlib releases are available as wheel packages for macOS, Windows and Linux on [PyPI](https://pypi.org/project/matplotlib/)." but I am not seeing Windows wheels as well.

Interestingly, my [periodic build](https://dev.azure.com/RaenonX/RaenonX/_releaseProgress?_a=release-environment-deployment-group-logs&releaseId=7796&environmentId=7796&deploymentGroupPhaseId=13551 ) shows that it was available before, did they accidentally get removed?
```
2024-08-03T21:12:46.0372547Z Collecting matplotlib (from -r requirements.txt (line 10))
2024-08-03T21:12:46.0390339Z   Using cached matplotlib-3.9.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
```

**Comment by jklymak** [comment]
Thanks for your report.  This is a duplicate and a fix is being worked on.

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2267647457

**Comment by RaenonX** [comment]
Thanks for the quick response, I was just gonna type out here asking if it's the same as #28551.
