### ISSUE TITLE
[Bug]: no windows wheels for 3.9.1

### ISSUE THREAD

**Issue by cpcloud** [matplotlib/matplotlib#28660]
### Bug summary

There are no windows wheels for the 3.9.1 release.

### Code for reproduction

```Python
# There's no code, because this isn't a bug report related to matplotlib library code.
```

### Actual outcome

https://pypi.org/project/matplotlib/3.9.1/#files

### Expected outcome

I would expect there to be windows wheels for the 3.9.1 release.

### Operating system

Windows

### Matplotlib Version

3.9.1

### Installation

pip

**Comment by Andrew-S-Rosen** [comment]
Yup, can confirm this is an issue. See https://github.com/Quantum-Accelerators/quacc/actions/runs/10235615291/job/28316651828?pr=2381

**Comment by rcomer** [comment]
Hi @cpcloud these were deliberately deleted due to a bug which only affected Windows.  See https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2267223102.

**Comment by cpcloud** [comment]
@rcomer Thanks! Just read through the issue 😬 

Closing this as not a bug then!

**Comment by tacaswell** [comment]
We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.

Sorry for the trouble.

**Comment by cpcloud** [comment]
No worries! Appreciate the thoughtfulness on avoiding segfaults, seems like a strong enough reason to remove some wheels.

Yanking might've prevented the current situation, not sure though. It's quite a large hammer, but it's really the only tool available in these cases afaik.

**Comment by tacaswell** [comment]
I yanked the whole release so it should have "fixed" it self unless you are hard-pinning 3.9.1.

**Comment by doronbehar** [comment]
For those who build from source (Linux distributions), is it OK to update to 3.9.1?

**Comment by rcomer** [comment]
@doronbehar my guess is that's fine because the problem seems to have been very specific to Windows and PyPI.  [3.9.1 is still available from conda-forge](https://anaconda.org/conda-forge/matplotlib/files).

**Comment by tacaswell** [comment]
Correct, downstream packagers SHOULD NOT yank 3.9.1 as well.

The problem is strictly with wheels on windows and the only tool we have is "yank the whole release for everyone".
