### ISSUE TITLE
[Bug]: set_xlim, set_xbounds being ignored when set_aspect('equal', 'datalim') being used

### ISSUE THREAD

**Issue by kjayawar** [matplotlib/matplotlib#28673]
### Bug summary

When ax.set_aspect('equal', 'datalim') is used, proceeding ax.set_xbound() or ax.set_xlim() calls being ignored

### Code to reproduce the error

```Python
import matplotlib.pyplot as plt
import numpy as np

# Generate some random data
x = np.arange(0, 10, 0.1)
y = np.random.randn(len(x))

# Create a plot
fig, ax = plt.subplots()
plt.ion()
ax.set_aspect('equal', 'datalim')


# Set x-axis limits
ax.set_xlim(2, 5)


# Print the x and y limits
print(f"x-axis limits before plotting: {ax.get_xlim()}")
print(f"y-axis limits before plotting: {ax.get_ylim()}")

ax.plot(x, y*10)


# Print the x and y limits
print(f"x-axis limits after plotting: {ax.get_xlim()}")
print(f"y-axis limits after plotting: {ax.get_ylim()}")

# Set x-axis limits
ax.set_xbound(lower=2, upper=5)
# ax.set_xlim(2, 5)

# Print the x and y limits
print(f"x-axis limits after setting xlim: {ax.get_xlim()}")
print(f"y-axis limits after setting xlim: {ax.get_ylim()}")

# Show the plot
plt.show()
```
What is been tried to mitigate the issue
ax._autoscaleXon = False

### Actual outcome

This code produces a plot with x-axis not limited to the given xrange 2-5.
![image](https://github.com/user-attachments/assets/f5124e52-1286-414c-b219-ebfd21dd04f6)

### Expected outcome

xlimit obeys the given range, with y range automatically adjusted to the given aspect ratio

### Operating system

windows

### Matplotlib Version

3.8.2

### Matplotlib Backend

QtAgg

### Python version

Python 3.9.7

### Installation

pip

**Comment by timhoffm** [comment]
One can only have 2 out of
- all data is visible
- apply a given data aspect
- respect limits for one axis 

I suspect (but to be verified in code) that adjustable datalim always chooses the first 2 and ignores limits.

The problem with cutting out data is: 
1. It’s dangerous to implicitly hide data. The user may not be aware that data is hidden.
2. Which sub-range should we display? Lower end/centered/higher end?

The minimum we can do is better documentation. I‘m not whether we can reasonably change behavior.

**Comment by kjayawar** [comment]
Hi Tim, 

Thanks for the reply. I am after the last 2 options. I tried number of variations with no luck at all so far. Could you please let me know if it's possible to do this with Matplotlib. ?

**Comment by jklymak** [comment]
@kjayawar Yes this is possible - define the x and y limits manually. Otherwise what you are asking for is underdetermined, which is why it is not offered.  In particular, as @timhoffm has pointed out, that if we zoom the x axis we would need to choose what to crop in the y direction and we have no basis for making that decision.

**Comment by kjayawar** [comment]
Hi @jklymak Thanks for the reply. But as I've shown in the code snippet above, manually setting xlim and xbounds is being ignored by matplotlib - hence this request. What I Ideally need is matplotlib to respect the manually set xlims such that the ylims automatically getting adjusted to the given AR

**Comment by jklymak** [comment]
Yes, you don't set the data aspect.

**Comment by kjayawar** [comment]
Hi @jklymak , sorry, could you please elaborate a little bit more on the "data aspect" I tried googling it but couldn't find any.
I also tried dir on ax only to find below functions with the string 'aspect' on it

_aspect
_box_aspect
_get_aspect_ratio
apply_aspect
get_aspect
get_box_aspect
set_aspect
set_box_aspect

Could you please point out how this can be done if possible ?
Thanks much

**Comment by jklymak** [comment]
You still don't say exactly what you are after, but if I were to guess:

```
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0, 10, 0.1)
y = np.random.randn(len(x))

aspect = 2.75/5
fig, ax = plt.subplots(figsize=(5, 5 * aspect))
# could query the default aspect ratio, but a bit easier to just set it explicitly:
ax.set_box_aspect(aspect)
ax.plot(x, y)

xlim = np.array([2, 5])
# centers ylim on zero.  offset as you see fit.
ylim = np.diff(xlim) * aspect * np.array([-1, 1])
ax.set_xlim(xlim)
ax.set_ylim(ylim)
```

![Aspect](https://github.com/user-attachments/assets/2c22d4fb-1bb6-40a4-9d17-a753f42b1662)

Again, note that the ylimit is arbitrary, and you'd need to decide on a heuristic to get what you want.

**Comment by kjayawar** [comment]
Hi @jklymak -- Thanks for the reply. To say what I want exactly -> I want to plot a graph to a given AR WITHOUT CHANGING the bbox size, adhering to the the xlimits. So in this case , y limits should adjust automatically.  Very simple requirement but apparently matplotlib doesn't support this

**Comment by jklymak** [comment]
Matplotlib does not do this because "y limits should adjust automatically" is ambiguous.  We know the range that y should have, but we do not know what that range should be centred on.

**Comment by kjayawar** [comment]
assuming im happy to use set_ylim(bottom=0) could this be done natively with matplotlib ?

**Comment by kjayawar** [comment]
I was actually able to get what I described above as per below

```
import matplotlib.pyplot as plt
import numpy as np


def get_ax_size(ax):
    bbox = ax.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
    return bbox.width, bbox.height

def set_ylim(ax, AR=2, lower=0):
	width, height = get_ax_size(ax)
	# fig.draw_without_rendering()
	x_lim = ax.get_xlim()
	x_range = max(x_lim)-min(x_lim)
	y_range = (x_range/AR) * (height/width)
	ax.set_ylim(lower, lower+y_range)

# Generate some random data
x = np.arange(0, 10, 0.1)
y = np.random.randn(len(x))

# Create a plot
fig, ax = plt.subplots()
plt.ion()
ax.set_aspect(1, 'box')


ax.plot(x, y)

# Set x and y limits
ax.set_xbound(lower=1, upper=5)
set_ylim(ax, AR=1, lower=0)

plt.show()
```
This shows correct plot. But unfortunately when I do zoom all goes south.
