### ISSUE TITLE
[Bug]: text misplaced on subplots with histograms

### ISSUE THREAD

**Issue by pedro-w** [matplotlib/matplotlib#28681]
### Bug summary

I wanted to create plot with multiple subplots incorporating histograms and 'empty' plots with text placed in them.
Surprisingly I found the text was misplaced if `sharex` was True and the histogram data didn't include zero. Minimal example below, will generate two files `test-0.png` and `test-10.png` - these are also pasted in the bug report below.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np


def mrt(midp):
    fig, (ax1, ax2) = plt.subplots(ncols=2, sharex=True)
    ax1.hist(np.random.normal(midp, 1, 100))
    ax2.set_axis_off()
    ax2.text(0.5, 0.5, f"TEST {midp}")
    fig.savefig(f"test-{midp}.png")


mrt(0)
mrt(10)
```

### Actual outcome

Where the histogram data *does not* include zero the "TEST 10" text is misplaced - it is in the left hand subplot
![test-10](https://github.com/user-attachments/assets/04888432-771f-4f61-b687-7cc21acad149)

### Expected outcome

Where the hist *does* include zero the "TEST 0" text is correctly placed in the center of the second subplot.
![test-0](https://github.com/user-attachments/assets/89632192-90c6-4fdb-a71f-5d844f54c3c8)

### Additional information

Seems to be reproducible, I initially saw it with a more complex 4x4 subplot layout. Needs `sharex` to be True. I guess the 'empty' plot has its own x-scale which somehow affects the placement?

### Operating system

Windows 11

### Matplotlib Version

3.9.1.post1

### Matplotlib Backend

tkagg

### Python version

Python 3.11.9

### Jupyter version

N/A

### Installation

pip

**Comment by pedro-w** [comment]
Having investigated a bit more I think perhaps this is not as I thought; what happens is that the histogram subplots all contribute to the shared x-limits which also* apply to the subplot with text in it. So `ax.text(0.5, 0.5, "...")` drawn at x=0.5 may be anywhere at all on the subplot depending on what the x-limits are.
A solution is 
```
(xmin, xmax) = ax.get_xlim()
ax.text((xmin+xmax)/2, 0.5, "...")
```
(as long as this happens after the histograms have been plotted to establish the limits)

If you agree, then this can be closed.

\* my mistake was to assume `set_axis_off` gets rid of the axis processing entirely

**Comment by rcomer** [comment]
Hi @pedro-w, by default the text is placed in data coordinates and you are correct that the data limits of the right-hand axes have been updated to match the left-hand.  You can also place the text relative to a fraction of the axes with

```python
ax2.text(0.5, 0.5, f"TEST {midp}", transform=ax2.transAxes)
```

See the [Transformations Tutorial](https://matplotlib.org/stable/users/explain/artists/transforms_tutorial.html) for details.

**Comment by pedro-w** [comment]
Thanks @rcomer - I was sure this was a bug, should have asked on StackOverflow or whatever first!
