### ISSUE TITLE
[Doc]: Analytics sharing policy

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#28696]
### Problem

We have analytics data from https://plausible.io/ and I'm still getting the email from google search console (but no access) and it's unclear how to get access to this data.

This request is primarily motivated by:
* interest from @tgmiller5 and @jeromefv on running a new user survey (the last one was 4 years ago and run by @jeromefv) and this information being helpful for design and analysis
* ongoing documentation discussions (#26366, #26389) that would benefit from having the usage data

Also we just got a request for it for research purposes:
* https://discourse.matplotlib.org/t/site-page-view-statistics-for-feature-importance/24594

### Suggested improvement

To make it easier to access this data, we should:
* document who has access to the analytics and how to request access
  * who should be admin vs viewer: https://plausible.io/docs/users-roles
* figure out a policy for what data we want to share 
  * e.g. do we want/can we have a public dashboard: https://plausible.io/napari.org

attn: @melissawm

**Comment by brianhempel** [comment]
Thanks a bunch!

**Comment by rcomer** [comment]
> resolution was https://views.scientific-python.org/matplotlib.org/

I was just looking for this link but couldn't remember where I'd seen it (I fruitlessly searched Discourse and Gitter before the issues).  Do we have it linked from anywhere else?
