### ISSUE TITLE
[bug]: arrowstyle doc interpolation in FancyPatch.set_arrow()

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#28698]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.patches.FancyArrowPatch.html#matplotlib.patches.FancyArrowPatch.set_arrowstyle

### Problem

The documentation interpolation isn't working here, so its not showing the table of arrowstyles

![image](https://github.com/user-attachments/assets/87762e9e-c352-4306-8c8b-41151fab7737)

The string looks correct though:
https://github.com/matplotlib/matplotlib/blob/1e983776e9210fbc7426f28ce6e7eeadea18f9e9/lib/matplotlib/patches.py#L4347-L4349

### Suggested improvement

Should be interpolated so that the table shows here:
![image](https://github.com/user-attachments/assets/0d4d287c-2b28-4415-8018-e8919c0b86d3)

**Comment by timhoffm** [comment]
Just missing the `@_docstring.interpd` decorator?
