### ISSUE TITLE
Wrong symbols from a TrueType font

### ISSUE THREAD

**Issue by mojca** [matplotlib/matplotlib#2870]
When I figured out that OpenType fonts wouldn't work, I found LucidaBrightRegular.ttf in Java and tried to use it with

```
matplotlib.rcParams['font.family'] = 'Lucida Bright'
plt.title('abc [def](ghi)')
```

(I actually need this for something like plt.xlabel('length [cm]').)

But this is what I get in PDF, the closing parenthesis are rotated and displaced (or maybe the wrong symbol is used):

![wrong_symbols](https://f.cloud.github.com/assets/15606/2340037/377b99f8-a4bd-11e3-9365-414a748652e6.png)

while PNG and native GUI on Mac OS X work fine. I'm using the latest matplotlib (9fea4307af) with Python 3.3.

Related issue: #2869

**Comment by jkseppan** [comment]
Fix in #18081
