### ISSUE TITLE
[Bug]: CI doc builds fail since a couple of days

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#28715]
### Bug summary

We get 86 warnings that references could not be resolved like

> /home/circleci/project/lib/matplotlib/axes/_axes.py:docstring of matplotlib.axes._axes.Axes.barbs:179: WARNING: py:meth reference target not found: matplotlib.collections._CollectionWithSizes.set_sizes [ref.meth]

One of the last clean builds seem to be https://app.circleci.com/pipelines/github/matplotlib/matplotlib/32390/workflows/b3701e27-4810-49ef-a165-951f5847d699/jobs/84333

Note that this uses the latest sphinx=8.0.2 so it's not a sphinx update that broke us.

A possible candidate could be #28632, which was merged about that time. I haven't looked into it but this would be my first step to investigate.

### Code for reproduction

CI run of PR against main (not doc-only)

**Comment by QuLogic** [comment]
The update was that broke it was `numpydoc` 1.8.0; I am investigating why exactly it did.
