### ISSUE TITLE
Size hint method in Qt backend should be named `minimumSizeHint`, not `minumumSizeHint`

### ISSUE THREAD

**Issue by mikhas** [matplotlib/matplotlib#28716]
https://github.com/matplotlib/matplotlib/blob/9f49b07ba92d71b967c1098e31d6b96bd0c28a3d/lib/matplotlib/backends/backend_qt.py#L396

**Comment by tacaswell** [comment]
task:

 - correct spelling of method name so Qt will use it!

**Comment by tacaswell** [comment]
This typo appears to have come in via b7d1d5964249892e1cc31bef0be711610e0a55db in 2007 and been carried forward through all of the Qt refactors

**Comment by tacaswell** [comment]
qt docs: https://doc.qt.io/qt-6/qwidget.html#minimumSizeHint-prop

**Comment by mikhas** [comment]
> This typo appears to have come in via [b7d1d59](https://github.com/matplotlib/matplotlib/commit/b7d1d5964249892e1cc31bef0be711610e0a55db) in 2007 and been carried forward through all of the Qt refactors

I can't even tell what the effect is, given that the intended minimum size of `width=10`, `height=10` appears to be too small (to me) anyway.

**Comment by tacaswell** [comment]
We had a number of issues where we would end up with 0 pixel sized widgets that lead to crashes in the rasterizer.  I suspect that the intent of the minimumSizeHint is to make sure Qt never squashes the widget _all they way_ to 0 so the figure is always technically render able (if useless).

Given it has never worked, and we have other fixes for the issues it being missing caused, just removing it is also an option.  However, I still lean towards "fix it".

**Comment by QuLogic** [comment]
Fixed by #28732.
