### ISSUE TITLE
[Bug]: `Invalid vmax or vmin` for colormap with LogNorm scaling using vmin+vmax

### ISSUE THREAD

**Issue by aetherspritee** [matplotlib/matplotlib#28729]
### Bug summary

Scaling an image using the LogNorm function with vmin and vmax arguments causes crash during colorbar creation. Using LogNorm without vmin and vmax works as expected.

### Code for reproduction

```Python
y_min = np.min(data["opd_per_layer"]) # 0.0
y_max = np.max(data["opd_per_layer"]) # 372.61

fig, ax = plt.subplots(1,2, figsize=(16.4,  4, layout="constrained")

im = ax[0].imshow(data["opd_per_layer"],norm=colors.LogNorm(vmin=y_min,vmax=y_max),aspect="auto")
fig.colorbar(im, ax=ax[0], extend='max') # supplying custom vmax/vmin manually does not seem to help, tried values between 0-1, as well as values within the y_min/y_max range
```

### Actual outcome

  ```
File "/Users/dusc/Code/master/virga_tests/plot_vfall.py", line 282, in plot_cloud_opd
    fig.colorbar(im, ax=ax[i], extend='max')
  File "/Users/dusc/venv/lib/python3.11/site-packages/matplotlib/figure.py", line 1253, in colorbar
    cb = cbar.Colorbar(cax, mappable, **{
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dusc/venv/lib/python3.11/site-packages/matplotlib/colorbar.py", line 391, in __init__
    self._reset_locator_formatter_scale()
  File "/Users/dusc/venv/lib/python3.11/site-packages/matplotlib/colorbar.py", line 1153, in _reset_locator_formatter_scale
    self._process_values()
  File "/Users/dusc/venv/lib/python3.11/site-packages/matplotlib/colorbar.py", line 1091, in _process_values
    b = self.norm.inverse(b)
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dusc/venv/lib/python3.11/site-packages/matplotlib/colors.py", line 1802, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
```

### Expected outcome

A working colorbar.

### Additional information

As mentioned above, using LogNorm without vmin/vmax and passing those args into the colorbar does work for me.

### Operating system

MacOS 14.2.1

### Matplotlib Version

matplotlib version 3.9.2

### Matplotlib Backend

macosx

### Python version

3.11.3

### Installation

pip

**Comment by timhoffm** [comment]
You try to set vmin of the LogNorm to 0. This cannot work as the log can only map positive values.

**Comment by aetherspritee** [comment]
Makes sense, thank you. 
Is there a reason this does not lead to an error using the LogNorm normalization on the image? This seems confusing to me as the normalization works fine using the provided vmin/vmax values so i expected them to work with the colorbar as well.

**Comment by timhoffm** [comment]
Without having really tracked this down: I suppose the reason that it works on your image is that you data does not contain 0. On the other side, the colorbar must exhibit the full range between vmin and vmax, so trying to map vmin happens during calculation these visual of the colorbar.
