### ISSUE TITLE
[Doc]: Even on https://matplotlib.org/stable/: This is documentation for an unstable development version.

### ISSUE THREAD

**Issue by danielfaust** [matplotlib/matplotlib#28721]
### Documentation Link

https://matplotlib.org/stable/

### Problem

There is a red banner at the top suggesting to "Switch to stable version". When I click on the button, the page is reloaded at the same location.

### Suggested improvement

When visiting a page of the stable documentation (`https://matplotlib.org/stable/.*`), the banner `This is documentation for an unstable development version. [Switch to stable version]` should not be displayed.

**Comment by timhoffm** [comment]
I don’t see this.

**Comment by ksunden** [comment]
I actually _do_ see it, but I _think_ it is just a matter of fresh 3.9.2 release, and should be resolved upon merging #28711.

**Comment by QuLogic** [comment]
Yes, #28711 will fix it via https://github.com/matplotlib/matplotlib/pull/28711/commits/b7fc61e3edf6a4a4ce7ea2ea5b26f3df56c36182

**Comment by 2shaar** [comment]
This is still happening.

**Comment by timhoffm** [comment]
Thanks for the notification. Will be fixed via #30929.
