### ISSUE TITLE
[Bug]: Plotting numpy.arrray of dtype float32 with pyplot.imshow and specified colors.LogNorm produces wrong colors

### ISSUE THREAD

**Issue by faressc** [matplotlib/matplotlib#28731]
### Bug summary

Plotting an equal numpy.array of dtype float64 and float32 with pyplot.imshow and a defined colors.LogNorm as norm will produce different colors in the resulting image.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import numpy as np

norm = colors.LogNorm(vmin=1e-10, vmax=1)
test_numpy = np.array([[1e-4]])
test_numpy_32 = np.array([[1e-4]], dtype=np.float32)

for test in [test_numpy, test_numpy_32]:
    plt.imshow(test, norm=norm)
    plt.title(f"numpy array of dtype: {test.dtype}")
    plt.colorbar()
    plt.show()
```

### Actual outcome

The resulting plot for the dtype float64 numpy.array looks like this:

![float64](https://github.com/user-attachments/assets/64b75fc1-9a6f-4c35-8340-c285f26d0cd6)

and the plot for the dtype float32 numpy.array looks like this:

![float32](https://github.com/user-attachments/assets/dd53c1ab-95a5-453c-9a40-9a48e3f2bb85)

### Expected outcome

I would expect both outputs to have the same color.

### Operating system

Arch

### Matplotlib Version

3.9.1.post1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.12.4

### Installation

pip

**Comment by tacaswell** [comment]
I can confirm this, however it is related to having singular arrays:

```python
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import numpy as np

norm = colors.LogNorm(vmin=1e-10, vmax=1)
test_numpy = np.array([[1e-4, 1e-5, 1e-1]]).T
test_numpy_32 = np.array([[1e-4, 1e-5, 1e-1]], dtype=np.float32).T

fig, axl = plt.subplots(1, 2)

for ax, test in zip(axl, [test_numpy, test_numpy_32]):
    im = ax.imshow(test, norm=norm)
    ax.set_title(f"numpy array of dtype: {test.dtype}")
    fig.colorbar(im)

plt.show()
```

works correctly.

**Comment by tacaswell** [comment]
```python
ax.imshow(test, norm=norm, interpolation_stage='rgba')
```

Also fixes the problem so it is definitely in our data-value resampling code.

**Comment by tacaswell** [comment]
I think this is fixed by https://github.com/matplotlib/matplotlib/pull/28122 but that seems too big of a change to backport.

**Comment by ksunden** [comment]
Indeed, changing the bounds improves it significantly (I zoomed in pretty far, didn't try too many range sizes):


![Figure_1](https://github.com/user-attachments/assets/277fab7d-2e35-4c9b-a41f-f063fe31219e)
![Figure_2](https://github.com/user-attachments/assets/d01862ac-e2af-46fa-8603-5160f9668100)

**Comment by jklymak** [comment]
This is indeed fixed on master for both `interpolation_stage='rgba'` (the new default) and `interpolation_stage='data'` (the current default).  I don't think we are going to backport either https://github.com/matplotlib/matplotlib/pull/28122 or #28061, but I also don't think we should fix this just for a point release as this would be a long-standing behaviour.  Currently the workaround is `interpolation_stage='rgba'`.  I'll close as already fixed on master

**Comment by faressc** [comment]
Thanks for the quick answers and happy to hear that it has been already fixed. I'll use the workaround ` interpolation_stage='rgba'` for now :)
