### ISSUE TITLE
[MNT]: new build thinks it's installing 3.4.0.dev

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#28742]
### Summary

With a clean branch, I followed the instructions for [setting up in codespaces](https://matplotlib.org/devdocs/devel/contribute.html).  On installing Matplotlib I get:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seaborn 0.13.2 requires matplotlib!=3.6.1,>=3.4, but you have matplotlib 3.4.0.dev15432+g3891c15b1b which is incompatible.
Successfully installed matplotlib-3.4.0.dev15432+g3891c15b1b
```
I note that

1. The tests pass as well as they ever do, so there doesn't _seem_ to be a practical problem other than some confusion
2. I noticed this yesterday, but did not see a problem last Friday 16th, so whatever changed happened recently (unless you actually need a second codespace to reproduce :confused: ).
3. I have not checked building locally in the last day, so cannot say whether this is specific to codespaces.

### Proposed fix

I have no idea.

**Comment by tacaswell** [comment]
try `git fetch --tags` in the shell?

This looks like the newest tag that checkout has is 3.4.0 (and it is saying you are 15k commits past it!).

**Comment by tacaswell** [comment]
Checking out the commit it is claiming, I get:

```
✔ 13:05:33 [belanna] @ git checkout 3891c15b1b
Note: switching to '3891c15b1b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 3891c15b1b Merge pull request #28739 from anntzer/id
~/s/p/m/matplotlib v3.9.2-595-g3891c15b1b|⚑8
✔ 13:05:41 [belanna] @ git describe
v3.9.2-595-g3891c15b1b
```

which also suggests it is the "Missing tags" issue.

**Comment by rcomer** [comment]
> try `git fetch --tags` in the shell?

I tried this in combination with `git clean -fdx` but the result was the same.

**Comment by tacaswell** [comment]
What does

```
git tag --list
```

give?

**Comment by oscargus** [comment]
`git fetch upstream --tags`?

(Sorry if this is too basic, but I tried on my own computer and it took a few minutes to figure it out...)

**Comment by rcomer** [comment]
@oscargus has it - thanks!  I suspect the difference last week was that I branched of `upstream/main` _within_ the codespace.

I'm going to close this with no action because I doubt many contributors will manage to maneuver themselves into this situation!  Anyone can re-open if they disagree.
