### ISSUE TITLE
[Bug]: `colors.is_color_like` accepts "0" and "1" as valid colors

### ISSUE THREAD

**Issue by timtreis** [matplotlib/matplotlib#28759]
### Bug summary

We're using `colors.is_color_like` to identify whether a user passed the name of a column or maybe an actual color. However, the function returns `True` for "0" and "1", but `False` for all other numbers like "2". Seems like it converts booleans to colors?

### Code for reproduction

```Python
from matplotlib.colors import is_color_like
is_color_like("1")
```
```


### Actual outcome

True

### Expected outcome

False

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.9.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12

### Jupyter version

_No response_

### Installation

None

**Comment by tacaswell** [comment]
float values as strings between [0, 1] are valid colors for grayscale: see https://matplotlib.org/stable/users/explain/colors/colors.html#color-formats .  

This is long standing and documented behavior so I am going to close this as no-action as I think there is no chance we will deprecate this behavior.

**Comment by timtreis** [comment]
Okay, thanks for the quick answer!
