### ISSUE TITLE
[Bug]: Unable to generate a simple plot when compiled with Intel

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [matplotlib/matplotlib#28762]
### Bug summary

When numpy is compiled with Intel classic compilers (v2021.5.0) on Rocky 8.8 Linux, matplotlib v3.8.4 (also compiled with Intel) is unable to generate a basic plot.

### Code for reproduction

[simple_plot.py](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/simple_plot.html)

### Actual outcome

```console
$ python simple_plot.py
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/David.Huber/simple_plot.py", line 23, in <module>
    fig.savefig("test.png")
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2187, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 445, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 3034, in draw
    self._update_title_position(renderer)
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 2978, in _update_title_position
    ax.yaxis.get_tightbbox(renderer)  # update offsetText
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axis.py", line 1334, in get_tightbbox
    ticks_to_draw = self._update_ticks()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axis.py", line 1275, in _update_ticks
    major_locs = self.get_majorticklocs()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axis.py", line 1495, in get_majorticklocs
    return self.major.locator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/ticker.py", line 2142, in __call__
    return self.tick_values(vmin, vmax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/ticker.py", line 2150, in tick_values
    locs = self._raw_ticks(vmin, vmax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/ticker.py", line 2088, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_matplotlib/envs/matplotlib_intel/install/intel/2021.5.0/py-matplotlib-3.8.0-rnemqcl/lib/python3.11/site-packages/matplotlib/axis.py", line 2764, in get_tick_space
    return int(np.floor(length / size))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

### Expected outcome

![image](https://github.com/user-attachments/assets/057792fe-17a7-482f-9d8c-9df323d51773)

### Additional information

This build is accomplished via spack stack ([jcsda/spack-stack](https://github.com/jcsda/spack-stack)), but is likely reproducible via spack.  Attached is the output of `spack concretize`.
[concretize.log](https://github.com/user-attachments/files/16784591/concretize.log)
And here is the spack.yaml used to build the environment:
```yaml
spack:
  concretizer:
    unify: when_possible

  view: false
  include:
  - site
  - common

  definitions:
  - compilers: ['%intel']
  - packages:
    - python@3.11.7
    - py-matplotlib@3.8.0
  specs:
  - matrix:
    - [$packages]
    - [$compilers]
  packages:
    all:
      prefer: ['%intel']
```
The version of numpy that builds with this is 1.25.2.

This particular build was with matplotlib v3.8.0, but I have encountered the same issue with v3.8.4.
I have not tried v3.9.x or v3.10.x.

The issue is resolved if numpy v1.25.2 is installed via pip.  After building this environment, lmod modules are generated.  After loading the py-matplotlib and py-pip modules and unloading py-numpy, running the following generates the plot successfully:
```bash
#!/usr/bin/bash
python -m venv venv
source venv/bin/activate
pip install numpy=1.25.2
...
python simple_plot.py
```

### Operating system

Rocky 8.8

### Matplotlib Version

3.8.0-4

### Matplotlib Backend

agg

### Python version

3.11.7

### Jupyter version

N/A

### Installation

from source (.tar.gz)

**Comment by DavidHuber-NOAA** [comment]
Updated the OS version.  This particular system is actually running Rocky 8.8 Linux.

**Comment by jklymak** [comment]
It's pretty hard to guess what the error could be.  I presume somehow `length` in the above has come out as NaN, but that would mean your transform stack got corrupted with a NaN somewhere.  This is going to be hard to find unless we have someone who has access to an intel compiler.

**Comment by tacaswell** [comment]
If you change the version of numpy spack installs does it change anything?  I agree with @jklymak it is very likely that `length` is ending up as `np.nan` which means that something is very broken in the transform stack:

https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/axis.py#L2757-L2766

if `size` were `nan` it would have failed `if` and I'm struggling to come up with any other value `size` could take that would result in a `nan`

It is possible that something is stale / not initialized yet, but that does not track with installing numpy from pip fixing the issue.  Can you check `fig.get_size_inches()` right before you save?

If you remove setting the title does it work (or expose the same issue else where in the code)?

**Comment by DavidHuber-NOAA** [comment]
After repeating the exercise with gettext@0.19.8.1 (system version), the error is still present.

**Comment by tacaswell** [comment]
> I printed fig.get_size_inches, which returned [6.4 4.8]

Can you try forcing the backend to agg (to avoid any of our GUI fallback logic / chance a GUI toolkit is getting involved)?  This seems unlikely to be the fix as my theory as to why this would be a problem would be that the figure was getting sized of 0 in one or both dimensions.

> Unsetting the title did not fix the issue either.

It at least moves where it happens from trying to do some layout logic to actually drawing the `Axis` which takes one more complicating factor out of it.

Is there any chance you can get a post-mortum debugger session and poke at what is in `self.axes.transAxes`  and `self.figure.dpi_scale_trans` ?

**Comment by DavidHuber-NOAA** [comment]
The backend is agg presently, so that doesn't seem to be the issue.

I will look into debugging.

One more data point.  I built numpy with spack/gcc on the system and used that installation when building with spack/Intel.  This version was able to generate the plot.

**Comment by jklymak** [comment]
Did you try removing the (few) plot elements in the test script?  Maybe something triggers the error that will make this easier to track down?  Do other examples work?

**Comment by tacaswell** [comment]
attn @seberg is this may be related to how numpy is compiled.

**Comment by DavidHuber-NOAA** [comment]
@tacaswell Now that I recompiled numpy with Intel compilers, I have done some debugging.  In `axis.py`, I modified `get_tick_space` to the following:

```python
    def get_tick_space(self):
        ends = mtransforms.Bbox.unit().transformed(
            self.axes.transAxes - self.figure.dpi_scale_trans)
        length = ends.width * 72
        # There is a heuristic here that the aspect ratio of tick text
        # is no more than 3:1
        size = self._get_tick_label_size('x') * 3
        print(size, length)
        print(self.axes.transAxes)
        print(self.figure.dpi_scale_trans)
        print(ends)
        exit()
        if size > 0:
            return int(np.floor(length / size))
        else:
            return 2**31 - 1
```
This returned
```console
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
```

**Comment by jklymak** [comment]
Obviously the transform should not be nan here, but maybe it just hasn't been setup properly yet and we can work around this. Can you check for length being nan like size is checked for zero and see if the drawing gets further?  If all is sane in the world it will not, but if it succeeds maybe that is an easy fix

**Comment by tacaswell** [comment]
Can you also look at 

```
print(self.axes._position)
print(self.axes.self._originalPosition)
```

If it were a race, I would expect to win it sometimes and lose it sometimes, not always win or lose based on what machine it is being run on...

I suspect you don't even need the `ax.plot`, an empty axes should show the same problem...

**Comment by DavidHuber-NOAA** [comment]
@climbfuji found that this issue is not present with matplotlib v3.7.4 and numpy v1.23.5.  Also, this is not an issue when compiling with the Intel LLVM compilers (which we will be moving to in the next few months), so I think we have a workaround in the interim.  I'm OK with closing this issue, but leave that up to you.

That said, I worked through all of the places that I received errors for operations on `nan` and added filter checks to prevent said operations.  This ended up resulting in a blank plot and some warnings.  Below are the diffs:

```diff
diff --git a/lib/matplotlib/axis.py b/lib/matplotlib/axis.py
index 9adfb2cde7..c6d7e4ca72 100644
--- a/lib/matplotlib/axis.py
+++ b/lib/matplotlib/axis.py
@@ -92,6 +92,7 @@ class Tick(martist.Artist):
         size is the tick size in points
         """
         super().__init__()
+        print(axes)

         if gridOn is None:
             which = mpl.rcParams['axes.grid.which']
@@ -2518,7 +2519,13 @@ class XAxis(Axis):
         # There is a heuristic here that the aspect ratio of tick text
         # is no more than 3:1
         size = self._get_tick_label_size('x') * 3
-        if size > 0:
+        print(size, length)
+        print(self.axes.transAxes)
+        print(self.figure.dpi_scale_trans)
+        print(ends)
+        print(self.axes._position)
+        print(self.axes._originalPosition)
+        if size > 0 and not np.isnan(length):
             return int(np.floor(length / size))
         else:
             return 2**31 - 1
@@ -2760,7 +2767,7 @@ class YAxis(Axis):
         length = ends.height * 72
         # Having a spacing of at least 2 just looks good.
         size = self._get_tick_label_size('y') * 2
-        if size > 0:
+        if size > 0 and not np.isnan(length):
             return int(np.floor(length / size))
         else:
             return 2**31 - 1
diff --git a/lib/matplotlib/pyplot.py b/lib/matplotlib/pyplot.py
index 00e5dea071..8a0b97e330 100644
--- a/lib/matplotlib/pyplot.py
+++ b/lib/matplotlib/pyplot.py
@@ -2035,7 +2035,9 @@ def xticks(
     """
     ax = gca()

+    print(Tick)
     locs: list[Tick] | np.ndarray
+    print(locs)
     if ticks is None:
         locs = ax.get_xticks(minor=minor)
         if labels is not None:
@@ -2106,7 +2108,9 @@ def yticks(
     """
     ax = gca()

+    print(Tick)
     locs: list[Tick] | np.ndarray
+    print(locs)
     if ticks is None:
         locs = ax.get_yticks(minor=minor)
         if labels is not None:
diff --git a/lib/matplotlib/ticker.py b/lib/matplotlib/ticker.py
index df848ef04a..2bcd40f2a1 100644
--- a/lib/matplotlib/ticker.py
+++ b/lib/matplotlib/ticker.py
@@ -767,7 +767,7 @@ class ScalarFormatter(Formatter):
             oom = math.floor(math.log10(vmax - vmin))
         else:
             val = locs.max()
-            if val == 0:
+            if val == 0 or np.isnan(val):
                 oom = 0
             else:
                 oom = math.floor(math.log10(val))
@@ -788,10 +788,10 @@ class ScalarFormatter(Formatter):
         locs = (np.asarray(_locs) - self.offset) / 10. ** self.orderOfMagnitude
         loc_range = np.ptp(locs)
         # Curvilinear coordinates can yield two identical points.
-        if loc_range == 0:
+        if loc_range == 0 or np.isnan(loc_range):
             loc_range = np.max(np.abs(locs))
         # Both points might be zero.
-        if loc_range == 0:
+        if loc_range == 0 or np.isnan(loc_range):
             loc_range = 1
         if len(self.locs) < 2:
             # We needed the end points only for the loc_range calculation.
```

Here is the `simple_plot.py` that I ran:
```python
# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

print(1)
fig, ax = plt.subplots()
print(2)
ax.plot(t, s)
print(3)

# ax.set(xlabel='time (s)', ylabel='voltage (mV)',
#       title='About as simple as it gets, folks')
# ax.grid()

print(fig.get_size_inches())
print(4)
fig.savefig("test.png")
print(5)
plt.show()
```

And here is the terminal output:
```console
1
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
2
3
[6.4 4.8]
4
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
30.0 nan
BboxTransformTo(
    TransformedBbox(
        Bbox(x0=nan, y0=nan, x1=nan, y1=nan),
        BboxTransformTo(
            TransformedBbox(
                Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                Affine2D().scale(100.0)))))
Affine2D().scale(100.0)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Bbox(x0=nan, y0=nan, x1=nan, y1=nan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
Axes(nan,nan;nanxnan)
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
5
```

**Comment by tacaswell** [comment]
`self.axes._position` having `nan`s in it is the root the the problem (and something we clearly assume can never happen). 

On one hand, clear evidence that something that "should never happen" is happening is worth tracking down, but if this only happens on some machines with some versions of numpy with some compilers that is very hard to track down.

@DavidHuber-NOAA If you are willing to put a few more cycles into this, the next thing to check is chasing "up" from `plt.subplots()` to where the `Axes` object is created to sort out why `nans` are being passed in for the position (which should all be floats in [0, 1] specifynig the lower left, height, and width).

**Comment by climbfuji** [comment]
For clarification, this happens on ALL machines as long as numpy is version 1.24 and newer and numpy / matplotlib are compiled with Intel classic (icc, icpc, ifort).

**Comment by jklymak** [comment]
But does it happen for all matplotlibs?  Or is v3.7.4 always OK?

**Comment by climbfuji** [comment]
No, 3.7.4 fails with numpy version 1.24 

(Side note: according to spack , 3.8.0 requires numpy 1.25.2)

**Comment by DavidHuber-NOAA** [comment]
Digging in, I found the point where the `axes` attribute is first set to something besides `None` and it is at this point that it is initialized to `nan`s.  Here is the call sequence:

```console
  File "simple_plot.py", line 17, in <module>
    fig, ax = plt.subplots()
  File "pyplot.py", line 1604, in subplots
    axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=sharey,
  File "figure.py", line 938, in subplots
    axs = gs.subplots(sharex=sharex, sharey=sharey, squeeze=squeeze,
  File "gridspec.py", line 299, in subplots
    axarr[row, col] = figure.add_subplot(
  File "figure.py", line 788, in add_subplot
    ax = projection_class(self, *args, **pkw)
  File "axes/_base.py", line 674, in __init__
    self._init_axis()
  File "axes/_base.py", line 821, in _init_axis
    self.xaxis = maxis.XAxis(self, clear=False)
  File "axis.py", line 2335, in __init__
    super().__init__(*args, **kwargs)
```
Note that the line numbers are a little different with print statements inserted.

The `XAxis` class (a subclass of `Axis`) `__init__` method header is defined as
```python
def __init__(self, *args, **kwargs)
```
`*args` is then passed to `super().__init__`.

The `Axis` class (a subclass of `Artist`), has the following method header:
```python
def __init__(self. axes, *, pickradius=15, clear=True)
```

So the first argument to the `Axis` class is an `Axes` object.

Going back to the `XAxis` `__init__` method and printing `*args` as follows:

```python
args_str = ','.join(map(str,args))
print('args:')
print(args_str)
print('done')
```
returns
```console
args:
Axes(nan,nan;nanxnan)
done
```

It is not clear to me how `axes` is getting passed to the `XAxis` constructor when called here:
https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/axes/_base.py#L812

If you can point me where to check next, I will continue digging.

**Comment by DavidHuber-NOAA** [comment]
@tacaswell Just checking in.  Do you have any suggestions on where to look for the `axes` assignment discussed in my previous post?

**Comment by tacaswell** [comment]
> It is not clear to me how axes is getting passed to the XAxis constructor when called here:

I think it is the `self` (we are sitting in an `Axes` method here) and the expected first argument to the `Axis` is an `Axes` (trying to have this discussion verbally is...fun.  I tend to say "axes-with-an-E" and "axis-with-an-I").

I suspect the `Axes` object (who's init we are in) is ultimately from https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/figure.py#L781 (likely run through `GridSpec`).

I would focus on these two layers in the call stack:

```
  File "gridspec.py", line 299, in subplots
    axarr[row, col] = figure.add_subplot(
  File "figure.py", line 788, in add_subplot
    ax = projection_class(self, *args, **pkw)
```

and verify that the `fig.transFigure` and `fig.transSubFigure` are sensible at this point as well.

**Comment by DavidHuber-NOAA** [comment]
Alright, I found the issue, and it does appear to reside in NumPy.  The occurrence on `np.nan` first appears at
https://github.com/matplotlib/matplotlib/blob/84464dd085210fb57cc2419f0d4c0235391d97e6/lib/matplotlib/gridspec.py#L658

At this point,
```console
rows := np.ndarray([0 0])
bottoms := np.ndarray([0.11])
bottoms[rows] := np.ndarray([0.11 0.11])
bottoms[rows].min() := np.nan
```
And I'm able to replicate it simply with
```python
rows = np.asarray([0, 0])
val = np.asarray([0.11])
print(val[rows].min())
```

**Comment by DavidHuber-NOAA** [comment]
@tacaswell Actually, thinking about this a little more, I believe this may be a dual issue.  One with matplotlib and one with numpy.  For gridspec.py, `rows` is a length 2 index vector, but `fig_bottoms` is only one-dimensional.  Numpy should probably bark at this.  

For matplotlib, `get_grid_position` should probably always return a 2-D ndarray.

**Comment by DavidHuber-NOAA** [comment]
Opened https://github.com/numpy/numpy/issues/27840

**Comment by tacaswell** [comment]
I don't think the slicing array being longer than the thing being sliced is a problem as it goes down the "fancy slicing" path.

```>>> import numpy as np
>>> ref = np.asarray([0, 0])
>>> val = np.asarray([.1])
>>> val[ref]
array([0.1, 0.1])
>>> 
```

so this is a way to defer the broadcasting of a constant value a bit.

**Comment by tacaswell** [comment]
I am going to close this issue as you have tracked this back to compiler issues with vectorized instructions in numpy so there is nothing we can do in Matplotlib to fix (or even impact!) this issue.

----

@DavidHuber-NOAA Impressive work running this down!
