### ISSUE TITLE
[Bug]: matplotlib.ticker.LogLocator.tick_values(vmin, vmax) returns values outside of specified range

### ISSUE THREAD

**Issue by mesvam** [matplotlib/matplotlib#28774]
### Bug summary

matplotlib.ticker.LogLocator.tick_values(vmin, vmax) returns values outside of specified range

### Code for reproduction

```Python
import matplotlib

# major ticks
matplotlib.ticker.LogLocator().tick_values(1, 10)

# minor ticks
matplotlib.ticker.LogLocator(subs='auto').tick_values(1, 10)
```

### Actual outcome

```
> matplotlib.ticker.LogLocator().tick_values(1, 10)
array([  0.1,   1. ,  10. , 100. ])

> matplotlib.ticker.LogLocator(subs='auto').tick_values(1, 10)
array([2.e-01, 3.e-01, 4.e-01, 5.e-01, 6.e-01, 7.e-01, 8.e-01, 9.e-01,
       2.e+00, 3.e+00, 4.e+00, 5.e+00, 6.e+00, 7.e+00, 8.e+00, 9.e+00,
       2.e+01, 3.e+01, 4.e+01, 5.e+01, 6.e+01, 7.e+01, 8.e+01, 9.e+01,
       2.e+02, 3.e+02, 4.e+02, 5.e+02, 6.e+02, 7.e+02, 8.e+02, 9.e+02])
```

### Expected outcome

```
> matplotlib.ticker.LogLocator().tick_values(1, 10)
array([   1. ,  10. ])

> matplotlib.ticker.LogLocator(subs='auto').tick_values(1, 10)
array([2.e+00, 3.e+00, 4.e+00, 5.e+00, 6.e+00, 7.e+00, 8.e+00, 9.e+00])
```

### Operating system

Windows

### Matplotlib Version

3.8.4

### Python version

3.11.9

### Installation

conda

**Comment by rcomer** [comment]
Hi @mesvam, thanks for the report.  I think it is often the case that a locator’s `tick_values` method returns some values outside of the specified range.  This does not in general cause a problem because those "extra" values just don’t appear on the axis, since they are beyond the axis range.

Is this causing a practical problem for you or are you just flagging it as surprising behaviour?

**Comment by mesvam** [comment]
So I'm trying to have a LogLogator on a scale that is not logarithmic, since using the default 'asinh' scale ticks does not produce enough minor ticks.
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
ax.scatter(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
```
![Untitled](https://github.com/user-attachments/assets/dbe5a017-f808-4d65-9639-67048bd1baa4)
But if you simply set LogLocator as the minor locator, it also produces a bunch of ticks squeezed between 0 to 1, which doesn't look good. Also, there's no data there so there's no reason to have ticks there.
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
ax.scatter(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
ax.xaxis.set_minor_locator(mpl.ticker.LogLocator(subs='auto'))
```
![Untitled](https://github.com/user-attachments/assets/35b9286f-5327-47ac-aa04-f068518c356b)

Plus, let's say I only want minor ticks in the logarithmic range (from 10 to 1000) not the linear range (1 to 10). If I try to have LogLocator compute the tick locations for me instead of making my own implementation, it gives too many ticks outside of the range, which extends the auto axes limits.
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
ax.scatter(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
ticks = mpl.ticker.LogLocator(subs='auto').tick_values(10, 1e3)
ax.set_xticks(ticks, minor=True);
```
![Untitled](https://github.com/user-attachments/assets/e6649c49-7e6d-4d5c-aa4e-a2681430fdec)
Using AsinhLocator doesn't work either. You get ticks on the negative side of the axis
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
sns.lineplot(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
ax.xaxis.set_minor_locator(mpl.ticker.AsinhLocator(10, subs=tuple(np.arange(2, 10))))
```
None of the obvious options work as expected. And you end up having to hack something like this or just computing it all manually.
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
ax.scatter(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
ax.xaxis.set_minor_locator(mpl.ticker.LogLocator(subs='auto'))  # auto ticks
# then remove the extra ticks
xt = ax.get_xticks(minor=True)
inrange = (10 <= xt) & (xt <= 1000)
ax.set_xticks(xt[inrange], minor=True)
```
![Untitled](https://github.com/user-attachments/assets/50676e06-0f1f-4ea2-8195-53de795c0a7f)
In this particular case, you *can* make AsinhLocator work for you, but you have to manually define axes limits, and lie about linear_width=100 instead of the actual value 10, to get the desired output.
```
x = np.geomspace(1, 1e3, 100)
fig, ax = plt.subplots()
sns.lineplot(x=x, y=x)
ax.set_xscale('asinh', linear_width=10)
ax.set_xlim([0, None])
ax.xaxis.set_minor_locator(mpl.ticker.AsinhLocator(100, subs=tuple(np.arange(2, 10))))
```
![Untitled](https://github.com/user-attachments/assets/fb7fd44e-23d0-43ff-b6d0-f64be104de81)

**Comment by jklymak** [comment]
Our automatic tick locators have finite flexibility and are meant to work in common cases.  The asinh scale is meant to be used instead of symlognorm, and is therefore meant to go through zero, but be logarithmic away from zero. It's not clear why you would want to use it the way you are planning - and as you are finding, the defaults are not suitable. 

I'm going to close as this is not a bug in Matplotlib per se.  However if you want to discuss further feel free, or feel free to discuss at discourse.matplotlib.org
