### ISSUE TITLE
[ENH]: Improvement of Animation for wxagg

### ISSUE THREAD

**Issue by komoto48g** [matplotlib/matplotlib#28773]
### Problem

When using animation with `wxagg` backend, the frame rate seems to be limited, especially when the interval is small (e.g. 0 ms).

The test code:
https://matplotlib.org/stable/gallery/animation/simple_anim.html#sphx-glr-gallery-animation-simple-anim-py
```python
import matplotlib
matplotlib.use('wxagg') # causes a slow-down.

import matplotlib.pyplot as plt
import numpy as np

import matplotlib.animation as animation

fig, ax = plt.subplots()
ax.set_title(matplotlib.get_backend())

x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))

def animate(i):
    line.set_ydata(np.sin(x + i / 50))  # update the data.
    return line,

ani = animation.FuncAnimation(
    fig, animate, interval=0, blit=True, save_count=50)

plt.show()
```

https://github.com/user-attachments/assets/71dc1602-c763-4156-94fe-826026b2aa82

### Proposed solution

1. The frame interval can be specified with backend-independent.
2. Otherwise, warn about the frame rate limitation with `wxagg`.

**Comment by timhoffm** [comment]
I think `interval=0` is undefined. We probably sould catch non-positive `interval` values. What happens at `interval=1` (which I believe is the shortest supported interval)?

**Comment by komoto48g** [comment]
Thanks for your consideration, Tim.
The longer the interval, the less the visible difference.

It seems the situation is about the same for interval=1:

https://github.com/user-attachments/assets/c4ec16c8-5287-45de-bb36-eac1f245d263

But the difference between `wxagg` and `tkagg` becomes little for interval=3 or more:

https://github.com/user-attachments/assets/fd5df090-0d5c-409a-8e64-27590a597778

**Comment by timhoffm** [comment]
Could it be that you are hitting speed limits of the rendering - the timer events come faster than the backend needs to process the rendering? This may be backend-specific.

Semi-OT: Why do you need such high rendering frequencies? Even at 100hz, an interval of 10ms should be enough.

**Comment by komoto48g** [comment]
> Why do you need such high rendering frequencies? Even at 100hz, an interval of 10ms should be enough.

I understand the point. Yes, practically a delay time of 10 ms should be enough.
I just noticed this while playing with the animation (I am unfamiliar with it) and care about the differences between backends.

**Comment by komoto48g** [comment]
This is a backend-specific feature; there seems to be no room for improvement and little impact.
Therefore, I will close it.

**Comment by tacaswell** [comment]
The first rule of speeding up code is to not guess where the bottle neck is but to profile/measure.  I'm now going to guess where the bottle neck is.

Given the way animation works the exact same code on the mpl side is running (rasterize image with Agg, give buffer to GUI toolkit and get out of the way) my guess is that the source of the performance difference is in the GUI toolkits with tk being more efficient about getting the buffer on the screen.

A second guess (again have not gone to check code or docs or anything) is that the wx timer is "delay from finish of last callback" and the tk timer is "time from the start of the last callback" which for delays on the same order of magnitude as the execution time of the callback can have a big effect on the rate.
