### ISSUE TITLE
[Bug]: Titles for subplots between other subplots are not wrapped

### ISSUE THREAD

**Issue by DUOLabs333** [matplotlib/matplotlib#28847]
### Bug summary

See title --- if you create a `n x n`-subplot figure, and add titles with wrapping, for any subplot that's not at the beginning or end of a row, wrapping is not enabled.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

if not False:
    figure, axis = plt.subplots(4, 4, figsize=(10,10),layout="constrained")
    
    shape = axis.shape
    
    for idx, plot in enumerate(axis.ravel()):
        #score = scores[idx]
        plot.set_title(titles[idx],wrap=True)
        #plot.plot(score[2])
    #figure.set_constrained_layout(True)
```

### Actual outcome

![image](https://github.com/user-attachments/assets/3b256f1d-9399-47ce-9c63-24ce83a5fb32)

### Expected outcome

Each of the titles should be wrapped to the width of the subplot, with no overlap.

### Additional information

I'm not sure whether this matters, but this is using the inline backend in a Jupyter Notebook.

### Operating system

Arch Linux

### Matplotlib Version

3.9.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.11

### Jupyter version

4.2.5

### Installation

pip

**Comment by rcomer** [comment]
Text is wrapped to figures rather than axes.  You could work around this by making a grid of subfigures:

```python
import matplotlib.pyplot as plt

fig = plt.figure(layout='constrained')

subfigs = fig.subfigures(4, 4)

for subfig in subfigs.ravel():
    ax = subfig.add_subplot()
    ax.set_title('Extra Super Dooper Really Very Long Title', wrap=True)
    
plt.show()
```
![image](https://github.com/user-attachments/assets/2f66f574-760b-468e-bd94-9eb5df444b59)

**Comment by DUOLabs333** [comment]
Oh, thanks! That solved it perfectly (though I had to add `figsize(20, 20)` to `fig` to make all of my graphs visible --- otherwise, I got a warning about collapsed axes).
