### ISSUE TITLE
The wrong \Game symbol is used

### ISSUE THREAD

**Issue by ibell** [matplotlib/matplotlib#2886]
This seems to be a common problem with this symbol (http://sourceforge.net/p/texstudio/bugs/716/), and the symbol used by MPL doesn't agree with LaTeX.  If we do

``` python
import matplotlib.pyplot as plt
plt.title('$\Game$')
plt.savefig('fig.png')
```

we get
![fig](https://f.cloud.github.com/assets/1859947/2372581/b80ae92a-a83c-11e3-9ea9-f2c615fd622c.png)

while the character should be rendered as

![clipboard01](https://f.cloud.github.com/assets/1859947/2372585/de971fbe-a83c-11e3-9576-ac5e9fe10a34.png)

It seems the issue is that you are using the unicode character here, and the unicode character doesn't agree with LaTeX.

according to http://www.tex.ac.uk/tex-archive/info/symbols/comprehensive/symbols-a4.pdf

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue. Thanks!

**Comment by tacaswell** [comment]
This is still an issue, but it looks like it is an issue with the font we use and should be addressed upstream.
