### ISSUE TITLE
[Bug]: Unable to suppress minor ticks in loglog plot with constrained layout

### ISSUE THREAD

**Issue by jsdodge** [matplotlib/matplotlib#28864]
### Bug summary

For some layout settings, Matplotlib includes unwanted minor ticks in a loglog plot.

### Code for reproduction

```Python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

x = np.logspace(1, 7)
y = 0.01 * x

mpl.rcParams['font.size'] = 6
fig, axs = plt.subplots(
    nrows=2,
    ncols=2,
    sharex="col",
    figsize=(3.375, 2.8125),
    constrained_layout=True,
)
axs[0, 0].loglog(x, y)
axs[0, 0].set_yticks([1e-1, 1e1, 1e3, 1e5], minor=False)
plt.savefig("test-layout-6pt.pdf")

mpl.rcParams['font.size'] = 8
fig, axs = plt.subplots(
    nrows=2,
    ncols=2,
    sharex="col",
    figsize=(3.375, 2.8125),
    constrained_layout=True,
)
axs[0, 0].loglog(x, y)
axs[0, 0].set_yticks([1e-1, 1e1, 1e3, 1e5], minor=False)
plt.savefig("test-layout-8pt.pdf")
```

### Actual outcome

[test-layout-6pt.pdf](https://github.com/user-attachments/files/17091354/test-layout-6pt.pdf)
[test-layout-8pt.pdf](https://github.com/user-attachments/files/17091355/test-layout-8pt.pdf)

### Expected outcome

Minor ticks should not appear in `test-layout-6pt.pdf`.

### Operating system

MacOS 14.7

### Matplotlib Version

3.9.1

### Matplotlib Backend

macosx

### Python version

3.12.5

### Jupyter version

7.2.1

### Installation

pip

**Comment by jklymak** [comment]
The argument minor=False does not turn minor ticks off.  https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_yticks.html. You want to do set_yticks([], minor=True)

**Comment by jsdodge** [comment]
Ah, I see, thanks!
