### ISSUE TITLE
[Bug]: Why is there an offset between grey bars and width of arrows in upper limits using geometric mean 

### ISSUE THREAD

**Issue by siddhantmannaiith** [matplotlib/matplotlib#28867]
### Bug summary

For the image shown below, which shows upper limits in red arrows between two variables X and Y and on the right side there is Z axis showing value of grey bars, why is their an offset between grey bars and width of arrows.
![WirxJ5Lw](https://github.com/user-attachments/assets/d7f956f6-b111-4183-91d8-20620a42ed04)

### Code for reproduction

```Python
def plot(Xmin, Xmax):
    
    datafile = ''  # Placeholder for the data file path

    try:
        data = np.loadtxt(datafile)
        xmin = data[:, 0]
        xmax = data[:, 1]
        yvalue = data[:, 2]
        yerror = data[:, 3]
        zvalue = data[:, 4]
        upperBound = data[:, 5]

        # Compute the midpoint of the x-axis
        x = np.sqrt(xmin * xmax)
        xerr = np.array([x - xmin, xmax - x])

        # Compute y-axis values
        y = x**2 * yvalue / (xmax - xmin)
        yerr = x**2 * yerror / (xmax - xmin)
        y_ul = x**2 * upperBound / (xmax - xmin)
        y_ulerr = np.array([0.5 * y_ul, [0] * len(y)])

        # Create the plot
        fig, ax = plt.subplots()

        # Plot the data points where z > 9
        ax.errorbar(x[zvalue > 9], y[zvalue > 9], xerr=xerr[:, zvalue > 9], yerr=yerr[zvalue > 9], 
                    fmt='.k', color='blue', label='Detected', markersize=12)

        # Plot upper limits where z < 9, in red
        ax.errorbar(x[zvalue < 9], y_ul[zvalue < 9], xerr=xerr[:, zvalue < 9], yerr=y_ulerr[:, zvalue < 9], 
                    fmt='.k', color='red', uplims=True, label='Upper Limit', markersize=12)

        # Set axis limits and scales
        ax.set_xlim(a,b)
        ax.set_ylim(c, d)
        ax.set_xscale('log')
        ax.set_yscale('log')

        # Set axis labels with bold font
        ax.set_xlabel(r'X [units]', fontweight='bold')
        ax.set_ylabel(r'Y [units]', fontweight='bold', fontsize=9)

        # Plot z-values on a secondary axis
        ax2 = ax.twinx()
        ax2.bar(x, zvalue, width=(xmax - xmin), color='gray', edgecolor='gray', alpha=0.5)
        ax2.set_ylim(bottom=0)
        ax2.set_xscale('log')
        ax2.set_ylabel('Z value', fontweight='bold')

        # Return the file paths (placeholders)
        return png_file, pdf_file
```

### Actual outcome

![WirxJ5Lw](https://github.com/user-attachments/assets/2fd5b759-6a86-4c3d-b60d-d771a686e730)
In this plot their is an offset between grey bars and width of red arrows (which shows upper limits) when we use geometric mean in above code. 

### Expected outcome

There should not be an offset between grey bars and width of red arrows. When we tried using arithmetic mean the problem does resolve. Is their some bug with geometric mean. 

### Operating system

Ubuntu

### Matplotlib Version

3.7.1

### Installation

pip

**Comment by jklymak** [comment]
Can you include an example with fixed reproducible number, not your calculations, that demonstrates a clear problem with matplotlib?

**Comment by jklymak** [comment]
I've closed this for now as I think you are not passing the same widths to your error bar and bar calls and are asking us to help you debug.  You have also crossposted from stackoverflow. https://stackoverflow.com/questions/78989932/why-is-there-an-offset-between-grey-bars-and-width-of-arrows-in-upper-limits where you state Matplotlib works fine with other numbers. However if you do find a bug in Matplotlib please feel free to follow up and we can reopen

**Comment by siddhantmannaiith** [comment]
As @tillahoffmann mentioned in the other post I opened, I am adding a minimal reproducible code and the data here.
The data is available at https://github.com/siddhantmannaiith/data/blob/main/data.dat 

import matplotlib.pyplot as plt
import numpy as np

 data = np.loadtxt(data.dat)
xmin = data[:, 0]
xmax = data[:, 1]
zvalue = data[:, 4]

x = np.sqrt(xmin * xmax)
xerr = np.array([x - xmin, xmax - x])

fig, ax = plt.subplots()
ax.set_xscale('log')
ax.bar(x, zvalue, width=(xmax
![edge](https://github.com/user-attachments/assets/9e37ce3e-0165-4e50-9a67-27089b5903ac)
 - xmin), align="edge", alpha=0.4, edgecolor='black')

Now the problem is with the allignment of error bars, as i had shown in above figure they don't align particularly well. If I used align = "edge", we still don't get them at the center as one should expect. I have attached the plot with align = "edge"

**Comment by jklymak** [comment]
Your new minimal code does not use errorbar call and you are not showing the plot.  Further your new code is still not self-contained as you are asking us to download data 

Please discuss on stackoverflow or at discourse.matplotlib.org.  GitHub is for reporting reproducible bugs.  Thanks.
