### ISSUE TITLE
[Bug]: secondary_axis and log scale behaviour

### ISSUE THREAD

**Issue by subsurfaceiodev** [matplotlib/matplotlib#28878]
### Bug summary

As you can see in actual outcome, xticks are still shown when setting parent axes xscale to 'log' and xticks=[], this is not happening for linear scale.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2)
# linear ax (correct behaviour)
ax = axs[0]
secax = ax.secondary_xaxis('top')
secax.set(xlabel='linear')
secax.set_xticks([])

# log ax (incorrect? behaviour)
ax = axs[1]
secax = ax.secondary_xaxis('top')
secax.set(xlabel='log')
ax.set(xscale='log')
secax.set_xticks([])

plt.show()
```

### Actual outcome

![actual](https://github.com/user-attachments/assets/7eb1bb3d-455d-4f46-ac88-06cab1f49aec)

### Expected outcome

![expected](https://github.com/user-attachments/assets/e7bf72e5-a96f-4d4c-b0c0-704b8ab26be8)

### Operating system

Windows

### Matplotlib Version

3.9.2

### Python version

3.12

### Installation

pip

**Comment by timhoffm** [comment]
This is currently not possible. The reason is that the secondary axis aligns its scale with the primary axis during `draw()` and thus reverts your tick settings. Note that the secondary axis concept is still experimental and not everything may work as expected.

That said, what are you trying to achieve? Creating a secondary axis and then hiding all its ticks does not make sense to me. It's the very purpose of the seconday axis to show additional ticks.

**Comment by subsurfaceiodev** [comment]
Hi @timhoffm as always thanks for replying. I'm currently on the last phase of implementing plotly express functionality in matplotlib (i like to call it matplotlib express). As you can see in the image below, some use case scenarios require to have a secondary axis label, so i figured using secondary_axis and hiding ticks was the best approach, of course, it works only for linear axis scales.

![image](https://github.com/user-attachments/assets/4fc8893e-44b9-44d4-b616-72cf9490c60c)

**Comment by timhoffm** [comment]
`ax.set_title("sex=Female")` may be the thing you are looking for.

**Comment by subsurfaceiodev** [comment]
Right, that would work for that specific scenario, but secondary labels may also be needed for y axis (see image below)

![image](https://github.com/user-attachments/assets/4816a3f1-7997-49fd-8044-9af717fd11e3)

**Comment by subsurfaceiodev** [comment]
Alright, ill try that, thanks so much Tim
