### ISSUE TITLE
[Bug]: Strange errorbar caps when polar axes have non-default theta direction or theta zero location

### ISSUE THREAD

**Issue by Hem-W** [matplotlib/matplotlib#28885]
### Bug summary

For the `projection="polar"` axes that are set to use a different theta direction or theta zero location other than the default, the caps of `ax.errorbar` would be rotated strangely. 

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

theta = np.arange(0, 2 * np.pi, np.pi / 8)
r = theta / np.pi / 2 + 0.5

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(projection='polar')
ax.errorbar(theta, r, xerr=0.1, yerr=0.1, capsize=7, fmt="o", c="seagreen")
ax.set_title("Pretty polar error bars")
ax.set_theta_zero_location("N")
ax.set_theta_direction(-1)
plt.show()
```

### Actual outcome

![output](https://github.com/user-attachments/assets/b481f93f-8dbb-4195-af0d-71e766a76b8a)

### Expected outcome

The caps of error bars are expected to be still perpendicular to the error bar lines.

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.9.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.18

### Installation

conda

**Comment by timhoffm** [comment]
It seems errorbar caps currently do not account for a changed orientation due to `theta_zero_location` nor due to `theta_zero_direction`. Their angle stays the same as for the unmodifed plot.

**Comment by johnsonhsiung** [comment]
I’d love to give this issue a try and work on the fix!

**Comment by timhoffm** [comment]
@johnsonhsiung Got for it!

Tipp: use [PolarAxes.get_theta_offset](get_thehttps://matplotlib.org/stable/api/projections/polar.html#matplotlib.projections.polar.PolarAxes.get_theta_offset) and [PolarAxes.get_theta_direction](get_thehttps://matplotlib.org/stable/api/projections/polar.html#matplotlib.projections.polar.PolarAxes.get_theta_direction) to obtain the relevant numbers to include into the calculation.

**Comment by johnsonhsiung** [comment]
I ran into a problem while trying to setup. I'm currently following this guide: https://matplotlib.org/devdocs/devel/contribute.html

While running this command 
`python -m pip install --no-build-isolation --editable .[dev]` 

I got this error which was an easy fix by running `pip install ninja`. 
`meson-python: error: Could not find ninja version 1.8.2 or newer.` 


However, after running again the command again, I was hit with a longer error 
```
Obtaining file:///E:/opensource/matplotlib
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup E:\opensource\matplotlib E:\opensource\matplotlib\build\cp312 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=E:\opensource\matplotlib\build\cp312\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.2
      Source dir: E:\opensource\matplotlib
      Build dir: E:\opensource\matplotlib\build\cp312
      Build type: native build
      Program python3 found: YES
      Project name: matplotlib
      Project version: 0.1.0.dev51091+g69f09d1
      C compiler for the host machine: gcc (gcc 6.3.0 "gcc (MinGW.org GCC-6.3.0-1) 6.3.0")
      C linker for the host machine: gcc ld.bfd 2.28
      C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.28
      Host machine cpu family: x86
      Host machine cpu: x86
      Program python found: YES (E:\opensource\matplotlib\myenv\Scripts\python.exe)
      Need python for x86, but found x86_64
      Run-time dependency python found: NO (tried sysconfig)

      ..\..\meson.build:37:14: ERROR: Python dependency not found

      A full log can be found at E:\opensource\matplotlib\build\cp312\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I tried looking around online and was told to install from these two sites: 
1. https://sourceforge.net/projects/mingw/
2. https://developer.arm.com/downloads/-/gnu-rm

I installed them, deleted my virtual env, and repeated the steps, but still receive the same error. Any ideas on how to proceed?
Thank you! 

Also, here's the full log: [meson-log.txt](https://github.com/user-attachments/files/17139680/meson-log.txt)

**Comment by timhoffm** [comment]
Sorry, I cannot help setting up the compiler infrastructure on Windows. That's not my OS for development.

**Comment by timhoffm** [comment]
You may alternatively try GitHub Codespaces so that you don't have to do any local setup:

![image](https://github.com/user-attachments/assets/3538e16f-5378-4c01-bf51-1647f1ce5c71)

**Comment by vas1l** [comment]
I'd like to work on this issue if possible! Newcomer so I may need some assistance.

**Comment by vas1l** [comment]
> @johnsonhsiung Got for it!
> 
> Tipp: use [PolarAxes.get_theta_offset](https://matplotlib.org/stable/api/projections/polar.html#matplotlib.projections.polar.PolarAxes.get_theta_offset) and [PolarAxes.get_theta_direction](https://matplotlib.org/stable/api/projections/polar.html#matplotlib.projections.polar.PolarAxes.get_theta_direction) to obtain the relevant numbers to include into the calculation.

what do you mean?

**Comment by vas1l** [comment]
I think I have fixed the issue, unsure how to test or publish it however.

**Comment by vas1l** [comment]
![image](https://github.com/user-attachments/assets/e6d55791-f686-4533-b6c3-6308367dc74a)

**Comment by rcomer** [comment]
Removed the Good first issue label.  Partly in hope to not attract any more duplicate PRs, but also because I think the discussion in #28905 is beyond the first issue level!
