### ISSUE TITLE
[Bug]: Inconsistent behavior of the supported dtype of linedwith argument for the errorbar function

### ISSUE THREAD

**Issue by Vinvin202020** [matplotlib/matplotlib#28917]
### Bug summary

Linewidth argument in errorbar function can be specified as '1' which works as long as xerr and yerr arguments aren't specified in the code. However adding yerr= np.array(something) leads to a TypeError. To fix it, linewidth must be set to 1 instead of '1'.

### Code for reproduction

```Python
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 14:34:53 2024

@author: vince
"""

import numpy as np
import matplotlib.pyplot as plt

#%%
# Just generating simple data to serve as an example

x= np.linspace(0, 10, 10)

y= np.linspace(0, 10, 10)

y_err= np.linspace(0, 10, 10)

#%%

"""
The following code, with linewidth= '1',
works perfectly fine with no warning raised.
"""
plt.figure()
plt.errorbar(x, y, linewidth= '1', linestyle= '--', marker= '+')
plt.show()


#%%

"""
The following code, with linewidth= '1', crashes and raise the following error :
    TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'
"""

plt.figure()
plt.errorbar(x, y, yerr= y_err, linewidth= '1', linestyle= '--', marker= '+')
plt.show()

#%%
"""
Finally, the following code, with linewidth= 1, fixes the issue.
"""

plt.figure()
plt.errorbar(x, y, yerr= y_err, linewidth= 1, linestyle= '--', marker= '+')
plt.show()
```

### Actual outcome

<unknown>:33: SyntaxWarning: invalid escape sequence '\L'
Traceback (most recent call last):
  File ~\anaconda3\Lib\site-packages\IPython\core\formatters.py:343 in __call__
    return printer(obj)

  File ~\anaconda3\Lib\site-packages\IPython\core\pylabtools.py:170 in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File ~\anaconda3\Lib\site-packages\matplotlib\backend_bases.py:2204 in print_figure
    result = print_method(

  File ~\anaconda3\Lib\site-packages\matplotlib\backend_bases.py:2054 in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(

  File ~\anaconda3\Lib\site-packages\matplotlib\backends\backend_agg.py:496 in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)

  File ~\anaconda3\Lib\site-packages\matplotlib\backends\backend_agg.py:444 in _print_pil
    FigureCanvasAgg.draw(self)

  File ~\anaconda3\Lib\site-packages\matplotlib\backends\backend_agg.py:387 in draw
    self.figure.draw(self.renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\artist.py:95 in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)

  File ~\anaconda3\Lib\site-packages\matplotlib\artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\figure.py:3162 in draw
    mimage._draw_list_compositing_images(

  File ~\anaconda3\Lib\site-packages\matplotlib\image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\axes\_base.py:3137 in draw
    mimage._draw_list_compositing_images(

  File ~\anaconda3\Lib\site-packages\matplotlib\image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File ~\anaconda3\Lib\site-packages\matplotlib\collections.py:426 in draw
    renderer.draw_path_collection(

TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'

### Expected outcome

This inconsistency in the type supported by the linewidth argument of the errorbar function leads to really hard to find errors.
I assume either linewidth should ALWAYS support both '1' and 1 syntax or support only the numerical syntax. But it shouldn't be inconsistent by sometimes supporting '1' and sometimes not.

### Additional information

My hypothesis is that the errorbar function internally calls the plot function when neither yerr nor xerr are specified. 
The problem is that the plot function accepts '1' as a value for linewidth while the errorbar function doesn't.

This could either be fixed by modifying the plot function to raise an error/warning when the linewidth= '1' syntax is used or make sure that every matplotlib function having linewidth as an argument works with the '1' syntax.

### Operating system

Windows

### Matplotlib Version

3.9.2

### Matplotlib Backend

inline

### Python version

3.12.3

### Installation

conda

**Comment by rcomer** [comment]
Without specifying an error, you only have a `Line2D`, and that linewidth is [explicitly cast to float](https://github.com/matplotlib/matplotlib/blob/54d718e462ef2a9cc07b28050b17609b929c8bd4/lib/matplotlib/lines.py#L1138).  With an error specified, you draw a path collection, and [there is no such casting](https://github.com/matplotlib/matplotlib/blob/54d718e462ef2a9cc07b28050b17609b929c8bd4/lib/matplotlib/collections.py#L571-L589) there.  It looks like it would be easy to introduce it, though I do not know if the string support for `Line2D` is intended.

**Comment by rcomer** [comment]
My instinct would be to add the casting to `PathCollection` so that strings work in both cases.
1. It's easy to do.
2. It will make the API consistent without breaking any currently working code.

**Comment by timhoffm** [comment]
The documented API is float. That str works for Line2D is an implementation detail. We don't give any guarantee that this will continue to work in the future or that similar APIs accept str.

**Comment by Vinvin202020** [comment]
> The documented API is float. That str works for Line2D is an implementation detail. We don't give any guarantee that this will continue to work in the future or that similar APIs accept str.

Although it is a detail, I think this kind of inconsistency should be removed.

**Comment by timhoffm** [comment]
You have three choices:

- Support '1' als linestyle everywhere. Accepting strings for numbers is not a desirable API or usage scenario. We won't add specific code to support that.
- Prevent accepting strings everywhere. This is cumbersome and thinking this further, we'd need a lot of explicit type checks. Again, this would be a lot of extra code and is unideomatic, I.e. runs against the concept of dynamic typing.
- Do nothing and accept that some inputs are valid, even though not intended. If you want to be stricter and check what is intended, run a type checker, which will flag your str input as invalid.

Recognizing that Python is a dynamically typed language, the canonical approach is the third one.

**Comment by Vinvin202020** [comment]
> You have three choices:
> 
> * Support '1' als linestyle everywhere. Accepting strings for numbers is not a desirable API or usage scenario. We won't add specific code to support that.
> * Prevent accepting strings everywhere. This is cumbersome and thinking this further, we'd need a lot of explicit type checks. Again, this would be a lot of extra code and is unideomatic, I.e. runs against the concept of dynamic typing.
> * Do nothing and accept that some inputs are valid, even though not intended. If you want to be stricter and check what is intended, run a type checker, which will flag your str input as invalid.
> 
> Recognizing that Python is a dynamically typed language, the canonical approach is the third one.

Okay, thanks for your answer.
As I am not really experimented with Python (I am more of a C++ programmer), I am not really used to dynamically type languages, thus I perceive this kind of inconsitency as dramatic 😅, but I trust your expertise in stating that fixing it would cause more harm than good to the matplotlib library.
