### ISSUE TITLE
Axes3D cannot be accessed

### ISSUE THREAD

**Issue by MrCherub** [matplotlib/matplotlib#28912]
Matplotlib: 3.9.2
Python 3.12.6
Sequoia 15.0

I have reinstalled matplotlib 
numerous times and this specific sub-library cannot be accessed no matter what.

**Comment by QuLogic** [comment]
It is not clear what "cannot be accessed" means. What are you doing and what is the error?

**Comment by timhoffm** [comment]
It's still quite unclear what you are doing and where the message comes up.

Searching for the term"<module> is not accessed" indicates that it comes from Pylance. I suspect that have an environement / configuration issue. This may help: https://github.com/microsoft/pylance-release/discussions/5143

**Comment by MrCherub** [comment]
> @MrCherub Can you reduce the problem to a minimal (less than a screen of code) example?  

It may have something to do with the version of Python and matplotlib that I'm using. ![image](https://github.com/user-attachments/assets/a8b13b7b-570e-4e5d-894b-2dfbe81f47c7)
![image](https://github.com/user-attachments/assets/850df4ea-cef7-4d08-8eb5-88b83dd647a7)

"Changed in version 3.2.0: Prior to Matplotlib 3.2.0, it was necessary to explicitly import the mpl_toolkits.mplot3d module to make the '3d' projection to Figure.add_subplot." Maybe it's this?

**Comment by QuLogic** [comment]
The H is a hint, not an error. Again, please post what the actual error is when you run the code.

**Comment by MrCherub** [comment]
> The H is a hint, not an error. Again, please post what the actual error is when you run the code.

Can you explain to me why it's giving me that hint?
