### ISSUE TITLE
[ENH]: Is there a way to plot a long format data in matplotlib without pivoting the table ? 

### ISSUE THREAD

**Issue by infinity-void6** [matplotlib/matplotlib#28928]
### Problem

I am currently reading this book called Hands On Data Analysis using Pandas by Stefie Molin. There are two formats of data, wide and long format data. The author uses matplotlib to plot a wide format data while seaborn package the long format data. I tried searching in the web and it seems to be the custom. I tried asking gpt as well, and I can plot the long format data in matplotlib but it seems that I have to pivot the dataset. Is there a way around it .

Wide Data Frame Sample

date | TMAX | TMIN | TOBS
-- | -- | -- | --
2018-10-28 | 8.3 | 5.0 | 7.2
2018-10-04 | 22.8 | 11.7 | 11.7
2018-10-20 | 15.0 | -0.6 | 10.6
2018-10-24 | 16.7 | 4.4 | 6.7
2018-10-23 | 15.6 | -1.1 | 10.0

Long Data Frame Sample

date | datatype | value
-- | -- | --
2018-10-01 | TMAX | 21.1
2018-10-01 | TMIN | 8.9
2018-10-01 | TOBS | 13.9
2018-10-02 | TMAX | 23.9
2018-10-02 | TMIN | 13.9
2018-10-02 | TOBS | 17.2

Long Data Frame after pivoting

![image](https://github.com/user-attachments/assets/d6a059c6-666d-448d-8e19-7d3e50ca4bc7)

plot command for wide df
`ax = wide_df.plot(
    x='date',
    y=['TMAX', 'TMIN', 'TOBS'],
    figsize=(15, 5),
    title='Temperature in NYC in October 2018'
)
`
plot command for long df after pivot
`ax=long_df.pivot(index='date',columns='datatype',values='value')`

plot command for long_df with seaborn 
`ax=sns.lineplot(data=long_df,x='date',y='value',hue='datatype')`

Why isn't there a hue parameter or something similar in matplotlib for a long data format?

**Comment by rcomer** [comment]
None of the plotting functions you use here are native Matplotlib.  When you do `my_dataframe.plot(...)`, that is a Pandas function.  I suspect you may be better off asking this question over at Pandas.

**Comment by jklymak** [comment]
As above.  Pandas uses matplotlib - we don't decide how they use it.

**Comment by infinity-void6** [comment]
ahhh sorry about that beginners mistake, if incase anyone has any idea about this please do comment. I will post it on pandas as well
