### ISSUE TITLE
[Bug]: unexplicit error message when using `matplotlib.colors.rgb_to_hsv()` with wrong input

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [matplotlib/matplotlib#28941]
### Bug summary

When we use `matplotlib.colors.rgb_to_hsv()` with values outside 0 and 1, it's very difficult to understand our error because the error is raised by numpy. I think it would be much more intuitive to raise an explicit error message.

### Code for reproduction

```Python
from matplotlib.colors import rgb_to_hsv
rgb_to_hsv(arr=(24, 68, 48))
```

### Actual outcome

```
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

### Expected outcome

ValueError: matplotlib.colors.rgb_to_hsv requires values to be below 0 and 1.

(or similar)

### Operating system

mac

### Matplotlib Version

3.9.2

### Installation

pip

**Comment by JosephBARBIERDARNAL** [comment]
*Note: I'm willing to do a PR to fix this if it's not considered expected behaviour.*

**Comment by rcomer** [comment]
I agree that this should give a more useful error.  I think the cause of the current error is that the values are not floats.  I also get the error with

```python
rgb_to_hsv(arr=(1, 1, 1,))
```
however, this gives me a result (but probably shouldn't?)

```python
rgb_to_hsv(arr=(24., 68., 48.,))
```

**Comment by JosephBARBIERDARNAL** [comment]
For some reason, it works well on matplotlib 3.9.0:

```python
import matplotlib; print(matplotlib.__version__)
from matplotlib.colors import rgb_to_hsv
rgb_to_hsv(arr=(24.1, 68.8, 48.2))
```

3.9.0
array([ 0.42319165,  0.6497093 , 68.8       ])

**Comment by yuanx749** [comment]
I am using matplotlib 3.9.2 but getting no error. Guess it is due to numpy 2.x.

**Comment by timhoffm** [comment]
I think the correct fix is to always promote to float (`rgb_to_hsv(arr=(1, 1, 1,))` should work), but check the values ranges - Note that `arr_max` is already calculated below. So we can reuse that.

@JosephBARBIERDARNAL a PR would be very welcome.
