### ISSUE TITLE
Unexpected behavior of `add_patch` with points around zero and large `linewidth`

### ISSUE THREAD

**Issue by aivarsoo** [matplotlib/matplotlib#28969]
### Bug summary

`add_patch` method renders incorrectly, if the linewidth is set to a large number and the patch is generated from a random path using `PathPatch`. 

This bug was noticed while using `shapely`, but isolated to this minimal example

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import PathPatch
from matplotlib.path import Path

if __name__ == "__main__":
    num_points = 50
    path = np.random.randn(num_points, 2)
    path = Path(np.asarray(path))

    path_patch = PathPatch(path, facecolor="none", edgecolor="b", linewidth=7)
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.set_xlim([-150, 150])
    ax.set_ylim([-150, 150])
    ax.add_patch(path_patch)
    plt.show()
```

### Actual outcome

![image](https://github.com/user-attachments/assets/94f742bb-fc61-46b1-baa8-ca9481e8b7f3)

### Expected outcome

If the linewidth is set to 1, then the behaviour is more reasonable 
![image](https://github.com/user-attachments/assets/f4490260-3310-4413-b7a5-19584cdafd17)

### Operating system

OS/X Sonoma

### Matplotlib Version

3.9.2

### Matplotlib Backend

macosx

### Python version

3.9.6

### Installation

pip

**Comment by jklymak** [comment]
This is expected behaviour with the default join style of "mitre".  Please see https://matplotlib.org/stable/gallery/lines_bars_and_markers/joinstyle.html for examples of why this is.  You can try other joinstyles if you prefer.  However, I'm going to close this as Matplotlib is behaving as expected.
