### ISSUE TITLE
[Bug]: The Z-axis of 3D figures cannot be visualized properly.

### ISSUE THREAD

**Issue by ChevalierOhm** [matplotlib/matplotlib#28995]
### Bug summary

3D figures cannot be visualized properly.
1. The Z-axis should be vertical, but it's not.
2. Z-axis label is not fully displayed.
How to solve these issues?

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(-5, 5, 100)
Y = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(X, Y)
Z = np.sin(np.sqrt(X**2 + Y**2))

fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X, Y, Z, cmap='viridis')

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
ax.set_title('3D Surface Plot')
ax.view_init(elev=30, azim=120)

plt.tight_layout()
plt.show()
```

### Actual outcome

![无标题](https://github.com/user-attachments/assets/9690f54e-127b-4bd1-b7b5-ffcbbf7b09f0)

### Expected outcome

1. The Z-axis should be vertical.
2. Z-axis label should be fully displayed.

### Matplotlib Version

3.9.2

### Installation

None

**Comment by timhoffm** [comment]
You may be looking for `ax.set_proj_type('orth')`. See https://matplotlib.org/stable/gallery/mplot3d/projections.html

**Comment by scottshambaugh** [comment]
Hi @ChevalierOhm, I'm going to close this ticket since it seems like your first point was answered above and your second is captured in another ticket, but please feel free to reopen if you have more questions!
