### ISSUE TITLE
Matplotlib does not display hatching when rendering to pdf

### ISSUE THREAD

**Issue by synapticarbors** [matplotlib/matplotlib#29]
I am attempting to use the hatching feature in matplotlib, which works fine when displaying to screen. However when I save the figure to pdf format, the hatch marks are not rendered:

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,2*np.pi,100)

plt.figure()
plt.fill(x,np.sin(x),color='blue',alpha=0.5,hatch='/')
plt.show()
plt.savefig('./test.pdf',format='pdf')
```

I am using matplotlib 1.0.1 on OS X 10.6.6 (Specifically the Enthought Python Distribution v7). 

Upon posting the issue initially to Stackoverflow, I received a workaround for the issue by using:

```
plt.fill(x,np.sin(x),color='blue',alpha=0.5)
plt.fill(x,np.sin(x),color='None',alpha=0.5,edgecolor='blue',hatch='/')
```

Not sure why this works, but it saves the pdf correctly when using the two commands in combination.

**Comment by dirteat** [comment]
This is a "feature" of MAC OSX which is called "anti-aliasing".
I've encountered the same problem recently (with recent version of mpl), the hatches are actually quite thin, and the MAC OSX PDF anti-aliasing filters just smooth them to vanish.

Opening the same figure with Xpdf just works fine ;)

It would be helpful to have some control on hatches thickness (mpl.rcParams[] seems to be ignored for hatches within a contourplot).

**Comment by WeatherGod** [comment]
@dirteat, could you open a new issue describing this problem in more detail? The original bug here is different, and we don't want to confuse the two (similar) problems.
