### ISSUE TITLE
[Bug]: `cmap` mutating inputs

### ISSUE THREAD

**Issue by ajfriend** [matplotlib/matplotlib#29002]
### Bug summary

Input vectors to color maps are being mutated. I would expect them to be unchanged.

### Code for reproduction

```Python
import pandas as pd
import matplotlib

cmap = matplotlib.colormaps['magma']
value = pd.Series([.1, .2, .3, .4])
out = cmap(value)
print(value)
```

### Actual outcome

input `value` vector is changed.

```
0     25.6
1     51.2
2     76.8
3    102.4
dtype: float64
```

### Expected outcome

input `value` vector is not changed.

```
0    0.1
1    0.2
2    0.3
3    0.4
dtype: float64
```

### Operating system

macos 14

### Matplotlib Version

'3.9.2'

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.11.8

### Jupyter version

4.2.5

### Installation

pip

**Comment by ajfriend** [comment]
Oh, another point: this only seems to happen to `pd.Series`, but not to numpy arrays.

**Comment by timhoffm** [comment]
We do

https://github.com/matplotlib/matplotlib/blob/9bfc330430b13753ba983549929e8c39ae5ee495/lib/matplotlib/colors.py#L772

but apparently, this does not copy data for a Series. I claim this is a bug either in numpy or pandas and should be reported there.

**Comment by kylebarron** [comment]
It looks like pandas doesn't implement the `copy` parameter for `__array__`:
https://github.com/pandas-dev/pandas/blob/2a10e04a099d5f1633abcdfbb2dd9fdf09142f8d/pandas/core/series.py#L844-L845

**Comment by jklymak** [comment]
I'll go ahead and close then.  We don't advertise cmap accepting a pandas series, so I don't think we would entertain trying to work around this. Please follow up with pandas if you need this functionality.

**Comment by timhoffm** [comment]
Upstream issue: https://github.com/pandas-dev/pandas/issues/57739

**Comment by ajfriend** [comment]
Thanks all! Its definitely helpful to know that the issue is with `pandas`.
