### ISSUE TITLE
[ENH]: implement back/forward buttons on mouse move events on macOS

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#29045]
### Problem

A followup to #28453, as @anntzer didn't have such a mouse. @tacaswell promised to look into it.

### Proposed solution

From https://github.com/matplotlib/matplotlib/pull/28453#issuecomment-2439441177:

> Looking at it again I note that I don't try to report back/forward for macos just because I don't have such a mouse to test, but perhaps mpl_buttons() in _macosx.m just needs some additional entries for 1<<3 and 1<<4? (see https://developer.apple.com/documentation/appkit/nsevent/1527943-pressedmousebuttons for the docs)

**Comment by tacaswell** [comment]
Please do not block 3.10rc1 on this.
