### ISSUE TITLE
[Bug]: `secondary_xaxis` produces ticks at incorrect locations

### ISSUE THREAD

**Issue by dkweiss31** [matplotlib/matplotlib#29067]
### Bug summary

It is possible I'm doing this incorrectly, but for a very simple example `secondary_xaxis` puts tick marks at incorrect locations. Modifying slightly the interpolation example from here https://matplotlib.org/stable/gallery/subplots_axes_and_figures/secondary_axis.html:

### Code for reproduction

```Python
fig, ax = plt.subplots(constrained_layout=True)
xdata = np.arange(0, 11, 0.4)
ydata = np.random.randn(len(xdata))
ax.plot(xdata, ydata, label='Plotted data')
ax.set_xlabel('X [m]')
ax.legend()
xnew = xdata**2


def forward(x):
    return np.interp(x, xdata, xnew)


def inverse(x):
    return np.interp(x, xnew, xdata)

secax = ax.secondary_xaxis('top', functions=(forward, inverse))
secax.xaxis.set_minor_locator(AutoMinorLocator())
secax.set_xlabel('$X_{other}$')

plt.show()
```

### Actual outcome

<img width="627" alt="image" src="https://github.com/user-attachments/assets/cb45f32e-4f53-4f6a-ad9d-4eed2c948c35">

### Expected outcome

Notice that e.g. 0 on the lower axis is not aligned with 0 on the top and 10 on the bottom is not aligned with 100 on the top.

### Operating system

OS/X

### Matplotlib Version

3.9.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.14

### Jupyter version

7.2.2

### Installation

pip

**Comment by jklymak** [comment]
Your interpolation won't go lower than zero, but the main axis has negative values so the secondary axes is not one to one. Your forward and reverse should take care of negative values, probably leaving them the same or doing -x**2

**Comment by jklymak** [comment]
Or just set_xlim(min=0)...

**Comment by dkweiss31** [comment]
Thanks for the quick reply @jklymak ! You're right about the negative values but I was hoping that the top x axis would not go negative and start at 0, same as the bottom x axis. As you suggest the following works code works by specifying the limits (note that if I don't specify the right xlim, the top x axis is still not correct). However it doesn't have the nice buffer of white space on the left and right that we are used to. Is there a way to retain that nice behavior with `secondary_xaxis`?
```python
fig, ax = plt.subplots(constrained_layout=True)
xdata = np.arange(0, 11, 0.4)
ydata = np.random.randn(len(xdata))
ax.plot(xdata, ydata, label='Plotted data')
ax.set_xlim(left=xdata[0], right=xdata[-1])
ax.axvline(10, color="grey")
ax.set_xlabel('X [m]')
ax.legend()
xnew = xdata**2

def forward(x):
    return np.interp(x, xdata, xnew)


def inverse(x):
    return np.interp(x, xnew, xdata)

secax = ax.secondary_xaxis('top', functions=(forward, inverse))
secax.xaxis.set_minor_locator(AutoMinorLocator())
secax.set_xlabel('$X_{other}$')

plt.show()
```
Producing 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/a1ac1b3c-26de-4713-93be-cd85d75018cf">

**Comment by jklymak** [comment]
There is an explicit note about this in https://matplotlib.org/stable/gallery/subplots_axes_and_figures/secondary_axis.html#sphx-glr-gallery-subplots-axes-and-figures-secondary-axis-py:

```
In order to properly handle the data margins, the mapping functions (forward and inverse in this example) need to be defined beyond the nominal plot limits.

In the specific case of the numpy linear interpolation, [numpy.interp](https://numpy.org/doc/stable/reference/generated/numpy.interp.html#numpy.interp), this condition can be arbitrarily enforced by providing optional keyword arguments left, right such that values outside the data range are mapped well outside the plot limits.
```

**Comment by dkweiss31** [comment]
I'm not sure that's the only issue here: it seems that this functionality doesn't play nice with `interp`. The following simple example which does away with the negative complications works fine for the first set of functions and doesn't for the second set:
```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(constrained_layout=True)
xdata = np.arange(2, 11, 0.4)
ydata = np.random.randn(len(xdata))
ax.plot(xdata, ydata, label='Plotted data')
ax.axvline(10, color="grey")
ax.set_xlabel('X [m]')
ax.legend()
xnew = 2 * xdata

# def forward(x):
#     return 2 * x
#
#
# def inverse(x):
#     return x / 2


def forward(x):
    return np.interp(x, xdata, xnew)


def inverse(x):
    return np.interp(x, xnew, xdata)

secax = ax.secondary_xaxis('top', functions=(forward, inverse))
secax.set_xlabel('$X_{other}$')

plt.show()
```
first set:
<img width="645" alt="image" src="https://github.com/user-attachments/assets/c7146506-d433-47f8-808e-4c2724448be7">
second set (interp)
<img width="639" alt="image" src="https://github.com/user-attachments/assets/813ed22c-15d9-4aae-9f98-1992a85f09f8">

**Comment by dkweiss31** [comment]
Ahh I see: that worked, thanks! Unless I'm mistaken about what the tutorial is trying to show, it might be suffering from the same problem I was running into. If there is interest I'd be happy to submit a PR to update the tutorial based on our discussion.
