### ISSUE TITLE
[MNT]: Add a default `markevery` for lines in rcParams

### ISSUE THREAD

**Issue by LorenzoPeri17** [matplotlib/matplotlib#29063]
### Summary

`markevery` is the only property regarding lines for which it is not possible to set a default value in `rcParams`.
This property would be convenient if a user wants to set a default value, rather then needing to specify for each plot.

### Proposed fix

Add `lines.markevery : None` to the defaut `matplotlibrc`

**Comment by jklymak** [comment]
This is a duplicate of #29025. Feel free to discuss there.
