### ISSUE TITLE
[Bug]: bar chart with variable fill not working

### ISSUE THREAD

**Issue by igurin-invn** [matplotlib/matplotlib#29072]
### Bug summary

An array-like `fill` argument to `plt.bar` has no effect.

### Code for reproduction

```Python
plt.bar([1, 2, 3], [1, 2, 3], fill=(False, True, False), color=('C1', 'C2', 'C3'))
```

### Actual outcome

![image](https://github.com/user-attachments/assets/948e23e3-b6b9-4153-b10c-4612683751a8)

### Expected outcome

![image](https://github.com/user-attachments/assets/ba3b9edb-cbb3-4c7a-8e6e-a41b149efa47)

### Operating system

Windows

### Matplotlib Version

3.8.4

### Matplotlib Backend

'module://matplotlib_inline.backend_inline'

### Python version

3.12.4

### Jupyter version

7.2.2

### Installation

conda

**Comment by jklymak** [comment]
Did this work in the past?  Fill is passed down ti Rectangle and I don't think it was ever done on a per-Rectangle basis, but I could be wrong.

**Comment by igurin-invn** [comment]
I haven't tried this before.

**Comment by QuLogic** [comment]
`fill` is not documented as being vectorized like that.

**Comment by timhoffm** [comment]
You can achieve the same effect by specifying `facecolor` and `edgecolor`, which both accept sequences. Use "none" as facecolor for the unfolded bars.

**Comment by Satyanarayana3012** [comment]
import matplotlib.pyplot as plt

x = [1, 2, 3]
y = [1, 2, 3]

fill_colors = ['none', 'C2', 'none']
outline_colors = ['orange', 'green', 'pink']

for i in range(len(x)):
    plt.bar(
        x[i], 
        y[i], 
        color=fill_colors[i],      
        edgecolor=outline_colors[i] 
    )

plt.show()
![github](https://github.com/user-attachments/assets/acbeb64f-3918-45ca-bd63-4ef03e3b1ca2)
Try this code

**Comment by rcomer** [comment]
@Satyanarayana3012 you can avoid the loop with

```python
plt.bar(x, y, color=fill_colors, edgecolor=outline_colors)
```

**Comment by timhoffm** [comment]
I prefer not to extend the fill parameter to support sequences. `bar()` currently uses a list or Rectangles as artists, and so individual fills would be possible. However, we may migrate to a Collection at some point. And collections do not support the fill property. The canonical apporach, which is also used in Collections is to use a sequence of `facecolors` and set unfilled elements to "none".

I therefore close this.

**Comment by igurin-invn** [comment]
The [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar) does not identify any of the `kwargs` as accepting sequences, so I don't understand how I was supposed to figure this out.

I also don't understand the solution. All of the following produced errors.
```python
 plt.bar([1, 2, 3], [1, 2, 3], color=('C1', 'C2', 'C3'), facecolor=(None, 'C2', None))
 plt.bar([1, 2, 3], [1, 2, 3], color=('C1', 'C2', 'C3'), facecolor=('none', 'C2', 'none'))
 plt.bar([1, 2, 3], [1, 2, 3], edgecolor=('C1', 'C2', 'C3'), facecolor=('none', 'C2', 'none'))
 plt.bar([1, 2, 3], [1, 2, 3], edgecolor=('C1', 'C2', 'C3'), facecolor=['none', 'C2', 'none'])
```

**Comment by jklymak** [comment]
Yeah, I'll take the liberty of reopening.  *facecolor* definitely doesn't work, though *color* instead of *facecolor* works fine.  Not sure if this is a behavior issue or just documentation.  It's a bit goofy that *edgecolor* works, but *facecolor* does not, in my opinion.

**Comment by igurin-invn** [comment]
Thanks!

For the record, the single-line solution is:
```python
plt.bar([1, 2, 3], [1, 2, 3], color=['none', 'C2', 'none'], edgecolor=['C1', 'C2', 'C3'])
```

Note also that `'none'` is not a [documented color](https://matplotlib.org/stable/users/explain/colors/colors.html). (Neither is `None`, which does not in fact work, but is reasonable to try.)

**Comment by igurin-invn** [comment]
This is a bit down in the weeds, but a workaround using only documented _colors_ is:
```python
plt.bar([1, 2, 3], [1, 2, 3], edgecolor=('C1', 'C2', 'C3'), color=('w', 'C2', 'w'))
```
This is not identical (considering the possibility of a non-white background), and it does still use the undocumented vectorization of `edgecolor`.

**Comment by rcomer** [comment]
The documentation does state that _color_ and _edgecolor_ may be lists.

![image](https://github.com/user-attachments/assets/52dce0da-3c30-4105-b682-3923e0fd2d9c)

**Comment by timhoffm** [comment]
`facecolor` should be made to accept sequences. I've opened #29090 for that.

`color` and `edgecolor` have special handling for accepting the sequences and are therefore listed explicitly. Generally, all kwargs are otherwise passed through to each `Rectange` - the list of rectangle properties is auto-generated and therefore also contains `color` and `edgecolor` in their original form. The auto-generation does not know about the special handling.
I think the documentation is okish as is, and it's not worth to jump extra hoops to remove the duplication. The specially handled parameters are documented explicitly and more prominently. Their functionality is a  superset of the original functionality, so the auto-generated table is not wrong, only incomplete.
