### ISSUE TITLE
Expose ax.yaxis.labelpad and ax.xaxis.labelpad to the rc file

### ISSUE THREAD

**Issue by saullocastro** [matplotlib/matplotlib#2907]
While trying to change the gap between the axis title and the tick labels I found this thread:

http://matplotlib.1069221.n5.nabble.com/Distance-between-axis-and-axis-label-td1181.html

Where it is explained that using:

    ax.xaxis.labelpad
    ax.yaxis.labelpad

One can adjust this gap. It works perfectly, but the problem is that I have to add some lines in everycode I need this adjustment. I tried to include in my ``maplotlibrc`` file these two lines and it gives:

    Bad key "ax.yaxis.labelpad" on line 247 in
    ...\.matplotlib\matplotlibrc.
    You probably need to get an updated matplotlibrc file from
    http://matplotlib.sf.net/_static/matplotlibrc or from the matplotlib source
    distribution

**Comment by Tillsten** [comment]
@tacaswell Sorry, is this in 1.4.3?

**Comment by tacaswell** [comment]
@Tillsten no, and I just noticed this went in with out proper documentation.

Re-opening as a reminder to add a line to Whats new.
