### ISSUE TITLE
[MNT]: More consistent color parameters for bar()

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#29090]
### Summary

From #29072. `bar()` supports

- `color` : color or list of color
- `edgecolor` : color or list of color
- `facecolor`: color

i.e.

- `facecolor` cannot take a sequence
- there are no plural aliase (e.g. `edgecolors`)
- likely (t.b.c.) the aliases also do not support sequences, similar to #28884

### Proposed fix

Make `facecolor` accept sequences and check that the parameter precedence among `color`, `edgecolor` and `facecolor` is reasonable and comparable with `scatter`, which can take an explicit color via `c` (equivalent to `color` here).

For now, I'd refrain from introducing plural aliase. `bar()` is originally and primarily a style-all-bars-identical function. Per-bar styling was added later on, and I don't think there's a strong need to support this additional use case with an added plural alias.

**Comment by vsanthapur** [comment]
Hi Matplotlib team! My partner and I would like to work on this issue as part of a project for our software engineering class. We're looking forward to contributing by improving the consistency of the bar() function’s color parameters. Any guidance or pointers on starting would be greatly appreciated!

Thanks very much!
