### ISSUE TITLE
[Doc]: ax.scatter `alpha` also supports an array-like of floats

### ISSUE THREAD

**Issue by EwoutH** [matplotlib/matplotlib#29101]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.scatter.html

### Problem

Aside from float, ax.scatter `alpha` also supports an array-like of floats.

### Suggested improvement

It would be useful if this was documented, potentially including an example.

**Comment by ksunden** [comment]
I think this is a reasonable documentation update.

There was some question to me as to whether putting an array was "intended behavior" or not, which would have had me pushed in the other direction (e.g. validating that it is _not_ array-like). In this instance, `alpha` is only ever used as a pass through to the underlying PathCollection, and alpha on Collections is documented as array-like or scalar or None.

I think it is reasonable to use the alpha value separate from the color/size/etc, and it already works, so I do not have a problem documenting it as such.

**Comment by NGWi** [comment]
@EwoutH, is the following an example of what you had in mind?
```python
import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = np.arange(10)
y = np.arange(10)

# Generate random alpha values for each point
alpha_values = np.random.rand(10)

# Create the scatter plot with individual alpha values
plt.scatter(x, y, c='blue', s=50, alpha=alpha_values)

plt.title('Scatter Plot with Individual Alpha Values')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

plt.show()
```
![image](https://github.com/user-attachments/assets/efa10534-6ea6-42a2-894c-96a6a980c52d)

**Comment by EwoutH** [comment]
Yes, I think that shows it well! Quite elegant minimal example.

**Comment by timhoffm** [comment]
Technically, this is documented, even though very hidden:

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter has

> **kwargs : [Collection](https://matplotlib.org/devdocs/api/collections_api.html#matplotlib.collections.Collection) properties

https://matplotlib.org/devdocs/api/collections_api.html#matplotlib.collections.Collection has

> **kwargs
>     Remaining keyword arguments will be used to set properties as Collection.set_{key}(val) for each key-value pair in kwargs.

https://matplotlib.org/devdocs/api/collections_api.html#matplotlib.collections.Collection.set_alpha

declares that array-likes are accepted.


I believe the reasonable improvement here is to list the accepted kwarg parameters explicitly, similar to https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.tripcolor.html#matplotlib-axes-axes-tripcolor.
