### ISSUE TITLE
[Bug]: Automated test failing

### ISSUE THREAD

**Issue by NGWi** [matplotlib/matplotlib#29131]
### Bug summary

One of the tests in the automated suite has been failing during PRs since this morning: https://github.com/matplotlib/matplotlib/actions/workflows/tests.yml 
Tests #25844 and on

### Code for reproduction

```Python
=========================== short test summary info ============================
FAILED lib/matplotlib/tests/test_backends_interactive.py::test_interactive_backend[toolmanager-MPLBACKEND=wxagg-BACKEND_DEPS=wx] - Failed: Subprocess failed to test intended behavior
<frozen _collections_abc>:982: UserWarning: Treat the new Tool classes introduced in v1.5 as experimental for now; the API and rcParam may change in future versions.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/matplotlib/matplotlib/lib/matplotlib/tests/test_backends_interactive.py", line 232, in _test_interactive_impl
    assert result.getvalue() == result_after.getvalue()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Actual outcome

=========================== short test summary info ============================
FAILED lib/matplotlib/tests/test_backends_interactive.py::test_interactive_backend[toolmanager-MPLBACKEND=wxagg-BACKEND_DEPS=wx] - Failed: Subprocess failed to test intended behavior
<frozen _collections_abc>:982: UserWarning: Treat the new Tool classes introduced in v1.5 as experimental for now; the API and rcParam may change in future versions.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/matplotlib/matplotlib/lib/matplotlib/tests/test_backends_interactive.py", line 232, in _test_interactive_impl
    assert result.getvalue() == result_after.getvalue()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Expected outcome

No hard failures.

### Additional information

https://github.com/matplotlib/matplotlib/actions/workflows/tests.yml

### Matplotlib Version

GitHub Repo / Dev Version

### Installation

git checkout

**Comment by timhoffm** [comment]
See #29129.

**Comment by NGWi** [comment]
@timhoffm, thanks. Hopefully, we can track down the change that introduced that issue.
