### ISSUE TITLE
[Bug]: Poly3DCollection initialization cannot properly handle parameter verts when it is a list of nested tuples and shade is False 

### ISSUE THREAD

**Issue by williamlus** [matplotlib/matplotlib#29156]
### Bug summary

The initialization of an `mpl_toolkits.mplot3d.Poly3DCollection` object cannot properly handle the parameter `verts` when `verts` = a list of (N, 3) array-like nested tuples, and `shade=False`.

### Code for reproduction

```Python
from mpl_toolkits.mplot3d import art3d
corners = ((0, 0, 0), (0, 5, 0), (5, 5, 0), (5, 0, 0))
tri = art3d.Poly3DCollection([corners], shade=True) # Failed when shade=True
# tri = art3d.Poly3DCollection([corners]) # Passed with the default setting shade=False
```

### Actual outcome

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 tri = art3d.Poly3DCollection([corners], shade=True)

File ~/anaconda3/envs/testmpl/lib/python3.12/site-packages/mpl_toolkits/mplot3d/art3d.py:905, in Poly3DCollection.__init__(self, verts, zsort, shade, lightsource, *args, **kwargs)
    875 """
    876 Parameters
    877 ----------
   (...)
    902 and _edgecolors properties.
    903 """
    904 if shade:
--> 905     normals = _generate_normals(verts)
    906     facecolors = kwargs.get('facecolors', None)
    907     if facecolors is not None:

File ~/anaconda3/envs/testmpl/lib/python3.12/site-packages/mpl_toolkits/mplot3d/art3d.py:1222, in _generate_normals(polygons)
   1220         n = len(ps)
   1221         i1, i2, i3 = 0, n//3, 2*n//3
-> 1222         v1[poly_i, :] = ps[i1, :] - ps[i2, :]
   1223         v2[poly_i, :] = ps[i2, :] - ps[i3, :]
   1224 return np.cross(v1, v2)

TypeError: tuple indices must be integers or slices, not tuple

### Expected outcome

No error.

### Additional information

When `shade=True`, the `__init__` function will first call the function `_generate_normals(polygons)`, where `polygons=verts`. In our case, `verts` is not an instance of `np.ndarray` but a list, so it enters the for loop:
```python
        for poly_i, ps in enumerate(polygons):
            n = len(ps)
            i1, i2, i3 = 0, n//3, 2*n//3
            v1[poly_i, :] = ps[i1, :] - ps[i2, :]
            v2[poly_i, :] = ps[i2, :] - ps[i3, :]
```
`polygons` is `[((0, 0, 0), (0, 5, 0), (5, 5, 0), (5, 0, 0))]`, and `ps` is a nested tuple, so we need to convert `ps` to `np.ndarray` before using the array slicing like `ps[i1, :]`. A possible fix may be setting `ps = np.asarray(ps)` before array slicing.

### Matplotlib Version

3.9.2

### Installation

None

**Comment by ksunden** [comment]
Yeah, I think your assessment is correct, the private function (and public constructor) is documented and says it takes "array-like" inputs, but then tries to do multiple indexing/subtraction on them. Since it says array like, it should be converted into an actual array before treating it as one. since it can be ragged, the outermost dimension is capable of being a list/tuple/etc, and that is why the loop in question exists.

**Comment by scottshambaugh** [comment]
I think this is a good first issue, as it is a bugfix with a simple fix and well defined scope. Tasks:
1) Fix the bug
2) Add tests which cover this case

**Comment by vicliu2001** [comment]
Hello, I would like to work on this. I will follow the contributing guide and create a PR.

**Comment by sagarv2522** [comment]
Hello Families, I'm new to open source contributing and I would like to work on this issue. Can someone assist me to breakdown the issue properly for getting clear insights

**Comment by scottshambaugh** [comment]
Hi @sagarv2522, we do not assign issues in the matplotlib project - anyone is free to try and work on any of them! The way to "claim" an issue is simply to open a pull request for it. In this case @vicliu2001 opened one already, so their fix will be prioritized.

If you'd like to help out we would welcome the contributions! Please take a look at the [contribution guide](https://matplotlib.org/devdocs/devel/contribute.html), and reach out in [the gitter chatroom](https://app.gitter.im/#/room/#matplotlib_matplotlib:gitter.im) if you have more questions or want help getting started.
