### ISSUE TITLE
[Bug]: Incorrect pcolormesh when shading='nearest' and only the mesh data C is provided.

### ISSUE THREAD

**Issue by smith2936** [matplotlib/matplotlib#29179]
### Bug summary

The coloring of meshgrid of `plt.pcolormesh(C, shading='nearest')` is inconsistent with other types of shading, e.g., 'auto', 'flat', 'gouraud'.

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt
x, y = np.mgrid[0:11, 0:11]
C = x + y
plt.figure(figsize=(20, 5))
plt.subplot(151)
plt.pcolormesh(C, shading='nearest') # Incorrect Plot
plt.title('shading=nearest, without x, y')
plt.subplot(152)
plt.pcolormesh(x, y, C, shading='nearest') # Expected Plot
plt.title('shading=nearest, with x, y')
plt.subplot(153)
plt.pcolormesh(C, shading='auto')
plt.title('shading=auto, without x, y')
plt.subplot(154)
plt.pcolormesh(C, shading='flat')
plt.title('shading=flat, without x, y')
plt.subplot(155)
plt.pcolormesh(C, shading='gouraud')
plt.title('shading=gouraud, without x, y')
plt.show()
```

### Actual outcome

![test_pcolormesh_shading](https://github.com/user-attachments/assets/e284b003-66d9-412c-a1ba-c7eb3f8248fe)

### Expected outcome

![test_pcolormesh_shading_expected](https://github.com/user-attachments/assets/757a8d00-5469-41c0-8aa1-b029ee46a128)

### Additional information

This bug happens when only the mesh data C is provided, and using `shading = 'nearest'`.

### Matplotlib Version

3.9.2

### Installation

None

**Comment by rcomer** [comment]
Thanks for the clear report @smith2936.  I have reproduced this with our `main` development branch.  I also note that if you do

```
plt.pcolor(C, shading='nearest')
```
you get an error.

If `X` and `Y` are provided the ['nearest' option gets translated to 'flat'](https://github.com/matplotlib/matplotlib/blob/b1d2ecd09bfee53cf2eddd95920d679c508be5b8/lib/matplotlib/axes/_axes.py#L5976-L6009), so I suspect the easiest fix will be to replace 'nearest' with 'flat' earlier in the [loop that checks whether X/Y was set](https://github.com/matplotlib/matplotlib/blob/b1d2ecd09bfee53cf2eddd95920d679c508be5b8/lib/matplotlib/axes/_axes.py#L5918-L5927).

I think this is a Good First Issue because the scope is limited.

**Comment by saikarna913** [comment]
@rcomer 
i guess this chnage can fix the issue
``` python
 if len(args) == 1:
            C = np.asanyarray(args[0])
            nrows, ncols = C.shape[:2]
            if shading in ['gouraud', 'nearest']:
                if shading == 'nearest':
                    X = np.arange(C.shape[1])  # Create x array based on the number of columns
                    Y = np.arange(C.shape[0])  # Create y array based on the number of rows
                else:
                     X, Y = np.meshgrid(np.arange(ncols), np.arange(nrows))

            else:
                X, Y = np.meshgrid(np.arange(ncols + 1), np.arange(nrows + 1))
                shading = 'flat'
            C = cbook.safe_masked_invalid(C, copy=True)
            return X, Y, C, shading
 ```

**Comment by gpxxlt** [comment]
Hi user @saikarna913, thank you for your contribution. We are also a team of new contributors and are more than happy to test your code. We will get back to you as soon as possible. If this solution does not work, we can also work on this and see if there is opportunity for collaboration. Thank you.

**Comment by jklymak** [comment]
This took me a while to parse what is going on, but the proposed fixes so far are not correct.  The OP made this complicated by flipping x and y; `np.mgrid` unfortunately uses the transposed matrix order from what `np.meshgrid` uses.  For problems like this, it is very helpful to make x and y different lengths so it is clear what data is being plotted.  

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(4)
y = np.arange(7)
X, Y = np.meshgrid(x, y)
C = X + Y
plt.figure(figsize=(7, 5))
plt.subplot(131)
print('shading=nearest, without x, y')

plt.pcolormesh(C, shading='nearest') # Incorrect Plot
plt.title('shading=nearest, without x, y')
plt.subplot(132)

print('shading=nearest, with x, y')
plt.pcolormesh(x, y, C, shading='nearest') # Expected Plot
plt.title('shading=nearest, with x, y')

plt.subplot(133)
print('shading=flat, with x, y')
plt.pcolormesh(C, shading='flat') # Expected Plot
plt.title('shading=flat, without x, y')
plt.show()
```

I think the correct fix is 

```diff
diff --git a/lib/matplotlib/axes/_axes.py b/lib/matplotlib/axes/_axes.py
index f6a4ebfdc7..cc4322e58e 100644
--- a/lib/matplotlib/axes/_axes.py
+++ b/lib/matplotlib/axes/_axes.py
@@ -5923,10 +5923,8 @@ class Axes(_AxesBase):
             else:
                 X, Y = np.meshgrid(np.arange(ncols + 1), np.arange(nrows + 1))
                 shading = 'flat'
-            C = cbook.safe_masked_invalid(C, copy=True)
-            return X, Y, C, shading
 
-        if len(args) == 3:
+        elif len(args) == 3:
             # Check x and y for bad data...
             C = np.asanyarray(args[2])
             # unit conversion allows e.g. datetime objects as axis values
```
