### ISSUE TITLE
[Doc]: locally testing changes

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#29181]
### Documentation Link

https://matplotlib.org/devdocs/devel/development_workflow.html

### Problem

Before opening a PR, I would expect to locally test my branch to check that the change both addresses the target issue and doesn’t break any existing tests.  Although the contributors’ guide has a section on testing, I do not think it makes it obvious that it should be used for every code change.  The Development Workflow linked above goes right from _how to git_ to opening a PR.  There is a section further down on the automated tests that will run in the PR.

### Suggested improvement

Maybe just link out to the testing page in between _how to git_ and open your PR?  

Edit: the PR section could have a link to the PR guidelines page, where requirements are set out.

**Comment by rcomer** [comment]
Oh wait the guidance here seems to actively encourage opening the PR _before_ checking the criteria are met.  Is that what we want?
https://matplotlib.org/devdocs/devel/contribute.html#start-a-pull-request

**Comment by timhoffm** [comment]
@story645 I'm slightly concerned whether project policies are a "good first issue topic". I think we aim for very specific directions here and new contributors may not have the background to recognise and judge the nuances we are aiming at.

**Comment by rcomer** [comment]
I am not sure this addition should include everything from the PR guidelines list.  Partly because we would essentially be duplicating the list, partly because "check that your change actually works" is more fundamental than flake8, documentation, type hinting, etc.  My concern is an issue get claimed by a PR that doesn’t work, and that PR doesn’t progress because the author does not know how to debug it.  Meanwhile, some other potential new contributor who might have completed the task doesn’t bother because that issue has been claimed.

**Comment by timhoffm** [comment]
https://matplotlib.org/devdocs/devel/pr_guide.html#pull-request-guidelines states

> We value contributions from people with all levels of experience. In particular, if this is your first PR not everything has to be perfect. We'll guide you through the PR process. Nevertheless, please try to follow our guidelines as well as you can to help make the PR process quick and smooth.

I think this is exactly what we're aiming at: Try to make a good PR, but don't be afraid of missing something.

IMHO https://matplotlib.org/devdocs/devel/contribute.html#start-a-pull-request

> After starting check that your contribution meets the [pull request guidelines](https://matplotlib.org/devdocs/devel/pr_guide.html#pr-author-guidelines) and [update the pull request](https://matplotlib.org/devdocs/devel/development_workflow.html#update-pull-request) as needed.

is not good wording / intention. You shouldn't dump arbitrary stuff later first and later fix it. Note that we explicitly state that [we do not assign issues](https://matplotlib.org/devdocs/devel/contribute.html#choose-an-issue). Dumping a quick non-quality PR is effectively a way of reserving. *Personal opinion*: For smaller topics (and these are the ones of being in danger of being snatched away) - I expect that any (new) contributor can make a not-perfect but reasonable PR within a day - if not they are either only claiming the topic without actually working on it, or they fundamentally lack skills.

Maybe we should revise our policy:

- There's (still) no reservation in the sense of "I plan to do this somewhen".
- One may indicate that one has started to work on a topic *right now* by a comment in the issue. In that case, others should not start to work on the same topic to prevent duplicate work.
- If the commenter does not report back within 24h either through followup discussion/clarification or through a PR, we will assume that they have stopped working on it. And then, anybody can have a go again.

IMHO [Start a pull request](https://matplotlib.org/devdocs/devel/contribute.html#start-a-pull-request) should read like

1. [unchanged] First set up a development environment, ...
2. Then <s>open a pull-request</s>*start working on the topic* by following the guidance in [development workflow]
   **Note:** this should contain the proposed "I'm working on this" comment from above
3. Then open a pull request; ...
   **Note:** link to https://matplotlib.org/devdocs/devel/development_workflow.html#open-a-pull-request and that should link further to https://matplotlib.org/devdocs/devel/pr_guide.html#pull-request-guidelines
4. [unchanged] follow up with maintainers ...

**Comment by rcomer** [comment]
An alternative change we could make is to be more willing to simply close non-quality PRs.  That way we do not need to change the way issues are claimed, but the PR does need to be a reasonable attempt at a solution.  I also suspect that the contributors opening the non-quality PRs are not following the steps in the guide (I have seen at least 2 recently where the author asked for help installing Matplotlib after opening the PR).

Completely agree that the PR does not need to be perfect.  Otherwise a lot of mine would be rejected off the bat 😄
