### ISSUE TITLE
Import hangs when importing pyplot

### ISSUE THREAD

**Issue by notmatthancock** [matplotlib/matplotlib#2919]
This is another font issue. This is similar to [this one](https://github.com/matplotlib/matplotlib/issues/2320), although the solution found there doesn't work for me. I am on OSX 10.6 using python 2.7.6. I installed the latest via git. That went fine. I can import matplotlib:

```
import matplotlib
print matplotlib.__version__
=> 1.4.x
```

Now if I do:

```
import matplotlib.pyplot
```

I get nothing. It just hangs. This is the traceback which is what leads me to believe that this a font manager issue: https://gist.github.com/chestervonwinchester/9725539

**Comment by ialexryan** [comment]
Why is this closed? Even if the solution is as simple as running `fc-list`, there should be some sort of error instead of just hanging forever.

**Comment by jenshnielsen** [comment]
Because that is not the solution. What happens is that matplotlib calls fc-list on the first import of pyplot to create the font cache. Unfortunately this can be really slow on some systems but it's not really an issue in matplotlib. No where in this issue is there any indication of anything hanging forever. It will hang for the time it takes to execute fc-list only.

**Comment by ialexryan** [comment]
Sorry, I meant forever in the colloquial sense. Most users have been trained by convention to expect that any program that produces no visual output for more than several seconds without warning has crashed - I know I have. Could we at least print a line saying something like "Running fc-list. This may take up to several minutes." ?

**Comment by RichardoC** [comment]
I'm also suffering from a slow fc-list import. A warning in the console would be appreciated. The only reason I spotted that the kernel wasn't hung was due to htop.

**Comment by jenshnielsen** [comment]
@RichardoC there already is a warning at import time in 1.5.1 see #5640 also see #5836 for users whishing to remove it again. Are you using an older version of matplotlib?

**Comment by RichardoC** [comment]
Just updated and the warning is now showing up. It's a nice feature to have.
