### ISSUE TITLE
[Bug]: `fontsize` in tables not working

### ISSUE THREAD

**Issue by acgc99** [matplotlib/matplotlib#29202]
### Bug summary

Specifying `fontsize` kwarg in `matplotlib.pyplot.table` doesn't have any effect.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = x + 1
tableData = [['a', 1], ['b', 1]]

fig, ax = plt.subplots()
ax.plot(x, y)
t = ax.table(
    cellText=tableData,
    loc='top',
    cellLoc='center',
    fontsize=30
)
plt.show()
```

### Actual outcome

![Figure_1](https://github.com/user-attachments/assets/4a60237b-4060-4438-854e-ba2b7a5b73e1)

### Expected outcome

A table with bigger font size.

### Additional information

This works:
```
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = x + 1
tableData = [['a', 1], ['b', 1]]

fig, ax = plt.subplots()
ax.plot(x, y)
t = ax.table(
    cellText=tableData,
    loc='top',
    cellLoc='center'
)
t.set_fontsize(30)  # <----------------
plt.show()
```
![Figure_1](https://github.com/user-attachments/assets/b668e57f-e676-40bc-98cb-c3e35ede6ad8)

### Operating system

Windows 11

### Matplotlib Version

3.8.2

### Matplotlib Backend

QtAgg

### Python version

3.12.0

### Installation

pip

**Comment by QuLogic** [comment]
It appears that `fontsize` is documented as a property because `Table.set_fontsize` exists. However, it does _not_ set some direct attribute, but sets the font size on all `Cell`s of the table. From `matplotlib.table.table`, the `Table` is created first (passing through the `fontsize` keyword argument), and the `Cell`s are added afterwards, meaning the `fontsize` is never given to the `Cell`s.

To get this working, the `fontsize` argument will need to be passed through [the `add_cell` calls somewhere here](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/table.py#L815-L839). This seems like a fairly straightforward Good First Issue.

**Comment by Kaustbh** [comment]
Hi @QuLogic can I make a PR?

**Comment by saikarna913** [comment]
@Kaustbh, can I create the pull request? Since I am a beginner, this can motivate me to Contribute.

**Comment by Kaustbh** [comment]
No problem you can work on it 👍, let me know if you need any help.

**Comment by saikarna913** [comment]
@Kaustbh, I’m facing issues installing Matplotlib in the development environment, both on my local desktop and in GitHub Codespaces. It’s throwing an import error, so I’m unable to test the code changes I’ve made.  

Here’s what I’ve done so far:  
1. Forked the Matplotlib repository.  
2. Created a new environment and installed dependencies using:  
   ```bash
   pip install -r requirements/dev/dev-requirements.txt
   ```  
also tried in GitHub Codespaces by activating the environment with:  
   ```bash
   conda activate mpl-dev
   ```  
4. Installed Matplotlib in editable mode with:  
   ```bash
   python -m pip install --verbose --no-build-isolation --editable ".[dev]"
   ```  
5. Also tried:  
   ```bash
   python -m pip install --no-build-isolation --config-settings=editable-verbose=true --editable .
   ```  

Despite these steps, I’m still encountering the import error. Could you help me figure out why this might be happening?

**Comment by NGWi** [comment]
> also tried in GitHub Codespaces by activating the environment
@saikarna913 Just to confirm, you activated your virtual environment when you were trying locally?

Also, please provide the error messages you're getting.

**Comment by saikarna913** [comment]
@NGWi, it is working after clearing my old versions and the above code runs, so please review my pull request and suggest the changes
