### ISSUE TITLE
[Bug]: Distribution `matplotlib==3.9.3 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

### ISSUE THREAD

**Issue by hongbo-miao** [matplotlib/matplotlib#29208]
### Bug summary

I am using [uv](https://github.com/astral-sh/uv). When upgrade from 3.9.2 to 3.9.3 in Python 3.12, I got error in [the build](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/12095612472/job/33729155287?pr=20940).

### Code for reproduction

```Python
[project]
name = "hm-test"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
    "matplotlib==3.9.3"
]
```

Then run `uv sync`.

### Actual outcome

> Distribution `matplotlib==3.9.3 @ registry+[https://pypi.org/simple`](https://pypi.org/simple%60) can't be installed because it doesn't have a source distribution or wheel for the current platform

### Expected outcome

I expect matplotlib 3.9.3 can be installed in Python 3.12.

### Additional information

matplotlib 3.9.3 can be installed successfully in Python 3.13: [build](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/12095694254/job/33729165842).

### Operating system

Ubuntu

### Matplotlib Version

3.9.3

### Python version

3.12.0

### Installation

uv

**Comment by rcomer** [comment]
Matplotlib v3.9.3 was only released within the last couple of hours, so it is possible that the PyPI files were still uploading when you ran the test.  Could you try re-spinning your tests?

**Comment by hongbo-miao** [comment]
Thanks @rcomer , makes sense. However, still same, I will try again tomorrow! 😃

**Comment by hongbo-miao** [comment]
Just tried again, confirmed the issue has gone, thanks! 😃

**Comment by adamjstewart** [comment]
I still don't see an sdist available on PyPI...
