### ISSUE TITLE
[Bug]: 3.9.3 release upload failed

### ISSUE THREAD

**Issue by mgorny** [matplotlib/matplotlib#29212]
### Bug summary

The upload for 3.9.3 release failed, apparently due to a token expiring in the middle of uploading.

### Code for reproduction

```Python
See https://github.com/matplotlib/matplotlib/actions/runs/12095099184/job/33728735029
```

### Actual outcome

```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid API Token: token is expired     
```

### Expected outcome

Successful upload with all resulting files available.

### Matplotlib Version

3.9.3

### Installation

None

**Comment by QuLogic** [comment]
I'm aware: https://github.com/pypa/gh-action-pypi-publish/issues/307; they were uploaded manually.

**Comment by mgorny** [comment]
Thank you!
