### ISSUE TITLE
[Doc]: The link at "see also" is incorrect. (Axes.violin)

### ISSUE THREAD

**Issue by cycentum** [matplotlib/matplotlib#29298]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.violin.html#matplotlib.axes.Axes.violin

### Problem

The link at "ses also" is incorrect.

It is currently violin. It should be violinplot.

**Comment by QuLogic** [comment]
Yes, that seems right; would you like to open a PR making that change?

**Comment by Brijeshthummar02** [comment]
@QuLogic on behalf of him i would like to open a pr for the same, just provide me path to the file also with right link.

**Comment by rcomer** [comment]
Looks like this has already been handled in the development docs, ready for v3.10.
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.violin.html

**Comment by cycentum** [comment]
Thank you! I should have looked at the development version.
