### ISSUE TITLE
`patches.Scatter()` and `patches.Plot()` should be added.

### ISSUE THREAD

**Issue by hyperkai** [matplotlib/matplotlib#29318]
### Problem

Only using [patches.Rectangle()](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Rectangle.html) of [plt.subplots()](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subplots_demo.html#creating-multiple-subplots-using-plt-subplots) works properly as shown below:

```python
from torchvision.datasets import CelebA

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)
    rect = Rectangle(xy=(x, y), width=w, height=h, linewidth=3, edgecolor='r', facecolor='none', clip_on=True) # Here
    axis.add_patch(p=rect)                                                                                     # Here
```

![Screenshot 2024-12-16 012242](https://github.com/user-attachments/assets/e56af00e-ca43-4902-8512-ff0b0142374d)

And only using [axes.Axes.scatter()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html) of `plt.subplots()` works properly as shown below:

```python
from torchvision.datasets import CelebA
import torchvision

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.patches import Circle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)

    for px, py in lm.split(2):                # Here
        axis.scatter(x=px, y=py, c='#1f77b4') # Here
```

![Screenshot 2024-12-16 020807](https://github.com/user-attachments/assets/4aac26da-1a63-4a3e-899e-ec9ed270168c)

And only using `axes.Axes.plot()` of `plt.subplots()` works properly as shown below:

```python
from torchvision.datasets import CelebA
import torchvision

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.patches import Circle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)

    px = []                    # Here
    py = []                    # Here
    for j, v in enumerate(lm): # Here
        if j%2 == 0:           # Here
            px.append(v)       # Here
        else:                  # Here
            py.append(v)       # Here
    axis.plot(px, py)          # Here
```

![Screenshot 2024-12-16 021239](https://github.com/user-attachments/assets/ef5af7a9-21c1-4363-919a-d961d746d26b)

But using `patches.Rectangle()` of `plt.subplots()` with `axes.Axes.scatter()` of `plt.subplots()` doesn't work properly as shown below:

```python
from torchvision.datasets import CelebA

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)
    rect = Rectangle(xy=(x, y), width=w, height=h, linewidth=3, edgecolor='r', facecolor='none', clip_on=True) # Here
    axis.add_patch(p=rect)                                                                                     # Here

    for px, py in lm.split(2):                # Here
        axis.scatter(x=px, y=py, c='#1f77b4') # Here
```

![Screenshot 2024-12-16 012506](https://github.com/user-attachments/assets/ff290aef-34ba-44fe-9592-49a13fb3b42e)

And using `patches.Rectangle()` of `plt.subplots()` with `axes.Axes.plot()` of `plt.subplots()` doesn't work properly as shown below:

```python
from torchvision.datasets import CelebA

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)
    rect = Rectangle(xy=(x, y), width=w, height=h, linewidth=3, edgecolor='r', facecolor='none', clip_on=True) # Here
    axis.add_patch(p=rect)                                                                                     # Here

    px = []                    # Here
    py = []                    # Here
    for j, v in enumerate(lm): # Here
        if j%2 == 0:           # Here
            px.append(v)       # Here
        else:                  # Here
            py.append(v)       # Here
    axis.plot(px, py)          # Here
```

![Screenshot 2024-12-16 013942](https://github.com/user-attachments/assets/f7414b6b-f1f1-45fb-9ea4-9e6c8da99e5e)

So instead, I used `patches.Rectangle()` of `plt.subplots()` with [patches.Circle()](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Circle.html) of `plt.subplots()`, then they properly work as shown below:

```python
from torchvision.datasets import CelebA

my_data = CelebA(
    root="data",
    split="all",
    target_type=["bbox", "landmarks"]
)

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.patches import Circle

fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(12, 6))
for (im, ((x, y, w, h), lm)), axis in zip(my_data, axes.ravel()):
    axis.imshow(X=im)
    rect = Rectangle(xy=(x, y), width=w, height=h, linewidth=3, edgecolor='r', facecolor='none', clip_on=True) # Here
    axis.add_patch(p=rect)                                                                                     # Here

    for px, py in lm.split(2):                # Here
        axis.add_patch(p=Circle(xy=(px, py))) # Here
```

![Screenshot 2024-12-16 014626](https://github.com/user-attachments/assets/653ec8e8-78f8-48ee-92ae-899cdb7ce01f)

### Proposed solution

So, it seems like [matplotlib.patches](https://matplotlib.org/stable/api/patches_api.html) works with `matplotlib.patches` so `patches.Scatter()` and `patches.Plot()` should be added.

**Comment by jklymak** [comment]
They are all working the same, just scatter is calling autolim, and add_patch is not.

**Comment by timhoffm** [comment]
What is happening:
- add_patch() is a lower-level function and updates the data limits (`Axes.dataLim`) to include the Patch, but doesn't touch the view limits (`Axes.viewLim`).
- `scatter()` is a high-level function that additionally updates the view limits based on the data limits (essentially through a lazy `autoscale_view()`), which then picks up the rectangle limits as well.



If you want to have limits exactly on the image, no matter what you plot afterwards you should call `ax.autoscale(False)` after `ax.imshow()`.

**Comment by timhoffm** [comment]
I'm closing as the solution for the present case is to deactivate autoscaling.

Independent of this, there are some ideas how to change/improve autoscaling. These are independently tracked, e.g. in

- #19290
- #19685
- #29219 / #29228
- #15595
