### ISSUE TITLE
[Doc]: Link rendered incorrectly

### ISSUE THREAD

**Issue by martinosorb** [matplotlib/matplotlib#29312]
### Documentation Link

https://matplotlib.org/devdocs/users/explain/colors/colormaps.html

### Problem

In the "Diverging" section, it shows as follows:
> These are taken from F. Crameri's [scientific colour maps]_ version 8.0.1.

The link doesn't render correctly. This is actually my fault as I wrote that bit, but I couldn't manage to build the docs, and both the CI and the maintainers did not spot that. Not sure how to correct it either. Sorry.

**Comment by rcomer** [comment]
Thanks for following up @martinosorb.  I must admit I find the sphinx linking syntax confusing and it usually takes me a few attempts to make a link work.  I have opened #29314 to fix.

**Comment by martinosorb** [comment]
Awesome, thanks.
