### ISSUE TITLE
[ENH]: Allow joining ContourSets

### ISSUE THREAD

**Issue by stefanv** [matplotlib/matplotlib#29339]
### Problem

In the scikit-image gallery, we sometimes draw several contours, and then want to label them.
These contours are all based on processed iterations of a dataset, so cannot be drawn with a single `contour` call.

We have a [workarounds for getting those contours labeled](https://github.com/scikit-image/scikit-image/pull/7638#pullrequestreview-2509633501), after API changes in 3.10, but it would be really nice if we could simply join the contoursets, and then use `plt.clabel` to do the job.

(By the way, contoursets confusingly have members such as `set_label` and `extend`, presumably inherited, which don't do what you'd expect; would perhaps be good to hide them?)

### Proposed solution

Allow contoursets to be joined as regular sets.

**Comment by jklymak** [comment]
I'm not really following your use case = the workaround linked is to legend entries, whereas here you are talking about `label`.   Do you want one clabel call on multiple contour sets?  What is the advantage of that over just calling clabel individually on each contour set?

**Comment by stefanv** [comment]
> I'm not really following your use case = the workaround linked is to legend entries, whereas here you are talking about `label`. Do you want one clabel call on multiple contour sets? What is the advantage of that over just calling clabel individually on each contour set?

Sorry, that's my confusion: we want a legend indeed.

Your suggested approach works perfectly for labeling on the contours.

While I still think it could be useful to join ContourSets, I don't think it will help with our legend issue, so will close this issue for now. Thanks!
