### ISSUE TITLE
KeyError: 'buttons' when plotting with matplotlib / ipympl backend in Jupyter Notebook within VSCode presumably due to typo

### ISSUE THREAD

**Issue by gnbl** [matplotlib/matplotlib#29337]
Using a current install of Python and notebook, matplotlib, ipympl etc. on Windows 11 within VSCode, 

```
%matplotlib ipympl
#%matplotlib widget
import matplotlib.pyplot as plt
```

and

```
fig, ax = plt.subplots()
...
ax.plot(...)
```

raise `KeyError: 'buttons'` in `c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\backends\backend_webagg_core.py:295`

respectively

https://github.com/matplotlib/matplotlib/blob/f8900ead0d9381a7652568768b065324f929734e/lib/matplotlib/backends/backend_webagg_core.py#L295

Changing the key to `button` resolves the error (for my use case).

**Comment by timhoffm** [comment]
I haven’t looked closer, but the code has recently been touched in https://github.com/matplotlib/matplotlib/pull/28453.

**Comment by rcomer** [comment]
I believe this has been addressed by https://github.com/matplotlib/ipympl/pull/568

**Comment by ianthomas23** [comment]
Yes, this has been fixed on the `ipympl` side as is in today's 0.9.5 release on PyPI. The `conda-forge` package isn't available yet but it will be shortly.

**Comment by ianthomas23** [comment]
But before we close the issue, can @gnbl confirm what versions of packages are installed, particularly `ipympl` and `matplotlib`.

**Comment by gnbl** [comment]
Afk, eta 14 hrs 😁

**Comment by gnbl** [comment]
matplotlib 3.10.0
ipympl 0.9.4

  ...
  Successfully installed ipympl-0.9.5

Fixed in the update! Thanks.

**Comment by gcohn** [comment]
This was driving me nuts! `pip install -U ipympl>0.9.5` for the win!
