### ISSUE TITLE
[ENH]: Indicating change of scale for symlog

### ISSUE THREAD

**Issue by SteffenBeirle** [matplotlib/matplotlib#29335]
### Problem

I appreciate that matplotlib provides various scales, including symlog. 
However, I see the problem that it is not quite clear in the axis labels what happens.

### Proposed solution

I propose to (at least optionally) insert automatically a break (like // ) on the axis at the transitions between lin and log scales.

**Comment by timhoffm** [comment]
Fundamentally, I believe this is a good idea. It's a bit difficult to implement though. Conceptually, we only have the locator, which determines tick positions. We don't have any infrastructure/API to handle the additional markers. Any automatism would need architectural changes.

A simple workaround would be a dedicated `mark_symlog_linear_range()` method that the user must call explicitly. It would add appropriate markers statically, but wouldn't update with a change of scale.

**Comment by SteffenBeirle** [comment]
Dear Tim,
many thanks for the prompt reply.
Having such a method would indeed be great!
Kind regards,
Steffen

**Comment by timhoffm** [comment]
One quick solution would be something like this:


```python
from matplotlib.scale import SymmetricalLogScale


def mark_symlog_linear_range(axis):
    if not isinstance(axis._scale, SymmetricalLogScale):
        raise ValueError("mark_symlog_linear_range() can only be applied to Axis with SymmetricalLogScale")

    thresh = axis._scale.linthresh
    if axis.axis_name == 'x':
        axis.axes.axvspan(-thresh, thresh, -0.02, 0.0, clip_on=False, color='lightgray')
    elif axis.axis_name == 'y':
        axis.axes.axhspan(-thresh, thresh, -0.02, 0.0, clip_on=False, color='lightgray')
    else:
        raise ValueError("mark_symlog_linear_range() only works on x-axis and y-axis")
```

Which then could be used as

```python
import matplotlib.pyplot as plt
import numpy as np

dt = 0.01
x = np.arange(-50.0, 50.0, dt)
y = np.arange(0, 100.0, dt)

fig, ax = plt.subplots()

ax.plot(x, y)
ax.set_xscale('symlog', linthresh=10)
ax.grid()
ax.set_xlim(-20, 20)
mark_symlog_linear_range(ax.xaxis)
```

![image](https://github.com/user-attachments/assets/305c5478-8dca-4864-b405-f5298f6707ac)

**Comment by jklymak** [comment]
Usually people want the linear region to be imperceptible.  If folks want the split in scales to be obvious there are lots of ways to do that which will depend on the reason for making it clear.  Perhaps @timhoffm example above could be added to the examples page, but I don't think we could or should provide a universal method for indicating this.  

Symlog should really be discouraged compared to asinh.

**Comment by timhoffm** [comment]
The linear region is a necessary deviation from the log scaling to be able to map data in a range (-x0, x0) onto a finite region. I agree with @jklymak that the linear range should typically a tiny fraction of the view range. It should be chosen to be slightly smaller than the absolute value of all “interesting data”.
We should better explain why it is necessary and how to use it, rather than adding tooling to visualize it. This explanation should likely go into https://matplotlib.org/devdocs/gallery/scales/symlog_demo.html and be cross-linked from https://matplotlib.org/devdocs/api/scale_api.html#matplotlib.scale.SymmetricalLogScale.

**Comment by SteffenBeirle** [comment]
Thanks for your efforts and replies.
I understand your concerns.
Thanks as well for the recommendation of asinh.
