### ISSUE TITLE
[Doc]: stable docs link to dev

### ISSUE THREAD

**Issue by shallow-beach** [matplotlib/matplotlib#29359]
### Documentation Link

https://matplotlib.org/stable/index.html

### Problem

On MacOS Firefox, the link to the documentation (which is for the stable version) takes me to 3.10 (dev), so I always get the "This is documentation for an unstable development version" message. 

### Suggested improvement

I figure this has something to do with the latest release, 3.9.4 (which has no link), while [3.9.3](https://matplotlib.org/3.9.3/index.html) is working.

**Comment by tacaswell** [comment]
Thank you for reporting this. 3.10.0 is the currently stalble version, but we did not update the metadata in the version switcher,  I'm working on a PR.
