### ISSUE TITLE
Move/copy documentation from pcolor to pcolormesh

### ISSUE THREAD

**Issue by dawehner** [matplotlib/matplotlib#2957]
Given that for many usecases pcolor is just way to slow
people use pcolormesh or at some point pcolorfast.

This means that pcolormesh/pcolorfast should have the documentation
about the expected sizes of X, Y (One bigger in size than the C data aka. the edges instead of the midpoints)

Do you think it is okay to just copy over the documentation instead of refering to it?
Silently changing the data before plotting is a problem

**Comment by petehuang** [comment]
I would tag this with `new-contributor-friendly`

**Comment by anntzer** [comment]
the doc of pcolorfast has been updated (https://github.com/matplotlib/matplotlib/pull/11363 and other PRs).
