### ISSUE TITLE
Feature Request: Data Cursor Mode

### ISSUE THREAD

**Issue by jeremy-patterson1** [matplotlib/matplotlib#2965]
It would really help my plotting to have a DataCursorMode button on the toolbar.  

A coded example is located here:
http://stackoverflow.com/questions/4652439/is-there-a-matplotlib-equivalent-of-matlabs-datacursormode

It would be nice if the user could drag the box to different corners around the point of interest and use the keyboard to move the datacursor onto the next data dot.

**Comment by K2LEEKorea** [comment]
Based on mpl example cursor_demo.html and custom_boxstyle01.html, we can make similar features like this without javascript
![mpl_cursor_cross_line_v27_SnaptoCursor_GD_all_around](https://user-images.githubusercontent.com/97375698/150379858-4a451fff-a95c-4b2b-a906-6205ac23a333.png)
