### ISSUE TITLE
Clabel and Setting Axis Limits

### ISSUE THREAD

**Issue by pjkottke** [matplotlib/matplotlib#2973]
When clabel is called before the axis limits are set, the labels do not appear or are dysfunctional. It seems like clabels should be redrawn after axis limits are set to prevent this (I don't know if this is possible). A MWE is:

```
import numpy as np
import matplotlib.pyplot as plt 

X,Y = np.meshgrid(np.linspace(0,10,100),np.linspace(0,10,100))
Z = X+10*Y

fig, (ax1,ax2) = plt.subplots(2)
CS1 = ax1.contour(X, Y, Z)
CS2 = ax2.contour(X, Y, Z)
ax1.clabel(CS1)

ax2.set_xlim((0,1e5))
ax2.set_ylim((0,1e5))
ax2.clabel(CS2)
ax2.autoscale()
plt.show()
```

**Comment by petehuang** [comment]
Confirming that this bug can be reproduced in 1.5.3, though I'm thinking this merits a simple doc change at http://matplotlib.org/api/axes_api.html?highlight=clabel#matplotlib.axes.Axes.clabel instead of a deeper fix

**Comment by dopplershift** [comment]
@ktyle I think this is the issue you've been seeing...
