### ISSUE TITLE
Gtk3Agg backend (Ubuntu 14.04)

### ISSUE THREAD

**Issue by tobias47n9e** [matplotlib/matplotlib#2976]
When running the example from the Matplotlib website:

http://matplotlib.org/examples/user_interfaces/embedding_in_gtk3.html

on Ubuntu 14.04 (64 bit), I get the following error:

```
/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py:12: UserWarning: The Gtk3Agg backend is not known to work on Python 3.x.
  warnings.warn("The Gtk3Agg backend is not known to work on Python 3.x.")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 52, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 52, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 52, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 52, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
```

**Comment by zenith-matic** [comment]
So I guys I managed to get the plots working in Python 3.x by using:

from cairocffi import *

but is there a better way of doing this without importing the entire namespace?

**Comment by jenshnielsen** [comment]
Which version of Matplotlib is this. All recent versions (al least 1.4.x) should support cairocffi out of the box without the need to do any special imports.

**Comment by zenith-matic** [comment]
version 1.4.3

**Comment by jenshnielsen** [comment]
Can you explain in some more detail what you are trying to do and any error messages you get?

As stated above plotting using the GTK3Agg backend should work without any need for work arounds 
like the one you mention.

**Comment by zenith-matic** [comment]
Downloaded matplotlib and numpy via pip. Launched the script and triggered "Not Implemented backend" error, and also the warning message "Gt3Agg is known to not work in Python 3.x". Applied timowcb's fix: sudo pip3 install cairocffi and importing it in the code got my problem fixed.

After reading what you mentioned about the master branch being updated to fix this issue, I'm thinking it perhaps has to do with pip installing an older version from the package index, instead of the updated branch? Have no idea, anways got my problem solved so all is well I guess.

**Comment by snowman907** [comment]
I am using Matplotlib 1.5 and the problem still exist. Is Zenith-matic's approach using- "from cairocffi import * " the only approach, I thought Python 3.0 is stable platform and worth the upgrade?! 

   >>> import matplotlib
   >>> matplotlib.__version__
  '1.5.0'
  >>> import matplotlib.pyplot as plt;import numpy as np;x=np.arange(1,10,1);plt.plot(x); plt.show()

  Warning (from warnings module):
    File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 18
      "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
   UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try   installing   cairocffi.
   [<matplotlib.lines.Line2D object at 0x7f343815d898>]
  Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
>>>

**Comment by jenshnielsen** [comment]
@snowman907 There exists 3 different Cairo wrappers for python. The 2 official ones py2cairo (python 2 only) and py3cairo (python 3) only. Unfortunately py3cairo does not implement `Surface.create_for_data` which we need for the GTK3Agg backend. However a third exists which is cairocffi which does support 
 `Surface.create_for_data`  normally Matplotlib should prefer cairocffi over py3cairo but it seems that does not work for you and Zenith-matic without first importing cairocffi. 

For me the following works with cairocffi installed and fails when I uninstall it.
```python
import matplotlib
matplotlib.use('Gtk3Agg')
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()
```

Could you try running the following with python3.5 and paste the output?

```python
try:
    import cairocffi as cairo
except ImportError:
    try:
        import cairo
    except ImportError:
        raise ImportError("Cairo backend requires that cairocffi or pycairo is installed.")
    else:
        HAS_CAIRO_CFFI = False
else:
    HAS_CAIRO_CFFI = True
print(HAS_CAIRO_CFFI)
```

**Comment by snowman907** [comment]
Earlier I tried:
$ sudo pip3 install cairocffi
 but got some error:
....
File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1077, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-gji6rp5t/cairocffi
Storing debug log for failure in /home/ejsaiet/.pip/pip.log

none the less I tried also your first suggestion:

import matplotlib
matplotlib.use('Gtk3Agg')
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()

**Comment by jenshnielsen** [comment]
My first suggestion was NOT a suggestion it was an example of a pice of code that works with `Cairocffi` and not with `py3cairo` Given that you can't install cairocffi it is completely expected that the example doesn't work. 

Which system are you using? On Ubuntu you should be able to install cairocffi with: 
```
sudo apt-get install python3-cairocffi
```

**Comment by snowman907** [comment]
I did not understand from your example
import matplotlib
matplotlib.use('Gtk3Agg')
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()

that is uses Cairocffi.

sudo apt-get install python3-cairocffi

Installed well and the above example worked well.

The first example plotted well. The second example got TRUE.

I am a bit surprise this problem is not more common/ better document on the web.

Thanks for the fast response.



On Thu, Nov 12, 2015 at 10:42 PM, Jens Hedegaard Nielsen <
notifications@github.com> wrote:

> My first suggestion was NOT a suggestion it was an example of a pice of
> code that works with Cairocffi and not with py3cairo Given that you can't
> install cairocffi it is completely expected that the example doesn't work.
>
> Which system are you using? On Ubuntu you should be able to install
> cairocffi with:
>
> sudo apt-get install python3-cairocffi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/2976#issuecomment-156355417>
> .
>



-- 
Eyal Saiet

Project manager
Remote sensing and in-situ measurements

Geophysical Institute
University of Alaska Fairbanks
Fairbanks, AK 99775
(907) 750 6555 (cell)

ejsaiet@alaska.edu

**Comment by jenshnielsen** [comment]
The example 
```
import matplotlib
matplotlib.use('Gtk3Agg')
import matplotlib.pyplot as plt
plt.plot(range(100))
plt.show()
```
uses cairocffi if that is installed. If not it will use py2cairo on python2 and py3cairo on python3. Unfortunalty py3cairo does not currently work for the gtk3agg backend (it does work for the gtk3cairo backend) There might be a new release of py3cairo sometime in the future fixing this but my hopes are not high. We reported the issue to the py3cairo developers several years ago.

**Comment by danijar** [comment]
Thanks, hope that will get a fix.
