### ISSUE TITLE
Make agg patches upstream

### ISSUE THREAD

**Issue by felixonmars** [matplotlib/matplotlib#2988]
The original agg website is gone, and there's an agg fork that is still maintained. It would be great if matplotlib could get any needed changes upstream, and libagg would be linked dynamically after this were done.

The fork is hosted on sf: http://sourceforge.net/p/agg/svn/commit_browser

**Comment by dmacks** [comment]
Debian is now shipping 2.6, which is forked off SF-upstream 2.4 and is BSD. As long as matplotlib is shipping its own patched version, it would be great if it clearly documented what those patches were, or the exact source-URL/svn-tag from which extern/agg24-svn was cloned (again, so we can see what specifically matplotlib has changed).

**Comment by oscargus** [comment]
Is this the "official unofficial" branch now: https://github.com/ghaerr/agg-2.6 ?

https://repology.org/project/agg/information mentions a 2.8.14 version, but not clear where that comes from... Seems like there are quite a few branches.

**Comment by dmacks** [comment]
Debian's is cloned from svn r134; ghaerr/agg-2.6 is r132. The 2.8ish that repology lists is from Mandriva, which is using https://github.com/cppfw/agg that is cloned from r134.

**Comment by tacaswell** [comment]
@QuLogic Took a pass at this iirc. 

It should be possible to use enough git pick-axe tools to get only the commits that touch those files.
