### ISSUE TITLE
freetype cannot be found by build

### ISSUE THREAD

**Issue by kravietz** [matplotlib/matplotlib#3029]
I've tried to install `matplotlib` using `pip` on Linux and it couldn't find `freetype` during the build process, even though it's installed with dev packages.

```
freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                    could not be found.  You may need to install the
                    development package.]
```

But:

```
$ ls -l /usr/include/freetype2/ft2build.h 
-rw-r--r-- 1 root root 2383 Mar 13 17:29 /usr/include/freetype2/ft2build.h
```

And:

```
$ freetype-config --cflags
-I/usr/include/freetype2
```

**Comment by gawbul** [comment]
Same here - `pkg-config` wasn't installed!

**Comment by Altoidnerd** [comment]
Same here... principle error message is

    * The following required packages can not be built:
    
                            * freetype
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FyyI8J/matplotlib


I tried 

    apt-get install pkg-config 

but the command return 0 installed/updated and nevertheless didn't solve my problem.
more discussion: 
http://www.reddit.com/r/learnpython/comments/2y89j0/pip_install_fail_command_python_setuppy_egg_info/

**Comment by llazzaro** [comment]
Same here with OS X 10.10.3

fixed with 

```
brew install pkg-config
```

**Comment by tacaswell** [comment]
@llazzaro  This is documented in https://github.com/matplotlib/matplotlib/blob/master/README.osx but says to use `brew install pkgconfig` instead of `brew install pkg-config`.  Do both work or did brew re-name things under us?

attn @jenshnielsen

**Comment by jenshnielsen** [comment]
Both should work. But pkg-config is the correct name and pgkconfig is an alias see https://github.com/Homebrew/homebrew/blob/master/Library/Aliases/pkgconfig

**Comment by cchriste** [comment]
```
sudo apt-get install pkg-config 
```
worked for me!

**Comment by khazamov** [comment]
@benesch  thanks for the post - it worked. How did you find out what was the reason?

**Comment by benesch** [comment]
@khazamov it's been a year, but IIRC I went source spelunking and noticed the hardcoded path to the freetype header was incorrect for OS X. Luckily pkg-config is capable of detecting freetype, and matplotlib prefers pkg-config's advice over the hardcoded path.

**Comment by kevinsoucy** [comment]
sudo apt-get install libfreetype6-dev
sudo pip install matplotlib --upgrade

DONE

**Comment by softwaremakerraj** [comment]
You solved my life kevinsoucy! Much thanks!

**Comment by Honghe** [comment]
Ubuntu 14.04 64bit 
Fixed with `sudo apt-get install pkg-config`

**Comment by prawn-cake** [comment]
Faced with the same problem on debian jessie.
Same solution: `sudo apt-get install pkg-config`

**Comment by mvnnn** [comment]
LinuxMint 17 64bit
i try: sudo apt-get install pkg-config
but still i get error while run : pip install matplotlib
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kyfoezji/matplotlib
```

**Comment by jenshnielsen** [comment]
Could you try doing `pip install matplotlib --verbose` It is by no means clear from that error message that your issue in any way relates to package config.

**Comment by mvnnn** [comment]
thanks, it's working now.

**Comment by jianqi** [comment]
same here.. faced the error will installing v1.5.1 on ubuntu 14.04

fixed with installing pkg-config

**Comment by ameyp** [comment]
Is it possible to have the error say "pkg-config: not found" instead of complaining about freetype?

**Comment by julianofischer** [comment]
Thank you.
> sudo apt-get install pkg-config

Worked for me!

**Comment by scott-vsi** [comment]
+1 Please suggest installing pkg-config.

**Comment by tacaswell** [comment]
@scott-vsi See http://matplotlib.org/users/installing.html#optional-dependencies

**Comment by ameyp** [comment]
@tacaswell Does the installation work on most systems without pkg-config installed?

**Comment by tacaswell** [comment]
Not sure.  We have talked about moving `pkg-config` to the required section.

**Comment by scott-vsi** [comment]
Thanks for the link. If the installation script can't suggest installing pkg-config (if it is not installed) when failing to find freetype then perhaps the documentation could suggest this. 

E.g., in the [Building on Linux](http://matplotlib.org/users/installing.html#building-on-linux) you could add a note like 

If the freetype developer package is installed by the system package manager but not found when installing matplotlib, try installing pkg-config, which is a tool used to find required non-python libraries.

**Comment by tacaswell** [comment]
@scott-vsi Can you put in a Pull request adding that text where you would expect to have found it?

**Comment by ameyp** [comment]
@tacaswell I would really prefer having the installation script check for pkg-config instead. I can try put in a PR for that if you'd like. I believe most users would try to install matplotlib via either pip or the system package manager, encounter the error, google for the error and then end up here. Having the installation check for pkg-config seems like a cleaner solution to me.

**Comment by scott-vsi** [comment]
I agree that is better. I did a pull request for the interim if you want.

**Comment by saukymo** [comment]
sudo apt-get install pkg-config 
works for me

**Comment by calebebrim** [comment]
brew install pkgconfig
I'm getting: 
Warning: pkg-config-0.28 already installed

But i still can't install matplotlib

**Comment by jenshnielsen** [comment]
@calebebrim Did you actually install freetype? 

```
brew install freetype
```

Freetype is a dependency of matplotlib and needs to be installed for matplotlib to build. pkg-config only helps locate it.

**Comment by janssen** [comment]
I'm having this problem on Windows 10, building matplotlib 1.5.1 for Python 2.7.11.  I'm using the conda package manager.  "conda build matplotlib" errors out with 

```
BUILDING MATPLOTLIB
            matplotlib: yes [1.5.1]
                python: yes [2.7.11 |Continuum Analytics, Inc.| (default,
                        Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]]
              platform: yes [win32]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.11.0]
              dateutil: yes [using dateutil version 2.5.3]
                  pytz: yes [using pytz version 2016.4]
                cycler: yes [using cycler version 0.10.0]
               tornado: yes [tornado was not found. It is required for the
                        WebAgg backend. pip/easy_install may attempt to
                        install it after matplotlib.]
             pyparsing: yes [using pyparsing version 2.1.4]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [The C/C++ header for freetype (ft2build.h)
                        could not be found.  You may need to install the
                        development package.]
                   png: yes [Using unknown version found on system.]
                 qhull: yes [pkg-config information for 'qhull' could not be
                        found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite. Please install it with pip or
                        your preferred tool to run the test suite / mock is
                        required to run the matplotlib test suite. Please
                        install it with pip or your preferred tool to run
                        the test suite]
        toolkits_tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite. Please install it with pip or
                        your preferred tool to run the test suite / mock is
                        required to run the matplotlib test suite. Please
                        install it with pip or your preferred tool to run
                        the test suite]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: no  [PyQt5 not found]
                qt4agg: no  [PySide not found; PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                        found.  You may need to install the development
                        package.]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairocffi or pycairo not found]
             windowing: yes [installing, installing]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype
```

freetype is installed.  ft2build.h is present.  There is no pkg-config for Windows.  This seems like a real matplotlib config bug that is being covered over by punting to pkg-config.  Wish it could be fixed.

**Comment by tacaswell** [comment]
@janssen I suggest you send this issue to the user mailing list (matplotlib-users@python.org which will require you to register to post un-moderated) or have a look at our appveyor configuration files (which build mpl in a conda env on windows).

**Comment by kubark42** [comment]
Same problem here, `sudo apt-get install pkg-config` resolved it. It would be *very* helpful if the build script would either suggest checking `pkg-config` directly, or would point to this GitHub issue. It would certainly have saved me at least 15 minutes of trial and error before landing here.

**Comment by Turing-Chu** [comment]
@razius  <br>
 I run your command by root user but get an error of 'Operation not permitted' on Mac.
And the command 'find / -name ft2build.h' get the flowing result:
```
/Users/XXXX/Downloads/freetype-2.6/devel/ft2build.h
/Users/XXXX/Downloads/freetype-2.6/include/ft2build.h
/Users/XXXX/Downloads/matplotlib-1.5.1/src/ft2build.h
/usr/local/apps/freetype-2.6/include/freetype2/ft2build.h
/usr/local/include/freetype2/ft2build.h
```

**Comment by cfblaeb** [comment]
Have this issue on ubuntu 16.04, python 3.5.2 (virtualenv), matplotlib 1.5.1 (installed via pip).
ft2build.h is in /usr/include/freetype2/ft2build.h
and sym linking it to /usr/include/ fixes it.
`$ ln -s /usr/include/freetype2/ft2build.h /usr/include/`

**Comment by iacchus** [comment]
```
OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype
```
## Then

> sudo apt-get install libfreetype6-dev
> sudo pip install matplotlib --upgrade
> 
> DONE

Which, by the way, is exactly the only error that the output is clearly saying.

**Comment by OnlyBelter** [comment]
If you are using docker, and install matplotlib in `python:3.5-alpine`, this may hlep: 
```
RUN set -e; \
        apk add --no-cache --virtual .build-deps \
                gcc \
                libc-dev \
                linux-headers \
                mariadb-dev \
                python3-dev \
                postgresql-dev \
                freetype-dev \
                libpng-dev \
                libxml2-dev \
                libxslt-dev \
                zlib-dev \
        ;

```

**Comment by z-pc** [comment]
If you're installing matplotlib in windows.
Then try:
1. Modify setupext.py:
1.1 Follow def get_base_dirs():
1.2. "Try" replace win_bases = ['win32_static', ] -> win_bases = ['C:\Program Files\Anaconda2\Library', ]
2. Install C++ compiler for Python at link: https://www.microsoft.com/en-us/download/details.aspx?id=44266
If error about library, you can go to C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
"no replace" to C:\Users\Yourname\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include

**Comment by stardigits** [comment]
In termux solve by:
```
pkg install freetype freetype-dev
export CPATH=$PREFIX/include:$PREFIX/include/freetype2:$PREFIX/include/freetype2/freetype
pip3 install matplotlib
```

**Comment by marxenegls** [comment]
Downloading https://files.pythonhosted.org/packages/26/04/8b381d5b166508cc258632b225adbafec49bbe69aa9a4fa1f1b461428313/matplotlib-3.0.3.tar.gz (36.6MB)
     |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 36.6MB 915kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sp8h0mz6/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sp8h0mz6/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-sp8h0mz6/matplotlib/
    Complete output (47 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC
                            6.3.0 20170516]]
                  platform: yes [linux]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.17.2]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: no  [Microsoft Windows only]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Try installing freetype with `apt-get install
                            * libfreetype6-dev` and pkg-config with `apt-get
                            * install pkg-config`
                            * Try installing png with `apt-get install
                            * libpng12-dev` and pkg-config with `apt-get install
                            * pkg-config`
    ----------------------------------------
ERROR: Command erred out with exit status 1: python setup.py egg_info Check the logs for full command output.

on raspbian stretch

**Comment by tacaswell** [comment]
@marxenegls Can you open a topic at https://discourse.matplotlib.org/c/community/install for installing Matplotlib on rasbian?

**Comment by liuqinfei** [comment]
I also encountered this problem in openEuler release 20.03 (LTS-SP1). 
Package freetype-2.10.2-2.oe1.aarch64 is already installed.
After searching, I found that the problem can be solved by performing the following operations:
dnf install freetype-devel.aarch64 -y --nogpgcheck
