### ISSUE TITLE
Change canvas.print_figure default resolution

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#305]
[Original report at SourceForge, opened Fri Feb  5 22:59:50 2010](https://sourceforge.net/tracker/?func=detail&aid=2946933&group_id=80706&atid=560723)

Change canvas.print_figure default resolution from 100 DPI to the resolution of the figure being printed.

**Comment by three-comrades** [comment]
Should this issue be closed, or do you still want to change the defaults (`savefig.dpi=100` -> `savefig.dpi='figure'` and `figure.dpi=80` -> `figure.dpi=100`)?

**Comment by tacaswell** [comment]
This should be folded in with the 2.0 style changes.

**Comment by Tillsten** [comment]
While on it, i really dislike the use of savefig.dpi in ipython-inline, it should just use the figure.dpi.

**Comment by Tillsten** [comment]
It should also stop using subplot adjust.

**Comment by tacaswell** [comment]
@Tillsten You need to take that up with the IPython folks, mpl does not control that backend.

**Comment by Tillsten** [comment]
@tacaswell I really think your voice is a lot stronger than the one of a single user.
