### ISSUE TITLE
Different paths for get_configdir and matplotlib_fname()

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [matplotlib/matplotlib#3062]
I work in a Linux system that uses a rather unconventional `HOME` directory. However, the `HOME` environment is always set up properly.

```
> echo $HOME
> /opt/my_home_directory/
```

I have set up the init files for `matplotlib` properly under:
`$HOME/matplotlib/matplotlibrc`
and also, just in case under:
`$HOME/.matplotlib/matplotlibrc`

However, when I ask matplotlib, it looks confused:

```
> matplotlib.get_configdir()
'/opt/my_home_directory/.matplotlib`
>matplotlib.matplotlib_fname()
'/some/long/path/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
```

The second one is wrong. I want to use `matplotlibrc` under my `$HOME` directory. Why does `matplotlib` return two different paths, and how can I make it use the one I want?

**Comment by anntzer** [comment]
I think this has almost certainly been fixed by https://github.com/matplotlib/matplotlib/pull/5268.  Feel free to request a reopen if not.
