### ISSUE TITLE
BUG signed/unsigned sloppiness in _image.cpp

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3064]
Found in #3009 by @solvent:

> I think the problems begin at size_t NUMBYTES(numrows * numcols * BPP); (_image.cpp:381) since size_t is unsigned.

**Comment by tacaswell** [comment]
@mdboom Did this issues survive the massive c++ refactor?

**Comment by mdboom** [comment]
It seems to have.  The test is on master, as is the two-line fix.
