### ISSUE TITLE
vistrails ImportError: No module named pylab.plot

### ISSUE THREAD

**Issue by aschilas** [matplotlib/matplotlib#3069]
Dear matplot-users,

i have a problem and cannot find a solution. I don't have a lot of experience with python in general and matplotlib.

I want to use a program called vistrails (http://www.vistrails.org) with ALPS (alps.comp-phys.org)
but i think that the problem stems from python.

I installed python from source in my own directory since i don't have superuser access at my pc and build all the neccessary packages from source including scipy numpy and matplotlib.

When trying to import the ALPS module to vistrails i always get the error:

ImportError: No module named pylab.plot

I already tried everything in the troubleshooting and matlibplot seems to work properly when testing.

Here the needed information:

OS: Linux l39 3.2.0-60-generic-pae #91-Ubuntu SMP Wed Feb 19 04:14:56 UTC 2014 i686 i686 i386 GNU/Linux

I am currently using matlibplot 1.1.0 and also tried the newest version 1.3.1 i downloaded the source from http://matplotlib.org and compiled it myself.

I made no changes to setup.py or setupext.py

my compiler is gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

python setup.py build gives:
# basedirlist is: ['/usr/local', '/usr']

BUILDING MATPLOTLIB
            matplotlib: 1.1.0
                python: 2.7.6 (default, May 15 2014, 12:12:10)  [GCC 4.6.3]
              platform: linux2

REQUIRED DEPENDENCIES
                 numpy: 1.8.1
             freetype2: 14.0.8

OPTIONAL BACKEND DEPENDENCIES
                libpng: 1.2.46
               Tkinter: no
                        \* TKAgg requires Tkinter
                  Gtk+: no
                        \* Building for Gtk+ requires pygtk; you must be able
                        \* to "import gtk" in your build/install environment
       Mac OS X native: no
                    Qt: no
                   Qt4: Qt: 4.8.1, PyQt4: 4.10.4
                 Cairo: no

OPTIONAL DATE/TIMEZONE DEPENDENCIES
              datetime: present, version unknown
              dateutil: 2.2
                  pytz: 2011c

OPTIONAL USETEX DEPENDENCIES
                dvipng: 1.14
           ghostscript: 9.05
                 latex: 3.1415926
               pdftops: 0.18.4
# [Edit setup.cfg to suppress the above messages]

pymods ['pylab']
packages ['matplotlib', 'matplotlib.backends', 'matplotlib.backends.qt4_editor', 'matplotlib.projections', 'matplotlib.testing', 'matplotlib.testing.jpl_units', 'matplotlib.tests', 'mpl_toolkits', 'mpl_toolkits.mplot3d', 'mpl_toolkits.axes_grid', 'mpl_toolkits.axes_grid1', 'mpl_toolkits.axisartist', 'matplotlib.sphinxext', 'matplotlib.tri', 'matplotlib.delaunay']
running build
running build_py
copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.linux-i686-2.7/matplotlib/mpl-data
copying lib/matplotlib/mpl-data/matplotlib.conf -> build/lib.linux-i686-2.7/matplotlib/mpl-data
running build_ext
building 'matplotlib.ft2font' extension
...

**Comment by vivek98799** [comment]
## # ### # ImportError: No module named pylab#
