### ISSUE TITLE
3d pie chart

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#310]
[Original report at SourceForge, opened Tue Nov 10 09:40:37 2009](https://sourceforge.net/tracker/?func=detail&aid=2895225&group_id=80706&atid=560723)

Feature request: Have a pie chart with a 3d look and feel. The option to add a shadow is nice to the normal chart is nice but it does not get close to what pie charts produced by spreadsheet software such as ms excel look like.

**Comment by petehuang** [comment]
This hasn't been updated in a while. Has the priority or progress on this changed at all? What ended up happening during SciPy 2013? And is it still worth the time beyond simply "nice to have"?

**Comment by nicoguaro** [comment]
I don't think that this should be included by default. 3D pie charts are confusing. Check: https://kosara.net/papers/2016/Kosara-EuroVis-2016.pdf

**Comment by anntzer** [comment]
I agree that 3D pies are pretty bad from a readability PoV and don't think it's worth the maintenance burden.  Of course, if anyone is interested, they can still publish this functionality as 3rd-party package and we could link it in the docs.
Also, this hasn't see any activity for years, so closing.
