### ISSUE TITLE
subplot() support for polar()

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#312]
[Original report at SourceForge, opened Thu Sep 17 15:55:03 2009](https://sourceforge.net/tracker/?func=detail&aid=2860903&group_id=80706&atid=560723)

Please add subplot() support for polar() plots. It would be nice if multiple plot types could be combined using subplot(). Thank you!

**Comment by tacaswell** [comment]
This can be done pretty easily:

```python
In [7]: fig = plt.figure()

In [8]: fig.add_subplot(211)
Out[8]: <matplotlib.axes._subplots.AxesSubplot at 0x7f093ae25b38>

In [9]: fig.add_subplot(212, projection='polar')
Out[9]: <matplotlib.axes._subplots.PolarAxesSubplot at 0x7f093ad69ba8>

```
![so](https://user-images.githubusercontent.com/199813/30786674-cc0e0ae4-a147-11e7-8a82-5a0bc6173a66.png)

**Comment by vergelli** [comment]
> This can be done pretty easily:
> 
> ```python
> In [7]: fig = plt.figure()
> 
> In [8]: fig.add_subplot(211)
> Out[8]: <matplotlib.axes._subplots.AxesSubplot at 0x7f093ae25b38>
> 
> In [9]: fig.add_subplot(212, projection='polar')
> Out[9]: <matplotlib.axes._subplots.PolarAxesSubplot at 0x7f093ad69ba8>
> ```
> 
> ![so](https://user-images.githubusercontent.com/199813/30786674-cc0e0ae4-a147-11e7-8a82-5a0bc6173a66.png)

What if i want to draw 2 polar plots under the top plot (Cartesian), both aligned each other.
I am having issues with this.
`fig = plt.figure()

ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(221, projection='polar')
ax3 = fig.add_subplot(212, projection='polar')`

**Comment by jklymak** [comment]
2,2,3 and 2,2,4

**Comment by UmeshDeshmukh** [comment]
but how to do it with OO interface?

**Comment by jklymak** [comment]
? `fig.add_subplot` is the OO interface.

**Comment by jklymak** [comment]
If they are not all polar, you cannot - just add them one at a time as above.
