### ISSUE TITLE
super-ify the code base

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3129]
Convert the add-hoc function call chains to use super.  This will make the code base play nicer with qt5.

**Comment by story645** [comment]
Was this ever worked into a coding guide/style guide?

**Comment by mdboom** [comment]
We have a coding guide (http://matplotlib.org/devel/coding_guide.html) but this is not in there.  I'm not opposed to adding it.

**Comment by timhoffm** [comment]
Some progress made by #10527 and #10541. Still a lot to do.

**Comment by QuLogic** [comment]
I've done most of the 'simple' cases and will open a PR (or a few) shortly. By 'simple', I mean
1. single-class inheritance
2. direct call to superclass method from overriding method

I do not (yet) intend to handle the more complex cases.

**Comment by QuLogic** [comment]
I think this was generally handled by the above PRs.
