### ISSUE TITLE
equivalent of 'xlim_changed' for mpl_connect()

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#317]
[Original report at SourceForge, opened Wed Aug  5 07:51:25 2009](https://sourceforge.net/tracker/?func=detail&aid=2832577&group_id=80706&atid=560723)

The 'callback' events 'xlim_changed' and 'ylim_changed' are only available through the 

callbacks.connect('xlim_changed',dostuff) 

API and there does not seem to be anything equivalent in 'standard' mpl_connect() API. However, this is definitely something that would be very useful (execute a function/method when the view limits change in at least one of the axes)

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue. Thanks!
