### ISSUE TITLE
Changing the legend fontsize "hides" dotted lines in the legend

### ISSUE THREAD

**Issue by dawehner** [matplotlib/matplotlib#3171]
When you change the fontsize of legends using matplotlib.rcParams['legend.fontsize'] you get some kind of crippled result bag. The line in the legend is not shown 100%

http://nbviewer.ipython.org/76ad2a8053ef0b01a7bd

It seems to be that the font properties are somehow applied to the line itself.

**Comment by pmreyes2** [comment]
I wanted to point out, that when using `LineCollection`, there is a mismatch of the size of the lines in the plot and the lines of the handle in the legend. Since the lines of the handle are larger than those from the plot, `handlelength` needs to be used, but the problem is that the lines in the legend are still larger. See this example:
```
lines1 = [[(0, .5), (.5, 1)], [(.3, .6), (.2, .2)]]
lines2 = [[[0.7, .2], [.8, .4]], [[.5, .7], [.6, .1]]]
lc1 = matplotlib.collections.LineCollection(lines1, linestyles="--")
lc2 = matplotlib.collections.LineCollection(lines2, linestyles="-.")
fig, ax = plt.subplots()
ax.add_collection(lc1)
ax.add_collection(lc2)
ax.legend([lc1,lc2],["line1","line2"],handlelength=3)
```
![fig1](https://cloud.githubusercontent.com/assets/3052100/21903403/64a634f8-d8c5-11e6-82a1-706d65677377.png)

**Comment by dopplershift** [comment]
@pmreyes2 Are you talking about the thickness of the lines? If so, does the following (running against matplotlib 2.0rc2) look better?

![test-handle](https://cloud.githubusercontent.com/assets/221526/21905812/fcb5bb2e-d8c5-11e6-9eda-ae719f1dc8aa.png)

**Comment by pmreyes2** [comment]
@dopplershift In your plot I still see different size of lines (in thickness and in dash spacing) I would prefer if the lines in the legend match  the lines in the plot as it does when using `Line2D` . I did my previous plot using version 2.0.0b4. I just tried same code (only `handlelength`=3 was not needed ) in a previous version: 1.5.3 and lines sizes/styles match. So something got changed with the newer versions of `matplotlib`.
 
![fig1_1 5 3](https://cloud.githubusercontent.com/assets/3052100/21906097/84062894-d8cf-11e6-918b-6495ec0b2180.png)

**Comment by tacaswell** [comment]
this is probably fall out from making the dash pattern scale with line width and the LineCollection legend handler pulling linestyle instead of dash pattern.

@pmreyes2 You are definitely hitting a different issue that the OP, can you please open a new issue?

**Comment by pmreyes2** [comment]
@tacaswell  I've just created a new issue: [https://github.com/matplotlib/matplotlib/issues/7814](https://github.com/matplotlib/matplotlib/issues/7814)
