### ISSUE TITLE
Issues with clipping image in display coordinates

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#3173]
For a package I am developing, I need to clip and image (shown with imshow) in display coordinates. Clipping seems to work fine in pixel coordinates:

```python
import numpy as np
from matplotlib.lines import Path
from matplotlib.patches import PathPatch

import matplotlib.pyplot as plt

x = [0.3, 0.6, 0.6, 0.3, 0.3]
y = [0.3, 0.3, 0.6, 0.6, 0.3]

np.random.seed(12345)

image = np.random.random((12,12))

data = np.vstack([x, y]).transpose()
path = Path(np.vstack(data))
poly = PathPatch(path, edgecolor='red', facecolor='none')

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.add_patch(poly)
im = ax.imshow(image, extent=[0., 1., 0., 1.], interpolation='nearest')
im.set_clip_path(poly)
fig.savefig('test1.png')
```

![test1](https://cloud.githubusercontent.com/assets/314716/3432396/3b40ec42-0074-11e4-843b-297be11663d5.png)

but not in display coordinates:

```python
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.add_patch(poly)
im = ax.imshow(image, extent=[0., 1., 0., 1.], interpolation='nearest')

display = ax.transData.transform(data)
path_display = Path(display)
poly_display = PathPatch(path_display, transform=None)

im.set_clip_path(poly_display)

fig.savefig('test2.png')
```

![test2](https://cloud.githubusercontent.com/assets/314716/3432398/4b767c6c-0074-11e4-97a1-5b77c371d573.png)

Is this a bug, or am I doing this incorrectly?

**Comment by petehuang** [comment]
Reconfirming in 2.0.0rc2

**Comment by tacaswell** [comment]
@astrofrog I am not sure this is incorrect behavior.  In the first case (what you called pixel, but I would like to call 'data' as that in the terminology used in http://matplotlib.org/users/transforms_tutorial.html (and 'pixel' is an alias for 'display' in my head).

In the second case (display) you are asking it to clip the image to a path specified in pixels-in-the-final-raster.  If you play with such a figure interactively and resize it, you will see that the clipped region stays a fixed distance from the bottom and left edges.  If you want to clip in terms of display (screen) coordinates, you will need to re-compute what those coordinates are every time the figure size and dpi changes.  I think the reason it works with `aspect='auto'` is the conversion from data space -> display space is happening before `imshow` has had a chance to set the aspect to 'equal'.

Did not check the figure-space example, but I suspect it is the same story.

**Comment by QuLogic** [comment]
@tacaswell is correct about this; you have put your path in fixed coordinates, but calculated those coordinates with outdated transforms. If you put in ` fig.draw_without_rendering()` before the transforms, then it's all correct. But of course, it will all break on resizing.
