### ISSUE TITLE
FormatterPrettyPrint(useMathText=True) is a memory killer

### ISSUE THREAD

**Issue by flomertens** [matplotlib/matplotlib#3177]
When using mpl_toolkits.axisartist.grid_finder.FormatterPrettyPrint, if I set useMathText to True, it use at least 2 time the memory and is a lot slower, especialy when zooming. I suspect there is something wrong there,

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. @flomertens can you help provide the information requested above so the community can help dig deeper into the potential problem? Thanks!

**Comment by QuLogic** [comment]
This has not been answered in about 3 years, so I'm going to close it. @flomertens please re-open if you are able to provide the requested answers.
