### ISSUE TITLE
moderize? boxplot demo

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3187]
This demo might need a bit of tlc: 
http://matplotlib.org/examples/pylab_examples/boxplot_demo2.html

@phobson can this be done more easily using`bxp`?  If not, is it worth extending bxp to make this sort of thing easy?

**Comment by dstansby** [comment]
https://matplotlib.org/gallery/pyplots/boxplot_demo.html#sphx-glr-gallery-pyplots-boxplot-demo-py is a lot better (I'm not even sure if the original one you linked to exists any more)
