### ISSUE TITLE
Add multiline equation support to MPL's math mode

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#321]
[Original report at SourceForge, opened Wed Apr 15 14:40:54 2009](https://sourceforge.net/tracker/?func=detail&aid=2766156&group_id=80706&atid=560723)

MPL currently has great math support for single line equations, but not for multiple line ones.  We ran into this problem when generating docs using sphinx.  The following snippet:
### /begin

.. math::

   E(t) = x + \delta(t)

This type of experiment can be represented by two counting processes
:math:`(E_a, E_b)` defined as

.. math::

   \begin{aligned}
   E_a(t) &=  a + \delta(t) \
   E_b(t) &=  b + \delta(t)
   \end{aligned}
### /end

has one single-line displayed equation, one inline and one multiline chunk.  The first two are rendered fine by MPL, but the latter fails.  It would be great to have MPL support this.

While multiline equations are not too common in plots, they could be very useful in certain cases, if this feature was supported.

**Comment by petehuang** [comment]
Given the age, I wanted to prompt for an update. I don't think multiline equations are supported still, but I'm also wondering if there's any guidance on whether this is still a good request based on MPL scope and impact-feasibility tradeoff

**Comment by tacaswell** [comment]
It still seems like a reasonable thing to want, but it is also still a lot of work.
