### ISSUE TITLE
imshow interpolation=None not working as expected

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#322]
[Original report at SourceForge, opened Tue Mar 31 16:05:53 2009](https://sourceforge.net/tracker/?func=detail&aid=2723839&group_id=80706&atid=560723)

When using interpolation=None in imshow, it seems that matplotlib still uses bilinear interpolation to resample the image:

import matplotlib
matplotlib.use('Agg')
from matplotlib.pyplot import *

import numpy as np

image = np.random.random((10,10))

fig = figure(figsize=(4,4))
ax = fig.add_subplot(111)
ax.imshow(image,interpolation=None)
fig.savefig('plot.png')

This should however be making an image which looks like interpolation='nearest'.

Furthermore, the interpolation=None implies that the image should not be resampled, for example when outputting to postscript or svg files, but this is not the case. For example, interpolation=None suggests that the following code should produce two files of similar size:

import matplotlib
matplotlib.use('PS')
from matplotlib.pyplot import *

import numpy as np

image = np.random.random((10,10))

fig = figure(figsize=(4,4))
ax = fig.add_subplot(111)
ax.imshow(image,interpolation=None)
fig.savefig('example1.ps')

fig = figure(figsize=(8,8))
ax = fig.add_subplot(111)
ax.imshow(image,interpolation=None)
fig.savefig('example2.ps')

At least, that is what the expected behavior should be from a user point of view. If interpolation=None actually does do an interpolation, then interpolation=None should not exist, and the default should be interpolation='nearest'
#### On Sat Apr  4 22:40:23 2009, efiring wrote:

Part of this is a problem of user interface design, convention, and backwards compatibility.  In our typical usage, the object None means use the default, which can be hardwired or taken from rcParams.  In this case it is an rc setting, and for as long as I can remember that default has been 'bilinear', not 'nearest'.  It is not what I would have chosen, either, but I don't think it is going to change any time soon. 

The other part is not strictly a bug, but it does seem to be a valid suggestion for improving some of the backends, so I am moving this from the "bugs" list to the "feature requests" list.  It is not something I am going to be able to work on.  Maybe Darren or Jouni?
### SourceForge History
- On Sat Apr  4 22:40:23 2009, by efiring: data_type: 560723

**Comment by derangedhk417** [comment]
Strangely enough, even when you use interpolation='none', the macosx backend will ignore it and do whatever it feels like when rendering an eps file. 
<img width="231" alt="Screen Shot 2019-07-11 at 3 20 29 PM" src="https://user-images.githubusercontent.com/15893548/61078797-7c557f80-a3ef-11e9-97cd-aa283b36375b.png">
