### ISSUE TITLE
Setting a fixed size for points in legend

### ISSUE THREAD

**Issue by Gabriel-p** [matplotlib/matplotlib#3225]
There is currently, to the best of my knowledge, no easy way to set the size of points in a legend to a fixed equal value if they have different sizes in the scatter plot (you can only _scale_ them)

This question, and the amazing answer given, give more details: http://stackoverflow.com/questions/24706125/setting-a-fixed-size-for-points-in-legend

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. As an update, #4257 seems to have stalled - please see the PR discussion for the last discussion points and pick up from there if interested.

**Comment by oscargus** [comment]
There is a new issue that contains a bit of code to solve this programmatically and a bit more discussion, so I close this. #12417
