### ISSUE TITLE
Navigation API Needed

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/matplotlib#3232]
Having tried to work with matplotlib for developing custom features to the navigation bar, I have found the API cumbersome and virtually non-existent.

As an example, consider this code:
```python
import numpy as np
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt

def say_hello():
	print ('Hello World')

fig = plt.figure()
fig.canvas.toolbar.addAction('Hello World', say_hello) # Qt4Agg
#fig.canvas.toolbar._Button('Hello World', 'subplots', say_hello) # TkAgg
#... many more examples

plt.show()
```

Even with the current code as it stands it looks ripe for refactoring, while making it the code far easier for developers in the future.

I don't mind taking this on, I see it as a nice little wishlist project.  Not sure how much time I have though to devote to it, so I can't guarantee a fast completion.  Also I feel rather new to github projects, so if someone could point me in the direction of a ``How to contribute to matplotlib'', I would greatly appreciate it :D.

**Comment by fariza** [comment]
We forgot to close this one
