### ISSUE TITLE
Changing color of axes, labels, tickmarks in one move 

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#326]
[Original report at SourceForge, opened Fri Nov 28 09:18:38 2008](https://sourceforge.net/tracker/?func=detail&aid=2355895&group_id=80706&atid=560723)

It looks like (or at least I haven't found it !) there is at the moment no way of changing the color of the whole set {axes,axes labels, tickmarks, legend edgecolor, colorbar edgecolor} to a given color in one command. This would be particularly useful to display plots on non-white backgrounds, e.g. white plot on black background ("negative"). At the moment the only solution seems to be to set a series of rc parameters to the desired color, but the default colors of tickmarks cannot be controlled in matplotlibrc for instance, which makes the whole process of changing from black on white to white on black rather cumbersome (particularly when there are colorbars with tickmarks in the figure).

Thank you very much for reading my request and potentially considering it in future releases.

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? What's the latest discussion / development for this? Thanks!

**Comment by derek-etherton** [comment]
I believe the addition of stylesheets provides an easy way to apply color to many graph components "in one move." Would it be worth the added convenience to go ahead with an additional "set_artists_color" method as was discussed earlier, or is this wishlist item pretty much fulfilled already?

Cheers.

**Comment by efiring** [comment]
I think this is adequately handled by styles.
