### ISSUE TITLE
Why does rec2csv ignore float precision?

### ISSUE THREAD

**Issue by gatagat** [matplotlib/matplotlib#3267]
Current `rec2csv` behavior for float data is to ignore the precision set by the caller and write all floats at maximum precision. This behavior seems counter-intuitive, especially, if you call it with `formatd`.

I wanted to submit a patch, but then noticed this is mentioned in the docstring:

> for formatd type FormatFloat, we override the precision to store
> full precision floats in the CSV file

 What is the rationale behind? Should not `rec2csv` honor the `formatd` items set by the caller?

**Comment by QuLogic** [comment]
`rec2csv` is deprecated in 2.2, so I don't think any changes like this are going to be implemented. You should shift to using NumPy's built-in functions like `np.savetxt` or `np.recarray.tofile`.
