### ISSUE TITLE
thetamin/-max for polar plot 

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#328]
[Original report at SourceForge, opened Sun Jun 15 16:58:00 2008](https://sourceforge.net/tracker/?func=detail&aid=1994587&group_id=80706&atid=560723)

It would be nice if there is a possibility to display only a circular sector of a polar plot. 
At the moment there is always plotted the full circle (360 degree).

So I suggest a thetamax and thetamin parameter for the polar plot.

Thanks!

**Comment by QuLogic** [comment]
So what's the actual way going forward here? Copying stuff from mpl_toolkit into the polar axes? (That code is ugly.)

The best result (from a user perspective) would be being able to set theta min/max on a regular polar axes. Using mpl_toolkit is already in the examples and not particularly nice.

**Comment by mspacek** [comment]
I agree, I think it would be best to make this a feature of regular polar axes. Even when I wrote it, I didn't understand some of the code in

https://github.com/neuropy/neuropy/blob/master/neuropy/scripts/polar_demo.py

which itself was mostly copied from mpl_toolkits:

http://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#floating-axes

I just got it to work through trial and error. So, I'm not sure I'm qualified to merge this into `pyplot.polar()`.

**Comment by caichao** [comment]
wonderful works. @mspacek
