### ISSUE TITLE
legend: reverse horizontal order of symbols and labels

### ISSUE THREAD

**Issue by fhoefling** [matplotlib/matplotlib#3285]
I want to customise a figure legend by reversing the horizontal order of the symbols and labels. Example: change `x  data1` to `data1  x`. In Gnuplot, this is simply achieved by `set key reverse`.

In matplotlib, there seems to be no user-friendly solution, or no solution at all. I've found examples how to reverse the *vertical* order, but no means to move the symbols (handles) *to the right* of the labels.

As a low level solution, I thought about changing a kind of handle anchor or just shifting the handle's position, but couldn't even find an entry point for that.

**Comment by cimarronm** [comment]
Closed via #3499
