### ISSUE TITLE
Using env var to control where tmp files will be written to?

### ISSUE THREAD

**Issue by ebreitmo** [matplotlib/matplotlib#3292]
Hello,

 In '**init**.py' there is the method '_get_home()' which sets the name of the directory for temporary files. Would it be possible to to extend the code such that it would allow the setting of an env var to control where tmp files are written to?

Thanks,
Elena

**Comment by anntzer** [comment]
MPLCONFIGDIR should suffice.  If you set it to somewhere nonwriteable, we fallback to gettempdir which is *also* customizable by environment variable (https://docs.python.org/3.6/library/tempfile.html#tempfile.gettempdir).

Feel free to request a reopen if neither solution is sufficient for you.
