### ISSUE TITLE
markerfacecolor / mfc not in rcparams

### ISSUE THREAD

**Issue by RinaldoB** [matplotlib/matplotlib#3293]
I can set the default marker for line plots thru:

`rcparams['lines.marker']` but `rcparams['lines.markerfacecolor']` does not exist.
Did  I miss a different way for the defaulr marker face color?

**Comment by petehuang** [comment]
#3583 has stalled but it is clearly spells out what work needs to be done to address this issue.

Recommend labeling as Difficulty: Medium due to level of work required to adjust `linestyle` to check this param properly

**Comment by anntzer** [comment]
fixed in #8479
