### ISSUE TITLE
assert mods.pop(0) == 'tests' errors for multiprocess tests on OSX

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#3314]
I'm testing OSX builds using Matt Terry's build grid.  All the matplotlib builds are giving multiple errors like this:

```
======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/loader.py", line 284, in generate
    for test in g():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 152, in test
    baseline_dir, result_dir = _image_directories(self._func)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 303, in _image_directories
    assert mods.pop(0) == 'tests'
AssertionError
```

See: https://s3.amazonaws.com/archive.travis-ci.org/jobs/30794968/log.txt

It's not clear where the failures are coming from, but this is an excerpt from the stdout of the tests.

```
matplotlib.tests.test_triangulation.test_tri_smooth_contouring.test ... ok
Failure: AssertionError () ... FAIL
matplotlib.tests.test_triangulation.test_triinterpcubic_C1_continuity ... ok
matplotlib.tests.test_triangulation.test_tri_smooth_gradient.test ... ok
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
Failure: AssertionError () ... FAIL
matplotlib.tests.test_transforms.test_pre_transform_plotting.test ... ok
```

I can replicate the failures on my laptop in a clean virtual machine, but only when running the tests via the multiprocessing plugin:

```
python ../matplotlib/tests.py -sv --processes=8 --process-timeout=300
```

Running in single process mode gives no failures.  Does anyone have any idea how I could investigate further?

**Comment by jenshnielsen** [comment]
This happens on Travis if I replace `python setup.py install` with `pip install .` as part of trying to get #4678 to work

**Comment by jenshnielsen** [comment]
https://travis-ci.org/jenshnielsen/matplotlib/builds/88694941 fails on Travis due to this with the only change being the install via pip build from https://github.com/jenshnielsen/matplotlib/tree/pipinstalltravis

**Comment by jenshnielsen** [comment]
Some more debugging shows that this happens for tests within `mpl_toolkits`

For regular Matplotlib tests mods is something like `['tests', 'test_cycles']` where 
it returns ['test_mplot3d'] or ['test_axes_grid1'] within mpl_toolkits. Not at all sure why this is different with multiprocessing or why it's different with a pip install

**Comment by jenshnielsen** [comment]
The same happens without multiprocessing if you do

`python tests.py mpl_toolkits`

It looks like yet another namespace oddity

**Comment by mdboom** [comment]
@jenshnielsen: Thanks for getting to the bottom of this.  I'm now able to reproduce...
