### ISSUE TITLE
Display legend in reverse order

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#333]
[Original report at SourceForge, opened Mon Jul 16 12:03:19 2007](https://sourceforge.net/tracker/?func=detail&aid=1754863&group_id=80706&atid=560723)

It would be nice if the legend() command had an option 
to print the legend in reverse order.  This would be useful when many lines are drawn on a plot and you would like the first legend element to correspond to the top-most curve of the plot.  This is good form, especially when the the same color is used multiple times.  The curves could be plotted in reverse order, but this is not always convenient.

For example, if I had the loop:

for index,number in enumerate(arange(16)*2):
    plot(y_data[index,:],label='Number %i'%number)
legend()

I would have to rewrite this as:
for index,number in enumerate(arange(15,-1,-1)*2):
    plot(y_data[(15-index),:],label='Number %i'%number)
legend()

It would be more convenient if I could use the original 
plot loop and just use a command like:
legend(reversed=True)

**Comment by alexsalo** [comment]
General approach to fix the problem:

    handles, labels = axis.get_legend_handles_labels()
    axis.legend(reversed(handles), reversed(labels), loc='upper left')  # reverse to keep order consistent
