### ISSUE TITLE
Issues with `imshow` and  RGBA values

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3343]
Raised at https://stackoverflow.com/questions/25089068/how-does-imshow-handle-the-alpha-channel-with-an-m-x-n-x-4-input  by @mwaskom

```
import numpy as np
import matplotlib.pyplot as plt

d = np.ones((100, 100, 4), dtype=np.uint8)*255
d[:, :, 3] = np.linspace(0, 255, num=100)
plt.imshow(d, interpolation='none')
plt.show()
```

One might expect the image to be completely white (as semi-transparent white over white should still be white), but is instead gray in the middle due to pre-multiplying of the alpha (1, 1, 1, .5) -> (.5, .5, .5) which is then composited with the background as an opaque layer, hence the gray.

Previously (related) discussion:

 - https://www.mail-archive.com/matplotlib-users@lists.sourceforge.net/msg22377.html
 - PR #545

**Comment by gcr** [comment]
This issue also affects me. Looks like matplotlib is doing some double-multiplication of the alpha value.

**Comment by hitzg** [comment]
I believe that this is also related to this issue: http://stackoverflow.com/questions/32828445/matplotlib-colormap-with-transparency-looks-different-in-colorbar-and-imshow

**Comment by goerz** [comment]
I'm also running into this. Here's an interactive notebook that should illustrate the issue nicely: http://nbviewer.ipython.org/gist/goerz/d6543e0878c1a10ed0da

**Comment by QuLogic** [comment]
@tacaswell This was fixed by #5718 and the one I _meant_ to close instead of #5949.

**Comment by tacaswell** [comment]
@QuLogic Ah, that makes more sense.

Thanks for all of your work keeping the issues tidy!

**Comment by tacaswell** [comment]
@KelSolaar Can you open a new issue for this with a minimal example?

**Comment by KelSolaar** [comment]
@tacaswell : I will!
