### ISSUE TITLE
devel doc independent from release

### ISSUE THREAD

**Issue by fariza** [matplotlib/matplotlib#3352]
The development documentation on the matplotlib webpage is tied to the latest stable release http://matplotlib.org/devel/index.html

Would it be possible to have at least this section to be "Automatically" updated when changes are made on `master`? 

Another option, that I like even better, is to do something **Django style** if you look at the documentation page https://docs.djangoproject.com/en/dev/ , it offers the possibility to view the docs for diferent releases including the development (`master` in our case) with a little js widget at the bottom of the page.

**Comment by tacaswell** [comment]
I am going to close this now that we have 
  - the 1.4.X-doc branches (so we can easily update the docmentation (that is the rst side of things) if needed
 - thanks to the work of @jenshnielsen the docs from current master are now pushed back to gh from travis.
