### ISSUE TITLE
feature request: set_data method for errorbar

### ISSUE THREAD

**Issue by parkus** [matplotlib/matplotlib#3366]
It would be awesome to have a `set_data` method for an errorbar object. Using that method for a line object is very convenient when I make complicated plots with labels, text, and so forth. Clearing the entire plot and redrawing everything just to plot some different data is a pain, and I am unable to figure out how to clear just the errobar lines. Even if I could, however, a set_data method would still be more convenient.

**Comment by xnaxe29** [comment]
Hi Guys, 
I am new to github and am not sure how to find solutions for a problem. Please let me know if the problem stated above has been resolved. If not, please let me know where I can follow the developments on the same.
Thanks
Adarsh

**Comment by phobson** [comment]
@xnaxe29 I would try search through the closed pull requests. To look at those, click the "Pull Requests" Tab above, then in the "filter" box, change `is:pr is:open` to `is:pr is:closed` and add your query to that box.

**Comment by davidfokkema** [comment]
Any progress on a `set_data()` for errorbar plots? I'm running into this issue now, myself. It hurts.

**Comment by jklymak** [comment]
Not that I know of.  Should be relatively straightforward if someone were strongly motivated ;-)

**Comment by davidfokkema** [comment]
Severely time-constrained at the moment, unfortunately.

**Comment by smartlixx** [comment]
You can have a look at #4556, and perhaps somebody should work further to implement a PR.
