### ISSUE TITLE
Variable number of ticks with LogLocator for a fixed number of tick labels displayed

### ISSUE THREAD

**Issue by mboquien** [matplotlib/matplotlib#3368]
Hello,

I am having problems removing specific tick labels when using a log scale because the number of elements in ax.get_xticklabels() is variable for a fixed number of displayed label. This is because the padding instead of being always of 1 element on each side actually varies depending on vmin, vmax and stride. It would be easier if the padding was always equal to 1.

Thanks!

**Comment by petehuang** [comment]
This hasn't been updated in a while. The provided code runs with the same output:

```
Number of xticklabels: 6 (4 tick labels displayed)
Number of xticklabels: 7 (4 tick labels displayed)
```

However, it's still unclear if this is a bug. If it is a user understanding issue, we may be able to fix this via docs and examples.

**Comment by tacaswell** [comment]
Closing this with no-action.

Some of the locator have a `prune` attribute [docs](http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.MaxNLocator) which will lop off either the top or bottom most ticks.

@mboquien There have been some big improvements to the default log format labeling in 2.0 (ex http://matplotlib.org/devdocs/users/dflt_style_changes.html#logformatter-labeling-of-minor-ticks)  which might address your underlying issue.
