### ISSUE TITLE
add link to gtk embedding cookbook to website

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3373]
Include a link to https://github.com/spiessbuerger/GTK3-Matplotlib-Cookbook on the website

@spiessbuerger What is your preferred link?

Tagged as 1.5.x as it looks like it is still a work in progress.

**Comment by fariza** [comment]
I think this is dead, no changes in the cookbook since dec 2014. Should we close?

**Comment by efiring** [comment]
Thanks for checking this, @fariza.

**Comment by fariza** [comment]
you're welcome. Glad could help
