### ISSUE TITLE
Add test for cx_freeze to CI test

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3391]
re #3385 

We should add a test of cx_freeze to the travis tests.

**Comment by ibell** [comment]
Bump.  I ran into more cx-freeze issues again with 1.5.1.  Every new version of MPL causes me hours of debugging to get cx-freeze working again!  ARGH!  In this case I had to revert to 1.3.1.

How can we get this working?

**Comment by tacaswell** [comment]
PRs to add tests are always welcome.  On the master branch we now run tests on appveyor so we will get both linux and windows coverage on the test.

I am not sure if this sort of thing fits naturally into the unit test framework, if you have a minimal script that uses `cx_freeze` with mpl, can you put it in the `ci` top level folder and run it from the travis and appveyor configs?

**Comment by ibell** [comment]
I spent a few hours trying to get a simple script to package in cx_freeze
last night and ultimately gave up, finding that pyinstaller worked for my
project without any messing about.

It would still be good if we could add a test.  I can put together an
example, but I have no idea how to force it to fire from the Travis or
Appveyor builds

**Comment by efiring** [comment]
I'm nervous about the idea of putting a test for cx_freeze in Travis.  If a changeset makes the test fail, how many people are going to have the slightest idea of what to do about it--or whether it is a false alarm, given that we already have quite a bit of trouble with those?

**Comment by ibell** [comment]
I certainly see your point.  But it is crucial that matplotlib be able to package into an exe in some fashion or another.  Ideally in both cx-freeze and PyInstaller.  I frequently see problems with both packaging tools with MPL, though PyInstaller does seem the more mature option currently.

**Comment by WeatherGod** [comment]
Maybe make it an "allow fail" test, like we do for the nightly python
builds?

**Comment by dopplershift** [comment]
If we want it to stay working, it needs a test. If it breaks a bunch, we need to figure out how to make it not.

**Comment by jenshnielsen** [comment]
Echoing @WeatherGod I suggest adding it to an allowed failure test in the beginning. If it works fine we can move it to a regular test.

**Comment by efiring** [comment]
I have no idea what requirements must be met for freezing to work.  Would someone provide a link, please? And maybe an example of a change that broke freezing, and how it was fixed?  If a test is added, then I suggest that this information must be added to the Developer section of the mpl docs at the same time.  Or better, it could be added right away.

**Comment by oscargus** [comment]
Is this something that is specific to travis (in that case we can close) or should it be renamed to CI (or something)?

**Comment by tacaswell** [comment]
I am going to close this as won't fix.

I suspect we would merge a weekly cron job to to this test, but probably do not want to run it on every PR.
