### ISSUE TITLE
Errorbar does not plot errorbars centered on the marker

### ISSUE THREAD

**Issue by quovatis** [matplotlib/matplotlib#3400]
Using `errorbar` does not properly center the errorbar on the marker.  See the following example and output.  The issue persists in the legend as well.  The errorbar is a few pixels off center and changing the `linewidth` does not solve the issue.  `snap` kwarg has no effect either.  I have reproduced this using matplotlib 1.2.1 and 1.3.1 on Mac OSX 10.8.4.

```
import matplotlib.pyplot as plt
plt.errorbar([1],[1],[0.1],fmt='k^',capsize=5,capthick=2,ms=9,markerfacecolor='none',mew=2)
plt.show()
```

![errorbar](https://cloud.githubusercontent.com/assets/8526633/4016780/7d8508ca-2a38-11e4-9d51-c406f5804024.png)
![legend](https://cloud.githubusercontent.com/assets/8526633/4016782/8118c4a4-2a38-11e4-8904-12e87f85e013.png)

**Comment by Knusper** [comment]
Is this bug still relevant.  I see it in 1.5.3 on my work machine.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/issues/3400#issuecomment-53292719.

I think this is due (as usual) to stamping -- looks like mpl_cairo does not display the issue (if snapping is turned off).

**Comment by quovatis** [comment]
Still present in 2.1.  Tested macosx, wx, and tkagg backends, and it's present in all of them.

**Comment by dstansby** [comment]
Still an issue in 3.0.1

**Comment by jklymak** [comment]
This is pixel snapping - `plt.errorbar([1],[1],[0.1],fmt='k^',capsize=5,capthick=2,ms=9,markerfacecolor='none',mew=2, label='a', snap=False)` is entered appropriately, and this will not be apparent with high DPI or vector formats.  I'll close, but feel free to re-open if folks disagree.
