### ISSUE TITLE
MEP25 - Artist Manager Class Discussion

### ISSUE THREAD

**Issue by theengineear** [matplotlib/matplotlib#3424]
This issue thread will serve as a better space to launch a solid development branch from.

This is related to https://github.com/matplotlib/matplotlib/wiki/MEP25

The main goal of this thread is to discuss the breadth of what MEP25 needs to solve in a more timely fashion to get development running in the right direction, sooner.

**Comment by theengineear** [comment]
@tacaswell and @bryevdv , just giving you a heads up that I'm jumping back into this. I would love some guidance and a chance to catch up on the status of this project.

**Comment by tacaswell** [comment]
@theengineear Have a look at https://github.com/matplotlib/matplotlib/pull/3944 where I have started (but not made a whole lot of progress on) to improve the existing notion of `Containers` in mpl.  I now think this is the path of least resistance to getting a sane visitor pattern + semantic grouping implemented.  I think sub-classing `Container` provides many of the benefits of what I had been talking about with out adding too much more complexity.

There is a seperate, but related discussion about larger scale refactoring of the library (https://github.com/matplotlib/matplotlib/pull/3587).  This is relevant as there may be some plotting functions which return `Containers` which do not currently.  I think we could implement this in a backwards compatible way by putting the new functions in their own module and then using that function in the axes method, extracting the artists and returning them to match the existing API.

There will have to be some discussion about how far we want to preserve back-compatibility on people reaching in and touching the `lines`, `patches`, etc attributes on `Axes` objects to remove artists rather than using the `remove` method on the artists.

Also see  https://github.com/matplotlib/matplotlib/pull/4014 for how to get to existing artist tree-walking code.

**Comment by pzwang** [comment]
Yay!  FWIW, I had a nice chat with @tacaswell at Strata NYC a few months ago and although I forget the exact details, I think that he was interested in thinking about how a JSON intermediate layer could be introduced in MPL which then Bokeh (and others) could target.

I looked at #3587; what is the fastest way to get up to speed on the current "tip" of the conversation?  A particular mailing list thread, or...?

**Comment by bryevdv** [comment]
I am pretty swamped this week but I will try to take a more careful look at it when I can. I will say that one thing that discouraged me a bit previously about the conversation in this issue, at least my first impression, is that the discussion seemed to be starting from a different place than I would. I believe the most important thing, and the best chance for interop between the 3-4 (more?) libraries is to start at the lowest ands simplest level, and surface a capability to coordinate basic, static graphical primitives, completely independently of any semantic information, metadata, or controlling. To be clear, I'm not saying that level of coordination is not important or desirable, I'm saying I wonder whether we can have a chance to succeed by starting there.

**Comment by tacaswell** [comment]
@pzwang My current thinking of the critical path is:

 1. get visitor pattern sorted out
 1. get the ability to dump/return our figures to _any_ serialization format other than pickle
 1. sort out how to map that onto bokeh data model (this may be nasty json <-> json transforms or something nicer)

Unfortunately, this discussion is smeared across a number of locations / in person conversations / in my head.

**Comment by tacaswell** [comment]
I think that someone from yhat/ggplot should at least be aware of this discussion.

cc  @glamp

**Comment by theengineear** [comment]
@tacaswell thanks for the info. A bunch to digest! I'll start poking around asap!

**Comment by theengineear** [comment]
@tacaswell , I've looked at the PRs you sent and I've been playing around with models for the visitor pattern. I'm going to try and summarize some of my thoughts so far to try and be on the same page. This is fairly abstracted away from actual implementation, I hope that's alright for this stage in the process.

### Visitor Pattern vs Serializer

Before the idea of changing the structure of an MPL figure was on the table (#3944, if i'm understanding right), I thought the visitor pattern was the way to go. However, I'm now thinking that putting effort into making the structure of artists and their children more predictable has basically the same effect.

To my understanding, the visitor pattern would be a way for some exporter to pass through a figure, collecting information it wants to. If the structure is highly predicable though, this seems more and more trivial? No?

Given that, I was tinkering around with the idea of just defining serializers for each artist.

### Ideal structure

Again, if I'm seeing this right, you're trying to leverage containers into their own artists so that changes there link into the complicated inter-artist interactions? At any rate, is this the sort of structure that will exist?

```
Figure:
    artists:
        Patch:
            artists: ..
            attr1: ..
            attr2: ..
            so on ..
         Axes:
            artists: ..
            attr1: ..
            attr2: ..
            so on ..
    attr1: ..
    attr2: ..
    so on ..
```

If that's what we're shooting for, then our serialization structure could simply be:

```json
{
    "name": "Figure",
    "children": [],
    "context": {}
}
```

`name` is the name of the class, `children` is an array of the serialized artists for the parent class, and `context` is *anything else* about the object that is not an artist.

### Thoughts on a serializer

In trying to not add more code to the artists, I thought we could define a mapping for each artist. Such that given an artist name *aname*, you get back a serializer.

`serializer = artist_name_to_serializer.get(name, None)`

Artists without serializers are forgotten, which will make sense as we develop.

I'm anticipating some fairly complicated logic for handling all the different ways to serialize an artist's context. This is going to bog down artist code so it would be nice separation to have it in a different serializer.

**Comment by bryevdv** [comment]
Of the four outside projects that were originally interested in this work, two are now completely unmaintained. With no work/discussion in 4 years, I propose that this issue be closed and the MEP rejected.

**Comment by tacaswell** [comment]
This is still an important thread of work, but I agree that this attempt at it is at a dead-end.
