### ISSUE TITLE
Response Spectra Tripartite Plot

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#343]
[Original report at SourceForge, opened Wed Dec  7 14:48:58 2005](https://sourceforge.net/tracker/?func=detail&aid=1375635&group_id=80706&atid=560723)

The tripartite plot is a very important plot in seismic
engineering. Not many plot softwares, even commercial
ones, have this capability. If you experts can add this
type of plot in this lib, it will greatly expanding its
use in seismic engineering.

**Comment by boustrephon** [comment]
I have written a tripartite plotting tool In python using matplotlib. What would I need to do to get it included in the repository? Does it need to be written in C?  Is there any guidance on how to submit custom charts?

The routine starts by getting the plot limits and then builds the network of lines from that. It is currently written for plotting against period (although I plan to add the option to plot against frequency) and it does not yet include numbers on the extra axes. I hope to sort those out soon.

**Comment by jklymak** [comment]
@boustrephon You should probably start a stand-alone project for this, and then we will be glad to add to https://matplotlib.org/3.2.1/thirdpartypackages/index.html   These types of graphs are pretty specialized, but we are happy to steer people your way if they need this.

**Comment by QuLogic** [comment]
As this seems to be a seismic thing about response behaviour, it _may_ be something that could be added to [ObsPy](https://github.com/obspy/obspy) or a related package.

**Comment by boustrephon** [comment]
Thank you for these suggestions. The ObsPy package looks very interesting, and I will see if this would fit in there. Strangely enough, they haven’t implemented tripartite plots already. I think this is because they are used more for engineering (for seismic response spectra and shock spectra) than for seismology.
