### ISSUE TITLE
Add note about CHM security issues

### ISSUE THREAD

**Issue by nepix32** [matplotlib/matplotlib#3446]
Thankfully CHM generation was [added back to mpl 1.4.0](https://github.com/matplotlib/matplotlib/pull/3325). However, the file downloaded from [matplotlib download page](https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.4.0/Matplotlib-1.4.0.chm) does not display properly on a Win7/32 bit machine with IE 10.
When downloading to a local directory and opening it (double-clicking), the HTML pane to the right remains blank. The Index/TOC pane to the left works normally (File can be searched). The same machine can open CHM files generated by Sphinx 1.2.2 and the default theme without any issues.

Workaround for me was to use an alternative CHM-Viewer (e. g. SumatraPDF).

**Comment by QuLogic** [comment]
It doesn't appear that CHM files have been produced since 1.5.1.
