### ISSUE TITLE
markers as linestyles

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#346]
[Original report at SourceForge, opened Thu Jan 28 06:12:59 2010](https://sourceforge.net/tracker/?func=detail&aid=2941544&group_id=80706&atid=560723)

Markers are only set at vertices. It would be nice to use them as kind of linestyle such that markers are plotted according to arc length. This would add a completely new dimension to linestyles and increase readibility of plots. Other libraries like R-project support this feature.

For example: Using a dash-dot linestyle but having a 'plus' instead of a dot.
Syntax could be like linestyle='-~+' where the tilde indicates that the following marker is meant as being part of the linestyle and not a vertex marker.

**Comment by petehuang** [comment]
Hi everyone,

Given that #2662 seems to adequately resolve this, I would recommend closing this issue.

**Comment by tacaswell** [comment]
Closing as #2662 provides an 80% solution and a 100% solution would either be very hard to propgate across all backends or involve significant resampling of user data.
