### ISSUE TITLE
Invalid DISPLAY variable

### ISSUE THREAD

**Issue by marcoippolito** [matplotlib/matplotlib#3466]
In my AWS Ubuntu 14.02 instance I installed the matplotlib dependencies and then via pip I installed matplotlib:

sudo apt-get build-dep python-matplotlib

sudo pip install matplotlib

sudo pip freeze:
matplotlib==1.4.0

in a brand new file plotting1.py I wrote:
# !/usr/bin/python

from pylab import *
plot([1,2,3])
show()

after typying chmod +x plotting1.py, I executed the little script:

time python plotting1.py
Traceback (most recent call last):
File "plotting1.py", line 4, in
plot([1,2,3])
File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3086, in plot
ax = gca()
File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 827, in gca
ax = gcf().gca(*_kwargs)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 461, in gcf
return figure()
File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 434, in figure
*_kwargs)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4ag g.py", line 47, in new_figure_manager
return new_figure_manager_given_figure(num, thisFig)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4ag g.py", line 54, in new_figure_manager_given_figure
canvas = FigureCanvasQTAgg(figure)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4ag g.py", line 72, in init
FigureCanvasQT.init(self, figure)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4.p y", line 68, in init
_create_qApp()
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.p y", line 139, in _create_qApp
raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

real 0m0.404s
user 0m0.284s

What do I have to do now?

Looking forward to your kind help.
Kind regards.
Marco

**Comment by LinZichuan** [comment]
I had the same problem and I solved it by adding ```plt.switch_backend('agg')``` after ```import  matplotlib.pyplot as plt```

**Comment by amberkaka** [comment]
@LinZichuan I encoutered this problem too and your solution works. Thanks for your sharing!

**Comment by jenshnielsen** [comment]
For the record it's better to chose a backend before importing pyplot i.e.

```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```

**Comment by aluenkinglee** [comment]
@LinZichuan Great! It works

**Comment by bzhr** [comment]
For me on AWS ec2 instance

`import matplotlib
matplotlib.use('agg')`
Does not work. But 
`plt.switch_backend('agg')`
does the trick.

**Comment by hana9090** [comment]
@jenshnielsen 
I have this error, although I add
```
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```


> Demo for data/demo/000456.jpg
> Detection took 0.233s for 300 object proposals
> Traceback (most recent call last):
>   File "./tools/demo.py", line 153, in <module>
>     demo(net, im_name)
>   File "./tools/demo.py", line 102, in demo
>     vis_detections(im, cls, dets, thresh=CONF_THRESH)
>   File "./tools/demo.py", line 51, in vis_detections
>     fig, ax = plt.subplots(figsize=(12, 12))
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1177, in subplots
>     fig = figure(**fig_kw)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
>     **kwargs)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
>     return new_figure_manager_given_figure(num, thisFig)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
>     canvas = FigureCanvasQTAgg(figure)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
>     FigureCanvasQT.__init__(self, figure)
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
>     _create_qApp()
>   File "/home/usr/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
>     raise RuntimeError('Invalid DISPLAY variable')
> RuntimeError: Invalid DISPLAY variable

**Comment by hana9090** [comment]
@bshr

I have modified as you suggested, by replacing `plt` with  `plt.switch_backend('agg')`
I have the following error:

> Demo for data/demo/000456.jpg
> Detection took 0.268s for 300 object proposals
> Traceback (most recent call last):
>   File "./tools/demo2.py", line 153, in <module>
>     demo(net, im_name)
>   File "./tools/demo2.py", line 102, in demo
>     vis_detections(im, cls, dets, thresh=CONF_THRESH)
>   File "./tools/demo2.py", line 51, in vis_detections
>     fig, ax = plt.switch_backend('agg').subplots(figsize=(12, 12))
> AttributeError: 'NoneType' object has no attribute 'subplots'

**Comment by tacaswell** [comment]
@hana9090 That is not how the library works.  `plt.switch_backend()` changes some global state which affects how future calls to `plt.subplots()` works.

**Comment by teuneboon** [comment]
For others having this issue: for me it was solved by putting the
```
import matplotlib
matplotlib.use('agg')
```
all the way at the top of the file it was used in. Initially I though "hmm, it should be fine as long as I put it above all other matplotlib stuff", but nope! It had to be all the way on the top for it to work.

**Comment by tacaswell** [comment]
@teuneboon It must be above anything that imports pyplot.

**Comment by HappyStorm** [comment]
@LinZichuan Thanks for sharing!!! It works for me 😆 !

**Comment by empty16** [comment]
@LinZichuan  I encountered this problem too and it works for me, Thanks for sharing! Mark!

**Comment by sulth** [comment]
@tacaswell Iam also having the same problem of visualizing the output using plt.show() ,when used plt.switch_backend().How to solve this issue.

**Comment by WeatherGod** [comment]
switch_backend() probably won't work (although we are working on
improvements to make it possible under certain situations).

It would be hard to figure out your problem without more information. What
OS? Which version of matplotlib? And how did you install matplotlib?

**Comment by sulth** [comment]
Hi Thanks !i got it.it was  due to agg (non interactive visualisation env).replaced it with qt4agg (interactive)and it worked

**Comment by Naman-ntc** [comment]
Is there any other method where matplotlib plots and shows over ssh or manually saving is the only option??

**Comment by kapil-varshney** [comment]
```
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```

^ Solved the problem for me. Thanks @jenshnielsen .

**Comment by debovis** [comment]
Switching to 'agg' does solve the issue. Although I am back stuck at this issue: https://github.com/matplotlib/matplotlib/issues/12074
