### ISSUE TITLE
boxplot() draws (min, max) whiskers after a zero-IQR input regardless of whis value

### ISSUE THREAD

**Issue by barusan** [matplotlib/matplotlib#3468]
When pyplot.boxplot() receives a list of lists one of that is zero-IQR as input X, box and whisker plots of subsequent columns of X will have (min, max) whisker regardless of the value of whis.

For example,

```
X = [data, [0.5], data]     
plt.boxplot(X) # whis = 1.5, flier points should be plotted for the first and third columns of X.
```

the script like above will draw the following figure.

![plt](https://cloud.githubusercontent.com/assets/580998/4149388/39d6b394-3433-11e4-9c0e-ab13db034608.png)

I suspect [this commit](https://github.com/matplotlib/matplotlib/commit/7cf8b357c80c9e1acf78487bf49d2d2fc2683c61).

**Comment by tacaswell** [comment]
@kay10 Can you move this discussion over to #5331 then?
