### ISSUE TITLE
Faster Text drawing needed

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#347]
[Original report at SourceForge, opened Wed Mar 21 08:03:30 2007](https://sourceforge.net/tracker/?func=detail&aid=1685117&group_id=80706&atid=560723)

Drawing of plots with multiple matplotlib.Text instances is so slow as to be unusable for some applications, such as realtime multiple sequence alignment rendering/viewing (see attachment for a pylab example, resize plot window to see effect).

Some layman's thoughts:
* Would it be possible to speed things up by implementing some kind of Text Collection?

* Is antialiasing involved? An option to turn it off would be nice in that case.

#### On Thu Sep  6 16:07:54 2007, mdboom wrote:
Logged In: YES 
user_id=119312
Originator: NO

It appears that the text is re-rendered to a newly allocated buffer each time the text is drawn.  Perhaps some caching of text elements would help.

(Mostly just making a note of it for someone else to work this through, or until I have the time.)

### SourceForge History

* On Wed Mar 21 08:03:30 2007, by yohell: File Added: 221568: test.py

**Comment by Tillsten** [comment]
This would be really nice. After doing some profiling text rendering and complicated tick handling are main reasons for mpl slowness.
