### ISSUE TITLE
What's the best way to make a matplotlib colormap mutable?

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#3491]
I'm working on using IPython widgets for interactive selection of color palettes/maps in seaborn (see the PR here: https://github.com/mwaskom/seaborn/pull/286). For palettes (which are really just lists) this is pretty easy because I can return a list and then, because lists are mutable, update the contents of the list in the body of the interactive function. I'd like to do something similar with matplotlib colormap objects, but I can't see any part of the public API where I would do that. That means that currently I've resorted to

``` python

def _init_mutable_colormap():

    greys = color_palette("Greys", 256)
    cmap = LinearSegmentedColormap.from_list("interactive", greys)
    cmap._init()
    cmap._lut = cmap._lut[:256]
    return cmap


def _update_lut(cmap, colors):

    cmap._lut[:] = colors


def choose_colorbrewer_palette(data_type, as_cmap=False):

    from IPython.html.widgets import interact, FloatSliderWidget

    pal = []
    if as_cmap:
        cmap = _init_mutable_colormap()

    if data_type.startswith("s"):

        opts = ["Greys", "Reds", "Greens", "Blues", "Oranges", "Purples",
                "BuGn", "BuPu", "GnBu", "OrRd", "PuBu", "PuRd", "RdPu", "YlGn",
                "PuBuGn", "YlGnBu", "YlOrBr", "YlOrRd"]

        @interact
        def choose_sequential(name=opts, n=(2, 18)):
            pal[:] = color_palette(name, n, desat)
            palplot(pal)
            if as_cmap:
                colors = color_palette(name, 256)
                _update_lut(cmap, np.c_[colors, np.ones(256)])

    if as_cmap:
        return cmap
    return pal

```

This works fine, but it relies on non-public methods/attributes and so I'm somewhat wary (though not totally wary as this is an interactive function and underlying matplotlib changes would be annoying but not catastrophic).

But perhaps there is some part of the public API for colormap objects that would make this easier?

**Comment by petehuang** [comment]
Can someone summarize the discussion? What's the latest, standalone understanding of the feature request?
