### ISSUE TITLE
fill_between disappears on axis limit change

### ISSUE THREAD

**Issue by marcopigg** [matplotlib/matplotlib#3553]
Running the fill_between_demo.py, if I zoom on figure 1 the fill_between shape disappears. Figure 2 and 3 instead zoom in correctly. It looks like this also happens when calling ax.set_xlim() in a python script, after fill_between has been called.

I am using matplotlib version 1.4.0 on Linux. This affects both python 2.7.8 and 3.4.1, and both Linux 32 bit and 64bit.

matplotlib 1.3.1 is not affected by this bug.

**Comment by arksch** [comment]
I also encountered this bug on Ubuntu 14.04, upgraded matplotlib from 1.4.0 to 1.4.2 and it was fixed. Still, the fill_between is acting strange after a certain zooming scale. Now it is filling parts, that should not be filled. Whether it does that or not, does not only depend on the zoom, but also on the window size. Extending the window left-right only is moving the part which is filled green also from left to right (see the attached plot) Extending up-down doesn't change anything. Zooming in even more gives some, probably overlapping,
![extending_left_right](https://cloud.githubusercontent.com/assets/10656207/5859372/11416268-a25a-11e4-829c-76812b76ddc4.png)
![strong_zoom](https://cloud.githubusercontent.com/assets/10656207/5859368/11133686-a25a-11e4-9862-733ee8349b87.png)
![whole_plot](https://cloud.githubusercontent.com/assets/10656207/5859371/113d545c-a25a-11e4-8f86-568c1d270a41.png)
![zoom_as_expected](https://cloud.githubusercontent.com/assets/10656207/5859369/11172700-a25a-11e4-9109-4e8d3f1260b9.png)



 fill_betweens from other parts of the plot.

**Comment by tacaswell** [comment]
@arksch Can you reduce this example to a [sscce](http://sscce.org/)?  I can't tell from your description (and lack of code) what _should_ be happening or what _is_ happening. 

I suspect that this is yet more issues with clipping of polygons....

**Comment by arksch** [comment]
Ok, I'll prepare one. Thanks for the quick answer.
