### ISSUE TITLE
Bug fix for plotting minor ticks

### ISSUE THREAD

**Issue by nhmc** [matplotlib/matplotlib#3557]
When using `AutoMinorlocator` the rightmost minor tick isn't drawn sometimes (in Matplotlib 1.4).  Changing this line in `class AutoMinorLocator(Locator)` (in `ticker.py`) from:

```
tmax = np.floor((vmax - t0) / minorstep) * minorstep
```

to

```
 tmax = np.ceil((vmax - t0) / minorstep) * minorstep
```

fixes this. I don't completely understand the code though, so this may not be the best fix.

**Comment by tacaswell** [comment]
closed by #3612
