### ISSUE TITLE
move flush_figure logic from ipython

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3561]
Some sub-set of the inline backends logic should be moved over to mpl. 

See discussion in https://github.com/ipython/docker-notebook/pull/7

Issue here so it does not get lost and to get more feed back from mpl devs.

cc @takluyver

**Comment by petehuang** [comment]
Repeating the bump (but this time with a 2+ year gap!). Any new guidance from MPL devs?

**Comment by jklymak** [comment]
I'll close this, but someone should feel to re-open if this really has modern relevance....
