### ISSUE TITLE
boxplot regression testing

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3572]
The boxplot/bxp code has a tremendous number of inputs which are not adequately tested.

A re-factoring of the boxplot code for 1.4 generated a number of regressions, tests should be added to exercise all of the arguments to `plt.boxplot` (with the base-line figures generated using 1.3.1) to ensure that there are no other regressions.

**Comment by QuLogic** [comment]
There are a whole bunch of tests for `boxplot, `bxp`, and `boxplot_stats` added by @phobson in #2643; do we really need to keep this open?

**Comment by SidharthBansal** [comment]
I will be willing to add tests if needed. Can you guys please confirm?

**Comment by phobson** [comment]
I think we have this covered now. I'm closing this, but welcome push back if there's a gap in the coverage that I'm not seeing.
