### ISSUE TITLE
Trouble reducing figure size with tkagg backend

### ISSUE THREAD

**Issue by Stretch97** [matplotlib/matplotlib#3584]
I am having trouble reducing a matplotlib figure's size with the TkAgg backend.

First, let me show that I can increase a figure's size. After running the following code,

```python
    import matplotlib as mpl
    mpl.use('TkAgg')
    import matplotlib.pyplot as plt
    plt.ion()
    fig = plt.figure(figsize = [2, 8])
    fig.set_size_inches([8,8], forward = True)
    fig.canvas.draw()
    print fig.get_size_inches()
```

the call to fig.get_size_inches() gives [ 8, 7.475]. It is a bit annoying that I get 7.475 instead of 8, but I can deal with that. Next, when I run the following code

```python
    import matplotlib as mpl
    mpl.use('TkAgg')
    import matplotlib.pyplot as plt
    plt.ion()
    fig = plt.figure(figsize = [8, 8])
    fig.set_size_inches([2,8], forward = True)
    fig.canvas.draw()
    print fig.get_size_inches()
```

then the call to fig.get_size_inches() gives [ 6, 7.475]. A reduction to 6 is a far cry from 2. Note that interactive mode must be on. If I turn interactive mode off (plt.ioff()) the TkAgg backend gives [8, 8] and [2, 8], but the shape of the figure windows still look more like [8, 7.475] and [6, 7.475].

If I switch to the Qt4Agg backend, the problem goes away.

In case it matters, I am on Matplotlib v1.4.0, with Enthought Canopy 2.7.6, on Mac OS X 10.8.5

[tac edit for markup]

**Comment by tacaswell** [comment]
@Stretch97 Is this fixed by https://github.com/matplotlib/matplotlib/pull/4052?

**Comment by tacaswell** [comment]
I am pretty sure that this should be fixed (as 6 is 3/4 of 8), closing.  Ping to have this re-opened if I am confused.
