### ISSUE TITLE
Won't use a font although it can be found by the FontManager

### ISSUE THREAD

**Issue by MichaelAdolph** [matplotlib/matplotlib#3590]
Hi,
I was asked to file an Issue here on github, although I'm not sure if the problem is not in front of my PC... .

``` python
from pylab import *
from math import sin
rc('text', usetex = False)
la = matplotlib.font_manager.FontManager()
lu = matplotlib.font_manager.FontProperties(family = 'Heuristica')
print la.findfont(lu)
x = np.arange(0,5,0.1)
y = map(sin,x)
title('This is an unnecessary title', family = 'Heuristica')
plot(x,y)
show()
```

As a result I get (besides a graph using an unwanted font):

```
C:\Windows\Fonts\Heuristica-Regular.otf
C:\Python27\lib\site-packages\matplotlib\font_manager.py:1279: UserWarning: findfont: Font   family ['Heuristica'] not found. Falling back to Bitstream Vera Sans
(prop.get_family(), self.defaultFamily[fontext]))
```

If I add Heuristica on first spot of the serif-font-Types this will also not work, (`i. e. font.serif          : Heuristica, Bitstream Vera Serif`)

I am using matplotlib 1.4.0 and Python 2.7.6, I asked this question on [StackOverflow](http://stackoverflow.com/questions/26085867/matplotlib-font-not-found) first

**Comment by liuyang1** [comment]
maybe also /tmp/xdgcache/matplotlib directory in 1.4.1 version

**Comment by bastelflp** [comment]
The matplotlib font cache can be found here: 
Win7: `%userprofile%\.matplotlib\
Ubuntu: `~/.cache/matplotlib`

**Comment by kleinash** [comment]
This is closed so apologies for raising it again. This is not working for me, matplotlib version: 1.5.1.

**Comment by WeatherGod** [comment]
At the least, please try version 1.5.3. It has a lot of fixes that might
address your issue.

There has also been some more work on font handling for 2.0.x and master.
