### ISSUE TITLE
Qt5 backend doesn't work with Qt 5.3

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#3623]
I have previously had the Qt5 backend working with mpl 1.4.0 however It seems broken to me now. 
Trying to do a simple plot with plt.plot results in 

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-bf7ca2578bf6> in <module>()
----> 1 plt.plot(range(100))

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/pyplot.py in plot(*args, **kwargs)
   3089 @_autogen_docstring(Axes.plot)
   3090 def plot(*args, **kwargs):
-> 3091     ax = gca()
   3092     # allow callers to override the hold state by passing hold=True|False
   3093     washold = ax.ishold()

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/pyplot.py in gca(**kwargs)
    826     matplotlib.figure.Figure.gca : The figure's gca method.
    827     """
--> 828     ax =  gcf().gca(**kwargs)
    829     return ax
    830

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/pyplot.py in gcf()
    460         return figManager.canvas.figure
    461     else:
--> 462         return figure()
    463
    464 fignum_exists = _pylab_helpers.Gcf.has_fignum

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/pyplot.py in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, **kwargs)
    433                                         frameon=frameon,
    434                                         FigureClass=FigureClass,
--> 435                                         **kwargs)
    436
    437         if figLabel:

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/backends/backend_qt5agg.py in new_figure_manager(num, *args, **kwargs)
     46     FigureClass = kwargs.pop('FigureClass', Figure)
     47     thisFig = FigureClass(*args, **kwargs)
---> 48     return new_figure_manager_given_figure(num, thisFig)
     49
     50

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/backends/backend_qt5agg.py in new_figure_manager_given_figure(num, figure)
     53     Create a new figure manager instance for the given figure.
     54     """
---> 55     canvas = FigureCanvasQTAgg(figure)
     56     return FigureManagerQT(canvas, num)
     57

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/backends/backend_qt5agg.py in __init__(self, figure)
    179         if DEBUG:
    180             print('FigureCanvasQtAgg: ', figure)
--> 181         FigureCanvasQT.__init__(self, figure)
    182         FigureCanvasAgg.__init__(self, figure)
    183         self._drawRect = None

/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib-1.5.x-py3.4-macosx-10.9-x86_64.egg/matplotlib/backends/backend_qt5.py in __init__(self, figure)
    235         # __init__() takes exactly 2 arguments (1 given) on QWidget
    236         # PyQt5
--> 237         super(FigureCanvasQT, self).__init__(figure=figure)
    238         self.figure = figure
    239         self.setMouseTracking(True)

TypeError: 'figure' is an unknown keyword argument
```

This is naturally because QtWidgets.QWidget does not take a `figure` keyword argument. Removing the kwarg seems to resolve the issue with a simple figure. But I am unsure if the intention of this line is to call init on QtWidgets.QWidget or FigureCanvasBase which does take that kwarg. 

Since this has working before I guess that this is somehow related to me upgrading to Qt5.3. 
The traceback above is from the master branch but the same seems to happen with 1.4.0

**Comment by fccoelho** [comment]
I am still having this issue: on pyqt5 5.4.2 and matplotlib 1.5.0
 Can't even force matplotlib to use a different backend with 
```python
matplotlib.use('GTKAgg')
```
here is my error message:

```python
File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_qt5.py", line 239, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: 'figure' is an unknown keyword argument
```

**Comment by WeatherGod** [comment]
Try the rc for v1.5.1, which should have this fix.

**Comment by tacaswell** [comment]
Are you calling `use` before you import `pyplot`?

**Comment by fccoelho** [comment]
Yes I am.

On Wed, Jan 6, 2016 at 3:37 PM, Thomas A Caswell <notifications@github.com>
wrote:

> Are you calling use before you import pyplot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/3623#issuecomment-169399164>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by tacaswell** [comment]
Can you provide a full example of how to trigger this?

```python
import matplotlib
matplotlib.use('gtkagg')
import matplotlib.pyplot as plt
```

should never touch any of the Qt related files.

**Comment by fccoelho** [comment]
This is what I have:

```python
import matplotlib
matplotlib.use('GTKAgg', force=True)
from matplotlib import pyplot as P
```

On Wed, Jan 6, 2016 at 4:17 PM, Thomas A Caswell <notifications@github.com>
wrote:

> Can you provide a full example of how to trigger this?
>
> import matplotlib
> matplotlib.use('gtkagg')import matplotlib.pyplot as plt
>
> should never touch any of the Qt related files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/3623#issuecomment-169408951>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by fccoelho** [comment]
here is a full example in  ipython --pylab
```python
plot([1,2,3])
```
Now if I do a `matplotlib.use('Agg')` or another non-qt backend, before importing pyplot, I get an import error:
```
ImportError: Gtk* backend requires pygtk to be installed.
```

**Comment by tacaswell** [comment]
Because using `--pylab` implicitly import `pyplot`.  We do not officially support switching gui backends once you have imported `pyplot`.

**Comment by fccoelho** [comment]
I had another library importing pyplot before my call to `matplotlib.use`. Now I am able to switch backends.
Thanks for the help.

**Comment by tacaswell** [comment]
I had a conversation with @weathergod about how to delay the import of the
gui tool kits until you make the first figure which would reduce pain like
this, but I do not think either of us had the bandwidth to do anything
about it.

**Comment by WeatherGod** [comment]
I have notes that I made while writing up my book about this idea, but I
have to find them and decode my awful handwriting...

**Comment by mgrady3** [comment]
I have a working PyQt4 app that I have begun working on upgrading to PQt5; I am running into this same old issue of the missing figure positional argument.

My development details:
python 3.5 via anaconda in a separate environment.
I have installed pyqt5
I have installed matplotlib 1.5.1 np111py35_0 via conda
This insall requires Qt4 and PyQt4 to be installed, so after installing matplotlib I went back and ran 'conda remove qt' and 'conda remove pyqt'

This leaves me with an environment running python 3.5, matplotlib 1.5.1, with an installation of Qt5 and PyQt5.

I begin my code with 
    
    import matplotlib; matplotlib.use("Qt5agg", force=True)

then later in the code I have

    self.LEED_IV_fig, (self.LEED_img_ax, self.LEED_IV_ax) = plt.subplots(1, 2, figsize=(6,6), dpi=100)

    self.LEED_IV_canvas = FigureCanvas(self.LEED_IV_fig)

This fails with 

    Traceback (most recent call last):
    File "/Users/Maxwell/PyCharmProjects/pLEASE/main.py", line 47, in <module>
    main()
    File "/Users/Maxwell/PyCharmProjects/pLEASE/main.py", line 31, in main
    view = gui.Viewer()
    File "/Users/Maxwell/PyCharmProjects/pLEASE/gui.py", line 81, in __init__
    self.init_UI()
    File "/Users/Maxwell/PyCharmProjects/pLEASE/gui.py", line 127, in init_UI
    self.init_tabs()
    File "/Users/Maxwell/PyCharmProjects/pLEASE/gui.py", line 305, in init_tabs
    self.init_LEED_Tab()
    File "/Users/Maxwell/PyCharmProjects/pLEASE/gui.py", line 315, in init_LEED_Tab
    self.LEED_IV_canvas = FigureCanvas(self.LEED_IV_fig)
    File "/Users/Maxwell/anaconda/envs/pyqt5/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
    File "/Users/Maxwell/anaconda/envs/pyqt5/lib/python3.5/site-packages/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
    TypeError: __init__() missing 1 required positional argument: 'figure'

Process finished with exit code 1`


The code can be seen at github.com/mgrady3/pLEASE in the branch dev_PyQt5
The code in question specifically comes from the file gui.py

I can try to come up with a minimal working example to recreate this in the mean time

**Comment by tacaswell** [comment]
You are importing the qt4 backend (
https://github.com/mgrady3/pLEASE/blob/dev_PyQt5/gui.py#L38) explicitly.
The `use` call only affects which backend `pyplot` attempts to use (and we
strongly advise against mixing pyplot + your own embedding; it can work,
but can also break in surprising ways.).

The main difference between pyqt4 and pyqt5 is that with pyqt5 all of the
classes are cooperative so just calling `super` works, where as in pyqt4
you need to manually call each of the parent classes in MI.

The simple fix is to just change your imports an line 38 and 39 to be from
`backend_qt5agg`.

Tom

**Comment by mgrady3** [comment]
Thanks, 
I realized that just a few moments before you posted.

Appreciate the help and quick response.

**Comment by arcooke** [comment]
I'm having this issue too, but even with an incredibly simple test... I cannot for the life of me get this working.

The backend set to `qt5agg` in `matplotlibrc`.. and this:

```
import matplotlib
matplotlib.use("Qt5agg", force=True)
from matplotlib import pyplot as plt

plt.plot([1, 2, 3], [4, 5, 6])
plt.show()
```

Results in this:

```
File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 3306, in plot
    ax = gca()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_qt5.py", line 243, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: 'figure' is an unknown keyword argument
```

**Comment by tacaswell** [comment]
@arcooke I am pretty sure your issue is that you have pyqt4 installed (and not pyqt5).  Check that you can import `PyQt5`.

If that does not solve it please try the mailing list, gitter, or creating a new issue.

**Comment by arcooke** [comment]
@tacaswell 
Thanks a bunch, that was it.. I could have sworn I had that installed.

A bit off topic, but I did get some errors about missing icons when switching from TkAgg (the only one that worked for me) to Qt5Agg.. does this merit a new thread?  I am using Papyrus-Dark icons and it seems to be trying to find a handful of specific icons

```
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
```
![image](https://cloud.githubusercontent.com/assets/6278400/25784632/4cedd4f8-3336-11e7-9ee2-341785d36a47.png)

**Comment by tacaswell** [comment]
Yes. please make a new issue for that.

**Comment by arcooke** [comment]
Done, thank you for the help. :+1:
