### ISSUE TITLE
Feature request for Fancy Arrow: allow arrow head and connector to have separate line attributes

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#3624]
I like that annotations let me place arrows whose shape stay the same when I resize the axes, yet the positions of the arrows move with the axes.  

However, I would like to be able to specify a different line attributes for the arrow head and the connector (arrow line).  Specifically, I want to have a zero line width for the arrow head and a non-zero line width for the connector.  Perhaps the user could specify things like the line width, line style, and line color in the `connectorstyle` string.  For example:

```
anno = ax.annotate('', xy=target, xycoords='axes fraction', \
         xytext=orig, textcoords='offset points', \
         arrowprops=dict(arrowstyle='-|>', mutation_scale = 200, \
         linewidth = 0, connectionstyle = 'arc3, linewidth=1'))
```

**Comment by KanwarGill** [comment]
@breedlun @tacaswell Regarding the issue here, doesn't the `FancyArrow` allow you to modify the arrow head's width and/or length independently? Can you also provide another example perhaps?

FYI @samriddhikaushik

**Comment by tacaswell** [comment]
Couldn't this be effectively done by 

```python
anno = ax.annotate('', xy=target, xycoords='axes fraction', 
                   xytext=orig, textcoords='offset points', 
                   arrowprops=dict(arrowstyle='-', mutation_scale = 200, 
                                   connectionstyle = 'arc3'))
```

**Comment by breedlun** [comment]
@tacaswell's suggestion produces a line without an arrowhead.  I was requesting the ability to independently control the line width for the arrowhead and the connector.    I still want to have a patch for the arrowhead, just no line around the perimeter of the patch.  Sorry if that wasn't clear from my original post.

**Comment by KanwarGill** [comment]
[Example](http://imgur.com/nkTbpTd)

@breedlun Is this a good example of what you want?

fyi @samriddhikaushik @zqliang

**Comment by KanwarGill** [comment]
![pasted image at 2016_03_21 06_06 pm](https://cloud.githubusercontent.com/assets/2533165/13935919/6cb49f8c-ef90-11e5-8144-6d6b3c37a337.png)
@breedlun Is this a good example of what you want?

fyi @samriddhikaushik @zqliang

**Comment by breedlun** [comment]
@KanwarGill, yes, that is an example of what I was requesting.  I was also requesting the ability to have different line styles and colors, but I would certainly be happy with only different line widths.

**Comment by tacaswell** [comment]
#6054 is vaguely related (touching same section of code) and you might be interested in #6117
