### ISSUE TITLE
Enable hatches for Cairo backend

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#363]
[Original report at SourceForge, opened Thu Sep  9 10:51:29 2010](https://sourceforge.net/tracker/?func=detail&aid=3062709&group_id=80706&atid=560723)

Hi, 
I would love to see hatches support with the Cairo backend. Right now I have to go through dynamic loading / unloading of matplotlibs to have hatches for some of my charts. Adding hatches to Cairo would solve this.

Thanks so much for Matplotlib, it really rocks!

**Comment by tobias47n9e** [comment]
I don't know if it needs mentioning that hatches also don't work in `GTKCairo` and `GTK3Cairo`.

**Comment by anntzer** [comment]
For the record hatches are supported by https://github.com/anntzer/mpl_cairo.
