### ISSUE TITLE
Better document meaning of notches in boxplots

### ISSUE THREAD

**Issue by rasbt** [matplotlib/matplotlib#3631]
Hi,
I found a problem regarding the `boxplot` function when the `notch` shape is being used (matplotlib 1.4.0).

I uploaded an self-contained [example](http://nbviewer.ipython.org/github/rasbt/matplotlib-gallery/blob/master/bugreport/boxplot_notch/boxplot_notch.ipynb) as IPython notebook with more details.

![1](https://cloud.githubusercontent.com/assets/5618407/4595245/7f7e2032-5097-11e4-9746-eca01d27a4df.png)

![2](https://cloud.githubusercontent.com/assets/5618407/4595246/82a4d576-5097-11e4-9cd1-83ff1c154c2b.png)

**Comment by kwill** [comment]
I think "won't fix" label needs to be removed, now that this is a documentation ticket? (Thanks for the thorough investigation here and at https://stackoverflow.com/questions/26291082 btw.)

**Comment by WeatherGod** [comment]
good point. tag removed.
