### ISSUE TITLE
Proposal: Add rc setting to control dash spacing

### ISSUE THREAD

**Issue by jgosmann** [matplotlib/matplotlib#3645]
When scaling the figure size the default dash spacing produced by commands like
```plt.plot(x, y, '--')``
does not look good and has to be scaled down. Using the `dashes` keyword argument this is possible, but requires to repeat this for every plotting command.

Therefore, I propose to add an rc setting to control the dash spacing for the default line styles globally.

**Comment by QuLogic** [comment]
Dash scaling was introduced by #6710.
