### ISSUE TITLE
Matplotlib Installing Test Dependencies

### ISSUE THREAD

**Issue by HolgerPeters** [matplotlib/matplotlib#3649]
Hi,

it seems that matplotlib by default now pulls dependencies for testing, such as `nose` and `mock`. While this might be handy for a matplotlib developer, I think this should not be the default for a matplotlib user.

I think the more canonical behaviour would be to install matplotlib (with its tests even) and then let the user install nose and test if they want to run the tests.

I would be willing to contribute a pull request removing the nose and mock from the list of install requirements.

**Comment by QuLogic** [comment]
This was fixed by #4188/#4668, no?

**Comment by jenshnielsen** [comment]
Yes they are no longer installed automatically
