### ISSUE TITLE
FigureCanvasQT backend_qt5agg bug (backend_qt4agg) works

### ISSUE THREAD

**Issue by atsju** [matplotlib/matplotlib#3656]
In this example,
http://matplotlib.org/examples/user_interfaces/embedding_in_qt4.html (embedding_in_qt4.py)
When replacing 
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg
through
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg

I got this error 
 File "C:\Python34\lib\site-packages\matplotlib\backends\backend_qt5.py", line 238, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)

When looking at class FigureCanvasQT in backend_qt5.py and backend_qt4.py it seems that super is calling __init__ on first inherited class (QtWidgets.QWidget) instead of second one (FigureCanvasBase). 

Let me know if I was not clear enough and if it is realy a bug or a missusage.

**Comment by jenshnielsen** [comment]
Finally got a chance to look at this. I believe that this issue is due to a mixture of qt4 and qt5 being imported by different imports. The example added in #4312 shows how to embed in qt5. @atsju if you are still interested it would be great if you can test that example.

**Comment by atsju** [comment]
Hello, 
Thank you for keeping me updated.
I'm really sorry but I haven't access to the computer I used anymore (I haven't Qt and matplotlib installed). I not even remember why I used PyQT4 and not PyQT5 at the time of this bug. I would not do better than the tests you already did for the fix. 
Thank you very much I realy appreciate your work. Sorry I can't do more.

**Comment by jenshnielsen** [comment]
No problem, Just wanted to keep you up to date.

**Comment by jrversteegh** [comment]
As far as I can tell, this issue still exists:

`MPLBACKEND=Qt5Agg python3 -c "import matplotlib.pyplot as plt; fig=plt.figure()"`

**Comment by tacaswell** [comment]
@jrversteegh Do you have pyqt5 installed?

**Comment by jrversteegh** [comment]
Only just after I ran this test ;), so automatic fallback to pyqt4 is the issue here. I guess it shouldn't do that when I explicitly specify the Qt5Agg backend. It should just complain that PyQt5 or PySide2 isn't installed. 
PEP 20: in the face of ambiguity, refuse the temptation to guess :)

**Comment by jrversteegh** [comment]
The issue that brought me here remains: an error in the same place with PySide2.
```
/matplotlib/backends/backend_qt5.py", line 240, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
AttributeError: 'figure()' is not a Qt property or a signal
```
but I guess that's a PyQt5 <-> PySide2 compatibility issue.

**Comment by tacaswell** [comment]
Does pyside2 not do cooperative inheritance?  If so, it just needs to keep going through the qt4 shims.

@jrversteegh That should get it's own issue.

**Comment by adam-grant-hendry** [comment]
@tacaswell PySide2 and PySide6 both ***do not*** yet properly support cooperative multiple inheritance:

- See [PYSIDE-1564](https://bugreports.qt.io/browse/PYSIDE-1564)

There are many different bugs stemming from this documented in the [Qt for Python Development Notes 2021](https://wiki.qt.io/Qt_for_Python_Development_Notes_2021)

Secondly, `PyQt` and `PySide` only accept keyword arguments for optional arguments (i.e. those that are specified as having default values in the docs). See the [PyQt4 docs](https://het.as.utexas.edu/HET/Software/PyQt/keyword_arguments.html) and [PYSIDE-1964](https://bugreports.qt.io/browse/PYSIDE-1964).

Therefore, `figure` is getting passed to the `QWidget` as a keyword argument, which creates the error that gets output by [pyside.cpp::fillQtProperties](https://github.com/pyside/pyside-setup/blob/69d43ea814788a18e8d77920d493fd84f6fc699a/sources/pyside6/libpyside/pyside.cpp#L129).

To work around this, `matplotlib` currently [does the following](https://github.com/matplotlib/matplotlib/blob/0371cf971ff5c81a963683e3e1c2d48002929e21/lib/matplotlib/backends/backend_qt.py#L173):

```python
# To work around lack of cooperative inheritance in PySide2 and
# PySide6, when calling FigureCanvasQT.__init__, we temporarily patch
# QWidget.__init__ by a cooperative version, that first calls
# QWidget.__init__ with no additional arguments, and then finds the
# next class in the MRO with an __init__ that does support cooperative
# inheritance (i.e., not defined by the PyQt4 or sip, or PySide{,2,6}
# or Shiboken packages), and manually call its `__init__`, once again
# passing the additional arguments.
```

This method was recommended by Raymond Hettinger in his PyCon 2015 talk [Super considered super!](https://www.youtube.com/watch?v=EiOglTERPEo) and his corresponding [blog post](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/)
