### ISSUE TITLE
drop test files from source distribution?

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3673]
Do we want to not ship the test files as part of the source distribution?  Doing so would greatly reduce the size of tarball (and this is what @cgohlke does for the windows installers).

**Comment by blink1073** [comment]
My 2 cents: you lose the ability for third parties to catch bugs in their run environments.  I've gotten bug reports before from folks building packages for Gentoo, Arch, and Debian.

**Comment by tacaswell** [comment]
Fair enough.

If we can convince the third parties to use the gh tarball (or just cloning the tag) instead of the sdist tarball that would not be a problem, but that involves getting lots of people to change their packaging scripts so point taken.

**Comment by WeatherGod** [comment]
-1 on dropping test files from the sdist. I rather like the fact that
projects like numpy and scipy includes their test files. It helps me track
down obscure problems in prebuilt distros (usually obscure linker errors).

**Comment by tacaswell** [comment]
right, two :-1:  and this is dead for now.
