### ISSUE TITLE
Runtime detection for default backend

### ISSUE THREAD

**Issue by felixonmars** [matplotlib/matplotlib#3679]
While I'd like to make every backend available for a distribution package, the Qt5Agg backend will be set as default by matplotlib's installation script, and when a user doesn't have qt5 installed, matplotlib will throw an error if the client application didn't specify a backend.

It would be nice if there could be a fallback logic on runtime so the best-available GUI backend will be chosen as the default backend.

**Comment by petehuang** [comment]
I believe this continues to stand as a valid request - please read the thread for some useful discussion

**Comment by anntzer** [comment]
xref https://github.com/matplotlib/matplotlib/issues/8613#issuecomment-301522814

**Comment by anntzer** [comment]
This is implemented as of 3.0 (#9795 and following PRs).
