### ISSUE TITLE
unit tests should compare pyplot.py with output from boilerplate.py

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#3701]
I think adding a simple test that would compare the two (somehow) would be a great way to flag that a particular PR needs to have boilerplate.py executed.

**Comment by tacaswell** [comment]
If this gets done it can go in for 1.5, but this is not a blocker

**Comment by pelson** [comment]
Incidentally, I did try to put it in setup.py many years ago in #928... truth is though, I'd be a bit more reluctant to do it now... we should just make use of the functionality that a non-crufty version of python brings (the original reason that pyplot wasn't just a runtime wrapper module). I know that is where you are hoping to take it currently @tacaswell, and I just wanted to say that I agree with that direction.

**Comment by QuLogic** [comment]
Is the current direction to make a runtime wrapper? Reading the previous discussions, @jkseppan _had_ implemented something along those lines, but didn't commit it. The branch seems to have disappeared, but maybe he still has something hidden somewhere.

**Comment by mdboom** [comment]
> Is the current direction to make a runtime wrapper? 

Yes.  That's my understanding -- i.e. to not use code generation at all, though probably some dynamic creation of objects at import time (I say hand-waving away the details).

**Comment by tacaswell** [comment]
Now that we have dropped 2.6 we can vendor the backport of signature (it is
currently conditionally imported from IPython) and probably do the run-time
wrapping.   The major hold up on this is to not present to the users
`f(*args, **kwargs)` api in pyplot.
