### ISSUE TITLE
Data draws on top of legend.

### ISSUE THREAD

**Issue by Redoubts** [matplotlib/matplotlib#3706]
I would expect the legend to draw on top of everything, but it seems to be obscured by plotted data from time to time.

![figure_2](https://cloud.githubusercontent.com/assets/2435101/4747407/059289c4-5a5c-11e4-846f-28327a359258.png)

The unfortunate above example keeps happening for me on OS X 10.10.

```
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
IPython 2.3.0 -- An enhanced Interactive Python.

Using matplotlib backend: MacOSX
In [2]: numpy.__version__
Out[2]: '1.9.0'

In [3]: scipy.__version__
Out[3]: '0.14.0'

In [4]: matplotlib.__version__
Out[4]: '1.4.1'
```

**Comment by tacaswell** [comment]
Actually, coming back to this again, you can probably use multiple figure legends to get what you want here.

**Comment by soupault** [comment]
@tacaswell Can something be done about this issue within current `matplotlib` structure? I found this bug very sad and will be glad to help fixing it.

**Comment by WeatherGod** [comment]
The primary issue is that the current architecture of matplotlib is
hierarchical: when a figure is drawn, all of its child axes are drawn in
series, so zorder is only respected for within an axes. The way this would
have to be fixed is to hoist up much of Axes.draw() into Figure.draw() so
that the list of child artists to iterate over can have *all* of the
artists and sort them properly.

A bit of complication here is if the bottom axes object is marked "stale"
(needing to be redrawn due to update), but the top axes is not stale, then
the drawing logic might mis-render that in interactive mode (I think, I am
not 100% certain).

**Comment by soupault** [comment]
@WeatherGod ok, thanks! I suppose this should be reworked...

As a temporary workaround I'm using following approach:

I've written a routine which takes `a list of axes` as input and returns united `handles` and `labels`. Then, these vectors has to be used on **last** initialized axes for current figure.

For example, you have
   
    fig, axes = plt.subplots()
    axes_r = axes.twinx()

    # ... HERE YOU PLOT A LOT OF THING ON BOTH axes AND axes_r
    
    def unite_legends(axes):
        h, l = [], []
        for ax in axes:
            tmp = ax.get_legend_handles_labels()
            h.extend(tmp[0])
            l.extend(tmp[1])
        return h, l

    handles, labels = unite_legends([axes, axes_r])
    # ... HERE YOU SHOULD USE LAST axes INITIALIZED. IN THIS CASE IT'S axes_r
    axes_r.legend(handles, labels, loc='center')

For the example of @Redoubts it returns:
![figure_1](https://cloud.githubusercontent.com/assets/1315589/11767500/b47c595e-a1c0-11e5-8154-1aa4e6136ffd.png)

P.S. Actually, I always work with `axes`-array, even if it's 1x1, so my oftenly used `unite_legends` is a bit more complex.

**Comment by NCSUphytotron** [comment]
Any news on this?  I'm still getting data on top of my legend and I'm using Matplotlib version 2.1.

**Comment by WeatherGod** [comment]
nothing has changed with respect to how the drawing architecture is done. I
wouldn't hold my breath on that, either, since that is a fundamental part
of the library architecture. Seems to just be easier to call legend() on
the second axes, instead.

**Comment by NCSUphytotron** [comment]
Hmm, when I declare my plots, the last axes that I declare is the one I call legend() on

```
Graph_Figure = Figure(figsize=(9.4,5.3),frameon=False)   
Graph_Figure.subplots_adjust(left=.09, right=.9, top=.93, bottom=.1)       
Light_Axes = Graph_Figure.add_subplot(211, label='Light',facecolor='gray')
CO2_Axes = Graph_Figure.add_subplot(211,label='CO2',frameon=False,sharex=Light_Axes)   
RelHumid_Axes = Graph_Figure.add_subplot(211,label='RelHumid',frameon=False,sharex=Light_Axes)
AbsHumid_Axes = Graph_Figure.add_subplot(211,label='AbsHumid',frameon=False,sharex=Light_Axes)   
Temp_Axes = Graph_Figure.add_subplot(212,label='Temperature',facecolor='gray')

##plot a bunch of z-ordered stuff on Temp_Axes

Temp_Axes.legend()  
```
...legend still going underneath all the data.

**Comment by ImportanceOfBeingErnest** [comment]
@NCSUphytotron If you want help or inform people about your problem you should always provide a verifiable example (see e.g. [sscce](http://sscce.org)). 

Concerning the general issue here, one can always add the legend to the topmost axes,

```
ax = plt.subplot(111)
ax2.twinx()
# ... some plotting
leg = ax.legend()
leg.remove()
ax2.add_artist(leg)
```

**Comment by baloe** [comment]
> @NCSUphytotron If you want help or inform people about your problem you should always provide a verifiable example (see e.g. [sscce](http://sscce.org)).
> 
> Concerning the general issue here, one can always add the legend to the topmost axes,
> 
> ```
> ax = plt.subplot(111)
> ax2.twinx()
> # ... some plotting
> leg = ax.legend()
> leg.remove()
> ax2.add_artist(leg)
> ```

You can, but then the legend is a random artist and any other code using `ax.get_legend()` downstream no longer works as desired.

**Comment by tacaswell** [comment]
I wonder how much work it would be to "promote" the legend to be a child of the (sub)Figure and not of the Axes?  It is already a specially named attribute on the Axes so figure could look for it to pull out into its draw list (and Axes could decide to ignore it).  However I am worried that this would have unforeseen consequences (like now you could could only put the legend above or below the whole axes, not just some of the artists...would would anyone care about that?) and now the z-order on the legend interacts with the things at the Figure level.

In the process of trying to explain why it is impossible, I have convinced my self it is _plausible_ that we could make this work but  I would want to see the code to try this before deciding one way or the other...

**Comment by jklymak** [comment]
Another approach would be to make the twin axes a child of the parent axes (basically an inset axes) and then let it have a zorder like other children.  I actually do t remember if inset axes have a zorder or if they are just drawn as part of the axes list.

**Comment by WeatherGod** [comment]
@tacaswell If legends get owned by the Figure, how would multiple legends be handled across the multiple subplots? When an axes is cleared or removed entirely, we would need to also remove the corresponding legend from the Figure object.

Also, I would anticipate that having the Figure object manage the legend may make it enticing to have a "shared" legend across subplots, whose semantics would need to be thought out.

**Comment by tacaswell** [comment]
@WeatherGod not move who owns it, just move who draws it. 

 Concretely, in https://github.com/matplotlib/matplotlib/blob/266be1250f61ef3092156c8967623968ececae8e/lib/matplotlib/figure.py#L155-L185 we could "lift" the responsibility of drawing the legend to the figure level and then remove the legend from https://github.com/matplotlib/matplotlib/blob/266be1250f61ef3092156c8967623968ececae8e/lib/matplotlib/axes/_base.py#L2873 .

**Comment by jklymak** [comment]
So, child_axes indeed respect zorder, so that is a pretty easy way to fix this by making the twin a child axes.  

```
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.plot(np.arange(10),'dr', zorder=10, markersize=50)

twinax = ax.inset_axes([0, 0, 1, 1], transform=ax.transAxes)
twinax.set_zorder(15)
twinax.set_facecolor('none')
twinax.plot(np.arange(10, 0, -1), 'db', markersize=50, zorder=100)
ax.set_title('z')
plt.show()
```

plots everything in the twin above everything in the parent:
![twintop](https://user-images.githubusercontent.com/1562854/108375528-e41ca080-71b6-11eb-8f11-11e014503fce.png)

Conversely if we set the twin's z-order to 5, the twin can be below the parent's plot items:

![twinbottom](https://user-images.githubusercontent.com/1562854/108375516-e121b000-71b6-11eb-9fa8-780b14b79d5c.png)

**Comment by jklymak** [comment]
I'm concerned about taking legend out of the parent-child draw hierarchy.  If a legend is to be drawn at the figure level, it should be a figure artist.   On the other hand making twin axes children of their parent would probably solve some other issues that we have with twins, particularly for layout management.

**Comment by tacaswell** [comment]
With the inset approach you still won't be able to layer "data1 < data2 < legend1 < legend2" as the legend for the "bottom" axes will still be drawn before the data in the top axes.

**Comment by jklymak** [comment]
True, it is not infinitely flexible.  Just to be clear, we know there is a `figure.legend` already that will draw on top of everything else?

**Comment by jklymak** [comment]
In the original example:

```
fig.legend(bbox_transform=ax.transAxes, bbox_to_anchor=[0, 0, 1, 1])
```

![orig](https://user-images.githubusercontent.com/1562854/108381339-90ad5100-71bc-11eb-811c-61385109d4aa.png)

**Comment by eddybl** [comment]
The original idea was to have two separate legends.

Here is a minimal working example of the idea of @Oidlichtnwoada :

This works for me as a good work-around
```python
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 7.5, 100)
plt.rcParams['lines.linewidth'] = 5
fig, ax = plt.subplots()
ax2 = ax.twinx()
ax.plot(x, np.sin(x), color="C0", label='ax1')
ax2.plot(x, np.sin(x+0.5), color="C1", label='ax2')
ax2.axvline(0.5, label='ax2', color='darkgrey')
ax.axvline(1, label='ax1', color='lightgrey')
ax.legend(loc='upper left', title="ax1 legend")
ax2.legend(loc='upper right', title="ax2 legend")

# Re-arrange legends to last axis
all_axes = fig.get_axes()
for axis in all_axes:
    legend = axis.get_legend()
    legend.remove()
    all_axes[-1].add_artist(legend)
```
Without re-arranging:
![matplotlib-issue3706-1](https://user-images.githubusercontent.com/43214674/114297052-c4b33d00-9aae-11eb-9e50-0a96afa81f5d.png)

With re-arranging:
![matplotlib-issue3706-2](https://user-images.githubusercontent.com/43214674/114297055-c8df5a80-9aae-11eb-8dc6-985aed80b0fb.png)

**Comment by BeSeeTek** [comment]
@eddybl Tank you for posting this work around
