### ISSUE TITLE
Axis labels only move with spines if there are ticks

### ISSUE THREAD

**Issue by jkseppan** [matplotlib/matplotlib#3715]
The following code plots some random data and moves the spines outward. It works just as expected if it leaves the automatic tick labels alone, but if it disables them the axis labels do not move with the spines. This is on the v1.4.x branch.

```python
import numpy as np
from matplotlib import pyplot as plt

for ticks in True, False:
    fig, ax = plt.subplots(figsize=(10,8), dpi=100)
    plt.subplots_adjust(left=0.3, bottom=0.3)
    data = np.random.uniform(size=100)
    ax.plot(data)
    ax.yaxis.set_ticks_position('left')
    ax.spines['left'].set_position(('outward', 30))
    ax.spines['right'].set_visible(False)
    ax.set_ylabel('random numbers')
    ax.xaxis.set_ticks_position('bottom')
    ax.spines['bottom'].set_position(('outward', 30))
    ax.spines['top'].set_visible(False)
    ax.set_xlabel('sequence')
    if not ticks:
        ax.xaxis.set_ticks([])
        ax.yaxis.set_ticks([])
    plt.savefig('ticks-%s.png' % ticks)
```

The output with ticks enabled:

![ticks-true](https://cloud.githubusercontent.com/assets/92814/4779199/0a975b3c-5c20-11e4-9ce5-a07e61f0b99c.png)

and with ticks disabled:

![ticks-false](https://cloud.githubusercontent.com/assets/92814/4779203/162d27ba-5c20-11e4-9838-270df52711ad.png)

**Comment by cimarronm** [comment]
The problem is the axis label locates on the axes bbox if no tick labels are present. @jkseppan, do you mind taking a look at #4134 and see if that looks good to you
