### ISSUE TITLE
matplotlib tooltips for previous plot figure remain stuck to screen with next figure on Mac OS X 10.10

### ISSUE THREAD

**Issue by js54434** [matplotlib/matplotlib#3746]
If I display a new matplotlib figure using

import matplotlib.pyplot as plt
plt.plot()
plt.show()

and hover the cursor over one of the icons on the bottom such as the pan/zoom icon with the four arrows, it shows a hovering tooltip that says something like "Pan axes with left mouse, zoom with right". If you move the cursor it goes away, as expected. However, if you close that figure, then open another figure, this tooltip will reappear, but usually much fainter, and basically stuck to that part of the screen on that desktop space (even if you quit python) until you hover over an icon and make a new tooltip or log out and log back in to Mac OS X. 

python info: Python 2.7.8 |Anaconda 2.0.1 (x86_64)| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
matplotlib version 1.3.1
Mac OS X 10.10

Tooltip appears normally:
![plot](https://cloud.githubusercontent.com/assets/6426598/4870363/c1828576-6164-11e4-8ed8-231540692a74.png)

Tooltip reappears faintly for a new figure (see very bottom)
![stucktooltip](https://cloud.githubusercontent.com/assets/6426598/4870364/c4a29a66-6164-11e4-9f8a-875bcf0e0a99.png)

**Comment by petehuang** [comment]
Can anyone repro this?

Last update: #4111 (which replaced #3798) stalled with a comment stating the problem is no longer present.

Recommend removing in progress label, adding needs confirmation label

**Comment by cimarronm** [comment]
The original issue is no longer present. There is a related issue with fix in PR #8761.
