### ISSUE TITLE
Slower Imports?

### ISSUE THREAD

**Issue by chebee7i** [matplotlib/matplotlib#3794]
Previously I was running 1.3.1 and this was a typical load time:

```
$ time python -c "import matplotlib;print matplotlib.__version__"
1.3.1

real    0m0.158s
user    0m0.089s
sys     0m0.061s

$ time python -c "import matplotlib;import matplotlib.pyplot as plt;print matplotlib.__version__"
1.3.1

real    0m0.271s
user    0m0.185s
sys     0m0.078s

```

After upgrading to 1.4.2, I'm now getting something like:

```
$ time python -c "import matplotlib;print matplotlib.__version__"
1.4.2

real    0m0.142s
user    0m0.085s
sys 0m0.058s

$ time python -c "import matplotlib;import matplotlib.pyplot as plt;print matplotlib.__version__"
1.4.2

real    0m3.051s
user    0m2.899s
sys 0m0.152s

$ time python -c "import matplotlib;import matplotlib.pyplot as plt;print matplotlib.__version__"
1.4.2

real    0m3.106s
user    0m2.905s
sys 0m0.198s
```

Any ideas on why it is so much slower?

**Comment by mspacek** [comment]
I had the same problem. .pyc files weren't the issue. The solution is documented here:

http://stackoverflow.com/questions/26421364/extremely-slow-import-of-matplotlib-afm

All it required was deleting `~/.cache/matplotlib`.

**Comment by pelson** [comment]
> All it required was deleting ~/.cache/matplotlib.

Thanks @mspacek. I think we should fix this - it is a wart which can be fixed without major hassle (i.e. we should version the cache).

@mspacek - would you mind opening an issue to do that?

**Comment by mspacek** [comment]
Done. #4993
