### ISSUE TITLE
hist2d and x/y limits

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#3815]
The hist2d doesn't behave as expected (at least as I expected) when setting x and y limits.

``` python

x = randn(10000);
y = randn(10000);


figure()
xlim(-2, 2);
hist(x, bins=100); # obeys the xlim

figure();
xlim(-2, 2);
ylim(-2, 2);
hist2d(x, y, bins=100); # sets it's own xlim that seems to depend on bin size
```

Running matplotlib 1.4.2

**Comment by petehuang** [comment]
Are we aware of any other places where this occurs? Happy to open another issue to document the behavior for these while this one sits.

**Comment by dstansby** [comment]
Just a note that this is still an issue on the current master branch.
