### ISSUE TITLE
savefig with bbox_inches='tight' ignores annotation without text

### ISSUE THREAD

**Issue by Stretch97** [matplotlib/matplotlib#3816]
It appears that the bbox_inches='tight' option in savefig ignores annotations without text. Here is my example code

    import matplotlib.pyplot as plt

    fig = plt.figure()
    ax = fig.add_axes([0.2, 0.2, 0.6, 0.6])
    arrow1 = ax.annotate('text', xy = [0.5,-0.2], xycoords = 'axes fraction', \
        xytext = [-72,0], textcoords = 'offset points', \
        arrowprops = dict(arrowstyle = '-|>', mutation_scale = 10.0, \
        shrinkA = 0, shrinkB = 0, linewidth = 1))
    arrow2 = ax.annotate('', xy = [0.5,1.2], xycoords = 'axes fraction', \
        xytext = [-72,0], textcoords = 'offset points', \
        arrowprops = dict(arrowstyle = '-|>', mutation_scale = 10.0, \
        shrinkA = 0, shrinkB = 0, linewidth = 1))
    fig.savefig('test.png')
    fig.savefig('test-tight.png', bbox_inches = 'tight')

Here is test.png, showing that I have two annotations. One annotation, with text, below the axes and one annotation, without text, above the axes.

![][1]

Here is test-tight.png, showing only one annotation. The annotation above the axes, without the text, has been ignored.

![][2]

Looking in the source code, `bbox_inches='tight'` attempts to find the size and location of artists by calling `artist.get_window_extent()`. When I try `arrow1.get_window_extent()`, I get a bounding box that appears to correspond to the text. When I try `arrow2.get_window_extent()`, I get a bounding box with zero height and zero width. Thus, the root of the problem is `.get_window_extent()` doesn't include the arrow.

Any ideas for how to get around this, in a reasonably robust manner? If I could somehow get the proper bounding box for the whole annotation, then I would be in business. However, I can't even seem to get the line or patch objects out of arrow2.

In case it matters, I am on matplotlib 1.4.0, Python 2.7.6, and Mac OS X 10.8.5

  [1]: http://i.stack.imgur.com/5DaZl.png
  [2]: http://i.stack.imgur.com/dAR8h.png

**Comment by itziakos** [comment]
I was hopping that I could spent some time on it over the next two weeks. The main delay is related to making sure that there are tests checking the different configurations for the annotation arrow. I can make a in-progress PR if it is desirable.

**Comment by tacaswell** [comment]
Just put 'WIP' in the title so we know it is a 'work in progress'.

It is probably better to get feed back sooner rather than later.

**Comment by tacaswell** [comment]
This will be tied to #4012 as changing the `get_window_extent` of the annotation will require that in the setup of the arrow it call up to the `Text` version of `get_window_extent`.

**Comment by itziakos** [comment]
Work in progress PR #4023

**Comment by tacaswell** [comment]
Should be fixed by 26c7d656de106534b1871433c965dac9789ef264
