### ISSUE TITLE
quiver is not plotting only 1 vector

### ISSUE THREAD

**Issue by moghimis** [matplotlib/matplotlib#3817]
For some reason my old script which was plotting correctly is not reproducing the same figure.
Here is the line of the code:

```python
axq.quiver([xtexth],[ytexth],[uwnd,],[vwnd,],units=units,scale=scalew,width=0.03,color='b')
```
However if I add 1 element to vector it will plot as before:

```python
axq.quiver([0,xtexth],[0,ytexth],[0,uwnd,],[0,vwnd,],units=units,scale=scalew,width=0.03,color='b')
```
It seems the first element is ommited.

Saeed.

```
In [178]: import matplotlib as mpl
In [179]: print mpl.__version__
1.4.2

```

[TAC edited to add formatting markup]

**Comment by tacaswell** [comment]
@efiring Thoughts on this?

**Comment by efiring** [comment]
It works on 1.4.0, but not on 1.4.2.  Strange.

**Comment by efiring** [comment]
Bisecting shows 350413cb as the first bad commit. @mdboom would you look at this, please?  It's deep in agg.

**Comment by efiring** [comment]
I don't understand why, but this seems to be fixed by #4025.  It must be the elimination of the conditional in the draw method.  How that would be related to my bisecting result, I don't know.

**Comment by rsignell-usgs** [comment]
@tacaswell, this bug was killing me all morning -- my student's notebook was working, and mine was not, eventually tracked this down to my newer matplotlib.  Any chance of releasing 4.1.3 with this bugfix?

**Comment by tacaswell** [comment]
@rsignell-usgs Target date for 1.4.3 is Feb 1, but we still have a few out-standing blockers (mostly #3095 ) so with in the next few weeks.

**Comment by rsignell-usgs** [comment]
@tacaswell.  Okay, thanks for this information and thank you also for all the great work you do for the community!
