### ISSUE TITLE
Ternary projection

### ISSUE THREAD

**Issue by ligon** [matplotlib/matplotlib#3825]
Back in 2011 Kevin Davies did some nice work adding a ternary projection to matplotlib.   This can be found at https://github.com/kdavies4/matplotlib/tree/ternary2.  I think it would be great to see this in the mainline.

The original work Kevin Davies did in 2011 no longer works with recent versions of matplotlib.  I've patched things up (very minor changes), and would like to propose that this new projection be added to matplotlib proper.  My work can be found at https://github.com/ligon/matplotlib/tree/ternary.

**Comment by petehuang** [comment]
Most updated PR is at #6737

**Comment by jklymak** [comment]
In https://github.com/matplotlib/matplotlib/pull/6737 we decided that this should be a third-party package, at least to start.   I'll close here.

**Comment by QuLogic** [comment]
From the PR, there are links to two third-part packages, which may be of use to anyone looking to make these sorts of plots:
https://github.com/yu9824/ternary_diagram
https://github.com/yuzie007/mpltern

**Comment by jklymak** [comment]
https://mpltern.readthedocs.io/en/latest/ is the home of this project now.
