### ISSUE TITLE
Save figure dialog blocks IPython after saving

### ISSUE THREAD

**Issue by lebigot** [matplotlib/matplotlib#3836]
In OS X (Yosemite), saving a file through a dialog can generally prompt the user for the password of any closed (and recently used) disk image (for which no password was saved). The user can then choose to dismiss the password prompt.

The OS X backend of Matplotlib 1.4.2. instead does not show the password prompt dialog, but prints (when in IPython) `Enter password to access "…"` (with the name of the disk image) _and blocks_: IPython cannot be used anymore (no command can be entered).

**Comment by dstansby** [comment]
I can't work out how to reproduce this - @lebigot is this still an issue, and if so could you post a step by step guide to reproduce it?

**Comment by lebigot** [comment]
I did try to reproduce the issue on macOS 13.1, but I can't find my recently mounted (and then ejected) disk image in the figure Save dialog. The dropdown menu with recent items used to show it and it could be selected (which prompted the user for the password of the disk image).

I am closing this, then, especially since I'd be surprised if most users haven't switched to Jupyter!

**Comment by lebigot** [comment]
PS: for reference, the step by step procedure to reproduce this is:

1. Launch Disk Utility so as to create a new disk image.
2. Select File > New Image… > Blank image.
3. Create an _encrypted_ image. Do not save the password.
4. (Maybe: add a file to the new disk, so as to create some "activity" in the new disk.)
5. Eject the new disk.

Before, the (now unmounted) new disk would appear in the (expanded) Save dialog of the macOS backend, and it could be selected. This would prompt the user for the disk image password.
