### ISSUE TITLE
New 'outside' locations for legend

### ISSUE THREAD

**Issue by mrkrd** [matplotlib/matplotlib#3857]
So far placement of legend using the `loc` argument is limited to the inside of the axis (e.g. `right`, `center`, `upper left`, etc). However, often the plotting area is cluttered with the data points, and it is desired to place the legend outside of the axis, as for example described in http://matplotlib.org/users/legend_guide.html#legend-location

It would be useful to have additional `loc` values for quick and intuitive placement of the legend outside of the axis:

```
plt.legend(loc='outside right center')
```

**Comment by petehuang** [comment]
#6182 made some good progress but has stalled since then. PR welcome - it would address #3745 as well.

Recommend labeling with Difficulty: Easy?

**Comment by isentropic** [comment]
I'd like this feature too, but there might be some aspect ratio problems / figure size problems, as now it complicated the layouting

**Comment by jklymak** [comment]
See https://github.com/matplotlib/matplotlib/pull/19743. That got bogged down in the whole anchor dance, which is super flexible but actually a pain to deal with conceptually and algorithmically.

**Comment by QuLogic** [comment]
I guess this is fixed by #19743.
