### ISSUE TITLE
collections.BrokenBarHCollection.span_where not working with pandas timeseries

### ISSUE THREAD

**Issue by fmaussion** [matplotlib/matplotlib#3872]
System:
python 3.3 on linux mint
pandas 0.15.1
matplotlib 1.4.2

Description of the problem:
Trying to use  collections.BrokenBarHCollection.span_where() with pandas timeseries as x values throws an error: TypeError: float() argument must be a string or a number.
see: http://matplotlib.1069221.n5.nabble.com/BrokenBarHCollection-with-pandas-timeseries-td44534.html

Minimal example reproducing the error:

``` python
import pandas as pd
import numpy as np
from datetime import datetime as dt
import matplotlib.pyplot as plt
import matplotlib.collections as collections
span_where = collections.BrokenBarHCollection.span_where

time = pd.date_range(pd.datetime(1950,1,1), periods=5, freq='MS')
df = pd.DataFrame(np.arange(5), index=time, columns=['data'])
df['cond'] = df['data'] >= 3

fig = plt.figure()
plt.plot(df.index, df['data'], 'k')
c = span_where(df.index, ymin=0, ymax=4, where=df['cond'], color='green')
```

**Comment by dacoex** [comment]
The following code show how this can work.

Modified from [api example code: span_regions.py](http://matplotlib.org/examples/api/span_regions.html?highlight=span_regions)


```python
"""
Illustrate some helper functions for shading regions where a logical
mask is True

See :meth:`matplotlib.collections.BrokenBarHCollection.span_where`
"""
import datetime as dt

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.collections as collections
from matplotlib import dates as mdates

import pandas as pd

import seaborn as sns


length = 200
dates = pd.date_range('1/1/2000', periods=length)

vals_t = np.random.randint(100, 800, length)
vals_s1 = (np.random.randint(20, 1500, length) * (-1))




t = np.arange(0.0, 2, 0.01)
s1 = np.sin(2*np.pi*t)
s2 = 1.2*np.sin(4*np.pi*t)


df = pd.DataFrame({'t' : t, 's1' : s1}, 
                  index=dates)



fig, ax = plt.subplots()
ax.set_title('using span_where / pandas')
sin = ax.plot(df.index, df['s1'], 'b', linestyle='-', marker='+', label='sin', linewidth=2.0)

ax_lims = ax.get_ylim()

dates = df.index.to_pydatetime()
x_val = mdates.date2num(dates)


collection = collections.BrokenBarHCollection.span_where(
    x_val, ymin=-1, ymax=1, where=df['s1'] > 0, 
    facecolor='g', 
    edgecolor='red', 
    linewidth=2.0, linestyle='--', 
    alpha=0.2, 
    label='span'    
    )

ax.add_collection(collection)

ticks = ax.get_xticks()
ax.set_xticks(np.linspace(ticks[0], mdates.date2num(mdates.num2date(ticks[-1]) + dt.timedelta(hours=3)), 5))
ax.set_xticks(np.linspace(ticks[0], mdates.date2num(mdates.num2date(ticks[-1]) + dt.timedelta(hours=3)), 25), minor=True)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d.%m.%y: %H:%M'))



legend = plt.legend(frameon = 2)
frame = legend.get_frame()


plt.show()

```

**Comment by dacoex** [comment]
But the following one does not fill the patches. 
I gues the reason is that the cut through the zeroline is between two intervall (here: timestamps)

```"""
Illustrate some helper functions for shading regions where a logical
mask is True

See :meth:`matplotlib.collections.BrokenBarHCollection.span_where`
"""
import datetime as dt

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.collections as collections
from matplotlib import dates as mdates

import pandas as pd

import seaborn as sns


length = 30
dates = pd.date_range('1/1/2000', periods=length)

vals_t = np.random.randint(100, 800, length)
vals_s1 = (np.random.randint(20, 1500, length) * (-1))


df = pd.DataFrame({'t' : vals_t, 's1' : vals_s1}, 
                  index=dates)
df['s2'] = df['t'] + df['s1']


fig, ax = plt.subplots()
ax.set_title('using span_where / pandas')

t = ax.plot(df.index, df['t'], 'blue', linestyle='-', marker='+', label=df['t'].name, linewidth=2.0)
s1 = ax.plot(df.index, df['s1'], 'yellow', linestyle='-', marker='+', label=df['s1'].name, linewidth=2.0)
s2 = ax.plot(df.index, df['s2'], 'brown', linestyle='-', marker='x', label=df['s2'].name, linewidth=2.0)


ax_lims = ax.get_ylim()

dates = df.index.to_pydatetime()
x_val = mdates.date2num(dates)


collection = collections.BrokenBarHCollection.span_where(
    x_val, ymin=-1, ymax=1, where=df['s2'] < 0,
    facecolor='g', 
    edgecolor='red', 
    linewidth=2.0, linestyle='--', 
    alpha=0.2, 
    label='span'    
    )

ax.add_collection(collection)

ticks = ax.get_xticks()
ax.set_xticks(np.linspace(ticks[0], mdates.date2num(mdates.num2date(ticks[-1]) + dt.timedelta(hours=3)), 5))
ax.set_xticks(np.linspace(ticks[0], mdates.date2num(mdates.num2date(ticks[-1]) + dt.timedelta(hours=3)), 25), minor=True)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d.%m.%y: %H:%M'))



legend = plt.legend(frameon = True)
frame = legend.get_frame()


plt.show()


```

![span_regions_pandas_clean_nonworking](https://cloud.githubusercontent.com/assets/8660305/13497514/ea3f0b8e-e155-11e5-8ea5-1bfbc7cf2baf.png)

**Comment by jklymak** [comment]
This all seems to work...

**Comment by szeitlin** [comment]
I'm running into this same error on 3.1.1 with span_where, but fill_between seems to work.

**Comment by jklymak** [comment]
@szeitlin can you make a reproducible modern example? Preferably w/o pandas or seaborn just to keep it clean?

**Comment by szeitlin** [comment]
well the point of what I'm doing is to use it with pandas, but maybe I can carve out time to do that. I'm ok with using fill_between for now (I'm not sure why both methods exist, TBH?).

**Comment by jklymak** [comment]
If pandas is quicker, thats fine.  Just prefer w/o in case the difficulty is with them, not us.

**Comment by szeitlin** [comment]
ok I've got a notebook with an example. lemme see if I can figure out how to get it up here.

**Comment by szeitlin** [comment]
![Screen Shot 2019-12-17 at 5 39 10 PM](https://user-images.githubusercontent.com/5185401/71048470-31edd280-20f4-11ea-99f7-4295308fc60f.png)
![Screen Shot 2019-12-17 at 5 39 52 PM](https://user-images.githubusercontent.com/5185401/71048481-3fa35800-20f4-11ea-9c1f-c0dd30c0fcd3.png)

**Comment by szeitlin** [comment]
```
#this throws the error
collection = collections.BrokenBarHCollection.span_where(df.index,ymin=0,ymax=df['numeric_col'].max(),
                                                         where=df['bool_col']==True,
                                                            facecolor='g', 
                                                            edgecolor='red', 
                                                            linewidth=2.0, linestyle='--', 
                                                            alpha=0.2, 
                                                            label='span')
axes.add_collection(collection)
```

**Comment by szeitlin** [comment]
full traceback:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-264dcc0313f6> in <module>
      6                                                             linewidth=2.0, linestyle='--',
      7                                                             alpha=0.2,
----> 8                                                             label='span')
      9 axes.add_collection(collection)

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/collections.py in span_where(x, ymin, ymax, where, **kwargs)
   1131 
   1132         collection = BrokenBarHCollection(
-> 1133             xranges, [ymin, ymax - ymin], **kwargs)
   1134         return collection
   1135 

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/collections.py in __init__(self, xranges, yrange, **kwargs)
   1111                   (xmin + xwidth, ymin),
   1112                   (xmin, ymin)] for xmin, xwidth in xranges]
-> 1113         PolyCollection.__init__(self, verts, **kwargs)
   1114 
   1115     @staticmethod

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/collections.py in __init__(self, verts, sizes, closed, **kwargs)
   1044         Collection.__init__(self, **kwargs)
   1045         self.set_sizes(sizes)
-> 1046         self.set_verts(verts, closed)
   1047         self.stale = True
   1048 

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/collections.py in set_verts(self, verts, closed)
   1065                     codes[0] = mpath.Path.MOVETO
   1066                     codes[-1] = mpath.Path.CLOSEPOLY
-> 1067                     self._paths.append(mpath.Path(xy, codes))
   1068                 else:
   1069                     self._paths.append(mpath.Path(xy))

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/path.py in __init__(self, vertices, codes, _interpolation_steps, closed, readonly)
    125             and codes as read-only arrays.
    126         """
--> 127         vertices = _to_unmasked_float_array(vertices)
    128         if vertices.ndim != 2 or vertices.shape[1] != 2:
    129             raise ValueError(

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/matplotlib/cbook/__init__.py in _to_unmasked_float_array(x)
   1388         return np.ma.asarray(x, float).filled(np.nan)
   1389     else:
-> 1390         return np.asarray(x, float)
   1391 
   1392 

/opt/anaconda3/envs/eda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

TypeError: float() argument must be a string or a number, not 'Timestamp'
`

**Comment by tacaswell** [comment]
@szeitlin can you make a new issue for this?

**Comment by szeitlin** [comment]
yup
