### ISSUE TITLE
behavior when plotting no data

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#3886]
Minor issue, but some of the plotting functions work when there's no data and some don't.

```python

# These work
plot([])
scatter([], [])
bar([], [])

# These raise a ValueError
hexbin([], [])
hist([])
hist2d([])
```

**Comment by alimehdi92** [comment]
@tacaswell , so should matplotlib support empty data on hist? e.g. follow same behaviour as hsit2d? I might give the fix a shot!

**Comment by umairidris** [comment]
I have made some simple modifications to fix this issue. Please see #4119  

Note: I was not able to reproduce this error with hist2d

**Comment by tacaswell** [comment]
It should support empty data on master now...

**Comment by tacaswell** [comment]
OK, this is odd, I have a clear memory of changing this, but can't find it...

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/3883 is what I was thinking of and the constraints did to get as relaxed as I thought they did.
