### ISSUE TITLE
MarkerStyle Instance not Accepted for scatter

### ISSUE THREAD

**Issue by rosenbrockc** [matplotlib/matplotlib#3895]
The docstring for `scatter` says that the `marker` keyword argument will accept a `matplotlib.markers.MarkerStyle` instance. However, when I pass one in, it breaks when trying to initialize a new `MarkerStyle` instance using an existing one. We could easily replace https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L3647 with the following to fix it:

```python
        if not isinstance(marker, mmarkers.MarkerStyle):
            marker_obj = mmarkers.MarkerStyle(marker)
        else:
            marker_obj = marker
```

or we could just fix the constructor for MarkerStyle to be smarter (a better option).

**Comment by tacaswell** [comment]
Closed by 86e5e6508aa1fb5242c93e1b39cee5098b4db513
