### ISSUE TITLE
Pickle not working in interactive ipython session

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#3899]
When I used the `%matplotlib` magic in ipython (notebook) to enable interactive matplotlib plotting, pickling of figures does not work anymore.

Test code:

```
%matplotlib  
import matplotlib.pyplot as plt
import pickle
fig, ax = plt.subplots()
ax.plot([1,2,3,4], [1,8,4,6])
pickle.dump(ax, file('test_plot.pickle', 'w'))
```

gives:

```
PicklingError: Can't pickle <built-in method copy_from_bbox of tuple object at 0x000000000B2A2988>: it's not found as __main__.copy_from_bbox
```

If I remove the `%matplotlib` line, then it works as expected.

@pelson It was also mentioned in the SO question you answered (http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object), and you encouraged to open an issue report, but I did not found it.

Using matplotlib 1.4.0, Windows 7, ipython 2.3.

**Comment by mfitzp** [comment]
In case it is useful, when I needed to be able to pickle some `Figure` objects post-draw I found the following code was sufficient to get it working (at least with `dill`):

    def figure_prepickle_handler(v):
        v._cachedRenderer = None
        for ax in v._axstack.as_list():
            for axi in ax.images:
                axi._imcache = None
            ax._cachedRenderer = None
        return v
