### ISSUE TITLE
LineCollection/PolyCollection kwargs inconsistency in `facecolor(s)`

### ISSUE THREAD

**Issue by demisjohn** [matplotlib/matplotlib#3902]
Are `LineCollection` and `PolyCollection` supposed to be somewhat analogous? 
If so, there is a disparity in that `PolyCollection` takes the plural key-worded argument `facecolors` while `LineCollection` instead takes the singular `facecolor` - both args otherwise behave identically as far as I can tell.

**Comment by anntzer** [comment]
Also, it would be nice if the alias `fc` (which is present for the Patch class) was also made available there.

**Comment by demisjohn** [comment]
Was this ever implemented?

**Comment by QuLogic** [comment]
`facecolor` and `facecolors` (and `fc`) have been aliases in all `Collection`s for a very long time.
