### ISSUE TITLE
Bug in example user_interfaces/printing_in_wx.html

### ISSUE THREAD

**Issue by kowalsk84** [matplotlib/matplotlib#3908]
http://matplotlib.org/dev/examples/user_interfaces/printing_in_wx.html

In function 

    def onKeyEvent(self,event=None):

it should read 

    key = event.GetKeyCode()

instead of 

    key = event.KeyCode()

**Comment by efiring** [comment]
I can't find any trace of it; I suspect it is an old example that has been deleted, and the broken link was to old documentation.  Closing.

**Comment by jenshnielsen** [comment]
For the record. The  version of the docs stored in dev/ was an old snapshot of 1.3.x. It has been deleted since we are now pushing dev docs from travis automatically.
