### ISSUE TITLE
copy/paste curves between matplotlib figures

### ISSUE THREAD

**Issue by jhillairet** [matplotlib/matplotlib#3914]
First of all, thank you for all of your great work ! 

A recurring remark made by users coming from Matlab against the Python/Matplotlib is the fact that one cannot make simple click/copy/paste of a curve from a figure into another. 

I guess this heavily depends of the backend used, or of the OS. So my question is probably naive, but anyway : would it be possible to add an interactive way to select one or more curves from a matplotlib figure and to copy/paste them into a another figure ? 

It is, I think, a killing feature for many beginners/average users who used to work with matlab before.

**Comment by jhillairet** [comment]
Dear all,

I'm coming back into this discussion. It is, I think, a killer feature for broader adoption of the Python/Matplotlib. 

And by the way, is there a simple way to make a copy/paste of the full image (without having to save a file somewhere) ?

**Comment by fariza** [comment]
@jhillairet I use a custom tool (toolmanager) check https://github.com/matplotlib/matplotlib/issues/1987#issuecomment-90502377 for the basic code, for now only works on GTK3

**Comment by jhillairet** [comment]
This issue is still important, especially for newcomers coming from the MATLAB world.

The following code allows one to make copy/paste the entire figure:
`plt.rcParams['toolbar'] = 'toolmanager'`

Which is already great. But copy/pasting each curve separately would be still very convenient.

**Comment by jklymak** [comment]
I'm genuinely curious why this is a "killer feature" of Matlab?  I used Matlab for many years, and had/have many colleagues who still do, but I've never heard of anyone cutting and pasting objects between figures.  

I'd say this objectively a bad practice from the point of view of reproducibility (as is anything GUI driven).  But even from a GUI-driven workflow, this seems like a clunky thing to do.  Is there a video or instructions of this in action?  My few minutes of googling didn't turn it up. 

We could keep this open, but I'm not sure the use case is that compelling, particularly considering the effort it would take to have this available on our numerous backends.

**Comment by jhillairet** [comment]
I'm working in a control room where users have to look to hundreds of different time series, and find the correlations between events in these time series. So, a lot of them copy paste curved from one figure to another to check these correlations vs time.

I agree this is generally a bad practice, but that's how they work...

**Comment by ksunden** [comment]
I agree that this is niche enough that it should not be on by default or even likely baked in to the core library, but the interactivity tools already give a reasonably good way of doing this:

```python
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.axes import Axes
from matplotlib.lines import Line2D

import numpy as np


fig: Figure
ax1: Axes
ax2: Axes

fig, (ax1, ax2) = plt.subplots(2)

line: Line2D | None  = None

def on_pick(event):
    global line
    if isinstance(event.artist, Line2D):
        line = event.artist
        print(f"Picked line {line!r}")
    fig.canvas.draw_idle()

def on_press(event):
    print("On press: ", event.key)
    if event.key == "n":
        gen_line()
    elif event.key == "ctrl+v":
        print(line)
        if line is not None:
            ax2.plot(*line.get_data(), color=line.get_color())
    fig.canvas.draw_idle()

fig.canvas.mpl_connect("pick_event", on_pick)
fig.canvas.mpl_connect("key_press_event", on_press)

def gen_line():
    global line
    line = ax1.plot(np.cumsum(np.random.random((100))-0.5))[0]
    line.set_picker(5)
    
plt.show()
```

This script allows you to add lines to the top plot by pressing `n` and then paste with `ctrl+v` into the second plot.

It could be dressed up to figure out the axes dynamically, etc.
Currently you just pick and then it is held in a variable that is used on paste. (i.e. I don't actually require you `ctrl-c` first and didn't hook up `ctrl-c`/`ctrl-x`, but both of those would actually be quite possible.)

(Note I was originally trying to use `update_from` to get _all_ the line properties copied over, not just color/data, but that also updates the transform, which we _don't_ want to change here, so I settled for just calling `plot` again)
