### ISSUE TITLE
2d slices in 3d plot

### ISSUE THREAD

**Issue by thisch** [matplotlib/matplotlib#3919]
Is it possible to create plots like the one below with matplotlib? If not, would it be difficult to add support for such plots in the mplot3d backend?

![slice](http://www.dartmouth.edu/~rc/classes/visit/three_slice.gif)

I know that such plots can be created with VTK but VTK is still limited to python 2 :-1:

**Comment by petehuang** [comment]
Seems like we've resolved this @WeatherGod?

**Comment by thisch** [comment]
The last time I tested it, it did not work satisfactorily AFAIR.

**Comment by WeatherGod** [comment]
Have you tried glumpy, which I originally suggested? It is possible to
create a function that could possibly do all of this for you, but it will
still suffer from possible rendering artifacts at certain viewing angles,
and it would still be a hack because it would use contourf() instead of
imshow(). I would imagine glumpy would be much better suited for this need.

**Comment by louity** [comment]
As explained in [this stackoverflow answer](https://stackoverflow.com/questions/39144482/matplotlib-plot-surface-transparency-artefact?answertab=oldest#tab-top), matplotlib won't be able to make the 3 slices plots on the same figure "until OpenGL support is added to all of the backends".

Indeed, occlusions of the different slices will not be rendered correctly, and you will get this kind of result (I plot the 3d function (x,y,z) -> x**2 + y**2 + z**2 over the [-1:1]^3) : 
![slice_plot_xyz](https://user-images.githubusercontent.com/14196488/28123613-ab45a5e8-6721-11e7-8a6b-5c622c2f23e6.png)

However, you can plot each slice on a separate figure : 
![slice_plot_x](https://user-images.githubusercontent.com/14196488/28123680-dfb2709a-6721-11e7-8b40-f7e960fb8fca.png)
![slice_plot_y](https://user-images.githubusercontent.com/14196488/28123684-e365249e-6721-11e7-9fad-033fbea618b4.png)
![slice_plot_z](https://user-images.githubusercontent.com/14196488/28123689-e6e61506-6721-11e7-9da7-f48fe0855646.png)

or plot slices that do not occlude each other from the point of view you are looking from.

code : 
```
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

def plot_3D_array_slices(array):
    min_val = array.min()
    max_val = array.max()
    n_x, n_y, n_z = array.shape
    colormap = plt.cm.YlOrRd

    x_cut = array[n_x//2,:,:]
    Y, Z = np.mgrid[0:n_y, 0:n_z]
    X = n_x//2 * np.ones((n_y, n_z))
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(X, Y, Z, rstride=1, cstride=1, facecolors=colormap((x_cut-min_val)/(max_val-min_val)), shade=False)
    ax.set_title("x slice")

    y_cut = array[:,n_y//2,:]
    X, Z = np.mgrid[0:n_x, 0:n_z]
    Y = n_y//2 * np.ones((n_x, n_z))
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(X, Y, Z, rstride=1, cstride=1, facecolors=colormap((y_cut-min_val)/(max_val-min_val)), shade=False)
    ax.set_title("y slice")

    z_cut = array[:,:,n_z//2]
    X, Y = np.mgrid[0:n_x, 0:n_y]
    Z = n_z//2 * np.ones((n_x, n_y))
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(X, Y, Z, rstride=1, cstride=1, facecolors=colormap((z_cut-min_val)/(max_val-min_val)), shade=False)
    ax.set_title("z slice")

    plt.show()


n_pts = 100
r_square = (np.mgrid[-1:1:1j*n_pts, -1:1:1j*n_pts, -1:1:1j*n_pts]**2).sum(0)
plot_3D_array_slices(r_square)
```

**Comment by louity** [comment]
You might actually overcome this issue using matplotlib [Poly3DCollection](https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.art3d.Poly3DCollection.html)
 [example](https://stackoverflow.com/questions/18897786/transparency-for-poly3dcollection-plot-in-matplotlib), but as you can read in the doc :"this class (Poly3DCollection) does a bit of magic with the _facecolors and _edgecolors properties."... Let me know if you manage to do it :-).

**Comment by louity** [comment]
There is an [example of solutio](http://nbviewer.jupyter.org/github/empet/Plotly-plots/blob/master/Plotly-Slice-in-volumetric-data.ipynb) using plotly.

**Comment by tacaswell** [comment]
Also see https://stackoverflow.com/questions/14824893/how-to-draw-intersecting-planes/14825951#14825951 .  Manually chopping your slices up can also be made to work.

**Comment by GeekMe93** [comment]
Is it type of plot still possible? As of matplotlib v3, it seems there no proper way to handle this

**Comment by gc13141112** [comment]
3D don't support zdir = 'x' ????  [https://gc13141112.github.io/test/test.png](url)

**Comment by gc13141112** [comment]
[3d plot don't support zdir = 'x'? and this has an error](https://gc13141112.github.io/test/test.png)

**Comment by WeatherGod** [comment]
It should work, but without a code example to demonstrate the problem, I
can't help you further.

**Comment by gc13141112** [comment]
[a. This is python code](https://gc13141112.github.io/test/python_3d.py)
[b. Data](https://gc13141112.github.io/test/MERRA2_100.instM_3d_asm_Np.198001.SUB.nc)
[c. shapefile](https://github.com/gc13141112/gc13141112.github.io/tree/master/test)

**Comment by gc13141112** [comment]
Thank you for reply!

**Comment by gc13141112** [comment]
import xarray as xr
from netCDF4 import Dataset
import cmaps
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.basemap import Basemap
from mpl_toolkits.mplot3d import axes3d
from matplotlib.collections import PolyCollection
from matplotlib import cm
import numpy as np
i = 225
j = 30

**Comment by gc13141112** [comment]
import xarray as xr
from netCDF4 import Dataset
import cmaps
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.basemap import Basemap
from mpl_toolkits.mplot3d import axes3d
from matplotlib.collections import PolyCollection
from matplotlib import cm
import numpy as np
i = 225
j = 30
nc_file = 'MERRA2_100.instM_3d_asm_Np.198001.SUB.nc'
mod = xr.open_dataset(xr.backends.NetCDF4DataStore(Dataset(nc_file)))
RH = mod.data_vars['RH'].values[0, :, :, :] * 100
lev1 = (1013.25 - mod.coords['lev'].values) * 9
lev2 = lev1 / 1000
lon = mod.coords['lon'].values
lat = mod.coords['lat'].values
fig = plt.figure()

ax = fig.gca(projection='3d',adjustable='box')
ax.set_aspect('equal')
map = Basemap(llcrnrlat=15, llcrnrlon=70, urcrnrlat=55, urcrnrlon=140,ax = ax)
ax.set_zlim(0,12)
ax.set_xlim(70,140)
ax.set_ylim(15,55)
ax.set_zticks([0,6,12])
lont,latt = np.meshgrid(lon,lat)
shp = map.readshapefile('bou2_4p', 'bou2_4p.shp', linewidth=0.15,color='grey')
ax.add_collection3d(shp[4],zs=lev2[0])
cs = ax.contourf(lont,latt,RH[0,:,:],np.arange(0,100,1),zdir='z',alpha = 1,offset = lev2[0],cmap = cmaps.NCV_jet)

shp = map.readshapefile('bou2_4p', 'bou2_4p.shp', linewidth=0.15,color='grey')
ax.add_collection3d(shp[4],zs=lev2[21])
ax.contourf(lont,latt,RH[21,:,:],np.arange(0,100,1),zdir='z',offset=lev2[21],cmap = cmaps.NCV_jet,alpha=1)

x,y = np.meshgrid(lat,lev2)
ax.contourf(x,y,RH[:,:,50],levels = np.arange(0,100,1),cmap = cmaps.NCV_jet,zdir='x',offset=lon[50],alpha = 0.8)
ax.set_xlabel('Longitude (degrees)',fontsize=5)
ax.set_ylabel('Latitude (degrees)',fontsize=5)
ax.set_zlabel('Altitude (km)',fontsize=5)
plt.savefig('test.png',dpi = 200,bbox_inches = 'tight')
plt.close()

**Comment by gc13141112** [comment]
Please help me address this question.

发自我的 iPhone

> 在 2019年7月30日，21:57，Benjamin Root <notifications@github.com> 写道：
> 
> It should work, but without a code example to demonstrate the problem, I
> can't help you further.
>

**Comment by dmeoli** [comment]
Is this not yet possible? I need to cut my convex function in the figure (left) with a plane along the z-axis in 0. 

![image](https://user-images.githubusercontent.com/21286237/82159779-12b8c400-9891-11ea-9dd0-30fc7f6d2f09.png)

**Comment by KrisSatie** [comment]
Is it type of plot still possible? As of matplotlib v3, it seems there no proper way to handle this

**Comment by dongjiaping** [comment]
yes, we need a better way to solve  make 3 slices plots on the same figure.

**Comment by scottshambaugh** [comment]
Relabeling the reason for closure as "can't fix", as this is a renderer issue. However, plotting slices can be done by plotting each quadrant of the slice around the intersection separately. Here's an example (which could probably be made more compact but demonstrates the concept):

```python
import matplotlib.pyplot as plt
import numpy as np

def plot_quadrants(ax, slice_data, fixed_coord, coord_val, colormap, shape, min_val, max_val):
    half_shape = (shape[1] // 2, shape[2] // 2)
    quadrants = [
        slice_data[:half_shape[0], :half_shape[1]],
        slice_data[:half_shape[0], half_shape[1]:],
        slice_data[half_shape[0]:, :half_shape[1]],
        slice_data[half_shape[0]:, half_shape[1]:]
    ]
    
    for i, quad in enumerate(quadrants):
        if fixed_coord == 'x':
            Y, Z = np.mgrid[0:half_shape[0], 0:half_shape[1]]
            X = coord_val * np.ones_like(Y)
            Y_offset = (i // 2) * half_shape[0]
            Z_offset = (i % 2) * half_shape[1]
            ax.plot_surface(X, Y + Y_offset, Z + Z_offset, rstride=1, cstride=1, facecolors=colormap((quad-min_val)/(max_val-min_val)), shade=False)
        elif fixed_coord == 'y':
            X, Z = np.mgrid[0:half_shape[0], 0:half_shape[1]]
            Y = coord_val * np.ones_like(X)
            X_offset = (i // 2) * half_shape[0]
            Z_offset = (i % 2) * half_shape[1]
            ax.plot_surface(X + X_offset, Y, Z + Z_offset, rstride=1, cstride=1, facecolors=colormap((quad-min_val)/(max_val-min_val)), shade=False)
        elif fixed_coord == 'z':
            X, Y = np.mgrid[0:half_shape[0], 0:half_shape[1]]
            Z = coord_val * np.ones_like(X)
            X_offset = (i // 2) * half_shape[0]
            Y_offset = (i % 2) * half_shape[1]
            ax.plot_surface(X + X_offset, Y + Y_offset, Z, rstride=1, cstride=1, facecolors=colormap((quad-min_val)/(max_val-min_val)), shade=False)

def plot_3D_array_slices(array):
    colormap = plt.cm.YlOrRd
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    min_val = array.min()
    max_val = array.max()
    
    x_slice = array[array.shape[0]//2, :, :]
    y_slice = array[:, array.shape[1]//2, :]
    z_slice = array[:, :, array.shape[2]//2]
    
    plot_quadrants(ax, x_slice, 'x', array.shape[0]//2, colormap, array.shape, min_val, max_val)
    plot_quadrants(ax, y_slice, 'y', array.shape[1]//2, colormap, array.shape, min_val, max_val)
    plot_quadrants(ax, z_slice, 'z', array.shape[2]//2, colormap, array.shape, min_val, max_val)
    
    plt.show()

n_pts = 100
r_square = (np.mgrid[-1:1:1j*n_pts, -1:1:1j*n_pts, -1:1:1j*n_pts]**2).sum(0)
plot_3D_array_slices(r_square)
```

![image](https://github.com/matplotlib/matplotlib/assets/14363975/82115ea3-2b78-41a8-a948-bce0812ccb03)

**Comment by timhoffm** [comment]
Thanks @scottshambaugh! I think this would be good as a gallery example. There were some indices mixed up (noticed when using different shapes for the dimensions). Below is a corrected version, which also simplifies the `plot_quadrants` interface:

```
import matplotlib.pyplot as plt
import numpy as np


def plot_quadrants(ax, array, fixed_coord, cmap):
    """For a given 3d *array* plot a plane with *fixed_coord*, using four individual quadrants."""
    nx, ny, nz = array.shape
    index = {
        'x': (nx//2, slice(None), slice(None)),
        'y': (slice(None), ny//2, slice(None)),
        'z': (slice(None), slice(None), nz//2),
    }[fixed_coord]
    plane_data = array[index]

    n0, n1 = plane_data.shape
    quadrants = [
        plane_data[:n0//2, :n1//2],
        plane_data[:n0//2, n1//2:],
        plane_data[n0//2:, :n1//2],
        plane_data[n0//2:, n1//2:]
    ]

    min_val = array.min()
    max_val = array.max()
    
    cmap = plt.get_cmap(cmap)
    
    for i, quadrant in enumerate(quadrants):
        facecolors = cmap((quadrant - min_val) / (max_val-min_val))
        if fixed_coord == 'x':
            Y, Z = np.mgrid[0:ny//2, 0:nz//2]
            X = nx//2 * np.ones_like(Y)
            Y_offset = (i // 2) * ny//2
            Z_offset = (i % 2) * nz//2
            ax.plot_surface(X, Y + Y_offset, Z + Z_offset, rstride=1, cstride=1, facecolors=facecolors, shade=False)
        elif fixed_coord == 'y':
            X, Z = np.mgrid[0:nx//2, 0:nz//2]
            Y = ny//2 * np.ones_like(X)
            X_offset = (i // 2) * nx//2
            Z_offset = (i % 2) * nz//2
            ax.plot_surface(X + X_offset, Y, Z + Z_offset, rstride=1, cstride=1, facecolors=facecolors, shade=False)
        elif fixed_coord == 'z':
            X, Y = np.mgrid[0:nx//2, 0:ny//2]
            Z = nz//2 * np.ones_like(X)
            X_offset = (i // 2) * nx//2
            Y_offset = (i % 2) * ny//2
            ax.plot_surface(X + X_offset, Y + Y_offset, Z, rstride=1, cstride=1, facecolors=facecolors, shade=False)


def figure_3D_array_slices(array, cmap=None):
    """Plot a 3d array using three intersecting centered planes."""
    fig = plt.figure()
    ax = fig.add_subplot(projection='3d')
    ax.set_box_aspect(array.shape)
    plot_quadrants(ax, array, 'x', cmap=cmap)
    plot_quadrants(ax, array, 'y', cmap=cmap)
    plot_quadrants(ax, array, 'z', cmap=cmap)
    return fig, ax


nx, ny, nz = 70, 100, 50
r_square = (np.mgrid[-1:1:1j*nx, -1:1:1j*ny, -1:1:1j*nz]**2).sum(0)

figure_3D_array_slices(r_square, cmap='viridis_r')
plt.show()
```
![grafik](https://github.com/matplotlib/matplotlib/assets/2836374/09310bdd-35b6-4587-b2bf-f0046d2f0b16)

**Comment by scottshambaugh** [comment]
That is cleaner, full disclosure I had chatgpt do my example so I'm not surprised it switched indexing. Agreed it'd make a nice gallery example, I can whip that up.
