### ISSUE TITLE
Please fix pip install, so that plt.show() etc works correctly

### ISSUE THREAD

**Issue by hughperkins** [matplotlib/matplotlib#3920]
Please fix pip install, so that plt.show() etc work correctly.

What I do:

- on ubuntu 14.04
- virtualenv ~/env
- source ~/env/bin/activate
- pip install numpy
- pip install matplotlib
- python
- import matplotlib.pyplot as plt
- plt.scatter([3,2,5],[3,4,2])
- plt.show()

What I expect to happen: plot should show

What actually happens: nothing

Other people with similar issue: see this stackoverflow question: http://stackoverflow.com/questions/7534453/matplotlib-does-not-show-my-drawings-although-i-call-pyplot-show

**Comment by danielotieno** [comment]
@WeatherGod  Thank you very much for your helpful comment.
