### ISSUE TITLE
Moving the ticks to the top or to the right resets tick format

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#3921]
Moving the ticks to the top or to the right resets tick formatting (e.g., font size, rotation).

``` python
xticks(range(5), rotation=90, size='xx-large')
gca().xaxis.tick_top()

yticks(range(5), rotation=90, size='xx-large')
gca().yaxis.tick_right()
```

Hence, the following two segments give different results:

``` python
xticks(range(5), rotation=90, size='xx-large')
gca().xaxis.tick_top() # not rotated 
```

and

``` python
gca().xaxis.tick_top()
xticks(range(5), rotation=90, size='xx-large') # rotated and xx-large font size
```

matplotlib version 1.4.2

**Comment by petehuang** [comment]
Confirming this still exists in 1.5.3 (along with evidence from #7020)

@tacaswell is this still in progress? Any guidance you'd give for other people trying to think about this problem?

**Comment by exowanderer** [comment]
Confirming that still exists in `matplotlib==2.2.3`. 

Is there at last a work around where we can change manual settings?
