### ISSUE TITLE
Feature request: place axes relative to other axes, with automatic updating

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#3926]
Matplotlib has well documented methods of how to place multiple sets of axes in a figure window, but it appears there isn't a way to define the position of one set of axes relative to the position of another set of axes, with automatic updating.  For example,

```
import matplotlib.pyplot as plt
import numpy as np    

#Define data
x1 = np.arange(0,10,0.01)
y1 = np.sqrt(x1)
x2 = x1
y2 = 1.0/2.0 * x2**2.0

#Generate vertically stacked plots
fig = plt.figure()
ax1 = fig.add_subplot(211)
ax1.plot(x1,y1)
ax2 = fig.add_subplot(212)
ax2.plot(x2,y2)
fig.savefig('nice_stacked_plots.png')
```

gives the following plot:
![nice_stacked_plots](https://cloud.githubusercontent.com/assets/4099759/5465757/4290ea30-855b-11e4-8db9-de7d96b71828.png)

This is all well and good, but when I change the size of the bottom axes

```
#Change the size of the bottom plot
bbox2 = ax2.get_position()
ax2.set_position([bbox2.x0, bbox2.y0, bbox2.width, bbox2.height * 1.25])
ax2.set_ylim(0,60)
fig.savefig('overlapping_stacked_plots.png')
```

the bottom axes overlap with the top axes

![overlapping_stacked_plots](https://cloud.githubusercontent.com/assets/4099759/5465768/6e19e558-855b-11e4-837d-273dc94dac1a.png)

I realize I could subsequently update the position of the top axes to remove the overlap, but I would like to just specify the top axes position relative to the bottom axes at the outset, and have things automatically update.

For example, in the annotate tutorial it is possible to place an annotation and then place a 2nd annotation at a specified offset from the 1st annotation using the OffsetFrom class. If the 1st annotation moves, then the 2nd annotation moves with it.  Can the `Axes` class be enhanced to do something similar?

**Comment by petehuang** [comment]
Constraint solver discussion mostly at #1109
