### ISSUE TITLE
fill_between() no longer works with border linewidth of 0

### ISSUE THREAD

**Issue by rabryan** [matplotlib/matplotlib#3929]
In 1.4.2, fill_between() does not always work when passing in lw=0 (to remove the border from the fill).

To reproduce, edit examples/pylab_examples/fill_between_demo.py and add argument "lw=0" in the first fill_between() call.  Run the demo and notice how the fill no longer appears (in previous matplotlib versions it would appear -- but with no border).

**Comment by atpage** [comment]
This is broken for me as well.  fill_between() with linewidth=0 was working in 1.4.0, but now in 1.4.2 it results in not plotting anything.  Even trying to add a legend says that there were no labeled objects found.  When I run your example, ax3 shows only the dashed line.

**Comment by mdboom** [comment]
This has been fixed in 1.4.3

**Comment by atpage** [comment]
Great, thanks.

**Comment by nebulaekg** [comment]
Great!
