### ISSUE TITLE
Missing Events in NbAgg Backend

### ISSUE THREAD

**Issue by blink1073** [matplotlib/matplotlib#3963]
Perhaps I am missing something, but it appears that some events are not implement for the `nbagg` backend?  Using the script below, I have seen the following work: `motion_notify_event, 
axes_enter_event, button_press_event`.  The following have not worked: `figure_enter_event, 
resize_event, key_press_event, scroll_event`.  The only one I'm *really* missing is `key_press_event`.

```python
import matplotlib
matplotlib.use('nbagg')
from matplotlib import pyplot as plt
plt.plot(range(3))
evt = None
def on_event(event):
    global evt
    evt = event
plt.gcf().canvas.mpl_connect('button_press_event', on_event)
plt.show()
```

I then check the value of `evt` in another cell to make sure it is getting updated.  I am using matplotlib ab549acc3a546c03b2fce1a5a156df4c2a60d6cd and IPython 2.3.1.

**Comment by blink1073** [comment]
I added a `console.log` print [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/mpl.js#L112), and the function is getting called for keyboard events when using the `webagg` backend but not the `nbagg` backend.  I tried the same [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/mpl.js#L121) and it is called by both backends.

**Comment by blink1073** [comment]
Just to pile on, the following picker demo did not work either:

```python
import numpy as np
x, y, c, s = np.random.rand(4, 100)
ind = 0

def onpick3(event):
    global ind
    ind = event.ind
    
fig, ax = plt.subplots()
col = ax.scatter(x, y, 100*s, c, picker=True)
fig.canvas.mpl_connect('pick_event', onpick3)
plt.show()
```

**Comment by tacaswell** [comment]
Your going to make me learn javascript aren't you .....

**Comment by blink1073** [comment]
I'm with you brother, I had resisted until this week...

**Comment by blink1073** [comment]
I think somehow the IPython `KeyboardManager` needs to be prevented from stealing all the events for the document.

**Comment by blink1073** [comment]
Its in `IPython/html/static/notebook/js/keyboardmanager.js`

**Comment by tacaswell** [comment]
Ah, I was trying to figure out what was different between webagg/nbagg that was eating keyboard events.  It makes a good deal of sense that IPython is what is eating the keystrokes....

Presumably they have a way of getting around this when entering code into cells.

**Comment by blink1073** [comment]
Yes and maybe we should ask the the IPython devs about scroll events since they seem to eat those as well.

**Comment by tacaswell** [comment]
@minrk Any advice?

The problem seems to be that the notebook keyboard handler is snarfing all of the keystrokes before they get to the `<div>` tag that mpl has `keydown` event listeners on.

**Comment by tacaswell** [comment]
attn @pelson

**Comment by minrk** [comment]
To avoid IPython handling keyboard events on a particular element, you will want to call

```javascript
IPython.notebook.keyboard_manager.register_events($element);
```

Generally, you would call this once on your outermost div when you create it.

**Comment by pelson** [comment]
Thanks @minrk - that is the kind of knowledge that would take a good while to figure out. @blink1073 - how do you want to proceed? Do you want to take a look at this?

**Comment by eyurtsev** [comment]
Not related to the fix. But if you guys are modifying mpl.js it won't hurt to fix a typo in line $43.

```
- this.focus_on_mousover = false;
+ this.focus_on_mouseover = false;
```

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/mpl.js#L43

**Comment by blink1073** [comment]
I'll give it a shot.

**Comment by blink1073** [comment]
I fear I may be out of my depth.  Here's what I tried (note that the `keyboard_manager` has moved between IPython 2.3 and 3.0):

```diff
diff --git a/lib/matplotlib/backends/web_backend/nbagg_mpl.js b/lib/matplotlib/backends/web_backend/nbagg_mpl.js
index 71c52f9..3dd7844 100644
--- a/lib/matplotlib/backends/web_backend/nbagg_mpl.js
+++ b/lib/matplotlib/backends/web_backend/nbagg_mpl.js
@@ -49,6 +49,7 @@ mpl.mpl_figure_comm = function(comm, msg) {
         return false;
     });
 
+    IPython.keyboard_manager.register_events($(fig.root));
 };
 
 mpl.figure.prototype.handle_close = function(fig, msg) {
```

Keyboard events are still getting eaten.  I tried a few syntax variations on `fig.root`, but I'm just stabbing in the dark.

**Comment by tacaswell** [comment]
@blink1073 I am also whacking at this (but keep getting side tracked).

**Comment by tacaswell** [comment]
@minrk The problem seems to be that the relevant are never getting focus which I think might be a problem on our end.

**Comment by tacaswell** [comment]
Ha! I have it working, PR on the way.

**Comment by minrk** [comment]
> The problem seems to be that the relevant are never getting focus 

Ah, yes. focus is a constant source of headaches for us.

**Comment by blink1073** [comment]
Update:  the picker is working (in `master`), with this demo:

```python
import matplotlib
import itertools
import numpy as np
matplotlib.use('nbagg')
import matplotlib.pyplot as plt
plt.close('all')
fig, ax = plt.subplots()
x = np.linspace(0,10,100)
y = np.sin(x)
ln, = ax.plot(x,y, 'o', picker=5)
evt = []
colors = iter(itertools.cycle(['r', 'g', 'b', 'k', 'c']))
def on_event(event):
    evt.append(event)
    ln.set_color(next(colors))
    fig.canvas.draw()
    fig.canvas.draw_idle()
fig.canvas.mpl_connect('key_press_event', on_event)
fig.canvas.mpl_connect('pick_event', on_event)
plt.show()
```

**Comment by pelson** [comment]
Woo. Thanks for working on this @blink1073 & @tacaswell. We should really get around to adding nbagg to the %matplotlib% magic in IPython.

**Comment by tacaswell** [comment]
The magic has been set up on their side already

**Comment by blink1073** [comment]
This isn't technically closed until #3968 is merged.

**Comment by tacaswell** [comment]
It probably got auto-magic closed via one of my commit messages.

**Comment by blink1073** [comment]
I think it was from the first line in your PR description.

**Comment by tacaswell** [comment]
Both are now merged and backported.

**Comment by tacaswell** [comment]
And the UAT all passes on the cherry-picked 1.4.x branch, hurray!

**Comment by blink1073** [comment]
Well that what easy, it only took two us learning a new language.  :smile:

**Comment by pelson** [comment]
> Well that what easy, it only took two us learning a new language.

And tripling the nbagg backend bus factor!
