### ISSUE TITLE
Zooming on images doesn't work properly (anymore)

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#3977]
Zooming on matrices and images doesn't work properly. The x axis coordinates are not selected properly.

To reproduce::

  from matplotlib import cbook
  import matplotlib.pyplot as plt

  file =  cbook.get_sample_data("lena.png")
  image = plt.imread(image)
  plt.imshow(image)

Then zoom in around the top left corner: the botton left corner is displayed.

**Comment by tacaswell** [comment]
Is this on master or 1.4.x?

**Comment by NelleV** [comment]
master, with tkagg backend.

**Comment by tacaswell** [comment]
confirm this on master with qtagg. 

Panning also moves the wrong direction.

If you un-invert the y-axis it behaves correctly again.

attn @mdboom I am guessing this is related to the cxx refactor?

**Comment by WeatherGod** [comment]
I wonder if this might be related to artist picking failures I am seeing in
master as well?

**Comment by mdboom** [comment]
Confirmed here, too.

**Comment by WeatherGod** [comment]
Do we have any zoom tests, and more importantly, do the zoom test not zoom
to the center?

**Comment by mdboom** [comment]
@WeatherGod: I'll add an image zoom test to #3978 (haven't yet).

**Comment by WeatherGod** [comment]
Note that panning was also pointed out to be in the wrong direction

**Comment by mdboom** [comment]
@WeatherGod: Yes, in this case panning and zooming were triggering the same bug when the image is clipped in the y dimension.
