### ISSUE TITLE
zoom in wx with retnia behaves badly

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3980]
See screen shots at https://github.com/matplotlib/matplotlib/pull/3905#issuecomment-66932401

**Comment by tacaswell** [comment]
@briantoby  @RobinD42  I created this issue to track the new retnia-related issues in wx discovered as part of #3905.

**Comment by briantoby** [comment]
I have created a fix (#5631) for this problem that works for me, but has only been tested under very limited circumstances. Note that the original file was taken from the Canopy dist. which seems to have an extra self.canvas.draw(). I am not sure how that got there.

**Comment by jenshnielsen** [comment]
closed by #5631
