### ISSUE TITLE
unable to pickle.load an AxesSubplot object

### ISSUE THREAD

**Issue by sektoid0** [matplotlib/matplotlib#3986]
Python 2.7.9 :: Anaconda 2.1.0 (64-bit)
Matplotlib 1.4.0

On an example code from http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object getting a following exception on pickle load.

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-2-37de7fcd9451> in <module>()
          2 import pickle
          3 
    ----> 4 ax = pickle.load(file('myplot.pickle', 'rb'))
          5 plt.show()    

    /home/anaconda/envs/py27/lib/python2.7/pickle.pyc in load(file)
       1376 
       1377 def load(file):
    -> 1378     return Unpickler(file).load()
       1379 
       1380 def loads(str):    

    /home/anaconda/envs/py27/lib/python2.7/pickle.pyc in load(self)
        856             while 1:
        857                 key = read(1)
    --> 858                 dispatch[key](self)
        859         except _Stop, stopinst:
        860             return stopinst.value    

    /home/anaconda/envs/py27/lib/python2.7/pickle.pyc in load_build(self)
       1215         setstate = getattr(inst, "__setstate__", None)
       1216         if setstate:
    -> 1217             setstate(state)
       1218             return
       1219         slotstate = None    

    /home/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/figure.pyc in __setstate__(self, state)
       1343             allnums = plt.get_fignums()
       1344             num = max(allnums) + 1 if allnums else 1
    -> 1345             mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
       1346 
       1347             # XXX The following is a copy and paste from pyplot. Consider    

    AttributeError: 'module' object has no attribute 'new_figure_manager_given_figure'

**Comment by pelson** [comment]
Are you loading a pickle file created with the same version of matplotlib? Can you provide the code to reproduce. Thanks.

**Comment by sektoid0** [comment]
Yes. The same version of matplotlib. The code is exactly the one listed here:
http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object

**Comment by blink1073** [comment]
[We can pickle that](https://www.youtube.com/watch?v=yYey8ntlK_E)

**Comment by efiring** [comment]
I can't reproduce the problem; with matplotlib 1.4.0, Anaconda 2.1.0, on OSX, if I cut and paste the code on that page as instructed, it works perfectly.

**Comment by prinsherbert** [comment]
I solved this issue in Jupyter notebooks, not Anaconda, using

    %matplotlib agg
    
    with open('file.p3', 'rb') as f:
        model = pickle.load(f)
    
    %matplotlib inline

**Comment by QuLogic** [comment]
This bug report doesn't involve notebooks. It's also 4 years old and closed. Your workaround may be helpful to you, but it's not really relevant here.

**Comment by prinsherbert** [comment]
Actually, the `%matplotlib agg` translates in to python code, so I could imagine it could be useful for someone doing plain python. Notebooks are just python in the end. I also don't think ipython vs. python related, I think it's related to the backend of matplotlib. So my suggestion was to temporarily switch backends.

Moreover, the bug was closed because it couldn't be reproduced. So anyone who Google's this error and gets to this page, now at least has a lead.
