### ISSUE TITLE
Plot markers are not drawn when no edge is requested

### ISSUE THREAD

**Issue by rwirth** [matplotlib/matplotlib#3990]
Applies to version 1.4.2

When using one of the GUI backends (tested with Tk and Qt using IPython) plot markers are only drawn if `markeredgecolor` is not set to 'none' and `markeredgewidth` is nonzero. So

        plot(linspace(0,2), linspace(0,2)**2, marker='o', markeredgecolor='blue', 
            markeredgewidth=0.01, markerfacecolor='blue')

draws plot markers while

        plot(linspace(0,2), linspace(0,2)**2, marker='o', markeredgecolor='blue',
            markeredgewidth=0, markerfacecolor='blue')

or

        plot(linspace(0,2), linspace(0,2)**2, marker='o', markeredgecolor='none', 
            markerfacecolor='blue')

don't.

Associated with this issue seems to be that the Axes method `fill_between` doesn’t draw anything if `linewidth` is set to zero. Could it be that any filled paths without outline are not drawn?

Saving the figure to PDF via the GUI is _not_ affected by this issue, saving to PNG is.

**Comment by WeatherGod** [comment]
I think this is already fixed? Could you try checking out the v1.4.x branch
and seeing if the problem is solved for you?

**Comment by tacaswell** [comment]
This looks like a duplicate to me.

You can either upgrade to 1.4.x or downgrade to 1.4.0.  There should be a 1.4.3 around the end of the month.

**Comment by rwirth** [comment]
Whoops, didn't realize the search box only searches the open issues. The 1.4.x branch works for me. Thanks.

**Comment by tacaswell** [comment]
@rwirth No worries, thank you for the report!
