### ISSUE TITLE
Choose rcfile to use at runtime

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#3996]
I would love a command like:

`plt.use_rc_file("/path/to/matplotlibrc")`

to choose a specific rc file in a script.

**Comment by mdboom** [comment]
You can do:

```
from matplotlib import style
style.use("/path/to/matplotlibrc")
```

**Comment by MaxNoe** [comment]
Oh, thanks. Why is this not mentioned here: http://matplotlib.org/users/customizing.html

**Comment by tacaswell** [comment]
@MaxNoe Because that documentation has gotten behind the code.  If you could put in a PR to update it that would be great!
