### ISSUE TITLE
Qt5 Backend: dblclick is always False on 'mouse_release_event'

### ISSUE THREAD

**Issue by diogolr** [matplotlib/matplotlib#4001]
Simple as that... The `dblclick` flag is always `False` on  `mouse_release_event` because the `mouseDoubleClickEvent` only call `button_press_event`, as follow:

**`backend_qt5.py`**

``` python
def mouseDoubleClickEvent(self, event):
        x = event.pos().x()
        # flipy so y=0 is bottom of canvas
        y = self.figure.bbox.height - event.pos().y()
        button = self.buttond.get(event.button())
        if button is not None:
            FigureCanvasBase.button_press_event(self, x, y,
                                                button, dblclick=True)
        if DEBUG:
            print('button doubleclicked:', event.button())
```

Can we fix this with a `button_release_event` call, also?

**Comment by tacaswell** [comment]
Can you please put that in a pull request?  That is the easiest way to review the changes and makes sure you get credit for your work.

**Comment by petehuang** [comment]
Code is largely the same as OP, see here https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5.py#L271

@diogolr would you like to help us improve this functionality with a PR?

**Comment by tacaswell** [comment]
What is the use for a release event on a double click?  Looking at https://doc.qt.io/qt-4.8/qwidget.html#mouseDoubleClickEvent it looks like Qt does not have a notion of 'double click release'. As mpl does not have separate notion of double click events, we just tack the flag on.  

It also says that the widgets will get the standard button press and button release events in addition to the double click events.  Experimentally, this second click is converted to the double click by Qt so we only see 2 press events (the first one + double-click) and 2 release events (the second of which is delayed until the mouse is actually released (ex press-release-press-wait-release)).

I think mpl should take the same position as Qt, it is the responsibility of user code to keep track of if a release event came from the second click of a double click.

If we do make this change, it should be done across all of the GUI backends (not just Qt).


----

```python
import datetime
import matplotlib.pyplot as plt
plt.ion()


def cb1(event):
    print('p', datetime.datetime.now().isoformat(), event.dblclick)


def cb2(event):
    print('r', datetime.datetime.now().isoformat(), event.dblclick)


fig, ax = plt.subplots()

fig.canvas.mpl_connect('button_press_event', cb1)
fig.canvas.mpl_connect('button_release_event', cb2)

```

```
p 2017-01-08T16:04:54.745000 False
r 2017-01-08T16:04:55.135865 False

p 2017-01-08T16:04:57.704899 False
r 2017-01-08T16:04:57.752425 False
p 2017-01-08T16:04:57.840663 True
r 2017-01-08T16:04:57.972945 False

p 2017-01-08T16:05:01.531077 False
r 2017-01-08T16:05:01.621503 False
p 2017-01-08T16:05:01.687119 False
r 2017-01-08T16:05:05.140481 False

p 2017-01-08T16:05:06.040959 False
r 2017-01-08T16:05:06.109972 False
p 2017-01-08T16:05:06.186492 True
r 2017-01-08T16:05:08.067290 False

```

**Comment by holy-motors** [comment]
Can you confirm this is still an issue?

**Comment by timhoffm** [comment]
`FigureCanvasBase.button_relase_event` does not have a notion of double click. The same is True for Qt.

In Qt a double click produces the event sequence:
~~~
press
release
doubleClick
release
~~~

The same is true for matplotlib; with the only difference, that Qt has it's own event type "doubleClick" but matplotlib only uses a flag in the `MouseEvent`. The `dblclick` flag is unused for events other than press.
