### ISSUE TITLE
Add a Figure Options Dialog to Web Backends?

### ISSUE THREAD

**Issue by blink1073** [matplotlib/matplotlib#4011]
This would emulate the Dialog used for Qt backend using the following method:
- Create a `figureoptions.json` file and use [jquery.dform](https://github.com/daffl/jquery.dform) (MIT license) to create the form.
- Clicking the tool calls the Python layer, which in turn calls a JS function with a snapshot object with all of the IDs and their current values.
- Populate the Form by looping through the object and using `$(#my_id).val(my_val)` and display it as a modal Dialog.
- When the form is validated, slurp up all of the values using `$(#my_id).val()` and send to the Python layer.
- Note there would be a middle step of bringing up an Axes Selection Dialog if there is more than one axes.

I'd like to take this on as a learning experience if there is interest.  This should work the same on both web backends with only an icon difference (I hope).  I didn't want to try the Subplots Dialog because 1) I don't find it that useful and 2) It would have to be interactive.

**Comment by tacaswell** [comment]
Sounds awesome to me.

When working on `figureoptions.json` it is probably worth looking at the object model that Bokeh or plotly uses.  If their model are too far from what seems natural for mpl don't worry about it, having a json rep on our end is still a step in the right direction.  There is a long-running and very slow moving effort to make everything talk to everything.

attn @pelson

**Comment by blink1073** [comment]
The structure of figureoptions.json is dictated by jquery.dform, but can be munges quite nicely on the Python end as well. :smile:

**Comment by blink1073** [comment]
It looks like Bokeh and IPython are both using Backbone models:
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/ui_events.coffee#L11
https://github.com/ipython/ipython-components/tree/master/backbone

**Comment by blink1073** [comment]
But I see `jquery.dform` as an analog to [formlayout](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_editor/formlayout.py) and a completely separate issue.

**Comment by petehuang** [comment]
@blink1073 you mentioned that you might want to engage on this - could you provide an update on where you are and what help you might need? Just so we can keep this fresh. Thanks!

**Comment by blink1073** [comment]
Hi @petehuang, thank you the nudge.  I am not planning to implement this myself.  Feel free to close this issue if there is no interested implementer.

**Comment by QuLogic** [comment]
> Create a `figureoptions.json` file and use [jquery.dform](https://github.com/daffl/jquery.dform) (MIT license) to create the form.

As a note, we no longer depend on jQuery, and the suggested form library is now archived. I'm sure that there probably exists a newer library for doing forms though. Possibly one might be available from ipywidgets or some Jupyter lab stuff.
