### ISSUE TITLE
Document default key-bindings

### ISSUE THREAD

**Issue by kogelnik** [matplotlib/matplotlib#4020]
matplotlib 1.4.2 
TkAgg 8.5
python 2.7.3
OSX 10.8.5

After plotting a figure and using the interactive features, pressing certain number keys (2-9) disables the display of the x, y coordinates on the interactive navigation menu.  Pressing '1' restores this functionality.   This prevents the number keys from being used in key mappings and having the coordinates interactively updated.

Reproduce with:

```
import matplotlib.pyplot as plt

plt.plot([1,2,3,4])
plt.show()
```
- move the cursor to cause the x,y coordinates to display 
- press a number key and move the cursor ('2'-'9' turn off, '1' restores the coordinate display)

**Comment by WeatherGod** [comment]
IIRC, the numbered keys are a shortcut for whichever axes you want to be
active. If you only have a single axes display, then selecting "2" would
change the "focus" to a non-existent axes. Of course, this would be
incorrect behavior, but that is my theory of what is happening.

**Comment by kogelnik** [comment]
I haven't found any documentation on this.  matplotlibrc and plt.rcParams don't show any obvious mappings.  ('a' can also be used set all axes.)

Is there a way to disable/override this feature?

**Comment by WeatherGod** [comment]
Ah hah! I knew I came across something about this when researching my book.
In backend_bases.py for key_press_handler():

```
    elif (event.key.isdigit() and event.key != '0') or event.key in all:
        # keys in list 'all' enables all axes (default key 'a'),
        # otherwise if key is a number only enable this particular axes
        # if it was the axes, where the event was raised
        if not (event.key in all):
            n = int(event.key) - 1
        for i, a in enumerate(canvas.figure.get_axes()):
            # consider axes, in which the event was raised
            # FIXME: Why only this axes?
            if event.x is not None and event.y is not None \
                    and a.in_axes(event):
                if event.key in all:
                    a.set_navigate(True)
                else:
                    a.set_navigate(i == n)
```
Essentially, it sets which axes are "navigable". I have zero clue if this
is actually documented anywhere, though.

The way to disable the default keymap in matplotlib is:
```
            manager, canvas = figure.canvas.manager, figure.canvas
            canvas.mpl_disconnect(manager.key_press_handler_id)
```

**Comment by kogelnik** [comment]
Thanks!

I haven't seen it documented anywhere.  At the very least, it would seem that there should be a mention in the matplotrc section for keymap, even though this seems to utilize a different mechanism.

**Comment by tacaswell** [comment]
Changed the title to be more of an action item

**Comment by fariza** [comment]
Just as a side note.
In the example of MEP22 https://github.com/matplotlib/matplotlib/pull/3652 I added a tool (with a shortcut) to list all the shortcuts of interactive features.

**Comment by tacaswell** [comment]
https://matplotlib.org/users/navigation_toolbar.html <- this appears to be done.
