### ISSUE TITLE
control hatch linewidth and fill border linewidth separately

### ISSUE THREAD

**Issue by jkokorian** [matplotlib/matplotlib#4026]
It would be awesome if it were possible to control the linewidth of the hatch effect, for example in fill_between. It is now only possible to set the linewidth parameter, but that also gives the filled area a border, which can be undesired. Is it possible to allow for a dictionary to be passed to a "hatch_kwargs"  parameter, that allows you to set the linewidth, hatch-style and possibly other things?

In this stackoverflow post (http://stackoverflow.com/questions/11452743/manipulating-linewidth-for-hatching-in-matplotlib?rq=1), I found that the hatch linewidth is hardcoded in C++, so it should be relatively easy to make its value depend on some python input, wouldn't it?

**Comment by tacaswell** [comment]
@jkokorian Want to take a crack at add that feature?  This might not be the gentlest introduction to the library but might be fun!

The code for the hatch width for AGG is now in `src/_backend_agg.h` (as it is templated c++).  I _think_ that the way you would have to get the new information in would be to add it to the `graphicsContextBase`.  

This is also a change that would have to be made across all of the backends.

**Comment by jkokorian** [comment]
I will definitely take a crack, but chances are I will get hopelessly stuck. I'm a reasonably accomplished python and c# programmer, but I haven't got much c++ experience...

Like you said, it might be fun!

**Comment by jkokorian** [comment]
Mmm, I looked at it quickly but it might be slightly out of my depth. I will have a go anyway, but I might need some tutoring...

**Comment by mdboom** [comment]
As @tacaswell suggested, there's sort of two sides to this.  One is creating the API and storage to store the new value (hatch width) with the artist.  The other is updating all of the backends to obey it.  Most of the backends are in Python, but the Agg one will require a little C++.  I can help with the Agg stuff, but can't realistically find the time to tackle the whole thing.

**Comment by tacaswell** [comment]
@jkokorian Tutoring/mentoring new contributors in one of the roles of project maintainers.   We are all very time-bound so the more people working on the code the better :smiley:

**Comment by QuLogic** [comment]
I believe this is fixed by #6198.

**Comment by lzkelley** [comment]
Am I correct that there's still no way to set hatch-linewidths for an individual plot object?
