### ISSUE TITLE
Text going outside subplot with multiple axes

### ISSUE THREAD

**Issue by diogolr** [matplotlib/matplotlib#4027]
![image](https://cloud.githubusercontent.com/assets/4297658/5859596/31ce2612-a23a-11e4-8dcf-931594aaf075.png)

System:
* Windows 7
* Qt 5.4.0
* Python 3.4.2
* PyQt 5.4
* Matplotlib 1.4.2

Any idea?

What I'm doing...
  1. Configuring multiple axes with ``twiny``
  2. Configuring the axes color, ticks, patch.set_visible( False )...
  3. Plotting some stuff on the axes previously configured
  4. Putting some text on the first created axe
  5. Catching the scroll event and using ``event.step`` times a factor with ``set_ylim`` of the axes
  6. Redrawing the canvas

**Comment by tacaswell** [comment]
With out code, there is really nothing we can do to help you.   Can you put together a _minimal_ working example that shows the problem?  My guess is that you are not keeping your y-axis in sync or have turned clipping off on you text objects.

This question might be better suited from the user maling list as well.

**Comment by vgm64** [comment]
I happened to run into the same issue today. Python 2.7.8, Matplotlib 1.4.0, MacOS 10.9.5. MWE below.
```
from pylab import *
f, (ax1, ax2) = subplots(2, 1)
ax2.text(20, 150, "If this appears on the top subplot, something's amiss...")
ax2.scatter([20, 40], [20, 80])
show()
```
![image](https://cloud.githubusercontent.com/assets/1680851/6069792/24874756-ad3c-11e4-9eb9-f7117332b9a2.png)

**Comment by WeatherGod** [comment]
ok, so what you want is clipping? Could you try adding "clip_on=True" as an
argument to the ax2.text() call?

**Comment by vgm64** [comment]
You're quite right. That solves it. I included clip_on in my fontdict instead of as a kwarg when testing. Thanks.
```
from pylab import *
f, (ax1, ax2) = subplots(2, 1)
ax2.text(20, 150, "Using tools the way they were meant to be used.", clip_on=True)
ax2.scatter([20, 40], [20, 80])
show()
```

**Comment by WeatherGod** [comment]
That option needs to be better documented, I think. Glad that worked!

**Comment by diogolr** [comment]
The `clip_on` flag also works for me! Thank you very much.
