### ISSUE TITLE
Add 'sticky' flag for x/y constrained panning/zooming.

### ISSUE THREAD

**Issue by jason-s** [matplotlib/matplotlib#4028]
There doesn't seem to be any way to constrain x- or y- axis when panning/zooming in IPython interactive (%matplotlib nbagg) mode. Is there? If not, I'd like to request this feature.

Also it is helpful to somehow to set a default constraint when plotting the figure. In time series plots with linked axes, for example, I generally just want to allow x-axis (really t-axis) zooming and panning, and I want to leave the y-axis limits untouched. I don't want the default behavior to allow zooming and panning to affect the y-axis, I want the user to have to select something to allow it if they really want. 

(by the way %matplotlib nbagg is AWESOME!!!!)

**Comment by tacaswell** [comment]
Actually, this might be fixed in 1.4.x/master as holding down shift gives you this in the other backends and keyboard events now work in nbagg.  Let me test....

**Comment by tacaswell** [comment]
Sadly no.  It looks like the js layer supresses the shift-key events and the way that mouse + keyboard gets combined is that the canvas keeps track of what key is 'down' most recently.

cc @WeatherGod @blink1073 any interest?  I will probably poke at this later tonight as well.

**Comment by jason-s** [comment]
(not sure whether this is a matplotlib thing or an IPython thing)

IMHO holding down a key while panning and zooming is not really a great way to do this.

MATLAB has x-axis-constraint or y-axis-constraint as a "sticky" attribute of each plot (e.g. [see this video])(http://blogs.mathworks.com/videos/2006/11/27/linked-zoom-and-constrained-zoom-in-matlab/), and as much as I hate using MATLAB, I think their UI behavior makes more sense.

**Comment by WeatherGod** [comment]
I rather like the idea of a "sticky" constraint. The whole shift thing is
legacy, but it is thoroughly documented and I see no reason to get rid of
it. But having a programatic way to enable the constraint is a great idea!

**Comment by blink1073** [comment]
@tacaswell, there is an `event.shiftKey` for both mouse and key events.

**Comment by blink1073** [comment]
I checked it with a `console.log` for both cases.

**Comment by blink1073** [comment]
Also, with the `Qt` backend, key modifiers are passed along with the mouse events, but not so with the Web backends.  I'm keen on making a PR...

**Comment by tacaswell** [comment]
The problem is that the shift-state is tracked at the python layer so the ingest on the python side for mouse events does not take any keyboard related args and the js-side does not issue keyboard events for the modifier keys.

**Comment by tacaswell** [comment]
ok, now I am confused...

**Comment by blink1073** [comment]
Let me do an experiment and get back to you.

**Comment by blink1073** [comment]
Okay, two problems:
1. We are not handling `shift` [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/mpl.js#L468).
2. There is no `key_event` fired when you press just the modifier keys in the browser, therefore `FigureCanvasBase._key` is `None` for the mouse event.

**Comment by blink1073** [comment]
"Modifier keys trigger keydown (but not keypress)." http://stackoverflow.com/a/15583312

**Comment by tacaswell** [comment]
It is somewhat odd that we catch 'keypress' and 'keyrelease', but not 'keydown'

**Comment by tacaswell** [comment]
wait, even more confused...

```javascript
 canvas_div.keydown('key_press', canvas_keyboard_event);
 canvas_div.keydown('key_release', canvas_keyboard_event);
```

on 'keydown' events we trigger two events which pass a 'key_press' and a 'key_release' event (more-or-less simultaneously).  But, if you hold a key down it keeps repeating (and you get both the 'press' and the 'release'  for each repeat) in both ff and chrome.

It also looks like mpl only has a notion of 'key_press' and 'key_release', but no 'keydown'.

**Comment by blink1073** [comment]
Yes, I messed that up.  `keydown` is a `jquery` method.  A PR is coming that will make it all better.  :smile:

**Comment by tacaswell** [comment]
@fariza To keep piling stuff onto you, how hard would this be to fold into the event-based navigation?

**Comment by tacaswell** [comment]
@jason-s Changed the title to be the request for sticky bit.  Holding down x, y, or shift in nbagg should now behave like it does in the other interactive guis.

**Comment by fariza** [comment]
@tacaswell I think it's possible to put this in there. I have to check.

**Comment by petehuang** [comment]
This still looks open, PRs welcome

**Comment by LinqingZ** [comment]
Is this problem solved? I would like to know how to restrict the x and y to be in range of the graph like heatmap when panning and zooming. 

> class My_Axes(matplotlib.axes.Axes):
>     name = "My_Axes"
>     def drag_pan(self, button, key, x, y):
>         matplotlib.axes.Axes.drag_pan(self, button, 'x', x, y) # pretend key=='x'

Tried this could make the drag stick with the x axis but I am to restrict the y axis only on the graph range like histogram only be in the range of bins. 
https://stackoverflow.com/questions/16705452/matplotlib-forcing-pan-zoom-to-constrain-to-x-axes

**Comment by tacaswell** [comment]
In QtAgg and ipympl holding down `x`, or `y` does constrain panning to only that direction.

I am skeptical of adding state to the Axes to pre-emptively forbid panning in one of the directions.

I am less skeptical of adding state to the Axes adding limits on the limits that can be accessed by panning / zooming but I suspect there is going to be some fun edge cases to work through.  If that is what you want @LinqingZ can you please open a new issue and describe the use case you are try to get to more verbosely?

**Comment by LinqingZ** [comment]
Created issues on https://github.com/matplotlib/matplotlib/issues/26442

**Comment by LinqingZ** [comment]
> In QtAgg and ipympl holding down `x`, or `y` does constrain panning to only that direction.
> 
> I am skeptical of adding state to the Axes to pre-emptively forbid panning in one of the directions.
> 
> I am less skeptical of adding state to the Axes adding limits on the limits that can be accessed by panning / zooming but I suspect there is going to be some fun edge cases to work through. If that is what you want @LinqingZ can you please open a new issue and describe the use case you are try to get to more verbosely?

Created issues on https://github.com/matplotlib/matplotlib/issues/26442
