### ISSUE TITLE
Disable context menu for WebAgg backend?

### ISSUE THREAD

**Issue by blink1073** [matplotlib/matplotlib#4030]
The context menu is disabled for the `nbagg` backend [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_mpl.js#L55).  The context menu is not suppressed for the `webagg` backend.  This interferes with right click events on the figure and if the user selects "Save Image" from the browser context menu, they get just the `rubberband` layer.  
Okay with me moving the context menu disable to `mpl.js`?

**Comment by blink1073** [comment]
cc @pelson

**Comment by pelson** [comment]
Yeah, go for it. Also, could you check that a right click is triggering the appropriate mpl events rather than just completely disabling the right-mouse button?

**Comment by WeatherGod** [comment]
ATTN: @mdboom I remember discussing this back during development/testing of
webagg. You had reasons for it, but I can't remember.

**Comment by mdboom** [comment]
@WeatherGod: The issue I had before is that many browsers up until around 2 years ago made it rather difficult to disable the context menu and this use the right mouse button for something else, on the premise that it was a security flaw: a program could popup a fake context menu that then leads to something asking for a password or something.  I think the browsers have all resolved this by not doing anything security related in the context menu and thereby allowing javascript to disable it.  TL;DR: No longer an issue in current versions of Chrome/Firefox/Safari.
