### ISSUE TITLE
Hist Plot Should allow Normalized Values other than 1

### ISSUE THREAD

**Issue by fridiculous** [matplotlib/matplotlib#4037]
Often, we want to normalize with respect to a percentages.  It would be very convenient if the plot handled this functionality. 

While `hist()` currently accepts `1` or `True`  for the `normed` as a `bool` argument, it would be great if `normed` also accepted a `<float>`.  The returned counts would then be normalized to the float.

**Comment by tacaswell** [comment]
Basically the same as #4038, please put all discussion there.
