### ISSUE TITLE
tick_right() doesn't move scale factor

### ISSUE THREAD

**Issue by duncanmmacleod** [matplotlib/matplotlib#4043]
The [`YAxis.tick_right()`](http://matplotlib.org/api/axis_api.html#matplotlib.axis.YAxis.tick_right) method doesn't move a scale factor when the formatter introduces one. The following minimal example should demonstrate that:

```python
import numpy
from matplotlib import pyplot
data = numpy.random.random(1e4) * 1e-22
fig, axes = pyplot.subplots(2, 1, sharex=True)
axes[0].plot(data)
axes[1].plot(data ** (.5))
axes[1].yaxis.set_label_position('right')
axes[1].yaxis.tick_right()
```

![tick_right](https://cloud.githubusercontent.com/assets/1618530/5930102/c91db7fc-a650-11e4-931e-ac6013b4abe7.png)

The `1e-11` factor should ideally be on the right-hand-side with the tick labels.

**Comment by WeatherGod** [comment]
Hmm, that's a bit odd. If I recall correctly, the offset/scale text is
moved to the right whenever we use twinx().
