### ISSUE TITLE
Delete vertical lines (or vertical rules) in plt.table? How to remove cell boundaries and shows table as scientific tables?

### ISSUE THREAD

**Issue by arnaldorusso** [matplotlib/matplotlib#4044]
Is there any way to remove the vertical lines in a matplotlib table?
Or even using `text.usetex=True` obtain a plot (using Arial for all texts and numbers) and append a table without vertical lines?

My code is this:

    import matplotlib.pyplot as plt
    import seaborn as sns

    sns.set_style("ticks")
    plt.rcParams.update({'xtick.labelsize' : 9,
                        'ytick.labelsize' : 9,
                        'mathtext.fontset' : 'stixsans',
                        'mathtext.default': 'regular'
                        })

    plt.subplots_adjust(left=0.17, right=0.96, top=0.97, bottom=0.09)

    fig = plt.figure(figsize=(5.5, 3.4))
    ax = fig.add_subplot(111)

    ax.plot([1, 2, 3, 4, 5, 6])
    ax.set_xlabel('X Label')
    ax.set_ylabel('Unit ('+u'μ'+r'velocity $\cdot$ m$^{-2}$ s$^{-1}$)',
                 size=10)

    l1 = ["","t0", "t1", "t2", "t3 ", "t4", "t5", "t6"]
    l2 = ["DLI", 35, 38, 10, 22, 25, 85, 22]
    t = ax.table(
                colWidths=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                cellText = [l1, l2],
                loc="upper center",
                colLoc="center",
                rowLoc="center",
                )
    plt.savefig('mpl_table.png')
    plt.show()

I tried to include some LaTeX stuff in another plot, which preserves Arial font, but does not render the table with horizontal lines [Table correct](http://imgur.com/4TckUyb). When I get the table as I want, the fonts can not be setted to Arial.

[Here](https://gist.github.com/arnaldorusso/e542b04245560300d4f7) the codes show the plots in two steps. First generating the [first plot](http://imgur.com/J1A01h5) and after running in a new session the [second plot](http://imgur.com/4TckUyb).

My main problem is to maintain the Arial font (mandatory rules in the guide for authors) and tables should be without vertical rules, as stated on [first plot](http://imgur.com/J1A01h5).

I have here three approachs and no one satisfy those recquirements (e.g. Arial font and table with no vertical lines)

I could not figure it out. Any clues?

Cheers,
Arnaldo.

**Comment by tacaswell** [comment]
It does not look like this is something that is currently supported via `matplotlib.table`, but I suspect it would not be too hard to do by sub-classing `matplotlib.table.Cell` (to override `draw` to not use a rectangle so you can drop the vertical bars) and `matplotlib.table.Table` (to override `add_cell` to use your new sub-class of `Cell`, or extent `Table` to make tuning the `Cell` class possible).

You might be better off in the short run `annotate` + `axhline`

**Comment by arnaldorusso** [comment]
Thank you @tacaswell for inlcuding this as *wishlist* label.
Always addressing good ideas (`annotate` + `axhline`)!
Cheers,

**Comment by tacaswell** [comment]
@arnaldorusso Sorry to not be of more help.

When you get this figured out, can you consider providing it back as an example or an enhancement?

**Comment by arnaldorusso** [comment]
A development task:
what could be the correct way, trying to do that @tacaswell ?
include a `type` of cells to be drawn? inside

    class Table(Artist):
        def __init__(self, ax, loc=None, bbox=None, **kwargs):

and include a parameter **type** as:

    def __init__(self, ax, loc=None, type=None, bbox=None, **kwargs)

where **self.types** would be what??
which is the best way to include a parameter on `Table` class to do not use rectagles of `Cell` class?!

Sorry about my bad english :grin:

**Comment by tacaswell** [comment]
I think that is along the lines of what I was thinking, but I would strongly advise against using the name 'type' and that shadows `type` which can have surprising behavior.

I would go with something like:

```
class Table(Artist):
    def __init__(self, ax, loc=None, bbox=None, cell_cls=None, cell_kwargs=None **kwargs):
        if cell_cls is None:
            cell_cls = Cell
        if cell_kwargs is None:
            cell_kwargs = dict()

       ....
       foo = cell_cls(..., **cell_kwargs)
       ....

```

Where I have thrown `...` in to mean 'what ever code makes sense'.

**Comment by arnaldorusso** [comment]
For sure `type` is not a good word... I'll try to do this as far as I can.
Thanks for initial comments.
=]

**Comment by arnaldorusso** [comment]
Awesome!!

Sorry to not dedicate my time on this issue!

Thanks at all!

**Comment by markroxor** [comment]
I tried using this implementation but it looks like since you're using "path". You won't get a closed figure which you could've got by "Rectangle" and therefore you cannot fill color in that cell. Is there a workaround for losing the vertical lines and at the same time keeping the cell color?
