### ISSUE TITLE
line color not picked up in rc arguments?

### ISSUE THREAD

**Issue by cel4** [matplotlib/matplotlib#4047]
Any idea what's going wrong here?` The issue is based on following SO question:

http://stackoverflow.com/questions/28191596/matplotlib-change-linewidth-on-all-subplots

This is the code:
```
%matplotlib inline
import matplotlib as mpl
import matplotlib.pylab as plt

mpl.rc('lines', linewidth=2, color="r")

plt.plot([1,2,3], [3,2,1])
```

And this the result:

![image](https://cloud.githubusercontent.com/assets/3819470/5937424/88ccb55a-a6ef-11e4-959d-d60fcd506855.png)

Any idea why the `color` argument is not picked up?

According to the docs, it should work: 
http://matplotlib.org/1.4.1/users/customizing.html#dynamic-rc-settings

**Comment by tacaswell** [comment]
because it is being over-ridden by the color-cycle functionality

```python
mpl.rc('axes', color_cycle=['r'])
```

will do what you want.

**Comment by tacaswell** [comment]
Some changes to this code was made in #3855 but I don't think that caused this issue.

**Comment by tacaswell** [comment]
I think this goes back to 9cfa33556400957ceffc5ed87cfb16ce8d4d98df

attn @efiring

**Comment by tacaswell** [comment]
And I am starting to think that the solution is to remove that bit of documentation.

@cel4 Has this code ever worked for you?

**Comment by WeatherGod** [comment]
I don't think that code would have ever worked. I recall this question
coming up from time to time, and I think the answer was always that "lines"
wasn't meant for plot lines. But, seeing the linewidth of the plot affected
as it is, it makes me reconsider that position.

On Wed, Jan 28, 2015 at 10:08 AM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
If you look in `Line2D` it does fall back to the rcparam if the input color is `None`, but there are no high-level functions which do not pass in a color to the `Line2D.__init__`

**Comment by efiring** [comment]
The "lines" parameters set defaults for LineCollection.
Overall, I agree that the problem here is the inherent messiness of the rcParams system combined with erroneous documentation.

**Comment by tacaswell** [comment]
I am going to close this because it is tied up in the overhaul that rcparams/our document model which is already on our radar.
