### ISSUE TITLE
PowerNorm().__call__ doesn't work with scalar input value

### ISSUE THREAD

**Issue by olegarch** [matplotlib/matplotlib#4053]
result[value<0] = 0; #fails if value is scalar

**Comment by tacaswell** [comment]
Can you provide a bit for context to what is going on here?  It is best if you can include an example that can be copy-paste run (http://sscce.org/) and the traceback produced.

**Comment by olegarch** [comment]
Python 2.7.6

=================== Sample starts here =============
#!/usr/bin/env python

import matplotlib
import matplotlib.pyplot

min,max = (1,100)
cm = matplotlib.pyplot.get_cmap('jet') 
cNorm0 = matplotlib.colors.Normalize(vmin=min, vmax=max)
cNorm1 = matplotlib.colors.LogNorm(vmin=min, vmax=max)
cNorm2 = matplotlib.colors.PowerNorm(1.,vmin=min, vmax=max,clip=True)
scalarMap0 = matplotlib.cm.ScalarMappable(norm=cNorm0, cmap=cm)
scalarMap1 = matplotlib.cm.ScalarMappable(norm=cNorm1, cmap=cm)
scalarMap2 = matplotlib.cm.ScalarMappable(norm=cNorm2, cmap=cm)

value = 50.
print "min,max",min,max
print "RGB for Normalize(50)", scalarMap0.to_rgba(value)
print "RGB for LogNorm(50)", scalarMap1.to_rgba(value)
print "RGB for PowerNorm(50)", scalarMap2.to_rgba([value])[0]
print "RGB for PowerNorm(50)", scalarMap2.to_rgba(value)
============== Sample ends here ==================

Output:
$ ./powernorm.py
min,max 1 100
RGB for Normalize(50) (0.46489563567362424, 1.0, 0.50284629981024676, 1.0)
RGB for LogNorm(50) (1.0, 0.21859114015976777, 0.0, 1.0)
RGB for PowerNorm(50) [ 0.46489564  1.          0.5028463   1.        ]
RGB for PowerNorm(50)
Traceback (most recent call last):
  File "./powernorm.py", line 20, in <module>
    print "RGB for PowerNorm(50)", scalarMap2.to_rgba(value)
  File "C:\Python27\lib\site-packages\matplotlib\cm.py", line 262, in to_rgba
    x = self.norm(x)
  File "C:\Python27\lib\site-packages\matplotlib\colors.py", line 1180, in __call__
    result[value < 0] = 0
  File "C:\Python27\lib\site-packages\numpy\ma\core.py", line 3072, in __setitem__
    ndarray.__setitem__(_data, indx, dval)
ValueError: boolean index array should have 1 dimension

**Comment by WeatherGod** [comment]
Which version of matplotlib? I could have sworn we fixed this.

By the way, with my matplotlib from (slightly old) trunk and numpy version
1.9.0:
>>> scalarMap2.to_rgba(50.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.x-py2.7-linux-x86_64.egg/matplotlib/cm.py",
line 263, in to_rgba
    x = self.norm(x)
  File
"/nas/home/broot/centos6/lib/python2.7/site-packages/matplotlib-1.5.x-py2.7-linux-x86_64.egg/matplotlib/colors.py",
line 1189, in __call__
    result[value < 0] = 0
  File
"/nas/home/broot/centos6/lib/python2.7/site-packages/numpy/ma/core.py",
line 3079, in __setitem__
    ndarray.__setitem__(_data, indx, dval)
IndexError: in the future, 0-d boolean arrays will be interpreted as a
valid boolean index

So, I don't know if this is a weird interaction or not with numpy.

**Comment by tacaswell** [comment]
have a fix in + extended the tests.

At some point we should go through and simplify all of that code to use arrays filled with nans internally rather than masked arrays.

**Comment by tacaswell** [comment]
@olegarch Thanks!  If possible can you confirm that this fixes the issue for you?

**Comment by olegarch** [comment]
It works. Thanks!

**Comment by tacaswell** [comment]
@olegarch Good. This fix will be in 1.4.3 (tagged a release candidate last night, should do full release next weekend).

**Comment by tacaswell** [comment]
@olegarch Good to hear.
