### ISSUE TITLE
FreeType checking for unix

### ISSUE THREAD

**Issue by autodrive** [matplotlib/matplotlib#4062]
1.4.2  may have difficulty locating freetype2 on unix if pkg_config is not installed (correctly). To make the installation more robust, what about adding get_extension method to the FreeType class of setupext.py file?

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/pull/3976, https://github.com/matplotlib/matplotlib/pull/3713, and https://github.com/matplotlib/matplotlib/pull/3622

**Comment by tacaswell** [comment]
@autodrive Sorry, reading that message after I posted it comes across as way more hostile than I intended!

That message is mostly notes the other devs.

**Comment by autodrive** [comment]
From your first comment, I could learn about prior similar ones.

**Comment by tacaswell** [comment]
@autodrive Yes, but I should have been friendlier about it.

**Comment by pelson** [comment]
@tacaswell - you missed #3363, which also deals with Freetype (specifically getting the correct version string).

@autodrive - I think it might be helpful if you could provide a PR which shows the kind of thing you had in mind (it doesn't have to be complete, just something to give focused feedback - it may be that by doing that we get some more information on the problem).

Cheers!

**Comment by jenshnielsen** [comment]
On Mac there is an issue when pkg config is not installed. I tried fixing it in #3713 but it breaks other stuff.  
We need to refactor and generalise the code a bit to make it possible to search more directories. It's been on my list of stuff that I want to fix for a long time. Just haven't gotten around to it.

**Comment by autodrive** [comment]
@pelson May I have your opinion based on which commit I should prepare a pull request? 1.4.2 (3a828dd)? Or any other?

**Comment by pelson** [comment]
> May I have your opinion based on which commit I should prepare a pull request?

I can't give a definitive answer. If your change would be invasive, I'd target the master branch, otherwise if this is a bugfix with little impact other than making a specific case better, then the v1.4.x branch would be the target.

Stick it against master for now, and we can always back port.

Cheers,

**Comment by tacaswell** [comment]
Definitely against master.  @efiring made a compelling case that 1.4.3 should be the last maintenance release and we should just start working on 1.5 now.

**Comment by QuLogic** [comment]
Based on the linked issues, I think `pkg-config` is now required building Matplotlib, and the old fallback of `freetype-config` is just broken, so the only course of action is to install `pkg-config`.
