### ISSUE TITLE
Histogram with histtype='step' dows not respect lines.linewidth 

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#4065]
hist with `histtype=step` ignores the `lines.linewidth` rcParam.

**Comment by tacaswell** [comment]
This is because hist use a `Patch` object to draw the stepped histogram, not a `Line2D` object.

I would suggest not using `hist` and instead use `np.histogram` + `ax.step`

```python
vals, bins = np.histogram(..)
ax.step(bins[:-1], vals, where='post')
```

which should be aware of that rcparam.

**Comment by MaxNoe** [comment]
So it does respect `patch.linewidth`?

**Comment by anntzer** [comment]
I would like to suggest switching to using `ax.step` internally to plot such histograms, so that `lines.linewidth` gets respected (I think it makes sense e.g. for seaborn to set a relatively small `patch.linewidth` but a large `lines.linewidth`).

**Comment by tacaswell** [comment]
@anntzer No, because then the return typo of `hist` would depend on a kwarg which is really bad form.

**Comment by anntzer** [comment]
Fair enough, reopened on seaborn's side as mwaskom/seaborn#704.

**Comment by anntzer** [comment]
Reporting an idea that had been shot down on seaborn's side:
What about having `hist` locally patch rcParams to set `patch.linewidth` to `lines.linewidth` when making the plot?  I still think the current behavior is unintuitive.

**Comment by tacaswell** [comment]
:-1: on that from me as well.  

If something like that were to happen, the right place would be for seaborn to wrap hist and then use the style context manager to locally over-ride the rcparams.
