### ISSUE TITLE
Cannot unpickle polar plot

### ISSUE THREAD

**Issue by joergdietrich** [matplotlib/matplotlib#4068]
I create the polar plot example from http://matplotlib.org/examples/pie_and_polar_charts/polar_scatter_demo.html

Then

```
fig = plt.gcf()
pf = pickle.dumps(fig)
f2 = pickle.loads(pf)
```

throws the following exception:
```
/home/joerg/applications/anaconda3/lib/python3.4/site-packages/matplotlib/transforms.py in __setstate__(self, data_dict)
    116         self.__dict__ = data_dict
    117         # turn the normal dictionary back into a WeakValueDictionary
--> 118         self._parents = WeakValueDictionary(self._parents)
    119 
    120     def __copy__(self, *args):

AttributeError: 'PolarAffine' object has no attribute '_parents'
```

Note that this is separate from issue #3483 in that `plt.ioff()` before unpickling does not work.

**Comment by pelson** [comment]
Thanks @joergdietrich. This should be a relatively easy fix. If you are interested in having a go, a similar problem was fixed in #3627. Otherwise, we will try to pick this one up before the next release.
