### ISSUE TITLE
Sliders show as (truncated) triangles when using Cairo backends, fine with Agg.

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/matplotlib#4074]
Testing ``matplotlib/examples/widgets/slider_demo.py`` on various backends, the bug fixed with https://github.com/matplotlib/matplotlib/pull/576 seems to have re-emerged since 1.3.1, or at least a similar phenomena.

I have tested ``slider_demo.py`` using the following backends:

Backend | Displays this bug
----------- | ------------
GTKAgg | no
GTK3Agg | no
Qt4Agg |		no
TkAgg	|	no
WXAgg	|	no
GTK		|	yes
GTK3Cairo|	yes
WX		|	yes
GTKCairo	| yes

**Comment by mdboom** [comment]
The first broken commit appears to be 91725d8665975de9a26d631445ab1448b0391e1a.

**Comment by OceanWolf** [comment]
@tacaswell Should this also go in the ``color overhaul`` branch as it fixes an issue introduced in 1.4.

**Comment by tacaswell** [comment]
@OceanWolf  I don't think the change that caused this is on the 1.4 branch.

**Comment by OceanWolf** [comment]
@tacaswell Ahh, my mistake, I remembered seeing the triangles before on a standard release, it must have been from the previous time this bug occurred.

**Comment by tacaswell** [comment]
@OceanWolf No worries.
