### ISSUE TITLE
osx testing on travis

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4077]
@matthew-brett Is it possible to get travis to run osx tests next to the linux tests?

**Comment by matthew-brett** [comment]
Pillow have automated a trigger of the OSX build after a successful Linux build:

https://github.com/python-pillow/Pillow/pull/1067

We could probably do something similar.

**Comment by tacaswell** [comment]
Could you set that up?

**Comment by matthew-brett** [comment]
OK - I'm working on that now, using stuff from the Pillow PR and the sources of the PR:

https://github.com/dmakhno/travis_after_all
https://github.com/ajdm/travis-build-children

**Comment by matthew-brett** [comment]
I think this will work: 

https://github.com/matplotlib/matplotlib/pull/4138

**Comment by jenshnielsen** [comment]
This has been working for some time?

**Comment by jenshnielsen** [comment]
Looks like this is not currently running because it doesn't respect that the python 3.5 job is allowed to fail. 
@matthew-brett is there an easy way to fix that? 

The python 3.5+ fails due to a bug which was fixed ages age but travis's "nightly" build of python is still alpha4+ something (python 3.5 beta 3 has been released now)

**Comment by tacaswell** [comment]
We could monkey patch sphinx on travis to fix the problem on that side.

**Comment by jenshnielsen** [comment]
I'm tempted to just disable that job. It's rather pointless with a nightly python build that haven't been updated for months.

**Comment by anntzer** [comment]
I think this is fixed now?  Or is there something needed other than the current OSX job on travis?

**Comment by jenshnielsen** [comment]
Yes this predates when travis had support for running mixed os jobs. we were using a script to trigger a downstream osx build
