### ISSUE TITLE
Images disappearing on mouse drag

### ISSUE THREAD

**Issue by kkoci** [matplotlib/matplotlib#4085]
Hi, I'm using matplotlib 1.4.2 and Python 2.7

I'm running the 'DraggableRect' example, the one which uses the 'blit' method.

BTW on gtk3agg it runs perfectly, and if I drag something it works just fine, however, when I set webagg as a backend, everything but mouse drag works, when I try to drag a rect, it looks like it is working, but the image actually disappears, and I can't visualize it well after I drop it.

I've heard it has something to do with 'blit' method, which is set to 'False' by default on backend_webagg.py.

Is there a solution for this?
Some Idea to make it work as it should be?

Thanks in advance!

**Comment by blink1073** [comment]
For what its worth, the [demo](http://matplotlib.org/users/event_handling.html#draggable-rectangle-exercise) works fine for me in webagg using the master branch (albeit a bit sluggish).

**Comment by kkoci** [comment]
My problem is just on webagg, are you using webagg? Sure?

**Comment by blink1073** [comment]
Sorry @kkoci, I realized I was using the example without the explicit blit.

**Comment by kkoci** [comment]
Oh, right, ya... =/ 

No problem...

**Comment by blink1073** [comment]
I added a `print(canvas.supports_blit)` in there, and sure enough the web canvas does not support blitting.  Perhaps the default behaviour should be changed when requesting a blit on a canvas that does not support blitting to raise a warning or an error.  What do you think @tacaswell?

**Comment by kkoci** [comment]
The (not ) blit version is painfully slow though, we're on this project for a client, but we cannot show it with blit like this, or that slow.

We think matplotlib is just awesome as it is very matlab-ish, and suits our needs, but we desperately need to solve this 'blit' issue, or if possible drastically reduce the sluggishness without blit.

:(

**Comment by tacaswell** [comment]
There is no technical reason (that I know of) that webagg can't do blitting, just that it has not been implemented.

You might just need to implement the `blit` method on `mpl.backends.backend_webagg_core.FigureCavasWebAggCore` to stage-manage shipping the updated images off to browser

**Comment by tacaswell** [comment]
and it looks like most of the hard work of that is arleady taken care of by `get_diff_image` and that machinery.

**Comment by blink1073** [comment]
Related question, are we always using "full" `image_mode`, and has `diff` ever been tested?
cc/ @pelson.
 
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_webagg_core.py#L163

**Comment by pelson** [comment]
> Related question, are we always using "full" image_mode, and has diff ever been tested?

I think you've missed the set_image_mode method - that does change the mode from full to diff wherever possible. 

> There is no technical reason (that I know of) that webagg can't do blitting

I completely agree.

> and it looks like most of the hard work of that is arleady taken care of by get_diff_image and that machinery.

I don't necessarily agree.

There are two phases to blitting on the web backends:

 1. Do the blitting with Agg (as per all other blittable backends). This should be easy (I think).
 2. Send only a subset of the rendered image over the pipe to the browser. I don't think this bit has been looked at yet. Essentially you would want to send over a smaller image, and the coordinates where this image should be applied on top of the existing image ala HTML5 canvas drawImage. 

Unsurprisingly the current code assumes that the image is the *whole* image, and therefore puts the image at coordinate 0, 0. To support blitting, that assumption would need to be removed. (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/mpl.js#L72)

**Comment by jakirkham** [comment]
I am seeing this same issue. It is also occurring in the nbagg/notebook backend. Is it due to some shared code between the two or are these two different code paths causing the same sort of issue?

**Comment by tacaswell** [comment]
Neither backend supports blitting.  I have a pr which starts to add blitting for nbagg, but it has issues (that i don't remember off the top of my head)

**Comment by jakirkham** [comment]
Where is the PR?

**Comment by sjvrijn** [comment]
Problem seems to be fixed; tested the ['extra credit' example](https://matplotlib.org/3.1.1/users/event_handling.html#draggable-rectangle-exercise) on `matplotlib==3.0.1` with and without `matplotlib.use('webagg')`, result was the same: was able to drag and drop the rectangles without anything disappearing.

So I think this issue can be closed

**Comment by timhoffm** [comment]
Thanks for checking!

**Comment by sjvrijn** [comment]
@QuLogic Sorry, you're right: I had tested with `matplotlib.use('webagg')` _after_ `import matplotlib.pyplot as plt` instead of before, meaning I wasn't using the webagg backend after all. Just tested correctly, and indeed, it is still broken (Windows 10, matplotlib 3.0.1, Python3.6).
My bad 😅
