### ISSUE TITLE
best way to access mouse event in webagg after going through backend?

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#4098]
disclaimer: I don't know javascript.

I am trying to reimplement an existing matplotlib GUI to use the new webagg backend. 

I have a front-end mouse event (click on the y-axis) which calls a function in the backend (to get some information), which then calls a function `handle_y_axis_click` in the front end (to show a pop-up menu with the information near the y-axis).

I would like to be able to access the original event (the click on the y-axis) from the `handle_y_axis_click` method. 

A simple solution is to store the last mouse_event inside the figure object. For example, adding the following line in mpl.js to the `mouse_event` method:

```
mpl.figure.prototype.mouse_event = function(event, name) {
+    this.last_mouse_event = event;
```

which later allows me to access this information:

```
fig.handle_y_axis_click = function(fig, msg) {
  mouse_x = fig.last_mouse_event.pageX;
  mouse_y = fig.last_mouse_event.pageY;
  blah
}
```

Is this the best way to go about doing this?

**Comment by tacaswell** [comment]
Why do you want to store this in the js layer rather than in the python layer?

**Comment by eyurtsev** [comment]
@tacaswell  I need to respond to the event in the js layer (make a pop-up menu at the location of the mouse using jquery).

But I think as long as the original event (guiEvent) is passed to the python layer, I can always pass it back to the javascript layer.

**Comment by HanMuYa** [comment]
You can change mpl.js when in your python code by replace funcition, and return to frontend, in html you can create a EventEmitter class, for example following:
`
<script>
        class EventEmitter {
          constructor() {
            this.events = new Map();
          }
        
          on(event, listener) {
            if (!this.events.has(event)) this.events.set(event, []);
            this.events.get(event).push(listener);
          }
        
          off(event, listener) {
            const arr = this.events.get(event);
            if (!arr) return;
            const idx = arr.indexOf(listener);
            if (idx >= 0) arr.splice(idx, 1);
          }
        
          emit(event, ...args) {
            const listeners = this.events.get(event);
            if (!listeners) return;
            for (const fn of listeners) {
              fn(...args);
            }
          }
        }
    window.ee = new EventEmitter();
    window.ee.on('data', (payload) => console.log('收到数据：', payload));
</script>
`
In python code after read mpl.js, replace following js_original with js_with_emit.
`
js_original = """this.send_message(name, {
        x: x,
        y: y,
        button: event.button,
        step: event.step,
        buttons: event.buttons,
        modifiers: getModifiers(event),
        guiEvent: simpleKeys(event),
    });"""

js_with_emit = """this.send_message(name, {
        x: x,
        y: y,
        button: event.button,
        step: event.step,
        buttons: event.buttons,
        modifiers: getModifiers(event),
        guiEvent: simpleKeys(event),
    });
    if (name === 'button_press')
    {
        window.ee.emit('data', {
            text: document.getElementsByClassName('mpl-message')[0]?.textContent.trim() ?? ''
        });
    };
    """
`
