### ISSUE TITLE
Unsharp text in pixel-based backends

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#4102]
Maybe this is a little bit subjective, but even after playing around with dpi, fonts and 
figure size, i still think that the text in plots generated by mpl looks not as sharp as it could be.
Please note i don't think my installation is to fault, e.g. the text in the examples at 
https://github.com/jbmouret/matplotlib_for_papers also looks not to good. In day
to day usage it is quite visible when working in the ipython notebook, even after adjusting 
the savefig.dpi. 

If i am the only one thinking this way, please close the issues, but i think there could be something 
wrong, either in freetype itself or the binding to it.

**Comment by efiring** [comment]
It would be most helpful if you could include a minimal script and the resulting .png file illustrating this.

**Comment by mdboom** [comment]
And a screenshot of some text that you think looks better would be helpful as well.

Note one thing that matplotlib does *not* do is subpixel antialiasing (called ClearType by Microsoft), since such images would not be portable to other displays.  This does give the appearance of slightly less antialiasing than you might see elsewhere on your system.

**Comment by Tillsten** [comment]
There more i play around with it the more i am sure that this is somehow ipython fault. Have look at

http://nbviewer.ipython.org/urls/gist.github.com/Tillsten/25e722abe97ad19e30f6/raw/f80604d99a1d1a888a238dd49c75eae197e5d1eb/mpl_inline

Both images are made by excatly the same code, only the backend differs. The top one is made by using %matplotlib qt (other backends have the same result.). The bottom one is done with %matplotlib  inline. I think i have directly set every setting ipython changes. Both figures have the same pixel size.

**Comment by Tillsten** [comment]
Hmm, ok it seems that the inline backend changes the font-size by default. I am not really happy about all the inline-backend related changes to the rcParams in python. This properly explains my impression: a 10-pt TTF-font looks quite bad if upscaled. So is mostly a ipython issue, please go ahead and close the issuse.

**Comment by tacaswell** [comment]
You should also have a look at the nbagg backend.

**Comment by mdboom** [comment]
Eventually we should probably figure out the CSS magic to have those images display at native resolution (i.e. "Retina mode"), too.

**Comment by Tillsten** [comment]
nbagg only works locally, and i use for exploratory work. But one main advantage of notebook is easy sharing, which only works with inline figures. Tbh I think ipyton should offer an inline backend with no changes to rcParams and document the changes for default-inline backend better.

**Comment by tacaswell** [comment]
nbagg should save down to png for sharing right?

**Comment by Tillsten** [comment]
At least in the last version, one have to handle all the figures and close them
if necessery. I never tried to save a notebook with open figures as html.

Changes done by inline-defaulst:

        'figure.facecolor': (1,1,1,0),
        'figure.edgecolor': (1,1,1,0),
        'axes.facecolor': (1,1,1,0),
        'font.size': 10,
        'savefig.dpi': 72, 
        'figure.subplot.bottom' : .125

**Comment by Tillsten** [comment]
I renamed the issue for better discoverability.

**Comment by Tillsten** [comment]
Is there any place in the FAQ for it? E.g. "Why does my plot looks different than in the ipython-notebook?".
