### ISSUE TITLE
Hanging in Django

### ISSUE THREAD

**Issue by msaysell** [matplotlib/matplotlib#4106]
Whilst trying to create a chart, Matplotlib will render correctly the first time a page is loaded, but if that page is then refreshed it will constantly hang on the line `_tkinter.create` deep within its inner workings (Tkinter.py) when creating the figure (`plt.figure`).

Template (Only needs this one line)

    <img src="data:image/png;base64,{{ graph }}"/>

Chart creation

    class PolarChart(object):    
        @staticmethod
        def example_chart():
            from math import pi, radians
            import cStringIO
            import base64  
            import numpy as np
            import matplotlib.pyplot as plt

            fig = plt.figure()    
            axis = fig.gca(polar=True)
    
            n = 20
            theta = np.linspace(0.0, 2 * pi, n, endpoint=False)
            radii = 10 * np.random.rand(n)
    
            axis.plot(theta, radii, marker='.', alpha=0.5, linewidth=1)
    
            jpg_image_buffer = cStringIO.StringIO()
            fig.savefig(jpg_image_buffer)
    
            plt.close(fig)
            base_array = base64.b64encode(jpg_image_buffer.getvalue())
            jpg_image_buffer.close()

            return base_array

View

    graph = PolarChart.example_chart()

    return render(request, "test.html", {'graph': graph})

**Comment by jenshnielsen** [comment]
Since you are not directly using a graphical backend I would suggest explicitly disabling the TK backend.

Could you try to adding with something like :
```python
import matplotlib
matplotlib.use('agg')
```

before the first import of pyplot i.e. `import matplotlib.pyplot as plt`

This will make sure that you are not ising an interactive backend which you presumably have no need for and where the issue seems to be coming from.

**Comment by msaysell** [comment]
Thanks that works perfectly!

Thank you also for the fast response!
