### ISSUE TITLE
Axis ticks are not aligned by baseline

### ISSUE THREAD

**Issue by jowr** [matplotlib/matplotlib#4115]
Hi, it looks like the PGF backend defaults to top-align tick labels without accounting for the height of the letters. This works without problems with the PDF backend, also using Tex to render text does not make a difference.
using this Python code:

```
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(2,2))
ax = fig.add_subplot(111)
ax.plot([1,2],[5,7])
ax.set_xticks([1,2])
ax.set_xticklabels(["up","down"])
ax.set_xlim([0,3]) # get the ticks closer together
plt.tight_layout()
fig.savefig("ticks_std.pdf")
fig.savefig("ticks_std.pgf")
for lab in ax.xaxis.get_ticklabels():
    lab.set_verticalalignment("baseline")
fig.savefig("ticks_base.pdf")
fig.savefig("ticks_base.pgf")
for lab in ax.xaxis.get_ticklabels():
    lab.set_verticalalignment("top")
fig.savefig("ticks_top.pdf")
fig.savefig("ticks_top.pgf")
```

... and this Tex document:

```
\documentclass{standalone}
\usepackage{tikz}
\begin{document}
\begin{tabular}{ccc}
\input{ticks_std.pgf} & \input{ticks_base.pgf} & \input{ticks_top.pgf} \\
\includegraphics{ticks_std.pdf} & \includegraphics{ticks_base.pdf} & \includegraphics{ticks_top.pdf}
\end{tabular}
\end{document} 
```

produces this:
![ticks](https://cloud.githubusercontent.com/assets/769593/6227474/85287de2-b6a0-11e4-9b64-0f6919e9a298.jpg)

One possible solution could be to use the baseline alignment with some additional padding depending on the font size.

**Comment by tacaswell** [comment]
cc @pwuertz

**Comment by pwuertz** [comment]
I think I remember a discussion we once had about that. The point is that top-anchoring the individual ticks isn't the correct thing to do in the first place, but it is the default behaviour in matplotlib. The pgf backend is probably the only backend that reports the correct text sizes and thus shows this problem.

Ideally one should look for the maximum height of all ticks and base-align all ticks at the same vertical position (or maybe just font-size + margin).

**Comment by pwuertz** [comment]
Ok, we talked about that problem a few times, for example in #1734. Apparently, issue #2051 was opened to discuss the necessary change in the default alignment, but it didn't really take off.

I'm closing this one since it is a question of alignment not related to the backend.

**Comment by pwuertz** [comment]
@jowr: As a workaround, you could manually base-align like you did already and set an appropriate padding for the labels:

    for lab in ax.xaxis.get_ticklabels():
        lab.set_verticalalignment("baseline")
    fontsize = ax.xaxis.get_ticklabels()[0].get_size()
    ax.tick_params(axis='x', pad=fontsize+.8)

**Comment by jowr** [comment]
Thank you all for the quick action. I indeed found the other issues, but I wanted to report a new one since I thought that the other ones were only looking at the axis label and not the ticks. Good luck with your work and keep up the good spirit for matplotlib!

**Comment by jowr** [comment]
Thanks for the quick fix. I currently use this code:
```
for tick in ax1.get_xaxis().get_major_ticks():
    tick.set_pad(2*tick.get_pad())
    tick.label1 = tick._get_text1()
```
since I read somewhere that one should reassign the text after changing the padding...

**Comment by pwuertz** [comment]
Ah, you are absolutely correct. The previous discussions were focused on labels, we shouldn't forget about the ticks. And yes, your quick fix looks good and might be more robust since you are forcing the tick positions to be re-evaluated.

**Comment by tacaswell** [comment]
@jowr Can you put that into a pull request?

@pwuertz Re-opened

**Comment by pwuertz** [comment]
@tacaswell: This is only a workaround, I don't think this is ready for a PR yet. We need to start/continue a discussion on how to implement base-alignment by default and how to setup the necessary padding, i.e. which usecases are to be covered, which pathological cases are to be ignored.

**Comment by zlee-personal** [comment]
I'd note that the alignment can also be messed up from text rotation. A workaround I have found it to always use rotation_mode='anchor' when rotating text, despite this not normally being necessary in pdf mode. With this option the text alignment lab.set_horizontalalignment("right") seems to work as expected in pgf mode.
