### ISSUE TITLE
_create_tmp_config_dir() in __init__.py does not create a directory

### ISSUE THREAD

**Issue by dgarwin** [matplotlib/matplotlib#4120]
I believe the following code inserted after tempdir is created fixes it:
```
from matplotlib.cbook import mkdirs
mkdirs(tempdir)
```

**Comment by tacaswell** [comment]
@dgarwin Can you put that in a PR?  That makes in much easier to follow the changes you are suggesting and then you get credit for them when it get merged.

**Comment by tacaswell** [comment]
Sorry, about jargon, PR -> pull request.
