### ISSUE TITLE
Circular hatching patterns contain too many path segments

### ISSUE THREAD

**Issue by jowr** [matplotlib/matplotlib#4122]
The produced PGF documents litarally explode in file size as soon as you start using dotted hatching patterns. Some of my graphs cannot be compiled by pdflatex anymore... 
A simple plot like this one:

```
import matplotlib.pyplot as plt
fig = plt.gcf()
ax = fig.add_subplot(111)
ax.bar(0.85, 5, 0.3, color="lightgrey", hatch="////")
ax.set_xlim([0,3])
ax.set_ylim([0,10])
plt.tight_layout()
fig.savefig("pgfhatch_1.pgf")
fig.savefig("pgfhatch_1.pdf")
ax.bar(1.85, 7, 0.3, color="lightgrey", hatch="....")
fig.savefig("pgfhatch_2.pgf")
fig.savefig("pgfhatch_2.pdf")
plt.close()
```

produces files of very different sizes

```
-rw-r--r-- 1 jorrit jorrit 6.9K Feb 18 09:29 pgfhatch_1.pdf
-rw-r--r-- 1 jorrit jorrit  27K Feb 18 09:29 pgfhatch_1.pgf
-rw-r--r-- 1 jorrit jorrit  55K Feb 18 09:30 pgfhatch_2.pdf
-rw-r--r-- 1 jorrit jorrit 668K Feb 18 09:29 pgfhatch_2.pgf
```

However, the result is OK, but it takes ages to compile with pdflatex (if it succeeds).

```
\documentclass{standalone}
\usepackage{tikz}
\begin{document}
\begin{tabular}{cc}
\input{pgfhatch_1.pgf} & \input{pgfhatch_2.pgf} \\
\includegraphics{pgfhatch_1.pdf} & \includegraphics{pgfhatch_2.pdf}
\end{tabular}
\end{document} 
```

![horner](https://cloud.githubusercontent.com/assets/769593/6244289/9eceae2c-b751-11e4-85fe-2b69f4308af2.jpg)

Could it help to make real dots instead of circles?

**Comment by tacaswell** [comment]
cc @pwuertz Can you mile stone this appropriately?

**Comment by pwuertz** [comment]
Well, the path matplotlib provides for the second hatch pattern contains a whopping number of 6130 path segments. This naturally increases the number of pgf commands which latex cannot handle anymore at some point.

`backend_svg` suffers from the same problem, but `backend_pdf` doesn't seem to use the hatch path at all and simply interprets the hatch name. The naming scheme appears to be native to PDF, but I don't know much about this format.

So it looks like the pattern generated for all the non-PDF backends isn't very efficient when you shrink the elements / increase the pattern's density.

**Comment by pwuertz** [comment]
Well, actually its only the circular patterns that seem to be overly complicated. Even the basic pattern contains 500-1000 segments.

**Comment by pwuertz** [comment]
Does anybody know some details about how/where these patterns are created within matplotlib? Since cubic splines are supported in `Path`, a simple circle shouldn't require more than 4 path segments.

**Comment by mdboom** [comment]
The hatches are generated in `hatch.py`, but many of them use lower-level paths from `path.py`.

Since the circle path is often used quite large in matplotlib, it actually uses an 8-cubic-spline approximation, not a 4-cubic-spline one, because the error was noticable on high-resolution plots, particularly if only part of the circle was shown.  For hatching, that level of accuracy isn't necessary, of course, so added a 4-spline approximation for that purpose would be fine.

But that doesn't explain why we see 500-1000 segments.  Perhaps a bezier spline to line segment conversion is happening somewhere along the way?

**Comment by pwuertz** [comment]
Ok, so for the "o" pattern I'm seeing circle instances using the 8 segment approximation you were mentioning. For each dot there are two circles, a smaller and a larger one. The basic hatch pattern contains about 50 circles, which amounts to 800 segments. So the problem isn't really the number of segments per circle, it's the amount of circles.

**Comment by mdboom** [comment]
I see -- in that case, the solution may be to reduce the size of the hatch pattern so it contains fewer circles.  Unfortunately, it's currently hard-coded, i.e. all of the backends assume the hatch pattern is a 1x1inch square.  So I think fixing that will require updating all of the backends.

**Comment by jowr** [comment]
Thank you for the fast responses and good luck with fixing this. I wasn't aware that it was such a general issue.

**Comment by pwuertz** [comment]
Oh, I am mistaken. Also the PDF backend uses the hatch path from matplotlib, it just uses a different method for retrieving it. However, at least on my system the hatch pattern appears to be rasterized in the PDF output, which explains the much smaller file size compared to the fully vectorized PGF or PGF->PDF output.

Scaling of the pattern density within the backend sounds like a good approach. But yes, every backend would need to implement this individually, which probably won't happen anytime soon. I don't see a good workaround, other than to avoid using non-trivial high-density patterns for now.

Thanks for the quick reply @mdboom

**Comment by jowr** [comment]
I am not sure, but doesn't this #4108 indicate that the PDF backend does **not** render the hatch pattern?

**Comment by pwuertz** [comment]
@jowr You are right, on my Ubuntu system it was the default PDF viewer that rasterized the hatch pattern before applying it, the document is fully vectorized. So it's just PDF being able to store the pattern more efficiently than a million lines of latex code ;)

**Comment by mdboom** [comment]
Interesting...  PDF is `zlib` compressing the path data, so that's probably a lot better than PGF wrt file size.  SVG is also pretty bad, but still about half the size of PGF.  PGF is just really verbose unfortunately, and probably really works the TeX parser, whereas SVG and PDF both have much simpler languages to represent paths.
