### ISSUE TITLE
Add better test for text aligment issues

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4127]
The Abel font @sgmentzer used in #253 is a good one to catch this kind of error because the difference between advance width and control point bounding box is so large and because the kerning is so extreme. It might make sense to make a test or two based on it -- but then we have some technical issues to solve about how to get it. (It's under SIL Open Font License, so we can just incorporate it, but that might be overkill).

This is a continuation of #4031 , but split off so that the other PR did not accumulate conflicts.

**Comment by mdboom** [comment]
Agree would be nice.  Not sure how to best implement it.  It's on a Google CDN as a webfont, so we could download it from there (from within a test), and just mark it as xfail if the download fails.

**Comment by jenshnielsen** [comment]
Some what related I made travis download a few free fonts when building the docs to get as complete as possible autobuild docs. If we decide on something more clever for this we should likely fold these fonts into the same system.
