### ISSUE TITLE
Support clim kwarg in pcolor-type plots

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#4132]
Image-type plots support the clim kwarg, but pcolor-type do not.  Pcolorfast is a hybrid, so whether it does or does not depends on whether it is generating an image or a quadmesh.

The problem is most likely a consequence of inconsistencies in the way **kwargs are passed down, and the way the overwhelming number of documented kwargs are collected by the auto doc generation--by looking for "set_" methods.  There has been discussion about cleaning this up, long-term; in the short term, I think we should just make sure that the clim kwarg actually is supported by anything that presently claims to support it, and potentially by anything that generates a ScalarMappable.

This is open to discussion.

**Comment by tacaswell** [comment]
:+1: on making sure everything supports it.

**Comment by petehuang** [comment]
Should we change the issue title to "Support clim kwarg in pcolor-type plots"?
