### ISSUE TITLE
MacOSX backend not closing properly

### ISSUE THREAD

**Issue by cimarronm** [matplotlib/matplotlib#4142]
MacOSX backend does not seem to be closing properly when plot windows are closed.

```python
import matplotlib.pyplot as plt

plt.plot(range(10))
plt.show()
print("Won't reach here")
plt.plot(range(20))
plt.show()
```

The python script will halt after the first `plt.show()` even after closing the plot windows. Problem seems to be that the backend NSApp is not quitting and is not returning back from `show()`.

**Comment by cimarronm** [comment]
This appears to have started with PR #4006. 

@mdehoon, do you want to see if you can reproduce on your system and it is not just an issue with my setup? I see the problem running on python 3.4.2.

**Comment by cimarronm** [comment]
Also, I don't see any issues if run under ipython or if `ion()` is set

**Comment by mdehoon** [comment]
Indeed this was caused by some code getting inadvertently lost in pull request 4006.
See pull request 4144 (https://github.com/matplotlib/matplotlib/pull/4144) for a fix.
