### ISSUE TITLE
BUG: different colorcycle behavior when using c or color as keyword when plotting.

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#4157]
The following code illustrates the problem:

    import matplotlib.pyplot as plt
    
    plt.subplot(211)
    plt.plot([2, 1], c='k')
    plt.plot([1, 2])
    
    plt.subplot(212)
    plt.plot([2, 1], color='k')
    plt.plot([1, 2])

One would expect the same plot, but actually the index of color_cycle is increased when using 'c', and stays the same when using 'color'. The latter is imo the right behavior. Matplotlib 1.4.3.

**Comment by Tillsten** [comment]
The fix should be adding to check for 'c' too in :
https://github.com/matplotlib/matplotlib/blob/a05a02a032283a585c0917eda3b5e191c9a8d317/lib/matplotlib/axes/_base.py#L236

**Comment by tacaswell** [comment]
Closely related to #4162
