### ISSUE TITLE
How to test for optional build dependencies?

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#4161]
How can I test, if matplotlib was build with an _optional_ dependency?

E.g. i write a package which requires matplotlib build with Tcl/Tk because i use it in a gui. How can I check that matplotlib was build with Tcl support?

**Comment by mdboom** [comment]
You could do:

```
from matplotlib.backends import _tkagg
```

it will raise an ImportError if matplotlib was built without tkinter support.

Closing issue, as this isn't really bug.

**Comment by efiring** [comment]
@MaxNoe The matplotlib-users mailing list is the ideal place for questions like this.  It gives more people a chance to answer, and to see the answer.
