### ISSUE TITLE
c=color not changing line color

### ISSUE THREAD

**Issue by divenex** [matplotlib/matplotlib#4162]
In Matplotlib 1.4.3

```
plt.plot([0,1], c='lime', linewidth=20)
```

produces a blue line, while

```
plt.plot([0,1], color='lime', linewidth=20)
```

produces a green one as expected.

**Comment by tacaswell** [comment]
Did using `c` used to work?

**Comment by Tillsten** [comment]
I can not reproduce that one, c works.

**Comment by NelleV** [comment]
I can't reproduce either but I only tried on master.

Did using c used to work?

—
Reply to this email directly or view it on GitHub
<https://github.com/matplotlib/matplotlib/issues/4162#issuecomment-75999454>
.

**Comment by divenex** [comment]
Yes, using c=color used to work for various matplotlib releases. I noticed the problem because the plots produced by some of my code suddenly changed colors after updating matplotlib.

**Comment by efiring** [comment]
"c" and "color" are listed in the Line2D docstring as synonyms, so they should work identically as kwargs in `plot()`.  The problem is present on master as well as 1.4.3.

**Comment by tacaswell** [comment]
Have a hunch that https://github.com/matplotlib/matplotlib/pull/3855/files caused this regression but don't have time to chase this down today.

**Comment by tacaswell** [comment]
github-foo linking magic #3855

**Comment by efiring** [comment]
Now, what I don't understand is why I can reproduce this on a recent master, and @NelleV cannot.  I'm on Python 3.4:
```
In [1]: import matplotlib

In [2]: matplotlib.__version__
'1.5.dev1'

In [3]: %matplotlib qt

In [4]: import matplotlib.pyplot as plt

In [5]: plt.plot([0,1], c='lime', linewidth=20)
[<matplotlib.lines.Line2D at 0x1155ec080>]
```
That gives me a blue line.

**Comment by WeatherGod** [comment]
I think I know what is happening (for once, my futile attempts at
refactoring color-cycling bears some useful knowledge!)

There are two dictionaries passed around for various reasons. While this
change improved things by not only retrieving data from either
dictionaries, but also saving information to both. Unfortunately, the code
doesn't check for the synonyms. Without "color' in the second dictionary,
the Line2D object was getting the value for 'c'. Now, 'color' shows up from
the color-cycling, overriding the 'c' argument.

**Comment by WeatherGod** [comment]
Could be different values for color-cycling in the rc?

**Comment by mwaskom** [comment]
Just ran into this issue in the seaborn tests and can confirm that I see it only on Python 3.4, but not on Python 3.3 or 2.7.
