### ISSUE TITLE
Error with nbagg backend on Windows 8.1 and Anaconda

### ISSUE THREAD

**Issue by Zuriich** [matplotlib/matplotlib#4169]
Although I have installed matplotlib 1.4.3 by means of Anaconda, I've got the following error when trying to use the nbagg backend. I have tryied both Python 2 and 3 environments.

%matplotlib nbagg
#Returns:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-05a583bde809> in <module>()
----> 1 get_ipython().magic('matplotlib nbagg')
      2 import matplotlib.pyplot as plt

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\interactiveshell.py in magic(self, arg_s)
   2203         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2204         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2205         return self.run_line_magic(magic_name, magic_arg_s)
   2206 
   2207     #-------------------------------------------------------------------------

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line)
   2124                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2125             with self.builtin_trap:
-> 2126                 result = fn(*args,**kwargs)
   2127             return result
   2128 

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\magics\pylab.py in matplotlib(self, line)

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\magics\pylab.py in matplotlib(self, line)
     78         """
     79         args = magic_arguments.parse_argstring(self.matplotlib, line)
---> 80         gui, backend = self.shell.enable_matplotlib(args.gui)
     81         self._show_matplotlib_backend(args.gui, backend)
     82 

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\interactiveshell.py in enable_matplotlib(self, gui)
   2929         """
   2930         from IPython.core import pylabtools as pt
-> 2931         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   2932 
   2933         if gui != 'inline':

C:\Users\Zurii\Anaconda\envs\py34\lib\site-packages\IPython\core\pylabtools.py in find_gui_and_backend(gui, gui_select)
    254     if gui and gui != 'auto':
    255         # select backend based on requested gui
--> 256         backend = backends[gui]
    257     else:
    258         # We need to read the backend from the original data structure, *not*

KeyError: 'nbagg'

**Comment by WeatherGod** [comment]
You might need to update ipython

**Comment by tacaswell** [comment]
You need ipython at least 2.4.1 iirc for the magic to work

**Comment by Zuriich** [comment]
Thanks for the extremely fast answer! It was that problem :)

2015-02-26 18:52 GMT+01:00 Thomas A Caswell <notifications@github.com>:
