### ISSUE TITLE
Make sure that Travis tests external links in docs, INSTALL, README etc.

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4205]
Avoid issues like the one fixed by #4204

**Comment by SidharthBansal** [comment]
Can we close this @tacaswell ?

**Comment by SidharthBansal** [comment]
Seems like duplicate issue of https://github.com/matplotlib/matplotlib/issues/5380

**Comment by timhoffm** [comment]
Thanks @SidharthBansal. Closing as duplicate of #5380.
