### ISSUE TITLE
eps export of rasterized grayscale images leads to compression artifacts

### ISSUE THREAD

**Issue by jaschau** [matplotlib/matplotlib#4207]
Dear all,

when exporting figures containing rasterized grayscale images to eps, the resulting files show strange compression artifacts when distillation with xpdf is used. In particular, the above problem occurs whenever imshow is used in conjunction with grayscale colormaps, which is a relevant use case. I could eventually solve this problem by adding the line

-dAutoFilterGrayImages=false -sGrayImageFilter=FlateEncode \

to the call to ps2pdf in line 1576 of backend/backend_ps.py. Currently, this set of parameters only gets used for color images, which leads to the inconsistent behavior with grayscale images described above. I would thus suggest to include this line per default in matplotlib. I am using matplotlib version 1.4.2. 
Best,

jaschau

**Comment by tacaswell** [comment]
Could you put in a pull request with that change?

**Comment by jaschau** [comment]
@tacaswell: I just opened a pull request #4208. Please let me know if I can be of further help.

**Comment by tacaswell** [comment]
Closed by #4208
