### ISSUE TITLE
add legend to error fill port / mlab.offset_line

### ISSUE THREAD

**Issue by dacoex** [matplotlib/matplotlib#4214]
According to
https://github.com/matplotlib/matplotlib/pull/1010
the errorfill from mpltools was ported over:
https://tonysyu.github.io/mpltools/auto_examples/special/plot_errorfill.html#example-special-plot-errorfill-py

But the legend is not created:

with mpl:
```
#using pure mpl
from pylab import *
x = linspace(0, 2*pi, num=100, endpoint=True)
y_sin = sin(x)

y_err = 0.2

y_minus, y_plus = mlab.offset_line(y, y_err)
plot(x, y, label='sin')
fill_between(x, y_minus, y2=y_plus, alpha=0.1, label='sin error')
#special.errorfill(x, y_sin, y_err, label='sin', label_fill='sin error')
legend()
show()
```
with mpltools

```
# using the mpltools
import numpy as np
import matplotlib.pyplot as plt
from mpltools import special

x = linspace(0, 2*pi, num=100, endpoint=True)
y_sin = sin(x)

y_err = 0.2

y_minus, y_plus = mlab.offset_line(y, y_err)
#plot(x, y, label='sin')
#fill_between(x, y_minus, y2=y_plus, alpha=0.1, label='sin error')
special.errorfill(x, y_sin, y_err, label='sin', label_fill='sin error')
legend()
show()
```

**Comment by dacoex** [comment]
OK, maybe this is the explanation why it's not possible:
http://matplotlib.1069221.n5.nabble.com/legends-with-fill-between-tt20830.html#a20831

**Comment by tacaswell** [comment]
I think this is added in current master (https://github.com/matplotlib/matplotlib/pull/3303)

See http://matplotlib.org/1.4.3/users/legend_guide.html#creating-artists-specifically-for-adding-to-the-legend-aka-proxy-artists how to do this in the current release.

**Comment by dacoex** [comment]
@tacaswell thanks. 
although the code of mpltools wraps this a little more convenient, I like that we can now use pure, mpl.
Beautiful. Thanks.
