### ISSUE TITLE
Cant install Matplolib

### ISSUE THREAD

**Issue by aruscher** [matplotlib/matplotlib#4216]
Hello guys,
i cant install matplotlib in a virtualenv using Python with pip.

Python Version: 3.4.3
Virtualenv Version: 1.11.6
Pip Version: 1.5.6
OS: Linux  3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
[Terminal Output](http://pastebin.com/v11aWth9)

**Comment by WeatherGod** [comment]
You might need to update your setuptools package.

**Comment by aruscher** [comment]
updated setuputils from 3.6 to 12.0 resolved this problem
