### ISSUE TITLE
Histograms in log-scale miss the "unity" bins

### ISSUE THREAD

**Issue by ycopin** [matplotlib/matplotlib#4242]
Take the following example, drawing an histogram with some "unity bins" with `yscale='log'`:
```python
import numpy as N
import matplotlib.pyplot as P

x = N.random.randn(1000)
fig, (ax1, ax2) = P.subplots(1, 2)

ax1.set_yscale('log')
ax1.hist(x, bins=100, histtype='stepfilled')
ax1.set_title("Automatic")

ax2.set_yscale('log')
ax2.hist(x, bins=100, histtype='stepfilled')
ymin, ymax = ax2.get_ylim()
ax2.set_ylim(ymin/2, ymax)
ax2.set_title("Tuned")

P.show()
```
This generates the following figure: 
![bug](https://cloud.githubusercontent.com/assets/812050/6709549/832e0066-cd7a-11e4-85cb-20bfac2db162.png)

The bug is that, in the left panel (default behavior), the `ymin` is set to 1=10^0, therefore *hidding* the unity bins (they are visible in the right panel where I tweaked the `ymin`). This is probably not a *strong* bug, but the resulting plot is misleading.

**Comment by tacaswell** [comment]
Auto-scaling with log seems to be a generically hard problem full of special cases.

It this case the ymin should probably be set to 'the largest decade strictly less than the smallest non-zero bin'.

**Comment by ycopin** [comment]
Sounds good, even though it will spoil some space on a basically useless decade (10^-1 to 10^0). Anywhere where I should look at and suggest changes?

I take for granted that a log-axis should by default only incoroporate an integer number of decades, right?

**Comment by tacaswell** [comment]
the `hist` function has a special cased 'log' code path, it should probably go in there.

`hist` also has a 'normalized' code path which will give floats for the bin heights so in general the space isn't wasted. 

And yes, the default should be an integer number of decades.

**Comment by ycopin** [comment]
Actually, using the `log` flag in `hist` already properly solves the current issue. The issue is therefore slightly more general, but maybe too specific. Feel free to close as 'wontfix', thanks for your help.

**Comment by tacaswell** [comment]
Great!  Glad to be of help.
