### ISSUE TITLE
ScalarFormatter does not use advanced formatting for scientific notation with PGF backend

### ISSUE THREAD

**Issue by EdwinChan** [matplotlib/matplotlib#4246]
`ScalarFormatter` uses the `text.usetex` rcparam to decide how it formats a number in scientific notation: with TeX on, the uglier 1e9 becomes the prettier ×10⁹. However, it does not check whether the PGF backend is used, which technically counts as a TeX backend. As a result, an image generated with the PGF backend has the uglier 1e9, even though the backend is fully capable of more advanced typesetting. It would therefore be desirable to include a check for the PGF backend wherever a check for `text.usetex` appears.

_(edit)_ P.S. `ScalarFormatter` is used as an example here, but it could be that similar changes can be applied across the board.

A minimal working example follows.

```
import numpy
import matplotlib
matplotlib.use('pgf')
# matplotlib.rcParams['text.usetex'] = True
from matplotlib import pyplot

pyplot.plot(numpy.linspace(0, 1) * 1e-9, numpy.linspace(0, 1) * 1e9)
pyplot.savefig('bug.pdf', transparent=True)
```

**Comment by tacaswell** [comment]
attn @pwuertz

**Comment by pwuertz** [comment]
As you described the pgf-backend (or any other backend for that matter) has no influence over the way a matplotlib astist element decides to draw itself to a canvas - which is probably a good idea and allows backends to be abstract and interchangable.

My understanding of the `text.usetex` parameter is that it controls whether LaTeX macros within text elements are processed by matplotlib itself or if the text is directly given to the backend as it is.
I don't think the parameter should implicitly affect the style for formatting numbers as `ScalarFormatter` does. Matplotlib ought to be capable of typesetting `$X \times 10^Y$` on its own, so there is no technical reason for forcing either the e-notation or the times-notation. Same goes for implicitly changing the minus sign within ticks when setting usetex on/off.

It should be possible to switch between the desired formatting styles using rc-settings regardless of the way latex code is being handled.

**Comment by QuLogic** [comment]
If you want to use fancier formatting, without invoking TeX, you can set the `axes.formatter.use_mathtext` rcParam to True. I agree with @pwuertz and don't think using specific backends should cause formatting to change.
