### ISSUE TITLE
dtype problems with record arrays

### ISSUE THREAD

**Issue by dns4861** [matplotlib/matplotlib#4253]
Hello,
it seems like the use of unicode literals in the names of records arrays causes problems with the record array operations in mlab that make use of the np.dtype() command.
While <code>np.dtype([(u'a',np.float),(u'b',np.float)])</code> produces an error <code>TypeError: data type not understood</code>, the form <code>np.dtype({'names':[u'a',u'b'],'formats':[np.float,np.float]})</code> seems to work.
For now I replaced the call to </code>np.dtype</code> in </code>mlab.py</code> by a function

```
def ddtype(dd):
        nn = [n[0] for n in dd]
        dt = [d[1] for d in dd]
        return np.dtype({'names':nn,'formats':dt})
```

which seems to work but this probably needs to be fixed at a deeper level.

**Comment by WeatherGod** [comment]
This isn't a matplotlib bug. This would seem to be a numpy bug, no?
Although, your work-around does make sense and seems harmless to update
mlab so that we remain compatible with older versions of numpy, I would
suggest filing a bug report with the numpy people as well.

**Comment by tacaswell** [comment]
Apparently a long standing one: https://github.com/numpy/numpy/issues/2407

**Comment by tacaswell** [comment]
punted as upstream fix required.

**Comment by anntzer** [comment]
Closed as I don't think we should bother working around numpy "bugs" (not really one, IMO) in the semi-unmaintained mlab and what's more for a Py2-only issue.
