### ISSUE TITLE
general colormap reverser

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#4271]
The reverse of the built-in colormaps can be easily accessed, but there isn't any straight-forward general way to produce a reversed colormap for an arbitrary colormap object.

See the discussion at the iris message board about this issue: https://groups.google.com/forum/#!topic/scitools-iris/biD6F6OG9Og

**Comment by chiragnagpal** [comment]
How about keeping the plot values negative and plotting ;)

**Comment by jonchar** [comment]
Is this still outstanding? If so, we're looking for a way to reverse an arbitrary colormap object rather than doing `np.flipud(colormap(x))` to just flip the RGBA values, correct?

**Comment by WeatherGod** [comment]
Correct. The flipud(colormap(x)) wouldn't work (that would just reverse the
order of the result which would not be a good thing because you have no
guarantee that the input data is sorted.

**Comment by kjartankg** [comment]
Alright, I've had a look at this and come up with two different solutions.

* Add a boolean `self._isReversed` into the base class `Colormap` and simply handle the reversing inside `__call__` by mapping i:[0..N] -> [N..0] and f:[0..1] -> [1..0] in an `if` block.

Pros | Cons
------ | -------
Simple to implement | Makes the `__call__` function more bloated
 | Underlying data stays the same, confusing if `__call__` is bypassed

* Make a function `reversed(self, name=None)` that reverses the data and returns a new instance.

Pros | Cons
------ | -------
Independent of current functions | Separate implementation for each derived class
Guaranties same as current behavior |

I'm leaning towards the second one and have therefore already implemented it. Now I'm reading up on how to do commits and pull request properly. If someone is in a mentoring mood...

**Comment by tacaswell** [comment]
Also :+1: on the second one
