### ISSUE TITLE
inset_axes does not work on top of imshow

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#4272]
I create overview plots of spectrograms, one as image, one as a profile through the middle point. 
I want to have an image histogram in the corner of the spectrogram, but it is not being drawn (also tried the workaround via
```python
data, _ = np.histogram(spec)
in_axes.plot(data)
```
but to no avail.
I attach 2 images, in the first the inset_axes histogram works fine on top of the profile plot, and in the 2nd I use the exact same code for the inset part on top of an axes that used `imshow` instead of `plot`, and the histogram does not show up.
![test_profile](https://cloud.githubusercontent.com/assets/69774/6816663/e9a2cd5a-d25b-11e4-904a-9fbe71f2423c.png)
![test_spec](https://cloud.githubusercontent.com/assets/69774/6816665/f3712980-d25b-11e4-8777-fa0c8c61bd89.png)

my system:
MPL: 1.4.3, using `nbagg` backend on IPython 3.0 

This is the code I am using for the inset:
```python
        # inset histogram
        if plot_hist:
            in_axes = inset_axes(ax, width="20%", height="20%",
                                 loc=2)
            in_axes.hist(spec.ravel(), bins=20, normed=True)
            plt.setp(in_axes.get_xticklabels(), visible=False)
            plt.setp(in_axes.get_yticklabels(), visible=False)
            in_axes.grid('off')
```

Using 'inline', the inset_axes even become transparent, see attached:

![test_spec2](https://cloud.githubusercontent.com/assets/69774/6816709/6472370a-d25c-11e4-8199-68f3f5b3fa0c.png)

**Comment by tacaswell** [comment]
What are the axis limits on the inset `axes`?

**Comment by michaelaye** [comment]
Sorry, false alarm. I had different data dealings for the spectrogram vs the profile: In the spectogram code I wanted the data to show logarithmized, but in the profile not. Taking the np.log10(spectrogram) brought the minimum of the data to -inf as there were some values = 0. That in turn made the histogram impossible (without extra precautions). Sorry for the noise.
