### ISSUE TITLE
matplotlib.rcParams['font.weight'] affects title, but not other plot elements

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [matplotlib/matplotlib#4279]
I have a script in which I did the following:

import matplotlib as mpl
mpl.rcParams['font.weight']= 'heavy'

This changed the font weight for the plot title, but did not affect the x-axis label, y-axis label, and plot annotations.

Phillip M. Feldman

**Comment by tacaswell** [comment]
The font properties of the label are controlled by the `axes.label*` set of rcparams.

Leaving this open for now to make sure it gets more visibility than just from me.

**Comment by pmfeldman** [comment]
Actually, I've been trying to find a solution for the following problem:
When I put a LaTex equation on a figure using `pyplot.text`, the equation
font is rather spidery, with the result that the equation is not legible
when the figure is displayed with a projector.  I've read everything that I
can find about customizing matplotlib, but haven't found anything that
seems applicable to this problem other than the global font change, which
didn't work.

Phillip

**Comment by tacaswell** [comment]
Please send question like that to the user mailing list (http://sourceforge.net/p/matplotlib/mailman/)  You may have to subscribe to be allowed to post.

**Comment by petehuang** [comment]
What's the action here? Maybe clarifying the rcParam `font.weight` into something more detailed?

**Comment by QuLogic** [comment]
Relating to the original problem:

> When I put a LaTex equation on a figure using pyplot.text, the equation
> font is rather spidery, with the result that the equation is not legible
> when the figure is displayed with a projector.

This is due to using Computer Modern for LaTeX, which wouldn't be affected by this rcParam, and probably needs to use the preamble to set a different font. However, if @pmfeldman really meant mathtext (without setting `text.usetex=True`), then we also used to use Computer Modern there as well. _However_, with 2.0, we will use DejaVu, so the math and normal text fonts should be pretty similar in weight when using that.

**Comment by basnijholt** [comment]
I am having the same problem, I use `text.usetex=True` and would like to make the font bold of my annotation, however using either `fontweight='bold'` or `fontdict={'weight': 'bold'}` doesn't change anything.

Does anybody found a solution?

**Comment by tacaswell** [comment]
@basnijholt if you use `text.usetex=True` then your text is shipped to LaTeX and almost all of our rcparams/configuration are ignored.

**Comment by dstansby** [comment]
@Phillip-M-Feldman or @basnijholt is this still a problem for you? If so would it be possible to post a simple self-contained example that illustrates the problem?

**Comment by Phillip-M-Feldman** [comment]
The attached script demonstrates the problem.  Note that the font.weight
setting affects only the axis tick labels.

Phillip

**Comment by basnijholt** [comment]
Attachments do not work on GitHub when sending emails, you'll have to post the whole script in the issue https://github.com/matplotlib/matplotlib/issues/4279.

**Comment by Phillip-M-Feldman** [comment]
"""
equation1.py


OVERVIEW

This Python script generates a plot using matplotlib.  x- and y-axis labels
are
formatted using 'mathtext'.  mathtext is less flexible than LaTex, and the
font,
which is somewhat spidery, may not be readable when displayed using a
projector.

The script demonstrates how to create a label containing an equation with a
Greek letter.


AUTHOR

Phillip M. Feldman
"""

import matplotlib
from matplotlib import pyplot
from numpy import linspace, pi, sin

matplotlib.rcParams['mathtext.fontset']= 'cm'

# The following setting appears to effect tick labels only:
matplotlib.rcParams['font.weight']= 'bold'

fig= pyplot.figure(figsize=[8,7], dpi=120, facecolor=[1,1,1])

x= linspace(0, 2*pi, 301)
pyplot.plot(x, sin( 2*pi*sin(x)), linewidth=2)

# The `y` parameter allows us to adjust the position of the y-axis label.
pyplot.title("Iterated Sine Function", y=1.04)

# Because of the backslashes, we need a raw string:
pyplot.xlabel(r'$x= \frac{x^2}{x}$')

# The \, inserts a small space.  See
#
https://en.wikibooks.org/wiki/LaTeX/Mathematics#Controlling_horizontal_spacing
pyplot.ylabel(r'$\sin(2 \pi\, \sin(x))$', fontsize=18)

pyplot.savefig('equation1.png', dpi=120)

pyplot.show()

**Comment by jklymak** [comment]
latex has its own way of making fonts bold.  Plus you are choosing computer modern for your math text font.  Its pretty spidery.  Suggest not changing the default, which looks a lot like the non math default and is much less spidery.  

I'm closing as this isn't really a bug...

https://stackoverflow.com/questions/14324477/bold-font-weight-for-latex-axes-label-in-matplotlib

**Comment by Phillip-M-Feldman** [comment]
Unless things have changed recently, without the change of the default, I
get output that is unreadable when printed.

**Comment by jklymak** [comment]
Hey, I even get the bold...

```python
import matplotlib
from matplotlib import pyplot
from numpy import linspace, pi, sin

matplotlib.rcParams['font.weight']= 'bold'

fig= pyplot.figure(figsize=[8,7], dpi=120, facecolor=[1,1,1])

x= linspace(0, 2*pi, 301)
pyplot.plot(x, sin( 2*pi*sin(x)), linewidth=2)
pyplot.title("Iterated Sine Function", y=1.04)
pyplot.xlabel(r'$x= \frac{x^2}{x}$')
pyplot.ylabel(r'$\sin(2 \pi\, \sin(x))$', fontsize=18)
pyplot.savefig('equation1.png', dpi=120)

pyplot.show()
```

![fig](https://user-images.githubusercontent.com/1562854/43281431-80802898-90c8-11e8-9c9c-a9d823e7eb13.png)

**Comment by jklymak** [comment]
If you are having trouble with the default fonts, make sure you have a reasonably modern matplotlib and if you still have trouble open a new issue.  Thanks!

**Comment by Phillip-M-Feldman** [comment]
OK.  I have to admit that this is also working for me.  The key is to not
specify a different font family.  Thanks!

**Comment by jklymak** [comment]
... though I note the title in the above is not bold 😬

**Comment by mojirml** [comment]
So is there an answer to this question？

**Comment by jklymak** [comment]
Maybe open a new issue?

**Comment by mojirml** [comment]
> Maybe open a new issue?

Thank you for your advice. I'll try
