### ISSUE TITLE
make_axes_locatable broken with imshow plots that specify an extent and an aspect ratio

### ISSUE THREAD

**Issue by ngoldbaum** [matplotlib/matplotlib#4282]
The following script and the image it produces illustrates the issue:

``` python

import numpy as np

from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

fig, ax = plt.subplots()

imax = ax.imshow(np.random.random((200, 200)), extent=[0, 100, 0, 1], aspect=100)

divider = make_axes_locatable(ax)

cax = divider.append_axes("right", size="5%", pad="2%")

cb = fig.colorbar(imax, cax=cax)
```

![image](https://cloud.githubusercontent.com/assets/3126246/6853080/fcb2b234-d3a5-11e4-8d3a-e346b43279c1.png)

As a workaround, I can produce the plot I'm looking for using ImageGrid:

``` python

import numpy as np

from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid

fig = plt.figure(1, (8, 4))

grid = ImageGrid(fig, 111, nrows_ncols = (1, 1), axes_pad=0.1, cbar_mode='single')

imax = grid[0].imshow(np.random.random((200, 200)), extent=[0, 100, 0, 1], aspect=100)

cax = grid.cbar_axes[0]

cb = fig.colorbar(imax, cax=cax)
```

![image](https://cloud.githubusercontent.com/assets/3126246/6853141/8ffc19f4-d3a6-11e4-8f08-1bc449717658.png)

I think this might be related to #3286.  Not sure if it's an out and out duplicate or just another symptom of the same basic issue with `make_axes_locatable`.

Some version info:

numpy 1.9.2
matplotlib 1.4.3
python 2.7.9

**Comment by tacaswell** [comment]
Looks like an issue in the order that various constraints are applied.  

Have a look at  `ax.set_adjustable` (http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.set_adjustable which needs better docs or http://stackoverflow.com/questions/4747051/matplotlib-subplots-with-fixed-aspect-ratio).

**Comment by newmrdenis** [comment]
I am experiencing the same bug right now with extent and aspect parameters, without which you can't create the heatmap. Try to perform my attempts, so, when you create a divider obj you settings falls off, and you obtain compressed picture.
Nothing from what you have suggested works i.e. ax.set_aspect and ax.set_adjustable do not work at all.

**Comment by tacaswell** [comment]
![so](https://user-images.githubusercontent.com/199813/231310022-9963c239-2eb2-4c8e-9a0e-2fb19d444255.png)

**Comment by tacaswell** [comment]
Given @jklymak comment I'm going to re-close this.
