### ISSUE TITLE
nbagg: Animation need "kick-off" when added from different notebook cell

### ISSUE THREAD

**Issue by aburgm** [matplotlib/matplotlib#4287]
When a figure is created in one notebook cell and shown by the nbagg backend, and then an animation is added in the next one, the animation does not start in the figure until it is "kicked off" by somehow interacting with the nbagg widget, for example starting to pan or zoom around.

I'm using matplotlib 1.4.3 with #4171 cherry-picked.

**Comment by aburgm** [comment]
Here's a notebook to reproduce: http://nbviewer.ipython.org/gist/aburgm/7ecac8c7835f4c5816b3

**Comment by WeatherGod** [comment]
In general, the animation objects are set up to trigger at the next call to
draw(). I haven't tried your notebook, but I bet adding a draw() call for
the original figure object after creating the animation would do the trick.

**Comment by aburgm** [comment]
Adding `plt.draw()` at the end does not cause the animation to run.

When the `%matplotlib nbagg` magic is active, there are not any show() or draw() calls involved at all, and so, naively, I wouldn't expect to need one in this case. (I just removed the `%matplotlib nbagg` in this notebook to be as close as possible to the original example)

**Comment by WeatherGod** [comment]
Right, I am not saying that you have to normally do the show() or the
draw(). In the nbagg backend, those things tend to be done automatically
for you. Somehow, the figure's "draw" event is not firing back to this
animation object. This might be a scope issue in the javascript.
