### ISSUE TITLE
nbagg scroll wheel / middle click button event

### ISSUE THREAD

**Issue by azjps** [matplotlib/matplotlib#4289]
On scroll wheel (middle) click for nbagg backend, the returned MouseEvent.button is 3 instead of 2, so middle and right clicks aren't distinguishable. For example try [UAT 16](http://nbviewer.ipython.org/github/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_uat.ipynb). This occurred for me on chrome with IPython 2.3.0 and matplotlib 1.4.3 / 1.5.dev1.

Would try to fix myself but I assume it'd be quicker for someone from [say this issue](https://github.com/matplotlib/matplotlib/issues/3963) to change the errant javascript / ipython / matplotlib / wherever code. :)

**Comment by tacaswell** [comment]
This looks like it is intentional to disable to context menu

See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_webagg_core.py#L296

**Comment by azjps** [comment]
Ah okay, that's a bit unexpected but understandable; right clicking doesn't open a context menu and registers correctly on the versions of chrome/firefox I was using. Maybe a note could be put in the [MouseEvent docstring](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py) about this special case? Thanks!

**Comment by tacaswell** [comment]
@azjps Could you put in a PR to do that?
