### ISSUE TITLE
undefined behavior of figure.add_subplot() once subplot is modified.

### ISSUE THREAD

**Issue by yannpaul** [matplotlib/matplotlib#429]
Modifying a subplot using `change_geometry()` method does not update the corresponding key for the subplot in the figure. So when you call `add_subplot()`, you need to call it with the original _args and *_kwargs not the modified ones, if you want to access the already existing subplot. 

This was identified in matplotlib version 0.99.1.1, but looking at the current code in github, it appears the same behavior exists.

**Comment by AeroEngy** [comment]
This issue doesn't seem to be fixed... Or it cropped back up since this one is pretty old.  See this stackoverflow link for an example.  http://stackoverflow.com/questions/31600726/matplotlib-add-subplot-change-geometry-bug
