### ISSUE TITLE
Annotation with negative axes fraction coordinate placed incorrectly with v1.4.3

### ISSUE THREAD

**Issue by Stretch97** [matplotlib/matplotlib#4292]
I am finding that annotations placed outside of axes get placed incorrectly in v1.4.3.  Here is an example:

    import matplotlib.pyplot as plt
    import matplotlib as mpl
    
    fig, ax = plt.subplots()
    
    ax.annotate('+ pts', 
        xytext = [40, 20], textcoords = 'axes points', \
        xy = [40, 20], xycoords = 'axes points', fontsize = 32)
    ax.annotate('- pts', 
        xytext = [40, -20], textcoords = 'axes points', \
        xy = [40, -20], xycoords = 'axes points', fontsize = 32)
    ax.annotate('+ frac', 
        xytext = [0.5, 0.1], textcoords = 'axes fraction', \
        xy = [0.5, 0.1], xycoords = 'axes fraction', fontsize = 32)
    ax.annotate('- frac', 
        xytext = [0.5, -0.1], textcoords = 'axes fraction', \
        xy = [0.5, -0.1], xycoords = 'axes fraction', fontsize = 32)
    plt.savefig('test' + mpl.__version__ + '.png')

In matplotlib v1.4.2 the plot looks like this:
![test1 4 2](https://cloud.githubusercontent.com/assets/4099759/6883289/4627552e-d56c-11e4-8518-543d4dee233e.png)

In matplotlib v1.4.3 the plot looks like this:
![test1 4 3](https://cloud.githubusercontent.com/assets/4099759/6883290/4d13ae3c-d56c-11e4-85f1-dd4b195dc9d6.png)

Apparently v1.4.3 takes a negative axes fraction (or points) and wraps it around to the top of the axes.

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/pull/4019  This is un-breaking something that was broken in 1.4.0.

**Comment by efiring** [comment]
The 4.3 behavior seems very odd, though.  Why would anyone want this behavior?  It seems inconsistent with every other case of positioning--does any other object positioning function do a wraparound like this?  It imposes unnecessary restrictions on where one can position annotations.

**Comment by Stretch97** [comment]
Yes, I agree with efiring.  I much prefer the v1.4.2 behavior.

I just tried out v1.3.1 and got the following plot:
![test1 3 1](https://cloud.githubusercontent.com/assets/4099759/6883425/38847b94-d572-11e4-981c-58cb1554886a.png)

The coordinates specified with axes points get wrapped around, while the coordinates specified with axes fractions behave as I would expect.

**Comment by tacaswell** [comment]
For reference, the original issue which triggered this 'fix' was https://github.com/matplotlib/matplotlib/issues/4012

Sorry, I was not careful about this twice.

**Comment by tacaswell** [comment]
I am also not sure what the best course of action here is.

I am in favor of rolling back to the 1.3.1 behavior for back-compatibility issues, but the asymmetry is annoying.

**Comment by efiring** [comment]
@tacaswell, I think this just points to the complexity of the code, and some uncertainty as to how it really should behave.
How about a more radical change: no wrapping at all.  If something like the wrapping behavior is needed, e.g. to make it easy to position with respect to the top instead of the bottom, then this should be specified via an additional kwarg, not via the sign of the offset.

**Comment by tacaswell** [comment]
I think I am ok with that.

Do we want to just revert #4019 for now and add the extra kwargs is later or try to do both now?

This does put us on track to have kwargs which are only sometimes used which is part of the problem with all of the FancyArrow/Box code.

How about putting the logic in the `textcoord` value, ex `'axes fraction invert-x' `?  This of course opens up a different world of pain (as now we are doing fancy parsing on string values) but we are already most of the way there.  

The other option I see is  `invert_x` and `invert_y` boolean kwargs, but I am having trouble making sense of what those would mean in data units (default to `None` and raise if non-none and data units?).

**Comment by Stretch97** [comment]
I am obviously not a lead matplotlib developer, but I thought I would put in my two cents as a user.  I don't see why you would want wrapping in 99 % of the cases.  IMHO, if a user wants wrapping behavior, they can easily implement it in their own code.

**Comment by tacaswell** [comment]
The compelling case is mostly for points based units.  Saying "I want the
Annotation to be 15 pixels from the right edge of the axes" is very
difficult without wrapping of some sort provided by the library (as you
don't know until draw time how big (in pixels) the axes or figure will be).

**Comment by Stretch97** [comment]
Hmm, I see.  Can't you get the axes size in normalized figure coordinates, and then use the figure size to figure out the physical size of the axes?  Perhaps you need a `draw()` somewhere in there…
 
Here is another thought.  The `OffsetFrom` class allows users to specify an annotation position as an offset from a reference point on an existing annotation.  What about allowing users to specify an annotation position as an offset from a reference point on a set of axes?

**Comment by efiring** [comment]
Exactly--what is needed is not wrapping, but an origin.  I think it would be enough to be able to specify origins as "SW", "SE", "NE", and "NW".  Positions would be signed offsets from those origins.  No wrapping at all.  No inversions.

**Comment by tacaswell** [comment]
@efiring I like that a lot better than either of my ideas.

**Comment by Stretch97** [comment]
What about specifying the origin in normalized axes coordinates?  That would combine the flexibility of the `OffsetFrom` class with the simplicity of just adding a kwarg to `annotate`.

**Comment by Stretch97** [comment]
@tacaswell You just sent out an email to the dev list asking if there are any issues that we would like to see tagged as "next release critical".  In my mind this is one of them.  The ability to specify an origin would be great, but if it turns out to be difficult to implement, would it be possible to just roll back the 1.4.2 annotation behavior?

**Comment by tacaswell** [comment]
Rolling back to the 1.4.2 behaviour is my current base-line for this and I
view as critical bug fix (I have just not built up the courage to dive back
into this code recently)

Can you create a new issue for adding the origin.  I am not sure you can't
currently get something like an arbitrary origin with enough use of
transforms.

**Comment by tacaswell** [comment]
Ok, so here is my understanding of what happened here.

For 1.4.0 I refactored annotations (https://github.com/matplotlib/matplotlib/pull/2351 ) but I missed that `{'axes points', 'axes pixel', 'figure points', 'figure pixel'}` were special cased to wrap.  Presumably from the function tame to maintain back compatibility.  This was an unintentional and undocumented API break.

This was noticed in https://github.com/matplotlib/matplotlib/issues/4012 and fixed in https://github.com/matplotlib/matplotlib/pull/4019 but that catches too many of the coordinate systems should not be _all_ things that start with `'axes'`) so fixed one API, but broke several others.

I see two reasonable courses of action:

 1. revert back to 1.4.2 behavior with nothing wrapping.
 2. revert back to 1.3.1 behavior with somethings wrapping.

I am inclined to go with option 1 and just accept the API break (and hope no one takes my commit rights away).

attn @efiring @Stretch97 @QuLogic @myshen

**Comment by efiring** [comment]
Agreed: best course of action for now is to eliminate wrapping.  That's good enough for this release.  It makes the behavior simpler and more predictable.  Then, with no time pressure, whoever is suitably inspired can put in a PR to add an origin kwarg.  The full Annotation and even Text API's are so complicated that I think we can be allowed a little breakage in the process of trying to fix bugs and get the code and APIs under control.  I took that point of view in #4178; for example, when eliminating the YAArrow code path I did not try to support every quirk and surprise of its behavior and API.

**Comment by Stretch97** [comment]
Option 1 works for me.

**Comment by myshen** [comment]
+1 option 1
+1 origin @tacaswell's [comment](https://github.com/matplotlib/matplotlib/issues/4292#issuecomment-87521429) is exactly the use case prompting my "fix".

**Comment by tacaswell** [comment]
It has dawned on me that there is a very easy way to implement an 'origin' as annotation already takes two positions (xy, xyann).  I think we can just allow the word 'offset' to be prefixed to any of the `textcoords` to mean 'use this unit relative to the xycoord'.  It doesn't seem too bad from the user side, not sure how hard it would be to do on the code side.

**Comment by efiring** [comment]
It might be a good idea--but the annotation API and code are already
so complicated and idiosyncratic that I think it would be a mistake to
make them even more complicated right now.  Actually, I probably don't
understand exactly what you are suggesting here.
