### ISSUE TITLE
Mathtext \left and \right with other delimiters (\Vert)

### ISSUE THREAD

**Issue by auxym** [matplotlib/matplotlib#4299]
I'm getting an issue similar to https://github.com/matplotlib/matplotlib/pull/715, except that delimiters such as `(`, `[` and `\{` work, but not others, particularly `\Vert`. Something like 

```python
ax.set_xlabel(r'$\left\Vert A \right\Vert$')
```
will crash with the same exception: `Expected a delimiter (at char 5), (line:1, col:6)`

Matplotlib 1.4.2 from debian sid repos

**Comment by tacaswell** [comment]
attn @md

**Comment by mdboom** [comment]
It's an easy enough fix.  According to the comprehensive LaTeX symbol list, `\vert` is just a synonym for `I` and `\Vert` for `\|` -- so we already have the symbols and the pieces -- they just need to be added to the parser.

**Comment by mdboom** [comment]
See #4300.
