### ISSUE TITLE
nbagg backend API incomplete?

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#4301]
I'm having a problem with some of seaborn's plots not showing the x/y coordinates for the nbagg backend, see here: https://github.com/mwaskom/seaborn/issues/495

The author of seaborn claims this to be a MPL problem. Will you now kick me back to him? ;)

**Comment by mdboom** [comment]
Doesn't seem to be nbagg-specific.  Same issue on GtkAgg and Qt4Agg -- that the coordinates displayed are `x= y=`.  Or is the issue something else?

**Comment by michaelaye** [comment]
I don't know which `qt` I get when I do `%matplotlib qt` but the coordinates are shown fine here for me.

Using this example code from `seaborn`:
```python
import seaborn as sns
sns.set()

flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")
flights = flights.reindex(flights_long.iloc[:12].month)

sns.heatmap(flights, annot=True, fmt="d")
```
and just leaving out the sns related plotting (but still importing sns just for the dataset):

```python
%matplotlib qt
import seaborn as sns

flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")
flights = flights.reindex(flights_long.iloc[:12].month)

plt.imshow(flights.values)
```
I get a QT window that is able to show the x/y coordinates.

![screenshot 2015-03-31 14 07 37](https://cloud.githubusercontent.com/assets/69774/6928132/4ced1e80-d7af-11e4-8f79-383ec66b02f6.png)

**Comment by tacaswell** [comment]
The reason `sns.heatmap` does not show the mouse over is due to https://github.com/mwaskom/seaborn/blob/master/seaborn/matrix.py#L172.  This is a seaborn bug, not a mpl bug.  

More detail at #4302 and https://github.com/mwaskom/seaborn/issues/495

**Comment by mwaskom** [comment]
Not to send pissy issues shooting back and forth at each other, but calling the use of `ax.set_xticklabels(xticklabels)` a "bug" perplexes me.

**Comment by michaelaye** [comment]
I don't think unprofessional language is helping anyone, so I unsubscribed from this.
