### ISSUE TITLE
Document installation with pip for Python3

### ISSUE THREAD

**Issue by krother** [matplotlib/matplotlib#4313]
I have struggled a bit to install matplotlib for Python3 in a virtualenv. It would be great to have a short explicit section in the installation docs or FAQ. I believe an explicit section would help those that prefer pip over apt-get.

Key points that solved the problem:
# Installing matplotlib for Python3 with pip
## 1. install pip3 and setuptools

```
sudo apt-get python-pip3
pip3 install --upgrade setuptools
```
## 2. install freetype

```
sudo apt-get install libfreetype6
sudo apt-get install libfreetype6-dev
```
## 3. install matplotlib

```
pip3 install matplotlib
```

I'd be happy to contribute to the text and create a pull request. Some comments what/where to add are highly appreciated.

**Comment by krother** [comment]
(all done on Ubuntu 14.04.1 LTS)

**Comment by tacaswell** [comment]
Edits should go against https://github.com/matplotlib/matplotlib/blob/master/INSTALL please.

**Comment by tacaswell** [comment]
@krother Any update on this?

**Comment by anntzer** [comment]
Arguably fixed as of master, as INSTALL.rst now includes
```
python -mpip install -U pip
python -mpip install -U matplotlib
```
and
```
It is easiest to use your system package manager to install the dependencies.

If you are on Debian/Ubuntu, you can get all the dependencies required to build Matplotlib with:

sudo apt-get build-dep python-matplotlib
If you are on Fedora, you can get all the dependencies required to build Matplotlib with:

sudo dnf builddep python-matplotlib
If you are on RedHat, you can get all the dependencies required to build Matplotlib by first installing yum-builddep and then running:

su -c "yum-builddep python-matplotlib"
These commands do not build Matplotlib, but instead get and install the build dependencies, which will make building from source easier.
```
