### ISSUE TITLE
Documentation table of contents doesn't go deep enough

### ISSUE THREAD

**Issue by mskoh52** [matplotlib/matplotlib#4319]
It would be much more convenient if the table of contents would include a few more levels of depth. For example, in

http://matplotlib.org/api/axes_api.html#matplotlib-axes

it would be very helpful to be have a clickable list of the names of the methods for the axes class in the sidebar on the right side of the page.

**Comment by tacaswell** [comment]
I think I found a fix for this: https://groups.google.com/forum/#!topic/sphinx-users/SqY5O0jM1JA working on sorting out if it actually helps.

**Comment by tacaswell** [comment]
It does not seem to :disappointed: This is out of my sphinx expertise, punting to next release.

**Comment by tacaswell** [comment]
It seems that the methods do not show up as a toc level as we currently generate them.

**Comment by dstansby** [comment]
https://matplotlib.org/api/axes_api.html has changed a bit recently; @mskoh52 do you think it's better now?

**Comment by mskoh52** [comment]
Wow, this looks really nice! Well done
