### ISSUE TITLE
Pyplot.imshow() "None" interpolation is not supported on Mac OSX

### ISSUE THREAD

**Issue by kennysong** [matplotlib/matplotlib#4320]
When passing in `interpolation='none'` to the `imshow()` function, I get the following error:

    /usr/local/lib/python2.7/site-packages/matplotlib/image.py:649: UserWarning: The backend (<class 'matplotlib.backends.backend_macosx.RendererMac'>) does not support interpolation='none'. The image will be interpolated with 'nearest` mode.

I'm on Mac OS X 10.10.3, Python 2.7.9. It seems strange that the no interpolation mode would not be supported here.

**Comment by tacaswell** [comment]
attn @mdehoon

**Comment by WeatherGod** [comment]
Interpolation 'none' is essentially the same thing as "nearest". The issue
is whether to let the native backend handle it ('none') or to have it taken
care of in AGG ('nearest'). The results are the same, although it tends to
be that the native backends can handle this more efficiently. I don't
remember why macosx backend wasn't set up to handle 'none', though.

**Comment by mdehoon** [comment]
I think this is fairly easy to solve, but I am having difficulty understanding what draw_image is supposed to do. If draw_image gets a transformation matrix, then why are the arguments dx, dy needed?

**Comment by WeatherGod** [comment]
I don't know. Maybe @mdboom knows?

**Comment by Stretch97** [comment]
I have at least one example where 'none' is not the same as 'nearest'.  Check out:
http://matplotlib.org/examples/images_contours_and_fields/interpolation_none_vs_nearest.html

**Comment by WeatherGod** [comment]
Ah, right. The PDF backend does treat them differently, I forgot about that.

**Comment by mdboom** [comment]
Fixed by #6178
