### ISSUE TITLE
clabel ticks and axes limits with eps zoom output 

### ISSUE THREAD

**Issue by ocehugo** [matplotlib/matplotlib#4321]
Hi, I'm having issues when saving figures in eps format with clabel and zoom/axis.

How to reproduce:

``` python
ff = np.zeros([20,20])
ff[10:15, 10:15] = 1
fig, ax = subplots()
cs = plt.contour(ff)
clabel(cs)
plt.axis((11, 14, 13, 14))  # or zoom
savefig('abc.png')
savefig('abc.eps') # look at top right corner

clabel(cs, inline_spacing=4)
clabel(cs, inline_spacing=4)
clabel(cs, inline_spacing=4)
clabel(cs, inline_spacing=4)
savefig('abc2.eps') # increase the number of ticks so ticks are spread outside axis
```

So the clabels that lies outside my current axis/zoom are being plotted in eps, while in png this is ommited ( expected).
the repeated clabel call are to increase the number of ticks outside the limits of the axis, so you get numbers lost outside the axis limits.

didn't attach the figures since github doint accept eps figures...

python 3.4
ipython (3.0.0)
matplotlib (1.4.3)
Plataform: OSX Yosemite/homebrew/pip

[TAC edited for markup and pep8]

**Comment by tacaswell** [comment]
Does it depend on the viewer you are using with the eps?

Something some where is not handling the clipping correctly.  In some cases, they should be done by the renderer and in come cases it should be done by mpl, not sure which one that it is here.

**Comment by ocehugo** [comment]
@tacaswell,

OSX preview (an automatic conversion from eps to pdf with osx libraries). Converting with brewed epspdf (0.6.1) to pdf also result in the same problem. GIMP 2.8.10 also import the image and show the problem/ticks.

**Comment by mefrazer** [comment]
I am having the same issue as ocehugo's original problem, and I really need to save my image in eps (as opposed to pdf) initially. Any solution?

**Comment by mefrazer** [comment]
After hours of troubleshooting, I found a solution that worked for me (I'm using a mac). I changed the backend to "macosx" (all the other backends I tried failed):
```
import matplotlib
matplotlib.use('macosx')
from matplotlib import pyplot as plt
```

**Comment by anntzer** [comment]
Turns out that's just because we're not setting clip paths on text elements in PostScript output at all, as can be seen with `text(0, .5, "foo", transform=gcf().transFigure, clip_on=True); savefig("/tmp/test.eps"); savefig("/tmp/test.png")`.  #18933 fixes this.

**Comment by mefrazer** [comment]
> Turns out that's just because we're not setting clip paths on text elements in PostScript output at all, as can be seen with `text(0, .5, "foo", transform=gcf().transFigure, clip_on=True); savefig("/tmp/test.eps"); savefig("/tmp/test.png")`. #18933 fixes this.

I'm confused as to how to implement the #18933 solution--could you clarify? Thanks!

**Comment by jklymak** [comment]
You would need to fetch @anntzer branch and then do a developers install on it. You can read more on our devdocs.  It's not terribly hard, but a bit of a pain.
