### ISSUE TITLE
FancyBboxPatch wrong size

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/matplotlib#4325]
Not sure what happens, but this should give me an arrow within the bounds of x=0.2 to 0.6, and y=0.2 to 0.5, any idea what goes wrong here?  Also the axes don't autoscale to include unless I add a plot (uncomment the line).

```python
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from matplotlib.collections import PatchCollection

fig, ax = plt.subplots()
patches = [FancyBboxPatch((0.2, 0.2), 0.4, 0.3, boxstyle='rarrow',fc='blue')]
p = PatchCollection(patches)

ax.add_collection(p)
#ax.plot([0,0.5])
plt.show()
```

**Comment by OceanWolf** [comment]
P.S.  I don't have the energy right now to look into this, maybe in a day or two, I just would like someone to confirm for my sanity that both these "problems" exist as bugs and not "intended features" :wink:,

**Comment by tacaswell** [comment]
None of the `add_*` calls trigger an auto-scaling, that is done by the higher level plotting functions (ex `plt.plot`).  That may be annoying, but it is at least known and intentional (autoscaling can be expensive, only do it explicitly).

As for the sizing, I am a bit unclear which units they are in.

**Comment by OceanWolf** [comment]
Okay, thanks for the explanation, re auto-scaling, still it seems a bit inconsistent behaviour to me, that with just the large arrow it doesn't scale, but add a plot (in this case smaller than the arrow) and then it does auto-scale to the arrow.  Why not just do it on the first draw of the canvas or have an array of bounds and every time something gets added, check to see if it overflows the min/max bounds?

About sizing, I have figured it out, I don't think a problem exists in the code, but I think we could improve the documentation.  I shall add it to my list...

**Comment by tacaswell** [comment]
in `plt.plot` it calls `self.autoscale_view(...)` which auto-scales to everything.

Having a check everytime is not a bad idea, but it would need to continue to respect the axes setting if autoscaling should happen or not.  That should be kept in mind for if/when we unify the way artists are handled.

**Comment by tacaswell** [comment]
Closing as this looks like it is not really a bug.
