### ISSUE TITLE
Rogue mathtext rendered spaces

### ISSUE THREAD

**Issue by ndevenish** [matplotlib/matplotlib#4333]
I'm aware that the built in mathtext rendered is not expected to be perfectly identical to tex, but I'm seeing some egregious behavior with spacing that I cannot seem to explain. With:

    import matplotlib.pyplot as plt
    plt.figure()
    plt.figtext(0.1, 0.9, r"1. ($a^2$)", size=20)
    plt.figtext(0.1, 0.8, r"2. $(a^2)$", size=20)
    plt.figtext(0.1, 0.7, r"3. $\left(a^2\right)$", size=20)
    plt.show()

In both 1.4.2 and a recent development version I get a rogue space before the bracket in all three cases:
![screen shot 2015-04-13 at 22 16 54](https://cloud.githubusercontent.com/assets/529963/7125674/d41b9d5c-e22a-11e4-94b2-f18a961f6bde.png)
Compared with turning `text.usetex` on:
![screen shot 2015-04-13 at 23 06 26](https://cloud.githubusercontent.com/assets/529963/7126530/cf0b00c6-e231-11e4-98cb-dd1aae47a9b2.png)

Using a negative space (`\!`) fixes the issue rendering with matplotlib, but screws up the latex output.

**Comment by tacaswell** [comment]
attn @mdboom Could this be related to the recent spacing changes?

**Comment by u55** [comment]
I get slightly more-reasonable whitespace after the exponent if I enclose the exponent in curly brackets.
```python
import matplotlib.pyplot as plt
s = 0.13
plt.figure(figsize=(3,2.5))
plt.figtext(0.1, 0.9-1*s, r"1a. ($a^2$)", size=20)
plt.figtext(0.1, 0.9-2*s, r"1b. ($a^{2}$)", size=20)
plt.figtext(0.1, 0.9-3*s, r"2a. $(a^2)$", size=20)
plt.figtext(0.1, 0.9-4*s, r"2b. $(a^{2})$", size=20)
plt.figtext(0.1, 0.9-5*s, r"3a. $\left(a^2\right)$", size=20)
plt.figtext(0.1, 0.9-6*s, r"3b. $\left(a^{2}\right)$", size=20)
plt.show()
```
![whitespace](https://cloud.githubusercontent.com/assets/8595627/7216614/aa27852c-e5d3-11e4-95da-2de0dcfb4994.png)

**Comment by jason-sachs** [comment]
another example:

    plt.text(0.2,0.5,"$d^2 \\leq K^2(q^2 - q_0^2)$",fontsize=30)

![image](https://cloud.githubusercontent.com/assets/10506541/7329623/193182b2-ea96-11e4-980c-ffd0a56223c5.png)

vs. MathJax `$d^2 \leq K^2(q^2 - q_0^2)$`

![image](https://cloud.githubusercontent.com/assets/10506541/7329629/2e21b156-ea96-11e4-939e-82f77ab64dd1.png)

**Comment by WeatherGod** [comment]
In that example, I would wonder if the kerning is being  turned off for
exponents, somehow.

**Comment by ndevenish** [comment]
That's an awful-looking example also - spacing screwed up next to the K and the contraction of the spacing in front of the q_0, along with the same spacing before the close bracket.

**Comment by zblz** [comment]
@ndevenish , @jason-sachs , @u55 : I have been finetuning the super/subscript spacing in mathtext in PR #4873, and applied a fix suggested by @mdboom to the symbol spacing in PR #4872. Applying these two PRs, the examples mention in this thread render like this:
![issue4333](https://cloud.githubusercontent.com/assets/576258/9134958/088a8fea-3d01-11e5-9388-879a496d7458.png)

It would be great if you could take a look and PR #4873 and make any comments you have on how the new script kerning works before it is merged. Thanks!

**Comment by jason-s** [comment]
>It would be great if you could take a look at PR #4873 and make any comments you have on how the new script kerning works before it is merged. 

Scanned it briefly. You've gone much more in depth than I have -- thanks, I trust your judgment!
