### ISSUE TITLE
Easiest way to limit clabel to current axis

### ISSUE THREAD

**Issue by ocehugo** [matplotlib/matplotlib#4336]
Hello devs,

can anyone point me out if there is an easy way to limit clabel ticks to only show up in the current axis!? Maybe something alike clabel(cs,axislimit=myaxislimit) ?

Say that you have a large contour, you zoom/axis over an area and want only that area to be clabeled based on your spacing settings...there is any easy way to do this ( except by subsetting your hole dataset!?)

If not, the way to do it is to search in cs.collections the path segmetns that lies inside my current axis and subset them and label them accordingly!? Any snipet around!?

cheers

**Comment by tacaswell** [comment]
This question is probably best handled by the mailing list (http://sourceforge.net/p/matplotlib/mailman/ to subscribe)  You will have to subscribe to post with out moderation.

**Comment by ocehugo** [comment]
sorry about that...

**Comment by tacaswell** [comment]
@ocehugo No worries!  More people will see your question on the mailing list which should get you a better answer.

Sorry my last message was terse.
