### ISSUE TITLE
inconsistent plotting behavier between x coordinate in number and dates

### ISSUE THREAD

**Issue by barpaum** [matplotlib/matplotlib#4339]
Hi,

I've found an inconsistent behavier for plotting between number coordinate and dates coordiante.
I don't know whether it's easy to fix or it's worthless.
Please see the code below:

Part 1: initialization
```python
from numpy import arange, sin
from matplotlib.pyplot import subplots, show
from matplotlib.dates import num2date
x=arange(0,10,0.1)
t=num2date(x+693596)
y=sin(x)
```
Part 2: plotting in numbers
```python
fig,ax=subplots()
ax.plot(None,None)
ax.plot(x,y)
show()
```

Part 3: plotting in dates
```python
fig,ax=subplots()
ax.plot(None,None)
ax.plot(t,y)
show()
```

Part 1 and Part 2 work well, but Part 3 got error of 
```
matplotlib/dates.py in _to_ordinalf(dt)
    195             dt -= delta
    196 
--> 197     base = float(dt.toordinal())
    198     if hasattr(dt, 'hour'):
    199         base += (dt.hour / HOURS_PER_DAY + dt.minute / MINUTES_PER_DAY +

AttributeError: 'NoneType' object has no attribute 'toordinal'
```

**Comment by tacaswell** [comment]
Why do you want to plot `None` vs `None`?  I think the issue here is that `ax.plot(None, None)` either does not not blow up or at least not add an artist to the canvas.  If you want to add an 'empty' line I suggest using `plt.polt([], [])`

**Comment by barpaum** [comment]
Yes, you are right. I just do not know which one is better solution for an 'empty' line. I've just made some tests, it seems [] is a more decent way to represent an empty line in matplotlib, for example the treatment inside matplotlib legend. Thanks for your suggestion.
I've written some script to represent empty entries as None, I will update them to [].

**Comment by tacaswell** [comment]
fixed by disallowing `None` to be passed for x or y in #4352
