### ISSUE TITLE
Feature: "default data point popups"

### ISSUE THREAD

**Issue by jondo** [matplotlib/matplotlib#4344]
Interactive (pan- and zoomable) plots (as e.g. in [WinPython](http://winpython.github.io/), which uses a Qt backend) should by default show a coordinate popup, when a data point is hovered, as e.g. in LibreOffice or Matlab.

Currently, this has to be manually programmed for each plot, e.g. by combining [this](http://stackoverflow.com/questions/6403153/data-value-at-each-marker) and [this](http://stackoverflow.com/questions/11537374/matplotlib-basemap-popup-box) method.

**Comment by tacaswell** [comment]
We has historically left such customization/specialization to downstream projects.  You should have a look at mpldatacursor (https://github.com/joferkington/mpldatacursor by @joferkington) which I think does what you want.

**Comment by jondo** [comment]
Thank you! It [seems to](https://github.com/joferkington/mpldatacursor/pull/19) need Python 3 compatibility, though.

**Comment by joferkington** [comment]
@jondo - ``mpldatacursor`` has had python 3 support for quite awhile. The pull request you linked to was broken and had many irrelevant commits, thus I've never merged it.  If you run into any python3 vs. python2 issues, please let me know!

**Comment by jondo** [comment]
@joferkington - thank you for the explanation, and sorry for the wrong impression I had. I am currently using Python 2.7, anyway.
