### ISSUE TITLE
Tick label padding on first y-axis changes when adding a second y-axis

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#4346]
When I have just the right set of commands, the tick label padding on the first y-axis changes when I add a second y-axis.  Here are my minimal working examples.

This set of commands

```
import matplotlib as mpl
import matplotlib.pyplot as plt

fig = plt.figure()
ax1 = plt.subplot()
ax1.plot(range(2),range(2))
ax1.yaxis.set_tick_params(which = 'major', direction = 'out', \
    labelsize = mpl.rcParams['font.size'], size = mpl.rcParams['ytick.major.size'])
fig.savefig('No_Issue1.png')
```

produces a figure that looks fine to me:
![no_issue1](https://cloud.githubusercontent.com/assets/4099759/7196376/f1ce5f28-e48d-11e4-80c1-dc09917c66af.png)

This set of commands,

```
fig = plt.figure()
ax1 = plt.subplot()
ax1.plot(range(2),range(2))
ax2 = ax1.twinx()
fig.savefig('No_Issue2.png')
```

also produces a figure that looks fine, even after adding a second y-axis:

![no_issue2](https://cloud.githubusercontent.com/assets/4099759/7196395/33c41076-e48e-11e4-9ef5-7f7a10cddc98.png)

This set of commands

```
fig = plt.figure()
ax1 = plt.subplot()
ax1.plot(range(2),range(2))
ax1.yaxis.set_tick_params(which = 'major', direction = 'out', \
    labelsize = mpl.rcParams['font.size'], size = mpl.rcParams['ytick.major.size'])
ax2 = ax1.twinx()
fig.savefig('Issue.png')
```

however, messes with the tick label padding on the first y-axis:

![issue](https://cloud.githubusercontent.com/assets/4099759/7196402/53ecd72a-e48e-11e4-89c8-261299cc72e7.png)

Apparently, the following commands

```
ax1.yaxis.set_tick_params(which = 'major', direction = 'out', \
    labelsize = mpl.rcParams['font.size'], size = mpl.rcParams['ytick.major.size'])
ax2 = ax1.twinx()
```

do not play nice together.

In case it matters, I am on matplotlib 1.4.0

**Comment by tacaswell** [comment]
If you reverse the order 

```python
fig = plt.figure()
ax1 = plt.subplot()
ax1.plot(range(2), range(2))
ax1.set_ylabel('y label')
ax2 = ax1.twinx()
ax1.yaxis.set_tick_params(which='major', labelsize=12, direction='out')
```

It works correctly.

@Stretch97 You seem to have a talent for finding really odd subtle bugs.

**Comment by Stretch97** [comment]
Talent?!  I think of it as a curse.  =)

Anyways, thanks for the temporary work around.

**Comment by yongzhez** [comment]
When debugging this, I noticed that autoscale_view when plot is called causes the problem. I'm on matplotlib 2.x branch and I get the following problem below.
![figure_1-1](https://cloud.githubusercontent.com/assets/6567068/13384800/38d8c6e6-de67-11e5-9525-a0c62f36426e.png)

This happens after the below code is called in autoscale_view:
` handle_single_axis(
            scalex, self._autoscaleXon, self._shared_x_axes,
            'intervalx', 'minposx', self.xaxis, self._xmargin,
            margins['left'], margins['right'], self.set_xbound)
        handle_single_axis(
            scaley, self._autoscaleYon, self._shared_y_axes,
            'intervaly', 'minposy', self.yaxis, self._ymargin,
            margins['bottom'], margins['top'], self.set_ybound)`

Is this is a new bug that popped up? if so, what would be considered a decent fix for autoscale_view?

**Comment by yongzhez** [comment]
I was wondering if auto_scale is actually even needed in plot. I managed to have the below graph just by removing it
![figure_1](https://cloud.githubusercontent.com/assets/6567068/13385158/a1e69a92-de6b-11e5-89dd-470325815093.png)

**Comment by tacaswell** [comment]
I think this is only working with out `autoscale_view` because the data limits are [0, 1], which also happen to be the default view limits. 

Autoscaling the limits (with the margins) is one of the big style changes for 2.0 so that functionality needs to remain.

It also looks like the last image you posted still shows the extra space between the tick labels and the ticks on the left axes.

**Comment by efiring** [comment]
I'm closing this because the original problem above seems to be gone now.  Reopen if I have misunderstood.  With
```python
fig = plt.figure()
ax1 = plt.subplot()
ax1.plot(range(2),range(2))
ax1.yaxis.set_tick_params(which = 'major', direction = 'out', \
    labelsize = mpl.rcParams['font.size'], size = mpl.rcParams['ytick.major.size'])
ax2 = ax1.twinx()
fig.savefig('Issue.png')
```
I get 
![issue](https://user-images.githubusercontent.com/85125/35427248-598785ec-020c-11e8-99fd-f485c4995b61.png)

**Comment by breedlun** [comment]
Yes, the problem does appear to be gone.  Thank you to whomever inadvertently solved it!
