### ISSUE TITLE
SVG backend is assigning same id to clipPath elements

### ISSUE THREAD

**Issue by rsmith31415** [matplotlib/matplotlib#4349]
@moble originally [reported](https://github.com/ipython/ipython/issues/8133) the following bug in the ipython repository, but it is related to the manipulation of SVGs in matplotlib:

If you create a simple HTML file with a couple of SVG elements:

```
<svg width="120" height="120"
     viewPort="0 0 120 120" version="1.1"
     xmlns="http://www.w3.org/2000/svg">

    <defs>
        <clipPath id="myClip" >
            <rect x="0" y="0" width="97" height="97" />
        </clipPath>
    </defs>
    <g clip-path="url(#myClip)">
        <rect x="0" y="0" width="100" height="100" fill="blue" />
        <circle cx="97" cy="50" r="5" fill="red"/> 
    </g>
</svg>


<svg width="120" height="120"
     viewPort="0 0 120 120" version="1.1"
     xmlns="http://www.w3.org/2000/svg">

    <defs>
        <clipPath id="myClip" >
            <rect x="0" y="0" width="97" height="97" />
        </clipPath>
    </defs>
    <g clip-path="url(#myClip)">
        <rect x="0" y="0" width="100" height="100" fill="blue" />
        <circle cx="97" cy="50" r="5" fill="red"/> 
    </g>
</svg>
```

and then using the developer tools in Chrome, you delete one of the images and zoom in (or zoom out), the remaining image has a problem with the clipping paths:

Before deleting image:

![alt text](https://cloud.githubusercontent.com/assets/599274/6991707/014b40b4-da62-11e4-98c1-db6eb41f0828.png)

After deleting image and zooming in:

![alt text](https://cloud.githubusercontent.com/assets/599274/6991708/08c80d2c-da62-11e4-80ad-584bf38ed6c3.png)

The reason is that both figures share the same `id` attribute in their `clipPath`  elements. This is the same issue that @moble found after plotting a couple of matplotlib figures and then removing or hiding one of them. Matplotlib currently assign the same `id` to their `clipPath` elements for figures that have the same content in its [_make_id](https://github.com/matplotlib/matplotlib/blob/481d8202746010b993c07c644ac448d52968f191/lib/matplotlib/backends/backend_svg.py#L310) method and this causes tricky bugs in the browser.

Essentially, Firefox and Chrome behave differently depending on the complexity of the figure but this can be solved by assigning different ids to the `clipPath` elements in matplotlib (which is good practice anyway.) 

I was suggesting to add a random value before generating ids (but maybe your tests are relying on the current behavior in some way).

**Comment by tacaswell** [comment]
Why is not re-using clip paths good practice?  I would naively have thought that reusing them (which reduces file size) would be good practice.

**Comment by WeatherGod** [comment]
Isn't this more like a namespace collision issue? The files by themselves
are fine, but when both appear in the same document, the ids collide?

**Comment by rsmith31415** [comment]
@WeatherGod I would phrase it this way: Figures with the same content share the same id, so if you have two or more figures with the same content in the same document, then you're going to have the issue described previously.

On the contrary, if you have two figures with different content (e.g. histogram and bar plot), they won't share the same ids and the issue will be avoided even if they are in the same document.
