### ISSUE TITLE
Different text extents with different backends

### ISSUE THREAD

**Issue by jakobgager** [matplotlib/matplotlib#4368]
There seems to be some issue with the line space or text size handling of the individual backends.
If you take this snippet

``` python
import matplotlib.pyplot as plt
def plotit(ba):
    f,a = plt.subplots(1,1)
    t1=a.text(0,0.1,'\nLine '.join(map(str,range(10))), fontsize=15)
    t1.set_linespacing(1.5)
    plt.savefig('test_{0}.pdf'.format(ba))
```

You get the following figures:
### nbagg output (directly from the notebook)

``` python
%matplotlib nbagg
plotit('nbagg')
```

![test_nbagg_live](https://cloud.githubusercontent.com/assets/1677740/7267960/8f91574a-e8c3-11e4-87b0-26ce7f359ebf.png)
### inline output (directly from the notebook)

``` python
%matplotlib inline
plotit('inline')
```

![test_inline_live](https://cloud.githubusercontent.com/assets/1677740/7267964/9e97d1ba-e8c3-11e4-8782-11ef0b5d68d8.png)
### savefig pdf

equal for nbagg and inline
![image](https://cloud.githubusercontent.com/assets/1677740/7267974/bfc24528-e8c3-11e4-9e5c-a145f9350af6.png)

As can be clearly seen, the extent of the text varies significantly. Please ignore the different image sizes. All figures are created using default rcs and in one single IPython session using matplotlib 1.4.3 on win7.

Is there a way to get identical results in nbagg and the saved pdf?

**Comment by tacaswell** [comment]
The pdf backend outputs vector graphics (that is it says 'put this text with this font at this place') so is dependent on the viewer so making the pdf pixel for pixel match the agg out put is probably impossible.

I am a bit more distressed by the difference between the nbagg and inline images (as those are both backend by agg).

I am also a bit confused by your script, are you _always_ saving a pdf or are you saving pngs and pdfs?

**Comment by jakobgager** [comment]
I'm always saving a pdf, just to check if these are equal. The inline and the nbagg images posted above are taken directly from the notebook (and not from savefig('img.png')). 
However, if I compare the images from savefig('img.png), nbagg and inline produce the same images, so your concern is not really met, and agg works as expected.
It seems, that the difference present in the notebook is somewhere to be found in the show() routine with the nbagg backend?

**Comment by Tillsten** [comment]
Note that saving pictueres in the notebook leads to differences because ipyhton changes some relevant rcParams.

**Comment by tacaswell** [comment]
@jakobgager Sorry, I am being dense.  All three of the images you posted above are different, labeling them A-C

 - A :: screen capture (?) or hitting s-key or killing the figure + save-as from nbagg
 - B :: right-click save-as from inline
 - C :: pdf converted to png some how

In all cases the pdf is the same (as it should be as the way figures get saved is that their canvas gets swapped out and more-or-less draw is called on them with the new canvas and then the figure is restored to as-it-was at the end of the save).

**Comment by jakobgager** [comment]
You are absolutely right.
* nbagg: kill figure + right click save-as (a screenshot of the active figure would yield the same result)
* inline: right click save-as
* pdf: screenshot form acroread
