### ISSUE TITLE
LaTeX and PGF preambles do not allow commas

### ISSUE THREAD

**Issue by EdwinChan** [matplotlib/matplotlib#4371]
I understand `latex.preamble` and `pgf.preamble` are not officially-supported features, but I believe the fact that commas cannot be used in them is enough of a showstopper to warrant a bug report.

Let me demonstrate by the following contrived example:

```
>>> import matplotlib
>>> matplotlib.rcParams['pgf.preamble'] = r'\macro[option1,option2]{arg}'
>>> matplotlib.rcParams['pgf.preamble']
['\\macro[option1', 'option2]{arg}']
```

As you can see, the command is incorrectly split up into two. Someone might want to supply their list of packages as `\usepackage{bm},\usepackage{euler}`, but I see no advantage to that as LaTeX is perfectly happy with `\usepackage{bm}\usepackage{euler}`, sans comma. The bigger problem is that `matplotlib` splitting the preamble at commas makes it impossible to choose a font in PGF/XeTeX, since one is often required to identify font variants in a comma-separated list if XeTeX cannot locate them:

```
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\setmainfont{texgyretermes}[
  Extension      = .otf,
  UprightFont    = *-regular,
  BoldFont       = *-bold,
  ItalicFont     = *-italic,
  BoldItalicFont = *-bolditalic]
\usepackage{amsmath,unicode-math}
\setmathfont[Extension=.otf]{texgyretermes-math}
```

At this moment I'm not aware of a method to separate `\setmainfont` into multiple commands. In a pinch, I can write

```
dict.__setitem__(matplotlib.rcParams, 'pgf.preamble', r'\macro[option1,option2]{arg}')
```

but this is certainly undesirable.

**Comment by jenshnielsen** [comment]
The problem is that the preambles are forced to be a string list which splits on ,  see validate_stringlist in rcsetup.py 

It is not clear to me what the best solution is.

**Comment by EdwinChan** [comment]
But certainly not all property values should be comma-separated lists? The authors may disagree, but I'd think such 'post-processing' should depend on the property, e.g. `font.serif` is clearly a list of names, but `latex.preamble` is not and therefore should not be comma-split.

**Comment by jenshnielsen** [comment]
And neither are they. There are various types of configurations and perhaps the solution is to change the type latex preample and friends but at the moment the code expects a list of lines for the preamble so either that needs to change or we should use a different way of representing a list in the rcparams file


Looking at http://matplotlib.org/users/customizing.html 

> # preamble is a comma separated list of LaTeX statements
> # that are included in the LaTeX document preamble.

**Comment by tacaswell** [comment]
Well, this gets us into an interesting problem as there is _no_ character we can pick to split on with out trying to parse and understand the pre-amble and I am not sure we want to start doing that. 

Switching the split charater is a huge api break so we can not do that.

@mdboom Can we re-purpose the parsing logic in mathtex to split these strings smartly?

**Comment by pwuertz** [comment]
`validate_stringlist` does also recognize list type input. In this case no parsing is required and your preamble is passed on unharmed:
```
>>> import matplotlib
>>> matplotlib.rcParams['pgf.preamble'] = [r'\macro[option1,option2]{arg}']
>>> matplotlib.rcParams['pgf.preamble']
[u'\\macro[option1,option2]{arg}']
```
So currently the rc-file syntax doesn't allow more complex latex preamble definitions, but you can always configure them from within the python interpreter. One could think of a specialized `validate_stringlist_for_latex` rc parser, but I don't think there is an urgent need for that.

**Comment by ArchangeGabriel** [comment]
This issue hits me a lot. Currently, I have to add this block in every thing I use for doing figures:
```
matplotlib.rcParams['pgf.preamble'] = [
    r"\usepackage{nicefrac}",
    r"\usepackage{fontspec}",
    r"\defaultfontfeatures[EBGaramond12]{Ligatures=TeX,Numbers={Lining,Monospaced,Proportional},Contextuals=NoAlternate}",
    r"\setmainfont[",
    r"Extension   = .otf,",
    r"UprightFont = *-Regular,",
    r"ItalicFont  = *-Italic,",
    r"BoldFont    = {AGaramondPro_Semibold.otf},",
    r"BoldItalicFont={AGaramondPro_SemiboldItalic.otf}",
    r"]{EBGaramond12}",
    r"\usepackage[math-style=upright]{unicode-math}",  # unicode math setup
    r"\setmathfont[Scale=MatchLowercase]{euler.otf}",
    r"\setmathfont[Scale=MatchLowercase,range=\star]{latinmodern-math.otf}",
]
```

Because I couldn’t find a way to make it work in an rc file. Was going to open an issue but found this one instead.

**Comment by pwuertz** [comment]
@ArchangeGabriel Right, copy&pasting such a block to every file for creating a coherent look for all figures really sucks. Maybe a separate .py file you can import in your figure scripts is an option for you? In my thesis I used such a file for setting up data sources, utility functions and matplotlib customization for all figures alike.

Of course this may be a viable solution for project based figure settings, if you want this as a global matplotlib default it seems we are out of luck since the rc-file syntax just won't allow it.

**Comment by ArchangeGabriel** [comment]
I use this in a lot of different contexts, including my thesis, teaching material, a book I’m writing…

But the .py file is a good workaround anyway, I’ll just add it to my path so that I can reach it from the different projects. It would be less clean than a nice `plt.style.use('pgf')`, but should work.

**Comment by ArchangeGabriel** [comment]
I’ve just found the [above linked PR](https://github.com/matplotlib/matplotlib/pull/12674) while looking at 3.1 release notes. Looks like it’s finally fixed!

**Comment by tacaswell** [comment]
This is indeed allowed in 3.1 (of which there is now an rc for!)
