### ISSUE TITLE
for the root example page, please provide more description

### ISSUE THREAD

**Issue by jason-sachs** [matplotlib/matplotlib#4379]
The [examples](http://matplotlib.org/1.4.3/examples/index.html) page is great, but it contains dozens (hundreds?) of example filenames with no description of what they do other than the name of the file and which category it is in. If you are browsing to see different examples of particular features, the name alone isn't helpful enough... is there a way to add a brief description?

**Comment by jenshnielsen** [comment]
The examples could clearly need some work but i'm not sure that adding more test to that page is the best way forward. It is already way to big. The main problem as I see it is that there are way to many examples in the pylab and api categories. They should be rewritten and moved to more meaning full categories.

Perhaps it makes more sense to add descriptions to the individual categories and make them expandable on that page. 

Please see http://matplotlib.org/devdocs/devel/MEP/MEP12.html for existing suggestions on improvements to examples. Completely reworking the examples is a lot of work so any pull requests that start to tackle single examples as suggested in MEP12 are greatly appreciated.

**Comment by petehuang** [comment]
MEP12-compliant example work is being tracked at #7206 - let's see what the outcome of that is and revisit this

**Comment by QuLogic** [comment]
With sphinx-gallery, there's a tooltip showing the first line or so of description. I think that will basically cover this once it's out.
