### ISSUE TITLE
use new binary comm in nbagg 

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4382]
A recent PR (https://github.com/ipython/ipython/pull/7757) into IPython adds binary comms so that we do not have to launder pngs through a base64 encoding to communicate with the JS side.

We should look into using the binary comms to see if we can get a bit more performance out of nbagg.

Not sure on what timeline we should aim for here as this is not in a released version of IPython/Jupyter (as of 2015-04).

attn @pelson

**Comment by OceanWolf** [comment]
This *may* have a slight effect on MEP27, I didn't touch binary comms directly in WebAgg, but I made a new wrapper around it.  That said, I have yet to touch NbAgg, so I have no clue how that works compared with WebAgg.  Anyway, I will make WebAgg my first priority after the base MEP27 branch lands.

**Comment by pelson** [comment]
Thanks @tacaswell - yes, this looks really interesting. :+1:
