### ISSUE TITLE
Windows installer does not run -> restarts itself continually

### ISSUE THREAD

**Issue by schlamar** [matplotlib/matplotlib#4389]
I cannot run the Windows installer with my non-admin account under Windows 7. The installer restarts itself continually:

![mpl_install](https://cloud.githubusercontent.com/assets/238652/7367675/7c2fa8a4-eda1-11e4-9928-35f59abe0dee.png)

I have UAC disabled. Installation works from an admin account. 

Other installers (numpy, pyparsing) work fine.

**Comment by schlamar** [comment]
Checked the 1.4.2 installer, too. Same issue.

**Comment by WeatherGod** [comment]
Just to make absolute certain, exactly where did you obtain the installer?
I take it that there isn't any error messages?

IIRC, doesn't Windows try to restart failing applications? That might
explain that part of the behavior...

**Comment by tacaswell** [comment]
attn @jbmohler @cgohlke

**Comment by schlamar** [comment]
1.4.3 from PyPI and 1.4.2 from Sourceforge. You can see in the screenshot that the process actually restarts itself.

My best guess is that this is some sort of failing elevation routine, something like this: http://stackoverflow.com/a/11746382/851737

**Comment by janschulz** [comment]
When I used the installers, I never saw such a behaviour.

**Comment by schlamar** [comment]
We have wheels now -> closing.
