### ISSUE TITLE
What is the real correct function name? 

### ISSUE THREAD

**Issue by staticor** [matplotlib/matplotlib#4392]
I want to add a subtitle in my figure.
In the doc I found there have **subtitle()** and **suptitle**, 

only later on can be used in  fig.xxx().

**Comment by tacaswell** [comment]
Can you please direct questions like this to the mailing list (see http://sourceforge.net/p/matplotlib/mailman/, you will have to subscribe to post) or to stackoverflow.com ?

We tend to use gh issues more for bug reports/feature requests and less for usage questions.  The mailing list and SO have much broader audiences which will increase the chances of your question getting answered.
