### ISSUE TITLE
document all rcaparams

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4394]
Each rcparam should be documented with a series of example like

``` python

with rccontext({param: val}):
    plt.plot(...)

```

This probably needs a more js front end on the website to deal with the large number of examples this will generate.

**Comment by timhoffm** [comment]
I propose to close this. This would be very tedious and a single plot does not even help. We'd need two plots to illustrate what actually changed. A good textual description should get us a long way (c.f. #26088) on moving us towards that.
