### ISSUE TITLE
Setting annotation background covers arrow

### ISSUE THREAD

**Issue by ndevenish** [matplotlib/matplotlib#4400]
Setting a background on the annotation covers the arrow also. This didn't happen in 1.4.2. I've been using it to separate the text from any plot data points in cases where they overlap. Resolvable for now by redrawing an empty annotation with an arrow.

Pre 1.4.2:
![screen shot 2015-05-03 at 15 06 58](https://cloud.githubusercontent.com/assets/529963/7445352/c6d0efa4-f1a6-11e4-9a7b-bc49dfef575f.png)
Current:
![screen shot 2015-05-03 at 15 03 21](https://cloud.githubusercontent.com/assets/529963/7445358/e821336c-f1a6-11e4-987b-f638ebb67cef.png)
Example code:

    import matplotlib.pyplot as plt
    import numpy
    a = numpy.zeros(100)
    a[::2] = 1
    plt.figure(figsize=(5.9,4.4))
    plt.plot(a)
    shared_args = {"xytext":(-15,0), "va":'center', "ha":"right", "textcoords":'offset points', "arrowprops":{"arrowstyle": "->"}}
    plt.annotate("Test", xy=(20,0.5), **shared_args)
    plt.annotate("Test", xy=(20,0.4), backgroundcolor="w", **shared_args)
    plt.show()
And the actual introducing commit, in the middle of what appears to be other restructuring https://github.com/matplotlib/matplotlib/commit/9d1c876e65e38b7596df68768a09baf9fcdb5916

**Comment by tacaswell** [comment]
Suspect that this is related to #4139 #4140 and #4178.

@efiring took a look at these issues and I have been avoiding looking into these issues as this code is more than a bit hairy.

**Comment by ndevenish** [comment]
Hmm, yes it is very closely related to #4139 - the root cause is the same, but with an extra ordering issue in this one.

**Comment by tacaswell** [comment]
![so](https://cloud.githubusercontent.com/assets/199813/13932223/6f0112f6-ef7d-11e5-9b1c-8c039dbff58f.png)

This appears to be fixed, have not done forensics to sort out by what.
