### ISSUE TITLE
Automatically setting agg.path.chunksize?

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4404]
I just realized that agg backends can throw an OverflowError when dealing with large datasets (in `draw_path`, `self._renderer.draw_path` throws OverflowError).  I wonder if it would be a good idea to automatically set `nmax` (i.e., the `agg.path.chunksize` config param) to a larger value and retry the plot.

**Comment by tacaswell** [comment]
I am not a huge fan of adaptive magic like that.

@efiring It looks like you added this feature in 2008, thoughts?

**Comment by efiring** [comment]
The chunking is disabled by the default value (0) of `agg.path.chunksize`.   There are other conditions on the chunking; it works only for simple lines.  I suspect it hasn't been used in many years.  Path simplification handles most of the cases where it would have been needed.  It's not clear to me that there is any point in keeping it.

**Comment by tacaswell** [comment]
@anntzer Do you have an example where this has actually been a problem?

**Comment by anntzer** [comment]
Basically the same as the ones mentioned by @efiring in #4464, i.e. plotting very long lines.
