### ISSUE TITLE
FancyArrowPatch misinterprets keyword for horizontal alignment

### ISSUE THREAD

**Issue by qleo** [matplotlib/matplotlib#4405]
It seems there is a problem with pyplot.annotate: when using FancyArrowPatch, the keyword "horizontalalignment" (or "ha") is not interpreted properly: Instead of aligning the text with respect to the end of the arrow, the arrow itself is tilted in an unwanted way. Please see the following demo code / graphics.

    import numpy as np
    from matplotlib import pyplot as plt
    
    plt.plot(np.arange(10),np.arange(10))
    
    plt.annotate(
	    'YAArrow',
	    xy=(1, 1),
    	    xytext=(1, 3),
	    arrowprops=dict(headwidth=0, frac=0, width=0.3, linewidth=0.3),
	    ha='left', color='b')
    
    plt.annotate(
	    'FancyArrowPatch',
	    xy=(3, 3),
	    xytext=(3, 5),
	    arrowprops=dict(arrowstyle='-', linewidth=0.3),
	    ha='left', color='b')```

![annotate_problem](https://cloud.githubusercontent.com/assets/12253033/7473175/5efe7010-f339-11e4-9d77-d9429080a3ce.png)

**Comment by tacaswell** [comment]
This is the intended behavior of the `FancyArrowPatch` which draws an arrow to the center of the text and then clips the arrow to the bounding box of the text.  If you want to connect to the bottom left corner of the text

```
plt.annotate(
    'FancyArrowPatch',
    xy=(3, 3),
    xytext=(3, 5),
    arrowprops=dict(arrowstyle='-', linewidth=0.3, relpos=(0, 0)),
    ha='left', color='b')
```

will do what you want.

 This is documented (tersely) here http://matplotlib.org/api/text_api.html#matplotlib.text.Annotation

**Comment by qleo** [comment]
In that case: sorry for the ruckus and thanks for the clarification.

**Comment by tacaswell** [comment]
No worries, it took me 10-15 minutes to track this down so it is clearly a documentation failure on our side.

As a whole the annotation/arrow API is very confusing.
