### ISSUE TITLE
Regression in maximum path size

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4407]
With matplotlib 1.4.3 it is possible to draw at least a random time series of 70,000 points on the Qt4Agg backend:
```
$ python -c 'import numpy as np; from matplotlib import pyplot as plt; plt.plot(np.random.rand(70000)); plt.show()'
```
With the current HEAD, an OverflowError is thrown:
```
OverflowError: In draw_path: Exceeded cell block limit
```
Perhaps it's just a transient regression, but I didn't see it mentioned anywhere.

**Comment by WeatherGod** [comment]
This sounds very familiar, but I could have sworn it was something to do
with the macosx backend and old limitations of quartz.

**Comment by efiring** [comment]
It seems odd that 1.4.3 and master are behaving differently; I think that with path simplification, both should be able to handle the test case.

**Comment by mdboom** [comment]
Do you have any rcParams in effect (in your matplotlibrc for example)?

**Comment by mdboom** [comment]
This may have to do with "upgrading" to Agg-svn from Agg-2.4.

**Comment by anntzer** [comment]
I thought both would pick up the same matplotlibrc anyways but just to be sure I removed it, and see the same difference.

**Comment by mdboom** [comment]
See #4408.
