### ISSUE TITLE
Curves, line & axis parameter editor has poor support for colors

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4410]
```
In [1]: plot([1, 2], color=(.75, .25, .25)) # <- normal reddish color
```
Select the parameter editor (green tick) and directly click ok.  The line becomes black.  In fact, if you check the Curves panel, the color editor gives `#000000` as color.  A quick look at `formlayout.py` shows that `to_qcolor` simply casts the `color` attribute to a string (so `"(0.75, 0.25, 0.25)"` in our case) and parses it as hex, giving up and returning black if it doesn't look like a hex RGB.

**Comment by tacaswell** [comment]
This should also be fixed in #4411
