### ISSUE TITLE
clabel support for manual singleton levels

### ISSUE THREAD

**Issue by ocehugo** [matplotlib/matplotlib#4412]

**Comment by ocehugo** [comment]
sorr ya bout that...i made a terrible mistake heheh

**Comment by ocehugo** [comment]
I'm trying to do a plot with a unique clabel tick in each line. Currently the clabel manual keyword only accept a tuple iterable and so when requesting a clabel over a line, its required 2 positions.

``` 
clabel(cs,[lineval],manual=((10,10),(10,10))
 ```

But this command cause the ticks to be too close if linespacing is small. An alternative is 
```
clabel(cs,[lineval],manual=((0,0),(10,10))
```

but this also creates a undesired tick.

Currently I'm setting the alpha of the second tick to 0.0 so I only got 1 tick showing up, but I believe that clabel should accept one manual single point. ( should be just an if with two and/or comparison instead of generating an error because a single tuple is not iterable).

**Comment by tacaswell** [comment]
Does ((10, 10), ) work?

**Comment by ocehugo** [comment]
I'm feeling embarrassed now @tacaswell. I was sure in my mind that I did that test, but now it works hehe. thanks again.

**Comment by tacaswell** [comment]
No problem. In the future please send questions like this to the mailing
list.
