### ISSUE TITLE
add `pyav` based movie writer

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4416]
There is now a cython based wrapper for ffmpeg (https://github.com/mikeboers/PyAV) which allows API access to the underlying library.   The project seems to be stabilizing and there are now conda recipes for both linux and OSX, wheels for OSX, and reports of it building on windows.

We should add a movie writer based on shoving images 

See https://github.com/scikit-image/scikit-image/pull/1012 for general discussion of movies and https://github.com/soft-matter/pims/blob/master/pims/display.py#L21 for an example of how to use pyav to write out a movie.

attn @danielballan

**Comment by dopplershift** [comment]
I'd be curious to see if this obviates the need for the other animation writers. They work, but at least mencoder and ffmpeg seem a little brittle.

**Comment by tacaswell** [comment]
Labeling this as a good first issue because there is no API design (match the current writers) but leaving as medium difficulty because video encoding (and hence the tools around video encoding) has a fair amount of complexity in it.

**Comment by jklymak** [comment]
https://github.com/mikeboers/PyAV still seems to be an active project, so this seems reasonable to keep around as a wishlist item.

**Comment by tacaswell** [comment]
Per the pyav docs, ffmpeg is curently doing an OK job for us so this will likely make our lives worse.

Going to close this as not something we are going to advertise as needing doing (but I do not think we would reject an PR doing this out of hand).
