### ISSUE TITLE
incorrect color assigned by scatter plot when plotting points of a single c value

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#4417]
In the second subplot, the point should be red (c=1.0). But a blue point is plotted instead. This happens whenever len(set(c)) = 1.

matplotlib 1.4.2

I saw there were a couple of recent fixes to the scatter plot functionality, so this may have been already addressed. (I apologize if that's the case.)

```
%pylab inline

subplot(3, 1, 1)
scatter([0.0], [0.0], c=[0.0], cmap=cm.coolwarm)
xlim(-1, 2)
ylim(-1, 1)

subplot(3, 1, 2)
scatter([1.0], [0.0], c=[1.0], cmap=cm.coolwarm)
xlim(-1, 2)
ylim(-1, 1)

subplot(3, 1, 3)
scatter([0.0, 1.0], [0.0, 0.0], c=[0.0, 1.0], cmap=cm.coolwarm)
xlim(-1, 2)
ylim(-1, 1)

tight_layout()
```

![download 2](https://cloud.githubusercontent.com/assets/3205522/7540333/59ffceda-f57b-11e4-921d-398b7ead8563.png)

**Comment by tacaswell** [comment]
Each scatter has it's own norm method and limits, this is the correct behavior.  

If you want all of the `scatter` calls to share the same limits either pass the same `Norm` object to all of them via the `norm` kwarg (just be careful to manage it's limits explicitly or they will be set to the min/max of the first data it is plotted with) which will keep all of them in-sync if you change the color limit (modulo bugs in the caching logic) or pass the same kwargs `vmin` and `vmax` to each call.
