### ISSUE TITLE
extra kwargs raises exemption

### ISSUE THREAD

**Issue by c-wilson** [matplotlib/matplotlib#4420]
I have a simple suggestion that I would be happy to implement if there is agreement: Can we NOT raise exemptions when unknown kwargs are passed to a plotting function (ie plot, scatter)? My understanding is that most APIs use *args and **kwargs in function definitions so that they won't crash if they get extra arguments.

**Comment by WeatherGod** [comment]
Why would you want to not raise an exception if something is incorrect? We already have a problem where we don't do enough input validation, so various arguments get silently lost. There are some functions that do pass-through keywords, but they really should be the exception and not the norm (it makes it difficult to know if everything has been validated).

**Comment by tacaswell** [comment]
The expand a bit on what @WeatherGod said, we use `**kwargs` heavily to allow the user to pass kwargs through to the underlying `Artist` objects.  For example, in the `scatter` case any kwargs that `scatter` does not explicitly use are used to update the `Collection` object before it is returned.  If there is a kwarg which is not a valid property of the `Collection` object the correct thing to do is to raise to alert the user that invalid input was passed in.  The alternative is to silently pass misspelling (for example the user meant to type `lw=5`, but typed `lq=5` silently passing could make it _very_ hard to sort out why the line width is not changing, where as raising and saying 'lq is not valid' makes it very easy). 

I am strongly :-1: on this (and would like things to raise _more_ exceptions earlier for invalid input).

**Comment by WeatherGod** [comment]
By the way, if you are looking to write error-free code: https://pypi.python.org/pypi/fuckit/4.8.0

**Comment by c-wilson** [comment]
ok, no problem, I agree with your arguments. I was wrapping plot functions, and I guess was being a bit lazy by just passing *args and **kwargs. Closed.
