### ISSUE TITLE
IPython Notebook: irregular marker edge for 'o'

### ISSUE THREAD

**Issue by tritemio** [matplotlib/matplotlib#4421]
In the notebook, using `%matplotlib inline`, plotting circle markers (`'o'`) with size of 7 results in a rendering error:

    plt.plot([1,2,3,4], [3,1,2,4], 'o', ms=7)

![image](https://cloud.githubusercontent.com/assets/4156237/7596234/0fe02678-f8a1-11e4-9613-583b087a7427.png)

The problem is present also in the png produced by `savefig`.

Changing the marker size to 6 or 8 results in correct rendering.

This rendering issue is very annoying also because the `ms=7` happens to be the default marker size in seaborn. In fact, I reported the bug there first (https://github.com/mwaskom/seaborn/issues/557).

**Comment by mwaskom** [comment]
Also it's not just a markersize of 7, though that size does look particularly bad:

```python
with plt.rc_context(plt.rcParamsDefault):
    f, ax = plt.subplots(figsize=(8, 3))
    for ms in range(1, 15):
        ax.plot(ms, 1, marker="o", markersize=ms, color="r")
    ax.set(xlabel="Marker size", xlim=(0, 15), yticks=[])
    f.savefig("/Users/mwaskom/Desktop/marker_distortion.png")
```
![marker_distortion](https://cloud.githubusercontent.com/assets/315810/7597921/b72969bc-f8ab-11e4-8ac0-c6ea02d8ec15.png)

**Comment by mwaskom** [comment]
Actually this may be either a regression in what `%matplotlib inline` is doing to the `rcParams` or in my memory. I thought that inline plots had a lower DPI but that the default `plt.savefig` behavior used `dpi=100` (the matplotlib default), but I can't reproduce that. This probably isn't a matplotlib issue after all.

**Comment by tacaswell** [comment]
I would suggest using `%matplotlib notebook` instead.  Leaving figure interactivity on the table is leaving more than half the power of mpl on the table.

It looks like `inline` defaults to 72 dpi and reduces the figure size from (8, 6) -> (6, 4)   https://github.com/ipython/ipykernel/blob/master/ipykernel/pylab/config.py.  The resulting image is a a bit small that expected because inline also saves with `bbox_inches='tight'`.

```python
fig, ax = plt.subplots(dpi=72)
ax.plot([1,2,3,4], [3,1,2,4], 'o', ms=7)
```

will reproduce this. 

I am in the process a PR to address this issue.

**Comment by tritemio** [comment]
@tacaswell thanks for fixing this issue. Regarding switching to `%matplotlib notebook`, I would need to add `plt.close()` for every new figure, whereas with `%matplotlib inline` a new figure is created by default. Or am I missing something?

**Comment by mwaskom** [comment]
Woah I had always assumed was an unavoidably annoyance, not a bug. Thanks for jumping on it, @tacaswell

**Comment by tacaswell** [comment]
It is a fun deep one too related to conditional snapping of the path used to draw the markers.  Ended up reading some c++ to sort this out.

@tritemio Why do you want to close the figures?  If you do that they are no longer interactive.  It is better to add

```python
fig, ax = plt.subplots()
```
when you want a new figure.  There is a PR in the works to make interactive OO work much nicer (https://github.com/matplotlib/matplotlib/pull/4091)

**Comment by tritemio** [comment]
@tacaswell, questions, can there be more 2 interactive figures in the notebook? Is it the rule that the procedural interface is interactive while the OO is not? Examples or docs to get started on this?

**Comment by tacaswell** [comment]
There can be as many interactive figures open as you want, `pyplot` has a notion of what the 'current' axes is (`plt.gca()` to get it), but if you have a ref to any axes you can either operate on it directly with the OO interface (ex `ax.plot(...)` ) or set it as the current figure (`plt.sca(ax)`).
