### ISSUE TITLE
Make limits options for vlines and hlines?

### ISSUE THREAD

**Issue by shoyer** [matplotlib/matplotlib#4425]
I often find myself wanting to add a horizontal or vertical line to a plot using the pyplot interface. This is currently a bit verbose, because I need to fill in the limits for the lines.

Would it be reasonable to infer these automatically from limits of the provided axis if the arguments are not provided? Here's my preliminary implementation:
```python
def hlines(y, xmin=None, xmax=None, *args, **kwargs):
    if xmin is None or xmax is None:
        ax = kwargs['axis'] if 'axis' in kwargs else plt.gca()
        limits = ax.get_xlim()
        if xmin is None:
            xmin = limits[0]
        if xmax is None:
            xmax = limits[1]
    return plt.hlines(y, xmin, xmax, *args, **kwargs)
```

**Comment by efiring** [comment]
It sounds like what you are looking for is a slight modification of axhline (and axvline) to support a first argument that can be array-like or scalar; at present only a scalar is supported.

**Comment by shoyer** [comment]
Actually, axhline and axvline serve my use case perfectly. I just didn't know about them.

**Comment by efiring** [comment]
Good!

**Comment by tacaswell** [comment]
I would also strongly discourage using `plt` in functions, use the OO interface instead.   The state machine is great until it breaks everything and the main defense of the the `plt` interface is brevity when typing at a repl is not there.

 #4091 is a first pass at getting rid of the other defense (automatic re-drawing) taken care of as well.

I would do something like

```python
def magic_hlines(ax, y, xmin=None, xmax=None, **kwargs):
    limits = ax.get_xlim()
    if xmin is None:
        xmin = limits[0]
    if xmax is None:
        xmax = limits[1]
    return ax.hlines(y, xmin, xmax, **kwargs)
```

**Comment by shoyer** [comment]
@tacaswell That's a good point, thanks. In this case, this was really just for a quick example.
