### ISSUE TITLE
Hyphen as a subscript doesn't appear at certain font sizes

### ISSUE THREAD

**Issue by jhpalmieri** [matplotlib/matplotlib#4428]
If I add text "$A_-$" to try to print an A with a hyphen as a subscript, some of the time that subscript does not show up. With only this text, it seems to appear if the font size is less than 20, but not if the font size is 20 or larger. It appears if there is more text with another subscript, maybe? I'm not sure what triggers it. Could the subscript be getting clipped off of the bottom?

Here is an example:

```
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.axis([0, 6, 0, 6])
ax.text(1, 1, '$A_-$', fontsize=19) # subscript visible
ax.text(1, 2, '$A_-$', fontsize=20) # no subscript
ax.text(1, 3, '$A_-B$', fontsize=20) # no subscript
ax.text(1, 4, '$A_-B_+$', fontsize=20) # subscript visible
```

**Comment by tacaswell** [comment]
attn @mdboom 

mathtext is getting quite a beating recently.

**Comment by QuLogic** [comment]
I believe this is working correctly on `v2.x`; can you try it out with 2.0.0rc1?

**Comment by Kojoley** [comment]
2.0.0rc2+2830.gcb89b8b
![issue_4428](https://cloud.githubusercontent.com/assets/2743474/21531794/d24d9160-cd5b-11e6-8fe1-b42db94b4feb.png)
