### ISSUE TITLE
Can't print scroll mouse events

### ISSUE THREAD

**Issue by rmccampbell** [matplotlib/matplotlib#4432]
This is a minor bug, but the __str__ method of MouseEvent uses a %d format for "button" which can be a string ("up" or "down") for scroll events. This causes a crash when you try to print it.

**Comment by tacaswell** [comment]
What version of mpl are you using?

This was fixed in 6c1f14f3bca7a5d0a0fa4fa78bd6503ca389540f / https://github.com/matplotlib/matplotlib/pull/2399 which should be included in 1.4.0 and later.

Closing this as a duplicate, please ping to have re-opened if this is still a problem in 1.4.x.
