### ISSUE TITLE
Cannot use umlauts in plot title

### ISSUE THREAD

**Issue by jondo** [matplotlib/matplotlib#4442]
I cannot get umlauts working in plot titles.

I have tested the following code in both utf-8 and latin-1 source encoding:

```python
import matplotlib.pyplot as plt
plt.figure()
plt.title('ä')
```
I always get: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 0: ordinal not in range(128)`.

I am using `WinPython-64bit-2.7.9.4.exe`, which contains Python 2.7.9 and matplotlib 1.4.3.

I have also tried to use LaTeX:
```python
import matplotlib.pyplot as plt
plt.rc('text', usetex=True)

plt.figure()
plt.title('\ss\"a')
```
This renders the \ss correctly into ß (s sharp), but the \"a just becomes "a .

My MiKTeX installations seems ok otherwise, e.g. the following tex file correctly generates ä:
```latex
\documentclass{article}
\begin{document}
\"a
\end{document}
```

Should this work? Do I miss something obvious? I will try with Python 3 tomorrow.

**Comment by mdboom** [comment]
You need to use a Unicode string literal, i.e.:

```
import matplotlib.pyplot as plt
plt.figure()
plt.title(u'ä')
```

And for LaTeX, a raw string literal so the slashes pass through unaltered:

```
plt.title(r'\ss\"a')
```

**Comment by jondo** [comment]
Thank you! The LaTeX hint works. The unicode string doesn't, however. With Python 3 (WinPython-64bit-3.4.3.3), both `plt.title(u'ä')` and the plain `plt.title('ä')` work (independent of source encoding).

**Comment by mdboom** [comment]
Do you have a coding token at the top of your file?  For example:

```
# -*- coding: utf-8 -*-
```

Without it, Python will use the default encoding on your system, which may not be the same encoding that your text editor saved the file in.  This also relies on a text editor that understands coding lines, but most do these days.

**Comment by jondo** [comment]
Yes, I have appropriately used either `# -*- coding: utf-8 -*-` or `# -*- coding: latin-1 -*-` as first line, and the editor (Spyder) processed it correctly.

**Comment by mdboom** [comment]
Puzzling then.  I can't seem to reproduce it.

**Comment by jondo** [comment]
Never mind. I have got the LaTeX workaround, and in 2021 Python 2.7 will be history :-)
