### ISSUE TITLE
%matplotlib notebook and procedural interface

### ISSUE THREAD

**Issue by tritemio** [matplotlib/matplotlib#4453]
When using `%matplotlib notebook` with the procedural interface, figures are not closed when the red 'x' button is pressed (the figure becomes static, but the figure object is not closed).

After closing the figure by clicking on the red 'x' button, no other plot is displayed until `close()` is called. Is this a deliberate choice?  I think it may be confusing for newbies.

DISCLAIMER: I know that the OO interface is preferred. However, the procedural interface has its use-case for a first-time users (plus allows saving some typing).

**Comment by WeatherGod** [comment]
Which version of matplotlib and ipython are you using? I think this is a
bug that was recently fixed in master.

**Comment by tritemio** [comment]
Great to know it has been fixed!

I'm using matplotlib 1.4.3 with python 3.4 under Anaconda for windows 7 x64.

Is this a bug in all the platforms? Is there a workaround until the next release?

**Comment by tritemio** [comment]
I forgot to mention the ipython version is 3.1.

**Comment by tritemio** [comment]
@WeatherGod, I found the previous issue, unfortunately is still open: #4281.

I think we can close this a duplicate.
