### ISSUE TITLE
savefig.format config has no effect under Qt4Agg

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4454]
All's in the title: despite setting `savefig.format` to "png" in the config file, the figure save window lists "eps" as default format.  Configuration information below.
```
$ grep ^backend ~/.config/matplotlib/matplotlibrc
backend      : qt4agg
$ grep ^savefig.format ~/.config/matplotlib/matplotlibrc
savefig.format      : png      # png, ps, pdf, svg
$ python --version
Python 3.4.3
$ python -c 'import matplotlib, PyQt4.Qt; print("matplotlib", matplotlib.__version__, "Qt4", PyQt4.Qt.QT_VERSION_STR, "PyQt4", PyQt4.Qt.PYQT_VERSION_STR)'
matplotlib 1.4.3 Qt4 4.8.6 PyQt4 4.11.3
```
(Arch Linux default packages)

Note that I do not observe this with the Qt5 backend.

**Comment by tacaswell** [comment]
I suspect that this is an issue in `qt_compat` where the file dialog is not being re-mapped correctly, I bet this does not happen with pyside or qt4v2 either.

Just to be sure, what do the following yield on your system?

```python
In [43]: matplotlib.backends.backend_qt4.FigureCanvasBase.get_default_filetype()
Out[43]: 'png'

In [44]: matplotlib.backends.backend_qt5.FigureCanvasBase.get_default_filetype()
Out[44]: 'png'
```

**Comment by anntzer** [comment]
Same output here.

**Comment by tacaswell** [comment]
I can not reproduce this with conda installed qt/pyqt + masterish

```
10:10 $ python -c 'import matplotlib, PyQt4.Qt; print("matplotlib", matplotlib.__version__, "Qt4", PyQt4.Qt.QT_VERSION_STR, "PyQt4", PyQt4.Qt.PYQT_VERSION_STR)'
matplotlib 1.5.dev1 Qt4 4.8.5 PyQt4 4.10.4

```

what is the value for `backend.qt4` ?

I have an arch box, but am currently working tethered to a phone and don't want to install everything over 4g.

**Comment by anntzer** [comment]
Indeed, the bug isn't present in a conda install (everything straight from conda).  It is still present using system libraries and matplotlib master (as of now).
What do you mean by "the value of `backend.qt4`"?

**Comment by tacaswell** [comment]
There is an rcparam (`backend.qt4`) which lets you set which flavor of the qt4 bindings (pyside, pyqt4v1, pyqt4v2).

That we both can make this work with conda's version of everything makes me think that this is a lower level bug.  I will try to testing this on system libraries in the near future.

**Comment by anntzer** [comment]
```
In [4]: matplotlib.rcParams["backend.qt4"]
Out[4]: 'PyQt4'
```

In my matplotlibrc I never changed the `backend.qt4` setting, note the commented line reads
```
#backend.qt4 : PyQt4        # PyQt4 | PySide
```
(so perhaps the list of allowed values should be updated?).

**Comment by tacaswell** [comment]
I thought we had...

**Comment by jenshnielsen** [comment]
@tacaswell There is an env variable QT_API  see the start of https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py

**Comment by tacaswell** [comment]
I can not reproduce this on an up-to-date arch:

```
[root@jupiter tcaswell]# pacman -Q python-matplotlib
python-matplotlib 1.4.3-2
[root@jupiter tcaswell]# pacman -Q python-pyqt4
python-pyqt4 4.11.3-4
[root@jupiter tcaswell]# pacman -Q python
python 3.4.3-2

```
and
```
In [2]: matplotlib.rcParams['savefig.format']
Out[2]: 'png'

In [4]: matplotlib.get_backend()
Out[4]: 'Qt4Agg'

```

**Comment by anntzer** [comment]
Replicated on another Arch machine.  I'll investigate.

**Comment by anntzer** [comment]
I think I figured it out: this is because my DE is based on KDE5, and PyQt4 tries to use the native dialog when requesting a save-file name, but there must be some bug in how it tries to create a Qt5-based dialog making it ignore the default extension.  Adding e.g. QFileDialog.DontUseNativeDialog to the call solves the issue, though I certainly don't expect you to add this to the matplotlib codebase as it is really an issue of Qt4 rather than of matplotlib.

**Comment by tacaswell** [comment]
Does it get the base part of the default filename correct?

I wonder if there is an order-of-operations thing where the file name is being set, then the list of allowed extensions is set and the first in the list sorted alphabetically is set (which is 'eps').

Closing this as 'needs upstream fix'.

**Comment by anntzer** [comment]
Default basename is correct.  Oh well.

**Comment by tacaswell** [comment]
@anntzer Not sure if this should go upstream to pyqt4 or kde5
