### ISSUE TITLE
following mathematic symbols failed in matplotlib.mathtext, version 1.3.1

### ISSUE THREAD

**Issue by nuix** [matplotlib/matplotlib#4462]
$\Cup$ $\Cap$ $\dotplus$ $\barwedge$ $\doteq$ $\doteqdot$ $\rightharpoonup$ $\ddots$ $\leftharpoonup$

**Comment by mdboom** [comment]
Can you describe how the fail?  Do you get an exception?  The wrong symbol?  This symbols do work, as evidenced by this doc page (where the math is rendered with matplotlib):

http://matplotlib.org/users/mathtext.html#mathtext-tutorial

**Comment by tacaswell** [comment]
The symbols that start as '\dot' are broken, it looks like the parser is too greedy about identifying '\dot' so `\doteq` is being grouped as `(\(dot))eq` instead of `\(doteq)`

**Comment by tacaswell** [comment]
@nuix This is now fixed on master, you can see the symbols rendered at http://matplotlib.org/devdocs/users/mathtext.html#symbols
