### ISSUE TITLE
Incorrect hatching in legend for PDF backend

### ISSUE THREAD

**Issue by jpallister** [matplotlib/matplotlib#4469]
When using hatching in a legend, the PDF backend does not draw the hatching if the previous label is empty:

    from matplotlib import pyplot as plt

    fig = plt.figure()

    a = plt.Rectangle([0,0], 0, 0, facecolor="green", hatch="//")
    b = plt.Rectangle([0,0], 0, 0, facecolor="blue", hatch="//")

    fig.legend([a,b,a,b], ["","","",""])

    plt.savefig("test.pdf")
    plt.show()

The displayed legend (from plt.show) is:
![image](https://cloud.githubusercontent.com/assets/1574422/7801867/56b5d5fc-0323-11e5-95c2-8666abcf977e.png)

The legend saved in the PDF is:
![image](https://cloud.githubusercontent.com/assets/1574422/7801873/9574f94e-0323-11e5-900e-00c742cc2129.png)

If one of the labels is non-empty:

    fig.legend([a,b,a,b], ["","","X",""])

the following hatching is displayed correctly
![image](https://cloud.githubusercontent.com/assets/1574422/7801882/e0c7a2f2-0323-11e5-82d4-56a9b7675152.png)

**Comment by tacaswell** [comment]
weird.

attn @jkseppan

**Comment by tacaswell** [comment]
I suspect that there is a graphics context which is not getting properly reset.

**Comment by jpallister** [comment]
The following commit fixes the issue in this case:
  232c50d9f54e4817413023e15bb5669d5ddd1563

However, I don't know enough to say whether this is the right thing to do. The problem does seem to be the hatch pattern is not reapplied in the PDF backend though.

**Comment by tacaswell** [comment]
@jpallister Great!  I also do not know enough about the internals of pdf's to tell if that is the right solution (it seems a bit brittle as I think it depends on the order of the commands), but I am convinced that this is the right place.

Can you put in a PR with that commit and maybe add a test, (see https://github.com/matplotlib/matplotlib/pull/4472 for an example of adding a pdf only test).  Even if this is not the final solution, having the commit in a PR greatly helps us with the review process.

**Comment by tacaswell** [comment]
maybe related: https://github.com/matplotlib/matplotlib/issues/3023

**Comment by tacaswell** [comment]
Closed by merging #4474
