### ISSUE TITLE
please re-schedule "Color Overhaul" milestone

### ISSUE THREAD

**Issue by stonebig** [matplotlib/matplotlib#4478]
https://github.com/matplotlib/matplotlib/milestones shows a past due date (by 27 days).
It would be nice to re-schedule.

**Comment by tacaswell** [comment]
Please bring this up on the dev mailing list.

There is a fair amount of work to do documenting the change (expanding on https://github.com/matplotlib/matplotlib/pull/4238/) and the considered color maps.

The is also the matter of pinning down what the new color map(s) will be.

Any help would be appreciated.
