### ISSUE TITLE
PGF Backend: "Dimension too large" error while processing log-scale plot

### ISSUE THREAD

**Issue by rwirth** [matplotlib/matplotlib#4482]
The PGF backend of MPL 1.4.3 causes a "Dimension too large" LaTeX error when processing a log-scale plot with a point at zero. The error is

```
[...]
! Dimension too large.
<to be read again> 
                   \pgf@y 
l.69 ...\pgfqpoint{-2148537.332542in}{0.600000in}}
                                                  %
No pages of output.
Transcript written on figure.log.
```

Obviously, the _x_ coordinate of the point is way out of bounds. The script triggering the error is

``` python
import matplotlib as mpl
mpl.use('pgf')
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([0, 1], [.5, 1])
ax.set_xscale('log')
fig.savefig('fig.pdf')
```

Adding `nonposx='mask'` to the call to `set_xscale` prevents the error but produces a plot consisting of only a single point. The PGF version installed is 2.10 but the error also occurs with PGF 3.00.

**Comment by tacaswell** [comment]
attn @pwuertz

**Comment by tacaswell** [comment]
With that data and a logscale on the x-axis a plot with a single point is correct.  `log(0)`  is `-∞` which can not be plotted.

**Comment by pwuertz** [comment]
I don't know the details, but from a quick search I found a comment in the changelog, saying that `nonposx='mask'` should be the default behaviour, thus the point that is causing trouble shouldn't be emitted to the backend in the first place.
Other than that, everything seems to be in order, right? So the invalid point is discarded and you end up with a plot containing the remaining point.

**Comment by rwirth** [comment]
The current situation precludes users from using `nonposx='clip'`, which is not ideal. It would be nice if the backend handled these "points at infinity" gracefully, just like the other backends where the above script produces a horizontal line (I checked that with the Qt and Tk backends).

Couldn't one just clamp these dimensions to some large value less than TeX's `\maxdimen`? My TeX distro gives me a value slightly below 16384 pt which corresponds to 226.7 in, so something of the order of 100 in should be a reasonable choice.

**Comment by pwuertz** [comment]
I don't think hardcoding some clamping behaviour inside matplotlib does away with this limitation.
For instance, what happens if you clamped all emitted values to 100in and the user expects a 1000in point to be placed correctly after placing the figure in a scale-box of 1/10? Or you clamp all points to 100in, the user upscales the figure 3x and runs into this error anyways? Or the user really tries to create a figure of 200in size and instead of an error, everything is displaced in a strange way?

TeX has limitations, alot of them. TeX could (should?) do the clamping you suggested itself and post a warning instead of an error, but for some reason they decided not to do that. I don't think trying to hide this fact is the best course of action.

Other than that, matplotlib could simply clip/omit points that are outside the viewable space. We had the same problem when drawing lines that happened to be way outside the plotting area and used a clip/optimize option of the path iterator to fix that. Something like this should be possible for points as well.

**Comment by pwuertz** [comment]
I don't have time to test it right now, but does that commit fix the problem for you?

**Comment by rwirth** [comment]
Thanks for the effort, but this doesn't fix the problem. The code you inserted was missing there but I don't think it gets called when the script is executed because no markers are requested. The "offending" point is part of a path that gets drawn by `_print_pgf_path`, which should get properly clipped already. The path just consists of two operations: `MOVETO (-∞,y0), LINETO (x1,y1)`, or from the script:

    [([-2.14853733e+08, 6.00000000e+01], 1), ([ 410.15500003, 460.], 2)]

I went through the code and I _think_ the problem is in `_path.cleanup_path`. During the call to that function a `PathClipper` is instantiated that does the clipping via some agg function, but only if the operation was a line-to. The move-to that contains the offending point is passed on verbatim and a new move-to is inserted as the next command as a result of the clipping operation. After the clipping the above path looks like

    [([-2.14853733e+08, 6.00000000e+01], 1), ([99., 459.99942071], 1), ([410.15500003, 460.], 2)]

I guess that second move-to is the correct one and one has to somehow detect this situation and discard the first one.

I haven't had time to wrap my head around the code in `PathClipper<T>::vertex` but there is a private member `m_broke_path` that seems to be set in exactly that situation. However, that member is never read.

**Comment by rwirth** [comment]
Also, the `draw_markers` function should probably iterate over the unclipped path and just exclude markers whose bounding box does not intersect the clip rectangle. If I understand correctly your patch would put such markers at the point of intersection of the path segment and the clip box.

**Comment by pwuertz** [comment]
Oh ok, I thought the problem was related to points since we talked about two of them, one that is invalid, and the one left. Concerning the markers, true, points should only be clipped if they are further away from the scene than half the markersize, so this presumed fix might be dangerous.

So apparently the code for optimizing paths in terms of clipping needs some work. If I remember correctly, this topic came up from time to time. The current path clipping solution can't handle filled paths for example, and as it seems it doesn't split path segments for achieving true clipping. There have been suggestions for using a more complete solution, I think someone pointed out `Clipper` could do the job.

**Comment by MaxNoe** [comment]
An intermediate solution for this is to modify the resulting hists:

###
```{python}
import numpy as np
import matplotlib.pyplot as plt

hist, edges, patches = plt.hist(np.random.normal(size=1000), bins=20, range=[-10, 10])

for rectangle in patches:
    rectangle.set_y(0.1)
    rectangle.set_height(rectangle.get_height() - 0.1)
```


### `histtype='step'`

```{python}
import numpy as np
import matplotlib.pyplot as plt

hist, edges, patches = plt.hist(np.random.normal(size=1000), bins=20, range=[-10, 10], histtype='step',)
xy  = poly.get_xy()
xy[:, 1][xy[:, 1] == 0] = 0.1
poly.set_xy(xy)
```

**Comment by tacaswell** [comment]
@pwuertz can you put that commit on a branch?

**Comment by pwuertz** [comment]
Updated branch https://github.com/pwuertz/matplotlib/tree/fix_4482
However, I'd consider this issue as "won't fix".

**Comment by EdwinChan** [comment]
As of matplotlib 2.0.2+4336.g2ea1261c8, `plot()` no longer causes the error, but `plot(…, marker='x')` and `scatter()` still do.

A fix may be worthwhile because the error can come up in more innocuous situations, such as scatter-plotting a large array of data and zooming in using `xlim()` and `ylim()`; with the default figure and axes sizes, zooming in 50× is enough to trigger the error.

**Comment by asmeurer** [comment]
I am getting this issue with a histogram plot with a log y-axis. It used to not be an issue in matplotlib 2.0.2. I bisected it to this commit:

```
commit 668ff586c12a3c577ddd985a375030381e80539c
Author: Thomas A Caswell <tcaswell@gmail.com>
Date:   Wed Oct 25 13:57:47 2017 -0400

    Backport PR #9477: In LogTransform, clip after log, not before.

:040000 040000 d06b0915732fc82068a655e4431ba43b1a00821c 62418b35c8ebff85c6dc33c856a6c0b610b4fbce M	doc
:040000 040000 cab591b5b1312c490acf32db29b33df75462e412 c9ae7ff3e20714580cac6c1575a3795a81ea0555 M	lib
```

(PR #9477)

Here's a segment of the diff (working vs. not working) of the pgf file

```diff
@@ -224,15 +224,15 @@
 \pgfsetstrokecolor{currentstroke}%
 \pgfsetstrokeopacity{0.000000}%
 \pgfsetdash{}{0pt}%
-\pgfpathmoveto{\pgfqpoint{2.704054in}{-105.424286in}}%
-\pgfpathlineto{\pgfqpoint{2.851090in}{-105.424286in}}%
+\pgfpathmoveto{\pgfqpoint{2.704054in}{-353.996572in}}%
+\pgfpathlineto{\pgfqpoint{2.851090in}{-353.996572in}}%
 \pgfpathlineto{\pgfqpoint{2.851090in}{1.406790in}}%
 \pgfpathlineto{\pgfqpoint{2.704054in}{1.406790in}}%
 \pgfpathclose%
 \pgfusepath{fill}%
 \end{pgfscope}%
 \begin{pgfscope}%
```

which produces errors like

```
! Dimension too large.
<to be read again>
\advance
l.1161 ...eto{\pgfqpoint{7.762078in}{-353.996572in}}
                                                  %
```

**Comment by asmeurer** [comment]
Looks like I can workaround the issue by changing

```py
ax.set_yscale('log', nonposy='clip')
```

to 

```py
ax.set_yscale('log', nonposy='mask')
```

**Comment by anntzer** [comment]
Can you check what is the maximal dimension you can (manually) put in that keeps pgf happy?

**Comment by asmeurer** [comment]
Seems to be -226in. -225.999999in gives no errors but -226in gives the errors.

**Comment by anntzer** [comment]
Can you figure out if that's documented somewhere?

**Comment by asmeurer** [comment]
According to [this](https://tex.stackexchange.com/questions/139883/origin-and-formation-to-the-error-dimension-too-large/139906#139906), the maximum number of points (pts) allowed in TeX dimensional arithemetic is 16384, which according to [this](https://tex.stackexchange.com/questions/8260/what-are-the-various-units-ex-em-in-pt-bp-dd-pc-expressed-in-mm) comes to 16384 / 72.26999 = 226.70544163628637 inches. I don't know where the extra 0.705 in comes in. Maybe there is some extra padding from the rest of the plot or some truncating to an integer inch or something else.

**Comment by anntzer** [comment]
Thanks for the info.
I think the correct fix is actually not to revert #9477 (which only exposed a preexisting underlying issue -- one could always have directly passed in a too-large coordinate), but actually to use the PathClipper machinery (in C++, see path_cleanup.cpp) which is already used to clip data to +/-2**23 (Agg's limitation) and set it to clip to whatever is needed with pgf.

**Comment by asmeurer** [comment]
I agree that the most correct solution is to never allow creating invalid pgf files (I never meant to imply that #9477 should
be reverted, only that it was the result of my bisection).

**Comment by anntzer** [comment]
No worries.  My point was mostly that given that we already have some code to work around the limitation of Agg, it seems fair to likewise apply it to pgf.

**Comment by nikhgarg** [comment]
What is the current best workaround? I'm facing this exact issue when trying to do a bar plot with y scale as log.

**Comment by phdoerfler** [comment]
My workaround is to generate those images as .pdf instead for now and include those like any regular graphic 🤷‍♂️

**Comment by MaxNoe** [comment]
> Can you figure out if that's documented somewhere?

Yes. It's not pgf. It's TeX:
https://tex.stackexchange.com/a/54703/59716

**Comment by MaxNoe** [comment]
> The \dimen registers perform their arithmetic’s internally with 32 bit scaled integers, so called ‘scaled point’ with unit sp. It holds 1 pt = 65536 sp = 2^16 sp. One of the 32 bits is used as sign. The total number range in pt is [−(2^30 − 1)/2^16, (2^30 − 1)/2^16 ] = [−16383.9998, +16383.9998].

1 inch = 72..27 pt = 72 bp
1 pt = 2^16 sp

**Comment by MaxNoe** [comment]
This is also stored in the length `maxdimen`:

```
\documentclass{standalone}
\begin{document}
\the\maxdimen
\end{document}
```

**Comment by asmeurer** [comment]
Were you able to figure out why the limit gets truncated to an integer number of inches?

**Comment by MaxNoe** [comment]
It shouldn't. Where did you observe that?

**Comment by MaxNoe** [comment]
16.383.9998 pt = 226.7054 in 

This compiles fine:

```
\documentclass{article}
\begin{document}

\rule{226.7in}{2pt}
\end{document}
```

This doesn't:

\documentclass{article}
\begin{document}

\rule{226.8in}{2pt}
\end{document}

**Comment by mabl** [comment]
So I also ran into this just now. I think, that the main problems in path clipping were already resolved in #5895. The remaining issue seems to be the markers. Having no glue about the inner workings of mpl, I tried skipping markers outside the canvas, see https://github.com/mabl/matplotlib/tree/fix_mpl_4482. It looks like this fixes the issue for me.

**Comment by svaberg** [comment]
I had this issue now as well, and the fix by @mabl solved it.

**Comment by MaxNoe** [comment]
@mabl COuld you open a PR with that fix? It would be geat to finally fix this.

**Comment by svaberg** [comment]
I just found that even after the @mabl fix, a problem lingers for certain markers, such as `x`, while others such as `o` are ok. After applying the fix the following code works for `o` but not for `x`:
```python
import matplotlib
matplotlib.use('pgf')
import matplotlib.pyplot as plt

x=[1, 2, 0]
y=[1, 2, 1]

for marker in 'ox':
    fig, ax = plt.subplots()
    
    ax.scatter(x, y, marker=marker)
    ax.set_xscale('log')

    plt.savefig('plot_' + marker +'.pgf')
    plt.close()
```
I was not able to patch `_print_pgf_path` method, which is used here, in the same way as the @mabl fix. 

In my case I can sanitise the data by changing `x[2]` to a non-zero value so I will be doing this for now instead of trying to fix this bug.

**Comment by nikchha** [comment]
Any updates here? I have the same issue with a broken y-axis graph.

```python
fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True, gridspec_kw={'height_ratios': [1,5]}, figsize=(8,6))

ax1.bar(langs["language"], langs["count"])
ax2.bar(langs["language"], langs["count"])

ax1.set_ylim(119150, 119200)  # outliers only
ax2.set_ylim(0, 1200)  # most of the data

ax2.set_xticklabels(langs["language"], rotation=60, ha="right")
plt.tight_layout()
plt.savefig('language_distribution.pgf', format='pgf')

```

When using the above code to save a figure as pgf, LaTeX always crashes and says the dimension is too large.

**Comment by asmeurer** [comment]
I think a workaround would be to postprocess the output pgf to remove/clip any number above -226in (see my comments above). 

I don't know how matplotlib works internally, but is it converting the values of the very large data from your `ax1.set_ylim(119150, 119200)  # outliers only` as inches in the resulting plot? If so, maybe another workaround would be to scale the data down to smaller numbers, and manually adjust the y-axis labels to compensate (I haven't tested this, it's just a theory). 

Really there's no need for a plot to produce a pgf with elements on the order of 226 inches (~18 feet) (TeX is thinking about literal inches on a printed page). Everything should be scaled down to reasonable values, or clipped if the value in question renders something way off the resulting page. But someone who actually understands how this stuff works would need to comment on how reasonable that would be to actually do.

**Comment by jklymak** [comment]
Most vector viewers do the clipping for you, so if we put a data point at -1e6 inches, it doesn't matter so long as our clip mask is finite.  We don't remove points in general because that is a difficult problem that truly is better handled by the downstream viewer.  

PGF/tikz have clip boxes defined.  It really seems to me that this is a PGF bug rather than something matplotlib should fix.  i.e. they should only complain about out-of-range data if its not clipped.

**Comment by randolf-scholz** [comment]
A simple fix for me was to change y-scale to `symlog`. Maybe if this error is produced this could be suggested to the user?
