### ISSUE TITLE
Automatically place annotations.

### ISSUE THREAD

**Issue by chebee7i** [matplotlib/matplotlib#4489]
Sometimes, you want to display some text and only one piece of text, but you don't want to precompute where it should be. So it would be nice if matplotlib could figure this out for you, just as it does with `legend(loc='best')`. This question came up on SO a while ago: 

http://stackoverflow.com/questions/7045729/automatically-position-text-box-in-matplotlib

There's also an old ticket (https://github.com/matplotlib/matplotlib/issues/176) that was looking to hack `legend(numpoints=0, loc='best')` in order to achieve the same effect.

**Comment by chebee7i** [comment]
Related (or possibly a duplicate of): https://github.com/matplotlib/matplotlib/issues/1313

**Comment by petehuang** [comment]
#6252 gave a good attempt at trying to solve this but needed some refactoring work - suggest looking into it if you are interested in taking a stab at this

**Comment by matthewsot** [comment]
Hi - this seems like a very useful feature, and I'm interested in trying to refactor some of the code in #6252 to make it work if it's still an open issue.

I'm also new to the codebase, though - would it make sense to move _find_best_position (and related functions) into the Axes class (perhaps renamed a bit), and then have both the legend and the annotation code call that? Thanks!

**Comment by tacaswell** [comment]
@matthewsot This is still an open issue!

Moving that method to cbook and making it a function is probably a better option than moving the methods to the `Axes` object because that de-couples the classes (rather than coupling them more tightly).

**Comment by jklymak** [comment]
Duplicate #1313
