### ISSUE TITLE
Wrong default value "loc" for pyplot.legend() in documentation or implementation

### ISSUE THREAD

**Issue by scimax** [matplotlib/matplotlib#4498]
Hey guys,

I think I found a mistake in the documentation or a wrong implementation of the location of a legend.

The documentation for pyplot.legend() says that the default value of the parameter "loc" is 0. But when applying the function it is placed above my line in the plot, upper right, which corresponds to loc=1. When passing loc=0 manually the legend is placed at the upper left corner in my specific example, so different than the default.

I couldn't find any issue on that which is why I added it.

**Comment by WeatherGod** [comment]
Yeah, that is misleading. A long time ago, that was the default, but then
one could add "legend.loc" to their matplotlibrc configuration. If that
isn't supplied, then it could fall back to 0, but with the way rcparams are
done, I don't think that is possible anymore.

**Comment by jhamrick** [comment]
This was fixed in 640a67e4.
