### ISSUE TITLE
Default style proposal: outward tick marks

### ISSUE THREAD

**Issue by ellisonbg** [matplotlib/matplotlib#4502]
I would like to propose making tick marks point outward by default (and for the 2.0 release). The idea for this comes from William Cleveland's *Elements of Graphing Data*. I quote directly from him:

> ...tick marks should point outward. This format prevents data from being obscured (page 33)

The idea is really simple. Data belongs on the inside of the axes frame. If your tick marks point inwards, there is a good chance that the tick marks and data will interfere. This type of interference happens often in practice with dense amounts of data in line/scatter plots and with all kinds of color/surface plots. Here is a simple example:

The tick marks on a a default styled `pcolor` plot are almost impossible to see along some borders:

![screen shot 2015-06-07 at 5 40 44 pm](https://cloud.githubusercontent.com/assets/27600/8026833/3515b6fa-0d3d-11e5-855c-fa6479776a57.png)

The tick marks outwards become extremely helpful and visible:

![screen shot 2015-06-07 at 5 40 50 pm](https://cloud.githubusercontent.com/assets/27600/8026835/457fdeda-0d3d-11e5-90f1-b1c7a69387c3.png)

Cleveland's way of describing this choice also helps me to understand the default visual styling of ggplot2 and seaborn, which use a) no tick marks and b) light grid lines against a grey bg. This is simply a different way of providing the visual guides for plots that don't interfere with the data itself. The other option for the defaults would be to move in this direction (no tick marks with light grid lines on a grey bg), but I think that is probably too much change for the defaults.

**Comment by neilpanchal** [comment]
This makes so much sense. I never noticed it but now I will everyday. This must be done.

**Comment by MrTomWhite** [comment]
The chart you show is a great motivating example. 
Coincidentally, it looks like Excel's old defaults also have tick mark going out of the plot. See an image here: http://www.excel-easy.com/examples/images/line-chart/line-chart.png

**Comment by mlgill** [comment]
I have a code snippet I use all the time that puts the tick marks outside for this exact reason. So I'm all for it.

**Comment by MrTomWhite** [comment]
@mlgill If you know where in the code to change the default, could you prep a quick PR and reference this issue?

**Comment by mlgill** [comment]
@MrTomWhite Changing the tick mark direction, what I was referring to, is a setting that can be done after the plot is made....

**Comment by ellisonbg** [comment]
I should note that the code for doing this on a particular axis is this:

```python
ax.get_xaxis().set_tick_params(direction='out', width=1)
ax.get_yaxis().set_tick_params(direction='out', width=1)
``

It is not too difficult, but definitely not something average users are going to remember off the top of their heads.

**Comment by ellisonbg** [comment]
Oh, the `width=1` part is probably not needed, but I have found it to be nice.

**Comment by mwaskom** [comment]
Could also look at the seaborn `ticks` style which also does this. (I actually use it more than the "default" seaborn style for personal work...)

**Comment by efiring** [comment]
On 2015/06/07 3:48 PM, Brian E. Granger wrote:
> I should note that the code for doing this on a particular axis is this:
>
> ax.get_xaxis().set_tick_params(direction='out',width=1)
> ax.get_yaxis().set_tick_params(direction='out',width=1)
> ``
>
> Itis  not  too difficult, but definitelynot  something average users are going to remember off the top of their heads.
>

More generally, it is also controlled by matplotlibrc, or by modifying 
the corresponding rcParams entries, or by using a style file to handle this.

e.g. in your matplotlibrc:

xtick.direction : out
ytick.direction : out
xtick.major.width : 1
ytick.major.width : 1

etc.

Eric

**Comment by ellisonbg** [comment]
I should note that if there isn't enough support to change the default on
this, I think it would be nice to have a method to quickly do this on an
axes (maybe `ticks_out` and `ticks_in`).

On Sun, Jun 7, 2015 at 7:06 PM, Eric Firing <notifications@github.com>
wrote:

> On 2015/06/07 3:48 PM, Brian E. Granger wrote:
> > I should note that the code for doing this on a particular axis is this:
> >
> > ax.get_xaxis().set_tick_params(direction='out',width=1)
> > ax.get_yaxis().set_tick_params(direction='out',width=1)
> > ``
> >
> > Itis not too difficult, but definitelynot something average users are
> going to remember off the top of their heads.
> >
>
> More generally, it is also controlled by matplotlibrc, or by modifying
> the corresponding rcParams entries, or by using a style file to handle
> this.
>
> e.g. in your matplotlibrc:
>
> xtick.direction : out
> ytick.direction : out
> xtick.major.width : 1
> ytick.major.width : 1
>
> etc.
>
> Eric
>
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/matplotlib/matplotlib/issues/4502#issuecomment-109825106
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/4502#issuecomment-109827054>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
The default histogram styling (tick marks in) is another case where you can be pretty sure you will never see the tick marks along the lower frame:

![screen shot 2015-06-07 at 7 16 45 pm](https://cloud.githubusercontent.com/assets/27600/8027284/d4968928-0d49-11e5-88a6-c0023a1e940d.png)

**Comment by njsmith** [comment]
For extra histogram fun, try plotting a non-normal distribution with lots of bins:
```
plt.hist(np.random.beta(0.5, 0.5, 10000), 200, color="pink")
```
Notice how the leftmost and rightmost bars have mysteriously turned into stacked bars or... something? wtf is this? OHH right it's just really confusing ticks.

**Comment by njsmith** [comment]
As for making a PR for this: my suggestion would be to:
* create two new built-in styles called "matplotlib1" and "_matplotlib2.0", which initially are identical to the current default style
* arrange so that by default we `style.use("matplotlib1")`
* make this change to the "_matplotlib2.0" style

And then we can accumulate all the visual changes for 2.0 in the "_matplotlib2.0" style, and when we're done we rename "_matplotlib2.0" -> "matplotlib2.0", release 1.last, and then switch our default to be `style.use("matplotlib2.0")` and release 2.0.

**Comment by gumption** [comment]
I prefer the outward tick marks, and support making outward (vs. inward) tick marks the default.

**Comment by empet** [comment]
A figure with inward ticks looks better. Many journals stress in their submission/publication guidelines that  figure tick marks must point inward.

**Comment by ellisonbg** [comment]
@njsmith I like the idea of using style sheet to help migrate the style work. The only thing that is a bit difficult is that the defaults are not in style sheets, but hardcoded in the rcParams definition in the code. For 2.0 wouldn't we want to be making the changes to the defaults there and offering a matplotlib1 stylesheet to allow users to move back? I am just not sure what the best way to handle this is...

**Comment by ellisonbg** [comment]
Overall the reaction to this proposal seems positive. Based on this I have been making some fine tweaks of the tick mark styles. Here I compare the same plot with diferent tick mark styles:

Here is the current default style with tick marks in:

![screen shot 2015-06-07 at 10 54 01 pm](https://cloud.githubusercontent.com/assets/27600/8028739/4a95643c-0d68-11e5-9cdb-d8fa010009de.png)

For the following two examples (with tick marks out) I have increased the line widths of the tick marks from the existing `0.5` to a value of `1.0` to match the axes frame. After playing more, I do think that the tick mark widths should be 1 when they are outwards.

This one (A) keeps the existing tick mark sizes/lengths of (4,2) for major/minor tick marks:

![screen shot 2015-06-07 at 10 51 06 pm](https://cloud.githubusercontent.com/assets/27600/8028706/b6dc5a66-0d67-11e5-945c-e413be78e5ff.png)

This one (B) increases the tick mark sizes/lengths to (6,3) for major/minor tick marks (the ticks style of seaborn uses these settings):

![screen shot 2015-06-07 at 10 52 39 pm](https://cloud.githubusercontent.com/assets/27600/8028721/efb323e2-0d67-11e5-86d8-32b07c17d837.png)

Any preferences for A or B?

* A=out, width=1, same lengths
* B=out, width=1, longer lengths

**Comment by ellisonbg** [comment]
Also, here the examples of @njsmith above.

First in the current default style:

![screen shot 2015-06-07 at 11 05 13 pm](https://cloud.githubusercontent.com/assets/27600/8028846/d45adfac-0d69-11e5-89ac-196a15341089.png)

Now in style (A):

![screen shot 2015-06-07 at 11 05 37 pm](https://cloud.githubusercontent.com/assets/27600/8028849/e6ecd670-0d69-11e5-937e-57e75b6981a5.png)

**Comment by njsmith** [comment]
@empet:
> A figure with inward ticks looks better. Many journals stress in their submission/publication guidelines that figure tick marks must point inward.

The other commenters in this thread have given some pretty objective reasons why outward ticks are better both in theory and in specific cases. Can you provide any evidence for "looks better", or at least provide links to a few of these submission guidelines?

@ellisonbg:
Huh, apparently your matplotlib defaults for tick length act the way that I remember them working, but not the way mine were actually working when I tried it earlier :-). For me, 200 bins gives ticks that are exactly the same width as the bin; it looks like to reproduce the effect I was thinking of, you should use 100 bins.

**Comment by ellisonbg** [comment]
@njsmith ahh, yes, I have updated those examples in place with 100 bins and now they show exactly what you were talking about.

**Comment by njsmith** [comment]
@ellisonbg: Also, I vote for B, both because I like it, and also because "just do what seaborn does" is a good way avoid endless bikeshedding over tiny details. I think literally everyone agrees that seaborn has prettier and more thoughtful visual defaults than matplotlib :-).

Regarding the stylesheet thing -- yeah, I dunno what's most maintainable... from the user point of view I think the goal is that we somehow arrange it so that 1.last has `style.use("matplotlib2.0")` and 2.0 has `style.use("matplotlib1")`, and then it's just a question of technically how to arrange that with the minimum amount of manual copy-pasting. Maybe that means revising the rcParams code so that it takes its defaults from a named stylesheet, instead of having those as two separate concepts. Or maybe practicality beats purity and we should just write everything out manually instead of trying to be clever :-).

**Comment by ellisonbg** [comment]
Moving over the handling config using traitlets would help manage all of the defaults and styles. But for now, I think the number of changes we would be making are really small, so doing it my hand is probably fine. Question: would it be tolerable to have call to `style.use` to load the default style within matplotlib  itself?

**Comment by empet** [comment]
@njsmith A few examples where it is explicitly stressed that outward  tiks are not allowed:

- http://stackoverflow.com/questions/26367296/how-do-i-make-my-axis-ticks-face-inwards-in-ggplot2
- *All tick marks should be internal* [Taylor & Francis](http://www.tandf.co.uk/journals/authors/style/TRAM-guidelines.pdf)
- *Y-axis tick marks should be moved right (inwards)* [De Gruyter](http://www.degruyter.com/view/supplement/s03650588_Instruction_to_Authors.pdf)

Outward pointing tick marks are recommended in statistical data graphying, but I couldn't find any physics or (applied) math journal
displaying such figures.

**Comment by ellisonbg** [comment]
The Taylor and Francis document is itself inconsistent. When discussing
general illustrations and graphs it says that *All tick marks should be
external to the box*, but in the section on **SigmaPlot** it says they
should be internal. However, this inconsistency doesn't really make much of
a difference to the decision at hand.

I don't disagree that inward tick marks are common in certain journals. But
it doesn't take long of looking through one of these journals to see why
inward tick marks are a bad default (I spent a few minutes browsing Phys.
Rev. Lett.). Tick marks are either invisible because of the data, or tick
marks actively obscure the data.

I think there are situations where inward tick marks can be used
effectively. Tufte's book have plenty of examples. However, it requires
greater care and tweaking to make sure the tick marks don't interfere with
or distract from the data. Because of this, I think outward tick marks
represent a better default choice for the majority of cases.



On Mon, Jun 8, 2015 at 12:34 AM, Emilia Petrisor <notifications@github.com>
wrote:

> @njsmith <https://github.com/njsmith> A few examples where it is
> explicitly stressed that outward tiks are not allowed:
>
>    -
>    http://stackoverflow.com/questions/26367296/how-do-i-make-my-axis-ticks-face-inwards-in-ggplot2
>    - *All tick marks should be internal* Taylor & Francis
>    <http://www.tandf.co.uk/journals/authors/style/TRAM-guidelines.pdf>
>    - *Y-axis tick marks should be moved right (inwards)* De Gruyter
>    <http://www.degruyter.com/view/supplement/s03650588_Instruction_to_Authors.pdf>
>
> Outward pointing tick marks are recommended in statistical data graphying,
> but I couldn't find any physics or (applied) math journal
> displaying such figures.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/4502#issuecomment-109892680>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by efiring** [comment]
A quick look at Science shows some plots with inward ticks, others with outward.

In any case, it will be impossible to find a default style that matches every journal's requirements.  The purpose of default style settings is to make plots that work well in the early and middle stages of work--for seeing one's results, and for conveying them efficiently to colleagues via screen, projector, and printer output. For the last stage, publication (and the more polished web and conference presentations) it is understood that additional customization will usually be needed.

**Comment by WeatherGod** [comment]
I like outward ticks where there are tick labels, but inward (or none) on
the spines without labels. In the examples posted, the outward ticks makes
the plot look like a porcupine!

**Comment by ellisonbg** [comment]
Could someone add the "default changes" tag to this issue as I would like this one to be considered for the default style changes.

**Comment by ellisonbg** [comment]
To summarize some of the points that need to be considered along with the outward tick marks:

* Based on my playing (see above) I think the default tick mark lengths should be increased slightly.
* Another point that I have been talking about with @tacaswell wrt outward tick marks is that there should always be tick marks at the limits of each axis (when there are tick marks on that axis). @tacaswell said that this should probably be done with a separate marks that appear at the axis limits.

@tacaswell do I need to submit a PR for this to have it considered for the 2.0 release? The rcParams changes are trivial, but the code to add the axis limit ticks would be a bit more work (help?). I am also traveling for another week and a half and have limited coding time.

**Comment by njsmith** [comment]
I disagree about forcing tick marks to fall at the limits of each axis, actually. Here's some carefully hand-tweak autocorrelation functions from my thesis:

![acf](https://cloud.githubusercontent.com/assets/609896/9153440/ef69cc28-3e0a-11e5-881a-922d725594b6.png)

Notice how to make these figures work, it's crucial both that the ticks go outward, and also that we don't put the lower axis limits *quite* at 0, because if we did then the data and the axes would bump into each other and make the figure unreadable. Forcing the addition of some extra tick marks labeling -0.05 or whatever would look absolutely awful.

For comparison, here's how R and current matplotlib handle that first plot by default:

R: `plot(c(1, rep(0, 1999)), type="l")`

![r](https://cloud.githubusercontent.com/assets/609896/9153445/8ae53a02-3e0b-11e5-9a36-764f099f17d8.png)

Matplotlib: `plt.plot([1] + [0] * 1999)`

![matplotlib](https://cloud.githubusercontent.com/assets/609896/9153450/a7192bde-3e0b-11e5-977d-6ef06ec1d4d0.png)

The R version isn't as nice as the hand-tweaked version at the top, but it's *functional* in a way that the matplotlib just isn't.

**Comment by njsmith** [comment]
(This is closely related to #4891)

**Comment by efiring** [comment]
I agree with Nathaniel. I strongly oppose the idea of putting any kind
of mark at the ends of the axes by default, without regard to regular
tick locations.  Labeled or not, such marks would only make the plot
messier.

I'm not opposed to increasing the default tick length, and barely in
favor of an outward default. It's close to 50-50; some plots will work
better with inward, others with outward.  One important disadvantage
of outward, especially when combined with longer ticks, is that it
reduces the ratio of plotting area to total axes area.

A basic design problem here is that we have a wide variety of units in
which various measures are expressed, and they scale differently.  In
too many cases, they don't scale in a way that makes sense.  Relevant
to the present topic, ideally one would probably want default tick
length, pad, and tick label font size to scale together.  But they
don't.

**Comment by efiring** [comment]
Two more points, or rather ticks:
1) With outward ticks, they don't need to be as long.
2) Consider thicker ticks as an alternative to longer ones.

**Comment by ellisonbg** [comment]
@njsmith I completely agree with your thinking about picking the xlim and ylim so that there is space between the data and the axes. I think that is mostly a separate issue from outward tick marks.

Originally, I thought exactly as @njsmith and @efiring about having tick marks at the end of axis lines. However, I have started to see a number of other vis libraries doing this and think it does add to the plot. Here is an example from vega with this style:

<img width="317" alt="screen shot 2015-08-09 at 7 08 21 pm" src="https://cloud.githubusercontent.com/assets/27600/9158352/285fe958-3eca-11e5-955f-a308da1c0905.png">

This plot has a number of other differences, but it illustrates the main visual idea.

There are a couple of purposes these end ticks serve:

* They indicate very clearly that there may be a fraction of a major tick worth of space at the edge of a plot and make this space easier to measure visually.
* They distinguish the edge of the data from the edge of the axis. Without these edge ticks, it can be difficult to tell if the last tick is the end of the data or just a regular tick position.
* When plots are panned (hard to show this) the edge ticks provide a visual anchor relative to the regular major/minor tick marks which are moving.

Even if the edge ticks don't make it as the default, I think it would be nice to have an rcparam to set them optionally.

**Comment by njsmith** [comment]
Oh, I see, these are special unlabeled ticks? What does vega do if you set the xlim on that plot to (-0.05, 5.05)?

(Might be good to open a separate issue for this, since I guess it's a new feature and somewhat orthogonal to the other issues here?)

**Comment by tacaswell** [comment]
The unlabeled ticks also make more sense if you are dropping the top and right spines.

This ticks would belong to the spine and be drawn independently of the tick marks (modulo some check to make sure that the first/last tick from the locators does not already fall on the edge).

**Comment by efiring** [comment]
I would say they make sense *only* for positions where the end of one
spine is not the start of another.  Even then, they work only when
well separated from the nearest genuine tick, so they should not be a
default.

**Comment by WeatherGod** [comment]
Is the spine logic even aware of the ticker in such a way to know if a tick
is getting drawn near the edge?

**Comment by tacaswell** [comment]
I don't think so, but they are both children of `Axis` so we can swing that without too much trouble.

**Comment by Tillsten** [comment]
On the topic of ticks: with 1.5 it is now possible to disable top and right spines, but not ticks. So adding 
ytick.left.visible and ytick.right.visible to the rcparms would be nice (same for xticks). Another nice feature would be able to have rounded ticks.

**Comment by tacaswell** [comment]
Till, can you make a new issue for an rc param to turn off the ticks by
spine?  That is something that we probably should fix for 1.5 (close enough
to a bug fix I am ok with it going in).

Tom

**Comment by astrofrog** [comment]
FWIW, I was surprised today to see this new default, and am very much against it. While I can see situations where this can be useful, the following simple example is in my opinion much worse than before:

![test](https://cloud.githubusercontent.com/assets/314716/15325327/f7f6a1de-1c41-11e6-8294-ee7ef246382d.png)

I think what bugs me is the outward ticks on the top and right axes. Many of the examples I've found that look ok with outward ticks have ticks only on the left and bottom axes and no axes on the top and right. I don't think mixing the full axes box and outward ticks works. I'm not expecting the default to be changed back of course, but just wanted to make sure I voiced an opinion as a user, in case others feel the same.

**Comment by ellisonbg** [comment]
In many cases, there are reasons to remove the T+R axes+ticks. This usually makes sense when there is no/little data in the upper right portion of the plot that you need to judge the position of visually. Another approach is to put always keep the B+L axes+ticks and use grid lines to guide the eye. That is the route that vega-lite as gone:

<img width="254" alt="screen shot 2016-05-17 at 10 11 14 am" src="https://cloud.githubusercontent.com/assets/27600/15331742/9b7491a2-1c17-11e6-86e6-fbdaccef39ac.png">

I think the vega-lite style works well in general, but as a default in matplotlib, I think using grid lines by default is going a bit too far from. Thus the box+tick marks.

What I don't think is appropriate as a default style is to have no T+R axes+ticks and no grid lines. Then there is too little to guide the eye.

I have described the reasoning for outward tick marks above and won't repeat it again.
