### ISSUE TITLE
"Customizing matplotlib" should mention style sheets

### ISSUE THREAD

**Issue by wackywendell** [matplotlib/matplotlib#4507]
The current documentation on [Customizing matplotlib](http://matplotlib.org/users/customizing.html) talks about the `matplotlibrc` file, customizing the `matplotlibrc` file, and dynamically changing the `matplotlibrc` file, but does not mention the newly implemented [style sheets](http://matplotlib.org/users/style_sheets.html), which are instead filed under "Beginner's Guide."

I'll be happy to make a PR for this, but I thought I should introduce it as an Issue first for the sake of discussion.

**Comment by tacaswell** [comment]
:+1: Our docs are in need of some serious curation/organization.
