### ISSUE TITLE
Allow rotations and flips of 'x axis' in Geo projections

### ISSUE THREAD

**Issue by adrn** [matplotlib/matplotlib#4515]
The transformations that subclass `GeoAxes` could allow rotations by arbitrary angles and flips. 

Right now, the axes are fixed to be centered on longitude=0 with a range from -180 to 180, but it would be incredibly useful (at least to astronomers) to 

1. allow rotations in longitude so that, e.g., the plot could be centered on arbitrary longitudes, and
2. allow flipping the x (longitude) axis so that they increase to the *left*

This is somewhat related to #1856.

I started digging in to how I might implement this myself, but am totally unfamiliar with what is going on in `lib/matplotlib/projections/geo.py`...

cc @mdboom

**Comment by pelson** [comment]
@adrn - have you taken a look at cartopy? 1. is already implemented, and 2. should be reasonably straightforward given the machinery already available.

**Comment by pelson** [comment]
For that matter, does ``wcsaxes`` fit the bill?

**Comment by tacaswell** [comment]
Closing as out-of-scope for mpl core.
