### ISSUE TITLE
Customizing defauts with matplotlibrc

### ISSUE THREAD

**Issue by maxnoe** [matplotlib/matplotlib#4520]
It would be really nice if one could customize the default behaviour of matplotlib functions
with the matplotlibrc.

E.g. 

``` python
plt.rcParams['hist.histtype'] = 'step'
```

Or in the matplotlibrc with

```
hist.histtype : step
```

**Comment by tacaswell** [comment]
You can put in a PR to add that if you like.  You will need to change the code of `Axes.hist` to respect the new rcparam and add the param to `matplotlib.rctemplate` and `rcparams.py`.  This needs to be done in a way that does not break back-compatibility. 

In general, I am pretty resistant to adding any more complexity to `Axes.hist`.

**Comment by ibab** [comment]
Just thought about opening a similar issue when I found this one.
I think that `histtype` was just an example, and the suggestion is meant to go further than that.

I often find myself needing many additional rc options that are currently not exposed.
For example, our experiment has an established plotting style that I want to follow, that (among other things) requires me to use `horizontalalignment=True` for the axis labels.
Right now there's no way to set many of these options from a `matplotlibrc`, which means I can't create a stylesheet with our established style.

It would be wonderful if we could set arbitrary defaults on a per-function or per-artist basis.
It looks like this would require a large rewrite, though.
Have there been previous thoughts about going in this direction?

Seeing as implementing this would require a lot of work, are we encouraged to submit PRs if we find we have a need for setting a certain parameter from a `matplotlibrc`?

**Comment by MaxNoe** [comment]
Yes, the histtype was just meant as an example.
 I had also a more general approach in mind. 
But that would probably be a real big effort to have every default customizable.
But probably easier than just a few selected.

**Comment by DanielGoldfarb** [comment]
> You can put in a PR to add that if you like. You will need to change the code of `Axes.hist` to respect the new rcparam and add the param to `matplotlib.rctemplate` and `rcparams.py`. This needs to be done in a way that does not break back-compatibility.

@tacaswell 
Tom,  I can't find either file: `rctemplate*` nor `rcparams.py`.  

Am I correct to assume those files don't exist anymore (since your comment is almost 5 years old)?  What I am seeing is `defaultParams` being defined in file `matplotlib/rcsetup.py`.   Has this replaced `rctemplate` and `rcparams.py` ?  (fyi, for context, I'm in the middle of writing a utility that allows one to quickly compare two styles and see exactly what the differences are).  

Thanks.  --Daniel

**Comment by timhoffm** [comment]
It’s `matplotlibrc.template` and `rcsetup.py`.

**Comment by jklymak** [comment]
An approach for customizing methods is to wrap them and release them as your own specialty package.  The advantage of this is reproducibility.  Future users of your code and even your self will not have access to your old matplotlibrc whereas it's pretty easy to pip install a package off of GitHub.
