### ISSUE TITLE
Alpha Channel does not work with custom colormaps

### ISSUE THREAD

**Issue by charleslaw** [matplotlib/matplotlib#4529]
I upgraded to matplotlib 1.4.3 (on osx) and ran the script:

https://github.com/matplotlib/matplotlib/blob/master/examples/pylab_examples/custom_cmap.py

and the output did not match what was expected - the varying alpha and alpha=1 graphs look the same.  The colormap is ignoring the alpha channel.  A copy of the expected output is shown here:

http://matplotlib.org/examples/pylab_examples/custom_cmap.html

**Comment by charleslaw** [comment]
A little more to add.  The alpha did not show up in version 1.1.1 which I had installed previously.  I upgraded to make sure it's not a bug that has already been fixed, and it was still broken.

**Comment by tacaswell** [comment]
http://matplotlib.org/devdocs/examples/pylab_examples/custom_cmap.html is built from the current master and seems to be working.

Does it work if you the figure to png?  Which backend are you using?

**Comment by charleslaw** [comment]
It does not work if I save a PNG.  The backend is "MacOSX".  I also just tried TkAgg (I added matplotlib.rcParams['backend'] = 'TkAgg' near the top of my script) and that did not work either.

**Comment by WeatherGod** [comment]
You will need to do `matplotlib.use('TkAgg')`. Setting the backend rcparam
from within the script is useless as the backend has already been selected
at that point.

**Comment by charleslaw** [comment]
Thanks for the tip.  Unfortunately, the alpha is still ignored.

**Comment by tacaswell** [comment]
@WeatherGod Is this a known issue with the osx backend?

**Comment by WeatherGod** [comment]
I think you mean to ask @mdehoon

**Comment by tacaswell** [comment]
No, I meant to ask you before we called in the expert ;)

**Comment by WeatherGod** [comment]
touche

**Comment by mdehoon** [comment]
I cannot reproduce this bug. Both tkagg and the MacOSX backend produce the correct image when I run the test script with matplotlib 1.4.3.

**Comment by charleslaw** [comment]
Looks like the issue is on my end.

I double checked pip and it showed 1.4.3, and then I pip uninstalled matplotlib, and everything still ran (and was still broken).  I printed `matplotlib.__version__` and `matplotlib.__file__` and found version 1.1.1 installed in `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/`.  I removed this folder & reinstalled with pip and it works without issue :)

Sorry for the trouble, and thanks for looking into it.
