### ISSUE TITLE
matplotlib.pyplot.plot does not use the kwarg 'c'

### ISSUE THREAD

**Issue by JacksonTanBS** [matplotlib/matplotlib#4531]
In Matplotlib 1.4.3, when plotting a line, the function `plot` does not use the color property if the keyword `c` is used. Using position kwarg or `color` works just fine. For example,
```
import matplotlib.pyplot as plt
plt.plot([0, 1], c = 'm')
plt.plot([0, 2], 'm')
plt.plot([0, 3], color = 'm')
plt.show()
```
gives
![figure_1](https://cloud.githubusercontent.com/assets/10673754/8167888/22922bde-136f-11e5-8608-ef587dccd850.png)

My system: Matplotlib 1.4.3, Python 3.3.2 64-bit, CentOS 6.6.

I have also tested this with an Anaconda installation of Python 3.4.1 on Windows 7. When running Matplotlib 1.4.0, `c` works fine; after upgrading to 1.4.3, it breaks.

**Comment by WeatherGod** [comment]
I believe this should be all fixed in master already

**Comment by JacksonTanBS** [comment]
Is that so? I am not adept enough to find where the `plot` function is in the raw code. If you can confirm that, I'll close the issue straight away.

I apologize if this has already been reported. I have been looking through the issues and could not find anything on this.

**Comment by WeatherGod** [comment]
Yeah, I think Issue #4162 addressed covered this.

**Comment by JacksonTanBS** [comment]
Ah! Thank you very much!

I shall close the issue and improve upon my skill in searching for issues!
