### ISSUE TITLE
Confusion about the number of contour levels

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#4537]
According to the docstring, `plt.contour(X, Y, Z, N)` should "contour *N* automatically-chosen levels".

The actual results are somewhat surprising:

```python
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
xx, yy = np.mgrid[-3:3:, -3:3]

for _ in xrange(10):
    zz = np.random.randn(6, 6)
    cset = plt.contour(xx, yy,  zz, 9)
    print(len(cset.levels)),
```
prints `9 9 8 8 9 9 8 8 9 9`.

Additionally, the docstring for `plt.contourf` has the same prose, but adds some more confusing behavior:

```python
for _ in xrange(10):
    zz = np.random.randn(6, 6)
    cset = plt.contourf(xx, yy,  zz, 9)
    print(len(cset.levels)),
```
prints `11 10 11 10 10 11 10 11 11 11` (note that the `N` is the same as for the `contour` call above).

Am I missing something, or is this is a bug?

**Comment by WeatherGod** [comment]
Hmmm, might be a bug. More specifically, I don't think it is selecting the
contour levels correctly. I should note that it is expected that contourf()
will return two extra contour levels because filled contours needs bounds,
but this should be made clearer.

Just to add some more debugging, here is some output from a degenerate case:
```
>>> zz.min(), zz.max()
(-1.5362436862772237, 1.9436211856492926)
>>> cset = plt.contour(xx, yy, zz, 9)
>>> cset.levels
array([-1.2, -0.8, -0.4,  0. ,  0.4,  0.8,  1.2,  1.6])
>>> cset = plt.contourf(xx, yy, zz, 9)
>>> cset.levels
array([-1.6, -1.2, -0.8, -0.4,  0. ,  0.4,  0.8,  1.2,  1.6,  2. ])
```

Don't know if we need to ping Ian on this or not.

**Comment by efiring** [comment]
It's not a bug, but the documentation should say "approximately N".  The `_autolev` method uses a `Locator` to choose nicely spaced levels; it does not guarantee exactly N. The use of N rather than explicitly set levels is intended for quick-look applications.
