### ISSUE TITLE
Qt backend should have default way to zoom out

### ISSUE THREAD

**Issue by jondo** [matplotlib/matplotlib#4539]
In the PyQt4 backend, the "Zoom to rectangle" button can only be used to zoom in. I suggest to zoom out instead when a keyboard modifier (e.g. Shift) is pressed. In this case, the original view should be mapped into the region defined by the rectangle.

I know about [programmatic ways to improve zooming](https://gist.github.com/tacaswell/3144287), but this is about a better experience for new Matplotlib users.

**Comment by WeatherGod** [comment]
Doesn't drawing the zoom rectangle with the right mouse button (as opposed
to the left mouse button) work? Zooming in with the left and zooming out
with the right should work across all backends.

**Comment by tacaswell** [comment]
Yes, zoom tool + right click zooms out on all backends.  The zoom factor is `(width_of_zoom_box / current_width)`

**Comment by jondo** [comment]
... and I have learned something, thank you! So there's just a problem with detectability.

**Comment by tacaswell** [comment]
this also reminded me to make an issue about moving the zoom factory code over https://github.com/matplotlib/matplotlib/issues/4540

**Comment by OceanWolf** [comment]
With MEP 22/27 coming out in the next release, I will create a help tool as I think that will solve a lot of these problems...
