### ISSUE TITLE
add scroll-to zoom to main codebase

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4540]
I have an example of how to install a scroll event call back to zoom, this should be moved over to be in core.

see https://gist.github.com/tacaswell/3144287 + comments on how to improve it.

**Comment by tacaswell** [comment]
attn  @giadang

**Comment by OceanWolf** [comment]
Which part(s) do you want to go in to core?  As far as I see it mainly looks like this should go in with MEP 22...

**Comment by tacaswell** [comment]
Enough parts so that every new axes is scroll-zoomable.

Getting mep22 into more backends should be a priority.

**Comment by OceanWolf** [comment]
I agree, I think MEP27 looks done on GTK3 (other stuff can get added later), waiting for @fariza to confirm, before sending a call out to all developers but I haven't heard from him in a week...

Once the MEP27 main branch gets in we can make PRs for the other backends.

**Comment by tacaswell** [comment]
I have lost track of which MEP is which,  I think the toolbar work needs to be moved to the other backends ASAP to try and make the next point release and the gcf refactor is not going to make the next point release.

**Comment by OceanWolf** [comment]
MEP22 = Toolbar, MEP27 = Window (Gcf).

In terms of other backends, MEP27 by far the farthest ahead (see the checklist at the top of the PR #4143) the backends "converted" just need a slight tweaking to update them to a slightly newer API.  Also I feel MEP27 will make MEP22 a lot easier to implement, on the other hand doing just MEP22 now means we have to put Gcf into the new ``backend_tools`` which will make it more complicated to remove later on and require more dirty hacking...

**Comment by OceanWolf** [comment]
@tacaswell bottom line, we can make the release date of end of July for MEP22+MEP27, but with just MEP22 that becomes more difficult, especially when you consider backends such as ``WebAgg`` (which MEP27 has already solved), but also for the ``SubplotTool`` class which with just MEP22 we will have create a subclass per backend, but with with MEP27 we have just the one class.  We just need to get MEP27 off the launchpad (reviewed), and then clear sailing from then on.

**Comment by fariza** [comment]
@tacaswell the scroll to zoom is already there
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_tools.py#L625

**Comment by fariza** [comment]
@tacaswell  I reopened because I didn't know if you wanted this outside MEP22 (NavigationToolbar2)

**Comment by fariza** [comment]
Closing it because it's solved by MEP22

**Comment by QuLogic** [comment]
I'd say this is more directly resolved by #30405.
