### ISSUE TITLE
fix typo in figure docs

### ISSUE THREAD

**Issue by CallumColvine** [matplotlib/matplotlib#4562]
Docstring for set_canvas() is:
"Set the canvas the contains the figure"
it should be:
"Set the canvas that contains the figure"

**Comment by tacaswell** [comment]
@CallumColvine Can you put in a PR with that change?  For documentation changes like this you can even do it completely through the web interface (click the pencil icon at the top of https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/figure.py ).

**Comment by tacaswell** [comment]
Closed by #4578
