### ISSUE TITLE
Plot cropping with sphinxext plot_directive

### ISSUE THREAD

**Issue by cmbant** [matplotlib/matplotlib#4563]
The sphinxext/plot_directive.py code to produce matplotlib plots for documentation uses figman.canvas.figure.savefig.

This tends to incorrectly crop, e.g. truncating axis labels. I found it works OK if you add  bbox_inches='tight'. However a general solution would probably also allow specification of bbox_extra_artists, to correctly account for more general plotting situations.

Sample docstring code to reproduce the issue::

```
    .. plot::
       :include-source:

       import matplotlib.pyplot as plt
       plt.figure(figsize=(4,3))
       plt.plot([1, 2])
       plt.xlabel('x-label', fontsize=24)
       plt.ylabel('y-label', fontsize=24)
```

(the output plot files also do not seem to get rebuilt if the source changes)

**Comment by Tillsten** [comment]
Would it be a reasonable fix to just call `tight_layout`?

**Comment by WeatherGod** [comment]
tight_layout() is not the same as bbox_inches='tight'. They do different
things. So, it depends on what you want. Do you want to resize the figure
(use bbox_inches='tight'), or resize the plot (use tight_layout())?

**Comment by Tillsten** [comment]
I know the difference, both are possible solutions to problem presented here,
where each has its own disadvantage.

*   tight_layout  changes the figure layout slightly.
*   bbox_inches=`tight` changes the size of the resulting picture.

**Comment by moorepants** [comment]
I'm using the plot directive with images that have equal aspect ratio axes but are much wider than they are tall. `bbox_inches='tight'` with `savefig()` produces the image I desire, i.e. without large white upper/lower margins in the resulting png. Being able to set bbox_inches in the plot directive would solve the issue.

**Comment by moorepants** [comment]
I have not been able to achieve what bbox_inches='tight' does without the argument to savefig. If there is another way, i can do that. The solution that seems most obvious to me is to have a new option on the plot directive that can set bbox_inches='tight' for the savefig call int the plot directive.

**Comment by moorepants** [comment]
Looks like there is a way to do this. In the sphinx `conf.py` you need:

```python
plot_rcparams = {'savefig.bbox': 'tight'}
plot_apply_rcparams = True  # if context option is used
```

**Comment by ImportanceOfBeingErnest** [comment]
My argument from above is that such option to the conf.py should not be added. 

Using `figsize` and `subplots_adjust` the figure can be manipulated inside the code itself to come out in the desired way.

**Comment by moorepants** [comment]
As said before I have not been able to achieve what bbox_inches='tight' does with various plot commands. Can you point me to an example of doing this?

**Comment by ImportanceOfBeingErnest** [comment]
It's really hard to know what problem you face.  
If there is something overlapping the figure's edge (say on the right side of it) you can make the figure wider (`figsize=(7, 4.8)`) and provide more space (`fig.subplots_adjust(right=0.8)`). If there is too much space to one side (say the top), you make the figure smaller (`figsize=(6.4, 3)`). 

Maybe you want to share a minimal runnable example of the problem you face such that one may solve this in some code? Or if you want to submit a PR with an example here, which is otherwise ready, just do it and one can also modify the actual code directly?
