### ISSUE TITLE
Add stylesheets to mimic Seaborn and Bokeh

### ISSUE THREAD

**Issue by petebachant** [matplotlib/matplotlib#4566]
These would be very helpful. Currently I am using Seaborn just to get the default plot styling, and it would be nice to remove the dependency.

**Comment by tacaswell** [comment]
Would you be interested in writing those style sheets?   I think we already have a ggplot style sheet (or at least a PR with one).

**Comment by petebachant** [comment]
Sure, I will give it a shot.
