### ISSUE TITLE
mpl.image.AxesImage array is stored as a MaskedArray

### ISSUE THREAD

**Issue by ericdill** [matplotlib/matplotlib#4567]
@efiring 

I was surprised that `AxesImage.get_array()` returns a `MaskedArray`. Talking with @tacaswell offline, he was also surprised and thinks that it might involve at least one extra memory copy that is not needed.  Can you shed some light on why AxesImage is storing its data as a MaskedArray?

**Comment by efiring** [comment]
The use of masked arrays to keep track of missing values is fairly deeply embedded, although increasingly there has been a trend to switch to using nans internally (as in all the C++ code) when the use of floating point is assured.
In AxesImageBase.set_data(), the input array is passed through safe_masked_invalid.  This allows us to transparently support incoming data with nans and/or masked values, regardless of the type or dtype.  No copy is made when converting an ndarray to a masked array.  Note that the ability here to preserve the type of an input array while respecting any existing mask is important; it permits the use of direct integer indexing into the LUT, as well as the use of uint8 rgba.
