### ISSUE TITLE
race condition in log scale + locating minor ticks

### ISSUE THREAD

**Issue by brentmsmith** [matplotlib/matplotlib#4581]
I'm trying to plot minor ticks in fixed locations, but when I attempt to use the FixedLocator, it generates 99970 points, and creates ticks outside of my defined range, down to 0.0307 up to 99.9991. I think this may be a bug. Here is my relevant code:

``` python
import matplotlib
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111,yscale='log',xscale='log')
ax.xaxis.set_major_formatter(matplotlib.ticker.ScalarFormatter())
ax.yaxis.set_major_formatter(matplotlib.ticker.ScalarFormatter())
ax.xaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
ax.set_xlim(0.98,9.05)
ax.set_ylim(3e-2,100)
ax.set_xticks([1,2,3,4,5,6,7,8,9])
ax2=ax.twiny()
ax2.set_xlim(0.98,9.05)
ax2.set_xscale('log')
majort=[1,1.1546,1.3519,1.619,2.0166,2.7159,4.5123]
ax2.set_xticks(majort)
minort=[1.073,1.2467,1.4741,1.7952,2.3078,3.3476,7.7718]
minloc = plt.FixedLocator(minort)
ax2.xaxis.set_minor_locator(minloc)
ax2.set_xticklabels(['0','2','4','6','8','10','12'])
plt.show()
```

**Comment by bsmith18** [comment]
One solution I found was to set ```ax2.minorticks_off()``` before defining the new fixed minor ticks.

**Comment by tacaswell** [comment]
This can be produced much more simply

This blows up 
```python
import matplotlib
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

ax.set_yscale('log')
ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
```

with a terrifying trace back

```python

Traceback (most recent call last):
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 286, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/cbook.py", line 564, in process
    proxy(*args, **kwargs)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backend_bases.py", line 2810, in mouse_move
    artists = event.inaxes.hitlist(event)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/artist.py", line 348, in hitlist
    L.extend(a.hitlist(event))
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/artist.py", line 347, in hitlist
    for a in self.get_children():
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/axis.py", line 705, in get_children
    minorticks = self.get_minor_ticks()
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/axis.py", line 1313, in get_minor_ticks
    numticks = len(self.get_minor_locator()())
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/ticker.py", line 1927, in __call__
    return self.raise_if_exceeds(np.array(locs))
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/ticker.py", line 982, in raise_if_exceeds
    raise RuntimeError(msg)
RuntimeError: Locator attempting to generate 10000301 ticks from 1.09e-07 to 0.099999991: exceeds Locator.MAXTICKS

```

but

```python
import matplotlib
import matplotlib.pyplot as plt
fig, ax = plt.subplots()


ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
ax.set_yscale('log')

```

works correctly.

**Comment by bsmith18** [comment]
That's strange, I don't get any errors until I try to set the secondary
axis minor ticks:

```
Traceback (most recent call last):

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper

    draw(artist, renderer, *args, **kwargs)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/figure.py",
line 1085, in draw

    func(*args)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper

    draw(artist, renderer, *args, **kwargs)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py",
line 2110, in draw

    a.draw(renderer)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper

    draw(artist, renderer, *args, **kwargs)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axis.py",
line 1114, in draw

    ticks_to_draw = self._update_ticks(renderer)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axis.py",
line 957, in _update_ticks

    tick_tups = [t for t in self.iter_ticks()]

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axis.py",
line 907, in iter_ticks

    minorLocs = self.minor.locator()

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/ticker.py",
line 1758, in __call__

    return self.raise_if_exceeds(np.array(locs))

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/ticker.py",
line 944, in raise_if_exceeds

    raise RuntimeError(msg)

RuntimeError: Locator attempting to generate 99970 ticks from 0.0307 to
99.9991: exceeds Locator.MAXTICKS

```

Running matplotlib version 1.4.3

On 3 July 2015 at 17:00, Thomas A Caswell <notifications@github.com> wrote:

> This can be produced much more simply
>
> This blows up
>
> import matplotlibimport matplotlib.pyplot as plt
> fig, ax = plt.subplots()
>
> ax.set_yscale('log')
> ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
>
> with a terrifying trace back
>
> Traceback (most recent call last):
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 286, in mouseMoveEvent
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/cbook.py", line 564, in process
>     proxy(*args, **kwargs)
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/cbook.py", line 430, in __call__
>     return mtd(*args, **kwargs)
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/backend_bases.py", line 2810, in mouse_move
>     artists = event.inaxes.hitlist(event)
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/artist.py", line 348, in hitlist
>     L.extend(a.hitlist(event))
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/artist.py", line 347, in hitlist
>     for a in self.get_children():
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/axis.py", line 705, in get_children
>     minorticks = self.get_minor_ticks()
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/axis.py", line 1313, in get_minor_ticks
>     numticks = len(self.get_minor_locator()())
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/ticker.py", line 1927, in __call__
>     return self.raise_if_exceeds(np.array(locs))
>   File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/ticker.py", line 982, in raise_if_exceeds
>     raise RuntimeError(msg)RuntimeError: Locator attempting to generate 10000301 ticks from 1.09e-07 to 0.099999991: exceeds Locator.MAXTICKS
>
> but
>
> import matplotlibimport matplotlib.pyplot as plt
> fig, ax = plt.subplots()
>
>
> ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator(10))
> ax.set_yscale('log')
>
> works correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/4581#issuecomment-118438866>
> .
>



-- 
Brent Smith
PhD Student, School of Earth and Space Exploration, Arizona State University

**Comment by tacaswell** [comment]
I was testing on master.

What are you running to get that back trace ? Please do not include any
code which is not needed to reproduce the problem, it really does help the
devs track down the problem faster.

**Comment by bsmith18** [comment]
I only needed the code from my initial post to reproduce the error.

**Comment by cimarronm** [comment]
The problem is that `AutoMinorLocator` is only designed to work on a linear axis. It just assumes the scale is linear and can end up creating an enormous amount of ticks.
```python
class AutoMinorLocator(Locator):
    """
    Dynamically find minor tick positions based on the positions of
    major ticks. Assumes the scale is linear and major ticks are
    evenly spaced.
    """
```

**Comment by cimarronm** [comment]
I added PR #5267 to throw a warning instead of blindly assuming the axis is linear and then raising an exception when the number of ticks is too large

**Comment by archman** [comment]
Simple questions:
1: How do you count the ticks number?
2: First turn on minor ticks, then turn off ticks, then turn on again, how many minor ticks are required?

It looks like the ticks number grows when I did the on/off iteration?

Thanks.

**Comment by QuLogic** [comment]
Current Matplotlib runs both @tacaswell's and @brentmsmith's code without crashing, and on the latter warns that `AutoMinorLocator` does not work with log scale. The ticks appear to be at the specified positions as well.
