### ISSUE TITLE
Matplotlib IPython Widget

### ISSUE THREAD

**Issue by blink1073** [matplotlib/matplotlib#4582]
I created a stub of a demo for a matplotlib interactive widget targeting IPython 3.2, for discussion.

https://gist.github.com/blink1073/0421d774677f8ffb98fe
http://nbviewer.ipython.org/gist/blink1073/0421d774677f8ffb98fe

**Comment by blink1073** [comment]
cc @pelson

**Comment by blink1073** [comment]
Here's what it comes down to:  we create a random `div` [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_nbagg.py#L279).
If I instead force it to use the div created by the ipywidget, we get the initial draw, but then [find_output_cell](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_mpl.js#L181) fails.

I see two options:
1) Modify `FigureManagerNbAgg` to accept an optional uuid and add some hackery to `find_output_cell` to handle the widget case.
2) Make the notebook backend always use a widget.  We can still export a raw static display.  See the QGrid [widget](https://github.com/quantopian/qgrid/pull/27#issuecomment-136091123) I created for an example.

**Comment by tacaswell** [comment]
So long as on save you still get a static png I am in favor of option 2.

The future work on figure serialization + the future work on persistent widgets has a very nice synergy.

**Comment by pelson** [comment]
I'm in favour of option 2 too if we can pull it off. Is there anything I can help with, or have you got everything you need @blink1073?

**Comment by blink1073** [comment]
@pelson, all I need is another 6 hours a day :smile:

**Comment by pelson** [comment]
I know that feeling :smile:

**Comment by ellisonbg** [comment]
I also think the notebook backend should always use a widget.

**Comment by fariza** [comment]
@blink1073 did you see structure of `ToolManager` and the interaction with `Tools` (the result of MEP22)
Also, with MEP27 @OceanWolf  is introducing a new **architecture** of FigureManager, Window, layout... 
I say this because to finalize MEP22 and MEP27 we are going to be porting all the backends, and with this and all new development (backend related) it would be easier if it's compatible with the new structure of things.

**Comment by blink1073** [comment]
I was only planning to attack the "which websocket" and "which div" part of the equation, at least to start.

**Comment by OceanWolf** [comment]
Not sure if that will overlap, I haven't seen much of the code of ``NbAgg`` yet, only ``WebAgg`` which I rewrite a large part of including the websocket and div part... I did most of it, but it annoyed the heck out of me (having spent about 40 hours on it, where as the other backends only took around 4 or so), then it went on ice to concentrate on the main branch (GTK3) of MEP27.  Imagine then I will do the easy ``TkAgg`` before resuming ``WebAgg`` and fix up ``NbAgg``.
