### ISSUE TITLE
use mkdtemp in _create_tmp_config_dir

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4597]
See https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp

Noted while reviewing #4591 

Python now has a function in tempfile which will ensure we get a usable directory in 'the most secure way possible' which seems better than rolling our own.

**Comment by souravsingh** [comment]
I would like to work on it.How do I go with it? Do I have to change the entire function to use mkdtemp()?

**Comment by KanwarGill** [comment]
@tacaswell We are working on this and we have a question. So what we understand from the code is that:

- It first gets the _tempdir_ of the system matplotlib is being run on. 
- Then it gets the login name _username_ of the user. 
- Then it uses os.path.join to create a directory address like tempdir/matplotlib-_username_. 
- Afterwards it sets the environment variable "MPLCONFIGDIR" to the newly created temp directory.
- Then it creates the tempdir/matplotlib-_username_ directory using the _mkdirs()_ function from book.

Our question is, when we use _mkdtemp_, do we use the same directory naming format as the current version or do we use the built-in naming convention that mkdtemp() provides–that is, creating a random string as the name for the directory?
