### ISSUE TITLE
 Error shows when I import  matplotlib after installation

### ISSUE THREAD

**Issue by ice-melon** [matplotlib/matplotlib#4598]
I use command `pip install matplotlib` to install it successfully. But when I type `pip list`, there is no matplotlib package in the list.

When I try 

    python2.7 -c 'import matplotlib; print matplotlib.__version__, matplotlib.__file__'

It shows

     1.4.3 /usr/local/lib/python2.7/site-packages/matplotlib/__init__.pyc

But when I try `import matplotlib.pyplot as plt` in .py file, an error shows

 

     import matplotlib.pyplot as plt
     ImportError: No module named pyplot

What makew me confused is that when I import matplotlib in python interpreter, no error shows.

I follow http://matplotlib.org/faq/installing_faq.html to check the installation. Installation seems succeed.

**Comment by jenshnielsen** [comment]
Which platform are you on? I don't know what exactly is wrong but I would guess that perhaps you have several  matplotlib installations on top of each other. Pip it not clever enough to remove all installations not installed by pip. 

I would recommend manually removing all matplotlib related folders from /usr/local/lib/python2.7/site-packages and then verify that matplotlib is completely removed  i.e. ```import matplotlib``` should fail

And then reinstalling matplotlib with pip

**Comment by ice-melon** [comment]
@jenshnielsen System is OS X 10.10.3.  I have tried your method but still not work. matplotlib only exist in python interpreter.

**Comment by tacaswell** [comment]
Also check which python interpreter you are using in each case.

**Comment by jenshnielsen** [comment]
What is the output of ```which python```? 

If you are using OSX system python (/usr/bin/python) then it ships it's own matplotlib version (1.3.1) which is likely to conflict with the one you are trying to install. 

If that is the case I would recommend installing you own python version from either homebrew or anaconda and use that.

**Comment by ice-melon** [comment]
@tacaswell python 2.7.10 is the interpreter of each case

**Comment by ice-melon** [comment]
@jenshnielsen `which python` shows `/usr/local/bin/python` . I use homebrew to setup the python environment.

**Comment by jenshnielsen** [comment]
@ice-melon Thanks, Im puzzled that setup sounds very similar to my setup which works as expected. 

Is it pyplot missing of is it the difference between the script and running from the command line?

i.e. does 
```
python2.7 -c `import matplotlib.pyplot as plt`
``` 

work?

**Comment by ice-melon** [comment]
@jenshnielsen scripts have no difference

**Comment by jenshnielsen** [comment]
@ice-melon sorry I don't understand at all what you are trying to say. 

Does 

```
python2.7 -c `import matplotlib.pyplot as plt`
```
work?

**Comment by ice-melon** [comment]
@jenshnielsen 
not work
`zsh: command not found: import
Argument expected for the -c option
usage: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' fo`

**Comment by jenshnielsen** [comment]
Sorry the one about have the wrong quotes

```
python2.7 -c 'import matplotlib.pyplot as plt'
```

**Comment by ice-melon** [comment]
@jenshnielsen works well

**Comment by jenshnielsen** [comment]
So can you confirm whether plotting a simple example works i.e. does the following work?

```
python2.7 test.py 
```

where test.py contains something like:

```python
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()
```

**Comment by jenshnielsen** [comment]
Actually reading your original error message I think you must have 
something like:

```
import pyplot
```

somewhere in your script.

```
import matplotlib.pyplot
```
should display:
```python
In [1]: import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-565170aa375b> in <module>()
----> 1 import matplotlib.pyplot as plt

ImportError: No module named 'matplotlib.pyplot'
```

**Comment by ice-melon** [comment]
@ Yes! You have reproduced the error

**Comment by jenshnielsen** [comment]
No I have not. It is a different error

The error that I get says ```No module named 'matplotlib.pyplot'``` yours says ```No module named 'pyplot'``` that is not the same

your error indicates that you are trying to do ```import pyplot``` somewhere which will not work

**Comment by ice-melon** [comment]
@jenshnielsen I only have one line code `import matplotlib.pyplot as plt`

**Comment by jenshnielsen** [comment]
Ok that might be python version difference giving different import errors. 

The most likely reason is that you are running your scripts with a different python interpreter than the one that you are using from the command line (with the -c option). How are you executing your scripts? 

Do you still get the error if you execute the simple example that I quoted above.

**Comment by jenshnielsen** [comment]
Also does

```
import matplotlib
```

work from a script?

**Comment by ice-melon** [comment]
@jenshnielsen  The python interpreter is same. `import matplotlib` actually work well.

**Comment by jenshnielsen** [comment]
Ok What does 

```python
import matplotlib
print matplotlib.__version__
matplotlib.__file__
```

do if you put it into a script compared to the command line as you did above?

**Comment by ice-melon** [comment]
@jenshnielsen thanks for your patience
in file
`  print matplotlib.__version__
AttributeError: 'module' object has no attribute '__version__'`


in terminal


` print matplotlib.__version__
1.4.3
 matplotlib.__file__
'matplotlib/__init__.pyc'`

**Comment by jenshnielsen** [comment]
Ok we are getting somewhere now.

Can you try without the second line so that we can actually see the result of the last line.

```python
import matplotlib
print matplotlib.__file__
```

**Comment by WeatherGod** [comment]
I see what is wrong... Chun, do you have a directory called "matplotlib"
for some reason at your current working directory? And does it have a blank
__init__.py file in it? When calling scripts or python from that directory,
and importing matplotlib, it will pick up that directory first, rather than
the install of matplotlib. That is why "pyplot" and "__version__" aren't
being found.

**Comment by jenshnielsen** [comment]
@WeatherGod I agree with you that is probably the reason or it could just be a matplotlib.py file? 

Printing matplotlib.__file__ would confirm what is going on

**Comment by WeatherGod** [comment]
He did, a few responses ago. It was "matplotlib/__init__.py". It did also
have a __version__ attribute, so I am wondering now if he is sitting in the
matplotlib source directory?

**Comment by ice-melon** [comment]
@WeatherGod @jenshnielsen Thanks guys, there is a matplotlib.py file in current directory.

**Comment by rohbhot** [comment]
I'm using OpenCV with Ubuntu 16.04
My matplotlib is installed only in python 2.7. What do you suggest I do for me to use the same library with another version of python viz. python 3.5 installed in my system ? 

My .py files run if properly using matplotlib if I type python2.7 instead of python3 in terminal. Kindly suggest.

**Comment by tacaswell** [comment]
@rohbhot Please send your question to the mailing list (matplotlib-users@python.org you will have to subscribe to post un-moderated).

**Comment by OsamaFayed** [comment]
## Cloud any one experience the below error while installing 'pyplot' package
_Collecting pyplot
  Could not find a version that satisfies the requirement pyplot (from versions: )
No matching distribution found for pyplot_

**Comment by jenshnielsen** [comment]
@OsamaFayed This is really a question that is better for the user mailing list. But anyway there is no python package called pyplot. You want to install matplotlib `pip install matplotlib` and `import matplotlib.pyplot as plt` from python

**Comment by harrypotter0** [comment]
You have two pythons installed on your machine, one is the standard python that comes with Mac OSX and the second is the one you installed with ports (this is the one that has matplotlib installed in its library, the one that comes with macosx does not).

/usr/bin/python
Is the standard mac python and since it doesn't have matplotlib you should always start your script with the one installed with ports.

If python your_script.py works then change the #! to:

#!/usr/bin/env python
Or put the full path to the python interpreter that has the matplotlib installed in its library.

[Source](https://stackoverflow.com/questions/18176591/importerror-no-module-named-matplotlib-pyplot)

**Comment by PeterSI92** [comment]
Im a complete newb trying to follow a tutorial. had the same exact error message. try saving your program in a different folder. It worked for me somehow

**Comment by Zeo312** [comment]
@PeterSI92 Dude you saved my life, thank you!

**Comment by bnanilgowda** [comment]
Deleting PIL folder in site-package works the matplotlib

**Comment by kobbycyber** [comment]
i slove it by installing python-tk using sudo apt install python-tk
