### ISSUE TITLE
Qt figure options colors in text fields

### ISSUE THREAD

**Issue by rmccampbell** [matplotlib/matplotlib#4600]
If you assign any of the text fields in the figure options dialog to a "color-like" string, it changes into a color field the next time you open the dialog. This happens even in some not-so-obvious cases, like the letter 'y' (which you'd think you'd be able to use for a y axis label). This would be a little difficult to fix since the form dialog code is pretty complex, but a quick solution would be to only consider #ffffff style strings as colors, and add a helper function to convert the color properties to this format. a better solution would be to either wrap the color properties in an object, or add some kind of disambiguation parameter to the form parser (as an optional third entry in each tuple, i.e. "('Color', line.get_color(), 'color')").

**Comment by tacaswell** [comment]
Thank you for reporting this.

Closing as a duplicate, I believe that this was fixed by #4304.  Please ping to have re-opened if you can reproduce this on master.
