### ISSUE TITLE
min mock version on travis

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4613]
It seems that is the last day mock went from version 1.0.1 -> 1.1.0 and is now broken (for different reasons) on both 2.x tests

**Comment by jenshnielsen** [comment]
I can take a look

**Comment by tacaswell** [comment]
Thanks

It looks like mock is getting auto installed by setup.py instead of
explicitly.

**Comment by jenshnielsen** [comment]
It looks like we are not the only ones http://lists.idyll.org/pipermail/testing-in-python/2015-July/006504.html

I will start with setting the version explicitly

**Comment by tacaswell** [comment]
Fixed by #4616
