### ISSUE TITLE
Followup items from the matplotlib 2.0 BoF

### ISSUE THREAD

**Issue by njsmith** [matplotlib/matplotlib#4614]
From the notes here:
https://docs.google.com/document/d/1ftNmQn7QVr6m2mkgVYTd_0eTA_o7vn9t3sliVp9cKOw/edit?pli=1

* [x] Put a notice on the front page of the matplotlib website informing people that this change is underway, and link to some information on how to participate (wiki page, link to github search for issues tagged 'new-style' or something?)
* [ ] Announce to relevant communities (e.g. scipy-users)
* [ ] Get in touch with Brian Granger to get their visual designer involved in the process
* [ ] It might be good to file bugs for the items on the notes page above that had broad consensus, so they don't get forgotten and slip through the cracks? (Many of them are rather small.)

[This could probably use a milestone 2.0 or something, but I don't think i have the authority to modify that]

**Comment by jenshnielsen** [comment]
Proposal for change of imshow interpolation is in #4622
