### ISSUE TITLE
Default bottom of Stepfilled histograms should be set according to ymin

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4621]
Follow up to #4606 and #4608 

Compare bar:

``` python
import numpy
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1)
hist1 = ax.hist(1, bins=1, normed=False, log=True, histtype='bar', label='No bottom', alpha=1, facecolor='red')
offset = 1e-9
ax.set_ylim(1e-4, 1.1)
ax.legend()
plt.show()
```

![bar](https://cloud.githubusercontent.com/assets/548266/8629222/edfeb7fc-271e-11e5-8ebb-e20093f1f31a.png)

to stepfilled:

``` python
import numpy
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1)
hist1 = ax.hist(1, bins=1, normed=False, log=True, histtype='stepfilled', label='No bottom', alpha=1, facecolor='red')
offset = 1e-9
ax.set_ylim(1e-4, 1.1)
ax.legend()
plt.show()
```

![stepfilled](https://cloud.githubusercontent.com/assets/548266/8629232/12bea534-271f-11e5-8733-40351e13fa74.png)

Setting bottom is not really a correct solution since it shifts the top of the bar with the same amount

**Comment by petehuang** [comment]
@jenshnielsen can you update the second code snippet? I think it's the same as the first. Thanks :)

**Comment by jenshnielsen** [comment]
I don't remember this but I think it should be correct now

**Comment by tacaswell** [comment]
Tagged as medium difficulty because hist.

**Comment by DhrumilSoft** [comment]
I was interested in working on this. Can you please verify some things. Currently, the bottom is set to be 1/logbase by default for a stepfilled graph set to a log scale. If the bottom parameter is provided, it's value is used instead.  This seems to be the intended behaviour from the comments in the code. Is it supposed to be set to the lower ylim value instead when bottom isn't given?

**Comment by anntzer** [comment]
Probably the correct fix is some variant of https://github.com/matplotlib/matplotlib/pull/9477.

**Comment by DhrumilSoft** [comment]
I think this issue is somewhat different. Can you please clarify how the step filled histogram is supposed to behave when bottom isn't set. The coding is setting the default to 1/ logbase which seems to be reasonable.
