### ISSUE TITLE
Change default legend location to 'best'.

### ISSUE THREAD

**Issue by jhamrick** [matplotlib/matplotlib#4671]
Currently it is 'upper right', but a more sensible default is 'best'.

**Comment by jenshnielsen** [comment]
:+1:

**Comment by WeatherGod** [comment]
devil's advocate here... 'best' is magical, in a sense. I would argue that
the default remains at a predictable location. Second, I don't think 'best'
has really ever been fully vetted, especially from the perspective of the
'best' location. It is something to consider, but I am a little bit more
hesitant with this style change suggestion than with others.

**Comment by dopplershift** [comment]
It seems odd to me to have the "magic" and general one as anything other than the default.

**Comment by mdboom** [comment]
I think in the past there have been bugs with "best" where it would make really bad choices -- mainly due to not taking into account certain kinds of artists etc.  I think a lot of those classes of things have been addressed over time, however.  I'm fine with changing the default -- we may discover some remaining bugs there, of course, but we should just identify and address those as the come.

**Comment by jhamrick** [comment]
To further explain my reasoning for why I think the 'best' is a good default: for my plots, usually 90% of the time the current default (upper right) is wrong and I need to change it (I tend to have plots that show a positive linear correlation, and upper right is actually a *really* bad default for that). I would imagine that positive linear correlations are quite common for others as well. 

So, I have to change the location away from the default in almost every single case. I would personally much rather though have behavior that tries to pick a better location automatically and sometimes fails in ways that seem opaque, rather than having to almost certainly change the location for every plot.

**Comment by michaelaye** [comment]
:+1: for 'best'
