### ISSUE TITLE
Default marker edge width in plot vs. scatter

### ISSUE THREAD

**Issue by jhamrick** [matplotlib/matplotlib#4674]
The default marker edge width is inconsistent across `Axes.plot` and `Axes.scatter`, due to differences between lines and patches. When all the other defaults are updated, perhaps this could also be made consistent.

For plot, the edge width is currently 0.5 (from `lines.markeredgewidth`), and for scatter, it is 1.0 (from `patch.linewidth`).

**Comment by has2k1** [comment]
Maybe do this with new rcParams `xtick.linewidth` and `ytick.linewidth`.

**Comment by tacaswell** [comment]
Close this as the new defaults for these values are the same.
