### ISSUE TITLE
Handling of alpha values in plot vs. scatter

### ISSUE THREAD

**Issue by jhamrick** [matplotlib/matplotlib#4676]
The behavior of alpha values in plot vs. scatter is inconsistent.
- If the `alpha` keyword argument is specified, then the behavior is the same (which is to apply the alpha value to both the marker face color and the edge color).
- If the color is specified as rgba, then `plot` will also apply the alpha value to the marker edge color, while `scatter` will not (both will apply the alpha to the marker face color).

The reason for this is that `scatter` uses `'c'` to set the face color, but does not use it to set the edge color. On the other hand, in the `Line2D.draw` method, the alpha value is pulled from the rgba face color.

I have no strong preference for which of these is the right way to go, though I think I prefer the behavior of inheriting the alpha value, but it is also more complicated.

**Comment by jhamrick** [comment]
I spent some time investigating this tonight and I think it might be worth it to wait until the traitlets work is done so there is some consistency with the color representation. Currently, I don't think I can add a way for scatter to easily inherit the rgba values for the edge colors without adding a whole lot of checking for the various ways colors can be represented.

**Comment by efiring** [comment]
@jhamrick, work in this direction can go beyond colors--there are also inconsistencies in things like `markeredgewidth` (in plot) versus `linewidths` (note the plural) but `edgecolors` in scatter.  From collections to patches to lines to markers, it's quite a mess.

**Comment by jhamrick** [comment]
@efiring Yeah, I've been running into a few of these things and reporting them when I find them. #4674 is a case of the edge/line widths.

**Comment by tacaswell** [comment]
punting to color overhaul to buy some time and because it is an API change.
