### ISSUE TITLE
Priority between color and edgecolor/facecolor depends on dictionary iteration order

### ISSUE THREAD

**Issue by tobias47n9e** [matplotlib/matplotlib#4690]
I think there is a bug when passing a color-kwarg to the PatchCollection function when using the Gtk3Cairo backend in combination with Python 3.

I am using the master-branch of [mplstereonet](https://github.com/joferkington/mplstereonet) to plot PatchCollections, but because the bug only occurs randomly and only in the combination with Python3+Gtk3Cairo I think that the problem must lie with the rendering backend.

Test matrix for no color-kwarg passed (defaults to black):

| Python Version | Gtk3Agg | Gtk3Cairo |
| --- | --- | --- |
| Python 2.7.10 | works | works |
| Python 3.4.2 | not supported | works |

![screenshot from 2015-07-14 14-03-59](https://cloud.githubusercontent.com/assets/6953323/8672756/a96327de-2a31-11e5-8ec7-ac3dc5815b10.png)

Test matrix for no color="#ff00ff" passed:

| Python Version | Gtk3Agg | Gtk3Cairo |
| --- | --- | --- |
| Python 2.7.10 | works | works |
| Python 3.4.2 | not supported | random filling (p=~0.5) |

![screenshot from 2015-07-14 14-11-55](https://cloud.githubusercontent.com/assets/6953323/8672906/db0d0006-2a32-11e5-8965-42b2dc44299e.png)

This is the code of the examples:

```
import matplotlib.pyplot as plt
import mplstereonet
from gi.repository import Gtk

#Choose one of the 2 backends
#from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg as FigureCanvas
from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas

myfirstwindow = Gtk.Window()
myfirstwindow.connect("delete-event", Gtk.main_quit)
myfirstwindow.set_default_size(500, 500)
myfirstwindow.set_title('Matplotlib')

box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
myfirstwindow.add(box)

fig, ax = mplstereonet.subplots()
canvas = FigureCanvas(fig)

#Try with and without the "color"-kwarg
ax.cone([20, 30, 40, 50], [45, 130, 230, 315], [5, 10, 15, 20], facecolor="None",
        color="#ff00ff")
ax.grid(True)

box.pack_start(canvas, True, True, 0)
myfirstwindow.show_all()
Gtk.main()
```

**Comment by tacaswell** [comment]
We have seen a number of bugs like this before with python3 because the order of iteration of dictionaries is randomized.  This probably required a fix like #4198 

Can you reproduce this without using an external package?

**Comment by tobias47n9e** [comment]
@tacaswell - Yes, I could also reproduce it using this code:

    from gi.repository import Gtk
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
    from matplotlib.figure import Figure
    import matplotlib.patches as mpatches
    from matplotlib.collections import PatchCollection

    myfirstwindow = Gtk.Window()
    myfirstwindow.connect("delete-event", Gtk.main_quit)
    myfirstwindow.set_default_size(500, 500)
    myfirstwindow.set_title('Matplotlib')

    box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
    myfirstwindow.add(box)

    fig = Figure(figsize=(5,5), dpi=100)
    ax = fig.add_subplot(111)
    canvas = FigureCanvas(fig)

    patches = []

    circle = mpatches.Circle((0.2,0.2), 0.1,ec="none")
    patches.append(circle)

    rect = mpatches.Rectangle((0.5,0.5), 0.05, 0.1, ec="none")
    patches.append(rect)

    collection = PatchCollection(patches, facecolor="None", color="#ff00ff", alpha=0.3)
    ax.add_collection(collection)

    box.pack_start(canvas, True, True, 0)
    myfirstwindow.show_all()
    Gtk.main()

I also noticed that when I use the edgecolor-kwarg then everything works as expected. Should the color argument be deprecated for PatchCollections and just accept edgecolor and facecolor?

    collection = PatchCollection(patches, facecolor="None", edgecolor="#ff00ff", alpha=0.3)

**Comment by efiring** [comment]
On 2015/07/14 10:34 AM, Tobias Schönberg wrote:
> I also noticed that when I use the edgecolor-kwarg then everything works
> as expected. Should the color argument be deprecated for
> PatchCollections and just accept edgecolor and facecolor?

I don't think so; I'm not positive, but I think that "color" serves a 
useful purpose independently of "edgecolor" and "facecolor", and the 
problem comes when they are combined.  What we probably need to do is 
factor out the logic for handling this, and then make sure it is applied 
everywhere that it is needed.

**Comment by tacaswell** [comment]
I am 90% sure that this is unrelated to cairo as I think I was seeing this
last night with an agg backend.

**Comment by tacaswell** [comment]
I think this is fixed by #4686 which sorts the input to set by key before applying it.

**Comment by tacaswell** [comment]
@tobias47n9e This should be fixed now, can you confirm against current master?

**Comment by tacaswell** [comment]
Nope, still happens...

**Comment by QuLogic** [comment]
Now that the order of dictionary iteration is defined as part of the language spec, this works consistently in that the _last_ argument always wins.
