### ISSUE TITLE
Overlay blend mode

### ISSUE THREAD

**Issue by njsmith** [matplotlib/matplotlib#4700]
No time to put together a PR just now (I need to check out of this hotel!) but while skimming `colors.py` I just noticed:
```
        blend_mode : {'hsv', 'overlay', 'soft'} or callable, optional
            The type of blending used to combine the colormapped data values
            with the illumination intensity.  For backwards compatibility, this
            defaults to "hsv". Note that for most topographic surfaces,
            "overlay" or "soft" appear more visually realistic. If a
```

Sounds like a good candidate for a 2.0 change to me. AFAIK the HSV space is never the best option for pretty much anything :-).

**Comment by WeatherGod** [comment]
We would need to make that controlable via rcparams for 1.5.

**Comment by jenshnielsen** [comment]
The new overlay modes were AFAIK introduced by @joferkington but are yet not in a release. Usually we   wait a bit before chancing the default. It we change this we should make it an rcparam for 1.5 and add a warning that the default will change.

**Comment by WeatherGod** [comment]
We don't even really need a warning. It would be a part of the 2.0 style
changes. We just need to make sure we get the rcparam in for 1.5 so that
there is no new code for 2.0, just config changes.

**Comment by mdboom** [comment]
Which of 'overlay' or 'soft' would be the best default?

**Comment by joferkington** [comment]
`"overlay"` is a better default than `"soft"`, i.m.o.  

I've never seen a surface where overlay blending the hillshade looks terribly bad.  Sometimes it's less than ideal, but it's never awful.  By contrast, soft light blending hillshades can yield a result that's almost unnoticeable in many cases.  

From a purely qualitative standpoint, `"soft"` blending (which is Pegtop soft light blending, by the way) provides a very subtle hillshade effect.  It's too subtle for "smooth" surfaces.  `"overlay"` essentially gives more contrast to the hillshade effect.

Just my $0.02, at any rate.
