### ISSUE TITLE
Matplotlib differences MacOSX and other Aggs

### ISSUE THREAD

**Issue by JohnCC330** [matplotlib/matplotlib#4705]
When doing a simple plot:

    import matplotlib.pyplot as plt

    def test_plot():
        x = range(11)
        y = [x0**2 for x0 in x]

       plt.plot(x, y, 'o:', fillstyle='none', label = "1", ms = 10)
       plt.legend()
       plt.show()

    def main(args):
        test_plot()
        return 0

    if __name__ == '__main__':
        import sys
        sys.exit(main(sys.argv))

The circle symbols are dotted in MacOSX, but not in other Aggs.

Non-dotted circle symbols on Matplotlib 1.3.1 and 1.4.3 on Linux Mint, Slackware,
     and MacOSX (with backend set to GTKAgg or TkInter), even though no Gtk installed.

Dotted circle symbols on MacOSX with the default MacOSX  backend (and MPL 1.4.2)

[Thread on Stackoverflow](http://stackoverflow.com/questions/31408928/how-can-i-plot-hollowed-symbols-connected-with-dotted-lines-in-one-go/31410105?noredirect=1#comment50794519_31410105) with some more information.

**Comment by efiring** [comment]
Attn:  @mdehoon

**Comment by tacaswell** [comment]
To be clear, the MacOSX is not an Agg backend.

**Comment by jenshnielsen** [comment]
I can reproduce this with Matplotlib 1.4.3 but not with current master (python 2.7, OSX 10.10.3 ) @JohnCC330 do you have the option to install and test with the master branch?

**Comment by mdehoon** [comment]
> I can reproduce this with Matplotlib 1.4.3 but not with current master (python 2.7, OSX 10.10.3 ) 

I'm getting the same with python 2.7 and python 3.4; the bug shows up in matplotlib 1.4.3 but not with the current master (OS X 10.9.5).

**Comment by efiring** [comment]
With two reports that the bug cannot be reproduced on master, I am going to close this.
