### ISSUE TITLE
property collisions

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#4716]
In hunting down a bug for the property cycling, I found something that I am not quite sure how to fix. The properties for lines and patches created by `plot()` and `fill()` all eventually go through the following two functions:

```
    def set_lineprops(self, line, **kwargs):
        assert self.command == 'plot', 'set_lineprops only works with "plot"'
        for key, val in six.iteritems(kwargs):
            funcName = "set_%s" % key
            if not hasattr(line, funcName):
                raise TypeError('There is no line property "%s"' % key)
            func = getattr(line, funcName)
            func(val)

    def set_patchprops(self, fill_poly, **kwargs):
        assert self.command == 'fill', 'set_patchprops only works with "fill"'
        for key, val in six.iteritems(kwargs):
            funcName = "set_%s" % key
            if not hasattr(fill_poly, funcName):
                raise TypeError('There is no patch property "%s"' % key)
            func = getattr(fill_poly, funcName)
            func(val)
```

So, let's consider the case of a kwarg containing 'color' and 'facecolor'. When `set_color()` is called on a patch, it subsequently calls `set_facecolor()` and `set_edgecolor()`. If when iterating the dictionary, 'facecolor' comes after 'color', then everything is fine because facecolor should override color. But, if it happens the other way around, then 'facecolor' effectively gets ignored.

I think this has mostly been not noticed because users usually do not put in contradicting keys, and the color-cycling mechanism was mostly conservative. I am still trying to figure out how exactly this problem is just now popping up in my PR's unit tests, but it is an example of where we need a common code that will take a dictionary and properly sort it so that property setting works correctly every time.

**Comment by tacaswell** [comment]
We have been seeing a relative of in both `plot`,  `scatter`, and `collection` as well where half the time a default value over-rides a user value.

**Comment by has2k1** [comment]
I think I have this issue show up in `python 3.4` but `python 2.7` works as expected. My plotting command specifies both facecolor and color.

```python
        ax.scatter(x=pinfo['x'],
                   y=pinfo['y'],
                   facecolor=pinfo['fill'],
                   color=pinfo['color'],
                   marker=pinfo['shape'],
                   # Our size is in 'points' while
                   # scatter wants 'points^2'
                   s=np.square(pinfo['size']),
                   zorder=pinfo['zorder'],
                   alpha=pinfo['alpha'])
```

Not really an MWE, I will provide one when I get a chance.

**Comment by WeatherGod** [comment]
I wouldn't worry too much about it. It has been addressed in my Property
Cycling PR (although, all I did was make the current behavior consistent
with constructors and not subject to randomness). In your example, color
would override facecolor after my PR. We might change that for 2.0 (have
facecolor override color).

**Comment by efiring** [comment]
Seems no longer relevant.  Closing.
