### ISSUE TITLE
pep8 tests are not really running but reporting success

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4720]
see: https://travis-ci.org/matplotlib/matplotlib/jobs/71292068

attn @jenshnielsen as the poor soul who is the testing expert

I am starting to think we should roll back #4668 and #4708

**Comment by tacaswell** [comment]
@HolgerPeters Any suggestions?

**Comment by jenshnielsen** [comment]
tests.py is still there and I think it still works. So we should be able to buy some time time by just reverting Travis to run tests.py again.

I have opened a PR to do that. #4723

**Comment by jenshnielsen** [comment]
I happy to look more into this. However I am traveling back to the UK tomorrow so I will be cut of from the internet

**Comment by tacaswell** [comment]
Fixed by #4723
