### ISSUE TITLE
Sort out how to auto-nbconvert notebooks as part of doc build

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4728]
This will let us start to include narrative notebooks in the docs. 

The IPython docs do this already, I think we can just borrow how they do it.

**Comment by mdboom** [comment]
This could dovetail well with plans to link to live notebooks as well.

**Comment by tacaswell** [comment]
Made redundent by sphinx gallery work

**Comment by jklymak** [comment]
@tacaswell - *can* we now do docs w/ notebooks?  That'd be so much more fun than trying to write rst (Not that I'm ragging on rst, I just don't know it very well, whereas I write notebooks all the time).

**Comment by dopplershift** [comment]
No notebooks, we use sphinx-gallery to convert python scripts into notebooks during the documentation build process.
