### ISSUE TITLE
The mailing list is down

### ISSUE THREAD

**Issue by jkseppan** [matplotlib/matplotlib#4735]
I sent a message to matplotlib-devel via gmane.org, but it hasn't gotten through, and I cannot access the list archives either. It seems that sourceforge.net is [experiencing major trouble](https://twitter.com/sfnet_ops/status/621859945487581184).

I'd like to suggest that we move the mailing lists elsewhere. Sourceforge has been in the news recently for bundling adware with their downloads, and [many projects are leaving](https://notepad-plus-plus.org/news/notepad-plus-plus-leaves-sf.html). I wonder if scipy.org would be willing to host matplotlib mailing lists aside [the numpy and scipy lists](http://www.scipy.org/scipylib/mailing-lists.html).

@matplotlib/developers

**Comment by tacaswell** [comment]
The numpy and scipy lists also have a good deal of down time.

**Comment by efiring** [comment]
I seem to recall having seen quite a few reports over the years of the scipy lists going down, also; but maybe not enough occasions to worry about it.  Other than that, being in parallel with numpy and scipy lists seems like a logical organization.
Oddly, I just tried to access the ipython list, http://projects.scipy.org/mailman/listinfo/ipython-dev, and can't get in.  It is hanging.

**Comment by efiring** [comment]
I wonder whether consolidation of infrastructure like this is a place where Numfocus (horrible name) could and should step in.

**Comment by mdboom** [comment]
scipy.org hasn't had a perfect uptime record, but at least it's controlled by people who are a lot more aligned with our interests.  I'm happy enquire about the possibility.

Aside from that, are there any other good alternatives?  Google Groups seems an obvious choice, but you never know when something will end up on Google's chopping block...

**Comment by efiring** [comment]
I would rather go the scipy route than the Google Groups route.
Long-term, a complete migration away from sourceforge for *all* services looks inevitable.  I think the decline is irreversible.

**Comment by jkseppan** [comment]
I like to follow mailing lists through gmane.org, which seems to often have problems with Google Groups.

One mailing list provider used by several lists is freelists.org, but I don't have any experience with them.

**Comment by matthew-brett** [comment]
We (neuroimaging) folks just switched from scipy.org to python.org for our
mailing list.

We had been on scipy.org for a long time, but the mailing list and admin
interface were starting to become unreliable.

I emailed postmaster@python.org and got a quick friendly response there.

Cython has been at python.org for a while without any problems I'm aware of.
​

**Comment by efiring** [comment]
I like the idea of switching to python.org.  @mdboom, would you like to inquire there?

**Comment by jkseppan** [comment]
Looks like we have switched to python.org. gmane.org is now following the new lists at python.org, I don't know how to update Nabble, and the web page needs updating. I'll make a PR about that.
