### ISSUE TITLE
Docs build hangs at pylab_examples/system_monitor example 

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4736]
See https://travis-ci.org/matplotlib/matplotlib/jobs/71414788

I suspect this happens after the merge of #4506 That example still calls plt.ion()

**Comment by tacaswell** [comment]
But what is odd is that the tests passed on that commit: https://travis-ci.org/matplotlib/matplotlib/builds/71330399

**Comment by jenshnielsen** [comment]
Could it be a combination of this and the MEP12 done on the same example in #4648 ?

**Comment by tacaswell** [comment]
Closing as this is fixed.
