### ISSUE TITLE
Difference between backend_wx and backend_wxag?

### ISSUE THREAD

**Issue by buhtz** [matplotlib/matplotlib#4740]
What is the difference between backend_wx and backend_wxag?
Which one should I use, when I use matplotlib-1.5dev with wxPhoenix_dev* on Python3?

**Comment by jenshnielsen** [comment]
http://matplotlib.org/faq/usage_faq.html#what-is-a-backend it AFAIK the best explanation of the different backends. Basically the WX backend uses build in WX to render the image while the WXAgg backend uses Agg which is the primary rendering engine for Matplotlib. In general we recommend the Agg backends. In the future questions like this are probably better suited for the matplotlib user mailing list

**Comment by buhtz** [comment]
The "list" http://sourceforge.net/mail/?group_id=80706 suggested on http://matplotlib.org/ is not available.

**Comment by efiring** [comment]
Yes, sourceforge is still in the recovery process from a massive failure.  We shouldn't need to mention the list in the README.rst; it points to the home page where that information is provided.

**Comment by buhtz** [comment]
Thanks for the hint. SF is missing this important piece of information (pointing to Twitter isn't a solution). Just a new reason to show SF your back.
