### ISSUE TITLE
bug in dark_background and transparent = True ?

### ISSUE THREAD

**Issue by marcocamma** [matplotlib/matplotlib#4745]
Thanks for the great work !
I find the style.use( ... ) a great enhancement.
Unfortunately it is not behaving as I would expect.
The two images saved by the code below are essentially identical
```python
import matplotlib.pyplot as plt
import numpy as np
plt.style.use("dark_background")
plt.plot( np.random.random(size=100) )
plt.savefig("dark1_notransparent.pdf",trasparent=False)
plt.savefig("dark1_transparent.pdf",trasparent=True)
```

I usually save pdfs for inserting plots in latex/beamer and I would really prefer to have no background, just whitish lines and text.

Given the name of the style (dark_background) maybe the observed behavior is to be expected. In this case would it be possible to have another style ?

I am using matplotlib 1.4.2-3.1 (debian sid)

Thanks,
marco

**Comment by jenshnielsen** [comment]
There is a typo in your call to savefig `trasparent` vs `transparent` with `transparent` everything works as expected for me. It is unfortunate and annoying that many MPL functions happily swallow mistyped kwargs which makes typos hard to catch.

**Comment by marcocamma** [comment]
really sorry (and embarrassed),
I confirm that everything works as expected.
I agree it is a bit unfortunate ...
thanks,
marco
