### ISSUE TITLE
Incorrect dependency handling from local pip

### ISSUE THREAD

**Issue by BanHammor** [matplotlib/matplotlib#4749]
I am trying to install matplotlib from a local pip repository on an internet-locked machine using a commandline like this:

```
pip install numpy matplotlib --index=http://path/to/localindex
```

While pip runs numpy's setup.py before matplotlib's, numpy doesn't install properly until after matplotlib's installation is attempted (And failed, since numpy is not downloaded from global pip).

This may or may not be solved by deferring dependencies on numpy until setup_requirements are met, but I am not an expert in python packaging.

**Comment by tacaswell** [comment]
Have you tried this with current master?  There have been some recent changes to setup.py

As a work around do this in two steps:

```
pip install numpy
pip install matplotlib
```

**Comment by anntzer** [comment]
Closed for lack of activity (and response from the OP).
