### ISSUE TITLE
fill_between saved as svg extends beyond boundaries of chart

### ISSUE THREAD

**Issue by adamcc** [matplotlib/matplotlib#4750]
![fill_between_bug](https://cloud.githubusercontent.com/assets/497933/8797542/b36aee7c-2fce-11e5-9677-7ec5be55fcf3.jpg)
I used fill_between to chart some error envelopes around data, then used plt.xlim([-20,20]) and then saved it to svg.

When opened in Adobe Illustrator I saw this - the average plot line is neatly inside the axes, but the envelope extends to the full data range.

**Comment by tacaswell** [comment]
can you post a minimal working example and/or the svg?

We see numerous reports like this and almost always it is a bug in the rendering software.

**Comment by adamcc** [comment]
![test](https://cloud.githubusercontent.com/assets/497933/8799921/aafc1ef2-2fe0-11e5-8884-48843934aa1f.png)

Github doesn't support .svg, so I changed the extension to .png, but its an .svg file

plt.figure()
time = df['Epoch time']
plt.plot(time, mchunk, color='#5882FA')
plt.xlim([-20,20])
plt.ylim([0,1.2])
plt.fill_between(time, CI[0].T, CI[1].T,
    alpha=0.2,  color='#81BEF7',
    antialiased=True)
plt.xlabel('Minutes after feed')
plt.ylabel('Median Speed (mm/s)')
plt.xlim([-20,20])
plt.ylim([0,1.2])
plt.savefig('test.svg')

This was run in a Jupyter Notebook, data are a pandas dataframe (time) and nparray (CI)

**Comment by mdboom** [comment]
What are you using to view the SVG?  In my own testing, it is broken in known-non-compliant renderers based on librsvg, but it works fine in Firefox, Chrome and Inkscape.

**Comment by adamcc** [comment]
I'm opening it in Adobe Illustrator. For editing should I try Inkscape instead?  Illustrator is pretty common for figure editing.

**Comment by mdboom** [comment]
That's a bummer that Adobe isn't following their own spec here.

**Comment by mdboom** [comment]
I suppose we'll have to find a workaround if a major piece of software is broken like that...

**Comment by tacaswell** [comment]
There was a promise of someone writing a little snippet to reorder the
elements after the fact.

I think this should be raised with adobe as a bug in their software, but
with us.  The spec is very clear on having no order dependencies.

What version of illustrator?

**Comment by mdboom** [comment]
FWIW, https://github.com/RazrFalcon/SVGCleaner seems to produce something that librsvg likes.  Illustrator may as well (though I don't have a copy to test with).

**Comment by adamcc** [comment]
I'm using Adobe Illustrator CS5.1

The lines are not visible until I click on the object, nor fully selectable as elements themselves.
