### ISSUE TITLE
Bar plot seems not to understand numpy.uint8 dtype

### ISSUE THREAD

**Issue by chriswl** [matplotlib/matplotlib#4751]
When I do 

    from matplotlib import pyplot as plt
    import numpy as np
    plt.bar(np.array([0, 1, 2, 3], dtype=np.uint8), [2, 3, 4, 5])

I get an unexpected result -- the values for the bar centers are interpreted as `[0, 257, 258, 259]`. Similar things do not happen with `plt.plot` and `plt.scatter`. The environment is matplotlib v. 1.4.3, numpy v. 1.9.2. in an IPython notebook, IPython v. 3.2.

This is a screenshot of the above example after doing `plt.gca().set_xlim([250, 260])`.
![screen shot 2015-07-21 at 20 40 22](https://cloud.githubusercontent.com/assets/2842628/8809410/c6290570-2fe8-11e5-84fa-2b16735137dd.png)

**Comment by tacaswell** [comment]
I can confirm this....what?!

**Comment by tacaswell** [comment]
The issue is actually down in the patch code.  I suspect some of the transforms are silently hitting integer overflow.  The question is where is the right place to do a cast to float.

**Comment by tacaswell** [comment]
ok, so the problem is that call to `rotate_deg_around` buried deep in the rectangle code which does 

```python
    def rotate_deg_around(self, x, y, degrees):
        """
        Add a rotation (in degrees) around the point (x, y) in place.

        Returns *self*, so this method can easily be chained with more
        calls to :meth:`rotate`, :meth:`rotate_deg`, :meth:`translate`
        and :meth:`scale`.
        """
        return self.translate(-x, -y).rotate_deg(degrees).translate(x, y)
```

which with uints wraps around and is _then_ cast to float.
