### ISSUE TITLE
rubber band in qt5agg slow

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4753]
Using the zoom tool to draw a rectangle lags behind mouse movement a noticeable amount, but panning is snappy.

**Comment by pwuertz** [comment]
There were 2 reasons for this. Rubberband was using draw instead of draw_idle, and the xy coordinates which are also updated while moving the rubberband were drawn in a synchronous way. Both problems are fixed in master and I'm seeing no lags anymore.

**Comment by fariza** [comment]
can we close this?

**Comment by jenshnielsen** [comment]
I think so, I have not noticed any slowdown in QT5 lately

**Comment by fariza** [comment]
please reopen if problem persist
