### ISSUE TITLE
PolarAxes documentation is confusing.  Constructor bug?

### ISSUE THREAD

**Issue by bhlevca** [matplotlib/matplotlib#4755]
In the documentation for the `PolarAxes` class one of the valid kwargs for self.set_rgrids is `fontproperties`, which theoretically should allow you to change the font size and font type.

```
self.set_rgrids(radii = radii, labels = radii_labels,
                           angle = self.radii_angle, **kwargs)
```

However, it is unclear from reading the documentation if the same kwargs are valid for the constructor. Apparently not, fontproperties is not valid for the constructor as I get an error if do that.

Since I have a wrapper class `MyPolarAxes`, which calls directly the constructor of  `PolarAxes`

```
fp = FontProperties(size=18)
ax = MyPolarAxes(fig, rect, axisbg = 'w', fontproperties = fp)
```

I created a new property self.rfontsize in the new class that is set inside the constructor, and later is passed when `self.set_rgrids` is called.

Perhaps I should suggest the `matplotlib` maintainers to either update the docs to make clear what kwargs the constructor of `PolarAxes` accepts, or modify the constructor to accept all the kwargs that are documented for `self.set_rgrids`.

**Comment by tacaswell** [comment]
Is that a typo in your issue title?  

Why do you have a wrapper/sub class of `PolarAxes`?

The typical way that args/kwargs work in constructors is that they fall through to `Artist` where eventually we do something like

```python
for k, v in kwargs.items():
    getattr(self, 'set_{}'.format(k))(v)
```

which works decently for single arguments, but is bad for passing anything more complicated.   I don't think we should get in the business of trying to guess when things should be unpacked as `*v` or `**v`.

attn @QuLogic I believe you are looking at this region of the code base?  

attn @rmorshea This should be on your radar for things that should be cleaned up with traitlets.

**Comment by bhlevca** [comment]
Yes it was a typo in the title. I fixed that.

The problem is that if I am passing to the constructor only  one `kwargs` , in my case `fontproperties`,   it fails. However, if I pass `fontproperties` directly to `self.set_rgrids` it is fine, 

It is either a bug in the constructor or the documentation should be updated to reflect what the constructor accepts as valid `kwargs`  

I created a subclass to enhance the functionality  (e.g. windrose) . I wanted to pass `fontproperties` to the class and reuse that as you mentioned and fall through for all the subsequent class methods.

**Comment by tacaswell** [comment]
what is windrose?  If it is just a new kind of plot it is probably easier to create a function that takes an axes as an input rather than creating a subclass.

**Comment by bhlevca** [comment]
Look here for an example: http://youarealegend.blogspot.ca/2008/09/windrose.html

No, in this case encapsulation is more elegant than delegation.

Anyway, I think that the documentation or the code should be fixed as the `PolarAxes` constructor does not accept `fontproperties`. Form the documentation you would expect that.

**Comment by tacaswell** [comment]
Can you point to where in the documentation you would expect this?

I have skimmed the linked code and I am not fully convinced that long term sub-classing `PolarAxes` is the right thing to do, everything you are doing can be done as functions.  For example you override `bar` which could be very surprising for users, where as `wr.bar(ax, data)` will always do the right thing.

**Comment by bhlevca** [comment]
Still the documentation may lead to confusions:

1) http://matplotlib.org/devel/add_new_projection.html
2) search for PolarAxes
3) seach for PolarAxes.set_rgrids ( the only place where kwargs are mentioned for this class)
4) scroll down to fontproperties

**Comment by QuLogic** [comment]
It is perhaps prudent to note that [this RadarAxes example](http://matplotlib.org/examples/api/radar_chart.html?highlight=radaraxes) does exactly what @bhlevca is doing by subclassing `PolarAxes`.

**Comment by QuLogic** [comment]
I'm not sure what version this issue is about, but the docs have listed all keyword arguments [since 2.2.3](https://matplotlib.org/2.2.3/api/projections_api.html#matplotlib.projections.polar.PolarAxes).
