### ISSUE TITLE
Basemap Glitch?

### ISSUE THREAD

**Issue by avipersin** [matplotlib/matplotlib#4759]
Hi,

I'm plotting on a Basemap using:

m = Basemap(projection='robin', lon_0=0, resolution='c')
m.hexbin(x, y, C=values, gridsize=74, cmap=plt.cm.jet)

It seems there is some glitch causing some of the hexagons to be plotted just outside the border.  If you look at the map border you will see it.  

Here is an image: http://imagebin.ca/v/29XPJc4HrS31

**Comment by WeatherGod** [comment]
Looks like Basemap's hexbin method should be setting a clip-path of the
map's frame, not the axes's frame (which is the default).

**Comment by avipersin** [comment]
Is there a workaround to prevent this behavior?

**Comment by WeatherGod** [comment]
There should be a workaround, but I haven't had time to figure it out. In
theory, one would take the object that forms that ellipse, and set it as
the clip-path for the object returned by m.hexbin(). I just don't know for
sure what that object is that forms the ellipse.

**Comment by efiring** [comment]
Basemap is handled separately now, and is in limited maintenance mode, so I'm closing this.
