### ISSUE TITLE
Default linewidth thicker than axes linewidth

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#4760]
As part of the default changes, I think some consideration should be made to differentiating the axes from the data in the axes.  I like how seaborne or ggplot does this, but even simpler is just setting the default line width to be thicker than the axes linewidths.  Of course there are times one wants thinner lines, but the default of 1 is quite thin for many plots and doesn't differentiate itself from the axes at all.

**Comment by jenshnielsen** [comment]
I think a thicker default linewidth makes sense. This came up in the Scipy bof too. See 
#4614 and the notes within the doc from that session: https://docs.google.com/document/d/1ftNmQn7QVr6m2mkgVYTd_0eTA_o7vn9t3sliVp9cKOw/edit?pli=1#heading=h.vax93dd688bv

**Comment by jklymak** [comment]
Ok, great!  Sorry I didn't read that document first, but I support a default line width>1.  Maybe 2 or 3 is good.  Assuming that list is going to be acted on, this can be closed.  

Thanks!

**Comment by jenshnielsen** [comment]
Im keeping this open as everything it that document really should have an issue so that we don't forget anything important. We just haven't gotten around to create them all yet.

**Comment by QuLogic** [comment]
I believe everything in that document has been implemented or has its own issue.
