### ISSUE TITLE
Conflict of local module Collections

### ISSUE THREAD

**Issue by Mrngilles** [matplotlib/matplotlib#4764]
I noticed I am not able to load IPython from the `matplotlib/lib` folder because the local `collections` module conflicts with the python `collections` module.
Maybe the local name could be changed, unless you guys have an idea how to solve this? Or am I doing something wrong?
If it has to be changed, I propose to change from `collections` to `collection`, but it is not as an accurate name...

**Comment by WeatherGod** [comment]
Firing up python/ipython/etc from within the source directory of almost any
project is not advisable. Furthermore, matplotlib had the "collections.py"
code for a lot longer than Python did in the standard library.

**Comment by tacaswell** [comment]
This is also the reason that in python 3 all of the imports are absolute (search from the top down not bottom up) and the reason we use the absolute import future in all of our files.  Kind of surprised that IPython does not.

Also, renaming mpl's version of collections would break a horrendous amount of user code.

**Comment by Mrngilles** [comment]
It also happens when using pylint from emacs, where I guess it launches pylint on the file from the current folder. I don't know if I can work around to get it to work, or if I'll have to launch pylint from anywhere else in the terminal. 

On July 23, 2015 3:42:23 PM GMT+02:00, Benjamin Root <notifications@github.com> wrote:
>Firing up python/ipython/etc from within the source directory of almost
>any
>project is not advisable. Furthermore, matplotlib had the
>"collections.py"
>code for a lot longer than Python did in the standard library.
>
>On Thu, Jul 23, 2015 at 8:33 AM, Gilles Marin
><notifications@github.com>
>wrote:
>
>> I noticed I am not able to load IPython from the matplotlib/lib
>folder
>> because the local collections module conflicts with the python
>collections
>> module.
>> Maybe the local name could be changed, unless you guys have an idea
>how to
>> solve this? Or am I doing something wrong?
>> If it has to be changed, I propose to change from collections to
>> collection, but it is not as an accurate name...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/matplotlib/matplotlib/issues/4764>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/matplotlib/matplotlib/issues/4764#issuecomment-124105878

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tacaswell** [comment]
I have worked around the emacs + plint issue before but I do not remember how...  This should probably be reported as a bug against `pylint`.

If you can, switch to python 3 and this problem goes away ;)

**Comment by Mrngilles** [comment]
The problem is that I am already running python 3... I'm looking into changing the cwd in emacs when working on matplotlib files... But that just seems like a bad fix for this 

On July 23, 2015 4:26:21 PM GMT+02:00, Thomas A Caswell <notifications@github.com> wrote:
>I have worked around the emacs + plint issue before but I do not
>remember how...  This should probably be reported as a bug against
>`pylint`.
>
>If you can, switch to python 3 and this problem goes away ;)  
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/matplotlib/matplotlib/issues/4764#issuecomment-124123422

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tacaswell** [comment]
Try updating pylint/making sure that emacs isn't seeing a system pylint

I just ran pylint on 2.7 (in a venv) and 3.4 (in a conda env) in the source directory and both worked fine.

**Comment by Mrngilles** [comment]
Alright I'll try that. Thanks 

On July 23, 2015 4:43:00 PM GMT+02:00, Thomas A Caswell <notifications@github.com> wrote:
>Try updating pylint/making sure that emacs isn't seeing a system pylint
>
>I just ran pylint on 2.7 (in a venv) and 3.4 (in a conda env) in the
>source directory and both worked fine.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/matplotlib/matplotlib/issues/4764#issuecomment-124128496

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by WeatherGod** [comment]
The problem does not "go away" in python3 because "import foo" will
*always* import foo.py if it is in the current working directory (or is it
the current directory of the module calling the import?). That has not
changed with py3k.

On Thu, Jul 23, 2015 at 10:34 AM, Gilles Marin <notifications@github.com>
wrote:

> But that just seems like a bad fix for this


In any case, the fix is not in matplotlib. Matplotlib's codebase uses
absolute import references and is correct, and we are not going to change
the name of a long-standing module just because the python environment is
being fired up in an inadvisable location. The problem is in the inherent
ambiguity of "import foo", and thus, a systemic issue within the Python
ecosystem.

**Comment by Mrngilles** [comment]
Yes sure, that's what I though. I'll try to fix that on my part. Thank you again

**Comment by tacaswell** [comment]
@WeatherGod Ah, I understand what I was confused about now. Thanks for the correction!

**Comment by tacaswell** [comment]
The rule is `import foo` searches `sys.path`, where has `import .foo` searches the folder that the importing module is in.

**Comment by dopplershift** [comment]
There's also a difference that `import .foo` only works within a package.

**Comment by Mrngilles** [comment]
If anybody is interested, I kind of fixed this by making a .pth file with `import sys; mpl_local = [s for s in sys.path if "matplotlib/lib/matplotlib" in s]; [sys.path.remove(m) for m in mpl_local]; [sys.path.append(m) for m in mpl_local];` in it.
It just puts the local folder at the end of the sys.path if you're workin in `matplotlib/lib/matplotlib` folder.
