### ISSUE TITLE
Tests not independent of each other

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/matplotlib#4772]
Opening an issue on this to track progress and get insight from other people.

I have just been playing with tests on my own system, and I have discovered that the tests don't run fully independently of each other...

So far, I have only discovered problems with different backends getting used, for example in ``test_backend_qt4.py`` we have a few tests that have :
```python
plt.switch_backend('Qt4Agg')
```
``test_backend_pgf.py`` seems to have the solution to this with a generic decorator, and it feels odd that such a beautifully generic decorator appears in a very specific class and doesn't get used elsewhere.

Anyway I shall make a PR to correct this backend thing and hope we have no other inter-dependancies, but in the meantime, some questions:
1. Why don't we reset everything at the beginning of each test anyway, we have a ``setup()`` function that should do this?
2. Do we have an easy way to print debug information for tests?  I.e. specific rcParams?  This will help debugging future issues like this (touch wood we don't get any).

**Comment by WeatherGod** [comment]
In my classic mode PR, I updated the ImageComparisonTest class to apply a
specified style (defaults to "classic") and then upon cleanup, revert back
to the rc defaults. Not a decorator, but it works. It seems to have solved
some other problems people have noticed where rare situations of test
failures would "bleed" custom style information to other tests, causing
them to fail.

**Comment by tacaswell** [comment]
The image test and cleanup decorators already do a good deal of clean up related to the rcparams.

**Comment by OceanWolf** [comment]
About to make a PR for this, one more question for this PR, why don't we have the qt5 tests in ``default_tests``?

I also notice that in quite a few modules we import six from externals, I remember reading elsewhere that we didn't want to do that... what gives?

**Comment by OceanWolf** [comment]
oh, and also, why do we have no differences between ``lib/mpl_toolkits/tests/__init__.py`` ``lib/matplotlib/tests/__init__.py``... that makes no sense.

**Comment by WeatherGod** [comment]
we don't have it in the default tests because qt5 backend isn't installed
by default. Also, I think it requires a graphics display, so it wouldn't
work in headless situations such as Travis.

We merged in the PR with respect to bundling six with matplotlib after a
lengthy discussion.

As for no differences between the two init files, the tests for
mpl_toolkits are separate from the main set of tests because toolkits are
optional. But we wanted them to work under the same framework. Sometimes,
code duplication is ok when you know it to be extremely limited number of
duplications.

**Comment by OceanWolf** [comment]
As far as I can see, the ``qt5`` tests look just like the ``qt4`` tests which we do include and pass fine...

With the ``__init__.py, `` I don't see why we need the code duplication, other ways exist, at the most basic we can just import the functions from one __init__ into another, right?

``lib/mpl_toolkits/tests/__init__.py``
```python
from matplotlib.tests import setup, assert_str_equal
```

That way we have a 1 line file instead of a 74 line file...
