### ISSUE TITLE
figure.add_subplot not creating new axes after change_geometry()

### ISSUE THREAD

**Issue by AeroEngy** [matplotlib/matplotlib#4786]
I have a PyQT4 GUI w/ embedded matplotlib that lets a user Add/Remove/Resize subplots and plot various items to them.  Occasionally after a certain sequence of add/removes a line would be plotted on the wrong subplot and the one specified would be missing.  A code sample is below  to recreate the issue.  Note in my real GUI I don't use pyplot and instead import Figure and FigureCanvasQTAgg but the behavior is the same as the sample below: 

``` python
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0, 10, 0.1)
y1 = 0.05 * x**2
y2 = -1 *y1
figure = plt.figure()
ax1 = figure.add_subplot(2,1,2,label='sub2')
ax1.plot(x, y1, 'g-')
plt.show()
# That was a mistake ... lets move it to sub1 and relabel.
ax1.change_geometry(2,1,1)
ax1.set_label('sub1')
#Now lets add subplot 2 for real this time and plot something else
ax2 = figure.add_subplot(2,1,2,label='sub2')
ax2.plot(x, y2, 'b-')
plt.draw()
```

![figure_1](https://cloud.githubusercontent.com/assets/13476671/8887209/82b6a314-3246-11e5-9f28-fe3ba29ff357.png)

No subplot 2 and both lines plotted on subplot 1.

This seems to be because the second call to add_subplot had the same args as the first call. So it returned the existing object.  However, I would have expected after the call to change_geometry and a re-label this wouldn't be the case.

Also this looks like the same issue as #429  that was closed along time ago just a different use case.  I added a comment there but went ahead and create this new issue since that one has been closed for so long.

**Comment by tacaswell** [comment]
huh, did not know that function existed and it has a rather ominous comment above it https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_subplots.py#L94

That function needs to go back up into the figure object and update the key the axes_stack that the figure holds.  See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/figure.py#L916

**Comment by AeroEngy** [comment]
Thanks!  What about the call to set_label or really anything that would modify one of the args/kwargs that make up the key?  Should it/they also update they key?  I am by no means an expert and just muddle through but it seems problematic since there is a wide combination of things that could be in the key depending on how add_subplot was called.

However, the label is specifically [called out in the documentation for add_axes](http://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.add_axes) as being exposed for tracking the key so maybe it at least should also update the key it if possible.  

Personally the behavior of tracking the key by args/kwargs and returning the axes if present seems unnecessary. To me `add_subplot` or `add_axes` should do exactly that always add an axes regardless.  The was mentioned by efiring in a comment on the original Issue (4 years ago)

**Comment by WeatherGod** [comment]
This is something we can fully blame Matlab for. In matlab, you dont work
from axes objects, so the subplot function was treated as the "getter" that
would create if needed.

The good news is that we have moved on from those functions and recommend
using things like add_subplots(), which doesn't expose that interface.

**Comment by AeroEngy** [comment]
I'm a little confused by the last part of your comment.  My example uses the add_subplots() metho.  This issue is present in that method because it is returning an existing object instead of just adding one.

**Comment by WeatherGod** [comment]
Hmmm, indeed. I missed that detail. It is probably an inadvertent result of
implementing add_subplots() upon the same framework that add_subplot() is
built on. So, an important question is if that is something that users rely
on, or is it ok for us to fix this so that it never returns an existing
object?

**Comment by AeroEngy** [comment]
Ummm.. Hold on I think I confused myself and you.  My example uses add_subplot()   no "s".   I am not aware of an add_subplots()  with an "s".   Do you mean pyplot.subplots()...  No "add_"

**Comment by WeatherGod** [comment]
I mean Axes.add_subplots() (and by extension pyplot.subplots()). They are
newer, added a few years ago, and are the recommended way of creating a
grid of subplots now. The singular form is the older, Matlab-ish way of
creating a subplot at a time.

**Comment by WeatherGod** [comment]
gah... I keep doing this to myself... of course, not Axes.add_subplots()...
that would be silly...

**Comment by AeroEngy** [comment]
Yeah that confused me furthe.  I can't really use subplots in my uses case since this part of a Gui that let's users add additional subplots 1 at a time.  Example they have 2 current subplots with various lines on each.  Then they want to plot something else on a third subplot..  Which doesn't exist yet.  So I add one more with add_subplot then change_geometry on the existing 2.

**Comment by themightyoarfish** [comment]
Is there any hope of having this fixed soonish?

**Comment by jklymak** [comment]
I think this would require someone who needs this functionality to look into doing this properly.  I think the core devs are relatively unanimous that the plt.subplot/fig.add_subplot interface is not preferred so making it even more complicated by making this work would be low priority 

I think you would have more success just figuring how to do this properly with the basic axes and GridSpec objects. It shouldn’t be too convoluted.  I think you just modify the axes subplotspec.

**Comment by fredrik-1** [comment]
You can avoid the problem in the example above with using 
`ax2 = figure.add_subplot(2,1,2,label='sub3')`
instead of 
`ax2 = figure.add_subplot(2,1,2,label='sub2')`

**Comment by anntzer** [comment]
change_geometry is now spelled `ax1.set_subplotspec(figure.add_gridspec(2, 1)[0])` (well it's better to create the gridspec outside, too), but other than that this issue is now fixed, AFAICT (and change_geometry has been removed).
