### ISSUE TITLE
MEP 13 and Traitlets

### ISSUE THREAD

**Issue by Mrngilles** [matplotlib/matplotlib#4789]
I sent a mail on the matplotlib-devel ML but it seems it is down... So I am copying my email here to have more of a discussion.

I understand you've been discussing integrating traitlets in mpl. It seems to me you have only discussed this for the `artists`.
With this in mind, and assuming it is done (which I know is still under discussion), would MEP 13 proposing to add getters and setters through the `property` method still be relevant ? It seems it would, but I don't have a good knowledge of either traitlets or enthought.traits...

Also, is there any other place where it could be possible to follow your discussions on the traitlets other than PR 4694? I'd like to have a better idea on what is involved in this and try to follow along.

Thanks

**Comment by petehuang** [comment]
Current PR is at #4762 for visitor reference. Have you been able to retry sending this to the mailing list?
