### ISSUE TITLE
Probability axes scales

### ISSUE THREAD

**Issue by phobson** [matplotlib/matplotlib#4799]
I've got a fairly general and battle-tested probability scale implemented here:
https://github.com/Geosyntec/wqio/blob/master/wqio/utils/probscale.py

I think it'd be a generally useful addition to the matplotlib *ecosystem*. I say *ecosystem* because it depends on scipy and matplotlib has a policy of not depending on scipy.

I see a few possible paths:
  1. build an embarrassingly small mpltoolkit, publicize it in the official MPL docs
  2. include it in matplotlib, wrap `try/expcept ImportError` around it, and declare scipy an "optional dependency" from now on (unlikely)
  3. see if seaborn/ggplot want it.

### Option 1
Pro: we release it whenever, libraries supporting old versions of MPL can use it right away
Con: it seems like a lot of overhead for something so small.

### Option 2
Pro: Once it's in, it's in and people have it
Con: I don't want to open the floodgates of optional dependencies.

### Option 3
Pro: those libraries are pretty agile and will be able to adapt/tweak to suit their needs
Con: I think probability scales are generally useful and shouldn't have to be re-implemented in every mpl-based module that might want them (especially in libs like stats-models).

Any thoughts?

Attn: @tacaswell @mwaskom @glamp

![statplot](https://cloud.githubusercontent.com/assets/1163939/8916915/8d6422cc-3463-11e5-8046-45e1a7a24c76.png)

**Comment by mwaskom** [comment]
The scipy dependency is just needed to get the normal ppf and cdf right? (I haven't looked closely at the code). You could probably just write those out in numpy and then scipy wouldn't be needed.

**Comment by phobson** [comment]
@mwaskom  The current implementation supports any fully spec'd  continuous distribution in `scipy.stats.distributions`. Reimplementing `cdf` and `ppf` means we'd need to limit that to just `norm` (or whatever else could be considered low-hanging fruit).

**Comment by mwaskom** [comment]
Maybe I'm missing something, but to use a non-default distribution, the *user* needs to have scipy installed (or really any library that offers RV objects with a certain interface), but matplotlib itself won't depend on scipy. Right?

**Comment by phobson** [comment]
That's a fair point -- we'd only need to reimplement the default case, if the use wants to pass an API-compliant custom distribution, from scipy or not, that's on them.

**Comment by has2k1** [comment]
@phobson, to have a python ggplot that is on par with its R counterpart I got into a rewrite I did probability transformations in similar fashion, [see] (https://github.com/has2k1/ggplot/blob/rewrite/ggplot/scales/utils.py#L590-L603).

**Comment by phobson** [comment]
@tacaswell I've got a sans-scipy probability scale working. Interested or should I just close this?

**Comment by tacaswell** [comment]
Interested, but maybe it should live in it's own repo in the matplotlib organization.  That would (annoyingly) mean you could use scipy.

**Comment by phobson** [comment]
OK -- I'll throw it up in its own repo under my name for now. If Matplotlib The Organization :tm: what's to own it, y'all can have it. 

Closing this for now.

**Comment by phobson** [comment]
https://github.com/phobson/mpl-probscale
