### ISSUE TITLE
Set default axis limits in 2D-plots to the limits of the data

### ISSUE THREAD

**Issue by TheExcalabur** [matplotlib/matplotlib#4815]
By default, pcolormesh and friends seem to not use tight boxes, leading to blank bars along the side or top of the figure depending on the range of values plotted.  I see no positive results from this behaviour.

**Comment by shoyer** [comment]
This is also an issue for contour plots.

**Comment by Tillsten** [comment]
+1, always calling autoscale after contour & co should not be necessery.

**Comment by mdboom** [comment]
Related to #4891

**Comment by tacaswell** [comment]
This is going to cause interesting interactions with using `margins` by default.

**Comment by efiring** [comment]
It sounds like this is a proposal for the default to execute what would need to be a new "tight" mode in Axes.autoscale_view.  Presently, `None` triggers tight scaling if the artists include `images` but do not include `lines` or `patches`.  If I understand correctly, the suggested alternative mode would trigger tight scaling if the artists include or result from any image-like elements (e.g. collections such as quadmesh, or LineCollection or PolyCollection from contour or contourf).  This seems reasonable.  In its simplest form it would not be difficult to implement: the judgment would be based exclusively on the artists without regard for how they were generated.  An alternative would be to add an attribute to artists that would specify whether they should be treated as image-like for autoscaling purposes.

**Comment by tacaswell** [comment]
This is handled in #5583
