### ISSUE TITLE
fill_between in matplotlib does not handle “rasterized=True” option correctly

### ISSUE THREAD

**Issue by katastrofa999** [matplotlib/matplotlib#4837]
The following script

    import matplotlib as mp
    import matplotlib.pyplot as plt

    ALPHA=0.2
    RASTERIZED=True

    x = [0, 1, 2, 3]
    y1 = [0, 0.1, 0.2, 0.3]
    y2 = [0.01, 0.11, 0.21, 0.32]
    fig, ax = plt.subplots(figsize=(4,4))
    ax.fill_between(x, y1, y2, alpha=ALPHA, color='red', lw=0, rasterized=RASTERIZED)
    ax.fill_between(x, list(reversed(y1)), list(reversed(y2)), alpha=ALPHA, color='blue', lw=0,     rasterized=RASTERIZED)
    fig.savefig('plot.pdf')
    fig.savefig('plot.eps')
    fig.savefig('plot.ps')

Generates plots with empty fills, instead of rasterized transparencies.

**Comment by tacaswell** [comment]
eps/ps do not support alpha at all.  What you are seeing is happening is that the alpha channel is getting dropped so you are seeing just the blue line, with no alpha.

You can get something that looks correct here by doing 

```python
import matplotlib as mp
import matplotlib.pyplot as plt

ALPHA=0.2
RASTERIZED=True

x = [0, 1, 2, 3]
y1 = [0, 0.1, 0.2, 0.3]
y2 = [0.01, 0.11, 0.21, 0.32]
fig, ax = plt.subplots(figsize=(4,4))

# note the zorder changes
ax.fill_between(x, y1, y2, alpha=ALPHA, color='red', lw=0, zorder=-5)
ax.fill_between(x, list(reversed(y1)), list(reversed(y2)), alpha=ALPHA, color='blue', lw=0,  zorder=-4)

ax.set_rasterization_zorder(-1)  # this is the important line

fig.savefig('plot.pdf')
fig.savefig('plot.eps')
fig.savefig('plot.ps')
fig.savefig('plot.png')

```

which will cause all of the artists with a zorder less than -1 to be composited by agg which does know how to deal with alpha. 
For me the pdf and png output look correct.

**Comment by katastrofa999** [comment]
Doesn't work for me, I'm afraid. Matplotlib version 1.4.2-3.1

**Comment by tacaswell** [comment]
Can you post the code and incorrect png output?

**Comment by tacaswell** [comment]
Also, try updating to 1.4.3.

**Comment by katastrofa999** [comment]
The code:
```python
import matplotlib as mp
import matplotlib.pyplot as plt

ALPHA=0.2
RASTERIZED=True

x = [0, 1, 2, 3]
y1 = [0, 0.1, 0.2, 0.3]
y2 = [0.01, 0.11, 0.21, 0.32]
fig, ax = plt.subplots(figsize=(4,4))
ax.fill_between(x, y1, y2, alpha=ALPHA, color='red', lw=0, zorder=-5)
ax.fill_between(x, list(reversed(y1)), list(reversed(y2)), alpha=ALPHA, color='blue', lw=0, zorder=-4)
ax.set_rasterization_zorder(-1)
#ax.set_title('Plot')
#ax.set_ylabel('Units')
fig.savefig('plot.pdf')
fig.savefig('plot.png')
```
PNG output:
![plot](https://cloud.githubusercontent.com/assets/3437759/9569990/403697ba-4f74-11e5-8e45-5087982ae53f.png)

PDF output looks the same.

The Linux distribution I use does not have 1.4.3, but I'll try to upgrade it manually.

**Comment by tacaswell** [comment]
This is fixed in 1.4.3.  I just ran your code in a conda environment with both 1.4.2 and 1.4.3:

## 1.4.3

![plot](https://cloud.githubusercontent.com/assets/199813/9570037/80d9ce8c-4f4b-11e5-8cc0-b7a962d91bbc.png)



## 1.4.2

![plot](https://cloud.githubusercontent.com/assets/199813/9570033/6d305d2e-4f4b-11e5-99b7-fcb2aa90dc0e.png)


You can also test at https://try.jupyter.org/

Closing as already fixed.

**Comment by katastrofa999** [comment]
OK, thanks.

**Comment by tacaswell** [comment]
Thank you for the bug report, sorry we can't do any more for you.

What linux distro do you use?  I can make sure they are on the list of people I notify about future releases.

**Comment by katastrofa999** [comment]
kubuntu 15.04
