### ISSUE TITLE
float repr in axes parameter editing window (aka the green tick button)

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4839]
After setting e.g. xlim to [.1, .9], the axes parameter editing window shows the xlims as 0.1000<...>1 and 0.9000<...>2 respectively, due to "classic" floating point repr issues.  While this shoudl technically be fixed by numpy (numpy/numpy#6136) I wouldn't hold my breath for it and I'd suggest casting these items to Python floats, which use the shortest repr that yields the same value when eval'd.

**Comment by QuLogic** [comment]
I believe this was fixed by #5555.
