### ISSUE TITLE
Setting colormaps for subsequent plots

### ISSUE THREAD

**Issue by duelli** [matplotlib/matplotlib#484]
When looking for documentation on how to set colormaps, I usually find the following ways to set a colormap

```
matplotlib.pyplot.copper()
matplotlib.pyplot.set_cmap(matplotlib.colormap.copper)
matplotlib.cm.copper()
matplotlib.cm.set_cmap(matplotlib.colormap.copper)
```

The latter of these ways is documented in the API but I am told

```
matplotlib.cm.set_cmap(cm.copper)
AttributeError: 'module' object has no attribute 'set_cmap'
```

Whatsoever, a colormap can be shown with

```
matplotlib.cm.get_cmap().name
```

However, I only could find successful examples on changing the colormap for `imshow`, but I am interested in changing the colormap for subsequent plots like this

```
# FIXME Set colormap

import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(num=1)
fig.clf()
ax = plt.subplot(111)
ax.hold(True)

N=10
for i in np.arange(N):
    ax.plot(np.arange(10), (i+1)*np.arange(10), label=repr(i))
```

This defaults to `hsv` (right?) but how can it be changed?

**Comment by alexbonnin** [comment]
Hi Michael, I am a student from Universitat Politècnica de Catalunya (Network Engineering) and I have some questions about ALEVIN that would help me in my final project. If you can see this pleas contact me at: alex.bonnin5@gmail.com
Thank you!!
