### ISSUE TITLE
set numpoints to 1

### ISSUE THREAD

**Issue by dsm054** [matplotlib/matplotlib#4854]
(File under "default changes".  For all I know this is already on the list of things to change, but if so I couldn't find it under either "numpoints" or "scatterpoints".)

My most popular answer on SO (see ["matplotlib legend markers only once"](http://stackoverflow.com/questions/6146778/matplotlib-legend-markers-only-once)) explains how to avoid multiple points showing up in the legend.

This is far from scientific, but for what it's worth the question has 107 upvotes, my answer has 117 upvotes, and neither has a single downvote.

My experience is that those who don't like the multiple-marker convention *really* don't like it, and those who do don't seem particularly worked up about it.

**Comment by joferkington** [comment]
+1 from me.  

I think an rcParam of `legend.numpoints = 1` is a much better default than the current default of 2.  Worth including in the color overhaul, i.m.o.

**Comment by gauteh** [comment]
:+1:

**Comment by HDembinski** [comment]
+1 from me, too :)

**Comment by Tillsten** [comment]
+1

**Comment by janpipek** [comment]
+1

**Comment by efiring** [comment]
If one of you will generate a suitable PR for this, it will be merged.  I will be very surprised if there is any opposition.
