### ISSUE TITLE
Limit what `style.use` can affect?

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#4855]
This might be a controversial proposal, so I thought I'd get some discussion first.

In `astropy`, there is a "house style", which, surprising to me, included `interactive: True`.  I wouldn't have expected a style to affect the interactive setting (which I see more as a user preference than affecting the style of the output).  I'm going to advocate that `astropy` removes that but relatedly...

Would it make sense to filter out rcParams that don't really relate to style in `style.use`?  I realize this somewhat breaks DWIM, but it does prevent a certain kind of shooting oneself in the foot...

**Comment by tacaswell** [comment]
:+1: from me.

**Comment by efiring** [comment]
Offhand, such a limitation sounds to me like a good idea.

**Comment by WeatherGod** [comment]
others might be the backend, keymaps, etc. As I was making the "classic"
style, I was conflicted in a few spots about what to explicitly set in the
style. I may be a bit overzealous when I made it and it could be trimmed
back before merging (once we figure out the whole font issue...).

**Comment by dopplershift** [comment]
:+1: Less foot shooting is a good thing.
