### ISSUE TITLE
Call `tight_layout()` by default

### ISSUE THREAD

**Issue by lstagner** [matplotlib/matplotlib#4859]
I almost always call ```tight_layout()``` on my plots so it might make sense to just call it automatically by default.

**Comment by tacaswell** [comment]
There should be an rcparam for this, but I don't think it be true by default.  As currently implemented tight layout requires rendering the figure twice and does not work correctly with all artists.

**Comment by WeatherGod** [comment]
There is also the question of when to call it automatically. If we were to
attach it to the show(), I don't think it would update whenever someone
changes the size of the figure window. We could attach it to the draw(),
but we would have to be careful of infinite recursion. Plus, that might
cause unnecessary overhead. Perhaps this is another case of where the
"stale" design might be able to help us out (by identifying changes to text
artists and changes to axes layouts)?

**Comment by mdehoon** [comment]
@WeatherGod  Calling figure.set_tight_layout(True) will ensure that the layout remains tight even upon resizing or adding/removing artists from the figure.

**Comment by nilsbecker** [comment]
In my experience tight_layout() is very useful but unreliable. So adding this as a default would put pressure on fixing it...

**Comment by tacaswell** [comment]
Generating pressure on the developers by breaking users code is a bad idea.

**Comment by nilsbecker** [comment]
yes, so maybe then making it default now is not advisable?

**Comment by fmaussion** [comment]
Maybe it's obvious to everyone but it sounds like a bad idea to me. Even adding an rcparam is dangerous, because it will silently ignore `ax.set_position()` and such. 

I use `tight_layout( )` very often and didn't find it buggy, but I think it's ok to call it explicitly.

**Comment by mdboom** [comment]
I think we'll need to improve `tight_layout` somewhat before it can be a reasonable default.
