### ISSUE TITLE
Plotting order matters for overlapping colors

### ISSUE THREAD

**Issue by domspad** [matplotlib/matplotlib#4862]
When plotting potentially overlapping data points of two different kinds, if both data points have their alpha set to 0.5, I would hope that the resulting color of their overlap is the same regardless of which point was plotted first. This demonstrates that is not the case -- instead the color deviates towards the most recently plotted one. This could be an artifact of color theory or something, I'm not sure, but I was wondering what people would have to say about this and possible work-arounds if a direct solution is not possible.

![plotting_colors](https://cloud.githubusercontent.com/assets/7263654/9064062/9b4f5d1c-3a7f-11e5-8848-fd48a1b34f32.png)

```
import matplotlib
import numpy as np
from matplotlib.patches import Circle
from matplotlib.collections import PatchCollection
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

patches = []
patches.append(Circle((0.2,0.8),0.1))
patches.append(Circle((0.3,0.8),0.1))
patches.append(Circle((0.6,0.2),0.1))
patches.append(Circle((0.7,0.2),0.1))
colors = [0,1,1,0]
p = PatchCollection(patches, cmap=matplotlib.cm.jet, alpha=0.5)
p.set_array(np.array(colors))
ax.add_collection(p)
ax.set_title('Plotting order matters for overlapping colors')
plt.colorbar(p)
plt.show()
```

**Comment by tacaswell** [comment]
If I understand correctly, there are actually two composite steps going on here.  First the bottom circle is blended with background and then the top circle is blended with the result of the first.  

I think the way that we do the blending is  `r = A (1 - alpha) + B alpha`  so applying this twice we get ` r = A (1 - alpha) **2 + B alpha (1-alpha) + C alpha` which will be weighted towards the last value as you observe.

**Comment by ymer** [comment]
That makes sense. But I think it would be preferable if it took the true average of the colors in such cases.

**Comment by mdboom** [comment]
It will be tricky to make this work -- at present we rely on standard alpha blending as supported by PDF, SVG, Agg, Cairo etc.  To deviate from that would require rebuilding a pretty substantial wheel.

However, as a workaround, if you plotted on a fully white background, rather than grey and limited yourself to two overlapping shapes, you should theoretically get what you're after.

**Comment by Saynah** [comment]
Hmm, @mdboom 
This doesn't seem to be the case.
![image](https://cloud.githubusercontent.com/assets/637288/23078301/00ea9392-f4fd-11e6-9cf3-ed57c3819f67.png)

Any other potential workarounds?

**Comment by WeatherGod** [comment]
gosh, I hope this isn't the whole pre-multiplied alpha thing all over
again...

**Comment by Saynah** [comment]
Here's a hack!:
Plot object 1 then 2....then 2 then 1 (with half the alpha)
![image](https://cloud.githubusercontent.com/assets/637288/23079074/20da4d84-f500-11e6-85d5-8e58d49777b6.png)

The OP's example, modified
```python
import matplotlib
import numpy as np
from matplotlib.patches import Circle
from matplotlib.collections import PatchCollection
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

patches = []
y = 0.4
patches.append(Circle((0.2,y),0.1))
patches.append(Circle((0.25,y),0.1))
# replot in reverse order
patches.append(Circle((0.25,y),0.1))
patches.append(Circle((0.2,y),0.1))

# compare to...
y = 0.2
patches.append(Circle((0.25,y),0.1))
patches.append(Circle((0.2,y),0.1))
# replot in reverse order
patches.append(Circle((0.2,y),0.1))
patches.append(Circle((0.25,y),0.1))

colors = [0,1,1,0] * 2

alpha = 0.25 # half the alpha 
p = PatchCollection(patches, cmap=matplotlib.cm.jet, alpha=alpha)
p.set_array(np.array(colors))
ax.add_collection(p)
ax.set_title('Plotting order matters for overlapping colors')
ax.set_xlim([0, 0.6])
ax.set_ylim([0, 0.6])
plt.colorbar(p)
plt.show()
```

**Comment by anntzer** [comment]
This is the standard behavior of alpha compositing.  See e.g. https://cairographics.org/operators/ (compare CAIRO_OPERATOR_OVER and CAIRO_OPERATOR_DEST_OVER).

**Comment by WingTillDie** [comment]
@Saynah The order of the color applied is the same, so the color are the same(#7a507d)
The code with different color apply order should be:
```python
import matplotlib
import numpy as np
from matplotlib.patches import Circle
from matplotlib.collections import PatchCollection
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

patches = []
y = 0.4
patches.append(Circle((0.2,y),0.1))
patches.append(Circle((0.25,y),0.1))
# replot in reverse order
patches.append(Circle((0.25,y),0.1))
patches.append(Circle((0.2,y),0.1))

# compare to...
y = 0.2
patches.append(Circle((0.2,y),0.1))
patches.append(Circle((0.25,y),0.1))
# replot in reverse order
patches.append(Circle((0.25,y),0.1))
patches.append(Circle((0.2,y),0.1))

colors = [0,1,1,0] + [1,0,0,1]

alpha = 0.25 # half the alpha 
p = PatchCollection(patches, cmap=matplotlib.cm.jet, alpha=alpha)
p.set_array(np.array(colors))
ax.add_collection(p)
ax.set_title('Plotting order matters for overlapping colors')
ax.set_xlim([0, 0.6])
ax.set_ylim([0, 0.6])
plt.colorbar(p)
plt.savefig('out.svg', format='svg')
plt.show()
```
![wrongorder](https://user-images.githubusercontent.com/11259109/44621398-5eb32080-a8d8-11e8-84ba-2f91f33efe86.png)
The color is #7a507d in upper circle, #7a507a in lower circle.

Replot in reverse order just reduce the difference, but does not eliminate it.

A example that is easier to see the effect:
```python
import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(0,1)
plt.plot(x, np.zeros_like(x), 'r', alpha=0.25, lw=198)
plt.plot(x, np.zeros_like(x), 'b', alpha=0.25, lw=198)
plt.plot(x, np.zeros_like(x), 'b', alpha=0.25, lw=198)
plt.plot(x, np.zeros_like(x), 'r', alpha=0.25, lw=198)

plt.plot(x, np.full_like(x, 0.02), 'b', alpha=0.25, lw=197)
plt.plot(x, np.full_like(x, 0.02), 'r', alpha=0.25, lw=197)
plt.plot(x, np.full_like(x, 0.02), 'r', alpha=0.25, lw=197)
plt.plot(x, np.full_like(x, 0.02), 'b', alpha=0.25, lw=197)
plt.show()
```
![closely](https://user-images.githubusercontent.com/11259109/44621427-ef89fc00-a8d8-11e8-87aa-29676080609f.png)
So the problem remains unsolved.

**Comment by tacaswell** [comment]
@WingTillDie That is probably because we are blending in to an int8 buffer (rather than a float buffer) which introduces truncation at each composite step (this has way worse issues when overlaying many very transparent objects).  The fix is to change the internal agg buffers to use float types rather than ints and cast to int at the very end.
