### ISSUE TITLE
Add additional minor labels in log axis with a span less than two decades

### ISSUE THREAD

**Issue by zblz** [matplotlib/matplotlib#4867]
For plots with log axis that have limits of the order or less than two decades, only one label is shown:
![log_labels](https://cloud.githubusercontent.com/assets/576258/9082131/c84ce962-3b59-11e5-80c3-f12b85f16ff5.png)

Which does not give a very good idea of the values of the x axis. Adding labels to the minor ticks results in a mess, including non-helpful labels such as `10^{4.30}`:

```
ax.xaxis.set_minor_formatter(ticker.LogFormatterMathtext(labelOnlyBase=False))
```

![log_labels_minor_logformattermathtext](https://cloud.githubusercontent.com/assets/576258/9082178/1e9f177c-3b5a-11e5-815a-a73d8bcdc33f.png)

And limiting them at `[2,5]*base**i` results in losing all other minor ticks:

```
ax.xaxis.set_minor_locator(ticker.LogLocator(subs=[2,5]))
```

![log_labels_minor_at_125_logformattermathtext](https://cloud.githubusercontent.com/assets/576258/9082194/471819ec-3b5a-11e5-8a89-22c23e2f2476.png)

The decimals in the exponent can be resolved using LogFormatter, but it is not a nice representation for axis and requires changing the major formatter to match:

```
ax.xaxis.set_minor_formatter(ticker.LogFormatter(labelOnlyBase=False))
ax.xaxis.set_major_formatter(ticker.LogFormatter())
```

![log_labels_minor_at_125_logformatter](https://cloud.githubusercontent.com/assets/576258/9082286/df6bfcfe-3b5a-11e5-892f-6958e5399f7e.png)

Finally, the only way to get them in a consistent manner with the major tick labels, while preserving all minor ticks, is to set them manually, which is far from ideal:

```
ax.xaxis.set_ticklabels([r'$2\times10^4$','','',r'$5\times10^4$','','','','', 
        r'$2\times 10^4$','','',r'$5\times10^4$','','','','',
        r'$2\times 10^5$','','',r'$5\times10^5$','','','','',
        ],minor=True)
```

![log_labels_minor_at_125_manual_labels](https://cloud.githubusercontent.com/assets/576258/9082304/055831b2-3b5b-11e5-94fe-83cc4a2c92ff.png)

I think that there should be a `LogFormatterMathtext` with a `subs` options like the locator, and an option to factors instead of decimal exponents. I will take a look at the `LogFormatterMathtext` and try to modify it in the following days. If it looks good, I would propose to switch to it automatically for axis spanning less than two decades.

Note that this issue has been reported in [a stackoverflow question](http://stackoverflow.com/questions/17165435/matplotlib-show-labels-for-minor-ticks-also) where a custom formatter is proposed as an answer.
This is somewhat related to the issue #4730 because the lack of labels is particularly noticeable when the axis is around 0.1,1,10, where it would make a lot of sense to have labels at [0.1,0.2,2,5,20,50].

**Comment by tacaswell** [comment]
I am somewhat ambivalent on this as I am not convinced of the utility of log scaled axis with less than 2 decades of data.

**Comment by zblz** [comment]
In my field (high energy astrophysics) they are extremely common: the
gamma-ray photon spectra of an astrophysical source will almost always
follow a powerlaw behaviour, and the energy detection band for a single
instrument is rarely larger than two decades (often less than one), so the
plotted spectra from a single instrument are always like this. It might be
a corner case, but I brought it up as it comes up very often in my use of
matplotlib.

This would be useful for the [gammapy](github.com/gammapy/gammapy) and
[naima](github.com/zblz/naima) packages, which deal with gamma-ray spectra
and use matplotlib for plotting.

2015-08-05 14:46 GMT+01:00 Thomas A Caswell <notifications@github.com>:

**Comment by tacaswell** [comment]
Fair enough.  I come from a soft-matter physics background where we are looking for power laws in noisy data, with less than 2 decades just about any powerlaw can be made to fit, hence my skepticism.

**Comment by efiring** [comment]
Another case where it would be nice to have labels for a short span of
a log scale is when one zooms in on a feature in a spectrum.

**Comment by QuLogic** [comment]
Is this fixed by the above PR?

**Comment by efiring** [comment]
It was, but that was reverted by #7000, and then a modified version was restored by #7419.
