### ISSUE TITLE
Pyplot ability to read 16 bit image (tiff) 

### ISSUE THREAD

**Issue by paulvija** [matplotlib/matplotlib#4888]
Hi there,

I have tried plotting a 16bit RGB tiff image and all what I got was a pixelated output however works fine with 8bit image.
If there is an alternative or workaround PLEASE forward me to it?
Code: 
plt.imshow(tasman.transpose((1, 2, 0)) # for correct order array order, see image attached for error plot.

PS: If raw image is required please let me know.
Thanks,
Vijay Paul

![16bit_pyplot_image](https://cloud.githubusercontent.com/assets/12703555/9149610/e32df506-3e05-11e5-9854-7688cd74dd06.png)

**Comment by tacaswell** [comment]
We delegate tiff reading to `PIL` / `pillow` so if the reading from disk is the problem, try `tifffile` or `libtiff`.

Internally, we only have 8bit RGBA buffers so as a quick work around you can down-scaling to 8bit (`skimage` has tools for changing the gamut).

**Comment by paulvija** [comment]
Thanks for the pointers tacaswell.
