### ISSUE TITLE
zeros in log space

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4893]
`plt.loglog(np.r_[.05, np.random.rand(100) * .9 + .1])` (i.e., all data points falling between .1 and 1, except (0, 0.05)) results in a y axis set from 0.01 to 1, i.e. the code that computes ylims "takes into account" the hidden (0, 0.05) point.

Perhaps that's not "wrong" per se, but the resulting graph definitely looks weird.

**Comment by jklymak** [comment]
I'll be so bold as to close this.  I suppose if the scale refuses to plot a data point, its corresponding y-value could be ignored, but we don't really have a way for x-values and y-values to co-ordinate axis limit calcs.

**Comment by anntzer** [comment]
> we don't really have a way for x-values and y-values to co-ordinate axis limit calcs.

@jklymak That's not really true?  For example, if you explicitly convert to log space and do a linear plot
```python
plt.plot(np.log(np.arange(101)), np.log(np.r_[.05, np.random.rand(100) * .9 + .1]))
```
then the first point (`(log(0), log(0.05))`) is correctly ignored.

**Comment by jklymak** [comment]
OK, so I guess I don't understand the relim logic then....

**Comment by tacaswell** [comment]
I think this is a variation on the "limit the y-axis based on the current x-limits" issue.

**Comment by jklymak** [comment]
Sort of, but as @anntzer points out, we already do this for linear scales, so the autolim behaviour of the log scales must need a tweak.

**Comment by tacaswell** [comment]
But in the linear case the user has passed us "invalid" data so we can drop it without any knowledge of what the state of the Axes.

**Comment by jklymak** [comment]
Ah - yes that is definitely the difference - we drop x and y before the relim.

**Comment by anntzer** [comment]
Let's close this for now.  I agree it's not entirely clear the current behavior is wrong.
