### ISSUE TITLE
[mpl_toolkits.axes_grid1] Can't remove host axes' twin axes

### ISSUE THREAD

**Issue by productivememberofsociety666** [matplotlib/matplotlib#4896]
Axes created via ``mpl_toolkits.axes_grid1.host_subplot(...).twin()`` (or ``twinx()``, ``twiny()``) can not be removed via their ``remove()`` method. Non-``mpl_toolkit`` twin axes can be removed; this is specific to ``mpl_toolkit``.

-----
**Example:**
````python
from mpl_toolkits.axes_grid1 import host_subplot
h = host_subplot(111)
t = h.twin()
t.remove()
````
raises ``NotImplementedError: cannot remove artist``.

-----

Is there a way around this that I'm missing? I'm using axes_grid1's ``twin()`` to interactively create axes with user-defined transforms and want to be able to destroy them as well, of course. Alternatively, it would suffice for me to be able to change the transform (given initially via ``twin(aux_transform)``), but even that seems not possible.

-----
**matplotlib version:** 1.5.dev1, at commit ``2c95107db6c09d42336a8ce901ea57ccae34f3ca``
**Python version**:  3.4.2

**Comment by tacaswell** [comment]
The remove method is a place-holder that needs to be installed at instantiation time by assigning a function to `a._remove_method` (have a look at the `add_*` methods on `Axes`).  axes_grid just needs to do the same thing.

**Comment by productivememberofsociety666** [comment]
Thanks for merging the PR, issue should be fixed now!
