### ISSUE TITLE
TransformWrapper is not reliably pickleable

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#4908]
Based on errors in #4699, I've whittled down the problem to a small example:
```python
import pickle
import matplotlib.transforms as mtransforms

class TestTransform(object):
    def __init__(self):
        self.identity = mtransforms.IdentityTransform()
        self.wrapper = mtransforms.TransformWrapper(self.identity)

c = TestTransform()
pkl = pickle.dumps(c)
ret = pickle.loads(pkl)
```
If you run this test, it might work fine. But if you run it a few times:
```bash
(for i in `seq 100`; do python test_pickle.py &> /dev/null; echo -n "$? + "; done; echo "0") | bc
```
then you will find that about 50% of the time, it fails:
```python
Traceback (most recent call last):
  File "test_pickle.py", line 13, in <module>
    ret = pickle.loads(pkl)
  File ".../matplotlib/lib/matplotlib/transforms.py", line 1556, in __setstate__
    self.__init__(state['child'])
  File ".../matplotlib/lib/matplotlib/transforms.py", line 1539, in __init__
    self._set(child)
  File ".../matplotlib/lib/matplotlib/transforms.py", line 1567, in _set
    self.set_children(child)
  File ".../matplotlib/lib/matplotlib/transforms.py", line 170, in set_children
    child._parents[id(self)] = self
AttributeError: 'IdentityTransform' object has no attribute '_parents'
```

**Comment by QuLogic** [comment]
BTW, that 50% is the result with master f852c0ccb0991ef45b26609cb8ba0f102947d0dc.

In 1.4.3, this particular example seems fine. But if you change it slightly to:
```python
self.identity = mtransforms.IdentityTransform()
self.identity2 = mtransforms.IdentityTransform()
self.composite = self.identity + self.identity
self.wrapper = mtransforms.TransformWrapper(self.composite)
```
then it fails 100% of the time on 1.4.3 (and somewhere between 50 and 100% on master.)

**Comment by tacaswell** [comment]
Is that the commit you meant to link to?  I don't see anyway those two are related

**Comment by QuLogic** [comment]
There's nothing specific about that commit; it's just the latest master commit I tested.

**Comment by tacaswell** [comment]
Oh, sorry I misread it and thought you were saying the change introduced in that commit broke it.

Are you using python 2 or 3?  This might be another dicts iterate in random order bug.

**Comment by QuLogic** [comment]
That might be part of it; the original example in the opening fails intermittently on Python 3, but not Python 2. The second example in the second comment fails intermittently on Python 3, but _always_ on Python 2.

**Comment by QuLogic** [comment]
Updated second comment since I accidentally attributed some difference to 1.4.3 vs. master when it's really Python 2 vs. Python 3.

**Comment by tacaswell** [comment]
Ah, that we can work with!

**Comment by tacaswell** [comment]
The thing that confuses me here is I thought that unpickling side-stepped `__init__`
