### ISSUE TITLE
UserWarning for pandas dataframe plot with errors

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#4917]
Only when I add the `yerr` option to this pandas dataframe plot I'm getting this matplotlib `UserWarning`:

``` python
df.FUV_CHIP_TEMP_C.plot(yerr=std)

WARNING:py.warnings:/Users/klay6683/miniconda3/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-macosx-10.5-x86_64.egg/matplotlib/collections.py:356: UserWarning: Collection picker None could not be converted to float
  % self._picker)
```

at the exact moment the mouse pointer hovers over the plotting area.
`std` is a dataframe with the exact same shape and columns as `df` and the plotting seem to makes sense. Thought I let you know of this irritating warning though.

This does not happen when I do not use the `yerr` option.

MPL: ''1.5.dev1'' (GH master from today: 3f758abfa1a)
Platform: OSX 10.10.4
Backend: `qt`

Edit: Let me know if this should go to pandas, then I move it over there.

**Comment by tacaswell** [comment]
It is coming out of a `Collection` object (which is how error bars are implemented).   The reason you are seeing this on master on mouse over is the hitlist computation a part of the hover feature (plot `imshow` to see the reason for this)

This should be ameliorated by #4813 which restricts the things that it tries to hit greatly.

**Comment by jklymak** [comment]
I'll close for lack of a reproducible example.  Feel free to ask for a re-open....
