### ISSUE TITLE
Notebook backend zoom rect VEEERY slow in 1.5dev

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#4918]
See this video that is NOT slowed down, it's in realtime:

https://dl.dropboxusercontent.com/u/139035/notebook_backend_slooow_zoom_rect.mov

I compared it with 1.4.latest and that does not show this at all (but it showed other problems with being picky where I have to drop the zoom rect to be registered, which seems improved in 1.5dev).

System: OS X 10.10.4
Browser: Safari
IPython notebook: 3.2.1

**Comment by michaelaye** [comment]
I confirmed that this is behaving the same in Chrome.

**Comment by tacaswell** [comment]
Can you check with https://github.com/matplotlib/matplotlib/pull/4878 ?

**Comment by michaelaye** [comment]
yes, much much better! No apparent delay. But another potential regression: the icon for zoom rect does not change it's shade after selecting it, that was working at some point, wasn't it?

**Comment by mdehoon** [comment]
--------------------------------------------
On Fri, 8/14/15, K.-Michael Aye <notifications@github.com> wrote:

 Subject: Re: [matplotlib] Notebook backend zoom rect VEEERY slow in 1.5dev (#4918)
 To: "matplotlib/matplotlib" <matplotlib@noreply.github.com>
 Date: Friday, August 14, 2015, 9:47 AM
 
 yes, much much better! No
 apparent delay. But another potential regression: the icon
 for zoom rect does not change it's shade after selecting
 it, that was working at some point, wasn't it?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by jenshnielsen** [comment]
Fixed by #4878
