### ISSUE TITLE
Memory leak in NavigationToolbar2.mouse_over

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4936]
As reported by @WeatherGod  in #4738 and #4878 there may be a memory leak somewhere in the mouse hover code in `NavigationToolbar2.mouse_over` 

Not clear if #4878 fixed it but it seems unlikely

**Comment by tacaswell** [comment]
My (hopeful) guess as to what is going on there is that @WeatherGod was using data from netcdf4 object and the random access of pulling out a single pixel is causing it to cache many chunks of the image.

@WeatherGod Can you make a reproducible example?

**Comment by tacaswell** [comment]
Labeling this as not a blocker for an RC because we don't have a reproducible example.

**Comment by anntzer** [comment]
Closing for lack of reproducible example and lack of activity and possibly being due to netcdf4 caching which is unrelated to matplotlib.
