### ISSUE TITLE
NBAgg figure management issues

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4940]
Remaining known issues after merging #4456 

- [ ] make sure figures get closed on kernel restart (also does not happen in 1.4.3)
- [ ] still get a 'no such comm' error from closing figure programtically from python side
- [ ] closing an animated figure triggers 'no such comm' error

**Comment by jenshnielsen** [comment]
I tagged this as proposed next point release since:

I don't think these issues are critical and they are as far as I know also present in 1.4.3 but if possible they would be nice to fix in 1.5.0

**Comment by tritemio** [comment]
For the record issue #4457 may also be related (@jenshnielsen probably it is your second point).

**Comment by jenshnielsen** [comment]
Have you checked with the master branch after the merge of #4456? I cannot reproduce any of those 2 issues anymore. 

The last change that went into #4456 after your initial report makes sure that the figure is closed when removed from the DOM (I.e. not visible in the notebook) That takes care of issue one because there is no longer a hidden figure to plot into.

I tried opening several figures and closing them again and I see no sign of a memory leak. As expected the memory consumption goes up with more figures. It may not be immediately released when the figures are closed however explicitly doing a garbage collect seems to drop the memory consumption to the same level:

```
import gc 
gc.collect()
```
