### ISSUE TITLE
Stackplot takes a transposed Y matrix

### ISSUE THREAD

**Issue by naught101** [matplotlib/matplotlib#4952]
`pylab.plot()` can take `y` as a matrix. When it does, it treats columns as data series. This makes it work nicely with, for example, pandas dataframes.

`pylab.stackplot()` takes y as a transposed matrix, where rows are data sereies, to data frames must be transposed. It would be better for consistency if it followed the plot format.

Also, `plot()` can take a y with no x, and x is generated as `range(y.shape[0])` - it'd be great if stackplot allowed this as well.

ref: https://github.com/matplotlib/matplotlib/pull/819

**Comment by jklymak** [comment]
I agree this is inconsistent.  However, 11 years later, this seems unlikely to change.  Whoever uses stackplot is probably used to its quirks and it seems impossible to change the sense of the matrix order at this late date.
