### ISSUE TITLE
Inconsistent handling of whitespace with LaTeX

### ISSUE THREAD

**Issue by lgeiger** [matplotlib/matplotlib#4954]
Hi matplotlib developers,

I noticed some inconstancies regarding text rendering with `usetex=True`.
I placed the following text with `plt.text()` in my plot.

```
begin{eqnarray*}
\phi &=& 1.00 \pm 0.10 \\
a &=& 3.00 \pm 0.30 m \\
\frac{\chi^2}{ndof} &=& 1.13
\end{eqnarray*}
```

If the plot is saved as `.png` or `.pdf`, the whitespace around the equal signs is to big:
<img width="288" alt="bildschirmfoto 2015-08-18 um 20 34 40" src="https://cloud.githubusercontent.com/assets/13285808/9339720/e73f6312-45eb-11e5-951c-8c2c49813cc7.png">

If saved as `.svg` everything looks good:
<img width="235" alt="bildschirmfoto 2015-08-18 um 20 34 27" src="https://cloud.githubusercontent.com/assets/13285808/9339772/3106774c-45ec-11e5-9719-f052636401b3.png">

It would be great if whitespace would be consistent in all file formats.
A possibility to align text without LaTeX would also be greatly appreciated.

Thanks

**Comment by tacaswell** [comment]
There are two PRs open (#4873, #4872) that address this.  Do either of them fix this?

I think we might be delegating the equation rendering in the svg backend to your viewer.

**Comment by lgeiger** [comment]
For some reason the current matplotlib master doesn't work on my machine. So I'm not able to test the PRs at the moment.

You are right, the error lies in the svg backend or in the viewer. The pdf and png renderings are equal to what LaTeX does outside of matplotlib.
If the `align*` environment is used instead of `eqnarray*` with `\usepackage{amsmath}` in the preamble, everything is consistent across all file formats.

**Comment by tacaswell** [comment]
Oh, sorry I misread your post.  If you are using `usetex=True` what you are getting as a png of the latex output embedded in your plot so it is 'correct' (in that we use latex as the reference standard for our internal mathtex layout engine which is what those PRs are working on).
