### ISSUE TITLE
Switch default Qt library

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#4955]
Anaconda stopped supporting PySide, this leads to errors if using the default settings of matplotlib.

See: https://github.com/ContinuumIO/anaconda-issues/issues/411#issuecomment-132279959
and
http://continuum.io/blog/anaconda-2-released
Should therefore the matplotlib default be switched to PyQt instead of PySide?

**Comment by jenshnielsen** [comment]
Matplotlib should not default to PySide unless you have the environmental variable `QT_API` set to pyside 

The logic that determins this is in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py 

As you can see if nothing is set it first tries qt4 and then falls back to pyside if pyqt doesn't work

**Comment by tacaswell** [comment]
`'PyQt4'` is the default rcparam, it is different on your system that is due to who ever built/packaged your binaries changing it.
