### ISSUE TITLE
IndexError when moused over panned image

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#4957]
The new get_cursor_data() function has an indexing bug. If the user pans an image such that there is a gap between the edge of the image and the axes edges, and you mouse over that area, IndexError exceptions are thrown all over the place.

@joferkington 's mpl data cursor takes care of this correctly, IIRC, and I know I covered this in my book as well. Hopefully, someone will buy a copy and take a look and adapt it to get_cursor_data().

**Comment by WeatherGod** [comment]
Ok, now that I had a moment to take a peek, I will have a PR to fix this real quick.

**Comment by WeatherGod** [comment]
Question: do we want to report the value of the nearest pixel when off the image, or nothing at all?

**Comment by tacaswell** [comment]
@WeatherGod Not sure quite how I assigned you to this, but great!

**Comment by tacaswell** [comment]
Also, thanks for reporting and fixing this.  I had noticed this, but not gotten around to doing anything about it (because I am a jerk).
