### ISSUE TITLE
Bug on the pyplot.table colColours property (version 1.3.0)

### ISSUE THREAD

**Issue by danielcestari** [matplotlib/matplotlib#4960]
When trying to set colors for the label columns in the table method the first row got collapsed with the columns labels row.

Test code:
from matplotlib import pyplot as plt
data=[[1,2,3],[4,5,6],[7,8,9]]; labels=['A', 'B', 'C']; colors=['r', 'g', 'b']; 

"PROBLEM"
plt.table(cellText=data, rowLabels=labels, colLabels=labels, loc='center', colColours=colors); plt.axis('off'); plt.show()

"GOT CORRECT"
plt.table(cellText=data, rowLabels=labels, colLabels=labels, loc='center', rowColours=colors); plt.axis('off'); plt.show()

**Comment by WeatherGod** [comment]
I am not seeing any problems with this in the development branch. Without images, though, I can't be sure exactly what you mean by "first row got collapsed with the column labels row".

**Comment by jenshnielsen** [comment]
@WeatherGod beat me to it ;) but anyway

Can you test that with master or at least 1.4.3
1.3.0 is a very old release. 

I can't reproduce the problem on master as far as I understand the issue. Here is what I see


![download 1](https://cloud.githubusercontent.com/assets/548266/9357162/43e664d0-467d-11e5-8b22-7011179e3249.png)


![download](https://cloud.githubusercontent.com/assets/548266/9357164/485e7840-467d-11e5-8880-c7b2eb97c95e.png)

**Comment by WeatherGod** [comment]
@jenshnielsen , is it just me, or is the alignment of the text all screwy?

**Comment by jenshnielsen** [comment]
It could certainly be better, not sure if that is a new thing. I usually never use plt.table

**Comment by jenshnielsen** [comment]
Comparing [1.4.3](http://matplotlib.org/examples/pylab_examples/table_demo.html) to [master](http://matplotlib.org/devdocs/examples/pylab_examples/table_demo.html) I would say thats about the same. The Zorder have changed thou and it looks like the example is build with different fonts on 1.4.3 and Master(Travis).

**Comment by danielcestari** [comment]
The file matplotlib/lib/matplotlib/table.py of my version (1.3.0) is different from the current one.
I'm not able to update my matplotlib but replacing the lines of my version that correspond to the lines 602-609 solve the problem.

Just to clarify that was my problem before
![figure_1](https://cloud.githubusercontent.com/assets/1761574/9367675/4a728b22-4695-11e5-9aa4-f5de4d827e11.png)

Thanks for the fast reply and sorry for the inconvenient.
