### ISSUE TITLE
make color abbrivations configurable

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4974]
This is a follow on from #4754. 

Despite my initial reluctance, I have come around to this being a good idea. 

We launder (almost?) all of the color mapping through a `colorConverter` singleton is `colors` module, implementing this functionality is a simply a matter of providing a public function to change the `colors` attribute of this object.  

Related, I want to get the XKCD long-form color table included optionally used instead of the X11 maps (see https://github.com/matplotlib/matplotlib/issues/4383 for where they clash).  I propose doing that by shipping both dictionaries and providing `colorConverter` with a way to switch the precedence of the two dictionaries.

**Comment by WeatherGod** [comment]
Is this the "palette" option we were talking about?

On Thu, Aug 20, 2015 at 10:04 PM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
In part, yes.

**Comment by QuLogic** [comment]
We have `C0`, `C1`, etc. now; do we really need this?

**Comment by anntzer** [comment]
Agree with closing as well.
