### ISSUE TITLE
missing imshow() subplots when using tight_layout()

### ISSUE THREAD

**Issue by douglase** [matplotlib/matplotlib#4976]
Hello, I've found an unexpected behavior when I make grids of subplots with imshow and tight_layout the second to last plot is missing, for example:

```
import numpy as np
import matplotlib.pyplot as plt
plt.figure()
for i in range(16):
    ax= plt.subplot(4,4 ,i+1)
    im=ax.imshow(np.random.normal(size=100).reshape([10,10]))
    plt.tight_layout()
    plt.title(i)
plt.savefig("imshow_4x4.png")
```

generates:
![imshow_4x4](https://cloud.githubusercontent.com/assets/1025951/9416051/5da48e66-4811-11e5-967e-ae4407c1411f.png)
Whereas the same loop with pcolor works:

```
import numpy as np
import matplotlib.pyplot as plt
plt.figure()
for i in range(16):
    ax= plt.subplot(4,4 ,i+1)
    im=ax.pcolor(np.random.normal(size=100).reshape([10,10]))
    plt.tight_layout()
    plt.title(i)
plt.savefig("pcolor_4x4.png")
```

gives:
![pcolor_4x4](https://cloud.githubusercontent.com/assets/1025951/9416047/5bc7e3b8-4811-11e5-8eb8-04c139feae9a.png)

If I omit the tight_layout() call from the first example it works:
![imshow_nottight_4x4](https://cloud.githubusercontent.com/assets/1025951/9416171/fe565cf4-4811-11e5-91bb-119411a3caac.png)

I'm using matplotlib 1.4.3 and numpy  1.9.2  in Anaconda 2.2.0.

**Comment by tacaswell** [comment]
... what

I can reproduce this on current master.

**Comment by tacaswell** [comment]
`plt.tight_layout()` is removing an axes from the `fig.axes` list.

There is a simple work around here, just call `plt.tight_layout` once outside of the loop and it works correctly.

**Comment by douglase** [comment]
yes, the work around works, thanks. Calling tight_layout inside the loop is admittedly an inefficient approach but not one I expected to delete a figure...

**Comment by tacaswell** [comment]
I agree, something _very_ strange is going on here.  Removing the call to `imshow` makes it work correctly.  The bug is in some interaction between `plt.tight_layout` and `plt.subplot(...)`.

I suggest re-writing this loop as 

```python
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(4, 4)

for i, ax in enumerate(axes.ravel()):
    im = ax.imshow(np.random.normal(size=100).reshape([10,10]))
    ax.set_title(i)


plt.tight_layout()

```

**Comment by WeatherGod** [comment]
That is f-ed up. I wonder if the axes isn't really removed, just misplaced?

**Comment by Hongyu1230** [comment]
This is my attempted fix of the problem

It seems like tight_layout is not removing the subplots but when you tried to call tight_layout on the figure it resized the subplots that were already on it(which made them bigger because it had avaliable space), then when you add another subplot to the figure with the already resized plot they will disappear because subplot is plotting in their region.

I'm not really sure if this is a good fix though.
#https://github.com/Hongyu1230/matplotlib/commit/f21fc17117ee67cf39dae218bf88ea1ef2d572fc

**Comment by tacaswell** [comment]
@hamgyu1230  Can you open a pull request with that change (with a better commit message!).

Can you explain why clipping these values at 0 fixes the problem?

**Comment by Hongyu1230** [comment]
#6094 

my attempt to fix it basically made it so when the subplot sees that it has space it will return 0 and thus it can only shrink or stay the same instead.

**Comment by Hongyu1230** [comment]
#6094

by making these at 0, the subplot can only shrink or stay the same, thus the existing subplots shouldn't be overwritten by any new ones.

**Comment by Hongyu1230** [comment]
#6096

by making these at 0, the subplot can only shrink or stay the same even when there is avaliable space, thus the existing subplots shouldn't be overwritten by any new ones when a new subplot is plotted.

**Comment by adizhol** [comment]
Was this fixed? I have the same problem

**Comment by jklymak** [comment]
Not really, but if you just call `tight_layout` once, at the end, it all works fine.

**Comment by jklymak** [comment]
This is caused by `fully_overlaps` returning True for the last axes, and hence the old one gets deleted, as pointed out by https://github.com/matplotlib/matplotlib/issues/7393.  What happens is that the "tight" axes is larger and the new axes overlaps the old axes and deletes it.  I'm not sure what we can do to fix this, since the stated behaviour is that if you (partially) cover an axes it gets deleted.  Better is to create the axes first (`fig, axs = plt.subplots(4, 4)`) and then call `tight_layout`, hence avoiding too much magic.

**Comment by anntzer** [comment]
I actually think the "remove overlapping subplots" behavior is pretty bad and should be deprecated and removed; see https://github.com/matplotlib/matplotlib/issues/11435 and https://github.com/matplotlib/matplotlib/pull/7377#issuecomment-260049527.

**Comment by jklymak** [comment]
I agree, but I'm not sure how you deprecate that without a huge rigamarole.

**Comment by anntzer** [comment]
You just emit a warning if an axes that would have been removed under the old behavior will no longer be removed with the new one?  (telling whoever was relying on the old behavior that they need to explicitly call ax.remove() to suppress the warning)
That means no one can actually benefit from the new behavior until the deprecation elapses, but that seems OK?

**Comment by fzyzcjy** [comment]
I have the same problem

MacOS, matplotlib 3.1.3, MacOSX backend

**Comment by jklymak** [comment]
Here you are only calling tight layout at the end. If this is indeed reproducible then please provide a sec contained example and open a new issue.  If it's not reproducible, because you are _really_ calling tight_layout in the middle of the process sometimes, then it is the same bug.  Also if you want to add subplots to an existing figure just call fig.subplots(1,2)

**Comment by fzyzcjy** [comment]
@jklymak Thanks I will look at it to see how to reproduce it

**Comment by back2yes** [comment]
> `plt.tight_layout()` is removing an axes from the `fig.axes` list.
> 
> There is a simple work around here, just call `plt.tight_layout` once outside of the loop and it works correctly.

@jklymak Thanks you saved my day.

**Comment by Godfreyoise** [comment]
Please why is this code not running
 plt.figure(figsize=(10, 10))
for image, labels in data_train.take(1):
    for i in range(9):
        plt.subplot(3,3,i+1)
        
        plt.imshow(image[i]).numpy.()astype ('uint8'))
        plt.title(data_cat[labels[i]])
        plt.axis('off')

**Comment by Godfreyoise** [comment]
Please why is this code not running
 plt.figure(figsize=(10, 10))
for image, labels in data_train.take(1):
    for i in range(9):
        plt.subplot(3,3,i+1)
        
        plt.imshow(image[i]).numpy.()astype ('uint8'))
        plt.title(data_cat[labels[i]])
        plt.axis('off')

**Comment by Godfreyoise** [comment]
Please why is this code not running
 plt.figure(figsize=(10, 10))
for image, labels in data_train.take(1):
    for i in range(9):
        plt.subplot(3,3,i+1)
        
        plt.imshow(image[i]).numpy.()astype ('uint8'))
        plt.title(data_cat[labels[i]])
        plt.axis('off')

**Comment by rcomer** [comment]
@Godfreyoise for usage questions please go to https://discourse.matplotlib.org/.  You will need to provide a complete code example so that others can reproduce the problem.
