### ISSUE TITLE
Install from source on linux sets incorrect permissions for mpl-data files

### ISSUE THREAD

**Issue by mspacek** [matplotlib/matplotlib#4989]
I was using an old 1.4.x devel that was installed from git over a year ago. I needed to try a more recent version. Installing either the commit tagged `v1.4.3` or the latest HEAD gives me this font permissions problem when I try to import pylab:
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/pylab.py", line 231, in <module>
    import matplotlib.finance
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/finance.py", line 38, in <module>
    from matplotlib.collections import LineCollection, PolyCollection
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 1415, in <module>
    _rebuild()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 1400, in _rebuild
    fontManager = FontManager()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 1055, in __init__
    self.ttflist = createFontList(self.ttffiles)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 580, in createFontList
    font = ft2font.FT2Font(fpath)
IOError: [Errno 13] Permission denied: u'/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/mpl-data/fonts/ttf/cmex10.ttf'
```
This is Python 2.7.6 in Xubuntu 14.04. Before installing, I removed my old matplotlib install from `/usr/local/lib/python2.7/dist-packages`, then in the source folder, I ran `python setup.py clean`, `python setup.py build` and `sudo python setup.py install`. As expected, this created a new install at `/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg`. Here's the output of `sudo python setup.py install`: https://gist.github.com/mspacek/a5ef467a30e70846ea5f . Looks pretty normal to me.

The problem seems to be that the install script sets the wrong permissions for the `.ttf` files in `mpl-data/fonts/ttf`.

Here are the permissions as I drill down the tree:
```
drwxr-sr-x 6 root root 4096 Aug 25 17:33 mpl-data

drwxr-sr-x 5 root root 4096 Aug 25 17:33 fonts

drwxr-sr-x 2 root root 4096 Aug 25 17:33 ttf
```
Those seem fine. Here are the contents of the ttf folder:
```
-rw------- 1 root root  25680 Aug 25 17:33 cmb10.ttf
-rw------- 1 root root  21092 Aug 25 17:33 cmex10.ttf
-rw------- 1 root root  32560 Aug 25 17:33 cmmi10.ttf
-rw------- 1 root root  26348 Aug 25 17:33 cmr10.ttf
-rw------- 1 root root  20376 Aug 25 17:33 cmss10.ttf
-rw------- 1 root root  29396 Aug 25 17:33 cmsy10.ttf
-rw------- 1 root root  28136 Aug 25 17:33 cmtt10.ttf
-rw------- 1 root root   5954 Aug 25 17:33 COPYRIGHT.TXT
-rw------- 1 root root   5475 Aug 25 17:33 LICENSE_STIX
-rw------- 1 root root    320 Aug 25 17:33 README.TXT
-rw-rw-r-- 1 root root   8113 Aug 25 17:33 RELEASENOTES.TXT
-rw------- 1 root root 181152 Aug 25 17:33 STIXGeneralBolIta.ttf
-rw------- 1 root root 237360 Aug 25 17:33 STIXGeneralBol.ttf
-rw------- 1 root root 175040 Aug 25 17:33 STIXGeneralItalic.ttf
-rw------- 1 root root 448228 Aug 25 17:33 STIXGeneral.ttf
-rw------- 1 root root  41272 Aug 25 17:33 STIXNonUniBolIta.ttf
-rw------- 1 root root  30512 Aug 25 17:33 STIXNonUniBol.ttf
-rw------- 1 root root  46752 Aug 25 17:33 STIXNonUniIta.ttf
-rw------- 1 root root  59108 Aug 25 17:33 STIXNonUni.ttf
-rw------- 1 root root  13656 Aug 25 17:33 STIXSizFiveSymReg.ttf
-rw------- 1 root root  12228 Aug 25 17:33 STIXSizFourSymBol.ttf
-rw------- 1 root root  15972 Aug 25 17:33 STIXSizFourSymReg.ttf
-rw------- 1 root root  12556 Aug 25 17:33 STIXSizOneSymBol.ttf
-rw------- 1 root root  19760 Aug 25 17:33 STIXSizOneSymReg.ttf
-rw------- 1 root root  12192 Aug 25 17:33 STIXSizThreeSymBol.ttf
-rw------- 1 root root  15836 Aug 25 17:33 STIXSizThreeSymReg.ttf
-rw------- 1 root root  12116 Aug 25 17:33 STIXSizTwoSymBol.ttf
-rw------- 1 root root  15704 Aug 25 17:33 STIXSizTwoSymReg.ttf
-rw------- 1 root root  58716 Aug 25 17:33 VeraBd.ttf
-rw------- 1 root root  63208 Aug 25 17:33 VeraBI.ttf
-rw------- 1 root root  63684 Aug 25 17:33 VeraIt.ttf
-rw------- 1 root root  49052 Aug 25 17:33 VeraMoBd.ttf
-rw------- 1 root root  55032 Aug 25 17:33 VeraMoBI.ttf
-rw------- 1 root root  54508 Aug 25 17:33 VeraMoIt.ttf
-rw------- 1 root root  49224 Aug 25 17:33 VeraMono.ttf
-rw------- 1 root root  58736 Aug 25 17:33 VeraSeBd.ttf
-rw------- 1 root root  60280 Aug 25 17:33 VeraSe.ttf
-rw------- 1 root root  65932 Aug 25 17:33 Vera.ttf
```
They're only read and writeable by the owner, root. The permissions for these ttf files in my old install were all `-rw-rw-r--`, also owned by root. I'm almost certain I didn't set those manually. So, perhaps something about the install process has changed in the interim to cause this problem? This should work out of the box. There obviously shouldn't be a need to manually set permissions for a specific set of files that matplotlib installed, just to get pylab to import.

**Comment by tacaswell** [comment]
What version of setuptools/distuils are you using?

I _strongly_ suggest against ever doing `sudo python setup.py install` (but @efiring disagrees) of anything.  Either use your system packaged versions or venvs/conda (which live in user space).

**Comment by mspacek** [comment]
Looks like I'm using the `python-setuptools` package that comes with Ubuntu 14.04, version 3.3-1ubuntu2.

`sudo python setup.py install` is in the documentation. I don't see what's bad about it. This is generally how I install all Python software from source.

I just realized this permissions problem (`600` instead of `644`?) applies to almost all files in the `mpl-data/fonts` and `mpl-data/images` folders, but not to those in `mpl-data/sample_data` or `mpl-data/stylelib`. In the `images` folder, .ppm, .xpm and .png files are set to 600, while .svg files are set to 775.

Yes, I guess this could be some kind of bug in setuptools, but it's strangely selective. I also tried installing with `sudo pip install .`, but that gives me the same incorrectly set permissions.

**Comment by mspacek** [comment]
Just to confirm, setuptools reports version 3.3:
```
In [9]: setuptools.version.__version__
Out[9]: '3.3'
```

**Comment by efiring** [comment]
If you are building and installing from git, you might need 'git clean -dfx' in addition to the other clean-out steps.
We routinely install mpl from a tarball or from git on xubuntu 14.04 machines (real and virtual; sometimes with sudo, other times in a virtualenv), using setup.py, and have never seen this problem.

**Comment by tacaswell** [comment]
It's in the docs?! Can you point me to where?   The only place I can find `sudo` in the docs is to install system packages to get dependencies or in the mac install sections.  Suggesting to a typical user that they should do `sudo` is just a recipe for disaster.

What are the permissions on the font files in your source?

Installing into a venv the premissions come out correct:

````
(pip_test) ✔ /tmp/pip_test/lib/python2.7/site-packages/matplotlib-1.5.dev1-py2.7-linux-x86_64.egg/matplotlib/mpl-data/fonts/ttf 
21:58 $ ls -la
total 2152
drwxr-xr-x 2 tcaswell tcaswell    800 Aug 25 21:55 .
drwxr-xr-x 5 tcaswell tcaswell    100 Aug 25 21:55 ..
-rw-r--r-- 1 tcaswell tcaswell  25680 Aug 25 21:55 cmb10.ttf
-rw-r--r-- 1 tcaswell tcaswell  21092 Aug 25 21:55 cmex10.ttf
-rw-r--r-- 1 tcaswell tcaswell  32560 Aug 25 21:55 cmmi10.ttf
-rw-r--r-- 1 tcaswell tcaswell  26348 Aug 25 21:55 cmr10.ttf
....
```

**Comment by mspacek** [comment]
@efiring Thanks. `git clean -dfx` removed a bunch of .pyc files, but the end result was unfortunately the same.

@tacaswell It's line 143 in INSTALL. There's no `sudo` there, but `python setup.py install` doesn't work without `sudo`, because /usr/local is owned by root. That's completely normal, AFAIK. Use of `python setup.py install` is also mentioned on the website: http://matplotlib.org/users/installing.html#installing-from-source

Ah, the actual version-controlled files in mpl-data mostly had permissions set to 600. That's a problem. I deleted all the checked out files and re-checked them out of .git. That solved it. Now they're mostly 644. Must've been from copying over from an old hard drive last year. I was under the impression git version controlled permissions.

Thanks, and sorry for the noise! I see matplotlib is painfully slow to import now, but that's a different issue.
