### ISSUE TITLE
rename/deprecate bbox kwarg/property on `Text`

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4990]
As discussed in https://github.com/matplotlib/matplotlib/pull/4942#issuecomment-134762095 the 'bbox' kwarg/property is confusing.  Most places in mpl 'bbox' means 'the bounding box that the artists falls with in' where as in this case it is properties to go with a background patch behind the text artist.

**Comment by WeatherGod** [comment]
I am +1 on rename (through a deprecation cycle). But this could probably be
immediately addressed by simple docstring.

On Tue, Aug 25, 2015 at 10:36 PM, Thomas A Caswell <notifications@github.com
