### ISSUE TITLE
wrong zooming behaviour in constrain mode ('x' or 'y' is pressed) 

### ISSUE THREAD

**Issue by sdementen** [matplotlib/matplotlib#5007]
If 'x' is pressed during zoom and the user zoom, if the x spread is too short (ie abs(x - lastx) < 5) the zoom is not done.

Problem lies in function release_zoom at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L3045

    if abs(x - lastx) < 5 or abs(y - lasty) < 5:

where the test could be replaced by

    if (abs(x - lastx) < 5 and (self._zoom_mode != "y")) or 
       (abs(y - lasty) < 5 and (self._zoom_mode != "x")):

(but maybe the "x" and "y" should be swapped ...)

**Comment by tacaswell** [comment]
That is checking in pixel units, not sure we want to disable that.  This is basically a throttling mechanism.

What exactly to you mean by 'x spread'?

**Comment by sdementen** [comment]
If the user zooms only on the x axis (by pressing the key "x" while zooming), he will displace its mouse on the x axis for sure ==> we must check that he indeed moves on the x axis (hence the abs(x-lastx)<5.) otherwise we shouldn't zoom.
However, he may have left the y position at the same level (y ~ lasty) (remember, the user is zooming on the x axis) and so we will have abs(y-lasty) < 5 but it is OK, we shouldn't stop the zoom (ie return)

**Comment by tacaswell** [comment]
Ah, now I understand.  What do you think of changing the `or` to an `and`?  I think that fixes the problem with a much smaller change.

**Comment by sdementen** [comment]
The original logic looks sound so i would rather keep the or. In all cases,
we must at least check that y!=lasty if zoommode!="x" and vice verse of x
and lastx.

On Friday, August 28, 2015, Thomas A Caswell <notifications@github.com>
wrote:
> Ah, now I understand. What do you think of changing the or to an and? I
think that fixes the problem with a much smaller change.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/j3_7LorebgnlcudMs1QhprPYNmYO8O43Rvc_MVne-RxUbBNgyU8jkthQE1PFLB_frUwQudPvvmTgFSrOMk66KcahKIM7Z-ecnzVL2FrmQez5Qb_62ASc_oTGuXG4Nu4PSAqaV5MAKNkhZ6KLreFuqVQq_HxysA=s0-d-e1-ft#https://github.com/notifications/beacon/ABPpduBaa4EBzjxkdeY4eaHRqD4wJwidks5osIpxgaJpZM4F0DOd.gif
>

**Comment by tacaswell** [comment]
OK.  That function already uses `self._zoom_mode` so it isn't making things worse in terms of number of interconnections.

Can you put in a PR with your proposed changes?

**Comment by sdementen** [comment]
I can do that tomorrow during the day

**Comment by sdementen** [comment]
@tacaswell, did I do a correct PR ? Do I need to do something more ? (Never done it before)

**Comment by WeatherGod** [comment]
Thanks! I just recently noticed this issue myself, but hadn't had a chance to hunt down the cause.
