### ISSUE TITLE
Add Hershey Fonts a la IDL

### ISSUE THREAD

**Issue by grimknight** [matplotlib/matplotlib#5013]
Please add support for Hershey Fonts for typography on plots with LaTeX support. 

http://www.exelisvis.com/docs/Using_Hershey_Vector_Fon.html

**Comment by mdboom** [comment]
What's the use case here?  Hershey fonts are basically an obsolete font technology designed for vector plotters.

**Comment by esheldon** [comment]
The use case is that some people like the look of these fonts.  It is a subjective preference.  I also prefer these fonts for plotting.

**Comment by jenshnielsen** [comment]
It seems like a much more useful approach would be to make the fonts available in a modern format that can be used directly by matplotlib and others https://lwn.net/Articles/654819/

In any case most of the font support in matplotlib comes from freetype and fontconfig or LaTeX in usetex mode, I don't see any indication that these fonts can be used in LaTeX or loaded with freetype

**Comment by efiring** [comment]
Given that the Hershey fonts are not presently available in a form that mpl can use, I am going to close this issue.  If and when something like the project referred to in the lwn.net link above reaches maturity, and the Hershey fonts are available via the mechanisms mpl uses, the issue can be re-opened.
