### ISSUE TITLE
Allow different line lengths for each bar in an eventplot

### ISSUE THREAD

**Issue by languitar** [matplotlib/matplotlib#5028]
For some use cases it is important to visualize a property like an event size in addition to the point of occurrence of the event in time. Therefore it would be nice if the linelengths property of `eventplot` would also support a 2d array with the same shape as positions, where each entry maps an individual linelength to each event instances.

**Comment by tacaswell** [comment]
Have you looked at the `stem` method?

**Comment by languitar** [comment]
Might be an option to use, but the proposed way would still allow other kinds of visualization with less visual clutter.
