### ISSUE TITLE
replace Grace Hopper with John Hunter image

### ISSUE THREAD

**Issue by fariza** [matplotlib/matplotlib#5046]
Before going any further what do you think of changing Grace Hopper image (she is great and all) for one of John Hunter?

I know the change was recent from Lena to Grace Hopper but I think John is more emblematic of Matplotlib than Grace.

If this seems like a good Idea, somebody close to the family can ask for permission and an appropriate image. If not we just close the issue and nothing happen ;)

**Comment by anntzer** [comment]
Doesn't seem close to happening.  May (or may not) get more responses if proposed on the mailing list.  Closing, at least for now.
