### ISSUE TITLE
Don't draw end caps on error bars by default

### ISSUE THREAD

**Issue by HDembinski** [matplotlib/matplotlib#5047]
The current default is to display end caps on error bars.

![errorbar_demo_features](https://cloud.githubusercontent.com/assets/2631586/9798244/bde5a546-57cd-11e5-89c8-e37e225a301c.png)

I argue that end caps are not useful as visual cues for most plots. They are seriously harmful in "busy" plots with many data points, where error bars start to overlap and the end caps start to cross other error bars.

Tufte teaches us that we should maximize the data-to-ink ratio. End caps do not provide any additional information over the error bar, so they should not be there by default. End caps are useful to indicate a secondary interval, like the systematic uncertainty of a point, a beautiful example is Fig. 13 in this paper:
http://arxiv.org/pdf/1409.4809v3.pdf

I recently introduced a patch to make the default length of these end caps part of the configuration, so that they can be turned off by default (by setting errorbar.capsize to 0 in matplotlibrc). Please make this the new default. :)

**Comment by fergalm** [comment]
As a user (not yet a contributor), I'm not a fan of this change. I'd guess that >90% of the plots I see in astronomy have end caps, so that seems like the natural default choice.

**Comment by HDembinski** [comment]
fergalm's argument in favour of end caps is not a very good. Here are some counter-arguments:

1) I'd argue that the new defaults should be based on proven design principles, not on what's common. If we chose based on common use, then we should also keep jet as the default colormap, because "everybody" is using jet.

2) matplotlib is popular in the astronomy community. I wouldn't be surprised if endcaps are common, exactly because they are the default in matplotlib. So unless we change the default to something that is better, fergalm's argument will remain a tautology.

3) No information is lost when end-caps are removed, but visual clarity is gained in all plots, and especially in busy plots with many points and nearly overlapping error bars.

**Comment by WeatherGod** [comment]
I would also be against removing caps as well because it isn't actually
"extra ink". If you think about it, the lines are really the extra ink.
Those lines don't communicate anything useful except to connect the end
caps to the mean, which could easily be accomplished by having grid lines
(which is another proposal). Endcaps are also useful in projector
situations because long, thin, vertical lines aren't always very visible in
conference rooms.

**Comment by fergalm** [comment]
> 1) I'd argue that the new defaults should be based on proven design principles, not on what's 
> common. If we chose based on common use, then we should also keep jet as the default 
> colormap, because "everybody" is using jet.

"What's common" is a great design principle. It's also known as the principle of least surprise. I suspect most people will be surprised if they try to plot an error bar and don't get end caps by default

> 2) matplotlib is popular in the astronomy community. I wouldn't be surprised if endcaps are common, 
> exactly because they are the default in matplotlib. So unless we change the default to something 
> that is better, fergalm's argument will remain a tautology.

The current matplotlib style of drawing error bars mimics a style that pre-dates matplotlib by many years. For example, pgplot draws end caps, and it was created in 1983.

>  3) No information is lost when end-caps are removed, but visual clarity is gained in all plots, and 
> especially in busy plots with many points and nearly overlapping error bars.

In sparse plots the end caps draw attention to the error bars, so I think visual clarity is lost by removing them.

There's a lot of "I think" and "I like", because ultimately this is an aesthetic choice. But my vote is against.

**Comment by tacaswell** [comment]
Always remember the style module so if you don't like the defaults it is very easy to override the ones you don't like.

I think a 'tufte' style sheet would be a worthwhile thing to have even if it is not everyone's cup of tea.

**Comment by HDembinski** [comment]
> "What's common" is a great design principle. It's also known as the principle of least surprise. I suspect most people will be surprised if they try to plot an error bar and don't get end caps by default

The principle of least surprise is a good one, I agree, and the change I am requesting is not very surprising.

On the other hand, "What's common" is a terrible design principle. All progress is about change, not about doing the same thing all over. Do you have an iPhone? Think about why they are so popular. Before we got them, nobody could imagine that phones and software could be that intuitive and playful. Now we cannot imagine how we could live with the clunky interfaces we had before. iPhones were different in a better way, and that's why they took over. I don't want to be dragged into an argument about commonness and the "majority of users", because it is not the point.

> I would also be against removing caps as well because it isn't actually "extra ink". If you think about it, the lines are really the extra ink.

The command is called "errorbar". It draws error _bars_, you can hardly call that the "extra ink". If the lines are too thin, they can be made bigger. This is again not the point. I am also not against end caps in principle, as shown in the paper cited initially. The end caps alone (without a bar) are very useful to indicate a secondary uncertainty, typically a systematic uncertainty, in addition to a statistical uncertainty indicated by the error bar.

The default changes are a great chance for matplotlib to go forward. I offered my arguments, and I can continue to defend them, but I respect the decision of the higher-ups whatever they decide. As a friend and promoter of matplotlib, I am just trying to contribute in a positive way.

**Comment by Tillsten** [comment]
Here a direct comparison with thicker lines instead of caps:

![bla](https://cloud.githubusercontent.com/assets/189880/9970616/6a98ea80-5e56-11e5-97e3-ce2fbf53c96f.png)

**Comment by fergalm** [comment]
For what it's worth (and I agree it's not worth a whole lot), I did an unscientific poll of the astronomers in my office. I asked "If you were starting to use a new plotting package, would you prefer if the plot error bar function plotted endcaps by default or not". There were 6 votes in favour of end caps by default, and 2 vote against. One of those two voting against changed their minds after discussing it with me, but it's probably fairer to record their initial vote.

**Comment by HDembinski** [comment]
In addition to the nice comparison from Tillsten, here is an example of a more busy plot. It visually compares two Gaussian distributions. I used the standard settings for the plot on the left and alpha=0.5. For the plot on the right, I used capsize=0, linewidth=2, alpha=0.5.

Plots with a high density of data points like this are typical in my area of research, high energy physics and astroparticle physics. With endcaps, the plot looks more messy and are harder to read. Our brain merges all these thin lines into kind of a blur. Look at the points near the maximum, for example. 

Without the end caps, the points stand out more, and the two distributions are easier to separate by eye.
![figure_1](https://cloud.githubusercontent.com/assets/2631586/10051780/4d8ec330-61f1-11e5-9986-b6aa416ae1e8.png)

**Comment by efiring** [comment]
I'm convinced.  Losing the endcaps would make for a more functional as well as aesthetically pleasing default. By emphasizing the precise ends, the endcaps are visually misleading; errorbars are *rough* estimates of a range, typically based on arbitrary cutoffs in an assumed statistical distribution.  It would make more sense for them to fade out at their ends than to have them capped by lines; but that's getting too fancy.  A simple line is a reasonable compromise.

**Comment by WeatherGod** [comment]
We should probably pick a default line thickness and marker size that would
result in properly centered lines. This has actually been a long-standing
pet peeve of mine for errorbars (you can see the non-centered-ness in the
examples posted here).

**Comment by efiring** [comment]
Yes, I noticed that too.  I presume it is caused by snapping to pixel boundaries.  Unfortunately, I don't see how that can be solved via the defaults.  Sizes are in points, and the translation to pixels depends on dpi, which can be changed at any time.  We would need a way of ensuring that anything subject to snapping gets expanded or contracted to a width that is an odd number of pixels.  Or something like that.  attn: @mdboom

**Comment by Tillsten** [comment]
One think i don't like about thicker lines is that this leads to more visual weight on the points with the biggest errors. Probably the best would increase the alpha with the error size :)

**Comment by flying-sheep** [comment]
what purpose do error bars have?

* for categorical x axes there are violin plots that better show distributions. another alternative would be to use vertical gradients instead of hard ends (the intensity of the color would be the probability)

* for continuous x axes, you should use a line plot instead of individual dots and correspondingly a shaded error region instead of the error bars.

**Comment by HDembinski** [comment]
flying-sheep: this is starting to get somewhat off-topic, but violin plots are not the ultimate answer to everything. I would argue again with Tufte: why use more ink when the same information can be represented with less?

Simple error bars are good indicators if:
* the represented probability distribution is normal and everybody knows it; then a central value (point) and a simple +/- 1 sigma interval (error bar) summarizes the information perfectly
* the represented probability distribution is not known, e.g. for systematic errors that are only estimated as a kind of upper limit

A histogram with Poisson uncertainties on the individual bins is a standard case that is well represented by errorbar.

**Comment by DerWeh** [comment]
I have to say that I find this change simply horrible. It removes the information where error bars end and thus renders them unusable without the caps. Consider the following example:

![without_caps](https://user-images.githubusercontent.com/22542812/45039484-04e2f100-b064-11e8-9be0-704e66d698a9.png)
![with_caps2](https://user-images.githubusercontent.com/22542812/45040016-3f995900-b065-11e8-8390-102fdadfb454.png)

The first plot indicates that the errors of line1 are too small to be seen (hidden behind the marker) and thus negligible. The plot with caps however reveals that this is certainly not true. The vertical lines are arguable only visual clutter however they are a guide to the eye to find the actual errors.

Obviously I can just change the settings (after finally finding out these things are called caps). I find this change however very dangerous, as in a less obvious case I am tricked into reading the plot wrong. This should never happen! Thus, I would argue to make the caps bigger than the actual marker by default.

**Comment by tacaswell** [comment]
@DerWeh I'm sorry you had this issue, however it is unlikely that we will revert this change.  

The use cases for Matplotlib are very broad and a stylistic choice that makes sense in one field (or with one set of data) does not make sense with another.  This issue appears to happen when 1) you have discrete x values shared across all of your datasets 2) the y values are almost identical 3) the error range of the first set is strictly less than the second at all points.  If any of those things were not true, we would not be having this conversation ;).  

You might also consider setting the alpha of each of the artists to 0.5 so you can see when they overlap. 

I would argue the real bug here is the interlaced z-order layering of the markers, errorbars, and caps...

**Comment by HDembinski** [comment]
@DerWeh The standard solution to your plotting problem is to add slight offsets for two sets of points. Shift the orange points a pixel to the left and the blue points a pixel to the right. Then they are very nicely comparable. Furthermore, if you insist on caps, although they are intentionally absent in most high-quality scientific papers in my field, you can still override matplotlibrc. Just set the capsize to 3.

**Comment by OnlyBelter** [comment]
This is a kind of solution: https://stackoverflow.com/a/49838455/2803344

**Comment by fergalm** [comment]
I lost this argument a number of years ago, but I will say I have yet to meet anyone who thinks the default is the better choice.

**Comment by flying-sheep** [comment]
the overlay problem is just a symptom of another problem with that plot: directly overlaying errorbars is not something you should ever do. moving them slightly to the side is how that plot should have looked in the first place.

there’s quite a few people who think the new default is better in this very thread.

but to be fair, matplotlib doesn’t make it easy to do the right thing. `hist` automatically staggers the bars, but you can’t do the same for other kinds of plots.

**Comment by fergalm** [comment]
> there’s quite a few people who think the new default is better in this very thread.
But none of them I've ever met. The people I work with who've expressed an opinion all dislike it. But I'm not going to relitigate it.

**Comment by flying-sheep** [comment]
well, physicians and physicists also preferred the jet colormap, because it was ubiquitous in their respective fields. studies show that it however decreases their performance in interpreting plots. what people prefer is never a good argument. it’s at most a hint at what *might* have proven itself through experience

**Comment by HDembinski** [comment]
I agree with @flying-sheep. You need objective rational arguments for your position. The new defaults were chosen so the average plot looks better. There are principles and rational arguments behind this decision, especially "increase the data-to-ink ratio", https://infovis-wiki.net/wiki/Data-Ink_Ratio.

You can still change the default to whatever you prefer, on a plot-by-plot basis and even permanently, by changing your `matplotlibrc` file.

**Comment by DerWeh** [comment]
I don't want to reopen the discussion here, I will just accept that matplotlib makes horrible choices and will always keep the overhead in my code, to always remember it.

@HDembinski The data-ink ratio is actually an argument against this choice. The cap contains the complete information, namely how big the uncertainty is. The error line itself contains no information whatsoever. It is solely a guide to the eye, to find the end more easily. 

What I really want to use this answer for, is to strongly emphasis that the defaults should not focus on making nice looking plots but unambiguous ones. Aesthetics is to a certain point always up to the beholder, and he is encouraged to change the design in a way he finds pleasing. 

However, wrong information should never be conveyed. That is why it was so important to change the default color map. This belongs to me in the same category.
The plot I showed was exactly such an example (and it is a real-life example). I tried different algorithms and suddenly my plot showed me that algorithm 1 is orders of magnitude better, as there was no more visible error in comparison to plot 2. You can now say, just change the design how you like it. But that just makes it even more dangerous for me, as I might forget about the terrible choice matplotlib does. I go to a different machine and might do the same error again and might lose a workday if I am not careful.

Thus, I just plead, focus that the plots represent the information. What you do afterwards to make the plots look better doesn't bother me. If I want a good-looking plot, I will change it anyway. But never misguide me, when I just want a quick representation of my data.

**Comment by jklymak** [comment]
W/o wading through the religious war above, I think this behaviour would be an obvious one to expose via an rcParam if it’s not already.  If it is an rcParam already, then I’m not sure what the problem is.

**Comment by kenogo** [comment]
@DerWeh Like others have pointed out, both of your plots weren't easy to read at all. If your argument depends on doing something you should really never do (overlaying error bars), then it is a rather weak argument.

Your point about the data-ink ratio would mean that you propose removing error bar altogether and just keeping the caps. First of all, I disagree with the notion that the precise position of the caps is the important information in error bars. Most of the time, they are important for checking overlap of the data with a fitted model. In my opinion, caps only distract from them. Remember that statistical errors are not precisely defined values but just statistical estimates. Secondly, removing the error bars and only printing the caps would lead to the caps not being attached to the data points any more, which would make the most common task of error bars (checking the overlap of data with a fit) even harder and would be confusing in general.

Finally, if you expect matplotlib's default choices to work in _every_ scenario and even run into the possibility of not thinking about how you're representing your data but just leave it to matplotlib instead, then you're the one making terrible choices. Your example plot was not a typical plot by any means, at least not without offsetting the two data sets. So there is no reason to expect matplotlib's default configuration to produce an unambiguous plot. Maybe there'll be some robust ML solution for that in the future, but for now, checking the plots for unambiguousness is up to the researcher.

**Comment by tacaswell** [comment]
This thread is getting contentious and needlessly personal.

It is the case that this behavior can be controlled both by an rcparam (for global control) and via a kwarg (for per-call control).  

It is also the case that we are not going to change the defaults.

Given those three things I am going to lock this thread as I do not think further discussion is going to be productive.

**Comment by tacaswell** [comment]
As a procedural note, was between "resolved" and "too heated" in the lock dialog.  People with commit rights will still be able to comment and can unlock the thread.

If anyone has issues with me locking this and either can not (or does not want to) comment here, send me an email.
