### ISSUE TITLE
pandas v0.17.0rc1

### ISSUE THREAD

**Issue by jreback** [matplotlib/matplotlib#5050]
we have some fairly significant changes and would like you to test and provide any feedback: https://github.com/pydata/pandas/releases/tag/v0.17.0rc1

thanks!

**Comment by WeatherGod** [comment]
You are going to have to be more specific. Matplotlib's support for Pandas
has been very hit-or-miss in the past, and we don't claim any sort of
official support for pandas or other similar objects. Our test suite
doesn't utilize pandas at all.

**Comment by jreback** [comment]
ok, then its just a heads up. Ok, mainly I am concerned with simply importing and showing deprecation warnings (as the sorting things were changed a bit).

I know you guys don't directly import, but hey, can't hurt :) thxs

**Comment by shoyer** [comment]
Probably worth testing out https://github.com/matplotlib/matplotlib/pull/4829 with the pandas RC (cc @JanSchulz @tacaswell), though I would be seriously surprised if any issues came up.

**Comment by tacaswell** [comment]
What is the time frame on this?

**Comment by shoyer** [comment]
@jreback writes in the announcement email:

> We will be releasing officially in 1-2 weeks or so.
