### ISSUE TITLE
When zooming a triangle is rendered instead of a rectangle.

### ISSUE THREAD

**Issue by andnovar** [matplotlib/matplotlib#5052]
Mpl is sending the number of vertex that are at least visible, for instance if the rectangle drawn is inside the bar it will send 0 paths since no paths are enclosed in that area. In the case of enclosing the right line it tries to create a mesh with the origin and the line enclosed. In the case of enclosing the left line since the origin and the line have the same y is just shown the line. This happens as well in Gtk and in none of the Agg backends neither backend_kivyagg. There is some clipping problem here.

![screenshot from 2015-08-21 12 51 27](https://cloud.githubusercontent.com/assets/400600/9416779/bba8bc22-4815-11e5-826c-29fc91970716.png)
![screenshot from 2015-08-21 12 51 35](https://cloud.githubusercontent.com/assets/400600/9416780/bbb6c56a-4815-11e5-8dda-b73840cda18f.png)

**Comment by jenshnielsen** [comment]
> This happens as well in Gtk and in none of the Agg backends neither backend_kivyagg.
Can you clarify this a bit? Does it only happen in Gtk or in the Agg backends too?

**Comment by WeatherGod** [comment]
I parsed that sentence to mean that any AGG-based backends are immune to
this problem, including his implementation of kivyagg backend, while his
"kivy" backend and our "gtk" backends suffer from this problem. This could
possibly point to an issue that might have been fixed in AGG, but we
completely forgot to address it in the "pure" backends? Makes me wonder if
any of our vector backends suffer from this?

**Comment by tacaswell** [comment]
This is related to https://github.com/kivy-garden/garden.matplotlib/issues/16

We special case this in the SVG backend and I suspect the pdf/ps backends as well.

**Comment by mdboom** [comment]
I don't know if this helps: Clipping should be explicitly disabled on filled paths.  The algorithm used does not support clipped paths.

**Comment by tacaswell** [comment]
Might be related to #5955

**Comment by tacaswell** [comment]
@andnovar Is this still a problem?

**Comment by andnovar** [comment]
@tacaswell I think this got fixed with the latest release, not sure though. I'll confirm tonight.

**Comment by anntzer** [comment]
Fixed, if I understand correctly.  Feel free to request a reopen otherwise.
