### ISSUE TITLE
PyQt4 canvas crashing on MacOS X 10.8

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#5058]
With the latest master version of matplotlib I am seeing the following error in IPython:

```python
In [1]: %matplotlib qt4

In [2]: import matplotlib.pyplot as plt

In [3]: plt.figure()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/tom/miniconda3/envs/mpldev/lib/python2.7/site-packages/matplotlib-1.5.dev1-py2.7-macosx-10.5-x86_64.egg/matplotlib/backends/backend_qt5agg.pyc in paintEvent(self, e)
     87             # (bgra).
     88             if QtCore.QSysInfo.ByteOrder == QtCore.QSysInfo.LittleEndian:
---> 89                 stringBuffer = self.renderer._renderer.tostring_bgra()
     90             else:
     91                 stringBuffer = self.renderer._renderer.tostring_argb()

AttributeError: 'FigureCanvasQTAgg' object has no attribute 'renderer'
Out[3]: <matplotlib.figure.Figure at 0x1099faa50>
```

Does anyone else see this error?

**Comment by efiring** [comment]
Yes, I get it with master built in an Anaconda environment on OS X 10.9, python 3.4.

**Comment by tacaswell** [comment]
This is probably a subtle draw order issues where the paint event gets fired before the first `draw` call has finished.

I have an idea on how to fix this, give me 5min

attn @pwuertz

**Comment by efiring** [comment]
As another data point, I *don't* get the error with python 3.4 on linux.  That sounds consistent with your hypothesis of a "subtle draw order issue".

**Comment by pwuertz** [comment]
Right, to be safe I'd add a
`if not hasattr(self, "renderer"): return`
line at the beginning of paintEvent. You are alreadyon it?

**Comment by tacaswell** [comment]
See #5060,  I added a call to the parent `draw`, but I see the case for just returning.
