### ISSUE TITLE
Precompiled wheel for Python 3.5

### ISSUE THREAD

**Issue by willingc** [matplotlib/matplotlib#5059]
Python 3.5 was released today. I'm posting this as a reminder (or helpful tip) for those trying to `pip install matplotlib` for Python 3.5 on OS X. You may need to build matplotlib from source until a precompiled wheel is available on PyPi.

Additional detail: https://bugs.python.org/issue25088

**Comment by tacaswell** [comment]
attn @matthew-brett

**Comment by matthew-brett** [comment]
On it, thanks.

**Comment by matthew-brett** [comment]
Binary wheel building broken for Python 3.5 : https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3#comment-21340853

**Comment by matthew-brett** [comment]
Wheel building fixed by new release of `wheel` package - 0.25.0

**Comment by matthew-brett** [comment]
Oops - fixed for some packages, not others : https://bitbucket.org/pypa/wheel/issues/148/unorderable-types-error-for-python-3

**Comment by matthew-brett** [comment]
`wheel` package now fixed, but you will need the latest version - 0.26.0.

**Comment by willingc** [comment]
Thanks @matthew-brett :sunglasses:
