### ISSUE TITLE
improve whats_new entry for prop cycler 

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#5067]
@WeatherGod 

Currently it mostly talks about the new rcparam

**Comment by cgohlke** [comment]
Please also document the new [dependency](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L27) on the [cycler](https://pypi.python.org/pypi/Cycler) package. Or maybe bundle the single in `matplotlib/externals`?

**Comment by tacaswell** [comment]
I am strongly :-1: on bundling into externals.

See #5073 for dependency documentation.

@cgohlke I don't remember if you saw it go by, but we _do_ bundle six.

**Comment by WeatherGod** [comment]
The whats_new is already horrendously long. Do we really want to make it
longer? I should note that the linked source code example demonstrates both
the rc param and the `set_prop_cycle`.

If I have time today, I will put together a PR that makes various fixes and
improvements to whats_new (such as cbook.is_sequence_of_strings() in a
completely wrong location, and the classic/default style stuff tucked away
near the bottom).

On Tue, Sep 15, 2015 at 10:26 AM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
Clearly we just need to release more often to keep the whats_new short :shipit: 

I think the property cycling should be one of the flag-ship features for this release to is deserves a better example than it has.

One thing that might help is to turn the entire rcparams section into a table...

**Comment by WeatherGod** [comment]
I very much agree with the need to release more often (as a side note, I
think landing MEP22/27 would be a good milestone for 2.1).

Let me first try cleaning up whats new. As for improving stuff for
prop_cycler, what might make more sense is to make a documentation page
specifically for all things related to cyclers and link to that. whats_new
really should only be a teaser.

On Tue, Sep 15, 2015 at 11:25 AM, Thomas A Caswell <notifications@github.com

**Comment by cgohlke** [comment]
Related to not bundling `cycler`: I think it is no longer feasible to use `bdist_wininst` installers to install matplotlib and dependencies on Windows. We should consider to discontinue providing wininst installers and only support wheels. At that point it makes sense to also revert bundling `six`.

**Comment by tacaswell** [comment]
Do I want to ask why `bdist_winist` is no longer feasible?  Is it worth pulling one of the core-devs who works an MS (Steve Dowre and Brett Cannon) into this discussion?

attn @matthew-brett as the main advocate for bundling `six`

**Comment by cgohlke** [comment]
There's no technical problem building `bdist_wininst` installers for matplotlib. But since I switched to wheels on my website it has become difficult/impossible to find pre-built `bdist_wininst` installers for matplotlib's dependencies (`setuptools`, `pytz`, `python-dateutil`, `pyparsing`, `cycler`, and even `numpy`) for all supported platforms. It is not a good idea to mix package managers such as `pip`, `bdist_wininst`, and `MSI`.

**Comment by tacaswell** [comment]
@cgohlke Great, we will defer to your judgment on all matters windows installations.
