### ISSUE TITLE
numpy incompatibility

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#5078]
We have non np 1.6 compatible code in the gdk backend which we do not test on travis.

Issue reported by @cgohlke 

http://matplotlib.1069221.n5.nabble.com/Matplotlib-devel-First-release-candidate-for-the-1-5-0-series-tp46156p46166.html

http://stackoverflow.com/questions/28499580/matplotlib-import-error-backend-gdk-soundefined-symbol-pyarray-setbaseobjec

The code in question went in in 
https://github.com/matplotlib/matplotlib/pull/3665

which was in response to discussion at

http://thread.gmane.org/gmane.comp.python.matplotlib.general/34771/focus=34771

Options here are: 

 - fix code to address both issues (no idea how hard that would be)
 - up the minimal numpy until it works

I am in favor of bumping the numpy version, but do not feel strongly.

**Comment by tacaswell** [comment]
We would only have to bump to 1.7 http://docs.scipy.org/doc/numpy-dev/reference/c-api.array.html#c.PyArray_SetBaseObject

attn @mdboom @jkseppan

**Comment by mdboom** [comment]
I don't have any objections to dropping numpy 1.6 support.

We should probably add the magic incantation that enforces the Numpy 1.7 API if we do this so it doesn't regress again, but I don't know how many changes would be required...  That can wait for another PR, of course.

**Comment by jkseppan** [comment]
If the fix is as simple as https://github.com/scipy/scipy/blob/master/scipy/signal/lfilter.c.src#L285-L292 I think we should just apply it. Is there a simple test case? I don't regularly use the gdk backend.

**Comment by jkseppan** [comment]
Oh, I guess it would be a compile-time error so the test case is easy if I can otherwise get gdk to compile?

**Comment by mdboom** [comment]
Yeah -- I think if we can install the gtk development packages on Travis, this extension would get built and then we'd at least catch simple compilation errors.

**Comment by jkseppan** [comment]
I think the fix would be something like https://github.com/jkseppan/matplotlib/commit/4ab9919810c506ef174590b9bf3fc3904309d613 but I didn't even try to compile it yet.

**Comment by jkseppan** [comment]
Unfortunately it's not a compilation error: it's just
```
    src/_backend_gdk.c:55:5: warning: implicit declaration of function ‘PyArray_SetBaseObject’ [-Wimplicit-function-declaration]
         PyArray_SetBaseObject(array, (PyObject *)py_pixbuf);
         ^
```
But `import matplotlib.backends.backend_gdk` triggers the error for me.

**Comment by jkseppan** [comment]
Would appreciate review of #5080, especially by someone who uses backend_gdk actively.

**Comment by OceanWolf** [comment]
Probably easier to do a shout-out on the mailing list for this?  Not so many people get alerted to issues/PRs...

**Comment by jkseppan** [comment]
I mentioned it at http://permalink.gmane.org/gmane.comp.python.matplotlib.devel/13729
