### ISSUE TITLE
Can't build 1.5RC1 on Mac OSX

### ISSUE THREAD

**Issue by TomAugspurger** [matplotlib/matplotlib#5082]
Not sure if this is user error, but figured I'd raise an issue.

I'm trying to build a conda package on OSX, python 3.4.
I succedded building matplotlib 1.4.3 [here](https://anaconda.org/taugspurger/matplotlib), using a variant the conda recipie in the `conda-recipies` repo. I had to change the `sed -i` lines in https://github.com/conda/conda-recipes/blob/master/matplotlib/build.sh which failed for me.

I tried the same thing with @tacaswell's version https://github.com/conda/conda-recipes/pull/419 (with the same changes to the `sed -i` lines) I get this failure

```bash
===== testing package: matplotlib-1.5.0rc1-nppy34_0 =====
running run_test.py
Traceback (most recent call last):
  File "/Users/tom.augspurger/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 30, in <module>
    import matplotlib.pyplot
  File "/Users/tom.augspurger/miniconda3/envs/_test/lib/python3.4/site-packages/matplotlib/pyplot.py", line 110, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/tom.augspurger/miniconda3/envs/_test/lib/python3.4/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/tom.augspurger/miniconda3/envs/_test/lib/python3.4/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends.
TESTS FAILED: matplotlib-1.5.0rc1-nppy34_0
```

I'll look more later. FWIW I saw this same error when trying to build matplotlib 1.5 with python 3.5, but managed to get around that somehow (I think by changing a line in my ipython config, not sure).

EDIT: A bit more info about this last bit. On a homebrew install with python 3.5, matplotib 1.5

```python
In [1]: %matplotlib osx
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-b548c8a3ffcc> in <module>()
----> 1 get_ipython().magic(u'matplotlib osx')

...

/Users/tom.augspurger/Envs/py27/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.10-x86_64.egg/matplotlib/backends/backend_macosx.py in <module>()
     22
     23 import matplotlib
---> 24 from matplotlib.backends import _macosx
     25
     26

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends.
```

but with (the same) homebrew python 3.5, matplotlib 1.4.3 I am able to use `%matplotlib osx`.

Summary

python | matplotlib | status
--------- | ------------ | --------
brew | 1.4.3 | good
brew | 1.5.0 | framework error
conda | 1.4.3 | good
conda | 1.5.0 | framework error

So it seems to be a matplotlib thing, not necessarily conda.

**Comment by tacaswell** [comment]
attn @jenshnielsen @mdehoon

**Comment by TomAugspurger** [comment]
This thread came up when I was looking earlier: http://sourceforge.net/p/matplotlib/mailman/message/32724556/

**Comment by mdehoon** [comment]
Matplotlib 1.5.0 checks more carefully if Python is installed as a framework (which is required for GUIs to work correctly) than previous versions. Can you check if your Python is actually installed as a framework? If not, then the RuntimeError raised by matplotlib is correct.

**Comment by TomAugspurger** [comment]
User error it was then. Sorry for the noise! My homebrew install is not a framework. I'm not sure how conda handles it, but it seems it's not a framework.

I've successfully built the conda package and uploaded it [here](https://anaconda.org/taugspurger/matplotlib).

**Comment by pelson** [comment]
> User error it was then. Sorry for the noise!

Not at all. I saw a similar issue, and was glad to find this. :+1:  (mine was found in: https://github.com/conda-forge/staged-recipes/pull/3)

**Comment by jenshnielsen** [comment]
The issue is not really with homebrew or Conda but with virualenvs. 

I have stated to write up some documentation on how to work around these issues but I failed to finish it for the release candidate. https://github.com/jenshnielsen/matplotlib/blob/799e0fed6336da6db8b70e3b2948f225d513a8fb/doc/faq/virtualenv_faq.rst
