### ISSUE TITLE
1.5 and 2.0 release schedule

### ISSUE THREAD

**Issue by 8one6** [matplotlib/matplotlib#5088]
With apologies that this is almost certainly in the wrong place: When are versions 1.5 and 2.0 scheduled for release?  What is the appropriate forum/discussion board/website to monitor to learn that sort of thing?

I've seen a few sources saying that both 1.5 and 2.0 release dates were supposed to be before the beginning of September, but it seems like the current production version is still 1.4.3.

**Comment by jkseppan** [comment]
The discussion happens on the mailing list, see http://thread.gmane.org/gmane.comp.python.matplotlib.devel for a web archive and http://article.gmane.org/gmane.comp.python.matplotlib.devel/13715 for the most recent thread on this topic.
