### ISSUE TITLE
`Template` backend fails when `usetex` is set

### ISSUE THREAD

**Issue by ian-r-rose** [matplotlib/matplotlib#5090]
The draw-nothing `Template` backend fails when I select `usetex` in the rcparams, with error:

```
AttributeError: 'RendererTemplate' object has no attribute '_text2path'
```

The following minimal example reproduces this for me:

```
import numpy as np

import matplotlib
matplotlib.use('Template')

import matplotlib.pyplot as plt

plt.rc('text', usetex=True)

x = np.linspace(0., 2.*np.pi, 100)
y = np.sin(x)

plt.plot(x,y)
plt.savefig('test.pdf')
```

Looking at the code for the `RendererTemplate` class suggests that there is a missing call to `RendererBase.__init__` in `RendererTemplate.__init__`, but I defer to those with more knowledge of the internals of matplotlib.

**Comment by WeatherGod** [comment]
Is there a particular reason why you are using the "Template" backend?  I
doubt that it has been properly maintained now that we have several example
implementations of backends.

**Comment by ian-r-rose** [comment]
I am using it to automate running some test scripts.
I just want to verify that they run but am not interested in producing/inspecting the output.
