### ISSUE TITLE
Easier way to plot shear arrows (or half arrows)

### ISSUE THREAD

**Issue by tobias47n9e** [matplotlib/matplotlib#5095]
In order to do proper structural geology plots one needs shear arrows (or half arrows) to indicate sinistral and dextral movements along a plane:

![shear arrows example](https://cloud.githubusercontent.com/assets/6953323/9929320/39c93818-5d2c-11e5-850f-a1c35aee3d66.JPG)

The best solution I could come up with uses the text annotations, but the result is very inconsistent with the typical matplotlib arrows:

![half arrow plot](https://cloud.githubusercontent.com/assets/6953323/9929359/71fb1026-5d2c-11e5-9f80-0a3b820b2451.png)

I was wondering if this could be added to matplotlib. For example the quiver function could allow for custom arrows and add shear arrows to the collection.

The two downstream projects that would immensly profit from these changes:
- https://github.com/joferkington/mplstereonet
- https://github.com/innstereo/innstereo

If anyone is interested, the code from the example above:

```
import matplotlib.pyplot as plt
import numpy as np
import mplstereonet
import matplotlib.image as image

#UTF-8 characters don't seem to work in the normal pyplot backend
plt.switch_backend("gtk3cairo")

fig = plt.figure()
ax = fig.add_subplot(111, projection='stereonet')

arrows = [[120, 30, 120, 30, "sin"],
          [160, 50, 160, 50, "dex"]]

for arrow in arrows:
    strike = arrow[0] - 90
    ax.plane(strike, arrow[1], color="#000000")
    ax.line(arrow[3], arrow[2], color="#ff0000")

    x, y = mplstereonet.line(arrow[3], arrow[2])
    ang = np.degrees(np.arctan2(x, y))[0] * (-1)
    gap = 0.08
    gap_x = gap * np.sin(ang)
    gap_y = gap * np.cos(ang)

    if arrow[4] == "dex":
        ax.text(x - gap_x, y - gap_y, "⇀", size=30, rotation=ang,
                horizontalalignment="center", verticalalignment="center")
        ax.text(x + gap_x, y + gap_y, "↽", size=30, rotation=ang,
                horizontalalignment="center", verticalalignment="center")

    elif arrow[4] == "sin":
        ax.text(x - gap_x, y - gap_y, "↼", size=30, rotation=ang,
                horizontalalignment="center", verticalalignment="center")
        ax.text(x + gap_x, y + gap_y, "⇁", size=30, rotation=ang,
                horizontalalignment="center", verticalalignment="center")

plt.show()
```

**Comment by efiring** [comment]
Having the ability to make nice shear arrows would be good, but I don't think it belongs in Quiver.  The functionality is much closer to the FancyArrow and Annotation familes.

**Comment by tobias47n9e** [comment]
Thanks for accepting the feature request! FancyArrow and Annotate would be just as good.

**Comment by ksunden** [comment]
FancyArrow now supports the `shape=["full"|"left"|"right"]`

**Comment by QuLogic** [comment]
In fact, I think that parameter has always existed.
