### ISSUE TITLE
Docs: low dpi defaults

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#5097]
The docs are build with only 80dpi, even lower than the already low mpl default of 90. I would propose to increase it to 100 dpi, especially to make the what new page nicer. In the future, matplotlib could use nicer looking examples on the whats new page.

**Comment by tacaswell** [comment]
Can you put in a pr to make this change? We are doing to rebuild the docs to go with the release.

How much is this going to increase the size of our already very heavy website?

**Comment by efiring** [comment]
Please reopen if this still needs attention.
