### ISSUE TITLE
wx: Recapturing the mouse in the same window? especially on Linux

### ISSUE THREAD

**Issue by newville** [matplotlib/matplotlib#5101]
I get frequent errors from the wx backend on Linux like this

```
  File "/usr/lib64/python2.7/site-packages/matplotlib-1.5.dev1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_wx.py", line 1138, in _onLeftButtonDown
    self.CaptureMouse()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 10638, in CaptureMouse
    return _core_.Window_CaptureMouse(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!wxMouseCapture::IsInCaptureStack(this)" failed at ./src/common/wincmn.cpp(3271) in CaptureMouse(): Recapturing the mouse in the same window?
```

when using the MPL API, though I never see it in pylab code.

I believe that checking `self.HasCapture()` is simply failing on Linux.   I also believe that the failure to `Capture the Mouse` is not critical, that that simply using 

```python
        try:
            self.CaptureMouse()
        except wx._core.PyAssertionError:
            pass
```

is sufficient for responsive wx interaction.

**Comment by tacaswell** [comment]
I am somewhat perplexed that you only see this when using the OO API and not with `pylab` (which just imports `pyplot` which is implemented in terms of the OO API).

**Comment by newville** [comment]
@tacaswell -- yes, I was pretty confused by that too.   The real problem was in my client code (wxmplot) which was doing too many ReleaseMouse().   Sorry for the noise.
