### ISSUE TITLE
__version__ not filled for master

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#5113]
do you have a policy for not filling in __version__ with a dev or RCx version string?
I'm running master and it has this in `__version__`:
```python
'0+unknown'
```
I'm asking because cartopy relies on this version string to be a correct version string and larger-equal 1.2.

**Comment by efiring** [comment]
It's not a policy, it's a new glitch of some sort.  I can reproduce it, but this is the first time I have seen it.

**Comment by tacaswell** [comment]
We just switched to using versioneer, how did you install mpl?

**Comment by efiring** [comment]
`python setup.py install` in a conda environment on OS X and in a virtualenv on Linux

**Comment by tacaswell** [comment]
you might need to do a `python setup.py build` step first.

**Comment by tacaswell** [comment]
attn @pelson

**Comment by michaelaye** [comment]
Same here: python setup.py install inside conda 3.4 environment on OSX.

**Comment by tacaswell** [comment]
also `python setup.py develop`

**Comment by efiring** [comment]
But I don't want develop mode--I don't trust it for a package as complicated as mpl, especially when I am using the same source directory for OS X and linux.

**Comment by tacaswell** [comment]
ok, so the version works in develop mode (either `setup.py develop` `pip install -e`), does not work with `python setup.py build && python setup.py install` or `pip install /path/to/mpl`, the packages on the tacaswell anaconda channel are also wrong, but the conda package on `conda-forge` are right.

**Comment by michaelaye** [comment]
If the `... build` method does not work, does that mean that the `conda-forge` thing builts itself in `develop` mode? Otherwise, how can it be?

**Comment by michaelaye** [comment]
I can confirm that python setup.py develop works on Linux as well.

**Comment by tacaswell** [comment]
Something is not set up right with our versioneer installation. It is supposed, on `python setup.py build` replace `_version.py` with a shorter file with.

Fix on the way.
