### ISSUE TITLE
RegularPolygon does not close path if fill=False

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#5119]
The edge path of the `RegularPolygon` does not get closed properly if `fill=False`:

```{python}
from matplotlib.patches import RegularPolygon
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.set_aspect('equal')

poly = RegularPolygon(
    xy=(0, 0),
    radius=10,
    numVertices=6,
    fill=False,
    linewidth=5,
)

ax.add_artist(poly)
ax.set_xlim(-11, 11)
ax.set_ylim(-11, 11)
fig.savefig('test_poly.pdf')
```

results in:
![test_poly](https://cloud.githubusercontent.com/assets/5488440/10019041/4ae4fd04-613b-11e5-83ae-f2747ce49229.png)

While the edgepath with `fill=True` is properly closed:
![test_poly](https://cloud.githubusercontent.com/assets/5488440/10019062/68664252-613b-11e5-9df1-c175411243a8.png)

**Comment by tacaswell** [comment]
What version of mpl?

**Comment by MaxNoe** [comment]
matplotlib 1.4.3 from an anaconda3 using python3 on arch linux.

**Comment by tacaswell** [comment]
can you try installing the rc from the `conda-forge` channel?

I can not reproduce this on currentish master

![so](https://cloud.githubusercontent.com/assets/199813/10020313/366b58a8-6110-11e5-82d7-43433edf0d89.png)

**Comment by MaxNoe** [comment]
Yep, it works with the new version!

**Comment by tacaswell** [comment]
My favorite kind of bugs, the ones we have already fixed!

**Comment by MaxNoe** [comment]
Any release date for mpl 1.5?

**Comment by tacaswell** [comment]
At risk of being flip, when it is done. We are a volunteer project so
estimating development time is hard.

**Comment by MaxNoe** [comment]
I know, and I appreciate you awesome work a lot! The fact that there are builds already in anaconda let me thought, that tour in the final steps of releasing a new version ;)

**Comment by tacaswell** [comment]
Sorry, i can be cranky first thing in the morning.  There will definitely
be an rc2 but given the feed back we have gotten so far, i am optimistic we
won't need an rc3.
