### ISSUE TITLE
custom axis scale doesn't work in 1.4.3

### ISSUE THREAD

**Issue by wiso** [matplotlib/matplotlib#5120]
If I execute this example:

http://matplotlib.org/examples/api/custom_scale_example.html

I get a straight line with matplotlib 1.4.3 instead of the one shown in the example.

Seems the same as https://github.com/matplotlib/matplotlib/issues/1844/, which should be closed.

**Comment by tacaswell** [comment]
The figure is generated from the 1.4.3 source so it worked when the docs were built (and still seems to be working on current master http://matplotlib.org/devdocs/examples/api/custom_scale_example.html).

I checked with a clean install from conda and it works correctly.
