### ISSUE TITLE
ENH: Better default font

### ISSUE THREAD

**Issue by toddrjen** [matplotlib/matplotlib#5128]
As part of the general style overhaul, might it be a good idea to look into a better default font?  The default matplotlib font, Bitstream Vera, only has a very limited set of characters.  In additional to lacking support for non-Latin alphabets, it also lacks a lot of characters that are important in scientific and numerical work, such as greek letters and mathematical symbols (for example you can't do "μs" in the default font if you want to abbreviate "microsecond").  This seems to be a pretty major omission.  

If we want to keep things pretty similar, the [DejaVu](http://dejavu-fonts.org/wiki/Main_Page) font family is mostly the same as Bitsream, but has a lot more characters.  Further, it is under a similarly liberal license.

If you want to search further afield, there are also a lot of newer fonts under liberal licenses that could be used.

**Comment by jenshnielsen** [comment]
Related to #4636

**Comment by mdboom** [comment]
:+1:

**Comment by zblz** [comment]
Related to this, and #4636 (or the PR that replaces it to ad DejaVu), I think it is necessary to have a default that has the same font for text and mathtext. The default right now is Vera for text and CM for mathtext, which is... not ideal.

**Comment by zblz** [comment]
#5214, which sets DejaVu as default font for regular and math text, has been merged.
