### ISSUE TITLE
ENH: Update the color spec parser to accept RGBA hex string values

### ISSUE THREAD

**Issue by Jul3k** [matplotlib/matplotlib#5137]
Currently the color spec parser does only check for RGB hex string color values in the form of `#FFFFFF`. If the user wants to pass RGBA values the color must be presented as a 4-tuple. For better user accesibility the parser could also accept color values in RGBA hex string format `#FFFFFFAA` directly, makeing the following code possible:

```
plt.rcParams['axes.color_cycle'][0] = "#FFFFFFAA"
```

**Comment by efiring** [comment]
I think this is closed by #6382.
