### ISSUE TITLE
Python [Error 17]No usable Temporary file name found

### ISSUE THREAD

**Issue by yogi86** [matplotlib/matplotlib#5145]
I developed a tool in Python 2.7.8 and packaged it using "py2exe". When I run the tool I get the following error:

Traceback (most recent call last): 
  File "application_gui.py", line 2, in <module>
  File "modules\Application.pyc", line 13, in <module>
  File "modules\Base.pyc", line 15, in <module>
  File "matplotlib__init__.pyc", line 764, in <module>
  File "matplotlib__init__.pyc", line 682, in rc_params 
  File "matplotlib__init__.pyc", line 595, in matplotlib_fname 
  File "matplotlib__init__.pyc", line 248, in wrapper 
  File "matplotlib__init__.pyc", line 470, in _get_configdir 
  File "matplotlib__init__.pyc", line 176, in _is_writable_dir 
  File "tempfile.pyc", line 462, in NamedTemporaryFile 
  File "tempfile.pyc", line 251, in _mkstemp_inner 
IOError: [Errno 17] No usable temporary file name found 
I am using matplotlib 1.4.3. 
It runs perfectly before packaging but the error is found to occur only after packaging. can anybody solve this issue or provide any information as I did not find anywhere.

**Comment by jkseppan** [comment]
Doesn't sound like a matplotlib issue. Possibly py2exe is making tempfile.NamedTemporaryFile not work, or something about your tool is affecting it. I recommend you make a [SSCCE](http://sscce.org/) and ask on whatever help channels there are for py2exe.

**Comment by yogi86** [comment]
Yes I would like to do it. 
I actually put a log in tempfile.py to check to see if matplotlib is using it or not and found out that it is using "tempfile.py" to create temporary files in  ".matplotlibrc" folder that is present in "%APPDATA% folder. So, I have strong feeling that it is due to permissions error. Do you think it is due to permissions?

**Comment by yogi86** [comment]
Okay,  I think I resolved the issue. It's not the problem with py2exe. It's the problem with "matplotlib". This is because, "matplotlib" is not able to create the folder called ".maplotlib" in the USERS directory of the windows system as it doesn't have enough permissions and this error pops up in this case. It would be nice if it searches for a couple of places before it finally throws this error.

**Comment by jkseppan** [comment]
There is already logic in `__init__.py` to check if the configuration directory is writable, and make a temporary directory otherwise. Is py2exe interfering with that somehow? In any case, you can set `MPLCONFIGDIR` to some suitable directory.

**Comment by yogi86** [comment]
Do I need to make any script to make it configurable when I package my script if I use MPLCONFIGDIR. I have seen this option but not sure how to use it when I am packaging.

**Comment by anntzer** [comment]
py2exe is not supported anymore (or rather, only supports too-old-versions of python) since https://github.com/matplotlib/matplotlib/pull/12043.
