### ISSUE TITLE
.whl package for Python 3.5

### ISSUE THREAD

**Issue by matysek** [matplotlib/matplotlib#5155]
For PyInstaller project we run some matplotlib tests and we would like to run PyInstaller tests on Windows with Python 3.5.

Could it be possible to create a wheel package for Python 3.5?

**Comment by tacaswell** [comment]
attn @cgohlke @matthew-brett

**Comment by matthew-brett** [comment]
Thomas - is Matplotlib 1.4.3 compatible with Python 3.5?

**Comment by tacaswell** [comment]
I believe so.  Continuum has a py3.5/v1.4.3 build up for linux.

Didn't you also build v1.4.3 py3.5 wheels for mac?

**Comment by matthew-brett** [comment]
Not yet - but I'll give it a go.

**Comment by matthew-brett** [comment]
Ok - it built fine, failed a couple of tests due to problems with mock - I've uploaded it to pypi now.

**Comment by cgohlke** [comment]
`matplotlib-1.4.3-cp35-none-win` wheels are at http://www.lfd.uci.edu/~gohlke/pythonlibs/#matplotlib
