### ISSUE TITLE
mpl.rcParams["lines.markeredgewidth"] = 0 removes markers in lines?

### ISSUE THREAD

**Issue by JanSchulz** [matplotlib/matplotlib#5156]
I have the problem that after importing seaborn, lines with markers do not show markers anymore.

The following will first output a plot with a blue line and three markers (the two on the ends are barely visible, but the one in the middle is clearly there), but after importing seaborn, the markers are not anymore visible.
```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot([1,2,3], marker="o")
# marker visible on the blue line
# -- next cell
import seaborn as sns
plt.plot([1,2,3], marker="o")
# No marker shown
```

 I tracked that down to this diff in `mpl.rcParams`

```diff
 lines.marker: None
-lines.markeredgewidth: 0.5
-lines.markersize: 6.0
-lines.solid_capstyle: projecting
+lines.markeredgewidth: 0.0
+lines.markersize: 7.0
+lines.solid_capstyle: round
 lines.solid_joinstyle: round
```

Setting `lines.markeredgewidth` to 1 will again show the marker.

```python
mpl.rcParams["lines.markeredgewidth"] = 1
plt.plot([1,2,3], marker="o")
# marker shown again
```

I tried to reproduce it on try.jupyter.org with the python2 kernel, but couldn't, despite the same mpl version (`matplotlib.__version__ == '1.4.3'`). My system is py2.7, win7, conda (matplotlib + seaborn updated to latest, but pandas/numpy a little older due to "never change a running simulation"...).

**Comment by JanSchulz** [comment]
Another interesting observation:

```
# Shows a marker
>>> mpl.rcParams["lines.markeredgewidth"] = 0.003497
>>> plt.plot([1,2,3], marker="o")
[<matplotlib.lines.Line2D object at 0x000000001A8D76A0>]
>>> plt.show()
#does not show a marker
>>> mpl.rcParams["lines.markeredgewidth"] = 0.00346
>>> plt.plot([1,2,3], marker="o")
[<matplotlib.lines.Line2D object at 0x000000001A63BD30>]
>>> plt.show()
```

**Comment by tacaswell** [comment]
This sounds like a bug that was fixed between 1.4.2 and 1.4.3.

See https://github.com/matplotlib/matplotlib/pull/3687 and https://github.com/matplotlib/matplotlib/pull/3699 for the fixes

**Comment by tacaswell** [comment]
I can not reproduce in a clean conda env 

```
09:53 $ conda create -p mew_test python matplotlib seaborn ipython
```


```
(mew_test) ✔ /tmp 
09:54 $ ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import seaborn as sns

In [2]: import matplotlib.pyplot as plt

In [3]: %matplotlib qt

In [4]: plt.plot([1,2,3], marker="o")
Out[4]: [<matplotlib.lines.Line2D at 0x7fddaab9f210>]

In [6]: import matplotlib     

In [7]: matplotlib.__version__
Out[7]: '1.4.3'

In [8]: sns.__version__
Out[8]: '0.6.0'

In [9]: 


```

![so](https://cloud.githubusercontent.com/assets/199813/10166064/5942ca2a-6690-11e5-8e46-3943b6ce0e79.png)

**Comment by JanSchulz** [comment]
Fun, I can't reproduce it in such a newly created environment either :-( I will try to find the root cause of this, but somehow I have the feeling that this won't be easy :-(

**Comment by JanSchulz** [comment]
Ok, I can't recreate the error even when I rebuild the conda env from an environment.yml exported in the problematic env :-( Not sure what to do here, probably best to close the issue :-(

**Comment by WeatherGod** [comment]
Gotta love Heisen-bugs!  Feel free to reopen this if you can reproduce it again.

**Comment by tacaswell** [comment]
My guess on this is that your env started as a 1.4.0, got upgraded, and
there was an old pyc hanging around.

**Comment by JanSchulz** [comment]
Looks like it: 
```
λ dir *_agg.*
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: E0FA-598A

 Verzeichnis von C:\portabel\miniconda\envs\monte-carlo_off\Lib\site-packages\matplotlib\backends

19.02.2015  18:59            21.106 backend_agg.py
19.02.2015  18:59            23.435 backend_agg.pyc
23.10.2014  19:59           319.488 _backend_agg.pyd
               3 Datei(en),        364.029 Bytes
               0 Verzeichnis(se), 361.723.437.056 Bytes frei
```
