### ISSUE TITLE
stop() method in matplotlib.backend_bases.TimerBase is dysfunctional

### ISSUE THREAD

**Issue by dafarr** [matplotlib/matplotlib#5163]
Tested in Ubuntu 14.04 with Python 2.7.6 and Debian unstable with Python 3.4.3. with Matplotlib default backend (TkAgg). Matplotlib loaded from distro repositories.

The following code should stop after 1 tick but instead continues printing ticks forever:

``` python
#!/usr/bin/env python
import matplotlib.pyplot as P
def fn():
  timer.stop()
  print("tick")
fig, ax = P.subplots()
timer = fig.canvas.new_timer(interval=1000)
timer.add_callback(fn)
timer.start()
P.show()
```

Workaround is to replace "timer.stop()" with
timer.single_shot = True
and that does stop the timer upon execution.

Documentation describing stop() method:
http://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.TimerBase

**Comment by dopplershift** [comment]
So the problem stems from the fact that Tk's underlying timers are, fundamentally, one-shot; we try to mimic repeating timer interface on top of this.

Is this example reflective of a use case you have? Because by returning `False` from the callback, it would no longer be called and the timer would be stopped.

**Comment by anddam** [comment]
Cannot reproduce on OS X 10.10.5 using matplotlib 1.4.3 from MacPorts and both python 2.7 and 3.4, the program prints "tick" once as expected and doesn't print anything more.

Commenting the stop() call periodically gives the "tick" output line.

**Comment by mdehoon** [comment]
I can reproduce this on Linux with matplotlib 1.5.dev1.

**Comment by tacaswell** [comment]
@mdehoon You got a linux box?

**Comment by mdehoon** [comment]
@tacaswell  We are running linux on our servers.

**Comment by tacaswell** [comment]
@mdehoon please excuse my poor attempt at humor.
