### ISSUE TITLE
"Data has no positive values"

### ISSUE THREAD

**Issue by lzkelley** [matplotlib/matplotlib#5165]

**Comment by ellisonbg** [comment]
Yeah, +1 on using yml for this

On Fri, Oct 2, 2015 at 10:26 AM, Luke <notifications@github.com> wrote:

> Closed #5165 <https://github.com/matplotlib/matplotlib/issues/5165>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/5165#event-425305179>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by tacaswell** [comment]
I am not super excited about issues being edited out of existence like this, @lzkelley Please don't it that again.

**Comment by lzkelley** [comment]
@tacaswell This was an accidentally opened issue (wasn't paying attention when the search for issues text-field switches to a create a new issue text-field).  Sorry, I should probably have edited the title to reflect that?  [Unfortunately there isn't a delete issue button](https://github.com/isaacs/github/issues/253).

**Comment by tacaswell** [comment]
Fair enough.
