### ISSUE TITLE
Error in boxplot, 1.5.0.rc2

### ISSUE THREAD

**Issue by thomas-haslwanter** [matplotlib/matplotlib#5173]
In RC2 of matplotlib 1.5.0, outliers in boxplots are connected by lines (see attached image). This should not be the case.
![error_boxplot](https://cloud.githubusercontent.com/assets/1530437/10263808/c5c6465a-69fa-11e5-8b98-9c6bda25802b.png)

**Comment by tacaswell** [comment]
Can you include the code you used to generate that as well?

**Comment by thomas-haslwanter** [comment]
import numpy as np
import matplotlib.pylab as plt
np.random.seed(1234)
data = np.random.randn(1000)
plt.boxplot(data)

**Comment by tacaswell** [comment]
Also, do the colors look right?

**Comment by thomas-haslwanter** [comment]
The colors look right. 
What I cannot judge: the lines from the error-bars to the box should be dashed, not solid.
And personally, I would prefer a slightly thicker default width.
Thanks for the super-quick responses!

**Comment by QuLogic** [comment]
FYI:
```
94d044e5fb453b54fd89cabc8a5387cae589766e is the first bad commit
commit 94d044e5fb453b54fd89cabc8a5387cae589766e
Author: Olga Botvinnik <olga.botvinnik@gmail.com>
Date:   Sat Jan 4 12:58:30 2014 -0800

    Added rcParams for removing specific spines

... + a lot of other things
```

**Comment by tacaswell** [comment]
@QuLogic Thank you for doing the bisect on this.  Starting from that this ended up being a 5 minute fix :smile: :beers:

**Comment by QuLogic** [comment]
Oh yes, that certainly was a simple fix!
