### ISSUE TITLE
"prop_cycle" or "prop_cycler" in ver 1.5.0.rc2?

### ISSUE THREAD

**Issue by thomas-haslwanter** [matplotlib/matplotlib#5175]
The docu for the API-changes in 1.5.0 claims that
   "axes.color_cycle"
will be replaced by
   "axes.prop_cycle"
However, the implementation in 1.5.0.rc2 uses 
   "axes.prop_cycler"

I don't know which version would be preferable.

**Comment by tacaswell** [comment]
Trust the code!

attn @WeatherGod

**Comment by WeatherGod** [comment]
Oh, crap. It was supposed to be prop_cycle. So, which do we want to fix?

**Comment by tacaswell** [comment]
If we fix the code, we need to reach out pandas ASAP @TomAugspurger

**Comment by TomAugspurger** [comment]
I'll follow along here. We're doing our release on Friday.

Not that it should affect anything but I look for `prop_cycle`. I do prefer `prop_cycle` to `prop_cycler`.

**Comment by WeatherGod** [comment]
`git grep axes.prop_cycler` yields no matches. Where are you seeing
`axes.prop_cycler` in the code implementation? Note that there is the
`Axes._get_lines.prop_cycler` and such, but those are considered private
and should not be accessed outside of matplotlib.

**Comment by thomas-haslwanter** [comment]
As you have stated correctly, I have only seen it in the "Axes._get_lines_prop_cycler".
This was not my own code. But I thought I'd report it anyway.

**Comment by WeatherGod** [comment]
Ah, I see. Well, the rcparam names do not have to align with the names used in the code. So, I'll close this issue. Do let us know if you see anything else that seems inconsistent to you, though.
