### ISSUE TITLE
pyplot.plot() doesn't respect the selected color

### ISSUE THREAD

**Issue by Gabriel-p** [matplotlib/matplotlib#5197]
This comes from a question made here: http://stackoverflow.com/questions/32956419/weird-matplotlib-color-issue-when-plotting-line

I'm running Python v2.7.6 and matplotlib v1.4.3. I have a simple plot:

    import matplotlib.pyplot as plt
    import numpy as np
    x, y = np.random.random(50), np.random.random(50)
    plt.plot(x, y, c='red', ls='-', lw=1., label='a', zorder=2)
    plt.show()

Notice that the color is supposed to be red as per `c='red'`. What I get instead is:

[![enter image description here][1]][1]

If I use the full name of the argument `color='red'`, the line is red as it should. If I remove *any* of the arguments after `c='red'`, e.g.:

    plt.plot(x, y, c='red', ls='-', lw=1., label='a')
    plt.plot(x, y, c='red', ls='-', lw=1., zorder=2)
    plt.plot(x, y, c='red', ls='-', label='a', zorder=2)
    plt.plot(x, y, c='red', lw=1., label='a', zorder=2)

the plotted line is **also** red. Using:

    plt.plot(x, y, c='r', ls='-', lw=1., label='a', zorder=2)

(i.e.: `c='r'` instead of `c='red'`) has no effect on my system, I still get the blue line.

  [1]: http://i.stack.imgur.com/JkPa7.png

**Comment by tacaswell** [comment]
I bet on python3 you get a red line half of the time.

What is going on here is that in the in the logic that plots checks to see if the the key `'color'` is in the property dict generated by the arg parsing or in the kwangs, and if it is not found adds a key `'color'` with the value of the next color in the color cycle (if you make multiple calls to plot it _should_ color cycle properly).  The reason that it works dependent on the other kwargs is that the the two style dictionaries mentioned above are applied to the created line artist in two passes, the internally generated one is passed to the `LIne2D` init and the user passed in kwargs is used to directly set properties on the line object.  As the user dict now has both a `'c'` key and a `'color'` key (and `Line2D` has both `set_c` and `set_color` methods) the final color is dependent on the iteration order of the dictionary.  In legacy python this is dependent on the history of the keys added to the dictionary, but is other wise deterministic (in python 3.3+ dictionary iteration order is random process-to-process).

The simplest solution is to just use the full kwarg.

The solution on our side is to do better validation on the keys passed into kwargs.

Probably should also deprecate `set_c`.

**Comment by Gabriel-p** [comment]
Thanks for the lengthy explanation @tacaswell. Is it ok if I answer my own question at stackoverflow simply with "it's a known issue" and point here? I mean, can I call this a "known issue"?

**Comment by tacaswell** [comment]
That sounds fine.   

Also, this is fixed on master and the fix will be released in 1.5.0 via  308fae57e3b84407e963e2ef6fb76a794649e7b4

I am going to close this as we do have a fix for this in the code base already.

**Comment by tacaswell** [comment]
Fix: https://github.com/matplotlib/matplotlib/pull/4198 

dups: https://github.com/matplotlib/matplotlib/issues/4162, https://github.com/matplotlib/matplotlib/issues/4157
