### ISSUE TITLE
use nose attributes to mark network tests

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#5198]
see http://anonscm.debian.org/cgit/reportbug/reportbug.git/tree/test/test_urlutils.py#n10,  http://anonscm.debian.org/cgit/reportbug/reportbug.git/tree/Makefile#n12

We are using nose under the hood so this should 'just work'.

**Comment by mdboom** [comment]
Astropy has a test hook that will fail any test that goes out to the network that isn't otherwise flagged.  It uses py.test, not nose, but something like that might be handy.  You can also find these things by unplugging the network, but that's not easy to remember to do...
