### ISSUE TITLE
plot color yields inconsistent results

### ISSUE THREAD

**Issue by lukasm91** [matplotlib/matplotlib#5199]
When using color in plt.plot(...), this may yield to inconsistent result. I would like to get this plot:

![result](http://i.imgur.com/9eAZFet.png)

Using python 3.5 and matplotlib 1.4.3, and the code below, I sometimes get the image above, but sometimes I only get a blue color (rgb 0 0 255). When using color instead of c, the results are as expected as far as I tested.

Some further information: http://stackoverflow.com/questions/32964051/inconsistent-results-using-matplotlib

	import matplotlib
	import matplotlib.pyplot as plt
	import numpy as np

	fig, ax = plt.subplots()

	cmap = plt.get_cmap('cubehelix')

	minval = 17
	maxval = 25
	bounds = np.arange(minval, maxval+1)

	mynorm = matplotlib.colors.Normalize(vmin = minval, vmax = maxval)
	sm = matplotlib.cm.ScalarMappable(norm=mynorm, cmap=cmap)

	color = sm.to_rgba(20)
	ax.plot([0, 100], [0, 100], c=color, lw=2) # ERROR
	#ax.plot([0, 100], [0, 100], color=color, lw=2) # OK

	ax2 = fig.add_axes([0.90, 0.1, 0.03, 0.8])
	cb = matplotlib.colorbar.ColorbarBase(ax2, cmap=cmap, norm=mynorm, spacing='proportional', ticks=bounds, boundaries=bounds, format='%1i')

	plt.show()

**Comment by jenshnielsen** [comment]
I think this is the same issue as #4162, #4157 and #5197 which has been fixed. Please ping to have this reopened if you disagree
