### ISSUE TITLE
ValueError when passing numpy array as edgecolors argument to scatter

### ISSUE THREAD

**Issue by jaminsore** [matplotlib/matplotlib#5211]
import numpy as np
    import matplotlib.pyplot as plt
    edgecolors = np.r_[['b'] * 5, ['r'] * 5]  
    x, y = np.random.randn(10), np.random.randn(10)

    plt.scatter(x, y, edgecolors=edgecolors, c='none')

raises 

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

But changing the call to `plt.scatter()` to 

    plt.scatter(x, y, edgecolors=edgecolors.tolist(), c='none')

Works as expected.  This error is occurring inside a `try`, `except` block so it looks it should be an easy fix.

**Comment by WeatherGod** [comment]
This is fixed in master.

**Comment by jaminsore** [comment]
Ok, I will close this, then.  Thanks.
