### ISSUE TITLE
Figure should be a contextmanager?

### ISSUE THREAD

**Issue by shoyer** [matplotlib/matplotlib#5218]
This would provide a clean way to automatically close figures after you're done with them. 

Here's an example of what the functionality would look like:
```python
import contextlib 

# dummy implementation
@contextlib.contextmanager
def figure_context(*args, **kwargs):
    fig = plt.figure(*args, **kwargs)
    yield fig
    plt.close(fig)

# example usage
with figure_context():
    plt.plot(range(5))
```

In reality, we would implement this using the `__enter__` and `__exit__` methods on `Figure`, which would make the context manager behavior entirely optional.

**Comment by tacaswell** [comment]
Interesting idea.  My knee jerk reaction is that the ussage should be

```python
with figure_context() as fig:
    ax_list = fig.subplots()
    ax_list[0].plot(range(5))
```

(there is an open PR which moves the `subplots` logic over to the `Figure` class.

**Comment by shoyer** [comment]
@tacaswell Yes, the context manager (even my example) would support either usage. Functions in the pyplot API, of course, automatically draw themselves on the current figure.

**Comment by WeatherGod** [comment]
Just taking this a step further, would it make sense to have a class method
"Figure.open()"?

**Comment by WeatherGod** [comment]
I should note, though, that I am a little unsure of the use-case here. If I
am going to show() the figure(s), then they get closed anyway. Also, when
having multiple figures, don't we typically group the plotting code with
the relevant figure? Is code that go with this approach cleaner when doing
multiple figures?

**Comment by efiring** [comment]
It seems like the only thing this would be good for is the case where you plot a figure, save it, plot another, save it, etc.  And in this case, it is only saving the user from having to remember to close the figure.  It doesn't help for any interactive use, or screen display, correct?

**Comment by WeatherGod** [comment]
It would help to automatically close the figure if an exception gets thrown
during the plot-making process. I have had confusing situations
interatively where I finally call plt.show(), and I have a bunch of
incomplete or blank figure windows come up.

**Comment by shoyer** [comment]
> It seems like the only thing this would be good for is the case where you plot a figure, save it, plot another, save it, etc. And in this case, it is only saving the user from having to remember to close the figure. It doesn't help for any interactive use, or screen display, correct?

Yes, exactly. My actual use case is writing unit tests, which looks pretty similar.

**Comment by efiring** [comment]
Given how restrictive the use case is, and how little it saves, I do not support adding this to the mpl API.

**Comment by shoyer** [comment]
I agree that there are limited returns here, but on the other hand it's not much of an API expansion, either. This really is an simple as adding two double underscore methods to `Figure`:
```
def __enter__(self):
    return self

def __exit__(self, type, value, traceback):
    plt.close(self)
```

Now `plt.figure()` just works in a `with` statement.

**Comment by tacaswell** [comment]
Having the `Figure` know about `pyplot` is a major API change, currently all of the import go the other way.

**Comment by dopplershift** [comment]
Given @tacaswell's point, it would make much more sense to me to add some way of doing this to `pyplot` API rather than `Figure`. Definite :-1: on adding `pyplot` to `Figure`.

**Comment by shoyer** [comment]
Yep, agreed. Guess I'll be keeping my context manager around.

**Comment by tacaswell** [comment]
There is a plan to make a side repo for fancy trial mpl higher order
programming things, i will ping you when i get that stood up.

**Comment by CMCDragonkai** [comment]
This would be quite useful in jupyter, where figures tend to leak alot.

**Comment by maartenbreddels** [comment]
I needed this for [ipyvolume](https://github.com/maartenbreddels/ipyvolume), so was curious if matplotlib had this to be somewhat api compatible. I've decided to make ipyvolume's Figure 'know' about it's pylab API since it's the most convenient.

The usage is obvious from the unittest:
```python
def test_context():
    f1 = ipv.figure(1)
    f2 = ipv.figure(2)
    f3 = ipv.figure(2)

    assert ipv.gcf() is f3
    with f2:
        assert ipv.gcf() is f2
    assert ipv.gcf() is f3
    # test nested
    with f2:
        assert ipv.gcf() is f2
        with f1:
            assert ipv.gcf() is f1
        assert ipv.gcf() is f2
    assert ipv.gcf() is f3
```

Or an example:
```python
f1 = ipv.figure(1)
f2 = ipv.figure(2)
with f1:
  ipv.scatter(x, y, z)
assert ipv.gcf() is f2
```

Maybe it is useful for the discussion, see the relevant commit: https://github.com/maartenbreddels/ipyvolume/commit/ad7eca3a994fad9532a0c3eb52223c10eb4ee586

**Comment by timhoffm** [comment]
@maartenbreddels Your use-case of the context is a bit different from this issue.

This issue discussed to create a figure for the duration of the context and close it at the end.

Your code uses the context to switch the current figure, but neither create nor close it. I don't know the exact workings of ipyvolume, but for matplotlib I don't see a need for this. The state-based pyplot API ("current"-semantics) is a legacy inherited from Matlab and a way to handle multiple figures with pure functions. The context manager would be a way of making state changes easier. However, with an object-oriented API, there is no need for a global state at all.

In matplotlib, I would write your example like this:
~~~
f1 = plt.figure()
f2 = plt.figure()
f1.gca().scatter(x, y, z)
# do something with f2
~~~

So, if you have an object-oriented API in ipyvolume, I wouldn't add a state-changing context. That'd only proivide a possibility for a second-best solution.

**Comment by maartenbreddels** [comment]
Ok, I misunderstood the use of the context, since I almost exclusively use the pyplot/pylab API.
ipyvolume is mostly used in the notebook, so the state-based interface is I think more useful. Behind the scenes it's OO (widgets), but I consider that an implementation detail.

**Comment by timhoffm** [comment]
Ok. Still I don't see a benefit in the state based approach. Your are storing references in `f1, f2` anyway. Since you have control on the API, you could implement functions on the figure.

~~~
f1 = ipv.figure(1)
f2 = ipv.figure(2)
f1.scatter(x, y, z)
~~~

IMO "scatter-plot to f1" is more straight forward "set the context to f1 and then scatter-plot to the current figure". But just my 2cents. I don't want to go into an API discussion on your library.

**Comment by tacaswell** [comment]
One down side of the OO approach is that it makes the figure / axes serve as both the draw container and the primary namespace of your plotting methods.  This can make it awkward for mixing 'built in' plotting with user defined plotting.

I think the biggest challenge to the notion of 'current-*' is if the user wants to write functions that are going to add marks to more than one canvas, ex plot a scatter along with the 1D histograms in the x and y directions or two views of the same data set with different iso levels / renderings.  The signature for that function would have to look something like:

```python
def my_multi_plotter(ax1, ax2, *data, **style):
    ...
```

Probably the best API is one of functions that take in a target, some data, and some style that return the artist/glyph objects created (the things that users can mutate to change the plot).  You can put the global state back on top of those functions as a convenience  with a decorator (which would also provide an easy path for third-party functions to opt-in as well), but I am still noodling over exactly what that should look like (and have been for a while now).

This also seems relevant: https://docs.python.org/3.7/library/contextvars.html

**Comment by maartenbreddels** [comment]
It goes a bit off topic, but an interesting discussion.
Around my I saw most people using the non-OO/state based API, and I am probably also influenced by bqplot, which takes a similar approach.
Also, I've been mostly using matplotlib and ipyvolume in the notebook, and there it doesn't really matter.
However, not that I'm using it as part of a library that keeps a reference to a Figure, it cannot expect it to be the current figure and the OO approach would make more sense. Until that time, I'll use figure as a context manager to set and restore the context/state.

**Comment by shouldsee** [comment]
Is this happening anywhere? Can I register callback for figure using "with"?

```python2
with figure_context(file='my-scatter.png') as fc:
    ax_list = fig.subplots()
    ax_list[0].plot(range(5))
```

**Comment by timhoffm** [comment]
There is no support from within matplotib for a figure context manager. You could write your own one. 

However the benefit of a figure context is not completely clear to me. The only advantage I see would be trying to manage the current figure and be able to use the pyplot API throughout (but that could still be broken by an unwary user). Your example uses the OOP approach. In that case the benefit seems minimal - just saving to write the savefig command. It comes at the additional cost that the figure creation is hidden, so that you would have to pass the figure parameters through the context. I would rather write this as:

~~~
fig, ax_list = plt.subplots()
ax_list[0].plot(range(5))
fig.savefig('my-line.png')
~~~

**Comment by cifkao** [comment]
How about this one-liner?

```python
with contextlib.closing(plt.figure()) as fig:
   ...

**Comment by tacaswell** [comment]
An interesting development in this space is that napar uses a context manager to manage starting / stopping the GUI event loop (rather than `plt.show(block=True)`) which is very interesting.

**Comment by sorenwacker** [comment]
I have a related problem. I have an application that runs on a flask server, that can create and serve plots. The problem is that the plots get confused when created simultaneously.

**Comment by tacaswell** [comment]
@sorenwacker You probably do not want to be using pyplot in your application as it brings in a bunch of global state.  If you use the explicit API I suspect most of your problems will be solved.

**Comment by sorenwacker** [comment]
I am using mostly seaborn to create rather complex plots. Not sure if it is at all possible to use that without pyplot.

**Comment by tacaswell** [comment]
I am not a regular seaborn user, but I am pretty sure you can pass `Axes` and/or `Figure` objects into most of that API.

**Comment by sorenwacker** [comment]
Ok, I know what you mean. I will try that. Cheers!
________________________________
