### ISSUE TITLE
legend--plot handle association

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#5222]
(I'm posting this here since [mailing list](https://sourceforge.net/p/matplotlib/mailman/matplotlib-users/) seems dead.)

Given a [legend](http://matplotlib.org/api/legend_api.html), I'm trying to figure out which plot handles it references. Is this possible at all? The reverse would also be fine, i.e., given a plot handle (e.g., a line), find the legend(s) in which it is referenced.

**Comment by tacaswell** [comment]
The mailing list has moved to matplotlib-users@python.org

**Comment by tacaswell** [comment]
Also, there is a bug in SF's display code, that mailing list was active up until a few months ago when we switched to the python.org address.

**Comment by nschloe** [comment]
The sourceforge page is the first thing that comes up for me when googling "matplotlib mailing list", so it's probably worthwhile fixing it. Making sure the actual mailing list comes up first would definitely help.

**Comment by tacaswell** [comment]
We have announced it several times on all of our lists and have updated the
main front page.  Nabble and gmane also both point to the new list.

If you know how to do SEO, we would love the help!

**Comment by nschloe** [comment]
> If you know how to do SEO, we would love the help!

Links help. :) A good place to start would be the [README.rst](https://github.com/matplotlib/matplotlib/blob/master/README.rst). Shall I prepare a PR?

**Comment by tacaswell** [comment]
Yes, please put in links to the mailing list in any of the places you
looked expecting to find them, but didn't find them ;)

**Comment by anntzer** [comment]
The info you are looking for is the `.legendHandles` attribute of the legend object.

**Comment by nschloe** [comment]
@anntzer Thanks!
