### ISSUE TITLE
the offset of the scientific notation in xaxis stays at bottom when axis is set to top

### ISSUE THREAD

**Issue by pogam** [matplotlib/matplotlib#5238]
the power indicator of an xaxis set to top stays on the bottom axis

I have seen that for the yaxis you have a function ax.yaxis.set_offset_position('right'), but I could not find any equivalent for the xaxis.

here is an example of the problem.

`import matplotlib.pyplot as plt`
`import numpy as np`

`datay = np.arange(20)`

`datax = np.random.random(20) * 1.e-4`
`ax = plt.subplot(111)`
`ax.plot(datax,datay,c='k')`
`ax.ticklabel_format(axis='x', style='sci', scilimits=(-2,2))`

`data2x = np.random.random(20) * 1.e-4`
`bx = ax.twiny()`
`bx.plot(data2x,datay,c='r')`
`bx.ticklabel_format(axis='x', style='sci', scilimits=(-2,2))`

`plt.show()`

**Comment by WeatherGod** [comment]
confirmed. I could have sworn we saw this bug before and addressed it...

**Comment by tacaswell** [comment]
This might require some invasive re-factoring of Axis so tagged for 2.1, if I am wrong and we can do this gently enough can go for 2.0.1.

**Comment by petebachant** [comment]
Is there any workaround for this, e.g., using text? I can't seem to get similar text for the upper axis when using math text (the bottom is not LaTeX).

**Comment by beojan** [comment]
I'm still seeing this bug in 3.1.1 (latest master)

**Comment by jklymak** [comment]
Someone could take over #5243?

**Comment by beojan** [comment]
This isn't fully fixed. When a colorbar is drawn, the multiplier for the colorbar is drawn at the top right corner of the main axes.

**Comment by QuLogic** [comment]
That seems different and should be a new issue.
