### ISSUE TITLE
improving mpl docs and accessibility for API users

### ISSUE THREAD

**Issue by jdh2358** [matplotlib/matplotlib#524]
There was a recent discussion on the numpy mailing list about how to improve the accessibility of the docs and the gallery, particularly for API users who find the pylpot state-machine annoying.  Add your suggestions and gripes here.

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. What is the current state of documentation relative to the original prompt in 2011?

**Comment by tacaswell** [comment]
Better, but still in need of _lots_ of work.

#7205 is a tracking issue for fixing the docstrings

MEP12 (http://matplotlib.org/devel/MEP/MEP12.html) is guidelines for improving the examples #7206 is tracking some of this.

**Comment by anntzer** [comment]
I don't think keeping this open really helps anything (there are enough issues tracking docs improvements at that point...).  Feel free to reopen if you disagree.
