### ISSUE TITLE
Exported to PDF looks different in Mac's Preview and in Acrobat

### ISSUE THREAD

**Issue by josepablog** [matplotlib/matplotlib#5252]
I am having a lot of issues exporting as PDF.  For example, the resulting PDF shows in Preview, but not in Acrobat reader. This files illustrates the problem:

https://dl.dropboxusercontent.com/u/4474769/chap123_kc_gc_3_2.pdf

Additionally, both lines should have the same linewidth.  This only happens if I use a different format (like png).

**Comment by QuLogic** [comment]
Interestingly, the lines are the same width in pdf.js, but different widths in evince.

**Comment by WeatherGod** [comment]
The linewidth issue is weird, indeed. Which version of matplotlib? And we
would need the code that generated that result (even if it is just random
data). Also, which backend were you using? While most backends delegate
PDF-making to the PDF backend, a couple of them handles it themselves.

**Comment by tacaswell** [comment]
Can you provide a minimal example to generate the issue?  I suspect the difference is that dashed lines and solid lines go through different rendering paths.

attn @jkseppan

**Comment by jkseppan** [comment]
The linked file is from the pdf backend, but yes, we'll need the source code for the plot.

**Comment by QuLogic** [comment]
It's been almost 2 years and we haven't received any source code, so I'm closing this issue. @josepablog please re-open when you can provide the source code.
