### ISSUE TITLE
no ax_get_lines.style_cycle

### ISSUE THREAD

**Issue by jona-sassenhagen** [matplotlib/matplotlib#5254]
As pointed out by [this](http://stackoverflow.com/a/9276196/3461409) stackoverflow answer, matplotlib has a nice color_cycle method, but no equivalent way to set line styles. The poster proposes to add two lines to axes.py. This would IMO be helpful.

**Comment by jenshnielsen** [comment]
Matplotlib 1.5 will have the new prop-cycle Documented [here](https://github.com/matplotlib/matplotlib/blob/master/doc/users/whats_new.rst#added-axes-prop-cycle-key-to-rcparams) 

I think that should cover what is asked for

**Comment by jona-sassenhagen** [comment]
Oh nice. Closing.
