### ISSUE TITLE
Document $MATPLOTLIBRC

### ISSUE THREAD

**Issue by itoijala** [matplotlib/matplotlib#5265]
The [documentation](http://matplotlib.org/users/customizing.html) does not mention the very useful `MATPLOTLIBRC` environment variable.

The variable would be even more useful if the file did not have to be called `matplotlibrc`.

**Comment by jenshnielsen** [comment]
Do you have any specific need for more than one rc file? In most cases I would recommend using the style module to customise your plot. See http://matplotlib.org/users/style_sheets.html

**Comment by itoijala** [comment]
The idea is that when working on a publication with multiple people, the output should be the same for everyone. This requires the styles to be bundled with the scripts. A `matplotlibrc` in a user's home that is loaded would also cause problems. I think the easiest way to prevent that is to have our own rc file.

I guess setting `MPLCONFIGDIR` to a folder that has style files would also work, though it would require every script to set the style. Can a style file set the backend?

**Comment by jenshnielsen** [comment]
If you care about the backend I would explicitly set it in the script. ```matplotlib.use('QT4Agg')` or whatever. 

> I guess setting MPLCONFIGDIR to a folder that has style files would also work, though it would require > every script to set the style.
I would personally consider that a significant advantage. Rather than relying on a hidden setup behind the scenes you are making the style used explicit in the script. 

Also note that the rc file in the current directly should always overwrite the one in the homedir http://matplotlib.org/users/customizing.html this is of cause not enough if you have your plot scripts in multiple directories. 

All of this does not mean that we should not document the env variable. That should be clearly be documented.

**Comment by itoijala** [comment]
I use the pgf backend with a custom preamble and so the labels will not work without the rc file anyway. Therefore I like to keep the scripts as short as possible and remove the error of not setting the backend in one of them.

I also have multiple folders with scripts and want to use a single rc file.

I know that the rc file overrides the one in home. The problem is that without an rc file, for example if using a stylesheet instead, the one from home would be loaded.

I think there should be an option to put matplotlib into a reproducible mode where nothing is ever loaded from home. The question is where to put this option.
I would even go so far as to say that matplotlib should default to the fully reproducible mode, though that would not be backwards compatible and is probably an unpopular opinion.
It should be as easy as possible to publish the source to a publication that does the complete analysis and all the plots and builds the resulting document in a reproducible manner.

Anyway, the system is fine now as long as no one forgets to include an rc file that is found by matplotlib.

**Comment by tacaswell** [comment]
Pretty sure this is documented on master

**Comment by itoijala** [comment]
Doesn't look like it: https://github.com/matplotlib/matplotlib/blob/master/doc/users/customizing.rst#the-filematplotlibrc-file
At least that it the place I expected to find it.

**Comment by tacaswell** [comment]
Huh, I could have sworn I remembered a PR about this going by, never mind then.

**Comment by itoijala** [comment]
Would you be open to adding functionality to also specify the filename?
It could work like this: if `$MATPLOTLIBRC` is a file, use it, otherwise look for `$MATPLOTLIBRC/matplotlibrc`.
