### ISSUE TITLE
Add an rc file setting for the pad parameter of tight_layout

### ISSUE THREAD

**Issue by itoijala** [matplotlib/matplotlib#5266]
Currently the parameter defaults to `pad=1.08` with no way to change it from the rc file, for example when using `figure.autolayout`, which is then not so useful since the user has to call `tight_layout` anyway to set the padding.

**Comment by Uttam-Singhh** [comment]
Hello, Can I work on this?

**Comment by jklymak** [comment]
I actually don't think that would be a good idea.  Right now we are _planning_ to redo how layout engines work, and adding new state to the rcParams file would make that harder in my opinion.  See #19892

**Comment by jklymak** [comment]
BTW< thanks for being willing to help!  Perhaps there are other issues.  Feel free to drop in at https://gitter.im/matplotlib/matplotlib if you'd like to chat...

**Comment by Uttam-Singhh** [comment]
Oh ok! no problem

**Comment by rcomer** [comment]
I’m guessing this is now redundant as we have constrained layout, which does take its default padding from rcParams.  I also note that, as of #25395, use of tight layout is “mildly discouraged“.
