### ISSUE TITLE
implement `get_ticks_direction()`

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#5277]
Right now, one can find out all kinds of things about ticks, e.g., via

* `get_ticklabel_extents`
* `get_ticklabels`
* `get_ticklines`
* `get_ticklocs`
* `get_ticks_position`

What's missing from that list is a method that tells you about the ticks direction (in/out/inout).

**Comment by mdboom** [comment]
:+1: to the idea.

**Comment by tacaswell** [comment]
closed by #5290
