### ISSUE TITLE
Warnings in doc build

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5287]
These are warnings produced by the doc build.  These are not-trivial to fix and relatively benign, so I'm just documenting them for now rather than giving priority to fixing them.
- [ ] examples/images_contours_and_fields/streamplot_demo_masking

```
site-packages/numpy/ma/core.py:806: RuntimeWarning: invalid value encountered in greater_equal
  return umath.absolute(a) * self.tolerance >= umath.absolute(b)
```
- [ ]  users/colormapnorms

```
site-packages/matplotlib-1.5.0rc2_55.g95e2346-py2.7-linux-x86_64.egg/matplotlib/figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```

Lastly, there's lucky ipython/ipython#8888, but it seems @minrk @matthew-brett and other are on it.

**Comment by dstansby** [comment]
These seem to have gone away, and new ones appeared, so I've opened a new issue.
