### ISSUE TITLE
Pixelated fonts when plot saved as jpeg

### ISSUE THREAD

**Issue by cbreeden** [matplotlib/matplotlib#5302]
I have noticed that when you save figures as jpeg using the nbagg backend you will get pixelated fonts for labels and tickmarks.  It appears this has to do with giving PIL raw data with transparent regions when trying to save jpeg images.  This can be avoided with setting: rcParams['nbagg.transparent'] = False.

Is this behavior desired?  Perhaps there is a way we can assign default values that will be called for when you have a transparency in a figure and you are trying to save it to a file format that doesn't support transparency?

Please see http://stackoverflow.com/questions/33283274/pixelated-fonts-when-plot-is-saved-as-jpeg for more information.

**Comment by tacaswell** [comment]
Odd that it only hits the tick labels, but not the other text.

Can you please move the images and example code over here?  I do not trust SO long-term.

**Comment by cbreeden** [comment]
Here is code to reproduce the pixelated fonts when saving a figure as a jpeg (when using jupyter):

    %matplotlib nbagg

    import matplotlib.pyplot as plt
    import numpy as np

    x    = np.linspace(-1.2,1.2,1000,endpoint=True)
    y    = np.copy(x)
    x,y  = np.meshgrid(x,y)
    z    = -x**2 + y**2 - y**3

    fig = plt.figure()
    ax  = fig.add_subplot(111)

    CS = plt.contour(x,y,z, [0,-0.1,0.1], colors=['black','blue', 'gray'])
    plt.clabel(CS, fontsize=14, inline=1, fmt='%1.1f', manual=[(-0.15,0), (-0.4,0), (0.25,0.5)])

    plt.title('Contour Sets')

    plt.savefig('plot.png', format='png')
    plt.savefig('plot.jpg', format='jpg')

This produces a plot.png shown here:

![plot](https://cloud.githubusercontent.com/assets/12069845/10713551/676b8e84-7a8b-11e5-933c-b841624a0431.png)

and plot.jpg shown here:

![plot](https://cloud.githubusercontent.com/assets/12069845/10713553/7abbc972-7a8b-11e5-82a2-16bc7d616f3a.jpg)

Adding the following code will "fix" this issue and produce jpegs that look nearly identical to the png files (with the undesirable side-effect of have non-transparent figures rendered in your jupyter notebooks):

    import matplotlib
    matplotlib.rcParams['nbagg.transparent'] = False

Another example for how PIL handles these transparent regions while trying to encode the raw data into jpeg is given by taking the first example and adding the code:

    import matplotlib
    matplotlib.rcParams['savefig.transparent'] = True

plot.jpg in this case looks like this:

![plot_transparent](https://cloud.githubusercontent.com/assets/12069845/10713583/8cd604e6-7a8c-11e5-8fbb-ebe01b751da1.jpg)

I'm not exactly sure if this problem should be handled by the PIL team of the matplotlib team, but it might be worth looking into adding code to remove transparent regions when trying to save figures to file formats that can't handle transparency.  I don't think it would be a difficult issue to fix, and might be able to write up a pull request for a suggested solution at some point in time.

This issue also seems to surface when trying to create animations.
