### ISSUE TITLE
Differences between function and keywords for savefig.bbox and axes.facecolor

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#5309]
For at least two rcparams the name is surprisingly different from corresponding keyword.

     rcParams['savefig.bbox'] = x -> savefig(..., bbox_inches=x)
     rcParams['axes.facecolor']  = x correct for ax.patch but fig.add_axes(bgcolor=x)

I think at least in the second case the keyword should be changed to facecolor for
consistency.

**Comment by tacaswell** [comment]
addressed by #5501
