### ISSUE TITLE
_tickdir inaccurate

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#5311]
When playing around with what pull request #5290 implements, I found that that `_ticksdir` isn't always quite accurate. Check out

``` python
from matplotlib import pyplot as plt

def plot():
    from matplotlib import style
    import numpy as np
    fig = plt.figure()
    with plt.style.context(('ggplot')):
        t = np.arange(0.0, 2.0, 0.1)
        s = np.sin(2*np.pi*t)
        plt.plot(t, s, 'o-', lw=4.1)
    return fig

f = plot()
c = f.get_children()
ax = c[1]
t = ax.xaxis.get_major_ticks()
print([tick._tickdir for tick in ax.xaxis.get_major_ticks()])
plt.show()
```

Clearly, all major ticks are facing `out`, but the `_tickdir`s are reported

``` python
[u'out', u'out', u'in', u'in', u'in']
```

**Comment by mdboom** [comment]
Attn: @pizzathief

**Comment by pizzathief** [comment]
sigh, I've been poked, ok.

from some preliminary hacking, I've found that if I replace the above plot() function with this:
'''
def plot2():
    import numpy as np
    fig = plt.figure()
    t = np.arange(0.0, 2.0, 0.1)
    s = np.sin(2*np.pi*t)
    plt.plot(t, s, 'o-', lw=4.1)
    return fig
'''
ie, no plt.style.context(('ggplot')) command, 
returns ['in', 'in', 'in', 'in', 'in']

so 'ggplot' is playing funny-buggers with ticks.

**Comment by pizzathief** [comment]
```
def plot(x):
    from matplotlib import style
    import numpy as np
    fig = plt.figure()
    with plt.style.context((x)):
        t = np.arange(0.0, 2.0, 0.1)
        s = np.sin(2*np.pi*t)
        plt.plot(t, s, 'o-', lw=4.1)
    return fig

for x in ['fivethirtyeight', 'dark_background', 'bmh', 'grayscale', 'ggplot']:
    f = plot(x)
```

fivethirtyeight  uses ticks of   ['in', 'in', 'in', 'in', 'in']
dark_background  uses ticks of   ['in', 'in', 'in', 'in', 'in']
bmh  uses ticks of   ['in', 'in', 'in', 'in', 'in']
grayscale  uses ticks of   ['in', 'in', 'in', 'in', 'in']
ggplot  uses ticks of   ['out', 'out', 'in', 'in', 'in']

and ggplot is the only one thats getting it wrong, too.

**Comment by pizzathief** [comment]
so temporary styling isn't handling the tickdir values properly, or at least not handling tickdir values of "out" or "inout" properly.  Seems ggplot is one of the few styles that don't specify 'in'.  still ploughing through classes...

**Comment by pizzathief** [comment]
if I put a ipdb.set_trace() statement before
```
plt.plot(t, s, 'o-', lw=4.1)
```

and step through every line thereafter, I get ['out','out','out','out','out'], if I leave out the set_trace(), than I get ['in','in','out','out','out'] . so its a hiesenbug :-(

**Comment by tacaswell** [comment]
There is definitely something fishy going on with the ticks and how they are configured/drawn.  I spent a while looking at this and mostly just grew more confused the more I looked at it (for example, I have having issues flipping individual ticks in/out).

**Comment by efiring** [comment]
Evidently it has been fixed.  When I try the initial example, all ticks are listed as 'out'.
