### ISSUE TITLE
Axes.bar: wrong default parameter in documentation

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#5316]
I have to open pull request, but couldn't decide what is preferred to fix . Logically `vertical` is right for default value, but altering API isn't good for code that relies on it.

From `lib/matplotlib/axes/_axes.py`:

```python
    def barh(self, bottom, width, height=0.8, left=None, **kwargs):
        """
        Make a horizontal bar plot.
        ...
        orientation : 'vertical' | 'horizontal', optional, default: 'vertical'
            The orientation of the bars.
        ...
        """

        patches = self.bar(left=left, height=height, width=width,
                           bottom=bottom, orientation='horizontal', **kwargs)
        return patches
```

**Comment by jenshnielsen** [comment]
Please change the doc string. `barh` is for horizontal bar plots so the default should be horizontal. For a vertical bar plot i suggest using `bar`

**Comment by jenshnielsen** [comment]
Forget about that barh does not actually take a orientation argument since it is hard coded into the call to bar which is how it's actually implemented. Can you remove the orientation argument from the barh docstring and add the correct default to the bar docstring?

```
        patches = self.bar(left=left, height=height, width=width,
                           bottom=bottom, orientation='horizontal', **kwargs)
        return patches
```
