### ISSUE TITLE
Make nbagg recognise the requested facecolor of a figure

### ISSUE THREAD

**Issue by willfurnass** [matplotlib/matplotlib#5317]
The `nbagg` backend in Matplotlib (1.4.3) seems to ignore calls to `figure.set_facecolor`.  

I know that one can disable figure background transparency with `nbagg.transparent : False` in one's `matplotlibrc` (not a particularly well documented feature) but even with that set, the background is grey rather than any color requested with `figure.set_facecolor`.

**Comment by jenshnielsen** [comment]
I cannot reproduce:

```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams.update({'figure.facecolor': 'red',
                            'savefig.facecolor': 'yellow'})
plt.figure()
plt.plot([3, 2, 1])

with matplotlib.rc_context({'nbagg.transparent': False}):
    f= plt.figure()

plt.plot([3, 2, 1])
plt.show()
```
This taken from the nbagg [UAT](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_uat.ipynb)  produces a red figure as expected with both 1.5rc and 1.4.3 can you please provide a minimal example of what you are doing?

**Comment by willfurnass** [comment]
Apologies, I was calling set_facecolor with an invalid MPL color spec (`fig.set_facecolor(1,1,1)` rather than `fig.set_facecolor((1,1,1))`.  Closing.
