### ISSUE TITLE
Migrate to py.test

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5325]
It would be nice to migrate to py.test which seems to have more features and better usability than nose at this point.

This is potentially a large chunk of work given how customized our nose environment is.

**Comment by pizzathief** [comment]
https://github.com/matplotlib/matplotlib/compare/master...pizzathief:5325?expand=1

this is what I've got so far.

**Comment by mdboom** [comment]
Hey, that's great!  I really prefer py.test.  Feel free to open a PR and mark it as "WIP" to start getting some Travis testing running on it.

I appreciate the heads up that you are working on it so we avoid duplication of effort.

**Comment by dstansby** [comment]
This has just been done!
