### ISSUE TITLE
Separate mathtext from the core

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5326]
It would be great to have mathtext as a separate project that becomes a dependency of matplotlib.

**Comment by zblz** [comment]
If it's separate, we might have to duplicate all the font manager stuff, as matplotlib would still need it for regular text. Do you think that mathtext might be useful for other projects?

**Comment by mdboom** [comment]
What I'd like to see happen (ideally) is:

- Separate out the freetype wrapper into its own project (that is already mostly done in matplotlib/freetypy)
- Separate out the font lookup stuff into its own project, and use `fontconfig` rather than our own home grown code wherever feasible (that stuff is a bear, and `fontconfig` solves exactly the same problem).
- The new mathtext would depend on the two projects above
- matplotlib would depend on the font-related projects, and *optionally* mathtext

**Comment by anntzer** [comment]
Closing as unlikely to happen (obviously, if there is interest, we can reconsider).
In particular, note that depending on fontconfig on Windows would bring "interesting" problems to the build.
