### ISSUE TITLE
QuadContourSet lacks remove method

### ISSUE THREAD

**Issue by jslavin** [matplotlib/matplotlib#5332]
Unlike Lnie2D, AxesImage, etc. objects that are contained in Axes, QuadControutSet does not have a remove method.  This makes it more difficult (and certainly non-obvious) how to remove a set of contours from a plot.

**Comment by mdboom** [comment]
Yes, agreed that would be nice to have (though I haven't looked to see if there's a technical reason that's non-easy).  We should find and consider any other classes that can't easily be removed as well.

**Comment by baloe** [comment]
Is there any workaround? Being able to remove those QuadContourSets can be essential when producing animations.

**Comment by jklymak** [comment]
This may indeed be desirable, but if you are computing a contour, my guess would be that you may as well clear and redraw the whole axes - contouring is expensive, even in C code.
