### ISSUE TITLE
Some tests give different results from run-to-run on the same machine

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5334]
The likely cause is a dictionary somewhere that causes the drawing order to be non-deterministic.

I found these in #5307, but decided to punt on resolving them for now -- instead just increasing the tolerance on those tests.  This is a reminder that we may want to go back and investigate this at a later date.

The tests are:
- [ ] test_axes_grid1:test_twin_axes_empty_and_removed
- [ ] test_axes:test_boxplot
- [ ] test_axes:test_boxplot_rc_parameters
- [ ] test_axes:test_specgram_freqs
- [ ] test_axes:test_specgram_noise
- [ ] test_axes:test_specgram_magnitude_freqs

**Comment by tacaswell** [comment]
boxplot is on the list of things to be converted to improved container artists (ex https://github.com/matplotlib/matplotlib/pull/3944)
