### ISSUE TITLE
RendererAgg.tostring_rgb merely truncates alpha

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5336]
As suggested https://github.com/matplotlib/matplotlib/pull/5324#issuecomment-151679275, it might be a good idea to have it actually blend onto some background color instead.

**Comment by cbreeden** [comment]
There is an algorithm for the solution found on stackoverflow http://stackoverflow.com/questions/2049230/convert-rgba-color-to-rgb, which agrees with the solution given on wikipedia.  The solution can be easily modified for our case where our RGB values are from 0-255 as opposed to 0-1 as found in wikipedia:

    //Destination = (Dr, Dg, Db)
    //Source = (Sr, Sb, Sg, Sa)
    //Background = (Br, Bg, Bb)

    Dr = [(255 - Sa)*Br + Sa*Sr]/255
    Dg = [(255 - Sa)*Bg + Sa*Sg]/255
    Db = [(255 - Sa)*Bb + Sa*Sb]/255

I took a quick look at https://github.com/matplotlib/matplotlib/blob/0037595096e3be3ec863f3e3008e73c469e2f2b8/extern/agg24-svn/include/util/agg_color_conv_rgb8.h#L150 and it appears that we would have to create two template functions, one from aRGB like types and one for RGBa types, or add a new input to the template to be able to incorporate the alpha values into the formula.

**Comment by tacaswell** [comment]
Should we just get rid of `tostring_rgb` all together?  It looks like we use it in 2 demos and wxagg, which can use `tostring_rgba` and special case getting rid of the alpha if it really can not deal with it.

**Comment by cbreeden** [comment]
I don't know.  I guess I had a hope that we could fix `tostring_rgb` to flatten with a background color for anytime matplotlib needed to interface with file formats that either doesn't support an alpha channel or supports only a boolean alpha channel (as does gif).

My first impression was that we could solve #5335 by passing 24-bit RGB (flattened) to write_png when it is used as an intermediate fileformat for things that don't support an alpha channel, like most animations.

Looking at the source, it seems that simply passing a 3-dimensional array to write_png will default to 24-bit RGB algorithms: https://github.com/matplotlib/matplotlib/blob/c32bde54dde984b9d51dd824b856d274f9022821/src/_png.cpp#L112

I thought that we could possibly add a kwarg to force RGB (as I believe the conversion has to be done here, or as an init variable to the renderer?) here: https://github.com/matplotlib/matplotlib/blob/b9957b186cb3a509b3db6b3ed7ab67ae776309cd/lib/matplotlib/backends/backend_agg.py#L527

I don't know, I'd have to trace through the steps some more and there probably is a better way.

**Comment by waleedka** [comment]
I just encountered this issue. I'm using `tostring_rgb()` to extract the pixels of multiple Figures and render them into one combined Figure. The result was really bad and it took me a long time to finally find out that the alpha channels are being removed. 

I see this issue was opened in 2015, so clearly not many people are getting bitten by it. Is there another way that I'm missing to extract the pixels of a Figure (without saving it to a file and then loading the file)?

**Comment by waleedka** [comment]
@anntzer Good idea. Solved the problem. Thanks!
