### ISSUE TITLE
Remove --nocapture from nosetests on .travis.yml?

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5337]
As mentioned in https://github.com/matplotlib/matplotlib/pull/5324#issuecomment-151626834, we are passing the `-s` or `--nocapture` flag to `nose` when we run the tests on Travis.  This causes the output of any tests to be printed immediately rather than with its failure block at the end of the run.  On the one hand, this can be nice if the test run is failing catastrophically (e.g. a segfault) because we know what printed right before the process died.  On the other hand, with the "running inside of gdb" functionality we have now, we will at least get a nice traceback when that happens.

I'm inclined to turn off `-s`, but I wanted to confirm there weren't good current reasons for keeping it on.

It seems to have been added by @pelson in b8bc21f4a5854a1cb5778b9ee1db41e1d352948a

**Comment by tacaswell** [comment]
:+1: It makes even less sense now that we print dots instead of the test names (which we do so that travis will render our test logs).

**Comment by pelson** [comment]
Yep, I'm ok with this. :+1:
