### ISSUE TITLE
Combobox improvements in qt figure options editor

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5341]
Some ideas:
- Drop the duplicate "nothing" entries in the marker style combo box (at least present in 1.5.0rc3).
- Sort the entries alphabetically.
- Add an icon with a representation of the marker/line style.

**Comment by mdboom** [comment]
Cc: @jrevans, @mfitzp as recent contributors to the Qt editor.

I think these are all good ideas.  Are you offering to develop pull requests, or just making suggestions?

**Comment by anntzer** [comment]
I need some help to generate QImages with representations of the marker/line styles in order to address my 3rd point.  It'll probably also involve fiddling more with fomrlayout...

**Comment by tacaswell** [comment]
You can use svg/png for that purpose.

**Comment by anntzer** [comment]
Sure, but I also need to figure out where to put the plot, what size to use and so on.  How are the representations in legends created, for example?

**Comment by mdboom** [comment]
The little keys in the legend are produced by the "legend handlers" in `legend_handler.py`.  There is a mapping from each Artist class to a handler class (the mapping itself can be obtained from a `Legend` object) and the handler class takes care of creating the right artist to draw in the legend.

**Comment by anntzer** [comment]
I'm going to need some more help:
```
from matplotlib import pyplot as plt
from matplotlib.backends.backend_agg import RendererAgg
from matplotlib.legend import Legend
from matplotlib.lines import Line2D

from PyQt4.QtGui import QImage


p = Legend(plt.gca(), [Line2D([], [], marker="*")], [""]).get_frame()
n = 50; dpi = 72
r = RendererAgg(n, n, dpi)
p.draw(r)
s = r._renderer.tostring_bgra() # endianness, same as backend_qt5agg.py
q = QImage(s, r.width, r.height, QImage.Format_ARGB32)
q.save("/tmp/test.png")
```
This seems to save an empty image, even though `s` seems to contain a nontrivial pattern (not just a bunch of `\x00\xff\xff\xff` but also some other pixels).  Any hint of what I'm doing wrong?

**Comment by anntzer** [comment]
Icons is probably too complex to implement to be worth it; the other parts have been implemented already.
