### ISSUE TITLE
'ctrl-w' keybinding in wx causes segfault

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#5354]
Closing a wxagg figure window with 'ctrl-w' results in a segfault.  Closing the window via pyplot (`plt.close('all')`) works correctly as does closing the window directly via the OS window manager.

I suspect that somehow we are trying to clean up some c++ objects twice.

**Comment by jenshnielsen** [comment]
I think this issue is related to #3316

**Comment by jenshnielsen** [comment]
Unfortunatly this still happens

**Comment by story645** [comment]
is this a dupe of #3690?

**Comment by jenshnielsen** [comment]
Yes probably

**Comment by story645** [comment]
So can we close one? (or at the least label 'em dupes?)

**Comment by efiring** [comment]
It's possible that both this one and #3690 have been fixed by #5639.  @story645, are you able to reproduce the failures?  And if so, can you test with v2.x to see whether the problem has indeed been fixed?

**Comment by QuLogic** [comment]
This looks like a dupe to me.
