### ISSUE TITLE
Warning in test_labeled_data_unpacking.test_positional_parameter_names_as_function

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5366]
```
matplotlib.tests.test_labeled_data_unpacking.test_positional_parameter_names_as_function ... /matplotlib/tests/test_labeled_data_unpacking.py:406: RuntimeWarning: Second argument is ambiguous: could be a color spec but is in data. Using as data.
Either rename the entry in data or use three arguments to plot.
  assert_equal(funcy(None, "x", "y1", data=data),
ok
```

@tacaswell: I think this warning is legit, and the test is testing it.  In that case the test should put it in a `catch_warnings` block so it doesn't bubble out.

**Comment by tacaswell** [comment]
Roughly related to https://github.com/matplotlib/matplotlib/pull/5244/files

**Comment by QuLogic** [comment]
That file no longer exists, and neither does the test function, as it was removed in #10928.
