### ISSUE TITLE
Change in zorder of streamplot between 1.3.1 and 1.4.0

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5369]
While upgrading Cartopy's test images (SciTools/cartopy#354), it seems that the zorder of the lines in stream plots has changed. Originally, the lines used the default zorder from `LineCollection`, but as a result of #2225, the lines use the zorder default set for the method. The default zorder from `LineCollection` is 2; the default for the method's argument is 1.

If you look carefully at the plot, you can see that the coastlines move from below to above the stream lines:
![streamplot](https://cloud.githubusercontent.com/assets/302469/10861856/c0bd31c4-7f66-11e5-9b04-93682638c4fd.png)

Z order is tricky, being a float, so I'm not whether adjusting the default won't cause issues.

**Comment by QuLogic** [comment]
Ping? Really, it's a simple change, but the question is whether it _should_ be changed here or not?

**Comment by tacaswell** [comment]
:+1: for bumping the method zorder default back to 2

**Comment by efiring** [comment]
I agree with @tacaswell.

**Comment by WeatherGod** [comment]
Fixed by #5567
