### ISSUE TITLE
Orthogonal projection for mplot3d

### ISSUE THREAD

**Issue by tazle** [matplotlib/matplotlib#537]
It would be nice to be able to view 3D plots without the distortions caused by perspective projection. Orthogonal projection allows easier comparison of different elements of a plot, especially when viewing the plot close to the direction of an axis.

Implementation requires orthogonal replacement for `persp_transformation()` in `mpl_toolkits.mplot3d.proj3d` and a constructor parameter that selects which projection is used in `Axes3D`.

**Comment by petehuang** [comment]
PR still welcome here. Looks simple but we should be careful of breaks as @tazle mentions

Recommend labeling as Difficulty: Easy

**Comment by efiring** [comment]
I don't think much of anything involving mplot3d rates as "easy", and I suspect a PR for this feature involves a bit more than the 2011 monkey patch above suggests.  @WeatherGod can change the label if he disagrees.

**Comment by RamiGASMI** [comment]
Hi 

I couldn't correctly implement this patch to use it with Axes3D, could any one help me with an example if possible

Thank you all,

**Comment by WeatherGod** [comment]
This was implemented in v2.1:
https://matplotlib.org/users/whats_new.html#orthographic-projection-for-mplot3d

**Comment by benmaier** [comment]
corrected link:
https://matplotlib.org/users/prev_whats_new/whats_new_2.1.0.html?highlight=orthographic#orthographic-projection-for-mplot3d
