### ISSUE TITLE
Change in large pcolormesh clipping in 1.4.3

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5370]
While upgrading Cartopy's test images (SciTools/cartopy#354), there seems to be a change in large pcolormesh clipping in 1.4.3. It is bisected down to 44ff97e30c03afe6a340b3d256bd04efff5808d0 (note: you also need to apply 86824c37bcd195902ee05b8b28b56e4efdfb5607 to fix the typo), which does achieve the desired speedup, but also changes clipping slightly:
![pcolormesh_goode_wrap](https://cloud.githubusercontent.com/assets/302469/10861917/b6a03cce-7f69-11e5-8463-4a7ef8d2b872.png)
It does not just affect the above because of the strange shape. Even the simpler Mercator projection ends up clipped differently:
![pcolormesh_mercator_wrap](https://cloud.githubusercontent.com/assets/302469/10861922/dac756e6-7f69-11e5-863f-57d68a02f27e.png)

**Comment by mdboom** [comment]
Cc: @pelson as author of the change.  Any thoughts as to the cause?  Just a difference in order of floating point operations, maybe?  I can see how the old behavior is probably a little more correct, so it would be nice to revert to that and keep the speedup if at all possible.

**Comment by pelson** [comment]
A pertinent comment is https://github.com/matplotlib/matplotlib/pull/4045#issuecomment-71987632.

We basically need to tune that ``get_datalim`` function in collections.
