### ISSUE TITLE
imsave and imshow ignore vmin/vmax

### ISSUE THREAD

**Issue by Arnoques** [matplotlib/matplotlib#5382]
I'm sure this should be already known, but I couldn't find any issue related to this.

As far as I can tell, imsave and imshow expect arrays of floats to be from 0 to 1, and arrays of uint8 to be from 0 to 255. In both cases, the vmin and vmax arguments are completely ignored.

The following code shows the issue with imsave, and I'm attaching the resulting images. It was tested with matplotlib 1.5.0 and numpy 1.8.2.

``` python
import matplotlib
print matplotlib.__version__  ## 1.5.0

import matplotlib.image as im
a = im.imread('lena.jpg')

print 'a: ', a.min(), a.max(), a.dtype  ## a:  0 255 uint8
# This works fine
im.imsave('test0.png', a)

# vmin and vmax are ignored. Expected a saturated image
im.imsave('test1.png', a, vmin=0, vmax=128)
a_expected = a.astype('float')/128
im.imsave('test1_expected.png', a_expected)

b = a.astype('float')
print 'b: ', b.min(), b.max(), b.dtype  ## b:  0.0 255.0 float64
# imsave should use b.min() and b.max() as limits.
im.imsave('test2.png', b)
im.imsave('test2_expected.png', b/255)

# vmin and vmax are ignored. Expected an image equal to the original
im.imsave('test3.png', b, vmin=0, vmax=255)
im.imsave('test3_expected.png', b/255)

c = b / b.max()
print 'c: ', c.min(), c.max(), c.dtype  ##c:  0.0 1.0 float64
# This works fine
im.imsave('test4.png', c)

# vmin and vmax are ignored. Expected a saturated image
im.imsave('test5.png', c, vmin=0, vmax=0.5)
im.imsave('test5_expected.png', c*2)
```

![lena](https://cloud.githubusercontent.com/assets/1845086/10894478/a9afe1b0-818d-11e5-8831-445f26a5b1e4.jpg) original
![test0](https://cloud.githubusercontent.com/assets/1845086/10894479/a9b033ae-818d-11e5-912f-c616ab61201f.png) test0
![test1](https://cloud.githubusercontent.com/assets/1845086/10894480/a9b2e34c-818d-11e5-8c1b-a93d653ff987.png) test1
![test1_expected](https://cloud.githubusercontent.com/assets/1845086/10894481/a9b38ec8-818d-11e5-9456-fd5c9b7501d3.png) test1_expected
![test2](https://cloud.githubusercontent.com/assets/1845086/10894477/a9afd6c0-818d-11e5-831d-0141097bd04c.png) test2
![test2_expected](https://cloud.githubusercontent.com/assets/1845086/10894482/a9b398dc-818d-11e5-99ff-b055039821a1.png) test2_expected
![test3](https://cloud.githubusercontent.com/assets/1845086/10894483/a9d2a18c-818d-11e5-972e-783ed72397a1.png) test3
![test3_expected](https://cloud.githubusercontent.com/assets/1845086/10894485/a9d3bdec-818d-11e5-9da8-547e9ea373c0.png) test3_expected
![test4](https://cloud.githubusercontent.com/assets/1845086/10894484/a9d30122-818d-11e5-8dc5-b3ee2757724f.png) test4
![test5](https://cloud.githubusercontent.com/assets/1845086/10894486/a9d55d14-818d-11e5-9ebf-5d72abe4a471.png) test5
![test5_expected](https://cloud.githubusercontent.com/assets/1845086/10894487/a9d65c8c-818d-11e5-92cd-591f14eb133f.png) test5_expected

**Comment by efiring** [comment]
I think you are misunderstanding the docstrings; maybe they can be improved.  The vmin/vmax kwargs are used only in the case where color mapping is being done, which is the case with a 2-D array input.  In all of your examples, I think you are using 3-D inputs, that is, 2-D arrays of RGB or RGBA.  These are not colormapped, so the cmap kwarg is inactive, and no normalization is done.

**Comment by tacaswell** [comment]
You are passing in an RGB(A) array which goes through a different code path which do not get passed through the normalize/colormap framework.

Also, please do not use Lena as an example image anymore.

**Comment by Arnoques** [comment]
Ok, I'm definitely misunderstanding the docstrings. It wasn't clear to me that RGB or RGBA weren't colormapped, though I can see it now. Maybe the docs could be clarified?
The following changes would make then clearer to me:
```
         format is deduced from the extension of the filename.
       *arr*:
         An MxN (luminance), MxNx3 (RGB) or MxNx4 (RGBA) array.
+        Only luminance images are colormapped.
     Keyword arguments:
       *vmin*/*vmax*: [ None | scalar ]
         *vmin* and *vmax* set the color scaling for the image by fixing the
```
or 
```
       *cmap*:
         cmap is a colors.Colormap instance, e.g., cm.jet.
         If None, default to the rc image.cmap value.
+        When *arr* is an RGB(A) image, *cmap*, *vmin* and *vmax* are ignored
       *format*:
         One of the file extensions supported by the active
         backend.  Most backends support png, pdf, ps, eps and svg.
```
Thanks for your answers!

**Comment by mdboom** [comment]
:+1: on the suggested clarifications to the docstrings.
