### ISSUE TITLE
TclErro : could not open matplotlib.gif

### ISSUE THREAD

**Issue by zsynacl** [matplotlib/matplotlib#5388]
Hi everyone, I used matplotlib in my project but I encounted a problem and I can't know what happend exactly. Here is my command line:

```
App\python.exe file\contour.py "C:\Documents and Settings\fanping\桌面\FOR3D_PARALLEL\print.out" 0 15000
```

and when I excuted, I got an error:

```
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: 
couldn't open "C:\Documents and Settings\fanping\桌面\FOR3D_PARALLEL\程序源码\PFOR3D\Release\For3D_Demo\PortablePython\App\lib\site-packages\matplotlib\mpl-data\images\matplotlib.gif":
no such file or directory
```

current directory is 

```
C:\Documents and Settings\fanping\桌面\FOR3D_PARALLEL\程序源码\PFOR3D\Release\For3D_Demo\PortablePython>
```

I used this in Portable Python whose python version is 2.7.6 and the matplotlib version is 1.3.1. Actually I got a result when the environment path does not have any Chinese charactors. eg. `C:\PortablePython\`

looking forward to any solution

**Comment by mdboom** [comment]
`C:\Documents and Settings\fanping\桌面\FOR3D_PARALLEL\程序源码\PFOR3D\Release\For3D_Demo\PortablePython\App\lib\site-packages\matplotlib\mpl-data\images\matplotlib.gif`

should exist -- it is distributed as part of matplotlib.  One of the ways this sometimes happens is if you install one version of matplotlib on top of another.  You could try deleting `C:\Documents and Settings\fanping\桌面\FOR3D_PARALLEL\程序源码\PFOR3D\Release\For3D_Demo\PortablePython\App\lib\site-packages\matplotlib\` and reinstalling matplotib or reinstalling your Python environment.

**Comment by zsynacl** [comment]
Hey, mdboom, thanks for your comment. But I think there maybe some misunderstanding. 
I didn't install any other version of matplotlib and I also checked the file `matplotlib.gif`, it does exist. I didn't change any thing of matplotlib.

**Comment by mdboom** [comment]
How did you install matplotlib?  Whatever method you used seems to have missed that file.

**Comment by zsynacl** [comment]
nope, I used portable python. I ensure that the file `matplotlib.gif` is just there.
![image](https://cloud.githubusercontent.com/assets/4392800/10927272/60d6349c-82d9-11e5-975d-c77ce8ba7846.png)

**Comment by tacaswell** [comment]
> I used this in Portable Python whose python version is 2.7.6 and the matplotlib version is 1.3.1. Actually I got a result when the environment path does not have any Chinese charactors. eg. C:\PortablePython\
> 
> looking forward to any solution

Might this be a bug in tk? Using conda + python3 + non-ascii path it works correctly, but trying to to the same thing with python2 gives me errors even starting up python.

Can you try with any python 3.4 or 3.5?

**Comment by zsynacl** [comment]
hey tacaswell, I can't control the environment. Maybe I should just suggest the user to use English-only path...

**Comment by anntzer** [comment]
matplotlib.gif no longer exists since https://github.com/matplotlib/matplotlib/pull/5626.
