### ISSUE TITLE
wrong legend in errorbar plot for pandas series

### ISSUE THREAD

**Issue by jkokorian** [matplotlib/matplotlib#5393]
When I make an errorbar plot from pandas Series, the names of the series appear twice in the legend. Once as a solid line, and once as a solid line with error bars. Explicitly setting the label argument replaces the label text for the solid line with errorbars.

    %matplotlib inline
    import matplotlib.pyplot as plt
    import pandas as pd
    import numpy as np
    df = pd.DataFrame(data = np.random.rand(10,3),index=pd.Series(np.arange(0,20,2),name="number"),columns="A B C".split())
    plt.errorbar(df.index,df.A,df.B)
    plt.legend()

![image](https://cloud.githubusercontent.com/assets/6113878/10935717/2fc98b4c-82e8-11e5-8750-683fbc66efdc.png)

**Comment by jkokorian** [comment]
This makes the errorbar plot pretty much unusable... I'll have to convert every series object to an array before plotting it.

**Comment by tacaswell** [comment]
Pretty sure this is because `errorbar` uses `plot` internally and now `plot` is smart enough to label it's self.

**Comment by tacaswell** [comment]
As a quick work-around pass `barsabove=True`, I will have a patch for this shortly.

**Comment by jkokorian** [comment]
Thanks!

**Comment by jkokorian** [comment]
Shortly indeed!:)
