### ISSUE TITLE
Style changes doc has optimistic release date

### ISSUE THREAD

**Issue by takluyver** [matplotlib/matplotlib#5395]
I just noticed that [the page linked from the big orange banner](http://matplotlib.org/style_changes.html) on the website says mpl 2.0 will be released in September 2015, which has now passed. I'd make a PR for it, but I don't know what the new estimate should be.

It also invites style proposals, saying that a decision will be made in August. Has the decision been made yet? Either way, that bit should be updated to reflect the current status.

**Comment by mdboom** [comment]
I'll take care of updating this.

In short, we're not taking proposals anymore.  The decisions are being made at a mini "summit" this very weekend.  A 2.0 release should optimistically be made a few weeks after that.
