### ISSUE TITLE
Expose compression and filter PNG options through savefig

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5397]
As a follow-on to #5389.

JPG saving already has some JPG-specific options.  We just need to follow that pattern again for PNG.

**Comment by eggsperde** [comment]
Would be very useful indeed to trade off file size and image quality before the export.

**Comment by anntzer** [comment]
I think file size optimization should remain the realm of tools such as pngcrush and optipng.

**Comment by eggsperde** [comment]
Definitely see your point, @anntzer - do one thing and do it well - but MPL is such a feature-rich tool that it would be a pity to miss this. Otherwise, let's get rid of the JPG options and the animation support. People can stitch their animations together by hand, too. Actually, who needs JPG anyway? Users could convert it from PNG...

**Comment by anntzer** [comment]
Good luck stitching animations by hand.  To get any reasonable performance you need to pipe the raw buffers to the encoder... which can be done, but is far from trivial.  Similarly (though less so) for jpeg.
OTOH if you really care about your png file size, the optimization size is going to be by far the slowest, so it's fine just to rely on an external tool.

Still, I didn't say I would veto a PR implementing this...

**Comment by tacaswell** [comment]
Please keep the comments here civil and avoid sarcasm.

This is reasonable feature to want, but given that it can be handled via external tools is not the highest priority (as you can infer that this is ~2 years old).

@eggsperde I would be happy to review a PR adding this feature.

**Comment by eggsperde** [comment]
No offense/sarcasm taken! 

It seems that PNG only has one compression variable ("speed/compression ratio"). The resulting image is always lossless. For more compression we'd have to look to external programs. I honestly thought there would be more to it. 

I am currently in the final stretch of writing a thesis, but would like to give this a shot once I have a real life again.

**Comment by tacaswell** [comment]
@eggsperde Best of luck finishing the thesis!

**Comment by philmaweb** [comment]
any progress towards this feature request?
