### ISSUE TITLE
FuncAnimation w/o init_func breaks when saving

### ISSUE THREAD

**Issue by cbreeden** [matplotlib/matplotlib#5399]
I was trying to work out a patch to #5335 and ran into issues introduced in merge #4800.  The following code is slightly simplified example from the animations examples:

    %matplotlib nbagg

    import matplotlib
    import matplotlib.pyplot as plt
    import matplotlib.animation as animation

    import numpy as np

    def update_line(num, data, line):
        line.set_data(data[...,:num])
        return line,

    fig = plt.figure()
 
    plt.xlim(0, 1)
    plt.ylim(0, 1)

    data = np.random.rand(2, 10)
    l, = plt.plot([], [], 'r-')

    ani = animation.FuncAnimation(fig, update_line, 10, fargs=(data, l),
                                                       interval=50, blit=True)
    ani.save('im.gif', writer='imagemagick')

running this yields:

![im 1](https://cloud.githubusercontent.com/assets/12069845/10946139/4b2470c0-82e6-11e5-947f-4a916ce875a4.gif)

The animation displays correctly in the notebook.  The issue is introduced here https://github.com/matplotlib/matplotlib/blob/5c58ea950e1c2bbe3c615a3a360b5368061ebb2f/lib/matplotlib/animation.py#L766.  When `FuncAnimation._init_draw()` is called, if no `init_func` is given, the first frame sequence is appended to `self._save_seq`.  After which, https://github.com/matplotlib/matplotlib/blob/5c58ea950e1c2bbe3c615a3a360b5368061ebb2f/lib/matplotlib/animation.py#L769 is executed and `FuncAnimation.new_saved_seq()` then only returns the first drawn frame for which to iterate over.  The end result is an animation file with only one frame.

**Comment by tacaswell** [comment]
attn @dopplershift

**Comment by tacaswell** [comment]
@WeatherGod

**Comment by WeatherGod** [comment]
Confirmed. This is a regression in 1.5.0. I can create a correct gif using
1.4.3.

**Comment by tacaswell** [comment]
5c58ea950e1c2bbe3c615a3a360b5368061ebb2f is the commit and https://github.com/matplotlib/matplotlib/pull/4800 is the PR where it was added for context

**Comment by WeatherGod** [comment]
Hmm, just noticed something:

```
if frames is None:
    self._iter_gen = itertools.count
elif six.callable(frames):
    self._iter_gen = frames
elif iterable(frames):
    self._iter_gen = lambda: iter(frames)
if hasattr(frames, '__len__'):
    self.save_count = len(frames)
else:
    self._iter_gen = lambda: xrange(frames).__iter__()
    self.save_count = frames
```
A couple of those lambda functions might be technically incorrect. What does `frames` resolve to when the lambda gets invoked later? Could it be that the save code-path is picking up a different "frames" variable at that point?

**Comment by cbreeden** [comment]
A quick test verifies that if `frames` is modified then `_iter_gen` _will_ return the newly modified `frames` version (which could even break if you go from say a callable to an integer), but I was unable to find any point in the source where `frames` could potentially be modified.

**Comment by jenshnielsen** [comment]
Sorry about that. I don't think it makes sense to call the init function unless a non default function is supplied. I have done that in #5402
