### ISSUE TITLE
Match zdata cursor display scalling with colorbar ?

### ISSUE THREAD

**Issue by JGoutin** [matplotlib/matplotlib#5409]
Hello,

With Matplotlib 1.5.0, zdata to the cursor is displayed in the status bar. It is a very good new feature.
But, this zdata is the base data value, and this don't match if a scalling is used with the colorbar.

Is it possible to scale this displayed zdata like the colorbar ? I din't found an existing function for rescale this zdata.

I think the better solution should be to default use the scaling used on the colorbar.

Thanks.

**Comment by tacaswell** [comment]
I don't quite understand what you mean.  Can you provide a snippet of code which demonstrates the problem?

**Comment by JGoutin** [comment]
Sorry if I am unclear.

Here is a snippet :
```python
import matplotlib.pyplot as plt
from matplotlib.pyplot import colorbar, gca
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.ticker import FuncFormatter
import numpy as np

# Source data
RawData = np.array(((1.0, 2.0), (3.0, 4.0)))  # Raw data in µm
DisplayUnitFactor = 1000  # Display unit is nm

# A plot with raw datas
plot = plt.matshow(RawData)

# Colorbar with Z scalled to unit (nm)
cbcax = make_axes_locatable(gca()).append_axes("right", "10%", pad="1%")
cbformat = FuncFormatter(lambda z, pos: '{0:g}'.format(z * DisplayUnitFactor))
cbar = colorbar(plot, cax=cbcax, format=cbformat)

plt.show()
```
![example](https://cloud.githubusercontent.com/assets/13535894/10992474/6db679f4-8466-11e5-9ecf-3b99bfbc0973.jpg)
In Statusbar, Z is still in µm even if my colorbar is in nm.

Ideally, FuncFormatter from the colorbar may be applied on the statusbar Z display also.

**Comment by efiring** [comment]
Why not just scale your data in `matshow` instead of doing it in the colorbar tick formatter?

**Comment by WeatherGod** [comment]
Isn't that besides the point? Don't we already obtain the axis formatters
for the x and y coordinates? I think it would make sense to use the
colorbar's formatter if it is available.

**Comment by efiring** [comment]
You are right, this is a reasonable idea, and it looks easy enough for the use case here.
In backend_bases:
```
   2839                     a = max(enumerate(artists), key=lambda x: x[1].zorder)[1]
   2840                     if a is not event.inaxes.patch:
   2841                         data = a.get_cursor_data(event)
   2842                         if data is not None:
   2843                             s += ' [%s]' % a.format_cursor_data(data)
   2844
```
One can try to find a `a.colorbar`; if it exists and is callable, then use it in place of `a.format_cursor_data`.
It might also be good to allow an axes to have an `fmt_zdata` attribute, like `fmt_xdata` and `fmt_ydata` for setting an alternative formatter.  One might not always want the formatting for the cursor display be the same as for the colorbar ticks.
@JGoutin would you like to generate a pull request along these lines?  Or at least for the first part?

**Comment by efiring** [comment]
Side comment: it would be nice not to have so much logic executed inside `mouse_move`; maybe some of it can be factored out. `format_cursor_data()` is a generic `Artist` method.  It could be overridden in a color-mapped artist when a colorbar is assigned to it.

**Comment by tacaswell** [comment]
Do the color mappables know what color bar they are associated with?

This seems like a very deep coupling that I am not sure we want.

In any case, the logic for this mapping should live in the artists, not the
axes.

**Comment by efiring** [comment]
On 2015/11/06 9:40 AM, Thomas A Caswell wrote:
> Do the color mappables know what color bar they are associated with?

Yes. Colorbar.colorbar_factory attaches the `colorbar` attribute to the 
mappable.

**Comment by JGoutin** [comment]
> would you like to generate a pull request along these lines? Or at least for the first part?
Why not. But my knowledge on mpl low level working is very poor.

>One can try to find a a.colorbar; if it exists and is callable, then use it in place of a.format_cursor_data.
I tried to do this, but a.colorbar is not be callable (With my snippet, in any case).

**Comment by efiring** [comment]
Oops!  I meant to say that one looks for a callable `a.colorbar.formatter`.

**Comment by JGoutin** [comment]
Work good with this. I created a pull request : #5425.
