### ISSUE TITLE
boxplot rcParams are not in matplotlibrc.template

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5441]
The boxplot rcParams added in #4218 are not included in matplotlibrc.template

**Comment by mdboom** [comment]
@olgabot: Could you take this one?  I tried to tackle it, but I'm not sure of the definition of all of the new rcParams.

**Comment by tacaswell** [comment]
@phobson is also a good person to ping on boxplot stuff

**Comment by phobson** [comment]
@mdboom @tacaswell 

I can take a look at this in the coming weekend.
