### ISSUE TITLE
Axes3D: tick label positioning logic changed in 1.5.0

### ISSUE THREAD

**Issue by fjarri** [matplotlib/matplotlib#5447]
Consider the following code:

```
import matplotlib
matplotlib.use('Agg')
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(4, 3))
ax = fig.add_subplot(111, projection='3d')
X, Y, Z = axes3d.get_test_data(0.05)
matplotlib.rcParams['font.size'] = 7
ax.plot_wireframe(X, Y, Z, rstride=10, cstride=10)

fig.savefig('t_' + matplotlib.__version__ + '.png')
```

In 1.4.3 it produced the following:

![t_1 4 3](https://cloud.githubusercontent.com/assets/30720/11025740/93e5ee4a-86f3-11e5-8f8b-5092fbea7815.png)

But in 1.5.0 I get:

![t_1 5 0](https://cloud.githubusercontent.com/assets/30720/11025746/9ee914fc-86f3-11e5-943f-2a204923c0b2.png)

Notice how the tick labels are disproportionately far from the axes. Is it some parameter in `rcParams` that I can revert to 1.4.3 value, or a bug?

**Comment by mdboom** [comment]
@WeatherGod: I don't know if this is 3d-specific or not, but Cc'ing you just in case.

**Comment by WeatherGod** [comment]
One of the changes in v1.5 was that mplot3d now respects the labelpad
rcParam: http://matplotlib.org/users/whats_new.html#configuration-rcparams.
However, I am not entirely certain that it was implemented correctly, as it
needed to do some hacky calculations to give a somewhat correct appearance
in various situations. If I were to do a regular 2D plot with your figure
size and fontsize, the tick labels are not all that spaced out...

On Mon, Nov 9, 2015 at 7:53 AM, Michael Droettboom <notifications@github.com

**Comment by mdboom** [comment]
`git bisect` says this was introduced in 0f66d2c0bc212356b076e279d11210929bc00a45

**Comment by mdboom** [comment]
Cc: @WeatherGod, @jbbrokaw  I'm not terribly familiar with this code path, so anything you can suggest would be great.

**Comment by WeatherGod** [comment]
@mdboom, I wonder if git bisect got caught in a local minimum. The very next commit should have fixed this issue, I think. In #3787, I specifically tested resizing of the figure window with success prior to merging. I suspect something else is going wrong.

**Comment by mdboom** [comment]
> The very next commit should have fixed this issue

By the very next commit, you mean c22e057?  That doesn't seem to fix it for me.

**Comment by mdboom** [comment]
> I specifically tested resizing of the figure window with success prior to merging

I'm not sure resizing of the figure window is necessary to reproduce this...

**Comment by WeatherGod** [comment]
if by necessary, do you mean "sufficient"? I would have thought that resizing the figure window would result in different figure sizes.

**Comment by mdboom** [comment]
I don't think this bug is related to figure size at all.  The spacing between the axis and the tick labels is too large regardless of the figure size.

**Comment by WeatherGod** [comment]
So, perhaps the hardcoded values need to be tweaked? Still curious that I
wouldn't have notice this when I tested this myself.

On Wed, Dec 9, 2015 at 3:19 PM, Michael Droettboom <notifications@github.com

**Comment by tacaswell** [comment]
@WeatherGod  Planning to punt on this for 1.5.1 unless you know how to fix it.

**Comment by WeatherGod** [comment]
I won't be able to get to this until maybe later this week. I don't know
what your timeline is for releasing v1.5.1. It should be an easy fix, just
a lot of guessing and checking.

**Comment by tacaswell** [comment]
This behavior has now been like this for 7 years so closing this issue.
