### ISSUE TITLE
Matplotlib is crashed over figersize=(288,16) and dpi = 500

### ISSUE THREAD

**Issue by TharinduKetipe** [matplotlib/matplotlib#5455]
Currently I,m working on CPU consumption and memory consumption visualizing tool for large distributed system. There are so many processes running. Some times this will covers the processes of whole day and generates graphs. For the clearance of the graph I'm changing the width of the figure size according to the time rang. Height of the figure size is constant. Output is png and it's more like the structure of a ECG printout. But when the figure width passes the 288 (for dpi=500), python was giving segmentation fault and matplotlib was crashed. What is the maximum capacity of this library?

**Comment by Tillsten** [comment]
You are properly out of memory, figure of this size uses at least 9 BG. Btw for this kind of question either stack-overflow or the mailing list are more appropriate.

**Comment by TharinduKetipe** [comment]
Sorry. I thought it is an issue of the library. Because I was running this process on system which have 65GB RAM.

**Comment by WeatherGod** [comment]
"system which have 65GB RAM"

!?!

Ok, important question. Are all 65GB of RAM accessible to any process, or
is it a cluster of some sort that has a total of 65GB of RAM?

**Comment by TharinduKetipe** [comment]
Yup. But there are some other huge processes too. So Tillsten should right I was running out of memory.

**Comment by TharinduKetipe** [comment]
When we are plotting multiple graphs in the same plot . Do library plot  one by one and merge them?

**Comment by tacaswell** [comment]
There is a limit in the underlying Agg where the rendering buffer is indexed with a uint16 (of which we can use 15bits?) which too-small for your image.

See https://github.com/matplotlib/matplotlib/pull/3451, https://github.com/matplotlib/matplotlib/issues/2105

attn @mdboom

**Comment by mdboom** [comment]
@tacaswell is right about the limitations in the Agg rendering buffer size.  I suspect it's true of most rasterizing libraries.  You do eventually have to represent values in pixels, and Agg uses 32-bit ints as 16.16 fixed point values, to the maximum number of pixels in any dimension is 2^16.  Using floating point wouldn't solve the problem because then you'd lose precision when the pixel values got high enough.  

To deal with really large images, you can sometimes get away with exporting to a vector format (PDF/SVG/PS), however.

**Comment by TharinduKetipe** [comment]
Also PDF wasn't working.

**Comment by WeatherGod** [comment]
Depending on what you are plotting, even the vectorized backends may
utilize the AGG backend for any rasterized portions of the plot.

**Comment by mdboom** [comment]
@TharinduKetipe wrote:
> Also PDF wasn't working.

Can you provide more details, such as a backtrace?

**Comment by TharinduKetipe** [comment]
Actually the same image size which I have provided before, wasn't working for the png format. Then I was trying to create that figure from the pdf format. But I was return the empty pdf document. I was trying several times, sometimes pdf was created with only X axis and Y axis nothing in the middle of the graph.

**Comment by QuLogic** [comment]
I don't think there's any need to keep this open, given that Agg limitations are already covered in #2105.
