### ISSUE TITLE
Example of new colormaps is misleading

### ISSUE THREAD

**Issue by 8one6** [matplotlib/matplotlib#5457]
Hooray for the new colormaps!

Boo for examples with the new colormaps that obfuscate their nature!

The example here (http://matplotlib.org/1.5.0/users/whats_new.html#new-colormaps) is attempting to show two things at once: first the new colormaps themselves and second the ability to use the new cycler functionality to change things from one place to another.

I think this is very misleading.  I think it makes much more sense to show the four new colormaps by plotting the *same* data four times, with only the colormaps changing from one axes to the next.

Thoughts?

**Comment by tacaswell** [comment]
Fair point, but I think a bit strongly worded.  I don't think anyone would look at those images and think they were the same data so using 'misleading' in the issue title is misleading as it were.

I would not be opposed to a PR that switched that data out for the 'standard' test pattern we use for all of the contour examples.

I am in favor of closing this issue independent of a future PR to change the example, but given that I wrote that example I will leave that for someone else.

**Comment by efiring** [comment]
Agreed.  I will close this, but a simple PR as @tacaswell suggests is welcome.
