### ISSUE TITLE
Adding colorbar changes imshow plot color when vmin is close to vmax

### ISSUE THREAD

**Issue by IamJeffG** [matplotlib/matplotlib#5467]
I can't tell whether this is an intended feature or a bug, so I'm going to run it by the group.

```
f = plt.figure()
mappable = plt.gca().imshow([[42]])
```

Here, we gave a single pixel, so the entire plot is the same color.
With default jet colormap, that single color is dark blue (the bottom of the jet cmap).  So far so good.

```
f.colorbar(mappable)
```

Here, observe that since vmin==vmax (effectively), the colorbar defaulted to the midpoint of the colormap, now green.  Luckily, the Axes from imshow, containing the data, changed too!

On one hand, I like that the colorbar shows context around the singular value. (I think due to [this line](https://github.com/matplotlib/matplotlib/blob/5ac32f3ad0f3464c4e996cb723dec0351d76d7ce/lib/matplotlib/colorbar.py#L671).)  On the other hand, over in Geopandas we plot patches one-by-one with face_color values from a normalized colormap, but adding this renormalization means the colorbar no longer matches the cmap I passed it.

Thoughts? If you tell me this is intended I'm willing to find a workaround to my use case. (Frankly I'm not 100% sure what I would expect matplotlib to do here instead.)  Just wanted to get a second opinion.

**Comment by mdboom** [comment]
Cc: @efiring

**Comment by tacaswell** [comment]
We probably should push the range expansion logic up (down?) into `ColorMappable`.

@IamJeffG You might be better performance if you use `PatchCollection` and we will do the color mapping for you.

**Comment by IamJeffG** [comment]
@tacaswell Thanks for the `PatchCollections` tip, they do give better performance!  But sometimes we'll have a GeoSeries with multiple geometry types, requiring multiple Collections.  I can't find a way to have two different Collections share the same colormap using `collection.set_array()`, so I still end up explicitly setting the colors on each Collection to the result of `mappable.to_rgba(values)` -- which still has the bug mentioned above.

**Comment by tacaswell** [comment]
@IamJeffG `mappable.set_map(cm)` does not work?

**Comment by IamJeffG** [comment]
@tacaswell Each collection re-normalizes the colormap to its own range of values.  So if `collection1` has values in (0, 5) and `collection2` has values in (20, 25), each with `set_map('RdBu')`, I wanted `collection1`  (low values) to be in the reds and `collection2` (high values) to be in the blues.

I was able to do this by setting `set_clim` to the absolute min and max on both collections.  Problem solved!  (The behavior mentioned in the issue title is still a problem though.)

**Comment by IamJeffG** [comment]
I still notice the behavior from the issue title ("adding colorbar changes imshow plot color") but I'm not convinced if this behavior is buggy.  Let's let this go. Closing.

**Comment by tacaswell** [comment]
Thanks @IamJeffG .

Re-reading this, I think I agree.  We are in a bit of a bind.  If you want a colorbar, the norm must not be singular so our options are to expand the norm or to raise and I think this is a case where expanding is reasonable.

Currently if you set the norm to be singular after the colorbar is added it will re-expand itself.
