### ISSUE TITLE
colorbar values could take advantage of offsetting and/or scientific notation

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5470]
Currently, colorbars seem to label their values by simply printing them out (with `str`).  It may be advantageous to use scientific notation and offset the values when needed (like axes do) instead.

Silly example:
```
from pylab import *; plt.imshow(np.random.rand(32, 32) / 1000); plt.colorbar(); plt.show()
```

**Comment by mdboom** [comment]
Colorbars have a formatter like regular axes, so you can tweak this behavior through

```
c = plt.colorbar()
c.formatter.set_scientific(True)
c.formatter.set_powerlimits((-1, 1))
# etc...
```

**Comment by anntzer** [comment]
Fair enough.  Consider this a vote for changing the default, then?

**Comment by efiring** [comment]
I think the default is already the same as for the x-axis and y-axis.  In all cases it is the ScalarFormatter with powerlimits of [-7, 7].

**Comment by anntzer** [comment]
I didn't realize that I tend to have x and y axes of the style "largenumber+[smallnumbers]" (which triggers scientific notation) but colorbars which are all (moderately) large numbers and therefore do not trigger scientific notation.  I was confused, my apologies.
