### ISSUE TITLE
FuncAnimation video saving results in one frame file

### ISSUE THREAD

**Issue by nils-werner** [matplotlib/matplotlib#5471]
When trying to use the [`basic_example_writer.py` example](http://matplotlib.org/examples/animation/basic_example_writer.html) I have noticed that the first file generated, `lines.mp4`, is empty. It shows one frame of plot backdrop but none of the lines appear.

This also happened with any other animation I myself was trying to write. Thus it seems that `FuncAnimation` ins incapable of creating animation videos.

Tried on platforms: Mac OSX and Ubuntu 14.04

**Comment by jenshnielsen** [comment]
I think this is a duplicate of #5399 fixed by #5402

**Comment by jenshnielsen** [comment]
The workaround is to add an init function to the function animator. That should work even if it is a noop

**Comment by nils-werner** [comment]
That is indeed correct, sorry for not spotting the issue earlier. :-)

**Comment by jenshnielsen** [comment]
No problem :)
