### ISSUE TITLE
Strange OS warning when import pyplot after upgrading to 1.5.0

### ISSUE THREAD

**Issue by notmatthancock** [matplotlib/matplotlib#5473]
I recently upgraded matplotlib to 1.5.0. I'm on OS X 10.6 with python 2.7.10. Whenever I import pyplot I receive these strange warnings:

    python -c "import matplotlib" # works fine
    python -c "import matplotlib.pyplot"
    2015-11-12 15:36:07.607 Python[8342:60f] *** __NSAutoreleaseNoPool(): Object 0x102e133e0 of class NSRunningApplication autoreleased with no pool in place - just leaking
    2015-11-12 15:36:07.610 Python[8342:60f] *** __NSAutoreleaseNoPool(): Object 0x102e13500 of class NSConcreteValue autoreleased with no pool in place - just leaking

I'm not really sure how to trace this back.

----

edit:

Since the only thing I could think to possibly do was try a reinstall of python, and since I've installed python with `brew`, I ran:

    brew reinstall python

The warnings above persist.

**Comment by mdboom** [comment]
Cc: @mdehoon

**Comment by mdehoon** [comment]
I cannot replicate this bug with matplotlib 1.5.0 and python 2.7.10. Could you try with Python 2.7.10?

**Comment by tacaswell** [comment]
What backend are you using?

**Comment by notmatthancock** [comment]
@mdboom , you wrote the same version twice. I assume you meant some other version? In any case, I've not tried any other version of python.

@tacaswell MacOSX. If I use TkAgg, there are no warnings.

**Comment by mdehoon** [comment]
@notmatthancock  Since I could not replicate this bug with Python 2.7.10, I am wondering if you get this bug if you use Python 2.7.10. Python 2.7.1 is quite old.

**Comment by notmatthancock** [comment]
@mdehoon , I'm sorry! Not only, did I misread your comment, but I misread my *own* version. I am indeed using 2.7.10! ... 2.7.1 is not installed on this machine.

**Comment by notmatthancock** [comment]
I traced this back using print statements to the import of the `_macosx.so` module. I'm guessing this has to do with my version of OSX?

**Comment by mdehoon** [comment]
That is possible. Can you tell me which compiler you are using?

**Comment by notmatthancock** [comment]
gcc 4.2.1

**Comment by mdehoon** [comment]
@notmatthancock  Can you try putting
```
            NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
...
            [pool release];
```
around the connection manager stuff at the end of init_macosx function in src/_macosx.m ?
The resulting code should look like
```
    NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
    WindowServerConnectionManager* connectionManager = [WindowServerConnectionManager sharedManager];
    NSWorkspace* workspace = [NSWorkspace sharedWorkspace];
    NSNotificationCenter* notificationCenter = [workspace notificationCenter];
    [notificationCenter addObserver: connectionManager
                           selector: @selector(launch:)
                               name: NSWorkspaceDidLaunchApplicationNotification
                             object: nil];
    [pool release];
```

**Comment by notmatthancock** [comment]
@mdehoon I wrapped the code and as you said and rebuilt. This cleared the second warning, namely the `NSConcreteValue` one. However, the first warning still appeared. Following your lead (I know close to nothing about objective-C and Cocoa apps), I searched the source for `NSRunningApplication`. Not surprisingly, it appears in a `#ifdef COMPILING_FOR_10_6` block. I wrapped the contents of this block similarly:

    ....
    #ifdef COMPILING_FOR_10_6
        NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
        NSRunningApplication* app = [NSRunningApplication currentApplication];
        NSApplicationActivationPolicy activationPolicy = [app activationPolicy];
        switch (activationPolicy) {
            case NSApplicationActivationPolicyRegular:
            case NSApplicationActivationPolicyAccessory:
                return true;
            case NSApplicationActivationPolicyProhibited:
                break;
        }    
        [pool release];
    #else
    ....

After rebuilding, the warnings are gone, and `matplotlib` appears to be working as normal.

**Comment by mdehoon** [comment]
@notmatthancock  Great, thanks. Note that in your code block above, the function will return true before the pool is released. As a final check, could you modify the code to make sure the pool is released before returning true? I don't expect any problems, but it would be good to make sure before we add this to the matplotlib code base.

**Comment by notmatthancock** [comment]
Ok. I made the following change, and did a clean build.

    ....
    #ifdef COMPILING_FOR_10_6
        NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
        NSRunningApplication* app = [NSRunningApplication currentApplication];
        NSApplicationActivationPolicy activationPolicy = [app activationPolicy];
        switch (activationPolicy) {
            case NSApplicationActivationPolicyRegular:
            case NSApplicationActivationPolicyAccessory:
                [pool release]
                return true;
            case NSApplicationActivationPolicyProhibited:
                break;
        }    
        [pool release];
    #else
    ....

Afterwards, the `NSConcreteValue` warning appeared again. So it appears your first modification is also necessary. I didn't clean before I rebuilt, which is probably why I thought it wasn't necessary earlier.

So to be clear: I added your modification above, as well as the modification in this post, cleaned, and rebuilt. This removes the warnings.

**Comment by mdehoon** [comment]
OK thanks. See pull request #5480  for the bug fix.

**Comment by mdehoon** [comment]
@notmatthancock  I believe this issue can be closed; please let me know if there are still any outstanding problems.
