### ISSUE TITLE
artist picker tolerance has no effect

### ISSUE THREAD

**Issue by mistycheney** [matplotlib/matplotlib#5475]
In artist.set_picker(float tolerange), the tolerance argument has no effect. No matter what value it is set to, a pick event is triggered only when click is contained completely within the patch.

**Comment by tacaswell** [comment]
Can you provide a minimal example?

**Comment by mistycheney** [comment]
```python
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(20,20))
ax = fig.add_subplot(111)
ax.set_xlim([0,20])
ax.set_ylim([0,20])
ax.set_aspect('equal')

def on_pick(event):
    print 'picked'

cid = fig.canvas.mpl_connect('pick_event', on_pick)

circle = plt.Circle((10, 10), radius=5, color=(1,0,0))
circle.set_picker(200.)
ax.add_patch(circle)

plt.show()
```

Note that although I set the picker tolerance to 200., callback is only triggered when I click on the circle itself.
