### ISSUE TITLE
Can't set specific text alignment in table

### ISSUE THREAD

**Issue by YujiShen** [matplotlib/matplotlib#5478]
``` python
tb = plt.table(cellText=[[1,2],[42,1]],
          rowLabels=["A","B"],
          colLabels=["1","2"],
          loc="bottom", 
          bbox=[0,-0.2,1,0.15])

tb.get_celld()[(1,0)].get_text().set_color('red')

print tb.get_celld()[(1,0)].get_text().get_ha()
tb.get_celld()[(1,0)].get_text().set_ha(u'center')
print tb.get_celld()[(1,0)].get_text().get_ha()
```

![matplotlib_issue](https://cloud.githubusercontent.com/assets/4230496/11149737/5469a5e8-89f2-11e5-9744-40342d7e70ac.png)

There is no problem for `cellLoc`, but it is for all cells.
I can set specific text color or cell color, but not text ha. I did not find option like `auto_set_font_size` for alignment.
Matplotlib 1.5.0

**Comment by mdboom** [comment]
Cc: @zairmubashar 

@YujiShen: Our table layout code doesn't see a lot of maintenance, so I'm not surprised you are finding these cases where it doesn't work well.  It really needs a maintainer to come in to work on some of these things.

**Comment by YujiShen** [comment]
@mdboom Thanks for reply!
I am curious whether I can do some contribution for it, is there any criteria for contributor?

**Comment by mdboom** [comment]
There's no criteria at all to becoming a new contributor.  Just submit a pull request and we'll be happy to review it.  We have some tips in our developer docs.

**Comment by YujiShen** [comment]
@mdboom Thanks! I found the docs. Great resources to learn how to contribute!

**Comment by jajupmochi** [comment]
Hi, just wondering if it is fixed or not? Thanks!

**Comment by timhoffm** [comment]
@jajupmochi This is not implemented. Otherwise the issue would have been closed.

**Comment by QuLogic** [comment]
You may want to look at [blume](https://github.com/swfiua/blume/) for this, which has a more comprehensive table implementation.
