### ISSUE TITLE
Table: auto_set_column_width not working

### ISSUE THREAD

**Issue by YujiShen** [matplotlib/matplotlib#5479]
```python
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
ax1, ax2 = axs
ax1.axis('off')
ax2.axis('off')

# Table1 use auto_set_column_width
tb1 = ax1.table(cellText=[['Long Text', 2],['Long Long text', 1]],
          rowLabels=["A","B"],
          colLabels=["Col1","Col2"],
          loc="center")
tb1.auto_set_font_size(False)
tb1.set_fontsize(12)
tb1.auto_set_column_width(["Col1","Col2"]) # NOT WORKING
tb1.auto_set_column_width([-1,0,1]) # NOT WORKING

# Table 2 use _autoColumns
tb2 = ax2.table(cellText=[['Long Text', 2],['Long Long text', 1]],
          rowLabels=["A","B"],
          colLabels=["Col1","Col2"],
          loc="center")
tb2.auto_set_font_size(False)
tb2.set_fontsize(12)
tb2._autoColumns = [-1,0,1]
```
![matplotlib_issue_2](https://cloud.githubusercontent.com/assets/4230496/11151142/66e03816-89f9-11e5-9c26-fd0a195c1ece.png)

Matplotlib 1.5.0

**Comment by mdboom** [comment]
@zairmubashar: As someone who recently improved the table code, I wonder if you have any thoughts.

**Comment by tacaswell** [comment]
@YujiShen This would be another place in the table code where any contributions would be welcome!

**Comment by tacaswell** [comment]
Sorry, that did not come out right, the entire code base is a place where contributions would be welcome.

What I meant is that this is a great place in the code base to start contributing!

**Comment by YujiShen** [comment]
@tacaswell Thanks! Great to hear that! I will learn how to contribute.
