### ISSUE TITLE
The default number of ticks should be based on the length of the axis

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5488]
The default number of ticks is fixed, and not dependent on the size of the axis.  This causes text to run together and almost always do the wrong thing in figures with multiple subplots.

For example:

![](http://matplotlib.org/_images/scales.png)

**Comment by has2k1** [comment]
This may be helpful

http://graphics.stanford.edu/vis/publications/2010/labeling-preprint.pdf
http://graphics.stanford.edu/vis/publications/2010/extended.txt
http://www.justintalbot.com/2010/07/an-extension-of-wilkinson%E2%80%99s-algorithm-for-positioning-tick-labels-on-axes/
http://www.justintalbot.com/research/axis-labeling/

**Comment by mdboom** [comment]
Thanks for those links.  Indeed, quite interesting.
