### ISSUE TITLE
Don't interpolate images in RGB space

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5490]
We currently interpolate images by mapping the raw data into RGB, then interpolate that RGB (using any number of algorithms) to produce the final result.  This can result in colors that don't actually appear in the colormap to be in the final result.

![interpolation_methods](https://cloud.githubusercontent.com/assets/38294/11196877/b849c1f0-8c87-11e5-9833-cde1b872b1a7.png)

We should instead change the order of operations so that the interpolation happens on the raw data (in floating-point space), then the image is color mapped.

**Comment by mdboom** [comment]
I think I have the Agg part of this figured out.  See mdboom/aggravate

All that's left, then, is the Python side of things, and #5602 offers some guidance as to where to insert the floating-point interpolation operations.  Ideally, the `matplotlib._image.Image` class on the C++ side should go away.  It predates Numpy when we needed a class just to store the image data.  Now, a Numpy array will do, and it would be better to just have functions on the C++ side for interpolation and coloring.

**Comment by WeatherGod** [comment]
"aggravate"? You get a free beer from me at the next SciPy meeting!

On Wed, Dec 2, 2015 at 1:38 PM, Michael Droettboom <notifications@github.com

**Comment by mdboom** [comment]
Roget's says it's a synonym for "magnify".

**Comment by WeatherGod** [comment]
Yes, it works on so many levels. #wordsmith

On Wed, Dec 2, 2015 at 1:43 PM, Michael Droettboom <notifications@github.com

**Comment by tacaswell** [comment]
shiny!

**Comment by mdboom** [comment]
One advantage of rewriting the image interpolation as a purely functional interface is that it was really easy to add OpenMP support to take advantage of multiple cores.

**Comment by tacaswell** [comment]
It is not obviously to me which of those interplotaions is 'average all of the values that fall under this much larger pixel' (ex, coarse graining).

**Comment by mdboom** [comment]
> It is not obviously to me which of those interplotaions is 'average all of the values that fall under this much larger pixel' (ex, coarse graining).

The different filter kernels are essentially amount to weighted averages with different curves.
