### ISSUE TITLE
violin{,plot} return value 

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5497]
The docstring of `violin{,plot}` indicates that it returns a dict with keys `bodies`, `means`, `mins`, `maxes`, `bars`, `medians` (not necessarily all of them), but the keys are actually `bodies`, `cmeans`, `cmins`, `cmaxes`, `cbars`, `cmedians`.

**Comment by tacaswell** [comment]
Should probably update the docstring to match the code.
