### ISSUE TITLE
Labels' collisions while plotting named DataFrame iterrows

### ISSUE THREAD

**Issue by soupault** [matplotlib/matplotlib#5498]
Hi!

I have the following plotting code:

        for idx, signal in enumerate(LIST_OF_SIGNALS):
            df_ftrs_tmp = df_ftrs.copy()
            df_ftrs_tmp.index = encode_meta(df_ftrs_tmp)
            df_ftrs_tmp = df_ftrs_tmp.filter(like=signal)

            for df_tmp_idx, df_tmp in df_ftrs_tmp.iterrows():
                label = decode_meta(df_tmp_idx)

                axes[idx].errorbar(
                    list(range(5)),
                    df_tmp.filter(like='[median]'),
                    yerr=df_tmp.filter(like='[std]'),
                    capsize=3, marker='o',
                    color=colors[df_tmp_idx], label='txt{}'.format(df_tmp_idx))

The issue is when I'm trying to generate plots this way, legend gets 2 records for each `df_tmp_idx`.
If I cast `as_matrix()` on vectors (`y` and `yerr`) before plotting, everything works as expected.
So, I suppose the `Name`-field of dataframe row (`df_tmp` in this case) is being processed in any case and not correctly overwritten by `label=...` casting.

Here are the pictures representing issue:
Returned by example above:
![01](https://cloud.githubusercontent.com/assets/1315589/11209298/4df9630a-8d31-11e5-8ece-1237648e219c.PNG)
Returned by example with `.as_matrix()` applied on vectors:
![02](https://cloud.githubusercontent.com/assets/1315589/11209317/65cd207a-8d31-11e5-9463-ab8597ecf362.PNG)

Sorry for poorly prepared example, will rework it soon.

**Comment by jenshnielsen** [comment]
Looks to me like this is a duplicate of #5393 
@soupault can you check if that is the same issue?

**Comment by soupault** [comment]
@jenshnielsen looks pretty much the same.
Proposed by @tacaswell `barsabove=True` instead of `.as_matrix()` or any other tricks worked for me.
Thanks!

**Comment by jenshnielsen** [comment]
Great. Should be fixed in the next release
