### ISSUE TITLE
UnicodeDecodeError in IPython Notebook caused by negative numbers in plt.legend()

### ISSUE THREAD

**Issue by goulu** [matplotlib/matplotlib#5499]
Encountered a strange error shown in a small IPython Notebook here : https://gist.github.com/goulu/ba518d1a0a5267c0d3f3

in the method _repr_svg_  method that generates a svg plot for IPython Notebook ( 2.7 kernel )

    plt.legend()
    savefig(output, format='svg')

generates content like

     

for "-5" in the legend, which causes a UnicodeDecodeError in JSON via Jupyter client

**Comment by jenshnielsen** [comment]
The svg output contains unicode characters so that can't we written to a bytesIO object. Is there any reason that you cannot use a [StringIO object](https://docs.python.org/2.7/library/stringio.html#module-StringIO)

**Comment by goulu** [comment]
I used BytesIO because the same rendering method also generates png, but I'll definitely have a look at StringIO, thanks.

In the meantime I solved my problem by adding a .decode('utf-8') at the end of the _repr_svg_ method. Sorry for the noise ...
