### ISSUE TITLE
Confusing status bar values in presence of multiple axes

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5506]
Run

```
plt.plot([1, 2]); plt.twinx().plot([4, 3])
```

The xy values printed in the status bar are those of the twin axes (I guess because they were added last), which is somwhat confusing.  I'd suggest listing the coordinates in all overlaid axes systems instead.

**Comment by tacaswell** [comment]
Also see discussion at https://github.com/matplotlib/matplotlib/pull/2986  

The limitation is how the event handling system deals with over-lapping axes (which is to give the event to the top one and be done with it).

**Comment by anntzer** [comment]
Perhaps we should just reopen the old issue and close this one?

**Comment by kawing-chiu** [comment]
Is there a workaround for this at the moment? In my case, I have
```
ax1 = fig.add_subplot(211)
ax1t = ax1.twinx()
```
and I want the `y=<...>` in the status bar to show `ax1`'s y value instead of `ax1t`'s.

**Comment by WeatherGod** [comment]
Unfortunately, I don't think there is a workaround, except to flip around
which axes twins which, which probably isn't ideal.

**Comment by tacaswell** [comment]
See https://stackoverflow.com/questions/16672530/cursor-tracking-using-matplotlib-and-twinx/16672970#16672970 for a start on how to do this.

**Comment by anntzer** [comment]
Displaying the coordinates on all axes over which the mouse cursor is (https://github.com/matplotlib/matplotlib/pull/2986#issuecomment-42146048) still seems reasonable to me.
