### ISSUE TITLE
matplotlibrc.template is messy

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5509]
It's a weird disorganized mess with inconsistent indentation and commenting.

This should be cleaned up, but it might make sense to hold off until after the style changes go in, since it will see a _lot_ of changes during that time.

This is a reminder to do that cleanup (time permitting) before 2.0 release.

**Comment by tacaswell** [comment]
We probably should auto-generate the template from default rcparams dict at install time.  I think a bit of jinja / just format string will work (and then we can make sure it goes out alphabetical).

**Comment by mdboom** [comment]
:+1: to autogenerating.  I don't know if we want alphabetical though.  I think there needs to be some grouping of concepts.  We can always see how the alternatives play out.

**Comment by efiring** [comment]
Yes, conceptual grouping and ordering is essential.  It's gotten so huge it probably needs a table of contents.  And maybe some sort of help function dedicated to finding and explaining rcParams entries.  I tend to search through matplotlibrc.template, but I suspect most users don't know it exists.  Alternatively, at the command line I dump rcParams and use "less" to search for what I want.  Neither method is user-friendly.

**Comment by tacaswell** [comment]
We now treat the template as the ground truth of the default defaults so closing this.

It is still messy, but it is a messy we have to live with (baring a full overhaul of rcparams).
