### ISSUE TITLE
autoscale context manager

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5510]
Currently, {plt,Axes}.autoscale returns None.  Any thoughts on turning it into a context manager?

**Comment by mdboom** [comment]
I have no objections from an API point of view.

**Comment by tacaswell** [comment]
How can that be done in a back-compatible way?

**Comment by mdboom** [comment]
If the context manager takes effect in `__init__` rather than `__enter__` it will ways take effect, even if the caller does nothing with it (the current API).  The only difference would be to have the effect reverted in `__exit__`.

**Comment by tacaswell** [comment]
ah, cute!

**Comment by mdboom** [comment]
@anntzer: Were you offering to make a pull request?

**Comment by anntzer** [comment]
Perhaps in a few days.

**Comment by anntzer** [comment]
Closing due to https://github.com/matplotlib/matplotlib/pull/5538#issuecomment-294336178 (not realistically possible for now).
