### ISSUE TITLE
"interactive example" not working with PySide

### ISSUE THREAD

**Issue by titusjan** [matplotlib/matplotlib#5517]
I am running the [interactive example](http://matplotlib.org/faq/usage_faq.html#interactive-example) from the documentation using the Qt4Agg backend. That is, I run the following commands in a regular Python shell:
```python
    import matplotlib.pyplot as plt
    plt.ion()
    plt.plot([1.6, 2.7])
```
When I put `backend.qt4 : PyQt4` in my `.matplotlibrc` it works as expected. However, when I use `backend.qt4 : PySide` an empty, unresponsive window is shown.

After a bit of googling I am not so sure that the "interactive example" is supposed to work for alli interactive backends. Especially [this comment by efiring](https://github.com/matplotlib/matplotlib/issues/3052#issuecomment-44441047) indicates so. However this is in contradiction with the documentation.

Can you clarify this and/or update the documentation?

I am using OS-X 10.6.8, Python 2.7.10, Matplotlib 1.4.3, PySide 1.2.2 and PyQt 4.11.4.

**Comment by tacaswell** [comment]
Try in `IPython` after having run `%matplotlib qt`.

The issue is the bridge between the python repl event loop and the qt event loop.

**Comment by titusjan** [comment]
Yes, that works. I'm perfectly happy with using `ipython --matplotlib=qt` in the future but my issue is that the documentation is (likely) incorrect. Sorry if that wasn't clear.

In the [interactive example section](http://matplotlib.org/faq/usage_faq.html#interactive-example) it says: *"From an ordinary python prompt, or after invoking ipython with no options, try this: ..."*. It seems that this not always works. In the past I've often wondered what I did wrong and spend a lot of time with fruitless debugging.

**Comment by tacaswell** [comment]
Can you put in a PR that changes that to something more accurate?

**Comment by tacaswell** [comment]
The source for that section is at https://github.com/matplotlib/matplotlib/blob/master/doc/faq/usage_faq.rst  You can edit it and create the pull request directly from the browser.
