### ISSUE TITLE
The linestyle 'None',  ' ' and '' not supported by PathPatch.

### ISSUE THREAD

**Issue by Rezangyal** [matplotlib/matplotlib#5519]
The linestyle 'None',  ' ' and '' not supported by PathPatch.
Line2D support these values, but PathPatch not.

the documentation say, that these are acceptable values:
http://matplotlib.org/api/patches_api.html#matplotlib.patches.PathPatch

``` python
from matplotlib import pylab
from matplotlib.patches import PathPatch
from matplotlib.path import Path
pylab.plot([0,1,2], [4,5,6], ls='solid') #ok
pylab.plot([0,1,2], [3,4,5], ls='-') #ok
pylab.plot([0,1,2], [3,5,7], ls='None') #ok
pylab.gca().add_patch(PathPatch(Path([(3,0), (2,1)]), fill=False, ls='-')) #ok
pylab.gca().add_patch(PathPatch(Path([(3,1), (2,2)]), fill=False, ls='solid')) #ok
pylab.gca().add_patch(PathPatch(Path([(3,2), (2,3)]), fill=False, ls='None')) # !!! ERROR
pylab.show()
```

the exact error message:
 File "...\site-packages\matplotlib\backend_bases.py", line 1064, in set_linestyle
    raise ValueError('Unrecognized linestyle: %s' % str(style))
ValueError: Unrecognized linestyle: None

version: matplotlib 1.5.0

**Comment by WeatherGod** [comment]
I am betting that this is not a regression, but rather a crack in the API
when we attempted to merge the notations for linestyles for v1.5.

**Comment by Rezangyal** [comment]
as i see the these values handled in Line2D.draw() in the "if funcname != '_draw_nothing'" condition,
but in Patch.draw() no such functionality.

I think the solution in the Patch.draw():
```python
....
if self._edgecolor[3] == 0 or self._linestyle in {'none', 'None', ' ', ''}:
            lw = 0
else:
            gc.set_linestyle(self._linestyle)
.....
```

**Comment by WeatherGod** [comment]
Would you like to put together a PR with that proposed fix?

**Comment by phobson** [comment]
I think this can be closed per @5696

**Comment by QuLogic** [comment]
That PR is closed, not merged; is there a replacement?

**Comment by phobson** [comment]
@QuLogic. You're right, I got lost in the maze of references.
