### ISSUE TITLE
'nearest' interpolation not working with low dpi

### ISSUE THREAD

**Issue by christine-e-smit** [matplotlib/matplotlib#5520]
I am using matplotlib v 1.4.3 with Python 2.7.10 :: Anaconda 2.4.0 (64-bit).

In this script, I am creating a 7x7 pixel image from a 7x7 data matrics. I expect to see on pixel per data point, but that's not what I'm seeing. The data is an identity matrix, so I should see a one pixel diagonal line. Instead, I'm seeing an odd 2x2 pixel blob in the middle of the diagonal.
```python
#! /bin/env python

import numpy as np
import matplotlib.pylab as plt

if __name__ == "__main__":
    '''
    Simple script to create 7x7-pixel image with a diagnonal line.
    '''
    n = 7
    data = np.identity(n, float)

    # Create an nxn size figure with no frame
    fig = plt.figure(figsize=(n, n), frameon=False)

    # make the axes to the edge of the figure
    ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
    # turn the axes off
    ax.set_axis_off()
    # add the axes to this figure
    fig.add_axes(ax)
    # show the data. Don't do any interpolation.
    ax.imshow(data, interpolation='nearest', origin='lower',aspect='auto')
    # Save the figure at 1 dot per inch, which should mean 1 data point per
    # pixel
    fig.savefig("image.png", dpi=1)
```
Here is the image, which is obviously teeny tiny. You can see the issue if you open it in something like gimp, which lets you zoom in: ![image](https://cloud.githubusercontent.com/assets/14983768/11281748/d8269502-8ef3-11e5-8f6b-54d81b2a3196.png)

**Comment by rougier** [comment]
Just adding a zoom of the image above.

![image](https://cloud.githubusercontent.com/assets/327203/11283034/d94f47ee-8f02-11e5-80e3-225ba1561592.png)

**Comment by tacaswell** [comment]
possibly related to https://github.com/matplotlib/matplotlib/pull/4406 / https://github.com/matplotlib/matplotlib/issues/4280
