### ISSUE TITLE
axhline fails on custom scale example

### ISSUE THREAD

**Issue by jeffrey-hokanson** [matplotlib/matplotlib#5522]
I am using the matplotlib demo [custom_scale_example.py](http://matplotlib.org/1.5.0/examples/api/custom_scale_example.html) as a starting point for my own custom scale.  When I try to add a vertical line or horizontal line to an axis using the demo scaling using [matplotlib.axes.Axes.axhline](http://matplotlib.org/api/axes_api.html?highlight=axhline#matplotlib.axes.Axes.axhline), I get the following error message

    ValueError: It is not possible to compute transA - transB since transB cannot be inverted and there is no shortcut possible.

Here is [gist reproducing this behavior](https://gist.github.com/jeffrey-hokanson/aa21f18825d307221b4a).  

This bug is similar #1246.

**Comment by tacaswell** [comment]
I think you need to implement an inverse method on your scale.

**Comment by jeffrey-hokanson** [comment]
Both of the `MercatorLatitudeTransform` and `InvertedMercatorLatitudeTransform` implement the `inverted` method.  This is analogous to how `LogScale` is implemented in `matplotlib/lib/matplotlib/scale.py`.  Is there another inverse method that needs to implemented?

**Comment by tacaswell** [comment]
It looks like the code in `transform.py` consults the attribute `has_inverse` to determine if the transform is invertable.  If add a class-level attrbitute of 

```
has_inverse = True
```

to both of the transfrom classes it will work

```diff
$ diff scale2.py scale.py -u
--- scale2.py	2015-11-20 11:42:34.415172874 -0500
+++ scale.py	2015-11-20 11:40:20.807021549 -0500
@@ -96,6 +96,7 @@
         input_dims = 1
         output_dims = 1
         is_separable = True
+        has_inverse = True
 
         def __init__(self, thresh):
             mtransforms.Transform.__init__(self)
@@ -131,6 +132,7 @@
         input_dims = 1
         output_dims = 1
         is_separable = True
+        has_inverse = True
 
         def __init__(self, thresh):
             mtransforms.Transform.__init__(self)

```

![so](https://cloud.githubusercontent.com/assets/199813/11305639/b173ed8c-8f7b-11e5-926f-45d53db0d143.png)


Can you put in a PR updating the example as well?

**Comment by jeffrey-hokanson** [comment]
Yep, that seems to fix it.  I've created a [pull request](https://github.com/matplotlib/matplotlib/pull/5533).  I can create a unit test later this afternoon if you'd like.

**Comment by tacaswell** [comment]
We don't really test the examples except via smoke testing.
