### ISSUE TITLE
Change in colorbar extensions

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5524]
In #5307, where I am lowering our testing tolerance down to zero, I am discovering a few recent changes that slipped through because the tolerance on our tests was too high.

In particular 8928311cc833ffa386344445709bcaa8e4b95243 introduced the following change in `test_axes:test_contour_colorbar`.

Current baseline image:

![contour_colorbar-expected](https://cloud.githubusercontent.com/assets/38294/11286720/970383aa-8ee4-11e5-86ac-0eebe9846c4f.png)

Current behavior after 8928311cc833ffa386344445709bcaa8e4b95243:

![contour_colorbar](https://cloud.githubusercontent.com/assets/38294/11286724/a5486cd2-8ee4-11e5-9649-bf6818b36bda.png)

The test code:

```
@image_comparison(baseline_images=['contour_colorbar'])
def test_contour_colorbar():
    x, y, z = contour_dat()

    fig = plt.figure()
    ax = fig.add_subplot(111)
    cs = ax.contourf(x, y, z, levels=np.arange(-1.8, 1.801, 0.2),
                     cmap=plt.get_cmap('RdBu'),
                     vmin=-0.6,
                     vmax=0.6,
                     extend='both')
    cs1 = ax.contour(x, y, z, levels=np.arange(-2.2, -0.599, 0.2),
                     colors=['y'],
                     linestyles='solid',
                     linewidths=2)
    cs2 = ax.contour(x, y, z, levels=np.arange(0.6, 2.2, 0.2),
                     colors=['c'],
                     linewidths=2)
    cbar = fig.colorbar(cs, ax=ax)
    cbar.add_lines(cs1)
    cbar.add_lines(cs2, erase=False)
```

@efiring: Do you know if this change was intentional?

**Comment by efiring** [comment]
Not intentional.  The problem is that contour is using np.inf and -np.inf as added levels with 'extend' in `_process_levels()`. The simple solution is to use something like 1e300 and -1e300 instead.

**Comment by mdboom** [comment]
#5546 is a solution based directly on @efiring's suggestion.

**Comment by tacaswell** [comment]
Wait, what did I do?

**Comment by mdboom** [comment]
I think this was a merging snafu (my fault).  This was a commit that we later reverted, but it's still in there and when it was merged up closed this issue again.
