### ISSUE TITLE
Radar Chart does not allow having different scales for each axis

### ISSUE THREAD

**Issue by ankur-gupta** [matplotlib/matplotlib#5527]
I have a use case in which each axis (eg: Sulfate, Nitrate in this [example](http://matplotlib.org/1.5.0/examples/api/radar_chart.html)) has a different scale. I don't see an easy way to do this. It looks like RadarAxes is based on PolarAxes which fundamentally uses the same scale for x and y dimensions. 

I am new to Python and to me it looks like a new RadarAxes projection can be written from scratch (i.e. not based on PolarAxes) which could allow this. 

What do you think ?

**Comment by tacaswell** [comment]
Sorting out a general way to do plotting in a figure between different `axis` objects is something we should probably do.  This relates back to the 'spark line' (maybe have the name wrong) code that @phobson has, but rotated so that the axis spines are radial instead of lined up.

**Comment by mdboom** [comment]
#4699 is adding a lot of improvements to polar plots.  Perhaps that could be addressed there or @QuLogic has some ideas having been digging around there a lot lately.

**Comment by phobson** [comment]
@tacaswell  are you referring to this: http://stackoverflow.com/questions/15167928/implementing-horizon-charts-in-matplotlib?

**Comment by tacaswell** [comment]
No it was something with many y axis with lines connecting them what was
used to show rough correlations between high dimensional data points.

**Comment by phobson** [comment]
oh oh oh ... this: https://gist.github.com/phobson/9de120cabde660ec734c

By the way -- this turns into a dumpster file if you try to use log scales.

**Comment by ankur-gupta** [comment]
@phobson This plot is much better than a radar chart for my use. Thanks.

**Comment by mdboom** [comment]
Great stuff all...  I guess the question is whether we want to keep this open.  The subject line of this issue is still true, however, multiple r scales on a polar plot is hard to display effectively...

**Comment by tacaswell** [comment]
At a minimum @phobson 's demo code should end up in the examples.

**Comment by phobson** [comment]
I can take a stab at removing the seaborn and pandas dependencies of the example over the holiday.

**Comment by anntzer** [comment]
I'll ambitiously close this as parallel coordinates plots (PCP) are present in pandas (https://pandas.pydata.org/pandas-docs/version/0.21.0/visualization.html#parallel-coordinates) and I think the original request (later noted as likely worse than a PCP) was to allow radar charts with different scales on each and every coordinates (not just switching r to log), which seems way more complex than #24825 and should probably first be made as a third party library, if anything.
