### ISSUE TITLE
$\rho$ in text for plots erroring

### ISSUE THREAD

**Issue by lheagy** [matplotlib/matplotlib#5528]
It looks like the symbol $\rho$ is not being recognized

```
import numpy as np
import matplotlib.pyplot as plt

# this works
plt.plot(np.random.rand(5))
plt.title('$\sigma$')
plt.show()

# this errors 
plt.plot(np.random.rand(5))
plt.title('$\rho$')
plt.show()
```
[mpl_rho_err.txt](https://github.com/matplotlib/matplotlib/files/39782/mpl_rho_err.txt)

**Comment by jenshnielsen** [comment]
The problem is that \r is a control character in python. Try doing the following in a python shell and you will see what happens:

```python
>>> a = '$\rho$'
>>> print(a)
ho$
```

The solution is to either escape the \ or use a raw string

```python
>>> a = '$\\rho$'
>>> print(a)
$\rho$
>>> a = r'$\rho$'
>>> print(a)
$\rho$
```
