### ISSUE TITLE
Wrong image/code for legend_demo (pylab)

### ISSUE THREAD

**Issue by hrjn** [matplotlib/matplotlib#5529]
As it is presented [here](http://matplotlib.org/examples/pylab_examples/legend_demo.html), the figure titled 'damped oscillation' does not fit with the corresponding code, which gives another result : 
![alt text](http://i.imgur.com/Ik1LjuC.png "?")

**Comment by jenshnielsen** [comment]
That example should actually have been deleted. It is not referred to from the index but the files where not deleted when a new version of the documentation was copied on top of the old one.

The matching examples are http://matplotlib.org/examples/api/legend_demo.html and http://matplotlib.org/examples/pylab_examples/legend_demo2.html 

Looks like there is a number of leftover files in the docs which should be deleted. 
In https://github.com/matplotlib/matplotlib.github.com/tree/master/examples/pylab_examples

**Comment by tacaswell** [comment]
Sorry, this is my mistake.  I have been being lazy/sloppy and just copying the new 'top level' docs ontop of the existing ones assuming any updated files would just be re-written and the old ones would not cause any harm.  

There are a bunch of non-autogenerated files in the documentation repo that need to be cleaned out.
