### ISSUE TITLE
test_axes:test_rc_grid image comparison test has always been broken

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5535]
In #5307, where I am lowering our testing tolerance down to zero, I am discovering a few recent changes that slipped through because the tolerance on our tests was too high.

As it turns out the `test_axes:test_rc_grid` test has always been broken since it was first added in 94d044e5fb45.

BASELINE IMAGE:

![rc_grid-expected](https://cloud.githubusercontent.com/assets/38294/11308141/7e3264b2-8f8a-11e5-8122-25ea9a0f0a40.png)

ACTUAL RESULT:

![rc_grid](https://cloud.githubusercontent.com/assets/38294/11308145/866e3e62-8f8a-11e5-8aab-6e890ad7e880.png)

@olgabot: Any thoughts about what might be up here?

**Comment by QuLogic** [comment]
Axes grids are disabled by default. The overriding `dict`s need to also contain `axes.grid: True`.
