### ISSUE TITLE
xlabel, ylabel forgets default values

### ISSUE THREAD

**Issue by mdehoon** [matplotlib/matplotlib#5540]
``` python
>>> import matplotlib
>>> matplotlib.use("tkagg")
>>> from pylab import *
>>> xlabel("text", fontsize=40)
>>> xlabel("text")
```

results in a label with font size 40, instead of the default font size for xlabel. The same problem appears with ylabel. With title, there is no bug:

``` python
>>> title("text", fontsize=40)
>>> title("text")
```

results in a title with the default font size (i.e. not a font size of 40).

**Comment by tacaswell** [comment]
It is not clear to me that the bug isn't with title and that font properties should persist.

**Comment by mdehoon** [comment]
Right now matplotlib is inconsistent: xlabel, ylabel, xticks, yticks have persistent font properties; title, legend, and text do not use persistent font properties. To me persistent font properties are unpythonic; I don't know of other examples in Python where the arguments of a function call are being interpreted differently depending on its usage history.
The pythonic way for persistent properties would be
```python
>>> label = xlabel("My label", fontsize=20)
>>> label.set_text("Some other label")
```
Then we are explicitly changing the text of the label only.
The other oddity is that to get the default font size back, one would have to use
```python
>>> xlabel("Some other label", fontsize=None)
```
though intuitively I would expect fontsize=None if fontsize is not specified.
Finally, the current convention for xlabel etc. does not agree with the documentation.

**Comment by efiring** [comment]
I agree with @mdehoon on this.  It looks like a deep-seated historical accident in the implementation.  Following the chain of calls, the action is in axis.py:
```python
    def set_label_text(self, label, fontdict=None, **kwargs):
        """  Sets the text value of the axis label

        ACCEPTS: A string value for the label
        """
        self.isDefault_label = False
        self.label.set_text(label)
        if fontdict is not None:
            self.label.update(fontdict)
        self.label.update(kwargs)
        self.stale = True
        return self.label
```
Kwargs are only used to update whatever values are already in place.

**Comment by mdboom** [comment]
Maybe we fix this behavior for 2.0?

**Comment by efiring** [comment]
It's a major behavioral change that could break user code, so if it's not 2.0 then I suppose it would have to be 3.0.

**Comment by tacaswell** [comment]
I would like to hold the line on 2.0 being style change only.

**Comment by mdboom** [comment]
One could argue this is a style change -- it changes how matplotlib reacts to font size requests...  But it could be argued either way.  (And too late on holding the line to style changes only :wink: -- the style changes themselves have already revealed a number of places where behavior changes were necessary to support them ;)

**Comment by WeatherGod** [comment]
I'd have to agree with @tacaswell here. This is a long-standing behavior
and it isn't really a bug per-se, just an inconsistency. We should document
it well and consider it for fixing in 3.0 one way or another. Maybe even
document that the behavior might change in the future?

**Comment by mdehoon** [comment]
I'm OK with fixing it in 3.0.
