### ISSUE TITLE
EllipseCollection renders incorrectly when passed a sequence of widths

### ISSUE THREAD

**Issue by apodemus** [matplotlib/matplotlib#5545]
The code below illustrates the issue:

```python
import matplotlib.pyplot as plt
from matplotlib.collections import EllipseCollection

fig, ax = plt.subplots( )

widths, heights, angles = 10, 10, 0
coords = [(10,10),(15,15)]
e = EllipseCollection( widths, heights, angles,
                        units='xy', 
                        offsets=coords, 
                        transOffset=ax.transData )

ax.add_collection( e )

ax.set_xlim( 0, 30 )
ax.set_ylim( 0, 30 )`
```

Produces 
![ellipses1](https://cloud.githubusercontent.com/assets/5623552/11331711/e1192366-91c6-11e5-8b47-1ed26d9994fd.png)
as expected.

However, changing `widths=10,10` produces the following.
![ellipses2](https://cloud.githubusercontent.com/assets/5623552/11331854/bd8de240-91c8-11e5-93ba-4c517e299d2c.png)
Here the sizes are not transformed to the 'xy' units as expected.

The same thing happens when changing any of the other cyclable properties. eg:  `facecolor = 'rg'`

The second case:  `widths=10,10`  works as expected in 1.4.3, producing the first figure.  I've tried to locate the issue in source, but I'm not familiar enough with the code to pinpoint exactly what is going wrong.

PS: I'm using the EllipseCollection as a base class to create a interactive tool for reducing astronomical image data here: https://github.com/apodemus/obstools/blob/master/ApertureCollections.py

**Comment by mdboom** [comment]
`git bisect` says first bad commit is ba4016014cb4fb4927e36ce8ea429fed47dcb787
