### ISSUE TITLE
Cropping text to axes

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5554]
After `text(-.01, -.01, "foo")`, the text is drawn on top of the axes.
An option to crop the text to the axes limits would be welcome.  At least, changing the zorder doesn't seem to be enough.

**Comment by mdboom** [comment]
Does

```
text.set_clip_path(ax.patch)
```

work?

**Comment by tacaswell** [comment]
By default the `Text` object returned by `ax.text` has clipping disabled, turn in on via:

```python
txt =  ax.text(.7, .7, 'very long string' * 50, clip_on=True)
```

or

```python
txt.set_clip_on(True)
```

**Comment by anntzer** [comment]
Sorry for the spam.

A general suggestion: would it be possible, whenever a docstring of a pyplot function states something like
```
    kwargs : `~matplotlib.text.Text` properties.
        Other miscellaneous text parameters.
```
(from `pyplot.text`) to actually fill in the list of properties?  (I guess I just self-assigned that project.)

**Comment by gepcel** [comment]
Agree with @anntzer . For someone not an expert with matplotlib, I have to dig deep into the help file to set maybe just a font size. Many times I just don't know there such a parameter, or can't spell the parameter correctly.
Probably too late to suggest.
