### ISSUE TITLE
Setting window titles when in interactive mode

### ISSUE THREAD

**Issue by lilynguyen** [matplotlib/matplotlib#5559]
Perhaps it's only a version issue that you cannot set a window title (fig.canvas.set_window_title('title')) for a figure when it's in interactive mode. I'm currently working with LeapMotion which right now can only work with in python v2.7 and mpl v1.4.3 which co-depends on numpy v1.6.1. I have tried newer versions of both numpy and mpl and it doesn't like python 2.7 and LeapMotion, both of which are necessary.

Is there a workaround for this or do I have to settle for "Figure1?"
It's not the end of the world, of course, but it's a nice customization!

edit:
not an interactive mode issue. still exploring the actual issue. sorry for the wasted issue!

**Comment by tacaswell** [comment]
You can also pass a string into the figure creation code (I think that shipped in 1.4.x)

**Comment by lilynguyen** [comment]
Do you mean `fig = plt.figure(figsize=(8,6),'title')`?

**Comment by tacaswell** [comment]
See http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.figure
`num` is badly named (but we can not change it for back-compatibilty
reasons.

`fig = plt.figure('my fancy fig', ...)` should work.

**Comment by lilynguyen** [comment]
Wow I totally just skipped over the desc of that arg - thought it could only take ints. 
Currently I have `self.fig = plt.figure('signum', figsize=(15,10), facecolor='black', tight_layout=True)`
'signum' being the name of the game I'm trying to create. Unfortunately this still doesn't work with that I'm working with - still says 'Figure1'. :(
Is this affected by the fact that this is all in a class?
Or that I'm adding a few subplots to `self.fig`?

**Comment by WeatherGod** [comment]
Which backend? I think some backends don't implement title setting
correctly.

**Comment by lilynguyen** [comment]
> Which backend? I think some backends don't implement title setting
> correctly.

What do you mean which backend?
If it means anything both `fig.canvas.set_window_title` and the `num` argument work when I'm doing simple plotting for mpl. Seems to be integration with LeapMotion that is doing it in unfortunately.

**Comment by rvalenzuelar** [comment]
Is this issue still open? I have the same problem when trying to use `fig.canvas.set_window_title`. I'm using Qt5Agg backend.

**Comment by tacaswell** [comment]
@rvalenzuelar Please open a new issue.
