### ISSUE TITLE
Explicit vs. implict figure construction with plt.matshow, plt.hist, etc.

### ISSUE THREAD

**Issue by jakirkham** [matplotlib/matplotlib#5564]
Trying to plot a histogram in the notebook using the `notebook` or `nbagg` backend does not display anything.

**Comment by jenshnielsen** [comment]
It definitely works for me for instance here https://gist.github.com/jenshnielsen/20d9bf3fa40b309ad865

You will have to provide a more full example of what you are trying to do to figure out what is wrong in your setup

**Comment by tacaswell** [comment]
As a side note, you can try any notebook examples on tmpnb.org (which has mpl 1.4.3 installed).

**Comment by jakirkham** [comment]
Sorry, not sure why it was giving me issues. Can't seem to reproduce it now.

**Comment by jakirkham** [comment]
I think the problem is two figures are getting combined together.

**Comment by tacaswell** [comment]
`notebook` behaves like normal gui figures (that is they are mutable and which one is current matters) rather than like `inline` figures (which are throw-away per cell).

**Comment by jakirkham** [comment]
Here's a gist of what I was doing that caused me issues ( https://gist.github.com/jakirkham/c6d5c515b8c7009dfbc7 ).

**Comment by jakirkham** [comment]
So, what I am confused by is multiple `matshow`'s don't seem to have this issue though.

**Comment by tacaswell** [comment]
That looks like correct behavior.  I suspect what is happening is that the multiple `matshows` are over plotting each other (which looks ok).  In this case you are plotting the histogram on top of the image, but as part of imshow/matshow the aspect is set to `equal'` which results in the figure you are getting.

If you want a new figure, throw a `fig, ax = plt.subplots()` in.

**Comment by jakirkham** [comment]
> I suspect what is happening is that the multiple matshows are over plotting each other (which looks ok).

Actually, that does not seem to be the case. Each matshow is creating a new figure each time. My main complaint is there isn't consistency here. If we are going to create a new figure each time, let's do that. If not, let's not do that.

**Comment by jakirkham** [comment]
Also, if we are going to replot on the old figure, could it at least be resized in some way so that one gets a graph that makes sense?

**Comment by jenshnielsen** [comment]
It's possible that the behaviour could be improved but this is not specific to the notebook backend. If you do the same in a ipython shell with the qt backend you get the same behaviour. I have not looking into why matshow closes the existing figure and creates a new where hist re uses the existing one. 

Personally I prefer the object oriented backend which makes this more explicit. I would do something like this https://gist.github.com/jenshnielsen/336f28fe846660917d12

**Comment by jenshnielsen** [comment]
It looks like this is actually more of a bug in plt.matshow which looks like this:
```python
def matshow(A, fignum=None, **kw):
    A = np.asanyarray(A)
    if fignum is False or fignum is 0:
        ax = gca()
    else:
        # Extract actual aspect ratio of array and make appropriately sized figure
        fig = figure(fignum, figsize=figaspect(A))
        ax  = fig.add_axes([0.15, 0.09, 0.775, 0.775])

    im = ax.matshow(A, **kw)
    sci(im)

    return im
```

default fignum is None but the code checks for False or fignum=0 before trying to get the current figure.

**Comment by jenshnielsen** [comment]
Neither does any of the other plot methods in pyplot. I think we need to at least make this consistent

**Comment by jakirkham** [comment]
Is `plt.imshow` doing the same thing?

**Comment by efiring** [comment]
No, matshow is a special case--a very old and rather odd function.

**Comment by jakirkham** [comment]
Oh sorry, I see that @jenshnielsen had already said that.

**Comment by QuLogic** [comment]
I'm not sure there's anything to do here. `matshow` appears to be working as intended; its docs say:

> Display an array as a matrix in a new figure window.

the key word there being **new**.
