### ISSUE TITLE
Latin Modern support?

### ISSUE THREAD

**Issue by chernals** [matplotlib/matplotlib#5568]
Is there a way to set the fonts to Latin Modern?
I'm not a TeX expert and don't know if I'm missing something or if the support is missing.
I want to be able to set the same fonts as my Latex documents that use the class `memoir` (which uses Latin Modern by default).

**Comment by zblz** [comment]
I you want to ensure consistency with the Latex document, the best way is to set the `text.usetex` parameter to True. You can then control the exact packages you want loaded into each of the TeX calls with the `text.latex.preamble` parameter, so something like the following should load Latin Modern everywhere (without the preamble you would get Computer Modern):

```
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True
plt.rcParams['text.latex.preamble'] = [r'\usepackage{lmodern}']
```

If you *really* want consistency in the text, use the pgf backend of matplotlib and the text will be rendered by Latex at compile time.

**Comment by chernals** [comment]
Thanks that's what I'm doing. I also wonder if lmodern could be "supported" through the usual font selection parameters of mpl: different usepackage are already there, lmodern could be added as well. Does that make sense?

**Comment by pwuertz** [comment]
Please note that you can install Latin Modern as OpenType Font (http://www.gust.org.pl/projects/e-foundry/latin-modern). Then you can use it in any application that is aware of the OS fonts (including matplotlib).

**Comment by anntzer** [comment]
Assuming that lmodern is installed in your system (typically under the name "lmroman10-regular.otf" or similar), you can use
```
rcParams["font.family"] = ["Latin Modern Roman"]
```
which is indeed the usual font selection mechanism (note that the name can be queried (if you have fontconfig installed, ie likely on Linux and perhaps on OSX) using `fc-query /path/to/lmroman10-regular.otf` (it's the "family" field)).

I believe this is sufficient to close the issue, feel free to request more information though.
