### ISSUE TITLE
Stackplot does not handle NaNs

### ISSUE THREAD

**Issue by kbrose** [matplotlib/matplotlib#5569]
Stackplot does handle NaN's gracefully. A NaN in the array to plot causes all down-stream values to also not be plotted. Consider the following example:

```python
import pylab as plt
import numpy as np
plt.figure()
plt.gca().stackplot([0, 1, 2, 3, 4], [[1, 2, 3, 4, 5], [5, 4, np.nan, 2, 1], [1, 1, 1, 1, 1]])
```

The figure is displayed as 

![figure_1](https://cloud.githubusercontent.com/assets/4053170/11434647/49aede4a-9495-11e5-8f1b-c00fa363da53.png)

Notice that the value `3` is plotted at index 2, but the value `1` is not. I think the most intuitive behavior would be to treat NaNs as zeros ("Possible fix 1" below). Alternatively, every value at an index that has a NaN value should be treated as missing ("Possible fix 2" below). Either way, I think plotting some of the values but not others based on ordering is unintuitive and should be changed.

Possible fix 1:

![figure_2](https://cloud.githubusercontent.com/assets/4053170/11434683/ee821428-9495-11e5-93dc-5c98f67d12a0.png)

Possible fix 2:

![figure_3](https://cloud.githubusercontent.com/assets/4053170/11434691/00ec0e20-9496-11e5-93cd-d18d1d98c323.png)

**Comment by efiring** [comment]
I don't think option 1 is a good idea, because NaN and zero are very different and should not be rendered as if they were the same.
Actually, I think the present behavior makes good sense.  It correctly shows that there is a gap in the second series.  If you *want* the NaN to be replaced by zero, you can make the replacement before supplying the arguments.  Similarly, if you want option 2, you can get it by manipulation of the input arguments.

**Comment by kbrose** [comment]
The current way definitely makes sense based on the math behind the stack plot (just doing a cumsum, which the NaN will infect for all sequences after it). the part that bothers me is that the sequences which are *not* NaN will sometimes be displayed and sometimes not based only on their ordering with respect to the NaN value. This just seems wrong to me, but perhaps others do not feel as I do.

A third option would be more in line with what I envisioned with my previous option 1. It is still internally replaced with 0 but in a way that makes it more clear that the value is actually missing and not just 0:

![figure_4](https://cloud.githubusercontent.com/assets/4053170/11444870/2182bc40-94ed-11e5-8c4c-45a5ca3ec6e8.png)

(Generated with `plt.gca().stackplot([0, 1, 1, 2, 3, 3, 4], [[1, 2, 2, 3, 4, 4, 5], [5, 4, 0, 0, 0, 2, 1], [1, 1, 1, 1, 1, 1, 1]])`)

Thoughts?

**Comment by efiring** [comment]
Better then your earlier alternatives, but is it worth the extra complexity to get this behavior?  And is this behavior what one would expect in general?  In the simple case here, with very few points, it makes the situation quite clear, but with many points it would not be so visually obvious.
In other words, I still don't see a rationale for changing the present behavior.
