### ISSUE TITLE
Finish reorganizing examples

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5571]
The `pylab` and `api` subdirectories are still basically unorganized blobs of stuff (some of which are more like unit tests than examples).  It would be nice to finish the organization for 2.0.

**Comment by anntzer** [comment]
examples/pylab is no more, but there are still quite a few entries in examples/api.

**Comment by dstansby** [comment]
I banished `examples/api` a while ago, so closing.
