### ISSUE TITLE
Support HiDPI (retina) displays in docs

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5573]
For 2.0, it would be nice to show off the new styles in the docs by having proper hi-resolution image support.

It may be that using SVG by default is now sufficient, since browser support for SVG has come a long way since we first put together the docs.  Alternatively, we can provide images at twice the current resolution, scaled down (which probably won't look as good on traditional low-DPI displays).

**Comment by Tillsten** [comment]
+1 for svg, would also solve #5097
