### ISSUE TITLE
Improper reliance upon pkg-config when C_INCLUDE_PATH is set

### ISSUE THREAD

**Issue by dpryan79** [matplotlib/matplotlib#5576]
In `setupext.py`, matplotlib uses `pkg-config --cflags --libs freetype2` to [determine where `ft2build.h` can be found](https://github.com/matplotlib/matplotlib/blob/master/setupext.py#L922-L924). That works well enough *except* when that path is already set in either the `C_INCLUDE_PATH` or `CPLUS_INCLUDE_PATH` environment variables. If the path is in one of those then pkg-config will not return the appropriate `-I/something` option and compilation will fail (i.e., setupext.py will mark freetype2 as being absent, even though it's not). `pkg-config` is behaving correctly, since gcc/clang/etc. check these environment variables.

Would it be possible to have `_check_for_pkg_config` also check these environment variables. That would solve some [issues on Galaxy](https://github.com/galaxyproject/tools-iuc/issues/417).

**Comment by mdboom** [comment]
See #5578 for a solution.  I think it makes sense to only look at CPLUS_INCLUDE_PATH, since all of matplotlib's code is C++ (with the exception of the macosx extension), and gcc doesn't seem to look at C_INCLUDE_PATH when in C++ mode (so neither should we).

**Comment by dpryan79** [comment]
Seems quite reasonable. :+1:
