### ISSUE TITLE
Problem with _init_func in ArtistAnimation 

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5592]
Found by @tomoemon in #5508

I found another problem within animation.py while testing on master branch.

The commit 728db55 has modified Animation.save method, but _init_func is not a member of Animation. So saving the ArtistAnimation raises an exception.

/home/tomoemon/project/matplotlib/.py27/lib/python2.7/site-packages/matplotlib-1.5.0+481.g6245d4e.dirty-py2.7-linux-x86_64.egg/matplotlib/animation.pyc in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
    777             for anim in all_anim:
    778                 # Clear the initial frame
--> 779                 if anim._init_func:
    780                     anim._init_draw()
    781             for data in zip(*[a.new_saved_frame_seq()

AttributeError: 'ArtistAnimation' object has no attribute '_init_func'
Anyway I try to create a PR for base64 issue. (The above problem is too confusing for me for now)

**Comment by thisch** [comment]
I've just encountered the same issue.

**Comment by QuLogic** [comment]
Fixed by #5740.
