### ISSUE TITLE
Quiverkey() positions arrow incorrectly with labelpos 'N' or 'S'

### ISSUE THREAD

**Issue by EdwinChan** [matplotlib/matplotlib#5613]
The documentation for `quiverkey()` in versions 1.3 through 1.5 states that

> If *labelpos* is 'N' or 'S', *X*, *Y* give the position of the middle of the key arrow.

This guarantee is clearly violated in version 1.5:

![quiver_1 4 3](https://cloud.githubusercontent.com/assets/906137/11569778/b3f8ee5e-99c1-11e5-804a-1cfebd8ebc5d.png)
![quiver_1 5 0](https://cloud.githubusercontent.com/assets/906137/11569782/b653cf0c-99c1-11e5-9082-3bdd125e737f.png)
![quiver_1 5 0 548 g9230cac](https://cloud.githubusercontent.com/assets/906137/11569783/b7907b72-99c1-11e5-8168-616b3e107b6f.png)

The script that generated these figures is

    import numpy
    import matplotlib
    from matplotlib import pyplot

    plot = pyplot.quiver(*numpy.random.rand(2, 10, 10))
    pyplot.xlim(-2, 12)
    pyplot.ylim(-2, 12)
    pyplot.quiverkey(plot, 0.5, 1, 1, 'N', labelpos='N')
    pyplot.quiverkey(plot, 1, 0.5, 1, 'E', labelpos='E')
    pyplot.quiverkey(plot, 0.5, 0, 1, 'S', labelpos='S')
    pyplot.quiverkey(plot, 0, 0.5, 1, 'W', labelpos='W')
    pyplot.annotate(matplotlib.__version__, (0, 0), (-1, 11), 'data', 'data',
      ha='left')
    pyplot.savefig('quiver_{}.png'.format(matplotlib.__version__))

**Comment by efiring** [comment]
I see what happened (in #3955), and it's easy to fix.  I can do it today or tomorrow. Thanks for the report, @EdwinChan.  Your script will inspire a test.

**Comment by tacaswell** [comment]
I do not see how I broke this :disappointed:

**Comment by efiring** [comment]
@tacaswell,  You normalized to "middle", but quiverkey is still using "mid" and is not going through the normalization (and indeed, it shouldn't need to).   So I will either change the normalization to "mid", or change quiverkey to request "middle".

**Comment by tacaswell** [comment]
Ah, I see.  I can clean up my mess if you would like.

**Comment by efiring** [comment]
OK, thanks.
