### ISSUE TITLE
Better error message if no animation writer is available

### ISSUE THREAD

**Issue by JanSchulz** [matplotlib/matplotlib#5616]
You have to set one *before* importing animation:

```
# Must be set before the animation import
mpl.rcParams['animation.ffmpeg_path'] = "C:\\Users\\jschulz\\Dropbox\\Programme\\cmder\\vendor\\jasc\\ffmpeg.exe"
import matplotlib.animation as animation
```

Without:

```
C:\portabel\miniconda\envs\katins2\lib\site-packages\matplotlib\animation.py:781: UserWarning: MovieWriter ffmpeg unavailable
  warnings.warn("MovieWriter %s unavailable" % writer)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-2c23ec3f11d2> in <module>()
     25 
     26 ani = animation.FuncAnimation(plt.gcf(), updatefig, frames=40, init_func=initfig)
---> 27 ani.save('_movie.mp4')

C:\portabel\miniconda\envs\katins2\lib\site-packages\matplotlib\animation.pyc in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
    786                                                         metadata=metadata)
    787                 except IndexError:
--> 788                     raise ValueError("Cannot save animation: no writers are "
    789                                      "available. Please install mencoder or "
    790                                      "ffmpeg to save animations.")

ValueError: Cannot save animation: no writers are available. Please install mencoder or ffmpeg to save animations.
```

This runtime error should give that information: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/animation.py#L788

**Comment by tacaswell** [comment]
The registration code should be user re-triggerable as well.

**Comment by JanSchulz** [comment]
Is there a way to register a retrigger by setting a rcParam value?

**Comment by JanSchulz** [comment]
ok, found a way to do that via the validation code... Will submit a PR...

**Comment by JanSchulz** [comment]
Ok, my solution has a problem: The validation happens before the value is assigned, so calling the animation code there isn't going to trigger a new result. I see a few ways to solve this:

* make validation function return a tupple `(new_validated_val, func_after_setting)`, which the `rcParam` objects calls after setting the value
* add a `func_after_setting` to the list of rcparam setup values, so if that's not None, call it after setting
* add a `dirty` state to the writer registry and make it re-setup when it's dirty.

If you don't have any other idea, I would go with the last idea as this seems to be the least invasive one.
