### ISSUE TITLE
Symlog linear region

### ISSUE THREAD

**Issue by julietbravo** [matplotlib/matplotlib#5619]
I recently posted [this](http://stackoverflow.com/questions/33935758/matplotlib-symlog-linear-region) question on SO, about what I believe is an incorrect behavior of setting `{x/y}scale('symlog')` in combination with a `linthres{x/y}`. For example:

```python
import numpy as np
import matplotlib.pylab as pl

z = np.linspace(0,1,100)
x = np.ones_like(z)
x[0] = 0

pl.figure()
pl.plot(x, z, '-')
pl.yscale('symlog', linthresy=1e-2)
pl.xlim(-0.1,1.1)
```

Produces the image shown below. I would expect a linear region from 0 to 1e-2, and a log region containing 1e-2, 1e-1, 1. Why isn't this happening? Is this a bug?

![figure_1](https://cloud.githubusercontent.com/assets/1067637/11598924/e2584746-9ac4-11e5-91dd-33d5c7e91150.png)

**Comment by tacaswell** [comment]
Please copy the relevant examples here, SO is not a stable link target.

**Comment by julietbravo** [comment]
Copied the relevant code....
