### ISSUE TITLE
RectangleSelector creates not wanted lines in axes

### ISSUE THREAD

**Issue by Acanthostega** [matplotlib/matplotlib#5635]
Hi everyone,

Creating a RectangleSelector adds unwanted lines in the axes. Before 1.5 version, I was not seeing this I think, but for now I can't try with an older version.

To reproduce, simply take the example provided in the documentation with RectangleSelector with the qt backend to use the figure options panel. Before the creation of the RectangleSelector, it shows one curve, and after the creation of toggle_selector.RS, four new lines have appeared. Indeed, they appeared in the lines attribute of the ax.

It should not be an expected behavior (I think) since some applications may rely on this for making line selections, etc.

**Comment by tacaswell** [comment]
You should not rely on access to or the contents of `ax.lines`.  It is very likely that these will be greatly changed / removed in the near (1-2 yr) future.

I suspect the lines are the handles?

**Comment by Acanthostega** [comment]
Lines are what is used by figureoptions.py to display the list of plots inside the figure options panel. get_lines() is called to access them.

What is the difference between lines and handles ?

**Comment by fariza** [comment]
Actually if I just open the figure options panel I get
```
Traceback (most recent call last):
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 635, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/qt_editor/figureoptions.py", line 115, in figure_edit
    ('Line Style', prepare_data(LINESTYLES, line.get_linestyle())),
  File "/home/fariza/workspace/matplotlib/lib/matplotlib/backends/qt_editor/figureoptions.py", line 98, in prepare_data
    canonical_init = name2short[d[init]]
KeyError: 'None'
```
So I don't even get to see the extra lines

**Comment by Acanthostega** [comment]
I provide a better test case to be sure that we are all using the same code:

```python
from matplotlib.widgets import RectangleSelector
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
x = np.linspace(0, 1, 10)
ax.plot(x, x, label="plot")
def line_select_callback(eclick, erelease):
    pass

# check curves in the qt editor to see just one
rs = RectangleSelector(ax, line_select_callback,
                                       drawtype='box', useblit=True,
                                       button=[1, 3],
                                       minspanx=5, minspany=5,
                                       spancoords='pixels',
                                       interactive=True)
# check again qt editor to see the other ones
```
