### ISSUE TITLE
pyplot.streamplot vmin and vmax

### ISSUE THREAD

**Issue by ledm** [matplotlib/matplotlib#5637]
Hi,

I'm attempting to automatically create a streamplot of 2D velocity with variable colour indicating the speed. I'm making multiple copies of this plot and need to fix the minimum and maximum values for the arrow colour scale. I had assumed that the default kwargs vmin and vmax would apply to streamplot, but:

streamplot() got an unexpected keyword vmin, vmax. 

Similarly, streamplot is unable to produce a colorbar().

**Comment by flothesof** [comment]
Hi @ledm,

Ineed vmin and vmax are not part of the function call for the streamplot module. 

A simple tuning for velocity could be obtained using the linewidths (not sure it applies to your case), as shown in the example: [http://matplotlib.org/examples/images_contours_and_fields/streamplot_demo_features.html](http://matplotlib.org/examples/images_contours_and_fields/streamplot_demo_features.html). 
Another thing to try if this doesn't work for you is to look up the source for the streamplot function here: [https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/streamplot.py](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/streamplot.py). You will see that streamplot does accept a color normalizer object as argument which might allow you to do what you need. 

I hope this helps you a little.

Best 
Florian

**Comment by tacaswell** [comment]
The `Norm` object can have the min/max pre-set before it is passed in.
