### ISSUE TITLE
plt.errorbar error with empty list

### ISSUE THREAD

**Issue by divenex** [matplotlib/matplotlib#5641]
The command below returns an error in Matplotlib 1.5.0
```
plt.errorbar([], [], xerr=[], yerr=[])
```
Even tough 
```
plt.errorbar([], [])
```
works as expected.

When the x and y coordinates are empty lists, It would make sense for the command to accept empty ```xerr``` and ```yerr``` keywords as well, without throwing an error, as in the previous Matplotlib version. In fact the empty lists will likely come from code like the following, where ```np.any(mask)==False```
```
mask = y > 0
plt.errorbar(x[mask], y[mask], xerr=xerr[mask], yerr=yerr[mask])
```

**Comment by mdboom** [comment]
Related to #5572, suggesting we need a general solution to this problem as hinted at in the comments over there.

**Comment by tacaswell** [comment]
Were we just not laundering enough inputs through the unit frame work before?
