### ISSUE TITLE
xlim not supporting datetime64 data

### ISSUE THREAD

**Issue by Acanthostega** [matplotlib/matplotlib#5643]
Hi everyone,

I don't know if this a numpy problem or not, but setting axes limits with datetime64 data raises:

```
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

An example to reproduce the problem:

``` python
import numpy as np
from matplotlib.pyplot import Figure

fig = Figure()
sub = fig.add_subplot(111)

x = np.array(['2015-07-13T04:32:23+0200', '2015-07-13T04:32:24+0200', '2015-07-13T04:32:25+0200'], dtype="datetime64")
y = np.arange(len(x))
ax.plot(x, y)
ax.set_xlim(xmin=x[0], xmax=[-1])
```

Matplotlib works well with python datetime, so I think that it should work also with numpy datetime64, but maybe np.isfinite should support all numpy "native" types?

**Comment by tacaswell** [comment]
If you import pandas, which will register convertors for datetime64 you get a different exception

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

fig, sub = plt.subplots()
x = np.array(['2015-07-13T04:32:23+0200', '2015-07-13T04:32:24+0200', '2015-07-13T04:32:25+0200'], dtype="datetime64")
y = np.arange(len(x))
sub.plot(x, y)
sub.set_xlim(xmin=x[0], xmax=[-1])
```

gives

```

Traceback (most recent call last):
  File "/src/path/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 176, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "/src/path/matplotlib/lib/matplotlib/backends/backend_agg.py", line 466, in draw
    self.figure.draw(self.renderer)
  File "/src/path/matplotlib/lib/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/src/path/matplotlib/lib/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/src/path/matplotlib/lib/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/src/path/matplotlib/lib/matplotlib/axes/_base.py", line 2314, in draw
    a.draw(renderer)
  File "/src/path/matplotlib/lib/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/src/path/matplotlib/lib/matplotlib/axis.py", line 1106, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/src/path/matplotlib/lib/matplotlib/axis.py", line 949, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/src/path/matplotlib/lib/matplotlib/axis.py", line 949, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/src/path/matplotlib/lib/matplotlib/axis.py", line 892, in iter_ticks
    majorLocs = self.major.locator()
  File "/src/path/matplotlib/lib/matplotlib/dates.py", line 1006, in __call__
    self.refresh()
  File "/src/path/matplotlib/lib/matplotlib/dates.py", line 1026, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/src/path/matplotlib/lib/matplotlib/dates.py", line 770, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/src/path/matplotlib/lib/matplotlib/dates.py", line 419, in num2date
    return _from_ordinalf(x, tz)
  File "/src/path/matplotlib/lib/matplotlib/dates.py", line 271, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

which I suspect means we need to consult the unit registry someplace in that call stack.

The problem is that `np.datetime64` does not support the `datetime.datetime` interface so will require a whole new code path (`pandas` deals with this by providing a container for `datetime64` which does expose that interface).

We also have the issue that we support versions of numpy which do not have (usable) implementations of `datetime64`.

**Comment by mvds314** [comment]
I experience the same problem, but strangely enough only when using the agg back_end. Furthermore, the problem does arise in matplotlib 1.5.1 (winpython 2.7.10.3), but not in 1.4.3 (winpython 2.7.10.2).
```
import matplotlib as mpl
import matplotlib.pyplot as plt
import datetime

plt.switch_backend('agg')
#plt.switch_backend('qt4agg')

x = [datetime.datetime(2013,12,i) for i in range(1, 11)]
y = range(len(x))
plt.plot_date(x,y)
```

**Comment by efiring** [comment]
@mvds314 what you are seeing is different; you are using the standard library datetime, which is supposed to work.  The issue here is about np.datetime64, which has never been intentionally supported by mpl.
I suspect your question is related to your `plt.switch_backend('agg')`.  That function has never gotten beyond "experimental".  It's use in your example looks pointless, because with the agg backend alone you will not get any screen display at all.  In fact, the `switch_backend()` function itself may be pointless, and perhaps should be removed.

**Comment by mvds314** [comment]
@efiring thnx for your response. If it is unrelated, I will post it as a seperate bug.

Regarding the example, the use of the agg backend in the example is of course useless. However, I use the agg backend to generate a whole bunch graphs and save them to a folder. I couldn't get this working with the other backends in an interactive development environment (Spyder). For this purpose, I find the agg backend really usefull.

**Comment by dstansby** [comment]
There's a slight bug in your example; `sub.set_xlim(xmin=x[0], xmax=[-1])` should be `sub.set_xlim(xmin=x[0], xmax=x[-1])` (missing `x`). With that small fix the example works fine so I presume this bug was fixed at some point.
