### ISSUE TITLE
Missing line in a self-sufficient example in navigation_toolbar.rst :: a minor bug in docs

### ISSUE THREAD

**Issue by dborisog** [matplotlib/matplotlib#5645]
(see at the bottom http://matplotlib.org/users/navigation_toolbar.html )

I presume such examples are designed to be self-sufficient, and therefore instead of 

    from matplotlib.figure import Figure
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
    from matplotlib.backends.backend_gtkagg import NavigationToolbar2GTKAgg as NavigationToolbar

it should contain 

    import gtk
    
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
    from matplotlib.backends.backend_gtkagg import NavigationToolbar2GTKAgg as NavigationToolbar

as shown in another example http://matplotlib.org/examples/user_interfaces/embedding_in_gtk.html

**Comment by tacaswell** [comment]
@dborisog Can you open a PR with that change?

**Comment by dborisog** [comment]
@tacaswell I would like to postpone such actions for later times when I have much better understanding of matplotlib and its dependencies. 

In particular, "import gtk" may also be wrong, because "pygtk" mentioned in docs ( http://matplotlib.org/users/installing.html ), and therefore it should look like "import pygtk as gtk" ( http://www.pygtk.org/pygtk2tutorial/ch-GettingStarted.html ). Which would affect the rest of "gtk" examples.

I however failed to run this script because pygtk is not a part of Anaconda project I'm using at the moment.

**Comment by fariza** [comment]
@dborisog there is no better way to get a better understanding that getting your hands dirty. And yes, I think you're right, that import `import gtk` is needed to run the example.

**Comment by dborisog** [comment]
@fariza I have rather limited understanding of Python packages. Study takes a lot of my time, and this bug is not related to the task I'm trying to solve. During familiarization with matplotlib via documentation, I tried and failed to run this example both on Windows and Linux machine. The fix may take from few minutes to few days+ of my (non-python-guru) time, and according to my experience the latter extreme is more probable, especially if solution should work both on Windows and Linux. I think the fix should be produced by people with a way better understanding of matplotlib and gtk.
