### ISSUE TITLE
Problems installing basemap behind a proxy

### ISSUE THREAD

**Issue by ispmarin** [matplotlib/matplotlib#5655]
Just to cross-reference, I can't install `basemap` from behind a proxy, even when `pip` works. https://github.com/pypa/pip/issues/3297

Has anyone faced the same problem or has a solution?

Cheers

**Comment by jenshnielsen** [comment]
Basemap should really be on pypi but the size currently prevents this see https://github.com/matplotlib/basemap/issues/198

I would suggest cloning the repository with git, checkout the release that you want and then do 
`pip install .` from the top level source directory as a work around. You can also download a tar.gz file if that is easier.

**Comment by ispmarin** [comment]
Got it. Downloaded the rep and installed with

    pip install --no-index file:///src/basemap

Had to install by hand a bunch of deps (both Python and Linux) but it worked.
