### ISSUE TITLE
Constant valued scatter plot has weird y-scale

### ISSUE THREAD

**Issue by jsirvine** [matplotlib/matplotlib#5657]
When plotting a scatter plot with constant y values, the y axis has a very small range (0.003) regardless of the magnitude of the constant value. For example, when plotting y=1.0, the y-axis range is [0.0005, 0.0035] with an added +9.98e-1 in the top left corner. 

I was expecting the same behavior as a line plot. In that case, for y=c, the range is [0.94c, 1.06c] or [-.06, .06] if y=0.

Code to reproduce:
```python
import matplotlib.pyplot as plt
x = [i/10.0 for i in range(101)]
y = [1.0] * 101
plt.scatter(x,y)
plt.show()
```
![const_scatter](https://cloud.githubusercontent.com/assets/4109189/11727098/bc46a428-9f36-11e5-9a82-277c0f079b1f.png)

-vs-

`plt.plot(x,y)`
`plt.show()`
![const_plot](https://cloud.githubusercontent.com/assets/4109189/11727106/c62a06a6-9f36-11e5-8f91-3b3243fac3c7.png)

**Comment by dstansby** [comment]
Looks like this has been fixed at some point in the last few years:

![Figure_1](https://user-images.githubusercontent.com/6197628/57698254-1fd31f80-764d-11e9-8d38-b5afc1cc26e8.png)

Feel free to comment/re-open if it's still a problem.
