### ISSUE TITLE
A way to remove the image of plt.figimage()?

### ISSUE THREAD

**Issue by lilynguyen** [matplotlib/matplotlib#5658]
Hi! Is there a way to remove an image for plt.figimage()? I would like to be able to set the background for my interactive application, but when I want to essentially change the screen and do another plt.figimage() it seems to just layer on the previous one. Doing this multiple times inevitably slows down graphing for interactive mode. I couldn't find a method for removing a figimage. Maybe I wasn't looking hard enough?

**Comment by tacaswell** [comment]
All artists (should) have a `remove` method which will remove them from the draw tree.

```python
In [7]: fm = plt.figimage(np.random.rand(10, 10))

In [8]: fm.remove()
```

You can also use the `fm.set_data` method to just change the image in-place.
