### ISSUE TITLE
plt.pause() with threading is extremely slow for MacOSX backend

### ISSUE THREAD

**Issue by danijar** [matplotlib/matplotlib#5675]
Here is a minimal example where a worker produces a sequence that's plotted every second by the main thread. Between the draw calls, the main thread pauses for 0.001s to update the GUI and sleeps for 1s. This takes 10 seconds. When pausing for 1s and sleeping for 0.001s instead, I would expect this to run in about the same time. However, it takes 70 seconds.

``` python
import random
import time
import threading
import matplotlib.pyplot as plt


class Plot:

    def __init__(self):
        plt.ion()
        plt.show()
        self.xdata = []
        self.ydata = []
        self.running = None
        self.axis = plt.figure().add_subplot(111)
        self.line, = self.axis.plot([])

    def start(self):
        self.running = True
        threading.Thread(target=self.worker).start()
        while self.running:
            self.axis.set_xlim(0, len(self.xdata))
            self.axis.set_ylim(0, max(self.ydata))
            self.line.set_data(self.xdata, self.ydata)
            plt.draw()
            plt.pause(0.001)
            time.sleep(1)

    def worker(self):
        for _ in range(100):
            self.xdata.append(len(self.xdata))
            self.ydata.append(random.random())
            time.sleep(0.1)
        self.running = False


if __name__ == '__main__':
    start = time.time()
    Plot().start()
    print(time.time() - start)
```

Profiling revealed that by far the most time is spent in `start_event_loop` of `_macosx.FigureCanvas`.

Possibly related: https://github.com/matplotlib/matplotlib/issues/5251

**Comment by jenshnielsen** [comment]
can you try the fix in #5562?

**Comment by mdehoon** [comment]
There are two issues here:
1) Drawing should be done in the main thread, not in the worker thread;
2) You don't need these lines:
```python
            plt.draw()
            plt.pause(0.001)
            time.sleep(1)
```

The following code works as intended:
```python
import random
import time
import threading
import matplotlib.pyplot as plt


class Plot:

    def __init__(self):
        plt.ion()
        plt.show()
        self.start = time.time()
        self.xdata = []
        self.ydata = []
        self.running = None
        self.axis = plt.figure().add_subplot(111)
        self.line, = self.axis.plot([])
        threading.Thread(target=self.worker).start()

    def worker(self):
        for _ in range(100):
            self.xdata.append(len(self.xdata))
            self.ydata.append(random.random())
            self.axis.set_xlim(0, len(self.xdata))
            self.axis.set_ylim(0, max(self.ydata))
            self.line.set_data(self.xdata, self.ydata)
            time.sleep(0.1)
        print(time.time() - self.start)


if __name__ == '__main__':
    Plot()
```

**Comment by mdehoon** [comment]
To explain how this works:
The event loop starts running in the main thread as soon as the MacOSX backend is imported.
Then we start the following cycle:
- The event loop is sitting in the main thread, waiting for something to happen;
- The worker thread calls set_xlim, set_ylim, set_data, which will invalidate the canvas;
- The event loop notices that the canvas is invalidated, triggering a redraw in the main thread.

**Comment by koogle** [comment]
Thanks for the explanation. I tried the updated script but the window does not get redrawn at all.
Which version of matplotlib are you referring to? (I am using 1.5.0)

**Comment by mdehoon** [comment]
I am using matplotlib 1.5.0. Run with "python -i script.py"; "python script.py" won't work.

**Comment by koogle** [comment]
Okay, I can confirm it works without problems in interactive mode. Thanks for the clarification.

**Comment by mdehoon** [comment]
The reason it doesn't work in non-interactive mode is probably that the set_xlim, set_ylim, set_data doesn't invalidate the canvas in non-interactive mode.

@tacaswell  Perhaps stale should always propagate irrespective of whether matplotlib is interactive or non-interactive.

**Comment by danijar** [comment]
Thanks @mdehoon for the example @koogle for testing. What would be the right way to make your example work in non-interactive mode?

**Comment by mdehoon** [comment]
@danijar  See my comment to @tacaswell  above. That should do it.

**Comment by danijar** [comment]
As I understand it, your comment suggested a change in matplotlib. Do you have a fix for users that works right now? I thought about invalidating the canvas with something like `fig.canvas.draw_idle()`.

**Comment by tacaswell** [comment]
Stale _does_ propagate, the question is if anything at the top is listening.

For non-interactive backends (ex Agg) the `draw_idle` is not (and can not be) asynchronous (it is re-entrant so stale flags that arise in a `draw` do not trigger recursive draws). 

One possible solution to this is to make the OSX backend's `Figure` always invalidate it's canvas independent of the interactive state.

Having said that, that might be the right place to put all of this logic (backend dependent).

**Comment by greglucas** [comment]
It seems like there is still some work here to do. This only seems to work as expected on the qt5agg backend for me.

`tk`: runtime error with calling draw_idle() from off the main thread. (Stemming from setting the figure stale during the xlim updates)

`macosx`: no canvas updates, it seems like the loop isn't receiving and processing the draw_idle() timers. The canvas is somewhat disassociated with the events. For example, after the worker thread is done, the mouse hovers all work as expected, but the draws never get triggered and update. However, if you click the subplot tool and mess around with those settings, then the Agg canvas is updated and redrawn, but going back to the pan/zoom tools does nothing again, so those events don't seem to go back to the Agg redraws.
