### ISSUE TITLE
Y-axis switches to log scale when an X-axis is shared multiple times.

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#5679]
This is a strange one.  If I create a set of axes, and then create a second set of axes that shares its x-axis with the first x-axis, like the following,

    import matplotlib.pyplot as plt
    fig = plt.figure()
    ax1 = fig.add_axes([0.1,0.1,0.3,0.3])
    ax1.set_yscale('log')
    ax2 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
    print ax2.get_yscale()

then ``ax2.get_yscale()`` produces ``'linear'`` as expected.  If I create a third set of axes that shares its x-axis with the second x-axis, like the following,
    
    import matplotlib.pyplot as plt
    fig = plt.figure()
    ax1 = fig.add_axes([0.1,0.1,0.3,0.3])
    ax2 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
    ax2.set_yscale('log')
    ax3 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax2)
    print ax3.get_yscale()

then ``ax3.get_yscale()`` produces ``'linear'`` as expected.  If I, instead, create a third set of axes that shares its x-axis with the FIRST x-axis, like the following,
    
    fig = plt.figure()
    ax1 = fig.add_axes([0.1,0.1,0.3,0.3])
    ax2 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
    ax2.set_yscale('log')
    ax3 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
    print ax3.get_yscale()

then ``ax3.get_yscale()`` produces ``'log'``.  I believe the y-axis for the third set of axes should have defaulted to ``'linear'``.

**Comment by tacaswell** [comment]
```python
fig = plt.figure()
ax1 = fig.add_axes([0.1,0.1,0.3,0.3])
ax2 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
ax2.set_yscale('log')
ax3 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
print(ax3.get_yscale())
print(ax2 is ax3)
```

gives

```python
In [5]: log
True
```

This is a 'feature', the second call to `fig.add_axes` is going "ah, I have that one already no need to create a new one!" and just gives you back a new ref to `ax2`.

**Comment by breedlun** [comment]
Oh, wow.  You are right.  All I have to do is nudge `ax3` and it creates a new set of axes:

    import matplotlib.pyplot as plt
    fig = plt.figure()
    ax1 = fig.add_axes([0.1,0.1,0.3,0.3])
    ax2 = fig.add_axes([0.1,0.4,0.2,0.2], sharex = ax1)
    ax2.set_yscale('log')
    ax3 = fig.add_axes([0.1,0.40000001,0.2,0.2], sharex = ax1)
    print ax3.get_yscale()
    print (ax2 is ax3)

gives

    linear
    False

What if someone wants to create a second set of axes right over top of the other set?  Or what if someone wants to create their axes in the same place every time and then move them to their final position?

**Comment by tacaswell** [comment]
As I said, 'feature' :smiling_imp: 

See http://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.add_axes  If you pass the `label` kwarg it will also prevent this behavior.

I was not around when this was written, but I suspect that this was done in analogy to the `fig.add_subplot(221)` which returns the already created `ax`. 

Independent of the reasoning, this is something that has been there almost forever (tracking git blame back got to JDH in 2004 18dca6619db9c3844bcfc56580362f3a60b54f53 ) so we can probably never get rid of it as there is a lot of time for people have come to rely on this behavior.

**Comment by efiring** [comment]
@tacaswell, I doubt many people actually *do* rely on it, though.  I don't see how it could have much of a use case.   Wouldn't it be possible to deprecate it via warning when it is returning an existing Axes, and a temporary "legacy" rcParam, or something like that?
