### ISSUE TITLE
Support error bars on 3D plots

### ISSUE THREAD

**Issue by jfinkels** [matplotlib/matplotlib#568]
Support error bars on 3D plots. This seems to not be implemented in other plotting libraries and programs. See here for someone's implementation for Matlab: http://code.izzid.com/2007/08/19/How-to-make-a-3D-plot-with-errorbars-in-matlab.html

**Comment by petehuang** [comment]
PR still welcome here after all this time, and doesn't seem like anyone is working on it

**Comment by tacaswell** [comment]
Tagging as new-contributor friendly because there is little API design work here (just mirror `ax.errorbar` as closely as possible), but medium difficulty as this will be a fair amount of work.

**Comment by vlas-sokolov** [comment]
As there are no containers returned by any `Axes3D` methods (as far as I can see), it is a bit unclear what the new method should return. Would this have to mirror the `ErrorbarContainer` class into `mplot3d`? Or would passing `Line3DCollection` instances suffice?

**Comment by vlas-sokolov** [comment]
Opened a pull request here: #8031.

**Comment by QuLogic** [comment]
Implemented in #8031.
