### ISSUE TITLE
Mac: Save button not working on 1.5.0 or 2.x with backend.qt4 in ipython 4

### ISSUE THREAD

**Issue by JCorson** [matplotlib/matplotlib#5689]
When trying to save a figure in matplotlib 1.5.0 with `backend:Qt4Agg` and `backend.qt4:PySide` the save button is not functional. The save dialog opens and then immediately closes.

```
# Use %matplotlib to prevent segfault reported in issue #5687
%matplotlib 
import matplotlib.pyplot as plt
plt.plot(range(10))
```

Click the save button. 
`plt.savefig()` still works.
I have been able to reproduce this behavior on Mac (OSX 10.11) in both Enthought and Anaconda's matplotlib 1.5.0.

**Comment by tacaswell** [comment]
just to confirm, this is a regression from 1.4.3?

**Comment by jdmarch** [comment]
I can reproduce on 1.4.3

**Comment by tacaswell** [comment]
ok, so not a regression.  

This is tickling something in the back of my mind as having seen this before and it getting fixed, but details are not forth coming.

attn @mfitzp

**Comment by mdboom** [comment]
I can't seem to reproduce with Homebrew Python 2.7.11 and pyside.  What Python are you using and how did you install PySide?

**Comment by mdboom** [comment]
Nevermind, if I run in IPython, I *can* reproduce.  Regular Python interpreter works, though.

**Comment by tacaswell** [comment]
I wonder if this is related to the ipython inputhook?

**Comment by mdboom** [comment]
That's my suspicion, but I haven't had much time to look at it.

**Comment by mdboom** [comment]
Sorry -- I think I introduced confusion by not being clear enough in the PR descriptions.  d041565 doesn't fix this bug.  This bug has to do with the save dialog displaying briefly.  d041565 (and #5720) fix a bug that only happens *after* the user has had a chance to select a filename and begin drawing and saving the file.  I've been poking at this bug without any success -- I think it's something pretty low-level in how the IPython input hook is set up, and (I think) used to work and recent PySide changes broke it.

**Comment by tacaswell** [comment]
sorry :sheep:

**Comment by mdboom** [comment]
No worries.  It would be hard to know they were different from the descriptions alone.

**Comment by tacaswell** [comment]
Punting this to the 2.0 tag as it is not a regression and we probably need to pull in someone from IPython here.

@JCorson https://github.com/matplotlib/matplotlib/pull/5690 fixed the segfault, does this bug exist using the not-ipython-eventhook?

**Comment by JCorson** [comment]
@tacaswell with #5690 patched, I have only been able to produce this bug when running ipython with %pylab or %matplotlib.

**Comment by tacaswell** [comment]
@Carreau who is the right IPython person to ping about input hook + qt + pyside issues?

**Comment by Carreau** [comment]
hum... I take my chance with @minrk that know all the things. I'll have a look too.

**Comment by efiring** [comment]
This is not a pyside-specific issue; I see it with an Anaconda installation using pyqt 4.11.4. @minrk, any chance you can look into this?

**Comment by tacaswell** [comment]
I think this may be a OSX specific issue as well.  It works correctly on linux.

**Comment by minrk** [comment]
I'll see what I can find out.

**Comment by tiagopereira** [comment]
I had this problem with both PySide and PyQt. However, updating to IPython 5.1.0 seems to solve the issue. Also improves the window redraw when resized on qt5.

**Comment by efiring** [comment]
I can reproduce it using ipython with or without '--pylab' or any gui magic (`plt.ion()`), but not at the ordinary python prompt, where `plt.ion()` is now sufficient for interactivity.  This is with ipython 4.0.3, so given the report above, it may be something we don't have to worry about, as newer ipython versions come into use.

**Comment by anntzer** [comment]
Closing as the last report is that this is fixed with recent ipython versions.  Feel free to reopen if still present with even more recent ipythons.
