### ISSUE TITLE
Possible enhancements to make data changes for animations / animate easier

### ISSUE THREAD

**Issue by ahed87** [matplotlib/matplotlib#5699]
Hi,

first of all thanks for a great library, and the heavy work done lately.
I welcome new styling options as well as new defaults and improved webagg with open arms.

A while ago I spent some time getting an animation done in mpl,
when doing that I gathered some thoughts that possibly could make it easier
to get animation like work done for other users in the future.

After the first read-up I thought it looked easiest to do what I wanted with matplotlib.path.Path.xx,
all primitives I needed where there and I thought I could apply the same transformation scheme to every element.

After a bit of coding with the Path primitives I realized that I could not easily use the same transformation scheme and also largely end up reimplementing several features already in matplotlib.patches so I started using those instead which took me all the way to a great animation.

The animation turned out to be perfect as a movie made from stitching up to thousands of png's - but the way to get there and the final mpl code could have been a bit easier :-)
I have to admit that I did not use mpl.animate (this time - but I have used it earlier for scatterplots), so I did not expect that I would be able to view the animation live, but was gladly surprised that the animation was fully viewable "live" as well when running without saving the png's, to get it perfect live I would have had to add a simple time.sleep in the "move elements" loop.

Here is my list of lessons learned, forgive me if some of the points are sprung out of my inability to find the easy/right way to do it :-)

I did it with py34 and mpl 1.4.3 (anaconda win64).
1. Did not find rotation in properties for Rectangle, or an angle property in Polygon, Wedge etc, but the Ellipse has one...
   **Proposal** would be that all patches have an angle/rotation option / property, for simplicity one might even consider to do angle on the Circle to avoid property checking in a loop over the elements.
2. Noticed that paths for patches are done so that some are unity with transforms (for example Arrow)
   and others are data points.
   **Proposal** would be that all patches holds same "base info" and same "base transform" upon creation,
   (i.e. not different scalings/transforms) - not sure what a good way to go is to make it happen but it would simplify usability it it was like that, suspect that simply saying datapoints will not work all the way.
3. Missed a bezier constructor in mpl.patches.
   **Proposal** would be to add Curve4, Curve3 as part of patches like Rectangle, Circle etc
   (I ended up doing my own version making points for Polygon in like 10 lines of code, with the midpoint between start/endpoint as reference for the polygon - for ease of later rotations/translations, having an optional midpoint in the constructor could be quite convenient for users, or why not always generate something like myBezier.center (and False/True if that is the start&endpoint of the created path) which could be used as reference for placement if wanted and would be simple to use as center with rotate_around, or I would probably prefer to rotate around the mid/center point with "rotate" (default behaviour), and leave start/endpoint for "rotate_around" :-)
4. Could not easily specify proportions of the Arrow (could not get the width property to do it nicely), the need for changing the proportions came out of that the Arrow's original proportions simply did not work visually (too wide, or non-pleasant head/tail proportion) when scaled to be larger (and different in x/y).
   **Proposal** would be to allow for a "unit shape/path" as property (or carry over relevant properties from FancyArrow).
   (I found my way by looking into the source, rolled the dice and tested what happened when I replaced the ._path property with a new shape on the created instance, which luckily worked out OK. The change of head coordinates of the unity path did the job).
5. Was a bit confused around the transforms, did not seem consistent to me, +transData to get the right point for incremental translate/rotate, and rotate_around for a specific point, and then the Arrow needed special care as well?!
   **Proposal** would be to skip +transData need for incremental translation, make rotate to be rotate around element reference, and add translate_to_absolute/roatate_around_absolute. If one would like to stretch it and avoid the last obstacle I ran into with depth of object references (see below) one could also think of some sort of intelligent "flatten function" for transforms, which could be a way to from a user perspective allow for infinite number of transforms...
6. For some reason Wedge did not react/move on change of myWedge.center...
   however the myWedge.set_center  worked fine (and with a .patch.Circle the myCircle.center the element moves, but I could not find any myCircle.set_center method)
   **Proposal** is just to unify Circle/Ellipse/Wedge behaviour.
7. Missed having the construction coordinates of the Arrow (x,y dx, dy) for later change.
   **Proposal** is to make them available on the created instance for later manipulation.
   (I ended up putting a monkey patch on the instance to always have the original _patch_transform at hand and always making an "absolute" translation from that original Affine2D to avoid the situation mentioned below.
8. **Maybe** add a Line with p1 = (x1,y1), p2 = (x2,y2), not being forced to use Polygon for a simple line?

Once I had figured out how to make the translations work, I thought that I was done and ran the script trying to make the frames for a movie - and then I found out that python did not allow for more than around 200 transforms (depth of object references I think it said - did not see that one coming...).
Anyways, that's when I made point 7 to get around the number of incremental transforms - which in the end worked like a charm and I got my nice animation :-).

PS: I think it would be perfectly OK to change things like this in minor releases. I think that the people that possibly would be affected of above proposals (changed/broken API) would appreciate it rather than being annoyed as long as it ends up in simplification of excisting code.

PS2: I used Polygon/Rectangle/Circle/Wedge/Arrow, so those are the only one's I got to know inside and out.

PS3: I have not read up on all new things in 1.5 or 2.0, so maybe my comments are already obsolete?

**Comment by WeatherGod** [comment]
This is a very interesting analysis. These sorts of analyses should be done
more often, especially on codebases that grew somewhat organically like
matplotlib's. It is going to take a bit to digest all of this.

One thing to note is that we do have a very strict API compatibility
policy, so an argument of "the users would like it better that way" isn't
sufficient to change the defaults. Especially if the change does not result
in breakage (which can be very difficult to detect and/or track down the
cause).

**Comment by ahed87** [comment]
Fair point - like is and should not be motivation for change of default, but maybe consistency and simplification can be?

Anyways, I'm looking forward to see what comes out of this.

**Comment by tacaswell** [comment]
Reading through this again, most of these can be done in a back compatible way (and where we have two different ways to do things on different artists we are going to have to support both on both for the mid term), pull requests implementing them from you would be a good start. In many of those cases the devil will be in the details.


Did you implement animation by appending to the transform stack rather than updating the data in the artists? I would like to see an example if that code as that is not how i would have done it.

I also think (but would have to check the docs) that the transforms have an inplace addition method which might help
