### ISSUE TITLE
Issue with xy and xytext

### ISSUE THREAD

**Issue by dsquareindia** [matplotlib/matplotlib#5704]
Here: http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.annotate it is written that `xytext` is the position of the label string. But while working I found that `xytext` coordinates are actually offset specified from `xy` coordinates.

**Comment by tacaswell** [comment]
Can you provide an example snippet to help clarify what you are asking?  How the values in `xytext` are interpreted is dependent on the value of `textcoords`.

**Comment by dsquareindia** [comment]
Hi @tacaswell sorry for that. It's an error on my part. Misinterpreted a few things. The documentation is absolutely fine.

**Comment by tacaswell** [comment]
Any help in clarifying the documentation would be appreciated. If you miss
read them, someone else will miss read them too.

**Comment by dsquareindia** [comment]
@tacaswell It would be nice if something on these lines could be added:

```xy: (x,y) , default: "data"```

    position of element to annotate. Use xycoords param for additional types.

```xytext : (x, y) , optional, default: None```

    position of the label s. Use textcoords param for additional types.

**Comment by tacaswell** [comment]
Could you open a pull request with those changes?

**Comment by dsquareindia** [comment]
Sure! Would be happy to contribute :-)
