### ISSUE TITLE
doc/users/plotting/examples/axes_zoom_effect.py is not a Python file

### ISSUE THREAD

**Issue by jayvdb** [matplotlib/matplotlib#5705]
Pyflakes complains there is a syntax error in `doc/users/plotting/examples/axes_zoom_effect.py`

```bash
$ pyflakes doc/users/plotting/examples/axes_zoom_effect.py
doc/users/plotting/examples/axes_zoom_effect.py:1:1: invalid syntax
../../../../examples/pylab_examples/axes_zoom_effect.py
^
$ cat doc/users/plotting/examples/axes_zoom_effect.py
../../../../examples/pylab_examples/axes_zoom_effect.py$ 

$ git log doc/users/plotting/examples/axes_zoom_effect.py
commit e671b6354a324d52b90e524db88365ad64dedcc8
Author: Jae-Joon Lee <lee.j.joon@gmail.com>
Date:   Tue Jul 14 21:24:07 2009 +0000

    initial submission of the annotation guide.
    
    svn path=/trunk/matplotlib/; revision=7262

```

Should it be a symlink to `examples/pylab_examples/axes_zoom_effect.py` ?

**Comment by WeatherGod** [comment]
Oh, wow, that's weird. It probably was a symlink at some point, but then
got broken by the svn->git transition, Grepping through the codebase and
documentation, that particular file is never referenced. So, it is probably
safe to get rid of it altogether.

**Comment by mdboom** [comment]
I think that's right.  Let's just remove the file.
