### ISSUE TITLE
Segfault with Qt4Agg backend in 1.5.0

### ISSUE THREAD

**Issue by dchandan** [matplotlib/matplotlib#5708]
After upgrading to 1.5.0 am getting segmentation faults with the Qt4Agg backend. Looks similar to issue https://github.com/matplotlib/matplotlib/issues/5609. Switching to MacOSX backend works.

**Comment by jenshnielsen** [comment]
It's very unlikely to be related to #5609 which is an issue in the WX backend specific to how WX windows is closed. Can you please provide some more information about what you are trying to do. How did you install python, are you using PySide of PyQt4, which version etc.

**Comment by dchandan** [comment]
I looked into it further and found that the issue was with the PySide backend for Qt4Agg. If the backend is changed to PyQt4 then there is no segfault. Unfortunately I cannot provide more details, as the only output is ``Segmentation fault: 11``. The minimum code that triggers the segfault is ``plt.figure()``.

**Comment by jenshnielsen** [comment]
Sound more likely to be #5687 ?

**Comment by dchandan** [comment]
Yup, closing this.
