### ISSUE TITLE
Cursor displays x, y coordinates with too much or too little precision

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5726]
Currently, the x, y coordinates of the cursor (displayed by the interactive backend) are displayed with 6 significant digits (basically, this is due to `ScalarFormatter.format_data_short` using the "-12g" format string, which defaults to 6 significant digits).  This leads to a few issues.
- The mouse position is typically only known with pixel-level precision (at least for Qt and Tk), so with screen sizes limited to a few thousand pixels, for axes limited to e.g. [0, 1], the cursor position should only be displayed with 4 significant digits.
- On the other hand, if the axes limits are far from the origin (say xlim = [1e5, 1e5+1]), the cursor position readout is useless because all significant digits are taken by the base offset.

Thus, I propose to change `format_data_short` (which AFAICT is only used for this purpose), so that it displays the coordinates with the same base offset as the axes do (but with the same absolute precision as the additional shift), and the additional shift with 4 significant digits (if we really wanted to do this properly perhaps we can get the axes size in pixels and decide accordingly, but that may be overdoing it).

Thoughts?

**Comment by tacaswell** [comment]
:+1:   Getting these changes in for 2.0 would be great.

**Comment by anntzer** [comment]
Is there an approximate timeline?

**Comment by tacaswell** [comment]
'soon'.  Many dragon inhabited rabbit holes were discovered by @mdboom.  Probably first quarter next year.

**Comment by mdboom** [comment]
> Many dragon inhabited rabbit holes were discovered by @mdboom

I love that expression.  What the hell were dragons doing in the rabbit holes?  They should stick to their dragon caves!

**Comment by WeatherGod** [comment]
I would worry about some rabbits that inhabit dragon caves...
https://www.youtube.com/watch?v=cCI18qAoKq4

**Comment by mdboom** [comment]
Yes.  The rabbits I've been dealing with definitely had pointy teeth...

**Comment by QuLogic** [comment]
We're (approximately) nearing the end now; @anntzer any chance you might make a PR out of your suggestions soon?

**Comment by anntzer** [comment]
This is handled in my large formatter rewrite PR (https://github.com/matplotlib/matplotlib/pull/5804/files#diff-efde3b8d2ec4015b0fc910f1080cc492R560), but it unfortunately seems unlikely that it'll go into 2.0.  To be honest I'd rather try to get that PR in instead of messing up again from scratch with that (nasty) part of the codebase...

**Comment by QuLogic** [comment]
As you say, that PR is probably too large to go into 2.0; we may have to bump this issue as well, then.

**Comment by tacaswell** [comment]
bumping the issue to 2.1.

**Comment by timhoffm** [comment]
Fixed by #16776.
