### ISSUE TITLE
Move from numpydoc to sphinxcontrib-napoleon

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5731]
napoleon is a more general replacement for numpydoc docstring support and ships with Sphinx since 1.3.

There seem to be subtle differences, however, and so it will take some manual updating to our docstrings to get this to work.

**Comment by QuLogic** [comment]
Google or NumPy style? There are some inconsistencies in at least `axes/_axes.py` that are causing it to choke.

**Comment by tacaswell** [comment]
We should definitely stick with numpydoc style (and put in the effort to pull all of our docstrings up to standards).

**Comment by mdboom** [comment]
Just a ditto for Numpydoc style -- that's the more prevalent one in the "scipy ecosystem".  Though my sense of napoleon is that it's a bit stricter than numpydoc and will probably find some problems in our docstrings.

**Comment by dstansby** [comment]
I think we're pretty much using numpydoc everywhere now, so I'll close this. Feel free to re-open if I'm wrong.

**Comment by QuLogic** [comment]
This is about using the Sphinx-provided napoleon extension instead of the external numpydoc one; I don't know if we still want to do that.
