### ISSUE TITLE
matplotlib 1.5 compatibility with wxPython

### ISSUE THREAD

**Issue by moonshoes87** [matplotlib/matplotlib#5737]
I'm running into a strange compatibility problem between wxPython and matplotlib.  

    import wx
    import pylab
    app = wx.App(False)
    app.frame = wx.Frame(None)
    app.frame.Centre()
    app.frame.Show()

With matplotlib 1.5.0 or higher, this code will not run -- it hangs with no error on: 

    app = wx.App(False)

If I comment out "import pylab", it works fine.  "import matplotlib" does not cause an error, but "import matplotlib.pyplot as plt" does.  

With matplotlib 1.4.2, this code works fine as is, including the pylab import.  This is with wxPython 3.0.2.0 and on OSX El Capitan.

I've looked for possible changes here: http://matplotlib.org/1.5.0/api/api_changes.html, but nothing appears relevant.  

Any ideas about what's gone wrong?

**Comment by jenshnielsen** [comment]
Sorry for not responding on this earlier. It seems to work if I explicitly set the WX/WXAgg backend before importing pylab


```python
import wx
import matplotlib
matplotlib.use('WXAgg')
import pylab
app = wx.App(False)
app.frame = wx.Frame(None)
app.frame.Centre()
app.frame.Show()
```

**Comment by jenshnielsen** [comment]
It's likely that this is related to the work in #3421 that enabled support for WXPython phoenix

**Comment by tacaswell** [comment]
If you do 

```python
from __future__ import print_function
import matplotlib.pyplot as plt
import matplotlib
print(matplotlib.get_backend())
```

what do you get?  

My suspicion here is that you are importing wx, it may or may not be installing the input hook, and then `pylab` imports some other gui framework which install's _it's_ input hook.  Your `wx` app then sets up waits for it's event loop to be run (which will never happen as python is letting the _other_ event loop run).

**Comment by moonshoes87** [comment]
I get 'Qt4Agg' as the default backend.  

If I set the backend as 'WXAgg' before importing pylab as jenshnielsen suggested, the error happens as before.

**Comment by jenshnielsen** [comment]
Can you try 1.5.1rc1? I can reproduce the hanging with 1.5.0 but not with 1.5.1rc1

**Comment by moonshoes87** [comment]
My original code still fails with 1.5.1.  However, if I add `matplotlib.use('WXAgg')`, then all works as expected.

**Comment by jenshnielsen** [comment]
In your original example you will import both WX and Qt4 since matplotlib defaults to the Qt4Agg backend and you import WX. Importing more than one GUI framework is unsupported and will in general lead to wrong behaviour. If you want to use matplotlib within a WX app you should make sure that it runs with the WX backend.

**Comment by jenshnielsen** [comment]
I think this can close, it looks like this is only triggered when more than one gui backend is involved is an unsupported way
