### ISSUE TITLE
Offset text should be computed based on lowest and highest ticks, not actual axes limits

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5738]
Now that the default margins are nonzero, picking the offset text based on the axes limits rather than the tick limits can have some unesthetic consequences:
```
plot([1e5, 1e5+1], [0, 1])
```
Old style (margins=0)
![old](https://cloud.githubusercontent.com/assets/1322974/11991234/c4383e80-a9cc-11e5-9f5a-6f026bf27004.png)
New style (margins>0)
![new](https://cloud.githubusercontent.com/assets/1322974/11991247/e9bffa76-a9cc-11e5-9463-d2a1c556c61e.png)
This is not a new issue (it can be reproduced with 1.5.0 by explicitly calling `margins`), it just got much more salient.

**Comment by tacaswell** [comment]
Closed by #5780
