### ISSUE TITLE
3D rendering, scatterpoints disapear near edges of surfaces

### ISSUE THREAD

**Issue by paitor** [matplotlib/matplotlib#5756]
Hi 

Environment: 
Linux 
python 2.7.8
matplotlib 1.5.0 (installed via pip 2015-12-29)

When plotting scattered points in combination with surfaces in 3D points disapear when viewed at an angle that renders them close to the edges of the surface along the line of sight. The code below reproduces the problem. (If the resulting figure is rotated a few degrees the scatter point will be made visible). 

    #! /usr/bin/env python
    import matplotlib
    matplotlib.use('tKAgg')
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter((0.5,), (0,), (0,))
    poly = Poly3DCollection([zip((0,0,0,0,0),(1,1,-1,-1,1),(1,-1,-1,1,1))])
    poly.set_facecolor((1,0,0,1))
    ax.add_collection3d(poly)
    ax.set_xlim3d([0,1])
    ax.set_ylim3d([-1,1])
    ax.set_zlim3d([-1,1])
    ax.view_init(elev=-165,azim=-140)
    plt.show()

regP

**Comment by WeatherGod** [comment]
See here with this FAQ:
http://matplotlib.org/mpl_toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles

Note, the documentation should be updated to also recommend VisPy for
non-trivial 3D rendering. There is talk with the VisPy developers to one
day make parts of VisPy into a matplotlib backend, but that is probably
still a year or two out from now.

**Comment by WeatherGod** [comment]
closing as "can't fix".
