### ISSUE TITLE
Several axes_grid1 and axisartist examples broken on master

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5757]
There are not really any unittest that tests this functionality so this is not caught but the following examples have changes since 1.5.0 

* inset_locator_demo1

1.5.0

![inset_locator_demo1](https://cloud.githubusercontent.com/assets/548266/12034724/467af8f8-ae35-11e5-860a-3cbc280e8875.png)

Master

![inset_locator_demo1-1](https://cloud.githubusercontent.com/assets/548266/12034728/52cb72cc-ae35-11e5-9fda-2a9790b7b320.png)

* inset_locator_demo2

1.5.0

![inset_locator_demo2-1](https://cloud.githubusercontent.com/assets/548266/12034691/dd227f0c-ae34-11e5-96d9-c95063b93496.png)

Master

![inset_locator_demo2](https://cloud.githubusercontent.com/assets/548266/12034692/e206d838-ae34-11e5-9874-b6881d00a051.png)

(http://matplotlib.org/devdocs/mpl_toolkits/axes_grid/examples/inset_locator_demo2.png)

* simple_axisline4

1.5.0

![simple_axisline41](https://cloud.githubusercontent.com/assets/548266/12034737/728626ac-ae35-11e5-932c-dd7dc19295a8.png)

Master

![simple_axisline41-1](https://cloud.githubusercontent.com/assets/548266/12034740/7735d6d4-ae35-11e5-97a9-83fbc415fe79.png)

* Simple anchored artists

1.5.0

![simple_anchored_artists1-1](https://cloud.githubusercontent.com/assets/548266/12034747/882230d2-ae35-11e5-842f-d35889fcc9a2.png)

Master

![simple_anchored_artists1](https://cloud.githubusercontent.com/assets/548266/12034788/f5ae703e-ae35-11e5-9b78-33bc087086c5.png)

It's likely that this is only one or two issues.

**Comment by jenshnielsen** [comment]
This was found doing #5752 Ironically #5752 fixes the issue with simple_axisline4 by changing the example from a axisartist axis to a regular matplotlib axis but that is of cause not a proper fix.

**Comment by mdboom** [comment]
I can bisect to hopefully find the cause.

**Comment by mdboom** [comment]
First bad commit is f88114c9a7cdb6aa9c8f90d62e36d30b7a7e48bf.  I'm working on a solution.

**Comment by mdboom** [comment]
simple_axisline4 was broken by d268abf8fd9c41fdc37b9bfeb8b1d576b4b288d3 (i.e. a different commit).

**Comment by smheidrich** [comment]
@mdboom Is [this change](https://github.com/matplotlib/matplotlib/commit/e5b5425d8eb2242912bdc977bc1d945a3fb6a320#diff-d0a331ed7b13fcf7a67d45f831157279R16) actually needed? If I remove the line on my system, the example still comes out fine.

**Comment by jenshnielsen** [comment]
@smheidrich Can you create a new issue detailing exactly which change you are referring too. The whole commit or a part of it. Commenting on a closed PR is sure to be lost in the noise.

**Comment by smheidrich** [comment]
@jenshnielsen the link has an anchor that points to the exact line I mean:
