### ISSUE TITLE
import matplotlib._png as _png ImportError: libpng16.so.16: cannot open shared object

### ISSUE THREAD

**Issue by haznav** [matplotlib/matplotlib#5765]
The error only occurs during usage in virtualenv. import matplotlib.pyplot occurs the error.I am using python 2.7.6 ubuntu 14.04.Urgent help needed please.

**Comment by tacaswell** [comment]
Try re-installing from source.  That sort of exception tends to pop up when the underlying system libpng get updated (via apt-get) but mpl does not get rebuilt.

There is not much else that we can do without a lot more information (full backtrace, how you installed mpl, mpl version, ...)

I am going to close this as I do not think there is a bug in mpl.  I suggest moving to our gitter (https://gitter.im/matplotlib/matplotlib), the mailing list (matplotlib-users@python.org), or ask a question on stackoverflow for further support.
