### ISSUE TITLE
Use Makefile for sphinx build

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5798]
#5743 reminded me:

We still use an ancient `make.py` that is based on what early versions of `sphinx-quickstart` used to generate.  We should probably modernize this to use a Makefile like current versions of sphinx create.

This is sort of low-priority, because the only _real_ advantage would be consistency with other Python projects.  The Makefile won't magically make things faster or anything.  Also, the work is non-trivial since our `make.py` includes customizations and other things that get run that will need to be ported to the "current way to do things" (probably Sphinx extensions).

**Comment by anntzer** [comment]
Closed by #9513.
