### ISSUE TITLE
mathtext kerning around comma

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5799]
When using a comma as thousands separator in tex, one should wrap it in braces to avoid a spurious space after it (http://www.tex.ac.uk/FAQ-dec_comma.html).  See below the difference between `"$1{,}234{,}567"` and `"1,234,567$"` with `text.usetext=True`.
![tex](https://cloud.githubusercontent.com/assets/1322974/12117120/4773d944-b373-11e5-8bcb-d45b45573651.png)
Unfortunately, mathtext doesn't implement this detail (`text.usetex=False`).
![mathtext](https://cloud.githubusercontent.com/assets/1322974/12117121/4774108a-b373-11e5-9ad7-53cee85cafe6.png)

(It doesn't look that bad on these zoomed images but I think the difference is more visible if you draw them e.g. using `xlabel`.)

(Yes, this qualifies as a major nitpick.)

**Comment by mdboom** [comment]
I agree it should be fixed.  Adding the `{,}` where using comma as a thousands separator seems to be the easy part.  Making `mathtext` obey the braces may or may not be a large project.

Cc: @zblz due to his recent interest in mathtext.

**Comment by anntzer** [comment]
"easy" modulo localization :/ (a quick look suggests there's "," -> "{,}", "." -> "{.}" and " " -> "\,")

**Comment by zblz** [comment]
@anntzer, @mdboom: I gave it a shot in #5813. It is a quick fix, and spaces inside the brackets will still cause it to typeset a space after.
