### ISSUE TITLE
No such file or directory: '/usr/share/matplotlib/stylelib'

### ISSUE THREAD

**Issue by juliettema** [matplotlib/matplotlib#5801]
When I try to use plt.plot(....), i've got the following error : 

for path in os.listdir(style_dir):
OSError: [Errno 2] No such file or directory: '/usr/share/matplotlib/stylelib'

Does soemone have the same? And know how to deal with? 

thank you

**Comment by tacaswell** [comment]
Did you manage to resolve this?
