### ISSUE TITLE
Barbs broken

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#5803]
I guess there were some line (or polygon edge?) changes with the new style. It turns out this broke `Barbs`. Here are the results running the `barb_demo.py` example.

Good (1.5.x):
![barbs_good](https://cloud.githubusercontent.com/assets/221526/12131765/af95395a-b3d2-11e5-95b1-e5b918497799.png)

Bad (master):
![barbs_bad](https://cloud.githubusercontent.com/assets/221526/12131771/ba76da5e-b3d2-11e5-8d78-4cacfa541812.png)

It turns out that there are **0** tests for the `Barbs` code. I'm willing to submit a PR to fix the problem and add some tests (probably just knock off the demo). Since I think I've seen mention of similar issues elsewhere, can someone point me to what exactly needs to be added, maybe some kind of edge/line style or color?

**Comment by jenshnielsen** [comment]
I have not looked at the barbs code at all but from the images alone it looks similar to #5757 fixed by #5759. Especially the filled=False part

**Comment by tacaswell** [comment]
I have the same suspicion.

**Comment by mdboom** [comment]
Unfortunately, in this case, barbs require both filled and unfilled parts, so `filled=False` isn't sufficient.  I'd recommend just setting a default linewidth for barbs with something like:

```diff
diff --git a/lib/matplotlib/quiver.py b/lib/matplotlib/quiver.py
index aef58c9..d7b9012 100644
--- a/lib/matplotlib/quiver.py
+++ b/lib/matplotlib/quiver.py
@@ -922,6 +922,9 @@ class Barbs(mcollections.PolyCollection):
             kw['edgecolors'] = barbcolor
             kw['facecolors'] = flagcolor
 
+        if 'linewidth' not in kw:
+            kw['linewidth'] = 1
+
         # Parse out the data arrays from the various configurations supported
         x, y, u, v, c = _parse_args(*args)
         self.x = x
```

**Comment by tacaswell** [comment]
This is someplace where that kwarg normalization function I have in https://github.com/matplotlib/matplotlib/pull/5056 would be nice to use here to make sure we don't clobber 'lw'.
