### ISSUE TITLE
matplotlib.pyplot.boxplot ignored showmeans keyword

### ISSUE THREAD

**Issue by cswarth** [matplotlib/matplotlib#5816]
I'm trying to suppress all graphical elements of a boxplot in order to take advantage of the scaling it provides for subsequent point plots.  Unless I'm misunderstanding the intent of the `showmeans` keyword, it appears to not work as advertised.  

[edit : wait - that red line is the median, isn't it?   `showmeans` probably doesn't do what I think it does and I need to some other keyword to suppress the red line and the small vertical lines too.]

```
import sys
import matplotlib.pyplot as plt
import numpy as np
print("python", sys.version)
print("matplotlib version", matplotlib.__version__)
print("numpy version", np.__version__)
# fake up some data
spread = np.random.rand(50) * 100
center = np.ones(25) * 50
flier_high = np.random.rand(10) * 100 + 100
flier_low = np.random.rand(10) * -100
data = np.concatenate((spread, center, flier_high, flier_low), 0)

# basic plot
plt.boxplot(data, showcaps=False, showmeans=False, showbox=False, showfliers=False)

plt.show()
```

![screen shot 2016-01-08 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/295428/12212346/165a2072-b61e-11e5-8a20-5b5c54fc5e1b.png)

**Comment by cswarth** [comment]
Does not look like a bug, just special case.  I can suppress the red horizontal line and vertical blue lines through `medianprops` and `whiskerprops`, respectively.

```
import sys
import matplotlib.pyplot as plt
import numpy as np
print("python", sys.version)
print("matplotlib version", matplotlib.__version__)
print("numpy version", np.__version__)
# fake up some data
spread = np.random.rand(50) * 100
center = np.ones(25) * 50
flier_high = np.random.rand(10) * 100 + 100
flier_low = np.random.rand(10) * -100
data = np.concatenate((spread, center, flier_high, flier_low), 0)

# basic plot
medianprops = {'linewidth': 0}
whiskerprops = {'linewidth': 0}

plt.boxplot(data, showcaps=False, showfliers=False, showbox=False,
                  medianprops=medianprops, whiskerprops=whiskerprops)

plt.show()
```
![screen shot 2016-01-08 at 4 34 33 pm](https://cloud.githubusercontent.com/assets/295428/12212979/c3a650a0-b625-11e5-9151-6e89a841b783.png)

**Comment by tacaswell** [comment]
It seems there should be an easier way to adjust the limits...
