### ISSUE TITLE
1.5.1rc1: dont use absolute links in the "new updates" on the homepage

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#5819]
Hello,
in the orange banner on the top of the documentation homepage, the "new updates" is absolute link, please change it to a relative one, so taht it will work also on the off-line doc:

```
@@ -178,13 +71,12 @@
 ">
 <h3>We're updating the default styles for Matplotlib 2.0</h3>
 
-<p>Learn what to expect in the <a href="/style_changes.html" style="font-weight: bold;
+<p>Learn what to expect in the <a href="style_changes.html" style="font-weight: bold;
 color: #11557C;">new updates</a></p>
 
 </div>
```

in doc/_templates/layout.html

**Comment by tacaswell** [comment]
This is also a bit of a moot point because the banner will be gone in 2.0.

**Comment by sandrotosi** [comment]
well, if you added that banner in 1.5 to prepare the users to the changes in 2.0, I think it should work, and not redirect to a not existing page if you build and use the doc locally

**Comment by tacaswell** [comment]
The suggested change to fix this breaks the link on every other page https://travis-ci.org/matplotlib/matplotlib/jobs/101451335

**Comment by QuLogic** [comment]
The relevant commit was reverted; reopening.
