### ISSUE TITLE
Consider using an offline copy of Raleway font

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#5821]
Hey there! similar to https://github.com/matplotlib/matplotlib/issues/5820, mpl doc refers to the Raleway font using the url http://fonts.googleapis.com/css?family=Raleway which might not be accessible if totally offline but if you can access it, it will breach the privacy of the user. Please consider using an offline version of the font (or another one).

**Comment by tacaswell** [comment]
Have you also noticed the google analytics code in the website :smiling_imp: ?

This one is pretty easy as we don't actually use that font anywhere in the docs right now.

Long term we are not going to commit to not using web fonts, they are a core part of modern web technology.  I think we can commit to providing a 'paranoid' option to the doc build process that will strip this sort of thing out.

As a side note,  Raleway does appear to be packaged by debian (https://lists.debian.org/debian-mentors/2014/07/msg00033.html).  That link pulls a snippet of ccs that defines the font face.  If the font is available locally it will be used, else it will reach out to google to get it.

**Comment by sandrotosi** [comment]
I did https://github.com/matplotlib/matplotlib/issues/5823 :)

What I meant to ask is an option to disable it (not to stop using them completely, I totally understand they make perfect sense on the main website), if you are extra paranoid, so yeah the --paranoid option would be great!
