### ISSUE TITLE
Recompute figsize-dependent parameters on resize

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5824]
Edit: See https://github.com/matplotlib/matplotlib/issues/5824#issuecomment-256202440 for the doc related issue.

Currently, applying tight_layout and resizing the figure do not commute (e.g., after `subplots(2); tight_layout()` and a manual maximization of the figure size, applying `tight_layout` again changes the margins).  This is basically due to the fact that certain paddings (and text sizes) are in absolute units, which is fairly reasonable.

However, it would be nice if an option was available to add a callback to figure resize events to auto-re-tightlayout when that happens.

> _The following part is solved by the yet-to-be-merged #5772_.
> This kind of feature may become even more useful now that #5588 (number of ticks determined from physical length of axis) has been merged, as the number of ticks should, well, also be adjusted when the figure is resized (or rather, the option to do so should be (easily) available).

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/5772 re-computes the number of ticks on the fly

**Comment by anntzer** [comment]
Actually, manually adding the callback is as simple as
```
fig.canvas.mpl_connect("resize_event", lambda _: fig.tight_layout())
```
so just a note in the docs may be enough.

(I am a bit confused as to why the callback (to which no other reference is kept) does not get garbage collected though.  I never really liked the fact that only a wearkref is kept to callbacks so I'm not complaining about it... just asking.)

**Comment by anntzer** [comment]
Actually, even better is to just use `fig.set_tight_layout()`, or the rcparam associated with it.  This could be mentioned in the tight layout guide (http://matplotlib.org/devdocs/users/tight_layout_guide.html), so I'm turning this into a doc issue.
