### ISSUE TITLE
extra label for non-existent tick

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5841]
After
```
rcParams["xtick.direction"] = rcParams["ytick.direction"] = "out"
xlim(4.001, 8)
```
There is an extra label at `x=4.0`, but (correctly) no tick there:
![extralabel](https://cloud.githubusercontent.com/assets/1322974/12286246/58aee1d6-b977-11e5-83d6-e0a38d2e2a25.png)

Probably a rounding issue, e.g. it doesn't appear using `xlim(4.005, 8)`.  I understand that some tolerance in floating point comparison is needed, but at least the same should be used for both ticks and labels (i.e. I wouldn't necessarily consider it a bug if both a tick and a label appeared when the lower xlim is e.g. 4+1e-10).

Sadly not solved by #5768.

PS: I guess this is going to be much more visible now that the default style has ticks pointing outwards...

**Comment by mdboom** [comment]
Some rough notes as we go through: See axis.py:253 for where we determine if things appear or not.  I suspect we just need to put the label drawing inside of the `if midPoint` block as well.

**Comment by anntzer** [comment]
Your solution seems to work.

**Comment by tacaswell** [comment]
Did a PR for this fix ever get created?
