### ISSUE TITLE
what is  the source  code of ax.pcolormesh(T, R, Z,vmin=0,vmax=255,cmap='jet') ?

### ISSUE THREAD

**Issue by shanyuk** [matplotlib/matplotlib#5843]
@_autogen_docstring(Axes.pcolormesh)
def pcolormesh(*args, **kwargs):
    ax = gca()
    # allow callers to override the hold state by passing hold=True|False
    washold = ax.ishold()
    hold = kwargs.pop('hold', None)
    if hold is not None:
        ax.hold(hold)
    try:
        ret = ax.pcolormesh(*args, **kwargs)
        draw_if_interactive()
    finally:
        ax.hold(washold)
    sci(ret)
    return ret

**Comment by mdboom** [comment]
If this is a question, please post to the matplotlib-users mailing list.  The issue tracker should be used for tracking known bugs.
