### ISSUE TITLE
Bar and box plots use the 'default' matplotlib colormap, even if the style is changed

### ISSUE THREAD

**Issue by halflings** [matplotlib/matplotlib#5851]
I originally thought this was an issue with pandas ( https://github.com/pydata/pandas/issues/12029 ), but I can reproduce it by using matplotlib alone.

After changing the style to "fivethirtyeight" (with pyplot.style.use("fivethirtyeight") ) and changing the default colormap (via rcParams), both bar plots and boxplots still use the default colors:

    plt.plot([0, 1, 2, 3], [5, 6, 7, 8])
    plt.plot([0, 1, 2, 3], [6, 3, 7, 12], alpha=0.5)

![lineplot](https://cloud.githubusercontent.com/assets/1626936/12325626/bf6bf6c0-bacb-11e5-8c72-8f1c399d0343.png)

    plt.bar([0, 1, 2, 3], [5, 6, 7, 8])
    plt.bar([0, 1, 2, 3], [6, 3, 7, 12], alpha=0.5)

![barplot](https://cloud.githubusercontent.com/assets/1626936/12325656/00d5b272-bacc-11e5-910b-1ab8059ec64e.png)

    plt.boxplot([6, 3, 7, 12, 20, 25, 33])

![boxplot](https://cloud.githubusercontent.com/assets/1626936/12325620/b18f4e80-bacb-11e5-8400-a7aa92bfcd16.png)

The code I used to customize the plotting style can be found on the pandas issue (like I said, it's mostly just setting the style to fivethirtyeight then changing the color cycle)

**Comment by mdboom** [comment]
I think this is fixed by #5598.

**Comment by halflings** [comment]
Great!

Seems like the pandas people did a work around to fix this ( https://github.com/pydata/pandas/pull/11865 ), I hope both fixes won't conflict with each other :)

**Comment by jenshnielsen** [comment]
@mdboom I remember that we talked about this issue sometime back but Is that the right PR? It only related to mplot3d as far as I can see

**Comment by mdboom** [comment]
Sorry -- I mistyped the PR number.  It's #5593.

**Comment by halflings** [comment]
Since it seems like this was addressed previously, closing the issue. Thanks!
