### ISSUE TITLE
Marker style request

### ISSUE THREAD

**Issue by euhruska** [matplotlib/matplotlib#5861]
Is it possible to have a MarkerStyle which is a rectangle? I have a scatterplot where the spacing in x- and y-direction is different, so a marker with different sizes in x- and y-direction would be useful.

**Comment by efiring** [comment]
You can make custom markers by specifying vertices or a Path object:
http://matplotlib.org/api/markers_api.html#module-matplotlib.markers
http://matplotlib.org/examples/pylab_examples/marker_path.html?highlight=marker_path
