### ISSUE TITLE
\left( ... \right) are too small

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5863]
All's in the title.  Both with 1.5.0 and the current HEAD (with which the screenshot was produced)
```
title("$\\left(1.234\\right)$")
```
![screenshot_20160116_200947](https://cloud.githubusercontent.com/assets/1322974/12375921/a043ea1e-bc8d-11e5-8057-aabd738fbf62.png)

Yes, I know \left and \right are not necessary here.  OTOH some code that generates LaTeX strings (e.g. the uncertainties packages, where I noticed this first) just always use \left and \right as that avoids having to parse the contents to know whether they're needed, which seems fair game.

**Comment by tacaswell** [comment]
attn @zblz

**Comment by tacaswell** [comment]
Exactly what source string produced that image?

**Comment by anntzer** [comment]
Edited original post.

**Comment by tacaswell** [comment]
Thanks

**Comment by zblz** [comment]
I put up a fix in #5871, so that it tries to use the regular parens (and the DejaVu ones) when the text inside is close to regular text.

**Comment by zblz** [comment]
Fixed in #5871
