### ISSUE TITLE
Useless Dvi dispatch docs in dvi_read api docs

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5873]
Compare http://matplotlib.org/devdocs/api/dviread.html#matplotlib.dviread.Dvi.dispatch to  http://matplotlib.org/api/dviread.html this seems like it should be excluded

**Comment by mdboom** [comment]
Agreed.  :+1:

**Comment by jenshnielsen** [comment]
Sorry the 2 link was wrong. Updated to point to the 1.5.1 docs

**Comment by QuLogic** [comment]
Is this really a problem on `v2.x`? I can't find any `Dvi.dispatch`, only a `_dispatch` on a different class. There _is_ `Dvi.dispatch` on `master`, though.

**Comment by QuLogic** [comment]
I built docs locally and can't find any `Dvi.dispatch`, so I'm bumping to 2.1.
