### ISSUE TITLE
Manual linestyle specification ignored if 'prop_cycle' contains 'ls'

### ISSUE THREAD

**Issue by Chroxvi** [matplotlib/matplotlib#5875]
If the `axes.prop_cycle` contains the label 'ls' it is not possible to manually specify a linestyle in a plot. However, if `axes.prop_cycle` contains the label 'linestyle', everything seems to work as expected.

An example showing the problem:

```Python
from cycler import cycler
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
mpl.__version__  # ==1.5.1

linestyle_cycle = cycler('linestyle', ['-', '--'])
ls_cycle = cycler('ls', ['-', '--'])

x = np.arange(10)

mpl.rcParams['axes.prop_cycle'] = linestyle_cycle
plt.figure()
for k in range(1, 6):
    plt.plot(x, k * x)
plt.plot(x, x**2, 'k:')  # Black dotted as expected
plt.title('linestyle_cycle')

mpl.rcParams['axes.prop_cycle'] = ls_cycle
plt.figure()
for k in range(1, 6):
    plt.plot(x, k * x)
plt.plot(x, x**2, 'k:')  # Black dashed - not expected
plt.title('ls_cycle')
```

![linestyle_cycle](https://cloud.githubusercontent.com/assets/5367057/12392263/f2a97cd6-bded-11e5-93fe-5c480e4b7e7f.png)
![ls_cycle](https://cloud.githubusercontent.com/assets/5367057/12392264/f2aa189e-bded-11e5-8c3b-e0db4465c1c1.png)

**Comment by tacaswell** [comment]
Thanks for reporting this.

**Comment by WeatherGod** [comment]
This might be the normalization bug we are seeing elsewhere. I have code
that normalizes the key names from 'ls' to 'linestyle', but it seems to
only trigger for cycles defined from the rc file. If a cycle object is
passed in, it just uses it as-is. Unfortunately, I needed that
normalization feature to simplify the cycle advancing feature. The
linestyle given by 'k:' is compared with the properties from the cycler.
Only properties from the cycler that doesn't exist in the manual
specification are taken. Unfortunately, without normalization, it sees "ls"
from the cycler, and "linestyle" from the manual spec and doesn't know that
they are the same thing. The "ls" value then overrides the "linestyle"
value when setting the artist properties.

**Comment by WeatherGod** [comment]
@tacaswell, we probably need to set a minimum version of cycler to depend
on so that I can write a patch that utilizes the "key_change()" feature I
added to cycler awhile back. Have you released a version with that feature?

**Comment by tacaswell** [comment]
No, we need to do new release of cycler.

**Comment by WeatherGod** [comment]
Might also be worth considering monkey-patching cycler if it is missing the
change_key() method. I *think* all the relevant logic is contained within
that method, I'll have to double-check that PR.
