### ISSUE TITLE
New colormaps : Inferno, Viridis, ... 

### ISSUE THREAD

**Issue by Aston630** [matplotlib/matplotlib#5883]
Hi,

I wanted to try today the new exciting colormaps that come with the 1.5.0 version of Matplotlib. I quickly discovered I could not use them the same as the previous colormaps. Indeed, in the past I used to do:

```python
import matplotlib as mpl
cmap = mpl.cm.get_cmap("jet", nb_curves)

# where cmap is LinearSegmentedColormap and from there get the colors the following way in order to
# handle them the way I wanted for a set of curves or points or arrows etc... :
colors = cmap(np.arange(nb_curves))
```
Now with the new colormaps I do the same:

```python
import matplotlib as mpl
cmap = mpl.cm.get_cmap("inferno", nb_curves)
```
where cmap is now a ListedColormap and I cannot do what I used to do before.

My first question would be : why this difference between old and new colormaps?
Then, is there a way I could get a LinearSegmentedColormap from Inferno, Viridis, etc... ? This is really what I want.

Thanks a lot for your time and considering this issue!

**Comment by tacaswell** [comment]
What is your use case that you need a `LinearSegmentedColormap` instead of a `ListedColormap`?  It looks like the only missing method on `ListedColormap` is `set_gamma`.

**Comment by Aston630** [comment]
Well, it is just that in the detailed example above, cmap is now being a ListedColormap object instead of usually being a LinearSegmentedColormap. In that case I cannot do:
colors = cmap(np.arange(nb_curves))
when I use "inferno" instead of "jet".

**Comment by efiring** [comment]
I think this accomplishes what you want, doesn't it?
```python
from matplotlib.cm import inferno
import numpy as np
nbcurves = 20
colors = inferno(np.arange(nbcurves))
```

**Comment by Aston630** [comment]
Thank you very much for your answer. It gives back that error:

colors = inferno(np.arange(files))
TypeError: unsupported operand type(s) for -: 'dict' and 'int'

**Comment by QuLogic** [comment]
Have you tried with 1.5.1? The code from @efiring seems to work for me as well.

**Comment by Aston630** [comment]
Yes, I am really sorry, my bad, you are right, no bug. In that case, `inferno` is still a `ListedColormap` and `colors` only contains the `20` first colors inside the colormap, but doesn't give you a nice gradient of colors adapted to the number of curves you have, i.e., for 20 curves with `inferno` I only get black curves moving towards gray. Do you what I mean? Is there no way to get this `LinearSegmentedColormap` object from `ListedColormap`?

**Comment by efiring** [comment]
My mistake, but one small change fixes it.  Use
```python
colors = inferno(np.arange(20, dtype=float))
```

**Comment by Aston630** [comment]
Thanks again, but it seems it still does not work, it gives me back a list of colors with the first element being black (one edge of the colormap), then the second element and the 18 others are pale yellow (the other edge of the colormap I guess).

**Comment by QuLogic** [comment]
You can do:
```python
colors = inferno(np.linspace(0, inferno.N, nbcolors))
```

**Comment by QuLogic** [comment]
Hmm, no, I should probably have tested that out, since it doesn't work either...

**Comment by Aston630** [comment]
Thanks again, I deeply sorry to bother you with that. Yes it still does not work, I get the same result as my last message as you said.

**Comment by efiring** [comment]
OK, I still wasn't thinking straight.  Do this:
```python
colors = inferno(np.linspace(0, 1, nbcolors))
```

**Comment by Aston630** [comment]
That is perfect! Solved :). Thank you very much for your precious help!
