### ISSUE TITLE
matplotlib stepfilled histogram breaks at the value 10^-1 on xubuntu

### ISSUE THREAD

**Issue by kxf010** [matplotlib/matplotlib#5885]
Why is it that when the code in the text file is run through python the graph seems to break down at 10^-1 on the y-axis?
[hist.txt](https://github.com/matplotlib/matplotlib/files/96760/hist.txt)

```python
from pylab import *

bins = [+0.000e+00,+1.000e+00,+2.000e+00,+3.000e+00,+4.000e+00,+5.000e+00]
wght = [[+3.000e-02,+7.0e-02,+3.0e-01,+5.0e-01,+8.0e-01]]

hist([ bins[:-1] for i in range(len(wght)) ], bins=bins, weights=wght, histtype="stepfilled", log=True )

ylim(bottom=0.01); ylim(top=1.0)

savefig("./output.pdf")
```

What it should look like: https://gyazo.com/b57ad2c8fb67580caf7e6296f33fa86e

What it actually looks like: https://gyazo.com/22470f9d7c9a46316061ca1c7874ac33

**Comment by tacaswell** [comment]
Can you please include the code in-line?  What exactly do you mean by 'break down'?

**Comment by kxf010** [comment]
I meant to add pictures, here they come.

**Comment by kxf010** [comment]
By "break-down" I mean the graph doesn't plot past 10^-1 on the y-axis

**Comment by QuLogic** [comment]
With what version? The code you provided works fine with 1.4.3 and 1.5.0. (And on a side note, you shouldn't really use `pylab`.)

**Comment by kxf010** [comment]
It looks like the version on Windows is 1.4.3 and Xubuntu's is 1.3.1. I downloaded the 1.5.1 and re ran the code and the graph is the same. Also instead of getting 1.5.1 when I execute this, python -c 'import matplotlib; print(matplotlib.__version__)' , I get 1.3.1 so for some reason the version hasn't changed.

**Comment by kxf010** [comment]
@QuLogic Why do you recommend against the use of pylab?

**Comment by WeatherGod** [comment]
pylab shouldn't be used for scripting. It really should only be for
interactive situations where you want conciseness. We have been working on
getting rid of scripting examples of pylab, because "explicit is better
than implicit" and "namespaces are a honking good idea". The other fun
thing that happens is that np.min(), np.max(), np.any() and np.all()
overrides the built-in min(), max(), any() and all(), which can cause very
subtle issues in some edge cases.

**Comment by tacaswell** [comment]
They are not even that edge:

```python

In [26]: min((i for i in range(3)))
Out[26]: 0

In [27]: import numpy as np

In [28]: np.min((i for i in range(3)))
Out[28]: <generator object <genexpr> at 0x7fcd58ccfca8>
```

or more fun

```python

In [32]: bool(np.all((0 for j in range(5))))
Out[32]: True

```

**Comment by WeatherGod** [comment]
We really should get around to taking advantage of the single-dispatch
system to register those functions for array-like inputs and get pylab to
not clobber the builtins.

**Comment by kxf010** [comment]
Thanks! Also, are there any known workarounds for when an older version is in use?

**Comment by WeatherGod** [comment]
yeah, don't use pylab... (actually, there is a real workaround, but it is
extremely convoluted. We implemented it in matplotlib for certain internal
uses, but perhaps it makes sense to export it somehow?

**Comment by tacaswell** [comment]
See https://stackoverflow.com/questions/18774388/re-import-aliased-shadowed-python-built-in-methods for how to get the original functions back.

However, this has been side tracked from the original bug.   What version of mpl are you using?

**Comment by kxf010** [comment]
I'm using both 1.5.1 and 1.3.1. My goal is to try and get a working bit of code on 1.3.1 so users will be able to use the code without having to update matplotlib as 1.3.1 is the latest in Ubuntu's Software Center(USC). For some reason it hasn't actually updated to 1.5.1 on the USC.

**Comment by tacaswell** [comment]
It looks like there is not a direct work-around with 1.3.1.  The best course of action would be to do your histograming via numpy

```python
bins, edges = np.histogram(data)
```

and then ship a version of the code in https://github.com/matplotlib/matplotlib/issues/643#issuecomment-63762568 to do the plotting.

We definitely will not be releasing a 1.3.2.
