### ISSUE TITLE
How can I plot the  text of data on a map with "contour()" 

### ISSUE THREAD

**Issue by ZhaoZhonglun1991** [matplotlib/matplotlib#5887]
![_2016-01-20t08-48-08 293z](https://cloud.githubusercontent.com/assets/16795914/12445861/c102d636-bfa1-11e5-857d-74c849662d61.png)

**Comment by tacaswell** [comment]
@dopplershift I think this overlap with your scatter text PR?

**Comment by dopplershift** [comment]
#4063 is absolutely relevant here, which I've recently updated (locally) to fit in with master. I probably should push my changes and try to get a design discussion in earnest.

I will note that in its current form, `scattertext()` doesn't handle the colormapping that is exhibited in the example above.
