### ISSUE TITLE
Polar Plot axis reversal and zero positioning producing strange results with quiver()

### ISSUE THREAD

**Issue by jomu9721** [matplotlib/matplotlib#5888]
I will start with image examples.

This is a quiver plot of the data I am trying to plot.  This data is correctly plotted on the default axes.
![vector_field](https://cloud.githubusercontent.com/assets/3028399/12455994/1fd51f8a-bf5b-11e5-998a-34e947f5a7da.png)

When I move the zero position to North, I get the following:
![vector_field_zero_north](https://cloud.githubusercontent.com/assets/3028399/12456045/682d5806-bf5b-11e5-999e-521c6f704698.png)
as can be seen, the data is NOT being plotted correctly once the zero position is changed.

To make things worse, I need to present my data clockwise.  When I change the direction to clockwise, I get the following:

![vector_field_zero_north_clockwise](https://cloud.githubusercontent.com/assets/3028399/12456116/9ff3eba6-bf5b-11e5-9b02-149a95b6b046.png)

As can be seen, the results are no where near correct,or what would be expected.  The plot should be able to be rotated and mirrored without changing the way the data is plotted.

If anyone can help me out on how to fix this, I would be grateful. 

Here is a quick snippet of my plotting code:

``` python
dt = Br1[0.0] * numpy.cos(thetaSlice1) - Bt1[0.0] * numpy.sin(thetaSlice1)
dr = Br1[0.0] * numpy.sin(thetaSlice1) + Bt1[0.0] * numpy.cos(thetaSlice1)

N = numpy.sqrt(dt**2 + dr**2)

fig5 = plt.figure()
ax5 = fig5.add_subplot(111, polar=True)
ax5.set_aspect(1.0)
ax5.set_theta_zero_location("N")
ax5.set_theta_direction(-1)
ax5.quiver(thetaSlice1, rSlice1, dt/N, dr/N)

ax5.set_title("Unit Vector Field for B\n\n "
              "(North at $0^{\circ}$, South at $180^{\circ}$)\n")

ax5.set_ylim(0, rStop)
plt.savefig(imageDirectory + 'vector_field_zero_north_clockwise.png', format='png', dpi=1000)
plt.show()
```

A detailed look at the plot will show that the position of the arrows is being rotated to the correct place, but the arrows themselves are not being rotated to the new (correct) directions.

**Comment by tacaswell** [comment]
attn @efiring

**Comment by efiring** [comment]
I'm a little surprised quiver works at all with anything other than a Cartesian projection; but since it does work with the default polar projection, it must be possible to correct the problems with non-default versions.  I think those polar options are quite recent additions.
@jomu9721 would you provide some stripped-down standalone test case code, please?

**Comment by mdboom** [comment]
I think it probably works with the default polar projection somewhat "by accident"...

**Comment by jomu9721** [comment]
@efiring ... here is a stripped down standalone example.  This is the example I am working on at the moment.  I have commented out the axis shift functions.  Putting them back in will produce the observed behavior.

-Josh

``` python
# Author: Joshua Murphy
# Purpose: Dipole Grid Exploration
# Date: 12 January 2016
#
# Description: This is an early attempt at creating a 3-D dipole around Earth.
#               For this exerscise, I am using multiple 2D grids, each
#               representing a different Phi. The grid starts at 1Re to
#               eliminate the singularity at the origin.  Each segment of the grid
#               is from 0 to 180 degrees to make for full continuity around the
#               Z-axis.  In this situation, theta of 0 degree is the + Z axis (North).
#               180 degrees is the -Z axis (South).
######################################################################################

# Packages Needed
import numpy
import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams.update({'figure.autolayout': True})

# Methods
def dipoleGrid(rStart, rStop, rStep, thetaStart, thetaStop, thetaStep, phiStart, phiStop, phiStep):
    Br = {}
    Bt = {}
    Bp = {}
    # Constants
    B0 = 3.12e-5
    Re = 1.0
    # build the grid intervals
    theta = numpy.linspace(thetaStart, thetaStop, thetaStep)
    phi = numpy.linspace(phiStart, phiStop, phiStep)
    r = numpy.linspace(rStart, rStop, rStep)
    # Convert to Radians
    theta *= (numpy.pi / 180)
    phi *= (numpy.pi / 180)
    # build the theta,r mesh
    rSlice, thetaSlice = numpy.meshgrid(r, theta)
    # generate the magnetic field (Dipole).
    # This for loop will generate the entire grid magnetic field
    B0 += rSlice * 0
    Re += rSlice * 0

    for phiUnit in phi:

        B01r3 = B0 * ((Re * (rSlice)**-1) ** 3)
        Br[phiUnit] = (-2 * B01r3) * (numpy.cos(thetaSlice))
        Bt[phiUnit] = (-1 * B01r3) * (numpy.sin(thetaSlice))
        Bp[phiUnit] = thetaSlice * 0 + phiUnit  # This is a hack to get it the right size...

    return rSlice, thetaSlice, Br, Bt, Bp


# output file location
imageDirectory = '../AIP/images/'

# grid start/end point settings
rStart = 1
rStop = 10

thetaStart = 0
thetaStop = 180

phiStart = 0
phiStop = 360

# build the course grid
rSlice1, thetaSlice1, Br1, Bt1, Bp1 = \
    dipoleGrid(rStart=rStart, rStop=rStop, rStep=10,
               thetaStart=thetaStart, thetaStop=thetaStop, thetaStep=18,
               phiStart=phiStart, phiStop=phiStop, phiStep=36)

dt = Br1[0.0] * numpy.cos(thetaSlice1) - Bt1[0.0] * numpy.sin(thetaSlice1)
dr = Br1[0.0] * numpy.sin(thetaSlice1) + Bt1[0.0] * numpy.cos(thetaSlice1)

N = numpy.sqrt(dt**2 + dr**2)

fig5 = plt.figure()
ax5 = fig5.add_subplot(111, polar=True)
ax5.set_aspect(1.0)
# ax5.set_theta_zero_location("N")   #Matplotlib bug -- this distorts the plotted data. Reported as Issue #5888
# ax5.set_theta_direction(-1)        #Matplotlib bug -- this distorts the plotted data. Reported as Issue #5888
ax5.quiver(thetaSlice1, rSlice1, dt/N, dr/N, pivot='middle')


ax5.set_title("Unit Vector Field for B\n\n "
              "(North at $0^{\circ}$, South at $180^{\circ}$)\n")

ax5.set_ylim(0, rStop)
plt.savefig(imageDirectory + 'vector_field.eps', format='eps', dpi=1000)

plt.show()

**Comment by dstansby** [comment]
Here's a slightly smaller minimal example (I am currently looking into this):

```
import matplotlib.pyplot as plt
import numpy as np

x = 0
y = 0.5

ux = 0
uy = 1

ax = plt.subplot(projection='polar')
ax.set_theta_zero_location("N")
ax.quiver(x, y, ux, uy)
ax.set_ylim(top=1)
plt.show()
```

This produces the following figure; the arrow should be rotated and pointing to the left:

![figure_1](https://cloud.githubusercontent.com/assets/6197628/22177489/829cfd72-e016-11e6-8e26-82444caa67c2.png)

**Comment by dstansby** [comment]
Reading from the `quiver` docstring:
```
angles : {'uv', 'xy'} or array-like, default: 'uv'
    Method for determining the angle of the arrows.

    - 'uv': Arrow direction in screen coordinates. Use this if the arrows
      symbolize a quantity that is not based on *X*, *Y* data coordinates.

      If *U* == *V* the orientation of the arrow on the plot is 45 degrees
      counter-clockwise from the  horizontal axis (positive to the right).

    - 'xy': Arrow direction in data coordinates, i.e. the arrows point from
      (x, y) to (x+u, y+v). Use this e.g. for plotting a gradient field.
```
The original code seems to be behaving as promised. With the default `angles='uv'` the u, v coordinates are specifying the angle in screen coordinates, so when you rotate the polar axes all the arrows aren't rotating with it. So I think the solution to this issue is to specify `angles='xy'`. If you do that does that solve the issue? For my simple case above it does seem to solve the issue.

**Comment by timhoffm** [comment]
Assuming this was a misconception regarding the *angles* parameter.
