### ISSUE TITLE
Factual errors in HowTo FAQ Box Plot Image 

### ISSUE THREAD

**Issue by madphysicist** [matplotlib/matplotlib#5889]
The image describing Tukey's box/violin plots has some factual errors. I am referring to the image at http://matplotlib.org/_images/boxplot_explanation.png, shown on http://matplotlib.org/faq/howto_faq.html#interpreting-box-plots-and-violin-plots.

  - The text for Q3 should read "Third Quatrile (threshold so that 75% of the data points fall below Q3)". ("above" -> "below")
  -  Outlier description should read "value < Q1 - 1.5 x IQR or value > Q3 + 1.5 x IQR". ("Q3 +" -> "Q3 -", and the inequality needs to be split up.)

**Comment by tacaswell** [comment]
Please open a PR with the text fixes.

**Comment by madphysicist** [comment]
I would be glad to. I would like to contact the original author to get the source of the image (e.g. svg or gimp project) first though. Otherwise there will probably be a change in the font or something.

**Comment by rasbt** [comment]
Sorry about that, I received an email from @madphysicist about this typo. I just searched my hard drive(s) and found a slightly version of this plot, let me know if it works for you. Otherwise, let me know what you'd like to change, and I'd be happy to help.

[boxplot.pdf](https://github.com/matplotlib/matplotlib/files/98639/boxplot.pdf)
![boxplot](https://cloud.githubusercontent.com/assets/5618407/12471138/ac5a230c-bfc8-11e5-8fea-7786b27707a3.png)

**Comment by madphysicist** [comment]
@rasbt This version is much better. I think that `Q1 - 1.5 x IQR > value > Q3 + 1.5 x IQR` needs to be split into two inequalities since it is an OR condition rather than an AND: `Q1 - 1.5 x IQR > value or Q3 + 1.5 x IQR < value`.

**Comment by rasbt** [comment]
sure! I found the keynote file and updated it accordingly (see attachment)
[boxplot.pdf](https://github.com/matplotlib/matplotlib/files/98716/boxplot.pdf)

**Comment by madphysicist** [comment]
Looks good to me. Would you mind also creating the PR? I expect that you know which file to replace better than I do.

**Comment by rasbt** [comment]
No problem! Done in #5894 . Thanks for reporting the issue and resolving it! 
Cheers,
Sebastian

**Comment by jenshnielsen** [comment]
#5894 was merged so closing this
