### ISSUE TITLE
Broader-ranged viridis cousin?

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#5890]
I really like viridis for mapping line or point data, but I've found myself wishing that it had a bit more dynamic range on the lightness dimension for image data. It's largely a matter of personal preference, but given that there are a few options for the red family of matplotlib colormaps, I thought it might be nice to have at least another option in the green family. I've been playing around with the wonderful viscm tool and have come up with something that I like a little bit better for image data:

![image](https://cloud.githubusercontent.com/assets/315810/12467772/18a4b288-bf93-11e5-8b0c-d861ff6cc9c8.png)

It ends up being rather similar to YlGnBu, but with a wider lightness range and constant perceptual deltas.

I was going for a relationship with `viridis` that is similar to the relationship between `magma` and `plasma`.

Is this something matplotlib would be interested in including? Symmetry is nice, so I or someone else could also add a colormap in the green family that is similar to `inferno` (also a wider lightness range, but more chroma at the top end).

**Comment by efiring** [comment]
Yes, I would support including it.  All you need is a clever name for it...

**Comment by mwaskom** [comment]
I was thinking "caninus". It is less mellifluous than "viridis" (and may be Latin overload), but it is [thematically appropriate](https://en.wikipedia.org/wiki/Emerald_tree_boa).

**Comment by mwaskom** [comment]
Maybe ["vernalis"](https://en.wikipedia.org/wiki/Smooth_green_snake) would be good.

**Comment by tacaswell** [comment]
:+1:  to latin and the extra color map.

we should also think about providing a clean(er) way for external packages it install color maps someplace mpl will find and automatically register color maps.

**Comment by efiring** [comment]
On 2016/01/20 2:49 PM, Michael Waskom wrote:
> Maybe "vernalis" <https://en.wikipedia.org/wiki/Smooth_green_snake>
> would be good.

That's it!

**Comment by QuLogic** [comment]
There is an ever-so-slight kink in the blue that if you strain your eyes enough, you might see. But it's a bit more obvious in the colour-blindness tests. Such a kink does not occur with viridis. I'm not sure if extending the lightness range will preclude getting rid of the kinks.

**Comment by njsmith** [comment]
I have nothing useful to add, but this is awesome.

**Comment by pelson** [comment]
>  external packages it install color maps someplace mpl will find and automatically register color maps.

entry points are our friends. This would be an excellent use for them.

**Comment by tacaswell** [comment]
@pelson how do entry points work ?

**Comment by njsmith** [comment]
I think the idea is that [entry points](https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins) give matplotlib a way to say "Hey, every package installed on the system, listen up! Can you tell me if you have any colormaps for me?"

I'm not sure what the value would be, really... you can already write `imshow(..., cmap=extpackage.awesome_cmap)`; does it really add much if we teach matplotlib to do `for pkg in list_of_random_external_packages: from pkg import *` so that you can instead write `imshow(..., cmap="awesome_cmap")`? Namespaces are one honking great idea! and all that.

**Comment by WeatherGod** [comment]
I thought every named colormap gets registered anyway? If not, maybe it
should?

**Comment by pelson** [comment]
> I thought every named colormap gets registered anyway? If not, maybe it should?

There is no registry from which matplotlib can pull colormaps which aren't part of core matplotlib and which haven't yet been imported.

For instance, I know that Iris ships with some of the brewer colormaps (its a long story, but this was before any brewer packages existed). From time to time we get reports of things like: "Hey, I can do ``plt.contourf(data, cmap='cool_brewer_palette')`` but it only works after I ```import iris```, what gives?".

Using entrypoints, for packages to register colormaps would allow us to provide a hook for package maintainers to "install" colormaps. Essentially, entry points are just a named key which map to a (normally callable) python object. It wouldn't be hard to plumb matplotlib to look at a specific entry point, to find any colormap that has been named by another package, but which hasn't yet been imported.

> Namespaces are one honking great idea! and all that.

A sound point @njsmith. I can certainly see an argument which says that entry points hide the origin of colormaps, and that package namespaces are certainly more explicit. That said, we are already in a position where matplotlib's colormaps are namespace-less (we have a global dict of cmaps), so we already suffer from that (as per the example above).

I'm sort of interested in the idea of pulling all the colormaps, and everything which does "color" out of matplotlib and into its own package. Given your history @njsmith, I know there would be things that aren't already in matplotlib which would make a lot of sense to be included in such a package...

**Comment by njsmith** [comment]
Ah, sure, if packages are going to be monkeypatching matplotlib's cmap namespace regardless, then using entry points may make that somewhat more predictable. (Of course the downside is that now, if there is a namespace collision between two packages, then your code can now potentially now be broken by some package that it doesn't even import -- merely installing some package to the same venv can change its behavior.)

**Comment by endolith** [comment]
looks more like https://commons.wikimedia.org/wiki/File:Coiledblueracersnake.jpg to me :)

also "vernalis" sounds a little too similar to "viridis"?

**Comment by njsmith** [comment]
@mwaskom: I'd be happy to add this to the the colormaps at github.com/BIDS/colormap if you're OK with releasing it as CC0.

**Comment by mwaskom** [comment]
Sure I just need to recall where I saved the dang .py file

**Comment by efiring** [comment]
I would still welcome a PR to install this in mpl as "vernalis" alongside "viridis"; apart from @endolith's disagreement with the name, is there any opposition to this?

**Comment by tacaswell** [comment]
I agree that the names are a bit too close and +1 to shipping this with mpl.

**Comment by thisch** [comment]
@mwaskom can you come up with a PR please?

**Comment by QuLogic** [comment]
@efiring Do you want to bump the milestone here like the other colour map PRs?

**Comment by mwaskom** [comment]
Oops sorry for dropping the ball here. For the record here is the colormap: https://gist.github.com/mwaskom/9f4c519e185637a4d0a7dd7bd900207e

**Comment by efiring** [comment]
Sorry this has to be delayed, but it is not central to getting 2.0 out, and we are having great difficulty doing that.

**Comment by mwaskom** [comment]
Not a problem!

**Comment by mwaskom** [comment]
Closed with addition of the "mako" colormap to seaborn.

**Comment by waldyrious** [comment]
I would like to resurrect these plans and submit a PR, if that's OK. My proposal would be to make it closer to Viridis, though, which perhaps would make the name similarity more justified.

Example images:

| Viridis: | [New proposal](https://github.com/waldyrious/wide-viridis): |
|:----------------------------------:|:-----------------------------:|
| ![viridis](https://user-images.githubusercontent.com/478237/34467296-512511f6-eee5-11e7-88b8-a1a36fba5830.png) | ![wide-viridis](https://user-images.githubusercontent.com/478237/34467300-57d2578e-eee5-11e7-9535-d42c3f93e1f6.png) |
| **Mako:** | **Vernalis:** |
| ![mako](https://user-images.githubusercontent.com/478237/34467301-5ab1507c-eee5-11e7-9c34-db677c8e865b.png) | ![vernalis](https://user-images.githubusercontent.com/478237/34467298-540bf524-eee5-11e7-9b3e-0acb5542f97a.png) |

Note how Mako and the original Vernalis proposal forgo Viridis' characteristic yellow tint in the high luminance regions. On the other hand, Mako retains the purplish tone in the dark regions. I could adjust the proposal to match those tones in the darker section of the color map, if that's desired. For that, I'd need access to the viscm parameters of Mako, which don't seem to be available [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/cm.py#L264-L521). (I made a [viscm-type script based on that data](https://gist.github.com/waldyrious/5d9108835221f44ce99626644d77051f), but without the parameters, the colormap can only be viewed in viscm, not edited.)

My questions would then be:

- Would such a colormap still be welcome for inclusion?
- If so, would it be OK to name this new variant "Vernalis", superseding the definition originally proposed here?
- If not, would inclusion of the original Vernalis (the color map, not necessarily the name) be preferred? Or perhaps Mako?

Looking forward to hear your thoughts.

(Also pinging @inversed-ru, who wrote about Viridis' reduced lightness range [here](http://inversed.ru/Blog_2.htm).)

**Comment by tacaswell** [comment]
A while ago @njsmith proposed as format for specifying colormaps (https://github.com/njsmith/json-cm/blob/master/json-cm-spec.md ).  I think the best path forward here is to pick up that work and get a reader into Matplotlib.  This would make it much easier to provide third-party color maps.  

If someone wants to champion it I would be interesting in seeing a repo in the matplotlib `mpl-colormaps` for hosting color map variations (a-la https://matplotlib.org/cmocean/ ).
