### ISSUE TITLE
Polar Projection PDF Issue

### ISSUE THREAD

**Issue by avipersin** [matplotlib/matplotlib#5895]
Python 3.4
Conda 3.18.3
Matplotlib 1.5.1
basemap 1.0.7
Adobe Reader XI

Trying to plot a polar projection with a custom shapefile results in an error when opening the PDF in Adobe Reader. 

I am creating two orthographic projections (a southern and northern hemisphere).
```
basemaps.append(Basemap(projection='ortho', lon_0=270, lat_0=90., resolution='c', ax=axes[0]))
basemaps.append(Basemap(projection='ortho', lon_0=90, lat_0=-90., resolution='c', ax=axes[1]))
```
I then draw a full world shapefile on each projection:
```
basemap.readshapefile('Earth', 'globe')
...
plt.savefig('amaps.pdf')
```
Everything works fine here and both basemaps display with the proper lines and shapes drawn. However, when downloading the PDF and displaying it in Adobe Acrobat, you will get something like this: 
[amap.pdf](https://github.com/matplotlib/matplotlib/files/99791/amap.pdf) (which looks fine if you view it in your browser, but try downloading it and opening it with Adobe Reader).  We've determined that the problem arises when the coastline includes lon, lat pairs in the opposite hemisphere from the hemisphere that it is to be drawn in. So if you are drawing the southern hemisphere, you cannot read a shapefile that has lon, lat points in the norther hemisphere, and vise-versa.

Our workaround required creating two separate shapefiles, one for the northern hemisphere and one for the southern.  So now it looks like this:
```
# drawing northern hemisphere
if polar and idx == 0:
    basemap.readshapefile('Earth_north', 'nh')
elif polar and idx == 1:
# drawing southern hemisphere
    basemap.readshapefile('Earth_south', 'sh')
# drawing all other projections
else:
    basemap.readshapefile('Earth', 'globe')
```
This works fine but shouldn't be necessary.

**Comment by mdboom** [comment]
It seems (at least on first read) that this is a basemap, not a matplotlib issue.  Would you mind filing this under matplotlib/basemap, and feel free to reopen this issue if there's something on the matplotlib side that needs to be addressed.

**Comment by WeatherGod** [comment]
but, why would it be a basemap issue in particular? Basemap doesn't have
any PDF specific code that I am aware of.

**Comment by mdboom** [comment]
Sorry -- I missed that it was PDF specific.  I'll reopen.

**Comment by mdboom** [comment]
Can you provide a complete example (with fake data) so I can reproduce?

**Comment by avipersin** [comment]
>Can you provide a complete example (with fake data) so I can reproduce?

Here is a link to the GitHub repo I made to illustrate the issue: https://github.com/avipersin/BasemapPDF.git

If you run basemap.py and open map.pdf in Adobe Reader you will see the problem.

**Comment by tacaswell** [comment]
> but try downloading it and opening it with Adobe Reader

Can we claim that adobe is not implementing their own spec right?  :smiling_imp: 

With acroread 9.5.5 it looks correct, but gives a cryptic warning in a modal window.  Is that the problem?

The attached file opened fine with chromium, firefox, and okular.

**Comment by WeatherGod** [comment]
For posterity, what was the cryptic error message?

**Comment by tacaswell** [comment]
I have sense removed acrobat, but from memory it was something like "This PDF is wrong, contact those who created it"

**Comment by mdboom** [comment]
Thanks.  With this I'm able to reproduce, on both Mac Adobe Reader DC 2015 and Linux 9.5 (which was discontinued and is fairly old at this point).  Both pop up a dialog saying there is a problem with the file, but both seem to provide no additional information.  This will be a fun puzzle :scream:

**Comment by mdboom** [comment]
I should add: On Acroread 9.5 on Linux is looks correct.  On a Mac with DC 2015, it looks like this:

<img width="357" alt="screen shot 2016-01-25 at 1 55 04 pm" src="https://cloud.githubusercontent.com/assets/38294/12560939/565b0510-c36b-11e5-9a94-1eb50f8afa16.png">

**Comment by mdboom** [comment]
The issue is that some shapes being drawn have shapes that are entirely made up of large numbers (1e30).  My best guess is that these are continents entirely on the other side of the projection.  These shapes aren't fully clipped by matplotlib's clipping algorithm -- instead a single "MOVETO" operation a location of (1e30, 1e30) is written out.  I suspect this is what is tripping up Acrobat Reader.  (The PDF spec doesn't really talk about range of numbers, but it's reasonable that they would reject numbers this large given that PDF is optimized for sheets of paper no larger than, say, a small planet).

Fixing the clipping algorithm to be careful about everything it emits seems to fix the issue.  See #5911.
