### ISSUE TITLE
Incorrect Image Tutorial Inline Sample Code

### ISSUE THREAD

**Issue by katzenbaer** [matplotlib/matplotlib#5900]
The inline/inpage sample code under the [Array Interpolation schemes](http://matplotlib.org/users/image_tutorial.html#array-interpolation-schemes) heading is incorrect. However, the Source Code linked below the inline code is correct. 

For example, see `In[20]`:
```
In [20]: imgplot = plt.imshow(resized, interpolation="nearest")
```
which links to [image_tutorial-9.py](http://matplotlib.org/users/image_tutorial-9.py).

This sample code assumes the users has followed the previous inline sample code:
```
In [16]: from PIL import Image
In [17]: img = Image.open('../_static/stinkbug.png')
In [18]: resized = img.thumbnail((64, 64), Image.ANTIALIAS) # resizes image in-place
In [19]: imgplot = plt.imshow(img)
```

As shown on `In [18]`, the thumbnail function resizes the image **in-place**. This means that `resized` is an empty variable and cannot be passed into `plt.imshow()`. The inline sample code should instead follow the downloadable sample code and pass `img` into `plt.imshow()`.

**Comment by tacaswell** [comment]
Can you open a pull request to fix the example?

**Comment by katzenbaer** [comment]
A fixed has been merged.

**Comment by katzenbaer** [comment]
I'm on [the website right now](http://matplotlib.org/users/image_tutorial.html) and it looks like it's still giving visitors a cached version of the page without this fix. Can we regenerate the page?

**Comment by tacaswell** [comment]
The website has been rebuilt and deployed.
