### ISSUE TITLE
Unclear Documentation ticker class

### ISSUE THREAD

**Issue by avipersin** [matplotlib/matplotlib#5908]
Difficult to understand what the second argument "presets" does in this function: http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.LinearLocator. 

"Use presets to set locs based on lom. A dict mapping vmin, vmax->locs"

A clearer explanation of what this parameter is and does would be nice.

**Comment by petehuang** [comment]
Need guidance on reading the code...it's looking to me like you can pass in your own ticker locations to use via `presets`, but it also seems like the `(vmin, vmax)` key you use in presets has to match the post-transform (vmin, vmax) of the axes?

Is that right? In the end, we just need to say this in simple english, right? "Use presets to directly set ticker locations. `presets` should be a dict that maps `(vmin, vmax)` to a list of locations."
