### ISSUE TITLE
The documentation for LinearLocator's presets keyword is unclear

### ISSUE THREAD

**Issue by ngoldbaum** [matplotlib/matplotlib#5909]
http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.LinearLocator

"Use presets to set locs based on lom. A dict mapping vmin, vmax->locs"

This uses abbreviations that aren't defined (`lom` in particular) and doesn't clearly explain why you would want to use it.

**Comment by ngoldbaum** [comment]
Oops, this was filed by someone else already!

**Comment by jenshnielsen** [comment]
For reference this is #5908
