### ISSUE TITLE
exceeds Locator.MAXTICKS

### ISSUE THREAD

**Issue by jdborg** [matplotlib/matplotlib#591]
This is just a question, rather that a bug submission:

Does this error mean I trying to plot too many points?
RuntimeError: Locator attempting to generate 171560 ticks from -8575.1 to 2.85: exceeds Locator.MAXTICKS

**Comment by kilojoules** [comment]
Nevermind! I found it.

    locator = mdates.HourLocator(interval=1)
    locator.MAXTICKS = 1500
    ax.xaxis.set_major_locator(locator)
