### ISSUE TITLE
Headless get_window_extent or equivalent

### ISSUE THREAD

**Issue by Immortalin** [matplotlib/matplotlib#5916]
Is it possible to call `get_window_extent` headlessly? In a third party library, it is currently failing because it requires a renderer but the output is actually a headless html file so there is no way to determine the boundaries at runtime. Refer (https://github.com/plotly/plotly.py/issues/381)

**Comment by tacaswell** [comment]
You can use the `Agg` backend which does not require a gui framework, but you will need to trigger a draw before you try to access the window extent.  There are some number we really do not know until the first time the figure gets drawn.

What backend are you using?

**Comment by Immortalin** [comment]
How do you trigger a draw without displaying anything?
