### ISSUE TITLE
improved dash styles

### ISSUE THREAD

**Issue by njsmith** [matplotlib/matplotlib#5917]
Reviewing the changes in #5774, I realized that one of the original proposals from the BoF, of fixing up the dash styles to be less terrible, got lost somewhere along the way. IMO the current non-solid dash styles are pretty much unusable. Each on its own might be okay, but when you use them on the same plot (and isn't the whole point of these that you put them on the same plot to make it easier to tell lines apart?), then they have wildly varying visual weights and the dotted style in particular is almost invisible. (This is similar to the problem with the old color cycle, where some colors high much higher contrast than others; fixing that required switching to a set of isoluminant colors. Similarly, we should make the dash style closer to isoluminant.)

Here's a quick mock-up of a better set of dash styles. Left is #5774; right is #5774 + better dash styles:

![dashes-color-2](https://cloud.githubusercontent.com/assets/609896/12572266/c30ab6d2-c39e-11e5-897d-709c4d7f98ee.png)

![dashes-black-and-white-2](https://cloud.githubusercontent.com/assets/609896/12572277/e9a98728-c39e-11e5-8f41-3e3c1248d98f.png)

(Code: https://gist.github.com/njsmith/ad4958cd1eb674fbed67)

The reason this is an issue rather than a pull request is that it looks like currently the dash styles are hard-coded constants in `GraphicsContextBase` and can't be touched by the RC system, and I'm not familiar enough with the life-cycle of `GraphicsContext` objects and their interaction with the RC system to fix this without some hints. Happy to make a PR if someone points me in the right direction :-)

**Comment by tacaswell** [comment]
:+1:  Sorry this got lost.

**Comment by mdboom** [comment]
:+1: from me as well.  I'll probably throw an implementation of this (based on the numbers in @njsmith's gist) on the #5774 pile.

**Comment by mdboom** [comment]
As for implementation, @njsmith is right about things being too hard-coded at present.  I see at least two ways forward:

1. Add an rcParam that is a dictionary from line style short names to numbers.  This seems like the most flexible option, but could create some confusion between adding line styles to the `prop_cycle` and just the linestyle-name mapping.  (This isn't really more-than-one-way-to-do-it -- it's very different things, but it could be a bit obscure/confusing to outsiders).

2. Use different numbers based on the `_internal.classic_mode` rcParam.  Less confusing, but not as flexible.

**Comment by njsmith** [comment]
Making the stroke units be proportional to the line width is probably a good idea, but I guess more work and could be done as a separate step later?

I guess I should point out that I haven't done any research on how other systems handle dash styles. Even a quick attempt is a big improvement though :-)

On a side note. I know it's been a long road and a lot of effort, but I am really surprised how *much* better things look in #5774 compared to 1.5. Even

**Comment by njsmith** [comment]
... this trivial plot has what, at least for different substantial style improvements? 2.0 is going to rock :-) thanks for all the work you put in making it real!

**Comment by mdboom** [comment]
Thanks for the reminder about dash styles being proportional to width.  That's something I've been meaning to fix for a long time.  I think we can tie that behavior to our special backward compatibility flag (`_internal.classic`).  I think we should definitely do that while we're at it.

**Comment by efiring** [comment]
Regarding using width as the unit for dash length: you might need to have some minimum value. I suspect that strict scaling would not work well for very thin lines.

**Comment by mdboom** [comment]
> Regarding using width as the unit for dash length: you might need to have some minimum value. I suspect that strict scaling would not work well for very thin lines.

That's a good point.  Some sort of function from linewidth to dash length will likely need to be applied.
