### ISSUE TITLE
How to rotate secondary y axis label so it doesn't overlap with y-ticks, matplotlib

### ISSUE THREAD

**Issue by hselbie** [matplotlib/matplotlib#5920]
![figure_2](https://cloud.githubusercontent.com/assets/9560230/12592609/f9711e9a-c421-11e5-8a04-8b10650f4308.png)
I am trying to rotate my secondary y-label to 270 degrees, but when I do this passing the rotate=270 argument it overlaps my y-tick text? I can fix the problem with labelpad but I think this might be a bug, perhaps using pandas?

fig, ax = plt.subplots()

ax.plot(df.index,df.tripTime,label='Fishing Effort', marker='D')
ax2=ax.twinx()
ax2.plot(tr.index,tr.cost, 'g',label='Fuel Expenditure', marker='d')

lines = ax.get_lines() + ax2.get_lines()
ax.legend(lines,[line.get_label() for line in lines], loc='lower left')
ax.set_ylim((0, 18))

ax2.set_ylabel('Cost ($)',color='g', rotation=270)

for tl in ax2.get_yticklabels():
    tl.set_color('g')

ax.set_ylabel('Fishing Effort (hrs)')
ax.set_xlabel('Time (days)')
plt.show()

**Comment by tacaswell** [comment]
Try adding `va='top'` to the call to `set_ylabel` as well?

**Comment by productivememberofsociety666** [comment]
Works with ``va="bottom"``. My bad, I pointed them here from http://stackoverflow.com/q/35020409/2748899 .

**Comment by efiring** [comment]
This does not seem to be a bug report, so I am closing it.
