### ISSUE TITLE
Feature Request: Error Ellipses and Ellipsoids

### ISSUE THREAD

**Issue by mohawkjohn** [matplotlib/matplotlib#5933]
It'd be great if there were methods in pyplot for printing error ellipsoids to represent multivariate Gaussian distributions.

Here's an outline of how to do it in two dimensions: http://www.visiondummy.com/2014/04/draw-error-ellipse-representing-covariance-matrix/

It's fairly straightforward to extrapolate to ellipsoids from ellipses.

**Comment by tacaswell** [comment]
You can do this with `Ellipse` artists: http://matplotlib.org/examples/pylab_examples/ellipse_demo.html

**Comment by fergalm** [comment]
I've just written such a function in 2 dimensions for myself. I'd be happy to contribute it if there's enough interest.

**Comment by mohawkjohn** [comment]
Is there an Ellipsoid artist? Maybe that's what my feature request should be.

I can provide code in n dimensions for the error ellipsoids, but my code doesn't rely on an artist, unfortunately. My Python is a bit rusty.

**Comment by KanwarGill** [comment]
@mohawkjohn  @tacaswell Can you provide more clarification regarding what you are proposing here? Do you want to have an _Ellipsoid_ artist to be in place that will help you with your requirements?

**Comment by bhargavvader** [comment]
Is this still of interest? Can I have a shot at this - and if so, any guidelines?

**Comment by tacaswell** [comment]
Presumably this would be methods on Axes/Axes3D which take care of the details of constructing the ellipse, adding it to the axes and then return the ellipse artist.

**Comment by mohawkjohn** [comment]
I have some code I can dig up to verify what you do, but I can't share it because proprietary (and anyway, not as clean as one would like for an actual releasable product). =(

With that said, I'm happy to provide input. Feel free to drop me a gchat (email is on my github).

**Comment by anntzer** [comment]
This was discussed recently in the mailing list (https://mail.python.org/pipermail/matplotlib-devel/2019-February/001214.html) and the agreement was that this should go to the docs as an example.

**Comment by anntzer** [comment]
This is now at https://matplotlib.org/gallery/statistics/confidence_ellipse.html
Feel free to PR more improvements to it :)
