### ISSUE TITLE
tricontourf got tearing while tricontour performed reasonable with nan values

### ISSUE THREAD

**Issue by barpaum** [matplotlib/matplotlib#5943]
I made a whole in a matploblib triangulation with nan values. The tricontour results are well represented, but the tricontourf got tearing. Please see the attached image.
I have another experience that matplotlib will consume increasing memory with many nan values until crash.

![snapshot125](https://cloud.githubusercontent.com/assets/3433058/12669254/053194e2-c69a-11e5-9fb6-7f513fa54993.png)

**Comment by ianthomas23** [comment]
`tricontour` and `tricontourf` expect `z` arrays containing values that are all finite.  NaNs, infs and masked arrays are not supported.

If you don't want to contour all of a triangulation, then either:
a) use a new triangulation containing only the triangles you are interested in, or
b) use a mask on the original triangulation, as in [tricontour_demo.py](http://matplotlib.org/examples/pylab_examples/tricontour_demo.html)

We need to make the requirements on `z` explicit in the documentation, and probably add explicit checks in the code too.
