### ISSUE TITLE
Calling subplots_adjust breaks savefig output

### ISSUE THREAD

**Issue by AdamSerafini** [matplotlib/matplotlib#5946]
On Mac OSX, `matplotlib==1.5.1`, in a Virtualenv the following program saves the scattergraph output correctly to `output.png`:

    import matplotlib
    matplotlib.use('TkAgg')

    import numpy as np
    import matplotlib.pyplot as plt

    if __name__ == '__main__':
        N = 50
        x = np.random.rand(N)
        y = np.random.rand(N)
        colors = np.random.rand(N)
        area = np.pi * (15 * np.random.rand(N))**2
        plt.scatter(x, y, s=area, c=colors, alpha=0.5)
        plt.savefig('output.png')

However, after introducing a call to `subplots_adjust`, the output in `output.png` is blank:

    import matplotlib
    matplotlib.use('TkAgg')

    import numpy as np
    import matplotlib.pyplot as plt

    if __name__ == '__main__':
        N = 50
        x = np.random.rand(N)
        y = np.random.rand(N)
        colors = np.random.rand(N)
        area = np.pi * (15 * np.random.rand(N))**2
        plt.scatter(x, y, s=area, c=colors, alpha=0.5)
        plt.subplots_adjust(
            left=0.125,
            right=1.5,
            bottom=3.3,
            top=5,
            wspace=0.4,
            hspace=0.8)
        plt.savefig('output.png')  # results in a empty/blank .png

Is this a bug or am I using it wrong?

(I realise there are no subplots to adjust here: the above is a simplification, this was noticed in the context of a bigger script which does have subplots).

**Comment by jenshnielsen** [comment]
As far as I remember the values are fraction of the figure size so when you are setting them to something larger than 1 you are probably moving the plot outside the figure.

**Comment by AdamSerafini** [comment]
I see. When I run the script in IPython notebook and view the plot 'inline' it looks fine with those values which confused me (perhaps the way it scales the image output in IPython is different than when saving to file).

**Comment by AdamSerafini** [comment]
Thanks for putting me on the right track @jenshnielsen Closing the issue.

**Comment by jenshnielsen** [comment]
The inline backend does an unusual step where it trims off any extra white space. That probably causes the plot back into the centre. We should probably do some input validation on these parameters to prevent something like this happening again. 


The parameters are documented here http://matplotlib.org/api/figure_api.html?highlight=subplots_adjust#matplotlib.figure.SubplotParams

**Comment by tacaswell** [comment]
`inline` use `bbox='tight'` in it's save command.  The intention of the flag was to trim off _extra_ whitespace, but has the side effect of _expanding_ to capture things outside of the figure area.  It is one of those 'features' which I do not think was intended to as it is used, but that we can never fix.
