### ISSUE TITLE
imshow rendering issue

### ISSUE THREAD

**Issue by mcspritz** [matplotlib/matplotlib#5959]
Hi, I'm plotting this simple graph and I got non equal pixel sizes for the graph, it happens with all kind of sizes and dpi.
(I'm using matplotlib 1.5.0, python 3.5.1)
I can prove with some pictures as well if needed (I'm not sure if the bug is in matplotlib or in the renderer).

```python
from matplotlib import use
use('Agg')
import matplotlib.pyplot as plt
import numpy as np

t = np.random.randn(64, 64)
fig, ax = plt.subplots()
ax.imshow(t, interpolation='none', origin="lower")
plt.savefig(
    'crap29.png',
    format='png'
)
plt.close()`
```

Thanks

**Comment by jenshnielsen** [comment]
Im not completely sure I understand what you issue is. Your code is plotting an image and not a graph? Please attach the image that you save not as a prof but to demonstrate what you are talking about.

**Comment by mcspritz** [comment]
Sorry, I knew it wasn't easy to explain.
I traced a line on the graphs and noticed that "pixes" of the imshow are not all of the same size.

![crap29](https://cloud.githubusercontent.com/assets/1878127/12752822/2fbceef8-c9bc-11e5-8023-3104a6b161c7.png)
![crap29-zoomed](https://cloud.githubusercontent.com/assets/1878127/12752830/333f519c-c9bc-11e5-923c-24c3b54bb708.png)

**Comment by jenshnielsen** [comment]
The issue sounds somewhat related to #5520 which is fixed by the rather large image rewrite in #5718 but I am not sure

**Comment by tacaswell** [comment]
Does it work correctly with 'nearest'?

**Comment by mcspritz** [comment]
Nope, I also tried to raise the dpi but no luck.
![nearest-zoomed](https://cloud.githubusercontent.com/assets/1878127/12755795/d95d94a6-c9c8-11e5-9565-7d5958ffdf29.png)

**Comment by jenshnielsen** [comment]
We have merge large changes to the image algorithm in to master and 2.x @mcspritz if possible could you try testing this on the 2.x branch or master?

**Comment by mcspritz** [comment]
Hi, I'm a newbie and want to know a simple thing, I built the cloned v2.x branch and it shows version 1.5.1+282.g918e80e, is this correct or I'm doing something wrong?

Thanks.

**Comment by jenshnielsen** [comment]
Yes that means that its 1.5.1 + 282 new commits on top of that which is the current state of the 2.x branch

**Comment by mcspritz** [comment]
Thanks,

So, the image is much better, I found for low number of pixels that column 0 has a pixel less.
![matplotlib-16x16](https://cloud.githubusercontent.com/assets/1878127/13252135/237cac3a-da35-11e5-9e3e-8c23f8a32d6c.png)

For bigger images things get more complicated.
![matplotlib-320x256](https://cloud.githubusercontent.com/assets/1878127/13252134/237c6964-da35-11e5-9ac4-9759dea97312.png)

**Comment by mdboom** [comment]
I think what we're seeing here is the case where the scaling factor from data points to on-screen pixels is not an integer multiple.  Imagine a 64x64 array scaled up to 200x200pixels.  Since 64 does not divide into 200 evenly, it's inevitable that not all data points will be rendered at the same size.  If I were seeing data points that were more than one pixel different in size, I'd be worried, but in the first example I'm seeing data points of 6 or 7 pixels, and in the last example 1 or 2 pixels.  So I'm not sure we could logically do any better (other than adding a mode and the inevitable complexity that would always ensure an integral scaling factor).

**Comment by mdboom** [comment]
Closing this, as I don't think there's a bug here, but feel free to continue to comment.
