### ISSUE TITLE
track bdist_wheel release and remove the workaround when 0.27 is released

### ISSUE THREAD

**Issue by janschulz** [matplotlib/matplotlib#5961]
See https://bitbucket.org/pypa/wheel/issues/91/cannot-create-a-file-when-that-file#comment-25194078

The workaround is this: https://github.com/matplotlib/matplotlib/blob/master/patched_bdist_wheel.py

**Comment by jenshnielsen** [comment]
Just noticed that wheel 0.28 came out so I guess this is ready to go?

**Comment by JanSchulz** [comment]
Unfortunately, conda still has 0.26 :-(

Seesm we should add a check for `bdist_wheel.__version__ >= "0.28.0"` in setup.py...

**Comment by JanSchulz** [comment]
Ok, conda got updated, so it seems that can be removed... Will do...

**Comment by dopplershift** [comment]
Done in 0f424a0be.
