### ISSUE TITLE
xkcd example in gallery

### ISSUE THREAD

**Issue by fariza** [matplotlib/matplotlib#5965]
The xkcd examples in the gallery (http://matplotlib.org/1.5.1/examples/showcase/xkcd.html) don't render with the correct font.

![xkcd_00](https://cloud.githubusercontent.com/assets/1490153/12800102/b9669958-caa0-11e5-903d-87b90e817535.png)

**Comment by jenshnielsen** [comment]
That's probably just because @tacaswell didn't have it installed when building the docs. The travis build version renders correctly http://matplotlib.org/devdocs/examples/showcase/xkcd.html

**Comment by tacaswell** [comment]
Gah sorry i will take care of that tonight

**Comment by tacaswell** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/199813/12879529/a2ea4eb2-ce02-11e5-9ea9-09df470aa773.png)
