### ISSUE TITLE
Accepting pathlib.Path as path inputs?

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#5968]
pandas recently made the great effort to accept pathlib.Paths as inputs where traditionally strings would have to be provided for any path related requirements. Could this be done also for matplotlib?

**Comment by WeatherGod** [comment]
We don't do much in the way of path manipulations, and we do need to be
compatible with the various backends we use, so internally, I don't see us
using anything else but strings. That said, it is probably feasible to make
sure that we cast those objects into strings.

**Comment by michaelaye** [comment]
That was all I was dreaming of so that I don't have to do the casting all the time! ;)

**Comment by WeatherGod** [comment]
If you can come up with a list of functions that will need to do this
casting, that would be a huge step towards getting a PR together.

**Comment by michaelaye** [comment]
I will, just not this month, which looks like the busiest of my life… ;)

**Comment by aragilar** [comment]
It's worth noting that there's now a path protocol outlined in https://www.python.org/dev/peps/pep-0519/. Using it you call os.fspath on a path to get a string/bytes view of the path, and the function is easy enough to backport (I've done this for h5py already). I'll try to submit a pull request in the next few days which adds this, should it be against master, or would this be small enough to the maintenance branches?

**Comment by tacaswell** [comment]
Please target it at 2.x.

**Comment by anntzer** [comment]
Closed by #10231.

**Comment by LukeIreland1** [comment]
I think this has regressed? I'm getting `ValueError: fname must be a PathLike or file handle` with `plt.savefig(Path("fitness/fitness1.png"))` works with `plt.savefig(str(Path("fitness/fitness1.png")))`

**Comment by tacaswell** [comment]
@LukeIreland1 Please open a new issue with your version details etc.
