### ISSUE TITLE
Add support for PySide2 (Qt5)

### ISSUE THREAD

**Issue by thliebig** [matplotlib/matplotlib#5971]
[PySide2](https://github.com/PySide/pyside2) is under active development and it would be nice to add support for it in matplotlib

PySide2 would be an alternative for PyQt5 as a qt5agg backend.

This should not be too difficult, since PySide2 and PyQt5 should offer the same interface.

**Comment by tacaswell** [comment]
Any chance you could help out with this?  

We shim all of our Qt import through `matplotlib.backend.qt_compat.py`.  The would would mostly be adding the correct import there and updating `setupext.py` to look for the new external dependency.

**Comment by thliebig** [comment]
I'm just now having a look into it.

**Comment by thliebig** [comment]
I have created a commit, that allows my test example to run with PySide2, what next? Create a pull request?

**Comment by tacaswell** [comment]
Yes please.

**Comment by thliebig** [comment]
Ok, done. That was easier as I though... Thanks
