### ISSUE TITLE
legend needs logic to deal with new linestyle scaling by linewidth

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#5977]
#5926 improves the linestyle dot and dash patterns, but with a wide line, legend does not show a long enough segment to show the pattern.

**Comment by WeatherGod** [comment]
A possible suggestion to solve this problem is to scale the width of the
swath by the linewidth, kind of like maintaining an aspect ratio.

**Comment by efiring** [comment]
This can be handled manually by the user by specifying the `rcParams['legend.handlelength']` appropriately, so this is  not urgent.  Something like @weathergod's suggestion can be implemented later if we find that this would be a substantial improvement in convenience.  If so, this can be reopened.
