### ISSUE TITLE
Increased tick width in 3D plots looks odd

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5981]
The first image in the devdocs repo (on [this commit](https://github.com/matplotlib/devdocs/commit/12e74bc4d2d839538cc8922b1ead4150c922da74)) with the updated style is a 3D plot:
![2dcollections3d_demo](https://raw.githubusercontent.com/matplotlib/devdocs/12e74bc4d2d839538cc8922b1ead4150c922da74/_images/2dcollections3d_demo.png)

In 2D, the increased tick width may be okay, but in 3D, it really stands out and I personally don't think it looks too good. Maybe if the axes lines were also increased in width, it would look a bit more consistent.

**Comment by jenshnielsen** [comment]
I think this can close we have reduced the line width again
![2dcollections3d_demo](https://cloud.githubusercontent.com/assets/548266/15482508/faad7dd6-2127-11e6-96b0-de9b7db8d157.png)

**Comment by WeatherGod** [comment]
Not sure what would have fixed that. The two PRs that addresses this (and other) issues are still pending.

**Comment by jenshnielsen** [comment]
Afaik we reduced the default 2d linewidth after this issue was created.

**Comment by QuLogic** [comment]
It's still slightly inconsistent, but definitely better looking than before.

**Comment by WeatherGod** [comment]
When the devdocs get built with the latest fixes, we should double-check that all is well. Hopefully, Travis will be all caught up by tomorrow, I guess?

**Comment by QuLogic** [comment]
The image in the doc is a bit small, but running locally confirms the ticks are of reasonable size now.
