### ISSUE TITLE
Styles need update after default style changes

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#5982]
Looking at the dev docs, I just noticed in the examples of the style sheets that these have changed. I suppose due to the changes in the default style, that now some more rcparams have to be set in the style sheets to keep the same style.

For example, the bmh style: http://matplotlib.org/examples/style_sheets/plot_bmh.html, and on master: http://matplotlib.org/devdocs/examples/style_sheets/plot_bmh.html

**Comment by QuLogic** [comment]
Fixed by #6019.
