### ISSUE TITLE
Outward ticks cause labels to be clipped by default

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5987]
In the [unicode demo](http://matplotlib.org/devdocs/examples/text_labels_and_annotations/unicode_demo.html), text in the xlabel is clipped because the outward ticks push the label down:
![unicode demo](http://matplotlib.org/devdocs/_images/unicode_demo.png)
In 1.5.2, this works fine by default:
![unicode demo](http://matplotlib.org/_images/unicode_demo.png)

This example doesn't use `tight_layout`, but there is nothing complicated here (just a single `Axes`) and I think it should be handled correctly by default.

**Comment by overdetermined** [comment]
Interestingly, I had this problem frequently in version 1.5.1.

**Comment by QuLogic** [comment]
Just as a note that this is not caused by the accented characters, [here](http://matplotlib.org/devdocs/examples/pylab_examples/color_demo.html) is another demo that clips the labels.

**Comment by mdboom** [comment]
The best fix is probably to move in the axes margins on all four sides.  The title at the top will still be too close, however, so there'll be some other fix needed there.

**Comment by jenshnielsen** [comment]
This should be fixed by #6468

**Comment by efiring** [comment]
closed by #6468
