### ISSUE TITLE
rainbow_text example is missing some text

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5988]
The [rainbow text example](http://matplotlib.org/devdocs/examples/text_labels_and_annotations/rainbow_text.html) is missing the text on the right side (see [original](http://matplotlib.org/examples/text_labels_and_annotations/rainbow_text.html)), because the spacing between each word seems to be bigger.

It seems like `text.get_window_extent()` returns something bigger, even though the text appears to have the same size. However, when I try it locally, the figure size is different, but the text remains within the figure.

**Comment by efiring** [comment]
The problem seems to be that the dpi used to show and/or save the figure must the one used when the transforms are generated for each section of text.

**Comment by tacaswell** [comment]
Closing this as the updated example is better.
