### ISSUE TITLE
Scatter markers do not follow new colour cycle

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5990]
See [scatter_profile](http://matplotlib.org/devdocs/examples/pylab_examples/scatter_profile.html) or [scatter_hist](http://matplotlib.org/devdocs/examples/axes_grid1/scatter_hist.html).

If I understood the code correctly, it _should_ be using `patch.facecolor`, but somewhere along the line that doesn't get applied.

**Comment by WeatherGod** [comment]
scatter has never used the color cycle. Do you mean "the new color scheme"?

**Comment by tacaswell** [comment]
There is probably a hard-coded-to-blue someplace in `scatter`.  Even if it does not respect the color cycle, it should at least use it's first color as the un-mapped color.

**Comment by mdboom** [comment]
I think the best fix here is to implement the "numbered color syntax" as proposed in #5674 and then change the hardcoded 'b' in scatter to '[0]'.
