### ISSUE TITLE
Points annotation coords not working in 2.x

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5994]
See the [annotation demo](http://matplotlib.org/devdocs/examples/pylab_examples/annotation_demo.html):
![annotation_demo](http://matplotlib.org/devdocs/_images/annotation_demo_00.png)

Both "points" and "bottom right (points)" are in the wrong location.

**Comment by QuLogic** [comment]
Oh, I knew I recognized this one from somewhere; it's caused by 7b712579fbb6f9300bee18228ba4b567ab4f9045 in 1.5.0. IIRC, this change is in fact desired, so probably the demo needs updating?

**Comment by tacaswell** [comment]
Yeah, I we should update the example

**Comment by dopplershift** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/221526/15332402/ac536948-1c22-11e6-9c69-bc9734b40c18.png)
So points is fixed, but for me the color is different and local max is directly vertical above the point (though if I try to move it further, that works). Not sure what to do about the "bottom right (points)" case.

**Comment by dopplershift** [comment]
Oh, maybe blue color is only with new style?

**Comment by tacaswell** [comment]
For reference, this is what it looks like:


---
## 1.3.1

![image](https://cloud.githubusercontent.com/assets/199813/15450378/faf864fc-1f67-11e6-8acc-e32395bd0928.png)

---
## 1.5.1

![image](https://cloud.githubusercontent.com/assets/199813/15450397/63f719ee-1f68-11e6-8877-d47943139040.png)


---
## 1.5.x

### as built in docs

![image](https://cloud.githubusercontent.com/assets/199813/15450482/812d19da-1f6a-11e6-9fd8-6941b58ac229.png)

### as run in a terminal

![so](https://cloud.githubusercontent.com/assets/199813/15450390/3f8f1732-1f68-11e6-87af-55d53700a9c1.png)

What corner of the 'local max' string the arrow hits is dpi/figure size dependent (it seems to be trying to do something smart and snaps to the closest corner.

---

## master
![image](https://cloud.githubusercontent.com/assets/199813/15450386/2015949e-1f68-11e6-9288-67313b5924f6.png)


----

I am in the process of cleaning up this example (with slightly better text as well).

**Comment by tacaswell** [comment]
![image](https://cloud.githubusercontent.com/assets/199813/15450668/d2fd1f26-1f6f-11e6-9768-186f23a4d425.png)

in PR #6455
