### ISSUE TITLE
2.x: Figure.add_axes(..., facecolor='color') does not set axis background colour

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5996]
The [polar legend demo](http://matplotlib.org/devdocs/examples/pylab_examples/polar_legend.html) sets the face colour using the `facecolor=` keyword argument, but the background is still white.
![polar legend demo](http://matplotlib.org/devdocs/_images/polar_legend.png)
It still works correctly if you pass the `axisbg=` keyword argument, but then that raises a deprecation warning.

**Comment by tacaswell** [comment]
Good catch!

**Comment by QuLogic** [comment]
This is working correctly now.
