### ISSUE TITLE
\math??{} font styles are ignored in 2.x

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5998]
The [STIX Fonts Demo](http://matplotlib.org/devdocs/examples/pylab_examples/stix_fonts_demo.html) shows three Blackboard entries with the same font. In [the 1.5.x line](http://matplotlib.org/examples/pylab_examples/stix_fonts_demo.html), these entries are italic, regular and bold. Additionally, the last three characters in the top row of circled numbers should be bold as well.

A bisect points to 4a2a18689794b6f0c6d35c55e4691e36bc47d5f8 as the first bad commit, the merging of #5214, so ping @zblz.

**Comment by zblz** [comment]
Yes, that should be fixed. Note it only happens with the `mathbb` style. 

On a different note, the demo is called STIX Fonts Demo, but it doesn't actually use any STIX fonts!

**Comment by zblz** [comment]
Also: Fraktur style is not bolded.

**Comment by zblz** [comment]
Note that setting `mathtext.fontset : stix` works fine in master, so it is likely a problem with the new DejaVu classes:

![math_fonts_example](https://cloud.githubusercontent.com/assets/576258/13075227/8736fc6a-d4a1-11e5-858e-ca48c235dc66.png)
