### ISSUE TITLE
add a "quick fail" to appveyor in case a new push to a PR was made

### ISSUE THREAD

**Issue by janschulz** [matplotlib/matplotlib#6004]
This helps in cases where someone pushes  new commits to a PR and the old commits were not yet built. As appveyor takes quite a lot time (only one build at a time), this can reduce the time until the last commit in a PR is actually built and also reduce the time until other (unrelated) PRs are built.

Actual code here: https://github.com/ogrisel/python-appveyor-demo/pull/37/files

**Comment by anntzer** [comment]
I think this is the current behavior now.  Feel free to reopen/request a reopen if I am mistaken.
