### ISSUE TITLE
linewidth in quotes causes error in PDF generation

### ISSUE THREAD

**Issue by awickert** [matplotlib/matplotlib#6010]
I have found that when I use a string to represent linewidth, ghostscript throws an error. This error goes away when the linewidth is a number. So:

```
linewidth='.5' # BAD
linewidth=.5 # GOOD
```

There are no problems viewing the PDF on Evince and Okular, but colleagues using Windows (and therefore likely Adobe Acrobat Reader, but not sure) have problems, and ghostscript shows the error.

I found this solution in Jouni K. Seppänen's second reply to this thread from 2013: http://matplotlib.1069221.n5.nabble.com/PDF-not-readable-by-Adobe-PDF-readers-td42580.html

**Comment by WeatherGod** [comment]
Just to clarify, PDF generation doesn't actually error out, it is the
reading of those generated PDFs by certain readers that is a problem?

**Comment by awickert** [comment]
Yes, PDF generation works just fine, and I can view the PDF 100% OK in Evince and Okular.

**Comment by tacaswell** [comment]
We should be either auto-casting or raising on linwidth input as a string.  Can you provide a minimal example of what methods are accepting a string line width currently?

**Comment by anntzer** [comment]
Must have been closed by #4306, not that I agree with it but heh...
