### ISSUE TITLE
bad behaviour on DateFormatter on y-axis --> polar vs normal plot

### ISSUE THREAD

**Issue by RolandRitt** [matplotlib/matplotlib#6026]
Hello!
I may figured out a wrong behaviour when plotting dates on the y-axis of a polar plot

My code:

```
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
#import pandas as pd
import numpy as np
import matplotlib as mpl
%matplotlib notebook

n_sample = 360
multiplier = 100
dates = np.arange(0, 0+n_sample) * multiplier
#dates = dates.astype('datetime64[ns]')
dates = dates.astype('datetime64[s]')
#dates = dates.astype('timedelta64[s]')
dates = dates.astype(object)
degrees = np.arange(0, 360)*np.pi /180

with plt.rc_context({'figure.figsize' : (10, 10)}):
    plt.figure()
    ax = plt.subplot(121, projection='polar')

    ax.yaxis_date()
    ax.set_ylim(min(dates), max(dates))
    ax.plot_date(degrees, dates,'-', xdate= False, ydate = True)

    ax2 = plt.subplot(122)
    ax2.plot_date(degrees, dates,'-', xdate= False, ydate = True)
    plt.tight_layout(pad=0.7)
```

produces

![timespolar](https://cloud.githubusercontent.com/assets/16588610/13145168/2b030fb0-d64f-11e5-8914-b821f1e2dee8.png)

In my opinion the y-axis in the polar plot should be formatted in the same way?

FYI: when adding `ax.yaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))` solves the Problem temporarly - the problem is you have to manually define the range...

Edit1:

if i change in my code `multiplier = 0.1`, the following plot is produced
![timespolar2](https://cloud.githubusercontent.com/assets/16588610/13145647/634295b4-d652-11e5-8fa6-6f227dbd9f18.png)

in this case, only the seconds should be shown, not the miliseconds...

**Comment by QuLogic** [comment]
On `master`, this produces:
![figure_1](https://user-images.githubusercontent.com/302469/29808776-6b29751e-8c67-11e7-8f00-70f89404b5fe.png)
which seems to be about correct?

**Comment by dstansby** [comment]
I think this seems fixed on master - feel free to leave a comment if it isn't and we can re-open it!
