### ISSUE TITLE
Appearance of non-math hyphen changes with math in text

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#6028]
See the following minimal example:
```
plt.rcParams['mathtext.fontset'] = 'stixsans' #change to cm for normal behavior

mv = u'MV$^{2+}$'
cor = u'Al-cor'
plt.text(0.5, 0.5, cor)
plt.text(0.5, 0.3, cor + mv)
```
In the second case the hypen is much longer than in the first. The behavior 
depends on the mathtext-setting, which is surprising. Confirmed in Python 2.7 and 3.5,
also in 2.X.

**Comment by crazyo** [comment]
The problem is that hyphen sign is intentionally converted to minus in order to avoid ambiguity, including those ones in texts. I made a fix: https://github.com/matplotlib/matplotlib/pull/6073
