### ISSUE TITLE
plt[.gca()].legend: items that are not passed as arguments are still displayed

### ISSUE THREAD

**Issue by DSLituiev** [matplotlib/matplotlib#6031]
I am following [this post](http://matplotlib.1069221.n5.nabble.com/exclude-something-from-legend-td12681.html)  and [this guide ](http://matplotlib.org/1.3.1/users/legend_guide.html) to select specific points to be included into the legend. However, items are still included based on order, not on handles provided.

```
import matplotlib.pyplot as plt
from seaborn import load_dataset

x = "total_bill"
y = "tip"
data = load_dataset("tips")
lims = (0, 60)

g = plt.scatter(data[x], data[y],  color = (0,0,1,.15))
ax = plt.gca()
ax.plot(lims, 0.15*np.array(lims), "--", color = (0,0,0,.3,), zorder = -1)

c1 = ax.plot(data[x].loc[0] ,data[y].loc[0], ".", color = 'r', label = "green")
c2 = ax.scatter(data[x].loc[1] ,data[y].loc[1], color = 'g', label = "red")

"both result in the same behaviour:"
#ax.legend([None, c1, c2], numpoints = 1)
plt.legend([None, c1, c2], numpoints = 1)
```

Output:

![image](https://cloud.githubusercontent.com/assets/8426290/13190274/1495908c-d711-11e5-802f-431217a9be32.png)

similarly

```
 plt.legend((c1, c2), ("green", "red"), numpoints = 1)
```

PS: 'best' location also seems broken.

---
- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

```
{'dirty': False,
 'error': None,
 'full-revisionid': 'c0728d23ca5adbff6b79cda3153d0d36bff12c55',
 'version': '1.5.1+1304.gc0728d2'}

Ubuntu 14

Python3.4
```
- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
  
   pip3 install git+https://github.com/matplotlib/matplotlib

**Comment by tacaswell** [comment]
If you want to pass the artists to legend you must also pass the labels to use as well.

The image you posted seems to be behaving 'correctly' (but annoyingly), however I am surprised that ` plt.legend((c1, c2), ("green", "red"), numpoints = 1)` did not work correctly.

**Comment by DSLituiev** [comment]
would not it be good if the labels that provided upon constructing "artists" could be read by the `legend`?

**Comment by QuLogic** [comment]
The documentation seems to have been fixed. If you pass a single positional argument, you are passing _labels_. If you pass two positional arguments, you are passing _handles_, then _labels_. If you only want to pass handles, use a keyword argument.
