### ISSUE TITLE
Better hot/thermal colormap

### ISSUE THREAD

**Issue by endolith** [matplotlib/matplotlib#6032]
The existing `hot` colormap copied from Matlab has bad rings of red and yellow on it, from going into the corners of the RGB cube:

![sine heatmap matlab hot](https://cloud.githubusercontent.com/assets/58611/13193256/8901d98a-d743-11e5-942e-6c97eff77a6f.png)

`afmhot` is better, but still has sharp angles in the curve:

![hot vs afmhot RGB cube](https://cloud.githubusercontent.com/assets/58611/13193472/f34f1336-d746-11e5-9032-acc2c75ba193.png)

[I've made a smoother version](https://gist.github.com/endolith/74275dc8fa2bb9a78266), but it's just a rounder version of the same concept, in RGB space, not based on perceptual color theory:

![sine heatmap smooth_hot](https://cloud.githubusercontent.com/assets/58611/13193252/7c5a2160-d743-11e5-91cf-12a81d8d8da4.png)

![smooth hot RGB cube](https://cloud.githubusercontent.com/assets/58611/13193482/0e774228-d747-11e5-8f09-5fe91eb1fa07.png)

If this is good enough for inclusion, I could make a PR for it.  If not, I could make a more perceptually-smooth one, or someone else could if I don't get to it and then close this issue.

These are the other thermal-ish colormaps for comparison:

![hottish](https://cloud.githubusercontent.com/assets/58611/13193533/1953db2e-d748-11e5-8db1-c510c44c970a.png)

![thermal colormaps rgb cube](https://cloud.githubusercontent.com/assets/58611/13193526/dd6e1188-d747-11e5-8d5e-bee7f91e15fb.png)

**Comment by QuLogic** [comment]
What about inferno, magma, plasma (these are new, but sort of thermal, I guess)?

**Comment by endolith** [comment]
True, those didn't exist when I made those plots.

**Comment by efiring** [comment]
There is scope for improved colormaps of many sorts; we have quite a motley collection.  To keep the collection from growing out of hand, however, we probably need to think a bit more about strategy, as suggested by @njsmith.  Therefore I am going to retag this as 2.1; we need to get the PR and issue count for 2.0 down to the point where we can actually release it.

**Comment by tacaswell** [comment]
magma, plasma, and inferno have no been in the library for 5+ years and we have become even more conservative about adding new color maps (instead directing people to third-party packages to provide the wider range of colormaps).

I'm going to close this as partially addressed (we ship 3 perceptually uniform "hot"-ish color maps) and not going to be addressed (very unlikely we would take a new ab-initio colormap).
