### ISSUE TITLE
return `_text` property as  __repr__  for Text class

### ISSUE THREAD

**Issue by DSLituiev** [matplotlib/matplotlib#6042]
now `print(text)`  returns  something like:

```
 <matplotlib.text.Text at 0x7f7d0cfdf0f0>
```

suggestion: return the `_text` property in `__repr__()`

---
- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

```
{'dirty': False,
 'error': None,
 'full-revisionid': 'c0728d23ca5adbff6b79cda3153d0d36bff12c55',
 'version': '1.5.1+1304.gc0728d2'}

Python3.4
Ubuntu 14
```
- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
  
   pip from git

**Comment by souravsingh** [comment]
I would like to work on the issue

**Comment by afvincent** [comment]
Closing this issue as the new behavior since #6068 is 
``` python
from matplotlib.text import Text

txt = Text(0, 0, 'Here comes the text!')
print(txt) # returns "Text(0,0,u'Here comes the text!')"
```
which somehow addresses the problem.

Feel free to reopen this issue if the original idea of doing
```python
from matplotlib.text import Text
Text.__str__ = lambda self: self._text

txt = Text(0, 0, 'Here comes the text!')
print(txt) # returns "Here comes the text!"
```
is really the wished behavior.
