### ISSUE TITLE
Advanced hillshading example looks strange with new defaults.

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#6043]
Compare:
http://matplotlib.org/devdocs/examples/specialty_plots/advanced_hillshading.html
to
http://matplotlib.org/examples/specialty_plots/advanced_hillshading.html

This is likely related to the change in blend mode

**Comment by mdboom** [comment]
I think there's actually two style changes affecting this: the change of `blend_mode` from `hsv` to `overlay`, and the change of interpolation from `bilinear` to `nearest`.

As to how to fix: does it make sense to just explicitly pass the old defaults to restore the old behavior?

**Comment by jenshnielsen** [comment]
Yes probably I will investigate it

**Comment by tacaswell** [comment]
@njsmith Can you comment on this one?  I think the change was at your request.

**Comment by njsmith** [comment]
Unfortunately I know nothing about hill shading, my only contribution was to point out that the source code had a comment saying that the default was unfortunate and should be changed when possible. I'd look to see who wrote that comment I guess :-)
