### ISSUE TITLE
Serious problems on the axes documentation

### ISSUE THREAD

**Issue by kawing-chiu** [matplotlib/matplotlib#6055]
I've found two problems in the documentation of `axes`:
1. In the docstring of `set_xlim()` and `set_ylim()`, it read: "Set the data limits for the xaxis". It should be _view_ limits instead, which is very confusing.
2. In the docstring of `autoscale_view()`, it should be mentioned that, if `set_xlim()` or `set_ylim()` has been called on the same axes before, `autoscale_view()` will not work (because `_autoscaleXon` would have been set to False by the above two functions) and `autoscale()` should be used instead.

**Comment by tacaswell** [comment]
Pull requests for documentation are always welcome!

**Comment by kawing-chiu** [comment]
OK, I'll see if I have time to make a PR in the next weekend. So is my understanding above on the `set_xlim()` and `autosacle_view()` methods correct?

**Comment by tacaswell** [comment]
2) is clearly correct.  I am not sure about the distinction between 'data limits' and 'view limits', they map to the same concept in my head.  You are making a distinction between the limits of the data passed in (`[min(x), max(x)]`) and the limits of the data shown on the graph?  If that is the case I do not see a problem with making the docstring clearer / more precise.

**Comment by kawing-chiu** [comment]
Yes, this is what I mean, and I think this distinction can also be seen in the code? Like, `ax.dataLim` and `ax.viewLim`. And `set_xlim()` changes `ax.viewLim`.

**Comment by tacaswell** [comment]
Yup, we do make that distinction in the code :sheep: .  Thanks for pointing that out!

**Comment by sameshl** [comment]
@tacaswell I would like to work on this. So, if I understand correctly I am supposed to make changes in docstrings set_xlim() and set_ylim() such that  `Set the data limits for the xaxis` --> `View the data limits for the xaxis`

Is that it?

**Comment by ImportanceOfBeingErnest** [comment]
Note quite. 

For 1.: There is a distinction between data limits and view limits. The data limits are the bounding box of all the data in the axes, but usually the axes leave some margin around the data, so `set_{x,y}lim()` set the view limits of the axes. Probably this is just about 

> "Set the view limits for the xaxis."

For 2. This is about the fact that `ax.autoscale_view()` does not change the view limits if they have been set via `set_{x,y}lim()`. So the request here is to let the documentation state something like

> "The the view limits of the axes are fixed, e.g. via `set_xlim`, they will not be changed by autoscale_view(). See `autoscale()` for an alternative.

or similar.

**Comment by sameshl** [comment]
Regarding:
1. This has already been implemented in that latest matplotlib release as the changes can be seen at  [set_xlim](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_xlim.html?highlight=set_xlim#matplotlib.axes.Axes.set_xlim) and [set_ylim](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_ylim.html?highlight=set_ylim#matplotlib.axes.Axes.set_ylim)
