### ISSUE TITLE
Axes.relim() seems not to work when copying Line2D objects

### ISSUE THREAD

**Issue by AKuederle** [matplotlib/matplotlib#6063]
In the following example I tried to "copy" one Line2D object from one Axes to the another. This seems to work, however the DataLimit doesn't get updated correctly.
As seen based on the printouts, the DataLimit is the same for and after calling relim().
Am I not using the the function correctly or is this a bug?

Thank you for your help!

```python
import matplotlib.pyplot as plt
import numpy as np

fig1 = plt.figure()
ax1 = fig1.add_subplot(111)
lines = ax1.plot(np.arange(0,10))

fig2 = plt.figure()
ax2 = fig2.add_subplot(111)
ax2.add_line(lines[0])
print(ax2.dataLim.bounds)
ax2.relim()
print(ax2.dataLim.bounds)
ax2.autoscale_view(True,True,True)
ax2.figure.canvas.draw()
```
Matplotlib version: 1.4.3

**Comment by efiring** [comment]
As far as I know, copying an artist from one axes or figure to another has never been supported.  I think this question has come up before, so we need to either support the operation, or make it generate an exception.

**Comment by WeatherGod** [comment]
yeah, in general you can't copy artists around because that would violate
the tree hierarchy assumption (the figure that the second axes is attached
to may or may not be the same figure that the first axes object is attached
to). I don't think you can deepcopy it either (but I could be wrong). You
might be able to get away with pickling the artist and then unpickling it
again, but at that point, why not just remake the artist?

We really should raise an exception.

**Comment by AKuederle** [comment]
I had the idea to write a function, which can quickly overlay all Lines drawn in multiple figures to compare them (data analysis). This way (so the theory) it should be easier to view and compare a bunch of plots, independent of how they original generated.

By the way, i tried to trace the problem and it seems to be a problem with the line.path of the copied Line2D object. All other properties are identical with a Line2D object created directly by ax2.plot().

But so far, thank you for your help! I will look in to other options to realise my idea.

**Comment by tacaswell** [comment]
In mpl 1.5.0 changing the axes that an `Artist` is associated with is explicitly forbidden (and will raise if you try).

I was going to suggest using the `update_from` method to copy the line properties, ex

```python
from matplotlib import pyplot as plt
from matplotlib.lines import Line2D

fig, (ax1, ax2) = plt.subplots(2, 1)

ln, = ax1.plot(range(15), color='limegreen')
ln2 = Line2D(*ln.get_data())
ln2.update_from(ln)
ax2.add_line(ln2)
```

but this also copies the clip box so the second line is not visible unless you turn off clipping or re-set the clip box.

**Comment by AKuederle** [comment]
Thanks for the suggestion and the fast response overall!
Keep up the good work guys!
