### ISSUE TITLE
Proposal to change color -- 'indianred'

### ISSUE THREAD

**Issue by elcaceres** [matplotlib/matplotlib#6065]
Without intending to cause offense or ruin someone's workflow, 'indianred' isn't really an appropriate name to be using in 2016. Maybe it's time to change it or remove the name? [matplotlib/colors.py](https://github.com/matplotlib/matplotlib/blob/0a727247037493fd996f4ee899d7e23cc520cf23/lib/matplotlib/colors.py)

**Comment by efiring** [comment]
Really?  Is a reference to laterite soil from India, dating back to 1792, politically incorrect now?
https://en.wikipedia.org/wiki/Indian_red_%28color%29

**Comment by WeatherGod** [comment]
Also, it is in the list of W3C HTML colors, which we support. If it were to
be changed there, then we would change it here.

**Comment by elcaceres** [comment]
Ah, that's really good to know. Learn something new everyday. Thanks.

**Comment by efiring** [comment]
Thanks for the suggestion; I was not aware of the origin of the color name until I looked it up.

**Comment by mdboom** [comment]
Nice to hear it has nothing to do with the name of the Washington, DC NFL team that I refuse to name.

**Comment by tacaswell** [comment]
@elcaceres Thanks for bringing this up (even if is fortunately a false alarm).  

This reminds me that we discussed adopting a more through code of conduct on the mailing list a while ago, but have not done anything about it yet...
