### ISSUE TITLE
Taylor Diagram

### ISSUE THREAD

**Issue by jhamman** [matplotlib/matplotlib#6066]
Would there be interest in adding a Taylor Diagram (example shown below) to the matplotlib api? I have a class that I'd be happy to put into a pull request if it would be accepted.  

![taylor prc_water_3](https://cloud.githubusercontent.com/assets/2443309/13365563/9e14e780-dc8a-11e5-803d-0f6f24b631db.png)

**Comment by tacaswell** [comment]
At a minimum I think it would be a good fit for the example gallery.

I have never heard of these plots before so I do not know how widely used they are.  One thing we have been talking about doing is encouraging domain specialists to build high-level charting libraries on top of mpl (and maybe host the project under the matplotlib gh org).  The idea is basically the scikit pattern, but for plotting.

I am hesitant to judge if a PR would be merged having not seen the code :wink:

**Comment by jhamman** [comment]
Okay, I've also reached out to @mwaskom with the same question: https://github.com/mwaskom/seaborn/issues/872.

The [Taylor Diagram](http://www-pcmdi.llnl.gov/about/staff/Taylor/CV/Taylor_diagram_primer.pdf) has mostly been applied in the Earth Sciences (climate modeling, hydrology, etc.) but could find applications in other disciplines.

**Comment by ocehugo** [comment]
I also like that idea. There are several implementations out there.

See also : https://github.com/pyoceans/utilities/blob/master/utilities/taylor_diagram.py
http://uv-cdat.github.io/cdat-site/taylordiag.html


maybe deserve more love to be a proper PR ?

**Comment by pwolfram** [comment]
:+1:

**Comment by anntzer** [comment]
I'll close this for now and suggest that this be made into its own third-party package (or example), similarly to the decision for ternary plots (https://github.com/matplotlib/matplotlib/pull/6737).  Once that third-party package exists, we can link it in the docs.

**Comment by A-Infor** [comment]
> I'll close this for now and suggest that this be made into its own third-party package (or example), similarly to the decision for ternary plots (#6737). Once that third-party package exists, we can link it in the docs.

So, where is the link in the docs for the third-party package?

**Comment by jklymak** [comment]
We have a third party package page.  https://matplotlib.org/thirdpartypackages/

I don't see this particular plot type there but if you find a package that does this please feel free to link it there.

**Comment by pwolfram** [comment]
Are you amenable to inclusion of this feature, minimally in the gallery @jklymak,  @anntzer, @jhamman, @tacaswell, et al ?  Arguably if we had ternary plots (https://github.com/matplotlib/matplotlib/pull/6737) they could also be included minimally in the gallery too.  

Each of these approaches is fairly basic but extremely helpful for model-observation comparisons as well as general data science, very much along the lines of the existing power spectral density (https://matplotlib.org/stable/gallery/lines_bars_and_markers/psd_demo.html#sphx-glr-gallery-lines-bars-and-markers-psd-demo-py) and multitude of different statistics plots (https://matplotlib.org/stable/gallery/statistics/time_series_histogram.html#sphx-glr-gallery-statistics-time-series-histogram-py).

**Comment by timhoffm** [comment]
This is too domain-specific to be added as a function to core matplotlib. If there is not third-party library that does this already, adding it to the gallery is reasonable. When doing so, I suggest to write it in the form of a reusable function, similar to https://matplotlib.org/stable/gallery/lines_bars_and_markers/horizontal_barchart_distribution.html, so that users can easily copy&paste. @pwolfram would you be interested in adding such an example?

**Comment by pwolfram** [comment]
@timhoffm , this third-party library is a recent enough example: https://github.com/PeterRochford/SkillMetrics/wiki/Taylor-Diagram-Examples and is based on matplotlib (https://github.com/PeterRochford/SkillMetrics/blob/master/requirements.txt); I concur, addition of a Taylor Diagram example isn't needed but if others disagree or this library ceases to be supported I can add an example.  The package provides additional value-added beyond just the diagram so use of this package is probably best as this package did not exist when this thread was opened in 2016.
