### ISSUE TITLE
pyplot.savefig doesn't expand ~ (tilde) in path

### ISSUE THREAD

**Issue by tobanw** [matplotlib/matplotlib#6067]
`pyplot.savefig` throws an error when given a path with a `~` for the user's home directory. Writing out the full path works as expected.

```python
import matplotlib.pyplot as plt
output = '~/plot.png'
plt.plot(range(10))
plt.savefig(output)

FileNotFoundError: [Errno 2] No such file or directory: '~/plot.png'
```

Matplotlib 1.5.0, Python 3.4.3 (Anaconda 2.4.1), Linux

**Comment by efiring** [comment]
It looks like that could be fixed by wrapping the file name in `os.path.expanduser`.  Would you like to submit a PR?

**Comment by efiring** [comment]
`savefig` starts quite a chain of function calls, so one question will be where to put the `expander` call.  I'm inclined to think it belongs in `Figure.savefig()`.

**Comment by WeatherGod** [comment]
I am inclined to say it doesn't belong in matplotlib at all. Expansion of
the tilde is a shell-ism.

**Comment by efiring** [comment]
@weathergod, all it costs us is a single call to the standard library.  We are already doing it in handling matplotlibrc entries.  It's a convenience to the user.

**Comment by WeatherGod** [comment]
I wouldn't block it. But we should make sure we are consistent. So, that
means imsave(), and imread(), and any other reading and saving function
that we have scattered about.  I would also be concerned about creating an
inconsistency within the SciPy ecosystem. Are there other libraries that
implement this convenience?

**Comment by mdboom** [comment]
I agree with @WeatherGod on this: I think the onus is on the user to call `expanduser`.  I think it's a confusing path to go down to diverge from the behavior of most other libraries I'm aware of in the Python ecosystem.  (numpy.savetxt doesn't do this either, for example).  I think the reason we handle it in `matplotlibrc` is because there's no real alternative there.

**Comment by efiring** [comment]
OK, I will withdraw my support for this proposal.

**Comment by tobanw** [comment]
Fair enough, I'll close this issue.

**Comment by tacaswell** [comment]
@tobanw Thanks for your input.  Saying no to user requests is hard, but sometimes it needed to keep the library maintainable :disappointed: .

**Comment by tobanw** [comment]
No worries, that's totally understandable. And now when people google this problem, they'll find this issue.
