### ISSUE TITLE
imshow no longer correctly handles 'bad' (`nan`) values

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6069]
To help us understand and resolve your issue please check that you have provided
the information below.

- [ v2.x ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
- [ source ] How did you install Matplotlib and Python (pip, anaconda, from source ...)

- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
```python
plt.imshow(np.ones((5, 5)) * np.nan)
```
-  If this is an image generation bug attach a screenshot demonstrating the issue.
![so](https://cloud.githubusercontent.com/assets/199813/13376811/a2088d70-dd92-11e5-83cd-77d70751c3a4.png)

Also got some user warnings

```pytb
 /home/tcaswell/.virtualenvs/dd_35/lib/python3.5/site-packages/numpy/ma/core.py:4089: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")
/home/tcaswell/source/p/matplotlib/lib/matplotlib/colors.py:581: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
/home/tcaswell/source/p/matplotlib/lib/matplotlib/cm.py:275: RuntimeWarning: invalid value encountered in less
  rgba[:, :, 3][x < 0.0] = 0

```

- [ always ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.

**Comment by tacaswell** [comment]
It looks like new image re-sampling code loses the mask that gets added on the way into `AxesImage` which then does not propagate properly through norm / color map.

**Comment by mdboom** [comment]
Lemme know if you need help with this one.

**Comment by mankoff** [comment]
I think this bug still exists w/ RGB images. An MWE based on the `test_image` in the above fix.

```
fig, (ax1, ax2) = plt.subplots(1, 2)

foo = np.ones((5,5))
foo[1:2, 1:2] = np.nan
ax1.imshow(A)

bar = np.zeros((5,5,3))
bar[:,:,0] = 1
bar[:,:,1] = 0
bar[:,:,2] = 0
bar[1:2,1:2,:] = np.nan
ax2.imshow(bar)
```

**Comment by tacaswell** [comment]
In the case of RGBA there is no color mapping.  The black coming through is a bit odd.

@mankoff What version of mpl and what backend are you using?

**Comment by mankoff** [comment]
mpl: 1.5.1
backend: Qt4Agg
OS: OS X.

I'm not sure what you mean by "no color mapping". Is it possible to have transparent values in an RGB displayed with imshow?

**Comment by tacaswell** [comment]
This original bug in this  issue with the new image code which is only on 2.x/master (not released yet).

What I mean by 'no color mapping' is that if you pass a (M, N, 3) or (M, N, 4) array to imshow it does not get run through the normalization / color mapping code path.  The [0,1] -> R3 step has a mapping, plus three special colors 'over', 'under', and 'bad'.

I am actually not sure what to expect for an RGB/RGBA input with nans in it.  Did this used to do something different?  In any case, can you make a new issue?

**Comment by efiring** [comment]
Something might have gotten lost.  We are using `safe_masked_invalid` in `set_data`, so I suspect that the mask was being handled prior to the big refactoring. What was being rendered in the masked locations, I don't know.

**Comment by efiring** [comment]
Contrary to my last comment, I don't think anything has been lost.  Looking at v1.4.1, I don't see any indication in the code or the docstring that invalid or masked data has ever been supported for RGB or RGBA arrays.  Even though they get passed through `safe_masked_invalid`, their mask is never checked or used.  Maybe the thing to do is to warn if any values are actually masked, and then use `.filled(0)` to turn them back into ordinary ndarrays.  Or raise an exception if any values are masked.  I think it should remain the responsibility of the supplier of RGB or RGBA arrays to handle bad values before passing the arrays in to `imshow`.

**Comment by benjimin** [comment]
I think it is a useful feature that regions of NaN appear like holes when visualised by `imshow`. Unfortunately (in matplotlib 2.0.0) `imshow` raises ValueError if the raster array does not contain any finite values whatsoever.

**Comment by tacaswell** [comment]
Can you try with 2.0.2 or provide a MWE in a new issue?

I have a memory of fixing something like that recently.
