### ISSUE TITLE
mpl_event

### ISSUE THREAD

**Issue by fuobug** [matplotlib/matplotlib#6078]
I recently installed the Anaconda distribution of python 2.7 on a MacBook Air running OS 10.9.5.

I've run "condo update --all"

I believe this installs:  matplotlib 1.5.1 np110py34_0

I am attempting to run sample event handling code from matplotlib found at:

http://matplotlib.org/1.5.1/examples/event_handling/keypress_demo.html

The code successfully brings up a window, puts the data on it, etc. It should toggle a label on the screen when the x key is pressed. 

However, it only toggles the label when I press the x key and then move the mouse cursor out of the window.

Any suggestions regarding how to fix this behavior would be greatly appreciated.

**Comment by Apo-** [comment]
I'm not a mac user, so I can't offer real help(I just saw this issue while searching for an issue in windows), but I think there have been issues with the focus on figure windows on Macs, so maybe you can start by looking into those.

Have you tried running the script from the ipython repl (meaning trying `%run <path/to/script.py>`)?

**Comment by tacaswell** [comment]
roughly related to #6108 but with the opposite sign.

I can not reproduce this issue with the Qt backend on linux.

**Comment by efiring** [comment]
If the problem persists with the latest matplotlib (2.2, in the process of being released), please re-open, or open a new issue.
