### ISSUE TITLE
Issues with colormap documentation and behavior

### ISSUE THREAD

**Issue by jni** [matplotlib/matplotlib#6080]
Over at scikit-image we were trying to write a function that would transform a grayscale image into a colormapped image of shape `im.shape + (4,)`, when @tacaswell [pointed out](https://github.com/scikit-image/scikit-image/pull/1965#issuecomment-190210990) that `cmap(image)` does this already, though this doesn't appear in the [MPL docs](http://matplotlib.org/api/colors_api.html#matplotlib.colors.Colormap). It turns out that this is a flaw in sphinx/numpydoc: `__call__` is ignored. The method itself _is_ in fact very well documented:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L525

So that's the first issue:
- [ ] fix sphinx/numpydoc/config/documentation so that the above functionality is exposed in the documentation.

The second issue is that we would probably want to use the normalizing version of this, `ScalarMappable.to_rgba`:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cm.py#L211

However, it's actually broken for nD cases, because a 3D image will unnecessarily cause a ValueError ([here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cm.py#L257)). So, the second (perhaps optional) issue:
- [ ] fix `ScalarMappable.to_rgba` behavior so that 3D grayscale images (numpy arrays) are supported.

Happy to submit PRs for this but I'd like for some core devs to chime in regarding how best to deal with these... (In particular, I have zero experience with sphinx configuration.)

**Comment by QuLogic** [comment]
[`__call__` is now documented](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.__call__), probably thanks to #20081.

I'm not sure what you mean about 3D images. If you know it's greyscale, just pass one channel to the colour mapping. Matplotlib can't know this is what you want.

**Comment by jklymak** [comment]
Yes, this has been discussed elsewhere as well - we don't want to guess if the image is grayscale or not.  I'll close...

**Comment by jni** [comment]
> we don't want to guess if the image is grayscale or not

Um, but you do, here:

https://github.com/matplotlib/matplotlib/blob/ae2a3b16376e93f1fcfc37aa94c0e0d7c2f51a4f/lib/matplotlib/cm.py#L322-L335

If I use `to_rgba` on a 3D grayscale image (e.g. shape (100, 100, 100)), a ValueError is raised, because you are guessing that I'm giving you a 2D RGB(A) array.

**Comment by jklymak** [comment]
That is correct. We don't accept 3-d arrays unless the third dimension has length 3 or 4, in which case we interpret as rgb(a). If we accepted other 3D arrays how would we know if a (100,100,3) array was rgb or three (100,100) greyscale arrays?

**Comment by jni** [comment]
I just think the code is in a weird place where 1D, 2D, 4D, 5D, and 27D arrays work fine, but 3D arrays are special-cased in case the user happens to have passed in a 2D RGB(A) array.

To enable full nD support, you could add a `guess_rgba=True` kwarg that would keep the existing guessing, but that users could disable.

But anyway, this issue is from a long time ago, and I can see that there's backwards compatibility concerns, so 🤷. I wouldn't be using it in the near term, it's just the special casing that bugs me, as a frequent user of 3D grayscale images. =)

**Comment by jklymak** [comment]
I see, you are correct that higher dim arrays are not explicitly forbidden in the code.  If it would be useful to folks, I don't see a reason to not skip the check if `guess_rgba=False`.  

This _is_ really just a one-liner at this point though: `rgba = cmap(norm(x), alpha=alpha)`
