### ISSUE TITLE
Cannot interactively edit axes limits using Qt5 backend

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6082]
Python 3.5.1, matplotlib 1.5.1, Qt5 backend ((Py)Qt5.5.1).
`plt.gca()` (so axes limits are 0, 1) then click on the "figure options" button.
Typing some values or backspace in the xlimits/ylimits fields has no effect.  I think this may be due to a change in behavior of QDoubleValidator between Qt4 and Qt5?

**Comment by tacaswell** [comment]
Can you also check that the limits have not been changed, but that the canvas was just not re-drawn?

**Comment by anntzer** [comment]
It is simply *not possible* to modify the contents of the fields at all.

**Comment by anntzer** [comment]
Closed by #6241.
