### ISSUE TITLE
Despined figure is cropped

### ISSUE THREAD

**Issue by Phyks** [matplotlib/matplotlib#6084]
Hi,

When removing frame from a figure (as `seaborn` use to do for instance), the figure is cropped at extrema (see below).

- Matplotlib version: 1.5.1
- How did you install Matplotlib and Python (pip, anaconda, from source ...) : pip
- SSCE:

Note that I increased the linewidth just to enhance the effect and that it could be well noticed. However, there is a similar issue with the default linewidth.
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-10, 10, 10000)
fig, ax = plt.subplots()
ax.plot(x, [np.sin(i) for i in x], linewidth=3)
ax.axis('off')
fig.show()
```
- If this is an image generation bug attach a screenshot demonstrating the issue.

![2016-03-01-103743](https://cloud.githubusercontent.com/assets/3856586/13423167/a5fafcb6-df99-11e5-8f06-7ba7216ef1f6.png)

Thanks

**Comment by WeatherGod** [comment]
Sigh... I think this is more of an issue with ipython notebooks than
anything else. By default, they do bbox_inches='tight' for their figures,
which will effectively crop to only what is visible. What makes this looks
bad, in my opinion is that the tight bbox doesn't take into account the
width of the line, so it makes the cropping very apparent. Most of the
time, line widths are 1, so we don't really notice it. Not entirely sure it
is a bug, though.

**Comment by Phyks** [comment]
@WeatherGod Just to be sure, I ran it in the above code in a Python shell, and got same result. It seems to be independant of ipython notebooks.

Screenshot:
![2016-03-01-155925](https://cloud.githubusercontent.com/assets/3856586/13430777/b0cf5d6c-dfc6-11e5-8cbd-e6a16167fd80.png)

Savefig result:
![3](https://cloud.githubusercontent.com/assets/3856586/13430794/c67b407c-dfc6-11e5-93f5-5e499821609f.png)

**Comment by jenshnielsen** [comment]
@WeatherGod The original example is in the notebook/nbagg backend. The bbox_inches='tight' issue only applies to the inline backend

**Comment by WeatherGod** [comment]
Ok, so, I think the whole despining aspect of this is a red herring. The
line isn't getting cropped by accident. It is cropped because it is at the
view limits of the axes, I believe. I am not sure there is a bug here at
all, as this is the intended behavior.

**Comment by tacaswell** [comment]
This is intended behavior, the line is clipped at the axes boundaries  If you want to disable clipping on the line use

```python
ln.set_clip_on(False)
```

**Comment by Phyks** [comment]
@tacaswell Ok, I was not sure it was intended behaviour. Disabling line clipping works though, I just have to not forget to call it :)
