### ISSUE TITLE
Large values in histograms not showing

### ISSUE THREAD

**Issue by LeoBreebaart** [matplotlib/matplotlib#609]
I posted this to matplotlib-users, and was asked to file a bug for it. So:

It would appear that Axes.hist() does not handle large input
values the way I was expecting it to.

For example:

```
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
# Plot as expected: single bar in the center:
#result = ax.hist([1.0e+14], 5)
# Plot remains completely empty:
result = ax.hist([1.0e+16], 5)
print "result:", result
plt.show()
```

My hypothesis is that the large value in x is causing the bin
interval size to become infinitesimally small, but is it
conceptually wrong of me to expect a histogram for such large
values to still work? If so, what would be a workaround? I don't
control the data I am trying to plot, and sometimes there's yes,
only a single value, and yes, it's that large...

(All this is done with matplotlib 1.1.0 on Debian stable (v6.0.x)
for Python 2.6.6. uname: Linux foo 2.6.32-5-686 # 1 SMP Mon
Oct 3 04:15:24 UTC 2011 i686 GNU/Linux).

**Comment by rlpitts** [comment]
I'd really like to reopen this because hexbin does the same thing and there's no range kwarg I can use to apply this workaround.

**Comment by efiring** [comment]
@rlpitts I suggest you post a message to matplotlib-users giving a simple example of what you want to do, and what the present problem or limitation is.

**Comment by efiring** [comment]
@rlpitts, I'm not sure I understand the problem you are referring to, but I think the "extent" kwarg of hexbin is analogous to "range" in hist.

**Comment by rlpitts** [comment]
I have a map of temperatures and a map of molecular hydrogen column densities for some nebulae. The temperatures are in the 10s of K, but the column densities are typically between 10^24 and 10^27 H2/m^2. I'm trying to make some hexbin 2D histograms of the column density vs. temperature distribution so I could try to fit a line to it and see if it has the slope I predict, but the plots just end up blank with no error message (it's worth noting that I'm using cm.cubehelix_r so bins with a single value would be white). My work-around was to put them both in log space, but people in the field aren't used to working in units of log(T) and it obscures the point I'm trying to make.
