### ISSUE TITLE
Accepting figure argument in subplot2grid

### ISSUE THREAD

**Issue by Phyks** [matplotlib/matplotlib#6105]
Hi,

Is there a reason to force the use of the current figure with `fig = gcf()` in `subplot2grid`: https://github.com/matplotlib/matplotlib/blob/2b4e69858db32a5c032d4e9d133ef22faed6294a/lib/matplotlib/pyplot.py#L1150?

I think it would be useful to be able to pass it a figure argument.

Thanks

**Comment by tacaswell** [comment]
Sounds reasonable enough to me.
