### ISSUE TITLE
Tight_layout failing on second png output with gtk backend

### ISSUE THREAD

**Issue by samtygier** [matplotlib/matplotlib#6125]
The first plot I output obeys the tight_layout() command, but the second one has large margins. Higher DPIs make it worse. No problem when outputting PDF. I tried a few backends and it seem to only be an issue with GTK.

```
#!/usr/bin/env python2
from matplotlib import pyplot
import numpy

xs = numpy.linspace(0,3.14,100)
ys = numpy.sin(xs)

for n in range(2):
    pyplot.clf()
    pyplot.plot(xs,ys)
    pyplot.tight_layout()
    #pyplot.show()
    pyplot.savefig("out_%s.png"%n, dpi=300)
```

Using matplotlib-1.4.3 on Fedora 23 Linux.

**Comment by fariza** [comment]
So far the problem is limited to `gtkagg` and is related to `pyplot.clf()` if I replace `clf()` for `figure()` it doesn't happen any more.

**Comment by tacaswell** [comment]
Does `fig.tight_layout()` work (instead of `pyplot.tight_layout()`?)  Does passing `tight_layout=True` as a kwarg into the figure constructor work?

**Comment by fariza** [comment]
problem persist `fig.tight_layout()` 

```
...
f = pyplot.figure()
for n in range(2):
    pyplot.clf()
    pyplot.plot(xs,ys)
    f.tight_layout()
    # pyplot.tight_layout()
    pyplot.savefig("out_%s.png"%n, dpi=300)
# pyplot.show()
```

Not present with kwarg
```
...
f = pyplot.figure(tight_layout=True)
for n in range(2):
    pyplot.clf()
    pyplot.plot(xs,ys)
    # f.tight_layout()
    # pyplot.tight_layout()
    pyplot.savefig("out_%s.png"%n, dpi=300)
```

**Comment by fariza** [comment]
IMHO I think the problem resides inside `matplotlib.backends.backend_gtkagg.py` because it is limited to the `agg` backend not the `cairo`

**Comment by jenshnielsen** [comment]
Confirming that this is happening with `GtkAgg` and `Gtk3Agg` it doesn't happen with `Gtk(3)Cairo` and `Gtk (GDK)` Weirdly enough these all 3 fall back to Agg since neither cairo nor gdk supports tightlayout

**Comment by tacaswell** [comment]
Punting to 2.0.1 because this is a long standing bug (not a regression).

**Comment by fariza** [comment]
More info

Problem present with:

* TkAgg
* WebAgg
* GtkAgg
* Gtk3Agg

Not present with:

* Qt4Agg
* Qt5Agg
