### ISSUE TITLE
ENH: add matplotlib equivalent of SVG stroke-alignment feature

### ISSUE THREAD

**Issue by jason-s** [matplotlib/matplotlib#6133]
It would be helpful to add the ability to draw inner and outer edges like the (proposed) SVG [stroke-alignment](https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment) feature: (see the border edges of the countries on this map)

![image](https://cloud.githubusercontent.com/assets/738893/13605478/f4f4c480-e504-11e5-8988-95d6b3a7a88d.png)
(from http://tavmjong.free.fr/blog/?p=1257)

**Comment by mdboom** [comment]
We would have to implement this in such a way that it's supported by backend formats that don't support it (PS, PDF), or don't support it yet (SVG).  So I think that means pre-shrinking/expanding the paths and then saving that out without any sort of special metadata about where to draw the stroke.

The math for shrinking/expanding the contours of a path is already in Agg [see here](http://antigrain.com/demo/conv_contour.gif) we just don't currently expose it to Python.
