### ISSUE TITLE
Feature request: configure default scatter plot marker size

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#6136]
As discussed on the issue tracker, it would be great if there was a way to configure the default size for scatterplot markers.

**Comment by rudolphyo** [comment]
Hello!
Could you please explain, what exact size you mean?
As I thought before, scatterplot markers can be configured by s parameter, which is equal to 20 by default.

**Comment by WeatherGod** [comment]
Andreas is speaking of an rcparam that would effectively be a default for
the default "s" parameter in scatter and plot. Having it be defined as "20"
in the call signature is a long-standing bug.

**Comment by tacaswell** [comment]
Tagged an 2.0 incase we also want to _change_ that value.

**Comment by amueller** [comment]
thanks :)
