### ISSUE TITLE
Matplotlib subplots and datetime x-axis functionality not working as intended? 

### ISSUE THREAD

**Issue by mburke05** [matplotlib/matplotlib#6141]
Hi guys!

I'm on Anaconda 64-bit, python 2.7, windows, and have been experiencing some wonkiness in subplotting with some datetime x-axes. 

I've written a detailed post on the issue on stack here:

http://stackoverflow.com/questions/35922918/matplotlib-subplot-datetime-x-axis-ticks-not-working-as-intended

The dataframe index that the x-axis is reading from is a series of date-time objects minute-by-minute for a week; could it be that the number of points is too great? If so why would it yield the plot for one subplot but not all the others? And why does it include the terminal point of the x axis for the previous plot. 

I wasn't able to find any help on the issue elsewhere combing through stack so it might just be an error in my interpretation of how to use the date formatter with subplots. 

Also forgive the aesthetic appearance (I imported Seaborn), the behavior is the same when I run without importing Seaborn. 

Finally, when I attempt to view the plot itself without using `%pylab inline` the figure window that opens freezes (and python crashes.) This to me suggests that maybe it's some sort of memory limitation which I think is possible given the number of x axis points in total across all 7 subplots (~10k total, ~1.4k/ea)

**Comment by mburke05** [comment]
Aha!

I have found the issue. (alongside my very poor code!, but that is more systemic in nature and something I'm working on.)

https://github.com/matplotlib/matplotlib/issues/1086/

Looks as though the set_major_locator and set_major_formattor need to be instantiated for each subplot instance because the formattor object will (to me, counter-intuitively) overwrite and move with each successive call.

Sorry and thanks for all the hard work you do guys!

**Comment by seguri** [comment]
@mburke05 hi, could you please check my recent update to #1086 ? Maybe you have a clue... Thanks
