### ISSUE TITLE
matplotlib.ticker.LinearLocator view_limits algorithm improvement?

### ISSUE THREAD

**Issue by maqifrnswa** [matplotlib/matplotlib#6142]
Inspecting the code of matplotlib.ticker.LinearLocator
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1161

you can see that the view limits are chosen such that the difference between vmin and vmax is an interger multiple of scale, which is itself a power of 10. Therefore, the range  will be nicely divisible when divided by 10 (11 tickmarks).
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1213

Therefore, the view_limits function determines the limits assuming there are 11 ticks. This assumption is implicit in two lines:
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1224
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1227

Code is repeated here:

```
exponent, remainder = divmod(math.log10(vmax - vmin), 1)
if remainder < 0.5:
    exponent -= 1
scale = 10 ** (-exponent)
vmin = math.floor(scale * vmin) / scale
vmax = math.ceil(scale * vmax) / scale
```

Since we know the number of ticks, from `self.num_ticks`, we can generalize the current algorithm to be better suited for any number of ticks. Suggested generalized algorithm:

```
exponent, remainder = divmod(math.log10(vmax - vmin), math.log10(self.num_ticks-1))
if remainder < 0.5:
    exponent -= 1
scale = (self.num_ticks-1) ** (-exponent)
vmin = math.floor(scale * vmin) / scale
vmax = math.ceil(scale * vmax) / scale
```

This generalized expression reduces to the current form when `self.num_ticks==11` (which is the current default). For other cases, here is an example:
when num_ticks = 10, vmin = 20, vmax=90
Current algorithm returns vmin = 20, vmax=90, corresponding to ticks spaced by 7.77778.

The proposed algorithm returns vmin = 18, vmax = 90, corresponding to ticks spaced by 8.

Is this something worth doing? The patch is trivial -- just changing two lines of code. I can turn this in to a pull request to illustrate if it is helpful.

**Comment by tacaswell** [comment]
A pull request would help to clairify (and will allow the tests to run).

**Comment by tacaswell** [comment]
provisionally tagging an 2.0 in case we like this change and it breaks tests, can be pushed out if needed.

**Comment by maqifrnswa** [comment]
No problem, here's a pull request:
https://github.com/matplotlib/matplotlib/pull/6146
