### ISSUE TITLE
drawstyle accepts anything as default rather than raising

### ISSUE THREAD

**Issue by madphysicist** [matplotlib/matplotlib#6143]
Setup
-----
`matplotlib.__version__` = 1.5.1
`matplotlib.__version__numpy__` = 1.6
Python 3.5.1, IPython 4.1.2  running under anaconda
OS: Red Hat 6.5

Matplotlib installed with `conda install matplotlib`.

Issue
-----
Supplying invalid `drawstyle` parameter to `plot` (and possible others) does not raise an error. I would expect the following **not** to work, but it does:

    >>> import matplotlib.pyplot as plt
    >>> plt.plot(range(5), range(5), drawstyle='mwahahahahaha')

For contrast, trying the same thing with `fillstyle` raises the expected error:

    >>> plt.plot(range(5), range(5), fillstyle='mwahahahahaha')
    ...
    ValueError: Unrecognized fillstyle full left right bottom top none

Notes
-----
The issue seems to be happening here: https://github.com/matplotlib/matplotlib/blob/3ba9279fd9810b088d876988b8b7cf419e470716/lib/matplotlib/lines.py#L988. I would submit a PR, but I am pretty sure that adding something like

    drawstyles = ('default', 'steps', 'steps-pre', 'steps-mid', 'steps-post')
    if drawstyle not in drawstyles:
        raise ValueError(' '.join(('Unrecognized drawstyle',) + drawstyles))

would mess up something or another. If not, I would be glad to make the change.

To help us understand and resolve your issue please check that you have provided
the information below.

**Comment by tacaswell** [comment]
That seems like a reasonable course of action.  In the (near) future the plan is to use traitlets everywhere which will help with this sort of thing, but documenting what needs to be validated by code that validates them in probably a good thing.

**Comment by tacaswell** [comment]
Most importantly, if you add tests it will make sure the traitlets do not cause any regressions.

**Comment by madphysicist** [comment]
I just wasn't sure if there was additional parsing being done as for [`set_linestyle`](http://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D.set_linestyle), which accepts both a linestyle and a drawstyle in the same string.
