### ISSUE TITLE
colormaps issue

### ISSUE THREAD

**Issue by MBalazs90** [matplotlib/matplotlib#6147]
```
C:\Users\M\Anaconda\lib\site-packages\matplotlib\cm.pyc in get_cmap(name, lut)
    161         raise ValueError(
    162             "Colormap %s is not recognized. Possible values are: %s"
--> 163             % (name, ', '.join(cmap_d.keys())))
```

`'viridis' in plt.cm.datad`
return FALSE

```
s1 = set(plt.colormaps())
s2 = set(plt.cm.datad.keys())
sorted(s1 - s2)
```

the result is:
`[]`

I got the same problem with 'inferno' too

**Comment by tacaswell** [comment]
What version of mpl are you using?  The new color maps first shipped with 1.5.

**Comment by MBalazs90** [comment]
ok, I updated it, it fixed the issue.

**Comment by tacaswell** [comment]
Closing as the issue was using a too-old version of mpl for the desired feature.
