### ISSUE TITLE
travis dedup

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6149]
Use web-hook to cancel travis jobs when more than on travis job is running for the same PR (because someone pushed a second (or third or forth ...) commit before the first one finished.  

https://github.com/grosser/travis_dedup

Pandas is testing this

https://github.com/pydata/pandas/issues/12438

**Comment by souravsingh** [comment]
I would like to work on this issue.

**Comment by souravsingh** [comment]
@tacaswell Do we want to run the dedup on multiple branches or only on master?

**Comment by tacaswell** [comment]
On all PRs would be ideal I think.

**Comment by samsontmr** [comment]
@tacaswell
From the main page of the repo
> DEPRECATED Travis will ship this as a feature in Q12017, currently in beta if you ask them.

**Comment by tacaswell** [comment]
Closing as this is apparently going to be officially supported.
