### ISSUE TITLE
Empty axes property sequence produces empty plots

### ISSUE THREAD

**Issue by astromancer** [matplotlib/matplotlib#6150]
Hi there matplotlib dev wizzards!

I've been playing around with a few of the new features and came across what I think is a bug.  The title basically describes the issue.  Here's a code segment:

```
# Platform:
# $ uname -rvos:  Linux 3.13.0-82-generic #126-Ubuntu SMP Tue Mar 8 22:44:00 UTC 2016 GNU/Linux
import matplotlib
matplotlib.__version__    #1.5.1+1427.g7f21cc5

import matplotlib.pyplot as plt
from cycler import cycler
import numpy as np

fig, ax = plt.subplots()
colours = []
ccyc = cycler('color', colours)
ax.set_prop_cycle(ccyc)

N = 250
x = np.linspace(0, 100, N)
y = np.random.randn(N)
ax.plot(x,  y)  #produces an empty list
```

So basically one ends up with an non-existant plot, even though no warnings or Exceptions where issued upon setting an empty property sequence.  IMHO this is somewhat confusing behaviour, and can produce confusing errors downstream.  I would suggest at least a warning when trying to set empty property sequence, or raising an Exception if this behaviour is not needed for any other part of the code to work correctly.

**Comment by tacaswell** [comment]
attn @WeatherGod Maybe this should be fixed in cycler?

**Comment by WeatherGod** [comment]
What I am surprised about is that a cycle() object of an empty sequence works. I think it would be difficult to correctly detect an incorrect situation in cycler, especially as we expand its functionality. We should probably see how to detect an empty cycler(), though in matplotlib. Maybe implement `__nonzero__()` in cycler?

**Comment by tacaswell** [comment]
Looks like that got removed in favor of `__bool__` in py3 http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#nonzero

I thought about forbidding empty cyclers, but that seems like a bad idea. I can image use cases where you are building up cyclers programatically and having 0 length cyclers is helpful.

For reference:

```python
In [6]: from itertools import cycle

In [7]: tt = cycle([])

In [8]: next(tt)
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-8-a94d886fdf9c> in <module>()
----> 1 next(tt)

StopIteration: 

In [9]: 
```

@apodemus What version of cycler and python are you using?  I get the following

```pytb
15:15 $ python scratch.py 
Traceback (most recent call last):
  File "scratch.py", line 9, in <module>
    ax.set_prop_cycle(ccyc)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/axes/_base.py", line 1112, in set_prop_cycle
    prop_cycle = cycler(*args, **kwargs)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/rcsetup.py", line 715, in cycler
    return Cycler(c)
  File "/home/tcaswell/.virtualenvs/dd35/lib/python3.5/site-packages/cycler.py", line 118, in __init__
    self._left = Cycler(left._left, left._right, left._op)
  File "/home/tcaswell/.virtualenvs/dd35/lib/python3.5/site-packages/cycler.py", line 135, in __init__
    self._keys = _process_keys(self._left, self._right)
  File "/home/tcaswell/.virtualenvs/dd35/lib/python3.5/site-packages/cycler.py", line 68, in _process_keys
    l_peek = next(iter(left)) if left is not None else {}
StopIteration

```

**Comment by apodemus** [comment]
I was using cycler 0.9.0!  Update to 0.10.0 now gives me the same StopIteration as above.

**Comment by tacaswell** [comment]
Where it is showing up is still a bit concerning, but at least it raises now.
