### ISSUE TITLE
Matplotlib 1.5.1 ignores annotation_clip parameter

### ISSUE THREAD

**Issue by mikoff** [matplotlib/matplotlib#6151]
Hello!
I think there is a problem with matplotlib annotation_clip value while using it to place a comment outside the main plot area. Surprisingly, but it works in jupyter notebook.

Matplotlib version: 1.5.1
Platform: Linux
Backend: Qt, TkAgg
Installed using: pip
To help us understand and resolve your issue please check that you have provided
the information below.

Minimal working example:
```
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
x = np.arange(0,1,0.001)
y = 0.5*np.sin(x) + np.cos(x)**2
ax.plot(x,y)

ax.annotate('Test annotation', xy=(1.5, 1.5), xycoords='data', annotation_clip=False)
plt.show()

```

**Comment by tacaswell** [comment]
by 'in a jupyter notebook' you mean with the `inline` backend?  The inline backend saves with `bounding_box_inches=='tight'` which was meant to 'shrink' the bounding box to exclude extra whitespace (at the cost of losing strict control of the figure size) but also will expand the saved area to include artists not strictly in the visible section of the figure.

Adding

```python
ax.set_xlim([0, 1.4])
ax.set_ylim([0, 1.4])
```
you will see the start of your text.


I suspect you should be using

```python
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
x = np.arange(0, 1, 0.001)
y = (0.5 * np.sin(x)) + (np.cos(x) ** 2)
ax.plot(x, y)
ax.annotate('Test annotation', xy=(1, 1),
            xycoords='axes fraction',
            xytext=(0, 12),
            textcoords='offset points',
            ha='right',
            annotation_clip=False)
plt.show()

```

instead.

![so](https://cloud.githubusercontent.com/assets/199813/13730408/e43ddf90-e924-11e5-9ed0-9ec8a27eaeae.png)

**Comment by mikoff** [comment]
Thank you!
I suppose that I misunderstood the documentation. I thought that the figure will be expanded automatically with `annotation_clip` parameter set to `False`.

**Comment by tacaswell** [comment]
If the documentation confused you, can you suggest a way to clarify it?

Not auto 'shrink wrapping' is frequently a feature, for example when making animations (where every frame must be exactly the same pixel count) or for embedding in other documents where matching font size is important.

**Comment by mikoff** [comment]
I was guided by this documentation [section].(http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.text)

To my sense, something like:

> Note: the figure won`t be extended to draw the text if its position exceeds figure dimensions.

after:

>The annotation_clip attribute controls the visibility of the annotation when it goes outside the axes area. If True, the annotation will only be drawn when the xy is inside the axes. If False, the annotation will always be drawn regardless of its position. The default is None, which behave as True only if xycoords is “data”.

will be more than enough.

I played a bit and understood the mechanics behind this option - it draws the text, but the text is only shown when its position is within current figure dimensions.

**Comment by WeatherGod** [comment]
I think that statement (modulo an addendum about bbox_inches='tight') would
be fair enough. The focus of the original statement was to provide a means
for placing annotations outside an axes area, but it was probably assumed
that it would still be inside the figure.

Would you like to put together a PR updating that documentation?
