### ISSUE TITLE
Tight layout, animation and usetex results in oscillating labels

### ISSUE THREAD

**Issue by Phyks** [matplotlib/matplotlib#6186]
Hi,

When using `tight_layout` in a Matplotlib animation, if we also set the `rcParams` to use TeX rendering for labels, the axes labels are oscillating (see example code below). Using default text rendering, there is no such issue.
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
  1.5.1 on Linux, Python 3.5
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
  Pip
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
    that demonstrates the issue i.e a small piece of code which reproduces the issue
    and can be run with out any other (or as few as possible) external dependencies.

(verified in a Jupyter notebook with `nbagg` backend)

``` python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import animation
with plt.rc_context(rc={"text.usetex": True}):
    fig, ax = plt.subplots()
    ax.set_xlim((-2, 2))
    ax.set_ylim((-2, 2))
    line, = ax.plot([], [])
    def animate(i):
        x = np.linspace(0, 2, 1000)
        y = np.sin(2 * np.pi * (x - 0.01 * i))
        line.set_data(x, y)
        return line,
    a = animation.FuncAnimation(fig, animate, blit=True, frames=200, interval=20)
    fig.tight_layout()
    fig.show()
```
- [x] If this is an image generation bug attach a screenshot demonstrating the issue.
  Here are the plots at two different time steps in the animation (look at upper part of Y axis).

![1](https://cloud.githubusercontent.com/assets/3856586/13897769/6ba2e74a-edbd-11e5-8eaa-26a225edd9cc.png)
![2](https://cloud.githubusercontent.com/assets/3856586/13897770/6ba562cc-edbd-11e5-905a-def9c67a42e1.png)
- [x] If this is a regression (Used to work in an earlier version of Matplotlib), please 
    note where it used to work.

Thanks

**Comment by tacaswell** [comment]
I can not reproduce this with QtAgg.

As a side note, nbagg does not support blitting so that input is ignored.

**Comment by Phyks** [comment]
@tacaswell Indeed, I cannot reproduce either with `tk` backend. It is then definitely coming from `nbagg` backend.

Where is the right place to report about it then?

**Comment by tacaswell** [comment]
here :disappointed:

**Comment by tacaswell** [comment]
I can reproduce this, seems to only happen if you use `tight_layout` and only on the positive labels....

**Comment by Phyks** [comment]
Ok. I was not sure if it was a jupyter side issue or matplotlib one. :/

Indeed, I can confirm these observations about `tight_layout` and positive labels. Still, I do not know enough of `nbagg` backend to figure out what is going on. =(

**Comment by tacaswell** [comment]
This is a mpl, not jupyter.

My guess on this if that it is related to the flip flop canvases that nbagg
uses to compute diffs.

**Comment by Phyks** [comment]
Do you have any news on this? Can I do anything particular to help debugging it?

**Comment by tacaswell** [comment]
I have not had time to look into this.  I am 60% sure that the issue arises from the logic at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_webagg_core.py#L243 where only one of the renderers gets told about the tight_layout which in turn does not know to invalidate the tex caches (or something in that general vicinity of problems).

if you do

```python
fig = plt.figure(tight_layout=True)
```
does the problem go away?

**Comment by Phyks** [comment]
Indeed, using `fig = plt.figure(tight_layout=True)` fixes the issue (but I did not (yet) find how to also fix the `pad` value with this method).

As long as I introduce a `fig.tight_layout()` call (with or without extra keywords argument), it breaks.

I will try to have a look at it and see if I can find a fix, f by chance I manage to find it before you do :). Let me know if you have any more ideas :)

Thanks!

**Comment by ksunden** [comment]
I cannot reproduce on current matplotlib, so going to close
