### ISSUE TITLE
Qt properties editor discards color alpha

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6196]
`plot([0, 1], [0, 1], color=(0, 0, 0, .5))` (a gray line) then click on the qt editor.  Upon clicking on OK, the line becomes black, likely because the alpha value has been discarded.
Tested on 1.5.1 and master.

**Comment by TuanNguyen27** [comment]
I would like to work on this issue, how do i start ?

**Comment by tacaswell** [comment]
@TuanNguyen27 You just did :wink:

**Comment by TuanNguyen27** [comment]
@tacaswell thanks for the reply! my apologies for the vague question, I'm new, as you can tell, so I'm wondering where should I look in the code base to get started?

**Comment by tacaswell** [comment]
The color handling in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_editor/figureoptions.py

I may be reconsidering tagging this as easy, there maybe a non-trivial amount of Qt work involved.

**Comment by anntzer** [comment]
Actually, the Qt side of things is relatively easy, because QColorDialog (Qt 4.8 and 5.6) provide the ShowAlphaChannel option (http://doc.qt.io/qt-5.6/qcolordialog.html#ColorDialogOption-enum).  The more tricky part is that functions in `matplotlib.colors` in charge of the `#rrggbb` to color conversion (in both directions: `rgb2hex`, `ColorConverter.to_rgba`, `is_color_like`) do not handle the `#rrggbbaa` format, so quite a bit of work would be needed on that side.

**Comment by WeatherGod** [comment]
IIRC, there is actually an open feature request to support #rrggbbaa
format. So, getting that to work would actually close two issues at once.
