### ISSUE TITLE
Path.contains_points "radius" parameter behavior depends on path handedness

### ISSUE THREAD

**Issue by lschr** [matplotlib/matplotlib#6199]
Depending on whether a path is specified in clockwise or  counterclockwise direction, the `radius` parameter of `Path.contains_points` either enlarges the "valid" area or reduces it.

Example:

``` python
from matplotlib.path import Path
import numpy as np

img_shape = (100, 100)
idx = np.indices(img_shape).reshape((2, -1))
vertices = [[10, 50], [50, 90], [90, 50], [50, 10]]
path1 = Path(vertices)
path2 = Path(vertices[::-1])

img1 = path1.contains_points(idx.T, radius=10).reshape(img_shape)
img2 = path2.contains_points(idx.T, radius=10).reshape(img_shape)
```

`img1` is actually made smaller, despite the positive `radius`,
![img1](https://cloud.githubusercontent.com/assets/13418822/13936187/3c9f5342-efbc-11e5-8b85-12ebaaa69067.png)
while `img2` is enlarged, as expected.
![img2](https://cloud.githubusercontent.com/assets/13418822/13936207/6069a296-efbc-11e5-89fc-f18ef57759bd.png)

I am using matplotlib version 1.5.1 installed through anaconda on Linux.

**Comment by lschr** [comment]
This gets even more interesting with self-intersecting paths. For
```python
intersecting = [[10, 10], [90, 90], [90, 10], [10, 90]]
```
one gets 
![intersecting](https://cloud.githubusercontent.com/assets/13418822/13936963/c1b5802e-efc1-11e5-8a15-7499c0e8b51d.png)

**Comment by mdboom** [comment]
Yes -- the algorithm is based on the same winding rules Agg uses when it fills a shape.  I suspect this is probably going to be a great deal of effort to fix, but we can start by at least documenting the behavior.
