### ISSUE TITLE
examples svg_histogram.html failes with UnicodeEncodeError

### ISSUE THREAD

**Issue by altsheets** [matplotlib/matplotlib#6201]
[Your example](http://matplotlib.org/examples/user_interfaces/svg_histogram.html) fails with a UnicodeEncodeError

    python svg_histogram.py

results in:

    Traceback (most recent call last):
      File "svg_histogram.py", line 83, in <module>
        tree, xmlid = ET.XMLID(f.getvalue())
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1316, in XMLID
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
        self._parser.Parse(data, 0)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 6447: ordinal not in range(128)
    
Thanks!

- Matplotlib version '1.5.1', Python version 2.7.9 on both platforms Windows, & Linux
- pip install matplotlib

**Comment by simongibbons** [comment]
Wierd looks like something to do with `StringIO`. The code example works fine if I replace the `StringIO` instance with a `cStringIO.StringIO` one.

**Comment by tacaswell** [comment]
Can you reproduce this with python3 (I can not).

**Comment by simongibbons** [comment]
Not with python 3.3.2 , only with python 2.7.8

**Comment by mdboom** [comment]
I think it should be `six.StringIO` in order to have something that works under py2 and py3.

**Comment by altsheets** [comment]
Thanks a lot. I love such vibrant activity. Much appreciated.

**Comment by QuLogic** [comment]
IIRC, `plt.savefig` should accept both text and bytes file-like objects, and `lxml` prefers `bytes`, so couldn't you just use `io.BytesIO` and thus avoid `six`?

**Comment by mdboom** [comment]
I think ideally `plt.savefig` should only ever take a `BytesIO` (or an old-fashioned `cStringIO.StringIO` on Python 2 as well) since there's actually a bug if you pass in an `io.StringIO` (unicode-writing IO) with anything but utf-8, since it will write in the xml declaration that it's utf-8 even if it's not.  But doing so would break backward compatibility.  Such a change would also be more consistent with writing PNGs, for example, which already requires `BytesIO`.

**Comment by QuLogic** [comment]
Sorry, when I said "should", I meant "should already do so", not "should do so in the future".

**Comment by altsheets** [comment]
Thanks a lot. Great. But would not close until fixed on webpage.

I have now replaced

    ...
    from io import StringIO
    ...
    f = StringIO()

with

    ...
    from io import BytesIO
    ...
    f = BytesIO()


and -great- the script runs through. Only a warning:

    C:\Anaconda\lib\site-packages\matplotlib\__init__.py:872: UserWarning: svg.embed_char_paths is deprecated and replaced with svg.fonttype; please use the latter.
      warnings.warn(self.msg_depr % (key, alt_key))

But a warning is a warning is a warning. No problem :-)

Thanks a lot!
