### ISSUE TITLE
Border on errorbars

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [matplotlib/matplotlib#6208]
I can't seem to find a simple way to set up black borders on error-bars,

At the moment it looks like this : 

![capture](https://cloud.githubusercontent.com/assets/11192748/13985351/8ef7cebc-f0fc-11e5-909c-b21ae0519eaa.PNG)

Would it be possible to add an argument to 'errorbar' in order to set a border to the error-bars ?

Example code :

```
#!/usr/bin/env python
import numpy as np
import matplotlib.pyplot as plt

# example data
x = np.arange(0.1, 4, 0.5)
y = np.exp(-x)

# First illustrate basic pyplot interface, using defaults where possible.
plt.figure()
plt.errorbar(x, y, xerr=0.2, yerr=0.4)
```

Platform : Windows 7
Python : Python 3.4.3
Matplotlib version : 1.4.3
Install : Anaconda

**Comment by timhoffm** [comment]
By design error bars are lines and thus have no border. I consider this request rare enough so that we should not jump extra hoops.

Workaround for the user: Draw the error bars twice, the first time with a thicker line and the desired “border” color.
