### ISSUE TITLE
Qt4 backend uses Qt5 backend

### ISSUE THREAD

**Issue by MichaelClerx** [matplotlib/matplotlib#6209]
When importing the qt4 backend, parts of the qt5 backend are loaded, which means users need to install the qt5 backend to make the qt4 backend work

```python
import matplotlib.backends.backend_qt4agg as backend
```

Results in:

```python
Traceback (most recent call last):
  ...
    import matplotlib.backends.backend_qt4agg as backend
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 17, in <module>
    from .backend_qt5agg import NavigationToolbar2QTAgg
ImportError: No module named backend_qt5agg
```

Python 2.7.10
Matplotlib 1.4.3
Both installed via the package manager shipped with Fedora 22 (dnf), Linux

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1219556

**Comment by tacaswell** [comment]
This is intentional, the qt4 backend is a shimmed version of the qt5 backend (as a vast majority of the code is the same).  

This is a packaging bug on the part of Fedora/red hat.

attn @QuLogic Looks like you were active in the linked bug report?

**Comment by efiring** [comment]
Although it is a packaging error, couldn't we make things easier in the future with some refactoring?  It really is counter-intuitive to have backend_qt4 depending on backend_qt5.  It would be more clear to have both depending on backend_qtcommon or something like that.  I haven't gone back to look, though; maybe there is a reason why this was not done.

**Comment by QuLogic** [comment]
@tacaswell Yes, it was originally my faulty spec, but as I'm not officially a packager, I can't do anything about it.

**Comment by tacaswell** [comment]
The major difference between qt4 and qt5 is if the `__init__` is cooperative or not, everything else is handled by the `qt_compat` module.

There is no technical reason we could not refactor into a common, qt4 and qt5 modules, but I would not put it as a high priority.
