### ISSUE TITLE
Example embedding_in_tk.py freezes in Python3.5.1

### ISSUE THREAD

**Issue by crxguy52** [matplotlib/matplotlib#6219]
When I try and run the [example code on matplotlib's website](http://matplotlib.org/examples/user_interfaces/embedding_in_tk.html) for embedding matplotlib in tk, the GUI never appears and the kernel crashes. I'm using Python 3.5.1, matplotlib 1.5.1, and tk 8.5.18 vc14. Everything was installed using Anaconda.

I'm pretty sure this is supposed to work, as I've seen other tutorials run it using Python 3. Interestingly, when I create a Python 2.7 environment, I'm able to run the code successfully. I've tried this on several machines (all Windows 7) and I get similar results.

**Comment by tacaswell** [comment]
I can not reproduce this with a linux box. 

Do you get any error messages from the crash?

**Comment by WeatherGod** [comment]
When you say "the kernel", are you talking about the ipython kernel, or the
linux kernel? If it is the linux kernel, I doubt this would be specific to
matplotlib and wonder if it is a tk packaging issue in general?

On Thu, Mar 24, 2016 at 12:14 PM, Thomas A Caswell <notifications@github.com

**Comment by crxguy52** [comment]
> I can not reproduce this with a linux box.
> 
> Do you get any error messages from the crash?

That's what's unusual - the python 3.5 window pops up and then immediately freezes. No error messages get reported before windows pops up and says "python.exe has stopped working". I also tried running it with python 3.4, same issue. If I run it with an instance of python 2.7, the example runs fine.

> When you say "the kernel", are you talking about the ipython kernel, or the
> linux kernel? If it is the linux kernel, I doubt this would be specific to
> matplotlib and wonder if it is a tk packaging issue in general?

I'm a grad student in MechE, so forgive me if I get some of the terminology wrong. I'm talking about the instance of python.

**Comment by WeatherGod** [comment]
On Thu, Mar 24, 2016 at 12:48 PM, crxguy52 <notifications@github.com> wrote:

> python.exe has stopped working



Ah, so you are on Windows? Which version?

**Comment by crxguy52** [comment]
> Ah, so you are on Windows? Which version?

Windows 7 Professional, SP1

**Comment by efiring** [comment]
I suspect this is a problem specific to the Anaconda build and/or your particular system (e.g., are there Tk versions installed in addition to the one from Anaconda?) rather then being an MPL bug.   You could check with a message to the Anaconda mailing list to see whether anyone there can reproduce it, or whether there is someone with a similar configuration who *cannot* reproduce it.

**Comment by crxguy52** [comment]
I've done a fresh installed on a smiliar windows 7 machine and was able to reproduce the same issue, so I'm thinking its either an issue with anaconda or matplotlib. Is anyone else running a non-anaconda python interpreter on windows 7, and is able to reproduce the issue?

I've started a [topic on the anaconda mailing](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/f-UwlCovN_I) list to see if someone else can reproduce it. I'm moving forward using Python 2.7, but hopefully we can get this resolved.

**Comment by crxguy52** [comment]
Per the anaconda mailing list:

> Yes, I think this is a bug in how we build Python, Tk, and Matplotlib.  Python is not using the same Tk as Matplotlib.  We need to fix that.  It is on our list.  For now, I'd recommend that you try PyQt instead.

Thanks for the help everyone!
