### ISSUE TITLE
References to non-existing class FancyBoxPatch

### ISSUE THREAD

**Issue by ProgVal** [matplotlib/matplotlib#6224]
Files `examples/shapes_and_collections/artist_reference.py` and `lib/matplotlib/patches.py` mention a class named `FancyBoxPatch`.

However, there is no such class in matplotlib. I guess it is supposed to be `matplotlib.patches.FancyBboxPatch`.

**Comment by QuLogic** [comment]
I think you are correct.

**Comment by jenshnielsen** [comment]
Fixed by #6230
