### ISSUE TITLE
Allow figure before source listing with plot directive

### ISSUE THREAD

**Issue by jfinkels** [matplotlib/matplotlib#6225]
Matplotlib version 1.5.1, Python version 3.4.3+, Ubuntu 15.10, installed via pip in a virtualenv.

When using the `plot` directive with the `include-source` option in the Sphinx extension `matplotlib.sphinxext.plot_directive`, the source code is listed before the image. I would like to be able to display the image before the source listing.

**Comment by tacaswell** [comment]
Tagged as medium as it involves touching the sphinx extensions....

**Comment by anntzer** [comment]
That can actually already by done by setting the plot_template config value, e.g. by grabbing matplotlib.sphinxext.plot_directive.TEMPLATE, chopping off ``{{ source_code }}`` at the beginning of the template and moving it to the end.

Although it's not really a trivial solution, I'm tempted to close this as "not worth supporting all possible layouts".

**Comment by jklymak** [comment]
I agrée with @anntzer there is already a knob to do this, if a slightly messy one.
