### ISSUE TITLE
ImportError from Sphinx plot_directive from Cython

### ISSUE THREAD

**Issue by cdeil** [matplotlib/matplotlib#6233]
I see an issue with the [iminuit](https://github.com/iminuit/iminuit) Sphinx build, which could be a bug in the matplotlib `plot_directive`, or a bug in `Sphinx` or just ignorance on my part (if that's the case, apologies!)

This is matplotlib 1.5.1, Sphinx 1.3.6, and Cython 0.23.4.
I see the same error on both Python 2 and 3 on OS X.

It should be easy to reproduce the issue within a minute by running these commands:
```
git clone https://github.com/iminuit/iminuit.git
cd iminuit/
make build
cd doc/
make html
```

The error I get is [here](https://gist.github.com/cdeil/2ccd421d3c6789a295ea#file-gistfile1-txt-L508):
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "<string>", line 8, in <module>
  File "iminuit/_libiminuit.pyx", line 343, in iminuit._libiminuit.Minuit.__init__ (iminuit/_libiminuit.cpp:3146)
  File "iminuit/_libiminuit.pyx", line 1397, in iminuit._libiminuit.Minuit._auto_frontend (iminuit/_libiminuit.cpp:20103)
ImportError: No module named 'iminuit.frontends'
```

The code is here: https://github.com/iminuit/iminuit/blob/master/iminuit/_libiminuit.pyx#L1397

This doesn't seem right, because `iminuit.frontends` does exist, and I can execute
https://github.com/iminuit/iminuit/blob/master/doc/pyplots/draw_mnprofile.py
just fine directly.
The error just occurs when running `draw_mncontour` via the plot directive
```
        .. plot:: pyplots/draw_mnprofile.py
            :include-source:
```
from here: https://github.com/iminuit/iminuit/blob/master/iminuit/_libiminuit.pyx#L987

As far as I know this is not a regression, i.e. this has never worked.

**Comment by tacaswell** [comment]
Does it work if you install `imunuit`?  My guess is that something funny is going on with your python paths and sphinx just can not see the build.

**Comment by cdeil** [comment]
@tacaswell - Thanks for the quick reply!

> Does it work if you install `iminuit`?

Yes.

> My guess is that something funny is going on with your python paths and sphinx just can not see the build.

Yes, something funny might be going on with the python paths during the Sphinx build.
But it cannot be the case that Sphinx simply doesn't see the build.

Look at the traceback above ... `iminuit` is successfullly imported, the error occurs when `iminuit._libiminuit.Minuit._auto_frontend` is called.
That method contains an `iminuit.frontends` statement which fails!???

I've been staring at this for a while and don't know how to debug / fix this.
We're using absolute imports consistently within `iminuit`, I don't see what's wrong.

Could this be a bug in how the plot directive or Sphinx runs the code, interacting badly with Sphinx?

If someone familiar with matplotlib, the plot directive and Cython could have a look, that would be much appreciated. The good thing is that the issue is easy to reproduce (see commands above).

**Comment by tacaswell** [comment]
If it works when you install (rather than just build) your package I do not
understand what the problem is. Just install before building the docs.

Are you hacking the sys.path in your sphinx config?

**Comment by cdeil** [comment]
The issue was that we had this in the Sphinx ``conf.py``:
```python
sys.path.insert(0, '../')
```
This was causing the issue.

Changing to this fixed the issue:
```python
sys.path.insert(0, os.path.abspath('..'))
```
but I decided to remove the ``sys.path`` change completely and require ``iminuit`` to be installed, as you suggest.

@tacaswell - Thank you! (and apologies for spamming the matplotlib issue tracker)

**Comment by tacaswell** [comment]
Great!  Glad you got this sorted out.
