### ISSUE TITLE
Issue with building docs with Sphinx 1.4.0

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#6235]
See https://travis-ci.org/matplotlib/matplotlib/jobs/118997591
```
Warning, treated as error:
WARNING: while setting up extension ['?', 'matplotlib.sphinxext.mathmpl']: node class 'latex_math' is already registered, its visitors will be overridden
```

For the time being I have submitted a pr to limit the Sphinx version to the 1.3 series for the time being see #6234

**Comment by trbedwards** [comment]
I get this error when building the matplotlib docs in Windows. 
I have Sphinx 1.4.8

**Comment by jenshnielsen** [comment]
Which version of matplotlib? Matplotlib docs are building on linux with the latest version of Sphinx 
https://travis-ci.org/matplotlib/matplotlib/jobs/174691679

**Comment by trbedwards** [comment]
It's the latest master version

**Comment by jenshnielsen** [comment]
Thats strange as it definitely works on Travis (linux) and also works locally for me on mac. 

You can temporary disable warnings as errors in travis and get it building anyway by passing `--allowsphinxwarnings` to make.py when building but I would like to get to the root of why this is different for you.

**Comment by Kojoley** [comment]
Except the 2 warnings, the doc builds fine for me on Windows (Sphinx 1.4.6, matplotlib master).

**Comment by VenusHu** [comment]
the same again for Sphinx 1.6.6, MacOS, can you help me?

**Comment by tacaswell** [comment]
@VenusHu what versions of python and mpl?  The docs build against the installed version of matplotlib so you may be hitting an older version of matplotilb that does not include #6238
