### ISSUE TITLE
pan/zoom cursor readout is upper left; should be center of "plus" cursor on Qt

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6236]
With the Qt4agg backend on mpl 1.5.1 and master, the pan/zoom cursor is a hollow plus sign.  One would expect the location readout to be the center of the plus, but it is the upper left corner, as if the cursor were still an arrow pointing NW.
On macosx in master (including the new agg-based version) the pan/zoom cursor is a hand, so the readout location is reasonable, but this cursor does not lend itself to an accurate readout.

**Comment by tacaswell** [comment]
I can not reproduce this on linux.

Interestingly, the pan tool is a closed hand for 'pan' and a filed '+' for zoom.

**Comment by dstansby** [comment]
I can't reproduce this - the readout seems to come from the middle of the cross in both `qtagg` and `qt5agg` backends. I'm going to close, but feel free to comment/re-open if still an issue.
