### ISSUE TITLE
MacOSX agg version: doesn't redraw after keymap.grid keypress

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6237]
On master, with the new MacOSX, pressing 'g' on a raised and active figure has no effect until a redraw is forced, e.g. by resizing the window.
It also behaved badly on the old macosx--in that case, a cursor movement would trigger the redraw with  or without the grid.
I'm guessing this might be easy to fix with the new version; but if not, the milestone can be moved to 2.0.1

**Comment by tacaswell** [comment]
That seems like something is going wrong with the event loop integration, as turning the grid on should be marking the figure as stale which _should_ be triggering a redraw.  

Do `l` an `k` correctly change the scales + trigger a re-draw?

**Comment by efiring** [comment]
Nope.  Same thing--have to resize the window to trigger a re-draw.
