### ISSUE TITLE
Can't build matplotlib.ft2font in cygwin

### ISSUE THREAD

**Issue by ATeal** [matplotlib/matplotlib#6255]
Matplotlib version: 1.5.1 (that's what i'm trying to install)
Python Version: 2.7.10
Platform: Windows(cygwin)

This is the exact error I'm getting: 
```
    gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/pytho/python-2.7.10-1.i686/build=/usr/src/debug/python-2.7.10-1 -fdebug-prefix-map=/usr/src/ports/python/python-2.7.10-1.686/src/Python-2.7.10=/usr/src/debug/python-2.7.10-1 -DNDEBUG -g -fwrapv -O3 -Wall -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matpotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/lucky_000/.virtualenvs/vistafy/lib/pytho2.7/site-packages/numpy/core/include -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include -I. -I/usr/inclde/python2.7 -c src/ft2font.cpp -o build/temp.cygwin-1.7.35-i686-2.7/src/ft2font.o
    gcc: error: spawn: No such file or directory
    error: command 'gcc' failed with exit status 1

```
I have a sneaky suspicion that maybe cygwin just has one of the libfreetype-devel package files in the wrong place and this just requires a symbolic link to fix, but honestly I'm not sure which or what to look for / at. Any help would be greatly appreciated!

**Comment by tacaswell** [comment]
https://stackoverflow.com/questions/16621529/gcc-fails-with-spawn-no-such-file-or-directory suggests that this is an issue with you gcc installation or PATH. 

Closing as I do not think this is a mpl specific issue, you might also try the matplotlib-devel@python.org mailing list or the cygwin mailing lists which will get more eyeballs looking at the question.
