### ISSUE TITLE
option for default space between title and axes

### ISSUE THREAD

**Issue by dstrozzi** [matplotlib/matplotlib#6257]
I suggest that the user be able to change the default distance between the title and the axes (or whatever you call the white area with the "meat" of the plot).  The default is too small - look around the matplotlib webpages, and a lot of plots have the title overlapping the y axis labels (esp. when a 1eN like 1e5 is displayed) or when a colorbar is used.

I fully realize one can do title('foo', y=1.1).  But I don't want to type the 1.1 all the time!  I could define my own function, but then the code isn't sharable.

So, please, add a "titlepad" analogous to "labelpad."  I can't see why there should be one but not both.

Thanks!

**Comment by tacaswell** [comment]
I think this is already planned as part of #6129

attn @mdboom

**Comment by mdboom** [comment]
Yeah -- Currently, though #6129 is just a bugfix around trying to make it less likely that the text touches the axes, not a true user option.  But I think we'll have to do that in #6129 anyway...

**Comment by jenshnielsen** [comment]
Fixed by #6468 which replaces #6129

**Comment by efiring** [comment]
Closed by #6468.
