### ISSUE TITLE
Document how to set viridis as default colormap in mpl 1.x

### ISSUE THREAD

**Issue by janschulz** [matplotlib/matplotlib#6265]
I've now tried to google `how to set viridis default matplotlib` and none of the first 20 pages contain any information how to set this as the default colormap (e.g. in a notebook session). It also looks like there is no "mpl20" style available and the docs only talk about "use default and you get it in the future".

The second page in my google results contain a stackoverflow post which does not work:

```python
import colormaps as cmaps
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-52-2b4a939ab51e> in <module>()
----> 1 import colormaps as cmaps

ImportError: No module named 'colormaps'
``` 

[conda env with py3.5 and latest available mpl from today]

Please add this information now so that google at least contains something useful and not only "in the future" talk when the map is available now.

**Comment by tacaswell** [comment]
```python
mpl.rcParams['image.cmap'] = 'viridis'
```

Assuming you have a python 1.5+.  Other wise install a new(ish) version of skimage who have vendored and install viridis if needed.

**Comment by janschulz** [comment]
Thanks! IMO this inforation should be included in http://matplotlib.org/style_changes.html and https://bids.github.io/colormap/ (the two higest results for "viridis default colormap". The third is funnily a link to the R version, which includes an example how to use it.).
