### ISSUE TITLE
MemoryError In copy_from_bbox

### ISSUE THREAD

**Issue by drammock** [matplotlib/matplotlib#6269]
I'm hitting an out-of memory error when plotting some EEG data.  It's not a particularly large dataset (1 figure with 12 subplots, 32 channels x 336 time points on each subplot, each channel plotted as a line).  The reason I think it's a bug is that I start out with `fig, axs = plt.subplots(nrow, ncol)` and I hit the memory error when `nrow, ncol = (3, 4)` but the plot works fine when `nrow, ncol = (4, 3)`.  An MWE including traceback is [in this gist](https://gist.github.com/drammock/babf1ca8f91fed444cab682d2c407eb6).  I suspect the problem may lie with the mne module and not matplotlib, but the entire traceback is within the matplotlib namespace so I wanted to alert you to its existence nonetheless, in case it does turn out to be your bug. (I have also alerted the mne developers).

Versions:
- Linux: 14.04 64-bit
- Python 2.7.6 (system)
- matplotlib: 1.5.1+1643.g0423430 (installed from source, current master as of 2016 April 01)

**Comment by drammock** [comment]
I forgot to mention that my system monitor shows RAM usage that is flat at around 17% throughout the running of the MWE script... the system has 32GB of total RAM so I am dubious whether this is legitimately a lack of memory.

**Comment by tacaswell** [comment]
what is `evoked_plot` doing?

**Comment by WeatherGod** [comment]
As I noted in the linked gist, I think the OP has a bad install of
matplotlib. His traceback shows pyplot existing in site-packages, but the
backend modules existing in "~/path/to/matplotlib/".

**Comment by drammock** [comment]
...and as I replied in the linked gist, those paths were manually altered
to make the traceback easier to read.

**Comment by WeatherGod** [comment]
Ah, I never got that reply. My apologises. In the future, don't bother
editing the traceback as it can cause confusion like this.

**Comment by tacaswell** [comment]
That looks like it was an intentional re writing of the traceback to make
it more readable.

**Comment by drammock** [comment]
@tacaswell  [Here is the function](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L162-L407) called by the `evoked.plot()` method.  The calls to matplotlib are scattered around within that function, but given what I know about the particular parameters passed in my MWE, the relevant bits of code actually being run are lines [252-255](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L252-L255), [269-282](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L269-L282), [339-351](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L339-L351), [362-373](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L362-L373), or [380-388](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L380-L388).  The note on [lines 345-347](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L345-L347) is particularly suspicious-looking.  Git-blame suggests @Eric89GXL, @jaeilepp, and @agramfort as likely to be the most knowledgeable about this...  hopefully they can chime in.

**Comment by tacaswell** [comment]
Can you get this down to a minimal example (using only mpl + our dependencies)?  There is quite a bit of code there and without diving into the mne code base it is very hard to see what is even going on.

**Comment by mdboom** [comment]
Even just knowing the inputs to `copy_to_bbox` might be useful as a first pass.

**Comment by drammock** [comment]
@mdboom is this what you're asking for?

```
> /home/drmccloy/.local/lib/python2.7/site-packages/matplotlib-1.5.1+1643.g0423430-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py(447)copy_from_bbox()
-> return renderer.copy_from_bbox(bbox)
(Pdb) p bbox
TransformedBbox(Bbox([[0.625526682064, 0.113425925926], [0.618223317936, 0.285648148148]]), BboxTransformTo(TransformedBbox(Bbox([[0.0, 0.0], [8.0, 6.0]]), Affine2D(array([[ 100.,    0.,    0.],
       [   0.,  100.,    0.],
       [   0.,    0.,    1.]])))))
```

@tacaswell I'm working on a mne-free MWE, but it may take some time.

**Comment by drammock** [comment]
I've narrowed down the problem somewhat: if I disable the interactive features of `mne.Evoked.plot()` it doesn't occur.  I've commented with code and screenshot on the "sister-thread" in the mne repository: https://github.com/mne-tools/mne-python/issues/3100#issuecomment-207078674

Unfortunately I can't do much further debugging at the moment, because the data I have is missing some features that are needed to make the interactivity function properly (namely, digitization of the location of the EEG electrodes in space).  Close this issue if you like; or leave open as "needs clarification" as bait for one of the MNE developers to dig deeper.

**Comment by WeatherGod** [comment]
I wonder if this might be related to a strange bug I noticed awhile back
where putting my mouse over the plotting area for an imshow() of data
loaded from a netCDF4 file caused an ever-growing memory usage? It only
started if I put my mouse over the plot area, and only for data loaded from
netCDF4. Does Evoked use mem-mapped file formats?

**Comment by drammock** [comment]
I can't say for certain about `Evoked`, but some other `mne` classes do use mem-mapping.

**Comment by Eric89GXL** [comment]
`Evoked` does not mem-map

**Comment by QuLogic** [comment]
It's almost been 2 years, so I'm going to close this.
