### ISSUE TITLE
Ability to set default scatter marker in matplotlibrc

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#6272]
As far as I know there is currently no easy way to set the default marker when calling plt.scatter(). It would be great to be able to do this in the matplotlibrc file.

**Comment by tacaswell** [comment]
Correct, the marker is hard-coded as a default in the signature.

**Comment by mdboom** [comment]
Does this fit with 2.0 style changes?

**Comment by tacaswell** [comment]
Yes, but do not think we want to block on it.

**Comment by efiring** [comment]
closed by #6328
