### ISSUE TITLE
add copy to clipboard button to interactive output plots of `%matplotlib notebook` magic

### ISSUE THREAD

**Issue by denfromufa** [matplotlib/matplotlib#6273]

**Comment by tacaswell** [comment]
Do you know how to do this from js?

**Comment by mdboom** [comment]
At least historically this hasn't been possible for security reasons, though one could do it with Flash.  However, I'm -1000 on relying on Flash for anything.

**Comment by denfromufa** [comment]
can this be done from python/jupyter backend?

On Thu, Apr 7, 2016 at 1:12 PM, Michael Droettboom <notifications@github.com

**Comment by QuLogic** [comment]
Unfortunately, there's no real guarantee that the backend is running on the same machine as the browser.

**Comment by blink1073** [comment]
Copying to the clipboard works on all recent browsers (including IE 11), it just has to be done in response to a user event (like clicking a button): ..https://github.com/jupyter/jupyter-js-ui/blob/master/src/clipboard/index.ts
