### ISSUE TITLE
Ticklabel format not preserved after editing plot limits

### ISSUE THREAD

**Issue by peynmurray** [matplotlib/matplotlib#6276]
Version: 1.5.1, Windows 7, using QT5 backend. Not tested on linux yet. After setting the format of an axis to use use scientific notation,

`ticklabel_format(style='sci', axis='y', scilimits=(0,0))`

changing the limits of the plot using the green checkbox widget in the NavigationToolbar will remove the scientific notation formatting that was just set. This would be a huge convenience for users who use scientific notation and want to work with plots interactively. Example:

```
import matplotlib
matplotlib.use("Qt5Agg")
from numpy import *
from matplotlib.pyplot import *
from numpy.random import uniform

npts = 1000

x = uniform(-100, 100, npts)
y = 1000*sin(x)*cos(x**2)

plot(x, y)
ticklabel_format(style='sci', axis='both', scilimits=(0,0))

show()
```

**Comment by tacaswell** [comment]
It is the `set_*scale` calls which remove the formatting.

**Comment by gepcel** [comment]
I think this might be relevant.
```python
plt.plot(1, 10000, 2, 20000, 'ro')
ax = plt.gca()
ax.yaxis.set_major_formatter(mpl.ticker.ScalarFormatter(useMathText=True))
ax.ticklabel_format(scilimits=(-3, 3))  # put after 'set_major_formatter', scilimits works
plt.show()
```
works fine. But if `ticklabel_format` is put before `set_major_formatter`, it doesn't work.
```python
plot(1, 10000, 2, 20000, 'ro')
ax = gca()
ax.ticklabel_format(scilimits=(-3, 3))   #put before 'set_major_formatter', scilimits doesn't work.
ax.yaxis.set_major_formatter(mpl.ticker.ScalarFormatter(useMathText=True))
plt.show()
```
