### ISSUE TITLE
ax.twinx().plot() will reset the x_limits if only an axvspan was used on ax

### ISSUE THREAD

**Issue by Redoubts** [matplotlib/matplotlib#6284]
Create a figure and axis, and add a vspan to that axis. If you twinx it, and apply a plot to the twin, the x_limits can adjust, potentially making the vspan not visible.

Minimal code sample:

```
fig, ax = plt.subplots(figsize=(12, 10))
ax.axvspan(1,2)
fig.canvas.draw()
```

![before_bx_plot](https://cloud.githubusercontent.com/assets/2435101/14406864/568dfe82-fe69-11e5-9191-996ac933b40a.png)

```
bx = ax.twinx()
bx.plot([0,.5], [1,2])
fig.canvas.draw()
```

![after_bx_plot](https://cloud.githubusercontent.com/assets/2435101/14406902/615a0aee-fe6a-11e5-9e68-da92d355153b.png)

Note how the x-axis labels shifted away from the range (1,2). 
I expected:
![expected](https://cloud.githubusercontent.com/assets/2435101/14406903/675afd72-fe6a-11e5-8bfb-e0c25e7336e9.png)
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
  Matplotlib 1.5.1 on OS X 10.11 with Python 2.7.10
- [x] System python, `pip install -U matplotlib` (with SIP disabled)

**Comment by tacaswell** [comment]
the autoscaling is apparently not twin axis aware enough.

**Comment by patniharshit** [comment]
What is the issue here?

**Comment by ibnIrshad** [comment]
I think we've tracked down the problem. `autoscale_view` apparently ignores ALL axis limits when atleast one of the limits is infinite (in this case, the y-limits of a vspan are infinite). We have a PR which fixes this by taking into account the case when either y-limits or x-limits are infinite, but the other is finite. PR coming shortly.
