### ISSUE TITLE
Wx backend does not render correctly error bars

### ISSUE THREAD

**Issue by andnovar** [matplotlib/matplotlib#6288]
To help us understand and resolve your issue please check that you have provided
the information below.
- Matplotlib 1.5 master, Python 2.7 and Ubuntu
- Installed from source.
- Example: Error bars are bold and don't have the horizontal lines.
  ![screenshot from 2016-04-11 03 29 32](https://cloud.githubusercontent.com/assets/400600/14419967/4a5b43e8-ff97-11e5-8ba0-efe789bf4a70.png)
- It used to work in 1.4.3

**Comment by WeatherGod** [comment]
Are you on the master branch, or v1.5.x branch? One of the changes in the
upcoming v2.0 style release is to eliminate the horizontal bars in errorbar
plots. If you are working off of the master branch, that would explain the
change.

I personally don't like this particular change, and the fact that you
thought it was a bug just makes me more certain that this isn't a great
idea.

**Comment by tacaswell** [comment]
The more worrying thing is the sift in the text.

**Comment by andnovar** [comment]
The screenshot is from current master but I tested with 1.5.x as well and same result. I agree with you too don't think it is a good idea to don't have the horizontal lines. I initially though of a bug.

**Comment by tacaswell** [comment]
What does the text alignment look like in 1.4.3?

**Comment by andnovar** [comment]
Alignment in Agg
![screenshot from 2016-04-12 16 53 10](https://cloud.githubusercontent.com/assets/400600/14475266/25dc6cd4-00cf-11e6-91a9-ad4d87ae0a69.png)

Alignment in Wx
![screenshot from 2016-04-12 16 44 03](https://cloud.githubusercontent.com/assets/400600/14475210/df61fdfa-00ce-11e6-85c5-5e549af340d2.png)

**Comment by andnovar** [comment]
These are the y ticklabels being added.

ax.set_yticklabels(('Ahh', '--G1--', 'G2', 'G3', 'G4', 'G5', 'G5','G5', 'G5'), rotation=90)

I still believe the error bars are somehow broken since the color is not being shown.

**Comment by tacaswell** [comment]
re-assigned to milestone 2.1 as the bug here is that wx is misplacing the ytick labels, but that is an old bug.

**Comment by dstansby** [comment]
Could someone provide a self-contained code that reproduces the issue here?

**Comment by timhoffm** [comment]
There have been two aspects discussed above:

- Tick label positioning: I've moved the issue to #14865.
- Error bars: I've run https://matplotlib.org/gallery/lines_bars_and_markers/bar_stacked.html with wxagg and it displays as in the docs. So I don't see any problem with the error bars.

Please reopen if I've overlooked something.
