### ISSUE TITLE
matplotlib notebook magic cells with output plots - skips next cell for computation

### ISSUE THREAD

**Issue by denfromufa** [matplotlib/matplotlib#6293]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 18.2
Cython: 0.23.5
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.2
IPython: 4.1.2
sphinx: 1.4
patsy: 0.4.1
dateutil: 2.5.1
pytz: 2016.2
blosc: 1.3.0
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.4
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None

**Comment by efiring** [comment]
Please give more information about the problem you are encountering, with a complete but minimal example that reproduces it.  Is this in a jupyter notebook?

**Comment by tacaswell** [comment]
Related to https://github.com/matplotlib/matplotlib/pull/6053

Being tracked at https://github.com/jupyter/notebook/issues/949
