### ISSUE TITLE
savefig() to eps/pdf does not work

### ISSUE THREAD

**Issue by lucaventurini** [matplotlib/matplotlib#6299]
While it works for png.

The error is:
```python
   1427     @staticmethod
   1428     def pathOperations(path, transform, clip=None, simplify=None, sketch=None):
-> 1429         return [Verbatim(_path.convert_to_string(
   1430             path, transform, clip, simplify, sketch,
   1431             6,

AttributeError: 'module' object has no attribute 'convert_to_string'
```

Maybe it's due to a missing `self` in this line: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py#L1425

**Comment by tacaswell** [comment]
Can you provide a minimal example and a full traceback?  I can not even tell which module that code is from.

**Comment by WeatherGod** [comment]
No, it is a static method, so the call signature does not get a `self`. Chances are, there is something wrong with your install/build. Could you please include the full traceback, and describe what version of matplotlib you have, and how it was installed?

**Comment by efiring** [comment]
Closing; there is nothing we can do with the information available.
