### ISSUE TITLE
Can't show images when plt.show() was executed

### ISSUE THREAD

**Issue by phfony** [matplotlib/matplotlib#6306]
Matplotlib version 1.4.3
Python version 2.7.* and 3.4.* is tried
Platform Linux(OpenSuse)

I install Matplotlib with command: pip install matplotlib

```python
import scipy.misc
import matplotlib.pyplot as plt

lena = scipy.misc.lena()
acopy = lena.copy()
aview = lena.view()

plt.subplot(221)
plt.imshow(lena)

plt.subplot(222)
plt.imshow(acopy)

plt.subplot(223)
plt.imshow(aview)

aview.flat = 0

plt.subplot(224)
plt.imshow(aview)

plt.show()
```

When I run this program, there is no reflection.
There is no error in this process.

```python
import scipy.misc
import matplotlib.pyplot as plt

lena = scipy.misc.lena()
acopy = lena.copy()
aview = lena.view()

plt.subplot(221)
plt.imshow(lena)

plt.subplot(222)
plt.imshow(acopy)

plt.subplot(223)
plt.imshow(aview)

aview.flat = 0

plt.subplot(224)
plt.imshow(aview)

plt.savefig('foo.png')
```
When I run this program, there is an new picture in the current folder

Thanks for your help!

**Comment by WeatherGod** [comment]
Chances are, you did not have any tk gui development packages installed
when you installed matplotlib. I think the pip installed version of
matplotlib defaults to using the tk backend, but it needs the tk dev
packages prior to building matplotlib (installing it afterwards doesn't fix
the problem, as you would still need to do a complete reinstall of
matplotlib). You could try the qt5agg backend, if you have Qt5 available.

**Comment by phfony** [comment]
@WeatherGod 
Thank! I'm going to try it.

**Comment by phfony** [comment]
How excited  I am! I solved it, 
```
ooo@linux-dbba:~/tmp> python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.get_backend()
u'agg'
```
The first solution(qt4 is needed):
import PyQt4
import matplotlib
matplotlib.use('qt4agg')
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()
```
The second solution(qt4 is needed):
edit matplotlibrc file.
```
vim ~/.config/matplotlib/matplotlibrc
line 38: update [backend:agg] to [backend:qt4agg]
```
 Sorry, my english is so poor, mabe some expression is not clear, you can communicate with me through email:phfony@phfony.com,thanks!

**Comment by WeatherGod** [comment]
Glad you solved it on your own. Do keep in mind that Qt4 is getting a bit
old, so at some point, you may need to update your matplotlibrc file to use
qt5agg. Obviously, the Qt5 libraries would need to in installed. In the
meantime, the qt4agg backend would work just fine.

**Comment by phfony** [comment]
@WeatherGod 
Thanks!

**Comment by bruce25796** [comment]
yes, add
`
Plt.savefig('foo.png')
`
