### ISSUE TITLE
Interactive figure issues with notebook backend

### ISSUE THREAD

**Issue by cycomanic** [matplotlib/matplotlib#6308]
I'm having issues with interactive (using interact) figures using ipython notebooks and the notebook backend (%matplotlib notebook). 

A self contained example of the issue is illustrated in this gist (you need to download and run it to see the issue):
https://gist.github.com/cycomanic/ec0145bb67d96ad9a0f27079779c3abc

Essentially if I create the figure inside a function call it gets plotted fine, however as soon as I move the slider the figure disappears and I get "No such comm" errors on the console. This is the case of the top two fields in the example notebook. 

If I create the figure outside of a function call on the other hand everything works fine (see the lower to part in the above notebook).

I'm running into this error because I'm creating a class which has a plotting method and I would really like to avoid having to pass a figure to it. 

I'm running Matplotlib 1.5.1, jupyter notebook server 4.1 on OpenSUSE installed via packagemanager.

Happy to provide more info if necessary.

Cheers
Jochen

**Comment by tacaswell** [comment]
This is mostly an issue with how the `display` machinery in the notebook works.  This is another expression of a long standing issue trying to create an interact widget + a figure in the same cell.

attn @Carreau

**Comment by Carreau** [comment]
Hum, I'm not the most experience with widgets. 

@jdfreder might be of help (though he is not full time on the project anymore). @sylvaincorlay might be of help too.

**Comment by soamaven** [comment]
Thx,  +1
I get the same behavior with matplot lib 1.5.1 and jupyter-client 4.2.2.

**Comment by WeatherGod** [comment]
can you confirm with either matplotlib master or with the v1.5.2 release
candidate?

**Comment by jenshnielsen** [comment]
@WeatherGod Master has the new widget based backend. It still have some rough edges and will not make it into 2.0 but makes this much better. I doubt there is any difference on 2.x or 1.5.2. In my experience you can make work with the current backend if you make sure that the figure is created in a different cell from the interact. See https://gist.github.com/jenshnielsen/20d9bf3fa40b309ad865 for an example

**Comment by soamaven** [comment]
Problem seems resolved in 2.0.0b1, but still choppy. 

I was able to make a relatively smooth interactive widget by using
```
%matplotlib inline
%config InlineBackend.figure_formats = {'svg',}
```

There is some latency, but no flashing of the figure as with `%matplotlib notebook` in 2.0.0b1

**Comment by tacaswell** [comment]
If you are using `notebook` you need to interact with the figure like a 'live' mpl figure (by updating the artists) rather than like an 'inline' figure where you need to re-create the entire figure from scratch each time.

**Comment by tacaswell** [comment]
See https://gist.github.com/tacaswell/b11cf6073c0e8b5e36e67f44ee5568a6 for an example of how to do this interaction

**Comment by tacaswell** [comment]
```python

%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets.widgets.interaction import interact
import ipywidgets.widgets as widgets

def plotsin(f, ln):
    x = np.linspace(-10,10, 2**10)
    s = np.sin(f*x)
    ax.lines[0].set_data(x, s)
    

fig, ax = plt.subplots(1,1)
ln = ax.plot([], [], label='sin')
ax.set_xlim(-10, 10)
ax.set_ylim(-1, 1)
def plot_interactive2():
    def pls2(f):
        plotsin(f, ln)
    ww = widgets.FloatSlider(description='frequency', min=1, max=100)
    interact(pls2, f=ww)

```

and in a different cell

```python
plot_interactive2()
```

**Comment by soamaven** [comment]
Ahh. I was using the `@interactive` decorator. I will try in a new cell. Do you know why this is required?

**Comment by tacaswell** [comment]
Because the nbagg widget was written before the ipywidgets framework was written so it does not integrate well.  On the master branch nbagg has been re-worked to use ipywidgets.

**Comment by Hades1996** [comment]
Damn this was driving me crazy, thanks

**Comment by tacaswell** [comment]
Closing as we are going to stick with shipping our orginal version of nbagg and direct user to `ipympl` for widgets integrated usage.

If you do `%matplotlib ipympl` and have `ipympl` installed (see https://github.com/matplotlib/jupyter-matplotlib ) you will get widget-ified figures that will play better with `@interactive`.
