### ISSUE TITLE
Qt properties editor could sort lines labels using natsort

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6315]
When there are more than 10 (unlabeled) lines in a graph, they appear in the combobox as
```
_line0
_line1
_line10
_line11
...
_line2
_line3
```
etc.

"Natural" integer sorting (https://pypi.python.org/pypi/natsort) would be, well, more natural here.  Or one could hack the "default" labels ("_lineX") to return a str subclass with a custom comparator, so that other labels are not affected.

**Comment by tacaswell** [comment]
Probably simpler to pad out the default labels to 2 places.

Both of those suggestions (picking up an extra dependancy or subclassing str) bring in too much complication.
