### ISSUE TITLE
Cannot import mpl_toolkits in Python3

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#6318]
Can't import `mpl_toolkits` on `Python3`.  Will need other parts of `mpl_toolkits` soon. 

 `python3` version is `3.5.1`
`matplotlib` version is `1.5.1`
```
import mpl_tookits
#Error
 #No module named 'mpl_tookits'
```
Luckily, I only need `basemap` right now
```
#Basemap Bug Fix
import importlib
mpl_toolkits = importlib.import_module('mpl_toolkits')
from mpl_toolkits.basemap import Basemap
```

**Comment by efiring** [comment]
This appears to be an oddity of your particular installation, not a general characteristic or a bug.  You could raise this on the matplotlib-users mailing list (after subscribing, if you have not already done so), including information about what your operating environment is and how you installed matplotlib.

**Comment by jolespin** [comment]
Hi elfring, thanks for responding. 

It seems to be a problem for others as well: 
https://github.com/pyinstaller/pyinstaller/issues/848
https://github.com/matplotlib/matplotlib/issues/3252/
http://matplotlib.1069221.n5.nabble.com/ImportError-No-module-named-mpl-toolkits-td43642.html
http://stackoverflow.com/questions/16769899/matplotlib-basemap-no-module-named-axes-grid1
https://borealperspectives.wordpress.com/2013/11/24/91/
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/KnbWZ5pl0pE
etc.

**Comment by efiring** [comment]
A potentially similar problem has cropped up before, as you note, but it is not a current matplotlib bug.  As explained in some of the reports you cite, there was an awkward transition period in the handling of namespace packages, when some mixtures of versions or sequences of installation could cause the problem.  Without more information it is impossible to even speculate on what is causing the present failure on your system--but I'm confident that it is a peculiarity of your installation, hence my recommendation that you raise your question (and add essential information) on the mailing list, where more people will see it and there will be a better chance of someone coming up with a solution.

**Comment by yogabbagabb** [comment]
Using http://stackoverflow.com/questions/18596410/importerror-no-module-named-mpl-toolkits-with-maptlotlib-1-3-0-and-py2exe, I found a way to import mpl_toolkits. The problem was that the package for mpl_toolkits had no "__init__.py" file.

**Comment by dbodily1** [comment]
Yea no __init__.py file, had to add one in recovery mode for OSX.  The new security layer is a bit of a pain to fix this bug.
