### ISSUE TITLE
matplotlib pcolormesh seems to slide some data around on the plot

### ISSUE THREAD

**Issue by mnky9800n** [matplotlib/matplotlib#6331]
Note, this question was originally posted by me on [stackoverflow](http://stackoverflow.com/questions/36799379/matplotlib-pcolormesh-creates-data-artifacts)

Matplotlib Version = 1.5.1
Installation method = anaconda

I'm plotting data using the `matplotlib` functions `pcolormesh` and `imshow` and when I use `pcolormesh` it produces artifacts where it seems to slide some of the data around:

[![pcolormesh][1]][1]

whereas `imshow` does not:

[![enter image description here][2]][2]

I was able to produce an example that has the same artifacting

    import numpy as np
    import pandas as pd
    
    data = pd.DataFrame({'x':np.random.normal(loc=0.5, size=5000)
                         , 'y':np.random.normal(loc=0.5, size=5000)
                         , 'z':np.random.normal(loc=0.5, size=5000)})
    
    data_pivot = data.pivot(index='x', columns='y', values='z')
    x = data_pivot.index.values
    y = data_pivot.columns.values
    z = data_pivot.values
    masked_data = np.ma.masked_invalid(z)

which produces the following figures like so:

    fig, ax = plt.subplots(1, figsize=(8,8))
    ax.pcolormesh(x, y, masked_data)

[![enter image description here][3]][3]

Where do these artifacts come from? There isn't anything wrong with the data as far as I can tell since the original data and the made up data produce the same result.

  [1]: http://i.stack.imgur.com/eu8fL.png
  [2]: http://i.stack.imgur.com/3M394.png
  [3]: http://i.stack.imgur.com/KGqnR.png

**Comment by efiring** [comment]
Pcolormesh requires X and Y to define a quadrilateral grid.  Each Zij determines the color of a quadrilateral defined by X and Y at ij, i,j+1, i+1,j, i+1,j+1.  In other words, X and Y define boundaries, not centers.  I don't understand how you are generating your X and Y, but I suspect the result is not consistent with what pcolormesh requires.

**Comment by mnky9800n** [comment]
Does this mean that Z always needs to be the same size as the layer beneath it? For instance, when plotting basemap maps?

**Comment by WeatherGod** [comment]
No, each pcolormesh "object" is independent of each other.

**Comment by WeatherGod** [comment]
also, which version of matplotlib are you using. Older versions had some very weird corner cases that *might* explain this problem (it was an oddity with handling polygons, but it was only exhibited in contourf3d() plots, IIRC).

**Comment by WeatherGod** [comment]
and I just noticed that you already stated that (v1.5.1), so that isn't the problem...

**Comment by mnky9800n** [comment]
I thought that there was a problem with parsing nans, so I added some using an example from [the basemap documentation for pcolormesh](https://basemaptutorial.readthedocs.org/en/latest/plotting_data.html#pcolormesh):

```
from osgeo import gdal
import numpy as np
import matplotlib.pyplot as plt
ds = gdal.Open("/home/max/Downloads/BasemapTutorial-master/code_examples/sample_files/dem.tiff")
data = ds.ReadAsArray()

data[data < data.mean()] = np.nan

x = linspace(0, map.urcrnrx, data.shape[1])
y = linspace(0, map.urcrnry, data.shape[0])

xx, yy = meshgrid(x, y)
masked_data = np.ma.masked_invalid(data)

fig, ax = plt.subplots(1, figsize=(4,4))

ax.pcolormesh(xx, yy, masked_data)
ax.set_ylim(0, y.max())
ax.set_xlim(0, x.max())
```
![image](https://cloud.githubusercontent.com/assets/942355/14787625/758faa18-0b04-11e6-88d0-7ad5868b9894.png)

However, as you can see this doesn't impact the figure the way it did before.

So I tried to replicate this as closely as possible in the code I actually want to get to work and I still get artifacts:

```
In[5]: fmd_df.head()
Out[5]:	lat	    lon	    b_value
1067	21.8	121.6	0.429033
1068	21.8	121.7	0.443072
1143	21.9	121.3	0.427714
1144	21.9	121.4	0.431214
1145	21.9	121.5	0.424853

val_df = fmd_df.pivot(index='lat', columns='lon', values='b_value')

fig, ax = plt.subplots(1, figsize=(8,8))

m = Basemap(projection='merc', 
              llcrnrlon=val_df.columns.min(), 
              llcrnrlat=val_df.index.min(), 
              urcrnrlon=val_df.columns.max(), 
              urcrnrlat=val_df.index.max(),
           )
m.drawcoastlines()

lats = val_df.index
lons = val_df.columns
data = np.ma.masked_invalid(val_df.values)

lons, lats = np.meshgrid(lons, lats)

m.pcolormesh(lons, lats, data, latlon=True)
```

![image](https://cloud.githubusercontent.com/assets/942355/14787719/fbea6c92-0b04-11e6-88b6-54a155c3068a.png)

I'm really not clear as to why this is happening.

**Comment by mnky9800n** [comment]
Two additional images for reference comparing imshow and pcolormesh.

![image](https://cloud.githubusercontent.com/assets/942355/14788354/c1f86cc0-0b07-11e6-938d-48c959d69ab5.png)

![image](https://cloud.githubusercontent.com/assets/942355/14788363/cbcc9154-0b07-11e6-862a-c10feda72cee.png)

**Comment by efiring** [comment]
In your last example, with 1-D `lats` and `lons` variables: are they sorted and strictly increasing, with uniform spacing, no gaps, no nans?  It looks like this is not the case, and that is the source of the difference.  For example, where you have the horizontal stretching in the "artifacts", this is simply because you have a larger interval in your `lons` array.  Imshow can only make rectangular blocks, all the same size and shape.  Pcolormesh uses the grid you give it; you are giving it an irregular grid.  Try plotting your meshgrid output with dots and you will see it.

As for the dimensions of the original 1-D lons and lats that go into the meshgrid: ideally, lons should be 1 element longer than the second dimension of Z, and lats should be 1 longer than the first dimension of Z, so that there is a boundary quadrilateral for each element of Z.  If this is not the case, you lose the last row and column of Z.

**Comment by mnky9800n** [comment]
I'm glad you confirmed this because I was inspecting the data I was feeding the plots and it is missing some steps. Nice to know that the problem is typically sitting in front of the computer.

**Comment by efiring** [comment]
It looks like no further action is needed so I am closing this.

**Comment by efiring** [comment]
@mnky9800n You might add a note to your stackoverflow post to completely resolve it.
