### ISSUE TITLE
Animation with blit broken

### ISSUE THREAD

**Issue by wernight** [matplotlib/matplotlib#6332]
Matplotliv 1.5.1 on Linux (Debian) [should have animations fixed in 1.5.1](https://github.com/matplotlib/matplotlib/commit/78bb82cec63f6f8adb5aa2e2ea62c99cca77249d) but I still get an error for what used to work.

Example:

````
%matplotlib inline
from pylab import *
import matplotlib.animation
import matplotlib.patches

fig, ax = plt.subplots(figsize=(13, 8))
def update(frame):  
    ax.add_patch(matplotlib.patches.Rectangle(numpy.array([0, 0]), 1, 1))
anim = matplotlib.animation.FuncAnimation(fig, update, frames=10, blit=True)  # blit=True !!
anim.save('anim.mp4', fps=20, writer='avconv', codec='libx264')
````

Gives:

````
python3.5/site-packages/matplotlib/animation.py in _draw_frame(self, framedata)
   1212         self._drawn_artists = self._func(framedata, *self._args)
   1213         if self._blit:
-> 1214             for a in self._drawn_artists:
   1215                 a.set_animated(self._blit)

TypeError: 'NoneType' object is not iterable
````

**Comment by WeatherGod** [comment]
For blitting to work properly in a FuncAnimation, the artists being updated
must also be returned by the updating function, IIRC.

**Comment by wernight** [comment]
Oh! Does that mean returning the `ax`? A good error message would be very useful. Something like: Blit requires the update function to return the artist being updated (e.g. XXX) but the function returned `None`.

**Comment by WeatherGod** [comment]
No, not `ax`. The patches you created.

I think there has been some fix-ups in master, but I think it might be more
in the direction of turning blitting off in the situation where the
function returns None.

**Comment by wernight** [comment]
Yes it works without blit. Not sure why I put it in the first place and the output looks the same; may be faster. It did use to work though as it is.

**Comment by WeatherGod** [comment]
Right, blitting is merely an optimization approach (though it does have
some nasty side-effects in certain edge-cases). Further, our code used to
be a fair amount more relaxed about this, but changes for v1.5 made things
more strict, which revealed bugs like this. If you don't need the speed
increases that blitting gives you, then feel free to turn that off (which
is the default).

**Comment by tacaswell** [comment]
blitting used to only be used for updating an interactive figure, if you are only saving a file blitting gets you nothing (we fully re-render every frame when saving to file).
