### ISSUE TITLE
[minor issue] animation.to_html5_video() with avconv

### ISSUE THREAD

**Issue by wernight** [matplotlib/matplotlib#6338]
Matplotliv 1.5.1 on Linux (Debian) animation's method `to_html5_video()` seems not to support AVconv:

Example:

```
%matplotlib inline
from pylab import *
import matplotlib.animation
import matplotlib.patches

fig, ax = plt.subplots(figsize=(13, 8))
def update(frame):  
    ax.add_patch(matplotlib.patches.Rectangle(numpy.array([0, 0]), 1, 1))
anim = matplotlib.animation.FuncAnimation(fig, update, frames=10)
anim.save('anim.mp4', fps=20, writer='avconv', codec='libx264')
```

Gives exception:

```
/opt/conda/lib/python3.5/site-packages/matplotlib/animation.py in to_html5_video(self)
    949                 # We create a writer manually so that we can get the
    950                 # appropriate size for the tag
--> 951                 Writer = writers[rcParams['animation.writer']]
    952                 writer = Writer(codec='h264',
    953            

/opt/conda/lib/python3.5/site-packages/matplotlib/animation.py in __getitem__(self, name)
     87         if not self.avail:
     88             raise RuntimeError("No MovieWriters available!")
---> 89         return self.avail[name]
     90 
     91 writers = MovieWriterRegistry()

KeyError: 'ffmpeg'
```

I'm not sure what it does, but just having the video displayed in Jupyter is pretty simple:

```
from IPython.display import HTML
import base64
anim.save('temp.mp4', fps=20, writer='avconv', codec='libx264')
with open('temp.mp4', 'rb') as f:
    video_tag = '<video controls alt="test" src="data:video/x-m4v;base64,{0}">'.format(base64.b64encode(f.read()).decode('utf-8'))
HTML(video_tag)
```

I didn't find a simple way to ask `to_html5_video()` to use AVconv or set the writer, and FFmpeg is kind of deprecated on Debian (see [package](https://wiki.debian.org/ffmpeg) info stating "Be careful, FFmpeg is not available on Debian 8 Jessie"). Simplest seems to support AVconv by default or as fallback.

**Comment by wernight** [comment]
Ha! I see, can set `rcParams['animation.writer'] = 'avconv'`. It's set by default to `ffmpeg` in my case, not sure why. It could be that Jupyter should actually have smarter defaults.

**Comment by WeatherGod** [comment]
You can also set the parameter in your matplotlibrc file as well to be more permanent.

**Comment by QuLogic** [comment]
I could have sworn Debian switched _back_ to ffmpeg since avconv is less developed/secure.

**Comment by dopplershift** [comment]
To be clear `anim.save()` and `anim.to_html5_video()` are two *completely* different things. The former is for manually saving the animation to whatever format you want; the latter is for notebook inline views, and is called automatically if the `animation.html` rcparameter is set to 'html5'.

The reason the html5 video is locked to ffmpeg is because that's the only one for which I was able to reliably find the magic incantation to create h264 video that plays in multiple browers on multiple platforms. Incantations for other tools welcome, but making them robust wasn't simple, at least as simple as I expected.

**Comment by Thatfreesky** [comment]
How to do 
> rcParams['animation.writer'] = 'avconv'

I can not solve this problem:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-5114ccf53b4c> in <module>()
----> 1 HTML(anim.to_html5_video())

/home/mountain/anaconda3/envs/biomedickeras/lib/python2.7/site-packages/matplotlib/animation.pyc in to_html5_video(self)
   1153                 # We create a writer manually so that we can get the
   1154                 # appropriate size for the tag
-> 1155                 Writer = writers[rcParams['animation.writer']]
   1156                 writer = Writer(codec='h264',
   1157                                 bitrate=rcParams['animation.bitrate'],

/home/mountain/anaconda3/envs/biomedickeras/lib/python2.7/site-packages/matplotlib/animation.pyc in __getitem__(self, name)
    128         if not self.avail:
    129             raise RuntimeError("No MovieWriters available!")
--> 130         return self.avail[name]
    131 
    132 writers = MovieWriterRegistry()

KeyError: u'ffmpeg'
```

**Comment by wernight** [comment]
import matplotlib
    print(matplotlib.animation.writers.list())

This show what's available.

There are two issues here:

1. I've avconv on my system but it's not detected.
2. It should do like `if name not in self.avail: raise RuntimeError("Current animation.writer ({}) is not one of available writers detected ({}).".format(name, self.avail))`

**Comment by tacaswell** [comment]
@wernight I believe that https://github.com/matplotlib/matplotlib/pull/8743 is a fix for your issue.

**Comment by wernight** [comment]
@tacaswell Probably a fix for (1). I'd suggest also fixing (2).

**Comment by dopplershift** [comment]
@wernight I'd merge a PR doing so--would you submit?

**Comment by wernight** [comment]
It would take me a lot of time to test it. I almost wrote the change here in my comment.

**Comment by jonathan-alvaro** [comment]
Is this issue still open? If yes, I would like to try tackling it.

**Comment by jklymak** [comment]
Seems like it’s still an issue but I’ve not tested.  Test it first and if it’s an issue go ahead and follow up with a PR!

**Comment by ksunden** [comment]
Libav/avconv is now completely abandoned, so no reason to support it here
