### ISSUE TITLE
pyplot.hist: normalization fails

### ISSUE THREAD

**Issue by khyox** [matplotlib/matplotlib#6357]
Matplotlib 1.5.1 under python 3.5.1. 
The [provided example](http://matplotlib.org/mpl_examples/statistics/histogram_demo_features.py) for pyplot.hist is not working as expected for different _mu_ and _sigma_ values:

```python
"""
Demo of the histogram (hist) function with a few features.

In addition to the basic histogram, this demo shows a few optional features:

    * Setting the number of data bins
    * The ``normed`` flag, which normalizes bin heights so that the integral of
      the histogram is 1. The resulting histogram is a probability density.
    * Setting the face color of the bars
    * Setting the opacity (alpha value).

"""
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt


# example data
mu = 0.5*5  # mean of distribution
sigma = 0.1*5  # standard deviation of distribution
x = mu + sigma * np.random.randn(10000)

num_bins = 50
# the histogram of the data
n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='green', alpha=0.5)
# add a 'best fit' line
y = mlab.normpdf(bins, mu, sigma)
plt.plot(bins, y, 'r--')
plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title(r'Normed histogram of IQ: $\mu=%f$, $\sigma=%f$' % (mu, sigma))

# Tweak spacing to prevent clipping of ylabel
plt.subplots_adjust(left=0.15)
plt.show()
```
![hist_normed](https://cloud.githubusercontent.com/assets/4109713/14942083/ae4f6e1c-0fb2-11e6-92f6-843e29a263ba.png)

If the parameters _mu_ and _sigma_ are reduced to:

```python
mu = 0.5*2  # mean of distribution
sigma = 0.1*2  # standard deviation of distribution
````
the plot becomes even more clearly unnormalized:

![hist_normed_fail](https://cloud.githubusercontent.com/assets/4109713/14942077/8ab63fa8-0fb2-11e6-9ab6-dc25ed0e81cb.png)

This fail with normalization also happens for non-gaussian datasets.

**Comment by jenshnielsen** [comment]
Are you sure that you are interpreting the normalization correctly? It normalizes the area under the curve not the sum of the counts.  See #6353 for a similar issue.
I haven't done an independent calculation of the normalization but the area under the curve in the last example is roughly (drawing a triangle around the data)  `1*2*(0.5) = 1` so I don't see how this is clearly not normalized.

**Comment by khyox** [comment]
@jenshnielsen Thank you very much for your fast and useful reply. OMG, I was clearly misinterpreting the normalization despite all the comments. I took for granted the approach in which the normalized count is the count in a class divided by the total number of observations. Further away my slip, I suggest to improve the [web documentation](http://matplotlib.org/api/pyplot_api.html) of pyplot.hist in two ways:
* An improved explanation for the normalization factor, so that it clearly shows that the normalized count is the count in the class divided by the number of observations times the class width. I think that ``` (n/(len(x)`dbin)``` (literally) is not very clear in that sense.
* And, please, in the [provided example in the doc](http://matplotlib.org/mpl_examples/statistics/histogram_demo_features.py) replace:
```python
plt.ylabel('Probability')
```
with:
```python
plt.ylabel('Probability Density')
```
Thanks again!

**Comment by tacaswell** [comment]
@khyox Can you open up a pull request making those changes to the documentation?

**Comment by khyox** [comment]
@tacaswell Of course, Thomas, and very sorry for not having done it yet (about to travel to Japan for the 1st time and a bit bewildered... 👾).

**Comment by khyox** [comment]
PR ready! 📦
