### ISSUE TITLE
Bug: matplotlib.pyplot.spy: does not work correctly for sparse matrices with many entries (>= 2**32)

### ISSUE THREAD

**Issue by jor-** [matplotlib/matplotlib#6368]
matplotlib.pyplot.spy does not work correctly for sparse matrices with a large number of entries (>= 2**32). I would guess it has something to do with the value range of int32. 

An example that reproduces the bug is:

```
import numpy as np
import scipy.sparse
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
n = 16
s = 2**n
A = scipy.sparse.coo_matrix(np.ones((s,s), dtype=np.int8))
plt.spy(A)
file = '/tmp/spy_{}.png'.format(n)
plt.savefig(file)
```

For n = 16, spy shows only some entries.
![spy_16](https://cloud.githubusercontent.com/assets/2393560/15041512/d5aae93e-12bc-11e6-8914-4bb839c7f117.png)
For n = 15 it works correctly.
![spy_15](https://cloud.githubusercontent.com/assets/2393560/15041505/d0300750-12bc-11e6-8240-0afdd63cdd02.png)

I have used Matplotlib 1.5.1 installed over pip with Python 3.5.1 on Linux.

**Comment by jor-** [comment]
I have traced back the bug a little. ``matplotlib.axes.Axes.add_line`` does not work correctly for a large number of data (>= 2**32). See #6413.

**Comment by efiring** [comment]
I'm going to close this as a duplicate since #6413 is pointing to the root of the problem.
