### ISSUE TITLE
Deprecation warning for axes.color_cycle

### ISSUE THREAD

**Issue by fonnesbeck** [matplotlib/matplotlib#6395]
Running the current master on Python 3.5.1, I get the following deprecation warning when I attempt to import matplotlib:

```
/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
```

![warning](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-05-10-14-38-43.png)

System info:

Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55)   
[GCC 4.2.1 (Apple Inc. build 5577)]
OS X 10.11.4

**Comment by WeatherGod** [comment]
Most likely due to an outdated matplotlibrc file.

**Comment by fonnesbeck** [comment]
Thank you.
