### ISSUE TITLE
Rendered text images do not exactly overlap for same text content

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#6411]
Matplotlib v1.5.1, Python 3.5.0, Windows x64
Installed from http://www.lfd.uci.edu/~gohlke/pythonlibs/#matplotlib

I used matplotlib to render text line images. For two text strings, say "the" and "the f",  ideally, the rendered two images should exactly overlap for text content "the", however, actully when rendered with certain fonts, these two images do not overlap perfectly. The difference image shows there is a little shift of text . So I'm wondering is this supposed to be right? What if I want these two images perfectly overlap for the same text content?

**Comment by daweileng** [comment]
A code snippet demonstrates the problem:

```
from matplotlib import pyplot as plt
from matplotlib import font_manager

def generate_line_samples(file, txt, font, fontsize, DPI, figsize = [1, 0.5]):
    fig = plt.figure(figsize=figsize)
    fontproperties = font_manager.FontProperties(fname=font, style='normal', size=fontsize)
    ax = fig.gca()
    ax.clear()
    ax.set_frame_on(False)
    ax.set_xticks([])
    ax.set_yticks([])
    t = ax.text(s=txt, fontproperties=fontproperties, x=0, y=0.2,
                horizontalalignment='left', verticalalignment='baseline')
    fig.savefig(file, dpi=DPI)
    plt.close(fig)


if __name__ == '__main__':
    font = 'angsa (599).ttf'
    generate_line_samples(file='test1.jpg', txt='the', font=font, fontsize=13, DPI=400, figsize=[0.7, 0.5])
    generate_line_samples(file='test2.jpg', txt='the f', font=font, fontsize=13, DPI=400, figsize=[0.7, 0.5])

```

The font file and the difference image can be found in my repository https://github.com/daweileng/matplotlib_debug.

**Comment by tacaswell** [comment]
attn @mdboom 

The diff image:

![image](https://cloud.githubusercontent.com/assets/199813/15296758/cec1ca42-1b64-11e6-9d11-ac8c66726e0e.png)


odd that it only hits the 't' (which is shifted slightly to the left due to extra padding added between 't' and 'h'.

I wonder if this is mpl caused or freetype caused?

**Comment by anntzer** [comment]
This is due to freetype hinting, e.g. forcing backend_agg.get_hinting_flag to return LOAD_NO_HINTING results in the "h" and the "e" being misaligned rather than the "t".

**Comment by tacaswell** [comment]
Closing this as a) it is due to freetype b) the OP has deleted their account
