### ISSUE TITLE
EventCollection._is_horizontal remains uninitialized, causing eventplot error

### ISSUE THREAD

**Issue by jniediek** [matplotlib/matplotlib#6412]
`EventCollection` does not set its property `is_horizontal` when the `positions` argument is empty. This causes an error in `pyplot.eventplot` if you pass multiple lists of events, with the first one empty. The reason is the line

 if colls[0].is_horizontal():

in `eventplot` (defined in `axes/_axes.py`)

A minimal working example is the following:

```
import matplotlib.pyplot as mpl
mpl.eventplot([[0], [0, 1]])
mpl.show()
mpl.eventplot([[], [0, 1]])
mpl.show()
```

The first call to eventplot produces the correct plot, but the second one fails with

```
AttributeError: 'EventCollection' object has no attribute '_is_horizontal'
```

The error is present in matplotlib 1.5.1. 

I would like to create a pull request to fix this. I suggest setting `.is_horizontal` to `True` by default.

**Comment by tacaswell** [comment]
It would be better to pick apart the horizontal/vertical state from the parsing the positions logic.

Can you also add a test for this?

**Comment by jgosmann** [comment]
Any easy workaround until this is fixed?

**Comment by afvincent** [comment]
:/ not sure. I'll try to open a PR soon
