### ISSUE TITLE
Bug: matplotlib.axes.Axes.add_line: does not work correctly for a large number of data (>= 2**32)

### ISSUE THREAD

**Issue by jor-** [matplotlib/matplotlib#6413]
matplotlib.axes.Axes.add_line does not work correctly for a large number of data (>= 2**32). I would guess it has something to do with the value range of int32.

An example that reproduces the bug is:

```
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.lines
n = 16
s = 2**n
a = np.arange(s)
x, y = [b.flatten() for b in np.meshgrid(a,a)]
line = matplotlib.lines.Line2D(x, y, linestyle='None', marker='s', markersize=10)
fig = plt.figure()
ax = plt.gca()
ax.add_line(line)
ax.set_xlim(xmin=0, xmax=s)
ax.set_ylim(ymin=0, ymax=s)
file = '/tmp/line_{}.png'.format(n)
plt.savefig(file)
plt.close(fig)
```

For n = 16, no entries are shown.
![line_16](https://cloud.githubusercontent.com/assets/2393560/15209953/341555aa-1834-11e6-958f-531e32039842.png)

For n = 15, everything looks fine.
![line_15](https://cloud.githubusercontent.com/assets/2393560/15209956/3907fa9a-1834-11e6-8eeb-bd223cf068e7.png)

I have used Matplotlib 1.5.1 installed over pip with Python 3.5.1 on Linux.

**Comment by efiring** [comment]
I think this is an inherent limitation in agg.  If so, the question is why we are not trapping it and either raising an exception or handling it by breaking the line into segments.  Attn @mdboom.

**Comment by timhoffm** [comment]
Pretty sure this is an Agg limitation. Nothing we can do about it.

In practice one should pre-filter data and not try to plot 2*32 points anyway.
