### ISSUE TITLE
matplotlib Qt5Agg backend error: 'figure' is an unknown keyword argument

### ISSUE THREAD

**Issue by dstrozzi** [matplotlib/matplotlib#6420]
I'm using Matplotlib 1.5.1 under python 3, installed via anaconda, on a Windows 7 machine.  When I use Qt5Agg as the matplotlib backend (set via my matplotlibrc file), I get the error in the subject line. It is very simple to reproduce:

Start python from a cmd.exe prompt
from pylab import *
figure(1)
Same problem in ipython.

I posted this issue earlier in the week on stackoverflow, got no response.

**Comment by jenshnielsen** [comment]
I think this is due to the Qt4 and QT5 backends being mixed up somehow. It's similar to what I saw in #3623 but that should have been fixed before 1.5.1 so not exactly sure why you see it

Do you have PyQt4/Pyside 1 installed on your computer?

**Comment by jenshnielsen** [comment]
Also can you try doing 

```
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
plt.plot(range(10))
```
And see if that works? It fixes the backend before importing pyplot or pylab

**Comment by tacaswell** [comment]
continuum does not ship Qt5 binaries or PyQt5 so I do not expect this to work.

**Comment by dstrozzi** [comment]
Ah, that's good to know!  Would it at all be possible for matplotlib to
give a more meaningful error, like "Could not find PyQt5 installed?"

Thanks,
Dave


On Sat, May 14, 2016 at 11:40 AM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
The logic for this is in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py which does need a clean up.  

Does in behave better on master?

**Comment by tacaswell** [comment]
This issue is still present on master.

We should either make sure that if qt5 import fails we raise.  This might cause problems for people who are `qt_compat.py` for external projects.

**Comment by kaspervanwijk** [comment]
In matplotlib 1.5.3 and python 3.5.2 from conda (OS is FC24), the default Qt4Agg backend leads to a segmentation fault (core dumped) without other errors. If I set it to Qt5Agg, I get the aforementioned error:

File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 239, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: 'figure' is an unknown keyword argument

If I set the backend to TkAgg, there is no problem:

import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()

**Comment by CarlosRDomin** [comment]
On Python 2.7.12_2, I get the same "TypeError: 'figure' is an unknown keyword argument" using Qt5Agg as the backend, but Qt4Agg works fine. I have Qt5.7 and PyQt5.7 installed and they work well for other projects' UIs.
I'm on OSX Yosemite, matplotlib 1.5.3.

**Comment by tacaswell** [comment]
@CarlosRDomin You most likely have pyqt4 installed and are hitting that instead.

The source of that exception is between pyqt4 and pyqt5 they switched to using cooperative multiple inheritance (so you _must_ use `super`) where as with pyqt4 you must _not_ use `super`.

**Comment by kaspervanwijk** [comment]
Updates with dnf and conda have fixed my problems when I set the Qt4Agg backend as the default in my matplotlibrc ( and using pyside bindings).

Here are the versions:
qt                        4.8.7                         3    conda-forge
pyside                    1.2.4                    py35_1    conda-forge

> sudo dnf info pyqt4
Last metadata expiration check: 1 day, 1:08:45 ago on Tue Oct 25 08:59:03 2016.
Installed Packages
Name        : PyQt4
Arch        : x86_64
Epoch       : 0
Version     : 4.11.4
Release     : 14.fc24
Size        : 15 M
Repo        : @System
From repo   : @commandline
Summary     : Python bindings for Qt4
URL         : http://www.riverbankcomputing.com/software/pyqt/
License     : (GPLv3 or GPLv2 with exceptions) and BSD
Description : These are Python bindings for Qt4.

Just for the record, using the pyqt5 results in an error:

File "matplotlibtest.py", line 5, in <module>
    plt.plot(range(10))
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3154, in plot
    ax = gca()
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 936, in gca
    return gcf().gca(**kwargs)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 223, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/kvan637/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 239, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
AttributeError: 'figure()' is not a Qt property or a signal

**Comment by mat2py** [comment]
This failed for me too, Spyder (the GUI) was set to use Qt5, once I changed it to 'Automatic' it worked fine. Not sure what automatic implies though.

**Comment by anntzer** [comment]
I believe this should be fixed by https://github.com/matplotlib/matplotlib/pull/8315 as there is no implicit fallback anymore.  Feel free to reopen the issue otherwise.
