### ISSUE TITLE
add drawstyle option to fill_between function

### ISSUE THREAD

**Issue by sbarthelemy** [matplotlib/matplotlib#643]
Hi,

I think the fill_between function should take a drawstyle option. It would be both handy and consistent.

Here is a post from someone else requesting the feature, with a figure illustrating why this is needed:
http://old.nabble.com/fill_between-with-drawstyle-steps--td30172277.html

thank you

**Comment by dguest** [comment]
This would be a very nice addition, @tacaswell do you think this would be implemented soon? I've written something similar myself (and step style is more or less required in my field, so I'm sure quite a few others have as well), but it would be great to see a standard solution.

**Comment by tacaswell** [comment]
I would just use the function above for now.  The only hold up is I am not sure if this should be it's own function `step_fill_between` or as a flag in the current `fill_between`.

**Comment by efiring** [comment]
I would vote for an additional kwarg in fill_between, and presumably in fill_betweenx as well.

**Comment by brovercleveland** [comment]
Great solution @tacaswell.  I would additionally request the ability to specify N+1 step edges for N step values.  Currently I am using your solution by plotting the first bin with `step_where='post'`, then the remaining bins with `step_where='pre'`.  Also, the poly collection that is specified by `fill_between` does not support `legend()`, which is unfortunate.
