### ISSUE TITLE
micro sign doesn't show in EngFormatter

### ISSUE THREAD

**Issue by amro-pydev** [matplotlib/matplotlib#6432]
Hi,
I'm currently using version 1.5.1 that is installed through anaconda.

When I used the "EngFormatter" "from matplotlib.ticker import EngFormatter", it works perfectly with all engineering notations except for the micro sign. It doesn't appear in the plot. 

Please see the snapshot attached.
![micron_issue](https://cloud.githubusercontent.com/assets/15850994/15280380/c628e396-1ae4-11e6-899f-36bba590e7c7.PNG)

Regards,
Amro

**Comment by amro-pydev** [comment]
Hi,
As a work around, I did the following:
eng_formatter = EngFormatter(unit='m', places=2)
eng_formatter.ENG_PREFIXES[-6] = "u"

And it worked.
Regards,
Amro

**Comment by amro-pydev** [comment]
Finally , I got it to use the correct symbol.

eng_formatter.ENG_PREFIXES[-6] = u"\u00B5"

**Comment by tacaswell** [comment]
This is a font issue (the default font does not have that unicode point).

This will work out of the box in 2.0 on ward (we are changing the default font to one with many more code points).

**Comment by tacaswell** [comment]
Closing this as

 a) OP fond work around
 b) changing font to one with more codepoints works (http://matplotlib.1069221.n5.nabble.com/Change-default-font-td19577.html)
 c) this works out of the box on 2.x/master branches.
