### ISSUE TITLE
Inequality error on web page http://matplotlib.org/faq/howto_faq.htm

### ISSUE THREAD

**Issue by Christopher-Field** [matplotlib/matplotlib#6451]
On the web page http://matplotlib.org/faq/howto_faq.html there is a section "nterpreting box plots and violin plots" which has an inequality to define outliers. The left side of the inequality is smaller than the right side, but the inequality uses greater than symbols (">"). Therefore, it makes no sense.
[Interpreting_box_plots.pdf](https://github.com/matplotlib/matplotlib/files/272632/Interpreting_box_plots.pdf)

The statement can be corrected in one of two ways.
Change to "Data points are not considered outliers if " and change the greater thans to less thans.
Or leave the text unchanged and break the inequality into two parts
Value < Q1 - 1.5 *IQR  or Q3 + 1.5 * IQR < Value.
This second approach makes clear that outliers are outside the range.

**Comment by tacaswell** [comment]
attn @rasbt

**Comment by rasbt** [comment]
Oh, that's weird, I thought that we already fixed it! (At least it appears fixed in my keynote file when I just opened it!) Anyway, thanks for the note, I will open a pull request!
