### ISSUE TITLE
Please add a generic "seaborn" style

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#6452]
I'm glad that matplotlib has included seaborn aesthetics in its built-in style sheets. However, the way that the different elements of the seaborn aesthetics were split up (i.e., that there are separate `seaborn-darkgrid`, seaborn-deep`, etc.) is both a little confusing and produces results that are, imo, visually unappealing.

I would much prefer if there were also a single "seaborn" style that encompasses `seaborn-darkgrid`, `seaborn-deep`, and `seaborn-notebook`, so that doing `plt.style.use("seaborn")` would create plots that look the same as actually importing seaborn.

**Comment by tacaswell** [comment]
Did that PR to put styles in style sheets get merged?

**Comment by mwaskom** [comment]
Not sure, but I just came across [this](http://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html) which prompted the issue.

**Comment by WeatherGod** [comment]
Here is the PR that originally added the seaborn style sheets along with
discussion of rationale of splitting it up:
https://github.com/matplotlib/matplotlib/pull/4570

I have no problem with a unified seaborn style sheet, but right now, I
don't think we have the capability of recursively loading sheets as
specified in another sheet.

On Thu, May 19, 2016 at 12:13 PM, Thomas A Caswell <notifications@github.com

**Comment by mwaskom** [comment]
But you could just put all of the aesthetics into one sheet, right?

**Comment by WeatherGod** [comment]
correct

**Comment by mwaskom** [comment]
Hah, I see now that I initially advocated for what I'm now objecting to... Although I think what I probably had in mind was that `seaborn-darkgrid` would correspond to the default seaborn aesthetics, i.e. darkgrid +  notebook + deep palette.

Anyway, having now seeing the result of my hasty suggestion, I do think that it's is not ideal because people who want their plots to look "like seaborn" should probably be able to do so with minimal effort. Currently you'd have to be aware of a number of relatively internal seaborn details (like the bad name for the default palette).

I also think that having so many "seaborn" styles is likely very confusing in the context of tools like [this](http://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html), because they totally dominate the list. Ultimately what to do about that is up to you folks, but I'd suggest that it might be better to scale back the extent to which matplotlib styles fully replicate the aesthetic control that seaborn has. (Similarly, the "ggplot" style is just one of the many themes that ggplot can do).

**Comment by WeatherGod** [comment]
I would be completely in favor of putting in a consolidated "seaborn" style sheet. As for the other sheets, maybe a way to specify "sub-sheets" might help, perhaps? Is there any analogous concept in CSS?

**Comment by tacaswell** [comment]
I am :+1: on adding a single 'seaborn' sheet, but am a bit worried about _removing_ styles that we have been shipping for a year.

**Comment by mwaskom** [comment]
Thanks @tacaswell !
