### ISSUE TITLE
Strange behavior in scatter when size is very small

### ISSUE THREAD

**Issue by rodonn** [matplotlib/matplotlib#6453]
When I make a scatter plot with sizes that vary over a large range 1e-1 to 1e-40 I've been getting some strange behavior where some of the points which have extremely small sizes get show much larger than they should be.

```
import matplotlib.pyplot as plt
import numpy as np
import random

x = np.repeat([a for a in range(1,101)], 100)
y = [random.random() for i in range(len(x))]
s = np.exp(-x)
plt.scatter(x,y,s)

plt.show()
```

In this image the sizes should be monotonically decreasing along the x axis, but instead they reappear briefly and then disappear again.
![image](https://cloud.githubusercontent.com/assets/2594443/15438811/c8142868-1e82-11e6-845d-9931339807e2.png)

I'm using 
Matplotlib version '1.5.1'
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

**Comment by rodonn** [comment]
Here's a close up of the "problem area"
```
x = np.repeat([a for a in range(56,68)], 100)
y = [random.random() for i in range(len(x))]
s = np.exp(-x)
plt.scatter(x,y,s)

plt.show()
```
![image](https://cloud.githubusercontent.com/assets/2594443/15438931/5e43e648-1e83-11e6-935d-1af8e315e2b8.png)

And here's the normal looking behavior when I don't let the sizes get so small
![image](https://cloud.githubusercontent.com/assets/2594443/15438965/886b295e-1e83-11e6-8449-de13ebec75a2.png)

**Comment by tacaswell** [comment]
I can not reproduce this on current master or 2.x but can reproduce this on 1.5.1 and 1.5.x.  The change is due to how the edge width on scatter is set.  


```python
import matplotlib.pyplot as plt
import numpy as np
import random

x = np.repeat([a for a in range(1,101)], 100)
y = [random.random() for i in range(len(x))]
s = np.exp(-x)
plt.scatter(x,y,s, linewidths=0)

plt.show()
```

works correctly on v1.5.x, and `plt.scatter(x,y,s, linewidths=1)` reproduces this on v2.x.

**Comment by efiring** [comment]
I'm surprised that a finite linewidth doesn't simply impose a minimum size, regardless of the requested size of the marker.  For the desired behavior, the logical solution is to use `linewidths=0`.  The odd behavior with finite linewidth seems to be an obscure bug in the agg rendering.  It looks like an aliasing phenomenon, or an integer wraparound.

**Comment by chahak13** [comment]
While this is undesirable, there is a lot more complexity going into the strokes that having linewidth follow the rules is much more difficult. For reference, #25410 talks about a similar problem. Closing this issue for now.
