### ISSUE TITLE
Notebook backend not working

### ISSUE THREAD

**Issue by beojan** [matplotlib/matplotlib#6454]
Plotting with the notebook backend results in no plot appearing. In the Jupyter notebook console, I get:

`404 GET /static/matplotlib.js?v=20160521145157`

Using Matplotlib from git with Python 3.5 on Archlinux.
Problem exists with Jupyter 4.2 installed with PIP, and after upgrading notebook to git master.

**Comment by jenshnielsen** [comment]
Following the merge of #5754 the notebook backend has been integrated with the Jypyter notebook extensions. This requires explicitly enabling the Jupyter notebook extension. 

```
jupyter nbextension enable --py matplotlib
```
Unfortunatly this is not really documented anywhere yet. Unless you really need something on the master branch I would recommend using the 2.x branch at this stage which is significantly more stable. 

There are several other issues with the new notebook backend following that merge see #6414

**Comment by shoeffner** [comment]
Since it was really hard to find it for me, here is explained how to get it back running, it's in the package ipympl: https://github.com/matplotlib/jupyter-matplotlib .

Also to install you can't use `jupyter nbextension enable --py matplotlib` (or at least I could not) but of course then you have to use `jupyter nbextension enable --py ipympl`.

**Comment by beojan** [comment]
I'm now getting the same error again, *after* installing `ipympl` as @shoeffner said.

**Comment by phobson** [comment]
@beojan with the latest version of jupyter, notebook, and matplotlib, installing and enabling an extension shouldn't be required. In other words, on my system:

```
conda create --name=mpltest python=3.6 matplotlib notebook
```

Is all a need to use `%matplotlib notebook` in a jupyter notebook.

**Comment by beojan** [comment]
The extension is required if you use matplotlib from git master.

On Apr 19, 2017 4:56 PM, "Paul Hobson" <notifications@github.com> wrote:

@beojan <https://github.com/beojan> with the latest version of jupyter,
notebook, and matplotlib, installing and enabling an extension shouldn't be
required. In other words, on my system:

conda create --name=mpltest python=3.6 matplotlib notebook

Is all a need to use %matplotlib notebook in a jupyter notebook.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/matplotlib/matplotlib/issues/6454#issuecomment-295321164>,
or mute the thread

**Comment by tacaswell** [comment]
ipympl and the notebook backend are different backends (both run in the notebook, but they use different js and communication methods).

**Comment by dstansby** [comment]
@beojan it's been a while since you opened the issue - is this still a problem with newer versions of Matplotlib for you?

**Comment by QuLogic** [comment]
Closing as there's been no response in a year.
