### ISSUE TITLE
Wrong package name in INSTALL file

### ISSUE THREAD

**Issue by Kondra007** [matplotlib/matplotlib#6458]
The documentation in `INSTALL` file says to execute `sudo apt-get install python-matplotlib` command. However, on both Windows and Linux an error "Can't find package" occurs. Replacing `python-matplotlib` to just `matplotlib` does the trick and install correct version of library. 

It this a bug in docs?

**Comment by jenshnielsen** [comment]
I'm not sure why you are using `atp-get` on windows. Apt-get is only for Debian/Ubuntu packages. Are you by any change mixing up `pip` and `apt-get`? 

The Ubunutu package is called python-matplotlib according to the Ubuntu documentaion see http://packages.ubuntu.com/search?keywords=matplotlib&searchon=names&suite=xenial&section=all

**Comment by Kondra007** [comment]
Yep, sorry, my mistake. Mixed `pip` and `apt-get`. Sorry again.

**Comment by jenshnielsen** [comment]
No worries
