### ISSUE TITLE
re-enable building conda package artifacts on appveyor / fix conda recipe

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6460]
In https://github.com/matplotlib/matplotlib/pull/6423 the conda package building was disabled due to libpng related build failures.

The failures are odd given that the build works the `python setup.py develop` used for running the tests.

See for details https://github.com/matplotlib/matplotlib/pull/6423#issuecomment-219472713

**Comment by tacaswell** [comment]
@pelson

**Comment by janschulz** [comment]
It seems that due to the way that conda-forge now has a libpng and this lib is differently named, we need a patch: https://github.com/conda-forge/matplotlib-feedstock/commit/410106aaf172536f74843c414927ec092b07395d#diff-ead893c9f392df956860bfe6a5dae3a8R6

The test probably work because of https://github.com/matplotlib/matplotlib/blob/master/appveyor.yml#L80 which put the static verison into a special dir and renames it.

I'm not sure how to proceed: I find it very unfortunate that the conda-forge and default libpng seem to differ. 

@ocefpaf do you have any idea why that is so?

**Comment by ocefpaf** [comment]
> @ocefpaf do you have any idea why that is so?

The only difference is that we updated `libpng`. Not sure if there is any **actual** difference in the build that caused the different naming. I will investigate this more and, if that is something we can avoid, we will!

**Comment by janschulz** [comment]
I can't even install that lib?

```bat
c:\data\external\jupyter\jupyter_environment_kernels (conda_windows)
[cf_png] λ conda create -n cf_png2 libpng=1.6.21 -c conda-forge
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..................
Solving package specifications: ....

The following specifications were found to be in conflict:
  - libpng 1.6.21*
Use "conda info <package>" to see the dependencies for each package.
```

I compare the vc14 versions of the default channel (.17) and the conda-forge channel (.21):

https://anaconda.org/anaconda/libpng/1.6.17/download/win-64/libpng-1.6.17-vc14_1.tar.bz2
https://anaconda.org/conda-forge/libpng/1.6.21/download/win-64/libpng-1.6.21-vc14_1.tar.bz2

The most interesting thing seems to be that the defaults versions contains an extra file called `\Library\lib\png.lib which the conda-forge version does not contain. Both have the `\Library\lib\libpng.lib`.

It seems that the original recipe simply copies the file:

```bat
C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
λ diff libpng.lib  png.lib

C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
λ diff libpng16.lib  png.lib

C:\data\downloads\libpng\win-64-libpng-1.6.17-vc14_1\Library\lib
λ diff libpng16_static.lib  png.lib
Binary files libpng16_static.lib and png.lib differ
```

@ocefpaf: do you think it would be possible to simply do the same?

**Comment by janschulz** [comment]
zlib seems to already do the same: https://github.com/conda-forge/zlib-feedstock/blob/master/recipe/bld.bat#L22

**Comment by janschulz** [comment]
@ocefpaf:will send a PR against libpng-feedstock...

**Comment by janschulz** [comment]
PR is in https://github.com/conda-forge/libpng-feedstock/pull/4

**Comment by tacaswell** [comment]
This has been fully superseded by conda-forge, closing.
