### ISSUE TITLE
Test failures testing matplotlib 1.5.1 manylinux wheels

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#6469]
I have automated building of matplotlib manylinux wheels for matplotlib 1.5.1, adding a version of PR #6442 .

The build script is [here](https://github.com/matthew-brett/manylinux-builds/blob/master/build_matplotlibs.sh), and the build matrix is [here](https://travis-ci.org/matthew-brett/manylinux-builds/builds/132304156).

Now I'm testing these wheels on travis at [manylinux-testing](https://travis-ci.org/matthew-brett/manylinux-testing) with test script [here](https://github.com/matthew-brett/manylinux-testing/blob/master/test_mpl.sh).

(Is this the right way to run tests on an installed matplotlib?)

But - I am getting test failures that look unrelated to the manylinux build itself - see [failing matplotlib test run](https://travis-ci.org/matthew-brett/manylinux-testing/jobs/132360195).

Would y'all mind casting your eyes over these failures to let me know if they are telling me anything bad about the manylinux build?

**Comment by tacaswell** [comment]
These tend to mean that there is an import error is those modules

```python
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'test_widgets')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/nose/util.py", line 322, in resolve_name
    obj = getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_widgets'

```

These are due to a bug fix in numpy that fixed some small-number rounding see https://github.com/matplotlib/matplotlib/issues/5950 and the ~~rabbit~~ dragon hole that leads to.

```python
======================================================================
FAIL: matplotlib.tests.test_axes.test_formatter_large_small.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /home/travis/build/matthew-brett/manylinux-testing/for_testing/result_images/test_axes/formatter_large_small.png vs. /home/travis/build/matthew-brett/manylinux-testing/for_testing/result_images/test_axes/formatter_large_small-expected.png (RMS 19.050)
```

**Comment by matthew-brett** [comment]
Great - just the feedback I needed.   Tests are now passing, after installing numpy 1.10.4, mock and sphinx: 

* Passing test matrix : https://travis-ci.org/matthew-brett/manylinux-testing/builds/132577898
* Diff to make tests pass : https://github.com/matthew-brett/manylinux-testing/commit/6134f9503ecc828eba4dbaee7966655ebd6db9a0
