### ISSUE TITLE
Savefig() to pdf renders markers differently than show()

### ISSUE THREAD

**Issue by nanicpc** [matplotlib/matplotlib#6477]
I'm making a scatter plot. Saving the figure in eps format makes (sometimes) a reproduction of the figure " show() " but the pdf changes (always) the configuration. For example, changing the colors and adding contour lines that weren't there.

![ex2](https://cloud.githubusercontent.com/assets/15998450/15545187/bf847bcc-229b-11e6-8eee-1556d2fd4336.png)

Even worst in some cases saving the figure weather in eps format or in the pdf changes the figure itself. 

![ex1](https://cloud.githubusercontent.com/assets/15998450/15545189/c3d8ffcc-229b-11e6-8c83-2133bba8653e.png)

```
fig2=plt.figure(figsize=[4,3])
fig2.add_subplot(111,yticks=[-4,0,4],xticks=[-10,0,10])
plt.scatter(X_l[:, 0], X_l[:, 1], c=np.array(colors[yy_lab].tolist()), s=np.array(sizes[yy_lab].tolist()),lw=0)
plt.axis([-11, 11, -4, 4])
fig2.savefig("fig.pdf",bbox_inches='tight',format='pdf')
fig2.savefig("fig.eps",bbox_inches='tight')
plt.show()
```

**Comment by WeatherGod** [comment]
Which version of matplotlib? I know some of the differences have been fixed
already. Also, which version of python?

**Comment by nanicpc** [comment]
Sorry.
Matplotlib 1.4.2
Python 3.4.3

**Comment by WeatherGod** [comment]
Yes, I think most if not all of those problems were fixed in 1.5.1, and
1.5.2 is in release candidate mode right now. Could you try with one of
those?

**Comment by tacaswell** [comment]
@WeatherGod What bugs were these?  I have no memory of anything like this going by.

**Comment by WeatherGod** [comment]
I am thinking along the lines of the dictionary ordering issue, maybe? TBH,
I can't quite remember what I was thinking when I wrote that.

**Comment by tacaswell** [comment]
@nanicpc Can you provide a runnable example?  Your code has a couple of undefined variables so it is hard to tell what you are doing.

**Comment by nanicpc** [comment]
i'm now using the 1.5.1 and the border inclusion is fixed and also the configuration is kept, you were right, thanks!
