### ISSUE TITLE
mpl_toolkits.mplot3d has a null byte somewhere

### ISSUE THREAD

**Issue by yogabbagabb** [matplotlib/matplotlib#6492]
To help us understand and resolve your issue please check that you have provided
the information below.

- Running Python 3.5 and Matplotlib 1.5.1
- Installed Matplotlib using pip3

Whenever I write the following statement at the beginning of a module 
`from mpl_toolkits.mplot3d import Axes3D` 

,I am returned the following error:

Traceback (most recent call last):
  File "/Users/blah/blah/blah/scatter3d_demo.py", line 2, in <module>
    from mpl_toolkits.mplot3d import Axes3D
ValueError: source code string cannot contain null bytes

Presumably, either the mplot3d module or the Axes3D one has a null byte (I believe "\0") hidden somewhere, although I haven't found it in either module.

**Comment by tacaswell** [comment]
In the worst maintainer answer ever 'it works for me'.  We also test `mplot3D`  on both linux and windows CI which makes me think that your installation is corrupted.

Can you try re-installing (nuke everything and try again)?  Is it importing from the path you expect it to be installed?  Do you have more than one version of mpl installed and they are clashing?

**Comment by jenshnielsen** [comment]
In my experience namespace packages such as mplot3d (which is a namespace package to allow basemap and others to be installed into it externally) are notoriously flaky. Sources of error that I know of include pip installing on top of an existing version installed with `setup.py install` and the other way around. The best advise is as @tacaswell suggests to to make sure mpl_toolkits is completely removed before pip installing. In the long term we should probably convert mpl_toolkits into a regular package

**Comment by yogabbagabb** [comment]
I just uninstalled and installed matplotlib using pip. That didn't work, unfortunately. I ran a -find command using bash to identify redundancies of matplotlib's installation. matplotlib is installed, strangely enough, on python 2.6 and 2.7, which are built-ins for Mac OSX. Because I've configured pydev to use 3.5, should it matter that 2.6 and 2.7 have (in their sitepackages folder) matplotlib?

**Comment by jenshnielsen** [comment]
No only what's installed for that paticular python installation matters.

Running
```
python -m site
```
where python is the relevant python should tell you which folders are on path i.e. searched for modules.

**Comment by yogabbagabb** [comment]
I ran sudo on find at my root directory and found matplotlib here:

`./Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib
./System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/matplotlib
./System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib`

and

`python -m site` and was given the following

`sys.path = [
    '/Users/ahanagrawal',
    '/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip',
    '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5',
    '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',
    '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload',
    '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages',
]
USER_BASE: '/Users/ahanagrawal/Library/Python/3.5' (doesn't exist)
USER_SITE: '/Users/ahanagrawal/Library/Python/3.5/lib/python/site-packages' (doesn't exist)`

_____
Did you suggest I try `python -m site` because a search using find wouldn't go through the folders that `python -m site` returned?

**Comment by yogabbagabb** [comment]
Perhaps my issue is more suitable for a forum like, say SO (because it now requires attention to my system and not a bug in general)? If so, please say so! :D I shall take this issue there!

**Comment by tacaswell** [comment]
Either SO or the user mailing list may be a better venue.

Also check the encoding of the files.  If it somehow ended up as utf maybe reading it in as ascii in causing problems?
