### ISSUE TITLE
BUG: OSX backend, Figure.set_dpi() gets confused on retina display 

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6501]
On v2.x, with `ipython --pylab=osx`:

``` python
plot([1,2,3])
gcf().set_dpi(115)
```

It now displays the result with an image size based on true dpi rather than pixel-doubled dpi used originally.  Subsequent attempts to change dpi result in nothing being plotted.

**Comment by jenshnielsen** [comment]
Somewhat related if an OSX backend figure is dragged from a hidpi screen to a low dpi screen or the other way the figure is blanked (the toolbar buttons stays and are even correctly repainted in the right resolution)

**Comment by greglucas** [comment]
The macosx dpi scaling issues were sorted out in #21365 and this seems to work as expected on my local retina display now.
