### ISSUE TITLE
Return values get_ydata() after original data has changed

### ISSUE THREAD

**Issue by julietbravo** [matplotlib/matplotlib#6503]
I'm not sure if this is a bug or a feature, so I would like the hear the opinion of the Matplotlib developers. With this example:

```
x = np.arange(1)
y = np.ones(1)

pl.figure()
l1 = pl.plot(x,y)[0]
y[:] += 1
l2 = pl.plot(x,y)[0]
```

Calling `get_ydata` on both `l1` and `l2` returns the same value (2) instead of the values originally used for plotting the lines (1 and 2). Perhaps this was done to save memory (otherwise the line object would need to keep a copy of the original data? But it makes using `get_ydata` a bit dangerous... 

Matplotlib 1.5.1, Python 3.4.4, OS X, installed with Macports

**Comment by ShivamNegi** [comment]
There is an 'orig' parameter for the get_ydata function.
`get_ydata(self, orig=True)`
So, if you do `l1.get_ydata(orig=False)` you get the previous value as (1).

**Comment by dstansby** [comment]
The following example seems to work properly:

```python
import numpy as np
import matplotlib.pyplot as pl

x = np.arange(1)
y = np.ones(1)

pl.figure()
l1 = pl.plot(x,y)[0]
print(l1.get_ydata())
y[:] += 1
l2 = pl.plot(x,y)[0]
print(l2.get_ydata())
```
and prints 
```
[1.]
[2.]
```
so I'm going to close this as fixed.
