### ISSUE TITLE
custom scatter marker demo broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6507]
![image](https://cloud.githubusercontent.com/assets/199813/15663043/6ea9f7e0-26c4-11e6-9bee-f58b5f461718.png)

http://matplotlib.org/2.0.0b1/examples/pylab_examples/scatter_custom_symbol.html

vs

![image](https://cloud.githubusercontent.com/assets/199813/15663055/8a3a2ab6-26c4-11e6-81ce-163a5a90209a.png)

http://matplotlib.org/1.5.1/examples/pylab_examples/scatter_custom_symbol.html

**Comment by efiring** [comment]
It looks like the `verts` kwarg is not making it through far enough to take effect.

**Comment by efiring** [comment]
Closed by #6611.
