### ISSUE TITLE
Dependencies in installation of 2.0.0b1

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#6511]
I just did an installation of the latest beta into my conda installation (Mac OS X 10.11.5, Python 2.7.11, Anaconda 2.3.0):

    $ conda install -c conda-forge/label/rc -c conda-forge matplotlib 
    Fetching package metadata: ..........
    Solving package specifications: .........
    
    Package plan for installation in environment /Users/rosborn/anaconda/envs/py27:
    
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        freetype-2.6.3             |                0         780 KB
        functools32-3.2.3.2        |           py27_1          16 KB
        matplotlib-2.0.0b1         |      np110py27_1         6.1 MB
        ------------------------------------------------------------
                                               Total:         6.9 MB
    
    The following NEW packages will be INSTALLED:
    
        functools32: 3.2.3.2-py27_1     
        matplotlib:  2.0.0b1-np110py27_1
    
    The following packages will be UPDATED:
    
        freetype:    2.5.5-0 --> 2.6.3-0            
    
    Proceed ([y]/n)? y 
    
    Fetching packages ...
    freetype-2.6.3 100% |################################| Time: 0:00:00   1.02 MB/s
    functools32-3. 100% |################################| Time: 0:00:00 471.17 kB/s
    matplotlib-2.0 100% |################################| Time: 0:00:02   2.80 MB/s
    Extracting packages ...
    [      COMPLETE      ]|###################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|###################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|###################################################| 100%

 and had the following two issues:

1) A cycler dependency was not caught by the installation:

    pkg_resources.DistributionNotFound: The 'cycler>=0.10' distribution was not found and is required by matplotlib

This was easily fixed by updating cycler using the default Anaconda channel.

2) The version of libpng was still too low:

    from matplotlib import ft2font
    ImportError: dlopen(/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: @rpath/libpng16.16.dylib
    Referenced from: /Users/rosborn/anaconda/envs/py27/lib/libfreetype.6.dylib
    Reason: Incompatible library version: libfreetype.6.dylib requires version 38.0.0 or later, but libpng16.16.dylib provides version 34.0.0

The default Anaconda channel maxes out at libpng v1.6.17, so it is necessary to upgrade to 1.6.21 using the conda-forge channel. I'm not sure if this counts as a bug in the conda freetype installation but it will affect matplotlib users wanting to upgrade.

P.S. After fixing these, the version seems to be working well.

**Comment by tacaswell** [comment]
The first issue is addressed by https://github.com/conda-forge/matplotlib-feedstock/pull/27

I am not sure about the second, but the correct version is available from conda-forge (as that is the version that is used by conda-forge to build the binary).

**Comment by tacaswell** [comment]
@pelson Is there a way to automatically bake more library version information into the metadata, or should we just explicitly pin the libpng version?

**Comment by pelson** [comment]
@tacaswell - the problem, as @rayosborn suggests, is that the freetype being used is incorrectly representing the versions it supports. The offending line is https://github.com/conda-forge/freetype-feedstock/blob/master/recipe/meta.yaml#L27. It should be pinned as per https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies.

I opened an issue at https://github.com/conda-forge/freetype-feedstock/issues/5 to address this problem. Any contributions there would be massively valued @rayosborn.

**Comment by tacaswell** [comment]
This is fixed in the 2.0.0b2 conda package and the underlying problem is way beyond the scope of mpl.
