### ISSUE TITLE
LaTeX axis labels can no longer have custom fonts

### ISSUE THREAD

**Issue by ngoldbaum** [matplotlib/matplotlib#6514]
This happens in matplotlib 2.0b1. Here's an example that triggers this behavior:

https://gist.github.com/ngoldbaum/67cf464cc1e2763f95808759423943d9

And this is what the resulting image looks like:

![test](https://cloud.githubusercontent.com/assets/3126246/15682406/1e37df8e-2723-11e6-87ff-586b53f1ed2f.png)

Here's what the image produced by the exact same script run under matplotlib 1.5.1 looks like:

![test](https://cloud.githubusercontent.com/assets/3126246/15682434/43cf7e78-2723-11e6-8195-6ca822bd7014.png)

Note how in matplotlib 1.5.1 the y axis label is drawn using the font I specify in the script (stixgeneral). Under matplotlib 2.0b1, the font is unconditionally set to the default matplotlib font no matter what I do.

This underlying issue is currently causing some labels in yt plots to be rendered with the incorrect font under matplotlib 2.0b1.

**Comment by ngoldbaum** [comment]
Spent a little bit of time digging into matplotlib internals. It's easiest to see a difference by looking at the `render_glyph` method of the `Fonts` object, defined in mathtext.py.

Under matplotlib 1.5.1, the call to `_get_info` inside `render_glyph` returns a font object with the following filename on my setup:

`/Users/goldbaum/Documents/matplotlib/lib/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf`

While on matplotlib 2.0b1, it returns a font object with the following filename:

`/Users/goldbaum/Documents/matplotlib/lib/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Oblique.ttf`

So it looks like the real issue is that mathtext used to be rendered in a serif computer modern font by default, but now defaults to a sans-serif DejaVuSans font.

Is there a way to modify the script I added in the description to pick out the computer modern font matplotlib used to use?

**Comment by ngoldbaum** [comment]
ping @zblz @mdboom since they appear to be the ones who have worked on these code paths in mathtext.

**Comment by ngoldbaum** [comment]
More precisely, is there a way to set the font used by matplotlib for mathtext rendering using the object-oriented interface? I don't think I can do this by setting rcparams, as suggested in the docs, since this is in the context of a library depending on matplotlib rather a user script making use of matplotlib.

**Comment by Tillsten** [comment]
From the whats new:

The default math font when using the built-in math rendering engine (mathtext) has changed from "Computer Modern" (i.e. LaTeX-like) to "DejaVu Sans". To revert to the old behavior, set the rcParam mathtext.fontset to cm. This change has no effect if the TeX backend is used (i.e. text.usetex is True).

**Comment by ngoldbaum** [comment]
I'm going to close this and open another issue with a feature request about controlling mathtext fonts via the OO API.

**Comment by mdboom** [comment]
>  I don't think I can do this by setting rcparams, as suggested in the docs, since this is in the context of a library depending on matplotlib rather a user script making use of matplotlib.

Indeed there's no way other than setting an rcParam at present.  You can, however, use the rcParam context manager to change it to what you need and then automatically change it back.

**Comment by WeatherGod** [comment]
IIRC, it is possible to pass in a dictionary to the context manager rather
than a style filename... right?

On Wed, Jun 1, 2016 at 8:32 AM, Michael Droettboom <notifications@github.com

**Comment by mdboom** [comment]
@WeatherGod: Yes.
