### ISSUE TITLE
Segmentation fault with any backend (matplotlib 1.4.3 and 1.5.1) when calling pyplot.show()

### ISSUE THREAD

**Issue by LuciusV** [matplotlib/matplotlib#6531]
Dear developers,
I'm getting segmentation fault on gentoo with both matplotlib versions 1.4.3 and 1.5.1 and every backends(have tried qt,gtk,cairo) 
Matplotlib is installed from source with emerge matplotlib.

How it happens:
cat mpl-test.py 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
if __name__ == '__main__':
    plt.plot(range(0,3),range(0,3))
    plt.show()

python2.7 mpl-test.py 
Segmentation fault

python3.4 mpl-test.py 
Segmentation fault

DE is plasma-5.5.5-r1
Information from emerge --info:

emerge --info
Portage 2.2.28 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/plasma, gcc-4.9.3, glibc-2.22-r4, 4.4.6-gentoo x86_64)
=================================================================
System uname: Linux-4.4.6-gentoo-x86_64-Intel-R-_Core-TM-_i5-6300HQ_CPU_@_2.30GHz-with-gentoo-2.2
KiB Mem:     8048508 total,   5869488 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Thu, 02 Jun 2016 09:00:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.19.1::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

science
    location: /var/lib/layman/science
    masters: gentoo
    priority: 0

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -fno-stack-protector -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -fno-stack-protector -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="ru_RU.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli consolekit cracklib crypt cups cxx dbus declarative dri dts dvd dvdr emboss encode exif fam firefox flac fortran gdbm gif glamor gpm gtk iconv ipv6 jpeg kde kipi lcms ldap libnotify mad mmx mmxext mng modules mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds qml qt3support qt4 qt5 readline sdl seccomp semantic-desktop session spell sse sse2 ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb vorbis widgets wxwidgets x264 xattr xcb xcomposite xinerama xml xscreensaver xv xvid zlib" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext mpx popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON
```

**Comment by LuciusV** [comment]
https://bugs.gentoo.org/attachment.cgi?id=436254 - strace output for segmentation fault

**Comment by tacaswell** [comment]
Which backend are you using?

**Comment by LuciusV** [comment]
Tried gtk, qt, tk, cairo - with all those segfault heppened.

**Comment by tacaswell** [comment]
:disappointed: Hoping this was a known wx bug.  We have seen issues where if the gui objects get torn down in the wrong order you get segfaults (because objects get gc'd on the python side, but someplace in the c side there was still a non-refcounted reference to it).

Do you have any custom rcparams (such as `interactive: True`) set?  Can you try with `Agg`?

Does adding a `plt.close('all')` after the show help?

**Comment by LuciusV** [comment]
I'll try as you said when I'll get to that machine, I also recall that same segfault happens with plt.savefig() as well.

**Comment by LuciusV** [comment]
No custom rc parameters are set, all default.

In interactive python shell, segmentation fault disappears with matplotlilb.use('Agg'), but no window is plotted.

if I call as python mpl-test.py, segmentation fault persists.
Window appears for a moment, then instantly crashes.
plt.close('all') does not help.

**Comment by LuciusV** [comment]
One more thing - while it has segmentation fault with savefig(), it still creates 0-sized file.

**Comment by tacaswell** [comment]
Can you save a `ps` or `pdf` file?

It is sounding like something got updated under your install and you are having ABI issues

**Comment by LuciusV** [comment]
I tried to install from pip, reinstall with all dependencies, nothing of it helps.

Tried ps and pdf with no success:

In [1]: import matplotlib as mpl

In [2]: mpl.use('ps')

In [3]: import matplotlib.pyplot as plt

In [4]: plt.plot(range(10))
Out[4]: [<matplotlib.lines.Line2D at 0x7fe1fa045d68>]

In [5]: plt.savefig('test.ps')
Segmentation fault

**Comment by matthew-brett** [comment]
What do you now get for:

In [1]: import matplotlib

In [2]: print(matplotlib.__version__)

​

**Comment by LuciusV** [comment]
1.5.1

**Comment by LuciusV** [comment]
end of strace:

mmap(NULL, 1232896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9d117b1000
brk(0x2cb5000)                          = 0x2cb5000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x802c72628} ---
+++ killed by SIGSEGV +++

**Comment by matthew-brett** [comment]
@tacaswell was suggesting that you try to install the 2.0.0b1 version of matplotlib and test that.  Did you succeed in installing that?   If you had problems, can we help?

**Comment by LuciusV** [comment]
I'll try 2.0.0b1 now. Before I do, I tried debug in pycharm.
For savefig, seg fault happens in file backend.bases.py
on line 2223 in code:
```
        try:
            #result = getattr(self, method_name)(
            result = print_method(
                filename,
                dpi=dpi,
                facecolor=facecolor,
                edgecolor=edgecolor,
                orientation=orientation,
                bbox_inches_restore=_bbox_inches_restore,
                **kwargs)
```

**Comment by matthew-brett** [comment]
Ah sorry - @tacaswell didn't yet suggest 2.0.0b1, I was thinking of another thread.  But it would be good to know whether you get the same problem with 2.0.0b1

**Comment by tacaswell** [comment]
I didn't suggest it, but it _is_ a good idea!

**Comment by LuciusV** [comment]
Ok guys, I found the reason: Its linear algebra package
(which is sad because I need linear algebra support for parallelization, but it is not matplotlib problem I think)

I dumped core and checked backtrace with gdb:

```
#0  0x00002adcef2fe0e0 in dcopy_ () from /usr/lib64/libblas.so.3
#1  0x00002adcf0256caa in ?? ()
#2  0x0000000000000002 in ?? ()
#3  0x00007ffca8b4fe2c in ?? ()
#4  0x00007ffca8b4fe28 in ?? ()
#5  0x00007ffca8b4fe24 in ?? ()
#6  0x00002adcf46c60f8 in ?? ()
#7  0x0000000000000000 in ?? ()

```
recompiled numpy without lapack and segmentation fault gone :)

**Comment by tacaswell** [comment]
Great!

**Comment by matthew-brett** [comment]
Did you try OpenBLAS?  Is it packaged for Gentoo?   We currently build numpy and scipy with the latest OpenBLAS, and it seems to be very reliable.   We'd love to hear from you if you have problems, so we can work with the maintainer to fix them.

**Comment by LuciusV** [comment]
Yes, I already use Openblas, fail was with openblas-0.2.15  and lapack-reference-3.6.0-r1 installed, and numpy installed with use "lapack" on (things went okay when I re-merged numpy without "lapack"
Anyway, I'll do whatever I can for help.

**Comment by matthew-brett** [comment]
Would you mind trying an install using numpy wheels?  I recommend a virtualenv:

virtualenv test-numpy-wheels
source test-numpy-wheels/bin/activate
python -m pip install --upgrade pip
pip install numpy   # Gets a numpy wheel with OpenBLAS 0.2.18
pip install matplotlib

Does that do any better?  If so, then maybe some encouragement to the Gentoo packagers to get out an OpenBLAS 0.2.18 version as soon as possible.

**Comment by LuciusV** [comment]
I did as you suggested, numpy and matptotlib both do work (matplotlib can't use qt5 inside virtualenv, but this can't be done I think - anyway, some other backend works nice)

performance of numpy of virtualenv:

`import numpy as np 
import time   
n = 5
N = 6000 
M = 10000 
k_list = [64, 80, 96, 104, 112, 120, 128, 144, 160, 176, 192, 200, 208, 224, 240, 256, 384] 
def get_gflops(M, N, K): 
    return M*N*(2.0*K-1.0) / 1024**3 
 
#np.show_config() 
for K in k_list: 
    a = np.array(np.random.random((M, N)), dtype=np.double, order='C', copy=False) 
    b = np.array(np.random.random((N, K)), dtype=np.double, order='C', copy=False) 
    A = np.matrix(a, dtype=np.double, copy=False) 
    B = np.matrix(b, dtype=np.double, copy=False) 
    start = time.time() 
    for i in range(n):
      C = np.dot(A, B) 
    end = time.time() 
 
    tm = (end-start) / float(n)
    print ('{0:4}, {1:9.7}, {2:9.7}'.format(K, tm, get_gflops(M, N, K) / tm))
`

my numpy with openblas-0.2.15 blas, acml lapack:
`python numpy-test.py 
  64,  0.163448,  43.41857
  80, 0.1636398,  54.29497
  96, 0.1753762,  60.85751
 104, 0.1840356,   62.8521
 112, 0.1849496,  67.37562
 120, 0.1968222,  67.85396
 128, 0.1965822,  72.48486
 144, 0.2075086,  77.28535
 160, 0.2190426,  81.37922
 176, 0.2301782,  85.21073
 192, 0.2398318,  89.23668
 200, 0.2519496,  88.49334
 208,  0.249305,  93.01832
 224, 0.2622646,  95.23997
 240,  0.272288,  98.30111
 256, 0.2875874,  99.28929
 384, 0.3980018,  107.6866`

numpy-wheels in virtualenv:
`python numpy-test.py 
  64, 0.1604748,    44.223
  80, 0.1663212,  53.41964
  96, 0.1767472,  60.38544
 104, 0.1896896,  60.97869
 112, 0.1886734,  66.04585
 120, 0.1973212,  67.68237
 128, 0.1962348,  72.61319
 144,  0.208095,  77.06757
 160,  0.218035,  81.75528
 176,  0.232176,  84.47752
 192, 0.2416878,  88.55141
 200, 0.2532434,  88.04124
 208, 0.2503274,  92.63841
 224, 0.2612336,  95.61584
 240, 0.2709914,  98.77145
 256, 0.2868076,  99.55924
 384,  0.394414,  108.6662`

**Comment by matthew-brett** [comment]
That looks good - I think your figures mean that OpenBLAS / lapack in the wheel is faster than the gentoo packaged OpenBLAS / lapack.

**Comment by zhaiyuqiang** [comment]
After reinstalling matplolib, it works.
```
conda install matplotlib
```
