### ISSUE TITLE
network tests are not skipped when running tests.py with --no-network

### ISSUE THREAD

**Issue by rathann** [matplotlib/matplotlib#6539]
To help us understand and resolve your issue please check that you have provided
the information below.

- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

> 1.5.2rc2, 2.7.11/3.5.1, Fedora rawhide

- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)

> From source.

- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.

```
python2 tests.py --no-network
```
or
```
python3 tests.py --no-network
```
The following tests are failing:

- `lib/matplotlib/tests/test_image.py:549` `test_load_from_url()`
- `lib/matplotlib/tests/test_style.py:60` `test_use_url()`

**Comment by tacaswell** [comment]
attn @mdboom 

I took a pass at this and lost to nose.

**Comment by tacaswell** [comment]
ok, took a second pass and won (not sure _why_ but eh).
