### ISSUE TITLE
Why does fill_betweenx  not  have interpolate?

### ISSUE THREAD

**Issue by rmlopes** [matplotlib/matplotlib#6543]
Hi,

I am working with seismic wigglets, and the lack of interpolate on the `fill_betweenx` creates very poor filling on my vertical wigglets. Why isn't there an option to interpolate as with `fill_between`?

Tks

**Comment by tacaswell** [comment]
What do you mean by 'interpolate'?  It should have the same behavior as 'plot'.  If you want to do a higher order interpolation than linear, do that as pre-processing before passing the data into `fill_between`

**Comment by rmlopes** [comment]
The `interpolate` is a keyword argument in `fill_between`.

What I mean is that if I plot the traces horizontally and use `fill_between` the wiglets are correctly filled, that is, the entire area under a curve is filled. But if I plot the traces vertically and then use `fill_betweenx` the wiglets are missing pieces close to the crossover points (in some cases it is just a line).

I deduce from the documentation that this is because there is no interpolation and the wiiglet filling is constrained to the data points available. 

Shouldn't it be done in the same way even though we are swapping the axis?

**Comment by tacaswell** [comment]
Sorry, I should read the docs before commenting more of the time :sheep: 

That is an oversite the `fill_between` has it and `fill_betweenx` does not (although you are the first person in 5 years to notice the asymetry!).

If you look at the source of the two functions, porting the functionality should not be too hard.

The only dicey bit is we have to decide if the API on fill between will be

```python
  def fill_betweenx(self, y, x1, x2=0, where=None, interpolate=False,
                      step=None, **kwargs):
```
to match the `fill_between` API

or 

```python
  def fill_betweenx(self, y, x1, x2=0, where=None, 
                      step=None, interpolate=False, **kwargs):
```

to not break the API of `fill_betweenx`.

I think this is a case where being python3 only and having kwarg-only parameters would be helpful.

@rmlopes Want to take a crack an implementing this?

**Comment by rmlopes** [comment]
Sure, it will be my pleasure.

> I think this is a case where being python3 only and having kwarg-only parameters would be helpful.

Agreed.

I guess the best would be not to break the `fill_betweenx` API for backwards compatibility, since anyway most of the use cases I have found specify the name of the argument when calling the function. I actually thought it was a keyword argument, not positional.

What I would suggest is just to use it as a keyword argument in `fill_betweenx`. If you have old code is not a problem, and if you confuse it with the `fill_between` API and do not use the name of the arguments it will most probably result in error. I am not sure what happens if you give a boolean by mistake in the `step` argument.

**Comment by QuLogic** [comment]
Fixed by above PR.
