### ISSUE TITLE
Recommendation to install packages for various OS

### ISSUE THREAD

**Issue by AbdealiJK** [matplotlib/matplotlib#6546]
In [setup.py L216](https://github.com/matplotlib/matplotlib/blob/master/setup.py#L216) there is an error message which says which packages were not found while installing.
Would it be possible to suggest methods of installing these packages in some common Operating Systems ? Something like:

```python
# A list of apt, brew, etc packages for various OS
# Example using freetype
pkg = 'freetype'
apt_pkg = 'libfreetype6-dev'
brew_pkg  'freetype'
win_pkg_url = 'http://gnuwin32.sourceforge.net/packages/freetype.htm'

if platform.system() == 'win32':
    print('Please check {0} for instructions to install {1}'
           .format(win_pkg_url, pkg))
elif platform.system() == 'darwin':
    print('Try installing {0} with `brew install {1}`'
          .format(pkg, brew_pkg))
elif platform.system() == 'Linux':
    distname, _, __ = platform.linux_distribution()
    if distname.lower() in ('ubuntu', 'debian'):
        print('Try installing {0} with `apt-get install {1}`'
              .format(pkg, apt_pkg))
```
This would be needed only for the required packages for which local copies are not provided.

A user found the error message - https://justpaste.it/v0if which was a bit confusing as it didn't suggest what to do. It'd be nice to give more helpful messages for people just starting python:

 - Matplotlib version - 2.0.0b1
 - Python version - 2.7.6
 - Platform - Linux, Kubuntu 14.04.1
 - Installation source - Using pip

**Comment by rathann** [comment]
Could you also mention Fedora (dnf install) and RHEL/CentOS/Scientific Linux (yum install)? I can provide the exact package names if necessary.

**Comment by tacaswell** [comment]
PRs to add this documentation is welcome.

**Comment by AbdealiJK** [comment]
Hey, a review on the PR I submitted would be helpful to know how I should edit and make it better so this can get merged before next point release

**Comment by WeatherGod** [comment]
Which PR is it? I don't see it at a quick glance.

**Comment by AbdealiJK** [comment]
The PR is at https://github.com/matplotlib/matplotlib/issues/6575

**Comment by tacaswell** [comment]
@AbdealiJK Sorry we can be slow to get to reviews

**Comment by AbdealiJK** [comment]
@tacaswell No problem :) I completely understand this is opensource and volunteer time. Just wanted to give a polite reminder
