### ISSUE TITLE
Log scale tick labels are overlapping 

### ISSUE THREAD

**Issue by mxmlnkn** [matplotlib/matplotlib#6549]
- Linux hypatia-pc 4.5.0-1-amd64 #1 SMP Debian 4.5.1-1 (2016-04-14) x86_64 GNU/Linux

        lsb_release -a
            No LSB modules are available.
            Distributor ID:	Debian
            Description:	Debian GNU/Linux 8.4 (jessie)
            Release:	8.4
            Codename:	jessie

  - matplotlib 1.5.2~rc2-1
  - Python 2.7.11+
  - installed using: `sudo apt-get install -t sid python matplotlibg`

Here is an example where the problem appears:

    from matplotlib.pyplot import *
    figure( figsize=[4,3] )
    subplot( 111, xscale='log' )
    plot( [1e-20,1e5], [1e-16,10] )
    show()

For lack of time the following image wasn't reproduced with the above example, but came from another problem:
![loglabel-bugfix-reduced](https://cloud.githubusercontent.com/assets/6842824/15871750/8236cfbc-2cf6-11e6-856a-c6faf803d052.png)

The right side shows the problem and the left side is my workaround which calculates some distance for a given amount of labels I want (here I wanted 5 labels or less). So it set every exponent, but every sixth integer exponent, i.e. -16,-10,-4.

It would be cool if it was fully automatic like with linear scales.

**Comment by mxmlnkn** [comment]
This bug also happens with the linear scale:

    from matplotlib.pyplot import *
    figure( figsize=[4,3] )
    plot( [0.1310,0.1315], [0,1] )
    tight_layout()
    show()

![label-overlapping](https://cloud.githubusercontent.com/assets/6842824/15875714/af9bf69a-2d09-11e6-80e9-2bb3bd8d5c08.png)

Note that without `tight_layout` the `+1.309e1` won't be inside the canvas:
![label-overlapping-no-tight_layout](https://cloud.githubusercontent.com/assets/6842824/15875788/fc2ec686-2d09-11e6-942f-ba9bd4ba1f07.png)
I would say this is still another bug.

I would just be nice if the formatter could do something like:

    while exists i: labelpos[i] + width( text(label[i]) ) + spacing >= labelpos[i+1]:
        reduce number of labels by one

**Comment by tacaswell** [comment]
Can you try the 2.0.0b1 which implements something like that?

**Comment by anntzer** [comment]
2.0 solves the problem for linear scale, but not for log-scale (the original issue): the `LogLocator` class does not use the ticks-limiting logic present in `MaxNLocator`.  (Apparently neither do `SymmetricalLogLocator` or `LogitLocator`.)

**Comment by mxmlnkn** [comment]
@tacaswell : The only difference in 2.0b is that the default label font size is smaller (or maybe it just uses a different backend), resulting in the above linear scale example to actually work. But adding some 0s, I can still reproduce the problem even with linear scales, unlike @anntzer said.

logarithmic scale (minimal example from 1st post):
![log-scale](https://cloud.githubusercontent.com/assets/6842824/15891368/7e944816-2d74-11e6-8118-a80a0a945f58.png)
linear scale (minimal example from 2nd post):
![lin-scale-2 0](https://cloud.githubusercontent.com/assets/6842824/15891346/6640ef3a-2d74-11e6-8a6d-7681b890626e.png)
linear scale even more extreme (This may be an extreme example, but it could still be solved by reducing the number of tick labels by one):
![lin-scale-2 0-even-smaller](https://cloud.githubusercontent.com/assets/6842824/15891477/f6f9788a-2d74-11e6-8b70-af71ce1fd1e3.png)

Above done with:

    from matplotlib.pyplot import *
    figure( figsize=[4,3] )
    plot( [0.131000,0.131005], [0,1] )
    tight_layout()
    show()

    print matplotlib.__version__
        2.0.0b1

**Comment by anntzer** [comment]
Indeed, 2.0 just uses a heuristic where the aspect ratio of an xlabel is no more than 1x3 (by the way, I just realized that this would be way too pessimistic (too optimistic for ylabels) if the labels are rotated...).

As discussed in #5494, it is not so easy to handle this automatically because the tick labels are rendered after the tick positions are selected.

**Comment by tacaswell** [comment]
Linked with #7001
