### ISSUE TITLE
3D axis ticks, labels, and LaTeX

### ISSUE THREAD

**Issue by tollbooth** [matplotlib/matplotlib#6561]
LaTeX does not seem to process properly in 3D plotting ticks and labels. For example, suppose I modify this script: [http://matplotlib.org/examples/mplot3d/lines3d_demo.html](url) to the following:

import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt

mpl.rcParams['legend.fontsize'] = 10

fig = plt.figure()
ax = fig.gca(projection='3d')
theta = np.linspace(-4 \* np.pi, 4 \* np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r \* np.sin(theta)
y = r \* np.cos(theta)
ax.plot(x, y, z, label='parametric curve')
ax.legend()

xArray = np.array([-4,-2,2,4])

ax.set_xlabel('$X$', fontsize=20, rotation=150)
ax.set_ylabel('$Y$')
ax.set_zlabel(r'$\gamma$', fontsize=30, rotation=60)
ax.set_xticks(xArray)
ax.set_xticklabels(xArray, ['$-4$', '$-2$', '$2$', '$4$'], fontsize=20)  
ax.yaxis._axinfo['label']['space_factor'] = 3.0

plt.show()

This produces the following:

![3d spiral](https://cloud.githubusercontent.com/assets/7296052/15909245/6d5a39a6-2d93-11e6-83e5-4a687c48df2c.png)

Notice that the Z-axis label is properly rescaled but not rotated. Also, the X-axis ticks are not in LaTeX like I wanted them. Why is this not working correctly?
- Python 3.5 using Spyder 2.3.7 on Windows 10
- Installed via Anaconda

**Comment by anntzer** [comment]
AFAICT, the tick labels now correctly use tex, and the rotation behavior is expected and can be manually controlled with https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axis3d.Axis.html#mpl_toolkits.mplot3d.axis3d.Axis.set_rotate_label.  (Perhaps documentation could be better, but it's not obvious where to mention this.)

Thus closing this, but feel free to request a reopen if necessary.
