### ISSUE TITLE
Unexpected behavior with ttk.Notebook - graph not loaded unless tab preselected

### ISSUE THREAD

**Issue by Seymourr** [matplotlib/matplotlib#6571]
I use Python's tkinter lib with ttk as well, and I have noticed the following problem:

My app has a ttk.Notebook widget with 2 tabs, each showing a different graph with different data.
The graphs are drawn exactly as specified in https://www.youtube.com/watch?v=JQ7QP5rPvjU 

The graphs read from two different text files, which are both open for continuous reading (im doing live graphs). The text files themselves are appended with new content from different processes, running at the same time my app does.

The problem is this: When initially starting my app and only seeing one of the tabs (the one currently selected), the seen graph is updated live accordingly as the writing process begins (started manually for simplicity after the app run). However, when then switching tab in the notebook widget, the other graph is empty - despite the text file associated with it clearly being populated with data.

Furthermore, if i start the tkinter app and click through all the tabs initially before doing the writing process (to fresh, empty files) all my graphs are drawn correctly.

I suspect that my problem lies with in how either tkinter load in the graph (establish a connection) or that ttk.Notebook somehow don't preload its widget.. But I have found no evidence of either.

Im sorry to not being able to provide any specific code, but as said, I draw the graphs according to the linked video, and manage the ttk.Notebook in the simplest way possible. Furthermore, the other processes writing to the files correctly writes to the files as intended (This has been checked redundantly).

Cheers for any tip

Matplotlibversion: latest (i keep it updated)
Python: 3.5
Platform: OS

Installed by using pip

**Comment by tacaswell** [comment]
Without a minimal example there is not much concrete we can do to help. 

Maybe try the tk mailing lists?
