### ISSUE TITLE
please copy http://matplotlib.org/devdocs/users/colormaps.html to http://matplotlib.org/users

### ISSUE THREAD

**Issue by denis-bz** [matplotlib/matplotlib#6587]
A doc hiccup: could someone please copy
http://matplotlib.org/devdocs/users/colormaps.html  over to
http://matplotlib.org/users/colormaps.html ?
The latter has text only, no plots, today (15 June).
Thanks.

(+100 to whoever did these "color squiggles" -- good idea, good implementation.)

**Comment by tacaswell** [comment]
Yikes, that is a major issue with the docs!

The 1.5.0 version is also correct: http://matplotlib.org/1.5.0/users/colormaps.html I apparently screwed up when I built the 1.5.1 docs.

@kthyng is responsible for those plots.

**Comment by kthyng** [comment]
@denis-bz @tacaswell Thanks!

**Comment by tacaswell** [comment]
@denis-bz The docs have been rebuilt and uploaded.
