### ISSUE TITLE
Different line styles between PNG and PDF exports.

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#6588]
### Is the line style supposed to depend on the export backend?
_MPL 1.5.1 is from Anaconda and MPL 2.x is from Github, both on Linux (CentOS 7)_

With MPL 1.5.1, I get the same line styles between both PDF and PNG exports:
- PNG @ 100 DPI: 

![mpl_ver_1 5 1_100dpi](https://cloud.githubusercontent.com/assets/17270724/16085565/ba31196e-331c-11e6-8788-01ca2774bcce.png)
- PDF @ None DPI: [MPL_ver_1.5.1_None.pdf](https://github.com/matplotlib/matplotlib/files/316429/MPL_ver_1.5.1_None.pdf)

while with master version, they are different between PDF and PNG exports:
- PNG @ 100 DPI: 

![mpl_ver_2 0 0b1 post1628 g1aba7c3_100dpi](https://cloud.githubusercontent.com/assets/17270724/16085566/ba8419de-331c-11e6-987c-527ed2194cfb.png)
- PDF @ None DPI: [MPL_ver_2.0.0b1.post1628+g1aba7c3_None.pdf](https://github.com/matplotlib/matplotlib/files/316430/MPL_ver_2.0.0b1.post1628.g1aba7c3_None.pdf)

NB: the problem seems to be independent from the DPI value: I get similar line styles between both PNG exports with 100 DPI and 300 DPI.
- PNG @ 300 DPI: 

![mpl_ver_2 0 0b1 post1628 g1aba7c3_300](https://cloud.githubusercontent.com/assets/17270724/16085887/e244d8b8-331d-11e6-89b1-d6af79a79cbe.png)

The example snippet is
```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

test_case = matplotlib.__version__

fig, ax = plt.subplots(num=test_case, figsize=(4.8, 3.2))
ax.set_title("MPL version: {0:s}".format(test_case))

xx = np.array([0.0, 1.0])

ax.plot(xx, 1 * xx, ls='dashed', label='default lw')
ax.plot(xx, 2 * xx, ls='dashed', lw=2, label='lw=2')
ax.plot(xx, 3 * xx, ls='dashed', lw=3, label='lw=3')

ax.legend(loc='upper left')

plt.show()

for ext, dpi in (('pdf', None), ('png', 100), ('png', 300)):
    fig.savefig("MPL_ver_{v:s}_{d}.{e:s}".format(v=test_case, d=dpi, e=ext),
                dpi=dpi)
```

My guess would that I may be somehow related to the new behavior introduced in #5926, _but I didn't have time to have a look yet_.

**Comment by tacaswell** [comment]
That is also my guess, it looks like the scaling is not being passed through to the pdf backend correctly.

attn @jkseppan

**Comment by afvincent** [comment]
I tested the same example with exports in EPS and SVG, and they look fine (i.e. like the PNG ones) even with MPL from the 2.x master branch. So it seems that the problem is indeed with the PDF backend.

**Comment by jkseppan** [comment]
It seems #5926 changed the interface of GraphicsContext toward subclasses in a way that's a bit unfortunate for how the pdf backend used it

**Comment by efiring** [comment]
This problem also shows up in interpolation_none_vs_nearest.py in the gallery, with #6584 applied (and presumably without it). The automatic selection of the number of ticks works for the agg output but not for the pdf.

**Comment by efiring** [comment]
I will make a separate issue for the tick number problem.
