### ISSUE TITLE
Feature request: filled error bar

### ISSUE THREAD

**Issue by wiso** [matplotlib/matplotlib#6593]
It would be nice to have an easy way to make plot like this: http://stackoverflow.com/questions/37852462/filled-errorbars-in-matplotlib-rectangles/37852631?noredirect=1#comment63165456_37852631 with the `errorbar` function.

**Comment by tacaswell** [comment]
At a minimum, I think the answer to that question would be a good example in the documentation.

**Comment by anntzer** [comment]
Closed by #6596.
