### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by Energya** [matplotlib/matplotlib#6594]
At http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.errorbar, just above the table for the kwargs, there is a typo in:

> where _mfc, mec, ms_ and _mew_ are aliases for the longer property names, _markerfacecolor_, _markeredgecolor_, _markersize_ and **_markeredgewith_**.

_markeredgewith_ should be _markeredgewi**d**th_

**Comment by tacaswell** [comment]
@Energya Thank you for reporting this.  The source of the error is most likely a typo in `axes/_axes.py` in the docstring of `errorbar`.   Would you be willing to open a PR to fix it (you can probably do it through the gh web interface)?

**Comment by Energya** [comment]
@tacaswell Didn't realise that was an option, so thanks for the suggestion. The file was exactly the one you said.

**Comment by tacaswell** [comment]
Closed by #6600 for house keeping
