### ISSUE TITLE
Version string wrong for `pip wheel` but not `setup.py bdist_wheel`

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#6605]
I ran into a strange error building matplotlib 2.0.0b1 wheels with `pip wheel -w /path/to/wheelhouse .`.  

With that incantation, the wheels I got have filenames like `matplotlib-0+unknown-cp27-cp27mu-manylinux1_x86_64.whl` - see: https://travis-ci.org/matthew-brett/matplotlib-wheels/jobs/138518911#L325 .

But - with `python setup.py bdist_wheel` on the same source, I get the wheel name I was expecting: `matplotlib-2.0.0b1-cp27-cp27mu-manylinux1_x86_64.whl` - see: https://travis-ci.org/matthew-brett/matplotlib-wheels/jobs/138543116#L7630.

I tried updating the mpl copy of versioneer to the latest (0.16) but that did not fix the problem.  The `get_version` command of versioneer gives the expected answer (after the commit to update to 0.16):

```
$ python -c 'import versioneer; print(versioneer.get_versions())'
{'error': None, 'version': 'v2.0.0b1+1.g7d6da18', 'dirty': False, 'full-revisionid': '7d6da181cb55d18ea3985dc21a9589159f5461b4'}
```

**Comment by matthew-brett** [comment]
It may be that this happens only when matplotlib is a submodule, as it in in the matplotlib-wheels repo that I have working on : https://github.com/matthew-brett/matplotlib-wheels . At least I can't replicate the problem in a similar docker image just now, with the matplotlib repo not in a submodule.

**Comment by WeatherGod** [comment]
this is probably due to versioneer. I don't think we ever consider the
submodule situation.

**Comment by tacaswell** [comment]
That might be something worth raising on the versioneer issue tracker.  I bet it is looking at the top level repo for tags and such.

**Comment by matthew-brett** [comment]
I just added a versioneer issue at https://github.com/warner/python-versioneer/issues/121 - but the description in https://github.com/warner/python-versioneer/issues/38 and related discussion implies this is a problem with `pip` and it might be hard to fix.

**Comment by anntzer** [comment]
I'm closing this as essentially unfixable from our side -- both versioneer (as mentioned above) and the more modern setuptools_scm (https://github.com/pypa/setuptools_scm/issues/96) are running into limitations of pip (https://github.com/pypa/pip/issues/3908).
