### ISSUE TITLE
Icons for Tk are not antialiased.

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6610]
As pointed out here https://github.com/matplotlib/matplotlib/pull/5626#issuecomment-226927789 the new icons are particularly ugly with the Tkagg backend.  The reason is that Tk is using the ppm versions, which are not antialiased.  One solution would be to use, e.g., 
```
convert -antialias -geometry 24x24 back.svg back.gif
```
etc. to generate antialiased gif files to replace the ppm files, and then change one line in backend_tkagg.py so that it will use these files.

In addition, the old and now unused xpm files can be deleted.

**Comment by tacaswell** [comment]
Closed by #6627

**Comment by lianghongzhuo** [comment]
Maybe also change the icon `matplotlib.ppm` to a high-res picture like `".png"`?
Tested in my system, working.
