### ISSUE TITLE
Assertion Failure + Exit code [400] on macOS Sierra, unusable

### ISSUE THREAD

**Issue by ElderFain** [matplotlib/matplotlib#6613]
To help us understand and resolve your issue please check that you have provided
the information below.
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
  ToT, 2.6, macOS Sierra 16A201w
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
  pip install matplotlib
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
    that demonstrates the issue i.e a small piece of code which reproduces the issue
    and can be run with out any other (or as few as possible) external dependencies.
1. Run this script (https://github.com/matplotlib/matplotlib/blob/master/examples/subplots_axes_and_figures/subplot_demo.py )
2. Assertion failure in -[Window _validateFirstResponder:]
- [x] If this is a regression (Used to work in an earlier version of Matplotlib), please 
    note where it used to work.
  Previous shipping version of macOS, 10.11.5

I believe these two lines should be reversed

https://github.com/matplotlib/matplotlib/blob/5d0ca1d1d55fe016ce87cea1e7d3647a65b9bdad/src/_macosx.m#L745-L746

**Comment by tacaswell** [comment]
Can you reproduce this with 2.7+?

Did mac change something that broke this?

Can you reproduce this with the 2.0.0b1 release?

**Comment by matthew-brett** [comment]
Are you really running Python 2.6?  How did you install it?

**Comment by QuLogic** [comment]
Matplotlib no longer supports Python 2.6.
