### ISSUE TITLE
Keyboard shortcuts for toggling minor ticks grid and opening figureoptions window

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6616]
I'd like to add two keyboard shortcuts: 1) "toggle the minor ticks grid" and 2) "open the figureoptions window".  The first one should probably be mapped to "G" ("g" toggles the major ticks grid), but I don't have a good idea as to what to pick for the second one.
Thoughts?

**Comment by efiring** [comment]
What is the rationale for adding a shortcut for opening the figure options window?  One can't do anything with that window without using the mouse or trackpad, so to me it makes sense to open it with a click.  I think the shortcut would just be code and cognitive clutter.

**Comment by anntzer** [comment]
There's already a bunch of keyboard navigation shortcuts which are just as accessible from the mouse (home, back, forward, zoom, pan); I personally find them rather useful.

**Comment by efiring** [comment]
I'm not saying all shortcuts are useless; but among those you listed, zoom and pan seem marginal because they don't reduce jumping between keyboard and mouse.  We can agree to disagree; I won't oppose your PR when it comes.

**Comment by fariza** [comment]
closing as the change was merged
