### ISSUE TITLE
Change in the result of test_markevery_linear_scales_zoomed

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6621]
The image plotted in classic style by `test_axes.test_markevery_linear_scales_zoomed` changed at 8356fc2.  Self-contained example:
```
import matplotlib, matplotlib.pyplot as plt, numpy as np


def test_markevery_linear_scales_zoomed():
    cases = [None,
             8,
             (30, 8),
             [16, 24, 30], [0, -1],
             slice(100, 200, 3),
             0.1, 0.3, 1.5,
             (0.0, 0.1), (0.45, 0.1)]

    cols = 3
    gs = matplotlib.gridspec.GridSpec(len(cases) // cols + 1, cols)

    delta = 0.11
    x = np.linspace(0, 10 - 2 * delta, 200) + delta
    y = np.sin(x) + 1.0 + delta

    for i, case in enumerate(cases):
        row = (i // cols)
        col = i % cols
        plt.subplot(gs[row, col])
        plt.title('markevery=%s' % str(case))
        plt.plot(x, y, 'o', ls='-', ms=4,  markevery=case)
        plt.xlim((6, 6.7))
        plt.ylim((1.1, 1.7))


matplotlib.style.use("classic")
test_markevery_linear_scales_zoomed()
plt.show()
```

As of 8356fc2:
![bad](https://cloud.githubusercontent.com/assets/1322974/16221571/64286ae2-3748-11e6-83a0-0814d86a367c.png)
As of its only parent, 077c72e:
![good](https://cloud.githubusercontent.com/assets/1322974/16221579/73b93464-3748-11e6-9837-a2d32d665efa.png)

Not sure why this was not caught by Travis.
numpy 1.11.0, Arch Linux.

**Comment by QuLogic** [comment]
It was changed by the new icons? Is that the right commit?

**Comment by anntzer** [comment]
That's what git bisect tells me.  I agree that seems weird...

**Comment by WeatherGod** [comment]
probably a red herring due to merge conflicts. I wonder if the fixes to the
margin-handling caused something. I am not exactly sure how markevery
works, but if the data limits got changed, then maybe this could impact
things?

**Comment by tacaswell** [comment]
I can not reproduce this and get

![markevery_linear_scales_zoomed](https://cloud.githubusercontent.com/assets/199813/16288581/4e8751d4-38bb-11e6-8066-b39e81850f86.png)

output by the tests.  

and 
![so](https://cloud.githubusercontent.com/assets/199813/16288610/a1f5038e-38bb-11e6-9650-7ceb93bd91bc.png)


My guess is that there is some strange DPI related issues going on (as if you resize the live figure it the markers change.

```python
In [5]: matplotlib.__version__
Out[5]: '2.0.0b1.post10+g8356fc2'

In [6]: import numpy

In [7]: numpy.__version__
Out[7]: '1.10.4'

```

**Comment by anntzer** [comment]
I can still see the issue, and also observe that the markers changes when the figure is resized.
Should this just be reopened as a general bug regarding `markevery`?

**Comment by tacaswell** [comment]
In the float cases the markers are on the closest markers to some fraction of the visible line.  In the case of floats, the location is determined in screen space (http://matplotlib.org/2.0.0b2/api/lines_api.html#matplotlib.lines.Line2D.set_markevery) so I think this is actually the correct behavior.
