### ISSUE TITLE
RectangleSelector disappears after resizing

### ISSUE THREAD

**Issue by jrfiedler** [matplotlib/matplotlib#6623]
I am trying to run the RectangleSelector example [here](http://matplotlib.org/examples/widgets/rectangle_selector.html). I am using a Mac, so I added the lines
```python
import matplotlib
matplotlib.use('TkAgg')
```
immediately after the module docstring.

Everything works fine, except when I try to resize the rectangle using the mid-edge control points. The rectangle disappears if my cursor is above the control point when I release. If I move my cursor perpendicular to the control direction, so that my cursor is away from the control point when I release, the rectangle remains.

OSX
Anaconda Python 2.7
Matplotlib 1.5.1

**Comment by tacaswell** [comment]
attn @blink1073

**Comment by blink1073** [comment]
Can confirm, should be able to fix it this weekend.
