### ISSUE TITLE
Error in example http://matplotlib.org/examples/misc/multiprocess.html

### ISSUE THREAD

**Issue by Thomas00010111** [matplotlib/matplotlib#6626]
Do not know if this is the right place because it is not a bug in the library but in the examples.
Tried to run the example  http://matplotlib.org/examples/misc/multiprocess.html and I think it would be good to make the following changes:

remove dependencies to gobject
# matplotlib.use('GtkAgg')
# import gobject

return return call_back()
instead of return call_back

use different timer
# self.gid = gobject.timeout_add(1000, self.poll_draw())

timer = self.fig.canvas.new_timer(interval=1000)
timer.add_callback(self.poll_draw)
timer.start()

Cheers,
Thomas

**Comment by jenshnielsen** [comment]
That sounds sensible. Are you willing to put your changes into a pull request that we can test and review?

**Comment by Thomas00010111** [comment]
Ok. Created pull request

**Comment by anntzer** [comment]
Closed by #9900 (and a few remaining bits in #10168).
