### ISSUE TITLE
Colorbar major ticks are reset when another colorbar is made from same image

### ISSUE THREAD

**Issue by EdwinChan** [matplotlib/matplotlib#6640]
I am using
- matplotlib 1.5.1 installed with pip for Python 3.5.1+ on Ubuntu; and
- matplotlib 2.0.0b1+1708.g5de9c44 built from source for Python 3.5.1 on Scientific Linux 5.8.

Consider the example

``` python
import matplotlib
from matplotlib import pyplot

pyplot.pcolormesh([[0], [1]])
for i in range(3):
  pyplot.colorbar()
for i in range(1, 4):
  pyplot.gcf().axes[i].yaxis.set_ticks([0.4, 0.5, 0.6])
  pyplot.gcf().axes[i].yaxis.set_ticklabels('abc')
pyplot.colorbar()
pyplot.annotate(matplotlib.__version__, (0, 0), (0.1, 1.9), 'data', 'data',
  ha='left', va='top')
pyplot.savefig('colorbar.png')
```

Here I draw an image with `pcolormesh()`, use the same image to construct multiple colorbars, and then manually set the major ticks and major tick labels on each colorbar. Now when add another colorbar using the same image, the major ticks and major tick labels on the last-drawn colorbar are unexpectedly reset.

Running the example above gives us
![colorbar](https://cloud.githubusercontent.com/assets/906137/16350258/c5462ce8-3a2b-11e6-87fc-ae417fc30e2c.png)
![colorbar](https://cloud.githubusercontent.com/assets/906137/16350280/e6fc4a52-3a2b-11e6-818f-b17e98e297e8.png)
Note that the colorbars are drawn from the right to the left.

**Comment by jklymak** [comment]
I think we can relatively aggressively close things like this.  We can always re-open if there is still bad behaviour...
