### ISSUE TITLE
Incorrect margins in log scale

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6643]
As of 2.0b1 and master, `semilogy([.2, 2])` gives
![semilogy](https://cloud.githubusercontent.com/assets/1322974/16359389/ab2c3df4-3ae7-11e6-97f1-f0726cb71fad.png)
i.e. the bottom margin is too small.

Actually, `handle_single_margin` (in `_AxesBase`) does the right thing (expand the limits after transforming to plot coordinates), but then passes the limits to `LogLocator.view_limits`, which undoes all the good work while executing

```
        if vmin <= minpos:
            vmin = minpos
```

(this check was introduced by 426eabc1, let's see whether it's still needed...)

**Comment by anntzer** [comment]
... interestingly, this only occurs if there's no explicit call to `margins` either before or after the plotting.

**Comment by NelleV** [comment]
Closed by #7410
