### ISSUE TITLE
Malware found on matplotlib components

### ISSUE THREAD

**Issue by MartinFSSr** [matplotlib/matplotlib#6655]
On Windows 10, did pip install matplotlib (see below). 
Norton 360 popped up with warning:  "_umath_linalg.pyd contained threat" identified as "Suspicious.Cloud.7.F"
Same warning for "multiarray_tests.pyd"
Norton 360 quarantined both.

My install log--

C:\py>pip install matplotlib
Collecting matplotlib
  Downloading matplotlib-1.5.1-cp27-none-win32.whl (6.0MB)
    100% |################################| 6.0MB 176kB/s
Collecting numpy>=1.6 (from matplotlib)
  Downloading numpy-1.11.1-cp27-none-win32.whl (6.5MB)
    100% |################################| 6.5MB 161kB/s
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in c:\python27\lib\site-packages (from matplotlib)
Collecting pytz (from matplotlib)
  Downloading pytz-2016.4-py2.py3-none-any.whl (480kB)
    100% |################################| 481kB 1.5MB/s
Collecting cycler (from matplotlib)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,>=1.5.6 (from matplotlib)
  Downloading pyparsing-2.1.5-py2.py3-none-any.whl (42kB)
    100% |################################| 51kB 3.2MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in c:\python27\lib\site-packages (from python-dateutil->matplotlib)
Installing collected packages: numpy, pytz, cycler, pyparsing, matplotlib
  Found existing installation: numpy 1.5.1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.5.1:
      Successfully uninstalled numpy-1.5.1
Successfully installed cycler-0.10.0 matplotlib-1.5.1 numpy-1.11.1 pyparsing-2.1.5 pytz-2016.4

**Comment by QuLogic** [comment]
Both of those files are part of NumPy, not matplotlib.

I downloaded [matplotlib from PyPI](https://pypi.python.org/packages/be/38/3ffb65a3f73f8526499a75cde188dc19ac4a7df8ccf2730d0fd926571b5b/matplotlib-1.5.1-cp27-none-win32.whl#md5=005ca755c60041c32b605b8c30da1277) and [NumPy from PyPI](https://pypi.python.org/packages/cd/19/d5b1a2b2daff3fb44d67e230f1790b45b46cb1b3b8e4dcc825ce9228a209/numpy-1.11.1-cp27-none-win32.whl#md5=8d519465e0f7549e88b4b67af37f32d5) and ran them through VirusTotal ([matplotlib](https://www.virustotal.com/en/file/a2dc1497eeb495bf7741f63a1da19e1a1da73a6ff8e62acc6dd2d74b970adddd/analysis/1467083388/) and [NumPy](https://www.virustotal.com/en/file/96d6b2bcaf2b729f7102c58a3fb4f4817cf26633dcaf397c68c723b1275b8473/analysis/1467083962/)). I also extracted the two named files and ran [_umath_linalg.pyd](https://www.virustotal.com/en/file/bb7fda07804fd487d53389a82eb3bc00ea80d9b0ee6f40f2745bce1cd1a8c563/analysis/1467084033/) and [multiarray_tests.pyd](https://www.virustotal.com/en/file/fd58edbd5776640ba534673ff0fdb95edb0b3d60438fd0bb57cb084e0054e393/analysis/1467084018/) and only Symantec flags this as suspicious.

You should report a bug to them; I doubt there's really a problem in the file, but it's not a matplotlib issue in any case.

**Comment by tacaswell** [comment]
This seems to be a common false-positive

**Comment by tacaswell** [comment]
The correct place to report the bug is with Norton, not numpy.

**Comment by MartinFSSr** [comment]
Norton got the report automatically. If this is not of interest, please excuse the ring.

**Comment by matthew-brett** [comment]
The numpy wheels get built on Appveyor, so I doubt there's a virus in them - but it would be good to have some reassurance that it's a false positive.
