### ISSUE TITLE
literature reference for 'viridis' colormap

### ISSUE THREAD

**Issue by jkokorian** [matplotlib/matplotlib#6658]
I'm currently writing a scientific paper in which I the viridis colormap and I would like grab the opportunity to educate the readers about the importance of perceptually uniform colormaps. Is there a scientific paper about viridis that I can cite? Or should I just cite matplotlib?

**Comment by jenshnielsen** [comment]
@njsmith did you publish any thing on the Matplotlib colormaps or have any other recommendation?

**Comment by tacaswell** [comment]
You might cite the talk from scipy last year?

**Comment by jkokorian** [comment]
That's probably the best idea. Too bad there is no corresponding proceedings article.

**Comment by dstansby** [comment]
Going to close this since it's not really a bug; thanks for asking though @jkokorian !

**Comment by swharden** [comment]
I was googling the same thing and this is what I found

I don't think viridis has a paper but I wish it did. Consider pointing to Berkeley Institute for Data Science colormaps GitHub page: https://bids.github.io/colormap

cividis, a derivative of viridis optimized for colorblindness, has a citation: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239

**Comment by dstansby** [comment]
Thanks for posting the info - do you think there's anywhere in particular it would be helpful to put this in the Matplotlib docs?

**Comment by swharden** [comment]
> Thanks for posting the info - do you think there's anywhere in particular it would be helpful to put this in the Matplotlib docs?

Good question! Unfortunately I think the core problem is that Viridis, while being fantastic, doesn't have a peer-reviewed scientific publication associated with it, making it difficult to cite in scientific journals that prefer citations to published peer-reviewed articles over unreviewed URLs. This isn't a shortcoming of the matplotlib documentation, and I edited my original comment to more clearly reflect this. Information below may be helpful for other people who search for this same topic:

Cividis (a derivative of viridis by an unrelated group) does have a publication associated with it, so I suspect many people who want to cite a publication to justify their choice of colormap will point to their paper instead.

* Viridis was introduced in https://matplotlib.org/stable/users/dflt_style_changes.html#colormap which links to https://bids.github.io/colormap which is the most appropriate reference I can find for what should be cited when using viridis.

* Cividis was introduced here https://matplotlib.org/stable/users/prev_whats_new/whats_new_2.2.html#cividis-colormap and lists a publication, making it much easier to cite [Nuñez et al., 2018](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239) ([PMID 30067751](https://pubmed.ncbi.nlm.nih.gov/30067751/))
