### ISSUE TITLE
cell focus/cursor issue when plotting to nbagg

### ISSUE THREAD

**Issue by croth1** [matplotlib/matplotlib#6660]
To help us understand and resolve your issue please check that you have provided
the information below.

- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
- [x] If this is an image generation bug attach a screenshot demonstrating the issue.
- [x] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.

---

Issue with matplotlib-1.5.1, anaconda on OS X.

This issue is related to https://github.com/matplotlib/matplotlib/issues/4758/. I am trying to understand how cell focus works after having plotted to the nbagg backend.

Here is a simple example notebook: https://gist.github.com/croth1/ebfd2171559e8fd1799b600f3a72965a

shift+enter in the first cell executes as expected and moves the cell cursor to cell 2. 
shift+enter in the second cell plots, grabs the focus of cell 2 and moves the cell cursor to cell 3.
another shift+enter releases the cell focus as described in https://github.com/matplotlib/matplotlib/issues/4758/, but also moves the cell cursor to cell 4.
finally shit+enter executes the empty cell 4.

Somehow navigating through the notebook just by keyboard jumps over the plot in cell 3. Any idea's why that is?

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/pull/6053 and https://github.com/jupyter/notebook/issues/949

This is fixed on master by properly using the ipython widget framework.

**Comment by tacaswell** [comment]
closed by #6752
