### ISSUE TITLE
“Bachelor's degrees…” picture in the gallery is cropped

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#6668]
The showcase picture “[bachelors_degrees_by_gender](http://matplotlib.org/examples/showcase/bachelors_degrees_by_gender.html)” in the gallery is cropped on the right side : the text labels are cut. It is the case in the 3 exports (PNG, HR PNG and PDF).

I ran the code of the example locally and the output PNG picture in not cropped as in the web gallery : might it be related to the website rather than MPL?

- [x] _Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)_
v1.5.1 and v2.0.0b1.post1628+g1aba7c3, both on Linux (CentOs 7) with Python 2.7.

- [x] _How did you install Matplotlib and Python (pip, anaconda, from source ...)_
anaconda for v1.5.1 and github for v2.x.

**NB**: with v2.x, even with `plt.style.use('default')` or `plt.style.use('classic')`, the x-ticklabels are still formatted with an offset: [-30, -20, -10, 0, 10] + 2e3 instead of [1970, 1980, 1990, 2000, 2010]…

**Comment by afvincent** [comment]
A `diff` between between the source code in the current gallery and the “devdocs” one returns:
```diff
29a30
> fig.subplots_adjust(left=.06, right=.75, bottom=.02, top=.94)
32,33c33,35
< plt.xlim(1968.5, 2011.1)
< plt.ylim(-0.25, 90)
---
> ax.set_xlim(1968.5, 2011.1)
> ax.set_ylim(-0.25, 90)
> ax.get_xaxis().get_major_formatter().set_useOffset(False)
94,95c96,97
< plt.title('Percentage of Bachelor\'s degrees conferred to women in '
<           'the U.S.A. by major (1970-2011)\n', fontsize=18, ha='center')
---
> fig.suptitle('Percentage of Bachelor\'s degrees conferred to women in '
>              'the U.S.A. by major (1970-2011)\n', fontsize=18, ha='center')
100c102
< plt.savefig('percent-bachelors-degrees-women-usa.png', bbox_inches='tight')
---
> # plt.savefig('percent-bachelors-degrees-women-usa.png', bbox_inches='tight')
```
The x-axis formatter in the new version has been changed to not use an offset text.

Besides the new line `fig.subplots_adjust(left=.06, right=.75, bottom=.02, top=.94)` seems to prevent the devdocs version from being cropped. Indeed, the code in the current gallery produces (with a v2.x MPL):
![current_gallery](https://cloud.githubusercontent.com/assets/17270724/16482716/642a2d62-3eb1-11e6-82c4-49874dc66a2d.png)
⇒ the export (on the right) isn't cropped but the picture in the interactive window (on the left) is (is it not a bit weird btw?). 

While with the code in the devdocs gallery, with the new `fig.subplot…` line, produces:
![devdocs_gallery](https://cloud.githubusercontent.com/assets/17270724/16482817/e9f291dc-3eb1-11e6-9f55-5f8284bcfc89.png)
where everything seems to be fine, both in the interactive window and the PNG export. 

I simply hadn't check in the example source code master repo but apparently @tacaswell already noticed the cropping issue and solve it with f649739.

As the picture in the “devdocs” gallery is OK and should replace in the end the one from the current gallery, I guess I should close this issue, shouldn't I?

**Comment by tacaswell** [comment]
The cropping issue is due to the use of `bbox_inches='tight'` which effectively 'shirk wraps' the figure.  I suspect the intention of that feature was to shrink the output by removing whitespace, but it will also increase the size of the figure.

I am a bit concerned that on 2.x the tick labels are still offset.

**Comment by WeatherGod** [comment]
The intention of `bbox_inches='tight'` is to automatically determine the
bounding box that will tightly encompass all of the visible artists by
cropping or growing the figure.

**Comment by tacaswell** [comment]
Is now rendering correctly.

http://matplotlib.org/2.0.0b2/examples/showcase/bachelors_degrees_by_gender.html

![image](https://cloud.githubusercontent.com/assets/199813/16897287/2d7a407c-4b72-11e6-9dec-5e7db121e0fc.png)
