### ISSUE TITLE
hexbin lacks a weights argument

### ISSUE THREAD

**Issue by samtygier** [matplotlib/matplotlib#667]
The hist function has an optional weights argument. It would be useful if this was replicated in the hexbin function.

usecase:
I have data for energy deposition events (x,y,z,e). I can do 1d plots of energy deposition with hist, and would like to do 2d plots with hexbin.

**Comment by trianta2** [comment]
This is an old issue, but for those searching around for doing some special reducing per hex bin, I found that I can pass a multi-dimensional C array with extra information that my custom reducer function can then use.
