### ISSUE TITLE
plt.text object updating incorrectly with blit=False

### ISSUE THREAD

**Issue by snelltheta** [matplotlib/matplotlib#6670]
I have a FuncAnimation that is using a plt.text object to display the i-th column of my time_data array.
It looks great when blit=true, but when I save the file as a movie or make blit=false, the text overwrites itself. Since my goal is making a movie, I wish there was a way to make blit=true for the save function.

# blit=True
![blit=True](https://cloud.githubusercontent.com/assets/12014328/16504333/551f2a5a-3ecc-11e6-88b2-1ced2b124762.png)

# blit=False
![blit=False, and also a movie](https://cloud.githubusercontent.com/assets/12014328/16504353/64bf28a2-3ecc-11e6-977f-34a1255b1e0e.png)

Basically, the code is this
```
#raw_data is a 2-D array where the 0th column is the data to display
def init():
    line.set_data([], [])
    return line,
def animate(i):
    x = np.linspace(lower_bound,upper_bound,upper_bound-lower_bound)
    y = raw_data[i,lower_bound:upper_bound]
    line.set_data(x, y)
    time_stamp=plt.text(0.5,0.1,time_data[i],verticalalignment='center',
						horizontalalignment='left',
						transform=ax.transAxes,fontsize=15)
    return time_stamp, line,
    anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=200, interval=110, blit=True)

    anim.save('basic_animation.mp4', fps=30, extra_args=['-vcodec', 'libx264'])
```

MPL version 1.5.2rc2
Installed from Debian apt repository

**Comment by efiring** [comment]
I think you need to treat the text element the same way that you treat the line: initialize and return it in your `init`, and then call `time_stamp.set_text(time_data[i])` in your `animate`.

**Comment by dopplershift** [comment]
I agree with @efiring 's assessment--the blit is masking the fact that `text` isn't being included in the animation. Instead what's happening is a new `Text` instance is being created for every frame.

**Comment by snelltheta** [comment]
That was it!

**Comment by guaracheitor** [comment]
Hi snelltheta, I think that I have the same problem, but I can't to figure out the solution. Can yo show me the final code? Thanks.

**Comment by guaracheitor** [comment]
Finally I made it work! :)  I think that this example is perfect to understand this problem -->  https://matplotlib.org/examples/animation/double_pendulum_animated.html
Tnx
