### ISSUE TITLE
Minor typo in the docstring of `IdentityTransform`?

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#6680]
In `transforms.py`, I'm wondering if there wouldn't be a minor typo in this docstring:
```python
class IdentityTransform(Affine2DBase):
    """
    A special class that does on thing, the identity transform, in a
    fast way.
    """
```
Shouldn't it be something like  `… that does on*e* thing,…` or `… that does nothing,…`?

**Comment by tacaswell** [comment]
I think it should be `'s/on/one/'`.

**Comment by afvincent** [comment]
Naive question: how do we know which milestone to target? 

Besides I opened the PR #6681 to fix the typo. As Travis & Co are green, I guess the next step is merging it, or is it expected to wait for someone else to review it? It's a one-character change in a docstring but I prefer asking.

**Comment by jenshnielsen** [comment]
@afvincent I merged #6681 now and backported it to the 2.x branch normally we try to avoid self merges but in this case I think it would be ok as the change is really small and @tacaswell has suggested the same change here

**Comment by jenshnielsen** [comment]
There is no general rule for the mile stoning but as this is a very low risk change that fixes a clear typo it should clearly go in the bugfix release. It could have gone into 1.5.2 but I think @tacaswell is in the progress of tagging that now so I only backported it to 2.x

**Comment by tacaswell** [comment]
Just pushed the 1.5.2 tag :smile: .

**Comment by afvincent** [comment]
@jenshnielsen Thanks for the explanations, it was more or less what I had understood. (BTW backporting the fix "only" to 2.x is perfectly fine to me.)
