### ISSUE TITLE
rcParam missing tick side parameters 

### ISSUE THREAD

**Issue by radlinsky** [matplotlib/matplotlib#6691]
I'd like to use rcParams to adjust which axes the minor and major ticks appear for plots.

Currently, it is possible to adjust the spines like so:
`pyplot.rcParams['axes.spines.*'] = Boolean`

There should be an equivalent series of settings for major and minor ticks:
`pyplot.rcParams['axes.xticks.major.*] = Boolean`
`pyplot.rcParams['axes.xticks.minor.*'] = Boolean`
`pyplot.rcParams['axes.yticks.major.*'] = Boolean`
`pyplot.rcParams['axes.yticks.minor.*'] = Boolean`

*=bottom, top, left, or right

**Comment by bcongdon** [comment]
We already have `xtick.*` and `ytick.*`, so I'm going to work under the assumption that we want `xtick.minor.*`, `xtick.major.*`, etc instead of having these fall under `axes.*`

**Comment by bcongdon** [comment]
This issue can probably be closed.
