### ISSUE TITLE
The test suite spends 20% of it's time in `gc.collect()`

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6705]
```
Thu Jul 07 14:33:31 2016    matplotlib_cProfile_fulltest.pstat

         192634679 function calls (182051956 primitive calls) in 345.231 seconds

   Ordered by: internal time
   List reduced from 9374 to 3 due to restriction <3>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     2986   75.105    0.025   75.107    0.025 {gc.collect}
     1250   19.139    0.015   19.139    0.015 {matplotlib._png.write_png}
     2257    9.801    0.004    9.801    0.004 {matplotlib._png.read_png_int}
```

Mostly this is due to [this call](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/testing/decorators.py#L75)

Python is very memory effective because of reference counting (object is freed when refcount drops to zero even with `gc.disable`) and `gc.collect` only forces him to run cyclic garbage collector immediately. If it is not acceptable to to remove this call, can we have option to tuning this?

**Comment by tacaswell** [comment]
:+1: on removing that line.

That line went in in 42fa2b6788af822874e9add6458e479fa707d27e where @mdboom notes it makes debugging memory usage easier.  However, I am willing to trade 20% on the tests for inflicting pain on the dev who does memory debugging :smiling_imp: .

**Comment by Kojoley** [comment]
We can add turnable plugin for this case.
```python
    class EnforcedGC(Plugin):
        def afterTest(self, test):
            gc.collect()
```
