### ISSUE TITLE
KnownFailure becomes an error with `--processes=1` flag

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6708]
If I supply number of processes to `tests.py` every `KnownFailure` become an error (with `--processes=0` all is ok)

Here is the log [tests.txt](https://github.com/matplotlib/matplotlib/files/354458/tests.txt)

```
>python -c "import platform; print(platform.platform())"
Windows-7-6.1.7601-SP2

>python -c "import sys; print(sys.version)"
2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]

>pip freeze | grep nose
nose==1.3.7
```

**Comment by Kojoley** [comment]
It seems to be a bug in the `nose`.
[This line](https://github.com/matplotlib/matplotlib/blob/master/tests.py#L34) does not help, every spawned child has the default `multiprocess._instantiate_plugins = None`

**Comment by jenshnielsen** [comment]
Which version of nose are you using. This seems to be working correctly on travis. See https://github.com/matplotlib/matplotlib/blob/master/.travis.yml

what does `matplotlib._get_extra_test_plugins()` return?

**Comment by Kojoley** [comment]
Travis uses `--processes=0` and I am talking about non-zero value. Nose version is 1.3.7. `matplotlib._get_extra_test_plugins()` returns what it should `[matplotlib.testing.noseclasses.KnownFailure, nose.plugins.base.Plugin]`.

**Comment by jenshnielsen** [comment]
Is it specific to ```NPROC=1```? In the medium term we probably want to switch from nose to pytest (hopefully before matplotlib 2.1) so if it only happens for ```NPROC=1``` it might not be worth fixing it at this stage

**Comment by Kojoley** [comment]
No, it is not specific to `--processes=1`, it is the same for 2, 3, 4, etc. If `--processes` value is not 0 then nose uses multiprocess plugin and spawn workers (child processes) to perform tests. On my machine (Windows OS) the value of `multiprocess._instantiate_plugins` is not populated from the main thread to the child threads.
I have solved this issue this way: https://github.com/nose-devs/nose/pull/1005

**Comment by tacaswell** [comment]
Work to migrate started in:  https://github.com/matplotlib/matplotlib/pull/5405  but that rebase onto current master will not be fun.

https://github.com/astrofrog/pytest-mpl provides a replacement for the nose image test plugins, not sure how hard it would be too re-write our decorators to use that.

If you tackle this (which would be _awesome_) I would suggest starting from getting all of the tests to _run_ under pytest before converting all of the assertions.

**Comment by QuLogic** [comment]
We aren't using nose any more and parallel pytest seems to work in AppVeyor, so I'm going to close this.
