### ISSUE TITLE
`cleanup` decorator implemented in an obfuscated way

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6716]
It seems to be that [this line](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/testing/decorators.py#L163) should be before `make_cleanup(style)` call.

**Comment by QuLogic** [comment]
I think that line is not necessary, according to the comment above the function.

**Comment by Kojoley** [comment]
Yeah, I have just realized it too.

**Comment by Kojoley** [comment]
Is not `style = 'classic'` assignment edits `make_cleanup` closure variable? Then it cannot be removed.

**Comment by QuLogic** [comment]
Yea, I guess I should have read the whole thing; it probably could do with another comment...

**Comment by Kojoley** [comment]
I think it is better to rewrite it in some cleaner way...

**Comment by tacaswell** [comment]
And do so with an eye towards playing nice with pytest.  I have been loving fixtures on other projects, but not sure how to apply them to this.

Maybe pass in a properly prepared `matplotlib` module as a fixture?

**Comment by anntzer** [comment]
Should we just deprecate it now that everything moved to pytest (and style choice is provided by a pytest marker)?

**Comment by tacaswell** [comment]
A lot of down-stream packaging use our testing code for their own projects, we should just let this sit for a few more years until nose fully dies.  

I am going to close this as no-action.  This code is working, no need to change it as we are no longer using it and no need to risk breaking anyone down-stream.
