### ISSUE TITLE
Font cache building of matplotlib blocks requests made to HTTPd

### ISSUE THREAD

**Issue by selvamvinod** [matplotlib/matplotlib#6721]
Platform details:
CentOS Linux release 7.2.1511 (Core) 
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.7 mod_wsgi/4.5.3 Python/3.5.2

The below script blocks and gives
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')  with the matplotlib version I got from https://github.com/matplotlib/matplotlib
by a git clone on 9th Jul 2016.(Or may be 10th Jul?....Date same as my previous comment date)

```
# -*- coding: utf-8 -*-
import imp
import codecs
import os, sys,imp
import cgi
import io
import MySQLdb as mdb
import sys
from collections import OrderedDict
import sys
import unicodedata

import numpy as np
from mpl_toolkits.basemap import Basemap
#import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

import io


def application(environ, start_response):
    map = Basemap(width=10,
                  height=20,
                  resolution='c',
                  projection='gall',
                  lon_0=0)

    map.drawcoastlines()
        ...
        ...
        ...
       img_io = io.BytesIO()
       return img_io

```

**Comment by tacaswell** [comment]
Can you reproduce this issue outside of a webserver?

Can you tell us the contents of `~/.cache/matplotlib`?

**Comment by tacaswell** [comment]
Closing due to lack of response.

I think the issue is that you just have to wait for the cache to finish building before the httpd process can take clients.

**Comment by tacaswell** [comment]
@joslloand almost all of the issues you are pinging have to do with a warning we started issueing and should have had resulted in no changes to the output.
