### ISSUE TITLE
Text: rotation inconsistency

### ISSUE THREAD

**Issue by apodemus** [matplotlib/matplotlib#6722]
Text rotation seems to occur about different points depending on the sign of the angle passed:

```
import matplotlib.pyplot as plt
from matplotlib import __version__
print(__version__)
#2.0.0b1+1800.g5c1e64d.dirty

fig, ax = plt.subplots()
xx = 0.5, 0.5
ax.plot(*xx, 'rx')
blk = '\u2588' * 10  #unicode blocks
ax.text(*xx, blk, rotation=-45, color='b')  # rotation about point xx
ax.text(*xx, blk, rotation=45, color='r')   # rotation about rhs of textbox
```

![txt](https://cloud.githubusercontent.com/assets/5623552/16717352/fecff926-4714-11e6-92e0-d99dc07c2f14.png)

So essentially:  A negative angle rotates about the lower left corner of text box, while a positive angle rotates about the lower right corner of text box.  Is this desired behaviour? Personally I find it somewhat confusing and would expect rotations to have the same origin, regardless of the sign of the angle passed.

**Comment by tacaswell** [comment]
attn @mdboom @zblz

**Comment by rougier** [comment]
This might be fixed by specifying rotation mode:

```
ax.text(*xx, blk, rotation=-45, color='b', rotation_mode="anchor")
ax.text(*xx, blk, rotation=45, color='r', rotation_mode="anchor")
```

From the [doc](http://matplotlib.org/api/text_api.html):

```
If “anchor”, the un-rotated text will first aligned according to their ha and
va, and then will be rotated with the alignement reference point as a
origin. If None (default), the text will be rotated first then will be aligned.
```

**Comment by NelleV** [comment]
As an addition to this ticket, the documentation of matplotlib.text.Text probably needs to be updated and in particular that anchor_mode needs to be documented.

**Comment by tacaswell** [comment]
```python
import matplotlib.pyplot as plt
from matplotlib import __version__
print(__version__)
#2.0.0b1+1800.g5c1e64d.dirty

fig, ax = plt.subplots()
xx = 0.5, 0.5
ax.plot(*xx, 'rx')
blk = '\u2588' * 10  #unicode blocks
ax.text(*xx, blk, rotation=-45, color='b', rotation_mode='anchor')  # rotation about point xx
ax.text(*xx, blk, rotation=45, color='r', rotation_mode='anchor')  # rotation about rhs of textbox
```

![so](https://cloud.githubusercontent.com/assets/199813/19275958/1ee2e88c-8fa3-11e6-9a5b-3b9b4804b9d7.png)

is what it looks like with the 'anchor' rotation mode.

**Comment by tacaswell** [comment]
I am inclined to leave this as-is, it makes the bounding box more predictable.  Changing this default would also require a lot of matching changes in the tickers to restore the old default. 

This behavior makes more sense if you also include an un-rotated text (and play with `set_ha` and `set_va` a bit).

```python
import matplotlib.pyplot as plt
plt.ion()

fig, ax = plt.subplots()
xx = 0.5, 0.5
ax.plot(*xx, 'kx')
blk = '\u2588' * 10  #unicode blocks
t0 = ax.text(*xx, blk, color='k')
t1 = ax.text(*xx, blk, rotation=-45, color='b')
t2 = ax.text(*xx, blk, rotation=45, color='r')
```

![so](https://cloud.githubusercontent.com/assets/199813/20374059/e2343b8a-ac43-11e6-8884-3d35b712537c.png)

**Comment by NelleV** [comment]
I agree, but we do need to work a bit on the documentation on that part (at some point…)
