### ISSUE TITLE
How to customize violinplots?

### ISSUE THREAD

**Issue by pd3** [matplotlib/matplotlib#6723]
Hi, is it possible to customize violinplots to look like this? 
https://stanford.edu/~mwaskom/software/seaborn/_images/aesthetics_23_0.png

**Comment by madphysicist** [comment]
You may want to look into the [seaborn library](https://web.stanford.edu/~mwaskom/software/seaborn/), which is an extension that provides such plots. The URL indicates that the plot is one of seaborn's sample image.

**Comment by madphysicist** [comment]
In fact, if you look half-way down the page at the [aesthetics tutorial](https://web.stanford.edu/~mwaskom/software/seaborn/tutorial/aesthetics.html#aesthetics-tutorial), you will find not only the plot you posted, but detailed instructions on how to make it. You can look at some of the source code of seaborn to find out exactly how they styled the matplotlib-based plot.

**Comment by pd3** [comment]
Thank you for your response. I understand the example was made in seaborn, but I would like to create such graphs directly in matplotlib. I had looked at the seaborn source code but they seemed to re-implement the whole thing, rather than tweak the matplotlib's violinplot.

In the meantime I found a way:

     # basic plot
     parts = ax.violinplot(data,showmeans=False,showmedians=False,showextrema=False)

     # now change colors
     for pc in parts['bodies']:
        pc.set_facecolor('red')
        pc.set_edgecolor('black')
        pc.set_alpha(1)

    # plot IQR and UAV-LAV lines (calculate this from the data)
    for i in range(len(medians)):
        ax.plot([i+1,i+1],iqr[i],'k-',lw=5)
        ax.plot([i+1,i+1],avs[i],'k-',lw=1)

    # display medians as filled circles (calculate this from the data)
    for i in range(len(medians)):
        ax.plot(i+1,medians[i],'o',mec='white',c='white',ms=5)

![rmme](https://cloud.githubusercontent.com/assets/524074/16759267/63beface-4816-11e6-98e8-fb31ffa63a20.png)

**Comment by efiring** [comment]
Would you like to submit a PR with a complete example like this to be added to the gallery?

**Comment by pd3** [comment]
OK, done
