### ISSUE TITLE
scipy 2016 sprint ideas

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6727]
Some ideas on what to work on during the scipy sprints
- finish 2.0
- Altiar
  - mostly stable
  - needs mpl rederer
  - someone who knows both mpl + pandas decently well
- scales
  - unify scale handling and pull out of mpl
    - domain -> [0, 1] or ints
    - scaled data -> {color, shape, size, ...}
- expose notebook docs through notebook
  - sprint on how to make this integration work, work with IPython folks
  - convert some of our examples to notebooks
- burn down open PRs

**Comment by story645** [comment]
housekeeping? Clearing out (or even just flagging) stalled issues?

**Comment by jenshnielsen** [comment]
[MEP12](http://matplotlib.org/devdocs/devel/MEP/MEP12.html) cleanup in general is always welcome and is a good place to start.

A specific examples could be:

Move boxplot/bxp examples from the pylab folder to statistics Examples and cleanup/unify all the boxplot/bxp examples removing duplication and making them more useful.

In general I guess we should try to move as many examples from the pylab folder to more topic specific folders and clean them up

**Comment by tacaswell** [comment]
Closing as past due.
