### ISSUE TITLE
Can't install matplotlib with specific python version

### ISSUE THREAD

**Issue by b5y** [matplotlib/matplotlib#6728]
Hi,
Information:

- [+] Matplotlib version: 1.5.1
- [+] Python version: 2.7.11 (pyenv) 
- [+] Platform: Linux m 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
- [+] Tried to install matplotlib via pip and in PyCharm with the same python version from pyenv
- [+] Output example: 
<br/>
The following required packages can not be built:
                            * freetype, png
<br/>
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yynSEi/matplotlib/

I can't install matplotlib with these characteristics. I can install in anaconda, but sometimes I need pyenv. I have tried to find information about required packages and found that there is only freetype-py and pypng packages.

**Comment by tacaswell** [comment]
Just merged a PR to make this clearer https://github.com/matplotlib/matplotlib/pull/6575

Install freetype-devel and libpng-devel via apt.
