### ISSUE TITLE
Adding `pairplot` functionality?

### ISSUE THREAD

**Issue by HashCode55** [matplotlib/matplotlib#6732]
I tried to make a pairplot using the library and found this [answer](http://stackoverflow.com/questions/7941207/is-there-a-function-to-make-scatterplot-matrices-in-matplotlib) on SO... Shouldn't we have the functionality of a pairplot in the library, so that we don't have to write the function or use another library?
Or am I missing something?

**Comment by efiring** [comment]
There is a natural division of labor among libraries.  Numpy provides array math, matplotlib provides a fundamental plotting library, basemap and cartopy use matplotlib for the special case of plotting maps, seaborn customizes matplotlib for statistical visualization, pandas builds on both numpy and matplotlib to facilitate a major category of data analysis and visualization, etc.  For the health of the overall system, it is important that each library concentrate on its core functionality, and not grow out of control by trying to incorporate upstream and downstream functionality.  The boundaries between libraries are fuzzy, but I think the SO discussion you cited gives a good rationale for leaving the scatterplot matrix out of matplotlib.  (I don't actually know what a "pairplot" is, so I am assuming it is another name for the scatterplot matrix discussed on SO.)
