### ISSUE TITLE
Feature request: Adding XClass property to interactively created figures

### ISSUE THREAD

**Issue by 00tau** [matplotlib/matplotlib#6743]
I need your help.  I would like to have the window manager to, well, manage the plots, I am creating interactively during an ipython session.  When I create a plot:

```
from numpy import arange
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as pt
pt.ion()

x = arange(-10,10,step=.1)
pt.plot(x, x**2)
```

And check for the window properties, I get nothing.

```
% xprop | grep CLASS
WM_CLASS(STRING) = " ", " "
```

Is it possible to configure matplotlib to add some X-window properties to its plots?

I have installed matplotlib using pip.

```
pip freeze | grep '\(matplotlib==\)\|\(ipython==\)'
ipython==4.2.0
matplotlib==1.5.1
```

Thanks!

**Comment by tacaswell** [comment]
I would also love to be able to do this.  Any help sorting out how to do this through the GUI toolkits would be great!

**Comment by CJ-Wright** [comment]
I'd very much like this as well!

**Comment by anntzer** [comment]
Is this not closed by https://github.com/matplotlib/matplotlib/pull/8394 (i.e. mpl2.1)? (see also https://github.com/matplotlib/matplotlib/issues/4746#issuecomment-326184642)
Feel free to request a reopen if I missed something...

**Comment by CJ-Wright** [comment]
I still get 
```
$ xprop | grep "WM_CLASS(STRING)"
WM_CLASS(STRING) = " ", " "
```
when running
```
In [1]: import matplotlib.pyplot as plt

In [2]: %matplotlib
Using matplotlib backend: Qt5Agg

In [3]: plt.plot()
Out[3]: []

In [4]: 
```
with matplotlib installed from conda-forge
```
conda list matplotlib
# packages in environment at foo/mc/envs/dp_dev:
#
matplotlib                2.1.1                    py35_0    conda-forge
ipython                   6.2.1                    py35_0    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
```

**Comment by anntzer** [comment]
Well, that's because in your case IPython is setting up the QApplication, not matplotlib.  Can you try without IPython?
matplotlib *could* use setApplicationName to update the QApp's WM_CLASS, but I think it should not (because in general, matplotlib could just be embedded in some other application that does not want WM_CLASS to be fiddled with).
So I'd say the issue (if any) should be reported to IPython.

**Comment by CJ-Wright** [comment]
Without IPython it does work. Would it be possible to have this be settable somewhere?

**Comment by anntzer** [comment]
It's a matter of calling QApplicatoin.instance().setApplicationName(...).  Again I think this should be IPython's job, because *they* own the QApp.

**Comment by tacaswell** [comment]
@CJ-Wright you can also do that call and set it to what ever you want (such as xpdacq ;) )

attn @Carreau can we do this on the IPython side?

**Comment by CJ-Wright** [comment]
@tacaswell The hope was to use Awesome both at xpd and on my local to place the various windows where they needed to go at instantiation time. What is the best way to access the `QApplication` and such for an individual plot?

**Comment by takluyver** [comment]
We (IPython) create the QApplication at a point where we don't know that it's for matplotlib, so we can't set the application name to be matplotlib at that point. But if you can find the right place to put it in our code, a PR would be welcome.

**Comment by tacaswell** [comment]
@CJ-Wright The QApplication is a process singleton, `QApplication.instance()` will either return the singleton or `None`.

Please do not install Awesome on the beamline.  If you are going to fill a screen with a fixed set of plots you are probably better off building a Qt Application with embeds all of your plots.  That way you only have to maximize it reliably.

**Comment by anntzer** [comment]
Closing, as "not a matplotlib issue" (IMO) per the discussion above.
