### ISSUE TITLE
Step diagram does not support xlim() and ylim()

### ISSUE THREAD

**Issue by a904012** [matplotlib/matplotlib#6749]
[Matplotlib v.1.5.1 // Python v.3.5.1 //Windows ] [Installed using pip ] 

`ysc, timestsc, title, ylabel, xlabel, imagename=data
        max = numpy.max(ysc)
        min = numpy.min(ysc)

        ceros = []
        for k in range(len(ysc)):
            ceros.append(0)

        dates, pos = getdatesfirstpos(timestsc)
        x = numpy.arange(len(ysc))
        plt.step(x, ysc, where='mid', lw=2, linewidth=0.5, color=plt.rcParams['axes.color_cycle'][1])
        plt.ylim = (min * 1.2, max * 1.2)   ##no visible effect
        plt.xlim = (0, len(ysc))  ##no visible effect
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        plt.title(title)
        plt.fill_between(x, ysc, ceros, facecolor=plt.rcParams['axes.color_cycle'][1], alpha=0.5)
        plt.xticks(pos, dates, rotation=30)`

The error I get refers to a failure in the tuple that is being passed to xlim() and ylim().

Thanks!

**Comment by efiring** [comment]
`xlim` and `ylim` are functions, so you need to call them, not assign to them:
```python
plt.ylim(min * 1.2, max * 1.2)
```
