### ISSUE TITLE
Tableau style

### ISSUE THREAD

**Issue by blahster** [matplotlib/matplotlib#6751]
Could you please include the Tableau 10 style created by @rhiever 
https://gist.githubusercontent.com/rhiever/d0a7332fe0beebfdc3d5/raw/205e477cf231330fe2f265070f7c37982fd3130c/tableau10.mplstyle

**Comment by WeatherGod** [comment]
Wasn't there a previous discussion with regards to trademarks about this?

**Comment by QuLogic** [comment]
Yes, #3700. I am going to close this under the assumption that the IP issues have not been resolved.

**Comment by blahster** [comment]
Oh, didn't know that. Thanks for clarifying @QuLogic
