### ISSUE TITLE
ImportError: No module named artist

### ISSUE THREAD

**Issue by Faruk10** [matplotlib/matplotlib#6771]
Hello, please could any one help ! I attempted to plot tsne,but  i got this error:
ImportError                               Traceback (most recent call last)
<ipython-input-3-92e95e3559a6> in <module>()
----> 1 from matplotlib.pyplot import *
      2 from matplotlib.offsetbox import TextArea, DrawingArea, OffsetImage,     AnnotationBbox
      3 from matplotlib.cbook import get_sample_data
      4 # Plotting function
      5 matplotlib.rc('font', **{'family' : 'sans-serif',

C:\Users\amaall1010\Anaconda2\lib\site-packages\matplotlib\pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

C:\Users\amaall1010\Anaconda2\lib\site-packages\matplotlib\colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections

ImportError: No module named artist
Thanks

**Comment by tacaswell** [comment]
Your installation is broken, reinstalling mpl via conda

```
conda install matplotlib --force
```

If this does not work, try the mpl user mailing list (matplotlib-users@python.org)

**Comment by IshitaShah06** [comment]
I had the same issue and it worked for me. Thank you :)

**Comment by 1529046970** [comment]
I had the same issue and it worked for me. Thank you :)

**Comment by jklymak** [comment]
@bgbutler If you are still having trouble, please open a new issue.  However, this really seems to be an install problem, possibly multiple places on your system where python is looking for libraries

**Comment by waqaschughtai** [comment]
It worked for me but there was a warning that force command will be removed in the future

**Comment by IssacMiao** [comment]
Reinstall matplotlib helps

**Comment by jbanerje** [comment]
`conda install matplotlib --force` worked for me

**Comment by tyadav** [comment]
ModuleNotFoundError: No module named 'matplotlib.artist' still not working

**Comment by tyadav** [comment]
Observed that this error: "ModuleNotFoundError: No module named 'matplotlib.artist'" is only with **Jupyter lab**, it working with other IDE even with jupyter notebook as well. 
Any suggestions please.

**Comment by DaGebster** [comment]
tyadav, you probably have competing python installs.. the force option should work

**Comment by tacaswell** [comment]
Please direct future questions about installation issues to https://discourse.matplotlib.org/c/community/install/13

**Comment by tyadav** [comment]
> 
> 
> tyadav, you probably have competing python installs.. the force option should work

YEs It's working now, I reinstalled everything. thanks.

**Comment by ostwalprasad** [comment]
Did not work with reinstalling or -force re-installation.

I perused error trace-back to find out that there's one more Python installation in my system at _~\AppData\Roaming\Python\Python37._ Deleted it and now it works fine!

**Comment by naikshubham** [comment]
> 
> 
> Did not work with reinstalling or -force re-installation.
> 
> I perused error trace-back to find out that there's one more Python installation in my system at _~\AppData\Roaming\Python\Python37._
> 
> Deleted it and now it works fine!

This worked for me. Thanks.

**Comment by sivaji12344** [comment]
from plot_decision_boundary import plot_decision_boundary
plt.figure()
plt_data(X[:,1:],y)
plt.xlabel('corona_test_andhra')
plt.ylabel('corona_test_telangana')
plt.legend(['corona=+ve','corona=-ve'],loc='upper right',numpoint=1)
plot_decision_boundary(theta,X,y)
plt.show()




and it gives error like: Module Not Found Error: No module named 'plot_decision_boundary'

**Comment by Akshay4452** [comment]
Thanks man it worked

**Comment by RutujaSheth** [comment]
![IMG_7073](https://user-images.githubusercontent.com/127329486/232247267-8cf08963-1b2e-4989-819b-f8a4348215ca.jpeg)
![Uploading IMG_7072.jpeg…]()
Getting above error. Can anyone help resolving it?
