### ISSUE TITLE
Shifted image extents in 2.0.0.b3

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#6773]
Comparing images in 1.5.2 and 2.0.0b3 shows a reasonably large change. Originally, I thought the sampling was just different and it was intended, but closer inspection seems to indicate that it might actually be a small shift in the extent.

 I don't have a simple example, but here are two from Cartopy to illustrate what I mean:
![global_map_v1.5.2](https://cloud.githubusercontent.com/assets/302469/16899812/2fb3a5a0-4bdf-11e6-8968-b39d70cfd8a9.png)
![global_map_v2.0.0b3](https://cloud.githubusercontent.com/assets/302469/16899814/3b3448d0-4bdf-11e6-98ff-b799c9f7c04d.png)
If you switch between them, you can see that 2.0.0b3 seems higher, though I think it's actually the right edge that's a bit further out.

A better example is:
![imshow_regional_projected_v1.5.2](https://cloud.githubusercontent.com/assets/302469/16899840/a47e4458-4bdf-11e6-94ac-22a19768e040.png)
![imshow_regional_projected_v2.0.0b3](https://cloud.githubusercontent.com/assets/302469/16899841/a7d6af32-4bdf-11e6-848f-49d3f890715b.png)
It's clear on this one that the image is just a bit wider in 2.0.0b3 vs 1.5.2.

The code for these two plots is [global_map.py](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/examples/global_map.py) and [test_regional_projected](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/tests/mpl/test_images.py#L146).

It looks like one edge is off-by-one or something, but it's also possible that the transforms were just corrected in some way.

**Comment by mdboom** [comment]
Good eye!

There's a very subtle adjustment in the image code to account for the fact that the edges of normal rectilinear axes are pixel-snapped -- the images are correspondingly pixel snapped as well.  For non-rectilinear axes, as here, that adjustment isn't necessary.  #6776 should fix this.
