### ISSUE TITLE
Last figure in http://matplotlib.org/users/pyplot_tutorial.html is not displayed correctly 

### ISSUE THREAD

**Issue by orena1** [matplotlib/matplotlib#6775]
Chrome Version 51.0.2704.103 (64-bit)

The xticks and yticks in the last figure in documentation page is not displayed correctly
http://matplotlib.org/users/pyplot_tutorial.html

![image](https://cloud.githubusercontent.com/assets/8983713/16900948/0f0eb6a6-4c3d-11e6-9b1c-7724140931ca.png)

**Comment by afvincent** [comment]
Thank you for reporting the issue. I'll have a look into it.
