### ISSUE TITLE
suggestion: set_xticklabels and set_yticklabels default to current labels

### ISSUE THREAD

**Issue by chubukov** [matplotlib/matplotlib#6795]
I often find myself writing a construction like this:

`ax.set_xticklabels([x.get_text() for x in ax.get_xticklabels()],rotation=90)`

This just looks ugly and it feels to me like this should have the same effect:

`ax.set_xticklabels(rotation=90)`

which would just require handling `labels=None` and defaulting to the current labels.

Or is there already a more idiomatic way to do this that I'm missing?

**Comment by Phlya** [comment]
`plt.setp(ax.xaxis.get_majorticklabels(), rotation=90)` is probably more idiomatic?.. Definitely shorter.

**Comment by tacaswell** [comment]
The `Axis` objects should probably be updated to include rotation as a valid tick parameter.  

I think this will require updating `mpl.axis._translate_tick_kw` to allow rotation as a key + a test + a whats_new entry.

With those changes I think you will be able to do

```python
ax.xaxis.set_tick_params(which='both', rotation=90)
```

**Comment by tacaswell** [comment]
implemented by #6829
