### ISSUE TITLE
clean and regenerate travis cache

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#6798]
The python nightly build is currently failing with 

```
  File "/home/travis/build/jenshnielsen/matplotlib/venv/lib/python3.6/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```
I suspect  this is due to the numpy wheel build on 3.6 alpha being build against an out of date version. I have verified on my own branch that this can be fixed by cleaning the Travis cache. 

Any objections to cleaning the Travis cache for matplotlib/matplotlib it will lead to increased build times until the ccache and wheel cache is regenerated (mainly the manual rebuild of Pandas I think)

**Comment by tacaswell** [comment]
Go for it!  Temporarily longer build times is better than a failing test build.

Depending on the caching rules, if we force rebuild master + v2.x that might propagate out to all of the PRs?

**Comment by jenshnielsen** [comment]
The list of caches are here https://travis-ci.org/matplotlib/matplotlib/caches We can delete them one by one or all together. If we rebuild master and 2.x then all new prs from them should reuse their caches. Annoyingly there is no way to just delete the 2.6 nightly cache.

**Comment by jenshnielsen** [comment]
All cache cleared and 2.x and master jobs restarted
