### ISSUE TITLE
creating axes outside of rc_context makes rc_context have no effect?

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#6801]
I'm using Ubuntu, matplotlib 1.5.1 installed via conda, Python 3.5.

I tried the following:

``` python
plt.title("stuff")
with mpl.rc_context(rc={'axes.prop_cycle' : cycler('marker', ['o', 'v', 's', 'D']),
                           'lines.linestyle': None}):
    plt.plot(np.random.uniform(size=10))
    plt.plot(np.random.uniform(size=10))
    plt.plot(np.random.uniform(size=10))
```

The context manager is ignored / the styles are not applied.
If I move the title into the context manager, it works as I would expect.

Is that the desired behavior?
From the [documentation](http://matplotlib.org/api/matplotlib_configuration_api.html#matplotlib.rc_context) I got the impression that I could use multiple context managers within one figure, so I'd thought I could apply the context manager only to parts of it.

**Comment by WeatherGod** [comment]
Yes and no. You are running into an edge case because of how the cyclers
are handled. Cyclers are created with the axes object. Setting the context
manager won't reset the existing cycler (maybe it should?). Many other
properties will work as you'd expect, though.

**Comment by amueller** [comment]
My expectation would be that if I define a new cycler, it resets the old one. I have no idea about the internals, so I'm coming from this entirely from a user perspective.

**Comment by WeatherGod** [comment]
so, here's some fun problems (not necessarily blockers, but troublesome):
1. We would need to retain the old cyclers from each axes in their current
state to restore upon exit of the context.
2. Another tricky point is that often times, the style context simply has a
cycler that is identical to the cycler that is in the current style. Should
declaring the style context reset the cycler to the beginning in that case?
Note, I am not talking about when a dictionary is explicitly passed in,
rather the case of specifying a style sheet that happen to have a normal
cycler.

**Comment by tacaswell** [comment]
Maybe `Axes` objects should have a prop_cycle context manager?


```python

fig, ax = plt.subplots()
with ax.cycle_context(cycler(...)):
   ...
```

**Comment by tacaswell** [comment]
and I change the title because setting the axes title is not the trigger, it is creating the `Axes` object (which is implicitly done by `plt.title` if an axes does not exist) is the trigger.

**Comment by WeatherGod** [comment]
nah, I have to agree with Andreas here. There is already style context, and
the property cycle is a part of the style, for better or worse. Splitting
the cycler out like that is just confusing. We just need to have a solid
idea of what the behavior should be.

**Comment by tacaswell** [comment]
Except for things that explicitly affect saving (ex the save dpi) all lookups to rcParams happens at artist creation time.  If we are going to special case the behavior of a handful of them to apply retroactively it seems better do add context managers to those cases than have to document that some keys behave differently.

**Comment by WeatherGod** [comment]
Well, I am thinking that the norm should be that if it is in the context,
then it should have an impact. The user doesn't know that the cycler exists
already, nor do they need to.

A partial solution might be to defer loading the cycler until the first
request for it. That would at least save users this particular surprise. I
don't think there is any good reason for it to be a part of the constructor
besides historical reasons.

**Comment by tacaswell** [comment]
Deferring creating of the cycler until it is used would break code like

```python
with mpl.rc_context(rc={'axes.prop_cycle' : cycler('marker', ['o', 'v', 's', 'D']),
                           'lines.linestyle': None}):
   fig, ax = plt.subplots()

ax.plot(...)
```

**Comment by amueller** [comment]
Break in the sense of backward compatibility, right? As a user, I would have hoped that has no effect ;)

**Comment by amueller** [comment]
Maybe to add to this: For the current way to work, I, as a user, need to be aware of what object the cycler is attached to (the axes object), which I couldn't have known without reading the code. I guess you could say this is also a documentation issue. I would also need to know which commands create the axes object, which I also don't know [insert john snow image].

**Comment by tacaswell** [comment]
Further if we defer

```python
with mpl.rc_context(rc={'axes.prop_cycle' : cycler('marker', ['o', 'v', 's', 'D']),
                           'lines.linestyle': None}):
   fig, ax = plt.subplots()
   ax.plot(...)  # <- if this line is present

ax.plot(...)   # would control which prop_cylce this line hits.
```

Keeping track of when/where you create the `Axes` object is one of the reasons I advocate for always doing `fig, ax = plt.subplots()` and then using the OO api rather than using pyplot.

The style cycles have to be attached to an axes, or there would be cross-axes conflicts.  Where would you have expected to look for this information (other than reading the source)?  The most obvious google search got to this: http://matplotlib.org/examples/color/color_cycle_demo.html

**Comment by amueller** [comment]
I looked at the docs for rc_context and at the docs for cycler.
I didn't see the example, which actually explains my use-case pretty well.

>     1. Setting the default rc-parameter specifying the property cycle.
       This affects all subsequent axes (but not axes already created).

I feel this should be somewhere in the docs, not only the examples. In my world, examples illustrate what is described in the main doc - but that is in a world of perfect documentation of course ;)

If you like you can file it under me not reading (finding?) the right docs.
I can achieve everything I want to achieve with the current API, I was just a bit surprised.
I'll defer to your judgement on whether this is an issue.

**Comment by tacaswell** [comment]
This component of the scope should probably be clarified in the `rc_context` docs.

**Comment by WeatherGod** [comment]
This is one of those rare times where I feel that declarative is better
than imperative.

**Comment by amueller** [comment]
hm possibly another misunderstanding of mine:
Can I have different cyclers on different subplots in the same figure?
If I do
``
fig, axes = plt.subplots(3, 3)
``
then all the axes will have the same cycler, right?

**Comment by WeatherGod** [comment]
It is possible to do that, but that approach will produce the same cyclers.
You would have to explicitly change the property cyclers for each axes
object. You can call ax.set_prop_cycle(). See the docstring for its very
flexible call signature.

**Comment by amueller** [comment]
thanks :)

**Comment by maij** [comment]
I've just learned of this problem the hard way myself, I'm happy to attempt a fix but it sounds like the design isn't 100% clear.

It would be really convenient if you could do something along the lines of:
```python
rc_fit_style = {'lines.linestyle': '-.', 'axes.prop_cycle': mpl.cycler(color=['gray'])}
fig = plt.figure()
plt.plot(x, y)
with plt.rc_context(rc_fit_style):
   plt.plot(x, best_fit_vals) # Plot a fit to the data on top
```

Although really in this context I just want some way to override the cycler with a single color, which I believe is not possible with rcParams any other way.

**Comment by timhoffm** [comment]
>  I'm happy to attempt a fix but it sounds like the design isn't 100% clear.

AFAICS there is no reasonable fix. The only thing we can do is better documentation.

All solutions are more or less problematic, some indicated above. But if you have a good idea, we'd welcome your suggestion.

**Comment by tacaswell** [comment]
I think the work that still needs to be done here is to make https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.rc_context.html#matplotlib.pyplot.rc_context clairify that it only affects objects created within the context (so new figures, new axes, new lines, new ...) not already existing ones.

**Comment by tacaswell** [comment]
It might be worth adding an example that does not work (e.g. creating an `Axes` and then setting the prop cyle in `rc_contetx` and plotting within the context block) so long as it is clear to anyone who copy-pastes the code what it is expected to do.
