### ISSUE TITLE
Histogram of xarray.DataArray can be extremely slow

### ISSUE THREAD

**Issue by maahn** [matplotlib/matplotlib#6804]
Xarray is a package for labeled arrays. If you use plt.hist to make a histogram of a DataArray, the speed depends a lot how you do it:

    import xarray as xr
    import numpy as np
    import matplotlib.pyplot as plt

    nPoints = 100000
    data = xr.DataArray(np.random.random(nPoints),dims=['time'],coords=[np.arange(nPoints)])
It takes only some ms if you use

    plt.figure()
    %time data.plot.hist()

    plt.figure()
    %time plt.hist(data.values)

However, if you omit .values it takes extremely long:

    In [12]: %time plt.hist(data)
    CPU times: user 2min, sys: 9.73 s, total: 2min 9s
    Wall time: 2min 3s

%prun suggests that the OrderdDict class is to blame:

             145056729 function calls (144455882 primitive calls) in 198.255 seconds

       Ordered by: internal time

       ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      1800009   11.602    0.000   29.587    0.000 collections.py:50(__init__)
      2800014    9.536    0.000   24.279    0.000 _abcoll.py:548(update)
       400002    5.934    0.000   30.815    0.000 variable.py:334(__getitem__)
     10200067    5.499    0.000    5.499    0.000 collections.py:90(__iter__)
     13203051    5.330    0.000   13.624    0.000 {isinstance}
      6600104    5.002    0.000    5.002    0.000 {hasattr}
      2400082    4.842    0.000    7.813    0.000 abc.py:128(__instancecheck__)
      2400012    4.821    0.000    4.821    0.000 collections.py:71(__setitem__)
      6200102    4.821    0.000    4.821    0.000 _weakrefset.py:70(__contains__)
      4400022    4.449    0.000    4.449    0.000 common.py:196(__setattr__)
       200001    4.378    0.000   12.152    0.000 base.py:124(__new__)
      1000005    4.308    0.000    5.123    0.000 indexing.py:10(expanded_indexer)
       200001    4.304    0.000   51.921    0.000 dataset.py:878(isel)
       200001    3.624    0.000   15.635    0.000 alignment.py:108(align_variables)
       400002    3.434    0.000    8.928    0.000 dataset.py:66(_calculate_dims)
       200001    3.347    0.000    9.288    0.000 dataset.py:470(_construct_dataarray)
       600003    3.216    0.000    6.535    0.000 variable.py:87(as_compatible_data)
       200001    3.142    0.000   99.663    0.000 merge.py:116(merge_datasets)
       200001    3.044    0.000   12.129    0.000 coordinates.py:198(_to_dataset)
       200001    2.740    0.000   92.687    0.000 merge.py:101(_merge_dataset_with_dict)
      2800014    2.714    0.000    5.114    0.000 abc.py:148(__subclasscheck__)
       400002    2.710    0.000   34.370    0.000 variable.py:493(isel)
      3400017    2.651    0.000    4.377    0.000 collections.py:138(iteritems)
      2400018    2.266    0.000    3.617    0.000 utils.py:355(ndim)
       200001    2.028    0.000   18.420    0.000 dataset.py:221(_update_vars_and_coords)
       400002    1.954    0.000   48.424    0.000 alignment.py:37(_join_indexes)
       600003    1.792    0.000   14.645    0.000 variable.py:192(__init__)
      4000844    1.712    0.000    1.713    0.000 {getattr}
       400002    1.675    0.000    3.975    0.000 dataset.py:367(_construct_direct)
       400002    1.624    0.000   44.523    0.000 alignment.py:28(_get_all_indexes)
       200001    1.607    0.000   48.978    0.000 alignment.py:95(partial_align)
       200001    1.585    0.000   17.709    0.000 merge.py:82(_merge_expand)

If one forgets to add .values or to use xarray's plot routine, one can be stuck for a long time. I have to kill python 1-2 per day due to that issue.

I have matplotlib 1.5.1 and xarray 0.7.2 on OSX/anaconda.

**Comment by shoyer** [comment]
Here's the stack trace I see if I interrupt `plt.hist(data)`:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-13-e6afcf6cf756> in <module>()
----> 1 plt.hist(data)

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/pyplot.py in hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, hold, data, **kwargs)
   2956                       histtype=histtype, align=align, orientation=orientation,
   2957                       rwidth=rwidth, log=log, color=color, label=label,
-> 2958                       stacked=stacked, data=data, **kwargs)
   2959     finally:
   2960         ax.hold(washold)

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5941 
   5942         # process the unit information
-> 5943         self._process_unit_info(xdata=x, kwargs=kwargs)
   5944         x = self.convert_xunits(x)
   5945         if bin_range is not None:

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/axes/_base.py in _process_unit_info(self, xdata, ydata, kwargs)
   1908             # we only need to update if there is nothing set yet.
   1909             if not self.xaxis.have_units():
-> 1910                 self.xaxis.update_units(xdata)
   1911 
   1912         if ydata is not None:

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/axis.py in update_units(self, data)
   1381         """
   1382 
-> 1383         converter = munits.registry.get_converter(data)
   1384         if converter is None:
   1385             return False

/Users/shoyer/conda/envs/xarray-dev/lib/python3.5/site-packages/matplotlib/units.py in get_converter(self, x)
    160 
    161         if converter is None and iterable(x):
--> 162             for thisx in x:
    163                 # Make sure that recursing might actually lead to a solution,
    164                 # if we are just going to re-examine another item of the same

/Users/shoyer/dev/xarray/xarray/core/common.py in _iter(self)
    137     def _iter(self):
    138         for n in range(len(self)):
--> 139             yield self[n]
    140 
    141     def __iter__(self):

/Users/shoyer/dev/xarray/xarray/core/dataarray.py in __getitem__(self, key)
    419         else:
    420             # orthogonal array indexing
--> 421             return self.isel(**self._item_key_to_dict(key))
    422 
    423     def __setitem__(self, key, value):

/Users/shoyer/dev/xarray/xarray/core/dataarray.py in isel(self, **indexers)
    600         DataArray.sel
    601         """
--> 602         ds = self._to_temp_dataset().isel(**indexers)
    603         return self._from_temp_dataset(ds)
    604 

/Users/shoyer/dev/xarray/xarray/core/dataarray.py in _to_temp_dataset(self)
    261     def _to_temp_dataset(self):
    262         return self._to_dataset_whole(name=self.__this_array,
--> 263                                       shallow_copy=False)
    264 
    265     def _from_temp_dataset(self, dataset, name=__default):

/Users/shoyer/dev/xarray/xarray/core/dataarray.py in _to_dataset_whole(self, name, shallow_copy)
    290                              'the same name as one of its coordinates')
    291         dataset = self.coords._to_dataset(shallow_copy=shallow_copy)
--> 292         dataset[name] = self.variable
    293         return dataset
    294 

/Users/shoyer/dev/xarray/xarray/core/dataset.py in __setitem__(self, key, value)
    562             raise NotImplementedError('cannot yet use a dictionary as a key '
    563                                       'to set Dataset values')
--> 564         self.update({key: value})
    565 
    566     def __delitem__(self, key):

/Users/shoyer/dev/xarray/xarray/core/dataset.py in update(self, other, inplace)
   1460         """
   1461         return self.merge(
-> 1462             other, inplace=inplace, overwrite_vars=list(other), join='left')
   1463 
   1464     def merge(self, other, inplace=False, overwrite_vars=set(),

/Users/shoyer/dev/xarray/xarray/core/dataset.py in merge(self, other, inplace, overwrite_vars, compat, join)
   1509         """
   1510         replace_vars, new_coord_names = merge_datasets(
-> 1511             self, other, overwrite_vars, compat=compat, join=join)
   1512         obj = self if inplace else self.copy()
   1513         obj._update_vars_and_coords(replace_vars, new_coord_names)

/Users/shoyer/dev/xarray/xarray/core/merge.py in merge_datasets(dataset, other, overwrite_vars, compat, join)
    138 
    139     newly_coords = new_coord_names & set(dataset.data_vars)
--> 140     no_longer_coords = set(dataset.coords) & (set(new_vars) - new_coord_names)
    141     ambiguous_coords = (newly_coords | no_longer_coords) - overwrite_vars
    142     if ambiguous_coords:

/Users/shoyer/dev/xarray/xarray/core/coordinates.py in __iter__(self)
     51         self.update({key: value})
     52 
---> 53     def __iter__(self):
     54         # needs to be in the same order as the dataset variables
     55         for k in self._variables:

KeyboardInterrupt: 
```

So the culprit appears to be matplotlib's units interface, which interates through every single element of the array to be plotted in an attempt to find a converter. This is possibly sane default behavior for methods that plot every input data point (so overhead should be small compared to constructing the points to plot in matplotlib), but not for methods like `hist` that summarize data before it's plotted.

**Comment by shoyer** [comment]
In particular, this logic [from units.py](https://github.com/matplotlib/matplotlib/blob/96003f977d255e406f339c275efd2d6390de1580/lib/matplotlib/units.py#L163) seems possibly backwards:
```
                # Make sure that recursing might actually lead to a solution,
                # if we are just going to re-examine another item of the same
                # kind, then do not look at it.
                if classx and classx != getattr(thisx, '__class__', None):
```

Shouldn't this be `if classx and classx == getattr(thisx, '__class__', None)`?

There are no tests, so possibly @jrevans can comment if they remember what they were intending here (https://github.com/matplotlib/matplotlib/commit/cce139d71d2cee1cbda0aa03ed8f380c2c38ed14).

**Comment by jrevans** [comment]
What you see in the code is the correct logic.

 

classx is the class of x.  If you get to that part of the method, then x is an iterable object, so we want to recurse into said container to determine the converter for the contained type.  As per the  comment, the idea is to *not* recurse if the contained item is of the same type as the container (such as with strings).  Changing the logic to '==' would make it recurse only if they are the same, which is not the desired behavior.

 

--James Evans

**Comment by shoyer** [comment]
@jrevans Indeed, the logic does seem correct there. Thanks for clarifying.

Still, the issue stands that is may be very expensive to iterate through every elements of a long non-numpy array individually.

**Comment by jrevans** [comment]
In most cases it won't iterate over every element, it will stop at the first one that yields a unique type that can provide a converter.  In most cases that should be the first item.

 

--James

**Comment by shoyer** [comment]
A 1-D `xarray.DataArray` is a sequence of 0-D `xarray.DataArray` objects. Unfortunately, matpltolib needs to loop over then entire outer array to figure this out.

**Comment by tacaswell** [comment]
Maybe add a `break` or use https://github.com/matplotlib/matplotlib/blob/96003f977d255e406f339c275efd2d6390de1580/lib/matplotlib/cbook.py#L2441 to look at just the first element?

It returns on the first element that 'catches' and if the input is of mixed type/units something else is going to go wrong down the line anyway.

**Comment by story645** [comment]
Would it make sense to write a convertor then for xarray.DataArray, similar to the ones pandas has for their dateframe objects? The convertors could then yield the most efficient structure?

**Comment by shoyer** [comment]
@tacaswell  It would be nice if matplotlib worked for objects convertable to numpy arrays without serious performance consequences automatically, so I think using `safe_first_element` for unit checks would be a good start.

@story645 I'm definitely open to writing a converter, but it's a little tricky because `xarray.DataArray` is a generic container type. What would a converter that simply converts using `np.asarray` look like? The challenge is that we also would like to (recursively) trigger any other appropriate converters on the input types (e.g., if it's an array of datetime values).

**Comment by story645** [comment]
@tacaswell @shoyer as much as this may introduce code bloat issue, can some optimization be thrown into the new asSequence for this case...

@shoyer maybe something recursive?

**Comment by tacaswell** [comment]
@story645 Which DF converter are you referring to here?

MPL does try to support things that smell like numpy arrays as transparently as possible, the issue is that both pandas, xarray, and the unit-full ndarray sub-classes break some subtle assumptions which we need to work around.  In this case, the assumption is that iterating over an iterable will eventually gives you back a scalar of a base type (pandas breaks the assumption that `obj[0]` gives you the first element and the unit-full ndarrays break the assumption that `obj = np.asarray(obj)` is safe).

**Comment by story645** [comment]
Looked through the code and realized I was mistaken and that they only do units registry for date stuff (element level units...)

I feel like this speaks to a need for intermediate level convertors or an unpacking function.

**Comment by tacaswell** [comment]
@shoyer @maahn I would backport a minimal patch to only check the first element for the 2.0 release, can one of you take care of that?

**Comment by maahn** [comment]
Sure, I'm happy to make a pull request. Just to make sure I get you right: you want to replace the loop 
https://github.com/matplotlib/matplotlib/blob/96003f977d255e406f339c275efd2d6390de1580/lib/matplotlib/units.py#L158
with

        if converter is None and iterable(x):
            converter = self.get_converter(safe_first_element(x))
            return converter

?

**Comment by tacaswell** [comment]
@maahn Yes.

**Comment by tacaswell** [comment]
I think you still need that extra `if` statement as well though.
