### ISSUE TITLE
Matplotlib seaborn styles examples

### ISSUE THREAD

**Issue by gVallverdu** [matplotlib/matplotlib#6812]
Hello

As I wanted to understand the seaborn styles provided by matplotlib, I wrote the following short notebook. I opened this issue just to give you the url. If you think it is relevant, you can take it or add the content to the doc for example or somewhere else !

http://nbviewer.jupyter.org/github/gvallverdu/cookbook/blob/master/mpl_seaborn_styles.ipynb
- matplotlib version 1.5.1, with python3, on mac OSX
- Installation using pip3

**Comment by tacaswell** [comment]
That should probably go in to http://matplotlib.org/examples/style_sheets/index.html

**Comment by gVallverdu** [comment]
Yes. I did not know that page but it seems that the containts of the notebook is the same as these examples.

**Comment by ImportanceOfBeingErnest** [comment]
It seems this is covered by the existing [style sheet reference](https://matplotlib.org/examples/style_sheets/style_sheets_reference.html), so this issue can be closed?
