### ISSUE TITLE
Failure to build docs: unknown property

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#6818]
Python 3.5.1 | Anaconda 4.0.0 | Matplotlib 1.5.1

I tried running `python make.py html` inside a conda created virtualenv and received the following error. I tried again using my standard Anaconda install and received the same error in the `~\Anaconda\lib\site-packages` directory.

```
Warning, treated as error:
C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\widgets.py:docstring of matplotlib.widgets.Curs   or:22: WARNING: Exception occurred in plotting cursor
 from C:\Users\Conner\Documents\GitHub\matplotlib\doc\mpl_examples/widgets/cursor.py:
Traceback (most recent call last):
  File "C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\sphinxext\plot_directive.py", line 517,    in run_code
    six.exec_(code, ns)
  File "<string>", line 7, in <module>
  File "C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\axes\_subplots.py", line 73, in __init_   _
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\axes\_base.py", line 537, in __init__
    self.update(kwargs)
  File "C:\Users\Conner\Anaconda3\envs\venv\lib\site-packages\matplotlib\artist.py", line 856, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property facecolor

Building HTML failed.
```

**Comment by tacaswell** [comment]
What happens if you try to run `python C:\Users\Conner\Documents\GitHub\matplotlib\doc\mpl_examples/widgets/cursor.py` ?

We run the doc build as part of the test suite (but not on windows) and I can not reproduce this on my machine.  Can you help narrow this down any?

**Comment by LindyBalboa** [comment]
It is a very similar error, just tracing back to the actual creating of the axes object:
'''
Traceback (most recent call last):
  File "cursor.py", line 7, in <module>
    ax = fig.add_subplot(111, facecolor='#FFFFCC')
  File "C:\Users\Conner\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "C:\Users\Conner\Anaconda3\lib\site-packages\matplotlib\axes\_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "C:\Users\Conner\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 537, in __init__
    self.update(kwargs)
  File "C:\Users\Conner\Anaconda3\lib\site-packages\matplotlib\artist.py", line 856, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property facecolor
'''

**Comment by LindyBalboa** [comment]
I did some more digging and I can't find any mention of `facecolor` being a valid parameter for an `Axes` object. There is however, the `axis_bgcolor` parameter. I changed it as such and running `cursor.py` on it's own worked
```
from matplotlib.widgets import Cursor
import numpy as np
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, axis_bgcolor='#FFFFCC') #Was formerly facecolor='#FFFFCC'

x, y = 4*(np.random.rand(2, 100) - .5)
ax.plot(x, y, 'o')
ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)

# set useblit = True on gtkagg for enhanced performance
cursor = Cursor(ax, useblit=True, color='red', linewidth=2)

plt.show()
```

However, upon trying to compile the docs again, I got another error which I haven't resolved yet:
```
Warning, treated as error:
C:\Users\Conner\Documents\GitHub\matplotlib\doc\examples\api\collections_demo.rst:8: WARNING: Exception occurred in plotting collections_demo
 from C:\Users\Conner\Documents\GitHub\matplotlib\doc\mpl_examples\api\collections_demo.py:
Traceback (most recent call last):
  File "C:\Users\Conner\Anaconda3\lib\site-packages\matplotlib\sphinxext\plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "<string>", line 41, in <module>
  File "<string>", line 41, in <listcomp>
AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'

Building HTML failed.
```

**Comment by tacaswell** [comment]
I think you are trying to build the current docs against an old version of
the library.

Either build the library also from source our check out the 1.5.1 tag to
build those docs.

**Comment by LindyBalboa** [comment]
Aha yes that is the conclusion I came to as well. I must admit I am rather quite new to the whole git process. I've been using the utilities for a while now and wanted to help give back. Noobie mistakes it seems. 

If you don't mind, what is the difference between the main branch and the 1.5.x branch? Most of the git resources (including for matplotlib) said to take the main branch, and I couldn't find much clarification on my own.

Thanks

**Comment by WeatherGod** [comment]
The general mpl development policy is that we keep 1 maintenance branch
which we target bugfixes for and cut releases from. The v2.x branch (used
to be called v2.0.x) contains the changes for the upcoming v2.0 release
(the style-change release). The master branch contains not only v2.x
changes (which is mainly the style changes + v1.5.x changes), but also all
the new features and changes that are coming down the pike for v2.1.

The v1.5.x branch was cut off recently as we prep for the v1.5.3 bugfix
release (skipping v1.5.2 for certain reasons). v2.x is now considered
"maintenance" even though v2.0 hasn't been released yet.

Yeah, it can be weird to follow, sometimes...
