### ISSUE TITLE
Image comparison decorator: symlinks to baseline images

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6824]
Currently image comparison decorator copies baseline image to `result_images` folder. Is not it better not to copy, but make symlink? With that change it still will be safe to remove `result_images` folder with `rm -rf`.

**Comment by jenshnielsen** [comment]
Sounds reasonable to me. We just need to ensure that this still runs correctly on all platforms

**Comment by tacaswell** [comment]
symlinks do not play will with windows

**Comment by Kojoley** [comment]
Matplotlib supports Windows XP? If not then Windows is not [a problem](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363866(v=vs.85).aspx).
Actually I have already developed cross-platform symlink support for `image_comparison` decorator with fallback to simple copy on unsupported platform, but it uses `ctypes` and gives not a big boost to testing time (around ~10 seconds)

**Comment by jenshnielsen** [comment]
As far as I remember the main problem is with symlinks within git repositories. That should not apply here. I am not sure about windows xp. We have not deliberately broken support for it but it's also not really tested.

**Comment by Kojoley** [comment]
I had some problems with git and links, but they were hard links to files or symlinks to folders (because you can easily wipe your original folder or files). That does no apply here at least because `result_images` does not belong to git repository.

**Comment by tacaswell** [comment]
As a non-windows user I am greatly confused why the issues with links apply to git, but not here?

@Kojoley If you work on windows and this works for you then :+1: to links instead of copying.

**Comment by Kojoley** [comment]
Previously git-scm on windows was not aware of symlinks (from its point they were just regular files), so `git checkout` or `git reset` will give you no error and just replace/wipe content of symlinked file.

**Comment by Kojoley** [comment]
I do not know is it problem or not, but I think by default artifact tars will contain symlinks to baseline images (I believe there is some switches for this)

**Comment by jbrockmendel** [comment]
Just discovered `@image_comparison` and its a nice feature, but I'd like to be able to specify where the created images will be placed.  Creating a `result_images` images in my project's root directory is not welcome.

LMK if this belongs in a separate issue.

**Comment by tacaswell** [comment]
@jbrockmendel You should have a look at pytest-mpl instead.

**Comment by anntzer** [comment]
done in https://github.com/matplotlib/matplotlib/pull/10222.
