### ISSUE TITLE
Spikes in small wedges of a pie chart

### ISSUE THREAD

**Issue by bronger** [matplotlib/matplotlib#6828]
The following applies to Python3 + matplotlib 1.5.1.

http://wilson.bronger.org/software.svg exhibits ugly spikes in the small wedges of this pie chart.  After importing the SVG into Inkscape, the problem is even worse but can be fixed by changing the style of line vertices to "rounded".

The code is:

    from matplotlib import pyplot
    import matplotlib

    figure = pyplot.figure()
    axes = figure.gca()
    axes.pie([23, 22, 2, 42, 1, 34, 17, 21, 15, 290, 897],
             labels=["Fedora", "CKAN", "dLibra" + 8 * " ", "DSpace",
                     "eSciDoc", "DataVerse", "EPrints", "MySQL", "Nesstar",
                     "sonstige", "unbekannt"],
             explode=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15],
             wedgeprops={"clip_on": True, "capstyle": "round"},
             shadow=True, startangle=150)
    axes.set_aspect("equal")
    figure.savefig("software.svg", bbox_inches="tight", transparent=True)

**Comment by tacaswell** [comment]
I am not sure that this is a bug in mpl.  PNG output looks correctly and you report that this is svg render dependent.

![so](https://cloud.githubusercontent.com/assets/199813/17215264/4ecf9b50-54aa-11e6-86c9-c3f2fa5a7fc8.png)

Maybe the default capstyle in pie plots should be changed to rounded?

**Comment by bronger** [comment]
Is the PNG generated via SVG as an intermediate step?

As a side note, a workaround would be enough I think.  E.g. It would be very helpful to be able to define the form of the vertex (round, rectangular etc).

**Comment by bronger** [comment]
> Maybe the default capstyle in pie plots should be changed to rounded?

+1

**Comment by tacaswell** [comment]
No, the png is directly rasterized using Agg.

@bronger would you be willing to take a crack at changing that default?

**Comment by bronger** [comment]
No, I'm sorry.  Although I acknowledge that this is a low-hanging fruit, I would have to dive into matplotlib's source code just for this (never hacked on it).

Besides, I found PDF export as a workaround, which is imported by Inkscape loss-less.

**Comment by tacaswell** [comment]
@bronger I think these changes would be limited to the `def pie(self, ...)` method in `axes/_axes.py`.  It would be a very shallow dive.

**Comment by LindyBalboa** [comment]
I checked this out on mpl 1.5.1 and python 3.5. Setting `wedgeprops={'capstyle': 'round'}` had no effect in IE, Firefox, and Chrome. I also tested `projecting` and that did not help as either. @tacaswell I think you were right that this might not be an mpl issue.

**Comment by bronger** [comment]
Had `wedgeprops={'capstyle': 'round'}` effect for PDFs?

**Comment by LindyBalboa** [comment]
@bronger Nope, capstone didn't seem to have an effect on any of the formats as far as my standard Anaconda install goes.

**Comment by QuLogic** [comment]
I don't know what caused it, but the output appears fine when running on the `v2.x` branch. It may already be fixed.

**Comment by tacaswell** [comment]
Closed as not reproducible.
