### ISSUE TITLE
tick rotation with axes_grid1.host_subplot not working

### ISSUE THREAD

**Issue by ocehugo** [matplotlib/matplotlib#6830]
To help us understand and resolve your issue please check that you have provided
the information below.
- [1.5.1,3.5.1,OSX ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
- [pip ] How did you install Matplotlib and Python (pip, anaconda, from source ...)

When using host_subplot output as axis objects to create new spines/axes, the tick rotation changes are not executed in the plot. I assume that several other tick operations are also not being executed.

I noted this when adding several new spines/axes following http://matplotlib.org/examples/axes_grid/demo_parasite_axes2.html.

Rotation is not done even in the most basic case below :

``` python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import host_subplot
import mpl_toolkits.axisartist as AA
import numpy as np

host = host_subplot(111,axes_class=AA.Axes)
plt.subplots_adjust(bottom=0.15)
host.plot(10,10)
host.set_xticks([10.2,10.4,10.6])
host.set_xticklabels(['A','B','C'],rotation=45)
```

In the figure above A,B,C ends up not rotated.

**Comment by tacaswell** [comment]
This is hopefully due to something in axisartist / axes_grid snarfing a kwarg.  My intuition is that the fix will be easy but finding it might be tricky :stuck_out_tongue_winking_eye: .

**Comment by timlod** [comment]
This is still (or again?) the case in 3.3.0.

To reproduce, run https://matplotlib.org/3.3.0/gallery/axisartist/demo_parasite_axes2.html and use plt.xticks(rotation=45) to attempt ticklabel rotation.

**Comment by oscargus** [comment]
Spent some time digging into this without any solution, but thought it was worth writing down that the `Text` objects obtained from `get_xticklabels` do have the correct rotation.
