### ISSUE TITLE
Which image formats to build in docs.

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#6835]
When I did #6823 and changed the dpi I did not remember that we had merged #5677
which changed the default HTML docs to build svg examples rather than pdf examples. Apparently  #5677 was not backported to 2.x

There are several questions.

* Should the change to use SVG's be backported? 
* The svg's are build with a dpi of 72? Why? Should that not match the default dpi?

**Comment by efiring** [comment]
The discussion on #5677 noted that the backport needed to await checking of the svg results.  My first random check, http://matplotlib.org/devdocs/examples/lines_bars_and_markers/scatter_with_legend.html, shows a problem.  Notice that the legend is plotting the symbol twice with slightly different sizes in the svg, but not in the png.
Conclusion: the necessary review of the svg output probably has not been done.  I think that some comparisons of rendering time between svg and pdf is also needed.  In the example above, the svg seems rather slow, much slower than the original pdf  here: http://matplotlib.org/examples/lines_bars_and_markers/scatter_with_legend.html.

Overall, at this point I suspect that switching to svg is just going to make more work and degraded performance.  The only benefit is sharper plots in the web page, compared to the present png.

**Comment by QuLogic** [comment]
On the [axisartist page](http://matplotlib.org/devdocs/mpl_toolkits/axisartist/users/axisartist.html), several axis lines appear to be too thick. This may be an SVG renderer issue. For example, see [SVG](http://matplotlib.org/devdocs/mpl_toolkits/axisartist/figures/axis_direction_demo_step02.svg) vs. [PNG](http://matplotlib.org/devdocs/mpl_toolkits/axisartist/figures/axis_direction_demo_step02.png) where the left line appears correct, but the right line is a bit thicker.

**Comment by QuLogic** [comment]
The [pcolor images](http://matplotlib.org/devdocs/examples/pylab_examples/pcolor_demo.html) have that unfortunate edge thing that shows up in PDFs, which I don't think is a great thing to show by default.

**Comment by efiring** [comment]
On 2016/07/25 10:39 PM, Jens Hedegaard Nielsen wrote:
> There are several questions.
>
>   * Should the change to use SVG's be backported?

I think the answer is a clear "No!"  I'm inclined to recommend reverting 
the change in master--maybe after taking advantage of the temporary 
change to find problems in the svg backend.  Overall, I don't think svg 
is a very useful format.  It's not as fast and reliable in web pages as 
png, and there aren't many applications in which one can use it.

**Comment by jenshnielsen** [comment]
Implemented in #6862
