### ISSUE TITLE
Figures not showing in interactive mode with macosx backend

### ISSUE THREAD

**Issue by julietbravo** [matplotlib/matplotlib#6838]
Matplotlib 1.5.1, Python 3.5.2, ipython 5.0.0, OS X El Capitan; Python3 installed with Homebrew, matplotlib through Pip. Empty `matplotlibrc` file, except for `backend : macosx`

When creating a figure in non-interactive mode in ipython, matplotlib behaves as expected:

    import matplotlib.pylab as pl
    pl.ioff()
    pl.figure()
    pl.show()

Gives me a nice on-screen figure. When I do the same in interactive mode (change `ioff()` to `ion()`) I get no on-screen figure, nothing. Exact the same happens when I use `pl.ioff()` combined with `pl.show(block=False)`, i.e. I again get no on-screen figure.

Could this be a bug in matplotlib?

**Comment by julietbravo** [comment]
Seems to be related to ipython 5.0.0; I downgraded it to 4.2 and now everything works again as expected

**Comment by afvincent** [comment]
Do you use the magic `%matplotlib` in IPython (or launch it with `ipython --matplotlib` or similar)?

**Comment by julietbravo** [comment]
No, I simply launch `ipython` and run the exact code shown above

**Comment by julietbravo** [comment]
Ah, with `%matplotlib` it also works. I was pointed to this: https://github.com/ipython/ipython/issues/9811 and https://github.com/matplotlib/matplotlib/pull/6734 from StackOverflow,  so it seems to be a known problem.

**Comment by tacaswell** [comment]
Closing as not a bug.
