### ISSUE TITLE
SVG backend: anomaly in gallery scatter legend

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6845]
From the devdocs:
1) http://matplotlib.org/devdocs/examples/lines_bars_and_markers/scatter_with_legend.html
Compare the legend in the svg version to the png version. At least on my system (OSX, Firefox or Chrome), the circles in the svg legend appear to consist of a smaller disk inside a larger one.  
2) The Imagemagick "convert" program can't handle our svg file.

**Comment by efiring** [comment]
Here is a conversion of a size-reduced screen-grab to show the problem:
![scatter_svg](https://cloud.githubusercontent.com/assets/85125/17167284/0331d704-5378-11e6-93db-99334dc84c24.png)

**Comment by afvincent** [comment]
If one looks very closely (I was playing with it under Inkscape), it seems that the legend handles are actually made of three disks: there is a very tiny one in the middle of each handle (weirdly, the blue one is a bit bigger than the red and green ones…).

**Comment by jenshnielsen** [comment]
It is in the pdf version too http://matplotlib.org/devdocs/mpl_examples/lines_bars_and_markers/scatter_with_legend.pdf

**Comment by mdboom** [comment]
There is code in `legend_handles.py` `HandlerRegularPolygonCollection.get_sizes` which when `numpoints` (number of legend points) is < 4, returns the min, max and avg(min, max) of the scatter points.  Hence, even though `numpoints` is 1 and we only have a single point location, we're drawing three points on top of each other.

There is a secondary bug which is that the behavior of `draw_path_collection` doesn't match between Agg and the vector backends.  I'll fix that as well while I'm in there.

**Comment by QuLogic** [comment]
There's only one scatter marker in the legend on current v2.x / master; I think it was fixed by #7214.

@efiring Is there still a problem with ImageMagick? I don't seem to be able to reproduce.

**Comment by NelleV** [comment]
Can we close this ticket?

**Comment by tacaswell** [comment]
Yes, the pdf link now looks correct http://matplotlib.org/devdocs/mpl_examples/lines_bars_and_markers/scatter_with_legend.pdf

We do not make svg for the website anymore (do not recall why we dropped that though).

**Comment by afvincent** [comment]
@tacaswell Dropping SVG format for the website pictures was related to #6835 .
