### ISSUE TITLE
Tick labels containing the digit "1" slightly misaligned in some plot exports

### ISSUE THREAD

**Issue by jotasi** [matplotlib/matplotlib#6847]
Hi,

Hopefully, my issue is not too unimportant and this is the right place to ask about it.
I experienced a minor problem, when using the `plt.savefig` function to save my plots to either `.png` (and also for `.jpg`) with a high resolution (300 dpi). If I specified to not use the standard font but set a font family to serif (`plt.rcParams["font.family"] = "serif"`) all x-axis labels containing the digit "1", that I tried, namely `0.1` and `1.0` are misaligned in y-direction by 1 pixel. It's not noticeable most of the time, but when one has two subplots next to each other and the `1.0` label of one plot and the `0.0` label of the other are really next to each other, the labels look off.

As a minimal working example you can run:

```
import matplotlib
import matplotlib.pyplot as plt

plt.rcParams["font.family"] = "serif"

fig, ax = plt.subplots(1, 1)
plt.savefig("minimalExample.png", dpi=300)
```

and then zoom in onto `0.8` and `1.0`. You can see the difference best, when you compare the decimal points.

Here is also a picture of the zoom and one of the two subplots, where I saw the problem first:

![minimalexamplezoom](https://cloud.githubusercontent.com/assets/10883104/17182410/ae3d0988-5423-11e6-8337-716b6d19420b.png)

![minimalexampletwoplots](https://cloud.githubusercontent.com/assets/10883104/17182156/dc4b83dc-5422-11e6-86e0-cd62d9d56241.png)

I tried this on a Linux machine with `python` version `2.7.9` and `matplotlib` versions `1.4.2` installed from `debian` repositories and `1.5.1` installed via `pip`.
Generally, this is not a big problem, though, as one can use alternate formats like `pdf` or `eps` if one really cares about a one pixel misalignment. Nonetheless, I thought, I might let you know. Feel free to close/delete this issue, if you consider it as too unimportant (or if this is the wrong place to raise it, as it might just be an external libraries fault).

Best (and thanks for this great package),

Jonathan

**Comment by tacaswell** [comment]
This is still an issue and appears to be font dependent.

with dejavu serif (using "serif" just means "find font in this list", on my system the one it picks in dejavu):

![image](https://user-images.githubusercontent.com/199813/227983455-4ac99f0d-ab1d-465f-972e-4a47d7319fa1.png)

with dejavu sans:

![image](https://user-images.githubusercontent.com/199813/227983756-c6b9a38d-97b2-451b-b85a-924f5f4615bc.png)


Speculation on what could be going on here:

 - inherent issues with pixel snapping
 - we are doing something wrong computing the bounding boxes
 - font metrics in the font could be wonky / wrong
 - the '1' is just a pixel bigger 

It should also be noted that the x-axis ticks have vertical alignment of "top" so if the bounding boxes are varying at all I would expect the offsets to appear at the bottom.
