### ISSUE TITLE
nbagg backend incredibly laggy in IPython notebook

### ISSUE THREAD

**Issue by alexanderwhatley** [matplotlib/matplotlib#6850]
- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
  Windows 10, Matplotlib 1.5.1, Python 3.5.2

I wrote some code for allowing the user to draw rectangles in a blank matplotlib graph using the nbagg backend in an IPython notebook, and it is incredibly laggy. Is this a current limitation, or is this perhaps a bug with the library? Here is the code I have:

```
import matplotlib
matplotlib.use("nbagg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from ipywidgets.widgets import Button
from IPython.display import display

class Test(object):
    def __init__(self):
        plt.ion()
        self.figure = plt.figure()
        self.ax = self.figure.gca()
        self.rect = Rectangle((0,0), 0, 0, color = '0', fill = False)
        self.x0 = None
        self.y0 = None
        self.x1 = None
        self.y1 = None
        # Graph interaction
        self.ax.add_patch(self.rect)
        self.ax.figure.canvas.mpl_connect('button_press_event', self.on_press)
        self.ax.figure.canvas.mpl_connect('button_release_event', self.on_release)
        self.ax.figure.canvas.mpl_connect('motion_notify_event', self.on_motion)

    def on_motion(self, event):
        if self.is_pressed:
            self.x1 = event.xdata
            self.y1 = event.ydata

            self.rect.set_width(self.x1 - self.x0)
            self.rect.set_height(self.y1 - self.y0)
            self.rect.set_xy((self.x0, self.y0))
            self.rect.figure.canvas.draw()

    def on_press(self, event):
        self.is_pressed = 1
        self.x0 = event.xdata
        self.y0 = event.ydata
        self.rect.set_visible(True)

    def on_release(self, event):
        self.is_pressed = 0
        self.ax.scatter(self.x_inside, self.y_inside, c = "red")
        self.figure.canvas.draw()
        self.rect.set_visible(False)
        self.rect.figure.canvas.draw()


test = Test()
```

**Comment by tacaswell** [comment]
Remove all of the explicit calls to `draw` (or at least change them to `draw_idle`).

Please try the 2.0.0b3 beta, there are some speed improvements on that branch as well.

The killer is probably fully re-drawing the figure on every mouse motion.  The toolbar has a `draw_rubberband` (which is what `zoom` uses) which draws the rectangle using the 'native' tools and is much more performant.

**Comment by watkinrt** [comment]
Does anyone know what makes the nbagg back so much slower than the other aggs with respect to event handling? I'm trying to do a similar draggable (motion_notify_event) interaction, but the latency makes it almost unusable. I've tried using blitting and draw_idle commands to speed things up, but they only help a little (at least, using Matplotlib 2.0.0).

**Comment by tacaswell** [comment]
I suspect the latency is because the communication happening over a web-socket rather than within a process.

**Comment by thomasaarholt** [comment]
Is there anyone working on improving speeding up the notebook backend? The notebook backend is wonderful, but on Windows it is quite slow. I find that it is slower here than it is on Linux.

**Comment by tacaswell** [comment]
Having someone pick up and finish https://github.com/matplotlib/matplotlib/pull/4290 may help with this.
