### ISSUE TITLE
PyQt5 (v5.7) backend - TypeError upon calling figure()

### ISSUE THREAD

**Issue by peynmurray** [matplotlib/matplotlib#6853]
Windows 10
Python 3.5.2
PyQt 5.7
Matplotlib 1.5.1

The following code throws a TypeError when run. It appears that there's a connection error when trying to connect the NavigationToolbar2QT.message[str] signal to the FigureManagerQT._show_message() slot.

```
import matplotlib
matplotlib.use("Qt5Agg")
from matplotlib.pyplot import *

fig = figure()
show()
```

**Comment by tacaswell** [comment]
attn @anntzer (as I think you are using Qt5 due to your recent bug reports)
