### ISSUE TITLE
Update URL for links to ggplot

### ISSUE THREAD

**Issue by andreas-h** [matplotlib/matplotlib#6859]
In many places in the documentation, when referring to the original ggplot library, the URL http://had.co.nz/ggplot/ is given for a link.  However, this URL seems to be obsolete, I get a 404 error.  The new website seems to be http://ggplot2.org/.  Maybe it would be a good idea to change the mpl docs accordingly.

Is there some macro defined somewhere, or do we need to grep on the whole source tree?

**Comment by tacaswell** [comment]
I think this is already done in the source, but the main pages have not been re-built see #6678

**Comment by tacaswell** [comment]
Can you check the docs at http://matplotlib.org/devdocs and http://matplotlib.org/2.0.0b3 ?

**Comment by QuLogic** [comment]
Based on #6981 getting filed, I'd say this change has not been made everywhere yet.

**Comment by tacaswell** [comment]
Because the main-page docs have not been re-built yet.  This was closed by #6861

**Comment by QuLogic** [comment]
No, #6861 only covers the example files; the prose still contains these links.

**Comment by jenshnielsen** [comment]
Closed by #6986
