### ISSUE TITLE
Add release dates to what's new page

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6864]
It would be helpful for debugging/git-archaeology purposes if the what's new page (http://matplotlib.org/users/whats_new.html) listed the dates for each release.  I can obviously look them up on the git log and add them retrospectively, but I think there's also some machinery involved in merging the what's new entries so perhaps it should be added there too for later releases?

**Comment by tacaswell** [comment]
The machinery recently has been me + emacs :wink: 

We probably should adopt / adapt the tooling ipython uses for this, but the recent releases I have made the penny-wise/pound-foolish choice to just do it (rather than understand all of the knobs on their tool).
