### ISSUE TITLE
examples/api/skewt.py is not displaying the right part of the grid by default

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6873]
mpl2.0b3/master Qt5Agg numpy1.11.1 Python 3.5.1

skewt.py is missing the left part of the grid by default:
![skewt](https://cloud.githubusercontent.com/assets/1322974/17279011/a175dbcc-571f-11e6-90ae-c20772fec3b8.png)
Triggering a redraw (eg by panning the axes) solves the issue, but it may be something deeper?

**Comment by dopplershift** [comment]
This was relying upon the upper spine's `_adjust_location()` method to update an interval on the xaxis for that upper range (ewww....); for some reason it wasn't getting called on that initial draw, but I'm not convinced that's a bug. My original design for handling that update was just....so bad and brittle, violating so many things, it needed to be redone.

I've got a cleaned up version working now that makes a lot more sense.
