### ISSUE TITLE
SVG backend: test_determinism

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6882]
I do not like the fact that it stores temporary files in the cwd (it is ugly way and unrandomized file names are not thread safe).

Possible solutions:
- Use `TemporaryFile`
- Use stdout, pipe or shared memory for interprocess communication
- Just make all the checks in the tests process

If I understand correctly the purpose of the subprocess call -- it is used to check if the outputs of multiple python runs are the same, but they will likely be the same, because the single source of difference is a random seed which is disabled by `-R` key to the python interpreter. I think that three consecutive calls to `savefig` will do the same job as `_test_determinism` (with the help of `_test_determinism_save`) does currently.

**Comment by tacaswell** [comment]
We should probably drop the `-R` than as the point of that was to account for random dictionary order.

**Comment by Kojoley** [comment]
Yes, removing the `-R` key will make the test at least working as intended, but I would like to rewrite it with `multiprocessing`. Here is evidence that dict keys order will be different in every process:
```python
def get_keys():
   somedict = {str(i): i
               for i in range(10)}
   return list(somedict.keys())

def helper(pipe):
   arr = get_keys()
   pipe.send(arr)


if __name__ == '__main__':
    from multiprocessing import Process, Pipe

    results = []
    for _ in range(3):
        pipe_in, pipe_out = Pipe()
        proc = Process(target=helper, args=(pipe_in,))
        proc.start()
        results.append((proc, pipe_out))

    for proc, pipe in results:
        proc.join()
        print(pipe.recv())
```

Result:
```
['9', '1', '6', '5', '3', '8', '0', '7', '2', '4']
['3', '4', '7', '9', '1', '2', '0', '8', '6', '5']
['2', '1', '7', '6', '3', '0', '4', '5', '8', '9']
```

Such solution will faster too, because images will be rendered in child processes simultaneously.

**Comment by tacaswell** [comment]
:+1:

**Comment by QuLogic** [comment]
`test_determinism` uses `stdout` now.
