### ISSUE TITLE
Check if ~/.matplotlib/ is a symlink to ~/.config/matplotlib/

### ISSUE THREAD

**Issue by nbrunett** [matplotlib/matplotlib#6885]
Hi

I was wondering if it would be reasonable to have __init__.py check if ~/.matplotlib/ is a symbolic link to ~/.config/matplotlib/ before issuing the UserWarning about that location being deprecated. I unfortunately have to work with a software package that comes bundled with it's own copy of matplotlib which is version 1.1.0. That means it looks for the configuration in ~/.matplotlib/. I use 1.5.1 for all of my other work and keep my configuration files in ~/.config/matplotlib/. I thought I was being clever when I just made a symlink ~/.matplotlib/ that points to ~/.config/matplotlib/ but now I get UserWarnings whenever I use matplotlib outside of that other software package.

I'm running on linux (Mageia 6), Python version 2.7.12 and both Matplotlib and Python were installed with Anaconda.

If this is too much of an edge case and would just clutter the code I'd understand.

Thank you.

**Comment by tacaswell** [comment]
Looks like we only run that check in linux.  I think we would merge a PR to add that check.

  Maybe it is time to just stop checking there?

Out of curiosity, what is the package that has bundled 1.1.0?

**Comment by nbrunett** [comment]
The package is a radio astronomy data reduction and analysis suite called [CASA](https://casa.nrao.edu/).

**Comment by anntzer** [comment]
I vote for stopping to check there starting from 2.0 (or 2.1).  ~/.matplotlib has been deprecated (with a warning) since 1.3, so 3 years and 3 minor versions.

**Comment by tacaswell** [comment]
@anntzer That sounds reasonable for 2.1

**Comment by anntzer** [comment]
Closed by #7195, unless I am mistaken.
