### ISSUE TITLE
Backend-dependent behavior upon ctrl-c

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6897]
When ctrl-c'ing a script (with the focus on the terminal, not the window), different backends exhibit different behavior:
- Qt5Agg quits the script (with a nonzero return value).
- Gtk3Cairo waits until the window is focused again, prints a traceback due to a KeyboardInterrupt in `on_draw_event`, and the canvas is lost.  It is restored by triggering redrawing, e.g. by panning.
- TkAgg waits until the window is focused again, and quits (with a nonzero return value) while printing a traceback due to a KeyboardInterrupt in `mainloop`.

Personally, I prefer the Qt behavior.

**Comment by tacaswell** [comment]
What is the blocking state of the event loops in these cases?

**Comment by Equidamoid** [comment]
@tacaswell How to check it?

**Comment by jclevesque** [comment]
Same here. MacOSX backend prints a traceback and then ignores Ctrl-C. TkAgg works as intended (i.e., it kills the program, although it requires me to focus the window).

**Comment by tacaswell** [comment]
Is this in a blocking `plt.show()`?

I think this needs a simple test case and a systematic survey of the behavior across backends and across platforms.

**Comment by jclevesque** [comment]
This causes it for me. 

```
import matplotlib
matplotlib.use('MacOSX')
import matplotlib.pyplot as plt

for i in range(10):
    plt.figure()
    plt.title(i)
    plt.show()
```


I press Ctrl-C in the terminal while figure is displaying and the program keeps looping. Traceback is printed when I click on the window, but the exception is not raised.
