### ISSUE TITLE
Add API function for removing legend label from graph

### ISSUE THREAD

**Issue by alexanderwhatley** [matplotlib/matplotlib#6901]
Right now, there does not appear to be an API function for removing a legend label from a matplotlib graph. This could be useful for say an interactive graph.

**Comment by fariza** [comment]
You can do it by

```
for leg in list(fig.legends):
                leg.set_visible(state)
```

Where state is `True/False`

**Comment by fariza** [comment]
I am closing this issue, if the answer is not what you were looking for, please reopen the issue
