### ISSUE TITLE
RuntimeError('Invalid DISPLAY variable') - With docker and django

### ISSUE THREAD

**Issue by francica** [matplotlib/matplotlib#6903]
- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...) 1.5.1
- [ ] How did you install Matplotlib and Python -> pip

- [ ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.
->  work on my windows and pycharm,but after I move it to a ubuntu and use docker to run it, it does not work.

Stackoverflow description:

http://stackoverflow.com/questions/38776267/docker-matplotlib-runtimeerror-invalid-display-variable/38776743#38776743

> 
> > Traceback (most recent call last):
>   File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/code/fileUpload_app/views.py", line 174, in msa_result
>     result1 = generate_hist(db, **processing_dict)
>   File "/code/fileUpload_app/post_processing.py", line 182, in generate_hist
>     fig1 = plt.figure()
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
>     **kwargs)
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
>     return new_figure_manager_given_figure(num, thisFig)
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
>     canvas = FigureCanvasQTAgg(figure)
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
>     FigureCanvasQT.__init__(self, figure)
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
>     _create_qApp()
>   File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
>     raise RuntimeError('Invalid DISPLAY variable')
> RuntimeError: Invalid DISPLAY variable

My code:
```

import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

def generate_hist(db, **kwargs):


    fig1 = plt.figure()

    hist = mat2[0, 0:pin_num]

    fig1 = plt.hist(hist)

    plt.savefig("fileUpload_app/static/img/result/hist.jpg")
```

**Comment by WeatherGod** [comment]
That isn't the code you used to generate this traceback, it has undefined
variables and would never execute `generate_hist()`. (the line numbers in
the traceback also does not correspond to your code). Having the
`mpl.use('agg')` should prevent this very issue, but for some reason,
something else is causing the backend to be qt4agg instead of agg. This
could be caused by other imports. Looking at your traceback, I don't envy
your situation as it looks like this is an app that is triggered by an
existing python environment of some sort, so it could very well be that
that environment already had matplotlib.pyplot called before the backend
could be set appropriately.

**Comment by francica** [comment]
Hi this is actually a django project. And i call this py file from views,py. I checked there is nothing related to matplotlib in views.py

in views.py i call:
```
from post_processing import generate_pic, circum_mean, set_stat, generate_hist, measurement_stat, generate_measurement_pic, circ_stat

result1 = generate_hist(db, **processing_dict)
```


The full version of my code is like:

```
import MySQLdb
import json
import database
import numpy as np
import seaborn as sns
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import math
import os


def generate_hist(db, **kwargs):
    #print "I am here"
    if kwargs['set_id']:

        user = kwargs.get('user', 'no_user')
        set_id = kwargs['set_id']
        set_id = int(set_id)

        # TODO

        mat2 = get3DresultMean(db, set_id)

        users = getUsers(db, set_id)

        # either 41 or 46

        pin_num = mat2.shape[1] - 1
        fig1 = plt.figure()

        hist = mat2[0, 0:pin_num]
        for i in range(1, len(mat2)):
            hist = np.concatenate((hist, mat2[i, 0:pin_num]), axis=0)
        # distMean = mat2[0,0:pin_num-1]
        fig1 = plt.hist(hist)
        plt.title("Pin distance of all user measurements")
        # print os.getcwd()
        plt.xlabel('Pin Number', fontsize=14)
        plt.ylabel('Frequency', fontsize=14)
        plt.savefig("fileUpload_app/static/img/result/hist.jpg")
        return "success"
    else:
        return "fail to generate historgram"

```

**Comment by efiring** [comment]
On 2016/08/04 11:44 AM, francica wrote:
> Hi this is actually a django project. And i call this py file from
> views,py. I checked there is nothing related to matplotlib in views.py

Your are importing seaborn, which imports matplotlib.  I don't know 
whether it imports pyplot or otherwise sets a backend.

Eric

**Comment by tacaswell** [comment]
99% sure that seaborn imports `pyplot`, set the backend before importing it.

Or try setting the `MPLBACKEND` or the system-wide matplotlibrc to use Agg so you do not have import-order race conditions.

http://matplotlib.org/1.5.1/users/whats_new.html#new-backend-selection / http://matplotlib.org/1.5.1/faq/environment_variables_faq.html#envvar-MPLBACKEND

**Comment by francica** [comment]
You guys are right! Thanks
