### ISSUE TITLE
matplotlib window freezing / hanging on close in ipython with OS X

### ISSUE THREAD

**Issue by flipdazed** [matplotlib/matplotlib#6908]
This problem has affected everyone I work with that updated to the _currently latest_ versions below. This only affects `ipython` plots. The regular `python` terminal is unaffected by this issue.

Also on posted on StackOverflow: http://stackoverflow.com/q/38801285/4013571
### Reproduction

```
import matplotlib.pyplot as plt
plt.plot()
# manually close the window with `x`
```

Attempting `plt.close()` also disables the three native `OS X` window buttons
### Workaround

Us the shortcut for closing `ipython` and then cancel the exit

```
^+d
Do you really want to exit ([y]/n)? n
```
### Versions

```
ipython 5.0.0
matplotlib 1.5.1 
OS X El Capitan Version 10.11.6
```
### Related
- http://stackoverflow.com/questions/34108696/cannot-manually-close-matplotlib-plot-window
- https://github.com/matplotlib/matplotlib/issues/5624

**Comment by jenshnielsen** [comment]
As far as I know this only affects the OSX backend so as a work around you can use another backend. I.e. 

```
%matplotlib QT4
```
or
```
%matplotlib QT5
```
or
```
%matplotlib tk
```

**Comment by jenshnielsen** [comment]
On the IPython side  ipython/ipython#9659

**Comment by jenshnielsen** [comment]
I think the problem is that `wait_for_stdin` is no longer called automatically with the new prompt-toolkit input hook. 

This used to be set as a regular python input hook with 

```
PyOS_InputHook = wait_for_stdin;
```

**Comment by CANMoose** [comment]
This affects me as well and can confirm that changing the backend away from MacOSX is a workaround.

**Comment by REMeyer** [comment]
Update: The Qt4 backend is now causing incredible lag in the ipython console after plotting is invoked. So it is not as nice of a workaround anymore. Doesn't seem like theres been a solution to this issue yet.

**Comment by tacaswell** [comment]
can you try updating ipython?  There were some recent changes to how the event loop integration is handled.

**Comment by jenshnielsen** [comment]
This was solved for me a long time ago with an update to ipython fixing the event loop integration with prompt-toolkit. @REMeyer If you have a new issue with PyQt5 can you please open a new issue for that

**Comment by fabki00** [comment]
Yes, I can confirm that updating ipython fixes this problem.

**Comment by tigerk0430** [comment]
I found it.


in my case, I restarted cmd as an administrator then it works!

**Comment by tacaswell** [comment]
@tigerk0430 Having to run python as an administrator suggests that your installation is broken.  In general doing _anything_ other than administration with elevated permissions is a very bad idea.

**Comment by sebma** [comment]
This also works : 

```python
%matplotlib auto
```
