### ISSUE TITLE
freetype build won't become local

### ISSUE THREAD

**Issue by prinsherbert** [matplotlib/matplotlib#6911]
I have a git checkout of matplotlib on which I would like to run the tests. In order to do so I have set `local_freetype=True` in setup.cfg and ran the following in a virtual environment:

	(matplotlib) matplotlib$ python3.5 setup.py build
	============================================================================
	Edit setup.cfg to change the build options

	BUILDING MATPLOTLIB
		    matplotlib: yes [2.0.0b3+1919.g2dfef6a]
		        python: yes [3.5.1+ (default, Mar 30 2016, 22:46:26)  [GCC
		                5.3.1 20160330]]
		      platform: yes [linux]

	REQUIRED DEPENDENCIES AND EXTENSIONS
		         numpy: yes [version 1.11.1]
		           six: yes [using six version 1.10.0]
		      dateutil: yes [using dateutil version 2.5.3]
		   functools32: yes [Not required]
		  subprocess32: yes [Not required]
		          pytz: yes [using pytz version 2016.6.1]
		        cycler: yes [using cycler version 0.10.0]
		       tornado: yes [tornado was not found. It is required for the
		                WebAgg backend. pip/easy_install may attempt to
		                install it after matplotlib.]
		     pyparsing: yes [using pyparsing version 2.1.5]
		        libagg: yes [pkg-config information for 'libagg' could not
		                be found. Using local copy.]
		      freetype: yes [Using local version for testing]
		           png: yes [version 1.2.54]
		         qhull: yes [pkg-config information for 'qhull' could not be
		                found. Using local copy.]

	OPTIONAL SUBPACKAGES
		   sample_data: yes [installing]
		      toolkits: yes [installing]
		         tests: yes [using nose version 1.3.7 / using unittest.mock]
		toolkits_tests: yes [using nose version 1.3.7 / using unittest.mock]

	OPTIONAL BACKEND EXTENSIONS
		        macosx: no  [Mac OS-X only]
		        qt5agg: yes [installing, Qt: 5.7.0, PyQt: 5.7.0; PySide2 not
		                found]
		        qt4agg: yes [installing, Qt: 5.5.1, PyQt: 5.5.1; PySide not
		                found]
		       gtk3agg: no  [Requires pygobject to be installed.]
		     gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
		        gtkagg: no  [Requires pygtk]
		         tkagg: yes [installing; run-time loading from Python Tcl /
		                Tk]
		         wxagg: no  [requires wxPython]
		           gtk: no  [Requires pygtk]
		           agg: yes [installing]
		         cairo: no  [cairocffi or pycairo not found]
		     windowing: no  [Microsoft Windows only]

	OPTIONAL LATEX DEPENDENCIES
		        dvipng: yes [version 1.15]
		   ghostscript: yes [version 9.18]
		         latex: yes [version 3.14159265]
		       pdftops: yes [version 0.41.0]

	OPTIONAL PACKAGE DATA
		          dlls: no  [skipping due to configuration]

	running build
	running build_py
	copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.linux-x86_64-3.5/matplotlib/mpl-data
	UPDATING build/lib.linux-x86_64-3.5/matplotlib/_version.py
	set build/lib.linux-x86_64-3.5/matplotlib/_version.py to '2.0.0b3+1919.g2dfef6a'
	running build_ext
	(matplotlib) matplotlib$ PYTHONPATH=build/lib.linux-x86_64-3.5/ python3.5 tests.py --nocapture
	Python byte-compilation optimization level: 0
	/home/herbert/Repositories/matplotlib/build/lib.linux-x86_64-3.5/matplotlib/__init__.py:1580: UserWarning: matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below. Expected freetype version 2.6.1. Found freetype version 2.6.1. Freetype build type is not local
	  "" if ft2font.__freetype_build_type__ == 'local' else "not "

as you can see, the build command reports that the used freetype should be local, but when running the tests, they are not local as reported by the error. Why is this the case?

**Comment by prinsherbert** [comment]
I ran `python3.5 setup.py clean` before, but this was not enough. `rm -rf build/` however, and then repeating the above seems to work though. This is not what I would expect.

**Comment by jenshnielsen** [comment]
We dont implement `setup.py clean` it's inherited from `distribute`/`setuptools` and as far as I know generally known to be broken. I don't think there is much we can do about that apart from perhaps replacing it with a no op that prints a warning.

**Comment by jenshnielsen** [comment]
It seems like if you pass all to `setup.py clean` it does the right thing. I.e. `python setup.py clean --all`
See 
http://stackoverflow.com/questions/17804185/what-does-setup-py-clean-exactly-do

**Comment by tacaswell** [comment]
`git clean -xfd` is your (some what dangerous) friend :imp:

**Comment by prinsherbert** [comment]
For me the problem is solved, and this issue may be closed. Thank you.
