### ISSUE TITLE
Cant get currency from yahoo finance with matplotlib

### ISSUE THREAD

**Issue by mushketer888** [matplotlib/matplotlib#6913]
Matplotlib cant get currency data from Yahoo Finance...
Symbol for EUR/USD is EURUSD=X.
But using this ticket it gives 404 Error.
Matplotlib version: 1.5.1

example:
quotes = quotes_historical_yahoo_ochl('EURUSD=X', date1, date2)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by tacaswell** [comment]
Does this fail for all symbols or just this one?  My two guesses are either yahoo changed the url under us or the `=` is going to require some extra escaping.

In either case, help sorting this out would be greatly appreciated.

**Comment by bcongdon** [comment]
I did a bit of sniffing around in `finance.py`:
* Doing a percent escape on the `=` still yielded a 404.
* 'Normal' symbols, such as `AAPL` still scrape fine.
* Symbols with non-alphanumeric characters like `^GSPC` still scrape fine.

(This suggests that nothing is wrong with the matplotlib interface with Yahoo Finance)

By my best guess, it looks like [internally](http://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote), Yahoo is using a different symbol for these exchange rate symbols. So, `EURUSD=X` becomes `EUR=X`

Calling `quotes_historical_yahoo_ochl('EUR=X', date1, date2)` works as expected.

**Comment by tacaswell** [comment]
@bcongdon Thanks!

Closing as this does not look like a bug in mpl.  @mushketer888 If you disagree and think that this _is_ a bug in mpl please ping to have this re-opened.

**Comment by HQ01** [comment]
Hi @tacaswell,

Seems that matplotlib fails to fetch data from yahoo Finance.

Code : just the example code in finance.py

fh = fetch_historical_yahoo('^GSPC', (2000, 1, 1), (2001, 12, 31))

Error : 

HTTPError: HTTP Error 404: Not Found

Matplotlib version : 2.0.0

Maybe Yahoo changed the url format?

**Comment by hajderr** [comment]
Can confirm with following virtualenv

```
 ./bin/pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2017.4.17)
chardet (3.0.3)
cycler (0.10.0)
idna (2.5)
matplotlib (2.0.2)
numpy (1.13.0)
pandas (0.20.2)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
requests (2.17.3)
requests-cache (0.4.13)
setuptools (36.0.1)
six (1.10.0)
urllib3 (1.21.1)
wheel (0.29.0)
```

**Comment by tacaswell** [comment]
It is likly that yahoo did change it's url.

This bug should be re-reported against https://github.com/matplotlib/mpl_finance

**Comment by bcongdon** [comment]
Looks like the Yahoo Finance's 'real-chart' subdomain is gone. (http://real-chart.finance.yahoo.com/)
