### ISSUE TITLE
"Error: local variable 'xdata' referenced before assignment" in legend_handler.py

### ISSUE THREAD

**Issue by pfaion** [matplotlib/matplotlib#6921]
Hi everyone,
I made a stupid typo and generated a legend for my plot with half a numpoint

`plt.legend(numpoints = 0.5)`

which obviously makes no sense. But finding the error took some time due to the stupid error message and the original issue not being handles correctly here:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/legend_handler.py#L151

If you check for being an integer in the if-statement and throw a more readable error if not (e.g. "Number of points has to be an integer", or similar) that would be great.

Cheers
Patrick

**Comment by tacaswell** [comment]
@pfaion would you be willing to take a crack at that?  You seem to have a good idea of what needs to be done.

**Comment by phobson** [comment]
closed via #8478
