### ISSUE TITLE
imshow does not immediately update shared axes

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6922]
On master:

``` python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax1 = fig.add_axes([0.1, 0.1, 0.2, 0.2])
ax2 = fig.add_axes([0.35, 0.35, 0.6, 0.6], sharex=ax1, sharey=ax1)
ax3 = fig.add_axes([0.1, 0.35, 0.2, 0.6], sharex=ax1, sharey=ax1)
ax1.plot([1, 10])
ax2.plot([2, 20])
# ax3.plot([3, 30])
ax3.imshow(np.random.randn(10, 10))

plt.show()
```

The two axes with the lines do not react to the changed xlim and ylim from the `imshow` call until one forces a redraw, such as by resizing the window or using a zoom tool.
This problem turned up in #6759.

**Comment by jenshnielsen** [comment]
Does it apply to 2.x too?

**Comment by efiring** [comment]
On 2016/08/07 9:01 PM, Jens Hedegaard Nielsen wrote:
> Does it apply to 2.x too?

Yes, I checked just now with the latest 2.x and the result is the same.

**Comment by efiring** [comment]
Possibly related to #6890.

**Comment by efiring** [comment]
Unfortunately, applying #6890, at least in its present form, does not solve the problem.

**Comment by efiring** [comment]
The behavior is the same in mpl 1.5.1, so it is not a regression.  I don't consider it a blocker. I'm going to shift the milestone.

**Comment by dstansby** [comment]
This looks fixed on master to me; feel free to re-open if it's still a problem.
