### ISSUE TITLE
Docstring section "Other Parameters" not rendering with rest of table

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#6924]
It has been bothering me that in general, kwargs are not very uniform at all in the docs. In many places they are listed after a simple "Addition keyword arguments... : ". Numpydoc does allow for the section Other Parameters (underscored with dashes) but it does not seem to render properly with the Parameters and Returns section table. The Other Parameters section doesn't seem to actually be used in _the_ numpy docs. However, there are several instances of it in mpl/axes/_axes.py.

Looking at the html in a browser inspector, you can see that Parameters and Returns are the header to a `<tr>` and the contents are in the respective `<td>`. However, with Other Parameters, the contents are being inserted into a new `<tr>` _following_ the Other Parameters row.

**Comment by jenshnielsen** [comment]
I agree, In general the docs could use a lot or work and we should be better at settling on a standard for how to format the doc strings.

I guess there are two perhaps solutions to the specific problem of `Other Parameters`. 

* We can probably submit a PR to numpy doc fixing this. Since it's not used in numpy it's probably just a bug.
* Rewrite the docs to not use other parameters. I have cleaned out a few instances where other non numpy doc compatible headers where used. Like `additional parameters` or similar
* Perhaps switching from numpydoc to sphinx napoleon will fix this. I think there is a pr for that somewhere. But that has it's own issues as far as I remember

**Comment by QuLogic** [comment]
> Perhaps switching from numpydoc to sphinx napoleon will fix this. I think there is a pr for that somewhere. But that has it's own issues as far as I remember

That's #5743.

**Comment by LindyBalboa** [comment]
@QuLogic So is that something that NelleV has taken over or...? Trying to track the progression of that PR has me a little confused.

**Comment by QuLogic** [comment]
Sorry; didn't seem to have replied here. I don't think @NelleV took over, but just accidentally tagged that PR in some commits. Since it's now going in 2.1, I was holding off until 2.0 was out. But of course, that was before 2.0 took an extra 3-4 months...

**Comment by tacaswell** [comment]
*an extra 11 months

@mdboom and I really thought we could do it in a weekend.....

**Comment by NelleV** [comment]
I don't think so, and I disagree with the switch from numpydoc to napoleon. I believe that projects should stick to packages that are standard, and napoleon isn't the standard in the scientific python community.
I am also confused with the statement that "Other parameters" is not render properly.

**Comment by NelleV** [comment]
And I did not take over that PR :)

**Comment by jenshnielsen** [comment]
I don't have any strong preference for numpydoc vs napoleon just wanted to make sure that this is coordinated. 

The non correct rendering is explained in the original post:
Inspecting the page source makes it a bit more clear. 

```
Looking at the html in a browser inspector, you can see that Parameters and Returns are the header to a and the contents are in the respective . However, with Other Parameters, the contents are being inserted into a new following the Other Parameters row.
```

I.e. [here](http://matplotlib.org/devdocs/api/axes_api.html#matplotlib.axes.Axes.acorr) I would expect the gray box to extend all the way down on the left and not across in the other parameters section

**Comment by QuLogic** [comment]
Napoleon is bundled with Sphinx 1.4+ and implements the NumPyDoc format, so I don't really think it's that non-standard.
