### ISSUE TITLE
Ability to add more than one canvas to a pyplot figure?

### ISSUE THREAD

**Issue by alexanderwhatley** [matplotlib/matplotlib#6936]
Is there a way to add multiple canvases corresponding to multiple axes/subplots in a single matplotlib figure? Right now, I am experimenting with interactive figures in the IPython notebook, and I would like to have this functionality, as matplotlib cannot distinguish between the individual subplots when performing dynamic updates. Say I have the code:

```
import matplotlib
matplotlib.use("nbagg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

plt.clf()
fig1 = plt.figure("0")
axes = []
axes.append(fig1.add_subplot(1, 2, 1))
axes.append(fig1.add_subplot(1, 2, 2))
rects = [Rectangle((1,1), 5, 5, color = '0', fill = False) for i in range(2)]
axes[0].scatter([1,2,3], [4,5,6])
axes[1].scatter([1,2,6], [6,7,10])
for i in range(2):
    axes[i].add_patch(rects[i])
print(axes[0].figure.canvas)
print(axes[1].figure.canvas)
```

Output:

```
<matplotlib.backends.backend_nbagg.FigureCanvasNbAgg object at 0x000001496AA07978>
<matplotlib.backends.backend_nbagg.FigureCanvasNbAgg object at 0x000001496AA07978>
```

Is there a way to add two canvases; one corresponding to each of axes[0] and axes[1]? Note that I specifically want this for a single figure with multiple subplots, and not multiple figures, as I want the graphs to be on the same row.

**Comment by LindyBalboa** [comment]
I'm not really sure what you mean by _dynamic updates_? I don't see anything problematic with the code you have shown us. Otherwise, so far as I know, two canvases in one figure doesn't make sense, since canvas is in a parent relationship to a given figure. Can you supply a minimum working example that at least gets up to whatever problem you are trying to solve?

**Comment by alexanderwhatley** [comment]
The issue is that if I want to do certain operations, such as displaying shapes such as a rectangle, that requires the use of a canvas, but since the canvases on the subplots are the same, this is not possible, hence my question.

**Comment by LindyBalboa** [comment]
I ran your code to see what was going on. The only difference is I ran it on Qt4agg because I am not set up to run nbagg. Is the following not what you expected? If not, could you do a MsPaint mockup/edit of what you are trying to accomplish?

![0](https://cloud.githubusercontent.com/assets/20605205/17598132/59dc6d0c-5ff9-11e6-8ff2-f02e9fe6f900.png)

**Comment by alexanderwhatley** [comment]
My bad, I did not give you a good example. I think that this example better illustrates what I am saying:

```
import matplotlib.pyplot as plt
%matplotlib notebook
from matplotlib.patches import Rectangle

class Test(object):
    def __init__(self):
        self.figure = plt.figure()
        self.ax1 = self.figure.add_subplot(1, 2, 1)
        self.ax2 = self.figure.add_subplot(1, 2, 2)
        self.rect1 = Rectangle((0, 0), 1, 1)
        self.rect2 = Rectangle((0, 0), 1, 1)
        self.x0 = None
        self.y0 = None
        self.x1 = None
        self.y1 = None
        self.ax1.add_patch(self.rect1)
        self.ax2.add_patch(self.rect2)
        self.ax1.figure.canvas.mpl_connect('button_press_event', self.on_press)
        self.ax1.figure.canvas.mpl_connect('button_release_event', self.on_release1)
        self.ax2.figure.canvas.mpl_connect('button_press_event', self.on_press)
        self.ax2.figure.canvas.mpl_connect('button_release_event', self.on_release2)

    def on_press(self, event):
        self.x0 = event.xdata
        self.y0 = event.ydata

    def on_release1(self, event):
        self.x1 = event.xdata
        self.y1 = event.ydata
        self.rect1.set_width(self.x1 - self.x0)
        self.rect1.set_height(self.y1 - self.y0)
        self.rect1.set_xy((self.x0, self.y0))
        self.ax1.figure.canvas.draw()
        
    def on_release2(self, event):
        self.x1 = event.xdata
        self.y1 = event.ydata
        self.rect2.set_width(self.x1 - self.x0)
        self.rect2.set_height(self.y1 - self.y0)
        self.rect2.set_xy((self.x0, self.y0))
        self.ax2.figure.canvas.draw()

a = Test()
plt.show()
```

Here, when I click around, the rectangles on both subplots are modified (see below image for example). I think that this stems from the fact that both axes are linked to the same canvas, since they are part of the same figure.

![image](https://cloud.githubusercontent.com/assets/14192598/17607161/e13fd0fc-5fd8-11e6-8b40-a1754807ffbe.png)

**Comment by tacaswell** [comment]
The 'event' objects include a reference to which axes they are in as the `inaxes` property.  Adding

```python
if not event.inaxis is self.ax1:
    return
```

and analogs to your callbacks allows you to filter by axes (which is the easiest course of action here).

A 1:1 mapping between `Figure` objects and `canvas` objects is baked into the architecture of maplotlib, that is unlikely to change.  In all of the backends (which provide the canvas classes) there is also a 1:1 mapping between a window and canvas in the code that is used by `pyplot`.  This is not as baked in, but for consistency and keeping the API simple that is also unlikely to change.

In the 'traditional' gui backends, the canvas is exposed as an object the multiply inherits from the gui-widget class, thus to get multiple `Figure`/`canvas` in a single gui window you can use the GUI frameworks layout tools to embed them anyway you you want. 

There is no technical reason that the same can not be done for nbagg, If you really, you will just have to dig into the js front end (see https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib/backends/web_backend/js and https://github.com/matplotlib/jupyter-matplotlib ).  

You could imagine an API that looks something like

```python
fig1, fig2 = your_module.get_multi_figure()
```

**Comment by efiring** [comment]
I don't think this needs to stay open, but reopen if you disagree.
