### ISSUE TITLE
wspace is not "The amount of width reserved for blank space between subplots" as documented

### ISSUE THREAD

**Issue by stilley2** [matplotlib/matplotlib#6939]
If wspace were really the width between the subplots (in normalized figure coordinates) as documented, the first printed value would be 0.2. The second value is to test whether wspace is actually the fraction of a gridspec cell dedicated to whitespace, which is also not the case. The issue seems to be due to the definition of sepW
https://github.com/matplotlib/matplotlib/blob/f3ed922d935751e08494e5fb5311d3050a3b637b/lib/matplotlib/gridspec.py#L116
In order to conform with the documentation, I think sepW should be defined as:
    sepW = wspace / (ncols - 1)
but I haven't tested this.

Example code:

```
from matplotlib import pyplot as plt
gridspec_kwargs = dict(top=0.9, bottom=0.1, left=0.1, right=0.9, wspace=0.2, hspace=0.2)
fig, axs = plt.subplots(nrows=1, ncols=2, gridspec_kw=gridspec_kwargs)
ax1_pos = axs[1].get_position()
ax0_pos = axs[0].get_position()
print('fraction of figure representing space between figures')
print(ax1_pos.x0 - ax0_pos.x1)
print('space between figures represented as a fraction of axis width')
print((ax1_pos.x0 - ax0_pos.x1) / (ax1_pos.x0 - ax0_pos.x0))
```

Output:

```
fraction of figure representing space between figures
0.0727272727273
space between figures represented as a fraction of axis width
0.166666666667
```

Installation information:
matplotlib version: 1.5.1
sys.version output
    >>>'3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

**Comment by tacaswell** [comment]
In this case the documentation should probably be updated to describe what the code actually does.

**Comment by stilley2** [comment]
I agree, except that I don't think it has a concise meaning as defined in the code. In order to maintain backwards compatibility, it seems the options are to 1) try to describe what wspace actually is in the documentation, or 2) add another parameter (wfraction?) that does what wspace is advertised as doing, and through an error if the user specifies both wspace and wfraction. 

Also, it looks like hspace has the same issue.

**Comment by efiring** [comment]
Thanks for working on this.  No question, the docs need clarification!

Let's rearrange lines 116 and 117 and add a definition (this is algebra, not code):
```
nspaces = ncols - 1
totW = cellW * ncols + wspace * cellW * nspaces
        = cellW * ncols + sepW * nspaces
```
Therefore "wspace is the space between subplots as a fraction of the  *average* subplot width".
In your example, I think you have an error in your last line.  Here is a corrected version:
```python
from matplotlib import pyplot as plt
gridspec_kwargs = dict(top=0.9, bottom=0.1, left=0.1, right=0.9, wspace=0.2, hspace=0.2)
fig, axs = plt.subplots(nrows=1, ncols=2, gridspec_kw=gridspec_kwargs)
ax1_pos = axs[1].get_position()
ax0_pos = axs[0].get_position()
print('space between figures represented as a fraction of axis width')
print((ax1_pos.x0 - ax0_pos.x1) / (ax1_pos.x1 - ax1_pos.x0))  # width of ax1
```
gives
```
space between figures represented as a fraction of axis width
0.2
```

**Comment by stilley2** [comment]
Ah I see. Thanks for clarifying! In that case I definitely agree with your definition.
