### ISSUE TITLE
Ring over A in \AA is too high in Matplotlib 1.5.1

### ISSUE THREAD

**Issue by joshuawallace** [matplotlib/matplotlib#6951]
This issue is for Matplotlib version 1.5.1 and uses version 1.4.3 as a reference point.
Python version: Python 2.7.12 :: Anaconda custom (64-bit)
Platform: Linux (Springdale Linux, based on RedHat)
Installation method: Anaconda, for both Python and Matplotlib

Please note: I also have a StackOverflow question on this subject (where someone suggested I submit this as a bug report) which is useful as an additional reference for this bug: http://stackoverflow.com/questions/38985423/in-matplotlib-how-to-get-same-math-text-font-as-before-an-update

**In short, the issue is that the ring above the A when using \AA is higher in version 1.5.1 than it was in 1.4.3, and I think the 1.4.3 ring height is the correct one.  The 1.4.3 ring height is the one I prefer at least.

After submitting the StackOverflow question, I downgraded my matplotlib back to 1.4.3 and verified that the ring height went back down to where it was before.  It did.

Here is an sscce:

import matplotlib.pyplot as plt
plt.xlabel("$\AA \mathrm{\AA}$")
plt.show()

I've attached two images: the first image shows a detail of the plot generated above with version 1.4.3, focusing on the xlabel and the second image shows the same for version 1.5.1.

![angstrom_1 4 3](https://cloud.githubusercontent.com/assets/5067798/17744663/c5e7cf42-6476-11e6-9a7f-e5ac6d718cc8.png)
![angstrom_1 5 1](https://cloud.githubusercontent.com/assets/5067798/17744664/c5f81780-6476-11e6-99e2-54fe3b703083.png)

**Comment by tacaswell** [comment]
attn @mdboom @zblz

**Comment by jenshnielsen** [comment]
It is possible that it's to high in the second image but in my opinion the first one is definitely to low. The ring should not touch the letter A. Take that from someone who has å as a letter in their native language (Danish)

**Comment by efiring** [comment]
This is not a matter of style change, but a detail of mathtext.  We would consider a PR that fine-tunes this detail, supported by an authoritative illustration of best typographic practice, but I don't see that we need to leave this as an open issue.  If anyone disagrees, feel free to reopen it.

**Comment by joshuawallace** [comment]
Is there any way in 1.5.1 to get the ring closer to the A like in 1.4.3?
