### ISSUE TITLE
Adding a system wide directory to place custom styles 

### ISSUE THREAD

**Issue by juanrg** [matplotlib/matplotlib#6954]
If you define a custom style you can [place it in your home directory](http://matplotlib.org/users/style_sheets.html) and then it will be accessible via `plt.style.use("customstyle")`. However, there doesn't seem to be a simple way of making the style available for all users in the system. I am thinking something like `/etc/matplotlib/stylelib/`. 

If this makes sense and I am not missing anything I could send a pull request.

**Comment by tacaswell** [comment]
To make something work _now_ you can add any path to `syle.core.SYLE_LIBRARY_PATHS` and it will be searched.  You can also put stuff in what ever `mpl.get_data_path()` returns.

:+1: on implementing this.  The search rules should probably exactly mirror the search rules for `matplotlbrc`.

**Comment by juanrg** [comment]
By reviewing the code, I just realized that this feature already exists. Setting XDG_CONFIG_HOME will solve the issue above, so no need to make any pull requests... right? In that case, sorry for opening the issue :)

See [here](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L670) and [here where its called](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/style/core.py#L33)

**Comment by jenshnielsen** [comment]
As I understand it XDG_CONFIG_HOME is supposed to set the default config dir for a specific user so setting it to the same for multiple users seems dangerous? I understood your original issue as you want the same directory to be read for multiple users.

**Comment by juanrg** [comment]
Ah, true, my bad again https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by WeatherGod** [comment]
In addition, that environment variable is not just for matplotlib, it is
for all software that recognizes that argument. It might not be desirable
for all such software for all users to use the same config directory. Also
note that matplotlib does try to write stuff out to that location upon
import, and has fail-back mechanisms when it can't do so. Presumedly, this
directory wouldn't be writable by all users, which might be problematic.

**Comment by anntzer** [comment]
Closed by #7100, afaict... feel free to request a reopen if not.
