### ISSUE TITLE
ArtistAnimation cannot animate Figure-only artists

### ISSUE THREAD

**Issue by typograph** [matplotlib/matplotlib#6965]
ArtistAnimation currently constructs a list of Figures to animate like this:

```python
    if artist.axes.figure not in figs:
        figs.add(artist.axes.figure)
```

However, some artists (e.g. suptitle) have `None` as axes, so this code fails. On the other hand, each artist has a `get_figure` method. Why not change the above code to:

```python
    if artist.get_figure() not in figs:
        figs.add(artist.get_figure())
```

**Comment by dopplershift** [comment]
Thanks for the report. That change makes sense to me--would you be willing to submit a Pull Request with that change?
