### ISSUE TITLE
quiverkey problem when angles=array

### ISSUE THREAD

**Issue by mlandriau** [matplotlib/matplotlib#6972]
With matplotlib 1.5.1 and python 3.5.2, quiverkey plots every vector when angles=array instead of 'uv' or 'xy' in the quiver object used to create the key.

```
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()

X, Y = np.meshgrid(np.arange(5), np.arange(7))
U = V = np.ones_like(X)

phi = (np.random.rand(5, 7) - .5) * 150
q = ax.quiver(X, Y, U, V*.5, angles=phi, color='r', alpha=1)

qk = ax.quiverkey(q, 0.5, 0.92, 2, r'$2 \frac{m}{s}$',
                      labelpos='W',
                      fontproperties={'weight': 'bold'})
plt.show()
```

![quiverkey_issue](https://cloud.githubusercontent.com/assets/19720130/17916794/5276d98c-696b-11e6-9f86-de64a4375463.png)

**Comment by QuLogic** [comment]
New arguments == not just a bugfix, so bumping milestone.
