### ISSUE TITLE
[Feature request] Simple ticks generator for given range

### ISSUE THREAD

**Issue by avi9526** [matplotlib/matplotlib#6975]
matplotlib allows to generate nice ticks for given image. But I had reverse task - generate custom color image (ratio of two images - pixel wise ratio define color and pixel wise average define intensity) with custom color bar with nice ticks. To do so I need to know ticks before I can make image, and the only thing that is known is approximate center value and range ±50%. I had to use code from below, but it would be nice to have easy access to built-in matplotlib function that generates ticks array for wanted range
```python
# Make equdistant ticks for given range
def Ticks4Range(Range, MinTickCount = 5):
	Sign = numpy.sign(Range[1] - Range[0])
	TickStep = Sign * (Range[1] - Range[0]) / MinTickCount
	Digits = numpy.floor(numpy.log10(TickStep) + 1) - 1
	TickStep = (TickStep / 10**Digits)
	if TickStep < 2:
		TickStep = 1
	elif TickStep < 2.5:
		TickStep = 2
	elif TickStep < 5:
		TickStep = 2.5
	else:
		TickStep = 5
	TickStep = TickStep * 10**Digits
	Digits = numpy.floor(numpy.log10(numpy.max(Range)) + 1) - 1
	#TickRange = numpy.ceil(Range[0] / TickStep) * TickStep, numpy.floor(Range[1] / TickStep) * TickStep
	#Ticks = numpy.linspace(TickRange[0], TickRange[1], numpy.round((TickRange[1] - TickRange[0]) / TickStep * Sign))
	Ticks = numpy.arange(numpy.ceil(Range[0] / TickStep * Sign) * Sign * TickStep, Range[1]*(1 + 0.01*Sign*numpy.sign(Range[1])), TickStep * Sign)
	return Ticks

```
I use it this way
```python
>>> custom.Ticks4Range(57.86 * numpy.array([0.5, 1.5]), 3)
array([ 30.,  40.,  50.,  60.,  70.,  80.])
```

**Comment by story645** [comment]
Just curious, why doesn't [`ticker.LinearLocator`](http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.LinearLocator) do what you want?

**Comment by avi9526** [comment]
If ignore that locators related stuff is hard to understand, after looking to examples of using locators it appears to me that you need to draw something before you can get ticks. There is no image yet to draw, I just want ask matplotlib what nice ticks it could have made for approximate range of data, and then alter data a bit to match that ticks nicely when drawn. 
Like this bar, I get good ticks, I alter data to match range of this ticks, draw image, put ticks in place with set_yticks
![colorbar](https://cloud.githubusercontent.com/assets/2995445/17959413/ec53da76-6aa8-11e6-9fed-b943f33d30e9.png)

**Comment by story645** [comment]
Do you want this for ticks or for coloring the images? If it's the latter,  that's the job of the http://matplotlib.org/users/colormapnorms.html

**Comment by anntzer** [comment]
You could do
```
l = matplotlib.ticker.AutoLocator()
l.create_dummy_axis()
l.tick_values(vmin, vmax) # here you go
```

**Comment by avi9526** [comment]
Yes, this is what I search for, sorry, didn't mean to waste your time, mark as closed please

**Comment by anntzer** [comment]
No worries.
