### ISSUE TITLE
problem accessing canvas on MacOS 10.11.6 with matplotlib 2.0.0b3

### ISSUE THREAD

**Issue by lebedov** [matplotlib/matplotlib#6980]
When I try running the below code directly with python (or within IPython 5.1.0 after running `%matplotlib qt4` with the `matplotlib.use('Qt4Agg')` line removed), 

```python
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt
import numpy as np

f = plt.gcf()
plt.imshow(np.random.rand(100, 100))
plt.draw()
im = np.fromstring(f.canvas.tostring_rgb(), dtype=np.uint8)
```
I observe the following error:

```
Traceback (most recent call last):
  File "test_renderer.py", line 9, in <module>
    im = np.fromstring(f.canvas.tostring_rgb(), dtype=np.uint8)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 484, in tostring_rgb
    return self.renderer.tostring_rgb()
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'renderer'
```

If I'm in IPython and run the script a second time after the above exception, no error occurs. Moreover, if I add `f.canvas.draw()` before I try to run `f.canvas.tostring_rgb()`, the error goes away. Also, the error appears to occur with backends other than qt4 such as tk (although not with agg).

Could this be related to #5058?

I'm running matplotlib 2.0.0b3 with Python 2.7.12 and PyQt4 4.11.4 (all installed in Anaconda from conda-forge) on MacOS 10.11.6.

**Comment by tacaswell** [comment]
I think you are running into a 'feature'.  We do not create the `Renderer` object until we strictly need it.

The better fix would be to make `renderer` a property, but I see a fast fix for now....

**Comment by tacaswell** [comment]
Actually, on a bit more consideration, I am not sure that this should be fixed or that those methods were meant to be public.  They are not part of the API defined in `backend_bases` and rely on the render created, attached to the canvas and filled with data in the `draw` method.

What exactly are you trying to do?  I suspect there is a better way.  Either by directly color-mapping an array or by passing a `BytesIO` object into `fig.savefig`.

https://github.com/matplotlib/matplotlib/pull/6909 might also be of interest.

**Comment by lebedov** [comment]
Essentially what #6909 provides, but with the additional step of converting the bytes to an array of RGB data. Saving the figure to a `BytesIO` and reading the latter with `imread()` does the job.

BTW, I got the idea to use the `tostring_rgb()` method from [here](http://stackoverflow.com/questions/21939658/matplotlib-render-into-buffer-access-pixel-data).

Feel free to close at your convenience.
