### ISSUE TITLE
link to ggplot is broken...

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6981]
... towards the top of http://matplotlib.org/users/style_sheets.html
Should probably point to http://ggplot.yhathq.com/ or http://ggplot2.org/

**Comment by QuLogic** [comment]
Should be fixed by #6861; not sure why it's not visible yet.

**Comment by QuLogic** [comment]
Oh, never mind, that PR only changed the Python file so it needs to be applied elsewhere.

However, this is still a dup of #6859.
