### ISSUE TITLE
Error in AxesGrid docs

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#699]
For the constructor of AxesGrid in mpl_toolkits.axes_grid1, it states that the 'axes_class' kwarg is a type object which must be a subclass of Axes.  If the axes that is passed in is a regular rectilinear Axes object, it works as expected (or if passed None).  However, if the axes is any other type, then the constructor appears to want to unpack axes_class into an axes class and arguments for the initialization of the class.  This needs to be stated in the docs.

Note that such change in the docs might then conflict with usage of host_subplot(), which does not do the same behavior for axes_class kwarg.

**Comment by tacaswell** [comment]
related to #4015

**Comment by tacaswell** [comment]
I think this is closed by #4015
