### ISSUE TITLE
FontProperties size and weight ignored by figure.suptitle

### ISSUE THREAD

**Issue by dmkent** [matplotlib/matplotlib#6996]
Passing a FontProperties object to suptitle used to allow setting of font size and weight (in 1.4.*) however #3011 means the defaults from rcParams now override the font properties values.

Issue is somewhere in figure.py#L540.

Happy to put a PR together but not sure on best approach to solve.

Should we check to see if fontproperties is present before overriding? Do other methods handle this somewhere?

This used to work:

```python
from matplotlib import pyplot as plt
from matplotlib.font_manager import FontProperties

fig = plt.figure()
fp = FontProperties(family="sans-serif", size="large", weight="bold")
txt = fig.suptitle('my title', fontproperties=fp)

assert txt.get_weight() == fp.get_weight()
```

**Comment by tacaswell** [comment]
Sigh, 2 steps forward, one step back.

I think checking if `fontproperties` is present in the kwargs as well as checking of `fontsize' and 'fontweight' are present is a good solution.

**Comment by petrenkomaxim** [comment]
Sorry for going off-topic, but while you guys are working on a permanent fix - can you possibly suggest a temporary workaround? We have recently updated matplotlib on our production system and the titles are now all over-sized. Should I just use a text box instead? Thanks!

**Comment by dmkent** [comment]
I'm doing this as a workaround:

'''
fig.suptitle("title").set_fontproperties(fp)
'''

**Comment by petrenkomaxim** [comment]
dmkent, thanks for a super quick reply! I tried your workaround and it indeed works! However, I then noticed that when I print a 4-line suptitle, the last line of the text spills under the top edge of the plot. Using fig.title seems to avoid this problem. Go figure.
