### ISSUE TITLE
Zooming with a large range in y-values while using the linestyle "--" is very slow

### ISSUE THREAD

**Issue by hsgg** [matplotlib/matplotlib#7004]
Zooming in on a part of a plot with a large range in y-values while using the linestyle "--" is very slow.

The following minimal working example hangs at the plt.show() line.

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.linspace(0,2)
    y = [0.5]*25 + [1.5e13]*25

    plt.plot(x, y, ls='--')

    plt.ylim(0, 2)

    plt.show()

The problem can also be experienced by commenting the plt.ylim() line, and then zooming in a few times with the mouse.

OS: OS X El Capitan 10.11.6
python: Python 3.5.1 (default, Mar  2 2016, 03:38:02) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
matplotlib.__version__ = 1.5.2
matplotlib.__numpy_version__ = 1.6

python is from macports, matplotlib and numpy from pip install --user.

**Comment by WeatherGod** [comment]
Is it possible for you to test out the pre-release of v2.0? In it we have
some major reworks of the macosx backend that should address issues like
these, I think.

**Comment by WeatherGod** [comment]
btw, `matplotlib.__numpy_version__` is not the version of numpy used,
rather the version of the numpy API we adhere to.

**Comment by hsgg** [comment]
Thanks for the info.
Yes, matplotlib-v2.0.0b3-2086-g0e46a9d works indeed.

**Comment by tacaswell** [comment]
Closing as resolved on the currently active branches.
