### ISSUE TITLE
Suspected incorrect axis transformation of symlog

### ISSUE THREAD

**Issue by desert0616** [matplotlib/matplotlib#7008]
Hi, @mdboom.
Can you roughly explain the meaning of _linscale_adj in SymmetricalLogTransform which was introduced via [d8bf0fed4d62324489ffe1d21d114c87ae9ca6a4](https://github.com/matplotlib/matplotlib/commit/d8bf0fed4d62324489ffe1d21d114c87ae9ca6a4)?

<pre><code>
class SymmetricalLogTransform(Transform):
    input_dims = 1
    output_dims = 1
    is_separable = True
    has_inverse = True

    def __init__(self, base, linthresh, linscale):
        Transform.__init__(self)
        self.base = base
        self.linthresh = linthresh
        self.linscale = linscale
        self._linscale_adj = (linscale / (1.0 - self.base ** -1))
        self._log_base = np.log(base)
</code></pre>

I am quite puzzled by it.

According to the [documentation](http://matplotlib.org/api/pyplot_api.html?highlight=xscale#matplotlib.pyplot.xscale) about linscalex / linscaley, its value is the number of decades to use for each half of the linear range. For example, when linscale == 1.0 (the default), the space used for the positive and negative halves of the linear range will be equal to one decade in the logarithmic range.

As I understand it, it means that when the base is 10 and the linthresh equals to 1, the length of the interval between 0 and 1 should equal to the interval between 1(10^0) and 10(10^1). And this feature seems to be very useful that user can adjust the relative ratio between linear range and logarithmic range.

However, since the _linscale_adj amplifies the original linscale by 1/(1-1/base), the actual place for the linear range will be 1.11x compared to logarithmic range per decade.

For example,

<pre><code>
import numpy as np
import matplotlib.pyplot as plt

x = np.array([0, 1, 5, 10, 100, 1000])
y = np.array([0] * 6)

plt.scatter(x, y)
plt.xscale('symlog', linthreshx=10, basex=10, linscalex=1)
plt.grid(True)
plt.show()
</code></pre>

![base10](https://cloud.githubusercontent.com/assets/13389038/18077096/a834e702-6eb5-11e6-9cb5-e0d1cc049763.png)

If the base is set to 2, the linear range will be 2x than logarithmic range per decade and this issue may be more considerable:

<pre><code>
import numpy as np
import matplotlib.pyplot as plt

x = np.array([0, 0.5, 1, 2, 4, 8, 16])
y = np.array([0] * 7)

plt.scatter(x, y)
plt.xscale('symlog', linthreshx=2, basex=2, linscalex=1)
plt.grid(True)
plt.show()
</code></pre>

![base2](https://cloud.githubusercontent.com/assets/13389038/18077163/33f0ba3c-6eb6-11e6-9d00-3cb1f6defc51.png)

Since _linscale_adj is relatively independent and is only used to be a coefficient of transformation for symlog, it seems not to be a bug. So, what is the meaning of the scaling of _linscale_adj which related to its base?

Well, as a user, the figures showed above is very weird and I used to set the linscale manually to 0.9 (base=10) to make each tick interval to be equal.

Thanks.

**Comment by desert0616** [comment]
is any comment for this issue?

**Comment by tacaswell** [comment]
@phobson You think a lot about non-linear scales, do you have any insight into this?

**Comment by phobson** [comment]
I'm still catching up on paid gig stuff after my vacation. But I'll shoot to give this a good look later in the week.

**Comment by jgehrcke** [comment]
I think this should get more attention. I cannot submit a bug report right now, I don't have enough clarity, but I face a quite similar issue with `symlog`, where the tick intervals are not equidistant.

**Comment by phobson** [comment]
@jgehrcke could you add a small example that illustrates what you're describing to this issue?

**Comment by jgehrcke** [comment]
> @jgehrcke could you add a small example that illustrates what you're describing to this issue?

Thanks for asking :)

```
$ cat repro.py 
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(1,2,10)
y = np.array([0, 3, 10, 20, 30, 40, 100, 400, 800, 1000])

plt.figure()
plt.yscale('symlog')
plt.plot(x,y)

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/265630/60199168-a03b9180-9843-11e9-811c-26c77c783d4d.png)

I would expect the distance between the `10^0` tick and the `10^1` tick to be equal to the distance between the `10^1` and the `10^2` tick.

However, the distance between the `10^0` tick and the `10^1` tick is *larger*.

```
>>> mpl.__version__
'3.1.0'
```

**Comment by desert0616** [comment]
wow... amazing, this thread is still alive after 3 years...

**Comment by jklymak** [comment]
`linthreshx` and `linthreshy` default to 2.  Try `plt.yscale('symlog', linthreshy=1)`

**Comment by phobson** [comment]
This is fascinating

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(1,2,10)
y = np.array([0, 3, 10, 20, 30, 40, 100, 400, 800, 1000])

fig, axes = plt.subplots(ncols=2)
for thresh, ax in enumerate(axes, 1): 
    ax.set_yscale("symlog", linthreshy=thresh)
    ax.plot(x,y)
    ax.set_title(f"linthreshy = {thresh}")

plt.show()
```

![image](https://user-images.githubusercontent.com/1163939/60203881-80d04480-9802-11e9-8d09-bd7a8b115212.png)

**Comment by jklymak** [comment]
But that's correct...

**Comment by phobson** [comment]
Oh yeah, I had forgotten 10^ = 1

**Comment by phobson** [comment]
so the gap between 1 and 0 changing makes sense and same for the game between 1 and 10

**Comment by jgehrcke** [comment]
> linthreshx and linthreshy default to 2. 

Dang! I assumed it's 1. Not documented here: https://matplotlib.org/3.1.0/api/scale_api.html#matplotlib.scale.SymmetricalLogScale

But interestingly the "Defaults to 2" has very recently been added here: https://github.com/matplotlib/matplotlib/commit/267935459d2ec071087068ada5ad4d36c0c53577#diff-9e3c26547d61ec9447f5420ec32f08f4R549 -- so I suppose with the next release the documentation will be clearer.

Thanks! So, "my issue" here is resolved. Lovely.

**Comment by jklymak** [comment]
@jgehrcke good point.  that should be fixed.   Any appetite for making a PR to do that?

**Comment by timhoffm** [comment]
@jklymak What exactly needs fixing? The documentation is already fixed by https://github.com/matplotlib/matplotlib/commit/267935459d2ec071087068ada5ad4d36c0c53577#diff-9e3c26547d61ec9447f5420ec32f08f4R549:

https://matplotlib.org/devdocs/api/scale_api.html#matplotlib.scale.SymmetricalLogScale

**Comment by gregcolyer** [comment]
Even in @phobson's linthreshy=1 plot above, there is still a different gap between 0 and 1 vs. 1 and 10, presumably due to the (1-1/b) factor mentioned originally by @desert0616 at the top. Cf. issue #10369, where I suggested what to change in the code and/or documentation to address this: for the examples there I also set linthreshy=1, so I'm not sure if I thought about other values (or if that is independent).

**Comment by YannDubs** [comment]
putting together what @gregcolyer and @desert0616 said (and code in #10369). There are 2 current workarounds depending on what you want :

```python
import matplotlib.pyplot as plt
import numpy as np

# Define some curves:
x = np.linspace(0.1,3.,100)
y1 = x
y2 = x**2
y3 = np.exp(x)/2.
y4 = np.log(x)*2.

def generate_plot(get_kwargs, ax, base, sffx):
    ax.set_title(f'base {base} {sffx}')
    ax.set_ylim(-100,100)
    ax.set_yscale('symlog',linthreshy=1, **get_kwargs(base))               # should set decade = half-linear
    ax.plot(x,y1)
    ax.plot(x,y2)
    ax.plot(x,y3)
    ax.plot(x,y4)
    

def generate_plots(get_kwargs, sffx):
    bases = [2,5,10,100]
    
    f, axes = plt.subplots(1,len(bases),figsize=(len(bases)*5,4))
    
    for base, ax in zip(bases, axes):
        generate_plot(get_kwargs, ax, base, sffx)
```

```python
# Default parameters
get_kwargs_dflt = lambda base : dict(basey=base)
generate_plots(get_kwargs_dflt, "dflt")
```

<img width="1175" alt="dflt" src="https://user-images.githubusercontent.com/24327668/76055491-ce7c7f80-5f41-11ea-977d-36926de42182.png">

```python
# Equidistant ticks
get_kwargs_unif = lambda base : dict(basey=base,linscaley=(1-(1/base)))
generate_plots(get_kwargs_unif, "unif")
```

<img width="1175" alt="unif" src="https://user-images.githubusercontent.com/24327668/76055224-00411680-5f41-11ea-96d2-00f1c602a97c.png">

```python
# Keep smooth plots (don't show inexistant "kinks")
get_kwargs_smooth = lambda base : dict(basey=base,linscaley=np.log(np.e)/np.log(base) * (1-(1/base)))
generate_plots(get_kwargs_smooth, "smooth")
```
<img width="1175" alt="smooth" src="https://user-images.githubusercontent.com/24327668/76055320-4ac29300-5f41-11ea-8247-967e6ec9c99e.png">

**Comment by QuLogic** [comment]
@YannDubs That seems like a pretty good example (or maybe tutorial), would you like to make a PR adding it? It would need some amount of prose added to explain what it does. It could supplement `examples/scales/symlog_demo.py`.
