### ISSUE TITLE
Issue with legend in 'expand' mode with a non keyword location

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#7013]
I was trying to put a legend outside of the axes and encountered a few strange behaviors, mainly with the option `mode='expand'`, which may be bugs.

Here is a small MWE to show it

``` python
import matplotlib.pyplot as plt

fig, ((ax0, ax1), (ax2, ax3)) = plt.subplots(nrows=2, ncols=2)
fig.subplots_adjust(hspace=0.4)  # make space for outside legend

# Case A: with a string 'loc' & a 'bbox_to_anchor' kwarg
legend_opts_A = {'loc': 'lower left', 'bbox_to_anchor': [0.0, 1.02]}
ax0.set_ylabel("Case A: w/ bbox_to_anchor")

ax0.plot([0, 1], label="mode: None")
ax0.legend(mode=None, **legend_opts_A)

ax1.plot([0, 1], label="mode: 'expand'")
ax1.legend(mode='expand', **legend_opts_A)

# Case B: with a 2-tuple 'loc' but no 'bbox_to_anchor' kwarg
legend_opts_B = {'loc': [0.0, 1.02]}
ax2.set_ylabel("Case B: w/ a 2-tuple loc")

ax2.plot([0, 1], label="mode: None")
ax2.legend(mode=None, **legend_opts_B)

ax3.plot([0, 1], label="mode: 'expand'")
ax3.legend(mode='expand', **legend_opts_B)

plt.show()
```

which produces, with  **mpl 2.0.0b3.post2098+g211984d** (master branch from GitHub):
![mpl_2 0 0b3 post2098 g211984d](https://cloud.githubusercontent.com/assets/17270724/18129096/6a5f68ba-6f89-11e6-8433-c9e66ca5792b.png)

and with **mpl 1.5.1** (from Anaconda):
![mpl_1 5 1](https://cloud.githubusercontent.com/assets/17270724/18129091/6666dacc-6f89-11e6-8083-b0d67bc1a2db.png)

1/ _The legend appears to be closer to the top spline in case B than in case A_, although the two cases should give identical results if I have correctly understood the docstring of legend.

2/ _Case A results in a broken legend with `mode='expand'`_.

3/ Even in case B with `mode='expand'`, the right side of the legend box is a bit surprising : I would have expected it to reach the right spline.

**NB**: I got similar problems when using a legend that is not outside of the axes

**Comment by afvincent** [comment]
I can confirm that this behavior is still present on the master branch.

I think this is likely to be related to the same issue as in #10476 and @dstansby may be right (i.e. the issue would be linked with the "expand" legend mode). If I call `fig.tight_layout()` before `plt.show()` in the example script, then I get
```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-64302a6f0b1a> in <module>()
     24 ax3.legend(mode='expand', **legend_opts_B)
     25 
---> 26 fig.tight_layout()
     27 plt.show()

~/FOSS/matplotlib/lib/matplotlib/figure.py in tight_layout(self, renderer, pad, h_pad, w_pad, rect)
   2271         kwargs = get_tight_layout_figure(
   2272             self, self.axes, subplotspec_list, renderer,
-> 2273             pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
   2274         self.subplots_adjust(**kwargs)
   2275 

~/FOSS/matplotlib/lib/matplotlib/tight_layout.py in get_tight_layout_figure(fig, axes_list, subplotspec_list, renderer, pad, h_pad, w_pad, rect)
    326                                      subplot_list=subplot_list,
    327                                      ax_bbox_list=ax_bbox_list,
--> 328                                      pad=pad, h_pad=h_pad, w_pad=w_pad)
    329 
    330     if rect is not None:

~/FOSS/matplotlib/lib/matplotlib/tight_layout.py in auto_adjust_subplotpars(fig, renderer, nrows_ncols, num1num2_list, subplot_list, ax_bbox_list, pad, h_pad, w_pad, rect)
    112             continue
    113 
--> 114         tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots
    115                                 if ax.get_visible()])
    116         tight_bbox = TransformedBbox(tight_bbox_raw,

~/FOSS/matplotlib/lib/matplotlib/tight_layout.py in <listcomp>(.0)
    113 
    114         tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots
--> 115                                 if ax.get_visible()])
    116         tight_bbox = TransformedBbox(tight_bbox_raw,
    117                                      fig.transFigure.inverted())

~/FOSS/matplotlib/lib/matplotlib/axes/_base.py in get_tightbbox(self, renderer, call_axes_locator)
   4177                 bb.append(child.get_window_extent(renderer))
   4178             elif isinstance(child, Legend) and child.get_visible():
-> 4179                 bb.append(child._legend_box.get_window_extent(renderer))
   4180 
   4181         _bbox = mtransforms.Bbox.union(

~/FOSS/matplotlib/lib/matplotlib/offsetbox.py in get_window_extent(self, renderer)
    260         get the bounding box in display space.
    261         '''
--> 262         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    263         px, py = self.get_offset(w, h, xd, yd, renderer)
    264         return mtransforms.Bbox.from_bounds(px - xd, py - yd, w, h)

~/FOSS/matplotlib/lib/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    382 
    383         whd_list = [c.get_extent(renderer)
--> 384                     for c in self.get_visible_children()]
    385         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    386 

~/FOSS/matplotlib/lib/matplotlib/offsetbox.py in <listcomp>(.0)
    382 
    383         whd_list = [c.get_extent(renderer)
--> 384                     for c in self.get_visible_children()]
    385         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    386 

~/FOSS/matplotlib/lib/matplotlib/offsetbox.py in get_extent(self, renderer)
    253         Return with, height, xdescent, ydescent of box
    254         """
--> 255         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    256         return w, h, xd, yd
    257 

~/FOSS/matplotlib/lib/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    479         xoffsets = xoffsets - xdescent
    480 
--> 481         return width + 2 * pad, height + 2 * pad, \
    482                xdescent + pad, ydescent + pad, \
    483                list(zip(xoffsets, yoffsets))

TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

**Comment by dstansby** [comment]
I think we've unearthed a ~10 year old bug!

**Comment by ImportanceOfBeingErnest** [comment]
1/ The same position is obtained by using `borderaxespad=0`. So I think case A shows the expected legend position, while case B might ignore the default `borderaxespad` for some reason?

2/ I think this is expected. `mode="expand"` would according to the docstring mean:
> If mode is set to "expand" the legend will be horizontally expanded to fill the axes area (or bbox_to_anchor if defines the legend’s size).

Since `bbox_to_anchor` is a 2-tuple, this bbox has no extention (width=height=0). This is precisely reflected by the legend box. 

Possibly relevant here: 
* [this SO question](https://stackoverflow.com/questions/39803385/what-does-a-4-element-tuple-argument-for-bbox-to-anchor-mean-in-matplotlib)) about the 4-tuple
* [This question](https://stackoverflow.com/questions/46710546/matplotlib-expand-legend-vertically) showing the same imploded legend as in case A.

In that sense I would say case A is exactly as expected. One might interprete case B as the problematic case, if any.

**Comment by afvincent** [comment]
Thanks @ImportanceOfBeingErnest As usual, your explanations are very clear :).

TBH, even if A + “expand” is actually consistent with the docstring, I still think that it may be difficult to track for a significant amount of users.

*Besides, my understanding is that the `TypeError` should not occur, but I guess that this is more related to #10476 and should not side track this thread.*
