### ISSUE TITLE
matplotlib works well in ipython note book but can't display in a terminal running

### ISSUE THREAD

**Issue by pipipopo** [matplotlib/matplotlib#7014]
I have installed matplotlib 1.5.1 on my ubuntu 14.04 system from source. The problem is whether I use qt4agg or other aggs, pyplot doesn't work when I run a python script in a terminal. It just doesn't display. But when running on jupyter notebook it works well. How can I fix the problem?

**Comment by jenshnielsen** [comment]
Can you show a simple example. Does your script call show? If you are running matplotlib non interactively as in a script you need to explicitly call show.


import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()

**Comment by pipipopo** [comment]
I do use plt.show.

**Comment by QuLogic** [comment]
> Can you show a simple example.

**Comment by pipipopo** [comment]
I deleted all the matplotlib versions (one from ubuntu and another installed from source) and reinstalled. Now it works. I should test this way earlier. Sorry for this!
