### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#7018]
Website is just showing up a blank white page. The tab shows the standard symbol and "Unicorn! * GitHub". Not sure what is going on.

**Comment by jenshnielsen** [comment]
It seems to be working for me now. The webpage is hosted on github.io so it's most likely a github issue

**Comment by LindyBalboa** [comment]
Hm this is weird. None of my normal browsers are working, but it comes up from within my virtual box?

**Comment by jenshnielsen** [comment]
It may be some sort of caching issue or perhaps you are getting the pages from a broken github cdn?

**Comment by tacaswell** [comment]
Closing as it seems to be working again and maybe a local network issue.

@LindyBalboa Thanks for reporting it though.  We did have an issue a while ago where we lost the DNS on matplotlib.org and the site really was down.

**Comment by LindyBalboa** [comment]
Not sure what happened. But checking back in a few hours later and it is fine.

**Comment by Coder-256** [comment]
It seems that the DNS is malfunctioning again, as the site is down.

**Comment by QuLogic** [comment]
DNS is moving to CloudFlare for TLS support; it might take a little while to propagate.

**Comment by tacaswell** [comment]
https://dnschecker.org/#A/matplotlib.org

It looks like the google DNS is lagging

**Comment by Coder-256** [comment]
It's working now.
