### ISSUE TITLE
How to prevent matplotlib from importing qt4 libraries when only 

### ISSUE THREAD

**Issue by dickreuter** [matplotlib/matplotlib#7021]
I'm currently having problems compiling a solution that contains pyqt5 and matplotlib with pyinstaller. An error is caused by the fact that matplotlib seems to import qt4 libraries even though they are not used (in my case I specify matplotlib.use('Qt5Agg')).

As a result the compiled solution throws an error saying RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class.

This is currently discussed on the pyinstaller issues log as well but we have come to the conclusion that this should probably be solved in matplotlib: https://github.com/pyinstaller/pyinstaller/issues/2174#issuecomment-244609322

Any suggestions how to prevent matplotlib from importing qt4 are appreciated.

**Comment by jenshnielsen** [comment]
Using the QT5 backend should most certainly not import any QT4 modules. 

Can you please provide a minimum example of what you are trying to do that produces this issue along with the information that we asked for in the issue template (Matplotlib version, operating system, python version and so on)

**Comment by tacaswell** [comment]
As I commented on the pyinstaller issue, this is something that needs to be fixed on their side.  It sounds like pyinstaller is just searching the code for imports and can not cope with conditional conflicting imports.

**Comment by dickreuter** [comment]
thanks, makes sense

**Comment by tacaswell** [comment]
Closing as a pyinstaller bug.
