### ISSUE TITLE
Python 3.5.2 crashes when launching matplotlib 1.5.1

### ISSUE THREAD

**Issue by arosen93** [matplotlib/matplotlib#7041]
I am running Python 3.5.2 via 64-bit Anaconda on Windows 10. All packages have been updated using `conda update --all`. Anytime I try to make a plot via matplotlib 1.5.1, I get an error identical to the one [here](http://stackoverflow.com/questions/36712654/python-crashing-while-launching-matplotlib) that simply says "Python has stopped working" with no other information. I tried uninstalling Anaconda and reinstalling it to no avail. The issue does not occur for .py files without matplotlib. This issue seems to have started today for me.

Running the following replicates the issue:
`import matplotlib.pyplot as plt`
`plt.plot([1,2,3],[4,1,2])`

**Comment by jenshnielsen** [comment]
I would guess this is most likely related to the GUI framework that matplotlib is using. I would think this is PyQT4 per default on Windows.

What happens if you execute something like
```
from PyQt4 import QtCore, QtGui
```

**Comment by arosen93** [comment]
I am able to execute the line you wrote (matplotlib issue still persists). Interestingly, when I try to launch Spyder, that also comes up with the same crash, so clearly something GUI-related is the issue.

**Comment by jenshnielsen** [comment]
That line is only the first part of the QT import (on PyQt4) so it's most likely something that happens later

**Comment by tacaswell** [comment]
Does this only happen in spyder, the notebook, in an python prompt or in an IPython prompt?

If you do

```
conda create -n clean_test python=3 matplotlib ipython
activate clean_test
python -c 'import matplotlib.pyplot as plt; plt.plot(range(5))'
```

does that work?

**Comment by arosen93** [comment]
The issue happens everywhere -- command line, Python prompt, and IPython prompt. I can't even load Spyder though.

I created the virtual environment per your instructions and ran it exactly and came to the same issue. I created a virtual environment for Python 2 as well and the issue remains.

**Comment by efiring** [comment]
1) The issue does not seem to be in any way specific to matplotlib, so I am going to close it.
2) Given that you can't load Spyder, it sounds like it is probably related to Qt libraries.
3) Given that you said "it seems to have started today", I suspect that some other software installation or Windows update has created a conflict or left a broken dll.  Unfortunately, I don't know how to go about trouble-shooting for that possibility.

**Comment by efiring** [comment]
You could try posting to the Anaconda support mailing list; someone there might have more ideas.
