### ISSUE TITLE
location of convert in rcparams on windows

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7044]
Related to #6523 #6767

Due to the name conflict between 'convert' from image magic there is some import-time configuration get gets done on windows (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/animation.py#L682) .  These changes can get cleared by the style module.

This function should probably reach in and change the defaults or style.use needs to be aware of this issue.

**Comment by QuLogic** [comment]
Closed by #7306.
