### ISSUE TITLE
Documentation for withStroke

### ISSUE THREAD

**Issue by magnunor** [matplotlib/matplotlib#7064]
I was trying to figure out how to avoid gaps in "borders" around text, as explained in https://stackoverflow.com/questions/39391592/gaps-in-border-around-text

Tryph found the solution, and posted it in the answers there. So I'm thinking it would be useful to improve the doc-string and/or documentation for `matplotlib.patheffects.withStroke` (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/patheffects.py#L177).

I'm happy to do this, but I'm wondering what would be the best place to add some info about it? I'm guessing the doc-strings themselves, and possible somewhere in the documentation?

**Comment by tacaswell** [comment]
The docstring would be a good place as would http://matplotlib.org/devdocs/users/patheffects_guide.html (which is sourced from https://github.com/matplotlib/matplotlib/blob/master/doc/users/patheffects_guide.rst)

Thanks for taking this on, we :heart: documentation extensions / fixes!

**Comment by magnunor** [comment]
Sounds good!

I'm a little bit confused about the relation between:
* `Stroke`: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/patheffects.py#L177
* `withStroke`: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/patheffects.py#L203

Since both work similarly, except `Stroke` gives thicker lines, given the same `linewidth`:
```Python
import matplotlib.pyplot as plt
import matplotlib.patheffects as patheffects

fig, axarr = plt.subplots(2)
axarr[0].text(
        0.1, 0.5, "test: S6",
        color='white',
        fontsize=90,
        path_effects=[patheffects.withStroke(linewidth=13, foreground='black', capstyle="round")])
axarr[1].text(
        0.1, 0.5, "test: S6",
        color='white',
        fontsize=90,
        path_effects=[patheffects.Stroke(linewidth=13, foreground='black', capstyle="round")])
fig.savefig("text_stroke.png")
```
![text_stroke](https://cloud.githubusercontent.com/assets/1690979/18356547/03aedd3c-75e5-11e6-8a29-1d741b74f79e.png)

**Comment by rougier** [comment]
From the image it seems that the first goes outside the shape only while the second goes both ways.

**Comment by Kojoley** [comment]
> From the image it seems that the first goes outside the shape only while the second goes both ways.

On the second image there is no actual text, only stroke.

http://matplotlib.org/api/patheffects_api.html#matplotlib.patheffects.withStroke

> Adds a simple Stroke and then draws the original Artist to avoid needing to call Normal.

**Comment by rougier** [comment]
Thanks for the precision.

**Comment by QuLogic** [comment]
#15515 added consistent docs on all `with*` effects, since they are all generated from the base effect.
