### ISSUE TITLE
enh: additional colorblind-friendly colormaps

### ISSUE THREAD

**Issue by drammock** [matplotlib/matplotlib#7081]
I've seen a lot of activity around colorblind-friendly colors (#2871, #6254) and simulation of colorblindness (#3279).  I wonder if you would also like [the colorblind-friendly colormaps published by Paul Tol](https://personal.sron.nl/~pault/colourschemes.pdf) which I have recently implemented for myself [here](https://github.com/drammock/colorblind/blob/master/colorblind.py).  Sample plot:

![test_colormaps](https://cloud.githubusercontent.com/assets/1810515/18402215/48f817ec-7693-11e6-84bb-44e32c54e42c.png)

The two bottom rows are the matplotlib versions, done via `ListedColormap` -> `register_cmap` -> `imshow(..., cmap=get_cmap(...))`.  I could easily add the data for these 3 colormaps as a PR into [`_cm_listed.py`](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm_listed.py).  Are you folks interested?

postscript: It would be great to get the discrete palettes in there too, but I'm not sure if they will work as `cycler`s, since the color values can change as the number of levels increases (see, e.g., the blue change in the jump from 4 to 5 in the qualitative palette). But to be honest I haven't tried yet... it could be a separate PR if there's interest.

**Comment by tacaswell** [comment]
That seems reasonable, except for the rainbow.  

I am curious how the there perform when put into `viscm`?

What is the licensing on the republishing of these color schemes?

Something along the lines of https://github.com/matplotlib/cmocean with these color maps shipping in their own package maybe more appropriate.

**Comment by drammock** [comment]
Wow, `viscm` is an amazing tool I didn't know about before.  Here is how they perform (not as well as I expected, in fact):

![diverging](https://cloud.githubusercontent.com/assets/1810515/18420881/15cc1daa-7832-11e6-9fbb-ffb35ca2091e.png)

![sequential](https://cloud.githubusercontent.com/assets/1810515/18420883/1c1a0cf8-7832-11e6-88b3-07d42c8d37b2.png)

![rainbow](https://cloud.githubusercontent.com/assets/1810515/18420884/20b26530-7832-11e6-8692-c659a14e218a.png)

The original tech note does not have a license, but a personal communication with its author said attribution (name + website) was acceptable.

**Comment by drammock** [comment]
It was just pointed out to me that the sequential and diverging maps here are very similar to what is already available in matplotlib (sequential is basically the same as `YlOrBr` and diverging is quite similar to `RdYlBu`).  Closing as redundant / already implemented.

**Comment by lrq3000** [comment]
The qualitative seems different, maybe this one at least could be merged in?

**Comment by drammock** [comment]
@lrq3000 the qualitative one will not work as a matplotlib `cycler` because the recommended color values change depending on how many colors you want; cyclers can't do that.

**Comment by lrq3000** [comment]
@drammock Ah ok thank you for the info, that's a shame :-(
