### ISSUE TITLE
Allow adding artist to axes with `+=` operator

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#7082]
``` python
############## Add `+=` operator to Axes class ############

def adder(self, artist):
    self.add_artist(artist)
    return self

from matplotlib.axes._base import _AxesBase
_AxesBase.__iadd__ = adder

######################### Showcase ########################

import matplotlib.pyplot as plt
from matplotlib.patches import Circle

fig, ax = plt.subplots()
# ax.add_artist(Circle((.5, .5), .3))
ax += Circle((.5, .5), .3)
plt.show()
```

What do you think about that?

**Comment by tacaswell** [comment]
Tentatively :+1: 

Should be coupled with the now 2 year old discussion of re-organizing how we hold artists internally and how we deal with compound artists.

**Comment by anntzer** [comment]
I'd rather first fix the fact that different artists have different add methods (`add_line`, `add_image`, `add_artist`) before adding more API (but once (and only once) it's fixed, I'm +1 for it).

**Comment by timhoffm** [comment]
Adding artists is rare enough for the average user, so that the explicit `ax.add_artist()` is not much of a burden.

In the capacity as API lead, I decide that we do not need an additional '+' logic.
