### ISSUE TITLE
DOC (released) style is badly broken on the user doc.

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7086]
See:
http://matplotlib.org/users/index.html

**Comment by Kojoley** [comment]
```html
<link rel="stylesheet" href="_static/mpl.css" type="text/css">
<link rel="stylesheet" href="_static/pygments.css" type="text/css">
```
`href` here must start with `/`, the fix is probably should be in [this line](
https://github.com/matplotlib/matplotlib/blob/2d1e51fe81e49e6c861c43182057c2964bbfce00/doc/conf.py#L188)

**Comment by tacaswell** [comment]
http://matplotlib.org/1.5.0/users/index.html is fine
http://matplotlib.org/devdocs/users/index.html is fine

This makes me think that this is an issue with the version of sphinx I built the docs with.

**Comment by NelleV** [comment]
Interestingly, it seems to be the only page like this… I checked several and couldn't find any others

**Comment by tacaswell** [comment]
I am in the process of building the 1.5.3 docs.  Once that is done I will re-generate the 1.5.1 docs

**Comment by NelleV** [comment]
Thank you so much! It is now fixed.
