### ISSUE TITLE
matplotlibrc reader cannot handle rcparams with a hash

### ISSUE THREAD

**Issue by has2k1** [matplotlib/matplotlib#7089]
The parser for the `.mplstyle` files is eager when identifying comments. A `#` always demarcates the beginning of a comment, therefore it cannot be part of an `rcparam`.

Reference: https://github.com/matplotlib/matplotlib/pull/6907#issuecomment-246133854
The reader function: https://github.com/matplotlib/matplotlib/blob/af16ac8/lib/matplotlib/__init__.py#L1055
Example style file: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/stylelib/classic.mplstyle#L183

**Comment by tacaswell** [comment]
Maybe we should just use json or yaml for the style files?

**Comment by WeatherGod** [comment]
not json... and yaml brings in another dependency (but it isn't that
onoerous...). ConfigParser is now in the standard library, and it could
bring for us string interpolation features (which I have been wanting for a
while).

On Sun, Sep 11, 2016 at 12:02 PM, Thomas A Caswell <notifications@github.com

**Comment by has2k1** [comment]
Comparison of potential options.

                       | YAML | JSON | ConfigParser
-----------------------|------|------|-------------
No Extra Dependency    | No   | Yes  | Yes
Interpolation          | Yes  | No   | Yes
Inline comments        | Yes  | Yes  | Yes[1]



**Caveats**

1. Cannot be used for entries that have only keys(and no values).

**Comment by efiring** [comment]
It doesn't look to me like ConfigParser provides facilities for gracefully handling the problem of an inline hash that starts a comment unless it is inside a string.  YAML looks like a pretty big hammer.  I think I would rather leave the existing restriction against having the hash in a value than introduce a new dependency and a new set of rules for matplotlibrc and style files.

**Comment by WeatherGod** [comment]
JSON can not support inline comments

**Comment by anntzer** [comment]
I'm going to make a possibly not so popular but actually serious proposal: if we do decide to change the config format, simply switch to using python source files as style and config formats.

Pros:
No extra dependency, interpolation, inline comments (duh).
Basically anything you will ever need.

Cons:
AFAICT the main con I have heard about is the security issue.  But the current parser is *already* unsafe (See link from OP in #6274 (Yes, I know that PR also proposes a custom PyParsing-based parser -- I guess that would be a pretty big hammer...)).  Additionally, a number of prominent projects (e.g. IPython, Sphinx, Django) already use python for config files without this turning out to be a real problem.

**Comment by jenshnielsen** [comment]
This should also be coordinated with the traitlets work https://github.com/matplotlib/matplotlib/pull/4762 Afaik the IPython config files are traitlets based

**Comment by davenquinn** [comment]
Why not just make yaml an optional parser for the matplotlibrc reader, if installed? The amount of code to convert to the current RC code is minimal, and we could integrate them more closely over time if needed.

I've already made a basic parser for this type of data for use in a project, it seems to work fine for basic datasets:

```
with open(fn) as f:
    style_object = yaml.load(f)
for k,v in style_object.items():
    matplotlib.rc(k,**v)
```

...which reads YAML configuration files as below into matplotlibrc.
```yaml
font:
  size: 8
  family: [sans-serif]
  sans-serif:
    - Helvetica Neue
    - Helvetica
    - Arial
    - sans-serif
  weight: 200
mathtext:
  default: regular
axes:
  labelsize: 8
  titlesize: 12
  facecolor: white
  grid: false
  edgecolor: black
```

A more bulletproof parser would probably take some effort, but I imagine not much. Happy to submit a pr if it seems like a good plan.

**Comment by anntzer** [comment]
My personal opinion is that yaml is a far too complex language for any purpose (see e.g. http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines).

**Comment by WeatherGod** [comment]
and why is having multiple ways to do a multi-line string a bad thing?
There are a few things I don't like about YAML, but that isn't one of them.

**Comment by anntzer** [comment]
This is just an example amongst others of the extreme complexity of the language.  For example, would you know whether
```
- % foo
```
is valid yaml?  if so, what does it evaluate to?  what about
```
- foo % foo
```
?

**Comment by davenquinn** [comment]
YAML is a pretty standard config language for many projects, and trying to reinvent the wheel when a standard tool can be adapted to the system is unnecessary.

@anntzer: we don't have to support the entire feature-set of YAML or handle edge cases for it to be useful nonetheless

**Comment by oscargus** [comment]
In #22589 support for quoted strings was introduced, which then allows including a hash. Will close this for now.
