### ISSUE TITLE
pyplot.scatter method is not working with Iterator types of an input arguments

### ISSUE THREAD

**Issue by b0noI** [matplotlib/matplotlib#7092]
There is an issue with `pyplot.scatter` that prevents migration from Python 2.x to Python 3.x:

``` Python
# Works perfectly on Python2.x since map(...) returns list. 
# However same code does not work with Python3.x
pyplot.scatter(map(lambda x: x[0], circles[0]), 
               map(lambda x: x[1], circles[0]), 
               c = circles[1], 
               cmap = colors)
# Fix that works with Python3.x, however correct way would be to fix pyplot.scatter
# and make it work with the Iterators.
pyplot.scatter([x[0] for x in circles[0]], 
               [x[1] for x in circles[0]], 
               c = circles[1], 
               cmap = colors) 
```

```
matplotlib.__version__
'1.5.1'
```

**Comment by tacaswell** [comment]
There are a number of places in mpl where we require the ability to go over an input more than once (not even that `__getitem__` behaves correctly with integers, just that `next(iter(inp))` is safe to do) and that `np.asarray(inp)` works correctly.  Neither of those is true `Iterator` or `generator` inputs. 

I think we would consider a PR that does some sanitation of inputs (we recently added code to support dict views to master).

I would argue that the list comprehension is the better choice anyway.  Or just wrap the `map` in a `list` (which is what many of the automated tools do for you).

**Comment by efiring** [comment]
In cbook:
```python
def sanitize_sequence(data):
    """Converts dictview object to list
    """
    if six.PY3 and isinstance(data, collections.abc.MappingView):
        return list(data)
    return data
```
I think that changing the second argument of `isinstance` to `(collections.abc.MappingView, collections.abc.Iterator)` would do the trick.  I don't know if it would have any bad side effects.  If this is all that is needed, I wouldn't object to it; but if handling iterators requires anything more complicated, then I would argue for leaving the conversion responsibility with the user.

**Comment by story645** [comment]
I didn't do that 'cause then it'll catch lists and it'll end up double casting. I'd kind of vote for (since it's made for this anyway, adding a second if statement check specifically for whatever type map returns (I think generator?)

**Comment by b0noI** [comment]
@story645 @efiring it returns type map:
```Python
x = range(0, 100)
m = map(lambda x: x ** 2, x)
print(type(m))
isinstance(m, map)
```

Output:
```
map
True
```

so the solution might be:
```Python
def sanitize_sequence(data):
    """Converts dictview object to list
    """
    if six.PY3 and isinstance(data, (collections.abc.MappingView, map)):
        return list(data)
    return data
```

**Comment by b0noI** [comment]
Probably title of the issue should be: "pyplot.scatter method is not working with *map* types of an input arguments"

**Comment by story645** [comment]
@b0noI is this issue specific to PY3? Otherwise, it probably needs its own if statment

**Comment by b0noI** [comment]
@story645 yep, since on Python2.x map is not lazy and returns list:
```Python
>>> l = range(0, 10)
>>> l = map(lambda x: x ** 2, l)
>>> l
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
```

**Comment by efiring** [comment]
@story645 
```python
In [2]: xx = map(lambda x: x+1, [1,2,3])

In [6]: isinstance(xx, collections.abc.Iterator)
True
In [7]: isinstance(list(), collections.abc.Iterator)
False
```

**Comment by story645** [comment]
So checked out why I didn't use Iterator in the first place, which is that it won't work for MappingViews.
>>> a = {'a':1}
>>> a.keys()
dict_keys(['a'])
>>> isinstance(a.keys(), collections.abc.Iterator)
False
```
 But since Iterator won't catch lists, I guess ``isinstance(data, (collections.abc.MappingView, collections.abc.Iterator))``` is probably the most optimal construction.
```Python

**Comment by anntzer** [comment]
Note that it is perfectly legal to construct infinite iterators (including, on Py3, by calling `map` on an infinite sequence)... in which case calling `list` on it is likely going to lead to matplotlib hanging.
It is a well known pattern that when porting Py2 code to Py3, calls to `map` should typically be replaced by `list(map(...))`.  IIRC even the venerable 2to3 handles this.
So I'm -1 on special casing maps.

**Comment by b0noI** [comment]
@anntzer so then probably best option would be to add some sanitation, as was proposed by @tacaswell , I will try to prepare a PR during the upcoming weekends.

**Comment by efiring** [comment]
I don't understand how one could perform sanitization that would address @anntzer's point.  For example, if given a `map` object, I suspect the only way to find out whether its iteration has an end is to try turning it into a list and see whether you land in an endless loop.  A `map` object is completely opaque, as far as I can see.  So I think the choices are between doing nothing and adding my originally-suggested modification to `sanitize_sequence`.

**Comment by anntzer** [comment]
I think you need to check for the `Sequence` abc, not `Iterable` (`map` is an iterable).

**Comment by efiring** [comment]
Map is an Iterator (and an Iterable), not a Sequence, and the whole point of @b0noI's complaint is that he wants to allow a map.  As you say, there is no way to do that without opening the door to an infinite loop.   And we can't use a check for a Sequence to determine whether an input is allowable because objects like numpy arrays do not inherit from collections.abc.Sequence.

**Comment by b0noI** [comment]
@efiring +1, infinite loop should not be possible. Then, and probably it should be documented as a new issue, at least method should have some type checks for the input arguments. So at least the method would fail fast, with clear explanation. It took some time for me, with current implementation, in order to figure out the root cause.

**Comment by tacaswell** [comment]
A duck-type way to fix this would be to take the `len` of the input.  That should be cheap and `map` and generators will fail-fast.

**Comment by anntzer** [comment]
This is already what 2.0b4 does...
```
In [2]: plt.scatter(map(lambda x: x, [0]), map(lambda x: x, [1]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d175e963a520> in <module>()
----> 1 plt.scatter(map(lambda x: x, [0]), map(lambda x: x, [1]))

/usr/lib/python3.5/site-packages/matplotlib/pyplot.py in scatter(x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, hold, data, **kwargs)
   3253                          vmin=vmin, vmax=vmax, alpha=alpha,
   3254                          linewidths=linewidths, verts=verts,
-> 3255                          edgecolors=edgecolors, data=data, **kwargs)
   3256     finally:
   3257         ax.hold(washold)

/usr/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1874                     warnings.warn(msg % (label_namer, func.__name__),
   1875                                   RuntimeWarning, stacklevel=2)
-> 1876             return func(ax, *args, **kwargs)
   1877         pre_doc = inner.__doc__
   1878         if pre_doc is None:

/usr/lib/python3.5/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   3949             edgecolors = 'face'
   3950 
-> 3951         self._process_unit_info(xdata=x, ydata=y, kwargs=kwargs)
   3952         x = self.convert_xunits(x)
   3953         y = self.convert_yunits(y)

/usr/lib/python3.5/site-packages/matplotlib/axes/_base.py in _process_unit_info(self, xdata, ydata, kwargs)
   1962             # we only need to update if there is nothing set yet.
   1963             if not self.xaxis.have_units():
-> 1964                 self.xaxis.update_units(xdata)
   1965 
   1966         if ydata is not None:

/usr/lib/python3.5/site-packages/matplotlib/axis.py in update_units(self, data)
   1401         """
   1402 
-> 1403         converter = munits.registry.get_converter(data)
   1404         if converter is None:
   1405             return False

/usr/lib/python3.5/site-packages/matplotlib/units.py in get_converter(self, x)
    159                 return converter
    160 
--> 161         if converter is None and iterable(x) and (len(x) > 0):
    162             thisx = safe_first_element(x)
    163             if classx and classx != getattr(thisx, '__class__', None):

TypeError: object of type 'map' has no len()
```

**Comment by b0noI** [comment]
@anntzer I would prefer better failure message though, but apart from it, this looks like it is the best possible solution (and it has been implemented already).

**Comment by anntzer** [comment]
Closing because I don't think there is much to do about the issue, and it looked like @efiring agreed with me.  Feel free to reopen if you disagree.
