### ISSUE TITLE
ordering issues between `set_xmargin` and `set_xscale`

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7093]
As of 2.0b4, the order in which calls to `set(xmargin=...)` and `set(xscale=...)` are made result in different plots:

```
from matplotlib import pyplot as plt
fig, axs = plt.subplots(2)
axs[0].plot([1, 2], [1, 2])
axs[1].plot([1, 2], [1, 2])
axs[0].set(xscale="log"); axs[0].set(xmargin=0)
axs[1].set(xmargin=0); axs[1].set(xscale="log")
plt.show()
```

![20](https://cloud.githubusercontent.com/assets/1322974/18427234/9b01e506-787b-11e6-820c-68e7c8864319.png)

The ordering did not matter in 1.5, but that was because the setting of `xmargin` was effectively ignored :-)
![15](https://cloud.githubusercontent.com/assets/1322974/18427249/b53d8f7e-787b-11e6-8082-d53250c08408.png)

I'm suggesting to milestone this to 2.0, but I'll let someone else make that call.

**Comment by efiring** [comment]
The minor ticks are also missing in the 2.0 example.

**Comment by anntzer** [comment]
That's because the axis span from 1 to 2, so there's no place for minor ticks.

**Comment by jenshnielsen** [comment]
Sounds like this could be related to #6968

**Comment by efiring** [comment]
This is connected to #7413.
