### ISSUE TITLE
Switch to log scale raises exception *after* editing figure options.

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7098]
2.0b4.

```
plot([0, 1, 2])
```

Pressing `l` (switch y to log-scale) results in ignoring the point at (0, 0) for the autoscaling which is a fairly reasonable thing to do.  But after opening the figure options, not editing anything and pressing OK, pressing `l` now results in a crash during the figure redraw (basically because the ylims are now considered to be force-set).
Note that #6983 cannot handle this because the key handler only calls `draw_idle`, so the exception occurs too late to be caught.

**Comment by efiring** [comment]
This also seems to have been fixed.  I can't reproduce it.

**Comment by anntzer** [comment]
There's no crash anymore, but the behavior still changes after opening the figure options window.  Not sure there's much to do about it, though.
