### ISSUE TITLE
BboxObject.union calls class method instead of instance method

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#7101]
python 3.5, mpl 1.5.2

Calling boxObject.union calls the class method, not an instance method. This leads to some awkwardness by needing to repeat the calling object. 

```
import matplotlib as mpl

box1 = mpl.transforms.Bbox([[-1, 1], [-10, 10]])
box2 = mpl.transforms.Bbox([[-10, 10], [-1, 1]])

mpl.transforms.Bbox.union([box1 ,box2]) #Class method 
                                        #output: [[-10, 10], [-10, 10]]
box1.union([box2]) #Expect instance method, instead class method only counts box2 
                   #output: [[-10, 10], [-1, 1]]
box1.union([box1, box2]) #Awkward class method call. 
                         #output: [[-10, 10], [-10, 10]]
```

Since the class method is being called, it expects an array of two Bbox objects. I believe `box1.union(box2)` in addition to `box1.union([array of length >= 1])` should be a valid signature for this function, as unionizing two Bboxes is an extremely common case.

Upon writing this now though, I feel creating an instance method for this might cause backwards compatibility issues. 

This is something I would be willing to tackle, but not within the next 2 weeks. Have a few exams to take care of.

**Comment by tacaswell** [comment]
I would rather go the other way and pull 'union' off of `Bbox` all together, if we change this at all.  `union` has been a static method sense it was first added to the code base by @mdboom in 2007.

**Comment by LindyBalboa** [comment]
I see. What would be the alternative? Making it strictly a function within the mpl.transforms namespace? But then it wouldn't necessarily be tied to Bbox and would need to be called `mpl.transforms.Bbox_union` or similar.

**Comment by anntzer** [comment]
Sounds like a good place for overloading `__add__`?

**Comment by LindyBalboa** [comment]
@anntzer That sounds like a reasonable contribution. But I would still expect that to depend on the class (or de-classed, per @tacaswell's suggestion) method. No sense having the same code in two spots. But `union_box = box1 + box2` is pretty damn logical.

**Comment by WeatherGod** [comment]
I would expect it to follow the same semantics as set() objects. So, |
instead of +.
```
>>> a = {1, 2, 3}
>>> b = {3, 4, 5}
>>> a + b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'set' and 'set'
>>> a | b
set([1, 2, 3, 4, 5])
```

**Comment by LindyBalboa** [comment]
Hm. While | may follow the standard sets syntax, I find that it carries too much meaning as being an "or" operator in python. I think + would keep it more straight forward and simple. 

I wouldn't see the harm in implementing both, but then again, look at how many ways python has to do string formatting...

**Comment by anntzer** [comment]
Actually I would now favor | just like one would use & for intersection.
