### ISSUE TITLE
Problems with anatomy figure on v2.x

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#7113]
Due to several default style changes, there are a few issues with the "anatomy of a figure" example from #7072 when run on `v2.x`.
- Ticks are not shown on the top and right spines, so one of the annotations is now on top of nothing.
- Ticks are outward and overlapping the labels. I'm not totally sure why that's the case. They shouldn't do that by default.
- Markers have no edge. Combined with the white face, they seem to be invisible.

Most of these should be straightforward to fix when I get a chance if no-one beats me to it.

**Comment by efiring** [comment]
While you are at it, you could change the call to `scatter` to a call to `plot`.

**Comment by efiring** [comment]
You have found a major bug: changing the tick length with ax.tick_params does not adjust the tick label locations.
