### ISSUE TITLE
BUG: ax.tick_params change in tick length does not adjust tick labels

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7114]
The problem was found by @QuLogic in #7113.
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.tick_params(length=20)
plt.show()
```

**Comment by WeatherGod** [comment]
Not entirely convinced that it is a bug. With inward facing ticks, I
wouldn't want the tick labels to move just be cause I set a long tick line.
Tick padding is a separate parameter.

**Comment by efiring** [comment]
@weathergod, it's a bug.  The logic is in place to calculate the padding based on tick length and a `_base_pad`, taking into account whether the ticks are inward, outward, or centered.  The calculation just wasn't being updated when the tick length was changed.

**Comment by NelleV** [comment]
eh… Thanks @wafflebot[bot] !
