### ISSUE TITLE
Polar plot cos(2x)

### ISSUE THREAD

**Issue by mpat260** [matplotlib/matplotlib#7120]
Matplotlib version - - [ '1.5.2'] 
install Matplotlib -- auto-install through winpython 3.5 

Code: 
`
import numpy as np
import matplotlib.pyplot as plt
plt.close("all")

x = np.linspace(0.0, 2 * np.pi, 1000)
y = np.cos(2*x)

plt.polar(x, y)
`

Problem: Generates only 2 lobes (not 4 lobes)
Incorrect figures (generated by Matplotlib) and correct figure (by matlab) are attached

[Incorrect(Matplotlib).pdf](https://github.com/matplotlib/matplotlib/files/475583/Incorrect.Matplotlib.pdf)
[Correct(Matlab).pdf](https://github.com/matplotlib/matplotlib/files/475582/Correct.Matlab.pdf)

**Comment by efiring** [comment]
Related to http://matplotlib.org/devel/MEP/MEP24.html, #2203, and many other issues and discussions. The present design of polar axes is based on clipping so that r >= 0.  Overall, I think that polar plotting in mpl could use quite a bit of work.
