### ISSUE TITLE
Updated matplotlib 1.5.3 broken in default Anaconda channel

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#7124]
Our pandas tests on travis started to fail last night on python 3.5 (eg https://travis-ci.org/pydata/pandas/jobs/160584906) with errors in our plotting tests (among others: "ImportError: No module named 'PyQt4'"). 
Compared to the previous build that passed, I noticed the difference in matplotlib and pyqt versions (matplotlib 1.5.1 -> 1.5.3,  pyqt-4.11.4 -> pyqt-5.6.0, qt-4.8.7 -> qt-5.6.0). I could also reproduce this locally with `conda create -n test-mpl python=3.5 matplotlib -c defaults`, then importing matplotlib.pyplot gives the above error.

I am not sure if this has anything to do with matplotlib itself, or rather a broken build in anaconda, but reporting it here to be sure.

**Comment by jorisvandenbossche** [comment]
There is a recent issue about the update of pyqt on the anaconda issue tracker where I also commented: https://github.com/ContinuumIO/anaconda-issues/issues/1065

**Comment by Kojoley** [comment]
Please take a look at the issue #6567.

**Comment by jorisvandenbossche** [comment]
Since it is happening both on travis (and it started to fail on travis after an update of matplotlib and qt) as locally in a fresh conda env (and I don't think I have a custom .matplotlibrc file), I am not sure this is the same issue

**Comment by jorisvandenbossche** [comment]
But indeed, specifying manually the backend, then importing does work:

```
>>> import matplotlib
>>> matplotlib.use('qt5agg')
>>> import matplotlib.pyplot as plt
>>> 
```

Going from this comment https://github.com/matplotlib/matplotlib/issues/6559#issuecomment-224683005, I assume this is an error in the matplotlib recipe in the default anaconda channel to fix the default backend to qt4 while installing qt5.

**Comment by jorisvandenbossche** [comment]
I more specifically reported this as https://github.com/ContinuumIO/anaconda-issues/issues/1068. Will close here as it is indeed (as expected) not a matplotlib issue

**Comment by Kojoley** [comment]
> I assume this is an error in the matplotlib recipe in the default anaconda channel to fix the default backend to qt4 while installing qt5.

According to [this](https://github.com/ContinuumIO/anaconda-recipes/blob/master/matplotlib/rctmp_pyside.patch) it is.
