### ISSUE TITLE
Document input requirements on `Colormap.__call__`

### ISSUE THREAD

**Issue by stonebig** [matplotlib/matplotlib#7129]
Hi,

Experimenting my usual list of test on Matplotlib-2.0.0b4, I get this error
- [x] Matplotlib-2.0.0b4, Python-3.5.2, Windows10, Ipython-5.1.0, Ipywidget-5.2.2, Numpy-1.11.1  and pandas-0.19.0rc1 of of cgohlke, 
- [x] WinPython, matplotlib-3.0.0b4 from cgohlke
- [x]  piece of code and image below
- [x] was ok in WinPython with Matplotlib-1.5.2 (only Matplotlib may have changed since this) 

Error:

```
%matplotlib inline
# Pandas interactive
import pandas as pd
import numpy as np
import seaborn as sns

# create a df with random datas
np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan

# interactive
from IPython.html import widgets
@widgets.interact
def f(h_neg=(0, 359, 1), h_pos=(0, 359), s=(0., 99.9), l=(0., 99.9)):
    return (df
             .style
             .background_gradient(
                cmap=sns.palettes.diverging_palette(
                     h_neg=h_neg, h_pos=h_pos, s=s, l=l, as_cmap=True)
             ).highlight_null()
           )
```

```
C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\matplotlib\colors.py:486: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
```

![matplotlib-20160918a](https://cloud.githubusercontent.com/assets/4312421/18615092/85539ce6-7d9d-11e6-85e4-efa19dd0ad57.PNG)

**Comment by tacaswell** [comment]
Do you have any idea what values are going in when the warning is raised?  If I am reading in right, it looks like the warning is coming out of the `xa < 0` .

**Comment by stonebig** [comment]
the seed paramater generates always the same subset:
![matplotlib-20160918b](https://cloud.githubusercontent.com/assets/4312421/18618440/2be32042-7de7-11e6-8f2b-c9aec1a81ecc.PNG)

**Comment by stonebig** [comment]
maybe it's a practice that is no more allowed ?

**Comment by tacaswell** [comment]
I am pretty sure that this is coming out of numpy.  What version of numpy/pandas do you have installed?

Can you reproduce this without pandas, jupyter, or seaborn?

**Comment by efiring** [comment]
`Colormap.__call__()` is assuming it's input contains no unmasked invalid values.  Normally this doesn't cause a problem because we use `masked_invalid` in enough places that invalid values don't find their way into the __call__ argument. Evidently we need to call `masked_invalid` in even more places, such as this.

**Comment by stonebig** [comment]
I'm using Numpy-1.11.1  and pandas-0.19.0rc1 of of cgohlke.

This test was the what's new in pandas 0.18 presentation of Jeff Reback ... can't find the youtube. Just to say there was no issue with that with previous Pandas/Matplotlib

**Comment by stonebig** [comment]
ok:
- the error is there even if I back-pedal down to Matplotlib-1.5.2,
- the error disappears if I back-pedal to Pandas-0.18.1

**Comment by tacaswell** [comment]
This is some very strange interactions between the libraries.  I am 90% sure that the warning is actually coming out of numpy, but very confused why changing the pandas version affects it.

**Comment by jorisvandenbossche** [comment]
So I could trim the reproducing example down to `df.style.background_gradient()`. 
What this `background_gradient` method more or less does under the hood is the following (and this may have changed):

```
s = df['C']
rng = s.max() - s.min()
cmap = 'PuBu'
low, high = 0, 0
from matplotlib import colors
norm = colors.Normalize(s.min() - (rng * low),
                                s.max() + (rng * high))
normed = norm(s.values)
c = [colors.rgb2hex(x) for x in plt.cm.get_cmap(cmap)(normed)]
```

And it is the last line that triggers the warning. So in any case anything to do with pandas itself anymore (but maybe with a wrong way we call things in matplotlib)

**Comment by jorisvandenbossche** [comment]
So in the above example, `normed` is a masked array but where the data includes a NaN. It is this were the colormap gives a warning:

```
In [3]: plt.cm.get_cmap('viridis')(np.array([np.nan, 1, 0.5]))
/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/matplotlib/colors.py:581: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
Out[3]: 
array([[ 0.267004,  0.004874,  0.329415,  1.      ],
       [ 0.993248,  0.906157,  0.143936,  1.      ],
       [ 0.127568,  0.566949,  0.550556,  1.      ]])

In [5]: plt.cm.get_cmap('viridis')(np.array([np.nan]))
Out[5]: array([[ 0.267004,  0.004874,  0.329415,  1.      ]])
```

A strange thing is that it does not give the warning when it is a array with a single nan value.

Is `cmap` supposed to be able to deal with NaNs? Or should we in pandas filter them out first?

**Comment by jorisvandenbossche** [comment]
Digged a little bit further, in the call method of Colormaps, basically the following happens:

```
In [16]: from matplotlib import cbook

In [17]: X = np.array([np.nan, 1, 0.5])

In [18]: xa = np.array([X])

In [19]: cbook._putmask(xa, xa < 0, -1)
/home/joris/miniconda3/envs/dev/bin/ipython:1: RuntimeWarning: invalid value encountered in less
  #!/home/joris/miniconda3/envs/dev/bin/python

In [20]: xa < 1
/home/joris/miniconda3/envs/dev/bin/ipython:1: RuntimeWarning: invalid value encountered in less
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[20]: array([[False, False,  True]], dtype=bool)
```

So it is indeed just coming from numpy by this comparison with NaNs

**Comment by tacaswell** [comment]
I am unclear what changed that there is now a warning where there was not before.

**Comment by jorisvandenbossche** [comment]
Since it is coming straight from numpy (the last line in my example, pure numpy), I am also not sure.

**Comment by jorisvandenbossche** [comment]
Ah, pandas 0.19.0rc1 no longer suppresses certain numpy warnings as it did before: https://github.com/pydata/pandas/pull/13145. That is probably the reason.

**Comment by jorisvandenbossche** [comment]
Question from the pandas side is then: is `cmap(vals)` supposed to be able to deal with nans? Or should be we deal with the missing values ourselves before passing any data to matplotlib?

**Comment by tacaswell** [comment]
It should be masked on the pandas side, we should clarify the docs on `__call__` if needed.

**Comment by tacaswell** [comment]
@jorisvandenbossche Thanks for doing the leg work to track this down, it is greatly appreciated.

**Comment by jorisvandenbossche** [comment]
No problem! OK, then I keep the issue open on the pandas side and repurposed it to deal with NaN values before passing them to `cmap`

**Comment by QuLogic** [comment]
`cbook._putmask` no longer exists, and `Colormap.__call__` masks NaNs:
https://github.com/matplotlib/matplotlib/blob/4d1cd5e0d8b74968407bdc407043cd19fbdac204/lib/matplotlib/colors.py#L606

The single line reproducer `plt.cm.get_cmap('viridis')(np.array([np.nan, 1, 0.5]))` doesn't warn either, so is there really anything left to do here?
