### ISSUE TITLE
spurious warning with nans in log-scale plot

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7143]
mpl1.5.3 and mpl2.0b4

```
semilogy([1, 2, 3], [1, np.nan, 2], "o")
```

triggers a warning:

```
/usr/lib/python3.5/site-packages/matplotlib/scale.py:93: RuntimeWarning: invalid value encountered in less_equal
  mask = a <= 0.0
```

due to the comparison that involves a nan.  I think this warning should be masked out (likely with the application of a `np.errstate` at the right place), given that nans are (AFAIK) a fully supported mechanism for hiding a point in a plot, and e.g. do not raise any warning in linear scale.

**Comment by efiring** [comment]
I agree.  The function below that one will need the same treatment.  Also `_clip_non_logit` and `_mask_non_logit` farther down.  It's not clear why these pairs of nearly-identical functions are implemented differently.  Direct indexing appears to be faster than using `where`.

**Comment by tacaswell** [comment]
Probably related to https://github.com/matplotlib/matplotlib/issues/7129

Are these warnings new in numpy 1.11?
