### ISSUE TITLE
Values Return From Set Methods

### ISSUE THREAD

**Issue by rmorshea** [matplotlib/matplotlib#7147]
I've decided to review my work merging traitlets into matplotlib https://github.com/matplotlib/matplotlib/pull/4762, and during my rebase I came across this change to `Artist.update`...

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/artist.py#L880

where `update` now handles values returned by setters.

I'm wondering what the motivation is behind these setters with return values, because they are incompatible with `traitlets`. If `traitlets` integration is to continue, these returning setters will need to be deprecated.

cc: @tacaswell, @jenshnielsen, @efiring

**Comment by tacaswell** [comment]
Awesome you have come back to this!  This went in as part of https://github.com/matplotlib/matplotlib/pull/5599/files

I did that out of an abundance of caution to not change a different API.  It looks like there are a handful of setters that do in fact return something.

I do not see why they are incompatible:

```python
def set_foo(self, value):
    self.foo = value
    return self.foo
```

but agree they should go long term.

**Comment by rmorshea** [comment]
@tacaswell by "incompatible" I mean that if returning setters where an actual feature supported by matplotlib, it could not be replicated using traitlets.

This kind of setter could be replicated with `traitlets`:

```python
def set_foo(self, value):
	coerced_value = change_it(value)
	self.foo = coerved_value
	return self.foo
```

However something like this could not:

```python
def set_foo(self, value):
	byproduct = change_it(value)
	self.foo = value
	return byproduct
```

**Comment by tacaswell** [comment]
From a quick skim it looks like all of the returning setters return the same thing as their paired getter (ex `set_title` returns the `Text` object that is the title).

If there are any in the second class I am nominally :+1: on deprecating / addressing on a case-by-case basis.
