### ISSUE TITLE
Labels don't rotate when set by pyplot.subplots

### ISSUE THREAD

**Issue by matanagasauce** [matplotlib/matplotlib#7150]
I expect the code

```
figure, axes = plt.subplots(2, 2, subplot_kw={
    'xticks': range(30),
    'xticklabels': [matplotlib.text.Text(text=date.strftime('%m%d'),
                                         rotation=45) for date in stat_dates_list]
})
```

to perform like this:
![46066c58-fe47-49b1-bfa9-c794a3ef2dcc](https://cloud.githubusercontent.com/assets/17398258/18704339/20f93ad6-801c-11e6-8402-5ce1f821361d.png)

but got:
![2ae8545d-12d3-49de-b6b7-272280fe1c81](https://cloud.githubusercontent.com/assets/17398258/18704819/29e27b24-801e-11e6-8b18-d9ef69dc4e76.png)

And I wrote

```
for ax in axes.flatten():
    for label in ax.get_xticklabels():
        label.set_rotation(45)
```

and finally got what I want.

I look into axis.py and find that in Axes.set_ticklabels, 

```
get_labels = []
for t in ticklabels:
    # try calling get_text() to check whether it is Text object
    # if it is Text, get label content
    try:
        get_labels.append(t.get_text())
    # otherwise add the label to the list directly
    except AttributeError:
        get_labels.append(t)
# replace the ticklabels list with the processed one
ticklabels = get_labels
```

It totally ignores the kwargs of `t` if `t` is `Text` like what's in my code above.
I think it would be more reasonable if it got not only the label content but also other kwargs if it is Text.

**Comment by efiring** [comment]
I can see why one would expect this.  I think the reason it is not implemented this way is that many of the Text object properties need to be customized depending on the tick type and location.  Rather than make the code much more complex to handle this, I think we should deprecate the use of `Text` type as a valid input, and require plain strings instead.  In practice we gain nothing but useless complexity and confusion by allowing `Text` while ignoring everything but its string content.  That's my first reaction, but I'm open to alternatives.

**Comment by Kojoley** [comment]
Well, I was hitted by this a while ago too. There are two problems here from my point of view:
  - `set_ticklabels`  should not accept `Text` objects
  - we cannot put kwargs in `xticklabels` (along with label strings) that will be passed to `set_ticklabels` at `Axes` instantiation

**Comment by efiring** [comment]
We have an API for setting tick label rotation and other properties in a single method. E.g.,
`ax.tick_params(axis='x', which='minor', labelsize='small', labelcolor='m', rotation=30)`.

**Comment by Kojoley** [comment]
Yes, but you have spread calls in different places of you code instead of one concentrated call.

**Comment by efiring** [comment]
On 2016/09/21 7:38 AM, Nikita Kniazev wrote:
> Yes, but you have spread calls in different places of you code instead
> of one concentrated call.

True, but it is better than having to construct an explicit loop over 
the ticks.  And it is a single call that can configure ticks and labels 
together.
