### ISSUE TITLE
bar graph with nan values leads to "No current point in closepath" in evince 

### ISSUE THREAD

**Issue by e-dschungel** [matplotlib/matplotlib#7154]
I want to plot a bar graph which contain some nan values and save it to PDF. If I open the file in evince it shows several errors like  "Syntax Error (596): No current point in closepath"  on the console but plot is shown as expected. This only happens with the pdf backend, cairo pdf backend works. I think this is related to #3654.
 
I'm on Matplotlib 1.5.1 (installed via pip), python 2.7.6, Linux

Example code:
```python
#!/usr/bin/env python

import matplotlib.pyplot as mpl

fig = mpl.figure()
ax = fig.add_subplot(111)
bars = ax.bar([1], [float("NaN")], 0.2)
mpl.savefig("test.pdf")
```

**Comment by Kojoley** [comment]
Cannot reproduce it with mpl 1.5.1 and Foxit Reader.

**Comment by QuLogic** [comment]
Also tried with mpl 1.5.2 and evince 3.20.1 and there are no warnings using this code.

**Comment by e-dschungel** [comment]
@QuLogic did you start evince in foreground/nondetached?
BTW: My evince is 3.10.3.

**Comment by tacaswell** [comment]
This may be fixed by https://github.com/matplotlib/matplotlib/pull/5911 ?

**Comment by tacaswell** [comment]
@e-dschungel 1.5.3 is available via pip, can you try updating?

**Comment by QuLogic** [comment]
I just tried with 1.5.1 and even 1.4.3 and also see no warnings. There is just an empty plot, as expected.

@e-dschungel I think the only course might be to update your system; evince 3.10.3 and Python 2.7.6 are fairly old at this point.

**Comment by tacaswell** [comment]
I also can not reproduce this (but also with evince 3.20.1) either with mpl2.x + py3.5 or mpl1.5.1+py2.7.6 (from conda).

Closing as not reproducible.  

@e-dschungel Thank you for reporting this, sorry we can not reproduce it to provide a fix!

**Comment by e-dschungel** [comment]
Thanks for the quick responses.
Some more information for the record: upgrading to mpl 1.5.3 does not help.
Upgrading to a more recent system with Python 2.7.12, mpl 1.5.2rc2 and evince 3.20.1 does.
