### ISSUE TITLE
use categorical in demos

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7155]
Update examples/lines_bars_and_markers/barh_demo.py to use categorical functionality.

attn @story645

**Comment by story645** [comment]
Ugh, I know, just have to get out a draft for school stuff first.

**Comment by tacaswell** [comment]
This would also be good for a new contributor to work on.  

Was not trying to assign this to you, just keeping you in the loop and making sure a new person would know who to ask questions.

**Comment by NelleV** [comment]
That be great for one of my students.

**Comment by story645** [comment]
Awesome! There's also another task on my todo list that's probably well suited to your students, which is that matplotlib sorely lacks "Basic Plots" gallery. It'd consist of line, scatter, bar, pie, heatmap (so the fundementals) and be limited to 3-5 lines of code.

**Comment by NelleV** [comment]
Awsome! There are settled for a couple of weeks!

**Comment by story645** [comment]
Also, out of curiosity, but is there anywhere with details on this class? 

At some point I started going through the backlog of issues to get acquainted  with the code base and started marking stuff that [seemed stalled](https://docs.google.com/spreadsheets/d/1PkxqqVAzrWuGtQ1KJJ-RrrnA17wMRniy1W4gVPOBSK0/edit?usp=sharing) and I wonder if there'd be any interest in anyone else getting involved with the housekeeping. That should probably just be labeling anything that's stalled as "needs followup", but still...

**Comment by NelleV** [comment]
@story645 It is not really a class, but a URAP program (undergraduate research associate program, I assume) at UC Berkeley. I only arrived at UC Berkeley a couple of months ago, and the program was not running this summer, so I am pretty much discovering how we're organizing ourselves at the same time as the students.
This semester, students will be divided in three teams: the first team will be working on scikit-image, under the supervision of Stéfan van der Walt. The second team will be working on feature extractions of fMRI scans of subjects listening to music to gain understanding of how the brain models music, and the last team will be working on matplotlib.
Stéfan and I will be training the students, to get them up to speed on different requirements (git, github and numpy mostly). We'll then divide them up by pair. The goal is to have them do a number of tasks to help them develop their skills and understanding of how working on opensource works. These include (1) code reviews, (2) bug fixing, (3) documentation writing, (4) unit testing, (5) feature integration.
We'll divide the students into pairs, and assign them (or to a queue) a limited number of tickets. Once a task is resolved, a new one will be added to the queue, the idea being to encourage collaboration amongst the students if some are stuck on a bug as well as to encourage pair coding and code review.
We'll have one weekly meeting (and I'll hold office hours), accompanied by a public blogpost on a weekly status of progress (typically containing what students have achieved during the week, roadblocks, and what they plan to do for the following week).

I'll try to get our website up and running with these explanations as soon as I find it. I'll also send an email to the dev mailing list with more information on this initiative

@tacaswell had given me that list already! Thanks for putting this together, that's going to be super useful.

**Comment by NelleV** [comment]
@story645 Is the "basic plot" task opened as a ticket somewhere?

**Comment by story645** [comment]
No, do you want me to create one?

**Comment by story645** [comment]
Also, some examples of categorical: http://story645.github.io/

**Comment by story645** [comment]
I think @choldgraf did this already?

**Comment by choldgraf** [comment]
well there's https://matplotlib.org/gallery/lines_bars_and_markers/categorical_variables.html now, so I think this can be closed
