### ISSUE TITLE
Inverted imshow using Cairo backend

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#7156]
In testing some stuff for #7151, I realized that the Cairo backend inverts images plotted using `imshow`.

```python
import matplotlib as mpl
mpl.use('Cairo')
import numpy as np
import matplotlib.pyplot as plt

a = np.random.randn(3,3)

im1 = plt.imshow(a, extent = [0,1,0,1])
plt.xlim(0,2.2)
plt.ylim(0,2.2)

plt.savefig('test.png')
```

It doesn't really matter if saving as png or pdf, the outcome is the same. With Agg, the image appears in the lower left corner:
![test](https://cloud.githubusercontent.com/assets/302469/18736364/627d4f5a-8054-11e6-9698-4be3ebe8e4ab.png)
With Cairo, the image appears in the upper left corner:
![test](https://cloud.githubusercontent.com/assets/302469/18736371/790b7800-8054-11e6-82c0-a03097fb30f6.png)

It worked correctly with mpl 1.4.3 and is broken with 1.5.0, but bisection is next to impossible because the Cairo backend was broken for a very long time.

**Comment by QuLogic** [comment]
I'm going to ping @jenshnielsen who seems to have last had contact with the cairo backend.

**Comment by tacaswell** [comment]
I can not reproduce this on 2.x with py3.5 and cairocffi

![test](https://cloud.githubusercontent.com/assets/199813/19288524/694f2d1e-8fd4-11e6-8539-05b9fd623116.png)

Please ping to have this re-opened if there is some combination of 2.x + py + cairo binding that fails.

**Comment by QuLogic** [comment]
Oh, I thought I tested with v2.x at some point, but it looks like you're right. It appears to have been fixed with the ever-growing list of things from #5718.

**Comment by tacaswell** [comment]
The dragon infested rabbit holes are paying for them selves in recovered technical debt.
