### ISSUE TITLE
should fill_between Cycle?

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#7157]
Prompted by @tacaswell tweet with the draft of [new style changes](http://matplotlib.org/devdocs/users/dflt_style_changes.html) I saw the following:

> The following changes were made to the default behavior of scatter
> [...] if the color of the markers is not specified it will follow the property cycle, pulling from the ‘patches’ cycle on the Axes.

It reminded me that I recently was surprised by `fill_between` not cycling.
is that on purpose, or do you want to be consistent across API for 2.0 ?

My search-foo did not turn any discussion about that...

**Comment by tacaswell** [comment]
I am :+1: on adding that.  should probably follow the patch cycle.

**Comment by WeatherGod** [comment]
Yeah... that is surprising, considering that ax.fill() does cycle.

**Comment by Carreau** [comment]
Could it be related to the fact that `c='c2'` fails as well ? 
I'm going to assume `fill_betweenx` is affected as well...

**Comment by tacaswell** [comment]
@Carreau it needs to be `'C2'`

**Comment by Carreau** [comment]
Ouch, what does `c0` and `c1` do both change color (in my graph to C9) and not raise. What id lower case `c` supposed to be ?

**Comment by Carreau** [comment]
> Ouch, what does c0 and c1 do both change color (in my graph to C9) and not raise. What id lower case c supposed to be ?

Oh, `c0`, and `c1` get interpreted as a 2-cycle `cyan-black` and `cyan-white`... and `cyan` is close to the default `C9`. Sorry.

**Comment by tacaswell** [comment]
How exactly are you using this?

**Comment by Carreau** [comment]
Like so, the lowercase uppercase `c0` vs `C0` make sens. Problem was me. I can see though how in some case it can be confusing for users. 
```
%matplotlib inline
from matplotlib.pyplot import subplots
from numpy import arange
fig, ((ax1, ax2),(ax3, ax4)) = subplots(2,2)
x = arange(10)

ax1.fill_between(x,0*x, x, label='1')
ax1.fill_between(x,x, x*0+10, label='2') 
ax1.legend()
#this is blue/blue 

#think: Oh, i actually want to change the color
ax2.fill_between(x,0*x, x, label='3')
ax2.fill_between(x,x, x*0+10, facecolor='c1', label='4')
ax2.legend()

# great it's blue/cyan, I let's try c2:
ax3.fill_between(x,0*x, x , label='5')
ax3.fill_between(x,x, x*0+10, facecolor='c2', label='6')
# get confused as to why it does not change ?
# legend would – rightfully –  raise also
# ax3.legend()

ax4.scatter(x,x, color='c0', label='7')
ax4.legend()
# he you can see it actually cycle through colors.
```

**Comment by tacaswell** [comment]
I see why it does that (it is in `matplotlib.colors.to_rgba_array`), but am not sure if that is a feature or a bug.....

**Comment by Carreau** [comment]
> but am not sure if that is a feature or a bug.....

I agree... I guess I would try to catch that at the right place and we-reraise with potentially some heuristics like `did you meant uppercase C`.

It will likely be annoying is users start to actually use `c0`, `c1` when they meant to use `C0` and `C1`... arguably for some things (like fill_between) you can guess that a cycle is (likely) wrong. But on things like scatter it can make sens.
