### ISSUE TITLE
matplotlib.ticker.FormatStrFormatter clashes with ax2.set_yticklabels when dual y-axis is used

### ISSUE THREAD

**Issue by FilipDominec** [matplotlib/matplotlib#7161]
- [x] Matplotlib version 1.5.1-1ubuntu1, Python version2.7.12, Platform Ubuntu 16.04 x64
- [x] I installed Matplotlib and Python from apt repository
- [x] Example:

```
#!/usr/bin/python3  
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

fig = matplotlib.pyplot.figure(figsize=(7,4), dpi=96, facecolor='#eeeeee', tight_layout=1)
ax = fig.add_subplot(111) 

x = np.arange(0., 10., 0.1)
ax.plot(x, 12+x**1.5+0.1*x**2.5)

## Simple axes
ax.set_xlabel('expected maximum load (kg)')
ax.set_ylabel('needed bar diameter (cm)')

ax2 = ax.twinx()
ax2.set_ylabel('bar cross-section (cm$^{2}$)')

## left and right y-axes apply to the same data, but the right one has a given functional dependency on the left one
## (in this example, right ticks share the position with the left ticks)
ylim2 = ax.get_ylim()
print(ax.get_ylim())
ax2.set_ylim(ax.get_ylim())
def tick_function(r): return r**2 + 0.123 # 10.46*(p**1.68)
ax2.set_yticks(ax.get_yticks()[:-1])
ax2.set_yticklabels(tick_function(ax.get_yticks()[:-1]))

## ERROR? When uncommented, the values on the secondary y-axis are not processed by tick_function!
ax2.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%.2g$\\pm \\beta$'))

## Finish the plot + save 
ax.set_title("with custom matplotlib.ticker.FormatStrFormatter")
ax.grid()
ax.legend(prop={'size':10}, loc='upper right')
fig.savefig('with_formatter_error.png')

```

In short,  I define dual y-axes of a plot, and need the right y-axis to show some given function of the left one. But when I try to format the right axis using the `FormatStrFormatter` class, it takes the values which are *not processed* by my function. 

I consider this to be a bug, preventing me from defining the values as `100.123+β`, `400.123+β`, `900.123+β` ... on the right axis. None of the attached example figures is therefore acceptable.  

Exchanging the order of the `ax2.set_yticklabels` and `ax2.yaxis.set_major_formatter` does not help. Switching to python2 does not help either. I did not test the latest git version yet. 

![without_formatter_correct](https://cloud.githubusercontent.com/assets/511950/18752032/676592ce-80e1-11e6-8568-3b2dcbd40394.png)
![with_formatter_error](https://cloud.githubusercontent.com/assets/511950/18752038/6a30e0c6-80e1-11e6-8255-90bca910ede3.png)

**Comment by tacaswell** [comment]
This is the expected behavior.   `set_yticklabels` is a short cut for `ax2.yaxis.set_major_formatter(FixedFormatter(list_of_string))`.   What you want here is `FuncFormatter` http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.FuncFormatter which must have the signature

```python
def tick_label_func(val, pos=None):
   return '%.2g$\\pm \\beta$' % (val**2 + 0.123)

ax2.yaxis.set_major_formatter(FuncFormatter(tick_label_func))

```

**Comment by FilipDominec** [comment]
Thank you - now I understand that matplotlib implicitly feeds the `FormatStrFormatter` with the original values of ticks, and this can not be changed through `set_yticklabels`. 

Actually this does not matter too much, since in real scientific plotting, one wants rather round numbers on the right axis, too. This makes the right axis ticks non-equidistant. I tried to sketch a solution in  https://gist.github.com/FilipDominec/9101258e8ba979c715a28bc527a43961

Do you think there is a more elegant way in matplotlib? Otherwise I suggest this practical feature could be implemented in matplotlib to enable easy use thereof.

**Comment by Kojoley** [comment]
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from mpl_toolkits.axes_grid1 import host_subplot

fig = plt.figure(figsize=(7,4), dpi=96, facecolor='#eeeeee', tight_layout=1)
ax = host_subplot(111)

x = np.arange(0., 10., 0.1)
ax.plot(x, 12+x**1.5+0.1*x**2.5)

ax.set_xlabel('expected maximum load (kg)')
ax.set_ylabel('needed bar diameter (cm)')

ax2 = ax.twin()
ax2.set_ylabel('bar cross-section (cm$^{2}$)')
ax2.yaxis.set_major_formatter(FuncFormatter(lambda r, _: r**2 + 0.123))
ax2.axis['top'].major_ticklabels.set_visible(False)

ax.legend(prop={'size':10}, loc='upper right')
ax.grid()

plt.show()
```

**Comment by FilipDominec** [comment]
@Kojoley Thanks for your posting. Originally, it appeared to me that you were answering the already solved formatter question, but I noticed unexpected behaviour of matplotlib - consider changing `ax2 = ax.twin()` to `ax2 = ax.twinx()`. 

The right-hand axis becomes completely different and I have no clue what the numbers may come from. It appears as matplotlib forgot about the y-range of `ax` and provided it with default yrange from 0 to 1. But this is probably not the desired user-friendly behaviour, is it?

**Comment by Kojoley** [comment]
`ax.twinx()` makes only x-axis shared, y-axis will still be independent, that is why you need then manually set the limits on y-axis.

**Comment by FilipDominec** [comment]
I see now, thanks for explanation. 

Finally, do you think there is some elegant way to implement https://gist.github.com/FilipDominec/9101258e8ba979c715a28bc527a43961 ? This would be useful in many publication-ready scientific plots.

**Comment by Kojoley** [comment]
> Finally, do you think there is some elegant way to implement

I have posted the code above. It looks quite simple and I do not see any room for simplification.

It produces this:

![issue_7161](https://cloud.githubusercontent.com/assets/2743474/18794053/6b04066e-81c6-11e6-9088-179198439f8a.png)

**Comment by FilipDominec** [comment]
While I appreciate @Kojoley's help with the first part of my question, I am afraid we did not understand each other concerning the other part of getting round numbers on the right axis, which was not entirely trivial.

Today, I have fixed it myself and I suggest such a code should be incorporated into matplotlib, since I believe it to be quite useful for real-life scientific data presentation.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from   mpl_toolkits.axes_grid1 import host_subplot

fig = plt.figure(figsize=(7,4), dpi=96, facecolor='#eeeeee', tight_layout=1)
ax = host_subplot(111)

x = np.arange(0., 10., 0.1)
ax.plot(x, 12+x**1.5+0.1*x**2.5)
ax.set_xlabel('expected maximum load (kg)')
ax.set_ylabel('needed bar diameter (cm)')
ax2 = ax.twin()
ax2.set_ylabel('bar cross-section (cm$^{2}$)')

def right_tick_function(r,q=0): return r**2 # 10.46*(r**1.68)


## If we wish nice round numbers on the secondary axis ticks, we must position the tick on correct positions:
## to do so, we need to numerically invert the tick values.
from scipy.optimize import brentq
def right_tick_function_inv(r, target_value=0): 
    return brentq(lambda r,q: tick_function(r) - target_value, 0, 20000, 1e6)
orig_limits = [tick_function(lim) for lim in ax.get_ylim()]
yticks2 = matplotlib.ticker.MaxNLocator(nbins=8, steps=[1,2,5]).tick_values(min(*orig_limits), max(*orig_limits))
ticks2position = [tick_function_inv(0, ytick2) for ytick2 in yticks2]
ax2.set_yticks(ticks2position)
from matplotlib.ticker import FuncFormatter
ax2.yaxis.set_major_formatter(FuncFormatter(lambda r, _: "%g" % tick_function(r)))


ax.legend(prop={'size':10}, loc='upper right')
ax.grid()
plt.show()
```

**Comment by tacaswell** [comment]
If you do not care if the ticks line up on the left and right, then just do

```python
ax2.set_ylim(transformed(ax.get_ylim()))
```

which will give you 'nice' numbers.

You can keep the two axes y-limits in sync via

```python
def sync_func(other_ax):
    ax2.set_ylim(transform(other_ax.get_ylim())

ax.callbacks.connec('ylim_changed', sync_func)
```

http://matplotlib.org/api/axes_api.html#matplotlib-axes

Seems to be dodge on pan/zoom, but work correctly with `ax.set_ylim`

**Comment by FilipDominec** [comment]
@tacaswell Does it apply also for nonlinear functional dependence between the axes?

**Comment by tacaswell** [comment]
It should.

**Comment by FilipDominec** [comment]
Maybe it is my fault, but through searching and experimenting I could not find any way how bare `set_ylim()` could provide me with ticks of a desired nonlinear functional dependence on the another axis as shown in the last plot above. 

Thus, the code at  with the nonlinear (Brent's) root search for each tick remains the only way for me to prepare publication-ready plots: https://gist.github.com/FilipDominec/9101258e8ba979c715a28bc527a43961

Here is the result: 
![with_round_numbers](https://cloud.githubusercontent.com/assets/511950/18987467/12d1f8e8-8702-11e6-9976-949372926b4e.png)

I believe this thread may be useful for others. Thank you anyway for your help.

**Comment by tacaswell** [comment]
Oh, sorry I was confused.

You need to make a scale.
