### ISSUE TITLE
_axes.py linestyle_map unused

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#7162]
[This thing](https://github.com/matplotlib/matplotlib/blob/f544a83db199ec35f4839f4d9ad2b0ca38965904/lib/matplotlib/axes/_axes.py#L3559-L3564) seem to be unused to me:

```
        linestyle_map = {
            'solid': '-',
            'dashed': '--',
            'dashdot': '-.',
            'dotted': ':'
        }
```

I'm not sure if this is on purpose, from git log it seem like it used to be to allow what is now `final_boxprops` to support the "dotted", "solid" keyword somewhere (not sure where).  
If it's not usefull anymore it might be removed I guess.

**Comment by Kojoley** [comment]
Would you like to open a PR?

**Comment by WeatherGod** [comment]
I have a vague recollection of commenting on this in a PR in the past year.
I just wish I could remember what the response was. I suspect the
explanation is in a comment for a PR to fix up linestyle name handling
(maybe the whole None/'none' mess?).

**Comment by Carreau** [comment]
> Would you like to open a PR?

Removing sure, if removing is the thing to do; but I'm not sure what it was supposed to handle, so if there is something else to fix I'm not sure if I can make a PR before knowing what the expected behavior should be.

**Comment by WeatherGod** [comment]
I wish there was a way to search for all review comments on a given set of
code lines.  Heck... is there any method for searching review comments?

**Comment by Kojoley** [comment]
Was added with 65a686cfd9360cace5ad763a0e140c5bf4ce4e78 and then all related code was removed in #3165

**Comment by tacaswell** [comment]
attn @anntzer

**Comment by tacaswell** [comment]
Err, never mind, wrong set of mappings between strings and line styles.

**Comment by anntzer** [comment]
Yup, never touched this part of the code :)

**Comment by Carreau** [comment]
I'm tempted to say, if it was added on the 2.x cycle it's safe to remove right ?

**Comment by Kojoley** [comment]
It is a local variable, and I have shown above that all related code was removed, so it is definitely safe to remove.

**Comment by Carreau** [comment]
Pr done: #7169
