### ISSUE TITLE
sip/pyqt4 issues during travisCI testing

### ISSUE THREAD

**Issue by andyfaff** [matplotlib/matplotlib#7165]
I have a project that indirectly imports matplotlib during testing on travisCI. When `matplotlib.pyplot` is imported there is a `RuntimeError` because:

> RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtCore module requires API v11.3

Please see the travisCI [log](https://travis-ci.org/refnx/refnx/jobs/162063268) or [here](https://gist.github.com/andyfaff/24893d0201d79e19d8e504766b7b3e35) for more details. Python (2.7, 3.4, 3.5 all have problems) is installed via miniconda, as is matplotlib. This has only just started occurring. If this is not a matplotlib issue please inform me and I'll raise the issue elsewhere.

**Comment by tacaswell** [comment]
This is probably a variation on https://github.com/ContinuumIO/anaconda-issues/issues/1068

**Comment by CJ-Wright** [comment]
Thanks!

**Comment by anntzer** [comment]
I believe this can be closed as fixed, feel free to request a reopen otherwise.
