### ISSUE TITLE
`axes.boxplot` does not have zorder kwarg

### ISSUE THREAD

**Issue by nancysendoh** [matplotlib/matplotlib#7171]
Hi eveybody,

I want to draw boxplot and scatter in one figure, but the boxplot always covers the points as below:
![1](https://cloud.githubusercontent.com/assets/10228916/18806287/c7c29aac-825a-11e6-80b2-fef600f3edf5.jpg)

How could I set the scatter above the boxplot? Thanks ~

Here's my code:

```
import matplotlib.pyplot as plt
import numpy as np

x=[1,2,3]
a=np.array([70,170,130])
y=[]
yy=[]
for i in range(3):
    yy.append(np.random.randn(5))
    y.append(yy[i].mean())

plt.figure()
fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(5, 5))
axes.scatter(x,y,c='r',s=a)
bplot1 = axes.boxplot(yy,
                     vert=True,   # vertical box aligmnent
                     patch_artist=True)   # fill with color
color = 'blue'
for patch in bplot1['boxes']:
    patch.set_facecolor(color)
    patch.set_alpha(0.5)
plt.savefig('1.jpg',dpi=100)
plt.show()
```

**Comment by Phlya** [comment]
Use `zorder` argument in plotting commands, the higher the value, the more on top will be the objects.

**Comment by Kojoley** [comment]
Please do not use the issue tracker to ask questions, use mailing list or gitter for this. https://github.com/matplotlib/matplotlib#contact

**Comment by nancysendoh** [comment]
thanks a lot! it's very helpful. but it seems the boxplot() doesn't have the zorder argument. So I couldn't set the order of two boxplot?
thanks again!



发自我的小米手机
在 Ilya Flyamer <notifications@github.com>，2016年9月24日 下午3:53写道：

Use zorder argument in plotting commands, the higher the value, the more on top will be the objects.

**Comment by tacaswell** [comment]
re-titled and re-opened, boxplot _should_ take `zorder` as a kwrag.

**Comment by efiring** [comment]
@nancysendoh, for your immediate problem, try raising the scatter plot by supplying scatter a "zorder=2.5" kwarg.  That will put its patch collection above the Line2D default zorder of 2 that is used by boxplot.

**Comment by nancysendoh** [comment]
Thanks a lot~![☺]


________________________________
发件人: Eric Firing <notifications@github.com>
发送时间: 2016年9月24日 18:46
收件人: matplotlib/matplotlib
抄送: Cookie; Mention
主题: Re: [matplotlib/matplotlib] `axes.boxplot` does not have zorder kwarg (#7171)


@nancysendoh<https://github.com/nancysendoh>, for your immediate problem, try raising the scatter plot by supplying scatter a "zorder=2.5" kwarg. That will put its patch collection above the Line2D default zorder of 2 that is used by boxplot.

**Comment by afvincent** [comment]
Closing: the `zorder` kwarg was added in #7178 :).
