### ISSUE TITLE
Different behaviour of `tight_layout` call and keyword

### ISSUE THREAD

**Issue by soupault** [matplotlib/matplotlib#7177]
xref https://github.com/scikit-image/scikit-image/pull/2289#issuecomment-245176563, https://github.com/scikit-image/scikit-image/pull/2289#issuecomment-245178778.

Code to reproduce:

```
import numpy as np
from skimage import data
import matplotlib.pyplot as plt


coins = data.coins()

# Adjustable, call
fig, axes = plt.subplots(1, 2, figsize=(8, 3), sharey=True)
axes[0].imshow(coins > 100, cmap=plt.cm.gray, interpolation='nearest')
axes[0].set_title('coins > 100')
axes[1].imshow(coins > 150, cmap=plt.cm.gray, interpolation='nearest')
axes[1].set_title('coins > 150')

for a in axes:
    a.axis('off')
    a.set_adjustable('box-forced')

plt.tight_layout()
plt.savefig('1.png')
plt.close()

# Adjustable, KW
fig, axes = plt.subplots(1, 2, figsize=(8, 3), sharey=True,
                         tight_layout=True)
axes[0].imshow(coins > 100, cmap=plt.cm.gray, interpolation='nearest')
axes[0].set_title('coins > 100')
axes[1].imshow(coins > 150, cmap=plt.cm.gray, interpolation='nearest')
axes[1].set_title('coins > 150')

for a in axes:
    a.axis('off')
    a.set_adjustable('box-forced')

plt.savefig('2.png')
plt.close()

# Call
fig, axes = plt.subplots(1, 2, figsize=(8, 3), sharey=True)
axes[0].imshow(coins > 100, cmap=plt.cm.gray, interpolation='nearest')
axes[0].set_title('coins > 100')
axes[1].imshow(coins > 150, cmap=plt.cm.gray, interpolation='nearest')
axes[1].set_title('coins > 150')

for a in axes:
    a.axis('off')

# Same results with `fig.tight_layout()`
plt.tight_layout()
plt.savefig('3.png')
plt.close()

# KW
fig, axes = plt.subplots(1, 2, figsize=(8, 3), sharey=True,
                         tight_layout=True)
axes[0].imshow(coins > 100, cmap=plt.cm.gray, interpolation='nearest')
axes[0].set_title('coins > 100')
axes[1].imshow(coins > 150, cmap=plt.cm.gray, interpolation='nearest')
axes[1].set_title('coins > 150')

for a in axes:
    a.axis('off')

plt.savefig('4.png')
plt.close()
```

Results (just save them on your PC and compare in any image viewer):

|  |  |
| --- | --- |
| 1.png | 2.png |
| ![1](https://cloud.githubusercontent.com/assets/1315589/18828613/4e369d9a-83e1-11e6-841d-36c4b9df56e3.png) | ![2](https://cloud.githubusercontent.com/assets/1315589/18828614/4fa7f6e2-83e1-11e6-83fd-0a62ea99a428.png) |
| --- | --- |
| 3.png | 4.png |
| ![3](https://cloud.githubusercontent.com/assets/1315589/18828615/515c76f2-83e1-11e6-9aa9-2aeec2f699de.png) | ![4](https://cloud.githubusercontent.com/assets/1315589/18828619/52af22ac-83e1-11e6-840f-0e47cf1b4afa.png) |
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...): mpl 1.5.2, python 3.5.2, Linux, skimage 0.12.3;
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...): via package manager, and pip;
- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
    that demonstrates the issue i.e a small piece of code which reproduces the issue
    and can be run with out any other (or as few as possible) external dependencies.
- [x] If this is an image generation bug attach a screenshot demonstrating the issue.

**Comment by efiring** [comment]
Does the problem occur if you do not use 'box-forced'?  Using 'box-forced' means you can expect some things to not work, and you accept the consequences.  It means you are in danger of over-specifying layout, and ending up with conflicting constraints.

**Comment by soupault** [comment]
@efiring Yes, see cases 3 and 4: no `box-forced`, but the results are still (slightly) different.
