### ISSUE TITLE
group deprecated methods at bottom

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7180]

**Comment by DrNightmare** [comment]
Hi, could someone provide a description? I'd like to look into this.

**Comment by tacaswell** [comment]
For example in http://matplotlib.org/devdocs/api/axes_api.html (which is source from https://github.com/matplotlib/matplotlib/blob/master/doc/api/axes_api.rst) there are a scattering of deprecated methods in the tables.  They should be grouped into a single deprecated table at the bottom.

**Comment by DrNightmare** [comment]
To clarify, for that given example, we would be adding a table, say, "Deprecated", at the bottom. Would adding this at the bottom of the .rst file do it?

```
Deprecated
==========

.. autosummary::
   :toctree: _as_gen
   :nosignatures:

   Axes.get_axis_bgcolor
   Axes.set_axis_bgcolor
   Axes.get_cursor_props
   Axes.set_cursor_props
```

The functions here are the deprecated methods for the given example.
Is there any way to view the output of the .rst file?
Also, the table needs to be above the "Inheritance" section right?

**Comment by tacaswell** [comment]
That is the idea.

Build the docs, http://matplotlib.org/devdocs/devel/documenting_mpl.html#getting-started https://github.com/matplotlib/matplotlib/blob/master/doc-requirements.txt for the extra deps and https://github.com/matplotlib/matplotlib/blob/master/.travis.yml#L172 for how we run the doc build on travis.  

Building the docs can take a while, I have gotten good results with throwing 2x the number of cores I have at the build. You may need to do `git clean -xfd` if sphinx's caches fight back.  The docs should be able to be built with no warnings.

Yes, converting them to the table format is very much a work in progress.

**Comment by DrNightmare** [comment]
I tried building the docs but am facing a problem. I have all the dependencies installed. From the doc folder, when I run `python make.py html -n 2` I get this:

`OSError: [Errno 2] No such file or directory: '../lib/matplotlib/mpl-data/matplotlibrc'`

Indeed 'matplotlibrc' is missing at the specified directory. I searched a bit and I see that it's a config file. Are we supposed to create one in that directory?

**Comment by tacaswell** [comment]
You have to run `python setup.py build` once (or just rename `matplotlibrc.template` to `matplotlibrc`).

**Comment by EJEP** [comment]
Does this still need doing? It looks like functions are tagged as deprecated in the web page (see screenshot of https://matplotlib.org/devdocs/api/axes_api.html) but there is nothing in the `rst` file to indicate this. I can have a look at this if it does need doing.

<img width="511" alt="deprecated_example" src="https://user-images.githubusercontent.com/22224469/65995067-a1a4d780-e48c-11e9-9b1e-d0de401833c6.png">

**Comment by timhoffm** [comment]
Thanks for bringing this up. The deprecation tag is inserted into the docstring via the `@cbook.deprecated` decorator.

Since we now have this deprecation tag, I'd argue that it's better to leave the methods in their semantic context. The tag makes the deprecation clear enough. Therefore I propose to close this PR.

**Comment by jklymak** [comment]
Agreed.
