### ISSUE TITLE
write sphinx extension to generate recursive inheritance

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7182]
Right now, the recursive inheritence diagrams are generated manually, using the following command:

``` python
for n in sorted(list(set(dir(maxis.Axis)) - set(dir(matplotlib.artist.Artist)))): 
    print('Axis.' + n) if n[0] != '_' else None
```

See #7176  for more information.

**Comment by QuLogic** [comment]
I'm confused, because `dir(maxis.Axis)` gives you class methods, not subclasses?

**Comment by tacaswell** [comment]
I am going to close this as I have no memory of what I was thinking and agree it makes no sense.

Maybe what I meant was "get a list of all of the unique methods on the children"?  At any rate, our thinking about docs has moved on in the last 6 years....
