### ISSUE TITLE
Improve documentation on cherry-picking & backports

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7183]
The current documentation on cherry-picking  & backports lacks a "real example", such as the one rebases has, that explains clearly what TARGET_SHA is, how to retrieve it, etc.

**Comment by NelleV** [comment]
This ticket follows up on the discussion around PR #7148.

**Comment by rcomer** [comment]
Is this still needed?  It looks like, at the time, backports were all done manually at the command line.  So it was a lot more important to get it right first time than it is now!

**Comment by tacaswell** [comment]
I think we can close this, we now use meeseeks and when it fails it has detailed steps in the error message.

We also have https://matplotlib.org/devdocs/devel/coding_guide.html#branches-and-backports now
