### ISSUE TITLE
matplotlib 1.5.3 raise TypeError: 'module' object is not subscriptable on pylab.py

### ISSUE THREAD

**Issue by zjjott** [matplotlib/matplotlib#7186]
matplotlib:1.5.3  
python version: 2.7.10 (0e2d9a73f5a1818d0245d75daccdbe21b2d5c3ef, Sep 27 2016, 02:22:00)\n[PyPy 5.4.1 with GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
CentOS 7.1

- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
pip

this code raise:`TypeError: 'module' object is not subscriptable`
```python
from numpy.random import bytes # or *
 __builtins__['bytes']
```
in pypy,and matplotlib use this code in 
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pylab.py#L286
It looks like in python3.4.1,also raise this error
should it modify to:
```
bytes = __builtins__.bytes
```
for better compatibility?

BTW:maybe have something wrong because I found python 2.7.5 also raise `TypeError: 'module' object has no attribute '__getitem__'` in this line but have no one report

**Comment by tacaswell** [comment]
I would also suggest not using `pylab`.  I suspect we will find a lot of these edge cases as people start to use mpl with pypy.

**Comment by zjjott** [comment]
actually,I just have a try like this:
```python
import matplotlib
%matplotlib inline
```
Looks like have many difference between CPython and PyPy such as execution model/ type system, I'll give a try to figure out the truth

**Comment by tacaswell** [comment]
Ah, the problem is that IPython imports pylab

```
09:40 $ git grep 'import pylab'
Python/core/interactiveshell.py:        from IPython.core import pylabtools as pt
IPython/core/magics/pylab.py:            from matplotlib import pylab, mlab, pyplot
IPython/core/pylabtools.py:          "from matplotlib import pylab, mlab, pyplot\n"
IPython/core/shellapp.py:from IPython.core import pylabtools
IPython/core/tests/test_pylabtools.py:from .. import pylabtools as pt
IPython/sphinxext/ipython_directive.py:            # setting its backend since exec_lines might import pylab.
IPython/terminal/ipapp.py:            "    Use `--matplotlib <backend>` and import pylab manually.")

```

**Comment by WeatherGod** [comment]
does it do so unconditionally?

**Comment by zjjott** [comment]
IPython imports pylab when use matplotlib inline mode
I change mpl to svg mode and it works

**Comment by NelleV** [comment]
eh… ipython *still* imports pylab? I thought that was deprecated a long time ago?

**Comment by QuLogic** [comment]
Yes, are you sure it's happening with `%matplotlib inline`? Also, how old is your ipython? From the code, it appears that only the `%pylab` magic should import all the extra stuff, and this should have been true since at least the 3.x line.

**Comment by QuLogic** [comment]
Actually, scratch that. There's a lot of indirection to trawl through, but it appears there _is_ a [`pylab` import here](https://github.com/ipython/ipython/blob/master/IPython/core/pylabtools.py#L304). It does not insert this into the namespace though. I'm not sure it's really necessary; that sort of thing probably should be reported downstream so they can stop using it.

**Comment by tacaswell** [comment]
https://github.com/ipython/ipython/pull/9998 <- IPython PR to fix at least some of this.

**Comment by tacaswell** [comment]
and for 1.5.3 + the `%matplotlib magic isn't needed anymore, importing `pyplot` and calling `plt.ion()` is now sufficient to properly hook up the event loops
