### ISSUE TITLE
graph not showing when I set format to line

### ISSUE THREAD

**Issue by romainecarter** [matplotlib/matplotlib#7189]
pip -> matplotlib version 1.5.3
anaconda -> python 3.5.2

Only shows an empty graph
```python
plt.plot_date(x=[X['Date'][400:500]], y=[X['Last Traded'][400:500]], fmt='r-')
plt.show()
```

Shows graph but with 'o' instead of a line
```python
plt.plot_date(x=[X['Date'][400:500]], y=[X['Last Traded'][400:500]])
plt.show()
```

**Comment by tacaswell** [comment]
Thank you for reporting a bug.  Can you add some example data to your post?  It is much easier to reproduce and debug if with a cop-paste-runnable example.

**Comment by romainecarter** [comment]
Hi @tacaswell I resolved the issue by running matplotlib from python console.
