### ISSUE TITLE
BUG: Animation bugs fixed in master should be backported to 2.x

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7191]
In v2.x the `MovieWriter.saving` context manager fails to pass on the kwargs that should go to the `setup` method.  This makes it impossible to specify the 'frame_prefix' and 'clear_temp' kwargs in `FileMovieWriter` without directly setting attributes inside the context.

**Comment by efiring** [comment]
I will close this upon backporting #6304 to v2.x; I think it should go into the next release.

**Comment by efiring** [comment]
#5453 also needs backporting.  Does anyone know of others like this?

**Comment by dopplershift** [comment]
None that I remember. 👍 on fewer bugs in 2.0

**Comment by efiring** [comment]
#6304 doesn't backport well, so I made a standalone PR, #7207.

**Comment by NelleV** [comment]
Closed in  053bd76
