### ISSUE TITLE
foo and reversed foo_r palettes not equal?

### ISSUE THREAD

**Issue by rathann** [matplotlib/matplotlib#7193]
To help us understand and resolve your issue please check that you have provided
the information below.
- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

2.0.0b4, python 2.7.12, Fedora rawhide
- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)

OS packages
- [x] If this is a regression (Used to work in an earlier version of Matplotlib), please 
    note where it used to work.

This worked in 1.5.2rc2.

seaborn (https://web.stanford.edu/~mwaskom/software/seaborn/index.html) has this test:

```
    def test_mpl_reversal(self):

        pal_forward = palettes.mpl_palette("BuPu", 6)
        pal_reverse = palettes.mpl_palette("BuPu_r", 6)
        nt.assert_equal(pal_forward, pal_reverse[::-1])
```

It fails with:

```
======================================================================
FAIL: seaborn.tests.test_palettes.TestColorPalettes.test_mpl_reversal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/python-seaborn-0.7.1-2.fc26.x86_64/usr/lib/python2.7/site-packages/seaborn/tests/test_palettes.py", line 166, in test_mpl_reversal
    nt.assert_equal(pal_forward, pal_reverse[::-1])
AssertionError: [(0.86168396770472899, 0.91280276816608996, 0.94975778546712808), (0.71146482122260668, 0.80127643214148403, 0.88830449826989621), (0.58998846597462518, 0.67472510572856592, 0.8219915417147251), (0.5490196078431373, 0.49036524413687044, 0.72867358708189156), (0.53788542868127642, 0.30269896193771628, 0.63844675124951944), (0.50943483275663204, 0.084198385236447515, 0.50302191464821222)] != [(0.86168396770472899, 0.91280276816608996, 0.94975778546712808), (0.71146482122260668, 0.80127643214148403, 0.88830449826989621), (0.58998846597462518, 0.67472510572856592, 0.8219915417147251), (0.5490196078431373, 0.49036524413687044, 0.72867358708189156), (0.53788542868127642, 0.30269896193771628, 0.63844675124951944), (0.50943483275663204, 0.084198385236447529, 0.50302191464821222)]
```

The actual difference in this case is in the second-to-last value: `0.084198385236447515 != 0.084198385236447529`

I tried with a few random predefined palettes (BuGn, RdBu, Greys) and the _r variant reversed is never identical to regular variant. Is this expected?

**Comment by tacaswell** [comment]
That is odd, but it looks like float issues on coming out of interpolation.

I suspect the test should be `nt.assert_equal((255*pal_forward).astype(int), (255*pal_reverse[::-1]).astype(int))`

**Comment by rathann** [comment]
Thanks, but unfortunately this fails with:
```
AttributeError: 'list' object has no attribute 'astype'
```

**Comment by tacaswell** [comment]
then make them numpy arrays first, did not expect those to come out as lists...

**Comment by dstansby** [comment]
It looks like this isn't an issue any more, feel free to re-open or comment.
