### ISSUE TITLE
Old whatsnews should be rendered using classic style

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7199]
It's a bit weird to see, say, the 0.99 whatsnew use viridis in its plots:
http://matplotlib.org/devdocs/users/prev_whats_new/whats_new_0.99.html#mplot3d

**Comment by NelleV** [comment]
What exactly did you have in mind? Cause "classic" style did not exist in 0.99 either :)
We could specify that the colormap should be `jet` in the what's new from before 2.0, but that won't make it "classic" style.

**Comment by anntzer** [comment]
Well, I assume these plots are rendered using the master codebase... so it should be possible to modify the examples by adding a call to `style.use`, right?

**Comment by WeatherGod** [comment]
Does the plot directive take a style argument?

**Comment by NelleV** [comment]
We could, but then we have another inconsistency, hence my question :)
You think it is better to use commands that did not exists at that time rather than have the design off?
I don't have  strong opinion, but if I put any of the BIDS machine shop on this, we need to make sure we agree on the fix.

**Comment by anntzer** [comment]
Well, the call to `style.use` could be somewhere outside, e.g. as a (new) argument to the `plot` Sphinx directive, as suggested by @WeatherGod.

**Comment by tacaswell** [comment]
Adding a `style` parameter to the plot directive would be a nice feature.

I am 50/50 about being concerned the old whats new changing.  It isn't what the figure looked like at the time they were created, but it _is_ what it renders as now and I think we should be more giving users representative views rather than preserving (this sort of) historical integrity.

This is an side effect of changing the defaults + rendering figures in the docs that, while obvious in hind sight, is not something that crossed my mind ahead of time!

**Comment by anntzer** [comment]
I'd say the issue is still valid.

**Comment by anntzer** [comment]
Looking at the entries in the old whatsnew they are of the form
```
.. figure:: ../../gallery/userdemo/images/sphx_glr_demo_gridspec01_001.png
   :target: ../../gallery/userdemo/demo_gridspec01.html
   :align: center
   :scale: 50
```

Directly using a `.. figure` to a gallery entry makes it tricky to change the style (because we want the gallery to still use the default style), but we could consider changing that to e.g. (just spitballing here)
```
.. plot:: /galleries/examples/userdemo/demo_gridspec01.py
   :style: classic
   :target: ../../gallery/userdemo/demo_gridspec01.html
   :align: center
   :scale: 50
```
where we add support for a :style: option to plot?

**Comment by jklymak** [comment]
We could definitely add support for :style:   However, it would only really be useful for this case, and detrimental in general - a user of the docs would have no way to know a style change was applied when the figure was created as it wouldn't show up in the source code, which seems a bad feature to add. On the balance, I don't think it's worth the effort to the directive for something that should only rarely be used.

**Comment by anntzer** [comment]
I am fine with closing this too if you think the solutions are not nice.

**Comment by tacaswell** [comment]
I think adding `plt.style.use('classic')` to the old examples would be enough?  It is a bit of a ret-con but it both restores those images to what they looked like when they were added and makes it clear to anyone who reads the code how to get exactly that image.

**Comment by anntzer** [comment]
That would be fine, too.

**Comment by tacaswell** [comment]
I added "good first issue".

The specific work here:

 - look at the whats new entries prior to 2.0 and identify any where the text and the image do not match
 - add `plt.style.use('classic')` to the source

**Comment by haojunsong-08** [comment]
Hi, I'm happy to help. 
I can add the plt.style.use('classic') to 0.99 release .rst file.
But I'm a little bit confused on 

> look at the whats new entries prior to 2.0 and identify any where the text and the image do not match

What What kind of mismatch are you expecting me to find? Similiar to the 0.99 issue where viridis is used at where is shouldn't be?

**Comment by tacaswell** [comment]
Like if the text says "The jet color map shows...." and then the color map in the image is viridis we should force that image back.  The idea would be to surgically add the line to as few of the examples as needed it.

I also see the case for unconditionally adding it to _all_ of the examples but that seems like a bit too much code churn (but I would probably merge a PR that did that).

**Comment by haojunsong-08** [comment]
Thanks for the clear explanation. I will work on it.

**Comment by haojunsong-08** [comment]
I'm still looking for other mismatches.

After I added `plt.style.use('classic')` to the whats_new_0.99.rst file, I didn't see the change was made.
After the addition of the line above,
I cd into the doc folder and followed the instruction using `make html` and then `make show`. Below is the example of the mplot3d. Where did I do wrong? Thanks in advance!
btw, is there a command that can expedite the process of 'make html', I only change one line of the .rst file and it is taking a long time.
**Here is the current readme show on website** 
<img width="1667" alt="Screenshot 2023-04-04 at 15 18 01" src="https://user-images.githubusercontent.com/84302343/229898731-03d368ab-0f39-4f7d-9697-0f5a1f5a24c3.png">
**Here is the readme generated after make show**
<img width="1666" alt="Screenshot 2023-04-04 at 15 17 52" src="https://user-images.githubusercontent.com/84302343/229898904-566ab106-eac0-4ac1-8ff0-60d8758d4c2c.png">
*The code did have the plt.style.use('classic') shown here*
<img width="1673" alt="Screenshot 2023-04-04 at 15 18 20" src="https://user-images.githubusercontent.com/84302343/229899037-a6243266-ca1b-4b9e-9ee7-c3a87a8e29bf.png">

**Comment by jklymak** [comment]
I think you need the style.use at the beginning of the script.

https://matplotlib.org/devdocs/devel/documenting_mpl.html#building-the-docs has instructions for skipping subdirectories.

**Comment by haojunsong-08** [comment]
Thanks! I will give it a try!
