### ISSUE TITLE
Default locator for log-scale messes up minor ticks sometimes

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#7200]
Ubuntu 16.04 | Python 3.5 | MPL 2.0.0b3.post2474+gf8d05a4

Don't have time to look into this more right now. You can see it gets it right sometimes, but sometimes it is very wrong.

![screenshot from 2016-09-29 11-13-57](https://cloud.githubusercontent.com/assets/20605205/18948283/bdb06afa-8636-11e6-8a93-8c6303140949.png)

**Comment by efiring** [comment]
It looks like the problem occurs when the major locator puts ticks at intervals of more than a decade.  What should the minor ticks do in that case?  I don't see an obvious solution, other than putting minor ticks at the decades when the major ticks are skipping decades. In the upper RHS plot in this example, the minor ticks would be at 10^-9 and 10^-7.

**Comment by anntzer** [comment]
Would it be a problem if a minor tick was always drawn at any position a major tick is drawn?  (We just need to make sure that the major tick is drawn over the minor tick, if both are present.)  This would also have avoided (somewhat) issues such as https://github.com/matplotlib/matplotlib/pull/6875#issuecomment-242576526.

**Comment by efiring** [comment]
That would make a mess, or more complexity to avoid the mess, in any case where minor ticks are labeled.

**Comment by anntzer** [comment]
Good point.

**Comment by LindyBalboa** [comment]
Would it be possible to decouple label generation from the ticks? There should totally still be major ticks there, but on some of my plots (ylim of 10^-17 to 10^-4) were just way too crowded and ugly. I was in a rush and just posted the first plot that showed it, so maybe not the best example.

**Comment by tacaswell** [comment]
You might be able to shoe-horn some 'return an empty string' logic into `LogFormatter`

**Comment by NelleV** [comment]
We've done a lot of work on the ticker module to improve the defaults recently, so it is possible this has been fixed. Do you mind sharing the data and the code so that I can verify we haven't fixed this already?

Thanks,
N

**Comment by efiring** [comment]
Not fixed on v2.x:
```python
import numpy as np
import matplotlib.pyplot as plt
x = np.logspace(-10, -5, 100)
plt.loglog(x, x)
plt.ylim(2.85e-14, 9.7e-3)
```

**Comment by afvincent** [comment]
@efiring Is this still a problem with 2.1.x? Running your snippet, I get
![efirings_mwe_7200_with_2 1](https://user-images.githubusercontent.com/17270724/32929324-155693f4-cb0c-11e7-9e3d-f33a6f7d884b.png)
which looks kind of OK to me (i.e. no funny minor ticks between major y-ticks spanning over more than 1 decade). Or am I missing something? 

However kind of agree with the suggestion that adding an extra unlabelled tick at each decade between the labelled tick might be a good idea.

**Comment by efiring** [comment]
I think we can consider the behavior sufficiently improved by #8381 that the original issue is no longer present.  Therefore I will close this.

**Comment by LindyBalboa** [comment]
Thanks for the continuing work guys!
