### ISSUE TITLE
Converting docstrings to numpydoc

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7205]
Some of the quite well used methodes of the Axes object haven't been ported to numpy doc yet.
This ticket aims at listing those, and slowly moving those functions to numpy doc.
- [x] set_xticklabels, set_yticklabels (missing documentation of some args)
- [x] Figure.add_subplot, Figure.add_axes
- [x] twinx, twiny
- [x] set_xlim, set_ylim
- [x] set_xlim, set_ylim
- [x] set_xscale, set_yscale

Contributors, feel free to update this list as need be!

Here is some documentation: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by QuLogic** [comment]
#7535 points out that finishing this and putting in return types will help with autocompletion in Jedi.

**Comment by melvyniandrag** [comment]
Just passing by looking for some stuff to do this evening. In the initial post of this thread there are two unchecked boxes, but I just looked at the docstrings for those functions and the format looks consistent with the format of the docstrings for the functions corresponding to the checked boxes. Should this be closed?

**Comment by anntzer** [comment]
I think the remaining work is in #9262.

**Comment by melvyniandrag** [comment]
Thanks for the reply. Looks like you finished it!

**Comment by dopplershift** [comment]
With #9262 merged, should we close this?

**Comment by tacaswell** [comment]
These methods all appear to have numpydoc docstrings now.

Discovered this while looking at issues with @eaishwa
