### ISSUE TITLE
variable frame size support in animation is a misfeature

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7210]
The essence of an animation is that it is a sequence of matching frames with gradually shifting contents.  It makes sense only when the frames match--that is, they are the same size.  Therefore the complexity added by the `frame_size_can_vary` attribute is not buying anything, and should be removed.  Specifically, what it allows is writing a sequence of png files, for example, which cannot subsequently be assembled into a video.  Even if viewed sequentially with a png-viewer, such a sequence will not be satisfying because the screen position of features that should be stationary will jump around with the changing frame size.

It was put in to support `bbox_inches='tight'`.  I suggest that this kwarg setting should instead raise a `ValueError`.  By requiring that the frame size be fixed from the beginning, it becomes easier to handle problems such as the need for even-number pixel dimensions with h264.

**Comment by tacaswell** [comment]
Did not even know this _was_ a feature.

**Comment by dopplershift** [comment]
Removed in #7208.
