### ISSUE TITLE
Including audio in FuncAnimation?

### ISSUE THREAD

**Issue by carlthome** [matplotlib/matplotlib#7212]
Aside from reencoding a FuncAnimation's mp4 output with audio afterwards with lets say ffmpeg, is there a builtin way to include audio? For visualizing music information retrieval (MIR) tasks it would be very useful to be able to also listen to the spectrograms with audio/video in sync.

I'm envisioning something like:

``` python
audio_samples = np.ndarray(...)
anim = animation.FuncAnimation(plt.figure(), 
                               animate, 
                               frames=100, 
                               interval=100, 
                               blit=True,
                               audio=audio_samples)
```

or that `animate` would optionally return a tuple with a corresponding audio buffer per rendered frame for oscilloscopes and such, and that the user would be expected to handle `interval` properly according to the audio buffer size.

If this doesn't exist already, would matplotlib be interested in a pr?

**Comment by tacaswell** [comment]
There is not currently an obvious built in way, but it might be interesting to add.

Any implementation of this would have to be compatible with writers that do not support audio (ex export to gif).

It might make more sense to inject the audio via the save rather than attached to the animation object?

You can currently pass arbitrary arguments down to ffmpeg, that may be a faster route to including the audio in the first pass.

**Comment by tacaswell** [comment]
attn @WeatherGod @dopplershift 

I labeled this as hard because I do not understand ffmpeg, it is possible that there is a simple way to do this and I am just ignorant.

**Comment by dopplershift** [comment]
I have no idea how you'd tackle this with the pipe-based writing, but I can see a path if you used Python's `wavfile` module to write the audio to disk and then pass the right incantation to ffmpeg. Not sure if our current approach to argument handling will allow passing to ffmpeg in the right order, though.

**Comment by sotelo** [comment]
I'm also interested in this functionality. Has anyone made some progress on this? I would love to help as well.

**Comment by carlthome** [comment]
Aside from not requiring matplotlib users to know about ffmpeg, there's the benefit of making a really useful visualization tool for audio analysis. I'm mostly working on machine learning and would love a quick way of displaying predictions and stuff within a Jupyter Notebook without involving subprocess.call which would confuse my readers (they are not CS majors).

Yes, it's reasonable to assume audio contained in a ndarray would be in sync already and that the user sets interval to `hop_length / sample_rate * 1000`.

**Comment by Kojoley** [comment]
> there's the benefit of making a really useful visualization tool for audio analysis

I thought that we are talking about saving plot, not about interactive plot + audio playback. Can't you just push audio buffer for playing in `animate` func with something like [`sounddevice`](https://python-sounddevice.readthedocs.io/en/0.3.5/#callback-streams)?

**Comment by tacaswell** [comment]
Closing this as out of scope for matplotlib.

Would happily merge an example of doing this or hosting a `mpl-loud-animation` repository in the matplotlib github org.
