### ISSUE TITLE
document and test Arrow and FancyArrow

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#7213]
See #6583.

The code is pretty crufty, there are no tests, and it's not clear at all what the units are for drawing these things.

**Comment by dstansby** [comment]
Yes please. I was just about to open a bunch of issues for `ax.arrow()`...

**Comment by dstansby** [comment]
Having another look into the whole arrow business(/mess), and it looks like `Arrow` and `FancyArrow` are arrows where all the vertices are rigidly fixed in data space, which I think is something useful to have.

**Comment by efiring** [comment]
Why is that useful?  It makes them behave badly when anything changes the aspect ratio.

**Comment by dstansby** [comment]
In response to the the original report, I'm happy to add tests, and I think it's now clear what the units are for drawing the arrows (#8770). They might not be the best way to draw an arrow in 99% of use cases, but as long as they're well documented (which I'm happy to do) I don't really see a need to get rid of them.
