### ISSUE TITLE
The documentation on "how to write documentation" need to be updated

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7217]
The documentation on how to write documentation is out of date:

http://matplotlib.org/devdocs/devel/documenting_mpl.html#documenting-matplotlib

Specifically, it should refer to our [MEP10](http://matplotlib.org/devdocs/devel/MEP/MEP10.html)

**Comment by NelleV** [comment]
Bumping this to 2.1

**Comment by timhoffm** [comment]
This is on it's way. The issue is basically duplicate with #9876. Maybe one should mere/collect the stuff in one issue.

Related pull requests:
#9884
#9875 
#9872
#9805
#9786
#9513

**Comment by dstansby** [comment]
All those PRs are closed, and we've had a big overhaul of the dev documentation, so shall we close this?

**Comment by remram44** [comment]
#9876 was closed but not this

**Comment by NelleV** [comment]
Thanks @remram44
