### ISSUE TITLE
Cycler passed as string for rc

### ISSUE THREAD

**Issue by JanisErdmanis** [matplotlib/matplotlib#7219]
Hello, I think I have found a bug with cycler when It is passed as a string for rc parameters. Here is example code I have

```
import pylab as plt

### WORKS
plt.rc("axes",prop_cycle=plt.cycler('linestyle', ['-', (0,(5,5))]) )
plt.plot([1,2])
plt.plot([1,4])
plt.show()

### ERROR

plt.rc("axes",prop_cycle="cycler('linestyle', ['-', (0,(5,5))])" )
plt.plot([1,2])
plt.plot([1,4])
plt.show()
```

When I run this code the first part works but the second part produces a long error - [error.txt](https://github.com/matplotlib/matplotlib/files/509552/error.txt). I am using Ubuntu 16.04 and upgraded matplotlib to 1.5.3 with pip today.

**Comment by akels** [comment]
code did not look right.

**Comment by tacaswell** [comment]
I hope you encountered this by reading in a style file / putting this in `matplotlibrc`.

It looks like the validation/parsing on this is not good enough.  This particular case is a bit tricky as the linestyle _can_ be a list of strings so treating this as a list of strings seems reasonable.

**Comment by WeatherGod** [comment]
I wonder if the same problem would happen if the order of the linestyles
were reversed? Also, is this happening on master as well?

**Comment by anntzer** [comment]
I'm going to take advantage of this issue to readvertise my suggestion of using a python source file for matplotlibrc (https://github.com/matplotlib/matplotlib/issues/7089#issuecomment-246261750)...

**Comment by WeatherGod** [comment]
This doesn't have anything to do with rc files. This is passing arguments
to `plt.rc()`.

**Comment by WeatherGod** [comment]
as a matter of fact, this is actually an argument *against* using python
source files for matplotlibrc's because we still need to support taking
string inputs into functions like `plt.rc()`, so we would need to keep our
parsing logic anyway, so there is very little gain.

**Comment by anntzer** [comment]
I thought that the whole reason for allowing string inputs in `plt.rc` was that the parsers are already there for handling matplotlibrc; if matplotlibrc is a python file then likewise `plt.rc` should likewise discard support for string inputs.  Or, if we really want to keep support for this, we should just eval such inputs.

**Comment by anntzer** [comment]
This has actually been fixed as of master.
