### ISSUE TITLE
subplots docstring: no example of NxN grid

### ISSUE THREAD

**Issue by stefanv** [matplotlib/matplotlib#7230]
It would be useful to see something like this:

```
f, ax = plt.subplots(2, 2)

ax[0, 0].plot([1, 2, 3])
ax[1, 1].plot([1, 2, 3])
```

So that users do not immediately jump to gridspec.

**Comment by NelleV** [comment]
Just to make sure I understand your comment, you are suggesting adding an example to the docstring?

**Comment by stefanv** [comment]
Yes, @michaelpacer mentioned that he used gridspec because he never saw any mention in the doc that `subplots` could be used this way.  Indeed, the only example given is of a side-by-side plot (there is an example of a bigger grid, but it is never indexed into).

**Comment by NelleV** [comment]
Ok. I'm working on the docstring, and I'll ping you guys on the PR for a review.
