### ISSUE TITLE
Improving documentation: Tests failing on a osx setup

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7234]
We've ran into some problems getting the matplotlib environment working fine on linux, and I am not sure this is documented anywhere.

We had a massive number of tests failing, as the tests where not running on the correct freetype issue. The fix was easy:
1. edit the setup.cfg file and set the test to True, and local_freetype to true.
2. Delete the old build - matplotlib caches the results and _will not rebuild with the new options despite they changed_.
3. Rebuild.

Our documentation need to be updated to reflect this issue.

Original issue.

On system python2.7.8, on latest master version,  with both the macosx and agg backend, @trpham is having _a lot_ of tests failing on images comparisons:

``` shell
======================================================================
FAIL: mpl_toolkits.tests.test_axes_grid1.test_inset_locator(0, u'inset_locator', u'png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/TruongPham/BIDS/matplotlib/lib/matplotlib/testing/nose/decorators.py", line 60, in failer
    result = f(*args, **kwargs)
  File "/Users/TruongPham/BIDS/matplotlib/lib/matplotlib/testing/decorators.py", line 297, in compare
    raise_on_image_difference(expected_fname, actual_fname, self.tol)
  File "/Users/TruongPham/BIDS/matplotlib/lib/matplotlib/testing/decorators.py", line 216, in raise_on_image_difference
    '(RMS %(rms).3f)' % err)
ImageComparisonFailure: images not close: /Users/TruongPham/BIDS/matplotlib/result_images/test_axes_grid1/inset_locator.png vs. /Users/TruongPham/BIDS/matplotlib/result_images/test_axes_grid1/inset_locator-expected.png (RMS 0.001)
```

Around 900 tests are failing, but the RMS is always extremely small. Anyone guesses what is going on?

Apart from this, matplotlib seems to be running fine. Any help would be appreciated.

**Comment by NelleV** [comment]
It  might be a freetype issue.

**Comment by NelleV** [comment]
It was a freetype issue.
I'll document this properly.

**Comment by tacaswell** [comment]
There is also an enviromental variable.

Some of this is documented at http://matplotlib.org/devdocs/devel/testing.html#building-matplotlib-for-image-comparison-tests (but does not seem to be in the currently built docs).

**Comment by NelleV** [comment]
I am working on improving the contributors documentation right now to be able to point to one page for new contributors. I've highly inspired myself from the scikit-learn documentation, and a work in progress can be found here:
http://cbio.mines-paristech.fr/~nvaroquaux/tmp/matplotlib/devel/contributing.html
