### ISSUE TITLE
mlab.psd behaviour has changed in 1.5.x, psd depends on window size NFFT?

### ISSUE THREAD

**Issue by callegar** [matplotlib/matplotlib#7237]
Issue seen in matplotlib 1.5.3, Linux, installed with pip.

Retesting software that was originally written in matplotlib 1.4 times, I am noticing a huge discrepancy in psd plots.

It looks like recent matplotlib mlab.psd fails to properly normalize the psd wrt the window size NFFT (at least when  scale_by_freq is set to False).

As a result psd plots (in dB) are shifted up and down when the NFFT parameter is changed.

It is unclear to me if this is an intended result. In any case, it does not seem to be documented.

**Comment by efiring** [comment]
This is intended--it is the way the "power spectrum" works, as opposed to the "power density spectrum".  The former is what you get with `scale_by_freq=False`, the latter with `True`.  It is illustrated in the second plot here: http://currents.soest.hawaii.edu/ocn_data_analysis/_static/Spectrum.html.  As NFFT changes, the power spectrum preserves the height of a spectral peak from a single sinusoid, but not the level of a broad-bandwidth background.  The reverse is true of the power spectral density.

See #4328 and #4593.

**Comment by callegar** [comment]
I was expecting that. My point was actually the change in behavior wrt previous matplotlib versions that I did not find in the changelog. Possibly I missed that.

**Comment by efiring** [comment]
No, I think we missed it.  It looks like it should be in http://matplotlib.org/api/api_changes.html, but isn't.

**Comment by jklymak** [comment]
This is really old history - closing...
