### ISSUE TITLE
Codecov instead of coveralls?

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#7244]
This was briefly discussed on gitter, but I'm not sure how much exposure that discussion had. I'm posting it here just in case others might want to weigh in.

@njsmith:

> I just switched from coveralls to codecov and am pretty happy
> fyi
> (some advantages: pretty plots, combining coverage from different python versions / languages actually seems to work which I could never manage with coveralls)

@jenshnielsen:

> @njsmith I spent a long time fighting with both codecov and coveralls. In the end we could only get coveralls to work correctly with our nose setup. Once we deprecate nose and replace it with PyTest we will likely switch to codecov

@njsmith:

> Ah, interesting. It's true, I'm using pytest on the relevant packages

**Comment by tacaswell** [comment]
I think this is blocked on dropping nose fully on master branch.
