### ISSUE TITLE
Inconsistent behaviour of  `subplots` for one and more-than-one axes 

### ISSUE THREAD

**Issue by DSLituiev** [matplotlib/matplotlib#7246]
The `pyplot.subplots` returns inconsistent type of output dependent on the number of subplots requested. While this might be "convenient" sometimes, it is anti-intuitive and requires additional handling from the user side.

Suggestion: Return consistently `numpy.ndarray` of axes for any number of requested axes.

```
fig, axs = plt.subplots(2)
type(axs)
# numpy.ndarray

fig, axs = plt.subplots(1)
type(axs)
matplotlib.axes._subplots.AxesSubplot
```

 [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
'1.5.3'; Python 3.5, OSX

**Comment by tacaswell** [comment]
This is controlled by by the `squeeze` kwarg http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplots  which controls if excess dimensions are squeezed out.
