### ISSUE TITLE
How can plot a figure with matplotlib like this?

### ISSUE THREAD

**Issue by wenmin-wu** [matplotlib/matplotlib#7257]
Note the ticks in y axis have different scales
![image](https://cloud.githubusercontent.com/assets/9409333/19305119/19a240c0-90a2-11e6-8e10-66fe5a21c52b.png)

**Comment by tacaswell** [comment]
Please send this question to the mailing list https://mail.python.org/mailman/listinfo/matplotlib-users

**Comment by tacaswell** [comment]
We try to keep the issues for bugs and new-feature development and use the mailing list for support.  You will get a much wider audience on the mailing list.

**Comment by wenmin-wu** [comment]
@tacaswell  OK, thanks!
