### ISSUE TITLE
autoscaling of yaxis fails

### ISSUE THREAD

**Issue by kampe004** [matplotlib/matplotlib#7259]
I have a model dataset that has a maximum value of (approx.) 10,000 or 1e4. 
When I plot this with MPL some of the timeseries come out with a wrong axis. As you can see in the attached figure, the maximum appears to be 2.0e4. 
One timeseries exhibits the value 7.0e3 (shown in Figure, not example).  

Minimal example attached (needs text files).

MPL version 1.5.3, Python 3.5.2, both installed from anaconda
Mac OSX 10.11.6

[y0.txt](https://github.com/matplotlib/matplotlib/files/524654/y0.txt)
[y1.txt](https://github.com/matplotlib/matplotlib/files/524653/y1.txt)
[y2.txt](https://github.com/matplotlib/matplotlib/files/524658/y2.txt)
[y3.txt](https://github.com/matplotlib/matplotlib/files/524656/y3.txt)
[y4.txt](https://github.com/matplotlib/matplotlib/files/524657/y4.txt)
[y5.txt](https://github.com/matplotlib/matplotlib/files/524655/y5.txt)
[y6.txt](https://github.com/matplotlib/matplotlib/files/524659/y6.txt)
[y7.txt](https://github.com/matplotlib/matplotlib/files/524660/y7.txt)
[y8.txt](https://github.com/matplotlib/matplotlib/files/524661/y8.txt)
[y9.txt](https://github.com/matplotlib/matplotlib/files/524662/y9.txt)

[example.py.txt](https://github.com/matplotlib/matplotlib/files/524665/example.py.txt)

![screen shot 2016-10-12 at 15 20 59](https://cloud.githubusercontent.com/assets/7933853/19312174/a0fd7186-9091-11e6-8a96-630abfa78ebf.png)

**Comment by afvincent** [comment]
It looks like the offset label is an additive one in the case of your screenshot (and should thus be read like 'tick_value = tick_label + 999x'), or am I wrong?

**Comment by kampe004** [comment]
Whoops, I didn't know additive offsets existed, I interpreted this as a multiplicative one. Inserting

y_formatter = matplotlib.ticker.ScalarFormatter(useOffset=False)
ax.yaxis.set_major_formatter(y_formatter)

found [here](http://stackoverflow.com/questions/3677368/matplotlib-format-axis-offset-values-to-whole-numbers-or-specific-number#6654046)
fixed the issue ! Please close

**Comment by kampe004** [comment]
Thanks afvincent

**Comment by afvincent** [comment]
You're welcome. 

If you want to know more about tick locators and formatters, here is some doc:
[http://matplotlib.org/api/ticker_api.html](http://matplotlib.org/api/ticker_api.html).

Some nice examples are available in the development gallery (and should be shipped with matplotlib v2):
[http://matplotlib.org/devdocs/examples/ticks_and_spines/tick-locators.html](http://matplotlib.org/devdocs/examples/ticks_and_spines/tick-locators.html)
[http://matplotlib.org/devdocs/examples/ticks_and_spines/tick-formatters.html](http://matplotlib.org/devdocs/examples/ticks_and_spines/tick-formatters.html)
