### ISSUE TITLE
Legend not displayed in Plot-Matplot lib

### ISSUE THREAD

**Issue by priyambial123** [matplotlib/matplotlib#7261]
Hi,
     I am using Enthought Canopy (Version 1.7.4.3348 (64 bit)) and I have downloaded Matplotlib version 1.5-1.5 in Python2.7 (Redhat Linux). I installed Matplotlib package in Canopy using package manager in Canopy. I installed Python2.7 using gzipped  file from Python website (https://www.python.org/downloads/). When I run some of the python files for generating a plot, the legend was not displayed in the plot. I got the below warning message:
```
/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/legend.py:633: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x7fb6dc346350>] instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
```

![figure_1](https://cloud.githubusercontent.com/assets/11889537/19314074/66f4e472-90b6-11e6-873c-ac05ecc51b33.png)

This was the code used for generating plot:
```python
p1 = pylab.plot(model.data["B"], 'ob-')
p2 = pylab.plot(model.data["C"], 'sr-')
pylab.legend([p1,p2], ["B","C"])
pylab.ylim((-0.1,1.1))
pylab.show()
```

Pls find the attached figure, in which the legend is not displayed. Kindly help me with this issue.
Thank you
Priya

**Comment by afvincent** [comment]
What are exactly your data structure `model.data[key]`?

I wonder if 
```python
p1, = pylab.plot( model.data["B"] , 'ob-' )
p2, = pylab.plot( model.data["C"] , 'sr-' )
pylab.legend( [p1,p2], ["B","C"])
pylab.ylim((-0.1,1.1))
pylab.show()
```
would work. The changes are the 2 commas added in the 2 first lines : `plot` returns a **list** of lines. However, I am not totally sure it will work in this case : the warning seems to complains about the emptiness of `p1` or `p2`.

If it still does not work, you may consider passing directly the labels during the `plot` calls:
```python
pylab.plot( model.data["B"] , 'ob-', label="B")
pylab.plot( model.data["C"] , 'sr-', label="C" )
pylab.legend()
pylab.ylim((-0.1,1.1))
pylab.show()
```

**Comment by Kojoley** [comment]
The right way to do it will be:
```python
p1, = pylab.plot(model.data["B"], 'ob-')
p2, = pylab.plot(model.data["C"], 'sr-')
pylab.legend([p1,p2], ["B","C"])
pylab.ylim((-0.1,1.1))
pylab.show()
```
_the difference is in tuple unpacking of `plot` calls_
_and you can notice this in the documentation http://matplotlib.org/users/legend_guide.html_

or:
```python
p1 = pylab.plot(model.data["B"], 'ob-')
p2 = pylab.plot(model.data["C"], 'sr-')
pylab.legend(p1 + p2, ["B","C"])
pylab.ylim((-0.1,1.1))
pylab.show()
```

because `plot` returns the _list_: [`Return value is a list of lines that were added.`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot)
