### ISSUE TITLE
axes.bxp fails without fliers

### ISSUE THREAD

**Issue by jacobmj** [matplotlib/matplotlib#7263]
I was trying to use the recent axes `bxp()` functionality with a list of statistics dictionaries.  My dictionaries include only `['whislo', 'q1', 'med', 'q3', 'whishi']`.

The documentation mentions that `fliers` is an optional key so long as `showfliers=False`.  However the bxp function always accesses the `fliers` key, and accordingly throws a `KeyError`.  The relevant access is as follows:

[lib/matplotlib/axes/_axes.py#L3722-L3727](https://github.com/matplotlib/matplotlib/blob/45dbc9bc7a1521c4889472ff60466dee8bd14a35/lib/matplotlib/axes/_axes.py#L3722-L3727)
```python
        for pos, width, stats in zip(positions, widths, bxpstats):
            # try to find a new label
            datalabels.append(stats.get('label', pos))
            # fliers coords
            flier_x = np.ones(len(stats['fliers'])) * pos
            flier_y = stats['fliers']
```

**Comment by Kojoley** [comment]
A repro-code (shortened version of http://matplotlib.org/examples/statistics/bxp_demo.html):
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook

# fake data
np.random.seed(937)
data = np.random.lognormal(size=(37, 4), mean=1.5, sigma=1.75)
labels = list('ABCD')

# compute the boxplot stats
stats = cbook.boxplot_stats(data, labels=labels, bootstrap=10000)
# After we've computed the stats, we can go through and change anything.
# Just to prove it, I'll set the median of each set to the median of all
# the data, and double the means
for n in range(len(stats)):
    stats[n]['med'] = np.median(data)
    stats[n]['mean'] *= 2

fig, ax = plt.subplots()

del stats['fliers']
ax.bxp(stats, showfliers=False)

plt.show()
```

**Comment by tacaswell** [comment]
The two lines in the OP need to be moved down into the if block at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L3800
