### ISSUE TITLE
documentation: texinfo markup error in matplotlib 1.4.3 and matplotlib 1.5.3

### ISSUE THREAD

**Issue by daym** [matplotlib/matplotlib#7269]
Hi,

there's a texinfo markup error in matplotlib 1.4.3 and matplotlib 1.5.3:

File doc/users/intro.rst has

Introduction
============

matplotlib is a library for making 2D plots of arrays in `Python
<http://www.python.org>`_.  Although it has its origins in emulating
the MATLAB |reg| [*]_ graphics commands, it is
independent of MATLAB, and can be used in a Pythonic, object oriented
way.  Although matplotlib is written primarily in pure Python, it
makes heavy use of `NumPy <http://www.numpy.org>`_ and other extension
code to provide good performance even for large arrays.

And .. [*] MATLAB is a registered trademark of The MathWorks, Inc.

I guess

   MATLAB |reg| [#]_ graphics commands

and

 [#] MATLAB is a registered trademark of The MathWorks, Inc.

was meant instead (for auto-numbered footnotes). 

See also https://github.com/sphinx-doc/sphinx/issues/3044 for further details.

**Comment by QuLogic** [comment]
Thanks! This was already fixed by #7135.
