### ISSUE TITLE
Pylab import

### ISSUE THREAD

**Issue by priyambial123** [matplotlib/matplotlib#7270]
Hi,
I have installed Python 2.7 and Matplotlib version 1.5-1.5 in Redhat Linux7. I am trying to run a python file in Enthought Canopy  1.7.4.3348. I get this following error 'from pylab import *' used; unable to detect undefined names. I have also attached the python script. Pls find it. Kindly help me to solve this issue
[test.txt](https://github.com/matplotlib/matplotlib/files/529556/test.txt)

Thank you
Regards
Priya

**Comment by tacaswell** [comment]
That looks like a linting warning, not an error (I expect the code to run correctly).

To avoid this warning, do not use the bulk import (`from foo import *`) but selectively import the functions / classes you need or just bring the module into your local namespace.  The current suggested pattern is to do

```python
import matplotlib.pyplot as plt
import numpy as np
```

and then use `np.foo` or `plt.foo` in your code.

In the future, question like this a better sent to the mpl-user mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users you will have to sign up to post un-moderated).
