### ISSUE TITLE
DOC: Misrendered URLs in the development_worflow section of devdocs.

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#7283]
In the "Rebasing a Pull Request (PR)" section of [http://matplotlib.org/devdocs/devel/gitwash/development_workflow.html](http://matplotlib.org/devdocs/devel/gitwash/development_workflow.html), some URLs seem to be not rendered correctly. Search for example "this nice write up" or "documented how to do this" (both are in the 2nd paragraph). They are just displayed as plain text, in a monospace font:
![misrendered_url_example](https://cloud.githubusercontent.com/assets/17270724/19419060/d24c4276-93cf-11e6-9e8d-6f6b39a420ea.png)

Attn @tacaswell and @NelleV as you are the last ones who have edited this part.

**Comment by QuLogic** [comment]
It looks like the trailing underscores are missing.

**Comment by afvincent** [comment]
Fixed by #7286.
