### ISSUE TITLE
Raise an error or a warning when ylim's min == 0 and yscale == "log"

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7299]
``` python
import matplotlib.pyplot as plt
import numpy as np

y = np.arange(3000, 112471, 10000)

fig, ax = plt.subplots()
ax.set_yscale("log")
ax.plot(y, linewidth=0, marker=".")
ax.set_ylim((0, 1e5))
```

yields:

![figure_2](https://cloud.githubusercontent.com/assets/184798/19459546/a29cffb6-9488-11e6-9acb-c9b22d26219a.png)

Basically, the ymin gets ignored (sometimes) when ymin == 0 and yscale == 0.

The code should raise an error or at least a warning.

version: 2.0.0b4.post2455+g063cd41

**Comment by dstansby** [comment]
Looks like this is fixed now.

**Comment by efiring** [comment]
Right, it is fixed in master.
