### ISSUE TITLE
weird mathtext doc markup

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7300]
At http://matplotlib.org/devdocs/users/mathtext.html#fonts:
![screenshot_20161017_204820](https://cloud.githubusercontent.com/assets/1322974/19463726/4feaabf6-94ab-11e6-93ca-de5bbb640d57.png)

The alignment of the last row is probably trivial to fix but this seems done on purpose in the source:

```
    ====================================== =========================================
    Command                                Result
    ====================================== =========================================
    ``\mathbb{blackboard}``                :math-stix:`\mathbb{blackboard}`
    ``\mathrm{\mathbb{blackboard}}``       :math-stix:`\mathrm{\mathbb{blackboard}}`
    ``\mathfrak{Fraktur}``                 :math-stix:`\mathfrak{Fraktur}`
    ``\mathsf{sansserif}``                 :math-stix:`\mathsf{sansserif}`
    ``\mathrm{\mathsf{sansserif}}``        :math-stix:`\mathrm{\mathsf{sansserif}}`
    ====================================== =========================================

.. htmlonly::

    ====================================== =========================================
    ``\mathcircled{circled}``              :math-stix:`\mathcircled{circled}`
    ====================================== =========================================
```

Or am I overthinking it?

**Comment by tacaswell** [comment]
@mdboom did that in 2008 when this table was added in e3a1bfb85fc85e4c300707ec1c45af5c9d72da34

:+1:  to removing the directive and see what breaks?

**Comment by NelleV** [comment]
:+1:

**Comment by anntzer** [comment]
@NelleV I allowed myself to assign this to the machine shop; please let me know if you'd rather me not do such assignments.

**Comment by NelleV** [comment]
Please, do such assignments!
I try to have only a limited of ticket in the project queue, but tagging them is perfect: that's less work for me.

**Comment by akarilimano** [comment]
Hi, I wanted to help and created this pull-request. I am new to contributing so I'm not sure whether I should have done this or not.
