### ISSUE TITLE
get_facecolors() reports incorrect colors

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#7312]
MWE:

```python
import matplotlib
from matplotlib import pyplot as plt
import numpy as np

fig = plt.figure()

N = 20
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area = np.pi * (15 * np.random.rand(N))**2
plt.scatter(x, y, s=area, c=colors, alpha=0.5)

children = fig.get_children()
for child in children:
    if isinstance(child, matplotlib.axes.Subplot):
        cc = child.get_children()
        print(cc[0].get_facecolors())

plt.show()
```

Output:
```
[[ 0.   0.   1.   0.5]]
```

**Comment by WeatherGod** [comment]
This is a similar problem to one that has been found in mplot3d. The issue
is that for ScalarMappables like scatter plots, the colors aren't set until
plotting, so they start off with the default polygon/patch color.

**Comment by nschloe** [comment]
Mhm. Any other ways of retrieving the colors from the figure then?

**Comment by tacaswell** [comment]
Why are you trying to do this?

To expand on what @WeatherGod said, the reason that the colors are not set until late is to avoid extra computation as you can change the underlying data, norm and colormap of the `ScalarMappable`.

**Comment by nschloe** [comment]
> Why are you trying to do this?

This is for matplotlib2tikz, in particular https://github.com/nschloe/matplotlib2tikz/issues/120.

Perhaps there's an mpl function then that returns the color data from the figure?

**Comment by anntzer** [comment]
Actually this issue is solved as of 2.0b4 (I did check that I could reproduce it with 1.5.3).

**Comment by nschloe** [comment]
@anntzer Tried this with 2.0b4 and got
```
[[ 0.12156863  0.46666667  0.70588235  0.5       ]]
```
This is still one entry for 20 circles. Do you get the same? If yes, I guess a reopen is in order.

**Comment by anntzer** [comment]
Oh, I see.  I saw that the color was not 0, 0, 1, .5 anymore and thought that was enough, sorry about the premature closing.

**Comment by anntzer** [comment]
You can (should?) call `fig.canvas.draw()` first.  Then the facecolors become correctly set.

**Comment by nschloe** [comment]
Indeed, when inserting `fig.canvas.draw()` I get
```python
[[ 0.9553    0.901065  0.118128  0.5     ]
 [ 0.120092  0.600104  0.54253   0.5     ]
 # ...
 [ 0.945636  0.899815  0.112838  0.5     ]]
```
which are the actual sizes after colormap matching. Better would be to get the values of the `c` argument of the `scatter` call, much like `get_sizes()` returns the `s` argument. Any way to do that?

**Comment by anntzer** [comment]
Ah.  For that, you have `cc[0].get_array()`.

**Comment by nschloe** [comment]
Just what I was looking for. Thanks!
