### ISSUE TITLE
plot range

### ISSUE THREAD

**Issue by farz92** [matplotlib/matplotlib#7332]
Is it possible to change plot range and number format representation on vertical axis when we plot 2-D figure?

- [ ] Matplotlib version 1-4-2, Python version 3.4 and Platform linux, Ubuntu
- [ ] How did you install Matplotlib and Python--- from source
![screenshot from 2016-10-22 08 15 12](https://cloud.githubusercontent.com/assets/22745179/19621038/47e15a1a-9896-11e6-8130-246a5af049d6.png)

**Comment by thisch** [comment]
This kind of question is better suited for stackoverflow. Please ask there.

**Comment by tacaswell** [comment]
The mailing list (matplotlib-users@python.org) would also be a good place to ask this question.
