### ISSUE TITLE
Error in error handling of ghostscript conversion

### ISSUE THREAD

**Issue by JannickWeisshaupt** [matplotlib/matplotlib#7339]
This bug occures in version 1.5.0 of matplotlib with python 3.4.
In line 1563 and following of matplotlib/lib/matplotlib/backends/backend_ps.py:
    raise RuntimeError('pdftops was not able to process your image.\nHere is the full report generated by pdftops: \n\n' + fh.read())
else:
    verbose.report(fh.read(), 'debug')

fh.read() is type byte and can not be added to a string in python 3.
In python 3 this can be solved by changing fh.read()to fh.read().decode() but this does probably not work in python 2.

**Comment by anntzer** [comment]
This chunk of code has been completely rewritten now, and the decoding is properly done.
Thanks for the report.
