### ISSUE TITLE
list of markers in documentation could be improved

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7342]
The table at the top of http://matplotlib.org/devdocs/api/markers_api.html could be improved.
- [x] The curly quotes are sometimes in the wrong direction (probably just wrap everything in backquotes).
- [ ] What's the difference between "triangle_down" and "tri_down", if any?  It may be better to actually just draw the markers in the table (possibly using some resembling unicode characters, to keep things simpler?).
- [ ] How do I specify TICKLEFT, CARETLEFT and friends?  (and again I have no ideas how these markers look like)
- [x] The various "nothing" entries could be merged together.
- [ ] What does "the size is normalized" mean for `verts`?  Single x/y rescaling so that the max size (between x and y) is equal to whatever?
- [x] The `(numsides, style, angle)` entry could easily fit within the table itself (not sure how easy this is to do with rst though.

**Comment by petehuang** [comment]
- [x] Fix quotes
- [ ] Document difference between `triangle_*` and `tri_*`
- [ ] Document usage of special-purpose marker identifiers (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/markers.py#L99)
- [x] Merge "nothing entries"
- [ ] Potentially, visually show all markers for explicit examples
- [ ] Clarify the phrase "the size is normalized" for `verts` entry
- [x] Move `(numsides, style, angle)` entry into table

**Comment by QuLogic** [comment]
I copied that information into the original post; that will give the issue a proper progress bar in the issue listing.

**Comment by ImportanceOfBeingErnest** [comment]
I tackled the remaining open points in https://github.com/matplotlib/matplotlib/pull/11437.
