### ISSUE TITLE
atomic saving of pdf

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7347]
I have just noticed that the saving of pdfs can be pretty slow for complex plots (I don't have a MWE but some of my plots take >1min to be saved (2.0b4); one can probably reproduce this just by drawing hundreds of lines with each thousands of points).

This is slightly annoying, of course, but more crucially, the output file is not written in a single step, instead it is progressively written to the disk.  Thus, if one tries to `cp` the file before it is fully written, one ends up with a truncated file.

It would probably be preferable if the writing happened in one go (not sure about whether `with open(...) as file: file.write(...)` is atomic but at worst one can always write to a temporary file and move it).

This may be applicable to other backends as well, I have not checked.

Additionally an hourglass cursor (or whatever is appropriate on your OS) could be added when triggering a save in the GUI.

**Comment by tacaswell** [comment]
Streaming is a major feature of at least the svg backend.

There may still be a bug where some of the collection classes put each sub-artist (patch or path) into it's own group which may be the bottle neck you are hitting.  For Agg this does not matter as it ignores the open_group / close_group calls, but for the vector backends it causes an explosion of nestedness.

**Comment by anntzer** [comment]
Why would one *need* a non-atomic save?  Just curious...

**Comment by ivanov** [comment]
presumably so you can start streaming the result out, in a webserver context, perhaps? ¯\_(ツ)_/¯

**Comment by WeatherGod** [comment]
This can be done at the application level by saving to a tempfile first (in
the same directory as the target file) and then renaming it at the final
step. Easily done with a context manager that yields the temp name when
given the target name. It can then take care of the renaming provided no
exceptions have occurred. Not perfectly atomic on all systems, but it has
been pretty darn reliable for me.

**Comment by anntzer** [comment]
Closing as wontfix based on the comments, I guess.
