### ISSUE TITLE
Colors drawn outside axis for hist2d

### ISSUE THREAD

**Issue by dfreese** [matplotlib/matplotlib#7350]
A bit of a nitpick, but when working with hist2d in matplotlib 2.0.0b3 installed using pip on OS X 10.9.5, I see a problem with the colors being drawn outside the axis ever so slightly at the top and right of the figure.  I generated the attached example using this code:

``` python
import matplotlib
print matplotlib.__version__
import matplotlib.pyplot as plt

measured = np.random.rand(4)

x_pos = np.array((0., 0, 1, 1))
y_pos = np.array((0., 1, 0, 1))

x_pos_unique = np.unique(x_pos)
y_pos_unique = np.unique(y_pos)

x_bins = np.unique(np.hstack((x_pos_unique - 0.5, x_pos_unique + 0.5)))
y_bins = np.unique(np.hstack((y_pos_unique - 0.5, y_pos_unique + 0.5)))

plt.figure()
plt.hist2d(x_pos, y_pos, weights=measured, bins=(x_bins, y_bins))
plt.colorbar()
plt.savefig('overfill_example.pdf')
plt.show()
```

[overfill_example.pdf](https://github.com/matplotlib/matplotlib/files/551472/overfill_example.pdf)

![overfill_example_zoom](https://cloud.githubusercontent.com/assets/3452851/19699295/aa4ba288-9aa7-11e6-8e3b-5404da5b1ac1.png)

**Comment by tacaswell** [comment]
This might be related to #6773 / #6776

**Comment by QuLogic** [comment]
Those tickets are for `imshow` while `hist2d` uses `pcolorfast`, and I can reproduce this all the way back to 1.4.3.

**Comment by QuLogic** [comment]
OK, so in this case, it seems like `pcolorfast` will end up using a `mimage.AxesImage`, but the fact that it's not new might still point to a different issue.

**Comment by tacaswell** [comment]
moved to v2.0.1 as this is not a 2.0 induced bug.

**Comment by QuLogic** [comment]
On further inspection, I think it may have been made worse in the same way that #6773 was made worse.
