### ISSUE TITLE
fill_between columnwise for numpy arrays or pandas dataframe

### ISSUE THREAD

**Issue by tntdynamight** [matplotlib/matplotlib#7355]
This would be a feature request for fill_between supporting automatic multiple drawings (with cycling) by making one shaded area per column in an array, instead of calling a loop. As described [here](http://stackoverflow.com/questions/40256876/fill-between-of-pandas-dataframe-values-by-column?noredirect=1#comment67776089_40256876), it doesn't seem to be implemented but would be helpful when trying to create plots of previously unknown length. 
- I run Matplotlib 1.5.1 on Python 3.5.1/Ipython 4.2.0; Ubuntu 16.04;
- Anaconda install

Example: 
```python
x = np.array([np.arange(4), np.arange(4)]).transpose()
y = np.zeros((4,2))
y[:,1] = 1
yerr=np.zeros((4,2))
yerr[:,0] = 0.1
yerr[:,1] = 0.2

plt.plot(x,y)
```
And then I would like to do something like this (not per column)
```python
plt.fill_between(x,y-yerr,y+yerr)
```
but I get:

```
ValueError: Argument dimensions are incompatible
```

P.S. I hope this is not a dupe, I did search but I could only find a 'cycling' issue referring to color cycling upon multiple calls, not a feature request to have automatic columnwise cycling to create more shaded areas..

**Comment by anntzer** [comment]
Since #7173 got merged, `fill_between` does respect the patch colorcycle, so you can do
```
for _x, _y, _yerr in zip(x.T, y.T, yerr.T):
    plt.fill_between(_x, _y - _yerr, _y + _yerr, alpha=.5)
```
which doesn't seem too bad?  (I'm not convinced that there is that much gain in having an implicit loop over the columns.)

Note that #7173 is not even in 2.0b4 so you'll have to build matplotlib yourself to test it for now.

**Comment by tntdynamight** [comment]
> I'm not convinced that there is that much gain in having an implicit loop over the columns.
The same could be said for plot function. I think it would be nice if it could be used analogously; but thanks for the info and your perspective on this. I guess it's a matter of perspective.

**Comment by anntzer** [comment]
(FWIW I *also* don't think `plot` should implicitly loop over the columns, but that is never going to change :-))

**Comment by oscargus** [comment]
Currently this gives the error: `ValueError: 'x' is not 1-dimensional` which is a bit more explicit about the problem.

**Comment by jklymak** [comment]
Lets close this as won't fix.  `plot` semantics cause a huge mess in trying to guess the correct broadcasting rules - trying to expand that API to fill_between should not be encouraged.
