### ISSUE TITLE
add multi-process flag as `-j` to `test.py`

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7361]
To run the tests in parallel you currently have to add `--processes=8 --process-timeout=300` to the CLI, doing this as `-j 8` would be much nicer.

This should be a 'simple' matter of extending the CLI parsing done in `tests.py`.

**Comment by tacaswell** [comment]
This work should also update `.travis.yml` to use the new CLI arg.

**Comment by QuLogic** [comment]
Fixed by #7362.

**Comment by sandrotosi** [comment]
@tacaswell @QuLogic  is this still working? i tried varied incantation of `-j N` or `-N N` but none work - it would be great to be able to run the test suite in parallel

**Comment by QuLogic** [comment]
It's pytest underneath now, so use `-n N`.

**Comment by QuLogic** [comment]
And you need the pytest-xdist extension.

**Comment by sandrotosi** [comment]
right right, i tried `-N N` instead of `-n N` as doc said, sigh!

but when i set that, i got weird import errors like

```
>               raise ConftestImportFailure(conftestpath, sys.exc_info())
E               _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named 'matplotlib.testing.conftest'",)
E                 File "/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py", line 212, in load_module
E                   py.builtin.exec_(co, mod.__dict__)
E                 File "/home/morph/deb/build-area/matplotlib-2.1.1/build/lib.linux-x86_64-3.6-pydebug/mpl_toolkits/tests/conftest.py", line 4, in <module>
E                   from matplotlib.testing.conftest import (mpl_test_settings,
```

that i dont get when running in sequential mode; we do pass some variables (like `PYTHONPATH`) so maybe they are not passed to the other process; i'll look at it

**Comment by tacaswell** [comment]
We have had issues with the path + execnet (https://bitbucket.org/hpk42/execnet/pull-requests/22/fix-be-more-gentle-about-hacking-the-path/diff) that is the first place I would check.
