### ISSUE TITLE
Moving get_ax and do_event to testing

### ISSUE THREAD

**Issue by jakirkham** [matplotlib/matplotlib#7372]
I'm wanting to do some testing in a library that uses matplotlib. In particular, this library is using matplotlib native widgets.

There appear to be some [utility functions]( https://github.com/matplotlib/matplotlib/blob/6e24047bdcdc0f35d282c27d62324e52fa7a7afb/lib/matplotlib/tests/test_widgets.py#L17-L76 ) used for testing called `get_ax` and `do_event`. These seem like they would be very handy for widget tests like the ones proposed above.

However, I'm not entirely clear on how they can access them ATM as they don't seem to be importable and they are not in `testing` currently. Would it be possible to move them to `testing` so they could be used externally? Related would that actually make sense/be usable for my use case?

**Comment by tacaswell** [comment]
:+1: 

They are not importable because some packings of mpl strip off the the `tests` module (there is a lot of binary image data in there).

**Comment by jakirkham** [comment]
> They are not importable because some packings of mpl strip off the the tests module (there is a lot of binary image data in there).

That's totally reasonable.

Just wanted to make sure I wasn't missing something big w.r.t. using these functions externally. For instance, will I need to have configured an interactive backend to get them to work?

**Comment by tacaswell** [comment]
Doesn't look like it.

That docstring is also very wrong...

**Comment by jakirkham** [comment]
Yep, it could use some help. 😄

Alright, I've put this on my ToDos. Can't promise I'll get to it soon, but I do plan to come back to it.

**Comment by SidharthBansal** [comment]
lib/matplotlib/testing/widgets.py doesn't exist, so to which file should i move these methods?

**Comment by tacaswell** [comment]
@SidharthBansal Please make that file.

**Comment by tacaswell** [comment]
I suggest taking the commits in https://github.com/matplotlib/matplotlib/pull/9905, rebasing them on master, pushing to a branch on your fork and then leaving a note on that 9905 that you have taken over the work.
