### ISSUE TITLE
Regression in imshow

### ISSUE THREAD

**Issue by alfredobrent** [matplotlib/matplotlib#7373]
The imshow command in 2.0.0b4 and current master (07adcde) don't export images with colormaps correctly. The colormap is not scaled correctly:

![imshow_git](https://cloud.githubusercontent.com/assets/23195715/19898477/8731c56c-a032-11e6-963c-79a487526138.png)

This bug is not present in 1.5.1:

![imshow_1 5 1](https://cloud.githubusercontent.com/assets/23195715/19898475/827e8a28-a032-11e6-8b52-c9470035afb8.png)

Some precisions:
* version 1.5.1 from ubuntu 16.04 repository
* git master (07adcde) #installed from source on ubuntu 16.04

Code to reproduce this behavior:

```python
#!/usr/bin/env python2.7
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

print(matplotlib.__version__)

cmap = plt.cm.jet

# coordinates
bbox=20
resolution = 100

xcoords = np.linspace(0, bbox, resolution)
ycoords = np.linspace(-bbox, bbox, 2*resolution)
    
# evaluate
xnb = len(xcoords)
ynb = len(ycoords)
dat = np.zeros((ynb,xnb))
for i in range(xnb):
    for j in range(ynb):
        dat[j][i] = np.sqrt(xcoords[i]**2+ycoords[j]**2)
# export to png
plt.imsave("imshow.png", dat, cmap=cmap, vmin=0, vmax=None)
```

**Comment by tacaswell** [comment]
```python
#!/usr/bin/env python2.7
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

print(matplotlib.__version__)

cmap = 'viridis'

# coordinates
bbox=20
resolution = 100

xcoords = np.linspace(0, bbox, resolution).reshape(1, -1)
ycoords = np.linspace(-bbox, bbox, 2*resolution).reshape(-1, 1)
    
# evaluate
dat = np.hypot(xcoords, ycoords)
fig, ax = plt.subplots()
ax.imshow(dat)
```

Oddly, does not happen with `imshow` 

![so](https://cloud.githubusercontent.com/assets/199813/19901428/84381842-a03d-11e6-8eda-3d55290472b5.png)

but does happen with `imsave`

![imshow](https://cloud.githubusercontent.com/assets/199813/19901535/b9c38050-a03d-11e6-8352-919ca5734745.png)


I will have a PR for this shortly.
