### ISSUE TITLE
mpl_toolkits.axes_grid1.axes_divider.LocatableAxes has inconsistent ticks

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#7378]
I'm using latest `v2.x` (4ea9892ea300a9773c1f2bf6e05b1c7771557248) to build some documentation and several examples are a bit non-reproducible. It seems like this is usually triggered by the examples that use `AxesGrid`. I've drilled down to it being something weird with `LocatableAxes`, which can be seen with this example:
```python
import sys

import matplotlib.pyplot as plt
from matplotlib.transforms import Bbox
from mpl_toolkits.axes_grid1.axes_divider import LocatableAxes
from mpl_toolkits.axes_grid1.mpl_axes import Axes

AxesClass = LocatableAxes
#AxesClass = Axes

fig = plt.figure(1)
ax = AxesClass(fig, Bbox([[0.05, 0.05], [0.95, 0.95]]))
fig.add_axes(ax)

plt.savefig(sys.argv[1] + '.png')
```
If you run two or three times and compare the images, the ticks in the corners will generally be slightly off, usually differing by one bit in the outermost pixel. If you uncomment the line above to use `Axes` instead, then there is no issue. If I understand correctly, `LocatableAxes` just adds the `LocatableAxesBase` mixin to `Axes`, which _appears_ to do nothing much by default. So I don't really understand why it breaks stuff.

This is probably related to the bugginess in #6759.

**Comment by anntzer** [comment]
LocatableAxes is no more (deprecated in https://github.com/matplotlib/matplotlib/pull/10403 and removed in master), so I think this can be closed?
