### ISSUE TITLE
Mp4's generated by movie writer do not appear work in browser

### ISSUE THREAD

**Issue by notmatthancock** [matplotlib/matplotlib#7379]
The mp4 file generated from the [`moviewriter.py` example](http://matplotlib.org/examples/animation/moviewriter.html) does not appear to work in the browser. I have tested on Firefox 49.0.2 and Chromium 53.0.2785.143. My OS is Ubuntu 16.04, and my matplotlib version is 1.5.3.

Firefox complains that the movie is corrupt, while Chromium gives the message `MediaEvent: PIPELINE_ERROR demuxer: no supported streams`.

I have found a [mailing list thread](https://mail.python.org/pipermail//matplotlib-users/2016-April/000437.html) mentioning this issue, but I'm not sure how the proposed solution:

`anim.save('file.mp4', extra_args=['-pix_fmt', 'yuv420p'])`)

fits into the `moviewriter.py` example, since the this example uses the `saving( ... )` context manager, which does not accept the `extra_args` argument.

Can this be fixed from matplotlib? or is this a browser / ffmpeg issue?

**Comment by tacaswell** [comment]
The context manager not taking arg/kwargs has been fixed on both 2.x (https://github.com/matplotlib/matplotlib/pull/7207) and master (https://github.com/matplotlib/matplotlib/pull/6304)

Does the movie work in other players?

Me also just changed the default codec to h264 (https://github.com/matplotlib/matplotlib/pull/7208) which might work better.

You can also inject the extra kwargs through an rcParam (but I do not remember which one off the top of my head).

**Comment by notmatthancock** [comment]
> Does the movie work in other players?

Yes.

> You can also inject the extra kwargs through an rcParam ...

I tried:
`plt.rcParams['animation.ffmpeg_args'] = ['-pix_fmt', 'yuv420p']`
and
`plt.rcParams['animation.convert_args'] = ['-pix_fmt', 'yuv420p']`
with no luck.

So, I just upgraded to the latest:
```
pip install git+git://github.com/matplotlib/matplotlib@master
python -c "import matpllib as mpl; print mpl.__version__"
2.0.0b4+2688.g297988c
```
and the mp4's now work in both Firefox and Chromium.

Thanks. I'll close this now.
