### ISSUE TITLE
Example examples/misc/multiprocess.py may not be python3 compatible?

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7388]
It uses raw_input, which I believe has disappeared from python3.

**Comment by rishikksh20** [comment]
@NelleV How about this if I replace : 
```raw_input('press Enter...')```
to
``` 
try: input = raw_input
except NameError: pass
input('press Enter...'))
```
its working fine for both python2 and python3

**Comment by tacaswell** [comment]
@rishikksh20 Can you open a PR with that change?

**Comment by rishikksh20** [comment]
@tacaswell Yes I do

**Comment by anntzer** [comment]
There's also the use of the gtkagg backend (and explicit import of gobject), which is not supported on py3.

**Comment by naoyak** [comment]
Looks like this should have been closed by #7729?

**Comment by anntzer** [comment]
Not the issue I just mentioned.

**Comment by souravsingh** [comment]
@anntzer Would use of Tkagg backend fix the problem with the example?

**Comment by anntzer** [comment]
dunno, try it :)

**Comment by WeatherGod** [comment]
We need something that would halt the interpreter, awaiting input. If Tk
has something like that, that might be useful.
