### ISSUE TITLE
Documentation guidelines improvements 2

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#7412]
Hey all - these are some quick issues I ran across when following the documentation guidelines. I can open a PR to fix them later (once I get the docs finally built) but want to make sure all the points I ran into are worth changing:

1. There are extra dependencies not listed there. In particular a Latex package with at least the package "type1cm". It would be helpful to point people to a latex distribution page if necessary.
2. When I was trying to build the docs initially I ran into a bunch of weird errors where the answer was usually solved by deleting a folder that is auto-generated by the docs build (e.g. the `examples` folder w/ the rendered rst files etc). It might be useful to include a quick section like "if something doesn't work and you can't find the answer here, try these steps to see if it fixes things". I'm imagining something like how I tell people "did you turn your computer off and on?" when they have computer problems.
3. There's a dependency on graphviz. Can't remember if this is documented or not but in case it's not I'm putting this here.

If anything else comes up I can bring it up here, this will serve as a placeholder for my own experience. @NelleV if you can remember anything that came up when we were doing this before then feel free to note here and I can make a change to the docs later on.

**Comment by NelleV** [comment]
Hi @choldgraf 
Thanks for keeping track of the problems you have. Do you think you could open a PR to update the documentation?

PS: I don't remember much from our installation attempt at the summit.

**Comment by choldgraf** [comment]
I can open a PR as soon as I can actually build the documentation ;)

**Comment by choldgraf** [comment]
Closing this because I think we figured these points out in subsequent PRs in the last few months
