### ISSUE TITLE
Document that python setup.py develop add the symlink to easy-install.pth

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#7422]
Else, it's really hard to "uninstall" matplotlib.

**Comment by anntzer** [comment]
It looks like `pip install -e .` / `pip uninstall matplotlib` handles this fine.  I'd suggest switching the docs to recommending using those (specifically `pip install --upgrade --no-deps -e .`, which is the more practical set of flags I think).

**Comment by tacaswell** [comment]
Both methods are currently in the docs as of https://github.com/matplotlib/matplotlib/pull/7229

**Comment by anntzer** [comment]
I'd rather move the pip-based method first (and explicitly recommend it), given, again, that it does not suffer from the issue @NelleV mentions.  (But it is only better if you remember to include the `--upgrade` (and possibly `--no-deps`) flags.)

**Comment by efiring** [comment]
I think `--upgrade` is dangerous; at least in some versions of pip, it upgrades all dependencies without the courtesy of even listing them and then asking if that is what you really want to do.  Does `--no-deps` reliably take care of that, or is it only available in newer versions of pip?  After being bitten by the unwanted upgrades, I switched to always uninstalling first, so `--upgrade` is not needed.
Apart from that, I agree, the pip methods should be emphasized because they handle uninstalling.

**Comment by QuLogic** [comment]
In a conda env, I've never had to use `--upgrade`; not too sure why that is though.

**Comment by anntzer** [comment]
I never had this issue while using `--no-deps`.  I have no idea about whether this was broken on previous versions but we can always first suggest `pip install --upgrade pip` and then we only have to care about the latest pip, which I'm certain implements this correctly :-)

**Comment by petehuang** [comment]
So the latest on this is that we feel positive about two changes in https://github.com/matplotlib/matplotlib/blob/master/doc/devel/contributing.rst:

1. Add language around `pip install --upgrade pip` to ensure that all pip commands on the page run well
2. Move a variant of the `pip install` method first (before `python setup.py develop`). Remaining question is which exact variant we want? Thoughts?

**Comment by NelleV** [comment]
fyi, I am against moving the pip command before the python setup.py install.
It is not a standard way of installing python packages. I would suggest waiting until that is the case (as IMO it is very unlikely that it will ever become the standard way to install python packages).

**Comment by efiring** [comment]
@NelleV, in https://docs.python.org/3/installing/, it says,

pip is the preferred installer program. Starting with Python 3.4, it is included by default with the Python binary installers.

You would maintain that although it is officially "preferred" it is not "standard", and is unlikely to become so?

**Comment by tacaswell** [comment]
Also see https://pip.pypa.io/en/stable/reference/pip_install/#usage .
This is also how IPython recommends installation http://ipython.readthedocs.io/en/stable/install/install.html?highlight=setup.py#installation-from-source

I have been test-driving always using pip for installing things from source for the last few months and am pretty happy.  It is less to type and reliably uninstalls (both develop and normal installs).

Going down this path also offers a sliver of hope that the setptools/distutils Gordian knot will ever be untangled (by localizing it all in `pip` first).

I am comfortable with mpl being on the leading edge of this shift.
