### ISSUE TITLE
from matplotlib.backends import _tkagg raises AttributeError: 'module' object has no attribute '__file__'

### ISSUE THREAD

**Issue by ettaka** [matplotlib/matplotlib#7428]
Matplotlib version: built from source after commit ba019f7119dc10e7531b148d1046b1fbce519976 (8.11.2016)
Python version: 2.7.12 (built from source)
Platform: Ubuntu Linux 14.04 

The following dialog with python interpreter demonstrates the problem I'm having:
>>> from matplotlib.backends import _tkagg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'
>>> _tkagg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_tkagg' is not defined
>>> from matplotlib.backends import _tkagg
>>> _tkagg
<module 'matplotlib.backends._tkagg' (built-in)>

Here are the key points:
1. Python is not able to import matplotlib.backends._tkagg at first
2. When the import is tried the second time it is succesfull
3. The _tkagg is built-in module which I believe should not have '__file__' attribute but at first Python would like to have it

Please advise.

Best Regards,

Eelis

**Comment by tacaswell** [comment]
@matthew-brett Could this be related to the tk linking changes making assumptions about how python was built?

@ettaka How did you build python?  Can you reproduce this issue with either system  / anaconda  / enthought built python?

**Comment by ettaka** [comment]
@tacaswell Many thanks for the reply! I built python with _ssl and _tkinter using tcl/tk8.5. Additionally I followed the INSTALL document when building matplotlib and I think I installed all the required packages and optional packages that I needed. I'm not sure what you mean by reproducing this issue with these other systems, could you ellaborate.

**Comment by tacaswell** [comment]
I mean if you build mpl from source against a not-built-from-source python do you still have this issue?

In the worst maintainer response ever 'works on my machine'

<details>
```
10:16 $ ipython
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.backends._tkagg

In [2]: import matplotlib

In [3]: matplotlib.__version__
Out[3]: '2.0.0b4+2755.gba019f7'

In [4]: 

```
</details>

using 2.7.12 from anaconda/continuum which makes me suspicious that it is something wrong with your build of CPython that is tripping up `_tkagg` / the mpl build system.   Testing you can build against the pre-built binaries as well will help narrow the places where this could be going wrong down.

**Comment by matthew-brett** [comment]
@ettaka - what do you get for:

```
ipython
In [1]: import Tkinter
In [2]: Tkinter.TkVersion
In [3]: Tkinter.TclVersion
```

**Comment by ettaka** [comment]
@tacaswell Thanks for the clarification! I tried with anaconda2 and you are right, it does work with that build. So that means there is a problem with my python built. Do you have any good guesses what could be the problem? Or how to debug this?

@matthew-brett This is what I get: 
Python 2.7.12 (default, Nov  8 2016, 15:17:25)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
>>> Tkinter.TkVersion
8.5
>>> Tkinter.TclVersion
8.5
>>>

**Comment by ettaka** [comment]
@matthew-brett I tried also Tkinter._test() and it works.

**Comment by matthew-brett** [comment]
Thanks for the extra info.  What do you get for:

```
In [1]: import Tkinter
In [2]: Tkinter.tkinter.__file__
```

**Comment by ettaka** [comment]
@matthew-brett I appreciate your help. This is what I get with my own built:
>>> import Tkinter
>>> Tkinter.tkinter.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'

And with the anaconda2 built I get the dynamic library in the lib-dynload folder of that python: anaconda2/lib/python2.7/lib-dynload/_tkinter.so

**Comment by ettaka** [comment]
@matthew-brett somehow Tkinter has become a built-in module (my own built):
>>> Tkinter.tkinter
<module '_tkinter' (built-in)>

whereas in the anaconda2 built it is an external library:
>>> Tkinter.tkinter
<module '_tkinter' from '/export/home/eelis/anaconda2/lib/python2.7/lib-dynload/_tkinter.so'>

**Comment by matthew-brett** [comment]
Yes, that explains the error - matplotlib is looking for a compiled module, that should have a ``__file__`` attribute.  Now the question is - what was it about your build that resulted in `Tkinter` being built-in?  Can you give any more details about it?

More general question - maybe to @mdboom - do you have any idea how to find the symbols of built-in modules at run time, in C?   Specifically, have y'all got any idea how to modify https://github.com/matplotlib/matplotlib/blob/master/src/_tkagg.cpp#L417 to find the tcl / tk symbols?

**Comment by ettaka** [comment]
@matthew-brett I installed the prerequisites (tk8.5 and tk8.5-dev) and then enabled _tkinter module from the python source folder Modules/Setup.dist, like so:
 # The _tkinter module.
 #
 # The command for _tkinter is long and site specific.  Please
 # uncomment and/or edit those parts as indicated.  If you don't have a
 # specific extension (e.g. Tix or BLT), leave the corresponding line
 # commented out.  (Leave the trailing backslashes in!  If you
 # experience strange errors, you may want to join all uncommented
 # lines and remove the backslashes -- the backslash interpretation is
 # done by the shell's "read" command and it may not be implemented on
 # every system.

 # *** Always uncomment this (leave the leading underscore in!):
  **_tkinter _tkinter.c tkappinit.c -DWITH_APPINIT \**
 # *** Uncomment and edit to reflect where your Tcl/Tk libraries are:
 #      -L/usr/local/lib \
 # *** Uncomment and edit to reflect where your Tcl/Tk headers are:
        **-I/usr/include/tcl8.5 \**
 # *** Uncomment and edit to reflect where your X11 header files are:
 #      -I/usr/X11R6/include \
 # *** Or uncomment this for Solaris:
 #      -I/usr/openwin/include \
 # *** Uncomment and edit for Tix extension only:
 #      -DWITH_TIX -ltix8.1.8.2 \
 # *** Uncomment and edit for BLT extension only:
 #      -DWITH_BLT -I/usr/local/blt/blt8.0-unoff/include -lBLT8.0 \
 # *** Uncomment and edit for PIL (TkImaging) extension only:
 #     (See http://www.pythonware.com/products/pil/ for more info)
 #      -DWITH_PIL -I../Extensions/Imaging/libImaging  tkImaging.c \
 # *** Uncomment and edit for TOGL extension only:
 #      -DWITH_TOGL togl.c \
 # *** Uncomment and edit to reflect your Tcl/Tk versions:
        **-ltk8.5 -ltcl8.5 \**
 # *** Uncomment and edit to reflect where your X11 libraries are:
 #      -L/usr/X11R6/lib \
 # *** Or uncomment this for Solaris:
 #      -L/usr/openwin/lib \
 # *** Uncomment these for TOGL extension only:
 #      -lGL -lGLU -lXext -lXmu \
 # *** Uncomment for AIX:
 #      -lld \
 # *** Always uncomment this; X11 libraries to link with:
        **-lX11**

**Comment by matthew-brett** [comment]
Just a shot in the dark, but try this patch to matplotlib:

```
diff --git a/src/_tkagg.cpp b/src/_tkagg.cpp
index 9191992..f63c832 100644
--- a/src/_tkagg.cpp
+++ b/src/_tkagg.cpp
@@ -406,10 +406,19 @@ int load_tkinter_funcs(void)
     // Load tkinter global funcs from tkinter compiled module.
     // Return 0 for success, non-zero for failure.
     int ret = -1;
-    void *tkinter_lib;
+    void *main_program, *tkinter_lib;
     char *tkinter_libname;
     PyObject *pModule = NULL, *pSubmodule = NULL, *pString = NULL;
 
+    // Try loading from the main program namespace first
+    main_program = dlopen(NULL, RTLD_LAZY);
+    if (_func_loader(main_program) == 0) {
+        return 0;
+    }
+    // Clear exception triggered when we didn't find symbols above.
+    PyErr_Clear();
+
+    // Now try finding the tkinter compiled module
     pModule = PyImport_ImportModule(TKINTER_PKG);
     if (pModule == NULL) {
         goto exit;
```

**Comment by ettaka** [comment]
@matthew-brett Nice work dude! The isolated test problem no longer produces the error. Moreover the __file__ is now an attribute for _tkagg module. Thanks alot! I will still try this on my program.

**Comment by matthew-brett** [comment]
Thanks for testing.  If that works for your program, let us know?  I'll make a pull request with this change.

**Comment by matthew-brett** [comment]
I submitted the pull request in hope that it works for you: https://github.com/matplotlib/matplotlib/pull/7433

**Comment by ettaka** [comment]
@matthew-brett Very nice, thank you! After applying your patch I didn't see any problems regarding this issue anymore. However, I will still run a few tests to be sure. I will keep you informed.

**Comment by ettaka** [comment]
@matthew-brett @tacaswell yup, definetely not a problem anymore. I humbly thank both of you for your help and quick reaction to this!
