### ISSUE TITLE
Two entries in examples fo marker_reference.py

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7429]
There are two entries in http://matplotlib.org/devdocs/gallery.html#lines_bars_and_markers for marker_reference.py that point to the same page -- likely because that example generates *two* plots.

A few possibilities:
- generate a single plot (probably the simplest and good enough).
- split the example into two files.
- somehow have the second link point to an HTML anchor corresponding to the second plot.

**Comment by petehuang** [comment]
This happens many, many times in the gallery:

+ `marker_reference`
+ `boxplot_demo`
+ `interpolation_none_vs_nearest`
+ `streamplot_demo_features`
+ `pie_demo_features`
+ etc.

Is having multiple links to the same page that bad? Certainly a repetition concern, but I don't know that the DRY mentality needs to be held as strongly for docs

**Comment by tacaswell** [comment]
I strongly prefer the third option (making the gallery link out to the correct image).  This may be made moot by sphinx-gallery @NelleV ?

**Comment by dopplershift** [comment]
For sphinx-gallery, you get one thumbnail, though you you have the option of controlling which plot it selects.

**Comment by choldgraf** [comment]
This is no longer an issue since we're using sphinx-gallery...this issue can be closed

**Comment by QuLogic** [comment]
For some reason, the file @anntzer linked is still in the devdocs when it shouldn't be, but if you navigate to the correct gallery page, then there are no duplicates as @choldgraf states.

**Comment by choldgraf** [comment]
that is weird!

**Comment by QuLogic** [comment]
Could be because of #8875.
