### ISSUE TITLE
Confusing examples in `annotation_demo2`

### ISSUE THREAD

**Issue by soupault** [matplotlib/matplotlib#7440]
It is difficult to understand the correspondence between the visualized annotations and the generative code snippets in http://matplotlib.org/examples/pylab_examples/annotation_demo2.html.

I suggest to change the text in `arc`, `angle`, and `wedge` calls to something like `arc_0`, `arc_1`, etc.

Let me know if the proposed fix is of any interest. If so, I'm willing to work on it.

**Comment by tacaswell** [comment]
We :heart: documentation improvements!

Tagged this an 'new-contributor-friendly' in case @soupault does not get to this.  

The work to do is:
  -  make the text in the figures easier to map back to the snippets. 
  - remove the `if 1` clauses

link to master version of docs: http://matplotlib.org/devdocs/examples/pylab_examples/annotation_demo2.html
