### ISSUE TITLE
pdf doc build is sort of broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7443]
In https://github.com/matplotlib/matplotlib/pull/7025/files#diff-d16d8f2163ade22dd20a465382c64881R148 I added some unicode to the docs which is not well handled by the latex.  It causes an error (which can be ignored by typing 'R' into the prompt) when bulding the docs.

That example could be fixed by:

 - removing the offending lines
 - sorting out how to make latex deal with Chinese characters
 - html-only that block

**Comment by QuLogic** [comment]
It may also work if setting docs to build with xelatex or lualatex, but those both might require some tweaks to the preambles.

**Comment by NelleV** [comment]
@sirlittle is going to work on this.

**Comment by dopplershift** [comment]
Removing the offending *characters* seems like the simplest solution--and given that it's just example output from a utility, I don't think the docs would lose anything by doing so.

**Comment by NelleV** [comment]
Let me see what I can do first. It is possible that it is a one liner fix.
