### ISSUE TITLE
Using Matplotlib in Abaqus

### ISSUE THREAD

**Issue by X-G** [matplotlib/matplotlib#7450]
I'm trying to use Matplotlib in Abaqus. Abaqus is a  finite element method software, which has Python embedded as a scripting language.
First, I install Matplotlib-1.5.2 on my Ubuntu machine using:
```
sudo apt-get install python-matplotlib
```
Then, I start Abaqus, in Abaqus-python, I append the path of the Matplotlib directory:
```
from sys import path
path.append('/usr/lib/python2.7/dist-packages')
```
after that, when I import the Matplotlib modules in Abaqus-python:
```
import matplotlib.pyplot as plt
```
I got the following traceback:
```
File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 14, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: No module named _path
```
Both the Ubuntu-python and Abaqus-python are version 2.7.

**Comment by QuLogic** [comment]
The compiled modules are probably not compatible that way, even if it's still 2.7; it would be better if you could install matplotlib using Abaqus' Python.

**Comment by X-G** [comment]
@QuLogic thanks for you reply. 
The problem is that Abaqus' Python is not extendable friendly. The only way I found is copy the 3rd party folder to Abaqus's Python default location, or append the `path` with the system's Python Matplotlib directory.
This method works fine on Windows platform, I created a project on github: [matplotlib-4-abaqus](https://github.com/Solid-Mechanics/matplotlib-4-abaqus). But I still cannot make it work on Linux platform.

**Comment by Kojoley** [comment]
Have you tried something like this in the Abaqus-python?
```python
import pip
pip.main(['install', 'matplotlib'])
```

**Comment by X-G** [comment]
@Kojoley , in Abaqus' Python, I cannot find a method to install `pip`. Basically, Abaqus' Python is a very closed Python environment.

**Comment by caiuamelo** [comment]
@X-G Thanks for reopening this issue

I am dealing with the same problem. Maybe an additional important information is the Abaqus python sys version:
`>>> sys.version
'2.7.3 (default, May 23 2015, 00:02:36) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]' `

**Comment by X-G** [comment]
@caiuamelo Is there any possibility that install a Python at exact the same path with the Abaqus' Python, and install Matplotlib in this Python environment. Then copy the installed package to Abaqus' Python.
Is this approach feasible?

**Comment by caiuamelo** [comment]
Not sure it is possible, maybe using Anaconda.
[https://www.continuum.io/downloads](url)

**Comment by tacaswell** [comment]
This might be better served on the user mailing list. (matplotlib-users@python.org)

**Comment by efiring** [comment]
I see this as not in any way a matplotlib-specific problem, but rather a problem with adding compiled modules to software with embedded python interpreters.  Are there any support options for Abaqus?  If not, stackoverflow might reach a wider audience that could help--or definitively say the situation cannot be helped.

**Comment by X-G** [comment]
@tacaswell @efiring Thanks for your suggestions and your efforts to Matplotlib.
