### ISSUE TITLE
Raise error if argument to xlim is invalid, e.g., nan

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7460]
As of 2.0b4, passing `nan` as a limit to `xlim` seems to reset *both* limits to `(-0.001, 0.001)` (try e.g. with `plt.plot([0, 1]); plt.xlim(right=np.nan)`).  I think this should either error, or, more usefully, be interpreted as None (i.e. leave that limit as is).  (For extra points, we can also bikeshed what passing `inf` to `xlim` should mean.)

The main use case would be when the `xlim` is read from some float context (e.g. from an array) where you can easily store `nan` but not `None`.

**Comment by tacaswell** [comment]
Biased toward erroring, using `np.nan` as a stand in for `None` seems a bit too clever and surprising, but am open to be talked into it.

From git-blame, I think that this behavior has been long standing (e356a151a7df2f2ececbfbc6d3f69eaf4ae522b9 in 2008 from @efiring )

**Comment by NelleV** [comment]
So your suggestion is to raise an error?

**Comment by NelleV** [comment]
(I'd raise an error…)

**Comment by tacaswell** [comment]
That seems to be 1.5 votes to error.

**Comment by efiring** [comment]
Make that 2.5.

**Comment by anntzer** [comment]
I'm fine with making it an error too.  Same with `inf`?

**Comment by efiring** [comment]
Yes.  Sounds like an `np.isfinite` check is in order.

**Comment by bcongdon** [comment]
Working on this now. It looks like `np.isfinite` raises an error if you pass it something non-numeric, like a date.

Do we need the full `np.isfinite` check, or can we just reject `np.nan` and `np.inf` values?

**Comment by efiring** [comment]
I think you can handle that by putting the check after the calls to `convert_xunits`; I think that `np.isfinite` should be safe there.

**Comment by tacaswell** [comment]
We now have 3 PRs for this!

**Comment by QuLogic** [comment]
Closed by #7744 and #8022.
