### ISSUE TITLE
The default backend (Qt4Agg) seems to change the figure size

### ISSUE THREAD

**Issue by Patrick5** [matplotlib/matplotlib#7472]
The default backend (Qt4Agg) seems to be changing my figure size. The problem does not occur in AGG, TKAGG, or WEBAGG backends. I have not tested others.  

Matplotlib version:  1.5.3  installed via anaconda
Python version:  3.5.2
Platform: Windows 8.1

The following is the minimal code I came up with that will reproduce the problem:

`import matplotlib.pyplot as plt`
`fig = plt.figure()`
`print('size before:', fig.get_size_inches())`
`fig.canvas.flush_events()`
`fig.canvas.flush_events()`
`print('size after:', fig.get_size_inches())`

This produces console output:
size before: [ 8.  6.]
size after: [ 8.    5.95]

In more general use this typically arises after a couple of frames have been displayed, and specifically causes a problem when making a movie from those displayed images: the output rolls by 5 pixels from frame to frame. Playing back the resulting mp4 looks like an old analog TV with the vertical sync out of whack. 

BTW, one workaround is to call `fig.set_size_inches(8,6)` after the second flush above but before any frames are generated or grabbed, as the size does not seem to get changed again.

**Comment by tacaswell** [comment]
related to https://github.com/matplotlib/matplotlib/issues/7353

**Comment by QuLogic** [comment]
I can't seem to reproduce this with Qt4; are you sure you aren't using Qt5?

**Comment by tacaswell** [comment]
@QuLogic I _thought_ I was using qt4 in #7353 , but I could be wrong (as I work in conda envs and may have accidentally jumped to qt5 and I know @anntzer is using qt5).

@Patrick5 The 1.5.3 builds from continuum pin to qt5 (see https://github.com/ContinuumIO/anaconda-issues/issues/1068)  Can you check the output of `matplotlib.get_backend()`?

**Comment by anntzer** [comment]
FWIW I cannot reproduce this with mpl1.5.3 or 2.0rc1 / qt4agg or qt5agg on Arch Linux.

**Comment by QuLogic** [comment]
Weird, I thought I could reproduce this yesterday, but I can't seem to find those results and can't reproduce now. Anyway, if it's actually Qt5, then I'm pretty sure this is the same as #7353.

**Comment by Patrick5** [comment]
get_backend() reports 'Qt4Agg'.  Also, I am still on Python 3.5.2 for 
what that is worth.

I have not had time to upgrade either QT or Python.

I am not surprised if the bug does not occur on Linux - I had an idea 
that the problem results from computing the window size but getting the 
sizes of the individual parts wrong by a few pixels. That computation is 
probably OS specific.

**Comment by tacaswell** [comment]
@Patrick5 Can you try with #7610 ?  I am not sure which of of our devs overlap between qt and windows users.

**Comment by tacaswell** [comment]
Manually re-opening as this may be OS specific.

**Comment by QuLogic** [comment]
Based on #17391, this seems to only be a problem with Qt5Agg on macOS now.

**Comment by tacaswell** [comment]
I could not reproduce this on OSX with the qtAgg backend.  I am going to close this is fixed unless someone else can reproduce it.
