### ISSUE TITLE
Using pdflatex in texmanager

### ISSUE THREAD

**Issue by dslochower** [matplotlib/matplotlib#7480]
What is the correct way to define a macro in the `text.latex.preamble` of `mpl.rcParams`? For example, say that I have the following preamble set:
```python
    mpl.rc('text', usetex=True)
    mpl.rcParams['text.latex.preamble'] = [
        r'\usepackage{amsmath}',
        r'\usepackage{helvet}',
        r'\usepackage{sansmath}',
        r'\sansmath',
        r'\renewcommand{\familydefault}{\sfdefault}',
        r'\usepackage[T1]{fontenc}',
        r'\usepackage{graphicx}',
        r'\usepackage{relsize}',
        r'\newcommand{\bigpi}{\scalebox{5}{\ensuremath{\pi}}}'
    ]
```
...and then I try to render a figure like so, using `jupyter notebook`
```python
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
mpl.rc('text', usetex=True)
mpl.rcParams['text.latex.preamble'] = [
    r'\usepackage{amsmath}',
    r'\usepackage{helvet}',
    r'\usepackage{sansmath}',
    r'\sansmath',
    r'\renewcommand{\familydefault}{\sfdefault}',
    r'\usepackage[T1]{fontenc}',
    r'\usepackage{graphicx}',
    r'\usepackage{relsize}',
    r'\newcommand{\bigpi}{\scalebox{5}{\ensuremath{\pi}}}'
]

plt.figure(figsize=(12,8))
plt.plot(range(5))
plt.xlabel(r'Hi $\bigpi$')
```
The pi symbol in the caption is rendered at normal size, instead of large size. If I go look in the temporary `.tex` files, I can see 
```latex
\documentclass{article}
\usepackage{type1cm}
\renewcommand{\rmdefault}{pnc}

\usepackage{courier}
\usepackage{textcomp}

\usepackage{amsmath}
\usepackage{helvet}
\usepackage{sansmath}
\sansmath
\renewcommand{\familydefault}{\sfdefault}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{relsize}
\newcommand{\bigpi}{\scalebox{5}{\ensuremath{\pi}}}
\usepackage[papersize={72in,72in},body={70in,70in},margin={1in,1in}]{geometry}
\pagestyle{empty}
\begin{document}
\fontsize{20.000000}{25.000000}{\sffamily Hi $\bigpi{}$}
\end{document}
```
...which looks normal. If I take this `tex` file and compile it with `pdflatex`, everything looks as expected. But if I compile with `latex` to get a `dvi` file, the pi is not scaled. So I think the problem is that Matplotlib is compiling the LaTeX source code to `dvi` files and using those to compose the figure.
![image](https://cloud.githubusercontent.com/assets/23266236/20401652/8bba616a-acae-11e6-9749-f76c23e48a65.png)
![image](https://cloud.githubusercontent.com/assets/23266236/20401654/8eef5232-acae-11e6-8a0c-e28dcbfd58d8.png)

Is there a way to force Matplotlib to use the `pdflatex` backend? Do I need to use pgf to do this? I tried changing the `rcParams` setup to this
```python
from matplotlib.backends.backend_pgf import FigureCanvasPgf
mpl.backend_bases.register_backend('pdf', FigureCanvasPgf)

pgf_with_pdflatex = {
    "pgf.texsystem": "pdflatex",
    "text.usetex": True,
    "pgf.preamble": [
    r'\usepackage{amsmath}',
    r'\usepackage{helvet}',
    r'\usepackage{sansmath}',
    r'\sansmath',
    r'\renewcommand{\familydefault}{\sfdefault}',
    r'\usepackage[T1]{fontenc}',
    r'\usepackage{graphicx}',
    r'\usepackage{relsize}',
    r'\newcommand{\bigpi}{\scalebox{5}{\ensuremath{\pi}}}'
    ]
}
mpl.rcParams.update(pgf_with_pdflatex)
```
...but then there's no pi at all.

- Matplotlib version 1.5.1 with Python 3.5.1. :: Anaconda custom (64-bit) on CentOS 7

**Comment by tacaswell** [comment]
To use a `pdflatex` I suspect you would have to rewrite https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/texmanager.py#L89 specifically `make_dvi` and/or `make_png` as `latex` is hard-coded (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/texmanager.py#L401)

**Comment by slochower** [comment]
@tacaswell aha, thanks for the pointer. I might give that a shot.

**Comment by dslochower** [comment]
@tacaswell aha, thanks for the pointer. I might give that a shot.

**Comment by dslochower** [comment]
@jkseppan Interesting, thanks, I appreciate the insight. I didn't have time to look into this further at the time, but it may be worth a look in the future.
