### ISSUE TITLE
Is there a way to subclass the zoom() function from the NavigationToolbar backends and modify its mouse button definition? 

### ISSUE THREAD

**Issue by Pynewbie2016** [matplotlib/matplotlib#7485]
First of all, I have to say the predefined functions from matplotlib is wonderful. For historical reasons, however, I need to modify the mouse motion for the zoom() function to do the following,

1) holding mouse button 1 & drag downwards -> zoom in
2) holding mouse button 1 & drag upwards -> zoom out

and I have spent a week on this now without success

Any help will be greatly appreciated!

**Comment by tacaswell** [comment]
This sort of question is best handled on the mailing list (matplotlib-users@python.org you will need to [join the list](https://mail.python.org/mailman/listinfo/matplotlib-users) to post un-moderated.  We try to keep the issues for bug reports or feature requests.
