### ISSUE TITLE
Funny things happen when a rectangle with negative width/height is passed to `axes()`

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7487]
mpl 2.0b4
```
axes([.9, .9, -.8, -.8]); plot([1, 2])
```
![negative-axes](https://cloud.githubusercontent.com/assets/1322974/20459953/ea7f8bb8-ae88-11e6-9618-530b10bded01.png)

Interative zooming seems to work but fails to draw the rubber-band; I suspect it is because the implementation of `drag_zoom` assumes that the axes' bbox extents are in the "standard" order:
```
            x1, y1, x2, y2 = a.bbox.extents
            x, lastx = max(min(x, lastx), x1), min(max(x, lastx), x2) # probably happens here
            y, lasty = max(min(y, lasty), y1), min(max(y, lasty), y2)
```
(and I'd guess there may be other issues elsewhere).

Not sure whether we want to do something about it (which may be as simple as reordering the bbox extents in the Axes constructor, or raising an exception if the width or height are negative), or just document that this is not supported and live with it.

**Comment by tacaswell** [comment]
How do you find these things?!

I am in favor of raising.

**Comment by anntzer** [comment]
I was trying to figure out what exactly was happening in [`NavigationToolbar2.drag_zoom`](https://github.com/matplotlib/matplotlib/blob/187a88190b48a1e9bb289d55bec7a8a954b552a7/lib/matplotlib/backend_bases.py#L3010).  (Initially, I wanted to replace some uses of `min(max(...` by `np.clip`).

See also https://gitter.im/matplotlib/matplotlib?at=5831157a238757566ccb3580

**Comment by samsontmr** [comment]
Hi I'm new to matplotlib and would like to contribute! Can I try this?
