### ISSUE TITLE
set_xlim in 3D scatter plots?

### ISSUE THREAD

**Issue by sb2nov** [matplotlib/matplotlib#749]
While plotting a 3D scatter plot, if you set axis limits to be lesser than the the maximum range of the array.
The array values are plotted outside the axis area.

In the 2D equivalent, those values are ignored. 

if x = [1, 2, 3, 4, 5, 6 ,7]
then ax.set_xlim(2, 6)

this still plots the 1 and 7 value.

**Comment by ajdroid** [comment]
Has anything changed, wrt this?
