### ISSUE TITLE
overhaul external process calls in TexManager

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7490]
We see frequent transient failures for the `TexManager` in travis and http://stackoverflow.com/questions/40695296/strange-crash-after-saving-many-colormeshplots-using-matplotlib

I _suspect_ what is going on here is that there is a race condition around the various system calls we are making.   We capture the stdout from the various tex related processes, but do not caputer stderr (which I hope will have useful debugging information).   We are using the (old) method of `os.system`.  The suggested way to do this is now the `subprocess` module (https://www.python.org/dev/peps/pep-0324/).   See https://docs.python.org/2/library/subprocess.html#replacing-os-system for comments on how to convert from `os.system`.

The specific tasks for this issue:

 - [ ] move from `os.system` to `subprocess.call`
 - [ ] capture stderr and include in exceptions

Tagging this as 'medium' difficulty because it is touching a rarely touched part of the code base and may require a good understanding of how subprocess calls work in python, but as new-contributor-friendly because it is a self-contained project on a relatively well tested set of functionality.

**Comment by dianarg** [comment]
Hi, is anyone working on this? If it's alright, I can try working on it.

**Comment by QuLogic** [comment]
@tomspur has some initial work in #7572.

**Comment by QuLogic** [comment]
Fixed by #7572.
