### ISSUE TITLE
sort out if the high-resolution ellipse code still works

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7491]
I am not sure that the code at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/patches.py#L1693 still does what it should do

Code originally went in via 7a82ea8112b0767f73a118ddfe0b5938c8dc287c

```python
        for theta in thetas:
            if inside:
                self._path = Path.arc(last_theta, theta, 8)
                Patch.draw(self, renderer)
                inside = False
            else:
                inside = True
            last_theta = theta
```

was changed via b7479ef74f25e5824affde59d2a094311f9b95d1 to

```python
        for theta in thetas:
            if inside:
                _path = Path.arc(last_theta, theta, 8)
                Patch.draw(self, renderer)
                inside = False
            else:
                inside = True
            last_theta = theta
```

and changed via 1938b446f501553ed86bbcf63513761837221d08 to

```python
        for theta in thetas:
            if inside:
                Path.arc(last_theta, theta, 8)
                Patch.draw(self, renderer)
                inside = False
            else:
                inside = True
            last_theta = theta
```

attn @mdboom

**Comment by dopplershift** [comment]
Wow. Seems like either it's wrong or doing unnecessary work.

**Comment by Kojoley** [comment]
I am getting the same output by comparing the outputs of:

  - reverting `self._path = Path.arc(last_theta, theta, 8)`
  - completely replace the whole `draw` body with `return Patch.draw(self, renderer)`.

What should happen if both width and height are lager than `inv_error`?

**Comment by tacaswell** [comment]
This code is now https://github.com/matplotlib/matplotlib/blob/5e046f72ae82788788c7e9b9354b87b131891cd8/lib/matplotlib/patches.py#L1728-L1739 and I think it is correct (if we have triggered this code path then we can only have one part of the arc going through the view box.
