### ISSUE TITLE
axes.cla() in mplot3d - grid lines don't fall back.

### ISSUE THREAD

**Issue by sb2nov** [matplotlib/matplotlib#750]
Once you do a axes.cla(), the grid lines do not fall back.

set_axisbelow() does not work and neither does resetting the grid function.

**Comment by WeatherGod** [comment]
This problem appears to have been fixed in #4553. I just tried the example and I didn't see any issues. Closing.

**Comment by rush719** [comment]
I think this is related: impossible to hide the axes after clearing the plot and plotting new data (matplotlib==1.4.3). Example code:

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x = np.random.rand(100,100)
y = np.random.rand(100,100)
z = np.random.rand(100,100)
ax.plot_surface(x, y, z)
ax.set_axis_off()

ax.clear()

x = np.random.rand(10,10)
y = np.random.rand(10,10)
z = np.random.rand(10,10)
ax.plot_surface(x, y, z)
ax.set_axis_off()

plt.show()

**Comment by WeatherGod** [comment]
This issue was fixed for v1.5.x. I just tried your example, and the axes are not displayed (as expected).

**Comment by rush719** [comment]
thanks, I didn't realize that I am using an outdated version
