### ISSUE TITLE
Rely on Sphinx' "any" role to make docstrings more legible

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7502]
Sphinx >=1.3 has the "any" role (http://www.sphinx-doc.org/en/1.4.8/markup/inline.html#role-any) which allows one to write e.g.
```
`Axes`
```
instead of
```
:class:`Axes`
```
and will automatically figure out the proper markup role (and warn if there is an ambiguity).

This would make non-rendered docstrings quite more readable.

**Comment by QuLogic** [comment]
Doc's current requirements are sphinx>1.0, so that will need updating.

**Comment by tacaswell** [comment]
Doesn't that cause there to be a tremendous number of warning again?

Also :+1: to bumping the minimal version of sphinx.

**Comment by jklymak** [comment]
This happens now, so I am closing.  If I've misunderstood, please re-open....

**Comment by timhoffm** [comment]
Note: we are using the "obj" role, not the "any" role right now. But that is equally good for the above purpose. IMO closing is fine.
