### ISSUE TITLE
Default color cycler for plots should have more than 8 colors

### ISSUE THREAD

**Issue by Naereen** [matplotlib/matplotlib#7505]
Could we try to **increase the number of cycling colors**, i.e., the length of the default [color cycler](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L2592) used in all the 2D plots (`pyplot.plot`, `pyplot.pie` etc) ?

## Why just 7 colors?
It feels weird to have only 7 colors (= `b` `g` `r` `c` `m` `y` `k`), and then cycle back. In practice, 7 is a small number of graphs... and it could easily be larger.

## Proposal
Their is many lists of nice and distinguishable colors (e.g. [the one from XKCD](https://xkcd.com/color/rgb/)), so the default could color cycler could easily be extended to, let say, 24 colors instead of 7.

Does any one agree with the proposal ?

If I am pointed out where exactly should I make my change[^1] I will do it and propose a pull request. Thanks in advance :smiley:!
[^1]: I didn't really understood [this part](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L2592) - can't figure where the default color cycler is defined

## Example of this problem
When doing some basic plotting with a dozen of curves, it's impossible to distinguish the first ones and the last ones, if using the default settings: (in the example below, curves `i` and `i + 7` has the same colors)
![not_enough_cycling_colors](https://cloud.githubusercontent.com/assets/11994719/20583027/c5aa893a-b1e6-11e6-895d-8f31e02b4141.png)

And it's not trivial to easily define either more colors, or a generic way to get enough different colors (one for each plot) that are both well readable (no light gray) and different enough to be distinguished. (e.g., [this lame try](https://github.com/Naereen/AlgoBandits/commit/d349c69b054065ecce86b137056fcdacd5a153ad#commitcomment-19945885)).

**Comment by efiring** [comment]
In version 2.0 (coming soon...) the default color cycle will have 10 colors, and you can always make a cycle with any set of colors you like.  Note, however, that in most cases trying to distinguish a large number of curves based on a large number of colors will not work well in conveying information to the viewer of the plot.  Instead, if you can't reduce the number of curves, you can use a combination of colors, line styles, and line widths.  For a preview, see http://matplotlib.org/devdocs/examples/color/color_cycle_demo.html and http://matplotlib.org/devdocs/examples/color/color_cycle_default.html.

**Comment by Naereen** [comment]
Is it only defined in the user `.rc` setting file? ([as in this example](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/stylelib/classic.mplstyle#L216))

If true, does anyone has an objection to increase the default value (`cycler('color', 'bgrcmyk')`) to something with simply *more colors* ?

Example with 24 colors:
```python
axes.prop_cycle : cycler('color', ['blue', 'green', 'red', 'cyan', 'magenta', 'yellow', 'black', 'purple', 'pink', 'brown', 'orange', 'teal', 'coral', 'lightblue', 'lime', 'lavender', 'turquoise', 'darkgreen', 'tan', 'salmon', 'gold', 'lightpurple', 'darkred', 'darkblue'])
```

**Comment by tacaswell** [comment]
@Naereen Going above 10 also breaks the new `'CN'` color notation.

Nothing is stopping you from doing this in your rc file, by setting `mpl.rcParams['axes.prop_cycle']`, or creating your own style sheet, but I do not think the 'default' we ship with is going to go above 10 (and probably will not use `cyan` or `yellow` due to the difficulty in seeing them against white backgrounds). 

An interesting problem I heard about a few days ago is how to choose successive colors that are maximally seperated from the existing colors (look at colorspacious, pick a fixed lightness plane and then fill it via some algorithm).
