### ISSUE TITLE
Legend not displayed

### ISSUE THREAD

**Issue by priyambial123** [matplotlib/matplotlib#7508]
Hi,
   I am using Python 2.7 in Enthought Canopy environment (Version: 1.7.4.3348 (64 bit)). I have installed Matplot lib (version 1.5-1.8) from package manager in Canopy.I have installed all these packages in RedHat Linux system. 

I am not able display the legend when I run the  Python script (attached as text file). I get this message: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x7f6312630d50>] instances.
A proxy artist may be used instead.

It will of great help, if someone can help me to fix this problem.
[migration-plot.txt](https://github.com/matplotlib/matplotlib/files/611303/migration-plot.txt)

Thank you

Regards
Priya

**Comment by Kojoley** [comment]
```python
    ps = [ plot( Migration1, 'bo-' ), plot( Migration2, 'ro-' ), plot( DISC, 'b^-' ), plot( DISC2, 'r^-' ) ]
    legend( ps, 'Migration DISC1'.split() , loc='lower left' )
```
`plot` call returns a list, so `ps` is a list of lists and this is the problem. Solution for you is to flatten `ps`.
