### ISSUE TITLE
Cannot Disable TkAgg Backend

### ISSUE THREAD

**Issue by git-blame** [matplotlib/matplotlib#7526]
### Setup: 
Matplotlib version 1.5.3 on FreeBSD 11 installed with pip

### Problem:
I want to use matplotlib with only non-GUI backend AGG but it always installs with at least tkagg. This leads to problems when matplotlib cannot import *_tkinter*. I have created my own *setup.cfg* file and explicitly disabled all GUI backends including *tkagg* but matplotlib will still install tkagg. Note that the matplotlib setup.cfg documentation states that all GUI backends can be turned off.
```
env MPLSETUPCFG=./setup.cfg pip install matplotlib
...
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [skipping due to configuration]
                    qt5agg: no  [skipping due to configuration]
                    qt4agg: no  [skipping due to configuration]
                   gtk3agg: no  [skipping due to configuration]
                 gtk3cairo: no  [skipping due to configuration]
                    gtkagg: no  [skipping due to configuration]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [skipping due to configuration]
                       gtk: no  [skipping due to configuration]
                       agg: yes [installing]
                     cairo: no  [skipping due to configuration]
                 windowing: no  [skipping due to configuration]
```

### Workaround:
Explicitly specify `matplotlib.use("Agg")` in code.

### Root Cause?
In file `setupext.py`, the subclass _BackendTkAgg_ overrides the  _check()_ method. This means tkagg never checks the configuration file (this behaviour is normally inherited from the original _check()_). Note the other GUI backend classes implement the _check_requirements()_ method.
```javascript
class BackendTkAgg(OptionalBackendPackage):
    name = "tkagg"
    force = True

    def check(self):
        return "installing; run-time loading from Python Tcl / Tk"
```
Is this a bug or is tkagg a required dependency?

**Comment by efiring** [comment]
Related to #7512, which reports that _tkinter is being imported even when the pyplot import is preceded by `matplotlib.use('pdf')`.

**Comment by efiring** [comment]
Tk is not required.  Having the tkagg backend available should be harmless.  The _tkinter import should only occur if the tkagg backend has been chosen.  Are you using a sequence like
```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```
or setting the backend to agg in a matplotlibrc file?  If so, it should not be necessary to disable the tkagg build.

**Comment by git-blame** [comment]
Yes, that's the workaround I'm using. OK, the tkagg backend class has the `force = True` set similar to the `Agg` backend class. So it really isn't an optional dependency.

**Comment by git-blame** [comment]
During pip install such as `env MPLSETUPCFG=./setup.cfg pip install matplotlib` if I include the following options in _setup.cfg_:
```cfg
[rc_options]
backend = Agg
```
then matplotlib will install with Agg as the default without me having to use `matplotlib.use('agg')` or edit the rc file.

**Comment by matthew-brett** [comment]
So - the `python-tkinter` package is an optional dependency, in the sense that matplotlib does not need it, either to build, or to run.   That is because it is using its own copies of the tk headers, and linking to the tkinter library at run time.   So your issue here is that matplotlib is using tkagg as the default backend, even if the system does not have tkinter installed.

Eric - do you happen to know where the default backend is chosen?  How about some logic there to disable the tkagg backend when no tkinter is present?

**Comment by efiring** [comment]
In setup.py:
```
    195             else:
    196                 good_packages.append(package)
    197                 if isinstance(package, setupext.OptionalBackendPackage):
    198                     if default_backend is None:
    199                         default_backend = package.name
```
I think the thing to do would be to add an attribute to the package when it is created in `setupext`, that could be checked here to find out whether the required gui library is present on the system.

**Comment by matthew-brett** [comment]
Hum - what about wheels?    We might build a wheel on a system with tkinter, but then import that wheel on a system without.    That makes me think that we need a run-time check for the default backend.

**Comment by efiring** [comment]
That starts to get complicated, if you mean that if the default backend doesn't run we would have a list of backends to try.  It's trying to get too clever and magical, to do to much behind the user's back.

Maybe the solution is just to provide a more informative message if the tkinter import fails: "Your default backend is tkagg, based on the matplotlibrc file in ..., but the tkinter library is not installed.  You may install the library, or you might want to change the default backend in ... See http://matplotlib.org/.../... for more information."

**Comment by efiring** [comment]
We could also have a script or other "help" mechanism that gathers and displays information about which backends are likely to be functional, which is the default, and where that is specified.

**Comment by matthew-brett** [comment]
Those would all help - but it seems a shame to, by default, import a backend that we know will crash.   I suspect this will become a major pain point, given that we've already had a couple of people reporting this.

**Comment by matthew-brett** [comment]
I can see that we do want to crash if the user has explicitly selected a backend that does not exist, but the logic would be for the case where matplotlib is guessing the backend.   At the moment, it guesses at build time, but now we're in the world where the user is likely to be running the code on a different machine from the one the code was built on, that makes a lot less sense.  So I think the guess logic needs to go somewhere at run time rather than at build time.

**Comment by efiring** [comment]
OK, so the default matplotlibrc file could have `backend : auto`, which would trigger the search.

**Comment by matthew-brett** [comment]
That's a nice solution.   It does mean that the default backend can change after the user installs new packages - like tkinter.  I guess that is a change in behavior and might be surprising.

**Comment by tacaswell** [comment]
@ngoldbaum has similar issues (but more related to there being no running X on headless servers).

I share @efiring 's concern about this getting too magical.  Historically, many of these decisions have been made by the down-stream packagers (which may have install-time scripts that can make decisions about what other packages it knows are installed).

There is a tension here between 'doing the right thing' for a desktop user that uses `pip` and people running headless on servers (vs how much complexity we will take on) and I think we should be biased towards the desktop users 

I suspect that we need to move http://matplotlib.org/faq/usage_faq.html#what-is-a-backend to someplace more prominent.

It looks like forcing `TkAgg` to build is very recent (0c2c5a000c4a35509504fc679beaffb50b3b0280 from @matthew-brett ), I think it makes sense to revert that (and to force the building of TkAgg for wheels).

**Comment by matthew-brett** [comment]
It makes sense to force *building* of TkAgg because we can always build TkAgg - it does not need tkinter installed to build.   The confusion arises because so far setup.py assumes that, if an extension can be built, it can be used.  Here's a suggestion to remove that confusion:

https://github.com/matplotlib/matplotlib/pull/7530

**Comment by matthew-brett** [comment]
@git-blame - can you confirm that current git master does what you want (now #7530 is merged)?

**Comment by git-blame** [comment]
@matthew-brett OK, master works for me. After installation when I use `import matplotlib.pyplot as plt` in my code, it does not complain about *_tkinter*.
