### ISSUE TITLE
nbagg doesn't change figure's facecolor

### ISSUE THREAD

**Issue by dinya** [matplotlib/matplotlib#7534]
```python
%matplotlib nbagg

import matplotlib.pyplot as plt

fig = plt.figure()
fig.set_facecolor('yellow')

ax1 = fig.add_subplot(1,1,1)

ax1.plot([1,2,3], [1,2,3], "b-")
plt.show()
```

figure facecolor is still white.

But ngagg works fine with
```python
%matplotlib inline
```

See also #5317.

I use (installed with conda):

<details>

python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 37 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

numpy: 1.11.2
IPython: 5.1.0
matplotlib: 1.5.3

</details>

**Comment by QuLogic** [comment]
Like it says in the ticket you linked, you need to set `nbagg.transparent` to `False` or the figure will be transparent:
```python
%matplotlib nbagg

import matplotlib.pyplot as plt
plt.rc('nbagg', transparent=False)

fig = plt.figure()
fig.set_facecolor('yellow')

ax1 = fig.add_subplot(1,1,1)

ax1.plot([1,2,3], [1,2,3], "b-")
plt.show()
```

**Comment by dinya** [comment]
@QuLogic, Many thanks!

**Comment by dinya** [comment]
@QuLogic, Many thanks!

**Comment by dinya** [comment]
@QuLogic, Many thanks!
