### ISSUE TITLE
Conflict between different AGG static libraries in a same binary

### ISSUE THREAD

**Issue by bartoli** [matplotlib/matplotlib#7537]
The binary of my project ends up needing two conflicting versions of statically linked AGG in process memory. In my case the conflict is with the Agg 2.4 modified for mapnik, and statically linked in libmapnik.so.
libmapnik.so happens to be loaded first, so when matplotlib is imported from python code, the agg symbols that have the same signature in mapnik are loaded from mapnik. This causes the use of conflicting code ( it seems inline code of matplotlib's agg linked in the backend loads non-inline code of mapnik's agg). Which result in a crash. 
Crashing call stack for me : 
`0  0x00007f6fb677676c in free () from /lib64/libc.so.6
#1  0x00007f6fbaf79102 in delete_replacement (p=0x2000, isArray=false) at basic/GbbMemTracer.cpp:115
#2  0x000000000040fa36 in operator delete (p=0x2000) at ../include/basic/basic/GbbMemTracer.hpp:32
#3  0x00007f6fbaf790ea in delete_replacement (p=0x2000, isArray=true) at basic/GbbMemTracer.cpp:113
#4  0x00007f6fbb562940 in operator delete[] (p=0x2000) at ../../include/basic/basic/GbbMemTracer.hpp:33
#5  0x00007f6fab787361 in agg::pod_allocator<agg::cell_aa*>::deallocate (ptr=0x2000)
    at deps/agg/include/agg_basics.h:41
#6  0x00007f6fab78cc8c in agg::rasterizer_cells_aa<agg::cell_aa>::allocate_block (this=0x516d470)
    at deps/agg/include/agg_rasterizer_cells_aa.h:487
#7  0x00007f6fab78b8e1 in agg::rasterizer_cells_aa<agg::cell_aa>::add_curr_cell (this=0x516d470)
    at deps/agg/include/agg_rasterizer_cells_aa.h:188
#8  0x00007f6fab78b5dc in agg::rasterizer_cells_aa<agg::cell_aa>::set_curr_cell (this=0x516d470, x=640, y=478)
    at deps/agg/include/agg_rasterizer_cells_aa.h:201
#9  0x00007f6fab789dee in agg::rasterizer_cells_aa<agg::cell_aa>::line (this=0x516d470, x1=163840, y1=122880,
    x2=163840, y2=0) at deps/agg/include/agg_rasterizer_cells_aa.h:402
#10 0x00007f6f847db6d7 in line_clip_y<agg::rasterizer_cells_aa<agg::cell_aa> > (this=0x516d470, x=640, y=0)
    at extern/agg24-svn/include/agg_rasterizer_sl_clip.h:157
#11 line_to<agg::rasterizer_cells_aa<agg::cell_aa> > (this=0x516d470, x=640, y=0)
    at extern/agg24-svn/include/agg_rasterizer_sl_clip.h:228
#12 agg::rasterizer_scanline_aa<agg::rasterizer_sl_clip<agg::ras_conv_dbl> >::line_to_d (this=0x516d470,
    x=640, y=0) at extern/agg24-svn/include/agg_rasterizer_scanline_aa.h:374
#13 0x00007f6f847de59d in agg::rasterizer_scanline_aa<agg::rasterizer_sl_clip<agg::ras_conv_dbl> >::add_vertex
    (this=Unhandled dwarf expression opcode 0xf3
) at extern/agg24-svn/include/agg_rasterizer_scanline_aa.h:391
#14 0x00007f6f847f9347 in add_path<Sketch<agg::conv_curve<PathSimplifier<PathSnapper<PathClipper<PathNanRemover<agg::conv_transform<py::PathIterator> > > > > > > > (this=0x516d2e0, path=..., has_clippath=Unhandled dwarf expression opcode 0xf3
)
    at extern/agg24-svn/include/agg_rasterizer_scanline_aa.h:169
#15 RendererAgg::_draw_path<Sketch<agg::conv_curve<PathSimplifier<PathSnapper<PathClipper<PathNanRemover<agg::conv_transform<py::PathIterator> > > > > > > > (this=0x516d2e0, path=..., has_clippath=Unhandled dwarf expression opcode 0xf3
)
    at src/_backend_agg.h:323
#16 0x00007f6f847e44f5 in draw_path<py::PathIterator> (self=Unhandled dwarf expression opcode 0xf3
) at src/_backend_agg.h:497
#17 PyRendererAgg_draw_path (self=Unhandled dwarf expression opcode 0xf3
) at src/_backend_agg_wrapper.cpp:215
`
`deps/agg/*` are the agg symbols in libmapnik. `extern/agg24-svn/*`are the AGG symbols linked in MPL

MPL can work properly if i use LD_PRELOAD to load mpl's agg first, but then i assume i will later have crashes in mapnik when it will use MPL's agg for the same reasons.
I assume similar issues could arise even if something else in the process uses the standard unmodified agg, since MPL's agg is modified too (and the other agg could have been built with different build options).

Both mpl-agg and mapnik-agg have some custom fixes, so i can't simply link both with a single of both.

Proposed solution :
I ended up renaming the agg namespace in matplotlib sources to something else (agg_mpl). 
I used the command `sed -e "s/agg::/agg_mpl::/g" -e "s/namespace agg/namespace agg_mpl/g" -i extern/agg24-svn/{include/*.h,include/*/*.h,src/*.cpp} src/*.{h,cpp}` in the sources root
Now i don't get any issues since no symbols can be confused with symbols of an other AGG.

Since the shipped AGG is already customized and there is no possibility to link an other AGG, could such namespace rename be integrated directly in the project, so that such conflict can not happen again for anyone anymore?

**Comment by tacaswell** [comment]
attn @mdboom

**Comment by tacaswell** [comment]
@bartoli Is there a companion tracking issue on mapnik (if not can you make one?).

It seems like the two projects should be collaborating on this.

**Comment by bartoli** [comment]
I created https://github.com/mapnik/mapnik/issues/3565 on mapnik side

**Comment by tacaswell** [comment]
Thanks! 

Sorry for the redundant comment (I had a very old tab open with a half typed out message and after I finished it and hit enter I saw you had already creating the mapnik issue).

**Comment by anntzer** [comment]
Unless we go the route of sharing(!) a single shared library with mapnik, I think a simple solution is to rename the agg namespace to (e.g.) mplagg (given that we're using a patched agg anyways...), which can be done by a simple sed invocation...

**Comment by tacaswell** [comment]
@bartoli it is not intentional policy that we can not use external Agg builds, but do need to push our changes upstream.  

If there is another 2.x series release of Agg (with a BSD-like license) we will happily change the build system to allow it's use.

**Comment by anntzer** [comment]
I would support just renaming the agg namespace on our side as a stopgap solution...

**Comment by tacaswell** [comment]
I am strongly :-1: on renaming the agg namespace.

**Comment by anntzer** [comment]
@tacaswell Are you still opposed to renaming the namespace?  If so, should this just be closed as "wontfix"?
