### ISSUE TITLE
automatic papersize selection by ps backend is almost certainly broken

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7551]
No minimal example, but the relevant chunk (`backend_ps.py`) is
```python
papersize = {'letter': (8.5,11),
             'legal': (8.5,14),
             'ledger': (11,17),
             'a0': (33.11,46.81),
             'a1': (23.39,33.11),
             <elided>
             'a10': (1.02,1.457),
             'b0': (40.55,57.32),
             'b1': (28.66,40.55),
             <elided>
             'b10': (1.26,1.76)}

def _get_papertype(w, h):
    keys = list(six.iterkeys(papersize))
    keys.sort()
    keys.reverse()
    for key in keys:
        if key.startswith('l'): continue
        pw, ph = papersize[key]
        if (w < pw) and (h < ph): return key
    else:
        return 'a0'
```

Note that the sorting is by name, which means that the size is the first one among "a9, a8, ..., a2, a10, a1, b9, b8, ..., b2, b10, b1" (in that order) that is larger than the requested size -- which makes no sense.

**Comment by oscargus** [comment]
Currently the code looks like:
https://github.com/matplotlib/matplotlib/blob/9caa261595267001d75334a00698da500b0e4eef/lib/matplotlib/backends/backend_ps.py#L80-L85
so slightly different sorting. I guess that
`sorted(papersize.items(), key=lambda v: v[1])` will be better as it gives:
```
{'a10': (1.02, 1.46),
 'b10': (1.26, 1.76),
 'a9': (1.46, 2.05),
 'b9': (1.76, 2.51),
 'a8': (2.05, 2.91),
 'b8': (2.51, 3.58),
 'a7': (2.91, 4.13),
 'b7': (3.58, 5.04),
 'a6': (4.13, 5.83),
 'b6': (5.04, 7.16),
 'a5': (5.83, 8.27),
 'b5': (7.16, 10.11),
 'a4': (8.27, 11.69),
 'letter': (8.5, 11),
 'legal': (8.5, 14),
 'b4': (10.11, 14.33),
 'ledger': (11, 17),
 'a3': (11.69, 16.54),
 'b3': (14.33, 20.27),
 'a2': (16.54, 23.39),
 'b2': (20.27, 28.66),
 'a1': (23.39, 33.11),
 'b1': (28.66, 40.55),
 'a0': (33.11, 46.81),
 'b0': (40.55, 57.32)}
```

**Comment by oscargus** [comment]
Based on the discussions in #22796 this is very hard to fix in a back compatible way. (But easy to fix as such.)

There were some discussions if we actually require ps, as most people probably use eps anyway. One solution is to introduce a pending deprecation for ps and see the reactions?

**Comment by anntzer** [comment]
My preference would be to completely deprecate and then drop papersize, and make ps output at the size of the figure, like all other backends.  We *could* (if there's really demand for it) additionally support `figsize="a4"` (and similar), auto-translating these to the corresponding inches sizes (this would not be equivalent to papersize, as the axes would default to spanning the entire papersize minus the paddings).

**Comment by tacaswell** [comment]
Talked about this on the call, the consensus was to remove the "auto" feature.
