### ISSUE TITLE
frange returns a last value greater than limit

### ISSUE THREAD

**Issue by gabrielfedel** [matplotlib/matplotlib#7553]
-Matplotlib 1.4.2, Python 3.4, Linux
-Matplot installed with pip

-Example problem:
frange(1,10,3.5)
array([  1. ,   4.5,   8. ,  11.5])

**Comment by jenshnielsen** [comment]
It's not really documented very well but it's clearly on purpose as looking at the code shows

```
    # compute # of points, spacing and return final list
    try:
        npts = kw['npts']
        delta = (xfin-xini)/float(npts-endpoint)
    except KeyError:
        npts = int(round((xfin-xini)/delta)) + endpoint
        # round finds the nearest, so the endpoint can be up to
        # delta/2 larger than xfin.
```

**Comment by efiring** [comment]
`frange` is left over from 2004, the earliest days of mpl development, and is not presently used anywhere in mpl.  It doesn't belong in mpl any more, and probably should be deprecated.  We have had some maintenance cycles removing things like this before; I don't know why `frange` has survived.  It's not even needed for matlab compatibility.
