### ISSUE TITLE
TeX formula rendering broken

### ISSUE THREAD

**Issue by raphaelm** [matplotlib/matplotlib#7554]
Hi,

a friend of mine has rendering issues with TeX rendering. When she tries to executes the scripts that run fine on my machine, she gets output like this:

![graph_10](https://cloud.githubusercontent.com/assets/64280/20837635/351995a8-b8a5-11e6-8cb5-fd6af8f420ae.png)

The correct output, that is reproducible on my machine, is:

![download 1](https://cloud.githubusercontent.com/assets/64280/20837714/89762332-b8a5-11e6-9a00-dadd3f5af473.png)

This happens for *any* plot that uses TeX rendering, both in labels and in plot titles. It also happens both in Jupyter notebook *and* in command-line scripts, as well as in PNG and SVG output files.

The presented picture is generated by the Jupyter notebook that I uploaded here:
[HTML export](https://www.raphaelmichel.de/tmp/V241.html)
[.ipynb file](https://www.raphaelmichel.de/tmp/V241.ipynb)

Her setup:
- Debian testing with recent updates
- Matplotlib version 1.5.3 from Debian package repositories
- Python 3 from Debian package repositories
- All texlive packages suggested by Debian's matplotlib package installed and recent

My setup:
- Arch Linux with recent updates
- Matplotlib version 1.4.3
- Python 3.5.2

Do you have any idea what the reason could be? We tried all applicable tips from http://matplotlib.org/users/usetex.html Is there any more useful information that we can provide or any good place to look?

Thanks!

**Comment by tacaswell** [comment]
This is probably yet another instance of the lynx fonts https://github.com/matplotlib/matplotlib/issues/6976 issue.

**Comment by raphaelm** [comment]
Yep, thanks!
