### ISSUE TITLE
Deprecation needed for `frange` and others?

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7555]
`mlab.frange` is not used anywhere in mpl and is not needed for matlab compatibility, so probably it should be deprecated and eventually removed.  There might be other `mlab` functions in the same category.

**Comment by anntzer** [comment]
fwiw see discussion at https://github.com/matplotlib/matplotlib/pull/6577#issue-159871923 (I'm all for it).

**Comment by anntzer** [comment]
@efiring Would you support a complete deprecation of mlab in 2.1?

**Comment by tacaswell** [comment]
For these very old tools that we would like to get rid of I suggest deprecating for removal in 3.0.

When we drop py2 support, that is going to be coupled with a major version bump so this will happen in 2018(ish).

**Comment by efiring** [comment]
We are using a few of them in our examples (e.g. the bivariate normal), and even some in our modules (especially contour--to my surprise).  We could move what we need to cbook; some of the things I see in our modules are well within the scope of cbook.

**Comment by QuLogic** [comment]
Is enough of this done in #9151 to close this?

**Comment by anntzer** [comment]
I'm going to assume #9151 was indeed enough, feel free to reopen if there's more to deprecate (or directly open a PR).
