### ISSUE TITLE
document when derived values (ex tick locations and labels) are computed

### ISSUE THREAD

**Issue by godaygo** [matplotlib/matplotlib#7556]
I certainly do not know, but I it seems that this behavior is very strange. `plt.xticks` does not accept labels which they return as arguments. As a simple example of this odd behavior:

```
x = np.arange(0,10)

plt.plot(x,x)
locs, labs = plt.xticks()
plt.xticks(locs[1:], labs[1:])
plt.show()
```
![figure_1-1](https://cloud.githubusercontent.com/assets/20781495/20849756/2f09f6be-b8e9-11e6-8a77-2849695c4108.png)

matplotlib 1.5.3
python 3.5.2
win 10

**Comment by dstansby** [comment]
Printing out your labels, it seems like they're just all empty strings, which might be why they're not showing up:
```
>>> for lab in labs:
...     print(lab)
... 
Text(0,0,'')
Text(2,0,'')
Text(4,0,'')
Text(6,0,'')
Text(8,0,'')
Text(10,0,'')
Text(0,0,'')
```

**Comment by tacaswell** [comment]
This most likely due to the tick labels being determined at draw time and you are asking for the labels before the figure has been drawn for the first time.

We have been systematically been making the library lazier and discovering that people have been relying on some of these details.

@godaygo what are you trying to do?

**Comment by godaygo** [comment]
@tacaswell Thank you for your insight. I was trying to set tick labels from one graph to another, because I think that labels are determined after I call `plt.plot`. I don't know matplotlib well as you see (and if it's a way of implementation it's ok), and maybe I harried with the issue. Sorry for that! 

p.s.: Also I didn't find any docs about matplotlib execution model (only some topics about `zorder` and etc) that is why this behavior wasn't obvious to me.

**Comment by tacaswell** [comment]
I suggest you send a question to the mailing list with your application.

If the two axes are in the same figure you can do something like

```python
fig, (ax1, ax2) = plt.subplots(1, 2, sharex='all')
```

**Comment by QuLogic** [comment]
This is now done whenever asked by #23170, so there is no longer the inconsistency that appears to happen as originally reported.
