### ISSUE TITLE
QPixmap: It is not safe to use pixmaps outside the GUI thread

### ISSUE THREAD

**Issue by senyai** [matplotlib/matplotlib#757]
Hi!

   I'm using Matplotlib 1.1.0 and PyQt4: 4.9.1 under WinXP. My idea is to generate image inside QThread and save it to a file without any gui interaction. It works fine, but I see about 30 warnings "QPixmap: It is not safe to use pixmaps outside the GUI thread". I looked at code and found that only two lines causes it: self.window.setWindowIcon(QtGui.QIcon(image)) and self.toolbar = self._get_toolbar(self.canvas, self.window) in backend_qt4.py. I think these methods should not be called before window is shown.
Code in my thread is simple:

```
from matplotlib import pyplot
fig = pyplot.figure(figsize=(6, 3))
```

Thank you!

**Comment by meawoppl** [comment]
I had this problem in a fairly recent matplotlib instance.  In my application I can't be sure if the figure is going to be saved or displayed before just a little before the plotting commands.  Is this a problem that is limited to the QT backend?  Win7 Py3.4

**Comment by tacaswell** [comment]
You can delay creating the cavas until just before draw time.

**Comment by meawoppl** [comment]
This seems a bit counterintuitive that certain backends should require different practices.  Is there a drawback to the approach suggested by @senyai?  I can flog it through the testing and open a PR if that helps.

**Comment by 1788** [comment]
I am using matplotlib for the following task:-

img4 = cv2.drawKeypoints(img1, kp1, outImage=None)
img5 = cv2.drawKeypoints(img2, kp2, outImage=None)
f, axarr = plt.subplots(1,2)
axarr[0].imshow(img4)
axarr[1].imshow(img5)
plt.show()

img3 = cv2.drawMatches(img1, kp1, img2, kp2, matches, flags=2, outImg=None)
plt.imshow(img3) 
plt.show()


When I use multithreading I get the error : It is not safe to use pixmaps outside the GUI thread.
