### ISSUE TITLE
Qt Designer plugin

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#758]
Qt designer provides a powerful interface for making Qt GUIs, including python GUIs (PyQt4 and pyside), much more powerful than matlab's GUI designer.  However, it lacks one GUI element that Matlab has: a plot element.  New GUI elements can be added to Qt Designer by means of plugins (pyqwt, which is unfortunately unmaintained, does this).  

Since Matplotlib provides PyQt4 and pyside interfaces, it would be great if it also offered a Qt Designer plugin so matplotlib plots could be easily embedded in PyQt4 or pyside GUIs.  I think python(x,y) has such a plugin that might be used as a basis for an official matplotlib one.

**Comment by tacaswell** [comment]
@hhslepicka  I know you are using qt designer these days, can you provide the right files for this ?

**Comment by timhoffm** [comment]
IMHO this does not fall into the core functionality of Matplotlib. While this could be nice, the use case is rather specialized. How many people are creating Qt GUIs nowadays who would benefit significantly from a plugin vs. adding the canvas by code?

Considering benefit vs effort, I don't think we want to develop and maintain this as part of core Matplotlib. If anybody is interested working on this, I propose to provide this as a third party package.

**Comment by rcomer** [comment]
I note that the OP's account no longer exists...
