### ISSUE TITLE
2.0.0rc1  cannot import name '_macosx' 

### ISSUE THREAD

**Issue by ChristopherShort** [matplotlib/matplotlib#7588]
Python 3.5, OS X

Launch ipython in the terminal, enter:

`import matplotlib.pyplot as plt`

returns

`ImportError: cannot import name '_macosx'`

Much bigger surprise : there is **no error** if I enter the command **via a jupyter notebook**.  And the namespace is loaded in the notebook - i can tab complete `plt.<tab>`

And ` __version__` returns `'2.0.0rc1'` in both terminal and a notebook (I can `import matplotlib` without error in the terminal)

The error definitely didn't occur prior to installing 2.0.0rc1

The trace is

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

/Users/ChristopherShort/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py in <module>()
    113 
    114 from matplotlib.backends import pylab_setup
--> 115 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    116 
    117 _IP_REGISTERED = None

/Users/ChristopherShort/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/Users/ChristopherShort/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_macosx.py in <module>()
     17 
     18 import matplotlib
---> 19 from matplotlib.backends import _macosx
     20 
     21 from .backend_agg import RendererAgg, FigureCanvasAgg

ImportError: cannot import name '_macosx'

```

**Comment by tacaswell** [comment]
If you use one of the other backends (ex 'qt5agg' or 'qt4agg', depending on which version of pyqt you have installed) it should work.  Before you import pyplot type

```python
%matplotlib qt5agg
```
(if that fails try qt4agg)

Did you install this via pip or via conda?  I wonder if these is like the #7579 related issues and a low level version mis-match?

**Comment by tacaswell** [comment]
🐑 I see you are the one who reported #7579 so unlikely that fix will work for you 😜

**Comment by ChristopherShort** [comment]
Switching the `backend` in my matplotlibrc to `tkagg` does **not** generate the error in a straight ipython session in a Terminal window.  

But switching the `backend` back to `macosx` still does (and tried from a clean startup earlier too)

I'm no technical help in figuring out the issue - (happy to test any thoughts/suggestions) but would it be related to the shift in the `macosx backend` being `Agg` based?

As noted above, using `macosx` as the `backend` is not an issue in a jupyter notebook.

Testing matplotlib this morning in a notebook showed everything working great (literally - the new matplotlibrc options are a big boon to me  -  and combined with the new defaults I think the efforts for 2.0 are outstanding).

**Comment by dopplershift** [comment]
If you're using the conda-forge packages for matplotlib 2.0, I don't think the osx backend even builds:

https://github.com/conda-forge/matplotlib-feedstock/blob/devel/recipe/build.sh#L22

Also looks like this is the same as conda-forge/matplotlib-feedstock#44. If indeed that backend isn't part of the package, why is it even trying to load it?

**Comment by WeatherGod** [comment]
could it be a leftover matplotlibrc file with macosx backend configured in
it?

**Comment by ChristopherShort** [comment]
yes - it's the conda forge packages (via  conda install -c conda-forge/label/rc -c conda-forge matplotlib)

yes - it's my matplotlibrc that's calling macosx  via the setting `backend : macosx`

Is that no longer a recommended option?

I have to confess, when I looked at the [backends docs](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend) yesterday, it wasn't clear to me why I would choose one over another.

Indeed, I no longer recall why I changed that setting to macosx (dimly recall something about not having to use `show()` on the mac).

**Comment by WeatherGod** [comment]
The choice of backend is highly dependent upon the user's situation. The
macosx option is still perfectly valid, but the conda version of the
matplotlib package must have left that backend out. We are considering
adding an "auto" option in the future, which should help ease things in the
future. In the meantime, since your install came from conda, try setting it
to "qt4agg".

**Comment by dopplershift** [comment]
It's not just that conda-forge left it out--it's that it won't build on their infrastructure for some reason (I don't know the details).

**Comment by tacaswell** [comment]
Closing as this is a conda forge issue (not an mpl issue).

For those who hit this, I suggest you try the wheel.

**Comment by dopplershift** [comment]
For the record, I have a PR open at conda-forge/matplotlib-feedstock#87 that will re-enable the backend. It's building fine--so hopefully I'll get the last edges of stuff ironed out and we can have acceptable conda-forge packages as well.
