### ISSUE TITLE
Subtick labels are not disabled in classic style

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#7590]
Using this example:
```python
#!/usr/bin/env python3

from distutils.version import LooseVersion

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt


if LooseVersion(mpl.__version__) >= LooseVersion('2.0.0'):
    plt.style.use('classic')

fig, ax = plt.subplots()
ax.semilogy([-1/2, -1], [1, 2], 'k')
ax.set_xlim(-1, 0)
ax.set_ylim(10**0, 10**1)
ax.set_title(mpl.__version__)

plt.show()
```
the result with 1.5.3 is:
![figure_1-1 5 3](https://cloud.githubusercontent.com/assets/302469/20999131/8df33884-bce0-11e6-8434-44146bc2b815.png)
and with 2.0.0rc1:
![figure_1-2 0 0rc1](https://cloud.githubusercontent.com/assets/302469/20999139/951e5698-bce0-11e6-9535-ab84bc10fb27.png)

The subtick labels remain visible even when using the classic style.

**Comment by efiring** [comment]
Increase the y limits ever so slightly, and the labels disappear.  In 1.5.3, the minor tick labels are never shown, which could be viewed as a bug--or at least as a poor design.  
To restore this via classic style we would need an rcParams['axes.formatter.log.minor_thresholds'].  It requires 2 numbers, and the cleanest way to disable the minor tick labeling is to set the first of these numbers to np.inf.  All of this is pretty complicated for an rcParams entry. I suppose that a string could be used for the "disabled" case, which would help a little bit.

**Comment by QuLogic** [comment]
If it's difficult to implement, can we just set `minor_thresholds` to what's required when not specified and `rcParams['_internal.classic_mode']` is on?

**Comment by efiring** [comment]
Good idea.  I can do that tomorrow.

**Comment by efiring** [comment]
This is turned out to be more complicated than I expected; ticking is a rat's nest.
