### ISSUE TITLE
Number of subplots in mpl.axes.Subplot object

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#7591]
From an `mpl.axes.Subplot` `obj`, I can find out information about the grid pattern via
```python
geom = obj \
    .get_subplotspec() \
    .get_topmost_subplotspec()\
    .get_geometry()
```
For example, the product `geom[0] * geom[1]` gives the maximum number of subplots in the grid.

_Q:_ Is there a way for finding out how many subplots there _actually_ are?

**Comment by tacaswell** [comment]
You can look at `fig.axes` which is a list of all axes in the figure.  There are ways to add axes to a figure without using the subplots machinery and arbitrary axes can be removed.

Why do you want this, I assume it is related to `matplotlib2tikz`?  Similar to https://github.com/mpld3/mplexporter , I do not think that manually walking a figure artist tree and special casing on artist type is the best approach, these things are probably better done as a new backend (and if it _can not_ be done as a backend we would be very interested in understanding why).

Are you aware one of the backends mpl ships is a pgf backend?

attn @pwuertz

**Comment by nschloe** [comment]
> it is related to matplotlib2tikz

Indeed.

> and if it can not be done as a backend we would be very interested in understanding why

The format I'm trying to convert to is Pgfplots (not PGF), higher-level than PGF/TikZ itself (matplotlib2tikz is actually a misnomer). If I understand correctly, the backend has access to low-level drawing info, i.e., a line here, a gradient there etc. What I need is information like how many axes there are, what the scaling is, which axes are color bars etc. As of now, I retrieve this info from the plot directly.

**Comment by pwuertz** [comment]
@nschloe 
You require a high level PGF/TikZ representation for human readability, post-processing or manual editing, right? I was in the same situation once, but I missed the more advanced matplotlib features which turned out to be very difficult to convert to high-level code. Emitting low-level drawing commands turned out to be much, much easier.

**Comment by nschloe** [comment]
>You require a high level PGF/TikZ representation for human readability, post-processing or manual editing, right?

Exactly. (I would think the main point here is manual editing after figure creation.)

> Emitting low-level drawing commands turned out to be much, much easier.

Understandable. matplotlib2tikz doesn't work for many complex examples, but it covers much of the basic stuff.
@tacaswell, does this clarify the situation? Again, it'd be lovely if we could turn matplotlib2tikz into a proper backend, but I don't think that's possible atm.
