### ISSUE TITLE
font cache: a possibility to disable building it

### ISSUE THREAD

**Issue by FRidh** [matplotlib/matplotlib#7592]
I'm using matplotlib 1.5.3 on Nix, and for general users it works good. Now, with Nix, we have a tool to build packages in isolation. The builds are run by special users in a clean environment. I've started using Nix for my data analyses and simulations. Unfortunately, whenever a module imports matplotlib, it will rebuild the cache. And it will do this for each step that I build separately.

Ideally a lazy evaluation would be used, i.e., no building of the cache until it is really needed. I guess this isn't implemented. Until then, is there some kind of flag I could set to disable building the cache - or passing it an empty cache?

**Comment by tacaswell** [comment]
The font cache is needed anytime text will be put on a figure (so we can find the fonts to draw it), there is not much way around it.  There is a PR open to suppress the warning if it takes less than 5 seconds to find the fonts.

**Comment by anntzer** [comment]
The warning has been removed (unless fc-list is *extremely* slow) by #7596.
