### ISSUE TITLE
Issue: Applying Axis Limits

### ISSUE THREAD

**Issue by freyalumb** [matplotlib/matplotlib#7593]
Python 2.7, Linux, annaconda3, pyart environment, matplotlib version 1.5.3

Generic Code

```python
import matplotlib.pyplot as plt  
  
fig=plt.figure(figsize=(10,3))  # Width by Height; 

ax = fig.gca()

#variables
zh=[90,10,15,20,30,40,50,60]
zdr=[-10,-20,10,5,2,3,4,8]

ax.scatter(zh,zdr)
ax.axis(0,60,-10,10)

fig.show()
```

Issue: 
```
File "/home/ubo/anaconda3/envs/pyart_env/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1554, in axis
    if len(v) != 4:

TypeError: object of type 'int' has no len()
```

The limits aren't restricted on Graph: 
![image](https://cloud.githubusercontent.com/assets/22682119/21024090/236d571a-bd7b-11e6-96bc-0143818acad6.png)

I have found a temporary work around 
For line 1553 commenting out the v=v[0]
```
#v=v[0] 
        #commented out as v=v[0] would always =1 also if a changing limit set to rule out clutter then you 
```
would still need `v=4` but `v[0]=xmin[:]` instead etc. 
This produces a graph with the limits specified:

![image](https://cloud.githubusercontent.com/assets/22682119/21024282/c86346b2-bd7b-11e6-9647-ee90ec56b234.png)

**Comment by phobson** [comment]
Try passing a list or tuple instead: `ax.axis([0,60,-10,10])`

**Comment by phobson** [comment]
Works as expected with:
`ax.axis([0, 60, -10, 10])`
and
`ax.axis(xmin=0, xmax=60, ymin=-10, ymax=10)`

@freyalumb It'd me much appreciated if you could find time to elaborate on how the docstring was unclear or  could be improved to clarify the API.

Closing this for the time being.
