### ISSUE TITLE
Feature request: add reflection to transforms

### ISSUE THREAD

**Issue by darkdragon-001** [matplotlib/matplotlib#7599]
Please add wrapper methods `reflect_horizontal()`, `reflect_vertical()`, `reflect_origin()` to `matplotlib.transforms.Affine2D`.

You can find the contents of the corresponding matrix for the affine transformation in the following picture: ![overview of affine transformation matrix](https://upload.wikimedia.org/wikipedia/commons/2/2c/2D_affine_transformation_matrix.svg).

**Comment by tacaswell** [comment]
@darkdragon-001 Would you like to take a crack at doing this?

What is the use case for the reflections?

attn @mdboom

**Comment by anntzer** [comment]
reflect_origin is effectively already available as rotation around origin.

**Comment by darkdragon-001** [comment]
@tacaswell I want to create a symmetric figure (4 triangles forming a square). Therefore, I decided to create one part, (shallow) copy the collections (thus reusing the underlying patches) and then transform the copies.

I might have a look at implementing this on my own and sending a push request.

**Comment by anntzer** [comment]
This is just a matter of adding `Affine2D(np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]]))` or `Affine2D(np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]]))` to the current transform.  Unless there is a use case on matplotlib's side, I believe this is better handled by your own custom subclass or free standing functions.

Closing.  Could be reopened with an actual patch and rationale why this is needed in matplotlib itself.

**Comment by darkdragon-001** [comment]
I thought that more wrappers in a library make life easier for users and resulting code more readable. Obviously, this is not wanted by the library maintainers -.-

**Comment by WeatherGod** [comment]
We aren't used to having users of our transforms system outside of mpl. I
am genuinely curious how you are using it. I can be convinced to make it
more user-friendly if users find it useful.

**Comment by darkdragon-001** [comment]
Well, I use it within mpl (= matplotlib?). I create figures and save the images afterwards to use them somewhere else. In order to "draw" vector graphics, something like reflections are heavily used for symmetry reasons.
