### ISSUE TITLE
Feature request: more operations on collections

### ISSUE THREAD

**Issue by darkdragon-001** [matplotlib/matplotlib#7600]
I would like to see more operations for collections:
- Merging / union: optionally overload `+` operator
- Grouping: Group several collections together and apply the same operations (e.g. setting properties, transformations, ...) to all of them

**Comment by phobson** [comment]
Can you provide some examples of what you think the API should look like?

**Comment by phobson** [comment]
Also, some simple examples of how you're currently working around these limitations would be helpful as well.

**Comment by tacaswell** [comment]
Something like https://github.com/matplotlib/matplotlib/pull/3944/files is starting to do?

**Comment by darkdragon-001** [comment]
@phobson I currently work around these issues as follows:
1. Create Polygon for background, set face color, set clip path
2. Create Patches via routine for background, add to Collection, set same face color, set clip same path
3. Create Patches via routine for foreground, add to Collection, set other face color, set clip same path
4. (Shallow) copy **background (1.), collection (2.) and collection (3.)** three times each
5. Apply **same transform to all shapes (foreground, background)** for every copy
6. Set clip path **for all shapes** for every copy
7. Change face color to **distinct colors** for every copy

What I would like to do instead
1. Create Polygon for background
2. Create Patches via routine for background, add to Collection
3. Create Patches via routine for foreground, add to Collection, set other face color
4. **Merge Polygon and Collection** for Background, set same face color
5. **Group collections (3., 4.)**, set clip path
6. (Shallow) copy groups
7. Apply transform for every copy
8. **Invert colors** for every copy

@tacaswell I had a brief look at your pull request and it might fulfill my needs.

Is it possible with such collections to 
1. Have sub collections with different face color?
2. Copy sub-collections to reuse patches?
3. Apply transformation to whole collection?
4. Change the background?
5. Invert colors?
Thus handling those sub collections like distinct images with reusing the same underlying patch data?

**Comment by tacaswell** [comment]
I suspect that you will need to write a new `Artist` class to provide exactly that API.  The `draw` method is where the rubber-hits-the-road going between our internal representation and what gets sent to the renderers (either by deferring to the draw methods of children or by directly calling the reneder methods).  
Would you be interested in working through what this API would look like?  It might be instructive to look at the broadcasting API that bokeh / bqplot expose for this sort of thing.

Why is inverting colors a special operation?

**Comment by darkdragon-001** [comment]
Still an issue

**Comment by jklymak** [comment]
@darkdragon-001 This hasn't gotten traction in 7 years.  I'm going to close but if there is still an argument to keeping it around, feel free to advocate for it.
