### ISSUE TITLE
color_cycle deprecation warning could provide more context to user

### ISSUE THREAD

**Issue by alanbernstein** [matplotlib/matplotlib#7601]
It took me an unfortunately long time to figure out why I was getting this: "UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter."

This warning happens at `import matplotlib.pyplot as plt`, regardless of the remainder of the file. It comes from __init__.py:878, and can, presumably, be for a few different reasons. It turned out I had an old, no longer used, .mplstyle file with a prop_cycle definition. In tracking down the warning, I learned that matplotlib loads all .mplstyle files at import, whereas I assumed it loaded them upon usage. It would be helpful if the warning could somehow point to the style definition that generates it.

OSX 10.11.5
Python 2.7.12 (from `brew install python`)
matplotlib 1.5.3 (from `pip install matplotlib`)

**Comment by alanbernstein** [comment]
I'd be happy to contribute, if someone could suggest the right approach.

**Comment by tacaswell** [comment]
I suggest wrapping https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/style/core.py#L190 with a warning context manager to catch these warnings and print out the additional context of what file is being read.

A PR to add that would be great!

**Comment by dstansby** [comment]
Looks like this is good to be closed.
