### ISSUE TITLE
The best channel to ask questions related to using matplotlib

### ISSUE THREAD

**Issue by wenouyang** [matplotlib/matplotlib#7609]
Dear All,

If I have questions on using matplotlib, what are the best channel to ask questions? Besides stackoverflow, are there any google discussion group dedicated to matplotlib. I know this one is for development-related questions.

Thanks,

**Comment by tacaswell** [comment]
We have 2 relevant mailing lists (matplotlib-users@python.org and matplotlib-devel@python.org you will need to register to post un-moderated) and a gitter room (https://gitter.im/matplotlib/matplotlib)

These are documented at https://github.com/matplotlib/matplotlib#contact and http://matplotlib.org/
