### ISSUE TITLE
make 'dpi' optional for animation.MovieWriter.setup

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7616]
The exact work to do:

 - set the default value of the `dpi` arg for `MovieWriter` and `FileMovieWriter` to `'figure'` to match the way we handle the default dpi for `savefig`
 - add test
 - update docs

**Comment by janismdhanbad** [comment]
I am up for it, if you could guide me a bit more for this issue, I am a beginner in open source contribution.

**Comment by tacaswell** [comment]
See http://matplotlib.org/devdocs/devel/gitwash/development_workflow.html for details on how to get git set up correctly (and please let us know what about that can be made clearer. @NelleV is this even the correct entry point?)

Have a look at http://matplotlib.org/devdocs/api/animation_api.html#writer-classes to see how this setup/saving are used.

See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L2136 for how to normalize the figure dpi consistent with have savefig does it.

Asking questions here or https://gitter.im/matplotlib/matplotlib are both good options to get help.

**Comment by janismdhanbad** [comment]
Just a rookie question, I have figured out the fix but can you please shed some more light on "add test" request in the issue.
Thankyou.

**Comment by WeatherGod** [comment]
We try to add unit tests for every feature we add in order to prevent our
future selves from breaking the feature by accident. We have some
smoke-tests for the animation module at
lib/matplotlib/tests/test_animation.py that could be a starting point. Add
a new test in there.

**Comment by mitko1994** [comment]
I assume this issue has to be closed since the merge above solved the problem, right?

**Comment by QuLogic** [comment]
I think you're right.

**Comment by QuLogic** [comment]
Actually, I don't think the `dpi` argument accepts the string `'figure'` even after that PR; is that still something we want to do, @tacaswell ?
