### ISSUE TITLE
set_ylabel does not work as expected with SubplotZero

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7617]
Discovered as part of #7489

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid.axislines import SubplotZero

fig = plt.figure()
ax = SubplotZero(fig, 111)
_ = fig.add_subplot(ax)


for direction in ["xzero", "yzero"]:
    ax.axis[direction].set_visible(True)
    ax.axis[direction].set_axisline_style("->")
    # Set outward ticks
    ax.axis[direction].major_ticks.set_tick_out(True)
    ax.axis[direction].minor_ticks.set_tick_out(True)

ax.axis["yzero"].set_axis_direction("left")

plt.plot([0,1], [0,1], c="blue", lw=2)
plt.xlabel('x')
plt.ylabel('y')
```

![so](https://cloud.githubusercontent.com/assets/199813/21091564/0dbc6cb6-c015-11e6-9d3e-237939132d0b.png)

**Comment by AndreWin** [comment]
There is workaround from [here](https://github.com/matplotlib/matplotlib/issues/7489#issuecomment-266348745):
```
ax.axis['xzero'].set_label("x")
ax.axis['yzero'].set_label("y")
```

**Comment by jacob-pecile** [comment]
@tacaswell is it only issue that the label on the extra y axis is incorrect, or should the axis of the original Axes be overwritten with the new one created using the AxisArtist. 

Sorry if this is obvious, I'm wondering if the extra set of axes drawn are expected or not

**Comment by tacaswell** [comment]
I am not sure what the 'should' here is.  `plt.ylabel` not working is very surprising, that is definitely a bug. However exactly how `SubplotZero` manages it's internals is not something I have clear in my head.

I would say the two pieces of work here are:

 - make `plt.ylabel` 'do the right thing'
 - make sure that what ever `SubplotZero` is doing is will documented.

**Comment by jacob-pecile** [comment]
Oh okay I see. What I was essentially asking is if the expected result is the same figure in the original post but with a y instead of an x on the y axis, or if there was more to it.

**Comment by tacaswell** [comment]
Yes, I think that is the core of it (`plt.ylabel` should work).
