### ISSUE TITLE
sharex or sharey with aspect=equal affects axis limits

### ISSUE THREAD

**Issue by godaygo** [matplotlib/matplotlib#7621]
When `aspect='equal'` and `sharex`/`sharey` are used together, they affect the axis limits, and I can not precisely set them.

```python
fig = plt.figure()

ax1 = fig.add_subplot(1,2,1)
ax2 = fig.add_subplot(1,2,2, sharey=ax1)

ax1.plot([.1, .5, .9], [.1, .5, .9], 'o')
ax2.plot([.1, .5, .9], [.1, .5, .9], 'o')

ax1.axis([0, 1, 0, 1])
ax2.axis([0, 1, 0, 1])

ax1.set_xticks([0, .2, .4, .6, .8, 1])
ax2.set_xticks([0, .2, .4, .6, .8, 1])

plt.show()
```
![figure_1-by](https://cloud.githubusercontent.com/assets/20781495/21112051/3b67098c-c0b5-11e6-831d-bd264c00f9df.png)

Also `sharex` and `sharey` behaves differently. Above picture was for `sharey`, below is for `sharex`:
![figure_1-bx](https://cloud.githubusercontent.com/assets/20781495/21112112/855245b6-c0b5-11e6-9aab-c8978f67fc2c.png)

When I use one of them everything looks fine, with `aspect=equal`, without  `share`:
```python
fig = plt.figure()

ax1 = fig.add_subplot(1,2,1, aspect='equal')
ax2 = fig.add_subplot(1,2,2, aspect='equal')

ax1.plot([.1, .5, .9], [.1, .5, .9], 'o')
ax2.plot([.1, .5, .9], [.1, .5, .9], 'o')

ax1.axis([0, 1, 0, 1])
ax2.axis([0, 1, 0, 1])

ax1.set_xticks([0, .2, .4, .6, .8, 1])
ax2.set_xticks([0, .2, .4, .6, .8, 1])

plt.show()
```

![figure_1-g](https://cloud.githubusercontent.com/assets/20781495/21112167/c72b85d8-c0b5-11e6-98ca-08a84d5181cf.png)
without `aspect=equal`, with `sharey`:
![figure_gy](https://cloud.githubusercontent.com/assets/20781495/21112204/eb10533e-c0b5-11e6-84bf-0b6861cd1958.png)

Also the trouble is the same for `set_aspect` and `axis('equal')`.

matplotlib 1.5.3.
python 3.5.2

**Comment by tacaswell** [comment]
This is because you are trying to over-constrain the system.  You essentially have the equations

```
x_range = C1
y_range = C2
x_range =  λ * y_range
```

which clearly can not be solved if `C1 = λ*C2` .

**Comment by godaygo** [comment]
@tacaswell Sorry, I can not fully understand your idea. `'equal'` means that the length of line segment  will be the same on x and y and `share` only shares. How the both here affect axis limits?

About over-determined systems, as I remember they can have zero, one, or infinity number of solutions. Here as I see the solution is:    x_range=[0, 1]; y_range=[0, 1]; &#955; =1. Maybe I'm wrong. 

I think that the solution should be (like with no sharing):
![image](https://cloud.githubusercontent.com/assets/20781495/21114913/e6e3dfa6-c0bf-11e6-8c8d-55187e824f41.png)

**Comment by godaygo** [comment]
@tacaswell Accoording to this issue [#7654](https://github.com/matplotlib/matplotlib/issues/7654). If I use `adjustable='box-forced'` kwarg, everything works fine as expected.
```python
fig = plt.figure()
ax1 = fig.add_subplot(121, adjustable='box-forced', aspect='equal')
ax2 = fig.add_subplot(122, adjustable='box-forced', aspect='equal', sharey=ax1)

ax1.plot([.1, .5, .9], [.1, .5, .9], 'o')
ax2.plot([.1, .5, .9], [.1, .5, .9], 'o')

ax1.axis([0, 1, 0, 1])
ax2.axis([0, 1, 0, 1])

ax1.set_xticks([0, .2, .4, .6, .8, 1])
ax2.set_xticks([0, .2, .4, .6, .8, 1])

plt.show()
```

![](https://cloud.githubusercontent.com/assets/20781495/21114913/e6e3dfa6-c0bf-11e6-8c8d-55187e824f41.png)
