### ISSUE TITLE
potential bug with plt.arrow and plt.annotate when setting linestyle via tuples

### ISSUE THREAD

**Issue by ebauch** [matplotlib/matplotlib#7623]
Seems like you cannot set the linestyle for arrows via tuples. This just works fine 

plt.annotate("", 
            xy=(0, 0), xycoords='data', xytext=(1, 1), textcoords='data',
            arrowprops=dict(arrowstyle="->", connectionstyle="arc3", color='0.5', **ls='--'**)
            )

where the bold part sets the linestyle of the arrow. However, this won't work and throws an error when using the tuple description of linestyle: 

plt.annotate("", 
             xy=(0, 0), xycoords='data', xytext=(1, 1), textcoords='data',
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3", color='0.5', **ls=(0, [2 ,2])**)
             )

The error says 

> TypeError: unhashable type: 'list'

The same is true for plt.arrow. The tuple description works just fine on regular plots: 

xx = np.linspace(0, 1, 100)
plt.plot(xx, xx, ls=(0, [2, 2]))

Am I doing something wrong or is this an actual bug?

**Comment by tacaswell** [comment]
What version of mpl?  I can not reproduce this on 2.x.

Does it work if you do

```python
plt.annotate("",
xy=(0, 0), xycoords='data', xytext=(1, 1), textcoords='data',
arrowprops=dict(arrowstyle="->", connectionstyle="arc3", color='0.5', ls=(0, (2 ,2)))
)
```
?

**Comment by ebauch** [comment]
Hey Taca, 

thanks for the quick response. I ran your code and it works! I think the issues is with [] versus () brackets. I thought you define the tuples via [2, 2], that is how I have been doing it for the regular plots. Seems like the arrow function don't like the list definition. (2, 2) does the trick though. What is the supposed tuple definition? 

Python 3.4.5 Kernel and Iphython Notebook IPython 5.1.0.

**Comment by tacaswell** [comment]
`[4, 4]` is a list, which is mutable, vs `(2, 2)` which is a tuple and immutable.  Mutable objects are not hashable (as their value can change) and hence can not be used as a key in a dictionary.  Apparently we were using the value of `ls` as a key _someplace_ inside annotation.

What does

```python
import matplotlib
print(matplotlib.__version__)
```
give?

**Comment by ebauch** [comment]
Interesting, thanks for the explanation. 

Matplot lib version 1.5.3

**Comment by tacaswell** [comment]
I can confirm that this is a bug in 1.5.3, but is fixed in 2.x so closing. This was likely inadvertently fixed as part of the linstyle/dash refactoring.

Thanks for taking the time to report the bug!

You can try out the pre-release, see http://matplotlib.org/style_changes.html
