### ISSUE TITLE
WX mouseevent assertion errors

### ISSUE THREAD

**Issue by kuch3n** [matplotlib/matplotlib#7636]
Hi, 

Got an assertion failed on MouseClick. MouseClicks won't work after this. 

Please see: https://github.com/newville/wxmplot/issues/25

- Python 2.7, Arch Linux, mpl 1.5.3
- Install: pacman and pip afterwards

**Comment by tacaswell** [comment]
Can you please include more details in this issue?

I have edited the title to make clear this is a wx-only issue.

**Comment by newville** [comment]
@tacaswell @kuch3n  A little background:  The code in backend_wx.py has many calls to `self.CaptureMouse()`  in the "MouseButton Down" events and `if self.HasCapture(): self.ReleaseMouse()` in the "MouseButton Up" events.  

It's not clear to me why this is necessary (or desirable), and it seems to cause the C++ assertions that @kuch3n referred to, especially on Linux and OS X.

From https://www.wxpython.org/docs/api/wx.Window-class.html#CaptureMouse (and also    https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.CaptureMouse) 
wxWidndow.CaptureMouse() is intended to force all mouse events to the window that captured the mouse, even if focus is lost to another window or application.  I don't know why a matplotlib cakend should want to do this.   

FWIW, In wxmplot we just monkey-patch `CaptureMouse` to be a no-op method for Linux  and OSX, and mouse actions work fine, without these C++ assertions from leaving and re-entering the Window.

The docs pointed to say:

> Any application which captures the mouse in the beginning of some operation 
> must handle wx.MouseCaptureLostEvent and cancel this operation when it 
> receives the event. The event handler must not recapture mouse.

I'm pretty sure that backend_wx.py does not handle `wx.MouseCaptureLostEvent`, as would be required.  That probably explains the assertion error.

FWIW, In wxmplot we just monkey-patch `CaptureMouse` to be a no-op method for Linux  and OSX, and mouse actions work fine, without these C++ assertions from leaving and re-entering the Window.   So IMHO, the CaptureMouse() is doing more harm than good.  

I'd be willing to make a PR removing CaptureMouse()/ReleaseMouse() if desired.

**Comment by efiring** [comment]
Please do so!

**Comment by NelleV** [comment]
Closed by #7752
