### ISSUE TITLE
Stacked 2D plots with interconnections in Matplotlib

### ISSUE THREAD

**Issue by mdepitta** [matplotlib/matplotlib#7637]
Fedora 20; Python 2.7.5; Matplotlib 1.4.3 (installed by yum/pip)

I need to visualize some complex multivariate datasets and the preferred way is to use a modification of parallel axis visualization, using stacked 2D plots, where each plot maps a degree of freedom/model parameter and data points belonging to the same data sets should be interconnected across different plots. I am attaching a conceptual sketch. How could I implement it in matplotlib?

I put emphasis that each plane should be a plot itself with its own axes with their own scales. More specifically, all plots have the same x-axis, but the y-axis represents something different.

![stack_plot](https://cloud.githubusercontent.com/assets/8409620/21293936/782bbe30-c4f7-11e6-9bbf-669515456065.png)

**Comment by tacaswell** [comment]
This sort of question is best handled on the mailing list (matplotlib-users@python.org you will need to [join the list](https://mail.python.org/mailman/listinfo/matplotlib-users) to post un-moderated).  We try to keep the issues for bug reports or feature requests.

**Comment by mdepitta** [comment]
Thanks. Sorry about it. I will post it there accordingly.
