### ISSUE TITLE
imshow seems to "shift" grid.

### ISSUE THREAD

**Issue by flamingbear** [matplotlib/matplotlib#7642]
When I try to us axes.imshow in matplotlib with a grid of known size and shape,
and then later read the png data, the image's data changes (is shifted) compared to the
input gridded data.

There may be a flag or option that I'm just not aware of, so I would love any help to prevent this shift.

Please see the gist included below for a self contained example.

To help us understand and resolve your issue please check that you have provided
the information below.

- [x ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
```
 $ python --version
Python 3.5.2
vagrant@vmsnowoffpiste ~/projects/cartopy-why (master *=)
 $ conda list | grep matplotlib
matplotlib                1.5.3               np111py35_3    conda-forge/channel/main
```  
I also ran my test code on macosx+conda with the same results.

- [X ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
via conda
- [ X] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
Please see gist here (has small code and data demonstrating the problem):
https://gist.github.com/flamingbear/8f3e081c31fbb428fe60afe71729d5ec
- [ X ] If this is an image generation bug attach a screenshot demonstrating the issue.
Easier to generate the problem image with the code from the gist above, but here are the output images I'm getting.
flickering gif:  http://imgur.com/i8Tf16X
imshow's png:  http://imgur.com/syjZmQ4
scipy's png: http://imgur.com/6rLIxA4

**Comment by tacaswell** [comment]
This might be an off-by-one bug / pixel aliasing issue.

attn @QuLogic as you have spent a lot of time looking at these small shifts recently.

@flamingbear Can you try with 2.0rc2 (see http://matplotlib.org/style_changes.html you are already using conda forge so it will be easy for you ;) , we significantly re-wrote the image handling code.

**Comment by flamingbear** [comment]
@tacaswell 

Wow,  I'm not sure how I feel about that, but I can confirm that  2.0rc2 does not exhibit the problem.

Thanks for the tip.  Not sure we're ready for that jump yet, but it's good to know this problem doesn't exist there.

Matt

**Comment by tacaswell** [comment]
Great, then I am going to close this as fixed.  There will not be another release in the 1.5 series.

Jumping to 2.0 should be less disruptive than a normal mpl minor release bump, particularly if you use the classic style sheet.
