### ISSUE TITLE
Matplotlib 2.0 deprecations

### ISSUE THREAD

**Issue by ngoldbaum** [matplotlib/matplotlib#7643]
I've just finished running the yt unit tests against matplotlib 2.0rc2 (i know, i know I'm late to the party) and noticed some new deprecations. It would be nice if a couple of them could be updated to be somewhat more ergonomic. In particular:

* The warning about deprecating axes.hold doesn't offer a way to adapt to the new behavior. Maybe the warning should just suggest looking at the API Changes document, which describes the deprecation in much more detail. Here's the warning as I saw it: `/Users/goldbaum/Documents/yt-hg/yt/visualization/plot_modifications.py:1389: MatplotlibDeprecationWarning: The hold function was deprecated in version 2.0.`.

* It looks like some of the colormaps names have been deprecated. It would be nice if this could be mentioned in the API Changes document. Here's the warning as I saw it: `/usr/local/lib/python3.5/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The spectral and spectral_r colormap was deprecated in version 2.0. Use nipy_spectral and nipy_spectral_r instead.`

If anyone is curious, here's the pull request I opened which fixes the deprecations I saw:

https://bitbucket.org/yt_analysis/yt/pull-requests/2467/

**Comment by tacaswell** [comment]
I am glad that the breakage looks not too bad to deal with!

**Comment by QuLogic** [comment]
`nipy_spectral` is not new in 2.0; it's been around since at least 1.3.0.

**Comment by ngoldbaum** [comment]
It looks like `spectral` was only explicitly deprecated back in November: https://github.com/matplotlib/matplotlib/commit/c7088714be5f219eba0f722596f3da77500a774e

**Comment by ngoldbaum** [comment]
Still, I think it deserves mention in the API changes doc along with the rest of the 2.0 deprecations.

**Comment by QuLogic** [comment]
Not disagreeing with you on that.
