### ISSUE TITLE
--nose-verbose isn't a correct option for nose

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7649]
http://matplotlib.org/devdocs/devel/testing.html#running-the-tests says to run

`python tests.py --nocapture --nose-verbose --processes=5 --process-timeout=300`

But the --nose-verbose option doesn't seem to exist!

```
$ python tests.py --nocapture --nose-verbose --processes=5 --process-timeout=300
Python byte-compilation optimization level: 0
Usage: tests.py [options]

tests.py: error: no such option: --nose-verbose
```
The options available are listed on https://nose.readthedocs.io/en/latest/usage.html#options . Just dropping the `--nose-verbose` option seems to be fine, but I'm not sure what was intended by whoever originally wrote that line of the docs.

**Comment by petehuang** [comment]
It looks like the intent was to use all the "important" arguments that were mentioned right before. I fixed `--nose-verbose` to be `--verbose` instead of full-on deleting. #7727 contains this change.
