### ISSUE TITLE
anchored_artists don't support zorder argument

### ISSUE THREAD

**Issue by RafiKueng** [matplotlib/matplotlib#7650]
AnchoredText and other items from `mpl_toolkits.axes_grid.anchored_artists` don't accept `zorder`.

In the following example, the anchored text should be above the line:
```python
import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid.anchored_artists import AnchoredText

fig = plt.figure()
ax = fig.add_subplot(111)

at = AnchoredText("test", prop=dict(size=24,zorder=20), loc=3, frameon=True, zorder=20)
ax.add_artist(at)
ax.plot([0,1],[0,1],'r', zorder=10)

plt.show()
```

- [x] Matplotlib 1.5.3, Python 2.7.12 and 3.4.5 Platform OpenSUSE linux
- [x] How install mpl: `pip install --update --user`

**Comment by RafiKueng** [comment]
one can however directly set the zorder on the at element:

at.zorder = 20

**Comment by tacaswell** [comment]
Without looking at the code, I expect this to be a matter of tracing through where the kwargs in AnchoredText get processed and ensure that zorder is properly handled.

**Comment by tacaswell** [comment]
@RafiKueng Would you be interested in taking a crack at sorting this out?

**Comment by RafiKueng** [comment]
I can have a try once my deadline is over ;)

**Comment by RafiKueng** [comment]
note to myself:
I also found other possible bugs in the ancored artists... (scalebar for example) I might clean up everything when I'm at it.

**Comment by tacaswell** [comment]
I believe that https://github.com/matplotlib/matplotlib/pull/7344 is related?

**Comment by RafiKueng** [comment]
yes, looks like #7344 is related.

Can anyone help me out: what's the reason for having `mpl_toolkits/axes_grid` and `mpl_toolkits/axes_grid1` and `mpl_toolkits/axisartist`? Should there some cleaning up happen or shoudn't one touch/move/delete anything?

**Comment by tacaswell** [comment]
There _should_ be some cleaning up, but it needs to be done carefully so that we do not break user code without warning.

**Comment by QuLogic** [comment]
`axes_grid` is the original, and `axes_grid1` and `axisartist` are split versions of them. I'm pretty sure `matplotlib.offsetbox` is the real implementation and the others just import it (of whatever's implemented there, anyway.) I've got a bit of cleanup ready for as soon as I've finished #7545.

**Comment by AhmadSenousi** [comment]
Is this problem Solved?

**Comment by timhoffm** [comment]
@AhmadSenousi In general, issues are closed when they are solved. If that this was missed, you can easily run the minimal example above to see that this is not yet solved.
