### ISSUE TITLE
legend doesn't show all markers

### ISSUE THREAD

**Issue by nbecker** [matplotlib/matplotlib#7653]
To help us understand and resolve your issue please check that you have provided
the information below.

- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
matplotlib-2.0.0rc2.dist-info python3.5 fedora 25 linux
- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
pip3 install --pre --upgrade --user matplotlib
- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
This is not (yet) self-contained, but the code is
```python
def plot_alloc_vs_sent (df):
    ax = df.plot(y='DataBytesSent', marker='x', linestyle='solid')
    df.plot(y='TotalAllocBytes', marker='o', ax=ax, linestyle='dotted')
    #df.plot(y='backlog', marker='^', ax=ax, linestyle='dotted')
    df.plot(y='queue', marker='<', ax=ax, linestyle='dotted')
    plt.grid()
    plt.show()
```
where df is a pandas [DataFrame]
- [ ] If this is an image generation bug attach a screenshot demonstrating the issue.
[figure1.pdf](https://github.com/matplotlib/matplotlib/files/666253/figure1.pdf)

- [ ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.

**Comment by WeatherGod** [comment]
Is it possible to make an example without pandas (in order to eliminate
possible sources of problems). Also, this isn't quite a SSCCE, as I can't
simply copy-n-paste this into an interpretor and execute it. It needs
imports and it needs data.

**Comment by tacaswell** [comment]
I can not reproduce this:

```python
import matplotlib.pyplot as plt
import numpy as np

th = np.linspace(0, 2*np.pi, 128)

fig, ax = plt.subplots()
ln1, = ax.plot(th, np.sin(th), marker='o', label='o -', linestyle='solid')
ln2, = ax.plot(th, np.cos(th), marker='x', label='x :', linestyle='dotted')
ln3, = ax.plot(th, -np.sin(th), marker='<', label='< --', linestyle='dashed')
ax.legend()
```

```
In [10]: plt.matplotlib.__version__
Out[10]: 
'2.0.0rc2.post12+g4f0d2ee'
```
![so](https://cloud.githubusercontent.com/assets/199813/21398122/369b382c-c774-11e6-9619-c4101a36939f.png)
[so.pdf](https://github.com/matplotlib/matplotlib/files/666900/so.pdf)

**Comment by nbecker** [comment]
It is not a regression, and it is a pandas problem.

If I add 1 line:
```python
def plot_alloc_vs_sent (df):
    ax = df.plot(y='DataBytesSent', marker='x', linestyle='solid')
    df.plot(y='TotalAllocBytes', marker='o', ax=ax, linestyle='dotted')
    #df.plot(y='backlog', marker='^', ax=ax, linestyle='dotted')
    df.plot(y='queue', marker='<', ax=ax, linestyle='dotted')
    ax.legend(loc='best') # <<<< added line
    plt.grid()
    plt.show()
```
Then all the markers are shown in the legend, and this is true using the mpl-1.5.2rc (standard fedora 25 version)

**Comment by tacaswell** [comment]
@nbecker Can you make an issue with pandas for this and link back to here?

Closing as not an mpl issue.
