### ISSUE TITLE
imsave ignores origin option

### ISSUE THREAD

**Issue by cdeil** [matplotlib/matplotlib#7656]
For me, the `imsave` option `origin="lower"` is silently ignored when saving to PNG.

If I execute this script, the resulting two images are identical:
```python
import numpy as np
from matplotlib.image import imsave

image = np.arange(30*20).reshape((20, 30))
imsave('lower.png', image, origin='lower')
imsave('upper.png', image, origin='upper')
```

Is this a MPL bug?

---

Version info: Python 3.5 as well as Numpy and MPL installed via macports, then MPL 2.0.0rc2 via pip in user site-packages, i.e. this is with MPL 2.0.0rc2.

---
lower.png is here:

![lower](https://cloud.githubusercontent.com/assets/852409/21391602/b47c2f0e-c78c-11e6-97f3-87741ecc8d1e.png)

---
upper.png is here:

![upper](https://cloud.githubusercontent.com/assets/852409/21391620/bec989f2-c78c-11e6-94dc-93e8124e630b.png)

**Comment by tacaswell** [comment]
```python
import numpy as np
from matplotlib.image import imsave

image = np.arange(30*20).reshape((20, 30))

fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.imshow(image, origin='lower')
ax2.imshow(image, origin='upper')
```

Fortunately this is a bug in `imsave` and not in `Axes.imshow`
![so](https://cloud.githubusercontent.com/assets/199813/21398920/6245c318-c777-11e6-83a2-541db4cc5dd7.png)

imsave is efficient and skips the standard draw machirary (and just uses `AxesImage.write_png`) which ignores the origin state.

**Comment by tacaswell** [comment]
Exact work:
 
 - add check in `AesImage.write_png` for the origin state and color mapped imaged if needed.
