### ISSUE TITLE
document that imshow now respects scale

### ISSUE THREAD

**Issue by PrometheusPi** [matplotlib/matplotlib#7661]
With the introduction of matplotlib 2.0.0 using `plt.imshow()` together with `plt.yscale('log')` changed its behavior.

The following example code:
```python
import numpy as np
import matplotlib.pyplot as plt

tmp = np.random.random((5,5))
plt.imshow(tmp, aspect="auto", extent=(0,5, 1e0, 1e5), interpolation='nearest')
plt.yscale("log")

plt.show()
```
produces with python 3.4.3 and **matplotlib 1.5.1**
![plt_imshow_2](https://cloud.githubusercontent.com/assets/5121158/21426111/5750a4b0-c84d-11e6-947a-26e46c8e7653.png)

*and the following warning:*
```shell
../.local/lib/python3.4/site-packages/matplotlib/image.py:375: UserWarning: Images are not supported on non-linear axes.
  warnings.warn("Images are not supported on non-linear axes.")
```

With python 3.4.3 and **matplotlib 2.0.0rc1** it produces
![index2](https://cloud.githubusercontent.com/assets/5121158/21425587/5256f78c-c84a-11e6-9444-b720f6c4f9a7.png)

Thus, 2.0.0 assumes that underneath the linear bin id of the numpy array `tmp` lies a linear data extend (y-axis) scaling.

If however my logarithmic extent is mapped correctly onto the linear bin id of the numpy array - the old behavior is exactly what represents the data. 

**Is it possible to reproduce the old behavior without relabeling the y-axis by hand?
Is there an option, the tell imshow directly that a specify data axis is already log-scaled?**
and if so:
**Is it possible to have the same behavior independent of the matplotlib version used?**

**System:**
Ubuntu 14.04.5 - Linux-Kernel 4.4.0-38
Matplotlib and Python are available via the HPC module system (probably via pip)

cc'ing: @s0vereign

**Comment by tacaswell** [comment]
To be clear, you were relying on a bug / undefined behavior.  The new behavior is in arguably correct.

I think you want to be using http://matplotlib.org/examples/pylab_examples/image_nonuniform.html in 2.0+ but not sure if that will work as expected in <2.0.

I think `pcolor` and friends will work in all cases, see http://matplotlib.org/examples/pylab_examples/pcolor_demo.html

**Comment by phobson** [comment]
Agree with @tacaswell about pcolor. This works in 1.5 and the 2.0 RC:
http://stackoverflow.com/a/20844584/1552748

**Comment by efiring** [comment]
Don't use pcolor--it's slow, and has no advantages in most cases.  Use pcolormesh.  Supply the cell *boundaries* explicitly:
```python
import numpy as np
import matplotlib.pyplot as plt

tmp = np.arange(30).reshape(5, 6)
x = np.linspace(0, 6, 7)
y = 10**np.linspace(0, 5, 6)
X, Y = np.meshgrid(x, y)
fig, ax = plt.subplots()
ax.set_yscale('log')
ax.pcolormesh(x, y, tmp)
ax.autoscale('tight')

plt.show()
```
It should be possible to do this more efficiently with Axes.pcolorfast, but it doesn't work with a log scale.  That's a bug.
When testing this sort of thing, use a rectangular array (not a square), and a regular pattern, so you can be sure you are getting the orientation the way you intend it.

**Comment by PrometheusPi** [comment]
Thanks a lot for your help. I finally had the time to implement the `pcolormesh` approach in our code. It works like a charm.

**Comment by mforbes** [comment]
What about when loading an RGB image from file?  `pcolormesh` does not obviously accept RGB data...
