### ISSUE TITLE
eventplot legend fails (linewidth)

### ISSUE THREAD

**Issue by nepix32** [matplotlib/matplotlib#7662]
Trying to add a legend to an event gives ``TypeError: 'float' object is not subscriptable``. Reason is that in ``legend_handler.HandlerLineCollection._default_update_prop`` ([link](https://github.com/matplotlib/matplotlib/blob/409d8b79074f99a2fd5b0e2498aab24535e40485/lib/matplotlib/legend_handler.py#L270)) in the call to ``lw = orig_handle.get_linewidth()[0]`` subscripting happens twice (the return of ``get_linewidth()`` already has ``[0]`` applied). Removing ``[0]`` fixes the issue.

There is no pull request as I do not know if this fix will break something somewhere else.

```python
from matplotlib import pyplot as plt

plt.eventplot([11.0], label='Label')
plt.legend()
plt.show()
```

Version: matplotlib 1.5.3, Python 3.5.2 32 bit
Distro: winpython

Did also not work on mpl 1.4.3/Python 2.7

**Comment by tacaswell** [comment]
@nepix32 Can you open a PR with that change?  We automatically run tests on ever PR which will answer the question if it breaks anything else :smiley: .

**Comment by nepix32** [comment]
Wrote a second, better fix.

How to re-run a test (I suppose the [app-veyor error for the last update pull request](https://github.com/nepix32/matplotlib/commit/ed9f0f757e2f6d7725f8bba21ea9eaebd635cb08) causeb by something else). Coverage fails, but should not be related to the fix).
