### ISSUE TITLE
BUG: Can't import `matplotlib._backports`

### ISSUE THREAD

**Issue by Eric89GXL** [matplotlib/matplotlib#7663]
- [x] Matplotlib version: `master`, Python version 2.7.12 and Platform Linux x86_64
- [x] Installed Matplotlib from source (python setup.py install) and Python is system python
- [x] SSCCE:
    ```
    >>> from mpl_toolkits.mplot3d import Axes3D
  File "/home/larsoner/.local/lib/python2.7/site-packages/matplotlib-2.0.0rc2+2775.g48d50fc-py2.7-linux-x86_64.egg/mpl_toolkits/mplot3d/__init__.py", line 6, in <module>
    from .axes3d import Axes3D
  File "/home/larsoner/.local/lib/python2.7/site-packages/matplotlib-2.0.0rc2+2775.g48d50fc-py2.7-linux-x86_64.egg/mpl_toolkits/mplot3d/axes3d.py", line 34, in <module>
    from . import art3d
  File "/home/larsoner/.local/lib/python2.7/site-packages/matplotlib-2.0.0rc2+2775.g48d50fc-py2.7-linux-x86_64.egg/mpl_toolkits/mplot3d/art3d.py", line 17, in <module>
    from matplotlib._backports import numpy as _backports_np
    ImportError: No module named _backports
    ```
- [x] This is a regression, works when I switch to, build, and install the v1.5.3-doc branch.   

Let me know if this issue makes sense and I can try to do a better `git blame` to find where it comes up.

**Comment by tacaswell** [comment]
It works with `pip install -e .`, but not with `pip install .`.  

attn @anntzer 

This file came in via 
de5a4eee98f21e90cec03089c23f14482187dc6a in #7544 

Strongly suspect the issue is a missing entry in the manifest.

**Comment by Eric89GXL** [comment]
Doing `pip install --user -e .` does indeed get me past this bug and onto another.

Do you mean MANIFEST.in? I don't see anything there that could relate to missing packages. I then thought it could be missing from `setup.py`, but it looks like the `py_modules` is auto-populated somehow. Might need to dig into that to figure it out.

**Comment by anntzer** [comment]
My quick guess is that an entry should be added to `Matplotlib.get_packages` in `setupext.py`.  It would probably be better to switch this to using `setuptools.find_packages` if possible, to avoid this kind of issues later.
