### ISSUE TITLE
standardize classic/v2.x order is docs

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7672]
http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#bar-and-barh and http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#fill-between-and-fill-betweenx have classic on the right, everthing else has classic on the left.

**Comment by QuLogic** [comment]
The Math text entry (http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#math-text) is also up/down instead of left/right.

**Comment by tacaswell** [comment]
That one is that way due to excessively global settings.  IIRC, you can not render text artists on the same canvas using different mathtext see https://github.com/matplotlib/matplotlib/issues/7107

**Comment by QuLogic** [comment]
I had a feeling it might be something like that, though I had hoped one of your font-related PRs had fixed it.
