### ISSUE TITLE
directory-of-files MovieWriter subclass

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7679]
Derived from https://stackoverflow.com/questions/41230286/matplotlib-animation-write-to-png-files-without-third-party-module

Some version of my answer http://stackoverflow.com/a/41273312/380231

```python
import matplotlib.animation as ma


class BunchOFiles(ma.FileMovieWriter):
    def setup(self, fig, dpi, frame_prefix):
        super().setup(fig, dpi, frame_prefix, clear_temp=False)

    def _run(self):
        # Uses subprocess to call the program for assembling frames into a
        # movie file.  *args* returns the sequence of command line arguments
        # from a few configuration options.
        pass

    def grab_frame(self, **savefig_kwargs):
        '''
        Grab the image information from the figure and save as a movie frame.
        All keyword arguments in savefig_kwargs are passed on to the 'savefig'
        command that saves the figure.
        '''

        # Tell the figure to save its data to the sink, using the
        # frame format and dpi.
        with self._frame_sink() as myframesink:
            self.fig.savefig(myframesink, format=self.frame_format,
                             dpi=self.dpi, **savefig_kwargs)

    def cleanup(self):
        # explictily skip a step in the mro
        ma.MovieWriter.cleanup(self)
```

should end up in the animation module in the case where people just want a folder of png and don't have any of the other external tools installed.

**Comment by efiring** [comment]
Good idea.  Along with it, we should have standalone wrappers for those external tools, acting on the folder of pngs.  This makes it efficient to test different parameters for the generated animation, or to make several versions of it.

**Comment by WeatherGod** [comment]
Could possibly make it possible to adapt the image comparison test
framework to work off a directory of pngs, so we could have some animation
tests?

**Comment by anntzer** [comment]
Couldn't that just be done by adapting FileMovieWriter accordingly?  In one of my oldest PRs (#3536) I argued that FileMovieWriter should default to putting its files in a tempdir anyways; it seems reasonable to just make it either a tempdir or a dir passed as argument.

**Comment by QuLogic** [comment]
If you pass a `frame_prefix` to `setup` instead of `clear_temp=False`, then those files will not be removed.
