### ISSUE TITLE
3-D scatter plot disappears when overlaid over a 3-D surface plot.

### ISSUE THREAD

**Issue by pwoosam** [matplotlib/matplotlib#7684]
I am trying to generate a 3-D surface plot with a 3-D scatter plot overlaid.
The issue is that not all of the points are visible when they are on the surface of the surface plot.

![angle1](https://cloud.githubusercontent.com/assets/18713517/21476043/644b5618-cae8-11e6-8692-adc2b9f9cc8a.png)
![angle2](https://cloud.githubusercontent.com/assets/18713517/21476044/6ab4a0d6-cae8-11e6-8a9d-cfdc12ed374b.png)
![angle3](https://cloud.githubusercontent.com/assets/18713517/21476045/6f7b018c-cae8-11e6-9a7a-0c8f09fb48c7.png)

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.gca(projection='3d')

x = np.arange(200)
y = np.arange(200)
x, y = np.meshgrid(x, y)
z = np.zeros((200, 200))

# Create index arrays.
I, J = np.meshgrid(np.arange(200), np.arange(200))

# Calculate distance of all points to center.
dist = np.sqrt((I - 100)**2 + (J - 100)**2)

# Create the peak.
radius = 50
height = 1
curve = np.linspace(0, np.pi, radius*2)
z_peak = [(np.cos(i) + 1) * height / 2 for i in curve]
for cr, h in enumerate(z_peak):
    z = np.where(dist < cr, z, h)

ax.plot_surface(x, y, z, rstride=1, cstride=1, linewidths=0, cmap='terrain')

# Generate points to represent population.
x_ = np.random.randint(0, 200, size=100)
y_ = np.random.randint(0, 200, size=100)
z_ = []
for x, y in zip(x_, y_):
    z_.append(z[x, y])
points = ax.scatter(x_, y_, z_)
```

Another issue is that at some angles, points on the other side of the surface plot's peak are visible. They should not be visible through the surface unless the surface plot's alpha is set below 1.

To see this, change:
`    z_.append(z[x, y])`
to
`    z_.append(z[x, y] + 0.2)`

![figure_11](https://cloud.githubusercontent.com/assets/18713517/21476191/8dbba03c-caea-11e6-89d7-78ec2cdbb96b.png)
![figure_12](https://cloud.githubusercontent.com/assets/18713517/21476196/93948d8e-caea-11e6-9192-29dda8e7c6ea.png)
Note: I also changed the stride values for the surface plot to their default values. It has little effect on the issue though.

System Info:
Matplotlib: 1.5.3 (from Anaconda installer)
Python: 3.5.2 (from Anaconda installer)
Platform: Windows 10

P.S. Happy Holidays!! 🎊 🎁 🎊 ☃️

**Comment by WeatherGod** [comment]
This this is a known limitation of mplot3d. It is not a true 3d rendering
toolkit, and it is constrained by the layering engine of matplotlib. Each
artist gets a single zorder value, which determines the order in which
artists and collections are drawn. As such, the rendering of mixed 3d
scenes is impossible in the general case because either the surface artist
or the scatter artist has to be drawn before the other.

You might want to look at glumpy, which is an open GL project that borrows
heavily from matplotlib. It does true 3d rendering, and may be more
suitable for your needs.
