### ISSUE TITLE
'Extend' keyword produces colorbar of zero width

### ISSUE THREAD

**Issue by AnkitBarik** [matplotlib/matplotlib#7686]
The 'extend' keyword gives a line instead of a colorbar.

Matplotlib version: 2.0.0rc2+2827.gab98852
Numpy version: 1.13.0.dev0+2498b74
Python version: 2.7.6
Compiler: gcc
Platform: Linux

Installation procedure: from source - using pip as well as directly using setup.py (tried both with same result)

Here's a piece of code generating the following

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mplc

x, y = np.mgrid[0:1:0.01, 0:1:0.01]
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(6 * np.pi * r)

norm = mplc.Normalize(0, 0.5)
fig0, ax0 = plt.subplots(1, 1, )
cf0 = ax0.contourf(x, y, z, np.arange(0, .5, .01), norm=norm,
                   extend='both', cmap='viridis')
cbar0 = plt.colorbar(cf0,)
```

Output:

```python
/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py:2888: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=0.5, right=0.5
  'left=%s, right=%s') % (left, right))
```

![figure_1](https://cloud.githubusercontent.com/assets/13730345/21479029/937615f4-cb51-11e6-88a3-eeef07b806e6.png)

**Comment by efiring** [comment]
I can't reproduce this with matplotlib  '2.0.0rc2.post23+g3b1f5da' and numpy '1.11.0'.  
I see that your font and tick sizes are not the default values, so I suspect that the odd behavior is related to some rcParams settings.  Please try inserting `plt.rcdefaults()` before the `Normalize` line and see if that fixes it.  If so, the next step is to track down which settings are causing the problem.

**Comment by WeatherGod** [comment]
I am still suspicious of those extraneous commas. Doesn't that produce a
positional None value in the function calls?

**Comment by efiring** [comment]
No.
```python
In [1]: def test(a, b=5):
   ...:     print("a", a, "b", b)
   ...:

In [2]: test('zzz')
a zzz b 5

In [3]: test('zzz',)
a zzz b 5

In [4]: def test(a, b):
    print("a", a, "b", b)
   ...:

In [5]: test('zzz',)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-4396293300c8> in <module>()
----> 1 test('zzz',)

TypeError: test() missing 1 required positional argument: 'b'
```

**Comment by AnkitBarik** [comment]
All right, I also tried the example given in the documentation:

http://matplotlib.org/examples/api/colorbar_only.html

Here's what I got

![figure_1-1](https://cloud.githubusercontent.com/assets/13730345/21495270/cc7c95ba-cc16-11e6-9a60-9b7189816435.png)

**Comment by AnkitBarik** [comment]
It seems to be a numpy problem.

Matplotlib version: 2.0.0rc2+2827.gab98852

With numpy version 1.11.3

![figure_1-2](https://cloud.githubusercontent.com/assets/13730345/21497084/12f6595c-cc23-11e6-9a39-2eb485f71aee.png)

With numpy version 1.13.0.dev0+2498b74

![figure_1-1](https://cloud.githubusercontent.com/assets/13730345/21497167/7f8a0a32-cc23-11e6-87ff-9ca65aa379df.png)

**Comment by efiring** [comment]
That's alarming! Would you open a numpy github issue, please?  If you can bisect to find the commit that starts the problem, that would be even better.
This can also be investigated on our side, to isolate the place where numpy is doing something differently in version 1.12.

**Comment by anntzer** [comment]
This bisects to https://github.com/numpy/numpy/pull/5302.

**Comment by dstansby** [comment]
I'm using numpy 1.12.0, and the example linked above is working fine for me on master, can someone else double-confirm that it's fine?

**Comment by dstansby** [comment]
Found the problem, currently working on a fix

**Comment by tacaswell** [comment]
@dstansby We can fix this on ourside?

**Comment by dstansby** [comment]
It turns out no, but I have filed a clearer upstream bug. For reference the issue is introduced to `matplotlib` here: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L843

**Comment by dstansby** [comment]
All fixed up on the numpy master branch:

![figure_1](https://cloud.githubusercontent.com/assets/6197628/22980691/22f75d2e-f392-11e6-8bf8-f736990e0a62.png)

**Comment by tacaswell** [comment]
@dstansby Thanks!

What version of numpy are we broken for, we should probably blacklist those (like we do for broken versions of pyparsing).

**Comment by AnkitBarik** [comment]
Thanks David!
"May the force be with you"

**Comment by dstansby** [comment]
I don't think we're broken for any, 1.12.0 works fine which was the last released version of numpy, so the problem was introduced and fixed in between releases from their master branch.
