### ISSUE TITLE
screenshots in the front page of devdocs are ugly

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#7704]
This is what the first two screenshots look like right now at http://matplotlib.org/devdocs/

![thick lines](http://matplotlib.org/devdocs/_static/membrane_frontpage.png)
![more thick lines](http://matplotlib.org/devdocs/_static/histogram_frontpage.png)

My suspicion is that this was caused by the recent changes to directly generate these images at these sizes rather than letting the html/css scale them to the desired size. I am not sure if there is some weird dpi bug or not.

**Comment by efiring** [comment]
Clicking on the screenshots figure takes us to a page that also shows some plots in need of adjustment.  
1) pie chart demo: the second figure is very poor; probably best to just delete it.
2) table demo: the text is too crowded; it needs more vertical space.
3) polar plot: there are too many r-grid lines (circles).

**Comment by tacaswell** [comment]
closed by #7740 and #7821
