### ISSUE TITLE
make all deprecation warnings be `mplDeprecation` instances

### ISSUE THREAD

**Issue by stonebig** [matplotlib/matplotlib#7717]
I'm trying to get rid of Deprecation Warnings of Matplotlib-2.0.0rc2.

I did this:
````
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
````

I still get that:
````
matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The spectral and spectral_r colormap was deprecated in version 2.0. Use nipy_spectral and nipy_spectral_r instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

matplotlib\__init__.py:914: UserWarning: axes.hold is deprecated. Please remove it from your matplotlibrc and/or style files.
  warnings.warn(self.msg_depr_set % key)
````

How can I silence them ?

**Comment by stonebig** [comment]
It seems that I need to do:

````
warnings.filterwarnings("ignore", category=UserWarning)
````

I would have thought that DeprecationWarning was more pertinent ... closing.

**Comment by QuLogic** [comment]
Hmm, @efiring as the last person to have looked at it, shouldn't out deprecation decorator be using `MatplotlibDeprecationWarning` instead of `UserWarning`?

**Comment by efiring** [comment]
We *are* using `MatplotlibDeprecationWarning` (aliased as `mplDeprecation`); it is just a renamed `UserWarning`:
```python
class MatplotlibDeprecationWarning(UserWarning):
    """
    A class for issuing deprecation warnings for Matplotlib users.

    In light of the fact that Python builtin DeprecationWarnings are ignored
    by default as of Python 2.7 (see link below), this class was put in to
    allow for the signaling of deprecation, but via UserWarnings which are not
    ignored by default.

    http://docs.python.org/dev/whatsnew/2.7.html#the-future-for-python-2-x
    """
    pass

mplDeprecation = MatplotlibDeprecationWarning
```

**Comment by QuLogic** [comment]
Ohh, looks like this line is not the decorator, but internal to `RcParams`:
```
matplotlib\__init__.py:914: UserWarning: axes.hold is deprecated. Please remove it from your matplotlibrc and/or style files.
  warnings.warn(self.msg_depr_set % key)
```

**Comment by efiring** [comment]
We could add `category=mplDeprecation` to all of those deprecation warnings.  It would still be a `UserWarning` subclass, but would allow filtering separately from other UserWarnings.

**Comment by NelleV** [comment]
@stonebig Can you explain what you do before getting those warnings?

**Comment by yoavram** [comment]
Why is `MatplotlibDeprecationWarning` a subtype of `UserWarning` instead of `DeprecationWarning`?

**Comment by WeatherGod** [comment]
Because if it subclasses DeprecationWarning, then it wouldn't be visible by
default. UserWarnings are intended for user-visible warnings, while
DeprecationWarnings is more meant for developers. Since matplotlib's users
are typically developers, it makes sense to use UserWarnings.

https://docs.python.org/2/library/warnings.html#warning-categories

**Comment by TangeniThePyGuru** [comment]
I used the `UserWarning` class and the warning disappeared.

Thanks!
