### ISSUE TITLE
Axis still drawn when the Axis.grid boolean set to False

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#7722]
This may be a bug or a feature depending on your taste, but I think it is anomalous that a call to the Axis grid function will draw a grid when keywords are supplied, even when the boolean first argument is set to False, e.g., this will still draw the grid:

    >>> ax.grid(False, color='b')

I understand the reasoning - why change a style if you don't want the grid - but it seems inconsistent to ignore an explicit boolean argument. It is true that in interactive sessions, nobody will type the above, but it is easily possible in a program, where it is often simpler to set style parameters in every call to the grid function, whether it is required or not.

I would suggest that the first lines of the grid function of the Axis class in axis.py should be:

        if b is None and len(kwargs):
            b = True

**Comment by tacaswell** [comment]
That seems reasonable.  The docstring should be clarified a bit as well.

**Comment by rayosborn** [comment]
I can issue a pull request. The only problem is that I can't test what I submit, because I can't run the latest development version without finding out how to update my ft2font library.

**Comment by rayosborn** [comment]
I can install 2.0.0rc with `pip install --pre matplotlib` but I can't install the latest development version using pip on a cloned repository. This is the end of the trace for importing peplos:

    /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/mathtext.py in <module>()
         56 
         57 import matplotlib.colors as mcolors
    ---> 58 import matplotlib._png as _png
         59 
         60 ####################
    
    ImportError: dlopen(/Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so, 2): Library not loaded: @rpath/libpng16.16.dylib
      Referenced from: /Users/rosborn/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/_png.so
      Reason: Incompatible library version: _png.so requires version 43.0.0 or later, but libpng16.16.dylib provides version 30.0.0

This is using a Conda installation of Python 2.7.11 on Mac OS X 10.11.6.

**Comment by tacaswell** [comment]
Can you try the following:

```bash
conda create -n mpl_dev python matplotlib ipython
source activate mpl_dev
conda remove matplotlib  # this is an easy way to get all of the build deps available
cd mpl_source
git clean -xfd  # make sure no stale build products are around
export MPLLOCALFREETYPE=1  # to build the version of freetype the tests are pinned to
pip install -v -e .
```

**Comment by rayosborn** [comment]
That seems to work. I tried to clean up an existing conda environment using the above commands, but that didn't work, even after removing freetype, so I'm not sure I understand why it worked.

**Comment by tacaswell** [comment]
Once the c library linking of a conda env gets fouled the fastest course of action is to just delete it and start again :stuck_out_tongue_winking_eye: .  

I nuke my 'daily' enviroment every other month or so and if I ever need to test different versions of things (python / numpy / whatever) I create throw-away envs in `/tmp`.

**Comment by ksunden** [comment]
This now issues a `UserWarning` explaining that the grid is enabled, as well as being better explained in the docstring. I think that is sufficient.
