### ISSUE TITLE
Can't import Matplotlib.widgets.TextBox

### ISSUE THREAD

**Issue by JeanRintoul** [matplotlib/matplotlib#7724]
Install: Matplotlib v 1.4.3, Python 2.7.1 with pip. 

`Traceback (most recent call last):
  File "realtime.py", line 10, in <module>
    from matplotlib.widgets import Slider, Button, RadioButtons, TextBox
ImportError: cannot import name TextBox`

I can see TextBox in the documentation listed the same as Button, Slider but it doesn't work. Other widgets do work.

**Comment by tacaswell** [comment]
Which docs are you looking at?  `TextBox` is not actually in a released version of matplotlib, only on the master branch (and will be included in the 2.1 release).

**Comment by Evidlo** [comment]
There is an example for `TextBox` [here](https://matplotlib.org/devdocs/examples/widgets/textbox.html).  Maybe it should say that `TextBox` is not actually in a released version yet?

**Comment by WeatherGod** [comment]
Those are devdocs; they are built off of master.

But, you do raise a valid point. We should do a better job of labeling when
features are added. Would you like to open a PR to update this docstring?
