### ISSUE TITLE
Trying to set_ylim(bottom=0) on a log scaled axis changes plot

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7733]
```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(2, 1)

axs[0].scatter(range(0, 4), [0, 1, 2, 3])
axs[1].scatter(range(0, 4), [0, 1, 2, 3])

axs[0].set_yscale('log')
axs[1].set_yscale('log')

axs[1].set_ylim(bottom=0)

plt.show()
```

This raises
```
/home/dstansby/matplotlib/lib/matplotlib/axes/_base.py:3174: UserWarning: Attempted to set non-positive ylimits for log-scale axis; invalid limits will be ignored.
  'Attempted to set non-positive ylimits for log-scale axis; '
```

However, the 2nd plot *is* changed by the `set_ylim(bottom=0)` call, and no data is visible.

![figure_1](https://cloud.githubusercontent.com/assets/6197628/21616640/2654ac76-d1da-11e6-800a-96b2027e9947.png)

This is present on master.

**Comment by anntzer** [comment]
See also the discussion at #7460 and the related PR #7744.  It would be nice to have a consistent behavior in both cases (and possibly reuse the same code-path, if possible).  As argued in #7460, I personally prefer the behavior of #7735 (treat invalid values as nan).
