### ISSUE TITLE
inconsistent doc regarding keymap.fullscreen default value

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7734]
`keymap.fullscreen` alternates between being described as only `f` (`matplotlibrc.template`, comment in `backend_bases.py`), only `ctrl+f` (`navigation.toolbar.rst`), and both values (which is the actual current default) (`classic.mplstyle`, `rcsetup.py`).

Simplest would be to make it both values everywhere although I wonder whether we could get away with sticking to only one of the two keymaps.

**Comment by petehuang** [comment]
I'll just go ahead and fix everything to both. Working on it
