### ISSUE TITLE
configure hash density and size

### ISSUE THREAD

**Issue by godaygo** [matplotlib/matplotlib#7750]
I've a laptop with HiDPI display, so I  use `c.InlineBackend.figure_format = 'retina'` in IPython to prevent blurring in browser . I found some differences between `mpl 1.5.3` and `2.0.0`. I've tried to summarize them:
* In both versions, **blur disappears** when I set up `figure_format = 'retina'`.  

In `mpl 1.5.3`  `'retina'` also **affects** the `hatch`es appearance (and they look nicer):  

<img width="184" alt="mpl 1 5 3 default title" src="https://cloud.githubusercontent.com/assets/20781495/21699773/510ce836-d3ae-11e6-9218-fc8ad78ff7c0.png">
<img width="369" alt="mpl 1 5 3 retina title" src="https://cloud.githubusercontent.com/assets/20781495/21699777/53e95e22-d3ae-11e6-962f-3192e6cfeb9b.png">  

Here you can't see the blur, but it actually is, without setting up `'retina'` or `'png2x'`.   

In `mpl 2.0.0`  `'retina'` only affects blur effect:   

<img width="131" alt="mpl 2 default title" src="https://cloud.githubusercontent.com/assets/20781495/21699965/18a4bc2a-d3af-11e6-91b3-9a2bf8ff02cc.png">
<img width="263" alt="mpl 2 retina title" src="https://cloud.githubusercontent.com/assets/20781495/21699968/1a6a6e2e-d3af-11e6-8c40-48bc6c69db27.png">

Also you can see that actual sizes differ between versions, I use `'Save image as'` to get pictures. It's nice that visual size in `2.0.0` in Jupyter notebook holds the same, but `hatch`es looks ugly:) Is it desirable behavior in `2.0.0`?

```python
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as patches

fig = plt.figure()
ax = fig.add_subplot(111, aspect='equal')

patt = ['-', '+', 'x', 'o', 'O', '.', '*', '\\', '/'] 

pol = lambda x, i: patches.RegularPolygon((i/(len(patt)-1), 0.5),
                                          50, 0.05, fill=False, hatch=x)

for i, pat in enumerate(patt):
    ax.add_patch(pol(pat, i))
    
ax.set_title('{} - retina\n size: ({}, {})'.format(mpl.__version__, fig.get_size_inches()[0],
                                                 fig.get_size_inches()[1]))
    
plt.show()
```

I use:   
Python 3.6  
IPython 5.1.0
jupyter-notebook 4.3.1
Firefox 50.1.0  
Windows 10  

**EDIT:**
`mpl 2.0.0`:
<img width="945" alt="mpl 2 0 0" src="https://cloud.githubusercontent.com/assets/20781495/21700782/2d158d66-d3b3-11e6-9404-b0bfcf58d099.png">

`mpl 1.5.3`:
<img width="927" alt="mpl 1 5 3" src="https://cloud.githubusercontent.com/assets/20781495/21700921/da6a0a82-d3b3-11e6-80b8-84fccbfabd81.png">

**Comment by tacaswell** [comment]
att @Carreau As this is mostly with the inline backend someone from jupyter should be looped in.

**Comment by tacaswell** [comment]
Hatches being dpi independent is a feature of 2.0.

**Comment by godaygo** [comment]
@tacaswell  Thank you let it be dpi independent:) But the sizes really differ, I add print-screens to my question.

**Comment by Carreau** [comment]
Thanks, I"ll have a look

**Comment by tacaswell** [comment]
ok, I can reproduce the issue locally.  One possible solution is to use

```python
patt = [p*2 for p in ['-', '+', 'x', 'o', 'O', '.', '*', '\\', '/'] ]
```

to increase the density of the hatch.

The default density looks like it has gone down (but should now be consistent across backends and dpi, see https://github.com/matplotlib/matplotlib/pull/7421 and http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#hatching).

A feature that we probably need to add is an rcParam to change the default density.

**Comment by tacaswell** [comment]
attn @QuLogic where is the hatch density set?

**Comment by tacaswell** [comment]
Pushing this to 2.2 because it requires adding configuration knobs to tune the hash size and density.

**Comment by Carreau** [comment]
Thanks @tacaswell, it's a good decision. I know it's tough to push things to later, but happy to see MPL 2.0 to be that close !

**Comment by QuLogic** [comment]
@tacaswell The density is applied in `hatch.py` from some default somewhere and a count of the number of specifiers used.

There are a lot of functions/methods that set a default value, but ultimately, the density is probably set from `path.py:Path.hatch`. This static method is directly called by the PDF and PS backends without a density, so it uses its default. The Agg backend uses `backend_bases.py:get_hatch_path`, but it doesn't pass a density either and uses the same default.

**Comment by oscargus** [comment]
Related to #20690
