### ISSUE TITLE
Can't open figure

### ISSUE THREAD

**Issue by shahen94** [matplotlib/matplotlib#7755]
**Bug summary**

I can't draw anything. it trays to open something but it closes immediately.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)
```

**Actual outcome**

It doesn't print something in console. it just doesn't opens

**Expected outcome**

Open Plot figure

Matplot version: 1.5.3
Python version: 2.7
OS: MacOS

I installed it with `pip`
```sh
$ pip install matplotlib
```

Thanks !

**Comment by tacaswell** [comment]
Are you running this as `python my_script.py`?

**Comment by shahen94** [comment]
@tacaswell yes, 
Also when i'm running
```python
matplotlib.test()
```

tests failed with errors like this
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/usr/local/lib/python2.7/site-packages/matplotlib/tests/__init__.py", line 18, in <module>
    'The baseline image directory does not exist. '
IOError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.
```

**Comment by jenshnielsen** [comment]
In that case you are not in interactive mode and you need to add a 

```
plt.show()
```
at the end of the script.

The error when running the tests are expected. Read what the last line says and that should explain it

**Comment by shahen94** [comment]
@jenshnielsen Thank you so much.
That helps !

I'm going to close this.
