### ISSUE TITLE
Cannot install the matplotlib 1.5.3 or 2.0.0rc2 on Mac OS Sierra, Python 3.6.0

### ISSUE THREAD

**Issue by jli05** [matplotlib/matplotlib#7756]
## Bug report

**Bug summary**

The macOS Sierra is updated to the latest version. We install matplotlib with Python 3.6.0. We have the latest XQuartz installed as well. matplotlib complains he cannot find header files for freetype2 although it's installed by XQuartz. 

**Code for reproduction**

Either

```bash
sudo -H pip3 install matplotlib
```

or

```bash
sudo -H pip3 install --global-option="build_ext" --global-option="-I/opt/X11/include/freetype2/" --global-option="-L/opt/X11/lib" matplotlib
```

**Actual outcome**

```
freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
...
                            * The following required packages can not be built:
                            * freetype
```

**Matplotlib version**

matplotlib 1.5.3 or 2.0.0rc2, macOS Sierra, XQuartz 2.7.11, Xcode 8.2.1, Python 3.6.0

**Comment by vindarmagnus** [comment]
Happened to me to, using homebrew.

**Comment by tacaswell** [comment]
Do you have pkgconfig installed?

Does it work if you set `expert MPLLOCALFREETYPE=1`?

**Comment by jli05** [comment]
I didn't have `pkgconfig` installed. I installed it, also tried to invoke `pip3` with or without `MPLLOCALFREETYPE=1`, and still get the same error.

**Comment by jli05** [comment]
The wheel build of Matplotlib 2.0.0 works with Python 3.6.0 on macOS Sierra.
