### ISSUE TITLE
matplotlib dynamic plotting

### ISSUE THREAD

**Issue by MpCamp** [matplotlib/matplotlib#7759]
Hi, after computer change, matplotlib don't work dynamically.
Before, it was able to update the figure at each iteration of a loop. Today only the last data are plotted.
Configuration : 
HP zBook 15 G3 with NVidia Quadro

###Bug report

**Bug summary**

A figure inside a loop are not updated at each step

**Code for reproduction**

```python3
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(128)
plt.figure(1)
plt.ion()
plt.hold(False)
for it in range(5):
    plt.plot(x, x+it)
    plt.draw()

plt.ioff()
plt.show()

```

**Expected outcome**

- I expect to see one plot at each step of the for loop

**Matplotlib version**
1.5.1

**Python version**
3.5.2

**OS**
Ubuntu 16.04 LTS

- All of them had been installed from Ubuntu repository using synaptic

**Comment by petehuang** [comment]
I think you may need to add `plt.pause(0.01)` after `plt.draw()` - can you try that?

**Comment by MpCamp** [comment]
Thank you very much Pete 

It works now ! 
It triggers an alarm, but it works : 
/usr/local/lib/python3.5/dist-packages/matplotlib/backend_bases.py:2437: 
MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented 
warnings.warn(str, mplDeprecation) 

Do you know why plt.pause() allows dynamic plots ? 




De: "Pete Huang" <notifications@github.com> 
À: "matplotlib/matplotlib" <matplotlib@noreply.github.com> 
Cc: "pierre campistron" <pierre.campistron@univ-valenciennes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 7 Janvier 2017 16:29:36 
Objet: Re: [matplotlib/matplotlib] matplotlib dynamic plotting (#7759) 



I think you may need to add plt.pause(0.01) after plt.draw() - can you try that?

**Comment by petehuang** [comment]
I'm entirely the wrong person to ask for the "why", but I'm glad it works! I just shuttled around StackOverflow for the answer :)

**Comment by tacaswell** [comment]
'why' is a bit of a long question (see https://github.com/matplotlib/matplotlib/pull/4779 for an old PR trying to document all of the details).  In very short, we made many of the GUI embedding more asynchronous, that is calling `plt.draw` calls `fig.canvas.draw_idle()` which asks the GUI to re-render the figure.  If you never turn control over to the GUI event loop to process it's events, then it does not have a chance to update it's self (you will also note that while your code is running you can not pan/zoom the figure).

Doing 

```python
import matplotlib.pyplot as plt
plt.ion()
import numpy as np

x = np.arange(128)
fig, ax = plt.subplots()

for it in range(5):
    ax.plot(x, x+it)
    # fig.canvas.draw_idle()  # required to work on mpl < 1.5
    fig.canvas.flush_events()
    time.sleep(1)

plt.ioff()
plt.show()
```

should do what you want.

**Comment by MpCamp** [comment]
Thank you very much Thomas 

It works perfectly, and I can zoom on figure during the loop ! 
I understand a little better now ;) 

Best regards 
Pierre 


De: "Thomas A Caswell" <notifications@github.com> 
À: "matplotlib/matplotlib" <matplotlib@noreply.github.com> 
Cc: "pierre campistron" <pierre.campistron@univ-valenciennes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 7 Janvier 2017 22:07:19 
Objet: Re: [matplotlib/matplotlib] matplotlib dynamic plotting (#7759) 



'why' is a bit of a long question (see #4779 for an old PR trying to document all of the details). In very short, we made many of the GUI embedding more asynchronous, that is calling plt.draw calls fig.canvas.draw_idle() which asks the GUI to re-render the figure. If you never turn control over to the GUI event loop to process it's events, then it does not have a chance to update it's self (you will also note that while your code is running you can not pan/zoom the figure). 

Doing 
import matplotlib.pyplot as plt
plt.ion() import numpy as np

x = np.arange( 128 )
fig, ax = plt.subplots() for it in range ( 5 ):
    ax.plot(x, x + it) # fig.canvas.draw_idle()  # required to work on mpl < 1.5 fig.canvas.flush_events()
    time.sleep( 1 )

plt.ioff()
plt.show() 


should do what you want.

**Comment by petehuang** [comment]
👍 

Should we close this?

**Comment by MpCamp** [comment]
Yes, I think that the problem is solved. 
Many thanks for all you 


De: "Pete Huang" <notifications@github.com> 
À: "matplotlib/matplotlib" <matplotlib@noreply.github.com> 
Cc: "pierre campistron" <pierre.campistron@univ-valenciennes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 8 Janvier 2017 17:40:22 
Objet: Re: [matplotlib/matplotlib] matplotlib dynamic plotting (#7759) 



👍 

Should we close this?

**Comment by maxgittelman** [comment]
Hey guys, any idea on how to fix my equivalent `MatplotlibDeprecationWarning`. I realized I essentially have the exact same problem except on a larger scale?

I have set up a server that will read in live data and produce two 3d plots. You can run this simulated code below (instead of reading in the data from the client).

```
import matplotlib.pyplot as plt
from threading import Thread, Lock, Condition
import random, time, socket
from mpl_toolkits.mplot3d import Axes3D
import numpy as np


class Plotter:
    def __init__(self):
        self.UDP_IP_ADDRESS = ''
        self.UDP_PORT_NO = 5007
        print "Server starting from port:", self.UDP_PORT_NO

        self.serverSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.serverSock.bind((self.UDP_IP_ADDRESS, self.UDP_PORT_NO))

        self.x_data = []
        self.y_data = []
        self.z_data = []

        # min, max
        self.x_min = self.y_min = self.z_min = 0
        self.x_max = self.y_max = self.z_max = 1
        self.update_x = self.update_y = self.update_z = False

        # threading variables
        self.mutex = Lock()
        self.points_received = 0
        self.cv = Condition()

        # initialize figure
        self.fig = plt.figure()
        self.num_plots = 1
        self.run_plot = False

    # This just simulates reading from a socket.
    def data_listener(self):
        while True:
            time.sleep(1)
            with self.mutex:
                x = random.random()
                y = random.random()
                z = random.random()
                self.x_data.append(x)
                self.y_data.append(y)
                self.z_data.append(z)

                # check max/min to update axes
                if x < self.x_min:
                    self.x_min = x
                    self.update_x = True
                elif self.x_max < x:
                    self.x_max = x
                    self.update_x = True
                if y < self.y_min:
                    self.y_min = y
                    self.update_y = True
                elif self.y_max < y:
                    self.y_max = y
                    self.update_y = True
                if z < self.z_min:
                    self.z_min = z
                    self.update_z = True
                elif self.z_max < z:
                    self.z_max = z
                    self.update_z = True

    def sub_plot(self, num):
        ax = self.fig.add_subplot(210+num, projection='3d')
        plt.ion()
        plt.show()

        # wait until ready, <Enter> is pressed
        self.cv.acquire()
        while not self.run_plot:
            self.cv.wait()              # I think this causes the plot to not respond before hitting <Enter>
        self.cv.release()

        while self.run_plot:
            time.sleep(0.01)
            with self.mutex:
                try:
                    # add data and clear graph
                    ax.scatter(self.x_data, self.y_data, self.z_data)
                    self.x_data = []
                    self.y_data = []
                    self.z_data = []
                    if self.update_x:
                        plt.gca().set_xlim(self.x_min, self.x_max)
                        self.update_x = False
                    if self.update_y:
                        plt.gca().set_ylim(self.y_min, self.y_max)
                        self.update_y = False
                    if self.update_z:
                        plt.gca().set_zlim(self.z_min, self.z_max)
                        self.update_z = False
                    plt.pause(0.000001)
                except:
                    print ("error")
        # Finish subplot
        self.num_plots += 1

    def cmdline_input(self):
        # Start then End Plot
        for status in ["start", "end"]:
            text_start = raw_input("Hit <Enter> to " + status + " plot " + str(self.num_plots))
            while text_start != "":
                print "Wrong input"
                text_start = raw_input("Hit <Enter> to " + status + " plot " + str(self.num_plots))

            self.cv.acquire()
            if status == "start":
                self.run_plot = True
            elif status == "end":
                self.run_plot = False
            self.cv.notify()
            self.cv.release()

    def run(self):
        d = Thread(target=self.data_listener)
        # t.daemon = True
        d.start()

        while self.num_plots < 3:
            # start cmdline input
            c_start = Thread(target=self.cmdline_input)
            c_start.start()

            # subplot
            self.sub_plot(self.num_plots)


if __name__ == '__main__':
    p = Plotter()
    p.run()
```

You guys have a better handle on how to fix this issue. Currently when I run the live plot (randomly sending over numbers), I can change the viewing angle with my cursor but I can't zoom in or out. I tried adding in `self.fig.canvas.flush_events()` after `plt.pause(0.000001)` but that didn't seem to functionally change anything.

I also noticed that when my plot isn't receiving live data, the window is unresponsive. I.e. If you try to maximize the window or change the window size the whole screen gets blurred. I have a feeling that this has something to do with me putting the plotting thread to sleep but maybe there's a simple fix?

**Comment by tacaswell** [comment]
This question is probably better sent to the mailing list (matplotlib-users@python.org ; you will have to subscribe to post).

https://github.com/matplotlib/matplotlib/pull/4779 may also be informative reading.
