### ISSUE TITLE
Different font size between math mode and regular text

### ISSUE THREAD

**Issue by fkbreitl** [matplotlib/matplotlib#7778]
Math text in matplotlib is rendered smaller than the regular text as show by

`ax.set_xlabel(r'Variable $\alpha$')`

Further details of this problem are discussed at

https://stackoverflow.com/questions/15836050/matplotlib-change-math-font-size

However the users need variables in math mode of same size as other text.

This should be the default.

I also discuss this problem at 

https://stackoverflow.com/questions/41555340/matplotlib-correct-math-font-size

**Comment by tacaswell** [comment]
What version of mpl are are you using?

**Comment by fkbreitl** [comment]
mpl.__version__ = '1.5.1'

**Comment by QuLogic** [comment]
In 1.5.3, this is because a different font is used for math:
![1 5 3](https://cloud.githubusercontent.com/assets/302469/21793666/45e1184a-d6c1-11e6-9a90-679c6dfb4b78.png)
In 2.0.0, the same font is used for both, so they are consistent:
![2 0 0](https://cloud.githubusercontent.com/assets/302469/21793679/73d3d36e-d6c1-11e6-9d75-203f1241bafb.png)

**Comment by fkbreitl** [comment]
Great. And is there a solution for earlier versions to use the same font, too?

**Comment by tacaswell** [comment]
Please see http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#math-text.  You just need to change the `mathtext.*` rcparams.

**Comment by fkbreitl** [comment]
But to what?
This links explains how to make matplotlib 2 behave like an earlier version.
But I am looking for the earlier version behaving like 2.

**Comment by tacaswell** [comment]
```
#mathtext.fontset : dejavusans # Should be 'dejavusans' (default),
                               # 'dejavuserif', 'cm' (Computer Modern), 'stix',
                               # 'stixsans' or 'custom'
```

from `matplotlibrc.template` on 2.x branch.  You will also need to install the font dejavu.

**Comment by tacaswell** [comment]
Actually, I am not strictly sure that will work, I have forgotten how much we had to change the internals of the math text code to support that.

**Comment by fkbreitl** [comment]
Unfortunately it doesn't:
> ValueError: Key mathtext.fontset: Unrecognized fontset string "dejavusans": valid strings are [u'custom', u'stix', u'cm', u'stixsans']

Although I have 'DejaVu Sans' installed and I can use it to replace the italic mathtext by
> plt.rcParams['font.sans-serif'] = 'DejaVu Sans'
> plt.rcParams['mathtext.default'] = 'regular'
But I want it italic.

But 'DejaVu Sans' gives the same error:
> ValueError: Key mathtext.fontset: Unrecognized fontset string "DejaVu Sans": valid strings are [u'custom', u'stix', u'cm', u'stixsans']

**Comment by tacaswell** [comment]
Yeah, sorry for misleading you :disappointed: 

It might be work to make the rest of your text cm?

**Comment by fkbreitl** [comment]
It would not be any work for me if it was possible. But 'cm' is not accepted for e.g. font.sans-serif.
