### ISSUE TITLE
Simple IndexError in artist.setp if empty list is passed

### ISSUE THREAD

**Issue by wielandbrendel** [matplotlib/matplotlib#7784]
An IndexError is raised in matplotlib.artist.setp if argument is an empty list,

```
import matplotlib
matplotlib.artist.setp([])
```

Arose in Seaborn jointplot example in their docs where minor_ticks was empty.

Ubuntu 16.04, Python 3.4.3 and Matplotlib 2.0.0rc2+2754.g8c5b548.

**Comment by tacaswell** [comment]
I can not reproduce this on 2.x, but can on master.

Exact work:

 - add short-ciruit return path to `matplotlib.artist.setp` if the input is length 0
