### ISSUE TITLE
Quiver barb size not correct on some arches (ppc64, ppc64le...)

### ISSUE THREAD

**Issue by AdamWill** [matplotlib/matplotlib#7797]
Continuing to work through test suite failures found when building on the Fedora ppc64 arch (big-endian) but not on little-endian arches. Two failures:

matplotlib.tests.test_quiver.test_barbs.test
matplotlib.tests.test_transforms.test_pre_transform_plotting.test

seem to be caused by differences in the lengths of 'barbs' on 'quivers' - the former is a test specific to such barbs, the latter includes a figure with some barbs as part of a larger test. In both cases, the lengths of the barbs come out subtly differently on ppc64:

barbs_test_image GOT: ![barbs_test_image](https://cloud.githubusercontent.com/assets/916551/21831207/edeaf426-d756-11e6-8647-cd6b6f9f6a93.png)
barbs_test_image EXPECTED: ![barbs_test_image-expected](https://cloud.githubusercontent.com/assets/916551/21831205/ede8ebb8-d756-11e6-8c99-692fce6eac8c.png)
pre_transform_data GOT: ![pre_transform_data](https://cloud.githubusercontent.com/assets/916551/21831204/ede871ce-d756-11e6-8d5b-526c642182ff.png)
pre_transform_data EXPECTED: ![pre_transform_data-expected](https://cloud.githubusercontent.com/assets/916551/21831206/ede9dad2-d756-11e6-9cd1-360119b06076.png)

the difference is quite subtle, it helps to A/B the images quickly in an image viewer. AFAICS, in all cases where the lengths are visibly different, the barbs actually produced are slightly shorter than expected.

**Comment by AdamWill** [comment]
@QuLogic @tacaswell

**Comment by AdamWill** [comment]
This may be https://github.com/matplotlib/matplotlib/issues/4385 ?

**Comment by AdamWill** [comment]
This also affects ppc64le, so it's not a big-endian thing. It may also affect aarch64.

**Comment by dopplershift** [comment]
I don't think #4385--that's a different rounding problem, IMO. It looks like some kind of pixel snapping issue to me.

I don't have a clue how to begin to figure out what's going on here without access to a machine...

**Comment by AdamWill** [comment]
@puiterwijk ahoy! would you be willing to let an upstream matplotlib person have access to one of our sandbox ppc64 or aarch64 environments to try and look into this kinda thing?

**Comment by puiterwijk** [comment]
@AdamWill You can add their key to your test instance, and let them use that?

**Comment by AdamWill** [comment]
I thought you'd already torn it down :) If you don't mind leaving it up a while longer, sure. @dopplershift , can you send me your ssh pubkey?

**Comment by dopplershift** [comment]
Sorry, I've been swamped with conference prep. It will probably be no earlier than the 21st/22nd that I might be able to get to this. Not sure if that time frame works for you guys.

**Comment by AdamWill** [comment]
I don't think it should be a problem, we should still be able to put up an instance for you at that time, I think.

**Comment by puiterwijk** [comment]
@AdamWill I'll keep your current instance around. Just let me know when I can clear it after they're done with it.

**Comment by dopplershift** [comment]
@AdamWill Ok, I've got cycles now. Here's the public key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxtEykVuf26l7WVrYnvzVWmKdM2a4IBtH0O6wRqPBbG6+/ABmx+YZ+gF63Ry0ylZ9AXhJslUFxkSnuk8X1HjlXc19fyoJTWnAWVF2kNyJj+fUC095dExI5DBCVqtA/34tKBX/FXHr90Nbb7eiUK0v3pjwo1H34ATq0ggeTur/Gj3pEhk5fg+EtsESv2WFIbofQUWN7d7nHxLTNwF45JNacl8BK2McnclVhg+qVHf91vK+x7vqHRi/biHm2NT9fojlOvfC6q/wmCKzZkQ6H2uI9A6RzrlKWpx0HibgRkNHh0bBKvSRpKHKVHBcZLz/J+YHMZ4Sb5Pf7hKXsqRfMb8uX rmay
```

**Comment by AdamWill** [comment]
sorry, I kinda lost track of these remaining issues; did I ever set you up with the appropriate access, @dopplershift ? If not, should we try another round?

**Comment by dopplershift** [comment]
Not that I'm aware of. I have a few cycles I can use to look at this.

**Comment by AdamWill** [comment]
same pubkey?

**Comment by dopplershift** [comment]
Yes.

**Comment by AdamWill** [comment]
@puiterwijk could you possibly spin up a sandbox ppc64 instance for @dopplershift to use, with the pubkey given above? thanks!

**Comment by AdamWill** [comment]
@dopplershift ok, you should be able to ssh to `fedora@209.132.184.129` with that ssh key now, and you can sudo without a password if you need root access. Let us know if that doesn't work out for you.

**Comment by dopplershift** [comment]
It's working...hoping to be able to give this a look tomorrow.

**Comment by dopplershift** [comment]
Ok, so far what I can say is that barbs itself isn't producing different polygon vertices on ppc64, which means that this actually happens somewhere in the Agg layer...sigh.

**Comment by dopplershift** [comment]
Not sure I have cycles to keep digging. Anyone from matplotlib feel like digging into a weird Agg rendering difference?

**Comment by tacaswell** [comment]
Did you look at the verts before or after running through all of the path simplification code?

**Comment by dopplershift** [comment]
Before. I may not know enough about the path simplification code, but the differences we're seeing aren't coming from *dropping* a vertex.

**Comment by tacaswell** [comment]
miss interpretting LE/BE tends to have catastrophic effects, I'm quite puzzled by this.  There are some issues with float128 on ppc64 (see https://github.com/h5py/h5py/pull/842/files) I wonder if this is related (I hope not!)?

attn @sandrotosi do you see these with debian too?

**Comment by AdamWill** [comment]
Note this is definitely *not* an LE / BE thing, per the comment on January 10. It also affects ppc64le.

**Comment by tacaswell** [comment]
Sorry, did not read carefully enough :sheep:

**Comment by QuLogic** [comment]
After a few days of trial and error, I think I've found the problem. It seems to originate in the [Agg `cross_product` function](https://github.com/matplotlib/matplotlib/blob/master/extern/agg24-svn/include/agg_math.h#L36-L42). You can see the difference in [this gist](https://gist.github.com/QuLogic/90fcf703b1974a22b4127d48cebdee83) where I ran a few sample inputs from the broken test. The inputs are bit-for-bit identical between x86 and ppc at the start of `cross_product`, but only the first test case outputs the same result. The second and third tests are slightly less and slightly greater than the expected 0.

Interestingly, this difference only happens with _both_ `-O2` and `-fPIC` (which are both part of Fedora flags). I wonder if that qualifies as a gcc bug?

The slightly negative result is okay, but the slightly positive result triggers the wrong side of [this check](https://github.com/matplotlib/matplotlib/blob/master/extern/agg24-svn/include/agg_math_stroke.h#L394), meaning the stroking uses an inner join instead of an outer join, resulting in a couple fewer vertices. If this condition is changed to use some epsilon check, then ppc should work (though I'd need to see whether it breaks anything else.)

**Comment by QuLogic** [comment]
For now, I'm not sure if we should import the changes here, as it causes a few test failures on x86_64. I've opened [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1502499) to see if there's anything up with gcc itself as the trigger is a bit odd to me.

**Comment by QuLogic** [comment]
gcc devs say this is an expected optimization ([FMA](https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation#Fused_multiply%E2%80%93add)), so I'm going to open a PR with the patch here.

**Comment by AdamWill** [comment]
Thanks a lot for figuring this out, folks!
