### ISSUE TITLE
Basemap uses deprecated methods

### ISSUE THREAD

**Issue by perimosocordiae** [matplotlib/matplotlib#7808]
I'm not sure who maintains basemap, or where the development takes place, but hopefully this gets routed to someone who knows.

With the current master branch of matplotlib and a fresh install of basemap-1.0.7, I trigger the following deprecation warnings:
```python
from mpl_toolkits.basemap import Basemap
m = Basemap()

m.fillcontinents()
#/usr/local/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.py:1767: MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.
#  axisbgc = ax.get_axis_bgcolor()

m.scatter([1,2], [3,4])
#/usr/local/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.py:3222: MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
#  b = ax.ishold()
#/usr/local/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.py:3231: MatplotlibDeprecationWarning: axes.hold is deprecated.
#    See the API Changes document (http://matplotlib.org/api/api_changes.html)
#    for more details.
#  ax.hold(b)
 ```

**Comment by efiring** [comment]
`hold` has been taken care of, but not `get_axis_bgcolor`, so thanks for the report.  I will open an issue on the basemap tracker, so this one can be closed.

**Comment by efiring** [comment]
Correction: get_axis_bgcolor is also being handled in basemap master, so I think all we need is a release to go with mpl v2.0.

**Comment by WeatherGod** [comment]
correct. that is the plan.

**Comment by roxyboy** [comment]
Has this fix already been released?

**Comment by WeatherGod** [comment]
Yes, the v1.1.0 release that is available on conda-forge. I have not
bothered with releasing basemap to pypi, which is why it still has v1.0.7.

**Comment by manojkken** [comment]
Any idea when this can be released?

**Comment by naught101** [comment]
You can use it now with `conda install -c conda-forge basemap`.

Basemap bugtracker is at https://github.com/matplotlib/basemap/issues

**Comment by gpetty** [comment]
Almost a year later, 'conda install basemap' still installs v1.0.7, which still throws an error when it tries to access ax.get_axis_bgcolor in matplotlib.  Why hasn't v1.10 propagated to Anaconda yet?

**Comment by WeatherGod** [comment]
I don't control what anaconda puts out. I tagged v1.1.0 over a year ago, I
don't know who to tell over at anaconda to update their packages. In the
meantime, the recommended way to install basemap is through conda-forge.

**Comment by efiring** [comment]
Ben, the problem is that even v1.1.0 fails on mpl 3.0, so a new release is needed.  conda-forge will automatically update their package when a release is tagged.  (ref. #424)

**Comment by WeatherGod** [comment]
Ok, I just quickly pulled together a commit and tagged v1.2.0rel off of
master. Let's see what happens.
