### ISSUE TITLE
Legend for lines created using `LineCollection` show different handle line scale.

### ISSUE THREAD

**Issue by pmreyes2** [matplotlib/matplotlib#7814]
### Legend for lines created using `LineCollection` show different handle scale as lines in the plot

When using `LineCollection` there is a mismatch of the line scales in the plot an the lines of the handle in the legend.

```python
lines1 = [[(0, .5), (.5, 1)], [(.3, .6), (.2, .2)]]
lines2 = [[[0.7, .2], [.8, .4]], [[.5, .7], [.6, .1]]]
lc1 = matplotlib.collections.LineCollection(lines1, linestyles="--")
lc2 = matplotlib.collections.LineCollection(lines2, linestyles="-.")
fig, ax = plt.subplots()
ax.add_collection(lc1)
ax.add_collection(lc2)
ax.legend([lc1,lc2],["line1","line2"])
```
![fig_2 0 0rc2](https://cloud.githubusercontent.com/assets/3052100/21912195/0b210e06-d8ea-11e6-8eca-1c61bd21a1a8.png)

A workaround found by [Goyo](http://stackoverflow.com/users/2142055/goyo) in the answer for [stackoverflow question](http://stackoverflow.com/questions/41620876/how-to-fix-line-size-in-the-legend-to-match-lines-in-a-plot-that-uses-linecolle) was to turn off `scale_dashes`:

```python
classic_dashes = {
    'lines.dashdot_pattern': [5, 4, 2, 3],
    'lines.dashed_pattern': [6, 6],
    'lines.scale_dashes': False
}

with plt.rc_context(classic_dashes):
    lines1 = [[(0, .5), (.5, 1)], [(.3, .6), (.2, .2)]]
    lines2 = [[[0.7, .2], [.8, .4]], [[.5, .7], [.6, .1]]]
    lc1 = matplotlib.collections.LineCollection(lines1, linestyles="--", linewidths=2)
    lc2 = matplotlib.collections.LineCollection(lines2, linestyles="-.", linewidths=2)
    fig, ax = plt.subplots()
    ax.add_collection(lc1)
    ax.add_collection(lc2)
    ax.legend([lc1,lc2],["line1","line2"])
```

![workaround](https://cloud.githubusercontent.com/assets/3052100/21912337/e997254e-d8ea-11e6-9afb-acf5ef44475e.png)

**Matplotlib version**

- The matplotlib version used is 2.0.0rc2+2995.gd7879bc
- When using old matplotlib version 1.5.3 which doesn't have `scale_dashes` activated, there is no scaling problem between legend and plot lines.

**Comment by tacaswell** [comment]
Contra to my previous comment, I have a different and likely much better theory.  I think what is happening is that we are pulling the (scaled) dash pattern from the line collection and then scaling it _again_ in the legend.

**Comment by tacaswell** [comment]
@pmreyes2 Thanks for finding this regression!
