### ISSUE TITLE
re-enable or delete xmllint tests

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7816]
Disabled in 2daf9f5892fb9d44f69849e01985b90dfabb8be6 in 2009.  We should either get this running again delete it altogether.

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/testing/compare.py#L213

attn @anntzer and @Kojoley

**Comment by anntzer** [comment]
I would get rid of it, together with the (now unused) verifier machinery.  I don't think there's much of a point in xmllint'ing the code if we're going to let inkscape convert it to png anyways (if the file is invalid, inkscape will catch it -- plus that'd be one more external dependency for running the tests).

Did I get mentioned just because this involves *deleting more code*? :p

**Comment by tacaswell** [comment]
@anntzer Yes :smiling_imp: 

Will inkscape 'patch over' slightly invalid svg?  Is it worth investigating how to make it stricter if it does?

**Comment by anntzer** [comment]
I have no idea, but looking at it again I'd say "interpretable by inkscape" (which is quite a small subset of all possible xml documents) is more valuable than "being valid svg" anyways (I know that not a strong argument to drop the xmllinting)...

**Comment by tacaswell** [comment]
Given our previous discussions with folks about the validity of the svg documents we produce (putting the clip path _after_ its first reference) and the failure of some svg renderers to properly render them (librsvg), sticking to 'proper svg' as per the spec is preferable to picking a particular renderer.

**Comment by anntzer** [comment]
Then we should reactivate the tests instead...
A semirandom guess regarding the multiprocessing issues (not that I'd want to try reproducing them) is that multiple xmllint processes could be trying to fetch the dtd at the same time.  Perhaps the internet connection doesn't like that, or they all try to write to the same temporary place...
