### ISSUE TITLE
Figure.savefig() not respecting bbox_inches='tight' when dpi specified

### ISSUE THREAD

**Issue by kiwirob** [matplotlib/matplotlib#7820]
**Bug summary**

`Figure.savefig()` with `bbox_inches='tight'` and PNG output is incorrectly clipping text annotations when a `dpi` argument is passed. When no `dpi` argument passed, `bbox_inches='tight'` functions as expected. 

**Python version**:
`Python 3.5.2 |Anaconda 4.1.1 (32-bit)| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)]`
Using matplotlib version 1.5.3

**Example**

```python
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df = pd.read_csv('http://www.who.int/childgrowth/standards/wfa_boys_p_exp.txt', sep='\t', index_col=0)

DAYS_IN_MONTH = 30.4375
DAYS_IN_YEAR = DAYS_IN_MONTH * 12

percentile_list = []

for i in range(7):
    percentile_list.append((tuple(df.columns[[3 + i,17 - i]])))

df.index = df.reset_index()['Age'].div(DAYS_IN_MONTH)
df = df.loc[df.index < 12]

fig, ax = plt.subplots()
df['P50'].plot(ax=ax, color='w')

x = df.index

color_list = sns.color_palette("Blues", len(percentile_list))

for i, j in enumerate(percentile_list):    
    y1 = df[j[0]]
    y2 = df[j[1]]
    ax.fill_between(x, y1, y2, color=color_list[i])

text_annotations= []

for i in df.columns[3:]:
    annotation = ax.annotate(i, xy=(12, df.loc[:,i].iloc[-1]),  
                             xytext=(5,0), textcoords="offset points",
                             va="center", ha="left", size=8)
    text_annotations.append(annotation)

fig.savefig('weight_chart.png', bbox_inches='tight')
fig.savefig('weight_chart_dpi.png', bbox_inches='tight', dpi=300)
```

**weight_chart.png**
![weight_chart](https://cloud.githubusercontent.com/assets/4974928/21929967/690d2364-d98b-11e6-85df-71bcc1dec6ec.png)

**weight_chart_dpi.png**
![weight_chart_dpi](https://cloud.githubusercontent.com/assets/4974928/21929976/76870d8e-d98b-11e6-99b5-f9bb506fc2f0.png)

**Comment by kiwirob** [comment]
Not a bug.  Requires 

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.annotate

**Comment by tacaswell** [comment]
Can you reproduce this with a simpler example (no pandas or sns)?

**Comment by kiwirob** [comment]
Hi,

Thanks for prompt response - Simpler example with no pandas or seaborn below. Problem does not reproduce (i.e. no clipping of annotations outside axes when dpi argument set). Looks like it must be caused by funky interaction with pandas or seaborn somewhere. I'll close this issue.

**Example**
```python
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([1,2,3], [1,2,3])

ax.annotate('annotation 1', xy=(3,1.5))
ax.annotate('annotation 2', xy=(3,2.5))

fig.savefig('chart.png', bbox_inches='tight')
fig.savefig('chart_dpi.png', bbox_inches='tight', dpi=300)
```
**chart.png**
![chart](https://cloud.githubusercontent.com/assets/4974928/21937669/243668fc-d9b0-11e6-8697-670dba5dce12.png)

**chart_dpi.png**
![chart_dpi](https://cloud.githubusercontent.com/assets/4974928/21937677/29a4a8bc-d9b0-11e6-9b04-24da4bb34df7.png)
