### ISSUE TITLE
Split docs for postscript distill rc out of latex docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7846]
I believe that currently, the only docs regarding the ps distilling options are part of the "text rendering with latex" docs.  Given that the ps backend can perfectly well be used without `usetex=True`, it may make sense to split these docs out, or at least make them a tiny bit more prominent.
That section should also note that distilling depends (I think) on ghostscript (which was probably not noted in the current version as ghostscript is a general requirement for `usetex=True`, but once again it is also a requirement just for distilling mathtext text.

**Comment by efiring** [comment]
One possible area of confusion to address is that ghostscript is required even when the `rcParams['ps.distiller'] = 'xpdf'`.
