### ISSUE TITLE
Update dependencies in the docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7858]
http://matplotlib.org/devdocs/users/installing.html#optional-gui-framework lists

> tk 8.3 or later, not 8.6.0 or 8.6.1
> The TCL/Tk widgets library used by the TkAgg backend.
> 
> Versions 8.6.0 and 8.6.1 are known to have issues that may result in segfaults when closing multiple windows in the wrong order.
> 
> pyqt 4.4 or later
> The Qt4 widgets library python wrappers for the Qt4Agg backend

--> "Qt4 or Qt5"

> pygtk 2.4 or later
> The python wrappers for the GTK widgets library for use with the GTK or GTKAgg backend

--> or pygobject for gtk3 (which is the only existing option on Py3).  Also pycairo/cairocffi.
(Basically copy from http://matplotlib.org/devdocs/faq/usage_faq.html#what-is-a-backend.)

> wxpython 2.8 or later
> The python wrappers for the wx widgets library for use with the WX or WXAgg backend

**Comment by matthew-brett** [comment]
I wonder whether we should change the Tk instructions to point out that they need python-tk or similar.

**Comment by Amrithasuresh** [comment]
> tk 8.3 or later, not 8.6.0 or 8.6.1
The TCL/Tk widgets library used by the TkAgg backend.

> Versions 8.6.0 and 8.6.1 are known to have issues that may result in segfaults when closing multiple windows in the wrong order.

> pyqt 4.4 or later
The Qt4 widgets library python wrappers for the Qt4Agg backend.

> Qt4` or `Qt5`
#### Do I need to write definitions under "Qt4` or `Qt5`"  or should I leave it blank?

> pygtk 2.4 or later
The python wrappers for the GTK widgets library for use with the GTK or GTKAgg backend

-------------

#### I didn't quite understand. Can you please explain second comment "pygobject for gtk3". I tried like below. 

> GTK3Agg	
Agg rendering to a GTK 3.x canvas (requires PyGObject and pycairo or cairocffi)

> GTK3Cairo	
Cairo rendering to a GTK 3.x canvas (requires PyGObject and pycairo or cairocffi)


Thank you for your time.

**Comment by tacaswell** [comment]
@Amrithasuresh Sorry for us not getting an answer to you until now!

I'm actually not sure about merging the Qt4 and Qt5 lines, they are different underlying libraries.

The support for the gtk bindings and python3 has not been as smooth as Qt or Tk and the you have to change the python library for handling the bindings between py2/py3.  I think the details around that are what @anntzer is referring to?  This might require a bit of research, I do not know the details of this off the top of my head!

**Comment by anntzer** [comment]
I'm pretty sure everything is covered at http://matplotlib.org/tutorials/introductory/usage.html#what-is-a-backend now (and the first link doesn't exist anymore).
TBH I also think that part should be moved out of the introductory tutorial...

**Comment by anntzer** [comment]
The info is up to date now.
