### ISSUE TITLE
widget radio buttons and check buttons no longer display outlines

### ISSUE THREAD

**Issue by tmdavison** [matplotlib/matplotlib#7860]
### Bug report

**Bug summary**

Widget radio buttons and check boxes no longer have outlines in the 2.0.0 release, presumably because with the new style changes: "Most artists drawn with a patch no longer have a black edge by default."

**Code for reproduction**

This can be demonstrated with the widgets example codes:

http://matplotlib.org/examples/widgets/radio_buttons.html
http://matplotlib.org/examples/widgets/check_buttons.html

**Actual outcome**

The buttons are created, and can be clicked on, but you have to guess where they are.

![radio_buttons](https://cloud.githubusercontent.com/assets/15687857/22040982/ee3d4bbc-dcfc-11e6-8a24-d51a7094d6a5.png)

![check_buttons](https://cloud.githubusercontent.com/assets/15687857/22040983/ee41043c-dcfc-11e6-94b7-bb48ead8eb09.png)

**Expected outcome**

Buttons should be visible. This worked in the 1.5.x releases.

**Matplotlib version**

- Matplotlib version = 2.0.0
- Python version = 2.7.12
- Platform = MacOS 10.12

- Matplotlib installed via pip

**Comment by dopplershift** [comment]
I was able to reproduce this locally on osx. Most like caused by the change to edgecolor, or whatnot. I'd expect this to be pretty simple.
