### ISSUE TITLE
add link to scipython book

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7877]
http://scipython.com/book/chapter-7-matplotlib/ has a nice collection of mpl examples, we should link to it in the docs.

**Comment by y3l2n** [comment]
Is this just finding an appropriate place in the documentation for the link?

http://matplotlib.org/devdocs/examples/index.html

maybe creating a new section in ^^ this website for "external examples"?

**Comment by story645** [comment]
I'm almost tempted to vote against this in a yeah it's useful...but man scope creep. What about a section at the bottom of http://matplotlib.org/users/tutorials.html for external tutorials?

**Comment by tacaswell** [comment]
Definitely see the argument in favor of better curation over sheer volume.  Despite opening the issue, I am only +0.5 on this.

**Comment by story645** [comment]
I'm squishy on this 'cause everyone learns differently so variety is good, but most of these resources basically take the same approach to teaching the topic. *shrugs*

**Comment by jacob-on-github** [comment]
Went ahead and opened a pull request for this issue, feel free to close it if that is the decision you make.

**Comment by afvincent** [comment]
@story645 After a quick glance, it seems to me that the SciPython book chapter presents examples that are rather different from the ones in the others links I was able to get access to in the “External Ressources” section.
