### ISSUE TITLE
Regression: imshow on geo axes produces an empty plot in matplotlib 2.0.0

### ISSUE THREAD

**Issue by lpsinger** [matplotlib/matplotlib#7903]
**Bug summary**

In Matplotlib 1.5.3, it was possible to use `imshow` on geo axes (e.g. the mollweide projection defined in `matplotlib.projections.geo`. In Matplotlib 2.0.0, this produces a blank plot.

**Code for reproduction**

Here is an example that worked in 1.5.3.

```python
from matplotlib import pyplot as plt
import numpy as np

lon = np.linspace(-np.pi, np.pi)
lat = np.linspace(-np.pi/2, np.pi/2)
lon, lat = np.meshgrid(lon, lat)

ax = plt.axes(projection='mollweide')
ax.grid()
ax.imshow(lon, extent=[-np.pi, np.pi, -np.pi/2, np.pi/2], aspect=ax.get_aspect())
plt.savefig('test.png')
```

**Actual outcome**

This is the output on Matplotlib 2.0.0: blank axes.
![test-2 0 0](https://cloud.githubusercontent.com/assets/728407/22172767/f2348f18-df7d-11e6-9f6d-0f15a1ca1d75.png)

**Expected outcome**

This was the output in Matplotlib 1.5.3.
![test-1 5 3](https://cloud.githubusercontent.com/assets/728407/22172765/eb9b1f28-df7d-11e6-90e0-90c6098b04e1.png)

**Matplotlib version**

Installed from MacPorts on OS X 10.11.6 "El Capitan". Port versions:
- `py27-matplotlib @1.5.3_0+cairo`
- `py27-matplotlib @2.0.0_0+cairo`

**Comment by efiring** [comment]
It appears that in 1.5.3 the image was being created in Cartesian coordinates and then clipped to the projection.  Is this what you want?

**Comment by lpsinger** [comment]
Yes.

**Comment by efiring** [comment]
That seems like fundamentally incorrect behavior, doesn't it?  Wouldn't most users expect that if anything, imshow with a projection would warp the image to that projection?  It's never done that, though.  In 2.0 its behavior with a log scale on one or both axes has changed so that it does map the image to the scale, but I think that its behavior with a non-affine projection has always been undefined.  If so, it should raise an error.  Alternatively, I suppose it could warn and drop back to the 1.5.x behavior.  Comments, @mdboom?

**Comment by lpsinger** [comment]
I was looking through past PRs... did this change occur in #5718?

**Comment by WeatherGod** [comment]
yes, that is the rework that Eric is referring to.

**Comment by lpsinger** [comment]
Oh, OK! I modified my test code to use `ax.imshow(..., extent=[0, 1, 0, 1], transform=ax.transAxes)`:

```python
#!/usr/bin/env python
from matplotlib import pyplot as plt
import numpy as np

lon = np.linspace(-np.pi, np.pi)
lat = np.linspace(-np.pi/2, np.pi/2)
lon, lat = np.meshgrid(lon, lat)

ax = plt.axes(projection='mollweide')
ax.grid()
ax.imshow(lon, extent=[0, 1, 0, 1], aspect=ax.get_aspect(), transform=ax.transAxes)
plt.savefig('test.png')
```

And it works now:

![test](https://cloud.githubusercontent.com/assets/728407/22225174/75d83c8a-e18f-11e6-9e7f-0978f66e30b5.png)

**Comment by lpsinger** [comment]
> Oh, OK! I modified my test code to use ax.imshow(..., extent=[0, 1, 0, 1], transform=ax.transAxes):

Was this just a latent bug in my own code that was revealed by the transition to 2.0.0? If so, then we can close this issue.
