### ISSUE TITLE
font_manager.get_fontconfig_fonts() reports a single item of all fonts concatenated

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#7906]
as reported on Debian as http://bugs.debian.org/852060:

```
While using matplotlib to list installed files in a python3 script:
font_manager.get_fontconfig_fonts(),
the list I get has only one element, that contains all fonts names concatenated.

I've tried replacing
out = subprocess.check_output([str('fc-list'), '--format=%{file}'])
on line 284 by:
out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
and that works.
```

I can confirm this happens on both py2 and py3

do you think that's the right approach or is there a better way to fix this issue? thanks!

**Comment by jkseppan** [comment]
Yes, I think including the newline in the format string is correct. It seems that we used to do that but accidentally lost the newline in #7596.
