### ISSUE TITLE
plt.show doesn't warn if a non-GUI backend is being used

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7908]
If a non-GUI background is being used, and `plt.gcf().show()` is called it raises the warning

```
/Users/dstansby/matplotlib/lib/matplotlib/figure.py:402: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```

However, calling `plt.show` does not raise this warning, and just silently doesn't show anything. I would expect at least the same warning to be raised.

**Comment by anntzer** [comment]
The warning could perhaps be moved to FigureManagerBase.show -- currently, this implementation raises a NonGuiException, only for the purposes of it being catched and replaced by a warning in Figure.show.  Interactive backends all override FigureManagerBase.show.
