### ISSUE TITLE
matplotlib doesn't work  with numpy+mkl

### ISSUE THREAD

**Issue by ArtGenesis** [matplotlib/matplotlib#7912]
When launch simple script in python IDLE, nothing happens, script exit with no error
when launch in win.promt have error : Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll

import matplotlib.pyplot as plt
plt.scatter([0, 1 ], [0 , 1 ])
plt.show()

then i deleted numpy-1.12.0+mkl, and install simple numpy, and all work fine

uninstall matplotlib and numpy, then installed numpy-1.12.0+mkl and matplotlib, doesn't work
pip install matplotlib and simple numpy, numpy-1.12.0+mkl from .whl
Python 3.4.4, latest version matplotlib and numpy,  win xp 32

**Comment by story645** [comment]
did you check that just numpy works?

**Comment by ArtGenesis** [comment]
`did you check that just numpy works?`
simple numpy and numpy+mkl works well,
but when installed numpy+mkl, matplotlib doesn't work

**Comment by tacaswell** [comment]
Where did you get the wheels from? This looks like linking conflict.

**Comment by ArtGenesis** [comment]
numpy+mkl wheels from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy+
so I tried also uninstall python3.4 and install WinPython 3.4.4.5Qt5 from http://winpython.github.io/ , same problem

**Comment by tacaswell** [comment]
attn @cgohlke Sorry to bother you with this :disappointed:

**Comment by cgohlke** [comment]
Intel MKL 11.3, which is used by numpy+mkl for Python >= 3.4, does not support Windows XP.

**Comment by ArtGenesis** [comment]
Thanks to all, tried on win7 everything is working,
Sorry for disturbing  :(

**Comment by NelleV** [comment]
FYI, that really sounds like a conda problem. Did you install numpy and python using conda?

**Comment by NelleV** [comment]
Sounds like not :)
I am closing the issue.
