### ISSUE TITLE
~/.matplotlib/matplotlibrc not being read

### ISSUE THREAD

**Issue by highpost** [matplotlib/matplotlib#7919]
### Bug report

**Bug summary**

~/.matplotlib/matplotlibrc is not being read

**Code for reproduction**
I have a matplotlibrc file with a single entry:

backend: qt5agg

This worked fine until I recently upgraded to both Python 3.6 and matplotlib 2.0. I had been using matplotlib 2.0 rc1 without a problem. But now matplotlib is not reading this startup file and I'm forced to specify qt5agg in my Python code.

**Actual outcome**

import matplotlib
matplotlib.matplotlib_fname()
'/home/dan/scipydev/venv/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc

**Expected outcome**

import matplotlib
matplotlib.matplotlib_fname()
'/home/dan/.matplotlib/matplotlibrc

**Matplotlib version**
matplotlib 2.0
virtual environment
Python 3.6
Ubuntu 16.04.1 LTS.

installed with pip into the virtual environment

**Comment by QuLogic** [comment]
The file path should be `~/.config/matplotilb/matplotlibrc`. See [the FAQ](http://matplotlib.org/faq/troubleshooting_faq.html#locating-matplotlib-config-dir).

You should have seen a warning about this old path with 2.0.0 rc1 and it has been there since 1.4.0.

**Comment by highpost** [comment]
Thanks. I did look, but (ahem) I didn't see the FAQ.
