### ISSUE TITLE
Text rendered with MathText looks really ugly (version 2.0 vs. 1.5)

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#7921]
It seems that matplotlib version 2.0.0 does not render MathText correctly.

In matplotlib 2.0.0 as can be seen from the [documentation of MathText](http://matplotlib.org/users/mathtext.html#example) the text rendered with MathText looks **really ugly**:
![Matplotlib 2.0.0 mathtext example](http://matplotlib.org/_images/pyplot_mathtext.png)

In matplotlib 1.5 we have the following image for the same code (also see the [old documentation](http://matplotlib.org/1.5.3/users/mathtext.html?highlight=writing%20mathematical%20expressions#example)), which looks the way it should.

![Matplotlib 1.5 mathtext example](http://matplotlib.org/1.5.3/_images/pyplot_mathtext.png)

Is this intentional? Can it be turned back?

**Comment by jkseppan** [comment]
Beauty or ugliness is subjective, but I think you are noticing the change in default fonts. See http://matplotlib.org/users/whats_new.html#change-in-default-font for how to change the mathtext fonts back to the old default.

**Comment by ImportanceOfBeingErnest** [comment]
For anyone to come across this: 
The above means that the old nice fonts can be restored by inserting
`plt.rc('mathtext', fontset="cm")` just below the pyplot import in [the example](http://matplotlib.org/users/mathtext.html#example).

**Comment by jdhao** [comment]
This style is changed in Matplotlib version 2.0.  see [here](https://matplotlib.org/users/dflt_style_changes.html#math-text).  To revert to old style:
```
mpl.rcParams['mathtext.fontset'] = 'cm'
mpl.rcParams['mathtext.rm'] = 'serif'
```

**Comment by dfrodriguezp** [comment]
You weren't the only one who thought the new font was ugly. I was looking for this solution. Thank you!
