### ISSUE TITLE
Python 3.6 deprecated escape sequences.

### ISSUE THREAD

**Issue by Carreau** [matplotlib/matplotlib#7924]
Python 3.6 has [deprecated](http://bugs.python.org/issue27364) invalid [backslash-pairs](https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior):

> A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError,[...]

Matplotlib is full of these in docstrings and regular expressions.

Python right now try to do the right things and "magically" inserting an extra `\` but this can be a sign of a latent bug.

I would suggest to turn the test suite to make these warnings visible and slowly start to fix it, eventually turning this into an error (on 3.6 and above) to make sure more are not injected.

**Comment by anntzer** [comment]
Closed by #7925 (and others).
