### ISSUE TITLE
[Bug] backend_bases.key_press_handler sneakily uses digit keys

### ISSUE THREAD

**Issue by kawing-chiu** [matplotlib/matplotlib#7928]
**Bug summary**

- [`backend_bases.key_press_handler()`](https://github.com/matplotlib/matplotlib/blob/v2.0.x/lib/matplotlib/backend_bases.py#L2571) listens and reacts to digit keys sneakily, which causes conflict to user code that is also using digit keys (which is confusing and hard to debug). This behavior is not documented at all and config option is not provided to disable it (i.e. there is no equivalent to `rcParams['keymap.pan'] = ''` for digit keys.

**Matplotlib version**

- Matplotlib 1.5.x/2.0.0, Python 3.6.0 on Arch linux.

**Comment by QuLogic** [comment]
These were removed in  #19796 after being deprecated in 3.3.
