### ISSUE TITLE
y-axis label no longer obeys x position in 2.0

### ISSUE THREAD

**Issue by robroc** [matplotlib/matplotlib#7946]
Using matplotlib with Seaborn's FacetGrid. Before upgrade to 2.0, setting the x,y position of the y-axis label worked. Now only y-position is respected.

```python

import seaborn as sns
import matplotlib.pyplot as plt

g = (sns.FacetGrid(df, col="prenom", hue="sexe", col_wrap=3, size=3, sharey=False, legend_out=True)
 .map(plt.plot, "annee", "freq", ms=3, linewidth=3))

g.set(xlim=(1980, 2015), xticks=[1980, 1990, 2000, 2010], ylim=0)
g.set_titles('{col_name}')
g.fig.subplots_adjust(top = 0.91, wspace=0.3, hspace=0.3)
g.set_titles('{col_name}', size=13, fontweight='bold', ha='left')
g.set_axis_labels('', 'BABIES')

### This is the line that is not working ###
g.set_ylabels(rotation=0, position=(0, 1.04), color='grey')

g.fig.suptitle('Names that changed gender', x = 0.1, ha='left')
sns.plt.legend(loc='upper left',bbox_to_anchor=(1.5,1))
sns.despine()
```

It doesn't mater if I put 0 or 999999999 as the x value in the `position` parameter. The label is always in the same horizontal place. 

Matplotlib version 2.0, Python 3.5 on Mac OSX El Capitan in Jupyter notebook
Matplotlib installed via `conda update matplotlib`

**Comment by WeatherGod** [comment]
It would be useful to have an example that does not rely upon seaborn in
order to isolate the source of the bug. The bug could very well be in
seaborn's FacetGrid, for all we know...

**Comment by robroc** [comment]
You're right, my apologies. Here's an example in pure matplotlib. The x position is still ignored.

```python
roberto = noms[noms.prenom == 'roberto'.upper()]
roberto = roberto.pivot_table('freq', index='annee', columns='sexe')

fig, ax = plt.subplots()
ax.title.set_text('Babies named Roberto')
ax.plot(roberto)
ax.axes.set_ylabel('BABIES', rotation=0, position=(2000,1.05))
```

![baaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/1219001/22305639/3eeff9c0-e30a-11e6-822d-b4b27d1e7436.png)

**Comment by NelleV** [comment]
Here is the full code to reproduce the problem:

```python
import matplotlib.pyplot as plt
import numpy as np

roberto = np.random.randint(0, 100, size=(10, ))

fig, ax = plt.subplots()
ax.title.set_text('Babies named Roberto')
ax.plot(roberto)
ax.axes.set_ylabel('BABIES', rotation=0, position=(2000,1.05))
```

**Comment by NelleV** [comment]
I have the same results on matplotlib 1.5 and matplotlib 2.0.
Which version of matplotlib are you using?

**Comment by robroc** [comment]
I just upgraded to 2.0 via conda.

**Comment by dstansby** [comment]
After a play around I've found that by setting `position=(x,y)`, `x` and `y` are in figure co-ordinates, so `y=0.5` puts the label halfway up the axis. Setting `x=2000` (if it worked would put the legend way off the the right of the figure.

I can't seem to be getting it working in 1.5.3 either, do you know what version you upgraded from?

**Comment by robroc** [comment]
Oh, I put 2000 in there just to show that no matter what x value I set, it
didn't make a difference. I should have been clearer. I'm sorry, I don't
know what version I upgraded from.

**Comment by dstansby** [comment]
Hmm, I'm not convinced setting `x` location of a y-label or `y` location of an x-label ever worked. The relevant line which sets the label location I think is https://github.com/matplotlib/matplotlib/blame/master/lib/matplotlib/axis.py#L2161 which hasn't changed for at least 5 years.

It might be worth another dev having a look... In the meantime I'd recommend just adding a normal text box to the plot which should give you full control over position.

**Comment by dstansby** [comment]
Punting this to `2.1` as no-one has disagreed (yet) with my assertion that this never worked.

**Comment by dstansby** [comment]
After a bit of a hunt, I think this is a duplicate of #7112

**Comment by tacaswell** [comment]
Closing as I am not sure this ever worked.

**Comment by Harrypotterrrr** [comment]
Hi, is there any solution? I use the latest version of Matplotlib 3.2.1, but `set_ylabels(position=(x,y))` where `x` parameter still not works.

**Comment by jklymak** [comment]
@Harrypotterrrr This would be a feature request at this point.  We just did a similar dance for title (#17127), so its possible to allow manual placement, but its not implemented for `set_ylabel`.

**Comment by Harrypotterrrr** [comment]
@jklymak Thanks for your help! I have found a solution to this tricky but simple problem. 
I managed to set the absolute coordinates of labels by using `set_label_coords()` but now I figured out a better solution, to use `labelpad` parameter of `set_x/ylabel()` method which could deal with overlap problem.

**Comment by jklymak** [comment]
There should not be an overlap problem.  Perhaps you can share your code, maybe in a different issue.

**Comment by fperonaci** [comment]
Hi, in my case I would like to manually align the ylabel of ax2 with the ylabel of ax1, without modifying the latter.
This is strictly related to what was already discussed here. The following would seem pretty reasonable to me:
```
coords = ax.yaxis.get_label_coords()
ax2.yaxis.set_label_coords(coords)
```
However, the `YAxis.get_label_coords` method is not implemented.
A workaround would be:
```
coords = ax.yaxis.get_label().get_position()
```
But in this case the x coordinate is junk.

1. Can you think of a workaround for this?
2. I suggest some improvements:
    2a. The method `YAxis.get_label_coords` should be implemented.
    2b. `Yaxis.get_label().get_position` should return the _true_ position.
    2c. `Yaxis.get_label().set_position` should work as discussed previously.

**Comment by jklymak** [comment]
The postion of the gland is not known until a draw is made so calling fig.canvas.draw() first is needed.

**Comment by jklymak** [comment]
BTW, I assume we are all aware of: https://matplotlib.org/gallery/pyplots/align_ylabels.html

**Comment by fperonaci** [comment]
@jklymak I imagined there was a similar problem. Still, as a user it is frustrating not to have the getter method corresponding to the setter method, as well as it is frustrating to obtain a junk coordinate out of `Yaxis.get_label().get_position`.

I am aware of `align_ylabels` but it seems that this takes as reference the label which is farthest from the axis. In my case I want to align according to the one which is closest to the axis.

**Comment by fperonaci** [comment]
I understand that label coordinates change dynamically, in particular upon changing the tick labels, I guess. But isn't it so also for other quantities? For example, the limits change according to the lines which are plotted. Still, at any time I can call `ax.get_xlim()` and I get the limits at that time.

**Comment by jklymak** [comment]
Sure, because we trigger a recalc when users ask for the x/ylims.  But every other possible thing that can get changed at draw time doesn't necessarily get a recalc just because no one has put the hooks in.  However, in this case, you basically have to recalculate everything, so you may as well just do a full draw.  

I'm curious why you want to align with the *closest* label.  That will presumably overwrite the tick labels on the axes you are moving the label on.

**Comment by fperonaci** [comment]
I understand, thanks for the explanation.

Well, it's because tick labels have different width, e.g. the label for the value -1 is very large compared to, say, the labels for 1,2,3, etc. In my case I only have one label with the minus sign which is pretty far from the axis label. So it is OK to have the label _nominally_ overlapping the tick labels, since in practice it does not (they are physically far apart). Actually, it looks better to have it closer to the axis.

For what concerns me, now I have understood how this works, and that is fine.
However, maybe it is good to get rid of these inconsistencies on the long run.

So for example, compare:
```
ax = plt.gca()
ax.xaxis.set_label_text('x-label')
ax.xaxis.set_label_coords(0.5,0.5)
```
with
```
ax = plt.gca()
ax.set_xlabel('x-label',position=(0.5,0.5))
```

It seems reasonable that the two snippets should do the same, but they do not.

**Comment by jklymak** [comment]
Sure, I agree - thats the suggested fix, is for someone to make the automatic label repositioning over-rideable with manual values if desired, like we did in #17127 for the title.
