### ISSUE TITLE
matplotlib 2.0.0 not using matplotlibrc file in IPython

### ISSUE THREAD

**Issue by sagittariusA1** [matplotlib/matplotlib#7951]
I recently upgraded from matplotlib v1.5.3 from v2.0.0, but with this change, it seems that matplotlib no longer uses my edited matplotlibrc file when plotting figures. When I open the matplotlibrc file in a text editor, I see that my changes are in fact implemented in the file, but when I type matplotlib.rcParams, these changes are not displayed. matplotlib.rcParams only displays the default parameters. Thinking that maybe it was looking at a different matplotlibrc file, I ran matplotlib.matplotlib_fname(), but this points to the same directory of my edited matplotlibrc file.

Does anyone know what's going on here?

FYI, I am running matplotlib 2.0.0 in Python 2.7.12 with IPython 5.1.0. To open matplotlib in IPython, I utilize first the command %matplotlib.

**Comment by QuLogic** [comment]
What is `matplotlib.matplotlib_fname()`? What `matplotlib.rcParams` are not being set?

**Comment by sagittariusA1** [comment]
`matplotlib.matplotlib_fname()` gives the location of the `matplotlibrc` file currently in use. As for which `matplotlib.rcParams` are not being set, all of them. None of the changes I have implemented in `matplotlibrc`, mainly line and axis parameters, have transferred over to the plots.

**Comment by phobson** [comment]
@sagittariusA1 could you post the contents of your RC file?

**Comment by nmayorov** [comment]
Actually I have this too, my matplotlibrc is very simple:  ``figure.figsize   : 8, 6``

**Comment by tacaswell** [comment]
@nmayorov Are you using the inline backend?  Sometime IPython overrides the rcparam values.

**Comment by efiring** [comment]
Where is the edited matplotlibrc file located?

**Comment by sagittariusA1** [comment]
Hi all, I found the reason why my matplotlibrc parameters were not updating properly. As it turns out, I just simply forgot to remove the '#' character from the parameter lines I changed. A mental lapse on my part I guess. Thanks for all of your help!
