### ISSUE TITLE
Cannot import _tkagg on windows 64 bits on 2.7

### ISSUE THREAD

**Issue by cournape** [matplotlib/matplotlib#7953]
It looks like the tk backend is broken with 1.5.3 and 2.0.0 on windows, most likely following #6442 

To reproduce:

1. install python 2.7.12 x64 windows from python.org, and wheels gholke for 2.7
2. do `python -c "import matplotlib.backends._tkagg"`, which fails:

``` python
>>> import matplotlib.backends._tkagg
...
RuntimeError: Could not find TCL routines
```

I have seen the same issue with:

* our own build of 1.5.3 in canopy (for 2.7)
* in Gholke wheels for 1.5.3 and 2.0.0 (2.7.12)
* conda package as well for 1.5.3 (both 2.7.13 and 3.5.2)

**Comment by tacaswell** [comment]
How does it fail (I do not have easy access to a win64 box to test on)?

Does this also affect py3?

attn @matthew-brett @cgohlke (sorry)

**Comment by cournape** [comment]
Oups, forgot that piece of info when rewriting my bug report from #6442. I am also testing on py3 now

**Comment by cournape** [comment]
I updated my findings on python 3 (same result)

**Comment by cgohlke** [comment]
I don't think `import matplotlib.backends._tkagg` can work without first loading the Tk DLLs into the process, e.g. by `import _tkinter` first. In practice I have never run into this error because the usual way to import the backend is `import matplotlib.backends.backend_tkagg`. Maybe I am missing something?

**Comment by cournape** [comment]
Ah, that makes sense. I will see if that works in embedded modes as well.

**Comment by tacaswell** [comment]
@cournape Any update on this?

**Comment by tacaswell** [comment]
Reported fixed in a private email.
