### ISSUE TITLE
im caching in draw_tex

### ISSUE THREAD

**Issue by jdh2358** [matplotlib/matplotlib#796]
This method is really confusing me (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_agg.py#L199): 

    def draw_tex(self, gc, x, y, s, prop, angle):
        # todo, handle props, angle, origins
        size = prop.get_size_in_points()

        texmanager = self.get_texmanager()
        key = s, size, self.dpi, angle, texmanager.get_font_config()
        im = self.texd.get(key)
        if im is None:
            Z = texmanager.get_grey(s, size, self.dpi)
            Z = np.array(Z * 255.0, np.uint8)

        self._renderer.draw_text_image(Z, x, y, angle, gc)

Specifically, if "im" is not None after the texd.get call, then "Z" is not defined in the draw_text_image call.  That we are not seeing failures suggests the im is never getting cached and perhaps we should just remove this logic.

**Comment by tacaswell** [comment]
The code in question moved to : https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_agg.py#L249
