### ISSUE TITLE
Stem is slow and will crash if I try to close the window

### ISSUE THREAD

**Issue by goldfita** [matplotlib/matplotlib#7969]
**Bug summary**

Stem will crash if you try to close the window while it's processing.  It's also very slow for what I would consider a relatively small number of data points.  I'm using the code from Julia, but I was informed the problem is Matplotlib.  See original [discusion](https://discourse.julialang.org/t/pyplot-crash/1706).

**Code for reproduction**

using PyPlot
stem(randn(32768))

**Actual outcome**

This will work if you wait about half a minute.  If you interfere by trying to close the window, the application crashes (Julia in this case).

**Matplotlib version**

I don't know.  I'm using the most recent version of PyPlot and PyCall in Julia 0.5.  Conda installed Python 2.7.

**Comment by tacaswell** [comment]
Can you please provide python code that generate the issue?  As the julia folks point at us, it is not clear that this is not a bug on the julia side.

**Comment by goldfita** [comment]
I tried just now.  I'm afraid I'm too much of a beginner with both Julia and Matplotlib to figure this out.  However, poster jheinen on the Julia forum claims to have reproduced this problem in pure Python.  I suggest asking him for his code.  I'm sorry I can't be of any more help.  I don't want to get in the middle of any finger pointing between these two communities.

**Comment by tacaswell** [comment]
It is not finger pointing, just sorting out what the actual bug is.


attn @jheinen

**Comment by jheinen** [comment]
This is how you can reproduce the bug (in Python)

```python
import matplotlib.pyplot as plt
import numpy as np
plt.stem(np.random.randn(10000))
```

Fails on macOS X, can't check other backends before Monday ...

**Comment by anntzer** [comment]
Indeed, this is likely due to the fact that `stem` generates one Line2D per stem, rather than grouping everything in a LineCollection, which would probably improve the performance quite a bit.

**Comment by anntzer** [comment]
(but LineCollection currently cannot take a custom marker :-()

**Comment by tacaswell** [comment]
At a minimum, we could save some time by not going through `plot`

**Comment by dstansby** [comment]
Having a look at this and think I'm making progress

**Comment by terriyu** [comment]
I also confirmed this bug in Python 3 on Ubuntu 16.04.  I tried to plot a stem plot with 130,000 points and the computer crunched on it a long time without displaying anything.

**Comment by grr37213** [comment]
Since I encountered this problem by plotting around 30000 data points today and found this issue.
I am also on Ubuntu
I can only link to this workaround, which solved my problem through manually calculating the line, coordinates and plotting a line collection, instead of using stem itself.
https://stackoverflow.com/questions/48301044/optimization-of-matplotlib-stem-plot

**Comment by racinmat** [comment]
Will this be merged to some 3.0.x version, or do we need to wait for stable 3.1.x version if we want this fixed in pip?

**Comment by dstansby** [comment]
I'm afraid this is only going to be in `3.1.x` onwards.

**Comment by timhoffm** [comment]
But 3.1.0 should hopefully come out soon :smile: .

**Comment by tacaswell** [comment]
Hopefully today or tomorrow.
