### ISSUE TITLE
Dotted grid lines in matplotlib v2.0.0 appear dashed

### ISSUE THREAD

**Issue by fkbreitl** [matplotlib/matplotlib#7991]
As discussed in issue #6515 dotted grid lines do not appear dotted but dashed.
This has not changed in version 2.0.0.
Could you please restore the dotted appearance as seen in earlier versions?
The current appearance is not satisfying.

**Comment by dstansby** [comment]
I would agree that they don't quite look dotted to me. From #6515, 

```
import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
y = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
grid = a.reshape(3, 3)

plt.imshow(grid, extent=(x.min(), x.max(), y.min(), y.max()),interpolation='bicubic')
plt.grid(linestyle='dotted')
plt.show()
```

For me (on current master) this currently gives:
![figure_1](https://cloud.githubusercontent.com/assets/6197628/22429891/2783f2fc-e704-11e6-92c4-bd74f174f679.png)

**Comment by tacaswell** [comment]
You can configure this however you wish: http://matplotlib.org/users/dflt_style_changes.html#plot

**Comment by fkbreitl** [comment]
Maybe, but people don't want to waste time fixing stuff before they can use it. Matplotlib should be provided ready for use and not misconfigured. Most people mean a dotted line if they say so. But currently they don't get it. People don't know the settings for a dotted line nor do they have time to figure it out.

**Comment by tacaswell** [comment]
Flagged as critical as we need to make a decision on this one way or the other.

**Comment by dopplershift** [comment]
Yeah, I'll agree that I don't think we should really be calling those lines dotted.

**Comment by tacaswell** [comment]
Clipping at 0.5 in the scaling:

![so](https://cloud.githubusercontent.com/assets/199813/22665688/a7ac8992-ec83-11e6-8cc2-bf2c47986c39.png)

**Comment by tacaswell** [comment]
clipping at 1.0

![so](https://cloud.githubusercontent.com/assets/199813/22665723/cd3cb790-ec83-11e6-86a4-b4a6d1a99015.png)

**Comment by tacaswell** [comment]
clipping at 1.5

![so](https://cloud.githubusercontent.com/assets/199813/22665775/0044fe90-ec84-11e6-95c3-bca227c02d74.png)

**Comment by dstansby** [comment]
I think both the 0.5 and 1 cases look good. It would also be worth checking over a range of line widths.

**Comment by tacaswell** [comment]
Clipping at 1 and range of lw

![so](https://cloud.githubusercontent.com/assets/199813/22665946/c99f1974-ec84-11e6-9e45-7a7d11134b86.png)

**Comment by tacaswell** [comment]
talking to @dopplershift we are going to adjust the clipping to 1.

**Comment by dstansby** [comment]
👍

**Comment by fkbreitl** [comment]
To me the dot frequency looks too high. Now it almost looks like a solid line. The classic version looked different. Can we not just restore the classic appearance? That was ok. See the example below.

![mpl-dotted](https://cloud.githubusercontent.com/assets/1030293/22686570/dbf440a4-ed24-11e6-85ef-b546c71e31d1.gif)

**Comment by tacaswell** [comment]
If you do not want to use the 2.0 styles, there is a classic style sheet available (the first thing documented in http://matplotlib.org/users/dflt_style_changes.html#changes-to-the-default-style ).

See http://matplotlib.org/users/dflt_style_changes.html#plot for how to selectively revert the changes to the classic patterns and disable the scaling with line width.

You can also pass a dash pattern directly to grid to get what ever pattern you want.

There is no set of defaults which will make all users of Matplotlib happy at all times, there are simply too many different use cases (and too many users).  Sorry that you have a case where they do not work well, but there is more than enough flexibility in the library to get your desired outcome.

As a reminder, a vast majority of the work done on Matplotlib is done by volunteers on their own time.

**Comment by fkbreitl** [comment]
Thank you for pointing things out.
But is there any reason to make the doted line in 2.0 not look as good as in the classic version?
I think that matplotlib should provide plots in publication quality on a professional level. That includes avoiding referee complaints about difficult to distinguish line styles. Matplotlib should make this most obvious and less number of dots for a dotted line would put it on the safer side.

**Comment by afvincent** [comment]
If I understood correctly, the new line styles are the results of discussions from #5917 and #5926 . One of the arguments was that the dotted style had a significantly smaller visual weight than the other line styles.

**Comment by fkbreitl** [comment]
Thanks for pointing this out.
I think also the other line styles presented there need more space. The gaps are too small.
This makes it harder to distinguish them.

**Comment by ankitkumar-pi** [comment]
You can use, ax.grid(color='r', linestyle='dotted', linewidth=2)
There are more linestyle as 
     [linestyle_str](https://docs.python.org/3/library/stdtypes.html#list) = [
     ('solid', 'solid'),      # Same as (0, ()) or '-'
     ('dotted', 'dotted'),    # Same as (0, (1, 1)) or ':'
     ('dashed', 'dashed'),    # Same as '--'
     ('dashdot', 'dashdot')]  # Same as '-.'
