### ISSUE TITLE
Hatching doesn't respect alpha

### ISSUE THREAD

**Issue by japborst** [matplotlib/matplotlib#7992]
### Bug report

**Bug summary**
When plotting using a hatch, alpha is not applied to the hatching

**Code for reproduction**
```python
import matplotlib.pyplot as plt
plt.fill_between(range(10), [10]*10, hatch='/', alpha=0.5)
plt.show()
```

**Actual outcome**
Hatching is black with no alpha
![Example](https://cloud.githubusercontent.com/assets/1426824/22429497/1b431fde-e70b-11e6-9f60-942852485866.png)

**Expected outcome**
Before matplotlib 2.0, the hatching was the color of the fill and alpha was respected

**Matplotlib version**

Windows 7
matplotlib 2.0.0
numpy 1.12.0
scipy 0.18.1
Installation through pip

**Comment by dstansby** [comment]
It looks like this will be fixed by #7976, in the case where the `edgecolor` argument is specified to `fill_between` to choose the colour of the hatch.

**Comment by japborst** [comment]
Nice! Thanks for the quick update :)

**Comment by dstansby** [comment]
This is now fixed in master and 2.0.1

**Comment by kilojoules** [comment]
Is there no way to control the hatch transparency separately?

**Comment by tacaswell** [comment]
At the lowest level it can be controlled, but currently there is no user interface to this in the classes we ship.    If you need a different color hatch + edge, I suggest using two over-lapping artists.

**Comment by tacaswell** [comment]
@usiu5555 See the last example of https://matplotlib.org/users/legend_guide.html#legend-handlers that section for how to handle merging multiple artists into a single legend entry.

There has not bee any progress on threading the alpha control of the hatch through the Artist classes, would you be interested in looking into that @usiu5555 ?

**Comment by usiu5555** [comment]
@tacaswell Thank you, that helped, and was much easier than I expected.

Well, sounds like a challenge, but sadly, because of many reasons, I can't.
