### ISSUE TITLE
Need Python 3.6 wheels for matplotlib 1.5.1 on PyPI

### ISSUE THREAD

**Issue by GDICommander** [matplotlib/matplotlib#8009]
Hello,

There is no wheel on PyPI for matplotlib 1.5.1 for Python 3.6, which forces those that install the package to build the library. Those not configured to matplotlib on their machine cannot use matplotlib with the latest Python version. All other Python 3 versions have wheels.

Can you produce these wheels for Python 3.6 on all platforms (Windows, OS X and Linux)?

Thank you and have a nice day!

**Comment by matthew-brett** [comment]
I see wheels for all platforms and Python 3.6 here : 

https://pypi.python.org/pypi/matplotlib/2.0.0 

and here: 

https://pypi.python.org/pypi/matplotlib/1.5.3

What platform are you on?   Have you got the latest version of pip?

**Comment by GDICommander** [comment]
There is no Python 3.6 wheel for matplotlib 1.5.1: https://pypi.python.org/pypi/matplotlib/1.5.1

Actually, we will work around this issue by upgrading to 1.5.3, which has a Python 3.6 wheel.

Feel free to add a Python 3.6 wheel or reject this issue if 3.6 is supported from a specific version after 1.5.1 :)

**Comment by dopplershift** [comment]
Since 3.6 came out well after 1.5.1, I'd say upgrading to 1.5.3 would be our preferred solution.
