### ISSUE TITLE
imshow interpolation uses masked values

### ISSUE THREAD

**Issue by dshean** [matplotlib/matplotlib#8012]
### Bug report

I recently upgraded to v2.0.0 and noticed that the new imshow interpolation is not honoring masked values.  This is likely related to the new edge handling, described here: http://matplotlib.org/examples/pylab_examples/image_interp.html

**Code for reproduction**

```python
a = np.random.random((7,7))*1000
ndv = -9999.0
a[2:4,1:5] = ndv
am = np.ma.masked_equal(a, ndv)

plt.figure()
#Plot with no interpolation, looks fine
plt.imshow(am, interpolation='none')
plt.title("interpolation='none'")
#Plot with bilinear interpolation, the -9999.0 values are used 
plt.imshow(am, interpolation='bilinear')
plt.title("interpolation='bilinear'")
```

**Actual outcome**

![none](https://cloud.githubusercontent.com/assets/1103530/22578435/9caeb99c-e97d-11e6-9b57-056f348f9048.png)

![bilinear](https://cloud.githubusercontent.com/assets/1103530/22578437/a01c81fe-e97d-11e6-9fc7-b60fdae837cb.png)

**Expected outcome**

The interpolation should ignore masked values as in previous versions.

**Matplotlib version**

- Matplotlib v2.0.0, Python 2.7.13, OSX
- installed from pip

**Comment by tacaswell** [comment]
It is honoring it, just in weird ways, will have a PR shortely:

![so](https://cloud.githubusercontent.com/assets/199813/22579192/1f87608a-e99c-11e6-87a8-d874de1a226e.png)

**Comment by tacaswell** [comment]
Note that in carves out a larger area because the region of screen pixels that get input from the masked data values is larger.

**Comment by tacaswell** [comment]
The fix seems to break something else, will get to this tomorrow.

**Comment by tacaswell** [comment]
This is _way_ nastier than I expected :disappointed:

**Comment by QuLogic** [comment]
@tacaswell Doesn't this still require some tweaks (cf. the last comment in #8024 and #8183)?

**Comment by tacaswell** [comment]
Yes, on my to-do list for tonight

**Comment by gurraburra** [comment]
> Note that in carves out a larger area because the region of screen pixels that get input from the masked data values is larger.

This seems still to be the case, would It be possible for interpolation to not change the size of the masked area?

**Comment by tacaswell** [comment]
> This seems still to be the case, would It be possible for interpolation to not change the size of the masked area?

No, because the way the interpolation works is by (effectively) convolving the input data with a fixed size kernel.  Any place you evaluate the kernel that overlaps with a masked point also needs to be poisoned (e.g. if you drop a `np.nan` into any interpolation method then the output is always `np.nan`).

**Comment by gurraburra** [comment]
> > This seems still to be the case, would It be possible for interpolation to not change the size of the masked area?
> 
> No, because the way the interpolation works is by (effectively) convolving the input data with a fixed size kernel. Any place you evaluate the kernel that overlaps with a masked point also needs to be poisoned (e.g. if you drop a `np.nan` into any interpolation method then the output is always `np.nan`).

Yes I understand. My problem is not that I have np.nan, but simply that I want to mask some voxels from the image being shown. One solution could be to add a mask option to imshow, then the interpolation could be done before masking. Or another option would be to detect if the data is masked, then remove the mask (perhaps also replace masked values with zero), do the interpolation and then reapply the mask.

**Comment by tacaswell** [comment]
If you want the masked pixel to be transparent, you are stuck, if you want to make it white, you can do something like

```
mask = np.ones((*data.shape, 4))  # RGBA of the right size
mask[~to_hide] = 0                # make the pixels you want to keep transparent
im_data = ax.imshow(data)
im_mask = ax.imshow(mask, zorder=im1.get_zorder() + 1, interpolation='nearest')
```
