### ISSUE TITLE
Unexpected HOME behavior after axis change

### ISSUE THREAD

**Issue by proximous** [matplotlib/matplotlib#8016]
### Bug report

**Bug summary**

HOME button returns axis to original axis even when hold(False) and new data is plotted.  Home should restore the axis of the last plot.

**Code for reproduction**

```plot(range(1000))```

axis is 0:1000 (expected)
zoom in on some area of the plot.
press Home
axis returns to 0:1000 (expected)

```
hold(False)
plot(range(10))
```

axis is 0:10 (expected)
zoom in on some area of the plot.
press Home
axis returns to 0:1000 (unexpected...0:10 expected)

**Matplotlib version**

- Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
Tested in virtual environment with current PIP version (matplotlib-2.0.0-1-cp35-cp35m-manylinux1_x86_64.whl) on Ubuntu 16.04, but also present on every prior version tested including default apt packages for Ubuntu 14.04 and Ubuntu 16.04

**Comment by tacaswell** [comment]
Does the same thing happen if you do `fig.clf()`?

We are planning to deprecate all of the `hold` related functionality, how critical is it to your use of Matplotlib?

**Comment by proximous** [comment]
fig.clf() does not have this problem, and is effectively the same as hold(False) so it is a fine solution for me.  The only drawback is that in theory I only have to issue hold(False) once to have each future plot be new, yet now I need to issue clf() before every plot().  This is manageable, but not ideal. Is there an alternate preferred method to getting the hold(False) behavior?

BTW, thanks for such a quick and useful response! Very much appreciated!

**Comment by tacaswell** [comment]
Write your self a helper function that does 

```python
def clearing_plot(ax, data):
    ax.cla()
    retrun ax.plot(data)
```

or some such.

The issue with the `hold` implementation is that inside of many of the plotting methods we call _other_ plotting methods so we have a lot of

```python

old_hold = self.hold
self.hold = False
# code
self.hold = old_hold

```

scattered through out the code-base.

**Comment by proximous** [comment]
Helper function is a good solution. I'll do that. And thanks for explaining the maintenance issue of hold. I guess Matlab just trained me to like the hold feature.

**Comment by tacaswell** [comment]
@proximous How disruptive is losing hold to you?

**Comment by proximous** [comment]
I'm fine with the helper function. It will just take some getting used to.  I'd say the big benefit to supporting hold is the similarity to Matlab, I use matplotlib a lot, and 95+% of my usage is interactively plotting data in IPython (started with --pylab).  I'm frequently toggling hold on and off as I look at data, and using hold was intuitive from my Matlab experience.

That said, I'm certainly not opposed to learning an alternate approach, and using a plot_hold() vs plot_clr() set of wrapper functions is no more work after the initial setup of getting the wrappers available to me when I start ipython.
