### ISSUE TITLE
Font family is not set on log-scaled tick labels

### ISSUE THREAD

**Issue by michael-a-hansen** [matplotlib/matplotlib#8017]
### Bug report

**Bug summary**

Setting the font family through `rcParams` doesn't impact tick labels if the axis is log-scaled. The size of the font can be changed, but not the family (e.g. using the serif font).

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib import rcParams

rcParams['font.family'] = 'serif'
rcParams['font.size'] = 16

x = [0, 1, 2]
y = [1, 100, 10000]

plt.plot(x, y)
plt.yscale('log')
plt.savefig('logscaled.png')
plt.clf()

plt.plot(x, y)
plt.savefig('not-logscaled.png')
```

**Actual outcome**

As seen in this screenshot, the linear-scaled y-axis on the left has a serif font while the log-scaled y-axis on the right still has the default sans-serif font. In both cases the font size is set appropriately to 16. It's just the font family that doesn't change. (Pardon the 'shadow' between the two images, that's my Mac, not matplotlib).

![issue](https://cloud.githubusercontent.com/assets/15069804/22612861/b6e4ed96-ea30-11e6-8df6-4c192ca0de51.png)

**Expected outcome**

The code should produce tick labels on log-scaled axes with the specified font family.

**Matplotlib version**

- Mac OS X 10.10.5
- python 3.5, installed from a [Mac installer pkg](https://www.python.org/downloads/mac-osx/)
- matplotlib 2.0.0 - upgraded February 3 with `python3 -m pip install --upgrade matplotlib`

**Comment by dstansby** [comment]
I can reproduce this bug, and it isn't present on 1.5.3

**Comment by tacaswell** [comment]
This is likely something fishy with mathtext...

**Comment by dstansby** [comment]
Bisects to https://github.com/matplotlib/matplotlib/commit/6bfd8b1b8ab41676f9dd2ca79de922014c272f11

**Comment by kbwestfall** [comment]
This isn't just isolated to tick labels.  It's anywhere you put in math expressions in a byte string.  Add `plt.title(r'byte string with $m_at_h$')` to the example code above and it will show that the text switches from serif to sans-serif for the rendered math.

**Comment by tacaswell** [comment]
what do you mean by 'byte string'?

**Comment by grahamrow** [comment]
In my case this can be solved with:
```
from matplotlib import rc
rc('mathtext', default='regular') 
```
which will use your specified font for math text, such as the $10^{x}$ being used for logscale tick labels.

**Comment by Tillsten** [comment]
I think this has to do with the mathdefault shim for  for preserving the classic style. Using just 2.0 defaults the `LogFormaterMathtext` ignores `font.family`. After `style.use('classic')` they are respected.

**Comment by Tillsten** [comment]
Actually I think the shim is wrong and uncessary:

```
def _mathdefault(s):
    """
    For backward compatibility, in classic mode we display
    sub/superscripted text in a mathdefault block.  As of 2.0, the
    math font already matches the default font, so we don't need to do
    that anymore.
    """
    if rcParams['_internal.classic_mode']:
        return '\\mathdefault{%s}' % s
    else:
        return '{%s}' % s
```
The assumption of that the math font equals the regular font is not true in general.

**Comment by Tillsten** [comment]
As a workaround 
```
import matplotlib.ticker
matplotlib.ticker._mathdefault = lambda x: '\\mathdefault{%s}'%x
```

**Comment by tacaswell** [comment]
Removing this shim and always using `'\\mathdefault'` seems like a reasonable change.

**Comment by NelleV** [comment]
Closed by #8354

**Comment by binaryfunt** [comment]
I've noticed the workaround suggested doesn't work for cases where tick labels like "2 x 10<sup>3</sup>" appear. These are styled with dejavu sans and there doesn't seem to be anything I can do to change them. They don't seem to use the usual mathtext or even roman masters

    import matplotlib.ticker
    from matplotlib import rc
    matplotlib.ticker._mathdefault = lambda x: '\\mathdefault{%s}'%x
    rc('mathtext', fontset='custom')
    rc('mathtext', default='regular')
    rc('mathtext', rm='serif')
    font_path = 'C:\Windows\Fonts\Roboto-Bold_0.ttf'
    font_prop = font_manager.FontProperties(fname=font_path, size=11)
    ...
    for label in (ax.get_xticklabels() + ax.get_yticklabels()):
        label.set_fontproperties(font_prop)
    plt.xlabel(r"Regular txt, ${math txt, \mathrm{rm math txt}}$", fontproperties=font_prop)

![figure_56](https://cloud.githubusercontent.com/assets/14579418/25058474/a3f17830-2171-11e7-9221-66cd1cc63a37.png)

**Comment by tacaswell** [comment]
@binaryfunt Can you open a new issue for that?
