### ISSUE TITLE
Log Scale Ticklabels Refuse to Die (Data Dependent)

### ISSUE THREAD

**Issue by riggsd** [matplotlib/matplotlib#8027]
### Bug report

When setting a scatter plot's y axis to log-scale in matplotlib 2.0.0, it is _data dependent_ as to whether y tick labels can be removed or not.

**Code for reproduction**

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

# create fake data
MIN, MAX = 13, 100
y = np.linspace(MIN, MAX, num=50)
x = np.arange(len(y))

# plot it
fig = plt.figure()
fig.suptitle('matplotlib %s  (range %d - %d)' % (mpl.__version__, MIN, MAX))
plot = fig.add_subplot(111)
plot.scatter(x, y)
plot.set_yscale('log')  # set log-scale y axis
plot.set_yticks([])     # disable y ticklabels (FIXME: silent failure on mpl 2.0.0)
plt.show()
```

**Actual outcome**

This animation illustrates driving the above code, starting with values 1-100, up to values 20-100. Note that y ticklabels are successfully removed for lower values, then the ticklabels appear for minimum y values of 13 and above.

![mpl_log_test_2 0 0_anim](https://cloud.githubusercontent.com/assets/647785/22634480/10b1aa08-ebdf-11e6-8d9c-116bafa86ef2.gif)

Note that I've tried several different approaches to remove the y ticklabels, but the labels always reappear given certain input data. Even when I set my own `ScalarFormatter()` for custom labeling (which is my real goal), the default scientific notation labels are still rendered "on top of" my own labels.

**Expected outcome**

Expected outcome is that y ticklabels would never appear, regardless of the values being plotted.

**Matplotlib version**

- matplotlib 2.0.0 (bug is _not_ present in 1.5.3)
- Mac OS X 10.9.5
- python.org Python 2.7.13
- all dependencies installed using `pip`

**Comment by riggsd** [comment]
I notice that there are several current bugs related to log-scale ticks, some of which _may_ be related to this one: #7200, #6915, #4131, #4581.

**Comment by tacaswell** [comment]
Because the other tick labels are from minor ticks.  It is far better to do

```python
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
plt.ion()

fig, ax = plt.subplots()
ax.set_yscale('log')
ax.yaxis.set_major_formatter(NullFormatter())
ax.yaxis.set_minor_formatter(NullFormatter())

```

**Comment by riggsd** [comment]
Oof! I was under the impression that only major ticks produced text labels.

Should this issue be closed, or should it remain open since the behavior differs in 1.5.3 vs 2.0.0?

**Comment by riggsd** [comment]
Confirmed that `set_minor_formatter(NullFormatter())` solved the problem using mpl 2.0.0 in both my simplified example code, and also in my complex application.

Thanks for the correction @tacaswell!

**Comment by riggsd** [comment]
Looks like this is a documented change to the default style, and I simply missed it when reading the 2.0.0 docs.

http://matplotlib.org/users/dflt_style_changes.html#tick-label-formatting

"Minor ticks on a log axis are now labeled when the axis view limits span a range less than or equal to the interval between two major ticks."

**Comment by tacaswell** [comment]
Glad you got it sorted!

We change lots of things in lots of ways and did our best to document them.  Things that seem small to those writing the docs may be the biggest change in the world to some users.
