### ISSUE TITLE
Unable to  intall matpotlib package using whl

### ISSUE THREAD

**Issue by chaksridhar** [matplotlib/matplotlib#8030]
I am in windows 10 env, using python 2.7.8 32 bit version. When I try to install matplotlib thru whl file as

   pip install  matplotlib-2.0.0-cp27-cp27m-win32.whl

I obtained the error 
    .......
  File   "c:\python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
    BadZipfile: File is not a zip file

The same error comes when I try to other versions of  matplotlib*whl file ( matplotlib-2.0.0-cp34-cp34m-win32.whl, matplotlib-2.0.0-cp35-cp35m-win32.whl).

Any help in resolving the issue is  appreciated.

**Comment by tacaswell** [comment]
I suspect you have an incorrect wheel.   

Doing `pip install matplotlib` should automatically get the correct wheel from pypi.

This is not a matplotlib bug so I am going to close this, but please follow up in gitter (https://gitter.im/matplotlib/matplotlib) or the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users you much subscribe to post un-moderated).
