### ISSUE TITLE
Traitlets Integration - Main

### ISSUE THREAD

**Issue by rmorshea** [matplotlib/matplotlib#8035]
This is homebase for updates regarding the integration of [`traitlets`](https://github.com/ipython/traitlets) into matplotlib.

For basic information, refer to the project [summary](https://docs.google.com/document/d/1xskjwygDKkRB466YSCzpT5mGnZNqmt1U84zkfyPKcfE/edit?usp=sharing) and [timeline](https://docs.google.com/spreadsheets/d/1tFlV0lZ06Xq5sjNrg3xeNPYZB83qvrk-Ghoq0ZWmecQ/edit?usp=sharing).

## Before Commenting...

This issue has a [gitter](https://gitter.im/matplotlib-traitlets/general) - post here first!

This issue will generally contain progress updates, or discussions that are relevant to the Matplotlib community as a whole. All technical questions and comments should first be posed on gitter so they can be developed before a post is made here or on this issue's corresponding pull request.

**Comment by tacaswell** [comment]
I'm going to close this.  We may want to go into using a managed attributes framework with the dataprototype work, however it may not be traitlets (we do not really need the detailed notification machinery).
