### ISSUE TITLE
Arc patch with starting and ending angle

### ISSUE THREAD

**Issue by pdhall99** [matplotlib/matplotlib#8046]
### Bug report

**Bug summary**

- Arc patch does not behave as expected when drawing elliptical arcs between two angles specified by theta1 and theta2.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
from matplotlib.patches import Arc

# Ellipse parameters
R = 1.0
x, y = 0.0, 0.0
a, b = 2.0*R, R

# Figure setup
fig_width, fig_height = 3.30, 3.30
fig = plt.figure(figsize=(fig_width, fig_height), frameon=False)
ax = fig.add_axes([0.0, 0.0, 1.0, 1.0], aspect='equal')
ax.set_axis_off()
ax.set_xlim(-R*1.05, R*1.05)
ax.set_ylim(-R*1.05, R*1.05)
# Axes
ax.axhline(0.0)
ax.axvline(0.0)
# 45 degree line
ax.plot([0.0, 1.0], [0.0, 1.0], 'k--')
# Arcs
ax.add_patch(Arc((x, y), a, b, 
                 theta1=0.0, theta2=360.0, edgecolor='k'))
ax.add_patch(Arc((x, y), a, b,
                 theta1=0.0, theta2=45.0, edgecolor='r', lw=1.5))
fig.savefig('Arc_patch_bug.png')
```

**Actual outcome**

![arc_patch_bug](https://cloud.githubusercontent.com/assets/20580126/22736007/3d8cc2bc-edf4-11e6-85ef-3e042599b626.png)

**Expected outcome**

- Red elliptical arc between the x-axis (0 degrees) and the dashed line (45 degrees), following the black ellipse.

**Matplotlib version**

- Matplotlib 2.0.0, Python 2.7.13, OSX
- Installed with MacPorts

**Comment by dstansby** [comment]
I'm trying to run your example, but you haven't specified `angle_deg` anywhere in the code (so adding the patches fails).

**Comment by dstansby** [comment]
I can reproduce this using a stripped down example:

```
import matplotlib.pyplot as plt
from matplotlib.patches import Arc

# Ellipse parameters
R = 1
x, y = 0, 0
a, b = 2 * R, R

# Figure setup
fig, ax = plt.subplots()
ax.set_xlim(-R * 1.05, R * 1.05)
ax.set_ylim(-R * 1.05, R * 1.05)
# 45 degree line
ax.plot([0, 1], [0, 1])
# Arcs
ax.add_patch(Arc((x, y), a, b,
                 theta1=0, theta2=360, edgecolor='k'))
ax.add_patch(Arc((x, y), a, b,
                 theta1=0, theta2=45, edgecolor='r', lw=1.5))
plt.show()
```
I'm guessing this is because the aspect ratio of the ellipse isn't 1

**Comment by pdhall99** [comment]
> I'm trying to run your example, but you haven't specified angle_deg anywhere in the code (so adding the patches fails).

Thanks for pointing out that error. I've corrected it in the original report.
