### ISSUE TITLE
includes not-really-free BaKoMa fonts

### ISSUE THREAD

**Issue by jonassmedegaard** [matplotlib/matplotlib#8051]
It seems matplotlib includes fonts without license.  And that the generally available license for said fonts is not really free (limited to non-commercial use).

Bug #6976 references the LyX project and their file ReadmeBaKoMa4LyX as proof of origin for some fonts shipped with matplotlib. That file references web page http://www.ctan.org/tex-archive/systems/win32/bakoma/  which describes the BaKoMa fonts as Shareware. At other places - e.g. http://www.math.utah.edu/~beebe/fonts/bakoma.html - the BaKoMa fonts are described as "free" but only for non-commercial use.

I recommend to add a file in same folder as the BaKoMa(-derived) fonts where you clarify its origin and license - including quoting verbatim the licensing terms as they were given to you from Basil - directly or possibly via redistribution, but not hearsay.

In my understanding, If project A receives the fonts and a license for using them, but then redistributes the fonts _without_ the license, then project B is not licensed to use the fonts!

You need not agree with my understanding of licensing - I am not here to point fingers at others. Issue here is that even if your interpretation of licensing requirements are more relaxed, then others - like Debian that I am part of - may impose a more strict interpretation and therefore need the details you possible feel are unneeded for your legal coverage.

**Comment by tacaswell** [comment]
I do not disagree with your analysis of the licensing issues, however I disagree with the provenance of the fonts.  

The version we ship comes from the AMS  (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/fonts/afm/cmex10.afm) which are freely distributable (see http://www.ams.org/publications/type1-fonts we might want to track down exactly which version of these files we are using.

This does shed some more light on the issue with LyX in that they have a set of files with identical names (as both are derivatives of the original metafont developed by Knuth) but have entirely different provenance.

**Comment by jonassmedegaard** [comment]
Quoting Thomas A Caswell (2017-02-09 17:15:55)
> I do not disagree with your analysis of the licensing issues, however 
> I disagree with the provenance of the fonts.
> 
> The version we ship comes from the AMS 
> (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/fonts/afm/cmex10.afm) 
> which are freely distributable (see 
> http://www.ams.org/publications/type1-fonts we might want to track 
> down exactly which version of these files we are using.
> 
> This does shed some more light on the issue with LyX in that they have 
> a set of files with identical names (as both are derivatives of the 
> original metafont developed by Knuth) but have entirely different 
> provenance.

Thanks for the details on the licensing of AMS fonts.

The issue I raise here is about BaKoMa fonts (not AMS fonts).

If you mean to say that e.g. 
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf 
derives from, and is identically licensed as,
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/fonts/afm/cmex10.afm 
then I believe you are mistaken:

If you run this command:

    strings cmsy10.ttf | grep Copyright

you will liekly get this output:

    Copyright (C) 1994, Basil K. Malyshev. All Rights Reserved.012BaKoMa Fonts Collection, Level-B.cmsy10RegularFontMonger:cmsy10cmsy101.1/12-Nov-94Cmsy10

Yes, the filenames are similar, but Basil clearly claims copyright for 
the truetype font (and it seems AMS fonts do not include truetype fonts 
at all).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by tacaswell** [comment]
Your correct (I just arrived at the same conclusion having learned the difference between afm and ttf files).  However, we have https://github.com/matplotlib/matplotlib/blob/master/LICENSE/LICENSE_BAKOMA which I think covers our re-distrobution of the ttf files.

**Comment by jonassmedegaard** [comment]
Indeed.

I agree there is no problem here - sorry I totally missed that file.

Hereby closing as a non-bug.

**Comment by tacaswell** [comment]
If it makes you feel any better I found it via google while trying to track down the BaKoMa license :-p
