### ISSUE TITLE
Provide an option for the Animation class to retain the previously rendered frames

### ISSUE THREAD

**Issue by veeresht** [matplotlib/matplotlib#806]
Currently the ArtistAnimation class renders the animation frame by frame and while rendering the current frame, it clears the previously drawn artists (from the previous frames). The _pre_draw function does this. 

There may be a use case where it is not required to clear the previously rendered artists, and trying to render the artists again in every frame may affect the performance.  

Hence it would be good if there is an option for the user to control this behavior through the API.

**Comment by efiring** [comment]
@dopplershift, this is a very old request--can we close it?  My sense is that trying to satisfy it would add complexity to an already-complex module, for relatively rare benefit.

**Comment by dopplershift** [comment]
Given that I'm not planning on doing it and I agree it would add unwise complexity, closing would be appropriate.
