### ISSUE TITLE
Scaling issues with PyQt5 when using mixed resolution displays

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#8061]
I have a set-up where I have a retina MBP (bottom) plugged in to a non-retina display (top).

Normally Matplotlib looks fine on retina or non-retina displays when used separately, but in the case of mixed resolutions, the fonts and the elements of the figure appear too large on the non-retina display. The following image sequence shows a matplotlib window that was created on the retina display and is then moved to the non-retina display. The same issue happens if I create the figure in the non-retina display to start with, so this is not about moving from one to the other.

![screen shot 2017-02-10 at 17 45 41](https://cloud.githubusercontent.com/assets/314716/22837586/332706ea-efb9-11e6-8b24-e39a7f601ca8.png)
![screen shot 2017-02-10 at 17 45 51](https://cloud.githubusercontent.com/assets/314716/22837593/3709d58a-efb9-11e6-8433-15c5c79bcd95.png)
![screen shot 2017-02-10 at 17 45 59](https://cloud.githubusercontent.com/assets/314716/22837598/3a678632-efb9-11e6-988d-2659b0a26e05.png)
![screen shot 2017-02-10 at 17 46 04](https://cloud.githubusercontent.com/assets/314716/22837602/3cc5cba0-efb9-11e6-9f62-65d6c66bf92c.png)

I then click in the bottom right to resize the window:

![screen shot 2017-02-10 at 17 46 17](https://cloud.githubusercontent.com/assets/314716/22837605/3f2b81e6-efb9-11e6-9706-461a4f4007aa.png)

**Comment by tacaswell** [comment]
Does Qt provide a signal we can hook into when the window changes screens (and hence the dpi scaling)?

**Comment by astrofrog** [comment]
Looks like the easiest way is to look for screenChanged then in there check if devicePixelRatio changes:

https://forum.qt.io/topic/52296/detect-changing-devicepixelratio/4

**Comment by astrofrog** [comment]
Note that this also causes issues when just showing a plot on the lower-res screen that is attached to a retina screen laptop (the fonts are two times too large and lines two times too thick) - that is, without even changing screen. I think this is something to do with the fact that the DPI device ratio is declared to be 1 for the low-res screen. If I force ``_dpi_ratio`` to return ``2`` then the scaling looks correct on the low-res screen. I'm not sure how other OSes deal with this, but maybe on mac the DPI device ratio should be the highest one of available screens rather than the one of the current screen?

**Comment by astrofrog** [comment]
@QuLogic - do you have any ideas since you've worked on the DPI ratio stuff before?

**Comment by tacaswell** [comment]
@astrofrog can you check with v2.0.1?

**Comment by astrofrog** [comment]
This is still an issue with 2.0.1 unfortunately

**Comment by efiring** [comment]
It looks like you identified at least part of the machinery we need to add (screenChanged, etc.); any chance you can have a go at implementing it?

**Comment by astrofrog** [comment]
All right, I'm going to take a look at this today. This has been bugging me for a while. Wish me luck.

**Comment by burnpanck** [comment]
This bug report here describes two problems:
 1. The figure did not properly get notified on a DPI change
 2. The figure is rendered with incorrect DPI settings on the low-DPI monitor if a hi-DPI monitor is available on the system as-well.
#8931 only fixes the first of the two issues. Should this bug report be reopened or a separate one be created?

**Comment by tacaswell** [comment]
@burnpanck Can you make a new issue for the second?
