### ISSUE TITLE
Matplotlib pyplot

### ISSUE THREAD

**Issue by mirfanud** [matplotlib/matplotlib#8064]
### Bug report

When I use the code as:
from matplotlib import pyplot as plt
plt.figure()

It gives error as:
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

But the code given below runs fine:
from matplotlib import pyplot as plt
plt.plot([1,2,3])
plt.show()

**Code for reproduction**

from matplotlib import pyplot as plt
# other lines of code
plt.figure()

**Actual outcome**

libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Matplotlib version**

I am using macos 10.12.3, python3.6 and OpenCV3.2.0.

**Comment by tacaswell** [comment]
How did you install all of your libraries?  This looks like some sort of crossed builds at the c/c++ layer.  I suggest removing and re building/installing everything.

**Comment by tacaswell** [comment]
Closing due to this being quite for 6mo.  @mirfanud I suggest trying at https://mail.python.org/mailman/listinfo/matplotlib-users if you still need help.
