### ISSUE TITLE
Please add Vega in perception documentation

### ISSUE THREAD

**Issue by sbillinge** [matplotlib/matplotlib#8073]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report

**Bug summary**

Vega is missign from the perception documentation:
http://matplotlib.org/users/colormaps.html

**Comment by afvincent** [comment]
@sbillinge Indeed. Thank you for reporting it!

@tacaswell I just saw that they were aliases `Vega*`/`tab*` for colormaps. Which one should be used in this documentation?

*Note to myself:* the colormap `Wistia` (to make colorblind-friendly heatmaps) seems to be missing too from the documentation. Do not forget to add too it.

**Comment by anntzer** [comment]
@afvincent Use tab everywhere, see discussion at https://github.com/matplotlib/matplotlib/pull/7639.

**Comment by afvincent** [comment]
@anntzer Thank you. I will do that.

**Comment by NelleV** [comment]
More specifically, vega colormaps are deprecated.

**Comment by tacaswell** [comment]
This should target 2.0.0-doc / be backported there please.
