### ISSUE TITLE
zorder is not respected by all parts of `errorbar` #1622 problem in matplotlib 2.0.0

### ISSUE THREAD

**Issue by fkbreitl** [matplotlib/matplotlib#8087]
Is see 

zorder is not respected by all parts of `errorbar` #1622

in matplotlib 2.0.0.

See also

https://stackoverflow.com/questions/14003572/how-to-force-errorbars-to-render-last-with-matplotlib

**Comment by dstansby** [comment]
I can confirm that this is still an issue; as @tacaswell mentions in #1622 it is probably quite hard to solve. I'll reopen #1622 since the code in that bug report still doesn't behave.

In the meantime, passing `zorder=3` to `plt.errorbar` seems to fix the problem.
