### ISSUE TITLE
Spectrogram of large arrays behaves badly on MacOSX backend

### ISSUE THREAD

**Issue by piannucci** [matplotlib/matplotlib#8090]
I'm getting partial images and crashes on 2.0.0 (from MacPorts), MacOSX backend, Python 3.4.6, OS X 10.11.6.

This one segfaults in agg:

```python
import numpy as np
import pylab as pl
pl.specgram(np.random.standard_normal(40000000)*1j, Fs=4e6)
```

With my actual dataset, rather than random numbers, I get results like this, with chunks of image missing:

<img width="972" alt="Bad spectrogram" src="https://cloud.githubusercontent.com/assets/552810/23042563/1c591fe0-f467-11e6-86df-1487e2f32cbc.png">

**Comment by piannucci** [comment]
[crash log.txt](https://github.com/matplotlib/matplotlib/files/781642/crash.log.txt)

**Comment by dstansby** [comment]
In case it's useful, I get the rather shorter error (on OSX, MacOSX backend, python 3.5, matplotlib master)
```
>>> pl.show()
/Users/Emily/miniconda3/bin/pythonw: line 3:  1263 Segmentation fault: 11  /Users/Emily/miniconda3/python.app/Contents/MacOS/python "$@"
```

**Comment by dopplershift** [comment]
I can reproduce locally on 2.0.0 on Python 3.6. Seems to work fine now on both 2.0.2 and 2.1.0, so I'm going to close.

Feel free to re-open if you're still having problems.
