### ISSUE TITLE
matplotlibrc doesen't work

### ISSUE THREAD

**Issue by tedoreve** [matplotlib/matplotlib#8098]
### Bug report

**Bug summary**

- I change the default colormap in matplotlibrc, but it dosen't work after I reboot the editor. It still shows previous colormap. 

**Code for reproduction**

The directory of matplotlibrc is 'D:\software\Anaconda\Lib\site-packages\matplotlib\mpl-data'.
I change the default 'image.cmap   :  viridis' to 'image.cmap   : jet'  just like

```matplotlibrc
### IMAGES
#image.aspect : equal             # equal | auto | a number
#image.interpolation  : nearest   # see help(imshow) for options
#image.cmap   : jet               # A colormap name, gray etc...
#image.lut    : 256               # the size of the colormap lookup table
#image.origin : upper             # lower | upper
#image.resample  : True
#image.composite_image : True     # When True, all the images on a set of axes are
                                  # combined into a single composite image before
                                  # saving a figure as a vector graphics file,
                                  # such as a PDF.
```

**Matplotlib version**

- Matplotlib 2.0.0, Python 3.6 on Windows
- I use Anaconda 4.3.0, updating through 'conda update anaconda'

**Comment by efiring** [comment]
You must remove the leading hash character from the line you want to make active.  Everything following a hash character is interpreted as a comment.
