### ISSUE TITLE
XKEYBOARD extension not present on the X server

### ISSUE THREAD

**Issue by JOJO-IAP** [matplotlib/matplotlib#8104]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report
Qt: XKEYBOARD extension not present on the X server
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Qt: Failed to compile a keymap!
**Bug summary**
when I import the matplotlib.pyplot, there is an Qt:XKEYBOARD extension not present on the X server

- A short 1-2 sentences that succinctly describes the bug

**Code for reproduction**

- A minimum code snippet required to reproduce the bug, also minimizing the number of dependencies required

```python
 import matplotlib.pyplot as plt
#
```

**Actual outcome**
In [2]: Qt: XKEYBOARD extension not present on the X server.
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Qt: Failed to compile a keymap!
Current XKB configuration data search paths are: 
/user/local/~,ect
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
- The output produced by the above code, which may be a screenshot, console output, etc.

```
# If applicable, paste the console output here
#
#
```
![image](https://cloud.githubusercontent.com/assets/25686344/23110799/f770a31a-f75e-11e6-8b1e-238f26ff05ff.png)

**Expected outcome**

- A description of the expected outcome from the code snippet
- If this used to work in an earlier version of Matplotlib, please note the version it used to work on

**Matplotlib version**

- Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
matplotlib version:2.0.0, Python version: 3.6.0; Platform: Linux
- How did you install Matplotlib and Python (pip, anaconda, from source ...)
anaconda

**Comment by tacaswell** [comment]
Do you expect interactive windows to work on this system (ex, not ssh'd into a headless box)?

Can you try

```
from PyQt5 import QtWidgets
qapp = QtWidgets.QApplication([''])
```

I suspect this will also fail.

Another thing that looks weird is that `qt-3.3` is in the search path which makes me think there is an installation issue. Can you try in a new enviroment (`conda create -n mpl_test ipython matplotlib` then `source activate mpl_test`)?

**Comment by Thomas-van-Dijk** [comment]
got the same issue:
looks similar to this: https://github.com/spyder-ide/spyder/issues/3713

**Comment by tacaswell** [comment]
What is RDS?

Closing as the OP has not responded and from the spyder issue this seems to be an upstream (Qt5) or configuration issue which Matplotlib can not do anything about.

**Comment by Thomas-van-Dijk** [comment]
*RDC Remote Desktop Connection
