### ISSUE TITLE
Cannot set the markeredgecolor by default

### ISSUE THREAD

**Issue by rlopezcoto** [matplotlib/matplotlib#8109]
In the new matplotlib version (2.0.0) one can still set the markeredgewidth in matplotlibrc 

lines.markeredgewidth: 1.0

but the markeredgecolor is now by default equal to the markerfacecolor, therefore increasing the edge color has the same effect as increasing the size of the marker.

I would like to set by default the markeredge color in matplotlibrc (which at the moment cannot), so a good solution might be to allow the user to set in matplotlibrc

lines.markeredgecolor : k

Thanks for the help!

**Comment by asafpm** [comment]
Setting the markeredgecolor by defining axes.prop_cycle in matplotlibrc like:
`axes.prop_cycle : cycler('color', ['r', 'g'])+cycler('markeredgecolor', ['k', 'b'])`
seems to work when using pyplot.plot(x,y,'o') but it breaks for pyplot.errorbar(x,y,yerr,fmt='o') saying
`AttributeError: Unknown property markeredgecolor`
I am not sure if this is a bug or an unintended use of axes.prop_cycle but the ability to define markeredgecolor for each element in the cycler would be great.

**Comment by tacaswell** [comment]
@asafpm That is an issue with style parameters of all the artists not being consistent.

**Comment by crstnbr** [comment]
Any idea on when this will be supported?

**Comment by jklymak** [comment]
Someone else just needs to review #8479

**Comment by timhoffm** [comment]
Closed by #8479.
