### ISSUE TITLE
Issue with sub-setting minor-ticks at intermediate number of decades

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8111]
@efiring reports that sub-sampling minor-ticks for an intermediate number of decades leads to un-interpretable plots (because there are unlabeled).

We should probably just drop this sub-sampling (by default).

**Comment by anntzer** [comment]
Minimal example:
`loglog([1, 1e9], [1, 1e9])`
![figure_1](https://cloud.githubusercontent.com/assets/1322974/24117478/a156de1c-0d67-11e7-8b7a-90a8ba7c31b8.png)

**Comment by NelleV** [comment]
Proposed solutions during the call:
(1) removing minor tick subsampling.
(2) minors ticks should not be displayed in major ticks are subsampled.

**Comment by efiring** [comment]
Closed by #8381.
