### ISSUE TITLE
Inconsistent inset_axes position between show(), savefig(format='png') and savefig(format='pdf')

### ISSUE THREAD

**Issue by sorenrasmussen** [matplotlib/matplotlib#8120]
### Bug report

**Bug summary**

inset_axes inconsistently positioned between show(), savefig(...,format='png') and savefig(...format='pdf') when the dpi option is set.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

fig = plt.figure(dpi=150);

ax1 = plt.gca()
ax1ins1 = inset_axes(ax1, width=.7, height=.7,bbox_to_anchor=(100,100))

plt.savefig("test.pdf",format='pdf',dpi=300,bbox_inches="tight")
plt.savefig("test.png",format='png',dpi=300,bbox_inches="tight")
plt.show()
```

**Actual outcome**

PDF:
![test_pdf](https://cloud.githubusercontent.com/assets/2952894/23159357/c45ab064-f822-11e6-976d-c07ac03b6152.png)
PNG:
![test](https://cloud.githubusercontent.com/assets/2952894/23159386/e0d785a0-f822-11e6-8ca5-27d3cdf2d612.png)
show():
![show](https://cloud.githubusercontent.com/assets/2952894/23159382/de06cf84-f822-11e6-92ae-5c3c4ff2e5a5.png)

**Expected outcome**

I would expect all the results to come out the same.

**Matplotlib version**

- Matplotlib 2.0.0 (conda)
- Python 2.7.13 (conda)
- Platform: Linux

**Comment by sorenrasmussen** [comment]
**Note:**
Setting `bbox_transform=ax1.figure.transFigure` for the the `inset_axes` makes the positioning consistent. However, I would still expect it to be consistent without doing so.

**Comment by tacaswell** [comment]
Setting the figure dpi to 300 should also work.

There is a dpi dependence in there someplace...

**Comment by sorenrasmussen** [comment]
Setting the figure DPI to 300 makes the PNG look right, but not the PDF.

**Comment by tacaswell** [comment]
attn @jklymak as another case of pdf / dpi issues

**Comment by jklymak** [comment]
Yes.  I think it's easy to fix (in general I think the rendered width should just return 72 times the inches width so it's in pdfs dpi units like the other backends.  But terrifying to then fix all the workarounds that have been added here and there!

**Comment by ImportanceOfBeingErnest** [comment]
I updated the documentation of `inset_axes` in #11060. Among other things it now includes the sentence

> Note that the units of the bounding box are determined through the
transform in use. When using *bbox_to_anchor* it almost always makes
sense to also specify a *bbox_transform*. This might often be the axes
transform *parent_axes.transAxes*.

There are also several examples added. The code does not forbid to specify a bounding box in pixels and use the default transform=None (i.e. the display coordinates), as this may still be useful in some limited cases. However I hope that the docs and examples are now clear enough such that people will not try to position something in pixel coordinates and then wonder why there is some dpi dependence introduced.

**Comment by jklymak** [comment]
I think this has substantively been fixed by the doc changes...
