### ISSUE TITLE
Actually deprecate Axes.axesPatch, Figure.figurePatch

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8124]
These aliases for Axes.patch and Figure.patch were intended as deprecated 8 years ago in https://github.com/matplotlib/matplotlib/commit/40f24d5af26de9b512acf3ee45ad695374454da3.  See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/figure.py#L335 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_base.py#L1083.

They should be replaced by deprecation-raising properties, and examples updated appropriately.

**Comment by dstansby** [comment]
Closed by #8150
