### ISSUE TITLE
ENH: Allow `mpl_configdir/stylelib` to point to URLs

### ISSUE THREAD

**Issue by CJ-Wright** [matplotlib/matplotlib#8125]
Would it be possible for the files in `mpl_configdir/stylelib` to point to URLs?
Eg. `style.use('presentation')` points to the `mpl_configdir/stylelib/presentation.mplstyle` which points to a URL based stylesheet
This could be very helpful for my group as we are trying to share a couple of style sheets on the internet.

**Comment by QuLogic** [comment]
You can do `style.use('http://example.com/stylelib/presentation.mplstyle')` already.

**Comment by CJ-Wright** [comment]
I understand that, however I think most of my potential users would prefer to just write `presentation` similar to how it would be if the stylesheet was in the local config folder.

**Comment by tacaswell** [comment]
This already basically works

```python
presentation_style = 'http://url'
style.use(presentation_style)
```

@danielballan did this in grad schoool. See http://matplotlib.org/api/style_api.html#matplotlib.style.use

I do not see a way to implement this that is not more complicated than it is worth.
