### ISSUE TITLE
bad error message from pyplot.plot

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [matplotlib/matplotlib#8131]
### Bug report

**Bug summary**

The following sequence of ipython commands causes a hard-to-decipher error message.  Is it possible to provide a better error message?

**Code for reproduction**

In [1]: x= range(200000)
In [2]: pyplot.plot(x, sin(x))
Out[3]: [<matplotlib.lines.Line2D at 0x7c2a3c8>]
In [3]: pyplot.show()

**Actual outcome**

<snip>

OverflowError: In draw_path: Exceeded cell block limit

**Matplotlib version**

1.5.1

- How did you install Matplotlib and Python (pip, anaconda, from source ...)

EPD

**Comment by WeatherGod** [comment]
I believe this bug has been fixed. If I remember correctly, it was a
macosx-only bug. Could you try v1.5.3 or even v2.0.0?

**Comment by QuLogic** [comment]
Unfortunately, I can still reproduce with 2.0.0.

**Comment by tacaswell** [comment]
Set `rcParams['agg.path.chunksize'] = 1000` or so.

 - add reference to the 'agg.path.chunksize' rcparam to the error message



@pmfeldman Please include the full traceback in the future.

**Comment by herilalaina** [comment]
Is there already someone working on this issue? If not I would like to take it

**Comment by anntzer** [comment]
Go for it.

**Comment by patniharshit** [comment]
@herilalaina are you doing it?

**Comment by herilalaina** [comment]
yes, I am working on it. sorry, I saw the confirmation very late

**Comment by anntzer** [comment]
Closed by #8176, I think...
