### ISSUE TITLE
check imshow performance

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8143]
see https://github.com/matplotlib/matplotlib/pull/8024#discussion_r103022128

 - Check if using `&` instead of `*` reduces run time and if the memory foot print can be reduced
 - micro-bench mark changes

**Comment by souravsingh** [comment]
@tacaswell I am interested in working on the issue. How do I benchmark the changes?

**Comment by tacaswell** [comment]
Using something like `%timeit` is a good start.

**Comment by eozcelik** [comment]
```
X = np.arange(100)
X = X.reshape(5, 20)

fig = plt.figure()
ax1 = fig.add_subplot(311)
print(timeit.timeit("ax1.imshow(X, interpolation='nearest')", "from __main__ import ax1, X", number=10000))
```
@tacaswell  I have used the above snippet to test time performance and `&` seems to perform better than `*` after second or third decimal place in timeit output

Should I be trying to localise the result in AxesImage.make_image ?

**Comment by tacaswell** [comment]
Closing this as https://github.com/matplotlib/matplotlib/pull/8966 re-wrote this code path and should have decreased the memory footprint.
