### ISSUE TITLE
Use Agg backend by default if DISPLAY is not set

### ISSUE THREAD

**Issue by infinity0** [matplotlib/matplotlib#8147]
SageMath makes some matplotlib plots as part of its tests but these fail if DISPLAY is unset. This is the case on different autobuilders. The failures can be avoided by adding `matplotlib.use('Agg')` in the early parts of the tests, as suggested by [this stackoverflow post](https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable) but I wonder if matplotlib should be doing this itself automatically. It would certainly be a neater solution than to patch SageMath.

See [here](https://trac.sagemath.org/ticket/22441) for the corresponding ticket on their trac.

**Comment by anntzer** [comment]
A similar idea was rejected in #2723 (when MPLBACKEND wasn't even available).
