### ISSUE TITLE
Long lines in literal blocks run off the edge of the page

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#8153]
e.g.
![screen shot 2017-02-25 at 12 44 54](https://cloud.githubusercontent.com/assets/6197628/23339265/7bf86d1e-fc16-11e6-9928-9cd2e7df1f6a.png)

I assume the fix is to make the box scrollable, which would probably be an upstream fix.

**Comment by tacaswell** [comment]
might also be in the templates..

**Comment by NelleV** [comment]
I don't think the appropriate fix is to add a scrollbar: this line should never have been that long in the first place.

**Comment by anntzer** [comment]
Why not?  This *is* the output of `git lg` as defined in the docs.

**Comment by NelleV** [comment]
The subject line of a git commit should be less than 50 caracters, while the body should be wrapped into 72 caracters line.

Even if you don't consider this, scrollbars are terrible UI designs.

**Comment by NelleV** [comment]
(I find the guidelines on writing git commit messages very stringent, and often don't follow them myself, but there is a difference between writing 80 caraters line, and a full paragraph in the title. These are bad practices, and we should not advertise them in our documentation.

**Comment by anntzer** [comment]
The output of `git lg` can *still* overrun the limit (due to the SHA1 and branch name being prepended), but I agree with you that this specific piece is a bad example.
