### ISSUE TITLE
Doc: Restructure environment variables in `Installing from source` docs

### ISSUE THREAD

**Issue by aashil** [matplotlib/matplotlib#8159]
### Bug report

**Bug summary**

The command to export environment variables(CC, CXX, PKG_CONFIG) required for installing from sources is displayed on the same line. They should be listed on three separate lines making it more reader friendly. 
![screenshot from 2017-02-26 14-16-56](https://cloud.githubusercontent.com/assets/6216576/23342844/536e2938-fc2f-11e6-90af-6bb6d667d55b.png)

I would like to submit a PR once someone acknowledges this issue.

**Comment by anntzer** [comment]
Go ahead, it should have the same style as the block just below.

Same page, there's an extra space (twice) after the opening parenthesis in
> Microsoft Visual C++ 2008 ( 64 bit or 32 bit for Python 2.7) or Microsoft Visual C++ 2010 ( 64 bit or 32 bit for Python 3.4)
