### ISSUE TITLE
Using plt.ion with startup commands

### ISSUE THREAD

**Issue by Kodiologist** [matplotlib/matplotlib#8160]
I'm running matplotlib 2.0.0, installed with pip, with the TkAgg backend and Python 3.5.2 on Lubuntu 16.10. If I open the Python REPL and type

    >>> import matplotlib.pyplot as plt
    >>> plt.ion()
    >>> plt.plot([1, 2, 3])

then, as I expect, a Tk window with the figure appears after the final command.

However, if I instead do:

    >>> import matplotlib.pyplot as plt
    >>> plt.plot([1, 2, 3])
    >>> plt.ion()
    >>> plt.plot([4, 5, 6])

no figure window appears, even after the last command. It seems that running any plotting command before `plt.ion` prevents it from having its usual effect.

You might ask why I don't just make sure to type `plt.ion()` first. The answer is I have a function named `matplotlib_prelude` containing some startup commands that's run automatically when I start the Python REPL, and if I call `plot.ion` before this, a figure window will open even though I haven't plotted anything yet (and indeed I may not use matplotlib at all this session). Here's what I have in `matplotlib_prelude` at the moment:

    import matplotlib.pyplot as plt
    plt.tick_params(right = False, top = False)
    plt.gca().spines["top"].set_visible(False)
    plt.gca().spines["right"].set_visible(False)

This used to work before matplotlib 2: I called `plt.ion` first, and these startup lines didn't cause a figure window to open.

**Comment by QuLogic** [comment]
I wonder if perhaps instead of this `matplotlib_prelude`, you might want to set some `rcParams` in your [`matplotlibrc` file](http://matplotlib.org/users/customizing.html#the-matplotlibrc-file). This should be equivalent to what you're running:
* `axes.spines.right: False`
* `axes.spines.top: False`
* `xtick.top: False`
* `ytick.right: False`

You could also set up a style as documented on that same page.

**Comment by Kodiologist** [comment]
Oddly, having a `matplotlibrc`, even an empty one, prevents the window from popping up when I do

    >>> import matplotlib.pyplot as plt
    >>> plt.ion()
    >>> plt.plot([1, 2, 3])

**Comment by QuLogic** [comment]
Does it also stop the window from showing up even after `plt.show()`?

**Comment by Kodiologist** [comment]
No. That works as usual.

**Comment by Kodiologist** [comment]
And now it's working for some reason. I upgraded to Python 3.6, so maybe that had something to do with it. Or perhaps it's setting a backend in my matplotlibrc, which I hadn't before.
