### ISSUE TITLE
Autowrapping text doesn't work in "What's New in Matplotlib 1.5" example

### ISSUE THREAD

**Issue by katzenbaer** [matplotlib/matplotlib#8169]
**Bug summary**

The [Auto-wrapping Text example](http://matplotlib.org/users/prev_whats_new/whats_new_1.5.html#auto-wrapping-text) in the What's New in Matplotlib 1.5 document doesn't seem to work.

![screen shot 2017-02-27 at 10 04 47 pm](https://cloud.githubusercontent.com/assets/1815591/23393614/e4bc149a-fd38-11e6-84cc-23243045c0ef.png)

**Actual outcome**

Text is wrapped, but displays outside the figure.

**Expected outcome**

Text is wrapped and displays inside the figure.

**Comment by QuLogic** [comment]
You are confusing the `Figure` and the `Axes`; as noted in the description, the text is wrapped to the `Figure`.

**Comment by katzenbaer** [comment]
Yeah. I realized this too while driving home from work. Sorry for the inconvenience!
