### ISSUE TITLE
3D Arrow Plot

### ISSUE THREAD

**Issue by Seanny123** [matplotlib/matplotlib#8170]
### Bug report

**No 3D version of arrow plot**

- Although in a 2D plot, it's possible to do `plt.arrow()` the 3D equivalent has yet to been implemented.

I'm going to try and implement a 3D version of the arrow plot based off [this code](http://stackoverflow.com/a/22867877/1079075) and would like some guidance.

1. Should I modify `matplotlib/lib/mpl_toolkits/mplot3d/axes3d.py` to include this new function or should it go somewhere else?
2. Is the signature `def arrow(self, x, y, z, dx, dy, dz, **kwargs):` to match the 2D version of `def arrow(self, x, y, dx, dy, **kwargs):` acceptable?

**Comment by dstansby** [comment]
I'm not an expert at all, but somewhere in the code there must be the ability to plot arrows in 3D as we already have a 3D version of `plt.quiver()`. Either way it would be great to have a 3D version of `plt.arrow()`!

http://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#quiver

**Comment by WeatherGod** [comment]
1. yes, the arrow function should go into axes3d.py, although feel free to
create any sort of submodule in mplot3d for code that might be
generalizable.
2. yes, that signature is fine.

The arrows in the 3d streamplots are a bit hacky, but they got the job
done. If we can improve that and use it in both places, that would be
great! There is also another PR that wants to add 3d errorbars (similar,
but not quite the same thing), but is having difficulties because 3d
markers aren't well-implemented.

**Comment by Seanny123** [comment]
Looking over [the errorbar code](https://github.com/matplotlib/matplotlib/pull/8031/files) and the quiver code, it has become apparent to me that this is beyond my current skill level and time resources.

In other words, I'm a wimp who hasn't yet acquired the Linear/Geometrical algebra skills required to do this properly. If someone else wants to take a shot at this, ping me when you need a reviewer. Otherwise, I'll come back when I'm ready to face the challenge.

**Comment by tacaswell** [comment]
@Seanny123 I have always found learning is best motivated by a problem I was solving.

**Comment by russkel** [comment]
This seems to work quite well for me: https://gist.github.com/jpwspicer/ea6d20e4d8c54e9daabbc1daabbdc027

**Comment by thohemp** [comment]
@russkel Link is dead.

Is there a new info or workaround regarding this issue?

**Comment by russkel** [comment]
@thohemp sorry I have completely forgotten what that was. It also wasn't my code.
