### ISSUE TITLE
Update list of dependencies to build docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8174]
The list at http://matplotlib.org/devdocs/devel/documenting_mpl.html#getting-started (sphinx+numpydoc) is outdated.  Compare with https://github.com/matplotlib/matplotlib/blob/master/doc/README.txt#L8 (sphinx numpydoc ipython mock colorspacious pillow).

**Comment by vidursatija** [comment]
Can I resolve this issue?

**Comment by vidursatija** [comment]
I've made the changes in my commit. I haven't built the docs using Sphinx. This can be found at #8191

**Comment by NelleV** [comment]
This whole document is severely outdated. I'd be in favor of removing it entirely.

**Comment by story645** [comment]
Close? think @choldgraf also did this in #8536 and #8544

**Comment by choldgraf** [comment]
I think so (though TBH I'd be +1 for adding a pandas dependency...guess that bridge can be crossed when we come to it though ;-) )
