### ISSUE TITLE
Add badges to README.rst

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8177]
README.rst could display some badges for ease of access to CI/docs/etc. (compare with https://github.com/scikit-learn/scikit-learn):
- Travis/Appveyor/Codecov
- docs
- pypi package
- gitter (move it up rather than being somewhere in the middle, which is not very practical).
- possibly depsy (as on matplotlib.org) / zenodo / python versions but I don't feel strongly about them.

I would also either remove the depsy and travis badges, or make the list match whatever is on the README.rst on matplotlib.org (but I don't really think a CI badge belongs to a static doc site).

**Comment by dstansby** [comment]
Closed by #8178
