### ISSUE TITLE
What is the use of Tick.set_label2 and can we make it useful?

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#8181]
Coming from this question,  [How to set tick label2 in matplotlib](http://stackoverflow.com/questions/42532687/how-to-set-tick-label2-in-matplotlib) at stackoverflow, I wonder what the use of [`YTick.set_label2`](http://matplotlib.org/2.0.0/api/_as_gen/matplotlib.axis.YTick.set_label2.html#matplotlib.axis.YTick.set_label2) is. It says *"Set the text of ticklabel2"* but actually any text set to it is [overwritten at drawtime](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axis.py#L1039) by the text of the label (or label1). 

Also, `ax.yaxis.set_ticklabels()` cannot be used to independently set the label2, as the same text seems to be [written into both](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axis.py#L1605) Text instances.

Finally, there is only one single formatter for each axis, and both, label1 and label2 share that same formatter.

There are several questions arising from that:
(1) Why is there a `set_label2` method at all, if it actually only copies text from label1.
(2) The original question: How to use a different text for label2 as for label1
(3) The wishlist question: Can we have a independent formatter for label2, which would make this label2 actually useful (e.g. show the same data in two different units, show correlated data in terms of two different quantities etc.)

**Comment by WeatherGod** [comment]
attn: @efiring. I know you told me once what it was, but I can't remember
the answer for the life of me.
