### ISSUE TITLE
Axes doesn't have ``legends`` attribute?

### ISSUE THREAD

**Issue by katzenbaer** [matplotlib/matplotlib#8187]
In the [Artist tutorial](http://matplotlib.org/users/artists.html#axes-container), it says that ``Axes`` have a ``legends`` attribute that is "A list of Legend instances". However, my Axes don't seem to have this attribute using matplotlib v2.0.

Is the tutorial wrong or is there a regression in matplotlib?

![screen shot 2017-03-02 at 3 12 24 pm](https://cloud.githubusercontent.com/assets/1815591/23531295/a8f5608c-ff5a-11e6-9af7-6ec9c0753ea4.png)

![screen shot 2017-03-02 at 3 06 23 pm](https://cloud.githubusercontent.com/assets/1815591/23531231/589df572-ff5a-11e6-8414-9bdb3d5fa587.png)

**Comment by tacaswell** [comment]
I think the tutorial has been wrong for a very long time (`Figure` objects do have `legends` attribute though).

As near as I can tell `Axes` never had an `legends` attribute and the legends guide even explains a work around to the hard-coded 1:1 mapping of legend to axes (http://matplotlib.org/users/legend_guide.html#multiple-legends-on-the-same-axes).

That particular line goes back to 2008 (f0f28a3efe8893fbde96a7f81388062030a1b2ee).

Checking out that commit and searching for legends gives:

```
✔ ~/source/p/matplotlib [:f0f28a3ef|⚑ 8] 
18:41 $ git grep legends
CHANGELOG:2005-10-26 Added support for scatter legends - thanks John Gill
doc/users_guide/artist_api_tut.txt:legends               A list of Figure Legend instances (different from Axes.legends)
doc/users_guide/artist_api_tut.txt:ax.legend - axes legends         Legend                ax.legends
doc/users_guide/artist_api_tut.txt:legends           A list of Legend instances
docs/users/artists.rst:legends               A list of Figure Legend instances (different from Axes.legends)
docs/users/artists.rst:ax.legend - axes legends         Legend                ax.legends
docs/users/artists.rst:legends           A list of Legend instances
examples/pylab/legend_auto.py:algorithm, but shows lots of different ways to create legends so is
lib/matplotlib/axes.py:        legends), linewidth, anitialising, marker face color, etc.  Here is an
lib/matplotlib/backends/backend_emf.py:        # legends where the circles are small anyway, and it is
lib/matplotlib/figure.py:        children.extend(self.legends)
lib/matplotlib/figure.py:        self.legends = []
lib/matplotlib/figure.py:        for legend in self.legends:
lib/matplotlib/figure.py:          'best' : 0,          (currently not supported for figure legends)
lib/matplotlib/figure.py:        self.legends.append(l)
lib/matplotlib/legend.py:  'best'         : 0, (only implemented for axis legends)
lib/matplotlib/legend.py:      'best'         : 0, (only implemented for axis legends)
lib/matplotlib/legend.py:    codes = {'best'         : 0, # only implemented for axis legends

```

**Comment by katzenbaer** [comment]
Then assuming I am in the one-legend-per-Axes scenario, is accessing the `Axes`'s legend via the `legend_` instance variable the officially supported (and more importantly – safe) method?

**Comment by tacaswell** [comment]
There is a `get_legend()` method that is what should probably be used.  Not sure what the trailing `_` means here...

**Comment by katzenbaer** [comment]
Oh, didn't realize there was a `get_legend()` method. I think the trailing `_` is to avoid conflict with the `legend()` method, although it's an interesting choice to have it as `legend_` instead of `_legend`.
