### ISSUE TITLE
Shortcut for moving the axis tick labels to the right side of a set of subplots when sharey=True?

### ISSUE THREAD

**Issue by naught101** [matplotlib/matplotlib#8188]
With subplots, the axis tick labels are on the left, and it's quite hard to move them to the right:

```python
nrows = 4
ncols = 3
labels = ['One', 'Two', 'Three', 'Four']
fig, axes = subplots(nrows, ncols, sharey=True, sharex=True)
for i, label in enumerate(labels):
     axes[i, 0].set_ylabel(label)

     [l.set_visible(False) for l in axes[i, 0].get_yticklabels()]
     axes[i, -1].yaxis.tick_right()
     axes[i, -1].yaxis.set_visible(True)
```

![figure_1](https://cloud.githubusercontent.com/assets/167164/23533060/6b7dbac0-0003-11e7-9ef8-d463c53f0b68.png)

It took me ages to work this out, and it feels like there should be a simpler way. Possibly I'm missing something, but if not, it would be nice to have a few new parameters to `subplots()`, perhaps:

```python
yaxis = ['left', 'right']  # move the whole axis, label, ticks, tick labels
yticks = ['left', 'right']  # Just move the ticks and labels
ylabel = ['left', 'right']  # Just move the axis titles to the right
```

And it would be nice to have all of these available for the xaxis too.

**Comment by anntzer** [comment]
Would
```
    axes[i, 0].tick_params("y", left=False, labelleft=False)
    axes[i, -1].tick_params("y", right=True, labelright=True)
```
be simple enough for you?

**Comment by naught101** [comment]
@anntzer that's definitely better than my version, but I think it's still overly complex and not very discoverable...

**Comment by anntzer** [comment]
In fact you can even do without the `"y"`:
```
    axes[i, 0].tick_params(left=False, labelleft=False)
    axes[i, -1].tick_params(right=True, labelright=True)
```

Rather than making the API even more complex, I would suggest adding an example at the end of the docstring of `subplots` (which should be just as discoverable).

**Comment by mollyrossow** [comment]
ping @chendaniely

**Comment by timhoffm** [comment]
The best solution is https://github.com/matplotlib/matplotlib/issues/8188#issuecomment-283869421.

I don't think there's a good place/discoverable way to put it in the documentation. Therefore, I'm closing as non-actionable. Additionally, this issue did not  get much attention from users, so it seems not too important.
