### ISSUE TITLE
pip install matploblib broken

### ISSUE THREAD

**Issue by adamcavendish** [matplotlib/matplotlib#8189]
if I use `pip3 install -U matplotlib`, I just get broken matplotlib with `mpl_toolkits`.

For instance, view `/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py`, and I got:

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from matplotlib.externals import six

from .axes3d import Axes3D
```

And this seems to be like the second last commit from now.

https://github.com/matplotlib/matplotlib/blob/8fe495a705153bdb7a224f58c02d54272c321094/lib/mpl_toolkits/mplot3d/__init__.py

Environment:
* Ubuntu 16.04
* Python 3.5
* Matplotlib (2.0.0-1)

**Comment by jenshnielsen** [comment]
You are most likely installing on top of another non pip installed version of matplotlib. Due to mpl_toolkits being a namespace package that does not work very well. I suggest pip uninstalling matplotlib and manually removing any remains of matplotlib from the /usr/lib/python3/dist-packages directory and then try pip installing again

**Comment by adamcavendish** [comment]
@jenshnielsen  Yes, I've already done it, and still get the result. And I tried another ubuntu pc, and got the same result again.

**Comment by matthew-brett** [comment]
When I install matplotlib via pip it gets installed into `/usr/lib/python3.5/site-packages/matplotlib` not `dist-packages` as you have, and the result of `cat /usr/lib/python3.5/site-packages/mpl_toolkits/mplot3d/__init__.py` is:

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import six

from .axes3d import Axes3D
```

So I think the code you are looking at must be from the Ubuntu matplotlib package.

**Comment by adamcavendish** [comment]
@matthew-brett Interesting, probably the pip was installing from the ubuntu source?

Anyway, if anyone come across such issue, you can:

1. `pip uninstall matplotlib`
2. `pip install git+https://github.com/matplotlib/matplotlib.git`
(You can also install a specific branch: `pip install git+https://github.com/matplotlib/matplotlib.git@v2.0.x`)

It fixed my issue.

**Comment by matthew-brett** [comment]
No, I don't think pip can install from the Ubuntu sources.  I think Jens was right, that you were seeing the effect of having the Ubuntu matplotlib package clashing with the pip-installed package.

When you run pip, you should see:

```
Collecting matplotlib
  Downloading matplotlib-2.0.0-1-cp35-cp35m-manylinux1_x86_64.whl (14.7MB)
```

Is that what you see?

**Comment by adamcavendish** [comment]
Yes, it is. If we can manually upgrade `mpl_toolkit`, I'd think it'll be better

**Comment by jenshnielsen** [comment]
In the long term it would be best to change mpl_toolkits so it's no longer a name space package. But that requires changes to basemap and other packages that install into mpl_toolkits plus a long deprecation cycle

**Comment by matthew-brett** [comment]
Clearing up a couple of points:

* @adamcavendish - Jens suggested clearing out any copies of `matplotlib` in `/usr/lib/dist-packages`; I suspect that you did just that, but left the `mpl_toolkits` directory untouched, which would explain why the problem remained;
* I can't explain why doing a pip install from source fixed the problem.  Can I confirm that `/usr/lib/dist-packages` still has the previous presumably `apt` installed `mpl_toolkits`? Does it have a not-empty `matplotlib` directory?
