### ISSUE TITLE
Sample data not found

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#8194]
### Bug report

`python3.5/site-packages/matplotlib/mpl-data/sample_data/grace_hopper.png` not found.

```
>>> image_file = cbook.get_sample_data('grace_hopper.png')
>>> image = plt.imread(image_file)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-dd6f8285e5f3> in <module>()
      4 
      5 
----> 6 image_file = cbook.get_sample_data('grace_hopper.png')
      7 image = plt.imread(image_file)
      8 

/home/atcold/anaconda3/lib/python3.5/site-packages/matplotlib/cbook.py in get_sample_data(fname, asfileobj)
    831             return gzip.open(path, mode)
    832         else:
--> 833             return open(path, mode)
    834     else:
    835         return path

FileNotFoundError: [Errno 2] No such file or directory: '/home/atcold/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/sample_data/grace_hopper.png'
```

**Matplotlib version**
Latest Matplotlib installed with Conda on Python 3, Ubuntu 16.

**Comment by afvincent** [comment]
Works fine with master and Python 2
```python
In [1]: import matplotlib as mpl

In [2]: mpl.__version__
Out[2]: '2.0.0.post3538+g72cea62'

In [3]: import matplotlib.cbook as cbook

In [4]: image_file = cbook.get_sample_data('grace_hopper.png')
```
*but indeed, I can reproduce it with 2.0.0rc1:*
```python
In [1]: import matplotlib.cbook as cbook

In [2]: image_file = cbook.get_sample_data('grace_hopper.png')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-2-c9bd86fec7fc> in <module>()
----> 1 image_file = cbook.get_sample_data('grace_hopper.png')

/opt/miniconda2/envs/physinet/lib/python2.7/site-packages/matplotlib/cbook.pyc in get_sample_data(fname, asfileobj)
    831             return gzip.open(path, mode)
    832         else:
--> 833             return open(path, mode)
    834     else:
    835         return path

IOError: [Errno 2] Aucun fichier ou dossier de ce type: u'/opt/miniconda2/envs/physinet/lib/python2.7/site-packages/matplotlib/mpl-data/sample_data/grace_hopper.png'

In [3]: import matplotlib as mpl

In [4]: mpl.__version__
Out[4]: '2.0.0rc1'

```

**Comment by phobson** [comment]
Hmm. I *can't* reproduce this on on windows, python 3.6, mpl v2.0.0 from conda-forge

```
In [1]: import sys, matplotlib
In [2]: from matplotlib import pyplot, cbook
In [3]: imgf = cbook.get_sample_data('grace_hopper.png')
In [4]: img = pyplot.imread(imgf)
In [5]: pyplot.imshow(img)
Out[5]: <matplotlib.image.AxesImage at 0x209c2302860>

In [6]: pyplot.show()
```

![image](https://cloud.githubusercontent.com/assets/1163939/23568876/8928f96e-0011-11e7-8b74-80985ca7498a.png)

**Comment by afvincent** [comment]
Well, the computer I used with 2.0.0rc1 is in my lab, so I will only have access to it on Monday.

**Comment by afvincent** [comment]
Huh, something is weird…

On fresh virtual envs with conda, indeed everything seems to be fine (at least with Python 2.7.13 + Matplotlib 2.0.0, Python 2.7.13 + Matplotlib 1.5.3 and Python 3.6 + Matplotlib 2.0.0), as @phobson reported. However, in cases where Matplotlib is installed from conda-forge, the `matplotlib/mpl-data/sample_data` directory appears to be missing (it does neither exist on my old Python 2.7.12 + Matplotlib 2.0.0rc1 setup, nor with a fresh Python 2.7.13 + Matplotlib 2.0.0).

To reproduce it:
```bash
conda create --name test_mpl_from_forge python=2 ipython
conda install --name test_mpl_from_forge -c conda-forge/label/rc -c conda-forge matplotlib
source activate test_mpl_from_forge
ipython
```
and then
```python
from matplotlib.cbook import get_sample_data
img = get_sample_data('grace_hopper.png')  # raises an IOError exception
```

**Comment by QuLogic** [comment]
It's [disabled on conda-forge](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/build.sh#L26); this is something you should report there.

**Comment by Foadsf** [comment]
I had the same issue. From [here](https://stackoverflow.com/a/22282935/4999991) I found the solution.  The problem is with opening a file in the current folder on Windows. so if you want to open  a file you need to do:

`import os
cwd = os.getcwd()
import matplotlib.cbook as cbook
fname = cbook.get_sample_data('%s/foo.bar'%(cwd))`

**Comment by sanster9292** [comment]
I was encountering the same data. I resolved it by upgrading my matplotlib version. The files exists in the current matplotlib GitHub repository as well, so updating your matplotlib should fix it.

**Comment by ddaahk** [comment]
Same issue.  My sample data folder was empty.

Search cbook on github then I dl'd the folder from there and manually copied it to:
C:\Users\###\Anaconda3\envs\####\Lib\site-packages\matplotlib\mpl-data\sample_data

Upgrading matplotlib 2.2.2 did nothing for me. conda-forge or anaconda versions.

Windows 10 Python 3.6. Anaconda

**Comment by shinecurve** [comment]
Same issue. My sample data folder does not exist.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\#####\\Anaconda3\\lib\\site-packages\\matplotlib\\mpl-data\\sample_data\\jacksboro_fault_dem.npz'

Windows 10 1903
Anaconda 2019.3
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
