### ISSUE TITLE
Matplotlib 2.0.0 crashes on plotting contour of array with two dimensions of size 1 in Python 3.4

### ISSUE THREAD

**Issue by jeroenmuller** [matplotlib/matplotlib#8197]
### Bug report

**Bug summary**

Python crashes on plotting contour of array with two dimensions of size 1.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

im = np.array([[0]])
plt.contour(im)

```

**Actual outcome**

```
Python interpreter craches, with this message:
Floating point exception (core dumped) 
```

**Expected outcome**
This is the output I get on Python 2.6.6:
ValueError: zero-size array to reduction operation minimum which has no identity

**Matplotlib version**
Fedora 23, with Matplotlib 2.0.0 and numpy 1.12.0 installed using pip.

**Comment by ianthomas23** [comment]
Fixed by PR #8227.  Thanks for the bug report @jeroenmuller.
