### ISSUE TITLE
tight_layout is incorrect for certain title sizes

### ISSUE THREAD

**Issue by retsyo** [matplotlib/matplotlib#8201]
I am using `Python 3.4.4 |Anaconda 2.3.0 (64-bit)` on win64 bits, with latest `matplotlib` and `pyqt` updated by `conda install xx`
for the following code, if I use unicode title in the for-loop, the images are too small. However, if I use English title, the images' size are expected

This can be observed for both `TkAgg` and `Qt5Agg`

```python
#coding=utf-8
import matplotlib
matplotlib.rcParams['backend'] = 'TkAgg'
#~ matplotlib.rcParams['backend'] = 'Qt5Agg'

from pylab import *
import PIL.Image as Image

im=Image.open('Mario cosplay.jpg').convert('L')

orgsize=im.size
newsize=[int(i/4) for i in orgsize]

subplot(2,3,1)
imshow(im, cmap='gray', vmin=0, vmax=255)
title('original pic', fontsize=20);

filters=[Image.NEAREST, Image.BILINEAR, Image.BICUBIC, Image.ANTIALIAS]
filtersName=['NEAREST', 'BILINEAR', 'BICUBIC', 'ANTIALIAS']
for k in range(len(filters)):
    subplot(2,3,k+2)
    im1=im.resize(newsize, filters[k])
    imshow(im1, cmap='gray', vmin=0, vmax=255)
    #~ title('原图的1/%i，插值法：%s' %  (4, filtersName[k]), fontsize=20)       # bug here
    title('size: 1/%i，interpolation: %s' %  (4, filtersName[k]), fontsize=20)    # no bug

gcf().tight_layout()

show()
```

![unicode_title](https://cloud.githubusercontent.com/assets/7960913/23596231/81cd9694-0263-11e7-96c1-5727af112f0f.png)
![english_title](https://cloud.githubusercontent.com/assets/7960913/23596232/83a9e8fa-0263-11e7-8316-f5b5e8a34932.png)

**Comment by anntzer** [comment]
This actually does have anything to do with unicode.  It's just that for certain title lengths, tight_layout shrinks the axes bbox in a vain attempt of decreasing the title size as well, but of course that doesn't work; for even longer titles it just gives up and doesn't shrink the axes.

Minimalish repro:
```python
from pylab import *

fig, axs = subplots(2, 3)
for ax in axs.flat:
    ax.imshow([[0]])
    ax.set_title("so long tight_layout() just gives up", fontsize=20)
fig.tight_layout()

fig, axs = subplots(2, 3)
for ax in axs.flat:
    ax.imshow([[0]])
    ax.set_title("just long enough to fail", fontsize=20)
fig.tight_layout()

show()
```
![1](https://user-images.githubusercontent.com/1322974/80036444-06d81d00-84f2-11ea-8364-098d7be53bbe.png)
![2](https://user-images.githubusercontent.com/1322974/80036450-08094a00-84f2-11ea-8f8c-a80ed6a4352d.png)

**Comment by jklymak** [comment]
So, I guess its a valid question if `tight_layout` and `constrained_layout` should even care about the title or xlabel for the x-direction calculation, or the ylabel for y-direction calculation.  Shrinking the axes doesn't make more room.  That makes the code more complicated, but maybe not terribly so.

**Comment by anntzer** [comment]
Ah, very good point, I guess we could just exclude them from tightbbox computation (but only in the "irrelevant" direction).
