### ISSUE TITLE
"search" doesn't find cmocean

### ISSUE THREAD

**Issue by denis-bz** [matplotlib/matplotlib#8220]
Try "search cmocean" in the search boxbox on matplotlib.org :
http://matplotlib.org/search.html?q=cmocean&check_keywords=yes&area=default  
    Your search did not match any documents.  
Shouldn't it find  http://matplotlib.org/cmocean/  ? (maybe just a Tuesday morning blip)  
Thanks, cheers

**Comment by dstansby** [comment]
I expect @tacaswell will know the answer to this; I suspect it's because http://matplotlib.org/cmocean/ isn't a part of the main website and is built separately.

**Comment by anntzer** [comment]
Including other sphinx-generated docs does not seem to be an option for sphinx (http://www.sphinx-doc.org/en/stable/markup/toctree.html#special-names).  Closing; maybe report an issue upstream?
