### ISSUE TITLE
matplotlib 3D surface - gaps / holes in surface

### ISSUE THREAD

**Issue by fmevers** [matplotlib/matplotlib#8222]
### Bug report

**Bug summary**

A grid is interpolated with scipy's `griddata()` and contains values and NaNs. However, when the grid is plotted with mplot3d's `plot_surface()` there are gaps in the surface (see upper plot). The lower the view height, the more of such gaps are rendered. When the grid is plotted in 2D with `imshow()` there are no gaps (see lower plot).

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

Z = np.loadtxt('data.txt')
X = np.linspace(0,3,301)
Y = np.linspace(0,3,301)
X = np.array([X,]*(301)).transpose()
Y = np.array([Y,]*(301))
fig = plt.figure(figsize=(15,15), dpi=100)
ax = fig.add_subplot(2, 1, 1, projection='3d')
ax.view_init(40,300)
surf = ax.plot_surface(X, Y, Z, cmap='jet', rstride=1, cstride=1, antialiased=False, shade=False, alpha=1.0, linewidth=0, vmin=0.25, vmax=0.35);

ax.invert_yaxis()
ax.dist = 11

ax = fig.add_subplot(2, 1, 2)
plt.imshow(Z, cmap='jet', vmin=0.25, vmax=0.35, origin='lower');

plt.show()

```

**Actual outcome**

![](https://i.stack.imgur.com/rSj0u.png)
Close-up:

![](https://i.stack.imgur.com/tsdkh.png)

**Expected outcome**

No holes in the 3D surface plot.

**Matplotlib version**

Matplotlib 1.3.0 to 1.5.3 (WinPython 3.3.2.3 to 3.5.2.3), but it was also reproduced up to Matplotlib 2.0: [http://stackoverflow.com/questions/41268550/matplotlib-3d-surface-gaps-holes-in-surface](http://stackoverflow.com/questions/41268550/matplotlib-3d-surface-gaps-holes-in-surface)

**Comment by WeatherGod** [comment]
why would you expect no holes for the surface if the grid has NaNs?

**Comment by WeatherGod** [comment]
Ah, I see, there are holes appearing where there shouldn't be any holes.
Well, this is a known issue with plot_surface(). It has never supported
NaNs or masked arrays, unfortunately. Yes, this is a departure from just
about every single other matplotlib function, but the nature of
plot_surface() makes it difficult to properly handle them. If you wish to
try your hand at adding support for it, I encourage you to give it a try!

**Comment by fmevers** [comment]
Did I get you right, that if I create an array with values instead of NaNs, plot_surface() would be able to handle the array correctly? This would provide me a workaround. Thank you for your encouragement! But, to be honest, adding support would exceed my coding skills by light-years.

**Comment by eric-wieser** [comment]
Can you attach the data that causes the problem?

**Comment by fmevers** [comment]
This is the data set (data.txt): https://gist.github.com/anonymous/bf886433298528bfa2f0f80448ddaa6b

**Comment by mackaiver** [comment]
I still have that problem with matplotlib 3.0.3. Would be happy to know about a workaround or solution.

**Comment by mackaiver** [comment]
I still have that problem with matplotlib 3.0.3. 
Would be happy to know about a workaround or solution.

**Comment by franchesoni** [comment]
Same issue!

**Comment by timhoffm** [comment]
This is indeed related to the NaN values.

If one does `Z[np.isnan(Z)] = np.nanmean(Z)` the artifacts are gone.

Note: Updated the example code since `plt.hold(True)` is no more (and is unneeded) in matplotlib 3.1.
