### ISSUE TITLE
need to backport docathon PRs

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/matplotlib#8223]
Rather than backporting each individual docathon PR, we will do one large docathon merge at the end of the week. Let's keep a list here of the docathon PRs that were accepted.

**Comment by WeatherGod** [comment]
#8219

**Comment by QuLogic** [comment]
#8212

**Comment by dstansby** [comment]
#8215

**Comment by anntzer** [comment]
https://github.com/matplotlib/matplotlib/pull/8233

**Comment by NelleV** [comment]
As mentionned on gitter, I feel uncomfortable backporting documentation pull request. We've identified a bug in the 2.0.0 documentation reference in a ticket (#8235), and if we backport the pull request that fixes this bug, we loose the information allowing to identify when the bug was discovered.

**Comment by NelleV** [comment]
(That's without considering the risk of backporting documentation that uses new features).

**Comment by dstansby** [comment]
#8211

**Comment by dstansby** [comment]
Would backporting to `2.0.x` instead be fine?

**Comment by anntzer** [comment]
#8228

**Comment by dstansby** [comment]
The docathon has long gone, so I'm happy to port these all back to `2.0.x` - if anyone has any objections then shout, otherwise I will do them in a couple of days!

**Comment by dstansby** [comment]
Great, these are all backported, thanks to everyone who did the original PRs, and sorry for the delay on my end...

**Comment by QuLogic** [comment]
Thanks @dstansby.
