### ISSUE TITLE
tight_layout does not work with set_visible(False)

### ISSUE THREAD

**Issue by ResidentMario** [matplotlib/matplotlib#8225]
### Bug report

**Bug summary**

- `tight_layout()` cooperates with `axis('off')` but not with `set_visible(False)`.
- cf. [pandas#9351](https://github.com/pandas-dev/pandas/issues/9351)

**Code for reproduction**

This code fails:

```python
import matplotlib.pyplot as plt
f, axarr = plt.subplots(2, 2)
axarr[1][1].set_visible(False)
plt.tight_layout()
```

This code succeeds:

```python
import matplotlib.pyplot as plt
f, axarr = plt.subplots(2, 2)
axarr[1][1].axis('off')
plt.tight_layout()
```

**Actual outcome**

```
AttributeError: 'NoneType' object has no attribute 'is_bbox'
```

**Expected outcome**

![selection_015](https://cloud.githubusercontent.com/assets/3466341/23668363/d3d5e862-032e-11e7-9b48-03e39cdda2cf.png)

**Comment by WeatherGod** [comment]
Looks like the tight_layout code is iterating over all of the subplots rather than just the visible ones

**Comment by WeatherGod** [comment]
My suspicion is that adding a condition to the list comprehension:
```
tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
```
at line 126 of matplotlib.tight_layout.py should do the trick.

**Comment by tacaswell** [comment]
Those two commands do very different things, `axis('off')` makes the spines invisible, but everything else is still visible ex

```python
fig, ax = plt.subplots()
ax.plot(range(5))
ax.axis('off')

```
gives 
![figure_1](https://cloud.githubusercontent.com/assets/199813/23812831/24b30328-05aa-11e7-85ab-fe19b77bae5a.png)

where are `ax.set_visible(False)` makes the `Axes` object (and all of it's children) are not included in the draw tree.

**Comment by ResidentMario** [comment]
Which is why they look the same output-wise when the plot is empty in the first place (except for dimensional differences), gotcha.
