### ISSUE TITLE
cache local freetype source

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8230]
A large number of CI builds are currently failing (after a looooong timeout) due to a failure to download freetype.  I would suggest caching the freetype source e.g. in ~/.cache/matplotlib, so that it's picked up by the CI caches.  That would also be a benefit for local testing.

(Right now it takes ~40s for me to wget the freetype sources, which is not negligible especially if you multiply it by 6 builds.)

**Comment by QuLogic** [comment]
It's supposed to be cached already, though it doesn't do so on Python 2 or AppVeyor (see my #8179 for the fix to that.)

**Comment by QuLogic** [comment]
Fixed by #8179.
