### ISSUE TITLE
Bug in mpl_connect(): On Windows, with the wx backend, arrow keys are not reported

### ISSUE THREAD

**Issue by christianbrodbeck** [matplotlib/matplotlib#8249]
**Bug summary**

- On Windows, with the wx backend, arrow keys are not reported

**Code for reproduction**

Use the [keypress example](http://matplotlib.org/examples/event_handling/keypress_demo.html) and insert:

```python
from matplotlib import use
use('wx')
```

**Actual outcome**

- On Windows, when pressing arrow keys, no keys are printed to the console.
- On macOS it works as expected.

**Matplotlib version**

- Matplotlib 2.0.0, Python 2.7, Windows 10
- Anaconda

**Comment by lukipro** [comment]
Are there any updates on this issue?

**Comment by anntzer** [comment]
Looks like moving the handler from EVT_KEY_DOWN to EVT_CHAR_HOOK fixes the issue (this is also suggested by e.g. https://stackoverflow.com/questions/3570254/in-wxpython-how-do-you-bind-a-evt-key-down-event-to-the-whole-window or various other googlings), but I don't know if there's any issues with that approach.
