### ISSUE TITLE
Could we decrease the number of test cases in test_mathtext.py? (potentially gaining 60-90s on the test suite)

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8255]
Currently, test_mathtext.py has >1500(!) image comparison tests (`ls lib/matplotlib/tests/baseline_images/test_mathtext | wc`).  Most of them are generated in the following snippet:
```
make_set('mathtext', 'cm', math_tests)
make_set('mathtext', 'stix', math_tests)
make_set('mathtext', 'stixsans', math_tests)
make_set('mathtext', 'dejavusans', math_tests)
make_set('mathtext', 'dejavuserif', math_tests)

make_set('mathfont', 'cm', font_tests, ['png'])
make_set('mathfont', 'stix', font_tests, ['png'])
make_set('mathfont', 'stixsans', font_tests, ['png'])
make_set('mathfont', 'dejavusans', font_tests, ['png'])
make_set('mathfont', 'dejavuserif', font_tests, ['png'])
```

The first part tests parsing of various mathtext constructs and runs image comparisons for png, pdf and svg.  The second part renders a large number of characters (per image) in a given style (\mathrm, etc.) and given font and runs only a png comparison test.

I am wondering whether we could run the first part of the tests only using png -- given that it's mostly a parsing issue, I don't think the backend should matter (I don't know enough about rendering to know whether testing all backends actually help)?  Alternatively we could run each set with a different backend for slightly more coverage.

This would shave off another 60-90s (10-15%) off the duration of the test suite.

**Comment by tacaswell** [comment]
No, but putting them behind a 'slow' flag which is off by default is probably a good idea.

This is one of the places where testing different backends is actually required, the vector backends output the text as string + backend specific markup vs agg where we rasterize the text.

**Comment by anntzer** [comment]
But surely something like
```
make_set('mathtext', 'cm', math_tests, ['png'])
make_set('mathtext', 'stix', math_tests, ['pdf'])
make_set('mathtext', 'stixsans', math_tests, ['svg'])
make_set('mathtext', 'dejavusans', math_tests, ['png'])
make_set('mathtext', 'dejavuserif', math_tests, ['pdf'])
```
should be enough?  I assume the markup in the vector backends is essentially the same except for the font specification?

**Comment by anntzer** [comment]
Let's close this for now, we can always revisit with an actual PR.
