### ISSUE TITLE
changing facecolor to 'none' prevents updating canvas

### ISSUE THREAD

**Issue by birnstiel** [matplotlib/matplotlib#8282]
### Bug report

**Bug summary**

`line.set_ydata` should update a drawn line, however this seems to break under some circumstances, depending on the background color.

**Code for reproduction**

```python
fig,ax = plt.subplots(facecolor='none')
ax.set_facecolor('none')

plt.subplots_adjust(left=0.25, bottom=0.25)
plt.axis([0, 4, 0,2])
l, = ax.plot([1,2,3],[1,0,1])
ax.set_title('down')
def update():
    l.set_ydata([1,2,1])
    ax.set_title('up')
```

this creates a 'v' shape with title 'down' as expected, but then calling `update()`

leads to this:

![ohne titel](https://cloud.githubusercontent.com/assets/3997171/23857516/e64ed4f8-07fd-11e7-8ee3-9dc5b5ee89cc.jpeg)

It continuously draws over the previous plot. `fig.canvas.draw()` doesn't help, but if I `fig.savefig('test.jpg')` it updates correctly.

If the axis background is set to something else but `'none' `, the lines updates correctly, but the title doesn't. The title only update correctly, if also the figure background is something else but `'none'`.

**Expected outcome**

- The `update` function should immediately update the interactive figure.

**Matplotlib version**

- Matplotlib version: 2.0.0
- Python version: 3.6.0 (but same issue with 2.7.13)
- Platform: OSX
- How did you install Matplotlib and Python: anaconda

**Comment by tacaswell** [comment]
Which backend are you using (`matplotlib.get_backend()`)?

My guess at what is going on here is you are using the native OSX backend and we are somehow not correctly clearing the buffer when updating the buffer (which with out the background patches will have a lot of transparent pixels).  This is further supported because the tick labels look 'over-struck' to me.  I would expect calling update multiple times to make them look bolder.

My guess is that this line https://github.com/matplotlib/matplotlib/blob/master/src/_macosx.m#L2169 needs to be preceded by a drawing a rectangle the 'native' color of the window?  I don't have a mac to test this on though.

I can not reproduce this with the qt5agg backend.

**Comment by tacaswell** [comment]
Tagging this as new contributor friendly as I think this will be a 1 line fix, but requires an OSX machine and some knowledge of objective c + the OSX gui toolkit.

Exact work:

 - sort out how to 'blank' canvas in `src/_macosx.m::_copy_agg_buffer`

**Comment by birnstiel** [comment]
yes, I'm using the `MacOSX` backend. And yes, this comes from an interactive figure, when I cause more updates, the labels, ticks, ... become thicker and thicker.

**Comment by cimarronm** [comment]
It would seem to me that the clearing of the canvas would need to be in the agg renderer instead. The MacOSX backend doesn't know anything about that gray color background and really only displays what the Agg render presents to it. The 'native' color of a Quartz window is black. It seems like the Agg render should be responsible for all the alpha blending with it's own background color and send a bitmap that does not include an alpha channel (or set to 1) to the MacOSX backend.

**Comment by cimarronm** [comment]
BTW, TkAgg is showing a pure white screen (no blue plot line, text, etc) if you make the figure facecolor='none' as done in the example.

**Comment by tacaswell** [comment]
It is a feature that Agg returns an RGBA buffer, this is what lets us make figures that really do have transparent areas.

The Qt backend has a line
( https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5agg.py#L116 ) which iirc went in to solve a bug exactly like this.

**Comment by dopplershift** [comment]
Removed the new-user labels because after digging, I've found that this issue has nothing to do with any clearing to be done by the GUI-specific code (after losing a couple hours beating my head against Core Graphics). As it turns out, this is due to a stale Agg buffer. PR incoming...
