### ISSUE TITLE
tight_layout: take suptitle into account?

### ISSUE THREAD

**Issue by birkenfeld** [matplotlib/matplotlib#829]
The tight_layout function is very useful.

In one of the common use cases, a figure with a few subplots, it would be nice if a figure title could be taken into account; otherwise it will overlap the top subplots.

I can see from the code that the suptitle is just a simple Text; maybe the figure could keep track of the last Text object that got created using suptitle(), and so be able to take it into account when calculating the tight layout params.

**Comment by adamjstewart** [comment]
It's been over a decade since this suggested feature was last discussed. Do the same technical difficulties preventing this from happening remain, or is this easier to implement now?

**Comment by adamjstewart** [comment]
Hmm, according to https://matplotlib.org/3.3.4/users/whats_new.html#tight-layout-now-supports-suptitle, it should be supported now, but in practice it's not working for me.

**Comment by jklymak** [comment]
Please open a new issue. Please also try constrained layout instead
