### ISSUE TITLE
six environment polluted when misuse of matplotlib import

### ISSUE THREAD

**Issue by alexandnpu** [matplotlib/matplotlib#8290]
### Bug report

**Bug summary**

- For not-so-careful beginners, misuse of import pollute six environment

**Code for reproduction**

For first time use after `pip install matplotlib`

```python
import matplotlib as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "draw_plot.py", line 4, in <module>
    import matplotlib as plt
  File "/path/to/.alexpy3/lib/python3.6/site-packages/matplotlib/__init__.py", line 129, in <module>
    from six.moves.urllib.request import urlopen
ImportError: cannot import name 'urlopen'
```
after this,  the same import error still stays.

```
python
> from six.moves.urllib.request import urlopen
ImportError: cannot import name 'urlopen'
```

**Expected outcome**

- six environment should not be polluted even for misuse of matplotlib

**Matplotlib version**

- Matplotlib version, 2.0.0
- Python version, 3.6.0 
- Platform, OSX
- How did you install Matplotlib and Python, pip

**Comment by jenshnielsen** [comment]
I can't reproduce this and I don't understand how that relates to importing matplotlib as plt 

```
[jhn:~] $ python
Python 3.6.0 (default, Jan  4 2017, 13:14:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib as plt
>>> from six.moves.urllib.request import urlopen
>>>
```
Which version of six are you using?

**Comment by alexandnpu** [comment]
@jenshnielsen , it is first-time-import after pip-install matplotlib.

my six version is 1.10.0

**Comment by jenshnielsen** [comment]
I still do not understand how you can be sure this has anything to do with matplotlib? To me it sounds like your six installation is broken for what ever reason? I would suggest pip uninstalling matplotlib and six and removing any left over trace from the installation folder and then `pip install six` and test if the issue persists.

**Comment by alexandnpu** [comment]
@jenshnielsen, I failed to reproduced this issue with a fresh new virtual env. I will close this issue first util I can find a way to reproduce it.

**Comment by Dewberrycat** [comment]
i have the same error, python 3.4 windows

**Comment by tacaswell** [comment]
@Dewberrycat What version of six?

**Comment by Dewberrycat** [comment]
1.11.0  it is bug version, yes?
some guy wrote to change __init__.py from
six.moves.urllib.request import urlopen
to
from urllib.request import urlopen

it works, but what is wrong with six, mistakes?

and i can not install pandas, i writes that it can not find appropriate version of numpy in repository and installation fails. it is good that i saved old whl with pandas, whl installs well.

could you tell me - programmers don't see that everything doesn't work and has mistakes? are they blind? hat is problem with them? i permanently have problems with installation of everything.
