### ISSUE TITLE
Unable to pickle.load(fig) with mpl in jupyter notebook

### ISSUE THREAD

**Issue by cbyrohl** [matplotlib/matplotlib#8291]
I use the following code snippet, similar to issue #3986 on Py35/matplotlib2.0.0 installed via Anaconda3:

```python
import matplotlib.pyplot as plt
import numpy as np
import pickle



ax = plt.subplot(111)
x = np.linspace(0, 10)
y = np.exp(x)
plt.plot(x, y)
with open('bla.pickle', 'wb') as pickle_file:
    pickle.dump(ax, pickle_file)
import matplotlib.pyplot as plt
import pickle

with open('bla.pickle', 'rb') as pickle_file:
    ax = pickle.load(pickle_file)
plt.show()
```

The latter pickle.load() fails with:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-0e84ab5169e3> in <module>()
     15 
     16 with open('bla.pickle', 'rb') as pickle_file:
---> 17     ax = pickle.load(pickle_file)
     18 plt.show()

/home/uni09/cosmo/cbyrohl/anaconda3/envs/py35/lib/python3.5/site-packages/matplotlib/figure.py in __setstate__(self, state)
   1443             allnums = plt.get_fignums()
   1444             num = max(allnums) + 1 if allnums else 1
-> 1445             mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
   1446 
   1447             # XXX The following is a copy and paste from pyplot. Consider

AttributeError: module 'ipykernel.pylab.backend_inline' has no attribute 'new_figure_manager_given_figure'
```

This code was executed in a jupyter notebook (ipython 5.3)..

When executing as usual python script, it works just fine. It also works fine when dumping in Jupyter and loading in script.

[TAC edited to add markup]

**Comment by tacaswell** [comment]
This should be reported against IPython as they maintain the inline backend.

attn @takluyver

**Comment by cbyrohl** [comment]
Sure, I reported this in the ipykernel repository.

**Comment by takluyver** [comment]
@tacaswell is it easy to implement the `new_figure_manager_given_figure` function? I'm not familiar with what's required for a mpl backend.

**Comment by tacaswell** [comment]
3 years on I finally came back to this...

**Comment by tacaswell** [comment]
Closed by #16189

**Comment by brianjoubert** [comment]
Hello,

Is it possible to dump the matplotlib plot in Pickle using the default figure manager and load it in Jupyter notebook. 
Basically I tried now to save a plot by running a .py file 

"""
import numpy as np
import matplotlib.pyplot as plt
import pickle

x = np.linspace(-np.pi, np.pi)
y = np.cos(x)
fig, ax = plt.subplots(1, 1)
ax.plot(x, y, label='cos(x)')
ax.set_xlabel('Time (s)')

# Pickle a tuple of figure and axes to a file
pickle.dump((fig, ax), open('myplot.pickle', 'wb'))

"""

and then load the produced pickle in a Jupyter Notebook:

"""
import matplotlib.pyplot as plt
import pickle

# Unpickle your figure and axes
fig, ax = pickle.load(open('myplot.pickle', 'rb'))
ax.set_ylabel('Voltage (mV)')
ax.minorticks_on()
ax.legend()
"""

I always get the following message.

"""
AttributeError: 'NoneType' object has no attribute 'new_figure_manager_given_figure'
"""

**Comment by jklymak** [comment]
Please open a new issue.
