### ISSUE TITLE
x marker is too big

### ISSUE THREAD

**Issue by fkbreitl** [matplotlib/matplotlib#8294]
### Bug report

**Marker 'x' too big**

- The marker 'x' is bigger than the other makers '+', 'o', '1', etc.

**Code for reproduction**

```python
#!/usr/bin/env python                                                          

import numpy as np
import matplotlib.pyplot as plt

x = [1, 2, 3]

x = (1, 2, 3)

plt.plot((1, 2, 2, 3), (1.5, 1, 1, 2), 'o', fillstyle='none')
plt.plot(x, (1, 2, 2), '+')
plt.plot(x, (2, 1, 1), 'x')

plt.savefig('test.png')
```

**Actual outcome**

- X markers are too big.
See images attached

**Expected outcome**

All markers should have the same size.

**Matplotlib version**

- Matplotlib version 2.0.0, Python 2.7.13 and Debian 9.
- Matplotlib installed with `pip`

![test3](https://cloud.githubusercontent.com/assets/1030293/23915212/bab1d408-08e8-11e7-9272-c17ab967a00f.png)

**Comment by tacaswell** [comment]
All markers should have the same bounding box.  The paths for the markers are defined in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/markers.py which it appears that they do.  

If you want a smaller x marker (that fits in the circle) I think the following should work.

```python
   small_x_path = Path(np.array([[-1.0, -1.0], [1.0, 1.0],
                    [-1.0, 1.0], [1.0, -1.0]]) * np.sqrt(2),
                   [Path.MOVETO, Path.LINETO,
                    Path.MOVETO, Path.LINETO])

```

**Comment by fkbreitl** [comment]
The same bounding box is the problem.
If the markers have the same bounding box, then they will have different sizes.
An 'x' should look like a rotated '+'. But with the same box the 'x' will become larger, which is wrong.
Please open this bug again so that this behavior can be corrected.
The current behavior looks unbalanced and is not what users expect and what other plotting programs do.

**Comment by tacaswell** [comment]
You are treating very subjective statements an objective truth.  

Having 'x' be a rotated '+' is not unreasonable, however neither is defining the 'size' of a marker as being the size of it's bounding box.  

Matplotlib has been using this path for 'x' at least from 2007 (and maybe earlier)(b93fc8f6479429df70d21f9bb865f5fc5efaf673 in 2011 is when it got refactored into markers.py from lines.py which in turn goes back to 4cd25ce5034fda04c659498809e6e08de1970e3b which on first glance looks like equivalent code).  

To change the scaling of the 'x' marker would be a major API break of long standing behavior.  This does not mean it can not happen (we just did 2.0 which changed many style things and will likely do a 3.0 in 2018), but it will need better justification than a flat assertion of 'should'.

**Comment by WeatherGod** [comment]
I agree that this is not a bug.

Also, just because "other plotting programs do [it]" (an unsupported
assertion, btw), doesn't mean that we have to do it that way, too. If you
can put together some objective evidence that your proposal is better than
the current behavior (improves readability, reduces confusion, etc.), then
we can certainly take that into account at the next major release.

**Comment by fkbreitl** [comment]
I am just considering the general and obvious definition.
The size of an object is defined by its diameter. In case of symmetric objects like an 'x' or '+' it is easily determined from its enclosing circle.
The current matplotlib definition results in different diameters for different markers, which is generally not desired.

I can believe that this change could be a lot of work. However, if you want to do it right and avoid users having to change the marker by sizes themselves, I don't see a way around it.

The historic development is an explanation but shouldn't be used as an excuse.

**Comment by WeatherGod** [comment]
Going with your diameter definition, then what about the square marker or
the various triangle markers? Should the diameter rule apply to them?
Should the hexagon marker be enclosed by a circle of the same size, or
should it enclose the circle? These are all decisions that would have to be
made if we were to change the definition.

As forthe historic development, matplotlib has a long-standing policy of
having correctly made plots be backwards compatible between minor releases,
and to provide a simple mechanism for backwards compatibility between major
versions. Because the markers are not incorrect, if we were to change them,
that change would have to wait until version 3.0.

**Comment by tacaswell** [comment]
If you want to have this discussion, please move it to the devel mailing list (matplotlib-devel@python.org  you will have to join to post unmoderated).

Again, you will need a better argument than flat assertions and claims to 'obviousness'.

**Comment by fkbreitl** [comment]
Yes, I think the size of a marker should be defined by their enclosing circle.

Of course the decision about the development priorities lies with the developers.

But since this is an issue tracker which goes beyond bug reports issues should be open until they get resolved or noted. Therefore please open it again so that others can take note of the problem.
If you prefer you can label it as feature request or something similar. Anyway I want to bring this problem to attention. I don't have time nor experience to lead a discussion at the developers list. This report has to suffice.

**Comment by phobson** [comment]
@fkbreitl 

I don't think we're going to reopen this. However, I encourage you to fill out a Matplotlib Enhancement Proposal (MEP). The MEP template is in the doc/devel/MEP folder of the source tree here: https://github.com/matplotlib/matplotlib/blob/master/doc/devel/MEP/template.rst

As you see, the template is pretty detailed and requires to the author to get specific about the steps they will take (i.e., pull requests *they* will make) to implement the proposal. The way you submit a MEP is to create a new file in that folder and submit a PR. In the thread of that PR, matplotlib developers will discuss and proposal changes to the MEP based on their experience with past MEPs and the MPL code base.

Authoring a MEP doesn't guarantee its acceptance by the matplotlib development team. You'll need to have a clear development plan and solid arguments for why it represents an enhancement and not just a lateral change.

At the moment, I feel it's safe to say that all of the MPL developers feel stretched thin by their careers/school work, families, hobbies, and then open source contributions. It's all I can do to keep up with the github notifications alone (I typically declare GH bankruptcy every Monday). As such, we're putting this in your hands to make a reality.
