### ISSUE TITLE
copy a color map object does not isolate changes to cm

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8299]
If you do `cm2 = copy.copy(cm)` and the original color map has been used at least once, then the copy will share a reference to `self._lut` (which is what is used to `__call__` to map from values -> rgba).  Any calls to `set_over`, `set_under`, or `set_bad` will be shared by all copies (as they update `self._lut` in place).

**Comment by tacaswell** [comment]
Exact work:
 - implement `__copy__` and maybe `__deepcopy__` on `ColorMap`

Tagging as medium because the color map code is a bit convoluted .

**Comment by bendichter** [comment]
I can reproduce this issue with:

```
import matplotlib.pyplot as plt
import copy
import numpy as np

%matplotlib inline
data = np.ma.masked_array([[1,2,3],[2,3,4]], mask=[[1,0,0],[0,0,0]])
cm = plt.cm.Reds
plt.imshow(data,cmap=cm)
plt.show()
cm2 = copy.copy(cm)
cm2.set_bad('b')
plt.imshow(data,cmap=cm)
```
In the second plot the image contains blue when it should remain white. copy.deepcopy works as expected, though. Would the solution be to have __copy__ call __deepcopy__?

**Comment by dopplershift** [comment]
Implementing `__copy__` should be enough to get the desired behavior.
