### ISSUE TITLE
standard key for closing figure ("q")

### ISSUE THREAD

**Issue by birkenfeld** [matplotlib/matplotlib#830]
For consistency with other plotting programs (such as gnuplot), I would love to have "q" as a standard key for closing a figure window.

**Comment by hbaromega** [comment]
@pelson what did you mean by "Added a close figure key ("q" by default)" ? Where did you do the modification (inside some file?) ?

**Comment by pelson** [comment]
> @pelson what did you mean by "Added a close figure key ("q" by default)" ?

All matplotlib figures can be closed with "ctrl + w" / "cmd + w" since a good number of years.

The changes (rather broadly) were done in #851. The specific file which changed: https://github.com/matplotlib/matplotlib/pull/851/files#diff-546df25a362e568e615b2a0558df2cbeR585
