### ISSUE TITLE
Too many open files: '/usr/lib/python3.6/site-packages/matplotlib/backends/web_backend/mpl.js'

### ISSUE THREAD

**Issue by beojan** [matplotlib/matplotlib#8308]
When using the `nbagg` backend to produce some plots with Pandas, I get the error:

`Too many open files: '/usr/lib/python3.6/site-packages/matplotlib/backends/web_backend/mpl.js'`

**Comment by WeatherGod** [comment]
which version of matplotlib? Also, linux or mac?

**Comment by beojan** [comment]
matplotlib 2.0 on Linux.

**Comment by beojan** [comment]
Still an issue with matplotlib 2.1.0.

**Comment by beojan** [comment]
Bumping. This issue still exists with current Matplotlib from git master.

**Comment by jklymak** [comment]
We’d need more to go on to try and fix this.  I use nbagg all the time and never have this problem.

**Comment by WeatherGod** [comment]
Could you try using `lsof -p PID` in order to see how many files are
getting opened by matplotlib? Start up a python process and identify it in
another terminal. Then import matplotlib and do an lsof -p PID for that
process and see what the list is.

On Fri, Jan 26, 2018 at 7:58 AM, Beojan Stanislaus <notifications@github.com

**Comment by tacaswell** [comment]
How many plots do you need to have open to get this issue?

**Comment by beojan** [comment]
Just one, but I draw into it multiple times.

It also seems the close button doesn't actually close the figure.

**Comment by tacaswell** [comment]
does the figure title stay 'figure 1' or does in continually go up?

**Comment by beojan** [comment]
Stays as figure 1.

**Comment by WeatherGod** [comment]
Have you tried running lsof? This is really the only way we would be able
to diagnose what is happening.

On Sat, Jan 27, 2018 at 2:43 PM, Beojan Stanislaus <notifications@github.com

**Comment by beojan** [comment]
Just tried running `watch -n 0.5 "lsof -p 11397 | wc -l"` (11397 is the appropriate process id), and I see the number of open files go up each time I plot something new into the figure. It goes up by a lot (30 or so each time) at first (per figure), and eventually seems to slow down ot about 5 extra open files each time.

**Comment by tacaswell** [comment]
What versions of everything (matplotlib, ipython, ipykernel, jupyter, pandas) do you have installed?  Exactly what are you plotting?

I can not reproduce this at all using

```python
￼
%matplotlib notebook
In [5]:
￼
import os
In [6]:
￼
os.getpid()
Out[6]:
3264
In [3]:
￼
import matplotlib.pyplot as plt
import numpy as np
In [11]:
￼
plt.plot(range(5))

```

**Comment by beojan** [comment]
matplotlib, numpy, scipy, and pandas from git, jupyter, ipython, etc. from pip.

In fact, I can't reproduce it with matplotlib alone either. What I'm plotting right know is read from ROOT files with root_pandas, so the issue may well be there.

I'll close this for now, and reopen if I find and still have the issue with the notebook I originally saw this in (which used only matplotlib and pandas).

**Comment by tacaswell** [comment]
@anerokhi What versions of everything?  We are using the IPython/jupyter coms so I don't think we are intentionally creating many connection.

**Comment by anerokhi** [comment]
@tacaswell python `3.6.5`, jupyter notebook `5.6.0`, matplotlib `2.2.2`
