### ISSUE TITLE
while importing EOFError comes out

### ISSUE THREAD

**Issue by waterple** [matplotlib/matplotlib#8313]
### Bug report

**Bug summary**

when I tried to 
`import matplotlib.pyplot`
makes EOFError

The OS is windows 10 Home

**Code for reproduction**

```python
import matplotlib.pyplot
```

**Actual outcome**

- The output produced by the above code, which may be a screenshot, console output, etc.

```
# If applicable, paste the console output here
#
#
```
![image](https://cloud.githubusercontent.com/assets/18376367/24028176/5cb7bb18-0b10-11e7-8cf6-0a0b3aeff67c.png)

**Expected outcome**

none

**Matplotlib version**

matplotlib (2.0.0)
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
Windows 10 Home

Matplotlib was followed from anaconda, and upgraded with

conda upgrade matplotlib

I installed anaconda 4.2.0, and it is not recent release since i want to use tensorflow

**Comment by anntzer** [comment]
When that error occurs (at the Python prompt), type
```
import pdb; pdb.pm() <enter>
```
then
```
p repr(path) <enter>
u <enter>
p repr(direc) <enter>
```

What do you get?

**Comment by waterple** [comment]
Thank you for your appreciation.
However I already solved the problem...
by changing
`direc = os.path.abspath(direc).lower()`
to
`direc = direc.split('\0', 1)[0]`

..and I cannot understand how your code works..

result:
`>>> import pdb
>>> pdb.pm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\water\Anaconda3\lib\pdb.py", line 1598, in pm
    post_mortem(sys.last_traceback)
AttributeError: module 'sys' has no attribute 'last_traceback'
>>> pdb.pm()
> c:\users\water\anaconda3\lib\pdb.py(1598)pm()
-> post_mortem(sys.last_traceback)
(Pdb) p repr(path)
*** NameError: name 'path' is not defined`

**Comment by anntzer** [comment]
You have to trigger the exception first before trying the snippet I gave.

It is good that you found a workaround, but if it's a bug in matplotlib we may as well fix it.

**Comment by waterple** [comment]
Actually I changed 
`direc = os.path.abspath(direc).lower()`
to
`direc = direc.split('\0', 1)[0]`

from `font_manager.py`

It may be the problem in windows os

**Comment by tacaswell** [comment]
In the future please copy-paste not screen-shot the console information.

Why is your path separator not `\` ?

We probably should be more permissive about finding fonts failing due to OS level issues in font manager.

**Comment by tacaswell** [comment]
Also try deleting everything in `~/.cache/matplotlib` (where ever that lands on windows).

**Comment by anntzer** [comment]
Because codepages.  See bottom of https://en.wikipedia.org/wiki/Path_(computing)#Representations_of_paths_by_operating_system_and_shell

**Comment by tacaswell** [comment]
https://twitter.com/jdub/status/842452736587182080

**Comment by tacaswell** [comment]
Closing as this has been quiet for 5 months and this is likely a local configuration issue.

Please subscribe to and send any follow up questions to https://mail.python.org/mailman/listinfo/matplotlib-users which is a better forum for these sorts of issues.
