### ISSUE TITLE
Fonts not changed in LaTeX mode (since version 2.0.0)

### ISSUE THREAD

**Issue by falkm** [matplotlib/matplotlib#8317]
### Bug report

**Bug summary**
if MP.rcParams['text.usetex'] == True, System fonts are not found and even ttf in the mpl folder are not recognized.
Before the upgrade to mpl 2.0.0, I was used to setting usetex and was able to take fonts from my system library. This, however, failed after the mpl 2.0.0 upgrade. 

I managed a temporary, limited workaround by 
- turning "usetex" to False  
- copyint a ttf conversion of the font to the matplotlib library folder

However, this is insufficient because I occasionally require LaTeX functionality and want a font to be consistent with my document.
This might be related to http://stackoverflow.com/questions/42097053/matplotlib-cannot-find-basic-fonts/42841531

**Code for reproduction**
```python
# minimal example
# the goal is to have a plot with LaTeX text and a custom font (Iwona)

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

mpl.rcParams['text.usetex'] = True # DOES NOT WORK.

## THIS, however, would work:
# mpl.rcParams['text.usetex'] = False


# the font "Iwona" is located in the texlive libraries as OTF
# and was converted to TTF via fontforge to be put to /usr/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf
mpl.rcParams['font.family'] = 'Iwona' # DOES NOT WORK.

## THIS, however, would work:
# mpl.rc('font',**{ \
#               'family': 'sans-serif' \
#             , 'sans-serif': 'Avant Garde' \
#             }) 


# from http://matplotlib.org/users/usetex.html#usetex-tutorial
t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(4 * np.pi * t) + 2

plt.plot(t, s)

plt.xlabel(r'time (s)', fontweight = 'bold')
plt.ylabel(r'il voltage (mV) $\mu$')
plt.title(r"mathtext is Number "
          r"$\sum_{n=1}^\infty\frac{-e^{i\pi}}{2^n}$!"
          , color='gray')

plt.subplots_adjust(top=0.9)

plt.show()
```

**Actual outcome**
All plot texts are reset to "DejaVu Sans". Optionally, "Avant Garde" works. Neither system fonts (from texlive), nor manually added ttf fonts from the "{matplotlib}/mpl-data/fonts/ttf" folder work. 

**Expected outcome**
Before, on version 1.5, I simply set "usetex" to True and set the font in rc parameters to for example "Iwona". All text elements in the plot were correctly adjusted.

**Matplotlib version**
matplotlib 2.0.0 (both via pip or pacman)
python 3.6
manjaro linux (arch-based)
texlive-most (unchanged with MPL upgrade)

**Thanks a lot!**
... for your help or advice for a workaround.

**Comment by QuLogic** [comment]
> mpl.rcParams['font.family'] = 'Iwona' # DOES NOT WORK.

I don't think this value is acceptable when using `usetex=True`. For some reason, [this warning](https://github.com/matplotlib/matplotlib/blob/v2.0.0/lib/matplotlib/texmanager.py#L178) is not shown by default, but only serif/sans-serif/cursive/monospace are allowed.

> ```
> ## THIS, however, would work: # mpl.rc('font',**{ \
> #               'family': 'sans-serif' \
> #             , 'sans-serif': 'Avant Garde' \
> #             })
> ```

This generally makes sense, but Matplotlib only knows how to map [a very small number](https://github.com/matplotlib/matplotlib/blob/v2.0.0/lib/matplotlib/texmanager.py#L141-L157) of font names to TeX names. This does point to a way to fix it though:

```python
import matplotlib as mpl
from matplotlib.texmanager import TexManager

mpl.rcParams['text.usetex'] = True
mpl.rc('font',
    # It's really sans-serif, but it doesn't override \sffamily, so we tell Matplotlib to use the "serif"
    # font because then Matplotlib won't ask for any special families.
    **{'family': 'serif',
       'serif': 'Iwona'
      }
)
# Tell Matplotlib how to ask TeX for this font.
TexManager.font_info['iwona'] = ('iwona', r'\usepackage{iwona}')
```

**Comment by falkm** [comment]
Thank you, QuLogic, this indeed worked for me.

It was non-intuitive that setting the 'family' attribute to the font name worked in non-tex mode.
Also, this is something that apparently changed compared to version 1.5, so moe people might encounter it in the future.
Maybe it's worth adding a piece of documentation to the usetex tutorial?

**Comment by tacaswell** [comment]
@QuLogic is what you just wrote in the docs any place?

**Comment by QuLogic** [comment]
I doubt it; I looked through the code to see what it was doing. The [LaTeX guide](http://matplotlib.org/users/usetex.html) doesn't seem to mention any of it. I would guess the assumption is using the `preamble` setting, though it's unsupported.
