### ISSUE TITLE
PyPy compatibility - __builtin__ is not iterable

### ISSUE THREAD

**Issue by mattip** [matplotlib/matplotlib#8330]
On PyPy __builtins__[key] should be __builtins__.key, which is also CPython compatible. This is a continuation of the fix(es) in issues #7186, #7272
lib/matplotlib/axes/axes.py line 6105
lib/matplotlib/axes/_axes.py line 6477 
``range = __builtins__['range']`` -> ``range = __builtins__.range``

For reference, this turned up in testing pandas/tests/plotting

**Comment by arigo** [comment]
Note that it's more complicated.  ``__builtins__`` can be a (regular) dictionary or a module object on CPython; on PyPy it is always a module object.  It is documented as an internal detail and the proper solution is to not use it.  Instead, do ``import __builtin__; range = __builtin__.range``.

**Comment by anntzer** [comment]
fixed by #8331.
