### ISSUE TITLE
style.use not working for some cases

### ISSUE THREAD

**Issue by prasants** [matplotlib/matplotlib#8348]
### Bug report

* When attempting to use Matplotlib Style, the selected style is not rendered. 
* `ggplot` and `seaborn` styles are working, but variations of `seaborn` are not working.
* Example, `plt.style.use('seaborn-paper')` renders the default seaborn style.

Edit: It turns out that the problem is that matplotlib styles are not being applied after another style has been applied, as can be seen in this screencast.
https://youtu.be/bJtpXt34weA
By the way, in this video, I have commented out `import seaborn`, but that was an experiment to see if importing or not importing seaborn had any effect.
**Code for reproduction**

from https://github.com/prasants/pyds/blob/master/12.Introduction_to_Pandas.ipynb
```python

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (15,7)
whacked.plot(kind = "bar", legend=None)
plt.title('How People Died on The Sopranos')
plt.style.use('seaborn-paper')
```

**Actual outcome**
![Screenshot](https://i.imgur.com/QTa6QrI.jpg)

**Expected outcome**
![Screenshot](https://i.imgur.com/ExF17Z3.png)
Incorrect - see https://youtu.be/bJtpXt34weA

**Platform**
* Matplotlib - 2.0.0
* Python - 3.6.0
* Seaborn - 0.7.1
* Jupyter - 4.4.1 
* OS Sierra

- Python installed via Homebrew, matplotlib and other libraries via `pip`

**Comment by WeatherGod** [comment]
I suspect that moving the plt.style.use() call might have had an effect
here. Typically, one should put the call as soon as possible in order to
guarantee that the style is completely applied. Putting it last causes some
things to get different defaults upon creation (lazy evaluation vs.
on-creation-evalution semantics are a bit mixed in matplotlib). The plot
you posted actually appears correct, and the one that you claim is the
expected outcome does *not* appear to be the seaborn style (but I could be
wrong here).

**Comment by prasants** [comment]
@WeatherGod : You are right, it is not the correct style. However, I have updated with a video that shows the problem. 
I will report back after implementing your suggestion to place `plt.style.use()` on top.

**Comment by afvincent** [comment]
Be careful that `plt.style.use` may only update *some* of the rcParams. Basically, it calls
```
def _apply_style(d, warn=True):
    mpl.rcParams.update(_remove_blacklisted_style_params(d, warn=warn))
``` 
Could you try calling early `plt.style.use(['default', 'seaborn-paper'])` to see if you get what you want? If I am correct, another way to achieve this that does not require to set the style early is to use a context manager:
```python
with plt.style.context('seaborn-paper', after_reset=True):
    yada yada yada
```

**Comment by prasants** [comment]
Thank you, that seems to be the solution! Seems like that should be an important step while working on something like IPython.

**Comment by afvincent** [comment]
For the record, here is some [useful doc](http://matplotlib.org/users/style_sheets.html)

**Comment by tylertroy** [comment]
When working in notebooks, I find the use of the context manager very helpful.
```
with plt.style.context('ggplot'):
    plt.plot(data)
```
