### ISSUE TITLE
seaborn styles make "+", "x" markers invisible; proposed workaround for shipped styles

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8351]
It is a somewhat well-known issue (#4679) that seaborn's styles make "+", "x" markers invisible by default (because they set `lines.markeredgewidth` to zero).  Although it may be helpful to use a separate rcparam to control such markers, this is not trivial (see linked issue).  Instead, in this issue, I'd like to argue that matplotlib should not ship styles available by default where some markers are completely invisible; instead, we may e.g. set `lines.markeredgewidth` to a tiny value, so that the markers are at least faintly visible (and it may be easier to realize where the issue comes from), even though it is not strictly equivalent to the "official" seaborn style.

From simple attempts, it seems that a value like 0.25 should be enough.

**Comment by mwaskom** [comment]
I think this can be handled once #8479 lands by setting `markeredgecolor` to `"auto"`, as per https://github.com/matplotlib/matplotlib/commit/de7bc9331c19ce378df3a3c066cbf1b87fceb58a.

**Comment by dmcooke** [comment]
Just hit this bug. Took me a while to figure out why my '+' marker wasn't showing (I'm using the seaborn-notebook style).

**Comment by mwaskom** [comment]
This is looong since fixed in seaborn itself, but unfortunately matplotlib refuses to fix the style sheets they ship: https://github.com/matplotlib/matplotlib/pull/13680

**Comment by anntzer** [comment]
I think this is effectively closed by #22317 (the old styles will stay what they are given the backcompat concerns, but they point to seaborn itself).
