### ISSUE TITLE
FuncAnimation object is run twice when saving

### ISSUE THREAD

**Issue by mountaindust** [matplotlib/matplotlib#8360]
### Bug report

**Bug summary**

The save method of FuncAnimation appears to run twice, the second time in a different thread. I discovered upon trying to give the user feedback on the process.

**Code for reproduction**

Here is a slight reworking of one of the basic animation examples, edited to provide progress feedback to the user. In addition to the output described below, I get a qt traceback at the end if this example is altered for blitting (TypeError: 'method' object is not connected). The behavior persists whether or not you use a generator function.

```python
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


def main():

    def make_animation():

        def update_line(row):
            plt.plot(row, 'r-')
            print(".",end="")
            sys.stdout.flush()

        data = np.random.rand(25, 2)
        
        def animGen():
            for row in data:
                yield row

        fig1 = plt.figure()

        plt.xlim(0, 1)
        plt.ylim(0, 1)
        plt.xlabel('x')
        plt.title('test')
        line_ani = animation.FuncAnimation(fig1, update_line, frames=animGen,
                                        interval=50, repeat=False)
        print("Saving:",end="")
        line_ani.save("test.mp4")
        print("\nSaved!")

    print("Starting routine to save animation:")
    make_animation()
    val = input("Now I'm waiting for input!")

if __name__ == "__main__":
    main()
```

**Actual outcome**

Here's what you get. Everything is like expected, and then the animation continues running after the make_animation function has returned! I did not provide input until after the second line of dots had printed, so they are coming out during a pause. None of this happens if you replace `line_ani.save("test.mp4")` with `plt.show()`.

```
PS D:\Python> python ani_test.py
Starting routine to save animation:
Saving:..........................
Saved!
Now I'm waiting for input!..........................
```

**Expected outcome**

Of course, you would expect that the second line of dots don't show up while the script is waiting for input. It's been a while since I used the original code that is now producing this error, so I can't say for sure which earlier version of Matplotlib it worked correctly on. It hasn't been more than a year though.

**Matplotlib version**

Matplotlib version 2.0.0
Python version 3.5.2
Platform: Windows
Anaconda installation

**Comment by mountaindust** [comment]
Possibly related:
- I'm using ffmpeg, the newest release version.
- I found this bug while trying to run a larger code which attempts to form an animation slide show out of a computationally expensive set of images, generating them as they are requested.  This is not working well at all. Any attempt to set the frame interval (FuncAnimation) or fps (save method) results in only the first image being shown throughout the resulting video file. There is no problem at all when I view the video with plt.show(). So, perhaps all of this is a compatibility issue with newer versions of ffmpeg? I tried to use mencoder to see if I could isolate the issue, but it throws errors.

**Comment by dopplershift** [comment]
This seems to be specific to the backend; it doesn't happen for me if I put `MPLBACKEND='agg'` or `MPLBACKEND='macosx'`

My suspicion is that the qt4 backend is starting up the GUI loop somehow even though the `show()` is not called.

**Comment by dopplershift** [comment]
The likely reason you don't see it when you replace `save()` with `show()` is because you've eliminated the pass through the generator caused by the `save()` call, and *only* seeing those from the GUI loop (i.e. the `show()` is redundant in terms of kicking off the animation).

**Comment by mountaindust** [comment]
I can verify what @dopplershift says; on my system, the agg backend gets rid of the original problem too. Unfortunately, the issue in my comment remains - too much to hope I'd get two birds with one stone! If I get the time, I'll try to come up an example to reproduce it and open a separate issue.

**Comment by tacaswell** [comment]
@mountaindust to kill two birds with one stone I would suggest looking at http://matplotlib.org/devdocs/api/animation_api.html?highlight=animation#writer-classes and https://github.com/matplotlib/matplotlib/pull/4779 for how to write out to the movie and update a figure in the middle of expensive computation.

**Comment by QuLogic** [comment]
I can't reproduce this with the Qt5 backend, and the Qt4 backend is gone now, so I'll close.
