### ISSUE TITLE
Installation on CentOS using pip in virtualenv

### ISSUE THREAD

**Issue by CorbinFoucart** [matplotlib/matplotlib#8361]
**Bug summary**

running `pip install matplotlib` within a python 2.7 virtualenv crashes with an error message stating
`Failed building wheel for subprocess32` on a CentOS cluster where I do not have admin rights. A python virtual environment I installed in October on the same cluster had no issue installing matplotlib using the same installation procedure, and I can still use matplotlib in the other virtual environment.

`pip install matplotlib`
produces
```python
(venv) mseas(Kovasnay)% pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-2.0.0-1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: functools32 in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: numpy>=1.7.1 in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: python-dateutil in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: cycler>=0.10 in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Collecting subprocess32 (from matplotlib)
  Using cached subprocess32-3.2.7.tar.gz
Requirement already satisfied: pytz in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: six>=1.10 in /home/foucartc/pyHDG/branches/MMSDebug/src/venv/lib/python2.7/site-packages (from matplotlib)
Building wheels for collected packages: subprocess32
  Running setup.py bdist_wheel for subprocess32 ... error
  Complete output from command /home/foucartc/pyHDG/branches/MMSDebug/src/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QHNCMS/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8hlovApip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying subprocess32.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_posixsubprocess' extension
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/apps/Python-2.7.11/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o
  gcc -pthread -shared build/temp.linux-x86_64-2.7/_posixsubprocess.o -L/home/mirabito/test_py2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_posixsubprocess.so
  /usr/bin/ld: cannot find -lpython2.7
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for subprocess32
  Running setup.py clean for subprocess32
Failed to build subprocess32
Installing collected packages: subprocess32, matplotlib
  Running setup.py install for subprocess32 ... error
    Complete output from command /home/foucartc/pyHDG/branches/MMSDebug/src/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QHNCMS/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j8Yiv8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/foucartc/pyHDG/branches/MMSDebug/src/venv/include/site/python2.7/subprocess32:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying subprocess32.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_posixsubprocess' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/apps/Python-2.7.11/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/_posixsubprocess.o -L/home/mirabito/test_py2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_posixsubprocess.so
    /usr/bin/ld: cannot find -lpython2.7
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/foucartc/pyHDG/branches/MMSDebug/src/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QHNCMS/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j8Yiv8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/foucartc/pyHDG/branches/MMSDebug/src/venv/include/site/python2.7/subprocess32" failed with error code 1 in /tmp/pip-build-QHNCMS/subprocess32/
```

**Comment by phobson** [comment]
does `pip install matplotlib --user` get around this for you?

**Comment by jenshnielsen** [comment]
Do you have the devlopment headers for python installed. I don't know the name of the package on Fedora but its something like python-dev on ubuntu/Debian? It fails installing subprocess32 which is a dependency of matplotlib not matplotlib it self which already comes as a binary wheel package

**Comment by matthew-brett** [comment]
The subprocess32 project appears to be pining for the fjords - there are no wheels, and no reply to my offer of automated wheel building : https://github.com/google/python-subprocess32/issues/14

**Comment by CorbinFoucart** [comment]
@jenshnielsen:

Yes, it appears so. It also stands to reason that I would not have been able to successfully install and use matplotlib in the other virtual environment I configured in October 2016.

```
mseas(lib)% yum search python-devel
Rocks-6.2                                                                                        | 3.6 kB     00:00     
============================================== N/S Matched: python-devel ===============================================
python-devel.x86_64 : The libraries and header files needed for Python development
python27-python-devel.x86_64 : The libraries and header files needed for Python development
  Name and summary matches only, use "search all" for everything.
```

**Comment by jenshnielsen** [comment]
subprocess32 is a new dependency of matplotlib 2.0 so installing 1.5.3 (which you probably did the last time) is a workaround

**Comment by CorbinFoucart** [comment]
@jenshnielsen 

Ah, ok. I did not know that. This is indeed exactly the case. I am able to successfully install matplotlib 1.5.3 in the new virtualenv. This is a good workaround for me.

However, if python-devel does exist on our cluster, I'm still unsure what I should do to update/fix subprocess32. Eventually, I will want to use matplotlib 2.0.

**Comment by jenshnielsen** [comment]
@matthew-brett understands this better but you may be able to use the wheels that he have build even if they are not on pypi as a work around? I am not sure how to read the yum output are those packages installed? I would expect the build of subprocess32 to work if they are installed as it fails when linking against libpython27 which is installed by that package. Indeed building matplotlib from source would probably fail in the same way (but there are prebuild wheels of matplotlib that you can use for this so it's not an issue on linux)

**Comment by CorbinFoucart** [comment]
@jenshnielsen 

Yes, you are correct, my list does not imply they are installed on the system. Trying again, it appears that they are indeed installed, though. The build of subprocess32 is failing regardless, though.
```
mseas(~)% yum list python-devel
Installed Packages
python-devel.x86_64                        2.6.6-52.el6                         @anaconda-base-201505101627.x86_64/6.2.0

```

**Comment by jenshnielsen** [comment]
I could be wrong but I think that's the headers for python 2.6 and python27-python-devel is the package for 2.7

**Comment by matthew-brett** [comment]
These commands worked for me on a fresh CentOS 7 container:

```
yum update
yum install python2-devel
yum install gcc
yum install python-virtualenv
virtualenv venv
source venv/bin/activate
# This works correctly
pip install subprocess32
# Need latest pip for manylinux wheels
python -m pip install --upgrade pip
# This works correctly
pip install matplotlib
```

**Comment by matthew-brett** [comment]
Hmm - I'm guessing from your output above that:

* you're on CentOS 6; and
* you're using Python 2.7 from Anaconda.

Is that right?  In which case, did you try `conda install matplotlib` instead?

**Comment by CorbinFoucart** [comment]
@matthew-brett 

I do not have administrator privileges on the cluster. I can set up new virtual environments, but can't change the system configuration. I don't think we are using Python 2.7 from Anaconda, because the conda command is not recognized.

**Comment by matthew-brett** [comment]
I was looking at this line:

```
python-devel.x86_64                        2.6.6-52.el6                         @anaconda-base-201505101627.x86_64/6.2.0
```

Maybe you have some Anaconda yum package source installed?

Maybe check where you got your Python 2.7:

```
yum whatprovides `which python2.7`
```

or similar.

**Comment by QuLogic** [comment]
Anaconda is the Fedora/RHEL installer, not the anaconda Python distribution; that entry means it was installed as part of the initial installation.

**Comment by tacaswell** [comment]
Also, mpl2.0 does not officially support py2.6 (but might still run?)

**Comment by matthew-brett** [comment]
Aha - yes - I forgot the other anaconda.

Still, @CorbinFoucart's traceback shows he is building for Python 2.7 on what appears to be a CentOS 6 machine, so the question remains, as to where Python 2.7 came from, and therefore, how to get the development machinery.

**Comment by jenshnielsen** [comment]
From the yum output above I would expect that `python27-python-devel.x86_64` needs to be installed from yum as `python-devel.x86_64` is the 2.6 headers which are installed but `python27-python-devel.x86_64` is not

**Comment by matthew-brett** [comment]
Right - I think that package comes from the CentOS software collection repository : https://wiki.centos.org/AdditionalResources/Repositories/SCL - I guess that's where the Python 2.7 binary comes from.

This works in a CentOS 6 container:

```
yum install -y gcc
# https://wiki.centos.org/AdditionalResources/Repositories/SCL
yum --enablerepo=extras install -y centos-release-scl
yum install -y python27-python-devel
yum install -y python27-python-virtualenv
# From https://www.vcloudnine.de/python-2-7-for-centos-6
echo "/opt/rh/python27/root/usr/lib64" > /etc/ld.so.conf.d/python27.conf
ldconfig
/opt/rh/python27/root/usr/bin/virtualenv venv
source venv/bin/activate
pip install subprocess32
```

**Comment by matthew-brett** [comment]
Is there any way of dropping the subprocess32 dependency?   Changing to another library?  I think subprocess32 is moribund now.

**Comment by tacaswell** [comment]
There was discussion of an alternative in another issue (in another thread that I can not find now) about moving to an alternative, mostly to keep the dependency lists the same between py2 and py3.

If someone wants to do the work I am fine changing the dependency.  Strongly prefer it continue to only affect py2 installs.

**Comment by sercretalphabets** [comment]
Solved this by adding the version: sudo pip install matplotlib==1.5.3

**Comment by wangdongxuking61** [comment]
command "sudo apt-get install python-dev" is useful.

**Comment by MaryoHg** [comment]
Dear all (participants),

I'm having a related issue. I was trying to install the same way (`$ pip install matplotlib==1.4.3`) without success.
The error showed the following:
>/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
  Rolling back uninstall of matplotlib
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yQEy9J/matplotlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lsyFNk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-yQEy9J/matplotlib/

I've been checking all dependencies mention and I couldn't install the version of python-dev mentioned by @jenshnielsen :

> but python27-python-devel.x86_64 is not

May you help me with a recommendations on how to proceed?
I kindly appreciate.

I'm working on a server with Fedora 25 OS installed.
`$ gcc --version`
gcc (GCC) 6.4.1 20170727 (Red Hat 6.4.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.

Thank you all.

**Comment by WeatherGod** [comment]
Why are you trying to install v1.4.3? It is fairly old. Quite likely, you
are running into issues trying to compile everything together. Try a newer
version of matplotlib like v2.2.3 or v3.0.0.

**Comment by MaryoHg** [comment]
Hi, @WeatherGod,

I had actually installed the last version but when I'm into QIIME it gives me an error because of matplotlib version.
Without 1.4.3 version, QIIME ([#2117](https://github.com/biocore/qiime/issues/2117)) will show that error. That's why I'm installing this specific version.

So, Will I be unable to install this specific version on the server?
A precompiled version or src code from [here](https://sourceforge.net/projects/matplotlib/) maybe?
I'm new using Fedora to install and update and that stuff.
In Ubuntu works perfectly. :(


Thanks for any comment.
