### ISSUE TITLE
Matplotlib %notebook lags when showing coordinate pixel values

### ISSUE THREAD

**Issue by VolkerH** [matplotlib/matplotlib#8365]
**Bug summary**

When using matplotlib in Jupyter notebook with `%matplotlib notebook`, the matplotlib widget provides a mouseover that updates the coordinates and or values in the lower right hand corner.
The implementation of this mouseover is very slow as it seems to update for every mouse event. 
If one moves around the mouse quickly over the plot, the widget quickly accumulates a backlog of mouse movement events. Working through this backlog, the plot is busy and the display of coordinates/values  is updating for another few seconds after the mouse has stopped.
A similar thing is happening when dragging open a zoom rectangle. 

**Code for reproduction**

any plt.plot  or plt.imshow command 

**Actual outcome**

terrible lag of the widgets. In particular for large images the `%matplotlib notebook` backend becomes unusable.

**Expected outcome**

display of the values should happen in sync with the mouse movements. This would require ignoring mouse position change events if newer events are already in the queue.

**Matplotlib version**

Matplotlib version  2.0.0 **Note: edited, originally had the wrong number here**
Python version 3.6.0
OS X Sierra
Installed via Anaconda (anaconda version 4.3.0)

**Comment by tacaswell** [comment]
by '5.1.0' I assume you mean '1.5.0'?  Can you update to a newer version (either 1.5.3 or 2.0)?  I am pretty sure we fixed a bunch of those performance issues in the mouse over in 1.5.1.

**Comment by VolkerH** [comment]
Sorry, wrong version number - I printed a bunch of package version numbers and looked in the wrong output line when writing the issue.
Matplotlib version is 2.0.0 from a  recent, fresh anaconda install. 

The IPython version was 5.1.0.

**Comment by tacaswell** [comment]
If you use one of the native backends (ex qt) do you see the same lag (to sort out if this is cpu bound or network bound)?

If it is network, then this is probably best handled in the javascript (which we definitely need Ihelp with!) to not send a request down socket if it is still waiting for a response.

If it is cpu, then we need help with the hit-testing code.

Also have a look at https://github.com/matplotlib/jupyter-matplotlib which is the notebook backend is going to move long-term.

**Comment by VolkerH** [comment]
with (ex qt) did you mean (example:qt) or (excluding qt) ?
Anyway, I assumed  you mean the former and just tested with` %matplotlib qt5` from an ipython  terminal. No lag, even for large images.

**Comment by tacaswell** [comment]
Meant example, sorry for not being clear.

**Comment by tacaswell** [comment]
Closing as the latency is somewhat inherent in how the notebook backend works (due to their being network hits) and re-writing the existing js to handle dropping events is a big task that I do not think we will take on.

Future work should move to https://github.com/matplotlib/jupyter-matplotlib which will integrate with the widgets frame work and can make use of the existing throttling machinery there.
