### ISSUE TITLE
Surprising behavior of legend when both `loc='best'` and `bbox_to_anchor` are used. 

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#8366]
### Bug (?) report

**Bug summary**

I do not know if it was ever intended to combine the `bbox_to_anchor` and the `loc` kwargs in `legend`. But it results in a behavior that I find rather surprising.

**Code for reproduction**
```python
import matplotlib.pyplot as plt


def do_plot(ax, loc='best', bbox_to_anchor=(0.5, 0.5), color='black'):
    ax.plot([0, 1], color=color, label='A label')
    ax.set_ylim(top=3)
    ax.legend(loc=loc, bbox_to_anchor=bbox_to_anchor)
    # Cosmeticks
    ax.xaxis.set_major_locator(plt.NullLocator())
    ax.yaxis.set_major_locator(plt.NullLocator())
    ax.set_title("loc={l}\nbbox_to_anchor={b}".format(l=loc, b=bbox_to_anchor))
    return ax

fig, ((ax0, ax1), (ax2, ax3), (ax4, ax5)) = plt.subplots(nrows=3, ncols=2)
# First row
do_plot(ax0, color='r', loc='upper right', bbox_to_anchor=(-0.001, 1))
do_plot(ax1, color='g', loc='best', bbox_to_anchor=(-0.001, 1))
# Second row
do_plot(ax2, color='b', loc='upper left', bbox_to_anchor=(0.001, 1))
do_plot(ax3, color='y', loc='best', bbox_to_anchor=(0.001, 1))
# Third row
do_plot(ax4, color='m', loc='upper left', bbox_to_anchor=(0.1, 1))
do_plot(ax5, color='c', loc='best', bbox_to_anchor=(0.1, 1))

fig.subplots_adjust(left=0.2, hspace=0.5, wspace=0.75, bottom=0.05, top=0.90)
plt.show()
```

**Actual outcome**
Matplotlib 2.0.0:
![confusing_legend_position_with_a_bbox_to_anchor_with_mpl2 0 0](https://cloud.githubusercontent.com/assets/17270724/24256745/428f3d5a-0fe9-11e7-89e6-cff90be7a449.png)

Matplotlib 1.5.1:
![confusing_legend_position_with_a_bbox_to_anchor_with_mpl1 5 1](https://cloud.githubusercontent.com/assets/17270724/24256735/3b5ad7b0-0fe9-11e7-8f35-3ba75ca1bae3.png)

**Expected outcome**
- First row is fine for me: 'best' <- 'upper right' because else the legend frame would have overlapped with the left spine.
- Second and third rows seem weird to me: why would the best location not be something like 'upper left'?

If I am not the only one to find the behavior of the left column a bit surprising, then _the real problem is that it is now the default legend behavior in 2.0 if the user **only** provide a `bbox_to_anchor` but no `loc`, isn't it?_

**Matplotlib version**
Tested on Linux (CentOS 7), with Python 2.7 and mpl 2.0.0 and 1.5.1 (installed from conda).

**Comment by afvincent** [comment]
Eventually marking it as release-critical (2.0.1). I am opened to remilestone it again for 2.1 if one shows that actually the case `ax.legend(bbox_to_anchor=(..., ...))` is not used that much by users. I think it is, but I may be wrong…

**Comment by afvincent** [comment]
Following a remark made by @anntzer on Gitter and looking closer to `legend` docstring, it appears that I may have slightly misread it. I thought that the new default for `loc` was 'best' (based on what is said [here](http://matplotlib.org/users/dflt_style_changes.html#legends) for example), but the docstring still states that the default value for `loc` is 'upper right', which at least seems consistent with the results of calling `ax.legend(bbox_to_anchor=...)  # no explicit *loc*`. With this new information **the issue does not look really critical anymore** as actually calling `legend` with only `bbox_to_anchor` but no explicit `loc` value behaves as in 1.5.3. So removing the red flag and remilestoning it to 2.1 in order not to block 2.0.1 release...

However, I still find the behavior of `ax.legend(loc='best', bbox_to_anchor=...) ` surprising. And I do not really understand what the `loc` default  value is: "upper right" as stated in the docstring or the rcParams from the matplotlibrc file?

**Comment by efiring** [comment]
The default really is "best".  The docstring is wrong--it looks like it didn't get updated when the default changed.

**Comment by timhoffm** [comment]
IMHO this is reasonably descibed in the legend docsting nowadays.
