### ISSUE TITLE
Simpler code for common plot setting (e.g. legend, lable, title, figsize)?

### ISSUE THREAD

**Issue by cqcn1991** [matplotlib/matplotlib#8370]
As I use matplotlib more and more, I find setting the figure cumbersome, for example 

    x = [1,2,3,4,5]
    y = [5,2,6,7,2]
    plot(x, y, '-', label='test')
    ax = plt.gca()
    ax.set_title('This is my title')
    ax.set_xlabel('X name')
    ax.set_ylabel('Y name')
    ax.legend()
    plt.gcf().set_size_inches(4,4)

[![enter image description here][1]][1]

For I make a sufficient plot, **too many lines of code are simply about the figure configuration**. 

I want to know, if there are simple ways to do this? For example, in `pandas` we can do 

    df['my_column'].plot(kind='bar', figsize=(20,4), ....)

-----

Currently, I solve this problem by define a `plt_configure()` function, 

[![enter image description here][2]][2]

The code looks like 

    def plt_configure(ax=None, xlabel=None, ylabel=None, title='', legend=False, tight=False, figsize=False, no_axis=False):
        if ax == None :
            ax=plt.gca()
            plt.suptitle(title)
        else:
            ax.set_title(title)
    
        if xlabel:
            ax.set_xlabel(xlabel)
        if ylabel:
            ax.set_ylabel(ylabel)
        if legend:
            if isinstance(legend, dict):
                ax.legend(**legend)
            else:
                ax.legend()
        if tight:
            if tight == 'xtight' or tight == 'x':
                ax.autoscale(enable=True, axis='x', tight=True)
            elif tight == 'ytight':
                ax.autoscale(enable=True, axis='y', tight=True)
            else:
                ax.axis('tight')
        if figsize:
            plt.gcf().set_size_inches(figsize)
        if no_axis:
            plt.gca().axis('off')
            legend = ax.legend()
            if legend:
                legend.remove()
       

Note: this is also asked at http://stackoverflow.com/questions/42976996/matplotlib-simpler-code-for-common-plot-setting-such-as-legend-lable-title

  [1]: https://i.stack.imgur.com/W8JSd.png
  [2]: https://i.stack.imgur.com/6o86w.png

**Comment by tacaswell** [comment]
This hits one of the tensions of mpl, it can do almost anything which means we expose API to do almost everything.

Writing local functions like this is addressed in the docs (http://matplotlib.org/faq/usage_faq.html#coding-styles but it probably should be put someplace more prominent and expanded) and is how I personally use Matplotlib.  The problem with including these functions in the library is that they are a projection of the full API that suits who ever wrote it. 


There is also the `set` method on all `Artist` objects so

```python
fig, ax = plt.subplots()
ax.set(xlabel='X Label', ylabel='Y Label', title='My Title')
ax.plot(range(5))
```

does what you expect.

**Comment by cqcn1991** [comment]
@tacaswell The set function is pretty cool, didn't know it before. Still, I think i can't do it without `ax`, and legend, figsize setting?

I think one of the problem might be that I've some background in Ruby on Rails, in which we care about `convention over configuration`. So we always want to do something with simpler code, which is much productive under many circumstances, and if you want to configure everything, you can still do it.

**Comment by anntzer** [comment]
`plt.gca().set(...)`

**Comment by anntzer** [comment]
Closing, but feel free to continue the discussion.

**Comment by tacaswell** [comment]
The `convention over configuration` works when there is a clear convention (or you are willing to railroad your users into one) which is something that does exist for RonR, but Matplotlib's user base is _way_ too big for that.

There are a number of libraries built on top of Matplotlib (seaborn, ggplot, pandas, yt, etc) that take a much more opinionated approach (because they know more about the semantics of the data coming in and about their users).

**Comment by cqcn1991** [comment]
@tacaswell Thanks, I see it right now. Matplotlib is more a ground-level thing (such as Ruby itself), and we need something more (Such as Rails, and Seaborn and others) to improve the efficiency.
