### ISSUE TITLE
MacOSX backend: figure is cleared when moving from one screen to another

### ISSUE THREAD

**Issue by HDembinski** [matplotlib/matplotlib#8387]
### Bug report

**Bug summary**

A figure created on Mac with the MacOSX backend on one screen gets blank when the figure window is dragged to another screen attached to the same computer.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.rcParams["backend"] = "MacOSX"
from matplotlib import pyplot as plt

plt.figure()
plt.plot([0,1],[0,1]) # to have some content
plt.show()
# now drag figure from one screen attached to the computer to another screen attached to the computer
```

**Actual outcome**

<img width="755" alt="screen shot 2017-03-27 at 13 50 45" src="https://cloud.githubusercontent.com/assets/2631586/24354979/6b5b1d72-12f4-11e7-9b43-76c7cf2505f6.png">

**Matplotlib version**

System: MacOS El Capitan
Matplotlib version: 2.0.0
Python version: 2.7.10 (System Python)

Matplotlib was installed with pip.

**Comment by mmckerns** [comment]
as noted in #8500, the plot "reappears" if you resize the window

**Comment by HDembinski** [comment]
Yes, resizing the window is a workaround, but it leads to loss of exact figure size in pixel (unless you have uncanny marksmanship with the mouse).

**Comment by tacaswell** [comment]
This needs attention from someone who understands the OSX gui framework.  It should be simple enough as forceing a re-render when the effective dpi changes.

**Comment by cimarronm** [comment]
I cannot seem to reproduce but am running macOS Sierra. @HDembinski, are you able to test with latest OS and still see the issue?

**Comment by tacaswell** [comment]
I strongly suspect that there are latent DPI scaling related issues in this, possibly put in by my work on qt5 and hi-dpi...

**Comment by HDembinski** [comment]
@cimarronm I will give it a try tomorrow! I compiled matplotlib myself on Linux before, not on Mac, but hopefully it will work fine.

**Comment by mmckerns** [comment]
@cimarronm: I see the bug on macOS Sierra.

**Comment by cimarronm** [comment]
I was able to reproduce it with v2.0.0 but don't see the issue with the latest master or v2.0.1 so it may have been addressed already. @mmckerns or @HDembinski, can you try with the latest master?

**Comment by HDembinski** [comment]
I just downloaded and compiled the github master, and it works like a charm now!

**Comment by tacaswell** [comment]
I have no idea what we changed that would have fixed this....

**Comment by tacaswell** [comment]
Closing as this is reported fixed on master.

**Comment by HDembinski** [comment]
One more comment: When I initially reported this, I used MacOS El Capitan. Before I tried the latest master, I updated to Sierra. Perhaps it is not a change in matplotlib but a change in the MacOS Version...
