### ISSUE TITLE
Can't install matplotlib from source due to recent addition of QHULL_LIB_CHECK to src/qhull_wrap.c

### ISSUE THREAD

**Issue by telamonian** [matplotlib/matplotlib#8390]
I'm currently trying to use pip (on a mac running osx El Capitan) to install a particular commit of matplotlib:
```
pip install -U --upgrade-strategy only-if-needed git+https://github.com/matplotlib/matplotlib.git@91e74257b770d#egg=matplotlib
```

I need this particular commit so I can fix an issue I (and others) are having with the width of type 42 fonts in v2.0. Unfortunately, this is failing with:
```
...

    building 'matplotlib._qhull' extension
    clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/sqlite/include -DMPL_DEVNULL=/dev/null -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib__qhull_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/usr/local/lib/python3.4/site-packages/numpy/core/include -I/usr/local/include -I/usr/include -I/usr/X11/include -I/opt/X11/include -I. -I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c src/qhull_wrap.c -o build/temp.macosx-10.9-x86_64-3.4/src/qhull_wrap.o
    src/qhull_wrap.c:112:5: error: use of undeclared identifier 'QHULL_LIB_CHECK'
        QHULL_LIB_CHECK
        ^
    1 error generated.
    error: command 'clang' failed with exit status 1

...
```

I know matplotlib is finding the relevant qhull library:
```
...

REQUIRED DEPENDENCIES AND EXTENSIONS

...

                     qhull: yes [Using system Qhull (version unknown, no pkg-
                            config info)]

...
```

so I'm not sure what the problem is. Examining `qhull_wrap.c` in the repo shows that the offending line was recently added in a recent commit with the note `Update qhull to 2015.2`. Is the fix that I should try to upgrade the qhull libs on my system? The [matplotlib install doc](http://matplotlib.org/users/installing.html) makes it sound like the qhull libs are included with matplotlib, so I'm somewhat confused.

**Comment by telamonian** [comment]
Okay, I got it working by upgrading the qhull libs I had installed on my system. So it seems like the issue was indeed that the build system was preferring the obsolete qhull libs on my system over the newer qhull libs packaged with matplotlib.

On the one hand, arguing over which version of qhull should take precedence in the build system seems like some serious bikeshedding to me. On the other hand, matplotlib forcibly requires the newer version of qhull, so there is a real problem. Maybe at the least you guys could add a note about this issue to the install doc?

**Comment by phobson** [comment]
Hey @telamonian thanks for following up with the solution. I'll try to add a note to the docs explaining this soon.

**Comment by tacaswell** [comment]
I am tempted to suggest we change the search logic to prefer the internal version if we can not determine if the system version is new enough, however that may cause problems for some of the down-stream packagers (ex debian / fedora / ..) who definitely do not want us to vendor qhull.

**Comment by anntzer** [comment]
Then it should be up to the downstream vendors to provide correct pkg-config information so that we can determine the installed version.
At least on Linux and possibly OSX (dunno whether e.g. homebrew installs pkg-config information) I am very much in favor of preferring the vendored version in the absence of pkg-config information.  And we may as well do the same on Windows because who has qhull headers installed on Windows anyways...

**Comment by ash13** [comment]
Hi,
I want to fix the doc. Can someone help me with it ? I am a beginner in this.

**Comment by anntzer** [comment]
I don't think this is a particularly good issue to start with (in fact, if we follow the route proposed by @tacaswell and which I agree with, it's not a documentation issue at all...).  You may want to have a look at https://github.com/matplotlib/matplotlib/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3ADocumentation instead.

**Comment by anntzer** [comment]
Actually I think this is also an instance of https://github.com/matplotlib/matplotlib/issues/9737 (matplotlib unnecessarily prepending the system include path); if the system path is not added then the vendored version would be found first.
