### ISSUE TITLE
shared twinned subplots: support `ax.twinx(sharey=...)` / `ax.twiny(sharex=...)`

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8392]
After
```
fig, (ax1, ax2) = plt.subplots(2, sharex=True, sharey=True)
ax1.plot([1, 2]); ax2.plot([1, 2])
ax1.twinx().plot([2, 1]); ax2.twinx().plot([2, 1])
```
zooming/panning one of the subplots only affects the other subplot along the x axis, but not the y axis -- because zooming/panning affects the twinned subplots, which only share their x axis, whereas the y sharing is lost (of course, it cannot always be shared with the original subplots -- the sharing needs to occur directly between the twinned subplots).

Having thought approximately 30s about the issue, I believe an easy way out would be to support passing an explicit `share{y,x}` argument to `twin{x,y}` (for the "other" axis, as the twinned axis is already shared with the original subplot, of course), so that one can properly re-link the twinned subplots between themselves.

**Comment by kundor** [comment]
An easy way to implement this is to add `**kwargs` to the signature of twinx and twiny
```
def twinx(self, **kwargs):
```
and pass them along to `_make_twin_axes` in the first line of code:
```
ax2 = self._make_twin_axes(sharex=self, **kwargs)
```
This allows passing on arbitrary keyword arguments for the newly constructed axes, including `sharex` or `sharey`.

**Comment by anntzer** [comment]
This is more or less covered by #15287.
