### ISSUE TITLE
Difference between settings of similar mlab spectrum tests 

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#8393]
I'm trying to parametrize mlab tests (which cuts out many many lines of classes), but there are a few differences between similar tests which makes it really difficult to parametrize things (e.g., real vs. complex). Here are some differences:
* Between real and complex:
    * `len_x` differs in:
      * `nosig_defaultsided_trim` (1024 vs 256)
   * `NFFT_density` differs in:
      * `nosig_*_defaultsided_nopad_to` (-1 vs None)
      * `nosig_*_defaultsided_oddlen` (33 vs 128)
      * `nosig_*_defaultsided_trim` (512 vs 128)
      * `nosig_*_twosided_nopad_to` (-1 vs None)
* Between onesided and twosided:
    * `NFFT_density` differs in:
        * `nosig_complex_*_nopad_to` (-1 vs None)
* Between onesided/twosided and defaultsided:
    * `len_x` differs in:
        * `nosig_complex_*_trim` (1024 vs 256)
    * `NFFT_density` differs in:
        * `nosig_complex_*_nopad_to` (-1 vs None)
        * `nosig_complex_*_oddlen` (33 vs 128)
        * `nosig_complex_*_trim` (512 vs 128)

Does anyone know why these differ in this way? @vollbier?
Can I replace some of the values by the others (and which by which?)

**Comment by vollbier** [comment]
I'm also having trouble comprehending these tests fully.
The code looks really similar to `scipy.signal` implementation [1], especially to the `_spectral_helper()` function. Perhaps their tests could be helpful (wouldn't it be great, if just could test against their functions...). 

On an unrelated topic: I'm quite certain that the scaling of `mlab.magnitude_spectrum()` is at least inconsistent. I did not file the pull request yet, because the tests show inconsistencies with `mlab.spectrogam()` (which shows, they're not useless). 

[1] https://github.com/scipy/scipy/blob/master/scipy/signal/spectral.py

**Comment by tacaswell** [comment]
Some of those may be from me randomly changing values to make the tests run faster (at one point we were spending 40s or something like that doing an fft on a huge array that we then down-sampled to 100 pixels!).

**Comment by QuLogic** [comment]
Do you think reducing all of the inconsistent ones to the smaller values would work fine?

**Comment by QuLogic** [comment]
Looking at it a bit more:

> * Between real and complex, `len_x` differs in `nosig_defaultsided_trim` (1024 vs 256)
> * Between real and complex, `NFFT_density` differs in `nosig_*_defaultsided_trim` (512 vs 128)
> * Between onesided/twosided and defaultsided, `len_x` differs in `nosig_complex_*_trim` (1024 vs 256)
> * Between onesided/twosided and defaultsided, `NFFT_density` differs in `nosig_complex_*_trim` (512 vs 128)

1) These really all refer to the same case, `nosig_complex_defaultsided_trim`. It looks like all the other similar cases had increased the lengths to fix warnings in #7985. Not sure why this one didn't trigger any warnings, but increasing the values doesn't seem to have much effect on runtime, so I'll just do that.

> * Between real and complex, `NFFT_density` differs in `nosig_*_defaultsided_nopad_to` (-1 vs None)

2) Appears to be a mistake as the parameters of the complex side duplicate `nosig_complex_defaultsided_noNFFT_no_pad_to`.

> * Between real and complex, `NFFT_density` differs in `nosig_*_twosided_nopad_to` (-1 vs None)

3) Appears to be a mistake as the parameters of the complex side duplicate `nosig_complex_twosided_noNFFT_no_pad_to`.

> * Between onesided and twosided, `NFFT_density` differs in `nosig_complex_*_nopad_to` (-1 vs None)
> * Between onesided/twosided and defaultsided, `NFFT_density` differs in `nosig_complex_*_nopad_to` (-1 vs None)

Same as 2/3 above.

> * Between real and complex, `NFFT_density` differs in `nosig_*_defaultsided_oddlen` (33 vs 128)
> * Between onesided/twosided and defaultsided, `NFFT_density` differs in `nosig_complex_*_oddlen` (33 vs 128)

4) Again, both of these entries refer to one case `nosig_complex_defaultsided_oddlen`. This is how it was implemented originally; I have a feeling it was just a mistake and all cases should be `NFFT_density=33`.

I'll implement these changes in #8568.
