### ISSUE TITLE
pyplot.subplots did not return the type of object specified in the documentation

### ISSUE THREAD

**Issue by mcyc** [matplotlib/matplotlib#8397]
### Bug report

**Bug summary**

- `pyplot.subplots` from `matplotlib` version 2.0.0 is returning `ax` as a `matplotlib.axes._subplots.AxesSubplot` object instead of an `Axes` objects specified in the documentation (see http://matplotlib.org/).
- Note: `matplotlib.axes.Axes` objects are much more useful to work with than `matplotlib.axes._subplots.AxesSubplot` objects.

**Code for reproduction**

- A minimum code snippet:

```python
# Paste your code here
from matplotlib import pyplot as plt
f, ax = plt.subplots()
type(ax)
print type(ax)
```

**Actual outcome**
```
# The console output:
<class 'matplotlib.axes._subplots.AxesSubplot'>
```

**Expected outcome**
- According to the documentation, the returned ax should be a `matplotlib.axes.Axes` object.

**Matplotlib version**

- Matplotlib version: 2.0.0
- Python version: 2.7.12
- Platform OSX (10.11.6)
- Matplotlib and Python installed via anaconda

**Comment by QuLogic** [comment]
> Note: matplotlib.axes.Axes objects are much more useful to work with than matplotlib.axes._subplots.AxesSubplot objects.

What do you mean? What can't you do with it? `matplotlib.axes._subplots.AxesSubplot` is a subclass of `matplotlib.axes.Axes`, so it should be able to do exactly the same things.

**Comment by mcyc** [comment]
@WeatherGod: Thanks for the clarification. I can see how clarifying the documentation on this can be fairly challenging. 

@QuLogic: You are correct. It turns out the attribute I was looking for actually belong to another subclass of `matplotlib.axes.Axes` rather than the `Axes` class itself. I was lead to believe the subclass I was looking for is just the `Axes` class due to the confusion in the documentation discussed above. Thanks for pointing that out.

**Comment by WeatherGod** [comment]
I am glad that helped you figure out your problem. If you have any suggestions on how we could possibly improve our documentation in this regard, we can certainly continue discussing it here or on the mailing list. Absent any actionable items, though, I will mark this issue as closed.
