### ISSUE TITLE
figures won't update correctly using MacOSX backend

### ISSUE THREAD

**Issue by js54434** [matplotlib/matplotlib#8400]
### Bug report

**Bug summary**

If I use the MacOSX backend in Mac OS X 10.11.6, matplotlib version 2.0.0, using "pythonw" as installed by anaconda, in the interactive mode (after running plt.ion()) in a normal Mac OS X terminal, then the initial plot may display fine, but attempts to interact with the plot result in unresponsiveness. If you attempt to adjust the plot by clicking on, e.g., the "scale" button below the plot and right-clicking and dragging the cursor on the plot to scale it, then nothing happens until you type some keys in the terminal, at which point it'll update, but then the terminal and the plot will become unresponsive until you execute Ctrl-C. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.ion()
plt.figure()
plt.plot([1], 'ko')    # plot a point
```

**Actual outcome**

After executing that code and try to adjust the figure by scaling or zooming in, nothing will happen. If you start typing, then the figure will update, but then the terminal and figure become unresponsive until you press Ctrl-C. 

**Expected outcome**

Attempts to adjust the plot should have an instantaneous response with no unresponsiveness afterwards. 

**Matplotlib version**

matplotlib 2.0.0

python info:
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin

platform: 
Mac OS X 10.11.6

I installed everything using anaconda.

**Comment by dstansby** [comment]
Can confirm this on

- Current master (`2.0.0.post3871+gf9e0b9251`)
- Pyton 3.6
- OSX 10.12.3

The entire plotting window is disabled, including the close/minimize/maximize buttons at the top.

**Comment by tacaswell** [comment]
Does it work in IPython?

**Comment by js54434** [comment]
Yes, it does seem to work in ipython 5.1.0.

**Comment by tacaswell** [comment]
Ah, great, so that narrows down the issue.  Did this used to work with 1.5.x?

Attn @mdehoon for mac related GUI integration issues.

**Comment by dstansby** [comment]
Just had a quick check, and the above snippet works fine with 1.5.3 on OSX.

**Comment by dstansby** [comment]
Bisects down to https://github.com/matplotlib/matplotlib/commit/fd7eeebe86340a9b327177865d0a5c4105b1c354

**Comment by efiring** [comment]
@cimarronm, the commit is from your #6521 PR; maybe you can see how to modify it to handle the use case here.

**Comment by efiring** [comment]
Presumably the `isEqualToString:@"Python"` is too restrictive; something is needed that will also match "pythonw", but I have no idea how to do this in ObjectiveC.

**Comment by smaret** [comment]
This bug is still present on:
 - macOS 10.15.9
 - Python 3.7.6
 - matplotlib 3.1.3
