### ISSUE TITLE
BUG: PDF export seems wrong with dash sequences that include a None offset

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#8405]
**Bug summary**

Custom dash sequences of the form (None, on_off_seq) seem to be rendered as solid lines in PDF exports.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(num="mwe")

linestyles = ('dashed', '--', (None, (3.7, 1.6)), (0, (3.7, 1.6)))
for y, ls in enumerate(linestyles):
    ax.plot([y]*2, ls=ls, label='{0}'.format(ls))

ax.set_ylim(-0.5, len(linestyles) - 0.5)  # useful on mpl < 2
ax.legend()

for ext in ('.png', '.pdf'):
    fig.savefig(fig.get_label() + ext)
```

**Actual outcome**
![screenshot_of_mwe_v2 0 0](https://cloud.githubusercontent.com/assets/17270724/24504235/bf7cbe34-1555-11e7-96b4-05a00055b2a9.png)
Please note that the picture above is a manual screenshot of the PDF produced with Matplotlib. For an unknown reason, GitHub does not allow me to upload the original PDF file… 

**Expected outcome**
Something like the PNG export of the same plot:
![mwe_v2 0 0](https://cloud.githubusercontent.com/assets/17270724/24503969/9f269c1e-1554-11e7-954f-bd0be9dbf6d8.png)

Both PNG and PDF look fine when exported with Matplotlib 1.5.1 (from conda). PDF export seems to be “broken” in this case both with Matplotlib 2.0.0 (from conda) and and master (from GitHub).

OS: CentOS 7
Python: 2.7

**Comment by kahnchana** [comment]
What do you use for viewing pdfs? I got them same problem. However when the PDF is opened in chrome  it showed up fine. Also for adobe reader 9 and edge it didn't even show the top two lines. Will go through this.

**Comment by afvincent** [comment]
I have the issue with Evince, MuPDF, xpdf and qpdfview.

**Comment by tacaswell** [comment]
my guess is an overly agressive cut-out looking for None in the pdf backend.

**Comment by jkseppan** [comment]
It seems to me that [the linestyle documentation](https://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D.set_linestyle) specifies "(offset, on-off-dash-seq)" and only explains what the on-off-dash-seq can be. It doesn't really say what the type of the offset should be, but I don't see how it could be anything but a number, so the bug is that this generates invalid PDF output instead of erroring out.

**Comment by QuLogic** [comment]
Passing `None` is deprecated as of #15828, so I don't think we have any plans to fix this.
