### ISSUE TITLE
FancyArrow, error in the polygon coordinates for shape 'full'

### ISSUE THREAD

**Issue by webermarcolivier** [matplotlib/matplotlib#8406]
### Bug report

**Bug summary**

Error in the coordinates in class FancyArrow for shape 'full', original code is
```python
coords = np.concatenate([left_half_arrow[:-2],
                                             right_half_arrow[-2::-1]])
```
resulting in a triangle-like arrow tail. Code should be
```python
coords = np.concatenate([left_half_arrow[:-1],
                                             right_half_arrow[-2::-1]])
```
**Actual outcome**
![image](https://cloud.githubusercontent.com/assets/12274716/24504714/9733b570-1557-11e7-9c0d-4c02b59a1f6d.png)

**Expected outcome**
![image](https://cloud.githubusercontent.com/assets/12274716/24504675/7574fcfa-1557-11e7-94d3-ae212ce6976d.png)

**Matplotlib version**

matplotlib version 2.0.0, Linux, pip

**Notes**
I know that FancyArrow will be deprecated and replaced by FancyArrowPatch. However, FancyArrowPatch does not allow to directly set the arrow head dimensions (width and length) in data coordinates, only in display coordinates (points). It would be nice to be able to set the arrow dimensions also in data coordinates in FancyArrowPatch.

**Comment by davipatti** [comment]
This wasn't an issue in version 1.5.3

![fancyarrow_mplversion1 5 3](https://cloud.githubusercontent.com/assets/6817331/24553151/1468a91e-1621-11e7-95bc-3a09e9fe5ca5.png)
![fancyarrow_mplversion2 0 0](https://cloud.githubusercontent.com/assets/6817331/24553152/146be566-1621-11e7-9fb1-4675d649b474.png)

~~~
#!/usr/bin/env python
import matplotlib
import matplotlib.pyplot as plt
version = matplotlib.__version__
arr = matplotlib.patches.FancyArrow(x=0, y=0, dx=10, dy=10,
                                    ec='black', fc='lightgrey', lw=1, 
                                    length_includes_head=True,
                                    head_length=5, head_width=10, width=5)
fig, ax = plt.subplots(figsize=(3, 3))
ax.add_patch(arr)
ax.set_xlim(-10, 20)
ax.set_ylim(-10, 20)
plt.title('mpl version {}'.format(version))
plt.savefig('fancyArrow_mplVersion{}.png'.format(version))
~~~

**Comment by tacaswell** [comment]
I wonder if this is the underlying issue with https://github.com/matplotlib/matplotlib/issues/8384

**Comment by tacaswell** [comment]
64cee30e26f191ef3392ad98a03588350a387a47  / 23afcb4 / https://github.com/matplotlib/matplotlib/pull/5392 is the source of this change which was to fix a different bug.
