### ISSUE TITLE
Python 3.4 image comparison test failure for `mathtext_cm_52-expected.png`

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#8416]
Image comparison test failure for `mathtext_cm_52-expected.png`, Python 3.4, manylinux 64-bit.

This is on the manylinux wheel daily builds:

https://travis-ci.org/MacPython/matplotlib-wheels/jobs/217472861#L666

**Comment by QuLogic** [comment]
See #7911.
