### ISSUE TITLE
set_ylim not working with shared x axis on 2.0.0

### ISSUE THREAD

**Issue by sergiocallegari** [matplotlib/matplotlib#8420]
Trying to have 2 plots sharing the same x axis:

    plt.figure()
    ax1 = plt.subplot(211)
    ax1.plot(x1, y1)
    ax1.set_xscale('log')
    ax1.set_ylim(-175, 20)
    ax1.grid(which='both')
    ax2 = ax1.twinx()
    ax2.plot(x2, y2)
    ax2.set_ylim(-175, 20)

the `set_ylim` on `ax1` does not seem to work. I invariably get the y axis on `ax1` as wide as the data.

This used to work OK on 1.5.3.

**Comment by sergiocallegari** [comment]
Found the problem, I also had a further

   ax5 = plt.subplot(212, sharex=ax1, sharey=ax1)

so the problem is that, unless I call the `set_ylim` on `ax5`, the one on `ax1` is ignored. Is this expected?

**Comment by phobson** [comment]
I'm not sure I follow. Could you incorporate that into your first example?

**Comment by WeatherGod** [comment]
twining isn't the same thing as sharex and sharey. They are two different,
but related things.

**Comment by sergiocallegari** [comment]
The whole code, reduced to the bare minimum is

    plt.figure()
    ax1 = plt.subplot(211)
    ax1.plot(x1, y1)
    ax2 = ax1.twinx()
    ax2.plot(x2, y2)
    ax2.set_ylim(-175, 20)
    ax3 = plt.subplot(212, sharex=ax1, sharey=ax1)
    ax3.plot(x3, y3)
  
And the thing is that, to limit the range of the ordinate in the first subplot, the obvious

    ax1.set_ylim(yminval, ymaxval)

does not work.  However, the result is achieved by

    ax3.set_ylim(yminval, ymaxval)

IMHO this goes against expectations. In fact, if ax1 is shared for the y axis, an action on ax1 to set the ylim should work and also apply to ax3. Conversely, after the sharey, actions on ax1 to set the ylim get completely ignored and only actions on ax3 work, also changing ax1.

**Comment by WeatherGod** [comment]
Ah, this is clearer now. This problem doesn't happen if you take out the
twinning?

**Comment by tacaswell** [comment]
I can not reproduce this issue

```python
plt.figure()
ax1 = plt.subplot(211)
ax1.plot(x1, y1)
ax1.set_xscale('log')
ax1.grid(which='both')

ax2 = ax1.twinx()
ax2.plot(x2, y2)

ax2.set_ylim(0, 1)

ax3 = plt.subplot(212, sharex=ax1, sharey=ax1)
ax1.set_ylim(-2, 1)
```
![so](https://user-images.githubusercontent.com/199813/30785908-d6bbfad4-a13b-11e7-8d30-9eb55c1c3429.png)

as expected.

I am going to close this as I can not reproduce it.  @sergiocallegari Please ping to have this re-open if I am confused.
