### ISSUE TITLE
Consistent deprecation of the hold kwarg of hlines and vlines

### ISSUE THREAD

**Issue by adeak** [matplotlib/matplotlib#8421]
**Bug summary**

The `hold` kwarg of `hlines`/`vlines` (to be called `hlines` in the following) has been deprecated since 2.0, but it's still present in the `pyplot.hlines` docstring. Furthermore, using it leads to difference in behaviour between `Axes.hlines` and `pyplot.hlines`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig,ax = plt.subplots()
ax.plot([1,2,3])
# compare:
ax.hlines(2,-1,4,hold=True)
# with:
#plt.hlines(2,-1,4,hold=True)
plt.show()
```

**Actual outcome**

When using `ax.hlines`, the following exception is thrown:
```
AttributeError: Unknown property hold
```
but the expected effect of `hold=True` is there in the result (contrasting with the case when `hold=True` is omitted):
![fig1_ax hlines](https://cloud.githubusercontent.com/assets/17914410/24629556/b584fa6a-18b9-11e7-8e8c-ed82e41a1b1c.png)

When using `plt.hlines`, I only get a deprecation warning:
```
MatplotlibDeprecationWarning: The 'hold' keyword argument is deprecated since 2.0.
```
and the expected effect of `hold=True` is missing:
![fig2_plt hlines](https://cloud.githubusercontent.com/assets/17914410/24629584/d19a02e0-18b9-11e7-9376-9778e4c29a96.png)

The docstring of `ax.hlines` (where the kwarg actually seems to work, sort of) doesn't contain `hold`, but `plt.hlines` (where the kwarg doesn't work) does, and without any note concerning deprecation.

**Expected outcome**

I'd expect `pyplot.hlines` and `Axes.hlines` to behave similarly, and this should be reflected in the respective docstrings. I find it extra confusing that the one that throws a warning about deprecation *doesn't* show the expected behaviour of the keyword, while the one that throws an exception shows it. I understand that one just shouldn't use the deprecated keyword, but I ran into the unfortunate combination of looking at `help(plt.hlines)` and using `ax.hlines`, so it took me a while to figure out what's going on.

**Matplotlib version**

I tested the above on matplotlib 2.0.0, Python 3.5 on Debian.

**Comment by tacaswell** [comment]
The `Axes` version never supported `hold` (which is why you see the `AttributeError`) so it does not need to be deprecated there.

The default value of `hold` has been `True` for a long time, which is basically a no-op.  If `hold` is False, then the axes is cleared before adding the new artist.

Closing this as it is expected behavior.
