### ISSUE TITLE
Hatches filling an empty color contour not saved in pdf 

### ISSUE THREAD

**Issue by andres0l1** [matplotlib/matplotlib#8431]
I am trying to create a contour plot with the contours filled with hatches and no color. The following example works if I save it to .png but when I save it to .pdf the output is just the axis.
![github](https://cloud.githubusercontent.com/assets/26870251/24703884/2f5ff954-19fd-11e7-8e89-99d0d588fbbe.png)

```python
import numpy as np
import matplotlib.pyplot as plt



delta = 0.025

x = y = np.arange(-3.0, 3.01, delta)


X, Y = np.meshgrid(x, y)
Z1 = plt.mlab.bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0)
Z2 = plt.mlab.bivariate_normal(X, Y, 1.5, 0.5, 1, 1)
Z = 10 * (Z1 - Z2)


levels=[0,1]
plt.contourf(X, Y, Z/X, 
                  levels,
                  #alpha=0.5,
                  colors='none', label='AGH',
                   hatches=['\\'])

plt.tight_layout()   

plt.savefig('GitHub.pdf')
plt.show()
```

I am using Matplotlib2.00 in Linux, installed  from source.

**Comment by dstansby** [comment]
Is the figure above what you expected to see when saving to a .pdf file? If so I think this is fixed on our `master` branch (we did a couple of patch fixes recently)

**Comment by andres0l1** [comment]
Hi Dstansby! Thanks what should I do then? Update the library or what exactly? Thanks!

**Comment by tacaswell** [comment]
I can confirm that this works correctly on 2.0.x.  I suggest installing from git for now, 2.0.1 will be out soon with this fix.

I have not checked, but I suspect this was fixed by f6b4a32e6fb4d4687b40da3a81b0eefaad57a995 / #7976

**Comment by tacaswell** [comment]
either the master branch or 2.0.x should work.

**Comment by andres0l1** [comment]
Thanks a lot!!!

**Comment by tacaswell** [comment]
Closing as resolved, keep an eye out for the next release.

**Comment by mschauer** [comment]
There are still problems on version 2.0.2 with saving `hatch`es into pdfs. I am calling
```
fill_between(xx, upper, lower, edgecolor=darkcol, facecolor=lightcol, hatch="X")
```

**Comment by dstansby** [comment]
`2.1` is our latest release. Could you upgrade to that and let us know if there are still issues?

**Comment by mschauer** [comment]
I am now on 2.1.0 which fixes the problem. Thank you for the guidance.

**Comment by dstansby** [comment]
No problem!

**Comment by mschauer** [comment]
<img width="541" alt="hatch" src="https://user-images.githubusercontent.com/1923437/33432478-5b6f0822-d5d8-11e7-8082-81b9c5e4f9f1.png">

There is still something going on while saving hatches to pdf. Left the pdf, right the result of show. 
I am not sure if I am reaching the limits to mathplotlib, but to the left also the hatch became transparent. 
```
import matplotlib.pyplot as plt
xx = [1,2,3,4,5]
upper = [3,3,3,3,4]
lower = [1,2,2,2,2]
plt.fill_between(xx, upper, lower, edgecolor="darkred", facecolor=[0.5,0.5,0.5,0.1], hatch="X", label="as")
plt.legend()
plt.savefig('ups.pdf')
plt.show()
```

**Comment by afvincent** [comment]
The problem seems to occur with Acrobat Reader but not Evince. I tested the example from above with Matplotlib 2.0.0, 2.1.0 and from the master branch (on a Linux OS with Python 3.6): every time I get transparent hatches with Acrobat Reader (9.5.5) and correct hatches with Evince.

*Worth opening a new dedicated issue?*

**Comment by tacaswell** [comment]
@afvincent yes please
