### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by jjough** [matplotlib/matplotlib#8432]

**Comment by Tillsten** [comment]
Not really a bug, you are using subplot wrong. First number gives the total number of rows, second the the total number of columns and the last gives the index (counting left to right, top to bottom). So want you want is properly just `plt.subplot(131)`, `plt.subplot(132)` and `plt.subplot(133)`. Next time you may try Stackoverflow first.

**Comment by jjough** [comment]
@Tillsten great, thanks.

**Comment by tacaswell** [comment]
Closing due to the title and content being stubbed out.

@jjough In the future, please just close the issue but leave the content intact.  Your question might help someone in the future.
