### ISSUE TITLE
GridSpec update: unable to update width_ratios via `gs.update`

### ISSUE THREAD

**Issue by DSLituiev** [matplotlib/matplotlib#8434]
### Bug report

**Bug summary**

By using `GridSpec` `update` method I am unable to update `width_ratios` argument. The `GridSpec.update` method does not clearly document which keywords argument it takes.

**Code for reproduction**

```python
import matplotlib.gridspec as gridspec

gs1 = gridspec.GridSpec(1, 3, width_ratios=[3,1,2], left =0.1, right=0.2, wspace=0.05)
```
Now look into documentation: `gs1.update?`:

```
gs1.update(**kwargs)
Docstring:
Update the current values.  If any kwarg is None, default to
the current value, if set, otherwise to rc.
```

Well, why not updating `width_ratios`, which is a keyword argument:
```python
gs1.update(width_ratios=[3,1,2], )
```

**Actual outcome**
Error:
```
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/gridspec.py in update(self, **kwargs)
    228                 setattr(self, k, v)
    229             else:
--> 230                 raise AttributeError("%s is unknown keyword" % (k,))
    231 
    232 

AttributeError: width_ratios is unknown keyword
```

**Expected outcome**
- documentation describing which arguments are taken
- possibility to adjust the width and height ratios.

**Matplotlib version**

- Matplotlib version, 
'1.5.3'
- Python version
3.5
- and Platform (Windows, OSX, Linux ...)
OSX

- How did you install Matplotlib and Python (pip, anaconda, from source ...)
pip3

**Comment by DSLituiev** [comment]
I figured out there is another dedicated method for setting the width ratio. I wonder what is rationale behind not allowing for it to be called from the `.update`:

```python
import matplotlib.gridspec as gridspec

gs1 = gridspec.GridSpec(1, 3, width_ratios=[3,2,1], left =0.1, right=0.2, wspace=0.05)
gs1.update(left=0.0, right=0.72, wspace=0.05, )
gs1.set_width_ratios([1,2,4])
```

**Comment by phobson** [comment]
Glad you figured this out. I think the docs could be improved to clarify this. I'll leave this open so that it doesn't get lost.

**Comment by ImportanceOfBeingErnest** [comment]
I think there is a bit more to this. While `gs.update` actually updates the positions, `gs.set_width_ratios` does not. It just updates the gridspec; but the positions do not follow the changed parameter.

```
import matplotlib.pyplot as plt

fig = plt.figure()
gs = fig.add_gridspec(2,2)
ax1 = fig.add_subplot(gs[0,:])
ax2 = fig.add_subplot(gs[1,1])

gs.update(hspace=1)            # works
gs.set_width_ratios([1, 10])   # does not work

plt.show()
```

This is important to note because there is currently a tendency to bundle the gridspec more and more to an actual figure (i.e. we now have [`fig.add_gridspec`](https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_gridspec)). For such a gridspec there is hence no option to actually update the width_ratios.

Therefore remilestoning this for 3.2.

**Comment by jklymak** [comment]
I don't know, you've added the subplot already.  Its ambiguous whether you think changing the grid spec should change the width ratio of already added subplots.   Without layout managers, once a subplot is placed, its position is set.  

If you use a layout manager, it can consult the grid spec post-facto, and indeed the snippet above works as expected with `constrained_layout=True`.  Of course the incantation above is not compatible with tight layout, but if you do:

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(2, 2, constrained_layout=False)

gs = axs[0, 0].get_gridspec()
#gs.update(hspace=1)            # works
gs.set_width_ratios([1, 10])   # does not work
plt.tight_layout()
plt.show()
```
it also resizes appropriately.s

**Comment by tacaswell** [comment]
I am going to close this as "decline".  There is a way to get the desired affect and I agree with Jody that it is ambiguous what _should_ happen in this case.
