### ISSUE TITLE
Upper limit of axis behaves differently when having a zero value in a stacked bar plot

### ISSUE THREAD

**Issue by Khris777** [matplotlib/matplotlib#8437]
Take this example code:

	import pandas as pd
	import matplotlib.pyplot as mpp
	import random as rd

	rd.seed(77)

	#create random data:
	dd = {"S":['A','B','C','D','E','F']}
	for i in range(6):
		l = []
		for j in range(6):
			l.append(rd.randint(5*(6-i),5*(6-i+1)))
			if False:
				if rd.randint(0,10) == 5:
					l[j] = 0
		dd["E"+str(i)] = l

	# create Dataframe, make Data into percentages
	data = pd.DataFrame(dd)
	data["ES"] = data.iloc[:,0:6].sum(axis=1)
	data.iloc[:,0:6] = 100*data.iloc[:,0:6].div(data.ES,axis="index")

	# create figure and axis
	fig,ax = mpp.subplots(figsize=(6,8.48))
	ax.set_position([0.2,0.15,0.65,0.75])

	# Create stacked horizontal bar plots:
	things = data.columns[:6]
	ll = pd.Series(len(data)*[0.0])
	for i in range(len(things)):
		ax.barh(data.index,data[things[i]],left=ll,height=0.95)
		ll += data[things[i]]

This creates a nice horizontal stacked bar plot. Now if you change the `if` expression in the loop that creates the random data to `True` it will set some of the data to zero. Plotting this again leads to a different result. While in the first result the bars have a visible space on the right side, in the second result the space is gone, the upper `xlim` is exactly 100 now instead of giving the bars some space.
This behaviour is interfering when working with real data where zeros may or may not appear at all.

Doing a vertical bar plot `ax.bar(data.index,data[things[i]],bottom=ll,width=0.95)` leads to the same behaviour.

The easy workaround is to just manually set `ax.set_xlim([0,105])` by default when doing this kind of plot.

Python 2.7.13
Matplotlib 2.0.0

**Comment by QuLogic** [comment]
This only appears to affect Python 2, but I think that's because the randomness is different. Can you simplify the example with a specific set of data that doesn't use randomness or Pandas?

**Comment by Khris777** [comment]
New example:

	import matplotlib.pyplot as mpp

	xData = [0,1,2]
	yData = [[0.25,0.0,0.7],[0.25,0.3,0.1],[0.5,0.7,0.2]]

	fig,ax = mpp.subplots(figsize=(6,8.48))
	ax.set_position([0.2,0.15,0.65,0.75])

	ll = [0,0,0]
	for i in range(len(yData)):
		ax.barh(xData,yData[i],left=ll,height=0.95)
		ll = [ll[j] + yData[i][j] for j in range(len(yData))]

Surprisingly now the problem does not appear.
In my real data there is no randomness, so does it have to do with `pandas`?

**Comment by rcomer** [comment]
I tried to run the example from the OP with a current environment, but got errors from pandas.  Given that

> This only appears to affect Python 2

I think it is safe to close this one.  If someone has a  similar problem they can always open a new issue.
