### ISSUE TITLE
Emit event when changing xscale/yscale

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#8439]
At the moment, changing xlim/ylim results in an xlim_changed/ylim_changed event being emitted, but there is nothing equivalent for changing xscale/yscale. Would it be possible to add this?

**Comment by WeatherGod** [comment]
Yes, it should be possible to do, especially if we follow similar design
patterns as for 'xlim_changed'. So, like set_xlim(), set_xscale() would
need an `emit` keyword, and we would need to figure out when to not emit in
the internal code, much like for set_xlim(). We should also remember to
update the blitting code to recognize this event as well.

**Comment by anntzer** [comment]
Seems like something that should ultimately be subsumed by the move to traitlets -- if it ever happens :-)

**Comment by MichaelTheFear** [comment]
Hi, I had a thought about this issue and I was thinking on something like this

```py
def onchange_scale_x(self,func):
    __set_xscale = self.set_xscale
    def wrapper_xscale(*args,**kwargs):
        __set_xscale(*args,**kwargs)
        res = self.get_xscale()
        func(res)
    self.set_xscale = wrapper_xscale

def onchange_scale_y(self,func):
    __set_yscale = self.set_yscale
    def wrapper_yscale(*args,**kwargs):
        __set_yscale(*args,**kwargs)
        res = self.get_yscale()
        func(res)
        
    self.set_yscale = wrapper_yscale
   ``` 
  these two functions overrides the definitions of set_yscale and set_xscale only to listen when they are called, would that be ok  or should I do something different?
