### ISSUE TITLE
ImportError: No module named _backend_gdk

### ISSUE THREAD

**Issue by GPrathap** [matplotlib/matplotlib#8441]
I am using matplotlib 2.0.0. I want to render to a GTK UI window. But I am geeting this error. 

### Bug report

>>> from matplotlib.backends.backend_gtkagg \
... import FigureCanvasGTKAgg as FigureCanvas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 36, in <module>
    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
ImportError: No module named _backend_gdk

**Code for reproduction**

This is the code which I am trying to execute so as to reproduce this issue

```
import matplotlib
matplotlib.use('GTKAgg')
import gtk
from matplotlib.figure import Figure
import numpy as np
from matplotlib.backends.backend_gtkagg \
import FigureCanvasGTKAgg as FigureCanvas
```

gtk.pygtk_version: 2.24.0, I am testing on linux 16.04 machine

**Comment by jenshnielsen** [comment]
How did you install matplotlib. The GTK(2) backends needs a compiled component so matplotlib needs to be able to find GTK when being build. The GTK3 and most other backends don't have this limitation

**Comment by GPrathap** [comment]
This is how I installed matplotlib :  `sudo apt-get install python-matplotlib`. Please let me know is there any other way of installing matplotlib which support gtk.

**Comment by jenshnielsen** [comment]
I don't really understand how you are apt-get installing matplotlib 2.0 from Ubuntu 16.04. (I assume thats what you mean by linux 16.04) According to http://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=matplotlib it has matplotlib 1.5.1. Did you get it from a ppa or some other external source? 

You can build matplotlib from source or you can use a different backend but that may be tricky if you are not familiar with it.

Is there any particular reason you need the GTK(2) backend. The GTK3 backend is much more modern and doesn't have this compile time issue.

**Comment by GPrathap** [comment]
Sure, thanks for the information. I had [this issue](http://stackoverflow.com/questions/43003758/matplotlib-is-throwing-segmentation-fault-when-running-on-non-gui-machineweb-se) previously with 1.5.1. Then installed 2.0.0 using ` sudo pip install matplotlib=2.0.0`. Then I resolved that issue. 

Truly speaking I don't have mush idea about GTK(2) or GTK(3). So I will use GTK(3). I want to do something related real-time plotting. Anyway thanks for your prompt response. You can close this issue.

**Comment by jenshnielsen** [comment]
Great, Ok then you didn't use apt but pip to install matplotlib. The whl binary packages that are installed from pypi with pip are indeed not build with GTK2 support so thats why it doesn't work. They have to work on all kind of linux systems so they cant have dependencies like that unfortunately

**Comment by GPrathap** [comment]
Ok, cool.  I had that mystery between apt-get vs. pip installation thing. Now I understood. Thanks a lot.

**Comment by Borda** [comment]
Hello, 
it seems that I have the issue, matplotlib==2.0.2 but I am still receiving the same import error for
`from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg`
as
```
  File "/home.dokt/borovji3/.local/lib/python2.7/site-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
  File "/mnt/datagrid/personal/borovec/Applications/PyCharm.Pro/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named _backend_gdk
```
I tried to install the library via pip and also python-matplotlib

**Comment by WeatherGod** [comment]
_backend_gdk.so has to be built from source. It is done automatically while
installing from source if the appropriate gtk/gdk header files are present
on the system at build time.
