### ISSUE TITLE
New urlopen HTTPError on manylinux machines

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#8442]
I'm getting a new testing error running the daily builds.

All the manylinux builds are failing with this single error:

```
@pytest.mark.network
    def test_load_from_url():
        req = six.moves.urllib.request.urlopen(
>           "http://matplotlib.org/_static/logo_sidebar_horiz.png")

/venv/local/lib/python2.7/site-packages/matplotlib/tests/test_image.py:581: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/urllib2.py:127: in urlopen
    return _opener.open(url, data, timeout)
/usr/lib/python2.7/urllib2.py:410: in open
    response = meth(req, response)
/usr/lib/python2.7/urllib2.py:523: in http_response
    'http', request, response, code, msg, hdrs)
/usr/lib/python2.7/urllib2.py:448: in error
    return self._call_chain(*args)
/usr/lib/python2.7/urllib2.py:382: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <urllib2.HTTPDefaultErrorHandler instance at 0x7f5845c37f38>
req = <urllib2.Request instance at 0x7f5845c37e18>
fp = <addinfourl at 140017057248248 whose fp = <socket._fileobject object at 0x7f5842ad9350>>
code = 403, msg = 'Forbidden'
hdrs = <httplib.HTTPMessage instance at 0x7f5843609c20>

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
E       HTTPError: HTTP Error 403: Forbidden
```

See: https://travis-ci.org/MacPython/matplotlib-wheels/jobs/219593901

Further investigation reveals that the request seems to require a `User-Agent` string in the header, which can be empty - test script:

```
# get_url.py
import six

url = "http://matplotlib.org/_static/logo_sidebar_horiz.png"

# Request object with empty user agent
request = six.moves.urllib.request.Request(url, None, {'User-Agent': ''})

# The URL on its own does not work
try:
    response = six.moves.urllib.request.urlopen(url)
except six.moves.urllib.error.HTTPError as err:
    print('Failed with {}'.format(err))

# With the headers, it does work
response = six.moves.urllib.request.urlopen(request)
data = response.read()
print('Succeeded with bytes {}'.format(data[:4]))
```

On the manylinux docker container, this gives:

```
# python get_url.py
Failed with HTTP Error 403: Forbidden
Succeeded with bytes ?PNG
```

Oddly, on my macOS laptop, the urlopen(url) command always failed until I did a request with headers, as above, at which point all subsequent urlopen(url) commands succeeded.   So, you may need the container to replicate this.

Is this something to do with the redirection via Cloudflare?

**Comment by tacaswell** [comment]
This is likely a side-effect of the cloudflare change, we saw the same thing in the main travis tests.

attn @jkseppan

**Comment by jkseppan** [comment]
Probably a side effect of that, yes. I set the security setting to "essentially off" but we still had to whitelist the Travis addresses. But this is on Travis, right?

I think one option is to change the URL in that test to use the matplotlib.github.io domain so it doesn't go through Cloudflare.

**Comment by matthew-brett** [comment]
The problem seems to be that the request requires a (possibly empty) User-Agent header.  So, this will always work from a browser, but not from Python via the URL string.

When I try to access http://matplotlib.github.io it redirects through http://matplotlib.org/

Sure enough:

```
# python -c 'import six; six.moves.urllib.request.urlopen("http://matplotlib.github.io")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/cp27-cp27mu/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jkseppan** [comment]
It seems that it's possible to make a "page rule" in Cloudflare to bypass the checks. There's a very limited number of rules available in the free plan, but I guess this test URL should be one of those. I'll take a look when I have some more time.

**Comment by matthew-brett** [comment]
An alternative would be to add the empty User-Agent header to the request in the test, I guess.

**Comment by jkseppan** [comment]
I added a page rule for that file to disable the security checks. Could you try again? I can't reproduce this myself because I didn't see a problem from my computer before adding the rule, but that is probably a function of how many earlier attempts have been made from the same IP address.

**Comment by jkseppan** [comment]
I discovered and turned off yet another CloudFlare feature: "Browser Integrity Check: Evaluate HTTP headers from your visitors browser for threats. If a threat is found a block page will be delivered."

That seems like it could have been the problem, or at least part of the problem.

**Comment by matthew-brett** [comment]
I don't which fix fixed it, but on the manylinux container, I don't get the error now.

**Comment by jkseppan** [comment]
I turned off the page rule, since I think it was probably the browser integrity check that was the culprit here, and page rules are a scarce resource. Let's see if any problems resurface.

**Comment by matthew-brett** [comment]
Looks like this one is fixed now, thanks, closing.
