### ISSUE TITLE
Allow to change base of LogNorm?

### ISSUE THREAD

**Issue by Phlya** [matplotlib/matplotlib#8457]
I think it would be great to be able to change the base of the LogNorm (and SymLogNorm) - for example, if the range of values is not that big, base of 2 would provide many more ticks than base of 10, and especially important if there is less than 10-fold difference between vmin and vmax. Also I suspect in some cases a natural log would be a good choice. As far as I understand, there is currently no way to do this. But maybe I am wrong?..

**Comment by story645** [comment]
If you're fine with discrete bins, you can do this via `BoundaryNorm`, but I can't find anything that'll support a continuous mapping. I'm tentatively 👍

**Comment by efiring** [comment]
There is no need to change `LogNorm`, as far as I can see.  I think what you are talking about is really just a matter tick location and formatting, e.g.
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

yr = 3 * np.random.rand(20, 30)
y = 2**yr

fig, ax = plt.subplots()
im = ax.pcolormesh(y, norm=LogNorm(1, 8))

cbar = fig.colorbar(im, ax=ax)
cbar.set_ticks([1, 2, 4, 8])
cbar.set_ticklabels(['$1$', '$2$', '$2^2$', '$2^3$'])
fig.savefig('LogNorm_ticks_base_2.png')
```
![lognorm_ticks_base_2](https://cloud.githubusercontent.com/assets/85125/24938474/234dffb4-1ed3-11e7-8ab8-2f802a4132a2.png)

**Comment by Phlya** [comment]
While you are correct that this is a way to do this (thank you!), I still think there should be an easier way - in case when you generate many plots with different vmin/vmax you would need to calculate the new ticks and their labels for each plot. Not very difficult, but changing the base of the log seems to me like such an obvious idea that it should be very easy to do. Maybe it's just my opinion, and you won't agree...

**Comment by efiring** [comment]
I think you are missing the point; the LogNorm itself is not what needs to be changed, if anything does.  The LogNorm does not determine where the ticks are placed or how they are formatted.  Those jobs are handled by a Locator and a Formatter.  The various LogFormatter and LogLocator classes already allow you to set a base, so I could have used them in the example instead of specifying the ticks and strings directly.

**Comment by efiring** [comment]
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from matplotlib.ticker import LogLocator, LogFormatterSciNotation

yr = 3 * np.random.rand(20, 30)
y = 2**yr

locator = LogLocator(base=2)
formatter = LogFormatterSciNotation(base=2)

fig, ax = plt.subplots()
im = ax.pcolormesh(y, norm=LogNorm(1, 8))

cbar = fig.colorbar(im, ax=ax, ticks=locator, format=formatter)
fig.savefig('LogNorm_ticks_base_2a.png', dpi=100)
```
![lognorm_ticks_base_2a](https://cloud.githubusercontent.com/assets/85125/24946214/e80c9b10-1efd-11e7-91fa-3be17249b694.png)

**Comment by Phlya** [comment]
OK, thank you, this solves it then!

**Comment by tacaswell** [comment]
To be a bit clearer, the value computed by `LogNorm` is

```
(log(inp) - log(min(inp))) / (log(max(ing)) - log(min(inp)))
```

To change to base 2 you would divide each term by `log_2(10)` which would then cancel out leaving you with the same expression.

**Comment by Phlya** [comment]
Funny, almost exactly a year has passed, and I am back here, checking how it is done! Maybe this example by @efiring would be a good addition to the documentation?
