### ISSUE TITLE
Errorbar plot has no name in axis.get_lines()

### ISSUE THREAD

**Issue by SirJohnFranklin** [matplotlib/matplotlib#8458]
### Bug report

**Bug summary**
In constrast to adding a plot with plt.plot(), adding a errorbar plot with plt.errorbar() does not assign a valid name to the line itself (also to the errorbars would be nice).

**Code for reproduction**
matplotlib version: 2.0.0

```python
import matplotlib.pyplot as plt
import numpy as np

t = 18.2781
x = np.linspace(0., 2 * np.pi, np.random.randint(5, 500))
y = np.sin(x * t)

plt.plot(x, y, label='sin without error')
plt.errorbar(x, y/2., xerr=x * np.random.random(x.shape) / 30., yerr=y * np.random.random(x.shape) / 20.,
              fmt='o-', linestyle='dashed', label='sin', ecolor='k', capsize=3)
plt.legend(loc=0)

ax = plt.gca()
for l in ax.get_lines():
    print(l)

plt.show()
```

**Actual outcome**
```
Line2D(sin without error)
Line2D(_nolegend_)
Line2D(_nolegend_)
Line2D(_nolegend_)
Line2D(_nolegend_)
Line2D(_nolegend_)
```

**Expected outcome**
```
Line2D(sin without error)
Line2D(sin)
Line2D(_nolegend_)
Line2D(_nolegend_)
Line2D(_nolegend_)
Line2D(_nolegend_)
```
or even better:
```(errx_top, errx_bot, erry_top, erry_bot)
Line2D(sin without error)
Line2D(sin)
Line2D(sin_errx_top_nolegend_)
Line2D(sin_errx_bot_nolegend_)
Line2D(sin_erry_top_nolegend_)
Line2D(sin_erry_bot_nolegend_)
```

**Matplotlib version**
matplotlib version: 2.0.0
Windows 10, 64bit, Anaconda Python 2.7 (will be the same for others)

**Comment by dstansby** [comment]
Having a look through the code, the label is applied to the `ErrorbarContainer` object returned by the errorbar method:

```python
import matplotlib.pyplot as plt
import numpy as np

t = 18.2781
x = np.linspace(0., 2 * np.pi, np.random.randint(5, 500))
y = np.sin(x * t)

plt.plot(x, y, label='sin without error')
errbar = plt.errorbar(x, y/2., xerr=x * np.random.random(x.shape) / 30., yerr=y * np.random.random(x.shape) / 20.,
              fmt='o-', linestyle='dashed', label='sin', ecolor='k', capsize=3)
print(errbar.get_label())   # sin
```

**Comment by tacaswell** [comment]
If you want access to the artists, capture the return.  

Even though it is public, I suggest not relying on `ax.lines` for access to created artists, it is really an internal implementation detail. 

It would be a pretty major API change to re-arrange the internals of where and how the errorbar artist(s) are stored internally so I do not think we will make the suggested change, sorry.

Thank you for taking the time to report this!
