### ISSUE TITLE
Possible legend locations

### ISSUE THREAD

**Issue by Franjov** [matplotlib/matplotlib#8464]
A naive question regarding the `loc` argument of `plt.legend`:

```python
In [5]: plt.legend(loc='left')
/opt/miniconda/lib/python3.6/site-packages/matplotlib/legend.py:326: UserWarning: Unrecognized location "left". Falling back on "best"; valid locations are
	best
	upper right
	upper left
	lower left
	lower right
	right
	center left
	center right
	lower center
	upper center
	center

  six.iterkeys(self.codes))))
```

Is there a reason why `right` is accepted whereas `left` is not?

By the way, is `right` the same as `center right`?
It seems so, but I could not find any confirmation in the doc.

**Comment by QuLogic** [comment]
I believe it is the same as `center right`; I suspect it exists only for backwards compatibility, but I'm not sure anyone really knows any more.

**Comment by tacaswell** [comment]
It looks like the docstring in `Legend` comes from e34a333d00814124d3e19d462b9d78ac35e7a49a (2004!) which has both 'right' and 'center right' which chasing back through blame seems to always have been aliases for each other.

For glancing at the code, adding a 'left' key would be a fair amount of work (probably re-write the legend box placement code would be the best approach, it _looks_ like there is unneeded complexity there, but I have been wrong about that before).

Probably the best thing to do is to add a note to the docs that `'right'` and `'center right'` are equivalent.
