### ISSUE TITLE
zorder values as a sequence are not respected by LineCollection

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#8465]
**Bug summary**

Looking at `LineCollection` docstring, one can read: “All parameters must be sequences or scalars” so I would expect passing a sequence of zorder values to be fine. Unfortunately, it does not seem to be working and it looks like the lines zorder correspond to their ”index” in the collection.

**Code for reproduction**
```python
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

ll = LineCollection([((0, 0), (1, 1)),  # tilted line
                     ((0.2, 0), (0.2, 1)),  # vertical line
                     ((0, 0.5), (1, 0.5))],  # horizontal line
                    colors=['r', 'g', 'b'], zorder=[5, 10, 2], linewidths=10)

fig, ax = plt.subplots()
ax.add_collection(ll)

plt.show()

print(ll.get_zorder())  # [5, 10, 2] so the expected result is:
                        # vertical green > oblique red > horizontal blue

# fig.savefig('expecting_green_over_red_over_blue.png')
```

**Actual outcome**
![expecting_green_over_red_over_blue](https://cloud.githubusercontent.com/assets/17270724/24950330/146a637c-1f71-11e7-82ec-45c85555c0e6.png)

**Expected outcome**
Based on the passed and returned zorder values, one would expect:
vertical green > oblique red > horizontal blue

**Matplotlib version**

Tested on Matplotlib 2.0.0.post3871+gf9e0b92 from GitHub and 1.5.1 from conda, on Linux (CentOS 7) and with Python 2.7.

**Comment by anntzer** [comment]
Actually this is never going to work.  Even adding `ax.plot([0, 1])` next to this fails with
```
...
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2386, in draw
    dsu.sort(key=itemgetter(0))
TypeError: '<' not supported between instances of 'int' and 'list'
```

The whole point of LineCollection (of Collections, in fact) is that the whole collection is handled in a single shot by the renderer for optimization purposes, so there is no way you can for example interlace the rendering of a LineCollection with the rendering of another artist (which you'd need to be able to do if different members of the LineCollection had varying zorders).

Closing, but feel free to reopen if you disagree.

**Comment by WeatherGod** [comment]
The core devs have been bouncing around ideas for how to make collections
more versatile, particularly being able to interleave the drawing of
different kinds of artists in the rendering engine. We see a related
problem with the z-ordering of error bar markers and lines, and the Escher
Effects in mplot3d. Fixing this problem is going to require a fundamental
overhaul of the 2D layering engine.
