### ISSUE TITLE
initialise imshow with zero array has unexpected side effects

### ISSUE THREAD

**Issue by paulbrodersen** [matplotlib/matplotlib#8467]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report

**Bug summary**

When initialising AxesImage with `numpy.zeros` array, changing the image with `set_data` will have no effect on the displayed image (whereas the reverse is not true, i.e. initialise with non-zero arrays, change data to zero array).

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

shape = (10,10)
Z = np.zeros(shape)
R = np.random.rand(*shape)

fig, ax = plt.subplots(1,1)
img1 = ax.imshow(R)
img1.set_data(Z) # shows zero array

fig, ax = plt.subplots(1,1)
img2 = ax.imshow(Z)
img2.set_data(R) # also displays zero array, ...

# ..., even though img.get_array() returns the correct array
print np.all(np.isclose(img2.get_array(), R))
```

**Actual outcome**

Two blue images.

**Expected outcome**

First figure blue, second figure showing randomly coloured pixels. 

**Matplotlib version**

matplotlib 2.0.0 (installed via pip), python 2.7, Ubuntu 14.04 LTS

**Comment by paulbrodersen** [comment]
**Addendum** 

I stumbled across this issue when I tried to make an animation with imshow along the lines of:

```python
def animate(movie, **kwargs):
    """
    Animate an image stack with dimensions frame, height, width.
    """
    fig, ax = plt.subplots(1,1)
    img = ax.imshow(np.zeros((movie.shape[1], movie.shape[2])), **kwargs) <- this doesn't work
    # img = ax.imshow(movie[0], **kwargs) # <- this alternative works

    def update(ii):
        print ii
        img.set_data(movie[ii])
        return img,

    return FuncAnimation(fig, update, blit=True, interval=50)
```

In my particular use case, the image stack is pretty large so I don't actually handle the function the full array but rather `update` loads each frame dynamically.

**Comment by paulbrodersen** [comment]
**Addendum 2**

Any uniform array (`np.ones(*shape)`, `np.ones(*shape)*0.1`, `np.ones(*shape)*10`) leads to the same weird behaviour.

**Comment by paulbrodersen** [comment]
Ok, I finally understood the problem. The issue is that when initialising the image with a uniform array, the minimum and maximum of the colormap are identical. As we are only changing the data, not the colormap, all images are shown as being of uniform colour. 

I suppose that you probably might not want to update the colourmap dynamically, but it would be nice to make people aware of this gotcha somewhere in the docs. A good place might be examples/animation/dynamic_image.html.

**Comment by anntzer** [comment]
xref #8468

**Comment by anntzer** [comment]
Closed by #8468.

**Comment by kernelizd** [comment]
How do you solve this problem? In my case, it is not me who deliberately initializes with uniform arrays, it is just coming in this way. How do you go about changing normalization?

**Comment by paulbrodersen** [comment]
@kernelizd Probably the easiest way is to set the parameters `vmin` and `vmax` explicitly when you first call `imshow`:

```
img = plt.imshow(arr, vmin=expected_minimum_value, vmax=expected_maximum_value)
```
