### ISSUE TITLE
equal aspect should try using equal tick spacing

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8469]
In an example like https://matplotlib.org/devdocs/examples/pylab_examples/equal_aspect_ratio.html, it is not obvious at all that the aspect ratio is the same between the two axes, because the tick spacing is different.

Also that specific example is a bit silly as the two axes have different dimensions (in terms of physical units: s vs mV), so it actually doesn't make much sense to impose equal aspect here.  A more physically correct example would be better.

Edit: the example above has been removed in f1928e6, but see https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/axis_equal_demo.html for one where the equal spacing still makes sense.

**Comment by WeatherGod** [comment]
This is probably another motivator for revamping the ticker system so that
not only can major and minor tickers can "communicate" with each other, but
also tickers across multiple axis'es.

**Comment by efiring** [comment]
On 2017/04/13 4:44 AM, Benjamin Root wrote:
> This is probably another motivator for revamping the ticker system so that
> not only can major and minor tickers can "communicate" with each other, but
> also tickers across multiple axis'es.

I think that would be going too far--too complicated, too much guessing 
about what the user might want.

But fixing the example makes sense.

**Comment by sjvrijn** [comment]
@anntzer Is there still something wrong with the `axis_equal_demo` example? The tick spacing seems fine to me in the equal aspect ratio cases.

**Comment by timhoffm** [comment]
The example chooses same tick spacing now. But that's just chance.

The general problem still exists (e.g. #17965) but is hard to solve.

**Comment by jklymak** [comment]
I don't see any reason for the tick spacing to be the same if the axises are different sizes.  That just seems like too much magic that half the users wouldn't want anyway.

**Comment by efiring** [comment]
I agree with @jklymak and think this should be closed.  Any objections?

**Comment by anntzer** [comment]
I certainly realize this would be quite hard to achieve in the current model, but I actually still think the request is reasonable?  I'm not going to fight to keep this open, though.

**Comment by Atcold** [comment]
Absolutely, @efiring, I'm strongly objecting.
`axis('equal')` is issued when one wants `y = x` to be at 45° and bisecting the squared grid.
You know, like when you draw on your notebook. No one uses a rectangular grid, right?

**Comment by anntzer** [comment]
I still think this would be nice, but short of completely rearchitecting the ticker system it seems close to impossible to make this work.  Perhaps we should just have a master "future ticker improvements" issue to track all these long-term ideas...
