### ISSUE TITLE
Colorbar documentation: `anchor` not recognized as possible argument to plt.colorbar

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#8493]
The [figure api documentation of `colorbar`](http://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.colorbar) lists  `anchor` and `panchor` as
possible arguments to `figure.colorbar()`. However they do not seem to exist anymore. 

E.g. when running the following in matplotlib 2.0:
```
import matplotlib.pyplot as plt
import numpy as np; np.random.seed(1)

fig, ax = plt.subplots()
im = ax.imshow(np.random.rand(11,16))
ax.set_xlabel("x label")

fig.colorbar(im, ax=ax, anchor=(0.0, 0.5))
plt.show()
```

the following error is thrown:

```
Traceback (most recent call last):
  File "D:\⬜⬜⬜⬜\⬜⬜⬜\⬜⬜⬜\python\test\SO_colorbar.py", line 15, in <module>
    fig.colorbar(im, ax=ax, anchor=(0.0, 0.5))
  File "c:\⬜⬜⬜⬜\⬜⬜⬜⬜\python-2.7.10.amd64\lib\site-packages\matplotlib\figure.py", line 1602, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "c:\⬜⬜⬜⬜\⬜⬜⬜⬜\python-2.7.10.amd64\lib\site-packages\matplotlib\colorbar.py", line 1347, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "c:\⬜⬜⬜⬜\⬜⬜⬜⬜\\python-2.7.10.amd64\lib\site-packages\matplotlib\colorbar.py", line 926, in __init__
    ColorbarBase.__init__(self, ax, **kw)
TypeError: __init__() got an unexpected keyword argument 'anchor'
```

I could imaging that this is simply because the documentation has not been updated?!

**Comment by sabian2008** [comment]
Not really. They are still supported, however there seems to be an argument parsing bug? in the target function. You need to append "use_gridspec=False" to the arguments so that anchor and panchor are parsed correctly.

Don't know if this is intended behavior or not.

**Comment by tacaswell** [comment]
Looks like the default value of `use_gridspec` was changed in da8827164b5d7664e0efb1fee8995769f5cfe32d

I think the correct thing to do is to label the entries in the table (now at https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.colorbar) and defined at https://github.com/matplotlib/matplotlib/blob/2fd479a2e65b8fd3258c8746a1837b43e9e3beb7/lib/matplotlib/colorbar.py#L46-L64

Should be marked which are contingent on `use_gridspec`.  This is not completely trivial as that string block is injected into a couple of docstrings (for `colorbar` and for the two helper functions).
