### ISSUE TITLE
vlines use of color string broken in 2.0.0

### ISSUE THREAD

**Issue by cmardiros** [matplotlib/matplotlib#8496]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report
`ax.vlines(x=-1.95, ymin=0, ymax=0.025, colors='r', alpha=1)` works in 1.5.0 but not in 2.0.0.

NOTE: vlines has as default argument colors='k' so the above should work.

**Bug summary**

Error returned is 
```
"Colormap <matplotlib.colors.LinearSegmentedColormap object at 0x7fdbede7e090> is not recognized".
```

**Code for reproduction**

Running demo code http://matplotlib.org/devdocs/mpl_examples/pylab_examples/vline_hline_demo.py found on http://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.vlines.html illustrates the problem.

**Matplotlib version**

2.0.0 (installed with anaconda3)

**Comment by tacaswell** [comment]
I can not reproduce this (on master or v2.0.0)

```
21:45 $ ipython
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot as plt

In [2]: plt.ion()

In [3]: fig, ax = plt.subplots()

In [4]: ax.vlines(x=-1.95, ymin=0, ymax=0.025, colors='r', alpha=1)
Out[4]: <matplotlib.collections.LineCollection at 0x7f84ef7ef4a8>

In [5]: import matplotlib

In [6]: matplotlib.__version__
Out[6]: '2.0.0.post4110+gb58ccb910'

In [7]: 

```

```
In [8]: import matplotlib.pyplot as plt
   ...: plt.ion()
   ...: fig, ax = plt.subplots()
   ...: ax.vlines(x=-1.95, ymin=0, ymax=0.025, colors='r', alpha=1)
   ...: import matplotlib
   ...: matplotlib.__version__
   ...: 
   ...: 
Out[8]: '2.0.0'

```

![so](https://cloud.githubusercontent.com/assets/199813/25076358/26963fc8-22ee-11e7-963d-2f40e9147ebb.png)

**Comment by jenshnielsen** [comment]
@tacaswell but evidently it was an issue when the 2.0 docs was last rebuild.

Compare http://matplotlib.org/devdocs/mpl_examples/pylab_examples/vline_hline_demo.png
to http://matplotlib.org/mpl_examples/pylab_examples/vline_hline_demo.png

**Comment by tacaswell** [comment]
The red lines were added in d353c71864257d0fcf2c21501f1e47ace8bcfb9a and not in the source to generate the main docs.

**Comment by dstansby** [comment]
This is what I get on master, OSX, python 3.6.1, which I presume is what it's meant to look like

![figure_1](https://cloud.githubusercontent.com/assets/6197628/25345918/0dca1e6e-28cb-11e7-9157-e4da21a77c95.png)

**Comment by anntzer** [comment]
I am going to close the issue as it apparently cannot be reproduced (I can't either), but @cmardiros feel free to provide more detail if you want to keep discussing it.
