### ISSUE TITLE
Remove false deprication warning

### ISSUE THREAD

**Issue by hiccup7** [matplotlib/matplotlib#8501]
I am seeing "backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented" when using `pyplot.pause(1)` or `pyplot.waitforbuttonpress(timeout=-1)`

@tacaswell indicated 3 years ago that this was a false warning:
http://stackoverflow.com/questions/22873410/how-do-i-fix-the-deprecation-warning-that-comes-with-pylab-pause

Is it really a false warning (to be fixed), or does the matplotlib team suggest a Pythonic way of avoiding the warning?

Tested with matplotlib 2.0.0 & Python 3.5.3 in an IPython console in 64-bit Windows 8.1

**Comment by anntzer** [comment]
xref #8185

**Comment by hiccup7** [comment]
I forgot to mention that I am using the Qt5 backend.

**Comment by hiccup7** [comment]
@anntzer - I edited backend_qt5.py according to the changes in #8185, and it fixed the problem, both with `pyplot.pause(1)` and `pyplot.waitforbuttonpress(timeout=-1)`.

Will #8185 be in release v2.0.1?  I noticed the commit failed 2 / 5 checks.

**Comment by phobson** [comment]
@hiccup7 the checks that failed won't block it from being included. We just need someone familiar with tQT backend to review it (I'm not familiar with QT at all, unfortunately).

**Comment by QuLogic** [comment]
Fixed by #8185.
