### ISSUE TITLE
`%matplotlib notebook` show nothing, both 2d and 3d plot

### ISSUE THREAD

**Issue by secsilm** [matplotlib/matplotlib#8508]
`%matplotlib notebook` show nothing while `%matplotlib inline` work. I'm using Chrome.

## 2D plot

```python
from sklearn.manifold import TSNE
from sklearn.datasets import load_digits
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import seaborn

digits = load_digits()
X = digits.data
y = digits.target

trans = TSNE().fit_transform(X)

plt.scatter(trans[:, 0], trans[:, 1], s=4, c=y)
```

**Actual outcome**

![2d](http://i.imgur.com/tKIubnS.png)

## 3D plot

```python
from sklearn.manifold import TSNE
from sklearn.datasets import load_digits
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import seaborn

digits = load_digits()
X = digits.data
y = digits.target

trans1 = TSNE(n_components=3).fit_transform(X)

fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(trans1[:, 0], trans1[:, 1], trans1[:, 2])
plt.show()
```
**Actual outcome**

![3d](http://i.imgur.com/QnMf3eu.png)

**Matplotlib version**

- Matplotlib version: 2.0.0
- How did you install Matplotlib and Python (pip, anaconda, from source ...): anaconda

**Comment by phobson** [comment]
what happens if you remove all of the sklearn stuff and just do:
```
%matplotlib notebook
from matplotlib import pyplot
fig, ax = pyplot,subplots()
ax.plot([1, 2, 3], [4, 2, 7])
pyplot.show()?
```

**Comment by secsilm** [comment]
@phobson YES, the code works. 

Weird! My code just work when I retry today. But it's very slow.

**Comment by dstansby** [comment]
Since this seems to be fine now I'll close; feel free to re-open if the issue appears again.
