### ISSUE TITLE
autofmt_xdate should not make xticklabels invisible when x-axis is not shared between rows

### ISSUE THREAD

**Issue by gerritholl** [matplotlib/matplotlib#8509]
### Bug report

**Bug summary**

When one calls the `Figure` method `autofmt_xdate` for a figure that contains multiple subplots, the xticklabels are made invisible on all but the last row.  This is undesirable when the x-axis is not shared between rows.  Moreover, it also removes xticklabels for subplots where the x-axis is not a datetime one at all.

- A short 1-2 sentences that succinctly describes the bug

**Code for reproduction**

```
(fig, axes) = subplots(ncols=2, nrows=2)
axes[0,0].plot_date([datetime.datetime(1985, 8, 13), datetime.datetime(1985, 8, 14), datetime.datetime(1985, 8, 15)], [0, 1, 2])
fig.autofmt_xdate()
```

**Actual outcome**

![resulting plot](http://i.imgur.com/1JW9iPs.png)

**Expected outcome**

It would be desirable to have an option to fix the ticks on the affected subplot without removing them, and in particular not removing them on subplots that don't have a datetime xaxis.

**Matplotlib version**

Matplotlib 2.0.0, Python 3.5.0.

**Comment by phobson** [comment]
This behavior is described in the docstring of the `autofmt_xdate` function. 

It'd help to understand what your broader goals are. For instance, if all you want to do is rotate the labels of 1 axis, it might make more sense to keep a function like the one below handy:

```python


def rotateTickLabels(ax, rotation, which, rotation_mode='anchor', ha='right'):
    """ Rotates the ticklabels of a matplotlib Axes
    Parameters
    ----------
    ax : matplotlib Axes
        The Axes object that will be modified.
    rotation : float
        The amount of rotation, in degrees, to be applied to the labels.
    which : string
        The axis whose ticklabels will be rotated. Valid values are 'x',
        'y', or 'both'.
    rotation_mode : string, optional
        The rotation point for the ticklabels. Highly recommended to use
        the default value ('anchor').
    ha : string
        The horizontal alignment of the ticks. Again, recommended to use
        the default ('right').
    Returns
    -------
    None
    """

    if which == 'both':
        rotateTickLabels(ax, rotation, 'x', rotation_mode=rotation_mode, ha=ha)
        rotateTickLabels(ax, rotation, 'y', rotation_mode=rotation_mode, ha=ha)
    else:
        if which == 'x':
            axis = ax.xaxis

        elif which == 'y':
            axis = ax.yaxis

        for t in axis.get_ticklabels():
            t.set_horizontalalignment(ha)
            t.set_rotation(rotation)
            t.set_rotation_mode(rotation_mode)
```

Personally, I think it would make sense to make `autofmt_xdate` a method the `Axes` class, and then the `Figure` method could rely on that.

**Comment by gerritholl** [comment]
I'm not calling `autofmt_xdate` directly.  I'm using [`xarray`s plotting routines](http://xarray.pydata.org/en/stable/plotting.html) which in turn call `autofmt_xdate`.

**Comment by phobson** [comment]
@gerritholl that wasn't clear from your initial report. it might be best to submit a PR there.

**Comment by gerritholl** [comment]
True; I figured that since it happens in matplotlib it should be reported here.  I think it could still be useful to make [`autofmt_xdate`](https://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.autofmt_xdate) more versatile.  And I see that it's mentioned in the documentation but I'm not sure why the current behaviour is desirable.  Wouldn't it make sense to change the behaviour to work only on subplots with date-axes?

**Comment by phobson** [comment]
> Wouldn't it make sense to change the behaviour to work only on subplots with date-axes?

`autofmt_xdate` is a very simple, convenient function. Determining if an axis is showing dates isn't nearly as straight-forward of a task as it might seem. In my mind, the cost of adding, testing, and maintaining such complexity doesn't outweigh the benefits.

I would be very happy to be wrong about that and review a PR making those changes, though.

**Comment by liamherronyahoo** [comment]
I just ran into this issue and wish it was smart enough to determine which x-axis are of type date and which are not.

Here is my simple test code:

import os
import sys
import math

from datetime import date

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

def generatePricesAndReturns():
   S = 100.0    
   mu = 0.10   # Mean Return
   vol = 0.15  # Volatility
   T = 1.0
   N = 252 
   
   dT = T/float(N)
   
   stdNormalRVs = np.random.normal(0.0, 1.0, N)
   stockReturns = mu*dT + stdNormalRVs * (vol * math.sqrt(dT))
      
   priceList = [S]
   stockPnLs = []
   for r in stockReturns:
      oldPrice = priceList[-1]
      newPrice = oldPrice * math.exp(r*dT)
      pxPnL = newPrice - oldPrice
      priceList.append(newPrice)
      stockPnLs.append(pxPnL)
       
   pyDateList = [date(2017,8,23),date(2017,8,24),date(2017,8,25),date(2017,8,28),date(2017,8,29),date(2017,8,30),date(2017,8,31),date(2017,9,1),date(2017,9,5),date(2017,9,6),date(2017,9,7),date(2017,9,8),date(2017,9,11),date(2017,9,12),date(2017,9,13),date(2017,9,14),date(2017,9,15),date(2017,9,18),date(2017,9,19),date(2017,9,20),date(2017,9,21),date(2017,9,22),date(2017,9,25),date(2017,9,26),date(2017,9,27),date(2017,9,28),date(2017,9,29),date(2017,10,2),date(2017,10,3),date(2017,10,4),date(2017,10,5),date(2017,10,6),date(2017,10,10),date(2017,10,11),date(2017,10,12),date(2017,10,13),date(2017,10,16),date(2017,10,17),date(2017,10,18),date(2017,10,19),date(2017,10,20),date(2017,10,23),date(2017,10,24),date(2017,10,25),date(2017,10,26),date(2017,10,27),date(2017,10,30),date(2017,10,31),date(2017,11,1),date(2017,11,2),date(2017,11,3),date(2017,11,6),date(2017,11,7),date(2017,11,8),date(2017,11,9),date(2017,11,10),date(2017,11,13),date(2017,11,14),date(2017,11,15),date(2017,11,16),date(2017,11,17),date(2017,11,20),date(2017,11,21),date(2017,11,22),date(2017,11,24),date(2017,11,27),date(2017,11,28),date(2017,11,29),date(2017,11,30),date(2017,12,1),date(2017,12,4),date(2017,12,5),date(2017,12,6),date(2017,12,7),date(2017,12,8),date(2017,12,11),date(2017,12,12),date(2017,12,13),date(2017,12,14),date(2017,12,15),date(2017,12,18),date(2017,12,19),date(2017,12,20),date(2017,12,21),date(2017,12,22),date(2017,12,26),date(2017,12,27),date(2017,12,28),date(2017,12,29),date(2018,1,2),date(2018,1,3),date(2018,1,4),date(2018,1,5),date(2018,1,8),date(2018,1,9),date(2018,1,10),date(2018,1,11),date(2018,1,12),date(2018,1,16),date(2018,1,17),date(2018,1,18),date(2018,1,19),date(2018,1,22),date(2018,1,23),date(2018,1,24),date(2018,1,25),date(2018,1,26),date(2018,1,29),date(2018,1,30),date(2018,1,31),date(2018,2,1),date(2018,2,2),date(2018,2,5),date(2018,2,6),date(2018,2,7),date(2018,2,8),date(2018,2,9),date(2018,2,12),date(2018,2,13),date(2018,2,14),date(2018,2,15),date(2018,2,16),date(2018,2,20),date(2018,2,21),date(2018,2,22),date(2018,2,23),date(2018,2,26),date(2018,2,27),date(2018,2,28),date(2018,3,1),date(2018,3,2),date(2018,3,5),date(2018,3,6),date(2018,3,7),date(2018,3,8),date(2018,3,9),date(2018,3,12),date(2018,3,13),date(2018,3,14),date(2018,3,15),date(2018,3,16),date(2018,3,19),date(2018,3,20),date(2018,3,21),date(2018,3,22),date(2018,3,23),date(2018,3,26),date(2018,3,27),date(2018,3,28),date(2018,3,29),date(2018,4,2),date(2018,4,3),date(2018,4,4),date(2018,4,5),date(2018,4,6),date(2018,4,9),date(2018,4,10),date(2018,4,11),date(2018,4,12),date(2018,4,13),date(2018,4,16),date(2018,4,17),date(2018,4,18),date(2018,4,19),date(2018,4,20),date(2018,4,23),date(2018,4,24),date(2018,4,25),date(2018,4,26),date(2018,4,27),date(2018,4,30),date(2018,5,1),date(2018,5,2),date(2018,5,3),date(2018,5,4),date(2018,5,7),date(2018,5,8),date(2018,5,9),date(2018,5,10),date(2018,5,11),date(2018,5,14),date(2018,5,15),date(2018,5,16),date(2018,5,17),date(2018,5,18),date(2018,5,21),date(2018,5,22),date(2018,5,23),date(2018,5,24),date(2018,5,25),date(2018,5,29),date(2018,5,30),date(2018,5,31),date(2018,6,1),date(2018,6,4),date(2018,6,5),date(2018,6,6),date(2018,6,7),date(2018,6,8),date(2018,6,11),date(2018,6,12),date(2018,6,13),date(2018,6,14),date(2018,6,15),date(2018,6,18),date(2018,6,19),date(2018,6,20),date(2018,6,21),date(2018,6,22),date(2018,6,25),date(2018,6,26),date(2018,6,27),date(2018,6,28),date(2018,6,29),date(2018,7,2),date(2018,7,3),date(2018,7,5),date(2018,7,6),date(2018,7,9),date(2018,7,10),date(2018,7,11),date(2018,7,12),date(2018,7,13),date(2018,7,16),date(2018,7,17),date(2018,7,18),date(2018,7,19),date(2018,7,20),date(2018,7,23),date(2018,7,24),date(2018,7,25),date(2018,7,26),date(2018,7,27),date(2018,7,30),date(2018,7,31),date(2018,8,1),date(2018,8,2),date(2018,8,3),date(2018,8,6),date(2018,8,7),date(2018,8,8),date(2018,8,9),date(2018,8,10),date(2018,8,13),date(2018,8,14),date(2018,8,15),date(2018,8,16),date(2018,8,17),date(2018,8,20),date(2018,8,21),date(2018,8,22),date(2018,8,23),date(2018,8,24),]
   
   return (priceList, stockReturns, stockPnLs, pyDateList)
   
   
def run():
   fig = plt.figure(figsize=(10, 10))
   
   gs = gridspec.GridSpec(4, 1, width_ratios=[1,], height_ratios=[2,1,1,1])
   
   (priceList, stockReturns, stockPnLs, pyDateList) = generatePricesAndReturns()
   
   ax0 = plt.subplot(gs[0])
   ax1 = plt.subplot(gs[1])
   ax2 = plt.subplot(gs[2])
   ax3 = plt.subplot(gs[3], sharex=ax0)
   
   ax0.set_title("Stock Price Time Series")
   ax1.set_title("Stock Return Histogram: NO X AXIS TICK VALUES HERE: autofmt_xdate kills them")
   ax2.set_title("Stock PnL Histogram: NO X AXIS TICK VALUES HERE: autofmt_xdate kills them")
   ax3.set_title("Stock Return Time Series")
   
   ax0.plot(pyDateList, priceList, label="Prices")
   
   ax0YtickVals = ax0.get_yticks()
   ax0.set_yticklabels(['{:3.2f}'.format(x) for x in ax0YtickVals])
   
   ax1.hist(stockReturns, bins=100)
   ax2.hist(stockPnLs, bins=80)
   ax3.plot(pyDateList[1:], stockReturns, marker=".", linestyle="None", label="Returns")
   
   fig.autofmt_xdate()
   
   plt.show()
   
   
if __name__ == "__main__":
   run()

**Comment by liamherronyahoo** [comment]
I just ran into this too. I wish that when the "autofmt_xdate()" is called it should iterate over all the charts in the figure and whichever charts don't have an x-axis of type date should continue to use their tick values.

Here is my test script:

`#!/usr/bin/python2.7
#
#
#
import os
import sys
import math

from datetime import date

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

def generatePricesAndReturns():
   S = 100.0    
   mu = 0.10   # Mean Return
   vol = 0.15  # Volatility
   T = 1.0
   N = 252 
   
   dT = T/float(N)
   
   stdNormalRVs = np.random.normal(0.0, 1.0, N)
   stockReturns = mu*dT + stdNormalRVs * (vol * math.sqrt(dT))
      
   priceList = [S]
   stockPnLs = []
   for r in stockReturns:
      oldPrice = priceList[-1]
      newPrice = oldPrice * math.exp(r*dT)
      pxPnL = newPrice - oldPrice
      priceList.append(newPrice)
      stockPnLs.append(pxPnL)
       
   pyDateList = [date(2017,8,23),date(2017,8,24),date(2017,8,25),date(2017,8,28),date(2017,8,29),date(2017,8,30),date(2017,8,31),date(2017,9,1),date(2017,9,5),date(2017,9,6),date(2017,9,7),date(2017,9,8),date(2017,9,11),date(2017,9,12),date(2017,9,13),date(2017,9,14),date(2017,9,15),date(2017,9,18),date(2017,9,19),date(2017,9,20),date(2017,9,21),date(2017,9,22),date(2017,9,25),date(2017,9,26),date(2017,9,27),date(2017,9,28),date(2017,9,29),date(2017,10,2),date(2017,10,3),date(2017,10,4),date(2017,10,5),date(2017,10,6),date(2017,10,10),date(2017,10,11),date(2017,10,12),date(2017,10,13),date(2017,10,16),date(2017,10,17),date(2017,10,18),date(2017,10,19),date(2017,10,20),date(2017,10,23),date(2017,10,24),date(2017,10,25),date(2017,10,26),date(2017,10,27),date(2017,10,30),date(2017,10,31),date(2017,11,1),date(2017,11,2),date(2017,11,3),date(2017,11,6),date(2017,11,7),date(2017,11,8),date(2017,11,9),date(2017,11,10),date(2017,11,13),date(2017,11,14),date(2017,11,15),date(2017,11,16),date(2017,11,17),date(2017,11,20),date(2017,11,21),date(2017,11,22),date(2017,11,24),date(2017,11,27),date(2017,11,28),date(2017,11,29),date(2017,11,30),date(2017,12,1),date(2017,12,4),date(2017,12,5),date(2017,12,6),date(2017,12,7),date(2017,12,8),date(2017,12,11),date(2017,12,12),date(2017,12,13),date(2017,12,14),date(2017,12,15),date(2017,12,18),date(2017,12,19),date(2017,12,20),date(2017,12,21),date(2017,12,22),date(2017,12,26),date(2017,12,27),date(2017,12,28),date(2017,12,29),date(2018,1,2),date(2018,1,3),date(2018,1,4),date(2018,1,5),date(2018,1,8),date(2018,1,9),date(2018,1,10),date(2018,1,11),date(2018,1,12),date(2018,1,16),date(2018,1,17),date(2018,1,18),date(2018,1,19),date(2018,1,22),date(2018,1,23),date(2018,1,24),date(2018,1,25),date(2018,1,26),date(2018,1,29),date(2018,1,30),date(2018,1,31),date(2018,2,1),date(2018,2,2),date(2018,2,5),date(2018,2,6),date(2018,2,7),date(2018,2,8),date(2018,2,9),date(2018,2,12),date(2018,2,13),date(2018,2,14),date(2018,2,15),date(2018,2,16),date(2018,2,20),date(2018,2,21),date(2018,2,22),date(2018,2,23),date(2018,2,26),date(2018,2,27),date(2018,2,28),date(2018,3,1),date(2018,3,2),date(2018,3,5),date(2018,3,6),date(2018,3,7),date(2018,3,8),date(2018,3,9),date(2018,3,12),date(2018,3,13),date(2018,3,14),date(2018,3,15),date(2018,3,16),date(2018,3,19),date(2018,3,20),date(2018,3,21),date(2018,3,22),date(2018,3,23),date(2018,3,26),date(2018,3,27),date(2018,3,28),date(2018,3,29),date(2018,4,2),date(2018,4,3),date(2018,4,4),date(2018,4,5),date(2018,4,6),date(2018,4,9),date(2018,4,10),date(2018,4,11),date(2018,4,12),date(2018,4,13),date(2018,4,16),date(2018,4,17),date(2018,4,18),date(2018,4,19),date(2018,4,20),date(2018,4,23),date(2018,4,24),date(2018,4,25),date(2018,4,26),date(2018,4,27),date(2018,4,30),date(2018,5,1),date(2018,5,2),date(2018,5,3),date(2018,5,4),date(2018,5,7),date(2018,5,8),date(2018,5,9),date(2018,5,10),date(2018,5,11),date(2018,5,14),date(2018,5,15),date(2018,5,16),date(2018,5,17),date(2018,5,18),date(2018,5,21),date(2018,5,22),date(2018,5,23),date(2018,5,24),date(2018,5,25),date(2018,5,29),date(2018,5,30),date(2018,5,31),date(2018,6,1),date(2018,6,4),date(2018,6,5),date(2018,6,6),date(2018,6,7),date(2018,6,8),date(2018,6,11),date(2018,6,12),date(2018,6,13),date(2018,6,14),date(2018,6,15),date(2018,6,18),date(2018,6,19),date(2018,6,20),date(2018,6,21),date(2018,6,22),date(2018,6,25),date(2018,6,26),date(2018,6,27),date(2018,6,28),date(2018,6,29),date(2018,7,2),date(2018,7,3),date(2018,7,5),date(2018,7,6),date(2018,7,9),date(2018,7,10),date(2018,7,11),date(2018,7,12),date(2018,7,13),date(2018,7,16),date(2018,7,17),date(2018,7,18),date(2018,7,19),date(2018,7,20),date(2018,7,23),date(2018,7,24),date(2018,7,25),date(2018,7,26),date(2018,7,27),date(2018,7,30),date(2018,7,31),date(2018,8,1),date(2018,8,2),date(2018,8,3),date(2018,8,6),date(2018,8,7),date(2018,8,8),date(2018,8,9),date(2018,8,10),date(2018,8,13),date(2018,8,14),date(2018,8,15),date(2018,8,16),date(2018,8,17),date(2018,8,20),date(2018,8,21),date(2018,8,22),date(2018,8,23),date(2018,8,24),]
   
   return (priceList, stockReturns, stockPnLs, pyDateList)
   
   
def run():
   fig = plt.figure(figsize=(10, 10))
   
   gs = gridspec.GridSpec(4, 1, width_ratios=[1,], height_ratios=[2,1,1,1])
   
   (priceList, stockReturns, stockPnLs, pyDateList) = generatePricesAndReturns()
   
   ax0 = plt.subplot(gs[0])
   ax1 = plt.subplot(gs[1])
   ax2 = plt.subplot(gs[2])
   ax3 = plt.subplot(gs[3], sharex=ax0)
   
   ax0.set_title("Stock Price Time Series")
   ax1.set_title("Stock Return Histogram: NO X AXIS TICK VALUES HERE: autofmt_xdate kills them")
   ax2.set_title("Stock PnL Histogram: NO X AXIS TICK VALUES HERE: autofmt_xdate kills them")
   ax3.set_title("Stock Return Time Series")
   
   ax0.plot(pyDateList, priceList, label="Prices")
   
   ax0YtickVals = ax0.get_yticks()
   ax0.set_yticklabels(['{:3.2f}'.format(x) for x in ax0YtickVals])
   
   ax1.hist(stockReturns, bins=100)
   ax2.hist(stockPnLs, bins=80)
   ax3.plot(pyDateList[1:], stockReturns, marker=".", linestyle="None", label="Returns")
   
   fig.autofmt_xdate()
   
   plt.show()
   
   
if __name__ == "__main__":
   run()`

**Comment by ninabel** [comment]
I have this problem too. I need 2 charts, one by month, second by weeks. And when using fig.autofmt_xdate() 
xticks of top chart disappiared.

**Comment by phobson** [comment]
@ninabel  I recommend that you not use `fig.autofmt_xdate` and create your own formatters and locators like in this example: https://matplotlib.org/gallery/api/date.html#sphx-glr-gallery-api-date-py

**Comment by ninabel** [comment]
But this example DO use fig.autofmt_xdate() after all.

**Comment by phobson** [comment]
I understand that and I'm suggesting that you don't.

**Comment by ninabel** [comment]
Without fig.autofmt_xdate() - xlabels on both grafic.
![image](https://user-images.githubusercontent.com/12895739/38441373-28643f0a-39ed-11e8-8951-938cacec6adb.png)

With fig.autofmt_xdate() - xlabels on top grafic lost. It's not good.
![image](https://user-images.githubusercontent.com/12895739/38441338-0ff55b7a-39ed-11e8-83c1-1086847b7e31.png)

**Comment by phobson** [comment]
is there a problem with the top figure?

**Comment by jklymak** [comment]
I'm closing this as `autofmt_xdate` is doing what it says it will.  I personally think `autofmt_xdate` is fine as a work around, but I would not support extending its functionality, and would actually be in favour of deprecation...
