### ISSUE TITLE
Can't plot with empty markers

### ISSUE THREAD

**Issue by naught101** [matplotlib/matplotlib#8514]
### Bug report

Why trying to plot with empty markers, markers are not plotted at all. Example:

```python
plot([1,2,3,4,5], [1, 1.5, 3, 4.2, 5], 'ks-',color='black', markerfacecolor='none', markeredgecolor='black')
# Out[22]: [<matplotlib.lines.Line2D at 0x7f3db3c11ac8>]
savefig('/tmp/figure1.png')
```

Should produce a plot with a black line, with empty squares ar each of the 5 points, but instead it produces this:

![figure1](https://cloud.githubusercontent.com/assets/167164/25209928/0921e750-25c1-11e7-9585-0bee093c8976.png)

I'm not sure if I've tried this before, but I think it works for others, so it could be a specific version problem, I guess.

Running on KDE Neon/ubuntu xenial, with python/MPL from conda:

```
# packages in environment at /home/naught101/miniconda3/envs/science:
libpng                    1.6.27                        0  
matplotlib                2.0.0               np111py36_0  
pyqt                      5.6.0                    py36_2  
python                    3.6.1                         0  
```

**Comment by phobson** [comment]
Had you imported seaborn before making that figure?

**Comment by tacaswell** [comment]
The issue is likely that `markeredgewidth` is 0.

There is some subtle logic around this.

**Comment by phobson** [comment]
I can only reproduce this with the example code provided if I import seaborn first.

**Comment by naught101** [comment]
Yep, it's the seaborn, and the markeredgewidth parameter fixes it.

I guess closing this and linking to https://github.com/matplotlib/matplotlib/issues/4679 is probably fix enough.
