### ISSUE TITLE
clabel throws runtime error for circular-like contours

### ISSUE THREAD

**Issue by mbakker7** [matplotlib/matplotlib#8529]
The following code produces a Runtime Warning thrown by `clabel`. I think it has to do with the circular-like contours. I often produce contours that look like this and keep getting this Runtime Warning, and I narrowed it down to this example. Is there anything we can fix in `clabel`? matplotlib version 2.0.0

```
import numpy as np
import matplotlib.pyplot as plt

x, y = np.meshgrid(np.linspace(-2, 2, 4), np.linspace(-2, 2, 4))
r = np.sqrt(x ** 2 + y ** 2)
plt.figure()
cs = plt.contour(x, y, r)
plt.clabel(cs)
```

**Comment by dstansby** [comment]
I can confirm this on `master`, with the following warning:

```python
>>> plt.clabel(cs)
/Users/dstansby/matplotlib/lib/matplotlib/contour.py:359: RuntimeWarning: invalid value encountered in true_divide
  dist = np.add.reduce(([(abs(s)[i] / L[i]) for i in range(xsize)]), -1)
<a list of 13 text.Text objects>
```

**Comment by dstansby** [comment]
(just edited the original post to put imports in the code snipped so it's easier to copy/paste, am going to have a look at fixing this now)
