### ISSUE TITLE
Feature Request: draw percentiles in violinplot

### ISSUE THREAD

**Issue by tino-michael** [matplotlib/matplotlib#8532]
At the moment violineplot allows to draw the median and the mean into the violin.
Would it be possible to add as an argument e.g. a list for percentiles to be drawn into the violin as well?

**Comment by phobson** [comment]
Hey @tino-michael 

This is definitely possible, it's a matter of finding someone with time to implement, test, and document it. I'd be happy to review a PR if you can take this on.

In the meantime, I'm tempted to simply kick this over to [seaborn](http://seaborn.pydata.org/generated/seaborn.violinplot.html#seaborn.violinplot), which already handles this case nicely

**Comment by tino-michael** [comment]
As far as I can see, seaborn also "only" allows to print the quartiles but not user-defined percentiles (some colleagues insist to see the "1sigma" -- i.e. 68th percentile -- point in the distributions).

I will try to find some time (you are right on that regard) to dig into it. I just thought that it would be quickly enough to implement for somebody that is already familiar with the code -- which I am not.

**Comment by Dylan-Dotti** [comment]
Hello, 
     What color should the percentile lines be? And what size in comparison to the mean/median lines?
