### ISSUE TITLE
"divide by zero" warning doing a proportional colorbar with only 3 bounds

### ISSUE THREAD

**Issue by rvilla87** [matplotlib/matplotlib#8534]
### Bug report

**Bug summary**
When trying to show a proportional colorbar with only 3 bounds I get a ```"division by zero"``` warning. **I don't get the warning if I put 4 bounds**, like that: ```bounds = [0, 3, 5, 7]```.

The thing is, I need a bar that shows me, for example, that having 5 animals, 3 of them are dogs. Am I using correctly the mpl.colorbar function? Here's the code:

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import matplotlib as mpl
fig = plt.figure(figsize=(3, 2))
ax1 = fig.add_axes([0.1, 0.5, 0.8, 0.2])
cmap = mpl.colors.ListedColormap(['green', 'red'])
bounds = [0, 3, 5]
cb2 = mpl.colorbar.ColorbarBase(ax1, cmap=cmap, boundaries=bounds,
                                spacing='proportional', orientation='horizontal')
cb2.set_label('3 of 5')
plt.show()
```

**Actual outcome**
```
C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\colorbar.py:810: RuntimeWarning: divide by zero encountered in double_scalars
  automin = (y[2] - y[1]) / clen
C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\colorbar.py:811: RuntimeWarning: divide by zero encountered in double_scalars
  automax = (y[-2] - y[-3]) / clen
```

**Expected outcome**
No warning output, I think the code is correct.

**Matplotlib version**
  * Operating System: Windows 10
  * Matplotlib Version: 2.0.0 np112py36_0
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): 5.0.0

Python and Matplotlib installed from conda, default channel.

Thanks in advance!

**Comment by efiring** [comment]
I agree that it is a bug: the failure is in a calculation that only needs to be done when the colorbar will have one or more extensions.  

As a workaround, try calling it like this:
```python
from matplotlib.colors import BoundaryNorm
norm = BoundaryNorm(boundaries=bounds)
cb2 = mpl.colorbar.ColorbarBase(ax1, cmap=cmap, norm=norm,
                                spacing='proportional', orientation='horizontal')
```
I think that this use of BoundaryNorm is what you will want anyway, to get the desired result.  It is designed for this sort of thing--working with ListedColormap with a small number of colors.

**Comment by rvilla87** [comment]
Thanks for the answer.

The workaround needs the ```ncolors=2``` parameter in ```BoundaryNorm``` function, right? I get a error if I don't put it.

Anyway the workarround gives me the same warning, here's the code with the workaround:

```python
from matplotlib.colors import BoundaryNorm
import matplotlib.pyplot as plt
import matplotlib as mpl
fig = plt.figure(figsize=(3, 2))
ax1 = fig.add_axes([0.1, 0.5, 0.8, 0.2])
cmap = mpl.colors.ListedColormap(['green', 'red'])
bounds = [0, 3, 5]
norm = BoundaryNorm(boundaries=bounds, ncolors=2)
cb2 = mpl.colorbar.ColorbarBase(ax1, cmap=cmap, norm=norm,
                                spacing='proportional',
                                orientation='horizontal')
cb2.set_label('3 of 5')
plt.show()
```

**Comment by efiring** [comment]
To be sure I understand: If you ignore the warning, the plot is correct, right?  It looks right to me.

**Comment by rvilla87** [comment]
Sorry, no, there are another bug (I think).

With your workaround it works perfectly but with my initial code there is a visual error. You will see that using ```bounds = [0, x, 5]``` where x in 1-4 you can see the green color filling the bar, but with 5 value it's showing the bar completedly red (instead of green). 

So, as I say, with ```bounds = [0, 5, 5]```  you can see:
- With your workaround (fully green color) --> Correct
![2017-04-28 18_51_24-figure 1](https://cloud.githubusercontent.com/assets/26299708/25538614/bab15c2a-2c43-11e7-9de4-58562d3d1c7b.png)

- With my initial code (fully red color) --> Not ok
![2017-04-28 18_52_11-figure 1](https://cloud.githubusercontent.com/assets/26299708/25538647/d22fc5f8-2c43-11e7-8b99-bdfc37949d14.png)


And another problem, and I'm not sure if it's a bug, is that with ```bounds = [0, 0, 5]``` with both of the codes (my initial and your workaround) it gives this error instead of showing an empty bar:
```
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\text.py", line 762, in draw
    raise ValueError("posx and posy should be finite values")
ValueError: posx and posy should be finite values
```

Should I open another issue explaining the bug or this problem I've just said?

Thanks

**Comment by efiring** [comment]
No need for another issue.  Please use BoundaryNorm; it really is the right way to handle discrete color mapping like this.  Do you have a use case for setting bounds to the same number?  And are you taking into account that except for the right-most, the boundaries are defined such that the left bound is inclusive and the right bound is exclusive?

**Comment by rvilla87** [comment]
Ok, I will use BoundaryNorm.
In order to show a graphic saying "_0 of 5_" I thought I should be put ```[0, 0, 5]``` bounds, but as you say if left bound is inclusive then I cannot do it this way, right? I'm not sure if I understand you.

How can I see a bar showing me 0 of 5? I can do it setting the bounds ```[0, 0.0001, 5]```. Is this the proper way of implementing this function? At least the graphic is ok for me:
![2017-04-28 20_05_06-figure 1](https://cloud.githubusercontent.com/assets/26299708/25541183/07546cfc-2c4e-11e7-8a11-39859a0df2c6.png)

**Comment by efiring** [comment]
It looks like that is indeed a reasonable way to do it.  I don't know of a better way.
