### ISSUE TITLE
Generate a `tutorials` sphinx gallery

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8541]
Per some recent conversations on gitter and otherwise, I think the user guide could be updated / modernized, and also auto-generated with sphinx-gallery. It's now a lot easier to draft more narrative, blog-post-style content on the website which is much better for conveying information.

My take on this is that we should do 3 things:

1. Extract the part of the user guide with the most useful, actionable stuff for the average MPL user and spin them off into a "tutorials" section. 
    * (e.g., the annotation tutorial is super useful for many people and should be easier to discover as are many of the user guide "tutorials" but they are currently buried like 3 levels deep in the docs)
1. Find other sections of the docs to consolidate into a single place (e.g. some in the tutorials or some in the user guide)
    * (e.g., there is a "how to" section in a whole different part of the docs but it's unclear to me why this should be in a different place than the "user guide" or "tutorials". There's also the really useful [Usage page](http://matplotlib.org/faq/usage_faq.html) with an awesome figure on it that should be much more prominent on the website).
1.  Add this "tutorials" section to the navbar on the main page.

The point here is that the Matplotlib docs have an *amazing* repository of learning material. But they've also got a huge signal-to-noise problem. I am all for covering many different usecases in the documentation, but there should be only one or two places that people know to look for a piece of information. Moreover, for users who just want to be told the "right" way to do things (my guess this is most users), there should be one clear place for them to look.

What do people think about something like this? Doesn't have to all be done at once, but piece by piece in a slow migration. Thoughts?

Pinging the usual suspects ;-)

@NelleV @anntzer @story645 @QuLogic @dopplershift @phobson @tacaswell

**Comment by dopplershift** [comment]
👍 The separate tutorials section for longer form narratives makes sense to me; I've done that on one of my own projects.

**Comment by story645** [comment]
I'm 👍 
I've been wanting a simple gallery of sorts that goes over the basic plot types - line, scatter, bar, pie, heatmap - in like 5 lines or less w/ nothing fancy and I think that'd be perfect for a tutorial type section.

**Comment by choldgraf** [comment]
Closing this since the tutorials are now here:

http://matplotlib.org/devdocs/tutorials/index.html
