### ISSUE TITLE
Allow scalar `weights` parameter to `hist` method

### ISSUE THREAD

**Issue by lzkelley** [matplotlib/matplotlib#8547]
Currently the [`Axes.hist` function requires the `weights` argument to match the shape of the input array](https://github.com/matplotlib/matplotlib/blob/81495363d283809021b5ae4fc87bbd5edbbb3f6c/lib/matplotlib/axes/_axes.py#L6059-L6070) so that each weight can be applied to each value being histogrammed.  It would be nice, however, if a single scalar could also be accepted which would rescale all elements of the input array* in effect to change the units of the y-axis.  For example, I'm currently plotting a histogram of galaxy masses in a finite volume, and I'd like to plot the number-density of galaxies instead of the total number --- and thus would like to divide each mass (or each histogram value) by the total space volume.

Edit: Alternatively, a new parameter could be added to the function which would have the same effect, e.g. `hist(..., rescale=None)`

\* The best way to do this would likely be to check if the weights are a scalar, and if so, apply the weight to the results array instead of the input array for efficiency.

**Comment by anntzer** [comment]
Probably related to #7562.

**Comment by eric-wieser** [comment]
Could this be a numpy feature request too?

**Comment by jklymak** [comment]
Umm, I don't get this.   Why not simply call `np.histogram(a/rescale)`?

**Comment by lzkelley** [comment]
@jklymak in my case, that is what I end up doing; but because the weighting parameters are determined dynamically (based on numerous factors, and resulting in either a value-wise weight, or a uniform-weight) it would be much easier to use the weight parameter instead of both a weight parameter and a `a/rescale` parameter.

**Comment by jklymak** [comment]
But you can still do both...  `ax.hist(a/rescale, weights=dynamicweights)`.  Anyway, as @eric-wieser says, this is probably a numpy request as we don't calculate the histogram at the Matplotlib level (any more) and we'd like to keep the call signatures relatively parallel.

**Comment by efiring** [comment]
I'm closing this based on the comment above.  Certainly, if numpy is changed to support a scaler
weight, we would welcome a PR to do the same.
Side note: our `hist` has more complicated argument handling than `numpy.histogram` because the latter handles a single dataset at a time, while we handle single or multiple datasets in a single function call.

**Comment by henryiii** [comment]
Has someone made a Numpy request? It's at least not linked here.

Unfortunately, one of the uses for this involves the MatPlotLib only list of data sources: Let's say you have twice as many samples in b as in a. Then if you do: `plt.hist([a,b])`,  `b` will be 2x too large. `weighs=[2,1]` or `weights=[1,.5]`, would fix this, but that probably would be tricky to separate from the currently supported syntax. I don't think you can even do this with the current workaround `weights=np.ones_like(a)*weight`.

And, I don't get `np.histogram(a/rescale)`, that a) works with non-scalar values too, and b) does not scale the resulting histogram values - it just moves all the values around into different histogram bins. Weights cause values to be counted as more than or less than 1, not where they are counted.
