### ISSUE TITLE
small-caps doesn't seem to work

### ISSUE THREAD

**Issue by geib7592** [matplotlib/matplotlib#8552]
I noticed that even in the [demo](https://matplotlib.org/examples/pylab_examples/fonts_demo.html), the small-caps feature is not working. I tried switching fonts to STIXGeneral, and setting `variant='small-caps'` still had no effect.

**Comment by coderforlife** [comment]
This is still true.

**Comment by jklymak** [comment]
Yes - recent version of docs: https://matplotlib.org/stable/gallery/text_labels_and_annotations/fonts_demo.html#sphx-glr-gallery-text-labels-and-annotations-fonts-demo-py

**Comment by anntzer** [comment]
This will basically not work (AFAICT) until we switch to using harfbuzz for font shaping (https://github.com/matplotlib/matplotlib/pull/14912).  (Currently the way we detect small-caps fonts is just if their name is *exactly* (case-insensitively) either "capitals" or "small-caps", which of course fails to catch any relevant small caps font -- but it's not as if any simple regex on the font name would really be sufficient, see e.g. https://www.fontsc.com/font/tag/small-caps, https://www.fontsquirrel.com/fonts/list/tag/small%20caps.)

Given that it seems unlikely we'll switch to harfbuzz any time soon (well, it depends on whether someone picks up https://github.com/matplotlib/matplotlib/pull/14912), I think we should simply just document "variant: small-caps" as unsupported and emit a warning when the user requests that.

**Comment by jklymak** [comment]
It seems regenerating the images is the only hold up for harfbuzz?

**Comment by anntzer** [comment]
Actually there's a bit more, e.g. figuring out whether we need static linking (especially the situation on non-linux), fixing a version, and all that stuff...

**Comment by jklymak** [comment]
Where are we tracking g the image comparison issue?  I think we should just go low tech and have two repositories and let folks who want smaller downloads just limit the depth they pull off GitHub.

**Comment by anntzer** [comment]
https://github.com/matplotlib/matplotlib/issues/16447

**Comment by AWildridge** [comment]
Are there any workarounds to get small caps fonts in text in matplotlib? Perhaps getting some LaTeX installation or something working with matplotlib? I would like to be able to use small caps as it is used a lot in high energy physics and our legends need to properly reflect the exact font formatting.

**Comment by oscargus** [comment]
@AWildridge it should work if you use `usetex=True` as that will use standard LaTeX to generate the text, see https://matplotlib.org/stable/users/explain/text/usetex.html

(The problem here is primarily that our internal mathtext engine cannot handle it, but with the correct preamble etc, anything that can be done in LaTeX can be done in Matplotlib.)

**Comment by QuLogic** [comment]
@dstansby pointed out that this didn't work in https://github.com/matplotlib/cheatsheets/pull/183#issuecomment-4160844111 Unfortunately, I had not noticed this property or I might have tried to do something with it in the font overhaul.

That being said, it should be possible to get small caps working in 3.11 by passing the right font features  (small caps is the `smcp` feature): https://github.com/matplotlib/cheatsheets/pull/183#issuecomment-4196868171

I do think that the font feature tag names are a bit unergonomic, so I wonder if we want to implement [all the CSS options for `font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/font-variant) (or at least the ones we are capable of providing.)
