### ISSUE TITLE
Add images of markers to the list of markers

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#8556]
Currently http://matplotlib.org/devdocs/api/markers_api.html#module-matplotlib.markers just has marker codes and a description of the marker; it would be nice to have a picture of what each marker looks like as a 3rd column.

**Comment by WeatherGod** [comment]
Here is the example where I built the table from:
http://matplotlib.org/devdocs/gallery/lines_bars_and_markers/marker_reference.html#sphx-glr-gallery-lines-bars-and-markers-marker-reference-py

**Comment by anntzer** [comment]
It's the second bullet point in https://github.com/matplotlib/matplotlib/issues/7342 (which has a few more related items).

**Comment by choldgraf** [comment]
that might be a good topic to be converted into a more in-depth tutorial (maybe on extending a basic plot or something?)

**Comment by choldgraf** [comment]
another thing you could do for this API page is to include a link to the thumbnail of the example @WeatherGod links to above. You could add this in the README file so that the thumbnail shows up above the API list. E.g., with a `.. figure::` directive

**Comment by dstansby** [comment]
Thanks a lot @ImportanceOfBeingErnest !
