### ISSUE TITLE
Rendering really large image

### ISSUE THREAD

**Issue by sandeep-gh** [matplotlib/matplotlib#8558]
### Bug report
Running  python/matplotlib/basemap on 3TB memory machine to create a large 400x240 inch image with 80 dpi. 
This ends in segmentation fault. If memory and time permits, shouldn't matplotlib be able to handle it?

**Bug summary**
Segfault on rendering large image

**Code for reproduction**

```python

import matplotlib
matplotlib.use('Agg') # Must be before importing matplotlib.pyplot or pylab!
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt


plt.figure(figsize=(400,240))
map = Basemap(llcrnrlon=-119,llcrnrlat=22,urcrnrlon=-64,urcrnrlat=49,
              projection='lcc',lat_1=33,lat_2=45,lon_0=-95, resolution='l') #l for low resolution
map.drawcoastlines()
map.drawcountries()
plt.savefig("us_map.png",dpi=80)


```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
  warnings.warn("tight_layout : falling back to Agg renderer")
[1]    9040 segmentation fault  ipython

```

**Expected outcome**

**Matplotlib version**

  * Operating System: linux 
  * Matplotlib Version: 1.5.3
  * Python Version: 2.7
  * Jupyter Version (if applicable):
  * Other Libraries: Basemap

Installed using easybuild, i.e., compiled from source

**Comment by efiring** [comment]
What backend are you using?  What output file format are you writing?  Have you tried putting everything in a script file and running from the command line instead of from ipython?

**Comment by sandeep-gh** [comment]
I have the code for reproduction. I am the Agg backend. I tried from python as well. I still get the segmentation fault.

**Comment by WeatherGod** [comment]
Could you use the faulthandler package to help see where the segfault is
coming from?
https://pypi.python.org/pypi/faulthandler/

**Comment by efiring** [comment]
This can be reproduced with a much simpler script:
```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(400, 240), dpi=80)
fig.savefig('big.png')
```

**Comment by efiring** [comment]
Furthermore, the dpi threshold for the segfault in the example above is 75; with 74 or less, it runs. I have also verified that it is a matter of the total number of pixels, not the width or the height.  The threshold is around 6.8 MegaPixels, so it doesn't obviously correspond to an integer overflow boundary.

**Comment by efiring** [comment]
From faulthandler (included in python 3 standard library):
```
(test) efiring@manini2:~/temp$ python -X faulthandler bigfile.py
Fatal Python error: Segmentation fault

Current thread 0x00007fffa80df3c0 (most recent call first):
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backends/backend_agg.py", line 93 in __init__
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backends/backend_agg.py", line 476 in get_renderer
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backends/backend_agg.py", line 459 in draw
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backends/backend_agg.py", line 545 in print_png
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/backend_bases.py", line 2252 in print_figure
  File "/Users/efiring/work/programs/py/mpl/matplotlib/lib/matplotlib/figure.py", line 1573 in savefig
  File "bigfile.py", line 10 in <module>
Segmentation fault: 11
```

**Comment by QuLogic** [comment]
(400*240 inches @ 80 dpi = 32000*19200 pixels = 614400000 pixels) * 4 bytes for RGBA = 2457600000 bytes ~ 2.28 GiB > 2^31. Usually an `unsigned int` is used for dimensions/indices, but _maybe_ somewhere uses a signed int that throws this off. I haven't figured out where this might be though.

**Comment by QuLogic** [comment]
PS, (400\*240 @ 74 dpi = 29600\*17760 pixels = 525696000 pixels) ~ 525 megapixels, not 6.8.

**Comment by efiring** [comment]
Oops!  Yes, a stupid mistake on my part.  And I'm not really surprised that an integer overflow is occurring; it's so easy to use an int rather than carefully specifying "unsigned" everywhere that it might be appropriate.

I suspect that what we should do is simply trap the > 2^31 case and raise an exception.  Even if the offending int were located and changed to unsigned, there would still be a need to be a trap for excessive size.

**Comment by tacaswell** [comment]
There was one of these that we fixed for 2.0 that changes a segfault -> exception (84f3a6f149d2cae74f2e8b5b190205dff7a0388c)  I suspect that this is related and we just need a check on the total number of pixels as well.

It might work if you save it as an svg or pdf?

**Comment by QuLogic** [comment]
A suggestion from #5191 is to generate a PDF or SVG and then convert that to PNG. If I use the PDF backend, I can create the output (that is viewable in evince) and use `convert -density 80 us_map.pdf us_map.png` to produce a PNG that is the right size. Unfortunately, I haven't found an image viewer that works properly so I don't know if it's correct.

**Comment by tacaswell** [comment]
Oh, I found the issue:

https://github.com/matplotlib/matplotlib/blob/master/src/_backend_agg.cpp#L55 (which is the root of the trace @efiring posted) computes the stride as an unsigned int as `w * 4` however this gets passed into 
https://github.com/matplotlib/matplotlib/blob/master/extern/agg24-svn/include/agg_rendering_buffer.h#L57 which expects the stride as an int (and has handling for if it is negative) so I suspect that (or one of the other attach calls) is wrapping around and causing the segfault when computing where the edge of the array should be.

I suspect the check needs to be that `width * 4` fits in a normal int.

**Comment by QuLogic** [comment]
That's only 128000; it should not be large enough to matter.

**Comment by tacaswell** [comment]
Right, `int` is 32 bit.  Trying to sort out where the 16 bit limit comes from, but not making huge headway...

**Comment by efiring** [comment]
I don't think there is a 16-bit limit; the problem found by the OP is with the total number of pixels, not with any one dimension.

**Comment by sandeep-gh** [comment]
@QuLogic : Using PDF backend and generating pdf images and using convert program to convert to png works. The feh image viewer works nicely for 400x240 inch images.

**Comment by QuLogic** [comment]
I found the problem [here](https://github.com/matplotlib/matplotlib/blob/master/extern/agg24-svn/include/agg_rendering_buffer.h#L81). When `y=16777`, it works, but when `y=16778`, then `y*m_stride` = 16778*128000 = 2147584000 _but_ since both `y` and `m_stride` are signed ints, this is interpreted as a negative number -2147383296 so it ends up way before the start of the buffer.

I think the individual dimensions are limited to 2**16 which when multiplied shouldn't overflow, but since stride is (up to) 4 times a single dimension, any multiplication like this needs to be upcasted to 64-bit.
