### ISSUE TITLE
Convert colorbar_only to tutorial

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#8561]
The [colorbar_only](http://matplotlib.org/examples/api/colorbar_only.html) example is a fairly intricate exploration of what can be done with a colorbar. Based on @phobson's (great) recommendation that more involved examples should be tutorials, colorbar_only.py should be converted to a tutorial on colorbars-and possible expanded-and placed in the [colors](http://matplotlib.org/devdocs/tutorials/index.html#colors) section of the tutorials. 

cc: @choldgraf , @phobson

**Comment by dstansby** [comment]
Fixed by #8600
