### ISSUE TITLE
Find examples to convert to tutorials

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8564]
@story645 and @phobson brought up good points that many examples have enough content / topics to really be more in-depth tutorials. I think it's a great idea. What if we use this issue to identify groups of examples that fit this description, and we can open PRs later to improve them.

- [x] colorbars (https://github.com/matplotlib/matplotlib/issues/8561)
- [x] annotations (https://github.com/matplotlib/matplotlib/pull/8266)
...

**Comment by story645** [comment]
Also the [style tutorial](http://predictablynoisy.com/matplotlib/tutorials/01_introductory/customizing.html#sphx-glr-tutorials-01-introductory-customizing-py) should likely be updated with the new context manager notation:
