### ISSUE TITLE
Superimposed markers when scatterpoints=1

### ISSUE THREAD

**Issue by silvioricardoc** [matplotlib/matplotlib#8569]
### Bug report

**Bug summary**

Savefig does not generate legends with a single marker when _scatterpoints=1_ and the output file format is PDF/EPS/SVG. (A similar problem also happens when  _scatterpoints=2_).

**Code for reproduction**

```python
from matplotlib import pyplot as plt
plt.scatter([1,2,3], [2,4,7], [10,20,70], facecolor="none", edgecolor="y", label="Foobar")
plt.legend(scatterpoints=1)
plt.savefig("output.png")  # this works perfectly
plt.savefig("output.pdf")  # this does not
plt.savefig("output.eps")  # this does not
plt.savefig("output.svg")  # this does not
```

**Expected outcome**

The output images should all be be similar, with a legend that only shows a single marker (since _scatterpoints=1_).

**Actual outcome**

The output PNG file looks perfect, just like with ``plt.show()``. The PDF/EPS/SVG files have 3 superimposed markers inside the legend.

**Matplotlib version**

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 1.5.1
  * Python Version: 3.5.2
  * Jupyter Version (if applicable): None.
  * Other Libraries: None.

**Comment by jenshnielsen** [comment]
I cannot reproduce this with Matplotlib 2.0.1 Can you if possible please test with a later version 1.5.1 is rather old by now.

**Comment by silvioricardoc** [comment]
Works fine in 2.0.1. Thanks.
