### ISSUE TITLE
mplot3D scalar arguments for plot function

### ISSUE THREAD

**Issue by godaygo** [matplotlib/matplotlib#8577]
Hi, `ax.plot` in 2D case allows to use scalar arguments for `x` and `y`, so `ax.plot( 1, 1, ls='', marker='o')` is valid code. But in 3D case it does not and assumes that arguments are always  **array-like**. I know this is a rare case, but it looks like inconsistent for `plot` function.

**Comment by WeatherGod** [comment]
personally, I would call that a bug in plot(). Probably came about by
accident during the work to add support for the data kwarg.

**Comment by anntzer** [comment]
Actually, passing scalars has worked at least as far back as mpl1.5 (pre-data-kwarg).
