### ISSUE TITLE
update errorbar in Matplotlib 2.0.0

### ISSUE THREAD

**Issue by mromanie** [matplotlib/matplotlib#8586]
I want to update matplotlib errorbar plotting as some input data varies. The code at:

https://github.com/matplotlib/matplotlib/issues/4556

doesn't seem to work with matplotlib 2.0.0 (works fine with version 1.5.2rc2). Hints? Thanks!!

**Code for reproduction**

For example:

```python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
x = np.linspace(0, 2*np.pi, 15)
y = np.sin(x)
y_err = np.cos(x) * 0.1
err = ax.errorbar(x, y, y_err)
ln, (err_top, err_bot), (bars, ) = err
```

**Actual outcome**

returns the following erro:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: need more than 0 values to unpack
```

It used to work on 1.5.2rc2 and python 2.7.12.

**Matplotlib version**

  * Operating System: Mac OS X 10.11.6
  * Matplotlib Version: 2.0.0
  * Python Version: 2.7.13
  * Jupyter Version (if applicable):
  * Other Libraries: 

Both python and matplotlib installed from MacPorts.

**Comment by tacaswell** [comment]
This is due to a change in the default behavior of errorbarr (https://matplotlib.org/users/dflt_style_changes.html#errorbar) where we no longer draw the caps by default.  This results in `err[1]` being an empty tuple rather than a length 2 tuple which is an API change we failed to document.

**Comment by mromanie** [comment]
Thanks!! Reverting to the matplotlib 1.5 behaviour with mpl.rcParams['errorbar.capsize'] = 3 works fine.

Apologies in advance for the trivial question, but, if one does not do that and, thus, err[1] is empty, where are the errors stored?

**Comment by tacaswell** [comment]
The third artist (the vertical lines) have the errors.

Closed by #8588

**Comment by mromanie** [comment]
Very last question. How does one access the third artist (the vertical lines) in a convenient way?Sometinh like err[2][0].get_segments() works, but is a bit cumbersome. In other words, what is the equivalent of

ln, (err_top, err_bot), (bars, ) = err

in matplotlib 2.0 if one does not set plt.rcParams['errorbar.capsize'] = 3?

**Comment by tacaswell** [comment]
```python
ln, _, (bars,) = err
```
should work 

or

```python
ln, *_, (bars, ) = err
```
in python3
