### ISSUE TITLE
Qt5 backend gives missing icon errors on KDE Neon

### ISSUE THREAD

**Issue by arcooke** [matplotlib/matplotlib#8590]
### Bug report

**Bug summary**

Using Qt5Agg backend produces missing icon errors on KDE Neon 

**Code for reproduction**

Any code

```
import matplotlib.pyplot as plt

plt.plot([1, 2, 3])
plt.show()
```

**Actual outcome**

```
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
```

**Matplotlib version**
  * Operating System: KDE Neon 5.9
  * Matplotlib Version: 2.0.1
  * Python Version: 3.5
  * Theme: Arc Dark KDE https://github.com/PapirusDevelopmentTeam/arc-kde
  * Icon pack in use: Papyrus-Dark https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

Everything installed with pip via Pycharm Community or apt

![image](https://cloud.githubusercontent.com/assets/6278400/25784816/3b87f254-3339-11e7-8394-5722db875678.png)

KDE Neon does not come with any of the expected icon packs.  Installing one of them would likely resolve this issue 

![image](https://cloud.githubusercontent.com/assets/6278400/25784861/eea94a9a-3339-11e7-847c-25f3f3838f1c.png)

**Comment by tacaswell** [comment]
From a quick google search on that warning, I am not sure that this is a Matplotlib issue, but rather an issue with the icon theme.

The window looks right and we ship our own icons for the toolbar as png files.

**Comment by arcooke** [comment]
Ah, it seems you may be correct according to this https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/322

Does matplotlib ship with white icons for dark themes?  I'm not sure how that works under the hood or if it's even possible to determine.  It is using black icons on a dark theme and they're difficult to see.  

I initially thought maybe that was a result of the missing icon errors

**Comment by tacaswell** [comment]
No, we only ship black-on-transparent icons.

**Comment by tacaswell** [comment]
Closing as not a Matplotlib issue.

If someone wants to provide light-on-dark icons, we will merge it, but I do not think we need to track it.
