### ISSUE TITLE
Giving credit via the documentation

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8595]
A thought I've had as I've been going through the documentation of Matplotlib is that there isn't any kind of systematic way to give people credit for their work. Scattered throughout the examples are pieces of information like "thanks to `so and so` for this example", but it's highly inconsistent.

How do people feel about adding a list of contributors that defines labels for any contributor who wishes to be attributed for their work. Then, you can reference this person with the label. For example, you could define:

```
.. _Some Person: https:mywebsite.com
```
and then in the `what's new` section, or in examples/tutorials/etc, you can easily reference this with something like

```
blah blah blah. Credit: `Some Person`_
```

I think it's a nice way of recognizing the work that people do to extend Matplotlib.

We use this with the MNE-python project and I think it works relatively well. For example, see the bottom of our [what's new](https://raw.githubusercontent.com/mne-tools/mne-python/master/doc/whats_new.rst) file. Then see the rendered attributions somewhere like [here](http://martinos.org/mne/dev/whats_new.html).

What do people think about this?

**Comment by tacaswell** [comment]
Sounds good, only concern is keeping it up / management of the list.  We have a large number of unique contributors :)

**Comment by choldgraf** [comment]
Yeah - for us at the end of any PR that adds a major change, we ask the person to add a line describing what they did to `whats_new` and also ask them to add their contact link if they'd like to.

**Comment by choldgraf** [comment]
perhaps we can use this issue to collect an initial list of names / emails? Or I guess we could just pull it from the git commits and take some top percentile of committers to add initially.

**Comment by choldgraf** [comment]
I'm gonna close this issue because it doesn't seem like there's a ton of excitement around maintaining this. I'll suggest that people just put their name in a credits section at the beginning of example etc

If somebody thinks this is worth implementing I'm happy to re-open
