### ISSUE TITLE
Pie Chart from CSV File

### ISSUE THREAD

**Issue by NedySuprianto** [matplotlib/matplotlib#8599]
hi guys, how i can make Pie Chart from CSV file include the activites/label too?

CSV file (if open with excel) : 

Used           Free                         -> Column
100000       50000                      -> Row

Example  Output :
http://3.bp.blogspot.com/-QircMw5Y1AA/T791QSLlRSI/AAAAAAAAA6c/VbtS8MBXyhs/s1600/mem-info.png

Thanks :)

**Comment by WeatherGod** [comment]
This isn't a bug report. For topics like this, please join the mailing list at https://mail.python.org/mailman/listinfo/matplotlib-users
