### ISSUE TITLE
Animation video file writer not working for real-time animation

### ISSUE THREAD

**Issue by kissmyjazz** [matplotlib/matplotlib#8604]
**Bug summary**

Hello,
I have an application that plots a real-time eye-tracking data it receives via socket from another program. Today I tried to implement an option to output the video recording of the plotting.
I tried several writers and did not succeed with any of them. Basically when I start recording, no error messages are generated, the real-time animation stalls for some time and then resumes. Video output is also generated, but consists only of several seconds of video showing the static canvas only. My idea is to turn the recording on when I press the button on my Qt gui interface which triggers the 'save' method on animation that is already running. Maybe therein lies my problem and such implementation is not supported. Then please consider this as a feature request. I am working on Linux Ubuntu with the latest Matplotlib 

Program files are attached
[fixTrainingRecWindow.tar.gz](https://github.com/matplotlib/matplotlib/files/991901/fixTrainingRecWindow.tar.gz)

**Comment by dopplershift** [comment]
On the face of it (not having looked at your code), I don't see why what you're describing wouldn't work; the animation should be caching a certain amount of the information from the frames in order to be able to save a movie from what I would call a "procedural" animation.

I'm also not sure that the code paths handling the procedural-style have been used as much, so it also doesn't surprise me that there is a bug or two lurking.

**Comment by kissmyjazz** [comment]
Thank you for your reply. Can you suggest any helper wrapper library that I can use for introspection to provide more information here?
Ideally I would like like to record just the chosen chunks of the running animation, so I need methods to start and stop/pause the recording. The frame number is extended by 1 at each loop iteration with a generator function, so maybe there lies some problem for the video writer class. 
I am graphing the behavioural experiment in real-time, so i cannot predict in advance what periods I would like to record.

**Comment by tacaswell** [comment]
I don't think that the existing save methods will work (as you also want to see the figure updating).

I suspect that you will want to directly use the writer classes (see 
http://matplotlib.org/api/animation_api.html#writer-classes)

Something like https://github.com/matplotlib/matplotlib/pull/7079 might be along the lines of what you need.
