### ISSUE TITLE
Feature request: qualitative colormap (Vega) with variable number of hue steps

### ISSUE THREAD

**Issue by MoritzImendoerffer** [matplotlib/matplotlib#8616]
It is pretty complicated to tweak the qualitative color-map Vega (or tab) to have custom numbers of hue steps (see this post for an example http://stackoverflow.com/questions/43938425/matplotlib-change-colormap-tab20-to-have-three-colors)

It would be great to be able to have for example Vega30c Vega20c and so on

**Comment by tacaswell** [comment]
I do not quite understand what you are asking for.

You can use `ListedColorMap` (http://matplotlib.org/api/colors_api.html?highlight=listedcolormap#matplotlib.colors.ListedColormap) to make your own color maps with colors of your choice.  

The vega names are deprecated, please use the 'tab' versions instead.

**Comment by MoritzImendoerffer** [comment]
The tab20 colormap is great if I plot data with 2 consecutive features, the tab20c colormap is great for 4 consecutive features (for example increasing temperature (4 levels) for different experiments). It would be great to have the feature of choosing the hue levels while I instantiate the colormap. For example color = plt.cm.tabc(hue_levels=3, colors = 5)
