### ISSUE TITLE
Plot Windows does not close when python script is closed forcefully

### ISSUE THREAD

**Issue by divyanshumehta** [matplotlib/matplotlib#8617]
### Bug report

When I forcefully stop the python script from the terminal by pressing `Ctrl + Z` the matplot windows does not close. Even when I click on the close button on the matplot window it does not close. Here is a screenshot trying to depict the bug. It would be great if the matplot windows could close when the script is also stopped or atleast the windows should close when the close button is clicked
![screenshot from 2017-05-14 19-47-36](https://cloud.githubusercontent.com/assets/16134827/26034714/57cb13ec-38de-11e7-9926-4ff0e60d8ec9.png)

**Comment by dstansby** [comment]
Hmm, which version of Matplotlib and python are you using, and do you know which matplotlib backend you're using?

**Comment by QuLogic** [comment]
`Ctrl+Z` does not interrupt anything; it pauses executation. Use `Ctrl+C` to interrupt processes.
