### ISSUE TITLE
The figure is not closed when the tab is closed

### ISSUE THREAD

**Issue by warmspringwinds** [matplotlib/matplotlib#8625]
Hello,

I don't know if it is a bug:
I have just observed that if I display figure using matplotlib's notebook magic
and then reopen the jupyter notebook the figure is no longer interactive but
 I still get the information that it is connected via:

```
import matplotlib

print(matplotlib.backends.backend_nbagg.connection_info())
```

I was expecting that the behaviour should be similar to the case when user explicitly presses
the button to stop interaction with figure like here:
https://github.com/matplotlib/matplotlib/issues/4281/

Meaning that when I explicitly stop the figure I no longer get info about connection via:

```
import matplotlib

print(matplotlib.backends.backend_nbagg.connection_info())
```

Thank you for your time.

**Comment by tacaswell** [comment]
That is probably a bug.  Suspect the issue is that we do not reliably detect that the figure is gone (due to closing tab) or correctly re-create the figure when the new tab is opened.

Can you try with `ipympl` ? https://github.com/matplotlib/jupyter-matplotlib

**Comment by tacaswell** [comment]
The reported behavior is still the case, however now if you run a cell like

```
fig
```

which will run the `Figure` object through the notebooks show machinery you get a live interactive figure again so I think that the current behavior of _not_ implicitly closing the figure when the tab is close (or reloaded) is correct (and I'm not even sure we get an event from the browser we could use to detect and close the figure).

It make be the case that we should do a better job of automatically reshowing in the new restored tab, but if that is something someone wants please open a new issue.
