### ISSUE TITLE
Remove unused resolution kwarg to PolarAxes

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8629]
The resolution kwarg to PolarAxes has triggered a warning of being with no effect (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/projections/polar.py#L243) since 8 years ago (https://github.com/matplotlib/matplotlib/commit/3093ce97d15dd018f1a265e6b84b6dcb655d5fd6).  Given that the warning effectively acts as a deprecation warning as well, the relevant code should just be removed.

**Comment by patniharshit** [comment]
Fixed by #8643 
This issue can be closed.

**Comment by anntzer** [comment]
thanks.
