### ISSUE TITLE
Codify documentation PR guidelines

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8632]
A quick thought for conversation: it's often the case that documentation-related PRs have a lot of narrative-style text in them. For this text, there are often little type-os etc that need to be fixed (e.g., capitalizing Matplotlib).

Currently the way this is handled is one of the code reviewers finds each of these errors and adds a comment (e.g., `capitalize Matplotlib`). Then the author goes through them and makes each little change. IMO this is an unnecessary doubling of the time it takes to make these small copy-edit changes.

What I propose is an addition to the developer guidelines specifically for documentation. The idea is that we set this 3 step process for documentation changes:

1. Author submits original documentation request.
2. Comments are only high-level ("this section should be moved" or "you should add a new component to this example" or "can you clarify what XXX means").
3. Once high-level stuff is approved, there is a final "copy-edit" step where reviewers are encouraged to edit the PR directly **only to improve small things like type-os, punctuation, missing words, etc**.
4. If there are lots of intermediate commits, we squash them before merging.

Thoughts? I think it would save people a lot of time, and could be pretty efficient as long as people are disciplined about saving the nitpicky edits for the very end. I think it'd also make the documentation PR process much more welcoming to new users.

Thoughts? 

pinging @story645 since we originally discussed this in a PR

**Comment by story645** [comment]
I love it 'cause it'll also hopefully minimize the conversations which currently makes some of the PRs kinda terrifying.

**Comment by tacaswell** [comment]
:+1:

**Comment by choldgraf** [comment]
> Clarity questions should be part of the review

Agreed.

pinging @dopplershift @anntzer @QuLogic in case they have thoughts on this, since they've been very helpful in documentation conversations in the last few weeks as well

**Comment by dopplershift** [comment]
That workflow makes sense to me.

**Comment by anntzer** [comment]
I have mentioned during the dev phone calls some time ago that I'd be in favor of *encouraging* code devs to take over PRs (whether doc or minor fixes) if they can just fix the issue faster.  (So the current proposal definitely gets a +1 from me.)

I think a reasonable idea would be to mention on the PR template something like "Unless you request otherwise (and feel free to do so), core devs may push minor (typo/style) fixes to your PR branch if this can make the PR merged faster."

**Comment by choldgraf** [comment]
> I think a reasonable idea would be to mention on the PR template something like "Unless you request otherwise (and feel free to do so), core devs may push minor (typo/style) fixes to your PR branch if this can make the PR merged faster."

I think that's a good idea.

The only drawback is that I can foresee one of the devs doing this, and then asking the author to rebase some of the small changes. Rebasing can be a big road-block to new contributors. So perhaps this can be paired with a small tutorial in the devdocs on rebasing with `-i`? Then the dev that asks for it can link to the tutorial when they ask for a rebase.

Alternatively there's always the GH "squash and merge" function but I feel like I've seen that get pushback in other MPL threads

**Comment by anntzer** [comment]
We had agreed on allowing squash and merge during a dev call a few weeks ago.

**Comment by choldgraf** [comment]
ah that's great - so what would the addition here be? A statement in the devdocs to the effect of what I mentioned above, plus another line in the github PR template that says devs can make changes to a branch?

**Comment by jklymak** [comment]
I don't think there are remaining acton items here?  Feel free to reopen if incorrect.
