### ISSUE TITLE
get_fontconfig_fonts() returning not a list but a concatenation of file names

### ISSUE THREAD

**Issue by adlvdl** [matplotlib/matplotlib#8635]
### Bug report

**Bug summary**

The method get_fontconfig_fonts() in matplotlib.font_manager should return a list of files according to the documentation but in my machine it returns a list with one element that represents all paths concatenated. The snippet comes from a [stack-overflow answer.](http://stackoverflow.com/questions/8753835/how-to-get-a-list-of-all-the-fonts-currently-available-for-matplotlib)

**Code for reproduction**

```python
import matplotlib.font_manager
flist = matplotlib.font_manager.get_fontconfig_fonts()
names = [matplotlib.font_manager.FontProperties(fname=fname).get_name() for fname in flist]
print(names)
```

**Actual outcome**

```
OSError: [Errno 36] File name too long
```

**Expected outcome**

It should return a list of names

**Matplotlib version**

  * Operating System: Fedora 25
  * Matplotlib Version: 2.0.0
  * Python Version: 3.5
  * Jupyter Version (if applicable):
  * Other Libraries: 

I think I used pip3 to install matplotlib but I'm not 100% sure.

**Comment by dstansby** [comment]
See https://github.com/matplotlib/matplotlib/issues/7906 - this should be fixed in version 2.0.1.
