### ISSUE TITLE
plt.hist chooses improper range when using string-based bin options

### ISSUE THREAD

**Issue by pollackscience** [matplotlib/matplotlib#8636]
### plt.hist range bug

When using plt.hist with multiple input data sets, not supplying a range, and using a string-based binning option ('auto', for example), the range determined will cut off the later datasets and only fully include the first.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

data = np.random.normal(0, 1, size=1000)
data2 = np.random.normal(3, 1, size=1000)
data3 = np.random.normal(6, 1, size=1000)

plt.hist([data, data2, data3], bins='auto', histtype='stepfilled', stacked=False)

```

**Actual outcome**
![bad_hist](https://cloud.githubusercontent.com/assets/5065341/26168360/6b32991e-3aff-11e7-95ea-bb6b95c98c82.png)

**Expected outcome**
This is the plot using the bin-edges as determined by np.histogram using the following code:
```python
_, be = np.histogram([data, data2, data3], bins='auto')
plt.hist([data, data2, data3], bins=be, histtype='stepfilled', stacked=False)
```
![good_hist](https://cloud.githubusercontent.com/assets/5065341/26168446/b42be1e8-3aff-11e7-9b72-5a78a051055a.png)

**Matplotlib version**

  * Operating System: OSX 10.10.5
  * Matplotlib Version: 2.0.1
  * Python Version: 2.7.13
  * Jupyter Version (if applicable): 4.0.6
  * Other Libraries: 

Python installed via Homebrew, all python packages installed via pip.

**Comment by tacaswell** [comment]
I have a PR to fix this, but am not _super_ happy about it.

**Comment by bebound** [comment]
Is this the same bug?  Trying to draw a hist from Series, the second one is the expected output.
Thank you.
![screen shot 2017-12-13 at 3 46 10 pm](https://user-images.githubusercontent.com/2227874/33927393-131c4658-e01d-11e7-8f00-fe07da0a07fa.png)
