### ISSUE TITLE
mpl 2.0.0 vs 2.0.1 line style with wx-backend

### ISSUE THREAD

**Issue by edge-python** [matplotlib/matplotlib#8637]
I have taken the base code from:

https://matplotlib.org/examples/user_interfaces/embedding_in_wx4.html
user_interfaces example code: embedding_in_wx4.py

I have added:

import matplotlib.widgets  # .Cursor

and in class CanvasFrame:

        self.lineprops = dict(linewidth=0.5, linestyle='-.', color='#660099', alpha=1)
       
        self.line_cursor = matplotlib.widgets.Cursor(self.axes, **self.lineprops)

RESULT:
the line style in 2.0.1 (and 2.0.2) is very different to 2.0.0 

I want the style of 2.0.0

What is the reason?

Thank you

![2 0 0 vs 2 0 1](https://cloud.githubusercontent.com/assets/4279914/26172443/c793c162-3b48-11e7-9740-ba0cb494475c.gif)

  * Operating System: Win 10 64bit
  * Matplotlib Version: 2.0.0 vs 2.0.1 (and 2.0.2)
  * Python Version: 3.6.1
  * Other Libraries: wx 4.0.0a1

**Comment by WeatherGod** [comment]
I don't think this has anything to do with the wx backend. One of the style
changes for v2.0.0 had to do with scaling the line style patterns, however,
there was a bug in how it was implemented and that was fixed for v2.0.1,
IIRC.

As a side note, I notice that this new linestyle scaling feature isn't
mentioned in the "what's new" docs.

**Comment by QuLogic** [comment]
It's in [API changes](http://matplotlib.org/api/api_changes.html); this is not a bug, but a correction of less-desired behaviour. The line width is now actually consistent with the width you requested.

**Comment by edge-python** [comment]
Thank you for your answer.
but,
these are not good news for me.

**Comment by WeatherGod** [comment]
Actually, you might be able to get what you want... maybe. There is an
rcParam, 'lines.scale_dashes'. Try setting that to False. The (corrected)
old behavior was to clip the scaling of the dashes at around 0.5, IIRC, so
you *might* be able to get the old behavior (or something close to it,
perhaps?).

**Comment by edge-python** [comment]
oh, you are so fast
I will try it

Please allow me a statement:
In mpl 2.0.0 very thin and sharp lines for the V and H lines are available for the cursor. But not so in mpl 2.0.1. This is a step back. I would appreciate it if the developers rethink that.
Thank you

**Comment by afvincent** [comment]
The API change is due #8032 (the relevant commit is 276e1e9). Basically the former scaling scheme was `dashes = unscaled_dashes * max(2, linewidth)`.

In your case, what about something like
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Cursor

# Manually rescale the desired dash pattern
my_dashdot = [2.0*val for val in plt.rcParams['lines.dashdot_pattern']]
cursor_props = dict(linewidth=0.5, dashes=my_dashdot, color='#660099')

plt.close('all')
fig, ax = plt.subplots()

t = np.arange(0.0, 3.0, 0.01)
s = np.sin(2*np.pi*t)
ax.plot(t, s)

line_cursor = Cursor(ax, **cursor_props)

plt.show()
```
![capture d ecran de 2017-05-18 18-15-32](https://cloud.githubusercontent.com/assets/17270724/26212520/1b04c1f4-3bf6-11e7-9cb6-a4e75d647ae5.png)

**Comment by edge-python** [comment]
Thank you for the example.
It looks better.
I still need to figure out how to do it for matplotlib.figure
...
I replaced plt.rcParams with matplotlib.rcParams and it seems to work.
I hope I'm on the right track.

many thanks for the support

**Comment by afvincent** [comment]
*I am pretty sure `matplotlib.pyplot.rcParams` is simply a convenient shortcut for `matplotlib.rcParams`.*

BTW, using the dash-dot pattern from *rcParams* was just a mean of showing that you could manually scale one of the default patterns. *But you could also perfectly use your own dash sequence if you are not satisfied with it.* See the [Line2D docstring](http://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D) for a comprehensive description of the API, or simply [this example](http://matplotlib.org/examples/lines_bars_and_markers/line_demo_dash_control.html) to get a quick glance at the syntax. In a nutshell, a dash style is an **even-length** sequence of on/off ink (in points).

PS: a similar way to customize the dashes may be to define a custom *line* style, which can be seen as a custom dash style prepended with an “offset” (usually set to zero...), following the pattern `(offset, on-off-dash-seq)`. See for example [here](http://matplotlib.org/examples/lines_bars_and_markers/linestyles.html).

**Comment by edge-python** [comment]
Thanks for your help, I'm not a professional developer even though I've created a complex Matplotlib application
I'm glad to have the right cursor lines again
![ant-fit_plot](https://cloud.githubusercontent.com/assets/4279914/26215599/3ff1ad14-3c01-11e7-9677-74bcdb0742ab.png)

**Comment by afvincent** [comment]
That's a nice looking application :).
