### ISSUE TITLE
System Error in backend_agg. (with a fix!)

### ISSUE THREAD

**Issue by Erotemic** [matplotlib/matplotlib#8650]
I found an error when trying to add a stroke patheffect to a FancyArrow collection. Unfortunately I don't have a MWE, but I do have a simple fix. 

The error I got was: 
SystemError: new style getargs format but argument is not a tuple?

The offending line was line 166 of `matplotlib/backends/backend_agg.py`, which was calling the `draw_path` method of a `matplotlib.backends._backend_agg.RendererAgg`. 

```
        else:
            self._renderer.draw_path(gc, path, transform, rgbFace)
```

This line calls into a compiled library, so I can't say much about what's going on further down the stack.

However, I did some print debugging. I found that this line was called just fine before I added my patheffects changes. Then I turned my new code on and did the same thing. The main difference was that `rgbFace` was always a tuple when the code worked and it was an `np.ndarray` when it crashed. 

I made a simple fix that changes the code to: 
```
        else:
            if rgbFace is not None:
                rgbFace = tuple(rgbFace)
            self._renderer.draw_path(gc, path, transform, rgbFace)
```

and now everything works. I don't have time to make a PR right now, but if someone else wants to this is an easy fix. 

--------------------

Versions:

Ubuntu Linux 16.04
matplotlib (2.0.2) from pip
Python 3.5.2

The library that had the crash in it: 
 _backend_agg.cpython-35m-x86_64-linux-gnu.so

**Comment by tacaswell** [comment]
Exact work:
 - apply the patch in a PR
 - find a MWE and add a test

**Comment by arcticbarra** [comment]
I'll start working on this 😄

**Comment by malgamves** [comment]
cannot find the directory with the issue
