### ISSUE TITLE
Document windows build using conda

### ISSUE THREAD

**Issue by fkohlgrueber** [matplotlib/matplotlib#8652]
Since I wanted to start contributing to matplotlib, I tried to build matplotlib from source. I read through the documentation and tried to use [matplotlib-winbuild](https://github.com/jbmohler/matplotlib-winbuild) as recommended on the [website](https://matplotlib.org/users/installing.html#building-on-windows).

The first problem was that matplotlib-winbuild seems to be outdated and does not support VS2015 / VS2017. There's a pull-request that claims to add support for VS2015, but that didn't work out for me.

I then tried several different ways to install the external dependencies, but none worked out until I found [build_alllocal.cmd](https://github.com/matplotlib/matplotlib/blob/master/build_alllocal.cmd) in the matplotlib repository. 

Using build_alllocal.cmd (with two small changes), I was able to get a working build of matplotlib. It uses anaconda to get the external dependencies and eliminates the trouble of compiling them. I made a short gist showing how I managed to build matplotlib: [gist](https://gist.github.com/fkohlgrueber/2e88ce965e9d79ccf5863032b8a0fa7a).

Now my questions are:

Is the way I installed matplotlib correct? Can I use this setup for testing/developing matplotlib? Are there any restrictions or things the won't work?

If it is a valid deveopment build, shouldn't the installation process above be part of the official documentation? It seems to be easier than the process that's currently suggested in the docs and might lower the barrier for new contributors who are working on Windows.

I'm looking forward to your replies.

**Comment by tacaswell** [comment]
Matplotlib has a shortage of windows based developers (most of us are linux or mac), any help updating the docs to be more correct for windows would be great!

Another reference for how to set up windows systems for development is the appveyor configuration files and the conda recipe.

As to your questions:

 - if it runs and passes tests it is probably correct
 - I don't see why you could not use it for testing / development or why there would be any limitations on it
 - The docs should be updated, can you put in a PR to do that?

attn @Kojoley

**Comment by QuLogic** [comment]
The site no longer refers to `matplotlib-winbuild`, nor does `build_alllocal.cmd` exist any more. There are no longer any extra dependencies other than the compiler and Python, and a simple `pip install .` works for installing from source. So I don't think there's anything more to write here.
