### ISSUE TITLE
Wrong colour rendering

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#8662]
### Bug report

**Bug summary**

Hex colours are off.

**Code for reproduction**

```python
fig.savefig('test.png', facecolor='#1D1D1D') #1D = 22...
```
**Actual outcome**
The output colour will be `#222222`.

**Expected outcome**
Should have been `#1D1D1D`.

**Matplotlib version**
Latest from Conda, on Ubuntu 16.

**Comment by tacaswell** [comment]
How are you measuring the color?

```python
import matplotlib.colors as mcolors
mcolors.to_hex(mcolors.to_rgb('#1D1D1D'))
```

round trips correctly as does

```python
png = plt.imread('test.png')
mcolors.to_hex(png[0, 0, :])
```

**Comment by Atcold** [comment]
I open the image, with Ubuntu's Image Viewer, and check the colour with Gpick.

**Comment by Atcold** [comment]
Here you have the source code
```python
import matplotlib.pyplot as plt
plt.axis()
plt.savefig('abc.png', facecolor='#1D1D1D')
```
![matplotlib](https://cloud.githubusercontent.com/assets/2119355/26476037/da2fae02-4189-11e7-86d5-4990faa814e4.png)

**Comment by tacaswell** [comment]
Gpick is a separate tool correct?  I strongly suggest that X11 is applying color correction or some such.

Can you check your file in gimp and that the test above round trip for you?

**Comment by Atcold** [comment]
OMG.
It's not X11, but *Ubuntu*'s *Image Viewer* that applies a gamma correction (what the heck?)!
Still odd, I was composing multiple images into a MP4 and the background colour was off... I guess that was because I had an error in my feedback loop (using *Gpick* on *Image Viewer*).

Sorry for the noise, guys...

**Comment by tacaswell** [comment]
No worries, if we _were_ getting this wrong it would be a major problem!

My guess as to what the image viewer devs were thinking is that their target use-case is viewing pictures-of-people-and-stuff in which case applying the gamma correction is probably the right thing to do.

**Comment by Atcold** [comment]
Hmm... I'm not sure. My monitors **are** calibrated. So, why would *you* alter my settings based on, what, your assumption on how my monitor renders its pixels? Meh...
