### ISSUE TITLE
Plots with many subplots can be slow

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#867]
Originally reported by John Gu on the mailing list thread "extreme navigation slowness for subplots".
#549 was a proposed solution to the problem that did not seem to create improvement for all users.

Script to reproduce the issue:

```
x = arange(1000)
y = x

f = figure(1)
for ia in xrange(5):
     for ib in xrange(5):
         ax = subplot(5,5,ia*5+ib+1, navigate=True)
         ax.plot(x,y)
```

**Comment by cvanelteren** [comment]
Is there any update on this? I currently need to have a figure containing 16 x 33 subplots and it takes ages to load.

**Comment by efiring** [comment]
It sounds like the relevant issue is #6664.
