### ISSUE TITLE
wxAgg navigation bar has no Figure Options

### ISSUE THREAD

**Issue by maddox32** [matplotlib/matplotlib#8675]
### Bug report

The wxAgg backend navigation bar misses the Figure Options dialog that is present in the Qt5Agg backend.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.use("wxagg")
# mpl.use("qt5agg")
import matplotlib.pyplot as plt

plt.plot([1, 2, 3], [1, 3, 2])
plt.show()
```

**Outcome**

wxAgg shows the navigation bar without the possibility to set axes/curve properties, Qt5Agg does have that option.

Also, wxAgg shows the bar below the figure, Qt5Agg above the figure.

**Matplotlib version**

  * Operating System: Mac OS 10.12, Windows 7
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6 (Mac, homebrew), 3.5 (Windows, conda)
  * Jupyter Version (if applicable):
  * Other Libraries: wxPython 4, latest Phoenix snapshot

**Comment by QuLogic** [comment]
AFAIK, only the Qt backend implements this property dialog. The location of the navigation bar is determined by the backend toolkit's default positioning, I think.
