### ISSUE TITLE
Tkinter backend errors over ssh connection

### ISSUE THREAD

**Issue by notmatthancock** [matplotlib/matplotlib#8680]
### Bug report

**Bug summary**

Matplotlib with Tkinter backend errors over ssh with X11 forwarding, `ssh -X [...]`. 
This error doesn't happen when I use matplotlib over ssh on my local network, however.

**Code for reproduction**

```
import matplotlib as mpl; mpl.use('tkagg')
import matplotlib.pyplot as plt

plt.plot([1,3,2])
plt.show()
```

**Actual outcome**

```
  File "XXX/lib/python/2.7.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "XXX/lib/python/2.7.10/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 163, in __call__
    manager.show()
  File "XXX/lib/python/2.7.10/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 610, in show
    self.canvas.manager.window.attributes('-topmost', 1)
  File "XXX/lib/python/2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1619, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window ?-type list?"
```

**Expected outcome**

The plot should be shown as normal. Other graphics appear to work normally over the same connection, e.g., I can plot via `gnuplot` or display images via image magick's [`display`](https://www.imagemagick.org/script/display.php) command over the same ssh connection.

**Matplotlib version**

  * Operating System: Cent OS
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.12

**Comment by matthew-brett** [comment]
This works for me on a Debian sid system.

What do you get for:

```
import tkinter as tk
tk.Tk()
```

**Comment by anntzer** [comment]
Does it work if you use ssh -Y instead of ssh -X?  (For me ssh -Y is needed.)

**Comment by notmatthancock** [comment]
@matthew-brett ,
```
In [1]: import Tkinter as tk
In [2]: tk.Tk()
Out[2]: <Tkinter.Tk instance at 0x7f1e9f3a74d0>
```
@anntzer ,
I'm currently using `-Y`. `-X` gives the message,
```
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: No xauth data; using fake authentication data for X11 forwarding
```

I should mention that I'm ssh'ing into one server and then ssh'ing to another local (relative to the first) server with X11 forwarding on both connections. Plotting via matplotlib over ssh has worked for a couple years over these servers until recently, and like I said, other GUI programs appear to work fine over the same connection.

**Comment by matthew-brett** [comment]
What version of CentOS do you have?  How did you install Python / Tcl / Tk?  What do you get for:

```
yum info python tk tcl tkinter
```

**Comment by notmatthancock** [comment]
CentOS release 6.9 (Final)

Python, etc was installed from source on the home dir since I don't have root permissions. The system-wide version seems to be working, though, which I failed to check initially. So, I definitely screwed up the tk, etc. installation when installing python locally.

Not a matplotlib issue! Closing this...

**Comment by matthew-brett** [comment]
I guess it could still be a matplotlib issue, if we can generate errors with an installed Tk that we haven't thus far tested.   Would you mind giving the output for:

```
>>> import Tkinter as tk
>>> tk.TkVersion, tk.TclVersion
```

**Comment by notmatthancock** [comment]
`(8.4, 8.4)`

**Comment by matthew-brett** [comment]
Ah - I doubt that we have tested Tcl 8.4 - it's really really old now.  How did you end up with Tcl 8.4?  I notice that 8.5 is the default on CentOS 6.9.

What do you get for `yum info tcl tk` ?

**Comment by notmatthancock** [comment]
I honestly don't remember. It was a while ago. I didn't realize it was so far behind. It would prob be better to upgrade since the system version is newer than mine:

```
Installed Packages
Name        : tcl
Arch        : x86_64
Epoch       : 1
Version     : 8.5.7
Release     : 6.el6
Size        : 4.4 M
Repo        : installed
From repo   : anaconda-CentOS-201303020151.x86_64
...

Name        : tk
Arch        : x86_64
Epoch       : 1
Version     : 8.5.7
Release     : 5.el6
Size        : 3.3 M
Repo        : installed
From repo   : base
...
```

**Comment by matthew-brett** [comment]
I don't think there's anything between matplotlib 2.0.0 and 2.0.2 that would lead to this error.  I guess we should just keep this one in mind, hope that it doesn't come up again, and if it does, spend a couple of hours getting ssh and Tcl 8.4 and Tkinter linked to 8.4 on a docker image.

**Comment by pyandri** [comment]
Same error for me, same version of Tk & Tcl  (8.4), python3.4.5 and matplotlib 2.1.2  : 
 File "/usr/local/lib/python3.4/tkinter/__init__.py", line 1621, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window"

**Comment by tacaswell** [comment]
@pyandri can you provide the full traceback?

We claim to support tk > 8.3, we may have to bump that number to match reality

**Comment by tacaswell** [comment]
@pyandri Can you also make a new issue so we do not loose track of it?
