### ISSUE TITLE
GTKAgg blit with bbox

### ISSUE THREAD

**Issue by jrgirvan** [matplotlib/matplotlib#8684]
### Bug report

**Bug summary**
I'm upgrading from 1.3.1 to 2.0.2 and all of my plots work except for those that use blitting
This worked in 1.3.1

`calling canvas.blit(ax.bbox) `
Fails in the  GTKAgg backend `_gtkagg.cpp`

Easiest example is to use the mpl examples and run pong_gtk example
`matplotlib/examples/event_handling>python pong_gtk.py`

https://github.com/matplotlib/matplotlib/blob/master/examples/event_handling/pipong.py#L214

**Actual outcome**
https://github.com/matplotlib/matplotlib/blob/master/src/_gtkagg.cpp#L75
`destbufferptr = &destbuffer[0];` fails due to `destbuffer` being empty

**Expected outcome**
`destbufferptr` retrieves a pointer to the beginning of the vector

I have two workarounds

1. Pass `None` as the bbox
1. Modify _gtkagg.cpp
```
destbuffer.push_back(0);
destbufferptr = &destbuffer[0];
destbuffer.pop_back();
```

**Matplotlib version**
  * Operating System: Window2 10 x64 Version 1607 (OS Build 14393.1198)
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.8
  * Jupyter Version (if applicable):
  * Other Libraries: 

Build from source

**Comment by tacaswell** [comment]
I think the `reserve` should be a `resize`, grabbing a pointer to reserved, but not filled entries in a stl vector seems non-kosher to me.

attn @mdboom

**Comment by jrgirvan** [comment]
Tested replacing
`destbuffer.reserve(destheight * deststride);`
with
`destbuffer.resize(destheight * deststride);`

works

**Comment by tacaswell** [comment]
This sent me down a fun rabbit hole, but now the pong demo works on any backend!
