### ISSUE TITLE
Feature Request: add "rasterized" to the pdf backend parameters.

### ISSUE THREAD

**Issue by baffelli** [matplotlib/matplotlib#8689]
It would be useful to be able to enable/disable the rasterizing behavior for the pdf backend directly from the rcParams.
Suppose the rcParams file contains the below line:
```
#remaining parmeters above
savefig.format: pdf
pdf.rasterize: True
```
when plotting something using those rcParams and saving the figure as in:
```
import matplotlib.pyplot as plt
import numpy as np
f, ax = plt.subplots()
ax.imshow(np.random.randn(100,100))
f.savefig("./some_plot.pdf")
```
```f.savefig``` should get the default kwarg ```rasterize``` from the rcParams.

**Comment by baffelli** [comment]
Did not read the documentation correctly.

**Comment by miguelfaf10** [comment]
I am looking exactly for this feature, but to be applied only to specific objects in plot, namely traces created with matplotlib.pyplot.plot(). 

How can you dot it? Couldn't find anything in the documentation.

**Comment by WeatherGod** [comment]
I think you only need to pass `rasterized=True` to that particular plot
call.

**Comment by miguelfaf10** [comment]
I know, But I have a hole lot of scripts with plot calls where I didn't pass the 'rasterized=True'. 

Is it possible to change the default setting of this argument for all plot calls a posteriori? like is done for the other rcParams settings?

**Comment by tacaswell** [comment]
I _think_ if you set the axes to rasterized everything under it will be rasterized as well.

If you have references to `Line2D` object return by `plot` you can also use `ln.set_rasterized(True)`.

**Comment by miguelfaf10** [comment]
But I don't want to have the entire axes rasterized. Ideally the axes and labels and legends are vectorial, and only the plot traces would be rasterized. Basically to account for the situation when there are too many plot points.

And ideally, do it once, by configuration, and not on every call to plt.plot()
