### ISSUE TITLE
Use rcParams to control default "raise window" behavior

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#8692]
See discussion at end of closed issue #596.  I suspect that code added to backend-specific `show` implementations to attempt to make the new window visible should be made conditional on an rcParams setting, since there will always be cases where one *doesn't* want this behavior.

**Comment by souravsingh** [comment]
I am interested in working on this. How do I start?

**Comment by WeatherGod** [comment]
Well, here is our developer's guide: http://matplotlib.org/devel/index.html
You'll want to look at rcsetup.py to add a new rcParam, and then you will
need to go into backend_bases.py most likely to have it's show() check the
value of this param and trigger or not trigger the raise.

**Comment by garritfra** [comment]
I could take on this problem if @souravsingh is not on it. I'd like to get into open source coding  but I can't find any beginner friendly issues. This seems to be a good starting point

**Comment by timhoffm** [comment]
Sounds good. The goal would be to have it on Qt, Gtk, Tk. But we can at least document if this cannot be made to work for a specific backend.

**Comment by immaxchen** [comment]
Hi @timhoffm, could you help to review my PR? thanks!  :)

**Comment by Higgs32584** [comment]
I think this should be closed given the commit
