### ISSUE TITLE
ImageGrid with varying extents fails to maintain padding

### ISSUE THREAD

**Issue by damca** [matplotlib/matplotlib#8695]
### Bug report

For an ImageGrid object, `grid = ImageGrid(...)`, when passing different extent values to `grid[ix].imshow(..., extent=extent)`  the resulting image does not maintain consistent padding.

**Code for reproduction**

```python
from mpl_toolkits.axes_grid1 import ImageGrid
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(18,12))
nr, nc = (2, 3)
nt = nr * nc
grid = ImageGrid(fig, 111, (nr, nc), axes_pad=0.1)
ims = np.ones((nt, 100, 100), dtype=np.uint8) * 255
ims[:,:-1:10,:] = 0
extents = [(i, i+99, i+99, i) for i in range(nt)]
for i in range(nt):
    ax = grid[i]
    im = ims[i]
    extent = extents[i]  # bug 
    # extent = extents[0]  # works (when uncommented passes the same extent to each ax)
    imax = ax.imshow(im, 'gray', extent=extent)
    ax.axis('off')
plt.show()
```

**Actual outcome**

Bug:
![image](https://cloud.githubusercontent.com/assets/16568850/26656318/66a92ea2-4613-11e7-8cff-2060b94135b6.png)

**Expected outcome**

Expected:
![image](https://cloud.githubusercontent.com/assets/16568850/26656345/81284be6-4613-11e7-8b8a-dac356bbac00.png)

**Matplotlib version**

  * Operating System: macOS 10.12.5
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Ipython Version (if applicable): 6.0.0

Installed in a conda enviornment with `conda create -n name ... matplotlib`

**Comment by ImportanceOfBeingErnest** [comment]
I think this issue is caused by 
(a)  a misconception of what the `extent` argument does
(b)  a misinterpretation of the image, where the imshow has white color and the axes-spines are turn off
(c)  a particularity (possibly of the MacOS backend?) of a transparent axes background.
or any combination of those.

Using the Qt4Agg backend, setting the figure's background to non-white, turning the axes on and using a colormap without white, 

```
from mpl_toolkits.axes_grid1 import ImageGrid
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(13,9))
fig.set_facecolor("lightgrey")
nr, nc = (2, 3)
nt = nr * nc
grid = ImageGrid(fig, 111, (nr, nc), axes_pad=0.1)
ims = np.ones((nt, 100, 100), dtype=np.uint8) * 255
ims[:,:-1:10,:] = 0
extents = [(i, i+99, i+99, i) for i in range(nt)]
for i in range(nt):
    ax = grid[i]
    im = ims[i]
    extent = extents[i]
    imax = ax.imshow(im, 'copper', extent=extent)
    #ax.axis('off')

plt.show()
```

one would get the following image. 
![gh_imagegrid py](https://cloud.githubusercontent.com/assets/23121882/26658803/c7755a7c-466c-11e7-889c-f30cafee244a.png)

I think this is the expected as well as the intended result from the above code.  
The only open question might be if there is a setting to **un**share the axes in the `ImageGrid`, since it seems to only allow for sharing everything or sharing rows and columns separetely, but not for sharing neither rows nor columns.

**Comment by damca** [comment]
Thanks for finding the underlying issue. I guess I was expecting that by default the axes would be independent. It would be nice to have a convenient option to unshare them.

**Comment by tacaswell** [comment]
@damca If you want independent axes, I suggest  `fig, ax_arr = plt.subplots(2, 3)`. 

`ImageGrid` is a helper class for when you have a grid of images and want to be able to disable the tick labels on everything but the edge axes (see third bullet point at https://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#imagegrid ).

If you have any other question about this I suggest dropping by our gitter https://gitter.im/matplotlib/matplotlib

**Comment by damca** [comment]
@tacaswell Thanks for the heads up about the gitter. One of the reasons I was using `ImageGrid` 
 (and is also a suggested reason under the link you provided) was for the ease of having rigidly defined `axes_pad` in inches rather than figuring out a hspace parameter that worked for a given layout of subplots and figsize.

**Comment by ImportanceOfBeingErnest** [comment]
Maybe it's worth mentionning that you can **un**share the axes of an ImageGrid by doing
```
grid = ImageGrid(...)
for i in range(len(grid)):
    for j in range(i, len(grid)):
        grid[i].get_shared_x_axes().remove(grid[j])
        grid[i].get_shared_y_axes().remove(grid[j])
```
The example from above would then look like this:

![gh_imagegrid py](https://cloud.githubusercontent.com/assets/23121882/26722991/a75d2040-4792-11e7-861f-e510fb5cd785.png)

Note that the images are the same, but the ticks are different for the different plots.

**Comment by damca** [comment]
@ImportanceOfBeingErnest that worked! Each extent is different, but they all display the same image. Thanks.
