### ISSUE TITLE
Make legend title fontsize obey fontsize kwarg by default?

### ISSUE THREAD

**Issue by gepcel** [matplotlib/matplotlib#8699]
mpl.__version__ : 2.0.1

Using the method `ax.legend(title='something', fontsize=18)` to draw a legend, only the handler labels has the fontsize but not the title. Was this the supposed behavior?

Example:
```python
%matplotlib inline
import matplotlib.pyplot as plt

fig, [ax1, ax2] = plt.subplots(1, 2, figsize=(8, 3))

ax1.scatter(1, 1, 40, label='point')
ax1.legend(title='location')

ax2.scatter(1, 1, 40, label='point')
ax2.legend(title='location', fontsize=20)
```
![image](https://cloud.githubusercontent.com/assets/4179106/26665811/b0802a74-46ce-11e7-8b87-e78de528bd1e.png)

Don't feel reasonable that everytime I have to do something like this:
```python
lg = ax2.legend(title='location', fontsize=20)
title = lg.get_title()
title.set_fontsize(20)
```

Or am I missing some args like `titlefontsize` of legend?

**Comment by efiring** [comment]
There is no legend kwarg for setting the title font properties, so you are stuck with using `lg.set_title('location', fontsize=20)` or `lg.get_title().set_fontsize(20)`.  

I see your point, though; having the legend fontsize kwarg apply to the title as well as the labels probably would be considered an improvement by most people.

**Comment by efiring** [comment]
Let's see what others think of this idea, or perhaps alternative legend API improvements.

**Comment by lzkelley** [comment]
I think `fontsize` applying to everything would be a big improvement.  Alternatively, there could be a separate `fontsize_title` argument, or a combination of the two... i.e.

```
def legend(..., fontsize=12, fontsize_title=None):
    if fontsize_title is None:
        fontsize_title = fontsize
    ...
```

**Comment by LeonardoLeano333** [comment]
What I have done for solving this is putting this in the begining of the plot

`plt.plot([0],[0],marker=' ',linestyle=' ',label='dose(mGy)')`

I think it is not the properly way to do this but it could be a easy/fast way to deal with such anoing problem.

**Comment by jklymak** [comment]
Note #10715 solves this issue.
