### ISSUE TITLE
Class pages don't document their methods

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#8701]
eg. compare http://matplotlib.org/devdocs/api/_as_gen/matplotlib.patches.FancyArrowPatch.html and http://matplotlib.org/api/patches_api.html?highlight=fancyarrowpatch#matplotlib.patches.FancyArrowPatch

In the devdocs no class methods are documented under the class documentation.

**Comment by tacaswell** [comment]
I suspect that this is caused by 17ef1d20f532061c95f050e7aebff0126fa5f8ef https://github.com/matplotlib/matplotlib/pull/8525 and the autoclass now going through different templates.
