### ISSUE TITLE
setting `font.family: serif` does not change math font to serif.

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#8702]
### Bug report

**Bug summary**

Setting 
```
font.family: serif
```
Does not effect math text like `ax.set_xlabel('$E / \mathrm{GeV}$')`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'serif'
plt.plot([1, 2, 3])
plt.xlabel('$E / \mathrm{GeV}$')
plt.ylabel('E / GeV')
```

**Actual outcome**

sans-serif font for the axis label using math

![test](https://cloud.githubusercontent.com/assets/5488440/26730967/e0c57754-47b2-11e7-920b-847f3ce9d549.png)

**Expected outcome**

Both axes labels using serif font

**Matplotlib version**

  * Operating System: Ubuntu 16.10
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6

**Comment by geib7592** [comment]
Your `mathtext.fontset` is probably set to the default value `dejavusans`. Adding
```
plt.rcParams['mathtext.fontset'] = 'dejavuserif'
```
should give you what you want.

**Comment by MaxNoe** [comment]
Wow, this is really unexpected. For me at least.

**Comment by tacaswell** [comment]
TODO:

 - [ ] update http://matplotlib.org/users/text_props.html#default-font to include this detail (or find a better place!)

**Comment by dstansby** [comment]
Fixed by #8853

**Comment by MaxNoe** [comment]
I think this is something that should not be "fixed" by adding documentation, but, you know, actually be fixed.

**Comment by ImportanceOfBeingErnest** [comment]
@MaxNoe Not clear what you mean by "actually be fixed". 

The font set used for normal text is necessarily different from the one for MathText. As an example, Comic Sans MS does not have an integral symbol, right? So it makes sense to set both types individually with the respective rcParams.

**Comment by MaxNoe** [comment]
This is changed behaviour compared to previous versions. Math sans text is in itself something very rare and not well supported (E.g. there is no open type math sf font).

But one should have at least have the option to just set a family then for math fonts. E.g. `mathtext.fontfamily: serif`

**Comment by MaxNoe** [comment]
Also, Deja Vu Serif isn't actually a math font. There are very few of those. 

* Latin Modern Math
* Libertinus Math
* Stix Math
* XITS Math
* TeX Gyre {Bonum, Pagella, Schola Termes} Math
* Asana Math
* Cambria Math¹
* Lucida Math¹
* Minion Math¹

¹ commercial or proprietary fonts

None of these is a sans serif font

**Comment by ImportanceOfBeingErnest** [comment]
The font tables for the DejaVu fonts can be found at https://dejavu-fonts.github.io/Samples.html

There are currently 5 supported math fontsets ('dejavusans' (default),  'dejavuserif', 'cm' (Computer Modern), 'stix',  'stixsans'). You are able to select any of those via the `mathtext.fontset` rcParam. Introducing yet another rcParam to automatically choose one of those seems a bit overkill. Plus it would become very intransparent which font is finally used in cases where `mathtext.fontset` and the newly proposed rcParam contradict each other. 

In any case if you feel that [the current documentation](https://matplotlib.org/2.2.2/tutorials/text/mathtext.html) can be improved at any point, people will be happy to hear your suggestions.
