### ISSUE TITLE
Use JPEG format in matplotlib inline

### ISSUE THREAD

**Issue by divamgupta** [matplotlib/matplotlib#8704]
We all love to use matplotlib with a jupyter notebook. 

`
%matplotlib inline
`

But on plt.show() , the image is added to the notebook in a image encoded in PNG format. This makes the .ipynb file very large. How can we use JPEG encoding of the image so that the it doesn't make notebook bulky.

PS : github won't cry when we push the notebook after that.

**Comment by WeatherGod** [comment]
I think this question is for the jupyter people, since they maintain the
inline backend.

**Comment by dstansby** [comment]
I came across this problem last week; can't remember where the StackOverflow question is that answered it for me, but in my code at the top I have

```python
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
```

Change 'svg' to 'jpg' and I think all should work fine. Feel free to re-open if it doesn't.

**Comment by divamgupta** [comment]
Thanks, it worked.
