### ISSUE TITLE
Bug with 3D graphing

### ISSUE THREAD

**Issue by Maxence1402** [matplotlib/matplotlib#8706]
### Bug report

**Bug summary**

I'm trying to plot 3d surfaces, however the given example on the website does not work well at all, see below. It seems like the plotting does not take all the given points...

```
'''
======================
3D surface (color map)
======================

Demonstrates plotting a 3D surface colored with the coolwarm color map.
The surface is made opaque by using antialiased=False.

Also demonstrates using the LinearLocator and custom formatting for the
z axis tick labels.
'''

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import numpy as np


fig = plt.figure()
ax = fig.gca(projection='3d')

# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface.
surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

# Customize the z axis.
ax.set_zlim(-1.01, 1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()
```

**Actual outcome**

[Image here](http://i.imgur.com/o5BhRRh.png)

**Expected outcome**

(http://i.imgur.com/5geshSc.png)

**Matplotlib version**

  * Operating System:Windows 10
  * Matplotlib Version: The latest on June 2nd, 2017 I suppose
  * Python Version: 3.5.1
  * Using Spyder (Anaconda 2.4.1)

**Comment by Maxence1402** [comment]
OK, I checked cstride and rstride and it seems like their default value isn't 1...

**Comment by WeatherGod** [comment]
cstride and rstride are no longer used by default for v2.x. The new ccount
and rcount are used instead. I haven't tried out the example yet, but the
example still builds just fine in the documentation:
http://matplotlib.org/2.0.2/examples/mplot3d/surface3d_demo.html

**Comment by anntzer** [comment]
The docstring of plot_function is a bit confusing (it still indicates that rstride and cstride defaults to 10, which is not really the case anymore (only one of them will default to 10 if only the other is given, otherwise we use rcount/ccount)).

Also, I think the automatic downsampling behavior is unusual enough that this deserves a WARNING entry (https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#other-points-to-keep-in-mind).
