### ISSUE TITLE
Updating MEP22

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8712]
@fariza @tacaswell 

Although I like, in general, the idea of MEP22, there are a number of details that I would like to change.  If we can agree on how to handle them, I would be happy to push the qt implementation.  We'd still need a wx implementation (which would be painful for me to write but I guess I could cargo-cult it if no one else volunteers) and a macos implementation (which I would have no way to work on).

A quick look suggests the following points (I may think of other stuff later):

Suggested changes to MEP22

### Change `_get_cls_to_instantiate`

Edit: Fixed by #20990.

Currently, `backend_tools` defines a `default_tools` dict, which maps tool names to either classes, or names of classes; for the latter, `toolmanager.add_tool` resolves the name in the current module context (e.g., the `'cursor': 'ToolSetCursor'` tool resolves to whatever class is named `ToolSetCursor` in the current backend module).  This looks brittle (e.g., one cannot override a tool that is specified directly as a class in `default_tools`).  Instead, I propose that that `default_tools` simply becomes a list of default tools, that the name becomes a class attribute, and that overrides in backends get specified using a decorator
```
@tools.override(backend="qt5agg")
class ToolX(backend_tools.ToolX):
    ...
```
(possibly stacking decorators if the override applies to multiple backends).  The decorator registers an override for the ancestor class(es), and would store the relevant override information somewhere for later use in `add_tool`.

Possibly, some default tools could be abstract, always requiring the backend to reimplement them, but not erroring if this is not the case (the tool is then just not available).

### Get rid of the `data` kwarg to `Tool.trigger`

AFAICT this kwarg is *only* present so that ZoomTool can pass to RubberbandTool the coordinates where a rubberband needs to be drawn.  I would simply get rid of RubberbandTool and let ZoomTool define the relevant drawing methods as abstract methods that need to be overriden by the individual backends.

### Get rid of the `sender` kwarg to `Tool.trigger`?

(Its purpose is not clear to me, but perhaps I am missing something.)

### Let togglable tools be implemented as contextmanagers (instead of enable/disable)

In general, this helps having to stick a bunch of temporary attributes on the instance to store the state.  The caller code can always call `__enter__` and `__exit__` manually.

### `ToolBase.destroy(self, *args)` should lose the `*args` in the signature

Edit: Fixed by #22509.

Why do we need it?

### What is happening with NavigationBase?

The class does not seem to be implemented anywhere.  A similar but not identical API seems implemented by ToolManager.

### Support sub-tools as menus to the tool button?

Edit: Essentially fixed (from my POV) by figure.hooks.

e.g. https://github.com/matplotlib/matplotlib/pull/7696#issuecomment-306069093

**Comment by fariza** [comment]
@OceanWolf  (cc)

@anntzer  Thanks for the comments you point out some things that I have thinking about for some time.

Before getting into details, I want to remind everybody that we are waiting for resolution of MEP27. 
Among other things, MEP27 brings generic windows and filechooser using those the amount of tools have to be implemented for each backend is reduced to 1 (cursor) and if we move the `set_cursor` isnside MEP27 all the default tools can be backend independent.

Regarding your comments

**Change _get_cls_to_instantiate**
I agree with you that this is not the best way to do it and it need improvement. 
Maybe I'm missing something, I find your solution a little bit too complex. 
One of the goals was to make all backends the same, so the user experience doesn't change from one to another that is why only the tools that are available for all backends are default tools. 
Let's define goals for the default tools and how do we want to control what gets instantiated (control by the user), then we can discuss implementation details


**Get rid of the data kwarg to Tool.trigger**
I have to double check if `data` isn't used anywhere else. I like the idea to be able to pass some data to the tools at trigger time but please share your thoughts regarding this.
On the side of the `RubberBand` and `ZoomTool` If you move the drawing methods inside `ZoomTool` then nobody else can use the ruberband, If I'm not wrong that was one point brought to us during development, but if there is no oposition, why not.

**Get rid of the sender kwarg to Tool.trigger**
If I am not wrong (maybe I am) this was introduced to prevent "re-trigger" the tool by itself, as some tools trigger other tools. Needs to be checked carefuly but I like the thought of getting rid of that.

**ToolBase.destroy(self, *args) should lose the *args in the signature**
I don't see the `*args` in the signature https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_tools.py#L135

**What is happening with NavigationBase?**
I don't see this class?

**Support sub-tools as menus to the tool button?**
I like the idea, we were looking for "context menu" or something similar. Are you suggesting as `tool` or as `tool modifier/configuration`

**Comment by anntzer** [comment]
The comments are regarding https://matplotlib.org/devdocs/devel/MEP/MEP22.html, not the actual implementation.  If things changed (e.g. for ToolBase.destroy's signature, and NavigationBase), let's update the MEP.

Regarding _get_cls_to_instantiate, I can try to implement something and we can then see whether it's too complicated :-)

If we want to make rubberbanding reusable, I'd just make it a free function.  Trying to make it a Tool feels like shoehorning it into the wrong API.

Do you have an actual example of problems with retriggering?  I see your point, but let's not overengineer things too.

No great idea yet as of a possible sub-tool API.

**Comment by OceanWolf** [comment]
Hi @anntzer, I already made branches for all the existing backends (apart from the mac backend(s) and GTK2, and NbAgg) for MEP27, I will need to tweak them a bit as we have slightly changed the API since I created those branches, but a lot of the work has already been done.  I should become free to take a look at this closer in a week or two.

Oh, and yes ``NavigationBase`` got changed to ``ToolManager`` during the long PR review phase of the first MEP22 PR that made it to trunk.

**Comment by anntzer** [comment]
I am totally not familiar with MEP27, so I'll need to review it carefully.  Should it go before or after MEP22?

Note that Qt also has the "edit axes curves and image parameters" tool which should definitely be kept by default, but until someone implements a formlayout-like API (... or just reimplements the whole tool) for other backends it's going to be tough to provide it for other backends as well (see also discussion at https://github.com/matplotlib/matplotlib/issues/1543).

**Comment by OceanWolf** [comment]
Logically MEP27 goes before MEP22 as a more fundamental API as it refactors ``FigureManager`` and abstracts a lot of backend concepts (see http://matplotlib.org/devel/MEP/MEP27.html); in terms of timeline though it goes the other way around with MEP22 inspiring MEP27 and superseded another refactor that Tom was working on.  This has meant that MEP27 refactors the MEP22 code a bit (although no changes to API).

**Comment by fariza** [comment]
@anntzer I just updated https://github.com/matplotlib/matplotlib/pull/4889 trying to reflect the current state of affairs.
I prefer to direct users to the documentation, in principle it is more updated than the MEP document
* https://matplotlib.org/api/backend_managers_api.html#module-matplotlib.backend_managers
* https://matplotlib.org/api/backend_tools_api.html#module-matplotlib.backend_tools
* https://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.ToolContainerBase
* https://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.StatusbarBase

**Comment by fariza** [comment]
@anntzer 
 **Get rid of the sender kwarg to Tool.trigger**
If a tool needs access to a widgetlock, it needs the the sender to be the owner of the widgetlock
Currently it is only used by the rubberband.
This decision is delayed until we agree on rubberband future

**Comment by fariza** [comment]
@anntzer 
**Change _get_cls_to_instantiate**
I don't fully understand what you mean, do you have a little sample code as reference?

**Comment by anntzer** [comment]
@fariza see #9941.  Of course the other points raised originally still remain.

**Comment by anntzer** [comment]
Also, is ToolManager supposed to keep a ref to a FigureManager object?  Its docstring says yes, but in practice it only has a ref to the Figure itself.
In other words, is ToolManager supposed to work with non-FigureManaged Figures?  If yes, then the docstring should be updated; if not, then perhaps it should take the FigureManager as argument in the ctor rather than the figure.

**Comment by fariza** [comment]
I agree, the problem is in the doc. I'll fix it

**Comment by fariza** [comment]
@anntzer docstring fixed in https://github.com/matplotlib/matplotlib/pull/9949

**Comment by anntzer** [comment]
So it's supposed to work with nonFigureManaged figures?

**Comment by fariza** [comment]
The idea is to be able to change the figure. The figuremanager has only one figure and is not really needed, so why keep it?

**Comment by anntzer** [comment]
You want to be able to reassign the figure a ToolManager manages?  what for?

**Comment by fariza** [comment]
My master plan (after that I can die happy), https://github.com/fariza/tabbed_backend
It is a MultiFigureManager where I group several figures into the same FigureManager
![screenshot from 2017-12-06 13-55-04](https://user-images.githubusercontent.com/1490153/33679559-18689cfa-da8d-11e7-8dc2-186b132517fd.png)

**Comment by OceanWolf** [comment]
Also for embedded applications in general whereby the user might want to use our figure and toolbar, but embed them into their own bespoke interface rather than our ``FigureManager``.

For me the beauty in this design lies in its flexibility.  I don't see that we need to have a reason for why we make it loose and flexible.  The goal lies in making it as fluidic as possible and allow the users to answer the question "what for?".

**Comment by anntzer** [comment]
Actually I'll take back what I said: allowing tools to manage multiple figures at once just makes everything needlessly complicated (see e.g. the dance around togglable tools); for the tabbed case you should just attach one separate toolbar to each notebook pane.

@OceanWolf the ultimate fluidity is of course to directly write against the underlying GUI toolkit, there isn't much of a point of trying to reproduce all the bells and whistles of {qt+gtk+wx+tk} using our own API...

**Comment by fariza** [comment]
@anntzer I guess you never tried doing what you are proposing.
I did it (several times) and it doesn't really work that well, you still need all the toggle/untoggle and extra magic.
For example, if you toggle the PAN tool, and you change figures (by tab selection), you expect the PAN tool to be toggled.
If you add or remove one tool, you have to do it for all the toolbars, not just the one that is visible.
If you want to have a tool that do something with all the figures (save all figures comes to mind), it is better if you have just one toolbar.

**Comment by jklymak** [comment]
I don't expect the GUI state to stay the say from tab to tab in the applications I work with.  i.e. I would not expect zoom selected in one tab to be selected if I move to a different tab.  I may expect it to be selected if I come back to the original tab. 

I'm not particularly sure what the advantage of a tabbed interface is.  If I have more than one plot popped up at a time, I usually want to compare them, which tabbing does not allow. Most widow managers have keyboard shortcuts for next-window, so running through open windows is relatively painless.

**Comment by fariza** [comment]
@anntzer Normally what I do, is to associate the toolbar with the "Window"  not the figure, I think it just makes more sense. And the window keep track of what figures are inside (notebook, select, etc..). So everything works the same, doesn't matter if you have one or more figures in the window.

@jklymak In my work, when I am analyzing results, normally I have 15 figures open for each result (EMVA1288 camera characterization tests), I normally don't want to compare between the figures of the same test, I want to compare the same figure within different tests, so if I have 30 open plots, it becomes really difficult to find the right ones.
With the tabbed approach, I have two windows (each with 15 figures), and I can easily select the right ones.

> Most widow managers have keyboard shortcuts for next-window, so running through open windows is relatively painless

Do you remember the days when web browsers didn't use tabs?

I have a hackish GTK3 implementation in https://github.com/fariza/tabbed_backend it is broken right now (some recent changes in mpl, pushing that on my todo;) ) 

This implementation, allows to grammatically detach a figure from a window into a new one or into an  existing one. So you you can reorganize figures

**Comment by anntzer** [comment]
Taking the example of webbrowsers: note that at least chrome and firefox put the forward/backward buttons *inside* the tabs, not outside.  Because that's where they logically belong...

**Comment by anntzer** [comment]
Indeed, that's completely straightforward:
```
from PyQt5.QtWidgets import *
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT
from matplotlib.figure import Figure

qapp = QApplication([])

win = QMainWindow()
tw = QTabWidget()
win.setCentralWidget(tw)

def add_page(tabname, fig):
    widget = QWidget()
    layout = QVBoxLayout()
    widget.setLayout(layout)
    canvas = FigureCanvasQTAgg(fig)
    navbar = NavigationToolbar2QT(canvas, None)
    layout.addWidget(navbar)
    layout.addWidget(canvas)
    tw.addTab(widget, tabname)

fig = Figure(); add_page("tab1", fig)
fig.subplots().plot([0, 1])

fig = Figure(); add_page("tab2", fig)
fig.subplots().plot([1, 0])

win.show()
qapp.exec_()
```
(probably the same with toolmanager).

**Comment by OceanWolf** [comment]
Personally I hated when firefox moved the search from window to tab, when I switch tabs  I want to continue to use the same tool I was just using, as a power uses, I want to switch back and forth between tabs and not think about what tools I have selected, I just want to use.  That said, I think an easy compromise solution exists, allow for both, give that freedom and flexibility to the user, different people work in different ways, and sometimes the same person will want to use both methods.

> the ultimate fluidity is of course to directly write against the underlying GUI toolkit, there isn't much of a point of trying to reproduce all the bells and whistles of {qt+gtk+wx+tk} using our own API...

@anntzer I don't understand your argument, the option to write directly against the underlying GUI toolkit already exists, see the Qt figure options dialog ``matplotlib.backends.qt_editor.figureoptions``  We also have our own MPL GUI toolkit located in ``matplotlib.widgets`` which the Configure Subplots tool uses.

But yeah, I don't see the problem of classes doing too much so long as the API remains clear.

**Comment by anntzer** [comment]
The argument is the following: MEP22 proposes to add hundreds of lines of code in order to "make it easier to modify (add, change, remove) the way the user interacts with the figures" (quoting from the MEP text).  I showed above that the tabbed browser proposed by @fariza can be implemented, without relying on MEP22, in just a few dozen lines of code.  If you *really* want the same tool to be active across all figures, you can easily add a connection system that triggers the sibling tools (on the other toolbars) when one is triggered -- I bet this would still be shorter than the figure-resetting machinery that we have.  What kind of examples do you have, that is overly difficult to do today, but that MEP22 makes easier (for that, there are things I can think of)?  What kind of examples, in particular, rely on the ability of a tool to change its controlling figure?

I do not buy the argument that "it doesn't matter what people do with it, it's great that we give them the option to play with it".  I could also PR all my random personal stuff to Matplotlib on the basis that "hey, it was useful for me, perhaps it'll be useful for someone else".  We have to be just a bit selective, otherwise the maintenance overhead quickly grows out of control.

**Comment by OceanWolf** [comment]
I don't know about MEP22 adding hundreds of lines of code, it may even reduce lines of code and definitely in connection with MEP27, at least in the long run once we have applied it to all backends and deprecated and removed all of the old lines of code.

MEP22 adds the functionality to easily create tools (both for MPL developers) and for users, at the moment by creating an API for tools and their addition and removal to the figure.

The difference as I see it between what I suggest and you PRing all of your useful stuff lies in making sure we create an API framework that does not prevent other people from making their own useful stuff. don't give users stuff that they cannot extend.  The difference lies between "should I PR my cool code to MPL" and "should I create a separate repository for my cool code".    Right now, without MEP22, trying to write my own tools becomes an ugly hackfest, as coders, we should encourage good coding rather than force people to use ugly hacking that takes extra work to learn how to do and implement, and then even more work to maintain because you hack private variables, etcetera.

So yeah, MEP22 refactors the unyieldly tool mess in MPL to make it easy for end users to create their own tools, and for us MPL developers to more easily understand what goes on and change it in a Backwards Compatible way.

**Comment by fariza** [comment]
@anntzer why do you insist on mixing the MEP22, the tools and tool manager with the idea of tabbed figure manager? 
If you don't like my idea of tabbed figure manager you just have to oppose to MEP23 and whatever PR comes from there.

The figure swapping ability is not hundreds of lines of code. 
Who else uses it? I don't know (but the same can be said about all the new stuff and some old things too)?
 If it is a really useless feature it will be removed eventually. I think that we have better things to do than fight over a feature that is not bothering anyone.

**Comment by anntzer** [comment]
What is hundreds of lines of code is the toolmanager+tool implementation, which is what I mean by MEP22 (which is after all the MEP that proposes the tool API).
The only reason I use the tabbed manager in the API is because I asked "why does the implementation of tools support reassigning figures?" and the answer you gave me was https://github.com/matplotlib/matplotlib/issues/8712#issuecomment-349738867.  It is at least bothering me, because it means (for example) that correct (reusable) tool implementations will need to support figure reassignment, which most won't or will add complexity to the tool implementation (see, for example, the zoom/pan tools, which end up storing a mapping of weakrefs to figures to their positions stacks, instead of just storing a single instance variable).

Will the new API make things shorter once the previous implementation is removed?  Perhaps, I cannot tell.

**Comment by timhoffm** [comment]
If one really wants reassignment, the correct way would be a model-view concept. The model would stay associated with a single figure and we only reassign the model for the UI elements. This is definitively better than storing mappings of weakrefs. However, I'm not convinced that that the added complexity is worth it.

**Comment by fariza** [comment]
@timhoffm I could say the same about many things that I don't use (that is not worth it). I agree that there is added complexity but I am pretty sure it won't present a problem for most new tools.

@anntzer please take your dozen lines and try to use it with several figures (real life) not just to test.
- Don't you find annoying that the state of the Pan/Zoom button is not persistent across tabs?
- Don't you find annoying that you have several instances of the Toolbar?
- If you open the "configure subplots" it doesn't let you change tabs.
  - Some backends will let you change tabs because that sub-window is implemented as a window and not as a dialog (it is like that and I wasn't there, so not my decision/fault)
  - Imagine for a second that it does let you change tabs. So wouldn't it make sense to refresh the content of that sub-window based on the figure?
- Don't you want to move that toolbar somewhere else that is not inside the tab? why? why not?
- Forget tabs, what if you change the figure programatically without changing windows?

I use that feature. And I can say that everybody inside my team (at work) uses that feature. And the feedback that I got from them, was that indeed I needed to make the toolbar state follow the figure. 
My first implementation was as simple as yours, but it wasn't enough for our use.

Why is that particular feature bothering you so much? Are you trying to implement a tool that got too complex because of that?

**Comment by OceanWolf** [comment]
Ahh, okay, I get you on figure reassignment within user created tools as that passes on complexity for the end user, but I counter that by saying tools shouldn't store such data anyway, think of tools we use in real life, like a knife, or a hammer, or a screwdriver, do these items store state?  No, because they exist as tools, tools don't store state.  You pick up the tool you want for a job and expect it to work just the same the last time you picked it up (I remember having a similar debate with @fariza way back when).

This follows through to tools here, if something should keep state, like history, then that should probably get stored either on the figure or on the figure manager, not as part of the tools or toolbar.  Stepping aside to the multifigure thing, I guess such logic could get implemented there for tracking state?  Otherwise that means that tabbing from one figure to the next would permanently erase the history stacks which makes this feature pointless if you tab a lot.

**Comment by anntzer** [comment]
@fariza I will give it a try once your tabbed_backend is back in a working state (or you can just tell me what version of matplotlib it is compatible with).  I won't compare my implementation with... stuff I can't compare with.

**Comment by jklymak** [comment]
@fariza what is the line that you envision between this work and a full-fledged GUI application built using a GUI toolkit and Matplotlib as the plotting engine?  I think we should be clear on that line...  

I personally appreciate the tools on the current interactive backends, and I see a value in allowing users to create new lightweight tools that suit their needs.  But I am leery of mission creep.

**Comment by anntzer** [comment]
@OceanWolf that state is *already* stored on the figure (that's how the pre-toolmanager nav buttons work, after all).

**Comment by anntzer** [comment]
Ah, I realized that tabeed_backend does work with 2.2, not master.  So I gave it a try.

> Don't you find annoying that the state of the Pan/Zoom button is not persistent across tabs?

... no, I just press "O" or "P" and trigger the tool I want (well in the example I gave you need to connect the global key_press_handler, but again that's one line that's standard)

> Don't you find annoying that you have several instances of the Toolbar?

How does that affect the end user in *any* way?

> If you open the "configure subplots" it doesn't let you change tabs.
> Some backends will let you change tabs because that sub-window is implemented as a window and not as a dialog (it is like that and I wasn't there, so not my decision/fault)
> Imagine for a second that it does let you change tabs. So wouldn't it make sense to refresh the content of that sub-window based on the figure?

The tabbed backend doesn't refresh that content either.

> Don't you want to move that toolbar somewhere else that is not inside the tab? why? why not?

... no?  why would I?  but note that it's just a boring regular old widget anyways, you can indeed add it anywhere you want.  If you really want it outside of the tab, you can use a QStackedWidget (http://doc.qt.io/qt-5/qstackedwidget.html) and switch the "real" toolbar depending on the tab that's active -- see e.g. the figureoptions editor for something similar (there's one form per artist, that get switched based on the artist combobox).

> Forget tabs, what if you change the figure programatically without changing windows?

The toolbar is attached to the canvas, not to the figure, so it doesn't matter.

**Comment by OceanWolf** [comment]
>> Don't you find annoying that the state of the Pan/Zoom button is not persistent across tabs?

> ... no, I just press "O" or "P" and trigger the tool I want (well in the example I gave you need to connect the global key_press_handler, but again that's one line that's standard)

You say that now, but what about switching between hundreds of figures as a power user, it can get quite annoying and proves a disruption in the thought process.  Maybe you don't find it a problem, but why deprive that for others who do?  This comes back to my point about fluidity earlier, about making code that's reusable and adaptable, that seems the quintessential function of a library, if we don't matplobLib doesn't live up to its name.  It doesn't take too much work to allow the user to choose whether they want to lock the tool state when changing tabs or keep them the same, anyway we digress as we talk about a different MEP, and now I wonder if the multitab MEP should exist as a separate package or not... but that exists as a separate discussion, the point here exists as to why we as a library we should force other people to do it a certain way creating their own packages extending our own.

@fariza Was there a reason why the pan/zoom history was moved to the tool and taken away from the figure?

**Comment by anntzer** [comment]
@OceanWolf It is not difficult to keep actions in sync across toolbars -- just connect the relevant event handlers.  Extending on my earlier example:

```
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from matplotlib.backend_bases import key_press_handler
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT
from matplotlib.figure import Figure

qapp = QApplication([])

win = QMainWindow()
tw = QTabWidget()
win.setCentralWidget(tw)

# Yeah, globals are ugly, just imagine this is stored in whatever relevant manager object.
_actions_sync = []

def add_page(tabname, fig):
    widget = QWidget()
    layout = QVBoxLayout()
    widget.setLayout(layout)
    canvas = FigureCanvasQTAgg(fig)
    canvas.setFocusPolicy(Qt.StrongFocus)
    canvas.setFocus()
    navbar = NavigationToolbar2QT(canvas, None)

    checkable_actions = {action.text(): action for action in navbar.actions()
                         if action.isCheckable()}
    _actions_sync.append(checkable_actions)
    for action in checkable_actions.values():
        @action.toggled.connect
        def sync_actions(state, *, action=action):
            for checkable_actions in _actions_sync:
                sibling = checkable_actions[action.text()]
                if sibling.isChecked() == state:  # Don't recurse.
                    continue
                sibling.trigger()

    layout.addWidget(navbar)
    layout.addWidget(canvas)
    tw.addTab(widget, tabname)
    canvas.mpl_connect(
        "key_press_event",
        lambda event: key_press_handler(event, canvas, navbar))

fig = Figure(); add_page("tab1", fig)
fig.subplots().plot([0, 1])

fig = Figure(); add_page("tab2", fig)
fig.subplots().plot([1, 0])


win.show()
qapp.exec_()
```

Again, note that this would work even if you decide that after all you want multiple windows instead of just one, which is not the case for the current toolmanager implementation.  So in a sense it is the toolmanager implementation that "force other people to do it a certain way creating their own packages extending our own" rather than letting them use standard APIs.

**Comment by anntzer** [comment]
> The figure and the canvas are interconnected, so why does it matter if the toolbar is attached to one or the other?

Because you can reassign them in either direction.  For example that's actually how saving to pdf works... (the figure is reparented to a pdf canvas.)

Indeed the _nav_stack is in the toolbar, I was wrong and stand corrected.  What I meant, however, was that it was stored on a global object that is associated to the figure (it could just as well be stored in the figure, a PR doing so would just be moving it from A to B), not on reparentable objects.

Note that I am not saying that MEP22 should be thrown out of the window.  Yes, the ability to reuse e.g. zoom/pan in a pluggable fashion is nice.  The *only* thing we're discussing in this subdiscussion is whether tools need to be reparentable or not...

**Comment by OceanWolf** [comment]
> So in a sense it is the toolmanager implementation that "force other people to do it a certain way creating their own packages extending our own" rather than letting them use standard APIs.

I don't see how making tools reparentable forces other people to reparent them.

I will need to take some time to think through this properly though, time I do not currently have...

**Comment by anntzer** [comment]
I think the important parts have been fixed and the rest is just small API tweaks, which are not so crucial.
