### ISSUE TITLE
Bug in the HiDPI support in the qt5agg backend

### ISSUE THREAD

**Issue by djpine** [matplotlib/matplotlib#8717]
### Bug report

**Bug summary**

The interactive plot window is too small, but the text remains at the size that would be correct for a larger properly sized window.

It works if you go through pyplot:

```python
fig, ax = plt.subplots(figsize=(6,4))
ax.plot([1,2,3])
```
but not in this example, which uses the pure OO interface.

The version of the plot saved to the file text.pdf is correctly sized.

**Code for reproduction**

```python
from matplotlib.backends.backend_qt5agg \
     import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

fig = Figure(figsize=(6, 4))
canvas = FigureCanvas(fig)
ax = fig.add_subplot(111)
ax.plot([1, 2, 3, 2, 3, 4, 3, 4, 5])
ax.set_title('A simple plot')
ax.grid(True)
ax.set_xlabel('time')
ax.set_ylabel('volts')
canvas.print_figure('test.pdf')
canvas.show()
```

**Actual outcome**

<img width="412" alt="screen shot 2017-06-04 at 2 43 05 pm" src="https://cloud.githubusercontent.com/assets/3291641/26764417/984cfeec-4934-11e7-82cc-c67caa45a794.png">

**Expected outcome**

![screen shot 2017-06-04 at 2 52 48 pm](https://cloud.githubusercontent.com/assets/3291641/26764486/a5cf535c-4935-11e7-935f-e95ff8575d07.png)

**Matplotlib version**

  * Operating System: MacOS Sierra 10.12.5
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Jupyter Version (if applicable):
  * Other Libraries: 

 
 
Installed with conda (default)

**Comment by tacaswell** [comment]
:disappointed: I thought we had this sorted out.

There is a bunch of jiggery-pokery to double the DPI under the hood.  Does it help if you set the figure size after your create and add the canvas?

attn @efiring

**Comment by djpine** [comment]
Nope.  Putting

fig.set_size_inches(6, 4)


at different places after setting the canvas in the code doesn't make a
difference.



____________________________________________________________________________
______

David Pine
New York University
Silver Professor
Chair, Department of Chemical & Biomolecular Engineering
    NYU Tandon School of Engineering
Professor of Physics
    NYU College of Arts & Science
Office (Brooklyn):158 Jacobs Administration Building [6 MetroTech Center,
Brooklyn, New York 11201]
Office (Manhattan): Room 883 [726 Broadway, New York, NY 10003]
Tel:  646-997-3004 (Brooklyn)
Tel:  212-998-7744 (Manhattan)
Web: http://www.physics.nyu.edu/pine/Home.html
E-mail:  pine@nyu.edu
____________________________________________________________________
______________

**Comment by QuLogic** [comment]
The `FigureCanvas` sets a (non-binding) `sizeHint`; the `FigureManager` takes the hint + the toolbar size and sets the window to the correct size. I think if you want to use the canvas directly, you'll need to read the size and set it as a hard requirement, or maybe set the QSizePolicy to require the hinted size.
