### ISSUE TITLE
tick labels should have `horizontalalignment='right'` even if `set_ticks_position(right)` is used.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#8731]
Sorry if this is a duplicate, but I didn't find anything...

Why does: 
`ax.xaxis.set_ticks_position('right')` set`horizontalignment = 'left'` for the tick labels?

```
fig,ax=plt.subplots()
ax.plot(np.arange(-10,10))
ax.yaxis.set_ticks_position('right')
```
I'm not clear on why the ticks should change their horizontal alignment based on what side of the axis they are displayed on.  I can *imagine* a technical difficulty in guessing how large the label is before it is drawn.  Is this a layout manager issue?    

Most importantly for me, it makes colorbars look poor if they have negative values, and require a manual twiddle to make look good.

**Comment by tacaswell** [comment]
That is exactly the issue.  You can get what you want if you set both the alignment and a large pad (see https://stackoverflow.com/questions/15882249/matplotlib-aligning-y-ticks-to-the-left but do it backwards).

Another way around this is to modify the formatter to left-pad with spaces (and use a monospace font).

**Comment by jklymak** [comment]
I had thought about padding on the left, but I hadn't thought about using monospace fonts.  The bonus of your solution is that I get that retro pen-plotter-produced look.

**Comment by jklymak** [comment]
I'm closing this, because I don't think there is an easy way to fix it (short of a contraints based layout engine), and the workarounds noted above work for me.
