### ISSUE TITLE
http://matplotlib.org/devdocs/{examples,gallery} point to old builds of the old examples/gallery folder

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8742]
All's in the title: compare
http://matplotlib.org/devdocs/examples/
https://matplotlib.org/devdocs/gallery/
https://matplotlib.org/devdocs/gallery/index.html

**Comment by QuLogic** [comment]
I deleted the extraneous files from the `devdocs` repo and the new CircleCI build should also delete any files from the repo that were removed from the build.
