### ISSUE TITLE
Plotted lines not symmetrical

### ISSUE THREAD

**Issue by endolith** [matplotlib/matplotlib#8746]
### Bug report

**Bug summary**

I tried to reproduce [this figure](https://commons.wikimedia.org/wiki/File:Discrete_Gaussians.svg), but when I plotted using lines and dots, the dots are in the correct place, but the lines are slightly out of place, making things asymmetrical.

**Code for reproduction**

```python
from scipy.special import iv
import numpy as np


def discrete_gaussian_kernel(n, t):
    T = np.exp(-t) * iv(n, t)
    return T


def sampled_gaussian_kernel(n, t):
    G = 1/np.sqrt(2*np.pi*t) * np.exp(-n**2/(2*t))
    return G

if __name__ == '__main__':
    import matplotlib.pyplot as plt

    plt.figure(figsize=(4, 5))
    for t in (0.5, 1, 2, 4):
        N = 6
        n = np.arange(-N, N+1)
        p = plt.plot(n, discrete_gaussian_kernel(n, t),  '.-', label=t)[0]
        plt.plot(n, sampled_gaussian_kernel(n, t),  ':', color=p.get_color())
    plt.grid(True)
    plt.ylim(0, 0.7)
    plt.xlim(-6, 6)
    plt.legend()
```

**Actual outcome**

![figure_1](https://user-images.githubusercontent.com/58611/27012691-e24ea298-4ea2-11e7-8d62-a8911911a0e1.png)

The dots look offset on the legend:

![2017-06-11 12_41_54- figure_1 imported -1 0 rgb color 1 layer 400x496 gimp](https://user-images.githubusercontent.com/58611/27012712-6b0e3ee0-4ea3-11e7-9135-1ecda9104722.png)

But I guess it's actually the lines that are offset and asymmetrical:

![asymmetrical](https://user-images.githubusercontent.com/58611/27012713-75830a9a-4ea3-11e7-82ef-163eb3ae09bc.png)

**Expected outcome**

If I save as SVG and open in Firefox, it looks fine:

![svg in firefox](https://user-images.githubusercontent.com/58611/27012701-32cdc3a2-4ea3-11e7-8b1e-c7f6df26d73c.png)

![firefox dot](https://user-images.githubusercontent.com/58611/27012724-d24ebc10-4ea3-11e7-9591-29d49fa63c38.png)

![firefox symmetry](https://user-images.githubusercontent.com/58611/27012725-d556215a-4ea3-11e7-82a1-c29c1b4125ee.png)

**Matplotlib version**

  * Operating System: Windows 7 Pro 64-bit
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.0
  * Jupyter Version (if applicable): IPython 5.1.0 

This is inside Spyder 3.1.4 installed from default Anaconda channel, with graphics backend set to "automatic":

![2017-06-11 12_51_28-preferences](https://user-images.githubusercontent.com/58611/27012759-d87c29e6-4ea4-11e7-9f00-74f51fd41264.png)

**Comment by tacaswell** [comment]
Turning the DPI up to 100 will help.

This is a feature of the Agg backend which will 'snap' to the nearest pixel which makes the lines look 'sharper' assuming that 1 pixel is very small.  This has been the behavior of the Agg backend for a while but it is getting noticed a lot more recently (not sure if it is all the high-dpi screens leading to more up-sampling or the larger defaults making it more obvious).

**Comment by endolith** [comment]
Is there a way to turn this feature off?  Changing the DPI in the settings of Spyder doesn't fix the interactive display.

**Comment by anntzer** [comment]
The gtk3cairo (any cairo backend, I guess) backend does not suffer from this issue.  I have been thinking of refactoring the backends so that one could also have {qt{4,5},wx,tk}cairo backends with minimal effort...

**Comment by tacaswell** [comment]
Digging into this is on my 'few days of work' project list...

Setting the `path.snap` rcparam to False make help (but I have not tested).

**Comment by anntzer** [comment]
path.snap = false does not help.
I have a working qtcairo backend, will make a PR soon.

**Comment by anntzer** [comment]
Closing as a duplicate of #7233, I think.
