### ISSUE TITLE
Use of recent Miktex version (2.9.6350) with Matplotlib --> "tex not found"

### ISSUE THREAD

**Issue by Lolbaer** [matplotlib/matplotlib#8748]
### Bug report

**Bug summary**

During use of Miktex (v2.9.6350) together with Python (v2.7) and Matplotlib (v2) on Windows 10, Matplotlib checks for the installed Tex version during initialization via the "tex -version" command. The command line call "tex -version" hands back only the Miktex version (in previous Miktex versions it handed back Miktex AND Tex version) which leads to Matplotlib thinking that the installed Tex version is outdated (it simply checks for the number 3.1). 

The result is that when "text.usetex" = True in the matplotlibrc file, Matplotlib issues a warning during initialization as it cannot find an update tex version. Setting "text.usetex" = True with dynamic rc settings works fine as no check for a current tex version is performed.

> C:\ProgramData\Anaconda2\lib\site-packages\matplotlib\__init__.py:513: UserWarning: matplotlibrc text.usetex option can not be used unless TeX-3.1415 or later is installed on your system

**Comment by anntzer** [comment]
What's the output of `tex -version` on your system?  We can probably adapt the test accordingly.

**Comment by Lolbaer** [comment]
`C:\Users\loren>tex -version
MiKTeX-TeX  (MiKTeX 2.9.6350 64-bit)

using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.54.0; using libcurl/7.54.0 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with liblzma version 50020032; using 50020032
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 1.6334; using 1.6334
compiled with MiKTeX Core version 1.6344; using 1.6344
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 1.6353; using 1.6353
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11`

**Comment by anntzer** [comment]
Thanks.  Would it be reasonably easy for you to install old versions and give us the corresponding outputs too?  (We may as well try to make this robust.)

**Comment by Lolbaer** [comment]
I will do so tomorrow. Thank you for your support. Best, L.

**Comment by phobson** [comment]
@anntzer 

I've got an older MikTex on my work machine, here's what I get:

```
(ssfl) C:\Users\phobson\sources
λ tex -version
MiKTeX-TeX 2.9.5800 (3.14159265) (MiKTeX 2.9 64-bit)
Copyright (C) 1982 by D. E. Knuth; all rights are reserved.
TeX is a trademark of the American Mathematical Society.
```

**Comment by tacaswell** [comment]
Reported upstream as https://sourceforge.net/p/miktex/bugs/2607/

**Comment by anntzer** [comment]
Given that version 3.14159 was released in 1995(!) (http://tex.loria.fr/historique/TeX1995-announcement -- I could not, in fact, find a release announcement for 3.1415, which is the minimal version that checkdep_usetex announces), I think it is safe to assume that there is probably no system that runs both tex<=3.141 and mpl2.1 (unless you REALLY do it on purpose), so I think we should just drop the version check.

**Comment by tacaswell** [comment]
In that case :+1:  to dropping the version check

**Comment by Lolbaer** [comment]
Removing the check sounds good to me. Let me know when you have a new version, then I am happy to test :)
