### ISSUE TITLE
Replace "jet" as the default colormap

### ISSUE THREAD

**Issue by endolith** [matplotlib/matplotlib#875]
This is subjective: a matter of sane defaults vs consistency with matlab, but here are the arguments against `jet` as default:

[Rainbow Color Map (Still) Considered Harmful](http://www.jwave.vt.edu/~rkriz/Projects/create_color_table/color_07.pdf):
> Research has shown that the rainbow color map is rarely the optimal choice when displaying data with a pseudocolor map. The rainbow color map confuses viewers through its lack of perceptual ordering, obscures data through its uncontrolled luminance variation, and actively misleads interpretation through the introduction of non-data-dependent gradients.

> Despite much published research on its deficiencies the rainbow color map is prevalent in the visualization community. We present survey results showing that the rainbow color map continues to appear in more than half of the relevant papers in IEEE Visualization Conference proceedings; for example, it appeared on 61 pages in 2005. **Its use is encouraged by its selection as the default color map used in most visualization toolkits** that we inspected. The visualization community must do better.
> ...
> In the absence of feedback about the data or task, the best approach for situations where color is the only display technique is **probably the black-body radiation spectrum**, because of its perceptual ordering and use of color to avoid contrast effects.

So this would presumably mean using one of `hot`, `afmhot`, or `gist_heat` as the default colormap:

![hot, afmhot, and gist_heat](http://i.imgur.com/cMBwG.png)

[How NOT to Lie with Visualization](http://www.research.ibm.com/dx/proceedings/pravda/truevis.htm):
> This rainbow hue colormap is widely used in visualization, but produces several well-documented artifacts (e.g., Lefkowitz and Herman [1992]; Robertson [1988]; Rogowitz, Ling and Kellogg [1992]). In this MRI image, for example, the colormap creates perceived contours which do not reflect discrete transitions in the data, structures in the data which fall within one of these artificial bands are not represented, and attention is drawn to the yellow areas because they are the brightest, not because they are in any way the most important.

[Let’s talk colormaps](https://abandonmatlab.wordpress.com/2011/05/07/lets-talk-colormaps/):
> What kind of insane colormap has the property that values spanning the extreme ends of the scale stand out less, and can’t be distinguished as easily as values in the noisy middle? Why, it’s MATLAB’s default colormap, of course!

[The 'jet' colormap must die!](http://cresspahl.blogspot.com/2012/03/expanded-control-of-octaves-colormap.html):
> The main issue here is that in grayscale representation, information about the 'height' of map regions gets lost. The center of the plot (where the highest intensity is found) has the same gray value as the border regions.

**Comment by ivanov** [comment]
Here's a [recent discussion on the mailing lists](http://matplotlib.1069221.n5.nabble.com/RFC-candidates-for-a-new-default-colormap-td45652.html) about this, with a [proposal](http://bids.github.io/colormap/)

**Comment by WeatherGod** [comment]
Paul, this is fantastic! A nice, well-organized page showing the three
proposed colormaps and a common set of graphs for each. We should get this
out onto the user list.

**Comment by tacaswell** [comment]
@njsmith Can that page get integrated with/replace https://github.com/matplotlib/matplotlib/blob/color_overhaul/doc/devel/color_changes.rst so we have a record in the docs?

**Comment by wernight** [comment]
Would be nice to add also some of the alternatives on http://bids.github.io/colormap/ to matplotlib.

**Comment by njsmith** [comment]
Yep, that's the plan.

On Wed, Jul 15, 2015 at 3:22 AM, Werner Beroux <notifications@github.com>
wrote:

> Would be nice to add also some of the alternatives on
> http://bids.github.io/colormap/ to matplotlib.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/875#issuecomment-121526766>
> .
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by tacaswell** [comment]
There is a discussion over names happening in a scikit-image PR thread (
https://github.com/scikit-image/scikit-image/pull/1599)

There is a proposal for naming options A-C as {'ignis', 'ortus', 'fyrian'}
in some order.

Commenting here and copying the devel list so it gets some visibility.

**Comment by scottsievert** [comment]
In [the proposal], what's the motivation for using XYZ colorspace instead of the Lab colorspace (like Matlab) when calculating perceptual differences?

This question is motivated by [Matlab's review of rainbow colorspaces]. This includes

> ##### Color Map Construction Principles
Use these guidelines for building effective color maps:
* Construct a perceptual color map by using smooth, equal-step interpolation in a **perceptually uniform color space such as L\*a\*b***.
* Use monotonic lightness (L*) to achieve perceptual ordering and assist color-impaired viewers.
* Do not use lightness variation alone because of the problem of simultaneous contrast. Use hue or saturation variation in addition to lightness variation. (Hue variation can also improve the attractiveness of a color map.)

That perceptually uniform stuck out at me and I looked into it. From the [Lab wikipedia page], the definition of perceptually uniform is

> Perceptually uniform means that a change of the same amount in a color value should produce a change of about the same visual importance.

We want the default colormap in mpl to be perceptually uniform, correct? According to the same wiki page,

> XYZ color space ... is not particularly perceptually uniform. [[3]]
...
> the intention of both "Lab" color spaces is to create a space that can be computed via simple formulas from the XYZ space but is more perceptually uniform than XYZ. [[4]]

If mpl cares about perceptual uniformity, it sounds like it should us the Lab color space to calculate perceptual differences.

[blog post]:http://scottsievert.github.io/blog/2015/04/23/image-sqrt/
[3]:http://www.brucelindbloom.com/UPLab.html
[4]:http://www.handprint.com/HP/WCL/color7.html#CIELUV
[Lab wikipedia page]:https://en.wikipedia.org/wiki/Lab_color_space
[Matlab's review of rainbow colorspaces]:http://www.mathworks.com/tagteam/81137_92238v00_RainbowColorMap_57312.pdf
[the proposal]:http://bids.github.io/colormap/

**Comment by WeatherGod** [comment]
Scott,

I would suggest watching this presentation which explains the limitations
of Lab space and exactly how the viridis colormap was constructed. It
certainly changed my mind about Lab:
http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCAQtwIwAGoVChMI9rfWtOrdxgIVhyweCh0nHgvP&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DxAoljeRJ3lU&ei=Lq-mVfboN4fZeKe8rPgM&usg=AFQjCNHrjjkuIQ5ogbtVPtyDpXuBjVYbtg&sig2=quywaH4SYnziH9S8C2vmGQ&bvm=bv.97653015,d.dmo

Ben Root

**Comment by ivanov** [comment]
(Ben, I took the liberty of updating your link to the direct youtube one - google doesn't play nicely when you try to copy-link from search results)

**Comment by WeatherGod** [comment]
Thanks Paul, I was wondering about the length of that URL...

Anyway, the tl;dr; of the video is that, yes, Lab space does measure color
distances better than XYZ, but Stefan and Nathanial didn't use XYZ. They
used newer model that had much lower errors for both nearby and far away
colors. They even show examples of parula having apparent gradients that
didn't really exist.

**Comment by njsmith** [comment]
@scottsievert: Is there text somewhere saying that XYZ space was used to calculate perceptual differences? If so it'd be good to know so we can correct it -- we used CAM02-UCS, which is a perceptually uniform space that improves on CIEL*a*b*. To get to either CAM02-UCS and CIEL*a*b* space you have to pass through XYZ -- here's the transformation graph supported by [colorspacious 0.1.0](http://colorspacious.readthedocs.org/en/latest/) --

![colorspacious](https://cloud.githubusercontent.com/assets/609896/8707689/ee847fcc-2afc-11e5-9605-195412a83d54.png)

but that's an implementation detail...

**Comment by scottsievert** [comment]
Got it. In [your talk] mentioned above, you referred to the XYZ space more often and I assumed that's what you were using to calculate the perceptual differences. It's good to know otherwise and I'll trust you on this.

[your talk]:https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by njsmith** [comment]
Ah, gotcha, right, that could definitely have been clearer. Something to
keep in mind if I end up giving the talk again :-)

On Wed, Jul 15, 2015 at 2:44 PM, Scott S. <notifications@github.com> wrote:

> Got it. In your talk <https://www.youtube.com/watch?v=xAoljeRJ3lU>
> mentioned above, you referred to the XYZ space more often and I assumed
> that's what you were using to calculate the perceptual differences. It's
> good to know otherwise and I'll trust you on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/875#issuecomment-121724338>
> .
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by stefanv** [comment]
See also https://github.com/matplotlib/matplotlib/pull/4707#issuecomment-121766482

**Comment by mycarta** [comment]
> Is there something like the Kindleman set available? Do some of the new stylesheets already improve this?

@michaelaye I only noticed this comment of yours today. 

I have a version of Kindleman linear lightness colormap in the second half of [this notebook tutorial](https://github.com/seg/tutorials/blob/master/1408_Evaluate_and_compare_colormaps/How_to_evaluate_and_compare_colormaps.ipynb). 

Using the same data and function in the notebook I also replicated his circular colormap. it's bee nsitting on my home computer for a while, I just uploaded it on GitHub [here](https://github.com/mycarta/PerceptualColormaps/blob/master/Kindleman_circular_colormap.ipynb).

**Comment by njsmith** [comment]
:star2: :dancers: :star2:
