### ISSUE TITLE
Interactive backend test timeouts on wheel tests

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#8756]
I have seen a couple of timeouts for the interactive backend tests when running the wheel tests:

* [most recent](https://travis-ci.org/MacPython/matplotlib-wheels/jobs/242336178)
* [previous](https://travis-ci.org/MacPython/matplotlib-wheels/jobs/241107872)

I suppose it may be a coincidence, but both were on Python 3.6.

EDIT: fixed links to point to job rather than log.
EDIT2: fixed links properly to point to job.

**Comment by tacaswell** [comment]
links are broken :disappointed:

**Comment by matthew-brett** [comment]
I edited to point to the page for the job instead - links to logs seem to be weirdly user and browser specific.

**Comment by anntzer** [comment]
links are still broken :(

**Comment by matthew-brett** [comment]
Oops - fixed now, I believe (at least, they work for me).

**Comment by anntzer** [comment]
Looks similar to https://github.com/matplotlib/matplotlib/issues/8679?  Can you check if $DISPLAY is set (both during test collection and when the test is run)?

**Comment by matthew-brett** [comment]
For reference, here is the error (same in both runs):

```
[gw0] darwin -- Python 3.6.0 /Users/travis/build/MacPython/matplotlib-wheels/venv/bin/python3.6
backend = 'tkagg'

    @pytest.mark.parametrize("backend", _get_testable_interactive_backends())
    def test_backend(backend):
        environ = os.environ.copy()
        environ["MPLBACKEND"] = backend
        proc = Popen([sys.executable, "-c", _test_script], env=environ)
        # Empirically, 1s is not enough on Travis.
>       assert proc.wait(timeout=5) == 0
```

This doesn't happen in every Python 3.6 run - it has passed a couple of times before failing again. 

I think DISPLAY must be set, given the the fix to #8679.

**Comment by anntzer** [comment]
Does explicitly unsetting $DISPLAY in .travis.yml's before_script (in the osx case) help?

**Comment by matthew-brett** [comment]
https://travis-ci.org/MacPython/matplotlib-wheels/jobs/245278596
