### ISSUE TITLE
error with setting linewidth and linestyle='--'

### ISSUE THREAD

**Issue by walkloud** [matplotlib/matplotlib#8759]
using numpy to make x and y instances for plotting produces a bug in design, if not a real bug when adding linewidth to a linestyle='--' - minimal working example provided.

### Bug report
The offending function call is in this file:

```
File "/usr/local/lib/python2.7/site-packages/matplotlib/lines.py", line 74, in _scale_dashes
    scaled_offset = offset * lw
TypeError: can't multiply sequence by non-int of type 'float'
```

Minimal working example:

```python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()
plt.figure(1)
x = np.arange(0,1.01,.01)
y = 3 * x

plt.plot(x,y,alpha=1,linestyle='--',color='k')
plt.savefig("linewidth_notset.png")

plt.figure(2)
plt.plot(x,y,alpha=1,linestyle='--',linewidth='3',color='k')
plt.savefig("linewidth_set.png")

plt.ioff()
plt.show()
```

**Actual outcome**

The first plot command works, making a dashed line.  The second one triggers and error.  Presumably, the numpy array gets converted to a list along the way, and then there is a multiplication of a list by a float (the linewidth) triggering the error.

**Expected outcome**

The user should be able to add a linewidth to a plot line using numpy to make the x and y plotting variables.

**Matplotlib version**
  * Operating System:  Mac OS Yosemite, 10.10.5
  * Matplotlib Version:  2.0.2
  * Python Version:      2.7.12
  * Other Libraries:      numpy 1.12.1

homebrew python
pip install all python libs

**Comment by tacaswell** [comment]
You are passing in linewidth as a string, 

```python
plt.plot(x,y,alpha=1,linestyle='--',linewidth=3,color='k')
```

works as expected.

**Comment by walkloud** [comment]
that is embarrassing…

I was so focussed on the error report, I didn’t check the obvious…

thanks!

**Comment by tacaswell** [comment]
@walkloud Don't worry, everyone makes mistakes like that!
