### ISSUE TITLE
ENH/Bug: gridspec.tight_layout() should respect rectangle bounds made when created.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#8763]
### Bug report

`gridspec.tight_layout()` accomplishes a tight layout on `gridspec` instance, but it ignores the rectangle size made when the gridspec was created.  You *can* respecify the rectangle in `gridspec.tight_layout()` , but it seems it should respect the original rectangle if the `rect` argument is not provided.

I'll also point out that the API for `gridspec.tight_layout(rect=(l,b,r,t))` is different than for `gridspec.GridSpec(left=l,right=r)`.  

I can make a pull request to make these changes, but wanted to create an issue for discussion first because it is *not a backwards compatible change*, and it will change `gridspec.GridSpec` to include new methods `set_rectange()` and `get_rectangle()`.  However, I think the non-backwards compatibility is going to affect vanishingly small people.  

(*Background*: I've been unsatisfied with the various kuldges for adding colorbars to figures that cause more than one subplot to change size.  i.e. you have four subplots and you want them all to shrink the same amount to allow a new colorbar.  Its now easy (with master) to take space away from a list of axes for the new colorbar, but `fig.tight_layout` fails to take the colorbar into accoun.  I think probably the easiset way to make multi-axis colorbars work with `tight_layout()`, is to allow colorbar to modify the rectangle of a gridspec, and then call tight_layout on the gridspec rather than the figure.  The colorbar won't necessarily be laid out to the edge of the figure, but the subplots inside the gridspec will be laid out to the edge of the modified rectangle, and that is a big improvement)

**Code for reproduction**

```python
fig, axs = plt.subplots(2, 2, gridspec_kw={'right':0.48})
```

yields

<img width="455" alt="untitled" src="https://user-images.githubusercontent.com/1562854/27143490-62d75e22-50e3-11e7-9b68-40fa221de0a5.png">

Running `tight_layout()` yields:

```python
fig, axs = plt.subplots(2,2,gridspec_kw={'right':0.48},figsize=(4,4))
a = axs[0,1]
ss=a.get_subplotspec()
ss.get_position(fig)
gs=ss.get_gridspec()
gs.tight_layout(fig)
```
yields:

<img width="467" alt="untitled" src="https://user-images.githubusercontent.com/1562854/27143532-855fde06-50e3-11e7-977d-e2d8532fea98.png">

i.e. `tight_layout()` has forgoten the `right=0.48` command.

**What should happen**

The following code should work without the kw `rect`.  

```python
fig, axs = plt.subplots(2,2,gridspec_kw={'right':0.48},figsize=(4,4))
a = axs[0,1]
ss=a.get_subplotspec()
ss.get_position(fig)
gs=ss.get_gridspec()
gs.tight_layout(fig, rect=[0,0,0.48,1.])
```

<img width="461" alt="untitled" src="https://user-images.githubusercontent.com/1562854/27143935-e9c82a64-50e4-11e7-9850-d2311619f419.png">

**Comment by jklymak** [comment]
Closing - my understanding of `left` and `right` was incorrect. `tight_layout` is supposed to ignore those.  I am going to make a pull request that proposes to add `tight_rect` to `gridspec` instances, so that other processes can set the `rect` parameter to `gridspec.tight_layout` without needing to involve the user.  This should be a backwards-compatible change.

**Comment by jklymak** [comment]
Re-opening.  Basically I played around with a bunch of ways of making `tight_layout` respect gridspecs that are not supposed to fill the whole figure, and was not successful (yet).  

To me, looking at the code for quite a while, the issue is that `gridspec` mixes metaphors.  It divides the canvas into m*n blocks, but then it worries about things like `left` and `bottom`, and the actual positions for the axes.  Similarly `subplotspec` returns the `figbox` for the axes.  To me, those positions are the job of `subplot` or whatever draws the axes and labels (i.e. a utlility like `tight_layout`), *not* the logical layout class.  

I'm not 100% sure, but it seems to me that:

  1. `gridspec` should just be an abstraction that divides a region into m*n equal blocks. I don't think that `gridspec` should have a method like `get_grid_positions()` which attempts computes the axes `figbox` parameter. 
  2. `gridspec` objects should have a "container" property, which is either the parent figure or a `subplotspec` made from another `gridspec`.  There is a class for the `subplotspec` case, but it is quite limited, and I'm not clear why it should be a separate class.  But allowing a "container" would allow nested gridspecs.
  3. `gridspec` could optionally have a `rect` property that specifies its size and position relative to its container.  Usually this wouldn't be necessary as gridspecs coule be defined based on parent `subplotspecs`, but there are cases when you want some plots to be smaller than others in a layout and this would be an easy way to do that.
  4. `subplotspec` should specify what blocks a given subplot should cover.   It should *not* say anything about *where* on the canvas the axes elements to be plotted in the subplotspec should go.  Whatever draws the axes should figure that out from the `subplotspec` and the parent `gridspec`.
    
I appreciate that this is just a bit of re-organization of the classes, but the advantage is that any sort of layout manager, like the original `subplot_class_factory()` or `tight_layout()` or a future linear constrained layout manager could respect the *logical* layout asked for by the user and have enough information to carry that out and not also have parameters that are supposed to be for seting the `figbox` of the axes they contain.  

I'm happy to try and impliment this - I think it can all be done in a backwards compatible way.  But I wanted to get some feedback first.

**Comment by tacaswell** [comment]
You look like you are slowly approaching writing a full layout manager ;)  Are you familiar with the cassowary solver (see https://github.com/nucleic/kiwi / https://pypi.python.org/pypi/kiwisolver/0.1.3)?  It provides the solver to take in all of the constraints you describe and turn them into optimal size / positions.

At first read this seems reasonable, but I think that this refactor should be done in conjunction with the linear solver work (as they will be tightly coupled and what the solver needs is a stiff set of requirements).

**Comment by jklymak** [comment]
Closing: Reference #1109 for further discussion.
