### ISSUE TITLE
Indic Script labels not rendered correctly

### ISSUE THREAD

**Issue by aquiire** [matplotlib/matplotlib#8765]
### Bug report

**Bug summary**

Title sums it up all I guess.
Related:
* Issue [#3517](https://github.com/matplotlib/matplotlib/issues/3517) on Github
* [This](https://stackoverflow.com/questions/10960463/non-ascii-characters-in-matplotlib) and [this](https://stackoverflow.com/questions/40956636/missing-polish-characters-in-matplotlib-pyplot-labels-regardless-of-using-utf-8?noredirect=1&lq=1) on stack exchange

Here I used sinhala as [Indic Script](http://unicode.org/faq/indic.html) instance.
I think the font family has to do something with this issue since output to different font families are different. I'm not an expert in these stuff. Help appreciated to to get this work even with a different font family. 
An example is given below for which I've tried with 3 different font families.
**Code for reproduction**

```python
from matplotlib import rc
families = ['WARNA','LKLUG','Arial']
for familyname in families:
    rc('font', family=familyname)
    from matplotlib import pyplot as plt
    import numpy as np
    r = np.linspace(0.1,5,100)
    A = 3*2/(r*2)+np.pi*r**2
    fig = plt.figure()
    axes = fig.add_axes([.1,.1,.8,.8]) 
    axes.plot(r,A)
    axes.set_ylabel(u'වර්ගඵලය')
    axes.set_xlabel(u'අරය')
    axes.set_title(familyname)
```

**Actual outcome**

![Result 1](http://i.imgur.com/KuHdEmk.png)
![Result 2](http://i.imgur.com/3dozmf0.png)
![Result 3](http://i.imgur.com/WW20iNl.png)

**Expected outcome**

Result 1 looks fine but it has 2 problems:
* Accents not been placed in the correct location. ("්" in "වර්ගඵලය" is placed after "ර" not before)
* Letter "A" is not renderd in the title "WARNA"

Issues in result 2:
* Same previous accent issue
* Axis values or title not shown at all

Issues in result 3:
* No Sinhala script shown.

**Versions**

|Software            |	Version|
|-------------------|-------------|
Python               |     2.7.13 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]|
IPython              |	5.1.0  |
OS                     |	Linux 4.4.0 78 generic x86_64 with debian jessie sid|
matplotlib           |	1.5.1|

(Matplotlib from anaconda bundle)

Wed Jun 14 22:54:11 2017 +0530

**Comment by anntzer** [comment]
The misplaced accent is due to lack of support for combining characters at the freetype level (e.g. https://stackoverflow.com/questions/9985340/how-to-render-combined-unicode-characters-in-freetype).  Using a real text layout engine (MEP14) is probably not going to happen any time soon :-/

Not sure what's happening with the missing A (well I guess the glyph is missing? unlikely though) and the missing title of case 2.

Case 3 is just that Arial does not provide Indic characters (in all likelihood) so you're out of luck.

**Comment by anntzer** [comment]
/self-promotion/ mplcairo now supports complex text layout using libraqm, this was suprisingly easy to add...
![figure_1](https://user-images.githubusercontent.com/1322974/32409351-4891b202-c167-11e7-8b34-20c8afa20662.png)

**Comment by baabsa** [comment]
can you please illustrate steps for adding and use (libraqm),

I am new in python and I didn't find an easy explanation how it is used.

Thanks in advance.

**Comment by anntzer** [comment]
It is a fairly technical project and will probably not be implemented any time soon.
But most solutions that fixes indic script will likewise fix arabic script (*well technically you can have a shaper without RTL support but let's not get there).

**Comment by baabsa** [comment]
this issue doesn't appear in printing an Arabic word from DataFrame, it is only appear when I have Arabic words in plot as x axes, y axes, or title!

**Comment by anntzer** [comment]
Actually this issue is basically already tracked at #5941, so I'll close this one as a duplicate.

**Comment by QuLogic** [comment]
Not sure why this is a duplicate of #5941, but that's closed and this issue isn't actually fixed.

**Comment by QuLogic** [comment]
The `text-overhaul` branch is now merged to `main`.
