### ISSUE TITLE
One one tick in a log-scale axis

### ISSUE THREAD

**Issue by szsdk** [matplotlib/matplotlib#8768]
### Bug report

For the data in a small range, there is just on tick in the default log scale axis, which means nothing.

**Code for reproduction**

```python
import matplotlib.pylab as plt
plt.loglog([ 0.53,  0.41],[ 0.53,  0.41] )
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/6657200/27209937-79adcc04-5281-11e7-82d2-003beb5706f4.png)

**Expected outcome**
Give at least two ticks for each axis.

**Matplotlib version**

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 2.02
  * Python Version: 3.6.0
I install the library by conda.

**Comment by afvincent** [comment]
What supplementary tick value would you expect? 0.41? Or would you expect the ylim to be automatically extended to include 0.4 (for example)?

Currently, one simple workaround solution may be to simply use `plt.xlim` and `plt.ylim` to include 0.4, which results in a second tick being used.

By pure curiosity, why is there the need of a logarithmic plot on such a short (meaning << 1 decade) range? Is it related to a specific field of research?

**Comment by dstansby** [comment]
An even worse case, where no tick labels are present:

```python
import matplotlib.pylab as plt
plt.loglog([ 0.45,  0.46],[ 0.45,  0.46] )
plt.show()
```

**Comment by afvincent** [comment]
@dstansby What would be the correct behavior in this case? I agree that no tick *is* a bad choice. But it also seems wrong to me to use a log scale on such a small range of values as it should be more or less linear anyway, shouldn't it? In your example, one wants to plot values `log10(0.45 + x)` with x in `[0, 0.01]` (i.e. x << 0.45) so
```
log10(0.45 + x) = log10(0.45) + log10(1 + x/0.45)  # log scale
                ~ log10(0.45) + x/0.45  # linear scale
```
Would you suggest the logarithmic locators to switch to a linear-like behavior for ranges where one or no tick at all would be displayed?

**Comment by efiring** [comment]
All of this is inherent in the way log locators and formatters work.  @afvincent's suggestion is correct: the solution to this is an AutoLogLocator that switches to using a MaxNLocator when the range drops below a threshold, probably a little larger than the largest minor tick interval.

**Comment by szsdk** [comment]
@afvincent The reason I want to use log-scale is that the theory shows that the data should behave the power law in this range. Indeed, there is no big difference between log-scale or linear-scale in this range.
Probably, the ticks could be
```
4.0e-1 4.5e-1 5.5e-1
```
Somehow, give readers a sense that this is not a linear scale axis.

**Comment by tacaswell** [comment]
If I put on my physicist hat, I am deeply skeptical of power law claims at less than 3 decades (as a default position), but with my Matplotlib hat on we probably should make sure we do not create plots with too few ticks to be useful.

For now @szsdk I suggest manually setting the ticks.

**Comment by danijar** [comment]
Running into the same problem with much more data points. Setting limits manually is hard since I only want to include the previous and next tick and not more.

**Comment by stevennoyce** [comment]
Although it may not always make sense to plot on a log scale over a small range, it can become necessary for some applications.  I have been building a matplotlib backend to a test and measurement system.  The expected data spans several decades and is best suited for a log scale.  By nature of doing research and measuring devices with properties that are not known in advance, however, there will be some devices that do not function properly and produce data spanning only a small range.  It does not make much sense to plot on a linear scale because I want to compare poorly functioning devices to those that function well.

I really appreciate that this was added to a milestone, but I noticed that milestone has been deleted.  I upgraded to 2.2.2 and the issue persists, so I just wanted to check: what is the status on this?  Is it in the plans?  Is anyone working on it?

Thanks all!

**Comment by anntzer** [comment]
Closed by #12865.

**Comment by aggna** [comment]
Still getting this issue. Using python 3.6.8, matplotlib 3.1.1 on Windows 10.

```
plt.figure(figsize=(6,2))
plt.semilogy(np.arange(6),[9, 5e1, 1e2, 6e2, 9e2, 2e3])
```

generates the following output.
![tickeg](https://user-images.githubusercontent.com/52263117/96300273-e1e0e480-1012-11eb-987f-3016a8caf70e.png)

For me, the ideal case would be to have minor ticks in the above plot. But when I tried to force-add them with the following three methods, none worked:

1. `ax.tick_params(axis='y', colors='k',which = 'both')`

2. `ax.yaxis.set_minor_locator(ticker.AutoMinorLocator())`

3. 
```
ax.minorticks_on()
ax.xaxis.set_tick_params(which='minor', bottom=False)
```


For now, I just artificially imposed ticks by increasing the ylim:
`plt.ylim(1,1e4)`
which gives the second example.
![tickeg2](https://user-images.githubusercontent.com/52263117/96299452-ba3d4c80-1011-11eb-84fd-ae57f7c4e143.png)

**Comment by jklymak** [comment]
You must have things set in your rcParams that are causing this, or we fixed something:  I get:

![image](https://user-images.githubusercontent.com/1562854/96304560-305d9700-0fb1-11eb-8f61-bd35a57a5f35.png)

**Comment by tacaswell** [comment]
if you make the window small enough you you can get it to go to 1 tick (I think it is font dependent).  For me if I make it ~1.2 in tall I can get it to drop to on tick.

**Comment by tacaswell** [comment]
The really upsetting part is that the ticks are in-range just not shown!

![womp_womp](https://user-images.githubusercontent.com/199813/96304887-eed9e580-0fca-11eb-9692-f67c25b697b1.png)

**Comment by tacaswell** [comment]
`ax.yaxis.get_major_locator().numticks = 4` makes it behave better for me locally.

**Comment by tacaswell** [comment]
and if you set `ax.yaxis.get_major_locator().numticks = 3` it is broken independent of figure size (the small figure here is needed to trigger a small enough number out of `ax.yaxis.get_tick_space()` and it looks like @aggna is using latex for the tick labels which places the exponent a bit higher than the defaults so they triggered the problem with a slightly bigger figure than @jklymak and I did.

I'm trying to puzzle through the `LogLocator` code to sort out what is going wrong...

**Comment by tacaswell** [comment]
ok, got this sorted, PR coming.

**Comment by aggna** [comment]
Thanks!

`ax.yaxis.get_major_locator().numticks = 4` worked well for me too.

By any chance, do you know how I'd turn on the minor ticks?

**Comment by dmylnikov** [comment]
I'm still able to get 1 tick axis with the following code using matplotlib 3.3.4:
`plt.semilogy([1.5, 50])`
![2021-07-30 02_02_40-Figure 1](https://user-images.githubusercontent.com/9592588/127576414-6bbb9bc7-f3e3-4531-8a72-ee7f446a3310.png)

**Comment by jklymak** [comment]
I think that is expected.  The problem before was there were no minor ticks...

**Comment by doronbehar** [comment]
@dmylnikov the issue you are describing was further described in https://github.com/matplotlib/matplotlib/issues/29414 and was fixed in https://github.com/matplotlib/matplotlib/pull/29054 - should be part of the matplotlib 3.11 release.
