### ISSUE TITLE
seeing issue on six.py import name in matplotlib on python3.4

### ISSUE THREAD

**Issue by sangmeshcp** [matplotlib/matplotlib#8769]
### Bug report

**Bug summary**
Seeing following issue on six.py import name in matplotlib on python3.4 ..

**Code for reproduction**
just try to install on matplotlib with centos 5.5 python3.4 and import matplotlib in any script .. this issue is hit.. 

File “***/lib/python3.4/site-packages/matplotlib/pylab.py", line 257, in <module>
from matplotlib import cbook, mlab, pyplot as plt
File “***/lib/python3.4/site-packages/matplotlib/pyplot.py", line 115, in <module>
_backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
File “***/lib/python3.4/site-packages/matplotlib/backends/init.py", line 32, in pylab_setup
globals(),locals(),[backend_name],0)
File “***/lib/python3.4/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
from six.moves import tkinter as Tk
File “***/lib/python3.4/site-packages/six.py", line 92, in get
result = self._resolve()
File “***/lib/python3.4/site-packages/six.py", line 115, in _resolve
return _import_module(self.mod)
File “***/lib/python3.4/site-packages/six.py", line 82, in _import_module
import(name)
File "/sw/packages/python3/current/lib/python3.4/tkinter/init.py", line 40, in <module>

**Comment by matthew-brett** [comment]
Have you installed the python-tk package or equivalent for Python 3.4?  It may not have been installed by default.

**Comment by tacaswell** [comment]
Is that the complete traceback?  It looks cut-off to me.

How did you install Matpltolib, pip or system packages?  If system packages this should probably be reported to centos.

**Comment by sangmeshcp** [comment]
@tacaswell that's the complete trace back I have ..  I'm trying to install using pip..

**Comment by jenshnielsen** [comment]
What happens if you just do ```import tkinter``` in a clean python console. As @matthew-brett writes it seems most likely that you python does not have a working TK installation.

**Comment by anntzer** [comment]
Closing due to lack of further information, and because it's likely "just" an botched install.
Feel free to request a reopen if you have additional questions.
