### ISSUE TITLE
subplots with 

### ISSUE THREAD

**Issue by giacomociani** [matplotlib/matplotlib#8780]
### Bug report

**Bug summary**

Not sure it is really a bug, but for generality's sake, I think subplots() should always returns an array of AxesSubplot objects, even when nrows=1, ncols=1. Currently it returns a single AxesSubplot in this case.

**Code for reproduction**

import matplotlib.pyplot as plt
fig, axs = plt.subplots(2,1)
print(axs)
fig, axs = plt.subplots(1,1)
print(axs)

**Actual outcome**

[<matplotlib.axes._subplots.AxesSubplot object at 0x0000014D358C4F98>
 <matplotlib.axes._subplots.AxesSubplot object at 0x0000014D1F645EB8>]
Axes(0.125,0.11;0.775x0.77)

**Expected outcome**

In the second case, just an array of AxesSubplot of length 1.

**Matplotlib version**

  * Operating System: Win10 64bit
  * Matplotlib Version: 2.0.0
  * Python Version: 3.5
 Using WinPython.

**Comment by jenshnielsen** [comment]
You just need to pass `squeeze=False` to subplots see http://matplotlib.org/api/pyplot_api.html?highlight=subplots#matplotlib.pyplot.subplots

**Comment by giacomociani** [comment]
My sincere apologies. I'm ashamed... :-(
It just didn't occur to me that such a behavior could be controlled by an option, so I didn't check.
Now that I have read how the option works, I see the logic and appreciate the flexibility.

Sorry for the waste of time.

**Comment by jenshnielsen** [comment]
No problem glad it works for you
