### ISSUE TITLE
Inconsistent doc vs behavior for RendererXXX.draw_markers

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8790]
The docstring for RendererBase.draw_markers states
```
        Draws a marker at each of the vertices in path.  This includes
        all vertices, including control points on curves.  To avoid
        that behavior, those vertices should be removed before calling
        this function.
```
but in fact, control points are dropped by the implementation:
```
        for vertices, codes in path.iter_segments(trans, simplify=False):
            if len(vertices):
                x, y = vertices[-2:] # <- HERE
                self.draw_path(gc, marker_path,
                               marker_trans +
                               transforms.Affine2D().translate(x, y),
                               rgbFace)
```
(other backends contain similar lines).

The discrepancy seems to have been introduced back in 2008 (https://github.com/matplotlib/matplotlib/commit/39e748853fdeba2807aa560329e437ca3d6d4c01).

The only points in the codebase where draw_markers is called all pass in a newly constructed Path with no curve codes (lines.py, collections.py, axis_artist.py; patheffect.py redefines draw_markers by passing in whatever Path it was given) so no one was going to ever notice unless they are directly calling draw_markers themselves.  For efficiency purposes, I think it makes most sense to go back to the behavior of docstring (as it avoids having to go through iter_segments to determine which points are true vertices and which are control points).

Semantically, it would make most sense if the `path` argument to draw_markers was not a Path but, in fact, just an (N, 2) array, but I sense that there may be reluctance in changing that :-)

**Comment by tacaswell** [comment]
When did the transform come in?

**Comment by tacaswell** [comment]
Ah, in the commit you linked to did not pass `trans` into `iterpath`, but I see that it was done the line above now.

It looks like `iter_segments` also drops `nan` cords (which is what I suspect this change was to support in the first place).

Given that this has been like this from 2008, I would lean towards correcting the docstring to match the code.

**Comment by anntzer** [comment]
Drawing a path at nan will be dropped by draw_path anyways, so it's not really an issue.
