### ISSUE TITLE
figimage does not work when the output format is pdf.

### ISSUE THREAD

**Issue by szsdk** [matplotlib/matplotlib#8791]
### Bug report

figimage does not plot image expected when the output file is pdf.

**Code for reproduction**

```python
import matplotlib.pylab as plt
import numpy as np

fig = plt.figure()
img = np.random.rand(50,50)
fig.figimage(img, 20, 20)
plt.savefig('test.png')
plt.savefig('test.pdf')
```

**Matplotlib version**

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1

**Comment by jklymak** [comment]
Closed by #9204
