### ISSUE TITLE
animation.save problems with ffmpeg

### ISSUE THREAD

**Issue by fredrik-1** [matplotlib/matplotlib#8794]
When saving an artist animation with ffmpeg I got bad mp4 when using the default parameters and I don't know about any extra parameters that work for the file writer. 

I want to show a set of plots relatively slow. Here is some code.

```python
import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

N=10
V=np.random.rand(N,100,150)
O=np.ones((100,150)) 
fig=plt.figure(1)
fig.clf()
ax=fig.add_subplot(111)

im=[None]*N
for k in range(N):
    title=ax.text(75,40.,str(k), size=80, ha='center')                  
    ax.add_artist(title)
    im[k]=(ax.pcolor(V[k,...]+k/2.*O, vmin=np.min(V[0]), vmax=np.max(V[-1]+(N-1)/2.*O )), title)
    
fps=1     
im_ani = animation.ArtistAnimation(fig, im, blit=False, interval=1./fps*1000, repeat=True) 
Writer = animation.writers['ffmpeg']
WriterFile = animation.writers['ffmpeg_file']
writer1 = Writer(fps=fps)
writer2 = WriterFile(fps=fps)
writer3 = Writer(fps=fps, extra_args=['-r', '25'])
writer4 = WriterFile(fps=fps, extra_args=['-r', '25'])
im_ani.save('test_anim_1.mp4', writer=writer1, dpi=200)
im_ani.save('test_anim_2.mp4', writer=writer2, dpi=200)
im_ani.save('test_anim_3.mp4', writer=writer3, dpi=200)
im_ani.save('test_anim_4.mp4', writer=writer4, dpi=200)  

```
When I run the script above, the first two mp4 movies don't show all plots and the first plot is shown to long in windows media player. The movies don't work at all in the VLC media player. 

test_anim_3 works as expected. 
test_anim_4 is very very short. 

I believe that the problem is that it is good if the output frame rate is high and the `extra_args=['-r', '25']` achieve an output frame rate of 25 frames per second. The output frame rate will be the same as the input frame rate if not -r fps is used also after the input files in the command.

The problem with test_anim_4 is that the FFMpegFileWriter puts `'-vframes', str(self._frame_counter)` in the command to ffmpeg (line 664 in animation.py). -vframes sets the number of frames that is included in the movie. It is not needed if -r fps for the movie is not used and it results in a very short movie if the movie frame rate is higher than the frame rate used for the input files.  

I would suggest that the frame rate for the output movie should be a parameter in the animation writer functions or at least make it clear that adding -r 25 is often a good idea and that -vframes should not be used in the file writer.  The -vframes is "in the way" for other parameters to ffmpeg.
 
windows 
matplotlib 2.0.0
python 2.7.13 I believe
ffmpeg version 2.8.4

**Comment by tacaswell** [comment]
The `-vframes` came in via ed6a25080f6316eb8f1fa9b82fb38f162d3674d3 originally to prevent picking up frames from previous animations.  I think we have fixed this in a different way by using temp directories for the output files?

It looks like `-vframes` is deprecated (https://ffmpeg.org/ffmpeg.html#Video-Options) and sets the number of _output_ frames, not the number of frames from the input to take.  We probably should remove that, or at least use the new name.

It is not clear to me how much of this is issues with the viewers issues with the output files.  

Using `ffplay` (on linux) gives:

```
(bleeding) ✔ /tmp 
17:29 $ ffplay test_anim_1.mp4 
ffplay version 3.3.2 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170516
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test_anim_1.mp4':B f=0/0   
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:10.00, start: 0.000000, bitrate: 1146 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960, 1145 kb/s, 1 fps, 1 tbr, 16384 tbn, 2 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Switch subtitle stream from #-1 to #-1 vq=    0KB sq=    0B f=0/0   
  38.83 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
(bleeding) ✔ /tmp 
17:30 $ ffplay test_anim_2.mp4 
ffplay version 3.3.2 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170516
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test_anim_2.mp4':B f=0/0   
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:10.00, start: 0.000000, bitrate: 1146 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 1145 kb/s, 1 fps, 1 tbr, 16384 tbn, 2 tbc (default)
    Metadata:
      handler_name    : VideoHandler
  14.82 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
(bleeding) ✔ /tmp 
17:31 $ ffplay test_anim_3.mp4 
ffplay version 3.3.2 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170516
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test_anim_3.mp4':B f=0/0   
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:10.00, start: 0.000000, bitrate: 1030 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960, 1027 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
  16.87 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
(bleeding) ✔ /tmp 
17:31 $ ffplay test_anim_4.mp4 
ffplay version 3.3.2 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170516
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test_anim_4.mp4':B f=0/0   
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:00.40, start: 0.000000, bitrate: 1913 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 1893 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
   5.25 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
(bleeding) ✔ /tmp 
17:31 $ du -hs test_anim_*.mp4
1.4M    test_anim_1.mp4
1.4M    test_anim_2.mp4
1.3M    test_anim_3.mp4
96K     test_anim_4.mp4
(bleeding) ✔ /tmp 

```

The first 3 moves are 10s long, with each frame for 1s and the

**Comment by fredrik-1** [comment]
I don't think using -frames:v makes any difference. 

It is possibly that the problem is actually in the viewers but it is not good if the movies doesn't work in the most used viewers. 

Are there any reasons why an output movie with slow updating input frames shouldn't have a high output frame rate? 

It is possibly to solve the issue by using -vframes framesIn*fpsOut (if -r fpsOut is used). 
This result in a slightly smaller movie compared to when -vframes was omitted for some reason but I believe that you got the same sized movie if a slightly larger -vframes where used.  

The ffmpeg documentation also suggest that -framerate should be used instead of -r in the beginning of the command. I didn't found any difference in my test excepts maybe a very small difference in movie size.

**Comment by tacaswell** [comment]
> Are there any reasons why an output movie with slow updating input frames shouldn't have a high output frame rate?

The counter question is why should the output file be artificially forced to a high frame rate?

Can you use vlc, windows media player, or ffmpeg to get any metadata out of the files?  Do they correctly report that the files are 1fps and ignore it?  Are the files produced by your ffmpeg not preserving the input framerate?  Is this tied to this a specific codec?

Giving the ability to pass extra args to both input and output is a good idea, :+1: on that (a kwarg named `extra_i_args` to the `ffmpeg` family of writer classes, maybe also add an alias `extra_o_args` for the existing kwarg for symmetry).

Still not sold on changing the default behavior to force the output fps up, I think we need to understand the root cause of the issue,  how wide-spread it is (at this point we have 2 data points, one of it working and one of it not), and which combinations of {viewer, ffmpeg version, codecs} is the issue.

@fredrik-1 Thank you for your work on this, it is really appreciated :smiley:  (even though I am being argumentative).

**Comment by fredrik-1** [comment]
I don't really know what is the best frame rate. Now I see that all movies seems to work in the quicktime player so it is probably nothing wrong with the movies but a problem with the viewers. 
 
> By using a separate frame rate for the input and output you can control the duration at which each input is displayed and tell ffmpeg the frame rate you want for the output file. This is useful if your player cannot handle a non-standard frame rate. 

from https://trac.ffmpeg.org/wiki/Slideshow  
but I don't really know which players that can't handle a non-standard frame rate are. I came to the conclusion that a standard frame rate is safer though and I am not sure that there are any drawbacks with using a standard frame rate. It seems to be a small difference in size though but I don't think that it large enough to be important.  

I also found the command on that page that I used before (but I now think that it was unnecessary) 
`ffmpeg -framerate 1/5 -i img%03d.png -c:v libx264 -vf fps=25 -pix_fmt yuv420p out.mp4 `

It is probably best to have as little as possible in the command line in the default case so that it is possible to easily ad extra functionality with the extra_arg list.

**Comment by tacaswell** [comment]
I think the best course of action here is to 

 - add a paragraph or two about frame rate to the animation docs (https://github.com/matplotlib/matplotlib/blob/master/doc/api/animation_api.rst)
 - clarify the `extra_args` apply to the output files
 - maybe drop the `-vframes` line from the `*File` classes (attn @dopplershift )

In general I am against working around down-stream tools that do not correctly implement reading file formats but could be talked into it here.

@fredrik-1 Given that you are likely now the local expert on this, could you update the docs?

**Comment by dopplershift** [comment]
If we're writing to temp directories (I can't even remember any more), then I think `vframes` can be removed from the `*File` classes.

It's an utter pain in the ass to map a programmatic API to a command line utility of such complexity as ffmpeg.

**Comment by stonebig** [comment]
could opencv ('import cv2") be used as an alternative of ffmpeg command line ?

**Comment by QuLogic** [comment]
I don't think we should try to guess what is a good frame rate given the user's choice for the animation.

> from https://trac.ffmpeg.org/wiki/Slideshow

However, reading over this link, I see that we really should be using `-framerate`, _not_ `-r`. The former is for the _input_ rate and is automatically copied to the output rate, but the latter is for the output rate only. Changing the option also means that the user can pass `-r` in the `extra_args` to override the output rate (causing ffmpeg to drop/copy frames as necessary) and not produce a confusing command line (i.e., I don't know if the last `-r` 'wins' or not, and changing options means not having to worry about that.)

The page also notes that there is a `-start_number` option to the image muxer; unfortunately there does not appear to be an equivalent `-end_number`. Since we default to a temporary directory, I think it makes sense to not include `-vframes` when doing so. If we aren't in a temporary directory, I think we should either a) warn if the next frame already exists, or b) [use the concat demuxer](https://trac.ffmpeg.org/wiki/Slideshow#Concatdemuxer) to be explicit about what files to use.
