### ISSUE TITLE
gtk3cairo draw_image does not respect origin and mishandles alpha

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8798]
As of master (and probably since a long time)
```
from pylab import *
rcdefaults()
fig, axs = plt.subplots(1, 2)
axs[0].imshow(np.arange(4).reshape((2, 2)))
axs[1].imshow(np.arange(4).reshape((2, 2)), alpha=.5)
show()
```
produces, on gtk3agg
![gtk3agg](https://user-images.githubusercontent.com/1322974/27520067-b15eda8a-59b6-11e7-9eb0-7c98645bb850.png)
and on gtk3cairo
![gtk3cairo](https://user-images.githubusercontent.com/1322974/27520068-b7c9934c-59b6-11e7-9e15-462c0ad173a7.png)

Looks like image.origin is not respected, and alpha is not applied correctly (this is not surprising, as cairo uses *premultiplied* ARGB (https://www.cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t CAIRO_FORMAT_ARGB32).

**Comment by AlexanderLarsRobinson** [comment]
I'd like to comment that using the argument `origin = 'lower'` will still flip the image upside down from `origin = 'upper'`, thus leaving the drawn image consistently inverted relative to Matplotlib's coordinates with this backend.

This caused me some confusion last week, so I'm glad I'm not the first to notice it.

**Comment by AlexanderLarsRobinson** [comment]
Looking more closely at older issues, the inversion thing seems to be a thing that has come and gone at least once already ...

**Comment by anntzer** [comment]
I consider the current cairo backend broken beyond repair.
If you are interested in using cairo, please have a look at https://github.com/anntzer/mpl_cairo, which can fully replace Agg.  I would gladly accept any help in getting that backend packageable/ PR'able into the main repo.
