### ISSUE TITLE
Division by zero in AutoMinorLocator

### ISSUE THREAD

**Issue by ffteja** [matplotlib/matplotlib#8804]
In ticker.py / AutoMinorLocator class / __call__ function,  there is a code mistake that results in a division by zero:
`if len(majorlocs) > 0 :`
should be replaced by :
`if len(majorlocs) > 1 :`

Otherwise this can happen :
```
majorstep = 0
minorstep = majorstep / ndivs
tmin = ((vmin - t0) // minorstep + 1) * minorstep
```
BOUM !

**Comment by tacaswell** [comment]
Can you please open a PR with that change?
