### ISSUE TITLE
3D plot camera-rotation does not update with mouse movement when using the MacOS backend

### ISSUE THREAD

**Issue by AlexanderLarsRobinson** [matplotlib/matplotlib#8814]
When displaying any simple 3D plot, rotation by dragging with the mouse during a left-click no longer properly updates with the cursor's movement, other than at the very beginning.  Using a right-click to zoom works as expected, however, updating the view throughout the cursor's movement.

This appears to happen with any 3D plot, so for a minimal example:
```python
import matplotlib.pyplot as plt, mpl_toolkits.mplot3d
fig = plt.figure()
ax = fig.add_subplot(111, projection = '3d')
ax.scatter([1,0,0,0,0,-1], [0,1,0,0,-1,0], [0,0,1,-1,0,0])
plt.show()
```
The problem appears to be that the image does not refresh during camera rotation movements, excluding at the very start.  Thus, in order to see the result of a rotation, a new (and preferably small) rotation must be initiated.  Alternately, a zoom action may be performed, as the view updates throughout the entirety of the zoom action.

~While this bug is present in Matplotlib 2.0.2, it was not present in (at least some) versions prior to 2.0.0.  Edit: This bug is only present with the MacOS backend, and was maybe not present in MacOS Mavericks version of that backend, while definitely being present in Sierra.~

Edit Edit: This bug is present with Matplotlib 2.0.2 using the MacOS backend on MacOS Sierra, but was not present with at least some versions of Matplotlib just prior to 2.0.0 using the MacOS backend on MacOS X Mavericks.

Using default MacOS backends.  ~Unsure if related to #8162.~

**Matplotlib version**
  * Operating System: MacOS 10.12.5
  * Matplotlib Version: 2.0.2
  * Python Version: 3.4.6
  * Installed via MacPorts.

**Comment by WeatherGod** [comment]
no, this is not related to #8162, as that is animation code + blitting.
There is no animation/blitting code going on here. Most likely, this is a
quirk of the macosx backend. Could you try a different backend (for
example, qt4agg) in order to confirm that the problem is isolated to the
macosx backend?

**Comment by AlexanderLarsRobinson** [comment]
I can confirm that the problem does not extend to the Qt4Agg backend.

It is therefore likely that the upgrade which caused the issue on my end was not the upgrade of Matplotlib to 2.0, but rather the upgrade of MacOS from Mavericks to Sierra.

**Comment by WeatherGod** [comment]
maybe, maybe not. There were updates to the macosx backend code that might
have caused this.

**Comment by dstansby** [comment]
Can confirm this on OSX, using the macosx background, will try and bisect to find the cause.

**Comment by dstansby** [comment]
Hmm, this bisects to https://github.com/matplotlib/matplotlib/commit/c4614b4947f00c53e50a6ab1321a2651595d98a2

**Comment by tacaswell** [comment]
@dstansby Did this get fixed?

**Comment by dstansby** [comment]
No, I'll put in a PR with the change that seems to fix it.
