### ISSUE TITLE
plt.plot() does not support structured arrays as data= kwarg

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8818]
As of 2.0.2 and master:
```
In [1]: t = np.array([(1, 2), (4, 5)], [("ABCD", float), ("EFGH", float)])
In [2]: plt.scatter("ABCD", "EFGH", data=t) # works
In [3]: plt.plot("ABCD", "EFGH", data=t) # fails with

ValueError: Unrecognized character E in format string
```

Passing a dict instead works -- there is no ambiguity as to whether "EFGH" should be interpreted as a color spec or a data key.

Other functions (e.g. plt.scatter) have no problem accepting structured arrays as the data= kwarg.

**Comment by njaremko** [comment]
This should probably be closed
