### ISSUE TITLE
BUG: clabel manual mode doesn't make a gap big enough in contour

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#8819]
### Bug report

**Bug summary**

Using ``plt.clabel(manual=True)`` adds labels but the labels are not easily readable because only a small gap is created in the contour.

**Code for reproduction**

The following works:

```python
plt.figure()
x = np.arange(400).reshape((20,20))
c = plt.contour(x)
plt.clabel(c)
```

<img width="752" alt="screen shot 2017-06-29 at 09 59 25" src="https://user-images.githubusercontent.com/314716/27677788-242a8664-5cb3-11e7-8231-03b00d006672.png">

But the following doesn't give as nice a result:

```python
plt.figure()
x = np.arange(400).reshape((20,20))
c = plt.contour(x)
plt.clabel(c, manual=True)
# click around
```

<img width="752" alt="screen shot 2017-06-29 at 09 59 29" src="https://user-images.githubusercontent.com/314716/27677808-3740dc6c-5cb3-11e7-9eab-0268dce8a443.png">

This happens with both the Qt5 and MacOS X backends, and I am using a retina display.

**Matplotlib version**

  * Operating System: MacOS X 10.11
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1

**Comment by tacaswell** [comment]
My guess is that this is a dpi scaling related issue as there is a mapping from screen-space back to data space...

**Comment by anntzer** [comment]
FWIW I can't repro on a non-high-DPI display.

**Comment by anntzer** [comment]
But perhaps @astrofrog you can try whether something along the lines of
```
diff --git i/lib/matplotlib/contour.py w/lib/matplotlib/contour.py
index 59b9fe63b..198aa78f9 100644
--- i/lib/matplotlib/contour.py
+++ w/lib/matplotlib/contour.py
@@ -17,9 +17,7 @@ import matplotlib.collections as mcoll
 import matplotlib.font_manager as font_manager
 import matplotlib.text as text
 import matplotlib.cbook as cbook
-import matplotlib.mathtext as mathtext
 import matplotlib.patches as mpatches
-import matplotlib.texmanager as texmanager
 import matplotlib.transforms as mtransforms
 
 # Import needed for adding manual selection capability to clabel
@@ -263,24 +261,12 @@ class ContourLabeler(object):
         """
         if not isinstance(lev, str):
             lev = self.get_text(lev, fmt)
-
-        lev, ismath = text.Text.is_math_text(lev)
-        if ismath == 'TeX':
-            if not hasattr(self, '_TeX_manager'):
-                self._TeX_manager = texmanager.TexManager()
-            lw, _, _ = self._TeX_manager.get_text_width_height_descent(lev,
-                                                                       fsize)
-        elif ismath:
-            if not hasattr(self, '_mathtext_parser'):
-                self._mathtext_parser = mathtext.MathTextParser('bitmap')
-            img, _ = self._mathtext_parser.parse(lev, dpi=72,
-                                                 prop=self.labelFontProps)
-            lw = img.get_width()  # at dpi=72, the units are PostScript points
-        else:
-            # width is much less than "font size"
-            lw = (len(lev)) * fsize * 0.6
-
-        return lw
+        fig = self.ax.figure
+        width = (text.Text(0, 0, lev,
+                           figure=fig, fontproperties=self.labelFontProps)
+                 .get_window_extent(fig.canvas.get_renderer()).width)
+        width *= 72 / fig.dpi
+        return width
 
     def set_label_props(self, label, text, color):
         """Set the label properties - color, fontsize, text."""
```
helps?
Note that get_window_extent() also takes `dpi` as a second argument; you may also want to check whether setting the value there helps...

**Comment by anntzer** [comment]
Can anyone with a high-dpi display check this?

**Comment by jklymak** [comment]
Check what?   The patch or just that the original issue is there?

**Comment by anntzer** [comment]
Both.

**Comment by jklymak** [comment]
The clabel works fine on master w/ hi-dpi and Qt5Agg.  Didn't check the patch (do I need to?)

![clabel](https://user-images.githubusercontent.com/1562854/67109577-a902fb00-f185-11e9-9776-35d23ca1d4f4.png)

**Comment by jklymak** [comment]
Note I don't manually set the dpi at any point.

**Comment by anntzer** [comment]
Let's ping @astrofrog to see whether he can give this a try again; if there's no reply we'll just close this.

**Comment by timhoffm** [comment]
Assuming fixed on master. Please ping if the problem still exists.
