### ISSUE TITLE
Regression with numpy ~~1.13~~ 1.14 for colorbars of boolean data

### ISSUE THREAD

**Issue by krischer** [matplotlib/matplotlib#8820]
I'm not even sure if this is a feature that is supposed to work but matplotlib with `numpy` < 1.13 could plot colorbars for boolean data. It was not a true categorical colorbar but it did the job and was useful to have a around.

The following code works with `numpy` < 1.13:

```python
import numpy as np
import matplotlib.pyplot as plt

plt.pcolor(np.array([[True, False], [False, True]]))
plt.colorbar()
plt.show()

```

![figure_1](https://user-images.githubusercontent.com/800487/27682923-9c1b1ac4-5cc4-11e7-9668-8e6d89a1b1fd.png)

With `numpy` 1.13 the following exception is raised:

```python
Traceback (most recent call last):
  File "binary_patch_example.py", line 5, in <module>
    plt.colorbar()
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2261, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/figure.py", line 1603, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/colorbar.py", line 1347, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/colorbar.py", line 926, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/colorbar.py", line 326, in __init__
    self.draw_all()
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/colorbar.py", line 347, in draw_all
    self._process_values()
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/colorbar.py", line 686, in _process_values
    expander=0.1)
  File "/Users/lion/.miniconda/envs/salvus_mesher_py36/lib/python3.6/site-packages/matplotlib/transforms.py", line 2786, in nonsingular
    elif vmax - vmin <= maxabsvalue * tiny:
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by jenshnielsen** [comment]
There has been some discussion on the numpy of reverting this as it's caused a number of issues see https://mail.python.org/pipermail/numpy-discussion/2017-June/076903.html

**Comment by anntzer** [comment]
Things should probably have been casted to floats at that point, otherwise we can also get issues with unsigned integer data...

**Comment by tacaswell** [comment]
If we cast as float we discard units.

**Comment by anntzer** [comment]
Hopefully units will have been stripped off by the time we reach transform.nonsingular.  Yes, we could fix the issue in that specific function, but it seems smarter to do it as much upstream as possible.

**Comment by krischer** [comment]
NumPy has reverted the removal of the boolean binary `-` operator so this works again with NumPy 1.13.1.

https://github.com/numpy/numpy/blob/master/doc/release/1.13.1-notes.rst

I'm leaving this open as you seem to still want to change some things somewhere else but feel free to close this as my original issue has been resolved by the latest numpy.

**Comment by tacaswell** [comment]
Great!

Going to close this as it is only present in 1 numpy patch version and doing anything about it on our side would require more invasive type checking than we really want to do.

**Comment by hovren** [comment]
I am getting this error on NumPy 1.14 and matplotlib 2.1.1.

**Comment by jklymak** [comment]
https://github.com/numpy/numpy/releases

> Using np.bool_ objects in place of integers is deprecated. Previously operator.index(np.bool_) was legal and allowed constructs such as [1, 2, 3][np.True_]. That was misleading, as it behaved differently from np.array([1, 2, 3])[np.True_].

I can't confirm this because 1.14 hasn't worked its way to conda for me yet...

As an obvious work around cast to int.

**Comment by hovren** [comment]
Yes, it is the exact same error/traceback. Tested with miniconda under Python 3.6. Reverting to numpy 13.3 makes the problem go away.

**Comment by jklymak** [comment]
Numpy changed this, and we decided to not fix their semantics; it'd require going through the whole code base and checking for bool, and thats a bit onerous for what is largely an edge case.  So please cast to int (ahem or feel free to submit a PR across the code base :wink:)

**Comment by dopplershift** [comment]
To be clear, the workaround should look like:
```python
arr = np.array([[True, False], [False, True]])
arr = arr.astype(np.int)
```
