### ISSUE TITLE
mpl_connect silently does nothing when passed an invalid event type string

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#8839]
### Bug report

If `fig.canvas.mpl_connect` is passed an invalid event type string, it silently does nothing. I think there should at least be a warning (maybe an error?)

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
def onclick(event):
    print('Event!')
cid = fig.canvas.mpl_connect('invalid_event_string', onclick)
plt.show()
```

**Actual outcome**

Clicking around or doing or trying to trigger `onclick()` does nothing.

**Expected outcome**

I would expect a warning if 'invalid_event_string' isn't one of the strings listed at http://matplotlib.org/devdocs/api/backend_bases_api.html?highlight=mpl_connect#matplotlib.backend_bases.FigureCanvasBase.mpl_connect

**Matplotlib version**
  * Matplotlib Version: master installed from source using pip

**Comment by WeatherGod** [comment]
Adding a warning might be noisier than useful as events get connected and
disconnected all the time. We should see if we are regularly firing events
after disconnects or not. But I can see how this could be useful for
debugging.

**Comment by tacaswell** [comment]
The callback registries do not know what keys they are going to get (which I think is a feature!), but adding an optional set of expected keys to the registry init + warning or error on invalid keys is a reasonable idea.

**Comment by WeatherGod** [comment]
No, I was thinking more along the lines of issuing a warning for unknown
events on the emit call. Although, now that I think of it, that wouldn't
help for connecting to built-in events.
