### ISSUE TITLE
Colorbar becomes too big for asymmetric matrices and for some aspect ratios

### ISSUE THREAD

**Issue by PerBr** [matplotlib/matplotlib#8840]
### Bug (?) report

Using imshow and colorbar to plot asymmetric matrices will result in a colorbar that is too big.
I believe the colorbar should be the same hight as the main axes.

```python
import numpy as np
import matplotlib.pyplot as plt

# setup some generic data
N = 34
x1, y1 = np.mgrid[:N, :N]
Z1 = (np.cos(x1*0.2) + np.sin(y1*0.3))

x2, y2 = np.mgrid[:N, :N*2]
Z2 = (np.cos(x2*0.2) + np.sin(y2*0.3))

plt.figure()
pos = plt.imshow(Z1, cmap='Blues', interpolation='none')
plt.colorbar(pos)
plt.title('Nice Symmetric Plot with Colorbar')

plt.figure()
pos = plt.imshow(Z2, cmap='Blues', interpolation='none')
plt.colorbar(pos)
plt.title('Asymmetric Plot with too big Colorbar')

plt.show()
```

**Actual outcome**

![bild](https://user-images.githubusercontent.com/15651646/27842443-72f22f1c-610a-11e7-8bae-29b25fdf4c25.png)

![bild](https://user-images.githubusercontent.com/15651646/27842456-8fc92992-610a-11e7-9895-1379f52a47d7.png)

**Matplotlib version**

  * Operating System: Win10
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Other Libraries: Anaconda 4.4.0

**Comment by PerBr** [comment]
After some additional testing it looks like this is also affecting the colorbar plot when changing the aspect ratio of the main plot.

```python
import numpy as np
import matplotlib.pyplot as plt

# setup some generic data
N = 34
x, y = np.mgrid[:N, :N]
Z = (np.cos(x*0.2) + np.sin(y*0.3))

plt.figure()
pos1 = plt.imshow(Z, cmap='Blues', interpolation='none', aspect=0.5)
plt.title('A plot with colorbar, aspect=0.5')
plt.colorbar(pos1)

plt.figure()
pos2 = plt.imshow(Z, cmap='Blues', interpolation='none', aspect=2)
plt.title('A plot with colorbar, aspect=2')
plt.colorbar(pos2, orientation='horizontal' )

plt.show()
```
![bild](https://user-images.githubusercontent.com/15651646/27856391-46143012-616e-11e7-8d53-29ca24bc2a2a.png)
![bild](https://user-images.githubusercontent.com/15651646/27856395-4abe9ba2-616e-11e7-919e-6cf117652397.png)

BR,
/Per

**Comment by Phlya** [comment]
AFAIK this is not a bug, but I agree this would be a very nice improvement - i.e. the question on SO about how to make the sizes match is very popular: https://stackoverflow.com/questions/18195758/set-matplotlib-colorbar-size-to-match-graph

**Comment by tacaswell** [comment]
Short of a proper layout manager, this is probably best addressed by moving the content of that SO post into an example.

**Comment by PerBr** [comment]
Tanks for sharing that that SO link.
The UPDATE to third (!?!) most popular answer (https://stackoverflow.com/a/33505522) solves the problem in a very nice way with an `add_colorbar()` wrapper for `colorbar()`

**Comment by jklymak** [comment]
I think this is actually an API problem in that there is no direct way to know what the position of the axes spines are.  If you use a set aspect ratio for a plot axes.get_position will still give you the nominal position that the axes would fill if its aspect wasn't constrained.  

There may be a more indirect way to get the actual position that I don't know about, but it is worth considering whether axes need another method that returns the actual position of the axes not just the nomina.

**Comment by jklymak** [comment]
This is specifically explained in https://matplotlib.org/stable/gallery/subplots_axes_and_figures/colorbar_placement.html#colorbars-with-fixed-aspect-ratio-axes where we suggest using `inset_axes` for these colorbars.  I think we can close this....
