### ISSUE TITLE
Guide for referencing inside documentation out of date

### ISSUE THREAD

**Issue by kbrose** [matplotlib/matplotlib#8841]
The section at [https://matplotlib.org/devel/documenting_mpl.html#referring-to-mpl-documents](https://matplotlib.org/devel/documenting_mpl.html#referring-to-mpl-documents) has instructions for referencing examples but these directions appear to have been outdated by #8456. To reference the `markevery` demo, I had to do

```rst
:ref:`sphx_glr_gallery_pylab_examples_markevery_demo.py`
```

**Comment by timhoffm** [comment]
Current docs for referencing are different but work:

https://matplotlib.org/3.2.2/devel/documenting_mpl.html#referring-to-other-documents-and-sections
