### ISSUE TITLE
Triangulation does not include all data points

### ISSUE THREAD

**Issue by ccrook** [matplotlib/matplotlib#8842]
### Bug report

**Bug summary**

Triangulation misses data points when data is far from the origin (eg example attached is in terms of a projection coordinate system with a false origin).

**Code for reproduction**

```python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.tri as tri

data=np.loadtxt('tricont.dat')
print data.shape
x=data[:,0]
y=data[:,1]
t=tri.Triangulation(x,y)
plt.triplot(t)
plt.plot(x,y,'k+')
plt.show()
x -= (x.min()+x.max())/2.0
y -= (y.min()+y.max())/2.0
t=tri.Triangulation(x,y)
plt.triplot(t)
plt.plot(x,y,'k+')
plt.show()

```

Data in: [tricont.zip](https://github.com/matplotlib/matplotlib/files/1123260/tricont.zip)

**Actual outcome**

![tricont](https://user-images.githubusercontent.com/631058/27845470-cdc94708-6183-11e7-9097-927026fb78c8.png)

Triangulation misses most data points

**Expected outcome**

![tricont2](https://user-images.githubusercontent.com/631058/27845572-8ff7d132-6184-11e7-9c9f-ec50d489f5c6.png)

Triangulation includes all data points 

**Matplotlib version**

Seen in version 1.5.1 and higher.
Not seen in version 1.3.1

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 1.5.1
  * Python Version: 2.7.12
  * Jupyter Version (if applicable):
  * Other Libraries: 

Installed from Ubuntu package repository

**Comment by jenshnielsen** [comment]
This is probably the same issue as #8682

**Comment by ianthomas23** [comment]
It is indeed the same issue. I have a candidate fix, currently testing it. Expect a PR in a few days.

**Comment by ccrook** [comment]
That sounds great - thanks. Subtracting the mean coordinate works fine as a workaround in the meantime.

**Comment by tacaswell** [comment]
Closing as duplicate, please move discussion to #8682
