### ISSUE TITLE
weird colormap when map the scalar value to RGB

### ISSUE THREAD

**Issue by zhuangjun1981** [matplotlib/matplotlib#8843]
### Bug report
weird colormap when map the scalar value to RGB

**Bug summary**

When use matplotlib.colors.Colormap to map scalar value to RGB colors. Sometimes the color I am getting are not as expected.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np
plt.ioff()


cmap = 'RdBu_r'
cmap = plt.get_cmap(cmap)

f = plt.figure(figsize=(8, 4))
ax1 = f.add_subplot(121)
ax2 = f.add_subplot(122)
plot_arr = np.arange(100).reshape((10, 10)) / 99.
ax1.imshow(plot_arr, vmin=0., vmax=1., cmap=cmap, interpolation='nearest')

for i in range(10):
    for j in range(10):
        curr_rgb = cmap(plot_arr[i, j])[0:3]
        curr_rgb = tuple([int(x * 255) for x in curr_rgb])
        r, g, b = curr_rgb
        curr_cstr = '#{:0<2}{:0<2}{:0<2}'.format(hex(r)[2:], hex(g)[2:], hex(b)[2:])
        ax2.plot(j, i, 'o', mfc=curr_cstr, lw=0, mec='none', ms=20)

ax2.set_xlim([-0.5, 9.5])
ax2.set_ylim([9.5, -0.5])
plt.show()

```

**Actual outcome**

![figure_1](https://user-images.githubusercontent.com/6720422/27885332-7d9c20b2-618c-11e7-939d-909d90b68bcb.png)

**Expected outcome**
As implemented in the code, the left plot is plotted as imshow(). Right plot is plotted dots with the color from the colormap object according to the input scalar. If my understanding is right, the colors at the same grid cell should be identical. But clearly different at high and low values. 
 

**Matplotlib version**

  * Operating System: windows 7 64-bit
  * Matplotlib Version: 2.0.2
  * Python Version: 3.5.3
  * numpy: 1.13.0

**Comment by zhangns** [comment]
`'#{:0<2}{:0<2}{:0<2}'` should be` '#{:0>2}{:0>2}{:0>2}'` to right align the number (pad zeros on the left)
![good](https://user-images.githubusercontent.com/10682831/27890271-948b3e7e-61bf-11e7-8aca-c92bb8b2baa0.PNG)

**Comment by zhuangjun1981** [comment]
Oh, how dumb I am. Thanks!
