### ISSUE TITLE
large alpha values do not cause an error but instead wrap around the internal uint8_t representation

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8854]
2.0.2 & master
```
from pylab import *
rcdefaults()
img = np.random.random(size=(3, 3, 4))
img[..., 3] = 1

fig, axs = subplots(2, 4)
axs[0, 0].imshow(img, alpha=.5)
axs[0, 1].imshow(img, alpha=1)
axs[0, 2].imshow(img, alpha=128)
axs[0, 3].imshow(img, alpha=255)
# pick a large linewidth to make things more visible.
axs[1, 0].plot([1, 2], alpha=.5, lw=5)
axs[1, 1].plot([1, 2], alpha=1, lw=5)
axs[1, 2].plot([1, 2], alpha=128, lw=5)
axs[1, 3].plot([1, 2], alpha=255, lw=5)
show()
```
produces
![test](https://user-images.githubusercontent.com/1322974/27996620-0acd92f2-649b-11e7-9eac-942695a9249a.png)
Note how alpha=128 behaves like alpha=.5, and alpha=255 yields nothing.

Looks like we wraparound some internal representation of the alpha channel as uint8_t.  We should just error on such alphas instead.

**Comment by greglucas** [comment]
Alpha is now represented as float internally, so gives a useful error message of alpha needing to be between 0 and 1.
