### ISSUE TITLE
expand log demo to a tutorial

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8863]
The behavior of log scales when dealing with non-positive values is a common gotcha issue.

This seems to only be documented at

https://matplotlib.org/api/scale_api.html#matplotlib.scale.LogScale and http://matplotlib.org/devdocs/gallery/pylab_examples/log_demo.html

The log-demo should be expanded to a tutorial with prose explaining 

 - npos clip vs mask behavior (#8623 #8056 and links there in)
 - `loglog` vs `semilog` vs `ax.set_scale` vs `plt.xscale`/`plt.yscale`
 - changing the base 
 - how ticking works with log scale (issues around http://matplotlib.org/users/dflt_style_changes.html?highlight=default%20changes#tick-label-formatting and issue around it (#8358 #7200 #8622 #8353 #8419 #8401 #8517 #8307)
  - maybe fold in the symlog demo (https://matplotlib.org/examples/pylab_examples/symlog_demo.html)

**Comment by afvincent** [comment]
@tacaswell I added #8307 to your list of issues related to a surprising behavior with ticking and log scale.

**Comment by tacaswell** [comment]
Still a good thing to be better documented.

**Comment by timhoffm** [comment]
So, `keep`?
