### ISSUE TITLE
uploading the devdocs is broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8875]
It looks like the  `git checkout --orphan gh-pages` is resulting in

```
Uploading documentation
Agent pid 17826
Identity added: ci/travis/matplotlibDeployKey (ci/travis/matplotlibDeployKey)
Cloning into 'devdocs'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

fatal: A branch named 'gh-pages' already exists.
HEAD is now at 1df21f0 Docs build of 80a09cca825bf4997d16d5fc262d88ea224710d1
[gh-pages 8c07238] Docs build of d5261057aff46632d6690ca9aba2eb777a83c235
<snip logs>
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

To github.com:matplotlib/devdocs.git
 + 4f3f060...8c07238 gh-pages -> gh-pages (forced update)
Branch gh-pages set up to track remote branch gh-pages from origin.

travis_time:end:07ae6fae:start=1499960749693811581,finish=1499960766082640488,duration=16388828907
[0Ktravis_fold:end:after_success.2
[0K
Done. Your build exited with 0.


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

```

**Comment by QuLogic** [comment]
Perhaps I should point out the possibility of building socs on CircleCI again?

**Comment by QuLogic** [comment]
I think this might be related to the docs containing old files. The `first_commit` tag in `devdocs` is some random version from 2015. The deploy does not delete any existing files from the repo, so they stick around when the new version is pushed. Additionally, since the original commit is so old, eventually git has to push some gigantic commit with changes to almost every file, which _may_ be the cause of the timeout. We should a) change `first_commit` to something from this year, and b) change deploy to delete existing files first.

**Comment by QuLogic** [comment]
I've uploaded a new `first_commit` tag with the latest build off of `master`; this also drops the old files so we should stop seeing them. I've also added an `empty` tag with an empty first commit, so we can more easily rebase the `first_commit` tag to something new.

I will leave the deploy script changes to #8893.

**Comment by QuLogic** [comment]
Even with the latest files, this is still hanging. I also noticed that it's uploading both 2 and 3 versions which causes quite a bit of churn, especially for the notebook files. I don't know how long the CircleCI PR will take, but I've opened #8905 to deploy only on Python 3 in the meantime.
