### ISSUE TITLE
Font warning: `... font family ['sans-serif'] not found. Falling back to DejaVu Sans ...` when using `fig.canvas.draw()`

### ISSUE THREAD

**Issue by lucainnocenti** [matplotlib/matplotlib#8876]
### Bug report

**Bug summary**
Using `fig.canvas.draw()` to redraw a plot produces the following warning:
```
/home/myname/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:1297: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```
It doesn't happen if I just plot the code, only when using `fig.canvas.draw()` to plot things dynamically.
I experience this when running the code in Anaconda, in bash, in Ubuntu, under Windows 10.
I tried to delete the content of `~/.cache/` (and of the corresponding folder in the windows anaconda installation, just to be sure), but the warning still appears.
I also tried installing `font-manager` as suggested [here](https://stackoverflow.com/a/42936670/4063051), but with no effect.

**Code for reproduction**

```python
import matplotlib.pyploy as plt
import seaborn
%matplotlib notebook
fig, ax = plt.subplots(1, 1)
ax.plot([0, 1, 2, 3], '-b')
fig.canvas.draw()
```

**Actual outcome**
![image 1](https://user-images.githubusercontent.com/10957113/28222263-988ecf80-68be-11e7-8bab-33d3ec1da427.png)

**Matplotlib version**

  * Operating System: Ubuntu in Windows 10 64bit
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1, provided by conda 4.3.2.2
  * Jupyter Version: 4.3.0

**Comment by lucainnocenti** [comment]
Nevermind, I solved as suggested [here](https://stackoverflow.com/a/42841531/4063051): installed `msttcorefonts` with
```$ sudo apt-get install msttcorefonts -qq```
and then deleted the content of `.cache/matplotlib` and restarted the notebook. No warnings issued anymore.

**Comment by lucainnocenti** [comment]
Nevermind, I solved as suggested [here](https://stackoverflow.com/a/42841531/4063051): installed `msttcorefonts` with
```$ sudo apt-get install msttcorefonts -qq```
and then deleted the content of `.cache/matplotlib` and restarted the notebook. No warnings issued anymore.

**Comment by LifeDrainFrog** [comment]
> Nevermind, the suggestion given [here](https://stackoverflow.com/a/42841531/4063051) solved the problem: I installed `msttcorefonts` with
> `$ sudo apt-get install msttcorefonts -qq`
> and then deleted the content of `.cache/matplotlib` and restarted the notebook. No warnings issued anymore.

For some Asian fonts, the straight way to solve this problem is that download the font you need and put it in the path like `/root/anaconda3/envs/<env name>/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf`
and use this ``maplotlib.matplotlib_fname()`` to get the path

**Comment by lifuqiang2016** [comment]
解决了吗？
我的是centos7.5;python3.6 ,出现这个问题

**Comment by LearningChanging** [comment]
> > Nevermind, the suggestion given [here](https://stackoverflow.com/a/42841531/4063051) solved the problem: I installed `msttcorefonts` with
> > `$ sudo apt-get install msttcorefonts -qq`
> > and then deleted the content of `.cache/matplotlib` and restarted the notebook. No warnings issued anymore.
> 
> For some Asian fonts, the straight way to solve this problem is that download the font you need and put it in the path like `/root/anaconda3/envs/<env name>/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf`
> and use this `maplotlib.matplotlib_fname()` to get the path

thanks
