### ISSUE TITLE
bars in plt.bar graph centered on "left" value

### ISSUE THREAD

**Issue by skjaeve** [matplotlib/matplotlib#8882]
### Bug report

**Bug summary**

Docstring for plt.bar:

> 
> matplotlib.pyplot.bar(left, height, width=0.8, bottom=None, hold=None, data=None, **kwargs)
> Make a bar plot.
> 
> Make a bar plot with rectangles bounded by:
> 
> left, left + width, bottom, bottom + height
> (left, right, bottom and top edges)
> 

However, "left" is in fact the center value of the resulting bars.

**Code for reproduction**

```python
# Paste your code here
#
#
import numpy as np
import matplotlib.pyplot as plt
lefts = np.asarray((0, 100, 200, 300, 400))
plt.bar(left=lefts, height=lefts, width=100)
plt.bar(left=lefts, height=lefts, width=75)
plt.bar(left=lefts, height=lefts, width=50)
plt.bar(left=lefts, height=lefts, width=25)

```

**Actual outcome**
![mwe-bar](https://user-images.githubusercontent.com/1247704/28239713-cdab0102-6972-11e7-8108-6041868daa75.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**
Bars should be left-aligned to the "left" value.
As the attached plot shows: Bars are centered on "left" value, and not left-aligned to it.

**Matplotlib version**

  * Operating System: Fedora Linux 26
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6
  * Jupyter Version (if applicable):
  * Other Libraries: 

matplotlib installed using pip

**Comment by QuLogic** [comment]
This is expected, if odd behaviour; `left` cannot be renamed to `center` due to API compatibility. See #7954.

**Comment by skjaeve** [comment]
If the behavior is correct, the documentation is wrong.

Den lør. 15. jul. 2017, 22.38 skrev Elliott Sales de Andrade <
notifications@github.com>:

**Comment by WeatherGod** [comment]
@tacaswell has an idea to fix all of this (essentially, accept both "left"
and "center" somehow through some kwargs magic). How is the documentation
incorrect, though? Does it say that "left" is the default?

**Comment by QuLogic** [comment]
It doesn't exactly say it's the default, but it does say that the rectangles will be `(left, left+width)` which is not quite correct when it's centred.

**Comment by skjaeve** [comment]
The first paragraph in the function documentation says:
>Make a bar plot with rectangles bounded by:
>
>left, left + width, bottom, bottom + height
>(left, right, bottom and top edges)
which clearly implies that "left" is in fact the left edges of the drawn rectangles. If this can't be fixed easily, please at least update the first paragraph of the documentation to explain the "align" keyword.

**Comment by WeatherGod** [comment]
Ah, yes. The documentation should be fixed. Technically, it has been
misleading for a *very* long time, ever since the `align` feature was added.
