### ISSUE TITLE
mplot3d projection results in non-orthogonal axes

### ISSUE THREAD

**Issue by eric-wieser** [matplotlib/matplotlib#8894]
When viewed from above, the default grids are not square, but are distorted into diamonds/parallelograms depending on the vertical rotation angle:
```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.view_init(90,45)  # or by manual rotation
plt.show()
```

![image](https://user-images.githubusercontent.com/425260/28248521-b5fb8aa6-6a3d-11e7-9a34-bea1dafe08bc.png)

The projection should not include non-uniform scale (or skew) components by default. Furthermore, it's not at all obvious how to fix this as a user.

Couldn't find another issue that directly reports this, so put it here.

Related are #1104 and #1077

**Comment by WeatherGod** [comment]
Orthographic projection was added as an option in https://github.com/matplotlib/matplotlib/pull/8326

Is that what you are looking for?

**Comment by eric-wieser** [comment]
No, I'm simply looking for correct perspective projection - the current implementation adds a linear distortion after projection, dependent on the aspect ratio of the window, which is something a perspective camera should never do.

**Comment by eric-wieser** [comment]
Orthographic projection is also broken:

![image](https://user-images.githubusercontent.com/425260/28371426-e25a10f0-6c94-11e7-8090-6fb38db8406e.png)

**Comment by WeatherGod** [comment]
Ah, I see what you mean. Ok, I'll look into your PR later today, then.
