### ISSUE TITLE
[subplot2grid] TypeError when using "fig" argument

### ISSUE THREAD

**Issue by smoneck** [matplotlib/matplotlib#8907]
### Bug report

**Bug summary**

`matplotlib.pyplot.subplot2grid` fails with `TypeError` when given a `figure`-argument.

**Code for reproduction**
```
import matplotlib.pyplot as plt

f = plt.figure()
ax1 = plt.subplot2grid((2, 2), (0, 0), colspan=2, fig=f)
```
It even fails for [this](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.subplot2grid.html):
```
import matplotlib.pyplot as plt

ax1 = plt.subplot2grid((2, 2), (0, 0), colspan=2, fig=None)
```
**Actual outcome**

```
Traceback (most recent call last):
  File "filename.py", line 4, in <module>
    ax1 = plt.subplot2grid((2, 2), (0, 0), colspan=2, fig=f)
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1292, in subplot2grid
    a = fig.add_subplot(subplotspec, **kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 1021, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
TypeError: __init__() got multiple values for argument 'fig'
```

**Matplotlib version**

  * Operating System: 4.11.6-3-ARCH
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): ---
  * Other Libraries: ---

Installed via official repositories.

**Comment by afvincent** [comment]
Looking at the source code of `plt.subplot2grid` for Matplotlib 2.0.2, it seems that *it simply uses the lastly active figure* (`fig = gcf()`) and is never expecting a "fig" argument (such a parameter is not mentioned in the docstring either). @smoneck Beware that you are looking at the *devdocs* version of the documentation, meaning the one for the latest master. A "fig" parameter was indeed added by #6179, and it is milestoned for the future 2.1 release.

Closing as it does not look like a bug to me. @smoneck Please feel free to reopen if you disagree.
