### ISSUE TITLE
Lack of date/unit support for barbs/quiver

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#8909]
It would be nice if the following worked (it doesn't as of 2.0.2 or master today):
```python
%matplotlib inline

from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

times = [datetime(2017, 7, 18, 12, i) for i in range(0, 60, 5)]
heights = np.linspace(0, 1000, 10)
t, h = np.meshgrid(times, heights)
u, v = np.random.randn(2, len(times), heights.size) * 20

fig, axes = plt.subplots(1, 1)
axes.barbs(t, h, u, v)
```
Currently that gives:
```pytb
TypeError: float() argument must be a string or a number, not 'datetime.datetime'
```
It's not surprising since none of the normal unit calls are done. It works fine if you do the work manually:
```python
%matplotlib inline

from datetime import datetime
from matplotlib.dates import date2num
import matplotlib.pyplot as plt
import numpy as np

times = [datetime(2017, 7, 18, 12, i) for i in range(0, 60, 10)]
heights = np.linspace(0, 1000, 10)
t, h = np.meshgrid(times, heights)
u, v = np.random.randn(2, len(times), heights.size) * 20

fig, axes = plt.subplots(1, 1)
axes.barbs(date2num(t), h, u, v)
axes.xaxis_date()
axes.set_xlim(datetime(2017, 7, 18, 12), datetime(2017, 7, 18, 13))
axes.grid(axis='x')
```

It'd be nice to have this work out of the box.

**Comment by dopplershift** [comment]
Here's what it looks like:
![barbs_dates](https://user-images.githubusercontent.com/221526/28342381-2ba3bca4-6bd5-11e7-9449-ff1f34c13e44.png)

**Comment by dstansby** [comment]
I may be wrong, but the x-axis is time, so I would expect the u-components of the barbs to be specified in timedeltas - (it makes no sense to work out the end of a barb using `datetime(2017, 7, 18, 12, 0) + 1`

**Comment by dopplershift** [comment]
No, in this case it's a time-height plot of the *horizontal* wind, so u,v are still x,y.  They're independent of the x, y coordinates.
