### ISSUE TITLE
line3D set_data only takes in x and y data

### ISSUE THREAD

**Issue by fragapanagos** [matplotlib/matplotlib#8914]
### Bug report

I was attempting to make an interactive 3D line plot in jupyter notebook, but noticed that line3D set_data method only takes in x and y data. 

**Code for reproduction**
The code below can be run outside of jupyter notebook to demonstrate the problem:
```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
x = [0, 1]
y = [0, 1]
z = [0, 1]
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
line = ax.plot(x,y,z)[0]
line.set_data([0,2], [0,2], [0,2])
plt.show()
```

**Actual outcome**

```
ValueError: too many values to unpack (expected 2)
```
**Expected outcome**

I would expect the set_data method exposed by line3D to take in 3 values.

**Matplotlib version**
  * Matplotlib Version: 2.0.0
  * Python Version: 3.6.0

**Comment by tacaswell** [comment]
I suspect you want to do this with the current `set_data` + `set_3d_properties` methods.

Exact work:

 - The `set_data` method needs to be over-ridden in `mpl_toolkits.mplot3D.art3D.Line3D`
 - add a test (does not raise should be enough)
 - bonus: also do `get_data`

**Comment by WeatherGod** [comment]
You can't override set/get_data. Those methods are widely used throughout
the codebase and elsewhere, and it is understood to mean the data as
displayed in the 2d coordinates. This is why we really need a new set/get
data method that is uniform across all artist types that refers to
something slightly different: getting and setting the raw data. For most 2d
artists, that would be synonymous with set/get_data.

**Comment by eeshugerman** [comment]
>You can't override set/get_data. Those methods are widely used throughout the codebase and elsewhere, and it is understood to mean the data as displayed in the 2d coordinates. This is why we really need a new set/get data method

In the meantime, should a `set_data_3d` method be added to `mpl_toolkits.mplot3D.art3D.Line3D`? I'm new, looking for something to get started with.

**Comment by PatrickHennis** [comment]
Just wanted to say that I am working with another student here at Christopher Newport University on fixing this issue
