### ISSUE TITLE
Subplot titles overlap x-axis labels in figure 1 of pylab/markevery example

### ISSUE THREAD

**Issue by RavingMadScientist** [matplotlib/matplotlib#8916]
### Bug report

**Bug summary**
The online example to demonstrate use of the 'markevery' attribute at https://matplotlib.org/examples/pylab_examples/markevery_demo.html has an ugly overlap between the rows of the GridSpec for figure 1, reproducible both online via Firefox 53.0.2, and from a fresh 2.0.2 mpl build. The fix requires a trivial readjust of the hspace for the first GridSpec, and will be completed momentarily. 

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System: Ubuntu 14.04
  * Matplotlib Version: 2.0.2
  * Python Version:
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by dstansby** [comment]
Fixed by #8918

**Comment by anntzer** [comment]
The problem with #8918 is that it makes the calls to tight_layout not work anymore, as shown by the warning when running the example or building the docs:
```
This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
```
The relevant line is in `tight_layout.get_subplotspec_list` (`elif gs.locally_modified_subplot_params(): subplotspec = None`: "if the user sets some params, then don't participate in tight_layout", which may not be a silly decision).

Reopening, at least for now.

**Comment by tacaswell** [comment]
This is what it looks like now: http://matplotlib.org/devdocs/gallery/lines_bars_and_markers/markevery_demo.html which seems like an improvement.

**Comment by anntzer** [comment]
My reopening of the bug was only about the need to avoid triggering mpl warnings (i.e., usually examples of questionable code) from within our own examples -- not about the layout itself, which I agree looks better now.

**Comment by timhoffm** [comment]
This is fixed by using constrained layout.

https://matplotlib.org/stable/gallery/lines_bars_and_markers/markevery_demo.html#sphx-glr-gallery-lines-bars-and-markers-markevery-demo-py
