### ISSUE TITLE
Separate plots in examples w/ multiple plots using ######

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8922]
Sphinx-gallery will render plots in sections if they are separated by a `#########` line. This makes it easier to read / follow examples that create multiple plots, putting them inline w/ the code instead of all placed at the top. Some examples don't have this line of `#####` put in there yet, so an easy first step is to insert it into any examples where it makes sense.

 these are examples with multiple calls to `plt.figure` or `plt.show` (that aren't already separated by `#####...`):

<details>

- [x] examples/animation/basic_example.py
- [x] examples/animation/basic_example_writer_sgskip.py
- [x] examples/api/sankey_basics.py
- [x] examples/axes_grid1/demo_fixed_size_axes.py
- [x] examples/axes_grid1/make_room_for_ylabel_using_axesgrid.py
- [x] examples/images_contours_and_fields/contour_demo.py
- [x] examples/images_contours_and_fields/contour_label_demo.py
- [x] examples/images_contours_and_fields/contourf_hatching.py
- [x] examples/images_contours_and_fields/quiver_demo.py
- [x] examples/images_contours_and_fields/tricontour_demo.py
- [x] examples/images_contours_and_fields/tripcolor_demo.py
- [x] examples/images_contours_and_fields/triplot_demo.py
- [x] examples/misc/contour_manual.py
- [x] examples/pylab_examples/demo_tight_layout.py
- [x] examples/pylab_examples/errorbar_limits.py
- [x] examples/pylab_examples/geo_demo.py
- [x] pylab_examples/hyperlinks_sgskip.py
- [x] examples/pylab_examples/markevery_demo.py
- [x] examples/pylab_examples/multipage_pdf.py
- [x] examples/pylab_examples/multiple_figs_demo.py
- [x] examples/pylab_examples/spine_placement_demo.py
- [x] pylab_examples/zorder_demo.py
- [x] examples/pyplots/fig_axes_customize_simple.py
- [x] examples/showcase/xkcd.py
- [x] examples/statistics/boxplot.py
- [x] examples/statistics/bxp.py
- [x] examples/units/ellipse_with_units.py

</details>

**Comment by ankit01ojha** [comment]
@choldgraf I would like to work on this. Do I need to change all the files mentioned? Is there any file where it is being used?

**Comment by choldgraf** [comment]
Just a subset is fine, though it should be relatively quick to do once you
get the hang of copy/pasting in the right spots!
--

**Comment by LindyBalboa** [comment]
I looked through the files which turned up from a `grep -r -L "################" * | xargs ag -c "ax1.show" | sort --field-separator=: -k 2` and it seems any files where this would apply have been handled by one PR or another. This can probably be closed.

**Comment by LindyBalboa** [comment]
I'm glancing through the files after a `grep -r -L "################" * | xargs grep -c "show" | sort --field-separator=: -k 2`. I've looked through all of the ones with 2 or more instances of "show" and these are the ones which I believe may be converted to this format with some refactoring and -could- benefit from it (but maybe not?). This list is by no means exhaustive, but it is focal point with some specific examples.

Exceptions may include:
ticks_and_spines/spines_dropped.py
ticks_and_spines/spines.py
ticks_and_spines/tick-formatters.py
ticks_and_spines/tick-locators.py
images_contours_and_fields/plot_streamplot.py
images_contours_and_fields/barcode_demo.py
text_labels_and_annotations/text_alignment.py
pie_and_polar_charts/pie_demo2.py
misc/demo_agg_filter.py
misc/customize_rc.py
lines_bars_and_markers/vline_hline_demo.py
lines_bars_and_markers/multicolored_line.py
images_contours_and_fields/pcolormesh_levels.py
images_contours_and_fields/image_nonuniform.py
images_contours_and_fields/contourf_demo.py
api/affine_image.py

**Comment by choldgraf** [comment]
Yep - feel free to cross reference your list with the one in the top-level of this thread and open some PRs! :-)

**Comment by LindyBalboa** [comment]
Maybe. I was intending on just taking a crack at your list, but saw that a lot had been done already (the two PRs I refd this to). So I decided to try and track down the files that still need it. I would appreciate if someone more senior the the project could take a glance through them and see if any of them _shouldn't_ be refactored before people go foreward editing them. 

Oh god, I just double checked the list. That formatting is aweful, I will fix that.

**Comment by choldgraf** [comment]
it shouldn't be too much work to add in the `####` where needed, so if you open a PR I am happy to give it a quick review and mention anywhere that it's unnecessary. But as a general rule I think that any code that generates >1 plots would benefit from having the output separated by `####` blocks

**Comment by ash13** [comment]
Hi, I want to work on this. Can someone help me to start of?

**Comment by ash13** [comment]
@choldgraf: Hi I tried adding the lines in the program list mentioned by you. Few of them already had it. The ones which din't have, I have added them.Please do let me know if I have to do any changes.
https://github.com/matplotlib/matplotlib/pull/9479

**Comment by jgtiu** [comment]
Hi, new contributor here, I'd like to work on this issue. Is this something you still need?

**Comment by timhoffm** [comment]
Yes, please go for the unchecked items in the details list of the original post.

**Comment by ardieorden** [comment]
Hi, I'd like to work on the `make_room_for_ylabel_using_axesgrid.py` item in the details list!

**Comment by timhoffm** [comment]
All handled.
