### ISSUE TITLE
quiver does not follow the color cycle

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#8924]
As of 2.0.2, quiver defaults to black arrows.  Given that e.g. streamplot (arguably a semantically related function) follows the color cycle (i.e., uses tab10 as the default color for the first plot), I would suggest that quiver should do the same.

**Comment by efiring** [comment]
Can you identify some quiver (and barb) users who would prefer this?  I suspect that by enforcing this in the name of consistency, you would merely be forcing most users to explicitly select black.

**Comment by anntzer** [comment]
My use case was plotting a quiver plot on top of a image of the underlying potential field that had been drawn using a grayscale colormap; in such a case it is convenient to have the arrows in a separate color (just like it is convenient to have the streamplot in a different color).

**Comment by efiring** [comment]
That's certainly a good use case, although I think that it illustrates why black is actually a pretty good default, even though it does not suit that case.  My suspicion is that when color is available and there is a colormapped field, more often than not the color map is not grayscale, so black for superimposed vectors is a reasonable default.  The default is just a starting point, and there is no default that will work well with all color maps underneath.  Blue is probably not very good with our default viridis--black is better, but not great, either.

I think defaulting to the color cycle makes the most sense for things that are actually likely to be cycled, like ordinary lines; quiver and barbs tend to be one-shot--just one per panel.  Streamplots are in the same category.

I won't dig my heels in on this one, but I would like to see what @weathergod and @dopplershift think.

**Comment by anntzer** [comment]
FTR I don't have a very strong opinion about this, and certainly wouldn't have argued for such a behavior if streamplot didn't provide as it does.  But now that we're here it feels strange to stop midway.

**Comment by timhoffm** [comment]
Since you usually don't use multiple quiver plots, cycling is not an important feature here. One could argue that the color should be the first color of the color cycle. However, the default black is almost as good. Changing the default would be an API break with little gain.

Thus closing.
