### ISSUE TITLE
LassoSelector Resizes the Y-axis When Setting the 'active' Attribute

### ISSUE THREAD

**Issue by macolby42** [matplotlib/matplotlib#8933]
### Bug report

**Bug summary**

When trying to make lassoing with LassoSelector on graphs toggleable via a key press event, it will resize the Y-axis thus distorting data.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import LassoSelector

def on_press_l(event):
    if event.key == 'l':
        if lasso.active:
            lasso.active = False
        else:
            lasso.active = True

data = np.random.rand(100, 2)

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(data[:,0], data[:,1], 'o', markersize=2)

lasso = LassoSelector(ax=ax)
fig.canvas.mpl_connect('key_press_event', on_press_l)

plt.show()
```

**Actual outcome**

Before Key Press:
![figure_1](https://user-images.githubusercontent.com/26264636/28573203-e1873518-7117-11e7-8672-59dedb6d194c.png)

After Key Press:
![figure_1-1](https://user-images.githubusercontent.com/26264636/28573211-e9932eba-7117-11e7-940a-2aaafab8f76f.png)

**Expected outcome**

When you press 'l' (lower-case L) the plot's Y-axis should remain unchanged.

**Matplotlib version**

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1

I used conda.

**Comment by tacaswell** [comment]
You are hitting the default key bindings where `'l'` is mapped to 'log scale y axis' (see https://matplotlib.org/users/navigation_toolbar.html#navigation-keyboard-shortcuts)

You can disable the binding of yscale to `'l'` by

```python
plt.rcParams['keymap.yscale'] = ''
```

in your `matplotlibrc` file (see https://matplotlib.org/users/customizing.html?highlight=keymap#a-sample-matplotlibrc-file) or by picking a different key.

ref: 

https://stackoverflow.com/questions/12774206/how-do-i-disable-the-keyboard-shortcuts-in-matplotlib
