### ISSUE TITLE
Default 2.0 style should have a name

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#8934]
The current default style should have a name, so that in future we can continue referring to this style even if defaults change again. This is important for example in pytest-mpl if we want to make sure the style stays the same with future Matplotlib versions.

**Comment by tacaswell** [comment]
`'mpl2'` ?  I am notoriously bad at naming things though.

**Comment by astrofrog** [comment]
I would say ``mpl20`` unless you can guarantee no default style changes without bumping the major version? I would then also add ``mpl15`` as an alias for ``classic`` for example?

**Comment by anntzer** [comment]
mpl20 sounds good.
Probably mpl10 then for classic (well it predates 1.0 but mpl00 seems silly :-)).

**Comment by tacaswell** [comment]
maybe `mpl15` as that is the version we started from?  I do not know how consistent the style from earlier versions was.
