### ISSUE TITLE
Add deploy key for CircleCI

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#8940]
CircleCI is currently missing a deploy key and thus cannot upload docs from `master` to the `devdocs` repo. We have an embedded [deploy key in the repo](https://github.com/matplotlib/matplotlib/blob/master/ci/travis/matplotlibDeployKey.enc), but it is encrypted. The key is saved in Travis environment variables, but those cannot be read from the UI and trying to extract it from a build is insecure.

So, the same steps will need to be taken to re-create the deploy key for `devdocs`, encrypt it and replace the one in the repo, add the keys to CircleCI's environment variables, and add the relevant decryption step to the build. Unfortunately, I do not have access to the deploy key settings to do this.

**Comment by QuLogic** [comment]
PS, anyone with a CircleCI login should go 'like' (press the heart) these two issues which affect us:
* [PR builds run on PR branch instead of merge commit](https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662), so all PRs opened before CircleCI was enabled run the default config which doesn't work.
* [Recursive artifact upload is slow](https://discuss.circleci.com/t/uploading-artifacts-recursively-is-exceptionally-slow/14558), costing us about 5-6 minutes per build (x2 for each PR).

**Comment by tacaswell** [comment]
@QuLogic I think I have added deploy keys on both sides.

**Comment by QuLogic** [comment]
Seems to be working now. Thanks @tacaswell.
