### ISSUE TITLE
Colorbar: 'shrink' not recognized at argument to colorbar when cax is specified

### ISSUE THREAD

**Issue by anandtrex** [matplotlib/matplotlib#8941]
### Bug report

Figure.colorbar doesn't recognize the argument 'shrink' when the cax argument is specified. If this is expected behaviour, the documentation does not mention it.

**Code for reproduction**

```python
a = np.random.rand(1000, 1000)
fig, (ax, cax) = plt.subplots(1, 2, squeeze=True)
im = ax.imshow(a)
fig.colorbar(im, cax=cax, shrink=0.4)
```

**Actual outcome**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input> in <module>()
      2 fig, (ax, cax) = plt.subplots(1, 2, squeeze=True)
      3 im = ax.imshow(a)
----> 4 fig.colorbar(im, cax=cax, shrink=0.4)

~/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/figure.py in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   1601                 cax, kw = cbar.make_axes(ax, **kw)
   1602         cax._hold = True
-> 1603         cb = cbar.colorbar_factory(cax, mappable, **kw)
   1604 
   1605         self.sca(current_ax)

~/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/colorbar.py in colorbar_factory(cax, mappable, **kwargs)
   1345         cb = ColorbarPatch(cax, mappable, **kwargs)
   1346     else:
-> 1347         cb = Colorbar(cax, mappable, **kwargs)
   1348 
   1349     cid = mappable.callbacksSM.connect('changed', cb.on_mappable_changed)

~/.virtualenvs/test/lib/python3.5/site-packages/matplotlib/colorbar.py in __init__(self, ax, mappable, **kw)
    924                 kw['alpha'] = mappable.get_alpha()
    925 
--> 926             ColorbarBase.__init__(self, ax, **kw)
    927 
    928     def on_mappable_changed(self, mappable):

TypeError: __init__() got an unexpected keyword argument 'shrink'
```

**Expected outcome**

That either it accepts the 'shrink' argument or the documentation reflects this behaviour.

**Matplotlib version**
  * Operating System: macOS Sierra
  * Matplotlib Version: 2.0.2
  * Python Version: 3.5.4
  * Jupyter Version (if applicable): 5.1.0
  * Other Libraries: 

Everything installed from pip.

**Comment by efiring** [comment]
This is expected, so it should be clarified in the docstring.  'shrink' applies only to the case where the colorbar is making its own Axes by stealing space from the Axes in which the mappable resides.

**Comment by tacaswell** [comment]
- Document that `cax` and `shrink` are incompatibly kwargs (the docs are actually in `colorbar.py` and injected into pyplot / figure at run time).

**Comment by navdeeprana** [comment]
I have documented it and submitted a pull request. Since this is my first teeny-tiny contribution, any suggestions are welcome.

**Comment by navdeeprana** [comment]
Fixed.

https://github.com/matplotlib/matplotlib/pull/9456

**Comment by jklymak** [comment]
Thanks @navdeeprana!
