### ISSUE TITLE
qt5 from jupyter qtconsole

### ISSUE THREAD

**Issue by eflanigan00** [matplotlib/matplotlib#8942]
I can't use %matplotlib qt5 form jupyter qtconsole

I get errors the following:

    Anaconda3-4.4.0/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py in <module>()
        139     # have been changed in the above if block
        140     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
       --> 141         from PyQt4 import QtCore, QtGui
         142 
         143         try:

    ModuleNotFoundError: No module named 'PyQt4'

I'm using anaconda 4.4.0 on RHEL 7.
There are no qt4 libraries installed (that I know of).

It may be related to this:

https://github.com/ContinuumIO/anaconda-issues/issues/1068

**Comment by tacaswell** [comment]
can you please provide the full traceback?

Can you `import PyQt5`?

Do you have anything in your `matplotlibrc` file?

This is almost certainly a configuration / installation issue.

**Comment by eflanigan00** [comment]
I think you are correct tacaswell about configuration. 
I deleted all my .ipython .matplotlib folders and it is working.
Sorry for the confusion.

**Comment by tacaswell** [comment]
Glad to hear it got sorted out!

The combination of backend + qt selection is surprisingly tricky, we probably should have better error reporting, but it is not clear what combinations of setting + installed packages are going to cause the problems and what to do about them.
