### ISSUE TITLE
The results have a deviation

### ISSUE THREAD

**Issue by fengdong110** [matplotlib/matplotlib#8945]
HI dear:
      Now I have a problem:
              I use the sample procedure, different computer. 
              A computer result like:
![image](https://user-images.githubusercontent.com/19946295/28659580-94880cac-72e2-11e7-8137-8ed31f178ea6.png)
             B computer result like:
![image](https://user-images.githubusercontent.com/19946295/28659636-c719ad1a-72e2-11e7-8e39-9d282b6197ce.png)
              First, this is differenet samples, I just want to know: Why the line became thicker.
              Whether the lack of the module??   Lack what module ???    3Q !

**Comment by efiring** [comment]
It looks like the first figure was made using matplotlib version 1.5.x or earlier, and the second with 2.0.x. See http://matplotlib.org/users/dflt_style_changes.html.
