### ISSUE TITLE
BUG: PathCollection.set_alpha causes colormap to be lost

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#8953]
### Bug report

**Bug summary**

When calling ``s = plt.scatter(...)`` and then setting ``s.set_alpha(...)``, any colormap information is lost.

**Code for reproduction**

If I run:

```python
s = plt.scatter([1, 2, 3], [3, 4, 5], c=[2, 4, 5], cmap=plt.cm.viridis)
```

I get:

<img width="752" alt="screen shot 2017-07-28 at 21 24 35" src="https://user-images.githubusercontent.com/314716/28735041-76650834-73db-11e7-8179-a98daae9d67e.png">

So far so good. But if I now run:

```python
s.set_alpha(0.8)
```

all the markers change to blue:

<img width="752" alt="screen shot 2017-07-28 at 21 24 40" src="https://user-images.githubusercontent.com/314716/28735058-8b2a31cc-73db-11e7-8078-7795d716c3d6.png">

**Expected outcome**

Calling ``set_alpha`` should change the transparency, but not the colors.

**Matplotlib version**

  * Operating System: MacOS X 10.11.6
  * Matplotlib Version: 2.0.2.post4456+g591a9e034
  * Python Version: 3.6.1

**Comment by tacaswell** [comment]
attn @efiring it looks like you touched this last.

**Comment by tacaswell** [comment]
I have a fix, hopefully I'll get it up before I have to transfer trains.

**Comment by tacaswell** [comment]
as a work-around `s.set_array(s.get_array())` will fix it.

**Comment by WeatherGod** [comment]
ping? you said you have a fix?

**Comment by tacaswell** [comment]
it is in #8954
