### ISSUE TITLE
Folder ordering for the examples / tutorials page

### ISSUE THREAD

**Issue by choldgraf** [matplotlib/matplotlib#8958]
Now that sphinx-gallery supports sub-folder sorting within a gallery, let's re-organize examples / tutorials to make sure that the most important folders come first.

Do folks have an opinion about which folders should be at the top? If not I'll take a stab at a PR that seems to make the most sense to me.

Also I don't think that tutorials really need reordering. BUT, we could remove the `01_` and `02_` etc if wanted, since those were used for ordering below. Thoughts?

**Comment by dstansby** [comment]
I might be imagining things, but did things get re-ordered in a recent(ish) PR?

**Comment by choldgraf** [comment]
ah yep: https://github.com/matplotlib/matplotlib/pull/8975
