### ISSUE TITLE
Documentation for plotting categorical variables does not work.

### ISSUE THREAD

**Issue by blackfist** [matplotlib/matplotlib#8959]
### Bug report

**Bug summary**
When following [the documentation on plotting categorical variables](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/categorical_variables.html) the plots do not render. Instead various errors are thrown about converting strings to floats.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

data = {'apples': 10, 'oranges': 15, 'lemons': 5, 'limes': 20}
names = list(data.keys())
values = list(data.values())

fig, axs = plt.subplots(1, 3, figsize=(9, 3), sharey=True)
axs[0].bar(names, values)
axs[1].scatter(names, values)
axs[2].plot(names, values)
fig.suptitle('Categorical Plotting')
```

**Actual outcome**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-c50911b594df> in <module>()
      4 
      5 fig, axs = plt.subplots(1, 3, figsize=(9, 3), sharey=True)
----> 6 axs[0].bar(names, values)
      7 axs[1].scatter(names, values)
      8 axs[2].plot(names, values)

/Users/kevin.thompson/venv3/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1896                     warnings.warn(msg % (label_namer, func.__name__),
   1897                                   RuntimeWarning, stacklevel=2)
-> 1898             return func(ax, *args, **kwargs)
   1899         pre_doc = inner.__doc__
   1900         if pre_doc is None:

/Users/kevin.thompson/venv3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in bar(self, left, height, width, bottom, **kwargs)
   2103         if align == 'center':
   2104             if orientation == 'vertical':
-> 2105                 left = [left[i] - width[i] / 2. for i in xrange(len(left))]
   2106             elif orientation == 'horizontal':
   2107                 bottom = [bottom[i] - height[i] / 2.

/Users/kevin.thompson/venv3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in <listcomp>(.0)
   2103         if align == 'center':
   2104             if orientation == 'vertical':
-> 2105                 left = [left[i] - width[i] / 2. for i in xrange(len(left))]
   2106             elif orientation == 'horizontal':
   2107                 bottom = [bottom[i] - height[i] / 2.

TypeError: unsupported operand type(s) for -: 'str' and 'float'
```

**Expected outcome**

I expected it to render the pretty pictures found in [the documentation I was trying to duplicate](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/categorical_variables.html)

**Matplotlib version**
  * Operating System: OSX 10.11.6 (El Capitan)
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.0
  * Jupyter Version (if applicable): 4.3.0

Installed via pip in a virtualenv

**Comment by tacaswell** [comment]
Because the categorical plotting in only on the master branch (and will be released in 2.1).  For now either be patient (2.1 will be 'soon') or install form source.

**Comment by danielhernanrico** [comment]
Then this must be a bug on the documentation. Is really frustrating for a newbye try something that is in the manual.

**Comment by jklymak** [comment]
You need to use the manual that is appropriate for your version of matplotlib. Categorical support is new for 2.1 so you can’t expect it to work in old versions.  The old manual is available.

**Comment by bradleyrobinson** [comment]
Older manuals said the same thing. So there must be something wrong with older documentation as well.
