### ISSUE TITLE
_tkinter.TclError: unknown color name "base00"

### ISSUE THREAD

**Issue by ZakKurasov** [matplotlib/matplotlib#8960]
Hello, guys.

I just want to try plot some data from pandas. So, I have such code for plotting:
```
plt.figure()
plt.plot(frame['ts'], frame['buyingPrice'])
plt.plot(frame['ts'], frame['sellingPrice'])
plt.savefig("12389.png")`
In result, after running, I get an error:
`Traceback (most recent call last):
  File "analyze.py", line 15, in <module>
    plt.figure()
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "base00"
````

I have Python 3.6.1. ArchLinux x64, LXDE.

[TAC edited to change markup]

**Comment by tacaswell** [comment]
This seems to be an issue with the underlying installation of Tk / it's configuration.

https://github.com/cpbotha/nvpy/issues/79
https://bugs.launchpad.net/ubuntu/+source/tix/+bug/371720
http://forums.fedoraforum.org/showthread.php?t=233283

**Comment by anntzer** [comment]
@NexiePrado Are you using solarized by any chance?

**Comment by anntzer** [comment]
Closing as likely an issue with solarized messing with Xresources colors.  Feel free to request a reopen if the comments above do not apply.

**Comment by liubamboo** [comment]
I have the same problem. so anybody solve it?

**Comment by tacaswell** [comment]
xref with traceback: https://github.com/JiawangBian/SC-SfMLearner-Release/issues/66

@liubamboo  can you try

```bash
python -mtkinter
```

from a prompt?

**Comment by liubamboo** [comment]
@tacaswell yes, I run python -mtkinter. and a small window appear and says:"This is Tcl/Tk version 8.6 This should be a cedilla:"

**Comment by jklymak** [comment]
I'll close as 8.6 has known issues.  Feel free to ask for a reopen if this is still an issue
