### ISSUE TITLE
Add alias for colormaps for grey vs gray English issues

### ISSUE THREAD

**Issue by erinleeryan** [matplotlib/matplotlib#8965]
### Bug report

**Bug summary**

The current colormap options reflect American English spellings for 2/3 of the colormaps with a flavor of gray. An alias to the gray definitions using the standard UK spelling of grey would be helpful.

Colormaps that would need aliases for the UK spelling include:
gray, gray_r, nist_gray, nist_gray_r

Colormaps that use the UK spelling and would want an American English alias are:
Greys, Greys_r

**Comment by anntzer** [comment]
I don't mind making things uniform by moving towards either direction (well I have no horse in this game :-)) but I'm quite strongly against adding more aliases -- it's not as it matplotlib's API ever claimed to be localized anyways (I'm not a native English speaker but I'm not going to complain that I have to write `plot(...)` instead of `représente_graphiquement(...)`).

**Comment by WeatherGod** [comment]
Just to note, this discrepancy appeared during my tutorial right after I
pointed out that any instances of "gray" in a colorname can also be "grey".
So, the colormaps are inconsistent with the colors system, in this respect.

**Comment by dopplershift** [comment]
In general, I'm against more helper aliases. In this case however, it's a pretty annoying usability flaw. The cost of adding the alias is much less than the annoyance this causes new users, or even repeat users, like me.

**Comment by timhoffm** [comment]
We should do this. This is a usability issue and a consistency issue (color names supporting both but coloraps names not).

Implementation:  I suggest to just re-register the colormaps with the respective other name. This should be done in https://github.com/matplotlib/matplotlib/blob/b3bd929cf07ea35479fded8f739126ccc39edd6d/lib/matplotlib/cm.py#L33, which also creates the reverse colormaps.

**Comment by anntzer** [comment]
Sure, I don't really mind anymore.
Note, however, that there's currently both "gray" and "Greys" which are *not* the same colormaps ("gray" is plain linear, "Greys" is not).  There's also gist_gray, which is I think(?) exactly the same as "gray" (and gist_yarg, which is the same as "gray_r").

**Comment by oscargus** [comment]
We just have to make sure that `gist_yarg` is aliased to ` gist_yerg`...

**Comment by timhoffm** [comment]
> We just have to make sure that `gist_yarg` is aliased to ` gist_yerg`...

And `matplotlib` to `metplotlib` 🤣

**Comment by rcomer** [comment]
> And `matplotlib` to `metplotlib` 🤣 

As [MetOffice](https://github.com/MetOffice) representative, I approve this plan 😆

**Comment by madeira-dev** [comment]
Hi! I was thinking about starting to contribute to this repository and found this good first issue which does not seems too difficult, although I also noticed that not everyone agrees on this issue about adding more aliases, so I would like to know if I can work on this issue or isn't necessary anymore?

**Comment by tacaswell** [comment]
This is still an open issue and I read this as a consensus that we should add the alias, however as part of the work there needs to be an accounting of all the colourmaps that involve the work "gr[ae]y" in their name to make sure that none of the names that reasonable _expect_ to be aliases of each other are infact aliases of each other.




It took me a while to sort out that `gist_yarg` is gray backwards 🤦🏻

**Comment by madeira-dev** [comment]
Hello, sorry for the delay.
I got some time to check this issue and I came to a solution that seems maybe too simple to say that I've fixed, but I also did some tests and apparently this part is working as expected.

In the function that was mentioned above, I added this last line to assure both gr[ae]y would result in the same colormap:
![Screenshot from 2023-05-22 18-29-13](https://github.com/matplotlib/matplotlib/assets/69992340/715c6500-3eb9-45c4-be6f-b31dd929ed73)

And I tested it with this:
![image](https://github.com/matplotlib/matplotlib/assets/69992340/2638f06f-6836-482c-a895-665a27888f86)



When changing the "cmap" arg in pcolor() I get the same colormap for gray and grey

With gray:
![image](https://github.com/matplotlib/matplotlib/assets/69992340/0f40989c-3458-4391-ae6d-6b51797d34e3)

With grey:
![image](https://github.com/matplotlib/matplotlib/assets/69992340/6b7f016b-0de1-4190-b177-9c66476bef48)

Please, let me know if this is a possible fix or if I should take a different approach.
