### ISSUE TITLE
Pyplot crashes 32 bit python

### ISSUE THREAD

**Issue by aquirdTurtle** [matplotlib/matplotlib#8967]
### Bug report

**Bug summary**

Any plotting utility in pyplot crashes 32-bit python. 64-bit works fine.

**Code for reproduction**

I can reproduce this in just a bare-bones python shell, by clicking python.exe. The same thing occurs in, for example, a jupyter notebook. I've reproduced this on both of the 2 computers that I have access to. Both occur on fresh installs of 32-bit anaconda distribution.

```python
from matplotlib.pyplot import *
figure()
# python then crashes. Any other command from pyplot also crashes python:
# plot(1)
# gca()
# axvline(1)
# xlabel("stuff")
# etc.
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/4393192/28758365-e524f594-7553-11e7-99b6-af9338bee2e1.png)

**Expected outcome**

a plot.

**Matplotlib version**

  * Operating System: Windows 10 64 bit
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Other Libraries: Anaconda version: 4.4.0 (32 bit)

I installed matplotlib via installing the anaconda distribution.

**Comment by tacaswell** [comment]
Can you get any sort of traceback as to where it is crashing?

**Comment by omarkb93** [comment]
If I open visual studio 2017 to debug the error, than I can get a bit more info:

![image](https://user-images.githubusercontent.com/4393192/28763432-3a3a01ba-757b-11e7-9e07-372dfeb45017.png)

and the disassembly looks like this:

![image](https://user-images.githubusercontent.com/4393192/28763483-b02e9660-757b-11e7-932b-7e688d101214.png)


While getting visual studio up, at various times it also told me

![image](https://user-images.githubusercontent.com/4393192/28763459-79fafbd8-757b-11e7-9f99-57c91b6624bc.png)

I hope this helps. I'm not sure where the symbols are for these files are; let me know if there's anything else I can do to help.

**Comment by efiring** [comment]
Have you raised this on the anaconda@continuum.io mailing list?  This doesn't look to me like anything that we can address.  Maybe it is a problem with the specific anaconda packages.

**Comment by omarkb93** [comment]
Okay, I'll do that.

**Comment by QuLogic** [comment]
This is pretty old, and I expect it's fixed by now. Please comment/re-open if that's not the case.
