### ISSUE TITLE
plot with solid line overhangs fill_between

### ISSUE THREAD

**Issue by LindyBalboa** [matplotlib/matplotlib#8974]
When overlaying plot upon a fill_between, the line hangs over the ends. This is most notable with the solid linestyle, but affects all of them. Minor detail but seriously decreases the quality factor of a plot.

```
import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np 

mpl.rc('lines', linewidth=10) #optional to improve visibility
plt.cla()
x=np.linspace(0,1,1000)
y=x
plt.plot(x,y,zorder=2, color='k')
plt.fill_between(x,y+.05,y-.05, color='r', zorder=1)

y=x+0.5
plt.plot(x, y, color='k', zorder=2, linestyle="--")
plt.fill_between(x,y+.05,y-.05, color='r', zorder=1)

y=x+1
plt.plot(x, y, color='k', zorder=2, linestyle=":")
plt.fill_between(x, y+.05, y-.05, color='r', zorder=1)

y=x+1.5
plt.plot(x, y, color='k', zorder=2, linestyle="-.")
plt.fill_between(x, y+.05, y-.05, color='r', zorder=1)

plt.show()
```

```python
# Paste your code here
#
#
```

**Outcome**
![untitled](https://user-images.githubusercontent.com/20605205/28827127-78a181d6-76c4-11e7-90ad-e00f93ad3226.png)

**Expected outcome**
![untitled1](https://user-images.githubusercontent.com/20605205/28827186-a6b1e5fc-76c4-11e7-8945-89ce034f598c.png)

**Matplotlib version**

  * Operating System: cygwin64 fresh install
  * Matplotlib Version:  2.0.2
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): 5.0.0
  * Other Libraries: 

installed from pip

**Comment by WeatherGod** [comment]
I don't see how this is a bug, per se. It isn't like the line is aware of
the fill_between's polygon. You should be able to specify a clip path for
the line using the polygon returned by fill_between, though.

**Comment by WeatherGod** [comment]
Another option, for a slightly different effect, is to simply plot a very
thick solid red line first, then the thinner black lines on top. While the
edges won't be vertical, they will line up.

**Comment by anntzer** [comment]
I agree that this is definitely not a bug.

**Comment by LindyBalboa** [comment]
Okay sorry it was the end of the work day and I lost the forest for the trees. This behavior itself definitely isn't a bug. They are separate things that don't know about each other. That is true, but it seems odd to me that such a simple thing requires so much roundabout work. 

What I would like to see is an additional capstyle that gives the option of a `vertical` cut on the line ends. I haven't browsed the code to see how feasable this is, but I don't think it seems unreasonable.

**Comment by LindyBalboa** [comment]
Okay sorry it was the end of the work day and I lost the forest for the trees. This behavior itself definitely isn't a bug. They are separate things that don't know about each other. That is true, but it seems odd to me that such a simple thing requires so much roundabout work. 

What I would like to see is an additional capstyle that gives the option of a `vertical` cut on the line ends. I haven't browsed the code to see how feasable this is, but I don't think it seems unreasonable.

**Comment by LindyBalboa** [comment]
As for the solution to my original problem, the answer is here: http://matplotlib.org/examples/pylab_examples/image_clip_path.html

with the critical lines:
```
patch = PathPatch(path, facecolor='none')
plt.gca().add_patch(patch) 
```
Comment on line 1: For the desired effect here, `edgecolor` must also be set to `'none'`. 
Comment on line 2: Absolutely necessary. I missed this part when trying to do it from the docs, before I found the example. Perhaps it would be wise to add to the docs a comment that the patch has to exist in the axes? It makes sense after seeing it, but it wasn't intuitive for me to go that direction, not having an indept knowledge of patches

That being said, it appears that there is still about a 1px offset.

![image](https://user-images.githubusercontent.com/20605205/28867433-6c764aec-7776-11e7-9ac5-29c9dd488f55.png)
```
from matplotlib import pyplot as plt
import numpy as np

x = np.linspace(0,1,1000)

plt.plot(x,x, linewidth=4, zorder=2, color='k')
plt.fill_between(x,x+0.05,x-0.05, color='r')

l = plt.gca().lines[0]
p = plt.gca().collections[0]

path = p.get_paths()[0]
patch = mpl.patches.PathPatch(path, facecolor='none', edgecolor='none')
plt.gca().add_patch(patch)
l.set_clip_path(patch)
```

**Comment by WeatherGod** [comment]
The 1px offset might be due to snapping. Setting snap=False might fix that.

As for new capstyles, that might be interesting to see if such caps are
possible.

**Comment by anntzer** [comment]
capstyles are usually defined pretty deep into the rasterizer so good luck with that.

Instead of creating your own pathpatch and adding it you can do
```
import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np

x = np.linspace(0,1,1000)

plt.plot(x,x, linewidth=4, zorder=2, color='k')
plt.fill_between(x,x+0.05,x-0.05, color='r')

l = plt.gca().lines[0]
p = plt.gca().collections[0]

l.set_clip_path(p.get_paths()[0], p.get_transform())

plt.show()
```

**Comment by WeatherGod** [comment]
Let's not encourage accessing `lines` and `collections` for this purpose.
Just do:

```
l, = plt.plot(x, x, linewidth=4, zorder=2, color='k')
p = plt.fill_between(x, x+0.05, x-0.05, color='r')
```

**Comment by anntzer** [comment]
agreed (I just copy pasted the original example and changed the clipping part)
