### ISSUE TITLE
How to easily set the location and size of a sub_axes?

### ISSUE THREAD

**Issue by gepcel** [matplotlib/matplotlib#8986]
The problem comes from me drawwing a map via cartopy. I want to add a little sub_axes on the lower_right corner of the main axes. But it seems hard to set the location and size of the sub_axes.

The first thing I tried was `fig.add_axes()`. But it doesn't accept `transform` args, while the [document](http://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.add_axes) says it should. Without the `transform` args, the location (left, bottom) and size (width, height) wasn't on the transform of `ax`.

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)
ax2 = fig.add_axes([0.8, 0, 0.2, 0.2], transform=ax.transAxes, projection='rectilinear') 
```

The second I tried was `inset_axes`, which was very easy to use. But it doesn't accept `projection` args.
```python
from mpl_toolkits.axes_grid.inset_locator import inset_axes
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)

# The following line doesn't work
ax2 = inset_axes(ax, width='20%', height='20%', axes_kwargs={'projection': 'rectilinear'})
# Doesn't work neither:
ax2 = inset_axes(ax, width='20%', height='20%', projection='rectilinear')
```

I may get what I want by `ax.get_position()`, the set the position according it.

**Comment by jklymak** [comment]
```
fig, ax = plt.subplots(1, 1)
box = matplotlib.transforms.Bbox.from_bounds(0.8, 0, 0.2, 0.2)
ax2 = fig.add_axes(fig.transFigure.inverted().transform_bbox( ax.transAxes.transform_bbox(box)))
```

but it *is* a bit roundabout...

**Comment by gepcel** [comment]
This works without a `projection`. But with a `projection` is doesn't. Like following:
```python
import cartopy.crs as ccrs
fig, ax = plt.subplots(1, 1, subplot_kw={'projection': ccrs.PlateCarree()})
box = mpl.transforms.Bbox.from_bounds(0.8, 0.8, 0.2, 0.2)
ax2 = fig.add_axes(fig.transFigure.inverted().transform_bbox(ax.transAxes.transform_bbox(box)), projection=ccrs.PlateCarree())
```
I got this:
![image](https://user-images.githubusercontent.com/4179106/28995809-92480470-7a25-11e7-83b3-6247d12d8502.png)


I tried to give a miminal example, sorry for the [`cartopy`](https://github.com/SciTools/cartopy) import.

**Comment by jklymak** [comment]
I think cartopy returns a geoaxes object which is a superset of axes.   Not sure, but maybe this is a cartopy question/issue. I can't test right now if this is an issue with vanilla matplotlib projections, nor do I understand exactly what they do.

**Comment by gepcel** [comment]
@jklymak  Thanks.
Is there a way I can anchor the top right point ([1.0, 1.0]) of  `ax2` at the top right corner of `ax1` ([1.0, 1.0])?
 Then the position or size of `ax2` won't matter that much.

**Comment by jklymak** [comment]
Again don't have a computer right now so I don't know but I suspect the issue is that the parent axis gets redrawn by the projection but the child axis has no way to know this and gets put in the location it would be at if the parent axis wasn't a projection.  

I've been playing with a geometry manager that should let you line axes up, but only if the new axes positions get set during the projection.  I'm not really familiar w the projection code so again, id bug the cartopy folks.  Or set the child position by hand.  

Cheers. Jody.

**Comment by QuLogic** [comment]
The plot you obtained is "correct" in that those really _are_ the limits of the axes space, but Cartopy has turned off the axis spines and ticks and is drawing its own boundary which is not necessarily "full" (this is how you can get complicated maps like Interrupted Goode Homolosine).

If you want to do something based on that boundary, you can do something like call `ax.get_extent()`, and calculate some relative position based on that. It will be in data space, so you would need to apply a transform into figure coords (possibly `ax.transAxes`, but I have not tried.)

**Comment by jklymak** [comment]
One wonders if cartopy could return the extent of the spines somehow.   I've been thinking about layout management and lining up spines is a pretty important part of layout.

**Comment by gepcel** [comment]
I may have figured out an answer. For someone who may run into the same problem, [here](https://stackoverflow.com/questions/45527584/how-to-easily-add-a-sub-axes-with-proper-position-and-size-in-matplotlib-and-car/45538400#45538400) is a working solution.
