### ISSUE TITLE
set_facecolor method does not auto-update in ipython

### ISSUE THREAD

**Issue by FaustinCarter** [matplotlib/matplotlib#9007]
### Bug report

**Bug summary**

While using interactive plotting via `ipython --pylab` (both 5.0 and 6.0), the `set_facecolor` (new version of `set_axis_bgcolor`) method does not automatically update the displayed figure with the new color. After the user interacts with the figure (i.e. zooms, pans, etc) the figure is updated with the new background color. The same behavior is apparent with a call to the deprecated method `set_axis_bgcolor`.

This is a new problem for matplotlib 2.0.x. In 1.5.x the interactive figure's background immediately updates with a call to `set_axis_bgcolor`.

**Code for reproduction**

In the bash terminal:
```bash
ipython --pylab
```

In the ipython session
```python
fig = plt.figure()
ax = fig.add_subplot(111)
ax.set_facecolor('red')
```

**Actual outcome**

The figure window axis background stays white until the user interacts with the figure.

**Expected outcome**

The axis background should immediately become red.

**Matplotlib version**

  * Operating System: OSX 10.11.6
  * Matplotlib Version: 2.0.2, via conda (default channel)
  * Python Version: tested on 2.7 and 3.6
  * IPython Version: tested on 5.0 and 6.0

**Comment by tacaswell** [comment]
For some reason the stale flag is not propgating up from the patch to the axes (and to the figure), that is odd...

**Comment by WeatherGod** [comment]
The axes patch might not be considered a child artist, perhaps?

**Comment by MaozGelbart** [comment]
Works fine for me on OSX with matplotlib 3.3.0, python 7.15.0 and python 3.8.3

**Comment by jklymak** [comment]
Yes works for me as well, Qt5Agg.  I'll close, but others should feel free to reopen if an issue w/ other backends.

**Comment by EmptyString1999** [comment]
Hi, I'm having this error appear in my code, recreated the same way, my system specs are 

`MacOS Monterey
Apple M1 chip
8GB RAM`

would you please be able to investigate this
