### ISSUE TITLE
log-scaled Exception when pressing L-key

### ISSUE THREAD

**Issue by voxspox** [matplotlib/matplotlib#9020]
When pressing the L-key an exception is raised:
ValueError: Data has no positive values, and therefore can not be log-scaled.

This was first confusing for me because I wanted to use this key for some action and was faced with this (unrelated) exception. It seems that the L-key is already bound to some log-scaling function.

I suggest to catch this exception if it was called by a short-key handler.

matplotlib 2.0.2

ValueError: Data has no positive values, and therefore can not be log-scaled.
  File ".../env/lib/python3.5/site-packages/matplotlib/ticker.py", line 1956, in tick_values

**Comment by fariza** [comment]
If you are using your own shortcuts, I would suggest to disable the default key_press_handler
Somewhere in the doc it states
```
To disable default key press handling::
            manager, canvas = figure.canvas.manager, figure.canvas
            canvas.mpl_disconnect(manager.key_press_handler_id)
```
Simpler option would be to look for non used keys.

**Comment by fariza** [comment]
The behaviour is the right one, it raises an error because it tries to apply a logarithmic scale.
Please see above comment on how to bypass/solve your problem.

I am closing this issue, but feel free to open it again if you still feel this is a bug

**Comment by voxspox** [comment]
I found the disable default key press handling in some [old docs](https://matplotlib.org/1.3.1/api/backend_bases_api.html#matplotlib.backend_bases.FigureManagerBase.key_press_handler_id). But this is gone in the [current docs](https://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.FigureManagerBase).

**Comment by fariza** [comment]
The missing documents is indeed a bug
