### ISSUE TITLE
Wrong x coordinates in pyplot.hist

### ISSUE THREAD

**Issue by danipozodg** [matplotlib/matplotlib#9023]
### Bug report

**Bug summary**
Histogram x-coordinates are not correct. They are different from the ones obtained by extracting the `bins` and plotting them with `pyplot.bar`.

**Code for reproduction**

```python
# img2 is a grayscale image
b, bins, patches = plt.hist(img2, 256)
plt.xlim([0,255])

bars = plt.bar(range(0,256), b)
```

**Actual outcome**

This is the outcome of the first graph:
![image](https://user-images.githubusercontent.com/15173583/29234909-cf2e10b2-7efa-11e7-836e-c2b551fe70a0.png)

**Expected outcome**

And this the one of the second:
![image](https://user-images.githubusercontent.com/15173583/29234918-df8aae0c-7efa-11e7-8d38-b1b1be8c909b.png)

**Matplotlib version**

  * Operating System: Manjaro Linux 17.0.2
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6
  * Jupyter Version (if applicable):
  * Other Libraries: 

I'm using matplotlib and Python packages from Manjaro repositories.

**Comment by tacaswell** [comment]
It looks like your data range is not actually [0, 255], but [0, 170].  You asked for 256 bins so each of your bins is less than 1 wide (which is also why you have the white spaces, if your data is integers, then there is no data between ex [10.1, 10.9]).

The second argument returned is the actual bin edges.

Please see http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hist.html?highlight=hist#matplotlib.axes.Axes.hist

If you have more questions I suggest subscribing to the [mailing list](https://mail.python.org/mailman/listinfo/matplotlib-users) and continuing the discussion there.
