### ISSUE TITLE
Error when trying to use pydub package 

### ISSUE THREAD

**Issue by ngragaei** [matplotlib/matplotlib#9045]
I am using Jupyter notebook and python 3.5 and i am trying to import pydub library. I downloaded and installed it but i have an error when using it. Anyone can help. 
Thanks

**Code for reproduction**

```python
#
import pydub
from pydub import AudioSegment
#
#
```

**Actual outcome**

```
# ImportError                               Traceback (most recent call last)
<ipython-input-24-66c539a2e6ca> in <module>()
      1 import pydub
----> 2 from pydub import AudioSegment

ImportError: cannot import name 'AudioSegment' 
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 
  * Python Version:
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by dstansby** [comment]
This is the bug tracker for Matplotlib, it looks like this should be reported here: https://github.com/jiaaro/pydub#bugs--questions

**Comment by ngragaei** [comment]
okkk thanks
