### ISSUE TITLE
Improper scaling on low-res display when a hi-res display is also present on the system

### ISSUE THREAD

**Issue by burnpanck** [matplotlib/matplotlib#9062]
### Bug report

**Bug summary**

This is a follow up on #8061, which was closed in #8931. That PR resolves updating the figure bounds when the figure is moved between displays with different resolutions. However, the issue persists that figures on the low-res display have way too large line widths and text sizes when a retina screen is present.

**Matplotlib version**

  * Operating System: OS X 10.12.6
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.1
  * Other Libraries: Qt 

**Screen shots**
The following two screenshots are taken from the same window, after moving it on either of my two screens.

On the MacBook Pro's retina screen:
<img width="478" alt="on hi-res display" src="https://user-images.githubusercontent.com/1310437/29508933-b82a8090-8656-11e7-83f9-2d137abb6020.png">

On the additional 2k 27in screen:
![on lo-res display](https://user-images.githubusercontent.com/1310437/29508938-bad3ae3e-8656-11e7-8f7e-ed2534b92cc0.png)

[TAC edited to fix xref]

**Comment by tacaswell** [comment]
Can you include some screenshots?  I do not really understand the issue (and do not have a mac to test on).

**Comment by tacaswell** [comment]
@burnpanck Can you try with current master?

**Comment by tacaswell** [comment]
attn @astrofrog can you reproduce this?

**Comment by dstansby** [comment]
Will check this out when I have my Macbook to hand

**Comment by astrofrog** [comment]
I'm traveling but will try and test this in a few days

**Comment by dstansby** [comment]
Hmm, I don't think I'm seeing this on the latest master branch. All I'm doing is
```python
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.scatter(1, 1)
plt.show()
```
and then moving between a retina and low-res screen, and everything seems to scale nicely. Let me know if there's other code I could try out.

**Comment by burnpanck** [comment]
I see, I'll therefore give it a shot with latest master too!

**Comment by astrofrog** [comment]
@burnpanck - are you still seeing this issue with Matplotlib 2.2? (it should be fixed)

**Comment by burnpanck** [comment]
No, I don't see the issue anymore either. I'll close the issue therefore. Thanks for all the good work!
