### ISSUE TITLE
matplotlib quiver

### ISSUE THREAD

**Issue by PythonEgg** [matplotlib/matplotlib#9083]
Dear Matplotlib help,

I have successfully created plots with quiver. The script is working. However, I want to create multiple plots (quiver) with different datasets. Due to the differences in datasets the length of the quiver is changing in each plot. How can I keep the quiver length same in each plots? Note, I do want variations in quiver length in the plot. I don't want the length of each quiver equal in same plot.

I am using below in my script.
Q=ax.quiver(x, y, u, v, pivot-'tip')
qk = ax.quiverkey(Q, 0.78, 0.78, 5, '5 mph', labelpos='E', coordinates=figure')
 
1. scale function will not work.
2. Normalizing the data will also not work

Please suggest/help.
RA

**Matplotlib version**

  * Operating System: Ubuntu 14.10 LTS
  * Matplotlib Version: 1.1.0
  * Python Version: 2.7.3
  * Jupyter Version (if applicable): None
  * Other Libraries: Numpy

**Comment by tacaswell** [comment]
That is a _very_ old version of Matplotlib!

This question is probably better handled on the mailing list ( https://mail.python.org/mailman/listinfo/matplotlib-users to subscribe so you can post un-moderated), we try to keep the issues on github for bugs and do support on the mailing list.

Also see http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.quiver.html?highlight=quiver#matplotlib.axes.Axes.quiver but I am not sure which of those args go back to 1.1.
