### ISSUE TITLE
libpng-1.6.30 Matplotlib 2.0.2 problems (Travis-CI)

### ISSUE THREAD

**Issue by mscuthbert** [matplotlib/matplotlib#9091]
### Bug report

**Bug summary**

With an upgrade to libpng-1.6.30 (installed by Conda pyqt), matplotlib is now failing on Travis-CI for failure of "libz.so.1: version `ZLIB_1.2.9' not found (required by /home/travis/miniconda2/lib/python3.4/site-packages/matplotlib/../../../libpng16.so.16)"

The upgrade to libpng-1.6.30 was pushed to pyqt within the last day (24 August 2017).  The code works fine with libpng-1.6.27.

This line is triggered by `import matplotlib._png as _png` performed from the import of pyplot.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Matplotlib version**

  * Operating System: Linux (Travis-CI Trusty)
  * Matplotlib Version: 2.0.2.
  * Other Libraries: PyQt 5.6.0, libpng-1.6.30

Default `conda install pyqt`, `conda install matplotlib`

**Comment by mscuthbert** [comment]
Nearly identical code (with no matplotlib changes) that failed today:
https://travis-ci.org/cuthbertLab/music21/jobs/268153245#L543
and that succeeded yesterday:
https://travis-ci.org/cuthbertLab/music21/jobs/267820084

THANKS!

**Comment by mscuthbert** [comment]
Pinning libpng to version 1.6.27 has fixed the problem temporarily:

`conda install --yes python=$TRAVIS_PYTHON_VERSION libpng=1.6.27`
`conda install --yes python=$TRAVIS_PYTHON_VERSION pyqt`
`conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib`

**Comment by tacaswell** [comment]
Thanks for reporting this but this is an issues with contimuum's packaging and should be reported to https://groups.google.com/a/continuum.io/forum/#!forum/conda .  Closing as there is nothing we can do on the Matplotlib side of things.

attn @msarahan .

**Comment by msarahan** [comment]
Thanks @tacaswell. I'll see to it that this gets fixed.

**Comment by mscuthbert** [comment]
Thanks all!

**Comment by tacaswell** [comment]
Thank you @msarahan !
