### ISSUE TITLE
Make LogFormatter limit (<10 decades) overrulable for always displaying minor ticks

### ISSUE THREAD

**Issue by Quas7** [matplotlib/matplotlib#9107]
This behavior looks more like a feature than a bug as it is limiting the minor tick density in graphs. But, manually reducing minor tick density should always be possible by users (IMHO).

Note, that matplotlib >2.0.0 might have made the former work around impossible. 
See comments in my [stackoverflow question](https://stackoverflow.com/questions/45905135/matplotlib-missing-minor-ticks-on-y-axis-because-of-log-range-10-decades).

Jupyter Code showing missing minor ticks behavior:
```
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np

#Used this to reset any changes to the rc params
#plt.rcParams.update(plt.rcParamsDefault)

x = np.arange(10) # np.arange(9) is working as expected - well documented issue with >10 dec-range
y = 10.0**x

fig, ax=plt.subplots()
ax.plot(y,x)
ax.set_xscale("log")

locmaj = matplotlib.ticker.LogLocator(base=10.0, subs=(0.1,1.0, ))
ax.xaxis.set_major_locator(locmaj)

locmin = matplotlib.ticker.LogLocator(base=10.0, subs=(0.1,0.2,0.4,0.6,0.8,1,2,4,6,8,10 )) 
ax.xaxis.set_minor_locator(locmin)
ax.xaxis.set_minor_formatter(matplotlib.ticker.NullFormatter())

plt.show()
```

**Matplotlib version**
  * Operating System: Windows 10
  * Matplotlib Version:  2.0.2
  * Python Version: 3.6.2
  * Jupyter Version (if applicable): 4.3.0
  * Other Libraries: numpy 1.13.1

installed by conda default.

**Comment by tacaswell** [comment]
The log-ticking has been  surprisingly subtle to get right.

I think this is primarily a documentation bug:

```python
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np

#Used this to reset any changes to the rc params
#plt.rcParams.update(plt.rcParamsDefault)

x = np.arange(10) # np.arange(9) is working as expected - well documented issue with >10 dec-range
y = 10.0**x

fig, ax=plt.subplots()
ax.plot(y,x)
ax.set_xscale("log")

locmaj = matplotlib.ticker.LogLocator(base=10.0, subs=(1.0, ), numticks=100)
ax.xaxis.set_major_locator(locmaj)

locmin = matplotlib.ticker.LogLocator(base=10.0, subs=np.arange(2, 10) * .1,
                                      numticks=100)
ax.xaxis.set_minor_locator(locmin)
ax.xaxis.set_minor_formatter(matplotlib.ticker.NullFormatter())

plt.show()
```

![so](https://user-images.githubusercontent.com/199813/29752073-21545884-8b25-11e7-9834-c4e5fbc8d50a.png)

@Quas7  where is the issue with >10 decades well documented?

The reason this stopped working is that for large number of decades, the `numticks` (which is the maximum number of ticks) starts to drop the major ticks, combined with automatically dropping some minor ticks leads to completely un-interpretable ticks, hence why once we decide decide to start skipping decades, if `subs` is anything but `1`, we do not emit any ticks.  

The default number of ticks is estimated from how big the axes is but clipped to [2, 9].

The way that `subs` works `(.1, 1)` will mark the same place 2x.

attn @efiring

**Comment by Quas7** [comment]
@tacaswell very nice solution. 
My comment "well documented" was only meant for the stackoverflow people because I referenced to an almost identical issue in my [question] (https://stackoverflow.com/questions/45905135/matplotlib-missing-minor-ticks-on-y-axis-because-of-log-range-10-decades). 
BTW, Your solution is quite close to the initial [solution on stackoverflow](https://stackoverflow.com/questions/44078409/matplotlib-semi-log-plot-minor-tick-marks-are-gone-when-range-is-large) that stopped working for matplotlib 2.0.2.

Skipping ticks because of hitting the numticks limit should maybe throw a little warning for debugging, in my opinion.

**Comment by tacaswell** [comment]
I am also one of 'the stackoverflow' people ;)  One of my long-term goals is to make sure all of the useful answers on SO get translated into examples or clarifications to the upstream docs.

Putting a warning here is dicey because you only want it for debugging if it is not doing what you want. In the default case, dropping the minor ticks intentional and there is no easy way for the users to avoid the warning.   Over-warning, particularly during 'normal' usage, is bad because it trains users to not read the warnings.

**Comment by Quas7** [comment]
That is a really big long-term goal. Keep it up!

You are right, this should not trigger a warning on a normal log level.
Normally, I would like to see a notice in info/debug log level but I must admit, I am a newby to jupyter and did not even check for any jupyter related log level settings yet.
