### ISSUE TITLE
Feature Request: extended manual positioning of contour labels

### ISSUE THREAD

**Issue by lzkelley** [matplotlib/matplotlib#9109]
Issue https://github.com/matplotlib/matplotlib/issues/613 suggested allowing contour labels to be positions manually and the [resulting feature](https://github.com/matplotlib/matplotlib/pull/642) works great, you specify a set of `(x,y)` pairs for each label as [demo'd here](https://matplotlib.org/examples/pylab_examples/contour_demo.html).  I'd like to suggest two extensions to this behavior,

1) Allowing an additional `transform` argument so that positions can be specified in arbitrary coordinates (e.g. data, figure, etc).

2) Allow **either** `x` **or** `y` positions to be given and have the method choose the coordinate *not* given.  For example, if a particular plot has (nearly) horizontal contour lines, it would be awesome to specify only the x-coordinate and let the method find a nice y-position (i.e. along the line).  If the contours are curved such that there isn't a unique x-crossing, then the method could choose the first (or the lowest, etc).

**Comment by tacaswell** [comment]
1 seems much easier than 2, but we do have some generic path intersection code in `Path` that might make it tractable.

**Comment by bklebel** [comment]
Here is a code snippet to get the paths of one contour line: 
```
   xs =  ax.contour(X, Y, Z, levels=[ level, ], **kwargs)
    p = xs.collections[0].get_paths()[0]
    v = p.vertices
    x_cont = v[:,0]
    y_cont = v[:,1]
```

From my side, it would be really nice to give as argument a number between 0 and 1 which scales along the shown contour - with code like in the example above the mentioned 2. option should be fairly simple, a scaling between 0 and 1 would require determining the length of the shown contour given the limits of the axes (this being potentially screwed up if their are changed later on). 

for number 2. we could possibly add something like the following in [lib/matplotlib/contour.py](https://github.com/matplotlib/matplotlib/pull/642/files#diff-b3f136a845ae5b7383fbc2be280c64af12352a6583ace9658cc4f6e2479df4a3) 
```         
           for x,y in self.labelManual:
                if None in (x, y):
                    # find corresponding value for x or y, depending on which is None
                self.add_label_near(x, y, inline,
                                    inline_spacing)

 ```

I don't have an idea how to implement a scaling between 0 and 1 without introducing breaking changes, as the whole signature would slightly change to allow for the two different options.

**Comment by tacaswell** [comment]
I think a bigger conceptual problem with the [0, 1] approach is that specifying where the "start point" is could be tricky and given that they are (now) closed polygons not something I think we should promise to be stable over time.

I the suggestion of letting values be `None` is a nice way to get at option (2) and I still think that adding option (1) will be much simpler.
