### ISSUE TITLE
Speed of refresh big data as image

### ISSUE THREAD

**Issue by Goczilla** [matplotlib/matplotlib#9113]
Hello,

I am working with matplotlib since two weeks and I am wondering if matplolib is possible to refresh a figure in which I draw an image with 82000 pixels, and this at a frequency of 60 Hz (60 refreshes per second).

I saw this [article ](http://bastibe.de/2013-05-30-speeding-up-matplotlib.html) which deals with a curve and not an image so maybe I can try to reproduce what he did but I have not a lot a time to experiment lot of solution.

Thank you in advance for your comments and your help.

**Comment by WeatherGod** [comment]
It should be possible to get that high of a refresh rate on a figure of
roughly 90-by-90 pixels. First, I would turn off any interpolations (this
is the default behavior in v2.0). Second, make sure you are using
matplotlib v2 or greater. There was a major overhaul of the image-handling
code between v1.5 and v2.0 that fixed many bugs, and also improved
performance overall.

Another factor that often gets overlooked is the choice in backends.
Certain backends are better at handling high frequency repaint events than
others. I haven't personally looked into any performance metrics as a
function of backend, so I can't tell you which ones would be better than
others. Along that vein, there is an experimental backend (packaged
separately) called mpl_cairo that you might want to look into because it is
a more modern rasterizer than AGG. We are keeping it separate from mpl for
the moment in order for it to easily be tested and vetted by others, but it
may one day replace AGG in matplotlib.

**Comment by anntzer** [comment]
(While I appreciate the advertisement :-), I don't think the backend really matters here (unless it is truly horrendous): when the data hits the backend it has already been resampled to its display size, so regardless of your input data size the backend always sees an array of size (npixels x npixels).  Thus, in general and for large enough data, you should mostly affected by the speed of the resampling code.)

**Comment by WeatherGod** [comment]
I was more thinking along the lines of how well a backend handles barrage
of repaint events. I recall that wxagg used to have problems (or was it
tkagg?).

As for mpl_cairo, I take it that AGG's resampler is still used for
imshow()? Might be nice to make that configurable at some point, too.

**Comment by anntzer** [comment]
Good point for the interactive backend.  In fact mpl_cairo is likely slightly better here (even though I doubt it's actually the rate limiting step) because it natively uses a ARGB32 buffer whereas Agg uses a RGBA8888 buffer than needs to be converted every time.

I don't think (but may be mistaken) than cairo exposes its resamplers for external use, in which case we're stuck with Agg's.

**Comment by Goczilla** [comment]
Thanks for your comments. I have to confess, I am a little lost in your speeches because I am a beginner with matplotlib, For example, I did an example with PyQt5 and Python 3.6 and matplotlib 2.0.2 (i turn off interpolation of imshow) :

    import sys, random, matplotlib
    from PyQt5 import QtCore, QtGui, QtWidgets
    matplotlib.use('Qt5Agg')
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
    import matplotlib.pyplot as plt

    class SecondWindow(QtWidgets.QWidget):
        def __init__(self, parent=None):
            super(SecondWindow, self).__init__(parent)
            self.setupUi(self)

        def setupUi(self, Form):
            Form.resize(800, 600)

            self.figure = plt.figure()
            self.canvas = FigureCanvas(self.figure)
            self.axes = self.figure.add_subplot(111)

            self.setLayout(QtWidgets.QVBoxLayout())
            self.layout().addWidget(self.canvas)

            self.initialisationFigure()

            self.timer = QtCore.QTimer(self)
            self.timer.timeout.connect(self.majFigure)
            self.timer.start(1/10)

            self.timer2 = QtCore.QTimer(self)
            self.timer2.timeout.connect(self.NumberRefreshPerSecond)
            self.timer2.start(1000)

        def NumberRefreshPerSecond(self):
            print(self.count)
            self.count = 0

        def majFigure(self):
            self.count = self.count +1
            self.img = [[random.random() for x in range(1, 320)] for y in range(1, 250)]
            self.plot.set_data(self.img)
        self.canvas.draw()

        def initialisationFigure(self):
            self.img = [[random.random() for x in range(1,320)] for y in range(1,250)]
            self.plot = plt.imshow(self.img, interpolation='none')
            self.count = 0

        def closeEvent(self, event):
            self.timer.stop()

    if __name__ == '__main__':
        app = QtWidgets.QApplication(sys.argv)
        form = SecondWindow()
        form.show()
        sys.exit(app.exec_())`

I actually have a frequency of 20 Hz. So what do you suggest to do? To change the backend? If I can permit myself, what do you call a backend, a cairo? I am not sure to well understand (I am french and french traduction is complicated in such subjects).

**Comment by tacaswell** [comment]
See http://matplotlib.org/devdocs/api/animation_api.html#funcanimation

I suspect (but may be wrong) that using `blitting` will give you better frame rates (as you may be drawing the full figure now).

Your method of generating random data is also very slow, 

```python
In [133]: %timeit [[random.random() for x in range(1,320)] for y in range(1,250)]
8.53 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [136]: %timeit np.random.rand(320, 250)
743 µs ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```

Which is using half of proposed time budget.

I also suggest not importing pyplot at all, see the first class in https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html and use the OO interface for plotting (`self.im = self.ax.imshow(...)`)

**Comment by WeatherGod** [comment]
For a newcomer to matplotlib, you did quite well in your snippet. The
choice of backends won't be a huge factor, but may give you a slight
optimization.

Two things that might help you here:

1) The use of list comprehension to build the random numbers. First, use
numpy's random number generator. It is a little bit faster, particularly
for creating a chunk of random numbers. Second, because it would generate a
numpy array, the set_data() call can process it more efficiently.

2) Try self.canvas.draw_idle(). This lets the backend decide when to
actually paint the image. Essentially, draw() is a blocking call, while
draw_idle() is a non-blocking call. You aren't guaranteed that the image
will draw, but the backend might perform better by allowing it to drop some
frames.

**Comment by Goczilla** [comment]
1) Thank both of you for your answers for random numbers. Using numpy instead of random library give me 10 fps more, but my final program will be with data I collect in another thread with local network which get data from a labview program. Here is just an example to try to optimize the update of my image and discover functionnality I don't know about that. Something weird here, rand(320,250) give me 30 fps when rand(250,320) give me 40 fps. Quite funny no?
2) No improvement with draw_idle unfortunately.
3) I already modify plt.imshow into self.axes.imshow just after posting, because I remember the example on the link of tacaswell (which was the base of my program for information).
4) I will check the animation module, but it seems to be a little difficult to understand ^^

**Comment by tacaswell** [comment]
A better test would be move a bit closer to your actual usage and run the random generation on a thread and push it to your update method via signal/slot.

Are you relying on anything else from matplotlib than drawing an image?  If it might be worth looking at pyqtgraph.  You drop a lot of flexibility, but it renders much faster.

**Comment by Goczilla** [comment]
Thomas, I chose matplotlib because it seemed to be prettier than pyqtgraph. Indeed, I want to use matplotlib only to plot an image at 60 fps but with tools of the toolbar like zoom. I will try today to deal with animation on an embedded PyQt program and if I don't suceed, I will look at pyqtgraph.

**Comment by tacaswell** [comment]
I would not necessarily use the animation tools, but the explanation of blitting an the top is the clearest place that is documented.

and :+1: I am glad you think mpl is prettier :smile:

**Comment by Goczilla** [comment]
I succeed to use animation 
```
import sys, random, matplotlib
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from matplotlib import animation

class SecondWindow(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(SecondWindow, self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1900, 1200)

        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.axes = self.figure.add_subplot(111)

        self.setLayout(QtWidgets.QVBoxLayout())
        self.layout().addWidget(self.canvas)

        self.img = np.random.rand(320, 250)
        self.im = self.axes.imshow(self.img, interpolation = 'none')
        self.im.set_data(self.img)
        self.canvas.draw()

        self.anim = animation.FuncAnimation(self.figure, self.animate, interval=10, blit=True)

        self.count = 0

        self.timer2 = QtCore.QTimer(self)
        self.timer2.timeout.connect(self.NumberRefreshPerSecond)
        self.timer2.start(1000)

    def animate(self, i):
        a = self.im.get_array()
        a = a * np.exp(-0.001 * i)  # exponential decay of the values
        self.im.set_array(a)
        self.count = self.count + 1
        return [self.im]

    def NumberRefreshPerSecond(self):
        print(self.count)
        self.count = 0

    def closeEvent(self, event):
        self.timer.stop()

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    form = SecondWindow()
    form.show()
    sys.exit(app.exec_())
```
But I get only 25 fps so it is not better than before unfortunately.

**Comment by anntzer** [comment]
Closing as the original issue seems to be handled, but feel free to ask more questions (although the mailing list is much more suitable for that).

**Comment by Mitko88** [comment]
> I succeed to use animation and I get 60 FPS ! But with a window of size 800x600. With a bigger window (what I have to do after, for example 1900x1200), I decrease to 25 fps. But it is better. Here is my code :
> 
> ```
> import sys, random, matplotlib
> from PyQt5 import QtCore, QtGui, QtWidgets
> import numpy as np
> 
> matplotlib.use('Qt5Agg')
> from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
> import matplotlib.pyplot as plt
> from matplotlib import animation
> 
> class SecondWindow(QtWidgets.QWidget):
>     def __init__(self, parent=None):
>         super(SecondWindow, self).__init__(parent)
>         self.setupUi(self)
> 
>     def setupUi(self, Form):
>         Form.setObjectName("Form")
>         Form.resize(800, 600)
> 
>         self.figure = plt.figure()
>         self.canvas = FigureCanvas(self.figure)
>         self.axes = self.figure.add_subplot(111)
> 
>         self.setLayout(QtWidgets.QVBoxLayout())
>         self.layout().addWidget(self.canvas)
> 
>         self.img = np.random.rand(320, 250)
>         self.im = self.axes.imshow(self.img, interpolation = 'none')
>         self.im.set_data(self.img)
>         self.canvas.draw()
> 
>         self.anim = animation.FuncAnimation(self.figure, self.animate, interval=10, blit=True)
> 
>         self.count = 0
> 
>         self.timer2 = QtCore.QTimer(self)
>         self.timer2.timeout.connect(self.NumberRefreshPerSecond)
>         self.timer2.start(1000)
> 
>     def animate(self, i):
>         self.im.set_array(self.img)
>         self.count = self.count + 1
>         return [self.im]
> 
>     def NumberRefreshPerSecond(self):
>         print(self.count)
>         self.count = 0
> 
>     def closeEvent(self, event):
>         self.timer.stop()
> 
> if __name__ == '__main__':
>     app = QtWidgets.QApplication(sys.argv)
>     form = SecondWindow()
>     form.show()
>     sys.exit(app.exec_())
> ```

I could not run this code. The image does not change. I use matplotlib 3.1.3 instead. Do you think this is the issue?
