### ISSUE TITLE
mpl or plt in code example

### ISSUE THREAD

**Issue by liuyigh** [matplotlib/matplotlib#9115]
### Bug report

**Bug summary**
https://matplotlib.org/users/dflt_style_changes.html
On this page, `mpl` was not specified. I could not find it in other document with reasonable efforts.

**Code for reproduction**

```python
import matplotlib as mpl
mpl.style.use('classic')
```

**Actual outcome**

```
Traceback (most recent call last):
  File "plotindex_2.py", line 3, in <module>
    matplotlib.style.use('classic')
AttributeError: 'module' object has no attribute 'style'
```

**Expected outcome**

It works after I changed to 

```python
import matplotlib.pyplot as plt
plt.style.use('classic')
```
`plt` is used all through the documents. Using `mpl` here while it really needs `plt` is confusing.

It would be nice to explicitly show what `mpl` is on that page 

**Matplotlib version**

  * Operating System: Ubuntu 16.04
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by tacaswell** [comment]
Thanks for the report!

Python does not recursively import modules automatically, #9116 adds the two missing imports to the example code.
