### ISSUE TITLE
make TeXManager more user-configurable

### ISSUE THREAD

**Issue by hrittich** [matplotlib/matplotlib#9118]
### Bug report

Matplotlib cannot be used with the LaTeX font NewTX. Matplotlib loads the LaTeX `texcomp` package, without any options, while the `newtxtext` package requires the `full` option.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc

rc('text', usetex=True)
rc('mathtext', fontset='custom')
rc('text.latex', preamble=r'\usepackage{newtxtext}\usepackage{newtxmath}')

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
plt.show()
```

**Actual outcome**

```
! LaTeX Error: Option clash for package textcomp.
```

**Expected outcome**

To be able to use the newtxtex package. Maybe to have the ability to override the default packages or set their options in some ways.

**Matplotlib version**

  * Operating System: Debian GNU/Linux 8
  * Matplotlib Version: 2.0
  * Python Version: 3.5

Installed matplotlib as Debian package.

**Comment by tacaswell** [comment]
I changed the issue title to something a bit clearer of the work that would be needed.

The TeXManager is a part of the code that, for the most part, 'just works', and has not received much attention in the past few years.  It could probably serve to have it's implementation simplified and functionality extended.

@hrittich could you propose what sort of hooks / configuration options you would want to see?

A super-hacky way to fix your immediate problem is to shadow `latex` with a script the first runs `sed` to replace `\textcomp` with a version with options and then run that file through actual latex

**Comment by tacaswell** [comment]
The relevant class is https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/texmanager.py but it is never instantiated in a very user-accessible way so all of the configuration probably has to be done through (new?) rcparams.

**Comment by hrittich** [comment]
My preferred way would be to have an rc parameter that allows setting the textcomp options. Maybe `text.latex.textcomp_options`.

Another possibility would be to allow overriding of the `_font_preamble` via rc parameter. This might, however, be fragile. The user have to make sure to include the right packages, which might change after an upgrade.

**Comment by anntzer** [comment]
Things also "work" if the custom preamble is included *before* any of the mpl-provided \usepackages...  Probably worth checking whether how much disruption it would be to always move it there.

**Comment by m-oliver** [comment]
I just ran into this issue, which is breaking old code that used to work.  There does not seem to be a workaround short of hand-editing the code (which is not an option in my case as I am working with several collaborators with their own matplotlib installations), so a resolution of this issue would be very welcome.  Question: does the default need to load textcomp at all?  It's easy to put into the custom preamble if required, but if pre-loaded with wrong options, there is nothing one can do.

**Comment by svaberg** [comment]
I also had this problem when using the `newtxtext` package. I added a boolean rc parameter `text.latex.textcomp_full` which toggles the `[full]` option. 

I would be happy to contribute this minimal fix, but I realise there are larger issues here about further customising the `_font_preamble` and naming rc parameters. 

To help this discussion along I could create a pull request for your review.
