### ISSUE TITLE
Slider Class: Option for discrete values

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#9129]
Hi there,

could you introduce a Option in the matplotlib.widgets.Slider Class that the slider takes/gives only discrete values.
At the moment you have to implement your own work around:

https://stackoverflow.com/questions/13656387/can-i-make-matplotlib-sliders-more-discrete
https://stackoverflow.com/questions/38150315/discrete-sliders-for-multiple-sliders-python

Regards,

Jakob

**Comment by tacaswell** [comment]
@JakobJakobson Would you be interested in open a PR to add that functionality?

**Comment by jcalbert** [comment]
I have one that might work [here](https://github.com/jcalbert/matplotlib/tree/discrete_slider).

**Comment by tacaswell** [comment]
@jcalbert Can you please open a PR so we can review it?

**Comment by jcalbert** [comment]
Done.

**Comment by dstansby** [comment]
Fixed by #9137
