### ISSUE TITLE
OSX delayed rendering issue

### ISSUE THREAD

**Issue by ckemere** [matplotlib/matplotlib#9133]
### Bug report

**Bug summary**
In OSX using a Jupyter notebook with Matplotlib 2.0.2 and inline display, subplots apparently render after all the code in a cell has executed. The result is that if an object changes between one subplot plot call and the next, only the newest object is shown in both subplots.

**This is fixed in 2.0.2, but I'm posting this issue for folks that might run into this.**

**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = A.copy()
fig, axes = plt.subplots(1,3)
ax0, ax1, ax2 = axes
ax0.matshow(A)
A[0,0] = 9
ax1.matshow(B)
ax2.matshow(A)
# Expected behavior - first and second subplots are the same.
# Observed behavior - first and third subplots are the same.

```

**Actual outcome**
![image](https://user-images.githubusercontent.com/1432092/29904415-5a4dbcb0-8dce-11e7-8668-88f73a586fe0.png)

**Expected outcome**
I would expect the first and second subplots to be the same.

**Matplotlib version**
  * Operating System: OSX 10.10.5
  * Matplotlib Version: 1.5.1
  * Python Version: 3.5.2
  * Jupyter Version (if applicable): 5.0.0
  * Other Libraries: 

Installed from Anaconda 4.3.

**Comment by tacaswell** [comment]
This is a duplicated of https://github.com/matplotlib/matplotlib/issues/6419 and fixed by https://github.com/matplotlib/matplotlib/pull/6422 which is in 1.5.2.  I suggest you update if possible or just be aware that imshow does not copy it's data so if you mutate it it will be reflected in the output.

**Comment by tacaswell** [comment]
Thank you for taking the time to report this!

**Comment by ckemere** [comment]
Thanks, and apologies for posting a duplicate.
