### ISSUE TITLE
unicode warnings in latex build

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#9144]
There are warnings about the unicode for `=<` and other math symbols.

[edited, only half of original issues is real]

**Comment by tacaswell** [comment]
Or not?  I did a `git clean`, still get warnings, but a pdf does come out.

It complain about missing uincode a few times as well.

**Comment by QuLogic** [comment]
PDF docs now build for me without major issues; is this Unicode warning still happening, or did the recent font change fix it?
