### ISSUE TITLE
Animation._end_redraw() issue with event-driven animation

### ISSUE THREAD

**Issue by wombatonfire** [matplotlib/matplotlib#9153]
### Bug report

**Bug summary**

```Animation._end_redraw()``` method, which is called after window resizing, always calls ```self._post_draw()``` with ```blit=False```:

```python
def _end_redraw(self, evt):
    # Now that the redraw has happened, do the post draw flushing and
    # blit handling. Then re-enable all of the original events.
    self._post_draw(None, False)
    self.event_source.start()
    self._fig.canvas.mpl_disconnect(self._resize_id)
    self._resize_id = self._fig.canvas.mpl_connect('resize_event',
                                                   self._handle_resize)
```
```self._fig.canvas.draw_idle()``` is used directly in this case, and ```self._drawn_artists``` is ignored. In a scenario where the plot is updated only when new data points arrive, this leads to a blank window after resize and until you get new data point and a plot update function is executed.

Of course, I can override this behaviour, but the question is why not to call self._post_draw() here as it is called from other places:

```self._post_draw(None, self._blit)```

Doing this will respect already drawn artists if you resize the window before new data points arrive.
  
**Matplotlib version**

  * Operating System: Windows 10
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.13

Matplotlib and Python are installed as part of Anaconda 4.4.0.

**Comment by dopplershift** [comment]
That was an explicit change came in #6339 to address some "glitches on resize on Mac/Qt".

So it seems like we may need to revert this. Can you cook up a simple example to replicate the incorrect behavior you're seeing?

**Comment by wombatonfire** [comment]
[Example](https://github.com/wombatonfire/post_draw_poc). Python 2.7, Qt 5, PyQt5. GUI with a plot receives data points from a different thread every 3 seconds. Try to resize the window between plot updates, or after we received all the data points (10 in total). Then have a look at the ```DataAnimation``` class and uncomment ```_end_redraw()``` method. The issue will be gone.

**Comment by wombatonfire** [comment]
@dopplershift does the example work for you? Canyou confirm the behaviour?

**Comment by dopplershift** [comment]
I can reproduce the problem, and I can reproduce it even more easily with some of our simpler animation examples if I tune down the refresh.

Unfortunately, your solution with matplotlib 2.1 triggers a lot of warnings (and non-functional behavior) because that ends up calling `draw()` from within an existing draw call. This produces warnings like

```
QWidget::repaint: Recursive repaint detected
```
and
```
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::end: Painter not active, aborted
```

What we really need is a way to force a new draw after the other one completes...

**Comment by anntzer** [comment]
#9505 should handle (or at least document...) most of the recursive repaint issues.

**Comment by dopplershift** [comment]
I'm also wondering if we're going about this all wrong. I wonder if there's a way to just turn off blitting entirely when a resize happens, since with blitting off everything works fine. Then let blitting return to on after the resize is taken care of.

**Comment by dopplershift** [comment]
@anntzer While I can confirm it works better on 2.1.x branch, I still definitely get messages. But I think the animation module is wrong in literally invoking recursive draws.

**Comment by dopplershift** [comment]
I have a branch where I've changed how blit + resize is changed that seems like a much better approach. I think this is going to grow into a bit of a refactor to separate out how blitting is handled (too many `if blit`s distributed through the code).

**Comment by tacaswell** [comment]
marked as 2.2 as @dopplershift says a big refactor is coming :smiling_imp:

**Comment by wombatonfire** [comment]
Hi,

I finally had to update Matplotlib and my workaround started to produce `QWidget::repaint: Recursive repaint detected` as it was expected.

Is there any other way of solving the original issue with a blank window after resize? Big refactoring didn't seem to help. 😆

**Comment by dopplershift** [comment]
Sadly, big refactor is still half-baked on my hard disk. 😱

**Comment by wombatonfire** [comment]
Do you think I can help somehow with this specific problem? Or is it too big and complex for someone not familiar with the codebase?

**Comment by dopplershift** [comment]
You're welcome to take a look at my branch here: https://github.com/dopplershift/matplotlib/tree/anim-blit2

I know I found the blitting stuff to be a little tricky, mostly because we don't control when the GUI frameworks actually complete a draw.

**Comment by tacaswell** [comment]
@wombatonfire What version are you using?  I thought we had squashed all of the recursive re-paint issues....

**Comment by wombatonfire** [comment]
@tacaswell The recursive re-paint issue appears if I override `self._post_draw()` in `_end_redraw()` and, as I understood, it is expected, it's not a matplotlib problem, but a problem of my workaround, which worked previously on v2.0.2.

The real problem for me is that I loose existing data on a real-time plot after resize, until new data points arrive. That's the core issue.

**Comment by tacaswell** [comment]
That sounds like we are missing a "and re-draw the animated artsts" call _just_ after we regenerate and capture the background.
