### ISSUE TITLE
Angled text not placed correctly with usetex in EPS

### ISSUE THREAD

**Issue by DTHaydon** [matplotlib/matplotlib#9158]
### Bug report

**Bug summary**
The text alignment of `.text(..., ha="center", va="center", ...)` whilst using `matplotlib.rc("text", usetex=True)` and saving as `.eps`  is not centred.
However the output is centred for `.pdf` and `.png`

**Code for reproduction**
```python
import numpy

from matplotlib import pyplot
from matplotlib import gridspec

import matplotlib
matplotlib.rc("text", usetex=True)

def plot(file_path):
    gs = gridspec.GridSpec(
            3, 1,
            wspace=0.0, hspace=0.0
            )
    fig = pyplot.figure()

    # Add plots
    for sub_plot in gs:
        ax = fig.add_subplot(sub_plot)

    # position text based on location of subplots
    fig.tight_layout()
    row_bottom, row_top, col_left, col_right = gs.get_grid_positions(fig)

    # Finding the vertical centre like this because the axis label for
    # the plots I create  should be shared with only some of the subplots
    vertical_centre = numpy.mean([row_bottom[-1], row_top[0]])
    fig.text(
            0.01, vertical_centre,
            r"$\mathrm{Response \, \left(Normalised\right)}$",
            ha="center", va="center",
            rotation="vertical",
            transform=fig.transFigure,
            fontsize=35.  # lage size to emphasize error
            )

    fig.savefig(file_path, bbox_inches="tight")
    pyplot.close(fig)

plot("./test_eps.eps")
plot("./test_pdf.pdf")
plot("./test_png.png")
```

**Actual outcome**
`./test_eps.eps`
![test_eps](https://user-images.githubusercontent.com/15086793/30071452-09e19966-9267-11e7-9ddb-af2e432ee810.png)

`./test_pdf.pdf`
![test_pdf](https://user-images.githubusercontent.com/15086793/30071455-0cd3e3f4-9267-11e7-8606-1b231e7fb123.png)

`./test_png.png`
![test_png](https://user-images.githubusercontent.com/15086793/30071833-9940cc5c-9268-11e7-91ce-845ef2efc62a.png)

**Expected outcome**
Ideally the output of `./test_eps.eps` should match the other two figures.

**System**
  * Operating System: macOS 10.12.6 
  * Matplotlib Version: 2.0.2 (Conda: build string: np112py27_0, channel: defaults)
  * Python Version: 2.7.13
  * Conda Version: 4.3.24

**Comment by JakobJakobson** [comment]
Hi DTHaydon,

I'm not a developer perhaps I had a similar problem recently:
https://github.com/matplotlib/matplotlib/issues/8067
Perhaps the answer will help you.

Regards

**Comment by QuLogic** [comment]
This is still a problem. But I think the problem has nothing to do with alignment directly, but with the angle:
```python
import matplotlib.pyplot as plt

plt.rc("text", usetex=True)

fig = plt.figure()

for i, angle in enumerate([0, 90, 180, 270]):
    fig.text(0.1 + i / 5, 0.1 + i / 5, f"$\\mathrm{{Response {angle} }}$",
             rotation=angle, fontsize=24)

for fmt in ['eps', 'pdf', 'png']:
    fig.savefig(f"test_{fmt}.{fmt}")
```
produces inconsistent results for everything but 0 angle.
<details>
<summary>Results</summary>

PDF: 
![image](https://user-images.githubusercontent.com/302469/234742843-fdcc9009-3c12-49c9-ac4c-e3572c51b324.png)

EPS:
![image](https://user-images.githubusercontent.com/302469/234742896-6bcc6e0d-ba2a-4f00-b322-986aaf60b992.png)
</details>

We currently place usetex using the bottom-left corner, but perhaps a different anchor should be used:
https://github.com/matplotlib/matplotlib/blob/2e2d2d5f574ad43ba87fc893098345db5eb1eacc/lib/matplotlib/backends/backend_ps.py#L591-L595
At least, always subtracting text depth from the y position seems wrong, if the text is vertical.
