### ISSUE TITLE
Figure sizing problems in most backends

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#916]
#756 fixed a problem in the qt4agg backend, but the discussion revealed that the various backends behave erratically under various methods of setting or re-setting figure dimensions.

**Comment by soupault** [comment]
Hi! Can we discuss it here or should I open new issue?

http://stackoverflow.com/questions/32698501/fast-redrawing-with-pyqt-and-matplotlib

**Comment by jklymak** [comment]
I'm not aware of current problems withs sizing figures, though there may be some.  Lets close this in favour of more recent reports...
