### ISSUE TITLE
blank space vs. white space

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [matplotlib/matplotlib#9160]
(I know that this is incredibly picky).  The not-yet-released documentation for `subplots_adjust` uses the terms "blank space" and "white space".  Unless there is a distinction between these, I'd like to suggest that the same term be used in both places.

wspace = 0.2   # the amount of width reserved for blank space between subplots,
               # expressed as a fraction of the average axis width
hspace = 0.2   # the amount of height reserved for white space between subplots,
               # expressed as a fraction of the average axis height

**Comment by anntzer** [comment]
Feel free to open a PR.  Extra points if you grep through the codebase to see whether we tend to use the first or the second phrase :-)

**Comment by afvincent** [comment]
@anntzer FWIW, independently from the current trend,  “blank” may be more accurate than “white” as the figure background may not be white ;).

**Comment by efiring** [comment]
I suggest just plain "space".  It is typically not blank (it can contain ticks and labels), and it doesn't have to be white.

**Comment by afvincent** [comment]
@efiring Fair enough for me :).
