### ISSUE TITLE
image cropped with imsave to SVG on RGB array

### ISSUE THREAD

**Issue by nicoulaj** [matplotlib/matplotlib#9161]
### Bug report

**Bug summary**

Using `matplotlib.image.imsave()` to save a RGB array `(800,600,3)` to a SVG image, the output image has a size of 720x540 and it is cropped. Changing the DPI parameter makes the image even more truncated or the canvas too big.

**Code for reproduction**

```python
from matplotlib import image
from numpy import tile, linspace

width, height, block = 800, 600, 50

data = tile(linspace(0, 1, block * block * 3).reshape((block, block, 3)), (height / block, width / block, 1))

for fmt in ['png', 'jpg', 'svg', 'tiff']:
    image.imsave(fname='out.%s' % fmt, format=fmt, arr=data)
```

**Actual outcome**

SVG image has a size of 720x540 and it is cropped.
PNG, TIFF, JPG images are fine.

**Expected outcome**

SVG image renders the same as PNG, TIFF, JPG images.

**Matplotlib version**

  * Operating System: Fedora 26
  * Matplotlib Version: 2.0.2, 2.1.0rc1
  * Python Version: 2.7.13, 3.6.2
  * Jupyter Version (if applicable): N/A
  * Other Libraries: numpy 1.13.1, Pillow 4.2.1

**Comment by ksunden** [comment]
If you extract the embedded PNG from the SVG, it is the expected 800x600. I'm not sure where the 720x540 is coming from exactly (I actually get 768x576 if I view it in an image viewer and 576pt x 432pt if I inspect the SVG XML or code which scales to 72 DPI, which just makes sizing work out)

Regardless, SVG is a vector format and thus the size in pixels as reported by various programs is kind of a moot point, what matters is the embedded image as that will scale

**Comment by QuLogic** [comment]
The default DPI in `imsave` is 100, so we likely saved at 800px/100 ppi -> 8 inches. And then 768/800 is .96, so the viewer calculated pixels at 96 DPI, and indeed 8*96 -> 768. Similarly, it's 72 points per inch, giving 8*72 -> 576pt.

@nicoulaj Given that your viewer gives you 720, that means it's using 90 DPI. So one could pick a different default DPI to match, but since we get completely different values, I think that means we can't just pick one that will work better for everyone.

**Comment by ksunden** [comment]
https://gitlab.gnome.org/GNOME/eog/-/issues/22

Relevant issue which explains the origins of both the 90 and 96 dpi values. These are external to matplotlib, so I stand by the assessment that there is nothing to do on our end. The 72 dpi value is only actually used for the header of the svg, which specifies the size in points, so it is the correct value.
