### ISSUE TITLE
pylab segfaults with QT5 backend and no x11

### ISSUE THREAD

**Issue by paddymul** [matplotlib/matplotlib#9179]
### Bug report

**Bug summary**

Importing pylab on a linux (centos6/7) box without x11 installed causes a non catchable segfault.
I think IPython was using the QT5 backend.

**Code for reproduction**

this must be run from IPython
```python
import pylab
```

**Actual outcome**

```

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
startup RC

In [1]: import matplotlib

In [2]: matplotlib.__version__
Out[2]: '2.0.2'

In [3]: import pylab

In [4]: QXcbConnection: Could not connect to display 
Aborted
```

**Expected outcome**

I would expect matplotlib to throw an exception when instatiated on a non properly configured machine.  I could catch an exception.  This error segfaults the ipython process

**Matplotlib version**

  * Operating System:  CentOS 6
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.13
  * Jupyter Version (if applicable): 
  * IPython : 5.3.0

I installed matplotlib from the default conda channel

**Comment by anntzer** [comment]
Is $DISPLAY set?  Can you check why the code at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5.py#L109 does not generate a RuntimeError?  (Perhaps because it's not an X11 build?)
Can you suggest a better way to check whether initializing the QApplication will work?  (Note that DISPLAY is not necessarily defined on all OSes, and I have no idea what's the behavior on OSX in particular.)

**Comment by WeatherGod** [comment]
As a bit of a side-note, I have a centos7 box that I occasionally SSH into.
The X11 stuff just doesn't seem to work on it any more, even if I specify
ssh -X or ssh -Y. This is regardless of the GUI backend. The same box works
fine if I am physically logged into it, though. Back when it was CentOS6,
X11 tunnelling through SSH worked like a charm.

**Comment by tacaswell** [comment]
Can you try just creating a qapplication (`from PyQt5 import QtWidgets; QtWidgets.QApplication([b"test"])`)?

I don't think matplotlib tries to create the qapp until the first time you create a figure, this may be being done by IPython (attn @Carreau ).

**Comment by anntzer** [comment]
Closed due to lack of confirmation.  Feel free to request a reopen with more information.
