### ISSUE TITLE
X-axis doesn't show entirely

### ISSUE THREAD

**Issue by yangwu91** [matplotlib/matplotlib#9183]
### Bug report

**Bug summary**
I generated a very large dotplot (figsize=(100,10)), but it only shows partial x-axis.

**Code for reproduction**

```python
#!/usr/bin/env python

import matplotlib
matplotlib.use('Agg') # To solve remote session issues
import matplotlib.pyplot as plt
import sys, subprocess

depth_file = sys.argv[1]

window = int(100e3)
total_job = int(subprocess.check_output(['wc', '-l', depth_file]).split(' ')[0])

plt.figure(figsize=(100,10), dpi=600)
tick = int(10e6) # ticks interval: 10 Mb
x, y = [], []
pre = -1
n = 0
depth = 0
with open(depth_file, 'r') as inf:
	for line in inf:
		n += 1
		line = line.strip().split('\t')[1:]
		line[0] = int(line[0])
		line[1] = int(line[1])
		if n % window == 0 or line[0] == total_job:
			pos   = (line[0] - 1) / window + 1
			depth = depth*1.0 / n
			if depth >= 100:
				depth = 100
				c = 'y^'
				a = 0.4
			elif depth <= 10 and depth >0:
				c = 'b.'
				a = 0.8
			elif depth == 0:
				c = 'rv'
				a = 0.8
			else:
				c = 'k.'
				a = 0.4
			plt.plot(pos, depth, c, alpha=a, clip_on=False)#, ms=2)
			n = 0
			depth = 0
		else:
			depth += line[1]
		process = round(line[0] * 100.0 / total_job, 1)
		if process > pre:
			print '\rProcessing: %s' % str(process) + "%...",
			sys.stdout.flush()
		pre = process
plt.xlim(0, 119556435/window+1)
plt.ylim(0, 100)
plt.xticks(map(lambda x: (x+1)*tick/window, range(total_job/tick)),
           map(lambda x: str((x+1)*10) + 'Mb', range(total_job/tick)),
           fontsize=28)
plt.yticks([0, 50, 100], ["0", "50", "100"], fontsize=28)
plt.xlabel('Position', fontsize=34)
plt.ylabel('Depth', fontsize=34)
#plt.gca().set_aspect('equal', adjustable='box')
plt.title(depth_file, loc='left')
plt.grid(b='on', lw=0.4, ls='--', axis='x')
plt.tight_layout()
plt.savefig('%s.w100k.png' % depth_file, dpi=600, transparent=True)
print 'Done.'
```

**Matplotlib version**

  * Operating System: Ubuntu 14.04
  * Matplotlib Version: 2.0.2
  * Python Version: 2.7.13
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by anntzer** [comment]
We don't have depth_file available.  Can you replace the data by something simulated, e.g. np.random.rand(...)?

**Comment by jklymak** [comment]
Also a screenshot or the png that shows the problem would help (maybe not the 600 dpi version!).  "only shows partial x-axis" is ambiguous - what part of x-axis is missing?  Horizontally?  Vertically?  Labelling missing?  Does it happen if you take out your funky `plt.xticks` call?  If not, then are you sure thats correct?

**Comment by yangwu91** [comment]
My apologies! I'll upload figures first.
As you ca see, x-axis only shows this part.
![image](https://user-images.githubusercontent.com/19332606/30396509-dd9cce48-9897-11e7-8702-fd252225f532.png)

If I zoom in, the partial x-axis is a dotted line.
![image](https://user-images.githubusercontent.com/19332606/30396441-a2d16a8a-9897-11e7-9093-894e905cc1f5.png)

Now I am trying to take out `plt.xticks`, it may take time.

**Comment by jklymak** [comment]
You could also take out `tight_layout` just to remove another possible tripup point, though it should work...

I just did the following and it looks fine, so maybe an issue w/ the backend or ??

```python
import matplotlib.pyplot as plt
import numpy as np
fig,ax=plt.subplots(figsize=(100,10))
ax.plot(np.arange(20))
fig.tight_layout()
fig.savefig('Boo.png', dpi=100)

```

**Comment by yangwu91** [comment]
Probably **dpi** causes these issues? When dpi=100, it is good to me too, but when I set dpi to 600, I couldn't see x-axis at all, in addition, partial of its background is white and the other part is transparent. 

# Here is my script

```python
#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np

fig,ax=plt.subplots(figsize=(100,10))
for i in xrange(11955): # my original depth_file has 11955 lines
        ax.plot(i+1, round(100*np.random.random()))
fig.tight_layout()
fig.savefig('Boo.png', dpi=600)
```
# Here are results:
## 
##dpi=100
### overview
![image](https://user-images.githubusercontent.com/19332606/30400152-f567d994-98a3-11e7-877a-c99a359f4f53.png)

## dpi=600
### overview
![image](https://user-images.githubusercontent.com/19332606/30400191-113fff7a-98a4-11e7-892a-97768854449a.png)
### zoom in
![image](https://user-images.githubusercontent.com/19332606/30400257-48e018a2-98a4-11e7-8f83-90f0766486fe.png)

**Comment by jklymak** [comment]
OK, if I do

```python
import matplotlib.pyplot as plt
import numpy as np

fig,ax=plt.subplots(figsize=(100,10))
ax.plot(np.arange(11955), np.round(100*np.random.random(11955)),'.')
fig.tight_layout()
fig.savefig('Boo.pdf')
```

Unless you have more than 60,000 x 6000 / 10 points = 36 million dots, I'd suggest that using PDF is better than png.  That pdf file is 36k, whereas a 600-dpi PDF is 3.1 Mb.  

`fig.savefig('Boo.png', dpi=300)`  Seems to work fine.  

`fig.savefig('Boo.png', dpi=600)`  I can duplicate the above.  So there is definitely a bug with the png renderer for very large files.  

But, I'm not sure this is a great use case.  That is a huge PNG, and on any reasonable screen you are trying to display at 6000 dpi.

**Comment by yangwu91** [comment]
Yes, I've tried PDF format, it looks way better than PNG when it's large. Thanks!

**Comment by tacaswell** [comment]
There is a limitation to how big the Agg backend can make images (due to the size of an internal pointer).

As @jklymak point out pdf (or eps or svg) are vector backends which do much better at extremely large sizes (and to a large degree 'dpi' is meaningless for them, they are always '72 dpi' and the display program takes care of doing the final rasterization).

What is the application of a 100in wide figure?

Bundling the data into a single set of x/y points and then calling `plot` once will likely make your code run much faster.

**Comment by anntzer** [comment]
Possibly related to #6572.

**Comment by jklymak** [comment]
I'm going to close this as "won't fix" because I don't think there is a good argument for 100in 600-dpi figures.  Feel free to re-open if you think this should be fixed!
