### ISSUE TITLE
Problem in Scatter-Piecharts example

### ISSUE THREAD

**Issue by fgotzens** [matplotlib/matplotlib#9185]
### Bug report

**Bug summary**

The example given [here](https://matplotlib.org/examples/api/scatter_piecharts.html) is not generally applicable. Try the code e.g. with:

**Code for reproduction**

```python
r1 = 0.6       # 60%
r2 = r1 + 0.05  # 5%
sizes = [600, 800, 1200] # increased by factor 10 just for visibility
```

**Actual outcome**

which will produce

![grafik](https://user-images.githubusercontent.com/24390473/30418442-400e7ec8-9933-11e7-80f4-e5c144b165b4.png)

**Expected outcome**

![grafik](https://user-images.githubusercontent.com/24390473/30418508-815da3b8-9933-11e7-977c-ab4722394cef.png)

**Solution**

The solution is to consider that in certain ratios, negative values can appear due to the trigonometric functions being applied, preventing matplotlib from drawing the correct radius. Instead use:

```
s1 = max(max(np.abs(x)), max(np.abs(y)))
s2 = max(max(np.abs(x)), max(np.abs(y)))
s3 = max(max(np.abs(x)), max(np.abs(y)))
```

**Comment by tacaswell** [comment]
@fgotzens Thanks for reporting this. 

Can you open a PR to apply that change?  We are always happy to have the examples improved!
