### ISSUE TITLE
matplotlibrc parameter for legend title font size

### ISSUE THREAD

**Issue by andrewfowlie** [matplotlib/matplotlib#9201]
As discussed here 

https://stackoverflow.com/questions/21130576/what-matplotlib-rc-parameter-controls-legend-title-size

there is no matplotlib rc parameter that controls the legend title font size, though it may be set in an ad hoc way by

> ax.legend().set_title(prop={"size": title_size})

can a new rc parameter be added for this element?

**Comment by tacaswell** [comment]
Exact work:

 - [ ] add the rcparam to `rcsetup.py`
 - [ ] add lookup in the legend code
 - [ ] add a test (set the rcparam, create a legend title, assert the font size is correct)
 - [ ] document new rcparam

@andrewfowlie Are you interested in implementing it?

**Comment by andrewfowlie** [comment]
Sure, I'll give it a go, *sounds* straight-forward.

**Comment by andrewfowlie** [comment]
All right, I'll begin new branches in future.  Re default, what is the current behaviour? I guess it uses `font.size` but not sure.
https://github.com/andrewfowlie/matplotlib/blob/a62f94ee57370643d592391041b7b4c07b7b8ece/lib/matplotlib/rcsetup.py#L1045

**Comment by magedhennawy** [comment]
@raab70 ill help finish

**Comment by hershen** [comment]
Seems this was fixed by #11172. Should this be closed?

**Comment by andrewfowlie** [comment]
yes, it has been fixed :)
