### ISSUE TITLE
install new matplotlib using .travis

### ISSUE THREAD

**Issue by huckl3b3rry87** [matplotlib/matplotlib#9218]
I am trying to install the latest stable version  of ``matlibplot`` using ``.travis``. I can get it working using
```
install:
  - sudo apt-get install python-matplotlib
```
But that gets me an old version. 

I have tried many different ways and feel like this should be pretty easy to do, but am having trouble. Here is my recent [build](https://travis-ci.org/JuliaMPC/MPCDocs.jl) where the ``.travis`` file that I used is [here](https://github.com/JuliaMPC/MPCDocs.jl/blob/b66c4ca8597d5f6f12c10cb405dfa7deb5eea6d6/.travis.yml)  and I was following this [link](https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html)

Any help would be greatly appreciated. Thanks!

**Comment by huckl3b3rry87** [comment]
I did notice the lengthy form that I am supposed to fill out, but since the .travis file specifies all of that an the only thing that I am trying to do is get the latest version of ``matlibplot`` installed using that file, I am not sure what else you need

**Comment by jklymak** [comment]
Hi, What do you mean by "old version"?  I'm not an expert on travis, by any means, but the command above will get you the debian package, won't it?  Were you after master?  To get master you need to clone from git, and then run `pip install .` from the directory.

**Comment by huckl3b3rry87** [comment]
@jklymak thank you for the response, I have been messing with this for too long and am having trouble getting this done. By old version I mean:
```
Setting up python-matplotlib (1.3.1-1ubuntu5) ...
```
which is [here](https://launchpad.net/ubuntu/+source/matplotlib/1.3.1-1ubuntu5). I was trying to specify ``zesty``, which gives me [2.0](https://launchpad.net/ubuntu/+source/matplotlib/2.0.0+dfsg1-2ubuntu1), but it seems to mess up other parts of my build. 

I will give ``pip install .`` a shot. 

Thanks!

**Comment by jklymak** [comment]
Well, if you are willing to go back to 1.3.1 (2014!) then you should at least be OK w. 2.0.2.  I wouldn't use master in that case.  

By far the easiest thing to do is install using [conda](https://www.anaconda.com/distribution/).  Or `pip install matplotlib`

**Comment by anntzer** [comment]
https://travis-ci.org/JuliaMPC/MPCDocs.jl#L506 says you got 2.0.2?

**Comment by huckl3b3rry87** [comment]
@jklymak  and @anntzer  yes! Thank you!

I am not sure why I had so much trouble trying to use conda to do this, but ``pip install matplotlib`` worked great!~!
