### ISSUE TITLE
Anaconda python spyder systematically crash when multiple plot savefig

### ISSUE THREAD

**Issue by qcha41** [matplotlib/matplotlib#9222]
I am encountering a problem in python about saving figures produced with Matplotlib in Spyder running in an Anaconda environment.

In my code, I have a lot of data to process, and several plots to produce and save in a file. I am using the function savefig from matplotlib to do that.

My problem is that Spyder is completely crashing when I try to save more than one figure in a script. The number of iteration necessary to get the crash is random : it seems to be a memory problem... More precisely, with the python terminal, I get "Kernel died restaring". With a IPython console, spyder is crashing completely and closing.

For example, this is a reduced code that produces systematically the crash :

    import matplotlib.pyplot as plt

    for i in range(100):
        x=i
        y=i
        plt.ioff()
        plt.clf()
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.plot(x,y)
        fig.savefig('./plot_%i.png'%i)
        plt.close()      

Even in a "try except" loop, spyder is crashing. I don't get any error message.

More than that, this crash seems to corrupt the whole Anaconda software. Indeed, after a crash, I often need to reinstall the whole Anaconda software since Spyder is not anymore starting in the Ananonda navigator. Sometimes, Anaconda navigator doesn't start itself. In the terminal, when trying to run the command "conda", I get : "conda' is not recognized as an internal or external command operable program or batch file".

I tried with different computers, different versions of Windows, different versions of Anaconda, different versions of Spyder. The problem is reproducible.

For information, I am now using : Python 3.6.1 Anaconda 4.4.0 (64-bit) IPython 5.3.0 Spyder 3.1.4

Thank you in advance for your help

EDIT

Thanks to [Paulo Xavier Candeias](https://groups.google.com/a/continuum.io/d/msg/anaconda/OxeDaw3B9s8/z8nr4S4KAgAJ), this is an alternative way to make it working :

    plt.ioff()
    fig = plt.figure()
    for i in range(100):
        x=i
        y=i
        ax = fig.add_subplot(111)
        ax.plot(x,y)
        fig.savefig('./plot_%i.png'%i)
        plt.clf()
    plt.close()  

But this doesn't explains why the first form is causing crash.. and for me, I need to work with different figure objects in the same time.

**Comment by tacaswell** [comment]
attn @ccordoba12 

I can not reproduce this crash outside of spyder on linux.  @qcha41 can you reproduce this outside of spyder?

Can you watch system memory and see if it really is increasing?

What is the matrix of windows, spyder, python, ipython, and matplotlib you have reproduced this on?

> In the terminal, when trying to run the command "conda", I get : "conda' is not recognized as an internal or external command operable program or batch file".

This sounds like the path is not set up correctly or you are not using the shell that has conda configured.  I can not think of any mechanism by which mpl could break an anaconda installation via saving pngs.

**Comment by QuLogic** [comment]
Been about 5 months without response.
