### ISSUE TITLE
Nonlinear colormap from a int list

### ISSUE THREAD

**Issue by Goczilla** [matplotlib/matplotlib#9224]
### Question

**Summary**

Hello, I want to create different colormaps from lists which have non linear values. I have a list with int and not RGB tripplet. Thanks in advance for your help.

**Code for reproduction**

```
import matplotlib.pyplot as plt
colormapList = [0,5,10,12,10,8,14,15]
plt.plot(colormapList)
plt.show()
```
**Expected outcome**

I wish I can create different colormap like this to be able to use the imshow method for plotting image later.

**Matplotlib version**

  * Operating System: Windows 7 Pro
  * Matplotlib Version: 2.0.2 (from source)
  * Python Version: 3.6

**Comment by jklymak** [comment]
Hi, what are the integers supposed to represent in the colormap?

**Comment by Goczilla** [comment]
The x-axis is the value of the pixel between 0 and 255. The y-axis is the value in the colormap. In my example,
pixel = 0 => color = 0
pixel = 1 => color = 5
pixel = 2 => color = 10
etc

**Comment by jklymak** [comment]
https://stackoverflow.com/questions/25408393/getting-individual-colors-from-a-color-map-in-matplotlib

```python 
import matplotlib
import matplotlib.plt
import numpy as np

cmap = plt.get_cmap('Spectral')

colormaplist = np.array([0,5,10,12,10,8,14,15])/16.  # normalize to between 0 and 1.
rgba = cmap(colormaplist)
print(rgba)
```

Gets you the values you want.  `plot` won't plot these though.  I'm still not clear what visual representation you are expecting.  Are you after a colored line on a plot?  

Maybe see:

https://matplotlib.org/examples/pylab_examples/multicolored_line.html

**Comment by Goczilla** [comment]
I work in the infrared field so I have different palettes with 256 values. for example I can have palette like this:

![image](https://user-images.githubusercontent.com/30922706/30847114-98000302-a29a-11e7-9e24-c4edc40cfe5b.png)
![image](https://user-images.githubusercontent.com/30922706/30847132-aeb3cc1e-a29a-11e7-8534-d97a256387a7.png)

And I have an image 320*256 pixels which have values between 0 and 255. So I want to change the display of my image with imshow using my own palettes. With the second example, you can see some pixels will be displayed with the same color whereas they have the same values.

Sorry for asking you this, but I didn't understand yet the working of colormap. After converting my list into rgba values (normalized between 0 and 1), and normalized too my image between 0 and 1, how can I apply the rgba palette to my image with imshow? 

Thank you in advance for your answer.

**Comment by jklymak** [comment]
You probably want to get your colours and then make a custom map.   https://matplotlib.org/examples/pylab_examples/custom_cmap.html

**Comment by jklymak** [comment]
I’ll close this but feel free to ask here or on the matplotlib users mailing list if it’s still causing issues.
