### ISSUE TITLE
Basemap Not Projecting Data correctly

### ISSUE THREAD

**Issue by annieT210** [matplotlib/matplotlib#9230]
**Summary**
When I try and plot some gridded WRF data using basemap, it is not projecting correctly. The data is both shifted and not filling the map as it should. You can see it's off based on where the Great Lakes & Florida are below. 

Geographic data from the file header: 
                :CEN_LAT = 38.29999f ;
                :CEN_LON = -94.5f ;
                :TRUELAT1 = 38.3f ;
                :TRUELAT2 = 38.3f ;
                :MOAD_CEN_LAT = 38.29999f ;
                :STAND_LON = -94.5f ;
                :POLE_LAT = 90.f ;
                :POLE_LON = 0.f ;
                :MAP_PROJ = 1 ;
                :MAP_PROJ_CHAR = "Lambert Conformal" ;

**Code for reproduction**

```python
print('lats: ', lat)
print('lons: ', lon)
m = Basemap(llcrnrlon = lon[0], llcrnrlat = lat[0],  urcrnrlon = lon[len(lon)-1], urcrnrlat = lat[len(lat)-1], \
            projection = 'lcc', lat_0 = 38.3, lat_1 = 38.3, \
            lat_2 = 38.3,  lon_0 = -94.5, resolution = 'l')


x, y = np.meshgrid(lon, lat)
X, Y = m(x,y)


varToPlot = var[dateIndex, :,:]
# Actually plot stuf
plt.title(varIn)
cs=m.pcolormesh(X, Y, varToPlot, cmap='rainbow')
plt.colorbar(cs, orientation = "horizontal")

# The rest of mapping
m.drawcoastlines(linewidth = 0.2)
m.drawcountries(linewidth = 1)
m.drawstates(linewidth = .3, color = '.1')
m.drawparallels(np.arange(-90., 1290., 10.), labels = [1,0,0,0], linewidth = 0.3)
m.drawmeridians(np.arange(0., 360., 10.), labels = [0,0,0,1], linewidth = 0.3)

# Show the figure
plt.show()

```

**Actual outcome**
```

lats:  [ 24.00225067  24.31139374  24.62088013  24.93069458  25.24085236
  25.55131531  25.86209106  26.17316437  26.4845314   26.79617691
  27.10811234  27.42029953  27.73276901  28.04548264  28.35843277
  28.67161942  28.98503494  29.29865646  29.61249161  29.92652893
  30.2407608   30.55516052  30.86974335  31.18448639  31.4993782
  31.81442261  32.1295929   32.4448967   32.7603035   33.07582474
  33.39144516  33.70714569  34.02292633  34.33877563  34.65467453
  34.97063828  35.28662491  35.60264587  35.9186821   36.23472214
  36.55076218  36.8667984   37.18278885  37.49876785  37.81469727
  38.13057327  38.4463768   38.76210403  39.07775116  39.3932991
  39.70874786  40.02406693  40.3392601   40.65432358  40.96922302
  41.28396606  41.59854126  41.91292953  42.22713089  42.54111862
  42.85490036  43.16844559  43.4817543   43.79481888  44.1076088
  44.42015076  44.73239899  45.04435349  45.35600281  45.66733551
  45.97833633  46.28900146  46.59932327  46.90927505  47.21886063
  47.5280571   47.83685684  48.14525604  48.45323181  48.76077652
  49.06788254]
lons:  [-112.03419495 -111.69500732 -111.35536194 -111.01525879 -110.67468262
 -110.3336792  -109.99224854 -109.65036011 -109.30807495 -108.96537781
 -108.62228394 -108.27877808 -107.93490601 -107.59065247 -107.24603271
 -106.90106201 -106.55574036 -106.21008301 -105.86408997 -105.51777649
 -105.17115784 -104.82423401 -104.47702026 -104.1295166  -103.78173828
 -103.43371582 -103.0854187  -102.73687744 -102.38812256 -102.03912354
 -101.68991089 -101.34048462 -100.99087524 -100.64108276 -100.29110718
  -99.940979    -99.59066772  -99.24023438  -98.88964844  -98.53894043
  -98.18811035  -97.83718872  -97.48617554  -97.1350708   -96.78387451
  -96.43261719  -96.08129883  -95.72994995  -95.37857056  -95.02716064
  -94.67572021  -94.32427979  -93.97283936  -93.62142944  -93.27005005
  -92.91870117  -92.56738281  -92.21612549  -91.8649292   -91.51382446
  -91.16281128  -90.81188965  -90.46105957  -90.11035156  -89.75976562
  -89.40933228  -89.059021    -88.70889282  -88.35891724  -88.00912476
  -87.65951538  -87.31008911  -86.96087646  -86.61187744  -86.26312256
  -85.9145813   -85.56628418  -85.21826172  -84.8704834   -84.52297974
  -84.17578125  -83.82885742  -83.48223877  -83.13592529  -82.78991699
  -82.4442749   -82.09893799  -81.75396729  -81.40936279  -81.06509399
  -80.72122192  -80.37771606  -80.03460693  -79.69192505  -79.34963989
  -79.00775146  -78.6663208   -78.32531738  -77.98474121  -77.64465332
  -77.30499268  -76.96582031]


```
![image](https://user-images.githubusercontent.com/32282746/30836957-99a80490-a22f-11e7-9d62-1e4bb3b8cdce.png)

**Expected outcome**

The output map should look more like this: 
![image](https://user-images.githubusercontent.com/32282746/30836897-217281da-a22f-11e7-9009-db65d2d33333.png)

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 2.0.2
  * Python Version: 3.5.1 (but I had the same problems with 2.7.13)
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by tacaswell** [comment]
attn @WeatherGod

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/issues/6331 <- this looks like a relevant discussion.

**Comment by jklymak** [comment]
It may be helpful to have access to the data file.  

How did you get `lon` and `lat`?  If a file has a header like this, I might expect it to already be on the specified projection.  i.e. the grid `var` is already equally spaced in Lambert Conformal (and unequally spaced in lat and lon).  So passing it to `Basemap` like this will project the projection!  But thats just a  guess as to whats happened.

**Comment by annieT210** [comment]
I have tried to use basemap to project the data into multiple different projections, just to see if that is the issue, and that doesn't work either. When I try and project it to the mercator projection, it's becomes warped the higher north you go: 
![image](https://user-images.githubusercontent.com/32282746/30863415-feb3cf08-a29e-11e7-9315-566fd8370fcf.png)



Here is the data file: 
[Landmask1.zip](https://github.com/matplotlib/matplotlib/files/1333354/Landmask1.zip)

**Comment by jklymak** [comment]
This data is already on the Lambert  projection.  Note that your variables `XLONG` and `XLAT` are matrices (ny,  nx) and they aren't uniform in dlat or dlon.  I didn't try in basemap, but

```python

import xarray as xr
with xr.open_dataset('/Users/jklymak/downloads/Landmask1.nc') as nc:
    print(nc.XLAT)

    fig, ax = plt.subplots()
    ax.pcolormesh(nc.XLONG[0], nc.XLAT[0], nc.LANDMASK[0])

```
gives the image below.  I'm 95% sure that if you pass the matrices for `XLONG` and `XLAT` to `m` you will do fine.  There is probably also a way to just directly figure out the values for `x` and `y`, and if you want more efficient plotting you could do that, but for only a few plots I'd just be lazy about it.

<img width="623" alt="untitled" src="https://user-images.githubusercontent.com/1562854/30864542-be782954-a288-11e7-8ea0-7917ba2c27ef.png">

**Comment by annieT210** [comment]
Totally understand now!

Thanks so much for your help!!!

**Comment by annieT210** [comment]
I totally understood what you were saying. And when I replicate your code, I get the image above. 

However, If I change mine, it still isn't projecting correctly: 

```python

f1=Dataset(path+filename, 'a')
lat = f1.variables['XLAT'][0,:,0]
lon = f1.variables['XLONG'][0,0,:]
varToPlot = f1.variables[varIn][0,:,:]
fig, ax = plt.subplots()
plt.title(varIn)
ax.pcolormesh(lon, lat, varToPlot)
plt.show()
```

I get this: 
![image](https://user-images.githubusercontent.com/32282746/30874117-71d7bdfa-a2bd-11e7-9da8-68155073e0c0.png)

And it remains all warped when I add the basemap portion:
```python
f1=Dataset(path+filename, 'a')
lat = f1.variables['XLAT'][0,:,0]
lon = f1.variables['XLONG'][0,0,:]
varToPlot = f1.variables[varIn][0,:,:]
fig, ax = plt.subplots()
plt.title(varIn)
ax.pcolormesh(lon, lat, varToPlot)
m = Basemap(llcrnrlon = -110, llcrnrlat = 24,  urcrnrlon = -77, urcrnrlat = 50)
m.drawcoastlines(linewidth = 0.2)
m.drawcountries(linewidth = 1)
m.drawstates(linewidth = .3, color = '.1')
m.drawparallels(np.arange(-90., 1290., 10.), labels = [1,0,0,0], linewidth = 0.3)
m.drawmeridians(np.arange(0., 360., 10.), labels = [0,0,0,1], linewidth = 0.3)
plt.show()
```
Output:
![image](https://user-images.githubusercontent.com/32282746/30875470-a2c4f4f6-a2c1-11e7-88c4-54d17d2a8960.png)

Is it because I'm using netcdf's Dataset to import the file and not xarray? I've never struggled with this before.
When I use basemap in conjunction with xarray, it works perfectly: 

```python
lon = nc.XLONG[0]
lat = nc.XLAT[0]
land = nc.LANDMASK[0]

lonMap = lon[0,:]
latMap = lat[:,0]

fig, ax = plt.subplots()
m = Basemap(llcrnrlon = lonMap[0], llcrnrlat = latMap[0],  urcrnrlon = lonMap[len(lonMap)-1], urcrnrlat = latMap[len(latMap)-1])
x, y = m(lon, lat)

cs = m.pcolormesh(lon, lat, land)

m.drawcountries(linewidth = 1)
m.drawstates(linewidth = .3, color = '.1')
m.drawparallels(np.arange(-90., 1290., 10.), labels = [1,0,0,0], linewidth = 0.3)
m.drawmeridians(np.arange(0., 360., 10.), labels = [0,0,0,1], linewidth = 0.3)
m.drawcoastlines(linewidth = .2)
plt.show()
```
![image](https://user-images.githubusercontent.com/32282746/30875256-e6bb6eca-a2c0-11e7-94bd-e3777c05f753.png)

And this should probably be enough of a resolution, but I just remain so confused as to why it's not working when I import the data using Dataset/netcdf. I just cannot figure out what I'm doing wrong.

**Comment by jklymak** [comment]
Its because you are slicing `lat` and `lon` in your first example, and not slicing it in your second (aside from the redundant time dimension)

Try:

```python

lat = f1.variables['XLAT'][0, :, :]
lon = f1.variables['XLONG'][0, :, :]
```

**Comment by annieT210** [comment]
Yup. That's totally it. 
THANK YOU!

**Comment by jklymak** [comment]
`xarray` is a red-herring in this.  Its just how I happen to read netcdf files.  OTOH, `xarray` is great, and everyone should read netcdf files w/ xarray!

**Comment by annieT210** [comment]
Yup, it's way easier. I've officially been converted.
