### ISSUE TITLE
run animation from animation.FuncAnimation fails

### ISSUE THREAD

**Issue by gopinath-balu** [matplotlib/matplotlib#9233]
### Bug report

**Bug summary**

I was trying to plot an animation using animation.FuncAnimation but it failed returning error: ValueError: I/O operation on closed file

**Code for reproduction**

```python
# Paste your code here
#
#
%matplotlib inline
import math,os,sys,numpy as np
from numpy.random import random
from matplotlib import pyplot as plt, rcParams, animation, rc
from __future__ import print_function, division
from ipywidgets import interact, interactive, fixed 
from ipywidgets.widgets import *
rc('animation', html='html5')
rcParams['figure.figsize'] = 3,3
%precision 4
np.set_printoptions(precision=4, linewidth=100)

def lin(a,x,b): return a * x + b

a = 3.
b = 8.
n = 30

x = random(n)
y = lin(a,x,b)

plt.scatter(x,y)

def sse(y, y_pred): return ((y-y_pred)**2).sum()
def loss(y, a, x, b): return sse(y, lin(a, x, b))
def avg_loss(y, a, x, b): return np.sqrt(loss(y, a, x, b)/n)

a_guess = -1
b_guess = 1
avg_loss(y, a_guess, x, b_guess)

lr = 0.01
#d[(y-(a*x+b))**2, b] = 2 (y_pred - y)
#d[(y -(a*x+b)) **2, a] = x * dy/db

def upd():
    global a_guess, b_guess
    y_pred = lin(a_guess, x, b_guess)
    dydb = 2 * (y_pred - y)
    dyda = x * dydb
    a_guess -= lr*dyda.mean()
    b_guess -= lr*dydb.mean()


fig = plt.figure(dpi=100, figsize=(5,5))
plt.scatter(x,y)
line, = plt.plot(x, lin(a_guess, x, b_guess))
plt.close()

def animate(i):
    line.set_ydata(lin(a_guess, x, b_guess))
    for i in range(10): upd()
    return line,


ani = animation.FuncAnimation(fig, animate, np.arange(0, 40), interval=100)
ani
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
 ValueError Traceback (most recent call last)
/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    309             method = get_real_method(obj, self.print_method)
    310             if method is not None:
--> 311                 return method()
    312             return None
    313         else:

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in _repr_html_(self)
   1233         fmt = rcParams['animation.html']
   1234         if fmt == 'html5':
-> 1235             return self.to_html5_video()
   1236 
   1237 

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in to_html5_video(self)
   1207                                 bitrate=rcParams['animation.bitrate'],
   1208                                 fps=1000. / self._interval)
-> 1209                 self.save(f.name, writer=writer)
   1210 
   1211             # Now open and base64 encode

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1061                         # TODO: See if turning off blit is really necessary
   1062                         anim._draw_next_frame(d, blit=False)
-> 1063                     writer.grab_frame(**savefig_kwargs)
   1064 
   1065         # Reconnect signal for first draw if necessary

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     33                 value = type()
     34             try:
---> 35                 self.gen.throw(type, value, traceback)
     36                 raise RuntimeError("generator didn't stop after throw()")
     37             except StopIteration, exc:

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in saving(self, *args, **kw)
    287             yield self
    288         finally:
--> 289             self.finish()
    290 
    291     def _run(self):

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in finish(self)
    307     def finish(self):
    308         'Finish any processing for writing the movie.'
--> 309         self.cleanup()
    310 
    311     def grab_frame(self, **savefig_kwargs):

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.pyc in cleanup(self)
    346     def cleanup(self):
    347         'Clean-up and collect the process used to write the movie file.'
--> 348         out, err = self._proc.communicate()
    349         self._frame_sink().close()
    350         verbose.report('MovieWriter -- '

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/subprocess32.pyc in communicate(self, input, timeout)
    925 
    926         try:
--> 927             stdout, stderr = self._communicate(input, endtime, timeout)
    928         finally:
    929             self._communication_started = True

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/subprocess32.pyc in _communicate(self, input, endtime, orig_timeout)
   1711             if _has_poll:
   1712                 stdout, stderr = self._communicate_with_poll(input, endtime,
-> 1713                                                              orig_timeout)
   1714             else:
   1715                 stdout, stderr = self._communicate_with_select(input, endtime,

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/subprocess32.pyc in _communicate_with_poll(self, input, endtime, orig_timeout)
   1767             select_POLLIN_POLLPRI = select.POLLIN | select.POLLPRI
   1768             if self.stdout:
-> 1769                 register_and_append(self.stdout, select_POLLIN_POLLPRI)
   1770                 stdout = self._fd2output[self.stdout.fileno()]
   1771             if self.stderr:

/home/gopinath/Workspace/anaconda3/envs/py27/lib/python2.7/site-packages/subprocess32.pyc in register_and_append(file_obj, eventmask)
   1746             poller = select.poll()
   1747             def register_and_append(file_obj, eventmask):
-> 1748                 poller.register(file_obj.fileno(), eventmask)
   1749                 self._fd2file[file_obj.fileno()] = file_obj
   1750 

ValueError: I/O operation on closed file
<matplotlib.animation.FuncAnimation at 0x7f085e3c0fd0>
```

**Expected outcome**
An animated line which fits to the data point in ten iterations.

**Matplotlib version**

  * Operating System:
Ubuntu 16.04
  * Matplotlib Version: 
Matplotlib version: 2.0.2
  * Python Version:
Python version: 2.7.13
  * Jupyter Version (if applicable):
  * Other Libraries: 
Anaconda version 4.4

I'm actually using python 3.5 on Ubuntu 16.04, anaconda 4.4, matplotlib 2.0.2, actually this particular course was taught using python 2.7 so I created a virenv (py27) installed 2.7 along with all related dependencies through conda. So will it be the problem?? I mean using python 2.7 via virtual environment on top of 3.5?

**Comment by stephenpardy** [comment]
I am also seeing this issue.
Code:
I have copy-and-pasted the first example from:
https://matplotlib.org/examples/animation/basic_example_writer.html 

Output:

```
File "make_animation_cumulative.py", line 30, in <module>
    line_ani.save('lines.mp4', writer=writer)
  File "/opt/local/anaconda2/lib/python2.7/site-packages/matplotlib/animation.py", line 1200, in save
    writer.grab_frame(**savefig_kwargs)
  File "/opt/local/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/local/anaconda2/lib/python2.7/site-packages/matplotlib/animation.py", line 241, in saving
    self.finish()
  File "/opt/local/anaconda2/lib/python2.7/site-packages/matplotlib/animation.py", line 367, in finish
    self.cleanup()
  File "/opt/local/anaconda2/lib/python2.7/site-packages/matplotlib/animation.py", line 405, in cleanup
    out, err = self._proc.communicate()
  File "/opt/local/anaconda2/lib/python2.7/site-packages/subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/local/anaconda2/lib/python2.7/site-packages/subprocess32.py", line 1713, in _communicate
    orig_timeout)
  File "/opt/local/anaconda2/lib/python2.7/site-packages/subprocess32.py", line 1769, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/opt/local/anaconda2/lib/python2.7/site-packages/subprocess32.py", line 1748, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
```
Operating System:
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

Python version: 2.7.13

Matplotlib version: 2.2.2

**Comment by ImportanceOfBeingErnest** [comment]
This works fine for me on windows 8.1 (64bit), python 2.7 as well as python 3.6, matplotlib 2.2.2. Could be Linux specific?

**Comment by tacaswell** [comment]
Animation does not work with inline, try with `%matplotlib notebook`

**Comment by ImportanceOfBeingErnest** [comment]
Are you sure that's the problem?   

* I copied the first code (by @thegopieffect) in a jupyter notebook and it runs completely fine as expected (due to `rc('animation', html='html5')` it shows an inline video)
@thegopieffect Can you specify which version of jupyter and IPython you are using?

* I copied the example code (reported about by @stephenpardy) in a jupyter notebook and it runs fine when removing the line that sets the backend (matplotlib.use("Agg")).
@stephenpardy Can you specify which interpreter (jupyter, Ipython console, Idle, python, Spyder, PyCarm or whatever it may be?) you are using and give a step by step manual on how you run the code. Also the version of the interpreter.

I used Windows 8.1, python 2.7, matplotlib 2.2.2, jupyter notebook server 4.4.1, IPython 5.3 here. 

Can anyone else reproduce this on Linux?

**Comment by ImportanceOfBeingErnest** [comment]
According to [this Stackoverflow question](https://stackoverflow.com/questions/46386759/animation-funcanimation-valueerror-i-o-operation-on-closed-file) this is solved by installing the newest `ffmpeg`. Can you confirm that this helps?

**Comment by stephenpardy** [comment]
I have tried the code both in a notebook and as a script running in the terminal. Both produced the same error. I have also tried removing the line that sets the backend. That change did not resolve the error.

I have just updated the ffmpeg installation, but that also didn't help things. I am including the ffmpeg version information below. 

ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg --extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --optflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --disable-htmlpages --enable-pic --disable-stripping --enable-shared --disable-static --enable-gpl --disable-openssl --enable-avresample --enable-libcdio --enable-gnutls --enable-ladspa --disable-cuda --disable-cuvid --enable-libass --enable-libbluray --enable-libcelt --enable-libcdio --enable-libdc1394 --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwebp --enable-netcdf --enable-vaapi --enable-vdpau --enable-muxers --enable-demuxers --disable-encoders --disable-decoders --disable-decoder='mpeg1video,mpeg2video,mpeg4,h263,h264,hevc,vc1' --enable-encoder='apng,ass,ayuv,bmp,ffv1,ffvhuff,flac,gif,huffyuv,jpegls,libgsm,libmp3lame,libopenjpeg,libopus,libschroedinger,libspeex,libtheora,libtwolame,libvorbis,libvpx_vp8,libvpx_vp9,libwebp,libwebp_anim,mjpeg,mp2,mp2fixed,pam,pbm,pcm_alaw,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_mulaw,pcm_s16be,pcm_s16be_planar,pcm_s16le,pcm_s16le_planar,pcm_s24be,pcm_s24le,pcm_s24le_planar,pcm_s32be,pcm_s32le,pcm_s32le_planar,pcm_s8,pcm_s8_planar,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,pcx,pgm,pgmyuv,png,ppm,sgi,srt,ssa,sunrast,targa,text,tiff,v210,v308,v408,v410,vorbis,xbm,xwd,y41p,yuv4,zlib,' --enable-decoder='ac3,ansi,apng,ass,ayuv,bmp,dirac,exr,ffv1,ffvhuff,ffwavesynth,flac,gif,gsm,huffyuv,libcelt,libgsm,libopenjpeg,libopus,libschroedinger,libspeex,libvorbis,libvpx_vp8,libvpx_vp9,mjpeg,,,,mp1,mp1float,mp2,mp2float,mp3,mp3float,opus,pam,pbm,pcm_alaw,pcm_bluray,pcm_dvd,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_mulaw,pcm_s16be,pcm_s16be_planar,pcm_s16le,pcm_s16le_planar,pcm_s24be,pcm_s24le,pcm_s24le_planar,pcm_s32be,pcm_s32le,pcm_s32le_planar,pcm_s8,pcm_s8_planar,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,pcx,pgm,pgmyuv,pgssub,png,ppm,rawvideo,sgi,srt,ssa,sunrast,targa,text,theora,tiff,v210,v210x,v308,v408,v410,vorbis,vp3,vp5,vp6,vp6a,vp6f,vp8,vp9,webp,xbm,xwd,y41p,yuv4,zlib,'
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by ImportanceOfBeingErnest** [comment]
What does `plt.rcParams["animation.ffmpeg_path"]` give? Is this the same ffmpeg that you are reporting about?

**Comment by tacaswell** [comment]
ooo, this is coming out of the hmtl repr of the animation which is trying to make the javascript player, not run a 'proper' animation inside of the Matplotlib event framework.

**Comment by stephenpardy** [comment]
That doesn't give me much. 
```
>>> plt.rcParams["animation.ffmpeg_path"]
'ffmpeg'

```

**Comment by ImportanceOfBeingErnest** [comment]
Well one answer in the linked SO post claims that they had to uninstall the conda ffmpeg to get it working. Not sure why conda is even involved in the whole process though.

**Comment by tacaswell** [comment]
Sorry, I am deeply confused and reading too fast.  I was looking at the OP code which does not explicitly save (but is being run in the notebook where the html repr would be hit) but the linked example does.

I have a memory of digging into this recently, but can find no paper trail (either of issue or a PR).  I think what is going on is that something is going wrong with the pipe to ffmpeg, but the clean up process is obliterating that stack trace with a different one.

Can you try using the avconv writer instead?  Due to split in the ffmpeg/avconv development effort there are a variety of things floating around as 'ffmpeg' that take different line arguments, I'm worried the way we are calling ffmpeg is compatible with the version you have or we are using a codec you don't have installed etc.

**Comment by QuLogic** [comment]
All posts seem to be about Python 2.7, so I think we can close this.
