### ISSUE TITLE
Make Rectangle._angle public.

### ISSUE THREAD

**Issue by moorepants** [matplotlib/matplotlib#9234]
### Bug report

**Bug summary**

`Rectangle._angle` is not a public attribute. Seems like it should be. I use it in animations, for example, and you can set the angle with a public init kwarg on the class but then it isn't obviously accessible or documented.

**Code for reproduction**

```python
r = Rectange((1, 1), 1, 1, angle=5)
r._angle = 6
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

```python
r.angle = 6
```

**Matplotlib version**

  * Operating System: ubuntu 17.04
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by jklymak** [comment]
Would `r.get_angle()` and `r.set_angle()` work?  I imagine that would be a welcome Pull Request.

**Comment by dopplershift** [comment]
I'd actually prefer we avoid adding `set_` and `get_`--that's pretty unpythonic these days. The whole point of `property` is to avoid that.

**Comment by jklymak** [comment]
Cool, learn something new every day!  So, for backwards compatibility, you could do something with `@property`

**Comment by anntzer** [comment]
I think the sad truth is that we are stuck with getters and setters in most of the library until traits come in, and I'd rather keep things internally consistent (... if unpythonic...) until we switch to traits and do the conversion all at once.

**Comment by dopplershift** [comment]
@anntzer I'm torn. I'm not sure I like the idea of making the existing problem worse in the name of consistency...

Of course you can always do:
```python
class Rectangle(object):
    def __init__(self):
        self.angle = 5

    @property
    def set_angle(self, val):
        self.angle = val

    @property
    def get_angle(self, val):
        return self.angle
```

Regardless, there's no need to worry about backwards compatibility for an attribute that starts with `_`.

**Comment by dopplershift** [comment]
This would work:
```python
class Rectangle(object):
    def __init__(self):
        self.angle = 0

    def set_angle(self, val):
        self.angle = val

    def get_angle(self):
        return self.angle

    angle = property(get_angle, set_angle)
```

**Comment by anntzer** [comment]
I think we should get mostly some consistent policy there.  I am +1 on keeping setters/getters for now because I think it's worse if we start having to remember what needs to go through properties and what needs to go through setters and getters; but I am open to be convinced otherwise.

**Comment by dopplershift** [comment]
Well that's why I like my last example--you get both.

**Comment by WeatherGod** [comment]
Really? Does that work? I would have expected `self._angle` to be used in
those setters/getters.

I think we have to provide the get_*/set_* methods because there is some
property-setting code that assumes that for setters, and there is the
ArtistInspector class that finds properties based on the existance of
getters, IIRC.

I do agree that I would want to move away from the getter/setter style, but
we need to have a plan laid out for that. My thought was that it was going
to dovetail with the traitlets work, wasn't it?

**Comment by tacaswell** [comment]
I think there is a typo as it will infinity recurse as is ;)

**Comment by dopplershift** [comment]
The point, you pedants 😁 , is that you can have access as both a property and with getter/setter.

**Comment by moorepants** [comment]
Nice conversation here :), but looks like it has already been fixed 10 months ago:

https://github.com/moorepants/matplotlib/commit/cc8c959b60de99271c12adea9d27f1b7f398f442

**Comment by moorepants** [comment]
From this PR: https://github.com/matplotlib/matplotlib/pull/7536
