### ISSUE TITLE
ENH: make default colorbar ticks adjust as nicely as axes ticks

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#9246]
### Bug report

**Bug summary**

It would be nice if the colorbars changed their number of ticks if the colorbar gets small.  

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

X = np.random.rand(32,32)*20.

fig, ax = plt.subplots()
pc = ax.pcolormesh(X)
fig.colorbar(pc)

plt.show()

fig, ax = plt.subplots(figsize=(4, 1.))
pc = ax.pcolormesh(X)
fig.colorbar(pc)

plt.show()

```

**Actual outcome**

**Expected outcome**

The full sized plot has 7 y-ticks and 7 colorbar ticks.  Whichs is fine.

<img width="548" alt="figure_1" src="https://user-images.githubusercontent.com/1562854/30940882-a3277b0e-a397-11e7-861e-f92d36f1e712.png">

If I make the plot much smaller (as can happen if I have a bunch of subplots), then the y-axis decreases its number of ticks, but the colorbar doesn't.  

<img width="366" alt="figure_1" src="https://user-images.githubusercontent.com/1562854/30940890-aecc359e-a397-11e7-82eb-5ed0b3d98ea1.png">

No idea how easy this is, and I don't think its a must-do (we can use a manual locator), but it does seem the default should be that the colorbar gets treated as well as the y-axis.

**Matplotlib version**

* Master

**Comment by efiring** [comment]
Agreed.  I have had some colorbar tick handling changes in mind for a while but haven't gotten to them.

**Comment by jklymak** [comment]
... for a less-pathalogical example:

```python
fig, ax = plt.subplots(figsize=(4, 2))
pc = ax.pcolormesh(X)
fig.colorbar(pc, shrink=0.4)
plt.show()
```
