### ISSUE TITLE
Mismatched plots in the 2.1 whatsnew

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9248]
At http://matplotlib.org/devdocs/users/whats_new.html#enhancements-to-polar-plot, the plot labeled "polar offset demo" is using a regular scatter plot whereas the plot labeled "polar sector demo" is using the offset demo (basically plots indices seem to have been shifted relative to http://matplotlib.org/devdocs/gallery/pie_and_polar_charts/polar_scatter.html).

**Comment by tacaswell** [comment]
Fixed by  #9259
