### ISSUE TITLE
Allow that MATPLOTLIBRC environment variable points to the file

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#9252]
As documented here: https://matplotlib.org/users/customizing.html

>   matplotlib looks for matplotlibrc in four locations, in the following order:
>
> 1. matplotlibrc in the current working directory, usually used for specific customizations that you do not want to apply elsewhere.
> 
> 2. $MATPLOTLIBRC/matplotlibrc.

I found that 2. is very impractical. I like to have multiple matplotlibrcs in the same directory, named with names I can understand:

e.g.
* `matpotlibrc_latex`
* `matplotlibrc_small`

My current workaround is to do

* `matpotlibrc_latex/matplotlibrc`
* `matplotlibrc_small/matplotlibrc`

So I would propose, that matplotlib checks if `$MATPLOTLIBRC` is a file, if yes, use it as rc file, if not check for `$MATPLOTLIBRC/matplotlibrc`

**Comment by MaxNoe** [comment]
mmh. Looking into c4da0f48b63599b667969383abb717d8019ba19f and the current master, this should be the case. But it doesn't work for me.

**Comment by tacaswell** [comment]
2.1 should be tagged in the next day or two.

There is an rc1 out and available via both pip and conda-forge
