### ISSUE TITLE
added axis ticks and labels don't replace default labels

### ISSUE THREAD

**Issue by gpetty** [matplotlib/matplotlib#9253]
### Bug report

**Bug summary**

Code that used to work flawlessly for replacing tick locations and labels on a log axis now seems to merely add to the default labels, so both now appear in the plot.

**Code for reproduction**

```

from matplotlib import pyplot as plt

# set the axis limits
xmin = -100   # min temperature to plot
xmax = 40    # max temperature
ymin = 100   # min pressure
ymax = 1000  # max pressure
plt.axis([xmin, xmax, ymax, ymin])

plt.semilogy()

# make lists of tick values and tick labels
plist = range(ymin,ymax,100)
plabels = []
for p in plist:
    plabels.append(str(p))

plt.yticks(plist,plabels)

x = [xmin, xmax]
y = [ymin, ymax]
plt.plot(x, y)
plt.show()

```

**Actual outcome**

<img width="401" alt="untitled 2" src="https://user-images.githubusercontent.com/2342020/31042868-4b415baa-a566-11e7-8811-72dbd12a5d37.png">

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

There should be no overwriting of custom labels with the default scientific notation labels.  It did work correctly about a year ago, but I cannot say what version of Matplotlib was being used at that time.

**Matplotlib version**

  * Operating System:  Mac osx-64
  * Matplotlib Version:  2.0.2
  * Python Version: 2.7.12
  * Jupyter Version (if applicable): 4.3.0
  * Other Libraries: 

conda install matplotlib

**Comment by tacaswell** [comment]
This is an intentional change in 2.0 (http://matplotlib.org/users/dflt_style_changes.html#logformatter-labeling-of-minor-ticks) that the default log ticking now labels minor ticks.

duplicate of #8027
duplicate of #8386
duplicate of #8517

**Comment by gpetty** [comment]
Thank you for the clarification.  It may not be a bug, but it significantly increases the complexity of doing simple things.  The students I instruct to use simple pyplot functions for their lab assignments did not previously need to know about axes and their methods. Now they apparently will, if I'm understanding the available workarounds.

**Comment by anntzer** [comment]
I think it would make sense for `plt.x/yticks` to clear the minor ticks (unless I'm mistaken, it doesn't appear like you can set the minor ticks using `plt.xticks` anyways, so they're not likely to be correct -- in other words, if you are using `plt.xticks` you are implicitly saying "I don't care about minor ticks").
Note that I'm specifically only talking about `plt.xticks`, not any of the Axes methods, which should maintain their documented behavior).

Reopening to discuss whether this would be a worthwhile approach.

**Comment by gpetty** [comment]
Someone on stackexchange just pointed out that there's a plt.minorticks_off() function that I hadn't previously found.  I'm surprised this wasn't mentioned in any of the related bug reports that I viewed.

**Comment by shamichatterjee** [comment]
This is still an issue in Python 3.6.6 / Matplotlib 2.2.3. Thank you for the pointer to plt.minorticks_off() - I ran into the same problem, and I second the sentiment that user-specified x/yticks should always take precedence over default labels.
