### ISSUE TITLE
Radar chart needs unittest

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#9261]
### Bug report

**Bug summary**

The radar chart example seems to be slightly broken on 2.1. It appears to have arisen out of 2430cc41cf4bd1c461d578a28923544b2693e173. I'm not sure why the lines are okay, since those are `Path`s also, aren't they?

**Code for reproduction**

See https://github.com/matplotlib/matplotlib/blob/master/examples/api/radar_chart.py

**Actual outcome**

![sphx_glr_radar_chart_001](https://user-images.githubusercontent.com/302469/31065034-37bde750-a710-11e7-95ba-ac647c321f13.png)

**Expected outcome**

![radar_chart](https://user-images.githubusercontent.com/302469/31065037-3cc2d292-a710-11e7-9b6f-5be89396586d.png)

**Matplotlib version**
  * Operating System: CircleCI
  * Matplotlib Version: 2.1.x
  * Python Version: 2.7/3.5

**Comment by QuLogic** [comment]
This patch seems to work, but I'm not sure about it:

```patch
diff --git a/examples/api/radar_chart.py b/examples/api/radar_chart.py
index 2f6fd8ac4..d19a911c6 100644
--- a/examples/api/radar_chart.py
+++ b/examples/api/radar_chart.py
@@ -67,7 +67,9 @@ def radar_factory(num_vars, frame='circle'):
         def fill(self, *args, **kwargs):
             """Override fill so that line is closed by default"""
             closed = kwargs.pop('closed', True)
-            return super(RadarAxes, self).fill(closed=closed, *args, **kwargs)
+            p = super(RadarAxes, self).fill(closed=closed, *args, **kwargs)
+            p[0].get_path()._interpolation_steps = self.RESOLUTION
+            return p
 
         def plot(self, *args, **kwargs):
             """Override plot so that line is closed by default"""
```

**Comment by anntzer** [comment]
Let's try to avoid regressions if we can...

**Comment by tacaswell** [comment]
Because we do not up sample lines.

**Comment by dopplershift** [comment]
Fixed by #9265. Might want to leave this open to remind us to add radar charts as a test so they don't get broken again.

**Comment by dstansby** [comment]
I think the problem here lies with using `ax.fill` on a polar axis. The question is do you expect the lines to be straight in 'polar' space (as they are with plot) or straight in 'cartesian' space (as they are with `ax.fill` without the reversion):

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, np.pi, 5)
y = np.abs(np.sin(x))

fig, ax = plt.subplots(subplot_kw=dict(projection='polar'))

ax.fill(x, y)
ax.plot(x, y, color='k')
plt.show()
```

![figure_1](https://user-images.githubusercontent.com/6197628/31099140-fe6206fc-a792-11e7-84dc-005a23e150ed.png)

**Comment by QuLogic** [comment]
So the example was fixed before 2.1.0 was released, but the question of interpolation methods still remains. Should we leave this open or open a new separate issue?

**Comment by tacaswell** [comment]
Change the title on this one to something more representative?  Only advantage of that is keeping the history of discussion a bit more contained.

**Comment by MeowsterEric** [comment]
Is there any existing image comparison test case available to test the output?
I think I have fixed the issue, but I would like to make sure it produces valid result before make any PR.

**Comment by tacaswell** [comment]
@MeowsterEric I don't think so.  The best approach would be to add a test and image _first_ and then add your fixes on top of that.
