### ISSUE TITLE
plot() mfc doesn't accept RGBA color

### ISSUE THREAD

**Issue by julietbravo** [matplotlib/matplotlib#9273]
### Bug report

**Bug summary**

`plot()` doesn't accept RGBA generated from colormap as `mfc`

**Code for reproduction**

    import matplotlib.pylab as pl
    import numpy as np

    col = pl.cm.RdBu(np.linspace(0,1,2))

    pl.figure()
    pl.plot(np.random.random(10), color=col[0])      # works
    pl.plot(np.random.random(10), 'o', mfc='k')      # works
    pl.plot(np.random.random(10), 'o', mfc=col[0])   # Fails
    # As suggested below:
    pl.plot(np.random.random(10), 'o', mfc=tuple(col[0]))   # works

**Actual outcome**

     /usr/local/lib/python3.6/site-packages/matplotlib/lines.py in set_markerfacecolor(self, fc)
        1204         if fc is None:
        1205             fc = 'auto'
     -> 1206         if self._markerfacecolor != fc:
        1207             self.stale = True
        1208         self._markerfacecolor = fc
     ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Expected outcome**

That this would work 👍 

**Matplotlib version**

  * Operating system: Mac OS 10.11
  * Matplotlib version: 2.0.2
  * Matplotlib backend: MacOSX
  * Python version: 3.6.2
  * Jupyter version (if applicable): N/A
  * Other libraries: Numpy 1.13.0

Python installed via Homebrew, all Python packages using Pip.

**Comment by WeatherGod** [comment]
Hmmm, might need to be cast as a tuple?

**Comment by julietbravo** [comment]
pl.plot(np.random.random(10), 'o', mfc=tuple(col[0]))   # works

**Comment by tacaswell** [comment]
I think this may be fixed in 2.1 (there is an rc with binaries available and binaries for the final will be coming sometime this week).

**Comment by anntzer** [comment]
Confirmed that this is solved as of 2.1.
