### ISSUE TITLE
Sharing axes not working properly in interactive mode with aspect=1

### ISSUE THREAD

**Issue by pcrumley** [matplotlib/matplotlib#9274]
### Bug report

When using aspect=1, sharing x between a 1D and a 2D plot, and sharing y for all the 2D plots, 

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

y = np.arange(10)
x = np.arange(10)
f = plt.figure()
ax1 = f.add_subplot(311)
ax1.plot(x,y)

ax2 =f.add_subplot(312, sharex = ax1)
ax2.imshow(np.random.rand(100,100), aspect = 1, extent=[0,10,0,3])

ax3 =f.add_subplot(313, sharex = ax2, sharey = ax2)
ax3.imshow(np.random.rand(100,100), aspect = 1, extent=[0,10,0,3])
plt.show()
```

**Axes are not aligned**

![screen shot 2017-10-03 at 13 11 42](https://user-images.githubusercontent.com/15001732/31138428-7449a97a-a83c-11e7-98ba-b47f227e9907.png)

**The x-axes should be the same
**

**Matplotlib version**

  * Operating system: MacOSX
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.13 
  * Jupyter version (if applicable): N/A
  * Other libraries: 

 conda, default

**Comment by jklymak** [comment]
I think @efiring had an explanation for this behaviour.  I'm not 100% sure I bought it, but...

As a workaround, turn off `sharex`, and you can get the position of ax2 *after* a call to `draw`.

However, turning off `sharex` ruins any panning experience you may have hoped to have.  

```python

f.canvas.draw()

pos2 = ax2.get_position().bounds
pos1 = ax1.get_position().bounds
ax1.set_position([pos2[0], pos1[1], pos2[2], pos1[3] ])
```

**Comment by efiring** [comment]
Try just leaving out the sharey.  I think it is causing the undesired behavior, and not helping anything.  Trying to share more than one axis while also specifying the aspect ratio tends to lead to over-specification.

The sharing code was designed for relatively simple cases, and it easily runs into problems.  I have a PR that improves the situation, I think, but breaks axis twinning--so more work is needed.

**Comment by pcrumley** [comment]
Thanks for the advice. I'm working on a GUI where I want to be able to zoom into images, so the sharey is needed. @efiring is right that leaving out sharey fixes it. Would you be willing to share your code that improves the situation? Thanks!

**Comment by efiring** [comment]
It probably doesn't address your situation, it is not finished, and it is in the guts of matplotlib, so I don't recommend trying to apply it.  Instead, I think the right solution for something like this is going to involve relying a bit less on the sharing machinery and more on explicitly setting up callbacks to propagate view limit changes from one image to the other.  Probably everything related to x can be handled with the existing sharing, so it is a matter of taking care of y via a callback.  I think this can be made to work provided the two image axes boxes remain the same--that is, for example, they are both subplots of the same figure, so they have the same on-screen aspect ratio.

I can't go into more detail right now.

**Comment by pcrumley** [comment]
@efiring: Your described method was exactly what I was planning on doing for my specific problem. Thanks again!

**Comment by jessebett** [comment]
Has this seen a solution? I also am experiencing problems with shared axes between imshows and plots when the imshow has an aspect change

**Comment by ImportanceOfBeingErnest** [comment]
@jessebett There isn't really any general solution; mostly because there is a logical constraint to sharing the axes in two dimensions and applying a fixed aspect at the same time.

That being said, feel free to share a code example for which you think matplotlib behaves unexpectedly.

**Comment by ImportanceOfBeingErnest** [comment]
@jessebett Now the important question is: How would you like this to look instead?

**Comment by jessebett** [comment]
Right, I understand that there isn't a general solution.
What I expect is that the x axis of the above subplot is scaled to be shared with the plot with specified aspect. I would also like to be able to control the height of that top subplot through something like height ratios.

I.e. I want to specify the aspect ratio of my imshow so it displays correctly. Then plot above it a subplot which shares its xaxis and also so that the ratios between imshow and plot are set.

**Comment by jklymak** [comment]
Still not quite clear what you want.  Do you want the two axes to be the same width?  If so, you can get the position of ax1, and set the xextent of ax2 with the correct values.  

sharex just means that they share their x data limits.  You have to do a bit more work to make them the same size.    

```python
import matplotlib.pyplot as plt
import numpy as np
fig=plt.figure()

ax1= fig.add_subplot(212,aspect=3)
ax0= fig.add_subplot(211,sharex=ax1)

ax0.plot(np.linspace(0, 1, 10), np.linspace(0, 20, 10))
pos1 = ax1.get_position(original=False)
pos0 = ax0.get_position(original=False)
ax0.set_position([pos1.x0, pos0.y0, pos1.width, pos0.height])

plt.show()

```

![boooo](https://user-images.githubusercontent.com/1562854/46056678-a068fe00-c106-11e8-9785-7e872e53fbc4.png)

**Comment by jessebett** [comment]
Ah! Yes you are right that it was not enough to sharex the axes. Thank you. set_position has mostly worked for me, the shared axes are just not matching up, which I think is coming from imshow. Anyway thanks!

**Comment by ImportanceOfBeingErnest** [comment]
I guess this is then asking for something like `share_x_geometry` or so. It's not a bad idea at all. And I think there would even be an immediate use case for this within matplotlib itself, namely to fix the colorbar next to an image to the image height - which is also an feature often being asked for.

**Comment by jklymak** [comment]
To me there are four things that can be shared, making the idea of "share" difficult:

1. the vlim (xmin, xmax)
2. the width of the axes
3. the x0 of the axes position (i.e. you want the axes to line up their left hand sides)
4. the decorators of the axes (i.e. should they have the same ticks and labels)?

All four can change from draw to draw, particularly because of aspect ratio calls.  

Colorbars are kind of a separate issue, which I'm also happy to discuss, but lets keep things simple here.

**Comment by ImportanceOfBeingErnest** [comment]
In my mind `share_x_geometry` is strictly limited to the combined set of *(2.)* and *(3.)* from the above list.  
*(1.)* is covered by `sharex`. *(4.)* does not seem necessary (as axes of equal width using the same locator will have the same ticks automatically). I imagine *(2.)* without *(3.)* looks weird and is specialized enough for not having it in the library. *(3.)* without *(2.)* may make sense, but I would think that this would rather be solved via a gridspec.

**Comment by jklymak** [comment]
I can imagine lots of uses for (2) without (3).  i.e. you want to keep two columns of subplots all the same width.  

(4), folks have definitely thought that setting the locator/formatter on a shared axis should set the locator/formatter on the other axis.  OTOH I agree its fine to tell them it won't and to loop though the axes and add isntances of the same locators/formatters to each.
