### ISSUE TITLE
Restore something like backend_driver

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#9284]
It turns out that @cgohlke was using this to smoke test the windows wheels.   We should provide an easy way to run all of the examples against the currently installed version of matplotlib and at least cycle through the Agg, svg, pdf, and one GUI backend.

Exact work:
 - write a script in `tools`  to exercise all of the examples and tutorials (this may have to deal with examples that call `show`, probably by turing on `plt.ion()` and defensively calling `plt.close('all')`)
 - make the backend list configurable 
 - bonus: regex matching on file names

**Comment by anntzer** [comment]
A funny (dunno how silly) way to achieve this would be to hack into sphinx-gallery.  You basically need to
1. hack what "agg" means (s-g calls `matplotlib.use("agg")`)
2. patch `s_g.gen_rst.save_figures` to instead close the figures.

Perhaps this can be done in the docs' conf.py when an environment variable is set...

**Comment by tacaswell** [comment]
I have a slight preference for this to run without any of the docs requirements (as just _building_ the docs covers 25% of the use case and likely 90% of the benefit).

**Comment by anntzer** [comment]
FWIW the following works for non-interactive backends (for interactive backends you have the additional problem of how to send it a signal to close it...):
```
diff --git a/doc/conf.py b/doc/conf.py
index 818238642..764f68223 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -480,3 +480,31 @@ def skip_deprecated(app, what, name, obj, skip, options):
 
 def setup(app):
     app.connect('autodoc-skip-member', skip_deprecated)
+
+
+if "MPL_BACKEND_DRIVER" in os.environ:
+    backend, fmt = os.environ.get("MPL_BACKEND_DRIVER").split(":")
+    import shutil
+    for regen in ["examples", "gallery"]:
+        shutil.rmtree("examples", ignore_errors=True)  # force regen
+    matplotlib.use(backend)
+    from matplotlib import pyplot as plt
+    # Tricking s-g to believe we're using Agg...
+    _get_backend = matplotlib.get_backend
+    _use = matplotlib.use
+    matplotlib.get_backend = lambda: "agg"
+    matplotlib.use = lambda backend: None
+    from sphinx_gallery import gen_gallery, gen_rst
+    matplotlib.get_backend = _get_backend
+    matplotlib.use = _use
+    _generate_gallery_rst = gen_gallery.generate_gallery_rst
+    def generate_gallery_rst(app):
+        _generate_gallery_rst(app)
+        sys.exit(0)
+    gen_gallery.generate_gallery_rst = generate_gallery_rst
+    def save_figures(*args):
+        for fignum in plt.get_fignums():
+            from io import BytesIO
+            plt.figure(fignum).savefig(BytesIO(), format=fmt)
+        return "", 0
+    gen_rst.save_figures = save_figures
```

Run with `MPL_BACKEND_DRIVER=agg:png ./make.py` (or `svg:svg`, or `pdf:pdf`, etc.)

**Comment by dstansby** [comment]
*cough* I tried to do this a while back ;) https://github.com/matplotlib/matplotlib/pull/8069

Wouldn't be surprised if it's easier dumping `backend_driver` and starting from scratch though.

**Comment by tacaswell** [comment]
@dstansby :sheep:

**Comment by anntzer** [comment]
closed by https://github.com/matplotlib/matplotlib/pull/17226
