### ISSUE TITLE
categorical axis sorts its keys

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9312]
### Bug report

**Bug summary**

Categorical (i.e. string) xdata inputs get sorted before plotting.

**Code for reproduction**

```python
plt.bar(["b", "a", "c"], [2, 1, 3])
```

**Actual outcome**

Bars appear in the order "a", "b", "c".

**Expected outcome**

Bars appear in the order of the input, so "b", "a", "c".

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version: 2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by story645** [comment]
closed by #9783 though the jpl implementation of [strconvertor](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/testing/jpl_units/StrConverter.py) has me thinking we should support sorted and unsorted by stashing the info in the plot kwarg arg and as an attribute on unitdata.
