### ISSUE TITLE
Can't exit the Drawing board process on Ubuntu

### ISSUE THREAD

**Issue by laoqiren** [matplotlib/matplotlib#9315]
### Bug report

**Bug summary**

Can't exit the Drawing board process on Ubuntu after the `python` process is killed by `ctrl+z`

**Matplotlib version**
  * Operating system: Ubuntu 16.04
  * Matplotlib version:  v2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: v3.5.2

Installed by pip3.  I use matplotlib to draw my matrix, it works fine. When I exit the drawing board first then I kill Python process, it works fine. While I kill Python process using `ctrl+z`, I found that the drawing board hasn't exited, I try to exit it, but it can't.  I have to find its process id to kill it.

**Comment by QuLogic** [comment]
`ctrl+z` doesn't kill the process, it puts it to sleep. You can use `fg` to bring it back or `bg` to resume running in the background. You can use `ctrl+c` to actually interrupt the process, but it's better to just close the window.

Closing as this is not a Matplotlib bug.
