### ISSUE TITLE
Non-reproducible line in Image tutorial

### ISSUE THREAD

**Issue by redi35** [matplotlib/matplotlib#9326]
### Bug report

**Bug summary**

The Image tutorial features a line of code which isn't reproducible. An `Out[5]` line is hard-coded into the tutorial by using a `print(img)` behind the scenes, in the source code of the article.

**Code for reproduction**

```python
In[5]: img=mpimg.imread('stinkbug.png')
```

**Actual outcome**

No output.

**Expected outcome**

![screenshot from 2017-10-08 21-52-41](https://user-images.githubusercontent.com/9330492/31321210-5b7a715a-ac82-11e7-9181-79676b9695f7.png)

Didactically, it would be a huge improvement to just call the resulting object after the assignment made above, i.e. actually generating the output which is contained in the `Out[#]`line:

``In[6]: img``

As is, there is a disconnect between the `In[5]`line and the following `Out[5]` in the tutorial. This is simply incorrect. It isn't reproducible and leaves room for unnecessary confusion for first readers.

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.5.2
  * Jupyter version (if applicable):IPython 6.0.0
  * Other libraries:

**Comment by anntzer** [comment]
This has been fixed as of 2.1.0 thanks to the switch to sphinx-gallery: http://matplotlib.org/tutorials/introductory/images.html#sphx-glr-tutorials-introductory-images-py

Closing, but feel free to request a reopen if anything is unclear.
