### ISSUE TITLE
Cannot open Matplotlib figure in new Process on Mac

### ISSUE THREAD

**Issue by petered** [matplotlib/matplotlib#9330]
### Bug report

If I try to launch a process that creates a matplotlib figure, the process hangs when trying to create the figure.  [See StackOverflow post](https://stackoverflow.com/questions/46621002/cannot-open-matplotlib-figure-in-new-process-on-mac)

This only appears to be a problem on Mac - I am not able to reproduce it on my Linux machine.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from multiprocessing import Process
import numpy as np

def plotit():
    data = np.cos(np.linspace(0, 10, 100))
    print 'Gets Here'
    plt.figure()
    print 'But This is never printed.'
    plt.plot(data)
    plt.show()

def main():
    p = Process(target=plotit)
    p.start()
    print raw_input('Press Enter when Done>>')

if __name__ == '__main__':
    main()
```

**Actual outcome**
```
Press Enter when Done>>Gets Here
```
... The new process hangs on `plt.figure()`, and no figure ever displays.

**Expected outcome**

(Figure should appear, all print statements should appear)

**Matplotlib version**

  * Operating system: OSX Sierra 10.12
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.12

(Installed with pip in virtual env)

**Comment by jklymak** [comment]
Does the tkagg backend work for you properly on Macos otherwise?  I’m not sure pip installs tk for instance.

**Comment by petered** [comment]
Yep, if I directly call plotit instead of launching a new process that call it it plots fine.

**Comment by jklymak** [comment]
I agree this doesn't work on my mac.  No idea what the issue is...

**Comment by tacaswell** [comment]
Most GUI frameworks do not like being used on the other side of a fork.  If you put

```python
import matplotlib
matplotlib.use('agg')
```

at the very top does it work (as in not hang, it should not show you any GUI windows though).

**Comment by timhoffm** [comment]
Matplotlib is not thread-safe. I assume that importing pyplot in one thread and creating a figure in the other thread is the problem.
