### ISSUE TITLE
`matplotlib.pyplot` is missing from intersphinx

### ISSUE THREAD

**Issue by bsipocz** [matplotlib/matplotlib#9331]
The updates to the API docs for the new v2.1 release apparently has some consequences for downstream documentation.

In a few places in astropy we link to ``matplotlib.pyplot`` using intersphinx. However the new mapping doesn't have this it any more in the module mapping part. 

I wonder what is the suggested approach? I would like to avoid hard wiring a link, or not linking at all. Also, the link using the old inventory resolves to ``http://matplotlib.org/api/pyplot_api.html#module-matplotlib.pyplot`` and it still seems to work, just missing from the new inventory.

**Comment by siebenkopf** [comment]
This is not only breaking your own links, but also links of other packages that want to use `intersphinx` to link to the `matplotlib.pyplot` module. For example, the following example sphinx documentation worked until recently, but does not work with version `2.1.0`:
```
:py:mod:`matplotlib.pyplot`
```

It would be great if you could add back `matplotlib.pyplot` to the API documentation.

**Comment by anntzer** [comment]
xref https://github.com/matplotlib/matplotlib/pull/8175 I guess the resolution should be similar.

**Comment by tacaswell** [comment]
yikes,  sorry about that!

**Comment by tacaswell** [comment]
The docs have been re-built and the xref should now be there.

Closed by #9386

**Comment by bsipocz** [comment]
Thank you @tacaswell!

**Comment by siebenkopf** [comment]
Great, thanks a lot :-)
