### ISSUE TITLE
Remove restriction in `plt.margins(m)` to  0 <= m <= 1 

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#9334]
Setting the margin (`ax.margins`) to something outside the range between 0 and 1 

    ax.margins(x=3)

result in an error. This is due to the lines:

    if m < 0 or m > 1:
            raise ValueError("margin must be in range 0 to 1")

in the axes._base's [`set_xmargin`](https://github.com/matplotlib/matplotlib/blob/969de0af74e64dd9edebd4a3dffcab954bad63fe/lib/matplotlib/axes/_base.py#L2071) method. 
This limitation seems rather arbitrary to me. 

If one comments out the restriction to 0 <= m <= 1, setting `ax.margins(3)` produces a result as expected, so it does not even seem to have any bad implications

```
import numpy as np
import matplotlib.pyplot as plt

x = np.array([0,0,1,0,1])*1.9+10.466
y = np.array([0,1,1,0,0])*1.9+10.466
x2 = np.array([1,0,0.5,1,1])*1.9+10.466
y2 = np.array([0,1,1.5,1,0])*1.9+10.466

plt.plot(x,y)
plt.plot(x2,y2)

plt.margins(3)

plt.show()
```
![image](https://user-images.githubusercontent.com/23121882/31345247-6244d80c-ad15-11e7-96c4-0bb9b7f891a1.png)

Sure, we can replace the single line `plt.margins(3)` by

```
margin=3
xmax = np.max([x.max(),x2.max()])
xmin = np.min([x.min(),x2.min()])
ymax = np.max([y.max(),y2.max()])
ymin = np.min([y.min(),y2.min()])

plt.gca().set_xlim(xmin-(xmax-xmin)*margin, xmax+(xmax-xmin)*margin)
plt.gca().set_ylim(ymin-(ymax-ymin)*margin, ymax+(ymax-ymin)*margin)
```

but if there isn't really any reason for the restriction, this would be overly complicated.

Therefore I would like to ask if there is a reason for the restriction `0 <= m <= 1`, and if not whether we could simply get rid of it.

**Comment by jklymak** [comment]
I don't think you want a negative margin!  I agree that there doesn't seem to be a reason to prohibit >1.

**Comment by ImportanceOfBeingErnest** [comment]
A negative margin could be used to zoom into the center of the plot. Probably there are only rare use cases for it, but why not. Plus, it also works if you comment out the restriction, e.g. `plt.margins(-0.1)` gives 
![image](https://user-images.githubusercontent.com/23121882/31346646-102f8198-ad1a-11e7-9d52-e72f679040d4.png)

**Comment by jklymak** [comment]
OK, what does -1.1 give?

**Comment by ImportanceOfBeingErnest** [comment]
`plt.margins(-1.1)` would work as well; it is equivalent to `plt.margins(1.1)` 
because `plt.gca().set_xbound(x0,x1)` is the same as `plt.gca().set_xbound(x1,x0)`.

**Comment by ImportanceOfBeingErnest** [comment]
I guess the hard limit should simply be `m > -0.5`, or in terms of the code

```
if m <= -0.5:
        raise ValueError("margin must greater than -0.5")
```

because `-0.5` would result in an infinitesimally small axis range (and therefore an `UserWarning: Attempting to set identical left==right results
in singular transformations`)  and everything below is just equivalent to some positive setting.

**Comment by anntzer** [comment]
I think a limit of -0.5 makes sense.

**Comment by tacaswell** [comment]
:+1: 

Exact work:

 - adjust limit checks
 - document use of margins >1 and < 0 in an example
 - add a test that it fails for < -0.5

**Comment by AtharvaKhare** [comment]
May I attempt to fix this issue?

**Comment by anntzer** [comment]
Go for it.

**Comment by jklymak** [comment]
@AtharvaKhare On gitter you asked about creating a test.  I'm new to this as well, but there are two kinds of tests - image tests, and logical tests.   For this, I think you can do fine with a logical test.  i.e.  set the margin and then `assert` that the new xlims and ylims are equal to what you expect them to be. You could probably just add to `lib/matplotlib/tests/test_axes.py:test_margins()`.

**Comment by AtharvaKhare** [comment]
@jklymak Thank you.
