### ISSUE TITLE
Integer Categorical Values Not Getting Mapped Correctly

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#9336]
As @anntzer described in #9318, integer categoricals (even when strings) aren't using the unit mapping and so are being handled incorrectly:
```python
fig, ax = plt.subplots()
ax.set_xlim([-1,2])
ax.set_ylim([0,2])
ax.plot(["!", "0"], [1, 2])
```
![index](https://user-images.githubusercontent.com/1300499/31353153-6dd1987e-acff-11e7-8282-c13b05dc810b.png)

ETA: Ok, so the bug is that it's doing an inplace substitution, and casting into a string:
```
vals[vals=='!'] = 0 # casts into string
vals=='0' # matches everything
```

**Comment by tacaswell** [comment]
Closed by #9783
