### ISSUE TITLE
referencing a plot_directive plot does not work

### ISSUE THREAD

**Issue by quantenschaum** [matplotlib/matplotlib#9346]
### Bug report

**Bug summary**

A figure created with `plot_directive` and preceeding label cannot be referenced with `:ref:` or `:numref:`.

**Code for reproduction**

```rst
.. _bar:

Testplot
--------

.. _foo:

.. plot::

   import matplotlib.pyplot as plt
   import numpy as np
   plt.hist(np.random.randn(1000), 20)

reference to plot: :ref:`foo` / :numref:`foo`
	
reference to section: :ref:`bar` / :numref:`bar`
```

**Actual outcome**

rendered HTML

![bildschirmfoto_2017-10-10_18-42-44](https://user-images.githubusercontent.com/3985599/31398922-d75c4e24-adea-11e7-9347-cbec853efb33.png)

LaTeX code

```latex
\subsection{Testplot}
\label{\detokenize{M01/index:testplot}}\label{\detokenize{M01/index:bar}}\phantomsection\label{\detokenize{M01/index:foo}}
\begin{figure}[H]
\centering

\noindent\sphinxincludegraphics{{index-1}.pdf}
\end{figure}

reference to plot: \DUrole{xref,std,std-ref}{foo} / \sphinxcode{foo}

reference to section: {\hyperref[\detokenize{M01/index:bar}]{\sphinxcrossref{\DUrole{std,std-ref}{Testplot}}}} / \hyperref[\detokenize{M01/index:bar}]{Section \ref{\detokenize{M01/index:bar}}}
```

**Expected outcome**

The `foo` references should be links like the `bar` references.

**Matplotlib version**
  * Operating system: Linux 4.10.0-35-generic 39~16.04.1-Ubuntu 16.04.3 LTS SMP x86_64 GNU/Linux
  * Matplotlib version: 2.1.0 via pip
  * Python version: 3.5.2
  * Other libraries: Sphinx (sphinx-build) 1.6.4

**Comment by quantenschaum** [comment]
1. The `plot` directive should support the [`:name:` option](http://docutils.sourceforge.net/docs/ref/rst/directives.html#name) to add a named label.
2. Especially for inline plot code there should be a `:caption:` option

**Comment by quantenschaum** [comment]
`:numref:` works with the following template in `conf.py` where the `only` directives have been removed.

```python
plot_template = """
{{ source_code }}

{% for img in images %}
.. figure:: {{ build_dir }}/{{ img.basename }}.{{ default_fmt }}
   {% for option in options -%}
   {{ option }}
   {% endfor %}

   {% if html_show_formats and multi_image -%}
     (
     {%- for fmt in img.formats -%}
     {%- if not loop.first -%}, {% endif -%}
     `{{ fmt }} <{{ dest_dir }}/{{ img.basename }}.{{ fmt }}>`__
     {%- endfor -%}
     )
   {%- endif -%}

   {{ caption }}
{% endfor %}
"""
```

**Comment by quantenschaum** [comment]
Adding `:caption:` is easy. 
In `setup()` add `'caption': directives.unchanged` to the `options`. And in `run()` add `if 'caption' in options: caption=options['caption']` before `format_template()`.

**Comment by anntzer** [comment]
Feel free to open a PR (preferably with a test -- sphinx has been having many backcompat issues in recent versions so we should try to make sure things stay in a working state...) :-)

**Comment by quantenschaum** [comment]
When I try to add `'name'` to the `options` in `setup()`, I get

```
TypeError: add_directive() got multiple values for argument 'name'
```
So it seems, as if there was already a `name` option, but supplying `:name:` does not work either.

```
(ERROR/3) Error in "plot" directive: unknown option: "name".
```

**Comment by tacaswell** [comment]
Is this documented to work and does not or would you like this to work as described?

**Comment by quantenschaum** [comment]
Referencing plots is not explicitly mentioned in the [docs](https://matplotlib.org/devel/documenting_mpl.html#module-matplotlib.sphinxext.plot_directive), but since the `plot_directive` generates a `figure`, which can be labelled by putting a label in front of it, I would expect  the plot to catch the label and the ref to be working. There is even [code](https://github.com/matplotlib/matplotlib/blob/ad730d1314cd2113ae96edac4c76984e439dd868/lib/matplotlib/sphinxext/plot_directive.py#L224) for moving 
> the reference from the "htmlonly" (or "latexonly") code to the actual figure node itself
but seems to fail.

**Comment by quantenschaum** [comment]
The culprit is [`mark_plot_labels`][(https://github.com/matplotlib/matplotlib/blob/ad730d1314cd2113ae96edac4c76984e439dd868/lib/matplotlib/sphinxext/plot_directive.py#L224). It look for tagnames `html_only` and `latex_only`, but they are [actually](https://github.com/matplotlib/matplotlib/blob/ad730d1314cd2113ae96edac4c76984e439dd868/lib/matplotlib/sphinxext/plot_directive.py#L819) named `only`.

After fixing this, it fail, because there is no [`document.settings.env.labels`](https://github.com/matplotlib/matplotlib/blob/ad730d1314cd2113ae96edac4c76984e439dd868/lib/matplotlib/sphinxext/plot_directive.py#L250)

**Comment by quantenschaum** [comment]
I modified the code such that it adds the `:name:` option to the figure in the template. I printed the [`result`](https://github.com/matplotlib/matplotlib/blob/ad730d1314cd2113ae96edac4c76984e439dd868/lib/matplotlib/sphinxext/plot_directive.py#L830) to console. The `:name:` is there as expected, but the ref does not work. If I paste the code, generated by the template engine, into the actual source, the ref is working.

Why does a label inside the `onyl` directive generated by the template engine not work?

**Comment by tushuhei** [comment]
I believe the root causation is how the `only` directive handles references, as pointed out at https://github.com/sphinx-doc/sphinx/issues/2150.
If we add `:name:` along with other options, it will be rendered twice (one within `only:: html` and the other within `only:: not html`), which will cause the `Duplicate explicit target name` warning eventually.

**Comment by eudoxos** [comment]
Anyone has a workaround for this, besides the hack in https://github.com/sfstoolbox/theory/issues/5 ?
