### ISSUE TITLE
Matplotlib introduction is unattributed

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#9348]
The new website/docs look like a huge improvement! Fantastic work by all involved.

While poking around, I noticed that the ["introduction"](http://matplotlib.org/users/intro.html) is written in the first person but is unattributed. I assume the author is John Hunter. It might be nice to add that attribution in some form.

**Comment by tacaswell** [comment]
It is indeed mostly JDH who wrote that (but by now the `git blame` identifies many copy edits).

**Comment by mwaskom** [comment]
FWIW I also think it might be better to re-categorize the page as "History" or something similar. It's interesting, and provides somewhat of a high-level overview of the goals/structure of the package, but (with all respect for John) I'm not sure it's the most informative first 5 minutes for someone who wants to know what they can get out of matplotlib these days.
