### ISSUE TITLE
mpl 2.1 barcharts edgecolor and linewidth only apply to first bar

### ISSUE THREAD

**Issue by jolespin** [matplotlib/matplotlib#9351]
I ran some code and realized it is only working on the first bar.  I'm using Python 3.6.2, matplotlib 2.1.  Just reverted back to 2.0.2.
![image](https://user-images.githubusercontent.com/9061708/31414567-668d8472-add3-11e7-8ea5-8f3fb9f7d36d.png)

**Comment by jolespin** [comment]
![image](https://user-images.githubusercontent.com/9061708/31414786-76a43440-add4-11e7-8497-600b30254014.png)

**Comment by afvincent** [comment]
I can confirm the issue with a fresh install of Matplotlib 2.1 (from conda) on GNU/Linux (Fedora 26), with Python 3.6.3 (from conda):
```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(num='mwe_scalar_bar_ec')
x = np.arange(1, 10)
ax.bar(x, x, edgecolor="black", lw=3)

fig.savefig(fig.get_label() + ".png")
```
![mwe_scalar_bar_ec](https://user-images.githubusercontent.com/17270724/31414932-2f666a8e-add5-11e7-8bea-d62dbeaba082.png)

**Comment by jolespin** [comment]
Off topic but what does `num='mwe_scalar_bar_ec'` do?

**Comment by anntzer** [comment]
See #9353.

**Comment by afvincent** [comment]
@jolespin I define the name of the figure. I then use it to define the name of the figure with (`fig.get_label()`). The name of the kwarg ('num') is due to the MATLAB legacy IIRC.

**Comment by afvincent** [comment]
@anntzer You are too fast ^^... And `git bisect` indeed yells 
`5348ce9551e2975050a495af1259294f03d3af12 is the first bad commit`

**Comment by timhoffm** [comment]
## Workaound

The bug is just a missing broadcasting of the `edgecolor`. You can circumvent this by explicitly setting it for all bars:

    ax.bar(x, y, linewidth=3, edgecolor=['black']*len(x))

**Comment by wardakhan149** [comment]
i am using the code below.

def show_hsv_hist(image):
    plt.figure(figsize=(20, 3))
    histr = cv2.calcHist([image], [0], None, [180], [0, 180])
    plt.xlim([0, 180])
    colours = [colors.hsv_to_rgb((i/180, 1, 0.9)) for i in range(0, 180)]
    plt.bar(range(0, 180), histr, color=colours, edgecolor = colours, width = 1)
    plt.title('Hue')



and getting the following error:
### 
**only size-1 arrays can be converted to Python scalars**



can someone help me here ? :(

**Comment by tacaswell** [comment]
@wardakhan149 That question would probably be better on the mailing list (matplotlib-users@python.org see https://mail.python.org/mailman/listinfo/matplotlib-users ).

Please include a minimal runnable example and the full traceback (it makes it _way_ easier to help you if we can copy-paste reproduce the problem and see the full traceback you are seeing).

Good luck!
