### ISSUE TITLE
Undefined name `baseline`?

### ISSUE THREAD

**Issue by cgohlke** [matplotlib/matplotlib#9429]
At https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mathtext.py#L2114 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mathtext.py#L2118, `baseline` seems to be undefined. Am I missing something?

**Comment by QuLogic** [comment]
Maybe should be `base_line`? https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mathtext.py#L2078

**Comment by tacaswell** [comment]
That it should be `base_line` seems plausible.

We do not cover this in our tests https://codecov.io/gh/matplotlib/matplotlib/src/master/lib/matplotlib/mathtext.py#L2109

Now to sort out how to trigger this code path.....
