### ISSUE TITLE
Memory issue using PdfPages

### ISSUE THREAD

**Issue by sommerc** [matplotlib/matplotlib#944]
I am generating several big multi-page pdf files including images.

Is there a possibility to flush these object into the pdf file without closing the pdf file before main memory is overflowing?

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue. Thanks!

**Comment by tacaswell** [comment]
Closing as no motion in 5 years.

**Comment by joekiller** [comment]
This would be a good feature.
