### ISSUE TITLE
how to remove the black bounding box of legend?

### ISSUE THREAD

**Issue by houxingxing** [matplotlib/matplotlib#9453]
I want to remove the black bounding box of legend in picture? however I can't find a function to realize this target.

The Matlab has this function like this:
`y=[500  218 11.4635
1000 162 13.2981
2000 123 15.2614
3000 94 17.4575
4000 83 18.5784
5000 76 19.4151
6000 65 20.9937
7000 54 23.0329];

plot(y(:,1)./1000,y(:,3),'^r-')  

set(gca,'Xtick',[0:8])
xlabel('\fontsize{15}X')
ylabel('\fontsize{15}Y')
h=legend('\fontsize{15}0%')

h =

    1.590021972656250e+002

>> set(h,'box','off')` 

matplotlib version: 1.5.2
python version: 2.7.3

**Comment by anntzer** [comment]
See the documentation of `legend`:
```
    frameon : None or bool
        Control whether the legend should be drawn on a patch (frame).
        Default is ``None`` which will take the value from the
        ``legend.frameon`` :data:`rcParam<matplotlib.rcParams>`.
```
Setting `frameon` to False removes the frame.
Please ask questions on gitter or the mailing list, and keep the issue tracker for issues.
