### ISSUE TITLE
ticklabel and gridlines in polar projection in v2.1.0

### ISSUE THREAD

**Issue by YingzhiGou** [matplotlib/matplotlib#9455]
### Bug report

**Bug summary**

After creating subplot with polar=True, 
* grid() function call to set alpha to the grid line only changes xaxes, yaxes remain unaffected
* when trying to hide the tick labels on yaxes using `plt.setp(ax.yaxis.get_ticklabels(), visible=False)`, labes are not affected

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, polar=True)

# make all major grid lines lighter, only x grid lines set in 2.1.0
ax.grid(alpha=0.2)   

# hide y tick labels, no effect in 2.1.0
plt.setp(ax.yaxis.get_ticklabels(), visible=False) 
fig.show()

fig.savefig("polar.png")
```

**Actual outcome**

![figure in 2.1.0](https://user-images.githubusercontent.com/29586247/31657503-42e9da1e-b37a-11e7-8aac-029abc42de72.png)

**Expected outcome**
![figure in 2.0.2](https://user-images.githubusercontent.com/29586247/31657502-42b6d2ea-b37a-11e7-8b9a-17949d9d6610.png)

**Matplotlib version**

  * Operating system: Ubuntu 17.04
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.13
  * Jupyter version (if applicable):
  * Other libraries: 
backports.functools-lru-cache==1.4
click==6.7
click-plugins==1.0.3
cligj==0.4.0
cycler==0.10.0
descartes==1.1.0
enum34==1.1.6
Fiona==1.7.9.post1
functools32==3.2.3.post2
GDAL==2.1.0
geopandas==0.3.0
matplotlib==2.1.0
munch==2.2.0
numpy==1.13.3
olefile==0.44
pandas==0.20.3
Pillow==4.3.0
py==1.4.34
pyparsing==2.2.0
pyproj==1.9.5.1
pytest==3.2.3
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
scipy==0.19.1
Shapely==1.6.1
six==1.11.0
subprocess32==3.2.7

all packages are installed using pip in virtualenv

**Comment by dstansby** [comment]
Hmm, your example seems to be working fine for me using Matplotlib `2.1` on python 3.6.3 with the TkAgg backend - what does `import matplotlib; print(matplotlib.__version__)` print for you?

![figure_1](https://user-images.githubusercontent.com/6197628/31664827-d85264e0-b33e-11e7-9d9b-7f55aacc1554.png)

**Comment by YingzhiGou** [comment]
use the following modified code to print the version, backend and alpha value of the gridline
```python
import matplotlib
import matplotlib.pyplot as plt

print(matplotlib.__version__)  # print version
print(matplotlib.get_backend())  # print backend

fig = plt.figure()
ax = fig.add_subplot(111, polar=True)

# make all major grid lines lighter, only x grid lines set in 2.1.0
ax.grid(alpha=0.2)   

# hide y tick labels, no effect in 2.1.0
plt.setp(ax.yaxis.get_ticklabels(), visible=False) 
fig.show()

fig.savefig("polar.png")

# prints alpha of one major gridline of each axis
print(ax.xaxis.majorTicks[0].gridline._alpha)
print(ax.yaxis.majorTicks[0].gridline._alpha)
```

# output in 2.1.0
```
2.1.0
TkAgg
0.2
1.0
```

# output in 2.0.2
```
2.0.2
TkAgg
0.2
0.2
```

**Comment by jklymak** [comment]
On macos:

```
2.1.0.post405+g7204e03ca
TkAgg
0.2
0.2
```

**Comment by YingzhiGou** [comment]
just tried on windows in anaconda
```
2.1.0
TkAgg
0.2
1.0
```
and in cygwin pyton with agg backend
```
2.1.0
agg
0.2
1.0
```
in cygwin python with svg backend
```
2.1.0
svg
0.2
1.0
```

 also, the y tick labels also visible in all the image created in 2.1.0 (same as the actual outcome in the original report)

and all the tests are also run with 2.0.2 and the output is the same as the expected outcome in the original report.

it seems has nothing to do with the backend and the platform but only happen in python 2.7.13?

**Comment by tacaswell** [comment]
I also can not reproduce this with 3.6 on linux but I can reproduce this with python2.7.

python-version dependent behavior smells like dictionary order in `**kwargs` handling someplace....(we saw this a lot with 3.4 and 3.5 when dictionary order was random from process-to-process).

@YingzhiGou Can you just switch to python3?

**Comment by tacaswell** [comment]
Something in the draw process is resetting the alpha to 1

```
In [22]: [(t.gridline.set_alpha(.5), t.gridline.get_alpha()) for t in ya.majorTicks]
Out[22]: [(None, 0.5), (None, 0.5), (None, 0.5), (None, 0.5), (None, 0.5)]

In [23]: [(t.gridline.get_alpha()) for t in ya.majorTicks]
Out[23]: [0.5, 0.5, 0.5, 0.5, 0.5]

In [24]: ax.figure.canvas.draw()

In [25]: [(t.gridline.get_alpha()) for t in ya.majorTicks]
Out[25]: [1.0, 1.0, 1.0, 1.0, 1.0]

```

That is odd....

**Comment by tacaswell** [comment]
Something is wrong in the tranfrom comparisons

```python
(Pdb) d
> /home/tcaswell/src/p/matplotlib/lib/matplotlib/projections/polar.py(974)draw()
-> self.yaxis.reset_ticks()
(Pdb) l
969                 yaxis_text_transform = self._yaxis_transform
970             else:
971                 yaxis_text_transform = self._r_label_position + self.transData
972             if self._yaxis_text_transform != yaxis_text_transform:
973                 self._yaxis_text_transform.set(yaxis_text_transform)
974  ->             self.yaxis.reset_ticks()
975                 self.yaxis.set_clip_path(self.patch)
976  
977             Axes.draw(self, *args, **kwargs)
978  
979         def _gen_axes_patch(self):
(Pdb) self._yaxis_text_transform != yaxis_text_transform
True
(Pdb) self._yaxis_text_transform == yaxis_text_transform
True
(Pdb) 

```

**Comment by tacaswell** [comment]
```python
> /home/tcaswell/src/p/matplotlib/lib/matplotlib/projections/polar.py(974)draw()
-> self.yaxis.reset_ticks()
(Pdb) l
969                 yaxis_text_transform = self._yaxis_transform
970             else:
971                 yaxis_text_transform = self._r_label_position + self.transData
972             if self._yaxis_text_transform != yaxis_text_transform:
973                 self._yaxis_text_transform.set(yaxis_text_transform)
974  ->             self.yaxis.reset_ticks()
975                 self.yaxis.set_clip_path(self.patch)
976  
977             Axes.draw(self, *args, **kwargs)
978  
979         def _gen_axes_patch(self):
(Pdb) yaxis_text_transform == self._yaxis_text_transform
False
(Pdb) self._yaxis_text_transform == yaxis_text_transform
True
(Pdb) yaxis_text_transform != self._yaxis_text_transform
True
(Pdb) yaxis_text_transform == self._yaxis_text_transform
False
(Pdb) self._yaxis_text_transform == yaxis_text_transform
True
(Pdb) self._yaxis_text_transform != yaxis_text_transform
True
(Pdb) self._yaxis_text_transform._child != yaxis_text_transform
False
(Pdb) self._yaxis_text_transform._child == yaxis_text_transform
True
(Pdb) yaxis_text_transform == self._yaxis_text_transform._child
True
(Pdb) yaxis_text_transform != self._yaxis_text_transform._child
False
(Pdb) 

```

**Comment by tacaswell** [comment]
Ah, yup, compare

https://docs.python.org/2.7/reference/datamodel.html#object.__eq__

> There are no implied relationships among the comparison operators. The truth of x==y does not imply that x!=y is false. Accordingly, when defining __eq__(), one should also define __ne__() so that the operators will behave as expected. 

vs

https://docs.python.org/3.5/reference/datamodel.html#object.__eq__

> By default, __ne__() delegates to __eq__() and inverts the result unless it is NotImplemented.

**Comment by QuLogic** [comment]
I knew that would be trouble... But `x == y` vs `y == x` was not what I expected to be wrong.

**Comment by tacaswell** [comment]
I have a simple fix ready, it is patching over a maybe bigger issue, but at least makes the python versions behave the same.

**Comment by tacaswell** [comment]
The only result that is 'correct' is `self._yaxis_text_transform == yaxis_text_transform # True`, the flipped version is wrong (and still is, but we are comparing in the correct order for it to 'just work').

**Comment by anntzer** [comment]
I guess this can be closed now?
