### ISSUE TITLE
XKCD context manager not resetting anymore in 2.1

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#9520]
### Bug report

**Bug summary**

The xkcd context manager does not reset the config anymore

**Code for reproduction**

```python
import matplotlib.pyplot as plt

with plt.xkcd():
    plt.figure()
    plt.plot([1, 2, 3])
    plt.savefig('xkcd.png', dpi=300)


plt.figure()
plt.plot([1, 2, 3])
plt.savefig('not_xkcd.png', dpi=300)
```

**Actual outcome**

Both figures are in xkcd style

**Expected outcome**
Second figure should be using default style

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6

using anaconda

**Comment by jklymak** [comment]
Is that example still documented that way?  I think the way you do it now is at http://matplotlib.org/tutorials/introductory/customizing.html#temporary-styling

**Comment by MaxNoe** [comment]
http://matplotlib.org/api/_as_gen/matplotlib.pyplot.xkcd.html

**Comment by jklymak** [comment]
Yes fair enough.  And it’s not implemented as a style.

**Comment by Kojoley** [comment]
`2.0.2` is not affected, `2.1.0rc1` contains the bug.

**Comment by jklymak** [comment]
Did this do it?  

https://github.com/matplotlib/matplotlib/commit/74680f619e924ca84fe31acbce2276c05fe29bf7 

@anntzer

**Comment by jklymak** [comment]
I think I have a fix...
