### ISSUE TITLE
How to avoid override pie

### ISSUE THREAD

**Issue by anxiaoyi** [matplotlib/matplotlib#9538]
![pie](https://user-images.githubusercontent.com/4382796/31880065-0478e274-b812-11e7-94de-6c4be25d17c8.png)

```python
figure = plt.pie(size_ratios,
                     colors=COLORS,
                     autopct='%1.1f%%',
                     shadow=False,
                     radius=1)
```

How to avoid legend label override pie chart ?

**Comment by ImportanceOfBeingErnest** [comment]
Note that the matplotlib issue tracker is in general not the place to ask question like "How to ...".

As commented on Stackoverflow to [the same question](https://stackoverflow.com/questions/46885649/control-matplotlib-draw-pie-position) already: Here, the simplest solution is probably to `plt.subplots_adjust(left=0.05, right=0.7)` and then move the legend using `bbox_to_anchor` as shown e.g. in [this question](https://stackoverflow.com/questions/43272206/python-legend-overlaps-with-the-pie-chart) or [this answer](https://stackoverflow.com/a/43439132/4124317).

**Comment by jklymak** [comment]
Closing unless you think the functionality is broken.
