### ISSUE TITLE
Display warning on out-of-date documentation websites

### ISSUE THREAD

**Issue by fkohlgrueber** [matplotlib/matplotlib#9553]
I was already beginning to file a ticket here because I didn't find any information about `pytest` in the docs until I realized that I've been using an old documentation page.

I was using https://matplotlib.org/2.0.2/devel/contributing.html instead of https://matplotlib.org/devel/contributing.html

As it is now, it's hard to see that you're using the documentation of an old version, and if you're not paying attention to the URL, you might not realize it. 

Would it be possible to display a warning on all websites of old versions? Something like the warning displayed [here](https://matplotlib.org/1.5.3/contents.html) but with a text like "This is the documentation of Matplotlib 2.0.2. Click here to view the documentation of the latest version." 

One could argue that these old version documentation websites are only used by people who explicitly search for it, but I think that that's not true. I (somehow) managed to use the websites above, most likely because I was using google to get to the documentation.

**Comment by tacaswell** [comment]
I think our pages are systematic enough that it should be possible to inject that banner into the old docs.

**Comment by anntzer** [comment]
Similarly note the confusion between
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.pcolor.html#matplotlib.pyplot.pcolor (2.1.0)
and
https://matplotlib.org/api/pyplot_api.html (2.0.2, google also pointed me there...)

(there's actually nothing that warns that it's 2.0.2, except the page title...)

**Comment by QuLogic** [comment]
Canonical links and redirects were added in matplotlib/matplotlib.github.com#49. There is also a banner noting that the page is outdated at the top of the page.
