### ISSUE TITLE
Inconsistency between AutoLocator and AutoDateLocator

### ISSUE THREAD

**Issue by Mark531** [matplotlib/matplotlib#9558]
### Bug report

**Bug summary**

The method tick_values() can be called directly with AutoLocator but not with AutoDateLocator.

**Code for reproduction**

```python
from matplotlib.ticker import AutoLocator
l = AutoLocator()
l.tick_values(10, 20) # works

from matplotlib.dates import AutoDateLocator
import datetime

l = AutoDateLocator()
start = datetime.date(2002, 1, 5)
end = datetime.date(2003, 12, 1)
l.tick_values(start, end) # Error
```

**Actual outcome**

```
array([ 10.,  12.,  14.,  16.,  18.,  20.])
AttributeError: 'NoneType' object has no attribute 'get_view_interval'
```

**Expected outcome**

 expect the AutoDateLocator to be independent of the axis or other graphical objects. It should be able to generate date ticks on its own.

**Matplotlib version**

  * Operating system: Win10
  * Matplotlib version: 1.5.1
  * Matplotlib backend (module://ipykernel.pylab.backend_inline):
  * Python version: 3.5.1
  * Jupyter version (if applicable):
  * Other libraries: 

I'm using Anaconda (conda 4.2.9).

**Comment by dstansby** [comment]
This is expected - `AutoDateLocator` can't choose a specific Locator until it is associated with an axis. I'll keep this open so we can add a better error message.

**Comment by dstansby** [comment]
I think what I said above is wrong... will have a look at this issue properly soon
