### ISSUE TITLE
Can you add some speed speed to matplotlib.pyplot.stem?

### ISSUE THREAD

**Issue by Felix-neko** [matplotlib/matplotlib#9560]
I've tried to plot `plt.stem` on 10000 points. It was as slow as hell even when I've tried to switch off any markers.

Cannot you somehow increase its performance?

The code is here: 

```
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0.1, 2 * np.pi, 10000)
markerline, stemlines, baseline = plt.stem(x, np.cos(x), '-.')
plt.setp(baseline, 'color', 'r', 'linewidth', 2)

plt.show()
```

**Comment by jklymak** [comment]
Are you sure `stem` is what you want for 10,000 data points?  You might like `fill_between` instead...

**Comment by Felix-neko** [comment]
Well, in MATLAB I do the same and then zom the region of interest (when the samples are high enough) to see the exact samples I need.

**Comment by anntzer** [comment]
See #7969.

**Comment by tacaswell** [comment]
@Felix-neko Please keep your comments G-rated and respectful.
