### ISSUE TITLE
Possible bug in tight_layout?

### ISSUE THREAD

**Issue by fperez** [matplotlib/matplotlib#9567]
### Bug report

**Bug summary**

Calls for tight_layout can produce figure titles that overlap with the input.

[This notebook](https://gist.github.com/anonymous/44b1d44637614fc7c677e4daa53f063d) has a full replication of the problem.

**System info**

{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/fperez/usr/conda/envs/s159/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/fperez/usr/conda/envs/s159/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) \n'
                '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'}

These were installed from default conda channels.

**Comment by jklymak** [comment]
Thanks for the bug report!

`tight_layout` doesn't work w/ suptitle.  #5355  See also #9082 which is a tight_layout alternative and does handle this case.  `tight_layout` could also prob be made to work.  

I'm going to close as a duplicate, but it is is a definite bug.

**Comment by fperez** [comment]
Ack, thx! It would indeed be niced if `tight_layout` worked in a few more cases, though I understand it's probably impossible/very hard to make it get every last corner case right.

But I've been teaching it to my students as a great one-stop shop for layout adjustments, so I was a bit bummed to see it fail when using `suptitle`.

As usual, thanks for the quick and informative response!
