### ISSUE TITLE
FancyArrowPatch -|> with patheffects - unable to change linestyle of arrowhead

### ISSUE THREAD

**Issue by strogdon** [matplotlib/matplotlib#9579]
### Bug report

**Bug summary**

The code from https://sourceforge.net/p/matplotlib/mailman/attachment/CAG%3DuJ%2Bnw2dE05P9TOXTz_zp-mGP3cY801vMH7yt6vgP9_WzU8w%40mail.gmail.com/1/ works with version 1.5.3, i.e. a `dashed` arrow can be drawn with a `solid` arrowhead using `matplotlib.patheffects.Stroke`. This no longer works with version 2.0.2. I haven't tried version 2.1.0

**Code for reproduction**
For the code to run replace

```python
class ConditionalStroke(pe._Base):
```
with
```python
class ConditionalStroke(pe.RendererBase):
```

**Actual outcome**

With `matplotlib-2.0.2` the code does not fail but the arrowhead portion of the arrow is drawn with the `dashed` linestyle. With `matplotlib-1.5.3` if I replace `pe.Stroke(linestyle="solid")` in the code with `pe.Stroke(linestyle="junk")` I get

```
valueError: Unrecognized linestyle: junk
```
However, with the same replacement and running the code with `matplotlib-2.0.2` there is no `valueError` and the arrow and arrowhead are drawn with the `dashed` linestyle.

**Expected outcome**
The desired result is to have an arrow with a `dashed` linestyle but with a `solid` arrowhead. It appears that `matplotlib.patheffects.Stoke` in version 2.0.2 is aware of the `linestyle` parameter but does not do anything with it. Pehaps with the newer matplotlib the intent is to not allow the `linestyle` to be changed via `patheffects`? If so, then perhaps an error should be thrown when the `linestyle` parameter in used. This is a feature that has been used in `Sage` (https://trac.sagemath.org/ticket/23696).

**Matplotlib version**

  * Operating system: Gentoo
  * Matplotlib version: 1.5.3 & 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt4Agg & TkAgg
  * Python version: 2.7.12
  * Jupyter version (if applicable):
  * Other libraries: 
Matplotlib was installed from source.

**Comment by dopplershift** [comment]
For reference, here's the code in question, with the aforementioned change:
```python
from matplotlib.pyplot import figure, show
from matplotlib.patches import FancyArrowPatch

import matplotlib.patheffects as pe

fig = figure()
ax = fig.add_subplot(111,autoscale_on=False,)
p = FancyArrowPatch((0,0), (1,1),
arrowstyle='-|>,head_width=8,head_length=16',lw=3,fc='k',ec='k',linestyle='dashed')
ax.add_patch(p)

class CheckNthSubPath(object):
    def __init__(self, patch, n):
        """
        creates an callable object that returns True if the provided
        path is the n-th path from the patch.
        """
        self._patch = patch
        self._n = n

    def get_paths(self, renderer):
        self._patch.set_dpi_cor(renderer.points_to_pixels(1.))
        paths, fillables = self._patch.get_path_in_displaycoord()
        return paths

    def __call__(self, renderer, gc, tpath, affine, rgbFace):

        path = self.get_paths(renderer)[self._n]
        vert1, code1 = path.vertices, path.codes
        import numpy as np

        if np.all(vert1 == tpath.vertices) and np.all(code1 == tpath.codes):
            return True
        else:
            return False


class ConditionalStroke(pe.RendererBase):

    def __init__(self, condition_func, pe_list):
        """
        path effect that is only applied when the condition_func
        returns True.
        """
        super(ConditionalStroke, self).__init__()
        self._pe_list = pe_list
        self._condition_func = condition_func

    def draw_path(self, renderer, gc, tpath, affine, rgbFace):

        if self._condition_func(renderer, gc, tpath, affine, rgbFace):
            for pe1 in self._pe_list:
                pe1.draw_path(renderer, gc, tpath, affine, rgbFace)


pe1 = ConditionalStroke(CheckNthSubPath(p, 0),
                        [pe.Stroke()])
pe2 = ConditionalStroke(CheckNthSubPath(p, 1),
                        [pe.Stroke(linestyle="solid")])

p.set_path_effects([pe1, pe2])

show()
```

**Comment by strogdon** [comment]
It appears the change happened somewhere between versions `2.0.0b4` and `2.0.0.rc1`. Some work was done on `patches.py` between those versions.

**Comment by strogdon** [comment]
Oddly, this the first commit that prevents drawing a `dashed` linestyle arrow with a `solid` arrowhead:
```
daa9394f4ef8a8514873037430e953f785170d60 is the first bad commit
commit daa9394f4ef8a8514873037430e953f785170d60
Author: Thomas A Caswell <tcaswell@gmail.com>
Date:   Tue Oct 11 16:41:33 2016 -0400

    FIX: fix FancyArrowPatch linestyle
    
    oversight when adding the dash-scaling
    
    Closes #7224

:040000 040000 a03f19c8b4314d8ca90561eaf71bbe5905580575 85eba89996d00a3da7b5625798fe351c6e6013e2 M      lib
```
I can provide figures if needed.

**Comment by strogdon** [comment]
Correction above. The commit did correct what was indicated. However, after that commit the arrowhead cannot be drawn with a `solid` linetype.

**Comment by tacaswell** [comment]
xref: daa9394f4ef8a8514873037430e953f785170d60

As part of scaled dashes we moved away from 'linestyle' being primary and towards 'dashes' being primary.  

The `_update_gc` on `AbstractPathEffects` should probably handle the re-mapping which is currently done in ex `Line2D.set_linestyle`.

The following works on currentish master, 2.0.2 and 1.5.3

```python

pe1 = ConditionalStroke(CheckNthSubPath(p, 0),
                        [pe.Stroke()])
pe2 = ConditionalStroke(CheckNthSubPath(p, 1),
                        [pe.Stroke(dashes={'dash_offset': 0, 'dash_list': None})])

p.set_path_effects([pe1, pe2])

show()
```

attn @anntzer

**Comment by anntzer** [comment]
I added the deprecation warning to set_linestyle, but AFAICT that was after the switch to dashes.  I think the best thing is just to clarify the deprecation warning message to refer to set_dashes instead?  Not sure if there's much else to do.

**Comment by strogdon** [comment]
Thanks. I suspected something like this but didn't really know where to look.

**Comment by anntzer** [comment]
@tacaswell's patch seems to be the required workaround here.
