### ISSUE TITLE
Broken legend auto-position with step*-type histograms

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#9580]
### Bug report

**Bug summary**

Automatic placing of legend seems to be not working with histograms of type `step*`. If I am correct, this is a new entry in the long list of current issues with legend ^^.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

hist_types = ('bar', 'barstacked', 'step', 'stepfilled')

fig, axs = plt.subplots(nrows=len(hist_types), num="test")    
for ax, ht in zip(axs.flat, hist_types):
    ax.set_title(ht)
    ax.hist([0] + 5*[9], bins=range(10), label=f"This is a label", histtype=ht)               
    ax.legend(loc="best")

fig.tight_layout()
#fig.savefig(fig.get_label() + ".png")
```

**Actual outcome**

Matplotlib 2.1

![test](https://user-images.githubusercontent.com/17270724/32027748-94a8a666-b99f-11e7-99d2-547a51ed6142.png)

**Expected outcome**

The same auto-position of the legend on each subplot, i.e. *upper left*, whatever is the histogram style.

**Matplotlib version**

  * Operating system: GNU/Linux (Fedora 26)
  * Matplotlib version: 2.1 from conda (also test “successfully” with master)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.3 from conda
  * Jupyter version (if applicable): X
  * Other libraries:  X

*FWIW, I tried the above snippet on Matplotlib 1.5.0 and the result is similar.*

**Edit:** tweaked a bit the snippet to be Matplotlib v1.5.x-compliant.

**Comment by anntzer** [comment]
This is because bar-type histograms returns a list of rectangles, so the auto legend locator can find where to put the legend to overlap with as few of them as possible.  On the other hand, step-type histograms return a single polygon (filled or unfilled) that includes all the drawn bars, and there is no code implemented (I think) to compute the intersection of a polygon with a rectangle; so instead legend() uses the bounding box of the polygon.  But as you can see, in your case, the bounding box essentially covers the entire axes, so all positions are equally bad from the POV of the autolocator.
In this specific case we could change the polygon to see how many vertices of the polygon are overlapping with the legend, but that sounds quite specific and brittle.

**Comment by afvincent** [comment]
@anntzer Thanks for the explanations, that's interesting :).

**Comment by afvincent** [comment]
@jklymak Dummy question, but just checking that I got it right: this issue will still be there once the layer manager from #9082 will become active, isn't it?

**Comment by jklymak** [comment]
Thats right, #9082 only deals with the bounding boxes of the axes objects, including ax.legend() if it overspills the spines.  But it doesn't move any objects around *inside* an axes.  It just moves axes around so they fit and line up properly.

**Comment by afvincent** [comment]
I am likely something very genuine, but I guess that somebody has to do so 🐑... *When trying to “autolocate” the legend, how dumb will it be to simply take the “edge line” of the patches instead of their bounding box (for example in [`legend._auto_legend_data`](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/legend.py#L700))?*

By “edge line,” I mean the line made out of the vertices of a patch. I imagine the performance not to be significantly worse if there are not too many vertices (not worse that having lines with as much points). And one could always set an arbitrary (hard-coded?) limit for the allowed number of vertices if one is afraid of pathologic patches with thousands of vertices (e.g. an histogram with thousands of bins and of "step" or "stepfilled" type).

**Comment by jklymak** [comment]
I think there is a `contains_points` method in path?  Could you just check the four vertices of the legend?

**Comment by jklymak** [comment]
... or, I guess you'd want more than just the vertices, but some over-sampled list of points that denote the legend box?

**Comment by afvincent** [comment]
From my viewpoint, the problem is not the legend box, but more relying on the bounding box of the histogram patch when it is significantly not convex.

**Comment by jklymak** [comment]
Right, but you can get the path of the histogram polygons (which will be convex and closed at the bottom if I'm not mistaken) and test if any of the legend edges are inside the path.

**Comment by afvincent** [comment]
Well rather than “convex” I should have said “covering way less area than their bounding box” ^^...

**Comment by afvincent** [comment]
My naive idea was just to try leveraging this [part](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/legend.py#L926) of the “legend autoplacing” function by using the path of non-rectangle patches instead of their bboxes. For example by altering this [part](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/legend.py#L736) of the function that provides the bboxes, paths, vertices, etc.

**Comment by jklymak** [comment]
Looks good!

**Comment by afvincent** [comment]
So for what it worth, with this small change
```patch
From e79499f3ac11aca88416f458c53cd1e68807e8b6 Mon Sep 17 00:00:00 2001
From: "Adrien F. Vincent" <vincent.adrien@gmail.com>
Date: Thu, 26 Oct 2017 17:29:38 -0700
Subject: [PATCH] use path rather than bbox for non rectangular patches

---
 lib/matplotlib/legend.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/lib/matplotlib/legend.py b/lib/matplotlib/legend.py
index 214d110fd..693dfb0f2 100644
--- a/lib/matplotlib/legend.py
+++ b/lib/matplotlib/legend.py
@@ -733,7 +733,8 @@ class Legend(Artist):
                 bboxes.append(handle.get_bbox().transformed(transform))
             else:
                 transform = handle.get_transform()
-                bboxes.append(handle.get_path().get_extents(transform))
+                tpath = transform.transform_path(handle.get_path())
+                lines.append(tpath)
 
         for handle in ax.collections:
             transform, transOffset, hoffsets, paths = handle._prepare_points()
-- 
2.13.6


```
one get
![with_cleverer_auto_legend](https://user-images.githubusercontent.com/17270724/32082914-cc71411e-ba73-11e7-8d6d-1dccf0b6c836.png)

:)


So I guess it would be interesting to benchmark it a bit more to see if it breaks anything or significantly harm the performance.

**Comment by jklymak** [comment]
What happens if the first histogram also goes up to 5?  i.e. the vertexes are above where the top of the legend box would go? 

I don't think this legend function is particularly a speed demon in the first place is it?  I don't think folks who want speed should be relying on autolayout features...

**Comment by afvincent** [comment]
@jklymak My performance “concern” is mostly due to #8108. For your other question, I am investigating a bit but I guess it should land in the upper center of the axes.

**Comment by jklymak** [comment]
Well, I won't comment on the wisdom of auto layout as the default...

**Comment by afvincent** [comment]
FWIW, I tried the following example
```python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

# Dummy data:
# Two sets of ramdom samples with peaks on both sides,
# the left one being lower than the right one
prng = np.random.RandomState(456852)
N = 10000
all_data = []
for _ in range(2):
    data = prng.random_sample(size=N)
    data[data < 0.05] = 0.05
    data[data > 0.9] = 0.95
    all_data.append(data)


# Function under test
def test(data, histtype):

    try:
        samples_ref = data[0]
    except TypeError:
        samples_ref = data
    N_bins = len(samples_ref)//10
    bins = np.linspace(
                samples_ref.min() - 0.05, samples_ref.max() + 0.05, N_bins)

    fig, ax = plt.subplots(num="test", clear=True)
    cnts, bs, ps = ax.hist(data, bins=bins, label=f"This is a label",
                           histtype=histtype)

    ax.legend()

    #fig.canvas.draw()
    #plt.show()
    return ps

# Hist with ~ 1000 bins for profiling
test(all_data, "step")
```
and “profiled” it with the Spyder profiler (which relies on cProfile if I am right): the time spent in `legend` does not seem to change that much (~ 10% of 1.5 ms while the total duration is dozens of milliseconds if I am able to read correctly the profiling output).

I'll try to open a proper PR soon.

**Comment by anntzer** [comment]
Apparently it wasn't that hard :-)
I still plan to try the method I proposed above (grab the raster buffer) at some point :-)

**Comment by afvincent** [comment]
@anntzer Still have to see how many tests it breaks, etc. but indeed I was not expecting it to potentially be a 2 line-fix ^^... It is still not perfect though, in the sense that you can have situations where it seems like the legend is placed *just* above a bar (nevertheless without overlap) while there is really plenty of space above other bars. I guess it is because the auto-placing algorithmn is picking the first reasonable position it finds. But well, making this better might really transform this into an optimization problem...

**Comment by jklymak** [comment]
... or just make a fake legend bbox that is pad bigger than the real one.
