### ISSUE TITLE
pixel sizes uneven with ImageGrid

### ISSUE THREAD

**Issue by damca** [matplotlib/matplotlib#9581]
### Bug report

**Bug summary**

Plotting with an ImageGrid can result in pixel sizes that are uneven. This seems to happen with larger images. For larger grids and images the problem is worse. This is the simplest example I could come up with to reproduce the problem.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid
import numpy as np


def get_demo_image(n=10):
    # make n x n horizontal gradient image
    r = np.linspace(-3, 3, n)[np.newaxis, :]
    z = np.concatenate([r]*n, axis=0)
    return z


def enlarge(z, n=10):
    # magnify by a factor of n
    r = np.concatenate([z]*10, axis=1)
    i = np.concatenate([r]*10, axis=0)
    return i

def make_fig(big=False):
    fig = plt.figure(1, (2, 2))  # default dpi=100, so 200x200 pixels
    grid = ImageGrid(fig, 111,
                    nrows_ncols=(1, 1),
                    axes_pad=0.1,
                    )
    z = get_demo_image(n=10)
    if big:
        # make 100 x 100
        z = enlarge(z, n=10)
    for a in grid:
        a.imshow(z, interpolation="none")
        a.axis('off')
    fig.savefig('example_{}'.format(big))
    plt.close('all')

make_fig(big=False) # pixel columns look even
make_fig(big=True)  # there are uneven pixel columns

```

**Actual outcome**

The smaller image results in even pixel sizes. However, if you open the larger image and zoom in you will find uneven pixel sizes. Most pixels will have a single width, but some are double width.

Small:
![example_false](https://user-images.githubusercontent.com/16568850/32031723-bbc75bf8-b9b7-11e7-9465-d9e1c8a4b373.png)

Large (zoomed in):

<img width="277" alt="example_true" src="https://user-images.githubusercontent.com/16568850/32031820-50e283ac-b9b8-11e7-9310-79285d8b84ab.png">

**Expected outcome**

I would expect ImageGrid to maintain even pixel sizes. Curiously, if one displays the image with plt.show() and zooms in the pixels maintain even size. But they won't remain so upon saving.

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 2.0.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.2
  * Jupyter version (if applicable):
  * Other libraries: 

Installed width conda

**Comment by jklymak** [comment]
Instead of the `ImageGrid` line try:  

```python
grid = [fig.add_axes([0., 0., 1., 1.])]
```

Your pixels and the png pixels will be aligned.  

This has nothing to do w/ ImageGrid, its just that your axis wasn't an even multiple number of pixels wide (your figure was).  I'm closing unless you really think there is a bug...

**Comment by damca** [comment]
For me `grid = [fig.add_axes([0., 0., 1., 1.])]` by itself results in this (zoomed in):

<img width="194" alt="screen shot 2017-10-26 at 9 24 39 am" src="https://user-images.githubusercontent.com/16568850/32064977-458ddc54-ba30-11e7-82bb-2670af8bb19b.png">

However you are correct in that making the axis have an even multiple of needed pixels resolves the issue:

```python
def enlarge(z, n=10):
    # magnify by a factor of n
    r = np.concatenate([z]*n, axis=1)
    i = np.concatenate([r]*n, axis=0)
    return i

def make_fig(num=10, size=(2,2), factor=2):
    z = get_demo_image(n=10)  # demo image
    z = enlarge(z, n=num)  # n=10 makes 100x100
    dpi = z.shape[0] / size[0] * factor  # calculate appropriate dpi
    fig = plt.figure(1, size, dpi=dpi)
    ax = fig.add_axes([0., 0., 1., 1.])
    ax.imshow(z, interpolation="none")
    ax.axis('off')
    fig.savefig('example_{}'.format(num), dpi=dpi)
    plt.close('all')

make_fig(num=1) # pixel columns look even
make_fig(num=10)  # there are uneven pixel columns

```

It seems to me that if the axis has more pixels than the image then the image should be evenly upsampled (according to the interpolation given in imshow) to fit the axis rather than upsampling some rows and columns and not others.  Respecting the `rect=[0., 0., 1., 1.]` and fig size would seem tricky. Maybe an option to have either a flexible dpi or a flexible fig size to allow optimal upsampling would be nice. But I agree the behavior is not a "bug", just a little bit unexpected.

**Comment by jklymak** [comment]
You set `inteprolation="none"`.  Not sure what you mean by "evenly upsampled".  You have four values: 1, 2, 3, 4 and six slots to put them in.  If you say `interpolation="none"` then it just chooses the nearest and gives you 1, 2, 2, 3, 4, 4  The other option is to allow interpolation, in which case you'd get [1., 1.6, 2.2, 2.8, 3.4, 4.0]

**Comment by tacaswell** [comment]
When you are using the interactive zoom, the image gets resampled on every draw so it looks even.  When you save the whole figure and then zoom in on the static figure it (obviously) can not resample.  At some level, this is just interference between the input data and the pixels at the bottom.

`Figure.figimage` (http://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html?highlight=figimage#matplotlib.figure.Figure.figimage) with the resize kwarg will do what you want for a single image.

If you wanted to do this more generally, you would very quickly run into messy interactions between multiple images on multiple axes at different resolution.  In general there is no ideal size / dpi to always make the logical pixels of the image line up with the real pixels of the rasterization.

If what you want really is a single array color mapped (no axis labels, no text, no other artists, etc) and saved to disk I would do something like

```python
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
cm = plt.get_cmap()
norm = mcolors.Normalize()
rgba = cm(norm(input_data))
```

and then use your image file writing library of choice (`pillow`, `tifffile`, `imageio`, `skimage`, ...) to save the RGBA data to disk which solve the re-sampling problem by simply not do it ;)

**Comment by damca** [comment]
@jklymak For an interpolation="none" I was expecting "nearest neighbor" upsampling, something like this:

<img width="198" alt="screen shot 2017-10-26 at 1 41 43 pm" src="https://user-images.githubusercontent.com/16568850/32076033-74c9341e-ba53-11e7-8185-cd48e43958ed.png">

But of course there is the limitation of having the number of pixels square upon each upsampling and it would in practice require either flexible figsize or flexible dpi.

@tacaswell Thanks for the insight about Figure.figimage I'll have to look at that more closely. And unfortunately I am hooked to making highly annotated images with text, labels, arrows, etc.
