### ISSUE TITLE
idle_event is invoked only once

### ISSUE THREAD

**Issue by bgamari** [matplotlib/matplotlib#959]
FigureCanvasBase.idle_event doesn't return anything, meaning it is only called once under the gtk backend. This leads to the apparent breakage of which means examples/idle_and_timeout.py is broken.

All in all it seems that the idle_event callback is incompletely implemented at best. It's quite unclear whether it's even a good idea to pipe this event through CallbackRegistry, since we only really want the backend to register it (with, e.g., gobject.idle_add) if there is a callback to be called. Otherwise we are just creating unnecessary work by executing a stub function.

**Comment by story645** [comment]
The docs say idle_event is deprecated (http://matplotlib.org/examples/event_handling/idle_and_timeout.html), so is the issue this is referring to still exist?

**Comment by tacaswell** [comment]
Closing as we have fully deprecated idle_event as of #8454.
