### ISSUE TITLE
Scientific format digits on figure

### ISSUE THREAD

**Issue by ardeal** [matplotlib/matplotlib#9590]
Hi,

If I put the mouse on the figure, x and y axis are displayed on the left-bottom corner of the figure.
but the x axis is displayed as scientific notation, I want it to be displayed as decimal notation.

how to make x axis or y axis values displayed as decimal notation on the left-bottom corner?

**Comment by jklymak** [comment]
Hi, please subscribe to https://mail.python.org/mailman/listinfo/matplotlib-users or try stackexchange for user support...

**Comment by ardeal** [comment]
Hi, 
I have already filled my email address to subscribe Matplotlib-users. What should I do next for my question?
where can I find the answer?

**Comment by efiring** [comment]
You need to send your question to Matplotlib-users if you have not already done so.  A satisfactory answer is not guaranteed, of course.
Your original question is a good one; you are looking for what is, as far as I can see, a feature that is almost impossible to find in the documentation without already having a pretty good idea of where to look and what to look for--and even then, it's easy to miss it.  See http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.format_xdata.html?highlight=format_xdata#matplotlib.axes.Axes.format_xdata and the reference to `fmt_xdata` in http://matplotlib.org/gallery/recipes/common_date_problems.html?highlight=fmt_xdata

**Comment by ardeal** [comment]
![default](https://user-images.githubusercontent.com/6227348/32091758-2749cf2a-bb28-11e7-83b3-2e76bb3a138d.png)

That is the left-bottom corner of the figure, I would like to make the scientific notation to decimal notation.

**Comment by ardeal** [comment]
![default](https://user-images.githubusercontent.com/6227348/32092087-9017a0da-bb29-11e7-9fad-c15ce235636f.png)
