### ISSUE TITLE
Scientific notation digits on figure

### ISSUE THREAD

**Issue by ardeal** [matplotlib/matplotlib#9592]
Hi,

If I put the mouse on the figure, x and y axis are displayed on the left-bottom corner of the figure.
but the x axis is displayed as scientific notation, I want it to be displayed as decimal notation.

how to make x axis or y axis values displayed as decimal notation on the left-bottom corner?

I have already followed  Jklymak's message to subscribe Matplotlib-users. I have no idea about how to get the answer.

Thanks!

**Comment by efiring** [comment]
You need to send your question to matplotlib-users@python.org.  You, as a subscriber, will then receive any answers that are posted.
