### ISSUE TITLE
Attempt to create a dynamically changing plot in console and notebook

### ISSUE THREAD

**Issue by dsblank** [matplotlib/matplotlib#9606]
### Bug report

**Bug summary**

Trying to have a dynamic plot that gets created and iteratively updated in a single function, both in the notebook, and in the console:

```
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
```
Other software versions:

* notebook (5.1.0)
* ipywidgets (7.0.0)
* jupyter (1.0.0)
* jupyter-client (5.1.0)
* jupyter-console (5.1.0)
* jupyter-core (4.3.0)

**Code for reproduction**

In the notebook, this is preceded with `%matplotlib notebook`. Testing on the Mac for the console part. All one cell.

```python
import matplotlib.pyplot as plt
import numpy as np
import time

fig = plt.figure()
fig.show()

for j in range(10):            
    plt.plot(range(0, j), [1/(i+1) for i in range(0, j)])
    fig.canvas.draw()
    time.sleep(.05)      
```

**Actual outcome**

1. in the notebook, the figure size changes (initial is small, final fills area)
2. in the console, the plot doesn't show up until all done plotting

**Matplotlib version**

  * Operating system: MacOSX, Darwin 16.7
  * Matplotlib version: matplotlib (2.0.2)
  * Matplotlib backend: MacOSX
  * Python version: 3.6
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: (see above), anaconda install

**Comment by jhamrick** [comment]
> in the notebook, the figure size changes (initial is small, final fills area)

I just ran into this bug as well. During the loop, the figure is small, e.g.:

![image](https://user-images.githubusercontent.com/83444/32147664-d868ec4e-bce2-11e7-9172-9d3c6dbced50.png)

when the loop finishes, the figure fills the whole area, e.g.:

![image](https://user-images.githubusercontent.com/83444/32147667-e32ed274-bce2-11e7-8931-6f039ef75b1b.png)

This was not a problem in matplotlib 1.5.3 (i.e. the plot always filled the whole area), and seems to have been introduced with the release of 2.0.0.

**Comment by tacaswell** [comment]
The issue is resizing is the high-dpi support and a race condition of when the front end JS resizes to account for it and when the backend gets notified of it.

**Comment by dsblank** [comment]
Note that is just one of the issues; the other is that it doesn't show in the console at all, until the code is finished.

**Comment by tacaswell** [comment]
If you add a `show()` it should work in the console and I don't _think_ it will break in the notebook.

**Comment by dsblank** [comment]
Adding fig.show() does allow it to work on my Linux console, but not on the MacOSX backend.

However, this works on the MacOSX backend, but not in the notebook because 

1. this issue: https://github.com/matplotlib/matplotlib/issues/9729
2. it would probably still have the "race condition" size problem

Maybe I'm going about this all wrong? Perhaps there is a more standard method of updating a plot on all GUI backends?

**Comment by dsblank** [comment]
One problem left: the tiny version, followed by the updated, full-frame version.

I don't believe that this is a "race condition" but rather a design issue. It appears that fig.show() is sending information to the backend, but (if done all in one cell) the program is running, and can't respond to it. 

For example, if a time.sleep() is placed after fig.show() in this updated example:

```python
import matplotlib.pyplot as plt

fig = plt.figure()
fig.show()
sleep.time(5) ### added time here!
for j in range(10):            
    plt.plot(range(0, j), [1/(i+1) for i in range(0, j)])
    plt.pause(.05)
```
The small version shows, followed by the full-size version as @jhamrick showed above. However, if split into two cells (at the inserted time), then t works as desired (size is correct).

I don't know how to debug this one.

**Comment by lucainnocenti** [comment]
I think this is the same as https://github.com/matplotlib/jupyter-matplotlib/issues/17

**Comment by streamnsight** [comment]
if found this that worked for me.
https://stackoverflow.com/questions/21360361/how-to-dynamically-update-a-plot-in-a-loop-in-ipython-notebook-within-one-cell

**Comment by komorihi** [comment]
Is there no solution to this problem?

**Comment by thomasaarholt** [comment]
Just to clarify some behaviour:

This same issue applies to the ipympl package.

The following does not work
```python
# all in one cell
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import time

fig = plt.figure()
for j in range(10):       
    plt.plot(range(0, j), [1/(i+1) for i in range(0, j)])
    fig.canvas.draw()
    time.sleep(.1)
```
But if one separates it into two cells, so that the plot is shown before the loop:

```python
# Cell 1
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import time
```

```python
# Cell 2
fig = plt.figure()
for j in range(10):       
    plt.plot(range(0, j), [1/(i+1) for i in range(0, j)])
    fig.canvas.draw()
    time.sleep(.1)
```
Then it works nicely. This is, however, still an issue, as one cannot create the figure and start loop plotting in the same cell.

**Comment by patricknraanes** [comment]
I copied your example to a corresponding question on stackoverflow @thomasaarholt 
https://stackoverflow.com/a/66399257

Unfortunately, I have a lot of plot functionality deep within a function, so it would be difficult to split it. Does anyone have another way?

**Comment by thomasaarholt** [comment]
@patricknraanes can you just `fig, ax = plt.subplots()` in one cell, and then use `ax = plt.gca()` or `fig = plt.gcf()` in your function?

**Comment by patricknraanes** [comment]
Unfortunately no, because the function is mainly about running a relatively heavy/slow computational process.

It also creates a (somewhat unpredictable) number of figures that are updated along with the process.

**Comment by thomasaarholt** [comment]
Gotcha. You can follow the issue over at matplotlib/ipympl#290. Feel free to bump the thread to see if there have been any developments.
