### ISSUE TITLE
matplotlib color not equal to the setting

### ISSUE THREAD

**Issue by qiliux** [matplotlib/matplotlib#9609]
**matplotlib usage**

The saved figure png file axis tick color not equal to the setting color.l
**Code for reproduction**
```python
    mpl.rcParams['axes.edgecolor'] = '#000080'
    mpl.rcParams['xtick.color'] = '#000080'
    mpl.rcParams['ytick.color'] = '#000080'
```

**Actual outcome**
```python
from scipy import misc
lbl = misc.imread('/home/qiliux/data/datasets/charts/ans_data_onlybar_little/bar_nogrid_0.png')
```

```
The ticks color in png is `#000066` not `#000080`.
```

**Expected outcome**
```
I want ticks color in png is `#000080`.  
```
**question**
1. How can i change this behaviour?
2. How can i stop any algorithm to render color edge. I draw a line with a color. I don't want it's begin and end has other gradient color info. Though it's good for viewing with adding begin and end gradient color, i don't need them at all.

**Comment by tacaswell** [comment]
How wide are your ticks and how are you measuring?  I suspect that this is the anti-aliasing of the renderer kicking in.   The pixel you are testing is not 100% covered by the tick so the color is de-saturated a bit.

**Comment by qiliux** [comment]
I think you are right. It does some de-saturated
