### ISSUE TITLE
Unexpected behaviour with string input to .plot and .fill_between

### ISSUE THREAD

**Issue by hoblins** [matplotlib/matplotlib#9611]
### Bug report

**Bug summary**

In matplotlib 2.0.2 .plot accepted also strings as an input for 'x' and 'y'. In matplotlib 2.1.0 this results in unexpected behaviour, see pictures below.
With `plot.plot(1, float(var), '^', color='black')` the result is the same as for 2.0.2.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, plot = plt.subplots()

var = '{:.1f}'.format(3.14159)

xNew = (0.5, 1, 1.5)
plot.fill_between(xNew, 2.5, 3.5)
plot.plot(1, var, 'v', color='black')

fig.show()
```

**Actual outcome**
![figure_2 1 0](https://user-images.githubusercontent.com/11378643/32144282-c452f30c-bcb6-11e7-8e4b-e33b960659c1.png)

**Expected outcome**
![figure_2 0 2](https://user-images.githubusercontent.com/11378643/32144277-b8f42616-bcb6-11e7-9cd7-5b1ec1c482bf.png)

**Matplotlib version**

  * Operating system: Ubuntu 17.10
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.3
  * Jupyter version (if applicable):
  * Other libraries: 

matplotlib was installed with pip.

**Comment by dstansby** [comment]
I'm guessing the string is being interpreted as a category - @story645?

**Comment by anntzer** [comment]
It is indeed interpreted as a category.  Despite the various issues I've raised with the categorical code, I definitely consider that we should not accept strings when a float is meant, so @hoblins you need to make sure to pass a float.
In favor of closing the issue...

**Comment by tacaswell** [comment]
Indeed, that we ever accepted floats as strings was a weird artifact of how some of the unit checking code worked and a cast through numpy.  At the time we did not think anyone would intentionally be using this.  

Given that this have come up twice now, I think we need to add an API changes note.

**Comment by hoblins** [comment]
Thank you guys to seize on that. Just wanted to share that "issue". It happened more or less by accident using just one variable for labelling and data plotting.
Maybe an error could be raised for wrong input parameters?

**Comment by tacaswell** [comment]
@hoblins  It probably should have _used to_ raise an exception, but we now treat strings as categorical data (see http://matplotlib.org/users/whats_new.html#string-categorical-values ).
