### ISSUE TITLE
contour_doc not rendered properly

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#9642]
See http://matplotlib.org/devdocs/api/contour_api.html?highlight=quadcontourset#matplotlib.contour.QuadContourSet.contour_doc

**Comment by anntzer** [comment]
that just needs to become a private variable, it gets interpolated into other docstrings.

**Comment by dstansby** [comment]
It's linked to directly in the line above from the docstring of `QuadContourSet` though - does that link need moving somewhere else?

**Comment by dstansby** [comment]
Closed by #10233
