### ISSUE TITLE
Spelling error in gallery (agg_oo_sgskip.html)

### ISSUE THREAD

**Issue by roysmith** [matplotlib/matplotlib#9663]
In https://matplotlib.org/gallery/api/agg_oo_sgskip.html#sphx-glr-gallery-api-agg-oo-sgskip-py, "instanciating" should be spelled "instantiating".

**Comment by tacaswell** [comment]
@roysmith Thanks for reporting this!  The source is at https://github.com/matplotlib/matplotlib/blob/master/examples/api/agg_oo_sgskip.py  Would you mind opening a pull request to fix this?  (You can even do this through the github website!)

**Comment by roysmith** [comment]
https://github.com/matplotlib/matplotlib/pull/9665 <https://github.com/matplotlib/matplotlib/pull/9665>
