### ISSUE TITLE
Change in behavior of axis.tick_left() with shared axes from 2.0 to 2.1

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#9664]
### Bug report

**Bug summary**

Between 2.0 and 2.1, using `tick_left()` on the y axis of an inner panel of a plot with shared y axes makes the tips reappear.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
f, axes = plt.subplots(1, 2, sharey=True)
axes[1].yaxis.tick_left()
```

**Actual outcome**

On matplotlib 2.1:

![mpl2 1](https://user-images.githubusercontent.com/315810/32330306-11d364a2-bfb6-11e7-8b68-60d1c5cc9114.png)

**Expected outcome**

On matplotlib 2.0:

![mpl2 0](https://user-images.githubusercontent.com/315810/32330301-0d1cd02e-bfb6-11e7-982f-f5e1b99f06cf.png)

**Matplotlib version**
  * Operating system: macOS
  * Matplotlib version: 2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6
  * Jupyter version (if applicable): NA
  * Other libraries: NA

Matplotlib installed via conda.

**Comment by mwaskom** [comment]
(This behavior is not restricted to `tick_left`; it's also true of `tick_bottom` when the x axes are shared).

**Comment by jklymak** [comment]
I think 2348584 does the right thing in `sharey`  (`yaxis.set_tick_params(labelleft=False)`) .  What happened before with `sharey` is that the tick labels were still there but were made invisible. 

The problem with `yaxis.ticks_left()` is that it does two things: puts the ticks on the left *and* says to label them (`yaxis.set_tick_params(labelleft=True)`).  They didn't appear to be labeled before because `sharey` just made them invisible, but they were virtually there.  

For now, I think a workaround is:

```python
axes[1].yaxis.set_tick_params(left=True)
```

and maybe the proper solution to the OPs issue is better documentation of `ticks_left()`?

**Comment by mwaskom** [comment]
This change causes some major problems for seaborn.FacetGrid. I can make changes going forward, but it's going to be an issue that is very difficult to work around for people who are updating asynchronously.

**Comment by jklymak** [comment]
I agree the API shouldn't change w/o notice.  

The question is do we want to change `ticks_left` to just do `set_tick_params(which='both', left=True, right=False)`? and leave the `labelRight` and `labelLeft` untouched?  That'd give you back the functionality you had before.  However, that would be an API change for people who (for whatever reason) expect `ticks_left` to redraw ticks that had been set with `labelleft=False`.

**Comment by jklymak** [comment]
@mwaskom Did you have the ability to try #9670 and make sure it works in general for you?

**Comment by mwaskom** [comment]
@jklymak No, I'm not set up to build matplotlib locally

**Comment by mwaskom** [comment]
Following up on this: I tried @jklymak's suggestion of using `ax.yaxis.set_tick_params`. However, I can't fully replicate what (e.g.) `ax.yaxis.tick_right` is doing because it's checking private attributes to know whether to set labelleft/labelright.

```python
        label = True
        if 'label1On' in self._major_tick_kw:
            label = (self._major_tick_kw['label1On']
                     or self._major_tick_kw['label2On'])
```

So I end up running right into the original problem in this thread.

Given that, if there's no public way to determine whether tick labels are on, I'd like to ask that you please maintain stability in the `tick_{left,right,bottom,top}` convenience methods.

Thanks.

**Comment by mwaskom** [comment]
> Given that, if there's no public way to determine whether tick labels are on, I'd like to ask that you please maintain stability in the tick_{left,right,bottom,top} convenience methods.

Actually I ended up needing to solve this problem for another reason, and it does turn out to possible (if a bit roundabout), so I retract this statement and request.
