### ISSUE TITLE
Make forward=True default consistent across size changing methods

### ISSUE THREAD

**Issue by jkjk822** [matplotlib/matplotlib#9669]
Some time ago, `forward=True` was made the default for `set_size_inches`: #4680 

However, this left [`set_figheight` and `set_figwidth`][1] with `forward=False` as the default. The original "it makes more sense" argument still applies here, but with the added (and perhaps more important) motivation of making all three methods consistent.

**For example:** A user changing the size will find their bounding box updated automatically, but when only changing the height or width, they will find the bounding box is not automatically updated. This is highly unintuitive.

[1]: https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.set_figheight

**Comment by jklymak** [comment]
Closed w #9715.  Thanks for the report!
