### ISSUE TITLE
Can I change default title location with matplotlibrc?

### ISSUE THREAD

**Issue by nickteff** [matplotlib/matplotlib#9682]
I am building my own style and would like to make the default title location left aligned, but have not figured out a way to do this with the matplotlibrc file.  Is this possible?  Thank you.

**Comment by ImportanceOfBeingErnest** [comment]
The simple answer is "No".
The matplotlib rc params have no option to change the title's alignment. 

You may use [the usual way of specifying the title's alignment](https://matplotlib.org/examples/pylab_examples/titles_demo.html) as

    

` plt.title('Left Title', loc='left') `

I guess one may see this as a feature request to add this possibility to the rcparams.

**Comment by nickteff** [comment]
I thought that might be the case, but thought I would ask.  Thank you for the follow-up.  Should I close this or leave it open?

**Comment by jklymak** [comment]
Work to do:

  - add a new rcparam
  - set rcParam default to "center"
  - change the default in `_axes.set_title()` to `loc=None`.  
  - add a bit of logic to fall back on rcParam if `loc=None`

**Comment by nickteff** [comment]
That sounds pretty straightforward, is this something a newcomer could give a stab at?

**Comment by jklymak** [comment]
Absolutely!  http://matplotlib.org/devel/index.html is a bit intimidating, but the hardest part is really getting a development version of matlab to run on your own machine.

**Comment by nickteff** [comment]
Or rather, Matplotlib???  Let me see what I just volunteered myself for and can I ask you for some guidance?  Or just keep question here in this issue?

**Comment by afvincent** [comment]
@nickteff The [gitter channel](https://gitter.im/matplotlib/matplotlib) might also be a place where to ask questions.

**Comment by jklymak** [comment]
Darn auto-correct ;-)

**Comment by jacob-aquino** [comment]
My colleagues and I are currently working on an implementation for this issue. We plan on completing it in a week or so.

**Comment by jklymak** [comment]
Closed by #13802 I think
