### ISSUE TITLE
gtk3agg not working with python 3.6.3 & cairocffi 1.10.0

### ISSUE THREAD

**Issue by AmitAronovitch** [matplotlib/matplotlib#9717]
Once I upgraded to Ubuntu 17.10, seems like #5793 came back to haunt us

Exactly as described by @anntzer on June,
Trying the gtk3agg backend, I now get the error
```
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```
with no traceback, and a blank window.

Ubuntu Artful (17.10), Python 3.6.3, python3-gi-cairo 3.24.1 (via ubuntu package manager)
In the virtualenv I have:
matplotlib 2.1.0, 
gi 3.24.1 (exposed from system package via symlinks)
cairocffi 1.10.0
(similar setup used to work fine with zesty packages (python-3.5, don't recall which python3-gi)).

The only workaround I found is removing cairocffi, and compiling latest pycairo from source (the packaged pycairo just does not work).

would appreciate tips on further info I can provide to debug this...

**Comment by fariza** [comment]
I just upgraded as well. I didn't have cairocffi installed and I got

```
NotImplementedError                       Traceback (most recent call last)
~/workspace/matplotlib/lib/matplotlib/backends/backend_gtk3agg.py in on_draw_event(self, widget, ctx)
     63             else:
     64                 image = cairo.ImageSurface.create_for_data(
---> 65                     buf, cairo.FORMAT_ARGB32, width, height)
     66             ctx.set_source_surface(image, x, y)
     67             ctx.paint()

NotImplementedError: Surface.create_for_data: Not Implemented yet.
```

After installing cairocffi everything works fine.
I am inclined in removing support for pycairo and forcing cairocffi for gtk3

**Comment by fariza** [comment]
Sorry for the confusion, what I mean is, why do we raise a warning
```
if six.PY3 and not HAS_CAIRO_CFFI:
    warnings.warn(
        "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
        "Try installing cairocffi.")
```
Instead of a simple `ImportError`?
We know it doesn't work, why can't we just remove it?

**Comment by fariza** [comment]
@AmitAronovitch In my case, using `cairocffi==0.8.0 cffi==1.11.2` (from pypi) works fine.
Your version of `cairocffi==1.10.0` sounds suspiciously similar to the pycairo version.
Are you sure you are using cairocffi and not pycairo?

**Comment by lazka** [comment]
The error indicates that pygobject can't find pycairo. You probably need to expose pycairo as well there (or use virtualenv --system-site-packages)

**Comment by anntzer** [comment]
@AmitAronovitch What's the packaged version of pycairo (that does not work)?  Here pycairo actually work with Py3 now...

**Comment by lazka** [comment]
Both [pycairo ](https://pypi.python.org/pypi/pycairo)and [pygobject ](https://pypi.python.org/pypi/PyGObject) are now on PyPI btw

**Comment by QuLogic** [comment]
Please re-open if you are still having issues with this.
