### ISSUE TITLE
Appveyor passing, even when tests are failing

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#9719]
e.g. this build passed, but 10 of the tests failed: https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.4300/job/24gagfqjoh67sx1b#L1972

**Comment by Kojoley** [comment]
The same happened in #9673

**Comment by anntzer** [comment]
(we probably don't want to make a release that actually doesn't pass the tests on windows, so I think this is release critical for 2.1.1...)

**Comment by dopplershift** [comment]
I'm going to re-open until the backport of #9773 is completed so that it doesn't get forgotten.

**Comment by tacaswell** [comment]
Closed by #9850
