### ISSUE TITLE
Legend not working when using a barstacked histogram

### ISSUE THREAD

**Issue by Khris777** [matplotlib/matplotlib#9728]
### Bug report

**Bug summary**

When plotting a histogram with the `barstacked` option no legend is created.

**Code for reproduction**

```python
import pandas as pd
import matplotlib.pyplot as mp

s1 = """A
1
1
2
2
2
2
3
3
3
3
4
4
5
5
5
4
4
1
2
4
5
"""

s2 = """B
5
5
5
4
4
1
2
4
5
"""

df1 = pd.read_csv(io.StringIO(s1))
df2 = pd.read_csv(io.StringIO(s2))

fig,ax = mp.subplots()
ax.hist([df1.A,df2.B],histtype="barstacked")
ax.legend()
fig.show()
```

**Expected outcome**

Just plot one histogram and a legend is visible as expected:

```
fig,ax = mp.subplots()
ax.hist(df1.A)
ax.legend()
fig.show()
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 2.1.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.3
  * Other libraries: Pandas 0.20.3, Numpy 1.13.3

Installed with conda in Anaconda 5.

**Comment by afvincent** [comment]
@Khris777 Thank you for the bug report :).

This may be related to how Matplotlib handles Pandas DataFrame, as
```python
import matplotlib.pyplot as plt

data1 = [0]*2 + [1]*8
data2 = [0]*8 + [1]*2

fig, ax = plt.subplots()
ax.hist([data1, data2], histtype="barstacked", label=["data 1", "data 2"])
ax.legend()
fig.show()
```
seems to be working fine¹ and produces
![mwe_no_pandas](https://user-images.githubusercontent.com/17270724/32707926-15239982-c7dc-11e7-945d-a8bab6c176ff.png)

¹ : at least on my machine (Fedora 26, Matplotlib 2.1 and Python 3.6 from conda)

**Comment by StefanBrand** [comment]
I can confirm that using `Series.values` makes the legend work, i.e. in your example:

```
fig,ax = mp.subplots()
ax.hist(df1.A.values)
ax.legend()
fig.show()
```

**Comment by oscargus** [comment]
@StefanBrand I believe the original problem is that the "label information" from the data frame is not passed on to the legend. So although it plots well, the request is that there should be a legend entry "A" in your code example. Which is not possible since `values` (and `to_numpy()` which both are used in the Matplotlib conversion) drops that information. So there should probably be some additional checking in most plot methods to pass that information as `label`.

**Comment by jklymak** [comment]
```python
ax.plot([df1.A,df2.B],histtype="barstacked", label=['A', 'B'])
```

works as expected.  We do not support getting the label automatically from the data, so far as I know.  I think this can be closed.
