### ISSUE TITLE
2.1.0 sdist does not allow building docs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9735]
See issue described at https://mail.python.org/pipermail//matplotlib-devel/2017-November/000895.html

This is due (at least) to an outdated MANIFEST.in (which is missing, for example, INSTALL.rst).

Instead of continually trying to keep MANIFEST.in in sync with the source tree (a never ending task...) I propose to make it include *everything*, but hook the sdist command to first check that we are in a clean git repo (and ask the user to run git clean -xdf if in a dirty repo, and accept not being able to build an sdist from a non-repo (not sure what the use case is tbh...)).

Or perhaps we can even completely subvert setup.py sdist to run `git archive $tag -o dist/matplotlib-$version.tgz --prefix matplotlib-$version.tgz` which actually appears to also creates a valid(?) sdist that pip can install (and we can set export-ignore if there are files we don't want to include, see https://git-scm.com/docs/git-archive#ATTRIBUTES).

**Comment by dopplershift** [comment]
Was this fixed by #9768 ?

**Comment by anntzer** [comment]
Someone needs to actually try it... (actually I think one of the docs build should try to build everything from a sdist).
