### ISSUE TITLE
doc inconsistency: definition of "aspect"

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#9739]
https://matplotlib.org/2.0.1/api/pyplot_api.html#matplotlib.pyplot.subplot 

says "If a number the ratio of x-unit/y-unit in screen-space".

https://matplotlib.org/2.0.1/api/_as_gen/matplotlib.axes.Axes.set_aspect.html#matplotlib.axes.Axes.set_aspect

says "num | a circle will be stretched such that the height is num times the width".

This looks to me like x and y are the other way round.  Is this right?

**Comment by timhoffm** [comment]
Indeed, it should be the ratio of y-unit/x-unit in screen-space.

![grafik](https://user-images.githubusercontent.com/2836374/33425510-36ea7ba8-d5bf-11e7-8142-a4c80119dea3.png)

**Comment by keithbriggs** [comment]
Then I think that this is opposite to the standard convention in video and TV, and image processing generally.

If I am right about that, a fix might be to keep the "aspect" argument with its current meaning (for backwards compatibility), and add a new "aspect_ratio" argument with the conventional meaning.

Also, a comma is needed after "If a number", otherwise the documentation makes no sense.

**Comment by timhoffm** [comment]
> Then I think that this is opposite to the standard convention in video and TV, and image processing generally.

I suppose so. The [pixel aspect ratio](https://en.wikipedia.org/wiki/Pixel_aspect_ratio) "describes how the width of a pixel in a digital image compares to the height of that pixel". It's counter-intuitive, that ``aspect=16/9.`` does not result in a landscape-style stretch.

I don't know what's worse: having ``aspect`` with a non-standard meaning, or having ``aspect`` and ``aspect_ratio`` with different meanings. That's for someone else to decide. At least, the non-standard meaning should be clarified in the docs.

**Comment by tacaswell** [comment]
Changing 'aspect' to be inverted is a non-starter, and I am pretty :-1: on having both `aspect` and `aspect_ratio`.  Users would still hit `aspect` and have to understand that it is inverted and that `aspect_ratio` is the 'correct' one, etc.

**Comment by jklymak** [comment]
Closed by #9902

**Comment by keithbriggs** [comment]
Actually, the expression

 the ratio of y-unit/x-unit in screen-space

is illogical. It should be either

 the ratio y-unit/x-unit in screen-space

or

 the ratio of y-unit to x-unit in screen-space

Keith
 

________________________________________

**Comment by efiring** [comment]
Historical note: the definition of aspect here is mine, I believe, and comes from sailing: a high aspect-ratio rig is one with a tall mast and a short boom.  That's how I have always remembered it.
