### ISSUE TITLE
doc infelicities on subaxes

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#9740]
https://matplotlib.org/2.0.1/api/pyplot_api.html#matplotlib.pyplot.subplot

sometimes writes "subaxes" and sometimes "sub-axes".  This makes it hard to search.

Also, it uses expressions like "Return a subplot axes" which is ungrammatical because "axes" is a plural noun.   I think it should be something like "Return a pair of subplot axes".

**Comment by story645** [comment]
While axes is generally a plural noun, in matplotlib it's a singular (collective) object. 

plt.subplot(211) returns a subplot axes object in the first row of a girl containing two rows.
