### ISSUE TITLE
Missing arguments in call to exception_handler

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#9741]
### Bug report

**Bug summary**

I have customized the exception handler for use in a PyQt5 GUI that has an embedded Matplotlib canvas. The call signature for the `exception_handler` function in `backends/backend_qt5.py` has three positional arguments, which are matched in my customized function. However, an exception triggered by a `key_press_event` that is caught in the [`process` function within cbooks/__init__.py](https://github.com/matplotlib/matplotlib/blob/91e4bee6e543dd62375feab7152eb9bab9647fa9/lib/matplotlib/cbook/__init__.py#L395) calls the function with a single argument.

**Code for reproduction**

This is the code I use to override the `exception_handler` function. `self.canvas` is an object that is a subclass of ` matplotlib.backends.backend_qt5agg.FigureCanvasQTAgg`.

```python
self.canvas.callbacks.exception_handler = report_exception
```

**Actual outcome**

 A key press within the Matplotlib canvas triggered the following traceback.

```
TypeError                                 Traceback (most recent call last)
~/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py in keyPressEvent(self, event)
    331         key = self._get_key(event)
    332         if key is not None:
--> 333             FigureCanvasBase.key_press_event(self, key, guiEvent=event)
    334 
    335     def keyReleaseEvent(self, event):

~/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backend_bases.py in key_press_event(self, key, guiEvent)
   1870         event = KeyEvent(
   1871             s, self, key, self._lastx, self._lasty, guiEvent=guiEvent)
-> 1872         self.callbacks.process(s, event)
   1873 
   1874     def key_release_event(self, key, guiEvent=None):

~/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/cbook/__init__.py in process(self, s, *args, **kwargs)
    394                 except Exception as exc:
    395                     if self.exception_handler is not None:
--> 396                         self.exception_handler(exc)
    397                     else:
    398                         raise

TypeError: report_exception() missing 2 required positional arguments: 'error' and 'traceback'
```

**Expected outcome**

I can, in principle, change my exception handler to accept the single positional argument, with the others specified by keywords, but the Matplotlib implementation seems to be inconsistent with its own call signatures. 

**Matplotlib version**

  * Operating system: Mac OS 10.12.6
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
The API is documented to be a single input (https://matplotlib.org/api/cbook_api.html#matplotlib.cbook.CallbackRegistry ).

The function in `backend_qt5` seems to be un-used.

https://github.com/matplotlib/matplotlib/blob/df1af2f41efd51db96e7c7c3de7505a69d71f994/lib/matplotlib/backends/backend_qt5.py#L829-L843

**Comment by tacaswell** [comment]
It looks like this function goes back to d934dd0db78f46f807c5ed7f5f8c8a5f3c425b8c which looks like it was used for testing / debugging and has been carried along for the last 13 years or so.

**Comment by rayosborn** [comment]
Shouldn't the call signature for a Matplotlib-defined exception handler match that of [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook), *i.e.*,

    sys.excepthook(type, value, traceback)

**Comment by tacaswell** [comment]
Where we call this from we have easy-access to the `Exception` object and `https://docs.python.org/3/library/sys.html#sys.exc_info` is available if you want those values.  The main reason that this exists is to prevent exceptions in the callbacks from killing Qt.

I am not enthusiastic about changing this API.

**Comment by rayosborn** [comment]
That's fine. I can use `sys.exc_info` in my own code, as long as Matplotlib doesn't do anything to modify the original exception. It might be worth removing the exception_handler function in `backing_qt5.py` to avoid further confusion. I presume you need to make sure it's not used in another context, so I won't issue a pull request unless you want me to.
