### ISSUE TITLE
*frac* in set_thetagrids() doesn't work

### ISSUE THREAD

**Issue by zhengx0925** [matplotlib/matplotlib#9744]
No code exits to deal with the parameter *fact* for matplotlib 2.1.0 as shown below.

    @docstring.dedent_interpd
    def set_thetagrids(self, angles, labels=None, frac=None, fmt=None,
                       **kwargs):
        """
        Set the angles at which to place the theta grids (these
        gridlines are equal along the theta dimension).  *angles* is in
        degrees.

        *labels*, if not None, is a ``len(angles)`` list of strings of
        the labels to use at each angle.

        If *labels* is None, the labels will be ``fmt %% angle``

        *frac* is the fraction of the polar axes radius at which to
        place the label (1 is the edge). e.g., 1.05 is outside the axes
        and 0.95 is inside the axes.

        Return value is a list of tuples (*line*, *label*), where
        *line* is :class:`~matplotlib.lines.Line2D` instances and the
        *label* is :class:`~matplotlib.text.Text` instances.

        kwargs are optional text properties for the labels:

        %(Text)s

        ACCEPTS: sequence of floats
        """
        # Make sure we take into account unitized data
        angles = self.convert_yunits(angles)
        angles = np.asarray(angles, float)
        self.set_xticks(angles * (np.pi / 180.0))
        if labels is not None:
            self.set_xticklabels(labels)
        elif fmt is not None:
            self.xaxis.set_major_formatter(mticker.FormatStrFormatter(fmt))
        for t in self.xaxis.get_ticklabels():
            t.update(kwargs)
        return self.xaxis.get_ticklines(), self.xaxis.get_ticklabels()

For matplotlib 2.0.2, the corresponding code is:
if frac is not None:
     self._theta_label1_position.clear().translate(0.0, frac)
      self._theta_label2_position.clear().translate(0.0, 1.0 / frac)

**Matplotlib version**

  * Operating system: Win 10
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6.3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
@zhengx0925 If you put those lines back does it work as expected?  If so can you open a PR fixing it?

**Comment by zhengx0925** [comment]
@tacaswell It doesn't work:
    ax._theta_label1_position.clear().translate(0.0, fact)
AttributeError: 'PolarAxesSubplot' object has no attribute '_theta_label1_position'

**Comment by QuLogic** [comment]
`frac` is no longer needed because the labels now correctly obey the padding setting which can be set with `ax.tick_params(..., pad=123)`. `frac` also doesn't work so well since the polar projection now supports setting the minimum radius to not be at the origin.

I suppose at the very least a deprecation warning should be added; I'm not sure how straightforward it would be to make it possible to use `frac` again.

**Comment by zhengx0925** [comment]
@QuLogic It works. Thanks.

**Comment by tacaswell** [comment]
closed by #9796
