### ISSUE TITLE
plt.ginput broken on 2.1.0: plot does not appear

### ISSUE THREAD

**Issue by mc10** [matplotlib/matplotlib#9758]
### Bug report

**Bug summary**: When calling `plt.ginput`, the icon for the graphics library (Qt5 for my case) will appear, but the actual plot does not appear, making it impossible to select icons. Other `plt` calls like `plt.show()` work fine. This issue is absent on 2.0.2.

I've confirmed that the changes in #8305 are the issue; reverting those changes manually fixes the problem. However, since it looks like that PR fixed another issue; I'm not sure what the right thing to do is.

**Code for reproduction**: See https://matplotlib.org/examples/pylab_examples/ginput_demo.html without the final line:

```python
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(10)
plt.plot(t, np.sin(t))
print("Please click")
x = plt.ginput(3)
print("clicked", x)
```

**Matplotlib version**

  * Operating system: macOS 10.13.1
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg (also tried TkAgg)
  * Python version: 3.6.3 (installed via Homebrew)

**Comment by timkchan** [comment]
Has this been back-ported to 2.1.0? The issue still persists in latest 2.1.0.
I have to install 2.0.2 to get this to work.

**Comment by jenshnielsen** [comment]
It's been backported to 2.1.x so it will be in 2.1.1 when that is released. There is no such thing as the latest 2.1.0 as there is exactly one release of 2.1.0 which is where this bug was originally reported
