### ISSUE TITLE
Plot_date default date format is not always the same

### ISSUE THREAD

**Issue by mirkocoric** [matplotlib/matplotlib#9765]
### Bug report

**Bug summary**

In the example below date format is changed when plotting with plot_date after calling dates.DayLocator(). This can be fixed with using dates.DateFormatter(), but the confusion could be avoided if plot_date uses the same date format when it is not specified by user.

**Code for reproduction**

```python
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

DATE1 = mdates.date2num(datetime.datetime(2017, 8, 10, 18, 0))
DATE2 = mdates.date2num(datetime.datetime(2017, 8, 11, 18, 0))
DATE3 = mdates.date2num(datetime.datetime(2017, 8, 12, 18, 0))
plt.plot_date([DATE1, DATE2, DATE3], [1, 2, 3], '-')
plt.show()

plt.plot_date([DATE1, DATE2, DATE3], [1, 2, 3], '-')
plt.gca().xaxis.set_major_locator(mdates.DayLocator())
plt.show()
```

**Actual outcome**

<img width="575" alt="beforedaylocator" src="https://user-images.githubusercontent.com/14822000/32735913-638bd714-c896-11e7-9f4b-94752e53e3e4.png">

<img width="584" alt="afterdaylocator" src="https://user-images.githubusercontent.com/14822000/32735922-6a0b0aa6-c896-11e7-93be-00c99b04d7ae.png">

**Matplotlib version**

  * Operating system: Mac OS
  * Matplotlib version:  2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 2.7.13
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by story645** [comment]
I sort of thing this should be generalized to plot_date should default to include the resolution of the ticks (or at least only one level higher). Like since it's a day locator, the ticks should include the days, it it was a month locator, it should id the months, etc...

**Comment by jklymak** [comment]
Cross ref #10841

**Comment by timhoffm** [comment]
Apparently fixed. As of current master, the ticks include the days.
