### ISSUE TITLE
Dotted grid lines have different individual dot sizes in pdf files

### ISSUE THREAD

**Issue by ViaFerrata** [matplotlib/matplotlib#9780]
Hello there,

I've a problem with drawing dotted grid lines that are saved in pdf files.
The grid is drawn with `plt.grid(True, zorder=0, linestyle='dotted')`.

I've attached a pdf file that demonstrates the issue:
If you look at the dotted grid line with 300% Zoom, the single dots in the grid have different sizes (some are thicker, some are thinner).
However, if you apply a higher zoom (e.g. 800%), you can see that suddenly, all of the dots have the same size.

I've tried different pdf viewers (Ocular, Adobe Reader, Evince), but the result stayed the same.
As a result, I guess that this has something to do with the rendering of the grid in pdf files, since the shape of the dots is correct in very high zooms.

Any idea?

Zoom 300%, different dot size             |  Zoom 800%, same dot size
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/19201882/32785126-fbabbe5a-c950-11e7-82d4-02d706dda63e.png" width="60%" height="60%">  |  <img src="https://user-images.githubusercontent.com/19201882/32785142-092f2684-c951-11e7-92c5-45eee68721d6.png" width="40%" height="40%">

The pdf file: 
[PT_model_VGG_4d_yzt-x_muon-CC_to_elec-CC_3-40GeV.pdf](https://github.com/matplotlib/matplotlib/files/1471114/PT_model_VGG_4d_yzt-x_muon-CC_to_elec-CC_3-40GeV.pdf)

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.1.0 installed with pip
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.13

**Comment by efiring** [comment]
This is inherent in vector-based file formats--you are at the mercy of the renderer and the available resolution of the output device.  I don't think there is anything matplotlib can do to improve the situation, so I am closing this.

**Comment by afvincent** [comment]
@ViaFerrata Defining a default grid custom linestyle with more space between the dots (with the `grid.linestyle` rcParam) might be a reasonable workaround if this issue with PDF rendering is really a problem for your use case. You can find an example of how to do this in the 2.1 [What's new](https://matplotlib.org/users/whats_new.html#stricter-validation-of-line-style-rcparams) list.

**Comment by jklymak** [comment]
If you have access to Acrobat turn off image smoothing and line smoothing.
