### ISSUE TITLE
Exception handling in the Qt5 backend

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#9782]
### Feature Request

**Request Summary**

This is not a bug, but I would like to be able to customize exception handling when using the Qt5 backend. At the moment, there is a `exception_handler` function for this in `backends/backend_qt5.py`, but I gather from the discussion in #9741 that it is not used. I would like to suggest that it be updated to conform to the exception handler defined [elsewhere](https://github.com/matplotlib/matplotlib/blob/91e4bee6e543dd62375feab7152eb9bab9647fa9/lib/matplotlib/cbook/__init__.py#L395),  so that it is used in the exception trapped in the `__draw_idle_agg` function within `backends/backend_qt5agg.py`. Currently, this automatically prints the exception to the terminal using `traceback.print_exc()` and does not allow me to override this behavior.  (In principle, I could subclass FigureCanvasQTAggBase to customize `__draw_idle_agg`, but this seems to be prevented by inheritance rules in my current design). 

The function `traceback.print_exc()` is called in a few other modules, so ideally, there should be a central exception handler that replaces all of these calls. I don't know enough about the Matplotlib design to know where that is best defined - perhaps [here](https://github.com/matplotlib/matplotlib/blob/91e4bee6e543dd62375feab7152eb9bab9647fa9/lib/matplotlib/cbook/__init__.py#L257).

**Matplotlib version**
  * Operating system: Mac OS 10.12.6
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.3
  * Jupyter version (if applicable):

**Comment by tacaswell** [comment]
I also like the changing to match the signature on the callback registry.   I suggest hanging a user-configurable callable off of either `CanvasBase` or the base `QtCanvas`.

Putting the default handler into cbook is a reasonable idea.  I like the freedom to set the handler on a per registry / per Canvas basis, but having a `cbook.exception_handler` default is :+1:
