### ISSUE TITLE
Contour plot doesn't show if setting "manual=True" in plt.clabel()

### ISSUE THREAD

**Issue by zhengx0925** [matplotlib/matplotlib#9791]
### Bug report

Contour plot doesn't show if setting "manual=True" in plt.clabel() for matplotlib 2.1.0. Such issue is not observed in matplotlib 2.0.2.

```python
"""
Illustrate simple contour plotting, contours on an image with
a colorbar for the contours, and labelled contours.

See also contour_image.py.
"""
import matplotlib
import numpy as np
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

matplotlib.rcParams['xtick.direction'] = 'out'
matplotlib.rcParams['ytick.direction'] = 'out'

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = mlab.bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0)
Z2 = mlab.bivariate_normal(X, Y, 1.5, 0.5, 1, 1)
# difference of Gaussians
Z = 10.0 * (Z2 - Z1)


# Create a simple contour plot with labels using default colors.  The
# inline argument to clabel will control whether the labels are draw
# over the line segments of the contour, removing the lines beneath
# the label
plt.figure()
CS = plt.contour(X, Y, Z)
plt.clabel(CS, inline=1, fontsize=10, manual=True)
# plt.clabel(CS, inline=1, fontsize=10, manual=False)
plt.title('Simplest default with labels')
plt.show()
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6.3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by afvincent** [comment]
@zhengx0925 Thank you for the bug report :). Do you know which backend are you using? If not, the string returned by `print(matplotlib.get_backend())` should normally tell you.

**Comment by jklymak** [comment]
Yeah, I'm not clear on what "doesn't show" means.  Do you mean after clicking on the contours nothing is drawn?

**Comment by afvincent** [comment]
Not sure that there is an “actual” bug. It looks more like you should add a `plt.show` (or use an interactive session with `plt.ion`) before calling `plt.clabel`. Otherwise, the figure window will not be displayed and you will not have anywhere to click (as `plt.clabel` is asking for with `manual=True`).

**Comment by jklymak** [comment]
Yeah, a quick look at the Blame doesn't indicate any changes in manual=True the last few years, so its strange that it doesn't work in 2.1.0, but worked in 2.0.2.

**Comment by afvincent** [comment]
Locally, apart from a slightly ugly warning ("QTimer::singleShot: Timers cannot have negative timeouts"), the following snippet (mainly the example above but in a `plt.ion()` session) is working fine.

```python
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
plt.ion()

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = mlab.bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0)
Z2 = mlab.bivariate_normal(X, Y, 1.5, 0.5, 1, 1)
Z = 10.0 * (Z2 - Z1)


plt.figure()
CS = plt.contour(X, Y, Z)
plt.clabel(CS, inline=1, fontsize=10, manual=True)
```

**Comment by zhengx0925** [comment]
@afvincent adding plt.ion() works for me as well. Thanks.
