### ISSUE TITLE
PdfPages and PdfFile closing error

### ISSUE THREAD

**Issue by scholi** [matplotlib/matplotlib#9798]
Hi,
I have noticed, that

```python
from matplotlib.backends.backend_pdf import PdfPages
pdf =PdfPages('test.pdf')
pdf.savefig()
pdf.close()
```

does not release the file opened. I found the bug in the source. It's an indentation problem here: (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py#L620)

I don't want to pull the whole repo for such a small pull request. Can someone do it for me?

Thank you and kind regards

Olivier

**Comment by QuLogic** [comment]
Should it be indented more or less? I'm not sure I see any indentation problem there.

**Comment by scholi** [comment]
I should have been more specific sorry. So it should be less indented otherise the first if will call the flush, but thever the close which implies that the files stays forever and thus the pdf cannot be view or deleted by an external program.

Does it make sens?

Kind regards

**Comment by dopplershift** [comment]
I'm not sure how that's the problem, looking here:
https://github.com/matplotlib/matplotlib/blob/3ccaf2d664cb89c9483f79d25686f409cabe09e6/lib/matplotlib/backends/backend_pdf.py#L611-L620

The only way `self.fh.close()` isn't called is if `self.passed_in_file_object` is `True`.  `PdfPages.__init__` would seem to indicate that it's `False` when passing in a filename:
https://github.com/matplotlib/matplotlib/blob/3ccaf2d664cb89c9483f79d25686f409cabe09e6/lib/matplotlib/backends/backend_pdf.py#L435-L453

**Comment by scholi** [comment]
mhmmm... you're right. That should not be the problem. Nevertheless I had the impression that it solved it. I'll double check everything and let you know.

**Comment by scholi** [comment]
It seems to work fine on my home computer. I'll double check that matplotlib is well updated at work. Sorry for the trouble and thanks for this awesome library :)
