### ISSUE TITLE
DOC/BLD: inter sphinx numpy

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#9802]
### Bug report

**Bug summary**

Neither `numpy.datetime64` nor `:class:numpy.datetime64` links back to numpy.   Could be operator error?  

i.e. http://matplotlib.org/faq/howto_faq.html#plot-numpy-datetime64-values  is composed w/ 

``` rst 
`numpy.datetime64`
```

**Comment by dstansby** [comment]
I'm fairly sure it should be :numpy:class:\`datetime64\`, since "numpy" is the module name that intersphinx uses for lookup. I'll give it a go.

**Comment by efiring** [comment]
I don't know whether it is related, but the numpy docstring is misleading:
```
In [1]: import numpy

In [2]: numpy.datetime64?
Init signature: numpy.datetime64(self, /, *args, **kwargs)
Docstring:
Base class for numpy scalar types.

Class from which most (all?) numpy scalar types are derived.  For
consistency, exposes the same API as `ndarray`, despite many
consequent attributes being either "get-only," or completely irrelevant.
This is the class from which it is strongly suggested users should derive
custom scalar types.
File:           ~/anaconda/envs/test/lib/python3.5/site-packages/numpy/__init__.py
Type:           type
```

**Comment by dstansby** [comment]
Never mind, ignore the above comment, I read the intersphinx docs completely wrong.

**Comment by anntzer** [comment]
Probably because numpy forgot to add an intersphinx entry (see https://github.com/matplotlib/matplotlib/issues/9331 https://github.com/matplotlib/matplotlib/pull/8175 for similar instances on our side).  I have a script to parse the intersphinx db somewhere...

**Comment by dstansby** [comment]
`python -m sphinx.ext.intersphinx 'https://docs.scipy.org/doc/numpy/objects.inv' | grep 'datetime64` doesn't output anything. (remove the grep to see the whole intersphinx inventory for numpy), so I think you're right @anntzer

**Comment by jklymak** [comment]
Thanks all!  Looks like its really an issue on their side, not ours.  I'll leave open to monitor...

**Comment by anntzer** [comment]
Oh nice, I never needed to write that script to start with then :p
