### ISSUE TITLE
Cloud any one experience the below error while installing 'pyplot' package 

### ISSUE THREAD

**Issue by OsamaFayed** [matplotlib/matplotlib#9822]
### Bug report

**Error while installing pyplot package**

**Code for reproduction**

```python
# import matplotlib.pyplot as plt
```

**Actual outcome**
```
#     import matplotlib.pyplot as plt
#     ModuleNotFoundError: No module named 'matplotlib.pyplot'
```

**Matplotlib version**
  * Windows 10:
  * Matplotlib version 12.1.0 : 
  * Python 3.6:
  * Jupyter version (if applicable):
  * Django | 1.11.7 |
  * Pillow | 4.3.0 | 4.3.0
  * cycler | 0.10.0 |  
  * image | 1.5.16 | 1.5.16
  * matplotlib | 2.1.0 | 2.1.0rc1
  * numpy | 1.13.3 | 1.13.3
  * olefile | 0.44 | 0.44
  * pip | 9.0.1 | 9.0.1
  * pyodbc | 4.0.21 | 4.0.21
  * pyparsing | 2.2.0 | 2.2.0
  * python-dateutil | 2.6.1 | 2.6.1
  * pytz | 2017.3 | 2017.3
  * setuptools | 36.8.0 | 36.8.0

**Comment by jklymak** [comment]
Please ask on user's mailing list or stackexchange!  Thanks!
