### ISSUE TITLE
Visibility of pane edges in 3d figures

### ISSUE THREAD

**Issue by kramerfelix** [matplotlib/matplotlib#9833]
Sorry for just linking, but I am not sure if this belongs here and don't want to repost it all.
[https://stackoverflow.com/questions/47334760/3d-figures-from-matplotlib-visibility-of-pane-edge](https://stackoverflow.com/questions/47334760/3d-figures-from-matplotlib-visibility-of-pane-edge)

**Comment by tacaswell** [comment]
That question is probably better handled on the mailing list (https://mail.python.org/mailman/listinfo/matplotlib-users you will need to subscribe to post un-moderated).

attn @WeatherGod
