### ISSUE TITLE
console gets stuck when creating figure

### ISSUE THREAD

**Issue by mboesi** [matplotlib/matplotlib#9834]
Hi everybody,
after the upgrade to matplotlib2.1.0 all my plotting scripts do not work any more. I've tracked the issue down to the matplotlib. Whenever I use its features the console gets stuck and I have to kill it. I tried to use the figure() or plot(...) command alone, but the result was the same: the script execution stops exactly at the first use of any matplotlib commands. The script is launched directly from the bash command line.
The update was done by pipdate.

Console gets stuck whenever a matplotlib command is used.

**Code for reproduction**

`import matplotlib.pyplot as plt
plt.figure()`

```python
# Paste your code here
`# plot reaction rates in arrhenius plots

# CSV writer
import csv
# Pandas Library for reading csv
import pandas as pd
# Numpy
import numpy as np
# Cantera
import cantera as ct
# matplotlib.pyplot
import matplotlib.pyplot as plt

def cm2inch(*tupl):
    inch = 2.54
    if isinstance(tupl[0], tuple):
        return tuple(i/inch for i in tupl[0])
    else:
        return tuple(i/inch for i in tupl)

# inits of A [kmol/m^3/s], Ea [J/mol]

ArrCoeffs = [
[5.012e+11,0,200000,'Current'],

[1.58E+10,0,2.40E+04,'Wolf'],
]

T = [1000+50*x for x in range(40)] #, 1250, 1500, 1750, 2000, 2250, 2500, 2750, 3000, 3250, 3000]

k = [[0 for x in range(len(T))] for y in range(len(ArrCoeffs))]


for index in range(len(T)) :
    for rI in range(len(ArrCoeffs)):
        k[rI][index] = ArrCoeffs[rI][0]*T[index]**ArrCoeffs[rI][1]*np.exp(-ArrCoeffs[rI][2]/8.3144/T[index])



fig = plt.figure(figsize=cm2inch(22,12))
cm = plt.get_cmap('gist_ncar')
ax = plt.subplot(111)
ax.set_color_cycle([cm(1.*i/len(ArrCoeffs)) for i in range(len(ArrCoeffs))])

for rI in range(len(ArrCoeffs)):
    if 'Current' in ArrCoeffs[rI][3] :
        ax.plot(np.divide(1000.0,T),np.log(k[rI]), marker='.', label=ArrCoeffs[rI][3],linewidth=2)
    else:
        ax.plot(np.divide(1000.0,T),np.log(k[rI]), label=ArrCoeffs[rI][3],linewidth=2)

plt.show()`

```

**Actual outcome**

Console gets stuck and has to be killed.

**Expected outcome**

One figure having log-log-axis and showing two lines.

**Matplotlib version**

  * Operating system: Ubuntu 14.04LTS
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 2.7.6
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: ipython 5.5.0

initial installation via pip
upgrade by pipdate

**Comment by jklymak** [comment]
I would assume you have a bad installation if 
```python
import matplotlib.pyplot as plt
plt.figure()
```
Try chaning the backend, and saving:
```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.figure()
plt.savefig('test.png')
```
If that runs, then I'd suspect your tk library is not compatible with a modern matplotlib.  Strongly suggest using anaconda instead of pip because it will upgrade libraries as well as python.  

It would help us know what tk library you are using.  Maybe the checks aren't strict enough at some point?

**Comment by mboesi** [comment]
jklymak, I tired your suggestion but still get stuck at plt.figure().

The Tk version is 8.6.

I tried to downgrade to version 1.5.3 but the problem, is not solved.

**Comment by tacaswell** [comment]
How long does it get stuck for?  The first time your import Matplotlib it searches for fonts and builds a cache which can take a while (depending on how many fonts you have).

Do you get any sort of traceback?

**Comment by mboesi** [comment]
hi, I've once waited for an hour or so before killing the console. There was no output/traceback and stopping with Ctrl+C does not work.

**Comment by mboesi** [comment]
hi, I've once waited for an hour or so before killing the console. There was no output/traceback and stopping with Ctrl+C does not work.

**Comment by mboesi** [comment]
Problem was resolved by installing anaconda and re-installing matplotlib using conda. 

Thank you all for your help!
