### ISSUE TITLE
Shift+Arrow key events not detected in osx backend

### ISSUE THREAD

**Issue by cbrnr** [matplotlib/matplotlib#9835]
Consider the following example code:

```python
import matplotlib.pyplot as plt
fig = plt.figure()

def on_key(event):
    print('you pressed', event.key, event.xdata, event.ydata)

fig.canvas.mpl_connect('key_press_event', on_key)
```

Now when I run this code and press Shift+Left Arrow, the `qt5` backend correctly detects this event as `shift+left`. However, the `osx` backend (which AFAIK is the default backend on macOS) doesn't register the shift key at all, I only get `left`. Is it possible to fix this somehow?

**Comment by dstansby** [comment]
I delved into the key handling recently, I'll have a look at see if I can do anything

**Comment by cbrnr** [comment]
Awesome! Let me know if I can be of any help!

**Comment by dstansby** [comment]
I've tracked it back to the OSX c code, which converts whatever the key press event is to a char here: https://github.com/matplotlib/matplotlib/blob/813d842994a76b94508d8ec4938f9985ddb86cab/src/_macosx.m#L2622

Unfortunately I don't really do C, so someone else is going to have to figure it out from here

**Comment by dstansby** [comment]
And I'm guessing this is the function that needs to be modified somehow: https://github.com/matplotlib/matplotlib/blob/813d842994a76b94508d8ec4938f9985ddb86cab/src/_macosx.m#L2558-L2617

**Comment by cbrnr** [comment]
This looks promising. I wonder if it as easy as adding

```
if ([event modifierFlags] & NSShiftKeyMask)
        [returnkey appendString:@"shift+" ];
```

in line 2608... but I guess this needs to be restricted to only a subset of keys such as the arrow keys.

**Comment by dopplershift** [comment]
Adding that for me and rebuilding does get me shift events, but as you expected, shift + g produces "shift+G". It looks like the Qt backend has a list of special keys it looks for first, then it assumes characters and removes the shift modifier.

**Comment by jklymak** [comment]
@cbrnr Have a look at #9836 if you are able to download development versions....

**Comment by cbrnr** [comment]
Closing since #9836 was merged.
