### ISSUE TITLE
YearLocator should prefer ticks at the turn of the decade

### ISSUE THREAD

**Issue by has2k1** [matplotlib/matplotlib#9838]
**Bug summary**

`YearLocator` is agnostic about decades. Ticks at the decades are nicer, so when choosing a starting value in some cases it should prefer to start a the turn of the decade or even mid decade. i.e 1970 instead of 1968, 1965 instead of 1964. This "smart" behaviour should apply when the intervals are factors of 5 and 10. 

**Code for reproduction**

```python
import datetime
import matplotlib.pyplot as plt

x = [datetime.datetime(1966, 1, 1),
     datetime.datetime(2017, 1, 1)]

ticks = [datetime.datetime(i, 1, 1)
        for i in range(1970, 2020, 10)]

y = np.arange(len(x))
fig, ax = plt.subplots()
ax.plot_date(x, y)
# ax.set_xticks(ticks)  # preferred ticks
```

**Actual outcome**
![bad-date-ticks](https://user-images.githubusercontent.com/780341/33162629-24dcc99a-cff0-11e7-8f9d-61b29de67429.png)

**Better outcome**
![good-date-ticks](https://user-images.githubusercontent.com/780341/33162648-40ddcb26-cff0-11e7-9774-8a9c86a06882.png)

**Comment by dstansby** [comment]
Probably related to #9801

**Comment by has2k1** [comment]
Yes I think the motivation behind both issues is the same, but the solution does not work for this case.

**Comment by jklymak** [comment]
Yeah, the logic for years is different because you don't know the range of years to start with.  But, this should be easy to fix with a bit of extra logic (I think).

```python

import datetime
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np

x = [datetime.datetime(1966, 1, 1),
     datetime.datetime(2017, 1, 1)]

ticks = [datetime.datetime(i, 1, 1)
        for i in range(1970, 2020, 10)]

y = np.arange(len(x))
fig, ax = plt.subplots()
ax.plot_date(x, y)
locator = mdates.AutoDateLocator(interval_multiples=True)
plt.show()

```
