### ISSUE TITLE
No keyboard focus in figures on macOS with Anaconda

### ISSUE THREAD

**Issue by cbrnr** [matplotlib/matplotlib#9839]
Using Python installed via Anaconda on macOS, figures do not receive keyboard focus. All key presses go to the terminal instead.

Minimal example:

```python
import matplotlib.pyplot as plt
plt.plot(1)
plt.show()
# then click on the "Save" icon
# it is impossible to change the file name in the dialog window
```

The same thing happens when listening to key press events - they are simply not detected at all.

Using Python installed via Homebrew doesn't have this problem. There are some reports regarding this behavior (#665, #2120, #3367, #4372), but I still run into this issue. I'm using the latest Anaconda packages and tried the latest Matplotlib release and latest development version.

**Comment by cbrnr** [comment]
Update: This only happens when using the (default) `osx` backend.

**Comment by dstansby** [comment]
Are you using the framework build of python? (ie. are you starting python using `pythonw`)

**Comment by cbrnr** [comment]
No. It works with `pythonw`, but how can I start IPython using this framework build?

**Comment by jklymak** [comment]
Here is a magic incantation to get `ipython` to play w `pythonw` https://github.com/matplotlib/matplotlib/issues/8982#issuecomment-342685632

**Comment by cbrnr** [comment]
Nice, thanks @jklymak this works! I wish Anaconda made `pythonw` the default for everything to avoid these kinds of tricks. Has anyone ever asked them why they don't want to play nice with macOS frameworks?

**Comment by jklymak** [comment]
Ha ha.  I think there are a *few* threads about it....  I don't understand the issue, but, I don't use ipython except via jupyter notebooks, so...

**Comment by efiring** [comment]
On 2017/11/23 9:19 PM, Clemens Brunner wrote:
> Nice, thanks @jklymak <https://github.com/jklymak> this works! I wish 
> Anaconda made |pythonw| the default for everything to avoid these kinds 
> of tricks. Has anyone ever asked them why they don't want to play nice 
> with macOS frameworks?

Yes, here is one early conversation about that:

https://groups.google.com/a/continuum.io/forum/#!topicsearchin/anaconda/subject$3A%22OSX$3A$20why$20not$20make$20%22$20AND$20subject$3Apython$20AND$20subject$3A%22$20invoke$20the$20framework$3F%22/anaconda/-ZAynUQW5HQ


Eric

**Comment by cbrnr** [comment]
OMG what's the tl;dr? I assume not much has happened. This is the one reason why I can't recommend Anaconda on macOS without any reservations.

**Comment by jklymak** [comment]
There is an open issue:  https://github.com/ContinuumIO/anaconda-issues/issues/199

**Comment by jklymak** [comment]
if you want more bedtime reading ;-)

**Comment by efiring** [comment]
On 2017/11/24 9:55 AM, Clemens Brunner wrote:
> OMG what's the tl;dr? I assume not much has happened. This is the one 
> reason why I can't recommend Anaconda on macOS without any reservations.

Right, no resolution or improvement that I know of.  For matplotlib, it 
just means it is easiest to use the qt5agg backend instead of the macosx 
backend.  The qt5agg backend has more features and gets more development 
anyway.  The Anaconda limitation is annoying, but I wouldn't let it 
block a recommendation to use Anaconda on OS X.

**Comment by cbrnr** [comment]
You're right, but the problem with this is that osx is the default backend. If it wasn't this wouldn't be such a big issue. Anaconda could probably change the default to qt5 because PyQt5 gets installed anyway.

**Comment by jklymak** [comment]
#9795 will make it easier to configure the "default" on a user-by-user basis...

**Comment by tacaswell** [comment]
I thought qt5 _was_ the default on osx with conda....Did that change recently?

**Comment by efiring** [comment]
I just checked by installing from defaults (version 2.0.2) and from conda-forge (version 2.1.0), and in both cases the backend default is qt5agg.  This is with Python 3.6.

**Comment by cbrnr** [comment]
How did you check this? When I start IPython in Anaconda, I get:

```
In [1]: %matplotlib
Using matplotlib backend: MacOSX
```

Also, `matplotlib.get_backend()` returns `MacOSX`.

**Comment by efiring** [comment]
@cbrnr, thanks for keeping after this--I wasn't being careful enough.  It turns out I didn't check something that I thought I had checked, and the upshot is that my backend was being set from my own matplotlibrc file, not from the one installed by conda.

Side note: it's far from obvious, but to find out which matplotlibrc file is being used one can call ``matplotlib.matplotlib_fname()``.

**Comment by cbrnr** [comment]
So what's the plan? The best solution would be if Anaconda defaulted their Python executables to a framework build (something everyone else is doing, seems to have no negative side effects and makes Python run smoothly on macOS). Alternatively, as a workaround, they could change the default matplotlib backend to `qt5` (on Macs) - not sure if this is feasible though because this would mean introducing `PyQt5` as a hard dependency of `matplotlib`.

**Comment by Mottl** [comment]
@cbrnr, could you test whether the issue gone with the fix in #12633?

**Comment by cbrnr** [comment]
I tried, but cloning stalls after an hour or so, so I can't test with this PR. However, I noticed that my example from my initial post does work in Anaconda now. Unless I create a new env, I then get a segfault. So I'm not sure what's wrong with Anaconda on my machine, I never seem to get it to work properly.

**Comment by cbrnr** [comment]
I tested with the latest Anaconda packages and this issue has been resolved. Thanks!
