### ISSUE TITLE
Missing `normed` parameter description in matplotlib.pyplot.hist

### ISSUE THREAD

**Issue by Atcold** [matplotlib/matplotlib#9864]
See online documentation at https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html
The parameter `normed` is never defined.

**Comment by QuLogic** [comment]
You should use `density` instead, though `normed` should also be noted on that entry.

This looks like a manual merging error in #8993. @dstansby

**Comment by Atcold** [comment]
Yeah, @QuLogic, I'm aware of that. I was pointing out that something went wrong with the docs.
