### ISSUE TITLE
Infinite number of /tmp/matplotlib-* dirs on machine without HOME env variable

### ISSUE THREAD

**Issue by EtsuNDmA** [matplotlib/matplotlib#9868]
Python 2.7
Matplotlib 2.1.0

Hi!
When I import matplotlib under user without HOME enviroment variable matplotlib creates /tmp/matplotlib-[smth random] directory. After some time huge amount of temp directories take up alll disck space

I know that I can set MPLCONFIGDIR env variable, but befor I knew it, fresh install of matplotlib have crashed the server

Maybe it's not a bug, it's a feature, but I think it is unsafe

**Comment by anntzer** [comment]
I agree that the tempdirs should be cleaned at exit (it's not as if we're reusing them anyways).

**Comment by WeatherGod** [comment]
Hmmm, it might make sense to register an atexit() action to clean that up?

**Comment by dstansby** [comment]
Is there any reason not to reuse the same directory?

**Comment by anntzer** [comment]
Right now it's using mkdtemp; I think the problem is whether we want to "claim" a directory under /tmp (tempfile.gettempdir(), to be precise) for our own use (that seems a bit overkill tbh).
