### ISSUE TITLE
Usage FAQ section missing in 2.1.0 documentation

### ISSUE THREAD

**Issue by sagrawal-idrc** [matplotlib/matplotlib#9879]
### Bug report

**Bug summary**

I can see there is an excellent Usage FAQ section for 2.0.2 version, which can be accessed [here](https://matplotlib.org/faq/usage_faq.html). But it is missing from the Table of Contents for 2.1.0, [here](http://matplotlib.org/faq/). Is this intentional?

**Expected outcome**
Updated Usage FAQ section for 2.1.0.

**Matplotlib version**

  * Operating system: Any
  * Matplotlib version: 2.1.0

**Comment by tacaswell** [comment]
I believe that content (and then some) got moved to https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

**Comment by sagrawal-idrc** [comment]
Yes, it did. Thanks. I am closing the issue. Sorry for the clutter.

**Comment by afvincent** [comment]
@sagrawal-idrc No problem :).
