### ISSUE TITLE
polar limits not snapping to 0

### ISSUE THREAD

**Issue by snoopyhunter2** [matplotlib/matplotlib#9887]
### Bug report

In matplotlib 2.1 radial lines starting at _r = 0_ do not start at the origin of the graph, because the _r = 0_ circle has a non-zero radius. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt

r = [1.9, 2, 2.1]
theta = [0.5, 0.75, 1]

fig = plt.figure(figsize=(5, 5))
ax = plt.subplot(111, projection = 'polar')

for i in range(len(r)):
    ax.plot([0, theta[i]], [0, r[i]])
    
fig.savefig('phases.pdf', format = 'pdf')
```

**Actual outcome**

![phases](https://user-images.githubusercontent.com/34123302/33422174-0e4e2460-d5b5-11e7-8fa6-1f27a776a24f.png)
(converted to png)

**Expected outcome**

Outcome in matplotlib 2.0.2:

![outcome](https://user-images.githubusercontent.com/34123302/33422188-1a2d3a96-d5b5-11e7-9e9e-118263e7392f.png)
(converted to png)

**Matplotlib version**

  * Operating system: Ubuntu 16.04 / also on macOS 10.13.1
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.3
  * Other libraries: 

I use python from conda, latest update, and downgraded matplotlib to 2.0.2 to produce the second figure.

**Comment by QuLogic** [comment]
It's supposed to snap to 0 when all input is positive, but I think this bug may be caused by the additional automatic margins. It'll probably work with `ax.margins(0)`, and definitely should work if you set explicit limits.

**Comment by snoopyhunter2** [comment]
Putting ax.margins(0) before the plot command does indeed fix this issue, thanks!
