### ISSUE TITLE
using `xs=..., ys=...` on ax.scatter 2D raises error

### ISSUE THREAD

**Issue by LukeLR** [matplotlib/matplotlib#9898]
### Bug report

**Bug summary**

When using `ax.scatter(xs=..., ys=...)` instead of `ax.scatter(x=...,y=...)` for a 2D ax, an error is raised: "This is a programming error, please report to the matplotlib list". Although I don't think, this is a programming error, but obviously my own fault, I'll do as I'm told, be it to remove that misleading advice.

**Code for reproduction**

```python
fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111)
scplot = ax.scatter(xs=srpoints_2d[:,0],ys=srpoints_2d[:,1])
```

`srpoints_2d` being a sorted numpy array of 2d points derived by PCA from a make_swiss_roll:
```python
>>> srpoints_2d
array([[ -8.4791427 , -10.86581215],
       [ -9.07341921,  -9.94806175],
       [ -8.14223695, -10.81799673],
       ..., 
       [ 10.29483432,   7.52702298],
       [  8.58172214,   9.43094977],
       [  9.34940513,   8.66963623]])
```

**Actual outcome**

An error is raised:
```
/usr/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: Tried to set a label via parameter 'y' in func 'scatter' but couldn't find such an argument. 
(This is a programming error, please report to the matplotlib list!)
  This is separate from the ipykernel package so we can avoid doing imports until

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-133-49c1b41d09a7> in <module>()
      1 fig = plt.figure(figsize=(7,7))
      2 ax = fig.add_subplot(111)
----> 3 scplot = ax.scatter(xs=srpoints_2d[:,0],ys=srpoints_2d[:,1])

/usr/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1708                     warnings.warn(msg % (label_namer, func.__name__),
   1709                                   RuntimeWarning, stacklevel=2)
-> 1710             return func(ax, *args, **kwargs)
   1711         pre_doc = inner.__doc__
   1712         if pre_doc is None:

TypeError: scatter() missing 2 required positional arguments: 'x' and 'y'
```
And an empty plot is drawn.

**Expected outcome**

Anything else than "this is a programming error", as I guess, it is not.

**Matplotlib version**

  * Operating system: 4.13.12-1-ARCH
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): `inline`
  * Python version: 3.6.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: numpy, 1.13.3

**Comment by tacaswell** [comment]
Thanks for the bug report

The first thing you see is just a warning

https://github.com/matplotlib/matplotlib/blob/045c951cfc4154068b84fc7a28d5b379077b61c1/lib/matplotlib/__init__.py#L1798-L1809

which we should be reported if everything else worked as expected.  In this case, the pre-processing steps (which raised the warning) ran, but then it failed in the actually plotting code.

I do not think it is worth the complexity in the warning logic to suppress it in the case where other things go wrong.
