### ISSUE TITLE
Perfectly horizontal or vertical lines don't render to svg

### ISSUE THREAD

**Issue by amauboussin** [matplotlib/matplotlib#991]
Perfectly horizontal or vertical lines do not show up in svgs on my machine. Could be an issue with my specific setup, I am curious if anyone else can reproduce the issue.

Here is the code that causes the bug for me:

import pylab as plt
plt.plot([-1,1],[1,1]) #perfectly horizontal line does not render
plt.savefig('/Users/Andrew/Desktop/plot.svg', format='svg')

Here is a workaround I found:

import pylab as plt
plt.plot([-1,1],[1,1.001]) #not a perfectly horizontal line; renders 
plt.savefig('/Users/Andrew/Desktop/plot.svg', format='svg')

My environment:
Matplotlib 1.10 on Mac OS X 10.7 obtained from Enthought

**Comment by williamstein** [comment]
For what it is worth, I have different users (of SageMathCloud) who hit this bug *constantly* and report it to me.  If any matplotlib experts had an idea for a workaround (even something horrible and crappy like slightly peturb the line), I would be interested...

**Comment by slel** [comment]
One way to report bugs to Apple is to join their beta-tester program [1] and to test development versions of OS X. You get a "Feedback Assistant" app which lets you report bugs.

Last year I beta-tested OS X 10.10 Yosemite and I reported the Safari svg bug (horizontal and vertical lines not rendered) via the Feedback Assistant but that did not result in any fix.

I just re-enrolled to the beta-tester program for OS X 10.11 El Capitan and I'll report the bug again.

I created a page to display the bug [2]. Feel free to link to that page. Comments welcome.

[1] https://beta.apple.com/
[2] http://samuel.lelievre.free.fr/bug/safari-svg-bug-horizontal-vertical-line.html

**Comment by mdboom** [comment]
@slel: Thanks.

As for workarounds: @williamstein's suggestion to slightly perturb the line is interesting.  I suppose we should experiment with how much skew would be required and how badly that looks.  The downside, of course, is that degrades the plot for *everyone*.  (Unfortunately, I don't have access to a Mac this week to play -- anyone else is welcome to.)

We could attach a small amount of Javascript to the SVG that detects the browser and displays a warning (and a suggestion to switch to Chrome or Firefox) if it's one of the known broken browsers...

**Comment by slel** [comment]
The bug is fixed in WebKit. And thus in Safari 9.
This is confirmed by beta-testers of WebKit, of iOS 9, and of OS X 10.11 El Capitan.

**Comment by tacaswell** [comment]
I am strongly :-1: on adding skew to work around bugs in external libraries. 

Does this issue depend on line width?
