### ISSUE TITLE
Saving a figure inside the event loop with TkAgg lets NavigationToolbar disappear.

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#9914]
Saving a figure with TkAgg backend from within the event loop lets NavigationToolbar disappear on windows 8.1, python 2.7, matplotlib 2.1.

![mpltkaggsave](https://user-images.githubusercontent.com/23121882/33517451-b2ef9f78-d784-11e7-979f-49a160786230.gif)

The same happens if saving the figure from within the event loop using `plt.savefig()`.

**Comment by QuLogic** [comment]
Does this happen on the latest version? Since we disconnect the manager during save, it should not modify the displayed figure.

**Comment by ImportanceOfBeingErnest** [comment]
No, this must in fact been fixed at some point.
