### ISSUE TITLE
test_rcparams test errors on Wheel builders / Python >= 3.5

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#9925]
I'm seeing test errors for manylinux and OSX builds on Python 3.5 and 3.6:

https://travis-ci.org/MacPython/matplotlib-wheels/builds/311230442

They are of form:

```
 ERROR at setup of test_validator_invalid[validator35-\xff\xfedotted-ValueError] 
[gw1] linux -- Python 3.5.3 /venv/bin/python3.5

self = environ({'UNICODE_WIDTH': '32', 'HOME': '/root', 'TEST_DEPENDS': 'numpy==1.11.0 pytest mock sphinx pytest pytest-timeo... 'VIRTUAL_ENV': '/venv', 'MANYLINUX_URL': 'https://nipy.bic.berkeley.edu/manylinux', 'PYTEST_XDIST_WORKER_COUNT': '2'})
key = b'PYTEST_CURRENT_TEST'
value = b'matplotlib/tests/test_rcparams.py::test_validator_invalid[validator35-\\xff\\xfed\x00o\x00t\x00t\x00e\x00d\x00-ValueError] (setup)'

    def __setitem__(self, key, value):
        key = self.encodekey(key)
        value = self.encodevalue(value)
>       self.putenv(key, value)
E       ValueError: embedded null byte
```

I think they began here : https://travis-ci.org/MacPython/matplotlib-wheels/builds/308354479 - on the 28th November.

Any ideas?

**Comment by tacaswell** [comment]
I have seen this across a bunch of projects, it is something to do with either pytest starting to add null bytes in the middle of strings or python getting pickier about null bytes on a patch release.

**Comment by jklymak** [comment]
This isn't: https://github.com/matplotlib/matplotlib/pull/9878 ?

**Comment by anntzer** [comment]
looks like a https://github.com/pytest-dev/pytest/issues/2957 indeed, which has been fixed by pytest.  feel free to reopen if not.
