### ISSUE TITLE
Imshow: error when rescaling integer values

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#9937]
In matplotlib 2.1 the `BoundaryNorm` seems to be introducing inaccuracies on the edges of the boundaries. 
Consider the following code which maps a colormap of alternating colors to integer values of `numpy.arange`. Even numbers should be light grey, odd number darker. In some cases, depending on how many numbers we have, this mapping is broken. It thus seems that you cannot expect  a value `x[n]` to be mapped to the `n`th bin.

```
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import numpy as np

ns = [16,20,26,36]

fig, axes = plt.subplots(nrows=len(ns), figsize=(7,3))

for i,ax in enumerate(axes):
    example_data = np.array([list(range(ns[i]))])
    cmaplist = ["#eeeeee", "#aaaaaa"]*(ns[i]//2)
    
    norm = colors.BoundaryNorm(np.arange(0,len(cmaplist)+1), len(cmaplist))
    cmap = colors.ListedColormap(cmaplist, 'mycmap', len(cmaplist))
    #cmap = colors.LinearSegmentedColormap.from_list('mycmap',cmaplist, len(cmaplist))
    
    im = ax.imshow(example_data, cmap=cmap, norm=norm, aspect="auto")
    ax.set_yticks([])
plt.tight_layout()
plt.show()
```

Output of the above code in matplotlib 2.1 (see second line, value 15, third line value 1, fourth line value 2 and 29)
![image](https://user-images.githubusercontent.com/23121882/33629500-90cd1132-da04-11e7-9cff-a01aecb864d4.png)

Expected output, achieved with matplotlib 2.0.2:
![image](https://user-images.githubusercontent.com/23121882/33629424-49a0b142-da04-11e7-9a8c-8f78fe8ca1bd.png)

Note that it does not matter whether a ListedColormap or a LinearSegmented colormap is used.  
Also note that the expected behaviour can be achieved in matplotlib 2.1 by subtracting a small value from the bin list. E.g.

`norm = colors.BoundaryNorm(np.arange(0,len(cmaplist)+1)-1e-6, len(cmaplist))`

will give the desired plot, while subtracting `1e-7` or smaller shows the issue from above. 

[Issue reproduced with python 2.7, matplotlib 2.1 on Windows 8; issue not present with python 2.7, matplotlib 2.0.2]

**Comment by efiring** [comment]
I can reproduce your plot, but I don't see the problem in the output of the norm or of the cmap acting on the norm.  Consider the second example, with 20 points:
```
In [14]: norm = colors.BoundaryNorm(np.arange(21), 20)

In [15]: dat = np.array([list(range(20))])

In [16]: cmap = colors.ListedColormap(cmaplist, 'mycmap', 20)

In [17]: norm(dat)
masked_array(data =
 [[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19]],
             mask =
 [[False False False False False False False False False False False False
  False False False False False False False False]],
       fill_value = 999999)

In [18]: cmap(norm(dat))
array([[[ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ],
        [ 0.93333333,  0.93333333,  0.93333333,  1.        ],
        [ 0.66666667,  0.66666667,  0.66666667,  1.        ]]])
```

**Comment by efiring** [comment]
@tacaswell, since the cmap and norm work as expected, I suspect this behavior change is an unwanted side-effect of the input rescaling operation prior to resampling.

**Comment by jklymak** [comment]
This is a relatively typical case of expecting something when data exactly hits a boundary.  If you do 
```
    norm = colors.BoundaryNorm(np.arange(-0.5,len(cmaplist)+0.5), len(cmaplist))
```
where the boundaries are between the expected data values, then you get the expected result.  I don't think we are planning to revert 12c27f3 any time soon.

OTOH hand, if you use the proposed norm, if you do 

```
    im = ax.imshow(example_data, cmap=cmap, norm=norm, aspect="auto", interpolation_stage='rgba')
```
then you also get the expected behaviour. 

I'm gong to close this as having two reasonable work arounds.
