### ISSUE TITLE
Deprecate Axes as a valid pyplot.axes() argument type

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#9940]
### Change Request

In continuation of a discussion in #9930:

## Deprecate Axes as a valid pyplot.axes() argument type

This use-case is just a hidden call to `sca()`. First, `sca(ax)` should be preferred over `axes(ax)` for clarity and. Second, this use of axes has a total diffent semanics. `axes()` creates a new Axes on the current figure. Whereas axes(ax) just makes the given axes current. As a side effect this may even change the current figure.

## Breaking Change 
This is an API-beaking change and requires a proper deprecation path.

If someone can give me a hint, how deprecations are handled in matplotlib, I will provide a pull request.

**Comment by anntzer** [comment]
You probably want to use cbook.warn_deprecatedn (grep for it) + add an entry in the api_changes folder.

**Comment by timhoffm** [comment]
PR is merged.
