### ISSUE TITLE
toolmanager_sgskip + tkagg example couples "GroupHide" toggle with Pan and (second) Zoom

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9943]
### Bug report

**Bug summary**

When running the examples/user_interfaces/toolmanager_sgskip example with the backend forced to tkagg (do so by editing the matplotlib.use line in the source), triggering the "show" tool also triggers the "Pan" tool and the (second) "Show" tool.

**Code for reproduction**

as described above.

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

tools should not be coupled

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): tkagg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
When I run the example (with tkagg as backend), even at startup, without clicking anything, the three tools I mention are all pressed.  Clicking on `show` to untrigger or trigger it also changes the state of the other two.

**Comment by fariza** [comment]
What do you mean "the second show tool"
here is how I see as soon as I run the example with the tkagg backend (from master)
![screenshot from 2017-12-06 13-08-50](https://user-images.githubusercontent.com/1490153/33677427-be3d8976-da86-11e7-8de6-9fd3488df671.png)
The only "pressed" tool is "show"

**Comment by fariza** [comment]
can you change `default_toggled = True` to `default_toggled = False` and see if it changes the state of the `show` button when starts

**Comment by anntzer** [comment]
not toggled by default anymore, but all three still get toggled simultaneously.

**Comment by fariza** [comment]
The only different thing is python 3.6.
Let me install it and give it a try

**Comment by fariza** [comment]
I installed python3.6 and I can confirm the bug. :(
Does it happen on gtk3agg?

**Comment by anntzer** [comment]
nope

**Comment by fariza** [comment]
the problem seems to be inside tkinter. At first sight, I don't see anything wrong. 
I am only toggling one button, but somehow the others get toggled to.
I will try to put a tkinter only sample and see if I'm able to reproduce the problem

**Comment by fariza** [comment]
Some references to the bug
https://groups.google.com/forum/#!topic/comp.lang.python/_7pQo37FYYY
https://bugs.python.org/issue25684
https://bugs.python.org/issue29402

I will play with the button variables to see if I can fix it that way

**Comment by fariza** [comment]
@anntzer can you check the fix https://github.com/matplotlib/matplotlib/pull/9962
