### ISSUE TITLE
test input data is not existed for demo

### ISSUE THREAD

**Issue by wooheaven** [matplotlib/matplotlib#9955]
### Bug report

**Bug summary**
test input data is not existed for demo : https://github.com/matplotlib/matplotlib/blob/baa5f8e2294cbbe96258437447b09d0587f44475/examples/mplot3d/custom_shaded_3d_surface.py#L17

Link or save this as alternatives :
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/sample_data/jacksboro_fault_dem.npz

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by dstansby** [comment]
I've just tried running that example, and it works fine for me. Is running it giving you an error?

**Comment by anntzer** [comment]
Closing for lack of confirmation or activity.  Feel free to request a reopen with more information.
