### ISSUE TITLE
subplots ignores figsize argument

### ISSUE THREAD

**Issue by fonnesbeck** [matplotlib/matplotlib#9965]
`subplots` does not apply passed `figsize` argument to figure. Here is a screen shot:

![](http://d.pr/i/4atQtQ+)

Here is a call without any of the supporting code:

![](http://d.pr/i/20Xfnc+)

**Matplotlib version**
  * Operating system: macOS 10.3.2
  * Matplotlib version: 2.0 
  * Matplotlib backend: Jupyter inline
  * Python version: 3.6.1
  * Jupyter version (if applicable): 1.0

**Comment by QuLogic** [comment]
The `inline` backend resizes the figure to fit in the browser, which comes from IPython/Jupyter. Try the `notebook` backend instead for interactivity and less sizing magic.
