### ISSUE TITLE
Slightly misleading  errorbar docs that interferes with attempt to animate errorbar

### ISSUE THREAD

**Issue by RDeRenzi** [matplotlib/matplotlib#9973]
In short I would like to animate an errorbar plot, letting it iterate in time over datasets, like in a few canonical [plot](https://matplotlib.org/2.0.0/examples/animation/simple_anim.html) or [histogram]( https://matplotlib.org/2.0.0/examples/animation/histogram.html) examples. My best attempt (below) produces the following error `AttributeError: 'tuple' object has no attribute 'set_animated'. Please consider this as a request in support of  [better docs](https://github.com/matplotlib/matplotlib/issues/9967)

 
**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as P
import matplotlib.animation as animation

def animate(i):
    y = np.sin(x+i/10.0)
    line.set_ydata(y)
    segs = [np.array([[q,w-a],[q,w+a]]) for q,w,a in zip(x,y,yerr[i%2]*np.ones(x.shape[0]))]
    ye[0].set_segments(segs) # path.Path(verts, codes)
    return line, ye, # @jklymak solution is to substitute with: "return line, ye[0],"  or "return [line]+list(ye)"

def init():
    line.set_ydata(np.nan * np.ones(len(line.get_xdata())))
    segs = [np.array([[np.nan,np.nan],[np.nan,np.nan]]) for q,w,a in zip(x,y,yerr[0]*np.ones(x.shape[0]))]
    ye[0].set_segments(segs) # path.Path(verts, codes)
    return line, ye, # @jklymak solution is to substitute with: "return line, ye[0],"  or "return [line]+list(ye)"

fig, ax = P.subplots()
x = np.linspace(0, 2*np.pi, 256)
y = np.sin(x)
line, xe, ye, =  ax.errorbar(x, y, yerr=0.1) 
yerr=[0.1,0.2]
ax.set_xlim(x[0],x[-1])
ani = animation.FuncAnimation(fig, animate, np.arange(1, 200), init_func=init,
    interval=25, blit=True)
P.show()
```
(saved as errornimate.py)

**Actual outcome**
python errornimate.py
Traceback (most recent call last):
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/animation.py", line 1081, in _start
    self._init_draw()
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/animation.py", line 1801, in _init_draw
    a.set_animated(self._blit)
AttributeError: 'tuple' object has no attribute 'set_animated'
Traceback (most recent call last):
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/animation.py", line 1368, in _handle_resize
    self._init_draw()
  File "/home/roberto.derenzi/.python3/lib/python3.5/site-packages/matplotlib/animation.py", line 1801, in _init_draw
    a.set_animated(self._blit)
AttributeError: 'tuple' object has no attribute 'set_animated'
```

**Matplotlib version**
  * Operating system: linux 
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2
 
software installed by pip

**Comment by jklymak** [comment]
I get:

```
 File "testanimerror.py", line 15, in init
    line.set_color(color)
NameError: name 'color' is not defined
```

So I don't think your example is [SSCCE](http://sscce.org)

Documenting things is hard....

**Comment by jklymak** [comment]
`ye` is a tuple.  I'm not sure why its a tuple, but it is.  The docs say it will be a list, so I guess you have a small complaint: https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.errorbar.html

Lots of different ways to fix this.  returning `line, ye[0]` is the easiest.  You could also return `[line + list(ye)]` if you want to keep the option open for `ye` to have more than one element.

**Comment by RDeRenzi** [comment]
Dear Jody, 
you answered to me privately

> ye is a tuple. I'm not sure why its a tuple, but it is. The docs say it will be a list, so I guess you have a small complaint: https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.errorbar.html

Yes, will that be passed on?

> Lots of different ways to fix this. returning line, ye[0] is the easiest. You could also return [line + list(ye)] if you want to keep the option open for ye to have more than one element.

Thanks a lot, I didn't realize it was so simple. Your first suggestion works, perfectly. The second doesn't, I am not sure I understand what you mean by it (but one solution is enough for me). I included it in the code above,  perhaps others find it useful

**Comment by jklymak** [comment]
Sorry.  Typo:   `[line] + list(ye)`  The first makes line a list, and the second makes `ye` a list.  Adding them concatenates the lists....

**Comment by tacaswell** [comment]
@RDeRenzi Sorry you are having issues.  

We are always happy to see PRs to update / clarify / correct the documentation!  Could you take a crack at adjusting the errobar docs to something that would have made it easier for you to understand this?

**Comment by jklymak** [comment]
@tacaswell  I think the issue is that it says it will return a list, but it actually returns a tupple.
