### ISSUE TITLE
ax.set_aspect triggers useless warnings

### ISSUE THREAD

**Issue by gauthe** [matplotlib/matplotlib#9976]
Hello,

### Bug report
ax.set_aspect triggers a seemingly useless warning when its argument is a numpy.float64:

**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([0],[0])
ax.set_aspect(float(1))    # this is fine
ax.set_aspect(np.float64(1))  # triggers warnings
```

**Actual outcome**
```
/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py:1292: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aspect == 'normal':
/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py:1297: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aspect in ('equal', 'auto'):
```

**Expected outcome**

I see little reason to treat differently float and numpy float and these warnings seem useless. Note that the actual result is fine.

The warnings appear for python 2.7 and matplotlib 2, I tested with
- Debian official python, Python 2.7.13, matplotlib 2.0.0, backend = TkAgg
- Anaconda python, Python 2.7.14, matplotlib 2.0.2,  backend = WebAgg

**Comment by jklymak** [comment]
This warning doesn't come up in Master, so I imagine this has been fixed...  Thanks for the report and feel free to re-open if you think there is a current bug.
