### ISSUE TITLE
Error shows when I import matplotlib after installation

### ISSUE THREAD

**Issue by Ralf33** [matplotlib/matplotlib#9977]
I use command "pip install matplotlib"  and "pip3 install matplotlib " to install it successfully. but i have always this error "ModuleNotFoundError: No module named 'matplotlib'"

when i write "pip3 install matplotlib" in command prompt it shows me "requirement already satisfied"

I use python 3.6 (32 bit) on windows 7 and PyCharm

My code is: 

```
from random import seed
from random import random
from matplotlib import pyplot
from pandas.tools.plotting import autocorrelation_plot
seed(1)
random_walk= list()
random_walk.append(-1 if random()<0.5 else 1)
for i in range(1,1000):
    movement= -1 if random() < 0.5 else 1
    value= random_walk[i-1]+ movement
    random_walk.append(value)
autocorrelation_plot(random_walk)
pyplot.show()
```

**Comment by WeatherGod** [comment]
How did you install python? Is it possible that you have multiple python
environments installed?

**Comment by Ralf33** [comment]
at the beginn i installed python from https://www.python.org/ and Anaconad at th same time. after that i deleted both and now i have just one python from https://www.python.org/ with this problem

**Comment by WeatherGod** [comment]
It is entirely possible that not everything got deleted. There are many
important directories that might have escaped your clearing out.

**Comment by jklymak** [comment]
Strongly suggest just installing from anaconda.

**Comment by dstansby** [comment]
Can you post the output of `import matplotlib.pyplot` in a python session?

**Comment by Ralf33** [comment]
The problem is solved cauz some of python files were not deleted. I deleted everything again and installed anaconda

**Comment by jklymak** [comment]
Great!
