### ISSUE TITLE
Axis limits are set badly with small values in scatter().

### ISSUE THREAD

**Issue by naught101** [matplotlib/matplotlib#9979]
I'm not sure if this is related to https://github.com/matplotlib/matplotlib/issues/7413

### Bug report

Example:

```py
%pylab
x = randn(1000) / 1e5
y = randn(1000) / 1e5
scatter(x, y)
```
produces this:
![figure_1](https://user-images.githubusercontent.com/167164/33868162-750d413c-df55-11e7-9d9b-79107cb34b34.png)

It should really produce something more like this:

![figure_1-2](https://user-images.githubusercontent.com/167164/33868215-caa17b5e-df55-11e7-875b-7d79a8afa98a.png)

There's not an obvious way to do this, other than manually getting the min/max x and y values and adding a little bit and using `ax.set_x/ylim()`

Using conda on kubuntu:

```
matplotlib                2.1.0            py36hba5de38_0  
python                    3.6.3                h0ef2715_3  
```

**Comment by jklymak** [comment]
Yes, it's scatter's specialness.  I bet plot doesn't do that.

**Comment by naught101** [comment]
No, plot() doesn't do that.

**Comment by Lusura** [comment]
I have been trying to see why scatter is behaving in a different way. I realized that some of the code used by scatter is in _path.h. The get_path_collection_extents method gets called from path.py to figure out the dimensions to give to the bounding box. I would be interested in pursuing this further, but I am just not sure how to debug the c++ part of the library, any tips would be appreciated.

**Comment by tacaswell** [comment]
@Lusura My knee jerk reaction is that the bug is not in the c++ layer, but in how we massage the returns of those calls in python.

One of the things scatter tries to take into account is that the size of the markers can vary in size which may be related to this.

Agree is in related to #7413.

**Comment by jzwinck** [comment]
Here's a trivial demo which doesn't do what anyone would expect: https://stackoverflow.com/questions/53536688/matplotlib-automatically-sets-insane-datetime-x-axis-range

The code:
```
import matplotlib.pyplot as plt
import pandas as pd
plt.scatter(pd.to_datetime(['10:00', '11:00', '12:00']), [30, 40, 50])
plt.show()
```
[The result](https://i.stack.imgur.com/6iTxS.png)

Summary: The simplest possible scatter plot of a time series on a single date chooses nonsensically huge x bounds, making the plot useless for visualization by default.

**Comment by anntzer** [comment]
AFAICT this (both examples) has been fixed by https://github.com/matplotlib/matplotlib/pull/13642.  Feel free to reopen if something is missing.
