### ISSUE TITLE
```'module' object has no attribute 'subplots'``` when importing with ```__import__```

### ISSUE THREAD

**Issue by KOLANICH** [matplotlib/matplotlib#9982]
### Bug report

When importing with ```__import__``` there are problems.

**Code for reproduction**

```python
plt=__import__("matplotlib.pyplot")
plt.subplots()
```

**Actual outcome**

```
AttributeError: 'module' object has no attribute 'subplots'
```
Some other properties work.

**Expected outcome**

Must work.

**Matplotlib version**
  * Operating system: Win XP
  * Matplotlib version: 2.1.0
  * Matplotlib backend: TkAgg
  * Python version: 3.4.4

**Comment by jenshnielsen** [comment]
I dont think that's how `__import__` works

As far as i can understand from https://docs.python.org/3/library/functions.html#__import__
plt will be the name of the top level module. A quick test confirms that
```
>>> plt=__import__("matplotlib.pyplot")
>>> plt.pyplot.subplots
<function subplots at 0x10cb22b70>
```

**Comment by jenshnielsen** [comment]
Specifically it says
```
spam = __import__('spam.ham', globals(), locals(), [], 0)

Note how __import__() returns the toplevel module here because
 this is the object that is bound to a name by the import statement.
```

**Comment by KOLANICH** [comment]
Thank you for the comment. Sorry for that.

**Comment by wanghaonanlpc** [comment]
import matplotlib.pyplot as plt

**Comment by Faisal-Shahrani** [comment]
I have try to import it with every ways , but it didn't work idk why 
**(module 'matplotlib' has no attribute 'subplots')** 

I tried 
from matplotlib import * 
and other ways and still doesn't work

**Comment by jklymak** [comment]
@Faisal-Shahrani please discuss at discourse.matplotlib.org.  However matplotlib indeed has no method subplots.  Please also read out documentation.

**Comment by Faisal-Shahrani** [comment]
@jklymak  thx <3
