### ISSUE TITLE
ImportError: ZLIB_1.2.9 not found

### ISSUE THREAD

**Issue by seanysull** [matplotlib/matplotlib#9983]
### Bug report

**Bug summary**
 I'm not sure if this is a matplotlib issue, please feel free to correct me and close this issue if it should be elswhere. I am using a Jupyter notebook and Pandas and tried to plot using the Pandas built in however, it failed. I have tried the same in a different computer with different OS (Windows) but smiliar everything else and it works as expected.

**Code for reproduction**

```python
# Paste your code here
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt

s = pd.Series([1,2,3,4,5,6,7,8,9])
s.plot()
```

**Actual outcome**

```
# If applicable, paste the console output here
/opt/conda/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

# many more imports from matplotlib then finally

/opt/conda/lib/python3.6/site-packages/matplotlib/mathtext.py in <module>()
     60 
     61 import matplotlib.colors as mcolors
---> 62 import matplotlib._png as _png
     63 
     64 ####################

ImportError: /opt/conda/lib/python3.6/lib-dynload/../../libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/conda/lib/python3.6/site-packages/matplotlib/../../../libpng16.so.16)

```

**Expected outcome**
A Plot.

**Matplotlib version**

  * Operating system: Ubuntu 16.04.3 LTS \n \lconda LIST
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.3 (conda-forge)
  * Jupyter version (if applicable): 4.4.0
  * Pandas version: 0.19.2

**Comment by QuLogic** [comment]
How did you install Matplotlib?

**Comment by seanysull** [comment]
Anaconda was installed on the server I am using already...

**Comment by QuLogic** [comment]
If you didn't build from source or a wheel, then this is probably something you need to report to anaconda or conda-forge (depending on where Matplotlib is from).

**Comment by seanysull** [comment]
Ok.

**Comment by agarnitin86** [comment]
I am also facing same issue.. Any resolution?
