### ISSUE TITLE
Contours are not removed correctly when using clabel with manual

### ISSUE THREAD

**Issue by tillahoffmann** [matplotlib/matplotlib#9988]
### Bug report

**Bug summary**

Contours created using `pyplot.contour` are not correctly removed when labelling the contours using`plt.clabel` invoked with `inline=True` and manual positions.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt

x = np.linspace(-1, 1)
xx, yy = np.meshgrid(x, x)

fig, axes = plt.subplots(1, 2, True, True)

manual = None
for ax in axes:
    cs = ax.contour(x, x, xx ** 2 + yy ** 2)
    clabels = plt.clabel(cs, manual=manual)
    manual = [label.get_position() for label in clabels]
```

**Expected outcome on the left, actual outcome on the right**

![image](https://user-images.githubusercontent.com/966348/33913033-128b6e54-df90-11e7-88b5-7ac859334edf.png)

**Matplotlib version**

  * Operating system: Linux 273ceb986a84 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 GNU/Linux
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: numpy (1.13.3)

All libraries were installed using pip in a docker image derived from `python:3`.

**Comment by jklymak** [comment]
Thanks for the nice test.  Interestingly its backend dependent: MacOS is OK, though different than the outplacement; Qt5Agg is worse than what you show above.  I'd try Qt5Cairo, but its not merged yet :-(

**Comment by tillahoffmann** [comment]
Interesting. I'm ultimately interested in rendering to PDF. Do you think using the MacOS backend first and then using `fig.savefig('/path/to.pdf')` could do the trick?

**Comment by jklymak** [comment]
Oddly that does seem to do the trick.  But....  This is still a bug.

**Comment by jklymak** [comment]
... a mercifully one-line bug...  See #9989

**Comment by jklymak** [comment]
![figure_1-1](https://user-images.githubusercontent.com/1562854/33913965-ca430a42-df50-11e7-9f1b-ae2bae0f7d40.png)

**Comment by tillahoffmann** [comment]
:tada: that was speedy! Thank you!
