### ISSUE TITLE
Remove badges from website side bar

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#9996]
### Website Change Request

I propose to remove the badges (numfocus, depsy, travis-ci) from the side bar of the website.

![grafik](https://user-images.githubusercontent.com/2836374/33958944-3c5dc5fe-e046-11e7-8aa7-b1d2912468e0.png)

- They are not relevant for the average user, but only for developers.
- They clutter the site, and in particular on pages with long TOCs, they take up valuable space.

IMO, it's sufficient to have the badges on the github page (and there we also have more than just the three above).

If you really do want the badges on the website as well, put them in a line at the bottom (preferred) or top (less preferred, but still ok) on the main page only.

I can provide the appropriate pull request, when we've agreed what to do.

**Comment by tacaswell** [comment]
The depsy one is already gone on master (see http://matplotlib.org/devdocs/) and the NF badge should definitely go in the readme on github!

I'm 50/50 on removing the NF badge and the travis badge from the main page.

**Comment by efiring** [comment]
Having a link to Numfocus on the front page is OK, but there should be no badges in the sidebar.  The logical place for the Numfocus link would be not a badge but the big image in the lower right-hand side of the front page.  Can that image serve as the clickable element?
